### ISSUE TITLE
Friendica does not seem to talk to Hubzilla

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10012]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

I tried to connect to myself from hubzilla to friendica, hubzilla finds me on friendica and shows my profile picture with a connect button but connect fails, but I can connect to users on other platforms from hubzilla fine.

Likewise friendica does not even find me on hubzilla.

I tried sending e-mail from friendica to my hubzilla account, does not arrive.

I tried sending e-mail from my hubzilla account to friendica, does not arrive.

### Platform Info

Friendica Version:

Friendica 'Red Hot Poker' 2021.03-dev - 1406 
Friendica Source: 
Github
PHP version:
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by annando** [comment]
Please provide more information. There is no general communication issue with Hubzilla, so I guess it is based upon some configuration thing.

**Comment by 4nanook** [comment]
What more information can I provide that would help?  I suspect though this is on the Hubzilla side.  I have been able to e-mail many other people from friendica fine and make contacts on other sites.  But none of the contacts that hubzilla offers are on friendica, search doesn't show up any friendica sites.

**Comment by SpcCw** [comment]
@4nanook - it works fine on my installation, I can talk to the latest Hubzilla and vice versa.

You probably checked for it already but usual problems I have with Hubzilla are:

- protocol plugin in Hubzilla disabled or "stuck" (helps to disable/enable it in admin panel), PubCrawl in this case.
- Hubzilla account  uses nomadic identity (clones). These kind of work some of time but not always. I suppose only Hubzilla itself can handle these accounts correctly. In this case it helps to figure out their other cloned addresses and add them all. Some will fail, some won't - and then it will work.

If any of this isn't your case then try to figure out which side fails. I.e. is it your Friendica server unable to talk to all Hubzillas or is it particular Hubzilla Friendica servers can't talk to? Does problem affect entire server or some accounts only?

**Comment by 4nanook** [comment]
I can't find any Plugins or configuration for them in the Admin menu or elsewhere.

**Comment by SpcCw** [comment]
@4nanook - turns out they are called addons, not plugins. Go to Admin - Addons (/admin/addons/) and make sure PubCrawl is enabled. If it is enabled, try disabling and re-enabling it.

After that go to your channel settings: top right hamburger button - Add Apps (/apps/) and make sure ActivityPub Protocol is among installed apps, if not then install it from "Available Apps" section.

After that Hubzilla should work with AP networks, Friendica included. Same with Diaspora protocol.

**Comment by 4nanook** [comment]
I have resolved this issue.  There is a beta worker that is included in the addon's in the hubzilla distribution.  It doesn't work properly.  I removed it and now hubzilla and friendica talk to each other properly.
