### ISSUE TITLE
PHP Notice in job runner after update

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10013]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

Job runner issues an PHP notice indicating a problem after applying current updates to development release.

### Steps to Reproduce

Apply all the current updates to the development release.
1.  step one
2.  step two
3.  step three

Actual Result:

Following error from job runner:
PHP Notice:  Trying to access array offset on value of type bool in             /misc/www/friendica/src/Protocol/ActivityPub/Transmitter.php on line 890        PHP Notice:  Trying to access array offset on value of type bool in             /misc/www/friendica/src/Protocol/ActivityPub/Transmitter.php on line 890        
Expected Result:
Error free operation.

Job runner should finish without errors.
### Platform Info

Friendica Version:

     Friendica 'Red Hot Poker' 2021.03-dev - 1406 
Friendica Source: 
Github
PHP version:
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by MrPetovan** [comment]
Thank you for the report, as the message indicates, this is a PHP Notice that we'd like to centralize in the following issue: https://github.com/friendica/friendica/issues/9749

Please post similarly categorized messages in the corresponding issue next time.

**Comment by 4nanook** [comment]
I did a search for "PHP Notice" before creating this bug report and that
issue did not come up in the search.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
It's not a big deal for this one, now you know for the potential next.

**Comment by 4nanook** [comment]
One of the reasons I use github is that my own memory can at times be
lacking.  Don't know if there is a way to include a keyword or something so
that it comes up in the search.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
The issue I pointed you to is the 7th in this search page: https://github.com/friendica/friendica/issues?q=is:issue+is:open+php+notice

**Comment by MrPetovan** [comment]
Thank you for copying the error message over there!

Moved to https://github.com/friendica/friendica/issues/9749#issuecomment-793282258, closing here.

**Comment by 4nanook** [comment]
I guess my eyesite is going too.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
