### ISSUE TITLE
Allow admin to set default chmod for downloaded files (e.g. to /proxy/)

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#10020]
What I wish for is a feature that allows admins to set `chmod` to their needs (PHP has a proper function for that) in their instances as not all installation environments are the same, some servers create files with 0600, but the web server cannot read it and end with a 403 response.

This is the case for my instance, where all files in `/proxy/` get created with `chmod 0600` but I definitely need `0640` instead. A workaround here is to have a [cronjob](https://f.haeder.net/chmod.sh) running which fixes the file permissions then.

Maybe something like `system.default_file_permissions=0640` would be nice. Still then people switch to more stricter access rights, if they desire. `0644` is maybe to broad (world-wide readable).

**Comment by MrPetovan** [comment]
Wait, the web server user creates files it can't read afterwards? Or are you having different users creating and reading the files? If yes, how?

**Comment by Quix0r** [comment]
Yes, it seems so. Every new file the `Module\Proxy` class is being creating is with `0600` and `vuXXXX.vuXXXX` and not `vuXXXX.www-data`.

**Comment by MrPetovan** [comment]
Is `vuXXXX` intended to run the web server?

**Comment by Quix0r** [comment]
Yes, the pool for Friendica. And I just noticed that `group` was set to the `vuXXXX` and not `www-data` in /etc/php/7.3/fpm/pool.d/friendica.conf (and others). I set it to `www-data` now. But I guess that's only half the effort.

**Comment by MrPetovan** [comment]
Is nginx running with a user and PHP-FPM with another?

**Comment by Quix0r** [comment]
Yes, Apache runs under a default user `www-data`. That's why all `vuXXXX` users are in the `www-data` group. I have uploaded a PR for this ticket.
