### ISSUE TITLE
DB error 1064 - syntax error near 'WHERE ... %d AND ...'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10032]
- [X] I have searched open and closed issues for duplicates

SQL syntax error found in my log.

@tobiasd discovered where this happens: "On the events page, if you click on an calendar entry the details view should be loaded. On current 2021.03-RC this is not working..."

### Bug Description
```
index [ERROR]: DB Error {"code":1064,"error":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%d AND `event`.`id` = %d' at line 1","callstack":"DBA::p, Event::getListById, events_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent, Page::run","params":"SELECT `event`.*, `post-user-view`.`id` AS `itemid` FROM `event` LEFT JOIN `post-user-view` ON `post-user-view`.`event-id` = `event`.`id` AND `post-user-view`.`uid` = `event`.`uid` WHERE `event`.`uid` = %d AND `event`.`id` = %d "} - {"file":"Database.php","line":662,"function":"p","uid":"01b870","process_id":3374711}
```

### Platform Info

Friendica Version:
2021.03-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
Huh, that's a remainder from the previous parameter interpolation.

**Comment by AlfredSK** [comment]
Hah! Added a discovery of @tobiasd about where it occurs and what happens in the UI.
