### ISSUE TITLE
Tooltip message of the elevator is not marked as translatable

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#10047]
### Bug Description

The tooltip "back to top" is not marked as translatable here:

https://github.com/friendica/friendica/blob/2021.03-rc/view/theme/frio/php/default.php#L152
https://github.com/friendica/friendica/blob/2021.03-rc/view/theme/frio/php/standard.php#L73

Additionally, it should be displayed as sentence case "Back to top" instead of lowercase "back to top".

**Comment by MrPetovan** [comment]
Good catch, thanks!
