### ISSUE TITLE
friendica removes link from tweet

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10055]
Friendica is removing a link from a Tweet. Maybe related to link preview but not sure.

Tweet with link after `➤ Verlauf:`: https://twitter.com/Wahlrecht_de/status/1372454606479970307
<img width="591" alt="tweet" src="https://user-images.githubusercontent.com/5708172/111606472-88eec580-87d7-11eb-9f9d-b2f7b6d10c9b.png">

On Friendica link preview is added but **link is removed from post**:
https://pirati.ca/display/a6551d712134c6f446a1c2491a31dbc2d9a94013
<img width="647" alt="friendica post" src="https://user-images.githubusercontent.com/5708172/111606954-14685680-87d8-11eb-9aa1-0aa12164c646.png">

Actual Result: Link gone.

Expected Result: Don't alter imported posts.

This is Friendica, version 2021.03-rc that is running at the web location https://pirati.ca (theme: frio). The database version is 1412/1412, the post update version is 1400/1400.

**Comment by MrPetovan** [comment]
It is related to the link preview. I thought it should happen only at the end of the post though.

**Comment by annando** [comment]
Yeah, AFAIK this is an automatic to remove unneeded duplicates.

**Comment by MrPetovan** [comment]
Personal note: https://friendica.mrpetovan.com/display/a6551d715865ac7446c59b1cfd796760eeed06c5

**Comment by annando** [comment]
I guess this is now fixed with the new attachment management.

**Comment by MrPetovan** [comment]
I haven't seen any instance of this issue lately, I'm cautiously optimistic.

**Comment by MrPetovan** [comment]
Closed by #10214
