### ISSUE TITLE
Folders in the friendca/proxy have 0777 permission

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10053]
Is that normal? Is that safe? I did nothing manually to change these permissions so I am wondering.

**Comment by MrPetovan** [comment]
Yes and yes. The proxy folder only contains images retrieved from public remote locations for local serving. So there's nothing confidential about them.

**Comment by tio-trom** [comment]
I understand so it should remain as such. Thanks!

**Comment by tio-trom** [comment]
A followup. It is the same scenario for itemcache right? I have that in tmp/domain

**Comment by MrPetovan** [comment]
It seems so, although I'm less familiar with this feature.
