### ISSUE TITLE
Storage move not working

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#10062]
- [X] I have searched open and closed issues for duplicates

### Bug Description

If the storage backend is changed and then the move is done for both by `bin/console storage move -n 500` many photos are lost, observed on profile pictures for example. 
This problem happened on my [node](https://friendica.utzer.de) and on the node of [Hans](https://federate.hopto.org/profile/hans_w). 
### Steps to Reproduce

Switch the storage from Database to Filesystem or vice versa and then start the move, it will loose some photos. @fabrixxm said it is probably not reversible, but Hans said moving it again back solved his problems. For me this did not work, but also between the moves there were 14 days or so. 

Actual Result:

see above

Expected Result:

move finishes, not pictures/files get lost. 

### Platform Info

Friendica Version: 
This is Friendica, version 2021.03-rc that is running at the web location https://friendica.utzer.de. The database version is 1412/1412, the post update version is 1400/1400.

Friendica Source: 
git

PHP version:
PHP 7.4.16

SQL version:
mysql  Ver 15.1 Distrib 10.5.9-MariaDB

**Comment by utzer** [comment]
Maybe the use of this function should be discouraged for now.

**Comment by AlfredSK** [comment]
Was the move complete? I remember when I did the move from db to filesystem I had to run the move command several times until ALL items were moved successfully.

**Comment by hansw-nlo** [comment]
My findings in this:

I moved the storage to the Filesystem and then moved the Photo's there too. After the cache was deleted everything besides the profile pictures was visible. I even noticed that my own profile picture was really gone.

I moved it back to the database and everything worked like expected again.

Done this exercise twice with the same result:

System:
PHP
--
upload_max_filesize | 12M
post_max_size | 8M
memory_limit | 128M
MySQL / MariaDB
max_allowed_packet | 16777216

This is hosted on a Raspberry pi that has a connection to a SSD storage where both the files and the database is stored. 

Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

What I described in the forums are two possible fixes for this.

1. Have a tinyint to identify if a picture is a local profile picture (or from one of your connections)
2. Adjust the location in the templates (I assume)

I am able to test any solutions when needed.

**Comment by annando** [comment]
Somewhere I heard something about storage and the `config_adapter` adapter setting. Have you set it to `jit` or `preload`.

**Comment by utzer** [comment]
@annando what is this?

**Comment by AlfredSK** [comment]
The config adapter. JIT is the default. Preload is maybe, possibly a little bit faster. It can be configured which one the system is using in the local.config.php.

**Comment by annando** [comment]
If you haven't changed this, then just ignore my question :-)

**Comment by utzer** [comment]
> Was the move complete? I remember when I did the move from db to filesystem I had to run the move command several times until ALL items were moved successfully.

Yes, now it works fine, I can move between both engines with a few minutes. Before there was some bug and it move the same files over and over again or something like this, but that bug was fixed few days ago. 


I did move again from Database to Filesystem, it did not bring back the missing profile photos, and I don't recall if I had more photos in that admin account there.

**Comment by hansw-nlo** [comment]
That is more or less the same experience I have.

**Comment by hansw-nlo** [comment]
So if we would be able to find a way to get the profile photos on the filesystem then it might be solved

**Comment by hansw-nlo** [comment]
This is what I see now
```
Exception thrown in /media/pi/html/friendica/friendica/src/Module/HTTPException/PageNotFound.php:32
Stack trace:
#0 [internal function]: Friendica\Module\HTTPException\PageNotFound::content(Array)
#1 /media/pi/html/friendica/friendica/src/App/Page.php(333): call_user_func(Array, Array)
#2 /media/pi/html/friendica/friendica/src/App/Page.php(390): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#3 /media/pi/html/friendica/friendica/src/App.php(561): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Util\Profiler), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#4 /media/pi/html/friendica/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1616279259.442)
#5 {main}
```

**Comment by hansw-nlo** [comment]
I think this is not a bug. I needed to chown the filesystem storage. Sorry for not paying more attention.

**Comment by hansw-nlo** [comment]
To make sure nobody is running this as the incorrect user I wrote a few lines on the top of bin/console since that is bash. This stops the console if it is not runnung as the correct user. Please keep in mind that this only works for apache. Solutions for nginx or windows should be added too but I have no windows nor nginx to test it
```
APACHE_USER=$(ps axho user,comm|grep -E "httpd|apache"|uniq|grep -v "root"|awk '
END {if ($1) print $1}')
echo $APACHE_USER


if [ "$(whoami)" != "$APACHE_USER" ]; then
        echo "Script must be run as user: $APACHE_USER"

	echo "usage: sudo -u $APACHE_USER"
        exit 255
fi
```

**Comment by fabrixxm** [comment]
Also the background tasks (cron or whatever) must be run as webserver-friendly user.

**Comment by hansw-nlo** [comment]
In that case Friendica might make this a general thing.

**Comment by MrPetovan** [comment]
Friendica is web server agnostic, I'm not sure we could guess the web server user without making exceptions for all the existing web servers.

**Comment by utzer** [comment]
The bug I filed is still standing, not sure if that is solved now. Maybe it was solved by the pull request of mine, but I can not test it, once the photos are lost they will not come back. :-( 



> Friendica is web server agnostic, I'm not sure we could guess the web server user without making exceptions for all the existing web servers.

You can just check if it is run as root and then issue a warning. That way people get at least notified about the fault when doing it by accident.

**Comment by MrPetovan** [comment]
How would you know on Windows?
