### ISSUE TITLE
Remove Mahjongg addon

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#10068]
The [Mahjongg](https://github.com/friendica/friendica-addons/tree/2021.03-rc/mahjongg) addon is written in Flash which is [no longer supported](https://www.adobe.com/products/flashplayer/end-of-life.html) by the major browsers since January, 2021. Please consider to remove this addon or rewrite in JavaScript is you have time :)

**Comment by MrPetovan** [comment]
It's a good idea, please submit a PR to delete it.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica-addons/pull/1085

**Comment by bkil** [comment]
What about this?

- https://blog.archive.org/2020/11/19/flash-animations-live-forever-at-the-internet-archive/

> Flash Animations Live Forever at the Internet Archive
> The Internet Archive is now emulating Flash animations, games and toys in our software collection.
> Utilizing an in-development Flash emulator called Ruffle
> You will not need to have a flash plugin installed, and the system works in all browsers that support Webassembly.

Basically they rewrote it in Rust. :smile:

**Comment by MrPetovan** [comment]
I don't think anyone played that Mahjongg game in a loooooong while, no need to disturb its rest.
