### ISSUE TITLE
Local hashtag search links are wrongly transmitted to Mastodon

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10060]
When a message contains hashtags, Friendica transforms them into links to the local node's tag search. However, these links seem to persist when transmitted to Mastodon, and are interpreted into external links for which a link preview is provided.

These links should be stripped from messages we send to Mastodon and other AP remote servers.

Original post: https://friendica.mrpetovan.com/display/735a2029-4160-54d6-c77d-f42252009005

Mastodon result:
<img width="654" alt="Screen Shot 2021-03-19 at 14 26 35" src="https://user-images.githubusercontent.com/925415/111826736-72bc3480-88bf-11eb-9688-fd1f4653ed8c.png">

**Comment by MrPetovan** [comment]
Is this just about stripping tag search links from AP messages? And let the remote systems fill in their own tag handling?

**Comment by annando** [comment]
All platforms are transmitting their hash tags as links to their own system. And the receiving systems then interpret them as hash tags. I'm not totally sure which magic sauce we used, but AFAIK we hadn't got these preview problems for a while.

**Comment by MrPetovan** [comment]
So I should submit this issue to the Mastodon repo to get the expected hashtag format?

**Comment by MrPetovan** [comment]
Thanks to @Gargron I was able to troubleshoot the issue, Mastodon uses the `rel="tag"` attribute and we were adding it in `BBCode::convert` only to immediately strip it with HTML Purifier. I've added the attribute value to the allowlist and it worked as expected.
