### ISSUE TITLE
frio on mobile: compose: unable to remove link review

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#10097]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When composing a message, the link preview cannot be removed.

### Steps to Reproduce

1. Be on mobile, with frio.
1. Compose new message /compose or popup doesn't matter.
1. Paste a link, e.g. https://github.com/friendica/friendica/issues/
1. Press enter, the page preview is fetched and inserted.
1. Click the X in the preview's upperbright corner to remove it.
1. ADDED: If the preview was removed, edit the URL and press enter again so that you get a new preview.
1. ADDED: Click to close the preview again.

Actual Result:

Nothing happens.

Expected Result:

The preview is removed.

### Screenshots

![Screenshot_20210328-164854_Fennec](https://user-images.githubusercontent.com/199180/112747061-95e49380-8fe5-11eb-95c0-990deb3f79b8.jpg)

### Platform Info

Friendica Version:

`This is Friendica, version 2021.03-rc that is running at the web location https://libranet.de. The database version is 1412/1412, the post update version is 1400/1400.`

**Comment by clacke** [comment]
Unable to reproduce on desktop.
Reproduced on Android, on F-Droid Fennec and IceCat. Cache cleared.

**Comment by AlfredSK** [comment]
Must be a browser thing. :-) I just tested that successfully with Firefox, Chromium on Linux and Firefox, Chrome on Android.

Edit:
> tested that successfully

To clarify that phrase, I couldn't reproduce the issue.

**Comment by AlfredSK** [comment]
How fast were you when you took that screenshot? 😁 I'm wondering about the spinner right next to the location button. For me the spinner vanishes after less than one second.

Maybe in your case something is going on in the background that blocks the removing of the link preview.

**Comment by clacke** [comment]
Reproduced on Bromite too, but I had to add one round of remove preview, generate new preview.

That spinner never goes away for me, even after the preview has come up.

On Fennec I don't have any kind of adblocker, LibreJS or anything else that should be able to interfere with the running of the frontend.

**Comment by AlfredSK** [comment]
Do you use the option to use the geo-location of the browser? This option is set in settings > basic settings > default post location > `[   ]` use browser location.

**Comment by clacke** [comment]
It is in Settings -> Account Settings -> Basic Information -> Posting location -> Use browser location =)

It is off.

**Comment by foss-** [comment]
Unable to reproduce this problem. Able to reliably remove link preview multiple times.
