### ISSUE TITLE
Photos are being deleted without user interaction

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10105]
- [🐰] I have searched open and closed issues for duplicates

### Bug Description

* photos are deleted without interaction by the users
* mainly old photos are affected (2017 and older) but also 1/3rd of the newer once, regardless of them being used in postings or not.
* automatically exporation of postings is set to 60 days, but only for other poeples content

### Steps to Reproduce

1.  make a timetravel to 2016
2.  post some pictures
3.  travel back to 2021 and see them being deleted

Expected Result:

* photos not being deleted

### Platform Info

Friendica Version: 2021.03-rc 1e71398c72e5bf42870fb19417049b08b78669f6

Friendica Source:  git

PHP version: 7.4

SQL version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB

**Comment by annando** [comment]
Concerning the "deleted": Is the whole `photo` entry deleted or just the stored content?

**Comment by tobiasd** [comment]
If you could tell me how to check that ;-) The photos are not displayed in the albums anymore, but the place for them is kept, IOW you browse the album and see 10 empty spots with links to the picture view (`/photos/$nick/image`). That view also pretents that the photo exists (no error message) but only shows the broken `<img>` tag. Only if one clicks through to the original sized photo, one gets a message that the photo could not be found.

**Comment by annando** [comment]
Okay. So the photo entry still exists, but the data has vanished. Where are your pictures stored?

**Comment by tobiasd** [comment]
Am Tue, Mar 30, 2021 at 08:11:11AM +0000 schrieb Michael Vogel:
> Okay. So the photo entry still exists, but the data has vanished. Where are your pictures stored?

I'm using the filesystem in the storage backend.

**Comment by annando** [comment]
Okay. So the files possibly got deleted. It is not caused by any expiry function then. When you changed it to "filesystem", have you executed the "move" command in the command line? One possibility would be that you haven't moved the old photos and the system now can't deal with this anymore.

Please do the following. Navigate to one of these "empty" photos. Then take the guid (the last part of the url). In my example it is `96490c7c3fe78bb2b78d0c71e8d342d8`. So then execute this sql query:

```
select * from photo where `resource-id`='96490c7c3fe78bb2b78d0c71e8d342d8';
```

Then please tell what you see.

**Comment by tobiasd** [comment]
> When you changed it to "filesystem", have you executed the "move" command in the command line? 

Looking at my self from years ago with a big question mark in my face...

> Please do the following.

Resulting in 3 rows with multiple screens of content, some binary.

**Comment by annando** [comment]
Okay. This means that you haven't moved the content. So the bug is that now pictures aren't fetched anymore if they are stored directly in the database.

And BTW: This is good news, your pictures aren't lost.

**Comment by tobiasd** [comment]
And executing the "move" might fix the problem?

**Comment by annando** [comment]
I guess that the move in the current situation would destroy these pictures.

**Comment by tobiasd** [comment]
Ok, then better save then sorry and I wont touch a thing :)

**Comment by annando** [comment]
I created some possible fix. If this doesn't work I don't have a clue and would hope that either @MrPetovan, @nupplaphil  or @fabrixxm could take over.

**Comment by tobiasd** [comment]
The photos should be back again immediately after pulling this change right? Then it did not fix the problem. OTOH the log now has a new entry that smells like photo related :)

```
[01-Apr-2021 07:58:05 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function __toString() on string in /src/Util/Logger/AbstractLogger.php:119
Stack trace:
#0 /src/Util/Logger/StreamLogger.php(164): Friendica\Util\Logger\AbstractLogger->jsonEncodeArray()
#1 /src/Util/Logger/StreamLogger.php(141): Friendica\Util\Logger\StreamLogger->formatLog()
#2 /src/Util/Logger/AbstractLogger.php(173): Friendica\Util\Logger\StreamLogger->addEntry()
#3 /src/Core/StorageManager.php(176): Friendica\Util\Logger\AbstractLogger->notice()
#4 /src/Core/StorageManager.php(110): Friendica\Core\StorageManager->checkLegacyBackend()
#5 /src/Model/Photo.php(195): Friendica\Core\StorageManager->getByName()
#6 /src/Module/Photo.php(106): Friendica\Model\Photo::getImageDataForPhoto()
#7 [internal function]: Friendica\Module\Photo::rawConte in /src/Util/Logger/AbstractLogger.php on line 119

```

**Comment by fabrixxm** [comment]
> The photos should be back again immediately after pulling this change right? Then it did not fix the problem. OTOH the log now has a new entry that smells like photo related :)

looks like more related to #10101

**Comment by tobiasd** [comment]
As of 5947698dc15ee6887dd9af0da1c68d6a41f06ced the pictures are back again, so I'm closing this issue
