### ISSUE TITLE
[frio] Contacts page - move subscription filter to more prominent location

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10100]
Currently the subscription filter is the lowest widget on the contact page. I already was ready to open a feature request, because I searched for it and didn't find it in the beginning.

For UX reasons, it would be far better to put this filter option on top of the contacts pages.

Something like this
![01_temp](https://user-images.githubusercontent.com/24474762/112755640-d6421280-8fe1-11eb-85ed-b15c44a1f379.png)

BTW ... the naming of contacts was discussed several times and I think we agreed not to use the misleading terms "Follower, Followings or Friends", like it is currently used in the filter widget.

**Comment by annando** [comment]
It could be done the same way it is done on the contacts page:
![grafik](https://user-images.githubusercontent.com/844208/112756427-67ff4f00-8fe5-11eb-9444-7a72af530416.png)

**Comment by hoergen** [comment]
And maybe reduce the options on your @annando screnshot since they would be doubled.

**Comment by annando** [comment]
On that page all the options do make sense since they display the contacts of a contact and not our contacts.

**Comment by hoergen** [comment]
For UX reasons I just want to avoid something like this

![00_temp00](https://user-images.githubusercontent.com/24474762/112758161-21adee00-8fed-11eb-95a2-8342b519a319.jpg)

**Comment by MrPetovan** [comment]
Ooooh, shiny! Look at all these marvelous gradients and plump round borders!

**Comment by hoergen** [comment]
> Ooooh, shiny! Look at all these marvelous gradients and plump round borders!

I would kindly like to  ask all participants to not pollute issues with toxic comments.  Thank you.

**Comment by MrPetovan** [comment]
You posted a completely unrelated picture to make a point nobody was even remotely contesting, so who's polluting?

**Comment by hoergen** [comment]
I would kindly ask you to read the thread again and not to derail the topic. 
To explain it for you: The image I was posting was an example what negative influence an overloaded UI is doing to the user experience, if we just add and add things to a GUI.
