### ISSUE TITLE
Use Compose editor as default editor

### ISSUE THREAD

**Issue by Singh-in** [friendica/friendica#10117]
I'm always frustrated when [...]` I have to use the modal editor. It is cumbersome to use and the different tabs do not support me when creating content.

### Describe the feature you'd like

The Compose Editor is easier and faster to use in the browser and on the mobile phone. Therefore, there should be a possibility to use it as a standard instead of the modal editor. 

### Describe alternatives you've considered

Clicking the middle button always opens the Compose Editor in a new browser window. It would be a start if it did this in the same browser window.

### Additional context

**Comment by cracrayol** [comment]
Can be closed. Resolved by #12002.
