### ISSUE TITLE
Impossible to make an introduction

### ISSUE THREAD

**Issue by JGaynard** [friendica/friendica#1012]
Another person joined Friendica and sent me an introduction, which I never received. I tried to send an introduction to this person and I received the message that I had already sent an introduction (so why didn't it show up in the other person's requests for introduction). This mutual introduction is now hanging in limbo. Any ideas? Thanks in advance,

**Comment by silke** [comment]
As this is quite old now could you test this again with Friendica 3.3.3? Does the issue still exist at all?

**Comment by annando** [comment]
We still need a method to resend introduction that got stuck.

**Comment by strk** [comment]
I've had problems with introductions too as of current master branch (beb4980f020e09625357114159a860f64f030004)

**Comment by MrPetovan** [comment]
Is it still current, do people still report issues with introductions?

**Comment by annando** [comment]
The introduction is a multi step process that musn't be interrupted. Means: Yes, we still have this issue and we need to change this.

**Comment by MrPetovan** [comment]
Not an RC task, moving to next.

**Comment by annando** [comment]
This is most likely fixed by the new AP based connection process.

**Comment by MrPetovan** [comment]
Closing for now, do you have a specific PR to link here?

**Comment by annando** [comment]
That's my PR where I changed the connection process to AP. I can try to look for the exact number this evening.
