### ISSUE TITLE
Automatic creation of Twitter threads if your post/reply in Friendica exceeds the 280-character limit

### ISSUE THREAD

**Issue by TheFuzzStone** [friendica/friendica#10135]
### Is the feature request related to a problem? Please describe.

I have a suggestion/feature request about linked Twitter. This is a very cool and useful thing that makes me want to stop using Twitter directly in the future.

I recently made a test post (https://venera.social/display/85a863ed-1060-6af5-e08c-926757795243) that showed up like this in Twitter: https://twitter.com/thefuzzstone/status/1379034978898620416

### Describe the feature you'd like

That would be really cool to create Friendica posts that exceed Twitter limit (280 characters) automatically turn into a Twitter thread and have numbers at the beginning of each tweet, for example "1/", "2/", etc.

Or even without numbering tweets in threads, just so that thread itself is created automatically.

And, of course, it would be cool to have the same functionality for replies to tweets. For example, I'm replying to someone's tweet and my reply exceeds the limit of 280 characters, which means a thread is created with tweets that come one after another. I hope I explained this point well... When you need to respond to a person with two tweets (or more), you will first create one tweet response and then respond to your previous tweet, thereby creating a logical and orderly reply.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
