### ISSUE TITLE
repeated posts in the Saved Folders

### ISSUE THREAD

**Issue by hansw-nlo** [friendica/friendica#10156]
- [ x] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Create a post with one or several categories
2.  Look at the saved folders where the post is shown

Actual Result:

Expected Result:

### Screenshots

https://federate.hopto.org/photo/1254297449607dae971c8ac621288174-2.png

### Platform Info

Friendica Version: Friendica 'Red Hot Poker' 2021.03-rc - 1411

Friendica Source: 

PHP version: PHP Version 7.3.27-1~deb10u1

SQL version: Server version: 10.3.27-MariaDB-0+deb10u1-log Raspbian 10

**Comment by hansw-nlo** [comment]
![Screenshot from 2021-04-19 18-22-24](https://user-images.githubusercontent.com/27645742/115279053-7fde7480-a146-11eb-85c4-06e5e4c278a5.png)

**Comment by MrPetovan** [comment]
Thank you for the report, I could have sworn someone already reported this issue but I haven't been able to find it again, it probably was on the Friendica Support Forum.

**Comment by hansw-nlo** [comment]
Maybe since I mentioned it a few weeks ago. I did, but I also wanted to see if others had it too

**Comment by AlfredSK** [comment]
I have it too. :-)

**Comment by annando** [comment]
I still can't reproduce the bug - but found another one. In fact storing into categories instead filed it, but hadn't put the post into categories (as you can see on the red color of the file/category)

**Comment by AlfredSK** [comment]
For me the repeated post behave more interesting. ;-) Maybe this helps to reproduce the issue.

When I scroll down in a folder with a lot of saved items I see something like this (same numbers represent the exact same items):
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
...

**Comment by AlfredSK** [comment]
I have the feeling that the `infinite scroll` does load the same items on every "page". Could this be the issue?

**Comment by AlfredSK** [comment]
Yep. Without `infinite scroll` the pages are showing the expected content.

**Comment by RealVegOs** [comment]
I still experience this on an instance running with 2022.12. Its OK on an instance still running 2022.06  I'm a user, not the admin. It's also not possible to delete the posts. Instead of the bin icon, a text popup with "Delete selected items" shows up. Clicking it has no effect at all.
