### ISSUE TITLE
Email notifications flood my inbox any time I'm mentioned even though I have every box unclicked

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#10161]
I have selected no email notifications, yet no matter what try I still get an email any time I'm mentioned in a response post.  I've considered sending it to spam because it fills up my email inbox so badly.

**Comment by realkinetix** [comment]
Which instance is this relating to?  I don't see any emails being sent out to your email address from social.isurf.ca.

Can you post the headers from an example notification?

Also, please  don't send any to spam/junk on gmail - you should be able to setup a filter to push them off to some other unique, but not-having-google-learn-it-as-spam folder, no?

**Comment by anubis2814** [comment]
This is on Social.isurf.ca 
[Friendica:Notify] James Uscroft tagged you (ksirion@social.isurf.ca)
Any places in setting you think I should check?  It only happens when I've been tagged

**Comment by anubis2814** [comment]
WAIIIIIIT NM I know what the issue is, this is for an account tied to it I never use.  Thanks!

**Comment by MrPetovan** [comment]
Can we close this?

**Comment by anubis2814** [comment]
Yes please, sorry for wasting people's time but thanks for the help.

**Comment by MrPetovan** [comment]
It's perfectly okay!
