### ISSUE TITLE
RSS feeds weird behavior

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10186]
On friendica version 2021.01 I get this behavior:
1. I add an RSS feed of my blog.
2. I setup to reshare it automatically as my own posts
3. I update old blog posts (but no date change, just update)
4. The old post now get posted on my page (reshares).

So, updated posts are shown in Friendica feed as new posts. Why is that?

**Comment by annando** [comment]
The import uses the page link as identifier. So when the page link changes the system cannot know if the content is new or old. So for example you correct a typo in the title and thus the link to the article is changed, then the article will be posted again.

Can you check if this is the case here?

**Comment by tio-trom** [comment]
Am not sure I understand or if you understand what I was saying. To explain it more exactly:

I have this website https://www.videoneat.com/ and the RSS feed is https://www.videoneat.com/feed . It is a Wordpress website. I add https://www.videoneat.com/feed to my contacts then setup so that all posts from https://www.videoneat.com/feed will be mirrored as my own posts. All good. Then  I go to https://www.videoneat.com/ and change some stuff for some very old posts, like correct some typos. I click update. The date of the posts does not change, the url does not change, they do not showcase in the RSS feed as newer posts, and yet Friendica somehow grabs these updated posts and quickly posts them on my Friendica page as if they are new posts.

One day I selected tens of posts from my website and only changed their category and updated them. Then they all ended up on my Frienica page spamming everyone :D. 

And RSS Reader won't behave like that for example.

**Comment by MrPetovan** [comment]
I've been receiving 13 years old posts from an RSS feed contact for the same reason: small updates to very old posts. The reason was because their blog was ActivityPub enabled, and as such was actively delivering updates to subscribers. And the reason I was subscribing is that I put in the base URL when adding a contact, and it grabbed the ActivityPub information instead of the RSS one since it has less priority.

Could it be the same issue?

**Comment by tio-trom** [comment]
Ah yes you are right! It is using the ActivityPub from the website and not the RSS. I didn't realize that. So then then issue is not RSS related but ActivityPub related. Sorry I didn't realize that.
