### ISSUE TITLE
Double entries when searching people that are not on the federation

### ISSUE THREAD

**Issue by hansw-nlo** [friendica/friendica#10184]
Dear team, 

I found a new issue when searching people that can't be found. It then shows a list of double entries of the first user on the instance

- [x ] I have searched open and closed issues for duplicates

### Bug Description

wrong search results when searching users

### Steps to Reproduce

1.  As an example I searched for a public figure that isn't on the federation
2.  See the image

![Screenshot from 2021-04-29 20-25-42](https://user-images.githubusercontent.com/27645742/116600434-985e4400-a929-11eb-8cca-323ee8d9e0c1.png)
3.  step three

Actual Result:

See the screenshot

Expected Result:

Empty resultset

### Platform Info

Friendica Version:

Friendica 'Siberian Iris' 2021.04 - 1413

Friendica Source: 

PHP version: 7.3.27-1~deb10u1

SQL version: Your MariaDB connection id is 87121
Server version: 10.3.27-MariaDB-0+deb10u1-log Raspbian 10

**Comment by annando** [comment]
Which search field have you used? Have enabled or disabled the local directory search? (You can configure it in the admin settings).

**Comment by hansw-nlo** [comment]
I am using the search box on the contact page, upper left ( Find people)

Discover followers/followings from contacts is set to none, I do have the discovery turned on.

**Comment by AlfredSK** [comment]
I guess Annando was talking about the last option in admin > site > auto-discovered contact directory. Is it on or off?

☑️ Search the local directory

**Comment by annando** [comment]
@AlfredSK exactly!

**Comment by hansw-nlo** [comment]
Search the local directory is off, even when it is on, double entries should never be found. select distinct, whatever, it should not be showing more then 1 unique entry

**Comment by annando** [comment]
Of course the system's behaviour is weird here. But currently I cannot reproduce it and thus cannot fix it, so there must be differences between our two systems.

**Comment by hansw-nlo** [comment]
I am using the latest rc. Are you on the dev version?

**Comment by AlfredSK** [comment]
@hansw-nlo 
> searched for a public figure that isn't on the federation

Do you have an example? Maybe I can reproduce it.

Btw. there was a release! Maybe you should switch to stable. :-)

**Comment by hansw-nlo** [comment]
This is one where I see the results like on the picture. 

https://federate.hopto.org/dirfind?search=robert+palmer

**Comment by AlfredSK** [comment]
I get zero results for that search - with 'search local' on.

But I can confirm the weird results when I switch off 'search local directory'.

![Screenshot_20210503-194449](https://user-images.githubusercontent.com/3656054/116912203-3282fc80-ac48-11eb-91a7-8030b05c5e39.jpg)

**Comment by annando** [comment]
Okay, then I know where to look at.
