### ISSUE TITLE
Disallow or at least require confirmation when blocking or ignoring self

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10198]
### Is the feature request related to a problem? Please describe.

I would either like the ability to block or ignore oneself disallowed altogether as I've done both unintentionally and can't think of any legitimate reason to have this functionality, but if there is a reason at least require conformation, block yourself really?  Yes, well OK if you really really insist...

### Describe alternatives you've considered

I don't really have any other solution, I don't even know how I managed to do either.
### Additional context

**Comment by AlfredSK** [comment]
Yep. Blocking and ignoring yourself shouldn't be possible.
But how did you manage to block/ignore yourself? I checked the usual places in the UI. I couldn't find a possibility to block/ignore myself.

**Comment by 4nanook** [comment]
If I look at a post I made, and hover over my icon I get a number of options, among them to block or ignore.  I suspect I was trying to block or ignore someone else but chose the wrong message / icon and blocked and ignored myself.  See the attached screen shot.

![block-ignore](https://user-images.githubusercontent.com/3466797/116827561-6679f700-ab4e-11eb-8d0a-d72d01a26bc0.png)

**Comment by AlfredSK** [comment]
Ok. That's a bug in theme 'vier' then. These links shouldn't exist at all for the users own profile. They don't exist in 'frio'.

**Comment by 4nanook** [comment]
In my opinion, themes should not be a place for program logic, only display.  But people are going to use this theme because it is responsive and works with portable devices where Frio does not.

**Comment by tobiasd** [comment]
Most likely it is a problem of _all other themes except frio_ but also most likely should be fixable by adjusting one spot in the templates, which all these themes share (except frio).

**Comment by MrPetovan** [comment]
I'll look into removing the link from the template variables altogether. This will fix this issue permanently for all thems regarding of template shenanigans.

**Comment by 4nanook** [comment]
Sounds like a plan, could save someone headaches in the future.

**Comment by MrPetovan** [comment]
This issue has been fixed in two places: the item photo menu doesn't offer links to block/ignore oneself across all themes, and the contact module will refuse to comply if the URL to block/ignore oneself is called.

**Comment by 4nanook** [comment]
Applied updates, it worked, ignore / block links are gone from my own posts.  Thank you!
