### ISSUE TITLE
Users miss direct login button in frost-mobile's start page

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1019]
Several people asked how they can login in frost-mobile. They don't find the link to the login page underneath the "arrow down" button.

So feature request: Place a direct login link on the start page.

**Comment by silke** [comment]
Btw, is frost mobile in a working state? When I used it last time, it wasn't. So this might mean to repair frost-mobile first - IF we are going to put any more energy into that theme.

**Comment by tobiasd** [comment]
I'll close the ticket as the theme is deprecated now
