### ISSUE TITLE
Deleted User still counts as blocked user

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#10216]
I just had a report of a spamming user. So, as a first measurement I blocked the user and asked for some proofs of the spam. Those were provided and I switched in User List to "Blocked" and clicked on the trash icon to delete the user. That worked, but now I still have a user cound of 1 for Blocked. 
![Bildschirmfoto 2021-05-07 um 07 29 56](https://user-images.githubusercontent.com/18173881/117402099-0dbbad00-af06-11eb-8dc3-da85d7bb4e8a.png)
I guess the count will (hopefully) go away when the user is really deleted in 7 days, but I still feel this is a "bug" because a user marked for deletion should not be listed anymore as blocked. Or other way around: when the user is removed from the blocked list, because it got deleted, the block marking should be reset and the user count for Blocked should correct. Or a deleted but blocked user should still be listed under Blocked. Whatever, but the current behaviour doesn't seem to be correct. :-) 

Friendica 'Siberian Iris' 2021.04 - 1413

**Comment by martincodes-de** [comment]
I will try it

**Comment by MrPetovan** [comment]
Thank you for the record, the count may indeed include users planned for deletion.

**Comment by martincodes-de** [comment]
> Thank you for the record, the count may indeed include users planned for deletion.

where i can find this view? i dont find it in the admin backend

**Comment by martincodes-de** [comment]
pr: https://github.com/friendica/friendica/pull/10873
