### ISSUE TITLE
Technical ActivityStreams messages appear as comments when sending a post for a new photo upload

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10219]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When a user uploads a new photo the user can uncheck the option 'do not show a status post for this upload' to instantly create a new post for the uploaded photo. When this is done the user receives technical ActivityStreams protocol messages visible as comments on the item.

Related post: https://libranet.de/display/0b6b25a8-3460-9472-55dc-4df370576872

### Steps to Reproduce

1.  upload a photo
2.  uncheck option 'do not show a status post for this upload'
3.  look for received protocol messages displayed as comments

**Actual Result:**

The user gets comments like...
`<a href="http://activitystrea.ms/schema/1.0/follow" target="_blank" rel="noopener noreferrer">http://activitystrea.ms/schema/1.0/follow</a>`

**Expected Result:**

These messages shouldn't be visible at all.

### Platform Info

**Friendica Version:**
2021.04 stable

**Friendica Source:**
git

**PHP version:**
7.4

**SQL version:**
10.3 MariaDB

**Comment by annando** [comment]
I need some data. Can you reproduce it? If yes, I need to know how this "follow" request had been created. Means: Have a look for the `uri-id`, `guid` and `id` of the post (you can see this in the `post-user-view`) in the logs.

**Comment by AlfredSK** [comment]
Oof. I didn't get those comments myself. It was a user on my node who reported that. But I will see later today if I can reproduce it somehow.

**Comment by AlfredSK** [comment]
Hmm. I tried. But I cannot produce a new post for a new photo upload. I have unset the option...

:ballot_box_with_check:  Do not show a status post for this upload

...and then uploaded a new photo to an album. But there is no new post for that new image. The option doesn't work for me. Is this another bug? :-D

But I cannot reproduce the original issue without further information how it happened exactly.

**Comment by AlfredSK** [comment]
Ah! I have it! \o/ It's on the photo's page! The photos have comment boxes! One of the functions of Friendica I have never used or looked at before. :-)

Look! -> https://libranet.de/photos/alfred/image/126310167660ab9c1b96ee8466828076

**How to produce the issue:**

![Bildschirmfoto vom 2021-05-24 19-01-42](https://user-images.githubusercontent.com/3656054/119382765-c897c900-bcc2-11eb-898d-61ca3662b6d0.png)

**Comment by AlfredSK** [comment]
This whole functionality of sending a post for a new photo upload is completely weird. I got a real comment now from Andreas on that photo. So, obviously he got it as post in his stream. But I don't see that post myself - not on my status page and not on my network page. I have to look at the photo details itself to see the comment.

Back to the bug. :-) The technical messages under the photo are coming from Diaspora pod admin accounts. So this is an issue with 'photo' type messages and the 'diaspora' protocol.

**Comment by AlfredSK** [comment]
Btw. the notification for Andreas' comment on the photo item is linked to nothing. If I follow the notification I am thrown at an empty page (empty as: a page without an item showing up).

So I would say that nearly everything regarding public photo uploads with sending posts for the new photo is utterly broken .

If you ask me I would suggest to remove that completely. It's weird, hard to understand and doesn't work.

**Comment by AlfredSK** [comment]
I have added a screenshot how to reproduce the issue.

**Comment by annando** [comment]
Thanks for the hint that all the "follow" requests are done by Diaspora. Then I know what's going on.

There are several ways to solve it. One is to simply not display these requests. And the other way would be to deactivate this weird commenting thing. But this should be discussed.
