### ISSUE TITLE
Junior Jobs 

### ISSUE THREAD

**Issue by AeronRoemer** [friendica/friendica#10236]
Hey, I'm noticing the 'Junior Jobs' label is not getting applied as of late. Any way to bring that back? I'm interested in starting to help.

**Comment by MrPetovan** [comment]
Hi @AeronRoemer and thank you for the offer. It is true we have been ignoring this label. I would suggest you start with the [PHP Notices](https://github.com/friendica/friendica/issues/10169) thread, it is pretty low stakes and can introduce you to the  internals of Friendica.

I'll comb the issue log for more opportunities.

**Comment by MrPetovan** [comment]
I have added the label to several issues, I've added it on this issue as well to help discoverability. Just click on the label on the right column to find all the labeled issues.

**Comment by AeronRoemer** [comment]
@MrPetovan Thanks, I'll take a look
