### ISSUE TITLE
Problems with MySQL 8?

### ISSUE THREAD

**Issue by DJoerger** [friendica/friendica#10263]
Hi,

i've tried to install Friendica 2021.04 on my webgo webhosting account with PHP 7.4 and MySQL 8.

The installation process went through, until i have to set up the database. This always ends with: #1142 - REFERENCES Befehl nicht erlaubt für Benutzer 'web*****'@'localhost' auf Tabelle 'web*****.user'.

I've also tried to run the SQL query via PhpMyAdmin, same result. For me this looks like a permission problem, but i have also no glue about MySQL... The technical support of my web hoster thinks that it would be an incompatibility with MySQL 8.

Best regards,
Denis

**Comment by annando** [comment]
MySQl and MariaDB are drifting away and neither side is seeking compatibility, I think. All the development is done on MariaDB. So it can assume that there can be problems, However, in this case I think that it is some permission problem, see here: https://community.woltlab.com/thread/250279-fehlermeldung-bei-anlegen-der-datenbank/

We are working with foreign keys. Possibly this needs some additional permission.

**Comment by DJoerger** [comment]
It really was a permission problem. Instance is now up and running. :)
