### ISSUE TITLE
'Comment this item on your system' sometimes doesn't appear

### ISSUE THREAD

**Issue by forenta** [friendica/friendica#10264]
Reference to the [Friendica post here](https://less.re/display/da596b0d-1460-a3e8-c00c-924079530982) (German).

In most cases posts appear with the option to leave a comment on my system, but in some cases they do not. So far, unfortunately, I can not make out what it is - in any case, in the upper right corner always appears the notice that I am visiting as a guest.

<img src="https://i.postimg.cc/hvyXmCsN/screenshot-29.png">

[Case 1](https://squeet.me/display/962c3e10-1160-9146-4b4b-828371756078) fine
[Case 2](https://libranet.de/display/0b6b25a8-3560-9d00-a8c5-bc0676640039) No way to become part of the conversation

If I replace the TLD of the post with the TLD of my own instance by myself, I'm able to join the conversation in both cases. But I'm wondering why this is necessary in some cases.

Sorry, but I wasn't sure if this is a rather a case for Question/Support or Bugs. 🤷‍♂️

**Comment by annando** [comment]
The weird thing about this is that at both machines you are recognized as remote visitor.

**Comment by annando** [comment]
Are you marked as "Guest" or "Visitor" on these remote systems?

**Comment by forenta** [comment]
> Are you marked as "Guest" or "Visitor" on these remote systems?

Due to an outdated SSL-certificate I am unable to access Friendica today. As soon as I get in again, I'll tell you.
