### ISSUE TITLE
API: respect ignore, block, communitysilence in community streams

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10287]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I discovered that accounts I have filtered out of my community pages show up in the local and global community stream when I use an app. So I assume that ignoring, blocking and communitysilencing doesn't work with the API.

I'm not sure if only the communitysilenced accounts show up in these streams or if this also happens with ignored and blocked users. I will have to figure that out somehow.

I remember this happens with Fedilab and now it also happens with e.g. Tusky. So, the bug exists in the legacy API and in the new Mastodon API.

The network stream seems to be ok.

When using a browser all streams are ok.

### Steps to Reproduce

1.  Use an app like Tusky or Fedilab
2.  Watch the local and global stream for content of filtered accounts

**Actual Result:**

The local/global community stream is different in browsers compared to apps.

**Expected Result:**

The local/global community stream should be the same no matter what client I use.

### Platform Info

Friendica Version:
2021.06-dev / 2021.06-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
I have the feeling the problem is that `communitysilence` isn't taken into account via API.

**Comment by annando** [comment]
Simple answer: Yes.

**Comment by AlfredSK** [comment]
I checked the federated timeline (which is our global community stream) in Tusky and Husky. I don't see content of user or server blocked accounts anymore. Good.

But I still have the content of 'silenced' accounts in these apps when I check the federated timeline. I have silenced the accounts via console command `bin/console globalcommunitysilence https://example.com/user/profile`. They don't show up in our web interface on the community pages but they still appear via API access.

So I think this issue isn't completely fixed yet.

**Comment by annando** [comment]
I guess what you see are comments from these silenced accounts?

**Comment by AlfredSK** [comment]
No. Top-level posts. I have silenced some porn and bot accounts on the community pages. But in Tusky/Husky their content is still showing up in the federated timeline.

**Comment by AlfredSK** [comment]
Wait. I need to check something. There seem to be duplicates of some of the bots.

**Comment by AlfredSK** [comment]
Checked. It is the same account - no duplicate. So, it is globalcommunitysilenced but the posts still show up in the apps.
