### ISSUE TITLE
Deprecation Notice 

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#10302]
Im geting this after gitpul on latest develop

`Deprecation Notice: Class Friendica\Module\Api\Mastodon\Conversation\Read located in ./src/Module/Api/Mastodon/Conversations/Read.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in  /bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by AlfredSK** [comment]
This is already fixed in RC.

**Comment by ghost** [comment]
Ah i have to switch
