### ISSUE TITLE
PHP 8.0 - incompatible dependencies

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#10301]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The following dependencies aren't PHP 8.0 compatible, so there's a risk when using Friendica withh PHP 8.0:
```console
bacon/bacon-qr-code              1.0.3   requires  php (^5.4|^7.0)  
patrickschur/language-detection  v3.4.0  requires  php (^7)         
pragmarx/recovery                v0.1.0  requires  php (~7.0)    
```

### Steps to Reproduce

```console
[philipp@PHIL-X1-CARBON friendica]$ bin/composer.phar why-not php 8.0
```

Actual Result:

```console
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
bacon/bacon-qr-code              1.0.3   requires  php (^5.4|^7.0)  
patrickschur/language-detection  v3.4.0  requires  php (^7)         
pragmarx/recovery                v0.1.0  requires  php (~7.0)      
```

Expected Result:

```console
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
There is no installed package depending on "php" in versions not matching 8.0
```

**Comment by nupplaphil** [comment]
@MrPetovan - maybe something for this release, because you always upgrade the dependencies before a release AFAIK :-)

**Comment by MrPetovan** [comment]
I do, but while I believe the QR Code library would be easy to replace, the other two are pretty central to their respective features. And I don't have a PHP 8 install to test my changes, so it would be challenging.

**Comment by MrPetovan** [comment]
Another incompatible dependency, this time in the `twitter` addon with the `abraham/twitteroauth` dependency:

By @utzer in https://github.com/friendica/friendica/issues/10473#issuecomment-894814806
> Another error with PHP 8.0.9:
> 
> ```
> [08-Aug-2021 15:34:30 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in addon/twitter/vendor/abraham/twitteroauth/src/SignatureMethod.php on line 61
> ```
