### ISSUE TITLE
Followers not seeing my reshares: is this expected behavior?

### ISSUE THREAD

**Issue by very-ape** [friendica/friendica#10306]
Specifically, they can see them when viewing my profile directly, but they don't show up in their network feeds.

Didn't want to start debugging before confirming this behavior is not intended.

**Comment by annando** [comment]
Well, they should. Which networks are they on and what had you reshared? There are limits so that a Diaspora reshare would only be visible on Diaspora and Friendica and an ActivityPub reshare will only be visible on ActivityPub and Friendica.

**Comment by very-ape** [comment]
These are members on my Friendica instance. :/

I'll start debugging later today, then.

Edit: Is this related to #8414?

**Comment by very-ape** [comment]
Um... I'm looking at the code in `Module/Conversation/Network.php` and... I don't think I want to touch it. Maybe this would be a task better suited for someone more familiar with what's going on here. I'm just gonna go wrap up my "Mobile Client Tokens" addon instead.

**Comment by MrPetovan** [comment]
Sorry about that, it is the most complicated part of Friendica and I've always have been reluctant to touch it as well.

**Comment by annando** [comment]
I just did some tests. I performed a reshare and looked if it had been distributed. In my tests it is.

Here it is on squeet.me:
![Bildschirmfoto vom 2021-05-24 10-49-38](https://user-images.githubusercontent.com/844208/119322613-0faf9b00-bc7e-11eb-84b3-915e8d5404ad.png)

And on pleroma and Mastodon:
![Bildschirmfoto vom 2021-05-24 10-48-33](https://user-images.githubusercontent.com/844208/119322648-1b9b5d00-bc7e-11eb-96a7-b1724590ba13.png)
![Bildschirmfoto vom 2021-05-24 10-49-06](https://user-images.githubusercontent.com/844208/119322650-1d652080-bc7e-11eb-8bba-0f5bb580f4bb.png)

**Comment by very-ape** [comment]
Yeah, I can see all my reshares from accounts on other networks. It's the people on the same Friendica instance that can't see them. E.g., "ryan@mast.verya.pe" can see reshares from the account "ryan@friendica.verya.pe", but "jessc@friendica.verya.pe" cannot.

**Comment by annando** [comment]
Ah okay. Thanks for clarification.

**Comment by annando** [comment]
@very-ape this really opened a can of worms. The problem had been much deeper, right at the message delivery itself.

**Comment by tio-trom** [comment]
I have reported this in the past I believe. I have reshares enabled and no one on our Freindica node at least, can see these posts in their news feed. I even tested with notifications and they get notifications for all posts, except reshares. In all, seems like reshares are invisible.

**Comment by annando** [comment]
@TROMsite yeah, internally they hadn't been delivered at all - only externally. The current fix is a complete rebuild of the local delivery. Reshares now work. It isn't tested with forums and events by now, but should work as well.
