### ISSUE TITLE
Posting a new comment shows a (1) counter at the home menu item.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1032]
When you yourself post a comment, I don't think it makes sense to give a notification for it.

![Example](http://ss.oscp.info/2014-06-23_12-36-13.png)
*Above `1` is triggered by "Pong"*

**Comment by strk** [comment]
Bump, I'd call this also a bug, found here while looking for existing reports before filing a bug myself.
Being notified about own posts is confusing at best.

**Comment by strk** [comment]
It happens for me with vier, last tested in 3.4-1208-g096cb91 (are some tags missing?)

**Comment by strk** [comment]
Proposed fix in https://github.com/friendica/friendica/pull/2092

**Comment by tobiasd** [comment]
seemm to be fixed with #2092 so I'm closing this issue
