### ISSUE TITLE
Navigating to index page with HTTPS forced does not redirect to HTTPS.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1034]
In my case we're talking about `fc.oscp.info` if I navigate directly to `http://fc.oscp.info/` with the force HTTPS setting enabled, I'm not redirected to HTTPS until I navigate or log in.

**Comment by Beanow** [comment]
Agreeing now that an .htaccess configuration is the best way to do this. I think it should be documented and possibly mentioned with HTTPS related config values in the admin section.

**Comment by annando** [comment]
We are having the option "Force SSL". This does the expected behaviour.

**Comment by Beanow** [comment]
At the time it didn't, was it changed?

**Comment by annando** [comment]
"Force SSL" is active since 3.3.2, I guess.

**Comment by silke** [comment]
@Beanow Can I close this issue?

**Comment by Hypolite** [comment]
Does the changes in the SSL docs I added are enough to dissipate any doubts about the "Force SSL" setting?
