### ISSUE TITLE
Calender entry changes are not distributed

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10365]
Current 2021.06-rc doesn't distribute changed calendar entries.

E.g. The Date 01.06.2021 was changed to 02.06.2021, but it wasn't distributed to the other nodes. Even after several days.

**Comment by tobiasd** [comment]
Current state (2021.09-rc) is, that the remote instance is getting the notification that the event description was changed (and is displaying that) but the actual changes are not shown on the remote side.
