### ISSUE TITLE
RSS-feeds for commmunity-forum accounts not working

### ISSUE THREAD

**Issue by regenpfeifer** [friendica/friendica#10369]
- [x] I have searched open and closed issues for duplicates

### Bug Description

RSS-feeds for **community-forum accounts** produce an error. I have tested this with [my own friendica node](https://friends.regenpfeifer.net) and described the error [here](https://friends.regenpfeifer.net/display/d368d644-1860-b7ee-3f96-7fa984056869).

### Steps to Reproduce

1.  I am trying to get messages from the RSS-feed of a **community-forum account** [https://friends.regenpfeifer.net/feed/bavarianbirds/posts](https://friends.regenpfeifer.net/feed/bavarianbirds/posts) and get an error message: `"malformed xml string parsing error: DOMDocument::loadXML(): Namespace prefix activity on object-type is not defined in Entity, line XX"`, different online feedreaders produce similar error messages.
2.  An **alternative RSS-feed** [https://friends.regenpfeifer.net/dfrn_poll/bavarianbirds](https://friends.regenpfeifer.net/dfrn_poll/bavarianbirds) is working correctly.
3.  Also RSS-Feeds of **"normal" user accounts** are working correctly in both modes: https://friends.regenpfeifer.net/feed/regenpfeifer/posts as well as [https://friends.regenpfeifer.net/dfrn_poll/](https://friends.regenpfeifer.net/dfrn_poll/regenpfeifer).
4. Other users confirmed this bug.

### Platform Info

Friendica Version: 'Siberian Iris' 2021.04 - 1413

Friendica Source: https://git.friendi.ca/friendica/friendica.git

PHP version: PHPFPM 8.0
SQL version: MySQL / MariaDB 10.5
APACHE: 2.4
OS: Debian 10 Buster

**Comment by hoergen** [comment]
This Bug is still existing. When testing my https://horche.demkontinuum.de/profile/filmzeit with the Firefox RSS Addon I got this error message


```
XML Parsing Error: prefix not bound to a namespace
Location: https://horche.demkontinuum.de/feed/filmzeit/activity
Line Number 20, Column 7:
      <activity:object-type>http://activitystrea.ms/schema/1.0/group</activity:object-type>
------^
```

**Comment by MrPetovan** [comment]
Thank you for the added information!
