### ISSUE TITLE
Local author's own post is not displayed on the author's wall (home stream)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10364]
- [X] I have searched open and closed issues for duplicates

### Bug Description

A user of my node reported that their own, original post don't show up on their wall (home stream). The user can see the post in their network stream and on the /display page of the item. But not on their own wall, profile, status page - whatever that stream is called, exactly. ;-)

Happens from time to time. But not with all own posts.

This is the post: https://libranet.de/display/0b6b25a8-1560-b691-7f12-846744488797

It is an original post. No reshare. It was reshared 2 times, liked a lot and commented on.

The user has the option to 'delete globally' in the 'more...' menu of the post item. But still, it doesn't show up on their ... damn it! How is that stream called? ... on their .../profile/nickname page. :-D

I have checked the database. I'm not sure if I was looking for the right thing but this is what I found. When you need anything else, please tell.

**Looking for the uri-id of the post's guid:**
```
MariaDB [friendica]> select * from `item-uri` where guid = '0b6b25a8-1560-b691-7f12-846744488797';
+----------+------------------------------------------------------------------+--------------------------------------+
| id       | uri                                                              | guid                                 |
+----------+------------------------------------------------------------------+--------------------------------------+
| 49607779 | https://libranet.de/objects/0b6b25a8-1560-b691-7f12-846744488797 | 0b6b25a8-1560-b691-7f12-846744488797 |
+----------+------------------------------------------------------------------+--------------------------------------+
```

**Looking for the details of that uri-id:**
```
MariaDB [friendica]> select uid, protocol, network, gravity, wall, `contact-id`, `owner-id`, `author-id`, `causer-id` from `post-user` where `uri-id` = '49607779';
+------+----------+---------+---------+------+------------+----------+-----------+-----------+
| uid  | protocol | network | gravity | wall | contact-id | owner-id | author-id | causer-id |
+------+----------+---------+---------+------+------------+----------+-----------+-----------+
| 2911 |       10 | dfrn    |       0 |    1 |    1261042 |  1261041 |    505353 |      NULL |
|    0 |     NULL | dfrn    |       0 |    0 |     505353 |   505353 |    505353 |      NULL |
| 2683 |     NULL | dfrn    |       0 |    0 |     505353 |   505353 |    505353 |      NULL |
|    2 |        9 | dfrn    |       0 |    0 |     505445 |   505353 |    505353 |      NULL |
| 1990 |        9 | dfrn    |       0 |    0 |     983077 |   505353 |    505353 |      NULL |
| 2974 |        9 | dfrn    |       0 |    0 |    1295544 |   505353 |    505353 |      NULL |
+------+----------+---------+---------+------+------------+----------+-----------+-----------+
```

**Looking for the uid of the local user:**
```
MariaDB [friendica]> select uid from user where nickname like '%thelocaluser%';
+------+
| uid  |
+------+
| 2911 |
+------+
```

Can you spot anything weird that could possibly be the source of the problem?

### Steps to Reproduce

1.  Really,
2.  no
3.  idea.

**Actual Result:**

Own post is missing on own wall/profile/status/home stream.

**Expected Result:**

Own posts should always show up on the user's wall/profile/status/home stream.

### Platform Info

Friendica Version:

2021.06-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
Umm. The owner-id in this row is not identical to the author-id.

```
+------+----------+---------+---------+------+------------+----------+-----------+-----------+
| uid  | protocol | network | gravity | wall | contact-id | owner-id | author-id | causer-id |
+------+----------+---------+---------+------+------------+----------+-----------+-----------+
| 2911 |       10 | dfrn    |       0 |    1 |    1261042 |  1261041 |    505353 |      NULL |
...
...
```

In fact, the owner-id is the contact id of one of the re-sharers of the original post.

```
MariaDB [friendica]> select name from contact where id = '1261041'; 
+-----------------+
| name            |
+-----------------+
| bicycling group |
+-----------------+
```

### 'bicycling group' is mentioned in the original post and it is an account from that gup.pe stuff.

Maybe that's important...

**Comment by annando** [comment]
@AlfredSK thanks for your investigations! It is a side effect of our forum handling. gup.pe is a forum service. And so Friendica behaves like it does for our own forums as well, we transfer the ownership to the forum upon posting.

This behaviour will be changed in the future.

**Comment by AlfredSK** [comment]
Probably fixed by #10372

**Comment by AlfredSK** [comment]
I'm waiting for confirmation of the user who reported the issue with gup.pe in my local support forum.

**Comment by AlfredSK** [comment]
I got a report from my user. It works as expected now. Great. Thank you!
