### ISSUE TITLE
ldap_autocreateaccount wrong parameterlist

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10378]
- [x] I have searched open and closed issues for duplicates

### Bug Description

ldap_autocreate=>true does not create a user. error is "mail-adress is not valid"
i put in a debug-line to show the invalid email-adress and found out, that the password is used as email!!

so i found this line
https://github.com/friendica/friendica-addons/blob/b300d27d19549f52907f101bb62dbda8aa359446/ldapauth/ldapauth.php#L151
```
ldap_createaccount($ldap_autocreateaccount, $username, $password, $emailarray[0], $namearray[0]);
```
which calls the function 
https://github.com/friendica/friendica-addons/blob/b300d27d19549f52907f101bb62dbda8aa359446/ldapauth/ldapauth.php#L183
```
function ldap_createaccount($username, $password, $email, $name)
```
The "$ldap_autocreateaccount" is to much in the call, so $password is used as $email... 

Removing "$ldap_autocreateaccount, " in the call creates the account, and i can login (even if the account does not exist before login).

### Platform Info

Friendica Version:

2021.06-rc

**Comment by MrPetovan** [comment]
Good catch, I don't know what I was going for there, but in my defense I don't have an LDAP server to test these changes.

**Comment by MrPetovan** [comment]
@xundeenergie Can you please pull the latest RC branch for the addons and test my intended fix?
