### ISSUE TITLE
Searching for similar interests brings php-warning

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10386]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

Searching for "similar interests" brings php-warning. See screenshot at the end.

### Steps to Reproduce

1.  got to "contacts" page
2.  klickt on "find similar interests" 
3.  see screenshot

Actual Result:

see screenshot in description above

Expected Result:

no warnings

### Screenshots

![grafik](https://user-images.githubusercontent.com/5894829/121335160-a2a53200-c91a-11eb-87d1-34b039cb9642.png)

### Platform Info

Friendica Version:

2021.06-rc commit bb60ed409

Friendica Source: git

PHP version: 7.3

SQL version: mariadb 10.3

**Comment by tobiasd** [comment]
Pert of  #10169

**Comment by annando** [comment]
It is recommened to log the PHP warnings and notices into some log file instead of printing them on the screen. This can have ugly side effects and is considered insecure as well.
