### ISSUE TITLE
Add an RSS/Atom feed button on a profile page

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10397]
This can be a simple addition I suppose. On each profile page to add a Friendica RSS/Atom button of the account, so that anyone can follow the RSS if they wish to. I am talking about people who do not want to use any particular platform to follow accounts.

**Comment by SpcCw** [comment]
Is this button still there? I vaguely remember seeing it somewhere but recently I was asked about it and I can't locate it.

UPD: Found it. It is shown only when viewing the profile page while not logged on. It isn't displayed when viewing your own profile or someone's profile finding them from your own server.

**Comment by tio-trom** [comment]
It is for me:
![2023-01-29_15-33](https://user-images.githubusercontent.com/38043315/215333492-986f186f-38d6-453b-bf8d-df17a8de5edc.png)

**Comment by n8chz** [comment]
I can't find it anywhere, logged in or otherwise, own profile or otherwise. Is there a recipe to construct the feed URL from the profile URL?

**Comment by MrPetovan** [comment]
The format is `https://<node domain>/feed/<username>`

This means you can replace `profile` by `feed` in the URL of any Friendica profile to obtain the RSS feed.
