### ISSUE TITLE
Remove Diaspora Relay functionality

### ISSUE THREAD

**Issue by annando** [friendica/friendica#10400]
Additionally to the ActivityPub based relay functionality we do support the Diaspora based relay functionality.

The support for the relays had now been removed from the Diaspora core and won't be part in their next release anymore, see this issue: https://github.com/diaspora/diaspora/pull/8243

I think we should do the same and should remove the configuration where one can enter a relay name in the admin back end. The whole other configuration will stay the same since it is used for the ActivityPub relay functionality as well. Also I would like to keep the "direct relay" functionality which uses the endpoints that had been created for the Diaspora relay functionality.

**Comment by AlfredSK** [comment]
> I think we should do the same and should remove the configuration where one can enter a relay name in the admin back end. 

Wouldn't it be a good idea to add the AP relay configuration at that place? ;-)

**Comment by annando** [comment]
Do you know a frontend developer who could do this?

**Comment by AlfredSK** [comment]
I was expecting this. That's why I added the smiley. :-)

**Comment by MrPetovan** [comment]
What exactly do we need for the frontend? Half a dozen of form fields?

**Comment by annando** [comment]
It should be a dynamically growing list. And when an address is added, the feedback has to be respected, since you need to know if a subscription worked or not.

**Comment by MrPetovan** [comment]
What feedback?

**Comment by AlfredSK** [comment]
I think the feedback is the accept or reject response the relay is sending for our follow request.

**Comment by annando** [comment]
@AlfredSK exactly. I would like to have a separate page, only for the relay settings including the list of all relays where one could add and remove them. Also there should be a functionality to resubscribe. I guess that we could get some functionality from the user list.

**Comment by MrPetovan** [comment]
Thank you for the elaboration.
