### ISSUE TITLE
Tags parsed from code in comments.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1041]
In this example, the # character from the comments was considered a tag. Probably `[code]` tags should be ignored.
![Code example](http://ss.oscp.info/2014-07-09_20-17-14.png)
^ Note the #forward tag.

https://fc.oscp.info/display/beanow/1423

**Comment by annando** [comment]
There is a related bug: anchor links are detected as hashtags as well. Maybe you could address this as well?

Example:
````
[url=http://domain.tld/sample.html#anchor]Some stuff[/url]
````

**Comment by fabrixxm** [comment]
Ok

**Comment by fabrixxm** [comment]
@annando I can't reproduce the link bug

**Comment by annando** [comment]
Have you also tried this one?
````
[url]http://domain.tld/sample.html#anchor[/url]
````
I have seen this some times, but hadn't had time to reproduce it.

**Comment by fabrixxm** [comment]
mmh.. bcode `[url]http://domain.tld/sample.html#anchor[/url]` is not rendered in html

    test
    [url]http://domain.tld/sample.html#anchor[/url]
   
gives only

    test<br/>

I think is because is invalid. According to our help, `[url]` tag must be in the form `[url=href]text[/url]`

And, a post like:

    Follow this link, Alice:
    http://domain.tld/sample.html#anchor

correctly don't get `#anchor` as a tag

**Comment by annando** [comment]
Okay. Then I have to check, where exactly this problem occured.
