### ISSUE TITLE
[API] Compatibility with Mastonaut: missing header image URLs in contact

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10424]
I had contact with the developer of Mastonaut and he found out why you can't enter Friendica.

> It seems Friendica is returning an empty string for a couple of fields where a URL is expected (header and header_static).

![image](https://user-images.githubusercontent.com/12276250/123156795-03c81c00-d46a-11eb-9db5-b5668fc13900.png)

Maybe this also fixes some problems with the other Mastodon clients

**Comment by brunophilipe** [comment]
Hey! Mastonaut developer here. I will tweak Mastonaut to support empty/null URLs but I think this would benefit from being fixed on the Friendica side as well because it might cause other clients to hiccup as well.

**Comment by MrPetovan** [comment]
Thank you for the suggestion, I don't think it's something we have to "fix", profile header images is a feature we aren't currently offering so we can't make up a value here. However we are looking into implementing this feature, which is a more substantive time investment than just a fix.

**Comment by brunophilipe** [comment]
What Mastodon does is return the URL for a placeholder image here if the user has no header. I think returning `null` rather than an empty string would already be better, though (even though this wouldn't fix Mastonaut support in the current release version as it expects a valid URL). This will be fixed soon though.

**Comment by MrPetovan** [comment]
It makes sense for software offering optional header images to have a placeholder ready, but we don't have this feature at all yet so we don't have a default image we could use as placeholder. Thank you for your work on being more accepting of exotic servers like Friendica!

**Comment by annando** [comment]
In some PR in the last days I added a blank picture when no header was found: https://github.com/friendica/friendica/blob/2021.06-rc/src/Object/Api/Mastodon/Account.php#L119

**Comment by Tealk** [comment]
i just installed the latest version 2021.06-rc - 1423
now i could add the account

**Comment by MrPetovan** [comment]
Can you please close the issue if you consider it resolved?
