### ISSUE TITLE
Twitter Addon: Missing profile pictures for retweets 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#10431]
##

- [x] I have searched open and closed issues for duplicates

### Bug Description

On Twitter, if a piece of content was retweeted or a piece of content was re-shared and also added text, the profile picture of the shared profile is no longer submitted and displayed in friendica. 

`Fehlerhaftes Foto mit der ID 2753220.

#0 [internal function]: Friendica\Module\Photo::rawContent(Array)
#1 /var/www/html/friendica/src/App/Module.php(333): call_user_func(Array, Array)
#2 /var/www/html/friendica/src/App.php(562): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Object(Friendica\Util\Profiler), Array, Array)
#3 /var/www/html/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1624640534.5128)
#4 {main}`

### Steps to Reproduce

Actual Result:

Expected Result:

### Screenshots
![Screenshot 2021-06-25 at 17-53-23  ˈloma  Network](https://user-images.githubusercontent.com/44441246/123453621-06e51880-d5e0-11eb-939c-5171884a3aa9.png)
---
![Screenshot 2021-06-25 at 18-21-49  ˈloma  Network](https://user-images.githubusercontent.com/44441246/123455742-5c222980-d5e2-11eb-886d-b33f856b0b6a.png)
---
![Screenshot 2021-06-25 at 17-53-45  ˈloma  Network](https://user-images.githubusercontent.com/44441246/123453539-f7fe6600-d5df-11eb-9bd6-a81f80a1cb38.png)
---
![Screenshot 2021-06-25 at 17-52-17  ˈloma  Network](https://user-images.githubusercontent.com/44441246/123453580-0056a100-d5e0-11eb-8146-7810c3afe026.png)

### Platform Info

Friendica Version:

Friendica 'Siberian Iris' 2021.06-rc - 1423

Friendica Source: 

https://github.com/friendica/friendica

PHP version:

7.4

SQL version:

10.3

**Comment by MrPetovan** [comment]
I'm not able to reproduce this on my single-use node, can you please paste examples of images not loading?

**Comment by AlfredSK** [comment]
I participated in the forum discussion. Later I've checked my own stream for those "quoted re-tweets" (retweets with additional text). They are looking ok on my node - even if the retweeted user is unknown to me (not a twitter contact of mine). Hmm.

**Comment by loma-one** [comment]
I have now reinstalled all the addon again and see if that was the cause. If so, I will close the error.

**Comment by annando** [comment]
Please check the contact entry for the url of the quoted user. Please check if the fields `photo` or `avatar` are filled. And please check the `uid` as well. At least there should be data for the `uid` with the value `0`.

**Comment by loma-one** [comment]
some pull request on the addon seems to have gone wrong. After I reinstalled the addon it looks good again.

![Screenshot 2021-06-25 at 19-10-58  ˈloma  Network](https://user-images.githubusercontent.com/44441246/123461272-31879f00-d5e9-11eb-8a86-a1a5c139413c.png)

**Comment by loma-one** [comment]
The problem is still there.It also occurs on other profiles on the server (https://loma.ml/display/373ebf56-6960-d5de-ab06-4a5275569071).
When I follow the profile picture and open it in a new tab, the following message appears.

```
Interner Serverfehler

Fehlerhaftes Foto mit der ID 2384218.

#0 [internal function]: Friendica\Module\Photo::rawContent(Array)
#1 /var/www/html/friendica/src/App/Module.php(333): call_user_func(Array, Array)
#2 /var/www/html/friendica/src/App.php(562): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Object(Friendica\Util\Profiler), Array, Array)
#3 /var/www/html/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1624649351.6279)
#4 {main}
```

PHP error log
```
[Fri Jun 25 21:37:05.737249 2021] [proxy_fcgi:error] [pid 16187:tid 140501424514816] [client 84.176.239.66:32938] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/friendica/a1/f6/3a8661b77b61cc758aaa5943c802246a40575c60689109f8b0ddfb241e46): failed to open stream: Permission denied in /var/www/html/friendica/src/Model/Storage/Filesystem.php on line 128'
```

The permissions on the directory are correctly set to www-data

---

I don't know if it has to be that way... some of the profile pictures are stored in the storage with root rights. But this does not happen with all images

---

I gave the images the correct rights in the storage and they are visible again. So the question is, why are they stored with the wrong rights?

**Comment by annando** [comment]
Under which permissions is the worker task executed?

**Comment by loma-one** [comment]
It is started as deamon under Systemd with these rights: 
[Service]
User=www-data
Group=www-data

**Comment by loma-one** [comment]
I stopped the daemon and restarted it, as I can't rule out that I started it manually at some point and maybe with root rights. 
Observe this now for now
