### ISSUE TITLE
Side-Effects at Addon settings page

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#10439]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Based on https://github.com/friendica/friendica/issues/10314#issuecomment-869060328

If one addon is using a required field, every other setting in the addon page depends on this required field.
This is a design flaw inside the addon settings page, because we're using one form for the whole setting page instead, which causes this effect.

### Steps to Reproduce

1.  Activate Cat Avatar
2.  Before https://github.com/friendica/friendica-addons/pull/1140 - Activate SecureMail
3.  Got to Settings > Addon and try to recreate a cat avatar

Actual Result:

The button is blocked because of the required field at Secure Mail

Expected Result:

Each section should have it's own fields and therefore one Addon setting shouldn't harm another addon setting

### Screenshots

![grafik](https://user-images.githubusercontent.com/379654/123557308-8580b800-d790-11eb-9f8b-911b3d96f2d9.png)

### Platform Info

Friendica Version: 2021.06-tc

Friendica Source: git

PHP version: php7.5

SQL version:

**Comment by MrPetovan** [comment]
Oof, that's bad. I can look into it.
