### ISSUE TITLE
friendica_test_data.sql is out of date

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#10457]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Our testdataset https://github.com/friendica/friendica/blob/2021.06-rc/friendica_test_data.sql is out of date. It's not possible to upgrade it anymore since breaking changes at 2021.01.

I tried manually upgrade it step by step, but I bricked it at every attempt.
And I had to skip serveral `upgrade.php` functions because of incompatibility (we should add `DBStructure::tableExists()` for a lot of direct DB-manipulations ...)

### Steps to Reproduce

1.  Use the `Vagrantfile` to setup an environment for the current branch 2021.06-rc
2.  Start it
3.  Bang :)

### Platform Info

Friendica Version: 2021.06-rc

Friendica Source: git

PHP version: 7.4

SQL version:

**Comment by annando** [comment]
I don't know how to update it.

**Comment by tobiasd** [comment]
It is not used for the Vagrant development VM anymore, IIRC @fabrixxm switched to automatically user generation via the console tool. Importing from that file is commented out in the [provision script](https://github.com/friendica/friendica/blob/2021.06-rc/bin/dev/vagrant_provision.sh#L111).

**Comment by MrPetovan** [comment]
So we probably should just ditch this file.

**Comment by tobiasd** [comment]
Is it used for anything else?

**Comment by MrPetovan** [comment]
Nope, no other mention in the whole Friendica codebase.

**Comment by annando** [comment]
So can we remove that file?

**Comment by MrPetovan** [comment]
Go ahead!
