### ISSUE TITLE
New accounts broken - no possibility to follow and other anomalies

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10464]
- [YES] I have searched open and closed issues for duplicates

### Bug Description

We have a problem in the current RC with new accounts. They can't be followed and behave partly wrong.

At first someone found out that forum accounts created via account management cannot be found and are losing their contact type 'forum' after following manually.

Discussion (mostly German): https://forum.friendi.ca/display/661564f3-3660-deb5-54e6-826955251233

So I tried to reproduce (it) ;-) and I found out the problem is a more general one.

It has nothing to do with account management or account types. **The actual problem is that ALL new accounts can't be followed via their public contact page.** There is NO BUTTON to follow them and no 'follow' entry in the contact's action menu. This is only happening with LOCAL accounts (both are on the same server).

The only way to follow those new accounts is to go to the /contacts page, enter their complete webfinger address in the 'add new contact' field and hit 'connect.

**Addional info about new accounts of type forum:**
And that's where the other/related issue with forum contacts happens. If you do that with a NEW local forum account, the contact is losing its type 'forum' in the very moment you hit 'connect'. After that the new forum doesn't behave like a forum contact but like a normal personal contact.

**Minor obstacle with new accounts:**
When a user decides not to be listed locally or globally it is ok to not being able to search and find the new user via the search field. That's the intended behavior, I guess. But in my opinion it should be possible to find the new user LOCALLY when the user has enabled the option to be listed in the local directory.
The `[hide] => 1` field is preventing that a user can be found via search. But it is exclusively triggered by the setting for the 'global' search (allow your profile to be searchable globally).

### Steps to Reproduce

1.  create a new local user account
2.  login to the new account and configure it
3.  go back to your old, personal account
4.  try to find the new user/account via search (hard)
5.  if you found the new account (actually the public contact) try to follow it
6.  becoming aware that there is no 'follow' button' and no other way to establish a connection with the new account
7.  you may go to /contacts, enter the webfinger in 'add new contact' and hit 'connect' -> this will work
8.  IF the public contact was of type 'forum' you'll notice that the contact has lost its type 'forum' now

**Actual Result:**
New, local accounts can't be followed. New, local forum accounts are losing their type 'forum' when added manually to the contacts.

**Expected Result:**
A possibility to follow new, local accounts. Forum contacts should stay forum contacts. 

### Screenshots

![fr-nofollow-button](https://user-images.githubusercontent.com/3656054/124384852-7d1a0700-dcd3-11eb-9920-f8a2e03800f5.png)
The follow button is missing

![fr-noforum](https://user-images.githubusercontent.com/3656054/124384857-85724200-dcd3-11eb-89d3-f53e1c657469.png)
The contact is no forum anymore

### Platform Info

Friendica Version:
2021.06-rc 1424

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by annando** [comment]
The additional information problem is fixed by PR https://github.com/friendica/friendica/pull/10465

**Comment by AlfredSK** [comment]
Interesting: there is **no network type** displayed in image 1 (should be 'friendica'). But the probe was showing the new account as DFRN, if I remeber corrcectly.

Probe of the new forum account:

```
Array
(
    [name] => Forentest Xyz
    [nick] => forentestxyz
    [guid] => 0b6b25a8-1260-e191-69f0-ea9468591143
    [url] => https://libranet.de/profile/forentestxyz
    [addr] => forentestxyz@libranet.de
    [alias] => https://libranet.de/~forentestxyz
    [photo] => https://libranet.de/photo/165734973860e1916a6719c489182548-4.jpg?ts=1625395562
    [header] => 
    [account-type] => 3
    [community] => 1
    [keywords] => 
    [location] => 
    [about] => Nur ein Test
    [hide] => 1
    [batch] => 
    [notify] => https://libranet.de/dfrn_notify/forentestxyz
    [poll] => https://libranet.de/dfrn_poll/forentestxyz
    [request] => https://libranet.de/dfrn_request/forentestxyz
    [confirm] => https://libranet.de/dfrn_confirm/forentestxyz
    [subscribe] => https://libranet.de/follow?url={uri}
    [poco] => https://libranet.de/poco/forentestxyz
    [following] => https://libranet.de/following/forentestxyz
    [followers] => https://libranet.de/followers/forentestxyz
    [inbox] => https://libranet.de/inbox/forentestxyz
    [outbox] => https://libranet.de/outbox/forentestxyz
    [sharedinbox] => https://libranet.de/inbox
    [priority] => 0
    [network] => dfrn
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5Zb6+0XU3IT28bBgJ2U3
i65lwGNy9yZzhUbYZbEB89KhSeMf3GJ9yEENbgoEE5fcDO3Ovn5dWgE6E0kk1EeT
3wHQQewS8Bp5tTCtSgS/edKV+ubv0+PyMe2d5gh1GfaSOgWfGnBwzOmI3kSQjfdd
qoWMDEN5AXXapHROdE5GNVBQkA3cw+Fvvq6IeurNkNqp93FtUKXxXz6jpxWjTa3H
SndQGiD/bNbmUE49Sj5A6x3uF60YFKDQ1EgmeAbDKgkkpt8A5mPnM7K2EXOLJPSi
t9V3Ye8jkbNhhin3iYKmu7zh/ewXqvpqGhBz5OHDxLA/6Is8BE9jar70KvqENnw3
WZUTj7wBbKEJaGpnS+ooabiNZX2xVi9CV2B21WRxsYWtYpVAdc40sZ8Mg1twfjVv
1QsTXvRCrWxAhSwwYAJSziGoUzgen4BMl19ltUQmaW1YWCxN1PSG4z8f2cNv+hXu
EOLq1FE4q44PmcHh0oVd4Xn/3eAriQVa36yt5p+y96AaKNZjdfD9qKhSdyvI5Uxl
AKcp1W9nfC6wibDB3Xfe/Cj+96Jkta/wDbrF2JOmIn+icGMJ8p6Sndf/a+mMkdz2
Ymen0NzpRCdrLuANOM4ZWUFMwthQF4yx8iWyvzZ1OxK3zr0O9YV9qmiKgF7sMjUx
IvgNi8zmyt2pLNyZHCrA+/8CAwEAAQ==
-----END PUBLIC KEY-----

    [manually-approve] => 0
    [baseurl] => https://libranet.de
    [gsid] => 3
)
```

**Comment by AlfredSK** [comment]
Is this correct?

```
[subscribe] => https://libranet.de/follow?url={uri}
```

**Comment by AlfredSK** [comment]
Looks good. Tested successfully.

Fixed by #10465 and by #10466

**Comment by annando** [comment]
@AlfredSK one thing isn't done: The `hide` behaviour. We shouldn't forget about this. (in the next release)

**Comment by AlfredSK** [comment]
Yes. You're right. I can extract that part and create a new issue about it.
