### ISSUE TITLE
Shared block displays incorrectly with RTL display names

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10469]
_Originally posted by @AlfredSK in https://github.com/friendica/friendica/issues/8262#issuecomment-873558147_
> Ha! Found one. :-)
> 
> ![grafik](https://user-images.githubusercontent.com/3656054/124380777-f65b2f00-dcbe-11eb-96c1-6aaf33f14d4b.png)
> 
> Username and date of post are inserted on the right side. But it should be on the left side.
>  
> Steps to reproduce:
> 1. Import this post on your node https://venera.social/display/67851619-983298e32d387710-a32197cb
> 2. Or use the original https://persadon.com/@danialbehzadi/106521529502265000
> 3. Click on 'Quote Share'
> 4. Look at the preview
> 
> I only used the preview function to reproduce the issue. But the same happens with the submitted share.

**Comment by MrPetovan** [comment]
Thank you, this is perfect.

@ahangarha, what would be the expected display in this case?

**Comment by ahangarha** [comment]
This is how it should look I think:

![image](https://user-images.githubusercontent.com/11241315/124399823-58ee1280-dd33-11eb-950c-8683a6fd3621.png)

All I did was to change css properies from left|right to relevant bidi values like start|end. If this is fine, then let me know. I will send PR.

```
(absolute positioning)
left -> inset-inline-start
right -> inset-inline-end

float: left -> float: inline-start

margin-right -> margin-inline-end
```

**Comment by MrPetovan** [comment]
Thank you, I have no other source of truth than you in this matter, so I'll go forward with your display through your suggested values.

**Comment by ahangarha** [comment]
Does that mean you apply the style or I should do it?

**Comment by MrPetovan** [comment]
If you don't submit a PR yourself, I will based on your suggestion in the coming week.

**Comment by MrPetovan** [comment]
Unfortunately the `float: inline-start` value is only supported by Firefox, so the display name will not be aligned with the profile picture on any other browser.

See display on Chrome-based browser:
![friendica-share-block-bidi](https://user-images.githubusercontent.com/925415/125092500-68f15380-e09f-11eb-9066-8f2a9d440c1d.png)

I wonder if we can achieve the same look with flex blocks.

**Comment by MrPetovan** [comment]
It works with flex boxes!
![friendica-share-block-bidi-flex](https://user-images.githubusercontent.com/925415/125097841-84129200-e0a4-11eb-8f23-21e83608ee7a.png)

I took advantage of this change to increase the avatar size to match the height of the share block header.

Onwards to the other themes!

**Comment by ahangarha** [comment]
> I took advantage of this change to increase the avatar size to match the height of the share block header.

Actually it is a good improvement. Just I have a suggestion. If you are changing this, then it should also change in timeline as well. Logically the preview here should be as identical as possible to what would be shown in timeline.

I also assume UX also should be considered in this case. If one have mixed content in timeline, then would it be good to have some posts' header right to left and some others left to right? Not sure. I think we can try it and see the result in action.

**Comment by AlfredSK** [comment]
I would suggest the same display as we use for normal, top-level posts. The avatar on the left. The user name on the left - as we do it with LTR posts. But the content of the post on the right side.

Other ways would be too confusing. But that's only my point of view. Sorry that I'm German. 😋

**Comment by ahangarha** [comment]
I would agree to follow same layout for better UX.
