### ISSUE TITLE
view/theme/frio/js/event_edit.js conflicts with current Content Security Policies

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10477]
- [x] I have searched open and closed issues for duplicates

### Bug Description

when i click on the tab extended i get the following error message
```
Uncaught ReferenceError: eventDescActive is not defined
    onclick https://rollenspiel.group/events:1
```

### Steps to Reproduce

1.  call calendar
1.  create event

### Screenshots

![image](https://user-images.githubusercontent.com/12276250/124769170-c616c900-df28-11eb-9c5e-74b2492f5bc0.png)

### Platform Info

Friendica Version: 2021.07, Database 1424/1424, Post-Update-Version 1400/1400.

Friendica Source: GIT

PHP version: 7.4

SQL version: 10.5.10-MariaDB-1:10.5.10+maria~buster

**Comment by MrPetovan** [comment]
I can open the "Advanced" tab just fine on Vivaldi (Chrome) on Windows, what browser/OS are you using?

**Comment by MrPetovan** [comment]
The error you are getting refers to a Javascript function named `eventDescActive()` and declared in this file: https://rollenspiel.group/view/theme/frio/js/event_edit.js

Please make sure this file correctly loads on the calendar page.

**Comment by Tealk** [comment]
I use LibreWolf on MacOS

Seems to be the CSP, but I don't quite understand why.
`Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"`

unsafe-eval must still be entered for script
`Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"`

**Comment by AlfredSK** [comment]
I know the issues with the event calendar and a local CSP from own experience.

As far as I know the event calendar is the only place that doesn't work w/o `script-src 'unsafe-eval'`. It would be great if we could get rid of everything that requires the unsafe CSP `script-src 'unsafe-eval'`.

**Comment by Tealk** [comment]
yes that would be great
best would be of course if all `unsafe-*` would be removed

**Comment by MrPetovan** [comment]
Thank you for looking into it, I've renamed the issue to keep track of this problem.

**Comment by MrPetovan** [comment]
@AlfredSK @Tealk How did either of you enable this CSP Policy? I need to replicate it in order to test this file would pass it.

**Comment by Tealk** [comment]
@MrPetovan i use nginx and this in the vhost file: `add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'" always;`

**Comment by AlfredSK** [comment]
Manually via `.htaccess` like this...

``
Header set Content-Security-Policy "default-src 'none'; connect-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' https:; media-src 'self' https:; font-src 'self'; style-src 'self' 'unsafe-inline'; worker-src 'self'; object-src 'self'; base-uri 'self'; form-action 'self'; frame-src 'self' https:; manifest-src 'self';"
``

There are add-ons for browsers telling what's needed to make sure the site works as expected. Whenever you access the event calendar they are showing that 'unsafe-eval' is needed.

Edit: For Firefox 'Laboratory' works great to create/check a CSP.

**Comment by Tealk** [comment]
> `Header set Content-Security-Policy "default-src 'none'; connect-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' https:; media-src 'self' https:; font-src 'self'; style-src 'self' 'unsafe-inline'; worker-src 'self'; object-src 'self'; base-uri 'self'; form-action 'self'; frame-src 'self' https:; manifest-src 'self';"`
> 
> Edit: For Firefox 'Laboratory' works great to create/check a CSP.

if this was created by the FF extension it is unnecessarily inflated

**Comment by AlfredSK** [comment]
I used the add-on as a basis.  The CSP contains everything necessary to use a secure default policy 'none'.  Of course, you can use a simpler variant.
