### ISSUE TITLE
API: iOS Metatext Mastodon App shows HTTP ERROR: 500 when selecting "Messages"

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10494]
### Bug Description

iOS14.6
This is Friendica, version 2021.07 that is running at the web location https://squeet.me. The database version is 1424/1424, the post update version is 1400/1400.

There is another problem when selecting Explore (2nd bottom Tab) and clicking a trending hashtag, error is shown: `Could not process request (NSURLErrorDomain-Error-1000.)`. Just noticing this error message shows every single time whenever the timeline is refreshed.

### Steps to Reproduce

1.  open [Metatext](https://github.com/metabolist/metatext) on iOS and select `Messages` tab

Actual Result:

HTTP ERROR: 500

Expected Result:

Show messages. Not sure if this should already be supported or not.

### Screenshots

![metatext](https://user-images.githubusercontent.com/5708172/125428893-766d5411-dab5-4046-a976-4db2337d6106.jpg)

**Comment by annando** [comment]
I see it in the logs. Sadly on squeet.me the log level is not very verbose, so I can't see the reason why.

**Comment by MrPetovan** [comment]
I can take a look at it.

**Comment by annando** [comment]
You have got an iPad? Great.

**Comment by MrPetovan** [comment]
I've got an iPhone, yes, and FYI here's the PHP error:
```
[13-Jul-2021 22:55:24 America/New_York] PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Friendica\Object\Api\Mastodon\Conversation::__construct() must be an instance of Friendica\Object\Api\Mastodon\Status, null given, called in src/Factory/Api/Mastodon/Conversation.php on line 79 and defined in src/Object/Api/Mastodon/Conversation.php:47
Stack trace:
#0 src/Factory/Api/Mastodon/Conversation.php(79): Friendica\Object\Api\Mastodon\Conversation->__construct('1', Array, false, NULL)
#1 src/Module/Api/Mastodon/Conversations.php(89): Friendica\Factory\Api\Mastodon\Conversation->CreateFromConvId(1)
#2 [internal function]: Friendica\Module\Api\Mastodon\Conversations::rawContent(Array)
#3 src/App/Module.php(332): call_user_func(Array, Array)
#4 src/App.php(562): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Obje in src/Object/Api/Mastodon/Conversation.php on line 47
```
