### ISSUE TITLE
Twitter addon post trimming is unusable

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10491]
Working with the 2021.07 stable release.

The addon should trim posts only on character count (260) . Not on paragraphs or empty lines. 
This behavior makes the addon unusable.

I wrote this post in Friendica 
![01_temp](https://user-images.githubusercontent.com/24474762/125255441-b8cc5680-e2fb-11eb-89f0-da3372322884.jpg)

And on Twitter it shows
![00_temp](https://user-images.githubusercontent.com/24474762/125255477-c41f8200-e2fb-11eb-8c14-a347f296c0bd.jpg)

**Comment by annando** [comment]
This is not a bug. You can disable this behaviour in the general connector settings. Also you can define an `[abstract]...[/abstract]` section for an abstract that is send to Twitter.

**Comment by hoergen** [comment]
Hm, besides I can't find such a setting (user / admin) the default setting should only trim within the technical specs (length)

**Comment by annando** [comment]
It's in the general settings at `/settings/connectors`.

**Comment by hoergen** [comment]
Hehehe yes, I know where the connector settings are, but which setting?

- Ausschließlich Unterhaltungen von meinen Kontakten anzeigen 
- Inhaltswarnung ausschalten 
- Intelligentes Link-Kürzen ausschalten 
- Link Titel hinzufügen 
- Automatisch allen GNU Social (OStatus) Followern/Erwähnern folgen 
- Veröffentlichung bei Twitter erlauben 
- Veröffentliche öffentliche Beiträge standardmäßig bei Twitter 
- Spiegle alle Beiträge von Twitter, die keine Antworten sind 
- Importiere die Remote-Zeitleiste 
- Automatisch Kontakte anlegen 

That's all I have as general settings and settings for Twitter.

**Comment by annando** [comment]
> Intelligentes Link-Kürzen ausschalten
> Normalerweise versucht das System, den besten Link zu finden, um ihn zu gekürzten Postings hinzuzufügen. Wird diese Option ausgewählt, wird stets ein Link auf die originale Friendica-Nachricht beigefügt.

**Comment by hoergen** [comment]
Oh really? Ok. I have to check the english description. I would have never thought that this option is responsible for that behavior.

**Comment by annando** [comment]
> Disable intelligent shortening
> Normally the system tries to find the best link to add to shortened posts. If this option is enabled then every shortened post will always point to the original friendica post.

**Comment by annando** [comment]
I just saw that independent from that setting the system will try to make a cut at a line feed. But that's no bug.

**Comment by hoergen** [comment]
I see, but the description doesn't reflect what it is actually doing. It just talks about a link and most people would assume tailoring an URL .. not trimming the text.

**Comment by annando** [comment]
Yes, the setting is for something different.

**Comment by hoergen** [comment]
Now I'm totally confused ... is this setting made for solving my problem or is it for something different?

**Comment by annando** [comment]
Yes.


The second option.

**Comment by hoergen** [comment]
Hmmm .. ok if you are not talking about the topic we should stop this discussion until someone is joining who wants to discuss the topic and tries to bring the problem to a solution :(

Thank you for your understanding.

**Comment by annando** [comment]
After looking in the code I realized that the setting wasn't causing this behaviour.

**Comment by annando** [comment]
New option added:
![grafik](https://user-images.githubusercontent.com/844208/125302422-37d98300-e32c-11eb-89bb-abdca693fd21.png)

**Comment by hoergen** [comment]
Thanks a lot. I will close this issue :+1:
