### ISSUE TITLE
Enable interaction on the community tab

### ISSUE THREAD

**Issue by MartinBober** [friendica/friendica#1050]
# Situation

There is no interaction possible with post displayed in the community tab, i.e. posts that are public but posted by people who are not connected with you.
# Reasoning

As I understand, this behavior is a spam protection feature which makes sense on public servers. However, on closed servers where the community tab could be a place for open discussions, this behavior is somewhat unexpected and undesired.
# Solution

Make this spam protection an option (default: on)

**Comment by Beanow** [comment]
I think this is inconsistent with how other pages work. If possible we should allow interaction.

**Comment by annando** [comment]
Interaction is partly possible. It will be no problem with Diaspora accounts and public postings. With OStatus it might be possible - but I don't know the protocol good enough. And finally: I haven't checked the Friendica protocol by now.

At the moment I'm making preparations that could be used for things like that in the future.

**Comment by annando** [comment]
With the release 3.6 this is now done.

**Comment by annando** [comment]
I think we should close the issue.
