### ISSUE TITLE
Back from Developer to stable

### ISSUE THREAD

**Issue by poltrian** [friendica/friendica#10504]
hello, I accidentally installed the Developer 2021.09. How can I get back to the stable 2021.07? It was installed via Git.
In the 2021.09 the search does not work properly, at least not for me. There are no "previews" and no local users and forums

**Comment by annando** [comment]
The develop should work fine. Switching back is always hard. I just switched squeet.me from stable to develop - and it worked great. I guess that the update hadn't went through. Please execute `bin/console dbstructure update`

**Comment by poltrian** [comment]
@annando 

it was a fresh installation and  after `bin/console dbstructure update` the search still won't work

**Comment by poltrian** [comment]
I followed the guide https://wiki.friendi.ca/de/docs/install and can*t remember to switch to developer. But this is shown in overview:
Friendica 'Siberian Iris' 2021.09-dev - 1429

**Comment by annando** [comment]
What do you mean with "fresh"? Have you started from scratch with a new host name?

**Comment by poltrian** [comment]
Yes, my first installation

**Comment by poltrian** [comment]
My first account is on squeet.me and I saw that you are on Developer. If I search there with @username, a list of suggestions is immediately displayed, on my instanz no local user is found for me. And I have no idea what's wrong with that

**Comment by annando** [comment]
When you search for local users these users have to have their profile published to the global or local directory.

**Comment by poltrian** [comment]
xes i know, an they have it. If you like you can do a test

**Comment by poltrian** [comment]
I have also a Mastodon account. If i try a search to my i type 3 signs and a small window pops up and show all names with 3 signs. Ans see my Mastodon account. In my Friendica i have to type the full adress and not windows pop up. So something should be wrong?

**Comment by poltrian** [comment]
![Bildschirmfoto vom 2021-07-16 07-29-11](https://user-images.githubusercontent.com/50879520/125897548-2d20ba55-4ff0-4f1a-b074-746692de1cb6.png)
@annando is these a special from you side?

**Comment by annando** [comment]
Is this installation really new? If yes, then the system currently doesn't know that much contacts. Also the question is if you have activated the auto discovery of contacts (in the site settings). Squeet.me has got a larger user base, so there is much more to find.

When you execute the following query then you see how much contacts your server does know:
```
select count(*) from contact where uid=0 and not failed and network in ('dfrn', 'apub', 'dspr', 'stat');
```

On squeet.me the system does know around 480,000 contacts, on pirati.ca it does know nearly 690,000 contacts. For this reason the system really does find a lot of them, if you search for it.

**Comment by poltrian** [comment]
` network in ('dfrn', 'apub', 'dspr', 'stat');tact where uid=0 and not failed and 
+----------+
| count(*) |
+----------+
|    13677 |
+----------+
1 row in set (0.022 sec)`
hmm then the Popup comes only at a minimum on users? i have add  relay from metalhead, same as Mastodon. 
when I enable Direct Relay Transmission, I get a lot of dirty content 

auto discovery of contacts settings are correct?

![grafik](https://user-images.githubusercontent.com/50879520/125903696-b3715fa8-cfbf-416e-b78a-717564e6ca3a.png)

**Comment by poltrian** [comment]
ok local directory did the trick. Now i have also the small users windows. And i find me in the fedivers :-) thank you for your patience @annando
