### ISSUE TITLE
Option RSS Mirror Missing

### ISSUE THREAD

**Issue by poltrian** [friendica/friendica#10500]
I can not activte RSS Mirror in the RSS Contact. The option is not shown

![grafik](https://user-images.githubusercontent.com/50879520/125687604-0f2cf45e-1aa6-45f6-a413-d405d3ab4f01.png)
 on another instanz

![grafik](https://user-images.githubusercontent.com/50879520/125687808-c0b67683-f1bd-440f-b738-6e5b25708cb2.png)

What's wrong in my configuration?

**Comment by AlfredSK** [comment]
This needs to be enabled in the admin panel first. Admin > Site > Policies > Allow users to set "Remote self".

**Comment by poltrian** [comment]
found it thanks
