### ISSUE TITLE
Search finds nothing

### ISSUE THREAD

**Issue by poltrian** [friendica/friendica#10501]
The search in my instance finds nothing. I have created a forum, it is not found either. I get a white page when I search !forum. At the bottom you can scroll to page 2, but this is also empty.

What do I have to do to fix the problem?

**Comment by annando** [comment]
Are you using Apache or nginx?

**Comment by poltrian** [comment]
Apache

**Comment by poltrian** [comment]
When type @poltrian there is nothing. When type the hole adress, there is no list/peview bit the user will be found. But all other poltrian not

**Comment by poltrian** [comment]
see #10504
