### ISSUE TITLE
Federation of Pictures to Mastodon

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#10506]
- [X] I have searched open and closed issues for duplicates

### Bug Description

For posts with multiple images, only one image is displayed on (or federated to) Mastodon.

### Steps to Reproduce

1. Create a post with more than one image
2. Send the post
3. View post on Mastodon

Actual Result:
Only one picture is visible

Expected Result:
All pictures are visible

### Screenshots

![ansicht-auf-friendica](https://user-images.githubusercontent.com/12498438/125982055-6c90f9bb-a239-47bf-a1f6-6b9f94bcf45b.png)
This is how it looks at Friendica (and Diaspora)
 
![ansicht-auf-mastodon](https://user-images.githubusercontent.com/12498438/125982059-45c7035e-cc45-41db-8efe-f01171822453.png)
This is how it looks at Mastodon

### Platform Info

Friendica Version: 2021.09-dev

Friendica Source: git

PHP version: 7.4.21

SQL version:

**Comment by annando** [comment]
How have you created the post? Via API or via desktop?

**Comment by atasingorneq** [comment]
Via Desktop. And i create a private test on my own system friendica.xyz and on my test account on libranet, with the same result. The mastodon account is on social.tchncs.de

**Comment by annando** [comment]
Can you make a test via API as well?

**Comment by atasingorneq** [comment]
Done. When creating a post via the API, all images are visible.

**Comment by atasingorneq** [comment]
I think, the bug is not really solved.

All images are now visible on Mastodon, but they are now shown twice on Friendica and Diaspora.

**Comment by annando** [comment]
Your pictures deserve it to be shown multiple times! :grinning:
