### ISSUE TITLE
API: Last login isn't updated when receiving a valid OAuth token

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10518]
See starting conversation: ~~https://nerdica.net/display/a85d7459-1460-e991-e5d3-02b203528993~~ (post deleted)

Basically, in the API we only update a user's last login date when we issue an OAuth token or when Basic Auth is used. When a valid OAuth token is used, we don't update this important value used to purge inactive accounts.

The solution would be to funnel all the authentication methods into `Auth->setForUser()`, whether it is OAuth (all the code paths) or Basic Auth.

**Comment by annando** [comment]
Since we don't have session data on OAuth requests we should only update the login date when it is really changed. And we shouldn't simply call `setForUser` since would be a massive overhead.

**Comment by MrPetovan** [comment]
Please read the original thread, simply using a OAuth token to interact with Friendica exposes one's user account to be deleted if there's a recent activity requirement.

We update the login date when we log in via session even though there was no user credential submission, so we should do it for API tokens as well. There's even a cooldown of 12 hours to prevent frequent last login updates for API requests when they go through `api_login()` but the valid OAuth token bypasses `api_login()` entirely which it probably shouldn't.

**Comment by annando** [comment]
Yes, we have to update the login date. Only thing is: We shouldn't call `setForUser` directly since this would had to be done with each single request (since we don't have session with the OAuth calls)

**Comment by MrPetovan** [comment]
What's the problem of calling it for every single request since we call it for the initial OAuth token request?

**Comment by annando** [comment]
We are setting session variables in that function - without even having a session. So this is superfluous. Also it normally is called during the login, so only once in a session. But with OAuth it would be called with each and every API call, so it would be called several dozen times per second when using an app.

**Comment by MrPetovan** [comment]
Time to break out this method then, it does too much at once.

**Comment by annando** [comment]
Yes

**Comment by annando** [comment]
@MrPetovan Do you see this issue solved with PR https://github.com/friendica/friendica/pull/12324?

**Comment by MrPetovan** [comment]
It should, yes.
