### ISSUE TITLE
All Posts Gone after Upgrade from 2020.09 to 2021.07

### ISSUE THREAD

**Issue by Xipherisroot** [friendica/friendica#10519]
Performed the standard upgrade as per usual, the result is that every post is gone and the database upgrade seems to have failed?

- PHP Version 7.4.21
- 
- MariaDB 10.3.30

The output I get for the "bin/console.php dbstructure update" command is:

> CREATE TABLE IF NOT EXISTS `parsed_url` (
>         `url_hash` binary(64) NOT NULL COMMENT 'page url hash',
>         `guessing` boolean NOT NULL DEFAULT '0' COMMENT 'is the \'guessing\' mode active?',
>         `oembed` boolean NOT NULL DEFAULT '0' COMMENT 'is the data the result of oembed?',
>         `url` text NOT NULL COMMENT 'page url',
>         `content` mediumtext COMMENT 'page data',
>         `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of creation',
>         `expires` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of expiration',
>          PRIMARY KEY(`url_hash`,`guessing`,`oembed`),
>          INDEX `created` (`created`),
>          INDEX `expires` (`expires`)
> ) DEFAULT COLLATE utf8mb4_general_ci COMMENT='cache for \'parse_url\' queries';

I have no idea what the issue could be since the upgrade process was smooth with no issues I could see, I'd certainly like to get my instance back up and running though...

**Comment by annando** [comment]
Please execute `drop table parsed_url;` in the MySQL console and run `bin/console dbstructure update` again.

**Comment by Xipherisroot** [comment]
> 
> 
> Please execute `drop table parsed_url;` in the MySQL console and run `bin/console dbstructure update` again.

Gotcha, I've dropped the offending table and I get no output when I run that command again, however all prior content still seems to be missing...  and in the admin panel I still see the message "The last update failed. Please run "php bin/console.php dbstructure update" from the command line and have a look at the errors that may appear in the console and logfile output."

**Comment by annando** [comment]
What is the system telling when you call `/friendica` on your system?

**Comment by Xipherisroot** [comment]
> 
> 
> What is the system telling when you call `/friendica` on your system?

I get the following:

> This is Friendica, version 2021.07 that is running at the web location https://redactedurl. The database version is 1424/1395, the post update version is 1400/1383.

**Comment by annando** [comment]
Okay. So the main update hadn't been finished at all. Please have a look at your friendica log file with entries with "DB Error" in it.

**Comment by Xipherisroot** [comment]
> 
> 
> Okay. So the main update hadn't been finished at all. Please have a look at your friendica log file with entries with "DB Error" in it.

The last lines are from just before I removed the parsed_url table it looks like:

> 2021-07-19T16:13:16Z console [ERROR]: DB Error {"code":1051,"error":"Unknown table 'foxes_friendica.parsed_url'","callstack":"DBA::e, pre_update_1403, Update::runUpdateFunction, Update::run, DatabaseStructure::doExecute, Console::execute, Console::doExecute, Console::execute","params":"DROP TABLE `parsed_url`"} - {"file":"Database.php","line":765,"function":"e","uid":"f1cddd","process_id":28359}
2021-07-19T16:13:16Z console [ERROR]: Update function ERROR. {"function":"pre_update_1403","retval":1} - {"file":"Update.php","line":264,"function":"runUpdateFunction","uid":"f1cddd","process_id":28359}
2021-07-19T16:13:16Z console [WARNING]: Pre update failed {"version":1403} - {"file":"Update.php","line":156,"function":"run","uid":"f1cddd","process_id":28359}

Rerunning the update or performing any other functions doesn't seem to cause any more entries in the log at the moment.

**Comment by annando** [comment]
Do you see any fresh "DB Error" entries when you execute the update command again?

**Comment by Xipherisroot** [comment]
> 
> 
> Do you see any fresh "DB Error" entries when you execute the update command again?

You are correct, I have no idea why though? I see the parsed_url table is back and the same error is back? Keeping in mind, I dropped it, re-ran the update command and had no output before, it seems like it recreated the table after receiving new network posts from external sources?

> 2021-07-19T16:42:20Z console [ERROR]: DB Error {"code":1054,"error":"Unknown column 'item-content.raw-body' in 'field list'","callstack":"DBA::e, update_1396, Update::runUpdateFunction, Update::run, DatabaseStructure::doExecute, Console::execute, Console::doExecute, Console::execute","params":"INSERT IGNORE INTO `post-content`(`uri-id`, `title`, `content-warning`, `body`, `raw-body`,\n\t\t`location`, `coord`, `language`, `app`, `rendered-hash`, `rendered-html`,\n\t\t`object-type`, `object`, `target-type`, `target`, `resource-id`, `plink`)\n\t\tSELECT `item-content`.`uri-id`, `item-content`.`title`, `item-content`.`content-warning`,\n\t\t\t`item-content`.`body`, `item-content`.`raw-body`, `item-content`.`location`, `item-content`.`coord`,\n\t\t\t`item-content`.`language`, `item-content`.`app`, `item-content`.`rendered-hash`,\n\t\t\t`item-content`.`rendered-html`, `item-content`.`object-type`, `item-content`.`object`,\n\t\t\t`item-content`.`target-type`, `item-content`.`target`, `item`.`resource-id`, `item-content`.`plink`\n\t\t\tFROM `item-content` INNER JOIN `item` ON `item`.`uri-id` = `item-content`.`uri-id`"} - {"file":"Database.php","line":765,"function":"e","uid":"f843ad","process_id":965}
2021-07-19T16:42:20Z console [ERROR]: Update function ERROR. {"function":"update_1396","retval":1} - {"file":"Update.php","line":264,"function":"runUpdateFunction","uid":"f843ad","process_id":965}
2021-07-19T16:42:20Z console [WARNING]: Post update failed {"version":1396} - {"file":"Update.php","line":194,"function":"run","uid":"f843ad","process_id":965}

> php bin/console.php dbstructure update
> CREATE TABLE IF NOT EXISTS `parsed_url` (
>         `url_hash` binary(64) NOT NULL COMMENT 'page url hash',
>         `guessing` boolean NOT NULL DEFAULT '0' COMMENT 'is the \'guessing\' mode active?',
>         `oembed` boolean NOT NULL DEFAULT '0' COMMENT 'is the data the result of oembed?',
>         `url` text NOT NULL COMMENT 'page url',
>         `content` mediumtext COMMENT 'page data',
>         `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of creation',
>         `expires` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of expiration',
>          PRIMARY KEY(`url_hash`,`guessing`,`oembed`),
>          INDEX `created` (`created`),
>          INDEX `expires` (`expires`)
> ) DEFAULT COLLATE utf8mb4_general_ci COMMENT='cache for \'parse_url\' queries';
>

**Comment by annando** [comment]
Which db error are you receiving now?

You can edit the file `update.php` this way:
```
function pre_update_1403()
{
	// Necessary before a primary key change
	if (DBStructure::existsTable('parsed_url') && !DBA::e("DROP TABLE `parsed_url`")) {
		return Update::FAILED;
	}

	return Update::SUCCESS;
}
```

**Comment by annando** [comment]
Please edit the `update.php` this way as well:

```
function update_1396()
{
	if (!DBStructure::existsTable('item-content')) {
		return Update::SUCCESS;
	}

	if (!DBA::e("INSERT IGNORE INTO `post-content`(`uri-id`, `title`, `content-warning`, `body`,
		`location`, `coord`, `language`, `app`, `rendered-hash`, `rendered-html`,
		`object-type`, `object`, `target-type`, `target`, `resource-id`, `plink`)
		SELECT `item-content`.`uri-id`, `item-content`.`title`, `item-content`.`content-warning`,
			`item-content`.`body`, `item-content`.`location`, `item-content`.`coord`,
			`item-content`.`language`, `item-content`.`app`, `item-content`.`rendered-hash`,
			`item-content`.`rendered-html`, `item-content`.`object-type`, `item-content`.`object`,
			`item-content`.`target-type`, `item-content`.`target`, `item`.`resource-id`, `item-content`.`plink`
			FROM `item-content` INNER JOIN `item` ON `item`.`uri-id` = `item-content`.`uri-id`")) {
		return Update::FAILED;
	}
	return Update::SUCCESS;
}
```

**Comment by Xipherisroot** [comment]
> 
> 
> Which db error are you receiving now?
> 
> You can edit the file `update.php` this way:
> 
> ```
> function pre_update_1403()
> {
> 	// Necessary before a primary key change
> 	if (DBStructure::existsTable('parsed_url') && !DBA::e("DROP TABLE `parsed_url`")) {
> 		return Update::FAILED;
> 	}
> 
> 	return Update::SUCCESS;
> }
> ```

Sorry, I edited the post above to add the errors, forgot to add them in before commenting.

I've changed that section of the update.php file and rerun the "php bin/console.php dbstructure update" command and still receive the following output:

> php bin/console.php dbstructure update
> CREATE TABLE IF NOT EXISTS `parsed_url` (
>         `url_hash` binary(64) NOT NULL COMMENT 'page url hash',
>         `guessing` boolean NOT NULL DEFAULT '0' COMMENT 'is the \'guessing\' mode active?',
>         `oembed` boolean NOT NULL DEFAULT '0' COMMENT 'is the data the result of oembed?',
>         `url` text NOT NULL COMMENT 'page url',
>         `content` mediumtext COMMENT 'page data',
>         `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of creation',
>         `expires` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of expiration',
>          PRIMARY KEY(`url_hash`,`guessing`,`oembed`),
>          INDEX `created` (`created`),
>          INDEX `expires` (`expires`)
> ) DEFAULT COLLATE utf8mb4_general_ci COMMENT='cache for \'parse_url\' queries';

and the log shows:

> 2021-07-19T16:46:59Z console [ERROR]: DB Error {"code":1054,"error":"Unknown column 'item-content.raw-body' in 'field list'","callstack":"DBA::e, update_1396, Update::runUpdateFunction, Update::run, DatabaseStructure::doExecute, Console::execute, Console::doExecute, Console::execute","params":"INSERT IGNORE INTO `post-content`(`uri-id`, `title`, `content-warning`, `body`, `raw-body`,\n\t\t`location`, `coord`, `language`, `app`, `rendered-hash`, `rendered-html`,\n\t\t`object-type`, `object`, `target-type`, `target`, `resource-id`, `plink`)\n\t\tSELECT `item-content`.`uri-id`, `item-content`.`title`, `item-content`.`content-warning`,\n\t\t\t`item-content`.`body`, `item-content`.`raw-body`, `item-content`.`location`, `item-content`.`coord`,\n\t\t\t`item-content`.`language`, `item-content`.`app`, `item-content`.`rendered-hash`,\n\t\t\t`item-content`.`rendered-html`, `item-content`.`object-type`, `item-content`.`object`,\n\t\t\t`item-content`.`target-type`, `item-content`.`target`, `item`.`resource-id`, `item-content`.`plink`\n\t\t\tFROM `item-content` INNER JOIN `item` ON `item`.`uri-id` = `item-content`.`uri-id`"} - {"file":"Database.php","line":765,"function":"e","uid":"2385f8","process_id":1729}
2021-07-19T16:46:59Z console [ERROR]: Update function ERROR. {"function":"update_1396","retval":1} - {"file":"Update.php","line":264,"function":"runUpdateFunction","uid":"2385f8","process_id":1729}
2021-07-19T16:46:59Z console [WARNING]: Post update failed {"version":1396} - {"file":"Update.php","line":194,"function":"run","uid":"2385f8","process_id":1729}

**Comment by annando** [comment]
Please apply the changes from https://github.com/friendica/friendica/issues/10519#issuecomment-882699940 as well.

**Comment by Xipherisroot** [comment]
> function update_1396()
> {
> 	if (!DBStructure::existsTable('item-content')) {
> 		return Update::SUCCESS;
> 	}
> 
> 	if (!DBA::e("INSERT IGNORE INTO `post-content`(`uri-id`, `title`, `content-warning`, `body`,
> 		`location`, `coord`, `language`, `app`, `rendered-hash`, `rendered-html`,
> 		`object-type`, `object`, `target-type`, `target`, `resource-id`, `plink`)
> 		SELECT `item-content`.`uri-id`, `item-content`.`title`, `item-content`.`content-warning`,
> 			`item-content`.`body`, `item-content`.`location`, `item-content`.`coord`,
> 			`item-content`.`language`, `item-content`.`app`, `item-content`.`rendered-hash`,
> 			`item-content`.`rendered-html`, `item-content`.`object-type`, `item-content`.`object`,
> 			`item-content`.`target-type`, `item-content`.`target`, `item`.`resource-id`, `item-content`.`plink`
> 			FROM `item-content` INNER JOIN `item` ON `item`.`uri-id` = `item-content`.`uri-id`")) {
> 		return Update::FAILED;
> 	}
> 	return Update::SUCCESS;
> }

This one seems to have done the trick!

I got:

> 
>  php bin/console.php dbstructure update
> CREATE TABLE IF NOT EXISTS `parsed_url` (
>         `url_hash` binary(64) NOT NULL COMMENT 'page url hash',
>         `guessing` boolean NOT NULL DEFAULT '0' COMMENT 'is the \'guessing\' mode active?',
>         `oembed` boolean NOT NULL DEFAULT '0' COMMENT 'is the data the result of oembed?',
>         `url` text NOT NULL COMMENT 'page url',
>         `content` mediumtext COMMENT 'page data',
>         `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of creation',
>         `expires` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime of expiration',
>          PRIMARY KEY(`url_hash`,`guessing`,`oembed`),
>          INDEX `created` (`created`),
>          INDEX `expires` (`expires`)
> ) DEFAULT COLLATE utf8mb4_general_ci COMMENT='cache for \'parse_url\' queries';

The first time it ran, but it paused at the end for a bit and seemed to actually be hitting the sql server to do something, ran it again and got a clean exit with no output, now everything seems to be back and in working condition!

**Comment by annando** [comment]
What does `/friendica` tells you?

**Comment by Xipherisroot** [comment]
> 
> 
> What does `/friendica` tells you?

I get:

> This is Friendica, version 2021.07 that is running at the web location https://redacted. The database version is 1424/1424, the post update version is 1400/1383.

**Comment by annando** [comment]
Great!

**Comment by Xipherisroot** [comment]
Thank you very much! I'll go ahead and close this out with this comment and hopefully this'll help anyone else who runs into the same issue or help resolve the root cause if there was one within the application its self.

Thanks!
