### ISSUE TITLE
imported retweet has misaligned author name

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10517]
![imported retweet](https://user-images.githubusercontent.com/5708172/126082502-195b5fb5-4129-44a7-ab12-9a37a2c547de.png)

Would expect author name is shown next to profile image on the left.

This is Friendica, version 2021.09-dev that is running at the web location https://squeet.me. The database version is 1429/1429, the post update version is 1427/1427.

**Comment by MrPetovan** [comment]
Have you cleared your cache? It doesn't automatically on develop like we make sure on stable releases.

**Comment by foss-** [comment]
Persisting after emptying cache.

**Comment by MrPetovan** [comment]
Hmmm, thank you for the additional information, what browser/platform are you using?

**Comment by foss-** [comment]
macOS 11.4, Firefox 90.0.1, but also reproducible in Brave 1.26.77 or Safari 14.1.1.

**Comment by MrPetovan** [comment]
Got it, thanks, I really should update my main node.

**Comment by annando** [comment]
I now fixed it by manually clearing the smarty cache.

**Comment by MrPetovan** [comment]
Whoa, this is rarely warranted.

**Comment by annando** [comment]
Yeah. I really was confused when seeing that the generated HTML contained structures that couldn't be generated by any existing template or code. Then I detected this structure in the smarty cache.

**Comment by foss-** [comment]
Seems to be fixed for new retweets. Thanks & closing.
