### ISSUE TITLE
Open all images inside a popup

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10539]
Take this post https://social.trom.tf/display/ba285ea5-d6474b97014e8c5f-f33d51b4 if you click any of those images they do not use the popup image viewer. Would be nice if they did so.

Also, I'd say the image viewer (popup) needs some improv :).

**Comment by schmaker** [comment]
Isn't this fixed with fancybox addon?

**Comment by tio-trom** [comment]
Yup closing.
