### ISSUE TITLE
iOS Metatext throwing Error (NSURLErrorDomain-Error-1000.) when refreshing timeline

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10547]
### Bug Description

When refreshing timeline on iOS 14.7, Metatext 1.5.0 frequently seeing Error (NSURLErrorDomain-Error-1000.).

New messages from not so long ago (~1-2 hours or so) are loaded. Then there is a "Load Mode" option for remaining messages that are between the recent (just loaded) messages and the last message shown (from when last refreshing timeline. Using this `Load More` option then results in the error message and posts are not loaded.

### Platform Info

Friendica Version: reproducible both on squeet me and pirati ca

**Comment by gitkald** [comment]
Same by me.

**Comment by MrPetovan** [comment]
Thank you for the report, I still haven't taken the time to look into it, being the only Friendica Core team member with an iPhone.

**Comment by annando** [comment]
Yeah, I only have got an older iPhone at hand that supports up to iOS version 12. This is one of our old company phones.

**Comment by MrPetovan** [comment]
The offending access log line seems to be:
```
dev-friendica.mrpetovan.com:443 71.105.40.175 - - [19/Sep/2021:19:30:53 +0200] "GET /api/v1/timelines/home?max_id=44093 HTTP/1.1" 200 51092 "-" "Metatext/4 CFNetwork/1240.0.4 Darwin/20.6.0"
```
However, the `NSURLErrorDomain-Error = -1000` is meant to be for a "Bad URL", so I'm not sure what the issue is since the call itself return 200.

I may have to actually perform this call in isolation to see what is returned.

**Comment by MrPetovan** [comment]
More information on the error code `-1000`: https://developer.apple.com/documentation/foundation/nsurlerrorbadurl

So it doesn't seem like we can do something about it? I may have to ask on the Metatext repository.

**Comment by annando** [comment]
I could imagine that it is some problem with providing an empty value where Metatext expects some value. We had something similar with the API in the past. There we provided some `null` value in an API field. This was unexpected by some of the clients. Rechecking with Mastodon it then appeared as if Mastodon removes fields from the answer when being empty. So I did the same. I tracked down this error by searching for the API call that was the cause of the client error. Then I had a look at the data we had transmitted. And then I reduced the answer field by field until the error vanished.

**Comment by MrPetovan** [comment]
But the client would issue the request, right? So you knew exactly what API call was the cause of the error. In this present case it's likely that the API call URL is invalid because an earlier API call didn't return the expected data, but this means it could be anything as clients are a dozen of various API calls just on app opening.

**Comment by annando** [comment]
I started with the last command that the client had sent.

**Comment by foss-** [comment]
Likely expected - just a heads-up, persisting with:
Metatext 1.6.0 (1)
Friendica  2022.12-dev

**Comment by foss-** [comment]
Closing, Metatext is EOL, sadly Maintainer is pausing development due to personal reasons. They did great work, but it's not worth keeping this issue open for an unmaintained client.

https://github.com/metabolist/metatext ` This repository has been archived by the owner on Nov 30, 2022. It is now read-only. `
