### ISSUE TITLE
See more posts

### ISSUE THREAD

**Issue by poltrian** [friendica/friendica#10542]
How can i see more post?

I can only see the posts of a certain time at a time. After not even the whole day:
https://squeet.me/community?max_id=2021-07-23%2018:25:15
How can I switch off the Max ID?

**Comment by MrPetovan** [comment]
"Switching off" the max ID won't show more posts if there aren't any more to show. I assume you don't have infinite scroll enabled for you to be able to see this parameter, what happens when you change page?
