### ISSUE TITLE
Tag [zmg] of ZAP

### ISSUE THREAD

**Issue by prolibre** [friendica/friendica#10545]
When a friend on zap posts an image I don't see it but I see the tag (for example):

`[zmg width="1024" height="682" alt="TXT ALT"]https://venera.social/photo/preview/XXX/XXXXX[/zmg]`

I think the tag is not interpreted.

**Version**
This is Friendica, version 2021.07 that is running at the web location https://venera.social. The database version is 1424/1424, the post update version is 1400/1400.

**Comment by MrPetovan** [comment]
What is the difference with the `[img]` tag?

**Comment by annando** [comment]
From what I see is the difference that it contains attributes like `width`, `height` and `alt`.

**Comment by tobiasd** [comment]
I think `zmg` also includes some remote auth/verification to access the image.
