### ISSUE TITLE
Avatars of RSS feeds are not shown

### ISSUE THREAD

**Issue by RealVegOs** [friendica/friendica#10556]
Avatars of RSS feeds are not shown in my timeline. I see the dafault avatar instread. In contacts the avatars of RSS feeds show up. I think this is since last update of friendica.feneas.org

![ehn-timeline_300](https://user-images.githubusercontent.com/7726676/127306403-33ceec40-617f-45dd-8b6e-27bc58112a58.png) ![ehn-contact_300](https://user-images.githubusercontent.com/7726676/127306397-9b09bc39-e44e-494f-bb64-21fa581ac983.png)

**Comment by annando** [comment]
This is fixed in the current develop branch.

**Comment by RealVegOs** [comment]
THX!
