### ISSUE TITLE
RSS does not pick up "media enclosure" when sharing a post with an image

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10559]
Before I upgraded to the latest Friendica, the RSS feed will pick up the first image as a media enclosure, but now it is a hit or miss. Mostly a miss. I'll give you one example. This is the post I made in Friendica:

```
TROMmaps officially added to https://trom.tf/ as a fully functioning service. See it here in action https://maps.trom.tf/ and here you can learn more about it https://trom.tf/maps/ . It is an amazingly great trade-free map.

[url=https://social.trom.tf/photos/trom/image/1409930277610234c1d2bf7107067180][img=https://social.trom.tf/photo/1409930277610234c1d2bf7107067180-1.png][/img][/url]

#tromimg
```

This is the post https://social.trom.tf/display/dbc8dc44-9861-0234-cc54-ea0509009838

This is the RSS output:

```
<entry>
    <id>https://social.trom.tf/objects/dbc8dc44-9861-0234-cc54-ea0509009838</id>
    <title>TROMmaps officially added to https://trom.tf/ as a fully functioning service. See it here in action ...</title>
    <content type="html">TROMmaps officially added to &lt;a href="https://trom.tf/" target="_blank" rel="noopener noreferrer"&gt;trom.tf/&lt;/a&gt; as a fully functioning service. See it here in action &lt;a href="https://maps.trom.tf/" target="_blank" rel="noopener noreferrer"&gt;maps.trom.tf/&lt;/a&gt; and here you can learn more about it &lt;a href="https://trom.tf/maps/" target="_blank" rel="noopener noreferrer"&gt;trom.tf/maps/&lt;/a&gt; . It is an amazingly great trade-free map.&lt;br&gt;&lt;br&gt;&lt;img src="https://social.trom.tf/photo/1409930277610234c1d2bf7107067180-1.png" alt="" title=""&gt;&lt;a href="https://social.trom.tf/photos/trom/image/1409930277610234c1d2bf7107067180"&gt;https://social.trom.tf/photos/trom/image/1409930277610234c1d2bf7107067180&lt;/a&gt;&lt;br&gt;&lt;br&gt;#&lt;a href="https://social.trom.tf/search?tag=tromimg" class="tag" title="tromimg"&gt;tromimg&lt;/a&gt;</content>
    <link rel="alternate" type="text/html" href="https://social.trom.tf/display/dbc8dc44-9861-0234-cc54-ea0509009838"/>
    <published>2021-07-29T04:55:40Z</published>
    <updated>2021-07-29T04:55:40Z</updated>
    <category term="tromimg"/>
  </entry>
```

There us no "enclosure".

**Comment by MrPetovan** [comment]
Are you talking about the link preview at the bottom of the posts? Not sure we can replicate their display within the limits of RSS since it requires custom CSS that might be blocked by readers.

**Comment by tio-trom** [comment]
No. I am using my RSS url from friendica https://social.trom.tf/feed/trom/posts to grab posts in my RSS reader or on our website via an RSS Reader plugin. And any RSS reader looks for a media enclosure to try and pull it as a thumbnail or whatever it is designed to do with it. The thing is, the new Friendica RSS seems to be unable to create a media enclosure out of some posts that clearly have an image attached to the post, like the above example.

Hope I explained it well if not I'll give it another try :D  .

**Comment by MrPetovan** [comment]
Yes you did, thank you very much! Do you know if this kind of enclosure should be specified in the RSS feed structure itself or if the body has to be a certain way? Do you have a working example of an RSS feed with correct media enclosures?

**Comment by annando** [comment]
@MrPetovan we only have to copy some code from the OStatus part to the feed part, I guess.

**Comment by tio-trom** [comment]
> Do you know if this kind of enclosure should be specified in the RSS feed structure itself or if the body has to be a certain way?

I guess should be `  <link rel="enclosure" href="URL OF THE IMAGE" type="image/TYPE" length="15827"/> `  something like that.

**Comment by annando** [comment]
I just had a look. We do add this data in the code.

**Comment by tio-trom** [comment]
> I just had a look. We do add this data in the code.

Yes but it doesn't work for many posts, like the above one I shared. It used to work perfectly fine, and now works 2 out of 5 times maybe. I do not think I am doing anything different to the posts I create. I simply add and image from the browser into the post. Would it make any different if you use the popup composer vs the standalone one?

**Comment by tio-trom** [comment]
Here's the latest post I just made https://social.trom.tf/display/dbc8dc44-2761-0406-8ba9-dc1680617147 - I simply attached an image to it, or inserted it however you call that. The post looks like:

```
We will go live in less than 7 hours. 

TROMcast: To Moderate, Or Not

Today we will discuss about this notion of moderating the Internet content by looking closely at our videos.trom.tf (Peertube) instance and what happens to it. The fact that it is full of nonsense content and why is it that these alternative platforms such as Peertube, get invaded by the worst that the Internet and our society has produced.


Here https://videos.trom.tf/w/239682f2-fd1f-43ab-81ef-7c92a3f01336

#tromimg 

[url=https://social.trom.tf/photos/trom/image/979015473161040682061a2631711567][img=https://social.trom.tf/photo/979015473161040682061a2631711567-1.jpg][/img][/url]
```

This is the RSS link https://social.trom.tf/feed/trom/posts. And the post has no media enclosure:

```
  <entry>
    <id>https://social.trom.tf/objects/dbc8dc44-2761-0406-8ba9-dc1680617147</id>
    <title>We will go live in less than 7 hours.</title>
    <content type="html">We will go live in less than 7 hours. &lt;br&gt;&lt;br&gt;TROMcast: To Moderate, Or Not&lt;br&gt;&lt;br&gt;Today we will discuss about this notion of moderating the Internet content by looking closely at our videos.trom.tf (Peertube) instance and what happens to it. The fact that it is full of nonsense content and why is it that these alternative platforms such as Peertube, get invaded by the worst that the Internet and our society has produced.&lt;br&gt;&lt;br&gt;&lt;br&gt;Here &lt;a href="https://videos.trom.tf/w/239682f2-fd1f-43ab-81ef-7c92a3f01336" target="_blank" rel="noopener noreferrer"&gt;videos.trom.tf/w/239682f2-fd1f…&lt;/a&gt;&lt;br&gt;&lt;br&gt;#&lt;a href="https://social.trom.tf/search?tag=tromimg" class="tag" title="tromimg"&gt;tromimg&lt;/a&gt; &lt;br&gt;&lt;br&gt;&lt;img src="https://social.trom.tf/photo/979015473161040682061a2631711567-1.jpg" alt="" title=""&gt;&lt;a href="https://social.trom.tf/photos/trom/image/979015473161040682061a2631711567"&gt;https://social.trom.tf/photos/trom/image/979015473161040682061a2631711567&lt;/a&gt;</content>
    <link rel="alternate" type="text/html" href="https://social.trom.tf/display/dbc8dc44-2761-0406-8ba9-dc1680617147"/>
    <published>2021-07-30T14:02:51Z</published>
    <updated>2021-07-30T14:02:51Z</updated>
    <category term="tromimg"/>
  </entry>
```

I wonder why...

**Comment by tio-trom** [comment]
I noticed that if you add more than 1 image then it works. So for one image the RSS won't display a "media enclosure" but with more than 1 image it will. It worked before with Friendica. If you guys can look into it. Thanks!

**Comment by tio-trom** [comment]
This seems to work now.
