### ISSUE TITLE
deleting scheduled posts not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10568]
Trying to delete a scheduled posting from the in #10565 introduced front-end results in a WSOD and the following error trace.

```
#0 [internal function]: Friendica\Module\Profile\Schedule::post()
#1 /src/App/Module.php(320): call_user_func()
#2 /src/App.php(657): Friendica\App\Module->run()
#3 /index.php(42): Friendica\App->runFrontend()
#4 {main}
```

This occurs using the `vier` theme. With `frio` it works. I've not tested other themes.

**Comment by MrPetovan** [comment]
What is the actual error? It should be shown above the trace.

**Comment by tobiasd** [comment]
I think it was this one

> The server cannot or will not process the request due to an apparent client error.
