### ISSUE TITLE
RSS feed polling is too aggressive

### ISSUE THREAD

**Issue by pvagner** [friendica/friendica#10561]
Hello,
I have added RSS feed of a site I have under my control. I have configured it to update its public posts frequently. Under contact settings I have fetch further information for feeds set to disabled.
Approximately each 10 minutes friendica is parsind the RSS feed also loading each URL to the articles within that feed.
So if my RSS feed returns 10 recent articles my instance of friendica is visiting URLs of all these articles each 10 minutes.
I like to check my RSS feed for new content frequently but loading the full article each time checking the feed seems as an overkill to me. 9 of 10 articles are already parsed and they are polled for the content nevertheless.
Is there a way so I can tweak this somehow to only load the content of respective URLs only when the article is unknown to friendica i.e. during creation of corresponding friendica post?

**Comment by hoergen** [comment]
There should be a setting where you can define the time range. 

Like every hour, every 2 hours, every 4 hours, every 6 hours, every 12 hours, once a day.

This would take a lot load away from an instance.

**Comment by MrPetovan** [comment]
Have you tried to change the poll frequency in the contact settings to less than "frequently"?

**Comment by annando** [comment]
Besides the configuration per contact, you can also enable `adjust_poll_frequency` in the `system` setting in the `local.config.php` to make the system automatically determine the best poll rate.

**Comment by hoergen** [comment]
Seems there are all solution in here and the issue creator seems not to disagree .. so should we close it?

**Comment by annando** [comment]
I think that we can do so. Additionally the "adjust poll frequency" can now be set directly via the admin backend.
