### ISSUE TITLE
problems on tag page

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#10560]
- [x] I have searched open and closed issues for duplicates

### Bug Description

On the search / tag page, there seem to be some problems like misplaced buttons ..

### Steps to Reproduce

visit for example `/search?tag=pinephone` on a friendica node. 
I saw it here : https://libranet.de/search?tag=pinephone
 
Actual Result:
there is a search box with misplaced buttons on top of the page and when I check a post and try to delete it, the delete button is huge with too big font and doesn't work.

Expected Result:

not sure.. like it was before maybe.

### Screenshots

![friendica-tag](https://user-images.githubusercontent.com/5753419/127690429-1b751c58-383e-4632-9a79-2805af8b7ba9.jpg)

### Platform Info
Friendica-Version: 2021.09-dev
https://libranet.de
Datenbankversion: 1430/1430
Post-Update-Version: 1427/1427.

**Comment by MrPetovan** [comment]
I'm sorry about the issue but it also is a hilarious display bug.

**Comment by haheute** [comment]
The checkboxes and the delete button have been removed. I think this issue is not longer relevant.
