### ISSUE TITLE
PHP Fatal error accessing profile pages with a lot of posts

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1056]
I see a lot of error messages when the profile page of a account that is posting a lot:

[Wed Jul 23 15:16:28 2014] [error] [client 0.0.0.0] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 89 bytes) in /var/www/virtual/snarl.de/htdocs/library/dddbl2/handler/register_result_handler.inc.php on line 39, referer: https://snarl.de/profile/protestation_

The error seems not to happen every time as I was able to access the profile page without error.

**Comment by Beanow** [comment]
Is this still an issue?

**Comment by MrPetovan** [comment]
Yesterday I had to set my PHP maximum memory limit to 384MB for Friendica, 128MB is way too low to expect smooh sailing. We probably can optimize memory usage but it isn't on the slate right now.

**Comment by tobiasd** [comment]
On my node 128M is enough

**Comment by MrPetovan** [comment]
Enough for what? I'm surprised this kind of error never appeared for you, or that you never saw it. Although Friendica is a resilient program that's able to keep on working even when some part are crashing, a well-groomed PHP eror log should have a couple of those, especially for people on the develop branch.

What I mean is, great! But would you be able to reliably know if it wasn't exactly enough? I didn't experience any visible difference in my Friendica usage when the memory consumption last went over 256MB and I still don't know why it reach that peak, and yet it did which made me write my comment above.

I can only think of a single reason for a memory consumption difference between Linux machines and it would be that I'm using the Apache2 PHP SAPI, although I would be surprised if it was the case.

**Comment by AlfredSK** [comment]
I also have these PHP memory errors lately. My setting for max memory is 128MB. I raised the value to 160MB but PHP still tried to allocate more. So I decided to ignore it. I don't get the error very often. Maybe 3 or 4 times a day.
(PHP 7.0 as Apache mod_php)

**Comment by MrPetovan** [comment]
Oh, PHP version could make a difference between servers, maybe PHP 7 is faster at a higher memory cost.

**Comment by AlfredSK** [comment]
Also, to add a little more confusion, I only have the error on libranet.de but not on forum.friendi.ca. Both nodes are running on the same machine.

**Comment by tobiasd** [comment]
> Enough for what? 

For running my Friendica node on lighttp and PHP7.0 fastcgi, without seeing that error in the logs.

**Comment by annando** [comment]
It would be good to isolate this error to some action in Friendica. Like I said above: I guess that there is some query that uses really much memory.

**Comment by MrPetovan** [comment]
@tobiasd Ok, good to know. Thanks for the details.
