### ISSUE TITLE
Forum contact is shown above forum's network stream

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10577]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I select a forum in the forum widget a "card" of the forum contact is displayed above the forum posts.

### Steps to Reproduce

1.  click on a forum in the forum widget
2.  look at the top area of the forum's network stream

Actual Result:

A weird contact "card" is displayed above the stream.

Expected Result:

It shouldn't be there.

### Screenshots

![1620440819610979bb08583002216194-0](https://user-images.githubusercontent.com/3656054/128387840-2af63bf0-403f-4a11-9afb-5cf84d48da6a.png)

### Platform Info

Friendica Version:
2021.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
Please stop adding bugs to the software. Before your report it was perfectly good. 😅

**Comment by AlfredSK** [comment]
Haha! 😁

**Comment by annando** [comment]
Yeah, as long as you don't report them, we don't have bugs!

Today I'm too tired. I had a much too short night and will most likely continue with stuff tomorrow.

**Comment by MrPetovan** [comment]
Please rest, it can wait.

**Comment by AlfredSK** [comment]
Seems to be fixed by... no idea. But it doesn't happen anymore. Closing.
