### ISSUE TITLE
Themes : Frio : custom link color not applied on /photos and /cal in incognito mode

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#10583]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When in browser incognito mode, custom link colors seem not to be applied on `/photos/..` and `/cal/..` pages.

### Steps to Reproduce

Change the link color in `/settings/display` in frio theme and then visit your photos and calendar in incognito mode or logged out.

`/photos/{ username }`
`/cal/{ username }`

Actual Result:

orange links under `photos`and `cal`

Expected Result:

blue link color everywhere -  same as on my `profile` and `status` pages.

### Screenshots

![friendica-frio-orange](https://user-images.githubusercontent.com/5753419/128614038-f02546e4-8fcb-485b-bca9-fc8dcd83e98c.jpg)
![friendica-frio-blue](https://user-images.githubusercontent.com/5753419/128614059-5e7e3250-2a28-4ecb-85be-f83d129932ff.jpg)

### Platform Info

Friendica Version: 2021.09-dev
https://libranet.de
database version: 1431/1431
post update version: 1427/1427

**Comment by haheute** [comment]
I have looked at the developer tools in firefox (network analysis / css) and I suspect that maybe under `/photos` and `/cal` the `puid` could be missing (in incognito window).

`/profile`:

        https://libranet.de/view/theme/frio/style.pcss?puid=3963&v=2021.12-rc

`/photos`:

        https://libranet.de/view/theme/frio/style.pcss?v=2021.12-rc

`/cal`:

        https://libranet.de/view/theme/frio/style.pcss?v=2021.12-rc

It seems, as if with this `puid`, a different css file (with different colors) is delivered..

**Comment by MrPetovan** [comment]
Yes, this is meant to show you the theme the user which you are viewed the profile for selected for themselves. `puid` stand for `profile user id`.

**Comment by haheute** [comment]
This seems to work now.. :+1:
