### ISSUE TITLE
Save Posts from the global timeline 

### ISSUE THREAD

**Issue by poltrian** [friendica/friendica#10587]
At the moment it is only possible to save posts in the local timeline. I use this, for example, to look at posts or videos later.
I would also like to do that in the Golbalen Timeline, also to view important posts or videos later.

I understand that the posts may have been deleted later. But this is also the case in other systems.

**Comment by MrPetovan** [comment]
Can you save the post when viewed individually by clicking on the date and time it was published in the global timeline?

**Comment by annando** [comment]
The problem behind is that by now we can only save posts when we have got an entry in the `post-user` table for that post and the current user. This is mostly not given when being at the global timeline.

**Comment by annando** [comment]
This is fixed by PR https://github.com/friendica/friendica/pull/10596
