### ISSUE TITLE
Wrong whitespace in Pleroma post

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10595]
Original post: ~~https://pl.thj.no/notice/AADsc2u5zHltKe3HRA~~ (unavailable)
Received post: ~~https://friendica.mrpetovan.com/display/ecb67e8c-e00a18e74a043d57-35ba9b91~~ (unavailable)

It looks like a conversion from Markdown but the addon is disabled on my node.

**Comment by annando** [comment]
The content looks like this:
```
<p>Norwegian words that might confuse or amuse the anglophone</p><p>borger = citizen
and = duck
spare = save, savings
tom = empty
hell = luck, slope
mat = food
rape = burp
dog = though
pave = pope
fart = speed
pine = torment, torture</p>
```
We are parsing this as regular HTML, which is correct, I think. We shouldn't start parsing linefeeds in HTML content.

**Comment by MrPetovan** [comment]
Ah dammit, I guess we have to report a bug in Pleroma then.

Edit: I can't submit an issue on [their repository](https://git.pleroma.social/pleroma/pleroma/-/issues) without signing up, but there's no sign up link available. I've joined the `#pleroma-dev` channel on libera.chat to ask how to report the issue.

**Comment by lanodan** [comment]
Issue is into the markdown renderer we're using, I sent <https://github.com/pragdave/earmark/issues/406>.

**Comment by MrPetovan** [comment]
Thank you for looking into it!

**Comment by hjri** [comment]
can't you just render it in frontend with `white-space: pre` i think pleromafe does it that way

**Comment by MrPetovan** [comment]
This would have an impact on posts not only from Pleroma, but from Friendica, Mastodon, Diaspora, GNU Social, etc... we simply can't make an exception for Pleroma posts.

The other alternative is for Pleroma to transmit Markdown text, which we would correctly transform to the expected display. The issue seems to stem from the HTML transformation Pleroma performs before transmitting the message to remote servers.

**Comment by hjri** [comment]
Benefits of using `white-space: pre`:

* posts with newlines render correctly
* posts without newlines render correcty
* post with meaningful spacing (ascii art) render correctly

PleromaFE has been doing this for years now and it work well with mastodon, pleroma, friendica and others, haven't had a single issue with it.

**Comment by MrPetovan** [comment]
I'm not saying it doesn't work well, I'm saying it's a very impactful change to our current workflow. Like @lanodan remarked on the `#pleroma-dev` IRC channel, Friendica adds `<br/>` tags for new lines, which then are rendered correctly according to the HTML spec without the need for `white-space: pre`.

~~Enabling it would require us to change the way we add `<br/>` tags by either not adding them against the HTML spec, or removing the new line character which would turns the HTML string into a one-liner harder to debug.~~ (see https://github.com/friendica/friendica/issues/10595#issuecomment-898437261)

We are currently missing on ASCII art which is a good reason to enable `white-space: pre`, but it has significant consequences that makes it non-trivial a change.

**Comment by hjri** [comment]
no it doesn't have any consequences nor require you to change anything, `<br>` is rendered properly when using `white-space: pre` as well.

unless you somehow indent/prettify html posts for whatever reason, but i haven't seen this in wild.

**Comment by MrPetovan** [comment]
Wouldn't `\n<br/>` be rendered as two consecutive new lines with `white-space: pre`? Because it only renders with one without. This is the change I'm talking about.

**Comment by annando** [comment]
Is this `white-space: pre` something at the frontend? We are internally reformatting everything to BBCode for historical reasons. So this wouldn't do anything.

**Comment by hjri** [comment]
yes, but if you're using `<br/>`s already, why do you also need `\n`?

**Comment by hjri** [comment]
yes, `white-space: pre` is frontend thing.

**Comment by MrPetovan** [comment]
> yes, but if you're using `<br/>`s already, why do you also need `\n`?

I could ask you the same opposite question, why discard it since white space isn't meaningful in the HTML spec?

**Comment by MrPetovan** [comment]
The reason we have `\n` in the first place is that, like @annando said, our native markup language is BBCode, which doesn't have `<br/>` but has new lines. Then we convert it to HTML by adding the `<br/>` tags where new lines are.

**Comment by hjri** [comment]
>I could ask you the same opposite question, why discard it since white space isn't meaningful in the HTML spec?

because it adds one or two extra bytes that don't do anything at all

>Then we convert it to HTML by adding the <br/> tags where new lines are.

just replace the `\n` with `<br/>` then, not add?

**Comment by MrPetovan** [comment]
Nevermind, this isn't where the problem is. The problem lies in the HTML to BBCode conversion when we receive remote messages from Pleroma or any other system. We convert `<br>` into `\n` because we perform the opposite operation when converting BBCode to HTML, but we strip the existing new lines because they aren't meaningful in HTML so they shouldn't appear in the BBCode where they are meaningful.

Resolving this issue with Pleroma isn't as simple as enabling `white-space: pre` since there aren't any `\n` left in the Pleroma post body once we converted the received HTML to the local BBCode representation according to the HTML spec.

**Comment by MrPetovan** [comment]
Closing since the upstream issue in the Markdown renderer https://github.com/pragdave/earmark/issues/406 has been fixed.
