### ISSUE TITLE
Wrong links in mentions

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10617]
### Bug Description

In some postings from Mastodon (so far I've only noticed it in Mastodon postings) the mentions in postings is linkified twice.

Some examples

````
7. Cluster Stammtisch - #[url=https://chaos.social/tags/Katastrophenschutz]Katastrophenschutz[/url] #[url=https://chaos.social/tags/cellbroadcast]cellbroadcast[/url] ist keine #[url=https://chaos.social/tags/SMS]SMS[/url]
Spannende Einblicke von Manuel Atug (@HonkHase), Sprecher und Gründer der @[url=https://chaos.social/@[url=https://chaos.social/users/AG_KRITIS]AG_KRITIS[/url]]AG_KRITIS[/url]

[url=https://cyber-security-cluster.eu/de/aktuelles/siebterclusterstammtisch.html]https://cyber-security-cluster.eu/de/aktuelles/siebterclusterstammtisch.html[/url]
````

![grafik](https://user-images.githubusercontent.com/433490/130182714-a4a9e93e-6c4c-465e-8f24-c6e422103239.png)

````
@[url=https://mastodon.technology/@[url=https://mastodon.technology/users/sergey_m]sergey_m[/url]]sergey_m[/url] they do as for PRs! [class=emoji mastodon][img=https://cdn.mastodon.technology/custom_emojis/images/000/106/011/original/9f2da297dece04c8.png]:blobcoffee:[/img][/class]
````

Original URL https://chaos.social/@crossgolf_rebel/106786675176036360

![grafik](https://user-images.githubusercontent.com/433490/130183135-285aed41-3367-40fe-ae79-ec0af8084b1b.png)

Original URL https://mastodon.technology/@rysiek/106785412862348330

Tested with vier and frio.

### Expected Result:

Mentions only being linked once.

### Platform Info

Friendica Version:  2021.9-dev 4b36f7e8c8f36a9aef35067b108a85f4733f9535

Friendica Source: git

PHP version: 7.4.22

**Comment by MrPetovan** [comment]
Goddammit, Mastodon with the `@` in the URLs again.

**Comment by MrPetovan** [comment]
Caused by #10604
