### ISSUE TITLE
Can not search for AP-Handle

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10625]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If i search for @Artists4Future_Muenchen@climatejustice.global i get no search-result.
If i search for https://climatejustice.global/@Artists4Future_Muenchen i get the user.

Expected Result:

Search for @user@domain should bring as result this user.

### Platform Info

Friendica Version: 2021.09-dev

Friendica Source: 

PHP version: 7.3

SQL version: mariadb 10.3

**Comment by annando** [comment]
This seems to be related to PR https://github.com/friendica/friendica/pull/10619

I tested with an older branch prior to this PR and probing worked. Switching back to the current develop branch lead to this problem.

@nupplaphil to the rescue!

**Comment by nupplaphil** [comment]
@annando  / @MrPetovan 
I'm sorry, but I'm not able to `/probe`  @Artists4Future_Muenchen@climatejustice.global with `stable`, `develop` and e7f25f2bee5e303b6af4f1cf707b897a6d794624 (the last PRs before the PR) ... It doesn't work for me ...

But probing `Artists4Future_Muenchen@climatejustice.global` isn't a problem at any branch, it returns exact the same result ..

**Comment by annando** [comment]
Yeah, it has to be done without the leasing `@`. On my system It is reproducable that I can't perform a probe with the current develop branch, but it works with an older branch. Weird.

**Comment by MrPetovan** [comment]
So it's a bug in the probe part, not the HTTP client part. I can take a look at it.

**Comment by annando** [comment]
I'm mostly sure that the probing is performing some HTTP request that now behaves differently.

**Comment by MrPetovan** [comment]
I'm getting no result with the leading `@` on my system before I updated it with @nupplaphil 's PR, so it isn't related to the change in HTTP client.

**Comment by annando** [comment]
The leading `@` is not the issue. On my system the probing in the format `user@domain.tld` doesn't work with the latest develop branch. But it works in a branch without the HTTP changes.

**Comment by MrPetovan** [comment]
Ah, got it.

Edit: I confirm the regression after the HTTP client update, I'll still look into it now that I opened my development environment.

**Comment by MrPetovan** [comment]
And done. There was some confusion as to how to use Guzzle's body as a stream but now it is fixed.
