### ISSUE TITLE
Postupdate doesn't run automatically - display of current postupdate version seems to be wrong

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10639]
- [YES] I have searched open and closed issues for duplicates

### Bug Description

I have upgraded the Friendica Community Forum node from 2021.07 (stable) to 2021.09-rc. The database structure update 1434 was successful. But it looked like the postupdate process wasn't started by the worker. The /friendica page was showing "the database version is 1434/1434, the post update version is **1427/1423**." 

Shouldn't it be like "the database version is 1434/1434, the post update version is **1423/1427**"?

I waited some time but nothing happened. Then I started the postupdate process manually with `sudo -u www-data php bin/console.php postupdate`. 

The postupdate was processed successfully. But the numbers on /friendica seemed to be wrong. For example when 2 postupdates were done it was showing "the post update version is **1427/1425**." Again, shouldn't it be **1425/1427**?

I have the feeling that the postupdate wasn't triggered because we not only show the numbers in a wrong way but (maybe) we also check the wrong number when we decide if the postupdate needs to be started by the worker or not.

### Steps to Reproduce

1.  switch a node from current stable to current rc
2.  watch if the postupdate is started by the system
3.  look at the version numbers on /friendica page

Actual Result:

Looks like the worker doesn't start the postupdate. The postupdate version numbers are swapped.

Expected Result:

Postupdate should run w/o admin interaction. Version numbers should be displayed in the expected order.

### Platform Info

Friendica Version:
2021.07 -> 2021.09-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by annando** [comment]
Please have a look for log entries on the `info` level with `PostUpdate.php`.

**Comment by AlfredSK** [comment]
I can't. Not with that node. :-) I was on log level `notice` when I switched to RC. So nothing about the postupdate has been logged.

**Comment by annando** [comment]
Please execute `bin/console postupdate`

**Comment by AlfredSK** [comment]
I already did that.

> I waited some time but nothing happened. Then I started the postupdate process manually with sudo -u www-data php bin/console.php postupdate.

And it was successful.

**Comment by annando** [comment]
Please set the loglevel to `info` then repeat the command, then have a look for entries with `PostUpdate` in it.

**Comment by AlfredSK** [comment]
Ok. As you wish...

```
sudo -u www-data php bin/console.php postupdate   
Check for pending update actions.
Done.
Execute pending post updates.

All pending post updates are done.
```

Log (level info):

```
2021-08-29T08:03:02Z worker [INFO]: Process start. {"priority":40,"id":58228957,"worker_id":"6481665","worker_cmd":"PostUpdate"} - {"file":"Worker.php","line":436,"function":"execFunction","uid":"d0f367","process_id":1792473}
2021-08-29T08:03:02Z worker [INFO]: ID 58228957: PostUpdate {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0.01,"total":0.01} - {"file":"Worker.php","line":504,"function":"execFunction","uid":"d0f367","process_id":1792473}
2021-08-29T08:06:02Z worker [INFO]: Process start. {"priority":40,"id":58228987,"worker_id":"daa1714","worker_cmd":"PostUpdate"} - {"file":"Worker.php","line":436,"function":"execFunction","uid":"58887b","process_id":1793177}
2021-08-29T08:06:02Z worker [INFO]: ID 58228987: PostUpdate {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0,"total":0} - {"file":"Worker.php","line":504,"function":"execFunction","uid":"58887b","process_id":1793177}
2021-08-29T08:09:15Z worker [INFO]: Process start. {"priority":40,"id":58229731,"worker_id":"744ea06","worker_cmd":"PostUpdate"} - {"file":"Worker.php","line":436,"function":"execFunction","uid":"1ac2f9","process_id":1793765}
2021-08-29T08:09:15Z worker [INFO]: ID 58229731: PostUpdate {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0,"total":0} - {"file":"Worker.php","line":504,"function":"execFunction","uid":"1ac2f9","process_id":1793765}
```

Hint: The worker is started by cron every 3 minutes.

Nothing in the PHP error log.

**Comment by AlfredSK** [comment]
Same issue here https://github.com/friendica/friendica/issues/10474#issuecomment-907734128 I guess.

**Comment by annando** [comment]
That's really weird. BTW: The format in the message on the `/friendica` is intended in this way. The first way is always the expected version, the second the current one. For some weird reason your system doesn't execute the post update but returns `true` anyway ...

**Comment by AlfredSK** [comment]
I'm pretty sure it was the other way around. :-)

Just to make sure... The postupdates were applied successfully. The system is showing 1427/1427 now! As I have written in the issue I ran the postupdate manually after I had waited approx. 40 minutes.

**Comment by annando** [comment]
Okay, so that's fine and I can start the day with a breakfast.

**Comment by AlfredSK** [comment]
Yes. But still, something seems to be kaputt. I have another node on stable. So I have the opportunity to check it again. :-)

**Comment by AlfredSK** [comment]
Bug confirmed, I think... https://github.com/friendica/friendica/issues/10474#issuecomment-907734128 ff

**Comment by nupplaphil** [comment]
@annando This one looks a little bit suspicious:
https://github.com/friendica/friendica/blob/c06ba3a7c993503da37c4e5ba7a469cf4a3a8f52/update.php#L980

**Comment by annando** [comment]
With version `1429` a bug was fixed concerning the `uri-id` fields of these tables. That's why they had to be cleared. Also that's the reason why the postupdate needed to be executed again.

**Comment by AlfredSK** [comment]
So. What is the status of the issue? I want to switch my last node running the current stable version to current RC.

Should I do that now and see what happens or should I wait for some fix?

**Comment by annando** [comment]
I'm confused. Isn't your system now on the correct version?

**Comment by AlfredSK** [comment]
I have multiple systems. :-) venera.social is still on stable.

**Comment by annando** [comment]
Since multiple persons updated and no one mentioned this problem, I guess you could give it a try.

**Comment by AlfredSK** [comment]
Switched branch. DB update successful. Postupdate seems to run. But pretty slow. Only 1000 rows are processed with every worker run. Those 1000 rows take around 20 seconds to process. Then the system waits 160 seconds for the next cron interval.

**Comment by AlfredSK** [comment]
If I extrapolate the needed time for the first postupdate it will take 25 hours. The system could easily process 10000+ rows with every worker run. No wonder I thought it doesn't work at all. :-)

**Comment by AlfredSK** [comment]
Postupdate finished. After two days. :-)
So, it works but it is really slow.
