### ISSUE TITLE
Friendica showing posts as other people

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#10651]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Please see this item that showed up on my timeline this morning:

https://social.isurf.ca/display/c6caade0ed4a01395a311eac510f7330

It claims to be posted from danie10@squeet.me but if one goes to the actual thread, https://squeet.me/display/c6caade0ed4a01395a311eac510f7330?owt=14975784f0dbeab091c1f23dcc6c1182 it was posted by another user from another instance (mudflap@sysad.org)

I should note that I block sysad.org on my instance.

Friendica Version:

2021.09-rc - 1434

Friendica Source: git

PHP version: 7.4.22

SQL version: MariaDB 10.5.10

**Comment by MrPetovan** [comment]
This isn't good, `danie10@squeet.me` is shown as the liker and I assume you are following them, so maybe this is what caused the confusion internally? @annando

**Comment by realkinetix** [comment]
Ah, yes, I can confirm I'm following danie10@squeet.me

**Comment by annando** [comment]
Yeah, that's weird. I saved the log, so that I can have a look at it later this week.

**Comment by annando** [comment]
This is some kind of double feature. The remote comment appeared as own post due to some problem in the `fetch` functionality. But this is only one half of the problem. The question also is why the comment had to be fetched. It should had been relayed to the receiver automatically.

**Comment by annando** [comment]
@realkinetix I'm still not totally sure why this comment hadn't been distributed to your system and had to be refetched when it had been liked. Both the comment and the like should had been transported the same way. I added some logging for future issues.

**Comment by realkinetix** [comment]
@annando Isn't it odd that it showed up at all when I am blocking the instance of the commenter?

**Comment by MrPetovan** [comment]
It may have been the reason why it showed this way, since we are checking the author's domain for a block, the original post wouldn't have reached you, but the related activity of the account you follow would, which we would try to reconstruct a thread from.

**Comment by annando** [comment]
@realkinetix that blocking is exactly the reason why the other bug occurred at all. So I haven't to check the message delivery process anymore.
