### ISSUE TITLE
Recursion problem

### ISSUE THREAD

**Issue by hansw-nlo** [friendica/friendica#10664]
https://federate.hopto.org/contact/18134/conversations

Dear all, on the link I posted I see another recursion problem. We've seen them in the past

### Bug Description

Post are show over and over if the user scrolls down a lot.

### Steps to Reproduce

1. See the link

Expected Result:

None repeated posts. 

### Platform Info

Friendica Version:

Friendica 'Siberian Iris' 2021.07 - 1424

Friendica Source: 

PHP version: 7.3.29-1~deb10u1 (raspberry so it is arm)

SQL version:mysqlnd 5.0.12-dev - 20150407

**Comment by MrPetovan** [comment]
Thank you for the report, for your information any `/contact...` URL is specific to the logged in user so we can't check the display of the URL you posted. Please post screenshots instead.

**Comment by hansw-nlo** [comment]
Hmm, if I keep making the post as small as possible it will hardly show more then one  of them since there  are some pictures in it that is shown beneath each other

**Comment by MrPetovan** [comment]
Some browsers give you the possibility to capture a whole page, resulting in a tall picture rather than a wide one like for screenshots.

**Comment by annando** [comment]
I have the feeling that we solved this problem in the current version. Can you switch to the RC to see if it is fixed?

**Comment by hansw-nlo** [comment]
I will in a few weeks, having my vacation now and to busy to watch it closely.

**Comment by hansw-nlo** [comment]
Sorry, I stopped using Friendica due to more issues. Was to busy tuning, etc...

**Comment by MrPetovan** [comment]
Thank you for the follow-up!
