### ISSUE TITLE
Add security token check to /contact module

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10672]
Discovered while working on #10502

**Comment by annando** [comment]
Wouldn't this be a good solution for our "probe" problem?

**Comment by MrPetovan** [comment]
No, the form security token only prevents someone from creating a malicious POST form on another website pointing to a Friendica instance where a user could be logged in already. It also makes GET links using it expire after a while, which prevents users to redo something by mistake or forces them to reauthenticate for sensitive settings changes.

If you're a legitimately logged in user, you can easily obtain a form security token and issue several legitimate probe calls.
