### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10678]
see https://github.com/friendica/friendica/issues/10679

**Comment by foss-** [comment]
Just saw on an instance running latest code that this has already been touched:

<img width="686" alt="Screenshot 2021-09-08 at 10 22 58" src="https://user-images.githubusercontent.com/5708172/132473805-448e4427-ba70-494f-979f-2b1727791370.png">

Personally prefer `Timeline` over `Content` as users will be familiar with that term and Content feels a bit blurry.

**Comment by MrPetovan** [comment]
I can't delete GitHub issues 🤷‍♂️
