### ISSUE TITLE
Twitter - wrong "translation" of text and links from friendica to twitter

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10671]
### Bug Description

When writing a longer post with several links, on twitter the post will have just the last link

The screenshot below were transferred to twitter this way

```
#NEINDOCHOH
RKI: Bundesweite Sieben-Tage-Inzidenz auf 84,3 gestiegen
https://www.nytimes.com/2021/09/01/health/covid-kidney-damage.html?referringSource=articleShare
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/24474762/132166959-0aececd4-1c2b-467f-ae65-196ef6d65152.png)

### Platform Info
Friendica Version: 2021.09-rc
Friendica Source:  git
PHP version: 7.4
SQL version: MariaDB

**Comment by annando** [comment]
Please provide the Twitter link. I need to have a look at the original post.

**Comment by hoergen** [comment]
I deleted that tweet because it was totally misleading. I pasted the output in quotes in the issue above.

**Comment by annando** [comment]
Ah, I just realized that it went to Twitter and not from Twitter to Friendica. Enable "Intelligentes Link-Kürzen ausschalten" and "Einfache Textkürzung aktivieren". This deactivates any automated link guessing.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
