### ISSUE TITLE
Joseph Hogan please read this

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10687]
Here's the private message I received this morning from Joseph Hogan (`joe@social.mmaj.ca`):

> Hello Hypolitel,
> 
> This is Joseph, the person from Montreal, Canada. I've been a little silent since I've been super busy. I tried upgrading my friendica with no success.
> 
> I have decided to reinstall Friendica with the latest version. and, a friend of mine showed me how git works, so I will be using GIT to install and upgrade.
> 
> But, I have a couple of questions, and when posting on the friendica support forum, I have gotten no replies. No sure if no one sees my messages, or they just are not showing up.
> 
> I am hoping to get some help and get active again.
> 
> Can yo let me know that yo get this email and if you see my message on the support forum?
> 
> Thanks!
> 
> Joseph

I tried to reply to them with the following answer:

> Hi Joseph, I received your private message loud and clear. However I can't see any recent message from you in the Friendica Support forum. Did you reinstall Friendica from scratch on the same domain by wiping the database out by any chance?
> 
> In this case you could have federation problems as your node's cryptographic keys have changed so its indistinguishable from an impersonation attempt.

But the message sending didn't work, I assume because Joseph Hogan's account on their new node with the same username on the same domain is failing the security check.  I'm getting the following error pop-ups:
- "Unable to locate contact information"
- "Message not available."

Unfortunately I have no other way to contact Joseph, hence the title.

Beyond this inconvenience, it seems like we're accepting private messages from anyone without checking their cryptographic keys which isn't great. I understand I can't reply to them, but I shouldn't have received the message in the first place, or with a privacy warning about the potential impersonation.

**Comment by annando** [comment]
I received the message as well - and couldn't reply.

**Comment by MrPetovan** [comment]
Is there a way we can still reply, again with a bright warning that the person might not be who they are?

**Comment by annando** [comment]
I have to have a deeper look.

**Comment by smokinjo** [comment]
How can I help?  I have the crippled server.  This is Joseph Hogan
