### ISSUE TITLE
Form security token incorrect error on URLs of a contact's posts/comments

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10684]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

When I go to to the page where I can view a contact's posts or posts & comments the page doesn't load. I get an info/error bubble instead saying...
"The form security token was incorrect. This probably happened because the form has not been submitted within 3 hours."

Example URLs:
`https://libranet.de/contact/1319055/conversations`
`https://libranet.de/contact/1319055/posts`
With both URLs I'm redirected to `https://libranet.de/contact/1319055`

I'm using frio in case that's important.

### Steps to Reproduce

1.  scroll through your network page
2.  click on an avatar to open the contact's info card
3.  click on the little cloud icon (network posts)
4.  you should see the posts of that contact, but you see the contact details (profile) instead
5.  try to open the posts / posts & comments by clicking on 'Status' or 'Posts and Comments'
6.  you stay on the contact details page and you get the info/error notification/bubble

Actual Result:

`https://libranet.de/contact/XXXXXX/conversations`
`https://libranet.de/contact/XXXXXX/posts`
...don't work.

Expected Result:

Both URLs should work. And the error/info notification/bubble shouldn't appear.

### Platform Info

Friendica Version:
2021.09-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
User reported it here: https://libranet.de/display/0b6b25a8-8361-3a45-3f46-749234525933

**Comment by annando** [comment]
@AlfredSK have you just updated the instance? If yes, then https://github.com/friendica/friendica/pull/10673 could be the source.

**Comment by AlfredSK** [comment]
Yes. I updated around 16:30 CEST. 2 hours later the user reported the issue.

**Comment by annando** [comment]
So we call @MrPetovan to the rescue!

**Comment by xundeenergie** [comment]
I got the same. Updated a few hours ago to last commit in RC.

**Comment by MrPetovan** [comment]
I'm on it, thank you for the report.

**Comment by xundeenergie** [comment]
Seems it fixed it. 

Thank you!
