### ISSUE TITLE
Deleting Twitter contacts does not work.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#10698]
When I try to delete a Twitter contact I get this message, and the page looks kind of broken.

Im on latest RC

`The security feature was not correct. This usually happens if the form was open too long before it was sent (longer than 3 hours).`
![202109121425](https://user-images.githubusercontent.com/12480023/132991796-048fbf9f-0447-43d5-9a61-8dfc0c11ed9c.png)

**Comment by copiis** [comment]
It seems that importing the Twitter contacts does not work either.

**Comment by tobiasd** [comment]
related by #10673

**Comment by MrPetovan** [comment]
Is it just Twitter contacts or all contacts? Don't worry, you still need to confirm to delete so you won't have to delete any contact.

**Comment by ghost** [comment]
> Is it just Twitter contacts or all contacts? Don't worry, you still need to confirm to delete so you won't have to delete any contact.

Only Twitter contacts, Mastodon, Diaspora, RSS Feeds and DFRN contacts can be deleted, but without confirmation if you click on the "X" symbol to the right of the contact.

**Comment by MrPetovan** [comment]
I'm sorry if you had to figure it out the hard way! 😅
