### ISSUE TITLE
Wrong URL parsing at composer (with Tusky)

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#10692]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I posted a deep-link into Github with the Android App "Tusky", but the Deep-Link got converted to a strange Link.

**Input:** `https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#L160`

**Output:** `L160]https">https]L160]https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#[url=https://https://friendica.philipp.info/search?tag=L160]L160[/url][/url]`

### Steps to Reproduce

1.  Using Android App tusky as Client
2.  Create a new post with the example URL

Actual Result:

see Output:
L160]https">https]L160]https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#[url=https://https://friendica.philipp.info/search?tag=L160]L160[/url][/url]

I guess that the `#L160` confuses the server

Expected Result:

https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#L160

### Screenshots

see https://friendica.philipp.info/display/f1417ed3-5561-3c44-71d0-5f2116102314 for an example

### Platform Info

Friendica Version: 2021.09-rc

Friendica Source: docker/GIT

PHP version: PHP7.4

SQL version:

**Comment by MrPetovan** [comment]
Yeah, hashtag regular expression. I’ll take it.

**Comment by MrPetovan** [comment]
Uh, Babel doesn't yield a wrong result with this URL, it sounds like the problem comes from the API code, which I'm not thrilled to have to debug.

**Comment by annando** [comment]
Possibly these lines play a role: https://github.com/friendica/friendica/blob/2021.09-rc/src/Module/Api/Mastodon/Statuses.php#L63-L66

Edit: ```$body = BBCode::expandTags($body);``` is to blame here.

It converts
`[url=https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#L160]https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#L160[/url]`
to
`[url=https://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#[url=https://https://pirati.ca/search?tag=L160]https]L160]https[/url]://github.com/friendica/friendica/blob/2021.09-rc/src/Util/Logger/StreamLogger.php#[url=https://https://pirati.ca/search?tag=L160[/url]]L160[/url][/url]`

**Comment by MrPetovan** [comment]
Thanks for doing the heavy lifting, I can take it from here.
