### ISSUE TITLE
Authorizing apps such as Tusky does not work

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#10700]
Authorizing apps such as Tusky does not work.
When you click on Okay, the page reloads and nothing happens.

I am on RC

![Screenshot_20210912-170821_Vivaldi](https://user-images.githubusercontent.com/12480023/132993093-eda1a4dc-34fc-45f2-a8a9-be180f3b88a3.png)

**Comment by tobiasd** [comment]
Pinging @annando is this something for the September release, or more for the Hackathon / December?

**Comment by annando** [comment]
I cannot reproduce this.

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/12480023/133595598-903e8c4e-b422-4480-8377-2f2f7edd4bd3.mp4

Can I look up what's wrong here somewhere?

**Comment by ghost** [comment]
Okay, the app appears in the settings under connected programs, but I am not redirected to Tusky on my phone.
![202109161148](https://user-images.githubusercontent.com/12480023/133602448-442617b2-765f-41a7-912f-d2b6b1fae6b5.png)

**Comment by ghost** [comment]
I have now deleted Vivaldi and tried it with the internal mobile phone browser and then I get the following error message.
![Screenshot_20210916-132228_Browser_1](https://user-images.githubusercontent.com/12480023/133603934-004d50ef-7547-4028-9356-be8bf28351e0.png)

**Comment by annando** [comment]
Looks like some phone issue to me. Since the app is registered, we did everything that we could. It seems as if this redirect is not processed on your phone.

**Comment by ghost** [comment]
Now it worked, I threw down Vivaldi and reinstalled it.
