### ISSUE TITLE
Stay local - where it doesn't make sense

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10705]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

There is a place where the 'stay local' feature doesn't make sense. When I visit the local profile of a contact (e.g. `https://libranet.de/contact/677605`) there is a link to the remote profile: `https://botsin.space/users/tiny_cityscapes`. 

When the feature 'stay local' is enabled clicking that link will redirect the user to `https://libranet.de/contact/677605/conversations` which doesn't make sense because the link text shows the remote URL.

Maybe there are more places like this. But this is the one I stumbled upon several times.

### Steps to Reproduce

1.  enable the stay local feature
2.  go to a local profile of a remote user
3.  look at the link and click on it (see also the provided screenshot)

Actual Result:

The link looks like a link to the remote profile but it redirects to a local URL.

Expected Result:

In this case the 'stay local' feature doesn't make sense. A URL to the remote profile should redirect to the remote profile.

### Screenshots

![grafik](https://user-images.githubusercontent.com/3656054/133142001-57324ed5-ef4f-4097-bfdb-5d6e40c60bb2.png)

### Platform Info

Friendica Version:

2021.09-rc

Friendica Source: 

git

PHP version:

7.4

SQL version:

10.3 MariaDB

**Comment by MrPetovan** [comment]
Thank you for the report, it indeed doesn't make sense.
