### ISSUE TITLE
Addons: Jappix-mini: Replace error link to Jappix website with something more useful

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1071]
Right now when the jappix box shows an error, clicking on that box leads to the jappix.com website which is not helpful and not intuitive. Replace it with f.e. popping up the error message.

**Comment by vinzv** [comment]
I could not get Jappix to run ad-hoc and don't have a BOSH server around either. So I could not check myself if this problem still exists. Maybe it's already solved? Can we close this issue?

**Comment by annando** [comment]
No one had worked on this addon for years.

**Comment by MrPetovan** [comment]
Closing.
