### ISSUE TITLE
Replace Verb model with class constants

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10727]
Offshoot of #10722

There are few enough verbs and they are common for all Friendica nodes that they can be handled by PHP class constants instead of by database calls.

Th tricky part is ensuring that the existing verb ids are matching the new hard-coded verb ids in the constant since we've been relying on auto-increment on each individual node.

**Comment by annando** [comment]
We have to store all incoming verbs and that can include some quite exotic ones. We can move the already existing text constants into some class, but the general handling shouldn't be touched at all.

**Comment by MrPetovan** [comment]
Aaah, I didn't think about receiving verbs. So the ones in `Activity` are the ones we know about, and we have an arbitrary table for unsupported ones. Thanks for the pointer.

**Comment by annando** [comment]
BTW: We are already storing the basic activities in a fixed order in the `verb` database: https://github.com/friendica/friendica/blob/2021.09-rc/src/Database/DBStructure.php#L1259-L1261

But this isn't extendable, so we couldn't easily add new activities (for example we could add support for the "block" activity from Mastodon).

This means that we should stay with comparing the activity strings with the values that we receive via views like `post-user-view`.

BTW: These activities are currently known by my system:
 
- http://activitystrea.ms/schema/1.0/delete                         
- http://activitystrea.ms/schema/1.0/favorite                       
- http://activitystrea.ms/schema/1.0/follow                         
- http://activitystrea.ms/schema/1.0/join                           
- http://activitystrea.ms/schema/1.0/like                           
- http://activitystrea.ms/schema/1.0/make-friend                    
- http://activitystrea.ms/schema/1.0/post                           
- http://activitystrea.ms/schema/1.0/share                          
- http://activitystrea.ms/schema/1.0/tag                            
- http://activitystrea.ms/schema/1.0/unfavorite                     
- http://activitystrea.ms/schema/1.0/update                         
- http://kirgroup.com/schema/1.0/created                            
- http://mastodon.social/schema/1.0/block                           
- http://purl.org/macgirvin/dfrn/1.0/dislike                        
- http://purl.org/zot/activity/attendmaybe                          
- http://purl.org/zot/activity/attendno                             
- http://purl.org/zot/activity/attendyes                            
- http://purl.org/zot/activity/poke#bitchslapped                    
- http://purl.org/zot/activity/poke#fingered                        
- http://purl.org/zot/activity/poke#giggled+and+fawned+at           
- http://purl.org/zot/activity/poke#pinged                          
- http://purl.org/zot/activity/poke#pointed+out+the+poke+feature+to 
- http://purl.org/zot/activity/poke#poked                           
- http://purl.org/zot/activity/poke#raised+their+eyebrows+at        
- http://purl.org/zot/activity/poke#slapped                         
- http://purl.org/zot/activity/poke#something+obscenely+biological  
- http://purl.org/zot/activity/poke#stroked+their+beard+at          
- https://www.w3.org/ns/activitystreams#Announce

**Comment by MrPetovan** [comment]
If the list can grow arbitrarily, then constants aren't the right way to handle these.
