### ISSUE TITLE
Scheduled Posts - Display Timezone

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#10737]
### Related problem

In scheduled posts, there is currently a discrepancy between how the datetimepicker relies on the browser timezone and how the scheduling time is executed according to the user-set timezone.

This may lead to confusion for travellers across different timezones and in other use cases. See here: https://github.com/friendica/friendica/issues/10691 , esp. https://github.com/friendica/friendica/issues/10691#issuecomment-922618111

The underlying issue is that the deployed JS library lacks a `timezoneOffset` option. See here: https://github.com/xdan/datetimepicker/issues/165#issuecomment-922542122

### Request for enhancement feature

A display of the current user-set timezone near the date/ time field would provide certainty when the post will go out.

I'd envisage something like this; it could also contain a hyperlink to the relevant user setting for a swift adjustment of the timezone in case of travel:

![Screenshot_2021-09-12_10-07-29](https://user-images.githubusercontent.com/28751375/133959477-501725d3-d2da-405d-bbce-c48583f9cc8d.png)

### Additional context

Friendica Version: 2021.08-rc

**Comment by MrPetovan** [comment]
Closed in #10818
