### ISSUE TITLE
Twitter: Allow unfollowing contacts from Friendica

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10734]
**Currently**

Follow contacts from friendica: ✓
Unfollow contacts from friendica: ⨉

**Expected**

Follow contacts from friendica: ✓
Unfollow contacts from friendica: ✓

Unfollowing should be possible as per https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/post-friendships-destroy

This would be an important step to get to a much better place in contact management for twitter contacts. Currently the situation is very confusing and messy. Unfollow does not exist. But Drop contact is offered and contacts can be deleted but are recreated as they are currently never unfollowed.

**Comment by annando** [comment]
I'm not sure if people expect that removing a Twitter contact in Friendica would mean that that Twitter contact would be removed from your Twitter feed as well.

**Comment by MrPetovan** [comment]
Not "removing", but "unfollowing" is pretty straightforward as meaning goes.

**Comment by foss-** [comment]
Personally think that is very expected as it is analogue to subscribing to a Twitter contact from friendica which results in following that contact on Twitter. Adapting the correct terminology for Twitter contacts will help to avoid confusion.

If you are unsure about this, a confirmation dialog could include an explanation about the unfollow also happening on Twitter.

**Comment by foss-** [comment]
Follow-up: https://github.com/friendica/friendica/issues/10875
