### ISSUE TITLE
Massive growing database

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#10732]
- [X] I have searched open and closed issues for duplicates

### Bug Description

See this discussion: https://friendica.xyz/display/174591b4-7961-4749-cbba-fc9446316526

The size of the database has increased massively. Within a few days it has grown from 7 to 22 GB. I noticed it for the first time in July.

### Platform Info

Friendica Version: Friendica 'Siberian Iris' 2021.09-rc - 1434

Friendica Source: git

PHP version: 7.4.23

SQL version: MariaDB 10.3.27

**Comment by annando** [comment]
Which tables grew the most?

**Comment by atasingorneq** [comment]
How can I display the size of individual tables?

To get the size of the whole database, I use this:
`SELECT table_schema AS "Database", SUM(data_length + index_length) / 1024 / 1024 / 1024 AS "Size (GB)" FROM information_schema.TABLES GROUP BY table_schema;`

That's probably why I can't keep track of which table has grown so much. But maybe it helps anyway if I see how big the individual tables are.

**Comment by atasingorneq** [comment]
OK, if I have found the right script snippet on stackoverflow the `storage` table is by far the largest.

**Comment by annando** [comment]
You could try some `optimize table` to check if the `storage` table does shrink.

**Comment by atasingorneq** [comment]
I regularly use `mysqlcheck -o`, but it only reduces the size of the database by a few MB.

But I have now taken a closer look at the output and noticed that an error is output for the `storage` table.
`friendica.storage
note     : Table does not support optimize, doing recreate + analyze instead
error    : The table 'storage' is full
status   : Operation failed`

I suspect that this is because I don't have enough memory on my webspace and therefore the table can't be optimized. I will book some more memory in the short term and see if it works then.

**Comment by tobiasd** [comment]
Are you deleting old postings (from your contacts) or do you keep them forever? All the posted images would be placed in the `storage` table if I'm not mistaken.

**Comment by atasingorneq** [comment]
Yes, old posts will be deleted.

However, I seem to have some problem with optimizing, after `optimize table` the table is even bigger.

**Comment by AlfredSK** [comment]
Do you use the database as storage? I'm asking because I use the filesystem and my storage table is tiny (only some kilobytes).

**Comment by atasingorneq** [comment]
I use the database as storage.
