### ISSUE TITLE
Only use /redir for external links to private posts

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10745]
External links to Friendica posts look like this to me: https://friendica.mrpetovan.com/redir/184027?url=https://social.gl-como.it/display/3e3ce0df-2161-4af1-3d81-9bb134136271

The `184027` number only makes sense to my user account, but it's the link I end up sharing with my partner for example. When she opens the link, she gets a nasty permission error because, well, she isn't logged in as me on my domain.

Now we have the target redirect URL so we could just skip the blame and simply redirect to the intended if not logged in.

**Comment by annando** [comment]
For not being abusable through external resources we should only redirect when logged in.

**Comment by MrPetovan** [comment]
Ah, damn it, I forgot again about this. How about we only use this link when the post is private?

**Comment by annando** [comment]
I'm not sure if we know about the privacy state of a post when adding the `redir`. I'm not totally happy with this functionality but I don't know a good replacement.

**Comment by MrPetovan** [comment]
Making sure we know when the link is generated is easier to live with than a gaping security hole on one hand, or a user inconvenience on the other.
