### ISSUE TITLE
nodes with Linkedin, Facebook and Twitter

### ISSUE THREAD

**Issue by Rik44444** [friendica/friendica#10742]
Hi all,
i am trying to find a Friendica node that offers linking/crossposting to Linkedin, Facebook and Twitter. I've looked through this list:https://the-federation.info/friendica 
But cannot find any. Does anyone have suggestions? 
Thanks,
Rik

**Comment by annando** [comment]
There is no connection to Facebook anymore since Facebook closed their API several years ago. Twitter should be available at many systems.

**Comment by AndyHee** [comment]
Posting to Facebook is not possible any more. This has been the result of FB deliberately modifying their code that prevents this.

LinkedIn, if I remember correctly, was possible at some point, but I think this deprecated.

**Comment by Rik44444** [comment]
ah that's a shame about FB
OK i will look into availability of one with crossposting to Linkedin and Twitter. Seems they do exist:
https://the-federation.info/node/social.outsourcedmath.com
https://the-federation.info/node/nsfw.wnymathguy.com
https://the-federation.info/node/philos.fkn-systems.de

**Comment by ghost** [comment]
> Linkedin

LinkedIn isn't possible to
