### ISSUE TITLE
Feature request: queueing

### ISSUE THREAD

**Issue by Rik44444** [friendica/friendica#10741]
Feature request: a really powerful feature of Buffer and Hootsuite is that besides scheduling (picking a specific date and time for a post), they also allow for “add post to queue”. In the settings you can then set the posting frequency for your queue, eg twice per day on Monday, Tuesday , Wednesday and Thursday at 11h and 15h. And then the posts in your queue are posted automatically at those times. The reason this is a super important feature is that this way you regularly post posts , which is important for the algorithms and followers , without having to actually post yourself twice per day.

See below for some screenshots for what this looks like on Buffer, i think their interface is really good. If Friendica was able to implement this, then together with the links to Linkedin, Twitter and Facebook that it already offers + the new function to schedule posts (https://github.com/friendica/friendica/issues/8038), it would mean i would no longer need Buffer anylonger, and could switch to Friendica for my social media post management, which would be great! 

![image](https://user-images.githubusercontent.com/42555414/134155950-cbff6799-f297-456d-8f4a-5f4ac70f3244.png)

**Comment by AndyHee** [comment]
> important for the algorithms

In the Fediverse there are no algorithms. But I hope you find the new feature still useful. 

What kind of posting scenario do you have where you need to pay attention to algorithms?

I have no idea about Buffer. Does this mean the same post will be sent out twice on Mondays and Wednesdays?

**Comment by Rik44444** [comment]
no not the same post, you queue a number of posts, and one by one their are posted according to this schedule.
Algorithms may not be important to the Fediverse, but they are to other services that can be linked (such as Twitter). 
More importantly, Fediverse readers, like any other social media reader, appreciate regular content in their favorite channels/influencers, so being able to queue posts is really important if you want to become a bit more active in your social media activities.

**Comment by AndyHee** [comment]
I see. Algorithms as the defined instructions for who sees what posts by "random" people.

In the Fediverse, your timeline only shows posts by people you follow, posts by people that your contacts interact with, replies by your followers, and posts from forums that you subscribe to.

The only way seeing random posts is via hash tags, providing your and the other person's node has a relay fuction. This function does not extent to Twitter though.

Friendica's Twitter plugin only brings in posts from your actual contacts, I think; I don't think it will show random interaction. It's mainly designed to keep in touch with your Twitter contacts.

Using Friendica merely like a Buffer app is probably way beyond it actual design and propose.

**Comment by Rik44444** [comment]
hi @AndyHee ,
OK. Just to reiterate again, this is just as much about giving your followers/friends frequent posts as it is about algorithms. So if the fediverse is algorithm-free, then you you can see this feature request as a way for active Friendica users to provide their followers/friends with regular posts

**Comment by annando** [comment]
@AndyHee I see a huge potential for this queuing. I think it is good to post your content at times when most of your followers are active. And using this queuing ensures that posts are published at the best times. For example when you are living in Asia but most of your followers are from the US then you can delay your posts so that they will see your posts at a time when they are awake.

Also this feature is really fine when distributing posts from feeds. Normally the system will read the feed items and will post them at some time, whenever this will be. With the queueing you will be able to control the times when the mirrored posts will be published.

And concerning Twitter: These queued posts will be posted to Twitter as well when it is enabled. So yeah, this brings some of Buffer's functionality to Friendica. But I don't see a problem here, as long as people interact on their Friendica accounts as well.

**Comment by AndyHee** [comment]
@Rik44444 I understand what you're saying. 

The reality on this project, and most other open source projects, there is a considerable lack of developers. Friendica for instance needs active front-end developers. The 2.5 core developer team is massively overwhelmed with maintaining and overhauling the inherited spaghetti code. 

Once in while a new feature request actually makes it for various strategic reasons. I optimistical estimate that one in 25 new feature requests end up being implemented.

If you know any willing developers (regardless how experienced), you can definitely mention our project to them. The perks might be limited, but they would gain invaluable experience within a friendly and constructive open source developer team.

**Comment by AndyHee** [comment]
Absolutely @annando and of course it would be an extension of the existing scheduling feature by adding specific preset times. Nice.

> as long as people interact on their Friendica accounts as well.

Yes that's the point I was making.

**Comment by Taur1O** [comment]
Tumblr has a similar feature, there's allows you to select the time period you want your posts to show up, and how many posts you want, and it exists solely for to avoid flooding, which is why I'd like to see it added to Friendica.

**Comment by annando** [comment]
For some time now we can create posts and can define the date and time that they will be posted. So I consider this issue as solved.
