### ISSUE TITLE
Offer users to revoke follows besides blocking

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10754]
It is currently possible to unfollow someone, but not directly to make someone unfollow us. It used to be silently done on contact drop, but [this feature is going away in version 2021.12](https://github.com/friendica/friendica/pull/10762). The same PR moves the follow revocation to the blocking feature, silently again.

This issue tracks the creation of an explicit control to revoke follows as suggested in https://github.com/friendica/friendica/pull/10751#issuecomment-927126951

It would be a separate button from the "Follow" button, depending on the current relationship status and the eventual support of the feature by the target network.

Potential locations of the button with my opinion for each:
- In the Contact list page, in a Contact row (already button-crowded)
- In the Contact page, in the Actions menu (confidential, appropriate given the edge use case)
- In the Profile vcard on the left (too prominent for a marginal feature)

**Comment by annando** [comment]
We could just use the same place where currently the deletion is present.

**Comment by MrPetovan** [comment]
I feel like the contact drop action was present in way more places than the revoke follow really needs to be.
