### ISSUE TITLE
Timeout for View Logs view if the log contans no entries

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#10766]
### Bug Description

If the Friendica log is completely empty (contains no log entries), the View Logs view (`/admin/logs/view`) runs into timeout and the browser displays only **504 Gateway Time-out** instead of an empty list.

### Steps to Reproduce

1.  Create a completely new log file or empty the current one.
2.  Go to Admin > View Logs (`/admin/logs/view`).
3.  Wait until the browser informs you about timeout.
4. Add at least one log entry to the log file.
5. Go to Admin > View Logs again, the list of log entries is displayed correctly.

Actual Result:

504 Gateway Time-out message in the browser.

Expected Result:

An empty list or a message like "No messages are available." in a rendered page.

### Platform Info

Friendica Version: 2021.09
Friendica Source: full package from https://files.friendi.ca/
PHP version: 7.4.3

**Comment by MrPetovan** [comment]
Paging @fabrixxm
