### ISSUE TITLE
Strings are not marked as translatable in View Logs

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#10767]
### Bug Description

The file [view/theme/frio/templates/admin/logs/view.tpl](https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/admin/logs/view.tpl) has all the strings hard coded, there is no translation support. These strings are displayed always in English in the browser.

### Steps to Reproduce

Open the source file mentioned above and check the strings. Nothing is marked as translatable.

Actual Result:

The page is rendered always in English. It doesn't honor the system language.

Expected Result:

The page should be rendered in the language of the system.

### Platform Info

Friendica Version: 2021.09

**Comment by MrPetovan** [comment]
Thank you for your report!
