### ISSUE TITLE
Twitter Addon - URLs are doubled when sending to twitter

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10772]
When posting an URL in friendica and using the twitter plugin, on the twitter post the URLs are doubled

Friendica post

![01_temp](https://user-images.githubusercontent.com/24474762/134967668-50df65d1-153b-4d48-8e6a-8ac71beb5e1f.jpg)

Twitter post

![00_temp](https://user-images.githubusercontent.com/24474762/134967648-28e590c2-942f-4f66-aa73-e91b9ba2cc28.jpg)

Friendica Version: 2021.9 stable
Friendica Source:  Git 
PHP version: 7.4
SQL version: MariaDB

**Comment by MrPetovan** [comment]
Closed by #10773 and https://github.com/friendica/friendica-addons/pull/1174
