### ISSUE TITLE
DB Fehler bei Update 021.09 - 1424

### ISSUE THREAD

**Issue by gitkald** [friendica/friendica#10774]
After Updating my friendica, I get an error: _Das Update der Datenbank ist fehlgeschlagen. Bitte führe 'php bin/console.php dbstructure update' in der Kommandozeile aus und achte auf eventuell auftretende Fehlermeldungen._

If I try this command I get this error:
ALTER TABLE `delayed-post` ADD `wid` int unsigned COMMENT 'Workerqueue id', ADD INDEX `wid` (`wid`), ADD FOREIGN KEY (`wid`) REFERENCES `workerqueue` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;

Fehler 1050 beim Update der Datenbank aufgetreten
Table './friendica_ennimedia/delayed@002dpost' already exists
Fehler beim Ändern der Datenbank aufgetretenALTER TABLE `delayed-post` ADD `wid` int unsigned COMMENT 'Workerqueue id', ADD INDEX `wid` (`wid`), ADD FOREIGN KEY (`wid`) REFERENCES `workerqueue` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;

I use friendica with MySQL.

**Comment by annando** [comment]
Please execute 
```
select * from `delayed-post`;
```

if this result is empty then it is the easiest way to just delete that table and run the command  ```php bin/console.php dbstructure update``` again.

**Comment by gitkald** [comment]
> Please execute
> 
> ```
> select * from `delayed-post`;
> ```
> 
> if this result is empty then it is the easiest way to just delete that table and run the command `php bin/console.php dbstructure update` again.

This was the solution. Thx Michael.
