### ISSUE TITLE
With 2FA user is asked to enter OTP on every browser restart

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10780]
### Bug Description

Once 2FA is setup, users are asked for OTP on every browser restart.

### Steps to Reproduce

1.  setup 2FA
2.  restart browser

Actual Result: user asked for OTP

Expected Result: Still logged in and not asked for OTP when using same computer and same browser.

Additional info: Tested with Firefox 92.0.1, clearing all cookies on closing but with firendica whitelisted in Preferences > Privacy & Security > Cookies and Site Data.

### Platform Info

This is Friendica, version 2021.12-dev that is running at the web location https://pirati.ca. The database version is 1434/1435, the post update version is 1427/1427.

**Comment by MrPetovan** [comment]
The "Remember Me" option for login is independent from the "This is my 2FA device" option even if they have the same goal: skip password login and skip 2FA verification.

Both use cookies so they should both survive the whitelisting you are alluding to.

**Comment by foss-** [comment]
I was a bit wrong here: user is still logged in but asked for OTP Code upon browser restart.
<img width="655" alt="Screenshot 2021-09-30 at 15 03 37" src="https://user-images.githubusercontent.com/5708172/135460531-15b3d4f4-3096-4c0a-be43-cd0d7beb5add.png">

But that behavior is not happening for other sites when using the same computer + browser.

**Comment by foss-** [comment]
1 Delta 10 Tango situation. I actually did not understand the option `This is my two-factor authenticator app device`. Ticking that option resolves the problem.

Follow up: https://github.com/friendica/friendica/issues/11177
