### ISSUE TITLE
Vier Theme: Logo will be scaled to wrong height

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1081]
The vier theme scales images to the wrong height value. 

Example can be seen on snarl.de where the logo should be 32px \* 32px but instead is scaled to 32px \* 22px

The responsible entry in the styles.css is:

header #banner #logo-img {
    height: 22px;
    margin-top: 5px;
}

**Comment by tobiasd** [comment]
with the recent changes on the view theme, is this still an issue?

**Comment by vinzv** [comment]
I can't reproduce the problem. Let's close this issue.

**Comment by annando** [comment]
If it's not reproducible then we can.

**Comment by MrPetovan** [comment]
Cloclosingsing
