### ISSUE TITLE
Friendica 2021.09 release tar.gz contains local.config.php

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#10829]
Release tar.gz   `friendica-full-2021.09.tar.gz` from https://files.friendi.ca/friendica-full-2021.09.tar.gz contains `config/local.config.php` file.

That file should not be included in release.

**Comment by MrPetovan** [comment]
Whoops.

**Comment by nupplaphil** [comment]
Oooooops... My fault, I manually created it because drone didn't work :-( ...

**Comment by tobiasd** [comment]
Can you update the archives manually?

**Comment by tobiasd** [comment]
Can someone of you add a node to the release page in the blog please. There is a "Known Issues" section.

**Comment by MrPetovan** [comment]
"Please pay no mind to @nupplaphil 's passwords mistakenly included in the archive" ?

I kid, I'll make the change.

**Comment by MrPetovan** [comment]
> **Update Mon Oct 4th**: A node-specific config/local.config.php file has been inadvertently included in the full archive. Please make sure you either remove it or overwrite it with your own when you perform the update as described above.

https://friendi.ca/2021/09/25/friendica-2021-09-released/

**Comment by AlfredSK** [comment]
Posted a comment as 'Friendica News' in the release announcement thread.

**Comment by MrPetovan** [comment]
The exclude list doesn't rightfully exclude the `config/local.config.php` file but now wrongfully excludes both the `config/addon-sample.config.php` and `config/local-sample.config.php` which are meant to be part of the release.

**Comment by nupplaphil** [comment]
This issue has an impact on the docker images as well :( small issue, big impact
