### ISSUE TITLE
Error when viewing events that were created before follow

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10837]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When I follow a forum that already has events entered, I can see the events in the forum's calendar but I can't view them. When I click on it I get the following error

### Steps to Reproduce

1.  create a forum
2.  create an event in the forum
3.  follow the forum

Actual Result:

I get the error displayed:

> Not found
> The requested post does not exist or has been deleted.
```
Exception thrown in /var/customers/webs/Anzah/rollenspiel.group/mod/display.php:221
Stack trace:
#0 /var/customers/webs/Anzah/rollenspiel.group/src/LegacyModule.php(90): display_content()
#1 /var/customers/webs/Anzah/rollenspiel.group/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction()
#2 [internal function]: Friendica\LegacyModule::content()
#3 /var/customers/webs/Anzah/rollenspiel.group/src/App/Page.php(333): call_user_func()
#4 /var/customers/webs/Anzah/rollenspiel.group/src/App/Page.php(390): Friendica\App\Page->initContent()
#5 /var/customers/webs/Anzah/rollenspiel.group/src/App.php(708): Friendica\App\Page->run()
#6 /var/customers/webs/Anzah/rollenspiel.group/index.php(42): Friendica\App->runFrontend()
#7 {main}
```

Expected Result:

See the calendar entry to participate in the event

### Screenshots

![image](https://user-images.githubusercontent.com/12276250/136185490-d33aa37c-84c1-48fb-be44-58e4df74fcb2.png)
![image](https://user-images.githubusercontent.com/12276250/136185543-030006f1-566a-40f8-b36c-860b03917a24.png)
![image](https://user-images.githubusercontent.com/12276250/136185571-7bb8c293-068e-42fa-8f53-e19ad93ebbca.png)

### Platform Info

Friendica Version:  2021.09 - 1434

Friendica Source: git

PHP version: 8.0.11

SQL version: mariadb 1:10.5.11

**Comment by Tealk** [comment]
I'm using the 2021.12-dev - 1438 and now I don't see the events that were shared from the forum anymore @annando 
![image](https://user-images.githubusercontent.com/12276250/137146650-0e943205-3b1a-4749-8b57-6ac661e5b0f4.png)

**Comment by annando** [comment]
That cannot be related to my changes, weird.

**Comment by Tealk** [comment]
I also don't see newly created events, but in my timeline the new event shows up
