### ISSUE TITLE
bin/console po2php unable to extract some strings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10832]
### Bug Description

I've noticed in https://github.com/friendica/friendica-addons/pull/1183 that the `bin/console po2php` command is unable to extract the following string from the `$lng/messages.po` file.

```
#: nitter.php:99
#, php-format
msgid ""
"In an attempt to protect your privacy, links to Twitter in this posting were"
" replaced by links to the Nitter instance at %s"
msgstr ""
"A magánélet védelme érdekében az ebben a bejegyzésben lévő Twitterre mutató "
"hivatkozások a %s címen elérhető Nitter-példányára mutató hivatkozásokkal "
"lettek helyettesítve."
```

### Steps to Reproduce

1. fetch the current `$lng/messages.po` file from transifex
2. run `bin/console po2php $filename` be happy to read the success message
3. have a look at the produced `$lng/strings.php` file and miss that string entirely.

One can try this with the `addon/nitter/lang/de/messages.po`.

Actual Result:

String gets discarded.

Expected Result:

Translated string being added to the `strings.php` file.

### Platform Info

Friendica Version: 2021-12-dev ac9e5df6142fbf387a01c55f121247a0cc0baa20

Friendica Source: git 

PHP version: PHP 7.4.24 (cli)

**Comment by tobiasd** [comment]
Problem seems to be, that the first line of the msgid / msgstr is empty `""` which might be, because else the line would be longer then 80 characters. Removing the `""` and pulling the second line up _seems to be a workaround_.

**Comment by MrPetovan** [comment]
Thank you for the report, I'll take a look at it.
