### ISSUE TITLE
Securemail PHP 8 compatible

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10839]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If using php8 and securemail is enabled, you will get the following error.
```
2021/10/05 13:16:07 [error] 394#394: *25695 FastCGI sent in stderr: "PHP message: PHP Fatal error: Array and string offset access syntax with curly braces is no longer supported in /var/customers/webs/Anzah/rollenspiel.group/addon/securemail/vendor/singpolyma/openpgp-php/lib/openpgp.php on line 125" while reading response header from upstream, client: 93.212.25.244, server: rollenspiel.group, request: "POST /removeme HTTP/2.0", upstream: "fastcgi://unix:/var/lib/fastcgi/6-anzah-rollenspiel.group-php-fpm.socket:", host: "rollenspiel.group", referrer: "https://rollenspiel.group/removeme"
```
https://rollenspiel.group/display/989be456-1761-5c2c-f9aa-689789533924

### Platform Info

Friendica Version:  2021.09 - 1434

Friendica Source: git

PHP version: 8.0.11

SQL version: mariadb 1:10.5.11

**Comment by MrPetovan** [comment]
Thank you for the report, this library doesn't seem to be actively maintained and as a result doesn't have PHP 8 support. We probably need to switch OpenPGP library for an actively maintained one but I don't know how extensive the changes would need to be nor do I have a setup to test it.

**Comment by MrPetovan** [comment]
Version 0.5.0 of `singpolyma/openpgp-php` seems to have fixed this issue, I'm not sure why I missed this before but it represents a clear upgrade path.

**Comment by pvagner** [comment]
While the library might not be well maintained, pulling latest version from github fixes this issue for me.
https://github.com/singpolyma/openpgp-php

**Comment by MrPetovan** [comment]
Thanks, I don't know why I missed this when this was reported, version 0.5.0 was already out.
