### ISSUE TITLE
How to remove contacts as a user, when the target account (server) doesn't exist any more

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10862]
How can a user remove accounts from the contact list where the servers (and the accounts) don't exist anymore?

Currently Friendica throws a timeout and advises to contact the administrator.

### Platform Info
- Friendica 'Siberian Iris' 2021.12-dev - 1437
- PHP 7.4
- MariaDB

**Comment by MrPetovan** [comment]
Thank you for the report, at the moment we don't update the local relationship if the unfollow message doesn't succeed like it happened to you. This prevents the case where the local relationship would be severed unbeknownst to the remote server and they would still try to deliver posts to you.

However, if the whole server doesn't exist anymore, the relevant accounts should soon be automatically archived by the contact update background task and they won't appear in your contact list anymore.

**Comment by hoergen** [comment]
It should but it seems it doesn't. 
That's why we discussed it in the Friendica Support Forum and I was asked to open an issue.

**Comment by MrPetovan** [comment]
Of course. At the moment we do not distinguish why the unfollow message was unsuccessful so we can't adapt the behavior depending on the cases. However, a timeout is the worst possible outcome since we can't guess whether the server is gone or temporarily unavailable, so we would show the same message to retry later.

**Comment by annando** [comment]
We could perform the unsusbcribe/remove functionality into some worker task. So we could set the "deleted" field in the contact table and we could try to send an "unsubscribe" for some time.

**Comment by MrPetovan** [comment]
We don't need this case to have a specialized handling for unfollow if the regular contact update can take care of it. Maybe we  just need to trigger a contact update task if the message fails?

**Comment by annando** [comment]
We shouldn't have two tasks that are doing the same. So we should separate the frontend action from the backend action. Means: You unfollow someone. Then the contact status is changed immediately. But the "unsubscribe" message is sent as worker task in any way.

**Comment by MrPetovan** [comment]
This is a good alternative, but this requires the creation of a couple new worker tasks for the unfollow and the revoke follow actions.

**Comment by annando** [comment]
This is done in a few minutes. (testing will take longer) We only need to separate the tasks. The whole handling of trying it again and again is all in the worker core.

**Comment by MrPetovan** [comment]
And the message part is in the Protocol class now, separated from the Contact stuff.
