### ISSUE TITLE
Mastodon API notifications don't work

### ISSUE THREAD

**Issue by annando** [friendica/friendica#10868]
With the current develop branch the API doesn't return any notifications. 

It comes down to the function `DI::notification()->selectByBoundaries` which returns this content:
```
object(Friendica\Navigation\Notifications\Collection\Notifications)#239 (2) {
  ["totalCount":protected]=>
  int(14)
  ["storage":"ArrayIterator":private]=>
  array(0) {
  }
}
```
Iterating this with `foreach($Notifications as $Notification) {` doesn't return anything, so no notifications are displayed at the moment.

**Comment by MrPetovan** [comment]
Maybe, but see how cleanly it returns nothing?
