### ISSUE TITLE
add Unfollow option to actions menu when on `View Contact`

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10875]
Tested on Friendica, version 2021.12-dev that is running at the web location https://pirati.ca. The database version is 1438/1438, the post update version is 1427/1427.

Contact Actions menu:
<img width="183" alt="contact   actions menu   no unfollow" src="https://user-images.githubusercontent.com/5708172/137278727-e44ea876-bb7e-4daf-8275-5ed50cf54349.png">

Contact left side pane:
<img width="167" alt="unfollow button in left side contact pane" src="https://user-images.githubusercontent.com/5708172/137278762-7b7550bc-2d48-45d5-a30c-f5bce87b31af.png">

Add `Unfollow` option to contact actions menu when on `View Contact` option. This is important for mobile. The way to unfollow a contact on mobile is to invoke the left side panel via the ellipsis icon. This works but has poor (none) visibility.

Edit: Split typo thing into separate issue https://github.com/friendica/friendica/issues/12112 and rephrased this issue here.

**Comment by MrPetovan** [comment]
Although I'm not sure what form it would take, addons have the possibility to not support follow/unfollow for their managed contacts, which would thwart the batch action.

And with such a prominent action button in the left column, I don't think we need to add it to the action dropdown menu in the single contact page either.

Good catch for the label inconsistencies though.

**Comment by foss-** [comment]
Just ran into this again and on mobile this is a bigger problem than on desktop since only the right OR the left column is visible. Searching for a contact only shows the actions menu without the unfollow option and no unfollow button is visible anywhere.

I have no idea, how to unfollow a twitter contact from mobile frio.
