### ISSUE TITLE
Email connector: mail contacts not selectable in composer modal

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10872]
I have no idea how the email connector and email contacts are supposed to work. But a user of venera.social reported that he could select email contacts in frio's composer modal in the past. But since I updated to 2021.09 (stable) it doesn't work anymore.

I managed to connect to my own imap server and I could send a private post to an email contact. That contact is in a test group. That works. But I don't get a contact suggestion when I start typing the email address of that email contact. So I cannot send a private message to an email contact.

![grafik](https://user-images.githubusercontent.com/3656054/137176611-4c4d6936-0a38-4cb3-904d-4b5799f9cb3c.png)
No contact suggestion 

Is this supposed to work that way? On the help pages I found this: "You may include email contacts in private conversations." So, it should work. Or shouldn't it?

**Comment by MrPetovan** [comment]
Thank you for the report!
