### ISSUE TITLE
Problem with Process.php function

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10871]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

The in the file Process.php there is a function that checks for free memory, and it uses /proc/meminfo and searches the field MemFree.  This really is wrong because Linux will use almost all memory for disk cache and even if you have 22GB available it will still fall below a very low value of MemFree.  This causes workers to not run even if you have 22GB available.  I changed
this to use the MemAvailable rather than MemFree entry in /proc/meminfo and it seems to work much better.  I would like to
suggest that this change be made to the code.

### Steps to Reproduce

Set a non-zero value for MinMemory for workers to run.  Workers will stop no matter for any non-zero value because sooner or later almost all available ram will be eaten for cache.  Changing this function to use MemAvailable instead of MemFree resolves this.

Actual Result:

Workers stop running even with 22GB of available memory.

Expected Result:
Workers continue to run unless there isn't enough available memory.

### Platform Info

Friendica Version:

Friendica 'Siberian Iris' 2021.12-dev - 1434

Friendica Source: 

Github

PHP version:
PHP 7.4.24 (cli) (built: Sep 23 2021 21:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by MrPetovan** [comment]
Thank you for the report, you are accurate about the memory use on loaded systems.

**Comment by MrPetovan** [comment]
Fixed by #10941
