### ISSUE TITLE
changes in profile get overwritten, but you must reload the page in order to see that.

### ISSUE THREAD

**Issue by aarontrom** [friendica/friendica#10903]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Everytime I change my description in the profile, the address or any other field, friendica saves the changes correctly, but I need to reload the page in order to see the changes. 

I just installed Friendica via YunoHost on my server and I'm learning how to run an instance.

### Steps to Reproduce

1.  Install a new Friendica node.
2.  Fill in your profile description.

Actual Result:

https://user-images.githubusercontent.com/69819346/138018396-4fde79ad-b3ca-4509-b01d-4e12521a380f.mp4

Expected Result:

Of course you should not reload the page in order to see the changes that you did.

### Platform Info

Friendica Version:

This is Friendica, version 2021.09 that is running at the web location https://social.tromdienste.de. The database version is 1434/1434, the post update version is 1427/1427.

Friendica Source: YunoHost

PHP version: PHP Version 7.3.29-1~deb10u1

SQL version: mysqlnd 5.0.12-dev

**Comment by MrPetovan** [comment]
Thank you for the detailed report!

**Comment by nupplaphil** [comment]
Regression alert by... Me , I think :/

**Comment by tio-trom** [comment]
Same here. Updated Friendica last night to the latest stable version and I see the same problem. It worked fine before.
