### ISSUE TITLE
Improve usability when posting to forums

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1091]
When I look at a forum on my instances (network entries from the "contact" forum), I still have to mention its name, otherwise my posting won't be displayed. That's confusing. Is it possible to involve some Javascript to auto-add the mention?

**Comment by Beanow** [comment]
:+1:, How should this be displayed visually though? Simply adding the @mention?

**Comment by tobiasd** [comment]
This was fixed with #1507 in the current develop branch I think.

**Comment by annando** [comment]
@tobiasd I would say so.
