### ISSUE TITLE
A way to deal with the storage files (too many, difficult to backup)

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10915]
My instance is 250 users strong. And already have 900.000 files in the storage department. It takes some 15 hours or more for the programs I use to check so many files to be able to incrementally download them to the backup location. Almost 1M files seems a crazy ton of files in my view, for just 250 people. We had some brief discussion on Friendica's forums about this but I think is worth opening an issue for. We should be able to purge some of these files.

What are these files btw? Just image files that come from everywhere like other instances and such? And how can we purge very old ones?

If our instance grows two times in size then 2M files are  as many as there are people in Latvia :D . And we can't take care of them all properly.

Ok let me know your thoughts!

**Comment by MrPetovan** [comment]
Have you disabled the proxy feature? This is a major source of storage consumption because any image posted will be copied on your server, with little control over their lifespan even if the last reference in a post is removed.

**Comment by tio-trom** [comment]
You mean this?
![2021-10-23_01-22](https://user-images.githubusercontent.com/38043315/138532770-e7fc84c5-ce10-44ff-9471-c48f7f7db0e7.png)

If so I just did that. So lets see.  Thanks!

In the meantime if there is a way to clean these files somehow let me know.

**Comment by AndyHee** [comment]
> disabled the proxy feature

Perhaps we should have an explanation about this in the hint. I.e that it's not recommend to be used together with the storage feature enabled.

**Comment by MrPetovan** [comment]
> In the meantime if there is a way to clean these files somehow let me know.

I have a folder named `proxy/` in my Friendica root folder, I'm pretty sure that's where they are.

**Comment by AndyHee** [comment]
> a folder named `proxy/`

I see, @MrPetovan. Very useful! 

I think @tio-trom means `/var/storage` or something to that effect, but I'm glad you're pointing this out.

Can the content of `proxy/` just be deleted from time to time?

**Comment by MrPetovan** [comment]
Yes, if the required file doesn't exist, it will be downloaded from the remote URL again. I seem to remember we do clean proxy files through a low priority worker task, let me make sure.

**Comment by MrPetovan** [comment]
Never mind, none of the files in the `proxy/` directory are older than July 10th of this year, so we must have changed the way it works.

**Comment by annando** [comment]
Yeah, we don't store any content anymore directly in the web root. We only store some stuff in the temp directory and - if configured - we store the storage files. And they are only stored for content in the `photo` table.

**Comment by AndyHee** [comment]
So we can delete the whole `proxy/` directory?

**Comment by annando** [comment]
When you are on the latest version.

**Comment by AndyHee** [comment]
Thanks @annando

**Comment by tio-trom** [comment]
Yes I am talking about the file storage directory "Folder where uploaded files are saved. For maximum security, this should be a path outside web server folder tree". I set that up to a folder in my home directory that I have access to. So the proxy files are stored here too?

**Comment by annando** [comment]
There are no proxy files anymore. The proxy data isn't stored on the server.

**Comment by annando** [comment]
The PR https://github.com/friendica/friendica/pull/10922 will help to save some (a lot of) disk space.

**Comment by tio-trom** [comment]
How about there will be an option to not store any remote images for longer than X days?

**Comment by 4nanook** [comment]
I've got 7.5 GB of images presently stored, 750 users, and 1336525 files so far and dump / restore handles that in about an hour with bz2 compression.

**Comment by tio-trom** [comment]
> I've got 7.5 GB of images presently stored, 750 users, and 1336525 files so far and dump / restore handles that in about an hour with bz2 compression.

Can you please tell me more about how you backup so many files?

**Comment by 4nanook** [comment]
/sbin/dump -b1024 -j9 -f friendica.dump.bz2 /friendica

Where friendica.dump.bz2 is the filename dumped to (I'm already cd'd to where it is stored, this is done in a script), this can also be a physical device such as a tape drive but to support compression it must support variable block lengths.

/friendica is the location of your friendica storage directory (not where I have it actually placed)

If you don't have dump/restore already installed, install with:
debian derivatives such as debian, ubuntu, mint, julinux, zorin, mxlinux, etc: apt install dump
old redhat derivatives such as centos7 scientific7: yum install dump
new redhat derivatives such as fedora, redhat, centos8, and centos-stream: dnf install dump
mandriva and company: pamac install dump

**Comment by tio-trom** [comment]
Thanks. I'd prefer tho a more automated solution. But compressing all files on the server may be a good idea indeed....

**Comment by 4nanook** [comment]
I use a small shell script that runs out of  cron, the shell script creates a data storage directory, makes the backup, and deletes directories more than so many days old, thus keeping a fixed number of rotating backups.

**Comment by SpcCw** [comment]
Was something changed recently in this proxy feature?

I noticed I no longer have any files in proxy folder. I even browsed a few pages of posts with photos and checked - yes, still empty. Also I notice image links now look like `https://friendica.server/photo/preview/600/2119203` not `.../proxy/...`

Yes, I have the checkbox " Proxify external content" on. The version is 2021.12-rc. Is it a bug or a feature? :)

**Comment by tio-trom** [comment]
Ok this is a reasonable idea to create an archive on the server, then pull it to a backup location. It is faster and I will try. However takes a lot more diskspace. My Friendica files are around 20GB in size, and if I create an archive to then backup, then the archive will also be stored locally.

**Comment by 4nanook** [comment]
You can use rdump to dump to a remote location rather than locally if you prefer or you can nfs mount disk from elsewhere, which is what I do.

**Comment by AlfredSK** [comment]
Just in case you're interested, I use `mysqldump` for db backups and `rsync` for files and storage. The backup script is also deleting backups older than 5 days. Twice a week I copy the locally stored backups to a remote storage server with `tar` (w/o any compression). The remote backup storage is mounted via davfs2.

But you're right, you need a lot of disk space to handle the backups locally. Concerning the speed of the backup, it makes a huge difference what kind of storage device the machine is using. Since I switched from HDD to SSD the backup is running much, much faster - minutes instead of hours. :-)

**Comment by tio-trom** [comment]
We use SSD too. But I didn't think of compressing the entire storage folder on the server, then grab it locally somehow. It will take too much SSD space tho....

> You can use rdump to dump to a remote location rather than locally if you prefer or you can nfs mount disk from elsewhere, which is what I do.

But if I create an archive and send it to a new location, isn't the archive created on the server and then sent to a remote location?

**Comment by 4nanook** [comment]
No, rdump compresses each block, then sends it across the net and writes it on the remote host.

**Comment by tio-trom** [comment]
Thanks @4nanook ! It may be too much for me to do this for technical and resource reasons. I manage over 20 such projects on my server + 10 more websites, so I would need a solution for all of my files. At the moment the best solution is to grab the friendica files in incremental ways, to my local machine via SFTP. But it is slow indeed...because of so many files.

**Comment by 4nanook** [comment]
I have hundreds of customer websites, mail, as well as a number of such projects, hubzilla, nextcloud, etc.  What is nice about dump / restore is in the restoration phase you can select which file(s) or directory(ies) you want to restore, so I dump all the server partitions this way and then just restore what I need.

**Comment by tio-trom** [comment]
Sounds very interesting. If you have some links that may help me with this please share them.

**Comment by 4nanook** [comment]
Don't really have any links, this is a very old tool.
apt install dump or yum install dump or pamac install dump depending upon your distro.
man dump
info dump
installing dump will also install rdump restore rrestore and rmt, they all work together.

**Comment by tio-trom** [comment]
Interesting. And how can it handle incremental backups?

**Comment by 4nanook** [comment]
Dump has a flag for incremental backups, I don't use it because when I restore restoration time is the ultimate goal so I prefer to
 avoid multiple iterations of restoration but it does have that capacity.

**Comment by tio-trom** [comment]
I see. Thanks! I will have a look at it maybe. Cheers!
