### ISSUE TITLE
Event start & end time wrongly converted in the RSS feed

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10914]
The RSS feed of a Friendica account contains the entries for new events in the calendar. After entering these dates in local time (e.g. CEST) the time in the RSS feed are converted to UTC - but no hint is shown that they are displayed in UTC instead of CEST.

Maybe a side effect of #10818

### Steps to Reproduce

Enter the event details in local time. e.g. CEST 19:30.

![grafik](https://user-images.githubusercontent.com/433490/138453264-94365588-0d4e-4ee6-8c92-6c06c61016c1.png)

Have a look in the RSS feed, which will show the event details in UTC

![grafik](https://user-images.githubusercontent.com/433490/138453407-7f02ac64-45a7-4d59-9bfe-999c618696c5.png)

Expected Result:

The time for the beginning and ending of an event should be converted into the local time of the user when generating the RSS feed.

### Platform Info

Friendica Version: 2021.12-dev (libranet.de)

**Comment by MrPetovan** [comment]
The problem is that at the time where the time string is generated, we don't have the information of the user that created the event since we're converting a BBCode `[event]` tag. The easiest solution is to indicate it is GMT time, otherwise changes will have to be much more extensive.

**Comment by tobiasd** [comment]
Yeah, I feared something alike ;-) but this is also the explanation for the used strings being in English and not the language of the account (which I think would be a reasonable thing).

**Comment by MrPetovan** [comment]
Translating the days/months in any language but English is possible in PHP but it requires the underlying system to have these translations installed in the OS. It would be yet another soft requirement to check on install.

**Comment by tobiasd** [comment]
Not the days & months, well those as well, but also the strings used by Friendica for the headers of "Starts:" and "Finishes:". For the RSS feed it is useless to have the datetime format string translate-able as the translations are not applied.

**Comment by MrPetovan** [comment]
The labels `Starts:` and `Finishes:` will also be translated according to the Friendica node system language.

**Comment by annando** [comment]
Should we convert the event entries in the feed to the user's timezone?
