### ISSUE TITLE
 don't see the events that were shared from the forum anymore

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10926]
I'm using the 2021.12-dev - 1438 and now I don't see the events that were shared from the forum anymore @annando 
![image](https://user-images.githubusercontent.com/12276250/137146650-0e943205-3b1a-4749-8b57-6ac661e5b0f4.png)

_Originally posted by @Tealk in https://github.com/friendica/friendica/issues/10837#issuecomment-942316193_

### Platform Info

Friendica Version:

Friendica Version: 2021.12-dev - 1442

Friendica Source: git

PHP version: 8.0.11

SQL version: mariadb 1:10.5.11

**Comment by annando** [comment]
What do you exactly mean with "events that were shared from the forum"? Are the events created on the forum account or via some other account?

**Comment by Tealk** [comment]
I create it on the forum account

**Comment by annando** [comment]
That worked here really fine, weird.

**Comment by Tealk** [comment]
Maybe this will help?

Calendar view of my profile:
![image](https://user-images.githubusercontent.com/12276250/152705492-415841ae-4468-4a2c-93ea-77a133d7a7ab.png)

Events on the forum page:
![image](https://user-images.githubusercontent.com/12276250/152705510-c10ee3ca-0cd1-4e62-8aa2-eae62da28e0b.png)

**Comment by annando** [comment]
I just checked. I can create an event on the forum page and this then is distributed to their users in my tests.

**Comment by Tealk** [comment]
Also to users who join the forum later?

**Comment by annando** [comment]
No. Currently this is technically not possible.

**Comment by Tealk** [comment]
This is a problem in my case because players leave the group and new ones join, then I would have to recreate the events again

**Comment by annando** [comment]
I do understand the problem. But I don't think that it is a bug but more a feature request.
