### ISSUE TITLE
Access to this profile has been restricted.

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10924]
`This is Friendica, version 2021.09 that is running at the web location https://social.trom.tf. The database version is 1434/1434, the post update version is 1427/1425.`

I get the above error plus:
Exception thrown in /var/www/friendica/mod/display.php:270
Stack trace:
```
#0 /var/www/friendica/src/LegacyModule.php(90): display_content(Object(Friendica\App))
#1 /var/www/friendica/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction('content', Array)
#2 [internal function]: Friendica\LegacyModule::content(Array)
#3 /var/www/friendica/src/App/Page.php(333): call_user_func(Array, Array)
#4 /var/www/friendica/src/App/Page.php(390): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#5 /var/www/friendica/src/App.php(708): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Util\Profiler), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#6 /var/www/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1635021365.3248)
#7 {main}
```

When I click form the notification area on a comment that was posted on a forum. Any idea why?

**Comment by nupplaphil** [comment]
@tio-trom can you please execute
```console
php ./bin/console.php postupdate
```

and show the output? Your post update version isn't correctly updated

**Comment by annando** [comment]
There is a setting one can set for their profile to reject direct access to the profile page. The setting causes this message. This is no bug.

**Comment by tio-trom** [comment]
@annando I am sure that profile didn't block mine. I am 100% sure of that. But I didn't see this error again so idk what was that....you can close this issue if you want, and I will get back to it if I see this again. Thanks for your input guys!
