### ISSUE TITLE
Database request error

### ISSUE THREAD

**Issue by BrokenGabe** [friendica/friendica#10935]
- [ X] I have searched open and closed issues for duplicates

### Bug Description
```
Code: 1055

Error: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'post-user-view.received' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Callstack: DBA::p, Profile::rawContent, call_user_func, Module::run, App::runFrontend

Params: SELECT `parent-uri-id` AS `uri-id`, MAX(`created`), MAX(`received`) FROM `post-user-view` WHERE `uid` = 2 AND NOT `contact-blocked` AND NOT `contact-pending` AND `visible` AND (NOT `deleted` OR `gravity` = 3) AND `wall` AND `unseen` GROUP BY `parent-uri-id` ORDER BY `received` DESC
```

### Steps to Reproduce

1.  Login
2.  Create Post
3.  Checked Logs in Admin

Expected Result:
No Errors?

### Platform Info

Friendica Version: Friendica 'Siberian Iris' 2021.12-dev - 1437

Friendica Source: Github Release

PHP version: 7.2.24

SQL version: mysql  Ver 14.14 Distrib 5.7.36, for Linux (x86_64) 
(mysqlnd 5.0.12-dev - 20150407 (according to phpinfo))

**Comment by MrPetovan** [comment]
Thank you for the report, MariaDB has been drifting away from MySQL so some SQL statements that work in MariaDB or older MySQL versions may not work anymore.

**Comment by AlfredSK** [comment]
I assume you're using MySQL. To make that error go away you need to remove `ONLY_FULL_GROUP_BY` from MySQL global setting `sql_mode`.

The default MySQL 5.7 setting for `sql_mode` is...

`ONLY_FULL_GROUP_BY STRICT_TRANS_TABLES NO_ZERO_IN_DATE NO_ZERO_DATE ERROR_FOR_DIVISION_BY_ZERO NO_AUTO_CREATE_USER NO_ENGINE_SUBSTITUTION`

Set it to...

`STRICT_TRANS_TABLES NO_ZERO_IN_DATE NO_ZERO_DATE ERROR_FOR_DIVISION_BY_ZERO NO_AUTO_CREATE_USER NO_ENGINE_SUBSTITUTION`

...in your `my.cnf` or whatever config file your distribution is using.

See https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode

**Comment by AlfredSK** [comment]
Wrong: mysql_mode
Right: sql_mode

Please read carefully. 😉 Also, I'm not a MySQL expert. I'm using MariaDB. Make sure the syntax of the config string is correct.

**Comment by BrokenGabe** [comment]
Okay, so i've made the changes to my my.cnf and restarted mysql, the error still continues after cleaning out the log file. So i'm not sure what's going on.

**Comment by AlfredSK** [comment]
You may check if the config had been applied successfully by running the following command from your SQL console...

`SELECT @@GLOBAL.sql_mode;`

With MariaDB it looks like this...

```
MariaDB [friendica]> SELECT @@GLOBAL.sql_mode;
+-------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                         |
+-------------------------------------------------------------------------------------------+
| STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

**Comment by BrokenGabe** [comment]
had to place in /etc/mysql/my.cnf
```
[mysqld]
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NOENGINE_SUBSTITUTION"
```

**Comment by HankG** [comment]
FYI apparently NO_AUTO_CREATE_USER doesn't exist in the latest MySQL so what worked for me in /etc/mysql/my.cnf (on Ubuntu 20) was:

```

[mysqld]
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

```
