### ISSUE TITLE
api_lists_statuses() - Unknown column 'group-id'

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#10945]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If you use the `api/lists/statuses` endpoint with corresponding `group_member` entries, the endpoint throws an error (at least in testmode :) ).

### Steps to Reproduce

1.  Adapt the `api.fixture.php` and add the following entries:
```php
	'group_member' => [
		[
			'id' => 1,
			'gid' => 1,
			'contact-id' => 47,
		],
		[
			'id' => 2,
			'gid' => 1,
			'contact-id' => 42,
		],
		[
			'id' => 3,
			'gid' => 2,
			'contact-id' => 43,
		],
	],
```
2.  Execute the Unit-Test `testApiListsStatusesWithListId()` or `testApiListsStatusesWithListIdAndRss()`

Actual Result:

```
Friendica\Database\DatabaseException : Unknown column 'group-id' in 'where clause'
 /vagrant/src/Database/Database.php:661
 /vagrant/src/Database/DBA.php:199
 /vagrant/src/Model/Post.php:414
 /vagrant/src/Model/Post.php:430
 /vagrant/include/api.php:3338
 /vagrant/tests/legacy/ApiTest.php:2620
```

Expected Result:

API result with `status` content.

### Platform Info

Friendica Version:

2021.12-dev

Friendica Source: 

GIT

PHP version:

- PHP 7.4.25
- PHP 8.0.11

SQL version:

mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by MrPetovan** [comment]
Do you need anyone's help or time to figure this bug out?

**Comment by nupplaphil** [comment]
It's caused by the `account-user-view`, where we don't join the `group_member` table, so there is no information about groups at all. But I'm totally unsure how to solve this issue, because of the 1:n dependency between contact and group_member

**Comment by nupplaphil** [comment]
Closing because corresponding functionality was already transformed to the new structure
Specific tests are now reenabled at #11084
