### ISSUE TITLE
SELECT * FROM permissionset

### ISSUE THREAD

**Issue by BrokenGabe** [friendica/friendica#10943]
- [X] I have searched open and closed issues for duplicates

### Bug Description
```
ERROR | worker | DB Error

Database.php | Line 668 | p

Code 1139

Error: Got error 'empty (sub)expression' from regexp

Callstack: Database::selectToArray, BaseDepository::_select, PermissionSet::select, PermissionSet::selectByContactId, ProfileField::selectByContactId, Transmitter::getProfile, Probe::localProbe, Probe::uri

Params: SELECT * FROM `permissionset` WHERE (`uid` = 2 AND (NOT (`deny_cid` REGEXP '' OR deny_gid REGEXP '<<>>') AND (allow_cid REGEXP '' OR allow_gid REGEXP '<<>>' OR (allow_cid = '' AND allow_gid = ''))))
```
### Steps to Reproduce

1.  make a post or comment
2.  wait for worker to process
3.  check logs

Actual Result:

The Above

Expected Result:

No Errors

### Platform Info

Friendica Version: Friendica 'Siberian Iris' 2021.12-dev - 1437

Friendica Source: 1adbdfb

PHP version: 7.2.24

SQL version: mysql Ver 14.14 Distrib 5.7.36, for Linux (x86_64)
(mysqlnd 5.0.12-dev - 20150407 (according to phpinfo))

**Comment by BrokenGabe** [comment]
Possibly Related
```
Warning: Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in /web/usr/34256/www/src/Object/Log/ParsedLogLine.php on line 122
```

I also noticed my server was not accessible after 24 hours, not sure if these things are related or not, i'll further check into it

**Comment by nupplaphil** [comment]
jfyi:

This error is related to the `mysql 5.7.36`.

I cannot reproduce it neither with `mysql 8.0.27` nor with `mariadb 10.6.4`.
