### ISSUE TITLE
OAuth token created using PHP's time, but checked using SQL's time

### ISSUE THREAD

**Issue by bkil** [friendica/friendica#10955]
If the two are on separate servers where NTP is not correctly set up, this could cause difficult to debug issues. It would be nicer to use the time of only one or the other server through the whole codebase. Maybe this had been done in other modules as well.

* https://github.com/friendica/friendica/blob/develop/src/Module/OAuth/Token.php#L79
* https://github.com/friendica/friendica/blob/develop/src/Security/OAuth.php#L179

During installation (or even daily?), it would be nice to detect this and give a warning.

All else equal and not giving much thought into it, I think choosing PHP's time throughout the codebase might be better .

**Comment by MrPetovan** [comment]
You're absolutely correct, thank you for your report!
