### ISSUE TITLE
[frio] Screen Reader Accessibility Part 1: Edit post formatting buttons

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10972]
@pvagner:
> In the message composer formatting buttons such as bold, underline and similar do have their icons augmented with either tooltips or aria-label property and that's communicated to screen reader users. That's awesome and I like it. However this is not working as intended when editing post. When editing posts aria-label properties on individual buttons are empty. Can this get fixed in future updates?

Source: https://github.com/friendica/friendica/issues/1743#issuecomment-961800209

**Comment by pvagner** [comment]
Thank you @annando  It's working fine now for me after pulling develop.
