### ISSUE TITLE
[frio] Screen Reader Accessibility Part 3: Post content and role="heading"

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10974]
@pvagner:
> When displaying comments you are using aria-level to signal the nesting level of a comment inside a conversation thread. That is unique screen reader user specific feature and I like it. However the whole post is contained inside a div element with role="heading" The content it-self might include a heading and include different heading inside existing heading is not very nice. Imagine you would cascade more anchor elements forming links... <a href="#first"><a href="#second"></a></a> It's technically possible but it does not have real value. I would suggest changing that role="heading" to role="article. Also articles of a social media platform are commonly included inside a feed. If it's suitable to friendica implementation then perhaps you might like to use role="feed" on the parent element and set other WAI ARIA related attributes on the individual articles if it would make sense from your point of view... Do you know pinafore a mastodon and also friendica frontend? It uses feed and article roles in a way I like as a screen reader user. It even has keyboard navigation.

Source: https://github.com/friendica/friendica/issues/1743#issuecomment-961800209

**Comment by MrPetovan** [comment]
After investigation, the `role="heading"` is applied to the actual heading of the post, only containing the author's information (picture, display name, link to profile) and the post information (date authored, date received, link to original post, protocol used). The whole post can be wrapped in a `role="article"` element but we won't be able to easily add a `role="feed"` or keyboard navigation at the moment.

**Comment by pvagner** [comment]
Hello,
Still if you can't predicate possible issues I'd like to get rid of the role=heading. As there are other nested headings heading level 4 and heading level 5 here in the bellow excerpt.
Other than aria related properties there are no other attributes set on the corresponding div so I image it won't be difficult.
Then the element with class h-entry should be possibly tweaked with aria-level or role=article and later on keyboard navigation might be considered.
I think we don't need to do all this at once. If possible I'd like to sort out confusing nested headings first.

```                                   <div role="heading" aria-level="1">
                     <div class="preferences">
                                                               <span class="wall-item-network"><i class="fa fa-friendica" title="friendica (via ActivityPub)" aria-hidden="true"></i></span>
                                                                                                  &nbsp;
                                   <a href="redir/21640?url=https://venera.social/display/85a863ed-1461-919a-9c4e-532426041560" class="plink u-url" aria-label="Link to source" title="Link to source">
                                          <i class="fa fa-external-link"></i>
                                   </a>
                                                 </div>
                                   <div class="contact-info hidden-sm hidden-xs media-body"><!-- <= For computer -->
                            <h4 class="media-heading">
                                   <a href="redir/21640" title="View Seph Harrison's profile @ https://venera.social/profile/taur10" class="wall-item-name-link userinfo hover-card">
                                          <span class="wall-item-name  sparkle">Seph Harrison</span>
                                   </a>
                                                                                    </h4>

                            <div class="additional-info text-muted">
                                   <div id="wall-item-ago-1032" class="wall-item-ago">
                                          <small>
                                                 <a href="display/85a863ed-1461-919a-9c4e-532426041560">
                                                        <span class="time" title="Mon, 15 Nov 2021 00:24:12 +0100" data-toggle="tooltip">
                                                               <time class="dt-published" datetime="Mon, 15 Nov 2021 00:24:12 +0100">12 hours ago (Received 11 hours ago)</time>
                                                        </span>
                                                 </a>
                                                                                                                                                          <span class="direction">
       •
                     <i class="fa fa-retweet" aria-hidden="true" title="Reshared by Friendica Support <https://forum.friendi.ca/profile/helpers>"></i>
       </span>
                                                                                                  
                                          </small>
                                   </div>

                                                               </div>
                                                 </div>

                                          <div class="contact-info-xs hidden-lg hidden-md"><!-- <= For smartphone (responsive) -->
                            <h5 class="media-heading">
                                   <a href="redir/21640" title="View Seph Harrison's profile @ https://venera.social/profile/taur10" class="wall-item-name-link userinfo hover-card"><span>Seph Harrison</span></a>
                                   <p class="text-muted">
                                          <small>
                                                 <a class="time" href="display/85a863ed-1461-919a-9c4e-532426041560"><span class="wall-item-ago">12 hours ago (Received 11 hours ago)</span></a>
                                                                                                                                                                                                           <span class="direction">
       •
                     <i class="fa fa-retweet" aria-hidden="true" title="Reshared by Friendica Support <https://forum.friendi.ca/profile/helpers>"></i>
       </span>
                                                                                           </small>
                                   </p>
                            </h5>
                     </div>
                             </div>```

**Comment by MrPetovan** [comment]
This is entirely possible, thank you for the follow-up!

**Comment by MrPetovan** [comment]
@pvagner Should I also remove the associated `aria-level` attribute where I remove the `role="heading"` attribute? The documentation about `aria-level` seems to indicate I should but I'd rather have first-hand information if you don't mind.

**Comment by pvagner** [comment]
@MrPetovan Excuse me for not replying earlier. I think removing the level attribute along with the heading would be a good idea here.
Level is either suitable for headings or for treeview items thus for our text node it would no longer be appropriate.
