### ISSUE TITLE
filebrowser / album navigation not working

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#10989]
- [x] I have searched open and closed issues for duplicates

### Bug Description

In the new post / compose overlay, in the file browser tab, the buttons for album navigation do not seem to work. Nothing happens when I click one of them.

### Steps to Reproduce

1.  start writing a new post in the composer overlay (I used firefox)
2.  switch to the browser tab
3.  try changing the album on the left side

Actual Result:

nothing happens

Expected Result:

should switch to the selected album

### Platform Info

friendica-version: 2021.12-dev
(https://libranet.de)
db-version: 1443/1443
post-update-version: 1427/1427

**Comment by AlfredSK** [comment]
Hmm. Works here. ;-) I tried it on a mobile device just now (Chrome/Brave web app).
Maybe the browser console can tell something about the issue. 
I can have a look later when I have a desktop available.

**Comment by haheute** [comment]
Yes, in chromium it works here (except that there are 2 slashes). But in firefox, not.

**Comment by MrPetovan** [comment]
Please clear your cache, a recent change has been made in the Javascript for these buttons.

**Comment by haheute** [comment]
yes, that helped.. thank you

**Comment by MrPetovan** [comment]
Friendica has an automatic Javascript/CSS cache busting feature that only applies to stable versions. If something doesn't work right on libranet.de that is on the `develop` branch, please clear your browser cache first.
