### ISSUE TITLE
language not applied for help page

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10983]
### Bug Description
Help section is ignoring language setting

### Steps to Reproduce
Set language to english.

Actual Result:
Help page shows in german

Expected Result:
Help page should follow language setting.

### Screenshots
<img width="643" alt="help in german" src="https://user-images.githubusercontent.com/5708172/141759316-208cebc7-5b16-4a89-9f8d-d78b59b0abb5.png">
<img width="618" alt="language settings" src="https://user-images.githubusercontent.com/5708172/141759320-cd7ecb5f-ecd4-4020-bad8-b2d9b04097db.png">

### Platform Info
This is Friendica, version 2021.12-dev that is running at the web location https://pirati.ca. The database version is 1443/1443, the post update version is 1427/1427.

**Comment by MrPetovan** [comment]
Help pages aren’t translated on Transifex, so we can’t easily hook them up with the user’s language. Help pages are only available in English and in German for most of them, so it would be a German-specific development which I feel weirdly uneasy about.

**Comment by foss-** [comment]
Thought something in that direction was going on. pirati.ca is mostly german users so this could slide under works as expected.
But then again it would make sense to show english as default and only switch to german if user language is specifically set to german.

**Comment by MrPetovan** [comment]
I'd rather have  something more generic if we start translating the help in more languages.

**Comment by foss-** [comment]
Maybe this was obvious already but behavior is not limited to pirati.ca - happens on squeet.me as well so seems to be a general problem.

**Comment by tobiasd** [comment]
Well, the idea _was_ to use the wiki for translations of the help files where it is really simple to have the texts translated. And while the idea was welcomed at the Hackathon 2020, the result was rather limited.

But apart from having only one translation at the moment, I think _if_ the help files are available in the users language, they should be displayed in that language.
