### ISSUE TITLE
Email on registration is complained as 'not an email'

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#10998]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The user registration fails on validating the email, when the email domain includes the characters '0x'.

### Steps to Reproduce

1.  Use an email like admin@0x56.de for registration.

Actual Result:

friendica complains that this is not an email address.

Expected Result:

The email is valid and should be accepted.

### Platform Info

Friendica Version:
2021.09 docker image

**Comment by MrPetovan** [comment]
Thank you for the report, I guess I have to check the valid email address regular expression.

**Comment by MrPetovan** [comment]
So, the email address syntax validity check is perfectly fine, but we optionally perform a `dns_get_record(DNS_A + DNS_MX)` call and a `dns_get_record(DNS_CNAME + DNS_MX)` call when the global `system.disable_email_validation` config value is false, and I assume either of those are failing.

Unfortunately, there's no way for us to know exactly what failed as the function doesn't have an error collection mechanism, so we can't distinguish a technical error in the function call from a data error if the MX record doesn't exist for example.

In this case, it seems both expected records exist but PHP fails retrieving them for an unspecified reason on your server. The only remediation is to disable email validation through the config value.

**Comment by nupplaphil** [comment]
@MrPetovan the `dns_get_record()` returns the correct DNS entry, maybe we accidentally transform "0x56.de" as hexadecimal value?
```php
[philipp@PHIL-X1-CARBON friendica]$ php -r "print_r(dns_get_record('0x56.de',  DNS_CNAME + DNS_MX));" 
Array
(
    [0] => Array
        (
            [host] => 0x56.de
            [class] => IN
            [ttl] => 6997
            [type] => MX
            [pri] => 10
            [target] => mail.0x56.de
        )

)
```
```php
[philipp@PHIL-X1-CARBON friendica]$ php -r "print_r(dns_get_record('0x56.de',  DNS_A + DNS_MX));" 
Array
(
    [0] => Array
        (
            [host] => 0x56.de
            [class] => IN
            [ttl] => 6959
            [type] => A
            [ip] => 46.38.243.234
        )

    [1] => Array
        (
            [host] => 0x56.de
            [class] => IN
            [ttl] => 6959
            [type] => MX
            [pri] => 10
            [target] => mail.0x56.de
        )

)
```

**Comment by MrPetovan** [comment]
If `dns_get_record` depends on the local DNS resolver then it is most likely a system-specific issue. Nowhere we are using the domain as a number which could trigger such a type casting.

**Comment by ne20002** [comment]
As the OP I did a retest. At the moment I can register with a name like that.

The issue poped up on the initial registration on a freshly set up instance. I managed to work around the issue by setting FRIENDICA_NO_VALIDATION = true. 
After registration everything works as expected. 

As I as the OP can't reproduce the problem I think this issue should be closed.

**Comment by MrPetovan** [comment]
Thank you for the follow-up!
