### ISSUE TITLE
Development is now broken

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10991]
Did a git pull at 12:53 (germany time) on development branch and now friendica is broken like follows (no interaction possible)

![00_temp](https://user-images.githubusercontent.com/24474762/142195931-c76d9dbc-5e72-4f5d-9504-4749d5be6495.jpg)

**Comment by nupplaphil** [comment]
any failures/errors/warnings in the log? I take a look, I'm sure it's because of my recent change #10977

**Comment by nupplaphil** [comment]
Accidentally deleted one really important row -> printing the content of the current module :D

@hoergen plz try again

**Comment by hoergen** [comment]
Works fine again. Thanks for the quick reaction. :sunflower:
