### ISSUE TITLE
post preview and post delete not working

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11001]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Since today morning, I can't delete posts or preview a new post. The answer is a server error 500.
I used firefox and also cleared the cache and logged out and in again. 

### Steps to Reproduce

Open the compose modal and write something. Click on preview.
(Or, try to delete a post from the timeline.)

Actual Result:

nothing happens, console shows a 500 error

Expected Result:

should display the post preview. (or, respectively delete the post.)

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2021.12-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1443/1443 und die Post-Update-Version 1427/1427."

**Comment by MrPetovan** [comment]
Please update develop again, this was likely caused by #10994, which has been reverted since.

**Comment by AlfredSK** [comment]
> Please update develop again, ...

Done.

**Comment by haheute** [comment]
thanks. works again, here.. :+1:
