### ISSUE TITLE
Question about the continuous integration checks

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11006]
@nupplaphil Can we separate the checks for the translation file, the formatting check and the unit tests in different runs instead of them being performed in order in the same "check" per GitHub? See this PR, it says "All checks have failed", but in reality, only the translation file check failed, so I'd like for this distinction to be visible from GitHub directly.

_Originally posted by @MrPetovan in https://github.com/friendica/friendica/issues/10969#issuecomment-974145700_

**Comment by nupplaphil** [comment]
I'm sorry, this isn't possible yet or at least I don't find any hint about it.
Unfortunately neither for github nor for gitea :-/

**Comment by MrPetovan** [comment]
Ok, thank you for the info!
