### ISSUE TITLE
contact management: with twitter connector in use, when unfollowing a contact on twitter, contact status is not updated / reflected on friendica

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11007]
### Describe the feature you'd like

When twitter connector is in use, it may make sense to poll for contact updates / changes. Some users use both platforms and may unfollow on friendica but sometimes also on twitter.

Currently: Once unfollowed on twitter the contact still shows as `I follow them` or `Mutual friendship`.

Expected: Contact change should be detected and contact
- no longer listed (if they are also not following me)
- listed as fan (they follow me, I am not following them)

**Comment by MrPetovan** [comment]
This can only be performed as part of the `twitter_sync` periodic task where we could theoretically check the connection status of all the Twitter contacts.

**Comment by foss-** [comment]
This is obsolete due to Twitter addon deprecation.
