### ISSUE TITLE
"array" in contact information

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11021]
### Bug Description

![grafik](https://user-images.githubusercontent.com/433490/142982781-35351cb7-3eba-4aea-a500-7b55a767ee66.png)

Instead of the real information "array" is shown in various places of the local contact profile view. Additionally one cannot change the groups a contact was placed into.

Situation is the same for new and old contacts, with all themes tested.

### Platform Info

Friendica Version: 2021.12-dev 4208535c16f0e8196effe230cc34141551a7be18

Friendica Source: git

PHP version: 7.4

**Comment by annando** [comment]
I just wanted to report the same :-) Also one of the text is missing on incoming contact requests when you can chose the relationship.

**Comment by nupplaphil** [comment]
Seems like the Module change caused it.. I'm on it .. I think I know what happend

**Comment by MrPetovan** [comment]
Possibly related Warnings and Notices:
- https://github.com/friendica/friendica/issues/10757#issuecomment-976235950
- https://github.com/friendica/friendica/issues/10757#issuecomment-976236351
- https://github.com/friendica/friendica/issues/10755#issuecomment-974624099

**Comment by tobiasd** [comment]
The second aspect of the issue is not solved

> Additionally one cannot change the groups a contact was placed into.

should I open a new issue for this or reopen this issue? I had hoped that they are caused by the same problem.

**Comment by MrPetovan** [comment]
It’s a different problem, please open a separate issue.
