### ISSUE TITLE
Contacts cannot be added to groups

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11029]
### Bug Description

As mentioned in #11021 currently I cannot add a contact to a contact group from the `/contact/ID` page. Instead a notification bubble pops up, that the contact was not found.

Adding them in the group management `/group` works.

### Platform Info

Friendica Version: 2021.12-dev dbcaf5192315d00f73c88d54e413c827fd31759b

Friendica Source: git

PHP version: 7.4

SQL version: mysql  Ver 15.1 Distrib 10.5.12-MariaDB

**Comment by tobiasd** [comment]
Reopening the issue as it does not work with Friendica as of Sunday morning (Nov 28th) c34994df0317eeb9fb5c5ae8e9ca65b9404126e2

**Comment by tobiasd** [comment]
In addition to the initial report, I've just noticed that existing contacts who were sorted into contact groups long time ago, are not included in any group on the `/contact/ID` page.

**Comment by AlfredSK** [comment]
Weird. When I try to add a new contact to one or more groups I get the message 'contact cannot be added to group' (or something like this. Also, those boxes ☑️ indicating the group membership remain empty.

BUT when I go to the group ID like https://libranet.de/group/71 I can see that the contact is displayed as member of that group.
