### ISSUE TITLE
Discrepancy between profile and /api/users/show output

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11020]
After updating profile info (description field) noticed that `https://friendica.instance/api/users/show.json?screen_name=username` is not updated.

Additional info: API draws its information from `apcontact` table, not `user` table. So while user table is updated but self contact information has not been updated.

**Comment by MrPetovan** [comment]
I'm not able to reproduce this issue on my test node on the latest RC, updating the description of my user profile is correctly propagated to the tables the API is polling from.

**Comment by foss-** [comment]
Could be working as expected in that branch, seeing the problem on squeet me:
This is Friendica, version 2021.12-dev that is running at the web location https://squeet.me. The database version is 1442/1442, the post update version is 1427/1427.

**Comment by annando** [comment]
Squeetme isn't updated for some time now. I'm still waiting for issue https://github.com/friendica/friendica/issues/10966 being resolved.

**Comment by annando** [comment]
AFAIK this problem is solved. There had been several changes in this release concerning avatar pictures.

**Comment by foss-** [comment]
Verified this on friendica. Since I am using 2FA had to generate an app-specific password to work around the limitation of the browser login request. With that then was able to access `https://friendica.instance/api/users/show.json?screen_name=username` with username + app-specific password.

Confirming that now the information is updated as expected 🎉
Note: custom fields are not shown in that view since twitter API does not support that. So if info is needed to be shown there, fallback to bio field is the workaround.
