### ISSUE TITLE
List of api endpoints for use with reverse proxy and filtering

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11027]
Hi
I wonder if there is a list of all api uri that are used by friendica. It would be handy to apply some filtering on a reverse proxy.

As an example: for Matrix I have set up a synapse server, where the reverse proxy filters as:
/_matrix allowed from everywhere
/_matrix/client and /_synape only allowed from internal network (all client are in a vpn internal zone)
any other access is instantly blocked.

This puts any illegal scanning of my server like for wp vulnarabilities and other on a blocklist on the first try. Can we have something similar for friendica?

**Comment by MrPetovan** [comment]
All the API endpoints are prefixed with `/api/`. For a complete list of URIs, I'll refer you to your node's Help page for Developer where you will be able to find all the API endpoints we support for each target platform (Twitter, Mastodon, GNU Social and Friendica specific)

**Comment by ne20002** [comment]
Hmmm... seems to be no so easy. Monitoring the URLs on the reverse proxy, I get a number of call starting with
/view
/photo
/images
/network
/contact
/update-network
/ping
/friendica
...

**Comment by annando** [comment]
I'm not sure if I understand exactly what you are searching for. We have got a lot of URL endpoints that are both used by the users of the system and external services on a "server to server" basis. Many `/api` are used by the users but some of them are also used for the server communication.

**Comment by ne20002** [comment]
What I try to do (not sure if it is possible) is to set up some filtering on the reverse proxy. The idea is
- to only allow valid url calls to be forwarded to the freindica server
- to find and filter all non friendica related urls (like bots scanning for wp vulnarabilities) and block them on the reverse proxy
- to identify unused/old versioned urls and not forward them to the friendica server
- filter all internal url like /admin to be allowed only from internal network.

So I can block (with fail2ban) all other requests like people scanning the internet for open servers, open WP or unpatched software .... This is for security and for reducing load on the friendica server behind the reverse proxy. 

For [Matrix] this is easy as all url begin with /_matrix, /_matrix/_client or /_synapse. But it seems as if this is not so easy for friendica server.

**Comment by MrPetovan** [comment]
You're correct, it won't be easy. Most the the URLs are described in the `static/routes.config.php`, and legacy URLs can also start with the basename of the PHP files in the `/mod` folder. For example, there's a `mod/cal.php` file so there's a `/cal` URL class.

**Comment by ne20002** [comment]
I'l close this as it is not feasable so far .. I chose to work the other way around and limit access to local networks for a few paths (admin/settings). But it seems this is all that can be done here.
