### ISSUE TITLE
Profile image cannot be changed

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11034]
### Bug Description

Changing the profile picture is not possible. The info bubble about the STRG+R reload to bypass the cache is shown, but the picture is not updated.

### Steps to Reproduce

You can either upload a pic directly or use one from your gallery. Both ways lead to the shown notification bubble, none updates your profile picture.

Actual Result:

The profile picture is not updated.

Expected Result:

The new profile picture should be used.

### Platform Info

Friendica Version: 2021.12-dev b03b1fe3671e06fde5e85081ed4186f3dd8fa2d6

**Comment by MrPetovan** [comment]
So, the profile picture is correctly updated, but the self-contact picture isn't. This issue seems related to #11020 where the profile is updated but the self contact isn't and some of the displays are outdated.

**Comment by annando** [comment]
I just tested on my system. I cannot reproduce it. Also there had been several changes in the photo functionality in this release, so I have got the feeling that this had been fixed.

**Comment by tobiasd** [comment]
Have you changed something within the last week on the code regarding this? Then I'll check again, else it's still a problem. I updated my profile pic a week ago (the t-shirt now shows the Friendica logo) but locally I still the the plain shirt.

**Comment by annando** [comment]
Can you post the image link that hasn't changed?

**Comment by tobiasd** [comment]
You mean https://social.diekershoff.de/photo/contact/300/f3ad7b1c115759259c16275554018953?ts=1643354245?rev=2022-01-20+16%3A31%3A36
