### ISSUE TITLE
Checkbox "Notification" is always empty

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#11033]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Can not see, if i follow a contact or not. Can not follow contact

### Steps to Reproduce

1.  Search for an account
2.  Go to profile->contact setting
3.  check "Notify me on new acitivites"
4. Klick "Send"
5. Open "Contact settings" again

Actual Result:

Checkbox is not checkt, when reopen contact-setting or even the whole page.
No new Notifications possible.

Expected Result:

When i check "Notify me" and Send the form, i would expect to see the checkbox checked on reload.
When checked, i want to receive notifications about new postings/activities from this contact

### Platform Info

Friendica Version: Friendica 'Siberian Iris' 2021.12-dev - 1445

Friendica Source: 

PHP version: 7.4

SQL version: mariadb10.3/Debian

**Comment by tobiasd** [comment]
@MrPetovan is this related to #11021 ?

**Comment by MrPetovan** [comment]
Most probably.

**Comment by nupplaphil** [comment]
@MrPetovan  - I fix it with #11005 as well, found it during debugging another issue :D

**Comment by xundeenergie** [comment]
the checkbox holds now.
but i don't know, if notifications also work again. 

will report on next successful (or not) notification.

thanks for the quick fix!
