### ISSUE TITLE
Can't follow diaspora users from diasp.org

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11047]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I just tried to follow 2 users from diasp.org (I'm on libranet.de) and it didn't work with both. 
( https://diasp.org/u/anane200 and https://diasp.org/u/santmat )

I saw this message:
> Die angegebene Profiladresse liefert unzureichende Informationen.
Es wurden keine kompatiblen Kommunikationsprotokolle oder Feeds gefunden.

    #: src/Model/Contact.php:2406
    msgid "The profile address specified does not provide adequate information."
    msgstr "Die angegebene Profiladresse liefert unzureichende Informationen."
    
    #: src/Model/Contact.php:2408
    msgid "No compatible communication protocols or feeds were discovered."
    msgstr "Es wurden keine kompatiblen Kommunikationsprotokolle oder Feeds gefunden."

### Steps to Reproduce

I clicked "follow" below the user avatar photo on this page ( https://libranet.de/contact/400301/conversations ), which produced the error message and led me to this site: https://libranet.de/follow?url=https%3A%2F%2Fdiasp.org%2Fu%2Fsantmat , where I clicked the "Anfrage abschicken" (submit) button . Then the messages appeared again in the top-right corner. (frio theme)

### Platform Info

> Diese Friendica-Instanz verwendet die Version 2021.12-rc, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1445/1445 und die Post-Update-Version 1427/1427.
Theme: Frio V.0.8.5

**Comment by MrPetovan** [comment]
Thank you for the detailed report!

**Comment by MrPetovan** [comment]
I'm confirming the inability to follow the following Diasp.org contact: `https://diasp.org/u/santmat`

**Comment by MrPetovan** [comment]
At first glance, no webfinger data can be obtained from `diasp.org` which prevents us from being able to identify the Diaspora contact.
```
2021-12-02T11:55:04Z index [DEBUG]: Request start. {"url":"https://diasp.org/.well-known/webfinger?resource=acct%3Asantmat%40diasp.org","method":"get"} - {"file":"HttpClient.php","line":70,"function":"request","uid":"941bc3","process_id":20822}
2021-12-02T11:55:04Z index [DEBUG]: http request config. {"url":"https://diasp.org/.well-known/webfinger?resource=acct%3Asantmat%40diasp.org","method":"get","options":{"headers":{"User-Agent":"Friendica 'Siberian Iris' 2021.12-rc-1445; https://dev-friendica.mrpetovan.com","Accept":["application/jrd+json"]},"timeout":20,"on_headers":{}}} - {"file":"HttpClient.php","line":145,"function":"request","uid":"941bc3","process_id":20822}
2021-12-02T11:55:09Z index [DEBUG]: construct {"url":"https://diasp.org/.well-known/webfinger?resource=acct%3Asantmat%40diasp.org","returncode":500,"result":""} - {"file":"CurlResult.php","line":135,"function":"__construct","uid":"941bc3","process_id":20822}
2021-12-02T11:55:09Z index [DEBUG]: debug {"info":{"http_code":500}} - {"file":"CurlResult.php","line":171,"function":"checkSuccess","uid":"941bc3","process_id":20822}
2021-12-02T11:55:09Z index [DEBUG]: Request stop. {"url":"https://diasp.org/.well-known/webfinger?resource=acct%3Asantmat%40diasp.org","method":"get"} - {"file":"HttpClient.php","line":160,"function":"request","uid":"941bc3","process_id":20822}
```
This technical endpoint returns a 500 error so it sounds a diasp.org problem.  I'll try to reach out to their admin.

**Comment by haheute** [comment]
Thanks. I tried following another user/pod, and got the same message as above. + another one:
 
    msgid "The network type couldn't be detected. Contact can't be added."
    msgstr "Der Netzwerktyp wurde nicht erkannt. Der Kontakt kann nicht hinzugefügt werden."

here the link:
    https://libranet.de/follow?url=https%3A%2F%2Fsysad.org%2Fu%2Ftomgrzyb

**Comment by MrPetovan** [comment]
Thank you for the added information, maybe we are doing webfinger wrong?

**Comment by MrPetovan** [comment]
For `https://sysad.org/u/tomgrzyb`, the WebFinger call succeeds so it isn't the same issue, I'll investigate further.

**Comment by MrPetovan** [comment]
Wait, we're calling `https://diasp.org/u/.well-known/host-meta` instead of `https://diasp.org/.well-known/host-meta` which expectedly fails.

No such issue with https://sysad.org/u/tomgrzyb where we correctly call `https://sysad.org/.well-known/webfinger`.

**Comment by MrPetovan** [comment]
More information about `diasp.org`. When probing an account, we're performing the following request:
```
GET HTTP/1.0 https://diasp.org/.well-known/webfinger?resource=acct%3Asantmat%40diasp.org
Accept: application/jrd+json
User-Agent: Friendica ‘Siberian Iris’ 2021.12-rc-1445; https://dev-friendica.mrpetovan.com
```
This request returns a 500 error, but it succeeds when I perform it from my desktop browser. My working hypothesis is that there's a user agent filter on `diasp.org` only allowing requests from known desktop browser user agent. I reached out to David Morley, the `diasp.org` admin, using my test account on another Diaspora pod since I can't add him as a contact on my Friendica nodes.

**Comment by MrPetovan** [comment]
Further tests have shown that the presence of the `User-Agent` header field with this value is triggering the errors.

**Comment by MrPetovan** [comment]
David Morley of diasp.org indicated that his server only accept TLS version 1.3 which could explain why some connections from Friendica nodes (among others, I suspect) are dropped without showing in the web server log.

**Comment by AlfredSK** [comment]
Hmm...

**diasp.org**

![image](https://user-images.githubusercontent.com/3656054/144455398-a94c6fc5-2457-4493-94c6-d792cdc1507e.png)

**libranet.de**

![image](https://user-images.githubusercontent.com/3656054/144455561-b337da18-5be4-43f7-a78e-c6d57dcc0823.png)

**Comment by MrPetovan** [comment]
In the process of troubleshooting this issue, David Morley has relaxed the TLS requirements of the server, to no avail on my end, it still fails to connect.

**Comment by MrPetovan** [comment]
Post-mortem: https://diasp.org/posts/735a2029-4961-a833-9fc2-e8e646274798#620a09b035e9013a2c8628a1592b385a

Confirmed working again.
