### ISSUE TITLE
Blocked contacts disappeared from the list

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11040]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

The list of blocked contacts .../contact/blocked has lost a lot of entries. I'm pretty sure there were more than 150 users/contacts on my personal block list. The list is showing only 20 all of a sudden.
Maybe the same is true for ignored contacts .../contact/ignored. That list is showing only 16 ignored contacts. But I'm not sure how many there were before.

Actual Result:

A lot of blocked contacts are missing on the list of blocked contacts.

Expected Result:

Show all blocked contacts on my .../contact/blocked page.

### Screenshot

![grafik](https://user-images.githubusercontent.com/3656054/143766425-4960723c-6bc6-45d4-af2c-9758454c6687.png)

### Query

Hmm. The DB query is also showing only 20 blocked contacts.

```
MariaDB [friendica]> select id, uid, blocked from contact where uid = 2 and blocked = 1;
+---------+-----+---------+
| id      | uid | blocked |
+---------+-----+---------+
|      59 |   2 |       1 |
|     441 |   2 |       1 |
|     621 |   2 |       1 |
|     838 |   2 |       1 |
|    1982 |   2 |       1 |
|    2369 |   2 |       1 |
|   14629 |   2 |       1 |
|   21743 |   2 |       1 |
|   61239 |   2 |       1 |
|  118404 |   2 |       1 |
|  121523 |   2 |       1 |
|  302682 |   2 |       1 |
|  314045 |   2 |       1 |
|  330012 |   2 |       1 |
|  408164 |   2 |       1 |
|  531515 |   2 |       1 |
|  636463 |   2 |       1 |
| 1079665 |   2 |       1 |
| 1299190 |   2 |       1 |
| 1764154 |   2 |       1 |
+---------+-----+---------+
20 rows in set (0.000 sec)
```

### Platform Info

Friendica Version:

2021.12-dev

Friendica Source: 

git

PHP version:

7.4

SQL version:

10.3 MariaDB

**Comment by MrPetovan** [comment]
Is it possible these accounts were cleaned up as unreachable by the node?

**Comment by AlfredSK** [comment]
Hmm. Originally, a user of my node reported that he discovered posts in his timeline from blocked contacts. Then he checked his list of blocked contacts and found a lot of entries missing. Today he added that he cannot block those users again. He can select 'block', he doesn't get any error message, but the blocked user doesn't appear on the list of blocked users.

German thread: https://forum.friendi.ca/display/0b6b25a8-9461-a24b-1ab7-128619943278

**Comment by MrPetovan** [comment]
I’m wondering why not all contacts were not blocked anymore. 🤔

**Comment by AlfredSK** [comment]
Me too. :-)

**Comment by MrPetovan** [comment]
> ### Query
> Hmm. The DB query is also showing only 20 blocked contacts.
> 
> ```
> MariaDB [friendica]> select id, uid, blocked from contact where uid = 2 and blocked = 1;
> +---------+-----+---------+
> | id      | uid | blocked |
> +---------+-----+---------+
> |      59 |   2 |       1 |
> ...
> | 1764154 |   2 |       1 |
> +---------+-----+---------+
> 20 rows in set (0.000 sec)
> ```

What about ``SELECT `cid`, `blocked` FROM `user-contact` WHERE `uid` = 2 and `blocked` = 1`` ?

**Comment by AlfredSK** [comment]
Will check that query later.

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> SELECT `cid`, `blocked` FROM `user-contact` WHERE `uid` = 2 and `blocked` = 1;
+---------+---------+
| cid     | blocked |
+---------+---------+
|     188 |       1 |
|     356 |       1 |
|     390 |       1 |
|     839 |       1 |
|     863 |       1 |
|    2374 |       1 |
|    2394 |       1 |
|    5798 |       1 |
|   72922 |       1 |
|  121609 |       1 |
|  320051 |       1 |
|  320056 |       1 |
|  320057 |       1 |
|  350222 |       1 |
|  381299 |       1 |
|  408008 |       1 |
|  449517 |       1 |
|  585702 |       1 |
| 1076240 |       1 |
| 1754100 |       1 |
+---------+---------+
20 rows in set (0.001 sec)
```

**Comment by MrPetovan** [comment]
Thanks, at least it looks consistent, which probably rules out any data loss shenanigans.

**Comment by AlfredSK** [comment]
Could it be that contacts that are blocked on node level don't appear on the personal block list anymore?

**Comment by MrPetovan** [comment]
I don't think they've ever appeared in this list, they aren't meant to, and if this was your expectation, I understand you would "miss" them.

**Comment by AlfredSK** [comment]
Well there were contacts I had blocked personally and later I blocked them node-wide, too. :-) Yes, my expectation might be wrong.

But there is still the original report from my user that there are contacts that are not blocked anymore and they cannot be blocked again.
> Then he checked his list of blocked contacts and found a lot of entries missing. Today he added that he cannot block those users again. He can select 'block', he doesn't get any error message, but the blocked user doesn't appear on the list of blocked users.

**Comment by MrPetovan** [comment]
Got it, I fixed the inability to block contacts in #11046 so even if you were confused about who you should see in your blocked list, the report was useful to troubleshoot blocking contacts. Can we close this issue?

**Comment by AlfredSK** [comment]
I'll ask the user if things are working as expected now.

**Comment by AlfredSK** [comment]
The user confirms that blocking contacts is working again. But he is still sure that he had at least 45-50 blocked contacts and he has only 15 left on his blocklist now.

**Comment by MrPetovan** [comment]
Thanks for following up. Unfortunately, unless you have a semi-recent DB backup, there's no way of knowing which contact used to be blocked but isn't anymore from the current state of your database.

**Comment by annando** [comment]
Blocked contacts could disappear because they closed their accounts. We have to see if a situation occurs when contacts are magically unblocked over time. Except from that I wouldn't consider this with a high priority.

**Comment by AlfredSK** [comment]
Yep. That's possible. I had a lot of usual suspects on my block list. Maybe these accounts were deleted later. But the user of my node who discovered the issue told me he is seeing content of once blocked contacts again.

**Comment by annando** [comment]
Has anyone else experienced this issue? Or did it happened again on the system?

**Comment by AlfredSK** [comment]
I need to check it.

**Comment by AlfredSK** [comment]
Well. My list of blocked contacts is still pretty short. But there were no other reports for this issue. So, I think we should close it.
