### ISSUE TITLE
Unable to follow a Diaspora account from sysad.org

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11055]
_Originally posted by @haheute in https://github.com/friendica/friendica/issues/11047#issuecomment-984415200_
> Thanks. I tried following another user/pod, and got the same message as above. + another one:
> 
> ```
> msgid "The network type couldn't be detected. Contact can't be added."
> msgstr "Der Netzwerktyp wurde nicht erkannt. Der Kontakt kann nicht hinzugefügt werden."
> ```
> 
> here the link: https://libranet.de/follow?url=https%3A%2F%2Fsysad.org%2Fu%2Ftomgrzyb

**Comment by MrPetovan** [comment]
I found the larger issue for this particular problem: I've wrongly simplified a probe URI condition when I removed the Twitter probe from the core detection and this caused regular profile URLs to fail probe, but `user@domain.tld` still works.

**Comment by AlfredSK** [comment]
Checked it and got these error messages.

![Screenshot_20211202-132733__01](https://user-images.githubusercontent.com/3656054/144422254-21daa3e2-f649-4471-85c8-0eeb40424547.jpg)

**Comment by MrPetovan** [comment]
But it works with `tomgrzyb@sysad.org`, right?

**Comment by tobiasd** [comment]
yes, `tomgrzyb@sysad.org` works in the probe.

**Comment by MrPetovan** [comment]
Thanks, then the PR is complete and will fix the issue with the profile URLs.
