### ISSUE TITLE
Upload via /api/v1/media returns HTTP error 403

### ISSUE THREAD

**Issue by annando** [friendica/friendica#11063]
With the current RC it is impossible to upload pictures via the Mastodon API. The API always returns 403 when trying to upload.

This also happens when creating a new post, so most likely the `POST` command will fail all the time with the API, I guess.

**Comment by MrPetovan** [comment]
THE PUT command has a bug, but the POST command doesn't, in any case the Friendica log should show you the reason why the upload failed.
