### ISSUE TITLE
[Question] Redirect url in Guzzle Responses

### ISSUE THREAD

**Issue by greengekota** [friendica/friendica#11078]
Here

https://github.com/friendica/friendica/blob/131606e07e11c541ac6c627e727697beee53783b/src/Model/GServer.php#L345-L354

it seems you are looking for a redirect by checking if the original url is different from the redirect one, but in the Guzzle Response you define it as

https://github.com/friendica/friendica/blob/8d5c03755d8b9d73d8c30517b1ee9c3cd330c158/src/Network/HTTPClient/Response/GuzzleResponse.php#L120-L123

where the url is 

https://github.com/friendica/friendica/blob/8d5c03755d8b9d73d8c30517b1ee9c3cd330c158/src/Network/HTTPClient/Response/GuzzleResponse.php#L51-L54

passed by `HttpClient::request` in

https://github.com/friendica/friendica/blob/8d5c03755d8b9d73d8c30517b1ee9c3cd330c158/src/Network/HTTPClient/Client/HttpClient.php#L147-L148

so isn't this passing the original url?

Since you are following and tracking redirects in Guzzle, I think `getRedirectUrl` should check the `X-Guzzle-Redirect-History` header (more or less how it's suggested [here](https://github.com/guzzle/guzzle/issues/2059#issuecomment-501224256)), taking care of the fact that as the documentation states
> Note: When tracking redirects the `X-Guzzle-Redirect-History` header will exclude the initial request's URI

**Comment by MrPetovan** [comment]
Thank you for the report, @nupplaphil set this up so he would be more able to answer your question.

**Comment by nupplaphil** [comment]
thanks, it's a bug .. There's the "legacy" way for creating the response with 
https://github.com/friendica/friendica/blob/e2ff48375fdc75fc3509233c55f41f20fd863308/src/Network/HTTPClient/Response/CurlResult.php#L139
and
https://github.com/friendica/friendica/blob/e2ff48375fdc75fc3509233c55f41f20fd863308/src/Network/HTTPClient/Response/CurlResult.php#L215-L217
So
https://github.com/friendica/friendica/blob/e2ff48375fdc75fc3509233c55f41f20fd863308/src/Network/HTTPClient/Response/CurlResult.php#L315-L318
returns the right redirect.

With Guzzle, we do have to check the redirect differently, I'll fix it

**Comment by greengekota** [comment]
Hi @nupplaphil 

If I understand correctly, after the fix the default value of `redirectUrl` is the empty string (unless it is an actual redirect).

In the legacy version instead it's the original url, at least according to this test:

https://github.com/friendica/friendica/blob/8d5c03755d8b9d73d8c30517b1ee9c3cd330c158/tests/src/Network/HTTPClient/Response/CurlResultTest.php#L60-L73

and I think it's being set here:

https://github.com/friendica/friendica/blob/c34994df0317eeb9fb5c5ae8e9ca65b9404126e2/src/Network/HTTPClient/Response/CurlResult.php#L181-L187

The default value of `redirectUrl` shouldn't really matter, but in

https://github.com/friendica/friendica/blob/131606e07e11c541ac6c627e727697beee53783b/src/Model/GServer.php#L352

the default value is being used to test if it's a redirect. Which is the perfect reason to remove all those ad-hoc tests and replace them with `isRedirectUrl()`. A [quick search](https://github.com/friendica/friendica/search?q=getRedirectUrl) shows that `getRedirectUrl` is not being used in too many places.

Edit:
Thinking again, it is not entirely equivalent, if someone does something silly like redirecting `example.com` to `example.com`, ie. a loop, which in the current implementation I think should stop with some failure because Guzzle follows up to some number of redirects.
