### ISSUE TITLE
What to do about missing .well-known directory/rewrite?

### ISSUE THREAD

**Issue by Andy3142** [friendica/friendica#11071]
I've just installed Friendica and right from the start I get the error 

"https://oshotestnet.co.uk/.well-known/host-meta is not reachable on your system. This is a severe configuration issue that prevents server to server communication. See the installation page for help."

I've no idea what to do about this! The installation page talks about the problem being "another directory" called .well-known. This suggests the problem is with a physical directory with this name. But there is no physical directory called .well-known anywhere in the brand-new installation. I've read general Linux instructions how to set up one up, and there seem to be related Friendica source files to do this, but I can find no specific instructions for Friendica how to create this directory.

If it is purely a rewrite matter, well, there's nothing obvious in .htaccess about it.
[copyhtaccess.txt](https://github.com/friendica/friendica/files/7655682/copyhtaccess.txt)

Should I make a directory and if so how? Is the .htaccess wrong?

Many thanks

Andy 
Bristol, UK

**Comment by AlfredSK** [comment]
Do the other pages/paths work as expected? If so is the cronjob/daemon running successfully? I had this message from time to time in my admin panel but as soon as the cronjob ran successfully the message disappeared and the well-known/host-meta path was working again.

**Comment by Andy3142** [comment]
The other pages work OK. The cron job is another outstanding question. The server is executing the job, and a new log file appears every 5 minutes.  But the worker.php file I used is /bin/worker.php and I'm not sure this is right. Also, the log file has zero size and I'm also not sure if this is normal though the worker.php file isn't obviously writing to any log file. Would it be worth my changing over to the daemon and seeing what happens?

**Comment by AlfredSK** [comment]
How does your cronjob looks like? And does it run with correct user permissions?
I don't understand the part with 'new log file appears every 5 minutes'. Usually, the worker is logging into the configured Friendica log file.

Also, you can run the worker manually from Friendica web root directory to get an instant output or error message. You need to do this with the correct user (sudo).

**Comment by Andy3142** [comment]
The cronjob was set up via a gui in the Hostinger host admin, so it should be OK:
*/5 * * * *       /usr/bin/php /home/u772168667/public_html/bin/worker.php

I hadn't realised I had to set up the log myself, but when I do the worker reports:
```
Date 			Level 	Context 	Message
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/2/0 (0:2) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/2/0 (0:2) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/4/0 (0:4) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/3/0 (0:3) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/3/1 (0:2, 40:1) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/3/1 (0:2, 40:1) - maximum: 1/10
2021-12-05T12:30:02Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:02Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/2/2 (0:1, 40:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Active worker limit reached, quitting.
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/2/6 (0:2) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	end
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/6 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/5 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/4 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/3 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/2 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/1 (0:0, 30:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	start
2021-12-05T12:30:01Z 	NOTICE 	worker 	Spool file does does not start with "item-"
2021-12-05T12:30:01Z 	NOTICE 	worker 	Spool file does does not start with "item-"
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/2 (0:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/1 (0:1) - maximum: 1/10
2021-12-05T12:30:01Z 	NOTICE 	worker 	Load: 15.25/20 - processes: 0/1/0 (0:1) - maximum: 1/10
```
I've no idea if this is correct, but no actual errors.  
The docs don't give a definite directory for the worker.php file, but they do have a definite directory for the daemon.php alternative, and that's the same directory, /bin , and the insides of the two files are approximately similar. So I think I possibly do have the right worker, and it has nothing to do because the node is inactive.

So my best guess is that the .well-known error may not be to do with the cron/worker.

**Comment by AlfredSK** [comment]
Thing is, the host-meta path is no static file or directory. It is created by PHP. From my experience the message in admin panel and the issue with that path (host-meta) disappears as soon as the worker was running successful. That's why I was curious about your cronjob and possible errors. But the logged line you provided are looking ok to me. So, I'm clueless...

**Comment by tobiasd** [comment]
Are you using Apache2 or Nginx as webserver?

**Comment by Andy3142** [comment]
The server is LiteSpeed.

**Comment by tobiasd** [comment]
Never heard about it before, but they claim to be compatible with Apache2.

**Comment by Andy3142** [comment]
The src directory contains these files, which look as if they might be a toolkit to construct a .well-known directory - are they, I wonder?

/oshotestnet.co.uk/public_html/src/Module/WellKnown/HostMeta.php
/oshotestnet.co.uk/public_html/src/Module/WellKnown/NodeInfo.php
/oshotestnet.co.uk/public_html/src/Module/WellKnown/SecurityTxt.php
/oshotestnet.co.uk/public_html/src/Module/WellKnown/XSocialRelay.php

**Comment by tobiasd** [comment]
The content of the `.well-known` directory is created automatically to match your nodes information, depending on the configuration you choose in the admin panel and for which accounts other nodes of the Fediverse are looking. All this information is distributed over the WellKnown module.

After thinking a bit about the problem it might be that the `.well-known` is also defined by/for LetsEncrypt (they are using it as well but a different sub-directory `acme-challenge`) and this config has a higher priority then Friendica has, hence the server "does not find" the routes Friendica is defining (as the LE config does not know about them).

**Comment by Andy3142** [comment]
But why this particular installation? The host company claim very definitely that the server is Apache 2 compatible. Maybe what I'll do is delete the whole thing and re-install. I understand everything a bit better now and at least I'll be more alert to things going a bit funny. 
Would it be worth going back to the previous release? - I've got Version 2021.09. I've been assuming it's a setup hiccup, but might it be a real issue?

**Comment by tobiasd** [comment]
The server can be Apache2 compatible, but still the configuration for the rewrite rules and directory aliases used in the configuration for LetsEncrypt certificates might be such, that the Friendica rewrite mechanism for generating the contents of `.well-known/host-meta` does not work.

**Comment by Andy3142** [comment]
Thank you, now I have an exact situation to put to them, I'll ask the hosts (Hostinger) and report back.

**Comment by Andy3142** [comment]
My hosts, Hostinger, say:
"It seems to me that this would require root access - in this case, we have VPS server selection. .well-known folder is basically hidden, since our Shared/Cloud plans are managed directly by our Admins. At this time really using shared hosting you will not be able to access folder oshotestnet.co.uk/.well-known. If you would need to actively use a folder like that for your app I would recommend a private server to host your project."

OK ... what to do ...  I'd be interested to learn how to do a VPS installation,  but it's not worth the effort at this point. I just need to get a quick test install up and running.

(1) Can I do anything myself, or ask Hostinger for a clear simple thing they could do, to easily get around what they say?

(3) The installation requirements don't say anything about root access. That does imply that I don't need a VPS and can find an Apache host where it will run without needing root access. At this early stage, it may be simplest to just change host.
Is there an up to date list of good (English speaking) European hosts that are known to work? On the wiki there's a list of VPS providers but it's very old and I can't see Apache hosts at all. 

Maybe I should open another support request asking for Apache host recommendations?

**Comment by Andy3142** [comment]
An afterthought:  does "Unix shell access" in the requirements actually imply "root access"?

**Comment by MrPetovan** [comment]
It shouldn't, although we can't really account for these opinionated setups on shared hosts.

**Comment by tobiasd** [comment]
No, root access is not implied. For my knowledge this is the 1st case where the `.well-known` path is completely blocked by the hoster. IIRC uberspace.de was used successfully in the past, for a testing/small instance this might be a shared hoster possibility. For VPS any should work (Friendica is working on a Raspberry Pi 4, more RAM is better as the database has to fit into RAM - for a guide to the hardware specs)

**Comment by Andy3142** [comment]
OK, to close things off, this in the end proves to be a host problem specific to Hostinger. Big thanks you all of you who replied to this. 

I asked Hostinger support if there was any workaround to make .well-known available, and they said No. Specifically they said:

" I went ahead and contacted our Tech Engineer and he explained to me that .well-known folder is mainly reserved for system configurations. So internal information, SSL challenges, etc.) Litespeed is a drop-in replacement of Apache though we redirect that folder to ourselves. ﻿ ﻿If access to .well-known folder is a must, Friendica won't work on our shared environment. We also use MariaDB 10.5 which is likely to cause this issue HERE: ﻿ ﻿"Unable to create all mysql tables on MySQL 5.7.17 or newer If the setup fails to create all the database tables and/or manual creation from the command line fails, with this error: ERROR 1067 (42000) at line XX: Invalid default value for 'created' You need to adjust your my.cnf and add the following setting under the [mysqld] section: sql_mode = ''; After that, restart mysql and try again." ﻿ ﻿Overall it seems that this app is pretty custom and would require full control of the server and thus VPS services for it would be highly recommended. "

So I'm going to have a look at uberspace.de and probably have a go with them, and if not, it's a message from galactic HQ that I need to learn to set up a VPS.

Once again, a big thank you for all your help.

**Comment by MrPetovan** [comment]
You're welcome, and this confirms we can't officially support shared host install.
