### ISSUE TITLE
Smiley button does not exist

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11108]
Although I have activated all smiley addons
![2021-12-18 08 03 56](https://user-images.githubusercontent.com/12480023/146632988-afa7b04c-0d24-4997-919e-b608977c545f.png)
I can't find a button when creating a post.
![2021-12-18 08 04 21](https://user-images.githubusercontent.com/12480023/146633014-27676a69-21c5-450d-b39d-346cb87133ce.png)

**Comment by Quix0r** [comment]
EDIT: Already existing, just start typing!

Can we have a drop-down menu similar to here on github, where you start with a `:` and get a drop-down menu and the further you type, the narrower results you get? It can be even without any AJAX.

Idea: https://social.trom.tf/display/dbc8dc44-1262-bda0-3d0e-d8f795861863

**Comment by Quix0r** [comment]
At least in the `/compose` view I can find it. But it sits very far away from the input box. Here with latest `develop` code, I have a smiley in your mentioned "popup" (it is a modal). And in the template `view/templates/item/compose.tpl` there is no variable next to the tools near the input box.

Edit: In `/compose` the opening div with all the smilies breaks the sign. It overlaps a lot.

**Comment by Ravenbird** [comment]
Is there anything new here? A smiley or emoticon button would be really great. On the smartphone and tablet I have it all integrated in the keyboard, but on the desktop it's really annoying a smilie apart from :-) :-( or ;-) or even to get to it at all.

**Comment by foss-** [comment]
This is resolved, no?

![1](https://github.com/friendica/friendica/assets/5708172/752ac747-668c-469f-988f-4ca615bc3274)
