### ISSUE TITLE
Reshares end up on Twitter

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#11104]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When a Diaspora post is reshared this will also send out a tweet. 

### Steps to Reproduce

1.  Enable/setup Twitter addon for your account
2.  Set that new posts go to Twitter by default
3.  Reshare a Diaspora post
4. See new cryptic Tweet on Twitter

Actual Result:
Reshare goes to Twitter. 

Expected Result:
Reshare should not produce a new Tweet but should only be shared in the Fediverse. 

### Platform Info

Friendica Version: 2021.12-RC

Friendica Source: Git

PHP version: 7.4.25 

SQL version: 10.6.4-MariaDB

**Comment by MrPetovan** [comment]
This is because Diaspora has no native reshares, it always creates a new post, which is mirrored on Twitter unlike the ActivityPub native reshares. Can you please confirm whether these reshares are distributed to your Mastodon followers or not?

**Comment by utzer** [comment]
> This is because Diaspora has no native reshares, it always creates a new post, which is mirrored on Twitter unlike the ActivityPub native reshares.

I know this, it was like that in the previous version of Friendica as well, but there the reshares did not go to Twitter I think. 

> Can you please confirm whether these reshares are distributed to your Mastodon followers or not?

Yes, the Diaspora reshares are sent to Mastodon, I checked on my Mastodon account... that I just created to sometimes be able to see how my posts look over there.

**Comment by MrPetovan** [comment]
Ok, so it's the same issue, since we're creating a new reshare post as per Diaspora protocol, we have no way of knowing it was originally a Diaspora post that was reshared. So we distribute it to all the contacts, Mastodon and Twitter included.

How cryptic is the display on Twitter?

**Comment by utzer** [comment]
> Ok, so it's the same issue, since we're creating a new reshare post as per Diaspora protocol, we have no way of knowing it was originally a Diaspora post that was reshared. So we distribute it to all the contacts, Mastodon and Twitter included.

I am almost sure this is new, it was like that before, but was fixed I think. Maybe need to scroll through my Tweets to confirm. 

> How cryptic is the display on Twitter?

[This](https://twitter.com/utzer/status/1470843658253791232) much.
