### ISSUE TITLE
Admin Panel: Statistics broken

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11109]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The statistics page in the admin panel is broken. My node says at the moment

> Currently this node is aware of 2 nodes with 4 registered users

with the `gserver` table containing some 13k lines. @annando [confirms](https://pirati.ca/display/ec054ce7-1261-bda2-b73b-fa0058939284) the brokenness.

### Platform Info

Friendica Version: 2021.12-rc 96a3991dfd83c3a5f35f6802d31444ab77469de7

**Comment by annando** [comment]
The problem lies within the detection of a redirect. This means that the fix won't fix the problem immediately, but it needs the server detection to catch up. I'm not sure if this could take days or weeks.
