### ISSUE TITLE
Migrate Drone to Woodpecker

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#11111]
Some of us have already recognized this little nice alert:
![grafik](https://user-images.githubusercontent.com/379654/146643968-5ddc91f0-f7df-4b26-8966-d797b1070e51.png)

Drone distinguishes now between community and enterprise. You can read details here: https://docs.drone.io/enterprise/#what-is-the-difference-between-open-source-and-enterprise .

Additionally, there's no official Docker image for free anymore, just for enterprise, so we do have to build & maintain it by our own now .. This step shows me that they don't "really" want open source anymore, because they explicit exclude the docker image build at their deployment process ..

The new version 2 of drone has a different syntax as well, which means we do need to migrate either using Drone or using Woodpecker, so we should start with Woodpecker as @annando already mentioned during a Drone PR.

So this will become the new way: https://woodpecker-ci.org/
It's a fork of the last OSS licensed Drone version with a new community

**Comment by annando** [comment]
What have I mentioned?

**Comment by nupplaphil** [comment]
I don't know where, but you posted a link in one of the PRs that Drone changed its license and there's a fork of it :D .. This was my starting point

**Comment by MrPetovan** [comment]
Why can't we have nice things?
