### ISSUE TITLE
DBStructure drop ordering

### ISSUE THREAD

**Issue by zeroadam** [friendica/friendica#11120]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

When upgrading from one or two previous versions (perhaps a jump of one or two versions, i.e. 2021.2-dev to 2021.12-dev) I received an error when running the dbstructure update script. It was indicating some FK violations. After seeking help in the support forum @annando provided assistance and noticed I had several tables that were no longer in use and advised the dbstructure drop command.

The drop executed but then encountered FK issues within the tables to be dropped, and after some back and forth, we were successful, and I was then able to run the update script without error, but seems the order of dropped tables is off. This issue is at the request of @annando to report my findings to achieve success.

Sorry if this is lengthy because of the table list, but wanting to provide as much detail to be helpful.

### My Findings

My initial list as given by dbscructure drop was:
```
auth_codes
ffinder
item-activity
participation
item-content
poll_result
term
profile_check
fserver
poll
clients
dsprphotoq
gcontact
item-delivery-data
challenge
item
gcign
thread
gfollower
host
deliverq
tokens
item_id
queue
sign
glink
spam
user-item
```
Running with the "-e" parameter successfully dropped the first few tables, but then encountered an error with the **clients** table. Upon instruction I began to manually drop tables, during which I determined it was the **tokens** table that was the culprit with regard to the **clients** table.

I then ran the drop script again, and it continued until it got to the **item** table. Similar to the **clients** table, but I had to manually drop all the remaining tables before **item** could be dropped. That list is:
```
gcign
thread
gfollower
host
deliverq
tokens
item_id
queue
sign
glink
spam
user-item
```

It seems that if the **tokens** table is dropped before the **clients** table, and then the **item** is dropped last, it may be solved.

Actual Result:
Two tables in the list of "eligible" tables to be removed caused FK errors.

Expected Result:

Successful run of dbstructure drop -e without FK errors.
### Links
Here is a link to the thread for any context.
[https://social.digitalcastle.me/display/6a6e6e0e-7761-c222-93be-49a838743359](url)

### Platform Info

Friendica Version:
2021.12-dev

Friendica Source: 
github dev branch

PHP version:
8.0.13

SQL version:
MariaDB 10.6.5

**Comment by Quix0r** [comment]
I can confirm wrong drop order with the `./bin/console dbstructure drop -e` console command:
````
vuXXXX@zulu289:~/friendica/htdocs$ ./bin/console dbstructure drop -e
DROP TABLE `auth_codes`;
DROP TABLE `challenge`;
DROP TABLE `clients`;

Error 0 occurred during database update:

DROP TABLE `deliverq`;
DROP TABLE `dsprphotoq`;
DROP TABLE `ffinder`;
DROP TABLE `fserver`;
DROP TABLE `gcign`;
DROP TABLE `gcontact`;
DROP TABLE `gfollower`;
DROP TABLE `glink`;
DROP TABLE `host`;
DROP TABLE `item`;

Error 1451 occurred during database update:
Cannot delete or update a parent row: a foreign key constraint fails
DROP TABLE `item-activity`;
DROP TABLE `item-content`;
DROP TABLE `item-delivery-data`;
DROP TABLE `item_id`;
DROP TABLE `participation`;
DROP TABLE `poll`;
DROP TABLE `poll_result`;
DROP TABLE `profile_check`;
DROP TABLE `queue`;
DROP TABLE `sign`;
DROP TABLE `spam`;
DROP TABLE `term`;
DROP TABLE `thread`;
DROP TABLE `tokens`;
DROP TABLE `user-item`;
vuXXXX@zulu289:~/friendica/htdocs$ ./bin/console dbstructure drop -e
DROP TABLE `clients`;
DROP TABLE `item`;
vuXXXX@zulu289:~/friendica/htdocs$
````
So I had to execute the command twice to drop all old tables.
