### ISSUE TITLE
instance specific bug for pirati.ca - favicon.ico does not exist in https://pirati.ca/favicon.ico

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11137]
While https://squeet.me/favicon.ico exists https://pirati.ca/favicon.ico does not. This leads to problems when clients or browsers expect the favicon at that location, e.g. Whalebird unable to load favicon and showing spinner indefinitely: https://github.com/h3poteto/whalebird-desktop/issues/3057

Current favicon PNG:

![triadon-rot2](https://github.com/friendica/friendica/assets/5708172/e6e21f98-d31a-46a5-9eee-13c78cd6500d)

**Comment by foss-** [comment]
~~https://pirati.ca/favicon~~ https://pirati.ca/favicon.ico
Edit: added extension

Thank you.

**Comment by MrPetovan** [comment]
Why doesn't it have an extension?
