### ISSUE TITLE
Default setup allowing following twitter users without having connected a twitter account

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11139]
### Bug Description

After creating a test account on squeet.me without changing any setting following a twitter user is possible.

### Steps to Reproduce

1.  Create new account
2.  Open Contacts and paste any twitter user URL into the `Add Contact` field e.g. `https://twitter.com/SwiftOnSecurity`
3.  Click `Connect`

Actual Result:

Following twitter user (which won't work without the connector being setup).

Expected Result:

It should not be possible to follow twitter users without the connector being setup and verified to be working.
<img width="666" alt="Screenshot 2022-01-04 at 18 52 46" src="https://user-images.githubusercontent.com/5708172/148102417-aa63ae6d-f1ac-4a66-a44a-2f0af4a07637.png">

### Platform Info
This is Friendica, version 2021.12-rc that is running at the web location https://squeet.me. The database version is 1446/1446, the post update version is 1427/1427.

**Comment by MrPetovan** [comment]
I couldn't easily hide the follow button but I was able to abort the follow process from the addon itself.
