### ISSUE TITLE
Halcyon don't work anymore with RC

### ISSUE THREAD

**Issue by annando** [friendica/friendica#11130]
In the current RC the web client [Halcyon](https://github.com/halcyon-suite) doesn't work anymore. The client does send an `OPTIONS` command and is expected to receive a list of allowed methods - but it fails with error 500 it seems. But it doesn't work either when temporarily fixing it by directly using the `header` command instead of the exception. I guess that this is the case because the execution is stopped before the access control header are sent.

i can't figure it out, so I hope that @nupplaphil can fix it.

**Comment by nupplaphil** [comment]
Which endpoint is it using ? I'll take a look

**Comment by annando** [comment]
They are using the Mastodon API endpoints. To test you can use a server like https://halcyon.zee.li/, https://halcyon.mstdn.social/ or https://halcyon.cybre.space/
