### ISSUE TITLE
api/statuses/retweet/ results in 404

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11144]
I noticed that a couple of my bots stopped working when I upgraded from the last stable version. Apparently now this endpoint results in 404 page (and not even API error code but returns complete HTML 404 page).

The call they use is the following:

`curl -sS -u usr:pass --request POST --url "https://friends.deko.cloud/api/statuses/retweet/16178428.json"`

Did something change or is it a bug? The docs seem to have changed slightly and I tried changing syntax to:

`curl -sS -u usr:pass --request POST --url "https://friends.deko.cloud/api/statuses/retweet/:16178428.json"`

...but get the same error.

**Comment by nupplaphil** [comment]
Can you try adding `16178428` as an `id` at the `POST` body and call
`curl -sS -u usr:pass --request POST --url "https://friends.deko.cloud/api/statuses/retweet.json` instead

It seems like the ID is now passed inside the POST body

**Comment by nupplaphil** [comment]
But tbh, you're right that your call should work as well, like explained here: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-retweet-id

@annando I guess we should fix this line 
https://github.com/friendica/friendica/blob/322b7c856ca9ba53bd9c7da50dd5c1e3c9197d56/static/routes.config.php#L133
and adapt it to
```patch
-		'/retweet[.{extension:json|xml|rss|atom}]'                 => [Module\Api\Twitter\Statuses\Retweet::class,               [        R::POST]],
+		'/retweet/{id:\d+}[.{extension:json|xml|rss|atom}]'        => [Module\Api\Twitter\Statuses\Retweet::class,               [        R::POST]],
```

And if so, we should check the other routes as well

**Comment by SpcCw** [comment]
Yep, this worked! Currently we can reshare like this:

`curl -sS -u usr:pass --request POST --data "id=16178428" --url "https://friends.deko.cloud/api/statuses/retweet.json"`
