### ISSUE TITLE
Webdav storage add-on interferes with configuration options of future storage add-ons

### ISSUE THREAD

**Issue by GidiKroon** [friendica/friendica#11147]
- [X] I have searched open and closed issues for duplicates

### Bug Description

The webdav_storage add-on doesn't take into account the provided `$name['name']` in its `webdav_storage_instance` and `webdav_storage_config` functions, so it would override settings from another storage add-on if it would exist. This applies to the current release candidate.

### Steps to Reproduce

1.  make a dummy storage add-on with a name that comes before 'w'
2.  enable the webdav_storage add-on
3.  go to storage admin page

Actual Result:

Note that both the dummy and the webdav storage items have the same (webdav) options

Expected Result:

Each storage item should have its own set of options.

### Platform Info

Friendica Version: Current release candidate 2021.12-rc.

Friendica Source: git

PHP version: 7.4.25

SQL version: mariadb 10.5.12

**Comment by GidiKroon** [comment]
The referenced PR is my attempt at addressing this. Since I have very limited experience with this, feel free to ignore/change/etc. I have tested it and it seems to work.

**Comment by MrPetovan** [comment]
It's perfect, thanks!
