### ISSUE TITLE
[frio] iOS Add to Home Screen: Offer to copy a post’s address to the clipboard

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11148]
The iOS Add to Home Screen browser doesn’t allow to copy the target URL of a link to the clipboard unlike iOS Safari does.

As a result, it’s impossible to share a local post URL from Add to Home Screen because it’s never available.

I want to add a new More menu item with a “Copy Link” feature for public posts only on mobile display in Frio.

**Comment by foss-** [comment]
Interesting and in its own way hilarious issue. Struggling to understand why Apple makes it so hard to copy the URL from a link in Home Screen Bookmarks. In safari itself long press works as expected and allows to just copy the URL of the link the long press is done on. I would expect Home Screen Bookmarks to behave the same and am wondering if this is a problem that should be filed with Apple.
