### ISSUE TITLE
view full size photo

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11146]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I'm not sure whether this is intended or a bug.. I just encountered it several times (I use the Frio theme):
When I'm on the single photo view page, when I click on the photo to "View Full Size", a smaller photo (than expected) is displayed.

### Steps to Reproduce

1 - Open the single photo view page. ( something like `/photos/{username}/image/785593807161d71a66509a6729465601` )
2 - Click the photo (in the center of it).

Actual Result:

`/photo/785593807161d71a66509a6729465601-2.jpg`
( a smaller photo, with `-2.jpg` ending )

Expected Result:

`/photo/785593807161d71a66509a6729465601.jpg`
( the full size photo, with  `-0.jpg` or just `.jpg` without a number. I'm not sure which one is correct )

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2021.12-rc, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1448/1448 und die Post-Update-Version 1427/1427."

Theme: Frio V.0.8.5

**Comment by SpcCw** [comment]
Same with me.

Also I vaguely remember that photos used to open not as direct links (i.e. opened in browser replacing the current page and requiring hitting "back" to return) but as popups (like they currently do in the posts) but right-clicking them and opening in new tab would open plain image.

**Comment by schmaker** [comment]
I can confirm this behavior (just wanted to report it today), pictures from albums are linked to preview image instead of full size photo.

Should be quite easy to fix as it's just hyperlink issue :)

**Comment by tobiasd** [comment]
It's not only `frio` but a general problem.

**Comment by haheute** [comment]
it seems to work now. I tried on libranet.de with all 4 themes.

**Comment by annando** [comment]
It was fixed with https://github.com/friendica/friendica/pull/11583
