### ISSUE TITLE
[Theme: frio] emoji picker can not be invoked on macOS

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11142]
### Bug Description

macOS 11.6.2: not possible to invoke emoji picker via keyboard shortcut `⌃⌘space`.

### Steps to Reproduce

1.  open browser (tried safari and firefox)
2.  open friendica with frio theme
3.  create new post and press `⌃⌘space`

Actual Result: nothing - no emoji picker is invoked

Expected Result: emoji picker should appear
<img width="626" alt="Screenshot 2022-01-05 at 11 11 41" src="https://user-images.githubusercontent.com/5708172/148200288-9f36d311-40dc-4345-aa3a-563d70d379d3.png">

To complicate things, there is a Firefox specific bug about the emoji picker option missing on macOS: https://bugzilla.mozilla.org/show_bug.cgi?id=1478347
EDIT: Fixed in Firefox v122.0 2024-01-23

### Additional testing
Since the Firefox bug complicates the situation a few additional tests were done:
- invoke emoji picker on https://search.trom.tf in Safari ✅
- invoke emoji picker on https://search.trom.tf in Firefox ❌
- invoke emoji picker on https://pirati.ca in Safari ❌
- invoke emoji picker on https://pirati.ca in Firefox ❌

Above test suggests that besides the Firefox trouble there is a frio specific problem with emoji picker on macOS.

### Platform Info
This is Friendica, version 2021.12-rc that is running at the web location https://pirati.ca. The database version is 1448/1448, the post update version is 1427/1427.

**Comment by MrPetovan** [comment]
Additionally, when pressing these keys on macOS, a "pause" icon shows up in the layout of the frio theme, suggesting a capture of the key presses in Javascript for a feature I have a hard time understanding. @rabuzarus ?

**Comment by foss-** [comment]
Firefox 122 and This is Friendica, version 2024.03-dev that is running at the web location https://pirati.ca. The database version is 1548/1548, the post update version is 1547/1547.

Works as expected. Closing.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/13834
