### ISSUE TITLE
[Twitter] Unable to integrate with twitter add-on

### ISSUE THREAD

**Issue by abhas** [friendica/friendica#11157]
I have been evaluating friendica for several weeks now. The one thing that I'm stuck on is twitter integration via the twitter add-on. I added the consumer key and secret from the API key and secret shown on the twitter developer dashboard.

After that once I try to connect with twitter (Settings -> Social Networks) and add the twitter PIN, it says "Invalid Twitter Info" in the settings. I see the following in the debug logs:

``` 
2022-01-15T07:12:35Z index [NOTICE]: Invalid twitter info (verify credentials). {"auth":"Abraham\\TwitterOAuth\\TwitterOAuth"} - {"file":"twitter.php","line":364,"function":"twitter_settings","uid":"8240ec","process_id":20465}
``` 
If I try any other combination of Twitter credentials, it does not even show the "Sign in with Twitter" button in the settings. So the API key and secret must be the right combination.

I upgraded to the latest friendica-full-2021.12-rc.tar.gz  and friendica-addons-2021.12-rc.tar.gz versions. But the behaviour remains the same. I tested this out with the friendica installation at https://libranet.de/ friendica instance and the twitter integration works perfectly there.

I believe there is something critical that I'm doing wrong. If anyone has any suggestions or experience with this issue, would be glad to try anything out!

Thanks a lot in advance...

**Comment by MrPetovan** [comment]
Hi and sorry about your trouble. Can you confirm the developer app you registered with Twitter is enabled and active?

**Comment by abhas** [comment]
> Hi and sorry about your trouble. Can you confirm the developer app you registered with Twitter is enabled and active?

Yes - the developer app in indeed enabled and active. I tried the friendica instance on libranet.de and the same keys worked there and I was able to successfully link my twitter account. But not on two friendica instances I have setup for testing.

Further things I've done:

1. Installed friendica from the github repository instead of a  rc or release tarball
2. Replaced the version of twitteroauth packaged with the twitter addon with one from the developer's git repository (and installing dependencies using composer afterwards)

The error that I get is the same in each case. After keying in the Twitter code, it continues to say "Invalid twitter info" on the settings.

Thank you very much for your response... :)

**Comment by MrPetovan** [comment]
Let's keep going. The message `Invalid twitter info` is used when the result of a successful `account/verify_credentials` call doesn't have any of the following properties: `screen_name`, `description` or `profile_image_url`.

Unfortunately we don't log successful API calls result so you wouldn't be able to see it in the log files. Instead you'll have to modify the file `addon/twitter/twitter.php` on your server to figure out what is going on.

Insert the following line just after line 357 so that it looks like this:
```php
				$account = $connection->get('account/verify_credentials');
				var_dump($account);
				if (property_exists($account, 'screen_name') &&
					property_exists($account, 'description') &&
					property_exists($account, 'profile_image_url')
				) {
```
Then refresh the connector addon settings page and it should show the result of the API call in the page. Please paste it here for further troubleshooting.

**Comment by abhas** [comment]
Got the error. Here is what was printed out by the `var_dump()` call:

> `object(stdClass)#350 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#345 (2) { ["message"]=> string(321) "You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve" ["code"]=> int(453) } } }`

Let me apply for elevated access and try this out again. Thanks a lot for this hint!

**Comment by MrPetovan** [comment]
Oh wow, didn't know about this, we should either clarify the documentation or upgrade to API v2 calls.

**Comment by abhas** [comment]
The twitter addon works fine after I was able to get elevated access for the twitter API.

> Oh wow, didn't know about this, we should either clarify the documentation or upgrade to API v2 calls.

I would be glad to contribute to this. Shall I add these instructions to this file:

    https://github.com/friendica/friendica-addons/blob/2021.12-rc/twitter/README.md

I'll send a pull request once its updated.

**Comment by annando** [comment]
I had a look at the new Twitter API. AFAIK their new version still lacks some significant functionality, so it doesn't seem to make sense to adapt the addon to the new version by now.

**Comment by MrPetovan** [comment]
> I would be glad to contribute to this. Shall I add these instructions to this file:
> 
> ```
> https://github.com/friendica/friendica-addons/blob/2021.12-rc/twitter/README.md
> ```
> 
> I'll send a pull request once its updated.

Yes, this would be great, thanks!

**Comment by MrPetovan** [comment]
> I had a look at the new Twitter API. AFAIK their new version still lacks some significant functionality, so it doesn't seem to make sense to adapt the addon to the new version by now.

Do you remember what the v2 is lacking that we need? So that we can keep an ear on the ground.

**Comment by annando** [comment]
See here: https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map

The home timeline (the part we use the most) is marked as "[COMING SOON]". Also the media part (which we use to upload images) is marked this way as well.

The endpoint `account/verify_credentials` which we use to determine the user's account is even marked as "[Replacement under consideration]".

**Comment by MrPetovan** [comment]
Ok, thanks.

**Comment by mexon** [comment]
@abhas I'm also hitting this problem.  Did you already update the documentation?  I can also help with that if you like... if I can actually get it to work!  On that... how do you actually get elevated access?  I found an application form for the Ads API, but the only information I can find for getting elevated access is:

> If you were approved for a developer account before November 15th, 2021, you were automatically converted to Elevated access. This means that your existing Apps can continue to be used to make requests to standard v1.1, premium v1.1, and enterprise endpoints, and that all of your user Access Tokens are still valid.

**Comment by MrPetovan** [comment]
The documentation hasn't been updated yet.

**Comment by ndarilek** [comment]
Struggling with this too. Initially I had the unhelpful "Invalid Twitter info" error. I found a link to request elevated access at the top of my dashboard, clicked it, and immediately had elevated access. That error went away, and my account showed as connected with the right username/bio. But posting to my timeline didn't cross-post to Twitter, nor are previous tweets imported.

Next I disconnected the account and attempted to reconnect it. The requested permissions say nothing about needing read/write access to tweets, just:

This application will be able to:
• See Tweets from your timeline (including protected Tweets) as well as your Lists and collections.
• See your Twitter profile information and account settings.
• See accounts you follow, mute, and block.

The Twitter app screen is incredibly confusing, but I'm guessing I need to grant my keys more permissions. And from this comment thread, I'm guessing I need to stick with V1 support for now. Anyone have any guidance on how to actually get this beyond just "connected" and actually working? :) When I initially tried enabling V1 support, the callback URL field was required even though the README said not to set it.

Thanks.

**Comment by Espionage724** [comment]
I just deployed a develop branch Friendica install. For Twitter, the API has to be V1. For the Callback URI, I did `social.mysite.tdl/.well-known/host-meta` although I don't know if that really does anything; the notes mention it should be blank, but Twitter requires something there for both V1 and V2.

My posts go from Friendica to Twitter fine!

**Comment by jakedfw** [comment]
Can confirm that the addon works with Elevated access and the v1 API if you are posting from Friendica to Twitter. 

I have not been able to pull the timeline into Friendica, however.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.

**Comment by Nurmagoz** [comment]
> This is likely obsolete due to Twitter addon deprecation.

Does that mean any ticket in the issues discussing Twitter is going to be closed as 'not planned?

If so, it's better to mention the deprecation announcement here as well:

https://git.friendi.ca/friendica/friendica-addons/src/branch/develop/twitter
