### ISSUE TITLE
Filter Addons did not work

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#11151]
I noticed that the "NSFW", "Advanced Content Filter" and "Blockem" addons no longer work.

- [x ] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Activate the NSFW Addon
2.  Set a filter rule
3.  Reload the Timeline and check the filter rule

#### Actual Result:

No post is folded

#### Expected Result:

The post to which the filter rule fits should be folded.

### Platform Info

Friendica Version: 'Siberian Iris' 2021.12-rc - 1448

Friendica Source: git

PHP version: 7.4.26

SQL version: 10.3.27 MariaDB

**Comment by MrPetovan** [comment]
I cannot reproduce this issue, I have the "NSFW" and "Advanced Content Filter" addon enabled and both are running nominally. I recently added the word "🟩" to the list in my "NSFW" addon settings to collapse Wordle posts and it's been working.

Are you able to reload the active addons in the Administration section for Addons?

**Comment by atasingorneq** [comment]
OK, i think I have solved the problem for me. I first disabled all addons and then enabled them again. Now the filters work again as they should.
