### ISSUE TITLE
Error 500 - settings/2fa/trusted... - Argument must be of the type string, null given

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11169]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

Looks like the page .../settings/2fa/trusted?t=... ist throwing a error 500 and is showing as white screen of death.

After entering my password and clicking on the 'trusted browsers' button I get an empty, white page.

But I don't get any PHP fatal errors in my PHP log.

This is logged in Apache access log:

```"GET /settings/2fa/trusted?t=1642856952.f8e62e6..........197d218 HTTP/2.0" 500 1043 "https://venera.social/settings/2fa" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:96.0) Gecko/20100101 Firefox/96.0"```

This is logged in Friendica application log:

```
index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Util\DateTimeFormat::utc() must be of the type string, null given, called in src/Module/Settings/TwoFactor/Trusted.php on line 114" at src/Util/DateTimeFormat.php line 55 {"exception":"TypeError: Argument 1 passed to Friendica\Util\DateTimeFormat::utc() must be of the type string, null given, called in src/Module/Settings/TwoFactor/Trusted.php on line 114 and defined in src/Util/DateTimeFormat.php:55
Stack trace:
#0 src/Module/Settings/TwoFactor/Trusted.php(114): Friendica\Util\DateTimeFormat::utc()
#1 [internal function]: Friendica\Module\Settings\TwoFactor\Trusted->Friendica\Module\Settings\TwoFactor\{closure}()
#2 src/Module/Settings/TwoFactor/Trusted.php(127): array_map()
#3 src/BaseModule.php(239): Friendica\Module\Settings\TwoFactor\Trusted->content()
#4 src/App.php(711): Friendica\BaseModule->run()
#5 index.php(44): Friendica\App->runFrontend()
#6 {main}"} - 
{"file":null,"line":null,"function":null,"uid":"273a83","process_id":1699349}
```

### Steps to Reproduce

1.  enable 2FA
2.  go to settings -> 2FA
3.  enter your password and click on the 'trusted browsers' button

Actual Result:
Empty, white page and error 500.

Expected Result:
Page with trusted browsers/devices.

### Platform Info

Friendica Version:
2021.12-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.6 MariaDB

**Comment by MrPetovan** [comment]
Thanks to @nupplaphil's work, most PHP errors now appears in the Friendica logs. The only PHP errors that will appear in the webserver logs will happen before the log system is set up.
