### ISSUE TITLE
reshared tweet with RTL username (e.g. hebrew) ends up showing RTL on friendica despite LTR language in post

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11160]
A reshared tweet with RTL username (e.g. hebrew) ends up showing RTL post content on friendica despite LTR language in post.

Expected
Not familiar with details of implementation but it feels as if language of post content should have priority over user nickname when deciding when to show a post as RTL.

**Comment by MrPetovan** [comment]
Follow-up to #10469 
Part of #8262
