### ISSUE TITLE
Improve implementation for 2FA remember browser option

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11177]
see also: https://github.com/friendica/friendica/issues/10690

### Currently

The wording is hard to understand and the places where management of trusted browsers is done in friendica is hard to remember and difficult to discover.

### Expected

The problem with current wording `This is my two-factor authenticator app device` is, that with a password manager which syncs with all devices, this is very confusing. Also OTPs are not only accessible on mobile but also on desktop when using password managers making this even more confusing. (the hint about recovery codes specifically mentions access to mobile.

Apple uses the text below which I think is a good solution and easy to grasp.

There is another smart aspect about how apple has implemented this browser trusting mechanism: They do not ask this question during login, but *after* the login has been sent:

```
Trust this browser?
If you choose to trust this browser, you will not be asked for a verification code the next time you sign in.

Options: Not Now | Don't Trust | Trust (defaulting to trust)
```

<img width="556" alt="Screenshot 2022-01-23 at 12 56 18" src="https://user-images.githubusercontent.com/5708172/150677471-1e6af4e9-c310-4078-abe0-ee438a1a220e.png">

And actually apple has done a good job with this implementation since when you log out you see another smart dialog:

```
Sign out of this browser?
If you trust this browser, you will not be asked for a verification code the next time you sign in.
Options: Trust and sign out | Cancel | Sign out (defaulting to Sign out)
```
Allowing to forget about the browser trusting on sign out, or keeping it and with that giving the user full control. That is really nicely done.

<img width="653" alt="Screenshot 2022-01-23 at 13 04 32" src="https://user-images.githubusercontent.com/5708172/150677586-43609b08-20eb-4f30-8fe1-da9271a8dcf9.png">

The info about recovery codes is also unnecessarily confusing:
`Don’t have your phone? Enter a two-factor recovery code`
Proposal: `If you do not have access to your authentication code you can use a two-factor recovery code.`

**Comment by foss-** [comment]
Patch trickled down to pirati ca 🙌

First test: When clicking on `Trust` after providing TOTP code, nothing happens. Do we have trust issues (scnr)?
![2fa totp trust](https://user-images.githubusercontent.com/5708172/179398455-ae9490b7-238b-4f38-8e23-2e2acab07694.gif)

**Comment by nupplaphil** [comment]
> Patch trickled down to pirati ca 🙌
> 
> First test: When clicking on `Trust` after providing TOTP code, nothing happens. Do we have trust issues (scnr)?
> ![2fa totp trust](https://user-images.githubusercontent.com/5708172/179398455-ae9490b7-238b-4f38-8e23-2e2acab07694.gif)
> 
> 

Can you open the webdebugger (F12) and paste the console output before and after clicking? It's hard to reproduce...

**Comment by foss-** [comment]
Maybe we can ignore this. I am not able to reproduce and  the second attempt behaved as expected.

Thanks so much for picking this up. I think this is a very useful improvement for users.
