### ISSUE TITLE
Videos not playing with error `No video with supported format and MIME type found.`

### ISSUE THREAD

**Issue by carlostkd** [friendica/friendica#11188]
From any of my post sources that appear on my feed , when i try to play any video i get:

no video with supported format and mime found.

did not found anything on the settings related to this, any help qould be appreciated.
Thanks in advanced

--SOLVED---
it was from browser and not from friendica.

**Comment by foss-** [comment]
Just to elaborate how to resolve this: if you see `No video with supported format and MIME type found.`in your browser, at least for Firefox, to resolve this you can click the shield icon in the address bar, then disable enhanced tracking protection. That will allow playing videos.
