### ISSUE TITLE
verify_credentials.json gives blank response and 500 error

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#11193]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The said API located at `/api/account/verify_credentials.json` is responding empty when a user name and app-specific password (2FA is surely enabled) credentials are entered.

### Steps to Reproduce

1.  Enable 2FA in your Friendica account
2.  Create app-specific password and copy it
3.  Invoke the API URL directly in your browser and enter `username` and the copied password

Actual Result:

An empty result (`wget` returns zero bytes) was returned.

Expected Result:

A JSON response is returned.

### Screenshots

_None needed._

### Platform Info

Friendica Version:
`develop` at c34994df0317eeb9fb5c5ae8e9ca65b9404126e2

Friendica Source:
git

PHP version:
`PHP 7.3.29-1~deb10u1`

SQL version:
`MariaDB 1:10.3.27-0+deb10u1`

The strange thing is, it worked yesterday and suddenly, over night and no changes are done, it behaves now constantly like this. The normal website, paths like `/network` are not affected by this bug.

**Comment by Quix0r** [comment]
I'm currently narrowing it down. It looks like `Model/Post/Media::addAttachmentsToBody(int,string)` with type `string` causing this. In other words `Friendica\Factory\Api\Twitter\Status::createFromArray()` is invoking it with `$item[body]` not being a string (maybe unset).

Edit: **Bingo!!!** The type is `NULL`, not `string`. So `Post::selectFirst($fields, ['uri-id' => $uriId, 'uid' => [0, $uid]], ['order' => ['uid' => true]]);` is returning an array with the key `body` having type `NULL`.

**Comment by Quix0r** [comment]
The body was actually empty. I deleted the comment with no body in it. If I check that `$item['body']` is `NULL` and fix to an empty string, the API returns a valid JSON again.

Temporary fix: https://f.haeder.net/item-null-body.diff

**Comment by MrPetovan** [comment]
Thank you for your report and your work troubleshooting the issue. Even if the body is empty, it shouldn't be `null`.

**Comment by Quix0r** [comment]
Okay, that's maybe a good testing scenery (unit test) and maybe `Post::select*()` should all validate if `body` is `NULL`? Means that they throw an exception?

**Comment by MrPetovan** [comment]
We can do this a couple ways. We can do it in the code using the null coalescing operator `??` in each call to ensure the body passed to `Model/Post/Media::addAttachmentsToBody` isn't `null`, or we can update the database structure to disallow `NULL` values in the `post-content.body` table field.

**Comment by Quix0r** [comment]
Okay, maybe both together? ``SELECT * FROM item-content WHERE body IS NULL`` returns zero rows here.

**Comment by MrPetovan** [comment]
I've got one result in my production Friendica database, although your result suggests that the issue is somewhere else, possibly a missing field?

**Comment by MrPetovan** [comment]
How about in the `post-user-view` view?

**Comment by MrPetovan** [comment]
I'm getting way more results with ``SELECT * FROM `post-user-view` WHERE `body` IS NULL``.

**Comment by Quix0r** [comment]
`$item['body']` is  set if you mean this. `post-user-view` has many records with `body` set to NULL.

**Comment by MrPetovan** [comment]
This is caused by the `LEFT JOIN` in the view query. We are already coalescing several values to empty string when they're `NULL`, we need to coalesce this one as well.

**Comment by Quix0r** [comment]
A view is based on real tables, shouldn't we address the issue at the causing table? E.g. setting `body` to an empty string where it is NULL?

**Comment by MrPetovan** [comment]
Yes, this is what "coalescing `NULL`" means.

**Comment by Quix0r** [comment]
> Yes, this is what "coalescing `NULL`" means.

Oh, okay. Thank you for explaining it. :)

**Comment by MrPetovan** [comment]
Of course, technical jargon is useful as shorthand only if everybody understands it.
