### ISSUE TITLE
XMPP addon blocks menu with post button

### ISSUE THREAD

**Issue by schmaker** [friendica/friendica#11202]
### Bug Description

When XMPP addon is enabled, menu and post button is missing. Disabling addon fixes the issue. Tested in Firedragon / Firefox

### Screenshots
XMPP enabled
![Snímek obrazovky pořízený 2022-02-02 18-53-24](https://user-images.githubusercontent.com/14954032/152210567-7b589d0d-ddf1-4e22-b832-6bd789a14705.png)

XMPP disabled
![Snímek obrazovky pořízený 2022-02-02 18-53-59](https://user-images.githubusercontent.com/14954032/152210529-ca336c53-cc26-48a7-bd25-2a4a7966df93.png)

### Platform Info

Friendica Version:
Friendica 2021.09

**Comment by annando** [comment]
Because of these reasons the XMPP addon is deprecated.

**Comment by schmaker** [comment]
i just deployed the instance and i actually have no idea how to tell it's deprecated at all, but i tried Jappix first and that feels more outdated than this one (it does not even show in UI).

So there is no way to use XMPP within friendica at the moment, or some rework is in progress?

**Comment by annando** [comment]
Sadly there is currently no one working at it. We need someone who is interested in working with Javascript.

**Comment by schmaker** [comment]
Closing as XMPP addon was removed from supported addons

**Comment by sjehuda** [comment]
> Sadly there is currently no one working at it. We need someone who is interested in working with Javascript.

Do you meam that this XMPP plugin is relied on JS?

I might consider to work on it, or other XMPP capabilities, provided that these are also of JS.

**Comment by annando** [comment]
In the past we used a Javascript client to act as an XMPP client.

**Comment by sjehuda** [comment]
I would advise to do so, again.

There are several useful ECMAScript modules of XMPP which can be
utilzed for all of the prevalent XMPP features.
