### ISSUE TITLE
Can't Post after Upgrading to Friendica 'Siberian Iris' 2021.12-rc - 1449

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#11203]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Can't Post after Upgrading to Friendica 'Siberian Iris' 2021.12-rc - 1449.  However, if I login as a different user I can.  I suspect I've gotten myself blocked again as this is how it behaved before, however, I do not show up as blocked in Users nor in Contacts.
### Steps to Reproduce

Upgrade to Friendica 'Siberian Iris' 2021.12-rc - 1449 as described on website.  In addition upgrade addons because although it did not tell you to, friendica would not load and logs indicated a compatibility issue with addons. Upgrading add ons got the site working again, for everyone except myself.  I can read but if I post it just disappears.  If I login as a different user and post, that shows.

## Actual Result:

My posts don't show.
## Expected Result:
My posts show.

Before you gave me a database query that removed me from a block list but I do not still have that query or know where to look.
### Platform Info

Friendica Version:

Friendica Source: 
Friendica 'Siberian Iris' 2021.12-rc - 1449
PHP version:
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.5.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by MrPetovan** [comment]
See https://github.com/friendica/friendica/issues/10162#issuecomment-830752874

**Comment by 4nanook** [comment]
Yep that was it.  Don't know how I'm "ignoring myself" by doing an update but at any rate same query fixed it.
