### ISSUE TITLE
PHP8 and smarty create a lot of warnings

### ISSUE THREAD

**Issue by annando** [friendica/friendica#11212]
I recently updated my server to PHP8. Friendica seems to work with it now - with the exception that smarty is generating a lot of warnings:
```
PHP Warning:  Undefined array key "name" in view/smarty3/compiled/810e28937977578ebd6d23086910568b640eade6_2.file.event_stream_item.tpl.php on line 59
```
That line looks this way:
```
<?php if ($_smarty_tpl->tpl_vars['location']->value['name']) {?>
```

In the template it looks that way:
```
{{if $location.name}}
```

There is a way fixing it: We can replace that check with a call like this:
```
{{if array_key_exists('name', $location)}}
```

But since we are using these types of checks all the time this would mean a lot of work in the templates.

Question is if there is some shortcut. Is there some smarty update or some smarty option that can help?

**Comment by MrPetovan** [comment]
We need to upgrade to Smarty version 4 that was released last November, and call `$smarty->muteUndefinedOrNullWarnings();` when we instantiate it.

**Comment by annando** [comment]
I'm still receiving these warnings:
```
[19-Feb-2022 14:22:37 UTC] PHP Warning:  Trying to access array offset on value of type bool in /htdocs/view/smarty3/compiled/533afe24beaad83b166e60561a10571d8bd76f73_2.file.wall_thread.tpl.php on line 500
[19-Feb-2022 14:22:37 UTC] PHP Warning:  Trying to access array offset on value of type bool in /htdocs/view/smarty3/compiled/533afe24beaad83b166e60561a10571d8bd76f73_2.file.wall_thread.tpl.php on line 672
[19-Feb-2022 14:22:37 UTC] PHP Warning:  Trying to access array offset on value of type bool in /htdocs/view/smarty3/compiled/533afe24beaad83b166e60561a10571d8bd76f73_2.file.wall_thread.tpl.php on line 792
[19-Feb-2022 14:22:37 UTC] PHP Warning:  Trying to access array offset on value of type bool in /htdocs/view/smarty3/compiled/533afe24beaad83b166e60561a10571d8bd76f73_2.file.wall_thread.tpl.php on line 912
```

**Comment by MrPetovan** [comment]
Please clear your Smarty cache, these templates were likely created with the previous version of Smarty. The cache is only refresh when the source file changes, which isn't the case when we just upgrade Smarty.

**Comment by nupplaphil** [comment]
@MrPetovan we could wipe the cache during an update process to avoid this situstion, couldn't we?

**Comment by MrPetovan** [comment]
Yes we could, although we could do it as a one-off each time we're upgrading Smarty since we rarely do it.

**Comment by annando** [comment]
I cleared the cache but the warning reappeared.

**Comment by nupplaphil** [comment]
> Yes we could, although we could do it as a one-off each time we're upgrading Smarty since we rarely do it.

Yes I ment exactly that case , just one time after a smarty upgrade, not every time :)

**Comment by MrPetovan** [comment]
> I cleared the cache but the warning reappeared.

Ugh, I did what I was told to do, not sure what to do next since I don't have PHP8 to test.

**Comment by annando** [comment]
It is only these three warnings. They occur with multi level arrays. One of the occurrences is `{{if $item.drop.dropping}}` which I changed to `{{if $item.drop && $item.drop.dropping}}` to reduce the noise. I'm not sure if we can fix this at the engine level or if we should fix that at the template level.

**Comment by annando** [comment]
This is fixed now.
