### ISSUE TITLE
Broken symlinks in friendica-full-2022.02.tar.gz

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#11219]
### Bug Description

There are some broken symbolic links in the `friendica-full-2022.02.tar.gz` released package:

```
$ ls -l /PATH/TO/FRIENDICA/vendor/bin/
lrwxrwxrwx 1 root root 72 febr   6 21:34 certainty-cert-symlink -> friendica-full-2022.02/../paragonie/certainty/bin/certainty-cert-symlink
lrwxrwxrwx 1 root root 70 febr   6 21:34 html-to-markdown -> friendica-full-2022.02/../league/html-to-markdown/bin/html-to-markdown
lrwxrwxrwx 1 root root 56 febr   6 21:34 uaparser -> friendica-full-2022.02/../ua-parser/uap-php/bin/uaparser
```

Possible fix:

```
cd /PATH/TO/FRIENDICA/vendor/bin/
sudo ln -fns ../paragonie/certainty/bin/certainty-cert-symlink certainty-cert-symlink 
sudo ln -fns ../league/html-to-markdown/bin/html-to-markdown html-to-markdown 
sudo ln -fns ../ua-parser/uap-php/bin/uaparser uaparser
```

**Comment by nupplaphil** [comment]
Strange.. Seems like a wrong or missing tar option .. I'll have a look

**Comment by nupplaphil** [comment]
ah I see what's happening:
https://github.com/friendica/friendica/blob/develop/.woodpecker/.continuous-deployment.yml#L65
This prefix **all** files with the current archive name as a directory.

But this doesn't work for symlinks this way ;-)

**Comment by urbalazs** [comment]
@tobiasd @nupplaphil this issue is now added to milestone **2022.05**. However, this will block the release of **2022.03** (if Friendica will be released in this month). I think it makes sense to fix this issue before the next release.

**Comment by tobiasd** [comment]
Thanks for noticing this!

**Comment by MrPetovan** [comment]
@nupplaphil This is now blocking the 2022.03 release, how soon can you work on this? Alternatively, do you know what needs to be done to fix this so that I can do it myself?

**Comment by nupplaphil** [comment]
I'll try it at night or at least describe the problem
