### ISSUE TITLE
No access to file storage after upgrade to 2022.02

### ISSUE THREAD

**Issue by Arrappathor** [friendica/friendica#11220]
I have searched open and closed issues for duplicates

### Bug Description

Cannot access file storage, no images are shown on website
I also have no acess to the file storage manager in the admin-panel.

### Steps to Reproduce

1.  Upgrade to 2022.02
2.  -> admin-panel
3.  -> file storage / Speicher

Actual Result:
White screen

Expected Result:
Finding options to change file-storage between database an file system

### Platform Info

Friendica Version:
2022.02

Friendica Source: 
full.tar.gz including addons from website

PHP version: 7.4 (Debian bullseye)

SQL version: MariaDB 10.5

Thank you!

**Comment by annando** [comment]
A blank screen most likely is a result of some PHP error. Please check your PHP log file. (see your php.ini file for the exact location)

**Comment by Arrappathor** [comment]
when executing worker.php manually it shows over and over and over:
 PHP Warning:  chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 102
PHP Warning:  chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 103
PHP Warning:  chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 154

Apaches error log only shows 
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
[Mon Feb 07 06:50:38.124062 2022] [mpm_prefork:notice] [pid 584] AH00170: caught SIGWINCH, shutting down gracefully
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
[Mon Feb 07 06:51:00.793165 2022] [ssl:warn] [pid 526] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the se>
[Mon Feb 07 06:51:02.779842 2022] [ssl:warn] [pid 590] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the se>
[Mon Feb 07 06:51:02.807779 2022] [mpm_prefork:notice] [pid 590] AH00163: Apache/2.4.52 (Raspbian) OpenSSL/1.1.1k configured -- resuming norma>
[Mon Feb 07 06:51:02.807966 2022] [core:notice] [pid 590] AH00094: Command line: '/usr/sbin/apache2'

Thank you.

**Comment by nupplaphil** [comment]
Try `chmod` the files itself.
`chmod 0770 -R your/data/directory`

Then it should work again

**Comment by Arrappathor** [comment]
My file-directory is located outside the webserver and hasn't been touched while upgrading.
chmod 0770 -R didn't solve the php-warnings:

PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 102
PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 103
PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 154

Somehow, i can't locate my php-error-log, i assume it's in apache's log (as seen above)
The admin panel shows php is being protocolled

PHP Protokollierung ist derzeit aktiviert.

But i can't find the said code

`error_reporting(E_ERROR | E_WARNING | E_PARSE);
ini_set('error_log','php.out');
ini_set('log_errors','1');
ini_set('display_errors', '1');
`

in my index.php

Thank you.

**Comment by Arrappathor** [comment]
I restored 2021.09 and can access storage/Speicher in admin-panel again. 
But now I get the same PHP-Warnings as above (now lines 108+109+160) and still can't upload images. 
Also only some images from the filesystem are shown.
I guess there's something wrong with the SD-Card (where my RaspberryPi OS is running on.)

**Comment by annando** [comment]
When you said that you "restored" it: Have you imported a backup of the database as well? Each new version normally contains some database changes. These can be imcompatible with previous versions.

**Comment by Arrappathor** [comment]
Yes, i also imported a backup of the database.
After a while i renewed permissions and ownership of the files directory, and now everything's running fine on 2019.09 again: no more PHP warnings and upload also works.
I will try upgrading to 2022.02 later again.

**Comment by Arrappathor** [comment]
Next try, no success, same warnings

PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 102
PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 103
PHP Warning: chmod(): Operation not permitted in /var/www/html/src/Core/Storage/Type/Filesystem.php on line 154

White screen on admin/storage

As 2021.09 was (also after restoring) running fine, i don't think, my sd-card is corrupt.

Uploading is still not possible (white screen), but some images are displayed:

![Screenshot 2022-02-08 at 13-32-27 Bambergica Social Network Arappathor Bambergica Social Network](https://user-images.githubusercontent.com/17974573/152989732-2777e3fa-3e15-4bde-86a4-89da893c4ef5.png)

Hm. Any ideas?

**Comment by annando** [comment]
A white screen is a good indicator for a PHP error. Means: you need to have a look into your php.ini to check where (and if) errors and warnings ere logged. This can be in an external log file. It can be in the syslog. We will need that information for any further investigation.

This `PHP Warning: chmod(): Operation not permitted` is a good indicator that the web server process has got a file permission process. So please check if the webserver's user has got access to the storage directory.

**Comment by Arrappathor** [comment]
i configured my in etc/php/7.4/apache2/php.ini

```
log_errors = on
error_reporting = E_ALL
error_log = syslog
```
but i get no entrys in /var/log/apache2/error.log
Am i doing something wrong here?

Enabling logging in friendica shows

```
Friendica\Core\Storage\Exception\StorageException: Path "/home/pi/friendica" does not exist or is not writeable. in /var/www/html/src/Core/Storage/Type/Filesystem.php:60
Stack trace:
#0 /var/www/html/src/Core/Storage/Repository/StorageManager.php(200): Friendica\Core\Storage\Type\Filesystem->__construct()
#1 /var/www/html/src/Core/Storage/Repository/StorageManager.php(131): Friendica\Core\Storage\Repository\StorageManager->getByName()
#2 /var/www/html/src/Core/Storage/Repository/StorageManager.php(106): Friendica\Core\Storage\Repository\StorageManager->getWritableStorageByName()
#3 [internal function]: Friendica\Core\Storage\Repository\StorageManager->__construct()
#4 /var/www/html/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#5 /var/www/html/vendor/level-2/dice/Dice.php(145): Dice\Dice->Dice\{closure}()
#6 /var/www/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#7 /var/www/html/src/DI.php(422): Dice\Dice->create()
#8 /var/www/html/src/Module/Admin/Storage.php(98): Friendica\DI::storage()
#9 /var/www/html/src/BaseModule.php(239): Friendica\Module\Admin\Storage->content()
#10 /var/www/html/src/App.php(711): Friendica\BaseModule->run()
#11 /var/www/html/index.php(44): Friendica\App->runFrontend()
#12 {main}
```

when entering admin/storage.

All i can tell is, that the storage-folder is writable by the webserver. I ran chown, chmod on files and folders as on my other services and 2021.09 didn't have this problem. 

?

**Comment by annando** [comment]
The system says `Path "/home/pi/friendica" does not exist or is not writeable.`. The message is thrown here:
https://github.com/friendica/friendica/blob/develop/src/Core/Storage/Type/Filesystem.php#L59-L61

It is this check:
````
if (!is_dir($this->basePath) || !is_writable($this->basePath)) {
	throw new StorageException(sprintf('Path "%s" does not exist or is not writeable.', $this->basePath));
}
````

The process is checking whether the directory exists (`is_dir(...)`) and if it is writable (`is_writable(...)`). If one or both of the checks are failing then the error is thrown. There are no other reasons why the error would be thrown here except of these two cases.

Concerning the configuration in the php.ini: This means that the PHP errors are logged in the syslog. This configuration doesn't mean that the logging is done in the apache log.

**Comment by Arrappathor** [comment]
When i 

`tail -f -n 1000 /var/log/syslog | grep "php"`

there are no php-warnings in syslog; except at 21:47 

```
Feb  8 21:00:02 raspberrypi CRON[15317]: (www-data) CMD (cd /var/www/html; /usr/bin/php bin/worker.php)
Feb  8 21:04:01 raspberrypi CRON[15463]: (www-data) CMD (php -f /var/www/nextcloud/cron.php)
Feb  8 21:09:01 raspberrypi CRON[15769]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  8 21:09:01 raspberrypi CRON[15770]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  8 21:09:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  8 21:09:02 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  8 21:09:02 raspberrypi systemd[1]: Finished Clean php session files.
Feb  8 21:39:01 raspberrypi CRON[16463]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  8 21:39:01 raspberrypi CRON[16464]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  8 21:39:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  8 21:39:01 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  8 21:39:01 raspberrypi systemd[1]: Finished Clean php session files.

Feb  8 21:47:05 raspberrypi php: PHP Warning:  session_set_cookie_params(): Cannot change session cookie parameters when session is active in /var/www/kriss/index.php on line 5004

Feb  8 22:00:01 raspberrypi CRON[16871]: (www-data) CMD (cd /var/www/html; /usr/bin/php bin/worker.php)
Feb  8 22:04:01 raspberrypi CRON[17030]: (www-data) CMD (php -f /var/www/nextcloud/cron.php)
Feb  8 22:09:01 raspberrypi CRON[17074]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  8 22:09:01 raspberrypi CRON[17075]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  8 22:09:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  8 22:09:01 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  8 22:09:01 raspberrypi systemd[1]: Finished Clean php session files.
Feb  8 22:39:01 raspberrypi CRON[17502]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  8 22:39:01 raspberrypi CRON[17503]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  8 22:39:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  8 22:39:02 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  8 22:39:02 raspberrypi systemd[1]: Finished Clean php session files.
(...)
Feb  9 04:39:01 raspberrypi CRON[22323]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  9 04:39:01 raspberrypi CRON[22324]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  9 04:39:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  9 04:39:01 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  9 04:39:01 raspberrypi systemd[1]: Finished Clean php session files.
Feb  9 05:00:01 raspberrypi CRON[22626]: (www-data) CMD (cd /var/www/html; /usr/bin/php bin/worker.php)
Feb  9 05:04:01 raspberrypi CRON[22795]: (www-data) CMD (php -f /var/www/nextcloud/cron.php)
Feb  9 05:09:01 raspberrypi CRON[23202]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb  9 05:09:01 raspberrypi CRON[23203]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Feb  9 05:09:01 raspberrypi systemd[1]: Starting Clean php session files...
Feb  9 05:09:01 raspberrypi systemd[1]: phpsessionclean.service: Succeeded.
Feb  9 05:09:01 raspberrypi systemd[1]: Finished Clean php session files.
```

I'm not getting, why the file storage is writeable in 2021.09, but should not be in 2022.02. I'm confused.

**Comment by annando** [comment]
To avoid these problems you could switch back to 2021.09. Then - using the console command - you could switch to the database storage and - **important** - perform the command to move the content. After this had been done, your content should be in the "storage" table and you shouldn't have got any permission issues anymore.

**Comment by Arrappathor** [comment]
Okay. Thank you.
I can manage all of this via cli, i.e.?

` bin/console storage set Database `

and then 

` bin/console storage move`

Do i have to take care of **this**?

bin/console storage move **[table] [-n 5000]**
    Move stored data to current storage backend.
        **table       one of "photo" or "attach". default to both
        -n          limit of processed entry batch size**

Thank you. Again!

**Comment by annando** [comment]
Yeah, please execute both commands via CLI.

**Comment by Arrappathor** [comment]
```
bin/console storage move
PHP Warning:  unlink(/home/pi/friendica/05/a0/a5de6e9bc180bbad013df65b19267c4840a73c2000830fc3accb044905fe): Permission denied in /var/www/html/src/Model/Storage/Filesystem.php on line 174
[Error] Cannot delete with file with reference "05a0a5de6e9bc180bbad013df65b19267c4840a73c2000830fc3accb044905fe"

```

**Comment by annando** [comment]
You have to run this with the user that has got write permissions for these files.

**Comment by Arrappathor** [comment]
Sorry, my fault. 
Somehow ownerships and permissions have changed; i renewed and now it seems to work. 
Thank you.

**Comment by Arrappathor** [comment]
Okay, it went well, i'm now on 2022.02.
Thank you very much for your help and patience.
Should i close this issue?

**Comment by nupplaphil** [comment]
If it works for you -> yes please :)
Glad to hear!

Does it work now with the filesystem too or do you mean you successfully migrated to the DB?

**Comment by Arrappathor** [comment]
I migrated to the database and upgraded sucessfully to 2022.02
I don't know, if i should return the storage to Filesystem:
I'm a little afraid. ;-) but i want my database to be as small as possible, and now its size grew from 100MB to 600MB
Anyway: thank you all!
