### ISSUE TITLE
Database upgrade fails during update to 2022.02

### ISSUE THREAD

**Issue by hpgauster** [friendica/friendica#11223]
The database update seems to fail for me when updating to 2022.02. When running `bin/console dbstructure update` I get this:

```[Error] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`friendica`.`item`, CONSTRAINT `item_ibfk_5` FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`))```

This is on Arch Linux, php Version 8.1.2

**Comment by annando** [comment]
From which version are you coming?

**Comment by hpgauster** [comment]
> From which version are you coming?

Recent stable 2021.09

**Comment by annando** [comment]
In that version you don't need the `item` table anymore. When you think that everything is fine then please execute `bin/console dbstructure drop` to see a list of deleteable tables. And when you send execute `bin/console dbstructure drop -e` all these tables will be deleted. In your version you might have to execute this command multiple times until all unneeded tables are deleted.

Then you should be able to perform the update.

**Comment by hpgauster** [comment]
OK, I ran `bin/console dbstructure drop` and `bin/console dbstructure drop -e`. (several times).

 `bin/console dbstructure update` now results in
```[Error] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`friendica`.`post-thread-user`, CONSTRAINT `post-thread-user_ibfk_7` FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`))```

**Comment by annando** [comment]
Which database version are you currently on?

**Comment by annando** [comment]
BTW: You could try to comment out the line 1029 (```DBA::delete('permissionset', ["`id` != ? AND `allow_cid` = '' AND ...```) in the file update.php and try again.

**Comment by hpgauster** [comment]
> Which database version are you currently on?

MariaDB 10.6.5

Running update.php with line 1029 commented out as suggested did the trick. Update is complete, my instance is running fine again. Thank you for your help!

If I can provide you with any information that might be useful -> let me know.

**Comment by annando** [comment]
Good that this helped! I don't think that I need more information, I guess I have everything I need to continue, thanks!

**Comment by efelon** [comment]
Commenting out line 1029 in update.php solved it for me too. My system fyi:
```
Friendica before: 2021.09
Raspberry Pi OS 64
PHP 8.0.15 (cli) (built: Jan 29 2022 07:39:48) ( NTS )
mariadb  Ver 15.1 Distrib 10.5.14-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper
```

**Comment by tobiasd** [comment]
Is this issue still active or can it be closed?

**Comment by hpgauster** [comment]
As far as I understand https://github.com/friendica/friendica/pull/11228 fixed the issue. I assume it is safe to close the issue.
