### ISSUE TITLE
Datenbank Update schlägt fehl - Update auf 2022.02 - 1434

### ISSUE THREAD

**Issue by gitkald** [friendica/friendica#11222]
Mahlzeit,
das DB Update scheint wohl nicht durchzulaufen. Das Ausführen des Befehls php bin/console.php dbstructure update erzeugt auf der Konsole folgenden Fehler:
PHP Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/vhosts/friendica.ennimedia.de/src/Core/Config/ValueObject/Cache.php on line 107

Danach geht die Instanz in den Wartungsmodus, den ich nur noch über SQL beenden kann. Jemand eine Idee?

Gruß Malte

**Comment by annando** [comment]
Welche PHP-Version setzt Du ein?

**Comment by gitkald** [comment]
Habe es mit 8.0.4 und auch mit 7.x versucht. Beide den selben Effekt.

**Comment by annando** [comment]
Die Meldung tritt nach meinen Recherchen nur auf, wenn die PHP-Version zu niedrig ist. Bitte führe diesen Befehl auf der Kommandzeile aus: `php --version`

**Comment by gitkald** [comment]
PHP 8.0.3 (cli) (built: Mar 10 2021 16:53:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

**Comment by gitkald** [comment]
Ok, da habe ich wohl mit der falschen PHP Version gearbeitet. Wenn ich nun folgendes eingebe:

```
/opt/plesk/php/8.0/bin/php bin/console.php dbstructure update

ALTER TABLE `user-contact` ADD `uri-id` int unsigned COMMENT 'Id of the item-uri table entry that contains the contact url', ADD `hidden` boolean COMMENT 'This contact is hidden from the others', ADD `pending` boolean COMMENT '', ADD `rel` tinyint unsigned COMMENT 'The kind of the relation between the user and the contact', ADD `info` mediumtext COMMENT '', ADD `notify_new_posts` boolean COMMENT '', ADD `remote_self` boolean COMMENT '', ADD `fetch_further_information` tinyint unsigned COMMENT '', ADD `ffi_keyword_denylist` text COMMENT '', ADD `subhub` boolean COMMENT '', ADD `hub-verify` varchar(255) COMMENT '', ADD `protocol` char(4) COMMENT 'Protocol of the contact', ADD `rating` tinyint COMMENT 'Automatically detected feed poll frequency', ADD `priority` tinyint unsigned COMMENT 'Feed poll priority', ADD UNIQUE INDEX `uri-id_uid` (`uri-id`,`uid`), ADD FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
[Error] SQLSTATE[42S01]: Base table or view already exists: 1050 Table './friendica_ennimedia/user@002dcontact' already exists
```

kommt dieser Fehler.

**Comment by annando** [comment]
Bitte schaue nach, ob im Hintergrund ein weiteres Datenbank-Update läuft. (`show processlist;` in der MySQL-Konsole). Sollte das nicht der Fall sein, führe das SQL-Kommando per Konsole aus. **Wichtig:** Bitte mache es wirklich per Konsole und nicht über irgendwelche Webfrontends.

**Comment by gitkald** [comment]
Guten Morgen Michael,
identische Fehlermeldung auf der Konsole:

`Database changed
mysql> ALTER TABLE `user-contact` ADD `uri-id` int unsigned COMMENT 'Id of the item-uri table entry that contains the contact url', ADD `hidden` boolean COMMENT 'This contact is hidden from the others', ADD `pending` boolean COMMENT '', ADD `rel` tinyint unsigned COMMENT 'The kind of the relation between the user and the contact', ADD `info` mediumtext COMMENT '', ADD `notify_new_posts` boolean COMMENT '', ADD `remote_self` boolean COMMENT '', ADD `fetch_further_information` tinyint unsigned COMMENT '', ADD `ffi_keyword_denylist` text COMMENT '', ADD `subhub` boolean COMMENT '', ADD `hub-verify` varchar(255) COMMENT '', ADD `protocol` char(4) COMMENT 'Protocol of the contact', ADD `rating` tinyint COMMENT 'Automatically detected feed poll frequency', ADD `priority` tinyint unsigned COMMENT 'Feed poll priority', ADD UNIQUE INDEX `uri-id_uid` (`uri-id`,`uid`), ADD FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
ERROR 1050 (42S01): Table './friendica_ennimedia/user@002dcontact' already exists`

**Comment by annando** [comment]
Okay, dann führe bitte zunächst dieses Kommando aus:
```
ALTER TABLE `user-contact` ADD `uri-id` int unsigned COMMENT 'Id of the item-uri table entry that contains the contact url', ADD `hidden` boolean COMMENT 'This contact is hidden from the others', ADD `pending` boolean COMMENT '', ADD `rel` tinyint unsigned COMMENT 'The kind of the relation between the user and the contact', ADD `info` mediumtext COMMENT '', ADD `notify_new_posts` boolean COMMENT '', ADD `remote_self` boolean COMMENT '', ADD `fetch_further_information` tinyint unsigned COMMENT '', ADD `ffi_keyword_denylist` text COMMENT '', ADD `subhub` boolean COMMENT '', ADD `hub-verify` varchar(255) COMMENT '', ADD `protocol` char(4) COMMENT 'Protocol of the contact', ADD `rating` tinyint COMMENT 'Automatically detected feed poll frequency', ADD `priority` tinyint unsigned COMMENT 'Feed poll priority', ADD UNIQUE INDEX `uri-id_uid` (`uri-id`,`uid`);
```

**Comment by gitkald** [comment]
Query OK, 1 row affected (0.02 sec)
Records: 1  Duplicates: 0  Warnings: 0

Führe ich danach aber /opt/plesk/php/8.0/bin/php bin/console.php dbstructure update erneut aus, kommt dieses:

`ALTER TABLE `user-contact` ADD FOREIGN KEY (`cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE;
[Error] SQLSTATE[42S01]: Base table or view already exists: 1050 Table './friendica_ennimedia/user@002dcontact' already exists`

klar, die Tabelle wurde ja manuell modifiziert.

**Comment by annando** [comment]
Okay, es ist also ein Problem mit dem Foreign Key. Die Frage ist, wie das zu lösen ist ...

**Comment by gitkald** [comment]
Brauchst Du nicht weiter forschen. Ich schalte meinen Knoten ab. Der läuft auf zu alter Software, updaten kann ich nicht, weil da einige Dinge "weiterlaufen" müssen, von daher fahre ich mein Friendica runter. Die letzte Zeit waren nur noch Probleme mit irgend welchen Updates, welche mit dem alter der Softwarestände zu tun haben werden.

Also so long, bis vielleicht irgendwann mal, vielleicht an anderer Stelle.
