### ISSUE TITLE
Profile images issues

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11231]
Hi, I'm experiencing some issues on my Friendica server. I had changed the storage to filesystem, but I made the mistake of deleting it, after I set a new path. Because of that, I ended up corrupting the images that I uploaded to my server, despite the fact that the albums show the image counts, even though they no longer exist. Another strange thing that happened was that some user profile images from other nodes were no longer displayed. 

How can I fix this problem? The weird thing like my profile that uses a gravatar image not display more my photo.

Thanks!

**Comment by annando** [comment]
The images are gone and cannot be recovered. If you dare you could at least try to delete the contact avatar picture. I created a script for a related purpose: https://pirati.ca/local/delete-photo-cache.txt

That script is untested. It should delete all cached avatars. Then slowly they should be restored over time. You need to store that script in the `local` folder and you have to execute it on the webroot.

**Comment by ghost** [comment]
Really he erased everything, but it was worse than before. I don't understand why Friendica is problematic in this. Even the entries for the images that don't exist are still there.

**Comment by annando** [comment]
When you deleted the files, you deleted the content. So the system cannot show you the pictures anymore. It's like ripping all pages of a book - except the index. Then the index will point to pages that don't exist anymore.

**Comment by ghost** [comment]
That I know, but I wanted a solution, not screw it up. I want to know how these images will come back, because not even the remote ones, from other users' profiles, are showing up anymore.

**Comment by annando** [comment]
Your own images are gone, including your profile picture. And with the script at least the remote avatars should reappear.

**Comment by ghost** [comment]
But how long does it take? Well, it's been more than 2 hours and no avatars from my remote contacts have reappeared, even avatars from other networks that aren't my contacts. This problem is happening to everyone, regardless of where they are.

**Comment by annando** [comment]
Which version are you using? With the current release it should work fine. You could also deactivate the caching of remote avatars in the admin settings.

**Comment by ghost** [comment]
I use this version:: 2021.09

Where can I disable avatar caching?

**Comment by annando** [comment]
This is a new feature in 2022.02.

**Comment by ghost** [comment]
I did the update and unchecked the cache related option. Nothing happened, maybe it will happen in a few minutes or hours?

**Comment by annando** [comment]
Please execute this query and report the result:
```
select `photo-type`,count(*) from photo group by `photo-type`;
```
This query returns the different types of photos on your system. When the script went well then there should be no or only a small number of entries with the type "20".

**Comment by ghost** [comment]
![Captura de tela em 2022-02-09 12-23-54](https://user-images.githubusercontent.com/2012588/153232314-750077fa-0228-4079-baa7-14034558829d.png)

**Comment by annando** [comment]
Okay. That means that the script that I linked wasn't executed. This should had reduced the number of entries with the value "20" a lot.

**Comment by Ballagyr** [comment]
Yes, I ran twice. But only now that I used user with administrative credential, before I had not done that. But I will have to wait as I have no connection on my PC. I just got the message that the network is down. As soon as I get back I'll see the result.

**Comment by ghost** [comment]
Yes, I ran this script twice. But only now that I used user with administrative credential, but almost nothing has changed either, only three of my contacts had the avatar restored. The global users had already been restored as soon as I turned off the cache. I don't know what else is missing, I followed all the guidelines. 

![Captura de tela em 2022-02-09 12-50-08](https://user-images.githubusercontent.com/2012588/153237493-74406244-e67b-4237-91f3-192ac6d8f169.png)

**Comment by annando** [comment]
How have you executed this script? And what was the output?

**Comment by ghost** [comment]
As it is a php script I ran this command: `sudo php script.php`
In the output appeared 3 sequences of numbers, probably hashes of the images.

**Comment by annando** [comment]
this script is meant to be stored in the `local` folder and is expected to run from the webroot with `php local/script.php`.

**Comment by ghost** [comment]
That's exactly what I did... Well, if there's nothing more to be done, then I'll end it here. 
Thanks for the help!
