### ISSUE TITLE
Restore thread completion for Like activities behind a setting

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11245]
From https://github.com/friendica/friendica/pull/11240#issuecomment-1040566477

> There is the boolean config variable `accept_only_sharer`. Every occurrence has to be replaced with a new configuration that has got with three options. Then the programming in this PR (in line 650) can be controlled by this new configuration as well.

**Comment by annando** [comment]
I allow you to correct my bad writing in the quote :-)
