### ISSUE TITLE
Twitter unfollow option missing on squeet me

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11254]
While Twitter unfollow option shows as expected on pirati.ca it is lacking on squeet.me when showing contact details for Twitter contacts.

The versions are identical:

This is Friendica, version 2022.05-dev that is running at the web location https://pirati.ca. The database version is 1452/1452, the post update version is 1427/1427.

This is Friendica, version 2022.05-dev that is running at the web location https://squeet.me. The database version is 1452/1452, the post update version is 1427/1427.

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by AlfredSK** [comment]
I guess someone needs to reload the add-on.

**Comment by MrPetovan** [comment]
@annando ? @tobiasd ?

**Comment by annando** [comment]
Okay, done.

**Comment by foss-** [comment]
Thanks so much @annando
