### ISSUE TITLE
PHP Fatal error in logs

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1125]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /var/www/virtual/snarl.de/htdocs/library/dddbl2/handler/register_result_handler.inc.php on line 39

**Comment by silke** [comment]
Is this still open?

**Comment by annando** [comment]
I guess so.

**Comment by MrPetovan** [comment]
The new prepared statements functions introduced in #3389 are effectively closing this issue.
