### ISSUE TITLE
German is recognized as Persian

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11287]
German is recognized as Persian. This is more of an addon problem and it's been around for a long time
![20220301_112320](https://user-images.githubusercontent.com/12480023/156153117-40c71fe1-a4b6-453e-bb86-9bfbaa2e9aa4.png)

**Comment by ghost** [comment]
Okay, that seems to be an adjustment thing...

**Comment by MrPetovan** [comment]
Duplicate of https://github.com/friendica/friendica/issues/11226
