### ISSUE TITLE
Inconsistency of themes for public viewing

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11291]
For my page, TROM, I have selected a different green-dark theme. I would expect any visitors to see my page with that theme. I am talking about public viewing, like someone who is not logged in. And they indeed see my page as such - https://social.trom.tf/profile/trom

![2022-03-03_12-29](https://user-images.githubusercontent.com/38043315/156556050-834969e5-a46a-4634-aa6a-cb59c2e7ede7.png)

But clicking any of my posts, it switches to the instance's default theme https://social.trom.tf/display/dbc8dc44-2562-1d53-c8cf-fc1846121026:

![2022-03-03_12-30](https://user-images.githubusercontent.com/38043315/156556290-57ffd0ad-8499-48bd-937e-c5e344043cd5.png)

I think my posts should also respect the theme I chose, right?

**Comment by MrPetovan** [comment]
That's an interesting point, we've only considered the profile page so far.

What about logged in users, what theme should they see when browsing your conversations? Theirs or yours?

**Comment by tio-trom** [comment]
> What about logged in users, what theme should they see when browsing your conversations? Theirs or yours?

Interesting....this only applies for friendica to friendica users so maybe it can create confusion if the users see a different theme. I'd say for logged in users to respect the theme of the logged-in user. But for sure, for public display it should respect the theme of the account holder. That's the awesome bit about Friendica that we can have our own custom layouts :)

**Comment by MrPetovan** [comment]
We can work with that.

**Comment by futureisfoss** [comment]
Thanks for bringing this up, I was gonna ask about this in the friendica support forum. My public profile page shows my theme when you visit, but my posts don't respect that theme and fall back to the instance default.

Also, new friendica users would expect the app to respect their theme when they're logged in, I'm not sure why this isn't the default behavior now. I had to go to the display settings and enable the option called "Stay local" just for the app to respect my theme and to not leave my instance when visiting other's profiles, I think this option should be enabled by default.

**Comment by tio-trom** [comment]
> I had to go to the display settings and enable the option called "Stay local" just for the app to respect my theme and to not leave my instance when visiting other's profiles, I think this option should be enabled by default.

Yes we have discussed in the past about this. I am all for this. At least allow admins to force that setting by default. I would do that for our instance in an instance :D. Makes a lot more sense. Else people are sent to websites that look different and out of their own instance, and can get very confusing. :P

**Comment by futureisfoss** [comment]
Yeah I agree. As someone coming from mastodon, it was very confusing for me. And even the setting's name "Stay local" isn't very intuitive, I just found this out by trial and error 😄

**Comment by MrPetovan** [comment]
The "Stay local" option is intuitive for new users, but goes against the existing Friendica behavior, which could confuse old users. We may end up switching it on by default for an upcoming release.

**Comment by futureisfoss** [comment]
Friendica allows users to post on other's wall, I asked about this feature on the friendica matrix room to learn how it works. After some testing I found out that this option is unavailable when the "Stay local" option is enabled on your display settings. Its not a big issue for me personally 'cause I don't really use that feature, but I thought I should let you know so other users don't have to go through the trouble.

**Comment by annando** [comment]
@MrPetovan do you still have this issue on your plan for this release or should we move it?

**Comment by MrPetovan** [comment]
I can look into it this weekend, if the release is also planned for this week-end we should move it.

**Comment by annando** [comment]
I'm not sure for when the release is planned. I'm just walking through all issues and have a look if they are blocking issues.

**Comment by MrPetovan** [comment]
PR done: https://github.com/friendica/friendica/pull/11571

**Comment by AlfredSK** [comment]
Hmm. The new behavior is weird in some cases. Example: When I'm logged in to my user account and I click on a notification for a new post of another local user (one of my own news bots) the theme is changing to the configured theme of that other user. This is unexpected from my point of view.

**Comment by MrPetovan** [comment]
There a logged-in setting to always use your own theme when browsing your local node’s users. It used to be confined to profiles but it just got expanded to conversations!

**Comment by AlfredSK** [comment]
> There a logged-in setting to always use your own theme when browsing your local node’s users.

Can you give me a hint where I can find that setting, please? I can't find it.

**Comment by MrPetovan** [comment]
Alright, you're going to laugh (or not). We only retrieve the value of `system.always_my_theme`, but we don't set it (anymore, I presume). Let me dig further.

**Comment by annando** [comment]
I have the feeling as if I introduced that value long years ago without documenting it.

**Comment by MrPetovan** [comment]
Alright, I have more info. The `system.always_my_theme` pconfig value was introduced in June 2015 but 373bb0822b2040d54fc17717840b5adfe15d1223, but only read, never set.

It's never been set ever since that I've been able to see.

I'm thinking about adding this settings in Settings -> Display -> Content/Layout. Thoughts?

**Comment by annando** [comment]
Yeah, like I said. I guess that I introduced it silently :-)

**Comment by AlfredSK** [comment]
> I'm thinking about adding this settings in Settings -> Display -> Content/Layout. Thoughts?

Seems to be a good place.

**Comment by tio-trom** [comment]
Yup I agree with Settings -> Display -> Content/Layout

**Comment by MrPetovan** [comment]
> Yeah, like I said. I guess that I introduced it silently :-)

It was Rabuzarus actually, you’re off the hook on this one.

And I’ve been suggested the setting is too confusing, better to assume logged in users don’t want or expect the theme to change when they visit other local users.

This would simplify the coding and reduce the number of future support requests!

**Comment by tio-trom** [comment]
Yes logged in users should not be forced to see the user's custom theme. That's why I was suggested this for public viewing (non logged in users).

**Comment by MrPetovan** [comment]
Of course, but I remembered seeing this setting before, so I thought it was intended to be user-configurable. Removing it was the simpler solution.
