### ISSUE TITLE
Pinned post not working

### ISSUE THREAD

**Issue by futureisfoss** [friendica/friendica#11310]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Pinned post not showing in my public profile.

### Steps to Reproduce

1.  Pin a post on your account.
2.  Open incognito mode in your browser and go to your public profile page, check if your pinned post is shown correctly.
3.  Try visiting your account from mastodon, check if your pinned post is shown correctly.

Actual Result:

There are no pinned posts shown when visiting the public profile from a browser or from mastodon.

Expected Result:

Pinned posts should be shown as pinned, both when visiting from a browser or from mastodon or other federated platforms.
Note: #10427 addresses the federation of pinned posts.

### Platform Info

Friendica Version:

This is Friendica, version 2021.09 that is running at the web location https://social.trom.tf. The database version is 1434/1434, the post update version is 1427/1427.

**Comment by tobiasd** [comment]
Confirmed on my node running Friendica 2022.05-dev
