### ISSUE TITLE
Respect Forwarded-For headers in log file

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11317]
I've set up my friendica instance behind a nginx reverse proxy.

Looking into the friendica log searching for failed logins, I see that the original IP is not available. This is the log line I found:
`2022-03-11T11:45:33Z index [WARNING]: authenticate: failed login attempt {"action":"login","username":"errewr","ip":"10.0.2.100"} - {"file":"Authentication.php","line":261,"function":"withPassword","uid":"bf0e28","process_id":123}
`
10.0.2.100 is the proxy address of the podman stack. I believe, docker is doing something similar and even just with a plain setup behind a reverse proxy it would be the proxy's ip address.

I request to add the original callers ip into the log line. This is neccessary to identify it for using fail2ban or Crowdsec.

As an example: Nextcloud uses the trusted-proxy array in it's configuration to determine if the original ip or the one in Forwarded-For header is to be logged as remote address (if ip is in trusted proxy use Forwarded-For header, otherwise senders ip).

**Comment by ne20002** [comment]
Ok, I solved it by using mod_realip in nginx. Not soo elegant, but a suitable solution to me.

**Comment by MrPetovan** [comment]
Thank you for the follow-up and the updated issue, do you think it would still be a good avenue to explore? It requires additional setup (the trusted proxy configuration) but it could be worthwhile for people not using `mod_realip`.

**Comment by nupplaphil** [comment]
I'm for it, because popular reverse proxies are behaving like that and yesterday, I was exploring new cluster methods (service mesh) and they're using this method for relsaying data as well.. I think I'll add a PR for it :D

**Comment by ne20002** [comment]
Thank you very much. :)
