### ISSUE TITLE
Notifications for BCC message threads

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11315]
- [x] I have searched open and closed issues for duplicates

### Bug Description

On Friendica 2022.05-dev e3025c2c151135bf69078a0007edc8389900c4e6 I've started to get notifications about new answers in threads I'm involved only as a BCC receiver--neither was I mentioned nor did I reply to the thread. The thread was started on a different Friendica node and is private.

Before today, I would not have gotten any notifications about new answers in the thread. I'd expect it to stay like this.

### Screenshot

![grafik](https://user-images.githubusercontent.com/433490/157871271-f946f2ea-d5d1-47d5-80b3-e6298f961c15.png)

**Comment by annando** [comment]
The situation is different. In the starting post you had been in BCC. Then it happened that in some comment the receivers had been transferred to the "to" header. And "to" always triggers a notification - which is the correct behaviour.

**Comment by tobiasd** [comment]
Yes, the BCC receivers list is leaking to the web interface.

**Comment by tobiasd** [comment]
From the receivers information behind the lock (TO, CC, BCC) it was Andreas Posting "Sorry..." which first included me in the To field. All messages before in the thread show me in the BCC field.

**Comment by annando** [comment]
In fact is it not "the BCC receivers list is leaking to the web interface" but: "The sending site used 'to' instead of 'bcc' this time". BCC data isn't transmitted.

**Comment by tobiasd** [comment]
Honestly, that does not sound that much better ;-)

**Comment by annando** [comment]
I can reproduce it. It's slightly weird: You have to create a non public post. Then you have to reply to your post. Then by sudden all receivers are now in the "to" header.

**Comment by MrPetovan** [comment]
Being able to reproduce it is the first step to a fix!
