### ISSUE TITLE
Share notifications don't generate a message

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11338]
Found while working on #11336

> I also found a notification that doesn't have a message, it's a share notification with the following verb: `https://www.w3.org/ns/activitystreams#Announce`
https://github.com/friendica/friendica/pull/11336#issuecomment-1067501219

This causes them not to appear in the notification menu.

**Comment by MrPetovan** [comment]
Some share notifications are getting a message, so I have to look into the specifics of the ones that do not.

**Comment by annando** [comment]
Is this still an issue?

**Comment by MrPetovan** [comment]
Since notifications now are correctly governed by the user notification settings, I haven't been able to figure out missing share notifications since I don't enable them on my personal account. Closing for now.
