### ISSUE TITLE
Timeline is no longer updated automatically.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11335]
Latest dev

Can someone confirm that when you are at the last post in the timeline in the web browser, the timeline is no longer updated according to the value specified in the admin settings?

**Comment by MrPetovan** [comment]
Is this with infinite scrolling?

**Comment by ghost** [comment]
> Is this with infinite scrolling?

No

**Comment by MrPetovan** [comment]
When you say the last post, do you mean the top of the page?

**Comment by ghost** [comment]
> When you say the last post, do you mean the top of the page?

Yes, the latest post

**Comment by MrPetovan** [comment]
Ok, thanks for the elaboration. I think I can confirm? I use the same setting, auto-update only at the top of the page, and I've had to refresh manually to see new posts.

**Comment by MrPetovan** [comment]
Ha, the `ping` command returns 500 error, I'm on it.

**Comment by MrPetovan** [comment]
I fixed this issue, and now I'm getting notifications for received likes, oh no!

**Comment by ghost** [comment]
Still not working for me

**Comment by MrPetovan** [comment]
You need to force-refresh your network page, changes have been added to the `main.js` file but it's cached by default until the next release.
