### ISSUE TITLE
No notification about new postings by specific contact

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11339]
Caused by  #11273

### Bug Description

One can specify to get a notification when a specific contact has posted something new. This notification does not work for me at the moment.

### Steps to Reproduce

1.  Activate the "Notification for new posts" in the contacts settings
2.  Wait for new posting by them

Actual Result:

I don't get a notification.

Expected Result:

Get notification about new postings.

### Platform Info

Friendica Version: 2022.05-dev e252b5972eea78ca1659cae8e1c7ca16bcc22503

Friendica Source: git

PHP version: 8.0.16

SQL version: 10.5.12-MariaDB

**Comment by tobiasd** [comment]
When I visit the page `notifications/system` the notification is shown. But they are not shown in the notification drop-down in frio or vier.

**Comment by MrPetovan** [comment]
Thank you for the report, the `notifications` page still uses the deprecated `notify` table while the notification dropdown uses the newer `notification` table, which explains the discrepancy.

**Comment by MrPetovan** [comment]
I was just able to test this between my main node and my dev node without changing anything to the code. I'll need more information on your end to debug this.

**Comment by MrPetovan** [comment]
Yeah, I tested this with a heavy poster contact of mine and it definitely works, I have 15 new notifications now including 13 from him sharing new posts.

**Comment by tobiasd** [comment]
Ok, I'll have a look. Maybe it is fixed in the meantime or was a caching problem. Thanks for having a look!

**Comment by MrPetovan** [comment]
Of course, thanks for the report again!

**Comment by tobiasd** [comment]
Confirmed, works again :)
