### ISSUE TITLE
Wrong notification text for threads

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11340]
Caused by https://github.com/friendica/friendica/pull/11273

### Bug Description

In the email notification send about replies to a forum thread, the text for the notification was wrong. The text was that the commenter replied on their own posting, and not the posting of the original author.

**Comment by tobiasd** [comment]
This happens in other threads as well. Seen in a shared AP thread  where I'm not following the original author, but the top posting of the thread was reshared by a contact and another contact replied to the thread. The notification read, that the commenter replied in their own thread.

**Comment by MrPetovan** [comment]
Thank you for the report, although I haven't been able to witness this for forum threads. There definitely is something funky going on with the messages.

**Comment by tobiasd** [comment]
Just noticed, it is not only for forum threads that this wrong text is used in the notifications. It also happens in conversations where the initial posting was reshared by a contact, but the initial author is not followed directly by me.

**Comment by MrPetovan** [comment]
Thank you for the added information!

**Comment by tobiasd** [comment]
Seems to be fixed in the mean time :)
