### ISSUE TITLE
Add *~ files to .htaccess exclusion

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11350]
From someone I will not name to protect their reputation:

> So, I just found out that my mail credentials were compromised this morning. After some digging, it seems that I made a critical mistake when setting up my Friendica node.
> 
> It's not, strictly speaking, an issue with Friendica, but there is perhaps something that can be done to prevent others from making the same mistake.
> 
> So here's what happened: I use Emacs, which leaves behind "backup" files when editing. This left a config/addon.config.php~ file that could be viewed by anyone who deliberately navigated to it.
> 
> I'm sure I'm not the only person to have done this. Can I request a change to the .htaccess file be made to block access to *~ files? It would protect future idiots like me from shooting themselves in the foot.

I don't remember how to do this in the `.htaccess-dist` file, can anyone with fresher memory take this on or provide pointers?

**Comment by tobiasd** [comment]
Yes... let me check something

**Comment by tobiasd** [comment]
I've only checked accessing files like `test~` and `.test.swp` in 11351, but only in the top-level directory and I've not checked for hazardous side-effects. Normal access to Friendica works with the the block added.

**Comment by MrPetovan** [comment]
Hmm, this is especially about the `config` subfolder, but I don't feel like pushing too much.

**Comment by MrPetovan** [comment]
Closed by #11351

**Comment by tobiasd** [comment]
File in subfolders are covered as well by the block. I cannot really think about why a file matching one of the patterns would be named the way but intended to be accessed. And if, the author does most likely know/finds the Apache config files at some point.

**Comment by nupplaphil** [comment]
Btw. Since the last release, we're able to define an alternative config path outside of the www path per environment variable. So no direct access would be possible at all

**Comment by MrPetovan** [comment]
That's good, but wouldn't it be applicable to Docker installs only?

**Comment by nupplaphil** [comment]
It's applicable on every system :) but yes, I introduced it for docker. Tbh but I don't actively use it yet, it's on my to-do list

But as said, even for any other system, it works:
https://github.com/friendica/friendica/blob/2703fd50fccde9ceb6f05eb3c6d1aac30e8c1649/src/Core/Config/Factory/Config.php#L37

**Comment by MrPetovan** [comment]
Good to know, I'm not sure where we can talk about this feature but it's nifty.

**Comment by tobiasd** [comment]
Does it need to be setup during install? Or can it be added to the configuration later on?

**Comment by nupplaphil** [comment]
I'll add a doc PR for it :)

Yes it's applicable after an installation as well, just copy the content to the new destination and set the env. If it's working as expected, delete the `config/*.config.php` files aaaand done :)

**Comment by MrPetovan** [comment]
The tricky part is that your web server user needs to have read access in the separate folder which is often a given in the existing `config` folder if the root `index.php` is readable.
