### ISSUE TITLE
Remove "<Forum> reshared this" above each comment in a forum thread

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11353]
Caused by #11268

All the comments are reshared by the forum by definition, there's no use for this label in this context.

**Comment by annando** [comment]
I see it as a good indicator that the forum distribution worked.

**Comment by MrPetovan** [comment]
Got it, but I don't think we should leave debug display on after it served its purpose. And if a forum conversation is missing a post, this display won't tell you that.

**Comment by annando** [comment]
Well, when someone tells "aren't my forum comments distributed" then it helps the support. An indicator is needed here.

**Comment by MrPetovan** [comment]
Either the posts show (they are distributed to their non-followers) or they don't (they aren't distributed to their non-followers), this display that is a quirk of the forum implementation doesn't help in that regard.

**Comment by annando** [comment]
This is an indicator if that comment arrived at the forum server and had been processed and distributed. Also it currently helps in pinning down some possible distribution that I have to have a look at. So changing anything here at the moment would be contra productive.

**Comment by MrPetovan** [comment]
Alright, now it is getting ridiculous, this mention is shown twice, at both the top and bottom of the forum replies:
<img width="598" alt="Screen Shot 2022-05-09 at 14 41 27" src="https://user-images.githubusercontent.com/925415/167475999-d6c07724-5491-41d1-8d1c-30f015784e06.png">

One mention was already clutter, two makes the conversation barely readable.

**Comment by annando** [comment]
Yeah, that is a side effect of one of my performance changes. I know where to look, it's on my list.
