### ISSUE TITLE
frio: mobile: notifications not showing

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11386]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Notifications do not show when selecting notification icon with unreal notifications.

### Steps to Reproduce

1. Open friendica with frio theme on mobile
2. tap notification icon with unread notifications

Actual Result:

The notification panel opens but no notifications are shown.

Expected Result:

Notifications should show.

### Screenshots

![--](https://user-images.githubusercontent.com/5708172/161294994-131314b8-cf59-4c8f-b93f-abacf01e087f.PNG)

### Platform Info

This is Friendica, version 2022.05-dev that is running at the web location https://pirati.ca. The database version is 1453/1453, the post update version is 1452/1452.

**Comment by AlfredSK** [comment]
Please clear your browser cache (in the browser settings).

**Comment by foss-** [comment]
It's always the cache is it? Thanks!
