### ISSUE TITLE
Blank space or line in .well-known/host-meta, is that normal?

### ISSUE THREAD

**Issue by scarlet-tobar** [friendica/friendica#11383]
Thank you for your time.
I have an instance but its .well-known/host-meta is not working well it seems. When I go there from chrome it says:
`This page contains the following errors:
error on line 2 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.`

I'm in Friendica 2022.03, php 7.4.3, Ubuntu 20.04.4 LTS and nginx.
Is that normal? Other Friendica instances don't seem to have this problem.

**Comment by MrPetovan** [comment]
Thank you for your report, would you mind sharing the URL to your Friendica node since it seems to be a local issue?

**Comment by scarlet-tobar** [comment]
friendica.chilemasto.casa

Thank you.

**Comment by MrPetovan** [comment]
Thanks, I can see the leading blank line in https://friendica.chilemasto.casa/.well-known/host-meta, compare with my own host-meta output: https://friendica.mrpetovan.com/.well-known/host-meta

I'm not sure where this blank line comes from, but I'm pretty sure Friendica itself doesn't add it. I can see this blank line added to all the other pages I've tried, so it might be your web server configuration. I know PHP allows to include script after and before the execution of the website's script, do you know if your webserver configuration might have been altered?

**Comment by scarlet-tobar** [comment]
Nginx has a similar configuración to the one in mods, and i haven't preloaded anything to PHP, so i don't know what can it be

**Comment by annando** [comment]
Please check your config files. Possibly they contain this space.

**Comment by scarlet-tobar** [comment]
I've checked php.ini and nginx config files, what else can I check?

**Comment by annando** [comment]
I meant the Friendica config files. 

How have you installed Friendica? Via git or via downloading the files?

**Comment by scarlet-tobar** [comment]
I installed Friendica via git, I'll check.

**Comment by scarlet-tobar** [comment]
There was an space in addon.config.php, now it is fixed.
Thank you for your help. I'll close this.
