### ISSUE TITLE
no post preview

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11393]
- [x] I have searched open and closed issues for duplicates

### Bug Description

It seems, the post preview is broken. It shows nothing and the browser console (firefox) displays an 'Error 500'.

```
POST https://libranet.de/item
[HTTP/2 500 Internal Server Error 191ms]
```

### Steps to Reproduce

1.  compose new post (open the modal window)
2.  write some text
3.  click the preview tab

Actual Result:

shows no preview

Expected Result:

the post preview should appear

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2022.05-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1453/1453 und die Post-Update-Version 1452/1452."

Theme: Frio V.0.8.5

**Comment by tobiasd** [comment]
I can confirm this using vier on 2022.05-dev 29f65d250f64457510f8ef6dbd795536da66e41a
