### ISSUE TITLE
Preview and resulting post show different photos

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11405]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I wanted to share this link ( https://www.mdr.de/nachrichten/sachsen-anhalt/podcast-digital-leben-mastodon-fediverse-uni-magdeburg-softwerke-100.html ) and in the preview the photo was another one then in the resulting post.

### Steps to Reproduce

1. open the modal window to create a new (public) post
2. paste above link
3. click preview
4. publish the post and compare the photo to that from the preview 

Actual Result:

a blue image with 3 heads on it
`https://libranet.de/photo/preview/600/25910684`

Expected Result:

the grey photo with a mastodon screenshot on it. (which seems to be the og:image)
`<meta property="og:image" content="https://cdn.mdr.de/nachrichten/sachsen-anhalt/screenshots-mastodon-machteburch-social-fediverse-softwerke-100_v-variantBig16x9_wm-true_zc-ecbbafc6.jpg?version=46368">`

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2022.05-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1457/1457 und die Post-Update-Version 1452/1452."
Theme: Frio

**Comment by MrPetovan** [comment]
Hmm, I'm not able to reproduce this issue, the preview image in the post composer was the same as the image it ended up posting. 

Composer:
![friendica-link-preview-composer](https://user-images.githubusercontent.com/925415/167302759-a9713a29-fcb0-4573-92f5-a9091c298732.png)
Resulting post:
https://dev-friendica.mrpetovan.com/display/b5f438f2-1762-77dd-8890-587505761414
![friendica-link-preview-post](https://user-images.githubusercontent.com/925415/167302760-ac0f29a5-42c1-4b31-9b11-82eca4818570.png)

**Comment by haheute** [comment]
Hm yes. seems to work now.
I have just tried and have the same image in both cases, too. Don't know what that could have been, before..

**Comment by MrPetovan** [comment]
Thank you for the follow-up, if you experience the same issue with a different link, please feel free to reopen this issue.
