### ISSUE TITLE
Getting post from contact i unfollowed

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11406]
Still getting posts from people on my server that I used to follow but have now unfollowed.

Can anyone confirm this behavior?

**Comment by ghost** [comment]
steps to reproduce it.
1. Subscribe to a person whose account is a Barker account (with auto accept followers) on your server.
2. Wait for him to post.
3. Unsubscribe him.
4. Will his posts still show up in your timeline?

**Comment by copiis** [comment]
Okay, since the other contact declined my follow-up request, his posts also disappeared from my timeline.

But I don't think that's the way it's supposed to work.

**Comment by ghost** [comment]
Okay, since the other contact declined my follow-up request, their posts also disappeared from my timeline.

But I don't think that's the way it's supposed to work.

**Comment by MrPetovan** [comment]
What's the "follow-up request"?

**Comment by ghost** [comment]
It seems that after message queues shrunk, the problem went away.
