### ISSUE TITLE
Ability to post in the past

### ISSUE THREAD

**Issue by schmaker** [friendica/friendica#11410]
It would be nice to have ability to set post date in the past. 

It is good for migrating people or (for example) "timelines" with pictures of kids.

**Comment by annando** [comment]
Technically this is no problem at all. But: These posts will be ordered after the date they had been received on the system.

**Comment by MrPetovan** [comment]
I think it's fine, we show both dates (published/received) anyway.

**Comment by schmaker** [comment]
To be honest, behavior i would expect is, that on the public timeline
it would be shown when server receives the post, but when i chose posts
at the user profile (for
example https://schmaker.eu/profile/schmaker/status?category=auta), the
posts will be ordered according to date of creation, not the date of
publishing. At least in my guessed use case. Not sure if it will work
this way or it is implementable somehow.

**Comment by MrPetovan** [comment]
This is exactly how it would work in Friendica.

**Comment by schmaker** [comment]
Well then, looking forward to trying it 

Where can i buy you guys a beer? :D

**Comment by annando** [comment]
@schmaker  Either in the US or in Germany :beer:

**Comment by annando** [comment]
There is now a PR for an experimental feature. There are some rough edges. Because of this, the feature has to be enabled manually in the config file by now.

**Comment by schmaker** [comment]
Seems like I'm unable to reopen this issue, please someone else reopen this.

At least since 2023.4 (maybe one more release back) I am not able to set custom creation date anymore.

**Comment by schmaker** [comment]
My bad, it's actually moved from full-sized composer to window, did not noticed.

![image](https://github.com/friendica/friendica/assets/14954032/bd6ce92c-441c-48f7-9770-5c130a42f2f6)

**Comment by MrPetovan** [comment]
It should also show in the `/compose` page, if it doesn't it's a bug or a half-baked feature.

**Comment by schmaker** [comment]
Just in case anybody wonders why it does not work anymore after update `'set_creation_date' => true,` is now moved to `system` section instead of `config`

It took me a while to find out :)
