### ISSUE TITLE
Incorrect ids of ActivityPub follower/following collection pages

### ISSUE THREAD

**Issue by gediminasel** [friendica/friendica#11427]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Example followers collection page ([from here](https://friendica.me/followers/doweio?page=1)):

```
{
  "@context": [not important],
  "id": "https://friendica.me/followers/doweio", // here
  "type": "OrderedCollectionPage",
  "totalItems": 18,
  "next": "https://friendica.me/followers/doweio?page=2",
  "partOf": "https://friendica.me/followers/doweio",
  "orderedItems": [not important]
}
```

Ids of collection pages should be unique (and probably equal to the request URI, i.e. contain `page` parameter) as described in [ActivityStreams](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-collectionpage)

### Steps to Reproduce

1.  query followers/following collection page of any friendica user using ActivityPub API.
2.  take a look at the `id` field

**Actual Result:**

```
{
  "@context": [not important],
  "id": "https://friendica.me/followers/doweio",
  "type": "OrderedCollectionPage",
  "totalItems": 18,
  "next": "https://friendica.me/followers/doweio?page=2",
  "partOf": "https://friendica.me/followers/doweio",
  "orderedItems": [not important]
}
```

**Expected Result:**

```
{
  "@context": [not important],
  "id": "https://friendica.me/followers/doweio?page=1", // here
  "type": "OrderedCollectionPage",
  "totalItems": 18,
  "next": "https://friendica.me/followers/doweio?page=2",
  "partOf": "https://friendica.me/followers/doweio",
  "orderedItems": [not important]
}
```

### Platform Info

Friendica Version:

Tested on `friendica.me`: 
This is Friendica, version 2022.03 that is running at the web location https://friendica.me. The database version is 1452/1452, the post update version is 1452/1452.

Friendica Source:

**Comment by MrPetovan** [comment]
Thank you for the report!
