### ISSUE TITLE
Only show a users pinned postings as pinned, not reshared postings as well

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11431]
### Bug Description

When resharing a posting that is pinned by the original author, it is shown pinned at the users status page.

### Steps to Reproduce

1.  Share an AP posting that was pinned by the author
2.  Have a look at your status page
3.  The shared posting is listed first within your postings and is marked as pinned.

Expected Result:

Only postings of the user should be shown as pinned.

### Screenshots

![Screenshot of my status page. Showing one of my own pinned postings, followed by a pinned posting from the PeerTube releases](https://user-images.githubusercontent.com/433490/164401842-a9cebbd4-b7f0-4e3a-b53d-10fc19684ed6.png)

The second posting that is shown on the screenshot was pinned by the PeerTube account, but is shown as pinned on my personal wall.

### Platform Info

Friendica Version: 2022.05-dev 70392df68d4e5e0881c1184e7d368593ccfa7068

Friendica Source: git

**Comment by foss-** [comment]
Also seeing this and was really unsure as to what was going on. Had a nice developer from USA point me in the right direction of this existing issue.

**Comment by igor-cali** [comment]
I am also affected by this on [Nerdica](https://nerdica.net) pod:
- code version: `2022.05-rc`
- database version: `1460/1460`

The following reshared post is shown on top of my profile, before my truly pinned posts and most recent ones:
![immagine](https://user-images.githubusercontent.com/12466054/169373886-71c0c99f-fd9a-45fa-8414-389613bf693e.png)

**Comment by MrPetovan** [comment]
Thank you for the report!
