### ISSUE TITLE
Use original Mastodon App with Friedica.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11432]
The original app for Mastodon is now also available for Android. here
https://play.google.com/store/apps/details?id=org.joinmastodon.android
Would it be possible to make Friedica usable for this app as well?
At the moment there is still an error message when logging in.

**Comment by tobiasd** [comment]
Which error message is reported?

**Comment by ghost** [comment]
> Which error message is reported?

After entering the domain, the message "Missing parameters" appears

**Comment by tobiasd** [comment]
Duplicate of #11415, closing this.
