### ISSUE TITLE
Federation with owncast user is not working

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#11442]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

[Owncast](https://owncast.online/) has just enabled fediverse feature which works nice with Mastodon but is having trouble with Friendica. When looking for a user like mine: `@valvin@live.valvin.fr` in search it doesn't find it and on contact it returns a message like "impossible to detect the network type. this contact cannot be aded".

### Steps to Reproduce

1.  go to a owncast server with federation enabled : https://live.valvin.fr for example
2.  click on fediverse logo and enter your federate username. it will redirect you to an url like: `https://yourserver.tld/follow?url=https://live.valvin.fr/federation/user/valvin`
3. see the error message

or in contact tab:

1. enter an owncast user : ex : `valvin@live.valvin.fr`
2. see the error  message

Actual Result:

contact is not added and we can't see the message it publishes

Expected Result:

add the contact and display the message in the feed

### Screenshots

![image](https://user-images.githubusercontent.com/1267915/165075769-403a348b-b6af-4997-9303-ec6d34ebca3b.png)

### Platform Info

Friendica Version:

Friendica Source: 2022.03

PHP version: 7.4.29

SQL version: MariaDB - 10.3

**Comment by Quix0r** [comment]
If I search for this user on `develop` branch, I get an URL like https://f.haeder.net/search?q=%40valvin%40live.valvin.fr which means Friendica has tried to search for it as a text, not as a user. If I try to add it under `/contact`, I get the same result.

**Comment by tobiasd** [comment]
See also this thread in the Friendica Support forum: [/display/c35d279b-3162-6469-7387-cef819412823](https://forum.friendi.ca/display/c35d279b-3162-6469-7387-cef819412823).

**Comment by gabek** [comment]
Hi there, is there anything that the Owncast project can do to help?

**Comment by Quix0r** [comment]
The related issue in owncast project had been closed. :-(

**Comment by cracrayol** [comment]
Seems to work now (on 2023.03-rc branch).
I've been able to add valvin@live.valvin.fr directly from friendica, or by using follow link on the owncast page.

**Comment by gabek** [comment]
Fantastic news, thanks for the update!
