### ISSUE TITLE
Twitter: Add existence check for connector accounts and remove non existent one

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11459]
**Currently**

When a twitter account no longer exists there is no way to revoke share. Since there is no check for existence there is also no way to fully remove that account. Unfollowing is possible but that will leave that account as an account with which the user is sharing.

**Expected**

In the batch actions there is an option to `Update` a contact. This could check existence for twitter accounts and if they no longer exist, inform user about that fact and remove the account from contact list.

There is no point in sharing with non existant accounts and no new posts will be received.

**Comment by foss-** [comment]
Obsolete due to the fact, that `The Twitter addon is deactivated now, since Twitter has sunsetted the 1.1 API access.`

**Comment by MrPetovan** [comment]
On the contrary, it seems like it's more relevant than ever since the connector will be disabled more than usual.

**Comment by foss-** [comment]
Good point, however @annando mentioned such left-over contacts to be gone with the addon deprecation. And I can confirm that when checking my contacts: a search for `Twitter` brings up no results.

**Comment by MrPetovan** [comment]
Oh, I didn't realize disabling the addon hid the Twitter contacts. I believe the total count shown in the Contacts page may be wrong in that regard, the contacts are just hidden, not removed.

**Comment by foss-** [comment]
Follow-up about follower numbers: https://github.com/friendica/friendica/issues/13289

Lets keep the issue here open as the initial problem could also exist with other connectors / addons.

**Comment by foss-** [comment]
Lets close this one. If this persists with other connectors please file a new issue.
