### ISSUE TITLE
Wrong Notification about dislike

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11469]
### Bug Description

I've got a notification about a dislike to one of my postings, even though I choose to be not notified about likes.

For me likes and dislikes have the same "value" to a posting. So my assumption was that I wont get a notification for either of them when I opted out in the settings.

### Steps to Reproduce

1.  Unselect "Someone liked your content" in the user settings (Notifications)
2.  Find someone who dislike your content
3.  Get a notification

Actual Result:

The notification about the dislike was send, although I choose to not get notifications about likes. 

Expected Result:

Only get the notification about a dislike when one gets a notification about a like.

### Platform Info

Friendica Version: git / 2022.05-rc

**Comment by tobiasd** [comment]
Today I got an notification about a dislike again.

**Comment by annando** [comment]
In the notification link there is some integer value. Please have a look into the `notification` table with an `id` with that value and post the result here.

**Comment by tobiasd** [comment]
I don't see a way in the browser to make this information visible... neither Firefox nor Chromium seem to display the link from the dynamically filled JS pull-down menu. I'll activate the server log later and then try to catch the notification URL from that.

**Comment by tobiasd** [comment]
```mysql
MariaDB [friendica]> select * from notification where id=5735;
+------+------+------+------+----------+---------------+---------------+---------------------+------+-----------+
| id   | uid  | vid  | type | actor-id | target-uri-id | parent-uri-id | created             | seen | dismissed |
+------+------+------+------+----------+---------------+---------------+---------------------+------+-----------+
| 5735 |    2 |    2 |    8 |   240084 |       2944441 |       2943558 | 2022-05-27 11:59:38 |    1 |         0 |
+------+------+------+------+----------+---------------+---------------+---------------------+------+-----------+
```

**Comment by annando** [comment]
Concerning the notifications: Where do you receive them? Do you see them on the desktop or via mail?

**Comment by tobiasd** [comment]
It's only in the web interface, no mail was send.
