### ISSUE TITLE
New follow request notifications don't seem to be translatable

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11461]
On current develp new follow request notifications are not translated:
![image](https://user-images.githubusercontent.com/35988439/166123636-460ffe89-b041-4a71-b7d7-d1e03cbc6cee.png)

The only `wants to follow you` string in Transifex is translated.

**Comment by tobiasd** [comment]
More likely your work has not been transferred from Transifex to the development branch since you translated the strings ;-) I have some notification mails marked as unread to remind me about transfers that have to be done for the release.

**Comment by SpcCw** [comment]
@tobiasd the thing is there are no new untranslated strings like `wants to follow you` in Transifex and the old one was translated long ago and didn't change since then.

So I wonder if it is just some glitch?

UPD: I see it was changed 15 days ago so you are right. I'll wait for the changes then :)

**Comment by tobiasd** [comment]
No, no glitch, just me not have updated the translations for a "long time". It is in [the pull request 11463](https://github.com/friendica/friendica/pull/11463/files#diff-f5b6d4dca5db55c2950c88b024a105c8392bff5f8ec62b41134fe936d9e92d9eR2167) (eventually you have to hit the "Load Diff" button for the `view/lang/ru/strings.php` file).
