### ISSUE TITLE
API: allow control over when a posting is published

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11478]
### Describe the feature you'd like

#11411 introduced the possibility to set the date of a posting in the past. In addition we have scheduled postings for some time now in the web interface of Friendica.

It would be great to have these features available in the API as well.

**Comment by annando** [comment]
We are supporting it via this endpoint: https://docs.joinmastodon.org/methods/statuses/#create

**Comment by annando** [comment]
I guess that we can close it, since we support it?
