### ISSUE TITLE
No notification about postings to forums

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11471]
### Bug Description

One can opt-in to be notified about postings of a contact. This used to be working, when a posting arrived via a forum (e.g. the helpers forum), but it is not the case anymore.

### Steps to Reproduce

1.  Join a forum
2.  Select the _I want to be notified about new postings by this contact_ option in the contact settings
3.  Wait for a posting in the forum.

Actual Result:

No notification is raised.

Expected Result:

Being notified about new postings to the forum.

### Platform Info

Friendica Version: git / 2022.05-rc

**Comment by annando** [comment]
In the notification link there is some integer value. Please have a look into the `notification` table with an `id` with that value and post the result here.

**Comment by annando** [comment]
Currently I can't reproduce it, it is working here really fine.

**Comment by tobiasd** [comment]
I've disabled the option for a bunch of forums and enabled it again, lets see what happens.

**Comment by tobiasd** [comment]
Sadly, that did not fix it.

There was a new posting to the suipport forum, but I did not get a notification about it.

**Comment by annando** [comment]
And I got it, weird.

**Comment by tobiasd** [comment]
Ok, I've moved this issue to the 2022.08 milestone, if it is only broken on my node, we don't need to delay the release for this.

**Comment by annando** [comment]
Possibly it has got something to do with the detailed notifications. I guess you have enabled them, haven't you?

**Comment by tobiasd** [comment]
Yes I have activated them, and I have not ignored any of the forums I like to get notifications about.

**Comment by annando** [comment]
Can you disable the detailed notifications to check if this does make a difference?

**Comment by tobiasd** [comment]
Yes, I did not get a new notification for the new support forum posting ;-)

**Comment by annando** [comment]
At least we now know what *isn't* responsible ...

**Comment by tobiasd** [comment]
For testing something else, I've installed an Android client on the phone. There the notification about a new posting to the _helpers_ and _developers_ forum was received. In the browser, using `vier` it is missing.

**Comment by annando** [comment]
Does this still occur? And does all other notifications take place?

**Comment by tobiasd** [comment]
It works now again... think for about a week or so? sorry I've forgotten to close the issue
