### ISSUE TITLE
Accounts on IDN domains are not found

### ISSUE THREAD

**Issue by Ravenbird** [friendica/friendica#11487]
When I search for a user whose account is on an [IDN domain](https://en.wikipedia.org/wiki/Internationalized_domain_name), the user is not found. As an example, @Umweltministerium@bawü.social is not found. However, if I search for @Umweltministerium@xn--baw-joa.social, then it works without any problems. I can still find that out somehow, even if it is cumbersome. But a normal user will not be able to handle it.

**Comment by MrPetovan** [comment]
Interesting, thank you for the report!
