### ISSUE TITLE
Responding to posts CWed with hashtags breaks CWs

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11504]
While responding to (ActivityPub?) posts with hashtags used for CWs, the resulting post will contain broken markup code:

![8370442](https://user-images.githubusercontent.com/685879/168420305-fbac06dd-38fb-45b8-8ee5-66afe1fd635c.jpeg)
 
Is there a way to fix this?

**Comment by annando** [comment]
Can you provide the links to the post you replied on and the reply?

**Comment by MrPetovan** [comment]
Caused by https://github.com/friendica/friendica/pull/11476
Related to https://github.com/friendica/friendica/issues/11445
