### ISSUE TITLE
Domain Name Change

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [friendica/friendica#11511]
I have had to switch domains from www.xxx.tk to www.xxx.org since my .tk domain was lost. I have read that changing domains is supported but I cannot find any instructions on how to do it. I tried to set the ENV VAR FRIENDICA_URL=https://www.xxx.org but it has no effect on an existing docker installation.
Thanks for your help.

**Comment by MrPetovan** [comment]
There's a field in the Admin -> Site section called "Relocate Instance".

**Comment by ThRPctmylSgltwH** [comment]
I no longer have access to the original domain to login and change it in the web interface. I can only see a text version of the login page but cannot login. Can I either,

- force ENV VAR FRIENDICA_URL=https://www.xxx.org to be used upon docker redeploy
- edit a php file to change the domain like I have done with WordPress
- run a script within the docker container or on the server to change the domain
- login through my local network at 192.168.0.xxx:yyyy directly to the Admin page to make the change. Currently this also only leads me to a text only login page and when I try to login it tries to use the old domain and fails.
- Or are there instructions on how to change it directly in the database?

The issue is that my free domain at .tk was taken back by the registrar and I have now purchased a domain but do not want to lose the data already posted by my family.
Thanks for your great work with Friendica

**Comment by MrPetovan** [comment]
So, you would have to manually perform what we do in the code for relocation: https://github.com/friendica/friendica/blob/ee05bd91a3ad97ce2a348f4095a6a6492a58e7cf/src/Module/Admin/Site.php#L75-L123

It isn't trivial given all the tables and the fields that need to be changed, and all the notifier tasks that have to be sent for each user account.

I'd say running a script closely inspired by these lines is your best bet. Let me know if you need help with this.

**Comment by tobiasd** [comment]
> I'd say running a script closely inspired by these lines is your best
> bet. Let me know if you need help with this.

Not apply-able for the problem at hand, but maybe we should expand the bin/console tool with this functionality.

**Comment by MrPetovan** [comment]
Why isn't it applicable? Replacing the user-provided new domain name input with a static value should do the trick.

**Comment by tobiasd** [comment]
I meant "it is not a solution ready to use at the current time".

**Comment by MrPetovan** [comment]
Indeed, it needs some manual work to write the script.

**Comment by tobiasd** [comment]
Which Friendica version are you running in the docker container @ThRPctmylSgltwH ?

**Comment by ThRPctmylSgltwH** [comment]
I am running :latest. I hope that makes things easier.

As a start I took the file Site.php and copied it to a new file called RelocateDomain.php. In file RelocateDomain.php I made the following changes

65 old 		//if (!empty($_POST['relocate']) && !empty($_POST['relocate_url']) && $_POST['relocate_url'] != "") {
65 new		if (1) {

66 old		//$new_url = $_POST['relocate_url'];
66 new		$new_url = "https://social.xxx.com";

I then tried to run the file from the container console in Portainer directly from the Admin directory with the command

php RelocateDomain.php

but received the following error

Fatal error: Uncaught Error: Class 'Friendica\Module\BaseAdmin' not found in /var/www/html/src/Module/Admin/RelocateDomain.php:44
Stack trace:
#0 {main}
  thrown in /var/www/html/src/Module/Admin/RelocateDomain.php on line 44

Am I on the right track and can you provide some assistance?

Thanks.

**Comment by MrPetovan** [comment]
It's a start but you will need more than this, I'll submit a console command to perform this action soon.

**Comment by ThRPctmylSgltwH** [comment]
Dear MrPetovan, I know that you are a volunteer and I am grateful for your work but do you have a timeline for the console command to change the domain? My site has been down for a couple of months at this point and I do not want to lose the history that my family has already created by starting over.
Thank you.

**Comment by MrPetovan** [comment]
Thank you for the reminder, I should be able to pull it together this week.

**Comment by MrPetovan** [comment]
Hey @ThRPctmylSgltwH , can you please pull the `2022.05-rc` branch and test the `bin/console relocate` command?

**Comment by ThRPctmylSgltwH** [comment]
@MrPetovan and @annando - when I update the container and restart, the container logs give the below text and the website cannot be reached. Do I have to do something else besides pulling the new container and restarting? I have made a backup of my /var/lib/mysql and my /var/www/html directories. The file VERSION is located directly in the /var/www/html directory and contains 2022.03. If I switch back to :latest the website is back up but with the old domain error. It seems that in :2022.05-rc the pointer to VERSION is not correct and the file is not updated.

Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory
Setup MSMTP for 'Friendica Social Network' with 'smtp.office365.com' ...
usermod: no changes
usermod: no changes
Setup finished
cat: /usr/src/friendica/VERSION: No such file or directory

**Comment by ThRPctmylSgltwH** [comment]
@MrPetovan and @annando can you help with the above error?

**Comment by tobiasd** [comment]
>  The file VERSION is located directly in the /var/www/html directory

and the error message shows

> cat: /usr/src/friendica/VERSION: No such file or directory

so at some point the directory is not `/var/www/html` but `/usr/src/friendica`

pinging @nupplaphil as he is the Docker person in the Friendica Dev team.

**Comment by ThRPctmylSgltwH** [comment]
@MrPetovan and @annando, it looks like there is an error in the script. Is it that the SET `uri` should be url?
```
root@0d9e11bee5a2:/var/www/html# bin/console relocate https://www.xxx.org/ -v
Executable: /var/www/html/bin/console.php
Arguments: array (
  0 => 'relocate',
  1 => 'https://www.xxx.org/',
)
Options: array (
  'v' => 1,
)
Command: relocate
Relocation started from https://www.xxx.org/ to https://www.xxx.org/. Could take a while to complete.
Entering maintenance mode
Updating apcontact table fields
Updating contact table fields
Updating conv table fields
Updating delayed-post table fields
Process aborted with message: Failed updating `delayed-post`: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delayed-post SET `uri` = REPLACE(`uri`, 'https://www.xxx.org/', 'http...' at line 1 thrown in /var/www/html/src/Database/Database.php:1825
Leaving maintenance mode
```

**Comment by MrPetovan** [comment]
No, the problem is that there's an hyphen (-) in the table name which is not escaped. It should be `` `delayed-post` `` instead of just `delayed-post`. Thank you for the report, I'll submit a fix for it.

**Comment by MrPetovan** [comment]
@ThRPctmylSgltwH Please try again after you pulled the latest `develop`!

**Comment by ThRPctmylSgltwH** [comment]
@MrPetovan, sorry for the late reply but I was travelling for business. The command now executes perfectly and the website is available. The next issue is that my default account no longer has access to the /admin page. I receive the error Forbidden You don't have access to administration pages.

Is there another parameter that still needs to be considered?

**Comment by MrPetovan** [comment]
Glad to hear it went through! The admin access is entirely controlled from the `config/local.config.php` file where you enter the email addresses of the admin accounts manually.

**Comment by ThRPctmylSgltwH** [comment]
Thanks for your help.
I do not see any remaining issues, but I will see over time.
