### ISSUE TITLE
Limited-visibility responses to public posts are lost?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11513]
Watched in 2022-05. Having two accounts that follow each other. Using web frontend, tusky and andstatus on Android. What happened:

* Did a post on my friendica account, public.
* Received a response to that, visibility set to follower-only, from a user on a Mastodon instance.
* This response...
* * ... never (until today) showed up in the Friendica web interface,
* * ... never showed up in tusky,
* * ... only was visible in andstatus.

By now, the only way to "see" this response is to look at the original message I posted on my Friendica account, but from the Mastodon frontend of my Mastodon account, even though the response even mentioned my Friendica, not my Mastodon account.

Can anyone make any sense of that? It's pretty weird to explain, I can provide screenshots and links to the particular posts if necessary. I _guess_ the post shows up in Mastodon because it's set up follower-only and my both accounts are followers of the person who responded, but still I can't make sense of that not showing up in Friendica at all. Ideas?

**Comment by annando** [comment]
Yeah, this is something that I wanted to have a look at it for a long time. Problem is that in the beginning Friendica always inherited permissions from the starting post. This means that a limited response to a public post would had become public as well. Because of this we drop such messages.

But we made several improvements to the core, so it is possible that we address this in the next version.

**Comment by kr428** [comment]
Stumbled into this again:

Post on Friendica, visibility set to be available only to followers: 
https://loma.ml/display/373ebf56-1662-f4aa-2301-7ad579382481

Responses on Mastodon, also set to be visible only to followers:
https://mastodon.social/@K0nrad/108802987532963246
https://social.tchncs.de/@z428/108803066175746665

Both didn't obviously appear on my Friendica instance/profile. What's a bit strange in this case is that, here, it seems visibility within the thread hasn't been changed at all but the Mastodon responses "just" took the visibility the default post used to have. Is this the same problem or a different kind of issue?
