### ISSUE TITLE
Consistent notifications (web frontend, apps)

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11512]
At the moment, notifications (in 2022-05 RC) seem a bit hard to grasp, especially while using Friendica with both the web frontend and some mobile app like Tusky or AndStatus. Experiences, learnt so far:

The web frontend seems to display notoriously different notifications than the mobile app. In the mobile app, I get information when posts of mine have been starred, reshared, commented  (much as I would expect) of whenever someone follows me, or information on new posts by some users I turned on notifications for. This, mostly, works as expected (even though "responses" and "new posts by users" look the same in some apps, like mastodon). In the web frontend, most notifications I receive are related to communication going on on some post I either interacted with (okay) or starred (which causes too much noise at least for my tastes). 

Expectation would be: The web frontend and the mobile app API are capable of showing the same notifications.

(Not sure whether this is a bug or a feature request, but at least in 2022-05 this seems to have worsened in quite some way.)

**Comment by annando** [comment]
It's not a bug, but some kind of feature. On the API we imitate the behaviour from Mastodon because we use their API. On the frontend we keep our own behaviour. However, there is an option in the settings where you can get notified on the frontend upon your posts being liked or reshared as well.

**Comment by tobiasd** [comment]
I agree with @kr428 in that I'd expect to see the same notifications in apps as in the web interface following the rules set in my settings. I wont care if Mastodon would show different notifications, as I don't use Mastodon but Friendica.

**Comment by annando** [comment]
The notifications via the API is working with a handful of predefined types. This is something that we cannot change when we want to stay compatible. This means: We don't send some text like "you are mentioned" or "someone commented on your post" but we are sending predefined types.

Edit: For that reason I don't see this as a bug.

**Comment by kr428** [comment]
I now managed to configure the setting mentioned above, making it at least somewhat more predictable in the web user interface. Personally, I get and agree with that particular reasoning. However, one way to mimick this behaviour without breaking changes all too much would be to (all along these lines) also provide a setting to disable notifications such as "XYZ has commented in conversation <ABC>" or "<YZX> has responded to a post you responded as well"? 

(Indeed, no bug from that perspective. Maybe a rather personal taste too, but for my usage the current notifications in web are by far too verbose and too extensive and it's too difficult to get rid of these. I don't really want to generally see notifications if someone added a comment to a post I "liked", this creates too much noise and makes notifications in the web at least for me next to useless. The subset provided to the Mastodon API is much "saner" here. YMMV of course).

**Comment by tobiasd** [comment]
> However, one way to mimick this behaviour without breaking changes all too much would be to (all along these lines) also provide a setting to disable notifications such as "XYZ has commented in conversation " or " has responded to a post you responded as well"?

That option is already there I believe. In your users settings in the *Notification Settings* you can enable the option **Someone writes a followup comment**. If you further don't choose the **Show detailled notifications** option, you will only see one notification per thread instead of one per action on a thread.

**Comment by kr428** [comment]
> That option is already there I believe. In your users settings in the _Notification Settings_ you can enable the option **Someone writes a followup comment**. If you further don't choose the **Show detailled notifications** option, you will only see one notification per thread instead of one per action on a thread.

Hmm, I'll give it a try then. This "someone writes a follow-up comment" is listed in the "e-mail notifications" section as far as I see? Does that apply to the web interface too?

**Comment by tobiasd** [comment]
TBH I hope so, the option for the "likes" in the deskop area seem to prevent mails for likes (or I am imagine this) but the "send mails as plaintext" option is in the desktop section as well. I've never realized, that there are different sections in the notification settings before TBH... örks

**Comment by annando** [comment]
@kr428 there is this issue: https://github.com/friendica/friendica/issues/11566

For the next version I will try to make the desktop notifications more customizable.

**Comment by kr428** [comment]
Ok thanks. So I'll for now consider this part a duplicate, and for the other aspects there seem workarounds.
