### ISSUE TITLE
Incomplete profile data User accounts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11548]
- [x] I have searched open and closed issues for duplicates

### Bug Description
If a profile picture is changed or a new account is shared, the profile pictures are currently not updated. Only the placeholder is visible. Apparently, the profile texts are also not always transferred cleanly.
Only with "Reload contact data" a complete update with picture and profile text takes place.
This only seems to happen with accounts that come from non Friendica & Twitter accounts. 

The problem exists with enabled and disabled images proxy

### Screenshots
Profile picture changed
![Screenshot 2022-05-22 at 11-26-07  ˈloma  Network](https://user-images.githubusercontent.com/44441246/169688625-99269a89-9773-4b64-9b5f-9ae6f4d07916.png)

Unresolved username in the timeline
![Screenshot 2022-05-21 at 13-44-45 (1)  ˈloma  Network](https://user-images.githubusercontent.com/44441246/169688638-12f91143-07da-4452-af91-10f1b2119f49.png)

Profile picture and description before manual update  
![Screenshot 2022-05-22 at 11-33-21 (2)  ˈloma  Contact](https://user-images.githubusercontent.com/44441246/169688913-c7612c6a-44cd-4e39-b7b8-720798267e9c.png)

Profile picture and description after manual update  
![Screenshot 2022-05-22 at 11-33-33 (2)  ˈloma  Contact](https://user-images.githubusercontent.com/44441246/169688914-9df54239-9898-492e-8d66-6654a75a75b3.png)

### Platform Info

Friendica Version:
2022.05-RC 22.05.2022 09:00

Friendica Source: 
Git-Hub

PHP version:
7.4

SQL version:
10.3

**Comment by annando** [comment]
Do other people experience the same?

**Comment by foss-** [comment]
Had this problem with Twitter accounts in the past. But with recent changes in regards to avatars I think (TM) all profile picture were updated and now show as expected.
See also https://github.com/friendica/friendica/issues/11324#issuecomment-1117986407

**Comment by annando** [comment]
squeet.me and pirati.ca don't count concerning this, since I'm using an experimental avatar caching here.

**Comment by loma-one** [comment]
Just looked over the public timeline again and yes, the problem is still here. If it is an instance problem, then a hint on how I can fix it myself would be nice.

**Comment by annando** [comment]
Where are you storing the avatar pictures? Database or file system? Have you checked or unchecked the option to cache avatars?

**Comment by loma-one** [comment]
File system. The rights are held by the web server. www-data:www-data

**Comment by loma-one** [comment]
Since today I run the config setting 'avatar_cache' => true. Observe if this is successful.

**Comment by tobiasd** [comment]
Any new observations @loma-one ?

**Comment by MrPetovan** [comment]
Is this still current?

**Comment by loma-one** [comment]
sorry, I lost sight of that. Was a local problem
