### ISSUE TITLE
Git install: Subdirectories (/install, /login, etc.) absent or not accessible?

### ISSUE THREAD

**Issue by robert-winkler** [friendica/friendica#11547]
I just installed friendica for the first time on a dedicated VPS.

1. Problem: I wanted to start the installation by visiting my webpage (after moving .htaccess-dist to .htaccess). However, the /install directory was not accessible.
I installed it manually (success!) and also changed the access to 755 and the owner to www-data.

2. The page seems to work, but I cannot do anything:
<https://mexico-pensante.blog/#>
None of the subdirectories needed, such as <https://mexico-pensante.blog/register> seems to exist.

You can visit my site and verify the problem:
<https://mexico-pensante.blog/#>

I'm using the stable git version (unfortunately, showing the version does not work either..

PHP:  7.3.31-1~deb10u1

SQL: 10.3.34-MariaDB-0+deb10u1 Debian 10

I appreciate any hint! Best, Robert

**Comment by tobiasd** [comment]
This sounds as if your webserver is not configured to allowr `rewriting`.

But, as I just wanted to test your problem for me calling https://mexico-pensante.blog/help/Connectors works. Have you found the solution in the mean time?

**Comment by robert-winkler** [comment]
Dear Tobias,

I modified the installation directory in the Apache conf; now it seems to work fine. Thanks!
