### ISSUE TITLE
Show which user I'm displaying follows/ followers for in Tusky

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11553]
- [x] I have searched open and closed issues for duplicates

### Bug Description

See https://github.com/tuskyapp/Tusky/issues/2538. The list of followers and followed in Tusky is empty. It does work with a Mastodon server though (so I believe it's a friendica issue).

### Steps to Reproduce

See https://github.com/tuskyapp/Tusky/issues/2538. 

Friendica Version: 2022.03, docker image

**Comment by annando** [comment]
I can't reproduce it here with the RC branch.

Edit: Have you checked if you see the followers via the web interface?

**Comment by foss-** [comment]
Follows | Followers numbers are not 0 for me and when tapped the lists do show entries. However both numbers are inaccurate and much lower than the numbers I see when logged into friendi.ca > Contacts and selecting Followers or Following.

This is Friendica, version 2022.05-rc that is running at the web location https://pirati.ca. The database version is 1464/1464, the post update version is 1452/1452.

**Comment by ne20002** [comment]
I gave it a few more tries yesterday and I still have the problem. I have non public account on Mastodon and my friendica and don't list my contacts. Just a guess: maybe there is two api calls for followed/followers list? one for the account owner / logged in user and on public? Might it be the wrong one used here?
Also: I have a few contacts to not to be shown in conatcts list ..
