### ISSUE TITLE
can't remove jabber address from profile

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11557]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I have repeatedly tried to remove my jabber address from my profile information. It is still visible on the "display post page" (`https://libranet.de/display/{id}`), although the field in settings is empty. It is also visible on that page in a private browser tab.

### Steps to Reproduce

1.  Add a jabber id in profile settings
2.  visit one of your posts, look if it is there 
3.  go back to settings. try to remove it by setting an empty value in the field
4.  visit one of your posts.. look below the profile picture

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2022.05-rc, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1464/1464 und die Post-Update-Version 1452/1452."

**Comment by MrPetovan** [comment]
Can you check if it is still present in the settings form? It might be a cache issue.

**Comment by haheute** [comment]
when i go to `/settings/profile`, the form field for xmpp / jabber is empty

**Comment by MrPetovan** [comment]
Thank you, what does your main profile show? The link should be something like `https://<yourdomain.com>/profile/<username>/profile`.

**Comment by haheute** [comment]
there also is no jabber address. but still on the `/display/<id>` page.

**Comment by MrPetovan** [comment]
Ok, so it definitely looks like a cache issue, thank you for the added details.

**Comment by annando** [comment]
It could be a problem that this value is removed from the user record but not the self contact or its corresponding public contact.

**Comment by annando** [comment]
I can't reproduce this here on my machine.

**Comment by haheute** [comment]
I'm observing this since some time. If I remember correctly, the jabber address was also gone, but then it reappeared..
I have tried with empty field, and with spaces - and with fantasy id's like bla@bla.xy to replace it. 
here, you should see it: https://libranet.de/display/0b6b25a8-1962-8cdd-880c-604042235213

**Comment by annando** [comment]
Weird ... BTW: Here it isn't: https://pirati.ca/display/0b6b25a8-1962-8cdd-880c-604042235213

**Comment by annando** [comment]
Could you have a look at the database? Please look for the field `xmpp` in the `contact` table and have a look for all contact records for that user. You should have at least the public contact record (with `uid' set to `0`) and the `self` contact (where `self` is set to `1`). I expect that the `self` and the public contact are both have an empty xmpp field (because that's what I tested and verified in the code). But possibly there are other issues.

**Comment by AlfredSK** [comment]
I can do that later today or tomorrow.

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> select id, nick, addr, url, uid, self, xmpp from contact where nick like 'xy' and addr like '%libranet%';
+---------+------+----------------+--------------------------------+------+------+-------------------+
| id      | nick | addr           | url                            | uid  | self | xmpp              |
+---------+------+----------------+--------------------------------+------+------+-------------------+
| 1319055 | xy   | xy@libranet.de | https://libranet.de/profile/xy |    0 |    0 | haheute@draugr.de |
| 1319953 | xy   | xy@libranet.de | https://libranet.de/profile/xy |    2 |    0 | haheute@draugr.de |
| 1319056 | xy   | xy@libranet.de | https://libranet.de/profile/xy |    3 |    0 |                   |
| 1319037 | xy   | xy@libranet.de | https://libranet.de/profile/xy | 3963 |    1 |                   |
| 2279771 | xy   | xy@libranet.de | https://libranet.de/profile/xy | 4365 |    0 | haheute@draugr.de |
| 2453496 | xy   | xy@libranet.de | https://libranet.de/profile/xy | 4441 |    0 | haheute@draugr.de |
| 2536874 | xy   | xy@libranet.de | https://libranet.de/profile/xy | 4574 |    0 |                   |
+---------+------+----------------+--------------------------------+------+------+-------------------+
7 rows in set (0.001 sec)
```

**Comment by MrPetovan** [comment]
Oof, all the “xmpp” values should be the same, either all filled or all empty.

**Comment by AlfredSK** [comment]
The uid 3963 is the uid of the local user (self = 1). For that user the xmpp field is empty but not for some other contacts and also not for the user with uid = 0.

**Comment by annando** [comment]
That's ... interesting. We are updating the `own` contact, the public contact and the profile at the same time:
https://github.com/friendica/friendica/blob/2022.05-rc/src/Model/Contact.php#L768-L787

Can you have a look at the `updated` field in the contact table?

**Comment by AlfredSK** [comment]
Here it is...

```
MariaDB [friendica]> select id, uid, self, nick, updated, xmpp from contact where nick like 'xy' and addr like '%libranet%';
+---------+------+------+------+---------------------+-------------------+
| id      | uid  | self | nick | updated             | xmpp              |
+---------+------+------+------+---------------------+-------------------+
| 1319055 |    0 |    0 | xy   | 2022-05-16 18:52:02 | haheute@draugr.de |
| 1319953 |    2 |    0 | xy   | 2021-05-22 10:05:01 | haheute@draugr.de |
| 1319056 |    3 |    0 | xy   | 2021-05-22 10:05:01 |                   |
| 1319037 | 3963 |    1 | xy   | 2022-05-16 18:52:02 |                   |
| 2279771 | 4365 |    0 | xy   | 0001-01-01 00:00:00 | haheute@draugr.de |
| 2453496 | 4441 |    0 | xy   | 0001-01-01 00:00:00 | haheute@draugr.de |
| 2536874 | 4574 |    0 | xy   | 0001-01-01 00:00:00 |                   |
+---------+------+------+------+---------------------+-------------------+
7 rows in set (0.001 sec)
```

**Comment by annando** [comment]
That's confusing ...

**Comment by AlfredSK** [comment]
I know. :-)
