### ISSUE TITLE
Tumblr crossposting is broken?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11551]
Starting late April, Tumblr connector seems to have broken for my account. Tested on loma.ml, been debugging that with the local admin without too much effect gained. Seems it's only limited to my account but for that one, it's apparently unfixable? No weird insights in the log files, posts just don't seem to go through. Already did reset the full Tumblr addon configuration (including the app registration on Tumblrs side) without things getting noticeably better. Any way to debug that?

(Finding all along the way: Tried to add a new Tumblr blog to my account there to check whether it's something specific to my _blog_, I noticed that, though, by then I can choose the newly added blog from the drop-down in Friendica connector configuration dialog but this will never be remembered - as soon as I reload the settings page after saving that, it's always set back to the "main" blog.)

**Comment by ghost** [comment]
> Tumblr connector seems to have broken for my account.

I can confirm, under settings - social networks the page is authetified but nothing arrives at Tumblr.
There is also nothing in the logs.
![2022-09-23 08 05 26](https://user-images.githubusercontent.com/12480023/191903467-0d9ce8bb-0b1d-44eb-b333-6e8879d0b67c.png)

**Comment by ghost** [comment]
I got just this maybe it helps
`2022-09-23T06:00:56Z index [NOTICE]: E_NOTICE: session_start(): A session had already been started - ignoring {"code":8,"message":"session_start(): A session had already been started - ignoring","file":"/addon/tumblr/tumblr.php","line":88} - {"file":null,"line":null,"function":"session_start","uid":"9730cb","process_id":180089}
`

`2022-09-23T05:59:02Z worker [NOTICE]: tumblr_send: general error {"error":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Got an error. Try again."}]},"worker_id":"4983eba","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":441,"function":"tumblr_send","uid":"bd9cf9","process_id":181912}`

`2022-09-23T06:00:56Z index [NOTICE]: E_NOTICE: Undefined variable: o {"code":8,"message":"Undefined variable: o","file":"/addon/tumblr/tumblr.php","line":137} - {"file":"tumblr.php","line":137,"function":"tumblr_connect","uid":"9730cb","process_id":180089}`

`2022-09-23T06:03:32Z worker [NOTICE]: tumblr_send: general error {"error":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Something flubbed. Try again."}]},"worker_id":"2accaf4","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":441,"function":"tumblr_send","uid":"9ea1d4","process_id":183063}
`

**Comment by kr428** [comment]
Interesting. Parts of that error apparently were visible on "my" instance too, but it seems to depend on user accounts in some way...? Because on my instance, there are other users for which this seems to flawlessly work, while for my account it same as reproducibly doesn't. 😶️

**Comment by ghost** [comment]
You mean that for other users on your instance the Tumblr addon works?

Is it possible that you, like me, have multiple user accounts?

**Comment by kr428** [comment]
> You mean that for other users on your instance the Tumblr addon works?
> 
> Is it possible that you, like me, have multiple user accounts?

Not sure. I've been discussing this at length with @loma-one (who's doing a rather great job maintaining the instance I'm on), and there seems no real error and I also don't seem to have multiple user accounts. Running out of ideas here...

**Comment by kr428** [comment]
Adding to that: It seems more an issue on Tumblr than on Friendica site. Tried the same on a different instance, same result. Linking to the account works, no error, but no post is being sent over. No real idea what's going on here.

**Comment by loma-one** [comment]
I need to correct that. The auth. works.
But no posts arrive on tumblr.
When comparing a new account and an existing authentication, it is noticeable that the path has changed

dre@dis-le.de  send to  https://www.tumblr.com/blog/lomaml
![grafik](https://user-images.githubusercontent.com/44441246/194875476-a0b48ee6-c9ad-4b0d-a22a-49191b66d201.png)

An existing, older authentication works and the posts are sent out
it works for the account @[one@loma.ml](mailto:one@loma.ml)
messages are sent to the account https://www.tumblr.com/blog/oeffentlicheversicherung

![grafik](https://user-images.githubusercontent.com/44441246/194877049-1da71aad-33a6-4c0f-bde7-df183e4b3a30.png)

**Comment by kr428** [comment]
@loma-one Just to add: I tried that several times with my account, it however doesn't seem to follow that route. In my case, here's what I tried several times  (always with the same outcome):

* Tumblr side: Remove the app registration for Friendica
* Friendica Tumblr connector: Uncheck both fields and save settings.
* Friendica Tumblr connector: (Re-)Authorize Tumblr page => moved to Tumblr => granted access.

At this point, I usually end up with that screen ...

![image](https://user-images.githubusercontent.com/685879/194871788-62f215e0-b0de-45dd-b64c-6378219c631c.png)

... that allows me to get back to the Tumblr settings page where I can enable connector and postings again. Don't see that "access denied" in my experiments, but it's still not working. Or are there remains of my previous (working) configuration somewhere in the database?

**Comment by kr428** [comment]
Adding to that, tried something else: Created a new Tumblr account. Tried to link Friendica. Worked, but resulted in a "wrong" URL appearing in the drop-down in the connector settings, same as above. Connector says "www.tumblr.com/blog/view/core42" (blog is https://www.tumblr.com/blog/core428 so the "8" is missing). Needless to say, no posts appear there. Switched back to my "old" account in Friendica -> drop-down again displays "<blogname>.tumblr.com" as URL, posts also don't make it there. Weird. So most likely two issues: (a) Why is the URL truncated for "newly"(?) registered accounts? And (b) why does the URL differ for "old" accounts?

**Comment by msdosfx** [comment]
I can confirm this issue. I tried linking a Friendica account to an old Tumblr account and the auth seems to work but posting to Tumblr doesn't. Tried linking that Friendica account to a newly created Tumblr account and the auth seems to work but posting doesn't and the URL is different with the last character truncated. Tried linking a newly created Friendica account with an old Tumblr account and the auth seems to work but crossposting doesn't, and the URL for the Tumblr in the dropdown in settings looks like example.tumblr.com. None of the options I tried worked. I can't confirm whether this is server-wide issue on my instance, because I don't know the admin on my instance. But nonetheless the truncated URL is sure to cause an issue, I would guess, in addition to the other unknown issue/s

**Comment by msdosfx** [comment]
Just a thought: I had the old tumblr reposting my Instagram posts via IFTTT, before I dropped out of polite society in favor of the Fediverse, and I am now wondering if that link still exists and might be causing an issue. This is a new issue for you though, so unlikely in your case I suppose.

**Comment by kr428** [comment]
> Just a thought: I had the old tumblr reposting my Instagram posts via IFTTT, before I dropped out of polite society in favor of the Fediverse, and I am now wondering if that link still exists and might be causing an issue. This is a new issue for you though, so unlikely in your case I suppose.

Yeah, I used to have a similar setup too, also with an existing IFTTT link in Tumblr, which I haven't used in quite a while though. Removed it, re-connected Friendica, doesn't seem to change things. However, thanks for the hint, was worth a try.🙂

**Comment by kr428** [comment]
Wanted to re-test this with 2023-03rc, seems it's still broken but broken "more" right now: Tried to re-authenticate with Tumblr and just ended up on a (Friendica) page showing 
"Could not connect to Tumblr. Refresh the page or try again later." 
CORS issues?

**Comment by annando** [comment]
Posting to Tumblr with an existing connection does work fine for me: https://blog.dabo.de/

I haven't tried reauthentication yet.

**Comment by annando** [comment]
I completely reworked many parts of the Tumblr addon. At least on my system everything from adding a new connection to choosing the blog and posting to it works now fine.

**Comment by ghost** [comment]
Its not working for mee, tryed to reauthenticat, that worked but no post arrives
This is what i get

```
PHP Notice: session_start(): Ignoring session_start() because a session is already active in addon/tumblr/tumblr.php on line 149', referer: https://www.tumblr.com/
--
PHP Notice: session_start(): Ignoring session_start() because a session is already active in /addon/tumblr/tumblr.php on line 97PHP message: PHP Warning: Undefined variable $o in /addon/tumblr/tumblr.php on line 143', referer: https://meld.de/settings/connectors

```
