### ISSUE TITLE
Support of Groups in Statusnet (Feature Request)

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#1156]
when posting to different social networks it would be nice that there will be automatically set a grouptag in statusnet but other connectors are using this as hashtag

so when i post like "this is a #test post" it should be visible in
friendica: this is a #test post
twitter: this is a #test post
statusnet: this is a !test post 

so that in friendica and twitter is test a hashtag and in statusnet a grouptag

**Comment by tobiasd** [comment]
Does GNUsocial publish a list of groups a user is in somewhere (over the API)? Otherwise I can ATM only think about a textinput that has to be filled by the user with group names where the the # should be replaced by a ! before the tag name.

**Comment by MrPetovan** [comment]
StatusNet is obsolete, closing this issue.

**Comment by tobiasd** [comment]
It is Gnu Social nowadays, and their group feature is still the best there is in the fediverse.

**Comment by MrPetovan** [comment]
Maybe, but nobody picked up the task in 4 years and now we use the exclamation point for mentioning forum contacts, which would make any work on this even trickier.

**Comment by annando** [comment]
The OStatus protocol is dying. It doesn't make any sense trying to figure out how the group support worked there.

**Comment by tobiasd** [comment]
I know. Both of you are right. Still, the StatusNet groups are / were the most usable group solution in the Fediverse for me.
