### ISSUE TITLE
Resize uploaded pictures so they meet the maximum permited size

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#11562]
### Describe the feature you'd like

When a picture is uploaded and it exceeds the maximum permitted file size (not PHP limit) then it should be resized (resize and quality decreased) to meet the maximum permitted file size instead of just giving a fault. 

### Describe alternatives you've considered

No, just a spree of the moment idea.

**Comment by annando** [comment]
We are doing so: https://github.com/friendica/friendica/blob/2022.05-rc/src/Model/Photo.php#L888-L920

**Comment by utzer** [comment]
> We are doing so: https://github.com/friendica/friendica/blob/2022.05-rc/src/Model/Photo.php#L888-L920

That is new, right? In the current stable I just get some exceed message that tells me the maximum upload size that I set in /admin.

**Comment by annando** [comment]
No, this is done several versions before.

**Comment by utzer** [comment]
> No, this is done several versions before.

So then I wonder how to activate it. Will check.

**Comment by annando** [comment]
It should work out of the box. How have you uploaded the picture?

**Comment by utzer** [comment]
It works, strange, I got the fault this morning. Strange.
