### ISSUE TITLE
Registration Email delivery to Gmail Accounts fails

### ISSUE THREAD

**Issue by robert-winkler** [friendica/friendica#11572]
Hi, am running a Friendica Node. Strangely, Users who want to register with a Gmail account will not receive their confirmation email with the password.

My admin email is xxx@bioprocess.org, but obviously, a gmail-smtp is configured in friendica:

~~~
    The original message was received at Sun, 29 May 2022 03:51:46 +0200
    from localhost [127.0.0.1]

    ----- The following addresses had permanent fatal errors -----
    <newuser@gmail.com>
    (reason: 550-5.7.1 [2a03:4000:f:99e:3802:9aff:fe22:10e1] Our system has detected that)

    ----- Transcript of session follows -----
    ... while talking to gmail-smtp-in.l.google.com.:

    DATA


    <<< 550-5.7.1 [2a03:4000:f:99e:3802:9aff:fe22:10e1] Our system has detected that
    <<< 550-5.7.1 this message does not meet IPv6 sending guidelines regarding PTR
    <<< 550-5.7.1 records and authentication. Please review
    <<< 550-5.7.1 https://support.google.com/mail/?p=IPv6AuthError for more information
    <<< 550 5.7.1 . b14-20020a056000054e00b0020ff2cca108si5691033wrf.221 - gsmtp
    554 5.0.0 Service unavailable

~~~

I already removed sendmail on the server, but another mailer seems to be configured.

I also tried using the PHP Mailer SMTP addon with the same error.

1) Where can I configure my sender SMTP?

2) Can I switch off email sending of login data? Anyway should be considered bad practice to send confidential data in plain text since nobody wants to use PGP (...). Displaying the information on the Registration Page would be fine (during the installation, there was no email sent, the information was displayed on the screen).

Best, Robert 
(https://mexico-pensante.blog)

Friendica Source: Friendica 'Siberian Iris' 2022.03 - 1452

PHP version: PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )

SQL version: Server version: 10.3.34-MariaDB-0+deb10u1 Debian 10

**Comment by ne20002** [comment]
The message complains about IPv6 PTR DNS record. Seems to be your mail Server setup.
Google is strict with checking oft ptr, dmarc, spf. ..

https://internet.nl/mail/bioprocess.org/728056/#

**Comment by robert-winkler** [comment]
Well, I can send emails with SMTP, using my bioprocess.org (=ionos.de) account, from a variety of systems to Gmail without problems. This is why I suggest a friendica/PHP problem. It seems strange to me that I only had to configure the admin email address in the local-config.php, but no smtp server, password, ... Thus, I am not surprised Gmail doesn't like me.

I think, the real question is: 

How can I configure my email settings in friendica?
 
How can I configure the other settings, such as SMTP server and password, ports, etc.?

**Comment by tobiasd** [comment]
Friendica uses your servers email sending capabilities by default (via the PHP `mail()` command) so you need a woking mailserver setup (with all the correct DNS settings and additional header information to make e.g. gmail happy) or alternatively the `phpmail` addon, you already tried.

As @ne20002 already mentioned, the PTR DNS entry for the IPv6 address. The tool that Gogle liked in the help article in the PTR section reports for your domain, that only the PTR entriy for the IPv4 address is set, but IPv6 seems to be missing. So gmail cannot verify your server as it reaches via IPv6.

So either this is the missing spot in the configuration - or their recommended tool is missing out IPv6. Could you check your IPv6 PTR DNS settings?

**Comment by robert-winkler** [comment]
@tobiasd Well, I configured ipv6 rDNS:

![ipv6](https://user-images.githubusercontent.com/9994605/171641112-72199b6f-6a6d-4e01-bdb0-64cf2848b9ad.png)

 but the ping delivers the ipv4:
`> ping mexico-pensante.blog
PING mexico-pensante.blog (37.120.185.146) 56(84) bytes of data.
64 bytes from mexico-pensante.blog (37.120.185.146): icmp_seq=1 ttl=55 time=185 ms
`
And `https://www.ipaddressguide.com/ipv6-check` also tells me that ipV6 is not supported..

Do I have to disable ipv4? 
Or is there anything else I need to configure?

**Comment by tobiasd** [comment]
Can you use the `::0` in the IPv6 address? I'm usually using the `::1` and really don't know if a `0` is valid there.

**Comment by robert-winkler** [comment]
OK. IPv6 online ping works with the ::1 IP!

<https://www.subnetonline.com/pages/ipv6-network-tools/online-ipv6-ping.php> (https://www.subnetonline.com/pages/ipv6-network-tools/online-ipv6-ping.php)
	PING 2a03:4000:f:99e::1(2a03:4000:f:99e::1) 32 data bytes 40 bytes from 2a03:4000:f:99e::1: icmp_seq=1 ttl=58 time=6.52 ms 40 bytes from 2a03:4000:f:99e::1: icmp_seq=2 ttl=58 time=6.57 ms 40 bytes from 2a03:4000:f:99e::1: icmp_seq=3 ttl=58 time=6.79 ms 40 bytes from 2a03:4000:f:99e::1: icmp_seq=4 ttl=58 time=6.45 ms --- 2a03:4000:f:99e::1 ping statistics --- 4 packets transmitted, 4 received, 0% packet loss, time 3005ms rtt min/avg/max/mdev = 6.453/6.588/6.798/0.140 ms https://mexico-pensante.blog still is not working.

I need to update the DNS entries first, I guess. I'm on it.

Best, Robert

June 2, 2022 10:36 AM, "Tobias Diekershoff" ***@***.*** ***@***.******@***.***>)> wrote:
	Can you use the ::0 in the IPv6 address? I'm usually using the ::1 and really don't know if a 0 is valid there.

**Comment by tobiasd** [comment]
Today I stumbled over this [blog entry about Google Mail and IPv6](https://www.spamresource.com/2020/11/honestly-dont-send-to-gmail-over-ipv6.html) which is kind of discouraging...

**Comment by robert-winkler** [comment]
I configured IPv6 on my server and modified the DNS mail to smtp.ionos.de; Now mailing to Gmail works, but messages are sent to Spam/ Junk. Other email addresses seem to work fine. Yes, the Google reputation of my server probably is still low.
I would love to not care about these special (and sometimes obscure) Google obstacles, but most of my users come from there...
Definitely, setting up the IPv6/ mailing was not trivial.
