### ISSUE TITLE
Mark all or no contacts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11574]
### Is the feature request related to a problem? Please describe.

It may happen that contacts need to be updated; locked/unlocked/ignored, ignore unchecked. Currently, on a paginated page, each contact must be marked individually. 

### Describe the feature you'd like

There should be a possibility to mark or unmark all contacts on a paginated page. 
![Screenshot 2022-05-29 at 11-03-07  ˈloma  Contact](https://user-images.githubusercontent.com/44441246/170860614-55d3abe7-5493-4a8a-a880-bc4ab7e95b82.png)

**Comment by loma-one** [comment]
No change is currently being considered. Therefore closed here.

**Comment by annando** [comment]
I don't think that this is a bad idea. It isn't just picked up yet.
