### ISSUE TITLE
Untranslated string "Data" in log view screen

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#11581]
Please see [this line](https://github.com/friendica/friendica/blob/2022.05-rc/view/theme/frio/js/module/admin/logs/view.js#L70):

```
if (data !== "") {
	elm.innerHTML = "<h3>Data</h3>";
	data = JSON.parse(data);
	elm.innerHTML += recursive_details("", data);
}
```

The `<h3>Data</h3>` is hard-coded. If this word is part of all events then you should move this string [to the template](https://github.com/friendica/friendica/blob/2022.05-rc/view/theme/frio/templates/admin/logs/view.tpl#L127) and mark it there as translatable.

**Comment by MrPetovan** [comment]
Fabioooo?

**Comment by fabrixxm** [comment]
You rang?

I'll have a look 👍
