### ISSUE TITLE
Where to configure Friendica Email settings?

### ISSUE THREAD

**Issue by robert-winkler** [friendica/friendica#11589]
For the registration of new users, Friendica needs to send an email with the user password.

1) For installation, only an email address needs to be given. But how can I configure the smtp server, password, ports, security, etc.? 

E.g. in my friendica node (I'm admin of https://mexico-pensante.blog) only some email addresses can be reached. Strict servers such as gmail (about 90% of my users) do not accept my emails, I suppose because of missing authentication.

2) Is it possible to register without email? In my first installation, the password was assigned by friendica and displayed on the screen. Is there a setting to make this method default. This would be more secure, anyway, than sending plain text user/password combinations.

Thanks, Robert

**Comment by tobiasd** [comment]
Friendica is using the PHP `mail` command which uses the server system mail setup to deliver emails. Alternatively you can use the [phpmailer](https://github.com/friendica/friendica-addons/tree/2022.05-rc/phpmailer) addon from the Friendica addon repository to send mails via an external server.

The information bubble is shown, when there is no email setup. One could probably change the code of the [registration module](https://github.com/friendica/friendica/blob/2022.05-rc/src/Module/Register.php#L324) to always show it.

It is possible for the admin to use the `bin/console` command from the commandline of the server to create a new user and change passwords for users.

**Comment by robert-winkler** [comment]
I changed to the phpmailer addon. After configuring also IPv6 and the DNS, mailing works fine. Thanks, @tobiasd!
