### ISSUE TITLE
Notifications received in mixed language

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11595]
### Bug Description

Friendica is set to `English (United States)` and yet there are some notifications in german as well. Think all german notifications are notifications for interactions of Twitter users from a connected Twitter account.

### Steps to Reproduce

- connect friendica account to twitter account
- set friendica to english
- wait for notifications about twitter user interactions to come in

Maybe they are german? Not sure which element decides which language is used for a notification. Browser is english, twitter shows up in english as does the rest of friendica.

### Platform Info

This is Friendica, version 2022.05-rc that is running at the web location https://squeet.me. The database version is 1464/1464, the post update version is 1452/1452.

**Comment by MrPetovan** [comment]
Is this related to https://github.com/friendica/friendica/issues/11594?
