### ISSUE TITLE
Mastodon API for FediLab support

### ISSUE THREAD

**Issue by stom79** [friendica/friendica#11604]
Hi there,

I am the main developer of Fedilab and Android app supporting the Mastodon API. I would like to find the best way to discute with you about the Mastodon API that is used with Friendica.

I have some problems with objects returned by the API. Example: https://codeberg.org/tom79/Fedilab/issues/134#issuecomment-463222

How could you do that? Is it ok on a single thread? Thank you.

**Comment by annando** [comment]
Which API command are you exactly sending and where are you expecting the result? Concerning this while "star, bookmark, fav" thingy there are some small but important differences in the different parts of the API. Also if you mix APIs (our Mastodon inspired and the Twitter inspired one) you have to be on the latest release (possibly the current rc, I'm not completely sure) since we there switched to a a unique id for the posts between those two implementations.

**Comment by stom79** [comment]
OK - Currently, when a user makes an action (boost, fav, etc.) Fedilab uses the reply to update the UI - I will update the code on my end when reply is null.

Also, for private messages, it seems that the last message is not attached. It's harder to find a trick for that case. See `last_status`
https://docs.joinmastodon.org/entities/conversation/

Currently, the app only uses the Mastodon API, I guess I can't use the Twitter API with the same token (bearer vs basic)?

**Comment by annando** [comment]
All API parts should be usable with the same token.

**Comment by annando** [comment]
I just fetched the latest beta version of Fedilab and tried myself. On my system `bookmark`, `favourite`, `unbookmark` and `unfavourite` work like expected.

**Comment by stom79** [comment]
I tested on `friendica.me` and for some accounts in public TL, it does not work. The weird part, the API doesn't return an error but the message with `favourited = false`, like if somehow it called `statuses/{id}/unfavourite` but it's  `statuses/{id}/favourite` which was called.

**Comment by annando** [comment]
Weird. Then I will have a deeper look if there can be some timing or cache issues.

**Comment by foss-** [comment]
For what its worth FediLab b19 now shows `Oops ! An error occured!` whenever trying to star | like or boost | reshare a post on a friendica account. Progress, since previously tapping star icon did nothing.

**Comment by stom79** [comment]
> For what its worth FediLab b19 now shows `Oops ! An error occured!` whenever trying to star | like or boost | reshare a post on a friendica account. Progress, since previously tapping star icon did nothing.

Yes we added that error message when the api returns the message without doing the action (fav/boost).

**Comment by futureisfoss** [comment]
Friendica currently don't have a good client support on android, and its the only thing stopping me from moving to friendica completely. I'm glad to see the fedilab developer is willing to help with this, I hope you guys can figure this out :)

**Comment by stom79** [comment]
Users encounter an issue when updating their profile with `api/v1/accounts/update_credentials` endpoint

Does it mean it's not yet implemented? 

https://github.com/friendica/friendica/blob/05a76a3dc2fd313e660752a7eb139ec2fb3a6667/src/Module/Api/Mastodon/Accounts/UpdateCredentials.php#L40

**Comment by annando** [comment]
Currently not. I guess we should work on this.

**Comment by stom79** [comment]
I have an issue with the endpoint `api/v2/search`, if I pass the URI of a message, I am getting an unrelated one.

Example with this call: 
```https://friendica.me/api/v2/search?q=https%3A%2F%2Ftoot.fedilab.app%2Fusers%2Fapps%2Fstatuses%2F108622861323735925&type=statuses&exclude_unreviewed=false&resolve=true&following=false&offset=0&limit=1```

<details>
<summary>Result:</summary>

```json
{
    "accounts": [],
    "statuses": [
        {
            "id": "1032539",
            "created_at": "2022-07-11T08:02:44.000Z",
            "in_reply_to_id": null,
            "in_reply_to_account_id": null,
            "sensitive": false,
            "spoiler_text": "",
            "visibility": "public",
            "language": "en",
            "uri": "https://pluspora.com/objects/c49ae820e31d013aad40005056264835",
            "url": "https://pluspora.com/posts/c49ae820e31d013aad40005056264835",
            "replies_count": 0,
            "reblogs_count": 0,
            "favourites_count": 0,
            "favourited": false,
            "reblogged": false,
            "muted": false,
            "bookmarked": false,
            "content": "<b><a href=\"https://squeet.me/display/962c3e10-1923d727-bee20f1a56dcc57f\">♲ aljazeera@squeet.me</a>:</b><br>\n<blockquote class=\"shared_content\" dir=\"auto\"><h3>Portugal deploys 3,000 firefighters to battle heatwave blazes</h3><br>Portuguese authorities announced a 'state of contingency' as at least 29 people have reported fire-related injuries.<br><a href=\"https://www.aljazeera.com/news/2022/7/10/portugal-battles-forest-fires-amid-heatwave\" target=\"_blank\" rel=\"noopener noreferrer\">Portugal deploys 3,000 firefighters to battle heatwave blazes</a></blockquote>",
            "reblog": null,
            "application": {
                "name": "Feed"
            },
            "account": {
                "id": "43008",
                "username": "tess",
                "acct": "tess@pluspora.com",
                "display_name": "Tessa Byrd",
                "locked": false,
                "bot": false,
                "discoverable": true,
                "group": false,
                "created_at": "2020-01-24T19:08:09.000Z",
                "note": "",
                "url": "https://pluspora.com/u/tess",
                "avatar": "https://friendica.me/photo/contact/300/34d91e80b4b3013620f700505608f9fe?ts=1657303546",
                "avatar_static": "https://friendica.me/photo/contact/300/34d91e80b4b3013620f700505608f9fe?ts=1657303546",
                "header": "https://friendica.me/photo/header/34d91e80b4b3013620f700505608f9fe?ts=1657303546",
                "header_static": "https://friendica.me/photo/header/34d91e80b4b3013620f700505608f9fe?ts=1657303546",
                "followers_count": 37,
                "following_count": 36,
                "statuses_count": 265,
                "last_status_at": "2022-07-11",
                "emojis": [],
                "fields": []
            },
            "media_attachments": [],
            "mentions": [],
            "tags": [],
            "emojis": [],
            "card": null,
            "poll": null
        }
    ],
    "hashtags": []
}
```

</details>

**Comment by oe4dns** [comment]
I have done some testing and want to report the current state I'm experiencing with Fedilab 3.0.6 and Friendica 2022.06. I hope this helps to get closer to the issues:

Creating posts works, but only if hey do not contain any image. Posts with images make it look like Fedilab is uploading for a while but nothing is postet and the Image is not saved into Friendica's Pictures store.

Deleting posts works, but not "Delete and Re-draft". In that case the Post is only removed from the server but kept in Fedilabs timeline. "Oops ! An Error occured" is shown.

Liking and Reposting also leads to the "Oops ! An Error occured" Popup. Even more interesting - the post itself as seen from the Friendica UI looks like it has been liked and/or reposted. But this never reaches other Servers/Accounts and it is also not visible from my profile page (which would be the case if I like/repost from the Friendica UI)

**Comment by kr428** [comment]
Stumbled across this (https://codeberg.org/tom79/Fedilab/issues/247) again with Fedilab.  Apparently, unlike in Mastodon, in Friendica posts hashtags, user profile mentions, ... are actual hyperlinks to a particular web resource (something like https://<instance>/tags/<tag> for Mastodon) which causes clients - both Fedilab and tusky behave like this - to open these links in a browser window rather than, in example, in a profile view inside the app. Completely unsure, though, where and how this should possibly be addressed. At least in terms of Mastodon API compatibility, it seems to break things here...

**Comment by kr428** [comment]
(Just an interesting note here: Having Friendica set up to mirror my Twitter timeline, I am seeing Twitter posts via Fedilab too. For Twitter posts, I can do a "star" or "reshare" and both works without displaying any particular error message in Fedilab... Not sure if this is related but it's a bit odd for sure.)

**Comment by foss-** [comment]
> (Just an interesting note here: Having Friendica set up to mirror my Twitter timeline, I am seeing Twitter posts via Fedilab too. For Twitter posts, I can do a "star" or "reshare" and both works without displaying any particular error message in Fedilab... Not sure if this is related but it's a bit odd for sure.)

I think that is, because Twitter API is implemented correctly and mastodon API is either lacking support for some API functionalities or has problems with current implementation.

**Comment by foss-** [comment]
A lot has changed in past months:
- https://codeberg.org/tom79/Fedilab/issues/68 (fixed)
- https://codeberg.org/tom79/Fedilab/issues/134 (fixed)
- https://codeberg.org/tom79/Fedilab/issues/247 (fixed)
- https://github.com/friendica/friendica/pull/12231 probably addresses the remaining issue with unstarring / unfavorite an item.
- Starring a post in friendica webUI is reflected as expected in Fedilab 3.7.4.

Remaining:
- https://github.com/friendica/friendica/issues/12233
- Did not test issue with the endpoint `api/v2/search` https://github.com/friendica/friendica/issues/11604#issuecomment-1180098022

@stom79 are you aware of other known issues with friendica and fedilab (mastodon API wise)?

For my taste this issue here touches on too many different problems and it is becoming hard to keep track of what is resolved and what remains a problem. Lets close this issue here and create single issues for the remaining issues.

**Comment by kr428** [comment]
FWIW I added a couple of issues prefixed mastodon-api recently that relate to this issue and usually are checked with at least two clients (fedilab and mostly tusky nightly). Essentially, most of the basics now seem to work but when it comes to more specific features (user notifications, list handling,...) there's still quite some room for improvement. 🙂

**Comment by foss-** [comment]
Asked tom via matrix chat whether there were remaining issues and they replied:

> For my test it was OK. I pinned [toot.fedilab.app](http://toot.fedilab.app/) from a Friendica account and then checked profile and messages. All were perfectly fetched with api/v2 and Friendica

This issue here should thus be closed.
