### ISSUE TITLE
Requests from 163.172.11.188 with suspicios user agent

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11607]
Hi @MrPetovan 

My Crowdsec IDS is detecting daily calls from 163.172.11.188 (friendica.mrpetovan.com) with suspicious user agent.

163.172.11.188 - - [04/Jun/2022:19:44:08 +0000] "GET /xrd?uri=https%3A%2F%2Ffm2.0x42.ch%2Fprofile%2Fstefan HTTP/1.1" 200 1734 "-" "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)" "163.172.11.188"
163.172.11.188 - - [04/Jun/2022:19:44:09 +0000] "GET /poco?fields=urls&count=1000 HTTP/1.1" 403 266 "-" "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)" "163.172.11.188"

This user agent is on many blocklists. It's originally an Internet Explorer 5.01 on Windows 2000..

**Comment by MrPetovan** [comment]
Hi, this is the official Friendica Directory at https://dir.friendica.social probing servers and profiles for public information. It's using the default curl User-Agent, I assume.

**Comment by MrPetovan** [comment]
Correction, it is using the default User-Agent set by a third-party curl wrapper library. I could update this string but I'm not sure what to put in. I'll figure something out, thank you for the report!

**Comment by ne20002** [comment]
The user agent is also listed in 
https://github.com/SigmaHQ/sigma/blob/master/rules/proxy/proxy_ua_malware.yml
as well as
Crowdsec bad user agents.

**Comment by MrPetovan** [comment]
Thank you for the elaboration, I'll update it.

**Comment by annando** [comment]
I guess best is to create a user agent string similar to the one used for Friendica. It contains the software, the host name and the version.

**Comment by MrPetovan** [comment]
Yes for the version, but we don't have the hostname information in the directory config at all.

**Comment by ne20002** [comment]
Most of the requests I get have a user-agent: 'friendica-directory-probe-1.0'
(which is fine)

**Comment by annando** [comment]
AFAIK there is a PHP command that returns the current hostname, isn't it?

So some `Friendica Directory 2.4.1; https://friendica.mrpetovan.com` would be fine, I think.

**Comment by MrPetovan** [comment]
My server is unlikely to have a friendly hostname, at the moment it's `sd-86364` 😅

**Comment by MrPetovan** [comment]
> Most of the requests I get have a user-agent: 'friendica-directory-probe-1.0' (which is fine)

Turns out I'm also using vanilla curl in the same project which has a custom user agent. Sounds like a project to normalize everything.

**Comment by MrPetovan** [comment]
Moved to the official directory repository: https://git.friendi.ca/friendica/friendica-directory/issues/89

**Comment by MrPetovan** [comment]
Hi @ne20002 , the PR I submitted was merged, and I updated https://dir.friendica.social, you shouldn't receive alerts related to this User-Agent anymore from my IP address. I'll prepare a release so that other Friendica directory installs won't bother you either.

**Comment by ne20002** [comment]
I can confirm that there are no more alerts.
Thank you.
