### ISSUE TITLE
Peertube videodescription shows words marked with exclamationmark, which are tags in video

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#11614]
As you can see, the word "Vogel" is marked with yellow exclamation-mark, because it is also a tag from peertubes video.

![grafik](https://user-images.githubusercontent.com/5894829/172237505-2dc2eed3-bfa8-41cf-8494-edeef796da26.png)

The original video is this
https://kino.schuerz.at/w/sGA6KKhhbpg5an7NzCw1r4

**Comment by tobiasd** [comment]
For some reason the word is enclosed in an `url` BBCode tag with the word as a target 
`[url=Vogel]Vogel[/url]`. Which is not a valid link target, hence it is marked that way.

**Comment by annando** [comment]
This issue is fixed in this commit: https://github.com/annando/friendica/commit/f7be610629a32eaca5f5ca2d22f90b5b5eb9e63a

**Comment by MrPetovan** [comment]
Fixed by #11882
