### ISSUE TITLE
Titles should not use the Markdown language interpretation

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11625]
I see that if any video is posted using in its title signs that belong to the Markdown language, they are getting converted or weirdly interpreted by friendica. Here is an example:
![2022-06-10_20-48](https://user-images.githubusercontent.com/38043315/173131141-84b8476f-2030-4b06-a467-49c9980696bf.png)

The video's title is "33. The Money Game and Beyond - Systems to Organize Societies - Part 6".

So I suggest you remove the option to interpret markdown for the titles of posts. Else it becomes messy. :)

**Comment by tobiasd** [comment]
Are you using the `markdown` addon for formatting your postings?

**Comment by tio-trom** [comment]
Yes sorry I forgot to mention that.

**Comment by tobiasd** [comment]
I checked importing Peertube videos with enabled or disabled Markdown addon, in both cases the title gets parsed.

**Comment by annando** [comment]
Can you provide a link to that video?

**Comment by tobiasd** [comment]
https://videos.trom.tf/videos/watch/fb24142d-1147-4961-a669-ac0cf582c251

**Comment by tio-trom** [comment]
thx for fixing
