### ISSUE TITLE
Editing in full screen mode (desktop browser)

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11634]
### Describe the feature you'd like

I also use Friendica as a personal blog. With the support of Markdown, I have all the formatting options I need for this and handle them well. 

For longer content, however, I quickly run into limits, as the clarity in the small edit box is very limited. Even if I enlarge the editor vertically, I miss the width in the horizontal.

Question: is it possible to open the editor in a full screen mode, so that I can use the entire screen area of the browser?
Would it be in the spirit of the Friendica developers to provide this possibility?
Then this function could possibly be implemented in the //compose/0 view, so that there is no negative impact on the mobile view?

**Comment by MrPetovan** [comment]
The “full-screen” editor is the Compose page. On mobile the text area field takes up the whole width of the screen.

We can look into extending the desktop-size page where the left column usually sits.

**Comment by loma-one** [comment]
That would be great and a real step forward.
Whereas I was actually thinking of a real editor that takes up the entire width and height of the screen. Maybe a left side for editing and a right side where you can see the output text.

That would be the golden solution and only make sense to use in the browser :)

**Comment by loma-one** [comment]
The [EasyMDEContainer](https://github.com/Ionaru/easy-markdown-editor) seems to be very powerful and has all the features I expect from an editor. I especially want to emphasize the full screen mode and the division into a right and left half with preview. 

Wouldn't the editor be a great asset to the project?

**Comment by loma-one** [comment]
No change is currently being considered. Therefore closed here.
