### ISSUE TITLE
Data too long for column 'site_name'

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#11638]
From the log of Friendica 2022.06:

```
[ERROR]: DB Error {
    "code": 1406,
    "error": "Data too long for column 'site_name' at row 1",
    "callstack": "DBA::insert, GServer::detect, GServer::check, GServer::getID, APContact::getByURL, HTTPSignature::fetchKey, HTTPSignature::getSigner, Followers::rawContent",
    "params":"INSERT INTO `gserver` (`detection-method`, `register_policy`, `platform`, `version`, `site_name`, `network`, `noscrape`, `directory-type`, `url`, `nurl`, `registered-users`, `next_contact`, `last_contact`, `failed`, `created`) VALUES (102, 2, 'friendica', '2022.05-rc', 'Ibbtown.com    ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  ⠀  <br><br>  <b><a href=\\\"https://ibbtown.com/display/2338580c-1962-7bf4-1ee6-f5f584362672\\\">Was ist das hier?</a></b> | <b><a href=\\\"https://ibbtown.com/community/\\\">Öffentliche Zeitleiste</a></b> | <b>Admin: @<a href=\\\"https://ibbtown.com/profile/ibbtown\\\">ibbtown</a></b> <br><br><b><a href=\\\"https://ibb.town\\\">ibb.town</a></b> | <b><a href=\\\"https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7DPJ7XTJZ4UGW\\\">Kaffeekasse</a></b> | <b><a href=\\\"https://ibb.town/kontakt\\\">Kontakt & Datenschutzerklärung</a></b>', 'dfrn', 'https://ibbtown.com/noscrape', 2, 'https://ibbtown.com', 'http://ibbtown.com', 1, '2022-06-19 14:30:25', '2022-06-12 14:30:25', 0, '2022-06-12 14:30:25')"
} - {
    "file": "Database.php",
    "line": 782,
    "function": "e",
    "uid": "b346e9",
    "process_id": 77702
}
```

**Comment by SpcCw** [comment]
I am getting these too for quite some time (before this version too) and it is the same site.

**Comment by Quix0r** [comment]
According to `static/dbstructure.php` it is `varchar(255)`. Can you please check (if possible) what length is used in your table?
````
"site_name" => ["type" => "varchar(255)", "not null" => "1", "default" => "", "comment" => ""],
````
Above comes directly from the source code and it was changed by @annando in 2020-05-22.

**Comment by Quix0r** [comment]
I wrote him a friendly email to please change the title.

**Comment by Quix0r** [comment]
I think one solution is to allow only 255 characters (and filter out HTML) for the Friendica's site name. Hmm, there is no `maxlength` supported by `templates/field_input.tpl`.

**Comment by annando** [comment]
We have got some functionality that can check content for stuff the maximum length. I can have a look at it.

**Comment by Quix0r** [comment]
@annando Does also the form field enforce the maximum length presented by the database column? Means adding support for `maxlength="$maxlength"` parameter?

**Comment by annando** [comment]
What do you mean with `maxlength`?

**Comment by Quix0r** [comment]
`<input name="site_name" maxlength="255" />` That sort of thing. :-)

**Comment by MrPetovan** [comment]
This is a remote server publishing their own very long name, nothing we can fix with a limited form field on our end.

**Comment by Quix0r** [comment]
Yes, true. The `maxlength` prevents it on the other server side during entering it into the form. You don't know what people squeeze into that little `<input>` field with a copy-paste ... :-/

**Comment by urbalazs** [comment]
Fix me if I am wrong but Frendica can federate with many other software like BirdsiteLIVE, BookWyrm, Diaspora, GNU Social/Statusnet, Hometown, Hubzilla/Red Matrix, Lemmy, Mastodon, Misskey, Mobilizon, Mistpark, Osada, Roadhouse, Zap, Peertube, Pixelfed, Pleroma, SocialHome, WordPress, WriteFreely etc. You cannot restrict all of them unless you make pull requests for each. This kind of database issue should be handled by Friendica and do not trust in the other side.

**Comment by Quix0r** [comment]
And? What does that say to me? I'm aware of that most of these software use `ActivityPub` as a federation protocol. So e.g. a 16k long title in `<title>` makes sense to you? Feels a bit spamming to me. Nobody reads such horrible long title plus screen readers like blind people use will talk to the person endlessly only because of a title (and it will also talk tags and URLs). Makes sense to you?

**Comment by annando** [comment]
It's not a big deal to perform some checks upon storing the data. Some information loss on that field doesn't matter at all. We aren't actively using that special field.
