### ISSUE TITLE
Feature Request: Using Web Notifications

### ISSUE THREAD

**Issue by annando** [friendica/friendica#1163]
See http://www.w3.org/TR/notifications/ and this example: http://jsbin.com/notification/1/edit

**Comment by FlxAlbroscheit** [comment]
Could take care about this issue. However, I'm asking myself what makes more sense: Including this feature into Friendica's core (So it can be activated under e.g. "Settings -> Additional features") or putting it into an own add-on?

**Comment by fabrixxm** [comment]
I would add it to core and modify Settings -> Notification Settings

**Comment by Hypolite** [comment]
This issue can be closed, it seems.

**Comment by annando** [comment]
No. We added it but the implementation wasn't so good.

**Comment by Hypolite** [comment]
What is the current issue with it? Aside from HTML entities showing up as such (#2804)?

**Comment by annando** [comment]
Maybe I'm wrong but I thought there were problems with notifications concerning seen and unseen notifications. (And I thought that we had disabled the code - but obviously we hadn't)

**Comment by Hypolite** [comment]
It's not disabled and it's working almost as expected, there is a little catch in that clicking on the notification doesn't do anything (it's supposed to go to the related URL), but aside from that it's working fine.

**Comment by annando** [comment]
Fine! So maybe you could fix that little catch? ;-)

**Comment by Hypolite** [comment]
Sure, but this present feature request can be closed. I'll open a new issue for the little catch.
