### ISSUE TITLE
Notify only when someone replies to your comments/posts

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11648]
I know you have added new notification options to the latest stable, but I'd argue we are missing an important one: only notify when someone replies to your comments/posts. If I see a post, and comment, I am interested in the replies for that comment, not in everything everyone comments on that post. I think this is the sane way. It is an improvement the fact that I can now like posts without being notified about all interactions on that post. But if I dare to comment on a post, I'll get notifications for any comment posted on that post.

Thanks!

**Comment by annando** [comment]
Exactly this can be done with the new settings as well.

**Comment by tio-trom** [comment]
hm...which one is it then:

![2022-06-16_17-34](https://user-images.githubusercontent.com/38043315/174106842-8c6ff555-e8d8-455c-927a-33d8be817696.png)

**Comment by Quix0r** [comment]
@tio-trom The 2nd one needs to be checked only for you.

**Comment by tio-trom** [comment]
> @tio-trom The 2nd one needs to be checked only for you.

I am confused....the "Someone directly commented on your post"? Is this the one that I am looking for?

**Comment by Quix0r** [comment]
@tio-trom The logic in source code says this:
````
$notify_type = $notify_type | (UserNotification::TYPE_IMPLICIT_TAGGED + UserNotification::TYPE_DIRECT_COMMENT + UserNotification::TYPE_DIRECT_THREAD_COMMENT);
````
So on all these 3 notification types you are being notified if that checkbox is set.

**Comment by tio-trom** [comment]
So I want to get a notification if someone comments on any of my posts but also on any comment I make on any post. Basically comments to my comments and posts, is what I am interested in. But now, as far as I understand, if I am to comment on a post, then anyone who comments there (not replies to my comment necessarily) will trigger a notification for me. Am I getting it wrong?

**Comment by MrPetovan** [comment]
No, you're right, it sounds like you should uncheck the "Someone commented in a thread where you commented".

**Comment by tio-trom** [comment]
Ah ok but will I get a notification if someone replies to any of my comments in others' threads/posts?

**Comment by MrPetovan** [comment]
Maybe "Someone commented directly on your post" would work?

**Comment by tio-trom** [comment]
I would suggest to rename them somehow else creates confusion.

Notify me when:

- I am tagged
- I get a friend request
- I am followed

- My post is liked
- My post is shared
- My post gets a comment

- My comment is liked
- My comment is shared
- My comment gets a reply

I would personally leave it at that. And if anyone wants to receive notifications for a thread they can click that thread and follow. Makes no sense to get spammed if you simply like a post, whenever anyone interacts with that post :D 

But those are my suggestions because now I am confused. I simply want to get notifications when: I am tagged, my post is being shared, my post gets a comment, and my comment gets a reply. To me these are important but idk how and what to select :D

**Comment by tio-trom** [comment]
> Maybe "Someone commented directly on your post" would work?

But would this mean when someone commented on a comment of mine? If I get a reply, in other words...

**Comment by SpcCw** [comment]
Maybe  "Someone commented directly on your post" should be renamed to  "Someone commented directly on your post or comment" to add clarity.

I had no idea it applied to comments as well. Otherwise I see no problem with new settings.

**Comment by tio-trom** [comment]
Ok I tested it and indeed with these settings:
![2022-06-17_22-02](https://user-images.githubusercontent.com/38043315/174393874-fafe8d63-31dc-4a5e-bc7e-5337556c9558.png)
I get a notification only when someone replies to my comments. I find the options there confusing to be honest. My best suggestion is above. https://github.com/friendica/friendica/issues/11648#issuecomment-1158025126 - I will close this issue however please consider renaming these options. Thanks!
