### ISSUE TITLE
Many posts in the timeline are very old. Why?

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#11650]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Since the last release a few days ago, my /network is full of old post, it is all weeks, months, years old posts that come in by relay (I guess), I see these just came in but the creation date is way in the past. 

Generally that would not be a problem, but I think it is thousands of posts each day and my database is growing really fast right now. 

I see the same on both my Friendica servers. 

### Steps to Reproduce

1. Run latest Friendica stable release. 
/End

### Platform Info

Friendica Version:  2022.06 

Friendica Source: git

PHP version: 7.3 or so, latest 7.x release for sure. 

SQL version: Not sure

**Comment by annando** [comment]
Since this version the system fetches pinned posts - and they can be old.

**Comment by utzer** [comment]
> Since this version the system fetches pinned posts - and they can be old.

But who has this thousands of posts pinned? My timeline looks like that since the release. Constantly the majority of posts is old. I only follow 1300 accounts, so who's pinned posts are these?

**Comment by annando** [comment]
Are you following hash tags?
