### ISSUE TITLE
Worker causes "Maximum function nesting level of '256' reached, aborting!"

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#11651]
- [x] I have searched open and closed issues for duplicates

In `friendica.log` the above message appears repeatedly:
https://f.haeder.net/friendica.log.txt (irrelevant lines removed)

The worker however seem to work?

### Steps to Reproduce

1.  Just start the worker as daemon

Actual Result:

No side-effects noticed so far. I just wonder what the worker has attempted to do?

Expected Result:

The message should not appear at all in log file.

### Platform Info

Friendica Version: `develop` @ 51b31a846f0ab6128c6c9cb3d54aa47f4a97d809

Friendica Source: `git`

PHP version: `PHP 7.3.29-1~deb10u1`

SQL version: `mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by MrPetovan** [comment]
Looks like recursive thread completion hits on the language soft limit, this isn't ideal, we should use a loop instead of recursion for this case, something like this:
```php
do {
  $url = array_pop($urlsToFetch);
  $result = fetch($url);
  if ($result['parentUrl']) {
    array_push($urlsToFetch, $result['parentUrl']);
  }
}while(count($urlsToFetch) > 0);
```

**Comment by Quix0r** [comment]
@MrPetovan Where do you think this needs to be implemented? Maybe I can take a look into it.

**Comment by MrPetovan** [comment]
Somewhere between `Processor::fetchMissingActivity` and `Receiver::processActivity` it looks like from your helpful log.

**Comment by Quix0r** [comment]
I maybe have something here:
`b/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#175 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#176 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#177 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#178 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#179 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#180 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#181 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#182 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#183 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#184 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#185 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#186 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#187 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#188 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#189 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#190 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#191 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#192 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#193 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#194 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#195 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#196 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#197 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#198 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#199 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#200 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#201 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#202 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#203 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#204 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#205 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#206 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#207 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#208 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#209 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#210 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#211 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#212 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#213 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#214 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#215 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#216 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#217 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#218 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#219 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#220 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#221 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#222 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#223 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#224 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#225 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#226 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#227 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#228 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#229 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#230 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#231 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#232 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#233 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#234 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#235 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#236 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#237 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#238 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#239 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#240 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#241 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#242 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#243 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#244 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#245 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(282): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...', Array, '', 4)\n#246 /var/www/.../htdocs/src/Protocol/ActivityPub/Receiver.php(564): Friendica\\Protocol\\ActivityPub\\Processor::createItem(Array)\n#247 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1197): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity(Array, '{\"@context\":[\"h...', 0, true, false, Array)\n#248 /var/www/.../htdocs/src/Model/Item.php(3414): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity('https://mastodo...')\n#249 /var/www/.../htdocs/src/Protocol/ActivityPub/Processor.php(1077): Friendica\\Model\\Item::fetchByLink('https://mastodo...')\n#250 /var/www/.../htdocs/src/Worker/FetchFeaturedPosts.php(36): Friendica\\Protocol\\ActivityPub\\Processor::fetchFeaturedPosts('https://mastodo...')\n#251 [internal function]: Friendica\\Worker\\FetchFeaturedPosts::execute('https://mastodo...')\n#252 /var/www/.../htdocs/src/Core/Worker.php(486): call_user_func_array('Friendica\\\\Worke...', Array)\n#253 /var/www/.../htdocs/src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction(Array, 'FetchFeaturedPo...', Array, true)\n#254 /var/www/.../htdocs/src/Core/Worker.php(106): Friendica\\Core\\Worker::execute(Array)\n#255 /var/www/.../htdocs/bin/worker.php(86): Friendica\\Core\\Worker::processQueue(false, Object(Friendica\\Core\\Worker\\Entity\\Process))\n#256 {main}"} - {"file":null,"line":null,"function":null,"uid":"353a23","process_id":23622}`

**Comment by MrPetovan** [comment]
I'm experiencing this issue as well, it's been delaying all the other worker tasks including delivery.
