### ISSUE TITLE
Friendica WSoD caused by cookienotice addon

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11695]
I do not know how to continue. For two days I've had a WSoD under the domain etiketi.de under which Friendica is running.
I rule out that the error is caused by a git pull because my Friendica continues to run normally under Twidere. What I suspect is that something broke during the last storage space optimization on the server.
I can't find anything in the logs either, does anyone have a tip or an idea where I could look further?
There is either something wrong with the database or with the website.

**Comment by SpcCw** [comment]
Maybe unrelated but I also got WSoD after pulling develop a few days ago. I was short on time and I just reverted webserver files (just them) to the nightly backup without investigating.

Right now I tried this again and the process went without issue.

**Comment by ghost** [comment]
It was exactly the same for me, except that unfortunately I didn't have a backup and the subsequent pulls didn't bring any improvement either

**Comment by MrPetovan** [comment]
Without any feedback from any log (PHP, Friendica, nginx?) it's hard for us to troubleshoot beyond general advice. What's the output of `> bin/console dbstructure update`?

**Comment by ghost** [comment]
> What's the output of `> bin/console dbstructure update`?

No output, the only thing i get from the server logs is this

```
500 | POST /receive/public HTTP/1.1
 500 | POST /receive/public HTTP/2.0
```
A lot of this
`(103)Software caused connection abort: [client 178.63.21.144:54102] AH01075: Error dispatching request to : (reading input brigade)`
Lot of this
`PHP Warning:  array_merge(): Expected parameter 1 to be an array, bool given in /src/Module/Profile/Status.php on line 213'`
Some of this
`PHP Fatal error:  Declaration of Friendica\\Content\\BoundariesPager::getStart() must be compatible with Friendica\\Content\\Pager::getStart(): int in /src/Content/BoundariesPager.php on line 76'`

**Comment by MrPetovan** [comment]
The latter one would trigger a 500 error, but it's been fixed already in https://github.com/friendica/friendica/pull/11701, can you confirm these errors happened before you updated to the latest `develop`

**Comment by ghost** [comment]
> The latter one would trigger a 500 error

Do you mean this?
`PHP Fatal error: Declaration of Friendica\\Content\\BoundariesPager::getStart() must be compatible with Friendica\\Content\\Pager::getStart(): int in /src/Content/BoundariesPager.php on line 76'`
I still have this error in the logs at 5 a.m. today. Latest gitpull

**Comment by MrPetovan** [comment]
Thanks, I can look into this.

**Comment by MrPetovan** [comment]
Can you please confirm the commit hash you pulled with `git rev-parse --verify HEAD` ?

**Comment by ghost** [comment]
> `git rev-parse --verify HEAD` ?

Output in the frindica folder = `da7bc082b934734cfc3ec94c5329cf23adf515e5`
Output in the addon folder = `fe4982d51b4c8ca0e0e44058e096549e555afee2
`

**Comment by MrPetovan** [comment]
Both look good, you shouldn't get this error anymore. Still WSOD?

**Comment by ghost** [comment]
😞 

![2022-07-02 17 38 16](https://user-images.githubusercontent.com/12480023/177007193-9f212b57-59a9-4d52-8823-7241283b3348.png)

**Comment by ghost** [comment]
But why does Friendica still work in Twidere but no longer in the web browser.

**Comment by MrPetovan** [comment]
It has to be something else. Please rotate both your Friendica and PHP/web server logs and paste here whatever is written in them after you get the 500 error.

**Comment by MrPetovan** [comment]
> But why does Friendica still work in Twidere but no longer in the web browser.

The API doesn't use the same code paths at the web frontend, so it has to be something specific to the web frontend.

**Comment by ghost** [comment]
> Please rotate both your Friendica and PHP/web

My Friendica log is off.
Can I get it switched on via FTP somehow?

**Comment by MrPetovan** [comment]
You can enable it from the command line:
```
$ bin/console config system debugging 1
$ bin/console config system loglevel notice
```

**Comment by ghost** [comment]
I'm being inundated with reports.
Will sort them out tomorrow and post here.

**Comment by MrPetovan** [comment]
You can reduce the verbosity with this:
```
$ bin/console config system loglevel warning
```

**Comment by ghost** [comment]
I get some of these

```
2022-07-03T03:49:47Z index [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to cookienotice_page_content_top() must be of the type array, string given, called in /home/users/zsemberi/www/friendica/src/Core/Hook.php on line 223" at /addon/cookienotice/cookienotice.php line 85 {"exception":"TypeError: Argument 2 passed to cookienotice_page_content_top() must be of the type array, string given, called in /src/Core/Hook.php on line 223 and defined in /addon/cookienotice/cookienotice.php:85\nStack trace:\n
#0 /src/Core/Hook.php(223): cookienotice_page_content_top()\n
#1 a/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()\n
#2 /src/App/Page.php(375): Friendica\\Core\\Hook::callAll()\n
#3 /src/App/Page.php(457): Friendica\\App\\Page->initContent()\n
#4 /src/App.php(725): Friendica\\App\\Page->run()\n
#5 a/index.php(44): Friendica\\App->runFrontend()\n#6 {main}"} - {"file":null,"line":null,"function":null,"uid":"b798e6","process_id":346694}
```
And plenty of these


```
2022-07-03T03:49:45Z worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":176,"function":"isReady","uid":"c4240a","process_id":507519}
2022-07-03T03:49:45Z worker [NOTICE]: Load: 2.79/20 - processes: 23620/14/96 (0:1, 30:1, 40:9, 50:3) - maximum: 13/20 [] - {"file":"Worker.php","line":727,"function":"tooMuchWorkers","uid":"795fc3","process_id":507521}
```

**Comment by ghost** [comment]
And this

```
2022-07-03T04:01:02Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Content\Smilies::pregHeart() must be of the type string, array given" at  /src/Content/Smilies.php line 276 {"exception":"TypeError: Argument 1 passed to Friendica\\Content\\Smilies::pregHeart() must be of the type string, array given in  /src/Content/Smilies.php:276\nStack trace:\n
#0 [internal function]: Friendica\\Content\\Smilies::pregHeart()\n
#1  /src/Content/Smilies.php(236): preg_replace_callback()\n
#2  /src/Content/Smilies.php(197): Friendica\\Content\\Smilies::replaceFromArray()\n
#3  /src/Content/Text/BBCode.php(1623): Friendica\\Content\\Smilies::replace()\n
#4  /src/Util/Strings.php(497): Friendica\\Content\\Text\\BBCode::Friendica\\Content\\Text\\{closure}()\n
#5  /src/Content/Text/BBCode.php(2400): Friendica\\Util\\Strings::performWithEscapedBlocks()\n
#6  /src/Content/Text/BBCode.php(1624): Friendica\\Content\\Text\\BBCode::performWithEscapedTags()\n
#7  /src/Util/Strings.php(497): Friendica\\Content\\Text\\BBCode::Friendica\\Content\\Text\\{closure}()\n
#8  /src/Content/Text/BBCode.php(2400): Friendica\\Util\\Strings::performWithEscapedBlocks()\n
#9  /src/Content/Text/BBCode.php(2087): Friendica\\Content\\Text\\BBCode::performWithEscapedTags()\n
#10  /src/Util/Strings.php(497): Friendica\\Content\\Text\\BBCode::Friendica\\Content\\Text\\{closure}()\n
#11  /src/Content/Text/BBCode.php(2400): Friendica\\Util\\Strings::performWithEscapedBlocks()\n
#12  /src/Content/Text/BBCode.php(2100): Friendica\\Content\\Text\\BBCode::performWithEscapedTags()\n
#13  /src/Content/Text/BBCode.php(465): Friendica\\Content\\Text\\BBCode::convert()\n
#14  /src/Model/Item.php(1791): Friendica\\Content\\Text\\BBCode::toPlaintext()\n
#15  /src/Model/Item.php(880): Friendica\\Model\\Item::getLanguage()\n
#16  /src/Protocol/ActivityPub/Processor.php(890): Friendica\\Model\\Item::insert()\n
#17  /src/Protocol/ActivityPub/Receiver.php(573): Friendica\\Protocol\\ActivityPub\\Processor::postItem()\n
#18  /src/Protocol/ActivityPub/Processor.php(1208): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity()\n
#19  /src/Model/Item.php(3415): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity()\n
#20  /src/Protocol/ActivityPub/Processor.php(1086): Friendica\\Model\\Item::fetchByLink()\n
#21  /src/Worker/FetchFeaturedPosts.php(36): Friendica\\Protocol\\ActivityPub\\Processor::fetchFeaturedPosts()\n
#22 [internal function]: Friendica\\Worker\\FetchFeaturedPosts::execute()\n
#23  /src/Core/Worker.php(486): call_user_func_array()\n
#24  /src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n
#25  /src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n
#26  /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n
#27 {main}"} - {"file":null,"line":null,"function":null,"uid":"d5552b","process_id":514214}
```

**Comment by ghost** [comment]
```
`2022-07-03T04:01:39Z worker [ERROR]: Uncaught Exception TypeError: "Return value of Friendica\Protocol\ActivityPub\Transmitter::createCachedActivityFromItem() must be of the type array, bool returned" at /src/Protocol/ActivityPub/Transmitter.php line 1203 {"exception":"TypeError: Return value of Friendica\\Protocol\\ActivityPub\\Transmitter::createCachedActivityFromItem() must be of the type array, bool returned in /src/Protocol/ActivityPub/Transmitter.php:1203\nStack trace:\n
#0 /src/Protocol/ActivityPub/Delivery.php(113): Friendica\\Protocol\\ActivityPub\\Transmitter::createCachedActivityFromItem()\n
#1 /src/Worker/APDelivery.php(72): Friendica\\Protocol\\ActivityPub\\Delivery::deliverToInbox()\n
#2 [internal function]: Friendica\\Worker\\APDelivery::execute()\n
#3 /src/Core/Worker.php(486): call_user_func_array()\n
#4 /src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n
#5 /src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n
#6 /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n
#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"94ae08","process_id":514607}
`
```

**Comment by ghost** [comment]
```
2022-07-03T04:00:03Z worker [ERROR]: Uncaught Exception TypeError: "Return value of Friendica\Protocol\ActivityPub\Transmitter::createCachedActivityFromItem() must be of the type array, bool returned" at /src/Protocol/ActivityPub/Transmitter.php line 1210 {"exception":"TypeError: Return value of Friendica\\Protocol\\ActivityPub\\Transmitter::createCachedActivityFromItem() must be of the type array, bool returned in /src/Protocol/ActivityPub/Transmitter.php:1210\nStack trace:\n
#0 /src/Protocol/ActivityPub/Delivery.php(113): Friendica\\Protocol\\ActivityPub\\Transmitter::createCachedActivityFromItem()\n
#1 /src/Worker/APDelivery.php(72): Friendica\\Protocol\\ActivityPub\\Delivery::deliverToInbox()\n
#2 [internal function]: Friendica\\Worker\\APDelivery::execute()\n
#3 /src/Core/Worker.php(486): call_user_func_array()\n
#4 /src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n
#5 /src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n
#6 /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n
#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"a815c7","process_id":513808}
```

**Comment by MrPetovan** [comment]
> I get some of these
> 
> ```
> 2022-07-03T03:49:47Z index [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to cookienotice_page_content_top() must be of the type array, string given, called in /home/users/zsemberi/www/friendica/src/Core/Hook.php on line 223" at /addon/cookienotice/cookienotice.php line 85 {"exception":"TypeError: Argument 2 passed to cookienotice_page_content_top() must be of the type array, string given, called in /src/Core/Hook.php on line 223 and defined in /addon/cookienotice/cookienotice.php:85\nStack trace:\n
> #0 /src/Core/Hook.php(223): cookienotice_page_content_top()\n
> #1 a/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()\n
> #2 /src/App/Page.php(375): Friendica\\Core\\Hook::callAll()\n
> #3 /src/App/Page.php(457): Friendica\\App\\Page->initContent()\n
> #4 /src/App.php(725): Friendica\\App\\Page->run()\n
> #5 a/index.php(44): Friendica\\App->runFrontend()\n#6 {main}"} - {"file":null,"line":null,"function":null,"uid":"b798e6","process_id":346694}
> ```

That's the one we want. It doesn't trigger with API calls since it's a frontend-only addon. I'll submit a patch immediately.

**Comment by MrPetovan** [comment]
@copiis You can manually apply the patch in https://github.com/friendica/friendica-addons/pull/1270 to restore your system.

**Comment by ghost** [comment]
How do i do this?

**Comment by copiis** [comment]
I made a git pull an a server restart but i stil have a WSoD and a lot of this

```
2022-07-03T04:51:25Z index [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to cookienotice_page_end() must be of the type array, string given, called in /src/Core/Hook.php on line 223" at /addon/cookienotice/cookienotice.php line 101 {"exception":"TypeError: Argument 2 passed to cookienotice_page_end() must be of the type array, string given, called in /src/Core/Hook.php on line 223 and defined in /addon/cookienotice/cookienotice.php:101\nStack trace:\n
#0 /src/Core/Hook.php(223): cookienotice_page_end()\n
#1 /src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()\n
#2 /src/App/Page.php(488): Friendica\\Core\\Hook::callAll()\n
#3 /src/App.php(725): Friendica\\App\\Page->run()\n
#4 /index.php(44): Friendica\\App->runFrontend()\n
#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"804ba2","process_id":1270}
```

**Comment by copiis** [comment]
I found these two errors
```

2022-07-03T05:04:07Z worker [ERROR]: Unable to find owner data for uid {"uid":3,"callstack":"Probe::localProbe, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue"} - {"file":"Transmitter.php","line":443,"function":"getProfile","uid":"a14ec2","process_id":9433}


2022-07-03T05:04:27Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'posted' in 'order clause'","callstack":"Photo::selectToArray, photos_content, LegacyModule::runModuleFunction, LegacyModule::content, BaseModule::run, App::runFrontend","params":"SELECT `resource-id` FROM `photo` WHERE (`album` = 'Pinnwand-Bilder' AND `uid` = 2 AND `scale` = 0 AND (allow_cid = '' AND allow_gid = '' AND deny_cid = '' AND deny_gid = '') ) ORDER BY `posted` DESC"} - {"file":"Database.php","line":694,"function":"p","uid":"810a2f","process_id":979}

```

**Comment by MrPetovan** [comment]
Now you can pull both friendica and addons and you should be good to go.

> How do i do this?

In this case, you could change the file manually since there's only one change in one file. For larger pull requests, you would have to add a new git remote pointing at my Friendica fork:

```
$ git remote add MrPetovan https://github.com/MrPetovan/friendica
$ git fetch MrPetovan (or --all)
```
Then you have to pull the branch that is referenced in the pull request
```
$ git checkout MrPetovan/bug/fatal-errors
```
To go back to a regular branch once the PR is merged
```
$ git checkout develop
$ git pull
```
