### ISSUE TITLE
Add RSS as contact ends in an error message

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11706]
Here is the error message.
After that the contact is in your contact list but it cannot be deleted or clicked on or set as remote_self
```
#0 src/Model/Contact.php(2667): Friendica\Model\Group::addMember()
#1 mod/follow.php(177): Friendica\Model\Contact::createFromProbeForUser()
#2 mod/follow.php(48): follow_process()
#3 src/LegacyModule.php(96): follow_post()
#4 src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#5 src/BaseModule.php(223): Friendica\LegacyModule->post()
#6 src/App.php(712): Friendica\BaseModule->run()
#7 index.php(44): Friendica\App->runFrontend()
#8 {main}
```

I am on latest develop

**Comment by MrPetovan** [comment]
Thanks for the report, but this is just a stack trace, which means whatever error message should be one line above in your log.

**Comment by ghost** [comment]
This is the only thing I have found.
Should I look for something specific?

```
Got error 'PHP message: 
PHP Notice:  Undefined index: guid in /src/Model/FContact.php on line 95
PHP message:
PHP Notice:  Undefined index: request in /src/Model/FContact.php on line 107
PHP message: 
PHP Notice:  Undefined index: nick in /src/Model/FContact.php on line 107
PHP message: 
PHP Notice:  Undefined index: addr in /src/Model/FContact.php on line 108
PHP message: 
PHP Notice:  Undefined index: guid in /src/Model/FContact.php on line 108
PHP message: 
PHP Notice:  Undefined index: batch in /src/Model/FContact.php on line 109
PHP message: 
PHP Notice:  Undefined index: notify in /src/Model/FContact.php on line 109
PHP message: 
PHP Notice:  Undefined index: poll in /src/Model/FContact.php on line 110
PHP message: 
PHP Notice:  Undefined index: confirm in /src/Model/FContact.php on line 110
PHP message: 
PHP Notice:  Undefined index: alias in /src/Model/FContact.php on line 111
PHP message: 
PHP Notice:  Undefined index: pubkey in /src/Model/FContact.php on line 111'
```

**Comment by ghost** [comment]
> Thanks for the report, but this is just a stack trace, which means whatever error message should be one line above in your log.

Thats not from the log it is from the `https://etiketi.de/follow page` and abowe it is just
```
Not Found
Invalid contact.
```

**Comment by ghost** [comment]
I get this message when I try to go to the contact's profile page.
```
Exception thrown in /src/Module/Contact/Profile.php:141
Stack trace:
#0 /src/BaseModule.php(244): Friendica\Module\Contact\Profile->content()
#1 /src/App.php(722): Friendica\BaseModule->run()
#2 /index.php(44): Friendica\App->runFrontend()
#3 {main}
```

**Comment by MrPetovan** [comment]
Thanks, all of this should be enough for me to troubleshoot.

**Comment by MrPetovan** [comment]
Can you please check if there are any `contact` table rows having NULL in their `uri-id` column like this:
```
SELECT COUNT(*) FROM `contact` WHERE `uri-id` IS NULL;
```

**Comment by ghost** [comment]
> Can you please check if there are any `contact` table rows having NULL in their `uri-id` column like this:

There is no value 0 in the `uri-id` column.

But I noticed something else.
For example, when I want to add this feed `https://www.notateslaapp.com/rss` everything works fine.
But when I want to add this feed `https://lingerie-lush.com/feed/` then comes the, above described error message.

**Comment by MrPetovan** [comment]
Ah, thanks for the examples, this is what I was going to ask you next.

**Comment by MrPetovan** [comment]
I am not able to reproduce the error with the above feed URL unfortunately, so it seems to be a local oddity on your system. Can you please ban and purge this contact URL from the admin, unban it and try to add it as a contact again to see if it can correct itself?

**Comment by ghost** [comment]
> Can you please ban and purge this contact URL from the admin, unban it and try to add it as a contact again to see if it can correct itself?

That solved the problem
