### ISSUE TITLE
500 Internal Server Error on Network Page

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#11700]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

White Screen of Death (500 Internal Server Error) on _/network_ Page

### Steps to Reproduce

Call the _/network_ Page

Actual Result:

A white screen of death

Expected Result:

See the content of the _/network_ Page

### Log Entrys

PHP log
```
PHP Fatal error:  Declaration of Friendica\Content\BoundariesPager::getStart() must be compatible with Friendica\Content\Pager::getStart(): int in /src/Content/BoundariesPager.php on line 76
```
Friendica Log:
```
[ALERT]: Fatal Error (E_COMPILE_ERROR): Declaration of Friendica\Content\BoundariesPager::getStart() must be compatible with Friendica\Content\Pager::getStart(): int {"code":64,"message":"Declaration of Friendica\\Content\\BoundariesPager::getStart() must be compatible with Friendica\\Content\\Pager::getStart(): int","file":"/src/Content/BoundariesPager.php","line":76,"trace":null} - {"file":null,"line":null,"function":null,"uid":"4e396e","process_id":25063}
```

### Platform Info

Friendica Version:

Friendica 'Giant Rhubarb' 2022.09-dev - 1473

Friendica Source: git

PHP version: 8.0

**Comment by MrPetovan** [comment]
Paging @Quix0r

**Comment by Quix0r** [comment]
This and other methods just miss a returned type-hint. Edit: How can we unit-test these classes? cc @nupplaphil
