### ISSUE TITLE
Twitter: Replies to own posts sometimes aren't attached to original conversation

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11707]
I've notice over the last couple of months some Twitter replies to my own posts don't get attached to the original conversation but instead start a new one, like this example:
![twitter_reply_conversation](https://user-images.githubusercontent.com/925415/177192102-98bdc9ed-f1b5-460b-b2f1-fcb87a952bab.jpg)
Original reply: https://twitter.com/FabricThief/status/1541450710620835840

Not sure how to reproduce or troubleshoot.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
