### ISSUE TITLE
2FA: Clicking on "Trust" reloads the same page

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11712]
Using 2FA, once I provided my TOTP code, I'm being asked if I want to trust this browser. Clicking on anything but "Trust" leads me to the desired page.

Clicking on "Trust" reloads the same page asking to trust the browser.

It's possible to navigate away from this page by using the top navigation. I didn't try to navigate before clicking on any button first.

**Comment by nupplaphil** [comment]
I'm not able to reproduce it, I tried it locally again and it works  ..
Can you provide some more details :-/

Do you see anything in the logs? Can you add a log of the network traffic? (so the chronologies of requests --> I'm using the webconsole for it)

**Comment by MrPetovan** [comment]
What log level do you expect something to show up?

**Comment by nupplaphil** [comment]
good question tbh ... I'll add some reasonable log-points :X

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/pull/11714 seems to have fixed the issue.
