### ISSUE TITLE
API should not return HTML but JSON

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11738]
> When I use the API /api/v1/accounts/verify_credentials with the wrong password, it returns a 401 error and as responseText a html page. According to this documentation https://git.friendi.ca/friendica/friendica/src/branch/develop/doc/api.md it should return a JSON as responseText. In earlier versions it returned a JSON. 

originally reported by [Marco R.](https://freunde.ma-nic.de/display/3e98eba8-1062-d1c0-86d3-b65596653277)

**Comment by nupplaphil** [comment]
It depends on the used extension for the call.

`/api/v1/accounts/verify_credentials.json` returns a JSON error, ` /api/v1/accounts/verify_credentials` doesnt'.
But it's like Twitter expects it as well.

Try
https://api.twitter.com/1.1/account/verify_credentials (empty page)
https://api.twitter.com/1.1/account/verify_credentials.json (JSON Error)

**Comment by nupplaphil** [comment]
> Ah okay. Didn't know about the different return with the .json call. Then I change my request in the app.

originally reported by [Marco R.](https://friendica.philipp.info/display/3e98eba8-8263-30b8-5f3d-b7c047066479)
