### ISSUE TITLE
frio: black accented is now white accented

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11732]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

Some of the latest fixes for frio introduced a new issue. Black accented styles are now displayed as white accented.

### Steps to Reproduce

1.  select frio color scheme 'black accented'
2.  for safety reasons put on sunglasses 
3.  press 'submit' to save settings

Actual Result:

Color scheme is white accented.

Expected Result:

Should be black accented.

### Platform Info

Friendica Version:
2022.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
Introduced by https://github.com/friendica/friendica/pull/11729
