### ISSUE TITLE
js_upload - Error 500 an Uncaught Exception TypeError when uploading a new photo

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11731]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

When I upload a new photo by using the drop-zone of js_upload  addon I get an error message that the upload wasn't successful. But in fact the new image is stored in the selected album. The upload actually works despite the error message.

However. There is an error 500 in Apache's log and an error in Friendica's log. 

Apache error 500:
```
[13/Jul/2022:15:33:33 +0000] "POST /photos/alfred?newalbum=&album=Test&not_visible=true&contact_allow=&group_allow=&contact_deny=&group_deny=&qqfile=baltic-sea-4095045_1280.jpg HTTP/2.0" 500 630 "https://libranet.de/photos/alfred/upload" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
```

Friendica error message:
```
2022-07-13T15:33:38Z index [ERROR]: 
Uncaught Exception TypeError: "Argument 2 passed to js_upload_post_end() must be of the type array, int given, 
called in /var/www/html/libranet/src/Core/Hook.php on line 223" 
at /var/www/html/libranet/addon/js_upload/js_upload.php line 84 
{"exception":"TypeError: Argument 2 passed to js_upload_post_end() must be of the type array, int given, 
called in /var/www/html/libranet/src/Core/Hook.php on line 223 
and defined in /var/www/html/libranet/addon/js_upload/js_upload.php:84
Stack trace:
#0 /var/www/html/libranet/src/Core/Hook.php(223): js_upload_post_end()
#1 /var/www/html/libranet/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()
#2 /var/www/html/libranet/mod/photos.php(774): Friendica\\Core\\Hook::callAll()
#3 /var/www/html/libranet/src/LegacyModule.php(96): photos_post()
#4 /var/www/html/libranet/src/LegacyModule.php(80): Friendica\\LegacyModule->runModuleFunction()
#5 /var/www/html/libranet/src/BaseModule.php(228): Friendica\\LegacyModule->post()
#6 /var/www/html/libranet/src/App.php(723): Friendica\\BaseModule->run()
#7 /var/www/html/libranet/index.php(44): Friendica\\App->runFrontend()
#8 {main}"} - 
{"file":null,"line":null,"function":null,"uid":"f92c8f","process_id":3054410}
```

### Steps to Reproduce

1.  use the js_upload addon to upload a new image
2.  go to https://lexample.com/photos/nickname/upload
3.  drop an image there
4.  see the message '...upload failed'
5.  check your photos
6.  check the logs

Actual Result:
Photo is uploaded successfully. But there is an error message and errors in Apache's and Friendica's log.

Expected Result:
Photo is uploaded successfully. No error messages. :-)

### Platform Info

Friendica Version:
2022.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by AlfredSK** [comment]
You don't need to use the 'drop image' function to trigger the error. It is sufficient to have js_upload addon enabled

**Comment by MrPetovan** [comment]
Paging @Quix0r

**Comment by Quix0r** [comment]
It is an `int`, `$item_id` in `mod/photos.php` line 774 says it.
