### ISSUE TITLE
Worker error

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11737]
```
Uncaught Exception Friendica\Core\Storage\Exception\StorageException: "Database storage failed to update " at /src/Core/Storage/Type/Database.php line 94 {"exception":"Exception: Got a packet bigger than 'max_allowed_packet' bytes in /src/Core/Storage/Type/Database.php:94\nStack trace:\n
#0 /src/Model/Photo.php(363): Friendica\\Core\\Storage\\Type\\Database->put()\n
#1 /src/Model/Photo.php(543): Friendica\\Model\\Photo::store()\n
#2 /src/Model/Contact.php(2146): Friendica\\Model\\Photo::importProfilePhoto()\n
#3 /src/Model/Contact.php(2480): Friendica\\Model\\Contact::updateAvatar()\n
#4 /src/Model/Contact.php(2335): Friendica\\Model\\Contact::updateFromProbeArray()\n
#5 /src/Worker/UpdateContact.php(37): Friendica\\Model\\Contact::updateFromProbe()\n
#6 [internal function]: Friendica\\Worker\\UpdateContact::execute()\n
#7 /src/Core/Worker.php(486): call_user_func_array()\n
#8 /src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n
#9 /src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n
#10 /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n
#11 {main}\n\nNext Friendica\\Core\\Storage\\Exception\\StorageException
```

**Comment by AlfredSK** [comment]
Sounds like someone tried to change the user avatar and used a very large image - larger than the allowed max packet size in the database configuration.

**Comment by ghost** [comment]
> larger than the allowed max packet size in the database configuration.

Hm, in the administration have set the maximum image size to 0, so without limit.

**Comment by AlfredSK** [comment]
> > larger than the allowed max packet size in the database configuration.
> 
> Hm, in the administration have set the maximum image size to 0, so without limit.

So, a user can upload a very large image. But it cannot be stored in the database because the DB server has a limit for the maximum size of data packages. On Debian based systems the default setting for MySQL/MariaDB is max. 16MB.

**Comment by ghost** [comment]
Then it was most likely a GIF, they are always so big

**Comment by annando** [comment]
The message is `Exception: Got a packet bigger than 'max_allowed_packet'`. 

I suggest to increase that number in your SQL server's config.

**Comment by ghost** [comment]
the error has not appeared again until now

closing
