### ISSUE TITLE
static content not cacheable?

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11749]
Hi

I have a number of requests to these two urls in my reverse proxy log:
```
/static/security-v1.jsonld
/static/activitystreams.jsonld
```
I wonder if those shouldn't be cacheable? Seems to be static content. I use the nginx template from examples in friendica/docker project.

**Comment by MrPetovan** [comment]
Yes, anything in the `static/` folder can be cached, as long as you clear the cache each release for potential changes.

**Comment by ne20002** [comment]
thx

**Comment by nupplaphil** [comment]
Good 2 know, I'll adapt the docker examples :-)
