### ISSUE TITLE
Invalid NodeInfo response when there is no usage data

### ISSUE THREAD

**Issue by SuperTux88** [friendica/friendica#11765]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Friendica produces an invalid NodeInfo response in some cases (probably when usage statistics are disabled?).

`The property '#/usage' did not contain a required property of 'users' `

Even if there is no usage data, at least an empty `users` object is always required, see the schema for NodeInfo 2.0 [here](https://github.com/jhass/nodeinfo/blob/main/schemas/2.0/schema.json#L135-L137) (but it's also the same for 1.0 and the issue exists there too)

The easiest way to prevent errors like this is to use unit-tests which validate the result against the schemas.

### Steps to Reproduce

1. go to a friendica server that doesn't provide usage data
2. go to `/nodeinfo/1.0` or `/nodeinfo/2.0`

Actual Result:

```json
{
    "version": "2.0",
    "...": "...",
    "usage": {},
    "...": "..."
}
```

Expected Result:

```json
{
    "version": "2.0",
    "...": "..."
    "usage": {"users": {}},
    "...": "..."
}
```

### Platform Info

Friendica Version: Since the validation fails, it also fails to read the version, and I'm too lazy to manually get the versions of all servers which fail. But since I didn't find any issues or pull requests about this, I assume it's all versions up to the current one.

A few random examples I got:
* https://friendica.nerdhaven.de/nodeinfo/2.0 (2022.02-1449)
* https://herkenhoff.com/nodeinfo/2.0 (2022.05-dev-1460)
* https://friendica.hellquist.eu/nodeinfo/2.0 (2022.06-1469)

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
Thank you for the report!
