### ISSUE TITLE
[frio] Can not change default Friendica Logo

### ISSUE THREAD

**Issue by bobyonekenobi86** [friendica/friendica#11774]
Hi!

Again I would like to ask for your assistance please.

I am trying to change the default Friendica logo and text in: Site Admin -> General Information -> Banner/Logo

This is what I try to achieve:

`<a href="https://friendcloud.hu"><img id="logo-img" width="218" height="32" src="https://friendica.hu/images/logo-horizontal-32x218.png" alt="logo" /></a><span id="logo-text"><a href="https://friendcloud.hu">friendcloud</a></span>`

or

`<a href="https://friendcloud.hu"><img id="logo-img" width="218" height="32" src="images/logo-horizontal-32x218.png" alt="logo" /></a><span id="logo-text"><a href="https://friendcloud.hu">friendcloud</a></span>`

I can open the image itself in the browser separately.

Interesting, that even if I leave the default and I only change the text in the `<span>` from "Friendica" to "Test", and leave everything on default, still nothing reflects. 

Could you please assist.
Thank you!

@MrPetovan edit: There are two issues that can be acted upon:
- The **site** logo/banner setting form field is present in the frio theme of the administration settings page but its value isn't used in the frio theme display.
- The **email** logo/banner setting form field isn't present in the frio theme of the administration settings page but its value is used in the outgoing emails that don't depend on any theme.

**Comment by MrPetovan** [comment]
Thanks for the report, it's possible the setting isn't used in practice, I'll check tonight EST.

**Comment by bobyonekenobi86** [comment]
[MrPetovan](https://github.com/MrPetovan), you are like a guardian angel. Thanks a lot! You are awesome! ;)

**Comment by MrPetovan** [comment]
I tried to reproduce this behavior successfully, but the simple reason is that frio isn't using this setting like the previous themes used to. The banner/icon is hardcoded in the theme files and doesn't use this setting at all. Ideally, this setting should be moved to the theme settings depending on the theme, thanks for bringing this up!

**Comment by bobyonekenobi86** [comment]
Can I also ask, that witch setting defines the logo and site name used in the system notification emails?

**Comment by MrPetovan** [comment]
> Can I also ask, that witch setting defines the logo and site name used in the system notification emails?

I found references to a setting key for the logo in the code that doesn't have a displayed form field in frio, I'm not sure why it was removed. @rabuzarus ?

On the other hand, the site name is hardcoded to the platform name, "Friendica".

**Comment by tobiasd** [comment]
The original author of frio did not like the changeability of the banner IIRC so he spend several days to get the Friendica logo at the correct place. If you want to use your own banner, you have to use one of the other themes at the moment.

**Comment by tio-trom** [comment]
Am sleepy right now so am not sure I fully get what you mean but I have created several themes for Friendica based on Frio (simple CSS) and the only way I could change the logo is to hack it a bit as such:

```
#logo-img {display:none;}
header #banner {
	position: fixed;
	left: 43%;
	right: 0;
	z-index: 1040;
	margin-top: 0.5px;
	padding-left: 55px;
	background-image: url('https://www.tromsite.com/wp-content/uploads/2021/02/trom.tf-big-white-black-tf.png');
	    background-size: 180px 50px;
    height: 50px;
    width: 180px;
}

```
I have removed it and used its div to insert a background image (my logo) at whatever dimensions I want.

**Comment by bobyonekenobi86** [comment]
[MrPetovan](https://github.com/MrPetovan), [tobiasd](https://github.com/tobiasd), Thanks for the update and the info!
[tio-trom](https://github.com/tio-trom) Thanks for the idea! I will use this workaround, but I presume every time I update the core of the Friendica to the latest version, I have to modify the css again. Am I right?

**Comment by bobyonekenobi86** [comment]
Also a small observation:
If I use the default frio - V.0.8.5 theme, on mobile (iPhone SE2) with different browsers (DuckDuckGo, Firefox, Safari), the logo is not visible, just the "Friendica" text.

**Comment by MrPetovan** [comment]
> [MrPetovan](https://github.com/MrPetovan), [tobiasd](https://github.com/tobiasd), Thanks for the update and the info! [tio-trom](https://github.com/tio-trom) Thanks for the idea! I will use this workaround, but I presume every time I update the core of the Friendica to the latest version, I have to modify the css again. Am I right?

@bobyonekenobi86 If you want to mention people on here you can use the @-sign followed by their pseudonym instead of plain links to their profile page.

> The original author of frio did not like the changeability of the banner IIRC so he spend several days to get the Friendica logo at the correct place. If you want to use your own banner, you have to use one of the other themes at the moment.

@tobiasd I hear you but there are two separate issues here:
- The site logo/banner setting form field is present in the frio theme of the administration settings page but its value isn't used in the frio theme display.
- The email logo/banner setting form field isn't present in the frio theme of the administration settings page but its value is used in the outgoing emails that don't depend on any theme.

**Comment by tio-trom** [comment]
> tio-trom Thanks for the idea! I will use this workaround, but I presume every time I update the core of the Friendica to the latest version, I have to modify the css again. Am I right?

It seems like, yes.

**Comment by tobiasd** [comment]
On Tue, Jul 26, 2022 at 10:27:49AM -0700, bobyonekenobi86 wrote:
> Hi!
>
> Again I would like to ask for your assistance please.
>
> I am trying to change the default Friendica logo and text in: Site Admin -> General Information -> Banner/Logo

Hi, sadly with the frio theme you cannot change the banner/logo displayed on the
pages. This is only possible with the other themes.
