### ISSUE TITLE
PHPMailer Issue: Could not instantiate mail function.

### ISSUE THREAD

**Issue by bobyonekenobi86** [friendica/friendica#11772]
Dear Team,

I am trying to get phpmailer working, but I cant.

I receive the following message in the log (level: error):
"Could not instantiate mail function."
`phpmailer.php | 108 | phpmailer_emailer_send_prepare
`
```
PHPMailer\PHPMailer\Exception: Could not instantiate mail function. in /var/www/friendcloud/addon/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php:1943
Stack trace:

#0 /var/www/friendcloud/addon/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php(1664): PHPMailer\PHPMailer\PHPMailer->mailSend()
#1 /var/www/friendcloud/addon/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php(1500): PHPMailer\PHPMailer\PHPMailer->postSend()
#2 /var/www/friendcloud/addon/phpmailer/phpmailer.php(104): PHPMailer\PHPMailer\PHPMailer->send()
#3 /var/www/friendcloud/src/Core/Hook.php(217): phpmailer_emailer_send_prepare()
#4 /var/www/friendcloud/src/Core/Hook.php(193): Friendica\Core\Hook::callSingle()
#5 /var/www/friendcloud/src/Util/Emailer.php(131): Friendica\Core\Hook::callAll()
#6 /var/www/friendcloud/mod/lostpass.php(89): Friendica\Util\Emailer->send()
#7 /var/www/friendcloud/src/LegacyModule.php(96): lostpass_post()
#8 /var/www/friendcloud/src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#9 /var/www/friendcloud/src/BaseModule.php(223): Friendica\LegacyModule->post()
#10 /var/www/friendcloud/src/App.php(712): Friendica\BaseModule->run()
#11 /var/www/friendcloud/index.php(44): Friendica\App->runFrontend()
#12 {main}
```

My config is the following in config/addon.config.php:

```
<?php
return [
        'phpmailer' => [
                // smtp (Boolean)
                // Enables SMTP relaying for outbound emails
                'smtp' => false,

                // smtp_server (String)
                // SMTP server host name
                'smtp_server' => 'mail.friendcloud.hu',

                // smtp_port (Integer)
                // SMTP server port number
                'smtp_port' => 25,

                // smtp_secure (String)
                // What kind of encryption to use on the SMTP connection.
                // Options: '', 'ssl' or 'tls'.
                'smtp_secure' => 'ssl',

                // smtp_port_s (Integer)
                // Secure SMTP server port number
                'smtp_port_s' => 465,

                // smtp_username (String)
                // SMTP server authentication user name
                // Empty string disables authentication
                'smtp_username' => 'noreply@friendcloud.hu',

                // smtp_password (String)
                // SMTP server authentication password
                // Empty string disables authentication
                'smtp_password' => '*********************',

                // smtp_from (String)
                // From address used when using the SMTP server
                // Example: no-reply@example.com
                'smtp_from' => 'noreply@friendcloud.hu',
        ],
];
```
![phpmailer-error](https://user-images.githubusercontent.com/109982820/180839146-c92ff43a-2693-440f-afd4-9ff0eb3366ae.jpg)

I am running it with: ubuntu (docekred), apache2, php8.1. I have SSL SMTP on port 465, auth required.

Thank you for you assistance in advance!
Bobyonekenobi86

**Comment by MrPetovan** [comment]
Oof, that's a hard issue to debug because it's related to the native PHP `mail()` function that PHPMailer calls while suppressing any error message, then throw this non-specific exception when it fails.

Can you please test using the `mail()` function on its own on your server using the parameters in the `email` data array?

**Comment by bobyonekenobi86** [comment]
Hi! Thank you for your fast answer! Sorry for giving you struggle... :( 

Could you please hint me how should I achieve that? Where the $email get's populated, so I can make a print the members? I should use the index.php of friendica? 
Also, I found out, when I try to send for eg.: password reminder e-mail, I have a hit in the apache log:
`sh: 1: /usr/sbin/sendmail: not found`

**Comment by MrPetovan** [comment]
Ah, that's a good hint! You need a Mail Transfer Agent on your server to be able to send emails, even if you are using an authenticated SMTP relay. Please install either Sendmail, Postfix or any other MTA on your server before retrying.

**Comment by bobyonekenobi86** [comment]
After installing postfix and some basic configuration, it started working like charm!

Thank you for you kind help! 
Have a pleasant day! :)
