### ISSUE TITLE
Notify all instance users when a domain is blocklisted

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11779]
For complete transparency it would be fantastic to automatically notify all users of your instance when I, the admin, am adding a new domain to the blocklist. Also when I remove any. This way all users are aware of what I block/unblock. Maybe the notification should contain the reason why it was blocked and redirect to /friendica.

**Comment by MrPetovan** [comment]
There are at least four ways to update the domain blocklist, a few of them work in bulk, so we can't show the details of the update. The email will be a generic "The domain block list has been updated, please review it at /friendica".

**Comment by tio-trom** [comment]
Ah yes, that is also good! Can it redirect to /friendica on click?

**Comment by MrPetovan** [comment]
Of course, yes.

**Comment by tio-trom** [comment]
@MrPetovan  you are amazing!

**Comment by MrPetovan** [comment]
I'm sorry you'll have to wait until September to try it out!

**Comment by tio-trom** [comment]
Naah...is no problem at all. This is a wonderfully useful feature! Keep on being so kind and great my friend, I really appreciate that, Makes me like Friendica even more. Thanks again for implementing this!

**Comment by MrPetovan** [comment]
Ha, I was able to test this feature live today, worked like a charm. 😌

**Comment by tio-trom** [comment]
> Ha, I was able to test this feature live today, worked like a charm. relieved

That's fantastic. As far as I am aware, Friendica is the only federated platform that has this feature.

**Comment by MrPetovan** [comment]
It's because you're patient enough to ask over a long period of time!
