### ISSUE TITLE
Facebook Connctor

### ISSUE THREAD

**Issue by rettenbs** [friendica/friendica#1178]
I am trying to enable the Facebook Connector for a private Friendica Page.

When I connect my account to facebook I get the following warning:
> Submit for Login Review
> Some of the permissions below have not been approved for use by Facebook.

My friends are not even able to connect their account. (I think because there are not a tester/admin/.. of the app).

Which permissions does the app need? Is it even possible to get the required permissions approved for a small private Friendica installation?

**Comment by Beanow** [comment]
Please refer to the facebook documentation for developers. If you still have issues you can ask at https://helpers.pyxis.uberspace.de/profile/helpers
