### ISSUE TITLE
[Security] Users should be informed about password limits

### ISSUE THREAD

**Issue by futureisfoss** [friendica/friendica#11794]
So I try to use very long passwords for my accounts, but one thing I noticed on Friendica is that if I remove some characters from the end of my password then I am still able to login successfully!
I know that some services may have have limits on how long a password can be, to reduce server load and everything. But when there is a limit like that, then users should be made aware of that and Friendica shouldn't be accepting that password.

Info about my instance:
> This is Friendica, version 2022.06 that is running at the web location https://social.trom.tf. The database version is 1469/1469, the post update version is 1452/1452.

**Comment by MrPetovan** [comment]
I’m not aware of password length limits, what length are we talking about exactly?

**Comment by futureisfoss** [comment]
Actually I has hoping to ask you what the password length limit is, haha 😄

So the password I used was 80 characters long, I know that sounds like a lot, but its not that crazy for people who use password managers. I wonder what the password length limit of Friendica is, because its not good if its too small. Anyway, I think users should be made aware of such limits, and Friendica shouldn't be accepting passwords if it goes over that set limit.

**Comment by MrPetovan** [comment]
You're right about the information, but again I don't think we have any code actively limiting the password length since they are hashed anyway.

**Comment by MrPetovan** [comment]
Ah-ha! From https://www.php.net/manual/en/function.password-hash.php
> **Caution** Using the PASSWORD_BCRYPT as the algorithm, will result in the password parameter being truncated to a maximum length of 72 bytes.

So there is a limit of 72 bytes, I just didn't know about it, thanks for bringing this up!

**Comment by futureisfoss** [comment]
Oh, so this wasn't directly related to Friendica, but an external password hashing function you guys use. Makes sense why you got confused, lol 😄

Thanks for looking it up BTW, I think its good to make this clear to the user that there is a limit like that :)

**Comment by futureisfoss** [comment]
There might be some users who currently use passwords longer than 72 characters, right? So shouldn't we inform them about this so that they can change their passwords? 🤔

**Comment by MrPetovan** [comment]
Yes, we definitely should, this makes the changes slightly less easy to implement but it's a good idea.

**Comment by MrPetovan** [comment]
Instead of sending an email, I created a separate page that users will be redirected to if the password they used to log in (the only other time we can actually know this aside from the password change form). This page is just a password change form that explains the issue with the 72 characters limit.

The 72 characters limit depends on the value of the `PASSWORD_DEFAULT` native PHP constant that may be change in the future, removing the check for 72 characters and disabling access to this new page.
