### ISSUE TITLE
Posts don't seem to get distributed

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11803]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Something seems to be broken...  ..since about 4-5 hours my posts don't seem to get distributed, it still shows the hourglass symbol with "Die Benachrichtigungsaufgabe ist ausstehend"
I just want to inform you, since I can't post in the libranet.de - support forum

### Steps to Reproduce

Post something and wait / look..

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1475/1475 und die Post-Update-Version 1452/1452."

**Comment by MrPetovan** [comment]
The worker/inbox has undergone severe changes these last few days that have had significant infinite loops that are being worked on one by one. How long ago have you pulled `develop`?

**Comment by AlfredSK** [comment]
6 hours ago.

**Comment by haheute** [comment]
update: I have posted something this evening and after ~ 1 hour it started to get distributed, but now it seems to be stuck at "22/52" (since ~ 20 minutes). I can see it on my mastodon account but not yet on my diaspora account. :-/ 

edit: ah, now. "51/52"

**Comment by haheute** [comment]
It seems to work again. I hope it's ok to close this..
