### ISSUE TITLE
rss feeds disappeared 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [friendica/friendica#11807]
One release on 2022-09 removed all RSS feed contacts from a viewable portion of the user. There was an earlier bug that listed multiple issues, it was closed when one was fixed but I saw no fix for RSS contacts. I am able to add new RSS feeds but can not get my old ones back. 

I suspect instance admin would need to restore an earlier database and I'm not sure if that would be a good idea considering what it could do to users contacts it has made since then. 

Just want to make sure other servers won't have this failure when they update while I decide whether I want to find all the feeds I subscribed to again.

**Comment by MrPetovan** [comment]
Thank you for your report, on my own account on a server on `develop` I still have access to my 29 RSS feed contacts and I've received an RSS feed item as recently as 2 days ago so I'm not sure what this is about unfortunately.

**Comment by DetroitLibertyPenguin** [comment]
Support thread for reference https://libranet.de/display/0b6b25a8-4662-d700-921e-c26830892006

**Comment by DetroitLibertyPenguin** [comment]
no longer able to duplicate issue
