### ISSUE TITLE
Question for the translate-abiity for the polls

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11824]
Hi @annando could the explain the logic of the poll result from https://github.com/friendica/friendica/blob/develop/src/Model/Item.php#L3273

Question is which strings are singular and which are plural. Ideally the strings should contains both forms so that the translators can fit the wording accordingly.

Mentioning @gunchleoc as he brought up the problem on transifex.

**Comment by MrPetovan** [comment]
Yes, in this case the `L10n->tt()` method should have been used.

**Comment by MrPetovan** [comment]
This code is weird, the condition is meant to avoid a division by zero on line 3269 but the calculus is outside of the condition.

I agree the `l10n->tt()` method should be used on line 3274.

**Comment by gunchleoc** [comment]
Where should I report String issues in the future, on Transifex or here? What is more convenient for you?

BTW just in case you don't know already, the plural function needs to be used for all strings that contain a plural, even if there is no singular expected. There are languages that have different plural forms depending on the number.

**Comment by MrPetovan** [comment]
Typos in source strings: Please don't report them, changing a source string requires translators for all the languages to re-submit their existing translation. Also, although the source strings are in English (almost), we do have a British English and an American English translations that both include typo corrections.
Singular/Plural oddities: Here is perfect.

**Comment by annando** [comment]
The code takes in respect that some systems reports the number of voters (not to mix with the numbers of votes) and some don't. Also some polls have got an endtime - and some don't.
