### ISSUE TITLE
Pluralization bugs

### ISSUE THREAD

**Issue by gunchleoc** [friendica/friendica#11826]
I'm using this issue to collect i18n bugs for string pluralization. c.f. discussion in https://github.com/friendica/friendica/issues/11824

[src/Module/Admin/Federation.php:173](https://github.com/friendica/friendica/blob/develop/src/Module/Admin/Federation.php#L173)
`%s total systems`
And the 6 following strings in the po file.  I have to translate as "Total systems: %s" etc. which makes the list harder to read.

[src/Module/Admin/Federation.php:205](https://github.com/friendica/friendica/blob/develop/src/Module/Admin/Federation.php#L205)
`Currently this node is aware of  nodes ( active users last month,  active users last six months,  registered users in total) from the following platforms:`
Plural forms with "%s nodes" as the controller would be nice here. Transifex doesn't allow copying the placeholders even in raw mode - it should be possible to identify this string without them

[src/Module/BaseApi.php:274](https://github.com/friendica/friendica/blob/develop/src/Module/BaseApi.php#L274)
`Monthly posting limit of %d post reached. The post was rejected.`

**Comment by MrPetovan** [comment]
The first three reported bugs have been addressed in #11830, I stay available for any subsequent pluralization bug.

**Comment by gunchleoc** [comment]
Thanks!

I'll close this and open an new issue if I come across any more of these.
