### ISSUE TITLE
Improve user experience when inserting media in posts.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11825]
At the moment the process looks like this with each dot representing a "click".
1: You click on "New Post" (a window opens and you are in the "Message" tab and you compose your text).
2: From the "Message" tab you click on the "Browser" tab.
3: You click on "Upload". (the selection window opens)
4: You select the desired file by "double-clicking" on it. (the file will be uploaded and will appear in the list of files on the server)
5: Click the desired file again. (the file will be inserted, one line further, under the previously entered text)
6: Click on "Share

You could save 2 clicks.
1: You click on "New Post" (a window opens and you are in the "Message" tab and you compose your text)
2: You click on a newly added tab "Upload", the upload window opens directly.
3: You select the desired file by a "double click". (the file will be uploaded and will be inserted one line further, under the previously entered text).
4: Click on "Share".

This will shorten the whole process of creating a post and make it a little more elegant.

**Comment by loma-one** [comment]
This is how it is realised in https://url.domin/compose/0. It can serve as a model.

**Comment by MrPetovan** [comment]
Not exactly, you still have to select the file manually after it was uploaded.

**Comment by tio-trom** [comment]
What if there is an image button that simply lets you upload one directly and after the upload is done it is inserted directly into the post? So you can either browse for your already uploaded files or upload one directly without using the browse tab. Seems like a much better option for me. How many times when you make a post you want to select an image that's already in your image gallery? For me this is never the case for example. I simply want to add a new image.

**Comment by MrPetovan** [comment]
I do use the gallery browsing feature but I also agree, images added from the post box should just be uploaded in the default gallery (called “Wall Photos”) and inserted in the post body in one fell swoop.

Or better yet, do we need these images to be in the gallery at all to display them?

**Comment by tio-trom** [comment]
> Or better yet, do we need these images to be in the gallery at all to display them?

I was thinking the same...probably you dont need that. Just upload to the post and done. However what if you want to find these images later on? Perhaps they should also be available in the gallery somewhere under "wall photos" or something like that.

**Comment by MrPetovan** [comment]
Ok, so the current workflow where it has to be added to a gallery and the default one is “Wall Photos”

**Comment by foss-** [comment]
> Or better yet, do we need these images to be in the gallery at all to display them?

2 cents incoming: no we don't. Certainly there will be a minority happy with the current workflow. But I believe the majority wants to upload an image to be used in a single post, have that image automatically show in that post after upload and be done.

The current workflow is working against that interest. Users have to go through uploaded images and delete them one by one.

Facebook and Twitter have the option to show all images by a certain user iirc. Such a mechanism could replace the gallery. But uploading to gallery and forcing users to select from there, to then use an image in a post, is the wrong way around. It makes no sense I think.

**Comment by MrPetovan** [comment]
What about uploading to gallery but not forcing to select from there?

**Comment by tio-trom** [comment]
> What about uploading to gallery but not forcing to select from there?

For me if I can select an image and have it directly in the post, then that's great. It does the job quickly. If you also add it to the gallery I am not that opinionated about that :D .

**Comment by ghost** [comment]
> What if there is an image button that simply lets you upload one directly and after the upload is done it is inserted directly into the post?

Exactly like this


> Or better yet, do we need these images to be in the gallery at all to display them?

I think we still need this if you want to delete the images at some point.
I also think you should have a "delete all" option.


> What about uploading to gallery but not forcing to select from there?

How about uploading to the gallery and pasting in the post an not forcing to select from there?

**Comment by MrPetovan** [comment]
Yes, this is the goal.

**Comment by tallship** [comment]
@MrPetovan 

Awesome! A feature sorely lacking and one that has caused some consternation with many new users I've successfully managed to onboard to Friendica.

Thank you! Can't wait!

**Comment by ZwoVierZwo** [comment]
why don't you use a dropup field for images like other application it do.
i use a webmailer named https://roundcube.net/ who solved this in a proper way.
but for this goal there should also the compose window be modified.

**Comment by MrPetovan** [comment]
I've been caught up in other tasks and won't be able to reach the target milestone I set for myself.

**Comment by foss-** [comment]
Isn't this solved in https://github.com/friendica/friendica/pull/12883 and can be closed?
