### ISSUE TITLE
Wrong link on homepage for translation instructions

### ISSUE THREAD

**Issue by gunchleoc** [friendica/friendica#11834]
- [x] I have searched open and closed issues for duplicates

### Bug Description

https://friendi.ca/resources/contribute/ contains dead link to https://github.com/friendica/friendica/blob/develop/README.translate.md

### Steps to Reproduce

1. Visit https://friendi.ca/resources/contribute/
2.  In the 2nd paragraph "If you want to help with the translation in other languages, please have look at [Transifex](http://www.transifex.com/projects/p/friendica/). You need a account there and provide an easy interface to translate. If you do not want to deal with development tools like git that is fine, we will take care, that your work will be included into the project. More information about the translation process can be found [here](https://github.com/friendica/friendica/blob/master/README.translate.md).", click on "here".

Actual Result:

https://github.com/friendica/friendica/blob/develop/README.translate.md

Expected Result:

https://github.com/friendica/friendica/blob/develop/doc/translations.md

**Comment by tobiasd** [comment]
Thanks for noticing this :) I've changed the URL to the actual expected one https://git.friendi.ca/friendica/friendica/src/branch/develop/doc/translations.md
