### ISSUE TITLE
[fedilab/mastodon] Support adding users to lists

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11832]
Mastodon API and applications support the idea of adding accounts to lists. Currently, Friendica contact groups already appear to be exposed as Mastodon "lists" and I can try to add an account to a "list" from there, but this action doesn't seem to change anything on the server. Mastodon API call for that seems a POST /api/v1/lists/:id/accounts with a list of account_ids in the body. Is it possible to support that in Friendica?

**Comment by annando** [comment]
It is already possible to add contacts to groups. But while testing I had an issue by trying to fetch some group members. This is fixed now.
