### ISSUE TITLE
[Mastodon/API] Links to hashtags or profiles

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11846]
See https://github.com/tuskyapp/Tusky/issues/2657 : In some Mastodon clients, hashtag and profile links emitted via Friendica Mastodon API do not trigger in-app interactions but rather lead to the app opening a web link in the browser. This _seems_ to be caused by the way Friendica is building these links. This could be fixed in the frontend apps but maybe fixing it in the API implementation would be generally better. Is that possible...?

EDIT: Unsure why this has been labeled "Bug", but seems I'm unable to change that.

**Comment by MrPetovan** [comment]
I chimed in the linked Tusky issue.

> EDIT: Unsure why this has been labeled "Bug", but seems I'm unable to change that.

It's because our issue templates. You can circumvent them by clicking the link at the bottom of the list:
![github_friendica_issue_template](https://user-images.githubusercontent.com/925415/184864382-e226bac8-13aa-425e-bd70-402c808335ea.png)

**Comment by kr428** [comment]
@MrPetovan Cool, thanks for that. :)
