### ISSUE TITLE
"The requested item doesn't exist or has been deleted"

### ISSUE THREAD

**Issue by toba321** [friendica/friendica#11850]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I edited my docker compose file slightly to add the SMTP settings. I also selected the following privacy options: 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/75487499/185504742-34428666-455b-488d-bb4f-a36bdfb8c335.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/75487499/185504799-1b4cd3da-0786-4c53-82dc-93ef15e2beac.png">

I could previously share a post with users who aren't logged in by copying the https://domain/display/item-id URL but this has stopped working and returns the error message "The requested item doesn't exist or has been deleted". As soon as I log in, the link loads correctly. 

I have also tried deselecting the options I changed. 

I have block public unchecked:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/75487499/185504964-67ee2605-cff1-4a84-b79d-5c7f28fb0800.png">

### Steps to Reproduce

1.  Open post and copy URL while logged in
2.  log out
3.  paste the URL in browser and see error message

Actual Result:

See error message

Expected Result:

I should be able to view the post without having to log into the account as public access is enabled.

### Screenshots
<img width="569" alt="image" src="https://user-images.githubusercontent.com/75487499/185505226-aaaabbd1-e41f-4d82-8ab1-1a5038a576eb.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/75487499/185505308-0e3830d1-2cc3-40d4-a1a3-b0e0ceaafb75.png">

### Platform Info

Friendica Version: 2022.06 

Friendica Source: 

PHP version: 7.4.30

SQL version:

**Comment by toba321** [comment]
Nevermind I've worked out why it wasn't working. It's because it was a RSS feed and not a community post and so wasn't public. Out of interest is there a way to make an RSS feed visible to the public when we add it as a contact?

**Comment by MrPetovan** [comment]
Yes, you need to mirror the posts by setting the RSS feed contact as "remote self" and enabling post mirroring. This will posts the feed items in your name.
