### ISSUE TITLE
Can't reshare Diaspora posts

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11867]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I reshare a Diaspora post (in this case from someone i don't follow), the UI works and counts my reshare, but the post does not appear in my stream/profile and not on the /network page.

### Steps to Reproduce

1. reshare a diaspora post (from someone you do not follow / not sure if that is important)
2.  check the /profile and /network pages

Actual Result:

post is not there

Expected Result:

post should appear there

### Screenshots

![friendica-reshare-diaspora](https://user-images.githubusercontent.com/5753419/187022741-83585968-38d8-468f-9c6a-6e28e40d493c.png)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1481/1481 und die Post-Update-Version 1452/1452.

Theme: Frio V.0.8.5

**Comment by MrPetovan** [comment]
Thank you for your report!
