### ISSUE TITLE
empty page when removing category from post

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11861]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I click the small (x) on a category of a post, to remove the category from that post, I end up on an (almost) empty page. It looks as if a redirect back to the post is missing. Or maybe it is supposed to work with javascript. I'm not sure. (the clicked link was: `https://libranet.de/filerm/214024006?cat=quote` )

1.  edit post
2.  add category or multiple categories
3.  save and go back to the 'status' page
5.  remove category by clicking the small (x) 

Actual Result:

An empty page after clicking, only with menu at the top. I have to use the browser back button.
I used firefox. Here a screenshot:

![friendica-remove-category](https://user-images.githubusercontent.com/5753419/186618097-114bfc1b-c370-46fc-877a-b1c462270bb8.jpg)

Expected Result:

to be redirected back to the post, (or the page where I was). or stay on the page and see just a disappearing category 

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1481/1481 und die Post-Update-Version 1452/1452."

Theme: Frio V.0.8.5

**Comment by MrPetovan** [comment]
Thank you for the report, it's likely that this URL needs to be called asynchronously but for some reason is open in the browser instead, revealing the absence of expected displayed content.
