### ISSUE TITLE
Weeks May Begin on Saturday

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11870]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Under `Settings -> Display -> Calendar`, there shall be a "Saturday" option in addition to Sunday and Monday, because in some geographical locations, weeks begin on Saturday, like Iran.

### Steps to Reproduce

1.  Go to `<your_instance_domain>/settings/display`
2.  Expand the Calendar thing.

Actual Result:

There are only two options for the week start: Sunday, and Monday

Expected Result:

Three options should be there for the user to select: Saturday, Sunday, and Monday.

### Screenshots

Unfortunately, I can take no screenshots while hovering on the expanded list in my browser. The drawer would disappear.

### Platform Info

Friendica Version: 2022.06

More information at social.trom.tf/friendica.

**Comment by annando** [comment]
Thanks for the hint! I didn't know that.
