### ISSUE TITLE
Can't see posts of local forums and some local contacts

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#11876]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Im following several Forums and accounts on my local server. It started that I (with my personal user) can't see the posts of my forum accounts I am following. Now it starts, that i can't see the posts of my other local accounts that I am following. -> It is getting worse.

### Steps to Reproduce

1.  Loggin in with my ONE Account
2.  Switching to my FORUM Account - writing a message
3.  Switching back to my ONE Account
4. Can't see it in my timeline and the Forum is empty

### 2. Steps to reproduce 

1.  Loggin in with my ONE Account
2. Switching to my SECOND Account
3. writing a post with my SECOND Account
4. Switching back to ONE Account
5. Can't see it in my timeline
6. Searching for SECOND Account -> getting older posts
7. Clicking on "Network Posts" (hover Card) -> Seeing that post

### Platform Info

Friendica Version: dev ( pull 30.08.22.15:30)
Friendica Source:  git
PHP version: 7.4
SQL version: mariadb 10.3.34

**Comment by AlfredSK** [comment]
Same here. I mostly never get any posts to my local support forum. I have to get the url from another instance and put it in the search field to get the post and reply to it.

This behavior started some weeks ago.

I didn't notice that normal local contacts are affected too.

**Comment by hoergen** [comment]
Local accounts seems to be new, since some days. Not really sure when it started, but last week I still got from that account posts in my timeline.

**Comment by hoergen** [comment]
It seems that a part of the problem is at my ONE acount. Because I can see posts from other people from other instances in my local forums.

**Comment by annando** [comment]
I'm convinced that the problem only occurs when everything stays local on the same machine. I have to perform some tests for that in the next days. I hope that there are no other bugs that distract me.

**Comment by hoergen** [comment]
bump bump bump

**Comment by annando** [comment]
In the last days I fought with performance updates, errors and warnings in the logs and the nasty problem of weirdly looking threads. When this all is quiet again, I can have a look at that problem.

**Comment by hoergen** [comment]
One more

1. Login in personal account
2. switching to forum account
3. searching for a post from personal account
4. clicking on "share" .. nothing happens

I can't reshare with my forum accounts posts from my personal account.

**Comment by hoergen** [comment]
I think this is a bigger problem than just the described above because I checked some external accounts were I didn't see posts the last days (weeks).

They wrote continuously posts, that are received on my server, but they are not shown in my timeline.

When searching for them or looking them up via their profile page (status) everything is displayed.

**Comment by tobiasd** [comment]
I have learned in personal conversation, that postings from some forums (helpers) have not been received on a different server (which I have no access to). Even though it is not a local forum problem, it may be the same underlying problem.

At which log level should problems about distributing forum postings be logged?

**Comment by annando** [comment]
I just discovered a bug that occurs when you are posting to a forum by using the `@` instead of the `!`. In that case (`@`) the forum hadn't distributed the message to the forum followers. I'm unsure if this is related to this issue or is another one.

**Comment by hoergen** [comment]
Didn't fixed it for me.

**Comment by annando** [comment]
@hoergen I'm slightly optimistic that the last PR fixed this bug.

**Comment by hoergen** [comment]
That fixed it partially. Some forums and accounts I see again. Some not.

E.g. a local forum (Filmzet) is not able to natively reshare a post from my main (admin) account. 
The admin account is the same that is able to switch to the local forum account (Filmzeit)
When I try to reshare, it does the "share animation" and jumps back to the original icon. I checked from both accounts, but no sharing was done.

**Comment by hoergen** [comment]
Found something that could have to do with it. I am not sure

If I don't follow an account, I cant native share posts of that account.

The fact that I should be able to native share public posts from people I don't follow, forums normally don't follow their members, so maybe there is something that is connected to that bug ?

**Comment by hoergen** [comment]
There is a problem with followings and not followings.  My current workaround is to use a hashtag that I follow with the forum account, to be able to share posts from users.

**Comment by hoergen** [comment]
I close this issue, because I think the visibility works. 
But the other problem with "can't reshare" is still there.

 Can't reshare posts of accounts I don't follow #12307
