### ISSUE TITLE
Unable to 'like' posts of people I don't follow (at least Mastodon and Diaspora)

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11875]
- [X] I have searched open and closed issues for duplicates

### Bug Description

At least with diaspora and mastodon posts, of users I do not follow, my like is not shown in the UI. 
I don't know if the rest works, but the counter does not seem to count me and my username does not appear and the 'like' text does not become blue and bold.

### Steps to Reproduce

1.  find a post you like of someone you don't follow
2.  click "like"
3.  look what happens 

Actual Result:

it looks as if it doesn't work

Expected Result:

the reaction on the page. (colored and bold text of the 'like' etc..)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1481/1481 und die Post-Update-Version 1452/1452.

Theme: Frio V.0.8.5

**Comment by annando** [comment]
Have you got the latest changes from Sunday evening?

**Comment by AlfredSK** [comment]
> Have you got the latest changes from Sunday evening?

I think so 🙂

**Comment by haheute** [comment]
Affects friendica posts, too.  
The "Like" text becomes bold, the spinning image appears. Then the image disappears and the font weight goes back to normal.  
Not possible to like the post.

**Comment by AlfredSK** [comment]
For me it works on the network page but not on the community pages and not on the display page of a single post.
That's what I noticed yesterday evening.

**Comment by MrPetovan** [comment]
Hmm, if it's consistent per page then it is likely it isn't related to the post type, I'll look into it.

**Comment by annando** [comment]
It is likely that the system behaves differently in the several pages where users can interact (network, display, contact posts, community). Although the identical action is called, the optical feedback may vary.

**Comment by AlfredSK** [comment]
I just had a déjà-vu. I couldn't like a post. Then I found this issue.

I guess the problem with 'likes' has only something to do with the status of the connection between me (the local user) and the author of the post I want to like.

I discovered a nice post of a stranger on the community pages. I tried to like it. No success.
I opened the single post view of that post. Tried to like it. No success.
Then I followed the author. Now I can like the post successfully - no matter what page I am on.

The liked post (Friendica): https://libranet.de/display/0b6b25a8-303c07c7-9cd456274f5ef55e

Forum post: https://forum.friendi.ca/display/0b6b25a8-6863-41ea-6e4c-b61794347032

**Comment by MrPetovan** [comment]
Could https://github.com/friendica/friendica/issues/12176 be a related issue?

**Comment by AlfredSK** [comment]
I need to check if I still can reproduce the issue.

**Comment by kr428** [comment]
Coming from #12176, adding myself here. I _pretty much_ can reproduce what's being described here in, like, 80% of the cases, but I'm unsure whether there are any factors affecting that. Actually, I also experienced situations where I visited some un-followed users profile and was able to interact with _some_ of the posts made there (own posts of that user only, no reshares/boosts).

**Comment by AlfredSK** [comment]
> I need to check if I still can reproduce the issue.

Tried two random posts on the community pages. One worked one didn't.

Liked successfully on community page:
https://libranet.de/display/357280ca-57bfe979c6a1925f-c0e3d30d

Can't like on community page or on display page:
https://libranet.de/display/844fec55-ca7ac791c7c892fc-8f437e95

**Comment by kr428** [comment]
Another example for a non-follower post I can't interact with, even through Friendica Web UI:
https://loma.ml/display/f87d4b91-b22f26f68600514f-a079b75c

**Comment by kr428** [comment]
(This seems to somehow get worse, no matter why or how. While just a few days ago it happened occassionally and only on mobile, by not it seems that virtually every post I hit in a public timeline or on a profile I'm not following is showing this kind of behaviour. Side effects of Mastodon 4.x?  For the two examples in https://github.com/friendica/friendica/issues/11875#issuecomment-1322353955 , it seems the "working" one is pointing to / coming from a 3.x instance, the "broken" one from a 4.x one. In my cases, the "broken" ones seem 4.x all the time...)

**Comment by foss-** [comment]
Pasted https://loma.ml/display/f87d4b91-b22f26f68600514f-a079b75c into  search field and was able to like + unlike post in question (am not following author) on Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1491/1491, the post update version is 1484/1484.

Not sure which findings to derive but would assume this is not mastodon related but friendica related.

@kr428 and @AlfredSK which version of friendica are you running?

**Comment by AlfredSK** [comment]
I'm on current develop. But I had the same issue with the last stable version.

**Comment by foss-** [comment]
Had you tried with linked example post? Are you unable to like that post as  well? Wondering how our setups differ. Using Firefox 107.0 here.

**Comment by kr428** [comment]
I'm on loma.ml which is 2022-10 AFAICT.

**Comment by foss-** [comment]
works fine on
This is Friendica, version 2022.09-rc that is running at the web location https://squeet.me. The database version is 1484/1484, the post update version is 1484/1484.

This seems to be a problem with your instance or a local issue on your end.

**Comment by kr428** [comment]
Just tried that again on loma.ml (2022-12rc), same effect for this post : https://norden.social/@Chaoscoco/109471730614683922
Tested on web ui and tusky.

**Comment by foss-** [comment]
To repro with webUI I open my friendica instance, past `https://norden.social/@Chaoscoco/109471730614683922` into search field and press enter. I then see the post in question and am able to like and unlike the post. That is not working for you?

If not, can you get logs from your instance admin?

**Comment by kr428** [comment]
Yes, that's what I tried, and it isn't working. I'll try to get the logs here.

**Comment by kr428** [comment]
This seems the only thing related to when I tried to interact with that sample post:

`2022-12-07T13:58:01Z index [INFO]: Contact is not a follower, thread will not be stored {"author":"[https://norden.social/users/Chaoscoco","uid":1154,"uri-id":35466583,"post-reason":76}](https://norden.social/users/Chaoscoco) - {"file":"Item.php","line":1632,"function":"storeForUserByUriId","uid":"c00155","process_id":13316}

2022-12-07T13:58:01Z index [INFO]: Contact is not a follower, thread will not be stored {"author":"[https://norden.social/users/Chaoscoco","uid":1154,"uri-id":35466583,"post-reason":76}](https://norden.social/users/Chaoscoco) - {"file":"Item.php","line":1632,"function":"storeForUserByUriId","uid":"c00155","process_id":13316}`

Does that help...?

**Comment by haheute** [comment]
I have updated to 2022.12-rc today (now on my own instance) and tried again. If I search for this post in friendica:

https://diaspora.psyco.fr/posts/eced8a802da4013b18fb7054d219cb33

I find it, but can't 'like' it. (I do not follow the user or any of those hashtags.) 
And, I could not yet find a clue in the firefox dev tools or in my instance's admin-area logs.

**Comment by kr428** [comment]
Seems to work here now too. Thanks for fixing that. 🙂️
