### ISSUE TITLE
Unable to unfollow an account

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11889]
Steps:
- Click on "Unfollow" button
- Receive a "contact has been unfollowed" message
- Contact page still says they're sharing with me
- Clicking again on "Unfollow" makes a "Unfollowing is currently not supported by your network." message show.

**Comment by MrPetovan** [comment]
After updating to the latest RC, the contact was correctly removed as expected, not sure if it's the update or the worker run that did it.

**Comment by tio-trom** [comment]
Oh wow saw the same issue....damn...glad the RC works!
