### ISSUE TITLE
Missing image description

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11880]
- [x] I have searched open and closed issues for duplicates

### Bug Description
If a picture is uploaded to Friendica, provided with a picture description and included in a post, the picture description is not displayed

### Steps to Reproduce

1. picture upload /photos/~/upload
2. navigation to the picture gallery /photos/~
3. selection image - edit image /photos/~/image/~/edit
4. create and send post

Actual Result:
The image description will not be copied

Expected Result:
The image description will be displayed in the published post

### Platform Info
The problem Occurs with all currently available current versions (stable/Dev)
Tested on libranet (dev) & opensocial.at, loma.ml (stable)

**Comment by MrPetovan** [comment]
Thank you for the report, however this isn't a bug, it was never intended this way. It is an enhancement to the base feature.

**Comment by loma-one** [comment]
Oh, thank you for the correction. Since it works fine via the Api, I had assumed it was a bug with the WebUI

**Comment by MrPetovan** [comment]
I'm not familiar with how it works with the API, could you provide me with an example?

**Comment by loma-one** [comment]
https://loma.ml/display/373ebf56-2063-1206-cf79-9ba780827510
APP Tusky v19.0

Procedure:
Open APP
Create new post
Add image from image gallery
Add picture description
Send

Switch to Friendica Browser Version
Open Friendica picture gallery
Call sent picture
Check image description

![Screenshot 2022-09-02 at 15-37-56 Pinnwand-Bilder](https://user-images.githubusercontent.com/44441246/188158405-c4517e6b-1bcb-4e47-8722-780845a8c38f.png)

![Bildbeschreibung](https://user-images.githubusercontent.com/44441246/188170764-32efe081-ff78-43d2-acce-ad220f2abed1.png)

**Comment by annando** [comment]
This is surely a useful improvement.

**Comment by utzer** [comment]
Also some UI way to add a description would be great, currently I struggle every time how to add it.
