### ISSUE TITLE
Incorrect allocation of comments and posts

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#11890]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I think there are big problems with assigning comments to launch posts right now. Comments on different posts are combined into one thread.

Some examples:

- [https://soc.schuerz.at/display/4edd2508-7563-1661-fcca-262595014955](https://soc.schuerz.at/display/4edd2508-7563-1661-fcca-262595014955)
- [https://soc.schuerz.at/display/4edd2508-2063-15ff-85ac-acd887530359](https://soc.schuerz.at/display/4edd2508-2063-15ff-85ac-acd887530359)
- [https://friendica.xyz/display/4edd2508-1263-15e2-3f8d-59d476483200](https://friendica.xyz/display/4edd2508-1263-15e2-3f8d-59d476483200)

### Steps to Reproduce

Comment on one of the posts and see what happens.

Actual Result:

A mixed thread is created, the initial post and comments do not fit together.

Expected Result:

The comments are assigned to the correct posts

### Platform Info

The wrong thread
![falsche-Threadzuordnung](https://user-images.githubusercontent.com/12498438/188514975-8a3c0b2e-7081-4ff9-b554-04fa97bde2de.png)

The right thread
![richtiger-thread](https://user-images.githubusercontent.com/12498438/188515025-43c59b87-f448-459e-b704-fdf17bcce0e6.png)

Friendica Version:
Friendica 'Giant Rhubarb' 2022.09-rc - 1482

Friendica Source: git

PHP version: 8.0.23

**Comment by annando** [comment]
Please execute this query:
```
select `parent-uri`, count(*) as parents from `post-view` where gravity = 0 group by `parent-uri` having parents > 1;
```

**Comment by atasingorneq** [comment]
The result of the query
```
select `parent-uri`, count(*) as parents from `post-view` where gravity = 0 group by `parent-uri` having parents > 1;
Empty set (12.713 sec)`
```

**Comment by xundeenergie** [comment]
This is my result. Threadings are also broken on my side

```
MariaDB [friendica]> select `parent-uri`, count(*) as parents from `post-view` where gravity = 0 group by `parent-uri` having parents > 1;
+-----------------------------------------------------------------------+---------+
| parent-uri                                                            | parents |
+-----------------------------------------------------------------------+---------+
| https://digitalcourage.social/users/mupan/statuses/108793717950243445 |       2 |
| https://embassy.social/users/Thalestria/statuses/108783150929196474   |       2 |
| https://fem.social/users/mehdorn/statuses/107693834556002392          |       2 |
| https://norden.social/users/Spreepunk/statuses/108927995631015683     |       2 |
| https://squeet.me/objects/962c3e10-1563-1453-4e13-722767753025        |       3 |
| https://troet.cafe/users/dieAnnie/statuses/108849093696422351         |       2 |
| https://troet.cafe/users/morsuapri/statuses/108913293043179533        |       2 |
+-----------------------------------------------------------------------+---------+
7 rows in set (9.002 sec)
```

**Comment by xundeenergie** [comment]
It happened after the last checkout in devel branch
