### ISSUE TITLE
Notification counts don't reset in 2022.09-RC

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11909]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

A user reports that since the switch from the 2022.06 version to 2022.09-RC the notification counts for new postings on the network stream and in user groups are raising continuisly and not being reset. The counts raise after several times of reading the stream via API and in the web browser.

### Steps to Reproduce

1.  update from 2022.06 to 2022.09-RC
2.  wait for new postings of your contacts, the counter is raised
3.  see the postings in the network stream, the counter is not reset to 0

Actual Result:

The numbers are climbing.

Expected Result:

After the postings are read, the counter should be reset to 0 and not be displayed until new postings arrive.

### Screenshots

![FriendicaRaisingCounter](https://user-images.githubusercontent.com/433490/191180282-034ac041-cdbd-4309-a5f7-894ae53877b3.png)

**Comment by annando** [comment]
The functionality to set items to "seen" hasn't changed for some time, see here:
https://github.com/friendica/friendica/blob/2022.09-rc/src/Module/Conversation/Network.php#L480-L486

The system should always set all user items to "seen" whenever the user doesn't have a look at one specific group, is looking for starred content, mentions or dedicated forum posts. Also the "seen" value is set whenever an unseen item is opened. You could possibly have got a look at your database to see what kind of posts these unread posts are. 

You can use this query to have a look at all unseen posts:
```
select id,`uri-id`,guid,received,gravity,network from `post-user-view` where unseen and uid=1 order by received;
```
Please replace the `uid` value with you own user id.

**Comment by tobiasd** [comment]
Looks like one of the last commits had solved the issue somehow... the user in question reports that the postings could be marked as seen now. Don't ask for details :-/ ;-) Closing the issue.
