### ISSUE TITLE
Blank page for the Network

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11901]
A user is reporting a pure blank page for the Network. But everything else works. He tried different browsers and so forth. He even removed the people he followed to get an "empty" network stream, but in vain. I looked at the logs with debug enabled. I cannot see anything relevant. Our instance works for me and so many others so I am baffled...what can we do to debug?

Comment from the user: "Vivaldi reports HTTP error 500, which is a pretty generic way of saying something's wrong on the server"

**Comment by MrPetovan** [comment]
500 errors should be reported in your webserver/PHP logs, likely an Exception or a Fatal Error that are likely to be logged.

**Comment by tio-trom** [comment]
In a weird twist visiting "/network?order=received" fixed it all....no idea why.....but well....I will close this for now.
