### ISSUE TITLE
[frio] Modal file browser upload button doesn't show if uploaded file list is too long

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11911]
After my file list is full the upload button disappeared to the bottom and uploading new videos is not possible.
Scrolling down is also not possible, as you can see.
![2022-09-20 16 54 50](https://user-images.githubusercontent.com/12480023/191292573-43e416c3-0f12-4652-976c-4a9c9b863ff3.png)

**Comment by ghost** [comment]
By the way, in the profile there is no possibility to delete videos that have been uploaded as files.

**Comment by MrPetovan** [comment]
Oof, thank you for the report.

**Comment by tek-aevl** [comment]
This part does not load at all for me, after changing to, file-system storage, switching back to database does not fix issue..
