### ISSUE TITLE
"Method start does not exist" on fresh install

### ISSUE THREAD

**Issue by sadaszewski** [friendica/friendica#11912]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Fresh install of 2022.06 using PHP 7.4, MariaDB 10.6, Apache 2.4. I get "Method start does not exist" exception and a blank page.

### Steps to Reproduce

1.  Install
2.  Go to / or /index.php
3.  Observe the error "Method start does not exist"

Stack trace:
```
Method start does not exist
#0 /friendica/vendor/level-2/dice/Dice.php(150): ReflectionClass->getMethod() 
#1 /friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}() 
#2 /friendica/vendor/level-2/dice/Dice.php(248): Dice\Dice->create() 
#3 /friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}() 
#4 /friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}() 
#5 /friendica/vendor/level-2/dice/Dice.php(248): Dice\Dice->create() 
#6 /friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}() 
#7 /friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}() 
#8 /friendica/src/DI.php(62): Dice\Dice->create() 
#9 /friendica/index.php(50): Friendica\DI::app() 
#10 {main}
```

### Platform Info

Friendica Version: 2022.06

Friendica Source: https://files.friendi.ca/friendica-full-2022.06.tar.gz

PHP version: 7.4

SQL version: MariaDB 10.6

**Comment by sadaszewski** [comment]
Same on 2022.03

**Comment by sadaszewski** [comment]
It moved a little further by installing php74-session. Any other modules I should add? The ones listed in https://wiki.friendi.ca/docs/install#requirements are not enough... Still getting a blank page on $a->runFrontend(...) this time.

**Comment by sadaszewski** [comment]
php74-filter seems also necessary.

**Comment by sadaszewski** [comment]
With php74-filter it finally worked !

**Comment by MrPetovan** [comment]
The session and filter extensions are built by default with PHP. To build PHP without these extensions, you have to add specific flags to the configure call. I'm not familiar with the Linux distribution/package manager you are using but I'm not sure we should mention the required extensions that you have to go out of your way not to include with PHP.

**Comment by sadaszewski** [comment]
`composer.phar install --no-dev --dry-run` detects the problem when cloned from GH and mentions it, therefore the documentation could mention it as well for the sake of completeness. I am using FreeBSD which has a very modular PHP setup where a staggering majority of extensions have to be pulled in explicitly. I ended up with the following exhaustive list:

```
curl gd pdo_mysql mbstring xml iconv zip openssl
pecl-mcrypt posix dom json fileinfo
pecl-imagick session filter ctype simplexml zlib
```

I throw in `pecl-APCu` for speed.

**Comment by MrPetovan** [comment]
Thank you for the list, the `composer.json` file includes dependencies for extensions that aren't bundled by default with PHP which explains the output of `composer.phar`. As a result it only lists 12 extension dependencies when you listed 19 extensions. With the complete list we can now update the requirement page but I would have been hard-pressed to come up with this list in the first place given my setup with a default PHP install.

**Comment by MrPetovan** [comment]
Update: Someone beat me to updating the wiki page, so now the requirements are more accurate thanks to you!
