### ISSUE TITLE
embedded youtube video won't play on friendica with ssl

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1191]
After posting a Video with the youtube tag the video won't play if you run friendica with ssl.

to reproduce:
1.) run friendica with https
2.) insert [youtube]https://www.youtube.com/watch?v=FM77KNURtd0[/youtube] to your post
3) After pressing play the JavaScript console prints: 
[blocked] The page at 'https://friendica.example.com/profile/rabuzarus' was loaded over HTTPS, but ran insecure content from 'http://www.youtube.com/embed/tP_OP_IDQQ4?feature=oembed': this content should also be loaded over HTTPS

Also the produced html prints the the non-ssl youtube link after pressing play.

**Comment by annando** [comment]
The fix is now implemented in the master branch, so I close this issue.
