### ISSUE TITLE
[mastodon-api] Boosts aren't visible on profile page?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11915]
- [x ] I have searched open and closed issues for duplicates

Connecting any Mastodon client app (tusky, fedilab, ...) to Friendica, the usually expected behaviour is to see your own boosts while looking at your own "profile" page. In case of Friendica, however, seems to only show my own posts and responses to other posts. Is that a known limitation of the current Mastodon API implementation? Or does Friendica generally behave in a different way, here?

**Comment by MrPetovan** [comment]
For a while the desktop version of Friendica wouldn't show the native reshares in the profile page because we used to create a new post for reshares, Diaspora-style. This has been updated to show posts from other authors that the user reshared, but maybe it hasn't been updated for the API output.

**Comment by kr428** [comment]
Ah. Ok. That's an interesting aspect because re-sharing Diaspora posts has a different weird effect. In this case, both the "original" post with a note that "I reshared it" and my re-share will appear in my profile. For all other posts I reshare (ActivityPub, actually), they do correctly show up in the Web UI but not in the app. Not sure this relates, though.

![twice](https://user-images.githubusercontent.com/685879/191820867-5522ec6e-5dce-46a6-996d-dfcd81dd801f.png)

**Comment by MrPetovan** [comment]
Possibly fixed by https://github.com/friendica/friendica/pull/12300, would someone on a `develop` node be able to test?

**Comment by foss-** [comment]
Sadly seems to be persisting. Reshared a post from local timeline, then switched to profile page in Fedilab. The share is not showing there.
Fedilab 3.8.1
This is Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1496/1496, the post update version is 1484/1484.

**Comment by annando** [comment]
@foss- I haven't updated my machine today. The next update will be after all of my pull requests are merged.

**Comment by foss-** [comment]
Just gave this another try and still not seeing the shared post in porilfe page in Fedilab. If this is expected feel free to ping for another test round.

**Comment by foss-** [comment]
Verified on Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1500/1500, the post update version is 1484/1484. and Fedilab 3.9.3.
