### ISSUE TITLE
Top-level post only RSS feed?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11920]
Currently, I'm then and now using and publishing my timeline as news feed to people who want to see that, which boils down to an URL like this:

https://loma.ml/dfrn_poll/z428

Subscribing to this, my feed reader always will collect both posts and responses I made to other posts. It would be good to be able to exclude responses from this feed.

**Comment by tobiasd** [comment]
You can add /posts to that URL to get only the postings into your feed, but no
comments.

**Comment by kr428** [comment]
Hmmm, if I try https://loma.ml/dfrn_poll/z428/posts , I see 404 Not found...?

**Comment by tobiasd** [comment]
right ... :-/

It's the correct URL, as it is noted in the routes definition, but then later
somewhere an exception is triggered. Here is the trace

```
Exception thrown in /src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound-&gt;content()
#1 /src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule-&gt;run()
#2 /src/App.php(719): Friendica\Module\HTTPException\PageNotFound-&gt;run()
#3 /index.php(44): Friendica\App-&gt;runFrontend()
#4 {main}
```

**Comment by MrPetovan** [comment]
I can look into this.

**Comment by loma-one** [comment]
@kr428 Please see if this fits for you
https://loma.ml/feed/z428/posts

**Comment by MrPetovan** [comment]
I looked into this and there's no `/dfrn_poll/{username}/posts` route. There is a `/feed/{username}/posts` as @loma-one correctly pointed out but it displays the same content as `/feed/{username}/`.

@kr428 Let me know if it's what you were looking for so that we can close this issue.

**Comment by kr428** [comment]
Thanks all. That's interesting, because the dfrn_poll URL is what I copied from the "Atom link" snippet on my Friendica profile page. /posts seems pretty much what I want, so seems fixed while using that.

**Comment by MrPetovan** [comment]
We expose both the `/dfrn_poll` link and the various `/feed` links in the profile page, not sure what software only showed you the `dfrn_poll` but I expect they took the first in the list which happens too be the `dfrn_poll` one.

**Comment by annando** [comment]
The `dfrn_poll` endpoint was needed for the legacy DFRN protocol and is still needed for OStatus. Once we deprecated OStatus, we can get rid of that endpoint as well and will only keep the `feed` endpoint which is solely meant for serving content for feed readers.

**Comment by MrPetovan** [comment]
Can we change the order of the exposed feed URLs in the profile page so that the `/feed` one is the first without breaking OStatus compatibility?

**Comment by annando** [comment]
I must confess: I'm unsure. And this is nothing that we can check easily.
