### ISSUE TITLE
Link to external comment at Lemmy is wrong

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#11937]
- [x] I have searched open and closed issues for duplicates

### Bug Description
The external Link from a comment in Friendica to the origin URL at the remote Fediverse service, in this case Lemmy, seems to be incorrect. 

### Steps to Reproduce

1. Fetch a Lemmy thread, ie. this one here:
Link Friendica https://social.yl.ms/display/e18176ef-6063-316c-7a90-705545510802
Link Lemmy https://feddit.de/post/389189
2. Pick a comment comming from Lemmy, ie. [this one](https://social.yl.ms/display/964fe573-c12cda56d14e59e5-a060cb7c). 
3. Click on the link to external, the little square with arrow to top right. 
![Screenshot_2022-09-26_12-07-03](https://user-images.githubusercontent.com/8361662/192250396-f21f5e8a-3e06-4e95-bdcd-c702c2d0221b.png)

Actual Result:
404 Error on Lemmy. 

Expected Result:
Show the thread and highlight the comment on Lemmy. 

### Platform Info

Friendica Version: This is Friendica, version 2022.06 that is running at the web location https://social.yl.ms. The database version is 1469/1469, the post update version is 1452/1452.

Friendica Source: Git

PHP version: 8.x

SQL version: NA

**Comment by MrPetovan** [comment]
Friendica-exposed comment link: https://feddit.de/comment/75250
Actual comment link: https://feddit.de/post/389189/comment/75250

**Comment by annando** [comment]
Problem is that Lemmy isn't propagating that secondary link.

**Comment by utzer** [comment]
> Problem is that Lemmy isn't propagating that secondary link.

but how can we pull the comment/thread with that URL and also Mastodon can find the comment with it, but not reach it on their webpage? Is it a Lemmy bug then?

**Comment by annando** [comment]
Normally you have got an endpoint that is meant for users and another one that is meant for technical purposes like fetching the content. System request content with a specific expected content type. Then the system delivers a JSON array in return. But obviously people cannot read JSON easily, so the browser will expect some HTML. Most systems then deliver human readable content - but Lemmy simply returns a 404.

**Comment by MrPetovan** [comment]
@utzer I encourage you to submit this issue with the Lemmy project: https://github.com/LemmyNet/lemmy/issues/new/choose

**Comment by utzer** [comment]
[Here](https://github.com/LemmyNet/lemmy/issues/2459) is the issue.

**Comment by dessalines** [comment]
I commented there. TLDR; we only recently added that `/comment/id` endpoint in the UI, and it'll be in the next release. 

Currently tho, the federation half of it should be working fine: 

`curl -H 'Accept: application/activity+json' https://feddit.de/comment/75250 | jq`

**Comment by annando** [comment]
@dessalines additionally Lemmy could add the `url` parameter to the comments that would point to the "human readable" link: `https://feddit.de/post/387422/comment/75456`.

**Comment by Nutomic** [comment]
@annando Thats not necessary, there will be a human readable link provided at `https://feddit.de/comment/75456` in the next version.

**Comment by utzer** [comment]
> there will be a human readable link provided 

Just a link and not the content straight away? Maybe then better provide the link with each post or comment. 😉

**Comment by annando** [comment]
@Nutomic the `url` is just some additional possibility. This field is used by many other projects. But yeah, when the technical url will redirect to to the human readable content, then this should work with most other systems as well.

**Comment by Nutomic** [comment]
Well not a link, you will directly see the comment under that url. Anyway, i think this issue can be closed.

**Comment by utzer** [comment]
> Well not a link, you will directly see the comment under that url. 

That sounds good. Thanks for clarifying. 

> Anyway, i think this issue can be closed.

Yes, in this case it can be closed. Can you give an estimation when this will be released?

**Comment by dessalines** [comment]
Not sure when our next release will be yet, but yes /comment/id will be a readable link.
