### ISSUE TITLE
Twitter Addon broken?

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11930]
After I set up the Twitter addon, I wanted to disconnect the previously set up Twitter connection.
When I tried to disconnect, I got the following error message that won't go away.

`An error occurred:{"errors":[{"code":32, "message": "Could not authenticate you."}]}`

![2022-09-25 08 41 36](https://user-images.githubusercontent.com/12480023/192131639-9238a9f8-9c48-4cab-80ad-0f0914096284.png)

**Comment by ghost** [comment]
I have to open this issue again because it seems that the Twitter addon is not working anymore.
I was able to authenticate on Twitter but the addon shows me that the Twitter information is invalid.
The timeline is also no longer imported.
![2022-09-25 09 10 16](https://user-images.githubusercontent.com/12480023/192132593-efc31130-acfd-407d-8e3b-a1d4e767f3a4.png)

**Comment by ghost** [comment]
I am closing the issue here because I have found the solution, you have to apply for an elevated status on the twitter app, then the app will also work.

**Comment by MrPetovan** [comment]
Ah, yes, we've been having this conversation a few times by now, we should have an auto-reply for issues about the Twitter addon!
