### ISSUE TITLE
frio on mobile: left sidebar on status page missing when not login

### ISSUE THREAD

**Issue by asherpen** [friendica/friendica#11943]
- [X] I have searched open and closed issues for duplicates

### Bug Description

On my mobile phone's browser, when I open my profile page (/profile/nickname) in mobile browser's InPrivate window, I found the left sidebar missing, while in normal window (with account login), the three dot on the top left is clickable, so the left sidebar can be shown when clicking.

I also tried on PC browser, when in InPrivate window the left sidebar can be seen. However, if I drag my browser window to <1000px width, the left sidebar disappears, and no way to have it shown, except drag browser window to >1000px width. 
### Steps to Reproduce

1.  mobile browser
2.  open profile page in InPrivate windows
3.  check the left sidebar

Actual Result:
left sidebar is missing

Expected Result:
left sidebar should be seen, so that users on other site can see the personal information/ tag cloud / Categories

### Screenshots
![IMG_20220928_234455](https://user-images.githubusercontent.com/8214569/192825560-560ff4ed-c4a3-4d1e-9bb6-a697a72a50da.jpg)

### Platform Info

Friendica Version:2022.06

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by MrPetovan** [comment]
Additional note: the discrepancy comes from the fact that the top bar is completely different whether a user is logged or not, so there's no provision at all for the skewer menu.
