### ISSUE TITLE
My server has the wrong time...

### ISSUE THREAD

**Issue by produnis** [friendica/friendica#11949]
Hi there, my friendica-node  https://friendica.produnis.de  seems to have an issue with his time (I am in timezone Europe,Berlin).
People wont see nor get any of my posts - while I still get posts into my timeline..
The error at other nodes is:
`Signature created in the future `

I checked my server-settings and everything seems to be fine,

https://systat.zilium.de/munin/time-day.html
https://systat.zilium.de/munin/zilium.de/hetzner5.zilium.de/index.html#time

If I check friendicas built-in phpinfo(), it states

```
Default timezone | UTC
date.timezone | Europe/Berlin
```

What else could I do to fix that?

**Comment by annando** [comment]
Please enter `date` in the command line. Please ensure that is is looking somewhat similar:
```
$ date
Mo 3. Okt 12:00:30 UTC 2022
```
Means: The timezone has to be `UTC` and the time should be your local time converted to UTC.

Please also have a look in your PHP config files for both CLI and Module/CGI, see here: https://stackoverflow.com/questions/32224547/setting-the-timezone-for-php-in-the-php-ini-file

**Comment by produnis** [comment]
It took me quite a while, but I hope, that my time-problem is fixed now....
could you please check if I still send wrong time?

**Comment by annando** [comment]
What had been the origin of the problem?

**Comment by produnis** [comment]
me being unskilled (but aware of it) :)

`date` was "Berlin", and now it is `UTC`

The problem was, that `/etc/localtime` and  `/etc/timezone` were symlinked from system.

Thx for your help, hope it works now 
(Michael, I sent a PM via friendica, did it go through?)

**Comment by annando** [comment]
It did.

**Comment by produnis** [comment]
hurray..... so, closing this one...
