### ISSUE TITLE
User should be able to choose between modal and composer editor and use it as default

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11941]
### Is the feature request related to a problem? Please describe.

Creating content in Friendica is complicated and not very attractive for new users. 
Since there is an alternative to the existing default, which is more oriented to the needs of users, it should be possible to use this as a default.

See also https://soc.schuerz.at/display/4edd2508-1363-3324-d436-740927886408

### Describe the feature you'd like

The Friendica theme Frio has a modal and composer editor.

The user should be able to select which editor should be used regularly. If a selection has been made, the editor will always be set as default for creating new content.

For this purpose, a switch should be integrated at https://domain.ltd/settings/display "Custom Theme Settings" that allows this selection.

Users can change the selection of their default editor at any time via the switch.

### Describe alternatives you've considered

Calling the modal editor via middle mouse button is not an alternative to permanent use via a switch solution

### Additional context

**Comment by MrPetovan** [comment]
Thank you for your suggestion, I guess we should also point to this setting in the compose page itself.
