### ISSUE TITLE
[twitter-crossposter] Also crosspost own responses to own (top-level) posts?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11951]
In quite some cases when using the Mastodon -> Twitter cross poster, I used threads to keep certain topics "alive" and linked over time and enjoyed the fact that in this case responses to my own posts would be sent to Twitter as responses to my own posts "there" too, exactly mirroring the thread on the other side which is pretty neat.
For Friendica (tested on loma.ml / 2022-06), it seems responses to my own posts aren't crossposted, neither do I have the option to choose or enforce that. It would be great to have that available here too.

**Comment by annando** [comment]
These crossposters and Friendica behave completely different in this point. When you post from Friendica to Twitter then you create two separate threads. So when someone answers on Twitter then you will find that answer in the Twitter thread - and when someone answers in the fediverse you will find the answer in the other thread. These two threads are completely separated. So when you want to add something to the Twitter thread then you have to add an answer there, but but not in the Fediverse thread.

**Comment by kr428** [comment]
Hmmmm, though I understand your explanation of _how_ it works, I wonder whether there's a rationale for that and whether it might be implemented in a different way then. In most situations, even looking at this just from "the Fediverse", this seems somewhat confusing, and separating (on Twitter) post that ought to belong together (on the Fediverse) also creates a behaviour that feels at least "unintentional", as on Twitter there's absolutely no way to tell these posts belonged together at some point, most likely in a chronological order too.

**Comment by MrPetovan** [comment]
I can provide some more technical context. When we create Friendica connector posts from Twitter posts during timeline import, we assign the local post an identifier that includes the Twitter post identifier so we know it's a reference to a Twitter thread and as a result we're able to keep adding replies to that thread from Twitter based on these identifiers.

However, when we crosspost from Friendica to Twitter, neither Friendica nor Twitter post have a reference to each other, so we aren't able to add more posts on one side when we receive replies from the other side.

**Comment by kr428** [comment]
@MrPetovan Ok, thanks for the explanation, but... the feature currently introduced for #11953 apparently does just that - adding subposts to new top-level posts. So it _is_ generally possible, I assume? Would it be possible to somehow keep these references between Tweets and Friendica posts? It somehow _should_ generally be possible, otherwise the Mastodon crossposters would not be able to work, would they...?

**Comment by MrPetovan** [comment]
Let's examine the two posting directions:
### Friendica to Twitter
1. A Friendica native post is created with a Friendica reference.
2. The post is sent to the connector addon that splits it and post it to Twitter. Each created post returns a Twitter reference which is used to string multi-parts posts together.

### Twitter to Friendica
1. The connector retrieves Twitter posts.
2. For each of these posts, a Friendica connector post is created with a Twitter reference. This enables us to:
    - Find the parent post in the connector thread of any subsequent replies fetched from Twitter.
    - Mirror Friendica replies in the connector thread to the correct Twitter post.

As you see, in the first case there's no opportunity to link the Friendica post to the Twitter thread since the Friendica reference is created first and cannot be stored in the Twitter post.

**Comment by kr428** [comment]
@MrPetovan I see, thanks for outlining... So in F -> T the connector addon isn't able to get hold of the Twitter URL / UID / whatever they use to identify a tweet? Or does it "just" have no way to return this information and somehow link it to the original post sent through the connector? "Naive" expectation would be something like "create post in Friendica" -> "send post to connector" -> "get target system URL(s) in return value from connector" -> "store target system URL with the original post", no matter whether handled via return value or some callback function provided to the connector to update the original post (at least in the instance database) with the Twitter/Tumblr/whatever url... but I assume it doesn't work like that?

**Comment by MrPetovan** [comment]
It doesn't work like that because the Twitter connector is called at the end of the process, when the post has already been created.

Beyond that, there is a philosophy issue: do we want reallyto brand native Friendica posts with a Twitter reference, replacing the Friendica reference? It can be a prickly issue when we're trying to get away from centralized platforms.

So in theory it could easily be changed so that when you activate the Twitter addon all your posts receive a Twitter reference but it isn't a trivial idea to promote.

**Comment by kr428** [comment]
Ohh, I'm not suggesting to replace the Friendica reference - rather than adding another one all along with that? 

Maybe, also, that kind of state (mapping Friendica URL <-> Twitter/Tumblr/... URL) could be managed by the connector itself? I mean, shouldn't it boil down to more than a table or map to figure that out? Looking at moa.party in example (will also try to see if that works with Friendica as it uses ActivityPub it seems): In this case, apparently a crossposter manages to do mapping between two systems while being completely autonomous and a third-party component not integrated with any of the both ends in a way. The Twitter connector, on the other side, lives way closer to Friendica so the assumption was that, maybe, it might be even easier to link these two systems together here. 🙂️

**Comment by MrPetovan** [comment]
Yes, it's possible, but it would require significant changes to the way the connector works. Currently the post reference is a field in the post table, and adding the possibility to track more than one reference for a given post requires the creation of an additional table. It isn't that hard, but it is a significant time investment.

This said I'll keep that in mind, thanks for opening my mind that was constrained by the existing arbitrary data structure.

**Comment by kr428** [comment]
Ok, cool, thanks too for explaining. 
(Maybe, for this specific use case, still recommending a "generic ActivityPub" crossposter like moa.party or crossposter.masto.donte.com.br is a viable workaround too...)
