### ISSUE TITLE
Synchronize communications view between Diaspora and ActivityPub

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11952]
Currently, when looking at my posts from an ActivityPub or a Diaspora account, I see the following:

- ActivityPub users only see communications with other ActivityPub users and no Diaspora comments at all.
- Diaspora users see all posts, all comments made by other Diaspora users and responses written by me to any other comment in there (but not, in example, other comments made via ActivityPub). This is a bit weird.

In both cases, behaviour is a bit odd but the approach for Diaspora seems even more confusing as this will result, in quite some cases, in a bunch of messages mentioning user profiles not accessible from Diaspora and responding to messages that aren't there. Workaround would be to, in Diaspora, also only see Diaspora posts (i.e. comments by other Diaspora users and responses I made to them), best of course would be to see all communications regardless of network used. 🙂️

**Comment by annando** [comment]
We cannot relay ActivityPub comments to Diaspora and vice versa. This is technically not possible, due to the incompatible protocols.

Also: When you directly answer an AP user (by commenting on their comment) then the comment should not be relayed to Diaspora at all. However, if you place a top level comment and you only mention someone, then this post will be distributed in both networks.

**Comment by MrPetovan** [comment]
Also: It isn't practical to know what network to direct your reply to an AP or Diaspora reply. Especially since Diaspora doesn't support replies to replies yet.

**Comment by annando** [comment]
In fact Diaspora supports replies to replies. But the only software that supports it is Friendica, not Diaspora.

But since you can directly reply a reply in Friendica we can safely direct these replies to their own networks.

**Comment by MrPetovan** [comment]
Huh, that would be an improvement regarding this issue.

**Comment by annando** [comment]
This only describes the current behaviour.

**Comment by MrPetovan** [comment]
I thought both Diaspora and AP received Friendica replies, regardless of the network of the author we’re replying to?

**Comment by annando** [comment]
If this currently happens then it is unintended and I would consider it as a bug. It already *should* work in the described way.

**Comment by MrPetovan** [comment]
See issue text (emphasis mine):

> Diaspora users see all posts, all comments made by other Diaspora users and **responses written by me to any other comment in there** (but not, in example, other comments made via ActivityPub). This is a bit weird.

**Comment by kr428** [comment]
I have to add, after looking closer: It doesn't seem to happen for responses to comments of Mastodon but of Friendica users that appear in Diaspora. Not sure whether this relates to ActivityPub or something else.

**Comment by annando** [comment]
Can you link an example?

**Comment by kr428** [comment]
Yes, sure. This is the top level post:

https://loma.ml/display/373ebf56-7163-3683-2a24-ef0521636271

This one is visible on Diaspora....

https://loma.ml/display/373ebf56-1863-36e3-182f-4d5235464698

... as a response to this, I guess, which isn't:

https://loma.ml/display/373ebf56-4163-368f-bf73-f5f324552849

**Comment by annando** [comment]
Thanks for providing the link. So the situation is as following:
- A starts a thread on Friendica. The post is distributed to AP and Diaspora
- B from Mastodon is commenting. The post is only visible via AP 
- C from Friendica answers B. This is also only visible on AP
- A answers C => Post is distributed to both AP and Diaspora

**Comment by kr428** [comment]
Ok, thanks for looking into this (and apparently resolving it too). 🙂️
