### ISSUE TITLE
Twitter shares look wrong

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11969]
_Originally posted by @Singh-in in https://github.com/friendica/friendica/issues/11967#issuecomment-1271944327_

> Post that is shared
> ![Screenshot 2022-10-07 at 20-32-01 Dis le moi! Network](https://user-images.githubusercontent.com/62051161/194626329-101a9c09-8048-4b35-836b-a16c29029b9f.png)
> 
> Preview
> ![Screenshot 2022-10-07 at 20-32-16 Dis le moi! Network](https://user-images.githubusercontent.com/62051161/194626367-b0f8ac8f-f701-4a87-93c8-6fe94d3d8852.png)
> 
> Result
> ![Screenshot 2022-10-07 at 20-33-05 Dis le moi! Network](https://user-images.githubusercontent.com/62051161/194626381-7e227efa-b50e-4ea8-959f-436d9f4514a6.png)
> 
> https://dis-le.de/display/50619573-1663-4070-c376-835026304896

**Comment by ghost** [comment]
The error is back again
![2022-10-08 17 47 40](https://user-images.githubusercontent.com/12480023/194716048-4243a55f-654b-4c9e-b481-c6145c68f1df.png)

**Comment by annando** [comment]
Go to the preview. Everything is fine.
