### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#11963]
test https://friendicarg.nsupdate.info/display/69172192-7663-3dd2-a065-b9a734971681

Public: https://friendicarg.nsupdate.info/attach/30
Private: https://friendicarg.nsupdate.info/attach/31

How do I make the attachments visible to everyone?

**Comment by MrPetovan** [comment]
Can you please share how you created these attachments?

**Comment by loma-one** [comment]
Here is a brief description of how to upload and distribute additional files (besides images).

- Create a new post
![Screenshot 2022-10-09 at 04-42-45 ˈloma Network](https://user-images.githubusercontent.com/44441246/194735400-18d36ca0-8924-4b1b-be1a-ddfdf12e0d99.png)

- Navigate to the browser (#jot-fbrowser-wrapper)
![Screenshot 2022-10-09 at 04-56-36 ˈloma Network](https://user-images.githubusercontent.com/44441246/194735546-28751259-9d6e-4356-b31c-b4a0a6f27894.png)

- Select "other attachments"
![Screenshot 2022-10-09 at 04-45-48 ˈloma Network](https://user-images.githubusercontent.com/44441246/194735506-7464bf6c-0bb6-478d-b973-1c0443bcbe44.png)

- Upload a file (*.MP3, MP4, php, PDF)

- Select a file 
![Screenshot 2022-10-09 at 04-48-07 ˈloma Network](https://user-images.githubusercontent.com/44441246/194735468-b4eae38f-76b1-4b87-aeb4-fcac74fa83bc.png)

- and send it
![Screenshot 2022-10-09 at 04-49-45 ˈloma Network](https://user-images.githubusercontent.com/44441246/194735435-1d158609-ebe2-4da4-b3c1-2e2b934ed469.png)
---
What stood out:
If only the attachment is created and distributed, the content is not visible to others. An accompanying text must always be created.

The name of the upload file is not equal to the name in the attachment that is distributed. Actually, the selected file and the distributed file should be named identically.
Upload file name - "Social-Media - 1360.mp4".
Attachment name - "3

**Comment by MrPetovan** [comment]
This is being improved with https://github.com/friendica/friendica/pull/12277

**Comment by nupplaphil** [comment]
Improved, but not ultimately solved tbh... There are some issues left with attachments when editing and overwriting and so on.. I think we need to dig into the `[attachment]` interpreter for it
