### ISSUE TITLE
DB Error: Table 'friendicadb.conversation' doesn't exist

### ISSUE THREAD

**Issue by itmc-rw** [friendica/friendica#11975]
```
worker [ERROR]: DB Error {"code":1146,"error":"Table 'friendicadb.conversation' doesn't exist","callstack":"DBA::p, PostUpdate::update1452, PostUpdate::update, PostUpdate::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT `post-view`.`uri-id`, `conversation`.`source`, `conversation`.`received` FROM `conversation` INNER JOIN `post-view` ON `post-view`.`uri` = `conversation`.`item-uri` WHERE NOT `source` IS NULL AND `conversation`.`protocol` = 0 AND `uri-id` > 0 LIMIT 1000"} - {"file":"Database.php","line":697,"function":"p","uid":"8afef1","process_id":2890548}

worker [ERROR]: Database error {"no":1146,"message":"Table 'friendicadb.conversation' doesn't exist","worker_id":"713e721","worker_cmd":"PostUpdate"} - {"file":"PostUpdate.php","line":1053,"function":"update1452","uid":"8afef1","process_id":2890548}
```
- [X] I have searched open and closed issues for duplicates (and I really tried my best).

### Bug Description

The above two error messages are written to the Friendica log every 5 minutes. According to the contents of database.sql, the "conversation" table no longer exists with that name. But some feature or addon apparently expects its existence, still.

### Steps to Reproduce

Don't know which feature/addon causes the error. I have enabled all additional features and these addons: advancedcontentfilter, blackout, blockem, cookienotice, curweather, impressum, js_upload, langfilter, nsfw, rendertime, smileybutton, superblock, twitter

Actual Result:

Error message in log file because of attempting to work w/ non-existing table 'conversation'.

Expected Result:

No attempt to work w/ a non-existing table.

### Screenshots

Non needed.

### Platform Info

Friendica Version:

2022.09-rc

Friendica Source:

git

PHP version:

7.4.3

SQL version:

MariaDB 10.3.34

**Comment by annando** [comment]
Have you recently updated your system or is this a brand new installation?

**Comment by itmc-rw** [comment]
It's a brand new installation. It was setup in mid September.

**Comment by annando** [comment]
Okay. Then I know what to do. See PR https://github.com/friendica/friendica/pull/11976

**Comment by annando** [comment]
BTW: Thanks for the report! It was just in time for the next release!

**Comment by itmc-rw** [comment]
Thank you for the quick fix! 😊
