### ISSUE TITLE
like-button above search field

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#11984]
- [x] I have searched open and closed issues for duplicates

### Bug Description

In frio theme on mobile browser is th like-button when liked, above the search-field.

See screenshot.

### Steps to Reproduce

1.  Like a posting
2.  Klick into search-glass, to open the searchfield
3.  Scroll around, that the likebutton (thumb up) of your liked posting passes the searchfield

Actual Result:

The z.coordinate of the liked likehbutton is higher than the searchfield.

Expected Result:

### Screenshots
![Screenshot_20221011_151322](https://user-images.githubusercontent.com/5894829/195100726-b2d235b8-c516-42ea-877b-b930a9001c51.jpg)

### Platform Info

Friendica Version:

Friendica Source: devel

PHP version: 8.1

SQL version: mariadb 10.3

**Comment by MrPetovan** [comment]
Nice catch!

**Comment by xundeenergie** [comment]
seems gone... can not reproduce it anymore.
