### ISSUE TITLE
[frio] Expand comment field with input

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11985]
### Is the feature request related to a problem? Please describe.

If a post is commented, the text content can be more than 3 lines long. In this case, it is advantageous if the text field is automatically expanded so as not to impede the flow of writing. 

Currently, only a scroll bar is displayed if the text is longer than 3 lines. The editor can be expanded manually.

**Comment by Lakshman76** [comment]
i would like to work on it.
plz assign me if it is available?

**Comment by tobiasd** [comment]
Thank you for having a look into the issue @Lakshman76 if you have any questions, don't hesitate to ask here, or in the developers forum in at [forum.friendi.ca/~developers](https://forum.friendi.ca/profile/developers).

**Comment by Lakshman76** [comment]
> Thank you for having a look into the issue @Lakshman76 if you have any questions, don't hesitate to ask here, or in the developers forum in at [forum.friendi.ca/~developers](https://forum.friendi.ca/profile/developersdefinetily 

definitely! Thank you

**Comment by loma-one** [comment]
The height of the input fields has been increased in the meantime. This issue is therefore no longer relevant.
