### ISSUE TITLE
[frio] Expand opening a Direct Message

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11986]
### Is the feature request related to a problem? Please describe.
Direct messages are presented as a list. To open a message, I have to click on one of the messages.

Visually, the sender and recipient are brought into focus. This text is highlighted in bold, signaling me that I need to click there to view the message.

In fact, the headline opens the message. 
![Screenshot 2022-10-11 at 17-02-29 ˈloma Message](https://user-images.githubusercontent.com/44441246/195128960-c8fd615d-6da4-4444-b8b6-d3849304fb79.png)

It would be great if the link to the message is expanded so that clicking on the image of the sender, sender-recipient or headline can open it.

**Comment by haheute** [comment]
@MrPetovan should one link enclose all elements including the avatar picture (like the red line on the image above) ? Or would it be better to only add a link into the heading?

**Comment by MrPetovan** [comment]
Just the heading please, there also is a "Delete conversation" link in the same block, so an enclosing link would either cover it or make it confusing to find the Delete link.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/12570
