### ISSUE TITLE
Avatars not shown

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#12009]
- [x] I have searched open and closed issues for duplicates

### Bug Description
Looks like this
![Screenshot_2022-10-17_20-25-43](https://user-images.githubusercontent.com/8361662/196254172-65a28a78-9916-4de1-84c4-c473197f9633.png)

The bigger profile picture on the left is missing, also the icon sized avatar is missing too. 

I get some entries like this in the Friendica log. 
`2022-10-17T18:24:37Z index [ERROR]: Uncaught Exception Error: "Call to a member function isSuccess() on null" at /srv/http/src/Core/Storage/Type/ExternalResource.php line 62 {"exception":"Error: Call to a member function isSuccess() on null in /srv/http/src/Core/Storage/Type/ExternalResource.php:62\nStack trace:\n#0 /srv/http/src/Model/Photo.php(207): Friendica\\Core\\Storage\\Type\\ExternalResource->get()\n#1 /srv/http/src/Module/Photo.php(155): Friendica\\Model\\Photo::getImageDataForPhoto()\n#2 /srv/http/src/BaseModule.php(238): Friendica\\Module\\Photo->rawContent()\n#3 /srv/http/src/App.php(719): Friendica\\BaseModule->run()\n#4 /srv/http/index.php(44): Friendica\\App->runFrontend()\n#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"3b0ed4","process_id":46753}`

Sometimes after some time the icon loads when reloading, then it looks like this:
![Screenshot_2022-10-17_20-30-10](https://user-images.githubusercontent.com/8361662/196254976-105a0b69-3bca-405a-9744-94bde4bf86a7.png)

I think this has to do with the avatar cache, when I activate the cache it seems the most avatars load fine. But I was told recently to disable the cache as it saves tremendous amounts of storage. 

### Steps to Reproduce

I see many posts in /network without avatar, sometime the avatars load when I open a post, but on the small icon sized one, the one on the left stays missing. 

Expected Result:
Avatars should show up at least after reloading a post. 

### Platform Info

Friendica Version: 2022.10

Friendica Source: git

PHP version: PHP 8.1.11

SQL version: 10.9.3-MariaDB

**Comment by annando** [comment]
Not sure how this could have happened. But PR https://github.com/friendica/friendica/pull/12385 will at least have got some "Contingency Plan" when an avatar can't be fetched.

**Comment by utzer** [comment]
This was solved, I think it was caused by some 8.1.x PHP compatibility issue.
