### ISSUE TITLE
WSOD since gitpull this morning latest dev

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12023]
Getting a WSOD since the gitpull of the last develop version.
This is all I could find in the logs
Friendica still works in Twidere.

`PHP Warning:  is_readable(): open_basedir restriction in effect. File(/proc/loadavg) is not within the allowed path(s): (/home/users/meld/www:/home/users/meld/files:/home/users/meld/tmp) in /src/Core/System.php on line 445`

**Comment by ghost** [comment]
I got this after the gitpull

```
Deprecation Notice: Class Friendica\Addon\Monolog\IntrospectionProcessor located in ./addon/monolog/src/IntrospectionProcessor.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:/// /bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Friendica\Addon\Monolog\DevelopHandler located in ./addon/monolog/src/DevelopHandler.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:/// /bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by tobiasd** [comment]
The first part was introduced by @annando the second by @nupplaphil but both are no ERROR messages. Any ERROR in the log? "Uncaught Exception" and then something where the error happens.

Might be https://github.com/friendica/friendica/issues/11992#issuecomment-1283453134, which I encountered and @nupplaphil is already working on a fix.
