### ISSUE TITLE
Huge increase of dns queries with 2022.10

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12031]
After installing 2022.10 (docker image) I get a huge increase in dns queries from my friendica server ...
![grafik](https://user-images.githubusercontent.com/39007279/196641152-3470c2ea-674d-441e-b57a-34fb9002bd06.png)
It seems as if it now queries all known servers every few minutes?

**Comment by nupplaphil** [comment]
@annando do you have an idea? I didn't change anything in docker itself, just use the new archive

**Comment by annando** [comment]
AFAIK we now perform a DNS lookup before trying to reach a remote system. Question of course is how the workers are looking. Means: Is the number increasing or is the number steady?

Also: From which version have you updated?

**Comment by ne20002** [comment]
This is a huge increase. I updated from last 2022.06 to 2022.10 by just updating docker image. 
The number is now steady by approx 3000 dns queries per 10 minutes. It was way lower before the update (as u see in the picture).
According to admin page my server is federating with 1429 other servers (as before). Looking for certain servers in pi-hole logging it shows four requests (2 A and 2 AAAA) per 5 minutes to most servers.

**Comment by annando** [comment]
What about the number of outgoing requests? Has this changed that much as well?

**Comment by ne20002** [comment]
Where do I check outgoing requests? It's a single user server and I write very little.

**Comment by ne20002** [comment]
I now eased the problem by activating systemd-resolved on the server. My pi-hole is now not flooded anymore, resolvectl statistics show still a huge number of requests (now served from local cache). So the restart of the server did not fix the problem ;)
