### ISSUE TITLE
Uncaught Exception ReflectionException: "Class Friendica\Module\Session\Capability\IHandleUserSessions does not exist

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#12052]
- [x] I have searched open and closed issues for duplicates

### Bug Description

```
2022-10-23T12:48:26Z index [ERROR]: Uncaught Exception ReflectionException: "Class Friendica\Module\Session\Capability\IHandleUserSessions does not exist" at vendor/level-2/dice/Dice.php line 107
{"exception":"ReflectionException: Class Friendica\\Module\\Session\\Capability\\IHandleUserSessions does not exist in vendor/level-2/dice/Dice.php:107
Stack trace:
#0 vendor/level-2/dice/Dice.php(107): ReflectionClass->__construct()
#1 vendor/level-2/dice/Dice.php(93): Dice\\Dice->getClosure()
#2 vendor/level-2/dice/Dice.php(247): Dice\\Dice->create()
#3 vendor/level-2/dice/Dice.php(132): Dice\\Dice->Dice\\{closure}()
#4 vendor/level-2/dice/Dice.php(96): Dice\\Dice->Dice\\{closure}()
#5 src/App/Router.php(343): Dice\\Dice->create()
#6 src/App.php(734): Friendica\\App\\Router->getModule()
#7 index.php(44): Friendica\\App->runFrontend()
#8 {main}"} - {"file":null,"line":null,"function":null,"uid":"803d57","process_id":14558}
```
### Steps to Reproduce

1.  Start writing a post/comment
2.  click on "Link or Media"
3.  Add an URL, e.g. `http://example.org`
4. Submit it and check your web server's error-log and/or `friendica.log`

Actual Result:

The code is not inserted into the comment/post form.

Expected Result:

The code should appear in the comment/post form.

### Screenshots

See description for the log message.

### Platform Info

Friendica Version: `develop` at latest changes
Friendica Source: `git`
PHP version: `7.4.30`
SQL version: `15.1`

**Comment by tobiasd** [comment]
part of #11992

**Comment by Quix0r** [comment]
Yes, it might be part of it but why isn't it then quickly fixed? That's why I named this PR a "Hotfix", it needs rapid fixing and is already helping and it is a simple, small change (which also makes no sense there).

**Comment by Quix0r** [comment]
I got previous comment wrong.
