### ISSUE TITLE
[twitter] Image attachments in shared tweets are shown twice

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12073]
See ![2022-10-29 14 36 11 friendica mrpetovan com e915340e3686](https://user-images.githubusercontent.com/925415/198847663-38207dc0-a3c4-41bf-834e-f3ee204b0a02.png)

What can I check? "Item Source" in the admin panel doesn't show anything.

**Comment by annando** [comment]
This is already fixed locally on my system. I'm currently working on the final steps for an overhaul for the quoted posts.

**Comment by MrPetovan** [comment]
Help. (there should be only one image: https://twitter.com/dorrismccomics/status/1588564751876968448)
![2022-11-04 12 49 22 friendica mrpetovan com a2e2e8d91d2f](https://user-images.githubusercontent.com/925415/200031358-012a4813-3f5c-4cf9-94cc-d4ae9a7866ff.png)
