### ISSUE TITLE
When trying edit addon's settings

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12080]
When trying edit addon's or addon settings.
Not sure where I went wrong. 
```
Service Unavailable
unable to create directory view/smarty3/compiled/e0/87/83

Exception thrown in src/Core/Renderer.php:90
Stack trace:
#0 addon/irc/irc.php(145): Friendica\Core\Renderer::replaceMacros()
#1 src/Module/Admin/Addons/Details.php(105): irc_addon_admin()
#2 src/BaseModule.php(244): Friendica\Module\Admin\Addons\Details->content()
#3 src/App.php(719): Friendica\BaseModule->run()
#4 index.php(44): Friendica\App->runFrontend()
#5 {main}
```

**Comment by annando** [comment]
Your system is missing the write permissions in the template folder. After you applied the correct permissions, it should work.

**Comment by tobiasd** [comment]
@annando could a worker maybe check the write ability on the needed directories, say once a day, and if not given notify the admin in the admin panel?

**Comment by tek-aevl** [comment]
> Your system is missing the write permissions in the template folder. After you applied the correct permissions, it should work.

So, what permissions are the correct ones? 
chmod 644 ?

**Comment by annando** [comment]
The permissions depend on your installation. When frontend and backend are executed by the same user, then write permissions for the user are enough. When the users are different, then both users at least should be in the same group, the folder should be assigned to that group and the group would need write permissions.

**Comment by tek-aevl** [comment]
thanks
