### ISSUE TITLE
Notification improperly displayed when a user puts a trailing UTF-8 'RTL override' character in their display name

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12084]
- [X] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Friend sets their display name with "\xE2\x80\xAE" at the end.
2.  Friend interacts with the test user on the friendica instance.

Actual Result:

The notification text displays with erroneous respect to the right-to-left override character with a language which is left-to-right. 
> [object Otter]‮ vous a répondu dans "TIFO friendica supplies a Mastodon-compatible API since 2021.06, me…" 

Expected Result:

The notification text displays properly, regardless of the trailing RTL Override character.
Example: 
> [object Otter] vous a répondu dans "TIFO friendica supplies a Mastodon-compatible API since 2021.06, me…" 

### Screenshots

![https://i92.servimg.com/u/f92/10/09/37/50/captur12.png](https://i92.servimg.com/u/f92/10/09/37/50/captur12.png)

### Platform Info

Friendica Version: 2022.10-1484

Friendica Source: 
  * [https://files.friendi.ca/friendica-full-2022.10.tar.gz](https://files.friendi.ca/friendica-full-2022.10.tar.gz)
  * [https://files.friendi.ca/friendica-addons-2022.10.tar.gz](https://files.friendi.ca/friendica-addons-2022.10.tar.gz)

PHP version: 7.4.30

SQL version: MariaDB 10.5.15-0+deb11u1

**Comment by ghost** [comment]
Adding the following block to `view/global.css` fixed the issue:

```css
.contactname {
  unicode-bidi: isolate-override;
}
```

You'll find below a screenshot of a trial of that fix in the dev console: the first notification is the fixed version, the third shows the problematic case.

![image](https://user-images.githubusercontent.com/5450075/199038102-2b58f487-da8b-44b9-b3bf-3409dd2ab892.png)

**Comment by MrPetovan** [comment]
Thank you for the report and the offered fix!

**Comment by ghost** [comment]
> Thank you for the report and the offered fix!

My pleasure. I'd be inclined to make a pull request, if I was sure it didn't break other use cases, especially with RTL languages.

**Comment by MrPetovan** [comment]
Good point, I should get @ahangarha 's opinion, they have been invaluable help to enable bidirectional content on Friendica.

**Comment by ghost** [comment]
The template used to generate `/notifications/system?show=all` also needs to be fixed by wrapping the display name with a `span` with the `contactname` class.

![image](https://user-images.githubusercontent.com/5450075/199121980-bb32f3e1-d4ba-46f0-924b-e1b873a8f57c.png)

**Comment by ghost** [comment]
The same fix as above needs to be applied in the e-mail template:

![image](https://user-images.githubusercontent.com/5450075/199678021-9e8d8e56-1b73-4c36-b452-bddf91feb72d.png)

**Comment by ahangarha** [comment]
Thanks for reporting this. And thanks for mentioning me.

This needs to be tested with other scripts. We should be very careful in applying `unicode-bidi`. Unfortunately I am very busy till the end of November, specially till mid November.

**Comment by MrPetovan** [comment]
We can take this the other way: is there a good reason for a RTL user to use the RTL Override character in their display name? Otherwise we can filter it out from display names which wouldn't need any CSS fiddling.

**Comment by MrPetovan** [comment]
I got an external confirmation this character isn't relevant to RTL users, so we'll just strip it from display names, too bad for practical jokers.

See: https://social.trom.tf/display/dbc8dc44-1763-6cbb-965e-b6d819216161
