### ISSUE TITLE
Logs details not working (JavaScript TypeError)

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#12085]
In Friendica 2022.10:

1. Open https://FRIENDICA_HOST/admin/logs/view
2. Click on a log entry
3. See the JavaScript console in the browser.

In Firefox 106.0.3:

```
Uncaught TypeError: event_data_header is undefined
    show_details_for_element https://FRIENDICA_HOST/view/theme/frio/js/module/admin/logs/view.js?v=2022.10:70
    <anonymous> https://FRIENDICA_HOST/view/theme/frio/js/module/admin/logs/view.js?v=2022.10:22
    jQuery 2
        dispatch
        handle
```

In Chrome 107.0.5304.87:

```
view.js?v=2022.10:70 Uncaught TypeError: Cannot set properties of undefined (setting 'hidden')
    at show_details_for_element (view.js?v=2022.10:70:28)
    at HTMLTableRowElement.<anonymous> (view.js?v=2022.10:22:3)
    at HTMLTableRowElement.dispatch (jquery.min.js?v=2022.10:3:7537)
    at r.handle (jquery.min.js?v=2022.10:3:5620)
```

The details of the log entry is not opened.

**Comment by MrPetovan** [comment]
Thank you for the report, does @fabrixxm want to take first pass at it?

**Comment by fabrixxm** [comment]
I don't have a dev env to test it right now, but It could be that [the class of this div](https://github.com/friendica/friendica/blob/2022.10/view/theme/frio/templates/admin/logs/view.tpl#L124) shoud be `event-data-header` , as searched by [js code](https://github.com/friendica/friendica/blob/2022.10/view/theme/frio/js/module/admin/logs/view.js#L67)

**Comment by MrPetovan** [comment]
Thanks, it was the issue!
