### ISSUE TITLE
Notification of new user registration

### ISSUE THREAD

**Issue by Tuxi2020** [friendica/friendica#12097]
### Is the feature request related to a problem? Please describe.

As an admin of a friendica server I don't like not being notified about new registrations.

### Describe the feature you'd like

When a new user registers on an instance, the admin should generally be informed by notification in the interface and by mail.

### Describe alternatives you've considered

I am not aware of any alternative

### Additional context
---

**Comment by MrPetovan** [comment]
It is because your node's registration policy is set to OPEN. If you want more control over registrations, you can switch to APPROVE which will notify administrators each time someone registers so that they can be approved.

**Comment by Tuxi2020** [comment]
Even if the registration is set to "open", it makes sense to inform the admin about a new registration.

**Comment by MrPetovan** [comment]
Why? What's your use case?

**Comment by Tuxi2020** [comment]
I would like to know as Admin, who logs on my instance to be able to react possibly as fast as possible, to be able to welcome, u.s.w..
See Topic: https://friendica.bachgau.social/display/aeb64f14-1763-63e4-47a7-55f926504643

**Comment by MrPetovan** [comment]
Got it. I must warn you that it is a somewhat complex feature request, and as such is unlikely to be tackled any time soon. My suggestion remains to switch your register policy to APPROVE in the mean time, or to check your user list every day/week for newcomers.

**Comment by annando** [comment]
In fact it was really simple since we already had got this other notification. This is untested code but I'm sure that it will not neuter your cat.

**Comment by MrPetovan** [comment]
You left out the part about notifications in the interface but hopefully it's enough to satisfy this issue.

**Comment by annando** [comment]
Yeah. The other part definitely would had been slightly more complicated.
