### ISSUE TITLE
mailstream addon: Argument 1 passed to mailstream_do_images() must be an instance of arrat, array given

### ISSUE THREAD

**Issue by bkil** [friendica/friendica#12111]
Seen in the log of someone else:

```
worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to mailstream_do_images() must be an instance of arrat, array given, called in /var/www/html/friendica.example.com/addon/mailstream/mailstream.php on line 378"
```

And indeed:
* https://github.com/friendica/friendica-addons/blob/f2ff1053b096977cf31cca5559a0f7ef6f91e21b/mailstream/mailstream.php#L189
* https://github.com/friendica/friendica-addons/blob/f2ff1053b096977cf31cca5559a0f7ef6f91e21b/mailstream/mailstream.php#L378

**Comment by MrPetovan** [comment]
`arrat` sounds like a typo that is not present in the source code at the moment. What version are they running?

**Comment by MrPetovan** [comment]
Ah, it's present in `stable` but not in `develop`:
- `develop`: https://github.com/friendica/friendica-addons/blob/f2ff1053b096977cf31cca5559a0f7ef6f91e21b/mailstream/mailstream.php#L200
- `stable`: https://github.com/friendica/friendica-addons/blob/408a62a9a16d2613ab37bc9e5dabf5fd63b36b73/mailstream/mailstream.php#L200

**Comment by MrPetovan** [comment]
Closed retro-actively by https://github.com/friendica/friendica-addons/pull/1287

**Comment by bkil** [comment]
Oh. It seems we weren't notified that an update is warranted due to a "release".

**Comment by MrPetovan** [comment]
So, the `develop` branch is ahead of the `stable` branch which only gets updated on releases. The fix will be available in the upcoming release in December.
