### ISSUE TITLE
Email issue / can't log in

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12120]
Hi all, Installation went perfectly, but I lost/misplaced my admin password. No problem, right? Just click on forgot email. Well, that won't work because sendmail on Digital Ocean is not working for me. So I went in and added the phpmailer addon via SSH, but I guess I can't enable it without logging into the admin interface, and I can't do that without my password. So...

Is there an easy way to reset my password via Mariadb? (It looks hashed)
Is there an easy way to enable phpmailer addon without logging in as an admin (because I can't)
Could I just delete the admin user Mariadb and will that re-start the process to create a new admin user?

Any other ideas?

Thanks!

**Comment by jakedfw** [comment]
Just completely re-installed Friendica, and now I know why I don't know my password... you can't set it on install. It is emailed to you. So I'm stuck: Sendmail isn't working, and I can't active phpmail without admin access. Any other mail solutions? Digital Ocean support is slow.

**Comment by tobiasd** [comment]
> Is there an easy way to reset my password via Mariadb?

You can use the `bin/console` command from the base directory of your Friendica installation to change the password of an account.

```
$ bin/console user --help
console user - Modify user settings per console commands.
Usage
        bin/console user password <nickname> [<password>] [-h|--help|-?] [-v]
        [...]
```

**Comment by jakedfw** [comment]
Thanks so much. I found out that Digital Ocean does not allow sendmail via port 25, so the default installation of Friendica won't work there. You need to use a relay, which is quite a bit more complicated to install.

**Comment by tobiasd** [comment]
If you have found a working setup, would you mind to share some notes about the Digital Ocean specific steps?

**Comment by jakedfw** [comment]
I have a solution that I'm currently troubleshooting, but it should work and is free:

1. Sign up for a sendinblue free account (up to 300 emails a day)
2. Install postfix in your linux instance
3. Go to the "Transactional" tab in sendinblue and click on configuration
4. Copy the configuration text they provide for postfix
5. Paste it into the postfix conf file

This should work, but I'm having some authentication problems with sendinblue that I'm working out. 

Thinking ahead, it really does seem that a lot of cloud hosts like Digital Ocean and others are blocking port 25 due to spam email. Adding some documentation to enable SMTP relay via sendmail or postfix with links to mailersend.com or sendinblue.com (both free transactional SMTP service) may be worthwhile.
