### ISSUE TITLE
Twitter quote-shares look empty on remote Friendica nodes

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12137]
See: https://motley.club/display/d8230ed6-3263-67ef-5bdf-4bd647438533
Original post: https://friendica.mrpetovan.com/display/735a2029-5763-67de-b40b-60a545991292

Is this related to your work on shares @annando ? Would it be already fixed on `develop` and the people on `stable` have to wait until the upcoming release?

**Comment by annando** [comment]
I hoped to have it fixed by now, so that both, people on stable and people on develop should have got no display problems.

**Comment by schmaker** [comment]
Obsolete
