### ISSUE TITLE
Weird registration page display issue

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12132]
Hi all, I'm using the Frio theme. In my admin settings I have the following for registration text:

> Welcome to a friendly place. We're glad you're visiting.[br][br] Want to make a home here? This is a small, public server administered by author Jake Kerr. With an account here you can connect with people all across the distributed social web, including users on Mastadon, Friendica, Pixelfed, and other places. There is no Elon Musk or Mark Zuckerberg, just a bunch of neighbors looking out for each other.

However, this is what it shows on the registration page:

> Welcome to a friendly place.

Am I doing something wrong? I'd like to update that to be more descriptive.

Site is here: https:afriendly.place

**Comment by MrPetovan** [comment]
I cannot reproduce this problem with the same text, and your own website looks perfectly normal:
![2022-11-07 01 44 45 afriendly place 196d6840b64b](https://user-images.githubusercontent.com/925415/200242647-fd029978-771d-49d7-81f4-2735cd7d734d.png)

**Comment by haheute** [comment]
@jakedfw I guess you are looking on the wrong page. Try to follow the "register" button, maybe.. 

If you want to customize the "login page": https://wiki.friendi.ca/docs/initicalconfiguration#customize_the_login_page
