### ISSUE TITLE
[mastodon-api] Support header image

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12133]
Minor visual feature request: Would it be possible to set a "header image" for Friendica accounts when talking to those using Mastodon client apps (tusky, fedilab)? They usually display an image in the user profile which is seen for the user as well as for other people visiting ones profile. See in example below; at the moment there's just a (more-or-less appealing) default image:

![tempFileForShare_20221107-093110](https://user-images.githubusercontent.com/685879/200262734-a70bed3f-5ca5-4a51-a9e0-c229961db45d.jpg)

Not sure whether Friendica as an easy-to-do way of supporting that. Just to have it written down. 🙂️

**Comment by annando** [comment]
In fact we only need the frontend to store the data. The whole backend is already present.

**Comment by foss-** [comment]
Does that mean setting a header image in fedilab should current work already? Tried but it results in unexpected results. Shows account name as (null) and then does not store the image. So either the backend implementation is not working as expected or there is a problem in Fedilab?

**Comment by annando** [comment]
With "frontend" I meant everything that a user can reach.

**Comment by tobiasd** [comment]
Which fields have to be set?

**Comment by annando** [comment]
There is the function `Photo::uploadBanner` that does all the work. One could call it with this line:
```
Photo::uploadBanner($uid, [], $url);
```

**Comment by tobiasd** [comment]
Thanks, I'll have a look into it. But I'm on the road over the weekend, so I
cannot say how long this look will take.

**Comment by Ryonez** [comment]
Would love to see this implemented!

**Comment by kr428** [comment]
Seems fixed in 2022-12 RC. Cool, thanks. 🙂
By the way does the profile pic show up somewhere in the web profile too?

**Comment by foss-** [comment]
Don't think this is in friendica webUI itself. You can only see this in mastodon clients and also confirming this works as expected now 2022.12RC via Fedilab and Tusky.

**Comment by MrPetovan** [comment]
We don't have a good way to display the header picture in the current version of the profile page of either theme, so it's a job for someone else™.
