### ISSUE TITLE
Home page icon leads to json output

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12148]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

Opening my instances home/login screen (before login) I see an 'i' icon which probably should show some information about the site. It leads to the /friendica url which reurns a json with some information (mostly technical). 

### Steps to Reproduce

1. Open your instance home screen (before login)
2.  Click on 'i' icon in upper rigth corner

Actual Result:

json with some information

Expected Result:

Web-page with information

### Platform Info

Friendica Version:

Friendica 2022-10

Friendica Source: 

Docker image

**Comment by MrPetovan** [comment]
Thank you for the report, do you mind sharing your domain name to reproduce the issue?

**Comment by ne20002** [comment]
fm2.0x42.ch

**Comment by MrPetovan** [comment]
Thanks, I was able to reproduce this your server, but not mine. Worse, your server seems to be skipping a critical check in the code based on the request header to be serving this specific content.

Let me explain.

The `/friendica` route is supposed to show this: https://friendica.mrpetovan.com/friendica

The `/friendica/json` route is supposed to show this: https://friendica.mrpetovan.com/friendica/json

It's close, but the data isn't the same.

What shows on your server shows on mine when I request `https://friendica.mrpetovan.com/friendica` with the HTTP request header `Accept: application/json` which regular browser don't send, this is why I can't easily show it to you.

To troubleshoot your server, you'll need to be able to edit your `src/Module/Friendica.php` file on your server, would you be able to do that?

**Comment by ne20002** [comment]
Hi @MrPetovan 
Thank ou. This information pointed me to the problem's root cause. Disabling caching in the reverse proxy for the friendicy server fixed it.
So: not a bug. (I still need to get the cache fixed).

**Comment by ne20002** [comment]
Hi @MrPetovan 
After reinstalling my friendica instance the issues popped up again. So I believe this is a bug. As you described in your post, the uri /friendica is used for two different purposes.

a) the /friendica url seems to be used to transfer node information between friendica nodes. I have a lot of calls to this /uri in my log files. This is where the JSON is the response data (and set with Cache-Control to be cached).
```
5.161.116.250 - - [31/Dec/2022:08:28:01 +0100] "GET https://fedi.0x42.ch/friendica HTTP/1.1" 200 2698 "-" "http.rb/5.1.0 (Mastodon/4.0.2+glitch; +https://indiepocalypse.social/)" 0.010
8
```

b) the /friendica url is also used in the landing/login page (on the small i in the upper right corner) to show the rules and some info to users (this response comes with Cache-Control: no-store no-cache).
```
fd42:0:0:41::da8 - - [31/Dec/2022:09:46:17 +0100] "GET https://fedi.0x42.ch/friendica HTTP/2.0" 200 4026 "https://fedi.0x42.ch/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.019
```
Using a nginx reverse proxy the cache key is build with the url, but not including any headers. So this is causing the issue seen.

I currently excluded the /friendica from caching to solve this for me but as the /friendica is called quite often, caching would be an advantage.  It is the only page where this issue comes up.

As mentioned above: yes I am able to edit a php file (but not experienced with php). I believe changing the url for the non json info page to something different would fix the problem. 

And a happy new year to you (all).

**Comment by MrPetovan** [comment]
This sounds like a web server configuration issue over which we usually have little control, but in this case there’s something we can do. As part of our effort to replicate some look and feel ofMastodon for remote users, we’ve created the `/about` route are as an alternative to `/friendica` so we could switch the link so that you won’t have this caching issue anymore.

**Comment by ne20002** [comment]
Yes, switching to /about would solve the problem.

Having the /friendica call giving different results based on a http header is somewhat unexpected. Afaik, there is a common sense that a default cache key would be $scheme$proxy_host$request_uri. This is convention. To prevent others to trap into same issue, having the change to /about would be appreciated.

Using a cache on a reverse proxy can significantly reduce load on the application server.

**Comment by annando** [comment]
This happens a lot in the Fediverse. We have got other places as well (like `/profile/` and `/display/`) where the system has to check for the headers to return the appropriate output.

**Comment by ne20002** [comment]
Hmm. Havent't found any other problems yet. 
Maybe for those endpoints the Cache-Control is not set for caching. A reverse proxy cache bases its caching decission on the Cache-Control header as the browser does.

For /profile Cache-Control is set to 'no-cache, no-store, must-revalidate'. So this wouldn't be an issue.

Using http-headers for selecting appropriate output is ok (but unexpected) as long as the Cache-Control is set accordingly. Or it shall be mentioned somewhere if a header must be added to the cache key to get it working correctly.

**Comment by MrPetovan** [comment]
The value of the HTTP request header “Accept” should be included in the cache key since its sole purpose is to vary the output of the same URI.

The switch to `/about` is just a workaround we can do in this case, but you should improve the specificity of your cache key.

**Comment by ne20002** [comment]
I changed the cache key to include the "Accept" header.

Many thanks for helping.

**Comment by GidiKroon** [comment]
I came across this same issue, so I'll add my comments here instead of making a new one.

When content negotiation is used by a server to serve different content based on e.g. `Accept` or `Accept-Encoding` (etc) headers, and the server allows caching with the `Cache-Control` headers in at least some of the negotiated cases, it should add a `Vary` header to indicate this. The `/friendica` and `/profile` paths in Friendica are missing the `Vary: accept` header, so caching frameworks will cache whatever comes first. I had indeed `/friendica` and my profile show up as json in my browser.

For now I fixed it by doing a hard override in Apache to add the `Vary: accept` header no matter what. But the documentation of e.g. mod_cache suggests it's up to the origin server (Friendica) to add this header in appropriate cases. See "Variable/Negotiated Content" in https://httpd.apache.org/docs/2.4/caching.html.

> Variable/Negotiated Content
> 
> When the origin server is designed to respond with different content based on the value of headers in the request, for example to serve multiple languages at the same URL, HTTP's caching mechanism makes it possible to cache multiple variants of the same page at the same URL.
> 
> This is done by the origin server adding a Vary header to indicate which headers must be taken into account by a cache when determining whether two variants are different from one another.
> 
> If for example, a response is received with a vary header such as;
> 
> Vary: negotiate,accept-language,accept-charset
> 
> [mod_cache](https://httpd.apache.org/docs/2.4/mod/mod_cache.html) will only serve the cached content to requesters with accept-language and accept-charset headers matching those of the original request.
> 
> Multiple variants of the content can be cached side by side, [mod_cache](https://httpd.apache.org/docs/2.4/mod/mod_cache.html) uses the Vary header and the corresponding values of the request headers listed by Vary to decide on which of many variants to return to the client.

And see https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation:

> The server uses the [Vary](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) header to indicate which headers it actually used for content negotiation (or more precisely, the associated request headers), so that [caches](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching) can work optimally.

For now my solution is to add this to the Apache configuration for the site, but this is not ideal:

```
    <IfModule mod_headers.c>
        <Location "/index.php">
            Header merge Vary "Accept"
        </Location>
    </IfModule>
```

I believe the affected paths include `/friendica`, `/about`, `/profile`, `/display` and `/object`.

**Comment by MrPetovan** [comment]
Thank you for the comment, I’ll reopen this issue since there’s actionable information.
