### ISSUE TITLE
Boosted post displayed like Mastodon backend in Tusky

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12149]
In Tusky a boost is displayed differently based on the backend. 

This is how the boost is displayed with an account on a Mastodon server:
![image](https://user-images.githubusercontent.com/39007279/200792411-eecaa7f4-6c72-449c-90db-40140fb7dcde.png)

This is how it is displayed with a Friendica backend:
![image](https://user-images.githubusercontent.com/39007279/200792642-db40d8ca-5ca0-499e-b648-344e3a3016b9.png)
![image](https://user-images.githubusercontent.com/39007279/200792759-3aec71d8-b113-479c-81f3-9aaa320e38c9.png)

I believe there are some fields in the api filled or not filled in the same way.

**Comment by ne20002** [comment]
I also realized that the numbers on the boost icon are not (always?) correct when using friendica as backend. It looks like
0 or 1 is shown as 0
2 is shown as 1
3 or more is shown as 1+

**Comment by hlad** [comment]
it seems that reblog field is always null in /api/v1/timelines/home

**Comment by annando** [comment]
@hlad Do you have got some background on how exactly this field should look like? It would be great, if you had got some real life JSON structure.

**Comment by kr428** [comment]
Looks resolved indeed in 2022-12. Thanks. :+1:
