### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12159]
Can't quite figure out this error message on my admin user page:

`The logfile 'log/friendica.log' is not usable. No logging is possible (error: 'Directory "" cannot get created: Invalid path')`

Which directory do I need to create?

**Comment by MrPetovan** [comment]
Is the `log/` folder existing in your Friendica base install folder? Does it have write permission for your web server user (usually `www-data` or `friendica` if you created a specific user for it)?

**Comment by jakedfw** [comment]
That did the trick. Thanks!
