### ISSUE TITLE
Friendica not working in sub-directory on NGINX

### ISSUE THREAD

**Issue by alex9434** [friendica/friendica#1215]
Unfortunately my contract does not allow me to create sub-domains. Therefore I have tried to install friendica in a sub-directory https://myserver/friendica
I have added the recommended rules to NGINX and created and populated the database with a manual install
    location /friendica/ {
        index index.php;
        if (!-f $request_filename) {
            rewrite ^/friendica/(.+)$ /friendica/index.php?q=$1 last;
        }
        try_files $uri $uri/ =404;
    }
However, it does not work. When I click on register, the site tries to open
https://register/ instead of http://myserver/friendica/register/
Also CSS etc. does not seem to load.
Any ideas what I am doing wrong?

**Comment by Beanow** [comment]
There are several points in the system that require Friendica to be at root level currently.
I think this is an issue we should solve, but this will take some time for it to work well.

**Comment by MrPetovan** [comment]
For anyone still wondering, this is the intended way for rewrite to be written for a subfolder in nginx (taken from Wordpress):
````
location /friendica/ {
    index index.php;
    try_files $uri $uri/ /friendica/index.php?$args;
}
````
It won't work out of the box with Friendica, most notably because we expect the parameter `pagename`, so maybe something like
````
location /friendica/ {
    index index.php;
    try_files $uri $uri/ /friendica/index.php?pagename=$args;
}
````
But I'm not using nginx at the moment so I can't vouch for it.

**Comment by MrPetovan** [comment]
Closed for inactivity.
