### ISSUE TITLE
add option to block #hashtags on user level

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12165]
Some topics a user may not be interested in at all. So for the occasional #unwantedTopic hashtag by contacts they do not want to unfollow, a hashtag blocking option would be very useful.

This issue is a featuer request to allow blocking hashtags on user level.

**Comment by MrPetovan** [comment]
The NSFW addon already has this covered. It only collapses posts but since they are coming from someone you're actually following, I believe it's enough, no need to remove the post completely from your timeline.

**Comment by foss-** [comment]
Will test and see how it feels.
