### ISSUE TITLE
mysql exception error from log

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12170]
Getting a ton of these:

`Uncaught Exception mysqli_sql_exception: "Connection refused" at /var/www/html/src/Database/Database.php line 168`

**Comment by MrPetovan** [comment]
Please consider increasing the number of simultaneous connections allowed by your database server. What MySQL flavor are you using?

**Comment by jakedfw** [comment]
Using MariaDB. And now I annoy you with asking how to increase the simultaneous connections. Sorry I'm not more technical!

**Comment by MrPetovan** [comment]
No, it's okay, I asked you so that I could give you the most accurate answer!

**Comment by MrPetovan** [comment]
So, in the `[mysqld]` category of your MariaDB server configuration, you should have a `max_connections` directive, by default set to 100. Please try to raise it to 200 (my current value for a single-user Friendica node).

On Debian-like system, the relevant configuration file will be `/etc/mysql/mariadb.conf.d/50-server.cnf`, but I encourage you create an additional file in this folder named `51-server-<your hostname>.cnf` with just the following content:
```
[mysqld]
max_connections = 200
```
This way you can move the file with your custom configuration instead of tampering with package-installed files.

Let me know if I can assist you further.

**Comment by jakedfw** [comment]
I both increased the limit to 250 in the 50-server.cnf and created 51-server-afriendly.place.cnf with the lines, and I'm still getting that error. :(

**Comment by MrPetovan** [comment]
Did you restart the service after editing these files? Let me know if you need help with this.

**Comment by jakedfw** [comment]
I rebooted the server, assuming that would restart the instance. If not, I guess I'll need to restart MariaDB directly? I just restarted MariaDB AND rebooted. Let's see if that helps! LOL

**Comment by MrPetovan** [comment]
Rebooting the server isn’t necessary, but it would be enough. Normally you’d just restart the service you changed the configuration of.

**Comment by jakedfw** [comment]
Still getting the error. It seems related to fetching new ActivityHub feed data just due to its intermittent nature. Pretty much at a loss and may abandon my personal server (I'm just using it for fun anyway).

**Comment by MrPetovan** [comment]
I’m sorry, I don’t know how to troubleshoot this non-specific error further.

**Comment by jakedfw** [comment]
Boy, I _really_ hate the Mastadon UI and how it handles pretty much everything. I will have to maybe do a clean and manual Friendica install without following a website tutorial, because for those used to a "friend" model like Facebook, Mastadon is near unusable, while Friendica is much, much better.

Anyway, I simply don't have the knowledge to troubleshoot database issues, so a clean install is probably the quicker solution for me. LOL.

**Comment by jakedfw** [comment]
Hrm. I think I found the problem. I'm using PHP 8.1, and that's not supported yet, correct?

**Comment by MrPetovan** [comment]
Only because none of the developers have a working PHP 8.1 environment, but it shouldn't fail this way. When new versions of PHP are released, we usually receive reports of deprecation errors that we fix to the extent of our knowledge of the new version. This doesn't look like it.

**Comment by jakedfw** [comment]
I think I isolated the problem. No errors in over 24 hours. I simply upgraded the hardware of my instance.

I basially changed the memory from 1 GB to 2 GB.

**Comment by MrPetovan** [comment]
This would help immensely as well!

**Comment by jakedfw** [comment]
Okay, it's been totally stable for over 48 hours now. I'm 99% sure that this was my using underspecced hardware. 

May I humbly suggest that you all add guidance on minimum hardware specs for a Friendica instance? Believe it or not, the Mastadon instance is more stable on 1 GB, while Friendica requires 2 GB (from my admittedly non-scientific experience). 

That may sound dumb for a public server, but I think my use case will become more common: A small one-user instance that uses a custom domain for branding. In those instances, people will be looking at smaller cost-effective set-ups.

**Comment by MrPetovan** [comment]
Yes, the suggestion is a good idea. Unfortunately, we aren't anywhere from this kind of memory usage optimization, so in the mean time, minimum 2G memory it is.

**Comment by MrPetovan** [comment]
The Requirements page on the blog is updated: https://friendi.ca/resources/requirements/
