### ISSUE TITLE
Browser scrolls on its own

### ISSUE THREAD

**Issue by roughnecks** [friendica/friendica#12175]
Hello,
I'm a new user and I can't read any post in the network global activity because my browser (latest chrome on Windows 10) keeps scrolling below to half page - I guess whenever there is new content published.

How do I stop the feed from endlessly reloading so that I can read what's already on my screen?

Thanks

**Comment by roughnecks** [comment]
Found the option to not refresh under "Display - Themes"
`Update browser every so many seconds: -1`

**Comment by MrPetovan** [comment]
Hi @roughnecks , you can also disable the automatic refresh unless the browser is at the top of the page in Settings -> Display -> Content -> Automatic updates only at the top of the post stream pages
