### ISSUE TITLE
Strange issue with pending registrations requests

### ISSUE THREAD

**Issue by Nodens-** [friendica/friendica#12187]
- [X] I have searched open and closed issues for duplicates

### Bug Description

 I have a rather strange issue. This is a kind of fresh instance, running for about a week. At some point, initially I set confirmation mode for registrations briefly before settling for open with invite only while I tweak performance options. I never checked initially but I then saw a "pending 2 registrations" that after a couple of days increased to 4. At the /admin/users/pending page though, I see a huge list of accounts. The first one has a blank name and the second one has my name. Batch or single deny of those accounts does absolutely nothing although I get the popup that the account has been rejected. They're still there. As you can see also all of them have the same timestamp.

Searching for existing issues on this repo I saw `pending-view` in one comment and did a `select * from ``pending-view``;` which results in `220096 rows in set (0.651 sec)`. Having no familiarity with the project and being just barely familiar with php (I work with low level languages), I have no idea if this is correct but it doesn't sound so. I took a look at the `register` table and I saw it indeed has 4 entries there BUT the hashes of those 4 entries match the hashes of those 220096 rows. Apparently they're all split up into those 4 hashes and they all look like remote federated profiles and/or relays. Eg:
```
|  5 | hash | 2022-11-15 17:22:07 |   0 |          |          | NULL |    0 | Name                                                                                                                          | https://friendica.xyz/profile/username                                                                     |                                                                                          |       | username                                       |
|  5 | samehash | 2022-11-15 17:22:07 |   0 |          |          | NULL |    0 | Another Name                                                                                                                         | https://pztrn.online/profile/username2                                                                        |                                                                                          |       | username2                                         |
***snip***
|  5 | samehash | 2022-11-15 17:22:07 |   0 |          |          | NULL |    0 | System Account                                                                                                                     | https://fd.korako.me/friendica                                                                             |                                                                                          |       | friendica                                      |
|  5 | samehash| 2022-11-15 17:22:07 |   0 |          |          | NULL |    0 | relay                                                                                                                              | https://diaspora.vigori.us                                                                                 |                                                                                          |       | relay                                          |
```

So I'm at a loss at what's going on here. Apart from this everything else *seems* to be working properly...

I'm using the frio theme but I tested others and the result is the same. This looks like a db issue? There are no errors in friendica log, or apache's or php-fpm's apart from deprecation notices.

### Steps to Reproduce

1.  Visit /admin/users/pending on my instance.

Actual Result:

Strange huge list of accounts.

Expected Result:

4 accounts waiting for confirmation listed (although I believe they shouldn't be any at all but 4 are listed on the counter)

### Screenshots

![Capture](https://user-images.githubusercontent.com/2942378/202029478-2e597632-074a-4af7-8ebf-161f1968da8b.JPG)

### Platform Info

Friendica Version: `Friendica 'Giant Rhubarb' 2022.10 - 1484`

Friendica Source: Stable from git.

PHP version: 8.1.12 on Fedora Server

SQL version: Mariadb 10.5.16 ( mariadb-10.5.16-1.fc36)

**Comment by MrPetovan** [comment]
Alright, so something went really wrong when creating this registration approval, as the `uid` should never be 0. This is a special value for the system user and for the note-wide record of contacts both local and remote. So having a registration approval with `uid = 0` will match the system user but also all the contacts your node knows about in the view.

Are all the rows in your `register` table with `uid = 0` ?

**Comment by Nodens-** [comment]
Yes, all 4 of them as seen here: 
![Capture](https://user-images.githubusercontent.com/2942378/202868463-3eff4a19-ff38-4c90-a215-08d0a6b01d15.JPG)

Should I just drop the 4 rows in the `register` table? Also is it possible that this is affecting something elsewhere down the line that I should check?

**Comment by Nodens-** [comment]
These don't even look like normal registration requests. Shouldn't they have the password column filled?
I had the `libravatar` plugin installed for a bit which somehow broke registrations. New users would land on a blank white page after hitting register and the password was not mailed to them (probably never generated) until I saw the error in the logs and disabled the plugin. I wonder if this related somehow due to the missing password column?

**Comment by MrPetovan** [comment]
Possibly. And yes, you can drop these 4 rows, they aren't of any use to you with a uid = 0.

**Comment by MrPetovan** [comment]
No other issues of this kind have been reported since, it's a tentative close.
