### ISSUE TITLE
Worker queue is empty

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12195]
HI all my worker queue doesn't seem to be firing. 

Here's my cronjob -e setting:

`*/10 * * * * cd /var/www/html; /usr/bin/php bin/worker.php`

I ran it manually, and it appears to be working. Just the cronjob isn't working. 

Note that I have no php folder in /usr/bin

Inside /usr/bin I have files: `php` and `php8.1`

**Comment by MrPetovan** [comment]
How do you know it isn't firing?

**Comment by jakedfw** [comment]
That's a good question. I'm not seeing any updates and the worker queue is empty. It could just be bad luck. I'll give it 24 hours.

**Comment by MrPetovan** [comment]
Any updates from where?

**Comment by jakedfw** [comment]
Workers are required to get updates from followers and people you follow. (right?)
I'm waiting for followed posts to show up
That would confirm workers are... working!

**Comment by jakedfw** [comment]
I tested it with another account, and it turns out that everything is working great. I was assuming that the worker queue would always be pretty long. Sorry for the false alarm!
