### ISSUE TITLE
[vier] Cannot view contacts using link on profile side

### ISSUE THREAD

**Issue by dceonline** [friendica/friendica#12193]
- [x] I have searched open and closed issues for duplicates

### Bug Description

if you follow the link "view contacts" on your profile side an error side is shown

### Steps to Reproduce

1.  go to your profile
2.  click on link view contacts 
3.  called url https://yourdomain.tld/profile/yourusername/contacts shows error side

Actual Result:

error side

Expected Result:

List of all my contacts

### Screenshots

![screenshot](https://user-images.githubusercontent.com/8067791/202176423-56496837-2952-4a99-9ba3-6ad0470c3531.png)

### Platform Info

Friendica Version:
2022.12-dev (last update pull today)

Friendica Source: 
github develop branch
PHP version:
PHP 8.1.12
SQL version:
MySQL 8.0.31

**Comment by MrPetovan** [comment]
Thank you for the report!
