### ISSUE TITLE
Hovercard is not displaying

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#12219]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The hovercard appears only if the "Stay local" setting is disabled, if the checkmark is set the hovercard does not appear.

### Steps to Reproduce

1.  Go to `Settings - Display`, mark `Stay local`
2.  Go to your timeline
3.  Click on an avatar to make the hovercard appear.

Actual Result:

Nothing happens, the hovercard does not appear. 

Expected Result:

The hovercard appears

Discussion on the support Forum: [https://friendica.xyz/display/adf174d5-5163-795d-0792-6b7788407842](https://friendica.xyz/display/adf174d5-5163-795d-0792-6b7788407842)

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2022.12-dev - 1490

Friendica Source: git

PHP version: 8.0.25

**Comment by MrPetovan** [comment]
Caused by https://github.com/friendica/friendica/pull/12215 that was attempting to fix the Hovercard display when "Stay local" is disabled.
