### ISSUE TITLE
Double share display coming from Friendica

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12212]
Original share post: https://friendica.myportal.social/display/e65e1095-4063-77fb-c9cf-3cd562746355
Received share post: https://friendica.mrpetovan.com/display/e65e1095-4063-77fb-c9cf-3cd562746355

I also received the shared post itself.

**Comment by MrPetovan** [comment]
Oh no, it's worse with custom emojis that aren't resized properly in the double share:

Original share post: https://friendica.myportal.social/display/e65e1095-5763-780c-af6f-2be032598698
Received share post: https://friendica.mrpetovan.com/display/e65e1095-5763-780c-af6f-2be032598698

**Comment by annando** [comment]
I guess that this is an issue with the `stable` release. I have seen this a lot by especially this machine.

**Comment by MrPetovan** [comment]
Thanks, I'll close for now.

**Comment by annando** [comment]
I now found the cause - and its tricky.  The system transmits a reshare via AP and some regular post (with the quoted text) to Diaspora. So at first everything is okay. Then someone from Diaspora likes the post. This like is distributed by the system to their followers. The like arrives at another Friendica system. That system doesn't find a regular post for that guid that has been liked. So it fetches it - and receives the post like it had been prepared for Diaspora.

**Comment by annando** [comment]
PR https://github.com/friendica/friendica/pull/12243 contains some quick fix to prevent Diaspora posts from having added posts. This should prevent at least such duplicated posts.
