### ISSUE TITLE
Registration email does not send initial password

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#12229]
For the past 3 months, I have had a Friendica node called washington dot community network dot us. I created it using the June 2022 version of Friendica and initially it worked as expected. New members could register and be sent an email with an initial password. However, recently instead of being sent an initial password, new members are sent an email with what appears to be some sort of encypted code. I therefore created a new Friendica node called friends dot community network dot us using the October 2022 version of friendica. Sadly, it has the same problem. Even worse, when I register as the admin, I am also sent what appears to be an encypted email. Even clicking on reset password results in being sent an encypted email. Any ideas on what is creating this problem?

**Comment by MrPetovan** [comment]
Thank you for the report, can you please submit a redacted excerpt of the raw email?

**Comment by davidspring** [comment]
Thank you for your help. Here is the top part. The bottom is more of the same:
--2-926021655-428688460=:75248
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

CkRlYXIgRGF2aWQgVGVzdDEsCglBIHJlcXVlc3Qgd2FzIHJlY2VpdmVkIGF0ICJGcmllbmRpY2Eg
U29jaWFsIE5ldHdvcmsiIHRvIHJlc2V0IHlvdXIgYWNjb3VudCBwYXNzd29yZApUbyBjb25maXJt
IHRoaXMgcmVxdWVzdCwgcGxlYXNlIHNlbGVjdCB0aGUgdmVyaWZpY2F0aW9uIGxpbmsKYmVsb3cg
b3IgcGFzdGUgaXQgaW50byB5b3VyIHdlYiBicm93c2VyJ3MgYWRkcmVzcyBiYXIuCgpJZiB5b3Ug
ZGlkIE5PVCByZXF1ZXN0IHRoaXMgY2hhbmdlLCBwbGVhc2UgRE8gTk9UIGZvbGxvdyB0aGUgbGlu
awpwcm92aWRlZDsgaWdub3JlIG9yIGRlbGV0ZSB0aGlzIGVtYWlsLCBhcyB0aGUgcmVxdWVzdCB3
aWxsIGV4cGlyZSBzaG9ydGx5LgoKWW91ciBwYXNzd29yZCB3aWxsIG5vdCBiZSBjaGFuZ2VkIHVu
bGVzcyB3ZSBjYW4gdmVyaWZ5IHRoYXQgeW91Cmlzc3VlZCB0aGlzIHJlcXVlc3QuCgpGb2xsb3cg
dGhpcyBsaW5rIHNvb24gdG8gdmVyaWZ5IHlvdXIgaWRlbnRpdHk6CgpodHRwczovL3dhc2hpbmd0
b25wYXJlbnRzbmV0d29yay5vcmcvbG9zdHBhc3MvNTAwZTIzYjhhOWRhNWM4ODRlNWY1YTgyZmNh
N2NkOGUKCllvdSB3aWxsIHRoZW4gcmVjZWl2ZSBhIGZvbGxvdy11cCBtZXNzYWdlIGNvbnRhaW5p
bmcgdGhlIG5ldyBwYXNzd29yZC4KWW91IG1heSBjaGFuZ2UgdGhhdCBwYXNzd29yZCBmcm9tIHlv
dXIgYWNjb3VudCBzZXR0aW5ncyBwYWdlIGFmdGVyIGxvZ2dpbmcgaW4uCgpUaGUgbG9naW4gZGV0
YWlscyBhcmUgYXMgZm9sbG93czoKClNpdGUgTG9jYXRpb246CWh0dHBzOi8vd2FzaGluZ3RvbnBh
cmVudHNuZXR3b3JrLm9yZwpMb2dpbiBOYW1lOgl0ZXN0MQoKdGhhbmtzCkZyaWVuZGljYSBTb2Np
YWwgTmV0d29yayBBZG1pbmlzdHJhdG9yCg==

--2-926021655-428688460=:75248
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

**Comment by davidspring** [comment]
My Friendica node is on a Debian 11 virtual private server using the Hestia Control panel. I have two different servers and the same problem occurs on both servers. I have also tried registering with several different computers and again the same problem.

**Comment by MrPetovan** [comment]
Thanks, this sounds like the same issue as described in this thread: https://talkabout.cf/display/c162020a-4763-688c-b552-6bb105124076

It has since been addressed and a fix has been merged in the `develop` branch and will be available in the upcoming December release.

In the mean time, you can apply the fix yourself in the two relevant files: https://github.com/friendica/friendica/pull/12173/files

If you do so, please report back if it fixed your issue and especially if it didn't.

**Comment by davidspring** [comment]
Yes, this does seem to be the same issue that was reported two weeks ago on a different forum. To keep things as simple as possible, I am not using any Friendica addons. Also, my Friendica node I made back in August 2022 from the June 2022 version of Friendica was working fine for about one month. It was using PHP 7.4 I recently updated the site to PHP 8.1 as PHP 7.4 is reaching end of support on November 28. This is when the registration email problem started to occur. I have since rolled the site back to PHP 7.4 and now the email function is working correctly. But obviously, I can not keep using PHP 7.4 much longer. 
I hoped that the October 2022 version of Friendica would allow me to use PHP 8.1 which is why I built a test Friendica node. However, it has the same problem as the June 2022 version of Friendica. Thus, the problem appears to be related to PHP 8.1. 
I read the other issue you linked to and I see that you have created a solution that will be available in the December release of Friendica and will hopefully work with PHP 8.1. Rather than applying the patch you suggested, I will wait for the December release and then test it and report back here if it solves the problem. My Friendica nodes are merely test websites. My real goal is to confirm that Friendica stable version will work with PHP 8.1. This is why I will wait for the December release and report back the results from that rather than adding the patch. 
Thanks again for your help!

**Comment by MrPetovan** [comment]
You're welcome, thank you for the elaboration about the PHP 8.1 compatibility, I was wondering why it started to misbehave all of a sudden. We are aiming for a full 8.1 compatibility by December but I don't have access to PHP 8.1 on my own server running Devuan yet, so most of the work has been done based on reports by other people.

**Comment by MrPetovan** [comment]
Closed by #12173
