### ISSUE TITLE
Fedifinder support for Mastodon function

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#12220]
- [x] I have searched open and closed issues for duplicates

### Bug Description

after I used [fedifinder](https://fedifinder.glitch.me/) and clicked on the "follow user from `@utzer@social.yl.ms` result, which just shows an ererror

Error: 
```
Exception thrown in /var/www/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /var/www/src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /var/www/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /var/www/src/App.php(739): Friendica\Module\HTTPException\PageNotFound->run()
#3 /var/www/index.php(44): Friendica\App->runFrontend()
#4 {main}
```
The Link is https://social.yl.ms/authorize_interaction?uri=https://example.org/@someuser

### Steps to Reproduce

Use Fedifinder with your Twitter account, click a link in the results. 

Friendica Version:
Current Dev

Friendica Source: 
Git

PHP version:
8.1.x
SQL version:
NA

**Comment by MrPetovan** [comment]
Hmm, it's a basic `contact/follow?url=` link, should be easy to add support for it.

**Comment by MrPetovan** [comment]
@utzer Can you please confirm it works with your node after update to the latest `develop`?

**Comment by utzer** [comment]
> @utzer Can you please confirm it works with your node after update to the latest `develop`?

it works. Thanks!
