### ISSUE TITLE
[Mastodon API] Fedilab crashes when editing account details

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12233]
Reported by Fedilab developer in https://github.com/friendica/friendica/issues/11604#issuecomment-1170227232

Users encounter an issue when updating their profile with api/v1/accounts/update_credentials endpoint

Reason being lacking implementation support (as confirmed by annando).

https://github.com/friendica/friendica/blob/05a76a3dc2fd313e660752a7eb139ec2fb3a6667/src/Module/Api/Mastodon/Accounts/UpdateCredentials.php#L40

**Comment by MrPetovan** [comment]
Probably fixed by https://github.com/friendica/friendica/pull/12272
