### ISSUE TITLE
no option to follow an account

### ISSUE THREAD

**Issue by ZwoVierZwo** [friendica/friendica#12235]
If i search for an account i get an overview of that account

but the only thing i can do is "ignore and block" but not a follow that account or unfollow

**Comment by foss-** [comment]
How are you accessing the UI? Desktop? Mobile? Client?

On mobile this is a known issue and follow option has already been added to the dropdown you are referring to. https://github.com/friendica/friendica/issues/10875

On mobile tap the top left three dots and an overlay will show with a `Follow` button. Agree however this is poor discoverability and mobile should ideally not at all use this mechanism and display all info by default. Current implementation is very confusing.

**Comment by loma-one** [comment]
A single click on the user image opens the Hoover button. There it is possible to follow
![Bildschirmfoto am 2022-11-22 um 16 09 27](https://user-images.githubusercontent.com/44441246/203349781-5fd0e7f9-919f-4e09-844a-7cfb88f3b337.png)

**Comment by ZwoVierZwo** [comment]
not on mobile - on desktop - on mobile i use tusky or fedilab

**Comment by foss-** [comment]
Please send a screenshot. I search for `zwovierzwo@social.fedinet.de` and then see

![1](https://user-images.githubusercontent.com/5708172/203665085-d0c052a0-da89-4174-aa57-d737bbab58fb.png)
with the option to `Follow` on the left.

**Comment by loma-one** [comment]
Both options are possible in the browser
1. follow via the hover
2. follow via the profile

**Comment by ZwoVierZwo** [comment]
Function should be available
