### ISSUE TITLE
Image upload broken - Exception method not allowed

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#12245]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Image/photo upload is broken in develop branch.

### Steps to Reproduce

1.  go to your photos page
2.  select 'browse' to find a photo on your device
3.  click 'submit'

Doesn't work with or w/o 'js_upload' add-on.

Actual Result:

```
Exception thrown in .../src/Module/HTTPException/MethodNotAllowed.php:32
Stack trace:
#0 .../src/BaseModule.php(244): Friendica\Module\HTTPException\MethodNotAllowed->content()
#1 .../src/App.php(739): Friendica\BaseModule->run()
#2 .../index.php(44): Friendica\App->runFrontend()
#3 {main}
```

Expected Result:

Well, I want to upload images.

### Platform Info

Friendica Version:
2022.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by AlfredSK** [comment]
Image upload works while creating a new post or comment. I mean, directly in the compose modal it's ok. But not on the photos page.

**Comment by AlfredSK** [comment]
Checked the logfiles. No further messages related to the issue are logged in application and PHP error log.

**Comment by AlfredSK** [comment]
Probably caused by #12228

**Comment by MrPetovan** [comment]
This is slander!

I'll take a look.

**Comment by MarekBenjamin** [comment]
What's the status here? Can I support somehow? I would love to test photo upload 👼

**Comment by AlfredSK** [comment]
The status is that the PR that fixes the issue isn't merged yet. But I think it will be merged very soon.

**Comment by MarekBenjamin** [comment]
Cool! I didn't want to rush anything, I was just asking because I made some changes regarding the upload limit settings and would feel better after testing it thoroughly with direct image upload. ☮️

**Comment by MrPetovan** [comment]
You'll have to move your changes once the PR is merged as I moved the POST part of the `/photos` module to its rightful class.

**Comment by MarekBenjamin** [comment]
No problem, should not be that much of an issue using refactoring in PHPStrom.

**Comment by MrPetovan** [comment]
Never mind, your changes were merged before mine, so I had to do some manual conflict resolution in my branch!
