### ISSUE TITLE
Search for text gives "not found"

### ISSUE THREAD

**Issue by lapo-luchini** [friendica/friendica#12242]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Searching for anything leads to "not found" errors.

### Steps to Reproduce

1. write "test" in the top bar search area
2. press enter

Actual Result:

```log
Page not found

Exception thrown in /usr/local/www/friendica/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /usr/local/www/friendica/src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /usr/local/www/friendica/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /usr/local/www/friendica/src/App.php(719): Friendica\Module\HTTPException\PageNotFound->run()
#3 /usr/local/www/friendica/index.php(44): Friendica\App->runFrontend()
#4 {main}
```

Log file:
```log
2022-11-23T11:37:59Z index [NOTICE]: no data for session {"session_id":"eulcli8bvvfljov86228lgjktt","uri":"/view/theme/diabook/icons/unselected.png"} - {"file":"Database.php","line":77,"function":"read","uid":"57daf8","process_id":61252}
2022-11-23T11:37:59Z index [NOTICE]: no data for session {"session_id":"p29ta7l0r20bpmnjfevuv0uvl0","uri":"/view/theme/diabook/icons/selected.png"} - {"file":"Database.php","line":77,"function":"read","uid":"e6f6a0","process_id":53544}
```

Expected Result:

Searching for any message containing "test" text.

### Screenshots

<img width="757" alt="image" src="https://user-images.githubusercontent.com/420454/203538192-156a3f1a-534d-4a2f-ade8-c703c4648b8b.png">

### Platform Info

Friendica Version: `This is Friendica, version 2022.10 that is running at the web location https://f.lapo.it. The database version is 1484/1484, the post update version is 1484/1484.`

Friendica Source: `git checkout 2022.10`

PHP version: `7.4`

SQL version: `MariaDB 10.5.12`

**Comment by MrPetovan** [comment]
Can you please share the URL in the browser address bar when the Not Found error shows up?

**Comment by lapo-luchini** [comment]
Here it is:
https://f.lapo.it/search?q=test&search-option=fulltext

BTW: other pages such as these are working fine, so I guess it's not URL rewrite fault (?):
https://f.lapo.it/search?tag=JavaScript
https://f.lapo.it/display/6a1cc041-1560-520a-65f0-dad569318136

Which is currently done in `lighttpd` as:
```
  url.rewrite-if-not-file = (
    "^\/([^\?]*)\?(.*)$" => "/index.php?q=$1&$2",
    "^\/(.*)$" => "/index.php?q=$1"
  )
```

Oh, I see: there's a clash between two `q` arguments: one implicit in URL rewrite and one explicit.

**Comment by lapo-luchini** [comment]
I didn't notice 2a526236fd07346a4b1934875c598d5766c672e7, it works now.
