### ISSUE TITLE
FRIO - Clicking on a notification results in error page

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#12258]
- [X] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Getting a notification
2.  Clicking on a notification

#### Actual Result:

- Getting an error page

```
Exception thrown in /FRIENDCAPATH/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /FRIENDCAPATH/src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /FRIENDCAPATH/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /FRIENDCAPATH/src/App.php(739): Friendica\Module\HTTPException\PageNotFound->run()
#3 /FRIENDCAPATH/index.php(44): Friendica\App->runFrontend()
#4 {main}
```

#### Expected Result:

Jump to the notificated thread/comment

### Platform Info

Friendica Version: current developer
Friendica Source:  git
PHP version:: 7.x
SQL version: 10.5.15-MariaDB-0+deb11u1 Debian 11

**Comment by hoergen** [comment]
Same happens, if I use the search field. 
It finds the post (Thread), but when clicking on the timestamp i get the same error page. 

e.g. my own post here https://horche.demkontinuum.de/display/2196d4ee-1863-7f77-0db3-c9b816789416

So I asume it has something to do with the display

**Comment by MrPetovan** [comment]
It's likely that you blocked or ignored the author of the original post, which currently prevents you from viewing the whole conversation.

Are you on the latest `develop`? I've improved the error page language to hint at that possibility instead of a dry "Page not found" message.

**Comment by hoergen** [comment]
> It's likely that you blocked or ignored the author of the original post, which currently prevents you from viewing the whole conversation.

I think that is unlikely, because the same happens, when I search for my own posts (see the link above)

> Are you on the latest `develop`? I've improved the error page language to hint at that possibility instead of a dry "Page not found" message.

Yes I am on the latest develop (pulled an hour ago before I filled the issue. 
While writing I pulled again, restarted the webserver and cleared the cache of the browser.
I used then the timestamp of [my last post](https://horche.demkontinuum.de/display/2196d4ee-1863-7f77-0db3-c9b816789416)  what is currently my last post  on [my profile page](https://horche.demkontinuum.de/profile/hoergen)

![01_temp](https://user-images.githubusercontent.com/24474762/203808880-ba9c572e-a65b-4abb-8688-0036bb4ea3ca.jpg)


I still get the error page

**Comment by MrPetovan** [comment]
Thank you for the elaboration, it doesn't look right if you can't access your own posts.

**Comment by hoergen** [comment]
I noticed that I can follow the notifications when another user followed me  .. I land on the profile page (on my server). But all other notifications are leading to the error page.

**Comment by hoergen** [comment]
I checked the link in the notification .. sorry I didn't do it earlier. One of them is very short  e.g. `https://horche.demkontinuum.de/notification/12673`  

Timestamps have the "old" long urls  (it's not the same)
`https://horche.demkontinuum.de/display/2196d4ee-1863-7f77-0db3-c9b816789416`

is there a shift from long urls to short urls?

**Comment by MrPetovan** [comment]
No, notifications always had short URLs, and the main function of the `/notification` endpoint is to redirect to the relevant page the notification is about, which would be the `/display` link with the GUID of the specific post or reply it is about.

There has been several reports of notifications appearing about items in a conversation that was ignored (which should not happen) and for items in conversations that the user ignored or blocked the original author, which makes the notification leads to a "Page Not Found" error because of the top-level ignore or block (which isn't ideal).

But your problem seems like yet another issue. I'm not sure how to troubleshoot it because of how complicated the database query that checks for conversation display permissions is.

**Comment by hoergen** [comment]
Ah ok, never noticed (or I can't remember) the short urls for the notifications. 
Maybe we should query then the "database guy" @annando  ;)

**Comment by MrPetovan** [comment]
In practice, these short URLs almost never show anywhere, except briefly in the browser status bar when you hover items in the notification dropdown. But if you click on them, it is almost instantly replaced by the target post/contact URL in the address bar.

**Comment by annando** [comment]
They are not really "short url", they are a link to the notification entry. They are used to set the notification to "seen" and then to display the content.

**Comment by hoergen** [comment]
Did you do something, after the last pull the problem seem to be gone. 
Notification links working again and timestamps as well.

I close this issue. Thanks :sunflower:
