### ISSUE TITLE
[Mastodon API] add support for suggestions

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12266]
Fedilab added support for `Suggestions`. It currently [crashes](https://codeberg.org/tom79/Fedilab/issues/541) when that option is tapped using a friendica account.

Would be nice to support that API: https://docs.joinmastodon.org/methods/suggestions/

**Comment by foss-** [comment]
Tom [added some findings](https://codeberg.org/tom79/Fedilab/issues/541#issuecomment-694971):

> I added a fix to avoid that crash. The problem, Friendica uses the api endpoint but doesn't follow the Mastodon payload.
> 
> `/api/v2/suggestions` from Friendica
> 
> 
> ```json
> {
>         "id": "1241329",
>         "username": "xxxxx",
>         "acct": "xxx@xxxxxx.com",
>         "display_name": "xxx xxx",
>         "locked": true,
>         "bot": false,
>         "discoverable": true,
>         "group": false,
>         "created_at": "2022-11-15T14:49:28.000Z",
>         "note": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
>         "url": "https:--------------------",
>         "avatar": "https://---------------------------",
>         "avatar_static": "https-------------------8",
>         "header": "https:-----------------------8",
>         "header_static": "https:-----------------",
>         "followers_count": 5,
>         "following_count": 19,
>         "statuses_count": 33,
>         "last_status_at": "2022-11-25",
>         "emojis": [],
>         "fields": []
>     },
> ```
> 
> 
> For Mastodon:
> 
> ```json
>  {
>     "source": "past_interactions",
>     "account": {
>       "id": "784058",
>       "username": "katie",
>       "acct": "katie@pleroma.voidlurker.net",
>       // ...
>   },
> ```
>

**Comment by annando** [comment]
@foss- I will have a look at it today and intend to fix it immediately.

**Comment by annando** [comment]
Could be fixed by https://github.com/friendica/friendica/pull/12269 but I haven't found the suggestions in the client.

**Comment by foss-** [comment]
> Could be fixed by #12269 but I haven't found the suggestions in the client.

In Fedilab tap the top left profile picture and in the left pane section `My Instance` tap `Suggestions`.

Tested on pirati.ca and suggestions show with profile picture and bio (previously this was just an empty list). Looking good. Also getting the recommendation for the `Developer Memes` account, seems as if recommendations are working as intended.

I find the naming of that section `My Instance` strange, since I see suggestions for people to follow from all sorts of instances. But that then is a Fedilab problem. Can you elaborate on that briefly?

Thanks for tackling this in lightning speed. This is a nice feature for new users.
