### ISSUE TITLE
Cleanup storage

### ISSUE THREAD

**Issue by DanielSiepmann** [friendica/friendica#12260]
### Is the feature request related to a problem? Please describe.

I've setup the system to remove old entries like posts.
This works as the data within database is removed. But the stored files are not removed. They still consume lots of GB of the disk. It would be cool if related storage data is also removed whenever data like a post is removed. That would free up disk space and ease maintenance and costs.

### Describe the feature you'd like

Remove storage once the associated data like a post is removed. This should be part of the existing workers that already delete data. Or as a new worker that will remove outdated data from storage, that would also clean things up on instances where posts are already deleted but stored data is kept.

### Describe alternatives you've considered

Removing files manually, but there seems no easy way to see whether they are still needed, at least not outside of PHP with database access.

### Additional context

This is especially usefull in regard of pricing of instances and maintenance. It would allow single user instances that don't explode in storage consumption over time.

**Comment by annando** [comment]
What do you mean with "stored files" in this context? Currently the storage system is mostly used to cache remote avatar pictures. Concerning these files we already have got a functionality that should remove these files when on your system there aren't any posts of this contact anymore for example.

**Comment by DanielSiepmann** [comment]
I've a single user instance where the storage folder has 24 GB after 1 month. I've setup to auto delete everything after some days which is working. But from what I understand: The storage is also used to store photos and videos of received posts, and this is not deleted, only posts within database, but stored files are kept.

So "stored files" also means photos and videos attached to posts. At least that's my current understanding.

I've checked some files, the largest one, and see:
```
file friendica-storage/0d/92/3e666ca2397c53202072d0770e218eeda02bd3431af5009cccf3ed48a0a2
friendica-storage/0d/92/3e666ca2397c53202072d0770e218eeda02bd3431af5009cccf3ed48a0a2: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=12, height=1270, resolutionunit=2, manufacturer=Google, model=Pixel 3, datetime=2019:01:26 09:58:48, orientation=upper-left, GPS-Data, xresolution=193, yresolution=201, width=952]
```

So no videos at least, but seems like there are a lot of photos. 24G and growing for a small single user instance is a bit much. I've already disabled the proxy as well as caching contact images. This was both turned on until yesterday. But I also don't see a way to clean things up. Renaming the storage folder results in my own pictures not showing up anymore. So deleting everything is not a proper way.

**Comment by annando** [comment]
Yeah the photos are mostly the avatars of (remote) contacts. The pictures of posts are not stored on the system, they are only relayed to decouple the viewer from the target.

**Comment by AlfredSK** [comment]
Btw. there is an option to not store avatars of remote contacts locally. It's located in admin - site - performance. Maybe that helps.

**Comment by MrPetovan** [comment]
What about all the existing stored avatars? After switching off local caching, they aren’t cleaned.

**Comment by DanielSiepmann** [comment]
> Btw. there is an option to not store avatars of remote contacts locally. It's located in admin - site - performance. Maybe that helps.

I've disabled that option, thanks.

> Concerning these files we already have got a functionality that should remove these files when on your system there aren't any posts of this contact anymore for example.

I now have only 23 GB instead of 24 GB, so looks like some files got removed. Thanks for your feedback :)

Still would be cool to have a small hint beside that option and a way to remove the avatars after disabling this option. But I'm happy that it doesn't grow anymore and I happily can use friendica :)

**Comment by annando** [comment]
When I'm not completely wrong, then the system removes the storage when the contact is updated the next time. So for a course of some weeks your storage should shrink.

**Comment by DanielSiepmann** [comment]
Thanks, will have an eye on it and close the issue for now.
Will re-open if it doesn't shrink.

Thanks for your time.
