### ISSUE TITLE
[mastodon-api] Reshares / boosts in the timeline aren't marked as such

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12263]
Tested with fedilab, tusky and tooot against Friendica 2022-10: While in (Friendica, Mastodon) web interface and (Mastodon) app boosts/reshares are marked as such (with that "reshare" symbol and the user who posted this), this doesn't work for Friendica in any of the client apps, making it impossible to distinguish between reshared and actual posts (and sort of messing up timeline a bit as they also affect chronology, given for reshared posts apparently the "original" date of creation is displayed).
Would it be possible to support that via Mastodon API too? I'm unsure whether it is completely a Friendica issue but given it doesn't work in any of the recent client apps, at least it _seems_ somewhat relatd to the data structures provided by the API?

**Comment by annando** [comment]
AFAIK we already have got an issue describing this. Can you have a look for it?

Concerning the issue: Yeah, we have to apply a fix here, this is on the list.

**Comment by kr428** [comment]
Ah indeed. #12149 and somehow #12204. Slipped my attention. Will close this off as dupe then. Thanks.
