### ISSUE TITLE
Shared Posts from the same instance are not shown at /Profile/{nickname} or /profile/{nickname}/status (Home)

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#12262]
### Bug Description

Shared Posts from the same instance are not shown at /Profile/{nickname} or /profile/{nickname}/status (Home)

### Steps to Reproduce

1.  Share a post that was created by an someone else from the same instance 
2.  switch to your Status Site (Home)

Actual Result: Shared Post is not listed (but followers see the post in their timeline)

Expected Result: Should be visible - same effect if you browse to the /profile/nickname/status site of an other account.

### Platform Info

Friendica Version: Dev and stable 

Friendica Source: This repo

PHP version: 8.1

SQL version: Unknown

**Comment by MrPetovan** [comment]
Maybe related to https://github.com/friendica/friendica/issues/11915

**Comment by matthiasmoritz** [comment]
Commenting out this from Module/Profile/Status and the shares are visible. on Profile Page. So it filters to Posts from ACTIVITYPUB? 
```/*
		$condition = DBA::mergeConditions($condition, ["((`gravity` = ? AND `wall`) OR
			(`gravity` = ? AND `vid` = ? AND `origin`
			AND `thr-parent-id` IN (SELECT `uri-id` FROM `post` WHERE `gravity` = ? AND `network` = ?)))",
			Item::GRAVITY_PARENT, Item::GRAVITY_ACTIVITY, Verb::getID(Activity::ANNOUNCE), Item::GRAVITY_PARENT, Protocol::ACTIVITYPUB]);
*/`
