### ISSUE TITLE
[Mastodon API] Header image not applied by clients

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12275]
Followup to https://github.com/friendica/friendica/issues/12233 (thanks for addressing that issue and can confirm: Fedilab is no longer crashing when trying to set header image).

Now when trying to set header image in Fedilab or Tusky, the apps allow image selection, applying the change results in confirmation message, but the image is never set.

Not sure how to provide more details or debug further - no error message is shown.

**Comment by annando** [comment]
For me it works fine. I tested with Tusky and Fedilab as well. (The Mastodon app crashes when I try to edit the profile)

**Comment by foss-** [comment]
Still not working here with Fedilab 3.9.3 or Tusky 20 with pirati.ca.

Both clients give info that the image or profile was updated but the image never shows. Are there any requirements towards the image being used? Any idea how to debug this?

**Comment by annando** [comment]
I could answer that you could ask your local admin - but talking to myself is slightly creepy :grimacing: 

I'm not sure where to look at, but yeah, I will give a try.

**Comment by foss-** [comment]
Made another attempt to change on pirati.ca at 2022-12-04 14:41:45 if the timestamp is helpful when looking at the logs.

**Comment by annando** [comment]
I added some logging. Can you try again? Currently I have got the feeling as if there is some weird interaction to other users if one user is uploading a new banner.

**Comment by foss-** [comment]
Sure, here's another attempt to change profile header image via
Fedilab at 2022-12-04 17:25:30
Tusky at 2022-12-04 17:26:32

**Comment by annando** [comment]
Thanks! I now have got some hints in the logs and some idea.

**Comment by annando** [comment]
This was a "coder too stupid" error ... Gnarf ...

**Comment by foss-** [comment]
And confirming it works. Glad this one got sorted. Thanks for digging in again.
