### ISSUE TITLE
Add /about alias for /friendica page

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#12286]
It is well-known that Mastodon servers have "about server" page `/about` with server rules, admin contacts and list of blocked servers and users go there to check this information.

Friendica has similar `/friendica` page but it is not intuitive for someone unfamiliar with Friendica to find it, especially if they just try to do it the usual way by adding `/about` to the server name. So it would be minor enhancement to make this same page also accessible with `/about` path. Even better if now obsolete but still well-remembered `/about/more` path also leads there (on Mastodon `/about/more` redirects to `/about`).

**Comment by MrPetovan** [comment]
Everything can be done from the `static/routes.config.php` file, it's about duplicating the current `/friendica` route to match `/about` and `/about/more`.
