### ISSUE TITLE
Double notifications when "watched" contact re-shares posts

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12285]
Not sure if this is a bug but it feels like undesired behaviour: Friendica 2022-10, loma.ml. Setup: I do have some users for which I have set up to be notified if they post anything new. Outcome, right now: If any of these users re-shares a post by someone else, I receive two notifications (both in Mastodon-compatible apps and in the web user interface), one about the user that re-shared the post (which is a person I am following) and one for the user that originally posted this. This is a bit surprising, and it would suffice to only have the "reshare" notification.

**Comment by kr428** [comment]
Example for that:
![dupes](https://user-images.githubusercontent.com/685879/204230379-47104678-c172-444d-a8fa-20496a2a3e00.png)

**Comment by annando** [comment]
it is surely intentional, it ensures that you *really* are notified ...

or ... well ... yeah, it is an unintentional behaviour that appeared after some bug fix.

**Comment by kr428** [comment]
Fixed. Thanks. 🙂️
