### ISSUE TITLE
Semantic of `$maximagesize = 0` in code is not unlimited but litteraly 0

### ISSUE THREAD

**Issue by MarekBenjamin** [friendica/friendica#12297]
On the admin site for image upload limits it is stated that "setting 0 bytes for maxfilesize equals no limit", but I found that the case `$maximagesize = 0` is not handled as `INFINITY` but as literally 0 in most cases, e.g. in `Photo.php:982`

```
if ($filesize > $maximagesize) {
				Logger::notice('Image size is too big', ['size' => $filesize, 'max' => $maximagesize]);
				return null;
			}
```

Should we not use -1 for no limited, like in the case for max image length, and set then convert `$maximagesize = -1` to `$maximagesize = INF` 
The case 0 could then be used as "upload disabled"? 

_Originally posted by @MarekBenjamin in https://github.com/friendica/friendica/issues/12267#issuecomment-1331527198_

**Comment by MrPetovan** [comment]
We don't have a concept of "upload disabled" at the moment and I'm not sure it would be welcome. You can try to post an informal poll in the Friendica Admins forum `@admins@forum.friendi.ca`

**Comment by MarekBenjamin** [comment]
Thanks for your input. For this issue, https://github.com/friendica/friendica/pull/12267 is expected to solve correct handling of limit = 0 to be used as unlimited image sizes (inside friendica, php might still prohibit uploading arbitrary large files).

I guess the consistency debate and if it's actually desirable to have a real 0 bytes (deactivated) limit should indeed be done freely in forum.

**Comment by MrPetovan** [comment]
#12267 has been keeping the 0 = unlimited upload size behavior, can we close this present issue?

**Comment by MarekBenjamin** [comment]
Yes, everything is done here at the moment in regard to my above post, since https://github.com/friendica/friendica/pull/12267 is merged now. :-)

Thank you very much
