### ISSUE TITLE
Including pictures in comments

### ISSUE THREAD

**Issue by betamax65** [friendica/friendica#1229]
When including a picture in an article, it could be done very easily to upload during writing. 

In a comment there will only an entry like "[image][/image]" so the user must upload the picture somewhere it is reachable over http(s) and then insert the link between [image][/image]. This is not very easy to handle. So it would nice if posting of pictures would as easy as in article writing.

**Comment by tobiasd** [comment]
This is working now with 3.4.2, so I'm closing this issue
