### ISSUE TITLE
Mirroring feeds as posts is not working

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#12302]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I stumbled upon a problem, my bot/news accounts that reshared feed content stopped working 7 days ago (last shared post), see [here](https://social.yl.ms/profile/earthquake) and [here](https://social.yl.ms/profile/nasa).
_The first account (earthquake) I tried to refresh the contact details of the RSS feed, then altered the feed URL, then unfollowed the feed account (remove the RSS feed contact) and re-added the RSS as a new contact. It seems nothing of that helps._

### Steps to Reproduce

see the italic text part above. 

Actual Result:

nothing is reshared, I think the feeds are not pulled. 

Expected Result:

posts appear... 

### Platform Info

Friendica Version: current develop (last pull 24 hours ago)

Friendica Source: git

PHP version: 8.1.13

SQL version: mariadb Ver 15.1 Distrib 10.9.4-MariaDB

**Comment by utzer** [comment]
The feeds posts show up for @earthquake@social.yl.ms, but just in /network, so the posts are not reshared as own posts (mirrored).

**Comment by MrPetovan** [comment]
The mirroring options have changed recently, can you confirm it sill is set in the contact settings?

**Comment by utzer** [comment]
> The mirroring options have changed recently, can you confirm it sill is set in the contact settings?

yes, it is still set, its this "Spiegeln als meine eigenen Beiträge". 
![image](https://user-images.githubusercontent.com/8361662/205286756-90000155-e81e-40be-af89-19e2dcec3a9b.png)

**Comment by utzer** [comment]
And just to make sure it is not missed, I can see posts from the feed in /network when logged in with that acocunt, but not shared publicly. So I can not see these posts when logged in with another account on that server.

**Comment by utzer** [comment]
@annando not sure if it was this fix, but I can now reshare other accounts posts as my own, did not try it, but the selection is available.
