### ISSUE TITLE
Some Articles will be send twice

### ISSUE THREAD

**Issue by betamax65** [friendica/friendica#1230]
Don't know why, but sometimes an arcticle will automatically send a second time. As you could see in the Picture, my Post was send about 20 Minutes ago, and after 13 Minutes, i got a hint that there is something new on my Pinwall and it is the same Posting again.
The second Posting will also send to the Connectors (in my case: statusnet, twitter, app.net and pump.io)
I don't know what i should looking for in the trace.log, so it did not included here.

![doppelte_post](https://cloud.githubusercontent.com/assets/5044393/5189787/f167387e-74e0-11e4-8357-78555b443ea4.jpg)

**Comment by annando** [comment]
If no one would disagree I would close this issue.

**Comment by Beanow** [comment]
Pump.io is not supported? Or is it filled with bugs? It seems to be an issue that should be solved.

**Comment by annando** [comment]
Since I'm using this addon on a daily base I guess that the origin of that problem is only based on the configuration.

**Comment by annando** [comment]
This should be solved by this pull request: https://github.com/friendica/friendica-addons/pull/248

**Comment by annando** [comment]
@fabrixxm @tobiasd @Beanow Could you have a look at my pull request?

**Comment by annando** [comment]
I got reports that it is working now. I'm closing this issue.
