### ISSUE TITLE
event details do not render correctly

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#12308]
### Bug Description

If you open details of an Event by clicking in the calendar item, text decorations are not renderd correct.

### Steps to Reproduce
1. Ceate a Event and use linebreaks and decorations in the description
2. click on the calendar item
Actual Result:

Description is not displayed correct.

### Screenshots

![smarty_linebreaks_events](https://user-images.githubusercontent.com/1984982/205138438-d07c705e-337f-4683-bd04-1c2f2a99f09a.JPG)

### Platform Info

Friendica Version:

Friendica Source: official/dev

PHP version: 7.4

SQL version: unknown

**Comment by matthiasmoritz** [comment]
Might be created by this 
https://github.com/friendica/friendica/blob/5ea22197ac37c58c82cecb1b8d55bd29077f3924/src/Model/Event.php#L676

**Comment by MrPetovan** [comment]
This may be the only part that didn't recently changed!

**Comment by matthiasmoritz** [comment]
I can debug this tomorrow.
