### ISSUE TITLE
[frio] Defective preview function when creating posts

### ISSUE THREAD

**Issue by Ravenbird** [friendica/friendica#12339]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

When you create a new post and open the preview, you can't scroll it. Only the upper part of the newly created post is displayed.

### Steps to Reproduce

1.  create a new post
2.  go to preview
3.  tadaa

Actual Result:

You can't scroll the preview. Only the upper part of the newly created post is displayed.

Expected Result:

Man sollte die Vorschau scrollen können um sie komplett anschauen zu können.

### Screenshots

![Screenshot - Friendica - Zitieren - kein Scrollen](https://user-images.githubusercontent.com/2757648/205692381-3426d659-165a-4d95-b41b-d05704d47781.png)

**Comment by AlfredSK** [comment]
Btw. works as expected in stable. No possibility to scroll the preview in develop.

**Comment by nupplaphil** [comment]
This defect is frio only, isn't it?

**Comment by MrPetovan** [comment]
Correct.
