### ISSUE TITLE
[fancybox addon] Image gallery is created for only the images <= clicked image

### ISSUE THREAD

**Issue by MarekBenjamin** [friendica/friendica#12331]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

When you click on an image in a post with images and this image is not the last one attached, the fancybox gallery lets you only iterate through the images prior and including the one you clicked on. Images which are attached after the one you clicked are not included in the gallery. 

### Steps to Reproduce

1.  Visit a post with multiple images attached (and have fancybox addon activated), e.g. [here](https://friendica.xyz/display/adf174d5-1363-8cb0-4dcd-455672791341)
2.  Click on the first, second or third image

Actual Result:

The upcoming fancybox gallery lets you only cycle through the one (if you clicked on the first image), two (if you clicked the second image), or three images (if you clicked the third image). 

Expected Result:

Regardless which images on a multiple image attachment post you clicked, the gallery should include all images from the attachment for cycling through. 

### Platform Info

Friendica Version: 'Giant Rhubarb' 2022.12-dev - 1496

Friendica Source: https://github.com/friendica/friendica/tree/62f982cf7e2cc976c578e36c0244d79aeb705522

PHP version: 7.4.33

SQL version: 10.6.11-MariaDB-0ubuntu0.22.04.1

**Comment by MrPetovan** [comment]
Paging @brockhaus

**Comment by brockhaus** [comment]
The gallery seen in this post is no fancybox at all. It is the lightbox gallery that pops up from the template(s).
Please switch off the fancybox addon and you will see: Exactly the same gallery will pop up. The old lightbox gallery does not support image switching.

If it is fancybox you will see a magnifying glass and a close button in the top right corner.

**Comment by MarekBenjamin** [comment]
I see, so that means the actual issue here is: "Fancybox is not loaded / used even if activated"?

**Comment by MarekBenjamin** [comment]
I admit my link was a little bit confusing, of course you have to view the post from an instance where fancybox is activated. 👼

**Comment by MarekBenjamin** [comment]
Please feel free to assign this issue to another one / close it, for it seems that is not a fancybox bug but related to calling the right hooks?

**Comment by brockhaus** [comment]
> I see, so that means the actual issue here is: "Fancybox is not loaded / used even if activated"?

No! This means I intentionally don't load fancybox when there is the chance that lightbox pops up. This is the case on nearly all post internal images. And as I said: I don't know how to hinder lightbox from doing so. If I would start fancy on that images, too, it would be a doubled gallery..

So this is no issue. It works as intended as long I see no way to disable lightbox.

**Comment by brockhaus** [comment]
P.S.: NOW I know how to disable the lightbox maybe.. Have to test it, but if that works, I can exchange this old gallery with fancybox, too! :)

**Comment by MarekBenjamin** [comment]
wuhuu
