### ISSUE TITLE
Disable link preview attachments for inline links

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12345]
I just posted [a comment on a thread](https://friendica.mrpetovan.com/display/735a2029-1163-8f46-7136-c7c892119262) that includes a link on part of the text I wrote. This was intentionally done so as to not be intrusive because it wasn't the main point of my comment, but could prove useful for people wondering what the term I linked was referring to.

Instead a full-blown link preview was created for that link, without it ever showing in the comment post box.

I get the intent when an explicit link is posted inside a comment, like [https://example.com](https://example.com), but it really is disruptive when the link is inline.

**Comment by SpcCw** [comment]
After these changes it seems previews are no longer created for links in comments at all regardless of preview mode settings.

E.g. I have the setting turned to "Show large image" and when I post a comment containing just a link there is no preview - although obviously it is not inline. The setting seems to affect my posts only but comments no longer have previews at all.

Is this intended behavior now? 
@annando
