### ISSUE TITLE
Errors after added csv file to serverblock

### ISSUE THREAD

**Issue by CarlBishop** [friendica/friendica#12342]
Hi All.

I uploaded a csv file with servers to block, but now I get an email every time the worker.php runs.

Here the email content:

`PHP Warning: Undefined array key "domain" in /home/xxxx/web/http://xxx.xxx.com/public_html/src/Util/Network.php on line 194`

One line each domain I added (more than 150).

If I run /bin/console serverblock I see the list:

![image](https://user-images.githubusercontent.com/12203647/205873662-a9b9c93a-6b6c-4eb3-ba07-465f81266f9e.png)

But from the web interface I do not see any info

![image](https://user-images.githubusercontent.com/12203647/205873843-dadfc36e-c2e4-494f-8250-b2a64eaf6250.png)

and of course I cannot modify anything.

I cannot modify any record from the /bin/console:

```
PHP Warning:  Undefined array key "domain" in /home/xxxxx/web/xxx.xxx.com/public_html/src/Moderation/DomainPatternBlocklist.php on line 118
PHP Warning:  Undefined array key "domain" in /home/xxxxx/web/xxx.xxx.com/public_html/src/Moderation/DomainPatternBlocklist.php on line 118
PHP Warning:  Undefined array key "domain" in /home/xxxxx/web/xxx.xxx.com/public_html/src/Moderation/DomainPatternBlocklist.php on line 118
PHP Warning:  Undefined array key "domain" in /home/xxxxx/web/xxx.xxx.com/public_html/src/Moderation/DomainPatternBlocklist.php on line 118
PHP Warning:  Undefined array key "domain" in /home/xxxxx/web/xxx.xxx.com/public_html/src/Moderation/DomainPatternBlocklist.php on line 118
The domain pattern 'ryona.agency' wasn't blocked.

```
My install is latest friendica stable version.

Is there something I am missing? is there a way to recover this situation (may be deleting everything)?

Thank you in advance for any help.

**Comment by CarlBishop** [comment]
I was able to cleanup the situation uploading a csv file with single record and then modify it.

By the way the csv upload doesn't work it shows blank data:
![image](https://user-images.githubusercontent.com/12203647/205880599-95ccd4d9-41a5-41ed-89a2-b770cb6d2dea.png)

**Comment by MrPetovan** [comment]
Thank you for your report, we've already had been made aware of this issue and it was fixed in https://github.com/friendica/friendica/pull/12037. The fix will be available in the upcoming December release.
