### ISSUE TITLE
Automatic "Follow" when liking a post is annoying. Is there a way to adjust this? 

### ISSUE THREAD

**Issue by tokenwizard** [friendica/friendica#12346]
Could not find any help at other sources, but that my just be because I'm not sure exactly what to search for. 

Not sure if this should go in Help or as a Feature Request. When using Friendica, if I "Like" a post, that seems to automatically "Follow" that post/thread. Every single comment made on that post/thread sends me a notification. Just because I like a post does not mean I want to get notified every time someone else comments on it. 

IMHO, liking a post should not automatically follow it. There should be a "Follow Thread" option for when we want to follow a post. I can also see automatically following a post if you COMMENT on it. But as it currently stands, if I'm scrolling and "Like" 5 or 6 posts, by the end of the day, I have so many Notifications that they become burdensome. 

Is there a feature/setting in the Admin dashboard or the app settings that controls this behavior?

**Comment by MrPetovan** [comment]
Thank you for the report, there is no settings adjusting this behavior just yet. I too have felt the burden of this coupling when Fediverse activity picked up after the Twitter purchase by Elon Musk.

**Comment by SpcCw** [comment]
I think we already have this:

![image](https://user-images.githubusercontent.com/35988439/205965544-98b0077f-93fe-470d-9b0c-63be62501bd2.png)

It says "desktop notifications" but I remember Michael said this setting appllied to any notifications.

**Comment by tokenwizard** [comment]
> I think we already have this:
> 
> ![image](https://user-images.githubusercontent.com/35988439/205965544-98b0077f-93fe-470d-9b0c-63be62501bd2.png)
> 
> It says "desktop notifications" but I remember Michael said this setting appllied to any notifications.

Ok, thanks for pointing this out. I will test this setting and see if it does what I need.

**Comment by MrPetovan** [comment]
Huh, neat.

**Comment by tokenwizard** [comment]
Ok, that seems to be working as expected. Thanks for pointing that setting out and explaining that it is not specific to Desktop notifications!

**Comment by MrPetovan** [comment]
> It says "desktop notifications" but I remember Michael said this setting appllied to any notifications.

In these settings, "desktop notifications" is used to separate from "mobile notifications" that would be retrieved via the Mastodon-like API Friendica provides.
