### ISSUE TITLE
[frio] Buttons in comment form are oversized

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#12354]
- [ o ] I have searched open and closed issues for duplicates

I notice that now buttons on new comment form became oversized. It is not much problem on desktop but on mobile they take a lot of space.

Desktop example:
![image](https://user-images.githubusercontent.com/35988439/206249049-13c3a142-f28f-426a-9fe7-7956884606e5.png)

Mobile example:
![image](https://user-images.githubusercontent.com/35988439/206252616-6ed9512a-1ed2-442f-a934-3577be0e8478.png)

I use Firefox but also tried Edge.

**Comment by MrPetovan** [comment]
This is happening because several unrelated elements are sharing the same "icon" CSS class. This size was set recently to control the size the the profile pictures of users in the administration section.
