### ISSUE TITLE
Don't add link preview to mirrored Blogpostings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#12355]
-  [x] I have searched open and closed issues for duplicates

### Bug Description

Entries from the blog/news on friendi.ca are mirrored as full text from the [news](https://forum.friendi.ca/profile/news) account on the forum server. The received posting on a 2022.12-rc node (e.g. [here](https://libranet.de/display/39bbe52a-2bd01f79-c1ac72b80d20adf0) or [here](https://social.diekershoff.de/display/39bbe52a-2bd01f79-c1ac72b80d20adf0)) has an additional "_link preview_" attached that contains the entire blog posting.

This preview should not be attached.

**Comment by MrPetovan** [comment]
Yeah, ideally these pages would return a content extract when a link preview is constructed for them, but we can't expect every page to conform.
