### ISSUE TITLE
Allow api/v1/accounts/[:accountid]/block to block any contact

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12358]
From https://freunde.ma-nic.de/display/3e98eba8-1363-90fc-029c-6fd881679932

> I just found out that the Mastodon API api/v1/accounts/[:accountid]/block only works for followers of my account. The problem is that the Google Play Store demands that ALL contacts can be blocked (like some stupid commentator of a post of an account I follow). Can this be extended?

**Comment by foss-** [comment]
Was surprised to find contacts blocked in Fedilab are not ending up in block list in friendica web UI. Sadly with the user influx to the Fediverse this is now needed.

**Comment by roelfrenkema** [comment]
I second that. They can be blocked in Friendica itself don't understand why the api would be a problem then.

**Comment by foss-** [comment]
Not a problem, someone "just" needs to do the work on the implementation.
