### ISSUE TITLE
Wrong time for last login

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#12367]
### Bug Description

Not important:
I created some test user and logged in after I created it, then I logged out, used the reset password function. 

Then now in /moderation I see in the list of users this:
![image](https://user-images.githubusercontent.com/8361662/206515977-04164f7a-9fbb-4b38-95a4-cade2b65ec2b.png)

This is wrong, it was within the last hour I logged in, maybe it is minutes instead of hours, but not sure. 

User list: /moderation/users/active?o=-register_date

### Platform Info

Friendica Version:

Friendica Source: git

PHP version: 8.1.13

SQL version: mariadb  Ver 15.1 Distrib 10.9.4-MariaDB

**Comment by MrPetovan** [comment]
We now use a `last-activity` field that is used more regularly than the `last-login` date, but we haven't updated its display everywhere, apparently.

**Comment by annando** [comment]
The field `last-activity` is a `date` field, not a `datetime` field. So possibly we shouldn't display the relative date there.
