### ISSUE TITLE
Embedding videos from Gallery via Frio/Vier using Composer and Modal unsuccessful

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12369]
- [x] I have searched open and closed issues for duplicates

Embedding videos from Galley via Frio/Vier using Composer and Modal unsuccessful. No playable frame is displayed, but a link is displayed.

### Steps to Reproduce

- Uploading a video to the media gallery
- Embedding the video by selecting it from the media gallery
- An `[attachment]https://domain.ltd/attach/7[/attachment]` is set.
- Sending the contribution
- A link to the video is set in the post. Clicking on the link triggers a download.
- However, the video is not executed in a playable frame.

Expected Result:

The video is embedded and can be started in the browser.
Function until 2022.10 ok

### Screenshots
![grafik](https://user-images.githubusercontent.com/44441246/206542260-57527ead-282c-4680-86aa-391b7bd0ea03.png)

### Platform Info

Friendica Version: 2022.12-rc from today

Friendica Source: github

PHP version: 7.4

SQL version: 10.4

**Comment by MarekBenjamin** [comment]
@loma-one Hi, how are you even able to upload videos on your instance? I was looking for uploading videos recently myself but did not find any possibility.

**Comment by loma-one** [comment]
For example, go to the Modal module > to the "Browser" tab. There you will find a selection "Images" or "Files".
Upload e.g. an mp3/4, pdf via "Files" and link the object with the output
![2022-12-28_12-08](https://user-images.githubusercontent.com/44441246/209803549-f24112ea-f6aa-42bf-bee2-34589a3b722d.png)

![2022-12-28_12-15](https://user-images.githubusercontent.com/44441246/209803835-fc0673da-99f9-49c0-b5fe-17c9634a7a44.png)

**Comment by MarekBenjamin** [comment]
Thank you!

**Comment by loma-one** [comment]
Embedding videos that have been uploaded to the instance is still not possible. This is one of the basic functions of a social network that one's own videos can be distributed in this way 😢

It would therefore be super good if this could be solved 🤩

![grafik](https://user-images.githubusercontent.com/44441246/221933411-b4781a81-b580-4092-8d4f-241d81e2069f.png)
![grafik](https://user-images.githubusercontent.com/44441246/221933468-1ad0b5c7-4c01-4449-8b79-dcd23f95ebcf.png)
![grafik](https://user-images.githubusercontent.com/44441246/221933583-6537373c-5bba-473e-bdbd-35913be6b3e3.png)

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/12902
