### ISSUE TITLE
Show maintenance page when instance is being updated

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12386]
While squeet me was updating from 2022.09RC to 2022.12RC just now, nothing was showing, just a blank white webpage.

Iirc there should be some maintenance page showing during update. Unclear as to why that is currently not the case.

**Comment by MrPetovan** [comment]
The maintenance page was meant to be shown, but there was a bug in stable showing it. It's been fixed in the 2022.12-rc branch, which means the next time the system will update, it will work as expected.

**Comment by annando** [comment]
Just today I updated squeet.me with the current RC - and according to the issue the blank page occurred. So it doesn't seem to be fixed by now.

**Comment by MrPetovan** [comment]
Anything in the error log?

**Comment by annando** [comment]
Sadly no. So let's see how other systems will behave.
