### ISSUE TITLE
twitter addon not working - "The network type couldn't be detected. Contact can't be added."

### ISSUE THREAD

**Issue by uk3** [friendica/friendica#12394]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I activated the twitter addon and also sucessfully logged into my Account. When I try to follow a twitter user I always get the error-message "The network type couldn't be detected. Contact can't be added."

The debug logs do not show anything related to that.

Remote following other protocols seems to work (RSS for example)

### Steps to Reproduce

See above. 
Connect to UlrichKiermayr@twitter.com or https://twitter.com/UlrichKiermayr always gives the error.

Actual Result:

 "The network type couldn't be detected. Contact can't be added."

Expected Result:

Following the User

### Screenshots
![image](https://user-images.githubusercontent.com/8853188/207096576-f8a54b7f-431c-4379-8c6b-166dfb5ecdb3.png)

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2022.12-rc - 1501

Friendica Source: Git

PHP version:  8.1.9

SQL version: MySQL 8

**Comment by shiribailem** [comment]
Saw this and thought I should ping it for likely closing due to the changes in how Twitter offers their API. Given that it now costs $100 a month for *limited* read access and they probably don't consider Friendica a valid use case.

**Comment by annando** [comment]
When Twitter finally closed the free API access (according to their announcement one month ago they are overdue with this by now), I will walk through all open issues here and will close them. If possible, the Twitter connector will be stripped down to a simple posting connector then.

**Comment by schmaker** [comment]
Obsolete
