### ISSUE TITLE
Nitter Addon for Twitter Reshares

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#12404]
The Nitter Addon currently only works for Twitter posts.

It would be great if it also can handle re-shared posts from the Twitter network.

**Comment by tobiasd** [comment]
The addon works by replacing the word "twitter.com" with the nitter URL. Why does it not work for re-shares for you? I mean, do you have an example where it did not work?

**Comment by AndyHee** [comment]
Sorry @tobiasd , I somehow just saw your reply now.

Here's a random example:

![Screenshot_2023-01-23_22-25-05](https://user-images.githubusercontent.com/28751375/214078705-8ebc9ddd-5e79-426f-bddb-511ef51757c9.png)

The post contains a mention i.e. `@natalieben` So that's properly converted into a nitter link. However, neither the link source (top right hand corner) nor the poster's name link "Jenny Jones" are converted; they are the original twitter links.

Is this a design feature or a fault? I was expecting that at least the link to the original source would be nitterfied. I usually like to see the original post when I'm expecting a long discussion or when I want to explore a mentioned hashtag via nitter.

**Comment by tobiasd** [comment]
I think it is a design feature, due to the usage of the `prepare_body_final` that I think correctly only modifies the content of the postings body but not the meta information.

**Comment by AndyHee** [comment]
I understand. Thanks for the explanation.

**Comment by tobiasd** [comment]
I have not looked into replacing the header / meta information TBH and I'm also not sure if it would be a good thing as I had it often that a nitter instance could not display something due to some reason.

**Comment by AndyHee** [comment]
Yes, it can happen when there is too much demand on the nitter instance. Since running my own nitter server, I have not experienced this any more. 😊
