### ISSUE TITLE
[FRIO] Missing frame on target page

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12406]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

The contact/match & contact/suggestions pages are missing the frame on the target page. See screenshot

### Screenshots
![2022-12-13_21-07_1](https://user-images.githubusercontent.com/44441246/207433976-a12e2177-5ceb-4a10-9b78-4e593469432e.png)

![2022-12-13_21-07](https://user-images.githubusercontent.com/44441246/207434007-172032da-f23b-4a7c-a537-25e0dfdfdab2.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment]
These page templates need a wrapping `<div class="generic-page-wrapper"></div>`.
