### ISSUE TITLE
[FRIO] Spacing of profile data too large

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12408]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
The spacing of the profile data has been changed since 2022.10. The spacing looks unnatural too and should be changed back to the original values. See screenshot

### Screenshots
![2022-12-13_23-00](https://user-images.githubusercontent.com/44441246/207454001-3894590e-2e0e-4890-ba48-49402b119de5.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment]
Oh fun, this regression is related to the change to the `.icon` class I introduced a while back to fix the display in the admin user list in https://github.com/friendica/friendica/pull/12196
