### ISSUE TITLE
[FRIO] Embedded images are not shown in the preview in Modal an Composer

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12401]
- [x] I have searched open and closed issues for duplicates

### Bug Description
If an image is included in a text via Frio Modal/Composer and the preview is activated, these images are not displayed.

### Steps to Reproduce

Set text
Embedding an image from the Gallery
Preview text & image
The embedded image has public rights

Actual Result:

Text and images are not displayed correctly in the preview.
After sending, both images are displayed correctly.

Expected Result:

Text and images are displayed correctly in the preview.
After sending, both images are displayed correctly.

### Screenshots
![Screenshot 2022-12-13 at 06-26-32 Dis le moi! Network](https://user-images.githubusercontent.com/44441246/207234951-e261a863-ec21-408b-8102-b6fe07d48916.png)

![Screenshot 2022-12-13 at 06-26-58 Dis le moi! Network](https://user-images.githubusercontent.com/44441246/207234964-18d765ff-c20f-4eab-9532-f38d813b8b00.png)

![Screenshot 2022-12-13 at 06-27-26 Dis le moi! Network](https://user-images.githubusercontent.com/44441246/207234979-b5d898ff-6cbd-4036-a141-a1cd44cca672.png)

![Screenshot 2022-12-13 at 06-27-41 Dis le moi! Network](https://user-images.githubusercontent.com/44441246/207235013-a3f96f03-6a1a-401f-9e5f-802d25c177e9.png)

![Screenshot 2022-12-13 at 06-36-00 Dis le moi! Compose](https://user-images.githubusercontent.com/44441246/207235307-291521d7-44f2-4ba9-a5b3-8aa9de9ac8a6.png)

![Screenshot 2022-12-13 at 06-36-30 Dis le moi! Compose](https://user-images.githubusercontent.com/44441246/207235319-50e9abd8-f854-4a07-b530-3ae653836153.png)

![Screenshot 2022-12-13 at 06-39-13 Pinnwand-Bilder](https://user-images.githubusercontent.com/44441246/207235800-158526ec-7d6b-4362-8026-7a93497e0007.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by loma-one** [comment]
I assume that these problems could be related. Therefore a reference https://github.com/friendica/friendica/issues/12369

**Comment by Singh-in** [comment]
the same on opensocial.at

![Screenshot 2022-12-17 at 06-49-02 The Open Social Network Network](https://user-images.githubusercontent.com/62051161/208227535-5d2d0ec4-5cad-40fb-8a25-2439bf1f829e.png)
![Screenshot 2022-12-17 at 06-49-17 The Open Social Network Network](https://user-images.githubusercontent.com/62051161/208227542-9394d7dd-8ca8-46dc-bdcc-9bc603341fb9.png)
![Screenshot 2022-12-17 at 06-49-45 Pinnwand-Bilder](https://user-images.githubusercontent.com/62051161/208227548-c412017f-2ffb-4616-bfe4-7b1ce2a60449.png)

**Comment by annando** [comment]
Should be fixed by https://github.com/friendica/friendica/pull/12446
