### ISSUE TITLE
Post attachments aren't updated when a post is edited

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12415]
This issue concerns both [Friendica posts being updated](https://friendica.xyz/display/adf174d5-7963-99d9-b212-26d183842917) and [remote posts being updated](https://github.com/friendica/friendica/issues/12414#issuecomment-1351545250).

The list of attachment is kept between based on the first version and is never updated based on the new post body (local)/attachments (remote).

**Comment by MarekBenjamin** [comment]
Is it related to: https://github.com/friendica/friendica/issues/12403 ?

**Comment by MrPetovan** [comment]
Only loosely.
