### ISSUE TITLE
[FRIO] Spacing of Admin Addon site too large

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12411]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
The spacing between the addon descriptions is broken. The administration of the addon under /admin/addons is limited. See screenshot

### Screenshots
![2022-12-14_08-06](https://user-images.githubusercontent.com/44441246/207529086-e73073b1-6c64-48a7-aa96-4622ba4c4d9c.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment]
Probably also caused by https://github.com/friendica/friendica/pull/12196
