### ISSUE TITLE
[twitter] Messages relayed to Twitter are truncated

### ISSUE THREAD

**Issue by kalon33** [friendica/friendica#12417]
- [X] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Send a message longer than a tweet in Friendica, with a new line between two paragraphs.
2.  Observe that the corresponding message in Twitter is truncated, even if you have activated the "thread" option

Actual Result:
https://social.badabam.net/display/0d6f7d4a-1663-99e3-c45b-ea6874891494

https://twitter.com/kalonbuntu33/status/1603040883565264903?t=AAZWwAuEYI56sI1PaLcDew&s=19 (note that I manually added the second message in the thread after the bug, it was not generated by Friendica add-on)

Expected Result:

The thread should be complete.

### Platform Info

Friendica Version: 2022-10

Friendica Source: last release from official website.

PHP version: 8.1

SQL version: Not related.

**Comment by annando** [comment]
I can't reproduce this on the current RC.

**Comment by schmaker** [comment]
Obsolete
