### ISSUE TITLE
Sending images to a group. Images are set to private and are not displayed

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12412]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

Sending images to a group. Images are set to private and are not displayed

It has already been noticed elsewhere that all images uploaded to Friendica are only visible to a limited extent. Even if the upload of new images should be done with the right "public", the image rights are set to "private". As if by magic, the image right is changed for a public contribution and it is visible.

But if a post is sent to a group, the image right remains unchanged. The images can not be accessed.

The same behavior when using Tusky and fedilab

### Steps to Reproduce

1. Upload pictures to Friendica
Right public
2. Embed and 
3. send images in post

Actual Result:
The images are hidden from other accounts

Expected Result:
The images are shown to other accounts

### Screenshots

https://loma.ml/display/373ebf56-1963-99c9-9531-76a320456998
Image rights subsequently changed to public
![2022-12-14_14-34_1](https://user-images.githubusercontent.com/44441246/207609123-6b515093-4658-4d7e-bd39-6a48da8b8163.png)
![2022-12-14_14-34](https://user-images.githubusercontent.com/44441246/207609352-d38d7ab5-18b1-4da4-8ddc-fe915d027e81.png)
![2022-12-14_14-35](https://user-images.githubusercontent.com/44441246/207609375-dda59438-d3af-4487-bc52-e2e9976bffc5.png)

https://loma.ml/display/373ebf56-8563-99cc-6774-aaa022906843
![2022-12-14_14-37](https://user-images.githubusercontent.com/44441246/207609689-9ecb0790-7bbe-4e41-883d-42f0f9a99dea.png)

![2022-12-14_14-37_1](https://user-images.githubusercontent.com/44441246/207609703-eddb7ab8-4142-455c-9073-fec5d4ff5c1c.png)

![2022-12-14_14-40](https://user-images.githubusercontent.com/44441246/207610466-c1bc9b79-35ef-49f6-a0cd-1d4fe1ff88da.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MarekBenjamin** [comment]
Important issue. I actually stopped trying to share images to followers only. Thus, I do not post any image which could be in some kind not suited for worldwide publicity. That, in return, limit the usage fun of drastically. I mean, I want to convince real life contacts to use friendica by telling them: Follow me, and then you can see images which I like to share with people I know like you. :-)

**Comment by MarekBenjamin** [comment]
Is it actually access rights issue or a path problem? I am wondering, since the return code is 404 (not found) and not 403 (forbidden) 

>  "GET /photo/1752100520639b4b6e838d6613626033-0.jpg HTTP/2.0" 404

**Comment by MrPetovan** [comment]
Don't trust the response code too much, they have not been accurate everywhere.

**Comment by MarekBenjamin** [comment]
OK! :-)

**Comment by MarekBenjamin** [comment]
Is anyone engaged on that issue or might give me a hint where I can start looking at it. I would love to fix it since in opinion it is quite severe for usability. At the very moment I have zero clue about permissions, but I am willing to learn and fix :)

**Comment by annando** [comment]
"somewhere" in the code we have got a routine that adjusts the permissions of pictures. I have an idea how this could be fixed.

**Comment by MarekBenjamin** [comment]
Hi @annando that is great news, since whenever "you have an idea how it could be fixed" something wonderful is happening in a short time. 👼

**Comment by annando** [comment]
I'm still at work and additionally I hove got some other PR open, so it will take more than some minutes.

**Comment by MarekBenjamin** [comment]
Should I start looking for a fix somewhere around here?:

https://github.com/friendica/friendica/blob/abd3b2180fee672a4f9c3b31446be96c53b3d02d/src/Model/Photo.php#L156-L174
