### ISSUE TITLE
Remove legacy schemes from Settings > Display > Theme customization > Color Scheme (Blue, Koyu-dark, Love-music, Plusminus, Red)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12420]
One aspect making user interaction with themes very hard is the overwhelming amount of schemes which are mostly not used.

The legacy schemes are not maintained or tested against. Removing them will help making theme settings more usable.

![1](https://user-images.githubusercontent.com/5708172/207734792-9e36aac3-3ef4-4afa-8b93-808e4ab0ff62.png)

**Comment by MrPetovan** [comment]
I've very favorable to their removal, I'm just not sure what would happens to users who selected them when we remove them.

**Comment by foss-** [comment]
I think a transition UI with wizard to switch to another theme is out of scope so probably switching them to frio light and showing a notification, informing about the change (can we link to a blog post covering that switch?) may work?

**Comment by tobiasd** [comment]
What we did before when removing a theme was to remove it from the  interface and notify the users about the removal of the theme, so they could adopt their settings. Then with the next version the theme was actual removed from the code.

Providing some information how to re-implement the color settings of the legacy themes with the current ones might do the trick for the transition period.

**Comment by loma-one** [comment]
What happens to the legacy themes that are created by the admin for the instance and used by default? Will they continue to work?

**Comment by MrPetovan** [comment]
There are two different concepts: theme and scheme. A scheme is just a color palette of a given theme. Did you create a custom theme or did you create a custom scheme for your node's default display?

**Comment by SpcCw** [comment]
I have a custom frio scheme which is listed in "legacy" section. It worked just fine so far, I noticed no regressions whatsoever. Will it still work? It is not just basic colors changed but includes some other styling tweaks.

I am fine with removing preinstalled legacy schemes however I like the idea of having custom scheme which admin can set for their node. Can we keep these legacy schemes optional - i.e. if they are present in the directory then they show up available for selection?

**Comment by MrPetovan** [comment]
Unfortunately not. Custom schemes are still supported through custom values. These values can be shared between users using the schemestrings:
<img width="636" alt="image" src="https://github.com/friendica/friendica/assets/925415/3850b488-01c7-44c2-b737-032665d1c719">

But the list of available Frio schemes is now static.

**Comment by SpcCw** [comment]
It is a pity. I don't know how many instances use custom or legacy themes but I really liked the ability to customize the look a little more than just three basic colors. For example currently "custom" theme is forcing weird light blue background for new notifications which doesn't match many palettes at all. The ability to make various CSS tweaks also is priceless, e.g. I have more compact notification panel which allows to see more notifications at once without having to scroll.

I appreciate your great work however I wish this was discussed with the community more. Look and feel matters and many view their social presence as something very personal.

**Comment by MrPetovan** [comment]
I've also been made aware of @tiotrom 's custom scheme for their own node and so I will reinstate custom schemes. I didn't expect to encounter the question of custom schemes when I started working on this issue and I made a quick decision to be able to go forward with the changes.

**Comment by tio-trom** [comment]
> I've also been made aware of @tiotrom 's custom scheme for their own node and so I will reinstate custom schemes. I didn't expect to encounter the question of custom schemes when I started working on this issue and I made a quick decision to be able to go forward with the changes.

Thank you! I plan to also share the custom themes we made directly with the Friendica devs so maybe we can add some to the default Friendica installation. I should work on this the following weeks. It was on my to-do list for a long time. I think that creating custom themes is really useful.
