### ISSUE TITLE
[frio] Calling a forum leads to the contact and not to the content

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12431]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
If a forum is called up via the side navigation, only one contact is displayed.

### Steps to Reproduce

1.  Aufruf /network
2.  Call any forum

Actual Result:

The contact of the subscribed forum is displayed

Expected Result:

List of content written in the forum

### Screenshots
![2022-12-15_09-56](https://user-images.githubusercontent.com/44441246/207817091-954e44af-1e46-4719-ab93-b1af01bc4056.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment]
What is the URL of the forum link you selected?

**Comment by AlfredSK** [comment]
It happens when you follow the link to the forum in the 'forums' widget. The URL (an example from my node) is: https://libranet.de/network/forum/2047239

**Comment by AlfredSK** [comment]
Btw. when I scroll down the posts of that forum are displayed. Not sure why that "card" with the contact shows up above the posts.

**Comment by MrPetovan** [comment]
Oh, I know what this is. It was probably always there, hidden behind a CSS rule on frio, but I recently added the frame element on the contact lists and now the selector doesn't work. Oh, the simple joy of regression in what was already an exception case. 🙏
