### ISSUE TITLE
DB Error: Table 'friendicadb.advancedcontentfilter_rules' doesn't exist

### ISSUE THREAD

**Issue by roerch** [friendica/friendica#12437]
- [X] I have searched open and closed issues for duplicates

### Bug Description

From the error log:
```
code: 1146
error: Table 'friendicadb.advancedcontentfilter_rules' doesn't exist
```

Just upgraded from 2022-10 to 2022-12rc. Upgrade itself went without problems, as far as I can tell.
In 2022-10 the advancedcontentfilter addon was not working, so I wanted to give it a try now. But somehow the table is not created/existing in the database. Don't know whether it should have been created already at 2022-10 (addon just delivered blank page). Checking the database structure says that Database structure update 1501 was successfully applied.

### Steps to Reproduce

Probably corner case, so difficult to say.

### Platform Info

Friendica Version: 2022.12-rc - 1501

Friendica Source: Github

PHP version: 7.4.33

SQL version: 10.5.15-MariaDB-0+deb11u1 Raspbian 11

**Comment by MrPetovan** [comment]
The addon is supposed to add its own table to the structure when it's enabled, please try disabling it/enabling it manually from the admin panel.

**Comment by roerch** [comment]
Did this already several times, but also just did it right now and it didn't add the table to the database. The logfile doesn't show any error either at the time of trying.

**Comment by MrPetovan** [comment]
With the addon activated, please run `bin/console dbstructure update -f` from the command line in your Friendica folder.

**Comment by roerch** [comment]
Did this now, but no obvious success. I do not get any error message from the dbstructure update, however still DB Error in Friendica logs, i.e.:
```
Executable: /usr/src/friendica/bin/console.php
Arguments: array (
  0 => 'dbstructure',
  1 => 'update',
)
Options: array (
  'f' => 1,
  'v' => 1,
)
Command: dbstructure
Class: Friendica\Console\DatabaseStructure
Arguments: array (
  0 => 'update',
)
Options: array (
  'f' => 1,
  'v' => 1,
)
```

But also the table does not show up:
```
+---------------------------+
| Tables_in_friendicadb     |
+---------------------------+
| 2fa_app_specific_password |
| 2fa_recovery_codes        |
| 2fa_trusted_browser       |
| account-suggestion        |
| account-user              |
| account-user-view         |
| account-view              |
| addon                     |
| apcontact                 |
| application               |
| application-marker        |
| application-token         |
| application-view          |
| arrived-activity          |
| attach                    |
| cache                     |
[...]
```
And output from addon table (just to confirm):
```
MariaDB [friendicadb]> select * from addon;
+----+-----------------------+---------+-----------+--------+------------+--------------+
| id | name                  | version | installed | hidden | timestamp  | plugin_admin |
+----+-----------------------+---------+-----------+--------+------------+--------------+
| 10 | fancybox              |         |         1 |      0 | 1671181732 |            0 |
| 12 | openstreetmap         |         |         1 |      0 | 1671181732 |            1 |
| 13 | markdown              |         |         1 |      0 | 1671181732 |            0 |
| 14 | nitter                |         |         1 |      0 | 1671181732 |            1 |
| 15 | phpmailer             |         |         1 |      0 | 1671181732 |            0 |
| 23 | advancedcontentfilter |         |         1 |      0 | 1671181732 |            0 |
+----+-----------------------+---------+-----------+--------+------------+--------------+
```

**Comment by MrPetovan** [comment]
Hmm, I'm slowly running out of ideas. Can you please check the `hook` table for `` `hook` = 'dbstructure_definition'`` rows?

**Comment by roerch** [comment]
Pasting the relevant rows, but looks like it contains what's needed.
```
+----+-----------------------------+-------------------------------------------------------+---------------------------------------------------+----------+
| id | hook                        | file                                                  | function                                          | priority |
+----+-----------------------------+-------------------------------------------------------+---------------------------------------------------+----------+

| 75 | dbstructure_definition      | addon/advancedcontentfilter/advancedcontentfilter.php | advancedcontentfilter_dbstructure_definition      |        0 |
| 76 | prepare_body_content_filter | addon/advancedcontentfilter/advancedcontentfilter.php | advancedcontentfilter_prepare_body_content_filter |        0 |
| 77 | addon_settings              | addon/advancedcontentfilter/advancedcontentfilter.php | advancedcontentfilter_addon_settings              |        0 |

```

**Comment by MrPetovan** [comment]
It does, and this makes your issue extremely puzzling at the moment. You can of course create this table yourself based on the output of `bin/console dbstructure dumpsql` where the `advancedcontentfilter_rules` table should appear. If it doesn't, then there's something seriously wrong.

**Comment by roerch** [comment]
Ehm, I don't dare to say it, but the output of dumpsql does not contain anything about the ```advancedcontentfilter_rules``` table. Which is at least consequent behaviour.
```
sudo -u www-data bin/console dbstructure dumpsql | grep rules
```
has empty output.

**Comment by MrPetovan** [comment]
It is consistent but it isn't what I'd like to see 😭

At least now I think I have a good idea of why it isn't working anymore. It seems to be related to @nupplaphil 's recent changes in the way the DB structure definition is loaded in a910fd8864f5f1e9c35e9065abad24353793f313

Long story short, the addon-supplied definitions aren't loaded anymore at any point in the app, which explains your error. And it wouldn't affect servers that had enabled the addon before the latest RC version.

**Comment by roerch** [comment]
thanks a lot, so it is not me getting crazy here. Let me know if you need further help debugging or if I should try something.

**Comment by MrPetovan** [comment]
I need @nupplaphil 's input first before I change anything. He must have had a good idea why he made these changes so I don't want to topple his card castle.

**Comment by nupplaphil** [comment]
ups .. Fixed with #12443 :-)

**Comment by MrPetovan** [comment]
@roerch Please pull the latest `2022.12-rc` branch, it should have fixed the issue and you should be able to disable/enable the addon one last time.

**Comment by roerch** [comment]
done and done. Table is now created after activating the addon.
```
+-----------------------------+
| Tables_in_friendicadb       |
+-----------------------------+
| 2fa_app_specific_password   |
| 2fa_recovery_codes          |
| 2fa_trusted_browser         |
| account-suggestion          |
| account-user                |
| account-user-view           |
| account-view                |
| addon                       |
| advancedcontentfilter_rules |
```
Thanks a lot for the wonderful support
