### ISSUE TITLE
When viewing other profile's contacts, links take you the contact url, rather than the contact's profile. No follow button

### ISSUE THREAD

**Issue by dpoulson** [friendica/friendica#12441]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

If you view the profile of a user on your server, and go to their contacts, the links shown are the links to that user's contact url. There is no follow button either, it is an unfollow button.

This makes finding more people to follow a pain. I would like to look through the contacts of people I follow to find more people to follow and just click on their image to view their profile, or directly follow them with a follow icon. Currently the only way to do this is to copy/paste their activitypub id into the search box.

### Steps to Reproduce

1.  Click on a profile of someone you're following on the same server as you.
2.  View their contacts
3.  Click on the user's image or name
4.  Get a contact not found page

Actual Result:

Clicking on a contact of someone you follow on your server gives contact not found and the last icon is to unfollow.

Expected Result:

You should get taken to that persons profile page (on a remote server). Clicking on the follow icon should follow that person

### Screenshots

![Screenshot_2022-12-16_15-21-22](https://user-images.githubusercontent.com/601921/208130347-002455f8-e079-4868-a458-6b3a58ffd9ae.png)
![Screenshot_2022-12-16_15-21-08](https://user-images.githubusercontent.com/601921/208130350-fe4a92b3-0ffb-4bf3-a464-fd384604f8c2.png)

### Platform Info

Friendica Version:

2022.12-rc  ( f84e76d8937258db5ace4617bc39f247c53b1a62 )

Friendica Source:  git

PHP version: 8.0

SQL version: 10.2.44-MariaDB (DB Update 1501)

**Comment by MrPetovan** [comment]
Thank you for the report, however just based on the information provided, I can't reproduce the issue. Can you elaborate on the following points:
- What is the account you're logged in as.
- Whether you have enabled "Stay Local" in Settings -> Display -> Content/Layout
- What is the page you're seeing the "Unfollow" button.
- What page is showing `/contact/xxxxx` URLs that result in a Page Not Found error.

**Comment by dpoulson** [comment]
I am logged into a local account on this server. (darrenp@myserver) 

I go to one of my contacts (dpoulson@myserver) and view their profile (/profile/dpoulson) 

If I click on the contacts tab for that profile (not my contacts tab), I get a list of all their followers or people they're following.

This page is showing the /contact/xxxxx urls, along with the unfollow link. I would expect this page to link me to the persons actual profile page (local or remote), and for a follow icon to be available for a quick follow. (The url is /profile/dpoulson/contacts). 

If it is someone I already follow (eg, both accounts follow George Takei), the /contact/xxxx link gives me a valid page with a link to the persons external profile.

Clicking the unfollow link eventually takes me to my contacts page (/contact) and a popup message saying "You aren't following this contact". 

An example unfollow link is:

https://myserver/contact/unfollow?url=https%3A%2F%2Fmastodonapp.uk%2Fusers%2Ffanthatracks&auto=1

Same behaviour if I have 'Stay Local' set or not.

**Comment by dpoulson** [comment]
As an added note, if I visit /profile/dpoulson/contacts as an unauthenticated user, then the behaviour is as I would expect. Clicking a name takes me to the persons profile.

**Comment by MrPetovan** [comment]
Thank for the elaboration!
