### ISSUE TITLE
Homepage URL pointing to Mastodon profiles is shown incorrectly (because of @ character?)

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#12452]
If I try to specify Mastodon profile link in homepage section of the profile it gets broken starting with `@` character.

E.g.
`https://lor.sh/@shuro` is shown as:
![image](https://user-images.githubusercontent.com/35988439/208248651-0b83c670-58d8-45bb-b1f4-14f70b4adf63.png)

At the same time if such link is specified as an additional profile field then it is shown properly. However it would be nice for people to be able to use verification feature.

Also homepage link should be shown with `rel=me` attribute for the same reason.

UPD: Funkwhale also has similar format for profile URLs.

**Comment by MrPetovan** [comment]
I believe our URL matching regular expression doesn't match on `@` past the domain part. I believe it should be URL-encoded but browsers are lenient about it.

**Comment by MrPetovan** [comment]
I can't reproduce this issue, setting the same URL in the Homepage field of my profile results in a complete link:
![friendica-homepage-link-at-sign](https://user-images.githubusercontent.com/925415/208280778-4e1f440a-1b79-428b-9fb4-ae31c445c746.png)

> Also homepage link should be shown with `rel=me` attribute for the same reason.

Yes, this is a good idea.

**Comment by SpcCw** [comment]
I rechecked and see that the link is displayed okay in the left column under avatar but is broken on the page `/profile/username/profile` specifically for the `homepage` field:

![image](https://user-images.githubusercontent.com/35988439/208286195-3aa02b74-55a3-4be5-9598-fa38e7cf444c.png)

> Also homepage link should be shown with rel=me attribute for the same reason.

After some thinking it seems nice to have `rel=me` attribute added to custom profile fields too, not just homepage. People might have multiple accounts or prefer have their actual homepage listed as their homepage and their social accounts listed with custom label.

**Comment by MrPetovan** [comment]
So custom profile fields, got it.

**Comment by MrPetovan** [comment]
I checked and the Homepage URL in the VCard in the left column already has a `rel="me"` attribute! 🎉
