### ISSUE TITLE
Blank row rules on /tos

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12456]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

The representation of instance roles on /tos starts at rule 2 instead of rule 1

Expected Result:

The rules should start with the 1 instead of the 2 line 

### Screenshots

![2022-12-17_18-37](https://user-images.githubusercontent.com/44441246/208254709-d014f91d-6275-4fd1-bb22-b8163af161e4.png)

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment]
Please pull the latest `2022.12-rc` branch and report back on the issue. I couldn't reproduce this unless I had an empty line at the start of the rules text, so we're now trimming whitespaces to avoid blank lines like this.

**Comment by loma-one** [comment]
- Rules removed
- saved
![Screenshot 2022-12-18 at 08-24-36 Dis le moi! Admin](https://user-images.githubusercontent.com/44441246/208286574-fe673a10-4b9d-4120-b449-ef60029459d8.png)

- checked: no rules in the display
![Screenshot 2022-12-18 at 08-29-39 Dis le moi! Tos](https://user-images.githubusercontent.com/44441246/208286623-5597a884-fe7c-4c53-9b90-b1a48ad2e1b9.png)

- Rules reset
![Screenshot 2022-12-18 at 08-25-27 Dis le moi! Admin](https://user-images.githubusercontent.com/44441246/208286596-c136cfbc-75ae-4ce4-ae94-e071939e4f18.png)

- rules tos output
![Screenshot 2022-12-18 at 08-25-52 Dis le moi! Tos](https://user-images.githubusercontent.com/44441246/208286601-0122027c-a232-4855-9eee-69b3abfe9620.png)

- Rules api 
![Screenshot 2022-12-18 at 08-26-18 https __loma ml](https://user-images.githubusercontent.com/44441246/208286604-2a13d62e-720c-43fa-80f4-c08f737f6fc9.png)
