### ISSUE TITLE
Print BBCode via [code][/code] does not work when normal bbcode follows

### ISSUE THREAD

**Issue by MarekBenjamin** [friendica/friendica#12468]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I put a bbcode "code" block to print some bbcode for showing / helping others the usage it is not printed when "active" bbcode follows. e.g.;

```
You can add a description for images in this way:

[code][img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img][/code]

[img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img]

```

See here: https://friendica-dev.mbbit.de/display/fa8fe840-1363-9f65-8de8-58f293435798

### Steps to Reproduce

1. Create a post with [code]"bbcode elements you want to show"[/code], e.g. [code][img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img][/code]
2.  Put the inner bbcode from the [code] block right beneath it, e.g. [img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img]

Actual Result:

No red monospaced code is printed, it is just omitted. 

Expected Result:

Output of `[code][img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img][/code]`
as
`[img=https://friendica.mbbit.de/photo/1866409891639f5e76ad883251047508]Test[/img]`

### Screenshots

https://friendica-dev.mbbit.de/display/fa8fe840-1963-9f65-fe41-68c667135857

### Platform Info

Friendica Version:

Friendica Version: 2022.12-rc

Friendica Source: https://github.com/friendica/friendica/commit/e73ef3e925132913c6f8fcb78a8b4c9fe50b5c75

PHP version: 7.4

SQL version: mysql Ver 15.1 Distrib 10.6.11-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapper

**Comment by MrPetovan** [comment]
Oh, fun, the image removal method must be a little greedy.
