### ISSUE TITLE
[Frio] Focus on album navigation tab "Pictures" > profile/user/photos 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12466]
### Describe the feature you'd like

Images can be structured in different albums. However, navigating between the albums is cumbersome because the album folders are always arranged below the profile information.
However, this proline information is not relevant there and can be removed.
Instead, the album folders should be placed there.

This happens in the same way already today in the "Calendar" tab
![2022-12-18_17-22](https://user-images.githubusercontent.com/44441246/208308891-469521eb-ccec-42f6-989a-e696ca19eb10.png)

![2022-12-18_17-23](https://user-images.githubusercontent.com/44441246/208308894-8b8a2809-907f-499e-8192-9347d59d51d6.png)

**Comment by MrPetovan** [comment]
We can remove the profile information for yourself, but we need to keep it for anyone else. We can remove the contact list though. Still, I wonder who would add so many pictures to their profile so that it would take that much vertical space? 🤔

**Comment by tobiasd** [comment]
> Still, I wonder who would add so many pictures to their profile so that it would take that much vertical space?

And if they do, it is their choice I'd say, leading to some inconveniences.
