### ISSUE TITLE
 Blank row rules on /tos #12456 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12462]
https://github.com/friendica/friendica/issues/12456

The changes from Git were put in this morning before I did the testing. 2022.12-rc - 1502

- Rules removed
- saved
![Screenshot 2022-12-18 at 08-24-36 Dis le moi! Admin](https://user-images.githubusercontent.com/44441246/208286574-fe673a10-4b9d-4120-b449-ef60029459d8.png)

- checked: no rules in the display
![Screenshot 2022-12-18 at 08-29-39 Dis le moi! Tos](https://user-images.githubusercontent.com/44441246/208286623-5597a884-fe7c-4c53-9b90-b1a48ad2e1b9.png)

- Rules reset
![Screenshot 2022-12-18 at 08-25-27 Dis le moi! Admin](https://user-images.githubusercontent.com/44441246/208286596-c136cfbc-75ae-4ce4-ae94-e071939e4f18.png)

- rules tos output
![Screenshot 2022-12-18 at 08-25-52 Dis le moi! Tos](https://user-images.githubusercontent.com/44441246/208286601-0122027c-a232-4855-9eee-69b3abfe9620.png)

- Rules api 
![Screenshot 2022-12-18 at 08-26-18 https __loma ml](https://user-images.githubusercontent.com/44441246/208286604-2a13d62e-720c-43fa-80f4-c08f737f6fc9.png)

https://loma.ml/tos

**Comment by MrPetovan** [comment]
Thank you, the TOS page and the API endpoint use a different system to retrieve the rules, because the TOS page can show HTML in the rules through BBCode tags, whereas the API output needs to be plaintext. I'll look into this.

**Comment by MrPetovan** [comment]
I'm not able to reach https://loma.ml/tos at the moment (Timeout), can you please paste here your rules so that I can use the same data as I'm not able to reproduce this behavior with any text I could come up with?
