### ISSUE TITLE
Language settings is a setting, so they should be in settings

### ISSUE THREAD

**Issue by DNS777** [friendica/friendica#1249]
I suggest to put the language settings under the settings menu, because i expect to find any settings in the settings menu.
Also it could be found like that in any theme, without searchin for a good place for the dropdown menu (like in vier theme).

**Comment by Beanow** [comment]
:+1: The strange hidden drop-downs in themes has always been confusing to me.

**Comment by silke** [comment]
DNS777, do you mean the "system language" setting in the admin settings (/admin/site)?? Or is there a different place that I just can't find? :p

**Comment by annando** [comment]
@silke There is the possibility to switch the current page language. This option is theme dependent and not possible with "vier".

**Comment by silke** [comment]
Postponing this as it's related to developing the new future super theme that takes the UX issues into account.
