### ISSUE TITLE
Worker not handling jobs with php 8.1

### ISSUE THREAD

**Issue by pvagner** [friendica/friendica#12499]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

I am using friendica by irregularly pulling from the develop branch. Since 16th of december my worker stopped handling tasks from its queue.
I have tried running both worker.php through the systemd timer unit as well as the daemon.php by using php 8.1.
I was unable to figure out what's wrong thus by trial and error I have started the daemon with php 7.4 and everything started to work.
So currently I am using php-fpm 8.1 to run the web frontend and php 7.4 to run the daemon.

### Steps to Reproduce

1.  Install php 8.1
2.  Run worker or daemon
3.  Observe no errors and exit status 0 and worker queue is increasing

Actual Result:

Expected Result:

The worker should run with no errors but queue jobs should be executing.

### Platform Info

Friendica Version: 2022.12

Friendica Source: git develop branch

PHP version: 8.1 / 7.4 as explained in the text

SQL version: Mariadb 10.9.4

**Comment by annando** [comment]
There has to be something in the logs that indicate an error or warning.

**Comment by AlfredSK** [comment]
I'm running our community forum node on PHP 8.1. The worker works fine here with Friendica 2022.12. Maybe some configuration issue?

**Comment by utzer** [comment]
This somehow looks like what I experience, but I am not sure, I have PHP 8.2 and the queue just goes up since 2 weeks. Now it is `8971 - 535428` and I think it goes up a few ten thousand each day. 

I wonder what is the reason. 

I can see jpm peak at 1000 jobs per minute, averaging on 300 jpm or so. This looks pretty much as always. Also there is no new users in the last weeks. 

In the Friendica log I have a lot of depreciated notices. The jpm look really ok, see below. Is it possible that there is many tasks that can not be finished and therefor it clogs up the queue? How can I find out what is the problem? 
```
2023-02-21T04:42:56Z worker [INFO]: Load: 3.67578125/12 - processes: 8116/9/535702 - jpm: 325/446/345 (0:0, 30:0/2, 40:7/543312, 50:2/504) - maximum: 9/25 {"worker_id":"9a65004","worker_cmd":"Notifier"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bb85ca9f","uid":"f6b659","process_id":2119858}
2023-02-21T04:42:57Z worker [INFO]: Load: 3.67578125/12 - processes: 8116/9/535714 - jpm: 325/445/345 (0:0, 30:0/2, 40:7/543324, 50:2/504) - maximum: 9/25 {"worker_id":"9a65004","worker_cmd":"Notifier"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bb85ca9f","uid":"f6b659","process_id":2119858}
2023-02-21T04:42:57Z worker [INFO]: Load: 3.67578125/12 - processes: 8115/9/535715 - jpm: 326/445/345 (0:1, 30:0/2, 40:6/543325, 50:2/503) - maximum: 9/25 {"worker_id":"9a65004","worker_cmd":"Notifier"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bb85ca9f","uid":"f6b659","process_id":2119858}
2023-02-21T04:42:57Z worker [INFO]: Load: 3.67578125/12 - processes: 8115/9/535723 - jpm: 328/445/345 (0:1, 30:0/2, 40:7/543333, 50:1/503) - maximum: 9/25 {"worker_id":"9eafed0","worker_cmd":"UpdateContact"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bc1c8388","uid":"cb741a","process_id":2119883}
2023-02-21T04:42:57Z worker [INFO]: Load: 3.67578125/12 - processes: 8114/9/535729 - jpm: 330/445/345 (0:1, 30:0/2, 40:7/543339, 50:1/502) - maximum: 9/25 {"worker_id":"9a65004","worker_cmd":"Notifier"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bb85ca9f","uid":"f6b659","process_id":2119858}
2023-02-21T04:42:57Z worker [INFO]: Load: 3.67578125/12 - processes: 8111/9/535730 - jpm: 333/446/345 (0:0, 30:0/2, 40:7/543340, 50:2/499) - maximum: 9/25 {"worker_id":"9a65004","worker_cmd":"Notifier"} - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bb85ca9f","uid":"f6b659","process_id":2119858}
2023-02-21T04:42:59Z worker [INFO]: Load: 3.67578125/12 - processes: 8109/10/535707 - jpm: 355/446/345 (0:1, 30:0/2, 40:8/543318, 50:1/496) - maximum: 9/25 [] - {"file":"Worker.php","line":817,"function":"tooMuchWorkers","request-id":"63f44bd3aa59c","uid":"953043","process_id":2120058}
```

**Comment by MrPetovan** [comment]
If you are on develop, the reversal to the config table may have overwritten the changes you made to your blocklist, possibly including `*.activitypub-troll.cf` like it did for me, triggering tens of thousands of server probe tasks shooting up my load and adding a million garbage gserver records.

**Comment by utzer** [comment]
I still see `*.activitypub-troll.cf` in my server block list, so this seems to be ok then?

**Comment by MrPetovan** [comment]
Yes, I would check the list of pending worker tasks just to be sure.

**Comment by utzer** [comment]
> Yes, I would check the list of pending worker tasks just to be sure.

I searched in the list for "activitypub-troll" and "forkbomb", which showed no results in the first page with 999 entries, the other pages can not be accessed I think. 
A grep in the friendica log for "fork" and for "activitypub-troll" did not return anything. So I guess that looks good then. 554000 tasks in the queue now. :-/

**Comment by HankG** [comment]
This may be OBE, I couldn't tell from the above convo, but I'm running the head of the develop branch with a worker setup as a daemon process and I do not seem to be having problems with workers crunching through the work queue.

**Comment by pvagner** [comment]
I have updated both friendica to the head of the develop branch and php to version 8.2.3 and all is back to normal with my instance. So that must have been something on my side I was unable to troubleshoot properly at that time.

**Comment by utzer** [comment]
Here it is going up more and more, now `7690 - 579736` and new is that mariadb is causing real high load sometimes. mysqlcheck looks good, filesystem check also looks good. 

mytop shows nice numbers like this: 
![Screenshot_2023-02-22_18-09-45](https://user-images.githubusercontent.com/8361662/220603693-4eb88cab-cd5f-4add-877e-fe472a634158.png)

Not sure what too look for.

**Comment by MrPetovan** [comment]
Can you paste a screenshot of your worker task list, the full screen height if possible?

**Comment by HankG** [comment]
Also curious what the result of this query is to see what type of workers are assigned. 

```sql
select command, count(*) as processes FROM workerqueue WHERE done = 0 and pid != 0 GROUP BY command ORDER BY processes DESC;
```

**Comment by annando** [comment]
@utzer your system has got a lot of sleeping SQL processes. AFAIK there are SQL configurations that limit this.

**Comment by utzer** [comment]
> Also curious what the result of this query is to see what type of workers are assigned.

What does that mean "type of workers"? Here is the output for this query for the friendica database. 
```
+---------+-----------+
| command | processes |
+---------+-----------+
| Expire  |         1 |
+---------+-----------+
```

**Comment by utzer** [comment]
> Can you paste a screenshot of your worker task list, the full screen height if possible?

Full page is not possible Firefox screenshot crashes when I try. I will post one later, after breakfast.

**Comment by utzer** [comment]
> @utzer your system has got a lot of sleeping SQL processes. AFAIK there are SQL configurations that limit this.

yes, so Friendica PHP scripts running for long time and keeping the connection open. But it should not matter as I have not reached the max connections. 
Edit: I search the net before adding the below, it turns out this is application configuration part. 

But I added this to my config now:
```
		// delete_sleeping_processes (Boolean)
		// Periodically delete waiting database processes.
		'delete_sleeping_processes' => true,
```

**Comment by utzer** [comment]
Playing too much with settings trying to tweak the whole thing, I now got mariadb to be unresponsive without anything in the logs, just many queries running for 4000s and more. So it somehow dies but does not crash. 

I saw there is a maximum execution time for task in the worker queue that can be set in the friendica config, what is the default setting if this is not set at all?

**Comment by utzer** [comment]
This is while the database is not responding to shutdown and Friendica is not loading. 
![Screenshot_2023-02-23_11-01-51](https://user-images.githubusercontent.com/8361662/220818767-84665990-b701-4eb9-b167-b371a3ab0763.png)
![Screenshot_2023-02-23_11-01-33](https://user-images.githubusercontent.com/8361662/220818771-e903eef3-3da0-42ab-8e11-d80e3f5070c7.png)


Killing php-fpm will not stop those processes, I will not try to put this in the friendica config, maybe it does something.

```
		// worker_max_duration (Array)
		// Maximum runtime per priority. Worker processes that exceed this runtime will be terminated.
		'worker_max_duration' => [
			Friendica\Core\Worker::PRIORITY_CRITICAL   => 720,
			Friendica\Core\Worker::PRIORITY_HIGH       => 10,
			Friendica\Core\Worker::PRIORITY_MEDIUM     => 60,
			Friendica\Core\Worker::PRIORITY_LOW        => 180,
			Friendica\Core\Worker::PRIORITY_NEGLIGIBLE => 720
		],
```

Also what is this spool path for? I never set that anywhere. 

`
2023-02-23T04:23:54Z worker [WARNING]: Path does not exist {"directory":"/tmp/friendica.utzer.de/spool","user":"http","worker_id":"d7cc608","worker_cmd":"SpoolPost"} - {"file":"System.php","line":544,"function":"isDirectoryUsable","request-id":"63f6ea415e02b","uid":"304395","process_id":685227}`

**Comment by utzer** [comment]
At some point I had the idea that maybe the NVMEs were degraded, so I had them switched out against new ones, but that seems not to be the source. 
Now also my second server starts to have a growing queue, it is now `454 - 382416`, the other is now at `8232 - 647098`. 

No other reports till now I assume?

**Comment by AlfredSK** [comment]
I'm running ~~two~~ three nodes on PHP 8.1. The queues are pretty short. Something like 300 - 20.

Do you know what kind of tasks are piling up in the delivery queue?

**Comment by utzer** [comment]
That was the length of my queue all the time on 8.1, but with 8.2 it changed. On the first server with the problem it is mostly APDelivery, UpdateContact, Notifier and ContactDiscovery, first 999 jobs are all prio 40. The other server first 999 jobs are UpdateContact except for three ContactDiscovery jobs.
