### ISSUE TITLE
Editing a post created with Markdown using Markdown

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12495]
### Is the feature request related to a problem? Please describe.

Contributions can be created with Markdown, but they are stored in BBCode. It is difficult to re-edit a content afterwards. Usually posts look unsightly if they have to be reworked via BBcode.
### Describe the feature you'd like

A content created with Markdown should be able to be edited again with Markdown. 
In various other applications, you can say "Edit with Markdown" via a switch in the editor. This flag can possibly be used to tell the system how to hold the content in order to provide the users with a clean template to edit. 
If necessary, two versions are kept 
1. storage object for the system in BBCode (because this is the internal coding)
2. copy in user format (because the human coding expects this)

### Additional context

**Comment by gbraad** [comment]
I would prefer to completely disable bbcode, as for export purposes I prefer markdown.

**Comment by MrPetovan** [comment]
There are a few native features (abstract, attachment, shared post) we can’t do with Markdown so BBCodes can’t be disabled.

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/12842
