### ISSUE TITLE
If a person is quoted, they should always be informed about it

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12498]
### Describe the feature you'd like

If a content is quoted, the quoted person is currently not informed about it. 
The function has been misused several times on Twitter to direct follower streams. 
It should therefore be ensured that the use of content by quoting can still be controlled by the creator and, if necessary, the solution can be demanded.

If a quote is shared, it should be ensured that the person quoted always receives information about it. 
This enables them to comment on the quoted content themselves or to request the deletion of the quote.

### Additional context

**Comment by MrPetovan** [comment]
I am against this feature. Why would you want to be notified of potentially toxic quote posts? What are the chances the author would delete such a toxic quote post if the author requests it in the comments? It sounds like pouring oil on a fire.

**Comment by annando** [comment]
I've got the impression as if the original author is already added as receiver of that post. I think it is important to notify people about being quoted. At least then you are able to file a report if that was some toxic post.

**Comment by tobiasd** [comment]
We already have a setting in the Notification settings if "Someone shared your content", I would assume "quoted share" is *like shared* at least in the sense that, I want to get notified.

**Comment by loma-one** [comment]
@tobiasd If it includes citation, then the goal would be achieved. 
Perhaps this can be made more explicit in the description. Thanks a lot

**Comment by loma-one** [comment]
@tobiasd You're right. Sharing does indeed show up in the notifications.
That's why I'm closing the request. Sorry for the excitement.

**Comment by tobiasd** [comment]
I was not sure about it. But glad that it is :)

**Comment by loma-one** [comment]
I have now tried it again with two accounts that do not know each other, that have no existing connection.

- If a post is shared privately as a quote, there is no notification (this was to be expected).
- If the post is shared publicly as a quote, there is also no notification.

I think, at least in case 2 the quoted person should receive a notification that the post was shared.

The point is not to encourage toxic behavior, but to empower the quoted to continue to control their own content. Quoting is a great feature that does not exist on Mastodon, for example. This leads to the creation of sceenshots that are 
1. are not safe from manipulation
2. puts the quoted person in a powerless position
3. undermines the deletion of the own content

**Comment by MrPetovan** [comment]
For 3 specifically, quote shares will still show content that was deleted by its author because of local post caching. In general we do honor deletion messages but none would be sent for quote shares.

**Comment by annando** [comment]
Since the last release we don't cache the quoted post anymore. Means: When the original post is deleted and that deletion reached our server, then automatically it will be removed from the quoted share as well.

**Comment by MrPetovan** [comment]
I hear you, but would the quoted post server know to send a deletion message to the quoting post server? Additionally, I still see remnants of Mastodon delete & redraft posts, so the deletion isn't completely straightforward as far as I can see.

**Comment by loma-one** [comment]
It is not about deleting a quoted content. This must be done by the admin within the framework of moderation. It is only about informing the quoted that the post was shared as a quote.

A quote is strictly speaking also only a comment on a content. In the case of comments, the commented person is also informed.

**Comment by loma-one** [comment]
After it was announced that Mastodon wants to check quoting, I took another look at the behavior on Friendica

- The quoted person receives a notification (also Mastodon).
![Screenshot 2023-01-03 at 09-28-56 Μαθθίας_ξ ✔](https://user-images.githubusercontent.com/44441246/210375530-6e4f0529-23cc-4503-a761-8ee1c42caeda.png)

- A quoted content can be changed afterwards.
https://dis-le.de/display/50619573-2063-b3e7-2846-4ec653343460
![grafik](https://user-images.githubusercontent.com/44441246/210375288-701330e2-d2e4-4b0a-bc8b-d58a895a5ee3.png)

- The quoted content can be deleted at the origin server.
https://loma.ml/display/373ebf56-3863-b3e6-e3f0-028720225780
![grafik](https://user-images.githubusercontent.com/44441246/210375054-430dbc9c-2775-4cb9-bf20-486504b2baa1.png)

- **The deletion is not performed at the remote server.**

I'm not sure if a notification is always created when a quote is made. In my test cases with Friendica, there was always a connection between the user profiles. 
However, since a Mastodon user received a notification after being quoted via Friendica, I conclude that this notification always occurs.
