### ISSUE TITLE
:verified: in user names

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12497]
Many thanks to the developers for 2022.12. Great work.

I have a number of users I follow with icon in the username that are not shown on my instance, like _:verified:_ or _:mastodon:_.
How can I add those icons so they are shown in friendica and tusky?

**Comment by annando** [comment]
Currently this is not supported.

**Comment by MrPetovan** [comment]
Duplicate of https://github.com/friendica/friendica/issues/11991
