### ISSUE TITLE
Gridded image order breaks on mobile displays

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12506]
Cc @MarekBenjamin

With the separation in two columns, the image grid keeps the original image order on devices that can show these columns side-by-side, but it doesn't work as well on single-column devices.
```
1 | 2
3 | 4
```
becomes
```
1 |
3 |
2
4
```
For maximum responsiveness, we need a CSS solution that doesn't require intermediate HTML tags for columns. Rows would be fine though, and I encourage anyone to look into the flex model: https://developer.mozilla.org/en-US/docs/Web/CSS/flex

So instead of grouping pictures by columns, they would be grouped by rows, which would preserve their order on single-column devices.

**Comment by MarekBenjamin** [comment]
What is a single-column device?
I was asking myself about this back then, but it seemed that the column width never falls below a certain value. Thus, I assumed it will never collapse to one column only. In fact, we removed the "collapse to one column" during PR discussion if I remember right. 


Though, I clearly see the issue that the order should not be mixed in that case! 👼

**Comment by MrPetovan** [comment]
See desktop view:
![2022-12-22 13 17 45 friendica mrpetovan com cfc999937b35](https://user-images.githubusercontent.com/925415/209199978-64a30d2e-fe22-434c-84a1-631fdaf2f02a.jpg)

And mobile view:
![CFB47F04-9020-457D-8D34-E13F11A6A261](https://user-images.githubusercontent.com/925415/209200852-5df41471-91b0-441a-8d98-843f718cc70a.png)
![A24423FE-5240-4286-9B36-15819C203309](https://user-images.githubusercontent.com/925415/209200864-2dee5c6a-027a-42ba-8bb7-ec24b4e12543.png)
![774C1426-325A-41BB-937C-FD805B009121](https://user-images.githubusercontent.com/925415/209200859-4ec1127f-43de-4aea-a9ce-8a68db2b1f7c.png)
![AD3B5B05-8799-432D-910A-4EF46988CACC](https://user-images.githubusercontent.com/925415/209200871-2d202ddf-208a-4e92-aa08-0164ca9282c1.png)

**Comment by MarekBenjamin** [comment]
![Screenshot_20221222-192724_Firefox](https://user-images.githubusercontent.com/117765478/209202468-33138f7b-68f2-41c8-94fb-2a1d9fe1604c.png)

Perhaps my mobile's resolution is too high?

**Comment by MarekBenjamin** [comment]
The question is: Do we want to collapse to one column for a screen width < X px, or (as I thought) do we want to keep two columns in any case. Depending on this decision, I guess the way to fix it differs. :-)

**Comment by MrPetovan** [comment]
No, it shows the same way as you if I open the post in Safari. I believe it has to do with how I set up my Friendica as a single page application on iOS. It's also called "Add to Home Screen" and it is correctly identified as mobile display by Friendica. Since I don't have the regular browser decoration, I can't bring up any developer console in this mode so I'd be hard-pressed to tell you what's the fundamental difference with regard to the image grid. What I do know is that a fixed width column-based layout doesn't work and a fixed height row-based layout would be better.

**Comment by MarekBenjamin** [comment]
Still, the question remains for me not clearly answered: Do we need to a fall back to one column / one image per row and if yes, when?

I honestly do not 100% understand this "single column device" issue. 😄 Your suggestion is to use rows with two images side by side instead of first and second column, do I get this right?

**Comment by MrPetovan** [comment]
Yes, so that it would look like this on double -columns devices:
```
1 2
---
3 4
```
And on single-column devices:
```
1
2
-
3
4
```

**Comment by MarekBenjamin** [comment]
Now it is clear enough, so that I can take care of it soon, thanks! :-)

**Comment by MarekBenjamin** [comment]
@MrPetovan Do you have an idea how to balance different image heights using the proposed row approach? I expect the follwoing results when mixing landscape and portrait:

```
LLLLL    PPPPPP
LLLLL    PPPPPP
LLLLL    [GAP]
----------------
PPPPPP    LLLLL
PPPPPP    LLLLL
[GAP]     LLLLL 
```

How can we avoid the [GAP]? I currently have no clue how to avoid the [GAP] using `<div>` rows only? In the https://developer.mozilla.org/en-US/docs/Web/CSS/flex doc, I didn't find an approach to apply it to our use case, am I missing something? 

Obviously, we need something like this, i.e. "a non straight row border":

```
LLLLL    PPPPPP
LLLLL    PPPPPP
LLLLL  |------
-------| LLLLL
PPPPPP   LLLLL
PPPPPP   LLLLL 
  
```

**Comment by MrPetovan** [comment]
Ideally it would do this:
```
PP LLLLLLL
PP LLLLLLL
PP LLLLLLL
----------
LLLLLLL PP
LLLLLLL PP
LLLLLLL PP
```
But I've never seen a pure-CSS solution to this.

Additionally, the masonry libraries usually operates on columns, not on rows.

**Comment by MrPetovan** [comment]
Here's my result so far with https://friendica-dev.mbbit.de/display/fa8fe840-3163-9603-2ec9-2ca945358166:
![friendica-images-horizontal-masonry](https://user-images.githubusercontent.com/925415/209579549-00326c14-e635-4251-b2d6-ed0e5aeb1d30.png)
HTML:
```
<div class="body-attach">
    <div class="imagegrid-row">
        <a href="https://friendica-dev.mbbit.de/photo/5996092522639601c847e1e304503322-0.jpg" class="">
            <img src="https://friendica-dev.mbbit.de/photo/preview/600/383" alt="" title="">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/1636370823639601a2a81ba703786777-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/1024/387" alt="" title="">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/6772095815639601ea396c7970175259-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/1024/385" alt="" title="">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/1385634648639603184245f227265326-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/600/389" alt="" title="">
        </a>
    </div>
</div>
```
CSS:
```
.imagegrid-row {
    display: -ms-flexbox;
    display: flex;
    margin-top: 1em;
    column-gap: 5px;
    flex-wrap: wrap;
    row-gap: 5px;
}

.imagegrid-row a {
    flex: 1 0 auto;
}

.imagegrid-row a img {
    height: 300px;
}
```
I assume the good result comes from the symmetry of the picture orientation (PLLP) and the similar dimensions, I'll try different images combinations with the same CSS.

**Comment by MrPetovan** [comment]
Yeah, PPLL is less flattering:
![2022-12-26 14 56 40 friendica-dev mbbit de 266299397525](https://user-images.githubusercontent.com/925415/209580078-43812304-69d8-4352-9f13-0212c5871be6.png)

**Comment by MarekBenjamin** [comment]
Thank you very much for sharing the example code. It helps me a lot to understand the flex concept, even though it is not the final solution yet. At least it is a DIFFERENT problem than I expected. ;-) 

Now I guess we need some conclusion: 
1. Keep it the way it is, 
2. Sacrifice neat arrangement for preserving image order, or 
3. introduce scripting
4. ...?

**Comment by MrPetovan** [comment]
I reached this result by setting the individual height of each image:
![friendica-images-horizontal-masonry-PPLL](https://user-images.githubusercontent.com/925415/209580388-6ff2af1f-66a7-4697-a1a7-0465a149f2c1.png)
See HTML:
```
<div class="body-attach">
    <div class="imagegrid-row">
        <a href="https://friendica-dev.mbbit.de/photo/1636370823639601a2a81ba703786777-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/1024/387" alt="" title="" height="418">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/6772095815639601ea396c7970175259-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/1024/385" alt="" title="" height="418">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/1385634648639603184245f227265326-0.jpg">
            <img src="https://friendica-dev.mbbit.de/photo/preview/600/389" alt="" title="" height="235">
        </a>
        <a href="https://friendica-dev.mbbit.de/photo/5996092522639601c847e1e304503322-0.jpg" class="">
            <img src="https://friendica-dev.mbbit.de/photo/preview/600/383" alt="" title="" height="235">
        </a>
    </div>
</div>
```
This would require a partly-computed solution where each image would receive a specific height so that we can have at least 2 images per row.

Here's the cases I imagine with a total width including 5px gutter of 632px:
- PPP: 1 row
- PP or LL or PL or LP: 1 row

So the PHP code would have to group images per row, normalize their width so that they all have the same height, then compute the height of the grouped image based on the total normalized width and the image ratio.

Let's see if I can explain this process with three Portrait images of various aspect ratios:
```
Image 1:  600px /  800px
Image 2:  900px / 1600px
Image 3: 1000px / 1600px
```
```
Normalized widths to have the same height:
Image 1: 600px / 800px
Image 2: 450px / 800px
Image 3: 500px / 800px
```
Fitting all three images in a 632px-wide column (on frio), minus 2 x 5px for the gutters (total 622px):
```
Height: (<Full column width minus gutters> * <Image 1 normalized width> * <Image 1 height>) / (<Total normalized widths> * <Image 1 width>)
Height: (622 * 600 * 800)  / ((600 + 450 + 500) * 600) = 321.03px
```
With two images you would only have one gutter so 627px for the available column width.

The most complex operation of this is finding the normalized width. It's easy in this example but finding a generalized algorithm is a nice programming exercise.

**Comment by MrPetovan** [comment]
Example groupings, trying to avoid a single P on a row:
- PLP: PL / P (no choice)
- PPPP: PP / PP
- PPPPP : PPP / PP
- LPPP: L / PPP
- PPLPP: PP / L / PP
- LLLLP: L / LL / LP

Any image alone on its row doesn't have assigned height.

**Comment by MarekBenjamin** [comment]
> PPPPP : PPP / PP
LPPP: L / PPP

I guess we need a complete enumeration of possible arrangements, in respect to the attachment sequence, for the first three rows. 
Based on your exampled where you identified that we should distribute 5 images in up to three rows, each row containing up to three images we need the number of variations for arranging Ls and Ps in a 5-tuple, Which is ` 2**5 = 32` possible variants which need to be mapped to 2 - 3 rows, draft: 

```
L	L	L	L	L	--> LL / LL / L
L	L	L	L	P
L	L	L	P	L	--> L / LL / LP
L	L	L	P	P	--> LL / L / PPP (?)
L	L	P	L	L
L	L	P	L	P
L	L	P	P	L
L	L	P	P	P
L	P	L	L	L
L	P	L	L	P
L	P	L	P	L
L	P	L	P	P
L	P	P	L	L
L	P	P	L	P
L	P	P	P	L
L	P	P	P	P 	--> L / PP / PP
P	L	L	L	L
P	L	L	L	P
P	L	L	P	L
P	L	L	P	P
P	L	P	L	L
P	L	P	L	P
P	L	P	P	L
P	L	P	P	P
P	P	L	L	L
P	P	L	L	P
P	P	L	P	L
P	P	L	P	P
P	P	P	L	L
P	P	P	L	P
P	P	P	P	L
P	P	P	P	P	-->  PPP / PP
```

Maybe we need also consider 4 and 3 images seperately:

```
L	L	L	L
L	L	L	P
L	L	P	L
L	L	P	P
L	P	L	L
L	P	L	P
L	P	P	L
L	P	P	P
P	L	L	L
P	L	L	P
P	L	P	L
P	L	P	P
P	P	L	L
P	P	L	P
P	P	P	L
P	P	P	P
```

```
L	L	L
L	L	P
L	P	L
L	P	P
P	L	L
P	L	P
P	P	L
P	P	P
```

All higher number of rows, due to more images, could then be processed in an iterative / recursive manner.

**Comment by MrPetovan** [comment]
> `L	L	L	P	P	--> LL / L / PPP (?)`

That's one to many P 😄

This looks fine so far, but how do you deal with arbitrary number of images if you only account to up to 5 images?

**Comment by MarekBenjamin** [comment]
> but how do you deal with arbitrary number of images if you only account to up to 5 images?

By iteration, my idea is based on building your blocks for a group of up to five images as you have already laid out. There might be some special cases like the "PL / P" which need to be handled between two iteration for a seamless grid. But in theory, creating such blocks iteratively should flawlessly scale up.

**Comment by MrPetovan** [comment]
I can’t wait to review what you come up with!

**Comment by MarekBenjamin** [comment]
I'm just as excited as you are at the moment. Let's see what becomes of the theory in practice. Usually it will be different, but still good :-)
It really wouldn't be the first time a simple solution has surfaced after initially taking a complex approach.

**Comment by MarekBenjamin** [comment]
@MrPetovan : I just realized that we might already have everything at hand in the image gallery:

https://friendica-dev.mbbit.de/profile/friendicadev/photos

How is this gallery rendered on your "single column device"? :)

**Comment by MrPetovan** [comment]
The same way than in Safari:
![D6C5772E-B057-4D60-BC8A-E3F70F21A081](https://user-images.githubusercontent.com/925415/209696210-66028100-1192-4e44-8605-4f518e13adb9.png)
Probably because it’s a different domain from my Single Page App. Let me get a screenshot of my own gallery.

![41AB9BF8-52AD-4853-B2CF-0BBC625EBA80](https://user-images.githubusercontent.com/925415/209696444-50bd4ae0-38be-44ed-9ac2-9165ed905e0a.png)

**Comment by annando** [comment]
@MarekBenjamin in the album gallery we are using this JS function: `justifyPhotos();` I guess that there is some preparation needed to make it work - on the other hand the function seems to arrange the photos in a nice way.

**Comment by MrPetovan** [comment]
It seems to keep the picture order, while having variable height rows as we've been discussing here.

**Comment by MarekBenjamin** [comment]
And the price for using it is the js dependency, right?

**Comment by MarekBenjamin** [comment]
Did someone change anything on regarding the image preview generation? I was just playing around with image gallery as I saw that portraits are quashed in to landscapes, which looks awful, during my last days 2 to 3 weeks ago this never happened:

See, e.g.

https://friendica-dev.mbbit.de/display/fa8fe840-1863-ab4b-5219-e24583154924

and 

https://friendica-dev.mbbit.de/profile/friendicadev/photos

Is that a problem in my instance, or do I need to create an issue?

**Comment by MrPetovan** [comment]
It looks like you need to create an issue for this.

> And the price for using it is the js dependency, right?

The file is manually imported in the frio theme folder in `view/theme/frio/frameworks/justifiedGallery/jquery.justifiedGallery.min.js`

**Comment by MrPetovan** [comment]
This has now been done using CSS flex.
