### ISSUE TITLE
Unable to change 'Week starts' to Monday

### ISSUE THREAD

**Issue by gbraad** [friendica/friendica#12524]
- [x] I have searched open and closed issues for duplicates

### Bug Description

For the 'Vier' display settings I am unable to change the value of 'Week starts' 

### Steps to Reproduce

1.  https://host/settings/display
2.  Change "Week starts" to Monday
3.  Save settings

Actual Result:

Value stays on Sunday

Expected Result:

Expect value to show Monday

### Screenshots

N/A

### Platform Info

Friendica Version: 22.12

**Comment by MrPetovan** [comment]
Turns out it wasn't theme-specific, thank you for your report!

**Comment by gbraad** [comment]
Fixed by #12528
