### ISSUE TITLE
Typo found, in the help portion

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12522]
in /help/tools from the menu, under the fail2ban info. for 3rd party tools, there is a typo, that breaks fail2ban, if you just copy paste.
 
 In /etc/fail2ban/jail.local create a section for Friendica:
 
 -logpath = /var/log/friend.log
 +logpath = /var/log/friendica.log
 
 everything else, points to friendica.log

**Comment by tek-aevl** [comment]
Guess it was really that easy, lol `\.o./

**Comment by AlfredSK** [comment]
Sorry. That's based on my configuration and my log file is friend.log. 😊

**Comment by MrPetovan** [comment]
Thanks to @haheute for their help!

**Comment by tek-aevl** [comment]
I managed to figure it, out, but if someone wanted to copy paste it, like I did, it didn't work, and I realized why, and was like, oh, lol.
