### ISSUE TITLE
Friendica server not recognized by some Mastodon clients

### ISSUE THREAD

**Issue by FahimF** [friendica/friendica#12530]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Some Mastodon clients (my guess is specifically iOS/macOS clients using Swift) fail to detect current Friendica instances as valid instances due to the `contact_account` property in the returned response from the `/api/v1/instance` endpoint not being a dictionary. (My guess is the Swift code looks for a dictionary.)

The returned value for `contact_account` from other instances that do work with clients which successfully identify the instance as a Mastodon instance do have the value as a dictionary of values. See screenshot for an example.

### Steps to Reproduce

1.  Set up a Friendica server
2.  Use Mastonaut and try to add a user from the new server

Actual Result:
Mastonaut will not recognize the new Friendica server as a valid server

Expected Result:
Mastonaut should recognize the server as a valid server and allow me to add my user from that server.

### Screenshots

![CleanShot 2022-12-26 at 10 49 14@2x](https://user-images.githubusercontent.com/181110/209513951-ea19b8d0-ee5d-4548-a31a-71f7bdc5ab31.jpg)

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2022.12 - 1502

Friendica Source: 
friendica/src/Object/Api/Mastodon/Instance.php at line 100 has the following code:
`$this->contact_account   = [];`

I believe the above is what sets `contact_account` to an empty array. I'm not sure if setting this to an empty dictionary instead would fix the issue or not, but might be worth trying? If not, simply set that to the values from my screenshot above but change any PII to dummy values should fix the issue would be my guess.

PHP version: 8.0.26

SQL version:

**Comment by hanubeki** [comment]
I think `"urls": null` is also causing compatibility issue.
[fediverse_objects](https://github.com/Kaiteki-Fedi/fediverse_objects), a library used in [Kaiteki](https://github.com/Kaiteki-Fedi/Kaiteki) expects `urls` is `Map<String, dynamic>`, not null.

https://github.com/Kaiteki-Fedi/fediverse_objects/blob/master/lib/src/mastodon/instance.g.dart#L20

**Comment by annando** [comment]
@hanubeki we currently don't support the streaming API, so that there is no data. Question is how to handle this, so that no library has got issues with it.

**Comment by MrPetovan** [comment]
`urls` should be an empty array instead of `null`.

**Comment by annando** [comment]
No, this prevents other apps from recognizing a Friendica server, see this PR: https://github.com/friendica/friendica/pull/10243

**Comment by annando** [comment]
Concerning the issue with the `contact_account`: There should always be a value there, as long as the system is set up correctly. 

Also I think that we are doing it exactly like Mastodon:
![image](https://user-images.githubusercontent.com/844208/231281762-e8ea932a-5c51-454c-b464-db9a9d49dae8.png)

Friendica:
![image](https://user-images.githubusercontent.com/844208/231281858-fe12e60f-5fea-458e-b3ee-fe5755511a6e.png)

**Comment by MrPetovan** [comment]
Could it have to do with `contact_account` being a JSON list `[]` when empty but a JSON hash `{}` when full?

**Comment by annando** [comment]
`contact_account` shouldn't be empty at all. Every system should have got at least one admin.

**Comment by kr428** [comment]
Linking to https://github.com/Kaiteki-Fedi/Kaiteki/issues/376 (Kaiteki) and https://github.com/trunks-social/trunks-public/issues/156 (trunks): Both are relatively new Android Mastodon clients, both quite usable in what they do, and both have in common that even login to Friendica instances fails. Not sure if it's a problem on "their" or "our" end, but maybe there's something that can be done in Friendica Mastodon API implementation to improve this?

**Comment by annando** [comment]
Is this still an issue? If it is the case, then a list of failing apps would be great, since this doesn't appear being a general thing.

**Comment by kr428** [comment]
Not sure if it is this very problem, but I still experience "issues" trying to connect the "official" Mastodon app and all of its forks (Megalodon, Moshidon, ...) to loma.ml which is on 2023.09-rc. Same for https://alpha.trunks.social (web / Android variant) and https://elk.zone (web). Then again, there seem several incompatibilities in the Mastodon and Friendica implementation of Mastodon client API (in example Kaiteki recently is able to connect properly but doesn't really work in a meaningful way afterwards). Not sure, thus, whether the problems with the apps mentioned relate to this very problem.
