### ISSUE TITLE
Replies should use the parent post's privacy by default

### ISSUE THREAD

**Issue by northivanastan** [friendica/friendica#12542]
### Is the feature request related to a problem? Please describe.

In 2022.12-rc, Friendica's web interface has no ability to set the privacy on replies. Replies use the default post privacy for the account, regardless of what the parent post's privacy is. This makes it easy to accidentally leak information when replying to a private post if the default privacy is public.

### Describe the feature you'd like

I think it makes more sense to have replies default to using the privacy of the parent post. That way information is not leaked if the default is public. Most Mastodon clients seem to behave this way already.

### Describe alternatives you've considered

I could use a Mastodon client with this behavior, but then I'd miss out on quite a few things I enjoy about Friendica's web interface. 

It would also be nice to have an option to set the privacy for replies in the web interface, and that in itself would somewhat resolve this issue (as I could just make sure to check the parent post's privacy before replying, then set it properly).

If replies to public posts being public when the default privacy is followers-only is undesirable, perhaps a special case could be made just for replying to followers-only posts, to set the reply privacy accordingly.

**Comment by northivanastan** [comment]
I just tested this again and I couldn't replicate it myself. Maybe it got fixed since I last tested it. Sorry for wasting your time.

**Comment by MrPetovan** [comment]
It's completely okay, we love self-resolving issues! ❤
