### ISSUE TITLE
Message is shown as 60 minutes ago, ≠ 1 hour ago? 

### ISSUE THREAD

**Issue by gbraad** [friendica/friendica#12552]
### Bug Description

"60 minutes ago" is shown before "1 hour ago"

### Steps to Reproduce

1.  Post message 
2.  Wait 1 hour (or 60 minutes) 
3.  Wait a little bit more

Actual Result:

"60 minutes ago" is shown

Expected Result:

"1 hour ago" is shown

### Screenshots

![Screenshot_20221228_124015_Vivaldi Browser](https://user-images.githubusercontent.com/1894/209758790-12e59212-b823-4e32-941b-57cb92c5fbc2.jpg)
![Screenshot_20221228_124052_Vivaldi Browser](https://user-images.githubusercontent.com/1894/209758806-a3adc653-c645-4655-bb88-8f346e650845.jpg)

### Platform Info

Friendica Version: 22.12

Using the Frio theme, on an Android tablet (Vivaldi browser).

**Comment by MrPetovan** [comment]
Thank you for the report, it would be useful if you had exact date and times when the post was published and when you consulted the relative time string. It is likely to be a quirk related to rounding, but without exact input data, it's hard to reproduce.

**Comment by MrPetovan** [comment]
Never mind, I found the issue, a duration of 59 minutes and 59 seconds is wrongly rounded to 60 minutes.

**Comment by MrPetovan** [comment]
Congratulations all, we fixed a 12-year old bug!

**Comment by gbraad** [comment]
I had used this to explain a rounding error or wrong `>` instead of `>=` check to my son. Seems I wasn't far.
