### ISSUE TITLE
Cookies not being removed

### ISSUE THREAD

**Issue by Keith2** [friendica/friendica#1255]
In the /tmp directory cookies are created by libcurl from Diaspora sessions.
These remain in the /tmp directory and accumulate, when first noticed they were
using 1.3GB of disk space.
There should be some means of non-manually removing them.

**Comment by annando** [comment]
Are you using the diaspora addon to post to an existing diaspora account?

**Comment by annando** [comment]
This problem was solved with this commit: https://github.com/friendica/friendica-addons/commit/a8a37ee6fc9e43ec6671ae9bac497165abc126fa#diff-5d175beed92663b2f4b5a05becc3cb3c
