### ISSUE TITLE
Image Grid is not generated when a URL is placed right before the attached images

### ISSUE THREAD

**Issue by MarekBenjamin** [friendica/friendica#12559]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Image Grid is not generated when a URL is placed right before the attached images

### Steps to Reproduce

1.  Create a post
2.  Add Text
3.  Add URL
4.  Add images

Actual Result:

https://friendica-dev.mbbit.de/display/fa8fe840-1263-acb3-6a91-153015414928

Expected Result:

https://friendica-dev.mbbit.de/display/fa8fe840-1763-acb4-9237-8b0980284898

### Screenshots

see urls above

### Platform Info

Friendica Version:

Friendica Source:  develop (https://github.com/friendica/friendica/commit/689b6b015b84da4b8ce2bdb2389093e5d104b2c9)

PHP version: 7.4

SQL version: 10.3.37-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

**Comment by MrPetovan** [comment]
I found the reason.

The working post body looks like this:
```
Now a post without a URL

[url=https://friendica-dev.mbbit.de/photos/friendicadev/image/394612332563960ce1561f3280329933][img=https://friendica-dev.mbbit.de/photo/394612332563960ce1561f3280329933-1.jpg][/img][/url]

[url=https://friendica-dev.mbbit.de/photos/friendicadev/image/160932786263ab10c386e2a124851915][img=https://friendica-dev.mbbit.de/photo/160932786263ab10c386e2a124851915-1.jpg][/img][/url]
```
No content after the images, they can be scooped up as attachments and displayed in the image grid.

Now here's the non-working post body:
```
Now it is time to test if the image grind is correctly generated if I put a link right before the attached images:

https://kassel.social/profile/marek/profile

[url=https://friendica-dev.mbbit.de/photos/friendicadev/image/394612332563960ce1561f3280329933][img=https://friendica-dev.mbbit.de/photo/394612332563960ce1561f3280329933-1.jpg][/img][/url]

[url=https://friendica-dev.mbbit.de/photos/friendicadev/image/160932786263ab10c386e2a124851915][img=https://friendica-dev.mbbit.de/photo/160932786263ab10c386e2a124851915-1.jpg][/img][/url]
[attachment type='link' url='https://kassel.social/profile/marek/profile' title='Friendica Social Network | Der Marek @ Friendica Social Network'][/attachment]
```
Notice the `[attachment]` tag that was added by the link preview system, now there is "content" after the images and so they are considered as inline images.

We just need to process the `[attachment]` tag before we check for images at the end of the body.
