### ISSUE TITLE
Unable to search for a specific public post

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12551]
While looking into https://social.yl.ms/display/e18176ef-3463-a783-0341-86b278278567, I stumbled upon a personal case where a thread should have been completed but it wasn't.

See this post in an another conversation: https://friendica.mrpetovan.com/display/73e2b342-1263-ab47-98b7-a06320068136
See the original conversation: https://social.gbraad.nl/display/73e2b342-1263-ab47-98b7-a06320068136

I received this post because I was tagged, and theoretically I should have fetched the whole conversation leading up to this post, but it didn't happen. Furthermore, trying to manually search for the post Gerard was replying to (https://mastodon.social/@shoq/109587263453618794) yields no result.

I tried searching the same URL on my dev node and here's the log:
```
[INFO]: Trying to fetch link {"uid":43,"uri":"https://mastodon.social/@shoq/109587263453618794"}
[INFO]: Got actor and followers {"actor":"https://mastodon.social/users/shoq","followers":"https://mastodon.social/users/shoq/followers"}
[INFO]: Using original object for url https://mastodon.social/users/shoq/statuses/109587263453618794 []
[INFO]: Processing {"type":"as:Create","object_type":"as:Note","id":"https://mastodon.social/users/shoq/statuses/109587263453618794","actor":"https://mastodon.social/users/shoq","platform":"mastodon"}
[INFO]: The activity already arrived. {"id":"https://mastodon.social/users/shoq/statuses/109587263453618794"}
[NOTICE]: Activity had been fetched and processed. {"url":"https://mastodon.social/@shoq/109587263453618794","entry":0,"completion":3,"object":"https://mastodon.social/users/shoq/statuses/109587263453618794"}
[INFO]: Link not found {"uid":43,"uri":"https://mastodon.social/@shoq/109587263453618794"}
```
Looking into it, `The activity already arrived.` shows because the activity object ID `https://mastodon.social/users/shoq/statuses/109587263453618794` exists in the `arrived-activity` table.

As a result, `ActivityPub\Processor::fetchMissingActivity` believes that the `Activity had been fetched and processed.` which isn't true.

But it still returns the `https://mastodon.social/users/shoq/statuses/109587263453618794` URI to `Model\Item::searchByLink` which uses to look up `post-user-view` and fails, returning `No results`.

Now, just to be sure, I've looked for both the original post URL and the activity object ID in the `item-uri` table. I could only find the former, and it doesn't get any hit in `post-user-view` either.

```
MariaDB [friendica_dev]> SELECT * FROM `item-uri` WHERE `uri` = 'https://mastodon.social/users/shoq/statuses/109587263453618794';
Empty set (0.001 sec)

MariaDB [friendica_dev]> SELECT * FROM `item-uri` WHERE `uri` = 'https://mastodon.social/@shoq/109587263453618794';
+--------+--------------------------------------------------+------+
| id     | uri                                              | guid |
+--------+--------------------------------------------------+------+
| 453563 | https://mastodon.social/@shoq/109587263453618794 | NULL |
+--------+--------------------------------------------------+------+
1 row in set (0.001 sec)

MariaDB [friendica_dev]> SELECT * FROM `post-user-view` WHERE `uri` = 'https://mastodon.social/@shoq/109587263453618794';
Empty set (0.006 sec)
```
I also ran the worker manually just in case the activity had effectively arrived but the processing was worker-based, to no avail.

At this point, I'm stumped.

I haven't tried searching for any other post URI because this one has failed independently on my two nodes, and it doesn't seem to be related to a communication issue with the remote server since the activity had apparently arrived on my dev node.

**Comment by gbraad** [comment]
This is specifically one of the problems I also faced.

**Comment by annando** [comment]
This is solved by https://github.com/friendica/friendica/pull/12978
