### ISSUE TITLE
max connections reached?

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12568]
not sure if bug..
have this in errorlog
WARNING | worker | Maximum level (100%) of system connections reached: 151/151
 is there a setting for this?

**Comment by AlfredSK** [comment]
That's your database configuration. When you want to raise that setting you need to change that in your MySQL/MariaDB config file - something like /etc/mysql/my.cnf or /etc/mysql/conf.d/some-config-file.cnf.

**Comment by tek-aevl** [comment]
thanks, I found, it. Is there a  recommended number?> by chance... I set it to 420, for lulz

**Comment by AlfredSK** [comment]
Depends on the size of your Friendica node and how much memory your server has. I have set this to 500. My server has 128 GB RAM.

**Comment by MrPetovan** [comment]
Show-off.

**Comment by SpcCw** [comment]
You can try [mysqltuner](https://github.com/major/MySQLTuner-perl) to see if your settings are adequate. I don't recommend blindly following its recommendations but it also will tell you if your current settings are dangerous in terms of memory usage.

Running out of memory and having random things on your server oom-killed can be annoying and result in unexpected consequences.

**Comment by tek-aevl** [comment]
I have mine in a vm, with limited resources, for fun, :) 
Is there a way to see if I am reaching the limit again, with out waiting on the error?
