### ISSUE TITLE
Quoted posts look strange on Twitter

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12563]
When I quote a post from Twitter on Friendica it looks like it should.
![2022-12-29 01 21 06](https://user-images.githubusercontent.com/12480023/209887877-72c2f867-e373-4f6c-90cd-45446297eba2.png)
If the quoted post is federated to Twitter, it will look funny.
Between your own comment and the quoted post is another quoted post as "RT" text.
The post I quoted was already a quoted post from another Twitter contact.
![2022-12-29 01 21 26](https://user-images.githubusercontent.com/12480023/209888477-2305b8f9-a809-458c-b42b-1ce795fd7d85.png)

**Comment by MrPetovan** [comment]
Yeah, it looks like we could just keep the quoted tweet link and it would quote itself. The `RT...` stuff is meant for non-Twitter platforms.

This said, this isn't the best example you could have used for this issue.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
