### ISSUE TITLE
Previous / next direction in photo gallery

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#12608]
### Bug Description

I am not sure if it's a bug or not.

When I open a photo gallery and there the first (top-left) photo, I want to see the "next" by clicking the right arrow. But I need to click the left arrow. For me, that is confusing. Correct me if I'm missing something.. or see it wrong.

Actual Result:

clicking right opens the last photo of the album.

Expected Result:

clicking right opens the 'next' in the album

### Platform Info

Friendica Version:

Friendica 'Giant Rhubarb' 2023.03-dev - 1508

PHP version: 8.1.13

SQL version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment]
Thank you for self-closing your issues!
