### ISSUE TITLE
/settings/profile

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12600]
Permission denied, for secondary accounts.... When going to /settings/profile
What should the friendica directory owner  be www-data root or friendica ? and for chown what should it be 755  ? 775 ?

**Comment by MrPetovan** [comment]
If you got an error page, can you please take a screenshot of it?

**Comment by tek-aevl** [comment]
I have many database errors in my logs, not even sure where to start,

**Comment by MrPetovan** [comment]
Let's start with the web page, do you get a rabbit picture or just a white screen? We can probably help with the database errors as well if you can provide a sample here, or a longer form in a pastebin of your choice.

**Comment by tek-aevl** [comment]
Ok, my account has another 2 accounts delegated to it, I can switch to them, but while using one of the accounts if I try to edit account [a] settings its does the white default apache like forbidden error, but if I use account [b], I can access it's settings fine.
After posting I noticed I can use account [b] to access the setting to account [a], some how, if I login as account [b] directly.

**Comment by annando** [comment]
How have you created the two accounts and how have you enabled the delegation between them?

**Comment by tek-aevl** [comment]
i used [mine] to make the other 4
mine (primary)=>account1,account2,forum1,forum2
for some reason, if logged into forum2 or switch to it then go to accounts only [mine], is an option.
if I switch to account2, from mine, then I see the others but am unable to go to account 2 settings,
if I login from forum1 then I can access account 2 via delegation and access settings for account 2
 I think something big is messed up.

**Comment by annando** [comment]
Can you switch from the primary account to all other accounts via delegation? Then the basics are totally okay.

**Comment by tek-aevl** [comment]
I don't know how to explain this any better, but It used to work, but now, its not as expected, and I have to do strange methods to get to settings for the delegated secondary profile.
