### ISSUE TITLE
translate-able strings, plural and singular should not be separated

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#12602]
If there are plural and singular forms of a string that is translate-able should not be splitted apart to ease the translation process. E.g. "like this" in https://github.com/friendica/friendica/blob/develop/src/Content/Conversation.php#L210 and https://github.com/friendica/friendica/blob/develop/src/Content/Conversation.php#L242. The two strings should be encapsulated in one ``l10n->tt()` (at two places in the code) instead so that translators are presented with both forms at the same time.

reported by kalon33 on transifex

**Comment by nupplaphil** [comment]
@tobiasd  - Are there current issues you know? Maybe we can fix some of them for the upcoming release

**Comment by tobiasd** [comment]
Except the one mentioned above no.
