### ISSUE TITLE
Theme: Frio: custom colors don't work on a certain page in a private browser window

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#12607]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I found another page where the custom CSS colors don't seem to work when not logged in.

### Steps to Reproduce

go to: 
https://server.tld/profile/username/photos (in a private browser window)

--> custom colors work

open a photo ( still in a private browser window) 
https://server.tld/photos/username/image/325371234923b4fe2e5de9d587357922

--> custom colors don't work

Actual Result:

we see the server theme default

Expected Result:

should be the colors, the user has selected. (if so)

### Platform Info

Friendica Version:  Friendica 'Giant Rhubarb' 2023.03-dev - 1508

PHP version: 8.1.13

SQL version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment]
What custom colors are we talking about? With accented schemes, I'm not able to reproduce the issue on my development node

Default theme: https://dev-friendica.mrpetovan.com/profile/frio
User-specific theme: https://dev-friendica.mrpetovan.com/profile/hypolite/photos

**Comment by haheute** [comment]
I mean the single photo page, like this for example: https://dev-friendica.mrpetovan.com/photos/hypolite/image/15319571805db4aca32541b881635232

**Comment by MrPetovan** [comment]
Ah, thank you for the elaboration.

**Comment by MrPetovan** [comment]
Confirmed: https://dev-friendica.mrpetovan.com/photos/hypolite/image/6877339995637e795f487bf447150542
