### ISSUE TITLE
UpdateGServer checks servers that are blocked.

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#12601]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

UpdateGServer checks servers that are blocked.

The server `*.activitypub-troll.cf` is blocked on my instance, but still it is checked by UpdateGServer.

This is what the entry in the worker queue looks like:
`56497884 	UpdateGServer 	https://2cjt1orib.activitypub-troll.cf 	2023-01-02 18:59:16 	40`

### Steps to Reproduce

1.  Block a server
2.  Wait for UpdateGServer to be executed
3.  Check the worker queue

Actual Result:

The blocked server is checked

Expected Result:

The blocked server should not be checked.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.03-dev - 1507

Friendica Source: git

PHP version: 8.1.

**Comment by annando** [comment]
When we pick up the same mechanism like some PR before, where you created an `Add` function in the corresponding worker class? There we could perform the check for blocked domains. Same can then be applied for `UpdateContact` as well, where we should check for globally blocked accounts and accounts of blocked domains.

**Comment by MrPetovan** [comment]
Yes, ha ha ha, yes!

**Comment by mama21mama** [comment]
The same happens to me. but yesterday I did the blocking. but no effect. there are no such domains.

https://reisub.nsupdate.info/filehost/files/6nn.jpg
https://reisub.nsupdate.info/filehost/files/5cW.jpg

the lock doesn't work. they keep making flood
