### ISSUE TITLE
Support Quote with the API

### ISSUE THREAD

**Issue by stom79** [friendica/friendica#12603]
### Describe the feature you'd like

Some softwares using the Mastodon API developed their own quoting mechanism with the API. That allows mobile app to offer the ability to use quote (that already exists with Friendica).

As an example (for Akkoma): https://ihatebeinga.live/akkoma/swaggerui/#/Status%20actions/StatusController.create

They added an extra parameter when posting to `api/v1/statuses` => `quote_id` (String id of the message to quote).

Also, for timelines, the `status` object embeds a parameter: `quote` (`null` or`Status`: a quoted status).

Fedilab already supports these parameters.

**Comment by annando** [comment]
There is one slight problem with this. Currently we are embedded the quoted post in the API in the regular body. When we simply would add that field here, then the content would be duplicated. We had to know if the system is able working with the quote.
