### ISSUE TITLE
Page scrolls while reading it (not touching anything)

### ISSUE THREAD

**Issue by bernd-wechner** [friendica/friendica#12617]
- [X] I have searched open and closed issues for duplicates

### Bug Description

My first sally with Friendica, trying it out ... and already, alas, I am on edge of finding it unusable. Why? 

I click Conversations, on the toolbar as:

![image](https://user-images.githubusercontent.com/7296506/210674211-567b7f5b-d18a-4af9-bf19-050d76c896a5.png)

And I have Global Community selected.

I page down to explore, see something I like, and start reading it. Then it disappears suddenly. WTF? Huh? Disoriented (and familiar with Facebook doing similar crap) I scroll up and lo and behold it's there. I keep reading. Rinse and repeat. 

Unusable in a nutshell. 

I am using the https://venera.social/ instance.

### Steps to Reproduce

1.  Click Conversations in the toolbar
2.  Click Global Community
3.  Use mouse-wheel to scroll down until you find something of substance (with text to read)
4. Start reading
5. Watch it disappear

Actual Result:

What I'm reading disappears, without me touching a thing.

Expected Result:

For the feed to stay as it is unless **I** choose to scroll.

### Platform Info

Friendica Version:

> You can see Friendica’s version number at Help -> About this site -> Site/Friendica Version 

Not at https://venera.social/ I can't. So alas, I don't know.

**Comment by MrPetovan** [comment]
There is a setting to prevent the feed from updating if you aren't at the top of the page: Settings -> Display -> Content -> Automatic updates only at the top of the post stream pages

**Comment by bernd-wechner** [comment]
Why thank you, kind sir. 

Can we kindly rename this issue then to "Automatic updates only at the top of the post stream pages" on by default.?

Or conversly, convince me there is a standard use case, more common than actually um, reading ones feed, in which auto updates might be preferred and that this (to me, currently unimaginable use case) is in fact more common and likely to be found among users than actually, scrolling down to read stuff? Not least, given paging to the top will then auto refresh anyhow. 

A side note: Friendica is not alone here. I find MeWe impossible to use on my phone because it does something very similar. I'll be reading my feed (all the stuff new since I last looked) and there's a lot. Before I'm done, though I get distracted on something else, and then I come back and want to carry on from where I left off but no, it's gone, I'm back at the top with one new post! So I read that and then have to page down for ages trying to find where I was up to! For all its vices, Facebook does not do that! At least not on my phone. It seems to do what Friendica promises to if I turn this setting on.

In closing, if we were to conclude the use case for wanting this off is common and the two use cases on and off are anywhere remotely similar in likelihood to encounter, then I would change this issue to a request to put this setting on the toolbar, in prime view, to switch between the modus operandi easily and not buried under four mounse-clicks of menus in a hard to find little nook.

**Comment by MrPetovan** [comment]
> Or conversly, convince me there is a standard use case, more common than actually um, reading ones feed, in which auto updates might be preferred and that this (to me, currently unimaginable use case) is in fact more common and likely to be found among users than actually, scrolling down to read stuff? Not least, given paging to the top will then auto refresh anyhow.

I'm sorry I can't help you there. Several settings were added to keep legacy behaviors intact, even if I vehemently disagree with said legacy behaviors.

> Can we kindly rename this issue then to "Automatic updates only at the top of the post stream pages" on by default.?

I'm with you but I can't take this kind of decision on my own, I'll run an informal poll about the setting usage to support such a change.

**Comment by MrPetovan** [comment]
See https://friendica.mrpetovan.com/display/735a2029-1863-b6ca-219d-299279723245

**Comment by AlfredSK** [comment]
Maybe this is a suggestion to fix this.
Misskey ist auto-scrolling the feed when you are on the very top of the page. Content is added and the page scrolls automatically in a way that you always see the newest posts.
When you are not on top of the page Misskey is just showing a non-disruptive overlay button "load new posts". When you click that button the new content is loaded and the page scrolls to the top of the page.
I find that very convenient.

**Comment by MrPetovan** [comment]
Well, that was swift, thank you for your report!
