### ISSUE TITLE
CSS is not rendered anymore

### ISSUE THREAD

**Issue by annando** [friendica/friendica#12616]
### Bug Description

After fetching the latest changes from the develop branch my system looked like this:
![Bildschirmfoto vom 2023-01-04 23-36-28](https://user-images.githubusercontent.com/844208/210663943-1ff41e63-05ac-4043-980d-a0ae3b676945.png)

**Comment by nupplaphil** [comment]
uiui ..

can you check the `system.theme` value?

**Comment by nupplaphil** [comment]
any errors in the log? What's the return if you actively execute the CSS url?

**Comment by annando** [comment]
Since I do have some other users on my system as well, I quickly switched back to a working branch. I hadn't got any errors or warnings in my log.

**Comment by nupplaphil** [comment]
which is the working git commit, you're currently on?

**Comment by annando** [comment]
I'm currently on the branch with my mod/item changes. And the addons I just used one shortly before the last changes.

**Comment by nupplaphil** [comment]
OK, as far as I can see, your branch `annando:/mod-item` is based on the PR #12597, which is the DB state `1507`.

I guess that the CSS isn't loaded because you didn't update to `1509,` so the new config file wasn't wrote and an empty node-config was load (without a theme setting).

**Comment by annando** [comment]
But why hadn't the updater updated to 1509? it should do so automatically. And my current branch doesn't contain any database stuff.

**Comment by annando** [comment]
Could the problem be related to the fact that I'm using the daemon? With the daemon running, all worker tasks are always executed via the it. In the non-daemon mode, the worker tasks are executed directly via the frontend or via the backend. In the daemon mode, the frontend and backend are letting the daemon know, that there is some work to do, then the daemon picks up the job. Possibly the communication doesn't work any more?

**Comment by annando** [comment]
I just tried - but it didn't worked:
![Bildschirmfoto vom 2023-01-07 16-18-43](https://user-images.githubusercontent.com/844208/211157952-d5e464b0-fe66-4797-8080-bc6ad088b3ac.png)
As you can see from the screenshot, the database update was applied, but still something hadn't worked correctly. I'm now back on the "safe state".

**Comment by nupplaphil** [comment]
I don't get it... Was something in the logs? I had similar problems when the theme was accidentally set wrong..

**Comment by nupplaphil** [comment]
Can you send me your config table / local.config.php except the critical parts? I will try to reproduce it .. the current safe state is your item branch?

**Comment by nupplaphil** [comment]
As PM to @nupplaphil@friendica.philipp.info would be fine :-)

**Comment by annando** [comment]
Update: I deleted the old config file and tried again. Not it worked.
