### ISSUE TITLE
permission denied when posting to diaspora or facebook

### ISSUE THREAD

**Issue by phil111** [friendica/friendica#1261]
I have installed friendica sucessfully, also activated facebook and diaspora plugin. now, when I post something to either of them, it foes not appear there, and I get a message " permission denied" in friendica.
any help?

ph

**Comment by annando** [comment]
What is the logfile telling? Do your posts arrive at your local machine?

**Comment by annando** [comment]
There was no reaction for a long time. I'm closing the issue.
