### ISSUE TITLE
API PushNotification Parsing error

### ISSUE THREAD

**Issue by stom79** [friendica/friendica#12620]
POST call to `  @POST("push/subscription")` should return something similar to: 

```json
{
  "id": 328183,
  "endpoint": "https://yourdomain.example/listener",
  "alerts": {
    "follow": true,
    "favourite": true,
    "reblog": true,
    "mention": true,
    "poll": true
  },
  "server_key": "BCk-QqERU0q-CfYZjcuB6lnyyOYfJ2AifKqfeGIm7Z-HiTU5T9eTG5GxVA0_OH5mMlI4UkkDTpaZwozy0TzdZ2M="
}
```
Currently, Fedilab has a parsing error and can't retrieve server public key because, there is a parsing error with boolean in `alerts` that are integer values with Friendica.

See: https://docs.joinmastodon.org/methods/push/#200-ok

**Comment by MrPetovan** [comment]
Thank you for the report!
