### ISSUE TITLE
Publicly posted picture is not visible to other users

### ISSUE THREAD

**Issue by HelmutsCab** [friendica/friendica#12626]
**Bug description**

A publicly posted picture isn't visible to everyone. Even accounts on the same friendica instance (squeet.me) only see the text from the post but no picture.

**Reproduce**

1. open post editor
2. click on icon to add picture  
3. add picture
4. add title, text and tags
5. preview post (picture shows up)
6. send post

Post URL: https://squeet.me/display/962c3e10-9863-aef6-d828-d60901033610

**Actual Result**

The picture in my post shows fine in my personal timeline and status, but it‘s not visible for others (unsure if all users or some are affected).

**Expected Result**

The picture should be visible for everyone, since the post is public.

Screenshots:

![IMG_0660](https://user-images.githubusercontent.com/121969129/211034577-8bd9af42-0ba9-4e39-8c96-94947a1ee36c.PNG)

Friendica: 2023.03-dev, squeet.me
Datenbankversion 1507/1507
Post-Update-Version 1507/1507

**Comment by annando** [comment]
That's weird. The permissions are looking really weird. They only contain your contact and the public id of your contact. This is something unexpected. I have to dig deeper into it. To fix this special issue, you can change the permissions on the photo to make it visible.

How have you uploaded that picture?

**Comment by HelmutsCab** [comment]
I loaded the picture from my iPad into the folder on friendica, then I opened the post editor and added the picture with the icon.

**Comment by HelmutsCab** [comment]
The Problem seems to be solved. I posted a picture first with smartphone, then with iPad. Both Posts are with picture now. So I close issue.
Thank you!
