### ISSUE TITLE
/api/v2/instance not helpful

### ISSUE THREAD

**Issue by markrprior** [friendica/friendica#12625]
- [ X] I have searched open and closed issues for duplicates

### Bug Description

If an instance is queried for the V2 instance API then a two item JSON is returned, both look like free text but one has label "error" and the second is "error_description".  My expectation would be that "error_description" is something presented to a human in a natural, local language, while "error" is a standardised fixed format machine processed message. "error" is not fixed text.

### Steps to Reproduce

1.  wget -qO - friendica.opensocial.space/api/v2/instance

Actual Result:

> wget -qO - friendica.opensocial.space/api/v2/instance
{"error":"API Endpunkt GET api\/v2\/instance ist nicht implementiert","error_description":"The API endpoint is currently not implemented but might be in the future."}

Expected Result:

The message returned at "error" should be returned instead as "error_description" and "error" should return "NOTIMPLEMENTED" (or similar). Other platforms return a HTTP 404 error in this case rather than a questionably useful message so new v2 capable clients may get confused by this response and not fall back to a v1 query.

### Platform Info

Friendica Version:

2.8.0

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
I thought we were sending an appropriate error code (404 or, more cheeky, 501) but it doesn't appear so, thank you for the report.

**Comment by markrprior** [comment]
On 6/1/23 15:30, Hypolite Petovan wrote:
> I thought we were sending an appropriate error code (404 or, more 
> cheeky, 501) but it doesn't appear so, thank you for the report.

A 404 with a custom error page would solve the needs of machine and 
human :-)

**Comment by MrPetovan** [comment]
It's already a very custom error page, much to your chagrin, apparently! 😄

**Comment by markrprior** [comment]
> It's already a very custom error page, much to your chagrin, apparently! 😄

Not really a pretty looking human friendly error page though 😃

**Comment by MrPetovan** [comment]
No, but the endpoint isn't meant to be accessed by humans either 🤔
