### ISSUE TITLE
/api/v1/instance thumbnail value often incorrectly formatted

### ISSUE THREAD

**Issue by markrprior** [friendica/friendica#12624]
- [ X] I have searched open and closed issues for duplicates

### Bug Description

According to https://docs.joinmastodon.org/entities/V1_Instance/#thumbnail the thumbnail value is a banner image for the website, this is not true for a number of friendica instances. This could be due to a lack of understanding as to what the value should contain (ie a documentation fault) and/or a lack of input checking (allowing an incorrectly formatted value).

### Steps to Reproduce

1.  wget -qO - venera.social/api/v1/instance | grep thumbnail

Actual Result:

In the case of venera.social the URL returned is just the base URL and not an image. Other sites return a mixture of item types which may or may not work with a mastodon client. For example loma.ml returns a favicon and friendica.opensocial.space returns "https://friendica.opensocial.spacehttps://friendica.opensocial.space/opensocial_favicon.jpg".

Expected Result:

The mastodon document "https://docs.joinmastodon.org/entities/V1_Instance/#thumbnail" calls for an URL to an image, which I would expect to be a JPG or PNG.

### Platform Info

Friendica Version:

2.8.0

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
I thought we were sending an appropriate error code (404 or, more cheeky, 501) but it doesn't appear so, thank you for the report.

**Comment by MrPetovan** [comment]
Thank you for the report. This field is supposed to be populated by the node favicon used in a `<link rel="icon">` tag, but the form field isn't clear about the requirement for a relative or absolute link, which leads to some confusion in this API endpoint when an absolute URL is provided.

**Comment by markrprior** [comment]
Mastodon doesn't seem to use a favicon for this attribute. It can be a custom JPG/PNG for the instance but a number use the same image so there must be a default value.

**Comment by markrprior** [comment]
If you look at the second column of the table in [https://mrp.net/fediverse/](https://mrp.net/fediverse/) you will see some of the mastodon examples.

**Comment by MrPetovan** [comment]
Hmm, there doesn't seem to be a standard for the dimensions of this image. We have a default user account banner image (https://friendica.mrpetovan.com/images/friendica-banner.jpg) and it's 1600x1200px but it's well below the size of most images in the list you gave so we could use it for this purpose.

**Comment by markrprior** [comment]
> Hmm, there doesn't seem to be a standard for the dimensions of this image. We have a default user account banner image (https://friendica.mrpetovan.com/images/friendica-banner.jpg) and it's 1600x1200px but it's well below the size of most images in the list you gave so we could use it for this purpose.

Yeah the mastodon documentation could do with some help. Calling it a thumbnail and then not describing it isn't exactly helpful but your solution seems workable.
