### ISSUE TITLE
Twitter quotes buggy

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12640]
In the preview, a shared, from Twitter federated post looks like this on the Friedica page, i.e. how it should appear.
![2023-01-16 10 17 07](https://user-images.githubusercontent.com/12480023/212642551-f73b03e4-97a1-4ff6-9185-404135f7b962.png)
But after publication it looks like this.
![2023-01-16 10 17 31](https://user-images.githubusercontent.com/12480023/212642706-adb96be9-ae00-4f59-9980-07a7e47f98a7.png)

**Comment by kr428** [comment]
Adding myself to that. We've discussed similar issues on loma.ml; apparently, quote-sharing Twitter content in my environment will result in other Friendica users just seeing empty posts in the timeline. Diaspora and Mastodon seem to retrieve and render what is linked to so it works for these, causing the interesting effect to Friendica contacts of having posts with no obvious content but comments and discussions below. Friendica version seems 2023.01.

Post as visible for Friendica contacts:

![543097452163d28026748cb516852343-0](https://user-images.githubusercontent.com/685879/215025078-a9dd074b-0e4f-41e9-a5a1-e9fd2a3b6ea9.png)

Post as visible to me:
![image](https://user-images.githubusercontent.com/685879/215025408-9149560f-0b50-452c-885e-8496d5414e5a.png)


Post link: https://loma.ml/display/373ebf56-1863-d27f-98ae-d37633154525

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
