### ISSUE TITLE
Mirroring this feed ends up with broken URLs within posts

### ISSUE THREAD

**Issue by DanielSiepmann** [friendica/friendica#12658]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Mirroring posts from https://typo3.org/rss end up in posts with broken URLs.

### Steps to Reproduce

1. Create a new account
2. Set it as news page
3. Add the feed (https://typo3.org/rss) as contact
4. Set to mirror the contact as own posts with `fetch_further_information` set to `3`.

Actual Result:

A mirrored post with broken link: https://friendica.daniel-siepmann.de/display/3db7c7b4-688c9f7a-bc5cce04d32c606e

Expected Result:

A mirrored post with working link (and fetched information from that link)

### Platform Info

Friendica Version:

2022.12,

Friendica Source: 

PHP version: 8.1.12

SQL version: mysql  Ver 15.1 Distrib 10.3.36-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by DanielSiepmann** [comment]
I guess I know the root cause. I've patched my instance and will have a look at the situation.
I've to wait for a new post until I can see whether this actually fixes the issue. But I'm sure this is the cause as I've come up with this short test:

```php
$url = '
							https://typo3.org/article/t3board23-typo3-snowboard-tour-back-in-the-dolomites

					';

var_dump(parse_url($url, PHP_URL_SCHEME));
```
This will output `null` while 
```php
$url = '
							https://typo3.org/article/t3board23-typo3-snowboard-tour-back-in-the-dolomites

					';

var_dump(parse_url(trim($url), PHP_URL_SCHEME));
```

returns proper scheme. And this is checked to prevent modifications of the URL.

**Comment by MrPetovan** [comment]
Thank you for your report, I was about to remark about the whitespace within the `<link>` properties, would you be want to submit a PR yourself for this issue?

**Comment by DanielSiepmann** [comment]
I already did (https://github.com/friendica/friendica/pull/12659) :) Just created issue prior sending in PR.
