### ISSUE TITLE
DM about Fedilab is shared publicly on Mastodon

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12654]
- [ x ] I have searched open and closed issues for duplicates

See See Fedilab's contribution
https://toot.fedilab.app/@apps/109672339655165342

![image](https://user-images.githubusercontent.com/44441246/211918700-cd39cd3f-eecc-40fe-967c-0aadaaaf3e32.png)

**Comment by stom79** [comment]
Posting a message with the direct visibility works. Replying to a public message but setting the privacy to direct fails.

**Comment by FediVideos** [comment]
> Posting a message with the direct visibility works. Replying to a public message but setting the privacy to direct fails.

Do you mean the reply won't post, or that the reply is public?

**Comment by MrPetovan** [comment]
The reply is public.

**Comment by stom79** [comment]
The reply is posted but "direct" visibility is ignored and seems to get the public visibility.
