### ISSUE TITLE
Shorten very long URL visually to one line

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12669]
### Is the feature request related to a problem? Please describe.

Through Mastodon, I keep getting links that can be extremely long. These can stretch over 4-5 lines or more.
This not only looks very unattractive, but also disturbs the readability.

### Describe the feature you'd like

If a URL is delivered, it should be visually shortened so that the max 1 line long. The shortened URL will be replaced by ... to indicate that the URL has been shortened visually. The URL must remain callable.

Mastodon:
https://social.tchncs.de/@kaffeeringe/109686933139092798
![grafik](https://user-images.githubusercontent.com/44441246/212466661-2752d824-ba89-45be-ba9f-b1856e64c2b0.png)

Friendica:
https://loma.ml/display/59e215f1-a17d92412801275f-4f9dcbfd
![grafik](https://user-images.githubusercontent.com/44441246/212466685-0a286d38-74df-46a9-af45-2a701d09b304.png)

### Describe alternatives you've considered

If a link is rendered as a clickable preview, the link can be omitted

### Additional context

**Comment by bkil** [comment]
This is a mixed bag. **I** sometimes actually deliver [software](https://github.com/bkil/private-plugin.php) within [links](http://bkil.hu/css-pad/), I kind of like seeing the full URL.
* https://bkil.gitlab.io/static-wonders.js/jump/iframe-js-sandbox.html#url=data:text/html;,%3C!DOCTYPE%20html>%3Chtml>%3Cbody>x=%3Cinput%20oninput='document.querySelector(`b`).innerText=value*value'>x^2=%3Cb>%3C/b%3E

**Comment by loma-one** [comment]
When driving over it can be displayed completely.

**Comment by bkil** [comment]
It is only an option if you have a mouse.

And for my use case I just shared, pointer hovering won't be good enough. In such cases, you usually prefer to copy & paste parts of the shared code (URL) to run it separately to learn from it and analyze it. You can't drag & drop sections of the URL hover text. And hover text is also usually implemented to be able to display only a single line of it and for up to about half of the screen width due to "design considerations".

**Comment by loma-one** [comment]
That is the exception, for which a solution can certainly be found. In the meantime, however, many contributions look like this one. The message is lost in the link.

![grafik](https://user-images.githubusercontent.com/44441246/222695508-b76e1176-4917-4f56-8e80-910edd1b79df.png)

**Comment by loma-one** [comment]
There is currently no majority in favour of an amendment. Therefore closed here.

**Comment by annando** [comment]
Only because some issue isn't picked up, it doesn't mean that it is a bad idea.
