### ISSUE TITLE
Monolog führt zur Nichterreichbarkeit der Instanz

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12665]
I stupidly activated the addon "Monolog", which unfortunately leads to an error and the start page only loads as a white wall.

Running bin/console dbstructure update
gives an error

```
bin/console dbstructure update
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Friendica\Core\Cache\Factory\Cache::__construct() must implement interface Psr\Log\LoggerInterface, instance of Friendica\Core\Logger\Factory\Logger given in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php:74
Stack trace:
#0 [internal function]: Friendica\Core\Cache\Factory\Cache->__construct()
#1 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#2 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#3 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#4 /var/www/html/friendica/vendor/level-2/dice/Dice.php(149): Dice\Dice->Dice\{closure}()
#5 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#6 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#7 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#8 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Di in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php on line 74
root@xxx:/var/www/html/friendica# 
```

Question: how can I deactivate the addon again without access to the admin area?

PHP: 7.4
SQL: 10.3
Friendica: Stable

**Comment by MrPetovan** [comment]
What does `bin/console config addons` outputs?

**Comment by loma-one** [comment]
```
bin/console config addons
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Friendica\Core\Cache\Factory\Cache::__construct() must implement interface Psr\Log\LoggerInterface, instance of Friendica\Core\Logger\Factory\Logger given in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php:74
Stack trace:
#0 [internal function]: Friendica\Core\Cache\Factory\Cache->__construct()
#1 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#2 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#3 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#4 /var/www/html/friendica/vendor/level-2/dice/Dice.php(149): Dice\Dice->Dice\{closure}()
#5 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#6 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#7 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#8 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Di in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php on line 74
root@xxx:/var/www/html/friendica# 
```

I archived the addon as *.bak, hoping that it would be disabled in the DB. Unfortunately this was not successful

**Comment by MrPetovan** [comment]
I'm on it, I'll have a fix in under 30 min if you can wait that long.

**Comment by loma-one** [comment]
With pleasure :)
Thanks in advance

**Comment by MrPetovan** [comment]
@nupplaphil The problem is that in `index.php` we instantiate a `LoggerInterface` object before instantiating the `App` object, but the `Friendica\Core\Logger\Factory\Logger->create` method that is called as part of the Dice configuration emits a call to `Hook::callAll` which instantiate an `App` object which requires a `LoggerInterface` in the `Cache` dependency. However, at this point the `create` method hasn't completed, so the Dice record for the `LoggerInterface` object is still the factory object.

It's a classic circular dependency that would require us to drop the App dependency in `Hook::callAll`. It's only used in 18 places in the current addons, but it will require a blanket replace for all the places the parameter is mentioned but not used.

May Goodness have mercy on our souls.

**Comment by loma-one** [comment]
That means it will take some time to ensure the function the addon?
Do they have a hint how I can disable the addon to access the instance again?

**Comment by MrPetovan** [comment]
I'm working on a fix but it's currently modifying almost a hundred files across Friendica base and especially addons.

**Comment by loma-one** [comment]
I will be patient. Thanks a lot

**Comment by MrPetovan** [comment]
Ah wait, I went at it the wrong way, I can fix the same issue with much less invasive changes.

**Comment by MrPetovan** [comment]
Nevermind, I was misled, we have to go the long way 😓

**Comment by loma-one** [comment]
In that case I will have to switch from stable to dev, correct?

**Comment by MrPetovan** [comment]
Indeed.

**Comment by MrPetovan** [comment]
@loma-one If you're still on stable, you can still recover your install by editing manually the database row in the table `config` identified by `` `c`= 'system' AND 'k' = 'addons' `` and removing `monolog` from the `` `v` `` field.

**Comment by MrPetovan** [comment]
@loma-one If you're still on stable, you can recover your install by removing the offending hook in the `hook` table, identified by `` `hook` = 'logger_instance' ``. Just delete the row.

**Comment by loma-one** [comment]
It worked on the stable. Thanks again :+1:

**Comment by MrPetovan** [comment]
I reopened this issue because the underlying problem isn't fixed yet. ☺

**Comment by MrPetovan** [comment]
Now it's fixed on `develop` !
