### ISSUE TITLE
DB Error: "Index post-tag is corrupted"

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12668]
DB Error,

 Index post-tag is corrupted
 
 would turning it ("#tags") off and on again fix this it? LOL

**Comment by AlfredSK** [comment]
That's a very vague issue description. I can only guess that an index of that table is damaged.

If so, you can recreate the index by optimizing the table.

`mysqloptimize dbname tablename`

**Comment by tek-aevl** [comment]
Well, I attempted to do this, but I guess I am not sure how to via, shell...

**Comment by tek-aevl** [comment]
In mysql, or from cli?

**Comment by MrPetovan** [comment]
I think it is a CLI command. You may have to provide your database credentials by using the additional arguments `-u <username> -p`.

What is the original error message in full?

**Comment by tek-aevl** [comment]
I got this> 
``SELECT `cid` FROM `post-tag` WHERE (`cid` =
This is in many of the DBerror logs, with a different ^ number, same limit of 1.

I thought I posted this yesterday, but it didn't post. I have many things going on, all at once, so sorry for the delay's.

**Comment by MrPetovan** [comment]
So from the MySQL console:
``> OPTIMIZE `post-tag`;``

From the command line:
`$ mysqloptimize -u <username> -p <database> "post-tag"`

**Comment by schmaker** [comment]
I can confirm it happened to me too. MariaDB optimize command fixed the issue.

**Comment by tek-aevl** [comment]
I am not seeing this error anymore, ~~however I think my search for tags is now broken.~~

**Comment by tek-aevl** [comment]
> So from the MySQL console: `` > OPTIMIZE `post-tag`; ``
> 
> From the command line: `$ mysqloptimize -u <username> -p <database> `'post-tag'`

Seems to be working.
 But this from the MySQL console: > OPTIMIZE TABLE `'post-tag'`;
 to be exact.

**Comment by tek-aevl** [comment]
Aww, Found this again!!!

**Comment by tek-aevl** [comment]
but now I am getting this error, 
mysqloptimize: Got error: 1045: Access denied for user 'friendica'@'localhost' (using password: YES) when trying to connect

**Comment by tek-aevl** [comment]
Fixed.

**Comment by tek-aevl** [comment]
Thanks So much!
