### ISSUE TITLE
Twitter federation broken

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12677]
Something broke federating with Twitter after the last git pull on 3 hour ago on develop.
I can't find anything in the logs so far either.
Can anyone confirm this?

**Comment by ghost** [comment]
Seems that Twitter has changed something. Posts no longer arrive from Twitter to Friendica, but from Friendica to Twitter they do.

**Comment by AlfredSK** [comment]
Same here. But it seems that the timeline is imported once per day or so. I see stuff coming in from Twitter. But with a delay of nearly 20 hours.

**Comment by ghost** [comment]
I'm also having trouble retrieving the list of my followers on Twitter, all I get is a blank page.
They seem to be rebuilding something, maybe it will go away in the course of the day.

**Comment by AlfredSK** [comment]
See here: https://forum.friendi.ca/display/ec054ce7-8163-c1cd-8f36-134414451394

**Comment by ghost** [comment]
I get a WSOD when I try to go to the Twitter Addon page in the administration.

**Comment by ghost** [comment]
```
index [ERROR]: Uncaught Exception TypeError: "twitter_addon_admin(): Argument 
#1 ($o) must be of type string, Friendica\App given, called in /src/Module/Admin/Addons/Details.php on line 105" at /addon/twitter/twitter.php line 988 {"exception":"TypeError: twitter_addon_admin(): Argument 
#1 ($o) must be of type string, Friendica\\App given, called in /src/Module/Admin/Addons/Details.php on line 105 and defined in /addon/twitter/twitter.php:988\nStack trace:\n
#0 /src/Module/Admin/Addons/Details.php(105): twitter_addon_admin()\n
#1 /src/BaseModule.php(244): Friendica\\Module\\Admin\\Addons\\Details->content()\n
#2 /src/App.php(719): Friendica\\BaseModule->run()\n
#3 /index.php(44): Friendica\\App->runFrontend()\n
#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"63c3fa83237c9","uid":"e720c4","process_id":93556}

```

**Comment by MrPetovan** [comment]
I'm on it.
