### ISSUE TITLE
Special characters does not seem to work with categories

### ISSUE THREAD

**Issue by schmaker** [friendica/friendica#12684]
I have created category - IT & technologie with "&" as special character. At this moment it's only category i'm not able to access - i suspect that Friendica does not expect that character in category name.

URL from /profile page that i'm trying to access:
https://schmaker.eu/profile/schmaker/status?category=IT%20&%20Technologie

Related support thread:
https://schmaker.eu/display/c83e3896-1563-c058-ce85-7cf451922178

**Comment by schmaker** [comment]
![Screenshot_20230204_201758](https://user-images.githubusercontent.com/14954032/216785808-14199348-bdad-40cd-b9cb-3c39187aae38.png)

I accidentally found out inconsistency between category links:

1 takes me to https://schmaker.eu/profile/schmaker/status?category=IT%20&%20Technologie - URL returns nothing
2 takes me to https://schmaker.eu/profile/schmaker?category=IT%20%26%20Technologie - there is /status missing, when i modify URL to https://schmaker.eu/profile/schmaker/status?category=IT%20%26%20Technologie, everything works as expected

**Comment by MrPetovan** [comment]
Thank you for the detailed information, it's very useful!

**Comment by schmaker** [comment]
Still present in 2023.04

**Comment by schmaker** [comment]
![image](https://github.com/friendica/friendica/assets/14954032/6c5e52bb-108c-4d10-abd9-22e7235377ff)
1 - Still not working - takes me to this url 
![image](https://github.com/friendica/friendica/assets/14954032/40a667ba-6e99-4d62-849a-ccb80853fb60)

2 - **Works** in 2023.05-rc
![image](https://github.com/friendica/friendica/assets/14954032/4801a02d-3167-404f-b8e7-4c5d11b6882d)
