### ISSUE TITLE
Mastodon-compatible API returns reshared post ID as reshare itself's ID

### ISSUE THREAD

**Issue by rinsuki** [friendica/friendica#12682]
- [x] I have searched open and closed issues for duplicates

### Bug Description

when using Mastodon-compatible API of Friendica, server returns reshared post ID as reshare itself's ID.

this is unexpected behaviour for some Mastodon clients.

e.g. my Mastodon client called [iMast](https://github.com/cinderella-project/iMast) is crashed by assert (I just change it to show an error instead of crash in beta version, but still can't handle it correctly)

### Steps to Reproduce

1.  Reshare someone's post
2. Check reshare in Mastodon API somehow (e.g. home timeline, get ID from MySQL's `post` table and access `/api/v1/statuses/:id`)

Actual Result:

`reblog.id` and `id` will be same.
![image](https://user-images.githubusercontent.com/6533808/212611118-f9e9dec2-f87a-4de2-81e7-b4b38e37569f.png)

Expected Result:

top-level `id` should be reshare itself's ID instead of reshared post's ID.

e.g. in my screenshot, it should return 14 instead of 2.

### Platform Info

Friendica Version:

> This is Friendica, version 2022.12 that is running at the web location https://(REDACTED since it is running on my laptop and cant access from internet). The database version is 1502/1502, the post update version is /1484.

Friendica Source: Docker Image `friendica:2022.12-apache`

PHP version: 8.0.27

SQL version: `10.10.2-MariaDB-1:10.10.2+maria~ubu2204 mariadb.org binary distribution`

**Comment by annando** [comment]
The first `id` should be the value for the reshared post, while inside the `reblog` the object is the original one? What value should have the other elements? Like `uri`, `url` and also `in_reply_to_id` and so on?

**Comment by rinsuki** [comment]
> The first `id` should be the value for the reshared post, while inside the `reblog` the object is the original one?

yes. in my screenshot case, `reblog.id` should have a `2`.

> What value should have the other elements? Like `uri`, `url` and also `in_reply_to_id` and so on?

* `uri`: It should be reblog itself URI (It shouldn't same as `reblog.uri`). Mastodon sets `Announce`'s object ID.
* `url`: Mastodon uses same value as `uri`, but I think actual clients are don't care.
* `in_reply_to_*`: If reshare itself isn't reply to other post, it should be null (but `reblog.in_reply_to_*` should exists if reshared post is reply).

**Comment by annando** [comment]
BTW: Is it a problem when the request is for id "a" and the returned id is "b"?

**Comment by rinsuki** [comment]
AFAIK Mastodon never returns another ID, so i think you should be avoided as much as possible...

**Comment by annando** [comment]
Hmm, because of our data model, requesting post 2 or 14 will always return the same content. After my local changes this means the original post has got the id 2 and the reshared post has the id 14.
