### ISSUE TITLE
Security - Passwords should have no limitations

### ISSUE THREAD

**Issue by k5123** [friendica/friendica#12693]
- [ X] I have searched open and closed issues for duplicates

### Bug Description
Current implementation disallows use of specific characters - this should not be the case, as the password is supposed to be hashed and its contents don't matter.

The PHP password_hash() function has no problems with any of the currently disallowed characters, thus the limitation should not exist. Current implementation causes less secure passwords.

**Comment by MrPetovan** [comment]
> Allowed characters are a-z, A-Z, 0-9 and special characters except white spaces, accentuated letters and colon (:)

Special characters are allowed, **except** white spaces, accentuated letters and colon (:).

**Comment by k5123** [comment]
> > Allowed characters are a-z, A-Z, 0-9 and special characters except white spaces, accentuated letters and colon (:)
> 
> Special characters are allowed, **except** white spaces, accentuated letters and colon (:).

That is EXACTLY my point. There should be no "except", there is no justification for this. Passwords are hashed, therefore there shouldn't be any problems with whatever the user types as password. It shouldn't actually be a concern for any web application what the user types as a password, due to hashing.

**Comment by MrPetovan** [comment]
We don't need this kind of attitude.
