### ISSUE TITLE
Cannot apply patch mods/patches/level-2-dice-dice-php.patch

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#12696]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When I update and do a `bin/composer.phar install --no-dev` I see the error message from the title in red:
```
  - Installing level-2/dice (4.0.3): Loading from cache
  - Applying patches for level-2/dice
    mods/patches/level-2-dice-dice-php.patch (0)
   Could not apply patch! Skipping. The error was: Cannot apply patch mods/patches/level-2-dice-dice-php.patch
```
I'm unsure how important that is. So, I'm reporting it.

### Screenshots

![friendica-composer-dice patch](https://user-images.githubusercontent.com/5753419/213426713-6f01e194-8e76-4de9-8652-ce979d7a9fdb.jpg)

### Platform Info

Friendica Version:  Friendica 'Giant Rhubarb' 2023.03-dev - 1512
PHP version: 8.1.14
SQL version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by nupplaphil** [comment]
Ui ... Can you retry again if it works at second attempt? Just to know if it's a timing problem?

**Comment by haheute** [comment]
Ok. I just tried.  It is the same . This error appears also since 2 days (or 3 maybe)...

**Comment by nupplaphil** [comment]
Thx, I know where it comes from, but not why :D maybe a version mismatching and the patch doesn't find the right structure, I'll investigate it

**Comment by haheute** [comment]
thank you very much :+1:
