### ISSUE TITLE
SO I some how did this...

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12691]
Vendor path not found. Please execute "bin/composer.phar --no-dev install" on the command line in the web root.
and now, it seems like I have no databases.       ^ also this does nothing.

**Comment by MrPetovan** [comment]
Can you please list the content of your Friendica directory and the output of the `bin/composer.phar --no-dev install` command?

**Comment by tek-aevl** [comment]
everything was still, there, but I reverted, my snapshot lost what seems like a days worth of post...
