### ISSUE TITLE
Quotes in ALT-text of images messes up D* federation

### ISSUE THREAD

**Issue by HankG** [friendica/friendica#12701]
### Bug Description

For posts created through the Mastodon API when the ALT-text for an image has actual quotes in it, then the federation to Diaspora gets very messed up. The problem doesn't seem to manifest on Mastodon.

### Steps to Reproduce
1. Create a post with an image attachment that has quotes (not smart quotes) in it as a media attachment through the API
2. Check the result on a Diaspora server to show that it is getting garbled BBcode text rather than an embedded image

Actual Result:

Garbled BBCode text 

Expected Result:

An image.

### Screenshots

This post from my friendica server: https://friendica.myportal.social/display/e65e1095-1363-ca14-3a61-8b4346494405
![image](https://user-images.githubusercontent.com/1683691/213616298-767b3654-9ab0-4224-bdc2-e1e9dce04f22.png)

As seen from the diasp.org server (improper): https://diasp.org/posts/e65e1095-1363-ca14-3a61-8b4346494405
![image](https://user-images.githubusercontent.com/1683691/213616260-b75a6bb1-c0af-4228-ba2e-02eae1c552a7.png)

As seen on the techhub.social Mastodon server (proper): https://techhub.social/@hankg@friendica.myportal.social/109719575090310057
![image](https://user-images.githubusercontent.com/1683691/213616455-097bde65-16a2-49dc-aed2-c2eb41c444f4.png)

### Platform Info

Friendica Version: Image created with 2022.12, post created with 2023.01

Friendica Source: https://github.com/friendica/friendica/ stable branch

PHP version: 7.4.33

SQL version: MariaDB 15.1

**Comment by tallship** [comment]
It's this really a Friendica bug, or perhaps it's a Diaspora* bug?

Just tested this myself and observed that there's no issue with the images and Alt-tags showing up correctly on Calckey, Soapbox, Mitra, or Smithereen.

I looked over the issues [here](https://github.com/diaspora/diaspora/issues) but didn't see that any related issue had been raised.

⛵

.

**Comment by HankG** [comment]
> It's this really a Friendica bug, or perhaps it's a Diaspora* bug?
> 
> Just tested this myself and observed that there's no issue with the images and Alt-tags showing up correctly on Calckey, Soapbox, Mitra, or Smithereen.
> 
> I looked over the issues [here](https://github.com/diaspora/diaspora/issues) but didn't see that any related issue had been raised.
> 
> boat
> 
> .

Do any of those federate with the Diaspora protocol instead of ActivityPub? If they do then perhaps the problem is D* specific. If not then we will have to investigate if the problem is how we are formatting the message or how D* is processing it.

**Comment by annando** [comment]
This problem is based on an incompatibility between our markdown generator and Diaspora's markdown generator.

**Comment by HankG** [comment]
> This problem is based on an incompatibility between our markdown generator and Diaspora's markdown generator.

Is that fixable or should I try to make sure my app replaces quotes with smartquotes on all platforms?

**Comment by annando** [comment]
I guess we have to try out how to convince Diaspora's Markdown parser to do like we want it to do. In any case we should change something for any other platform.
