### ISSUE TITLE
CW/Spoiler Text isn't federating to Mastodon Correctly through Mastodon API

### ISSUE THREAD

**Issue by HankG** [friendica/friendica#12702]
### Bug Description

When creating posts through the Mastodon API with CW/spoiler text it does not federate over to Mastodon in a way that renders correctly.

### Steps to Reproduce

1. Create a post through the Mastodon API that fillers in the spoiler field
2. Go to a Mastodon server to see how it renders.

For example this body:
```json
{
  "status": "main content",
  "visibility": "public",
  "spoiler_text": "A header"
}
```

sent into the POST endpoint: `/api/v1/statuses`

Actual Result:

With posts created in the 2022.12 and 2023.01 version the CW renders as a Title field which when clicked opens up to the post itself but without any additional text.

Expected Result:
It should render with a "SHOW MORE" button. 

### Screenshots
Below is a screenshot of a native Mastodon post below one federated over from the Friendica server:
![image](https://user-images.githubusercontent.com/1683691/213617969-2f6d83d3-ee3b-46e8-a7d2-6b87ba5e32bd.png)

This is the same native post with the additional text shown:
![image](https://user-images.githubusercontent.com/1683691/213618065-7f92695f-163d-4998-8e6b-7f7a96d4241f.png)

This is the post created with 2023.01 as rendered on the Friendica server:
![image](https://user-images.githubusercontent.com/1683691/213618136-0c7e357d-11f5-4a26-abca-fd28955e2b1c.png)

This is the rendering of that post on Mastodon when I click on the header:
![image](https://user-images.githubusercontent.com/1683691/213618188-e379ec15-1e58-4aa1-a21e-27d526f66519.png)

### Platform Info

Friendica Version: 2022.12 and 2023.01

Friendica Source: https://github.com/friendica/friendica/ stable branch

PHP version: 7.4.33

SQL version: MariaDB 15.1

**Comment by HankG** [comment]
...weirdly these posts from 29 December show that it doesn't work on the post but it did on comments I wrote on the post (all through Friendica): 
![image](https://user-images.githubusercontent.com/1683691/213619230-218f798a-4447-4837-b7cf-d04e12166d32.png)

**Comment by HankG** [comment]
...same problem with a post done with 2022.10: 
![image](https://user-images.githubusercontent.com/1683691/213619524-daa1c0f3-3109-409c-bd3f-d770cb423a7a.png)

**Comment by HankG** [comment]
The problem is that spoiler-text on posts is being put into the title field. When it is a comment it is being put into the "content-warning" field *and* the API appends the [abstract=apub][/abstract] to the beginning. I believe the correct behavior should be to do the comment way for anything posted through the API, whether it is a post or a comment.

**Comment by annando** [comment]
The PR #12702 contains a possibility for the user to change the behaviour for their own. This enables backwards compatibility. Also we should add a "title" parameter for our own apps.
