### ISSUE TITLE
Been spammed by *.activitypub-troll.cf, how to delete related items in storage and database

### ISSUE THREAD

**Issue by kalon33** [friendica/friendica#12705]
I've been spammed by *.activitypub-troll.cf (2026619 servers known when trying to filter through web interface...).
I tried blocking them using web interface but obviously that failed (needed more than 5GB RAM...), and my web browser is using a lot of memory. I could using csv list but this way I couldn't remove items already in database/storage.
   
How can I proceed to purge that items from my instance? Is there a way to prevent that kind of problem that could crash a server?

Thanks for your help.

**Comment by ghost** [comment]
Block the Domain *.activitypub-troll.cf

**Comment by MrPetovan** [comment]
We're working on a fix: https://github.com/friendica/friendica/pull/12700

**Comment by kalon33** [comment]
> Block the Domain *.activitypub-troll.cf

I already did using a .CSV file as I can't from the web interface as I said in my report, due to the number of items. But I couldn't clear storage and database from these spams as it is normally possible using web interface, so I was asking for help: 1) to make the cleanup 2) to be able to use the web interface when being targeted by these spams 3) to be able to prevent them.

**Comment by kalon33** [comment]
```
DELETE FROM `gserver` WHERE `url` LIKE '%activitypub-troll.cf%' OR `url` LIKE '%gab.best%';
Query OK, 5734330 rows affected (16 min 42.328 sec)
```
(Also cleared gab as I wasn't sure to have done it previously)
Is this enough to cleanup or should I perform more operations?
   
Thanks for your help and for working on the fix.

**Comment by MrPetovan** [comment]
There's nothing more you can do at the moment, I believe this query left some contact records orphans but it's better than nothing to save space and memory when dealing with the server domain pattern block list.

**Comment by Quix0r** [comment]
I guess the problem with orphaned `contact` records is, that they are not directly linked to a `gserver` records, means there is only a programmed link between them and no foreign key constraint. It could be relatively easy to do that by checking each `gserver` record, if records in `contact` table have this part of their profile URL (compare `nurl` columns as they are normalized).

**Comment by annando** [comment]
@Quix0r we don't have got a "programmed link". The foreign keys are set correctly for the `gserver` table.

**Comment by MrPetovan** [comment]
Does it mean all the contacts referencing deleted servers are deleted in cascade? What about their posts? Are they also deleted in cascade from the contacts?

**Comment by Quix0r** [comment]
In table `contact` there is a foreign key to `gserver` with `ON DELETE CASCADE` (**EDIT:** Local change!). So yes, they are being deleted (or else it will cause a lot of other errors like empty arrays.

**Comment by Quix0r** [comment]
Sorry for the confusion I have caused. I have a local change on database, default is `ON DELETE RESTRICT` (see file static/dbstructure.config.php` around line 221).

**Comment by MrPetovan** [comment]
Ah-ha!

**Comment by annando** [comment]
The deletion restrictions are set intentionally this way. The posts are the most important part of the system, so we have to prevent them from being deleted by accident. So you can only delete global contacts when they aren't connected to any post. And we can't delete servers when they are connected to any contact.

**Comment by MrPetovan** [comment]
So we need a purge option from the command line as well.

**Comment by grinapo** [comment]
And logging where it comes.

**Comment by Quix0r** [comment]
> And logging where it comes.

Yes, we need to know why a post/contact has been rejected.

**Comment by MrPetovan** [comment]
Logging where what comes?

**Comment by annando** [comment]
A basic purging is not that much of a deal. The fast version could simply delete all `gserver` entries that aren't connected to any contacts. This should cover the most entries.

**Comment by MrPetovan** [comment]
Not sure about that, I believe these gserver records were created because there was at least on bogus user on them.

**Comment by annando** [comment]
On two of my servers I hadn't got any connected user. I only had one contact on the third server. And there it only had been one contact. And that one was only created because someone tagged that user in a post.

**Comment by 4nanook** [comment]
I've got this same issue from same site, I ran the above DELETE from query and deleted 15 million some odd rows:
Query OK, 15402233 rows affected (11 min 6.416 sec)
But workqueue still is full of *.activitypub-troll.cf entries.

**Comment by 4nanook** [comment]
I have both *.activitypub-troll.cf and activitypub-troll.cf in my server block list, still these bastards are queueing up new jobs in my workqueue.  How to get rid of these assholes?

**Comment by 4nanook** [comment]
For what it's worth there is no DNS for either activitypub-troll.cf nor the bogus subdomains, so perhaps a ip->domain->ip lookup requiring the ip point to a domain point back to the original ip is a check that could stop these (this is done by postfix mail servers).

**Comment by 4nanook** [comment]
Ought to be somewhere or someway to make friendica log the IP associated with these so we can block at router or firewall.

**Comment by grinapo** [comment]
> Logging where what comes?

There should be data on where a server originates. 
For example right now I have such logs:
```
2023-01-29T10:27:59Z worker [INFO]: Server peer update start {"url":"https://fed.sbcloud.cc","worker_id":"85e31dd","worker_cmd":"UpdateServerPeers"} - {"file":"UpdateServerPeers.php","line":54,"function":"execute","uid":"a33038","process_id":295381}

2023-01-29T10:27:59Z worker [INFO]: Server is unknown. Start discovery. {"Server":"https://1chs090ty.activitypub-troll.cf","worker_id":"85e31dd","worker_cmd":"UpdateServerPeers"} - {"file":"GServer.php","line":358,"function":"check","uid":"a33038","process_id":295381}
```

Server is unknown where? What triggered dicovery? Where does the objsect triggering discovery originate?
And is there a relation between these two lines, or they just happen to follow randomly one another?

I have no origin server, no ip, no log trails, no nothing. Or if I do, I cannot see it.

**Comment by grinapo** [comment]
> I have both *.activitypub-troll.cf and activitypub-troll.cf in my server block list, still these bastards are queueing up new jobs in my workqueue. How to get rid of these assholes?

I have banned that server (sbcloud.cc) above, then cleaned `workerqueue` table of trolls, removed trolls from `gserver` table then restarted everything. Since then these are gone, and gab.best started to accumulate, same way.

**Comment by 4nanook** [comment]
I do not see sbcloud.cc showing up in apache access logs nor any of the IPs to which it resolves.

**Comment by ne20002** [comment]
> For what it's worth there is no DNS for either activitypub-troll.cf nor the bogus subdomains, so perhaps a ip->domain->ip
> lookup requiring the ip point to a domain point back to the original ip is a check that could stop these (this is done by postfix
> mail servers).

I disagree with this idea. Many servers are operated by volunteers on private basis and are running in home networks with probably dynamic IP allocation. Setting a PTR record is mostly not possible for those servers.   

Generally the Fediverse will face the same spaming problems as we had and still have with email plus comment spamming. And we will have to fight it with mostly the same tools.

To do so, we need to identify the spammers (see also #12692), we need to ignore the spam posts and the spammer accounts and even the spamming servers and we need to share the information about detected spammers with others.

On my small private Server I run a ModSecurity WAF in front of my friendica (which is blocking by 20 illegal requests per day) and it also blocks requests from servers on xbl.spamhaus.org dnsrbl list (zen.spamhaus.org is not usable as it includes many dial up ip ranges where servers are running (see point above)). Using a dnsrbl list would at least easy blocking of spam servers. 
ModSecurity WAF as well as CrowdSec does have a few rules to identify comment spamming.  

I think about a public list of identified spammer domains/accounts to share this so servers can drop messages from and also do not request any data from those domains/accounts.

**Comment by 4nanook** [comment]
First the solution I suggested IS implemented in the majority of mail servers, it is the default with both postfix and sendmail, second, RBL lists which you propose are easily abused by anyone who has a political agenda or just feels like being a jerk.  Nobody in their right mind would run a server on a dial-up connection, a cable modem maybe if lame, but a dial-up would not be workable.

**Comment by ne20002** [comment]
I run my own mail server and yes: PTR records are used by most of them and already neccessary as otherwise servers wouldn't be trusted. But also a static IP is required (for this I have a small vps with static ip just forwaring connection with vpn to my home site).
For the Fediverse servers most of the small servers runned privatly by people are hosted on networks without static ip and without the ability to set PTR records. Thus, making PTR a requirement would foreclose those servers from Fediverse.
In many areas of Europe you only get connection with non static IP (or you have to pay extra) and the ip changes once per day (so using dyndns is quite common but PTR is impossible). I have looked in my connetions and requests logs for quite some time to optimize my firewall rules and my server federates to nearly 2000 other servers where most of are in ip ranges without static ip assignment (mine also on a 1GBit fibre) and many use dyndns.

So: I doubt we can use the same mechanism for fighting spam as email servers do. But we have indeed the same need to fight spam anyway. I'm sure that also with the other software as Mastodon, Pixelfed, etc together there will be some more or less working solutions. How detecting spam/spammers, blocking spam/spammers and sharing this information with others will work is a work in progress for me.
But definitely a topic that shall be taken care of.

**Comment by 4nanook** [comment]
I guess the degree to which Friendica and the Fediverse in general are going to succeed is a function of the degree to which people are willing to provide the necessary resources.

**Comment by ne20002** [comment]
I think we're going more and more off topic but yes ... the Fediverse is social media from people for people and therefore depending on how much people are willing to give content, to interact and to provide resources.

**Comment by annando** [comment]
Fixed by https://github.com/friendica/friendica/pull/12910

**Comment by MrPetovan** [comment]
> Fixed by #12910

If there’s at least a contact, will the blocked server still be deleted?

**Comment by annando** [comment]
No. But all the other entries will be deleted - which is a lot.

**Comment by MrPetovan** [comment]
I thought the activitypub troll worked by having fake users link to each other, which also triggers fake server lookups?

**Comment by annando** [comment]
At least not for me.

**Comment by tek-aevl** [comment]
It seemed that way for me, the user could create and account, I think the payload is via a photo upload. The suspect accounts I had have been deleted., maybe they add something during registration that only they can see...that link to trollbase? 





I wish we could make our server invite only-sh.... or allow manual activation.

**Comment by Quix0r** [comment]
@tek-aevl With manual activation the table `gserver` is still (!) being flooded by these trolls with useless records. That was the whole point of this patch (initially written by me). That there were millions (!) of fake records in it causing the whole database to expand. I guess that was the reason for them doing it in the first place. My patch stopped blocked domains/instances from entering `gserver`.

**Comment by Mannshoch** [comment]
I have 2023.12 installed.
Yesterday I wondered why Friendica seems not resceiving any posts and found a 20GB database. After cleaning with:
```
DELETE FROM `gserver` WHERE `url` LIKE '%activitypub-troll.cf%' OR `url` LIKE '%gab.best%;'
```
 my database only has 9GB
I entered the donain `activitypub-troll.cf` and `*.activitypub-troll.cf` into the blocklist .

Today I checked the worker queue and around of 75% of all entries came from activitypub-troll.cf

If I run the command and then wait 5m and drerun it. Around 7000 entries agian are to remove.
It seems the blocklist does not work

**Comment by Mannshoch** [comment]
May I did not recognize the save button at the very end of the Page for blocking domains.

**Comment by Quix0r** [comment]
@Mannshoch You can check your `/friendica` view if the blocked domains appear there. To make Friendica not flood your table with these massive redundant entries, you can try my patch here: https://github.com/friendica/friendica/commit/1a9ed768846b2672fddd6ed15a935a5f5d42c449 It re-adds some checks in `GServer` if the domain is blocked and then prevents it from being inserted.

**Comment by MrPetovan** [comment]
@Mannshoch If you had a running worker/daemon process when you updated your blocklist, it's possible it won't be taken into account until the next cron run/daemon restart. And since this forkbomb works based on server discovery that's the done in the background, it doesn't directly hit your node with requests which would have had been blocked immediately after you added the pattern to your blocklist.
