### ISSUE TITLE
not receiving contact requests

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12708]
On `This is Friendica, version 2023.03-dev that is running at the web location https://pirati.ca. The database version is 1512/1512, the post update version is 1507/1507.` not seemingly receiving contact requests.

This was first noticed after a contact unfollowed and tried to follow again (we were testing something). And it was confirmed by following from a new test account.

In both cases no notification with a request to allow following was received.

**Comment by damianwajer** [comment]
It happened to me once too. I can't provide any debug details (only Friendica version 2022.12), but it was a similar case as above.

**Comment by MrPetovan** [comment]
On my end with a auto-accept follower account, I'm only not getting notifications for follows, but the requests come through.

**Comment by annando** [comment]
Reading this I realized that I hadn't seen incoming requests for days now.

**Comment by foss-** [comment]
No longer reproducible. Another test round and follow notification for contact request showed as expected. Closing.
