### ISSUE TITLE
Resetting the admin settings (node.config.php)

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#12715]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

After today's git pull https://github.com/friendica/friendica/commit/ced77ccbce8e6310b47500769fe5736c59e88f72 the following areas in the adminstartions area were deleted or reset to initial values of the first installation

General information
	- page name 
	- Additional information
	
Registration 
	- Registration text
	
Upload file
	- Quality of JPEG image 

Performace
	- Clean up database
	- Lifetime of contributions from other nodes 
	- Lifetime of not requested contributions 
	- Lifetime of contributions (reset)
	- Optimize tables regularly 
	
Message relay
	- Direct relay transmission 
	
Administration - protocols
	- Keep log
	- Log file
	- Log level
	
deleted the complete settings of the imprint addon 

these are all settings which are stored in the node.config.php as far as I know

### Platform Info

Friendica Version:

Friendica Source:  2023.03-dev - 1512

PHP version: 8.1.2-1ubuntu2.9

SQL version: MariaDB 10.6.11

**Comment by annando** [comment]
i experienced the same. AFAIK @nupplaphil is already working on it.

**Comment by AlfredSK** [comment]
I had this issue some time ago - shortly after the node.config.php had been introduced. Later it was fixed and worked as expected. So, most likely this is a regression of a later commit.

**Comment by sekretaerbaer** [comment]
I just noticed that this behavior does not only occur with the git pull. This morning the entries were deleted again. When I then re-entered the entries via Admin Site, my changes were deleted again when I clicked under Save Performance all entries. There was also a strange behavior of the interface. The background color changed briefly from the color I set to the default color.

**Comment by annando** [comment]
Are you on the latest develop branch?

**Comment by Tuxi2020** [comment]
I can confirm this behavior on the local test environment.

**Comment by MrPetovan** [comment]
@EssmannMa This seems to indicate your `config/node.config.php` file isn't correctly written every time a config value is changed. The truncation seems to work ok though!

**Comment by sekretaerbaer** [comment]
@annando last git pull was yesterday [df021b07e](https://github.com/friendica/friendica/commit/df021b07e330740510320fe5e0e1700829104b44)

**Comment by annando** [comment]
That's weird. I hoped that this wouldn't occur anymore, once we only use the config for real config values. I hope that @nupplaphil will find the origin of the problem.

**Comment by AlfredSK** [comment]
And now I have the same issue on libramet.de. Parts of the config are magically reset to default values.
I change them, save them. When I check later some are reset to default. Annoying, tbh.

**Comment by AlfredSK** [comment]
Looks like when I save the settings in my admin panel two or three times the values are not reset to default.
1. adjust a setting/option
2. click the safe button
3. click the save button

**Comment by AlfredSK** [comment]
I just rebooted my server. After the reboot nearly all config values were reset to default. 😖

**Comment by AlfredSK** [comment]
The weird thing is on my small node (mordor.social) I had the issue only one time. Since then it works.

**Comment by nupplaphil** [comment]
Sadly I got Corona yesterday, but I'm near to fix my PR and revert the node.config.php at all

**Comment by AlfredSK** [comment]
@nupplaphil Take all the time you need. No need to hurry. Get well!
