### ISSUE TITLE
Server error 500 - can't post or preview post

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#12721]
### Bug Description

With the latest dev code, I can not preview a post, or post it. I get server error 500 in the browser console.

the latest commit in my instance's git log seems to be [2db935fae24c71b1b77bb66c4f7b347ecdd42ae4](https://github.com/friendica/friendica/commit/2db935fae24c71b1b77bb66c4f7b347ecdd42ae4)

### Steps to Reproduce

try to post a post (I had one with a photo)

edit: It seems to fail only with a photo in the post.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.03-dev - 1512
PHP version: 8.1.14
SQL version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment]
A 500 error should leave a trace in your web server logs. Please check if there's anything relevant showing up when you try to preview or publish a post.

**Comment by haheute** [comment]
I think this one appears when I click preview:

```
2023-01-22T20:30:17Z index [ERROR]: Uncaught Exception InvalidArgumentException: "Unable to retrieve the host in URL: " at /var/www/localhost/friendica/src/Network/HTTPClient/Client/HttpClient.php line 73 {"exception":"InvalidArgumentException: Unable to retrieve the host in URL:  in /var/www/localhost/friendica/src/Network/HTTPClient/Client/HttpClient.php:73
Stack trace:
#0 /var/www/localhost/friendica/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\\network\\HTTPClient\\Client\\HttpClient->request()
#1 /var/www/localhost/friendica/src/Content/Text/BBCode.php(519): Friendica\\network\\HTTPClient\\Client\\HttpClient->get()
#2 /var/www/localhost/friendica/src/Content/Item.php(1014): Friendica\\Content\\Text\\BBCode::scaleExternalImages()
#3 /var/www/localhost/friendica/mod/item.php(248): Friendica\\Content\\Item->finalizePost()
#4 /var/www/localhost/friendica/mod/item.php(199): item_process()
#5 /var/www/localhost/friendica/mod/item.php(81): item_insert()
#6 /var/www/localhost/friendica/src/LegacyModule.php(96): item_post()
#7 /var/www/localhost/friendica/src/LegacyModule.php(80): Friendica\\LegacyModule->runModuleFunction()
#8 /var/www/localhost/friendica/src/BaseModule.php(228): Friendica\\LegacyModule->post()
#9 /var/www/localhost/friendica/src/App.php(697): Friendica\\BaseModule->run()
#10 /var/www/localhost/friendica/index.php(44): Friendica\\App->runFrontend()
#11 {main}"} - {"file":null,"line":null,"function":null,"request-id":"63cd9cd94a732","uid":"6aa078","process_id":21494}
```

**Comment by MrPetovan** [comment]
Oh, thank you, I believe this is related to an elusive issue we've had with the unit tests https://github.com/friendica/friendica/issues/12713

**Comment by MrPetovan** [comment]
Can you please share the body of the post you're trying to preview/post?

**Comment by haheute** [comment]
yes, this is what I tried to post:
> [url=https://boerdica.de/photos/noidea/image/205873784863ce439bc24d7845834962][img=https://boerdica.de/photo/205873784863ce439bc24d7845834962-1.jpg][/img][/url]
> 20230122-gimp.jpg -- late #sundaygimp

**Comment by MrPetovan** [comment]
Thank you!

**Comment by HankG** [comment]
I just tried setting up a new server against the head of the dev branch and was getting nothing but 500 errors for everything as well, including against the missing favorite icon (rather than a 404). I was going to write a new Issue against it but maybe this is the same thing? Unfortunately there were no error logs in the apache logs.

**Comment by MrPetovan** [comment]
Have you enabled any addons?

**Comment by HankG** [comment]
...sorry I hit "comment" too fast. I was able to get it installed against stable and then switch to develop. I tried reproducing this above bug on the head of develop with only standard addons installed and I can both post and see previews.

**Comment by HankG** [comment]
...however doing a post with an image attachment also produces an error mentioned above with the same error in the log file.

**Comment by HankG** [comment]
Using git bisect I think I've nailed it down to Commit 9ff3aca3b26adbfadda67e5f37d292e742d455bc

**Comment by HankG** [comment]
Using git bisect it appears to be this commit that is causing the problem: 881cb456e2712e04d0a510619e06fa371567feaf

**Comment by MrPetovan** [comment]
Well, it's a symptom rather than the cause. I wanted to know why we're trying to perform HTTP request to empty domains, and that's why I added this Exception.

**Comment by haheute** [comment]
I was, just now, able to post an image inside a link similar to the above example via the button "insert Link or media file"...  where I inserted the URL of one of my photos. And then I added a link to the full size photo manually / with the editor.
(But it is a private post.)

Another (also private) post with photos inserted via the photo browser still could not be previewed / posted.
