### ISSUE TITLE
Add cache headers for static files

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12728]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Looking on my nginx log file on my reverse proxy I find a high number of cache missed entries on static files.

Having (today until writing) 2187 calls to my friendica instance thereof are 425 calls to `https://fedi.****.ch/static/security-v1.jsonld` and 425 calls to `https://fedi.****.ch/static/activitystreams.jsonld`.
 
For me those seem to be candidates for caching.

Actual Result:

Static jsonld files not chached.

Expected Result:

Static files to be cachable.

### Platform Info

Friendica Version:

Friendica 2023.01 docker image with Podman behind Nginx reverse proxy.

**Comment by MrPetovan** [comment]
Do you have any suggestion for nginx configuration? I'm only familiar with Apache.

**Comment by ne20002** [comment]
The fascinating part here is that those are currently served by php (in src/Util/JsonLD.php).

According to the answer in  #11749 this is not needed? Looking into /static I see a number of jsonld files as well as php files. I suspect only the jsonld files are really static (and may be served to the clients).

If there is really no further processing of the jsonld files, I will provide a change for the nginx.

**Comment by ne20002** [comment]
For the nginx used together with php-fpm as described in the documentation on [hub.docker.com](https://hub.docker.com/_/friendica) pointing to the nginx.conf example [here](https://github.com/friendica/docker/blob/stable/.examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/fpm/web/nginx.conf) I suggest to add the following lines at line 74:

```
    location ~* /static/.*\.jsonld$ {
      expires 30d;
      try_files $uri /index.php?pagename=$uri&$args;
      access_log off;
    }

```

**Comment by ne20002** [comment]
Hi @MrPetovan 

there is one other thing I don't understand: looking in the log file it is not only that the files are not cached/cacheable: it seems as if those requests are coming from the friendica itself?
In my logs the source ip of the requests on the reverse proxy is the ip of the backend server. But why would Friendica do this?

**Comment by AndyHee** [comment]
> Having (today until writing) 2187 calls to my friendica instance thereof are 425 calls to `https://fedi.****.ch/static/security-v1.jsonld` and 425 calls to `https://fedi.****.ch/static/activitystreams.jsonld`

May I ask why the `*.jsonld` calls are so high. My node (no docker) has 10,000s calls per day but only a few dozens relate to `*.jsonld`.

**Comment by AndyHee** [comment]
> In my logs the source ip of the requests on the reverse proxy is the ip of the backend server.

Are you using nginx in a container or tunnel in via a CDN? This could produce localhost entries in the log.

**Comment by ne20002** [comment]
No
I run the Friendica in a container behind a nginx reverse proxy. The reverse proxy is one machine, the backend services (where Friendica is one of) are hosted on two additional machines.
For me it looks like Friendica is doing calls to these files with its base url.
`192.168.40.144 - - [26/Jan/2023:00:04:30 +0100] "GET https://fedi.xxxx.ch/static/activitystreams.jsonld HTTP/1.1" 200 7985 "-" "-" 0.001 MISS
`
This is the entry in the reverse proxy's log where 192.168.40.144 is the ip of the machine running friendica (dmz1xxxx.ch) and fedi.xxxx.ch is the host as served by the reverse proxy.
I don't think this is an unusual setup. The machine running Friendica (dmz1.xxxx.ch) itself does not resolve fedi.xxxx.ch to localhost.

**Comment by AndyHee** [comment]
I guess it's actually the destination IP what we see here. To also see the origin, one might have to possibly enable geo-location or something like this. 

We do have a wonderful [Admin forum](https://forum.friendi.ca/~admins) where more experienced Sys OPs might be able to give more precise information of the intricate workings of nginx's logging function.

Do join us over there - it's usually very informative and good spirited. It'd nice to hear more about the  scale of your setup in terms of usage numbers, system capacity, and maintenance experience. 😊

**Comment by MrPetovan** [comment]
The address at the start of the log line is the IP address of the remote connection, of the sender, not of the destination.

**Comment by AndyHee** [comment]
Thanks @MrPetovan

**Comment by ne20002** [comment]
I have restartet my instance and the reverse proxy, but the requests still appear.
Looking into the log I see that it is always directly following a request to /inbox (from an outside ip) with one or two sets of calls to /static/activitystreams.jsonld and /static/security-v1.jsonld (from my Friendica instance on dmz1).
I have removed the caching now but this does not change behaviour (as it has been there before). Still not any clue what is causing this.

**Comment by MrPetovan** [comment]
It's the JsonLD parser that performs these requests which seems to be namespace URLs, but I can't explain beyond that. It's a core part of ActivityPub federation communication though.

**Comment by ne20002** [comment]
I think the issue is not what is handling these requests but more what is _causing_ the requests. 
As those clearly come from the Friendica instance for me it seems as if Friendica is doing requests to itself (where itself is not localhost but the baseUrl, which is then causing the request to go via the reverse proxy). 
Either way I don't really see why it is using requests to itself.

Another possible explanation
* would be something like that Friendica is using this requests to call remote systems but somehow there is now an issue where it is resolving to itself: like do this calls for any system you receive messages from and for whatever reason one of the messages is referring to my own instance. 
* or with another observation: _all_ requests to the two /static/ urls are coming from my instance, not a single one from another instance, which may suspect that Friendica is calling itself _instead_ of a remote system. This might be caused by using wrong variable when building the requests. As it does not get a correct answer, it tries repeatedly.

Also to mention: I have't found any issues with Friendica not working properly with web interface as well as with using Tusky. It's just a bunch of mysterious requests.
I also rechecked my setup and neither the nginx reverse proxy nor the nginx in front of php-fpm is doing something that would explain this.

**Comment by AndyHee** [comment]
So are they pull or push requests?

**Comment by MrPetovan** [comment]
These are pull requests. The way JsonLD works is that you can provide namespace-like context URLs as a shorthand for a mapping list of field names. When we compact/normalize JsonLD documents, instead of making external calls to these URLs (like https://w3id.org/security/v1) to retrieve the associated mapping, instead we point at an internal URL, chiefly `https://<your node base URL>/static/security.jsonld`. It's better for privacy and performance since we cache the content of these files for a day in the volatile Friendica cache (Memcached, Redis, Memory, etc...)

If you have so many requests for these URLs, it probably means your local cache handler isn't properly set up.

**Comment by AndyHee** [comment]
What about `/.well-known/nodeinfo` ? 

Should that not be cached too? There are constantly many GET requests.

This looks like a static file:

`{
    "links": [
        {
            "rel": "http://nodeinfo.diaspora.software/ns/schema/1.0",
            "href": "https://my-friendica.node/nodeinfo/1.0"
        },
        {
            "rel": "http://nodeinfo.diaspora.software/ns/schema/2.0",
            "href": "https://my-friendica.node/nodeinfo/2.0"
        }
    ]
}`

**Comment by ne20002** [comment]
Ok, so what I understood is:
- there is kinda processor for jsonld files which requires certaint files which it looks up by requests
- you spoof these requests urls before passing to the processor e.g.: replace https://w3id.org/security/v1 with https://<your node base URL>/static/security.jsonld
- you serve this files under the spoofed url
- you're proxying outgoing requests and have a cache for this to reduce number of outgoing requests

This would explain the behaviour I see here if the cache is not working. So I take a look at this.

**Comment by ne20002** [comment]
> What about `/.well-known/nodeinfo` ?

I see a few more requests that's responses shall be cacheable, e.g. profile pictures. It may be an idea to collect such urls and see/discuss what the correct caching strategy and lifetime would be.

**Comment by AndyHee** [comment]
> profile pictures

How would caching affect if someone updates their profile picture?

**Comment by AndyHee** [comment]
I think `/view/js/*.js` might be interesting to see how much caching would make a performance difference.

**Comment by ne20002** [comment]
> How would caching affect if someone updates their profile picture?

Depends on the cache lifetime. Also: cache can be configured with revalidation.
- serve content and then call upstream server for revalidation (so next requester gets new content) or
- check upstream for new content and if upstream answers with 304 serve the cached content. If upstream server handles check for changed content this can be very fast.

**Comment by ne20002** [comment]
Hi @MrPetovan 

> If you have so many requests for these URLs, it probably means your local cache handler isn't properly set up.

I have a Redis running and it says it has a client connection. But it has a very few keys and those seems to be sessions.
In config folder there is 00apcu.config.php and 01redis.config.php. REDIS_HOST is set. So I would say it is standard setup.

Any place to look or something to check in particular?

**Comment by MrPetovan** [comment]
> I think `/view/js/*.js` might be interesting to see how much caching would make a performance difference.

JS files are only used in the context of a web browser which already caches them, so we don’t need to do it ourselves.

@ne20002 What’s your `system.cache_driver` config value?

**Comment by ne20002** [comment]
> @ne20002 What’s your `system.cache_driver` config value?

This is what I found:
```
ne20002@dmz1:/mnt/pods/friendica/html$ cat config/00apcu.config.php
<?php

/**
 * If nothing else set, use APCu as a caching driver (best performance for local caching)
 */

return [
	'system' => [
		'cache_driver' => 'apcu',
	],
];

```

**Comment by MrPetovan** [comment]
Thanks, what the output of `bin/console config system cache_driver` ?

**Comment by ne20002** [comment]
```
# ./console config system cache_driver
system.cache_driver => apcu
# 
```
For me the caching on Friendica side is still unclear. As you mentioned, you cache it for the uri `https://<your node base URL>/static/security.jsonld`. 
If I request it by this uri, it will be served from apcu cache. Correct?
But when you call this uri somewhere in Friendica itself, it would be resolved normaly. As in my case, the `<your node base URL>` is the hostname resolving to the reverse proxy, doesn't that lead to exactly what I see? All those requests going through the reverse proxy with the ip of the backed server as origin?

In my case `<your node base URL>` is different to local hostname.

**Comment by MrPetovan** [comment]
The output of these URLs will only be cached and used from the cache in the context of the JsonLD namespace resolving. I'm not familiar with using APCu as a cache engine so I'm not sure whether it's correctly caching for a day as requested in the JsonLD code.

**Comment by ne20002** [comment]
My understanding now is, that my statement about resolving the `<your node base URL>` is correct and it indeed runs the request via the reverse proxy.
If I understood you correctly, still the APCu shall function as a cache to the JsonLD code and therefore minimizing the number of requests to these files.

I will do some research on this, maybe an explanation or solution can be found.

Other than this I wonder why this url is spoofed as `https://<your node base URL>/static/security.jsonld`. Instead of using `<your node base URL` using the hostname or 'localhost' may be a solution. But this may require to change from https to http.

**Comment by MrPetovan** [comment]
I can't help you there. We are spoofing URL of local static files that we could load directly in the method that spoofs the URL, saving an HTTP round-trip in favor of a fast local file read.

I'll submit an improvement, let's see what @annando has to say about it.

**Comment by annando** [comment]
Have you checked if the validator accepts local files?

**Comment by ne20002** [comment]
I have merged the changes manually. The requests to the /static url do not longer appear.

However, is seems there is a side effect as I now have (just a few) other requests coming from the Friendica instance to itself in the log file on the reverse proxy (and the log file on the nginx of the Friendica instance). Those are:
```
"GET https://fedi.****.**/images/person-80.jpg HTTP/1.1"
"GET https://fedi.****.**/.well-known/host-meta HTTP/1.1"
```
> Have you checked if the validator accepts local files?

After the changes made I found the folowing in my log, but only two times (two times three entries):
```
2023-01-29T09:16:08Z index [WARNING]: E_WARNING: Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/friendica/json-ld/jsonld.php:391) {"code":2,"message":"Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/friendica/json-ld/jsonld.php:391)","file":"/var/www/html/src/App/Page.php","line":395} - {"file":null,"line":null,"function":"header","uid":"294d36","process_id":585}
```

```
2023-01-29T09:26:18Z index [WARNING]: E_WARNING: Undefined variable $http_response_header {"code":2,"message":"Undefined variable $http_response_header","file":"/var/www/html/vendor/friendica/json-ld/jsonld.php","line":391} - 
{"file":"jsonld.php","line":391,"function":"jsonld_default_document_loader","uid":"184c69","process_id":1177}
```

```
2023-01-29T09:26:18Z index [WARNING]: E_WARNING: foreach() argument must be of type array|object, null given {"code":2,"message":"foreach() argument must be of type array|object, null given","file":"/var/www/html/vendor/friendica/json-ld/jsonld.php","line":391} - {"file":"jsonld.php","line":391,"function":"jsonld_default_document_loader","uid":"184c69","process_id":1177}
```

Also to mention: Friendica is still working without problems seen.

Fixed with https://github.com/friendica/friendica/pull/12832

**Comment by MrPetovan** [comment]
Thank you for your report, I know why you're getting these messages but I don't expect them to affect how Friendica works. I'll submit a patch with the JsonLD library that we publish ourselves.

**Comment by MrPetovan** [comment]
@annando See https://git.friendi.ca/friendica/php-json-ld/pulls/1

**Comment by annando** [comment]
I will have a look at it in the moment where I can remember my credentials there. Sadly my password storage app in Nextcloud doesn't work at the moment.

**Comment by ne20002** [comment]
> @annando See https://git.friendi.ca/friendica/php-json-ld/pulls/1

I also applied this fix manually. With this fix I don't see any more warnings in log file. Also Friendica seems to work without problems. No calls to /static resources in the reverse proxy's log any more.

I do have a few other request with the Friendica instance as source and destination (only these eight until now):

```
192.168.40.144 - - [30/Jan/2023:08:44:37 +0100] "HEAD https://fedi.****.**/images/default/peertube-account.png HTTP/1.1" 200 0 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.001 MISS
192.168.40.144 - - [30/Jan/2023:08:44:37 +0100] "GET https://fedi.****.**/images/default/peertube-account.png HTTP/1.1" 200 4944 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.000 HIT
192.168.40.144 - - [30/Jan/2023:10:13:43 +0100] "HEAD https://fedi.****.**/images/person-300.jpg HTTP/1.1" 200 0 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.001 MISS
192.168.40.144 - - [30/Jan/2023:10:13:43 +0100] "GET https://fedi.****.**/images/person-300.jpg HTTP/1.1" 200 11087 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.000 HIT
192.168.40.144 - - [30/Jan/2023:16:19:59 +0100] "HEAD https://fedi.****.**h/images/person-300.jpg HTTP/1.1" 200 0 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.001 MISS
192.168.40.144 - - [30/Jan/2023:16:19:59 +0100] "GET https://fedi.****.**/images/person-300.jpg HTTP/1.1" 200 11087 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.000 HIT
192.168.40.144 - - [30/Jan/2023:16:54:54 +0100] "GET https://fedi.****.**/images/person-80.jpg HTTP/1.1" 200 2669 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.001 MISS
192.168.40.144 - - [30/Jan/2023:16:54:58 +0100] "GET https://fedi.****.**/.well-known/host-meta HTTP/1.1" 200 975 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://fedi.****.**" 0.239 MISS
```
HIT and MISS are cache status on the reverse proxy. ;)

**Comment by annando** [comment]
@MrPetovan I just got to know that the password app on Nextcloud now needs at least PHP 8.1 which Synology still has to deliver. I will try to find the password elsewhere or will try some possible passwords, but not today. Possibly tomorrow, but since i will be away for the next few days, I cannot really tell when I will find time. Possibly @nupplaphil or @tobiasd is quicker for this.

**Comment by annando** [comment]
@ne20002 this is all fixed already in several of my latest PRs for the develop branch.

**Comment by ne20002** [comment]
> @ne20002 this is all fixed already in several of my latest PRs for the develop branch.

Great. I'm on stable docker image and with manually appying the fixes here I fine. Works for me. Knowing that the other issues are already addressed/fixed I'm happy.

@MrPetovan , @annando Thank you very much
