### ISSUE TITLE
Default RSS Update Freqency to More Sane Level

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#12722]
### Is the feature request related to a problem? Please describe.

Currently all new contacts are set, by default, to update frequency `regularly`. This is means **very often**, usually less than five minutes.

Such short update intervals make perfect sense for social communication in the context of the Fediverse. That's what's expected!

However, this is not sensible for RSS updates for following two reasons:

- RSS are (more) unidirectional forms of communication, where blogs, announcements sites, etc. tend to publish less often and don't expect instantaneous replies in some form or another 
- Unlike Fediverse type of servers, regular web servers that host RSS feeds are usually not designed with high-frequency automated calls in mind that for example a Friendica node produces.

Discussion in the admin list have highlighted how for example Nitter servers are totally overwhelmed by Friendica's high frequency updates: https://friendica.hubup.pro/display/174591b4-1963-cd40-a734-47a915679743 Similarly Friendica can easily trigger bot alerts in some content delivery networks.

In sum, what makes sense perfect sense in-between Fedivers nodes, is not only unneeded with other servers, but also can be seen as misuse.

### Describe the feature you'd like

Default the RSS update frequency to `hourly`.

<strike>Add an additional  `'rss_adjust_poll_frequency' => true,` setting in `local.config.php` to prevent misuse by users.</strike>
[feature already exists]

**Comment by MrPetovan** [comment]
> Add an additional `'rss_adjust_poll_frequency' => true,` setting in `local.config.php` to prevent misuse by users.

What do you mean about misuse?

**Comment by AndyHee** [comment]
> What do you mean about misuse?

Let's say a user on a Friendica node wants to disable a nitter server. They would just create a few RSS contacts on a node that pulls on that nitter server often to achieve that aim. Or maybe just inadvertently they change the update frequency to `regularly` on that server. Does this make sense?

This is an example of such an "attack" that caused rate limitation rendering the server unusable.
 https://friendica.hubup.pro/display/174591b4-1563-cd46-8b5b-d7a542504470

**Comment by annando** [comment]
You can already set `min_poll_interval` to a level that you feel better about.

**Comment by AndyHee** [comment]
> You can already set min_poll_interval to a level that you feel better about.

But this would affect all communication, wouldn't it?

I normally would like to have very frequent updates with other Friendica nodes.

**Comment by annando** [comment]
That affects the fetching of all RSS/Atom posts.

**Comment by AndyHee** [comment]
So what that already exists, admin control of RSS update frequency? This would part two of my request redundant.

**Comment by MrPetovan** [comment]
> > You can already set min_poll_interval to a level that you feel better about.
> 
> But this would affect all communication, wouldn't it?
> 
> I normally would like to have very frequent updates with other Friendica nodes.

There's no other scheduled content pull across protocols. All other content is pushed to you by remote servers through the delivery mechanism, so this wouldn't affect it.

**Comment by AndyHee** [comment]
I think I've learned something here. Thank you, both.
