### ISSUE TITLE
New user created an account,

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#12742]
When I try to follow them it fails, and this pops up, in a notice bubble on the top right.

**The profile address specified does not provide adequate information. No compatible communication protocols or feeds were discovered.**

**Comment by MrPetovan** [comment]
1. Did they create an account on the same node?
2. If yes, what version is the node running?
3. Do you mind to share the profile address of this account?

**Comment by tek-aevl** [comment]
they joined my node.  2023.01
(https://www.urbanmind.net/profile/pauby)

**Comment by tek-aevl** [comment]
IT would be nice if accounts didn't require email verification, to become available. Maybe like another form of verification.

**Comment by tek-aevl** [comment]
Was 2fa. Removed with this update, I do not see anything about it in my account anymore.

**Comment by MrPetovan** [comment]
When I tried to access https://www.urbanmind.net/profile/pauby I was first brought to a page saying "verifying that your connection is secure" before being redirected to the profile page. I suspect that this verification blocks automated HTTP requests that cannot be redirected via Javascript or HTML tag.

Unfortunately at the moment there's no exception for local profiles, their profile page needs to be available for Friendica to reach without an interstitial screen.
