### ISSUE TITLE
[API] friendship object (probably) not returning `blocking` and / or `blocked_by`

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12750]
Lovely that blocking users is now supported via mastodon API. It works great when blocking users e.g. in Fedilab app. Thanks for adding this.

**Currently**

However I noticed that while blocks arrive and show in friendica, when looking at the profile of a blocked account in Fedilab there is no indicator that they are blocked.

**Expected**

Tom mentioned that this might be related to friendship object not returning "blocking" and "blocked_by" values.

Fedilab Codeberg: https://codeberg.org/tom79/Fedilab/issues/764

**Comment by HankG** [comment]
Looking at this I think one problem we have is that the statusing fields are going through the Contact::getPublicAndUserContactID method to build up the data. That calls into the `account-user-view` view which maps the blocked parameter from the contact table. However once a contact is blocked it seems the contact entry for a given user is deleted and only the public one is left. Therefore we never have any user-specific block data. The user-contact table seems to still have this data however. Perhaps we should be building off that table's data instead?
