### ISSUE TITLE
no new posts on latest develop

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12757]
Since a few hours, it seems no new posts are received on pircati ca

This is Friendica, version 2023.03-dev that is running at the web location https://pirati.ca. The database version is 1513/1513, the post update version is 1507/1507.

Maybe this is related to https://github.com/friendica/friendica/issues/12708 covering the absent contact requests.

**Comment by annando** [comment]
There had been a bug in https://github.com/friendica/friendica/pull/12752 which the server currently runs on.

**Comment by foss-** [comment]
Receiving new posts again. Thanks @annando
