### ISSUE TITLE
Mastodon API follow_requests/:id/authorize endpoint is broken

### ISSUE THREAD

**Issue by HankG** [friendica/friendica#12761]
We have an ID inconsistency between the endpoint that returns follow requests and the ones for authorizing/rejecting them. The IDs that are returned from the follow_request are the follow_request ID. The ID's that the authorize (and I'm guessing reject) them is expecting the user's ID. On Mastodon these IDs are always the user's IDs. In the discussions on initial implementation in #7887 and #7968 @MrPetovan had points about why these should always be the follow request ID. Making them all the follow request ID would fix this *except* for the fact that the follow_request notifications have no concept of that. The only thing we have to work with over there is the user's ID. Therefore I think that the ID for this endpoint should follow the Mastodon methodology and be the user's ID with the only place the follow_request ID's are user facing is in the Link data in the response header.

**Comment by annando** [comment]
From my point of view it has to be the contact id, because apps expect this. So I guess we have to fix it at some places.
