### ISSUE TITLE
category link below timeline items link to an outdated route

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#12760]
If you add an category to your post the button in the footer of the post do not link to the correct route ( /profile/matthias?category=neuhier instead of /profile/matthias/conversations?category=neuhier ) 
Not complete shure how it's ment to work but the filter is not applied if I click to the button in the link.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/1984982/215755794-105b45e0-55ad-48ee-9106-659c9e2f6614.png">

**Comment by matthiasmoritz** [comment]
Am I the only one experiencing this?

**Comment by MrPetovan** [comment]
The labels at the bottom of posts can be disabled, so it's likely very few users actually see them, let alone click on them.

**Comment by tobiasd** [comment]
I can confirm that the links in the footer of postings in frio are broken. I'm just not a frio user, so I did not notice before ;-)
