### ISSUE TITLE
[ActivityPub C2S] Implement posting via ActivityPub C2S

### ISSUE THREAD

**Issue by yvolk** [friendica/friendica#12776]
This is one of ActivityPub C2S implementation problems, reported by me at @annando request (see my first report at https://github.com/andstatus/andstatus/issues/573#issuecomment-1417286215 )

Currently posting to outbox fails: it is not implemented yet, as I understand. I got HTML page as a response instead (time in UTC below)
```
02-05 09:38:24.604 D/HttpReadResult: getJsonObject; ; statusCode:OK (200); url:'https://pirati.ca/outbox/andstatus'; response:'<!DOCTYPE html…'
```

**Comment by annando** [comment]
What kind of response do you expect from the endpoint? I'm currently having a look at what AndStatus is transmitting.

**Comment by yvolk** [comment]
Please see about exactly the same: https://todo.sr.ht/~tsileo/microblog.pub/121
