### ISSUE TITLE
Can you clarify the multiple admin documentation please?

### ISSUE THREAD

**Issue by scarlet-tobar** [friendica/friendica#12788]
I feel like this piece of information could be improved with an example.
"Can there be more then one admin for a node?

Yes. You just have to list more then one email address in the config/local.config.php file. The listed emails need to be separated by a comma."

At first I tried:
` 'admin_email' => 'mail1@example.com', 'mail2@example.com'`
But it is actually like this:
` 'admin_email' => 'mail1@example.com,mail2@example.com'`

Thank you for your work.

**Comment by MrPetovan** [comment]
Thank you for your suggestion!
