### ISSUE TITLE
friendica account not recognized by tusky mastodon android app

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12780]
Android: 13
Friendica: This is Friendica, version 2023.03-dev that is running at the web location https://pirati.ca. The database version is 1513/1513, the post update version is 1507/1507.
Tusky: 21.0

### Bug Description

While it previously was possible to add friendica accounts to Tusky without problems, this is no longer the case for pirati.ca. It still works fine for squeet.me. 

**not working**
pirati.ca: Friendica: This is Friendica, version 2023.03-dev that is running at the web location https://pirati.ca. The database version is 1513/1513, the post update version is 1507/1507.

**working**
squeet.me: This is Friendica, version 2023.03-dev that is running at the web location https://squeet.me. The database version is 1507/1507, the post update version is 1507/1507.

### Steps to Reproduce

1. in Tusky `Add Account`
2. add `pirati.ca` in the instance field
3. tap `Login with Tusky`

Actual Result: Error message `Could not load the login page.`

Expected Result: successful login.

Polite ping @annando since this is your instance.

Related:

- https://github.com/friendica/friendica/issues/12530
- https://github.com/friendica/friendica/issues/11415

Decided to still file this issue as this is such a cluster of issues, I prefer to keep things as specific as possible.

**Comment by annando** [comment]
I just tested, I cannot reproduce it.

**Comment by foss-** [comment]
Very strange. Still seeing the same issue here.

**Comment by foss-** [comment]
This is likely https://github.com/tuskyapp/Tusky/issues/3196 and related to outdated Android System WebView version which can happen on custom ROMs.
