### ISSUE TITLE
White pages since update to last dev version

### ISSUE THREAD

**Issue by johnassel** [friendica/friendica#12793]
- [X] I have searched open and closed issues for duplicates

### Bug Description
After updating to the latest dev version (commit d3acdd3) I'm getting a white page everywhere.
Interestingly no logs through PHP or Apache are created even when I try to force it with
ini_set('display_errors', true);
error_reporting(E_ALL);
in index.php.
In addition the requests are answered with HTTP 200 instead of e.g. 500.

Edit: Even the installer won't start after a fresh checkout.

### Steps to Reproduce

1.  checkout latest dev version
2.  get white pages everywhere

Actual Result:

Friendica shows white pages everywhere

Expected Result:

Working website

### Platform Info

Friendica Version: latest dev

Friendica Source: git

PHP version: 8.1.15

SQL version:

**Comment by johnassel** [comment]
I reverted to my backup from 11.2.2023  and Friendica works again. So something must have happened at the weekend which breaks Friendica (at least for me).

**Comment by annando** [comment]
It is possibly related to PR https://github.com/friendica/friendica/pull/12772

**Comment by johnassel** [comment]
Hmmm, the table config is there:

MariaDB [friendica]> SHOW TABLES;
+-----------------------------+
| Tables_in_friendica         |
+-----------------------------+
| 2fa_app_specific_password   |
| 2fa_recovery_codes          |
| 2fa_trusted_browser         |
| account-suggestion          |
| account-user                |
| account-user-view           |
| account-view                |
| addon                       |
| advancedcontentfilter_rules |
| apcontact                   |
| application                 |
| application-marker          |
| application-token           |
| application-view            |
| arrived-activity            |
| attach                      |
| cache                       |
| category-view               |
| collection-view             |
| config                      |
| contact                     |
| contact-relation            |
| conv                        |
| conversation                |
| delayed-post                |
| delivery-queue              |
| diaspora-contact            |
| diaspora-contact-view       |
| diaspora-interaction        |
| endpoint                    |
| event                       |
| fcontact                    |
| fetch-entry                 |
| fetched-activity            |
| fsuggest                    |
| group                       |
| group_member                |
| gserver                     |
| gserver-tag                 |
| hook                        |
| inbox-entry                 |
| inbox-entry-receiver        |
| inbox-status                |
| intro                       |
| item-uri                    |
| key-value                   |
| locks                       |
| mail                        |
| mailacct                    |
| manage                      |
| media-view                  |
| network-item-view           |
| network-thread-view         |
| notification                |
| notify                      |
| notify-threads              |
| oembed                      |
| openwebauth-token           |
| owner-view                  |
| parsed_url                  |
| pconfig                     |
| pending-view                |
| permissionset               |
| photo                       |
| post                        |
| post-activity               |
| post-category               |
| post-collection             |
| post-content                |
| post-delivery               |
| post-delivery-data          |
| post-history                |
| post-link                   |
| post-media                  |
| post-question               |
| post-question-option        |
| post-tag                    |
| post-thread                 |
| post-thread-user            |
| post-thread-user-view       |
| post-thread-view            |
| post-user                   |
| post-user-notification      |
| post-user-view              |
| post-view                   |
| process                     |
| profile                     |
| profile_field               |
| profile_field-view          |
| push_subscriber             |
| register                    |
| report                      |
| report-post                 |
| search                      |
| session                     |
| storage                     |
| subscription                |
| tag                         |
| tag-search-view             |
| tag-view                    |
| user                        |
| user-contact                |
| userd                       |
| verb                        |
| worker-ipc                  |
| workerqueue                 |
| workerqueue-view            |
+-----------------------------+
107 rows in set (0.003 sec)

Or am I missing something?

**Comment by johnassel** [comment]
Oh, and even when I try to install Friendica from scratch from a fresh checkout the white pages are staying. The installer does not even start.

**Comment by nupplaphil** [comment]
I'm on it

**Comment by johnassel** [comment]
Just do confirm it really is PR #12772:
- Updated to latest dev
- Checked out commit [a7b3949](https://github.com/friendica/friendica/commit/a7b3949ca0531328935dcd589f77ba4ab0c21ada) (the one before the PR): Friendica works
- Checked out commit [b168ff3](https://github.com/friendica/friendica/commit/b168ff3e1708fd1de4daaaeeabf3dea3fc293f69) (the PR): Friendica is broken

**Comment by johnassel** [comment]
Are there additional things to do to get this commit working?
Because when I'm pulling the newest commit the problem still exists.

Edit: I updated the addons, too.
Edit2: The addon "blockem" was the problem now:
`2023-02-20T14:28:35Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/social/addon/blockem/blockem.php line 128 {"exception":"ParseError: syntax error, unexpected double-quoted string \"/images/person-80.jpg\" in /var/www/social/addon/blockem/blockem.php:128\nStack trace:\n#0 /var/www/social/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle('conversation_st...', Array, Array)\n#1 /var/www/social/src/Content/Conversation.php(544): Friendica\\Core\\Hook::callAll('conversation_st...', Array)\n#2 /var/www/social/src/Module/Update/Network.php(82): Friendica\\Content\\Conversation->create(Array, 'network', 3, false, '`commented`', 3)\n#3 /var/www/social/src/BaseModule.php(238): Friendica\\Module\\Update\\Network->rawContent(Array)\n#4 /var/www/social/src/App.php(700): Friendica\\BaseModule->run(Object(Friendica\\Module\\Special\\HTTPException), Array)\n#5 /var/www/social/index.php(52): Friendica\\App->runFrontend(Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), Object(Friendica\\Content\\Nav), Object(Friendica\\Module\\Special\\HTTPException), Object(Friendica\\Util\\HTTPInputData), 1676903315.7725, Array)\n#6 {main}"} - {"file":null,"line":null,"function":null,"request-id":"63f38393bdfe9","uid":"628e06","process_id":1336043}`
Disabling it and it works now!
Thank you!

**Comment by MrPetovan** [comment]
Thank you, this error has been addressed in https://git.friendi.ca/friendica/friendica-addons/pulls/1357
