### ISSUE TITLE
When a mastodon post is edited and an image is exchanged, that post then shows on friendica with both images

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12809]
1. create mastodon post with image
2. edit mastodon post and remove image and add another image

**Currently**

This results with both images showing for the post when received on friendica.

**Expected**

Edits should be taken into account and only the new images should be shown and the image which got removed should indeed also be removed from the post received on friendica.

**Comment by annando** [comment]
Should be fixed with pr https://github.com/friendica/friendica/pull/12851
