### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12808]
Hi all, did a fresh install of Friendica using Ubuntu 22.04 LTS and using php 8.2. I had a few issues, but it looks pretty good. However, I just got this error after logging in:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/38843638/219804997-0a95d272-25da-4797-9c5c-abf3124558f4.png">
I think all my permissions are correct. So not sure what is happening.

**Comment by MrPetovan** [comment]
What is you web server/phpfpm user? What do the permissions look like in `view/smarty3/compiled`?

**Comment by jakedfw** [comment]
everything in the Friendica director is user www-data.
How can I find the phpfpm user?

**Comment by jakedfw** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/38843638/219816454-d68b2646-f2cf-431e-a915-3168b00a9fa8.png">

**Comment by MrPetovan** [comment]
I’m not very familiar with phpfpm but it should be set in the config file, on Debian-like it would be in `/etc/php`.

What about `view/smarty3/compiled`?

Disk isn’t full? Not running out of inodes?

**Comment by jakedfw** [comment]
That was it. Very odd. There were a few directories in view/smarty3/compiled that were root owner. Not sure how that happened. Thank you!
