### ISSUE TITLE
Can't follow Friendica actors

### ISSUE THREAD

**Issue by silverpill** [friendica/friendica#12815]
Hello, I'm sending `Follow` activity from [Mitra](https://codeberg.org/silverpill/mitra) server to Friendica server but it doesn't reply with `Accept`.
At first I thought that there is a problem with my JSON-LD context so I changed it to pass validation at https://json-ld.org/playground/. It didn't help.

Any ideas? Here's my `Follow` activity:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    "https://w3id.org/security/data-integrity/v1",
    {
      "MitraJcsRsaSignature2022": "mitra:MitraJcsRsaSignature2022",
      "mitra": "http://mitra.social#",
      "proofPurpose": "sec:proofPurpose",
      "proofValue": "sec:proofValue",
      "verificationMethod": "sec:verificationMethod"
    }
  ],
  "actor": "https://mitra.social/users/silverpill",
  "id": "https://mitra.social/objects/01866c75-84b4-79ef-df49-53f39af15eac",
  "object": "https://venera.social/profile/fediversenews",
  "proof": {
    "created": "2023-02-20T01:34:49.091030169Z",
    "proofPurpose": "assertionMethod",
    "proofValue": "z3DR9jxVFSiB3L4MrnQLdkYV9xjRSWXy3Y27pRCR4EgpRWHkigDbgGayPSrUtukGjNS6GNPzKHsDwhtJmKLeDnb1yh79NEFyp7ygWQcwBs8jUQo4ELTDeCwXjDwPFHVktcr2XUQhxmzHvqr8u4pokPRwdCiVgGAhKN7mg7HmZgpNn2HXXzEcSVgp9uz3q9oJAn7t2bGVPCPnmZg4Q6jzjchHSdZ2aFrjWzabgCbQhUo1LT11pStv9rKoXgvUTM7JSiCfc9Do6p4Ft3h7CLYMEUZ5PBEmiRfNmByD47HJtwCsWxWusv6XBwcSkmW9tncUAwq5ZJ4kY17hUb7YKzFZLaykDC55vxo",
    "type": "MitraJcsRsaSignature2022",
    "verificationMethod": "https://mitra.social/users/silverpill#main-key"
  },
  "to": [
    "https://venera.social/profile/fediversenews"
  ],
  "type": "Follow"
}
```

**Comment by tallship** [comment]
I can also report this behavior as being able to be occurring.

This was also tested against my account at Venera, where I've configured connection requests to automatically be approved, yet the expected behavior is not occurring, she the requests aren't waiting for approval either.

**Comment by annando** [comment]
Sorry for replying late. I just tested that JSON above. Our JsonLD compactor has got problems with the `https://w3id.org/security/data-integrity/v1` context.

I created a workaround in which I applied some changes to that context, so that our parser doesn't complain.

**Comment by silverpill** [comment]
Thank you @annando !
There's another unusual context that this software adds to actor objects: `https://w3id.org/security/multikey/v1`. Could it also cause problems?

**Comment by annando** [comment]
I need some data, (like in this post) so that I can check it on my system..

**Comment by silverpill** [comment]
I see you already added a workaround for multikey context, but if you still need testing data you can fetch the `https://mitra.social/users/silverpill` actor.

Thanks again!

**Comment by annando** [comment]
There's still a problem with our JsonLD validator. I have to reformat the whole context document.

**Comment by silverpill** [comment]
Both contexts are related to Verifiable Credentials Data Integrity standard. If these context documents are not valid, workgroup participants may fix them. I believe the relevant repositories are:
- https://github.com/w3c/vc-data-integrity for `https://w3id.org/security/data-integrity/v1`
- https://github.com/digitalbazaar/multikey-context/ for `https://w3id.org/security/multikey/v1`

**Comment by annando** [comment]
I can imagine that the documents are valid - but that our parser doesn't work well.
