### ISSUE TITLE
WSOD after git pull

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#12822]
- [x ] I have searched open and closed issues for duplicates

### Bug Description
after the git pull just now 

after the [git pull ](https://github.com/friendica/friendica/commit/cef063e4fd07e673138186c1726887c3c18806ef)just now I have a WSOD and the following error message in the logs 

> 2023-02-20T14:11:48Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:11:50Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:11:58Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:12:00Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:12:04Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:12:04Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:12:06Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:15:34Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:15:36Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:17:17Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:17:22Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>
> 2023-02-20T14:17:24Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected double-quoted string "/images/person-80.jpg"" at /var/www/html/addon/blocke>

### Platform Info

Friendica Version: 2023.03-dev - 1515

Friendica Source:  git

PHP version: 8.1.2-1ubuntu2.9

SQL version: MariaDB 10.6.11

**Comment by annando** [comment]
Please disable blockem.

**Comment by sekretaerbaer** [comment]
Thx ... worked

**Comment by SpcCw** [comment]
@annando - I have got the same problem however after I tried disabling "blockem" (by removing the checkmark in the addon list) it disappeared from the list completely but I still get the same error.

![image](https://user-images.githubusercontent.com/35988439/220161996-1fa3f3f2-02c2-4e6b-8bc7-49febf27b105.png)

Can I disable it in some other way?

UPD: renaming the directory to blockem2 did the trick.

**Comment by MrPetovan** [comment]
`blockem` is now unsupported so it won't show in the list of addons if it wasn't previously activated.

**Comment by MrPetovan** [comment]
Thank you for the report, the error has been addressed in https://git.friendi.ca/friendica/friendica-addons/pulls/1357
