### ISSUE TITLE
[frio] mobile: use full width for spacing of post interaction icons

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12835]
**Currently**

Post interaction icons are clumped up on the left side unter a post on mobile.

Friendica frio mobile:
![2](https://user-images.githubusercontent.com/5708172/220635042-0ff5e2d8-a934-4656-bcb1-4e41da3a694f.png)

**Expected**

No need to make interacting with posts unnecessarily hard for users. Spreading the icons equally over full width will make for a symmetric layout and improve UX by making post interaction much easier.

Twitter mobile:
![4](https://user-images.githubusercontent.com/5708172/220636821-0b08c9d0-e29c-4b63-bdaa-09c19e4b80d9.jpg)

**Comment by damianwajer** [comment]
I have a work-in-progress branch related to this since [my first changes](https://github.com/friendica/friendica/pull/12699). I will create a pull request soon with before/after examples.

**Comment by matthiasmoritz** [comment]
Looks very nice for Posts, but Not on Calendar Items

![24280CFF-D634-444F-ACFE-5069D3D1F913](https://user-images.githubusercontent.com/1984982/222809898-08eec6ca-7548-4b13-a835-23f2a6764cad.png)
