### ISSUE TITLE
Share-it button (or link) for Friendica 

### ISSUE THREAD

**Issue by lindenbl** [friendica/friendica#1283]
Many web-pages have buttons so the viewer can easily share the URL of the page with his/her friends using an existing social network account. I suggest this feature so that these links can be created in this manner:

On the web-page:
`<a href="http://friendica.com/share/?url=http%3A%2F%2Fwww.example.com%2Fgo%2Fsomewhere&title=The%20Friendica%20Example&message=Some%20text%20here">
<img src="http://www.example.com/icons/friendica_icon.png">
</a>`

When the Friendica user click this icon, he/she will be forwarded to his/her profile with a pre-filled message box. 

The use of the friendica.com website may be discussed; the problem is that the programmer of the web-page cannot know the instance / the URL of the visiting Friendica user.

**Comment by annando** [comment]
We can use the functionality for Diaspora: http://sharetodiaspora.github.io/

We just have to make some changes to friendica to make that work, I guess.

**Comment by annando** [comment]
I've done a pull request for that: https://github.com/friendica/friendica/pull/1315

**Comment by tobiasd** [comment]
Seems to be working but maybe we should fork it to use a friendica logo instead of the asterix and a list of the bigger friendica nodes for the preselection?

**Comment by annando** [comment]
We shouldn't fork that project but making pull requests for it.

**Comment by tobiasd** [comment]
I wont search a link to share a blog entry in friendica under the asterix of D*... also mixing of D* and ~f nodes in the pre-selection of big nodes seems counter intuitive for me.

**Comment by friendica** [comment]
https://github.com/duthied/Friendika-Bookmarklet

**Comment by annando** [comment]
I think we have to work together. It doesn't make a sense to have a share button for each and every network. This is only confusing.

**Comment by annando** [comment]
@friendica I saw this bookmarklet. But I don't like the idea that a user has to enter his credentials on a foreign system. I won't do that for security reasons.

**Comment by annando** [comment]
I think that we can close the issue since we now support this share functionality from Diaspora. Does anyone disagree?

**Comment by poVoq** [comment]
For reference: https://github.com/distributopia/share-connect-support
