### ISSUE TITLE
Error in Help page on BBCode

### ISSUE THREAD

**Issue by EubieDrew** [friendica/friendica#12846]
You can see this at the very bottom of https://venera.social/help/BBCode

[url=https://venera.social/photos/threadblogs/image/220074420263fb77f5e5cb2900337996][img=https://venera.social/photo/220074420263fb77f5e5cb2900337996-1.png][/img][/url]

"You can change all " text needs to be moved to precede the [style=] code.

Sorry if I am bringing this up in the wrong location. Where do I give feedback on help pages?

thanx

   --- Eubie

**Comment by EubieDrew** [comment]
clean link to image --> https://venera.social/photo/220074420263fb77f5e5cb2900337996-1.png

**Comment by MrPetovan** [comment]
Feedback here is perfect since these page are saved in the git repository 👍
