### ISSUE TITLE
[Markdown Addon] editing a markdown post will change the post to BBCode (and result in the expected formatting havoc)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12842]
This is Friendica, version 2023.03-dev that is running at the web location https://pirati.ca. The database version is 1516/1516, the post update version is 1507/1507.

**Reproduce**

1. enable Settings > Add-ons > Markdown Settings > Enable Markdown parsing
2. create a post with markdown and a list in the form of
```
This is:

- some
- amazing
- list
```
3. share post
4. edit post and add a word (no need to even touch the list)

**Currently**

This results in a malformed list, since friendica changes post formatting to BBCode for unknown reasons 😢.

**Expected**

Don't destroy users posts and stick with markdown, even when editing an existing post.

**Comment by HankG** [comment]
Doing some testing this seems to be driven by the Markdown addon not recognizing that it is processing BBCode on the second pass. In the test, the original passed in status was:

```
This is:

- some
- amazing
- list
```
![image](https://user-images.githubusercontent.com/1683691/221367311-65fe145e-9898-41f8-9d99-08347edd1372.png)


When the edit function came back the text it was passed back was:
```
This is:[list][*]some[*]amazing[*]list[/list]
```

On the second time through it doesn't realize those start/end asterisks are part of BBCode already so processes them as markdown again:

![image](https://user-images.githubusercontent.com/1683691/221367349-5774afbc-d33d-4b8d-bdfb-9a595bd9f9c0.png)

The text returned to the editor the second time, which I assume is what is stored in the DB is:
```
This is:[list][[i]]some[[/i]]amazing[*]list[/list]
```

These behaviors don't happen on a Friendica instance running stable and develop that aren't running the addon.

**Comment by annando** [comment]
Internally we always store the content in BBCode.

**Comment by HankG** [comment]
> Internally we always store the content in BBCode.

Yup. I'm guessing the addon needs to intercept the call back and replace markdown similar markup back to markdown? Either way it is an addon bug not a Friendica bug.

**Comment by annando** [comment]
I won't change it back to markdown. Problem is that not everything can be done via markdown.

**Comment by MrPetovan** [comment]
In this case it sounds more like a HTML to BBCode issue.

**Comment by AndyHee** [comment]
I also experienced this bug while using this addon.

**Comment by foss-** [comment]
Sadly the patch does not resolve the issue with broken lists from markdown posts after editing.

New post

```
This 

- is
- a markdown
- list
```

editing that post, results in:

```
This
[ul]
[*]is
[*]a markdown
[*]list
[/ul]
```

once saved, the post is showing a broken list:
![1](https://user-images.githubusercontent.com/5708172/226596930-172d83de-935e-49dc-b881-e2dbba1e3a8a.png)

**Comment by MrPetovan** [comment]
I forgot that Markdown ignores single new lines, which means even formatted correctly for humans, a BBCode list still appears like one line for Markdown which rightfully applies the italic based on the asterisks.

The Markdown addon now needs to escape all BBCodes tags before applying the Markdown conversion.

**Comment by annando** [comment]
I'm thinking about alternatives. For example I'm thinking about an additional field for the source that contain the Markdown. This is then converted into the body. And upon editing, the user would edit the original source. I would use this field as well for receiving HTML and Markdown (at least for testing purposes).
