### ISSUE TITLE
Increase readability of longer contents

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12856]
### Describe the feature you'd like

https://post.news has an interesting feature that works well for longer posts in Friendica.

Classification: Under the heading News, newspaper articles are published on post.news. These are usually complete articles from the respective press providers.

What Friendica can do: The special feature is that clicking on "Read" does not simply open the article, but opens a modal dialogue that covers the screen and into which the article is loaded. For the user, this creates a clear focus on the content. Distractions are avoided. Since the modal is somewhat wider, readability is greatly aided.

Perhaps it is also a good way for Friendica to better highlight the features of the Macroblog and stand out from other applications.

![Screenshot 2023-03-01 at 19-09-42 Post - Feed](https://user-images.githubusercontent.com/44441246/222229757-6c75f271-183b-45ed-a9a5-a825645293d8.png)

![Screenshot 2023-03-01 at 19-09-52 Post - Feed](https://user-images.githubusercontent.com/44441246/222229799-c90840da-c880-4b68-bc88-afc494a4bee3.png)

**Comment by MrPetovan** [comment]
About 10-15 years ago, I learned that the maximum comfortable screen reading width is about 700 pixels (or equivalent since they have been shrinking). The current reading width of Friendica posts is about 640 pixels so there’s little room for change in that regard without overshooting the optimal width.

As for the clutter, it’s another story but I would like to stress we wouldn’t get anything out of a wider post display.

**Comment by AndyHee** [comment]
In the olden days of text consoles it was said 80-120 characters was an optimal width for reading. Anything above or below this makes reading on screen awkward.


A clutter-free "reader view" of course (like firefox provides `Ctrl + Alt + R`) would be great. But shouldn't the UI be designed like this in the first place?

**Comment by AndyHee** [comment]
>  current reading width of Friendica posts is about 640 pixels

Apparently, as typography tells us, 640 pixels equals 80 characters. Nice! [ [*]](https://www.unitconverters.net/typography/pixel-x-to-character-x.htm)

**Comment by MrPetovan** [comment]
Friendica needs to expose the many features it provides, so there are some limits to how much we can declutter by default.

**Comment by AndyHee** [comment]
So true. But I'd say we still have quite a bit to go for achieving a minimalist look that subtly exposes the important parts.

I admit that might be my own preference. I noticed some people seem very comfortable with bold buttons and big threading lines. 😊

**Comment by loma-one** [comment]
No change is currently being considered. Therefore closed here.
