### ISSUE TITLE
Decouple activity buttons rendering from conversation rendering

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#12859]
I try some improvement for the frontend.

And i need a little hint, how to build new endpoints to query for example for the likes/dislikes/shares of a posting or a comment.

Something like https://<instance>/api/bla/foo/get_responses?item=123456789&verb=like (the id of posting or comment) 
which returns a snippet of html-code, i can add/replace per jquery on the right place.

**Comment by MrPetovan** [comment]
First of all, thank you for your interest.

Unfortunately, at the moment the display of the action button is extremely tightly coupled with the general display of conversations, so we can't easily render just that part at the moment, but it's something worth exploring.

**Comment by annando** [comment]
I would love seeing a complete new way to perform activities.

**Comment by xundeenergie** [comment]
I see, it is rendered all at once... 

But i separated the buttons functionality and updating successfully from updating the whole page. 
When i click to like or dislike, my buttons are updated in dependence of the response from the post-request. 

But allow me this question please... is it this complicated, to create a new endpoint with a query-interface to the database for only one item/posting/comment to get only the responses for it?

**Comment by annando** [comment]
Endpoints are super easy, since we encapsulate all these activities.

**Comment by MrPetovan** [comment]
This part is easy. Rendering them, a little less so.

> But i separated the buttons functionality and updating successfully from updating the whole page.
When i click to like or dislike, my buttons are updated in dependence of the response from the post-request.

Where so?

**Comment by xundeenergie** [comment]
I just modified the function doActivityItemAction in frio/js/theme.js to this code

```
function doActivityItemAction(ident, verb, un) {

  _verb = un ? 'un' + verb : verb;
  $('#like-rotator-' + ident.toString()).show();
  $.post('item/' + ident.toString() + '/activity/' + _verb)
  .success(
    function(data){
      console.log("data.status: " + data.status);
      if (data.status == "ok") {
        console.log("connection: " + data.status);
        $('#like-rotator-' + ident.toString()).hide();
        if (verb.indexOf("announce") === 0 ) {
          console.log("announce")
          if (data.verb == "un" + verb) {
            $("button[id^=shareMenuOptions-" + ident.toString() + "]" ).removeClass("active");
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).attr("onclick", "doActivityItemAction(" + ident +", '" + verb + "', " + false + ")").change();
          } else {
            $("button[id^=shareMenuOptions-" + ident.toString() + "]" ).addClass("active");
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).attr("onclick", "doActivityItemAction(" + ident +", '" + verb + "', " + true + ")").change();
          }
        } else {
          console.log("likes")
          if (data.verb == "un" + verb) {
            console.log(data.state);
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).removeClass("active");
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).attr("onclick", "doActivityItemAction(" + ident +", '" + verb + "', " + false + ")").change();


          } else {
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).addClass("active");
            $("button[id^=" + verb + "-" + ident.toString() + "]" ).attr("onclick", "doActivityItemAction(" + ident +", '" + verb + "', " + true + ")").change();

          }
          $("button[id^=" + verb + "-" + ident.toString() + "]" ).button('refresh');
        }
      } else {
        console.err("No connection to host");
      }
  })
  .error(
    function(data){
      console.log("POST unsuccessfull " + data.toString());
    });

}
```

it is a first try.

And the templates have to be modified a little bit... just remove `data-toggle="button"` in every occurance in like_noshare.tpl and wall_thread.tpl.
data-toggle makes a button toggling everytime you click it. No response from query is possible. So i removed it, and now i can set class independent from bootstrap only depending on response of post-request.

**Comment by xundeenergie** [comment]
This updates only the buttons. 
On next ping-run, the share/like/dislike-users get updated. But with an endpoint, which delivers these users, i can render and update this part in the same function.
This should be as easy as...

**Comment by xundeenergie** [comment]
I don't know, how to send a warning, which is displayed... 

i want to send a notification, if no connection to the server is possible, when clicking like or share, so that the user gets notificated, that the like-button works, but not the connection to the backend.

Where do i find, how to do this?

**Comment by MrPetovan** [comment]
In order:
- Your code is working, but it's only updating part of what changes when a like is registered. We also show who liked or reshared any given post.
- For asynchronous notifications, we are using `jGrowl`, here's our main use case, coming from the background poller: https://github.com/friendica/friendica/blob/180b81c6e74bdc8d677f447fe796fb10783c96dd/view/js/main.js#L360-L365

**Comment by xundeenergie** [comment]
I know, it updates only the buttons, not more.

So i asked for an endpoint to query likers/dislikers/shareres from a posting/comment 😊

**Comment by MrPetovan** [comment]
Yeah, I understand the need for the endpoint, but it would have to render the list in HTML the way we do in complete posts, which is tricky to extract from the whole conversation rendering.

**Comment by xundeenergie** [comment]
The code is not that difficult... i think.

What i have to know... first i see a list of <a href.. with contact-page and the displayname in a announce-list (or like-list).

When i hover over such a name, the <a>-tage get expanded with "data-awaiting-hover-cars", "data-original-title"... does this happen in case of bootstrap automagical, or do you add some events on it. Because i see no events on this <a>s. 

If this happens automagical from bootstrap, then i think i only need the following from the api:

- list of contact/conversation link (relative... they look all like "contact/12344566/conversations" 
- display-name 
- rendered text in language of the user (for example: "20 Personen haben dies geteilt") 
- if important and server-generated... the id of the announce/like/dislike-list

I think, if i get this, i can build a jquery-function which creates the single or both links, or the list and the fakelink-span to open the list, and add all of them to the corresponding field.

**Comment by MrPetovan** [comment]
This is the HTML structure the endpoint would generate for the frio theme:
```html
<div class="wall-item-responses">
    <div class="wall-item-like" id="wall-item-like-5385575">
        <p><button type="button" class="btn btn-link fakelink" onclick="openClose('likelist-5063255');">32 people</button> like this</p>
        <p class="wall-item-like-expanded" id="likelist-5063255" style="display: none;"><a href="https://chaos.social/users/zerody">Zerody</a>, <a href="contact/redir/452564" class="sparkle">Marek Bachmann</a>, <a href="https://mstdn.social/users/rorystarr">Astrobach :breadified:</a>, <a href="contact/redir/384604" class="sparkle">Jonathan Lamothe</a>, <a href="contact/redir/377735" class="sparkle">anubis2814</a>, <a href="https://mastodon.social/users/meercat0">Meercat  ✅</a>, <a href="https://mastodon.social/users/Jolg42">Joël 🍵</a>, <a href="https://berserker.town/users/thor">Thorwegian ❄️</a>, <a href="https://blimey.social/users/alan">Lord Alan of Chaol Ghleann</a>, <a href="https://diaspora.permutationsofchaos.com/u/debo">debo</a>, <a href="https://pleroma.nylarea.com/users/NiLace">NiLace</a>, <a href="contact/redir/262204" class="sparkle">Spencer</a>, <a href="https://diasp.org/u/jcsesecuneta">♾️ 스노 (雪亮 Yuki) 🔏 ✳</a>, <a href="https://mastodon.sdf.org/users/jdarnold">Jonathan</a>, <a href="contact/redir/172077" class="sparkle">Marco R.</a>, <a href="https://diaspora.glasswings.com/u/muse">Muse</a>, <a href="https://tabletop.social/users/genevieve">genevieve</a>, <a href="https://tech.lgbt/users/testoceratops">Burn This Dyspho Out 🐺</a>, <a href="https://tenforward.social/users/SilveringOfRose">SilveringOfRose (In Detail)</a>, <a href="https://social.lol/users/stu">Stu :prami:</a>, <a href="contact/redir/29" class="sparkle">Montag</a>, <a href="https://federation.ninetiesmysteri.es/users/masstransitkrow">Eric Shields | 🅜assTransitKrow</a>, <a href="https://kolektiva.social/users/cscott">C. Scott Ananian (he/him)</a>, <a href="https://mastodon.radio/users/k2za">k2za</a>, <a href="https://fosstodon.org/users/ryandaniels">Ryan Daniels ~# :idle:</a>, <a href="https://pleroma.soykaf.com/users/lnxw37a2">Linux Walt Alt (@lnxw37a2) {3EB165E0-5BB1-45D2-9E7D-93B31821F864}</a>, <a href="https://mastodon.social/users/colocracy">Colocracy</a>, <a href="https://sysad.org/u/mnw">Marcus</a>, <a href="https://mindly.social/users/JoeB1">JoeBWun</a>, <a href="https://rheinneckar.social/users/andreas">Andreas Rilinger</a>, <a href="https://social.pinheirodeabrantes.pt/users/joao">João Pinheiro</a> and <a href="contact/redir/352226" class="sparkle">Scifijunkie</a> like this.</p>
    </div>
    <div class="wall-item-dislike" id="wall-item-dislike-5385575"></div>
    <div class="wall-item-announce" id="wall-item-announce-5385575">
        <p><button type="button" class="btn btn-link fakelink" onclick="openClose('announcelist-5063255');">12 people</button> reshared this</p>
        <p class="wall-item-announce-expanded" id="announcelist-5063255" style="display: none;"><a href="https://mstdn.social/users/rorystarr">Astrobach :breadified:</a>, <a href="contact/redir/384604" class="sparkle">Jonathan Lamothe</a>, <a href="https://mastodon.uy/users/jorge">soloojos (Mastodon Uruguay)</a>, <a href="https://pleroma.nylarea.com/users/NiLace">NiLace</a>, <a href="https://diasp.org/u/jcsesecuneta">♾️ 스노 (雪亮 Yuki) 🔏 ✳</a>, <a href="https://tenforward.social/users/SilveringOfRose">SilveringOfRose (In Detail)</a>, <a href="https://social.lol/users/stu">Stu :prami:</a>, <a href="https://nerdpol.ch/u/jayfkk">Ninja FKK</a>, <a href="https://federation.ninetiesmysteri.es/users/masstransitkrow">Eric Shields | 🅜assTransitKrow</a>, <a href="https://mastodon.social/users/meercat0">Meercat  ✅</a>, <a href="https://mindly.social/users/JoeB1">JoeBWun</a> and <a href="https://mstdn.social/users/fediversefan">In The Fediverse</a> reshared this.</p>
    </div>
</div>
```
This is currently generated inside the `view/theme/frio/templates/wall_thread.tpl` template:
```
<div class="wall-item-responses">
{{foreach $item.responses as $verb=>$response}}
	<div class="wall-item-{{$verb}}" id="wall-item-{{$verb}}-{{$item.id}}">{{$response.output nofilter}}</div>
{{/foreach}}
</div>
```
`$response.output` is another HTML snippet that is generated in `src/Object/Post.php`:
https://github.com/friendica/friendica/blob/11527761d7783afa59ccc081209b83d04abc5c33/src/Object/Post.php#L313-L319

`$conv_responses` is generated in `src/Content/Conversation.php`: https://github.com/friendica/friendica/blob/11527761d7783afa59ccc081209b83d04abc5c33/src/Content/Conversation.php#L121

This is where is becomes complicated because you need to retrieve all the posts that are direct children of the post you're considering.

**Comment by xundeenergie** [comment]
I've just tried the following:

Editing the DOM of a like in dev-tools. 
added a <p> and <a> with the href="contact/123455/conversations" from a user i know. 
Text is "blafoo"

And then i hoverd over the new link in browser and friendica shows me the correct hovercard from the user.

THAT is great.

**Comment by xundeenergie** [comment]
I just did a pull-request for a first part of functionality... 

https://github.com/friendica/friendica/pull/12873

It fixes the annoying behaviour, that the timeline jumps somwhere around after a like or share... 
and videos are not disrupted, when you watch them and like or share them. 

The update of likers/sharerers list will follow, when i get an idea of creating an endpoint to get likers/dislikers and sharerers of a comment/posting with relativ url and name.
