### ISSUE TITLE
Request storm this morning / limiting outgoing connections?

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#12860]
Hi
today I have a **huge** number or errors in my nginx logs. The main message is:
`2023/03/02 02:06:50 [alert] 354465#354465: 768 worker_connections are not enough`
together with
`2023/03/02 02:06:50 [alert] 354465#354465: *49886 768 worker_connections are not enough while connecting to upstream, client: 2001:41d0:d:218a:a7d:a7d:82fc:d43, server: ****.****.ch, request: "GET /photo/profile/ne20002.png?ts=1668185910 HTTP/1.1", upstream: "http://[fd42:0:0:40::144]:8012/photo/profile/ne20002.png?ts=1668185910", host: "****.*****.ch"
`
Doing some analysing I see this on my dns (pi-hole):

![grafik](https://user-images.githubusercontent.com/39007279/222483185-b8b86d55-0533-4832-9831-0b13bd133c9a.png)

So there is a huge number of outgoing and incoming requests. 

According to the nginx logs there is no external client with more than 29 requests per second and according to the log there is a (again) huge number of incoming requests (~32000) between 02:06:50 and 02:52:41. After this, no more errors logged. Friendica works without problems and there is no entry in the Friendica log.

I'm unsure if this is caused by outgoing connections started from my Friendica for whatever reason at 02:06 or if this started by incoming requests and the dns is caused by some resolving Friendica is doing.

I take this as a reason to set up my reverse proxy's limits. But for the outgoing requests: is there any way to limit the number of outgoing requests (mine is a small instance)?

**Comment by AndyHee** [comment]
So what's a reasonable setting for the limits of the reverse proxy?

Regarding the control of outgoing requests, would it make sense to first look at your worker settings?

**Comment by ne20002** [comment]
I already had a rate limit on requests. I now needed to set up limit on parallel connections as well (so reaching the limit will answer overhelming requests with 429). 
When the issue occured, I had by 1400 parallel connections from nearly the same amount of servers (which is way more of what I usually get). All valid Fedivers requests ... This is kind a hickup and I wonder what caused it.
My worker settings are default.
