### ISSUE TITLE
LDAPAuth does not work with API

### ISSUE THREAD

**Issue by esackbauer** [friendica/friendica#1286]
When I use the API, I cannot logon with LDAPAuth Plugin. 
However login is successful if I use the password stored with the user in the friendica database.
It seems the API is not aware of the LDAPAuth plugin.

Tested with:
https://friendica.flyar.net/api/statuses/home_timeline.json?count=1

**Comment by silke** [comment]
Hi! 

I'm not sure if I get what you are trying to do... On your instance I see an authentication request from the webserver. How is that related to Friendica's LDAP plugin? With the plugin I would expect Friendica (and not Apache) to pass on the credentials to ldap.

Also, can you please provide some more details? What does your ldap config in .htconfig.php look like?

**Comment by silke** [comment]
Hm, yeah, if my config is okay, I can confirm that Friendica doesn't seem to react to the plugin. When I look further, I'm wondering if that plugins was made to support bind via a tls connection... What steps did you do?

I tried:
* to install php5-ldap
* to put the ldap server's certificate to the friendica instance
* to load it with putenv in htconfig
* to configure the plugin

**Comment by esackbauer** [comment]
Hi Silke,

as I wrote the LDAP plugin is working properly for using Friendica through the normal web interface.
However when I use an app like "Friendica mobile" for Windows Phone, which uses the Friendica API, I cannot logon with my LDAP credentials.
I would expect, that if the LDAP plugin is working properly for my web page, it also would do for the API provided by my installation. The API just looks for credentials in the Friendica database, and not via the properly configured ldapauth plugin.

**Comment by fabrixxm** [comment]
The 'authenticate' hook is not called by `api_login()`, so ldapauth plugin can't say a word on authentication process...
I'm on it, but I don't have any LDAP to test the code...

**Comment by fabrixxm** [comment]
@esackbauer can you replace your `include/api.php` with [this version](https://raw.githubusercontent.com/fabrixxm/friendica/b45a4b398be2324a39ee23de07864b797b60a64b/include/api.php) and check if you can login on ldap?

**Comment by esackbauer** [comment]
Yes, it works!

**Comment by tobiasd** [comment]
can we close this issue now?

**Comment by fabrixxm** [comment]
yep: "it works" :-)
