### ISSUE TITLE
Core\Worker\Exception\ProcessPersistenceException: "Cannot save process with PID nnnnn"

### ISSUE THREAD

**Issue by tim-pearce** [friendica/friendica#12871]
- [x] I have searched open and closed issues for duplicates

### Description

worker.php fails with 'ProcessPersistenceException' on line 87 of src/Core/Worker/Repository/Process.php
This is a fresh install on a cPanel host. I had to change the line 'php bin/worker.php' to '/usr/local/bin/php bin/worker.php' to get the php-cli (Checked the error in worker.php. Added a bit to its error message to find why it did nothing.)

### Steps to Reproduce

1.  Install friendica
2. Turn on logging
3.  Create cron job to run bin/worker.php (every 5 minutes)

Actual Result:

'Administration - Summary' tells me 'The worker process has never been executed. Please check your database structure!' 
Get the error in the log every 5 minutes.
Same thing happens if I open a terminal on the server and run it from there.

Expected Result:

bin/worker.php should run

### Platform Info

Friendica Version: 2023.01

Friendica Source: Github release

PHP version: 7.4

SQL version: 10.6.12-MariaDB

**Comment by tim-pearce** [comment]
I have solved the problem on my system. The field in the 'process' table for 'hostname' is 32 characters and my host has a name which is 33 characters long. Increased the field length and it now works.

**Comment by MrPetovan** [comment]
Interesting, thank you for the report and congratulations on the self-fix!
