### ISSUE TITLE
Return only bb-code link on image-upload

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#12888]
### Is the feature request related to a problem? Please describe.

I built the new image-upload feature. And there i tried the url `/media/photo/upload?response=json&album="` to upload the image.
On  this i get only a "status: ok" or so back... 
When i leave the response-parameter away, i get the whole website-base (headers, scripts... MUCH htmal-code) and as content only the bb-code for the image/url to the just uploaded image, which i can paste bare as it is into the textarea.
I have to parse the html response and grad in the DOM for the right field to get its content... 

### Describe the feature you'd like

I want with `response=json` a second field with the formatted url or another response with `response=url` parameter only the text for the bb-encoded url to the new uploaded image. So the traffic is much less than now. only the few characters.

Something like this:
```
{ status: ok, 
bb: [url=http://...[img]asldklsj[/img]][/url], 
originalfilename: blafoo.jpg, 
album: "Albumname",
deleteLink: "http://....."
...
}
```

### Describe alternatives you've considered

--

### Additional context

**Comment by MrPetovan** [comment]
The output of `/media/photo/upload` is controlled in [`src/Module/Media/Photo/Upload.php:236-253`](https://github.com/friendica/friendica/blob/705e86f8c3fd3edf755a328a5fcac3188796888e/src/Module/Media/Photo/Upload.php#L236-L253)

It looks like it could work as you expect without the `response=json` parameter if you add the following line at the end of the `return` method:
```php
DI::page()->exit($this->response->generate());
```
Don't forget the `use Friendica\DI;` line at the top of the file!

**Comment by annando** [comment]
You could also possibly use the API functions for picture upload.

**Comment by MrPetovan** [comment]
The advantage of the media/photo/upload is that authentication is automatic through session, I’m not sure the API would (or should) do the same.

**Comment by xundeenergie** [comment]
i tried it.... just use the api url... it asks me for authentication.

so, where can i get the auth-bearer from? 

It should work like this, i think:
https://stackoverflow.com/questions/43908977/how-to-include-the-header-access-token-to-the-dropzone-config
