### ISSUE TITLE
Friendica server missing in the Friendica server directory

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12897]
My Friendica server on meld.de does not show up in the Friendica server directory (https://dir.friendica.social/servers) anymore, even though the open registration is set up on meld.de.

**Comment by MrPetovan** [comment]
Thank you for the report, I've successfully manually polled your server and it should appear shortly, albeit with a low health score if it's been on the `develop` branch because of a bug in the output of `/friendica/json`.
