### ISSUE TITLE
stop play

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1290]
[Contenido incrustado - recarga la página para verlo]

[Embedded content - reload the page to view] This appears when you give me like a video playback.

It is annoying.

**Comment by silke** [comment]
Hi mama21mama, 
hm... I think this is not related to friendica itself, but it might be browser config issue, no?
An working example for youtube: Make your browser request the html5 version of youtube. Allow javascript. Play a video directly in your friendica timelime.

**Comment by fabrixxm** [comment]
Its friendica if i remember correctly that remove embeds when timeline si reloaded via json. I dont remember exactly why, i think was some browser issue....

Il 24 gennaio 2015 19:42:20 CET, Silke Meyer <notifications@github.com> ha scritto:
>Hi mama21mama, 
>hm... I think this is not related to friendica itself, but it might be
>browser config issue, no?
>An working example for youtube: Make your browser request the html5
>version of youtube. Allow javascript. Play a video directly in your
>friendica timelime.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/friendica/friendica/issues/1290#issuecomment-71331515

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by fabrixxm** [comment]
In fact is related to friendica. direct embeds are removed when network page is updated via ajax (eg, when like is clicked).
I don't remember exactly why, but I think was a workaround for some kind of browser bug
As per [git blame](https://github.com/friendica/friendica/blame/0e9c8f6f1a0af4b613e468aa2a74ae9a268038d2/mod/update_network.php#L25) the code has been added by @fermionic
