### ISSUE TITLE
[frio] new upload area in post composer should take dark and black color scheme into account

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12924]
The new upload area does not take dark and black mode into account. Would be nice to have the new area reflecting the selected color scheme.

![upload](https://user-images.githubusercontent.com/5708172/226575453-57e385d5-2b7c-4001-9e74-13db868b0005.png)

**Comment by MrPetovan** [comment]
Paging @xundeenergie

**Comment by foss-** [comment]
Follow-up: https://github.com/friendica/friendica/issues/12944
