### ISSUE TITLE
[twitter] Quote-sharing Twitter posts is broken?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12929]
In 2023-03rc, quote-resharing Twitter posts doesn't seem to work anymore. Tried to quote this post...

![twitter-1](https://user-images.githubusercontent.com/685879/226819188-d278d1c8-26cc-479b-9504-2b712eb70f8c.png)

... which ended up in this message in my profile ...

![twitter-2](https://user-images.githubusercontent.com/685879/226819195-5f1b258f-04b8-44fe-9b83-4c9b37bdfa30.png)

... and just an "RT twitter:<id>" over in my Twitter profile. Not sure of how much relevance this still is (and for how long this will continue to work at all), but at the moment it seems broken. Also tried this with several other Twitter posts, result's always the same.

**Comment by annando** [comment]
I'm currently unsure, how much time I want to invest into the Twitter extension.

**Comment by kr428** [comment]
> I'm currently unsure, how much time I want to invest into the Twitter extension.

Can imagine. Just wanted to leave it here to have it tracked, and maybe it's an easy/simple/obvious fix.

**Comment by ghost** [comment]
> Twitter posts doesn't seem to work anymore. Tried to quote this post...

You need to quote the tweet from Twitter page, then it will be displayed and seen in Friendica as well.

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
