### ISSUE TITLE
[2023-03rc] "Like" on posts of non-followers randomly misbehaving?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12923]
Hard to catch this one, leaving it here in case anyone else hits it. After seeing my home instance updated to 2023-03rc, adding "likes" to accounts of non-followers "randomly" behaves weird again. So far tested on mobile (web ui, current fedilab), always same approach - interact with a post that floats by in a public timeline and is sent by someone you don't follow.

- Sometimes, fedilab will again throw a red "an error has occured" message. This doesn't necessarily seem to affect whether or not the "like" is added to this particular post - in some cases it will work, in some it won't.
- Same way using the web ui in a mobile browser. While tapping on thumbs-up on a post of a follower, this will toggle within a short while and add my name to "... has liked this". For posts of non-followers, tapping on the thumb-up will in some cases do nothing, in some cases take much longer to show some effect than for posts of people I follow (in some cases I reloaded the page to see the status has - not - been updated).

Not sure this makes sense or is a real issue. Will add some more info once it gets clearer.

**Comment by Raroun** [comment]
"Like failed: Network Error"
Thats what i randomly get.
Its not reproducable tho. Happens every now and then. After one Minute, i am able to get the like through.
Happens only  at non-followers.

**Comment by xundeenergie** [comment]
This sound to my new improvement of like-button.

If this happens, you have really network-problems. If you can not reach the server, when you click on like, this error-message plopps up.
Does it happen on smartphone or desktop?

**Comment by xundeenergie** [comment]
Another Question... 

Are you sure, this likes have been successful in the past?
Because before you sent a like, the whole page was rendered and loaded new... if the like was not successful, your only response was, seeing your name in the likers-list... and if there have been more than two, you had to open this list manually to check, if you like it now...

**Comment by xundeenergie** [comment]
When you open the devtools in firefox (chrome should be the same), then you can see the network analysis. 

When you click to like, you see a "POST" Request in the network-tab in devtools.
What does the "Answer" say on broken likes?

This is a successful like, for example
![grafik](https://user-images.githubusercontent.com/5894829/226865873-a95596d2-dbf2-489b-8adc-d9441f665854.png)

**Comment by kr428** [comment]
In my case, it occassionally happens on the smartphone and in fedilab (talking to Friendicas Mastodon API implementation). Haven't seen it that often on the desktop.

**Comment by xundeenergie** [comment]
Ok.... in Fedilab too... this - so i think - should not be touched by my change.
Because my changes are only for the frio-theme in web-client, not to the api.

I think, this is in case of a bad internet-connection.

**Comment by xundeenergie** [comment]
This posting https://friendica.opensocial.space/display/8ffdf77c-1664-1b35-d83e-260670807655 is such a candidate.

I can share it, and the POST-Request goes to `/item/8236881/activity/announce` with the answer

![grafik](https://user-images.githubusercontent.com/5894829/227042245-82ce8a74-a102-4983-a42a-dc56b932bce4.png)

All is fine.

The posting is shown as shared by me, after a page-reload, but the share-button did not get the right state

![grafik](https://user-images.githubusercontent.com/5894829/227042512-e8beae95-451a-43d7-8db6-e0e4208397a5.png)

If i like this posting, the like is correctly recognised after a reload.

![grafik](https://user-images.githubusercontent.com/5894829/227042616-55c2eeb0-a7ae-42ca-8310-ad6af612dc8f.png)

I reported this behaviour a few days, before i implemented the new like/share-button functionality, so this seems broken on another position.

When i recognised this behaviour, it thought it happens only on my own posts. But now, it happens also on another posting.

**Comment by xundeenergie** [comment]
Here i shared a comment
![grafik](https://user-images.githubusercontent.com/5894829/227043132-660303cc-2d95-4c66-82dc-147aad1cd689.png)

and after a reload, the sharing is still visible in the share-button. 
It's just another discussion on the same friendica.

**Comment by xundeenergie** [comment]
another test-posting

i shared the posting and the comment
![grafik](https://user-images.githubusercontent.com/5894829/227043512-44212afe-72f8-41da-a09b-26e43104b9bc.png)

It is shown as shared by me, but the share-button is still black.

https://soc.schuerz.at/display/4edd2508-1564-1b73-fe90-954293031568

**Comment by xundeenergie** [comment]
Here, i shared this, and the sharing is shown in the button too.

![grafik](https://user-images.githubusercontent.com/5894829/227043900-a3d14bb6-d06d-433d-8f7f-d5dcc97ee57f.png)

The i follow the user, who shared this posting.
I don't follow the original poster.

**Comment by xundeenergie** [comment]
Here i follow this user. Sharing is persistent viewable in the Button after reloading the page.

![grafik](https://user-images.githubusercontent.com/5894829/227044398-13010326-64a4-4c52-9b4e-be434f0884a7.png)

**Comment by xundeenergie** [comment]
I don't follow this person: Sharing is in the "sharers list", but the button does not reflect, that i'm sharing this

![grafik](https://user-images.githubusercontent.com/5894829/227044868-c637b36f-1b78-4980-a2b6-e175d8d46761.png)
![grafik](https://user-images.githubusercontent.com/5894829/227044905-5b571b71-be1e-4042-9703-b9315f09ce2d.png)

**Comment by xundeenergie** [comment]
Another Users post, which i don't follow:
I'm in the list "shared this posting", but the button does not reflect it after Reload

![grafik](https://user-images.githubusercontent.com/5894829/227046112-3b8acb08-f114-4a73-8289-ee0db58be134.png)

**Comment by xundeenergie** [comment]
so it seems, the share-button does not reflect, that i shared it, if i share my own postings and postings from users, which i do not follow. 

It seems a bug for me. @MrPetovan what do you think?

**Comment by MrPetovan** [comment]
I didn’t even know the Share button state could change 😅

**Comment by xundeenergie** [comment]
It's the class "active" which is added or removed, in case of sharing or likeing a post/comment.
And the class is set on rendering the page, when a post/comment is known in database as shared/liked/disliked from you.

But not in every case, how we found out now... 

😉

I think, the sharing-state is not queried or answered from db or rendered in every constellation correctly. Because a posting/comment is shown as "shared by me" in the list, but not in every case in the button as it has not got the 'active' class.

**Comment by kr428** [comment]
Just for that matter, along the lines (as I'm currently stumbling across this): On loma.ml, my home instance, this seems broken at the moment. Though the "like" button apparently sends the correct server request and the response looks "good" but the "Like" button stays inactive even after fully reloading the particular post.

**Comment by xundeenergie** [comment]
> Just for that matter, along the lines (as I'm currently stumbling across this): On loma.ml, my home instance, this seems broken at the moment. Though the "like" button apparently sends the correct server request and the response looks "good" but the "Like" button stays inactive even after fully reloading the particular post.

When you reload, are you in the list of users, who like this? And is only the button, which does not reflect it?
Or is the like not recognised at all?

And do you follow the user or not?
In not, die someone you follow shared thisIs it your own posting/comment?

**Comment by kr428** [comment]
At the moment, I'm neither in the list of users who like this nor is the button toggled. But then again, it seems the instance has other issues as well at the moment, as I can't post anything and the timeline is several hours behind so maybe it's a similar but unrelated effect.

**Comment by xundeenergie** [comment]
Ok.

But if you like a post/comment and you reload the page, and it is shown again as not liked on the button, are you in the list og users, who like this, or also not?

**Comment by xundeenergie** [comment]
@MrPetovan i switched back to develop, and here is the misbehaviour the same.
I share a posting from a user, i don't follow, and the rotator rotates, then the site is reloaded. I'm in the list of users, who share this, but the share-button has no class "active", so it stays black and not fat. 

So it is something in the backend/rendering independent from the new share/like-button-functionality.

**Comment by MrPetovan** [comment]
That’s what I thought as well.

**Comment by kr428** [comment]
> Ok.
> 
> But if you like a post/comment and you reload the page, and it is shown again as not liked on the button, are you in the list og users, who like this, or also not?

In most cases, the "like" button is toggled "before" I appear in the list of the people who liked this post. This seems a general behaviour and there usually seems bit of a delay between these two changes in the frontend. Is that how it should be?

**Comment by xundeenergie** [comment]
It works now this way:

- You click in like/dislike/share
- the icon on this buttonis replaced by a rotator
- a post-request is made to the server
- if the post was successful, the rotator is replaced by the original icon
- the class "active" is added to the button, which makes the icon bold and colored

- if the post-request was not successful, the rotator is replaced by the original icon
- the class "active" is NOT set
- the button appears normal

Every few seconds a so called "ping" updates the page. This means, it updates the list of users, who liked/disliked/shared this item, and should update the state of the button (active or not) as well.

So you have a gap between seeing the button change it's state and the userlist for this activity.

The bug now we can see is:
In some cases the state of the button (active or not) is not set correctly, when page is rendered.

This happened before the changes too, but most users did not recognise it.

**Comment by xundeenergie** [comment]
Here i faced the problems a few weeks before

https://soc.schuerz.at/display/4edd2508-7864-097b-74a7-086375667519

I just recognised it, because i played around a lot, to understand how the buttons work.

**Comment by xundeenergie** [comment]
Just made another check:
In theme "Vier" is it the same problem. 

Here i shared this posting from a user i don't follow, and the button does not reflect it

![grafik](https://user-images.githubusercontent.com/5894829/227230113-65757834-46c7-45fb-a72d-e22e665999b2.png)


Here i shared and liked a posting from a user, i follow

![grafik](https://user-images.githubusercontent.com/5894829/227229911-62c8a791-3723-4d22-8192-4b9d0c79eed9.png)

**Comment by xundeenergie** [comment]
Not only misbehaviouring, also inconsitencies between followed users and not followed users...

![grafik](https://user-images.githubusercontent.com/5894829/227316129-fc8e69f1-6523-425d-934d-b54267317665.png)
I'm following "Don Aristo", and i liked and shared his comment.
I'n NOT following "Holy Crap", and i liked and shared his comment too.

On "Don Aristos" comment I can see the Buttons green (= class is "activate") and my username is UNDER the comment in the List.

On "Holy Crap"s comment i can see only the like-button with class "activate", not the share-button.
The "like" is shown UNDER the comment, the "share" is shown ABOVE the comment.
Maybe this is the reason, why the button is not activated.

**Comment by xundeenergie** [comment]
So i found out more... some kind of hackish debugging... :D

This is the posting of a non-following user, the announce has not saved as "self" and no username
![grafik](https://user-images.githubusercontent.com/5894829/227329116-938ae84a-eed3-4f4a-b812-961ff861ee29.png)

This is the posting of a followed user (the same two from above). The announce has self set to 1 and my username in  output
![grafik](https://user-images.githubusercontent.com/5894829/227329734-5979c3cb-88b7-4b1d-8d2c-f3fcc61602a7.png)

Now my question is: 
Is this planned, a feature, or really a bug... 
it looks inconsistent to me.

**Comment by MrPetovan** [comment]
Still a bug, thank you for the additional information!

**Comment by xundeenergie** [comment]
No, sorry, this does not fix it. It opens another problem... 
Posting shared by another one are shown as shared by me (the button gets class "activate" even if it is only shared by another).

The PR is changed to a draft, since i realized this problem.

It has to do, that repost/announce-information for postings from not-following users is stored in another way than for following users.

Please reopen this again.

**Comment by xundeenergie** [comment]
Information about a shared posting from users i don't follow is not correct... 

This is a posting from a user, which i did not follow and i reshared this posting
```
 ["responses"]=> array(3) { ["like"]=> array(2) { ["self"]=> int(0) ["output"]=> string(0) "" } ["dislike"]=> array(2) { ["self"]=> int(0) ["output"]=> string(0) "" } ["announce"]=> array(2) { ["self"]=> int(0) ["output"]=> string(0) "" } }
 ```

And from the same user another posting, i reshared AFTER i followed him
```
["responses"]=> array(3) { ["like"]=> array(2) { ["self"]=> int(0) ["output"]=> string(0) "" } ["dislike"]=> array(2) { ["self"]=> int(0) ["output"]=> string(0) "" } ["announce"]=> array(2) { ["self"]=> int(1) ["output"]=> string(136) "

[𝗝𝗮𝗸𝗼𝗯 :𝗳𝗿𝗶𝗲𝗻𝗱𝗶𝗰𝗮: 🇦🇹 ✅](https://soc.schuerz.at/contact/43/conversations) hat dies geteilt
" } }
```

I'm thinking about the different handling, when i reshare a posting. Does somebody know the idea behind?
And where does this happen?

**Comment by Raroun** [comment]
So, I now have it reproducible. At least with the "like" button. But it looks like it has nothing to do with the changes to the "like button", but rather with the change that the "Moderation" menu that was implemented.

I can reproduce it at any time (it may be that some steps are not necessary, but that's how it is reproducible):

I go to the drop-down menu of my profile at the top right.
Then I click on Moderation and then on Users on the left.
I then sort the list by date of registration and click on the most recent entry. A new user I do not follow.
I am on his profile under the menu "Conversations".
Here I can click on "I like" for as long as I want and always get a "Network Error".
I do this procedure every day to see who has registered on our instance and what the new ones are posting.

As I said, I assume that it has something to do with the new menu-item "Moderation" under administration.

**Comment by MrPetovan** [comment]
The moderation menu only moved links to relevant pages in a central location. The issue might come from the User Conversations page which predates this new menu.

**Comment by xundeenergie** [comment]
I tried to debug a little... 

when i go to this posting https://soc.schuerz.at/display/4edd2508-1564-0f2c-f991-5bc473448417 via the moderation/conversation tab, the post-request goes to
`https://soc.schuerz.at/item/8050409/activity/like`
and ends with "400 Bad Request"

when i search for this posting via searchbar and like it, the request goes to
`https://soc.schuerz.at/item/8300940/activity/like`
and i get a 200 OK"

I don't know, it the item-number somewhat uniq for a instance, and does the conversations-tab uses a wrong item-number?

**Comment by xundeenergie** [comment]
switched back to develop to check:

And yes... also in develop the POST-Request goes to the wrong `https://soc.schuerz.at/item/8050409/activity/like` resulting in a 400 Bad Request and the like is not changed... 

It would be cool, if someone with stable could test this too...

**Comment by xundeenergie** [comment]
So i asked a friend, who is running friendica on stable.
And in stable it works as expected also on the conversations-site.

**Comment by cracrayol** [comment]
~~Don't know if it's the same problem but when I want to share a post, I've got an error when calling item/\<id>/activity/announce endpoint~~ :

```
Bad Request

The server cannot or will not process the request due to an apparent client error.

#0 /home/cracrayo/friendica/src/BaseModule.php(238): Friendica\Module\Item\Activity->rawContent()
#1 /home/cracrayo/friendica/src/App.php(700): Friendica\BaseModule->run()
#2 /home/cracrayo/friendica/index.php(52): Friendica\App->runFrontend()
#3 {main}

Request: 642584132d39e
```

~~I'm on the latest commit of 2023.3-rc branch~~

Edit : Ok, it seems that it's more of a DB problem. I've 3 lines in contact table for my profile.

**Comment by kr428** [comment]
Would close this off as, recently, this doesn't seem a problem anymore.
