### ISSUE TITLE
Issue with addons phpmailer in particular 

### ISSUE THREAD

**Issue by dogrileycom** [friendica/friendica#12945]
I am a bit confused about addons. 2 questions, 1 general and 1 specific:

General
There are instructions for enabling them manually that refer to .htconfig.php where the plugins seem to be registered.
The only .htconfig.php file I have is in the ./tests directory: 
./tests/datasets/config/.htconfig.php

Should I have another .htconfig.php file? where should it be? Will this get altered through the admin interface choices?

Specific
I have copied the phpmailer.config.php to ./config and altered it appropriately but it is not working.  Maybe it is not getting called properly because of the .htconfig.php missing? I also found reference in an older support email to naming this addon.php or something similar, did I misname the config file this is what the file says to name it.

Where or how in the logs should I see the mail attempt? (sorry 3 questions :) )

**Comment by MrPetovan** [comment]
1. `.htconfig.php` file is deprecated, where did you see a reference to it? It should be updated.
2. There is an ongoing issue where addon config stored in `config/` (no matter the file name) gets overwritten by the default values set in the addon config file itself. Please add your local values in `addon/phpmailer/config/phpmailer.conf.php` while we work on fixing this issue.
3. You can check the working value of any config key using the console CLI tool from the base Friendica folder: `bin/console config phpmailer host`

**Comment by dogrileycom** [comment]
I’ll go find it and let you know.  It’s probably old.

It seems the correct config is getting read if the output from 
bin/console config phpmailer is to be believed (unsure what host does…)

I can change the setting in the ./config file and it gets picked up here.

Still not sending though.

In this:
if (DI::config()->get('system', 'smtp_secure') && DI::config()->get('phpmailer', 'smtp_port_s')) {
				$mailer->SMTPSecure = DI::config()->get('phpmailer', 'smtp_secure');
				$mailer->Port       = DI::config()->get('phpmailer', 'smtp_port_s');
			}

Where is ’system’ - ’smtp_secure’ set?  I may not have that set?

**Comment by dogrileycom** [comment]
OK so I made an educated guess and added smtp_secure setting manually to the local.config.php file at the end:
           ...     'language' => 'en',
                   'smtp_secure' => 1,  ...

And everything works fine now.  Is this a setting from the front end?  I cannot find it...

**Comment by dogrileycom** [comment]
This is closed, still unsure if this is a UX issue

**Comment by MrPetovan** [comment]
I can’t check where the `system.smtp_secure` config key should be set until this week-end, that’s why I didn’t close the issue myself even though ou said you solved your initial issue.

**Comment by dogrileycom** [comment]
I have looked everywhere, not seeing it, suggest it gets added the the add-on documentation. Can go in the example conf file.
