### ISSUE TITLE
improve file drop area in post composer

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12944]
This is frio after the patch to respect dark and black color schemes https://github.com/friendica/friendica/pull/12931:
![1](https://user-images.githubusercontent.com/5708172/227472330-504536e0-8be8-46ff-b536-1b5145244515.png)

A few improvements come to mind:

- remove grey bar on the right side
- remove grey bar at the bottom
- increase size of drop area
- rename `Drop files here to upload` to `Drag and drop to upload` and center text
- use a text color with less contrast to lower focus on this information (compare to composer and title hint text color)
- put a dotted line at the border of drop area to indicate that it can be interacted with

Twitter solves this nicely: they only ever show the dotted line in the composer area when a user actively drag and drops a file. As soon as the file is dragged, the entire composer turns into target area indicated by the dotted line which only ever shows when active dragging is happening.

Polite ping @xundeenergie @damianwajer

**Comment by xundeenergie** [comment]
The first thing, after the release, when there's less pressure on time for me, i've planbed to prepare dropzone to be translateable.
And to remove images also fromserver, if you remove them from dropzone (it's possible in the first 5 seconds after upload).

Thank you for your suggestions, i will pick them up as well i've time to.

**Comment by xundeenergie** [comment]
@foss- But are you sure, you have the latest commits?

This is dark
![grafik](https://user-images.githubusercontent.com/5894829/227522907-8748e99d-743e-4aea-8d41-7c4de7cb520e.png)

and this ist black 
![grafik](https://user-images.githubusercontent.com/5894829/227523037-2a19f761-82dd-40ed-9236-2c8985e1630d.png)

Which browser are you using?

**Comment by foss-** [comment]
Firefox 111.0.1. pirati.ca where I am testing on seems to be lacking your spacing fix https://github.com/friendica/friendica/pull/12938.

**Comment by MrPetovan** [comment]
Please be sure to clear your browser cache

**Comment by xundeenergie** [comment]
I know, the "Drop files here" is a bit missleading...

But the whole textarea is dropzone... You can drop it somewhere in the textarea. And this is "big enough" i think. Just try it. 
With Copy/Paste you can insert an Image just at cursor-position. The same, if you drop an image somwhere in the textarea, it is inserted on cursor-position too.

In case, that the whole textarea including the dropzone-text below is "dropzone" a dotted border around does not look very nice.

I changed the color of the text to `#999` like other similar text has.
This will come with the next pullrequest.

**Comment by MrPetovan** [comment]
This is the display I'm getting on Vivaldi/Windows 10. Inactive scrollbars take up a lot of space.
![friendica-dropzone-scrollbars](https://user-images.githubusercontent.com/925415/228011057-9bd1def5-bfbf-4857-bf67-e84c9ad2d8c6.png)
I didn't even test the feature itself, but just this doesn't look super good.

**Comment by xundeenergie** [comment]
Oh, this are scrollbars... ok...

**Comment by MrPetovan** [comment]
I retract my comment about the label not appearing, I didn't have the Composer dependency installed. The scrollbars are still there, though.
