### ISSUE TITLE
Urlpreview from a wordpress shows css-code

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#12940]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

I don't know, if it is a bug in friendicas url-preview or in this specific wordpresstheme. But adding this url to friendica, the urlprewview gives CSS-Code back... 

### Steps to Reproduce

1.  Create new Posting
2. Add https://verzeichnis.handelsfrei.org/ to the text

Actual Result:

See screenshot below

Expected Result:

Just a Preview, without Sourcecode

### Screenshots

![Screenshot_20230323_205002](https://user-images.githubusercontent.com/5894829/227335398-5ff6e8e3-5e3c-4729-8356-7898fb819a7c.jpg)

### Platform Info

Friendica Version: 2023.03-rc

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
It looks like a Wordpress plugin called Elementor is inserting its CSS in the post body which is thwarting our post retrieval system.

This isn’t a link preview, it is a full post retrieved from the URL.

**Comment by MrPetovan** [comment]
Can't do anything from our end for this unfortunately.
