### ISSUE TITLE
Quote Share seems not to work between Friendica instances

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#12977]
I created a post with a quote share from pixelfed. On an other Friendica instance I see only the text and not the shared post.

my post: 
![D7283C15-12E9-45D9-A8F8-D20EA4A67032](https://user-images.githubusercontent.com/1984982/230656966-d041d4ae-90e3-4cb7-b394-0de6ffedf130.jpeg)

other instance:
![CFEF387C-DEE8-487F-A468-6EB8933550F9](https://user-images.githubusercontent.com/1984982/230657010-92755d3c-21fc-444f-99db-bf674e986648.jpeg)

link to original: https://punkrock-underground.com/display/98475452-5164-2fa7-a82f-250288353218

**Comment by annando** [comment]
Thanks for the report!

Luckily I had got the same issue on my system. It was some really ugly timing issue, see the description in the pull request. Hopefully my changes fixed it.

BTW: It was a very close race:
```
+---------------------+---------------------+
| created             | received            |
+---------------------+---------------------+
| 2023-04-07 05:18:32 | 2023-04-07 05:20:31 |
| 2023-04-07 05:17:12 | 2023-04-07 05:20:33 |
+---------------------+---------------------+
```
The first line is the post from above. The second line is the quoted post. It was created several seconds before the first one but was processed two seconds after it. (But was already received on my system at that time and awaited processing)
