### ISSUE TITLE
[frio] Missing "Back to Top" Button 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12974]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The Back to top button is no longer displayed

Restoring the "Back to top" button function

Friendica Source: Github RC

PHP version: 8.0

SQL version: 10.4

**Comment by MrPetovan** [comment]
I can confirm, thank you for your report!

**Comment by loma-one** [comment]
Addition: the problem occurs when using Firefox (111.01). 
With Brave (1.49.120) the back-to-top button is displayed.

**Comment by AlfredSK** [comment]
For me it works with Firefox 111.0.1 on Linux.

**Comment by loma-one** [comment]
uBlock Origin filtered it away.

! 2022-03-19 https://loma.ml
loma.ml###cookienotice-box

![grafik](https://user-images.githubusercontent.com/44441246/230202258-06f57596-7bc3-4e81-a75a-f23662a8d54e.png)
