### ISSUE TITLE
Frio: Editor does not expand when end of line is reached

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12995]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When the end of the field is reached, the editor in the modal and composer should expand by one line each.

**Modal**: If the modal is used in a forum, it is not expanded.
**Composer**: the editor must be expanded manually.
**Comments**: the comments are only expanded when a Diaspora post is commented. 

### Screenshots
Modal
![grafik](https://user-images.githubusercontent.com/44441246/231481988-9183c703-9e12-4097-bf48-be074baa056c.png)

Composer
![grafik](https://user-images.githubusercontent.com/44441246/231481449-0b21d471-ea4d-4909-801b-c4dc2a6cbbef.png)

Comments
![grafik](https://user-images.githubusercontent.com/44441246/231482167-6b41f3c2-9eec-477b-98bf-e000526d2281.png)

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.03-rc - 1518

Friendica Source: github

PHP version: 8.0

SQL version: 10.5

**Comment by xundeenergie** [comment]
Can you check this again?
This should be fixed with my last PR https://github.com/friendica/friendica/pull/13008

**Comment by foss-** [comment]
Fixed for me with: This is Friendica, version 2023.03-rc that is running at the web location https://pirati.ca. The database version is 1518/1518, the post update version is 1507/1507.
