### ISSUE TITLE
[vier] Sending comments not possible

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12993]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If a comment is created on an existing post, it is not possible to send it.
There is no button: send or cancel

### Screenshots

![grafik](https://user-images.githubusercontent.com/44441246/231455816-2649171d-0c20-49ac-967a-3c8b32389504.png)

### Platform Info

Friendica Version: 
Friendica 'Giant Rhubarb' 2023.03-rc - 1518 

Friendica Source: github

PHP version: 8.0

SQL version: 10.5

**Comment by tobiasd** [comment]
I can confirm this bug

**Comment by tobiasd** [comment]
Running `git bisect` yielded to 4db29565def8cffcb5f0aec2f41f8f82d8f0bf1d as the first bad commit.#12984

**Comment by tobiasd** [comment]
I think it is caused by [this javascript block](https://github.com/friendica/friendica/pull/12984/files#diff-a8b659e26f0de1b27b23c8542780c5c0f02c248e4085cf490fcc6601728dee77R47) re-declarating two constants that are defined elsewhere in vier already. But I'm not sure about it.

**Comment by tobiasd** [comment]
@MrPetovan do you remember why you added the two declarations to that Javascript block to the file?

**Comment by MrPetovan** [comment]
Yes, I changed the global `var` declarations to better-scoped `const` declarations, however I didn't test on vier.

**Comment by tobiasd** [comment]
Can the 4 lines you added that cause the problem be suavely removed then, or do you advise a different fix for the bug?

**Comment by MrPetovan** [comment]
I will look into it today so that you can release this week-end.
