### ISSUE TITLE
Installation screen does not show English

### ISSUE THREAD

**Issue by dranii** [friendica/friendica#12998]
Latest version (friendica-full-2023.01.tar) tried with php 7.3, following latest instructions.
The installation screen does not show English language, making things difficult to follow. I  think it shows "de".
Although  php8x is supposedly not supported (in fact with php8.2 it asks for a maths module which is not in common use) - same language problem exists there too.
I also tried git installation - same language problem there.

**Comment by tobiasd** [comment]
What underlying server OS are you using?

**Comment by dranii** [comment]
Linux / LiteSpeed V8.0.1 Cloudlinux 1.3 @MrPetovan @tobiasd 
According to underlying server OS, the language changes? However this does not happen with other fediverse php scripts/softwares (social networking related) I have tried. The installation screen shows NON-english, as if by default on another web-hosting company too as well as on git clone.

**Comment by MrPetovan** [comment]
Friendica's localization feature takes into account several parameter to determine the language it presents to users:
- The query string parameter `lang` that you can use like this: `?lang=en`
- The Friendica node language setting, by default `en` if it isn't set.
- The `Accept-Language` header sent by the browser.

On a fresh installation, it looks like it could be related to your the browser header.

**Comment by dranii** [comment]
@MrPetovan all are `en`
Even after setting the language as English (via administration page and after installation) the language does not change to English. Has any one tested installation with the latest stable release?
PS : on git clone also, this happens - "header sent by the browser" should not come there or it does?

**Comment by MrPetovan** [comment]
Archive install or git clone will give you the same files, it's just a couple different ways of doing it.

So far it sounds like a specific issue related to your own server since nobody else has ever reported a similar issue.

Can you please confirm the result of the following command ran from the Friendica base folder:
```
bin/console config system language
```

**Comment by dranii** [comment]
**Information about browser**
Chrome is up to date
Version 112.0.5615.121 (Official Build) (64-bit)
chrome://settings/languages - 1. English - This language is used to display the Google Chrome UI

**Information from Terminal**
```
# bin/console config system language
Database isn't ready or populated yet, showing file config only
system.language => en
```

**I get the following screen (partly shown)**

![frndka-instll](https://user-images.githubusercontent.com/9887635/232615392-4ff7c962-7c0b-4427-9e4f-c32af4d1d2f8.png)

I think, the first  installation screen should default to English in an absolute sense irrespective of OS/browser/location or whatever or just present a choice of language (like Drupal or many others do) in a pictorial way (icons/flag symbols etc) without any language. Also important point is, somehow I can proceed with "de" but when I change to English via the administration page "de" still remains, and the system does not change to English, The only work-around I find is by deleting or renaming (to something obscure) the "de" folder. Since installation is the first and foremost screen one gets, the experience should be smooth and pleasant with no such high-tech hassle of "localization feature taking into account several parameter". Let the user (admin) choose the language in a pictorial screen with _no_ language (if that is preferred to English), and just after that the "localization feature" can take over.

**Comment by dranii** [comment]
@MrPetovan 

**Information about browser**
Chrome is up to date
Version 112.0.5615.121 (Official Build) (64-bit)
chrome://settings/languages - 1. English - This language is used to display the Google Chrome UI

**Information from Terminal**
```
# bin/console config system language
Database isn't ready or populated yet, showing file config only
system.language => en
```

**I get the following screen (partly shown)**

![frndka-instll](https://user-images.githubusercontent.com/9887635/232615392-4ff7c962-7c0b-4427-9e4f-c32af4d1d2f8.png)

I think, the first  installation screen should default to English in an absolute sense irrespective of OS/browser/location or whatever or just present a choice of language (like Drupal or many others do) in a pictorial way (icons/flag symbols etc) without any language. Also important point is, somehow I can proceed with "de" but when I change to English via the administration page "de" still remains, and the system does not change to English, The only work-around I find is by deleting or renaming (to something obscure) the "de" folder. Since installation is the first and foremost screen one gets, the experience should be smooth and pleasant with no such high-tech hassle of "localization feature taking into account several parameter". Let the user (admin) choose the language in a pictorial screen with _no_ language (if that is preferred to English), and just after that the "localization feature" can take over.

**Comment by MrPetovan** [comment]
This would make a lot of sense (except icons for languages, this is a touchy subject and writing the name of the languages in the language is better) if this was a systematic issue reported by more than one person. As it stands it seems to be limited to your system.

Can you please replace the `detect()` method in `src/Core/L10n.php` on line 192 by the following:
```php
	public static function detectLanguage(array $server, array $get, string $sysLang = self::DEFAULT): string
	{
		var_dump($server, $get, $sysLang);

		$lang_variable = $server['HTTP_ACCEPT_LANGUAGE'] ?? null;

		if (empty($lang_variable)) {
			$acceptedLanguages = [];
		} else {
			$acceptedLanguages = preg_split('/,\s*/', $lang_variable);
		}

		// Add get as absolute quality accepted language (except this language isn't valid)
		if (!empty($get['lang'])) {
			$acceptedLanguages[] = $get['lang'];
		}

		var_dump($acceptedLanguages);

		// return the sys language in case there's nothing to do
		if (empty($acceptedLanguages)) {
			return $sysLang;
		}

		// Set the syslang as default fallback
		$current_lang = $sysLang;
		// start with quality zero (every guessed language is more acceptable ..)
		$current_q = 0;

		foreach ($acceptedLanguages as $acceptedLanguage) {
			$res = preg_match(
				'/^([a-z]{1,8}(?:-[a-z]{1,8})*)(?:;\s*q=(0(?:\.[0-9]{1,3})?|1(?:\.0{1,3})?))?$/i',
				$acceptedLanguage,
				$matches
			);

			// Invalid language? -> skip
			if (!$res) {
				continue;
			}

			// split language codes based on it's "-"
			$lang_code = explode('-', $matches[1]);

			// determine the quality of the guess
			if (isset($matches[2])) {
				$lang_quality = (float)$matches[2];
			} else {
				// fallback so without a quality parameter, it's probably the best
				$lang_quality = 1;
			}

			// loop through each part of the code-parts
			while (count($lang_code)) {
				// try to mix them so we can get double-code parts too
				$match_lang = strtolower(join('-', $lang_code));
				if (file_exists(__DIR__ . "/../../view/lang/$match_lang") &&
				    is_dir(__DIR__ . "/../../view/lang/$match_lang")) {
					if ($lang_quality > $current_q) {
						$current_lang = $match_lang;
						$current_q    = $lang_quality;
						break;
					}
				}

				// remove the most right code-part
				array_pop($lang_code);
			}
		}
		
		var_dump($current_q, $current_lang);

		return $current_lang;
	}
```
This will output internal language detection data to your browser when you navigate to the install page again. Please copy the output here, removing any sensitive data from it beforehand.

**Comment by dranii** [comment]
@MrPetovan  Yes, writing the name of the languages in the language is better. The moot point is whether to wait for "reporting by more than one person" or just remove that possibility which can happen in another person's system sooner or later. Anyway, I am in favor of closing this ticket. Thanks  a lot for all your help.
