### ISSUE TITLE
[abstract] only statisfies text but not attached images

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#12997]
A Content warning is ignoring attached pictures. 

Example:

[abstract=apub]Inhaltswarnung[/abstract]

collapses the text, but not attached images.

For Detail you can look here;

https://friendica.opensocial.space/display/8ffdf77c-1964-3046-a0a2-d6e283847655

Content warnings should include Imgaes. It makes no sense to just include the text into a content warning, but not the attached image.

**Comment by Raroun** [comment]
Obiviously in friendica it works like expected, but not in other services like mastodon.
i am not sure it´s a friendica problem tho.

**Comment by MrPetovan** [comment]
It isn't a Friendica problem, Mastodon's content warning just doesn't include attached images, and I'm not sure they support inline images. Mastodon has a "sensitive picture" flag to initially blur pictures out instead.

**Comment by Raroun** [comment]
ok, thank you :)
