### ISSUE TITLE
[Frio] background image for login page cannot be set

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13006]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

An image is to be selected for the login page in order to display it on the login page.
It is not possible to store an image, as the server's timeline is integrated after the selection.

### Steps to Reproduce

1. login as admin
2. uploading an image that is to be included for the login page
3. change to the adminstration /admin/
4. change to the theme administration /admin/themes
5. select Frio /admin/themes/frio
6. navigate to the Frio settings > background image of the login page
7. selection of an image via the Gallery

Actual Result:

After selecting an image from the Gallery, the timeline of the server is integrated.

Expected Result:

The URl for the gallery image is stored in the field "Background image of the login page" and must be confirmed.

Workaround:

Get the URL via the Gallery and enter it directly in the field "Background image of the login page", confirm is without function. The login page does not show a changed image on the start page.

### Screenshots

![grafik](https://user-images.githubusercontent.com/44441246/232328946-b93e717c-5bd1-4e8d-bd42-a91ee53b95c2.png)

### Platform Info

Friendica Version: 2023.03-rc - 1518

Friendica Source: git

PHP version: 8.0

SQL version: 10.5

**Comment by MrPetovan** [comment]
What do you mean by "the server's timeline is integrated" ?

**Comment by loma-one** [comment]
I have included a picture above. There you can see the page /admin/themes/frio:

![grafik](https://user-images.githubusercontent.com/44441246/232382550-39298748-164d-4074-a9fb-5abe23aaed16.png)

which should look like this:

![grafik](https://user-images.githubusercontent.com/44441246/232381679-937bb043-c89a-480c-9254-28abd3bbe114.png)

**Comment by MrPetovan** [comment]
Thanks, I get it now.
