### ISSUE TITLE
[diaspora] Login fails if 2FA is enabled on the remote Diaspora account

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13011]
Social networks

Built-in support for diaspora*
 
Diaspora Export 

fails to connect... with invalid login.

**Comment by annando** [comment]
I guess this is the expected behaviour. Also this addon is a addon that doesn't has got much sense, I think. I thought we already deprecated it, since the native Diaspora support is really great.

**Comment by tek-aevl** [comment]
It seems like it pulls my post from diasp.org to my friendica instance?
Is that right?

**Comment by annando** [comment]
No. This is meant to use a given Diaspora account to post the content that you posted on Friendica. But since people from Diaspora can easily subscribe you directly, it doesn't make much sense.

**Comment by tek-aevl** [comment]
Thanks for clearing that up.
