### ISSUE TITLE
Change the icon for the mobile sidebar to make it more intuitive.

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13016]
Probably something one hasn't encountered if they are developers.  It took me several weeks to realize that the ellipses was a way to access the side bar.  It was so small I didn't even notice it was there.  Everything else was very intuitive.  
Simple fix, change the ellipses icon to one with a right arrow or right alignment special icon of some kind so its stands out more and something people would be curious to push. once popped up, switch it to  left until collapsed.  I think it would be much more intuitive for the casual user.  

I use Frio but I believe vier has the same layout in the top bar.

I believe it should just take a simple change to nav.tpl, lines 34 and 44 from fa-ellipses-v to some other icon from fork awesome.

I'm trying to learn the software and code so let me know if something else also needs to be changed to make this work.  I have around 8-9 other changes I will suggest down the road but I want to learn by finding the way to fix it myself before I bring it up, and will include the code change needed.  At that point you can collectively decide if you even want the change or if there is a better way to fix the problem and correct me if there are other changes in code needed to make it work.  

Also let me know if there is a reason the ellipses should stay that I am unaware of from a design standpoint.

**Comment by MrPetovan** [comment]
Ellipses are a "traditional" way of meaning "there are more controls" in a menu bar, but I guess it doesn't apply when we have two whole columns hidden away.

**Comment by anubis2814** [comment]
Yeah that was exactly the issue for me, ellipses in the right hand side was intuitive I figured that out, but because they were thin and packed in front on the left I think my brain just viewed it like the left hand corner of any desktop browser.

**Comment by anubis2814** [comment]
I have added the change to my personal fork if anyone wants to use it, just one line change.  It is just the right pointing double chevrons in nav.tpl.  I think it stands out a lot better and makes more sense now.

**Comment by MrPetovan** [comment]
Can you please share the modified line here for easier integration?

**Comment by anubis2814** [comment]
friendica/view/theme/frio/templates/nav.tpl 
line 44 
`<i class="fa fa-angle-double-right fa-fw fa-lg" aria-hidden="true"></i>`
