### ISSUE TITLE
[Tumblr] Message: Could not connect to Tumblr under php7.4 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13021]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

Connecting an account under php7.4 is not possible. Message: Could not connect to Tumblr. Refresh the page or try again later.
IMPORTANT: From php 8.0 the login works without problems.

### Steps to Reproduce

1. settings
2. social networks
3. tumblr export addon
4. (Re-)Authentication of your tumblr page
5. could not connect to Tumblr. Refresh the page or try again later.

Actual Result:
Message: Could not connect to Tumblr. Refresh the page or try again later. 

`2023-04-23T05:58:59Z index [NOTICE]: E_NOTICE: session_start(): A session had already been started - ignoring {"code":8,"message":"session_start(): A session had already been started - ignoring","file":"/var/www/html/friendica/addon/tumblr/tumblr.php","line":98} - {"file":null,"line":null,"function":"session_start","request-id":"6444c923aded7","uid":"274395","process_id":25599}`

`2023-04-23T05:58:59Z index [NOTICE]: E_NOTICE: Undefined index: oauth_token {"code":8,"message":"Undefined index: oauth_token","file":"/var/www/html/friendica/addon/tumblr/tumblr.php","line":119} - {"file":"tumblr.php","line":119,"function":"tumblr_connect","request-id":"6444c923aded7","uid":"274395","process_id":25599}
2023-04-23T05:58:59Z index [NOTICE]: E_NOTICE: Undefined index: oauth_token_secret {"code":8,"message":"Undefined index: oauth_token_secret","file":"/var/www/html/friendica/addon/tumblr/tumblr.php","line":120} - {"file":"tumblr.php","line":120,"function":"tumblr_connect","request-id":"6444c923aded7","uid":"274395","process_id":25599}`

Expected Result:
The account is (re-)authenticated

### Platform Info

Friendica Version: RC 1518

Friendica Source: github

PHP version: 7.4

SQL version: 10.3

**Comment by annando** [comment]
Can we postpone this to the next version? On my system I completely overhauled the addon, including the possibility to import the Tumblr timeline and to reshare and like Tumblr posts. I would like to publish this in the next version.

**Comment by annando** [comment]
The new Tumblr code is now in the system. Please check again.

**Comment by loma-one** [comment]
IMPORTANT: The addon is used under Stable. I assume that Dev and Stable are currently still very much together.

Under PHP8.0 / PHP7.4 💯 🤩. 
![grafik](https://user-images.githubusercontent.com/44441246/234503651-6a52e461-deaf-4a94-a47b-ea404d4f5327.png)

**Comment by tobiasd** [comment]
> IMPORTANT: The addon is used under Stable. I assume that Dev and Stable are currently still very much together.

No, not for the Tumblr addon. The changes @annando wrote about are in the `develop` branch of the addon repository.

**Comment by annando** [comment]
Can we close this issue?
