### ISSUE TITLE
OAuth Buffer.com not successful

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13020]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

Connecting a channel to Buffer is not successful. The login is aborted with the error message "Entity could not be processed".

### Steps to Reproduce

1. login buffer
2. add channel
3. connect a new channel "Mastodon
4. choose your Mastodon server > other
5. entry instance URL
6. button next

Actual Result:

No OAuth connection could be established.

``2023-04-23T05:31:03Z index [NOTICE]: no data for session {"session_id":"3ln1t4qclk8au78brnea3hnbb5","uri":"/oauth/authorize?client_id=543f4c814c75ede667bce1eefa6a7f93ce7c1d774c9ca054de5de54774123da0&scope=read+write&redirect_uri=https%3A%2F%2Faccount.buffer.com%2Fchannels%2Fconnect%3FconnectingMastodon%3Dtrue%26server%3Dloma.ml%26followBuffer%3Dtrue&response_type=code&force_login=true"} - {"file":"Database.php","line":78,"function":"read","request-id":"6444c29764c5e","uid":"82c45f","process_id":25518}``

``2023-04-23T05:31:03Z index [WARNING]: Application not found {"client_id":"543f4c814c75ede667bce1eefa6a7f93ce7c1d774c9ca054de5de54774123da0","redirect_uri":"https://account.buffer.com/channels/connect?connectingMastodon=true&server=loma.ml&followBuffer=true"} - {"file":"OAuth.php","line":137,"function":"getApplication","request-id":"6444c29764c5e","uid":"82c45f","process_id":25518}
2023-04-23T05:31:03Z index [INFO]: API Error {"no":422,"error":"Entität konnte nicht verarbeitet werden","method":"GET","command":"oauth/authorize?client_id=543f4c814c75ede667bce1eefa6a7f93ce7c1d774c9ca054de5de54774123da0&scope=read+write&redirect_uri=https%3A%2F%2Faccount.buffer.com%2Fchannels%2Fconnect%3FconnectingMastodon%3Dtrue%26server%3Dloma.ml%26followBuffer%3Dtrue&response_type=code&force_login=true","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"} - {"file":"Error.php","line":50,"function":"logError","request-id":"6444c29764c5e","uid":"82c45f","process_id":25518}``

Expected Result:

A channel is created and the instance is connected to Buffer.

### Screenshots

![grafik](https://user-images.githubusercontent.com/44441246/233822222-034d65c0-b387-4b09-967a-b879d22efaa6.png)

### Platform Info

Friendica Version: RC

Friendica Source: github

PHP version: 7.4

SQL version: 10.3

**Comment by annando** [comment]
The important part in the log is "Application not found". AFAIK buffer.com shut down their public API a long time ago.

**Comment by loma-one** [comment]
I use the same public key for three different instances. The two other instances run on php 8.0, where the authentication works.

**Comment by loma-one** [comment]
There is no longer a separate public API for Buffer. There is a new process through which Mastodon-compatible applications can register. 
Or do they think that the actual once existing own Api can cause a problem here?

![grafik](https://user-images.githubusercontent.com/44441246/233826910-9e7ef6a0-d1da-42cc-8d24-bd5efcf8e29a.png)

**Comment by annando** [comment]
See here: https://buffer.com/developers/api/logs

> ## September 8, 2020: API deprecation
>
> On September 8, we began limiting third party usage of the Buffer API in order to protect the relationships we have with our social network partners. Having reviewed usage of the Buffer API and the commitments we’ve made to Facebook, Instagram, Twitter, Pinterest, and LinkedIn, we’ve determined that we can no longer permit certain usage of the Buffer API. We’re grateful to our partners for being a part of Buffer’s API in the past and apologize for any disruptions this might cause your community or clients. As part of this change, some accounts have had their access to the Buffer API suspended.

**Comment by loma-one** [comment]
Thank you for the tip.
The addon for Friendica has not been active for a while.  
I do not use the process. 
I log onto Buffer and follow the path as described above. That is a different auth process.

**Comment by annando** [comment]
Ah, now I understand. Sorry, I'm still in my bed and my brain is still in boot up. I guess I have to check by myself what they are doing there. Seems to be as if they are doing stuff slightly different than other apps.

**Comment by loma-one** [comment]
Guten Morgen 😆

**Comment by annando** [comment]
The OAuth connection will now work, posting don't. I don't even see a HTTP request on my side, so it seems to be a Buffer issue.

Also a warning: Buffer only once tries to create an app. So don't delete the "application" entry in the database. (not to confuse with the application that a user can delete).

**Comment by annando** [comment]
Update: It now works for me for a long time, so I suggest to close this issue.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/13306
