### ISSUE TITLE
Editing comments: Empty page after submit

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1302]
When editing a comment of a post, after submitting the comment an empty page is shown (not a white page of death but an page showing all navigation elements but no content).

It would be good to be redirect to the post where the comment has been changed.

**Comment by silke** [comment]
Did you mean edit a comment of a post that you already sent? How can I reproduce this? I tried to
* connect two accounts in my vagrant friendica instance, both post and comment.
* Edit one's own comments after sending.
Everything is fine though, no white pages, neither in Vier nor in the default theme.

**Comment by tugelbend** [comment]
This happens when editing an already posted comment, f.e. correcting a typo.

**Comment by tugelbend** [comment]
I couldn't reproduce it with the recent release branch version. Closing it for now.
