### ISSUE TITLE
Service Unavailable after 2023.04 upgrade

### ISSUE THREAD

**Issue by oe4dns** [friendica/friendica#13029]
The 2023.04 upgrade did not work on my server.

I upgraded the usual way by pulling from git and running the composer script, but immediately got a "Service Unavailable" instead of the DB upgrade notification page.

Now I am experiencing an issue that looks exactly like https://github.com/friendica/friendica/issues/11778
![Friendica_workers](https://user-images.githubusercontent.com/1168512/233922540-acb69e28-9fb1-4744-8d3b-12eed5448dad.png)

It eats up all the servers RAM until it becomes unreachable. Killing the worker processes prevents this, but only until they respawn. I would have asked in the forums, but since my instance is not working, I can't

This is on a VPS with Debian stable.

**Comment by annando** [comment]
Please have a look at the SQL processes. What is `mytop` saying?

**Comment by oe4dns** [comment]
There are queries being processed. To me it does not look like there is one that hangs or is in a loop - See image. This was taken when the worker process already used up more than 80% of the system's RAM

I'm by far not a SQL person, but this does not look problematic to me - or does it?

![Friendica_mytop](https://user-images.githubusercontent.com/1168512/233935358-d494fb8b-a032-4410-b31e-f48071485e01.png)

Edit: The "Service Unavailable" issue still persists. It is not that Friendica grows slower and slower until it halts the server. It is not even showing up. The FAQs hint that this seems to be a database connection problem, but I'm not sure if this is true

**Comment by annando** [comment]
Do you see anything in the logs?

**Comment by oe4dns** [comment]
Apache as well as SQL logs do not show any errors that would give a hint. Are there any others I can check?

**Comment by annando** [comment]
Friendica's own logs should be helpful.

**Comment by oe4dns** [comment]
Great, but where di I find them?
Sorry for the Support Questions here, but since I cannot reach the forums.

**Comment by xundeenergie** [comment]
Directly after the upgrade, i got also a WSOD... after 2 Minutes or so, Friendica loaded successfully again.

**Comment by oe4dns** [comment]
WSOD is not the issue. I do get a "Service Unavailable" Page from Friendica (see image)

![Friendica_error](https://user-images.githubusercontent.com/1168512/233966378-182b16c2-4271-4e20-a0d1-46c425f8a836.png)


And then there is the worker.php taking up all RAM. These might even be seperate issues, I'm trying to figure it out

Regarding logs - stupid me: there was an error in the SQL logs before I had to deactivate Friendica for the moment (because its crashing my webserver)

I can see multiple errors like the following in the DB logs:
`[Warning] Aborted connection 75 to db: 'friendica' user: 'friendica' host: 'localhost' (Got an error writing communication packets)`

**Comment by annando** [comment]
The Friendica log is where you have set it up. Can you remember if you had activated it at all?

**Comment by MrPetovan** [comment]
Can they set it up like this from the command line?
```
bin/console system logfile friendica.log
bin/console system loglevel notice
bin/console system debugging 1
```

**Comment by oe4dns** [comment]
I have not set it up explicitely, but I will now do so from the console

**Comment by oe4dns** [comment]
Following advice I got from the Friendica Matrix room, I'm first purging 43 Million (!) activitypub-troll.cf entries from the databases gserver table. I blocked them asap when that issue arrived, but seemingly not quickly enough. Maybe it is just a performance problem after all, but further investigation will have to wait until the database is cleaned up a bit.

**Comment by oe4dns** [comment]
After some more discussion in the Matrix room and further investigation, I came to the conclusion that file permissions could be behind the "Service Unavailable" Error.

Prior to the current 2022.04 Version, I pulled from Friendica's  Github as Root. So most of the files belonged to root:root which did not pose a problem until now. Suspecting file permissions, I moved everything to www-data and Friendica started working again - meaning the Web-UI showed up in the browser.

I suspect that issue https://github.com/friendica/friendica/issues/13032 is related to this. Deleting the "compiled" folder might recreate it with correct permissions. But I did not look into this myself. This issue is fixed for me!

worker.php eating up all RAM is most likely a seperate thing and might be connected to upgrading a database still containing 43 Million entries from the activitypub-troll.cf activity earlier this year. I'm currently purging the DB and will try to run the DB upgrade afterwards. If this turns out to work as expected I will close this issue as solved!

**Comment by HankG** [comment]
> Following advice I got from the Friendica Matrix room, I'm first purging 43 Million (!) activitypub-troll.cf entries from the databases gserver table. I blocked them asap when that issue arrived, but seemingly not quickly enough. Maybe it is just a performance problem after all, but further investigation will have to wait until the database is cleaned up a bit.

The gserve entries were coming from updates from infected Mastodon servers not from direct communications with the troll servers that never existed.  Thankfully this won't happen after 2023.04.

**Comment by ghost** [comment]
> Prior to the current 2022.04 Version, I pulled from Friendica's Github as Root. So most of the files belonged to root:root which did not pose a problem until now.

I did that once by mistake and afterwards I had a WSOD because the whole folder had root as owner.

**Comment by oe4dns** [comment]
After cleaning the database and fixing file permissions, this problem is solved.

To recapitulate for anyone running into similar problems, there were two issues involved:

* "Service Unavailable" screen coming up after the upgrade instead of Friendica's normal Web-UI - This was due to wrong file permissions in the Friendica webserver directory. Files should belong to the webserver user - e.g. www-data on Debian Linux and related Distributions

* worker.php process using all the system's memory until the server crashes. Here the reason is not entirely clear. It could also be a file permissions problem or the database simply was to big for the upgrade on a system with only 8 GB RAM. I did remove 43 Million entries from the troll server problem earlier this year and optimized the gserver table. After that worker.php only uses a few % of RAM and everything looks fine.

**Comment by mend0za** [comment]
> Following advice I got from the Friendica Matrix room, I'm first purging 43 Million (!) activitypub-troll.cf entries from the databases gserver table. 

I also located a huge amount of gab.best entries on my instance, in addition to  activitypub-troll.cf. Now waiting forever until remove them all.
