### ISSUE TITLE
Private Messages flaw

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#13026]
- [ X] I have searched open and closed issues for duplicates

### Bug Description

Composing private Messages don´t work in Friedica 2023.04

### Steps to Reproduce

1.  Open Private Messages
2.  Try to create a ne private Message via the "+" Button

Actual Result:

It won´t work you get a 550 Error. 

Error Messages provided from other admins:
```
TypeError: Cannot access offset of type string on string in /var/www/html/view/smarty3/compiled/67/5d/4e/675d4ecb09a737a51110c0f1840ef4487aa1be4e_2.file.message_recipient.tpl.php:32
Stack trace:
#0 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_644553cc4d1d03_80577142()
#1 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#3 /var/www/html/vendor/smarty/sm
```
It worked seamless in the lates pull of 2023.03.RC
It seeams that thias is Php 8.0 related (not sure)

Expected Result:

You could create a new private message.

### Platform Info

Friendica Version: 2023.04

**Comment by utzer** [comment]
Just for information, I only get a WSOD, nothing else. I think others also have the empty page and not fault.

**Comment by AlfredSK** [comment]
Maybe related to this...
https://github.com/friendica/friendica/pull/13019

**Comment by AlfredSK** [comment]
Yep. I'm still on RC. Checking out one commit before above mentioned PR solves the issue.

`Head is: 9dc5557fb Merge pull request #13018 from annando/share-federated`
