### ISSUE TITLE
Twidere: Likes, Dislikes and Comments produce "mention" notifications

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1303]
When liking, disliking or commenting on a post, a connected twidere instance notifies the user that did it as if he/she has been mentioned by someone else, which is confusing and not the desired behaviour.

**Comment by tobiasd** [comment]
This is not a bug it seems. The problem is, that the "mention" tab in Twidere is more like the "personal interaction tab" in the Friendica network stream.

I'm hence closing the issue.
