### ISSUE TITLE
Shortcut for sharing/sending a post

### ISSUE THREAD

**Issue by DerPivit** [friendica/friendica#13039]
### Is the feature request related to a problem? Please describe.

I do not always want to grab my mouse for sending a post.

### Describe the feature you'd like

I'd love a shortcut like "Strg-Enter" for sending/sharing. See how Mastodon/Hubzille handle that...

**Comment by foss-** [comment]
`ctrl + enter` or `cmd + enter` are fairly common.
If this is implemented, this should also work in comments. Maybe that needs no additional work, just something to keep in mind / test.

**Comment by foss-** [comment]
What's missing here? Sending posts and comments worked fine in a brief test using cmd + enter on macOS.
