### ISSUE TITLE
on current dev avatar image vanished

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13034]
Unsure why but reporting that on `This is Friendica, version 2023.06-dev that is running at the web location https://pirati.ca. The database version is 1518/1518, the post update version is 1507/1507.` avatar image vanished with me changing anything.

Maybe others on current dev can double check and report what they see.

**Comment by MrPetovan** [comment]
It happened to me yesterday too, my own account's profile picture reverted to default image. Changing back my profile picture worked.

**Comment by foss-** [comment]
Some time has passed, this has not occurred again. Seems to have been a one time glitch. Probably nothing actionable. Closing.
