### ISSUE TITLE
Service not available after upgrade

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#13040]
Hi all, I did search github and saw only two solutions, which were to check my directory owners/permissions, which I did. I also deleted the Smarty directory which was also recommended.

Neither of these worked.

The error I'm getting is an HTTP 500.

The server is fine, and the CPU and other states aren't redlining at all.  The permissions/user is www-data. I did try to hit the url/udpate.php, and that didn't 500 but rather gave me a white page.

Any ideas?

**Comment by MrPetovan** [comment]
White pages and 500 error should leave traces in your log, either Friendica/PHP/web server.

**Comment by jakedfw** [comment]
I couldn't find any errors in the PHP log.

Apache log:

```
  GNU nano 6.2                                                       kerr.social.error.log.1                                                                 
[Wed Apr 26 22:22:02.129709 2023] [php:warn] [pid 1737] [client 139.59.251.58:60580] PHP Warning:  require(/var/www/friendica/vendor/phpseclib/phpseclib/php>
[Wed Apr 26 22:22:02.129812 2023] [php:error] [pid 1737] [client 139.59.251.58:60580] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/fr>
[Wed Apr 26 22:22:06.763625 2023] [php:warn] [pid 1180] [client 139.59.251.58:43232] PHP Warning:  require(/var/www/friendica/vendor/symfony/polyfill-intl-i>
[Wed Apr 26 22:22:06.763669 2023] [php:error] [pid 1180] [client 139.59.251.58:43232] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/fr>

**Comment by annando** [comment]
Have you executed the composer to update the vendor folder?

**Comment by jakedfw** [comment]
DId I miss that in the upgrade instructions on the website?
How do I do that?

**Comment by jakedfw** [comment]
Wait. I think I figured it out. I forgot to update addons! Updating now.

**Comment by annando** [comment]
Also with the composer see here: https://github.com/friendica/friendica/blob/develop/doc/Composer.md

**Comment by jakedfw** [comment]
Oh crap. I deleted the smarty folder, and now I'm getting this error (even though the directory doesn't exist): 
<img width="879" alt="image" src="https://user-images.githubusercontent.com/38843638/234759790-325d5856-7acc-4046-834e-bc3be8f22d50.png">

**Comment by jakedfw** [comment]
Okay, I fixed it. 

Ran the addons update
Manually restored the smarty3 directory
CHOWN smarty3 to www-data

Boom. all good now.

thank you!
