### ISSUE TITLE
Connection Requests unavailable right after notification on Mastodon API

### ISSUE THREAD

**Issue by HankG** [friendica/friendica#13056]
### Bug Description

The Mastodon API endpoint for doing connection request adjudication seems to have a delay in getting an actual available connection request. This is manifesting in Relatica as an invalid connection request panel (the way it error statuses it). It takes between 5-10 minutes against my server for the request to actually start working. I assumed there was some worker that had to finish getting something done but the work queue was empty the entire period from about 1 minute after the request came in until it became available at about 5 minutes after the request came in.

### Steps to Reproduce

1.  Initiate a connection request from a remote server
2. Notice notifications generated both through the Mastodon API and the main UI
3. Notice that the web UI panel for adjudicating it is available (but do not accept/reject it)
4. Notice that the request for the connection request that came over the Mastodon notifications API will not work for a period of time (up to 5-10 minutes).

Actual Result:

The API endpoint doesn't know about the request for a period of time even though the notification exists. Eventually, 5-10 minutes later, the end point works

Expected Result:

The API endpoint should work at the same time that the notifications are generated and the adjudication is available in the API

Friendica Version: 2023.04

**Comment by annando** [comment]
Are you sure that there isn't possibly any caching enabled on your web server?

**Comment by HankG** [comment]
> Are you sure that there isn't possibly any caching enabled on your web server?

Only what is in the default Apache configuration.

**Comment by HankG** [comment]
I'm not seeing this happening on my server any longer so I'm going to close this for now.
