### ISSUE TITLE
`/api/v1/notifications` endpoint is not Mastodon compatible

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13052]
- [x] I have searched open and closed issues for duplicates

### Bug Description

https://wiki.friendi.ca/docs/api-mastodon says `/api/v1/notifications` is defined according to the Mastodon API reference (https://docs.joinmastodon.org/api/).

At least the `limit` parameter is not compatible. The Mastodon docs (https://docs.joinmastodon.org/methods/notifications/#query-parameters) for the `limit` parameter say:

> Integer. Maximum number of results to return. Defaults to 15 notifications. Max 30 notifications.

Friendica's default is 20, not 15 (https://github.com/friendica/friendica/blob/develop/src/Module/Api/Mastodon/Notifications.php#LL62C1-L62C1 @ most recent commit 4abb7ed)

```
		$request = $this->getRequest([
			'max_id'        => 0,     // Return results older than this ID
			'since_id'      => 0,     // Return results newer than this ID
			'min_id'        => 0,     // Return results immediately newer than this ID
			'limit'         => 20,    // Maximum number of results to return (default 20)
			'exclude_types' => [],    // Array of types to exclude (follow, favourite, reblog, mention, poll, follow_request)
			'account_id'    => 0,     // Return only notifications received from this account
			'with_muted'    => false, // Pleroma extension: return activities by muted (not by blocked!) users.
			'include_all'   => false,  // Include dismissed and undismissed
			'summary'       => false,
		], $request);
```

In addition, it seems as through Friendica does not impose the "Max 30 notifications" limit either. If a client requests more notifications than that then more notifications are returned.

I am unsure if this should be treated as a code bug or a documentation bug.

**Comment by HankG** [comment]
Yeah our limits are certainly different, both absolute and default. The slowness is a secondary problem though because it still isn't returning more than 100 elements and even smaller queries take a while to run. I imagine we are doing something requiring full table scans which may or may not be avoidable.

**Comment by nikclayton** [comment]
As I've just discovered, Mastodon have recently changed the limits to default = 40, max = 80 (https://github.com/mastodon/mastodon/issues/24684#issuecomment-1529059080).

Rather than having to repeatedly chase their limits it might be better if your docs are explicit about what the Friendica limits are.
