### ISSUE TITLE
Server errors on calls to /api/v1/streaming/public/local

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13055]
In my log I find a number of 501 error codes for calls to `/api/v1/streaming/public/local`. Interesstingly all from a singe client ip.
Is this endpoint not implemented? 

Friendica 2023.04-1

**Comment by HankG** [comment]
The streaming endpoints are not implemented at this time and don't have a timeline for being implement right now :( https://wiki.friendi.ca/docs/api-mastodon#non_supportable_endpoints

**Comment by ne20002** [comment]
In this case I will serve the 501 from the reverse proxy for this api and reduce load on the Friendica instance.
Thanks for info.
