### ISSUE TITLE
Events from the past are shown in the reminder

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1306]
The screenshot has been taken today. Although it is correct if you label it "Events this week", it is of no use with the heading "Events reminders" and I doubt that anyone needs the link to past events at this prominent place.

![screenshot-snarl de 2015-01-23 10-10-20](https://cloud.githubusercontent.com/assets/3009959/5872160/629b665c-a2e8-11e4-9b25-06f146e13f2f.png)

**Comment by tobiasd** [comment]
On Fri, 23 Jan 2015 01:13:32 -0800
Hauke Altmann <notifications@github.com> wrote:

> The screenshot has been taken today. Although it is correct if you
> label it "Events this week", it is of no use with the heading "Events
> reminders" and I doubt that anyone needs the link to past events at
> this prominent place.

So you suggest only show the calendar entries from today till today+7? Or better labelling in the interface?

**Comment by tugelbend** [comment]
I think only future events should be shown and the Label "Events this week" should be changed to "Next up" with a limitation to 3 events.

**Comment by rabuzarus** [comment]
some side notes to the events reminder:
Yes, the events reminder should remind maximal from today up to +7 days. I'm not sure if it should limit to 5 events at the same time. For my personal use case it would be enough. But maybe there are other use cases. E.g. using friendica in a buisness or as social platform on conferences or only to show the paties/events of my hometown from today.

I don't really know how to deal with the problem. The best way would be it would be configurable (but to much options are bad for ux)

What I want to say/ask. Why should the number of visible events be five? 
Personally I have no problem with a number of 5 future events. But does it fit to the needs of the user? It's maybe something which should discussed in the ux-group at a later point.

OT: In my personal view the events reminder should be a widget on the side. With a specific number of unclollapsed upcoming events (like in some wordpress blogs). So the user can easily recordnize upcoming events at the first glance (without a click). But that is something the new ux-group have to decide.

**Comment by tugelbend** [comment]
I think there are different levels to discuss this issue. My bug report is aimed to fix an UI element that currently makes no sense quick. And go for the broader discussion if it would make sense to put it f.e. in a side widget later. Right now we don't even know if we will have side widgets in the new theme. I don't think we should stop improving the existing interfaces to wait for the new one (which surely will need some months to be finished).

I agree that the best options might be to make it configurable for the needs of the user and that there might be users that need more then five events shown. However, I think that one of the issues of the friendica UI is that it's undecided or to put it in other words, "if your target group is everyone, you will build an interface that works for no one". In my opinion, five events on this element are enough. To see more events, the user can open the (barely usable ;-)) calendar.

**Comment by tobiasd** [comment]
Well I like how quattro is including the calendar of the next week showing the events on the network tab instead of this simple text overview thing. It's a theming issue and one reason almost all my themes were derived from quattro ;-)

**Comment by tugelbend** [comment]
That's (at least for me) the ugly part of theming: To find out if this is a theme issue or a general friendica problem. And theme inheritance is making it worse. Should we add labels for the supported themes to make this more clear? 

However, back to the bug report: This behavior appears in vier.

**Comment by rabuzarus** [comment]
Sry, I don't want to discourage somebody from improving the existing interfaces. And your points are all valid. 
My comment should be only one side note for future discussions. Nothing which should solved in the present.

**Comment by annando** [comment]
The pull request https://github.com/friendica/friendica/pull/1467 is now complete. There was some problem with the timezones. Hopefully they are solved now.

**Comment by annando** [comment]
The pull request is merged, so I close the issue.
