### ISSUE TITLE
rel=me verification

### ISSUE THREAD

**Issue by shiribailem** [friendica/friendica#13079]
Pretty self explanatory, it would be nice to implement rel=me in a similar fashion to Mastodon as it would allow accounts to confirm themselves as the official entities.

Probably already vaguely on the roadmap, but figured I'd make an actual official entry for it.

**Comment by MrPetovan** [comment]
You can already input a single URL in the "Homepage URL" profile field which page will be checked for `rel="me"` backreference;
![image](https://user-images.githubusercontent.com/925415/236103846-3bcbc611-0415-4911-9e4a-62ec72b35a8e.png)

The result is shown discreetly on your vCard:
![image](https://user-images.githubusercontent.com/925415/236104022-9482a92b-4e25-4810-8942-3249d9c47294.png)

**Comment by MrPetovan** [comment]
Oh, and your Homepage URL also includes a `rel="me"` attribute so that the verification can be two ways:
```html
<div class="homepage detail">
	<span class="homepage-label icon"><i class="fa fa-external-link" title="Homepage:"></i></span>
	<span class="homepage-url u-url">
		<a href="https://mrpetovan.com/" rel="me" target="_blank" rel="noopener noreferrer">https:<wbr>/<wbr>/mrpetovan<wbr>.com</a>
		<span title="This website has been verified to belong to the same person.">✔</span>
	</span>
</div>
```

**Comment by shiribailem** [comment]
Whelp, that was fast lol.

I think the reason I never noticed it before was that I really don't have any Friendica contacts yet. Does it also show the verification in searches and on posts, or just on the profile page?

I guess the big thing will instead be figuring out what the barrier is to Friendica accessing Mastodon profile details so it can verify those profiles?

**Comment by shiribailem** [comment]
Kinda answered my question when I went to follow your profile ;-)

Looks like verification is only done on the account server, and is also therefore only on the profile page (and only on the profile page that's hosted on the server).

Will make a new request for more specific request details.

**Comment by MrPetovan** [comment]
The result of the verification is only shown on this vCard that shows on your profile and next to your top-level posts when displayed in a single conversation page.

For your second question, Mastodon profiles would have to expose a `rel="me"` link to the Friendica profile page for this feature to work. This is the standard way to verify a remote URL, the same way Mastodon does, even if they support multiple URLs when we only support one at the moment.

**Comment by shiribailem** [comment]
So I think some of the confusion there in my thoughts is that I also don't agree with relying on only their profile server to provide verification.

That is, it would be entirely possible and trivial for an admin to falsify a verification via rel=me on their own page, but if other servers double checked it then it couldn't be falsified.

And along those lines for Mastodon support the intent was that it would pull the link from their profile and check it, and I guess in the feature request I make in a minute I'll also be requesting the same for Friendica posts as well because I guess it's really just pulling very little of the data in general.

**Comment by MrPetovan** [comment]
What kind of "falsification" are you talking about?

**Comment by shiribailem** [comment]
Simplest way: edit your hosts file to redirect the website to a static page you control, voila you can pass verification for any page you want on your own server (but if we were double checking it it would be caught)

**Comment by MrPetovan** [comment]
If you control the hosts file of the Friendica server where the verification is done you can already add a static checkmark to the profile template, no need for a fancy tech solution. Your feature request actually answered my question about the falsification.

This said, so far the verification has been mostly intended for users on the same server which implies a shared trust in the node admin.
