### ISSUE TITLE
Umlauts not correctly displayed in Links

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1307]
I just noticed that Umlauts are not correctly displayed in the Headlines of my some postings (See example). This doesn't seem to be a general issue but only in some contexts (links maybe). 

![screenshot-snarl de 2015-01-23 13-03-42_umlauts](https://cloud.githubusercontent.com/assets/3009959/5874340/abcf5a0a-a300-11e4-8b93-186110a7452c.png)

![screenshot-snarl de 2015-01-23 13-07-00_umlauts2](https://cloud.githubusercontent.com/assets/3009959/5874368/e943026a-a300-11e4-9442-44a4ef636233.png)

**Comment by Beanow** [comment]
Can you check the character encoding for the page and whether html entities are used for the ones that do work?

Encoding:
```html
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
```
![FF Network tab](http://ss.oscp.info/2015-01-23_13-43-22.png)

**Comment by silke** [comment]
I don't have this issue. Umlauts in Links are correct here.

**Comment by annando** [comment]
There was an issue with umlauts several versions ago. Maybe snarl just needs an update.

**Comment by tugelbend** [comment]
I think I am on the latest release. I'll check tomorrow.

**Comment by silke** [comment]
Is this still an issue?

**Comment by annando** [comment]
I - personally - don't think so. Maybe we should switch snarl.de to the 3.3.3 to see if there are still issues.

**Comment by tugelbend** [comment]
Snarl is on the 3.3.3 release branch. The issue still exists.

**Comment by annando** [comment]
it will not be for old stuff but only for new content.

**Comment by silke** [comment]
I still do not have this on 3.3.3. Character encoding is like beanows, everything's fine.

**Comment by tugelbend** [comment]
Character encoding ist correct:
```html
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
```

As the problem only exists for specific content, which is headline links underneath images, I assume that there is an issue when fetching/processing incoming data. I've got this issue with RSS feeds from Taz and Sueddeutsche. Umlauts everywhere else are displayed correctly.

I cannot connect to the snarl database without my nodebook. So I will check how the data is saved in the database later.

**Comment by tugelbend** [comment]
Some more notes: Looking at the HTML source, the Umlaut is missing completely. So no wrong encoding, it's simply not there. And this issues does not apply when accessing the content via api (using f.e. twidere).

**Comment by gitkald** [comment]
Same problem on my friendica system. No umlauts in RSS Feeds messages. I Use the newest friendica release.

**Comment by tugelbend** [comment]
I made some progress finding the cause of the issue: It's in includes/bbcode.php, line 42ff

<pre>
//$title = htmlentities($title, ENT_QUOTES, 'UTF-8', false);
$title = bbcode(html_entity_decode($title), false, false, true);
$title = str_replace(array("[", "]"), array("&#91;", "&#93;"), $title);
</pre>

Uncommenting the first line and commenting the second and third makes the issue disappear on my server. Michael introduced this in january: https://github.com/friendica/friendica/commit/bf147ca9d96df6e3ab38001b34349dae0e74ed45#diff-f228b89ec4b9c9ef9457ec748c08cbb2

Next step is to find out, why this isn't working on my server. Maybe a default encoding issue of the system.

**Comment by annando** [comment]
see here: http://php.net/manual/en/function.html-entity-decode.php

> If omitted, the default value of the encoding varies depending on the PHP version in use. In PHP 5.6 and later, the default_charset configuration option is used as the default value. PHP 5.4 and 5.5 will use UTF-8 as the default. Earlier versions of PHP use ISO-8859-1.

**Comment by silke** [comment]
Hey @tugelbend, I just tested again on the freifunk friendica instance and it doesn't have this issue any more.

**Comment by annando** [comment]
Could someone (tm) create a new pull request for the 3.4?

**Comment by annando** [comment]
I just realized that it was only reverted in another branch. The release branch seems to be okay. I'm closing this issue.
