### ISSUE TITLE
User Can't Change Addon Settings

### ISSUE THREAD

**Issue by shiribailem** [friendica/friendica#13073]
Until it gets rolled out into standard usage, I felt it would be good to have an open bug report of this even though a fix is in the dev version.

This regards: https://github.com/friendica/friendica-addons/pull/1354/commits/53524e235205857013730729b9b369cfc7ea56bf

Despite not using the mailstream addon, this bug was causing the page to crash when I tried to change any user addon settings (blank white page whenever hitting save).

For those facing this problem the fix is to either apply that small change to the file or remove the mailstream addon from the addons directory.

As I said, I'm just creating this to help people find support faster for this situation until it's rolled into production.

**Comment by tobiasd** [comment]
The bug was fixed in the current 2023.06 development version of the addon. See https://git.friendi.ca/friendica/friendica-addons/pulls/1377 for the necessary change which will also work in 2023.04-1

**Comment by shiribailem** [comment]
@tobiasd Yes, I linked to the exact line change because it both acknowledges the fix and shows someone how to fix it.

Basically this is just so people who are having this problem can find an answer and fix it easily before 2023.06 comes out. Because me and a couple of other people spent probably an hour in the matrix chat tracking down what was happening.

And instead of talking about the error specifically this is talking about the impact, making it easier to find than the pull request.

**Comment by MrPetovan** [comment]
Thank you for the write-up, we usually close issues for which a patch has been merged in develop, was this your intention with this issue?

**Comment by shiribailem** [comment]
My purpose was just to put it somewhere with reasonable search visibility so others affected would do less blind groping. I leave it to maintainer discretion whether it should be open or closed.

Though this does make me think we could use a more traditional searchable support forum.

**Comment by MrPetovan** [comment]
Got it, thanks! What is a "more traditional searchable support forum"?

**Comment by MrPetovan** [comment]
Closed by https://git.friendi.ca/friendica/friendica-addons/pulls/1377

**Comment by shiribailem** [comment]
@MrPetovan our current support forum on platform is designed more as a stream of communication (as is the whole platform), so it's not really something you can search and navigate. A "traditional style" would be like your regular forum websites, because they have categories and search indexes (and are index by search engines) that allow you to find previous issues faster. Some of that is covered by the Github issues, but it also means that alot of support issues end up here that aren't actually a development problem... basically clogging up the issue tracking.

I don't see this as a fault with Friendica/ActivityPub but rather just a different niche (it would be like judging ActivityPub for not being Matrix or email). The social format is for more immediate and timely communication, especially without algorithmic sorting because if you're not there to see it at the time then you often don't see it at all. A traditional forum however is designed where something could sit for hours, days, even potentially a few weeks and still get attention.
