### ISSUE TITLE
Implement passkeys (WebAuthn) for user login

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#13083]
### Is the feature request related to a problem? Please describe.
No.

### Describe the feature you'd like
Implement passkeys for user login, also called [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn). 

### Describe alternatives you've considered
This is some new unfishable way to login to systems, it is some kind of one time password. 

### Additional context
Google released this for login today.
https://blog.google/technology/safety-security/the-beginning-of-the-end-of-the-password/

PHP library for WebAuthn
https://github.com/web-auth/webauthn-lib

**Comment by lapo-luchini** [comment]
Seems a duplicate of #12172.

**Comment by MrPetovan** [comment]
I knew the protocol name was familiar!

**Comment by utzer** [comment]
Ah sorry about that.
