### ISSUE TITLE
Cron problem when running PHP 8.1

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13089]
I have searched open and closed issues for duplicates

### Bug Description

I am a college instructor working on writing handouts on how to install and use Friendica (among many PHP based open source programs). I have two Virtual Private Servers. One runs PHP 7.4 by default. However, before I install Friendica, I manually set the domain to 8.1. The other VPS runs PHP 8.1 by default. Before I install Friendica, I also manually set this domain to 8.1. 

I then install **Friendica version 2023.04-1** from a zipped file in the same way on both websites. I then use the same command to create the cron job. 

However, while the server that uses PHP 7.4 by default successfully runs the cron job, the server that uses PHP 8.1 by default results in the following error: 
/bin/sh: 1: cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html: not found
/bin/sh: 1:  /usr/bin/php: not found

Here is the cron command for the server that works: 
cd /home/ctct10f/web/friends.communitynetwork.us/public_html; /usr/bin/php bin/worker.php

Here is the cron command for the server that does not work. 
cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html; /usr/bin/php bin/worker.php

### Steps to Reproduce

Strangely, when I change the cron command on the 8.1 VPS to tell it to specifically use PHP 7.4: 
cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html; /usr/bin/php7.4 bin/worker.php
Then the cron job works. However, I still get this error: 
/bin/sh: 1: cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html: not found
/bin/sh: 1:  /usr/bin/php7.4: not found

I have checked the path many times and the path is correct even though the error email sent from Friendica claims that the path can not be found. 

I have also checked the system base path in the local.config.php file and it is correct. 

Also the 'php_path' => '/usr/bin/php',
is also correct. 

Finally, when I change the PHP system default setting on the server that was running 8.1 to PHP 7.4, the error messages stop being transmitted and all is well. 

Expected Result:

I really need the default system server to be PHP 8.1 – in which case neither of my Friendica website cron jobs would run and both would be sending error messages. 

### Platform Info

Friendica Version: Friendica version 2023.04-1 

Friendica Source: From the release announcement page. 

PHP version: 8.1 does not work and 7.4 does work

My conclusion is that Friendica Cron jobs work fine with PHP 7.4 but have a problem when the VPS system default is PHP 8.1. I hope this problem can be fixed. Let me know if there is anything more I can do to help.

**Comment by MrPetovan** [comment]
Thank you for your report, however the errors you are getting from the shell don't seem to be related to the Friendica code but rather your hosting environment. In particular, the emails you are receiving come from the cron executable, not Friendica itself. May I ask how you set a specific domain to work with PHP 8.1?

**Comment by davidspring** [comment]
I am using the open source Hestia Control Panel. There is a default admin user and in the settings, one can set the default PHP version. When this default is set for 7.4, the error email is not sent and the cron jobs run. When the default is set to 8.1, the cron job does not run and the error email is sent. 
I have also created a user account for each website. When adding a domain name to the user account, one can select a PHP version. On both domains, I set the domain to 8.1 – which then overrides the system PHP version. 

However, the cron command – which does not specify the PHP version - called the system PHP version rather than the domain PHP version. 

I should add that I also set cron jobs for my Moodle and Joomla websites and all of those cron jobs work without problem with PHP 8.1. This leads me to believe that there is a problem with Friendica cron jobs and PHP 8.1.

**Comment by MrPetovan** [comment]
Do you have access to a terminal console in the Hestia Control Panel? I'd like to verify a few things in the 7.4 mode and the 8.1 mode.

**Comment by davidspring** [comment]
Yes. I have access to the terminal. Let me know the command and I will post the response.

**Comment by MrPetovan** [comment]
Please run these commands both when PHP version 7.4 is set and when PHP version 8.1 is set.
```
whoami
```
```
php --version
which php
ls -al /usr/bin/php*
```
```
cron -l
```
```
ls -al /home/bfn16b/web/washingtonparentsnetwork.org/public_html
ls -al /home/bfn16b/web/washingtonparentsnetwork.org
ls -al /home/bfn16b/web
ls -al /home/bfn16b
```

**Comment by davidspring** [comment]
Here is the result when PHP 7.4 is set for the system PHP and I have ssh into the server as root: 
whoami
root
php --version
PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

which php
/usr/bin/php

ls -al /usr/bin/php*
lrwxrwxrwx 1 root root      21 Nov  5  2021 /usr/bin/php -> /etc/alternatives/php
-rwxr-xr-x 1 root root 4760504 Feb 22 20:07 /usr/bin/php7.4
-rwxr-xr-x 1 root root 4949168 Oct 28  2022 /usr/bin/php8.0
-rwxr-xr-x 1 root root 5530984 Apr 14 04:39 /usr/bin/php8.1

I have modified the commands you want slightly since this is a Linux Debian 11 server with the username of bfn16b and thus these commands did not work: 
cron -l
cron -u -l
so I replaced them with these commands which indicate that there were no root cron jobs and only one cron job for the user bfn16b. 

crontab -l
reply was no crontab for root 

crontab -u bfn16b -l
MAILTO=davidspring@protonmail.com
CONTENT_TYPE="text/plain; charset=utf-8"
*/10 * * * * cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html; /usr/bin/php bin/worker.php

ls -al /home/bfn16b/web/washingtonparentsnetwork.org/public_html
drwxr-x--x 14 bfn16b www-data   4096 May  1 04:30 .
dr-xr-x--x  8 bfn16b bfn16b     4096 May  4 20:37 ..
-rw-r--r--  1 bfn16b bfn16b     1554 May  1 04:30 .htaccess
-rw-r--r--  1 bfn16b bfn16b     1554 Apr 26 22:34 .htaccess-dist
-rw-r--r--  1 bfn16b bfn16b   126733 Apr 26 22:35 CHANGELOG
-rw-r--r--  1 bfn16b bfn16b     4539 Apr 26 22:34 CREDITS.txt
-rw-r--r--  1 bfn16b bfn16b    34523 Apr 26 22:34 LICENSE
-rw-r--r--  1 bfn16b bfn16b     4171 Apr 26 22:34 README.md
-rw-r--r--  1 bfn16b bfn16b       10 Apr 26 22:35 VERSION
drwxr-xr-x 85 bfn16b bfn16b     4096 Apr 26 22:26 addon
drwxr-xr-x  2 bfn16b bfn16b     4096 Apr 28 20:26 bin
drwxr-xr-x  2 bfn16b bfn16b     4096 May  3 19:06 config
-rw-r--r--  1 bfn16b bfn16b   150657 Apr 26 22:35 database.sql
drwxr-xr-x  6 bfn16b bfn16b     4096 Apr 26 22:34 doc
drwxr-xr-x  5 bfn16b bfn16b     4096 Apr 26 22:34 images
-rw-r--r--  1 bfn16b bfn16b     1946 Apr 26 22:34 index.php
drwxr-xr-x  2 bfn16b bfn16b     4096 Apr 26 22:34 mod
drwxr-xr-x  5 bfn16b bfn16b     4096 Apr 26 22:34 mods
-rw-r--r--  1 bfn16b bfn16b     2915 May  1 04:23 old-index.html
-rw-r--r--  1 bfn16b bfn16b       66 May  1 04:23 robots.txt
-rw-r--r--  1 bfn16b bfn16b      219 Apr 26 22:34 security.txt
drwxr-xr-x  2 bfn16b bfn16b     4096 Apr 26 22:34 spec
drwxr-xr-x 24 bfn16b bfn16b     4096 Apr 26 22:35 src
drwxr-xr-x  2 bfn16b bfn16b     4096 Apr 26 22:34 static
-rw-r--r--  1 bfn16b bfn16b    44342 Apr 26 22:34 update.php
drwxr-xr-x 40 bfn16b bfn16b     4096 Apr 26 22:35 vendor
drwxr-xr-x 11 bfn16b bfn16b     4096 Apr 26 22:35 view

ls -al /home/bfn16b/web/washingtonparentsnetwork.org
dr-xr-x--x  8 bfn16b bfn16b   4096 May  4 20:37 .
drwxr-xr-x  3 bfn16b bfn16b   4096 May  1 04:23 ..
drwxr-x--x  2 bfn16b bfn16b   4096 May  1 04:23 cgi-bin
drwxr-x--x  2 bfn16b bfn16b   4096 May  4 20:37 document_errors
dr-xr-x--x  2 bfn16b bfn16b   4096 May  4 20:37 logs
drwxr-x--x  2 bfn16b bfn16b   4096 May  1 04:23 private
drwxr-x--x 14 bfn16b www-data 4096 May  1 04:30 public_html
dr-xr-x--x  2 bfn16b bfn16b   4096 May  1 04:23 stats

ls -al /home/bfn16b/web
drwxr-xr-x   3 bfn16b bfn16b 4096 May  1 04:23 .
drwxr-xr-x+ 13 root   root   4096 Aug 23  2022 ..
dr-xr-x--x   8 bfn16b bfn16b 4096 May  4 20:37 washingtonparentsnetwork.org

ls -al /home/bfn16b
drwxr-xr-x+ 13 root   root   4096 Aug 23  2022 .
drwxr-xr-x  34 root   root   4096 Apr 22 08:17 ..
-rw-r--r--   1 bfn16b bfn16b  220 Aug  4  2021 .bash_logout
-rw-r--r--   1 bfn16b bfn16b 3526 Aug  4  2021 .bashrc
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .cache
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .composer
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .config
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .local
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .npm
-rw-r--r--   1 bfn16b bfn16b  807 Aug  4  2021 .profile
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .ssh
drwxr-xr-x   2 bfn16b bfn16b 4096 Aug 23  2022 .vscode-server
drwxr-xr-x   5 root   root   4096 Aug 23  2022 conf
drwxr-x--x   3 root   root   4096 May  1 01:11 mail
drwx------   5 bfn16b bfn16b 4096 May  3 13:15 tmp
drwxr-xr-x   3 bfn16b bfn16b 4096 May  1 04:23 web


Here is the result when PHP 8.1 is set for the system PHP and after restarting php8.1-fpm then ssh in to the server as root: 
whoami
root

php –version
PHP 8.1.18 (cli) (built: Apr 14 2023 04:39:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.18, Copyright (c), by Zend Technologies

which php
/usr/bin/php

ls -al /usr/bin/php*
lrwxrwxrwx 1 root root      21 Nov  5  2021 /usr/bin/php -> /etc/alternatives/php
-rwxr-xr-x 1 root root 4760504 Feb 22 20:07 /usr/bin/php7.4
-rwxr-xr-x 1 root root 4949168 Oct 28  2022 /usr/bin/php8.0
-rwxr-xr-x 1 root root 5530984 Apr 14 04:39 /usr/bin/php8.1

crontab -l
reply was no crontab for root 

crontab -u bfn16b -l
MAILTO=davidspring@protonmail.com
CONTENT_TYPE="text/plain; charset=utf-8"
*/10 * * * * cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html; /usr/bin/php bin/worker.php

Note that all of the other commands resulted in the same for php8.1 as php7.4 as the folder structure did not change. 

Also it turns out the emails with the error messages continued even after switching the system PHP to 7.4. They were just delayed. So there appears to be something else wrong with my BFN server that is not wrong with my CTC server (even though they are supposed to be identical). 

Any commands or tools I can use to figure out what the differences might be between these two servers? If I can figure this difference out, this could be an important clue in determining what is wrong. 

Happy to enter any more commands that you may want.

**Comment by davidspring** [comment]
To be clear, I have not changed the PHP system setting on the ctc server from 7.4 to 8.1 because I have websites that I am afraid would be adversely affected by the switch. 
I thought that the only difference between these two servers was the system PHP setting. But there is clearly some other difference between the two servers which is causing the error emails to be sent on the bfn server but not on the ctc server. I have been trying to figure out the difference for several days and the only difference I could find was that bfn was set for 8.1 and ctc was set for 8.1. 

I would be happy to give you root access to both servers if you would be interested in taking a look at them. Both servers have several friendica sites in various stages of development. They also have numerous Joomla sites and a few Moodle sites and a few Next cloud sites.

**Comment by MrPetovan** [comment]
Thank you, I'm out of my depth in system administration, I've called a friend for help, I'll report back with their suggestion.

**Comment by davidspring** [comment]
Thank you for your assistance. As I said, I have spent several days on this issue. It is a major problem that one server works with Friendica cron jobs and the other server does not. Both servers work with cron jobs for several other PHP programs. So I still think there must be some problem with Friendica.

**Comment by Raroun** [comment]
```
/bin/sh: 1: cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html: not found
/bin/sh: 1: /usr/bin/php7.4: not found

```
indicates that the shell has some problems with the path´s from where its called.

What you you could try:

Its probably better to do a single call in CRON and not multiple commands in one line.
Also Cron isn´t allways aware it should use bash.

example crontab with bash script:

`*/10 * * * * /bin/bash -c "/home/bfn16b/friendicaworker.sh"`

Create the bash script "/home/bfn16b/friendicaworker.sh" that changes directory und calls the worker und put that shell script in the CRON.
eg:

```
#!/bin/bash
cd /home/bfn16b/web/washingtonparentsnetwork.org/public_html
/usr/bin/php bin/worker.php
```

dont forget to make the script executable:

`chmod +x /home/bfn16b/friendicaworker.sh`

Thats what i did in the past to call the worker process - probably it´s worth a try.

**Comment by silverwizard** [comment]
I think it might be the user not having a shell, or running inside a chroot of some form.

I think the endpoint
washingtonparentsnetwork.org/worker is still supported so putting `/usr/bin/wget -q -O /dev/null https://washingtonparentsnetwork.org/worker > /dev/null` in the crontab might help. Obviously with that link to the correct wget.

If that does then there's definitely a misconfiguration - after reading the Hestia Control Panel setup tools - it looks like it's not supposed to be chrooting you unless your user is using SFTP and I can't see any obvious mistakes that would cause cron to run in a chroot.

The Hestia people might be able to give you some answers about why absolute paths aren't working however.

But try the web worker - it's not as good as the local worker - but it will at least unblock you while you figure out cronjobs.

If the same issue occurs (likely manifesting as ` /bin/sh: 1: /usr/bin/wget: not found`, then you definitely have a path issue with bfn16b and could try it on root's crontab (since it's just visiting the website), and if that happens - then contact your server provider.

**Comment by davidspring** [comment]
I want to thank you for your suggestions. It turns out that you were right after all. There was a problem with the Hestia user. I did not think this was possible because I have created more than 100 Hestia users for various websites and none of them have ever had any problem. Despite a week of trying, I have been unable to figure out what was wrong with this user. I finally gave up and deleted the application, the domain name, the database and even the Hestia user and started over with a completely new user. I installed Friendica and created a cron job and it is working very well with PHP 8.1. The problem with the previous user will remain forever a mystery. But I want to thank you for your time and help. You can close this issue or let me know how to close it and I will close it.
