### ISSUE TITLE
Automatically insert a paragraph when uploading media.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#13082]
When inserting a media file using the "drag files here to upload them" function, a paragraph should be inserted before the file, otherwise the post will look like this...
![2023-05-04 06 55 19](https://user-images.githubusercontent.com/12480023/236115947-56492b9f-0a62-4f95-a3af-f0035efb6ab3.png)

**Comment by Raroun** [comment]
This is funny, because it doesn´t happen to all files that are uploaded.

Changing

```
Line 29 in
/view/js/dropzone-factory.js
```
from

`targetTextarea.setRangeText(' ' + $.trim(serverResponse) + ' ');`

to

`targetTextarea.setRangeText('\n' + $.trim(serverResponse) + '\n');`

should do the trick.

I testet it on my instance and it works for that case, but i don´t know if it breaks complex designed posts (like really long ones) when composing.
On the other hand, it just adds a new line ¯\ (ツ) /¯

**Comment by annando** [comment]
I think that this should be done in the corresponding function that does the upload, but not directly in the JS.

**Comment by Raroun** [comment]
Thanks for the advise, it´s the first time a have a look at the code.
i just saw that dropzone is a dependency via composer. 
please bare with me :)

**Comment by MrPetovan** [comment]
The line you mentioned should read `targetTextarea.setRangeText(serverResponse);` and it will take the new lines from the `media/photo/upload` call into account. The `$.trim` is currently removing the new lines that are provided in the response. This goes for `view/js/dropzone-factory.js:29` and `view/js/dropzone-factory.js:32`.

**Comment by Raroun** [comment]
Well, 
`targetTextarea.setRangeText(serverResponse);`
gets its returnvalue from `media/photo/upload`.
`\n\n` Newlines are included into the string, which are getting trimmed from `view/js/dropzone-factory.js`.
I shoudln´t change the file `view/js/dropzone-factory.js`, so the Newlines are allways getting trimmed, whatever i do.

An in my eyes dirty Solution would be to add "Zero Width Space" at the beginning and the end of the returnstring, which aren´t trimmed and would preserver the newlines.
I tried that and it works.

`$this->return(200, "\u{200B}" . "\n\n" . '[url=' . $this->baseUrl . '/photos/' . $owner['nickname'] . '/image/' . $resource_id . '][img]' . $this->baseUrl . "/photo/$resource_id-$smallest." . $image->getExt() . "[/img][/url]" . "\n\n" . "\u{200B}" );`

I have no other clue to get newlines through the trim, :(
At least i tried 👯

**Comment by MrPetovan** [comment]
Currently the new lines from the asynchronous call are getting explicitly trimmed by `$.trim`, we just need to remove this call and I believe we should be good.

**Comment by Raroun** [comment]
In the file `view/js/dropzone-factory.js` ?
that would be to easy :)
Guess ill need some months to dig into this code.

**Comment by MrPetovan** [comment]
Lines 29 and 32.
