### ISSUE TITLE
Create a link on the forums widget to register so it is easier to create a new forum

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13105]
I have already created a fix for this on my personal fork and you can find the commits there.

It took me 6 months, 4 years ago to realize that I could create a new forum or account without having to log out and create a brand new account.  You have to dig around in settings to get to the 'register'page.  I think many more people will be creating forums once there is a link right in the forums area to do so.  At the moment its way too confusing. 

Changes were to styles.css widget_forumlist.tpl, forumManager.php and ran a /bin/run_xgettext.sh

**Comment by MrPetovan** [comment]
Where did you create your fork? Here or on Forgejo? In your fork on GitHub I couldn't see a feature branch we could merge in the core repository: https://github.com/anubis2814/friendica/branches, and I couldn't find you on Forgejo: https://git.friendi.ca/friendica/friendica/forks

**Comment by annando** [comment]
@anubis2814 there is a functionality to create an additional account on the delegation page in the settings.

**Comment by anubis2814** [comment]
@annando Yes the problem is for the casual user digging through settings is the last place they would think to look. I know where it is but its hard to find.  If we want the function for the average user it needs to be an option located with the forums list.  Having it easily there in the widget similar to how FB does it will make things a lot easier. Settings is where people think to go when technical issues occur, changing passwords or appearance.  I have a feeling there are quite a few users who don't even know forums exist or how they work.

@MrPetovan https://github.com/anubis2814/friendica/ Is there something you can think of that is not allowing it to merge?  and no I'm not on forgejo

**Comment by MrPetovan** [comment]
Ah, I see a commit that was added to the `develop` branch. I was able to create pull request from it: https://github.com/friendica/friendica/pull/13110

But it is about the mobile icon to bring the side menu, not about a link to register new accounts.

**Comment by anubis2814** [comment]
Hmmmm, Unsure why you can't find it.  I created another clone and then ported and committed the changes on the new clone.

**Comment by MrPetovan** [comment]
Your GitHub repository still doesn't show any deviations from the official Friendica one. What is the remote you are using to push your changes once you committed them in your local clone?

**Comment by anubis2814** [comment]
https://github.com/friendica/friendica/compare/develop...anubis2814:friendica:develop I see the changes here, though you might not have permission to see this page.

**Comment by MrPetovan** [comment]
It looks like you pushed this commit since the last time I checked your fork, so you did good! From the link you sent me, you can create a pull request on your own which I will be able to review.

**Comment by MrPetovan** [comment]
@anubis2814 Just press the green button on the Compare Branches page:
![IMG_5601](https://github.com/friendica/friendica/assets/925415/1a1d6cff-0f31-4043-a7bd-630398c7c0aa)

**Comment by anubis2814** [comment]
I completed this task, it is now done.
