### ISSUE TITLE
Add custom menu item to any of the menus

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13104]
I am setting up a Friendica instructional social network and would like to add custom menu items linking to instructional pages (URLs) on a related website. 

I have searched the Friendica forum and the internet but have not found any way to do this. 

If it is possible, could you steer me in the right direction. 

If it is not possible, then consider this a feature request. 
Thank you for your help in this matter.

**Comment by MrPetovan** [comment]
It definitely is a feature request, what menus on what pages would you link to expand with arbitrary links?

**Comment by davidspring** [comment]
Ideally, it would be the personal drop down menu which is reached by clicking on the member image in the upper right hand corner. But whatever is easiest would work. 

In addition, I was hoping to start a discussion about this issue on the Friendica forum which is at this link. 
[https://forum.friendi.ca/~helpers](https://forum.friendi.ca/~helpers)

However, I can not figure out how to join this Friendica instance nor can I figure out how to post to it from my own Friendica instance. Any tips for how join and or how to post this issue to the Friendica forum would be appreciated.

**Comment by MrPetovan** [comment]
Just click "Follow" on the page you linked, provide your own profile URL, and once the follow process ends, you should be able to post exclusively to the forum with the following mention: `!helpers@forum.friendi.ca`

**Comment by davidspring** [comment]
I have clicked Follow and provided my profile URL. However, I do not understand what you mean by post to the forum with the mention. Do you mean make a post on my own forum and put the mention at the beginning or end of the post on my own forum? 

I will try this to see what happens. However, assuming that the post appears, I also want to be able to provide input to questions posted by others. Can I do that even if I am not registered on that forum? 

Finally, there is an menu item on all new Friendica sites under the Home (Profile) icon, click on the Status menu item, then click on the drop down arrow called **Tips for New Members.** 

I have been searching for this in the Friendica code for days without success as I may be able to use this link. Do you know where this menu item is called in the Friendica file system? 

Also, this menu item disappears after just two weeks. Do you know what I can change in the code to make it last 10 weeks?

**Comment by MrPetovan** [comment]
> I have clicked Follow and provided my profile URL. However, I do not understand what you mean by post to the forum with the mention. Do you mean make a post on my own forum and put the mention at the beginning or end of the post on my own forum?

Yes, just start composing a new post on your account, and use the `!helpers@forum.friendi.ca` mention to address only the people following the forum account.

> However, assuming that the post appears, I also want to be able to provide input to questions posted by others. Can I do that even if I am not registered on that forum?

Once you start following a forum account, you're considered registered to that forum and you will receive future publications by other forum members using the same special mention.

> I have been searching for this in the Friendica code for days without success as I may be able to use this link. Do you know where this menu item is called in the Friendica file system?

It is declared here:
https://github.com/friendica/friendica/blob/4c40bc164db95e36278f26c6a0d0541df4d81999/src/Module/BaseProfile.php#L136-L144

> Also, this menu item disappears after just two weeks. Do you know what I can change in the code to make it last 10 weeks?

You can change the new member delay here:
https://github.com/friendica/friendica/blob/4c40bc164db95e36278f26c6a0d0541df4d81999/src/Security/Authentication.php#L343

**Comment by davidspring** [comment]
Thank you. I think this gives me what I need to create my own custom documentation. I greatly appreciate your help.
