### ISSUE TITLE
[Support] Deleted profile is not removed from the DB

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13117]
For months I have had two accounts that are deleted but not removed on the database.
The posts from these accounts can still be accessed via remote instances. This is not how it should be.

The following message repeats itself continuously:

`2023-05-13T05:29:55Z worker [ERROR]: DB Error {"code":1451,"error":"Cannot delete or update a parent row: a foreign key constraint fails (`friend`.`mail`, CONSTRAINT `mail_ibfk_2` FOREIGN KEY (`author-id`) REFERENCES `contact` (`id`))","callstack":"DBA::delete (101), ExpireAndRemoveUsers::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (83)","params":"DELETE FROM `contact`  WHERE (`nurl` = 'http://loma.ml/profile/one' AND `self` = 0)"} - {"file":"Database.php","line":808,"function":"e","request-id":"645f2050bddfd","uid":"2cba75","process_id":459909}`

`2023-05-13T05:30:03Z worker [ERROR]: DB Error {"code":1451,"error":"Cannot delete or update a parent row: a foreign key constraint fails (`friend`.`photo`, CONSTRAINT `photo_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `user` (`uid`))","callstack":"DBA::delete (143), ExpireAndRemoveUsers::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (83)","params":"DELETE FROM `user`  WHERE (`uid` = 114)"} - {"file":"Database.php","line":808,"function":"e","request-id":"645f2050bddfd","uid":"2cba75","process_id":459909}`

**Comment by annando** [comment]
Please have got a look at what type of content is still available (posts, photos, profile?).

**Comment by loma-one** [comment]
All posts, pictures and profile information can still be accessed via https://mastodon.social/@one@loma.ml. 

With Friendica & Hubzilla (different instances) the profile is no longer displayed in the search. The profile can no longer be called up directly [https://loma.ml/profile/one].
![2023-05-14_14-07](https://github.com/friendica/friendica/assets/44441246/002264ad-f36b-43e8-a9e0-cd2b16fb6943)

**Comment by annando** [comment]
So you don't mean the local removal but the remote one?

**Comment by loma-one** [comment]
I don't know what is right. 

The DB says there are problems removing the account from the DB with all the posts, pictures, etc... that were created for this account.
![image](https://github.com/friendica/friendica/assets/44441246/6d2bb01b-6c4e-4583-b7d7-bf8a955449ce)
I can no longer access the account via the friendica instance. It can also no longer be found via the search function. So at least it seems to be locked. 

However, a search via Mastodon still leads to success. The account can still be accessed there, with all its contents. A local copy?
