### ISSUE TITLE
Rename contact groups to circles and user forums to groups

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13114]
Is this just legacy or is this what you guys all prefer?
Pretty much everyone at least in the English speaking world of social media at this date has a specific meaning for those words.  This might contribute to the under utilization of forums.  Most of the forums in the directory are German. 
I feel like our forums help to make us the best decentralized social media platform out there with only misskey/calckey being able to rival us but we need to be more intuitive the the casual user.  
I can do the changes for the English language and documentation, perhaps other languages prefer the naming scheme they already have.  If you all prefer our naming scheme I wont touch it but I've talked to several users who were confused by it.

**Comment by davidspring** [comment]
I agree. It took me a while to figure out that Friendica forums are actually like Facebook groups. My goal is to convince Facebook exiles to use Friendica. But it makes it tough when Friendica ignores terms they are already used to.

**Comment by tobiasd** [comment]
The forum functionality was developed after a discussion on how one could transplant the classic internet forums into Friendica. At this time one already could group contacts for addressing and filtering them, similar to the aspects of diaspora* the feature that later became circles in some proprietary network.

In addition, the forum is a public place for discussions since the ancient times. Whereas a group is a group of things.

**Comment by MrPetovan** [comment]
How are contact groups called in Facebook if this feature exists?

**Comment by anubis2814** [comment]
Lists do not exist in facebook.  Both Twitter and mastodon call them lists.  A circle as diaspora and G+ put it would allow you to share things exclusively to that group as well.  And while yes a forum is a place for public discussion, both facebook and Mewe use groups for more things like planning events and attempting to built in person community creating a group of people to join and such, something Friendica forums totally have the potential to do.  Its not that its wrong linguistically its just what people in the English world associate with the terms on social media in this day and age.  So when they come on and a word used to describe something 2/3rds of at least the english speaking internet user base has in their heads does something completely different, it creates some confusion.  Even in the friendica developers forum we've had to establish what I meant because its that ubiquitous in the language, as I had to clarify that yes I was talking about Friendica groups and not facebook groups.  Its there is no confusion in other languages they should stay exactly the same and we can just change the English names.  I know FB and twitter are less used in Germany for certain compared the the English speaking nations, France may be similar..

**Comment by MrPetovan** [comment]
So “group” -> “list”
and “forum” -> “group”?

**Comment by anubis2814** [comment]
Yes.  And if we were building the first social media site the current terms would be logically just fine to use, but the terms now mean specific things in this language as defined by the big social media and everyone knows what they mean.

**Comment by MrPetovan** [comment]
It's fine by me but we should start communicating about it right now.

**Comment by anubis2814** [comment]
How do we start that communication?

**Comment by MrPetovan** [comment]
Posting on the Friendica Support ~~forum~~ group for example. The Friendica Admins group is a good other one, so that they can communicate with their own users.

**Comment by anubis2814** [comment]
So just learned 5 mins ago that you can select a group to be the only people who can see your post.  So many amazing features on this platform that are buried.  Mind you since I don't know anyone in person there, I would have not ever needed to use this option.  Perhaps we should call "groups" -> "Circles" instead of "lists". Similar but more robust.   Even twitter now distinguishes between the two, something I also didn't know existed until 5 minutes ago.  Sorry, I'm making this more complicated, I had no idea this was even a feature because I assumed they were just like lists.  Any objections?

**Comment by MrPetovan** [comment]
So “group” -> “circle”
and “forum” -> “group”?

**Comment by anubis2814** [comment]
Yes.

**Comment by anubis2814** [comment]
So just realized that the docs are all in english.  So if i change the docs in help to say circles and leave the other languages as groups, will they know what I am talking about?  Are there help files in other languages? It sounds like people in other languages don't have the same confusion as english speakers on this so there is probably little need to change this unless you want it all uniform.

**Comment by anubis2814** [comment]
Looks like there is just German

**Comment by anubis2814** [comment]
Or should I put a note in the docs that they are groups and forums in all other languages?

**Comment by anubis2814** [comment]
Nm, we can just create an english only folder and leave the rest as default for any other language.

**Comment by tobiasd** [comment]
> Or should I put a note in the docs that they are groups and forums in all other languages?

I don't think that we should rename it only in one language, as this will lead to more confusion when German people read about circles in the support channels and all the time need to be told, that these are just your regular Kontaktgruppen that got renamed in the English version only.

It is also important that the changes are then also made to all the translations that we have for the Friendica UI.

> Looks like there is just German

Yes, sadly the documentation is only bi-lingual.

> So just learned 5 mins ago that you can select a group to be the only people who can see your post.

Just to complete this, if you write a posting, you can also use groups to negate visibility as with contacts. Say this is a posting for all contacts (but it is not public)  but not those that I put into the group of people from Berlin.

**Comment by MrPetovan** [comment]
What would be the changes in German for the hosted documentation?

**Comment by informapirata** [comment]
In all my informative posts on the Fediverse, I have decided to call the Friendica forums with the denomination groups/forum 😅... In this way I simply added an unofficial term (groups) without losing contact with the original name (forums)

**Comment by anubis2814** [comment]
@MrPetovan Did G+ and diaspora have an equivalent word to circles?  Groups can be easily the same word.

**Comment by anubis2814** [comment]
On twitter they just call it a Circle, in french its a Cercle.  So that should work unless German has a better word for them.

**Comment by davidspring** [comment]
The problem with circle is similar to the problem with forum. In English, these words have specific meanings. For example, a circle implies something that is round while a forum implies a series of questions and answers. The benefit of the word group is that it is a commonly used general term for a group of people. In addition, because Facebook has dominated social networks for the past 15 years, most people in the US have come to understand what a Facebook group is. I think the best compromise suggested so far is to use the term group/forum which means that it can either be a group or a forum.

**Comment by anubis2814** [comment]
@davidspring Twitter doesn't seem to have any problems pushing circle on all the other language and I think its fairly popular in most languages.  Currently compiling a list of words twitter uses for circle in each one.

**Comment by davidspring** [comment]
I  understand what Twitter does. However, Facebook is about 10 times bigger than Twitter. In addition, as an adult education instructor, I get to deal with a lot of people - many of whom have never used Twitter. Using the plain meaning of words helps a lot when working with beginners.

**Comment by anubis2814** [comment]
@davidspring Right and everyone knows what a facebook group is.  So do we still call groups, groups and forums forum/groups? Because friendica groups have little to nothing to do with facebook groups while forums are exactly like facebook groups.

**Comment by davidspring** [comment]
I agree that Friendica forums are similar to Facebook groups. But could you clarify what you mean by a Friendica group?

**Comment by anubis2814** [comment]
Do you not use friendica groups?

**Comment by anubis2814** [comment]
If you haven't i suggest you read the entire thread.  Frienidca Groups are a way to group your contacts together so you only see posts from them when selected.  This is what a twitter or mastodon list does.  However they also have the added benefit of being able to be used to give exclusive permissions or block permissions to everyone in that list.  This elevates it to the level of Diaspora, G+, twitter circles   You know what a facebook group is, it has nothing to do with a friendica group and facebook terminology is globally known.

**Comment by MrPetovan** [comment]
Let's see

|Platform | Custom Audience | Theme-specific community |
| --------- | ------------------- | ------------------------------ |
| **Friendica (now)** | **Group** | **Forum** |
| Facebook | ? | Group |
| Google+ | Circle | ? |
| Twitter | Circle | N/A |
| Diaspora | Circle | N/A |
| Mewe | ? | Group |
| **Friendica (planned)** | **Circle** | **Group** |

It looks like a no-brainer to me. We just need to find the equivalent change in German to update the hosted documentation.

**Comment by anubis2814** [comment]
Ar دائرة , bg Кръг,  ca cercle del, cs Kruh, da-dk cirkel, de circle, en-gb circle, en-us circle, eo cicle, ,es Círculo de, et ring, fi-fi piiri, fr cercle, gd cearcall, hu kör, is hring, it circle, ja サークル, nb-no sirkel,  nl circle, pl krag na, pt-br roda do,  ro cerc,  ru Близкий круг в, sv krets,  zh-cn 圈子 These are the words twitter uses for them, all translating to circle after running through google translate.  I things these should work just fine.

**Comment by MrPetovan** [comment]
Thanks, the translations in anything but German will be solely performed by translators on Transifex, but I'd rather have the input of a native German speaker for the hosted documentation change.

**Comment by anubis2814** [comment]
Ok cool, I won't have to worry about that then. I've changed the english language strings.php, messages.po and .md docs, for both US and GB, just have to do some second checking. However should we keep the code the way it is and just have developers and translators know what we mean when going into the code, as that will be a bit of a mess to change terms in the code.

**Comment by anubis2814** [comment]
example code change I did to strings.php `$a->strings['Add contact to group'] = 'Add contact to circle';` Do We need to look back into the code and change the original ['Add contact to group'] to circle? Or will that confuse the translators if we don't.

**Comment by davidspring** [comment]
Thanks to both of you for producing a table of words used by different platforms and for clarifying what you mean by a Friendica group. By Friendica group, you meant a group of contacts or a custom audience. I do not think this custom audience function exists in Facebook and because I do not use Twitter very much I was not aware this was possible in Twitter. After a little research, I do see this term groups in Friendica as creating what I would think of as a circle of friends - similar to what was done with Google Plus. So yes, I agree that what Friendica is using for the word Group is actually a Circle of Friends and what Friendica is using for the word Forum is actually what an uninformed person like me would think of as a Facebook group which you have correctly described as a community that shares a specific interest. I think that changing this language will help those of us who are moving from Facebook to Friendica... In addition, one thing I like about Friendica is that it does appear to novices like me to be similar in appearance and function to Facebook. So we do not need to learn an entirely new set of terms and processes.

**Comment by MrPetovan** [comment]
> example code change I did to strings.php `$a->strings['Add contact to group'] = 'Add contact to circle';` Do We need to look back into the code and change the original ['Add contact to group'] to circle? Or will that confuse the translators if we don't.

Yes, please don't change anything manually in the `strings.php` and `messages.po` files. Translation strings should be changed in the code itself (the translation calls are `->t()` and `->tt()`), and then the `bin/run_xgettext.sh` script must be ran.

**Comment by anubis2814** [comment]
Should we just keep all the variable the same and just know what that means? Changing variables could be messy.

**Comment by anubis2814** [comment]
I made "Group your contacts" to "Group your contacts into Circles."

**Comment by davidspring** [comment]
I've changed the english language strings.php, messages.po and .md docs, for both US and GB,...
Where are the english language strings in the Friendica file system? I would like to make this change on my own site.

**Comment by davidspring** [comment]
please don't change anything manually in the strings.php and messages.po files. Translation strings should be changed in the code itself...
why do you not want us to make changes to the strings.php file and the mesages.po file?

**Comment by anubis2814** [comment]
@davidspring Its not uploaded or merged yet.  It sounds like there is an automated system to insert everything with a l10n tag into messages.po and strings.php, doing this manually might screw with that automated system.   Since the default language is already english, most likely it will just auto translate into english once i run the process..

**Comment by MrPetovan** [comment]
- `messages.po`: Generated by the `bin/run_xgettext.sh` script. Everything that you change in this file but not in the code will be overwritten the next time someone uses the script as expected.
- `strings.php`: Generated by the `po2php` console command from the language-specific `messages.po` files imported from Transifex. Everything that you change in this file but not on Transifex will be overwritten the next time someone uses the console command as expected.

**Comment by oe4dns** [comment]
> Thanks, the translations in anything but German will be solely performed by translators on Transifex, but I'd rather have the input of a native German speaker for the hosted documentation change.

As a native G speaker, I'd say that "Groups->Circle" and "Forum->Gruppe" are just fine. Circle seems to be widespread enough to be generally recognized in the social media context and Group is a much better description to what Forums used to be anyway.

Just make sure to announce the change loudly so that people hear about it during the next update cycle.

**Comment by MrPetovan** [comment]
Thank you for your input, and yes, communication is planned. We don't have a way to reach out to every single Friendica user but we will be posting in the major Friendica groups.

**Comment by MrPetovan** [comment]
At this point, given the extensiveness of the changes and the potential technical finesse required, I think I should be carrying this task. I'll make an announcement in the official groups before the PR is merged so that nodes on the `develop` branch don't suddenly wake up to a major terminology change.

**Comment by anubis2814** [comment]
Are old unused l10ns left often in the strings.php?   There are some phrases in strings.php I can't find anywhere in any of the other code files.

**Comment by MrPetovan** [comment]
It's unlikely. Remember that sometimes apostrophes or quotes are escaped in the L10n calls and that a string search may not find them. Additionally, for historic reasons, parentheses have been escaped as `\x29` and `\x30` or something like that. The escaped characters show normally in the `strings.php` file.

**Comment by anubis2814** [comment]
Nm i found the ones missing

**Comment by davidspring** [comment]
Thank you for this information. I think this change to using more commonly accepted meanings for words like Group and Circle will make it much easier for Fakebook and Google brainwashed people like me to understand and use Friendica. Your explanation has raised two other important issues. However, I will make separate posts about those issues. Thanks again for making this change.

**Comment by anubis2814** [comment]
The following l10ns don't have corresponding lines in strings.php can you tell if they are written wrong so bin/run_xgettext.sh doesn't pick them up?

'src /module/admin/site.php
'$compute_group_counts'   => ['compute_group_counts', DI::l10n()->t('Generate counts per contact circle when calculating network count'), DI::config()->get('system', 'compute_group_counts'), DI::l10n()->t('On systems with users that heavily use contact circles the query can be very expensive.')],
 src /module/group.php
   DI::sysmsg()->addNotice(DI::l10n()->t('Circle name was not changed.'));'

**Comment by MrPetovan** [comment]
No, they look good. Also I started working on this so we will have conflicting changes. I'll submit the first PR replacing "group" with "circle" soon.

**Comment by anubis2814** [comment]
Oh just finished up mine for both and was about to upload it after I got word about this.  Oh well you can do a comparison and see if one of us forgot something.
I assumed you meant you needed to be in charge of doing the announcements.

**Comment by MrPetovan** [comment]
I'm sorry, I should have been more clear. I believe I went in more details than you, especially for the variable names across the PHP and JS code and the templates.

**Comment by MrPetovan** [comment]
See for yourself the changes just for the "group" to "circle" replacement: https://github.com/friendica/friendica/pull/13121/files

**Comment by anubis2814** [comment]
Ah yes I didn't change any of the variables names purposely.  Would it be helpful to upload mine just to see if you forgot anything or would it be less confusing without it?

**Comment by anubis2814** [comment]
Yeah I only changed the l10ns you went WAAAY beyond what I did.  I'll just leave it for you to do.

**Comment by MrPetovan** [comment]
Thanks, I don't think we should change just the translation strings, it's likely to cause endless confusion because we are reusing "group" for forum. If we were replacing A with C and B with D, it wouldn't matter as much but in this case we're replacing A with C and B with A so the reusing of the same term needs to be absolutely clear.

**Comment by anubis2814** [comment]
Makes sense and something I'm not remotely knowledgeable to do yet.

**Comment by anubis2814** [comment]
Just a heads up, I have the docs changed over if that will help, though you may have an automated way to do it all quickly

**Comment by MrPetovan** [comment]
No, I did everything manually because we're talking about language, and it is messy. In the process of finding all the occurrences of "group", I discovered we were already using it since 2012 to designate what we call private forums. The terminology used is "forums and private groups" which means the seeds for this change already existed in Friendica since its inception.

**Comment by anubis2814** [comment]
Ah digging up old artifacts now put on display

**Comment by davidspring** [comment]
As long as we are trying to clarify words, in my research I have found that when you click on the My Posts and Conversation icon in the top bar, some Friendica sites use the word Status to the right of the word Profile while other Friendica sites use the word Conversations.  This change also occurs in the top or first item in the main menu. I have no idea what either word is supposed to mean but I am wondering why some sites use one word and other sites use the other word and which you think sites should use and why and how this difference occurred in the first place???

**Comment by Raroun** [comment]
I would be fine with "Circle" or even "Zirkel" in German too. Both are widely spread. I would probably go with "Circle" on a second thought.

**Comment by MrPetovan** [comment]
> I have no idea what either word is supposed to mean but I am wondering why some sites use one word and other sites use the other word and which you think sites should use and why and how this difference occurred in the first place???

We changed this terminology recently but not all Friendica nodes have updated to the latest version yet.

**Comment by AndyHee** [comment]
I generally don't see any problems with the suggested renaming.

However, I'd like to highlight a bit of background and point to scope for improvement.

The term forum was very popular in the 1990s in the English-speaking Internet culture. In that way, it really predates social media. 

It mainly denoted message boards and online discussion place that were accessible to anyone with Internet. In a sense, it was the continuation of how the English terms forum implies a "public place", very much in line of the classic use of the Latin term _[Forum Romanum](https://en.wikipedia.org/wiki/Roman_Forum)_.

The current suggestion to call it a group, however, loses that connection of an implied public place. In the interest of clarity (esp. data protection transparency), would it not be better to call Friendica's Forums: "**Public groups**"?

**Public groups** would then also be distinct from the experimental feature currently called "Private forums".

**Comment by AndyHee** [comment]
Btw, this is what I currently see for British localisation. The account type is actually called "Community forum" here.

![Screenshot_2023-05-14_23-35-00](https://github.com/friendica/friendica/assets/28751375/5be50777-6402-4b9d-b9dd-27e30c91fb80)

**Comment by davidspring** [comment]
So the word Conversations is the new word that has replaced the word Status... This is good to know as I am working on a book on Friendica and I want to make sure my screen shots are as up to date as possible. 
Are there any other recent word changes I should be aware of that have been made in the past month?

**Comment by MrPetovan** [comment]
Not that I can remember, these changes are unusual and it's a coincidence that you caught two of them.

**Comment by anubis2814** [comment]
@AndyHee If they can get the private forums past experimentation stage, perhaps there will be 3 tiers of groups, private which requires approval, public which requires joining but everyone is approved and forum which requires no joining.

**Comment by MrPetovan** [comment]
There's no concept of forum that requires no joining. "Following" a forum account counts as joining in. Public forums will automatically accept the follow requests, private forums will require manual approval.

**Comment by AndyHee** [comment]
> private forums past experimentation stage

@anubis2814 Not sure whether someone is still "experimenting" on this. The experimental label has been there for many years, as far as I remember.

I think, it's currently not well tested and mainly serves as a warning that privacy issues may occur.

Perhaps we should send out a call to users/ admins to toughly test this feature. What do you think?

**Comment by MrPetovan** [comment]
@tobiasd This is a big one for the Release Notes! In particular, two addon have been renamed, which mean the existing addon has been marked as unsupported, and new addons have been created with the new names, see https://git.friendi.ca/friendica/friendica-addons/pulls/1394

**Comment by annando** [comment]
@AndyHee funny thing about this "experimental" flag is that it went from "experimental via DFRN" to "experimental via AP", when the way changed how we distribute those posts. Also we possibly should point out that the private groups most likely will only work with Friendica systems.
