### ISSUE TITLE
Vier: Location link below postings links to google maps

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1311]
Would be better to link to openstreetmap.org to support privacy and free maps.

**Comment by fabrixxm** [comment]
There is a plugin for this: "openstreetmap".
Just activate it and set "Tile server URL" to http://nominatim.openstreetmap.org/search.php

**Comment by tugelbend** [comment]
I would love to see that Openstreetmap is the default (and there is a plugin for google, if someone cares).

**Comment by fabrixxm** [comment]
:+1:

**Comment by silke** [comment]
+1 for OSM as the default! :)

**Comment by annando** [comment]
If nobody minds I would move the code from the addon to the core and would create a setting (system wide or user setting?) to switch between these two map providers.

**Comment by fabrixxm** [comment]
I would move the osm code in core and gmap one in addon....

**Comment by annando** [comment]
I would like to reduce the number of addons as far as possible.

**Comment by tugelbend** [comment]
Why not remove the google maps option? The location link provides very basic functionality that will perfectly be provided be openstreetmap. By removing the google option, we don't need a switch, reduce complexity and we stop promoting a service that violates the privacy of it's users.

Google fans are free to provide an addon if they want to use google instead.

**Comment by Beanow** [comment]
The problem I have with OSM is that search often is buggy and links on smartphones open in browser, not a fast interactive offline available gmaps app. Lack of navigation as well. Gmaps solves more problems so it is still attractive for many to use.

**Comment by silke** [comment]
I propose to create a switch as a temporary solution and if then we find osm good enough to be the only map service we can still remove google.
Good idea to move it into core.

**Comment by annando** [comment]
In the upcoming release we removed Google maps from the core and created a GoogleMaps addon. I think we can now close this issue?

**Comment by tugelbend** [comment]
Sure! Thanks for the work!
