### ISSUE TITLE
nologin option not working?

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1312]
On our server I have set 'nologin' to 30 days: $a->config['public_server']['nologin'] = 30;

However, in the user list there are several users who haven't logged in first time for more than 30 days:

![no_login](https://cloud.githubusercontent.com/assets/3009959/5887629/ff31bcec-a3dc-11e4-898b-31fb57c26425.png)

**Comment by silke** [comment]
I can confirm this. My expiration setting for inactive accounts is not working (anymore?) either.

**Comment by annando** [comment]
The whole expiration stuff needs much rework. There is the danger that wrong settings can delete active accounts.

**Comment by silke** [comment]
That's what we have vagrant for! ;)

**Comment by fabrixxm** [comment]
What about to block the inactive user instead of delete it? Blocked users should not get involved in poller and notifier...
Admin can then review the users and delete or unblock as needed...

**Comment by annando** [comment]
Inactive users are set into a kind of "stand by" mode by now. Means: Their RSS feeds aren't polled anymore. AFAIK they don't waste much CPU time and database space by now.

**Comment by fabrixxm** [comment]
what's the status here?

**Comment by annando** [comment]
I haven't changed anything here. I guess it really needs to be reworked but I don't see it as a blocking issue for the release.

**Comment by fabrixxm** [comment]
I'll move this to milestone 3.5

**Comment by tobiasd** [comment]
probably related to #1908

**Comment by annando** [comment]
I did some work to the addon and related core functions. During this work I saw that only regular user accounts are removed. Forums aren't. 

So possibly the user accounts in this issue aren't regular users but possibly forums.

**Comment by tobiasd** [comment]
The accounts are just created, but the user never log in, so they cannot change their role to forum or so. I think they should be regular accounts then.

**Comment by tobiasd** [comment]
Regarding the forum accounts, I don't know if they should be automatically deleted. Ideally nobody will log in to that account once it is working, so how to decide automatically when to delete it.

**Comment by annando** [comment]
Forum accounts aren't automatically deleted, when I read the code correctly.
