### ISSUE TITLE
New RSS/Diaspora contacts run into errors due to incompatible communication protocols

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13136]
The instance was moved to a new server about 2 weeks ago. The move was completed without any major problems. The old server was running php7.4. The new one is running php8.1. After some time I noticed that it is no longer possible to create new contacts from RSS sources. All existing RSS contacts are still retrieved and provide data
![image](https://github.com/friendica/friendica/assets/44441246/332d78b0-0513-4632-be49-ea087494904e)
_"The specified profile address provides insufficient information. No compatible communication protocols or feeds were found."_

error message:
https://next.dis-le.de/index.php/s/4JQbiCt4D8HNLaF

The PHP dependencies are fulfilled:
https://next.dis-le.de/index.php/s/BmYi4Tg37TjYAdP

In parallel, there also seem to be problems with diaspora contacts
`2023-05-18T04:41:09Z index [INFO]: Fetched for user 0 from https://diasp.org/u/vtel57 returned 406 [] - {"file":"HTTPSignature.php","line":505,"function":"fetchRaw","request-id":"6465ac6551926","uid":"4c4ce6","process_id":586064}`

What do I have to/can I check and how in order to further isolate and rectify the fault?

**Comment by tobiasd** [comment]
What version of Friendica are you running?

**Comment by loma-one** [comment]
Stable Friendica 'Giant Rhubarb' 2023.04-1 - 1518
This is probably a local problem. The error does not exist on other instances under my control.

---
Change to 2023.05-rc. The problem persists.

**Comment by shiribailem** [comment]
@MrPetovan this sounds a lot like the problem I had with RSS feeds and iirc it was the bug with the Tumblr addon?

**Comment by MrPetovan** [comment]
Ah, possibly. @loma-one , did you update addons to version 2023.05-rc as well?

**Comment by loma-one** [comment]
I am on
`14956244cce99e84554f2fc8cca57e6ab2992f0f		branch '2023.05-rc' of https://github.com/friendica/friendica`

`e91962b0b69af35ed777bdc49d3b590083ab1a6b		branch '2023.05-rc' of https://github.com/friendica/friendica-addons`

**Comment by loma-one** [comment]
Yes, it is the tumblr connector. After deactivating it I was able to follow rss feeds and diaspora contacts again.

**Comment by loma-one** [comment]
Yes, it is the tumblr connector. After deactivating it I was able to follow rss feeds and diaspora contacts again.
Would it make sense to make a mistake out of this?

**Comment by kr428** [comment]
> Yes, it is the tumblr connector. After deactivating it I was able to follow rss feeds and diaspora contacts again. Would it make sense to make a mistake out of this?

Interesting however: When I opened this, it _seemed_ this combination (Tumblr, Diaspora) worked on the same version on venera.social. Are there other aspects that might matter here?

**Comment by MrPetovan** [comment]
> I am on `14956244cce99e84554f2fc8cca57e6ab2992f0f branch '2023.05-rc' of https://github.com/friendica/friendica`
> 
> `e91962b0b69af35ed777bdc49d3b590083ab1a6b branch '2023.05-rc' of https://github.com/friendica/friendica-addons`

This looks good, with the same pull I'm not able to reproduce the issue though, even with the tumblr addon enabled.

**Comment by loma-one** [comment]
Here, PHP 8.1 is running with MariaDB version 10.5.19. Can it be related to this?
Two other instances are running PHP 8.0 with the same SQL version. I cannot reproduce the problem there either

---
I have activated the addon as a test. With the result described above. RSS and Diaspora can no longer be subscribed to.

**Comment by MrPetovan** [comment]
It's possible but I don't have PHP 8.1 available to test so I'd be hard-pressed to find the issue.

**Comment by loma-one** [comment]
The problem is solved with the upgrade to 2023.05. The server pulled files from a cache, which caused the instance to be in an undefined state.
