### ISSUE TITLE
The "to" field for private messages is ambiguous.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1313]
For example if you have people from different networks or friendica nodes, they can show with the same name:
![example](http://ss.oscp.info/2015-01-24_19-43-33.png)

I think this list should be made easier to use and allow unique identifiers to know precisely where you're sending the message.

**Comment by silke** [comment]
We could display the name AND the complete friendica ID, like so:
Name (user@server1.example.org)
Name (user@server2.example.org)
... maybe even with the avatars although those are likely to be ambiguous, too.

**Comment by annando** [comment]
@silke I second this idea.

**Comment by fabrixxm** [comment]
:+1:

**Comment by annando** [comment]
I just changed it on my machine. I guess I will make a pull request for that soon.

**Comment by friendica** [comment]
These used to have a hovertip  providing either the url or webbie.

**Comment by annando** [comment]
@friendica hovertips aren't so practical for a quick view. And we are having the space in that case, so there is no need to spare it.
