### ISSUE TITLE
Update to stable / version name is not set high

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13164]
- Friendica directory raised to current stable (2023.04-1 > 2023.05) via git fetch/pull. 
- Pull Version 2dbfb070083ec395bf5d24ec89fe96b282c6a12d
- ./bin/composer.phar install --no-dev && ./bin/console dbstructure update && ./bin/console postupdate executed without error message.
- The version number 2023.04-1 is still displayed (https://loma.ml/friendica).

Error handling
- Friendica completely rebuilt via git pull
- the version name still remains 2023.04-1

Question: How can I convince the database to use the stable version?

PHP 8.1
SQL 10.5
Apache

Discussion https://loma.ml/display/373ebf56-5264-6e57-4c1b-2e1097046942

**Comment by Raroun** [comment]
I have no clue - but did you checked the permission in your friendica directory?
Sometimes it happens to me that i forgot to change the user to www-data and change files as root, which arent updated by a git pull then (permissions).
Did you did a pull on that specific Version, or did you do a `git pull stable`?

**Comment by loma-one** [comment]
This is always the same procedure:
```
bin/console maintenance 1 "wir sind gleich wieder da"
cp -r /var/www/html/friendica/ /var/www/html/friendica_backup/
cd /var/www/html/friendica/
git fetch
git checkout stable
git pull
bin/composer.phar install --no-dev
cd /var/www/html/friendica/addon
git fetch
git checkout stable
git pull
sudo chown -R www-data:www-data /var/www/html/friendica/ 
./bin/console dbstructure update && ./bin/console postupdate
bin/console maintenance 0
```

**Comment by MrPetovan** [comment]
What's the result of `head -67 src/App.php | tail +67`?
What about `cat VERSION`?

**Comment by loma-one** [comment]
class App
{
	const PLATFORM = 'Friendica';
	const CODENAME = 'Giant Rhubarb';
	const VERSION  = '2023.05';

**Comment by MrPetovan** [comment]
The file version is right, and also it's the one the `/friendica` endpoint is using to display the node's version, so I'm a little confused.

**Comment by loma-one** [comment]
I am also confused.
The DB must somehow realise that a new version is to be used. Therefore I had run `./bin/console dbstructure update --force`. Without success.

I then fast-forwarded to 2023.09-dev to see if that made a difference. Even then, the version designation 2023.04-1 is still displayed.
I noticed that the addon "BlueSky export" is not supplemented with the reference "Import". The field "Import the removed timeline" is displayed, but the field description is not displayed.

I have now fallen back to the stable version.

**Comment by loma-one** [comment]
After a reboot, the new version was accepted

**Comment by annando** [comment]
Please keep this problem on your mind when performing future updates.
