### ISSUE TITLE
Well, this is one of many...

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13162]
<html><body>

2023-05-24T10:09:18Z | ERROR | worker | DB Error
-- | -- | -- | --

<h3 class="event-data-header">Data</h3>
<div class="event-source">
</div>
<div class="event-data"><details open=""><summary>code</summary><pre>1712</pre></details><details open=""><summary>error</summary><pre>Index post-tag is corrupted</pre></details><details open=""><summary>callstack</summary><pre>DBA::exists (2610), Contact::hasLocalData (2680), Contact::updateFromProbeArray (2590), Contact::updateFromProbe (70), UpdateContacts::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (83)</pre></details><details open=""><summary>params</summary><pre>SELECT `cid` FROM `post-tag` WHERE (`cid` = 42094) LIMIT 1</pre></details></div>
</body>
</html>

### Platform Info

Friendica Version:
Friendica 'Giant Rhubarb' 2023.05 - 1518

 

PHP version:
8.1.2

**Comment by tek-aevl** [comment]
More useful...
<html><body>


2023-05-24T10:21:16Z | ERROR | worker | DB Error
-- | -- | -- | --



<h3 class="event-data-header">Data</h3>
<div class="event-source">
</div>
<div class="event-data"><details open=""><summary>code</summary><pre>1451</pre></details><details open=""><summary>error</summary><pre>Cannot delete or update a parent row: a foreign key constraint fails (`friendicadb`.`post-tag`, CONSTRAINT `post-tag_ibfk_3` FOREIGN KEY (`cid`) REFERENCES `contact` (`id`))</pre></details><details open=""><summary>callstack</summary><pre>DBA::delete (232), Contact::deleteById (45), Remove::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (83)</pre></details><details open=""><summary>params</summary><pre>DELETE FROM `contact`  WHERE (`id` = 21737)</pre></details></div>
</body>
</html>

**Comment by annando** [comment]
This "index ... is corrupted" is a message from your SQL server. Please have a look at how to fix it. I don't think that this error can be caused in any way by Friendica.

**Comment by tek-aevl** [comment]
tags are not working as of 2 versions ago. AS in searching for things with it get 0 results

**Comment by Raroun** [comment]
@tek-aevl 
a "mysqloptimize friendicadb" on the shell should rebuild all indexes.

or you can do an optimze table only on the table  "post-tag".

That should fix your tag search.

**Comment by tek-aevl** [comment]
Tbh I fixed this before but it was with a comment left on something else here, however I do not remember what the main post was about.

**Comment by tek-aevl** [comment]
Yes this is what it was!!!! Thanks @Raroun  @annando 
also I found this, 
https://github.com/friendica/friendica/issues/12668
