### ISSUE TITLE
How to set up error stack trace log

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13165]
I am trying to figure out a white screen of death issue. I have added the error log file log/friendica.log as described in the wiki. I have also checked Enable Debugging in Administration Logs. However, when I click View logs I only get a table of the time of the error, the level and the Message. How can I set up a stack trace to help me figure out which line on which file is causing the problem?

**Comment by MrPetovan** [comment]
What kind of errors are you getting in the View Logs page?

**Comment by davidspring** [comment]
I created a new theme called Spring by copying the Vier theme using the wiki instructions. The new theme is identical to the Vier theme except for a few dozen changes in the style.css file.  I changed all of the Vier references in the three php files to the word spring.  These files are theme.php, style.php and config.php. I then copied the netcolour.css file and named it spring.css and added the new variant to the end of the config.php file. 

I also changed the theme template settings from Vier to Spring. This resulted in a new third theme correctly appearing in Admin theme selection screen. I can check the box to make it an option. I then go to Admin, Site where I can select the Spring theme as an option and check the spring variant as an option. 

However, when I go to Settings, Display, Display theme and use the drop down to change from the Vier option to the Spring option and then click Save settings, I get the white screen of death. Even worse, I am unable to recover because there is no way to uncheck the spring theme due to the white screen of death. The only solution is to use a backup to roll the website to a previous version. 

I am running a Debian 11 VPS and I did check the Apache2 error log at  /var/log/apache2/error.log. But there was nothing useful there. 

So my hope is to do a trace so I can figure out where the problem is and fix it.

**Comment by MrPetovan** [comment]
If nothing shows in the Apache log and nothing shows in the Friendica log, it's possible it's a Parse Error. Please check your Friendica install using `php -l`.

Here's a command to do this recursively in the `view/theme/spring` folder:
```
find view/theme/spring -iname '*.php' -exec php -l '{}' \; | grep '^No syntax errors' -v  | less
```

**Comment by davidspring** [comment]
I connected to the server via ssh and added the full path and entered the command in the terminal. The reply was spring is a directory. Either I did something wrong or the command is intended for a file rather than a directory.

**Comment by MrPetovan** [comment]
Hmm, please try again like this:
```
cd view/theme/spring && find . -iname '*.php' -exec php -l '{}' \; | grep '^No syntax errors' -v  | less
```

**Comment by davidspring** [comment]
I have not tried the new command yet. However, I just got this email about an error which I do not know how to fix:
PHP Warning:  sem_acquire(): Failed to acquire key 0x66018e06: Identifier removed in /public_html/src/Core/Lock/Type/SemaphoreLock.php on line 65

**Comment by davidspring** [comment]
This was in response to the cron job I have set up for this website. The cron job has not had any problems before this. 

I will try the command and report back in a couple of minutes.

**Comment by davidspring** [comment]
the command as accepted but there was no response.

**Comment by MrPetovan** [comment]
The semaphore warning is unrelated and wouldn't trigger a white screen of death.

Next, you can try exposing PHP error messages in the browser by temporarily adding the following lines to the beginning of the `index.php` file:
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by davidspring** [comment]
Thank you so much for your help! That was the tip I needed. It reported that the error was on line 55 of the config.php file where I had failed to change vier to spring. Once I made this change, the problem was solved and this issue can be closed.
