### ISSUE TITLE
Accept header as array not functional with nginx

### ISSUE THREAD

**Issue by git-marijus** [friendica/friendica#13174]
- [x] I have searched open and closed issues for duplicates

### Bug Description

In https://github.com/friendica/friendica/blob/70674f2ecc9d34ba7eabbd15c06f85b469b27d0e/src/Module/Magic.php#L122 the accept header is set as an array. If the receiving server is nginx (in its default config), only the last entry of the array will appear under accept and thus make it impossible to verify the HTTP signature. I can confirm that apache handles this differently and the accept header looks like expected there.

Actual Result:
`$_SERVER[HTTP_ACCEPT] => 'application/x-zot+json'`

Expected Result:
`$_SERVER[HTTP_ACCEPT] => 'application/x-dfrn+json, application/x-zot+json'
`

Fix: 
According to RFC9110 headers with multiple values should be set in separate lines like
```
Accept: application/x-dfrn+json
Accept: application/x-zot+json
```
or combined
`Accept: application/x-dfrn+json, application/x-zot+json`

I can confirm that the latter works for nginx and i suppose also for apache. Have not tested the first though.

### Platform Info

Friendica Version:
2023.05

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by git-marijus** [comment]
Is there a specific reason this is not being addressed?
It breaks HTTP signatures for nginx and a fix is proposed...

**Comment by MrPetovan** [comment]
The reason is that nobody has come around to apply the suggested fix yet. Would you like to try your hand at it? https://docs.github.com/en/get-started/quickstart/github-flow

I'll be happy to assist if you have specific questions.

**Comment by annando** [comment]
@git-marijus I started working on improving some more stuff at that module, but a lot of other stuff distracted me from finalizing my work there.
