### ISSUE TITLE
Function of chart js and moment js

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13171]
I would like to reduce the file size of Friendica. I therefore have been going through the files to see if any major files can be deleted. In the View Folder, in the assest subfolder are files called chart js and moment js. They both appear to be for graphing. Chart js is 7 mb and moment is 4 mb. I deleted both of them from a test install and could not find any adverse effects. I am hoping someone can explain what these two folders do and if there is any drawback in deleting them.

**Comment by MrPetovan** [comment]
Chart.js is used to create graphs of the federation in `/admin/federation` and moment.js is used in the display of the calendar.

**Comment by davidspring** [comment]
Thanks for the info.
