### ISSUE TITLE
Invite option Register?

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13170]
A way to make registrations invite only style like discord?

**Comment by tobiasd** [comment]
You can go to `example.com/invite` to send out invitations. IIRC those invites are working, even if the registration is otherwise closed.

**Comment by tek-aevl** [comment]
Sending email, is an issue in my set up that I have not been able to get around.
So using url's to authenticate would be better in my set up.

**Comment by MrPetovan** [comment]
We send out the initial password for all newly created accounts as a form of email verification, you can't accept new user registrations without a working email system.

**Comment by tek-aevl** [comment]
That is why an invite link in like a hash url that has limited uses and or expiration  date meaning self deleting if used more than so many times or not available after a fixed date even if unused would be great for me.

**Comment by MrPetovan** [comment]
Even if we exposed in the UI the invite links that are currently sent out, people would not be able to start using their account without a working email system to send the initial password.

**Comment by tek-aevl** [comment]
I can see how it could be a lot of work.

**Comment by MrPetovan** [comment]
It isn't a question of work, it's a question of safety. We have to confirm the email address of new users to satisfy the double opt-in requirement, which means you need to have a working email system to run a Friendica node, there's no way around it.

**Comment by tek-aevl** [comment]
Ok, so is there a default example for 
phpmailer.config.php

**Comment by tek-aevl** [comment]
? Configuration

The configuration options for this module are described in the config/phpmailer.config.php file.
I don't see this file...

**Comment by MrPetovan** [comment]
Please look in the addon folder `addon/phpmailer/config`.

**Comment by tek-aevl** [comment]
I just came back to edit with nvm, lol. Thanks.

**Comment by tek-aevl** [comment]
So is there a way to test that email is sending? or some logs for this?
