### ISSUE TITLE
Normalize @-tag/@-mention in hosted documentation

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#13180]
Both "@-tag" and "@-mention" are used in the hosted documentation, we need to pick one and replace all the other occurrences.

**Comment by Raroun** [comment]
I´ll do it :)

**Comment by tobiasd** [comment]
For me it is a mention, I never understood the *tag* reference.

**Comment by MrPetovan** [comment]
Probably from the confusion with hashtag, hash-tag, #-tag.

**Comment by Raroun** [comment]
I also would prefer the @-mention

**Comment by MrPetovan** [comment]
Go for it!

**Comment by Raroun** [comment]
I wait until the pull request "Replace "forum" by "group" #13183" is through. There are some grammatical errors there after the change from forum to groups, which I can fix directly with.
@-tag occurred only 3-4 times :)

**Comment by MrPetovan** [comment]
At this rate, you're better off making the changes yourself now and I'll rebase my huge PR onto yours.

**Comment by Raroun** [comment]
my PR misses the new Groups.md - ill add that

**Comment by MrPetovan** [comment]
These files have been renamed in my PR only, they won't be available from the current `develop`. Please add your changes to the existing `Forums.md` files.
