### ISSUE TITLE
"MySQL server has gone away" error in the log

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13195]
Seems like sql injection?

<html><body>

2023-06-04T15:50:43Z | ERROR | worker | DB Error
-- | -- | -- | --

<h3 class="event-data-header">Data</h3>
<div class="event-source">
</div>
<div class="event-data"><details open=""><summary>code</summary><pre>2006</pre></details><details open=""><summary>error</summary><pre>MySQL server has gone away</pre></details><details open=""><summary>callstack</summary><pre>DBA::selectFirst (2457), Contact::setAccountUser (2382), Contact::updateContact (2805), Contact::updateFromProbeArray (2590), Contact::updateFromProbe (47), UpdateContact::execute, Worker::execFunction (386), Worker::execute (121)</pre></details><details open=""><summary>params</summary><pre>SELECT `id`, `uid`, `uri-id` FROM `account-user` WHERE (`uid` = 0 AND `uri-id` = 16883) LIMIT 1</pre></details></div>
</body>
</html>

**Comment by MrPetovan** [comment]
This error arises from a connection issue between the PHP process and the database daemon, it generally has nothing to do with the query itself.

**Comment by tek-aevl** [comment]
System updates cause this machine to need to be migrated and when I got it to come back up, the logs show a few errors like this.

**Comment by Raroun** [comment]
Please have a look at your MariaDB log at the time Friendica logged the error.
There you will usually find the reason.
If you have the error message, feel free to post it here - at least most of the time I can interpret the messages well and offer a solution.

**Comment by tek-aevl** [comment]
Thanks
