### ISSUE TITLE
Resource (frio) blocked beause of MIME type mismatch

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13201]
- [X ] I have searched open and closed issues for duplicates

### Bug Description
In the developer tools of Firefox and Chrome I get this MIME type error on every Friendica page.

```
The resource from “https://example.com/view/js/button/frio.css?v=” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

### Steps to Reproduce

1.  open web developer tools of your browser
2.  reload the page of Friendica
3.  see the error message

Actual Result:
MIME type mismatch for a frio CSS file because type is set to "text/html". Resource is blocked. 

Expected Result:
Resource shouldn't be blocked.

### Platform Info

Friendica Version:
2023.05 and 2023.09-dev

Friendica Source: 
git

PHP version:
8.1

SQL version:
10.6 MariaDB

**Comment by MrPetovan** [comment]
It's outputting `text/html` because this file doesn't exist and it's showing the "Not Found" page instead. Thank you for the report, this reference should be removed.
