### ISSUE TITLE
[frio] Wrong z-index of left side menu with showmore_dyn enabled 

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13205]
- [X ] I have searched open and closed issues for duplicates

### Bug Description
When using frio and the addon showmore_dyn on a mobile device the z-index of the left side menu is wrong. It's also possible that showmore_dyn has a problem with the z-index. See screenshot.

### Steps to Reproduce

1.  enable addon showmore_dyn 
2.  scroll to a position with a show more button
3.  open the left side menu 

Actual Result:
Menu is under the show more area.

Expected Result:
Menu should be over all other things

### Screenshots

![Screenshot_20230608-175619](https://github.com/friendica/friendica/assets/3656054/47dbb66e-de6e-425b-b49d-362401627c83)

### Platform Info

Friendica Version:

2023.09-dev

Friendica Source: 

git

PHP version:

8.1

SQL version:

10.6 MariaDB

**Comment by Raroun** [comment]
i´ll look into it :)

**Comment by Raroun** [comment]
unfunfortunately I'm very busy at work this week - but this weekend I have time to look at it :)

**Comment by Raroun** [comment]
After i totally forgot about this issue, i discovered there is already a pull request here:

https://git.friendi.ca/csolisr/friendica-addons/pulls/1

**Comment by MrPetovan** [comment]
Hmm, the PR was submitted to a fork, we can't merge it in the project repository.

**Comment by haheute** [comment]
I can't reproduce this.. It seems to work here..

**Comment by AlfredSK** [comment]
Need to check again. Maybe it has been solved by magic. 😁

**Comment by AlfredSK** [comment]
Yeah. Seems so. 

![Screenshot_20240326-171720](https://github.com/friendica/friendica/assets/3656054/9e1cd7d6-88b4-441e-aeb6-245f82c43d6e)
