### ISSUE TITLE
/toggle_mobile being used by spammers

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#13216]
### Is the feature request related to a problem? Please describe.

I currently have many requests to `/toggle_mobile?address=https://other-address.example`. I guess spammers suffer from URL blocks now have discovered that Friendica has an unchecked/unprotected redirect "service" where they can use our software to circumvent those URL blocklists.

Let me explain it for you:
1. Spammer floods someone's guestbook/comment section with his URL `https://evil.example`
2. The website owner realizes this and bans `evil.example` entirely
3. The spammer noticed this and uses URLs like `https://f.haeder.net/toggle_mobile?address=https://evil.example` instead to circumvent the URL block
4. visitors are redirected to his website until also `f.haeder.net` is also blocked

### Describe the feature you'd like

I think we don't want this! For my own software, I added a hash to the URL which consists of a private key (unknown to the spammer), a salt (to make "guessing" it harder) and the targeted URL. If it is an approved URL by the Friendica administrator, the computed hash will be the same and the redirect happens. If it is not the same, the request is blocked with a message "Invalid hash". If no hash is provided, it is also blocked (so spammers cannot rely on old URLs anymore).

### Describe alternatives you've considered

I cannot think of any alternative here, letting our Friendica installations wide open for spammers is not an option. I have temporary disabled that route (by removing it from `static/routes.config.php`.

### Additional context

**Comment by MrPetovan** [comment]
Thank you for the report, we've closed such an attack avenue with the `/redir` path but there still is some work. If the target address is meant to be local, we can check that the provided URl is local or start using relative path and rejecting URLs with scheme and domain.

**Comment by Quix0r** [comment]
The only `/redir` path that I found was for `/contact`. And yes, `/toggle_mobile?address=foo` should be local URLs only. `address` receives the value of `$this->curPageURL()` which is in turn a wrapper method around `$_SERVER` elements.
