### ISSUE TITLE
Can't open reshared Diaspora posts

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13213]
I hope this is the right place for this issue:

Since some days I observe the problem that I cannot open reshared posts.

For example here: https://boerdica.de/display/e0c29ea0ebd4013bfda928a1592b385a
I can open this post, but I can't open the reshared post below (click the date + time). I don't understand what could cause this.. 

Thanks for help

**Comment by MrPetovan** [comment]
We've had other issues with Diaspora posts recently, maybe it is related.

**Comment by haheute** [comment]
It seems I only receive reshared posts from diaspora. Like this one: https://boerdica.de/display/5d64ad50f02b013bd6af268acd52edbf

The original posts can not be opened and also are not displayed on the contacts pages on my system..
(I mean I don't see _direct_ posts from the contacts, only when they reshare something.)

related discussion: https://boerdica.de/display/a1e4bf6c-1164-856f-6c27-0b6682628954

**Comment by haheute** [comment]
now the post come in again :+1:  .. except reshared posts from at least 1 pod, which is: pod.mttv.it
I don't know why. that is maybe another issue
