### ISSUE TITLE
Syntax error in include/api.php

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1321]
In the development branch, the logs report an Syntax error in the include/api.php:

[Tue Jan 27 18:05:53 2015] [error] [client 79.157.165.184] PHP Parse error:  syntax error, unexpected '[' in /var/www/virtual/snarl.de/htdocs/include/api.php on line 1646

**Comment by annando** [comment]
it is part of the starring and unstarring of items. I guess @fabrixxm built that? Meybe he can have a look at it to see whether this was intended and it's just a problem with different PHP versions?

**Comment by fabrixxm** [comment]
Most of the time, I hate php... :-)

**Comment by annando** [comment]
Can we close it?

**Comment by tugelbend** [comment]
Yes.
