### ISSUE TITLE
Uploading photo leads to wsod.

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13215]
Not sure why, but after my last update/recovery almost all photo are blurred, uploading leads to wsod, or I get the crop screen then when hitting save it wsod, but the logs say permission issue, even though I set them to www-data:www-data 755, problem still happens.
Friendica\Core\Storage\Exception\StorageException: Filesystem storage failed to create "/var/www/uploads/8a/1a". Check you write permissions. in /var/www/friendica/src/Core/Storage/Type/Filesystem.php:94

**Comment by MrPetovan** [comment]
Can you please post the result of the following commands:
```
ls -al /var/www
ls -al /var/www/uploads/8a
df -h
```

**Comment by tek-aevl** [comment]
```
ls -al /var/www
total 48
drwxr-xr-x   7 www-data www-data  4096 Jun 15 03:22 .
drwxr-xr-x  14 root     root      4096 Jul  6  2022 ..
-rw-r--r--   1 www-data www-data    26 Apr 26 00:10 gitupdate
-rw-r--r--   1 root     www-data     0 Jun 11 13:31 .htaccess
drw-r-xr--   2 root     www-data  4096 Jun 11 15:35 html
-rw-r--r--   1 root     www-data    14 Jun 11 14:03 index.html
drw-r--r--   2 www-data www-data  4096 May 30 01:01 logs
drwxr-xr-x   2 www-data www-data  4096 Dec  1  2022 tmp
-rw-r--r--   1 www-data www-data   445 May 28 03:48 update
drw-rw-r-x 259 www-data www-data 12288 Dec  1  2022 uploads


ls -al /var/www/uploads/8a
ls: cannot access '/var/www/uploads/8a': Permission denied

 df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           702M  1.2M  701M   1% /run
/dev/vda2        98G   55G   39G  60% /
tmpfs           2.9G  168K  2.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           576M   12K  576M   1% /run/user/1000
```

**Comment by MrPetovan** [comment]
Thanks, what about the following commands?
```
whoami
ls -al /var/www/uploads
```

**Comment by tek-aevl** [comment]
Is this normal?>
if I run it as my user and results were ? ? ?  /
Is this normal?>
as sudo 
total 1056
drwxrw-r-x 259 www-data www-data 12288 Dec  1  2022 .
drwxr-xr-x   7 www-data www-data  4096 Jun 15 03:22 ..
drwxrw-r-x 258 www-data www-data  4096 Dec 27 04:23 00
drwxrw-r-x 258 www-data www-data  4096 Dec 27 21:40 01
drwxrw-r-x 258 www-data www-data  4096 Dec 28 03:33 02
drwxrw-r-x 258 www-data www-data  4096 Dec 26 18:19 03
drwxrw-r-x 258 www-data www-data  4096 Dec 26 15:29 04
drwxrw-r-x 258 www-data www-data  4096 Dec 27 20:24 05
drwxrw-r-x 258 www-data www-data  4096 Dec 27 09:46 06
drwxrw-r-x 258 www-data www-data  4096 Dec 27 20:43 07
drwxrw-r-x 258 www-data www-data  4096 Dec 26 12:54 08
drwxrw-r-x 258 www-data www-data  4096 Dec 26 20:16 09
drwxrw-r-x 258 www-data www-data  4096 Dec 27 13:21 0a
drwxrw-r-x 258 www-data www-data  4096 Dec 28 01:51 0b
drwxrw-r-x 258 www-data www-data  4096 Dec 29 18:38 0c
drwxrw-r-x 258 www-data www-data  4096 Dec 26 14:40 0d
drwxrw-r-x 258 www-data www-data  4096 Jan  7 15:40 0e
drwxrw-r-x 258 www-data www-data  4096 Dec 26 13:29 0f
drwxrw-r-x 258 www-data www-data  4096 Dec 26 20:08 10
drwxrw-r-x 258 www-data www-data  4096 Feb 12 18:59 11
drwxrw-r-x 258 www-data www-data  4096 Dec 26 03:21 12
drwxrw-r-x 258 www-data www-data  4096 Jan 13 18:10 13
drwxrw-r-x 258 www-data www-data  4096 Dec 25 18:58 14
drwxrw-r-x 258 www-data www-data  4096 Jan  3 03:15 15
drwxrw-r-x 258 www-data www-data  4096 Jan  4 03:28 16
drwxrw-r-x 258 www-data www-data  4096 Dec 26 09:31 17
drwxrw-r-x 258 www-data www-data  4096 Dec 27 08:16 18
drwxrw-r-x 258 www-data www-data  4096 Dec 26 22:31 19
drwxrw-r-x 258 www-data www-data  4096 Dec 27 08:26 1a
drwxrw-r-x 258 www-data www-data  4096 Jan 20 11:56 1b
drwxrw-r-x 258 www-data www-data  4096 Dec 25 10:42 1c
drwxrw-r-x 258 www-data www-data  4096 Dec 27 08:09 1d
drwxrw-r-x 258 www-data www-data  4096 Dec 27 10:16 1e
drwxrw-r-x 258 www-data www-data  4096 Jan 20 07:29 1f
drwxrw-r-x 258 www-data www-data  4096 Dec 25 15:45 20
drwxrw-r-x 258 www-data www-data  4096 Dec 26 15:08 21
drwxrw-r-x 258 www-data www-data  4096 Dec 28 03:52 22
drwxrw-r-x 258 www-data www-data  4096 Jan 21 15:31 23
drwxrw-r-x 258 www-data www-data  4096 Jan  2 22:53 24
drwxrw-r-x 258 www-data www-data  4096 Dec 27 16:12 25
drwxrw-r-x 258 www-data www-data  4096 Dec 27 17:18 26
drwxrw-r-x 258 www-data www-data  4096 Dec 27 16:08 27
drwxrw-r-x 258 www-data www-data  4096 Dec 27 06:24 28
drwxrw-r-x 258 www-data www-data  4096 Dec 29 15:38 29
drwxrw-r-x 258 www-data www-data  4096 Dec 26 06:47 2a
drwxrw-r-x 258 www-data www-data  4096 Dec 26 05:12 2b
drwxrw-r-x 258 www-data www-data  4096 Jan 20 22:20 2c
drwxrw-r-x 258 www-data www-data  4096 Dec 26 20:56 2d
drwxrw-r-x 258 www-data www-data  4096 Dec 27 02:39 2e
drwxrw-r-x 258 www-data www-data  4096 Dec 27 17:45 2f
drwxrw-r-x 258 www-data www-data  4096 Dec 27 23:15 30
drwxrw-r-x 258 www-data www-data  4096 Jan 20 20:27 31
drwxrw-r-x 258 www-data www-data  4096 Dec 26 21:20 32
drwxrw-r-x 258 www-data www-data  4096 Dec 27 01:03 33
drwxrw-r-x 258 www-data www-data  4096 Dec 27 20:24 34
drwxrw-r-x 258 www-data www-data  4096 Dec 26 01:20 35
drwxrw-r-x 258 www-data www-data  4096 Dec 27 18:34 36
drwxrw-r-x 258 www-data www-data  4096 Dec 26 06:07 37
drwxrw-r-x 258 www-data www-data  4096 Dec 27 13:28 38
drwxrw-r-x 258 www-data www-data  4096 Dec 26 05:11 39
drwxrw-r-x 258 www-data www-data  4096 Dec 25 23:14 3a
drwxrw-r-x 258 www-data www-data  4096 Dec 26 05:13 3b
drwxrw-r-x 258 www-data www-data  4096 Dec 27 12:39 3c
drwxrw-r-x 258 www-data www-data  4096 Dec 27 17:57 3d
drwxrw-r-x 258 www-data www-data  4096 Jan 21 10:04 3e
drwxrw-r-x 258 www-data www-data  4096 Dec 26 06:37 3f
drwxrw-r-x 258 www-data www-data  4096 Jan  4 02:54 40
drwxrw-r-x 258 www-data www-data  4096 Dec 27 07:46 41
drwxrw-r-x 258 www-data www-data  4096 Dec 25 11:54 42
drwxrw-r-x 258 www-data www-data  4096 Jan 18 12:55 43
drwxrw-r-x 258 www-data www-data  4096 Dec 25 22:50 df
drwxrw-r-x 258 www-data www-data  4096 Dec 26 01:28 e0
drwxrw-r-x 258 www-data www-data  4096 Dec 27 13:34 e1
drwxrw-r-x 258 www-data www-data  4096 Dec 25 17:12 e2
drwxrw-r-x 258 www-data www-data  4096 Dec 26 02:33 e3
drwxrw-r-x 258 www-data www-data  4096 Dec 27 08:38 e4
drwxrw-r-x 258 www-data www-data  4096 Dec 28 00:15 e5
drwxrw-r-x 258 www-data www-data  4096 Dec 26 14:06 e6
drwxrw-r-x 258 www-data www-data  4096 Dec 26 08:41 e7
drwxrw-r-x 258 www-data www-data  4096 Dec 25 20:24 e8
drwxrw-r-x 258 www-data www-data  4096 Dec 27 22:01 e9
drwxrw-r-x 258 www-data www-data  4096 Dec 25 22:47 ea
drwxrw-r-x 258 www-data www-data  4096 Dec 26 00:31 eb
drwxrw-r-x 258 www-data www-data  4096 Jan  3 13:15 ec
drwxrw-r-x 258 www-data www-data  4096 Dec 27 18:07 ed
drwxrw-r-x 258 www-data www-data  4096 Dec 26 05:19 ee
drwxrw-r-x 258 www-data www-data  4096 Dec 25 20:53 ef
drwxrw-r-x 258 www-data www-data  4096 Dec 27 00:53 f0
drwxrw-r-x 258 www-data www-data  4096 Dec 26 05:26 f1
drwxrw-r-x 258 www-data www-data  4096 Dec 27 18:50 f2
drwxrw-r-x 258 www-data www-data  4096 Dec 26 22:03 f3
drwxrw-r-x 258 www-data www-data  4096 Dec 26 23:31 f4
drwxrw-r-x 258 www-data www-data  4096 Dec 27 06:13 f5
drwxrw-r-x 258 www-data www-data  4096 Dec 27 12:03 f6
drwxrw-r-x 258 www-data www-data  4096 Dec 25 21:04 f7
drwxrw-r-x 258 www-data www-data  4096 Jan  3 08:25 f8
drwxrw-r-x 258 www-data www-data  4096 Jan 21 19:47 f9
drwxrw-r-x 258 www-data www-data  4096 Jan 20 23:53 fa
drwxrw-r-x 258 www-data www-data  4096 Dec 26 09:04 fb
drwxrw-r-x 258 www-data www-data  4096 Jan 20 03:55 fc
drwxrw-r-x 258 www-data www-data  4096 Dec 26 02:20 fd
drwxrw-r-x 258 www-data www-data  4096 Dec 27 07:08 fe
drwxrw-r-x 258 www-data www-data  4096 Jan 21 16:10 ff
-rwxrw-r-x   1 www-data www-data    21 Nov 13  2022 getCachedDispatchData.sem
-rwxrw-r-x   1 www-data www-data     0 Nov 23  2022 http-0wpDSj
-rwxrw-r-x   1 www-data www-data     0 Nov 15  2022 http-2hmFvO
-rwxrw-r-x   1 www-data www-data     0 Nov 13  2022 http-2yYTdU
-rwxrw-r-x   1 www-data www-data     0 Nov 28  2022 http-6Ynxsu
-rwxrw-r-x   1 www-data www-data     0 Nov 17  2022 http-6ZjIxy
-rwxrw-r-x   1 www-data www-data     0 Nov 20  2022 http-8RgwjL
-rwxrw-r-x   1 www-data www-data     0 Nov 25  2022 http-9IxjXu
-rwxrw-r-x   1 www-data www-data     0 Nov 20  2022 http-ASYdCJ
-rwxrw-r-x   1 www-data www-data     0 Nov 23  2022 http-Av4tiv
-rwxrw-r-x   1 www-data www-data     0 Nov 14  2022 http-DQAjlC
-rwxrw-r-x   1 www-data www-data     0 Nov 25  2022 http-e7rEnv
-rwxrw-r-x   1 www-data www-data     0 Nov 16  2022 http-Emrh1u
-rwxrw-r-x   1 www-data www-data     0 Nov 20  2022 http-gB116q
-rwxrw-r-x   1 www-data www-data     0 Nov 22  2022 http-ICNtY6
-rwxrw-r-x   1 www-data www-data     0 Nov 19  2022 http-KdklvP
-rwxrw-r-x   1 www-data www-data     0 Nov 14  2022 http-KpaNjf
-rwxrw-r-x   1 www-data www-data     0 Nov 18  2022 http-LmTiQr
-rwxrw-r-x   1 www-data www-data     0 Nov 20  2022 http-LoFcHt
-rwxrw-r-x   1 www-data www-data     0 Nov 16  2022 http-MvkcLC
-rwxrw-r-x   1 www-data www-data     0 Nov 14  2022 http-n7mO1C
-rwxrw-r-x   1 www-data www-data     0 Nov 21  2022 http-Q9BjBy
-rwxrw-r-x   1 www-data www-data     0 Nov 18  2022 http-s9lsWq
-rwxrw-r-x   1 www-data www-data     0 Nov 25  2022 http-SDCR63
-rwxrw-r-x   1 www-data www-data     0 Nov 15  2022 http-thy4eu
-rwxrw-r-x   1 www-data www-data     0 Nov 23  2022 http-uaT48Q
-rwxrw-r-x   1 www-data www-data     0 Nov 16  2022 http-VbdcLD
-rwxrw-r-x   1 www-data www-data     0 Nov 23  2022 http-Vp3wlg
-rwxrw-r-x   1 www-data www-data     0 Nov 14  2022 http-W8jrHe
-rwxrw-r-x   1 www-data www-data     0 Nov 19  2022 http-wqvIMb
-rwxrw-r-x   1 www-data www-data     0 Nov 18  2022 http-xwhlzY
-rwxrw-r-x   1 www-data www-data     0 Nov 21  2022 http-yjVHSl
-rwxrw-r-x   1 www-data www-data     0 Nov 16  2022 http-zHfYw3
-rwxrw-r-x   1 www-data www-data     0 Nov 21  2022 http-Zl6Bhf
-rwxrw-r-x   1 www-data www-data     0 Nov 15  2022 index.html
drwxrw-r-x   2 www-data www-data  4096 Dec 25 04:36 spool
-rwxrw-r-x   1 www-data www-data    14 Nov 13  2022 worker_process.sem
-rwxrw-r-x   1 www-data www-data     6 Nov 13  2022 worker.sem

**Comment by MrPetovan** [comment]
The permissions of the `/var/www/uploads` are wrong, they're missing the `x` flag for user and group.
Instead of
```
drw-rw-r-x 259 www-data www-data 12288 Dec  1  2022 uploads
```
It should be
```
drwxrwxr-x 259 www-data www-data 12288 Dec  1  2022 uploads
```
You can do this with the following command:
```
sudo chmod 775 /var/www/uploads
```
From then on it should work.

**Comment by tek-aevl** [comment]
Seems like it worked and the upload photo screen seems different.
