### ISSUE TITLE
Search for Lemmy post or comment not working

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#13211]
Fetching of comments from Lemmy is not working, example URL:
https://lemmy.ml/comment/519205

Same for post URLs:
https://lemmy.ml/post/1203763

But then it works for this link, so what's the difference?
https://lemmy.world/post/55240
Here completion of the thread would be nice, I mean on Lemmy it is even mor important to completely load the whole thread. 

So fetching by searching does just show a empty result page as if you searched for a tag that returns no result. 

Roland got the same problem, see [here](https://social.yl.ms/display/adbba6c6-1864-863b-0733-d91040363624). 

Current stable version of Friendica and some PHP 8.2 if it matters.

I can add other information later when I have access with my laptop if needed, please let me know.

**Comment by utzer** [comment]
Alright, I think I found the problem and it is a interface problem of Lemmy... or well it is a human problem. This is what you call a pain in the ass anyway, usability issue I guess, you can not copy the link from the link symbol but you need to copy it from the small Fediverse symbol instead. 

So when you go to https://lemmy.ml/post/1203763 you need to copy the link of the small rainbow umbrella (Fediverse symbol that each post/comment has) and that will work to search for, ie. this one here https://lemmy.world/post/55240

**Comment by MrPetovan** [comment]
Would you be able to open an issue on the Lemmy repository about this?
