### ISSUE TITLE
URL Masking Addon

### ISSUE THREAD

**Issue by shiribailem** [friendica/friendica#13220]
In the vein of the Nitter Addon, I'd like an addon for automatically translating admin specified links to certain pages.

An example might be to maintain a list of news websites to automatically translate to https://12ft.io/ links, but rather than a specific addon just for that it might make sense to have a general addon that allows multiple uses cases (though possibly with some pre-defined defaults).

The general idea of configuration:
* A way to enter multiple lists of sites to match (since you might use this for multiple ends, ie. both Nitter and 12ft on the same node).
* A list of sites
* A site to substitute
* A checkbox to either substitute the domain name (like Nitter) or put the URL after the substitute URL (like 12ft.io)

This is probably a junior task as it could be built off the skeleton of the nitter addon, just adding more options.

**Comment by toddy15** [comment]
Hi,

after meeting @tobiasd on 37C3, I got some new enthusiasm for contributing to Friendica. So I'd like to give this a go. :slightly_smiling_face:

However, I could need some advice for this: How (or where) are addons developed? Do I start in a separate git repository and propose to merge later? Or do I clone the addons repository, add a new directory and submit a PR from there?

Regards,
Tobias

**Comment by MrPetovan** [comment]
Please clone the Addons repository currently hosted on our Gitea server: https://git.friendi.ca/friendica/friendica-addons

I see you have already your own user fork. You can then duplicate the `nitter` folder and rename it to your addon name. Also rename the `nitter.php` file to the same name. You will have to perform additional string replacements in the file itself to match the new name. If you have additional questions about the inner working of the addon, I'll be glad to answer them.

**Comment by toddy15** [comment]
Thanks, I'll start with that and see how it goes. :+1:

**Comment by toddy15** [comment]
Here is a PR: https://git.friendi.ca/friendica/friendica-addons/pulls/1453

**Comment by MrPetovan** [comment]
Oh, I discovered auto-closing words in commit messages!

**Comment by toddy15** [comment]
Glad that I could show you this little trick! Here's the documentation, there are several keywords to close PRs with commit messages:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by MrPetovan** [comment]
I knew those words could be used in pull requests, but I didn't expect them to be active in commits pushed on a remote repository only mirrored on GitHub.
