### ISSUE TITLE
Distributed postings from Diaspora unwanted in network stream

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#13221]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

In the 2023.09-dev version of Friendica unwanted postings from Diaspora SPAM the network stream (see [the associated support forum thread](https://forum.friendi.ca/display/f3ad7b1c-2264-8497-e20b-ef2139658021)). The authors of the postings are not connected to me and the Friendica UI shows as information why the posting is displayed that it was "distributed". They don't match saved searches, nor any tag list that are imported from relays as far as I can tell.

This happens with postings that have and also with postings that have no visual interaction (likes / comments) by other accounts where no connection exists either.

Here is an [log example](https://social.diekershoff.de/request-id-64848ff4c2a7c.txt) from one of these postings.

### Steps to Reproduce

1.  run Friendica 2023.09-dev
2.  ???
3.  see "distributed" postings from Diaspora users of no visual connection in the network stream

Actual Result:

Receiving SPAM from Diaspora.

Expected Result:

Not to receive SPAM in my network stream.

### Screenshots

Example screenshot of a posting with no visible interactions by others. As I use the German translation of the interface, the mouse over text reads "Verteilt" which is the translation used for "Distributed".

![grafik](https://github.com/friendica/friendica/assets/433490/f220dda9-e0c6-4e20-bf70-54590e8759f1)

### Platform Info

Friendica Version: 2023.09-dev

Friendica Source: git

PHP version: 8.0

SQL version: MariaDB Debian Bullseye

**Comment by atasingorneq** [comment]
On my instance I have the same problem. Very many diaspora posts from accounts I don't interact with.

Friendica 'Giant Rhubarb' 2023.09-dev - 1522
PHP 8.2.7

**Comment by annando** [comment]
I found the origin, this problem was introduced by PR https://github.com/friendica/friendica/pull/13208

This evening I will isolate the issue and will create a PR to fix it.
