### ISSUE TITLE
Tusky not showing users who boosted / favourited a post when querying via friendica account

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13236]
Android: 13.0
Tusky: 22.0
Device: Gauguin
Friendica: squeet.me + pirati.ca both on 2023.09-dev

**Currently**

When looking at post details and tapping Favourites or Boosts the list that should show the users is blank.

**Expected**

Users who favourited or boosted a post should be shown. This works as expected with mastodon accounts. The blank page only shows when using a friendica account.

**Additional info**

Afaik this never worked. Question is, what is wrong and where this needs to fixed. In friendica webUI when hovering reactions or favourites, a tooltip shows the corresponding users. So the information is available. Maybe this is a shortcoming in friendica of how it corresponds this information via mastodon API? If we need a bug in friendica happy to file that. Ideally with more details as to what is going wrong.

Tusky dev connyduck added:
> The Api seems to always return empty arrays on the `/api/v1/statuses/:id/reblogged_by` and `/api/v1/statuses/:id/favourited_by` endpoints. I don't think there is anything we can do about that, it is a Friendica problem.
https://github.com/tuskyapp/Tusky/issues/3776#issuecomment-1607652306

![fav](https://github.com/tuskyapp/Tusky/assets/5708172/10c7c109-e537-4285-8b06-c5a6c325e09b) ![boost](https://github.com/tuskyapp/Tusky/assets/5708172/9030933b-42aa-498a-a7b9-2547d086a4dd)

**Comment by kr428** [comment]
Noticed that too on Fedilab.

**Comment by foss-** [comment]
Works as expected in latest RC branch
+ Fedilab 3.24.1
+ Tusky 24.0
