### ISSUE TITLE
Mixed encryption error

### ISSUE THREAD

**Issue by anthronaut** [friendica/friendica#1323]
After having run my friendica server unencrypted for a while I installed an SSL certificate and turned on the "forced SSL links" and "forced SSL" options. It worked fine, except on the "Network" and "Profile" pages browsers would throw a mixed encryption error. The unencrypted media were in all cases contact icons.

I found that the function *micropro* in the file */includes/test.php* executes a DB query for the contact icon URI's. The URI's of the unencrypted files were stored with a HTTP:// scheme in the database. Manually changing the entries to HTTPS:// fixed the error. It did not appear again, when I subsequently added unencrypted sites to my contact list.

I did a double-check: Turned off both SSL options, added an unencrypted site, turned on both options and the error appeared again.

In my opinion, this is not a grave bug - I doubt that admins will go on switching the SSL options on and off frequently.

**Comment by annando** [comment]
I did a pull request for that.
