### ISSUE TITLE
Calendar events are visible to people they are not shared with

### ISSUE THREAD

**Issue by russell-phillips** [friendica/friendica#13240]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Calendar event shared with limited number of people appears in other people's fediverse feed.

### Steps to Reproduce

1.  Create a calendar event
2.  On permissions tab, set to show to one person
3.  View timeline of someone who is following the user that created the calendar event

Actual Result:

Calendar event appears in fediverse feed of person that is following user

Expected Result:

Calendar event should only appear in feed of person that it is to be shown to

### Screenshots

![Sharing with one person - event details](https://github.com/friendica/friendica/assets/8222297/a5b29b31-aa5c-4693-8481-35b2680fa783)
Creating event

![Sharing with one person - permissions](https://github.com/friendica/friendica/assets/8222297/a58feb84-bd0f-494c-8fb1-821eda70a396)
Setting permissions - only visible to one person

![Sharing with one person - event visible on Mastodon](https://github.com/friendica/friendica/assets/8222297/48f79f66-6613-4af9-b4e7-3af89db59a63)
Event is visible on another person's Mastodon feed

### Platform Info

Friendica Version: 
This is Friendica, version 2023.05 that is running at the web location https://social.justec.co.uk. The database version is 1518/1518, the post update version is 1507/1507.

Friendica Source: 

PHP version: PHP 7.4.33

SQL version: 10.5.19-MariaDB-0+deb11u2 - Debian 11

**Comment by tobiasd** [comment]
Confirmed in the current 2023.09-dev branch

**Comment by MrPetovan** [comment]
Confirmed again now that I'm looking into it.
