### ISSUE TITLE
"Friendica allows markup to hide urls, one of the most basic of online safty (sic) layers?"

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13256]
Today I found [this post](https://mstdn.social/@kevinrns/110664420029871643) this post in my timeline, is this something to care about?

**Comment by annando** [comment]
I'm unsure what he is talking about in his post. And also this is more than overreacting here.

**Comment by MrPetovan** [comment]
This person is talking about HTML links that can have a different label than the URL it's leading to. They consider this a "crime" because it can be abused to hide a malicious link that wouldn't be able to be expanded on mobile devices behind an innocuous label.

I guess it is an attack vector, however having full URLs in posts doesn't completely cover it, so I don't see any benefit to curtail Friendica's formatting capabilities.

**Comment by annando** [comment]
I know that Friendica does make some stuff differently than other systems. And some of the feature could possibly annoy people. But that link descriptions could annoy people, I hadn't got on my bingo card.

**Comment by ne20002** [comment]
Ok, but is this something that only affects the Web-UI or is this something that is in the messages and therefore affects other servers/clients when they display content created on Friendica?

**Comment by MrPetovan** [comment]
Friendica displays a subset of HTML from remote servers which includes `<a>` tags with a different label from its URL, but how Friendica posts displays on other services/clients is out of our hands. We do send the full post body HTML to them, and they can do whatever they want with it.

**Comment by annando** [comment]
@ne20002 AFAIK Calckey for example is added the linked domain name behind the link, so people know the link target. But this really is a task for the target systems.

**Comment by ne20002** [comment]
Ok, got it. So the idea of the original poster in the mentioned thread to block Friendica instances because Friendica is doing this and as Friendica is doing this only in its own web UI is a bit out of line.

**Comment by MrPetovan** [comment]
Some remote platforms might display Friendica HTML links as is but there’s nothing we can do about it. 🤷‍♂️

**Comment by annando** [comment]
From my point of view I recommend to open issues at the remote systems, so that they display the hostname.
