### ISSUE TITLE
Will Meta get my data or be able to track me?

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13257]
Eugen Rochko posted a  [blog statement](https://blog.joinmastodon.org/2023/07/what-to-know-about-threads/) clarifiying a few things for Mastodon regarding Meta/Threads entering the Fediverse.

One part of the post is this:
```
Will Meta get my data or be able to track me?

Mastodon does not broadcast private data like e-mail or IP address outside of the server your account is hosted on. Our software is built on the reasonable assumption that third party servers cannot be trusted. For example, we cache and reprocess images and videos for you to view, so that the originating server cannot get your IP address, browser name, or time of access. A server you are not signed up with and logged into cannot get your private data or track you across the web. What it can get are your public profile and public posts, which are publicly accessible.
```
I wonder if we can have a similar statement for Friendica?

**Comment by MrPetovan** [comment]
Not exactly the same. We have the Proxy feature to achieve the same privacy level regarding images but it can be turned off to save disk space.

**Comment by ne20002** [comment]
Actually the blog post from Eugen Rochko made a few things clearer for me. I believe the general approach to consider any external/other server as potentially dangerous is a good design, especially in terms of privacy.
This is related to cross-origin policy also. Having Freindica able to proxy or serve anything a client would load would be an appreciated feature.
Would it be an idea to at least set some mark on a toot when it includes external (not from the own server) content or links to external resources. Or even have this suppressed until a user allows it explicitly (like 'load external images' in Thunderbird).

**Comment by MrPetovan** [comment]
From my point of view, Friendica started as pretty paranoid about privacy, and then it relaxed a little bit, including the possibility to turn off the proxy feature, but now with the arrival of commercial platforms within the decentralized social media space, we might have to turn the screw again.

**Comment by annando** [comment]
I think that the default settings are still okay. But we should check for leakage.

**Comment by ne20002** [comment]
> ... but now with the arrival of commercial platforms within the decentralized social media space ...

Yes, we need to keep this in mind.
