### ISSUE TITLE
[Addon] Extension of the Blockbot addon to include threads IP and domain names

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13255]
### Is the feature request related to a problem? Please describe.

Threads is the first commercial provider to join the Fediverse. Many admins are not comfortable with sharing data with these companies. Therefore, there should be an effective way to block META effectively.
With the addon Blockbot, a protective shield against GabSocial was built in the past. This mechanism should also be applied to threads.

### Describe the feature you'd like

Add another category Threads to the Blockbot addon and make sure that all known IPs and domains of threads are blocked. This would make it much easier for all admins who want to block threads to block them properly. Possible individual misadministrations can be avoided and user data is effectively protected.
### Additional context
https://anonsys.net/display/bf69967c-5364-a464-2d6f-950136024297

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/13286

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/13286 doesn't cover this feature request as it is a user-based remote server-wide moderation feature.

On the other hand the Blockbot addon is meant as a low-level User-Agent based way of blocking incoming requests. Both features aren't overlapping.
