### ISSUE TITLE
zrl URL parameter spam DoS misuse

### ISSUE THREAD

**Issue by kkretsch** [friendica/friendica#1326]
I just got a bunch (thousands) of requests (from vietnam) like that pattern:

"GET /profile/k_kretschmann?zrl=http://example.com

When I try that request with a target domain I have access to, I can see these requests originating from my friendica installation:

11.11.11.11 - - [28/Jan/2015:10:59:21 +0100] "GET /.well-known/host-meta HTTP/1.1" 404 7900 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"
11.11.11.11 - - [28/Jan/2015:10:59:21 +0100] "GET / HTTP/1.1" 200 16381 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"
11.11.11.11 - - [28/Jan/2015:10:59:21 +0100] "GET /feed/ HTTP/1.1" 200 11184 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"
11.11.11.11 - - [28/Jan/2015:10:59:40 +0100] "GET /.well-known/host-meta HTTP/1.1" 404 7900 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"
11.11.11.11 - - [28/Jan/2015:10:59:40 +0100] "GET / HTTP/1.1" 200 16381 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"
11.11.11.11 - - [28/Jan/2015:10:59:40 +0100] "GET /feed/ HTTP/1.1" 200 11184 "-" "Friendica 'Ginger' 3.3.2-1175; http://f.example.com"

My fear is I could be used as a DoS reflector. With just a small request I create lots of traffic for my server and the external one. How can we disable this behaviour?

**Comment by fabrixxm** [comment]
`zrl=` parameter usually is something like `http://friendicaserver/profile/username` and is appended to links to your profile with as value the profile's url of the user clicking on that link.
System uses this to know who is visiting the profile, to show (e.g.) friends in common.
To get useful data from that url, we need to request `host-meta`, to find user's XRD[1] , to find things like POCO (to get user's contacts, if we have permission to).

In your case above, I think that as you get 404 for  `host-meta`, the system load  top url and find a link to a rss feed, trying to find some useful information.

That said , if you get too many of request from someone you don't know, could be someone trying urls at random. Block the ip with iptable :-)

**Comment by kkretsch** [comment]
Blocking IPs only helps temporary after an possible attack. I think the host-meta request should be the only request friendica issues. Not the one for the homepage and possible feeds. Otherwise you realy could DoS yourself and/or others.

**Comment by annando** [comment]
I added a cache mechanism for the "probe_url" function. That means that repeated calls won't probe the systems over and over again - only once.

**Comment by kkretsch** [comment]
Thank you, that sounds like a good solution.

**Comment by kkretsch** [comment]
As I'm running Friendica 'Ginger' 3.3.2 - 1175 - when will that patch be received by a git pull?

**Comment by annando** [comment]
It will be in 3.3.3

**Comment by kkretsch** [comment]
I'm running 3.3.3 now and just today I got DoSed again. I get massive zrl requests from one or more IPs which I sort of forward to those sites. I think that feature is a massive security break for third party websites which might get DoSed by that way. But I haven't a clue how to get around that.

**Comment by annando** [comment]
This zrl parameter should point to another Friendica installation. And of course the ip should lead to this installation as well. Is that the case?

The caching should prevent a DoS possibility, since every server would only fetch a profile once.

**Comment by kkretsch** [comment]
It seems the zrl URL is misused and points not to friendica installations but to what ever website has to be attacked with traffic. As each zrl call to me seems to generate three requests to the remote side this might be a nice DoS multiplier, like the DNS reflector attack.
The caching doesn't help that much because the urls differ from call to call with slight random variations.
My zrl URL seems to circulate in some forums for beeing a nice jump server to attack third party websites.

Might it help to only request external friendica URLs if the zrl parameter URL matches some reasonable pattern? Otherwise I might just block that calls to my side by some modrewrite rule.

**Comment by annando** [comment]
We could improve the whole process so that we could check, whether this is a friendica installation at all and then block all upcoming variations to the same host. This should work, shouldn't it? I guess the variations aren't to the host?

**Comment by annando** [comment]
I just assigned it to the 3.4, since I think that this is a security thing that we should address.

**Comment by kkretsch** [comment]
Thanks for pushing that topic. I just found several attacks via an adserver pointing to my website with the fiverr.com zrl parameter. So you can book DoS attacks via adfarms? great! :-/

**Comment by annando** [comment]
The pull request was merged. It checks for the hostname of the target. If that stays the same, then repeated attacks aren't possible anymore.

**Comment by annando** [comment]
@kkretsch Could you test it? In my tests it worked great - but I don't get the described requests, so my tests are more theoretical.

Otherwise I would close this issue in the hope that it should work.

**Comment by kkretsch** [comment]
I just installed the 3.4 branch over my 333 and activated the debug log and got the first match.
[DEBUG]:boot.php:2193:zrl_init  DDoS attempt detected for mk.luckbagsoutlet.com
So I think this might be the solution we want.
Many thanks.

**Comment by annando** [comment]
Sounds good. Then I will close this issue.
