### ISSUE TITLE
Private replies to public thread are displayed in public profile

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13270]
Relating to https://loma.ml/display/373ebf56-1064-aba4-7ad9-701255739438 : Currently, whenever a public post receives non-public responses, it seems they still are displayed in a public Friendica profile view, essentially making them public without the sending user having in idea about that. See in example

![image](https://github.com/friendica/friendica/assets/685879/c2718c7d-8138-4d09-8a85-1010bb0f1c78)

Especially surprising is that the post view itself apparently seems to omit private messages in anonymous mode:

https://loma.ml/display/373ebf56-8564-aa4a-1190-ec4954279304

This is the behaviour that would be expected on the profile page too. At the moment this seems pretty ... difficult as, using "private" messages as such, sender will expect them to stay reasonably "private", otherwise this distinction doesn't really make sense.

**Comment by MrPetovan** [comment]
@annando Are you still looking into this?

**Comment by annando** [comment]
I still have to have a look at it.

**Comment by kr428** [comment]
Not sure, but could this be related?

![image](https://github.com/friendica/friendica/assets/685879/8377ce7e-996e-4095-acdf-1e67af9502d3)

In this case, a post has been labeled "private message" but most likely was a follower-only post. And there's one intermediate post (that has been responded to, in the thread) been missing. Two options I could think of:

- I'm not seeing the response that was responded to because, privacy-wise, I shouldn't. But then most likely that second-level response should be hidden too.
- I'm not seeing that intermediate response because permissions are broken, even while I actually should?

Not sure if this is the same problem though, but it feels close to it.

**Comment by kr428** [comment]
Seen just a moment ago on loma.ml (cc @loma-one ):

![image](https://github.com/friendica/friendica/assets/685879/d1cc0a0f-9a59-4d5d-89e1-f298c9986716)

Seems that ...

- ... the top-level post is public - https://social.tchncs.de/@beandev/111409250249103970 .
- ... there is a "hidden" response which apparently isn't public and/or visible for my account.
- ... there is a response marked as "private message" - https://social.tchncs.de/@beandev/111409256246618525 - which however still is visible in my timeline.

Not sure if this is the same issue, yet it still feels utterly disturbing...

**Comment by annando** [comment]
@kr428 please have got a look at the receivers for that comment. if the receivers are the follower collection of that author, then everything is okay. Then someone wrote a "followers only" reply (and you aren't a follower of that person) and that person answered "followers only" - and you are a follower of that person.

**Comment by kr428** [comment]
> @kr428 please have got a look at the receivers for that comment. if the receivers are the follower collection of that author, then everything is okay. Then someone wrote a "followers only" reply (and you aren't a follower of that person) and that person answered "followers only" - and you are a follower of that person.

Looks like it:

![image](https://github.com/friendica/friendica/assets/685879/dd4717a6-7d2b-4e06-92c8-651c8aebd9b1)

It still ... feels somehow weird. Especially given that this conversation, seen from Friendica at least, has "gaps". In the meantime, this has grown into a thread between the two people involved and every second message is invisible for me as I don't follow that "other" person. Wonder where exactly the "issue" is, here. Looking at this post from Mastodon (where I follow the same user too), I only see the top-level post and nothing below as the only "direct" response is one apparently set to follower-only by someone I am not following. To me, this kind of behaviour seems more "expected", and (though trivial in this case) I am unsure whether people writing communication in this kind of structure would expect this kind of messages to be seen by others...?

**Comment by HankG** [comment]
I may have found something related too. https://friendica.myportal.social/display/e65e1095-9465-5258-2587-afb140996486
There is a private thread in which started with a reply the person set to "mentioned people only" but when I replied to it through the API it came back as "followers only". I need to determine if is a problem with my app (Relatica of course), the API settings, or a combination of both. I have a bug on my side to look into that but haven't yet.

**Comment by kr428** [comment]
Given a recent discussion on Friendica helpers, I'd like to pour another thought in this:

- Take users A,B,C,D. Assume B,C,D are mutuals with A. D is mutual with B and C. B and C, however, dislike each other and, thus, don't follow each other and don't want to communicate at all.
- A does a post limited to "Followers". This is delivered to and seen by B,C,D.
- Both B and C respond to that post. Given the current implementation, A and D will see both responses, but B won't see Cs response and vice versa. Right?
- Now, consider D is responding to both the responses made by B and C. All responses will be visible by A (fine). B and C will still not see each others responses but they will see Ds responses to these. Right?

If I'm right here: This doesn't strictly _have_ to be a problem, but it causes a ... somewhat uncomfortable behaviour (at least from where I stand) as it essentially will leak information to B and C, information they might chose not to see or maybe mustn't be shown. B and C still will not see each others posts directly, but as soon as they see Ds responses, they will both most likely see who these responses address, and at they will be able to draw conclusions on what each other wrote by reading Ds responses. Is this expected and desirable? Or would it, in this case, be saner to avoid B and C seeing all responses to each others responses?

@annando ?

**Comment by kr428** [comment]
![Bildschirmfoto vom 2024-07-30 15-42-45](https://github.com/user-attachments/assets/a57228fb-0e27-4b56-852b-444ae9bc3cb1)

This is still an issue in 2024.06rc as far as I see? This ...

https://loma.ml/display/373ebf56-1566-a8c7-b24a-2df135293111 

... is the post. This ...

https://loma.ml/display/4c926222-fe4b065c3a8a8fd1-5944333e

.. is one of the private responses. This ...

https://troet.cafe/@Hope/112875104127109414

... is the corresponding post on the sending system (Mastodon). This is what clicking the "lock" icon says:

![image](https://github.com/user-attachments/assets/548d32a8-0d9b-4277-b8db-84f2ca8ef930)

It's obvious to see that not just for me as it is follower-only not "private", but seeing these things pop up on a public profile seen by unauthenticated users is ... really difficult, especially for users who send such messages (and probably trust all involved systems to handle things in a certain manner).

**Comment by tobiasd** [comment]
> ... is the post. This ...
> 
> https://loma.ml/display/4c926222-fe4b065c3a8a8fd1-5944333e
> 
> .. is one of the private responses. This ...
> 
> https://troet.cafe/@Hope/112875104127109414
> 

For me these two links show an error about the items not being found.

**Comment by kr428** [comment]
> > ... is the post. This ...
> > https://loma.ml/display/4c926222-fe4b065c3a8a8fd1-5944333e
> > .. is one of the private responses. This ...
> > https://troet.cafe/@Hope/112875104127109414
> 
> For me these two links show an error about the items not being found.

Ok, now I'm completely lost. So, using a browser with which I haven't been logged in to this account before. (a) Looking at my public profile:

https://loma.ml/profile/z428

![image](https://github.com/user-attachments/assets/26d78147-83e5-4041-9e05-1b4dd635a70d)

Scrolled down a bit to see the actual post - saw these two "locked" ones visible.

Same browser, same session, same window, clicked on the timestamp for that particular post...

... to see this: Different theme, "locked" posts missing (as I would have expected):

![image](https://github.com/user-attachments/assets/873461fb-f2ef-4737-a75c-adfb7bd99f63)

What on earth...? Am I drunk? Or do I get something else completely wrong here in how this is supposed to work?

**Comment by kr428** [comment]
Any news on this...? Any way to help tracking this down? As far as I see this is still kind of broken...

**Comment by kr428** [comment]
Pinging this again. Problem seems still open even with recent RC build, see

https://loma.ml/profile/z428

vs

https://loma.ml/display/373ebf56-7167-1a36-ab71-99e682604728

in a browser that isn't logged in to this particular instance. This is a breach of security and trust for users, and in worst cases (not in this particular example) it puts users sending "private" replies to Friendica posts at risk!

**Comment by kr428** [comment]
Seems to work, thanks very much. Apparently comes with a side-effect but I'll file a new issue for that, this is not that critical.
