### ISSUE TITLE
Bluesky feed

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#13287]
### Is the feature request related to a problem? Please describe.

This is a request for an extension of the AT protocol/Bluesky addon.

### Describe the feature you'd like

I would love if the Bluesky connector would not only publish to Bluesky but would also pull the Bluesky feed into my Friendica feed. The Twitter addon used to do this, and I found it very convenient. 

### Describe alternatives you've considered

This is managed in mobile apps like Ivory, but those apps are designed to integrate Mastodon and Bluesky, and their integration of the Mastodon API does not let them work with Friendica. (e.g. Ivory and Icecubes).

### Additional context

You all rock. I love Friendica.

**Comment by MrPetovan** [comment]
Thank you for the kind words and the suggestion! Please submit this feature request to the official Friendica Addon issue tracker over at our Gitea server: https://git.friendi.ca/friendica/friendica-addons/issues/new

**Comment by annando** [comment]
Just an addition: What you describe is already coded in the "develop" branch and will be part of the next release.
