### ISSUE TITLE
Add a user-controlled remote server ignore toggle

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#13286]
This feature does:
- Hide content from ignored servers, either posted or reshared from it, from the Network feed.

I can't find the forum discussion that led me to work on this feature, if someone can find it back I'd be grateful.

**Comment by MrPetovan** [comment]
It's coming.

New contextual action:
![image](https://github.com/friendica/friendica/assets/925415/1bd62240-f9ed-4ad2-8116-a56640b12553)
User setting page WIP:
![image](https://github.com/friendica/friendica/assets/925415/54385c4f-09bb-4be2-8d65-8390d675336c)

**Comment by MrPetovan** [comment]
Final version of the settings page:
![image](https://github.com/friendica/friendica/assets/925415/8ddf1cf8-257d-4b5f-aee5-b77945734b6a)

**Comment by annando** [comment]
Having it removed from the community should be the same work like having it removed from the network page.

Also: is this only a muting of incoming posts or should this option also suppress transmitting content of this specific user to the specific server?

**Comment by MrPetovan** [comment]
It’s just a mute at the moment, only for incoming content. There’s room to expand the user server settings to implement such a block.

> Having it removed from the community should be the same work like having it removed from the network page.

What do you mean?

**Comment by annando** [comment]
Well, all pages are using the `Conversation` and `Post` class and their data is fetched by `Post::selectForUser`. So we only have to add it at these places to make it work everywhere.

**Comment by MrPetovan** [comment]
Sure, but add what exactly? Do I need to change some views? Which ones? What's the best way to do it performance-wise given the additional JOIN?

**Comment by MrPetovan** [comment]
Found the query to change in `Post::selectViewForUser`, but it isn't used in the Network module where it's using a bespoke `getItems` method that queries the `network-thread-view` view that doesn't have gsid information. Not sure where to go from there.

**Comment by MrPetovan** [comment]
The `Post::selectThreadForUser` call in `src/Module/Conversation/Community.php` uses `$uid = 0`, bypassing any filtering we could want to apply from user settings. Is there a good reason for not using the local user uid?

**Comment by annando** [comment]
I have to check how we are checking the user blocking of contacts, since this (I think) works on every level.

**Comment by MrPetovan** [comment]
I now have the Network and Display pages on lock, it's just the Global Community page now. with the question above.

**Comment by MrPetovan** [comment]
@annando One last feature I forgot about: how do I prevent notifications for posts coming from muted servers?

**Comment by annando** [comment]
Isn't this even an open issue with the blocked users? I'm unsure.

**Comment by MrPetovan** [comment]
Found the blocked contact condition in `Model/Post/UserNotification::setNotificationForUser`, I was able to add my muted server condition.

**Comment by annando** [comment]
Ah okay. I will try having a look at the PR this week, but currently I'm occupied with preparations for the move of squeet.me, which will take some time.

**Comment by MrPetovan** [comment]
Are you changing host?

**Comment by annando** [comment]
Yeah, I have to. My sponsor for squeet.me does some internal changes and cannot sponsor that system anymore.

**Comment by MrPetovan** [comment]
Good luck!

**Comment by MrPetovan** [comment]
Added a profile status mention
![image](https://github.com/friendica/friendica/assets/925415/ff5dff77-8621-434b-bd30-7fa11910732f)

**Comment by HankG** [comment]
If we are adding this for the UI then would be relatively easy to add it to the Mastodon API as well? If so that would be a huge feature. If the answer is "I think so" I can do some more research on that and try an implementation.

**Comment by annando** [comment]
AFAIK there are endpoints in the API for that. So they "only" need to be filled with life.

**Comment by MrPetovan** [comment]
Added vier support:
![image](https://github.com/friendica/friendica/assets/925415/e925341d-7ced-44e5-941e-3728f9623bb9)

![image](https://github.com/friendica/friendica/assets/925415/dc2e53d5-b348-46f5-a690-e0f8d0e7cbab)

![image](https://github.com/friendica/friendica/assets/925415/cd3348de-d98d-4168-813a-63d78c771179)
