### ISSUE TITLE
Message queue number rising

### ISSUE THREAD

**Issue by tek-aevl** [friendica/friendica#13282]
Administration - Summary
Message queues
[83](deferred) - [190982]

How do I reduce these numbers, they have been rising, Thanks, in  advance.

**Comment by tek-aevl** [comment]
these queues are now
Message queues
[89](deferred) - [180979](queue)

Message queues
[91](https://www.urbanmind.net/admin/queue/deferred) - [174499](https://www.urbanmind.net/admin/queue)

**Comment by MrPetovan** [comment]
Apparently federating with Lemmy will generate a large amount of worker tasks. Blocking the domains of large Lemmy instances might help reduce the number of pending tasks.
