### ISSUE TITLE
Correct follower numbers after Twitter addon was deprecated

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13289]
`The Twitter addon is deactivated now, since Twitter has sunsetted the 1.1 API access.` which resulted in all twitter contacts no longer showing in contacts.

However the contacts were not deleted but hidden, which does not result in changed follower numbers.

What is the plan here? Will twitter contacts be deleted in the future and if not, what would be a good way to handle this so that follower numbers are correct?

**Comment by tek-aevl** [comment]
you can manually move people that are twitter accounts to a new group to fix the numbers on your account.
I did this.

it's in https://yourdomain/group/none

**Comment by foss-** [comment]
Don't think this is possible on a user level.

**Comment by annando** [comment]
At which place there is a count that doesn't respect the active connectors?

**Comment by MrPetovan** [comment]
The main Contact page. Deactivating the Twitter addon didn’t reduce the count in the header despite Twitter contacts not appearing in the list.

**Comment by annando** [comment]
I have by now only found the circles, where we hadn't ignored the unsupported networks. From what I have seen, the contacts page does respect the unsupported networks.

**Comment by foss-** [comment]
I counted the number of accounts I am following and that are following me and both numbers matched the number of accounts listed on main contact page. Now I am unsure about this issue, but glad the hidden contacts were not correctly reflected in a different location (circles) and you managed to spot that.
