### ISSUE TITLE
[mastodon-api] Implement /api/v1/accounts/lookup endpoint

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13293]
Seen while trying to play with https://circle.grasserisen.de/ :

![image](https://github.com/friendica/friendica/assets/685879/d145515a-bf40-453c-8418-37864133c7f4)

Not a critical thing but might break other tools built on top of Mastodon API, too, while connecting to Friendica. Can this route be easily implemented?

**Comment by foss-** [comment]
There have been many fixes in regards to API support since. Is this still reproducible and if yes, could you provide exact steps.

**Comment by kr428** [comment]
> There have been many fixes in regards to API support since. Is this still reproducible and if yes, could you provide exact steps.

In the current state, this is pretty easy:

* Visit https://circle.grasserisen.de/ .
* Open your browsers dev tools (assuming desktop browser of course).
* Enter a valid handle there (feel free to use mine - @z428@loma.ml ).
* Click on the button below"

The error above will be the first one you run into, which (most likely) causes an request to be sent to 

https://loma.ml/api/v1/accounts/undefined/statuses?exclude_replies=true&exclude_reblogs=true&limit=40

(note the "undefined") which will also fail. loma.ml is on 2023.09rc up-to-date, as far as I know.

**Comment by MrPetovan** [comment]
I can confirm we know about this endpoint but is currently non implemented.
