### ISSUE TITLE
Login broken on Friendica installed via Yunohost

### ISSUE THREAD

**Issue by baslow** [friendica/friendica#13292]
Hi!
I can't be sure that this problem belongs to Friendica (rather than Yunohost) but it seemed like I should ask here.

I’ve just installed Yunohost (11.2.1) on a Linode VPS (4 GB RAM) running Debian 11. I then installed Friendica (2023.01~ynh1), apparently successfully, on friendica._mydomain.org_. Documentation indicates that, as administrator, I should be able to login using my Yunohost admin login (or email address) and password. When I attempt to do so, however, the Friendica login page takes me to https://login/ – which, of course, doesn’t exist. When I attempted to sign up for a new login (providing different login name and email address) the registration page sent me to https://friendica/.[mydomain.org](http://mydomain.org/)/register, which displayed as a blank page.

Friendica seems to be installed and running – but the login (and registration) screens don’t work. Clicking on the information icon on the login screen shows:

`This is Friendica, version 2023.01 that is running at the web location http://. The database version is 1502/1502, the post update version is 1484/1484.`

(note that it isn't picking up the web location...)

`Installed addons/apps:
ldapauth`

Yunohost installed Friendica using:

nginx 
php7.4-fpm
10.5.19-MariaDB-0+deb11u2

**Comment by sekretaerbaer** [comment]
you can't login to your Friednica instance with Yunohost admin by default. 

> For admin rights: When installation is complete, you will need to visit your domain page and **login with the admin account username and password which was entered at the time of installation process.** You can then create your profile and access the admin panel.

Did you install Friendica via the web interface? If yes then you should reinstall it from the command line with 

`sudo yunohost app install https://github.com/YunoHost-Apps/friendica_ynh/tree/master --debug`

**Comment by tobiasd** [comment]
>  When I attempt to do so, however, the Friendica login page takes me to https://login/ – which, of course, doesn’t exist.

This sounds for me, like Yunohost does something wrong setting up the URL redirections.

> This is Friendica, version 2023.01

And this should be `2023.05` not your fault ;-) but since then 3 stable releases have been released.

**Comment by baslow** [comment]
Command-line installation did the trick! Thank you!

**Comment by baslow** [comment]
Installation via the command line rather than by the Yunohost web interface seems to have made the difference. Once that was finished, Friendica showed up as a tile in the front end and clicking on it yielded a login page which worked. I signed up using the Yunohost email address and when I logged into Friendica I had admin priviliges.
