### ISSUE TITLE
"From"-Address

### ISSUE THREAD

**Issue by vaggi** [friendica/friendica#1329]
Hi,

would it be possible to allow for the "from"-address in Friendica system messages to be set from the admin settings?

**Comment by fabrixxm** [comment]
:+1:

**Comment by silke** [comment]
I'll try this one!

**Comment by annando** [comment]
And you did this one :) https://github.com/friendica/friendica/pull/1335

**Comment by silke** [comment]
Yep!

**Comment by tobiasd** [comment]
:+1:
