### ISSUE TITLE
Expand URL from Twitter

### ISSUE THREAD

**Issue by vaggi** [friendica/friendica#1330]
Hi,

one of the points of developing and using Friendica is the independence from major networks like Twitter. But apparently, when using Friendica as a network hub, links sometimes are not expanded when receiving a post from Twitter and relaying it to a follower on Diaspora. Extension of links from Twitter posts on Friendica itself works fine, though. Anyone has the same issue and an idea how to fix that?

**Comment by annando** [comment]
I need examples. The system should always expand the addresses.

**Comment by rysiekpl** [comment]
Example here: https://joindiaspora.com/posts/5508939

The link in the twitter message is `http://t.co/cmOgsOu1PD` even though the *text* of the link is deceitfully `bbc.in/1tFOMm4`

Of course that's Twitter's *modus operandi* and nobody's blaming Friendica for it; still if it were possible to make such links available *sauté*, would be great (less spying by Twitter on Friendicans, Diasporeans and other TheFederationalists).

**Comment by annando** [comment]
We have no influence on that. The tweet is embedded from Diaspora based on oembed. Not Friendica but Diaspora generates this part of the code.

**Comment by rabuzarus** [comment]
Since friendica has no influence on this behavior can this issue be closed?

**Comment by annando** [comment]
Does anyone disagree on closing this issue?
