### ISSUE TITLE
Removal/deletion of own and other contributions not possible

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13304]
- [x] I have searched open and closed issues for duplicates

### Bug Description
- Once a post has been created and sent, it cannot be removed using the "delete globally" function.
- A post from a remote instance that is displayed in the personal or public timeline cannot be removed via the "delete locally" function.

### Steps to Reproduce

1. create a contribution and send it
2. select the sent contribution and try to remove it via the function "delete globally
3. select any post from a remote instance and try to delete it using the "remove locally" function.

Actual Result:

- The self-created post is not transmitted as deleted on remote instances. The post is greyed out but not removed.
- After a refresh of the page, the post will still be displayed. The deletion or removal of the post is not successful.

Expected Result:
- The own post is deleted in the timeline and transmitted to the remote instances as deleted.
- The post from a remote instance is removed from the local timeline.

### Screenshots
Delete globally: Post display after call Delete
![grafik](https://github.com/friendica/friendica/assets/44441246/24d1aadf-b08f-4155-ad9f-43bcce908b84)
Delete globally: post display (10 min) after page update
![grafik](https://github.com/friendica/friendica/assets/44441246/ce6df138-5c19-4b41-886c-c88e858b202d)

---

Remove locally: post display 19 min after function call
![Screenshot 2023-07-25 at 17-45-48 joinfriendica Network](https://github.com/friendica/friendica/assets/44441246/9dd4e7c4-965d-4f69-82b4-27118b92b780)
Remove locally: post display (20 min) after page update
![grafik](https://github.com/friendica/friendica/assets/44441246/736172e0-cbe5-4ce7-938d-750999776575)

### Platform Info

Friendica Version: dev.

Friendica Source: git

PHP version: 8.0

SQL version: 10.5

**Comment by MrPetovan** [comment]
I can confirm, the `item/drop` calls returns error 400 on `develop`. Looking into it.
