### ISSUE TITLE
No admin email sent when registration set for open or approval

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13316]
I installed latest stable version of Friendica May 2023 on Debian 12 VPS using PHP 8.1 and NGINX as a reverse proxy in front of Apache.  I  previously made sure that both the domain name and the mail domain had a valid SSL certificate. Then registered admin with admin email. Then logged in as admin and clicked admin, Site, Registration, Registration policy set to Open. And made sure that box for Email administrators on new registration was checked. Then logged out and set up cron job. Also created log/friendica.log. 

I then successfully registered a test user. However, the email to the administrator that there was a new user was never sent. 

I then added to index.php: 
error_reporting(E_ERROR | E_WARNING | E_PARSE);
ini_set('error_log','log/friendica.log');
ini_set('log_errors','1');
ini_set('display_errors', '1');

There do not appear to be any PHP errors. 
I am using the default Frio theme and I also tried it with Registration set for Approval required. Still no emails sent to administrators when a new member registers. 

I am pretty certain that couple of months ago, these emails were being sent. But something happened that has caused these emails to no longer be sent. 

The Friendica test site is test1.reuniteamerica.net 

I have spent more than a week trying to solve this problem. Any ideas  or suggestions would be greatly appreciated.

**Comment by MrPetovan** [comment]
Are you able to receive any other email? Like the Forgot Password email?

**Comment by davidspring** [comment]
I received the reset password email both as admin reset and as a normal user reset.

**Comment by MrPetovan** [comment]
The admin email sending is based on the administrator account list, are you able to access the administration menu with the expected account?

**Comment by davidspring** [comment]
Yes. I and my admin email are shown as the administrator to this test Friendica site.

**Comment by davidspring** [comment]
To be clear, I got the initial admin email when I registered. What I am not getting is later emails when new test members register.

**Comment by MrPetovan** [comment]
Can you please run the following SQL query and paste the result:
```sql
SELECT `uid`, `parent-uid`, `blocked`, `verified`, `account_removed`, `account_expired`
FROM `user`
WHERE `email` = "<your administrator email>";
```

**Comment by davidspring** [comment]
Here is the information from all four users in the user table: No accounts were removed or expired or blocked. 
    uid: 0
    parent-uid: NULL
     
           username: System Account
                nickname: friendica
                   email: 
           register_date: 2023-07-28 19:50:06
              login_date: 0001-01-01 00:00:00
           last-activity: NULL
  verified: 1
                 blocked: 0
  uid: 2
              parent-uid: NULL
                username: David Spring
                nickname: david
                   email: david@reuniteamerica.net
           register_date: 2023-07-28 19:45:10
              login_date: 2023-07-28 23:40:44
           last-activity: 2023-07-28
   verified: 1
                 blocked: 0
 uid: 4
              parent-uid: NULL
                username: David Test2
  nickname: test2
                   email: friends@reuniteamerica.net
            register_date: 2023-07-28 19:58:20
              login_date: 0001-01-01 00:00:00
           last-activity: NULL
     verified: 1
     blocked: 0
      uid: 5
              parent-uid: NULL
                username: David Test3
                nickname: test3
                   email: springforschools@gmail.com
           register_date: 2023-07-28 20:13:55
              login_date: 0001-01-01 00:00:00
           last-activity: NULL
   verified: 1
    blocked: 0

**Comment by davidspring** [comment]
I should add that while no email is shown for the system user, I have logged in as admin and gone to Admin, Site General Information and added my admin email address to the Sender email box.

**Comment by davidspring** [comment]
I thought maybe the problem was putting Friendica on a sub domain but I just installed Friendica on a primary domain and I still have the same problem.

**Comment by MrPetovan** [comment]
So far my intuition says the problem is at the email communication stage because we haven't received widespread reports of this email not being sent, but if you received the forgotten password email it is also unlikely.

Just to be sure, what gives the following command, ran from your Friendica root folder:
```bash
bin/console config system register_notification
```

**Comment by davidspring** [comment]
The reply was 
system.register_notification => 1

Any suggestions for how I can investigate problems with the email communication stage?

**Comment by MrPetovan** [comment]
You can either log every outgoing email from your system, which varies depending on your system, or set your Friendica logger to the DEBUG level and look for the "Emailer" string.

**Comment by Raroun** [comment]
The fix for this is marked for the 2023.09 Milestone.

[https://github.com/friendica/friendica/pull/13169](https://github.com/friendica/friendica/pull/13169)

So I think its not in stable yet.

When the Parent-id of the admin account is set to 0 - the Emails should arrive on 2023.05 stable.

have a look here:

[https://friendica.opensocial.space/display/8ffdf77c-1664-70c0-e908-261313207977](https://friendica.opensocial.space/display/8ffdf77c-1664-70c0-e908-261313207977)

**Comment by davidspring** [comment]
Thank you! Your fix solved the problem on all of my sites!

**Comment by Raroun** [comment]
Credits belong to @MrPetovan.
He submitted the fix to the code.
I only figured the issue out :)
