### ISSUE TITLE
Sometimes, @mentioning does not work with non-contacts

### ISSUE THREAD

**Issue by cpfeiffer** [friendica/friendica#1331]
When you create a comment to a thread and @mention someone who is not in your contact list, you can autocomplete the name to its qualified form, i.e @user@domain.com

When previewing or posting that comment, the @mention is typically transformed to a clickable link to the user's profile page.

Sometimes, this doesn't work though, so you end up with a plain, non-clickable @user@domain.com text
And that user will not receive a mentioned-notification.

Example: Fabio's comment at https://kirgroup.com/display/235947282132341288754ca33eee7ace

**Comment by silke** [comment]
When I try to enter that specific address into my contacts search it fails, too. The error I get:

The profile address specified does not provide adequate information.
No compatible communication protocols or feeds were discovered.
An author or name was not found.
Unable to match @-style Identity Address with a known protocol or email contact.
Use mailto: in front of address to force email check.

Can this be related to the instance using dyndns?

**Comment by silke** [comment]
If there is no way to find out more, it looks like it was related to the specific configuration of that server. I propose to close the issue.

**Comment by cpfeiffer** [comment]
So you say that this does not happen anymore?

**Comment by fabrixxm** [comment]
Looks like the problem was the server not online anymore ( http://mozartweg.dyndns.org/ give me default "It works!" apache page). Closing this.
