### ISSUE TITLE
[frio] alignment in main menu isn't correct on mobile

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13312]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

In develop an "information" entry has been added to the main menu. On mobile that entry isn't correctly aligned with the other menu entries.

### Screenshots

![Screenshot_20230718-200217](https://github.com/friendica/friendica/assets/3656054/2a35d82f-53f9-4d61-ad6c-7a366386cc2f)

### Platform Info

Friendica Version:
2023.09-dev

Friendica Source: 
git

PHP version:
8.1

SQL version:
10.6 MariaDB

**Comment by MrPetovan** [comment]
The class `fa-fw` must be added to the `class` attribute in `view/theme/frio/templates/nav.tpl` on lines 281 and 414.

**Comment by AlfredSK** [comment]
Indeed. I'll do it.

**Comment by AlfredSK** [comment]
Ok. Someone is already on it.
