### ISSUE TITLE
Permissions of calendar posts

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#13334]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Creating a public calendar post is not possible, the post remains private/limited.

### Steps to Reproduce

1.  Create a calendar post.
2.  Check the box "Share event".
3.  Set the permissions to public
4. Publish the event

#### Actual Result:

The permission of the event is private.

#### Expected Result:

The permission of the event should be public.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.09-dev - 1524

Friendica Source: git

PHP version: 8.2.8

**Comment by MrPetovan** [comment]
At least it’s less a problem than the previous recent issue where private events were published publicly 😅

Nevertheless, this new behavior seems connected to the fix I provided to the aforementioned issue.

**Comment by atasingorneq** [comment]
Probably due to the wrong permissions it is currently also not possible to import the actually public events as ical into external applications. For example in the Android calendar.

**Comment by atasingorneq** [comment]
I would like to bring this issue back to the top because it is a function that I would like to use again. ;-)

**Comment by MrPetovan** [comment]
Thanks for the bump, I had forgotten about it.

**Comment by MrPetovan** [comment]
I was able to reproduce the issue on my first try, which will speed up the fix.

**Comment by atasingorneq** [comment]
I have now created an event. This event has arrived on another account on my instance, but unfortunately not on my test account on another Friendica instance and the event has not arrived on Mastodon and Diaspora either.

A normal post created afterwards (no event) was delivered correctly to everyone. Unfortunately, something is still not working properly.

[https://friendica.xyz/display/adf174d5-3565-47c4-7aca-078946508722](https://friendica.xyz/display/adf174d5-3565-47c4-7aca-078946508722)

**Comment by MrPetovan** [comment]
I'm unable to troubleshoot further, I've fixed the obvious logic bug here but the rest of the code is as-is. 😕

**Comment by annando** [comment]
@atasingorneq I just created an event. It not only is visible on my own instance:
![image](https://github.com/friendica/friendica/assets/844208/8c57097e-aaff-4a6c-a61c-bb69bcd3fbed)
but also on a different Friendica instance:
![image](https://github.com/friendica/friendica/assets/844208/568f0634-f8d8-43c6-aba7-4caf6079a053)
Also I see it on Mastodon:
![image](https://github.com/friendica/friendica/assets/844208/f96338ec-798c-4406-9cc4-c22f3b76cd36)
And Pleroma:
![image](https://github.com/friendica/friendica/assets/844208/f75647de-7216-400b-9ad5-f248f9e16332)

**Comment by atasingorneq** [comment]
I have just tried it out again. The event appears on my own instance and it also appears on Mastodon. Only on Diaspora it does not appear. I'm pretty sure that this used to work. But it works better than the last time I tested it.

**Comment by annando** [comment]
Diaspora isn't working here as well. I don't know why, since the log tells that the message was delivered successful.

**Comment by annando** [comment]
@atasingorneq Diaspora will work with PR https://github.com/friendica/friendica/pull/13701 again. From my point of view this issue appears as solved.
