### ISSUE TITLE
Possibilities to interact with others are hidden

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1334]
I "poked" a person who was trying out Friendica for the first time. The person want to poke back but couldn't figure out where to do that. The interactions with others are too hidden (contacts page -> mini menu icon).

Any ideas how we could solve this in a better way?

**Comment by rabuzarus** [comment]
Mhhh, maybe a little bit to much of restructuring of the present behavior but my thoughts to this topic.

If I would be new at friendica and I would like to interact with someone, I would look first look on someones profile-page. (So the first behavior would be like in a chat. Clicking on someones Avatar to interact.)

So my suggestion would be to make possibilities of interaction present there. I borrowed a picture of diaspora to show what I mean.
![image](https://cloud.githubusercontent.com/assets/3750381/5988862/c1ec10f8-a972-11e4-89a8-03acbd8062ab.png)

Regarding the contact page and the mini-icon, maybe it should be permanently visible, not only on mouse hover. But maybe this achieves the opposite effect.

BTW: I don't really know why but the left lower corner seems to me not the right place for the mini icon. Every time I expect it in one of the upper corners.

**Comment by tobiasd** [comment]
Another point I noticed, when following a notification to the discussion thread, the initial authors avatar picture is displayed in the sidebar with the connect button beneath it (if no connection is there ATM) but the avatar itself is not linked to the profile. I think it should.

**Comment by annando** [comment]
Is this still is an issue?

**Comment by AlfredSK** [comment]
Oh no! That brings the poking issue back to life. 👉😱👈

**Comment by tobiasd** [comment]
works now :-)
