### ISSUE TITLE
Registration mail does not include Message-ID header or id is empty

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13343]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Mail created for registration does not include `Message-ID` header or message id is empty:  `Message-ID: <>`. This leads to downscoring with spamassasian.

### Steps to Reproduce

1.  register to an instance
2.  check email for Message-Id
3.  e.g. use mail-tester.com for test

Actual Result:

mail-tester.com complains about missing Message-Id.

![grafik](https://github.com/friendica/friendica/assets/39007279/5e52b331-bf76-4cad-8a22-24a597c2def3)

Depending of the MTA used and its configuration the MTA might add a Message-ID header (which might lead to other problems). Setting the Message-ID shall be done by the sending MUA.

Expected Result:

Having a Message-ID header set.
### Platform Info

Friendica Version:  2023.05
Friendica Source: Docker image

**Comment by Raroun** [comment]
I did a Registration on my Instance with the email that mail-tester.com provided.
Looks fine in my case, but i am using an external email provider:

[https://www.mail-tester.com/test-yfujcak89&reloaded=1](https://www.mail-tester.com/test-yfujcak89&reloaded=1)

Running Friendica 2023.09-dev on PHP 8.0
