### ISSUE TITLE
Header Image

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#13355]
- [x] I have searched open and closed issues for duplicates

### Bug Description

With this entry in the `local.config.php` it should actually be possible to define an instance wide banner, which is then displayed e.g. at Mastodon.

```
        'api' => [
                // mastodon_banner (String)
                // Banner for Mastodon API
                'mastodon_banner' => '/images/banner.jpg',
        ]
```

In a profile where I have defined a banner via the API (Fedilab), this is also displayed. Only in the profiles where no banner was defined via the API, no banner is displayed, not even the default banner.

### Steps to Reproduce

1.  Define a banner in `local.config.php`
2.  Wait a little
3.  Log in to a Mastodon server and call up a profile of your Friendica instance.

#### Actual Result:

No banner will be displayed.

#### Expected Result:

The defined banner should be displayed.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.09-dev - 1524

Friendica Source: git

PHP version: 8.2.9

**Comment by MrPetovan** [comment]
This configuration value is only used at the instance level, meaning that it isn't transmitted with single profiles, only when the server information is queried:
```
GET https://dev-friendica.mrpetovan.com/api/v1/instance
```
```json
{
  "uri": "dev-friendica.mrpetovan.com",
  "title": "Friendica Social Network Dev",
  "short_description": "Additional info",
  "description": "Additional info",
  "email": "hypolite@mrpetovan.com",
  "version": "2.8.0 (compatible; Friendica 2023.09-dev)",
  "urls": {
    "streaming_api": ""
  },
  "stats": {
    "user_count": 8,
    "status_count": 78,
    "domain_count": 2211
  },
  "thumbnail": "https://dev-friendica.mrpetovan.com/images/friendica-banner.jpg",
  "languages": [
    "en-us"
  ],
  "max_toot_chars": 200000,
  "registrations": false,
  "approval_required": false,
  "invites_enabled": false,
  "contact_account": {
    ...
  },
  "rules": [
    ...
  ]
}
```
Notice the `thumbnail` field.

**Comment by MrPetovan** [comment]
I found where the information is coming for contact, it still is hardcoded here:
https://github.com/friendica/friendica/blob/2dbfb070083ec395bf5d24ec89fe96b282c6a12d/src/Model/Contact.php#L1871-L1880
I guess all I have to do is to plug the configuration value to update the image that will be returned by `/photo/header/{contact_guid}` which is provided in the accounts endpoint:
```
GET https://dev-friendica.mrpetovan.com/api/v1/accounts/hypolite
```
```json
{
    "id": "47",
    "username": "hypolite",
    "acct": "hypolite",
    "display_name": "Hypolite Petovan (dev)",
    "locked": true,
    "bot": false,
    "discoverable": false,
    "group": false,
    "created_at": "2019-05-10T01:21:40.000Z",
    "note": "Test $$",
    "url": "https://dev-friendica.mrpetovan.com/profile/hypolite",
    "avatar": "https://dev-friendica.mrpetovan.com/photo/contact/300/b5f438f2-565c-7ca1-826d-3bd124710852?ts=1650724547",
    "avatar_static": "https://dev-friendica.mrpetovan.com/photo/contact/300/b5f438f2-565c-7ca1-826d-3bd124710852?ts=1650724547&static=1",
    "header": "https://dev-friendica.mrpetovan.com/photo/header/b5f438f2-565c-7ca1-826d-3bd124710852?ts=1650724547",
    "header_static": "https://dev-friendica.mrpetovan.com/photo/header/b5f438f2-565c-7ca1-826d-3bd124710852?ts=1650724547&static=1",
    "followers_count": 5,
    "following_count": 7,
    "statuses_count": 12,
    "last_status_at": "2023-07-25T00:00:00.000Z",
    "emojis": [],
    "fields": [
        ...
    ]
}
```
