### ISSUE TITLE
adding mastodon contact via `Contacts > Add New Contact` using short-hand URLs including @ results in error message

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13359]
Searched, but couldn't find an existing issue.

Adding mastodon contact via `Contacts > Add new contact` using short-hand URLs including @ results in error message.

### Steps to Reproduce

1.  open Contacts
2.  paste mastodon URL with `@` e.g. https://mozilla.social/@mconley in `Add New Contact`
3.  click `Connect`

Actual Result:
Error message: `The network type couldn't be detected. Contact can't be added.`

Expected Result:

Contact should be added.

### Platform Info

Friendica Version: This is Friendica, version 2023.09-dev that is running at the web location https://pirati.ca. The database version is 1524/1524, the post update version is 1507/1507.

**Comment by AlfredSK** [comment]
I used diagnostics probe on a develop node:

Probing `https://mozilla.social/@mconley` -> network unknown 
Probing `mconley@mozilla.social` -> works as expected

**Comment by MrPetovan** [comment]
The profile URL that works is `https://mozilla.social/users/mconley`

**Comment by MrPetovan** [comment]
We do record the short form in the `alias` field of the contact. so I'm not sure why it doesn't work in the Add New Contact field.

**Comment by MrPetovan** [comment]
Ah, if the node doesn't already know about the user, the short form wouldn't work since it's relying on a probe and the probe fails.

**Comment by MrPetovan** [comment]
And here's the reason the probe fails:

> GET https://mozilla.social/users/mconley
> Accept: application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"

This gives the AP representation of the account.

> GET https://mozilla.social/@mconley
> Accept: application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"

This gives the HTML representation of the account.

**Comment by MrPetovan** [comment]
I found a workaround: providing the short-form URL to Webfinger returns the correct profile data, which enables us to probe these URLs normally afterwards. By skipping WebFinger query for fully-formed URLs, we've been avoiding this Mastodon feature.

Looks like optimization led us to miss the bigger picture on this one.
