### ISSUE TITLE
Frio: ignore, block and hide user not in mobile menue 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13352]
### Bug Description

In the Frio theme, the menue "more" below a post has links to "ignore", "block" or "hide" a user. 
It seems, in mobile view, these are missing. Maybe it would be possible to add them there..(?)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2023.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1524/1524 und die Post-Update-Version 1507/1507.

PHP version: 8.1.22

SQL version: Ver 15.1 Distrib 10.11.4-MariaDB

**Comment by haheute** [comment]
seems to be fixed. the links are there, in the mobile view..

**Comment by foss-** [comment]
Kudos goes out to @raroun for unifying the menu items iirc.

**Comment by haheute** [comment]
Yes, I think so, too... I think this PR: https://github.com/friendica/friendica/pull/13604
