### ISSUE TITLE
Login with Mastodon clients: source_url is null?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13353]
Linking to https://github.com/Kaiteki-Fedi/Kaiteki/issues/376 (Kaiteki) and https://github.com/trunks-social/trunks-public/issues/156 (trunks): Both are relatively new Android Mastodon clients, both quite usable in what they do, and both have in common that even login to Friendica instances fails. Not sure if it's a problem on "their" or "our" end, but maybe there's something that can be done in Friendica Mastodon API implementation to improve this?

At least in Kaiteki, the problem (in logging) seems addressed with this source_url being null in some response, see 
https://github.com/Kaiteki-Fedi/Kaiteki/issues/376#issuecomment-1560942252 and the API response of what seems https://loma.ml/api/v2/instance here. Not sure if this is the same problem in trunks though.

**Comment by kr428** [comment]
See https://github.com/Kaiteki-Fedi/Kaiteki/issues/376#issuecomment-1738194841 too. Is that something that should be in future addressed on our end?

**Comment by annando** [comment]
A summary of what to change would be nice.

**Comment by kr428** [comment]
> A summary of what to change would be nice.

In a nutshell, reading through the changes it seems they mainly made sourceUrl , videoSizeLimit, maxMediaAttachments  fields in the instance info optional. Core issue in this case was the app not even connecting because source_url being null, see https://github.com/Kaiteki-Fedi/Kaiteki/issues/376#issuecomment-1560942252 ... 🙂

**Comment by annando** [comment]
Question is, what we should enter there. Can you check that? We don't have got any of these values in our system.

**Comment by kr428** [comment]
Browsing  https://docs.joinmastodon.org/entities/Instance/, it seems all of these fields are not optional, and specifically source_url seems to have a dedicated meaning:

"The URL for the source code of the software running on this instance, in keeping with AGPL license requirements."

So maybe just a pointer to Friendicas github here...?
