### ISSUE TITLE
Fehler 1553 beim Update der Datenbank aufgetreten

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13363]
- [x] I have searched open and closed issues for duplicates

### Bug Description

```
Fehler 1553 beim Update der Datenbank aufgetreten
Cannot drop index 'gsid': needed in a foreign key constraint
ALTER IGNORE TABLE `report` MODIFY `category-id` int unsigned NOT NULL DEFAULT 1 COMMENT 'Report category, one of Entity\Report::CATEGORY_*', MODIFY `status` tinyint unsigned NOT NULL COMMENT 'Status of the report, one of Entity\Report::STATUS_*', MODIFY `resolution` tinyint unsigned COMMENT 'Resolution of the report, one of Entity\Report::RESOLUTION_*', MODIFY `created` datetime(6) NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT ''; 
Erledigt.
Ausstehende Post-Updates ausführen
```

Friendica Version: Dev

Friendica Source: git

PHP version: 8.0

SQL version: 10.5

**Comment by MrPetovan** [comment]
@annando I don't understand where does this error come from regarding the query that doesn't touch the `report.gsid` field.

**Comment by annando** [comment]
This is most likely a fragment from the moderation pull request some PRs ago.

**Comment by AlfredSK** [comment]
Just an addition: The messages are the output of the postupdate command.
The first one "cannot drop index..." is a new one. Most likely related to a very recent PR.
The second one "alter ignore table..." exists for a longer time like @annando already mentioned.

**Comment by annando** [comment]
@AlfredSK your problem is different. That is easy to solve. We just need to add the missing key for `gsid` here: https://github.com/friendica/friendica/blob/develop/static/dbstructure.config.php#L170

**Comment by loma-one** [comment]
The error has been fixed
