### ISSUE TITLE
Identifier Ignore Server Misleading?

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13369]
First of all, a big thank you for the possibility of blocking individual servers by users. This significantly reduces the pressure by META on the admins and gives users a powerful tool. Thank you very much 🙌👏🎊🎉

However, when testing the function, I was a bit puzzled. As you can see in the screenshot, the post comes from a bluesky server and is displayed in Friendica. However, the question about ignoring the server focuses on Michael and not on the domain bsky.app

![2023-08-21_20-57](https://github.com/friendica/friendica/assets/44441246/697422a7-d31b-4a95-950e-248b6146eca8)

At the time of the block, I cannot see which server I am blocking. 
Question: Wouldn't it make more sense to display bsky.app as the server to be blocked? Otherwise, it can very quickly lead to me setting locks on servers with which I actually want to continue communicating.

**Comment by MrPetovan** [comment]
We barely expose remote accounts' server name/domain, so I didn't feel that it would be relevant in this specific context. `bsky.app` doesn't show anywhere in this display, you had to add it yourself for it to show. it does show in the hovercard, but I don't think it is enough. On the other hand, mentioning "{Account}'s server" can help prevent mistakes.

**Comment by annando** [comment]
Adding the server name could help in better understanding what one is doing. And especially when you - for example - are blocking mastodon.social, you really should see this, since the impact is high.

**Comment by MrPetovan** [comment]
Sure, domain name or server name then?

**Comment by loma-one** [comment]
I Vote Domainname "mastodon.social" or "mastodon.online" etc.

**Comment by annando** [comment]
Just the hostname would be great, I think.

**Comment by MrPetovan** [comment]
Ok, I just have to figure how to retrieve it in this context.

**Comment by annando** [comment]
I suggest using the field I mentioned in the PR.

**Comment by MrPetovan** [comment]
Even if it’s potentially empty? I don’t like it 😕

**Comment by annando** [comment]
When it is empty, we cannot ignore the server anyway, since we don't know the server.

**Comment by MrPetovan** [comment]
Depends on #13368
