### ISSUE TITLE
Chat function based on ActivityPub

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13379]
### Is the feature request related to a problem? Please describe.
Just a thought
With the bridge from Friendica to Trumblr, I had to get more involved with the Tumblr software. In the process, I noticed how extremely helpful the integrated chat is when you want to quickly get in touch with a contact on Tumblr. 

I kept asking myself if ActivityPub didn't have everything on board to implement a 1:1 chat. Chat is nothing new for Friendica. It existed in the form of an addon that supported xmpp chat but was removed at some point. It's actually a shame that this addon no longer exists.

Now I read that @dansup will realise exactly that. In the form of a messanger.

https://mastodon.social/@dansup/110836811082599292
![grafik](https://github.com/friendica/friendica/assets/44441246/a50970f0-aa72-405d-8a3a-0a29955934d7)

How cool would it be if such a chat could not only be started in a messanger, but also in Friendica. In a chat window, comparable with the chat window addon for xmpp.

**Comment by loma-one** [comment]
The idea is currently no longer relevant

**Comment by annando** [comment]
@loma-one why?
