### ISSUE TITLE
WSOD when calling profile remote contact

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13370]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When a profile is called up on a remote server, a WSOD occurs.

```
2023-08-22T11:55:35Z app [ERROR]: Uncaught Exception TypeError: "Friendica\User\Settings\Repository\UserGServer::isIgnoredByUser(): Argument #2 ($gsid) must be of type int, null given, called in /var/www/html/friend/src/Module/Contact/Profile.php on line 271" at /var/www/html/friend/src/User/Settings/Repository/UserGServer.php line 105 
{"exception":"TypeError: Friendica\\User\\Settings\\Repository\\UserGServer::isIgnoredByUser(): Argument #2 ($gsid) must be of type int, null given, called in /var/www/html/friend/src/Module/Contact/Profile.php on line 271 and defined in /var/www/html/friend/src/User/Settings/Repository/UserGServer.php:105
Stack trace:
#0 /var/www/html/friend/src/Module/Contact/Profile.php(271): Friendica\\User\\Settings\\Repository\\UserGServer->isIgnoredByUser()
#1 /var/www/html/friend/src/BaseModule.php(244): Friendica\\Module\\Contact\\Profile->content()
#2 /var/www/html/friend/src/App.php(707): Friendica\\BaseModule->run()
#3 /var/www/html/friend/index.php(55): Friendica\\App->runFrontend()
#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"64e4a2373cb25","uid":"d88329","process_id":76855}
```

### Steps to Reproduce

1. Global Timeline
![grafik](https://github.com/friendica/friendica/assets/44441246/785e72a2-f6d9-4e24-988b-7da48422661d)
2. Call Profile > Conversations https://joinfriendica.de/contact/116719/conversations
![grafik](https://github.com/friendica/friendica/assets/44441246/4d5d04ee-7068-46d5-8851-1df5ff4c4a23)
3. Aufruf Profile
![grafik](https://github.com/friendica/friendica/assets/44441246/98b0914d-449d-4e54-820d-9252c95cd6a2)

### Platform Info

Friendica Version: dev

Friendica Source: git

PHP version: 8.0

SQL version: 10.5

**Comment by MrPetovan** [comment]
Thank you for your detailed report!
