### ISSUE TITLE
[Addon] Mailstream: Addon page not accessible

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13389]
- [x] I have searched open and closed issues for duplicates

### Bug Description
```
Exception thrown in /var/www/html/friend/src/Core/Renderer.php:90
Stack trace:
#0 /var/www/html/friend/addon/mailstream/mailstream.php(521): Friendica\Core\Renderer::replaceMacros()
#1 /var/www/html/friend/src/Core/Hook.php(222): mailstream_addon_settings()
#2 /var/www/html/friend/src/Module/Settings/Addons.php(62): Friendica\Core\Hook::callSingle()
#3 /var/www/html/friend/src/BaseModule.php(244): Friendica\Module\Settings\Addons->content()
#4 /var/www/html/friend/src/App.php(707): Friendica\BaseModule->run()
#5 /var/www/html/friend/index.php(55): Friendica\App->runFrontend()
#6 {main}
```
### Steps to Reproduce

Call /settings/addons

### Actual Result:

Error message above

### Platform Info

Friendica Version: dev from today

Friendica Source: Git

PHP version: 8.0

SQL version: 10.3

**Comment by MrPetovan** [comment]
There's no title to the error message?

**Comment by loma-one** [comment]
I dont understand?
![grafik](https://github.com/friendica/friendica/assets/44441246/ada0b7ca-99c1-4b40-8506-0f4236b155c8)

**Comment by MrPetovan** [comment]
What's the browser look like when you are getting the error?

**Comment by loma-one** [comment]
Does that help?
![grafik](https://github.com/friendica/friendica/assets/44441246/0faba969-2c8d-416b-b8b3-49375fd8c37a)

![grafik](https://github.com/friendica/friendica/assets/44441246/3faabbb8-919d-47a7-92d5-48f86e7464c9)

**Comment by MrPetovan** [comment]
Yes, that's what I expected, thanks!

**Comment by MrPetovan** [comment]
I'm not able to reproduce the error, please make sure that the path `/var/www/html/friend/addon/mailstream/templates/settings.tpl` exists and is readable by the web server.

**Comment by loma-one** [comment]
Very strange. Only the `mainstream.php` was in the directory.
