### ISSUE TITLE
[frio] "More" function to place a post above a post.

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13380]
### Is the feature request related to a problem? Please describe.

The "More" function for a post has received many new, great functions in the last few releases. However, it has also become much longer and more complicated to use. In some cases, the various functions can no longer be displayed in the browser (despite a diagonal of 1920x1080 or higher). The functions are outside the visible area.
![2023-08-27_09-53](https://github.com/friendica/friendica/assets/44441246/413c464c-a87e-41dd-ae8f-13dda2135b51)

### Describe the feature you'd like

It would be good if the call "More" was placed differently. In all the applications I know, this happens above a post. 
![Moor_Sandwitch](https://github.com/friendica/friendica/assets/44441246/1f8d54b9-b74e-4f06-8aa4-29a8ba3882a1)
This has the advantage that I don't have to scroll and can concentrate better on the individual functions.

**Comment by MrPetovan** [comment]
Ideally, if the list is too long, it should never clip out of the actual page. It should show above the More link instead of below. Can you scroll down the page when part of the menu shows up below the viewport?

**Comment by loma-one** [comment]
Here you can see nicely that the "Moore" function reacts in various non-beneficial ways. 

This is how it should be. The menu opens in the visible area of the browser window.
![Screenshot 2023-08-27 at 15-01-01 (1) ˈloma Network](https://github.com/friendica/friendica/assets/44441246/f5739363-f244-42b3-a99a-939809adcdc7)

Breaking out upwards
![Screenshot 2023-08-27 at 15-01-19 (1) ˈloma Network](https://github.com/friendica/friendica/assets/44441246/9532d1e9-d7b4-4cfb-9135-9caa817046ce)

Breaking out downwards
![grafik](https://github.com/friendica/friendica/assets/44441246/09f853be-5a1a-4b35-983a-62db26d433a5)

---

Scrolling down works. However, there are other menu items in the dev, which means that I have to scroll almost completely out of the relevant post and no longer have it in the viewing area.
![grafik](https://github.com/friendica/friendica/assets/44441246/294edb1e-0fd2-4997-bbb9-4f89a51b4205)

---

Here full screen prints in screen size from Dev.
![grafik](https://github.com/friendica/friendica/assets/44441246/c1b72b69-0bea-4a1e-93fc-878eb11caa0a)

There is no recognisable point at which the menu is opened upwards.
![grafik](https://github.com/friendica/friendica/assets/44441246/d020c517-c4a4-4787-827a-944ef1d39fd5)

---

Tested with Firefox, Chrome and Brave. All browsers show the same behaviour.

---

Here is another screenshot on another instance (libranet) that is not under my control.
![grafik](https://github.com/friendica/friendica/assets/44441246/e7421dc3-72f7-4438-86a1-78f7a2508cc2)

**Comment by MrPetovan** [comment]
Thanks for the detailed screenshots!
