### ISSUE TITLE
[frio] After unliking a post the thumbs up icon remains in highlight color

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13381]
### Bug Description

Once a post is liked and the thumps up icon shows in highlight color, there is no way to unlike that post.

### Steps to Reproduce

1. like a post
2. thumbs up icon gets colored in highlight color
3. click icon again to unlike

Actual Result:

The icon remains colored and it seems as if the like is not removed.

Expected Result:

Apparently the like is removed, but the UI only reflects that after a page reload it seems. So unlike is functional but that should be instantly be reflected in the UI.

Reproduced on squeet me and pirati ca.

**Comment by mr-eshua** [comment]
Seems like we have the same issue with our friendica instance recently updated to 2023.05. Like/Unlike is happening, it seems, underlyingly, but the status of your like (if you liked it or not) under the post does not appear, only after the page reloading.

**Comment by foss-** [comment]
This works as expected in `This is Friendica, version 2023.09-rc that is running at the web location https://pirati.ca. The database version is 1542/1541, the post update version is 1507/1507.`

UI is slow, but that is known and expected in current state.

There is a follow-up problem: https://github.com/friendica/friendica/issues/13735
