### ISSUE TITLE
Move Network into channels view

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13398]
**Currently**

The new channels (https://github.com/friendica/friendica/pull/13390) are a great addition. However the top icon menu is getting rather crowded and overwhelming.

**Expected**

One way to at least keep the same number of icons would be to simply move `Network` to channels.

That brings up the question where the sorting options should go. I believe users are not switching sorting options very often so maybe the sorting options could go into a new `Timeline Settings`.

**Comment by haheute** [comment]
I use /network more often than the channels. At least until now.. Mostly latest activity and latest received..

**Comment by foss-** [comment]
Well due to the fact, channels haven't yet been released, we all used network more often than channels. I understand you are on dev and refer to your testing experience.

However, even considering your statement, using network more often wouldn't affect your usage if network was just another channel. This is merely a question of providing an easy to use structure and not overwhelm users with too many options which friendica has quite the track record of tending to do, due to lack of frontend devlopers.

@haheute can you share how frequently you change between the different network view options?

**Comment by haheute** [comment]
Mostly I use "latest received" and maybe 1-10 times per day I look into "latest activity". Mainly when "latest received" has nothing new to show and it is a little bit boring...

**Comment by annando** [comment]
I'm currently thinking about some configuration, where you can see some channels at the network page. Let's see what I can do in the next few days.

**Comment by tobiasd** [comment]
I think it makes sense to include the channels into the existing network page and let users choose which ... say max 4 types of sorting (for space reasons) they would like to see for their network stream.

**Comment by foss-** [comment]
Channels have moved to a box on the left side panel of the timeline. Closing.

![1](https://github.com/friendica/friendica/assets/5708172/2c32b369-f751-4e5f-977a-9792d993fda0)
