### ISSUE TITLE
Inconsistent URL generation again

### ISSUE THREAD

**Issue by esackbauer** [friendica/friendica#1341]
Issue #1190 is again there.

Still wrong links left or again the same bug: Ampersand instead of question mark.
(tested with Friendica 3.3.2 - 1175):

After clicking for next page of contacts:
https://friendica.site.net/contacts&page=2

After clicking "older" on the bottom of Pinnwand page:
https://friendica.site.net/profile/user&page=2

**Comment by ddorian1** [comment]
Should have been fixed by #1366

**Comment by annando** [comment]
Can someone check if its fixed?

**Comment by annando** [comment]
It's working for me, I'm closing it now.
