### ISSUE TITLE
Do not include preview when using [url] tag 

### ISSUE THREAD

**Issue by schmaker** [friendica/friendica#13439]
I know it's corner case, but I do think my post should not include preview when linking to self with [url] tag.

The reason i do this is to make people from Mastodon to reach my server, so they could read the post in the same manner they would with blogpost (as Mastodon attaches images at the end of the post instead inline).

There are 2 thing i would like you to consider, not sure which is better globally:
 - use [url] tag only for linking and no previews are being generated (use [share] tag for this instead?)
 - disable previews for [url] tag when linking to same post it links from

See attached problematic post in this link - i get post content and then i get whole post content again included as "preview"
(https://schmaker.eu/display/c83e3896-1564-faca-2018-bd4839736244)

Friendica 2023.05

**Comment by MrPetovan** [comment]
How do you include a link to itself in your posts? Through editing after initial publication?

**Comment by schmaker** [comment]
Exactly. There is afaik no other way to find out URL before posting

**Comment by annando** [comment]
Adding a link to a post will attach the other post, since this is the way, quoted posts work. If you want that people especially from visit your system to view the message, then create messages with titles. These messages are transmitted as "article", which means that Mastodon then only displays the title and the link to the post.

**Comment by schmaker** [comment]
I understand what you are saying and as I said - it's corner case. 

Anyways, I can image more use cases when you do **not** want to create thumbnail/post preview.
 - linking to more posts creating some sort of index of them 
 - linking to potentionally problematic or NSFW content

I think it should be up to user, if he wants Friendica to create thumbnail (use [share] then) or not (use [url] then)

Anyways, that's up to you guys, consider and feel free to close this :)

**Comment by MrPetovan** [comment]
Another case is Wordpress AP posts that have a link t the original source, which ends up duplicating the content, see these examples:
- https://friendica.mrpetovan.com/display/0370d486-91b14afb107d4336-5ad64544
- https://friendica.mrpetovan.com/display/8e8c5502-b3ecdacac09d8ddb-5d5f214c

We really should compare the links inside the body to the plink of the post before linking them, creating the preview.

**Comment by MrPetovan** [comment]
Another example, still from Wordpress: https://friendica.mrpetovan.com/display/8e8c5502-bce5fcf629ae90bb-4121cd33

**Comment by MrPetovan** [comment]
Fixed in #13465
