### ISSUE TITLE
[BlueSky] slow synchronisation after changing login data

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13443]
I use three Friendica accounts to test the bridge with BlueSky.
Since I only received new invite codes gradually, all three accounts were running with the same login data from BlueSky.

After creating the additional BlueSky accounts, I gradually changed the login data to Friendica. Each test account now has its own login data. At that point, contacts were already imported and posts in the timeline.
It seems that by changing the login data I had upset the connector.

### The problems:
all three accounts cannot send posts with pictures.
Synchronising contacts doesn't seem to work as there is a conflict with the existing contacts.
Importing posts sometimes has a delay of up to 7 days.

### Question:
How can I reset the BlueSky Connector to remove all contacts and shorten the synchronisation time?

Deleting the login data seems to have no effect. The contacts cannot be removed manually
Temporarily switching off the connector has no effect on the connection.

**Comment by annando** [comment]
Please have got a look at the log. There should be entries with "bluesky.php".

**Comment by loma-one** [comment]
no notice

---
Another important addition:
Instance 1 runs on stable = 1 account
Instance 2 runs on dev. = 2 accounts

**Comment by loma-one** [comment]
It runs very well in production. The problem only affects a very small test instance. Therefore closed here

**Comment by loma-one** [comment]
The problem has been solved. The reason was that the daemon was started via systemd. This does not seem to work in conjunction with Bluesky.
