### ISSUE TITLE
Alt-Text of received images not displayed on mobile in Friendica

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13440]
- [ x] I have searched open and closed issues for duplicates

Disclaimer: I'm on mobile at the moment. Well check later how it works with a desktop system. Edit: With desktop systems it works as exprcted.

### Bug Description

When I create a post with an image on Misskey or Mastodon I can add alt-text to the image. The alt-text is working between Misskey and Mastodon, but not with Friendica. No alt-text is displayed in Friendica on mobile devices.

### Steps to Reproduce

1.  Create an image post on Misskey or Mastodon, add alt-text to the image
2.  Check the federation of the alt-text on Misskey and Mastodon. Works!
3.  Check the federation of the alt-text on Friendica. Alt-Text is missing when using mobile devices.

Actual Result: No alt-text displayed in Friendica for imported images from Mastodon and Misskey.

Expected Result: Alt-Text should exist for received images.

### Platform Info

Friendica Version: 2023.09-dev

Friendica Source: git

PHP version: PHP 8.1

SQL version: MariaDB 10.6

Browser: Firefox on Android

**Comment by MrPetovan** [comment]
Do you happen to have a copy of the same post on both Mastodon and Misskey to figure out what they do differently?

**Comment by AlfredSK** [comment]
Examples: 

https://misskey.de/notes/9jfvmozl39
https://mastodon.social/@steffen@misskey.de/111036416828065006 (*1)
https://libranet.de/display/c7f7fa91-019721addd051921-ef2cb2cd

https://mastodon.social/@libranet/111039857004012116
https://misskey.de/notes/9jgqvtrsjj
https://libranet.de/display/52acf9cd-e99534c2adad17c6-79a04972

(*1) I have no idea how to get a local link to a remote post on Mastodon. 🤷

**Comment by MrPetovan** [comment]
I don't think Mastodon provides a deep link to remote posts like Friendica does.

**Comment by MrPetovan** [comment]
How do you check the alt-text on your mobile device? I've tried checking it using iOS Safari and it's a fail on all accounts.

On MissKey, pressing long on the image just grabs it for drag and drop, no alt-text shows.

<img width="375" alt="image" src="https://github.com/friendica/friendica/assets/925415/4f2e2a86-4210-4140-b0af-1f908e2ac8ef">

On Mastodon, the regular image action prompt shows but no alt-text. That’s where I expect it to show:
<img width="375" alt="image" src="https://github.com/friendica/friendica/assets/925415/c2ec363f-783b-46be-9182-ed6ac2fa1acc">

Same behavior on Friendica if the lightbox isn’t active:
![IMG_5824](https://github.com/friendica/friendica/assets/925415/456307dc-b2bc-4f67-a201-cd4efad3454e)

**Comment by AlfredSK** [comment]
On the other platforms there is a small [ALT] button on the image. Misskey: Press ALT button. Text is displayed below the image. Mastodon: Press ALT button. No alt-text. :-/ Then long-press image -> alt-text is displayed in a browser context menu window (weird).

Misskey:

![Screenshot_20230911-180120](https://github.com/friendica/friendica/assets/3656054/891c0b6b-b0d3-4e25-b0ae-0521c63b7dac)

Mastodon:

![Screenshot_20230911-180053](https://github.com/friendica/friendica/assets/3656054/6c5785e4-7e18-44e1-be95-6482373a4f91)

**Comment by AlfredSK** [comment]
TBH, I prefer the misskey way. :-)

**Comment by MrPetovan** [comment]
Got it. I thought it had to do with our markup but the MissKey display is bespoke. Maybe we can have the same lightbox/carousel system.

**Comment by MrPetovan** [comment]
I found the lightbox Misskey is using: https://photoswipe.com

Let's see if I can integrate it to our code once #13476 is merged as it will necessarily conflict with it.

**Comment by MrPetovan** [comment]
Closed by #13522
