### ISSUE TITLE
Friendica can't display this page at the moment, please contact the administrator in Caddy

### ISSUE THREAD

**Issue by Kyouma960** [friendica/friendica#13452]
[ :heavy_check_mark: ] I have searched open and closed issues for duplicates

### Bug Description

Installing friendica in caddy results in error:
 `Friendica can't display this page at the moment, please contact the administrator.`
### Steps to Reproduce
Caddyfile:

```bash
friendica.server.xyz {
	@not_file {
        file {
            try_files {path} /index.php
        }
    }
	php_fastcgi unix//run/php/php7.3-fpm.sock
	rewrite @not_file /index.php?q={path}&{query}	
	root * /opt/friendica
	log {
        output file /var/log/caddy/friendica.log
    }
	file_server
}
```

steps:
```bash
#installed dependencies listed in the wiki.
sudo mysql_secure_installation
CREATE DATABASE friendicadb;
CREATE USER 'friendica'@'localhost' IDENTIFIED BY '<password>';
GRANT ALL ON friendicadb.* TO 'friendica'@'localhost';
FLUSH PRIVILEGES;
EXIT;
```
cloned repo
```bash
bin/composer.phar install --no-dev
```
installed addons 
```
mkdir -p view/smarty3
chmod 775 view/smarty3
```

restarted caddy.

### Platform Info
debian 10
Friendica Version: stable https://github.com/friendica/friendica.git -b stable html

Friendica Source: 

PHP version: 7.3.31

mySQL version: Ver 15.1 Distrib [10.3.39-MariaDB](url)

**Comment by MrPetovan** [comment]
Thank you for the report, when this message is displayed a related log message is written, have you configured your Friendica log yet?

If not, you can do it from the command-line with these handy commands:
```
$ bin/console config system debugging 1
$ bin/console config system loglevel error
$ bin/console config system logfile log/friendica.log
```
The log file will be available in the `log/friendica.log` path of your Friendica install if it's writable by the web server user.

**Comment by doskel** [comment]
hey there! sorry to drag this issue out of the grave, but i'm having the same issue; i've got the commands run and all, but there's zero output in any of the friendica log files
i've checked all the php and caddy logfiles and they say it's a 503 but i have no idea why
any help?
