### ISSUE TITLE
Frio: Link to Source button to open in a new tab

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#13457]
### Is the feature request related to a problem? Please describe.

I'm always frustrated when clicking the link to source button (top right on a post), finding myself navigating away from my network page and then subsequently having to navigate back again.

### Describe the feature you'd like

I would like to the Link to Source open in a new tap that I can close swiftly close when done and  thereby speedily return to  my network page without having to wait for it to fully reload.

**Comment by FarisKarim** [comment]
hey i can work on this

**Comment by Raroun** [comment]
@AndyHee 
This Issue can be closed. 
PR #13480 resolved this issue.

**Comment by AndyHee** [comment]
Thanks @Raroun
