### ISSUE TITLE
emoji_activities setting in database table "config" always returns "true"

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#13458]
- [X] I have searched open and closed issues for duplicates

### Bug Description

emoji activities are always `true` if that value is present in the database table `config`.
Once the value is set, you can only deactivate them by deleting the row in the database.

### Steps to Reproduce

1.  ./bin/console config system emoji_activities false
2. check table` config` you can see the value is now `false`
3.  check and see that emojie_activities are now rendered as true in` conversations.php` and on friendica network page (and elsewhere)

Actual Result:

no matter what value is set in emoji_Activities -  friendica behaves like it is `true`
you can only got back to `emoji_activities = false` if you delete that row in the database

Expected Result:

being able to turn off emoji_Activities without manually deleting a row in the database.

### Platform Info

Friendica Version: 2023.09-dev latest commit

PHP version: 8.2

SQL version: 10.5

**Comment by MrPetovan** [comment]
“false” is a string that will be interpreted as a truthy value by PHP. Please use 0 (zero) instead when disabling a configuration value from the command line.
