### ISSUE TITLE
[frio] Render placeholders for embedded images to prevent timeline from jumping around

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13455]
Sometimes, in timelines heavy with images (and network connections that are a bit slower), Friendica in "frio" theme will load posts first and then apparently populate them with images if there are any to display. Though this works reasonably well, it's a bit annoying at times: In example, while adding a comment somewhere in the page, reloading and displaying images above will almost immediately lead to your page "jumping" and you losing track of where you were actually typing. Not a real bug, merely an inconvenience; maybe it would be possible to pre-render placeholders for images to be loaded beforehand in order to avoid this behaviour?

**Comment by MrPetovan** [comment]
It's a good idea, but it's tricky in our case. We would need to know the dimensions of the images of a post, something we don't have in the BBCode themselves.

**Comment by kr428** [comment]
Maybe then all along with a setting to always display images in a fixed size in a timeline and only show a full view on clicking "something"? As far as I see, this functionality's already there if pictures exceed a certain height or if there are multiple pictures in sequence added to a particular post?

**Comment by annando** [comment]
@MrPetovan The `post-media` table does contain this information. That table also contains the corresponding blurhash. This means that technically it could be possible to create a blurry preload picture that is then replaced by the real one. Only thing is: I don't know how to do it.

**Comment by MrPetovan** [comment]
Like I said, you need the dimensions in advance, which we don't have in the BBCode text. Other platforms can do it because they don't have inline images so they can fetch the image data (including dimensions) separately from the post body. So we would have to have the dimensions provided in the `[img]` BBCode, but it's already crowded and we don't have support for arbitrary attributes.

**Comment by annando** [comment]
No, we have all the data at hand. Have got a look here: https://github.com/friendica/friendica/blob/develop/src/Model/Item.php#L3298

At that place we are creating the code for the gallery. There we have all the data at hand. The gallery is used everywhere, also at inline images.

**Comment by MrPetovan** [comment]
Cool, what about inline images? They may not be the most frequent case but they are a case of images taking space in the timeline all of a sudden.

**Comment by annando** [comment]
That functionality does cover all kind of images. I guess that we only have to find the best place - and the best way of doing these previews. But I guess that it just needs to be done. We could even do this with avatar images as well.

**Comment by MrPetovan** [comment]
Thanks to your pointers et some black magic, vertical space is now allocated for almost all images included in the timeline. The only remaining stragglers are the images in the link previews for which we don't seem to have dimensions.

**Comment by annando** [comment]
The dimensions for the link preview are in the table `post-media`. They have got the `type` 17. But there is some other magic somewhere in the code, where we decide upon the width and height that we want to display.

**Comment by MrPetovan** [comment]
This is the data we have at hand when rendering link previews:
```
array (size=12)
  'after' => string '' (length=0)
  'author_name' => string 'Euronews' (length=8)
  'author_url' => string '' (length=0)
  'description' => string '' (length=0)
  'image' => string 'https://dev-friendica.mrpetovan.com/photo/preview/600/32834' (length=59)
  'preview' => string '' (length=0)
  'provider_name' => string 'Euronews.com' (length=12)
  'provider_url' => string 'https://de.euronews.com/' (length=24)
  'text' => string '' (length=0)
  'title' => string 'National Rejoin March: Brexit-Gegner wollen zurück in die EU' (length=61)
  'type' => string 'link' (length=4)
  'url' => string 'https://de.euronews.com/2023/09/23/national-rejoin-march-brexit-gegner-wollen-zuruck-in-die-eu?utm_term=Autofeed&utm_medium=Social&utm_source=Twitter#Echobox=1695481010' (length=168)
```
I'd rather not try to extract the `post-media.id` from the `image` property.

**Comment by MrPetovan** [comment]
Per #13467 we don't actually have reliable dimensions data for images, so my solution cannot work, I'll pull it back. It also stunts my horizontal masonry gallery which will have to be pulled as well.

**Comment by MrPetovan** [comment]
> This means that technically it could be possible to create a blurry preload picture that is then replaced by the real one.

I actually explored this idea, but it ended up loading both the preloading image and the image itself at the same time, which negated the benefit of having a preload image. For this I implemented an additional `/photo` endpoint that outputs the blurhash image of a given `post-media.id` which proved pretty slow. It may be faster by providing the blurhash string as a query parameter instead of hitting the database but there is a possible parameter length issue and we would still have to download tens of kilobytes of data for larger images, not too far from the preview image we should be creating for the same images.

**Comment by annando** [comment]
Wouldn't it be possible, to calculate the blurhash picture in JS on the client side, while in parallel fetching the image from the server?

**Comment by MrPetovan** [comment]
Yes but in practice I feel like it isn’t a big enough improvement over having a static placeholder to have yet another Javascript dependency.

**Comment by kr428** [comment]
In Frio on mobile devices at least (couldn't so far check on a desktop), there's a huge empty space below each image. Is this a side-effect of that change...?
![Screenshot_20231014-075422_Brave](https://github.com/friendica/friendica/assets/685879/6416ab7e-c238-44bc-99de-b10f049a7023)

**Comment by AlfredSK** [comment]
Please clear your browser cache.

**Comment by kr428** [comment]
> Please clear your browser cache.

Ah ok. Seems to work, thanks.
