### ISSUE TITLE
Group atom feeds don't have any posts

### ISSUE THREAD

**Issue by snan** [friendica/friendica#13471]
Group atom feeds, [such as this one](https://venera.social/dfrn_poll/activitypubblueskybridge), don't have any posts. This is similar to Mastodon where boosts don't show up in RSS (which is appropriate for a microblog, I guess, I don't know) but it's unlike kbin and Lemmy where they do (since that's the whole point of a group feed).

**Comment by tobiasd** [comment]
They should have, and [for the support group](https://forum.friendi.ca/feed/helpers) it is working.

**Comment by annando** [comment]
The system https://venera.social is running 2023.05, while https://forum.friendi.ca runs with 2023.09-rc. I guess that we have fixed it in the meantime.
