### ISSUE TITLE
image upload failing without error or info about file size limit

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13474]
### Currently

When uploading an image with 557 KB (not the image in the screencast), the upload briefly shows the image then closes and goes back to the post composer view.

### Steps to Reproduce

1.  create new post
2.  drag large image into upload area

Actual Result:

The uploaded image briefly shows. When hovering the image with the mouse there is a red speech bubble below the image, but no text is visible. Then the image vanishes and users find themselves back in the compose box.

Expected Result:

Image should either be uploaded and added to the post or if there is a problem, inform users about the problem, so they know why the action they are trying to use is not working.

### Screencast

https://github.com/friendica/friendica/assets/5708172/05694248-aaae-44ad-abb6-28eca0a63fb4

### Version info

This is Friendica, version 2023.09-dev that is running at the web location https://squeet.me. The database version is 1532/1532, the post update version is 1507/1507.

**Comment by annando** [comment]
Seems to be some configuration problem with the server. But I just checked, the PHP upload size is set to 2M, so it has to be something else.

**Comment by xundeenergie** [comment]
I have this settings on my friendica:
![grafik](https://github.com/friendica/friendica/assets/5894829/f2ca027b-cebc-45fc-992d-f9ec7d710318)

In `/etc/php/8.2/fpm/php.ini` is set `post_max_size = 1G` and `upload_max_filesize = 1G`

Did you check all these settings on your server?

**Comment by xundeenergie** [comment]
> Seems to be some configuration problem with the server. But I just checked, the PHP upload size is set to 2M, so it has to be something else.

The uploaded file in the video is about 7.8MB... if i saw this right...

**Comment by foss-** [comment]
Right, I wanted to ensure to trigger the error. Later I wanted to ensure the upload works but the upload still failed with a file size at around 550 kb.

This issue is twofold:

- one: understand why image upload even below the set threshold fails on squeet.me
- two: if upload fails (for whatever reason, either image size or server issues), don't fail without showing an error message to the user

**Comment by xundeenergie** [comment]
if the upload fails, you see the preview-image with an "X" symbol.
if it was ok, you see a checkmark on the preview...

**Comment by foss-** [comment]
> if the upload fails, you see the preview-image with an "X" symbol. if it was ok, you see a checkmark on the preview...

Not sure I understand, what you are trying to indicate. The UI seen is documented in the report. Do you mean the light x in the middle indicates a failed upload. Maybe so, but what does the red cut off speech bubble below the image indicate?

If the upload failed, why not inform the user about that, ideally along with the reason for the failure?

**Comment by xundeenergie** [comment]
Yes, the light "X" indicates a failure. 
The red bubble... i have to have a look... but you should be able to scroll down to read it.

There should also be a notification (white characters on black bubble) right above with information if upload or network failed.

**Comment by foss-** [comment]
Image upload is working fine on squeet me now. Closing.
