### ISSUE TITLE
Load notifications-update before whole site is loaded

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#13486]
### Is the feature request related to a problem? Please describe.

When i open a timeline, it takes sometimes a long time to load all images. Sometimes some images run into a timeout on loading.
And i have to wait for updating the notification-area, until all images are loaded.
This is sometimes very annoying, if some servers are not reachable.

### Describe the feature you'd like

Just load notifications after first navbar was loaded.

### Describe alternatives you've considered

thats all. :)

### Additional context

**Comment by MrPetovan** [comment]
It looks like this could be easily solved by adding the `loading="lazy"` attribute to all the post images. Interestingly enough, this feature is disabled when Javascript is also disabled, to prevent tracking across a webpage with strategically placed image tags.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading

**Comment by FarisKarim** [comment]
hi i would like to be assigned this

**Comment by MrPetovan** [comment]
Sure, let us know if you have any questions!
