### ISSUE TITLE
Vier: "Remember me" button is unusable as it's hidden

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1348]
The following screenshot was taken from the Vier theme using the "breathe" style. The "remember me" button can't be used like this. (You can see a tiny part of it under the password field.)

 * check if it's the theme Vier or the style breathe
 * fix it

![hidden_remember_me](https://cloud.githubusercontent.com/assets/1151403/6017828/1f3f943e-ab92-11e4-95be-a1cd0c7a1f3a.png)

**Comment by silke** [comment]
This doesn't occur in Chromium, but in Firefox. The width of the input filed is max 400px. Which somehow makes the slide thingy appear which then hides the checkbox.

**Comment by Beanow** [comment]
I noticed this as well. Seems to be a linux firefox thing.

**Comment by tobiasd** [comment]
Just had a look with FF37 on linux, no scrollbars even with a small window size. Is this still an issue for you?

**Comment by tobiasd** [comment]
is this still an issue?

**Comment by tobiasd** [comment]
yes it is, on smaller screens the side panel is *too narrow*

**Comment by silke** [comment]
Hm. We are not sure why sometimes the login section ends up in the sidebar of home.html. And in other cases it does not (it ends up underneath the text of home.html).

**Comment by tobiasd** [comment]
A fix for this is merged in the develop branch. Could someone test if it is working?

**Comment by tobiasd** [comment]
looks ok for me on the small screen of the eeePC on the node of @silke so I'm closing this issue
