### ISSUE TITLE
Add help text to explain the options for approving contacts

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1349]
This question came up on Friendica support: "When getting a contact request from diaspora, there is an option "Approve as:" which can be set to "Friend" or "Sharer". What is this for?"

The answer should be added as an inline help text. Quoting heluecht from support forum: ""Friend" means that you want to read the posts from this contact as well. "Sharer" means that you allow the other to read your stuff but you aren't interested in what this person writes."

**Comment by Beanow** [comment]
A single paragraph of text, plus some `tile=""` tooltips would work for this I think.

**Comment by silke** [comment]
@Beanow I don't understand you. What would be the difference compared to my suggestion in the commit?

**Comment by fabrixxm** [comment]
@silke, to me your patch is ok. The only thing is that in case of a Diaspora contact, the `$as_fan` would be "Sharer" and not "Fan/Admirer", so the help text should be adjusted correctly

**Comment by silke** [comment]
Ok, @fabrixxm if you can wait until 10:30/11:00 a.m. today, I'll change that.

**Comment by fabrixxm** [comment]
Ok, but not a minute more :-P

**Comment by silke** [comment]
Will be solved with pull request #1463
