### ISSUE TITLE
padding-bottom in timeline sometimes way to high

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#13496]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

On some pictures the "padding-bottom" is way to high. Not on all images, but on some.

### Steps to Reproduce

1.  view timeline or
2.  open posting with image
 
Actual Result:

Beneath the image is a big blank area.

Expected Result:

padding-bottom should be the same as on all other images.

### Screenshots

![grafik](https://github.com/friendica/friendica/assets/5894829/533c4aa4-96fd-4c37-b1bb-5ec82d8dcbcf)

### Platform Info

Friendica Version:

develop

Friendica Source: 

PHP version:  8.2

SQL version:

**Comment by Raroun** [comment]
i noticed this also:

https://github.com/friendica/friendica/pull/13476#issuecomment-1746629307

**Comment by MrPetovan** [comment]
Thank you for your vigilance, please clear your browser cache.

**Comment by xundeenergie** [comment]
I clear my browser-cache on every closing the browser automatically.

and i recognize this on firefox on linux and android.

This is on chrome (in timeline)
![grafik](https://github.com/friendica/friendica/assets/5894829/85c7ae10-918e-4246-8617-487cf5ca1ccc)

also on chrome (in timeline)
![grafik](https://github.com/friendica/friendica/assets/5894829/114b5a42-cf5c-48ea-b845-17770e5f02dd)

in firefox this two postings are ok now... 
hmmm. it's interesting.

**Comment by xundeenergie** [comment]
The second posting in firefox
![grafik](https://github.com/friendica/friendica/assets/5894829/80ea4881-bd59-477c-8af5-68ebe73adaa0)

**Comment by MrPetovan** [comment]
I'm not sure what to say to you, I tested the feature on a Chrome-based browser, so I still believe it's a browser cache issue.

**Comment by annando** [comment]
For me a "force reload" cleared the problem.

**Comment by AlfredSK** [comment]
A forced reload (Shift+Reload) solved it for me, too. Firefox on Android can be tricky sometimes. The last time I had to clear the cache twice and force Android to close the app.

**Comment by xundeenergie** [comment]
Hmmm.. it seems, the force reload solved it really...

But this behaviozr startet 4 weeks ago first time on all my devices... the same time.

**Comment by AlfredSK** [comment]
There was another PR for the same issue. That one has been reversed later because of some fatal errors. Now we have a new/better PR that solves the issue. So you had the chance of getting the CSS cache problem twice. ☺️

**Comment by MrPetovan** [comment]
Stale cache issue confirmed, closing here.

**Comment by xundeenergie** [comment]
I found a possible reason for that.

I have an own css (threadview, you know). And i tried to fit bigger images into the screen, adding `max-height: 75vh;` to img-tags.

When i do this, images with a taller height than my current screen show this behaviour.
When i remove this style from img i have no padding below and next to the img.

But i have no chance to reduce the size of the surrounding figure-tag... it has `padding: 177.777%` set, in case of a function in php which calculates this from `100*(height/width)`
I calculated the same value from the images dimensions.

And i fon't know why you do this in this way, but it prevents images to fit into viewport/screen...

**Comment by MrPetovan** [comment]
We do it this way now because it reserves space on the page for each image we know the dimensions of in advance. This prevents the page from resizing itself once the image is effectively loaded.

**Comment by xundeenergie** [comment]
ok.
i found the problematic keys... 

If an image or a video i higher than the vertical view in my browser, it does gives problem.
scrolling through an image is ok, or tip to view it with fancybox.

But a video, higher than the space between the second navbars bottom and the bottom of the browser is not funny to watch.
This is especially a problem of smartphon/tablet view.

That is, why i inserted in my theme-specific custom-css this

```
audio, canvas, progress, video, img {
        max-height: 75vh;
}
```
So the max vertical height of an image and video is set to i can always see the full height of a video or image.
But the figure-tag around gets much bigger on smaller screens. I tried it in my firefox on laptop with developer-tools an set it to another device-size.

But i did not found a good solution, that the dimensions of the "figure"-tab go with the size of the device/browser.

css-hell

**Comment by MrPetovan** [comment]
Native video players have a button to go full screen which would prevent the video from being taller than the screen.
