### ISSUE TITLE
[Frio] Suggestion to place the new "Reply to" function at Favicon

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13524]
First of all, thank you for this wonderful and very useful feature "in reply to".
However, I would like to suggest that the function be placed somewhere else, because

1. the number of references to a normal post or a reaction to a post keeps increasing.
2. the clarity suffers as a result
3. I, as a user, am overwhelmed by the classification of this information.

I have looked at how Bluesky, for example, do it. Here, the jump mark is placed discreetly next to the user's favicon.

![grafik](https://github.com/friendica/friendica/assets/44441246/e81396e3-8000-450f-91ce-fe2b54a12033)

![grafik](https://github.com/friendica/friendica/assets/44441246/1fcc2b2c-dc18-4efe-bd2d-c296edeaf5e0)

Since a reference and information within a thread and the sharing of a post are two fundamentally different pieces of information, it would, in my view, be more comprehensible for the user if the sharing continues to be above a post and the link mark to a content moves to the user favicon as a personal reference.

![grafik](https://github.com/friendica/friendica/assets/44441246/18f61542-c2ac-4b2f-a1e7-267e749e14b4)

**Comment by MrPetovan** [comment]
Paging @xundeenergie

**Comment by xundeenergie** [comment]
I had it in the first tries on exactly this position, you suggest... 

But it was not very handy on smartphones... i have big fingers... and i beliefe, webdevelopers should all have big fingers!!

Maybe it's an idea to have the parent-link on smartphones above and on wide-screens next to the avatar.... i will try it.

**Comment by xundeenergie** [comment]
Now i made it flip on small screens above the posting

On small (smartphone) screens:

![grafik](https://github.com/friendica/friendica/assets/5894829/7562bf6a-64b8-4583-8546-d1bdae6c5ba8)

On small-medium screens

![grafik](https://github.com/friendica/friendica/assets/5894829/a291798f-78f0-4983-aec6-82cef2852882)


and on wider screens under the username

![grafik](https://github.com/friendica/friendica/assets/5894829/46daca48-c711-4b12-82c5-75b439fc139f)


I can touch it without problem with my fingers. :)

And i put a nice icon (fa-reply) on the beginning.

**Comment by annando** [comment]
Can you reduce the font size of the resharing information part to the size of the date information? Having it the same size as the account name, it is too much in the focus.

**Comment by annando** [comment]
@xundeenergie BTW: I think that it looks fine as a dedicated line below the date:
![image](https://github.com/friendica/friendica/assets/844208/b5df323f-0785-4195-b1ab-b70bacb950e3)

**Comment by xundeenergie** [comment]
I did it in this way now with the last commit:

On wide-screen
![image](https://github.com/friendica/friendica/assets/5894829/3145118c-1b98-445f-b293-65575bc6b4e7)


on middle screen
![image](https://github.com/friendica/friendica/assets/5894829/cd071f6d-e94e-4351-84de-83be2a6be8cd)

and on smartphone-screen 
![image](https://github.com/friendica/friendica/assets/5894829/73e87926-e2b2-49d5-bbbf-2beeb1ae668d)

**Comment by MrPetovan** [comment]
Closed by #13527
