### ISSUE TITLE
Chat messages from Firefisch are fragmented into

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13535]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I don't know if this is actually a bug. Therefore, feel free to categorise it differently if this is a mistake from me.

 - A chat with remote users can be started from Firefish. This is an @ addressed, private message that can be sent to a confirmed contact.
 - The receipt of the message is displayed on Friendica in the personal timeline. 
 - A reply can be created on Friendica and sent to Firefish.
 - The message and replies are displayed on Firefish in a thread (image 1)
 - If a new question is created and sent from Firefish, Friendica will not create a link between the first and the new message.
 - The new question is delivered in Friendica as a new, independent @ addressed, private message and displayed in the personal timeline (picture 2)
 - For the Friendica user, the connection between the messages is lost if further posts have been received in the personal timeline in the meantime.

### Steps to Reproduce

1. start a new chat from Firefish
2. select a Friendica user as chat partner
3. send a message as a Firefish user to the Friendica account
4. reply to this message as a Friendica user
5. as a Firefish user, reply again to the Friendica user's last reply.

Actual Result:

- Each new reply from Firefish to Friendica is treated as a new thread.
- The messages are sorted fragmented in the personal timeline

Expected Result:

- The messages are not fragmented
- The history of the conversation is traceable and is displayed in the correct order
- The message from Firefish is stored as a chat in the DM system?

### Screenshots
image 1
![Screenshot 2023-10-14 at 06-24-18 tchncs](https://github.com/friendica/friendica/assets/44441246/d1e4cb95-a13e-408a-a123-16ec94342f09)
image 2
![Screenshot 2023-10-14 at 06-26-41 ˈloma Network](https://github.com/friendica/friendica/assets/44441246/0449e191-6777-4b51-9229-8b528ef6ae7f)

### Platform Info

Friendica Version: dev

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
Please chat with me, I need to have a look at the message source.

**Comment by annando** [comment]
This is fixed with PR https://github.com/friendica/friendica/pull/13543
