### ISSUE TITLE
[frio] Jumping to the thread position no longer works reliably from the 5-6 level? onwards

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13545]
In a very long and deeply nested discussion, the entry slips into the thread position. The post is visible for a short moment, but then jumps to another position in the thread. It is only possible to find the appropriate post with great effort.

https://loma.ml/display/d7544f40-4c92aca706e8865d-57d5c26a

I suspect that the level depth is causing this error, as the jump into the thread works relatively safely up to level 3.

In this context I have questions
1. do these deep levels make sense. Due to the increased number of users of Fediverse, such threads are no longer rare. Wouldn't it make sense to stop indenting from a depth of 3 and instead give a visual incentive?
2. wouldn't that also solve the problem that the remaining readable space is getting narrower and narrower? Commenting in a comment field that is now only 30 characters wide is also not very pleasant.
3. the descriptions of the icons are really crucial? As you can see, they do not contribute to the content still being easily recognisable. With the mousover descriptions, accessibility should still be established without problems. The entire thread would look tidier if the additional description of the icons were generally dispensed with.
![image](https://github.com/friendica/friendica/assets/44441246/ab3a90dc-b357-41f4-8d87-f1ab7def2d54)

Tested with Firefox without addon

**Comment by MrPetovan** [comment]
The URL you provided correctly scrolls to the "Don di Dislessia" post it's supposed to.

What kind of "visual incentive" you are referring to?

It should be possible to extend the width of the conversation without extending the post width on wide screens, but we're stuck on narrower screens like mobile devices.

For the action buttons, they already are reduced to icons in mobile view, so this shouldn't be a problem.

**Comment by loma-one** [comment]
If I may express a wish, I would like to see a width for all contributions that varies only slightly and is only marginally indented from level 2, 3 or 4. 

I would symbolise the levels with a thread. Here is an attempt to represent it visually ;)
![image](https://github.com/friendica/friendica/assets/44441246/753cfa37-13b5-4362-a428-45b4e4c1c38b)

**Comment by loma-one** [comment]
> The URL you provided correctly scrolls to the "Don di Dislessia" post it's supposed to.

It is always the combination of notification and jumping from notification to a very low position in the thread. Unfortunately, this cannot be recreated in this way.

https://loma.ml/display/373ebf56-1065-2b09-fde6-d8a762154432

**Comment by MrPetovan** [comment]
> If I may express a wish, I would like to see a width for all contributions that varies only slightly and is only marginally indented from level 2, 3 or 4.
> 
> I would symbolise the levels with a thread. Here is an attempt to represent it visually ;) ![image](https://user-images.githubusercontent.com/44441246/275341803-753cfa37-13b5-4362-a428-45b4e4c1c38b.png)

We've experimented with smaller indentation for thread level, but there's a threshold under which you can't reliably figure out what level you're on or who's replying to whom. It's been improved with the display of the direct parent author thanks to @xundeenergie, but at this point we'd need a really different display for smaller indentation to work.

**Comment by loma-one** [comment]
I know the theme from @xundeenergie. It starts at the outer edge of a post element. 
If it is not at the outermost edge, but closer to the user favicon of the poster, the visual impression can be strengthened. However, this probably requires changes to the UI.
I might be able to think of other alternatives.

**Comment by xundeenergie** [comment]
I can not figure out, what's not working on jumping to the right position.

Here it jumps to the postings, you've linked to, and stays there. (Firefox Android).

I made an update for my threadview, which looks much nicer than the old one. But it's not finished. Can push it, if you want in this state.

Yes, it does not solve the problem with very deep threadlevels, but i can read all of the discussions very good, even on my smartphone.
Since yesterday screencasts are working again on my gnome, so i will show you your linked discussion on my friendica.

And threadlevels... yes, I want them in all holy deepness. Even in deep discussions i want to know, which answer is to which other...

**Comment by xundeenergie** [comment]
Here is my screencast
https://kino.schuerz.at/w/oBi2FhUH5mF2bUDgFf4eZz

**Comment by loma-one** [comment]
I think that's a very nice basis because it solves the problem of deep levels better in many cases than the existing function. It doesn't indent as much, which increases readability tremendously.

However, at the moment it is tied to your theme and is not colour neutral in terms of interaction elements.

I would also like layer 1 not to have a thread (this is certainly a matter of taste).

It would be great if the thread connected the favicons of the users. But I had already written about that elsewhere.

**Comment by xundeenergie** [comment]
You mean something like this?
![connection](https://github.com/friendica/friendica/assets/5894829/a7f06c38-4c51-4644-bf64-51bebd87f748)

And what do you mean about "not color neutral"?
My modifications follows the accenture-color of the theme... no other colors are used.

And the "first" posting should have no line on the left? only above level 1 should have a thread?

**Comment by loma-one** [comment]
i mean this
![grafik](https://github.com/friendica/friendica/assets/44441246/3762f4ca-a324-40bf-91ea-2be6ae96e5a3)

**Comment by xundeenergie** [comment]
Ok... 
Therefore i think, the template must be rewritten...
