### ISSUE TITLE
[frio] Adding user to a circle - search works only with Fullname not with username/fediverse-handle

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#13542]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

Tried to add a user to a circle and search by userid. Did not found the User. Tried the fullname, the user appears ans i can add him.

### Steps to Reproduce

1.  Go to new circles
2.  klick on one circle
3.  add username in filter

Actual Result:

the user does not appear in filtered result.

Expected Result:

Get search-results for fullname and username as well.
### Platform Info

Friendica Version:

The Name (which is part of the username):
![grafik](https://github.com/friendica/friendica/assets/5894829/d91a6a36-439a-491e-b21a-ca1c958fd7b2)

The same name added one "w", which is also part of the username
![grafik](https://github.com/friendica/friendica/assets/5894829/89650cda-25ee-4c66-812b-ca72c5b445bf)

Friendica Source: 2023.09-rc

PHP version: 8.2

SQL version: mariadb 10.11

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/13544
