### ISSUE TITLE
Personal Timeline Fedilab is not updated

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13554]
- [x] I have searched open and closed issues for duplicates

### Bug Description
With the RC, the personal timeline on Fedilab no longer loads correctly. The last post is from 10.09.
The account was deactivated once and reconnected. No change.

Suspicion: the channels are not recognised cleanly by Fedilab and are not updated.

Tusky updates the timeline reliably.

### Screenshots
![Screenshot_20231018-085638](https://github.com/friendica/friendica/assets/44441246/1a805e81-0379-482e-b511-9f778c3d98e2)

### Platform Info

Friendica Version: RC

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by kr428** [comment]
(Just as a note: In my case, tusky is broken in timelines too (running into a network timeout after a while, without displaying any data). Relatica, apparently, is broken too at the moment, I'll file another issue for that.

EDIT: Relatica behaves similar to tusky on my account, documented this here: https://gitlab.com/mysocialportal/relatica/-/issues/49

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/pull/13557

**Comment by foss-** [comment]
Fix has been merged, can you retry with that? A similar issue with pachli has been resolved: https://github.com/pachli/pachli-android/issues/88

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/pull/13557
