### ISSUE TITLE
Wrong permissions set for followers-only comments (via web interface)

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#13566]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

If there is thread with followers-only comments and multiple users engage then Friendica sends replies restricted only to specific user.

### Steps to Reproduce

There are three users **A B C** on different servers all following each other discussing a post by User **C**. Users **A** and **B** are not Friendica, user **C** is on Friendica.

1.  User **A** sends a followers-only comment, everyone sees it. Permission tooltip says "To: Followers (User  A), CC: User C"
2.  User **B** replies to this comment, also followers-only, everyone sees it. Permission tooltip says "To: User A, User C, Followers (User B)"
3.  User **C** (Friendica) replies to comment of user **B**. Just **B** sees it. Permission tooltip says: ""To: User B"

Actual Result:

Only User **B** sees the reply, user **A** wonders about gaps in the thread.

Expected Result:

Replies to protected comments should include audience of the comment the reply is sent to, not just the author of it. At least they should include explicitly listed recipients if it is not possible to know followers scope.

Current RC.

**Comment by SpcCw** [comment]
Looks like this is closed with https://github.com/friendica/friendica/pull/13584

Huge thank you!

**Comment by annando** [comment]
There is still some open work. I'm currently working on that.
