### ISSUE TITLE
Worker freezes or distributes contributions only with a strong delay

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13564]
- [x] I have searched open and closed issues for duplicates

### Bug Description
The worker queue is continuously busy with contact updates jobs. The worker no longer does this cyclically, but continuously (24 h). This ensures that the distribution of contributions is only carried out with a long delay or stops completely. 

The fetching of new contributions also only takes place with a long delay. There are many gaps in the thread history.

The problem must have crept in during the last 3-4 days. Previously, the distribution of contributions was possible almost in real time.

The load is normal. No hanging scripts on the DB
![grafik](https://github.com/friendica/friendica/assets/44441246/281cea1f-a023-45e3-a35d-f13bc6b9b7a6)

### Platform Info

Friendica Version: RC 1538

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by utzer** [comment]
Maybe related to https://github.com/friendica/friendica/issues/13563?

**Comment by loma-one** [comment]
@utzer I have not noticed any unusual load. 
I have restarted PHP-FPM & Apache several times without noticing any change.

---

With a queue of 177 - 766, it currently takes 11 minutes to deliver new posts. 
'bulk_delivery' => true,

**Comment by utzer** [comment]
> I have not noticed any unusual load.
> I have restarted PHP-FPM & Apache several times without noticing any change.

OK, I just thought it could be related.

**Comment by loma-one** [comment]
On one of my instances, since the RC, I have to delete the worker queue in the morning, otherwise it stops sending posts. 
I realise that this should not be done. But what is the alternative? 

What do I have to look for in the logs to isolate the problem?

**Comment by xundeenergie** [comment]
It is now 20. October 9:45am.
![grafik](https://github.com/friendica/friendica/assets/5894829/81df4c8a-1240-41e2-8cc5-97372c473b5c)

I've restarted php and the worker daemon.
Also running the daemon manually does not do anything.

**Comment by loma-one** [comment]
Recording of the Load: logs
https://mecp.de/jamorepako.less

**Comment by annando** [comment]
PHP-FPM is frontend, worker is backend. They are unrelated.

Please execute this command:
```
> select command,count(*) as total from workerqueue where not done group by command;
+----------------------+-------+
| command              | total |
+----------------------+-------+
| APDelivery           |    42 |
| Delivery             |    17 |
| FetchMissingActivity |     2 |
| ProcessQueue         |     3 |
+----------------------+-------+
4 rows in set (0,001 sec)
```
This shows the number of pending tasks.

Also execute this command:
```
$ tail -f friendica.log | grep -a Load:.*Worker.php
2023-10-20T21:35:34Z app [INFO]: Load: 2.34/20 - processes: 61/1/5 - jpm: 21 (0:0, 20:1/20, 30:0/46) - maximum: 21/30 [] - {"file":"Worker.php","line":825,"function":"tooMuchWorkers","request-id":"6532f2a625262","stack":"Worker::tooMuchWorkers (1319), Worker::add (689), Receiver::processActivity (1624), Processor::fetchMissingActivity (241), Receiver::processRelayPost (111), Receiver::processInbox (101), Inbox::post (233), BaseModule::run (109), BaseApi::run (43), Inbox::run (710), App::runFrontend (55)","uid":"290da2","process_id":3770345}
2023-10-20T21:35:37Z app [INFO]: Load: 2.34/20 - processes: 61/1/6 - jpm: 19 (0:0, 20:1/21, 30:0/46) - maximum: 21/30 [] - {"file":"Worker.php","line":825,"function":"tooMuchWorkers","request-id":"6532f2a90ef9a","stack":"Worker::tooMuchWorkers (1319), Worker::add (689), Receiver::processActivity (168), Receiver::processInbox (101), Inbox::post (233), BaseModule::run (109), BaseApi::run (43), Inbox::run (710), App::runFrontend (55)","uid":"1171d5","process_id":3771825}
...
```
That one shows the jobs per minute and a lot of other worker related stuff. That command will display new log entries while they are created, so wait a few minutes. Then have a look at the average numbers of jobs per minute during that time.

**Comment by loma-one** [comment]
https://soc.schuerz.at/display/4edd2508-1165-304b-8c44-16c726565393

MariaDB [friend]> select command,count(*) as total from workerqueue where not done group by command;

```
+-------------------------+-------+
| command                 | total |
+-------------------------+-------+
| APDelivery              |   405 |
| BulkDelivery            |    44 |
| Contact\Remove          |    25 |
| Contact\Unfollow        |     1 |
| DelayedPublish          |    10 |
| Delivery                |     6 |
| ExpireAndRemoveUsers    |     1 |
| Notifier                |     1 |
| OnePoll                 |    52 |
| PostUpdate              |     1 |
| ProcessQueue            |    38 |
| RemoveUnusedAvatars     |     1 |
| RemoveUnusedContacts    |     1 |
| UpdateContact           |    13 |
| UpdateContacts          |     1 |
| UpdateGServers          |     1 |
| UpdateServerDirectories |     1 |
+-------------------------+-------+
17 rows in set (0,003 sec)
```

```
+----------------------+-------+
| command              | total |
+----------------------+-------+
| APDelivery           |   499 |
| BulkDelivery         |    44 |
| Contact\Remove       |    26 |
| Contact\Unfollow     |     1 |
| DelayedPublish       |    11 |
| Delivery             |     6 |
| ExpireAndRemoveUsers |     1 |
| Notifier             |     1 |
| ProcessQueue         |    63 |
| RemoveUnusedAvatars  |     1 |
| RemoveUnusedContacts |     1 |
| UpdateContact        |    50 |
| UpdateSuggestions    |     2 |
+----------------------+-------+
13 rows in set (0,003 sec)
```

```
+----------------------+-------+
| command              | total |
+----------------------+-------+
| APDelivery           |   534 |
| BulkDelivery         |    88 |
| Contact\Remove       |    33 |
| Contact\Unfollow     |     1 |
| Cron                 |     1 |
| DelayedPublish       |    11 |
| Delivery             |     6 |
| Directory            |     1 |
| ExpireAndRemoveUsers |     1 |
| Notifier             |    13 |
| OnePoll              |   133 |
| ProcessQueue         |   337 |
| PushSubscription     |    72 |
| RemoveUnusedAvatars  |     1 |
| RemoveUnusedContacts |     1 |
| SearchDirectory      |     1 |
| SpoolPost            |     1 |
| UpdateContact        |    66 |
| UpdateGServer        |     7 |
| UpdateSuggestions    |     2 |
+----------------------+-------+
20 rows in set (0,004 sec)
```

```
+-------------------------+-------+
| command                 | total |
+-------------------------+-------+
| APDelivery              |   339 |
| BulkDelivery            |    82 |
| ClearCache              |     1 |
| ContactDiscoveryForUser |     1 |
| Contact\Remove          |    27 |
| Contact\RemoveContent   |    73 |
| Contact\Unfollow        |     1 |
| Cron                    |     1 |
| DelayedPublish          |    23 |
| Delivery                |     6 |
| ExpireAndRemoveUsers    |     1 |
| Notifier                |     2 |
| OnePoll                 |   116 |
| PostUpdate              |     1 |
| ProcessQueue            |   188 |
| PubSubPublish           |     2 |
| PushSubscription        |     8 |
| RemoveUnusedAvatars     |     1 |
| RemoveUnusedContacts    |     1 |
| SpoolPost               |     1 |
| UpdateBlockedServers    |     1 |
| UpdateContact           |   724 |
| UpdateContacts          |     1 |
| UpdateGServers          |     1 |
| UpdateScores            |     1 |
| UpdateServerDirectories |     1 |
| UpdateSuggestions       |     2 |
+-------------------------+-------+
27 rows in set (0,004 sec)

```

---

$ tail -f friendica.log | grep -a Load:.*Worker.php

https://mecp.de/pefotezilo.sql

---

Once again for classification. 
* Although the worker queue is small, it currently takes at least 3 minutes until a new contribution is scheduled for dispatch. It takes 6 minutes until delivery to a remote server.
* Comments are sometimes only displayed with a delay of 25 minutes. This is then a whole swarm of notifications.

**Comment by annando** [comment]
Concerning the data, your system is doing really fine. You possibly should increase the number of parallel workers.

**Comment by loma-one** [comment]
There are already 50 workers running.
How can I calculate how many workers I can run?
I had once read that there are 5 per processor.
With 14 processors, that would be 70 workers
![grafik](https://github.com/friendica/friendica/assets/44441246/a1efbacf-d003-4f85-9ac3-e7b1521f75e5)

---
It doesn't help on smaller servers where the workers break overnight and the only way to get them running again tomorrow is to hard clear the queue.

How can I help to find the real problem so that the system feels healthy again?

**Comment by loma-one** [comment]
It looks like that is the reason:
IP 129.105.31.75 set to instance block and IP block. The requests are not coming in. The load no longer increases 
![grafik](https://github.com/friendica/friendica/assets/44441246/5906c445-cfe5-401b-a0cb-4e1bfe4aaf4b)

https://www.bentasker.co.uk/posts/blog/security/digging-into-the-behaviour-of-a-self-authenticating-mastodon-scraper-bot.html
