### ISSUE TITLE
[housecleaning] sunset app.net support and remove from about website

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13567]
app.net has shutdown operations 2017. Not sure how this is handled in friendica but potentially sunset / remove related code and remove `App.net` from `About` website https://friendi.ca/about/

https://en.wikipedia.org/wiki/App.net

**Comment by MrPetovan** [comment]
About page has been updated.

**Comment by foss-** [comment]
I don't think app.net is still supported anywhere in friendica. Closing.
