### ISSUE TITLE
Massive Deferred worker queues

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#13570]
I want to figure out what's up with this. I have over 100.000 processes in the Inspect deferred worker queue for the past may many months. 

Here are some commands I used from this issue https://github.com/friendica/friendica/issues/13241 :

` select command,count(*) as total from workerqueue where not done  group by command;`

| Command               | Total   |
|-----------------------|---------|
| AddContact            | 17,670  |
| APDelivery            | 651     |
| ContactDiscovery      | 1,871   |
| Contact\Remove        | 11,818  |
| Delivery              | 130     |
| ExpireAndRemoveUsers  | 1       |
| UpdateContact         | 79,916  |
| UpdateGServer         | 87      |

` select retrial,count(*) as total from workerqueue where not done group by retrial;`

| Retrial | Total  |
|---------|--------|
| 0       | 28     |
| 1       | 79     |
| 2       | 359    |
| 3       | 501    |
| 4       | 1,307  |
| 5       | 18,240 |
| 6       | 15,926 |
| 7       | 21,103 |
| 8       | 844    |
| 11      | 2,827  |
| 12      | 6,955  |
| 13      | 10,983 |
| 14      | 9,308  |
| 15      | 23,741 |

` select priority,count(*) as total from workerqueue where not done group by priority;`

| Priority | Total  |
|----------|--------|
| 30       | 14     |
| 40       | 58,402 |
| 50       | 53,808 |

My server is: 
```
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 8 cores
32GB RAM + 32GB SWAP
3TB SSD
```

My server is doing fine it seems. Friendica works very well.

Here are my workers settings:
![2023-10-23_02-51](https://github.com/friendica/friendica/assets/38043315/f0ec3e16-55f0-43aa-a214-bb1b476bf1d9)

### Platform Info

Friendica Version: 2023.05

| Category           | Configuration Value     |
|-------------------- |------------------------- |
| PHP                |                         |
| Version            | 8.2.11                   |
| php.ini Location   | /etc/php/8.2/fpm/php.ini |
| upload_max_filesize| 200M                    |
| post_max_size       | 200M                    |
| memory_limit       | 128M                    |
| MySQL / MariaDB    |                         |
| max_allowed_packet  | 16,777,216 bytes (16MB)  |

I've read that these deferred queues may not be that important, but over 100k seems like there is an issue somewhere.

**Comment by MrPetovan** [comment]
Deferred tasks are background tasks that failed for an external reason (remote contact not reachable for example) and will be retried at a later date, with increasing delay each subsequent retrial. As a result they don't take up any resources while they're waiting for their due date.

**Comment by tio-trom** [comment]
Ok so they are deferred for external reasons, not server limitations or Friendica misconfiguration. That's all I wanted to know. Am closing it now and thank you very much, as always!
