### ISSUE TITLE
[FRIO] Remove the icon descriptions for the interaction options on posts.

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13577]
### Describe the feature you'd like
The icon descriptions for the interaction options on posts (like, dislike, share, quote) are more of a hindrance than a help in deep discussions. It makes the application unnecessarily complex and confusing. They were originally helpful to ensure accessibility. Tooltips continue to ensure accessibility.

In comparable applications such as Friendica, the description on icon is dispensed with. In the mobile view, the icon description is also dispensed with in Friendica.

![grafik](https://github.com/friendica/friendica/assets/44441246/7c6e0329-8e72-4798-ab7b-ea163709f476)
![grafik](https://github.com/friendica/friendica/assets/44441246/e8d23ca0-ec7d-480f-becc-c460ebef032e)
![grafik](https://github.com/friendica/friendica/assets/44441246/fc9a03be-e749-482c-87ed-13dad104960f)
![grafik](https://github.com/friendica/friendica/assets/44441246/beb1df02-fef0-4ab1-a111-ac03a7811c1f)

**Comment by foss-** [comment]
Welcome change to unclutter webUI. Slightly increasing icon size would be a nice touch.

**Comment by haheute** [comment]
I would try this one..

**Comment by Raroun** [comment]
Something like this?
![image](https://github.com/friendica/friendica/assets/10846157/ff408e5c-aa3c-4715-99cc-cddf29f1595a)

**Comment by loma-one** [comment]
Super👍. One more question. Can the icons still be distributed equally on the horizontal?

**Comment by Raroun** [comment]
i was thinking about that - or move some of the items in the "more" section to the empty space, but im unsure - any input is welcome :)

**Comment by Raroun** [comment]
@loma-one 
![image](https://github.com/friendica/friendica/assets/10846157/94e887c7-bc27-4627-88be-60499eb7b6c0)

like this?

**Comment by haheute** [comment]
@Raroun .. I also tried this. I thought one could perhaps use the CSS from the mobile view, but I wasn't able to find the right media query .. :shrug:

**Comment by Raroun** [comment]
@haheute 
Took me an hour to find the correct place. It is in in the Frio `wall_thread.tpl`.

**Comment by foss-** [comment]
Looking better already. While you are touching this code, would it be possible to increase the size of those icons just a tad? They look small. I think X does a good job UI wise finding the sweet spot for icon size:

![X icons](https://github.com/friendica/friendica/assets/5708172/c96cd5c1-a2b4-4336-a89d-9e451f0e942f)

Btw there is a lot more to learn from their UI, but that is better tackled in future friendica issues:

- use different colors for actions
- show light circle around icon when hovering with mouse using the respective icon color
- number of interactions is shown next to icon (friendica shows them in an extra row, cluttering the view)

**Comment by Raroun** [comment]
I will try, but i think it will collide with the font size - like the "more".

**Comment by foss-** [comment]
Hmm, good question. Would need to see screenshots to make a statement on that. Do we even need the "More..." text? Wouldn't removing that text just follow the logic of removing the other icon text?

**Comment by Raroun** [comment]
@foss- 
I will look into it - first i will create a pull request for the remove of the icon descriptions.
After that i will look into your suggestions and fiddle a bit with the sizez and hover actions. :)

**Comment by foss-** [comment]
Sure, taking small steps is a good approach to keep moving and this can be iterated on as we go.

**Comment by Raroun** [comment]
PR #13596

**Comment by haheute** [comment]
It seems, now I have double icons when dragging the window small/narrow...  I almost believe we could use the smartphone icons everywhere when removing the visible-xs class (i mean in the template, i tried with the browser dev tools..) but I'm not sure

**Comment by Raroun** [comment]
@haheute 
just checked - and you are right. in the mobile view there are now double icons.
i will check that tomorrow.

**Comment by foss-** [comment]
Just a screenshot to document the known issue of double icons in small window size (when frio switches to mobile view). Obviously this affects all mobile devices accessing friendica:
![patch icons only](https://github.com/friendica/friendica/assets/5708172/7bc6db71-8f84-4e90-b041-56f392abe70d)

What can also be seen is that mobile does not use `… More` but only `…` which I think is an indicator `More` should also go on desktop / non-mobile webUI.

**Comment by loma-one** [comment]
> @loma-one ![image](https://user-images.githubusercontent.com/10846157/279911438-94e887c7-bc27-4627-88be-60499eb7b6c0.png)
> 
> so was?

Yes. Great

**Comment by Raroun** [comment]
Double icons on mobile view are fixed in PR #13599.

**Comment by foss-** [comment]
Merged and seems to work as expected. Thanks for your efforts and tackling this @Raroun 
I really enjoy the less busy UI.

Can this issue be closed or is there remaining work to be done?

**Comment by kr428** [comment]
Question on that however: The new arrangement of course needs getting used to, but what somehow triggers me now is that, on private posts lacking a "reshare" button, all the others suddenly move one to the left. By no means a problem but it feels a bit unexpected. Would it be possible in this case to not hide but somehow visually / functionally "disable" the reshare button?

**Comment by MrPetovan** [comment]
Please create a new issue for this. If we show a disabled state we also have to explain why it is disabled.

**Comment by kr428** [comment]
> Please create a new issue for this. If we show a disabled state we also have to explain why it is disabled.

Ok, done, thanks. See https://github.com/friendica/friendica/issues/13615 . 🙂
