### ISSUE TITLE
Setting up 2FA is not working anymore

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#13573]
### Bug Description

Setting up 2FA isn´t working anymore.

### Steps to Reproduce

1.  Click on Preferences
2.  Set up 2FA

Actual Result:

Nothing happens - i remeber a scannable code there.
No errors in php log or fiendica log.

Expected Result:

A Scannable Barcode should show

### Platform Info

Friendica Version: 2023.09-rc, latet commit

Friendica Source:  git

PHP version: 8.2

**Comment by MrPetovan** [comment]
I can confirm, I was locked out of my account on one device and has to deactivate 2FA from another (which worked). But reactivating doesn't. Thanks for the reminder.

**Comment by MrPetovan** [comment]
So, something is wonky with the page redirection. When I replace the call to `System::externalRedirect` by an HTML link and click this link, I'm led to the right page, but if I don't, the same page reload as if the redirect call never happened.

The thing is, redirection works like a charm in any other page. Why specifically the two-factor authentication settings index page, I don't know yet.
