### ISSUE TITLE
[addon] Bluesky addon does not send pictures

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13572]
Probably a local problem.

1. New Friendica account created
2. New Bluesky account created
3. Bluesky Addon activated
4. Bluesky handle and APP password stored
5. The connection from Friendica to Bluesky is active.
6. Sending a new text contribution
7. The contribution is published on Bluesky
8. Sending a new contribution with picture + text
9. The contribution will not be published on Bluesky

---

Addon directory redrawn via pull and repeated attempt.
Same result as described in points 6-8?

---

No errors or warnings in the log files
Where should I look for the error?

Friendica Version: 2023.09-rc
Quelle: git
Mysql_ 10.5
PHP Version: 8.1

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/13550

**Comment by loma-one** [comment]
The attempt to send posts with images still fails. The post is not sent.
Only text posts appear on Bluesky.

No PHP message

https://loma.ml/display/373ebf56-1665-5f16-211b-68b904190435

`2023-11-23T09:07:45Z app [NOTICE]: no data for session {"session_id":"92l50vt4o7d95teolbjs0l33sv","uri":"/photo/104765277164806ad3a83d2357264937-0.gif"} - {"file":"Database.php","line":78,"function":"read","request-id":"655f16615a022","stack":"Database::read, session_start (54), Native::start (150), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (92), DI::app (42)","uid":"353290","process_id":1086}`

**Comment by annando** [comment]
`no data for session` belongs to something completely different. Please have got a look for entries with `bluesky.php` in it and possibly raise your log level to `debug` prior.

**Comment by loma-one** [comment]
No Logs "bluesky.php"

These logs were ejected for the article https://loma.ml/display/373ebf56-6165-5f5a-ce0d-d21361990375.
https://mecp.de/witorututu.js

I hope they can point the way.

**Comment by annando** [comment]
Please check if you are on the `debug` level. There is quite some logging in that addon.

**Comment by annando** [comment]
@loma-one possibly you have got an issue with the logs. Please check if the log can be written by both the front end user and the back end user.

**Comment by loma-one** [comment]
The directory is executed with the rights www-data:www-data. This should probably not be the problem? 
I have written out everything that happens when sending to [post](https://loma.ml/display/373ebf56-1565-62eb-ce8e-c79063772236): https://mecp.de/tuxeqalori.coffeescript

The executed code is from this morning.

**Comment by annando** [comment]
All log entries there have got the "app" in it. But we are missing the background tasks. Are you using the daemon or cron?

**Comment by loma-one** [comment]
Daemon

**Comment by annando** [comment]
Okay. Then please check if the daemon user is the same as the web server user or if both users have write permission.

**Comment by loma-one** [comment]
That was the problem
So far I have run the daemon as follows. The setting should actually start the daemon with the same rights as the web server.

/etc/systemd/system/friendica-daemon.service

```
[Unit]
Description=Friendica daemon
After=network.target mysqld.service
Requires=network.target remote-fs.target nss-lookup.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/html/friendica/
Type=simple
StandardOutput=null
StandardError=syslog
ExecStart=/usr/bin/php ./bin/daemon.php start
ExecStop=/usr/bin/php ./bin/daemon.php stop
PIDFile=friendica/daemon.pid
PrivateTmp=true
InaccessibleDirectories=/home /root /boot /opt /mnt /media
ReadOnlyDirectories=/etc /usr
Restart=always

```

I now start it with a cron. It is restarted at midnight. In the config I have the following system entry `'daemon_watchdog' => true,`. If I understand it correctly, the entry checks whether the cron is running and restarts it if necessary, correct?
