### ISSUE TITLE
Bluesky: Crossposts with videos show up text-only

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13571]
Crossposting content that contains, in example, videos linked from invidious or youtube, currently only the text part will pop up on Bluesky while neither an embedded preview of the video nor the video link itself will show up, so the Bluesky receiving user has no idea that content is missing (or which). Expectation would be at least to see the link on Bluesky, ideally this would show up as a preview card as if posted via Bluesky web interface.

**Comment by annando** [comment]
Have you got an example Friendica post that wasn't converted correctly?

**Comment by kr428** [comment]
No, unfortunately not. Tried this yesterday (with this - https://loma.ml/display/373ebf56-1265-6320-6d85-46c163070238 - particular post) but apparently failed to even have this delivered to Bluesky at all. Not sure whether this helps debugging that issue though. 😬

**Comment by kr428** [comment]
Similar (not sure if the same or just related): Quote-sharing a Diaspora* post from Friendica, adding some text to it and choosing to crosspost to Bluesky will completely omit any trace of the Diaspora* post - no embed, no link, ... visible on Bluesky. Should this be separated from this one?

**Comment by annando** [comment]
Fixes by https://git.friendi.ca/friendica/friendica-addons/pulls/1471
