### ISSUE TITLE
Network posts button leads to error page

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13603]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Clicking on the Network posts button leads to an error. 

```
Exception thrown in /var/www/html/friendica/src/Module/Contact/Conversations.php:84
Stack trace:
#0 /var/www/html/friendica/src/BaseModule.php(250): Friendica\Module\Contact\Conversations->content()
#1 /var/www/html/friendica/src/App.php(711): Friendica\BaseModule->run()
#2 /var/www/html/friendica/index.php(55): Friendica\App->runFrontend()
#3 {main}
```

### Screenshots

Profile page of a user with the Network posts button

![2023-11-04_12-04](https://github.com/friendica/friendica/assets/44441246/8cf47871-de09-4454-ba04-0d4615b9e4f7)

Result after clicking on the Network posts button

![2023-11-04_12-04_1](https://github.com/friendica/friendica/assets/44441246/dabdc2f5-2a48-4ad5-92b1-16609b14757e)

### Platform Info

Friendica Version: 2023.09-rc

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by MrPetovan** [comment]
Please provide the URL this button is leading to.

**Comment by Raroun** [comment]
@MrPetovan 
This happens when you access a profile from the moderation page.
The Button has a contact-number that is allways wrong.
Example:

`<button type="button" id="showgroup" class="btn btn-labeled btn-primary" onclick="window.location.href=('contact/94240/conversations')">`

This is the button from a Profile Page that you access through moderation.
The value is allways wrong by 1.

the right contact would be **94241**.

**Comment by Raroun** [comment]
![image](https://github.com/friendica/friendica/assets/10846157/34d76283-76b8-4c6b-a6ae-7ce1fb139799)


![image](https://github.com/friendica/friendica/assets/10846157/ea9633f2-9c55-4563-b7a5-8e53f1a7e91a)


![image](https://github.com/friendica/friendica/assets/10846157/fbf9c261-7baf-4ab5-a5e0-9a87d3e17584)

**Comment by MrPetovan** [comment]
Thank you for the detailed report!

**Comment by MrPetovan** [comment]
Hum, that's a tricky one. In this context, the only contact ID we have is for the self-contact record  which cannot currently be used to query a contact.
