### ISSUE TITLE
Uncaught exception in worker execution

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#13601]
since the git pull this morning I keep getting the following error message in the logs 

`2023-11-04T05:21:05Z daemon [ERROR]: Uncaught exception in worker execution {"class":"Error","message":"Call to undefined method Friendica\\Core\\L10n::getDetectableLanguages()","code":0,"file":"/var/www/html/src/Model/Item.php:2037","trace":"#0 /var/www/html/src/Model/Item.php(2003): Friendica\\Model\\Item::getLanguageArray()\n#1 /var/www/html/src/Model/Item.php(1269): Friendica\\Model\\Item::getLanguage()\n#2 /var/www/html/src/Protocol/ActivityPub/Processor.php(1155): Friendica\\Model\\Item::insert()\n#3 /var/www/html/src/Protocol/ActivityPub/Receiver.php(738): Friendica\\Protocol\\ActivityPub\\Processor::postItem()\n#4 /var/www/html/src/Protocol/ActivityPub/Queue.php(239): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()\n#5 /var/www/html/src/Worker/ProcessQueue.php(39): Friendica\\Protocol\\ActivityPub\\Queue::process()\n#6 [internal function]: Friendica\\Worker\\ProcessQueue::execute()\n#7 /var/www/html/src/Core/Worker.php(572): call_user_func_array()\n#8 /var/www/html/src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n#9 /var/www/html/src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#10 /var/www/html/src/Core/Worker.php(1183): Friendica\\Core\\Worker::processQueue()\n#11 /var/www/html/src/Core/Worker.php(1203): Friendica\\Core\\Worker::forkProcess()\n#12 /var/www/html/bin/daemon.php(208): Friendica\\Core\\Worker::spawnWorker()\n#13 {main}","previous":null,"worker_id":"a8064a2","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":577,"function":"execFunction","request-id":"6542f5b31f41d","stack":"Worker::execFunction (386), Worker::execute (121), Worker::processQueue (1183), Worker::forkProcess (1203), Worker::spawnWorker (208)","uid":"15c1c2","process_id":2719}`

`2023-11-04T05:21:05Z daemon [ERROR]: Uncaught exception in worker execution {"class":"Error","message":"Call to undefined method Friendica\\Core\\L10n::getDetectableLanguages()","code":0,"file":"/var/www/html/src/Model/Item.php:2037","trace":"#0 /var/www/html/src/Model/Item.php(2003): Friendica\\Model\\Item::getLanguageArray()\n#1 /var/www/html/src/Model/Item.php(1269): Friendica\\Model\\Item::getLanguage()\n#2 /var/www/html/src/Protocol/ActivityPub/Processor.php(1155): Friendica\\Model\\Item::insert()\n#3 /var/www/html/src/Protocol/ActivityPub/Receiver.php(738): Friendica\\Protocol\\ActivityPub\\Processor::postItem()\n#4 /var/www/html/src/Protocol/ActivityPub/Receiver.php(702): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()\n#5 /var/www/html/src/Protocol/ActivityPub/Processor.php(1618): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity()\n#6 /var/www/html/src/Protocol/ActivityPub/Receiver.php(774): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity()\n#7 /var/www/html/src/Protocol/ActivityPub/Queue.php(239): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()\n#8 /var/www/html/src/Worker/ProcessQueue.php(39): Friendica\\Protocol\\ActivityPub\\Queue::process()\n#9 [internal function]: Friendica\\Worker\\ProcessQueue::execute()\n#10 /var/www/html/src/Core/Worker.php(572): call_user_func_array()\n#11 /var/www/html/src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n#12 /var/www/html/src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#13 /var/www/html/src/Core/Worker.php(1183): Friendica\\Core\\Worker::processQueue()\n#14 /var/www/html/src/Core/Worker.php(1203): Friendica\\Core\\Worker::forkProcess()\n#15 /var/www/html/bin/daemon.php(208): Friendica\\Core\\Worker::spawnWorker()\n#16 {main}","previous":null,"worker_id":"d68c19e","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":577,"function":"execFunction","request-id":"6542f5b31f41d","stack":"Worker::execFunction (386), Worker::execute (121), Worker::processQueue (1183), Worker::forkProcess (1203), Worker::spawnWorker (208)","uid":"15c1c2","process_id":2719}`

[[](url)](https://paste.sekretaerbaer.net/?bcc3a55196b40863#AeG5FYDR3rQfHE2phUYg4eG2gG3nfTzJt19DEVgFbBSP)

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.09-rc - 1539

Friendica Source: git

PHP version: 8.1.2

SQL version: 10.6.12-MariaDB

**Comment by sekretaerbaer** [comment]
I have just noticed that ActivityPub posts are no longer arriving on my instance. All of them are moved to the delayed queue.

**Comment by sekretaerbaer** [comment]
restarting the worker solved the problem

**Comment by MrPetovan** [comment]
Living on the edge, huh? Code changes can sometimes trip the worker that's running in memory in the background. It doesn't happen so often for stable release users but for `develop` and `rc` people, this is bound to happen eventually. Thank you for your report!
