### ISSUE TITLE
[Frio] new interaction layout doesn't provide access to profiles of interacting users anymore

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13617]
The current changes to the action bar in Frio look rather slick but come with a major shortcoming:

![image](https://github.com/friendica/friendica/assets/685879/5e49ed81-3a1d-4ae5-892a-2dc76193a5a3)

For the numbers next to the actions, it's not possible anymore to access the profiles that interacted with a post. On desktop, at least one has the chance to see the names (by hovering the icon), on mobile this doesn't work anymore at all. Would it be possible to restore these functionality on all devices, in example by tapping the number?

**Comment by MrPetovan** [comment]
Tentative junior job, but it heavily depends on the data we're passing to the `wall_thread.tpl` template so it might be a little more involved.

**Comment by annando** [comment]
With PR https://github.com/friendica/friendica/pull/13618 there is now a new configuration setting `legacy_activities` to enable or disable the list of activities below these buttons.

Disabled:
![image](https://github.com/friendica/friendica/assets/844208/4ff753d8-9cc5-41d8-8e38-d07dfe4cd06d)
Enabled:
![image](https://github.com/friendica/friendica/assets/844208/e3d84346-839e-4241-bd52-bf516af1023d)

**Comment by MrPetovan** [comment]
Closed by #13618
