### ISSUE TITLE
[Frio] "Enable dislike" doesn't work with recent action bar anymore

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13625]
In current 2023.09-rc, my action bar looks like this:

![image](https://github.com/friendica/friendica/assets/685879/7af304ae-c583-464b-94a6-3f544e688305)

I however have disabled the "enable_dislike" feature in the settings. This probably shouldn't happen...?

**Comment by MrPetovan** [comment]
See https://github.com/friendica/friendica/pull/13618#issuecomment-1802356611

**Comment by kr428** [comment]
Ah ok. Thanks. Then this is most likely a dupe? Feel free to close it off then.

**Comment by AlfredSK** [comment]
> Ah ok. Thanks. Then this is most likely a dupe? Feel free to close it off then.

I think this issue is a good reminder - better than just a comment under a PR. 🙂

**Comment by MrPetovan** [comment]
@AlfredSK is right, I was merely pointing at an earlier related discussion. If it had been a duplicate, I would have closed it myself. 🙂
