### ISSUE TITLE
Gallery with spaces in their names can't be browsed for adding images

### ISSUE THREAD

**Issue by HankG** [friendica/friendica#13621]
### Bug Description

One cannot add images from a gallery with a space in their name because the browser for the gallery never renders

### Steps to Reproduce

1. Upload an image into a gallery with a space in the name
2. Click the icon to make a new post
3. Go over to the browse tab
![Screenshot 2023-11-08 at 11-56-26 Friendica Social Network Network](https://github.com/friendica/friendica/assets/1683691/abc374aa-7e37-439c-b3d6-6cc67948f97e)
4. Click the button of the gallery with the space in the name (in the above case "Test Images"). 

Actual Result:
Below is what is rendered. In the browser console there is a 403 error. 
![Screenshot 2023-11-08 at 11-56-35 Friendica Social Network Network](https://github.com/friendica/friendica/assets/1683691/0e15d481-cb4a-4211-a8c0-456ad929312a)

Expected Result:
![Screenshot 2023-11-08 at 11-57-07 Friendica Social Network Network](https://github.com/friendica/friendica/assets/1683691/b48fb85b-162f-4d1a-ab85-eaa2fe017503)

### Platform Info

This is Friendica, version 2023.09-rc. The database version is 1539/1539, the post update version is 1507/1507. I've noticed this for some time now so at least since 2023.03 but haven't tried to fix yet

PHP version: PHP 8.1.2

**Comment by MrPetovan** [comment]
I can't reproduce this issue with spaces in album names, mine are loading fine. I'm not sure why your system doesn't support `%20` for spaces but it doesn't seem to be a Friendica issue.

Sample path: `/media/photo/browser/Test%20drop?mode=none&theme=frio&_=1699573272412`

With all non-ASCII characters (album name is `Фото стены`): `/media/photo/browser/%D0%A4%D0%BE%D1%82%D0%BE%20%D1%81%D1%82%D0%B5%D0%BD%D1%8B?mode=none&theme=frio&_=1699573272414`

Both are working as expected.

**Comment by HankG** [comment]
The problem is that in more recent Apache releases, apparently, you need an additional parameter `B` on the Rewrite rules. These were added to the `.htaccess` template at the end of 2022 with commit https://github.com/friendica/friendica/commit/0e2c2cd0e0fc8c2ed7a94ef7b4b22c98f562656d but mine never got updated. If others have the problem they should ensure their rewrite rules have been updated as well.
