### ISSUE TITLE
Wrong link in posting

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1362]
I just got a post by Tobias (ProP­ub­lica: The World’s Email Encryp­tion Soft­ware Relies on One Guy, Who is Going Broke) that contained this link: https://snarl.de/www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke which obviously is going nowhere. On tobias' friendica instance the link is wrong as well: https://f.diekershoff.de/www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke

Not sure if this is a usage error or a friendica issue. If it's the later, I consider this bug as critical.

**Comment by fabrixxm** [comment]
Someone inserted the URL without ‛http://‛

**Comment by tugelbend** [comment]
If that's the case, the editor should check that and assist.

**Comment by tugelbend** [comment]
I checked the functionality. If you add a link using the editors Link-Button, there is no http added if it's not in the link.

**Comment by tobiasd** [comment]
I wonder how the http was lost though copy&paste magic x-) but I agree the link should be checked for being with a http. As the content was embedded as usual I did not suspect any difficulties with that posting.

**Comment by annando** [comment]
The pull request is accepted and it seem to work. I'm closing the issue.
