### ISSUE TITLE
Visibility for Mentions needs to be more obvious

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13626]
2023.09-rc: Tried: Navigated to a Mastodon profile of mine, used "Mention" and started out with a compose screen.

![image](https://github.com/friendica/friendica/assets/685879/60521e21-18ba-4773-9989-28321964d8f4)

I however failed to, this way, create a Mastodon-style "direct message" addressing this particular recipient. In the "visible for" text field I do not have suggestions / completion for accounts or circles. Tried adding the handle of the recipient (as in the text field above) again and sent out this message - which resulted in the recipient seeing a "follower-only" post not (as expected) a "private" message only visible for sender and recipient. This makes using that particular feature between Friendica and other Fediverse platforms a bit ... risky. Could this be improved - and be it by making the dialogue clearer to figure out how to send a "follower-only" and how to send a direct message?

**Comment by MrPetovan** [comment]
"Mention" isn't meant to be "Private", I thought the language distinction would make this clear. It doesn't use Friendica's own private message pages either.

**Comment by kr428** [comment]
> "Mention" isn't meant to be "Private", I thought the language distinction would make this clear. It doesn't use Friendica's own private message pages either.

Hmmm, I'm unsure what adds more to the confusion here - the fact that mention is "somewhat public" (like, how comes it's "follower-only" if I leave the "visible for" field empty") or the fact that, if coming from a Mastodon/Firefish/Hubzilla, there's some notion of (cross-platform/instance) "private message" understanding which doesn't seem to be the case for Friendica? Would it be _possible_ to support something like a "Private Mention" in this setup?

**Comment by MrPetovan** [comment]
Let's untangle all these concepts:
- Mention: It simply mentions an account in a post, but doesn't say anything about its deliverability. You can mention someone in a public or a restricted post. Although it's possible we add the mentioned account to the delivery targets, which may be wrong depending on the use case (privately talking about an account that shouldn't be in the loop)
- Restricted post: It's a regular post with less than public visibility. On Friendica it can be your followers-only, to a specific circle or list of people, or to followers excluding a specific circe or accounts.
- Private message: In Friendica it's a separate feature from regular posts, although it may be piggy-backing off the same delivery feature than regular posts. These are always restricted to the accounts listed as recipients, regardless of mentions (not even sure mention works in private messages)
- Access Control List: This is the form element you use to specify who gets to be delivered your post or not. If you select the "Private" tab, then we expect you to provide accounts and/or circles in the provided form fields. It should already be populated with your default permission settings, and if it's empty when you submit the post it should be visible only to you.

"Private mention" is just a private message with a single recipient, which we already offer as an action on the VCard on the left with the "Message" button.

**Comment by kr428** [comment]
@MrPetovan Thanks for outlining. I have a brief understanding of the technology behind, but am looking at it more through users eyes. From that perspective, direct messaging in the Fediverse is difficult already (try sending a Friendica "private message" to a Mastodon or Firefish contact...), and I somehow feel this "Mention" thing makes that even worse...

**Comment by MrPetovan** [comment]
I can't argue there, there are a lot of different concepts that intersect in confusing ways. But I didn't expect "mention" to be that controversial.

**Comment by kr428** [comment]
Wouldn't it be possible to auto-fill the "visible for" field with the mentioned user and make the post visible for recipients only, at least as default?

**Comment by MrPetovan** [comment]
No, that's not the intent of "Mention" at all. It's the intent of the "Message" button which loads in the relevant direct message page.

**Comment by kr428** [comment]
But Direct Messages don't work for recipients on Mastodon or Firefish at all. So at the moment a mention seems the only way for direct communication here...

**Comment by MrPetovan** [comment]
Then we should fix the existing Direct Message feature, not piggy-back off of a different one.

**Comment by kr428** [comment]
Hmm, ok, point taken. But still, does it make sense to have a mention addressed to be "visible by" jost one person to be sent out set to "followers-only"? Is this just a display error on Mastodon? It _seems_ in this cases the post gets delivered to only one instance but still this feels a bit ... confusing.

**Comment by MrPetovan** [comment]
This is an entirely different question about what visibility a post should have when none of the ACL fields are filled. In the code it's supposed to be for yourself only to prevent privacy leaks.

**Comment by kr428** [comment]
Ok, then I will close this one and see to write a better one for the mail system (and check the permissions for the posts closer).

**Comment by kr428** [comment]
(See #13627 for the DM issue.)
