### ISSUE TITLE
[Discussion] Default theme for new users

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13632]
I seem to remember that the "Blue" theme was the first theme in Frio. Even today, the "Blue" theme is the default for new users when they create a new account. 
The admin of an instance has the option of specifying a different theme, but this is rarely used.

---

When I compare this theme "Blue" with other available trio themes, I immediately notice the low contrast between the background and the links. 

![grafik](https://github.com/friendica/friendica/assets/44441246/5bab5b94-80f6-423a-a2c8-e51d9792fd22)

It takes a certain amount of concentration to distinguish the background from an embedded link, which I personally find very tiring.

I would therefore be interested to know whether it would not be time to offer a new or accentuated theme as standard for new users? My personal favourite is "Light accentuated".

Blue
![Screenshot 2023-11-12 at 07-40-00 ˈloma Matthias ✔ @ ˈloma](https://github.com/friendica/friendica/assets/44441246/62a706f0-dd58-46bd-87d1-7ce43473871d)

Hell akzentuiert
![Screenshot 2023-11-12 at 07-40-40 ˈloma Network](https://github.com/friendica/friendica/assets/44441246/f9bf47af-8103-4fd3-9c20-b58cd6e4ce3f)

Dunkel akzentuiert
![Screenshot 2023-11-12 at 07-41-10 ˈloma Network](https://github.com/friendica/friendica/assets/44441246/cbfca4f9-631c-4717-ad97-8b90a83720a2)

Schwarz akzentuiert
![Screenshot 2023-11-12 at 07-41-40 ˈloma Network](https://github.com/friendica/friendica/assets/44441246/35da7b93-52b7-4703-8f7c-52973cfab8b8)
 
All of these current themes have a much better contrast distance between the background and a link. This makes reading in Friendica much more pleasant and less tiring.

**Comment by haheute** [comment]
I agree. The links in "Blue" are hard to read, and my favourite of those 4 is the second. (Hell akzentuiert).

**Comment by foss-** [comment]
Wondering how useful it is to keep the legacy themes. Ideally user preference would be read from `prefers-color-scheme` on a per user basis and then the default color scheme would be light or dark accentuated.

An old website elaborating on contrast is https://contrastrebellion.com and kudos to @MrPetovan who picked colors with sane values for the accented themes.

And yes, `Legacy > Blue` is really painful on the eyes. It should not be something that can be selected by the user, nor should it be the default 😱
`Legacy > Koyu` has similar trouble with the left side menu text becoming unreadable. I am in favor of removing those unmaintained legacy themes.

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/pull/13948 sets Light Blue as the default Frio theme since the Legacy Blue scheme has been removed.
