### ISSUE TITLE
Wrong translation (Veranstaltungsdetails) 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13639]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Where "error details" or "error message" should be, it seems there is a wrong German 
translation, maybe for "event details" : It says "Veranstaltungsdetails".

### Steps to Reproduce

1.  go to the admin area
2.  open the log viewer
3.  open a log detail
4. look at the modal heading

Actual Result:

"Veranstaltungsdetails"

Expected Result:

maybe "Fehlerdetails" or "Meldungsdetails"
"Veranstaltung" means "event", but in the sense of a concert or something that you can visit

### Screenshots

![friendica-veranstaltungsdetails](https://github.com/friendica/friendica/assets/5753419/8dac1064-8ed4-4ec1-be5c-9c2f25dabad9)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2023.09-rc, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1539/1539 und die Post-Update-Version 1507/1507.

PHP version: 8.1.25

SQL version: Ver 15.1 Distrib 10.11.5-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by haheute** [comment]
maybe "Ereignisdetails", but I'm not sure where else that string is used... (if I should replace Veranstaltung with Ereignis, or if there need to be 2 different strings for 'Event' and 'Log Event')

**Comment by MrPetovan** [comment]
Thank you for looking into this, I would just like to make sure you intend on making translation changes on Transifex and not directly in the project file.

**Comment by haheute** [comment]
okay, yes.. I have looked in transifex, but I haven't touched anything ..

**Comment by Raroun** [comment]
This string occurs in
`src/module/Module/Calendar/Event/Form.php`
and
`src/Module/Admin/Logs/View.php`
It is String 875 in messages.po „Event Details“
I changed it to the German translation "Ereignisdetails" which fits both cases, as @haheute suggested.
