### ISSUE TITLE
Clones of the directory may be out of sync

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1363]
to be inverstigated

**Comment by tobiasd** [comment]
I think this is mostly a problem of the directories documentation as the syncing procedure is not well explained.

**Comment by Beanow** [comment]
With #3053 in mind, if there's anything I can help with here let me know.

https://github.com/Beanow/dir/tree/feature/redesign-prototype#how-syncing-works
Do you mean that syncing?

**Comment by AndyHee** [comment]
I suspect this can be closed with the new directory.
