### ISSUE TITLE
Frio: Photo caption prevents photo selection in the file browser 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13637]
- [X] I have searched open and closed issues for duplicates

### Bug Description

With the frio theme: When I add a photo caption (alt-text) it can happen that the photo can't be selected in the file browser. So it can't be posted, or added to a post. 

### Steps to Reproduce

1. open a photo in /profile/{{ username }}/photos and add a description text (=alt-text)..
2.  start to write a post with the post modal and try to add the photo by clicking it in the filebrowser
3.  if the alt text is long enough, you maybe cannot click the underlying photo because the text covers it all

#### Actual Result:

photo not clickable .. see screenshot

#### Expected Result:

maybe a click on the caption text could also add the photo to the post. or the caption must be smaller. not sure what to do

### Screenshots

![friendica-photobrowser-caption](https://github.com/friendica/friendica/assets/5753419/231528f2-0274-4f64-be2a-e826c37325d9)

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2023.09-rc, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1539/1539 und die Post-Update-Version 1507/1507."

PHP version: 8.1.25

SQL version: Ver 15.1 Distrib 10.11.5-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by Raroun** [comment]
We could shorten the caption if its more than x characters in the file browser.

**Comment by MrPetovan** [comment]
A better solution would make the caption also reactive to click in this context.

**Comment by Raroun** [comment]
I will do this if nobody else wants to :)

I will remove the Leftover from PR#13633 on Friday and will do this at the weekend.

**Comment by Raroun** [comment]
@haheute 
How did you add an alt-text in `/profile/{{ username }}/photos`?

**Comment by MrPetovan** [comment]
This caption in the browser isn't an alt-text, It's the name of the image file as it was uploaded.

**Comment by haheute** [comment]
Yes you are right. Perhaps I mixed it up with the captions inside an album, sorry: 

![friendica-caption-album](https://github.com/friendica/friendica/assets/5753419/b00d8315-cd3f-426a-a583-4d560f6f4d61)


In the filebrowser it really is the filename, but it also sometimes covers the whole thumbnail picture and makes it un-insertable.

@Raroun :  when you edit a photo, there is an input field for a description text. ("Bildunterschrift" in German)

**Comment by Raroun** [comment]
This isn't as easy as expected or I'm looking at the wrong places - anyway I'll do this but please bare with me :)

**Comment by haheute** [comment]
I like to look with grep or rg (ripgrep) .. just in case this info helps you :|

**Comment by Raroun** [comment]
I did it - but the filebrowser is something different. I'm switching between the template, JavaScript and php.
When you edit a photo it works as expected (the caption is clickable too) but in the file browser view it's different.
Probably it's a different div ¯\_(ツ)_/¯ 
I'll find out sooner or later:)

**Comment by Raroun** [comment]
This was a journey for me - i learned so much about the filebrowser, justified gallery and in general how everything is connected.
After all that, the solution was very simple. ¯\_(ツ)_/¯

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/13724
