### ISSUE TITLE
Twitter connector: Better help text for "Name of the Twitter Application"

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1364]
There is a help text, but I somehow didn't get it nevertheless. I'd like to clarify the help text. (Put in exactly the name you gave the app you created in Twitter to avoid duplicate posts or something like this.)

**Comment by silke** [comment]
Pull request submitted

**Comment by tobiasd** [comment]
closed via [friendica-addons/pull/240](https://github.com/friendica/friendica-addons/pull/240)
