### ISSUE TITLE
The preview mode for images cannot be changed

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13649]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The preview mode is permanently set to "no image". If a different selection is made, this will not be applied

![grafik](https://github.com/friendica/friendica/assets/44441246/1c9cc4b9-615b-4e84-a4ab-a2bf50fcd609)

### Platform Info

Friendica Version: 2023-09-RC 

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

https://github.com/friendica/friendica/pull/13646

**Comment by AlfredSK** [comment]
See also...
https://github.com/friendica/friendica/issues/13157#issuecomment-1815033582
