### ISSUE TITLE
Unicode Emoji defective (only limited usability)

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13662]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The emoji can only be used to a limited extent. 

For word concatenations such as :sun behind cloud:, the Unicode emoji is no longer rendered and no longer sent to the remote instances. 

Only the word chain :sun behind cloud: is transmitted on remote instances

There may be a connection with the issues https://github.com/friendica/friendica/pull/13635

### Screenshots
![2023-11-23_21-09](https://github.com/friendica/friendica/assets/44441246/acf9b63b-8497-42fb-9566-1bde0b58a22a)

### Platform Info

Friendica Version: 2023.09-rc

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by MrPetovan** [comment]
So, in order to better support single-colon emojis like `:p` and prevent them from being replaced in otherwise unrelated strings, we updated the emoji search feature to exclude non-words characters. This may have broken support for emojis with a space in them. I still believe the Friendica emoji system was poorly thought out (partly because Unicode emojis weren’t universally available) and should be overhauled to better match Mastodon’s system that’s more consistent with fewer false positives.

**Comment by loma-one** [comment]
Would it be a short term solution if I join the spaces with a _ like github does? 

---

No, it wouldn't be. The emoji are displayed incorrectly on remote systems

![grafik](https://github.com/friendica/friendica/assets/44441246/b4b2ecc0-23a2-4b5f-b514-5dfc5af2d99e)
![grafik](https://github.com/friendica/friendica/assets/44441246/31d7c194-acf7-439f-8315-1ebac461d797)

![grafik](https://github.com/friendica/friendica/assets/44441246/cbb73297-54ef-4b65-981d-dae52d1e66fa)

**Comment by MrPetovan** [comment]
Indeed, any change in the short codes will break backward compatibility, but it already depended on the relevant addons to be enabled anyway.

**Comment by loma-one** [comment]
The addon is activated on all instances on which I have a test account. It can at least be assumed that it is widely used.
- libranet.de
- nerdica.de
- loma.ml
- dis-le.de
- venera.social
- anonsys.net
- philos.fkn-systems.de
- squeet.me
- joinfriendica.de

**Comment by gudzpoz** [comment]
Ah, so I missed the `unicode_smilies` addon... The code can actually be easily modified to handle smilies with whitespaces. Besides the whitespaces, it *is* a bug that the code assumes all smilies to contain images, which of course fails for Unicode smilies relying on text substitution.

I should be able to provide a PR to fix this soon.
