### ISSUE TITLE
LDAPAuth not working anymore since last commit

### ISSUE THREAD

**Issue by esackbauer** [friendica/friendica#1367]
2 days ago there was a commit of Version 1.1 of ldapauth
Since then no user can login via LDAP anymore. Nothing was changed in Friendica configuration or Active Directory.

The only log entry I see:
2015-02-06 19:45:20@ae97k5jl6nsm3uxxxxxxxxx	[NORMAL]:auth.php:174:require	authenticate: failed login attempt: username from IP 10.1.1.2

My Active Directory logs an authenticate error: Unknown user name or bad password.

It seems Friendica does not deliver the credentials correctly.

**Comment by silke** [comment]
So, you think this commit broke it? https://github.com/friendica/friendica-addons/commit/31456b2f43daa3516300c69c4ad54d5468dece0c I'll try to test later today.

**Comment by fabrixxm** [comment]
@aymhce

**Comment by aymhce** [comment]
Sorry, i dont see issue with my commit. I have only add functions and just modify ldapauth_hook_authenticate main function.
If there is this message : "My Active Directory logs an authenticate error: Unknown user name or bad password."
I think the code stop here :
"     if(! @ldap_bind($connect,$dn,$password))
         return false;"

In state, it's running for me (openldap), however, I don't have Active Directory for test.
I will remake test later. At the moment I lack of time.

**Comment by aymhce** [comment]
@esackbauer 
hello, do you still have the problem (test with another account or ldap database) ? No problem on my side starting from a clean install of firendica and plugin.

**Comment by esackbauer** [comment]
Yes, still the same problem. I tried with different parameters, but it doesnt work.
It would help to log some more information in friendica, at what stage the LDAP auth fails.
I see only logging is enabled only for users auto-creating.

**Comment by aymhce** [comment]
@esackbauer 
hello, can you send me your config parameters please ?
Also if you want, you can test an older version plugin file... to see if the problem would come well from the new version.
https://raw.githubusercontent.com/friendica/friendica-addons/18903ade74ae274b50e69a48c23103368e2533db/ldapauth/ldapauth.php
(It would be copy to $friendica-directory-install/addon/ldapauth/ldapauth.php)

**Comment by esackbauer** [comment]
I have used this config:
$a->config['ldapauth']['ldap_server'] = '10.0.0.1';
$a->config['ldapauth']['ldap_binddn'] = 'ldap';
$a->config['ldapauth']['ldap_bindpw'] = 'password';
$a->config['ldapauth']['ldap_searchdn'] = 'OU=Benutzer,DC=domain,DC=org';
$a->config['ldapauth']['ldap_userattr'] = 'sAMAccountName';

With the old version it works. With the new one it does not work.

Logging I have up to debug level.
With old Plugin:
[DEBUG]:security.php:67:authenticate_success    auth_identities: Array

With the new Plugin:
[NORMAL]:auth.php:174:require   authenticate: failed login attempt: username from IP 10.0.0.2

**Comment by aymhce** [comment]
Ok, I have clean the code and fix a potential issue.
Can you test this new file please : https://raw.githubusercontent.com/friendica/friendica-addons/e5252af61bdfa17a402fcceab4aca934458c18c8/ldapauth/ldapauth.php

**Comment by esackbauer** [comment]
Yes, now it works!

**Comment by aymhce** [comment]
Ok, nice :)
I do a pullrequest : https://github.com/friendica/friendica-addons/pull/245

**Comment by fabrixxm** [comment]
closed by friendica/friendica-addons#245
