### ISSUE TITLE
[frio] Threads with many comment levels - indentation not capped at 7

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13693]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

There is a  display problem in threads with many levels of comments. Even with 'Smart Threading', the text becomes so narrow that it is hard to read. With a lot of comment levels, the text even slips outside the background box.

Happens on **desktop**. On mobile it's not ideal (looks pretty narrow, too. but much better) but the cap at level 7 seems to work.

### Discussion in Support Group

https://forum.friendi.ca/display/0b6b25a8-1065-6c38-9d28-b43199453613

### Steps to Reproduce

You need a thread with a lot of comments in many levels like this: https://venera.social/display/9ca7ab3e-49d138c622fc6c9c-66e47cbd

**Actual Result:**

In higher comment levels the text gets so narrow that it is hard to read. With a lot of comment levels, the text even slips outside the background box.

**Expected Result:**

The indentation should be capped at level 7. 

### Screenshots

![grafik](https://github.com/friendica/friendica/assets/3656054/ff9c99fb-3c13-4014-9489-b60fc5301530)

![grafik](https://github.com/friendica/friendica/assets/3656054/5b7829bb-b2f2-4cd3-92c5-d98fb3b4a649)

### Platform Info

Friendica Version:
2023.09-rc

Friendica Source: 
git

PHP version:
8.1

SQL version:
MariaDB 10.6

Browser:
Firefox 120 on Linux desktop

**Comment by MrPetovan** [comment]
I was able to fix the issue but I have to precise something. The maximum of 7 is for the thread level which starts as 1 for the top-level comment. Since the 1st level comment (with thread level 2) doesn't have any indentation, the fix caps the indentation level at 5 (at thread level 7).

Is this intended? Should the indentation level reach 7?

Indentation level capped at 5
---------
![2023-12-07 08 15 23 dev-friendica mrpetovan com 74b8477942cb](https://github.com/friendica/friendica/assets/925415/4cf2ac44-6f78-4837-baa6-011e13ebc1ea)

Indentation level capped at 7
--------
![2023-12-07 08 14 38 dev-friendica mrpetovan com dff8bd029ddc](https://github.com/friendica/friendica/assets/925415/932cee5d-1dab-4ff6-85ad-86971be0693a)

**Comment by MrPetovan** [comment]
Aside: Trying to import the hilariously long retro.social thread on my dev node ended in a Fatal error triggered by XDebug infinite recursion protection. After that, I wasn't able to recover a correct threading even by importing the thread by smaller chunks. Some replies lost their parent relationship forever even after I added their parent, and some replies are forming their own top-level conversation alongside the actual top-level conversation.

I tried to delete the orphan replies and re-import them, but now I'm getting a 404 errors for their related `/display/<guid>` pages even if the replies themselves still show in the conversation. Do you know what's going on @annando ?

<details>
<summary>Long screenshot</summary>

![2023-12-07 08 22 27 dev-friendica mrpetovan com 43600554de9e](https://github.com/friendica/friendica/assets/925415/7c307371-d845-4783-96c2-deb2049f0423)

</details>

**Comment by AlfredSK** [comment]
> Please weigh in on the max indentation level dilemma

@MrPetovan Do you mean which one I like best - capped at 7 or 5? What is the dilemma?

**Comment by MrPetovan** [comment]
I thought thread level was the same as indentation level but they aren’t so we have to decide whether the thread level is capped at 7 (capping indentation level at 5) or the indentation level is capped at 7 (capping thread level at 9).

So it really is which one you like the best.

**Comment by AlfredSK** [comment]
Ok. The second screenshot of 'Indentation level capped at 7' looks ok for me.

Is the thread publicly available? I'd like to check it on various devices.

**Comment by MrPetovan** [comment]
Here you go: https://dev-friendica.mrpetovan.com/display/b5f438f2-6365-71c1-61eb-c1e990486245

If you want the same cascade, you’ll have to import all the “B” replies.

**Comment by AlfredSK** [comment]
Thanks! I think it looks perfectly fine now.
