### ISSUE TITLE
table 'dsprphotoq' has no 'IF NOT EXISTS' in database.sql

### ISSUE THREAD

**Issue by txt-file** [friendica/friendica#1370]
When I tried to install friendica I ran in an error ```ERROR 1050 (42S01) at line 250: Table 'dsprphotoq' already exists```
The other tables have ```IF NOT EXISTS``` written in the command. This is the only table I found which does not have this statement.

**Comment by annando** [comment]
How have you installed the system? The file database.sql shouldn't be in use anymore.

**Comment by txt-file** [comment]
I used the installer but the sql scripts returned with some errors that
it was unable to execute some "ALTER TABLE" statements. On this error
page was written that I might try import the database via mysql import.
This is what I did.

**Comment by fabrixxm** [comment]
options:
- we keep database.sql updated
- we delete database.sql and remove any mentions of it

**Comment by annando** [comment]
I would like to remove it - if we are really sure that there is no scenario where this would be needed.

**Comment by annando** [comment]
The file "database.sql" is used in some way in the mailstream and the retriever-addon. I guess we can remove it from there. Question is, how we can do some fallback mechanism if the automatic process fails. I could try to write a script that automatically generates the database.sql from the dbstructure.php. That maybe is the best idea.

**Comment by annando** [comment]
I guess I will write some code so that the file can be created from the defined structure. I'm not sure when I can do this, since I'm still at a customer for this (and maybe next) week.

**Comment by fabrixxm** [comment]
I'll take a try, if it's ok for you

**Comment by annando** [comment]
Feel free! There is one function in dbstructure.php that was left behind by me that once did that job: "print_structure". It is not complete and I don't find any traces how I called it before.

**Comment by annando** [comment]
... another bug bites the dust ...
