### ISSUE TITLE
can't import threads.com posts by searching for their url

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13719]
Wanted to block the new kid on the block: threads.com

So went ahead and looked for a post to open in friendica so that I could select `… > Ignore "Threads.com" server`.

But after copying `https://www.threads.net/@zuck/post/C01LXhDrCAM` into the top search field and pressing enter, friendica says `no results`.

MrPetovan added the suspicion this may be lacking support for nodeinfo or webfinger - to give a hint where to first check.

Not sure if this can be worked around. Guess I'll just have to wait for the first threads.com post in my timeline to then ignore that server.

**Comment by sekretaerbaer** [comment]
I have tried to access the threads accounts of Zuck and Mosseri from several Friendica and Mastodon instances. It never worked, so I suspect that it may also be due to Threads itself that the accounts are not found. 

Edit: on mastodon.social I can at least find `@mosseri@threads.net`.

**Comment by HankG** [comment]
I tried as well with similarly unsuccessful results with  @mosseri@threads.net as well. I also tried loading the link from a URL using:

https://www.threads.net/@mosseri/

and 

https://threads.net/@mosseri/

Those also brought up no results.

**Comment by ne20002** [comment]
Several Mastodon instances ... Checked if threads.net is maybe in the servers blocklist?

**Comment by HankG** [comment]
> Several Mastodon instances ... Checked if threads.net is maybe in the servers blocklist?

I double checked it wasn't on the blocklist of the server I maintained and confirmed it is not.

**Comment by ne20002** [comment]
I tried with my mastodon.social account and was able to search for and to follow and unfollow @mosseri@threads.net.

**Comment by ne20002** [comment]
On my Friendica server I can resolve threads.net (Ipv4 and IPv6). Friendica does not find the user. I have two entries in log file:

1. Key could not be fetched in HTTPSignature.php 	759 	fetchKey for Key: `https://www.threads.net/ap/users/threads.sys/`
2. No valid network found in Contact.php 	1381 	getIdForURL for URL: `mosseri@threads.net`

The page in `https://www.threads.net/ap/users/threads.sys/` gives an error in the browser.

**Comment by annando** [comment]
The URI of Threads posts and their web link are very different:
```
> select uri,plink from `post-view` where guid = '9fd1d7c3-38c67c16a3b9f5dd-57cd9d5f';
+------------------------------------------------------------------+---------------------------------------------------+
| uri                                                              | plink                                             |
+------------------------------------------------------------------+---------------------------------------------------+
| https://www.threads.net/ap/users/mosseri/post/17932554806790742/ | https://www.threads.net/@mosseri/post/C01zMgWp4V- |
+------------------------------------------------------------------+---------------------------------------------------+
```

Also you don't see the post, when you enter the URI. So I guess that you won't be able to fetch a Threads post by entering their web link.

**Comment by foss-** [comment]
Was able to search for `@mosseri@threads.net`. Follow, unfollow and Ignore threads.net server was now possible. Thanks for the fix.

**Comment by ne20002** [comment]
I also was able to search, follow and unfollow. But there is still things to do (maybe on Threads side): 
* I don't get a picture (which is working with mastodon.social)
* Profile URL in Friendica is still `https://www.threads.net/ap/users/mosseri/` which leads to empty page in threads

**Comment by annando** [comment]
The picture problem is solved with https://github.com/friendica/friendica/pull/13723

**Comment by ne20002** [comment]
I confirm the picture problem is solved.

**Comment by lapo-luchini** [comment]
> Was able to search for `@mosseri@threads.net`. Follow, unfollow and Ignore threads.net server was now possible. Thanks for the fix.

Am I missing something in the configs?
When I try  `@*@threads.net` I get always the same 3 results:

![image](https://github.com/friendica/friendica/assets/420454/ddb01acd-fa08-48b1-9fed-bc5ffae32cde)

but if I try from the contacts page I get this instead:

`The network type couldn't be detected. Contact can't be added.`
