### ISSUE TITLE
[frio] Long handles prevent a clean display of common contacts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13710]
- [x] I have searched open and closed issues for duplicates

### Bug Description
If two profiles are on the same server, an icon list of the shared contacts is displayed when the URL https://domain.ltd/profile/[USERNAME]/conversations is called. The name of the user is listed under the UserIcon. 
For handles with more than 10-12 characters, the adjacent UserIcon is moved. 
The result is an unsightly patchwork of differently arranged icons.

In my opinion, the name is not relevant. This is already displayed as a mouseover. The name of the user under the UserIcon should therefore be removed

Actual Result:

The icons are arranged inconsistently

Expected Result:

The icons are displayed uniformly. The name of the user is no longer displayed.

### Screenshots
![2023-12-10_10-28](https://github.com/friendica/friendica/assets/44441246/4603eae2-99c4-4afb-befe-eda065ba4649)

### Platform Info

Friendica Version: 2023.09-rc

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by Raroun** [comment]
I want to do this. I probably would not remove the the names because of mobile users but I will find a solution.

**Comment by MrPetovan** [comment]
A simple solution is to move the display name to the right of the profile picture where it can spill over a few lines because of the picture height. Then it's a matter of deciding how many of these boxes should fit on a single row depending on the available width. I assume [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) could be your friend in this case.

**Comment by Raroun** [comment]
this is planned for next weekend - i´ll go with the grid :)

**Comment by Raroun** [comment]
This wasn´t as easy as expected too, because of the div-structure in `remote_friends_common.tpl` which is used in other themes.
Displaying the names besides the Avatars looked very strange, so i did the classical view - names under the Avatars.
