### ISSUE TITLE
Big empty box under images since 2023.12

### ISSUE THREAD

**Issue by johnassel** [friendica/friendica#13766]
Hi,
I just updated to 2023.12 and noticed a big empty box under images.#
This did not occur in previous versions.

- [x] I have searched open and closed issues for duplicates

### Bug Description
All images are having an empty box underneath approximately the same size as the picture:
![2023-12-25_18-04](https://github.com/friendica/friendica/assets/827399/d0dc71a1-20f7-4b46-a21c-7bef9eef39e6)

This didn't happen in the previous stable versuon

I tried a bit around and the bug seems to be in
view/templates/content/image/single_with_height_allocation.tpl

changing
`<figure class="img-allocated-height" style="width: {{$allocated_width|default:"auto"}}; padding-bottom: {{$allocated_height}}">`
to
`<figure class="img-allocated-height" style="width: {{$allocated_width|default:"auto"}}; padding-bottom: 0px">`

makes the box disappear.

Or is there an other tweak to fix this?

### Platform Info

Friendica Version: 2023.12

Friendica Source: GIT

PHP version: 8.2.13

SQL version: 10.5.23

**Comment by MrPetovan** [comment]
Please clear your browser cache. It should have been cleared automatically when you upgraded to the latest version though.

**Comment by johnassel** [comment]
Ah yes - clearing the cache fixed the issue! 
Thank you!
