### ISSUE TITLE
FediTips not moved

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13776]
FediTips has moved to a new server as announced here:
https://mstdn.social/@feditips/111591592022237601

On my instance the move has not been processed. Also when searching for the new account, nothing is found.

Is this only my problem or is someone else affected?

**Comment by foss-** [comment]
Did a test search for `https://social.growyourown.services/@FediTips` on pirati.ca in the top search box and the account was found.

Does that not work for you? And if not, can you share details about the friendica version you are running.

**Comment by ne20002** [comment]
Yes, it is doing it this way.
But inside my Friendica, going to search people page and entering @FediTips@social.growyourown.services does not find it.

I managed to follow it as an rss but I still don't get it to follow the AP account.

**Comment by foss-** [comment]
Search for `@FediTips@social.growyourown.services` works fine on two friendica instances. Which version are you using?

**Comment by ne20002** [comment]
Latest one.
![grafik](https://github.com/friendica/friendica/assets/39007279/aba32238-9b83-418b-9937-0c2bd926b774)

**Comment by foss-** [comment]
Your instance is: `This is Friendica, version 2023.12 that is running at the web location https://fedi.0x42.ch. The database version is 1542/1542, the post update version is 1507/1507.`
(you can find the version info in Help > Site/Version Info)

Unable to reproduce in `This is Friendica, version 2024.03-dev that is running at the web location https://squeet.me. The database version is 1542/1542, the post update version is 1507/1507.`

**Comment by ne20002** [comment]
Ok, I close this one as (hopefully) fixed in next version.

**Comment by foss-** [comment]
You could try to update to dev and see if that indeed resolves the problem. If not, this needs to be investigated further.
