### ISSUE TITLE
Create an option to select between people you follow and people who follow you in the "Contacts not in any circles" tab

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13787]
In contacts > Circles it lists all "Contacts not in any circles"
Unfortunately it also includes people who follow you but you don't follow and if you wanted them in a circle you be following with them.  So to see all of the people who I follow and aren't in circles already I have to create circles just of people I don't follow to get them out of that menu.  While technically they are contacts, pretty sure no one is going to be putting them in circles or they would be following them

**Comment by annando** [comment]
You can create circles for different purposes. It is not only to filter for people to follow, but you can also control the contacts that you want to send your content to.

**Comment by anubis2814** [comment]
That makes sense I forget that's an option.  Could you make an option to select between people you follow and people who follow you?  Would probably be more what I want here.

**Comment by annando** [comment]
You mean something like that?
![image](https://github.com/friendica/friendica/assets/844208/6892be45-ffd7-48ea-a131-aea24f58b43a)
I just coded it. it is one of the branches for the next release:
![image](https://github.com/friendica/friendica/assets/844208/59e03a56-23ab-4949-a078-1a6bc8edfe5a)

**Comment by annando** [comment]
Fixed by https://github.com/friendica/friendica/pull/14016
