### ISSUE TITLE
Update trashed my Friendica Installation.

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#13784]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

After updating to the most recent release, when I go to the DB updates page I get the following error:
 Warning: include(): Failed opening '/space/www/friendica/addon/monolog/vendor/composer/../psr/log/Psr/Log/LogLevel.php' for inclusion (include_path='.:/usr/share/php') in /space/www/friendica/vendor/composer/ClassLoader.php on line 444 
Also unable to display images, moderation and admin menus are missing.  It is totally fuxored, thanks.
### Steps to Reproduce

1.  step one
Update to most recent release
2.  step two
Go to db updates page.

Actual Result:

 Warning: include(): Failed opening '/space/www/friendica/addon/monolog/vendor/composer/../psr/log/Psr/Log/LogLevel.php' for inclusion (include_path='.:/usr/share/php') in /space/www/friendica/vendor/composer/ClassLoader.php on line 444
Expected Result:

No errors.  Seems like every update introduces new bugs rather than fixes them.
Also not displaying images any more.
### Screenshots
![Screenshot at 2023-12-31 01-53-46](https://github.com/friendica/friendica/assets/3466797/2b133c2a-c454-4136-9dda-30c2ac91c5a9)

### Platform Info

Friendica Version:

Help menu is missing now, can only get there through Admin->Oveview
     Friendica 'Yellow Archangel' 2024.03-dev - 1543 
Friendica Source: 
Github
PHP version:
  PHP 8.0.30 (cli) (built: Sep  2 2023 08:05:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
SQL version:
mariadb  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by AlfredSK** [comment]
> Friendica 'Yellow Archangel' 2024.03-dev - 1543

You didn't upgrade to the 'most recent release' but to the current develop version. Apart from that, did you update the addons to the `2024.03-dev` version as well? An did you execute the dependencies update via  `bin/composer.phar install --no-dev` after switching the branch to develop?

**Comment by 4nanook** [comment]
I've been using the development branch all along, didn't recently switch.

      I did the following:

 	su - friendica
 	(That puts me in friendica's home directory)
 	git pull
 	bin/composer.phar install --no-dev

      Then for the add-ons I did:

 	cd addon
 	git pull

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
I am also getting the following in my Apache PHP logs:
[Sun Dec 31 02:36:26.475338 2023] [:error] [pid 3795:tid 140192456562240] [remote 51.222.253.17:35860] PHP Warning:  include(/space/www/friendica/addon/monolog/vendor/composer/../psr/log/Psr/Log/LogLevel.php): Failed to open stream: No such file or directory in /space/www/friendica/vendor/composer/ClassLoader.php on line 444

**Comment by 4nanook** [comment]
Seeing that addon/monolog was missing a file, I disabled monolog in the addons, still getting a shitload of errors but that at least brought the admin and moderation menus back.  Still no help menu.  The error I am getting now is:
[Sun Dec 31 02:40:42.330388 2023] [:error] [pid 3794:tid 140192431384128] [remote 51.222.253.17:39424] PHP Warning:  Trying to access array offset on value of type null in /space/www/friendica/src/Module/Conversation/Community.php on line 136

**Comment by 4nanook** [comment]
Disabling monolog also brought back images.

**Comment by haheute** [comment]
Do you also run the bin/dbstructure.... command when updating? I could Post my Update Script If you are interested when I am again at the Computer . I Dont remember the exact commands now.. using a smartphone .

**Comment by 4nanook** [comment]
This is what lead me to go to the dbstructure command in the first place, I am used to the update doing that automatically, but it had not been done.  Now when I look there is no dbstructure command in the bin directory.
However, when I got to dbupdates, now that I've disabled monolog, and click on check db updates, I get this:

Database structure update 1543 was successfully applied.
Database: 0/0, Network: 0, Rendering: 0, Session: 0, I/O: 0, Other: 0.36, Total: 0.36
Class-Init: 0.107, Boot: 0.021, Init: 0, Content: 0.223, Other: 0.013, Total: 0.364

But I'm still getting the same error:
[Sun Dec 31 03:38:47.142653 2023] [:error] [pid 127788:tid 140181457843776] [remote 51.222.253.11:36670] PHP Warning:  Trying to access array offset on value of type null in /space/www/friendica/src/Module/Conversation/Community.php on line 136

Which strongly suggests an error in Community.php as opposed to a database error.

**Comment by tobiasd** [comment]
pinging @nupplaphil as he works on the Monolog

**Comment by haheute** [comment]
I have these 2 commands (regarding the database) in my update script: 

`bin/console dbstructure update`
`bin/console postupdate`

they sometimes change things or create new tables, i believe.. maybe try to run them.. information is here: https://wiki.friendi.ca/docs/tools

**Comment by 4nanook** [comment]
I tried them but now get this error:

[Sun Dec 31 05:46:02.291056 2023] [:error] [pid 1353954:tid 140192490133056] [remote 54.36.148.166:35105] PHP Warning:  Trying to access array offset on value of type null in /space/www/friendica/src/Module/Conversation/Community.php on line 136

,,, which other than being a different IP address, is same.

**Comment by 4nanook** [comment]
I take it this error is on ignore?  I've just turned off visible errors so users don't see them, it isn't obvious to me what this code does that is broken because it appears to be working save for this error and the monolog plugin not working, which does not matter to me as I have my own way of handling logs.

**Comment by 4nanook** [comment]
I missed the notice on the manual change to .htaccess.  I applied that change and recent updates and the errors are now gone so I am closing this issue.
