### ISSUE TITLE
[frio] A "01" next to each checkbox

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13818]
### Bug Description

Using the Frio theme, I see a `01` next to each checkbox in the settings area.

### Steps to Reproduce

Update to latest dev version and open the settings.

### Screenshots
![friendica-01](https://github.com/friendica/friendica/assets/5753419/8a03e2af-6313-4db8-9a46-d3e4604728e6)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2024.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1545/1545 und die Post-Update-Version 1544/1544.

PHP Version: 8.2.14

MySQL: Ver 15.1 Distrib 10.11.5-MariaDB

**Comment by MrPetovan** [comment]
Caused by https://github.com/friendica/friendica/pull/13807

See https://github.com/toddy15/friendica/blob/6fd057fd00b5ace830a87b1fcf32b0c2b718fa62/view/theme/frio/templates/field_checkbox.tpl#L5

**Comment by MrPetovan** [comment]
Paging @toddy15

**Comment by toddy15** [comment]
Oops, sorry about that. From a quick look at this commit, it seems to be the only edit error. Are you going to fix this or should I send a PR? It'll take me about three hours to get to that, I am quite busy currently.

**Comment by haheute** [comment]
I can try. (if you mean me)

**Comment by MrPetovan** [comment]
Anyone can take it, it's a simple fix, and it isn't urgent.

**Comment by haheute** [comment]
ok.. then I do it
