### ISSUE TITLE
Public forums with manual contact request approval

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#13812]
### Is the feature request related to a problem? Please describe.

Public forums are hardwired to accept every contact request.
Forums are often abused by bots and test accounts that remain forever, because Friendica doesn't have a proper cleanup procedure.

### Describe the feature you'd like

There should be an option for public forums, that you are able to change the default behavior for contact requests to manually.

### Describe alternatives you've considered

Close and don't use forums.

**Comment by annando** [comment]
@hoergen Please test it out if there are any quirks.

**Comment by hoergen** [comment]
Works great. Thank you !
