### ISSUE TITLE
Hide circle posts from main timeline

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13817]
Mastodon has an interesting feature that comes in handy quite once in a while: In there (not sure whether it's a feature of Mastodon server or just its web frontend), I am able to add users to a list and then hide all posts from users in this list from the main timeline. On Friendica, it seem /network generally does display posts by _all_ users. Really would be good to have a way to hide posts from (groups of) users from /network without having to unfollow or mute them.

**Comment by annando** [comment]
I currently have the idea of a new feature where contacts could be their own channels. For example you then could enable this option on the helpers group. This then would create a new channel with the name of the group and would hide that contact from the network page itself.

It's not exactly what you asked for, but could this help as well? What is exactly your use case?

**Comment by tobiasd** [comment]
Duplicate of #12999 I think

**Comment by kr428** [comment]
Ah. Yes. Seems a duplicate. Naming apparently was too obvious for me to find. 😬
My main idea is to keep a certain amount of structure in my contacts, and I'd like to have people whose posts I always and generally see by default as easy as somehow possible whereas others should be left accessible without being displayed in my standard stream. Currently (as of now) I solve this by creating a circle and a channel from that particular circle and set this to be my local starting page when accessing Friendica web via browser, but that doesn't work for the "Home" timeline in clients such as tusky or fedilab.

**Comment by kr428** [comment]
I'll close this off as a duplicate by now, seems #12999 is sufficient here.
