### ISSUE TITLE
"Do not use OEmbed" without function

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13819]
- [x] I have searched open and closed issues for duplicates

### Bug Description

"Do not use OEmbed" is activated, but OEmbed from Youttube and other services are still directly integrated if the link is not removed before a post is sent.
This means that an unnecessary amount of information about the user and everyone else who clicks on this link is passed on to third parties. I therefore consider this to be a serious data protection problem.

Is there possibly an opposite setting that allows the embedding of Youttube or other services?

### Steps to Reproduce

1. copy a link from Youtube
2. have the image preview generated
3. check the post in the preview
4. send the post without removing the link to YouTube

Actual Result:

An image preview + the "OEmbed" viewer from Youttube is displayed

Expected Result:

An image preview is displayed. Instead of an OEmbed Youtube Viewer, only a link is sent.

### Screenshots

Preview
![2024-01-10_16-55](https://github.com/friendica/friendica/assets/44441246/d6cb170a-447d-4037-a483-82ddd4c9b242)
Post sent

![Screenshot 2024-01-10 at 17-18-43 (1) ˈloma Network](https://github.com/friendica/friendica/assets/44441246/ec3191e4-11a2-453f-b51f-79e0a239333c)

### Platform Info

Friendica Version: Stable

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
Directly below this setting to disallow OEmbed, you can add a bunch of domains for which you can allow it.

**Comment by loma-one** [comment]
That's the point. I don't want to allow it for any domain. Especially not the embedded player from youtube.
Is there a setting I have overlooked that will allow me to achieve this?

**Comment by annando** [comment]
![grafik](https://github.com/friendica/friendica/assets/844208/30527017-b68f-4d91-91da-2b21bfc7e98a)

**Comment by loma-one** [comment]
Many thanks for the hint. We are probably writing at cross purposes ;)
I'm not talking about releasing a domain that is allowed to embed third-party code. It's about putting the Youtube player on a banned list. The player should not be integrated. Only a preview with an external link should be sent.
![2024-01-11_11-39](https://github.com/friendica/friendica/assets/44441246/c1345b74-6e21-47b5-99de-66be3ed58685)



Ich kann mich daran erinnern, dass das bis zum 2023.05 funktioniert hat.
