### ISSUE TITLE
Option for blocking "summarize & reshare" accounts as node admin or/and as user

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#13813]
### Is the feature request related to a problem? Please describe.

More and more people setting up accounts to automatically reshare and distribute commercial mass posters. The source is currently rss feeds but it is planned to reshare grouped hashtags. This can lead to a flood of spam in the timelines.

### Describe the feature you'd like

To avoid having timelines scrolling with lightspeed because you following "the wrong hashtags" that are used (abused) by mass posters there need to be a deny/allow feature to automatically block such accounts.
On one hand blocking it on a sever level and/or on the other hand on user level

### Describe alternatives you've considered

- Blocking Servers completely that setting up such spam accounts
- Leaving the fediverse

### Additional context

**Comment by annando** [comment]
How should the system automatically detect RSS/Atom mirror accounts that fall into the category you specified?

Considering "it is planned to reshare grouped hashtags": This is not how the channel relay works. The channel relay simply reshares posts, it doesn't create any new posts. So when you don't follow these accounts, it won't have got any impact on you other than possibly a notification that one of your posts had been reshared, if that meets some channel definition.

**Comment by hoergen** [comment]
So there is no way that those accounts can be abused to spam the timelines?

**Comment by annando** [comment]
Since they don't create new posts, but only reshare them, this shouldn't be the case. I deliberately avoided to do this with Diaspora posts, since a reshare there would indeed create a new post.

**Comment by annando** [comment]
To further reduce any possible impact, with PR https://github.com/friendica/friendica/pull/13866 the reshare itself is now a "followers only" post. I think this makes this issue solved?

**Comment by hoergen** [comment]
Great thank you :+1:
