### ISSUE TITLE
Link to sharkey profile

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13828]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I am not sure what this is... The link to a sharkey user's original profile is displayed in this format: https://shk.mv2k.com/users/9ofxdx9pas0l0001 (in the hovercard).

That shows me some JSON data instead of the profile page.

It seems the right link would be: https://shk.mv2k.com/@memo

I use the Frio theme.

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2024.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1545/1545 und die Post-Update-Version 1544/1544.

Friendica Source: github

PHP version: 8.2.14

SQL version: Ver 15.1 Distrib 10.11.5-MariaDB

**Comment by MrPetovan** [comment]
According to the probe of the URL `https://shk.mv2k.com/@memo`, the canonical URL of this profile is indeed `https://shk.mv2k.com/users/9ofxdx9pas0l0001`:
```
Array
(
    [name] => Memo
    [given_name] => 
    [family_name] => 
    [nick] => memo
    [guid] => 
    [url] => https://shk.mv2k.com/users/9ofxdx9pas0l0001
    [addr] => memo@shk.mv2k.com
    [alias] => https://shk.mv2k.com/@memo
    [photo] => https://mv2k-sharkey.s3.fr-par.scw.cloud/files/985ac03f-ead8-4394-892b-fd7c5f74de06.webp
    [photo_medium] => 
    [photo_small] => 
    [header] => https://mv2k-sharkey.s3.fr-par.scw.cloud/files/109cb705-aacc-4473-9350-fcfa95dd860c.webp
    [account-type] => 0
    [community] => 
    [keywords] => 
    [location] => 
    [about] => Ich bin zurzeit oft draußen in der [url=https://shk.mv2k.com/tags/Natur]#Natur[/url] und nicht im [url=https://shk.mv2k.com/tags/Internet]#Internet[/url] unterwegs, und poste deshalb hier auch weniger.

Durch die Einflüsse des [url=https://shk.mv2k.com/tags/Klimawandel]#Klimawandel[/url]⁣s wird wohl innerhalb weniger Jahre vieles zerstört werden.
    [xmpp] => 
    [matrix] => 
    [hide] => 0
    [batch] => https://shk.mv2k.com/inbox
    [notify] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/inbox
    [poll] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/outbox
    [request] => 
    [confirm] => 
    [subscribe] => https://shk.mv2k.com/authorize-follow?acct={uri}
    [poco] => 
    [following] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/following
    [followers] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/followers
    [inbox] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/inbox
    [outbox] => https://shk.mv2k.com/users/9ofxdx9pas0l0001/outbox
    [sharedinbox] => https://shk.mv2k.com/inbox
    [priority] => 0
    [network] => apub
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp9hp+FFgmXHdaF8N765o
fPt8qeFDLa//6PXOhpqAn/GXnMiVoOAIn9dzelfpBQjuJbA3L18Ewn/iLq8cYIHt
XROA4IQsR/QDg/AXYMGT8ZJ2NUOSezVndWYG+bBHDMVCvlX7ULoQCGh+k2iiC8Km
hgDIGkefkMBwgQhTaijKGiPhKhJwdccZ46pTX++WZezkRHM6+gyvrfGSrnacPdfY
CODK0qk7o6JXvSg1mJDpG0x7aSpS9+xkFL63U6zh1jyWIcxSlqkKdalB5sla/mUV
rbtdqLEPV83QESl/LZoeiqhxXLRAOmeU6Mahu0Zn2BRyWlg6RRqEsBtPXfhSupbG
wwIDAQAB
-----END PUBLIC KEY-----
    [manually-approve] => 0
    [baseurl] => https://shk.mv2k.com
    [gsid] => 19536224
    [networks] => Array
        (
        )
)
```
The beautified URL is listed under `alias` which we don't use to show profile URLs. Ideally, both URL would be exchanged but we can't make this decision by remote platform at the moment.

**Comment by annando** [comment]
Concerning AP, the endpoint that we store at `url` represents the technical endpoint, while we store the HTML endpoint at `alias`. We should always display `alias`, but due to some legacy reasons we don't.

**Comment by MrPetovan** [comment]
Huh, so there is a fix.

**Comment by haheute** [comment]
On my smartphone, the link seems to work.. leads me to the profile. But on my Laptop, not, shows me only json output..
