### ISSUE TITLE
[Addon] Advanced content filters cannot be created, edited, activated, deactivated or deleted

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13822]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The Advanced content filters add-on does not allow editing. It cannot be used to create or edit new rules or to activate or deactivate existing rules. It is also not possible to delete rules.
Tested on loma.ml., libranet.de, opensocial.at

### Platform Info

Friendica Version: stable

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by MrPetovan** [comment]
Any error showing up in either the console or the PHP log?

**Comment by loma-one** [comment]
`app [ALERT]: Fatal Error (E_COMPILE_ERROR): Declaration of Slim\Container::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool {"code":64,"message":"Declaration of Slim\\Container::has($id) must be compatible with Psr\\Container\\ContainerInterface::has(string $id): bool","file":"/var/www/html/friendica/addon/advancedcontentfilter/vendor/slim/slim/Slim/Container.php","line":160,"trace":null} - {"file":null,"line":null,"function":null,"request-id":"65a03376538d6","stack":"ErrorHandler::handleFatalError","uid":"cab47b","process_id":3190375}`

**Comment by MrPetovan** [comment]
Thanks!

**Comment by MrPetovan** [comment]
Addressed in https://git.friendi.ca/friendica/friendica-addons/pulls/1455

I had to migrate the addon to Slim version 4 because version 3 will not receive PHP 8.2 deprecation fixes.
