### ISSUE TITLE
call to Mastodon mutes endpoint returns unprocessable entity error

### ISSUE THREAD

**Issue by technicat** [friendica/friendica#13823]
- [X] I have searched open and closed issues for duplicates

### Bug Description

The Mastodon API mutes endpoint

https://docs.joinmastodon.org/methods/mutes/

returns an error

```json
{
"error" : "Unprocessable Entity"
}
```

I believe it's due to this code in Mutes.php

```php
if (empty($this->parameters['id'])) {
			$this->logAndJsonError(422, $this->errorFactory->UnprocessableEntity());
		}
```

which is expecting a parameter not in the spec and not in the analagous blocks query in Blocks.php, which works fine (see screenshots for a side by side mutes vs blocks comparison)

### Steps to Reproduce

1.  go to fedicat.com and click on the Apple icon to get a testflight build of my fediveres app
2.  login to a friendica account (I'm using friendica.opensocial.space), mute and block some accounts
3.  in the left menu, under Filters, view the muted and block account lists
4. Any Mastodon client that displays the muted account list should exhibit similar behavior, e.g. Manny displays the list of blocked accounts fine and does not display an error for the muted account list but also does not display the correct list

Actual Result:

Displays an HTTP error (the above json error is from debug console output)

Expected Result:

No error and a display of the muted accounts

### Screenshots

![IMG_5466](https://github.com/friendica/friendica/assets/1530082/b0601407-ae5b-42cb-a24e-09dacee2904e)
![IMG_5467](https://github.com/friendica/friendica/assets/1530082/6a0b5cce-07b1-4434-9f6d-c0c6c8c7f28d)

### Platform Info

Friendica Version:

2024.03.-dev

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
@HankG Do you want to take this one?
