### ISSUE TITLE
[mastodon-api] Use channels not circles for list feature?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13821]
Mastodon (API) offers the idea of user lists which are supported by most client. Friendica Mastodon API implementation so far maps these to circles (formerly groups). With the channels feature being available in 2023.12 and already by now much more powerful than circles in many regards, would it be possible to expose channels not circles as "lists" to Mastodon API clients?

**Comment by annando** [comment]
I already thought about it. This would be some work, but not impossible.
