### ISSUE TITLE
External profile image URL wrongly redirect to default avatar URL for all-digits usernames

### ISSUE THREAD

**Issue by justdaj** [friendica/friendica#13837]
I've just setup a new sever (using the Yunohost app).  When I follow someone on another server, the user only sees the default avatar and not my actual profile photo. Similarly, if someone searches for me from another server to follow me, they do not see my profile photo; all the other profile info is shown.

Is there anything I can check?  thanks

Friendica, version 2023.05.

Thanks

**Comment by MrPetovan** [comment]
Do you mind providing your profile URL to enable us to check independently?

**Comment by justdaj** [comment]
sure:  `@007@talkbox.social`

**Comment by MrPetovan** [comment]
I have the feeling it has to do with your username being all digits. The URL for your avatar on your local node is https://talkbox.social/photo/contact/300/14640056-2665-a69f-1591-df3797874667 and it works, but the URL for your avatar for remote purposes is https://talkbox.social/photo/profile/007.png which is correct for your profile but it redirects to the default avatar image.

**Comment by justdaj** [comment]
Interesting.  Let me create another non-numeric user as a test

**Comment by justdaj** [comment]
Yeah, if I create a user with letters in the username the avatar is shared.  🤔

Bug?

**Comment by MrPetovan** [comment]
Definitely a bug. Let me rename and re-categorize this issue.

**Comment by tobiasd** [comment]
For nicknames the requirement from the documentation is 

> Due to the way that the nickname is used, it has some limitations. It must contain only US-ASCII text characters and numbers, and must also start with a text character..

see [account basics](https://github.com/friendica/friendica/blob/develop/doc/Account-Basics.md#nickname)

**Comment by MrPetovan** [comment]
Ha, so we do not enforce this in the code. Should be a quick add in the `Register` module.
