### ISSUE TITLE
"Inspect deferred workers" has counter 999, in database all entries have a retry value greater than 10

### ISSUE THREAD

**Issue by Mannshoch** [friendica/friendica#13842]
after solveing the spam with blacklist and cleaning the database acording to https://github.com/friendica/friendica/issues/12291#issuecomment-1722654267

I  could watch rising the "Inspect deferred workers" counter until 999.
If I look into the database every entry has a retry value greater than 10.

![grafik](https://github.com/friendica/friendica/assets/7795891/9f4a9f8a-73ff-4664-9baf-a9e95cc4ec30)

Anything I have to do?

**Comment by annando** [comment]
The system normally tries 15 times to reach other systems. In the "worker" section of the admin settings you can decrease that limit to a value of - for example - 10.

**Comment by Mannshoch** [comment]
What does that value mean? What could cause a failure? Shouldn't I reduce that value to around two or three.

**Comment by tobiasd** [comment]
It is the number of retries. The time interval between retries grows (though I don't remember the formula behind the increments ATM).

**Comment by annando** [comment]
A value of 2 or 3 would mean that messages wouldn't be delivered any more to a remote system that was offline just for a few minutes. This value here does not only impact the server check but also the message delivery. And there it is crucial that the system tries for at least some hours.

**Comment by Mannshoch** [comment]
Why should a message not be delivered if only 3 retries are allowed. I have a cheap shared webhoster with only PHP support and even here I never met a time when the server was not reachable. Friendica does a good job and wait for enough times a server could react. I think server that do not react for three time should not fill my worker queue.

**Comment by annando** [comment]
For example yesterday I had to perform some database maintenance at one of my servers and went into maintenance mode for about an hour. Also I'm planning to perform a server update on one of my servers soon, which will mean that the system will be offline for about half a day. Then there are Friendica updates, that can last for several hours on larger systems.

**Comment by Mannshoch** [comment]
For the record, my problem was solved after  switch back to php7.4

**Comment by annando** [comment]
If switching the PHP version helped, then there is a configuration issue in your system. I assume that most systems work with PHP 8.x, including mine. But possibly this coincided with a bugfix that I made in the GServer part that lead to fatal errors.

**Comment by annando** [comment]
As far as I remember now, we had a `GServer` problem some time ago, so this PHP version thing was some coincidence, I'm convinced. Also I guess that it is solved now anyway.
