### ISSUE TITLE
Enable the filtering and hiding of hashtags in the timelines "New - Activity", "New - Received", "New - Creation"

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13844]
### Describe the feature you'd like

Friendica has hashtag filters that can hide a post, but not remove it completely.
However, this option is available in the channels.  The "Exclude tags" function can be used to filter out posts from the stream that are no longer displayed in the timeline.

This option to completely remove filtered posts instead of just hiding them should also be possible for the fixed timelines "New - Activity", "New - Received", "New - Creation".

The idea is to be able to enter terms for these timelines that are filtered and removed in the 3 timelines. Posts with these terms should be completely removed from the timeline. 

In addition, it will still be possible to use the "Content filter" add-on, for example, to enter terms that will only be hidden.

### Additional context

**Comment by MrPetovan** [comment]
It sounds like you would like a custom channel to show when you go to your network channel since the feature already exists. If you create a custom channels drawing from "Network" and excluding the tags you don't want to see, then all is left is show this channel by default and voilà.

**Comment by annando** [comment]
It's slightly different, since channels are always sorted like "New - Creation". So when you prefer another sorting, this might not be what you want.

**Comment by loma-one** [comment]
@MrPetovan 
No, that's not it. Channels deliver different results because they use a different event for sorting. 

The request also offers the option of adopting a working filter function for fixed timelines, where posts are not only hidden but can be completely removed.

I now use around 30 filter terms. Without a script that removes the collapsed posts, the timeline would already be completely unusable. I assume that other Friendica users feel the same way.

I noticed on this occasion that filtering on logs, archive, etc. does not work. The channels are great for occasional and targeted use, but not if they are to be used permanently and cannot replace the fixed timelines.

```// ==UserScript==
// @name        loma remove filtered elements
// @namespace
// @description
// @include     *loma.ml/*
// @version     1
// @author      lrustand
// ==/UserScript==

function deleteFiltered()
{

    let elements = document.querySelectorAll(".content-filter-content");
    for(let e of elements)
    {
        let post = e.closest(".wall-item-container");
        post.parentElement.removeChild(post);
    }
}

setInterval(deleteFiltered, 100);
```

**Comment by annando** [comment]
@loma-one The PR #13871 introduces circles for user defined channels that are completely based on the network feed, including the order. With this you should be able to create an exact replica of the network feed - but with added filtering.
