### ISSUE TITLE
[Solved] Ignore thread is only possible for a few threads

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#13843]
Edit: The error is not an error, this message can be closed or deleted.

- [x] I have searched open and closed issues for duplicates

### Bug Description

The "Ignore thread" function in the drop-down menu below the posts is now only available for some threads. In my "network" stream, the menu item does not appear for any posts.

### Steps to Reproduce

1.  Go to the "network" stream.
2. Try to ignore a thread

Actual Result:

The "Ignore thread" menu item is not visible.

Expected Result:

The menu item should be visible and you should be able to ignore the thread.

### Platform Info

Friendica Version: Friendica 'Yellow Archangel' 2024.03-dev - 154

Friendica Source: git

PHP version: 8.2.15

**Comment by MrPetovan** [comment]
What was the solution?

**Comment by atasingorneq** [comment]
It wasn't a bug, or just an error in my thinking. The menu item is only visible if you have previously interacted with the post. It also makes no sense to ignore a post that you have not interacted with. So it works as it should.

If I had known how to delete this error message, I would have done so ;-)

**Comment by MrPetovan** [comment]
Unfortunately Microsoft remembers everything 😈
