### ISSUE TITLE
Add support for the 'sensitive' property in the ActivityPub API definiton

### ISSUE THREAD

**Issue by justdaj** [friendica/friendica#13845]
- [X] I have searched open and closed issues for duplicates

### Bug Description

If someone on Mastodon selects 'Mark media as sensitive' after uploading an file to the post, the recipient's preview of the image should then be obfuscated in some way until they click it.   The corresponding "as:sensitive" property in the Object appears to be ignored on Friendica.

### Steps to Reproduce

1.  On Masoton create a new post and attached an image
2.  Click the check for 'Mark media as sensitive'
3.  Post the message
4. The recipient in Friendica will receive the post 

#### Actual Result:

The Friendica recipient will receive the post and no notice the image is sensitive.

#### Expected Result:

Image should be blurred/hidden until the user interacts 

### Screenshots

Creating in Mastodon
![CreatingInMastodon](https://github.com/friendica/friendica/assets/5741412/89580fcf-fbe8-45d1-aef9-14a4ec50621b)

As received in Mastodon
![ReceivedInMastodon](https://github.com/friendica/friendica/assets/5741412/ea846b3a-0754-4b9b-a9ff-a7acc867f587)

As received in Friendica
![ReceivedInFriendica](https://github.com/friendica/friendica/assets/5741412/271c07c3-6f6a-4c09-91b1-1bf9a9afa66a)

### Platform Info

Friendica Version: 2023.12 and latest develop branch

### Additional Notes

I have tested this on a variety of Misskey forks too (Firefish, Sharkey, Catodon) and all will respect the 'sensitive' property.

Note from the Mastodon API:   

> Mastodon uses the _as:sensitive_ extension property to mark certain posts as sensitive. When a post is marked as sensitive, any media attached to it will be hidden by default, and if a summary is present, the status content will be collapsed behind this summary. In Mastodon, this is known as a content warning.

**Comment by justdaj** [comment]
I am happy to pick up on this one and try it.  I'll throw some Qs at the developers support group as I think that will be the best place, unless it should be here?

**Comment by MrPetovan** [comment]
Either way is fine with me! I already started answering you on the Friendica Developers group.

**Comment by annando** [comment]
The sensitive flag is now received, processed and stored. It is also enabled in the API after PR #13876 is accepted.

What's missing is some hint in the frontend. After #13876 the preview is blurred. But currently we don't give a clue, why the picture is blurred.

**Comment by SpcCw** [comment]
This definitely should be an user setting. Not everyone wants to blur pictures (even marked as sensitive) and some streams can contain lots of them (not always even really sensitive i.e. nsfw or disturbing but some users prefer post them by default).

Mastodon has user setting for it: "blur media marked as sensitive", "don't blur media", "blur all media".

**Comment by AlfredSK** [comment]
There is a user setting at settings -> display -> content -> display sensitive content.
