### ISSUE TITLE
Check for dead accounts 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13841]
### Is the feature request related to a problem? Please describe.

I just read a post where somebody asked someone else if he would not like to delete some of his unused (dead) accounts.
The other person said, he did, but it is not refreshed by all fediverse instances.
So I searched for the user and found several accounts including 4 dead ones. (see screenshot).

### Describe the feature you'd like

Maybe once per month (or week?) a worker job could run and (somehow) check accounts ..? And after several not successful attempts, the account could be removed?

I am not sure what would work well. Maybe somebody knows how other fediverse projects are handling that. Maybe there is even a value in the user data, that marks an account as dead or maybe if a whole instance does no longer exists, that could be used to know which accounts are gone.

### Describe alternatives you've considered

Another way could be to mark accounts as "dead" by hand, so they are removed. Again, I am not sure if that would be a good idea and what could be drawbacks or negative effects of that.

### Additional context

A screenshot of the search (see the [moved] accounts):

![Firefox_Screenshot_2024-01-18T12-47-23 064Z--memo-search](https://github.com/friendica/friendica/assets/5753419/d2b9f9b0-5f7b-45f0-b4aa-6c9b1cce1dad)

Or is friendica already doing this?
I found this issue, which sounds like the same topic: https://github.com/friendica/friendica/issues/12351

**Comment by annando** [comment]
We already have got a check for dead accounts. And normally they should be set to "archive" if they aren't reachable for a long time.

**Comment by haheute** [comment]
Ah.. yes..  thanks.

I really have some contacts in "archived" from instances, that are no more reachable. When I unfollow them and also revoke the "follow me" permission, the contacts disappear. I will observe if the one contact from the screenshot above, that I have in my contacts, will be moved to 'archived'.
