### ISSUE TITLE
Post with hashtag and image gets truncated on Mastodon

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#13868]
Friendica display: https://friendica.mrpetovan.com/display/d05884ce-ccc6cb7d27ee13ba-bfa3c28f

<img width="657" alt="Screen Shot 2024-02-01 at 15 13 40" src="https://github.com/friendica/friendica/assets/925415/f17fddf9-c855-4e3c-9a2a-f9cfc2a464ce">

Mastodon display: https://muenster.im/@hypolite@friendica.mrpetovan.com/111856763109325378

<img width="582" alt="Screen Shot 2024-02-01 at 15 13 56" src="https://github.com/friendica/friendica/assets/925415/0e6a81df-44d1-4380-9cb7-548ee4ac2f8f">

Body string:
```
The world of second-hand #LEGO sellers is very diverse. You have the opportunists eager to make a quick buck, the meticulous hobbyists, the small brick and mortars business owners… And then there’s this tucked into a package.

[url=https://friendica.mrpetovan.com/photos/hypolite/image/109467797465bbade3e0cb1250083946][img=https://friendica.mrpetovan.com/photo/109467797465bbade3e0cb1250083946-1.jpg]A small piece of paper on a desk reads “Thank you for ordering from Hanger (sic) 18, which features bricks shipped from Roswell, NM, the UFO capital of the world. As a token of our appreciation, please enjoy this custom micro-scale build of a genuine UFO.” Next to the text, a one-step one-part LEGO instruction shows a small gray dish. Next to the paper on the desk, here is the expected small gray dish part. [/img][/url]
```

**Comment by AlfredSK** [comment]
Looks good on Misskey
https://misskey.de/notes/9p6w7zs8m6

**Comment by annando** [comment]
Looks fine on Pleroma:
![image](https://github.com/friendica/friendica/assets/844208/6ebb157b-7d23-4785-9fd6-cb826413ad98)

Also it looks fine on the Mastodon server that I use:
![image](https://github.com/friendica/friendica/assets/844208/971f0578-17a3-43f2-b993-e2654394c98f)

**Comment by MrPetovan** [comment]
Ok, I thought Friendica was truncating the text itself.

**Comment by aki42** [comment]
Ran into the same problem yesterday - pure text, no image involved. The text of my comment gets truncated after an inline hashtag on the OP's server colearn.social.
Same behaviour confirmed for mstdn.animexx.de („Beitrag mit #Testhashtag und weiterem Text […]" becomes „Beitrag mit #Testhashtag" on animexx). Both servers are running mastodon 4.2.10.

complete: https://friendica.andreaskilgus.de/display/f016db04-9166-9e50-a765-1a0575901612
truncated: https://colearn.social/@asgro62/112829007160818828

I don't know if this is simply a bug on the mastodon side (am willing to report) or if the projects have to communicate concerning the way messages with hashtags get delivered and interpreted.

**Comment by MrPetovan** [comment]
Thank you for the report!
