### ISSUE TITLE
Incorrectly returning non-empty search results when searching with `offset`

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13863]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Using the API to search for posts should return an empty result set if the `offset` parameter is larger than the total number of results.

It doesn't, it returns the result set as though `offset` was not present, causing clients to infinitely load search results from Friendica servers.

### Steps to Reproduce

1. Find a post. For this example I'll use https://loma.ml/display/373ebf56-1165-8876-5363-14e295858477
2. Perform a search for this post on a Friendica server, for example:
https://pirati.ca/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=0

Observe that one result is returned.

3. Perform the same search but set the `offset` parameter to `1`.
https://pirati.ca/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=1

Actual Result:

You get the same result as the search query in step 2.

Expected Result:

You should get an empty result set, as the `offset` is past the number of possible results.

Compare this with the same search on a server running Mastodon, like mastodon.social:

https://mastodon.social/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=0 <-- requests 20 results, offset = 0, returns 1 result

https://mastodon.social/api/v2/search?q=https%3A%2F%2Floma.ml%2Fdisplay%2F373ebf56-1165-8876-5363-14e295858477&type=statuses&resolve=true&limit=20&following=false&offset=0 <-- requests 20 results, offset = 1, returns 0 results

### Platform Info

Friendica Version: 2024.03-dev (currently reported by pirati.ca)

This was discovered via a user report for Pachli, https://github.com/pachli/pachli-android/issues/338

**Comment by foss-** [comment]
Verified in This is Friendica, version 2024.03-rc that is running at the web location https://pirati.ca/. The database version is 1553/1553, the post update version is 1550/1550.

That shows a single post in the search results while This is Friendica, version 2024.03-dev that is running at the web location https://squeet.me/. The database version is 1552/1552, the post update version is 1547/1550. still shows the infinite results.

Pachli 2.2.0
