### ISSUE TITLE
Unordered lists written in BB Code are rendered wrongly with the Markdown add-on enabled

### ISSUE THREAD

**Issue by ktlinux** [friendica/friendica#13878]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I described the issue more in detail [here](https://libranet.de/display/0b6b25a8-3965-c690-e994-b9b868690603). But whenever I want to create a bulleted (unordered) list in a post/comment, the default formatting for this is the following:

```
[ul]
[*] item 1
[*] item 2
[/ul]
```

This renders the list as follows:

![image](https://github.com/friendica/friendica/assets/27150141/702fb732-ef07-4532-a96e-c4a351b38bdb)

When writing this issue, I remembered that I had the Markdown add-on enabled (can't remember if by default or not). I disabled it, and the lists were properly created. The problem is, some people might have the add-on enabled and not realize this. They might try to type the list, get the `[ul]` suggestion and have the list displayed wrongly, because the parser interprets the `*` symbol instead of the BB Code.

A possible solution to this would be to use the `[li]` parameter instead of `[*]` by default for unordered lists, as that gets rendered correctly even with Markdown enabled. Else, I don't know.

### Steps to Reproduce

1.  Enable the Markdown add-on (if installed on your node)
2.  Type `[ul` in a new post or comment and choose the first suggestion
3.  Go to the preview pane to see the result

Actual Result:

![image](https://github.com/friendica/friendica/assets/27150141/702fb732-ef07-4532-a96e-c4a351b38bdb)

Expected Result:

![image](https://github.com/friendica/friendica/assets/27150141/0c8f249f-9768-4df5-88b0-8afcdbfcf38e)

### Screenshots

Displayed above

### Platform Info

Friendica Version: 2024.03-dev

**Comment by MrPetovan** [comment]
As a workaround, there is an alternative syntax for lists that uses `[li]` instead of `[*]` that doesn't break Markdown syntax.
