### ISSUE TITLE
Shared contacts has wrong linking (text link differs from profile image link)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#1388]
**Repro**

You need to have at least one shared contact with someone else you are following.
If you then visit their profile (not sure if it has to be on the same instance - it is in my case), you'll see their posts and above their posts is a listing of shared contacts (contacts you and the other person are both following).
The list of those shared contacts consists of profile image and username (in text form below the image).

The linking of image + text are not consistent:

* the image (profile pic) goes e.g. to https://pink.pilot.io/profile/username (the profile on the specific instance) > EXPECTED
* the text (username) goes to https://pirati.ca/ (the instance me or the contact I'm seeing shared contacts for are on) for all shared contacts > BROKEN

**Expected**

The text lin should have the same URL, as used for the profile-image, namely the profil of the specific shared contact.

**Comment by fabrixxm** [comment]
Confirmed
(and yes, "share contacts" works also on different istances if you came in with "zrl=" param and your contact list is public)

**Comment by fabrixxm** [comment]
if anyone what to take a look at this, please start from and pull request to branch "release-3.3.3"

**Comment by annando** [comment]
I did a pull request to "develop". I accidentally pushed the change to my local branch of 3.3.3. Could anyone apply the bugfix to 3.3.3?

**Comment by annando** [comment]
Okay, I now did a pull request for 3.3.3.

**Comment by foss-** [comment]
Verified. Thx for this fix @annando ! Should this be closed here?

**Comment by annando** [comment]
I will close it for you.
