### ISSUE TITLE
Link preview images are sensitive-blurred without any way to unblur them

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#13891]
Caused by https://github.com/friendica/friendica/pull/13876

See https://friendica.mrpetovan.com/display/2d4b02f1-079ca9d9af96ac44-bb56d22a

![image](https://github.com/friendica/friendica/assets/925415/248a3e6a-e1fa-4bd5-b8f0-52aba7dc8a6a)

For attached images, it's possible to show the unblurred version by bringing up the lightbox, but there's no such behavior on link preview images. These should be exempt from blurring as they generally aren't user-submitted.

**Comment by annando** [comment]
Problem here is, that this could be a link to some - for example - porn site. Then the preview picture could contain some unwanted content.

**Comment by MrPetovan** [comment]
This particular case has little to do with the sensitive flag which is much broader than that. If you have people unexpectedly post porn links in your timeline, the correct response isn't to blur all the link preview pictures for everybody without any way of lifting the blur when the sensitive flag is set, it's to stop following or blocking the person who shared porn with you.

The way I see it, we first remove this blur overreach, and then if people complain about this specific case, we'll figure out a way to let users unblur these specific pictures.

**Comment by annando** [comment]
Well, this could happen to you while scrolling through the public timeline. Also there is a user setting where you can decide to not blur sensitive content. Also: We already had people complaining about not blurring sensitive content.

**Comment by MrPetovan** [comment]
Yes, sensitive content as in user-submitted pictures, not link previews.
