### ISSUE TITLE
2024.03-rc  Uncaught Exception Error

### ISSUE THREAD

**Issue by Tslmuun** [friendica/friendica#13898]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When searching for any keyword, errors occur. However, searching using tags works fine.

### Steps to Reproduce

1.  search any keyword, 
2.  error 500

```
Uncaught Exception Error: "Call to undefined function Friendica\Util\idn_to_ascii()" at /var/www//src/Util/Network.php line 540

Error: Call to undefined function Friendica\Util\idn_to_ascii() in /var/www//src/Util/Network.php:540
Stack trace:
#0 /var/www//src/Module/Search/Index.php(245): Friendica\Util\Network::convertToIdn()
#1 /var/www//src/Module/Search/Index.php(131): Friendica\Module\Search\Index::tryRedirectToProfile()
#2 /var/www//src/BaseModule.php(250): Friendica\Module\Search\Index->content()
#3 /var/www//src/App.php(711): Friendica\BaseModule->run()
#4 /var/www//index.php(46): Friendica\App->runFrontend()
#5 {main}
```

### Platform Info

Friendica Version:2024.03-rc

PHP version:8.2.12

SQL version:1552

**Comment by AlfredSK** [comment]
I just checked on my node with a simple search for 'Test'. This worked fine.
What was the keyword you were searching for?

**Comment by Tslmuun** [comment]
__

> I just checked on my node with a simple search for 'Test'. This worked fine. What was the keyword you were searching for?

I have tried searching for many keywords, but it doesn’t work properly. However, if I add a “#” before the keyword, it works fine.

**Comment by Tslmuun** [comment]
Sorry ！This issue has been resolved.  The php-intl extension is missing.

**Comment by gudzpoz** [comment]
:+1: Installing php-intl solved my problem as well. However, the [Requirements](https://friendi.ca/resources/requirements/) page does not mention the php-intl dependency. Maybe the documentation should be updated? (It is mentioned in [doc/Install.md](https://github.com/friendica/friendica/blob/develop/doc/Install.md#Requirements) though.)

**Comment by MrPetovan** [comment]
Thanks for the catch, I'll update the page right away.
