### ISSUE TITLE
`ostatus` entry missing from activitypub `@context`

### ISSUE THREAD

**Issue by puckipedia** [friendica/friendica#13905]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When a post is federated out over ActivityPub, using a `conversation` entry, the context only mentions `"conversation": "ostatus:conversation"`, while missing `"ostatus": "http://ostatus.org#"`.

### Steps to Reproduce
1. Look at a post (e.g. `https://friendica.mrpetovan.com/objects/735a2029-2065-d0ad-33d5-345868501720`)
2. Try to JSON-LD expand it

Actual Result:

`ostatus:convernsation` being set

Expected Result:

`"conversation"` in the object being expanded to `"http://ostatus.org#conversation"`, like other activitypub servers.

### Platform Info

Friendica Version: idk, not my instance

**Comment by MrPetovan** [comment]
Thank you for your report, for your information Friendica server version can be found at `https://<domain>/friendica`
