### ISSUE TITLE
Add support for protocol filtering in the channels

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13909]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If a channel is selected as a timeline and this timeline is to be filtered by protocol type (/channel=x?nets=bsky), the view always jumps back to the selected channel. A channel cannot be combined with a protocol filter

Expected Result:

A channel should offer the option of filtering it according to a protocol type.

### Platform Info

Friendica Version: 2024.03-rc

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by MrPetovan** [comment]
What's the full URL you're using to filter networks from a channel page? Did you manually type the URL or click on a link in the interface?

**Comment by loma-one** [comment]
The URL above is theoretical. There is no callable URL according to which the protocol can be filtered in the channel.

**Comment by annando** [comment]
When I created the channels, I intentionally hadn't added the filtering by protocols there. So I see this more as a feature request than as a bug. But yeah, we should do something here.
