### ISSUE TITLE
update Mastodon API documentation

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13914]
https://docs.friendi.ca/develop/spec/api/mastodon/ is the official documentation for Mastodon API.

- [ ] After recent changes there are a few more support API endpoints that can be added: https://github.com/friendica/friendica/pull/13911
- [ ] Unsupported apps: Android: Fedilab - afaik Fedilab uses Mastodon API and is functional, the linked issue is in a repo that has not seen a commit in 2 years and is no longer actively used for fedilab development which is now at Codeberg https://codeberg.org/tom79/Fedilab/issues
- [ ] Is Mammut client still developed? No commit for 9 months and could not find the listing in PlayStore, should probably also be removed
- [ ] remove iOS Mast: https://github.com/Beesitech/Mast, last commit 6 years ago, last MAS update 3 years ago
- [ ] Toot! no update for almost 1 year: https://apps.apple.com/us/app/toot-for-mastodon/id1229021451 it is a payed app, is anybody using this and can verify the status?

**Comment by MrPetovan** [comment]
If I remember correctly, these pages are automatically generated via a process @nupplaphil set up.

**Comment by foss-** [comment]
Correct: changes need to be made in https://github.com/friendica/friendica/blob/2024.03-rc/doc/API-Mastodon.md
