### ISSUE TITLE
Display of new incoming messages in the badges does not count context sensitive when a channel is used

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13910]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I'm not sure if this is a mistake. Please label it differently if this is the case.

If a channel is permanently used as the start view, new incoming messages are still counted up in a badge via the network icon. The number of new incoming messages does not take into account the channel set by the user. Only the call /network is taken into account in order to set the number in the badges to 0.

As a result, the number of messages in the channel is not corrected.

### Steps to Reproduce

1. select a channel
2. refresh the channel without calling up the network page
3. note the number of messages in the badges, which is not set to 0 despite refreshing the page

Actual Result:

The badge is not calculated context-sensitively when a channel is used

Expected Result:

The badge takes into account the number of new messages for the channel

### Platform Info

Friendica Version: 2024-03-rc

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by annando** [comment]
The number that is displayed there shows the total number of unread posts. I guess there is room for improvement.

**Comment by loma-one** [comment]
One question: is it possible to deactivate the counter in the badge, as is also possible on the circles?

**Comment by annando** [comment]
Currently not.

**Comment by B0ngripper** [comment]
For the moment that is the only thing bugging me for the new channel options. Great filtering for custom channels, but i have to switch back and forth to get rid of the false counter of unread messages. I fix would be highly appreciated.

**Comment by annando** [comment]
Yeah, I really want to have a look at this. But I'm currently fighting with some other stuff.

**Comment by B0ngripper** [comment]
All good, just wanting to raise awareness of this issue. You are doing great work.

**Comment by annando** [comment]
This is somehow not an easy task. Would it be okay for you, so simply have got some kind of a marker (without a number) that indicate new posts?

**Comment by B0ngripper** [comment]
Sure, it would be less visible and therefore annoying.

For the moment i switch back to the default channel to get rid of the counter twice or thrice a day. Not that of a huge effort.
