### ISSUE TITLE
profile settings should be available in settings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1391]
reported from a user
- accessing the profile settings should be possible via the Settings. editing your profiles is too hidden
- changing the profile picture should be more intuitive
- should changes in the profile trigger an activity notification by defailt?

**Comment by Beanow** [comment]
Which theme did they use?

Tobias Diekershoff <notifications@github.com> schreef op 12 februari 2015 08:24:31 CET:

**Comment by tobiasd** [comment]
I've checked duepunto, quattro, vier and frost all of them hide the profile settings outside of the settings area. You always have to go over your profile to access the editor (vier has an additional button there) which is one place I'd look into, but searching a setting under the settings is valid as well.

**Comment by hoergen** [comment]
This is still a mess. I tried to manage 2 profiles and I ended up in complete chaos. By accident i found the /profiles/ page .. but I dont know how to get there?
