### ISSUE TITLE
Avatar photos broken on Diaspora

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13939]
It seems on Diaspora, my Friendica Avatar photo is broken. / replaced by a default image.

### Bug Description

Such a link was it, I believe (from a comment there): `https://boerdica.de/photo/custom/50/4.jpg` but now this throws an error and after a hard reload Diaspora shows a default avatar.

```
Not Found

The requested resource could not be found but may be available in the future.

#0 /var/www/localhost/friendica/src/BaseModule.php(244): Friendica\Module\Photo->rawContent()
#1 /var/www/localhost/friendica/src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#2 /var/www/localhost/friendica/src/App.php(711): Friendica\Module\BaseApi->run()
#3 /var/www/localhost/friendica/index.php(46): Friendica\App->runFrontend()
#4 {main}

Request: 65db97fe13eec
```

### Screenshots

![diaspora-avatar-broken](https://github.com/friendica/friendica/assets/5753419/8ca696d8-14de-4aeb-9a95-cba8369b339e)

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2024.03-rc, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1554/1554 und die Post-Update-Version 1550/1550.

PHP version: 8.2.16

SQL version: Ver 15.1 Distrib 10.11.6-MariaDB

**Comment by MrPetovan** [comment]
> `https://boerdica.de/photo/custom/50/4.jpg`

This is a deprecated avatar picture URL format we just stopped honoring in the 2023.04-rc version. Even on your own profile page the image URL doesn't look like this. It looks like Diaspora didn't update your avatar picture URL in more than a year. Not sure how you can trigger a contact update manually.
