### ISSUE TITLE
curweather addon does not display information for non-amerricans

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1394]
The curweather addon uses weather.gov as source of the data, but that seems to only provide data for the USA and CA. It would be nice to have a source that includes the rest of the world as well.

**Comment by blog2read** [comment]
I would like to sencond this - would be great to have European stations as well.

**Comment by annando** [comment]
What about this source: http://openweathermap.org/api

**Comment by fabrixxm** [comment]
:+1:

**Comment by silke** [comment]
I started to look at it. From a "make friendica easier" perspective I would say let's get rid of the plugin. From a "learning to code" perspective it's quite interesting for me though. But right now, I can't tell if I can bring to an end what I started...

**Comment by annando** [comment]
I think we should make our thoughts about the way such a plugin could make sense and then rewrite it completely.

**Comment by n4rky** [comment]
Quoting Michael Vogel <notifications@github.com>:

> I think we should make our thoughts about the way such a plugin  
> could make sense and then rewrite it completely.

If I understand correctly, it relies on METAR via NOAA? But there are  
other worldwide meteorological services. Perhaps they offer something  
equivalent, but more universally applicable?


-- 
David Benfell <benfell@parts-unknown.org>

**Comment by annando** [comment]
The question isn't if we find this data. The question is more, if we need this addon. Und if we say so, the question is, how it should work.
