### ISSUE TITLE
Unexpected 404 from `/api/v1/statuses/:id/context`

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13940]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Requesting the `context` (i.e., posts up and down thread) from statuses in a specific thread (using the Mastodon API) returns a 404 instead of the expected lists of statuses.

This was originally reported by @foss- in https://github.com/pachli/pachli-android/issues/472, where they note "Somehow this does not happen with all comments, but seems to happen for all comments in this specific thread."

### Steps to Reproduce

1.  In Pachli, in an account signed in to a Friendi.ca server (I used pirati.ca) search for the status https://social.wake.st/@liaizon/111987368609277135. The status is found and appears in the search results
2.  Click the status

Actual Result:

The status' detailed information is displayed, as well as an error indicating that the call to fetch the status' context returned a 404.

Behind the scenes Pachli makes two API calls

- https://pirati.ca/api/v1/statuses/50597202 <-- this works (returns 200), 50597202  is the local ID for the status linked to above
- https://pirati.ca/api/v1/statuses/50597202/context <-- this fails (returns 404)

Expected Result:

The https://pirati.ca/api/v1/statuses/50597202/context fetch should succeed. The thread content is visible in the web UI if I search for the same post (so pirati.ca has the content), and it's visible if you search for the same status signed in to an account on a Mastodon server.

I expect this to work because https://wiki.friendi.ca/docs/api-mastodon lists "[GET /api/v1/statuses/:id/context](https://docs.joinmastodon.org/methods/statuses/)" in the "Implemented endpoints" section.

### Platform Info

Friendica Version:

`https://pirati.ca/api/v2/instance` reports:

version: "2024.03-rc"
codename: "Yellow Archangel"
db_version: 1554

**Comment by MrPetovan** [comment]
I can confirm we have implemented the `/context` endpoint, it looks like it isn't finding the relevant post which is surprising because it finds it in `/statuses`. @annando will have to investigate `uri-id = 50597202` on pirati.ca since it's on a server he hosts.
