### ISSUE TITLE
Missing `source_url` property from some Friendica servers

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13941]
- [x] I have searched open and closed issues for duplicates

### Bug Description

It appears to be possible to configure Friendica in such a way that the `source_url` property is missing in the `/api/v2/instance` response.

Per https://docs.joinmastodon.org/entities/Instance/#source_url this property is non-optional and non-nullable, so should always be present. The description also notes that it is necessary to comply with the AGPL.

### Steps to Reproduce

1.  Open https://friends.andreaalbertini.ch/api/v2/instance
2.  Look for the `source_url` property

Actual Result:

Property is missing.

Expected Result:

Property should be present.

Friendica Version:

friendica |  
-- | --
version | "2023.04-1"
codename | "Giant Rhubarb"
db_version | 1518

I also see this on: astoundingteam.com, b65.me.in, community.ballhaus.dk, community.uncensoredwisdom.com, delmenhorst.social, digitalnomads.social, discover.freedica.org, f.kawa-kun.com, friendica.cucitofacile.it, friendica.freunde-des-punk.de, friendica.glytch.dev, friendica.gnomos.org, friendica.greyhat.chat, friendica.harkonen.pw, friendica.inclusion.cc, friendica.j62.de, friendica.s-a.at, friendica.se1.eu, friendica.tigvarts.com, friendica.wige.erabo.de, friends.andreaalbertini.ch, friends.dialogundsinn.com, friends.unixweb.net, herkenhoff.com, jibberjabber.online, lugnasad.eu, our.betternetwork.us, social.ojour.de, social.pouill.eu, social.syndae.de, social.trom.tf, social.tromdienste.de, social.watdalos.de, tagessch.eu, thames.blisses.org, whitelion.me, wirnity.de, your.sensor.community

**Comment by MrPetovan** [comment]
Thank you for your report!

**Comment by MrPetovan** [comment]
Retroactively fixed by https://github.com/friendica/friendica/pull/13493, these nodes need to upgrade to version 2023.12.

**Comment by nikclayton** [comment]
Ah, thanks. Sorry for the noise. As evidenced by the edits in the description I think I'd latched on `sourceUrl` as the property name for a bit, and must have searched for that when I was looking for duplicate issues.

**Comment by MrPetovan** [comment]
It's okay, thank you for taking the time reporting the issue!
