### ISSUE TITLE
Likes shown in New-Received timeline from local instance users

### ISSUE THREAD

**Issue by B0ngripper** [friendica/friendica#13952]
I am using the New-Received timeline as default, also for my custom channels.

Normally, likes are not shown in this timeline, only new articles, comments and shared articles by users, that i follow.

I have noticed, that despite the channel defaults, my timeline also gets filled with articles, that have been liked by followed users of my local instance. This behavior can be noticed also with custom channels. Everything else works as expected.

How do i get rid of the likes? I am not sure, if this could be an error in configuration or if it's actually a bug.

**Comment by annando** [comment]
"New Received" show content based on the time it arrived on your system. This can include fairly old content as well, when it had been fetched during the thread completion functionality.

Concerning the content that you see at all: In the "social media" settings you can select, if you want only want to see posts that had been created by your contacts, all posts where your contact commented on or all posts where your contacts reacted in any way (including likes).

**Comment by B0ngripper** [comment]
![grafik](https://github.com/friendica/friendica/assets/81742294/fb84d775-dea3-44b8-93da-f36bf25a7f15)

As you can see, likes are deactivated under social media. And the likes i can see are only fetched from my local instance, not anywhere else. Which is odd.

**Comment by B0ngripper** [comment]
The new RC seems to have solved the issue. Thanks!
