### ISSUE TITLE
Follow Twitter users from any ActivityPub service

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#13958]
Would it be possible to incorporate this into Friendica?

Bird.makeup is a way to follow Twitter users from any ActivityPub service. The aim is to make tweets appear as native a possible to the fediverse, while being as scalable as possible. The project started from BirdsiteLive, but has now been improved significantly.

Compared to BirdsiteLive, bird.makeup is:

More scalable:

Twitter API calls are not rate-limited
It is possible to split the Twitter crawling to multiple servers
There are now integration tests for the non-official api
The core pipeline has been tweaked to remove bottlenecks. As of writing this, bird.makeup supports without problems more than 20k users.
Twitter users with no followers on the fediverse will stop being fetched
More native to the fediverse:

Retweets are propagated as boosts
Activities are now "unlisted" which means that they won't polute the public timeline, but they can still be boosted
WIP support for QT
More modern:

Moved from .net core 3.1 to .net 6 which is still supported
Moved from postgres 9 to 15
Moved from Newtonsoft.Json to System.Text.Json
[#](https://sr.ht/~cloutier/bird.makeup/#official-instance)

https://sr.ht/~cloutier/bird.makeup/ in Friendica?

**Comment by annando** [comment]
Since birdmakeup exists, I guess that there is no need for that. Also Twitter is constantly trying to cut all these possibilities, so I guess that that service will close as well.

**Comment by MrPetovan** [comment]
Also Bird,makeup is a standalone application, it isn't something we can "add" to Friendica.

**Comment by ghost** [comment]
Oh, I thought that was such a GIT thing.
