### ISSUE TITLE
Wordpress installations with active AP add-on paralyse workers

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13955]
# For general question about Friendica, please try to find a solution at https://wiki.friendi.ca first.

Over the last few days, I have had two large Word Press domains, some of which have flushed up to 10 years old posts into my timeline. Under the constant load associated with this, no new posts could be retrieved or sent. Only blocking the domain led to an immediate improvement. The workers were able to process the existing jobs quickly and the instance was accessible again.

https://mecp.de/egijuxigog.sql

This raises two questions for me
1. Is there a kind of rate limit for Friendica for individual domains that I can use to limit the number of simultaneous worker jobs?
2. Is it possible to reject contributions that are already 10 years old when they are sent?
- Does it make sense to integrate such techniques if further very large instances (threads) will be added to the Fediverse in the course of the year?

**Comment by annando** [comment]
We currently don't have got such a rate limit. Concerning the date check: We will have to see, how we could do this. Concerning Threads: Yeah, we will have to see, how to conquer it.

**Comment by loma-one** [comment]
At the same time, I got in touch with Matthias Pfefferle. The assumption is that an SEO add-on may have made changes to the article and this may have led to it being resent. This creates a DOS-like behaviour of the sending instance.

**Comment by annando** [comment]
I can't think of any possibility to distribute the tasks to the workers based on the systems we receive content from. I guess that we don't have got the data for that at this point at all.

**Comment by informapirata** [comment]
> This creates a DOS-like behaviour of the sending instance.

Unfortunately I had direct experience of a problem with the ActivityPub plugin for Wordpress: when I changed the server where the blog www.informapirata.it was located, the plugin started shooting all the blog articles throughout the Fediverse!
On Friendica I didn't have any major problems, but the new informapirata.it server collapsed several times and only stabilized after a couple of days...

**Comment by loma-one** [comment]
the problem is fixed with https://github.com/friendica/friendica/pull/13956
