### ISSUE TITLE
Blockbot addon prevent Friendica URLs from generating previews on remote systems

### ISSUE THREAD

**Issue by informapirata** [friendica/friendica#13959]
### Is the feature request related to a problem? Please describe.

When a Friendica post is linked on any social network (Facebook, Twitter or Mastodon), on any messenger (Whatsapp, Telegram, Matrix, etc) or within a WordPress post, the preview of that post is never displayed.

By now all users are accustomed to becoming suspicious when faced with links that do not generate previews. Furthermore, the standard link of a Friendica post is also rather long and incomprehensible:
 `(https://[instancename]/display/[8-digit hexadecimal code]-[8-digit hexadecimal code]-[16!!-digit hexadecimal code]`

It can be said that the perception of the average user when faced with a link like this is that of being faced with a warning like this: "HEY STUPID, DON'T CLICK HERE! IT COULD BE THE LAST THING YOU DO WITH YOUR DEVICE!"

### Describe the feature you'd like

I'm not a developer and I don't know what causes this lack of Friendica, which is unable to communicate the minimum information to generate a preview to other systems: but it probably depends on the inability to generate open graph tags. We should therefore implement this functionality.

This is a feature supported by all the social networks of the Fediverse (Mastodon, Pleroma, Pixelfed and Lemmy; Misskey not...) and therefore by comparing with their developers, one could understand how they managed to implement the possibility of generating a preview readable

### Describe alternatives you've considered

You could copy the Friendica post, publish it on Pleroma and share the Pleroma link... Or you could take a screenshot of the post and insert it immediately after the link... 
(this is obviously an ironic joke)

Jokes aside, when I have to publish the preview of a link to Friendica, today I'm forced to do this:
- given that for several months, I have also been republishing all the most important posts in a Lemmy community of my feddit.it instance
- once the Friendica post is reposted by Lemmy, I have the option to use the Lemmy link when I want to share it on Telegram or Twitter
- in this way, the user who receives the link does not become suspicious, thinking that I have sent him a malicious link

### Additional context

I understand that working on the Friendica interface is no longer easy, but improving the preview processes is important for the perception of Friendica as an advanced system

**Comment by MrPetovan** [comment]
Thank you for reporting this. We already support OpenGraph properties, for example for this post of mine: https://friendica.mrpetovan.com/display/735a2029-1465-e238-3fb0-499171352130

```html
<meta name="author" content="Hypolite Petovan" />
<meta name="title" content="Hypolite Petovan" />
<meta name="fulltitle" content="Hypolite Petovan" />
<meta name="description" content="#MiniReview #VideoGames Gloomhaven (2021) immediately felt like a Games Workshop production to me, not without reason: it was originally conceived in 2017 as..." />
<meta itemprop="name" content="Hypolite Petovan" />
<meta itemprop="description" content="#MiniReview #VideoGames Gloomhaven (2021) immediately felt like a Games Workshop production to me, not without reason: it was originally conceived in 2017 as..." />
<meta itemprop="image" content="photo/20682437145daa4e85f019a278584494-5.png?ts=1682368420" />
<meta itemprop="author" content="Hypolite Petovan" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="Hypolite Petovan" />
<meta name="twitter:description" content="#MiniReview #VideoGames Gloomhaven (2021) immediately felt like a Games Workshop production to me, not without reason: it was originally conceived in 2017 as..." />
<meta name="twitter:image" content="https://friendica.mrpetovan.com/photo/20682437145daa4e85f019a278584494-5.png?ts=1682368420" />
<meta name="twitter:url" content="https://friendica.mrpetovan.com/display/735a2029-1465-e238-3fb0-499171352130" />
<meta name="DC.title" content="Hypolite Petovan" />
<meta name="DC.description" content="#MiniReview #VideoGames Gloomhaven (2021) immediately felt like a Games Workshop production to me, not without reason: it was originally conceived in 2017 as..." />
<meta property="og:type" content="website" />
<meta property="og:title" content="Hypolite Petovan" />
<meta property="og:image" content="https://friendica.mrpetovan.com/photo/20682437145daa4e85f019a278584494-5.png?ts=1682368420" />
<meta property="og:url" content="https://friendica.mrpetovan.com/display/735a2029-1465-e238-3fb0-499171352130" />
<meta property="og:description" content="#MiniReview #VideoGames Gloomhaven (2021) immediately felt like a Games Workshop production to me, not without reason: it was originally conceived in 2017 as..." />
<meta name="og:article:author" content="Hypolite Petovan" />
```

So I'm not sure what more do we have to do for link previews to be generated on remote systems. 🤷‍♂️

**Comment by loma-one** [comment]
Test on Signal
![2024-03-03_18-49](https://github.com/friendica/friendica/assets/44441246/192ef541-cd3d-465f-9f57-f3a266624c64)

Test on Telegram
![Screenshot_20240303_185029](https://github.com/friendica/friendica/assets/44441246/ad009652-88ba-4f28-ba80-7c845ae5fc19)

Test on Mastodon
![Screenshot 2024-03-03 at 18-48-45 Mastodon](https://github.com/friendica/friendica/assets/44441246/e99f1bb7-5e9a-4ebb-a3db-2b92c0264b27)

Test on MATRIX NEOCHAT
![grafik](https://github.com/friendica/friendica/assets/44441246/c53aa3c6-dc84-4d3e-8df9-c3c67a683e61)

**Comment by informapirata** [comment]
> Thank you for reporting this. We already support OpenGraph properties, for example for this post of mine: https://friendica.mrpetovan.com/display/735a2029-1465-e238-3fb0-499171352130

How strange... Can I ask you a favor? You can try to understand why your posts are visible, while those of your two friends and friendica locksmiths @annando and @tobiasd are not?

See here:

https://pirati.ca/display/ec054ce7-1965-e49a-064e-c6a027105081

and here:

https://social.diekershoff.de/display/f3ad7b1c-1465-de33-4d5f-f19744667207

**Comment by annando** [comment]
Possibly it has something to do with the robots.txt?

**Comment by MrPetovan** [comment]
Interesting, I'm getting 403 Forbidden errors fetching the OpenGraph data on https://opengraph.xyz (paid service with a free probe tool) for both of these URLs, so I'd assume it has to do with how these nodes were configured.

**Comment by MrPetovan** [comment]
> Possibly it has something to do with the robots.txt?

No, it wouldn't trigger 403 errors. More likely to be the consequence of using the blockbot addon.

**Comment by tobiasd** [comment]
> More likely to be the consequence of using the blockbot addon.

I have that active yes,

**Comment by AlfredSK** [comment]
On Misskey I see no URL previews for posts from libranet.de. And yes, the blockbot addon is active on my Friendica node. 🤔

**Comment by AlfredSK** [comment]
Yep. It is the blockbot addon. Without that addon the URL preview works on remote systems. With blockbot enabled the preview cannot be generated on remote systems.

**Comment by MrPetovan** [comment]
Thank you for checking, the remaining question therefore is: is this intended?

**Comment by informapirata** [comment]
> Without that addon the URL preview works on remote systems.

I confirm! I disabled the add-on and now the previews work... 🙄🤦‍♂️

**Comment by annando** [comment]
I just had looked into my server log:
```
$ cat access-ssl.log | grep ec054ce7-1965-e49a-064e-c6a027105081.*" 403 "
127.0.0.1 - - [03/Mar/2024:18:03:22 +0000] "GET /display/ec054ce7-1965-e49a-064e-c6a027105081 HTTP/1.1" 403 5304 "-" "TelegramBot (like TwitterBot)"
127.0.0.1 - - [03/Mar/2024:18:37:52 +0000] "GET /display/ec054ce7-1965-e49a-064e-c6a027105081 HTTP/1.1" 403 5304 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36 Twitterbot/1.0"
```
Both "Twitterbot" and "TelegramBot" are listed as bots in the addon.

**Comment by MrPetovan** [comment]
So it looks like it's intended. Case closed?

**Comment by annando** [comment]
I will do some adjustments to the code, so that the admin can decide to allow these kinds of bots.

**Comment by annando** [comment]
PR https://git.friendi.ca/friendica/friendica-addons/pulls/1474 is created.

**Comment by MrPetovan** [comment]
Closed by https://git.friendi.ca/friendica/friendica-addons/pulls/1474

**Comment by AlfredSK** [comment]
Looks like the PR doesn't fix it. I have enabled the new option to `allow preview agents` but Misskey is still showing a "could not preview" message.

**Comment by annando** [comment]
Please have got a look at your access log of your webserver. You should see an error `403` along with the URL. Please post the line here, so that we can see the corresponding agent string. See my example above: https://github.com/friendica/friendica/issues/13959#issuecomment-1975374672

**Comment by AlfredSK** [comment]
Hmm.. This looks good, I guess. At 11:30:16 UTC I created the post on misskey.de with this URL `https://mordor.social/display/027b03f7-1365-e5af-59a2-2eb674767027`


```
95.217.210.30 - - [04/Mar/2024:11:21:36 +0000] "POST /inbox HTTP/1.1" 202 5527 "-" "Misskey/2024.3.1 (https://misskey.de/)"
2a01:4f9:c010:553f::1 - - [04/Mar/2024:11:22:08 +0000] "POST /inbox HTTP/1.1" 202 971 "-" "Misskey/2024.3.1 (https://misskey.de/)"
95.217.210.30 - - [04/Mar/2024:11:26:33 +0000] "GET /photo/194043398165e5af3a3f94f793631242-0.jpeg HTTP/1.1" 200 2240265 "-" "Misskey/2024.3.1 (https://misskey.de/)"
95.217.210.30 - - [04/Mar/2024:11:29:36 +0000] "GET /photo/profile/sauron.jpeg?ts=1575493524 HTTP/1.1" 200 14382 "-" "Misskey/2024.3.1 (https://misskey.de/)"
89.186.159.176 - - [04/Mar/2024:11:29:36 +0000] "GET /photo/194043398165e5af3a3f94f793631242-0.jpeg HTTP/2.0" 200 2217942 "https://misskey.de/" "Mozilla/5.0 (Android 11; Mobile; rv:123.0) Gecko/123.0 Firefox/123.0"
2a01:4f9:c010:553f::1 - - [04/Mar/2024:11:30:16 +0000] "POST /inbox HTTP/1.1" 202 971 "-" "Misskey/2024.3.1 (https://misskey.de/)"
2a01:4f9:c010:553f::1 - - [04/Mar/2024:11:30:58 +0000] "POST /inbox HTTP/1.1" 202 971 "-" "Misskey/2024.3.1 (https://misskey.de/)"
2003:e5:1728:6f00:235d:7f12:6149:406a - - [04/Mar/2024:11:32:17 +0000] "GET /display/027b03f7-1365-e5af-59a2-2eb674767027 HTTP/2.0" 200 8994 "https://misskey.de/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
95.217.210.30 - - [04/Mar/2024:13:17:15 +0000] "POST /inbox HTTP/1.1" 202 5527 "-" "Misskey/2024.3.1 (https://misskey.de/)"
```

But still, the preview cannot be generated.

![grafik](https://github.com/friendica/friendica/assets/3656054/e155e109-99a3-418e-bdb1-0169ba5ac4aa)

I'll do another test with `blockbot` disabled...

**Comment by AlfredSK** [comment]
Yep. When I disable the `blockbot` addon and then reload the page on misskey.de the URL preview is instantly generated as expected.

![grafik](https://github.com/friendica/friendica/assets/3656054/a9388a00-32f6-4598-b79e-660257c9e0e6)

**Comment by AlfredSK** [comment]
The only difference I can spot in my log file is that misskey.de is now accessing this URL for the profile picture. That was missing with `blockbot` enabled...

` 95.217.210.30 - - [04/Mar/2024:13:45:25 +0000] "GET /photo/20753421955de81f8314687265970581-5.jpg?ts=1575493524 HTTP/1.1" 200 8852 "-" "Misskey/2024.3.1 (https://misskey.de/)"`

**Comment by AlfredSK** [comment]
In Apache's access log on misskey.de I get an HTTP error 422 - HTTP 422 Unprocessable Entity for this URL...

```
"GET /url?url=https%3A%2F%2Flibranet.de%2Fdisplay%2F0b6b25a8-1265-d097-2a71-359018856991&lang=en-US HTTP/2.0" 422 155 "https://misskey.de/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
```

misskey.de log with blockbot disabled...

```
"GET /url?url=https%3A%2F%2Flibranet.de%2Fdisplay%2F0b6b25a8-1265-d097-2a71-359018856991&lang=en-US HTTP/2.0" 200 484 "https://misskey.de/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
```

**Comment by AlfredSK** [comment]
Sorry  for the noise. :-) But could it be that Misskey ist using another UA string for fetching URL previews?

I found this in my Friendica log. The IP is the IPv6 of misskey.de. Maybe the HTTP 200 happened when the addon was disabled.

```
2a01:4f9:c010:553f::1 - - [04/Mar/2024:13:45:25 +0000] "GET /display/027b03f7-1365-e5af-59a2-2eb674767027 HTTP/1.1" 200 9749 "-" "SummalyBot/5.0.3"
2a01:4f9:c010:553f::1 - - [04/Mar/2024:14:02:53 +0000] "GET /display/027b03f7-1365-e5af-59a2-2eb674767027 HTTP/1.1" 403 5934 "-" "SummalyBot/5.0.3"
```

**Comment by AlfredSK** [comment]
> But could it be that Misskey ist using another UA string for fetching URL previews?

Yes. They do...

From misskey-dev/misskey/packages/frontend/src/components/MkUrlPreview.vue:
``import type { summaly } from '@misskey-dev/summaly';``

And from misskey-dev/summaly/src/utils/got.ts:
``const BOT_UA = `SummalyBot/${repo.version}`;``

**Comment by annando** [comment]
Done: https://git.friendi.ca/friendica/friendica-addons/pulls/1476

**Comment by tobiasd** [comment]
merged the PR, you can try again

**Comment by annando** [comment]
BTW: it would be great if someone can try with some more social media services and messenger services.

**Comment by AlfredSK** [comment]
> merged the PR, you can try again

![grafik](https://github.com/friendica/friendica/assets/3656054/8ab648da-2865-45d8-ac63-7b7bb7e1280b)

🎉 🚀 😃

**Comment by marcusxss** [comment]
MrPetovan wrote:
> Thank you for reporting this. We already support OpenGraph properties, for example for this post of mine: https://friendica.mrpetovan.com/display/735a2029-1465-e238-3fb0-499171352130

This is the (lack of) preview I get from that post on Facebook right now:
<img width="703" height="217" alt="Image" src="https://github.com/user-attachments/assets/893d7f19-96d6-4780-9cc0-74a2d81651b0" />

That doesn't look too trustworthy or attractive to potential new users.

...but it's fine on Mastodon:
<img width="589" height="317" alt="Image" src="https://github.com/user-attachments/assets/ffadc9da-2160-4cf7-b0d9-83984dd21102" />

Has Facebook (and possibly others) changed how previews are handled? If so, I can create a new issue for it.
