### ISSUE TITLE
Wrong image preview orientation

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#13964]
Remote post: https://blimey.social/objects/a95264c9-926b-48ae-948e-5c9f7a78423c

![image](https://github.com/friendica/friendica/assets/925415/1c745da7-754e-407e-973f-330f3662f46e)

Image URL: https://blimey.social/media/9111c37d-57a8-44c0-b117-bd85da4564eb/IMG_4601.jpeg

Local post: https://friendica.mrpetovan.com/display/5039ef88-399904c1d8c5fa45-0c5134f4
![image](https://github.com/friendica/friendica/assets/925415/a49cf7fa-fb8a-445d-86ac-fabbdcd6fc50)

Local image preview: https://friendica.mrpetovan.com/photo/preview/640/2084366

![image](https://github.com/friendica/friendica/assets/925415/ecd89620-2d0b-4f0d-b529-fbdabf829fc0)

Local image URL: https://friendica.mrpetovan.com/photo/media/2084366

Can't paste the original image here because it's 4032x4032px with over 10MB size.

**Comment by schmaker** [comment]
Might be related?
https://github.com/friendica/friendica/issues/13578

**Comment by MrPetovan** [comment]
Yes, both are about preview images.

**Comment by MrPetovan** [comment]
Duplicate of https://github.com/friendica/friendica/issues/13578
