### ISSUE TITLE
No picture in post preview

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13984]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Since some days, I see no picture in the preview of a new post.

### Steps to Reproduce

1. Write a new post, and add a link. I used this YouTube link: https://youtu.be/qbqd6aJASdI
2. Check if a preview picture is displayed. 
3. click on the "preview" tab and look if the picture is there, too

Actual Result:

I see the picture it in the "new message" tab, but not in the "preview".

Expected Result:

The picture should also appear in the "preview" tab.

### Screenshots

![no-preview-image](https://github.com/friendica/friendica/assets/5753419/5ef444d0-1fef-432e-929c-08bea26aca94)

### Platform Info

Friendica Version: 2024.03-rc
Datenbankversion: 1556/1556 
Post-Update-Version: 1550/1550

PHP version: 8.2.16

SQL version: Ver 15.1 Distrib 10.11.6-MariaDB

**Comment by annando** [comment]
The created post does contain the preview picture, doesn't it? We have got some technical challenges concerning the way we perform the preview.

**Comment by haheute** [comment]
Yes the resulting post contains the picture. It is only missing in the preview.

**Comment by annando** [comment]
I know where to look and I will work at it. But I don't consider this a showstopper concerning the release.

**Comment by haheute** [comment]
Thanks. It's not urgent for me. I have only added the issue for the sake of completeness.
