### ISSUE TITLE
`/api/v1/statuses/:id/source` references mentions as `@{<name>; <account@server>}`, not `@account@server`

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13985]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Making a Mastodon API request for a status's source text with `/api/v1/statuses/:id/source` has a weird encoding for any mentions in the text.

Consider a mention of `@pachli@mastodon.social` in a status.

If I make the API call to fetch the status' source then instead of seeing `@pachli@mastodon.social` in the returned text the mention is replaced with `@{Pachli; pachli@mastodon.social}`; so it's the account's displayable name, a semi-colon, the account name (without the leading `@`, wrapped in a `@{...}`.

This was first reported by https://github.com/foss- in https://github.com/pachli/pachli-android/issues/518

### Steps to Reproduce

1.  Have an account on a Friendica server, I used pirati.ca
2.  Send a status that at-mentions another account
3.  Fetch the status' source text and inspect the result

### Platform Info

pirati.ca reports: "2.8.0 (compatible; Friendica 2024.03-rc)"

**Comment by annando** [comment]
Which format should the system return here? HTML or text?

**Comment by nikclayton** [comment]
https://docs.joinmastodon.org/entities/StatusSource/#text describes it as "plain text", so that's what Pachli is expecting.
