### ISSUE TITLE
Markers API returns non-RFC3339 datetime format in the `updated_at` field

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#13986]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The Markers API is returning a non-RFC3339 datetime format in the `updated_at` field.

### Steps to Reproduce

1.  Call the API endpoint `GET /api/v1/markers`

Actual Result:

The `updated_at` field looks like (for example) `2024-03-11 14:14:30`.

Expected Result:

For that time it should look like `2024-03-11T14:14:30Z`, there should be a `T` between the date part and the time part and a `Z` timezone marker (or offset).

I *think* the fix might be to modify https://github.com/friendica/friendica/blob/2024.03-rc/src/Module/Api/Mastodon/Markers.php#L60 and change the `utcNow()` call to `utcNow(DateTimeFormat::JSON)`, but I may very well be wrong about that.

### Platform Info

Observed with an account on pirati.ca a few moments ago, running:

Friendica Version: "2.8.0 (compatible; Friendica 2024.03-rc)"

**Comment by annando** [comment]
You found the right file, only the place has to be somewhere else.
