### ISSUE TITLE
Update Forjego instance

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13999]
As of today 2024-03-09 running 1.20.5+1 released nov 2023.

In the meantime several security relevant releases have happened. Would be nice to update Forgejo:
https://forgejo.org/releases/

**Comment by MrPetovan** [comment]
Paging @utzer for Friendica server administration.

**Comment by nupplaphil** [comment]
Done :)

`Forgejo-Version 1.21.7+0`
