### ISSUE TITLE
Add a class to the inline image div

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14012]
Recently there was a change and the inline images are wrapped inside a div that has a width equal to the inline image. This way the inline image does not become larger than it actually is. In theory it is a good addition, however since this div has no CSS class associated with it, it makes it impossible for people like me who do custom themes for Friendica, to tweak it.

I want to for example force the images to have the full width of the post, or align them to the center. Adding a class to this div will fix these issues.

Thanks!

**Comment by haheute** [comment]
@tio-trom Do you have an example post? I'm not sure which `div` you mean. When I post photos, a gallery is created.. I guess that is not what you mean.

**Comment by tio-trom** [comment]
Yes here https://social.trom.tf/display/dbc8dc44-3865-f85e-5e18-ef0121773041 - the portrait photos have a big gap in the right side and are not aligned to the center. 

![2024-03-26_13-38](https://github.com/friendica/friendica/assets/38043315/e268eda9-52c4-4edb-bbb4-67ae6369aa82)

![2024-03-26_13-39](https://github.com/friendica/friendica/assets/38043315/79b53f41-83ff-4654-8734-2512d8d37e5b)

**Comment by tio-trom** [comment]
Thank you for adding this people! You are awesome!

**Comment by tio-trom** [comment]
I finally was able to update my friendica to this version and check this thing. So it seems it does not really work here's why:

![2024-06-08_02-50](https://github.com/friendica/friendica/assets/38043315/ee2b1a6d-407d-4af0-9476-e30a2e4be82e)

The "img-allocated-heght" block is under another block that seems to put a max width depending on the image's resolution....so one cannot really tweak the image's width because the block above dictates its width.

If this can be fixed would be great. Not a big deal but I wanted to mention this. Thanks!

**Comment by MrPetovan** [comment]
The `max-width` tag will have a `img-allocated-max-width` class once version 2024.06 will be released.
