### ISSUE TITLE
Declutter the filters, channels, post types, etc. - They are overwhelming in my view.

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14031]
It is super great to be able to have such a control over what you want to see, but I think it is overwhelming. 

We have:

**Circles** - which can have multiple entries.
**Groups** - multiple choices
**Archives** - automated based on the date
**Protocols** - automated based on the protocol
**Account Types**
**Channels** - a lot of choices
**Saved Searches
Trending Tags**

This is only the left sidebar area full of these widgets.
![2024-03-23_23-51](https://github.com/friendica/friendica/assets/38043315/5da84896-32e9-44ec-a89e-63478c2301a7)

On top of this (literally hehe) we have Networks and Conversations:
![2024-03-23_23-52](https://github.com/friendica/friendica/assets/38043315/8277465b-db8c-4bae-8e89-1255baee0b3d)

Which in turn they have their own categories:
![2024-03-23_23-53](https://github.com/friendica/friendica/assets/38043315/9a74f1c3-ad4d-43c9-8dab-81d6a62a5cd3)
![2024-03-23_23-54](https://github.com/friendica/friendica/assets/38043315/b15d535b-7835-4260-823e-5b8783dcd78f)

To me that's too much I think.

My suggestion is to have one single Network page and to merge the channels into FILTERS. And all of the above to be filters that people can disable/enable much like we do for channels. And to have them all in that second top bar.
![2024-03-23_23-55](https://github.com/friendica/friendica/assets/38043315/91691995-770b-44ef-a3d8-d47e40f0b89c)

And I would even suggest dropdown lists:

**Filter**: (all of the channels options) - plus including the circles since they are similar to what custom channels do - plus global or local
**Type**: (image, video, RSS or any other protocols)
**Tags**
**Date**

This way it gives me a lot of control without being overwhelmed. I can select to see the posts made by the people who follow me, and filter by image (the type). Very cool! 

Or select to see the global posts, that are videos, and contain a tag that I select.

Or simply select to see the posts from the people I follow and that's all. 

What do you guys think?

**Comment by loma-one** [comment]
Yes, the filter options are overwhelming. It takes a well thought-out concept to change this without losing anything. It's the combination possibilities between the filters that make Friendica so powerful.

As I have not fully understood how their ideas affect the filter options or views, I have a bad feeling.

So I suggest an old feature that used to exist in Friendica but has been removed.

 - Enable/disable filters in the sidebar: 
 A setting that allows me to turn individual filter areas on and off. 
  (For example, I rarely or very rarely use areas such as "Archive", "Saved folders" or "Account types"). This allows me to fix the filters in the sidebar that I regularly need.

If necessary, it is also useful to be able to show or hide the filters in the sidebar with one click. A + or - indicates that something is hidden or can be hidden.

**Comment by annando** [comment]
@tio-trom concerning the community icon: In fact it is not needed any more, since the two communities are also accessible via the channels. In the channel list in the left you will find them.

Concerning the widgets: Yeah, there had already been complaints about the vast amount of them. In the past we had some configuration for them. But these had been configurations where admin was able to decide what the user could select or not. I don't think that an admin should control this.

I wanted to have a look at this for a long time, but priorities dragged me towards other issues.

**Comment by tio-trom** [comment]
> But these had been configurations where admin was able to decide what the user could select or not. I don't think that an admin should control this.

Agree. But at least the admin could also decide which ones are visible from the get-go, and the user can enable more. I am concerned that we will scare people with so many options. It is indeed overwhelming I feel like.

@loma-one I agree yes, would also be useful to enable/disable those side widgets. I also never use the ones you mentioned. I am unsure why I'd like to filter by the Protocol type for instance, and the account type kinda confuses me so never used that either.

Indeed Friendica stands out from the rest as this very feature-rich network platform, but things can be improved in terms of making it less scary because of so many options :)

**Comment by loma-one** [comment]
@tio-trom 
So as not to be misunderstood. The distribution of which filters are considered important and which are not varies from user to user. It is just used less frequently than other filters :)
