### ISSUE TITLE
Commented and shared contents of threads are not displayed correctly

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14030]
### Is the feature request related to a problem? Please describe.

Threads uses a method from Misskey to comment and share posts: https://misskey-hub.net/ns/

It is written in this blog post from Instagram: "Federating quote posts": https://engineering.fb.com/2024/03/21/networking-traffic/threads-has-entered-the-fediverse/

It might be a good idea to additionally support this method in order to achieve a good appearance for shared posts again.

Currently the shared content looks like this: 

![2024-03-23_18-29](https://github.com/friendica/friendica/assets/44441246/4bfb2a33-1d07-41c9-8029-12fe2e4f242f)

https://www.threads.net/@lilkioko/post/C43RrWpr4UhomSkdZm8YE2-pkti8jVAqIgGZFE0

**Comment by annando** [comment]
We already support the way, Misskey does quoted posts. We have to see what's the reason for that behaviour.

**Comment by annando** [comment]
Update: We had a problem with the Misskey support. A PR will follow soon.
