### ISSUE TITLE
Addon 'Showmore Dynamic' deactivated in Admin Settings, but still active for posts

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#14045]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I have activated the `Showmore Dynamic` Addon in Admin --> Addons to test something and then again deactivated it.
The checkbox there is now _unchecked_, but my posts are still shortened by the addon. 

### Steps to Reproduce

Activate and deactivate the addon as described.

#### Actual Result:

The posts are still collapsed, and there is a "Show more.." text. A hard reload of the page did not help.

#### Expected Result:

The addon should be turned off, and the posts should be in full size again

### Platform Info

Friendica Version:  2024.06-dev
Datenbankversion: 1559/1559 
Post-Update-Version: 1550/1550

PHP version: 8.2.17

SQL version: Ver 15.1 Distrib 10.11.6-MariaDB

**Comment by haheute** [comment]
I have different kinds of "paths" for the `file` column in the `hook` table:

![Bildschirmfoto_2024-05-10_12-35-49--addons-uninstall](https://github.com/friendica/friendica/assets/5753419/7fc0eb36-e458-4900-8c48-b006efda7f7b)

Those with `/var/www/localhost/friendica/addon/{addon}/{addon}.php` are those, which I can _not_ uninstall.
Those with `addon/{addon}/{addon}.php` _can_ be uninstalled and installed.

I wonder why there are different paths or values for the `file`column..

Here are the different kinds of `Hook::register(..);` of the addons `.. _install()` functions:

blockbot:
```
Hook::register('init_1', __FILE__, 'blockbot_init_1');
```
blackout:
```
Hook::register('page_header', 'addon/blackout/blackout.php', 'blackout_redirect');
```
catavatar: 
```
Hook::register('avatar_lookup', __FILE__, 'catavatar_lookup');
Hook::register('addon_settings', __FILE__, 'catavatar_addon_settings');
Hook::register('addon_settings_post', __FILE__, 'catavatar_addon_settings_post');
```
showmore_dyn:
```
Hook::register('page_end',  __FILE__, 'showmore_dyn_script');
Hook::register('head', __FILE__, 'showmore_dyn_head');
Hook::register('footer', __FILE__, 'showmore_dyn_footer');
Hook::register('addon_settings',  __FILE__, 'showmore_dyn_settings');
Hook::register('addon_settings_post',  __FILE__, 'showmore_dyn_settings_post');
```
openstreetmap:
```
Hook::register('load_config',     'addon/openstreetmap/openstreetmap.php', 'openstreetmap_load_config');
Hook::register('render_location', 'addon/openstreetmap/openstreetmap.php', 'openstreetmap_location');
Hook::register('generate_map', 'addon/openstreetmap/openstreetmap.php', 'openstreetmap_generate_map');
Hook::register('generate_named_map', 'addon/openstreetmap/openstreetmap.php', 'openstreetmap_generate_named_map');
Hook::register('Map::getCoordinates', 'addon/openstreetmap/openstreetmap.php', 'openstreetmap_get_coordinates');
Hook::register('page_header', 'addon/openstreetmap/openstreetmap.php', 'openstreetmap_alterheader');
```


Those with `addon/..` work for me, and those with `__FILE__` do not. That means:  I have uninstalled `catavatar` and `showmore_dyn` in the admin panel, and the admin panel said: "ok, successfully uninstalled" and also shows the checkboxes unchecked.. looks okay. But in the user settings, still, `showmore_dyn` and `catavatar` are visible. And, for example, `showmore_dyn` still shortens the posts.. 

Only thing is.. How to fix this? (In the best way..)

**Comment by MrPetovan** [comment]
I've identified the bug with the automatic unregistration of addon hooks, I'll have a patch soon.
