### ISSUE TITLE
Artifact at the point where the number of new contributions should be.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#14049]
Artifact at the point where the number of new contributions should be.
Is that only for me that way?
Can i fixed this somehow?
Clearing the page cache didn't help.
![2024-03-28 14 59 03](https://github.com/friendica/friendica/assets/142184406/c34574da-61b2-4b4c-89a2-af2a805cde87)

**Comment by MrPetovan** [comment]
I had this when I updated to the latest `develop` and my browser cache wasn't cleared. Clearing it removed the artifact. I don't have any other suggestion.

**Comment by ghost** [comment]
Yes, that helped. I didn't do it thoroughly enough beforehand.
