### ISSUE TITLE
[Bluesky] Display of third-party content through interactions of contacts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14057]
- [X] I have searched open and closed issues for duplicates

### Bug Description

- The Bluesky addon is activated. 
- Posts from Bluesky are imported
- Under Social networks > Scope of the following content, "Only conversations that my contacts have started" is activated.
- Posts are imported with which my contacts have interacted on Bluesky

These errors may belong together https://github.com/friendica/friendica/issues/13952

Expected Result:

- Only posts from direct contacts are imported. 
- Posts with which my contacts have interacted are not imported into the timeline

### Screenshots
Setting
![42075867](https://github.com/friendica/friendica/assets/44441246/d9378233-e4c3-4014-92b6-f137e909942c)

Post imported by Bluesky
![42075224](https://github.com/friendica/friendica/assets/44441246/c2142b2b-6016-4d65-bf17-00dc8eba7332)

ASP: @inventum@anonsys.net (User)
ASP: @tuxadmin@anonsys.net (Admin)

### Platform Info

Friendica Version: 2024.03 anonsys.net

**Comment by annando** [comment]
The setting does not control the behaviour with connector networks. Here you have to change the behaviour inside of Bluesky.

**Comment by loma-one** [comment]
Mit der Erklärung von @annando ist der Issue hier abgeschlossen
