### ISSUE TITLE
Forums - "Link to Source" URL should link to the forum server

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#14055]
Writing a post to a forum means, that the forum takes over the ownership of the post (not the content) and redistribute it. 

![Friendica Forum](https://github.com/friendica/friendica/assets/24474762/16cc750c-0e9f-462b-a521-04d621bf347a)

But if you click on the "Link to Source" button on the right side you are lead to the original posters server, instead to the forum server. This is illogical and wrong, because the technical owner should be as well the content provider.

One very natural reason is, that instances come and go and then it is a very hard task to follow a conversation for a normal user.

So the "Link to source" should always point to the post on the forums server.

**Comment by MrPetovan** [comment]
Huh, that's a good observation.

**Comment by annando** [comment]
I just realized that this could be more complex that I thought. We only receive the "Announce" activity with no hint to link where it is published. I have to see, how I can safely do this, especially since we not only support posts from Friendica, but from other systems as well.

**Comment by MrPetovan** [comment]
Can we just rely on the `guid` and generate the forum link based on the following schema: `<forum base URL>/display/<post GUID>`?

Edit: Ah, let me guess, it wouldn't work for non-Friendica posts reshared by the forum?

**Comment by annando** [comment]
Posts from most AP systems don't contain a `guid`. We generate a dummy guid for them.
