### ISSUE TITLE
Resolution 1024x768  - fix avatar

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1405]
<a href="http://upimage.mamalibre.com.ar/#040533ba99bc2a825e14501707e0d763.png"><img src="http://upimage.mamalibre.com.ar/up/040533ba99bc2a825e14501707e0d763.png" alt="Image hosting by Imagebin" /></a>

**Comment by annando** [comment]
I'm confused. What exactly is the problem? What is this picture where you point with an arrow to?

**Comment by mama21mama** [comment]
the picture should be next to the profile name. if you look closely this below the name.

**Comment by mama21mama** [comment]
<a href="http://upimage.mamalibre.com.ar/#68e8d984081387df12e58ef1f47c8375.png"><img src="http://upimage.mamalibre.com.ar/up/68e8d984081387df12e58ef1f47c8375.png" alt="Image hosting by Imagebin" /></a>

**Comment by annando** [comment]
This seems to be a problem in the theme Diabook. This theme is marked as "unsupported" since there is no current maintainer.

**Comment by annando** [comment]
Since Diabook is unsupported I will close this issue.
