### ISSUE TITLE
[FRIO] highlighting effect when calling comment with dark themes too bright

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14052]
The coloured highlighting when calling up a comment via the bell is a good function for quickly finding the position.
However, in a dark theme and when the eyes have become accustomed to the darkness, it feels like a laser beam trying to burn out the eyes.

The highlighting is controlled at this point: https://github.com/friendica/friendica/blob/31b74b1c8a2c92137e4b61ae9fde69abb94b772d/view/theme/frio/js/theme.js#L743

Question: 
- Is there a way to control the effect in a theme via a CSS instruction?
- Alternatively, is it possible to control this effect separately for light and dark themes?

https://loma.ml/display/373ebf56-1166-031a-53cd-b2e686160001

**Comment by MrPetovan** [comment]
For these to be depending on the theme, the declaration of the variable would have to be in a place that is controlled by the theme. We have some JavaScript variables initialized in template files, however there aren't any provisions to pass scheme-defined variables to any template at the moment, so I'm a little stumped.

**Comment by loma-one** [comment]
Perhaps it is already sufficient if a value is stored at the relevant code point that represents a compromise for light and dark themes.

I have done it with the values

```
	// Define the colors which are used for highlighting
	var colWhite = { backgroundColor: "#7f7f7f" };
	var colShiny = { backgroundColor: "#7e763a" };
```

and it seems to be more pleasant. However, I am sure that the choice of colour can be better.

**Comment by MrPetovan** [comment]
This is a good first step, however finding values that work in all three official schemes (light, dark and black) is a challenge. Any improvement is welcome though. Would you mind posting screenshots of the new colors in all three schemes?

**Comment by loma-one** [comment]
This is of course a flowing colour gradient and the effect looks friendlier than shown here.
In principle, only the brightness peaks have been removed here.


![2024-04-04_13-34](https://github.com/friendica/friendica/assets/44441246/f14a72e8-0b2d-43bc-8c92-7b41ee1f0051)
![2024-04-04_13-35](https://github.com/friendica/friendica/assets/44441246/21a53a3e-704e-433f-812f-63c5d4e7dc6e)
![2024-04-04_13-36](https://github.com/friendica/friendica/assets/44441246/8e656961-f80b-44fd-8b69-8f0d5ed65ec5)

**Comment by MrPetovan** [comment]
Looks fine to me!

**Comment by AlfredSK** [comment]
World it be possible to do the highlighting with a flashing colored margin instead?

**Comment by MrPetovan** [comment]
Yes but it would be more work than just tuning the colors of the current highlighting.
