### ISSUE TITLE
Extension of the editor function with the SCEditor

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14065]
### Is the feature request related to a problem? Please describe.

For the majority of new users, formatting texts using BBCode and Markdown is a major challenge. Friendica is perceived as complex and only for technically experienced users. Despite the clear advantages of Friendica over other Fediverse projects, users fail due to the critical handling and leave their account.

### Describe the feature you'd like

The SCEditor appears to be a very impressive BBCode editor that offers many functions that go very well with Friendica. 
- Written content is displayed directly in its formatted state. A preview is not required
- All BBCode formatting options supported by Friendica are accessible via a menu selection
- The "Maximise" function allows the editable area to be extended to the entire screen (a dream)
- The position of images can be checked (without preview)

It may make sense to provide an add-on that complements the editor functions and thus offers a very convenient way to create, change and publish content.

The SCREditor is published under an MIT licence
https://github.com/samclarke/SCEditor

**Comment by tobiasd** [comment]
I think this is a duplicate of #9848

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/9848
