### ISSUE TITLE
Shortening of overlong URL links in posts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14079]
### Describe the feature you'd like

Shared links can sometimes be very long. It would therefore be an advantage if a link is never longer than one line.
If the link is hovered over with the mouse, the complete URL should be displayed (e.g. footer of the browser).
It may make sense to offer the shortening of the URL as an option.
See also the discussion under https://loma.ml/display/373ebf56-8466-115b-512c-132009782211

**Comment by annando** [comment]
It now looks that way:
![image](https://github.com/friendica/friendica/assets/844208/7d500b99-8abf-402d-ae0f-58e04962fb7c)
