### ISSUE TITLE
Follow and unfollow problems - Klick on button leads to remote server instead of following or unfollowing

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#14078]
- [ ] I have searched open and closed issues for duplicates

### Bug Description

Searching a contact and try to follow or unfollow this contact sends you in browser to remote instance but does not follow or unfollow.

### Steps to Reproduce

1.  Search some contact
2.  Open this contact
3.  Klick "Follow" (if you are not following this contact) or "Unfollow" (if you are following this contact)

Actual Result:

On Pleroma-, Calckey- and Threads-Accounts:
You land after the Klick on the remote instance on the userprofile. Friendica does no action follow or unfollow.

This happens NOT on pixelfed-, and peertube-Accounts. There it works as expected.

Expected Result:

I can follow or unfollow this contact (depending of not following or following the contact before)

Other services i've not tested.

### Platform Info

Friendica Version:

Friendica: 2024.06-dev (commit: e9dcf15d86)
Database: 1559/1559
Post-Update-Version: 1550/1550

Friendica Source: 

PHP version: 8.3

SQL version: mariadb-server 1:10.11.6-0+deb12u1 (debian bookworm)

**Comment by annando** [comment]
On which page have you executed the `follow` functionality?

**Comment by xundeenergie** [comment]
I did a search.
Then i clicked on a Searchresult, which shows the contact.
Then in the sidebar i klicked on Follow (or Unfollow).

**Comment by annando** [comment]
Is "stay local" enabled?

**Comment by xundeenergie** [comment]
Yes it's enabled.

First i thougt it is a Problem of my Browser. But then i realised, it happens on my Smartphone on on Laptop.

**Comment by xundeenergie** [comment]
Today i tried to follow this RSS-Feed
https://www.bahn87.de/rss.php
And i can not follow this Feed... 

I tried to search in searchfield for this url: Friendica does not give me a searchresult, instead it opens the feed-url in the browser-window.
I tried to add the feed-url as new contact... the same. Friendica opens the feed-url instead of presenting a search-result.

In browser-console in firefox i get this messages only, when trying to add rss-feed as contact:

```
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
[rss.php](https://www.bahn87.de/rss.php)
Speicherzugriff erlaubt für Isolierung von Ressourcen gleichen Ursprungs: "https://soc.schuerz.at/" auf "https://www.bahn87.de/". [rss.php](https://www.bahn87.de/rss.php)
```

​

**Comment by xundeenergie** [comment]
Ok... it seems, it's a firefox-issue... 

In chromium i can follow... 

But i did not change any settings in firefox. And it appears in desktop (flatpak 123.0 (64-Bit)) and smartphone-version (from f-droid).

**Comment by xundeenergie** [comment]
I upgraded firefox on my smartphone, now i works as expected.
Firefox from flatpak is upgrading.

**Comment by annando** [comment]
Hmm, is it possibly some extension?

**Comment by xundeenergie** [comment]
Yes... i deactivated now the "Skip redirect" (https://github.com/sblask-webextensions/webextension-skip-redirect) extension. Now i can follow.

But the "Unfollow" Button below the avatar-image on the contact-page does not work. I have to unfollow in the "Actions" menu.

**Comment by xundeenergie** [comment]
It was the Firefox-Addon "Skip redirect". So no Friendica-problem.
