### ISSUE TITLE
RSS contacts: Fediverse compatibility setting - mirror posts without title/headline

### ISSUE THREAD

**Issue by forenta** [friendica/friendica#14081]
### Description of the problem:

For various news sources, I have created accounts that mirror RSS feeds so that the information about the sources is available to everyone in Fediverse.
Problem: Friendica also posts a title for each post by default. Most followers follow the accounts from the _Mastodon_ software - however, this does not support titles and if a title exists for a post, it does not display the post, just the title and a link to the Friendica post.
Example post [here](https://squeet.me/display/962c3e10-4866-1281-b200-242209733457) - how it is displayed on Friendica:
![image](https://github.com/friendica/friendica/assets/2451238/7ae3cc76-17cb-4ab3-baa1-2f25ad28b9f0)
On Mastodon:
![image](https://github.com/friendica/friendica/assets/2451238/45d6eb47-7bfb-48d5-bc86-d697d4c216b9)

### Describe the feature you'd like
Add compatibility mode: Mirror the RSS feed-items, but ignore the title:
![image](https://github.com/friendica/friendica/assets/2451238/ce18ef9b-a2d4-4930-a9e7-befbbc26dba5)

_Premium solution_: Optional move the items _title_ to the _content_ of the post:
`post = <title> + "\n" + <content>`

### Describe alternatives you've considered

If mirrored with the option _Fetch information_ enabled, the post contains no title, but the content Friendica gets from the linked article.
In some cases, this option solves the issue, but in _most_ cases, there are no summaries available (e. g. typical WordPress-blogs). So instead of posting the summary within the RSS-feed, the post contains the first 250 letters of the article and cuts the rest in the middle of the sentence.
![image](https://github.com/friendica/friendica/assets/2451238/364a25df-9c2b-4030-8af1-1825aaccfb83)

**Comment by kr428** [comment]
+1 from here. For integrating and re-sharing RSS posts, it would be nice to have at hand options like these (shamelessly screenshot from EchoFeed) where one essentially is capable of configurating how such a feed share should look like:

![image](https://github.com/friendica/friendica/assets/685879/1266bc76-88a1-46c8-932c-c7ac1fd27316)

Really would be amazing to have this baked right into Friendica, though I'm unsure whether this is beyond the scope of the platform.

**Comment by forenta** [comment]
**Bounty offered**: I threw 30$ into the pot for this one. Deadline 01/20/25.
https://gitpay.me/#/task/802

**Comment by forenta** [comment]
Solved by @annando, available in 2024.06-dev.
https://github.com/friendica/friendica/pull/14195

**Comment by alexanmtz** [comment]
Hey @annando , you fixed this issue successfully 🚀

 You can claim your bounty by visiting this issue on Gitpay: https://gitpay.me/#/profile/task/802/rss-contacts-fediverse-compatibility-setting-mirror-posts-without-title-headline

You can paste the merged PR on the "Solve Issue" and "Send Solution" tabs, and the Bounty process will be initiated.

But one of our requirements is having the issue mentioned on the PR, can you refer this one in your PR.

Let me know if you need any help.

**Comment by MrPetovan** [comment]
Thank you for the follow-up, I just edited the relevant PR to mention this issue.

**Comment by annando** [comment]
@alexanmtz there seem to be issues:
![image](https://github.com/friendica/friendica/assets/844208/1cce90fa-0225-4432-8825-a8820145a81d)
![image](https://github.com/friendica/friendica/assets/844208/a38176a2-3b65-430e-a09e-0cb9ff1826c7)

**Comment by forenta** [comment]
@annando You need to link the Pull Request `https://github.com/friendica/friendica/pull/14195`, not the issue.

**Comment by kr428** [comment]
Thanks very much. Really happy to see this feature added, but ... what do I need to make use of it...? 🙈

**Comment by forenta** [comment]
> what do I need to make use of it...? 🙈

Settings >  Social Networks > General Social Media Settings > Article Mode
