### ISSUE TITLE
Service Actors Don't Have an Inbox or Outbox Collection

### ISSUE THREAD

**Issue by 4tuw2tuv0** [friendica/friendica#14084]
- [x] I have searched open and closed issues for duplicates

### Bug Description
This is more an ActivityPub compatibility issue (than an active bug Friendica users may visibly encounter) but it doesn't seem, to me, like Services have their required Inbox/Outbox endpoints.

I pulled the `application/ld+json` of https://soc.schuerz.at/profile/jakob and, under `generator`, there's a service but those endpoints aren't provided; if I understand the AP spec. correctly, they're required to as Actor objects _MUST_ have an Inbox and Outbox (https://www.w3.org/TR/activitypub/#actor-objects) and, according to the AS spec., a Service is a type of Actor (https://www.w3.org/TR/activitystreams-vocabulary/#actor-types).

### Steps to Reproduce

1.  Pull the JSON-LD of any Friendica object containing a Service, I'd expect (admittedly, I have not check all of them)
2.  Look for an Inbox or Outbox endpoint, on the Service

**Actual Result:**
Cannot find any.

**Expected Result:**
Should be able to see both.

### Screenshots

![2024-04-07T15:56:52,297556963-05:00](https://github.com/friendica/friendica/assets/10533934/41691019-38a6-488a-a104-0d84a7970892)

### Platform Info

**Friendica Version:**
2024.06-dev

**Friendica Source:** 
Not sure.

**PHP version:**
Not sure.

**SQL version:**
1559/1559

**Comment by annando** [comment]
The example for `generator` at https://www.w3.org/TR/activitystreams-vocabulary/#dfn-generator is even missing the `url`. So my assumption is that you don't need to provide all the information there.

**Comment by 4tuw2tuv0** [comment]
I think that's more because `url` isn't a required field than because it was leaving out information (but, even if we assumed that it had the info. but it just wasn't presented, there's no ID attached to the Service so there's no way to access or look that info. up).

If `url` was a requirement of Object (and, in turn, any Actor and, in turn, a Service), I'd expect the spec. _would_ have the field present in the example (as I think any values it is assumed that an Object has _should_ be present if it's dereferenced).

The ActivityStream spec., though, wouldn't necessarily provide any good examples as the requirement of the Inbox and Outbox are a requirement of ActivityPub, in its extension of ActivityStream.

So it's accurate to say that these Collections aren't a requirement in ActivityStream but very much so in ActivityPub.

(sorry if it sounds like I'm repeating the obvious multiple times; trying to make sure I'm communicating clearly)

**Comment by annando** [comment]
With the attached PR the `id` is now present, so additional information can be fetched. I prefer to only transmit data that is really needed for the communication, so I would like to omit all stuff that isn't needed to transmit a note, a like, ...

**Comment by 4tuw2tuv0** [comment]
Fair enough; as far as I can tell, neither spec. has a prohibition regarding that (and it'd probably be a non-issue due to the _SHOULD_ regarding dereferencing to make sure the data is accurate, in the AP spec.).

As long as the ID is there and fetchable, I think that addresses the issue. Thanks so much!
