### ISSUE TITLE
Threads: Videos are not loaded. CDN reports "URL signature expired"

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14092]
- [x] I have searched open and closed issues for duplicates

### Bug Description
If an account with an embedded video is loaded in Friendica from Threads, the most recent video is displayed. 
If you scroll through the timeline and land on older content with an embedded video, it is not displayed.

The Firefox console reports:

```
HTTP load failed with status 403. Load of media resource [https://scontent-fra5-1.cdninstagram.com/](https://scontent-fra5-1.cdninstagram.com/o1/v/t16/f1/m69/GICWmADsBWvkeOsDAFTaKR9Pn7xzbpR1AAAF?_nc_ht=scontent-fra5-1.cdninstagram.com&_nc_cat=102&vs=730822359244394_4183460442&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HSUNXbUFEc0JXdmtlT3NEQUZUYUtSOVBuN3h6YnBSMUFBQUYVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dJM1NFUnJ4VnZOM0Vrb05BTjJyajBZa2lkVlJia1lMQUFBRhUCAsgBACgAGAAbAYgHdXNlX29pbAExFQAAJqSFy5Xjj5NAFQIoAkMzLBdAUUxaHKwIMRgWZGFzaF9iYXNlbGluZV8xMDgwcF92MREAdeoHAA&ccb=9-4&oh=00_AfBip859xNAsoIwQDEnvJTAl2L5ydXH9rqeaoA5NtrxrXw&oe=661A5690&_nc_sid=1d576d&_nc_rid=50a0932d29)
```
If the link is called up in the browser, the message "URL signature expired"

### Steps to Reproduce

1. call @potus@threads.net
2. scroll to the first video (is ok)
3. scroll to the second video (is not ok)

Actual Result:

Expected Result:

### Screenshots
![2024-04-13_12-55](https://github.com/friendica/friendica/assets/44441246/ad15ff82-bb34-4ff7-a96d-b501994502a7)

### Platform Info

Friendica Version: stable/(dev - 1559/1559 Post-Update-Version 1550/1550.)

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
We have to have a look at it. It is possible that the URL to the videos and images are temporary only. For storage reasons we don't store the image data locally, but only pass them through a proxy. So when these links were temporary only, we had to store this data - which would result in a much higher storage space needed for Friendica systems.

**Comment by loma-one** [comment]
The problem seems to be easing. Videos will now continue to be displayed and played even after 24 hours. It could have been a CDN error
