### ISSUE TITLE
Auto-complete emoji in handles and posts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14106]
There was a feature that used to collect emoji from the removed instances to fill in missing emoji in posts or in the handle of accounts. 

Since the stable and also in the dev, this feature doesn't seem to be active anymore. Presumably this is an addon that needs to be activated on the instance. Which addon ensures that missing emoji are loaded from the removed instances?

![2024-04-20_22-13](https://github.com/friendica/friendica/assets/44441246/a8f3eb87-8799-4807-bf0d-6c67170d3598)

**Comment by annando** [comment]
We currently don't support custom emojis in contact names.

**Comment by MrPetovan** [comment]
More precisely, we've never supported custom emojis in contact display names. There's an open issue outlining the technical requirements: https://github.com/friendica/friendica/issues/11991
