### ISSUE TITLE
Moderation reports for posts are not showing

### ISSUE THREAD

**Issue by TheTomcat14** [friendica/friendica#14110]
### Bug Description

Moderations reports for post are not shown in the "Moderation" > "Information" > "Reports" page.

This seems to be caused by an error in the SQL query that fetches the reports.

The reports are fetched in https://github.com/friendica/friendica/blob/fe9ef2039272fd26712b53f238a7983e0f15ba4e/src/Module/Moderation/Reports.php#L59-L61

The SQL query includes the columns `report`.`category` & `report`.`rules`, these columns do not exist in the `report` table.
The SQL query throws an error.

I've changed the query to: 
```
SELECT `report`.`id`, `report`.`cid`, `report`.`comment`, `report`.`forward`, `report`.`created`, `report`.`reporter-id`,
`report`.`category-id`, 
(
    SELECT GROUP_CONCAT(`report-rule`.`text` ORDER BY `report-rule`.`line-id` SEPARATOR \"\n\") 
    FROM `report-rule` 
    WHERE `report-rule`.`rid` = `report`.`id` 
    GROUP BY `report-rule`.`rid`
) AS `rules`, 
`contact`.`micro`, `contact`.`name`, `contact`.`nick`, `contact`.`url`, `contact`.`addr` FROM report
INNER JOIN `contact` ON `contact`.`id` = `report`.`cid`
ORDER BY `report`.`created` DESC
LIMIT ?, ?
```

* The `category` field was changed to `category-id`. (Extra code is needed to transform the id in a text representation, the category names are set hard-coded in the source, they are not stored in the database)
* The `rules` field was changed to a subquery selecting them from the `report-rule` table, in order to fetch them in one field. (Extra code is needed to show the rules field in the interface, the template does not show them)

### Steps to Reproduce

1.  File a couple of reports on some posts
2.  Go to "Moderation" > "Information" > "Reports"

Actual Result:

No reports are shown

Expected Result:

A table showing an overview of the reports.

### Platform Info

Friendica Version: Friendica 'Yellow Archangel' 2024.03 - 1557

PHP Version: PHP 8.1.24

**Comment by MrPetovan** [comment]
Thank you for your report, would you like to submit a patch in your name or would you prefer I take over from your work?

**Comment by TheTomcat14** [comment]
I currently don't have a friendica github clone setup to make a pull request. (I'm using the zip file from [files.friendi.ca](https://files.friendi.ca/))
I'm fine with you taking over this bug.
