### ISSUE TITLE
Import filter for each contact

### ISSUE THREAD

**Issue by zotheco** [friendica/friendica#14127]
### Is the feature request related to a problem? Please describe.

No

### Describe the feature you'd like

A good option would be to create an import filter for each contact. If I follow a news agency, I would like to import only certain topics. Hubzilla has this feature and I would like to see it in Friendica.

**Comment by MrPetovan** [comment]
What do you mean by "topic"?

**Comment by zotheco** [comment]
Let's assume I like to travel to Italy and follow an account of a travel guide. In the contact, I would like to specify that only all posts containing the word 'Italy' are imported from this account.

**Comment by loma-one** [comment]
If you follow an account on Hubzilla, you can specify which terms (hashtags) from this account should be displayed, or whether terms from this account should be filtered.

**Comment by MrPetovan** [comment]
It looks like you could achieve this with the Custom channels, but all the account's posts would still land on your regular Network page.

**Comment by zotheco** [comment]
> It looks like you could achieve this with the Custom channels, but all the account's posts would still land on your regular Network page.

The key difference is that the procedure proposed by Channel first imports all the data and then filters the required data afterwards. In terms of the concept, it is a different approach whether I decide that I only want this or that data.
In the worst case, the solution via channels would mean that I would have to create 100 filter channels for 100 accounts.

**Comment by MrPetovan** [comment]
Channels don't import any data, they rely on the data that your node already received from remote accounts. And yes, I'm aware that's a different approach, but I expect you'd rather have something usable right now rather than a feature request that may well never been built.

**Comment by zotheco** [comment]
Thank you for your response.
