### ISSUE TITLE
[frio] Sluggish scrolling and heavy load on Mastodon profiles

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#14156]
Hard to really report or describe this. In quite a lot of cases, it seems the Friendica web frontend has some performance issues when scrolling through a local view of a Mastodon profile. Like, in example, this one... 

https://mastodon.social/@Muetzenfalterin

... which boils down to this one ...

https://loma.ml/contact/1929547/conversations

... on my instance. Effect, in most of these cases:

- Scrolling down the page stutters and feels utterly slow.
- CPU and memory load noticeably increase.

Generally, this isn't really usable at the moment so I have to choose alternative web frontends to browse profiles and comment there. This problem doesn't seem to happen in any kind of public, network, channel, ... timeline. It seems visible on all browsers but more severe on those based on Chrome (using Brave as my main driver here). Seen this on both Fedora 40 / GNOME / Wayland and Ubuntu 23.10 / X11 / KDE so supposedly it's not an issue of display / environment. Anyone able to reproduce this?

**Comment by foss-** [comment]
Could not reproduce no pirati.ca. Looking at Conversations tab of profile https://mastodon.social/@Muetzenfalterin scrolled flawlessly. There are not that many posts with the oldest from 1 year ago.

This is Friendica, version 2024.06-dev that is running at the web location https://pirati.ca. The database version is 1560/1560, the post update version is 1550/1550.

**Comment by kr428** [comment]
Hmm. Strange. What about https://leipzig.town/@Friedi then? This seems even worse here. (loma.ml is on Friendic 2024.03 for what I know.)

**Comment by annando** [comment]
Could the problem be some Chrome addon that you activated?

**Comment by kr428** [comment]
> Could the problem be some Chrome addon that you activated?

Don't think so. Happens in Brave with some addons but also in vanilla Linux Chromium with cache cleared on exit and no extension whatsoever installed...

**Comment by kr428** [comment]
Will close this by now. It is reproducible and slows down my Chrome based browsers again and again, but in current 2024.0x release, it seems if I wait a while (seconds...a minute), whatever is happening here is coming to an end and then the profile can be displayed and scrolled correctly. Fine with me so far.
