### ISSUE TITLE
Enough with the reboosts!

### ISSUE THREAD

**Issue by snan** [friendica/friendica#14153]
I'm on Akkoma and here's what happens:

Some jerk replies to me in a thread and I see their reply in my timeline and that's fine and normal and I can reply to it if I so choose.

What then happens is not so cool: Friendica users that then boost that reply cause the post to reappear into my timeline. So I get to see it again and again everytime a Friendica user boosts it. Friendica users that I don't follow or haven't even heard of get to re-inject it into my timeline. Quit that please. Feel free to boost 👍🏻 but no need to post it to my /inbox is what I'm saying. I've already seen it and I'm not following the user.

**Comment by annando** [comment]
To understand what you mean: When someone reshares one of your posts you don't want to get notified about this? ("boost" means "reshare", I guess)

From my point of view I would consider it as impolite to not being informed about a post being reshared.

**Comment by snan** [comment]
When people reshare my own posts I do get notified of that and that's fine. That's not the issue.

Instead here is the problem:

I write on Fedi a normal and popular post.  
Some jerk replies with something mean.  
Friendica users whom I never have heard of boost the jerk's reply.  
(So far, so normal.)  

I then get that jerk's mean reply sent into my timeline again every time a Friendica user (even people I've never heard of) boost that mean reply. That is the problem.

**Comment by annando** [comment]
So as far as I understand your issue is when someone reshared a comment that's not from you, but where you had been mentioned?

**Comment by snan** [comment]
Yes, that describes the issue

**Comment by annando** [comment]
We did some changes in the past with how we distribute activities like an `Announce`, so it would be good to have a look at the software versions of these systems. Do you have got a handful of systems at hand where this came from? Then I can check if these are newer or older systems. Possibly it is already solved and it's just an issue of older systems.

**Comment by snan** [comment]
On their end: 2024.06-dev, database version 1560/1560, post update version 1550/1550 🤷🏻‍♀️ 
On my end Akkoma 3.13

**Comment by annando** [comment]
Meh ... Okay, that is the current development version. Thanks for looking that up. I thought that I had changed something there, when I had a look at the channels.
