### ISSUE TITLE
Liking a post mentioning a Friendica user should not add you to the audience for further replies/announces

### ISSUE THREAD

**Issue by trwnh** [friendica/friendica#14160]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I am receiving activities from someone I do not follow, pertaining to a conversation I did not participate in, unless you count liking a post mentioning a user to be participation and/or grounds for receiving further conversation updates

### Steps to Reproduce

1. Use software that federates Like activities to actors other than the author of the liked post (e.g. Akkoma/Pleroma, etc)
2. Like a post mentioning a Friendica user (the post need not be on Friendica)

Actual Result:

I am now receiving every single update to the conversation in my inbox, including replies to+from users I do not follow, and announces by users I do not follow.

Expected Result:

Liking a post in a thread should not be equivalent to subscribing to that thread.

### Screenshots

![image](https://github.com/friendica/friendica/assets/10606431/d0f606b4-46eb-40e7-b23c-648a41a267e3)

![image](https://github.com/friendica/friendica/assets/10606431/7bc392c9-bd44-44b6-b2ba-48b74c63bc0c)

![image](https://github.com/friendica/friendica/assets/10606431/db2ddfd1-ccc8-4b3d-a270-9cf02783a983)

![image](https://github.com/friendica/friendica/assets/10606431/fb5a3d85-0975-42d7-9a27-c9fb756f9dc1)

### Platform Info

Friendica Version:

> This is Friendica, version 2024.06-dev that is running at the web location https://libranet.de. The database version is 1560/1560, the post update version is 1550/1550.

**Comment by tobiasd** [comment]
Please have a look into your users settings -> Notification settings and check if the *Someone commented in a thread where you interacted* is enabled or not. Assuming it is, then it is working as expected as your "Like" is an interaction with the thread.

**Comment by trwnh** [comment]
@tobiasd I don't have that setting as I am not using Friendica. The issue is with the activities being sent out by Friendica. They should not be delivered to me just because I liked a post merely *mentioning* a Friendica user. The bar for interaction should be much higher than that. Especially seeing as there is no way to "unsubscribe" from the thread remotely.

**Comment by tobiasd** [comment]
I see, then I misunderstood your report - sorry!

**Comment by foss-** [comment]
Wouldn't this be a feature request for Akkoma then if that is where your account is?

**Comment by trwnh** [comment]
@foss- it's a request for friendica to reconsider and/or revert a recent change. interacting once should not be taken as a signal to subscribe someone to an entire thread in perpetuity. espcially not if the "interaction" was a passing Like.

it would be different if i had expressed interest in being updated about the thread, say, for example, if there was a collection representing the thread and i sent a Follow to it. i might even understand if replying/commenting to a thread auto-subscribed me to the thread (provided that there was a way to remotely unsubscribe). but a mere Like of a mention is going too far.
