### ISSUE TITLE
Unable to connect/follow channel on streams repository

### ISSUE THREAD

**Issue by macgirvin** [friendica/friendica#14163]
[x] I have searched open and closed issues for duplicates

### Bug Description

Unable to follow streams account/channel. This worked last year sometime. Error text is "The network type couldn't be detected. Contact can't be added." Possibly the result of being a generic ActivityPub service with no brand identity and no nodeinfo tracking service. 

### Steps to Reproduce

1. Attempt to follow/add test@fediversity.site

Actual Result:

"The network type couldn't be detected. Contact can't be added."

Expected Result:

Contact is added. Possibly with 'unknown' or 'activitypub' as the server/network type. 

### Platform Info

Friendica Version:

This is Friendica, version 2023.12 that is running at the web location https://social.trom.tf. The database version is 1542/1542, the post update version is 1507/1507.

**Comment by tobiasd** [comment]
Maybe you see a follow request from me? With the current development version of Friendica I could send out a follow request.

![image](https://github.com/friendica/friendica/assets/433490/29994602-97f1-4573-b074-15aaac2c18c3)

**Comment by macgirvin** [comment]
Cool. I'll just have to wait for trom to update. Thanks. You can close this.
