### ISSUE TITLE
Connector publishes even posts in hidden FB-Groups to Stream

### ISSUE THREAD

**Issue by heyme-itsyou** [friendica/friendica#1416]
Hey there,

first of all...I´m a newbie on Friendica, in Webhosting, on Github...in digital Life I´d say...so I hope I can express the matter properly ;)

I installed Friendica on Uberspace and activated the FB Connector. Now it publishes all of my FB Posts in my stream - even those from hidden groups. Is there any possibility to change settings in order to limit the publication to public posts? 

thanks for any comment,
gruesse from germany :)

**Comment by silke** [comment]
Just to clarify: Your Friendica posts that are published to a specific group of people all go out to Facebook - correct?

I don't have the Facebook connector to test. This is what I'd do for the Twitter connector: Turn off the setting that sends *every* post to Twitter, then select whom it should be visible for. For Twitter this works. Is the FB connector made similarly and it's broken? Or did you tell your connector to send everything to FB which it then does.

**Comment by heyme-itsyou** [comment]
thanks for your reply silke!

actually the fb connector works only one way from FB to friendica at the moment....so it just sends everything i post on fb to friendica....also the private stuff...

**Comment by annando** [comment]
It is a known bug and we really should solve this.

**Comment by annando** [comment]
Since this is an addon issue, we shouldn't assign this to a milestone, shouldn't we?

**Comment by silke** [comment]
Hey @annando , does that reference ^^ mean you solved it?

**Comment by annando** [comment]
It doesn't solve your personal bug since you *really* are doing a double post. Your posts with twidere are always send to Friendica *and* Twitter. But that's a configuration issue in twidere. You have to select a single target to make it work.
