### ISSUE TITLE
Gallery image upload - File format webp cannot be uploaded

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14170]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Friendica supports Webp, among others. When trying to upload a webp file via the gallery, an error message is returned: "The file extension is not allowed, it must be one of the following jpeg, gif, png, jpg."

### Steps to Reproduce

1. navigation to the gallery 
2. call up "Upload new photos"
3. call up "Call up files for upload"
4. select file
5. start upload 

Actual Result:

error message: "The file extension is not allowed, it must be one of the following jpeg, gif, png, jpg."

Expected Result:

The image can be uploaded

### Screenshots
![2024-05-19_17-43](https://github.com/friendica/friendica/assets/44441246/082797c6-aeea-43d6-bd98-2013ffeb93e6)
![Screenshot 2024-05-19 at 17-55-19 (2) ˈloma Matthias ✔ @ ˈloma](https://github.com/friendica/friendica/assets/44441246/d12541ab-93f0-4c00-937f-d6231ef4eaba)

### Platform Info

Friendica Version: 2024.06-dev 1560/1560 und die Post-Update-Version 1550/1550.

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by annando** [comment]
Fixed by https://git.friendi.ca/friendica/friendica-addons/pulls/1506
