### ISSUE TITLE
Links and link previews are not distributed

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14197]
- [x] I have searched open and closed issues for duplicates

### Bug Description
News accounts do not distribute links and link previews to mirror posts if the 2024.06-dev 1564/1564 post update version 1550/1550 is used.

Actual Result:
No link and link preview is distributed

Expected Result:
Link and link preview will be distributed again

### Screenshots
![2024-06-02_09-18](https://github.com/friendica/friendica/assets/44441246/0f64e667-dbeb-4619-9e5a-a5bcb38f0907)

![2024-06-02_09-25](https://github.com/friendica/friendica/assets/44441246/c5764bcf-5233-4db8-957a-b522dfa23da6)

### Platform Info

Friendica Version: Stable / 2024.06-dev 1564/1564 Post-Update-Version 1550/1550.

Friendica Source: git

PHP version: 8.1/8.2

SQL version: 10.5

**Comment by annando** [comment]
Yeah, just saw this. It works for some feeds and doesn't work for others.
