### ISSUE TITLE
Allow .jpg image uploads

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#14196]
### Is the feature request related to a problem? Please describe.

I  often want to upload `.jpg` pictures, for example from my smartphone and then I get an error message that only `.jpeg` is allowed. Then I have to rename the file, before I can upload it. I don't understand why only `.jpeg`. 

Maybe for non technical users, that's a barrier, too.

### Describe the feature you'd like

If possible, it would be nice to be able to upload `.jpg` files, too.

**Comment by foss-** [comment]
Works fine on pirati.ca
Please provide version info of the instance on which you are running into this problem (best to do this with every report). Had you reached out to your admin and asked about allowed files for upload?

**Comment by haheute** [comment]
Diese Friendica-Instanz verwendet die Version 2024.06-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1564/1564 und die Post-Update-Version 1550/1550.

PHP: 8.3.7
MySql: mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using readline 5.1

I am my own admin. (the only user on my instance). Is there a setting where I can allow `.jpg` ? I did not find it.

**Comment by MrPetovan** [comment]
Can you please share a screenshot of the error message?

**Comment by haheute** [comment]
yes, of course..

![Bildschirmfoto_2024-06-03_18-02-52--jpg-screenshot](https://github.com/friendica/friendica/assets/5753419/e2758430-1fe9-4fc2-ad2d-3d98caf00357)

I found this function, but why it then works on other instances.. I don't know
https://github.com/friendica/friendica/blob/9eafb5edcba8dd17d6a97ac6acb8218eb6dacfe5/src/Util/Images.php#L46

**Comment by MrPetovan** [comment]
It seems to rely on the underlying image manipulation library, we don't maintain this list ourselves.

**Comment by haheute** [comment]
I found the php imagick addons were missing. Now I have installed these:
```
php-pecl-imagick-1-r0
php83-pecl-imagick-3.7.0-r0
```
and restarted apache, then rebooted the server , cleared the firefox cache..
Now I can upload `.jpg` files from the post modal, and from my images page (but there only when the `JS Uploader`  addon is deactivated). I have also tried reloading all addons , removing and adding `JS UPloader` again, but with this addon actived, it doesn't work. 

I'm a bit clueless what to do now.

**Comment by haheute** [comment]
It seems in the `js_upload` addon was a change, 2 weeks ago. That would approximately match the start time of my problem: https://git.friendi.ca/friendica/friendica-addons/commit/9ae8925069fe87ff35b138668ee91946304593bf

**Comment by MrPetovan** [comment]
Nice find, it would indeed limit the allowed extensions for JPG images to one of the two usual.

**Comment by annando** [comment]
@haheute yeah, I'm convinced that we have to apply some change there.

**Comment by foss-** [comment]
Probably resolved with https://git.friendi.ca/friendica/friendica-addons/pulls/1515

**Comment by haheute** [comment]
yes.. thanks for the reminder. seems to work again :+1:
