### ISSUE TITLE
Should be able to find Pump.io users using their user@host handle

### ISSUE THREAD

**Issue by stevenroose** [friendica/friendica#1420]
When tried, this error message is shown:
> The profile address specified does not provide adequate information.
> No compatible communication protocols or feeds were discovered.
> An author or name was not found.
> Unable to match @-style Identity Address with a known protocol or email contact.
> Use mailto: in front of address to force email check.

Pump.io uses WebFinger to point to communication protocols. 

So when user@host.com is entered, Friendica should inspect https://host.com/.well-known/webfinger and look for the links defined in the Pump.io specification. If I'm correct, they are also part of the Activity Streams (v1) specification.

**Comment by annando** [comment]
We don't support pump.io directly - but only via connector. Trying to support the whole contact management would have been much work and had cost much time. It would be better to add native support for pump.io.

**Comment by annando** [comment]
@stevenroose Which behaviour would you expect? We can't add contacts via the pump.io connector.

**Comment by stevenroose** [comment]
If Pump.io is not supported directly, I don't expect any behaviour. I'd expect Friendica to find Pump.io users based on their handle. Just so with Diaspora handles. But I only tested Friendica, I stopped using it already..

**Comment by annando** [comment]
Okay. I will close this issue. We will have some changes in the contact management. Maybe we can support third party networks there.
