### ISSUE TITLE
Automatically detected temp folder should include the hostname

### ISSUE THREAD

**Issue by annando** [friendica/friendica#1421]
On shared servers like Uberspace several users seem to share the same temp folder (which is unsecure). This could maybe lead to strange problems.

So the automatically detected temp folder should alwyas contain the hostname.

**Comment by tobiasd** [comment]
You mean boot.php get_temppath() should be expanded by config->hostname leading to a path like /tmp/example.com for temporary files?

**Comment by annando** [comment]
Yeah. If you are hosting several friendica system on one plattform and you are sharing the temp folder (which I don't recommend for security reasons) then it could get funny when several systems would share the same folder.
