### ISSUE TITLE
[mastodon-api] Channel-only contact posts still appear in regular network timeline?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#14212]
On 2024-06rc, checked the feature to have "channel only" contacts whose posts should not appear in other timelines. Learnt:

- Works in Friendica web ui. Posts by those contacts don't appear in network timeline anymore, as expected. Great.
- Doesn't seem to work in Mastodon API client however (checked with tusky and phanpy) - posts still show up there.

Intended behaviour or bug? Having the API timelines honour this setting definitely would be expected I'd say...?

**Comment by annando** [comment]
It's slightly complicated. For the network feed the setting will control the visibility of posts done by the specific contacts. But in the API we display not only starting posts but also comments. So to completely emulate the behaviour, we have to look at the contacts that started the post and not the contacts that commented.
