### ISSUE TITLE
Allow activitypub to comment on groups.

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#14217]
I am unsure how this will work.  Perhaps the group will need to be tagged and then Friendica will look for an ! at the beginning of the post as I don't believe activitypub recognizes !address so perhaps a work around could convert the @address into !address and send the message on to the group.  It would raise awareness of groups if that became a feature the rest of the fediverse could use.

**Comment by annando** [comment]
I don't understand what you mean here. Can you go more into detail? What is the use case?

**Comment by anubis2814** [comment]
Ok, normally you when you post to a group on friendica you use the !address option.  If you follow a group from say mastodon, that feature doesn't work so you are just following the group, not part of it. You can use the @address feature but I don't think other people will see it shared in the groups feed, it will just be seen by the group, not as if it were posted by the group.  I could be wrong.

**Comment by anubis2814** [comment]
Actually I may be wrong. I thought that was the difference but does !address just make it exclusive and only people can see it in the group and not outside?  
The wording is a bit confusing so maybe I've been assuming things wrong about it.

Additionally, it is possible to address a group with the exclamation mark. In the example above this means that you can address the bicycle group via !bicycle. The difference with the @-mention is that the post will only be sent to the addressed group. This also means that you shouldn't address multiple groups in a single post in that way since it will only be distributed by one the groups.

**Comment by anubis2814** [comment]
It appears I don't really understand why people use the ! and what its purpose is after 6 years of being here.  
Perhaps what I want instead is an option for people from activitypub to be able to join so that they can engage in conversation there.  I believe I tried mentioning a group from mastodon and my post never showed up in the group because I was following not joining.

**Comment by MrPetovan** [comment]
Like I told you in your Friendica Support post, there's no meaningful difference between following and joining a group, it's one and the same. Starting to follow a group makes you "join" it as well.

And posts addressed to a group with a !-mention can be visible even if you don't follow/join the group if the post is public and the group isn't configured as a private group.

**Comment by anubis2814** [comment]
Yes why I closed this item once I found out
