### ISSUE TITLE
Firefish doesn't find Friendica groups

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#14218]
This might be an unfixable problem.  Mastodon (toot.cat) was able to find a group.  Firefish (ibe.social) was unable to find the group only the groups parent member.  I don't know if this is something wrong with the way firefish uses the api or not.

**Comment by annando** [comment]
Since several other systems can subscribe to our groups, I suggest that you create an issue at the Firefsh repository, so that they take a look. Possibly they can't handle group actors.

**Comment by anubis2814** [comment]
That makes sense. Thanks.
