### ISSUE TITLE
Weather addon “curweather” is not working

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#14228]
I hope I've come to the right place.

I think the weather addon “curweather” is not working.
You can enter your data but when you want to save it, nothing is displayed and the input fields are empty again.

**Comment by haheute** [comment]
I have registered on openweathermap.org to get an API key and changed something in the curweather addon: https://git.friendi.ca/friendica/friendica-addons/pulls/1521

Seems to work now, here. I see the widget on the network page.

**Comment by ghost** [comment]
It workf fine now. Many thanks.
