### ISSUE TITLE
Error thrown on login and all page clicks

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#14246]
When I logged in it looks like I got some kind of 2fa error. The UI menus show, this error page comes up on every click:

Exception thrown in /var/www/friendica/src/Core/Renderer.php:90
Stack trace:
#0 /var/www/friendica/src/Module/Security/TwoFactor/Verify.php(93): Friendica\Core\Renderer::replaceMacros()
#1 /var/www/friendica/src/BaseModule.php(250): Friendica\Module\Security\TwoFactor\Verify->content()
#2 /var/www/friendica/src/App.php(711): Friendica\BaseModule->run()
#3 /var/www/friendica/index.php(46): Friendica\App->runFrontend()
#4 {main}

**Comment by jakedfw** [comment]
Anyone know how to fix?

**Comment by annando** [comment]
Additionally to the callstack that you provided, there should be an error message. Without this information, there aren't enough clues.

**Comment by jakedfw** [comment]
Sorry about that! 
<img width="666" alt="image" src="https://github.com/friendica/friendica/assets/38843638/c7f76829-b82f-426b-a3fa-a3dd73534885">

Here you go.

**Comment by annando** [comment]
This is a local permission issue on your system. The web user doesn't have got write access to that given folder.

**Comment by jakedfw** [comment]
Thanks, Annando, that was it. Is there any code from an update or something that would have root folders created? I do the updates as www-data and that shouldn't allow for root folders to be created. 

Note: this absolutely could be user error. But I don't remember erroring!

**Comment by jakedfw** [comment]
Closing!

**Comment by annando** [comment]
This normally only happens when you work with different users for worker/daemon and web frontend.
