### ISSUE TITLE
Shared posts that come from threads are not displayed

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14260]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If an entry comes from threads that contains a shared post link to a thread content, it will not be rendered.

### Steps to Reproduce

1. check incoming posts from threads
2. check if it contains a shared post "RE: [threads.net/@nytimes/post/C8pp...](https://www.threads.net/@nytimes/post/C8pp164S3YC)"
3. check if the shared post is displayed

Actual Result:

The shared post from a thread content is not displayed

Expected Result:

The shared post from a thread content is displayed

### Screenshots

https://www.threads.net/@stonekettle/post/C8qSBFrtJlr
![Screenshot 2024-06-26 at 06-49-18 ˈloma Network](https://github.com/friendica/friendica/assets/44441246/38b38028-5609-4398-8da5-5ea80953ddaa)

### Platform Info

Friendica Version: RC  1568/1568 Post-Update-Version 1550/1550.

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
@loma-one why have you closed it? BTW: I have got the feeling as if this could be caused by shared accounts that haven't enabled the ActivityPub integration.
