### ISSUE TITLE
Error 1452 updating the database after latest gitpull on -rc

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#14274]
ALTER IGNORE TABLE `post` ADD INDEX `replies-id` (`replies-id`), ADD FOREIGN KEY (`replies-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE; 

Fehler 1452 beim Update der Datenbank aufgetreten
Cannot add or update a child row: a foreign key constraint fails (`friendicadb`.`#sql-alter-429-6ecf9`, CONSTRAINT `#sql-alter-429-6ecf9_ibfk_9` FOREIGN KEY (`replies-id`) REFERENCES `item-uri` (`id`) ON DELETE CASCADE)
ALTER IGNORE TABLE `post-user` ADD INDEX `replies-id` (`replies-id`), ADD FOREIGN KEY (`replies-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;

**Comment by annando** [comment]
Change to the maintenance mode, disable the cron/daemon. Kill all stray worker processes and execute the database update command again via the command line.

**Comment by ghost** [comment]
> Change to the maintenance mode, disable the cron/daemon. Kill all stray worker processes and execute the database update command again via the command line.

Could you give me detailed information how I switch to maintenance mode, disable the cron, and stop the workers?

**Comment by annando** [comment]
See the output of `bin/console`.

**Comment by ghost** [comment]
> disable the cron/daemon. Kill all stray worker processes

yes  i set the node in maintenance, how about disabeling the cron and kill the worker?

**Comment by annando** [comment]
I don't know your setup, so I can't tell you, where you activated the background jobs. Concerning killing the running workers: `ps` and `kill` is your friend here.
