### ISSUE TITLE
Badly-formed webfinger requests should return 400

### ISSUE THREAD

**Issue by mexon** [friendica/friendica#14281]
- [X] I have searched open and closed issues for duplicates

### Bug Description

It is a technicality but: according to the webfinger spec section 4.2, "If the resource parameter is absent or malformed, the WebFinger resource MUST indicate that the request is bad as per Section 10.4.1 of RFC 616."  Following that up, section 10.4.1 is a response code of 400.  In fact, Friendica returns 404.

### Steps to Reproduce

1.  request malformed URL including two equals signs:

```
curl -v "Mozilla" "https://friends.holograms.test/.well-known/webfinger?resource==acct:jem@friends.holograms.test"
```

Actual Result:

Return code is 404

Expected Result:

Return code is 400

### Platform Info

Friendica Version: 2024.06-dev

Friendica Source: git

PHP version: 8.2

SQL version: 10.11.8

**Comment by mexon** [comment]
This is a bug report from [FediTest](https://feditest.org/), specifically test 4.2.  There should probably be a tag for these - there will be more.

**Comment by annando** [comment]
@mexon can we close this issue or have you detected more things?

**Comment by mexon** [comment]
Please close.  I was actually wrong in my previous comment - with this change Friendica passes all the FediTest tests 🎉
