### ISSUE TITLE
Event looks not good on Diaspora (HTML tags are displayed)

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#14294]
- [X] I have searched open and closed issues for duplicates

### Bug Description

If an event is using  BBCodes, it seems, those are not displayed correctly on Diaspora. The `<p>` and `<i>` and similar elements are displayed raw as they are.. See screenshot.

### Steps to Reproduce

Write a new Event on Friendica and let it be posted (with permission: public) by checking the "Veranstaltung teilen" (share event) checkbox. Then check how it looks on a Diaspora.

I have not written any HTML tags into the event's description . Only new lines by pressing enter and BBcodes (like `[h3]` and `[i]` and so on, and BBCode links).  

My Friendica Node has the Markdown Addon activated, if that's important. 

#### Diaspora:
![event-on-diaspora-looking-not-good](https://github.com/user-attachments/assets/acad7482-19ca-46fa-b9dc-b99385c036a4)

#### Friendica:
![event-on-diaspora-looking-not-good--friendica](https://github.com/user-attachments/assets/4cb227af-b9a8-444f-aef9-9a090dd3aa69)

### Platform Info

Friendica Version: 2024.06-rc
DB-Version: 1569/1569 
Post-Update-Version: 1550/1550

Friendica Source: https://github.com/friendica/friendica

PHP version: 8.3.9

SQL version: mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by haheute** [comment]
Can somebody help me? Where must I look for the cause of this problem?
Did not yet find out how this happens..

**Comment by annando** [comment]
It seems like they don't like everything that our MarkDown parser produces.

**Comment by haheute** [comment]
I thought, if it works for posts, why not for events. Should be the same thing?
So I tried to find out where the "event" post and the "post" post get produced, and what exactly is sent to diaspora..

**Comment by annando** [comment]
I guess that we use some template for that. But I also have to check.
