### ISSUE TITLE
Saving hashtag blocked by Apache message "Unsafe URL with %3f URL"

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14295]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Saving or deleting hashtags is blocked. Message:

`
[Sat Jul 13 08:53:06.249580 2024] [rewrite:error] [pid 64683:tid 64692] [remote 2003:e5:1730:f600:2884:3b50:b8e2:d79a:36410] AH10508: Unsafe URL with %3f URL rewritten without UnsafeAllow3F, referer: https://loma.ml/search?tag=tag
` 
https://loma.ml/search/saved/add?term=%23dog&return_url=search%3Ftag%3Ddog

This is irritating, as adding and deleting hashtags had worked without any problems until the RC was updated. No changes were made to the system

### Steps to Reproduce

1. search for any hashtag
2. try to save the hashtag
3. check the log files of your Apache2

### Platform Info

Friendica Version: RC 1569/1569 Post-Update-Version 1550/1550

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by loma-one** [comment]
The update to the current version of Apache2 led to the unexpected result. It looks like the encoding of a "?" is no longer allowed. But this is exactly what php does when it tries to save a tag.

This call is probably used in different places, which can lead to problems.

Solution: If the current Apache version is used, an UnsafeAllow3F must be added to the RewriteRule in the .htaccess: 

RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA,B,**UnsafeAllow3F**]

Please correct this urgently if there is a better solution.

**Comment by Copiis** [comment]
I can confirm this behavior.
It also occurs when you try to log in via an app or when you try to add feeds with question marks in the URL
Geting this from the Server `"AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F"`
