### ISSUE TITLE
OpenID URL encryption downgrade: automatic "https://" stripping

### ISSUE THREAD

**Issue by v6ak** [friendica/friendica#1429]
Steps to reproduce:
1. Go to profile settings
2. Configure a HTTPS URL for OpenID, e.g. `https://launchpad.net/~v6ak`

Expected results:

a. SQL command `SELECT openid FROM user WHERE nickname=…` returns `https://launchpad.net/~v6ak`
b. My profile page links to `https://launchpad.net/~v6ak` OpenID

Actual results:

a. SQL command `SELECT openid FROM user WHERE nickname=…` returns `launchpad.net/~v6ak`, that is "https://" is missing!
b. My profile page links to `http://launchpad.net/~v6ak` OpenID, that is "http" instead of "https"!

**Comment by silke** [comment]
tobiasd and I started to look into this tonight. Indeed logging in with openID is not working at the moment.

**Comment by Quix0r** [comment]
Still an issue with latest develop.

**Comment by strk** [comment]
This is fixed by #2530 -- please report your tests there

**Comment by Quix0r** [comment]
Okay, I can check it at home with local HTTPS addresses, too.

**Comment by strk** [comment]
@Quix0r did you check ? Can this be closed ?

**Comment by annando** [comment]
BTW: How good is our OpenID implementation at all? I really would like to have something reliable and compatible in both directions.

**Comment by strk** [comment]
@annando on the specs, `https://` must be retained because lack of protocol has to be interpreted as `http://`. The issue reporter was using launchpad.net, so it's not *his* implementation...

**Comment by Quix0r** [comment]
Sorry, work keeps me very busy. ;-( I can only find some time at weekend.

**Comment by Quix0r** [comment]
Login on my public instance at https://f.haeder.net with my OpenID https://social.mxchange.org/roland seem to work, I am logged in (logged out before with regular login data).

**Comment by MrPetovan** [comment]
Closing since nobody seem to have any problem anymore.
