### ISSUE TITLE
Find a better way to select sharing options in mobile web interface

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1430]
I think that the clean theme is the only one that is somehow usable on a phone without some client app. I used it more recently and, in our future dream theme, there should be a nicer way to select whom you want to share your post with. Right now, there is this huge window/overlay thingy opening that has twice the size of a smartphone display. Would be cool to find a different solution at some point.

**Comment by tobiasd** [comment]
Yes, even if it was styled to fit the width (I seem to have forgotten x-) ) with 200 contacts or so, it gets clumy to pick on small screens.

**Comment by fabrixxm** [comment]
We should design the UI as a mobile app, with ideas and UI interaction as in android or in iOS , an then adapt it to the bigger screens.


Il 13 marzo 2015 17:10:02 CET, Tobias Diekershoff <notifications@github.com> ha scritto:
>Yes, even if it was styled to fit the width (I seem to have forgotten
>x-) ) with 200 contacts or so, it gets clumy to pick on small screens.
>
>On Fri, 13 Mar 2015 06:09:30 -0700
>Silke Meyer <notifications@github.com> wrote:
>
>> I think that the clean theme is the only one that is somehow usable
>> on a phone without some client app. I used it more recently and, in
>> our future dream theme, there should be a nicer way to select whom
>> you want to share your post with. Right now, there is this huge
>> window/overlay thingy opening that has twice the size of a smartphone
>> display. Would be cool to find a different solution at some point.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/friendica/friendica/issues/1430#issuecomment-79086396

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by FlxAlbroscheit** [comment]
@silke Could you please upload a screenshot of the current sharing-module on mobile browsers? Just to give me an idea of its status quo :) And as I'm developing a theme which is responsive out-of-the-box, I would like to figure out a better way to implement such an improved sharing-option. Felix

**Comment by tobiasd** [comment]
What is the status with this? Is the current situation better with Vier and Frio?

**Comment by rabuzarus** [comment]
I think it is almost the same situation. If you have many contacts or many contact groups the content of the acl window is very confusing

**Comment by tobiasd** [comment]
At least on my Jolla1 with the vier theme this works now.

**Comment by tobiasd** [comment]
If nobody reports otherwise from other mobile platforms, I think we can close this issue prior to the release then.

**Comment by tobiasd** [comment]
How would a autocomplete enhance the UX? This sounds like typing the account handles right? I really prefer just to click on buttons for the selection of groups and persons.

**Comment by MrPetovan** [comment]
Instead of having a massive list of all your contacts in the ACL, we would have at most four input fields (user allowed, user denied, group allowed, group denied) that matches how we manage permissions with a direct visual impression as contacts would be added manually in either lists, reinforcing the feeling of control.
