### ISSUE TITLE
Unsafe URL with %3f URL rewritten without UnsafeAllow3F

### ISSUE THREAD

**Issue by Copiis** [friendica/friendica#14303]
If you try to add a feed that contains question marks in the URL or you try to create a Friendica account in an Android app, a blank page appears with the message "You do not have permission to access this resource."

### Steps to Reproduce

Go to the Contacts page.
Try to add an RSS feed with question marks in the URL
Click Add
Open Tusky.
Under Add, enter the affected instance.
Click Add.
Actual Result:
Forbidden
You don't have permission to access this resource.

Expected Result:

It is expected that you can add the feed and in the second case that you can add your account in the app.

### Platform Info

Friendica 'Yellow Archangel' 2024.06-rc - 1569
PHP version | 8.1.2-1ubuntu2.18
php.ini | /etc/php/8.1/fpm/php.ini
upload_max_filesize | 128M
post_max_size | 144M
memory_limit | 512M
MySQL / MariaDB
max_allowed_packet | 16777216

</div></div>

**Comment by sekretaerbaer** [comment]
I also noticed the same thing with my instances when I tried to log in to the instances with an app (Mona and Whalebird). 

The error message in the Apache logs is 

> Thu Jul 18 05:47:55.785754 2024] [rewrite:error] [pid 607863:tid 140668072609344] [client XX.XX.XXX.XXX:XXXX] AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F

I think this is related to https://github.com/friendica/friendica/pull/14298.

the link with which Mona tries to log in looks like this

`https://sekretaerbaer.de/login?return_path=oauth%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3D1218fc2c129e5214ad72477064b104295e4dd7c726f750476a7112b265f3cbf6%26redirect_uri%3Dcom.jonny.mona%253A%252F%252Foauth%26scope%3Dread%2Bwrite%2Bpush%2Bfollow%26lang%3Dde`

**Comment by Copiis** [comment]
I think this will be the case for all current RC instances. It just won't be noticed because you don't log in or add contacts very often.

**Comment by AlfredSK** [comment]
Is this hard to "fix"? Can we avoid the encoded question marks (%3F) in URLs? 

I regularly get support requests because users can't login to their apps (e.g Tusky) anymore.

**Comment by sekretaerbaer** [comment]
add `UnsafeAllow3F `to the RewriteRule in .htaccess

`RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorisation},L,QSA,B,UnsafeAllow3F]`

I cannot judge whether this is a secure solution

**Comment by AlfredSK** [comment]
> I cannot judge whether this is a secure solution

No. It isn't.

**Comment by AlfredSK** [comment]
Here is another one: 

Apache access log: `[08/Aug/2024:04:31:58 +0000] "GET /api/v1/timelines/public?limit=40&max_id=115385796%3Flimit%3D40 HTTP/1.1" 403`
Apache error log: `[Thu Aug 08 04:31:58.019364 2024] [rewrite:error] [pid 2205086:tid 2205132] [client 58.97.240.95:45289] AH10508: Unsafe URL with %3f URL rewritten without UnsafeAllow3F`

**Comment by annando** [comment]
That one is weird.

**Comment by AlfredSK** [comment]
Yep. The `limit=40` exists twice in the URL. The user-agent is `"python-httpx/0.25.2"`. Maybe the client is adding the additional `%3Flimit%3D40`.

**Comment by annando** [comment]
From my point of view it is a client problem. Normally one could then have got a look at the user agent string and then tell the responsible person to fix it. But some `python-httpx/0.25.2` isn't really helpful ...

**Comment by Copiis** [comment]
I'm getting a lot of this error in the logs at the moment and I can't narrow it down. There's nothing in the Friendica logs.
```
2024-08-21 14:15:10	66.249.68.69				AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F
2024-08-21 14:15:10	66.249.68.69	
403	GET /toggle_mobile?off=1&address=https%3A%2F%2Fchatfreu.de%2Fcommunity%2Fglobal%3Faccounttype%3Dperson%26max_id%3D2024-07-18%252020%3A10%3A45 HTTP/1.1
```
