### ISSUE TITLE
Import Account

### ISSUE THREAD

**Issue by FelipeFcosta** [friendica/friendica#14312]
How to import an account? I already exported an account from another instance as a test, I go to the url newserver.com/user/import, upload the .account file, but when I click the import button, I always get Page Not Found! Every friendica instance!. Am I missing something? I'm really new to all this
![image](https://github.com/user-attachments/assets/d3301058-7c17-410e-a9ee-46f2a982bc51)

**Comment by MrPetovan** [comment]
Thank you for the report, it looks like it is redirecting to `/uimport` which is a route that doesn't exist anymore.

**Comment by TheNomad11** [comment]
Is there a way to fix it? I just wanted to move

**Comment by AlfredSK** [comment]
Not sure. But maybe `example.com/user/import` is the correct path now.

**Comment by TheNomad11** [comment]
yeah but it redirecting to the wrong path, so the import feature is broken
