### ISSUE TITLE
Log Warning: Empty host GUID part

### ISSUE THREAD

**Issue by gravity-deleted** [friendica/friendica#14311]
Hi everyone,

I have had a Worker Warung in my log for some time now which spams extremely;

Every ten minutes an "app.bsky.feed.post" onePoll is queried:

**WARNING 	worker 	Empty host GUID part**
uri: at://did:plc:ciwdjtycukekyw24yp6xqmxf/app.bsky.feed.post/3ks26eaohqn2b
worker_id 	32b3bbd
worker_cmd 	OnePoll
file 	Item.php
line 	2306
function 	guidFromUri
request-id 	669bbf5f6326b
stack 	Item::guidFromUri (381), Feed::import (188), OnePoll::pollFeed (95), OnePoll::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (87)
uid 	681526
process_id 	1051115

`bin/console cache clear` does not work to solve the issue.

How can I stop this onePoll?

**Comment by annando** [comment]
It looks like someone added a Bluesky post as a feed contact. I'm unsure how this could happen. But best would be to delete that contact.
