### ISSUE TITLE
Adding Facebook RSS feeds does not work.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1432]
When adding a feed like this: https://www.facebook.com/feeds/page.php?format=atom10&id=40796308305
In my case it attempts to add it as a Twitter contact, because no facebook plugins are installed on my server. This is because `facebook.com` is detected and seen as a connector network. Skipping RSS features.

Temporarily commenting these lines in `include/Scrape.php` worked to add the feed as expected:

```php
    if (strpos($url, 'www.facebook.com')) {
        $connectornetworks = true;
        $network = NETWORK_FACEBOOK;
    }
```

**Comment by annando** [comment]
I guess we can call that a bug, since it prohibits adding facebook pages as feed.

**Comment by annando** [comment]
Pull request is done.
