### ISSUE TITLE
No local timeline with different apps

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14368]
- [x] I have searched open and closed issues for duplicates

### Bug Description

With the adoption of the issue https://github.com/friendica/friendica/pull/14366 the local timeline in various apps is no longer loaded, Tusky crashes when the notification is called up

### Steps to Reproduce

1.  Start mobile APP
2.  go To local Timeline
3.  the Timeline is emty

Actual Result:

Expected Result:

### Screenshots

Relatica

![Screenshot_20240817-174357](https://github.com/user-attachments/assets/60bfdafc-f2e6-4bce-8792-ce3c25c90f0a)

Tusky

![grafik](https://github.com/user-attachments/assets/52b76d13-c46b-4bef-9e10-c911a1d34b48)

Moshidon

![Screenshot_20240817-183808](https://github.com/user-attachments/assets/62119847-9efb-4960-9d5c-0846ebb64c17)

### Platform Info

Friendica Version: rc/Stable  1571/1571  Post-Update-Version 1550/1550 / 

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
I guess this issue is caused by https://github.com/friendica/friendica/pull/14356 How is your configuration concerning the community pages?

**Comment by loma-one** [comment]
I have undone the change manually. The local timeline is still not loaded via external apps.

Tusky can now load notifications, but crashes when returning to the timeline.

I can't find any error logs

**Comment by ne20002** [comment]
I can't reproduce the issue, thus I assume it is something with based on settings.
I had/have a similar issue with federated timeline not shown in Tusky based on the setting of 'Gemeinschaftsseite'. This option works for me (showing the federated timeline in Tusky):

![grafik](https://github.com/user-attachments/assets/5543efd8-75eb-4e4c-860a-bed2f6b37628)

**Comment by sekretaerbaer** [comment]
I tested this with Relatica (IOS + MacOS) and the local timeline is displayed.

MacOS

![Bildschirmfoto 2024-08-18 um 09 35 03](https://github.com/user-attachments/assets/5fb65625-4a1d-45d6-92c4-fc4f15570787)

IOS

![IMG_5858](https://github.com/user-attachments/assets/96c71979-6a7a-4fb1-a975-30b349d721c4)

**Comment by loma-one** [comment]
@sekretaerbaer @ne20002 
Please enter your PHP and mySQL versions. I suspect that this may have something to do with it.

**Comment by sekretaerbaer** [comment]
PHP: 8.1.2
mySQL: 15.1 Distrib 10.6.18-MariaDB

**Comment by loma-one** [comment]
@ne20002 Correct. The focus is on ‘Public posts from the federated network’ and has been for years. 
The simple reason for this is that I don't want to reveal too much to visitors. The change that now prevents this setting is therefore a problem and creates unnecessary legal uncertainty.
@annando 

![grafik](https://github.com/user-attachments/assets/b843c8c3-f08d-4bfc-aa60-94d6ae16f535)
