### ISSUE TITLE
Posts from Friendica groups are not displayed. 

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#14364]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Posts that are posted in Friendica groups such as helpers@forum.friendi.ca do not appear in the group view. 
I have noticed that no new posts have been displayed in the helpers@forum.friendi.ca group on either of my two instances for days. I have also been able to observe this behaviour on another instance that I do not operate.
I then created a post in helpers@forum.friendi.ca: the result was that it appeared on my two instances and on a third instance, but not on two of my Mastodon accounts.

View of the group from sekretaerbaer.de

![Bildschirmfoto 2024-08-16 um 17 44 29](https://github.com/user-attachments/assets/6c1c4d1c-9043-430d-a6fd-46930efff3c5)

View of the group from friendica.opensocial.space

![Bildschirmfoto 2024-08-16 um 17 45 43](https://github.com/user-attachments/assets/17cb3fdd-7100-42f3-9449-43c98150f99c)

View of the group from forum.friendi.ca

![Bildschirmfoto 2024-08-16 um 17 44 24](https://github.com/user-attachments/assets/70ec338c-9bd0-4e64-9d2a-2cbc4ada9ecb)

https://sekretaerbaer.de/display/61b27817-1466-be06-d599-b22304170502

all instances with which I have tested are on version 2024.06-rc , database version 1571/1571 , update version 1550/1550

**Comment by tobiasd** [comment]
@annando who has to pull @sekretaerbaer or @AlfredSK so that we can test the delivery?

**Comment by annando** [comment]
It's a server thing.

**Comment by annando** [comment]
The PR #14367 now really fixes the issue.

**Comment by sekretaerbaer** [comment]
thank you, it works

**Comment by AlfredSK** [comment]
Confirmed. Works again. :-)
