### ISSUE TITLE
Support "postingRestrictedToMods" for Groups

### ISSUE THREAD

**Issue by pfefferle** [friendica/friendica#14377]
### Is the feature request related to a problem? Please describe.

I am the developer of the WordPress ActivityPub plugin and had some discussions with the Friendi.ca community that WordPresses use of Groups is different because it does not allow others to post to the Group. Supporting the `postingRestrictedToMods` flag would be an easy way to resolve the issue.

### Describe the feature you'd like

Lemmy has a feature flag for Groups to define that not everyone can post to a Group. This is also supported by PeerTube and WordPress.

To have the best possible compatibility with other Group implementations it would be nice to hide the "Post to a Group" button if `postingRestrictedToMods` is set to `true`.

### Additional context

https://join-lemmy.org/docs/contributors/05-federation.html#community

<img width="1336" alt="Screenshot 2024-08-18 at 14 59 30" src="https://github.com/user-attachments/assets/cd20ebfd-9001-45cf-ac86-c3b0a16b5142">

**Comment by annando** [comment]
Can you provide some URL where we can query this value? Best would be addresses from Wordpress, Peertube and Lemmy, thanks!

**Comment by pfefferle** [comment]
Sure!

WordPress:

```
curl "https://notiz.blog/@notiz.blog" \
     -H 'Accept: application/activity+json'
```

Lemmy:
```
curl "https://lemmy.ml/c/modonly" \
     -H 'Accept: application/activity+json'
```

and I think PeerTube only consumes the flag, but does not support setting it for own groups/channels: https://docs.joinpeertube.org/api/activitypub#actor
