### ISSUE TITLE
No "sign up" or "register" button on initial install.

### ISSUE THREAD

**Issue by mjharmon** [friendica/friendica#14381]
Hi.

I've followed the installation process on my own server as outlined at:
https://github.com/friendica/friendica/blob/develop/doc/Install.md

Everything seems to work as it should, except that when I attempt to register/sign up for the administration account, there is no means to do so.

I've tried the command line autoinstall (which reports success) and the web based install - which reports a correct environment but then gives a blank page after that check - with the same results.

when I attempt to access the https://myhostname/register URL, the web page reports "Permission denied"

How can one create the initial / first / administrative account without the web interface? Have I missed a configuration setting?

Thank you for any guidance anyone can provide.

A screen shot of how the initial page appears is below:

![inital-panel](https://github.com/user-attachments/assets/a74269f8-1415-4834-b2c4-6b9b06f901fd)

**Comment by tobiasd** [comment]
This might be related to #14017 @annando what do you think?

@mjharmon could you try and change the value of `admin_inactivity_limit` in the `static/defaults.config.php` to `0` to deactivate the check as described in the comment above.

**Comment by mjharmon** [comment]
After setting `admin_inactivity_limit` in  `static/defaults.config.php` to `0`, I was able to see the "Sign up  now" button and register as the administrator without a problem.
Thank you!

**Comment by tobiasd** [comment]
Thanks for checking @mjharmon
