### ISSUE TITLE
Clarifying the branching model, git flow.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1439]
Because of pull request #1433 I noticed several things about using [git flow](http://nvie.com/posts/a-successful-git-branching-model/).
I'll try to clear up what went wrong here, be sure to ask any further questions you might have @tobiasd @fabrixxm @tugelbend @annando 

# Fast forwarding

![--no-ff](http://nvie.com/img/merge-without-ff@2x.png)
Fast forwarding is **enabled by default** in git.

When you merge with fast-forwarding it does not add a new commit to mark when you've performed the merge and how. This means in your commit history you can't know exactly what happened in terms of merges. **It's best to turn off fast-forwarding.**

https://stackoverflow.com/questions/5519007/how-do-i-make-git-merges-default-be-no-ff-no-commit

# When to create release branches.

A release branch is created when the develop branch contains **all features it should have**.

So in the case of 3.4. When I look at the milestone https://github.com/friendica/friendica/milestones/3.4
there are still features missing. Meaning the `release-3.4` branch should not exist yet.

## Why use a release branch then?

A release branch is used for a few things.

1. Allow last-minute bug fixing before the release goes to `master`.
1. Allow meta-data changes (README, CHANGELOG, etc.) for version bumps and documentation changes.
1. Makes sure the `develop` branch can receive new features that are not part of this release.

That last point is important because...

# Never merge `develop` into a release.

The moment a release branch is created, develop is now intended for **the version after this release**. So if `release-3.4` is created, `develop` becomes either 3.5 or 4.0.

If you were to merge `develop` into `release-3.4` at this point. Features and bug-fixes intended for 3.5 or 4.0 might leak into this release branch. Possibly introducing new bugs too. Which defeats the purpose of the release branch.

**Comment by Beanow** [comment]
In the interest of this, I've removed branches that have been completed. IE: all release branches.

**Comment by silke** [comment]
I'll insert this cool explanation into the dev documentation.

**Comment by silke** [comment]
Added to the /help pages in pull request #1524, hope it's fine to close this issue.
