### ISSUE TITLE
Animated GIF avatars cause zombie process in worker that persists forever.

### ISSUE THREAD

**Issue by Sarahlizzy** [friendica/friendica#14419]
Contacts with animated GIF avatars crash the worker.

- [X] I have searched open and closed issues for duplicates

### Bug Description

Contacts with animated GIF avatars crash the worker when it tries to perform an "Update Contact" action, leaving "Fatal Error (E_ERROR): gd-webp cannot allocate temporary buffer" in the logs every 5 minutes. This carries on until the remote contact is blocked and the job manually purged from the worker queue.

### Steps to Reproduce

1.  Have a contact that uses an animated GIF avatar
2.  Wait for the worker to perform an Update Contact on it
3.  Observe that the job never finishes

Actual Result:

Worker job persists forever, and never completes. This is caused by an error thrown on line 231 of /var/www/html/src/Object/Image-php, which detects that the avatar is animated, and therefore unsupported 

Expected Result:

The worker should drop the job and fail gracefully, if unable to support animated avatars, not leave the zombie job there forever.

### Screenshots
![Screenshot 2024-09-05 at 16 40 05](https://github.com/user-attachments/assets/c57cf14f-7750-4bed-8454-a0b13c120b31)
![Screenshot 2024-09-05 at 17 17 41](https://github.com/user-attachments/assets/4b8e60d4-5a59-4c54-83ac-91b9c147dd23)

### Platform Info

Friendica Version: 2024.08

Friendica Source: Docker (latest)

PHP version: 8.1.29

SQL version:

**Comment by Sarahlizzy** [comment]
Another instance of this. Trying to update this user has once again bricked the worker task. https://thelemmy.club/u/bdonvr

**Comment by ne20002** [comment]
I have this not in my friendica log file but in the container log of the cron container. 
I may have time next week to look into this.

**Comment by annando** [comment]
@Sarahlizzy Can you have got a look at your friendica log file for these errors? It would be great to have a callstack here.

**Comment by Sarahlizzy** [comment]
every time this happens, I get one of these every five minutes, but the trace field is always empty. Is there somewhere I can look at the log directly? Currently on mobile so a bit fiddly. 

![IMG_5089](https://github.com/user-attachments/assets/ff5f5e6b-12ad-4c38-a06a-661479cf060f)

**Comment by annando** [comment]
It would be the best to have a look directly in the text file instead of this web view here.

**Comment by Sarahlizzy** [comment]
Ok. Here’s one direct from friendica.log

`2024-09-04T23:55:47Z worker [ALERT]: Fatal Error (E_ERROR): gd-webp cannot allocate temporary buffer {"code":1,"message":"gd-webp cannot allocate temporary buffer","file":"/var/www/html/src/Object/Image.php","line":231,"trace":null} - {"file":null,"line":null,"function":null,"request-id":"66d8f37fdbd73","stack":"ErrorHandler::handleFatalError","uid":"edacce","process_id":286270} `

**Comment by annando** [comment]
Can you fetch the last few lines that contain `66d8f37fdbd73`? Then we should see what the system had intended to do.

**Comment by annando** [comment]
I just had a look at the code at the given place: https://github.com/friendica/friendica/blob/develop/src/Object/Image.php#L216-L235

We already try to catch exceptions there.

Do you have got a link to the picture that is making these problems? Possibly I will find some workaround when can reproduce the problem as well.

**Comment by Sarahlizzy** [comment]
That's the only line in the log that contains it

`root@40fd2ae45a4b:/var/www/html# grep 66d8f37fdbd73 friendica.log 
2024-09-04T23:55:47Z worker [ALERT]: Fatal Error (E_ERROR): gd-webp cannot allocate temporary buffer {"code":1,"message":"gd-webp cannot allocate temporary buffer","file":"/var/www/html/src/Object/Image.php","line":231,"trace":null} - {"file":null,"line":null,"function":null,"request-id":"66d8f37fdbd73","stack":"ErrorHandler::handleFatalError","uid":"edacce","process_id":286270}
root@40fd2ae45a4b:/var/www/html# `

**Comment by Sarahlizzy** [comment]
I don't have that specific one handy because I purged it from the database, but this image causes the problem: https://hexbear.net/pictrs/image/5918519b-03d2-4ccc-80d4-a0a2943ec9c7.webp?format=webp

**Comment by annando** [comment]
Can you install Imagick on your machine? it isn't installed, isn't it?

**Comment by Sarahlizzy** [comment]
Imagemagic is installed in both containers. It isn't helping.

`sarah@friendica:~$ docker exec -it friendica-cron /bin/bash
root@40fd2ae45a4b:/var/www/html# apt install imagemagick
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.3+deb11u4).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
root@40fd2ae45a4b:/var/www/html# 
exit
sarah@friendica:~$ docker exec -it friendica /bin/bash
root@347d4a56513c:/var/www/html# apt install imagemagick
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.3+deb11u4).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
root@347d4a56513c:/var/www/html# 
`

**Comment by annando** [comment]
When you call "admin/phpinfo" on your system, do you see a section with "imagick"?

Nonetheless, when you apply the changes in the linked PR, at least these errors will most likely stop.

**Comment by Sarahlizzy** [comment]
Yes. The imagick section is there. I am still getting the errors.
<img width="943" alt="Screenshot 2024-09-18 at 10 03 56" src="https://github.com/user-attachments/assets/2101acc0-e79f-4423-aa81-839013fb9525">

**Comment by annando** [comment]
Have you applied the changes from the pull request?

**Comment by Sarahlizzy** [comment]
No. I honestly have no idea how I'd do that in the Docker image.

**Comment by Sarahlizzy** [comment]
Actually, let me apply the changes via a direct edit of src/Object/Image.php, rather than a pull, and I'll see what happens.

**Comment by Sarahlizzy** [comment]
ARGH! Every time I restart the container, it pulls the original version of Image.php down from 2024.08, overwriting the changes, because FRIENDICA_UPGRADE is set to true in both containers, and you can't modify the environment of an existing container.

I'd have to blow away the existing containers and rebuild them without FRIENDICA_UPGRADE set, which I can do, but it's a pain in the arse because I've modified them quite a bit since they were created.

Going to come back to this later.

**Comment by annando** [comment]
Can you switch to the develop branch?

**Comment by Sarahlizzy** [comment]
I can, but will probably look at this tomorrow now, after taking backups and stuff. 

Thanks for looking at this. Will get back to you when I'm on dev
