### ISSUE TITLE
Gallery not working with folders containing spaces

### ISSUE THREAD

**Issue by schmaker** [friendica/friendica#14415]
### Bug Description

Gallery picker for post "crashes" when opening gallery folder with spaces (maybe reproducible with other special characters).

### Steps to Reproduce

1.  Open post composer
2.  Try to add image from gallery folder with spaces
3.  Gallery crashes  

See attached screenshots when trying to open gallery folder with spaces:
![Screenshot 2024-09-04 at 17-05-51 Schmaker eu - end of dem Internets Network](https://github.com/user-attachments/assets/d03ce087-534f-4bdb-b061-6b6f163a43e0)
![Screenshot 2024-09-04 at 17-06-11 Schmaker eu - end of dem Internets Network](https://github.com/user-attachments/assets/79c1da6e-d305-409a-a907-d1e714dc6bb2)

Actual Result:
Gallery crashes and does not show anything (folders without spaces works as expected). According to Firefox the response is this:
`HTTP/1.1 403 Forbidden
Date: Wed, 04 Sep 2024 15:05:54 GMT
Server: Apache/2.4.62 (Unix) OpenSSL/3.3.1 PHP/8.3.10
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Content-Language: cs`

Expected Result:
Load images from gallery folder

### Platform Info

Friendica Version: 2024.08 (but was happening in earlier versions as well)

Friendica Source: Official git

PHP version: 8.3.10

SQL version: MariaDB 11.4.3

**Comment by haheute** [comment]
I tried to reproduce this, but it seems to work in Chromium and Firefox on Linux and also on my Android Smartphone with Chromium. (Screenshot is Chromium/Linux)

![Bildschirmfoto_2024-10-15_12-42-46--gallery-whitespace](https://github.com/user-attachments/assets/915284d8-0e0e-4653-863a-b75e459702bb)

Does your Browser Dev-Tools Console show some Information? Maybe a Javascript Error?
And it looks on your Screenshot as if you have a folder with an empty name (below "Auta") ? Could this one maybe cause problems?

**Comment by schmaker** [comment]
If it works on your system, then it's possibly not Friendicas issue, but configuration/local data issue instead.

Is this output helpful somehow? 
https://pastebin.com/9CS1t2qP
https://pastebin.com/AtR48vY6 

If it works on your side, I somehow wonder if there isn't something fishy going on on Apache side.

Anyways - that propably makes this bug invalid

**Comment by haheute** [comment]
I don't know. I hope my Apache is configured correctly.. don't know much about it.. 
Maybe one more person can try with an album name with whitespace ..  

Can you see the photos of the problematic album in your profile / photos page?

**Comment by MrPetovan** [comment]
I seem to remember Apache tightened its policy regarding special characters in the URL. We had a series of bug reports right when the update was published as different parts of Friendica started breaking down as a result of this policy.

Edit: Ah, nevermind, it was with forward slashes: https://github.com/friendica/friendica/issues/14295

**Comment by schmaker** [comment]
Thank you all for helping me out. Turns out that I had wrong rewrite rule from previous versions:

`RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]`
should actually be
`RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA,B]`
