### ISSUE TITLE
No feed retrieval for days

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#14432]
Since 9 September, no more feeds have been retrieved from anonsys.net.
Is the problem known and is a solution already being worked on?

**Comment by annando** [comment]
Will be fixed by PR #14431.

**Comment by ghost** [comment]
Strange - feeds are retrieved on squeet.me, but not on anonsys.net. Why is that?

**Comment by annando** [comment]
It will work on the other servers, once the pull request #14431 is checked and accepted and the other server is updated. I don't know when this will be the case.

**Comment by ghost** [comment]
Thank you for the information.

**Comment by ghost** [comment]
I have not yet understood why feeds can be retrieved via squeet.me but not via anonsys.net. Then, as I understand it, it is not a problem with Friendica, but with individual instances. 
Or do I not really understand the problem - which I would not rule out.

**Comment by annando** [comment]
I developed the fix on squeet.me. So it now works there. But it will only work on every other instance after the fix is an official part of the code. And this will happen after the pull request got accepted and the other instances have fetched the latest code.

**Comment by ghost** [comment]
**Remark:**
If I hadn't saved an OPML file of my feeds before using Friendica as a feed reader, I wouldn't have been able to read my feeds for six days now.
**Question:**
What option would I have in such a case if I don't want to wait for the problem to be solved and want to use a ‘normal’ feed reader again in the meantime?
_Transferring each feed individually would not be a solution for me._

**Comment by foss-** [comment]
>  Transferring each feed individually would not be a solution for me.

OPLM backup is your workaround. And if that wasn't done, manual transfer. If you are not happy about that there is nothing much friendica devs can do. annando did his best and provided a very quick fix on the day you filed this report. Try getting an issue you see in a Microsoft or Apple product fixed that fast.

Please be patient and kind - this is free software developed as a side project by a small team (mostly one person). There really is no point putting more pressure on them. If you look at the commit log of friendica you will find that the past months have been busy with many fixes being done.

**Comment by ghost** [comment]
@foss-
Thank you for your informative feedback. 
I am aware of the high level of commitment of the developers and do not want to put anyone under pressure. I always get into conflict with my impatience.

What is the commit log of friendica and where can I find it?

**Comment by foss-** [comment]
No worries, I am familiar with being impatient myself 🙈. But sometimes things just take time.

All commits are here, branch may change when a release comes closer: https://github.com/friendica/friendica/commits/develop/
