### ISSUE TITLE
[Bluesky] Unexpected GZIP response from getTimeline endpoint

### ISSUE THREAD

**Issue by Maeglin73** [friendica/friendica#14451]
Apparently, yesterday, Bluesky started applying GZIP encoding to getTimeline responses, even if clients didn't ask for it. This caused Friendica to silently stop getting new timeline posts from them. I made a quick patch to fix the problem in the Bluesky addon, but maybe a better place would be in Network/HTTPClient/Response/CurlResult to more universally handle this kind of thing?

[bluesky_gzip_response.patch](https://github.com/user-attachments/files/17139190/bluesky_gzip_response.patch)

**Comment by annando** [comment]
Thanks for the hint. I will have a look at where to apply the changes the best.
