### ISSUE TITLE
hitting enter after typing password on 2FA settings page deletes 2FA config

### ISSUE THREAD

**Issue by bmillwood** [friendica/friendica#14464]
- [x] I have searched open and closed issues for duplicates

### Bug Description

On the 2FA settings page, you need to enter your current password before making any changes.  If I hit Enter on this field, it submits the form. I don't know how it chooses which submit button to use, but empirically it seems to choose "Disable 2FA", so I find my 2FA settings are gone.

I ran into this bug because 1Password offered to fill my password on the page, and "helpfully" autosubmitted the form after filling it, which has the same effect.

### Steps to Reproduce

1. Enable and verify 2FA in Friendica settings.
2. Go to /settings/2fa
3. Type your password in the box and press enter

#### Actual Result:

2-Factor authentication is disabled, and has to be freshly set up again.

#### Expected Result:

Either:
* Disable 2FA is still pressed, but Friendica asks for some kind of confirmation, which I can then decline, or,
* Since the meaning of pressing Enter on the password field is ambiguous, the form is not submitted at all.

### Platform Info

Friendica Version: 2024.08

Friendica Source: I don't know, I'm not an admin of the instance I tried this on (but also I doubt it matters)

PHP version: 8.1.29

SQL version: I don't know (as above)

**Comment by bmillwood** [comment]
some discussion at https://stackoverflow.com/questions/925334/how-is-the-default-submit-button-on-an-html-form-determined of tricks to control which submit button is the default (though not obviously any way to prevent there from being any default, apart from [using JavaScript to eat the Enter keypress completely](https://stackoverflow.com/questions/895171/prevent-users-from-submitting-a-form-by-hitting-enter))

as an aside, I notice that the submit buttons all have the same id attribute, which is surely incorrect, but I don't think it's relevant here

**Comment by tobiasd** [comment]
Thanks for the report!

#14466 should fix the problem.
