### ISSUE TITLE
Table './friendica/item' is marked as crashed

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1447]
This is really frustrating. Do not understand how that table damage.

150323  7:51:38 [ERROR] /usr/sbin/mysqld: Table './friendica/item' is marked as crashed and last (automatic?) repair failed
150323  7:51:50 [ERROR] /usr/sbin/mysqld: Table './friendica/item' is marked as crashed and last (automatic?) repair failed
150323  7:51:50 [ERROR] /usr/sbin/mysqld: Table './friendica/item' is marked as crashed and last (automatic?) repair failed

<a href="http://upimage.mamalibre.com.ar/#ccac909f861015c11a130eee93846b9e.png"><img src="http://upimage.mamalibre.com.ar/up/ccac909f861015c11a130eee93846b9e.png" alt="Image hosting by Imagebin" /></a>

**Comment by annando** [comment]
Friendica can't damage your database. It will be an issue with your server.

**Comment by mama21mama** [comment]
I had to go back in time a backup. First day of March.
Throughout the only server that table was hurt ... really weird.
Security Check Please, also does not return to happen.
Of all the places only that was affected. very, very rare.

**Comment by annando** [comment]
Have a look at ytrabackup: http://www.percona.com/doc/percona-xtrabackup/2.2/

With this you can do a daily backup without locking your database.

**Comment by mama21mama** [comment]
via cron make my copies monthly. I like so.


script:
mysqldump -u root -proot friendica --databases | bzip2 -c  > "~/backup/friendica-$(date +%d-%m-%y).sql.bz2"

cron:

05 15 1 * * bash ~/scripts/bd >/dev/null

**Comment by annando** [comment]
I really would recommened a daily backup. (I'm thinking about an hourly backup at my system)

Since this isn't a Friendica issue, I would like to close it. Do you agree?

**Comment by mama21mama** [comment]
just remind me if in the future someone happens something similar. You can close the topic.

**Comment by n4rky** [comment]
Quoting Michael Vogel <notifications@github.com>:

> I really would recommened a daily backup. (I'm thinking about an  
> hourly backup at my system)

I concur on hourly backups. They've saved my tail a few times.

-- 
David Benfell <benfell@parts-unknown.org>
