### ISSUE TITLE
threads.net: signature expired

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#14488]
I'm not sure if this is a problem on friendica side (I believe friendica is acting correct).

I'm following a few accounts on threads.net (yes, I know) and I get a number of ignored posts to inbox with log statements as shown below.
It seems as if threads is signing with an **only five minutes** valid signature and when friendica tries to fetch the data the signature is already invalid.

1. Is there a way to disable the signature check in friendica?

2. May it be possible to add a grace period for signature checking? If the signature is expired but still correct, then accept during the grace period?

Log statements (always the three like this, I removed some sensitive/env values):

`2024-10-22T09:04:43Z app [NOTICE]: Signature expired {"created":"2024-10-22 08:57:57","expired":"2024-10-22 09:02:57","current":"2024-10-22 09:04:43"} - {"file":"HTTPSignature.php","line":780,"function":"getSigner","request-id":"67176aab60260","stack":"HTTPSignature::getSigner (112), Receiver::processInbox (95), Inbox::post (219), BaseModule::run (95), BaseApi::run (31), Inbox::run (668), App::runFrontend (32)","uid":"e0e399","process_id":4661}
`

`2024-10-22T09:04:43Z app [NOTICE]: Invalid HTTP signature, message will not be trusted. {"uid":0,"actor":"https://threads.net/ap/users/17841401319223604/","header":{"<env values removed>","USER":"www-data","HTTP_SIGNATURE":"keyId=\"https://threads.net/ap/users/17841401319223604/#main-key\",algorithm=\"rsa-sha256\",headers=\"(request-target) host date digest\",signature=\"cblnhB8tcYMCg2AIW/IlEmORhFf9gk8FGCGgHxqJH1yZp8PnvbN/OmCULiB3Ep6g887fux/zF6w9HYYITncQ0YTjKzGe7w73ujWrw4/thAwlYaxG2yWTr/rfyE6rU3dFzFXUlsA4nOaw1+BrI5d8tpB2LRyumH7qxmmMQbFNbBFlQz9fwx5PB4EupKXLlJL210WiS17JvGpQUnZgDgdtuR/PnhVsY/lgj204gkPFSxLDTSeSUltX38KsHrrcF08AbBaOyJsM/eVXO92gK5fSZ0pFAEH6k+nNIhgdgy20irRK1V7WImdoZLMg62R6feIlRbaRp7+KTexuDhdlx1QZgg==\"","HTTP_DIGEST":"SHA-256=UpGNMEEuw/f5p+J2FWYl0jYTZ3/QAqjaoHcbGWJ+v78=","HTTP_DATE":"Tue, 22 Oct 2024 08:57:57 GMT","HTTP_CONTENT_TYPE":"application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"","HTTP_USER_AGENT":"facebookexternalua","HTTP_ACCEPT_ENCODING":"deflate, gzip","HTTP_ACCEPT":"*/*","HTTP_CONTENT_LENGTH":"410","HTTP_X_REAL_IP":"2a03:2880:13ff:4::face:b00c","HTTP_FORWARDED":"for=2a03:2880:13ff:4::face:b00c; proto=https; by=fd00::1:8:13","HTTP_HOST":"fedi.0x42.ch","HTTP_X_FORWARDED_PROTO":"https","HTTP_X_FORWARDED_PORT":"8443","HTTP_X_FORWARDED_FOR":"2a03:2880:13ff:4::face:b00c","HTTP_X_FORWARDED_BY":"fd00::1:8:13:8443","SCRIPT_FILENAME":"/var/www/html/index.php","REDIRECT_STATUS":"200","SERVER_NAME":"","SERVER_PORT":"8080","SERVER_ADDR":"10.0.2.100","REMOTE_PORT":"","REMOTE_ADDR":"2a03:2880:13ff:4::face:b00c","SERVER_SOFTWARE":"nginx/1.27.2","GATEWAY_INTERFACE":"CGI/1.1","REQUEST_SCHEME":"http","SERVER_PROTOCOL":"HTTP/1.1","DOCUMENT_ROOT":"/var/www/html","DOCUMENT_URI":"/index.php","REQUEST_URI":"/inbox","SCRIPT_NAME":"/index.php","CONTENT_LENGTH":"410","CONTENT_TYPE":"application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"","REQUEST_METHOD":"POST","QUERY_STRING":"pagename=/inbox","FCGI_ROLE":"RESPONDER","PHP_SELF":"/index.php","REQUEST_TIME_FLOAT":1729587883.390656,"REQUEST_TIME":1729587883},"body":"{\"\\u0040context\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams\"],\"id\":\"https:\\/\\/threads.net\\/ap\\/users\\/17841401319223604\\/post\\/18023833043160272\\/#delete\",\"type\":\"Delete\",\"actor\":\"https:\\/\\/threads.net\\/ap\\/users\\/17841401319223604\\/\",\"to\":[\"https:\\/\\/www.w3.org\\/ns\\/activitystreams#Public\"],\"object\":{\"id\":\"https:\\/\\/threads.net\\/ap\\/users\\/17841401319223604\\/post\\/18023833043160272\\/\",\"type\":\"Tombstone\"}}"} - {"file":"Receiver.php","line":114,"function":"processInbox","request-id":"67176aab60260","stack":"Receiver::processInbox (95), Inbox::post (219), BaseModule::run (95), BaseApi::run (31), Inbox::run (668), App::runFrontend (32)","uid":"e0e399","process_id":4661}`

`2024-10-22T09:04:43Z app [NOTICE]: Activity was not fetchable, aborting. {"url":"https://threads.net/ap/users/17841401319223604/post/18023833043160272/#delete","uid":0} - {"file":"Processor.php","line":1608,"function":"fetchCachedActivity","request-id":"67176aab60260","stack":"Processor::fetchCachedActivity (326), Receiver::prepareObjectData (672), Receiver::processActivity (156), Receiver::processInbox (95), Inbox::post (219), BaseModule::run (95), BaseApi::run (31), Inbox::run (668), App::runFrontend (32)","uid":"e0e399","process_id":4661}`

**Comment by annando** [comment]
The signature check is crucial to maintain the data integrity, so it cannot be disabled. The 5 minute period is in fact our own rule. Each signature has got only a short time period to prevent replay attacks. It seems as if Threads needs a long time between signing and transport. I guess I check with other implementations, how their limits look like.

**Comment by loma-one** [comment]
If I remember correctly, the Fediverse is supplied with a time delay of 10 minutes. Can this play a role?

**Comment by ne20002** [comment]
So the limitation with the 5 minutes is used for preventing replay attacks? 
Assuming there is no other id that can be used identifying an inbox post, how about
- having the time limit extended or configurable and
- using redis for storing/lookup of the id/signature with a configurable timeout for the entries for preventing replay attacks?

**Comment by annando** [comment]
@loma-one normally the signature should be created right about the time of transmission.
