### ISSUE TITLE
Archive Links using SSL

### ISSUE THREAD

**Issue by DJoerger** [friendica/friendica#1451]
I'm using a self signed certificate for local links to secure Administration/Preferences and Login. Links to my profile, images etc. are not encrypted (as it should be), but the links in the archive selection box uses SSL... is there a reason for this or is it a bug?

**Comment by AlfredSK** [comment]
@DJoerger Is this still an issue? Or can this be closed?

**Comment by annando** [comment]
I really don't know. We now mostly use relative links, so all links should be with the same protocol.

**Comment by DJoerger** [comment]
I think this can be closed.

LG
Denis
