### ISSUE TITLE
UI glitches with posts and contacts

### ISSUE THREAD

**Issue by ddorian1** [friendica/friendica#1457]
I just noticed some (in my opinion) wired UI behavior with posts and contacts:
### What happens at the moment is:
- When I click on "View Profile", I get redirected to the contact's page on his pod
- When I click on "link to source" (respectively the icon) at a post, the post is shown **on my pod** and the profile of the contact is shown
### The problems I see with this:
- I would expect, that "link to source" leads to the real source (at the poster's pod). With the current behavior, I don't see any reason why someone should use this link to read the post.
  For contacts on other networks (e.g. diaspora) I may see nothing of his profile when clicking on "View Profile", because I'm not authenticated.
- As far as I know, the only way to see the (private) profile of such an account is to click on "link to source" at some of his posts. (Until now, I didn't even have known that I can actually see the profile of diaspora contacts.)
### What I would like to suggest to fix this:
- Change "link to source" to point to the posters pod
- Change the "View Profile" to show the users profile on **my** pod (and maybe add a link to the remote profile there). Beside being able to see the private profile of other network's users, another advantage would be, that the UI is more consistent, since I stay on my pod and see the profile with the theme I selected.

**Comment by rabuzarus** [comment]
Concerning the second point (show users profile on my pod):
This isn't possible because the profile is not on your pod (only the messages which have been sent to you)

**Comment by MrPetovan** [comment]
Link to source now points to the remote pod.
