### ISSUE TITLE
German translation confusing

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14587]
- [x] I have searched open and closed issues for duplicates

### Bug Description

[Transiflex](https://wiki.friendi.ca/translations) has been offline for some time, so here is a note.
The German translations for block, ignore and hide are not used consistently

In the content they are called ‘Blockiere, Ignoriere und Verberge’
In the submenu for /contact they are called ‘Geblockt, Ignoriert, Zugeklappt’

The terms in the submenu for /contact should be harmonised. E.g. ‘Blockiert, Ignoriert, Verborgen’

### Screenshots

Content > Sandwich-Menue

![2024-12-04_18-18](https://github.com/user-attachments/assets/5071826a-833d-4cc9-9cc6-1612d6a507d9)

Submenu Contact

![2024-12-04_18-19](https://github.com/user-attachments/assets/685e2af3-1a61-4c4a-873c-d58374581709)

### Platform Info

Friendica Version: RC

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by haheute** [comment]
I believe that was my fault. I think I found the term untranslated in transifex and chose "verberge" because it seemed easier to translate as "Verberge User X" than "klappe User X zu" which would need 2 words.

**Comment by haheute** [comment]
I have [changed it to](https://app.transifex.com/Friendica/friendica/translate/#de/messagespo/459612489) "Klappe {1%s} zu"  in Transifex. Maybe it fits better, since the source string is "collapse", not "hide".
