### ISSUE TITLE
The navigation bar of the settings-page is shown to each user.

### ISSUE THREAD

**Issue by FlxAlbroscheit** [friendica/friendica#1459]
When opening the settings-page, a navigation-bar including all setting-categories will be shown to a user who has not been logged in.

This possibility should be removed, as being useless for the user. Instead, he/she should be referred to the main-page to log in.

**Comment by annando** [comment]
Thanks to the pull request from @fabrixxm now no settings are revealed anymore. I'm closing the issue.
