### ISSUE TITLE
Friendica instances are spamming my atproto PDS with requests to `/.well-known/nodeinfo`

### ISSUE THREAD

**Issue by DavidBuchanan314** [friendica/friendica#14609]
### Bug Description
I have a web server at https://pds.dev.retr0.id/. It's an atproto PDS, nothing to do with ActivityPub. My HTTP request logs are filled with requests that look like this:

```
Dec 21 12:21:01 millipds[338320]: INFO:aiohttp.access:[redacted ip] [21/Dec/2024:12:21:01 +0000] (0.000807) "HEAD / HTTP/1.1" 200 266 "-" "Friendica/2024.08 DatabaseVersion/1571 Request/URLVerifier/1 +https://freundica.de"
Dec 21 12:21:01 millipds[338320]: INFO:aiohttp.access:[redacted ip] [21/Dec/2024:12:21:01 +0000] (0.000511) "GET /.well-known/nodeinfo HTTP/1.1" 404 175 "-" "Friendica/2024.08 DatabaseVersion/1571 Request/ServerInfo/1 +https://freundica.de"
```

(successful HEAD request to `/`, followed by 404ing GET to `/.well-known/nodeinfo`)

The request rate is multiple times per second, although sometimes it stops for a few minutes at a time.

As you can see, this happens a lot:

```
$ journalctl -u millipds.service | grep Friendica | wc -l
14484
````

I'm seeing these sorts of requests from a variety of instances, but I think the spam is mostly coming from `freundica.de` specifically (maybe it's a config issue on their end rather than Friendica itself). Please let me know if there's any more information I can provide to try to help this. Also if someone could help put me in touch with the `freundica.de` admin that would be great.

**Comment by DavidBuchanan314** [comment]
By the way, I'm reading about `/.well-known/nodeinfo` now and might add it to my PDS at some point

**Comment by DavidBuchanan314** [comment]
```
$ journalctl -u millipds.service | grep Friendica | cut -d "+" -f 3 | sort | uniq -c | sort -nr
  14832 https://freundica.de"
     40 https://superstimul.us"
     40 https://social.raitisoja.net"
     40 https://social.badabam.net"
     40 https://sekretaerbaer.de"
     40 https://friendica.opensocial.space"
     40 https://friendica.ingram-braun.net"
     40 
     34 https://loma.ml"
     28 https://hub.azkware.net"
     26 https://thegoatery.dyndns.org"
     18 https://poliverso.org"
     18 https://fc1.entities.org.uk"
     12 https://my-place.social"
     12 https://friendica.myportal.social"
     12 https://f.doskel.net"
     10 https://friendica.hellquist.eu"
      2 https://friendica.world"
```

**Comment by annando** [comment]
I've got the impression as if the `UpdateContact` process at freundica.de fails with some fatal error (or something similar), so that the worker is repeated over and over again. I will have a look if we can cover this behaviour.
