### ISSUE TITLE
Calling /settings/importcontacts leads to the message ‘Not Found’

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14614]
- [x] I have searched open and closed issues for duplicates

### Bug Description

After this morning's pull, the /settings/importcontacts page cannot be accessed. Message ‘Not Found’

```
Exception thrown in /var/www/html/friendica/src/Module/HTTPException/PageNotFound.php:35
Stack trace:
#0 /var/www/html/friendica/src/BaseModule.php(236): Friendica\Module\HTTPException\PageNotFound->content()
#1 /var/www/html/friendica/src/Module/HTTPException/PageNotFound.php(66): Friendica\BaseModule->run()
#2 /var/www/html/friendica/src/App.php(668): Friendica\Module\HTTPException\PageNotFound->run()
#3 /var/www/html/friendica/index.php(41): Friendica\App->runFrontend()
#4 {main}

```
However, the call on the test instance was successful

Actual Result:
Page /settings/importcontacts cannot be called up

Expected Result:
Page /settings/importcontacts can be called up

### Platform Info

Friendica Version: RC 1576/1576 Post-Update-Version 1550/1550.

Friendica Source:  github

PHP version: 8.1

SQL version: 10.5

**Comment by annando** [comment]
Hmm, it works here ...
![grafik](https://github.com/user-attachments/assets/f11bb8c4-ee54-4f3f-b5ae-f513154481ad)

**Comment by loma-one** [comment]
Yes, it also works on two other test instances. They first have to prove themselves before I perform the pull on my main instance. In this case, something went wrong.

**Comment by loma-one** [comment]
Local Problem
