### ISSUE TITLE
friendica.com still offline - what to do?

### ISSUE THREAD

**Issue by annando** [friendica/friendica#1462]
Since yesterday the site friendica.com and with it the global directory aren't available anymore. Either if it was intentionally or a hoster problem, it shows us that there is something to do.

Yesterday I quickly set up a page under http://friendi.ca (mostly copied from wikipedia and cached parts of the old page). if someone can access the settings of this repository we should move that page here - and someone with a feeling for design could make it more beautiful :)

**Comment by ericcotelnu** [comment]
It's up now.

**Comment by annando** [comment]
Yeah, I'm relieved. But anyway we should set up a small page under friendi.ca.

**Comment by annando** [comment]
@friendica Could you add github pages for this project?

**Comment by friendica** [comment]
Your project page has been created at http://friendica.github.io/friendica. Read more at https://help.github.com/pages.

**Comment by annando** [comment]
Thanks, it all seems to work. There's now a basic page under http://friendi.ca that can be changed in the future.
