### ISSUE TITLE
[Error] "Database isn't ready or populated yet" and "Friendica isn't properly installed yet." after update to Debian 12

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14627]
I have upgraded to server to Debian 12. I am using the Yunohost package for Friendica https://github.com/YunoHost-Apps/friendica_ynh . After the upgrade all seemed to work fine - I was getting new post updates from the people I followed even registrations requests. But a day later I realized this:

![image](https://github.com/user-attachments/assets/8a1cfb39-eea0-48b3-9b84-bef6aff07cf9)

`The last worker process started at 2024-12-24 22:58:07 UTC. This is more than one hour ago. Please adjust your crontab settings.`

The Friendica Yunohost uses a daemon and the daemon is working when I check the server's processes:

![image](https://github.com/user-attachments/assets/45940c9e-0da8-457d-8c87-a70a9b44adf8)

But when I SSH into the server and from Friendica's install folder I do "bin/daemon.php status" I get: `Friendica isn't properly installed yet`. It is the first time I see this. When I try to put Friendica in maintenance mode I get 
```
root@server /var/www/friendica # bin/console maintenance 1
[Error] Database isn't ready or populated yet
```

This is so strange....can anyone help? We've been running Friendica for a while now and it worked just fine. The Yunohost and Debian upgrade should not have touched the Friendica package.

From the daemon logs I see this https://paste.yunohost.org/ibujozamep and especially:
```

#8 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#9 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#10 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#11 /var/www/friendica/bin/daemon.php(64): Dice\Dice->create()
#12 {main}
  thrown in /var/www/friendica/src/Database/Database.php on line 201
Starting worker daemon.
Child process started with pid 898204.
PHP Fatal error:  Uncaught mysqli_sql_exception: No such file or directory in /var/www/friendica/src/Database/Database.php:201
Stack trace:
#0 /var/www/friendica/src/Database/Database.php(201): mysqli->__construct()
#1 /var/www/friendica/src/Database/Database.php(106): Friendica\Database\Database->connect()
#2 [internal function]: Friendica\Database\Database->__construct()
#3 /var/www/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#4 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#5 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#6 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#7 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#8 /var/www/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#9 /var/www/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#10 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#11 /var/www/friendica/bin/daemon.php(64): Dice\Dice->create()
#12 {main}
  thrown in /var/www/friendica/src/Database/Database.php on line 201
Starting worker daemon.
Child process started with pid 963790.
Worker daemon process 963790 was killed.
Starting worker daemon.
Child process started with pid 2050.
Worker daemon process 2050 was killed.
Starting worker daemon.
Child process started with pid 1961.
Starting worker daemon.
Child process started with pid 2993.
Starting worker daemon.
Child process started with pid 3329.
Starting worker daemon.
Child process started with pid 2814.
Worker daemon process 2814 was killed.
Starting worker daemon.
Child process started with pid 2300.
Worker daemon process 2300 was killed.
Starting worker daemon.
Child process started with pid 2142.
Worker daemon process 2142 was killed.
Starting worker daemon.
Child process started with pid 2028.
Worker daemon process 2028 was killed.
Starting worker daemon.
Child process started with pid 14988.
```

`Uncaught mysqli_sql_exception: No such file or directory in /var/www/friendica/src/Database/Database.php:201` ???

**Comment by MrPetovan** [comment]
This is a vague error message that can mean several things. Can you please confirm the database server version you're running?

Also what's the output of `php -i | grep socket` ? It should give you something like this:
```
/etc/php/8.2/cli/conf.d/20-sockets.ini,
mysqli.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
sockets
default_socket_timeout => 60 => 60
```
I'm interested in the `mysqli.default_socket` value, see if this file exists and what its permissions are, for example `ls -l /var/run/mysqld/mysqld.sock`.

**Comment by tio-trom** [comment]
`MariaDB version 10.11.6 `

```
php -i | grep socket
/etc/php/7.4/cli/conf.d/20-sockets.ini,
sockets
default_socket_timeout => 60 => 60

```
I wonder why is the php 7.4 ? 

```
ls -l /var/run/mysqld/mysqld.sock
srwxrwxrwx 1 mysql mysql 0 Dec 26 11:37 /var/run/mysqld/mysqld.sock

```
And btw the worker is running if I run it with `sudo -u friendica /usr/bin/php8.2 /var/www/friendica/bin/worker.php`

Thanks!

**Comment by MrPetovan** [comment]
It looks like you found your problem, please let us know if there's anything else we can help you with!

**Comment by tio-trom** [comment]
Thing is I found a solution that only works for a few minutes and I have to trigger it via SSH. But I still do not know where the issue is to fix it permanently...if you think this is too YNH related feel free to close this issue and I will continue on the YNH github page. 

In essence I still do not know how to fix the issue for good.

**Comment by MrPetovan** [comment]
It looks like your default PHP version has reverted to 7.4. Would you be able to run this command:
```
$ sudo update-alternatives --set php /usr/bin/php8.2 
```
This should make PHP 8.2 your default version for command-line. Apparently the loaded Apache module is still PHP 8.2 which is what we want.

**Comment by tio-trom** [comment]
Ah you saved me :) That fixed it. Many many thanks! Interesting how the default PHP version changed to 7.4. @MrPetovan thank you very much!
