### ISSUE TITLE
Unable to receive events from Wordpress

### ISSUE THREAD

**Issue by mexon** [friendica/friendica#14630]
When using Wordpress with the Activitypub and [EventsBridge](https://code.event-federation.eu/Event-Federation/wordpress-activitypub-event-bridge) plugins enabled, events that are published are not received by Friendica.

The issue seems to be due to them using a context of `https://schema.org/`, which is then used for the `externalParticipationUrl` field.  The URL cannot be used to retrieve the schema definition.

**Comment by annando** [comment]
Can you provide a link to the failing document?

**Comment by mexon** [comment]
Here's an example document: 
[signed-activitypubJ7Lit5.json](https://github.com/user-attachments/files/18262592/signed-activitypubJ7Lit5.json)
