### ISSUE TITLE
Registration E-Mail is not arriving

### ISSUE THREAD

**Issue by K8chel0fen** [friendica/friendica#1464]
I'm new to friendica and I chose to use uberspace for it. I followed all steps through the installation guide and it worked fine until I wanted to register my admin account. The mail with the password never arrived. I made another test account with another e-mail adress than the admin address and it happened the same. No mail with a password. So I gave up first until 2 days later an e-mail arrived but only to my secondary account. Since it isn't the admin account I can't make any changes. I like the idea of friendica but somethings not working properly. Have I done something wrong? Is it perhaps a problem with uberspace? Is there anyone with the same problem or anyone who knows a solution?

**Comment by annando** [comment]
Do you use a mail provider like Google Mail? They have a very strict spam checking. I had issues with sending notification mails to Google addresses in the past.

It's not really a Friendica issue but an issue with the whole mail system.

**Comment by ddorian1** [comment]
If you don't have activated mail-redirection for your uberspace account, you may register with your uberspace mail address. Then you should find the mail in your uberapace maildir.

Btw. If your second account is working, afaik it should be possible to make this account the admin account by simply changing the admin mail address in the config file.

**Comment by K8chel0fen** [comment]
My mail provider is startmail. I had no issues with them yet. I'll try to register with my uberspace mail adress like ddorian1 suggested. The second account is for trashmails and test purposes, so I don't really like to use it for my admin account. But since it doesn't seem to be a Friendica issue I'm trying to get further help in the uberspace board or my mail provider, if I get nowhere. Thanks for the replies.

**Comment by silke** [comment]
Hi, I'm closing this issue. Good luck figuring it out!
