### ISSUE TITLE
mysql warning in error.log

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1465]
I've got this warning message all over my mysql error log:

[Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statements writing to a table with an auto-increment column after selecting from another table are unsafe because the order in which rows are retrieved determines what (if any) rows will be written. This order cannot be predicted and may differ on master and the slave. Statement: DELETE FROM `gcontact` WHERE `nurl` = 'http://snarl.de/profile/tugelblend' AND `id` != 602 AND
                NOT EXISTS (SELECT `gcid` FROM `glink` WHERE `gcid` = `gcontact`.`id`)

**Comment by tobiasd** [comment]
seems not to be that relevant? see https://stackoverflow.com/questions/17057593/warning-unsafe-statement-written-to-the-binary-log-using-statement-format-since

can we close this?

**Comment by tugelbend** [comment]
Yep. Can be closed.
