### ISSUE TITLE
Endless scroll with frost-mobile doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#1482]
If endless scroll is enabled the pagination buttons in frost-mobile theme are disappearing. Looks like only the network page is affected.

**Comment by ddorian1** [comment]
Actually this was intended by my patch a while ago, since I considered them useless and even confusing when endless scrolling is enabled. (Only the network page is affected because endless scrolling only works there atm)

**Comment by AlfredSK** [comment]
Okay. Then the hiding of the buttons is fine, but the endless scrolling with frost-mobile does not work nonetheless.

**Comment by annando** [comment]
@AlfredSK Could you test it again?

**Comment by AlfredSK** [comment]
Hmm. I'm on the master branch. But I'll try to test it...

**Comment by AlfredSK** [comment]
Test passed. Infinite scrolling is working with this fix.

**Comment by annando** [comment]
Okay. Then I'm closing the issue.
