### ISSUE TITLE
upload avatar to merged profile

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1489]
Hi.
After uploading profiles to a new server uploading a new avatar doesn't work correctly.
The uploaded photo is displayed in the photo page as profile photo but not displayed in the directory, the profile itself or anywhere else. It also doesn't federated as avatar when connecting to others.

https://tupambae.org/photos/lzjiec2apbeqhveaz6vmzvhtefb3b9pygm
https://tupambae.org/profile/lzjiec2apbeqhveaz6vmzvhtefb3b9pygm
https://tupambae.org/directory

**Comment by annando** [comment]
This could be a problem of your server configuration regarding your problem with background jobs.

**Comment by TupambaeNet** [comment]
I actually doubt that it is a problem because of my server settings. I also have problems to connect to those accounts from diaspora. New profiles don't show these problems at all.
https://github.com/friendica/friendica/issues/1491

Do we have two well installed severs to test this some how?

**Comment by tobiasd** [comment]
problem seems to be that the photo entry in ttable contacts with `userid=0` and your `url=your_profileurl`. At Hackathon16 we discussed this and decided to put this in the 3.5.2 milestone.

**Comment by annando** [comment]
@tobiasd Could you remind we what we spoke about exactly?

**Comment by tobiasd** [comment]
IIRC the `photo` in the `profile` table is not set properly.

**Comment by annando** [comment]
The photo field is okay. I need some example to fix the problem.

**Comment by Hypolite** [comment]
The problem I've experienced is a picture discrepancy between the public contact (uid=0) and the personal contact (uid=1). Since either are displayed in different parts of Friendica (for very good reasons), different avatars can show up.

**Comment by Hypolite** [comment]
A new example in two parts, Thomas Willingham changed his profile picture this morning, and even on his instance the picture of his public profile isn't updated, while the profile picture of his local account is.

![screen shot 2017-03-28 at 10 09 08 am](https://cloud.githubusercontent.com/assets/925415/24409702/fa1e531c-139e-11e7-87a3-adf472e7cb42.png)

A view from my instance:

![screen shot 2017-03-28 at 10 21 16 am](https://cloud.githubusercontent.com/assets/925415/24410155/5328da80-13a0-11e7-924e-2c041638e8ac.png)

**Comment by annando** [comment]
We are having two different issues here. The one is the simple change of the avatar. The other one is the result of moving your profile from one server to another one.

**Comment by Hypolite** [comment]
There is now a specific issue opened for the avatar change : #3309

**Comment by annando** [comment]
Is this still an issue?

**Comment by MrPetovan** [comment]
Closed for inactivity.
