### ISSUE TITLE
uploading existing profile circunvents admin autorisation

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1490]
When the registration settings in admin panel are set to "autorisation by admin" in the register page the setting "upload existing profile" is available. Uploading a profile gives immediate access to the profile with the "old password" without the need of approval  of the new account by the site admin.

**Comment by annando** [comment]
In fact this isn't coded at all. The easiest solution would be to not allow this feature on such servers.

**Comment by tobiasd** [comment]
Then the admin should have a way to import accounts manually, thus approving by action.

**Comment by annando** [comment]
For systems with a closed registration this is already the case that the administrator can import an account file.

I would like to change the behaviour so that the import is only possible on open registrations or when the administrator is doing it personally.

Everything else has got some more possible problems.

**Comment by tobiasd** [comment]
> For systems with a closed registration this is already the case that
> the administrator can import an account file.

How is it done in that case?

**Comment by annando** [comment]
The administrator has to be logged in. Since the account file contains the account name, this is no problem.

**Comment by tobiasd** [comment]
> The administrator has to be logged in. Since the account file
> contains the account name, this is no problem.

And then they call the uimport module to upload the file?

**Comment by annando** [comment]
Yes. So had been the existent coding for closed systems.

**Comment by tobiasd** [comment]
> Yes. So had been the existent coding for closed systems.

Could you add it to the documentation and as a hint on the UImport page, when the registration is closed, one should contact the admin of the node if an upload/relocation was possible.

**Comment by annando** [comment]
Every time you say "add it to the documentation" I'm totally lost in finding the right place. :-)

**Comment by MrPetovan** [comment]
1. Look for an existing mention to user import
2. If you can't find anything, create a new page and link it it in the user/admin/dev manual
