### ISSUE TITLE
Define one friendica UI as standard and create styles branch

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1492]
I started into websites by playing with phpbb so my mindset/experience might be "programed" by "what I'm used to", .. anyway ..

I trully believe we should have only one UI and center all friendica developers attention on that one, in any case opening playing fields by option settings for users and/or admins like color change or box display options like header-footer-left and right box fields.
I consider that duepunto zero and parents are from Mike's time when he coded and displayed his ideas on his basic UI. When I travel the friendica-universe I basically stumble over two or three UI and switch maself basically between diabook and vier. I favor vier but in some views like directory diabook displayes better. Also the bug report button doesn't exist in vier so I actually had to switch UI just for to access as it should be.
I think a styles branch for optional styles or styles to develop should be created and one style (vier in my opinion) should be pollished "exclusively" until it's "perfect" in the sense of including the user experience, accessibility of option settings and so on.

Several UI are simply confusing, dividing efforts and some how a waste of time for a small coder community. A comprehensive styles wiki should be enough for the styles coder community to bring themselfs into the playfield when ever they want.

**Comment by tobiasd** [comment]
Are you aware of the [UX Watchdogs](https://fc.oscp.info/profile/ux-watchdogs) and the ongoing work to improve the UX and the work on a new theme?

**Comment by TupambaeNet** [comment]
No i wasn't really aware of it, think I saw the profile, that's why I added " including the user experience" I suppose. I know that this issue isn't new but didn't find a "request" over here so just decided to pin it here. 
joined watchdogs .. 
Is there any mayor thread with discussion on how to tackel this?

**Comment by tobiasd** [comment]
Yes, the forum is used actively for discussions, coordination and stuff like finding the next date for a chat in IRC ;-)

**Comment by MrPetovan** [comment]
Since the publication of this issue, another non-standard theme has been added (frio) and we're nowhere near a consensus about a standard theme.
