### ISSUE TITLE
BBCode

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1493]
There is some BBcode I'd like to use like "spoiler" that should be in the basic friendica setup in my opinion.
At the same time I think it would be important to be able to add bbcode via the admin panel to customize servers. As an example, I'm trying to setup sites with e-coin and paypal donation options. On a phpBB board due to the ability to ad bbcode I could add a paypal options field via bbcode and bitcoin/litecoin donation buttons that refer to the user wallet for donations as well as displaying wallet information like savings or transactions. With the actual bbcode I only could create some buttons like in this example in the footer of the impressum addon for friendica: https://tupambae.net

In this phpBB board portal: https://tupambae.com you can see the donation boxes on the right side and in the center (in the middle of the page) as a demonstration of what I'm talking about, hoovering over the buttons you'll see some extra info on the idea. Clicking on the flour buttons the following action is called: litecoin:LdzFYLCPt7Brv6ebFQRKQSMsFmuD65SyCV?amount=1.00&label=Seeds%20CafeteroClub&message=Donation%20for%20seeds

related: #1610

**Comment by tobiasd** [comment]
> There is some BBcode I'd like to use like "spoiler" that should be in the basic friendica setup inmyopinion.

It is, just use

    [spoiler]Something spoiling here[/spoiler]

and the spoiling text will be hidden.

**Comment by TupambaeNet** [comment]
Oh nice, I couldn't find spoiler in the help text infos.

The real request is the possibility to add personal bbcode or to add some bbcode to friendica itself.
These for example is the the bitcoin and paypal donation codes I used at the phpBB board:

<addr> <a href=bitcoin:{INTTEXT}?amount={INTTEXT1}&label={INTTEXT4}&message={INTTEXT3} title=Click para donar bitcoins><img src=https://tupambae.com/images/site_image/bitcoin-fleur-64.png  title="Donar {INTTEXT1} {INTTEXT2}" /></a>

<addr> <form name="_xclick" action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="{EMAIL}">
<input type="hidden" name="item_name" value="Donacion a traves del sitio tupambae.com">
<input name="amount" value="5.00" onclick="if (this.value == '5.00')
this.value = '';" onblur="if (this.value == '') this.value = "5.00';">
<select name="currency_code">
<option value="USD">USD (&#36;)</option>
<option value="EUR">Euro (&euro;)</option>
</select>
<input type="image" src="http://tupambae.com/images/site_image/donar.jpg" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
</form>

**Comment by TupambaeNet** [comment]
Oh nice, I couldn't find spoiler in the help text infos.

The real request is the possibility to add personal bbcode or to add some bbcode to friendica itself.
These for example is the the bitcoin and paypal donation codes I used at the phpBB board:

<a href=bitcoin:{INTTEXT}?amount={INTTEXT1}&label={INTTEXT4}&message={INTTEXT3} title=Click para donar bitcoins><img src=https://tupambae.com/images/site_image/bitcoin-fleur-64.png  title="Donar {INTTEXT1} {INTTEXT2}" /></a>

<form name="_xclick" action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="{EMAIL}">
<input type="hidden" name="item_name" value="Donacion a traves del sitio tupambae.com">
<input name="amount" value="5.00" onclick="if (this.value == '5.00')
this.value = '';" onblur="if (this.value == '') this.value = "5.00';">
<select name="currency_code">
<option value="USD">USD (&#36;)</option>
<option value="EUR">Euro (&euro;)</option>
</select>
<input type="image" src="http://tupambae.com/images/site_image/donar.jpg" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
</form>

**Comment by TupambaeNet** [comment]
Oh nice, I couldn't find spoiler in the help text infos.

The real request is the possibility to add personal bbcode or to add some bbcode to friendica itself.
These for example is the the bitcoin and paypal donation codes I used at the phpBB board:

'<a href=bitcoin:{INTTEXT}?amount={INTTEXT1}&label={INTTEXT4}&message={INTTEXT3} title=Click para donar bitcoins><img src=https://tupambae.com/images/site_image/bitcoin-fleur-64.png  title="Donar {INTTEXT1} {INTTEXT2}" /></a>'

'<form name="_xclick" action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="{EMAIL}">
<input type="hidden" name="item_name" value="Donacion a traves del sitio tupambae.com">
<input name="amount" value="5.00" onclick="if (this.value == '5.00')
this.value = '';" onblur="if (this.value == '') this.value = "5.00';">
<select name="currency_code">
<option value="USD">USD (&#36;)</option>
<option value="EUR">Euro (&euro;)</option>
</select>
<input type="image" src="http://tupambae.com/images/site_image/donar.jpg" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
</form>'

**Comment by TupambaeNet** [comment]
Oh nice, I couldn't find spoiler in the help text infos.

The real request is the possibility to add personal bbcode or to add some bbcode to friendica itself.
I can't find the correct way to post the code here so I will try to post it to the developers forum.

**Comment by tobiasd** [comment]
But your private bbcode wont be displayable on the remote node receiving your postings containing that code--right?

**Comment by fabrixxm** [comment]
Il 07 aprile 2015 18:16:42 CEST, Tobias Diekershoff <notifications@github.com> ha scritto:
>But your private bbcode wont be displayable on the remote node
>receiving your postings containing that code--right?
>

Yep.

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by TupambaeNet** [comment]
That's in part what I was wondering about. The bbcode is translated for federation to diaspora and other conectors I suppose, so the basic problem is friendica internally passing it just like it is .

What about something like extended smiley packs, couldn't something like this be done for bbcode? Point is how it would be displayed when the "extended bbcode-addon" isn't activated on a friendica server.

Wouldn't it be possible to create a general bbcode that triggers commands like :bitcoin :litecoin or other applications?

**Comment by MrPetovan** [comment]
This feature request is far out of Friendica's scope and since it hasn't got any taker in 4 years, I'm closing it.
