### ISSUE TITLE
UI Settings linked between admin and admin profile settings

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1495]
When in the admin panel the site UI is set to vier but in the admin profile settings the UI diabook is selected, the vier settings that are supposed to be selectabl ein the admin settings show blank diabook fields option instead of the vier theme selector field.

**Comment by tobiasd** [comment]
Could reproduce that behavior on my node with a combination of clean and duepunto themes (as Diabook is not supported anymore). The wrong theme settings template file (from the theme the admin uses) is loaded.

**Comment by MrPetovan** [comment]
Closed via #6340
