### ISSUE TITLE
Creating groups directly from the sidebar in contacts-page

### ISSUE THREAD

**Issue by FlxAlbroscheit** [friendica/friendica#1504]
The current way of creating a new group of users is a bit messy. Starting from the contacts-page, you will click "Create a new group" in the sidebar, be then directed to */group/new* (where you type in the group's name) to finally manage the group's permission at */group/{ID}*.

This process can be made more easy when displaying the form from /group/new right under the "Create a new group"-label in the sidebar, after clicking on it (such changes would only affect group_side.tpl). However, there is (for some reason...) a security-token used in group_edit.tpl which would need to be generated when displaying the sidebar (= group_side.tpl).

#ui #juniorjobs

**Comment by FlxAlbroscheit** [comment]
Bump - Could take care of this issue. However, the question is whether the use of security-token's (there are about 11 of them in mod/group.php) makes any sense... at least as long as the user is logged into the network?!

**Comment by tobiasd** [comment]
fixed in #1554
