### ISSUE TITLE
blank page when adressing post to email

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1506]
When posting to an email address over the
_CC: email addresses_
field, posting restricted to some profiles and an email address a blank page https://tupambae.net/item is displayed. Apparently emails are not delivered, (still checking on this).
Actual settings:
_Connectors disabled, since "Hide your profile details from unknown viewers?" is enabled._
________
edit:
Tested without hidden profile and different options of sending. The profile itself has email contacts. It's a little bit confusing as the email check box seems to be related in part to contacts that are email contacts. Public posts with checkbox send mails to email contacts, restricted posts without checkbox sends to email contacts that are selected. Whenever email addresses are entered in the email address field the blank item page appears and no email is send. Not to emails that are in the contact list and not to the particularly addressed email.

**Comment by annando** [comment]
Please have a look into the php logfile (not the friendica logfile). Mostly when a blank page occurs it was caused by a php error.

**Comment by TupambaeNet** [comment]
Apparently our site was using proc_runner instead of poormancron which should have been enabled, maybe that's what caused this, I will check it again.

**Comment by TupambaeNet** [comment]
This is the only error message I could find till now:
[10-Apr-2015 13:05:20 America/Lima] PHP Fatal error:  Class 'enotify' not found in /var/www/virtual/tupambae.net/htdocs/mod/item.php on line 986

**Comment by annando** [comment]
Please switch to 3.4.0. It is a known bug in a past version.
