### ISSUE TITLE
Improve notification messages

### ISSUE THREAD

**Issue by FlxAlbroscheit** [friendica/friendica#1508]
This is a feature the Diaspora community recently integrated and I really like it: 

Instead of giving a notification each time a user commented or liked a post, the system should have a look if there has already been a similar (yet unread) notification on this thread and then re-generate it into something like "*xy* **and** *xz* commented on ..." OR "*xy* **and** *xz* liked..."

**Comment by FlxAlbroscheit** [comment]
![this](https://cloud.githubusercontent.com/assets/2439195/7118040/f409b960-e1fc-11e4-97e9-19ab5c348cdc.png)

**...Point 2:** If there has already been a similar notification generated for a (yet unread) thread, simply UPDATE THE TIMESTAMP which will increase the UX about 946484³ times ;)

**Comment by annando** [comment]
BTW: I'm currently working at it.

**Comment by FlxAlbroscheit** [comment]
Thx! I recently noticed that the *'notify'*-table seems to be designed following the activitystrea.ms 1.0-protocol... I was not sure whether changings which affect the table-layout (...if such are necessary) will "damage" these guidelines?!

**Comment by annando** [comment]
The changes are only additional data (like the id of the message the notification refers to) and filling the "parent" value at every time.

Most of the changes are in the post-processing.

**Comment by annando** [comment]
I've done a pull request for it: https://github.com/friendica/friendica/pull/1529

**Comment by annando** [comment]
I will close this issue if nobody minds.
