### ISSUE TITLE
no notification in OStatus conversations

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1513]
When communicating with an OStatus contacts that does not use the old-style @-reply style for a reply but leaves the mention out of the message, there is no notification added to the notification list.

**Comment by annando** [comment]
I have code for this in the new OStatus part - but it doesn't seem to work by now. I will try to fix it.

**Comment by annando** [comment]
@tobiasd Could you check whether it works now? My tests were successful.

**Comment by tobiasd** [comment]
I have only one GS contact who always don't mention my username, and he's on vaccation ATM ;-) So I'll have an eye open for this issue but cant promise anything *soon*

**Comment by tobiasd** [comment]
I finally received a reply (threaded correctly) without an @-mention but got no notification about it. Possible problem on this, I was still on the other branch tesing the fix for mobile view, so I don't know for sure if the updated OStatus parts were in it (but I assume from the shown list of changed files when switching the branches).

**Comment by annando** [comment]
You could have a look into the original message. It is stored into the field "object" in the item. If your profile was mentioned there, then it isn't working correctly.

**Comment by annando** [comment]
BTW: I wouldn't define this as a blocker. I think we can do the release if there are no other issues.

**Comment by tobiasd** [comment]
I agree especially since I got notified for another contacts reply. I have not investigated the differences between their SN/GS instances. So closing this issue.
