### ISSUE TITLE
fbpost: link to photo rather than upload to Facebook

### ISSUE THREAD

**Issue by treellama** [friendica/friendica#1522]
For various reasons, I don't really trust Facebook to store my photos. When posting a single photo with fbpost, though, it uses the /photo edge to upload the photo to Facebook.

Instead, I'm going to modify my local copy to include it as a link back to the original. In the interest of upstreaming it, there are a few options:

1. Change the behavior of the plugin to work that way without an option
2. Add a user or admin preference for handling photos
3. Perhaps this change isn't of general interest, in which case I can just maintain it locally

Thoughts?

**Comment by annando** [comment]
The default behaviour should stay the upload. Everything else reduces the "user experience" of the Facebook users. And since Facebook even stores the preview pictures of linked pictures it would also store a photo that was only linked.

If you want to do a pull request please make it a user setting where the default value is the current behaviour.

**Comment by treellama** [comment]
> The default behaviour should stay the upload. Everything else reduces the "user experience" of the Facebook users.

Makes sense, I agree.

> And since Facebook even stores the preview pictures of linked pictures it would also store a photo that was only linked.

Also true, but including an image in the remote metadata may not give Facebook the same permissions as uploading an image directly to the site on a user's behalf. On the other hand, it may be impossible to remove a cached link preview, unlike a directly uploaded image!

Perhaps the user setting ought to have three options: post to Facebook, link with preview image, and link without preview image. I'll think about it some more.

**Comment by annando** [comment]
Sounds like you want to work at it. So can I close this issue and you open an pull request when it is done?

**Comment by annando** [comment]
Or should I assign this to you?

**Comment by treellama** [comment]
Yep I can open a pull request if you want to close this
