### ISSUE TITLE
Bug with add Friendica's contact

### ISSUE THREAD

**Issue by StefOfficiel** [friendica/friendica#1528]
### Hi everybody !
I have a little problem for a few weeks (months), I can not add Friendica contact.
I can add Diaspora's contacts and OS-Status contacts. But when I do an add request I have three error messages.

__________________________
In French:

``Attention: l'emplacement du profil n'a pas de nom identifiable.``
``Attention: l'emplacement du profil n'a pas de photo de profil.``
``1 paramètre requis n'a pas été trouvé à l'endroit indiqué``
__________________________

On the code, I found in the file "dfrn_request.php" in lines 123-133 ~ is this part that is turned around.

Have you ever been the case? Maybe it comes from my Friendica POD ?

Screenshot :
![Screenshot](https://lut.im/H9HcFTyw/sFqysk5X)

**Comment by fabrixxm** [comment]
It's your theme. It's missing some classes to form a valid hcard in the profile aside.
try this:

change

```html
<div class="Xprofile-content">
    <h2 class="visible-lg"></h2>
```

to

```html
<div class="Xprofile-content vcard">
    <h2 class="visible-lg fn"></h2>
```

**Comment by StefOfficiel** [comment]
Fuck yeah ! \o/

Thx @fabrixxm !
