### ISSUE TITLE
Posting to twitter gets cut off, no reference to original friendica post

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1540]
Seems that since 3.4 twitter postings that are too long are getting cut off but without referencing to the original post on friendica (which they did in the past). This can be pretty bad as the meaning of the posts gets lost or twisted on twitter.
![twitter_cut_off](https://cloud.githubusercontent.com/assets/3009959/7365192/40904334-ed8e-11e4-8ac1-8d71840fa45e.png)

**Comment by annando** [comment]
The behaviour hadn't changed since 3.3. I guess I had to write it down (maybe in the wiki?) to clarify it.

**Comment by tugelbend** [comment]
So this is intended? It's an anti-feature for me. 

If it should be handed like this there should be a warning in the editor as soon you exceed the 140 characters and twitter posting is activated.

**Comment by annando** [comment]
There is now a pull request for that: https://github.com/friendica/friendica/pull/1563

When the new option is activated then a shortened message will always point to the friendica post.

**Comment by tobiasd** [comment]
can we close this issue @tugelbend ?

**Comment by tobiasd** [comment]
What is the relation to #1559 same problem or a different one?

**Comment by annando** [comment]
That's different.

**Comment by tobiasd** [comment]
with #2377 there is now a BBCode tag to define an abstract for crossposting to size limited networks. (that is currently in development branch only)

**Comment by MrPetovan** [comment]
Per-user solution has been provided in #4144 by going to Settings -> Social Network -> Click on General Social Media Settings -> Disable intelligent shortening
