### ISSUE TITLE
Plugin - Show more

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1541]
Personal account settings are not taken over to post display for visitors.
When "show more" is disabled in the plugin setup of a profile, the post is displayed colapsed on the wall and in single page view.

**Comment by annando** [comment]
Personal account settings are relevant for the current user and the posts he is watching. If some other user is looking at the post then his own settings are used.

And if a guest is looking at the posts then a standard value is used.

This is no bug but the intended behaviour. We could extend this for a default value that could be set in the admin settings for this addon.
