### ISSUE TITLE
Old GNU Social/Ostatus postings popping up (again) in network tab

### ISSUE THREAD

**Issue by DNS777** [friendica/friendica#1552]
I recognized strange behaviour of old Ostatus postings (especially from pirati.ca ... sorry) popping up after 1 or 2 weeks, after they were displayed before.
And if i delete them, then they appear again after some time (~ 1-3 days)

**Comment by tobiasd** [comment]
I think your SN/GS contacts just don't post enough ;-) friendica does delete the posting and with the next look at your contact it discovers that there is a "new" posting in the Atom feed of the contact that is not in the DB so it fetches it again.

I have this with blogs that I follow which get not updated so often; when the postings expire they will be fetched again.

**Comment by fabrixxm** [comment]
For expired items, the quick solution would be "don't import items older than `today - expire time`"
For deleted items.. I should check how items are deleted, we could flag items as deleted and let them expire (we don't import items that are already in db and older than expire time)
But if the channel didn't set any expire time, items are never deleted from db...

**Comment by annando** [comment]
It's no UX stuff, it's a protocol issue with OStatus. I really, really would like to rewrite the whole stuff ...

**Comment by ben-utzer** [comment]
I also have that problem, so I asked on Friendica the following:
"Gibt es Probleme mit status.pirati.ca? Ich bekomme da hin und wieder lauter doppelte Posts von einem Nutzer.

https://social.yl.ms/display/e18176ef125563031d63cf7904984059
https://social.yl.ms/display/e18176ef185563031c0b879275367539
https://social.yl.ms/display/e18176ef125563031a61b92381092905
https://social.yl.ms/display/e18176ef805563031969421446716102

Da habe ich noch ein ganze Reihe und das hatte die vor ein paar Tagen auch schon einmal."

Short discussion here: https://social.yl.ms/display/e18176ef1555630cc24727d457896441

**Comment by annando** [comment]
We rewrote the complete OStatus import. This problem won't occur again. It worked very well on my installation.

@DNS777 @tobiasd @ben-utzer Can you confirm that? (You have to be on the latest developer branch for that)

**Comment by tobiasd** [comment]
I have not had problems with old OStatus postings popping up, neither old blog postings.

**Comment by annando** [comment]
Since no one disagrees I'm closing the issue.
