### ISSUE TITLE
Bring Ubuntu Server 14.04 to our Vagrant

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1557]
The Vagrant development machine is still Ubuntu 12.04. Would be nice to have 14.04.

**Comment by tobiasd** [comment]
just connecting the vagrant issues #1556

**Comment by silke** [comment]
It's basically working but needs more tests. It also requires a vagrant upgrade. The vagrant 1.4.3 provided in Ubuntu 14.04 is too old to virtualize Ubuntu 14.04 with it. ;)

**Comment by tobiasd** [comment]
I think you can commit it so we can test it

**Comment by silke** [comment]
Closed with #2026
