### ISSUE TITLE
Links from Twitter get cut off

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1559]
I send a post containing a comment and a link from a Twitter account mirrored in Friendica.
- The tweet exceeds 140 characters.
- Twitter accepts it because their link shortener strips every link to 22 characters. It is then short enough to pass.

What gets through:
- the comment
- the image Friendica collects from the link target
  -> The link is missing in Friendica.

Everything works fine if the length of the tweet is under 140 characters before the link shortener does its job.

**Comment by annando** [comment]
This behaviour can be controlled by the setting that is described here: https://github.com/friendica/friendica/issues/1540#issuecomment-355478432

I think we can close the issue.
