### ISSUE TITLE
events in calendar are not deleted

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1561]
When I delete an event in the network stream the event shows up further on the calendar page (/friendica/events) of the people with whom I shared this event. There the colorbox popup gives the right information about the event but after clicking on the link to the source they get informed that the event could not be found.

I reproduced this behavior with 2 friendica instances

**Comment by tobiasd** [comment]
Similar, if one edizs the text of an event on the network tab, the even in the calendar wont be updated.

**Comment by annando** [comment]
This will be fixed in pull request https://github.com/friendica/friendica/pull/1966

**Comment by tobiasd** [comment]
works in develop branch, so I'm closing this issue
