### ISSUE TITLE
Connecting diaspora profiles doesn't work correctly from friendica

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1572]
When connecting to a diaspora account (automatic friend ship) the connection is apparently established. The new contact is notified in the diaspora profile and shows also up in the friendica profile as a friend. Post's send from friendica don't federate, mentions neither. When skipping the contact in the diaspora profile and than reconecting from diaspora without deleting the contact in friendica makes federation work.

**Comment by annando** [comment]
Have you connected from Friendica to Diaspora or from Diaspora to Friendica for the first connection?

**Comment by TupambaeNet** [comment]
This is about first connection from friendica to diaspora.

**Comment by annando** [comment]
I assume you meant that you initiated the contact request from the Diaspora account and not from the Friendica account.

Assuming this, the pull request https://github.com/friendica/friendica/pull/1585 should address this issue.

Please assure that "hide wall" isn't enabled in your account. This would prevent sending messages from Friendica to Diaspora as well.

**Comment by TupambaeNet** [comment]
No.
Nein es geht darum wenn der Kontakt von friendica aus hergestellt wird. Wird er von Diaspora aus hergestellt funktioniert es. Ebenso funktioniert es wenn der Diasporaccount nach einer ersten Kontaktaufnahme von friendica aus den Kontakt entfolgt und dann erneut zu seinen Kontakten hinzufügt. In friendica entstehen über ein solches entfolgen/folgen keine Nachrichten, aber Nachrichten werden dann durchgestellt.

**Comment by annando** [comment]
Um es zu verstehen: Du baust von Friendica zu Diaspora eine Verbindung auf - wieso sollte Dein Friendica-Beitrag dann bei Diaspora erscheinen? Der Diaspora-User hat die Verbindung nicht initiiert, also wieso sollte er den Friendica-User lesen wollen?

**Comment by TupambaeNet** [comment]
Sprich, wenn ich einen Diaspora Kontakt hinzufüge dann bekomme ich seine Nachrichten aber er bekommt zunächst einmal nicht meine Nachrichten. Dazu müßte der Diaspora Kontakt mir folgen. Der Diaspora Account hat jedoch automatisch folgen eingestellt, müßte also die Nachrichten die vom friendica Profil versendet werden bekommen, und das passiert erst wenn der friendica Kontakt auf diaspora entfolgt wird und dann erneut einem Aspekt/Gruppe hinzugefügt wird.

**Comment by TupambaeNet** [comment]
Haben wir hier Aussichten das dies Problem in absehbarer Zeit gelöst wird?
(Sorry, ich halte es "existenzeil für die Forenfunktion)

**Comment by annando** [comment]
Kann ich nicht sagen. Es gibt so irre viele Issues in letzter Zeit, dass es kaum möglich sein wird, sie alle in absehbarer Zeit umzusetzen.

**Comment by TupambaeNet** [comment]
Ist wahrscheinlich Zeit auf helpers die Milestone Diskusion zu führen. Dabei sollte korrekte Föderation und vorallem die Foren Funktion von Friendica best möglich integriert im federated web funktionieren.

Sie ist etwas was wir der D* community anbieten können, und DIE Möglichkeit Vereinen eine kleine ideale Plattform anszubieten von der aus sie ihre Soziale Netzwerk Komunikation in die eigene Hand nehmen können.

**Comment by annando** [comment]
We had rewritten the Diaspora implementation since then multiple times. I don't think that we still have such issues here.
