### ISSUE TITLE
Attachments  - critical issues

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1574]
As what for I can see, video attachments that are uploaded as personal notes or to restricted post's are not restricted in access at all.
Deleting a post that uploaded a video doesn't delete the attachment (video). Also there is no option to delete videos in the video tab.
.ogg audio files uploaded as attachment aren't displayed at all in the post. No possibility to delete the attachment.
.srt document file uploaded as attachment is not displayed at all in the post. No possibility to delete the attachment.

Not sure about the permission restrictions, some attachments are apparently restricted.
(when checking ://website/attach/1..2..3..)

**Comment by fabrixxm** [comment]
[quote]As what for I can see, video attachments that are uploaded as personal notes or to restricted post's are not restricted in access at all.[/quote]
I can't reproduce this. Video attached to restricted post can't be accessed by unauthorized user.
( see [this](https://kirgroup.com/attach/26?attachment=0) )

[quote]Deleting a post that uploaded a video doesn't delete the attachment (video). Also there is no option to delete videos in the video tab.[/quote]
Can reproduce this.

[quote].ogg audio files uploaded as attachment aren't displayed at all in the post. No possibility to delete the attachment.
.srt document file uploaded as attachment is not displayed at all in the post. No possibility to delete the attachment.[/quote]
Every attachment without a special handler are shown as icon at the bottom of the post.
If you don't see icons, that's a theme bug.
![bug_1574](https://cloud.githubusercontent.com/assets/309361/7785500/b53fe906-0192-11e5-9675-e16ddbe1332c.jpg)

**Comment by TupambaeNet** [comment]
I will have recheck on the unrestricted access to restricted attachments. I believe it was an upload of a personal note.
The theme used is vier, I will check with others.

**Comment by fabrixxm** [comment]
My attachment linked in previous comment was from personal note.
Please do your tests against "develop". Could be that some issues was already fixed :-)

**Comment by TupambaeNet** [comment]
I do git pulls by requests to the webhoster, i suppose that would mean some extra work and setting, i will have an eye on this and check when changes are merged to main stream.
