### ISSUE TITLE
forwarding posts to diaspora via Settings > Social Networks connector no longer works

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#1576]
This could well be related to the diaspora 0.5.x update. It seems forwarding posts from friendica to diaspora no longer works although login credentials are correct, have previously worked and not been changed.

Anybody up for looking into and fixing the php-script for the diaspora connector?

**Comment by annando** [comment]
To clarify: This happens when using the Diaspora connector in the Addon to use an existing Diaspora contact to post stuff.

The regular federation with Diaspora is unaffected from this.

**Comment by foss-** [comment]
Diaspora API needed https://github.com/diaspora/diaspora/pull/4554
But I don't have high hopes of seeing that in 2015 tbh.

**Comment by annando** [comment]
I don't think that we should enable the Diaspora connector again - even when there would be an API. I think that it is confusing for new users. They could easily think that this connector would be the only option to post to Diaspora. There is no advantage in using the connector. If a user wants to move to Friendica, the user should notify the followers on Diaspora of the new address.

**Comment by foss-** [comment]
Agreed. It was not obvious in the first place, Friendica accounts can be subscribed to from Diaspora. But since that is possible, your reasoning is true and valid. I am thus closing this bug.
