### ISSUE TITLE
own upload icon for .webm files

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1578]
I think the .webm video upload option is a outstanding feature on friendica. I haven't become aware until lately. Maybe a particular upload button for media (.webm, .ogg if possible) should be added to the posting.

**Comment by vinzv** [comment]
Why would one want to have a dedicated upload icon for a particular file format? I'd refrain from that and close the issue.

**Comment by MrPetovan** [comment]
Agreed.
