### ISSUE TITLE
request - sort  any post into categories

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1579]
In particular for post's that are crossposted to form pages I'd love to have the possibility to sort them into the category system that is available for own post's.This would be crucial to organize any kind of forum. This even refers to the platform discusion we had recently in a post of mike about if we need external service to comunicate and work on our federation and protocol issues.
With this feature the helpers forum for example could be "moderated" by sorting questions, bugreports, tutorials, interesting info or discussion and so on.

**Comment by fabrixxm** [comment]
categories are user related and not federated.
you can, anyway, add tags to contacts posts, and that would be federated.

**Comment by TupambaeNet** [comment]
I know that they are not related. This is for to be able to sort the own and the incoming stream. Anyone who visits a forum page will be able to find content by categories.

Example:  
Bug is posted to helpers forum, the admin places the post in "bug?" folder, conversacion  reveals that it's a bug, post is changed from category "Bug?" to "bug!" and maybe "minorbug", or "important bug" category. Bug is solved, post is changed to solved category.

Sportsclub .. a game is  sceduled and placed in "future games scedule". The week before it's placed into "next game" category, after the game, more info (results, comentaries) is added and placed in Season 2015.

The stream has the disadvantage that post's diaspear in the vast sea of "long time ago". Whenever a friends post turns out to have an interesting conversation, we can stare it or save into folders. Being able to sort it into categories would be a realy good option to get some order into the activity. This would turn a forum page more into the realm of classical forums like phpBB which creates actually a category tree where people post into, or post's are moved around.

This is not about federation of the categories, all the contrary. This is for the abillity to sort info by your own criteria for you and your visitors, may those be  friendicans or not.

**Comment by TupambaeNet** [comment]
Here is an example for to explain the request.
A forum page is used to sort standard information that users like to share.
In this case the idea is to create a folder where users can find master public keys of others.
The user post there info to the forum stream, but the forum has to reshare the post to be able to sort into categorys. This creates a lot of "reshare spam" in the stream:
https://tupambae.net/profile/bitcoinfair
https://tupambae.net/profile/bitcoinfair?f=&category=MasterPublicKeys

**Comment by tobiasd** [comment]
So, why not tak the postings as twith the forum account with "MasterPublicKeys". This would then generate a shortcut link to the search for that keyword, thus a page collecting all MasterPublicKeys.

**Comment by TupambaeNet** [comment]
You mean a separate MasterPublicKey Profile?

**Comment by tobiasd** [comment]
No, you have a forum that is used to share (among other things) these keys--right?

So that forum is basically an account that can act as any other account, post stuff etc. So you can use the forum account to add the tag (if missing) MasterPublicKey which will be shown below the posting you applied it to as #MasterPublicKey. Tags are a shortcut to the search for the tag on the node of the user who set the tag. So in this case, the node of the forum account.

**Comment by TupambaeNet** [comment]
The idea is to be able to create moderated forums, moderated content. Basicaly our forums culture is selfmoderated, that's a blessing! But if we could organize their content better, by being able to sort incoming info into categories a different set of options come into place. The helpers forum right now for example is a kind of social stream with reapeatig questions that slip down the line. A publicacion send to the forum like "Starting friendica, first steps" could be sorted in the category:
* a - Beginners guide
The a category
* common cuestions
would fill up easily I suppose. The categorys bugs, merged, UI etc. for sure would pop up next.
Propably a integration in permissons for delegating accounts should be implemented too as this way a forum could be attended by several colaborators.

**Comment by tobiasd** [comment]
You can get this by tagging postings. People post what they want and the forum "moderator", i.e. all who have the possibility to act in the name of the forum, can tag the postings with the correct keywords.

For long lasting docs, there is /doc in the repository which is reachable on every friendica node as /help that can even be translated.

**Comment by annando** [comment]
Is this more a feature request or support? If it is considered the latter one, I suggest closing it.
