### ISSUE TITLE
avatar federation of comments in forum pages are not displayed on diaspora

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1580]
Some answers in discussions on forum pages are displayed with the forum avatar on diaspora. This makes it virtually impossible to comunicate from diaspora to those conversations.
https://pod.geraspora.de/posts/3639770
Reference: #1572 #1572

**Comment by annando** [comment]
Please watch the situation after the new protocol implementation is active.

**Comment by annando** [comment]
We changed a lot here. This is not an issue anymore.
