### ISSUE TITLE
comment federation on forums from diaspora

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1581]
Somehow not all answers into a forum post are displayed in the forum itself and there for i suppose not federated to forum members that maybe aren't on the same pod/node.

https://tupambae.net/display/4d7c841513552f1d48129b4702228837
https://pod.geraspora.de/posts/3506333
Reference: #1572 #1581

**Comment by annando** [comment]
We had improved the forum functionality with Diaspora in some of the last versions. I don't think that this is an issue anymore.
