### ISSUE TITLE
gif images upload broken

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1582]
Since 3.3 gif images are uploaded as jpg. Also old uploaded gif images don't work.

**Comment by fabrixxm** [comment]
have you installed and enabled php5-imagick ?
Animated gif upload [works for me](https://kirgroup.com/photos/fabrixxm/image/74462785410a4237aaf2947c2409a1bd)

**Comment by TupambaeNet** [comment]
I suppose php5-imagick is hosting site setting, can't remember to have seen it in the backend.
I will ask the provider.

**Comment by fabrixxm** [comment]
you can check if is installed creating a new file in your server, name it `myinfo.php` and add this content
```php
<?php
  phpinfo();
?>
```

Call it from the browser and search for "imagick"

**Comment by TupambaeNet** [comment]
Doesn't work :(
https://tupambae.net/myinfo.php

**Comment by fabrixxm** [comment]
try this
```php
<?php
if (class_exists('Imagick')){
    echo "Imagick extension installed";
} else {
    echo "Imagick extension NOT installed";
}
```

**Comment by TupambaeNet** [comment]
thx for the help, it wasn't activated, now it is and gif images are "recovering"
