### ISSUE TITLE
request - language selector for profile display

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1583]
I't would be nice to have a language setting in the profile that defines standard language displayed to visitors.

**Comment by fabrixxm** [comment]
That would change only static labels, but not user-inserted text.
(and btw, the page should be displayed already in language based on visitor's browser settings)

**Comment by TupambaeNet** [comment]
Setting to visitors browser languages is for sure the correct way. I understud that if no settings are found, system falls back to english. I think it would be reasonable at least for the user as whenever he logs in he get's his predefined language. Not a mayor issue, maybe I recon it because of several different language instalation on my systems.
