### ISSUE TITLE
Social Network Setting

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#1589]
On my installation the *Settings -> Social Network* dont work. If I try to activate it, these notification appears: 

    An internal server error occurred. Please try again later.

When I disabel the "Diaspora Post Connector" or I dont use it in the account, the "Social Network" setting works fine, so I think there is a problem with the connector.

**Comment by annando** [comment]
I guess this correlates with issue https://github.com/friendica/friendica/issues/1576

**Comment by atasingorneq** [comment]
Yes, the problem appears after the update of despora.de

**Comment by annando** [comment]
For this reason I would like to close this issue. Do you agree?

**Comment by atasingorneq** [comment]
Yes, of course.
