### ISSUE TITLE
Would this be a way to make Friendica more popular?

### ISSUE THREAD

**Issue by gavinbask** [friendica/friendica#1591]
Hi,  I'm not a developer or programmer, just an avid Friendica user and part time graphic designer.  I have set up a Friendica site and I love it (https://twork.com.au/profile/gav), but I'm having a tough time convincing others to join and get involved. The main barriers are ease of use and obvioulsy the lack of users. 

What I'm wondering about is if there is any way to replicate the framework used by companies like Weebly and Wix to make Friendica easier to setup and manage for new users. 

I started using Weebly a while back when I got sick of using HTML and CSS to update my websites and when mobile devices become more common. Their drag and drop interface cuts hours off the time spent maintaining my websites. When you create a site on Weebly or Wix it gets it's own domain and I assume it's own virtual server. It also gives the user an easy to use drag and drop design editor. As Weebly is CSS based and so is Friendica, I'm wondering if this would be a way to make Friendica more attractive to new users. By having the base coding already installed and working, the user would get their own site and they'd get to customise the look of their site and add the features they want easily. As users still have to pay for a webserver to set up Friendica anyway there's the potential for an ISP or webhost to integrate 'ready-to-go' Friendica sites to onsell to users. Essentially it's selling pre-set-up and customisable Friendica sites. Plug and Play. 

Alternatively, would it be worth approaching Weebly ofr Wix with the idea? They may be attracted to the idea of getting more users and creating a new wave of social media. Because Friendica is intriniscally decentralised and users retain control of thier privacy, the risk of corporatisation is reduced (I assme). 

I have no vested or financial interest in this idea. I just thought it might work, but I don't personally have the technical know-how to pursue it. I'm happy for anyone to run with the idea as I just want to see Friendica succeed. 

As a graphic designer I'm happy to help out in whatever way I can to assist with the future of Friendica.  My coding and programming knowledge is a bit limited, but I grasp the basic principles and can create good looking graphics, logos, buttons etc if needed. 

All the best.

**Comment by redmatrix** [comment]
We're actually doing something like this with redmatrix, which is more of a decentralised CMS than a social network. We're not quite there with drag and drop but that's the direction we're going - and one of our members is trying to work this into a commercial hosting business so anybody can build community and social websites for any purpose and which all link together; as easily as setting up a blog.

**Comment by gavinbask** [comment]
Awesome! That's really good to know. I've played a bit with Red Matrix and look forward to seeing it evolve. I'll keep an eye on it. And sorry to suggest something already in development. I should have known someone would be on top of it.

**Comment by fabrixxm** [comment]
I'm closing this because not really relevant with Friendica :-)
