### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1594]
395mb photo table

184mb  item table

it's very slow.

You can not put the pictures on the web server.

link > http://friendica.mamalibre.com.ar/display/a5cfe07236555ff88253592087279600

**Comment by annando** [comment]
Please check your server settings. Friendica can handle much larger database sizes. The item table of my main system for example has a size of 9gb. Please check things like the slow query log. Have a look at the resources of your system with "top" or "htop". If you haven't enough RAM then systems can react very slowly.

**Comment by mama21mama** [comment]
change it to this
$a->config['system']['huburl'] = '[internal]';

I think now going faster.

**Comment by annando** [comment]
This setting does not affect the performance. I guess you have server problems.

**Comment by michaelmd** [comment]
depends on the server 

on my vps 395mb photo table and 184mb item table would be no problem but anything using mysql on that vps will becomes slow when there 1000000+ items in a table

but it probably depends on the server ...

btw if you are using innodb and its a vps you might have problems with smaller tables
(innodb needs more ram and virtualisation doesn't seem to play nice with it)
if there isn't much ram and its a vps you might be better with myISAM 
(despite the locking)
I found that that (when using myISAM) putting tiny usleeps where it writes can reduce the problem of page timeouts when poller runs.
 (when there's a lot of inserts locking the table for long periods - the usleeps just give it a small amount of time so other queries can still happen) - probably not something that can be put in the distribution (would vary for different servers) and people hosting on realy hardware or faster servers don't need it.

also maybe check caching related headers  are handled properly (a page can have a lot off images on it and if the browsers aren't caching them properly that would mean a lot of requests

**Comment by annando** [comment]
Can we close this issue?
