### ISSUE TITLE
Allow numbers as first digit of nicknames

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1604]
Right now the restrictions for nicknames allow from their caracteristics to use litecoin wallet addresses as a name, as they start with a letter.
It would be perfect if we could use also bitcoin addresses and multisig addresses (in bitcoin and litecoin they start with the digit 3).
Example: https://tupambae.org/profile/ltjus1lpwal8nymfqattzuh13ysjuzyhsc
This way it is possible to relate directly a wallet ID (address) with a social web address for to communicate with. The wallet owner will be able to proof at any time by signed messages that he (still) represents the respective wallet. The cryptocurrency world has a lot of influence from the anonymous "darkcoin" web. At the same time creating a "web of trust" has a lot to do with having unique profiles. A "feature" like this could call attention in the cryptocurrency community, the cryptocurrency  technology itself shares the same views on decentralization and privacy so I think it's a proper proposal.

**Comment by strk** [comment]
I think unique profiles are already guaranteed by the identity schema.
Relating such unique profile to any kind of information (including bitcoin/litecon wallets) can already be done via profile info, I don't see a need to embed such related info into the nickname.

my 2 cents...

**Comment by strk** [comment]
See also #1488 for a proposal to give a structure to e-coin addresses in prifiles

**Comment by fabrixxm** [comment]
as there are no technical issues with a nickname starting with a number, I don't see any problems to allow it.

**Comment by redmatrix** [comment]
This was originally to provide the ability to interchange the uid and nickname in various modules and so we didn't get into the same situation as statusnet where one could have both a name and a uid and only one would work (always a different one). If we encountered a number,intval($x) we would lok up by uid, else lookup by name. Anyway that's why the rule exists. I don't think we still use it any place.

**Comment by TupambaeNet** [comment]
If there aren't mayor reasons to skip the restriction it would be nice to have that opportunity. This might enhance the possibility to create an addon to recover passwords or register with the signing message capability of wallets as an option to email. If a password is lost, a message could be displayed, answering with the the correct wallet signiture creates access to the profile. Also it would be possible for servers to allow only the creation of profiles if the wallet contains certain amount of coins, this way it could provide a tool for to prevent creation of spam accounts or some kind of payment methodology to fund server expenses.

**Comment by tobiasd** [comment]
The restriction on the username was dropped. So I'm closing this issue..

**Comment by TupambaeNet** [comment]
Thx! tobiasd :)
