### ISSUE TITLE
Integration of crypto currency fields into profile

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1606]
Wallet addresses of cryptocurrencys are becoming more and more a standard detail of profiles. For now there is no real "best place" to locate them. I tried several options to ingrate addresses in profiles but nothing really fits the needs.
Here an example:
[Tupambae.net Profile](https://tupambae.net/profile/tupambaenet/?tab=profile)

The e-coin addresses in the location field are displayed, as a means of recognizing that the profile has wallets, but the addresses are way to long and basically it is not necessary to see the direction itself. An icon that indicates a wallet address with a link to the address at some blockchain site would be a possibility.

I suppose best would be a new content category in the profile editor containing fields for those data. Most likely it will make no sense in predefine coin addresses except bitcoin/litecoin/namecoin in any case other standard currencys could call the attention like from "the vibrant" dogecoin community.

An 4 digit field for currency code and a field for the wallet address, maybe a currency name field would be enough. Relating buttons to the currency field should do the job for most "established" currencys.
An optional profile update post when changing properties would be neat also.

---

edited: I deleted some lines that where addressed and solved already in a different issue #1610
reference: #1608

**Comment by MrPetovan** [comment]
Duplicated by #1488

**Comment by annando** [comment]
I'm more a fan of "less is more". Means: We shouldn't add masses of new profile fields. This data can easily be added in profile text.

I would vote for "won't fix".

**Comment by MrPetovan** [comment]
I like the Mastodon approach with user-defined profile fields but it's another can of worm. I'm with you.
