### ISSUE TITLE
Profile bbcode is not displayed under avatar

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1607]
When using bbcode in the profile field __about:__ the bbcode tags are displayed under the avatar instead of the respective layout.
Theme related?
Used theme vier.
https://tupambae.net/profile/tupambaenet/?tab=profile

**Comment by tobiasd** [comment]
which bbcode tags? because I'm using [b] in my about text to emphasise some parts.

**Comment by TupambaeNet** [comment]
at least in the link there are [b] [img] and [url]

**Comment by tobiasd** [comment]
Oh there, now I see what you mean. The vier theme shows the information in the aside panel as well, other themes don't do this and in the usual about section of your profile those tags are honoured. So this is a theme issue and I'll ping @annando for it.

**Comment by tobiasd** [comment]
fixed in 3.4.3-rc branch
