### ISSUE TITLE
Profile information contact and social networks

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1608]
Basically we have no special fields for standard web contact information like XMPP address, twitter, gnusocial or other social network profiles. At the same time some or most of the directions could trigger an event like visiting the gnusocial/twitter profile or opening a communication device like pidgin or TOX. I think I've seen in the gnusocial profile a layout where web addresses are if possible related to the website displayed, otherwise it's just a website image with the respective link. Most addresses are long and it's unnecessary to display the text.
We should probably discus which sites and technology should figure predefined:
- XMPP
- TOX
- diaspora
- redmatrix
- gnusocial
- wordpress
- Skype (i suppose that there isopposition because of centralized MS propiatarian software but lots of people use it)
- googlehangouts
- google+
- twitter
- youtube-channel
- tumblr
- fb

**Comment by n4rky** [comment]
Quoting TupambaeNet <notifications@github.com>:

> Basically we have no special fields for standard web contact  
> information like XMPP address, twitter, gnusocial or other social  
> network profiles.

This information can be added to one's profile already. What is the  
functional advantage to creating special fields for it?
-- 
David Benfell <benfell@parts-unknown.org>

**Comment by TupambaeNet** [comment]
First of all it's the space and also faster information.
With four-five-six buttons you cover the same space than with one web address like https://twitter.com/TupambaeOrg. This is data which has few daily use, if you are interested in it you will contact at the respective services or bookmark his homepage. The fact that he has a homepage, a XMPP address or what ever is expressed by the respective button, who really needs that info has access to it by a click on it, for the rest it's like a general overview on the users web activities. Actually I suppose that 80% of the people in the internet when they see "XMPP jesuisatire@jabber.ccc.de" think _"oh he has an email address mayb I should try this xmpp provider next time for my own email account .." . Just look at the TOX addresses, they look like a string of an endless, useless, encrypted snake kind of accesoir real geeks wear like medals .. in their profiles :-O

**Comment by fabrixxm** [comment]
Problem is: we always leave out the service one user use, and may services don't have any protocol to link directly, eg Tox.
In profile there is a textarea and support for bbcode so you can make it almost as you like:

`[url=https://twitter.com/TupambaeOrg][img]path to icon[/img][/url]`

My xmpp service give me an url which returns an image with my online status, and I like to have it along my jabber address. I could not this with a fixed field :-)

And btw, If someone see "XMPP: user@server.com" and think "he has an email", if he sees ![apps-jabber-icon](https://cloud.githubusercontent.com/assets/309361/7801138/671c0f7c-0320-11e5-9053-7a093df24728.png) what he would think? "Oh, he as a lightbulb!" :-P

**Comment by fabrixxm** [comment]
Anyway, if someone want to implement this (and maintain it :-) ) , we surely will not reject the pull request :-) :-)

**Comment by TupambaeNet** [comment]
We could use a phone as image .. added to some xmpp logo ..

On one hand we have the issue of whom to promote by adding special fields and also there should be some privacy aware info that over this "metadata" people might be traceable or identifiable. The bbcode "trick" is of course a possibility, and part of the solution. To diaspora right now there are already bad displayed bbcodes in profile info, but this is not about minor bugs, but general considerations.
Since years we have the discussion on XMPP integration, missing chat possibilities and so on. How difficult would it have been to add at least a xmpp profile field to all platforms to promote decentralized communication options?

I think we should look for a social web contact field that combine both.
Predefined fields:
* XMPP
* TOX
* diaspora
* redmatrix
* gnusocial
* wordpress
* webpages  
for witch other federated platforms can look for.

Also it's reasonable to consider fields for addon connectors like:
* twitter
* tumblr

A second field like now with some example text for the bbcode use like @fabrixxm mentions would do the rest to be able to display all the other info.

**Comment by TupambaeNet** [comment]
Here an example from a phpBB forum to show the idea. Certain info is available for registered users (friends) other for public access, ideal would be to have this optional for every field public/friends.

Public Profile
![public-profile](https://cloud.githubusercontent.com/assets/1240367/7802072/2b2747c2-0305-11e5-9425-fdc0a3f7da3d.png)


Friends Profile
![profile-friends](https://cloud.githubusercontent.com/assets/1240367/7802065/12f24440-0305-11e5-8edc-27e2da3afb87.png)

**Comment by AlfredSK** [comment]
Is this still an issue? I checked my profile. We still have a fixed XMPP field. Does it make sense to add more communication/contact fields since we have the custom fields now? Is this a 'won't fix'?

**Comment by MrPetovan** [comment]
Closed as invalid by #8156
