### ISSUE TITLE
bbcode display of class=type-link

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1612]
In some kind of post, using class=type-link the display on the post becomes strange. Text that is posted before [class=type-link] is displayed inside the bbcode text field in the post. Something similar is happening when youtube videos are posted with the complete web direction, in particular if two videos are posted one after another.
Example text:
Also works for friendica!
be sure to add https:// to the friendica domain name.
[class=type-link][bookmark=https://addons.mozilla.org/es/firefox/addon/diaspora-advanced-sharer/]diaspora* Advanced Sharer[/bookmark][quote]Puntuado con 4 de 5 estrellas A button to share on diaspora\* via diaspora\* Advanced Sharer ( http://sharetodiaspora.github.com/about/ ). Este complemento no es compatible con tu versión de Firefox por lo siguiente: Share current page easily to the diaspora\* social network - works for any pod! Uses diaspora\* Advanced Sharer as a sharing service.[/quote][/class]

Post display:
https://tupambae.net/display/4d7c8415125563b0a335b2f732363286

**Comment by annando** [comment]
I do not see the problem? The link looks okay for me.

**Comment by TupambaeNet** [comment]
The text:
_"Also works for friendica!
be sure to add https:// to the friendica domain name."_
is published inside the [class field] text, same happens if text is added after [/class], the text is displayed inside the text field at the bottom.

**Comment by fabrixxm** [comment]
The link looks okay also for me... the text you added is show between post title and oembed markup.

**Comment by annando** [comment]
Please provide a screenshot. Maybe it's a display problem on your system (browser problem, font problem, ...)

**Comment by fabrixxm** [comment]
I think I found it. `<span class="type-link">` isn't closed properly

**Comment by TupambaeNet** [comment]
Does this mean I should close this issue fabrixxm?

**Comment by annando** [comment]
If it's working for you?

**Comment by tobiasd** [comment]
can you check if this is now woring @TupambaeNet ?

**Comment by annando** [comment]
I think we can close the issue. Does anyone disagree?

**Comment by tobiasd** [comment]
closed as nobody disagreed
