### ISSUE TITLE
Generate encryption keys??

### ISSUE THREAD

**Issue by mogcabul** [friendica/friendica#1614]
im trying to set up this script on my server, but i get 2 red lights. 
The SSL files are enables, and in the locations form the php web site i checked, but still get the redlight on these errors. 0.o
you can View them here: http://www.skalliance.net/index.php?q=install

How do i correct this?

**Comment by fabrixxm** [comment]
can you try to change [mod/install.php, from line 377 to 380](https://github.com/fabrixxm/friendica/blob/master/mod/install.php#L377-L380)
to this:
```php
    if(! $res) {
        $help .= t('Error: the "openssl_pkey_new" function on this system is not able to generate encryption keys'). EOL;
        $help .= t('If running under Windows, please see "http://www.php.net/manual/en/openssl.installation.php".');
        $help .= "<hr>";
        while (($e = openssl_error_string()) !== false) { 
            $help .= $e . EOL;
        }
    }
```

**Comment by annando** [comment]
@mogcabul How is the current status?

**Comment by mogcabul** [comment]
sorry for the late reply.  after modding this code i get this error:

Parse error: syntax error, unexpected end of file in C:\xampp\htdocs\mod\install.php on line 539

i look at 539, and there is nothing there, its blank???

**Comment by mogcabul** [comment]
when attempting to register a new user i now get this: 

SERIOUS ERROR: Generation of security keys failed.

**Comment by fabrixxm** [comment]
You should re-run install procedure and report again results of initial tests.
The lines you added should print detailed error on why key generation fail.

If you already completed the install procedure, you can rename the .htconfig.php file.
If that file is not found, the install procedure is triggered.

**Comment by silke** [comment]
Not enough information to work in this. If the problem persists or reappears, please reopen this issue, provide information on the server you are installing Friendica on, the Friendica version you are trying to install.
