### ISSUE TITLE
block local directory for public access

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1615]
since I'm not sure if https://github.com/friendica/friendica/issues/1361 is doable in a an easy way, I think from the other side and would love to have an option to block the local directory for public access.

My main concern:
No one needs to know which people are signed up to my friendica node

Explanation:
I'm the admin of a friendica node which we use for communication for friends who know each other away from keyboard. To see who signed up to friendica they all published their profile on the local site directory. Some also published their profile to the worldwide directory but some didn't because they don't want to be found by anyone else than the trusted members from the local friendica node.
Apart from the possibility to get found from anyone with the help of the the local directory there is another issue.
If your node have a name with a clear meaning (e.g. a special topic, an institution, ideology) and maybe no public registration you could connect this meaning to the people of the local dir.
To give an fictitious example. Not everybody on http://friendica.greenpeace.com (or http://friendica.porn.com) wants that everybody from the outside knows that he/she is active for greenpeace (or is interested in porn).

The present state with the "Block public" option contain some restriction, which are not always desirable. The main restriction of "Block public" is that no one from the outside can send connect requests or private mails.

**Comment by annando** [comment]
I guess this is only one half of the work. Please check if the accounts are still visible via /poco/

**Comment by tobiasd** [comment]
Isn't POCO more in the scope of the user choice to hide their profile and not in the scope of the admin to hide the local directory?

**Comment by rabuzarus** [comment]
@tobiasd Yes, I agree. The best way would be to have an option in the user settings to show the profile in the local directory only to users of their own friendica instance. But I've no clue how to implement this.
At the present state I've enabled 'block_public' but this means that no one from another friendica instance can connect to people from our friendica instance. For unknown people there is also no possibility to send them private mails.

@annando 
Yesterday I've made some tests with /poco/
- nickname and '[at]all'' allows access to the local directory
- '[at]me', '[at]self' and '$cid' allows access to the profile of the user
- '[at]global' give some of the contacts

can I block the whole poco_init if 'block_local_dir' is enabled or is it better to block only /poco/nickname, '[at]all', and maybe '[at]global'?

**Comment by fabrixxm** [comment]
but "block_public" don't block communications. if someone on external server know that there a user on server with "block_public" can connect anyway. I'm right? (I've not tested. a quick search for 'block_public' in repo looks like dfrn isn't blocked)

**Comment by rabuzarus** [comment]
I have tested it yesterday. You will get to the profile page (of course with content blocked and the notification 'public access denied'). After pressing connect you will get message you get a notification that public access is denied and will stay on the profile page

**Comment by rabuzarus** [comment]
Mhhh strange
the connection request from my local test installation (https://SUBDOMAIN.no-ip.biz/friend) to the blocked server directs me to https://friendica.DOMAIN.de/dfrn_request/NICKNAME&addr=68747470733a2f2f6b6f6d6d756e65342e6e6f2d69702e62697a2f667269656e642f70726f66696c652f747265626f72
This is the profile page and the notification 'public access denied' appears

If I try it from my local netbeans instance it directs me to https://192.168.1.145/friendica/follow?url=NICKNAME%40friendica.DOMAIN.de&submit=Verbinden

The last one works.
Strange. Maybe a wrong configuration

**Comment by rabuzarus** [comment]
closed. Because of https://github.com/friendica/friendica/pull/1619
