### ISSUE TITLE
User profiles not being pushed to global dir

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1626]
I registered on two sites and finally put up my own node (3.4.0).
None of the users I created appeared on the global directory.
The profile settings ask to publish the profile to the global directory, and the url to submit is the default one in current git repo.

Cronjob is up, but I also run the poller manually in case it needed to do something.

Is this normal ? How can I further debug this ?
The "queue" table in the database is empty.

**Comment by redmatrix** [comment]
The global directory is running on a shared host on my personal account (shared with all of my redmatrix servers and several others) - and jobs occasionally get killed by the hosting provider if the load gets too high. The friendica dev team has been trying to provide alternate and better equipped resources, but currently that's where it is. If you save the profile again when the server is less busy it may work. If it fails repeatedly, it may be a recent bug in the code.

**Comment by strk** [comment]
is friendica.eu one of your redmatrix servers ? because 2 friends created accounts there in about the same time and go correctly registered. My account registration failed from myfriendica.net, friendika.openmindspace.org and my own node (I tried again).

Are logs supposed to contain traces of registration attempts ? Because I don't see them...

**Comment by strk** [comment]
Could it have to do with using non-signed https certificate ?

**Comment by strk** [comment]
I just found out that I cannot be found even on my local directory. This one is pretty weird because by omitting the search parameter I do see my _only_ account (from an anonymous browser window), but typing the name and hitting "Find" finds no match !

**Comment by ddorian1** [comment]
Have you checked the options under "Security and Privacy settings" for your account? Maybe you have  accidentally disabled the publication of your profile.

**Comment by strk** [comment]
Both
 ```Publish your default profile in your local site directory?``` and ```Publish your default profile in the global social directory?``` are set to Yes ("Yes" is the visible word in the switch widget).

I verified, with the _local_ directory, that switching to "No" that option removes my profile from the list of profiles shown when no search string is given. But, if I type the first name and hit "find", then nothing is found.

It's like the search engine does not search in my full name (which is instead shown when no string is put in the input widget).

**Comment by strk** [comment]
```Hide your profile details from unknown viewers?``` is set to No

**Comment by fabrixxm** [comment]
@strk you should enable logs and change something like your description (that should trigger an update to global dir)

**Comment by strk** [comment]
Debugging enabled, level "normal" -- changes to profile (basic settings, default post location) do not leave any trace in the log

**Comment by strk** [comment]
Setting "hide your profile from unknown people" also does not change the behavior (nothing logged).
I noticed that the "Basic Settings" form asks for my existing password in order to "confirm the change". I never fill that field in, but on "Save" I do receive visual notification of the changes being accepted (and I do get the new values if I get back to the setting later). Sounds like an usability issue.

**Comment by strk** [comment]
Raising log level to "All" gets me some logs, but only about the poller but nothing is added on profile changes:
```
2015-06-09 10:10:01@	[NORMAL]:poller.php:75:poller_run	poller: start
2015-06-09 10:10:01@	[NORMAL]:ostatus_conversation.php:23:check_conversations	poll interval not reached
2015-06-09 10:10:01@	[NORMAL]:poller.php:296:poller_run	poller: end
2015-06-09 10:10:02@	[NORMAL]:cronhooks.php:57:cronhooks_run	cronhooks: start
2015-06-09 10:10:02@	[NORMAL]:cronhooks.php:63:cronhooks_run	cronhooks: end
2015-06-09 10:10:02@	[NORMAL]:queue.php:113:queue_run	queue: start
2015-06-09 10:10:02@	[NORMAL]:queue.php:8:handle_pubsubhubbub	queue [pubsubhubbub]: start
```

**Comment by tobiasd** [comment]
> I noticed that the "Basic Settings" form asks for my existing password in order to "confirm the change".

You can only change your password if you know the current one. For the other settings the password is not checked.

**Comment by strk** [comment]
So I confirm my profile is still not being added to global dir. The logs reveal that the poller is running, but I dunno what else I should be checking. I confirm both "publish in local" and "publish in global" user setting are set to true. And I confirm I can find my profile on the local dir but not the global one.

Friends of mine, who registered on friendica.eu, are happily getting listed in the global dir.
The directory url in the admin page is set to ``http://dir.friendica.com/submit`` (I think it's the default).
My node url always redirects to https, in case that matters. Should I try switching to https for dir.friendica.com too ?

**Comment by strk** [comment]
FWIW: using https for global dir did not work (no https support over there)

**Comment by redmatrix** [comment]
send me your Friendica url via email - mike at macgirvin dot com and I'll see if I can debug anything on the directory side. Haven't had to look at those logs in years.

**Comment by strk** [comment]
I've just also installed a node on my laptop, straight from develop branch, and the admin account there is also not pushed on global dir (expected ?)

**Comment by strk** [comment]
btw, I did send you an email @redmatrix, please reply if you received it

**Comment by redmatrix** [comment]
Got it - I'm having a look now.

**Comment by redmatrix** [comment]
Very weird - I ran the exact same sequence of steps manually that happens during a submit and it worked just fine and you're showing up in the directory. All I did was hardwire the URL instead of pulling it from the request URL. So this suggests that the directory code is working and for whatever reason the fetch containing the hexified url either wasn't arriving at the directory submit endpoint or there was something wrong with hexifying the url. -- e.g. it's probably on the client side. That's really all I know currently and unfortunately is back in the hands of Friendica developers as the code has changed considerably since I left a few years ago. 

The only thing I can suggest is that due to the way Apache re-writes work we've typically needed a dummy request variable, for instance http://dir.friendica.com/submit?f=&url=xxxxxxxxxx where 'f=' is a throwaway argument to make a legal URL as 'submit' will get re-written to ?q=submit and the request would otherwise contain two '?' args and the second will be discarded and never make it to the code. This was part of the way we did things back when I worked on the project but the dummy variable may have gotten dropped at some point if somebody didn't understand why it was needed.

Otherwise I don't know what went wrong.

**Comment by strk** [comment]
I tried changing the `Global directory update URL` site configuration from `http://dir.friendica.com/submit` to `http://dir.friendica.com/submit?f=issue1626` and updated my profile name. We'll see in ten minutes if anything changes.

Did you look in the web server logs for your service to see what kind of request arrived, if any ?
On my side the client logs are not detailed enough to tell me what URL was tested for submission (Log Level: Debug)

**Comment by strk** [comment]
Nothing changed in the global dir, so changing the `Global directory update URL` to `http://dir.friendica.com/submit?f=issue1626` did not help.

**Comment by strk** [comment]
Reading https://github.com/friendica/friendica/blob/master/include/directory.php#L41 it looks like a log should appear with the string "Updating directory" but no such log is written here, which makes me think that code is not run at all ...

**Comment by strk** [comment]
Actually I can't get to have anything written into the log, even if I call `logger('test')` from index.php -- only traces from poller get written there ?!

**Comment by annando** [comment]
That sounds like a local permission issue. I guess the web processes are running under a different user than the cron job. Please check this. If the users are different, you have to alter the file permissions of the log file so that both users can write into the file.

**Comment by strk** [comment]
@annando good hint, indeed the cron job was running as root. Should be ok to run as the same user as the rest of the website instead, right ? The INSTALL file should maybe mention this

**Comment by strk** [comment]
I just got a new registration (second one, after mine) on my node. Her profile is published on the local dir but not on the global dir. FYI (I've yet to find the time to further debug this).

**Comment by tobiasd** [comment]
But she had chosen to publish it in both directories?

**Comment by strk** [comment]
She didn't choose anything, so the default was used.

Global dir url is now set to:
 http://dir.friendica.com/submit?f=issue1626

**Comment by strk** [comment]
This ticket can be closed, doesn't serve any purpose here.
