### ISSUE TITLE
Register text get wrongly encoded

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1628]
If you put single-ticks in the "Register Text" field in Administration->Site form, the single-tick gets converted to the sequence ```&amp;amp;#039;``` on save (in the input text).

On the registration page, it remains visible as ```&#039;```

This is with beb4980f020e09625357114159a860f64f030004 and both diabook and duepunto themes

**Comment by fabrixxm** [comment]
Register Text is encoded before passed to template ( https://github.com/friendica/friendica/blob/develop/mod/admin.php#L652 ) but template encode all values before put them in html ( https://github.com/friendica/friendica/blob/develop/view/templates/field_input.tpl#L4 )

**Comment by annando** [comment]
Can someone check that this is now working correctly? I would like to close the issue.

**Comment by fabrixxm** [comment]
Checked. Works.Closing
