### ISSUE TITLE
Friend drop confirmation page lacks context

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1629]
The page asking  you for confirmation about dropping a friend does not tell you anything about the friend you're confirming the drop of. It's not very user-friendly as you're asked to take an important decision with no information about it.

All I can see is the contact identifier in the uri, like:
https://myhub/contacts/3/drop?confirm=1

**Comment by fabrixxm** [comment]
I think all supported themes are using ajax based deletion, with javascript alert in page.
(tested with quattro, vier and duepuntozero)
Still, more infos can be shown in that page.

**Comment by annando** [comment]
This is a generic dialogue that is used for many cases (and it is translated in a confusing way in German). This is not a simple text replacement.
