### ISSUE TITLE
AndStatus fails to connect

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1633]
I'm trying to use AndStatus to connect to my friendica node. Added it as a social netowrk of type "pump.io". Then adding new account there, via webfinger, fails with error "no client keys for the host yet; registerClient; URL...http../api/client/register". I went to the reported URL (on my node) and got:
```{"error":"not implemented","request":"api\/client\/register"}```

Is pump.io not supported by friendica ? Or do I have to choose another communication protocol from AndStatus ?

**Comment by tobiasd** [comment]
The friendica API is StatusNet (nowadays GNU social) compatible. So the network type should not be pumpio but StatusNet.

If you have an account on a pumpio server, you can use friendica to communicate to your pumpio contacts over that relay proxy.

**Comment by strk** [comment]
Thanks, I'm in ! :)
