### ISSUE TITLE
Comments order should be backward ?

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1634]
When "infinite threading of items" is disabled you find yourself answering people from right below the original post and far far away from the comment you're answering to. This is because comments are shown in submission order (latest comment lowest in list). Enabling "infinite threading of items" make things better because you can reply right below the comment of interest.

I dunno if it is theme dependent. I'm using "diabook", is it ?

**Comment by annando** [comment]
This is a theme thing.

**Comment by fabrixxm** [comment]
it's a theme thing. and diabook is unsupported. I'm closing this.
But feel free to send patches, if you  want :-)
