### ISSUE TITLE
diabook theme not showing up in Admin->Themes

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1635]
I had "diabook" enabled but don't remember how. In any case from the Admin->Themes page there was NO "diabook" entry, and the existing entries were all disabled. I enabled one of them (duepuntozero) and now I can't get back to "diabook" anymore.

The list of available themes to select from is:
- duepuntozero
- Frost - Version 0.4
- Frost--mobile version - Version 0.3
- Quattro - 0.6
- Smoothly - Version 2013-05-08
- Vier - 1.2

The listing under view/theme is:
```
cleanzero
comix
comix-plain
darkbubble
darkzero
darkzero-NS
decaf-mobile
diabook
dispy
duepuntozero
facepark
frost
frost-mobile
greenzero
purplezero
quattro
slack-NS
slackr
smoothly
testbubble
vier
```

Why the discrepancy between available directories and entries in the Admin panel ?

**Comment by rabuzarus** [comment]
because some themes are marked as unsupported (e.g. diabook). Unsupported means that there is no maintainer for the theme. If you want to enable it, you have to delete the file with the name "unsupported" in the respective theme directory.

**Comment by tobiasd** [comment]
There are some legacy themes that are not supported anymore (the theme devs left the project and nobody else took over). Those themes are marked as unsupported with an empty file with the filename "unsupported" in the directory. They are still in the project tree in case anyone still uses them (so they don't suddenly face another interface) and in case someone wants to take over an get new features into the themes.

The *zero themes are now (almost) all subthemes of duepuntozero.

If you want to revive diabook on your node, just delete the "unsupported" file or rename it to "_unsupported", but be aware that either git may complain in the future or the zip archives will contain this file, so it gets marked again with future updates.

**Comment by strk** [comment]
Thanks for the info! I wonder how it could get enabled initially, as I
hadn't manually removed any file in the beginning. Is there a dynamic update
of some sort ?

**Comment by tobiasd** [comment]
If you used diabook before it was marked as unsupported, you could use it afterwards. The marking just prevents new usage.

**Comment by strk** [comment]
Ok but what does "before" and "after" mean here ?
I'm the administrator of my own node and I did not run any intentional
upgrade. Unless "DB updates" from Admin panel can do such a thing.

**Comment by tobiasd** [comment]
IIRC we deprecated most of those themes after the Hackathon last Summer, since then there were two releases.

**Comment by annando** [comment]
We have two settings in the .htconfig.php:

````
$a->config['system']['show_unsupported_addons'] = true;
$a->config['system']['show_unsupported_themes'] = true;
````

When enabled, all themes and addons are shown, even the unsupported ones.

**Comment by strk** [comment]
I hadn't manually touched .htconfig.php, is there a web GUI for
toggling that value ? (still trying to figure how I could have possibly
enabled it otherwise).

**Comment by annando** [comment]
Changing the .htconfig.php is the only possibility.

**Comment by fabrixxm** [comment]
mmh no, he installed it about a week ago...

**Comment by annando** [comment]
question is: Can we close this issue?

**Comment by strk** [comment]
Doesn't sound worth a further inspection to me, closing.
