### ISSUE TITLE
embedding soundclound not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1640]
Embedding content from soundcloud with the [audio] tag is not working anymore.

Using [audio]soundcloud url[/audio] results in the targeted audio linked, but not the player being embedded. Branch develop, tested with Firefox and Chromium browsers.

**Comment by annando** [comment]
Can we close this issue?

**Comment by tobiasd** [comment]
It works for me again so I'll close this, although the original reporter could not test as he is not running dev code on the node.
