### ISSUE TITLE
{0} in notifications

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1642]
In at least two places the placeholder for names is not replaced within the notification system. I see {0} in notifications via the API for replys and new registrations in the friendica app for Android and the desktop notification system using develop branch.

![friendica_notification](https://cloud.githubusercontent.com/assets/433490/7939629/34a98420-094c-11e5-818e-9e3312e80425.png)

**Comment by tobiasd** [comment]
same for the notification about new private messages with both devices.

**Comment by tobiasd** [comment]
I think part of this, the desktop notification part, needs tobe done in js/main.js around l. 190. The part that was added by @FlxAlbroscheit in #1460. I only assume that this is the place for the missing replacement of {0} by the name though.

**Comment by FlxAlbroscheit** [comment]
Thx for the commit - ping.php has been changed some weeks ago and therefore not each new notification actually starts with "&rarr;"... BTW: I thought about freezing/deleting this feature for now, as the notification-system (mostly ping.php) is not as flexible as it should be...

My plan was to simply implement a variable "htmldesktopnotification" into the table "notify" that is false in the beginning and then changed to true when an AJAX-request (including the notifications-data) has been send => Notification is only shown once... however, after some time of frustration modifying ping.php I decided to leave this feature...

**Comment by annando** [comment]
What should we do with this? The desktop notification has issues. Maybe we should deactivate it until it is fixed? I guess that this "{0}" is only a problem in the notifications?

**Comment by tobiasd** [comment]
The {0} is also a problem in some notifications for the friendica android app. I would miss the notifications, but as discussed at friendica I'm not able to fix this problem after several tries.

**Comment by tobiasd** [comment]
While I have not seen {0} in notifications in the friendica app for a while now, it has HTML special char encodings in the texts (``erw&auml;nte``.)

**Comment by annando** [comment]
In the app everything now seems to work fine. Can we close the issue?

**Comment by tobiasd** [comment]
What about the desktop notifications?

They seem to have stopped working for me. If this was on purpose, the settings should be removed as well.

But the app seems to be fine now yes.

**Comment by annando** [comment]
I haven't changed anything with the desktop notifications.

**Comment by tobiasd** [comment]
mmh for me it stopped working (Firefox 38); the example you linked http://jsbin.com/notification/1/edit?html,output is still working.

**Comment by annando** [comment]
@fabrixxm What do you think? Should we hide the notifications for the release? I would suggest that we wait for my OStatus fix. When this is done (hopefully until Friday) then could do the freeze. If you have a working desktop notification to this date, it would be fine. Otherwise we maybe should hide the setting, so that we could work on it in the next developer branch?

**Comment by fabrixxm** [comment]
If I don't get them working before Friday, I'll do a request to remove the setting...

**Comment by fabrixxm** [comment]
new pull request #1692

**Comment by annando** [comment]
@tobiasd Is it now working for you?

**Comment by tobiasd** [comment]
desktop notification only work in chromium. In Firefox the options are there and when activating it the browser asks if I allow this, but afterwards the notifications are not shown. Notifications in the friendica app work fine.

**Comment by fabrixxm** [comment]
on Firefox works, sometimes.
I tested it and worked, then stopped to work, then started again, then stopped again. Without any useful error message or any change to the code.

**Comment by tobiasd** [comment]
/o\ so I think *this* issue is fixed but the Firefox one deserves another one.
