### ISSUE TITLE
No email need on first install

### ISSUE THREAD

**Issue by jonaysanz** [friendica/friendica#1651]
There are some friendica installations made to test in a local webserver. So, it doesn't have email server, but on installation, admin password is sended by mail. 
So need to hack the mysql database to access it.

A request could be that if there's an error sending the email (cause email server isn't found) allow to set manually the password

**Comment by annando** [comment]
I have another request of someone who wants to use a previously defined password. I'm thinking about something like a special config file for the installation that contains username, mail address and password. (and that is deleted afterwards). What do you think?

**Comment by TupambaeNet** [comment]
Sounds good.

**Comment by ben-utzer** [comment]
Wouldn't it be easier to show the password during the installation and mail it to the admin? So if mail will not work you can write it down and that's it.

**Comment by annando** [comment]
In the development branch there is new code that allows entering a password during the creation of the first account: https://github.com/friendica/friendica/pull/1722

**Comment by tobiasd** [comment]
this is in master now (v 3.4.1) so we can close this issue right?

**Comment by annando** [comment]
I would say yes.
