### ISSUE TITLE
Mention Users

### ISSUE THREAD

**Issue by jonaysanz** [friendica/friendica#1652]
On a photo, status or comment could be nice to be able to mention your friends to get referenced

**Comment by fabrixxm** [comment]
can't we already? I'm missing something?

**Comment by ben-utzer** [comment]
Well I can mention them, just type @$Name and it will show a list below the message entry field, but maybe there is java script problem, guessing it is done with js?!

**Comment by vinzv** [comment]
Can't see the problem here. Therefore maybe close this issue?

**Comment by MrPetovan** [comment]
Agreed.
