### ISSUE TITLE
Search in local directory don't work as expected

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#1657]
I can't find my user (fabrixxm) with
- fab
- fabr
- fabri
- fabrix
- fabrixx

but with fabrixxm it works.
Other users are found with partial usernames 

(see #1626 )

**Comment by annando** [comment]
The query is incorrect. A "MATCH" query doesn't work with mixed tables, see: http://stackoverflow.com/questions/2610812/mysql-full-text-search-why-am-i-getting-incorrect-arguments-to-match

Additionally the fields don't support the full text search. So we have to rewrite the whole query.
