### ISSUE TITLE
Subscribing to GNUSocial groups does not work

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1666]
I tried passing my identity to the form here:
http://oracle.skilledtests.com/main/ostatus/group/fediverse

But it failed with: 
Unable to find services for xxx@friendica.xxx.net.

May be the same (or similar) issue then #1665 but I hadn't found a similar workaround to test (subscribe to remote group from friendica node?)

**Comment by strk** [comment]
\cc @Erkan-Yilmaz

**Comment by annando** [comment]
Groups aren't supported by now. But they really should be.

**Comment by vinzv** [comment]
Given the constant decline of GNU Social: is this still relevant and worth the efforts?
I don't think so and would close the issue.

**Comment by annando** [comment]
I think so as well. Does anyone disagree?

**Comment by MrPetovan** [comment]
Nope.
