### ISSUE TITLE
Error (php memory_limit) when trying to install

### ISSUE THREAD

**Issue by abixadamj** [friendica/friendica#1675]
I have my own hosting server and I want to set up Friendica.

I have got git clone, and modyfi .htconfig.php with localhost as host name, user, db, password....

When I try to run http://friendica.info.pl (to complete installation), nothing happens (white screen). In logs there is error:

[Fri Jun 19 13:20:43 2015] [error] [client 188.146.85.208] PHP Fatal error:  Allowed memory size of 1585446912 bytes exhausted (tried to allocate 130968 bytes) in /var/www/clients/client4/web32/web/include/config.php on line 700

[Fri Jun 19 13:27:25 2015] [error] [client 188.146.85.208] PHP Fatal error:  Allowed memory size of 1585446912 bytes exhausted (tried to allocate 130968 bytes) in /var/www/clients/client4/web32/web/include/config.php on line 700

Browser waits about 40 seconds with "Waiting for..." message, and after that I can see error.log.

In php.ini I set to be sure:
memory_limit = 1512 MB 
(YES, 1 ,5 GB...)

Can anyone help me?

**Comment by fabrixxm** [comment]
[include/config.php](https://github.com/friendica/friendica/blob/master/include/config.php) has 341 lines.

How you managed to get an error on line 700? :-)

**Comment by abixadamj** [comment]
I don't know.... It is 341 lines log on my server in fact.
I don't have ANY idea..... Do you?

**Comment by redmatrix** [comment]
We've seen this problem many times at installaton and has usually been found to be a DB connection issue which results in this. When trying to log the issue it makes a DB call to get the log configuration and it loops on itself since the database isn't opened yet. We've tried to prevent this in numerous ways but none of them have been 100% successful. There may be other reasons, but please double check all of the DB connection credentials and verify they connect with the DB.

**Comment by abixadamj** [comment]
Now I see : "Apologies but this site is unavailable at the moment. Please try again later."

in .htconfig I have:

$db_host = 'friendica.info.pl';
$db_user = 'my_user';
$db_pass = '**************';
$db_data = 'my_database';

I'am 100% sure, that db_conn is ok, I have just generated new SQL user password.

In log there is only:
188.146.76.161 - - [22/Jun/2015:11:24:49 +0200] "GET / HTTP/1.1" 200 407 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36"

When I have changed line
$db_host = 'friendica.info.pl';
to
$db_host = 'localhost';
I have empty page and in error.log:
Mon Jun 22 11:26:30.914653 2015] [core:notice] [pid 1503] AH00051: child pid 11
094 exit signal Segmentation fault (11), possible coredump in /etc/apache2

Of course there is no coredump in /etc/apache2, but I think that with 'localhost' there is php memory_limit error. So, nex question - why there is info about site unavaible?

**Comment by fabrixxm** [comment]
> So, nex question - why there is info about site unavaible?
because it can't connect to the database server, or it can connect but can't select the database.
Have you been through the install procedure?

**Comment by abixadamj** [comment]
No, I just edit .htconfig.php and go to http://friendica.info.pl - that is all I have done. I don't know, what else coud I do? 2 years ago I had my firendica instnace and then everything was ok.

**Comment by fabrixxm** [comment]
Remove `.htconfig.php` , go to http://friendica.info.pl and follow the instructions

**Comment by fabrixxm** [comment]
for reference: https://github.com/friendica/friendica/blob/master/doc/Install.md

**Comment by abixadamj** [comment]
OK, thanks, now it is working. For everyone else... always READ carrefully instructions... there is statement:
"create an empty file called .htconfig.php and make it writable by the web server"
This is very important!!! EMPTY FILE ;-)
Thanks a lot for your patients and help. See you in Friendica network.
