### ISSUE TITLE
UX: show profile connect button only if you are logged in

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1700]
At the present state the connect button appears if someone visit your friendica profile page (it doesn't appear if you are logged in and already connected). So the connect button also appears for users which have no friendica account.
If someone isn't logged in friendica his/her friendica account the connect button shouldn't appear.

**Comment by tobiasd** [comment]
Why? The button then leads to the contact request form where you then fill out your profile url manually so you can initiate the process even if you have not reached the profile over a magic link.

**Comment by rabuzarus** [comment]
To get a strengthen feeling to be a member of a network/platform. This means that there is an inside (member - logged in user) and and outside (just a visitor).  Outside means that if your have no friendica account (or you are not logged in) there should no possibility to connect with someone.
Why should you want to connect with someone if you don't have any friendica account?

Maybe it's possible to set a cookie which tells if a user is logged in friendica. If so the connect button becomes visible.

**Comment by fabrixxm** [comment]
We can't do it.
You can't be authenticated on a remote server without being in conctact with the user.
You aren't authenticated as "john on example.com", but as "john on example.com, contact of mark on this server"

Plus: 
- only friendica can do remote auth, any other can't: diaspora users can't, ostatus users can't, so they will never view the conect button
- it's a way to show to unaware users that that is not a simple blog, but it's more

**Comment by tobiasd** [comment]
Now after visiting the page after a long time I had not used it; I was thinking that there maybe should also be a link to the atom feed of the postings and one for the conversations. That's getting in contact with a profile as well.

**Comment by rabuzarus** [comment]
Since this feature request is not doable I would like to close this issue.
@tobiasd can open a separate  issue?

**Comment by tobiasd** [comment]
#1779 covers that issue I think - so I'll clode this one.
