### ISSUE TITLE
Feature Request: make puplic calendar events visible for visitors

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1701]
At the present state the events page is only visible to the owner (local user) of the callendar.
It would be very useful if there would be a public events page which is visible for everyone.

With this feature a visitor can easily recognize which are the upcoming events of the profile owner. It would make friendica more attractive for organisations (and people) who organize events.

**Comment by tobiasd** [comment]
Just for reference as it partly addresses the issue, there is the ``cal`` addon one can use to export public events to ical links. But I agree it might be nice to have a web view to access the events for visitors of the profile.

**Comment by rabuzarus** [comment]
just as note: https://github.com/redmatrix/hubzilla/commit/c95d7c69eb3135f137390323a09eb105776ce29c

maybe it could be useful at some time

**Comment by tobiasd** [comment]
@rabuzarus this was implemeted right?

**Comment by rabuzarus** [comment]
Oh yes I was the one who implemented this
