### ISSUE TITLE
Allow nodes to be configured to render location using openstreetmap

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1705]
It isn't nice for a free software federated social software to rely on a proprietary SaaS to render locations. It would be better to use the community powered opendata providing crowdsourced planet map instead: http://www.openstreetmap.org

It should likely be the default, eventually with node configuration allowing for changing it.

**Comment by fabrixxm** [comment]
There is an addon "openstreetmap". And I think is the only one that currently supports [map] tag...

**Comment by strk** [comment]
I hadn't looked into the plugin, but this PR makes OSM the default (deserved).
Tested locally with both browser-enabled location sharing and manually entered locations.
I hope this can make it into the upcoming release :)

**Comment by strk** [comment]
Oh, the PR, in case it isn't automatically notified: #1706

**Comment by fabrixxm** [comment]
At this point, I would better leave out any default and leave the work to addons

**Comment by fabrixxm** [comment]
Or move "opestreetmap" addon functionality into core

**Comment by strk** [comment]
your call, I'm not confident enough about core to tell what's the best option.
For sure I didn't like being sent to google from my liberated node :)

**Comment by strk** [comment]
I've just enabled the plugin to take a look and I found it being slightly different than the core behavior.
The core behavior (also used by my PR) is to show both the coordinate _and_ the manually entered location, sending you to two different urls. Also with core both manually entered and coordinates are shown. With the plugin the location text is replaced by "map" ?

**Comment by annando** [comment]
I did two pull requests (one to the addons, one to the core) that removes Google Maps and that adds a "Google Maps" addon. Additionally the output format was unified.

**Comment by strk** [comment]
both merged? Have a link for the one to addons ?

**Comment by tobiasd** [comment]
they are both in the addon repository [OSM](https://github.com/friendica/friendica-addons/tree/master/openstreetmap) and [GM](https://github.com/friendica/friendica-addons/tree/master/googlemaps)

**Comment by strk** [comment]
So, closing. Thanks !
