### ISSUE TITLE
Allow node-wide IRC plugin configuration

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1707]
There's currently no node-wide configuration for the IRC plugin.
I saw it defaults to joining the channel with the name of the third level node domain and only the user can change it (via GUI, at least). It would be nice to allow node administrator to set some defaults (server, channel)

**Comment by tobiasd** [comment]
Yes it is, the settings are only shown for the admin users. But I will add the config dialog to the admin panel as well. Question is, should the normal user be allowed to enter favs in their settings?

**Comment by strk** [comment]
why not ?

**Comment by tobiasd** [comment]
I don't know why not. IIRC this addon was from a time before we had the admin panel and the OA never felt the need of changing things. I've added it now  in the referenced pull request.

**Comment by tobiasd** [comment]
the IRC addon is now updated in the addon reporisoty

**Comment by annando** [comment]
@strk Can you check whether it now behaves like expected?

**Comment by strk** [comment]
I'm logged in as the admin user, but there's no "IRC" section under the "Plugin Features" section of the menu (where "impressum" and "openstreetmap" links are, instead). Where's the system wide IRC plugin configuration ?

**Comment by strk** [comment]
Note this is with addons from https://github.com/friendica/friendica-addons/commit/68129e2d5a69855e3d7fb91f0e7a267cca26caff

**Comment by tobiasd** [comment]
It should be right there. Have you activated the addon? In any case, you can directly call the page at /admin/plugins/irc on your server (you can check it's activated there as well)

**Comment by strk** [comment]
/admin/plugin/irc works, but is the same page you get to when you select "IRC" from the list of plugins. There is no configuration there. Only the ability to "Disable"/"Enable" it, and various links to external resources (among which a link to your email address, @tobiasd, which is malformed as it is taken as an HTTP url, relative to my node...)

**Comment by fabrixxm** [comment]
disable and reenable it.

**Comment by tobiasd** [comment]
Thanks, I've used the wrong format of the author tag m) that should be the webfinger but the URL of the profile there.

**Comment by strk** [comment]
Disable and re-enable works. Is there no support for "upgrades" of plugins ?
The admin configuration now works. Didn't test with a real non-me user as I'm the only user on that node. Will let you know if anything goes wrong. To me this ticket can be closed, Thank You !
