### ISSUE TITLE
Pending connection requests are not shown in GUI

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1708]
There's no way for me to see which invitations I've sent and are thus pending.
As a result I keep inviting the same people and keep receiving the "you already introduced yourself here". Am I missing some tab/page to see that list ?

**Comment by annando** [comment]
I haven't seen such a tab either. But it is a good idea.

**Comment by strk** [comment]
Followup from this situation: my problem was that I sent an invite to a friend who finally revealed he just _ignored_.

Being unable to see my pending invite I started thinking I never invited him and tried to invite him again, but could never do because his server responded "there've already sent an invitation here" or something similar.

So finallyl I removed my invitation from _my_ node database, and now we're stuck with him being unable to accept the previously ignored invote because there's no more pending invote from my side.

Although I know it's all my fault for messing with the database, I somehow think there could have been a more "friendly" handling of this whole process. 

Thinking out loud:

 1) I could have been notified of my invite being "ignored" (my friend node did list my invitation in the ignore lits)
 2) I could have had the option to re-invite (although I do understand it could be a spamming device)

Also I'm thinking, if we don't want to bother the admin of my friend's node (friendica.eu), would it make sense for a user to just _delete_ an invitation, both sent and received ? In this case, if my friend could delete my invitation, I could re-invite him again.

\cc @guglielmo

**Comment by annando** [comment]
AFAIK there is another issue that describes exactly the problem you had. We really have to dig into this process. There is a need to redo a connection request. This will be interesting, since there can occur several situations.

**Comment by strk** [comment]
Hey, this is still an issue with current version. Just an heads up.
I invited a friend, neither me nor her has any web UI indication of this ! (she got an email though, so the process was somehow completed). I'm on 2018.09-2420-g5ca279478 and she's on libranet.de not sure which version

**Comment by strk** [comment]
btw: in this case the recipient of my invitation did not actively _ignore_ the invitation, because she just received an email but NOTHING in the UI, so it was some form of accidental "ignorance". BTW, the mail arrived in Spam folder so she didn't even ever see the mail...

**Comment by AlfredSK** [comment]
You should definitely get a system notification about a new contact request. Usually there is a counter on the notifications icon to give a hint about the request. And it should be in .../notifications/intros (the ignored requests too).
When you introduce yourself to another user (sending a contact request) you don't have a menu or page where those pending contact requests are listed, unfortunately.

That being said, you should really update your node. There were _a lot_ of changes in the last 3 releases concerning the process of adding contacts.

> she's on libranet.de not sure which version

Your friend is on Friendica 2019.06-rc.

**Comment by strk** [comment]
My node is fresh:
```
# git describe --tags
2019.04
# git describe 
2018.09-2420-g5ca279478
```

must be the lack of annotated tags

**Comment by MrPetovan** [comment]
What do you mean by "invitation"? Was she on Friendica already? Was it a contact request through the `/follow` page?

There is a separate process to invite people to sign up on Friendica that doesn't involve any notification.

**Comment by strk** [comment]
She was on friendica. With "invitation" I mean an "introduction"

**Comment by MrPetovan** [comment]
Thanks for the clarification. Do you know which theme she is using?

**Comment by strk** [comment]
I don't. @AlfredSK should (it's the default theme for new users). She was using a browser on an Android phone to visit.

**Comment by AlfredSK** [comment]
Default is frio. And yes, notifications on mobile aren't very obvious. You have to look into the main menu (three dots on the right side of the top menu bar) -> Notifications.

**Comment by AlfredSK** [comment]
I think this is fixed since we have .../contact/pending now. Can we close it?
