### ISSUE TITLE
Show number of unread items near each of contact groups

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1718]
When looking at the Network tab, the count of unread items is only shown at the top menu ("Network").
When group filtering is active (Settings->AdditionalFeatures->WidgetsForNetworkSideBar) it is hard to find which group contains the unread items and all you can do is select each group in turn until you find them. Having  a per-group notification area would help with that.

**Comment by strk** [comment]
Just a tip for those who had this problem: enabling "Network New Tab" in Settings->AdditionalFeatures->NetworkTabs makes life much easier (supposedly you can click on the "new" tab to get all the new things, I'm not sure if that's effectively the case or the tab is limited to last 12 hours of activity)

**Comment by strk** [comment]
I gave  a look at the code and it looks like the `/ping` endpoint output should be tweaked to allow for this as it currently only contains a `<net>#</net>` tag with no further information about those # posts.

BTW, the output also contains lots of posts, 3 months back! is that another bug to file ?

**Comment by strk** [comment]
continues in #2048 PR

**Comment by strk** [comment]
And the "quattro" theme implementation is in #2050

**Comment by strk** [comment]
I've been told the "official" theme would be "duepuntozero" so I guess this can only be closed when implemented there (but I'd really like it in "vier" too :)

**Comment by tobiasd** [comment]
for me it seems to work in quattro, duepuntozero and vier as well. You should test it. Maybe it is only my node.

**Comment by strk** [comment]
Yes, it's now working in all the mentioned themes. Closing.
