### ISSUE TITLE
Group filter and New Tab do not play nicely togheter in network page

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1720]
When both "Group Filter" and "New Tab" are enabled under Settings->AdditionalFeatures there's a confusing output where one of the groups is shown as "selected" while you see "new" posts from any group.

They should maybe integrate to be at the same level, like "Grouping of posts".
There could be a hierarchical kind of grouping:
- By contact group
  - contact group1
  - contact group2
- New posts only
- (Posts involving yourself)

**Comment by strk** [comment]
Or, as an alternative, selecting "New" should only show the new posts in the selected category

**Comment by strk** [comment]
This is still an issue as of version 3.4.3

**Comment by rabuzarus** [comment]
It seems, that the whole network filter is a little bit buggy. There should be a more clean url. All filters should display `/network?[filteroptions].

e.g.
filtering by new comment: `/network?order=comment`
filtering by network: `/network?nets=dfrn&`
filtering by cid: `/network?cid=210`
filtering by group: `/network/9` (`/network?guid=9` would be more logical`)
filtering by new: `/network/new`  (`/network?new=1` would be more logical`)

**Comment by strk** [comment]
+1 for cleaner urls, but I guess backward compatibility should also be retained.

**Comment by strk** [comment]
so for your suggestion what I'm after would be `/network?guid=9&new=1` ?

**Comment by rabuzarus** [comment]
Yes somethink like this.

But we have to look if it's possible in an easy way (I mean from db structure - the url think souldn't be that hard). Yesterday I have looked inside the code to find the part for network/new . But I'm not really sure about this. 

If you want, take a look at mod/network.php . All network filter parts seems to be in this file

**Comment by annando** [comment]
mod/network.php is ugly. :-) We have to define which parts are allowed to be combined and which ones not. For example it doesn't make any sense to combine the filtering by contact id and the network or the group.

BTW: "guid" would be a bad name. "gid" would be better. "guid" is used for the id of posts.

**Comment by tobiasd** [comment]
@strk can you check if this is working now in current develop branch for you? Please note the explanation @annando gave in the PR #3286

**Comment by strk** [comment]
works for me
