### ISSUE TITLE
Fonts used in post textarea change size on focus

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1723]
Extremely annoying behavior: putting focus in and out of the "post" textarea changes the size of the test written in it. This is with "quattro" theme, with theme settings's "Post font size" and "Textareas font size" both set to 20.

**Comment by strk** [comment]
NOTE: setting "Post font size" and "Textarea font size" to 10 fixes the problem, so it looks like there's another "font size" which lacks a configuration ?

Actually, I don't understand the two existing configurations either... All I'd want is being able to read the pages :)

**Comment by tobiasd** [comment]
Which browser are you using?

**Comment by strk** [comment]
Firefox 38.0 on Ubuntu 14.04

**Comment by fabrixxm** [comment]
It's not a browser issue, it's the way it works.

**Comment by strk** [comment]
Do you agree the way it works is not very friendly ?

**Comment by tobiasd** [comment]
This only happens when you don't have the rich-text editor enabled right?

**Comment by strk** [comment]
I don't know, but I confirm I don't have the rich-text editor enabled.

**Comment by MrPetovan** [comment]
Is anyone still having an issue with this? How popular is the Quattro theme at the moment?

**Comment by tobiasd** [comment]
On Sat, 11 Nov 2017 23:36:39 +0000 (UTC)
Hypolite Petovan <notifications@github.com> wrote:

> Is anyone still having an issue with this?

It is the way the theme is supposed to work. I think we can close the issue.

**Comment by fabrixxm** [comment]
Quattro isn't supported anymore (by me, at least, @tobiasd ?) . we could remove it from repo...

**Comment by MrPetovan** [comment]
The theme doesn't have the `unsupported` file in its folder like `frost` and `frost-mobile`, maybe we should start by that. Closing this in the mean time.

**Comment by tobiasd** [comment]
On Sun, 12 Nov 2017 10:30:44 +0000 (UTC)
fabrixxm <notifications@github.com> wrote:

> Quattro isn't supported anymore (by me, at least, @tobiasd ?) . we
> could remove it from repo...

Then take your name out of the supporter Fabio.
