### ISSUE TITLE
ACL in bookmarklet isn't working as expected

### ISSUE THREAD

**Issue by annando** [friendica/friendica#1725]
Since the last version we are having /bookmarklet as a possibility to use the share widget for Diaspora. In the current version I cannot select or deselect whether I want to post the item to 3rd party networks or not.

There is much empty space under the list of contacts - but no possibility to select or deselect twitter, pump.io, ...

**Comment by rabuzarus** [comment]
I think it can be closed. https://github.com/friendica/friendica/issues/1726 has been accepted and it should work now
