### ISSUE TITLE
Embedded video dis-embeds on comment or like

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1727]
See comments in this thread:
https://kirgroup.com/display/61b57c7e69559509c082ff1264188732

Basically a video embedded in a post changes and becomes a simple link on commenting or liking it.
Tried with both "duepuntozero" and "quattro" themes.

**Comment by strk** [comment]
@fabrixxm suggested to look at a6603a54d9c68d1efee553e747de233f992dc3d2 as a possible source of the problem

**Comment by strk** [comment]
Now I see every interaction reloads the page, which sucks when you're watching an embedded video and want to "like" it while at it :-(

**Comment by strk** [comment]
So, I confirm reverting https://github.com/friendica/friendica/commit/a6603a54d9c68d1efee553e747de233f992dc3d2 fixes the issue for me (although behavior is still not satisfying).

Note that I wouldn't have noticed the "problem" if the video was never embedded, but the thing is it _is_ loaded on first look, so why omitting it on interaction ? Firebug shows no "media" being fetched on like/comment so I'd rather just avoid the stripping. After all users can ask their browser to avoid loading images or videos...

**Comment by fabrixxm** [comment]
because if it's  `[video]http://youtube.com/whatewer[/video]`, that will be converted to an iframe which loads a youtube page which loads youtube javascripts and youtube flashplayer, which loads youtube thumbnails, and doesn't seems to be our case, but it can start playing video, loading youtube mp4.
Every time your network page is reloaded, because you want automatic update of your page, don't you? :-)

Can this work better ? yes.
Can this work better now? no, we need to rework all the UI/UX from scratch.

**Comment by strk** [comment]
Automatic updates ? I actually installed a firefox plugin to block them in newspapers (refresh blocker).
I'm happy if I can get the visual notification about something new waiting for me to reload (which can wait, if I'm watching a video).

If a video starts playing on page load, that's a problem every time, not only on updates.
Even the first time it is a problem.

**Comment by MrPetovan** [comment]
Is it still current?

**Comment by strk** [comment]
I don't know and not willing to test at the moment. My Friendica use
is restricted to "wait for someone to fix the bug which prevents me
to be in contact with any of the contacts I used to have before my
disk crash". That'd be my priority in testing, shall anything move.

So feel free to close this ticket if it's waiting for my feedback.

**Comment by MrPetovan** [comment]
Ouch, sorry to hear that. Is it #3466?

**Comment by strk** [comment]
Yes, #3466 is the reason why I'm blocked by all pre-existing contacts at the moment

**Comment by foss-** [comment]
This is reported against two themes which don't even exist in friendica any longer. Should be fair to close this.

**Comment by strk** [comment]
Closing to be fair (please please please drop all but ONE theme from core :)

**Comment by foss-** [comment]
> Closing to be fair (please please please drop all but ONE theme from core :)

💯

This 👆! And drop legacy schemes.
