### ISSUE TITLE
adding an OpenID to existing account does not allow logging it with it

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1728]
The "Settings->AccountSettings->PasswordSettings promises that you would be allowed to login to the existing account via OpenID by adding that information.

I tried but while Friendica DOES accept the openid credentials, it does not map it back to my account, but rather prompts me for registering a new account.

I hadn't completed the registration to see what would happen then (I guess/hope I'd then be recognized by always logging in via openid).

**Comment by annando** [comment]
I really would like to remove the whole OpenID stuff. It doesn't seem to work right.

**Comment by strk** [comment]
Doesn't seem to work right in Friendica, you mean ?
As on itself OpenID works pretty nicely. Federated authentication since 2005...

**Comment by annando** [comment]
@strk I referred to the OpenID implementation in Friendica.

**Comment by strk** [comment]
It would be great to have a working OpenID support. Wouldn't it be great to be able to specify OpenID urls in the ACL for a post ?

**Comment by strk** [comment]
This is finally fixed with #2530 -- @annando it works right with the PR applied :)
