### ISSUE TITLE
@group mentions not working as documented (documentation is confusing)

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1729]
According to the guide, "Friendica makes no distinction between people and groups for the purpose of tagging. (Some other networks use !group to indicate a group.)", but while the UI prompts me for friend names when I start typing @..., it does not do the same for group names, and even when I type the whole group name it doesn't render it as a link to the group (of contacts).

I also think the people in the group are not getting the mention notification at all, which makes me think it's just not working.

A possible problem might be that my group names start with an Uppercase letter. Could this be a problem ?

**Comment by fabrixxm** [comment]
"groups" in other nets are  "forums" in friendica
"groups" in friendica are what on other nets are "aspects"

[this](https://helpers.pyxis.uberspace.de/profile/helpers) is a "forum" and you can mention it with "@helpers"

what you find in aside bar on yourserver/contacts are your "groups" of contacts, that you can use in ACL (e.g. "this post can be viewed only by my contacts in "football" group)

I'll call wrong wording in guide.

**Comment by tobiasd** [comment]
Added !forum notation to the docs in #5007 with the prior work from #2285 I think we can close this now.
