### ISSUE TITLE
Remove tgz from addon repository ?

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1730]
I noticed the friendica-addon repository is full of .tgz files, aren't them just packages of other directories ? Nothing that isn't considered "source" should be in the source repository (IMO).

**Comment by strk** [comment]
Where by "source" I mean `The “source code” for a work means the preferred form of the work for making modifications to it`, as defined in the GPL3 license:
http://opensource.org/licenses/gpl-3.0.html

**Comment by tobiasd** [comment]
If you only want to have one addon and not all, take the tgz file. That's what they are for. They just need to be updated once in a while with the make file.

**Comment by strk** [comment]
Sounds like a job for something different from a revision control system

**Comment by redmatrix** [comment]
I removed them from redmatrix/hubzilla. Most folks are grabbing the entire repository anyway and you're right - it's a mess dealing with revisions and cleaning up after the occasional merge conflict.  It neatly solved the problem of mixing addons from multiple repositories without causing git issues; which we're now doing in a completely different way.

**Comment by annando** [comment]
I'm with @redmatrix - I would like to remove it as well.

**Comment by fabrixxm** [comment]
:+1:
