### ISSUE TITLE
vier: no possibility to write private messages to foreign people

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1733]
The vier theme lacks  {{$wallmessage}} in profile_vcard.tpl.
So there is no "Message" button on the profile page (if profile uses vier theme) an no possibility to write people if you are not connected to them.

**Comment by annando** [comment]
The poll request is merged. @rabuzarus do you want to test it?

**Comment by rabuzarus** [comment]
technically it seems to work. but it needs some css styling.

I guess  aside #dfrn-request-link   needs to be extended with #wallmessagelink

**Comment by silke** [comment]
Hm. I consider it a feature that people I'm connected with cannot write me DMs.

**Comment by tobiasd** [comment]
@silke it's an optional feature to allow strangers to send you (n) DMs per day. The button in the profile for this was missing. But if you don't want to have strangers DM you, just don't allow it in the settings.

**Comment by annando** [comment]
@rabuzarus sorry, I really had forgotten the CSS stuff. It is now included in the pull request.
