### ISSUE TITLE
open id password problem

### ISSUE THREAD

**Issue by palmy9435** [friendica/friendica#1735]
I use Friendica  by OpenID, and  I'm registered by browser. When I'd tried to set a password for accessing by  smartphone, it asks me a old nonexistent pass.

**Comment by strk** [comment]
Why do you say "nonexistent" ? Did you not receive the password via mail ?

**Comment by davidep8922** [comment]
yes palmy9435 still received the password via e-mail even if registered through open id , and with that ' failed to connect with the app for your phone .

**Comment by palmy9435** [comment]
the ticket can be closed I'd found the pass in the mess of the spam

**Comment by strk** [comment]
Thanks for testing and following up, @palmy9435 ! Happy "friendicaing" (... we need a word for that)
