### ISSUE TITLE
fast discussions get the time mixed up

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1738]
I'm having a weird conversation where answers arrive before questions are sent.
Not only in the way they are displayed (which could make me think it was a theme issue)
but also in the way they are reported as being originating.

To be clearer, there are comments reported as being sent by "User X at 11:30" which contain answers to quetions reported as being sent by "User Y at 11:35". 

Is the time not taken from a synchronised clock ?

**Comment by strk** [comment]
\cc @fabrixxm

**Comment by strk** [comment]
Actually, the thread is public so can be seen directly: https://friendica.eu/display/davidepolimanti/7054970 (WARNING: italian language)

**Comment by tobiasd** [comment]
The time is taken from the server when the user sends it away. So one or more servers involved may have wrong time settings. I don't speak Italian, but they seem to be sorted correctly (I mean, one responses to another one, and so on).

**Comment by strk** [comment]
Thanks for the information. My server was indeed ahead of time.
I was suggesting @fabrixxm that adding an ntp client could be maybe suggested as part of the INSTALL procedure, and even better if the poller (or equivalent periodically running script) could check for system time being in sync to warn administrators of new nodes...

**Comment by strk** [comment]
I see the times in the linked thread now have resolution of _hours_ so obviously you can't see the problem. It was just a 4 minutes drift.

**Comment by tobiasd** [comment]
If you mouse over the *time ago* the timestamp will be displayed. As far as I checked, they were rising, sometimes within 3 seconds or so, but rising.

**Comment by strk** [comment]
I can't find the misordered discussion either, now.
Can it be fixing the time on my server also fixed the ordering
of old posts ?!

**Comment by rabuzarus** [comment]
Is this issue still valid or can it be closed?

**Comment by strk** [comment]
can be closed, I'm closing it
