### ISSUE TITLE
Introduction pages do not contain requestor profile info

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1739]
The introductions page tells me that "FirstName LastName" wants to be my friend, but doesnt' tell me what her profile or webfinger address is.

I don't have enough information to know who would i "friend" if I accepted....

**Comment by strk** [comment]
\cc @fabrixxm

**Comment by fabrixxm** [comment]
1) there's a link somewhere, i think on profile picture. I always take a look to a profile before confirming a connection. Could be more prominent.
2) you don't need to cc me on issues. I got a mail for every single post in this pages :-)

**Comment by strk** [comment]
Yes more prominent would be useful. Should be the _main_ information, imho,
as granting friendship to someone is a big responsibility (in terms of
where your messages end up going to). You also want to evaluate the server
they are using.

Ok about the \cc, I actually wanted to ask you :)

**Comment by annando** [comment]
In some tables we already should have even more data about such a user (depending, if this profile was transmitted via poco or is known to another user on the system). Then we additionally could display stuff like a description or the location.

**Comment by tobiasd** [comment]
there are some changes for this in the develop branch. can you test them?

**Comment by strk** [comment]
if you get someone to send me an introduction I'll tell you how it looks :)

**Comment by annando** [comment]
Tell me your address.

**Comment by strk** [comment]
You should have it, I'm one of your contacts: same nick @ pallamondo

**Comment by strk** [comment]
introduction received, it did include requestor profile link, thank you !
