### ISSUE TITLE
Replace StatusNet by GNU social

### ISSUE THREAD

**Issue by GreenLunar** [friendica/friendica#1744]
Replace StatusNet icon by GNU social icon.

See http://friendica.com/f-intro.jpg

**Comment by GreenLunar** [comment]
And add a pump.io icon, perhaps?

**Comment by tobiasd** [comment]
You mean the OStatus logo? (green O)

**Comment by GreenLunar** [comment]
Yes.

I did not know OStatus has a logo; if so, please close this ticket.

**Comment by tobiasd** [comment]
I think it was the following combo (as I did not find the references in one color set and the original resources aren't anymore). The [Wikipedia](https://en.wikipedia.org/wiki/Identi.ca) has the old logo for identica, StatusNet hat the same three "Q"s but more in a cloud-like assembled and OStatus had only one of them, IIRC the green one.

**Comment by GreenLunar** [comment]
@evanp, mind helping us on this?

**Comment by GreenLunar** [comment]
@evanp, may you help us with this?

**Comment by silke** [comment]
Ok, the above mentioned fix was merged long ago. Closing the issue.
