### ISSUE TITLE
RSS feed contact detail does not contain RSS url

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1745]
I just added my first RSS "contact".
Nice. But when I "edit contact" I do not see the URL to the RSS, which isn't nice.
Cannot change it, for example.

**Comment by strk** [comment]
I found that the RSS feed is shown from the contacts list.
But it's still not in the contact editor.

**Comment by tobiasd** [comment]
For clarification, the contacts list is the list of contacts in your profile and the contacts editor is /contacts? or is /contacts the list and /contacts/<number> the editor?

**Comment by strk** [comment]
Contact list is /contacts. There I do see the RSS url.
Contact editor is /contacts/7 (where 7 is the contact identifier)

**Comment by tobiasd** [comment]
Ok. The behaviour is consistent with the other network types, not only RSS/Atom. The link you are searching is hidden behind the contact photo; but the information might be useful being displayed more visible.
