### ISSUE TITLE
Allow overriding contact icon

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1746]
Sometimes contacts do not (or cannot) provide an icon. In those cases (and possibly others) it'd be useful to be able to configure a custom icon for a contact.

I'm suffering this one mainly from adding an RSS feed, which I'd like to have an icon associated with.

**Comment by tobiasd** [comment]
You can do this in the "repair" area of the contact. "Contacts -> Edit Contact -> Repair" Then the 2nd last option "new photo from URL"

**Comment by strk** [comment]
Thanks, that does it. Weird name "repair" for an editing operation.

**Comment by tobiasd** [comment]
The primary function of this part of the contacts section is to repair lost icons and DB entries, hence the name.

I'll close this issue then.
