### ISSUE TITLE
Empty list item in contact editor

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1747]
The third list item in the contact editor is always empty for me. On any contact.
Example:
![empty_item](https://cloud.githubusercontent.com/assets/289678/8632858/88b187f6-27ac-11e5-81fd-f2a50930eb5b.png)

**Comment by strk** [comment]
Theme: "quattro"

**Comment by tobiasd** [comment]
Yes, there is an empty <li> element in [line 39](https://github.com/friendica/friendica/blob/master/view/templates/contact_edit.tpl#L39) of the template. Other themes hide the bullet so it get's a design element with a large gap between the points.

**Comment by strk** [comment]
Style would better not be mixed with structure.
If you want to separate the items in two lists, better make two lists
(IMHO).

**Comment by tobiasd** [comment]
Yes I agree, I've always assumed that there might be a piece of information there, which just does not fit to my contacts.
