### ISSUE TITLE
duplicate  account

### ISSUE THREAD

**Issue by davidep8922** [friendica/friendica#1748]
My son did one account on friedica.eu through open id then to also access the app on the phone and ' come as e-mail and password
now finds duplicate the ' account 
the  https://friendica.eu/profile/pspig  is  the login account
 https://friendica.eu/profile/palmy9435  account that should be eliminated , can you tell me how?

**Comment by Keith2** [comment]
Under settings, Remove account at the bottom.
Alternatively do not log in to the duplicate account, the public server addon will eventually remove it.

**Comment by davidep8922** [comment]
can no longer ' to enter https://friendica.eu/profile/palmy9435

**Comment by davidep8922** [comment]
ok eliminated https://friendica.eu/profile/palmy9435  coming in with open ID now but ' does not make me more ' get in https://friendica.eu/profile/pspig  and I have no way to eliminate it

**Comment by Keith2** [comment]
palmy9435 was showing as removed, normally there's a delay before it actually happens.
It has now been admin removed.
Try pspig again, you may have to reset the password.

**Comment by davidep8922** [comment]
ok now is ok
