### ISSUE TITLE
[feature] Trim long posts, provide "show more" link

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1759]
I've added a few RSS/Atom contacts but now my news stream is often fully occupied by one or two loooong posts. I understand it's up to the RSS/Atom publisher to decide how long the text in there is, so how about having Friendica trim long texts and provide a "show more" link to see it fully ?

Is this something that belongs to theme or core ?

**Comment by annando** [comment]
Just activate the "show more" addon. It is doing exactly what you described.

**Comment by strk** [comment]
That's perfect, thanks !

**Comment by davidep8922** [comment]
:-)
