### ISSUE TITLE
Allow sharing private posts

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1762]
I think sharing private posts should not be forbidden. The info contained in the post could be shared anyway by copy & pasting its contents, so why preventing the easy share ?

By allowing sharing, we could warn the user about why sharing should be done carefully.
It would be much easier to do IF it was possible to know who the recipients of the original posts were (at least approximately). See #1656.

**Comment by tobiasd** [comment]
:-1: the warning would just be clicked away, many years of training will guaratiee this.

If you want to break the trust someone put into you by sharing something in private with you, you should have to work for it. And if this means copy and pasting.

**Comment by strk** [comment]
How about letting the original post author decide if he's ok with me sharing ?
In my case many of my "private" posts are not really "private", but only configured as such to avoid "spamming" the public with information the public likely doesn't care about. But I"m perfectly fine with friends sharing my post with their friends...

**Comment by fabrixxm** [comment]
It's a mess.
It's already a mess, but that would be messier.
Then you have to deal with users that want it to be private but clicked "allow share" and then complains that their private post is now public.
And with people who want to share this with you but not with Bob, but they clicked "allow share", and post goes to Alice, which is in contact with Bob. She reshare the post, and it goes to Bob.

**Comment by strk** [comment]
Isn't there a "don't show" option in the ACL ? Is that used at all to forbid access ?

**Comment by annando** [comment]
This isn't exported to the other systems to avoid that someone can see the receivers. All things in the ACL are treated like BCC in mails.

**Comment by strk** [comment]
But in order to create a community it is useful to get a feel about who are you talking with when you comment. Who's going to read your comments...

Once again, should the author decide this ? (it does when she picks "Bcc" or "Cc")

**Comment by silke** [comment]
I don't like the idea at all. I expect "private" to mean "if you read this, it's for you and not for the general public". If I restrict posts and my followers start asking "hey can I share this with John Doe?" why should I say yes?

**Comment by strk** [comment]
Couldn't you just say no ?
In other words, would it be ok if it was a choice you make
when initially sharing ? The default could be "no further sharing"
to retain the current model.

**Comment by rabuzarus** [comment]
There are many concerns about implementing such a feature and this request is 3 years old. Can we close it with wont fix?
