### ISSUE TITLE
Feed urls not normalized before checking for duplicates

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1770]
If you duplicate a slash in an RSS url you can cheat Friendica into thinking you don't already have that contact. It was useful for me (as I was debugging something), but I don't think it's nice to fail so easily.

Unless you think duplicating a slash in an URL may possibly result in a different resource being addressed (I'm not into web development since a long time so dunno what habits people have these days...)

**Comment by annando** [comment]
I tested it with a trailing slash, with double slashes and without them. I tested http and https - the system always tells me that I already added the contact. For me it works.

**Comment by strk** [comment]
checked, works for me too (might have been the recent refactoring).
