### ISSUE TITLE
"quattro" theme does not show events edit link

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1771]
I found no "edit" button for events, does any such thing exist ? Maybe I need to activate some plugin ?
Or is delete/new the only way to edit an event ?

**Comment by strk** [comment]
I see someone tries to edit/delete using the corresponding post but that way to do it also fails (#1561)

**Comment by silke** [comment]
I can edit (my) events by going to https://my-friendica-instance.org/events and then double-clicking onto them. There is a pop-up opening with an edit button at the bottom-left. That button is not there if I'm not allowed to edit the event.

**Comment by strk** [comment]
The popup I get has no edit button. But I created those events so I don't understand why I should not have the rights to edit it.

**Comment by rabuzarus** [comment]
You can edit your own events. There are links in the left bottom corner of the event colorbox popup. The Problem is that not all themes have icons for the link and so they are not visible. If you are on 3.4.1 you can try the vier theme. I submitted a patch some time ago to give the links icons in vier theme. https://github.com/friendica/friendica/pull/1663

**Comment by strk** [comment]
You're right ! So, I'm changing the title to reference "quattro" (the theme I'm using)

**Comment by tobiasd** [comment]
I've just added the missing icons to my clean theme, quattro will follow as soon as I've installed lessc eventually.

**Comment by tobiasd** [comment]
Nope, wont work node.js is throwing internal errors, so someone else needs to check this (@fabrixxm ?)

**Comment by tobiasd** [comment]
the missing icons should now be in quattro (the patch was accepted an hour ago) could you check it out.

**Comment by strk** [comment]
Confirmed, thanks!
