### ISSUE TITLE
Show contact list only to friends ?

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1772]
I'd like my friends to see my list of contacts but not the rest of the world. Is it possible at all ? I'm not finding a way to do that.

**Comment by tobiasd** [comment]
yes it is. make a second profile, one for everybody without showing your contacts and one for all your friends. Then when you accept a new contact, just remember to change the profile they can see to your "friend profile". If they follow a magic-link to your profile page (the redirs) so the node can check that the visitor is allowed to see the other profile, they will see the contact list.

**Comment by strk** [comment]
Uhm, I can't find the page in which I can create profiles.
I did enable "multiple profiles" from the settings panel.

**Comment by strk** [comment]
Never mind, found. Will quikly test and let you know. Thanks !

**Comment by tobiasd** [comment]
have you tested this?

**Comment by strk** [comment]
Yes, sorry I forgot to report.
It's working. Thank you!
