### ISSUE TITLE
vier theme: unreachable toggle mobile link 

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1773]
Using the vier theme, the "toggle mobile" link is unreachable behind the site banner/menu.
There's no such problem with "quattro"

**Comment by tobiasd** [comment]
in develop branch vier theme now has better support for mobile devices. can you check if we can close the issue @strk?

**Comment by strk** [comment]
Well I don't even see a "toggle mobile" link now, but the browser menu has an item to toggle between mobile and desktop version so this is a non-issue for me now. Closing.
