### ISSUE TITLE
Touch icon not honoured

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1774]
I added a "Shortcut icon" to my node and it works fine on desktops.
But adding a "Touch icon" does not change the icon shown on mobile browsers.

**Comment by tobiasd** [comment]
bug on the mobile browser? I have a "shortcut icon" and a "apple touch icon" defined in the header, the browser of my Jolla has the correct icon displayed.

**Comment by strk** [comment]
I installed "View Source" addon for firefox mobile and looking in the sources I actually do not see the custom "shortcut icon" and "apple-touch-icon" when toggling the mobile interface (frost-mobile).
It is there when switching back to desktop mode.

**Comment by silke** [comment]
So is it a browser issue or not??? If so, I'd like to close this issue as not related to friendica.

**Comment by tobiasd** [comment]
looking at your profiles HTML source I see

    <link rel="shortcut icon" href="https://amici.pallamondo.net/images/icon-amici.png" />
    <link rel="apple-touch-icon" href="https://amici.pallamondo.net/images/icon-amici.png"/>

which should be the shortcut icon for apple and others. And it looks custom for me.

**Comment by strk** [comment]
I guess it was fixed by a recent upgrade, will re-open in case it pops up again. Thanks for testing.
