### ISSUE TITLE
Blocked contacts are stuck in groups

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1777]
Blocked contacts cannot be removed from groups.
No notice/warning/info is given to the user about the reason why those contacts cannot be removed.
Clicking on them just fails, while clicking on non-blocked contacts in a group successfully removes them from the group.

**Comment by MrPetovan** [comment]
Just reproduced on the contact page, unchecking the group selection in the group widget works, but reloading the page shows the choices haven't been recorded.

**Comment by MrPetovan** [comment]
Just verified in the `/group` display that the blocked contact isn't displayed, which prevents from removing them from the group as well.

**Comment by MrPetovan** [comment]
Closed via #6732
