### ISSUE TITLE
Allow setting filters on user feeds

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1778]
It would be useful to configure, for a contact, to only receive posts matching or non-matching a given set of filters. For example, to avoid receiving posts in a language which you can't read.

See background here: https://amici.pallamondo.net/display/96008cc27155acaf9a43a8a028463845

Same request was sent to GNUSocial developers, as this is a federated social issue:
https://git.gnu.io/gnu/gnu-social/issues/66

**Comment by tobiasd** [comment]
There is already a good guess for the language a posting is written in available; vier used to display it optionally, the typography addon uses it to load the correct language rules. It's waiting for a developer with time to implement a filter based on the language.

**Comment by strk** [comment]
Yep, I saw the "vier" theme showing those guesses.
Could the guess become a suggested "category" for the post, before the user submits it ?
Or are you envisioning a mechanism in which the guess is performed by the reader ? (could be weak)

**Comment by fabrixxm** [comment]
categories don't federate

**Comment by tobiasd** [comment]
IIRC @abinoam envisioned something where the user says "I speak German, French, English" and friendica then only displays postings matching those languages by default. The guess is performed for any posting by the node, but is reliable mostly for long postings. I don't use categories myself, but the language is a attribute of a posting, you could most likely write a quick addon collapsing the content of postings in languages not spoken by the viewer.

**Comment by strk** [comment]
So that I can see what the full set of information making up a post, is there a way from a post page to retrive it in the format it travels from node to node ?

**Comment by strk** [comment]
For example, staring from here: https://amici.pallamondo.net/display/61b57c7e3555acc44cbd261007689549

**Comment by tobiasd** [comment]
No, the meta-information (like languate or date it was edited after initial sending) is only "visible" in the "code" but not for every user.

**Comment by strk** [comment]
It would be useful to have that option, for spreading knowledge about inner workings and have people learn by imitation (view source?)

**Comment by fabrixxm** [comment]
there is a "viewsrc" plugin. It shows bbcode source for a post.
What you want is inner rappresentation of a post.

You can: 
- look at db, "item" table.
- you can start with "[nsfw](https://github.com/friendica/friendica-addons/blob/master/nsfw/nsfw.php)" plugin and and dump data passed to `nsfw_prepare_body(&$a, &$b)` function: `$a` is the global application object, `$b` is an array with current item. You can dump it and see what's inside.
you can, for example add 
```php
echo "<pre>"; var_dump($b['item']); killme();
```
at line [116](https://github.com/friendica/friendica-addons/blob/master/nsfw/nsfw.php#L116) and load network page. you should get the 'item' array for the first post in network page.

**Comment by strk** [comment]
Uhm, I've just installed "viewsrc" but can't find any "view source"
link nor any differences in my posts. Would BBCode include mentions
fully expanding to webfinger or is that only visible as "inner
representation" ?

**Comment by tobiasd** [comment]
The view source link is in the pull down menu of the authors of the posting you want to see the source from. The source would contain something like

    @[url=http://example.com/path/to/profile]name[/url] ...

**Comment by tobiasd** [comment]
the language filter addon was merged into the addon repository.

**Comment by strk** [comment]
I'm loving it, thanks !
