### ISSUE TITLE
Add RSS link(s) in the "connect" page for a user

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1779]
For those who are willing to follow public posts of a user, it would be useful to have a link to the RSS feeds. I guess such links could be in the "connect" page but maybe it could also be in the "profile" page.

Right now there's no such link rendered in the HTML output, nor I could find it in a `<link>` tag of the profile page source.

**Comment by tobiasd** [comment]
see the [FAQ](https://github.com/friendica/friendica/blob/master/doc/FAQ.md#how-to-create-a-rss-feed-of-the-stream) about the RSS feed, the browser should pick up the link element. You want this link also on your wall?

**Comment by annando** [comment]
I think it would be a good idea to have such a link visible as well.

**Comment by strk** [comment]
I'd like to have visible links, yes. Way too many times I'm missing the visible links.
For example right now I'm teaching a friend to use Friendica as an RSS aggregator, but many of the blogs she's interested in do not expose the RSS link, meaning I have to find it in the HTML source, which is way far from being friendily (dunno if Friendica would attempt to do it itself, but you never know how many bugs you can encounter when relying on such magic :)

**Comment by strk** [comment]
Ideally, in presence of "categories", there would be also links for each of them (in addition to the link to the all-things feed)

**Comment by tobiasd** [comment]
Yes, friendica tries that magic. Just copy/paste the blog URL into the field for adding contacts, if friendica finds a RSS field it will add the blog.

**Comment by fabrixxm** [comment]
An rss icon in connect page, or an rss icon for categories it's :+1: for me
Anyway, you don't need to watch the source to find rss feeds:
![senzanome](https://cloud.githubusercontent.com/assets/309361/8773937/c42be014-2ed8-11e5-83f0-dd36b3f4c74e.jpg)

**Comment by strk** [comment]
I never get that icon in the firefox menu.
Not even when I'm on a wordpress.com blog... does it depend on an
add-on ?

**Comment by fabrixxm** [comment]
No. Try "Personalizza"

**Comment by strk** [comment]
Wow, I never saw it before, thanks for the suggestion
(it's "Customize" here, btw :>)
