### ISSUE TITLE
theme "quattro": post privacy editing widget invisible

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1780]
When post editing is enabled you can "edit" the ACL (actually you can ly add a Cc).
Well, today I was trying to do that but got a tiny dialog window. So tiny that's impossible to focus in the input text and to read the label. Practically, I cannot add a Cc for my posts.

This is using the "quattro" theme.

**Comment by strk** [comment]
Is the "ACL editing" widget still supported at all ?
Neither the "vier" theme (#1781) nor "duepuntozero" expose that widget.

**Comment by tobiasd** [comment]
You cant change the visibility of a posting once posted.

**Comment by strk** [comment]
I remember that I've seen the possibility to add a Cc (maybe a mail was sent to the email written there ? I don't really know what it did)

**Comment by strk** [comment]
I'm aware that you cannot change the visibility of a post. It's something I'd like to be possible, but already discussed in #704

**Comment by strk** [comment]
@tobias can't you click on the padlock in the edit form ? I can, but what pops up is just useless...

**Comment by tobiasd** [comment]
yes, that button needs to be removed I think. As it leads to the wrong impressions.

**Comment by tobiasd** [comment]
fixed in current develop branch
