### ISSUE TITLE
theme "vier": missing post ACL editing widget

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1781]
There's no widget to edit a post's ACL with the "vier" theme.
The "quattro" theme does have one (although currently broken: #1780)

**Comment by strk** [comment]
I've also tested "duepuntozero", "frost" and "smoothly". They are all missing the widget.

**Comment by tobiasd** [comment]
You cannot change the permissions on a posting once it is posted. Hence there is no such widget.

**Comment by strk** [comment]
In that case the widget in "quattro" theme is to be removed ?

**Comment by fabrixxm** [comment]
duplicated of #1780
