### ISSUE TITLE
Local contact not seeing my posts

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1782]
I wrote a post visible by contacts in my group "Amici".
One of the contacts in that group cannot see it.
How can I debug this ?
She gets "item not found" if she goes directly to the url of my post.

**Comment by tobiasd** [comment]
But she has it in her network stream?

**Comment by strk** [comment]
None of my posts are in her network stream, not even the public ones.
Looking at my profile in her contacts list shows:
```
Last update: Mon, 20 Jul 2015, 9:50 AM (Update was not successful)
```

What does "Update was not successful" mean ?

Hitting "Update now" doesn't seem to change anything.

Note I've been playing with "multiple profiles" recently. Possibly _after_ accepting her friendship.
Indeed if I follow (as her) my profile link, I get to see my "public" profile, rather than my "for-contacts" profile, which is what I configured my account to show her.

**Comment by tobiasd** [comment]
Friendica checks regularly the feeds from your contacts for something new that did not reach the node (say because you turn your notebook on which you are running friendica off over night, or your server had a hardware problem for a day). The last of these updates was 9:50 AM.

**Comment by strk** [comment]
What does it mean for that update to be "not successful", as written in that message ?

**Comment by strk** [comment]
For the record: the update time does change on clicking "Update now". Current one is:
```
Last update: Mon, 20 Jul 2015, 12:34 PM (Update was not successful)
```

But still.. "was not successful" ?

**Comment by fabrixxm** [comment]
Be aware: multiple profile is not multiple accounts.
Multiple profiles just change what people sees in your profile tab when they come to your node as authenticated contacts

**Comment by annando** [comment]
Can you check, whether your server is reachable via its public name directly from the server?

During the update the systems does a HTTP(s) request to the contact's server. If that fails then this error is displayed. The system does this HTTP request no matter if it is a foreign server or the local one. If - for example - you have several interfaces on your server and the hostname directs the internal requests to a local interface, but the HTTP server only listens to the public interface, then this error could happen.

**Comment by strk** [comment]
On Mon, Jul 20, 2015 at 05:22:21AM -0700, Michael Vogel wrote:
> Can you check, whether your server is reachable via its public name directly from the server?

It is, just double-checked.
Apache listens on the IP to which `hostname` is resolved.

**Comment by annando** [comment]
Could you check if it happens only to your account? We have to check if it is a problem related to your server or your account?

**Comment by strk** [comment]
I'm closing this as it may have been due to cookies confusion (multifox addon not succeeding at isolating cookie jars).
