### ISSUE TITLE
allow admin to completely remove user

### ISSUE THREAD

**Issue by davidep8922** [friendica/friendica#1783]
I've removed an user because malfunctioning (migration failed) and now I'd like to re-create it, but the system does not let me because the user is still existing in "waiting to be completely removed" state.

(How) can I force complete removal ?

I'm running Friendica 'Lily of the valley' 3.4.1 - 1185

**Comment by tobiasd** [comment]
The system wont let you recreate a user with that name to prevent identity fraud. Except if you do some surgery on the database of your node.

**Comment by davidep8922** [comment]
I can then restore it ?

**Comment by davidep8922** [comment]
how do I make a normal user an administrator ?I changed the email administrator and the user does not give me more ' menu Administration

**Comment by davidep8922** [comment]
I solved the modified file .htconfig.php and put the new e-mail

**Comment by davidep8922** [comment]
remains the problem of permanently delete a user put into it , it was a user who had migrated from friendica.ue problems

**Comment by davidep8922** [comment]
Utete Deleted Successfully and definitely by the manu User administration
