### ISSUE TITLE
Unknown theme in use by default

### ISSUE THREAD

**Issue by davidep8922** [friendica/friendica#1784]
I have installed Friendica 'Lily of the valley' 3.4.1 - 1185, and I cannot tell what theme is in use because the 'Display' user setting section gives me an empty select widget for the 'Theme' input.

From the admin panel all themes are disabled. 
If I enable any theme, the 'Theme' input widget in the 'Display' user setting section contains a single theme (the enabled one) making it impossible to switch back or know what theme was in use before (the default)

**Comment by tobiasd** [comment]
The default theme is "duepuntozero", it's also the fallback for the system if no theme is selected.

**Comment by davidep8922** [comment]
OK thanks
