### ISSUE TITLE
New contacts start as blocked

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1792]
I've noticed that new contacts start as "blocked". Is this intentional ?

**Comment by annando** [comment]
They are blocked until the other side allows the request.

**Comment by strk** [comment]
But there's a menu item to "unblock" them, so what's the point ?
I mean, is it _my_ choice or that of the other party ?

**Comment by strk** [comment]
I confirm once the connection is accepted the user becomes unblocked, but I still don't understand the behavior, as it strips my control over block/unblock flag...

**Comment by strk** [comment]
so, what's the rationale ? did it change recently or was it always like this (I didn't notice before) ?

**Comment by annando** [comment]
AFAIK this behaviour never changed.

**Comment by silke** [comment]
Hey, this is an bug tracker rather than a forum. ;) I'm closing this one.
