### ISSUE TITLE
Improve bbcode [code] tag render of one line codes

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#1796]
Currently `[code]` tag is rendered as `<code>`.
Our default css render this element as block element (that break text flow).
On certain situations, could be better render it with another element, to stile as inline:
when `[code]` contains no end-line chars, and when there are other chars than space or tab before him on the same line.

This would allow to render the text:

the variable called [code]$a[/code]

as

the variable called `$a`

instead of

the variable called
```
$a
```

This is also more similar to markdown difference between single backtick and triple backtick, leading to better visualization of some diaspora posts.

See here http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_phrase_test for some other elements to use instead of `<code>`

(i'm for `<kbd>` or `<var>`)

**Comment by tobiasd** [comment]
I like the current behaviour. Can we have both?

**Comment by fabrixxm** [comment]
You can't like the current behaviour, it's horrible :-P

This is the same page rendered with current code and with an experimental branch
![friendica-feature-1796](https://cloud.githubusercontent.com/assets/309361/9058709/9be2051c-3aa3-11e5-8dfe-19887d83067b.png)

**Comment by tobiasd** [comment]
Well I like to be able to post multible lines of code in a single code block. From your description I understood that you want to get rid of that and instead only have embedded code in the text.

**Comment by fabrixxm** [comment]
no no no. I want [code] tag in a text line without newlines inside to be rendered as inline.

Other [code] blocks should be rendered as usual.

eg:

    The variable called [code]$a[/code] can be used in this code:
    [code]$b = $a + 1;[/code]
    or in this:
    [code]if ($a) {
       die();
    }
    [/code]

The first [code] should be rendered as inline, the second and the third as blocks. The 3rd because there are \n in it, the first because there aren't other chars before it on the same line...

**Comment by tobiasd** [comment]
:+1:

**Comment by annando** [comment]
I wouldn't like to change the bbcode but the CSS for "code".

**Comment by fabrixxm** [comment]
@annando : I don't want to change the bbcode: just render it a little different on content and context.
You can't do this with only CSS. With CSS you have "all inline" or "all block".
I'll upload my experimental branch, so I'll show you what I want to do :-)
