### ISSUE TITLE
Delete Improve-Performance.md (doc)

### ISSUE THREAD

**Issue by fraengii** [friendica/friendica#1805]
It seems to me, that the named file is obsolete. For example it tells to activate the Alternate Pagination plugin and some other settings which are already preset.
Please have a look at it. I'm overcharged with this.

**Comment by tobiasd** [comment]
something to attach to #1478

**Comment by tobiasd** [comment]
I think it should be reviewed and updated; not deleted.

**Comment by tobiasd** [comment]
@annando has updated the help files, so I'll close this issue.

**Comment by fraengii** [comment]
Thanks @annando! Thanks @tobiasd!
