### ISSUE TITLE
Document the SQL user permissions that Friendica needs to run

### ISSUE THREAD

**Issue by strugee** [friendica/friendica#1814]
This is for the purposes of least privilege, etc.

**Comment by tobiasd** [comment]
rel. #1478

**Comment by annando** [comment]
If someone wants to add this to the documentation: Friendica needs the permission to create and delete fields and tables in its own database. It doesn't need the permission to grant permissions to others. And it doesn't need permissions on other databases as well.

**Comment by tobiasd** [comment]
I wanted to clear this at the latest in Zwenkau :-)

**Comment by tobiasd** [comment]
It's now in the INSTALL docs in the develop branch. So end of the month it will be in master as well.
