### ISSUE TITLE
Diabook theme suggests connecting to Facebook even if this isn't enabled

### ISSUE THREAD

**Issue by strugee** [friendica/friendica#1815]
This is shown on the `/network` page, under "Connect Services".

**Comment by annando** [comment]
Diabook is unmaintained. It has several issues. Maybe we should delete it?

**Comment by tobiasd** [comment]
the diabook theme is unsupported, it is in the repository for old users to not loose their current theme out of the sudden.

You can probably remove the reference to FB by editing the ```/view/theme/diabook/templates/communityhome.tpl``` file. Have not tried myself, but it seems to be the only file in diabook referring to FB.

**Comment by annando** [comment]
The whole section in which Facebook is mentioned contains a list of connectors that may - or may not - be enabled on the system.

**Comment by annando** [comment]
I would like to close this issue. In the current developer branch several options were added to the "vier" theme that were derived from Diabook.

**Comment by rabuzarus** [comment]
I'm for closing it to clean up the bug tracker a little bit
