### ISSUE TITLE
GUID problems after moving nodes and moved accounts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1840]
inherited from #1491 

possible problems with GUID in the cases when the admin moves a node
also find a solution for the already moved accounts to regenerate GUID in a way that it is save and not done by accident.

**Comment by annando** [comment]
I think that we can't solve this problem. If you would generate a new GUID for your account then your posts would appear on the old servers that new you before - but will disappear on the newer servers that know you with your new GUID.

I guess this problem can only be solved with a bugfix in the Diaspora part. I spoke with one of the Diaspora devs about this problem at the 32C3.

**Comment by tobiasd** [comment]
My experiments with the RasPi/FreeBSD are preperations for migrating (parts of) the server at $HOME. I would have preferred to copy the files over, but I can import/export the account as well and brace the extra work for reconnecting all the federated contacts.

Too bad OStatus and Diaspora don't support the "moved" signal.

**Comment by tobiasd** [comment]
closing this, as Michael is right ;-)
