### ISSUE TITLE
oohembed service isn't avaiable anymore

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#1855]
oohembed now redirects to embedly for which an apy key is required.

code in [include/oembed.php](https://github.com/friendica/friendica/blob/master/include/oembed.php#L59-L67) should be updated

**Comment by annando** [comment]
Since there already is some code for embedly, we simply could remove the other part and let the API key be entered via front end. I think we should do this for the current release.

**Comment by fabrixxm** [comment]
Yep. was my idea, but no time atm, so I left an issue :-)

**Comment by annando** [comment]
I guess I can do it this evening.

Ceterum censeo: We really should reorganize the admin settings

**Comment by tobiasd** [comment]
When embedly is not configured, following an RSS feed  now only shows the header, but not the body of the feed item. Does the option to fetch more informations from the contact be deactivated or is this a bug?

**Comment by fabrixxm** [comment]
It shouldn't be related.
Old oembed code called oohembed which redirected to embedly which returned error because user key was missing, so nothing should have changed for rss

**Comment by tobiasd** [comment]
Set the setting to fetch more information back to deactivated now the feed items are displayed with the original feed content.

**Comment by annando** [comment]
And the oohembed call was only done when the regular oembed calls fail.
