### ISSUE TITLE
URL anchors considered Tags 

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1858]
Sharing a link with an anchor makes Friendica think the anchor part is a tag ...

Example:

```
[bookmark=http://www.festivalstradella.org/#!programma-2015/c1tvn]FESTIVAL ALESSANDRO STRADELLA[/bookmark]
```

**Comment by annando** [comment]
Which version have you tested? I couldn't reproduce it on my system (developer branch).

**Comment by strk** [comment]
commit 55ad7f9199de6914c2b4def3e71127642c7cb914 aka 3.4-644-g55ad7f9

Full snippet is (made with "Web Link" button):
```
[class=type-link][bookmark=http://www.festivalstradella.org/#!programma-2015/c1tvn]FESTIVAL ALESSANDRO STRADELLA[/bookmark]
[quote]III° Festival Internazionale ALESSANDRO STRADELLA Nepi VT Italy CONCERTI CONFERENZE MASTERCLASS[/quote][/class]
```

**Comment by strk** [comment]
The Theme is "quattro"

**Comment by fabrixxm** [comment]
I can reproduce this. @annando you need to post the message, in preview you don't see tags.
I thought to have already fixed this, but ...

**Comment by strk** [comment]
@fabrixxm you might be remembering a similar one which was about hashtags in [code] blocks

**Comment by fabrixxm** [comment]
Yes, it was in commit a98d2ee38

**Comment by strk** [comment]
Yep, for #1041 (so we have full linking :)

**Comment by tobiasd** [comment]
Utzer had a [similar problem](https://social.yl.ms/display/e18176ef6755dd6fd7d6f22477987396) with a @ in the link

**Comment by MrPetovan** [comment]
Both issues (with # and @ in links have been solved by now.
