### ISSUE TITLE
UX: Show an info message if an empty contact group ist shown.

### ISSUE THREAD

**Issue by tschlotfeldt** [friendica/friendica#1871]
If an empty contact group is displayed it dosn't show an info text telling the user that there is no contact associated with this group. This could be irritating because it follows a list of „All Contacts“.
So a short explaination could be helpful.
![20150831_shot_contacts_groups](https://cloud.githubusercontent.com/assets/149240/9580263/acc05400-4ff8-11e5-9e52-e3c91336c3e9.png)

**Comment by annando** [comment]
See pull request https://github.com/friendica/friendica/pull/2148

**Comment by tobiasd** [comment]
works for me now in develop, so I'm closing this issue

**Comment by tschlotfeldt** [comment]
Nice :-)
