### ISSUE TITLE
Diaspora: Comments from Friendica are created as new posts

### ISSUE THREAD

**Issue by annando** [friendica/friendica#1877]
See this post: https://pod.geraspora.de/posts/ec054ce75655e8a895073f4544249233

In fact it is a comment, as you can see here: https://pirati.ca/display/978b2e951555e8a7a927f38101359471

This seems to me like (another) show stopper for the upcoming release.

**Comment by tobiasd** [comment]
I've seen this with replies to my postings and addressed it to the fact that my (new) account has the old accounts GUID and thus D* does not like my new account at some pods and then somehow interprets the reply due lacking top posting as a top posting in itself.

**Comment by annando** [comment]
I added some more logging :) We have to check the origin of the problem. Is it the server of the commenter or the server of the original post. When it happens again we can have a look at the logfiles. Since I cannot reproduce it, it doesn't seem to be an obvious thing. So I would redeclare it as a "non-show stopper".

**Comment by annando** [comment]
The problem always seem to occur when a comment was send to Diaspora and the original posting hasn't reached Diaspora.

**Comment by annando** [comment]
I rewrote the whole Diaspora part. I don't think that this was a Friendica issue but a Diaspora issue. Diaspora changed some things with incoming comments. Had it happened again? If not then I would like to close the issue.

**Comment by tobiasd** [comment]
Any reports of this since March?

**Comment by annando** [comment]
I never heard of this problem again. I think we can close the issue.
