### ISSUE TITLE
Avatars missing when searching for persones

### ISSUE THREAD

**Issue by ddorian1** [friendica/friendica#1884]
When searching for a person with the search bar at top of the network and profile page, there are no avatars shown (even not your own when searching for yourself).
![screenshot-20150908 155029](https://cloud.githubusercontent.com/assets/5332987/9736610/8069e420-5642-11e5-9130-bdc9310ed13d.png)

**Comment by silke** [comment]
I can confirm this. (My instance is on the latest development branch.)

**Comment by annando** [comment]
I can't reproduce on my system. Which directory server are you using?

**Comment by ddorian1** [comment]
http://dir.friendica.com/submit

**Comment by ddorian1** [comment]
I wasn't aware of the fact that this is just the url for uploads. My .htconfig.php was missing the 'directory' entry. After adding 
```
$a->config['system']['directory'] = 'http://dir.friendica.com';
```
it is working now.

**Comment by annando** [comment]
This issue (and another one) pointed to the situation of the different configuration parameters. So thanks for creating the issue. There will be a pull request soon that avoids the confusion.
