### ISSUE TITLE
Cut fork info from duthied

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1885]
@duthied, wouldn't it make more sense to give repo ownership to the "Friendica" group directly ?

**Comment by redmatrix** [comment]
There's a long story behind this. The repo was owned by "Friendika" and when that account was deleted and the name changed to "Friendica", github went searching for anybody in their system who had earlier checkins and linked it to that. In fact I have the initial repository and hold the complete history from Mistpark to Hubzilla. Duthied merely held a copy on github when github went looking for earlier forks. It could have just as easily been Tobias or fabrixxm, but they found duthied first.

**Comment by strk** [comment]
I think it's not too complex for @duthied to go to Settings and
TransferOwnership to @friendica. Or maybe ask github ops to do
this directly

**Comment by redmatrix** [comment]
Neither he nor Anne have spoken to any of us in years since the testbubble theme kerfuffle. So good luck.

**Comment by duthied** [comment]
A simple request to change ownership would have sufficed - I wasn't aware of any of the background that @redmatrix detailed in his comment.

**Comment by duthied** [comment]
done

**Comment by duthied** [comment]
..or not, I get an error: `friendica already has a repository in the duthied/Free-Friendika network`

**Comment by fabrixxm** [comment]
I don't see that to be a problem now.
I think in future we could migrate friendica repos under a github Organization.
I'm closing this issue as not an issue :-)

**Comment by strk** [comment]
I do think it's confusing to see friendica org not being the root of the network

**Comment by strk** [comment]
@duthled "friendica" was correct, the problem is that github sees the existing "fork" and doesn't want to override. The fix seems to be for @friendica to temporarely drop the "friendica" repo, wait for ownership transfer and force-push everything. Or (might be easier), just send a mail to the github devops: https://github.com/contact

**Comment by tobiasd** [comment]
History books are full of confusions, this is nothing else, just historic roots to Friendika and Mistpark. If it is a bug, then one from github, I think it can be closed.

**Comment by strk** [comment]
I'll note that in May this year someone sent a PR to the @duthied repo, @duthied ? Would that force github bot to re-compute roots ?
