### ISSUE TITLE
update_suggestions takes to long

### ISSUE THREAD

**Issue by ddorian1** [friendica/friendica#1886]
There seems to be a problem with the new suggestions in the 3.4.2 branch. For me, poller.php never exited, because it runs for more then 10 minutes and gets killed be the next one.
After adding some debug messages (and turning of cron), it found that update_suggestions() takes very long. Especially poco_load in line 1253 of socgraph.php is running >40min right now just for https://friendica.free-beer.ch.

**Comment by ddorian1** [comment]
After adding 
```PHP
if (strpos($base, "friendica.free-beer.ch") !== FALSE)
         continue;
```
before line 1253, it seems to work fine. So maybe a time out for poco_load may be a good idea, to prevent one slow or broken host to stop the whole poller.php?

**Comment by annando** [comment]
Have you set a timeout for network connections? There is one in the admin settings.

**Comment by ddorian1** [comment]
Yes, it's at 60s. But from what I understand from the log, there isn't a single connection that takes really long. Here is the beginning of a log, I killed the process after ~3 min.
https://jschwab.org/friendica.log

**Comment by ddorian1** [comment]
With #1887 it's working fine for me, so I will close this.
