### ISSUE TITLE
Friendica doesn't use the correct profile photos if you have more than one profile

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1902]
If you have more than one profile with different profile photos friendica use the profile photo of the standard profile in most cases.

If you visit the the profile page of a friend the correct profile photo is used in the sidebar (except: the vcard of the photos and the videos page; and in the posts of the stream).

On the own page it always displays the standard profile photo (network stream; private Messages, contact page)

Wish:
If someone has the permission for an advanced profile of an user friendica should display the correct profile photo (of the advanced profile) everywhere

**Comment by annando** [comment]
I think the only way to make this work reliable would be to completely rework the way we transmit our profile. By now we do this in the feed that is available to the public as well. We would need some new message type (like Diaspora is doing).

I'm not sure if I really would like to do that in the near future.

**Comment by rabuzarus** [comment]
I don't know the best way how to realize this. But I think this should stay on the list of planned behavior (even if it's not the highest priority).

In my opinion the possibility of having different profiles are a very important one. It could be a very mighty feature but without federation (between friendica contacts) it has limited use

**Comment by AlfredSK** [comment]
I think this is outdated due to the changes to the user profiles. Should we close it?

**Comment by MrPetovan** [comment]
Closed as invalid by #8156
