### ISSUE TITLE
Friendica Homepage: link to addons.friendi.ca doesn't work

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1905]
At the bottom of http://friendica.com/extend is  a link to http://addons.friendi.ca/ . This link doesn't exist.

**Comment by tobiasd** [comment]
There should be a Wiki with a listing of all the Addons available, thanks for reporting!

**Comment by annando** [comment]
@tugelbend has moved the snarl.de to a new server. I guess this was forgotten.
