### ISSUE TITLE
Report invalid feed to the user when adding feed contact

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1913]
See https://github.com/annando/friendica/commit/7f8284eb1b2e77b0fd0b1ca77d9eba4c2ebda067#commitcomment-13493735

**Comment by tobiasd** [comment]
does this work now as expected?

**Comment by strk** [comment]
On October 31, 2015 9:41:37 PM CET, Tobias Diekershoff <notifications@github.com> wrote:
>does this work now as expected?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/friendica/friendica/issues/1913#issuecomment-152770650

Which branch should I check?

--strk;

Sent from device with lame keyboard. Please excuse my brevity.

**Comment by strk** [comment]
well, it's not fully clear what I was after, but adding as a contact an url which cannot be parsed as a valid one does give an error as of commit e1f3f2bc6c2ac819a4f2aa0221bc5fddb0d3780a
assuming done :)
