### ISSUE TITLE
scoop.it pages considered OStatus rather than Atom/RSS

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1914]
Adding this page as a contact considers it an OStatus, while it would be an Atom/RSS instead:
http://www.scoop.it/t/graffio/

Passing the rss directly works fine:
http://www.scoop.it/t/graffio/rss.xml

@annando can you check if it work with your  new code #1910 ?

**Comment by strk** [comment]
Besides, the malformed contact is still added and you never get to know that it was NOT a valid OStatus contact.

**Comment by annando** [comment]
This problem has nothing to do with my code. The problem lies in the detection routines when adding a contact. These routines need to be reworked as well. But this is another issue.

**Comment by annando** [comment]
I did a pull request: https://github.com/friendica/friendica/pull/1927

This won't fix your existing contact. But if you remove the contact and then you wait for more than a day (to avoid caching issues) you will be able to import this contact as feed again.

**Comment by strk** [comment]
@annando thank you!  It worked w/out having to wait a day :)
