### ISSUE TITLE
No mentions completion with visual editor

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1920]
I've recently switched to the "Visual Editor" (in order for the Firefox "post to friendica" addon to work) but doing it breaks the popup for mentions completion.

Can anyone else confirm ? This is with commit 2e8caf7f27197be5f12ea22f4a5e9aae2bb1ee89
in develop branch

**Comment by annando** [comment]
BTW: I would suggest using this one: https://activations.cdn.mozilla.net/de/diaspora.html - it is working with Friendica as well.

But: It really should work with the mentioning. It is working here as well.

**Comment by strk** [comment]
I'm using the Vier theme, in case that matters.
What are you using where it works ?

**Comment by rabuzarus** [comment]
I'dont think https://github.com/friendica/friendica/commit/2e8caf7f27197be5f12ea22f4a5e9aae2bb1ee89 could be cause.
BTW: In my Visual Editor the mentions didn't work at any time

**Comment by annando** [comment]
I just checked: It doesn't seem to work at my installation as well. I would suggest that someone with knowlege in JS should debug it.

**Comment by strk** [comment]
I found that mentions do work when written as the very first and only thing, but not after something is written before the mention (for example by sharing another post).

**Comment by tobiasd** [comment]
For me completion of @-mentions works in Firefox 42, both when creating a new posting of commenting to a thread.

But with current Chromium (46) I see the list of suggestions left aside the input box instead of below. There is no space for displaying the list, so only the scrollbar is shown.

**Comment by tobiasd** [comment]
Could you check if it is now working with current develop branch?

**Comment by tobiasd** [comment]
works for me now

**Comment by strk** [comment]
Works for me too now, thanks.
