### ISSUE TITLE
improve search to stop crawler

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1924]
@annando mentioned the existance of crawlers who followed every link in a very short time. As a consequence he blocked the access to the search function for not logged in users on his node.
So no one from other friendica nodes which visit this node can use the search (e.g. to follow tag links).

This should be solvable through a better implementation of the search function

**Comment by annando** [comment]
See this pull request: https://github.com/friendica/friendica/pull/1926

**Comment by rabuzarus** [comment]
fine

one note: what about making the time configurable? With a comment that 60s are recommended.
$a->config['system']['permit_crawling'] = 60

0 disables the config

PS: your to-do is very interesting ;-)

**Comment by tobiasd** [comment]
@rabuzarus there is something new for this in develop, what do you think can we close the issue?
