### ISSUE TITLE
UX: display nickname@hostname.com instead of the link to the profile

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#1925]
In many places (e.g. hover on left side contact block) the full address to the owner profile is displayed.
In the logic of friendica it should rather be nickname@hostname.com. This would be also better to remember (like emails). And to deal with friendica names could be as common as to deal with email addresses.

There is already a column 'addr' in the contact table of friendicas database. This could be used.

**Comment by annando** [comment]
When doing this we have to consider that not every contact has an address (for example RSS feeds)

**Comment by tobiasd** [comment]
In those cases the URL should be shown I think

**Comment by tugelbend** [comment]
The complexity of the task is higher than expected. Currently the idea is to query the gcontact table for the id of the posting user for every item and then to check if this has performance implications.

**Comment by annando** [comment]
I think we can close this issue now? The address is now shown at many places and is filled in the database as well.
