### ISSUE TITLE
vier: unable to load template file

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#1938]
Since the last changes to the vier theme I get an error on loading a template file.

replace_macros: Unable to load template file 'view/templates/theme_admin_settings.tpl'

This happens in the admin themes settings: <server>/admin/themes/vier
It happens also in admin site settings, system theme, link to change theme settings.

**Comment by annando** [comment]
Let me guess: "Vier" is not activated on your system? This, I haven't tested.

**Comment by AlfredSK** [comment]
Well, I use vier for my user accounts and as the system default theme but not for the admin account. The admin is using smoothly.
So, vier is activated but the admin doesn't use it.

**Comment by AlfredSK** [comment]
I just charged the user settings for my admin account. If the admin is using vier the error doesn't occur.

**Comment by annando** [comment]
Wait for pull request https://github.com/friendica/friendica/pull/1939 - then it will work with any theme.

**Comment by AlfredSK** [comment]
@annando Your fix works. :-) Thank you! 
The error message is gone but as you mentioned yourself - in pull request #1939 - it is not possible to change the theme settings if the admin himself is using a different theme.

**Comment by tobiasd** [comment]
created #2022 as a follow up issue for the remaining part, so I'm closing this one
