### ISSUE TITLE
invite fail

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1945]
url http://friendica.ml/invite

"Discúlpanos. Este sistema no está configurado actualmente para conectar con otros servidores públicos o invitar nuevos miembros."

:s

**Comment by annando** [comment]
Please go to the admin menu under http://friendica.ml/admin/site/

Once this is done it should work again.

**Comment by annando** [comment]
Does it work now?

**Comment by mama21mama** [comment]
work
