### ISSUE TITLE
Sharing events

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#1946]
Sharing events with Diaspora shows on Diaspora some html stuff like this:

    Starts: <abbr class="dtstart" title="2015-10-11T11:00:00">Sunday October 11, 2015 @ 11:00 AM</abbr>
    
    Location: <span class="location">Elisabethstr. 25, 24143 Kiel</span>
    
    <iframe src="https://pod.geraspora.de/camo/46a338a47274f62bbf007659dc9a119439d8dfb1/68747470733a2f2f7777772e6f70656e7374726565746d61702e6f72672f6578706f72742f656d6265642e68746d6c3f62626f783d31302e3133383938393725324335342e3330343638303925324331302e3135383938393725324335342e33323436383039266c617965723d6d61706e696b266d61726b65723d35342e3331343638303925324331302e31343839383937" style="width:100%; height:300px; border:1px solid #ccc"></iframe>

**Comment by annando** [comment]
Yeah, that's ugly and we have to fix it.

**Comment by annando** [comment]
This will be fixed with pull request https://github.com/friendica/friendica/pull/1966

**Comment by tobiasd** [comment]
can we close this issue?

**Comment by annando** [comment]
it should work well.
