### ISSUE TITLE
add support for attending an event for the supported themes

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#1953]
inherited from #1929 

the supported core themes need to be adjusted so users can attend to events

this will be blocking for the milestone

**Comment by tobiasd** [comment]
I think frost(-mobie) are the last ones, which need the functionality

**Comment by tobiasd** [comment]
Missing icons for frost/-mobile should be delivered by Wednesday by postal services. I guess we can close this issue after that.

**Comment by tobiasd** [comment]
missing icons for frost came with #2170

**Comment by fabrixxm** [comment]
and missing icons for frost 'desktop' with #2172 . can we close this?

**Comment by tobiasd** [comment]
yes, I think that all themes now support attending to events
