### ISSUE TITLE
mailstream doesn't send me activity from pumpio

### ISSUE THREAD

**Issue by sim6** [friendica/friendica#1967]

**Comment by annando** [comment]
There is no obvious reason why this could happen. Do pump.io posts arrive at all? Do you have a regular setup with a crontab and background processes? Or do you use something like proc_runner?

**Comment by sim6** [comment]
I don't have my own instance, I'm using friendica.eu. I recieve emails
of posts from ostatus contacts. I have posts from pumpio in my network
tab but I didn't receive the emails of those posts.

**Comment by tobiasd** [comment]
could not reproduce this on my node. I had to wait an eternity for a posting from pumpio but once it was there, I also got it via email.

**Comment by tobiasd** [comment]
Discussing this at Hackathon we had the idea that the messages might have ended up in SPAM filter maybe? @sim6

**Comment by tobiasd** [comment]
What is the status of this issue @sim6 ? If it still exist could you get in touch with the [support](https://friendica.eu/profile/support) account on frientica.eu; maybe it's a local problem?

**Comment by Keith2** [comment]
Could be a now fixed mail configuration issue, a new ipv6 address was added, enabled mailstream for myself and had undelivered emails, spf error for the new ipv6 address.

**Comment by sim6** [comment]
Today I'm receiving emails from identi.ca posts. Thanks!
