### ISSUE TITLE
Show less (like 10) recent postings on a profile on default, in the public view

### ISSUE THREAD

**Issue by DNS777** [friendica/friendica#1974]
Atm it is a bit too much to load for the public view of some profile pages, because of the amount of default postings. I'm using the vier theme.
So i suggest to reduce it to ~10, to make profile pages load faster.

**Comment by tobiasd** [comment]
You can set the limit at /settings/display for your stream. But you mean the default setting after installation right?

**Comment by DNS777** [comment]
Yes i mean the default setting, when somebody is not logged in and visits a profile.

**Comment by FlxAlbroscheit** [comment]
+1
Especially when visiting profile's on very slow instance's, a large amount of wall-thread's can lead to a bad UX or even freeze some people's browser for a certain time. Although there is a setting to handle this issue, only few people may will notice it. Btw, I suggest a default value of 10 - 15 wall-thread's.

**Comment by fabrixxm** [comment]
Fixed in develop
