### ISSUE TITLE
Image / File selector need better UI/UX

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#1992]
With current interface is not clear how to select images, how to upload new, is not possible to upload directly into an album, etc..

**Comment by tobiasd** [comment]
fixed in #2041

**Comment by fabrixxm** [comment]
> fixed in #2041

Well not really, as that commit just add some abstraction to allow themes to open the popup with different systems

This Issue is more related to the usability of the content of the dialog itself...

**Comment by fabrixxm** [comment]
moved to next milestone

**Comment by tobiasd** [comment]
@fabrixxm what is the status of this?

**Comment by fabrixxm** [comment]
dead

**Comment by tobiasd** [comment]
:-/ so we move it forward to the next milestone to revive it?

**Comment by foss-** [comment]
This is obsolete now that there is a drag and drop zone for image upload when composing a post.
