### ISSUE TITLE
Privacy Image Cache: Gifs are saved as JPGs

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#2008]
Privacy image cache seems to save Gifs as JPGs. This is especially annoying when adding external animated Gifs to a post.

**Comment by tobiasd** [comment]
could be a missing imagick package, IIRC that is needed for gifs.

**Comment by tugelbend** [comment]
I tried
```bash
sudo apt-get install php5-imagick
sudo service apache2 reload
```

The issue remains.

**Comment by tugelbend** [comment]
Additionally this happens when uploading gifs to friendica. Deactivating privacy image cache does not change that beaviour. I can reproduce this on snarl and on a fresh vagrant instance with imagick installed.

**Comment by tugelbend** [comment]
Found the issue: Restarting the webserver you are using (f.e. apache2 or php5-fpm) is mandatory after installing imagick and php5-imagick. Now things work as expected.
