### ISSUE TITLE
PHP Fatal error: Allowed memory size (poller)

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2012]
I got this message from the poller:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/virtual/ylms/social/include/ostatus.php on line 706

@annando asked me to create an issue, so I did. ;-)

Thanks for any fixes.
utzer

**Comment by fabrixxm** [comment]
could be related to #2038

**Comment by annando** [comment]
@ben-utzer Please check whether this error occurs with the current developer branch.

**Comment by ben-utzer** [comment]
Oh, I forgot to reply. 

As initially explained the problem occurred only a few times, I am on the dev branch, but maybe it was a temporary fault on my side, but also I do a daily git pull, so maybe the problem was fixed again the next day?

**Comment by annando** [comment]
Then I can close this issue?

**Comment by ben-utzer** [comment]
Yes, sorry, I'll close it.
