### ISSUE TITLE
feature request: option to not include content in the email notifications

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2017]
While you likely use https to read messages directed only to you and those messages could be stored only on trusted servers, the email notifications might transit on more untrusted servers and/or in clear-text.

This ticket is a request to add an option to exclude content from notifications, leaving them only to contain links to the trusted node holding the content.

**Comment by silke** [comment]
This exists already. Go to your_server/admin/site/ settings page, use the check box "Don't include post content in email notifications".

**Comment by strk** [comment]
On Sat, Nov 07, 2015 at 07:21:35AM -0800, Silke Meyer wrote:
> This exists already. Go to your_server/admin/site/ settings page, use the check box "Don't include post content in email notifications".

Thanks, but then it's per-node rather than per-user, while it
sounds it should be a user config.

--strk;
