### ISSUE TITLE
Ignore function should only block postings by ignored persons

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2028]
Actually nothing is delivered from an ignored person, also private messages and mentions aren't.
So I can send a private message to an ignored person - the ignored person can write and send an answer, but it will not be delivered. The delivery of private messages should be allowed.

Also comments by an ignored person on own postings and postings by an ignored person where I have been mentioned should be delivered.

**Comment by MrPetovan** [comment]
We aren't preventing delivery from ignored contacts anymore, just display. Closing as irrelevant.
