### ISSUE TITLE
Friendica making rapid API requests to GNUsocial instance

### ISSUE THREAD

**Issue by lo-windigo** [friendica/friendica#2038]
I run my own GNUsocial instance (http://micro.fragdev.com, running GNUsocial v1.2.0-dev), and our VPS has been seeing massive CPU spikes after several Friendica instances have began to send many API requests per second.

For example, here's a sample of the logs during one of these instances: 

```
93.196.103.202 - - [07/Nov/2015:16:34:06 -0500] "GET /api/statusnet/conversation/1445688.as?page=1325 HTTP/1.1" 200 6633 "-" "Friendica 'Lily of the valley' 3.4.3-dev-1190; https://f.diekershoff.de"
93.196.103.202 - - [07/Nov/2015:16:34:07 -0500] "GET /api/statusnet/conversation/1445688.as?page=1326 HTTP/1.1" 200 6633 "-" "Friendica 'Lily of the valley' 3.4.3-dev-1190; https://f.diekershoff.de"
93.196.103.202 - - [07/Nov/2015:16:34:08 -0500] "GET /api/statusnet/conversation/1445688.as?page=1327 HTTP/1.1" 200 6633 "-" "Friendica 'Lily of the valley' 3.4.3-dev-1190; https://f.diekershoff.de"
```

Here's another occurance, from a separate instance:

```
2607:f298:5:100b::53f:13e4 - - [07/Nov/2015:00:54:37 -0500] "GET /api/statusnet/conversation/1354461.as?page=8 HTTP/1.1" 200 2767 "-" "Friendica 'Lily of the valley' 3.4.2-1190; https://aegibson.me"
2607:f298:5:100b::53f:13e4 - - [07/Nov/2015:00:54:37 -0500] "GET /api/statusnet/conversation/1354461.as?page=9 HTTP/1.1" 200 2767 "-" "Friendica 'Lily of the valley' 3.4.2-1190; https://aegibson.me"
2607:f298:5:100b::53f:13e4 - - [07/Nov/2015:00:54:37 -0500] "GET /api/statusnet/conversation/1444467.as?page=43 HTTP/1.1" 200 22100 "-" "Friendica 'Lily of the valley' 3.4.2-1190; https://aegibson.me"
```

We have seen this behavior from multiple Friendica instances, run by separate people, and I don't think their intent is malicious.

It looks almost like Friendica is having trouble figuring out how many pages are in a conversation, and just infinitely looping until PHP times out.

**Comment by annando** [comment]
Yeah, it should detect whether a conversation has come to an end. I have tested this behaviour with my two servers (and several others). Maybe the current GNU Social server behaves different in this case.

You are lucky. We currently are at our hackathon, so I really have time for a look at it.

**Comment by annando** [comment]
I just tested. It seems to be a paging issue at GNU Social. Just have a look at this content:
http://micro.fragdev.com/main/public?page=1

And then have a look at this content:
http://micro.fragdev.com/main/public?page=2

The paging doesn't work any more as expected. I will see if I could make some loop protection. But the source of the problem is the GNU Social code.

**Comment by lo-windigo** [comment]
@annando Sure, but Friendica isn't using the web interface - it's polling the API, right?

It doesn't look like the API supports pagination to begin with; I'm still digging through my instance to see if I can prove myself wrong.

**Comment by annando** [comment]
The API supported pagination in the past. So I guess there is an issue with the pagination in general.

**Comment by lo-windigo** [comment]
I'm a few versions behind on GNUsocial (need to migrate to a server with a higher supported PHP verison), so I'll close this for now and see if the behavior reoccurs in the future.

Thanks for your help; hope your hackathon goes well! :)

**Comment by annando** [comment]
@lo-windigo We made a change to avoid this problem with your server. But like you said in the thread: you did some change to the nginx configuration. I really think it is based upon that.

Just to show what I mean.

Take this conversation on one of my servers:
https://status.pirati.ca/api/statusnet/conversation/1442261.as?page=1

Then take the second page:
https://status.pirati.ca/api/statusnet/conversation/1442261.as?page=2

Then the third one:
https://status.pirati.ca/api/statusnet/conversation/1442261.as?page=3

Then see your system:
http://micro.fragdev.com/api/statusnet/conversation/1446212.as?page=1

And compare it with the second page:
http://micro.fragdev.com/api/statusnet/conversation/1446212.as?page=2

On your system it doesn't matter which page number you chose. On any other GNU Social/Statusnet system you can switch the page numbers with this.
