### ISSUE TITLE
duepuntozero theme misplaces site logo

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2051]
See attachment
![duepuntozero](https://cloud.githubusercontent.com/assets/289678/11021330/7414e07c-863e-11e5-87b9-da289464988d.png)

**Comment by fabrixxm** [comment]
admin can write any html in "banner" settings. It's up to the admin to be sure that it works with enabled themes.

I'm closing this.

**Comment by strk** [comment]
I wrote no HTML, only specified an url to the logo and the name of the site.
Same with other themes which work nicely (resizing the logo and text if needed).

**Comment by fabrixxm** [comment]
where? in `admin/site/`, field "Banner/Logo" ?

**Comment by strk** [comment]
Uhm, I now see that field is filled, but I don't remember having
filled it myself, could it have been defined by the theme itself
by only filling some other field (Site name and Shortcut icon,
for example) ?

How would I know about the "id" to assign to the tags, otherwise ?

Now I tried blanking that field and indeed on "save" it gets
re-filled with a default HTML. The default icon is a 32x32 pixels
image but the default HTML does not include the icon size.

I confirm that adding an `height="32"` attribute to the `img` tag
fixes the display for me.

Could the default HTML include an `height="32"` attribute, so that
people like me (who just modify the default HTML) would know what's
the expected size to avoid breaking the UI ?

Even better it would be if "duepuntozero" would adapt to the banner,
rather than rendering _over_ it.
