### ISSUE TITLE
vier menu disappeares on android tablets in develop branch

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2057]
menu in vier fully disappears on the network tab on android tablets and it's not possible to switch to another theme, because the display menu entry disappeared from the the settings menu.

**Comment by annando** [comment]
I guess we can close this issue now? it should work like a charm now.

**Comment by rebeka-catalina** [comment]
Also the menu entry for display in the settings menu got fixed ?

**Comment by rebeka-catalina** [comment]
Yes, you were right - everything is fine :-)
