### ISSUE TITLE
Problem with profile picture or small avatar pictures

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2058]
I discoverd a problem with my profile picture. All of a sudden an old picture of me reappeared as avatar on the top navigation pane and in the top left corner of my posts. The profile picture itself is still up to date and okay.

If I change my profile picture only the big one on my profile page gets updated. The other appearances of the profile picture are not updated. A flush of the browser cache doesn't work.

I'm on version 3.4.3-dev with vier.

**Comment by annando** [comment]
There seems to be some issues with avatars and names. I will investigate.

**Comment by AlfredSK** [comment]
I think this issue is fixed by #2073 . If no further testing is necessary this issue can be closed.
