### ISSUE TITLE
No feedback message or forwarding to login after successful registration

### ISSUE THREAD

**Issue by oliverjkb** [friendica/friendica#2060]
as discussed with @annando at the Berlin Hackathon ;)

## Issue
When trying to register a user account messages will be displayed for errors during registration. 
On succcessful registration no message is displayed, nor will the user be forwarded to the login page.

## Steps to recreate error: 
Set up new friendica node from develop branch, register new account.
Type wrong email or the like. -> Message alert.
Type correct user information. -> No Message, no Forwarding.

## Expected behavior:
When entering correct user information and account can be created, users should also receive a feedback message. 
Additionally a nice-to-have would be, to forward the user to login.

**Comment by annando** [comment]
This issue occurred in situations when a password was provided during the registration process. See pull request https://github.com/friendica/friendica/issues/2076 for further explanations.
