### ISSUE TITLE
Failing constant with posix_kill()

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#2063]
From #friendica IRC channel

> 13:01:33 - ToeiRei: poller.php triggers an error/warning - pidfile.php bails out on posix_kill()
> 13:02:00 - ToeiRei: the actual message is: Warning: posix_kill() expects parameter 2 to be long, string given in include/pidfile.php on line 38
> 13:02:22 - ToeiRei: That line reads as follows: return(posix_kill(file_get_contents($this->_file), SIGTERM));
> 13:03:01 - strk: SIGTERM not recognized as a constant ?
> 13:03:06 - ToeiRei: the PCNTL constant causes the problem here, as far as I can see. Changed it to: return(posix_kill(file_get_contents($this->_file), 15));
> 13:03:12 - ToeiRei: et voila.
> 13:03:21 - ToeiRei: yup, strk. you nailed it
> 13:03:22 - strk: which php version ?
> 13:03:35 - ToeiRei: tried it on 5.5 and 5.6
> 13:03:58 - ToeiRei: 5.5.30 and 5.6.15-r2 to be exact
> 13:05:17 - ToeiRei: I got an idea about php itself, as I might not have the pcntl use-flag set.
> 13:09:14 - ToeiRei: I suspect that's it
> 14:18:01 - fabrixxm: I think that having 15 in code is better, maybe with a comment on the side to tell what 15 is

see also http://my.stargazer.at/2015/11/10/friendica-troubleshooting-poller-php/

**Comment by tobiasd** [comment]
What about convertign the constant to a numeral "just in case"; thus keeping the readability of the constant name.

**Comment by annando** [comment]
I would like to see the content of the constant SIGTERM on that system.

**Comment by annando** [comment]
The warning occurs when this extension isn't enabled at PHP: php.net/manual/en/pcntl.installation.php

I would vote for closing the issue.

**Comment by fabrixxm** [comment]
Shouldn't the install wizard check for this extension?
Is the extension essential or are we using it only for constants?
if is the last case, we could add some conditional define() in boot.php, like
```php
if !defined("SIGKILL") define("SIGKILL", 15); 
```
or we can use our constants like
```php
define("F_SIGKILL", 15); 
```
this way the extension is optional, the code works with constants, which is more clear to read, and there aren't chlashes in constants definition if the extension is enabled...

**Comment by annando** [comment]
I would prefer the first solution. That means definition of the constant only if it is not available. This is the cleanest way.

**Comment by annando** [comment]
Pull request is done.
