### ISSUE TITLE
Requirements outdated

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [friendica/friendica#2066]
In install.txt it says 5.2+ will do well except for some fancy stuff, but that is wrong.

I just tried to install on 5.2.6 and it gives a FATAL ERROR:

PHP Parse error:  syntax error, unexpected T_FUNCTION in include/html2bbcode.php on line 92

Its an anonymous function there that was added in php 5.3, so 5.3 is minimum.

Cheers,
Chris

**Comment by fabrixxm** [comment]
fixed in develop
