### ISSUE TITLE
TypeError: $(...).colorbox is not a function

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2078]
In the current develop branch I'm getting the error ````TypeError: $(...).colorbox is not a function````

The origin is this here:
https://github.com/friendica/friendica/blob/develop/js/main.js#L143

It happens on many pages but not on the network page.

**Comment by fabrixxm** [comment]
I can't reproduce this. Is still an issue for you?

**Comment by annando** [comment]
I have the feeling that the XMPP addon could be the origin of the problem.

**Comment by annando** [comment]
I haven't had this issue for a longer time. So I'm closing it now.
