### ISSUE TITLE
Post privacy settings ignored when posting from a social API client

### ISSUE THREAD

**Issue by gvansanden** [friendica/friendica#2084]
I set my settings so that by default new posts are shared with one group only, this works perfect in the Web GUI, but I added my account in AndStatus on Android using the Statusnet API.

Posts made from AndStatus are publicly visible to everybody, this is a privacy risk when users don't realize this will be the case.

I think posts from clients should follow the user preference for sharing.

**Comment by annando** [comment]
In fact the API do respect the default privacy settings that you did in the settings.

**Comment by gvansanden** [comment]
Hmm, you are correct.  It seems my privacy settings where not saved...  It does work now.  Sorry
