### ISSUE TITLE
own posts should not be notified

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2091]
It's annoying to receive a notification for own posts. You post something and get a "Hey, a new message was posted!". Really ? Doh !

I guess I'm in a good position to fix this myself, having it looked at how notifications are generated (by ping.php). But maybe (hopefully?) someone will beat me to this :)

**Comment by tobiasd** [comment]
duplicate of #1032 I think

**Comment by strk** [comment]
confirmed, better handled in #1032
