### ISSUE TITLE
Auto-mention forums does not work from a user created group context

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2093]
Forums are not auto-mentioned with the rich-text editor.

**Comment by tobiasd** [comment]
Can you specify how you expected them to be mentioned?

I've just tried for myself. On the network tab, click in the collapsed editor box, then selected a forum in the ACL and the @name was inserted at the end of the text.

**Comment by strk** [comment]
what you describe is what I'd expect. now I tried again and it still doesn't work with "rich-text" editor disabled, but I'm sure it worked with non-rich editor before I filed this, so must be something else, unrelated to the kind of editor.

**Comment by tobiasd** [comment]
It works for me with and without the rich-text editor... mmh... but you have enabled the feature to auto-mention forums? Just to make sure ;-)

**Comment by strk** [comment]
yes, the feature is enabled, or it would never work..

**Comment by strk** [comment]
ok, from Home it works, from Network it does not.
When starting the post from the Network tab it starts with a pre-filled ACL, not sure if that's what makes a difference.

**Comment by strk** [comment]
It works from the Network tab while watching post from the built-in/special group "Everybody", not while watching posts from a specific group.

**Comment by tobiasd** [comment]
confirmed, when in a user created group of contacts, the auto-mention does not seem to work.

**Comment by tobiasd** [comment]
There is now a potential fix in develop, could you check if it is working now for you?

**Comment by strk** [comment]
Still fails for me as of commit c50b49d303aec426ad14eac470c212f96887d8a1 (with Vier)

**Comment by strk** [comment]
Still fails as of 748d0e576c5b2b1247a9dd2d159ef3230d7562ad
