### ISSUE TITLE
vier: too much community profiles in the right sidebar

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2122]
The widget Community Profiles of  the new right sidebar of the vier theme should only show 9 suggestions but on my instance it shows 10 profile suggestions. Additionally the Help Widget don't appear in a new line.
![vier-community-profile](https://cloud.githubusercontent.com/assets/3750381/11462579/9d4a44b2-9716-11e5-87ef-ad5cc56aab91.jpeg)

**Comment by rabuzarus** [comment]
can we tag this for 3.4.3? It isn't a showstopper but should be resolved before the release since it's a bug which is noticeable for every user on the first view

**Comment by annando** [comment]
See pull request https://github.com/friendica/friendica/pull/2147

**Comment by tobiasd** [comment]
seems to work now, so I'll close the issue
