### ISSUE TITLE
vier : different forum list results on the left and on the right

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2165]
![forumlist_comparison_left_right](https://cloud.githubusercontent.com/assets/7385838/11714783/ea5de05a-9f3c-11e5-926a-62ad38eb58dd.png)

I've taken screenshots of the two situation and put them into one file, that you can better see, what I mean. 

If my browser is big enough, that the left-menu doesn't appear and the forum list appears on the right, then the entry of ux watchdogs is missing. When my browser is small enough, that the menu on the left appears and the forum list gets displayed in that menu, the entry is shown.

**Comment by rabuzarus** [comment]
Can please test with 3.4.3rc. The forum widget was included in core. Now both widget should use nearly the same code

**Comment by rebeka-catalina** [comment]
Now the the item is missing on both sides and the icons are much bigger - 
doesn't look very nice with these huge icons I think.

**Comment by rabuzarus** [comment]
strange, since it uses the same query like the original addon

**Comment by rebeka-catalina** [comment]
Maybe, but ...
![forum_list_left-rc](https://cloud.githubusercontent.com/assets/7385838/11721897/6880e9ae-9f66-11e5-8bf9-41f7887465b4.png)
... this is how it's looking now after switching to 3.4.3-rc :-/

**Comment by rebeka-catalina** [comment]
Same in here : I'm pretty sure, that it wasn't caused by friedica - 
Yesterday evening I've seen that our node's filesystem was fully in use. I deleted some unneede stuff and this morning the forum list appeared as it should, so the problem seems solved.
