### ISSUE TITLE
Stream is not filtered correctly in groups   3.4.3-rc

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2177]
Since the friendica hackathon this year the node has been on develop branch and since one day after the hackathon I didn't pull new stuff from github. 
3 days ago I've pulled the actual stuff and switched to the 3.4.3-rc branch because of #2165  and since that day I've got the problem, that postings are not filtered correctly. 
I've created two groups A and B and I used to be in group B to filter out the contents from group A, but since I switched to the rc-branch I get postings from group A displayed in group B.
At first I checked the memberships of the several groups again in the settings, but everything was fine. 
It does not happen permanently, but quite often.
Until today I've counted postings from 6 different contacts, whom aren't in group B.

**Comment by rebeka-catalina** [comment]
It always happens, when a posting in group A get's commented or liked - not by publishing.

**Comment by rebeka-catalina** [comment]
Oh perhaps it was not caused by friendica - the filesystem of our node was fully in use yesterday evening. I think this is the reason for this strange behavior and some other problems which appeared the last days.

**Comment by annando** [comment]
Is this still an issue?

**Comment by rebeka-catalina** [comment]
It is.
I can describe a bit exactlier now:

There is group-A  and group-B.

Let's say, there is a person XYZ in group-A and you are in both - group-A and group-B.

I used to be the most time in group-B to filter out group-B. Now you see a posting by person XYZ and comment it. There is the mechanism in friendica, which brings postings up to the top when activity happens and the combination : you as member of group-B and that mechnism brings me up a posting by a person from group-A directly into group-B and breaks my filter.
