### ISSUE TITLE
vier: missing icons

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2182]
Some icons don't appear in vier right-sidebar service widget
![missing-icons](https://cloud.githubusercontent.com/assets/3750381/11780789/e7762b6a-a264-11e5-90e5-f156408f7594.jpeg)

3.4.3-rc

**Comment by tobiasd** [comment]
Those are missing addon related icons right?

**Comment by annando** [comment]
BTW: This is depending on the webserver configuration. Under certain circumstances you can leave out the file extension. But of course it is better to leave it.

**Comment by tobiasd** [comment]
so we can close this?
