### ISSUE TITLE
manage: automatic switch to the former account on page reload

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2184]
I have several delegations. If I switch to an account to witch I have delegetion rights and swith back to my account it switches back to the delegated account when the page reloads.

I haven't find out under witch conditions this bug appears.
With accounts which are connected trough the same email address this won't happen.
Short after the account switch I can use all links of the top nav bar but with the automatic page reload (or after pressing F5) it switches back to the former account (the one for which I have delegation rights)

Friendica 3.4.3-rc

**Comment by tobiasd** [comment]
could be related to #1241

**Comment by annando** [comment]
I guess this is some cookie stuff.

**Comment by rabuzarus** [comment]
maybe. yesterday the bug didn't happen.
I wait some days and will close it if it don't appear anymore.

**Comment by annando** [comment]
This issue happens when you opened a friendica site in several browser tabs.

**Comment by rabuzarus** [comment]
the issue seems really to be gone

I close this issue
