### ISSUE TITLE
doc/settings.md is unclear

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#2194]
make sure that the documentation in doc/settings.md file is up to date and not confusing as the settings from the admin panel might override the settings mentioned there.

part of #1478

**Comment by tobiasd** [comment]
Some notes about this

* do you need the admin panel at all? or can you, never ever touching the panel, do all configuration with .htconfig like it was before the admin panel got there?
* what has to be configured within the admin panel?
* what has to be configured in .htconfog? [these two points should be clearly be separated from each other]

**Comment by annando** [comment]
The settings that are done in the admin panel always override the settings in the .htconfig.php.

I think that every *stable* stuff has to be configurable from the admin panel and only experimental or debugging stuff should be made in the .htconfig.php

**Comment by tobiasd** [comment]
> I think that every stable stuff has to be configurable from the admin panel and only experimental or debugging stuff should be made in the .htconfig.php

*has to be configurable* yes, but does it have to?. Say after installation one erases the configuration for the admin account from the htconfig and never touch the admin panel  - then you still can do all the configuration from the config file.

**Comment by fabrixxm** [comment]
> has to be configurable yes, but does it have to?. Say after installation one erases the configuration for the admin account from the htconfig and never touch the admin panel - then you still can do all the configuration from the config file.

how you decide which one has priority?

**Comment by annando** [comment]
I have to precise myself. The whole config stuff is a little bit confusing. The .htconfig.php seems to override the settings that are changed via admin panel - but not if "load_config" was called - which is (hopefully) called with every backend and frontend call for the "system" and "config" family.

So the situation is: An admin changes stuff in the .htconfig.php. Then - after some time - the admin does a change in the panel. After that time *every* setting that is reachable in the panel (at that time) overrides the .htconfig.php. If after an update there are additional settings in the panel but the user never changes them from there, then these settings can still be changed via .htconfig.php - but only if the admin never ever changes *any* value in the panel again.

This means: You cannot configure a friendica installation reliable only from the .htconfig.php

**Comment by tobiasd** [comment]
Not even if you **never** (like in never ever) touch the admin panel? Don't configure an admin account, don't reach the panel. That was the initial scenario.

Once the panel is touched, one has to use it. That is ok, but was not the question for the documentation.

**Comment by annando** [comment]
We shouldn't make it too complicate. I bet that this will create confusion. We really should remove all settings from the documentation that can be set via the panel.

**Comment by tobiasd** [comment]
I think it would be sufficient enough to make a clear distinction. Make it clear that the panel is the usual way to do the configuration and have the no panel option mentioned as second case for people who don't use UIs for config.

Nothing complicated there. You are a normal user - here is how configuration works. Use the Admin panel, the important screws are the following...

And if this works (the question is still open) then mention the pure possibility that one can do the configuration over the htconfig file, but only if **XYZ** and once you have touched the panel, you are bound to the panel.

In either case, the template for the htconfig file needs to make clear which settings will be overruled by settings from the admin panel but are in the template to give reasonable values for initialization.

**Comment by annando** [comment]
Why should someone not use the admin panel? I really think that this is a total special case - especially since it cannot easily made undone if you had done a change from the panel once.

**Comment by tobiasd** [comment]
> Why would someone not use the admin panel?

Because *it is possible* ;-)

**Comment by annando** [comment]
Do we want to describe every possible (and sometimes unintended) side effect? There is no good reason to use it this way, I think.

**Comment by tobiasd** [comment]
Then I would say, remove all the ''''$a->...'''' stuff from the docs, except for the ones that need to be set in the htconfig file and make a clear separation (in the docs and the htconfig) of the parameters configurable in the panel and not.

**Comment by annando** [comment]
Sounds good for me.

**Comment by tobiasd** [comment]
Just so it is noted here as well, the German translation of doc/Settings.md needs to be updated as well. I think then we can close the issue.

**Comment by annando** [comment]
I'm okay with that.

**Comment by tobiasd** [comment]
German translation is merged, so I'll close this issue. Further enhancements are welcome nevertheless ;-)
