### ISSUE TITLE
bbcode to markdown conversion fails for size=xx-large

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2199]
The conversion of bbcode [size=xx-large] to Diasporas markdown fails. On Diaspora the posting looks like this...
`<span style="font-size: xx-large; line-height: initial;">Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears,
I’ll give it to someone special</span>`
I used a combination of "bold" and "size" [b][size=xx-large]...[/size][/b].

**Comment by AlfredSK** [comment]
Related... #4445

**Comment by MrPetovan** [comment]
Closed via #7601
