### ISSUE TITLE
Notifications have problems with < and > in author name

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2229]
I have a user in my contact list who has "<" and ">" in his user name. The notifications are looking this way:

![bildschirmfoto 2015-12-31 um 14 40 46](https://cloud.githubusercontent.com/assets/844208/12064805/a89192c0-afcc-11e5-869e-63f25cb21f60.png)

The XML that is generated by mod/ping.php is looking valid. So I think the JS part that reads from there must be adjusted.

**Comment by tobiasd** [comment]
There seems to be a regression for this problem

**Comment by tobiasd** [comment]
This is working again.
