### ISSUE TITLE
twidere issue

### ISSUE THREAD

**Issue by osakaleland** [friendica/friendica#2230]
twidere 0.3.0-dev-135
Friendica (master branch) installed yesterday
twitter plugin

I am using the twitter plugin to aggragate my twitter feeds into friendica/ post to twitter from friendica. I made a test post from friendica to twitter and it worked great.

When I added friendica to twidere (https://social.*****.com/api) it download all of my friendica posts ( including those aggragated by the twitter plugin) but would not download any new ones after that. I manually reloaded, reinstalled twidere, tried different versions of twidere - but no new posts from friendica are downloading.

To restate: twidere connected to friendica and downloaded posts but will not download any new posts. After reinstalling twidere: no posts have downloaded.

I have tested with Andstatus and all of my friendica posts are being downloaded.

**Comment by osakaleland** [comment]
Has anyone else confirmed this? Twidere has now started working again - neither twidere or Friendica has been updated. The only change is that I updated my server to debian testing and rebooted.

**Comment by annando** [comment]
Sometimes I'm having similar problems. I'm not sure where it comes from. I have to investigate if Twidere is sending API commands we don't support or that we support only halfway.

**Comment by annando** [comment]
I'm still unsure if this could be a twidere issue. I guess we have to check together with @mariotaku

**Comment by mariotaku** [comment]
@osakaleland 135 build is too old, use newest builds instead. Also next release will be improve a lot.

**Comment by annando** [comment]
Current versions of twidere really are improved a lot. Additionally from my side it looked like a problem in twidere - not in Friendica. I would like to close this issue.

**Comment by annando** [comment]
Does anyone disagree?

**Comment by mariotaku** [comment]
@annando Is it work on Twidere now?

**Comment by annando** [comment]
I'm currently using 3.1.1.5 and the timeline seems to load reliable. Old versions often had some hiccups where the loading stopped. This doesn't seem to occur anymore. I'm just waiting for some reports of other users before closing this issue.

**Comment by annando** [comment]
It really works totally flawless. I close this issue. If someone still has an issue with Twidere, we can reopen this issue.
