### ISSUE TITLE
Relocating the server does not update all information

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#2247]
I've done a fresh test installation in my LAN (IP based) and later set up reverse proxy to an external resolvable name. After the proxy was in place I used the "Relocate" functionality in the admin panel to "move" the node from the "IP address" to the "name".

This seem to have worked fine (I could connect and communicate from/with an external nodes) but locally, looking at the profile the address is still shown as nickname@local-ip-address; connections made after the move are showing the correct information on the other nodes.

**Comment by annando** [comment]
Please have a look at all the data fields that are still needed to be updated.

**Comment by tobiasd** [comment]
That is the one I observed, give me a list of all and I'll check ;-)

**Comment by annando** [comment]
Have a look at the fields in the profile table, the gcontact table and the contact table.

**Comment by tobiasd** [comment]
profile looks good, but gcontact does not seem to be touched by the relocate function at all.

**Comment by annando** [comment]
My pull request https://github.com/friendica/friendica/pull/2244 already contains code for this:
https://github.com/friendica/friendica/pull/2244/files#diff-193500fd936e6e8fcd31e1020682ba20R344

When you or @fabrixxm accepted it, you can test it again.

**Comment by fabrixxm** [comment]
I want to take a look at your PR, @annando .. it will take some time :-)

**Comment by annando** [comment]
These few lines? :-)

**Comment by tobiasd** [comment]
2 more entries in gcontact were created for the account on the node it seems and using the relocate function seems not to have any effect anymore. I tried to switch back to the IP number, but it remains with the url. Also the protocol in url seems to be wrong, as the node does not have an https access but in the url it is listed with https.

**Comment by annando** [comment]
Can we close this issue now?

**Comment by tobiasd** [comment]
I was not able to test it again so far ;-)

**Comment by tobiasd** [comment]
I have relocated my test server successfully recently, from one subdomain to another, but there might be problems from a subdirectory installation to a subdomain.

**Comment by annando** [comment]
Is there any data that could be analysed? Means: how is the contact entry and the gcontact entry looking? Which fields are looking bad? if we have that data we can search for the problem. Otherwise we also could close this issue.

**Comment by tobiasd** [comment]
I will test it hopefully this weekend

**Comment by tobiasd** [comment]
Ok, I relocatec a fresh installation from IP/friendica to something.example.com the entries in `contact` was updated correctly, `gcontact` was empty (fresh install, one admin account, no contacts).

The following configuration is not updated in `config` table automatically when relocating
> system->url
> config->->hostname

as well as the tmp directory names should they contain the domain name.

Also, as expected, relocating from the sub-directory needs manual editing of the `.htconfig.php` file to remove the `$a->path` configuration (just noting it here for later reference)..

**Comment by tobiasd** [comment]
Similar problem I think, hence writing it down here. When importing an account, the old webfinger is displayed in the vcard.

**Comment by annando** [comment]
From my understanding this issue should be solved. See the linked PR.

**Comment by tobiasd** [comment]
I have too few spare server at hand to test this at the moment. But I can try to setup the scenario again that initially had the problem.

**Comment by annando** [comment]
The last reported problem was with the import of a single account. This could be tested together with https://github.com/friendica/friendica/issues/4396

**Comment by annando** [comment]
According to https://github.com/friendica/friendica/issues/4396#issuecomment-366706702 and https://github.com/friendica/friendica/issues/4396#issuecomment-366718694 it is working as expected.

**Comment by tobiasd** [comment]
ok :-) closing this

**Comment by tobiasd** [comment]
Reopening this after a [user reported problems](https://forum.friendi.ca/display/39bbe52a175a9bf357473f1932229532). We needs at least to test this again.

**Comment by annando** [comment]
I guess that there could be the special situation that forums don't recognise the "relocation" message. But everything else should work.

**Comment by tobiasd** [comment]
See [this forum entry](https://forum.friendi.ca/display/0b6b25a8135aabc37a5a0f5684081633) for some testing. The relocation needs some work.

**Comment by annando** [comment]
I guess I finally found the reason for the problems. We have the "New base url" setting at the bottom, which sends the relocation message and does some more stuff - the only thing that it doesn't do is to set the hostname. This is done in the setting "Host name" on the same page ...

Could someone check if changing both values does solve the problem?
