### ISSUE TITLE
Move http://dir-fc.oscp.info/health from experimental to stable and use it as entry point for new users

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#2311]
Friendica lacks a good entry point for new users and makes it very hard to find healthy, free for all to sign up, instances.
This is imo the biggest blocker for broader user adaption of friendica so I would consider this a high priority item.

http://dir-fc.oscp.info/health exists but is still "experimental".
http://friendi.ca/ links to that location

Ideally both http://friendi.ca/ and http://friendica.com/ would list open instances on their front pages so that new users easily have a sign up option. I understand that many instances are desired but not everybody is a sys admin and for most people it is even a bad idea to tap into that space. Setting up such an instance is not trivial. So the majority of visitors should be addressed and given an easy join option.

**Comment by tomas-nz** [comment]
Possibly related: I noticed that when I go to my profile page (while I am logged out) and click Connect, I get into "Friend/Connection Request" page. There is a link "follow this link to find a public Friendica site and join us today" pointing by default to http://dir.friendi.ca/siteinfo - When you go to this page, it is almost empty. If you have any control over friendi.ca site, could you organize to point that page to your new list, please?

Btw, I find your new list very helpful. It is really off-putting and hard to pick a sensible option from the list at http://dir.friendica.com/siteinfo

**Comment by Beanow** [comment]
Perhaps http://dir-fc.oscp.info/servers is more the style of listing you mean?
It's the same data as http://dir-fc.oscp.info/health but aimed at users wanting to sign up.

Source in https://github.com/Beanow/dir/tree/feature/redesign-prototype
Improved later by https://github.com/tugelbend/dir/tree/feature/redesign-prototype

**Comment by tobiasd** [comment]
> We have https://dir.friendica.social/servers now.

That does not display the health of a node. Here an example https://dir.friendica.social/health/16 but I think there is missing a graph (at least in Vivaldi for me) that displayed some health-statistics in a nicer way then write it doen.

**Comment by MrPetovan** [comment]
The heart actually change color depending on the health. There just aren't that many public servers and all are healthy.

**Comment by tobiasd** [comment]
How often is that health test done? I found only nodes with data 120 days old.

**Comment by AlfredSK** [comment]
Sometimes all hearts are green and sometimes all hearts are red. I can't remember I ever saw a mixture of both. I think the speed of the directory server during the measuring determines the color. :-)

**Comment by MrPetovan** [comment]
Given the amount of PHP Notice Errors I'm getting from the directory maintain cronjob about the site health, I'd say often but it probably is for different servers 😅

**Comment by AlfredSK** [comment]
Btw. my server and some others are showing "HTTPS + 1 other" on https://dir.friendica.social/servers. That's not right. Shall I open an issue?

**Comment by MrPetovan** [comment]
Yeah, sure.

**Comment by foss-** [comment]
Guess this can be closed. Below some minor observations. Maybe someone wants to tackle them?

1. text "Try It"
http://friendi.ca/ has "Try it" at the top which goes to https://dir.friendica.social/servers.Not sure if "Try it" is a good wording. May sound like users may be looking at a demo. But it's not a demo, it's a real user profile created on a real instance. Maybe "Sign Up Now" or "Join Now" is better?

![bildschirmfoto](https://user-images.githubusercontent.com/5708172/36631053-762f541e-1971-11e8-8a5a-dbeadf1bbed9.png)

2. text on server list page
Regarding https://dir.friendica.social/servers:

**Currently**

Public servers

If you are not interested in hosting your own server, you can still use Friendica. Here are some public server run by enthusiasts that you can join. We recommend these based on their health.

Keep in mind that different servers may support different features like communicating with additional networks besides Friendica. It's best to pick the one that best suits your needs. 

Button: "Surprise me »"

**Proposed**

Public servers open for sign up:

Text imo not needed. The titel includes that the servers are public and that they are open for sign up. Users going to the sign up option from the main friendica website are obviously not interested in hosting their own instance so I see no need to link to self-hosting installation instructions. It feels like the wrong place for that.

Button: Sign up now (random server will be selected for you)
text in bracket could be smaller and in a second row.

Recommending 11 public servers ← remove
no need to repeat that info. Obviously the servers on the list are recommended, otherwise they would not be on the list and the fact they are public is mentioned in the new headline already.

What do you think?

**Comment by MrPetovan** [comment]
Who has write access to the Friendica website? @annando Maybe its code should be in a repo on GitHub as well so that anyone can push a PR.

**Comment by tobiasd** [comment]
> Who has write access to the Friendica website? @annando Maybe its
> code should be in a repo on GitHub as well so that anyone can push a
> PR.

It is a Wordpress page and you have an account there.

**Comment by MrPetovan** [comment]
That's good to know, thanks, but I don't want to make unilateral changes, does anyone else agree with the changes suggested by @foss- ?

**Comment by tobiasd** [comment]
> does anyone else agree with the changes

I think that page is missing the information why it lists these nodes. If you look at the-federation.info it lists many more nodes with open sign-up. So I would not simple remove the header, but replace it with the information why only these 11. Which is the estimated server health IIRC. It would also be nice, if the heart could be made into a link to the respective health page for that node.

**Comment by AlfredSK** [comment]
Is this still an issue? Since the directory shows the health status and take it into account for sorting the recommended servers. Also, that URL doesn't exist anymore. Closing?

**Comment by MrPetovan** [comment]
Closed as invalid by https://github.com/friendica/friendica-directory
