### ISSUE TITLE
Move div#pause to default.php

### ISSUE THREAD

**Issue by stieben** [friendica/friendica#2320]
I noticed [the following line](https://github.com/friendica/friendica/blob/master/index.php#L416) inside of **/index.php**:

`$a->page['content'] .=  '<div id="pause"></div>';`

Is there a reason this div can't be put into **/view/default.php**?

I stumbled upon this when thinking about a theme adding Ajax content that would always have this _pause div_, a rather undesired effect. What is it for, anyway?

**Comment by rabuzarus** [comment]
> What is it for, anyway?

https://github.com/friendica/friendica/blob/master/doc/Settings.md
> [Pause] - Pauses "Ajax" update activity. This is the process that provides updates without reloading the page. You may wish to pause it to reduce network usage and/or as a debugging aid for javascript developers. A pause indicator will appear at the lower right hand corner of the page. Hit the [pause] key once again to resume.

**Comment by fabrixxm** [comment]
:+1:

**Comment by tobiasd** [comment]
I think we can close this issue--right?

**Comment by stieben** [comment]
Yeah, but it would have been auto-closed, anyway.
