### ISSUE TITLE
Show Ascii-Code for Emoticon on Mouseover

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#2330]
Sometimes when I see an emoticon in a post, I wonder how to add it to my posts. Would be great to see ascii-code of that emoticon when placing the mouse over the image. As the code is already in the alt-tag, this should be easy. It works on other icons already.

**Comment by tobiasd** [comment]
In the mean time, you can always have a look at $yournode/smilies to see a list of emoticons supported by your node.

**Comment by MrPetovan** [comment]
Related to #3641

Is this fixed, can we close it?

**Comment by tobiasd** [comment]
> Is this fixed, can we close it?

It is fixed when you use my emojione addon, don't know other cases ;-) What happens when you mouse-over an emoji in your timeline? Is the alt-text set for it so the browser show it.

**Comment by MrPetovan** [comment]
Nothing shows with Unicode emojis as expected, and I'm never using smileys, although I activated a couple addons to display them.

**Comment by MrPetovan** [comment]
The ASCII code shows as a tooltip on custom emojis now.
