### ISSUE TITLE
Smiley Pack 1.04: some smiley keywords aren't replaced correctly

### ISSUE THREAD

**Issue by RuJo09** [friendica/friendica#2337]
Some smiley keywords are replaced with the right picture, but there remain a rest of the keyword. Some keywords are replaced with a wrong picture and other aren't replaced.

Examples:
:bunnyflowers
:dragonfly
:babycot
:catdevil
:horseriding
:bowman
:tearsofjoy
:shaka
:.../
:ooo/

Screenshot:
![screenshot](https://rjaf.deneb.uberspace.de/photo/14b7727b75c17be8cd3f6d483e3ce860-0.jpg)

[Original post](https://rjaf.deneb.uberspace.de/display/af68e9262056b9c83090884290328096)

**Comment by tobiasd** [comment]
have you installed any of the additional smiley packages from the addon repository?

**Comment by RuJo09** [comment]
I have installed the addons "smiley_pack" and "smileybutton".

**Comment by MrPetovan** [comment]
Closed via #5216
