### ISSUE TITLE
[master] Reply from an unfollowed GNUSocial account doesn't show up

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#2340]
I received an email and notification in web UI but the actual reply didn't show up nor it is findable in database.

What happens so far:
1. I followed from Friendica to GNUSocial account A
2. Account A posted something and I can see it in Friendica
3. Now I reply to and my reply is received by account A's timeline
4. Another GS account B replies to A (not showing up to me because I don't follow B)
5. Account A replies to B and so I can see both in the thread
6. I reply to B and my reply shows up in B's timeline
7. Account B replies to me, but the reply is only "visible" as an email and notification, no database entry (searched with %bla blub%) and so no entry in web UI

**Comment by annando** [comment]
We have totally rewritten the notifications in the "develop" branch. Hopefully this is solved there.

**Comment by Quix0r** [comment]
Okay, so I may need to retest that in my LAN where I more tend to use developer branches.

**Comment by Quix0r** [comment]
Hmm, the problem is, I have GNUSocial in a sub path (Intranet) and it is detected as RSS/Atom and not OStatus ... Okay, I can setup a fake virtual host. :-)

**Comment by Quix0r** [comment]
With _develop_ it partially works, look at this screenshot, please.
https://social.mxchange.org/file/83f35479ef95956c0185358e9dccdcd607a4cfe6b35676a1b389192c772ca22d.png

The other avatar of mine is a followed GNUSocial account.

**Comment by annando** [comment]
Does this still happen?

**Comment by Quix0r** [comment]
Need to find time for this.

**Comment by tobiasd** [comment]
What is the status of this @Quix0r ?

**Comment by annando** [comment]
I think the problem mentioned in the starting post has been solved long time ago. We had the issue that we hadn't shown posts when the thread parent wasn't existing. So I think we can close it.

**Comment by tobiasd** [comment]
Fine for me. @Quix0r please comment if the problem should still exit. Else we can close this before the release is done.

**Comment by Quix0r** [comment]
Does not seem to come back, for now.
