### ISSUE TITLE
vier mobile - embedded graphics are scaled with wrong aspect ratio

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2376]
I like the current state of vier on mobile devices like tablets. But there is also a problem with - I think - embedded pictures and video previews. They're scaled to use full width but the aspect ratio is wrong.

Here are some pictures. First picture with desktop view:

![desktop-1](https://cloud.githubusercontent.com/assets/3656054/13229898/4f148490-d9a3-11e5-95e5-220024712a41.jpg)

Second picture shows the same with mobile version:

![mobil-1](https://cloud.githubusercontent.com/assets/3656054/13229953/9b8720bc-d9a3-11e5-93bc-0e111900b2c0.jpg)

Now comes the real trouble. :-) You can only watch the upper part of the video:

![mobil-2](https://cloud.githubusercontent.com/assets/3656054/13229978/c6e18770-d9a3-11e5-9ab8-9ffbb7152a54.jpg)

I really like the scaling to full width on mobile devices. But the aspect ratio should be correct.

Regards,
Steffen

**Comment by rabuzarus** [comment]
OK the aspect ratio is now correct - but the yt video is still cuted off

**Comment by tobiasd** [comment]
@AlfredSK can you check the current develop branch if it is working now for you?

**Comment by AlfredSK** [comment]
I posted a "thumb up" already! :-)  Yes, it works. Thanks. 👍

**Comment by tobiasd** [comment]
Ok, then I'll close this issue :-)
