### ISSUE TITLE
Upload creates posts for each picture

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2381]
When you upload several pictures via https://example.com/photos/$username/upload it will create a post for each uploaded picture by default it does not matter what you select for "Keine Status-Mitteilung für diesen Beitrag anzeigen". This should not happen and also the default should be *_not *_to create status posts for a uploaded photo.

**Comment by tobiasd** [comment]
just tested on my node (develop branch) and could not reproduce this. I've uploaded 2 images, left the default selection to not post a comment about it. The images got uploaded and no posting was made as expected.

**Comment by ben-utzer** [comment]
Well I tried it again and I get [this](https://social.yl.ms/display/00000000d1aebf693187c439d3eb2dfda400fc87).

**Comment by tobiasd** [comment]
Today I encountered this with an image I uploaded, which then was supposed to be included in a comment. So I did *not send status update on picture upload* but it was posted onto my wall..

At that point I had switched to PHP7. When I switched back to PHP5 and uploaded a test image, this was not published to my stream.

My guess is that `mod/photos.php` line 773 does not work correct with PHP7, but I've not investigated it any further.

**Comment by thrrgilag** [comment]
Just noticed this occurred on my instance, posted to the wall when it wasn't supposed to.  Running with PHP 5.6.  So it may not be specific to PHP7.

**Comment by tobiasd** [comment]
Ok, thanks.

**Comment by MrPetovan** [comment]
Related to #4228

Is it still current?

**Comment by tobiasd** [comment]
I have not seen this happening lately. But lets dig into it for the 08 milestone and test/fix/close it then.

**Comment by tobiasd** [comment]
Has anybody seen this problem occur in 2018.08-dev?

**Comment by AlfredSK** [comment]
Nope.

**Comment by tobiasd** [comment]
Closing this issue then.
