### ISSUE TITLE
editing events does not include the ACL

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#2385]
and does not honor original settings. Tested with vier and quattro themes

**Comment by annando** [comment]
We cannot change the ACL afterwards. So why should we include them in the editing? Or had I misunderstood the case?

**Comment by tobiasd** [comment]
the issue is more, that the ACL settings are not honored when editing an event! at least on my system

**Comment by annando** [comment]
I guess you have to it show me so that I do understand it :-)

BTW: I'm planning to visit Berlin in the summer.

**Comment by tobiasd** [comment]
meh - seems to be an issue with the quattro theme (and therefore with my derived theme too). But vier shows the option as well..

**Comment by tobiasd** [comment]
raburarus fix seems to solve the issue, so I'll close it
