### ISSUE TITLE
Wiki: DFRN specs

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2395]
The github wiki (https://github.com/friendica/friendica/wiki/Protocol) points to https://macgirvin.com/spec/dfrn2.pdf but this link isn't available anymore.

Use https://github.com/friendica/friendica/blob/master/spec/dfrn2.pdf instead

**Comment by fabrixxm** [comment]
fixed with [9a8d887](https://github.com/friendica/friendica/wiki/Protocol/9a8d8872c5c6d0b2ce2b9106efa38707e63fe2f7)
