### ISSUE TITLE
Transifex is failing to update messages.po from curweather addon

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#2402]
The exact error we encountered was:

    'ascii' codec can't encode character u'\xb0' in position 1856: ordinal not in range(128) 

I think it could be the ° at [line 95](https://github.com/friendica/friendica-addons/blob/master/curweather/lang/C/messages.po#L95)

Possible solutions:

- remove the ° from the string
- encode the messages.po file in ascii

**Comment by tobiasd** [comment]
Fun that it worked before :-/

**Comment by tobiasd** [comment]
see PR #345 at the addons repo

**Comment by tobiasd** [comment]
hopefully I've now added the correct URL to transifex so the pipe can pick the fule up again.
