### ISSUE TITLE
privacy_image_cache should be removed

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#2403]
privacy_image_cache functionality has been moved in core.
The addon should be removed from friendica-addons repo.

**Comment by annando** [comment]
Pull request is done. I also included some other absolute stuff. Question is how long we should keep deprecated things. Should we remove them when they are obsolete in the current master?

**Comment by tobiasd** [comment]
I think addons should made obsolete a version after the release with which they went obsolete. And over that grace period being marked as such. Maybe the cron job could trigger a notification for the admin when obsolete addons are active in this time?

**Comment by tobiasd** [comment]
can we close this issue?
