### ISSUE TITLE
Log file not in system time zone

### ISSUE THREAD

**Issue by masupilamie** [friendica/friendica#2406]
To enable fail2ban to correctly find failed login attempts, the log file must use the same time zone as used by the system. Right now the log file timestamp seems to be UTC only.

Checked by doing a fresh install on Ubuntu 14.04. Time zone set to Europe/Amsterdam in system and friendica but friendica log timestamp stays 1 hour earlier (UTC).

**Comment by tobiasd** [comment]
Yes, UTC makes global debugging much easier then local timezone ;-)

**Comment by masupilamie** [comment]
I see and understand. If I would write an addon to create a second log file (only logging failed login attempts with system time zone timestamp), the [authenticate hook](https://github.com/friendica/friendica/blob/develop/include/auth.php#L159) will not work, right? For this addon to work there will need to be an extra hook for when the authentication fails (probably [here](https://github.com/friendica/friendica/blob/develop/include/auth.php#L180)), is this new hook a possibility or would I waste my time writing the addon?

**Comment by masupilamie** [comment]
Will close this because it's by design

**Comment by tobiasd** [comment]
Sorry for not replying earlier ;-) Maybe @annando, @fabrixxm or @rabuzarus  can help you with the hook question? As I'm not sure myself. You could also ask you question in the [support](https://helpers.pyxis.uberspace.de/profile/helpers) forum.

**Comment by masupilamie** [comment]
Thank you for your reply and pointing me to the support forum, useful info!
