### ISSUE TITLE
'remember me' keeps forgetting about me

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2432]
On my own node, the "Remember me" option on login doesn't behave as expected.
The cookie is set with 1 year expiration date, but somehow the node occasionally forgets about me nonetheless. I suspect there's a cleanup running at the database side but didn't run any deep debugging on the cause.

I think others confirmed the problem in a forum thread but i hadn't found a ticket, so here it is.

@annando maybe this is one of those things you could look at next :)

**Comment by tobiasd** [comment]
@silke had a similar problem solved with resolving a problem (#1839) in the cookie settings of the browser.

**Comment by strk** [comment]
@silke what was your cookie setting poblem ? I'm having this with the same browser that keeps being recognized on all other cookie-using sites that implement "remember me".
Maybe I should close this ticket and re-open #1839 ?

**Comment by redmatrix** [comment]
include/auth.php:new_cookie() calls session_set_cookie_params() to alter the expiration from php.ini defaults. The issue is that session_set_cookie_params() has no effect if called after session_start() which is the case here. What I've done is basically in index.php:

    /* session_set_cookie_params() needs to happen before session_start() */

    if($_POST['remember_me'])
        session_set_cookie_params(31556926);

    session_start(); 

This results in a cookie with a one year expiration, as desired. 

Then you should probably remove the call to session_set_cookie_params() in include/auth.php as it does absolutely nothing.

**Comment by annando** [comment]
@redmatrix I tried it like you suggested, but the following way seemed to be more reliable, see here:

https://github.com/annando/friendica/blob/1604-session/include/auth.php#L190-L198

I'm simply setting the same cookie again - only with a different time value.

@strk Once the pull request is accepted, please test if its working for you.

**Comment by redmatrix** [comment]
I agree that's an improvement.

**Comment by strk** [comment]
I just had the problem this morning, from a smartphone. Wont' be easy to test because I don't have a clear way to replicate. Now that you looked at a possible fix, do you have instructions for predictable steps to take to trigger the bug ? (oh how I miss a proper testsuite :)

**Comment by redmatrix** [comment]
Best test I've found is to examine the PHPSESSID cookie in your browser. It's either way into the future (a year out) or it expires with the browser session. An automated test could be performed by using CURL with a cookie file and examining it after a mock login. Incidentally what hasn't been covered with this bug is extending the expiration date if you continue to be remembered for a year and then it expires. That may require another bug if it is deemed important.

**Comment by strk** [comment]
@redmatrix good point, filed as #2438

**Comment by strk** [comment]
And #2439 is to add an automated test for _this_ specific bug. I've upgraded after the merge and closing this assuming it's fixed, so will re-open if it is not :)

**Comment by strk** [comment]
Still happens for me. From different browsers and devices, so it's not specific to a given browser.
It looks like it has to do with the server-side session being expired, not the cookie.

**Comment by annando** [comment]
I can imagine that there are some limits for the cookie that PHP is using for its sessions. I guess we have to use a different cookie for that.

**Comment by annando** [comment]
BTW: There is now a new system for this "remember me" in the develop branch. Since it doesn't rely on sessions any more (but on a cookie) it should work like a charm. It will work in a way that it automatically renews itself - but you will have to login again if you hadn't visited the site for longer than one week. This is for security issues when you maybe had logged in at a friend.

**Comment by strk** [comment]
Why 1 week ? Most "remember me" mechanism last 1 year.
The user should always be able to explicitly LOG OUT to make
the cookie harmless.

**Comment by annando** [comment]
I think that regular users do use the system more than once a week, don't they? So these people wouldn't feel any inconvenience. Of course people can always log out as well.

**Comment by strk** [comment]
How about mentioning the timeout in the "Remember me" text ?
It'd read something like "Remember me on this machine for 1 week".

**Comment by strk** [comment]
Ideally I'd like to be able to decide for how long I want to be
remembered. For a trusted machine that'd be ... 1 year

**Comment by annando** [comment]
Let's see and wait how the people will accept this.

**Comment by strk** [comment]
As it keeps happening, I went looking in the code and found some occurrences that would "nuke" a user session. Among those, there's a check for an IP mismatch, meaning that if I access my node from my ADSL *and* from a mobile network I would keep triggering such session destruction.

In order to verify that's the case, I'd like to find the logs, can you help ? The logging code goes:
```
                        logger('Session address changed. Paranoid setting in effect, blocking session. '.
                                $_SESSION['addr'].' != '.$_SERVER['REMOTE_ADDR']);
```

**Comment by tobiasd** [comment]
Have you checked in your DB that the paranoia mode is active @strk ? The line above your snipplet checks if the system config is set.

From the base directory of your installation you can check it with `php util/config system paranoia`.

**Comment by strk** [comment]
Paranoia is unset, and on second thought I guess I would not have
the same "session-id" from mobile and desktop browser, so I
should not have hit.

Still, do you know where I would get the logs printed via "logger" ?

**Comment by fabrixxm** [comment]
> do you know where I would get the logs printed via "logger" ?

touch a file in your friendica install dir (e.g. friendica.log), make it writable by webserver, go to yourserver/admin/logs/, enable debug, put your file name, set an appropriate debug level (the code you posted above don't set a level, so it defaults to LOGGER_NORMAL), save the settings, replicate the bug, get the log file and take a look...

**Comment by strk** [comment]
As it just happened again, I'm now wondering if this has to do with OpenID login.
That is, my OpenID provider forgets about me every 2 weeks, could it be that Friendica keeps checking my OpenID credentials rather than just trusting my Friendica cookie ? (just thinking out loud)

**Comment by strk** [comment]
For the record, it's still happening here. Does nobody else have this problem ?

**Comment by strk** [comment]
NOTE: I'm using OpenID to login, which may be related.

**Comment by strk** [comment]
Cookie naming needs an overhaul here, I just found out that by logging in via username/password I get a 7-days lasting "friendica" named cookie, while logging in via OpenID does not give me a "friendica" cookie but leaves me with a session-lasting "PHPSESSION" cookie only (the same you get even before being authenticated)

For comparison with something that works better: GNUSocial installs a "rememberme" named cookie which lasts 1 months and is renewed on every new session (everytime the PHPSESSION cookie is not presented, where PHPSESSION cookie expires with session)

**Comment by strk** [comment]
Ok so I think the problem here is that logins via OpenID just don't get the "Friendica" cookie returned. At least part of it.

**Comment by strk** [comment]
Confirmed, while username/password is handled in include/auth.php the openid is handled in another function which doesn't have an hold on the "rememberme" POST field at all. My PR #3221 puts the POST field into a session variable.
