### ISSUE TITLE
vier theme commenting renders badly

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2433]
I don't know how that's supposed to look like, but certainly not like this:

![screenshot-21](https://cloud.githubusercontent.com/assets/289678/14234082/3ed8d78c-f9da-11e5-8134-8a121c2ca29e.png)

This is with Firefox29/linux, emulated

**Comment by annando** [comment]
You are on the develop branch? Do a refresh of the browser cache. We changed the comment icon.

**Comment by strk** [comment]
clearing the browser cache did it, sorry for the noise
