### ISSUE TITLE
Website and documentation indicate Facebook is supported

### ISSUE THREAD

**Issue by Treer** [friendica/friendica#2448]
I think Google Plus might be no longer supported as well, but I don't have any good place to find out.

It took a lot of time setting up a system before figuring out from git commits that the services aren't supported anymore. I assume it's unlikely Friendica will ever have Facebook support given their change in API so it's safe to remove references? 

Obviously there's the [main site](http://friendica.com/), but also:
- [Last section here](https://github.com/friendica/friendica/wiki/How-to-install-addons)
- [Here](https://github.com/friendica/friendica-addons/tree/master/facebook)
- [Should say all Facebook connectors are deprecated](https://github.com/friendica/friendica/wiki/How-to:-Friendica%E2%80%99s-Facebook-connector)

**Comment by tobiasd** [comment]
can you give me a link for the main page as I've tried to remove the references to the working connection to FB when they changed the rules. Or are you referring to the image on the start page?

**Comment by Treer** [comment]
Yeah, looks like it's just the image - it was a long time ago when I first read the site, the image is quite prominent though.

**Comment by annando** [comment]
Concerning Google+: There is some functionality. We can post to Google+ pages with the use of the "buffer" addon. And we can mirror posts from G+ accounts and G+ pages.

But yes: The website is highly irritating.

**Comment by tobiasd** [comment]
What's with the wiki pages @annando ? can we just delete them? Or replace them with the info that FB changed the rules as I did on the homepage.

**Comment by annando** [comment]
I would simply remove every mention of facebook. But we should keep the addons for a while.

**Comment by tobiasd** [comment]
It is a really long text and deleting every occurrence of that one word does not make much sense ;-) I removed the last paragraph, could you update the HowTo page from the wiki and eventually deprecate the addon?

**Comment by annando** [comment]
All facebook addons are "deprecated" a long time ago.

**Comment by tobiasd** [comment]
So the Howto connect Friendica to FB can be leleted

**Comment by annando** [comment]
Yeah.

**Comment by tobiasd** [comment]
As the website was renewed without the image, I'll close this issue as the other encounters were removed before.
