### ISSUE TITLE
priority issue when probing connections

### ISSUE THREAD

**Issue by redmatrix** [friendica/friendica#2472]
I've got a test hubzilla site with both diaspora and statusnet (beta) connectors. If I probe it from a friendica site (libranet.de in this case) I get the following result:

Notice that it is labelled as a diaspora connection, but with statusnet communication parameters (notify and poll). Communication doesn't work properly because Diaspora protocol messages are sent (which is OK), but they are sent to the salmon endpoint /salmon and not the Diaspora endpoint  /receive. 

Array
(
    [name] => glip
    [nick] => glip
    [url] => https://hz.macgirvin.com/channel/glip
    [addr] => glip@hz.macgirvin.com
    [batch] => 
    [notify] => https://hz.macgirvin.com/salmon/glip
    [poll] => https://hz.macgirvin.com/feed/glip
    [request] => 
    [confirm] => 
    [poco] => https://hz.macgirvin.com/poco/glip
    [photo] => https://hz.macgirvin.com/photo/profile/300/12.jpg
    [priority] => 0
    [network] => dspr
    [alias] => https://hz.macgirvin.com/~glip
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwdyDtxq0bFJHXVY1Y9ptZ
rOkcl1y9gmoxXVOGHxyV5aj8IRB4C0/au3VhBvHUm34aVsOZoKV4dfZbeHgyDoPbx
Fj3V8QcXZEwipbkTFEvhdO1c/uKJkSCg29Gd0dxD5SxfOIhDBLg6nFmUEgJ+WPDko
86aVSx8Qph3kwtTBmRB5ch31wgieZqcYPiMMUAvJ/V/iLgALF73IB7ZnHFOBCFFc0
A3Yuzi85fSbJ0fPt7kBiw759Lojdy1nsZL9X/fmNnNF2NFCPij+3LraNk4RBLyFQO
EV3TJly9yirpbU8nWSPqGfVcu6EjBxXPQansJJP8flTaVcepWTDn/nGEmg6j9VgTc
0+f/EPhtJtAWRJOIqoKK8QPoxQKT4JfDFPD7y9+VrH/ku4U/YipMm38XNAxWnuYer
07RM9sCcHpCR9MLwbaZgiN853gdv0hpsamZ7VehvZUiPmrOEj3aXCS6bweiVq9qsX
UJXAf85nBpJ83aMFQFvw79XfYCgknRxq7zJ+rTcI48ldXoxuQvw47Jt+klKKurnFY
CA3r6i2T8qsRt8JNgKHJG/i/rinotM10YSSmHHYY9yVHlxeqjvyrRPBNfmfqVianV
xbziC/Yy5LF2dGJYWp5NXaMLPnsMErpia5XNEprnZMI9T6UdJeAmDsHN6oZWrNtq8
CruysJbDbkrECAwEAAQ==
-----END PUBLIC KEY-----

    [baseurl] => http://hz.macgirvin.com
)

**Comment by annando** [comment]
Probing is fun and a very clever way to shot oneself in the foot :-)

I will dig into it, thanks for reporting!

**Comment by redmatrix** [comment]
Anybody who thinks they can reduce this to a clean algorithm is deluding themselves. Ultimately I think one needs to make a priority list of networks and then exhaustively search them in priority order (e.g. hubzilla, friendica, diaspora, pump, statusnet). Any of these probe sequences that hits a dead end goes back to the list and tries the next one - but saves everything it already fetched and parsed. That's easy to describe, but it's a mother to code when you're talking about up to a dozen URL fetches and 5-6 different parsing algorithms.

**Comment by annando** [comment]
Yeah, I guess the probing should be rewritten completely. And it should be separated in probing for Friendica, then for Diaspora, then for OStatus. So if we find that a system is compatible to a protocol, then we needn't to continue the search. That sounds like a clever idea.

**Comment by annando** [comment]
I wrote a quickfix that will help at the moment - but it isn't perfect (it is slowing down the process) and has to be rewritten in the future.

**Comment by AlfredSK** [comment]
I've merged the latest changes on libranet.de so @redmatrix can continue with testing. :-)

**Comment by annando** [comment]
Since this fix will work for this situation, I would suggest to move this issue to an upcoming milestone. I wouldn't like to close it, since reworking the probing should be done. What do you think?

**Comment by tobiasd** [comment]
sure, if t is working

**Comment by annando** [comment]
Since the new probing is now merged, I guess we can close this issue, can't we?
