### ISSUE TITLE
Vier (mobile): search widget 

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2485]
When the width of screen is not enough, the search widget goes above the content. This is a relatively new bug in the vier theme (desktop version, supposedly adaptive).

See https://oc.kbt.io/index.php/s/Zd3yVk5TQR4rmnl

**Comment by annando** [comment]
Please update your system. This is fixed in the current version.

**Comment by strk** [comment]
I'm running commit 64595e9a2df5bee7fe3a0bddd4b6017d6ae00be8 and that's
what started showing the problem. Was coming from 295489e.

**Comment by annando** [comment]
I'm running this version as well, it is looking that way:
![screenshot_2016-04-26-22-13-25](https://cloud.githubusercontent.com/assets/844208/14832943/f1de7114-0bfc-11e6-83ce-b0a6c6302502.png)

**Comment by strk** [comment]
I dunno what's happening but now I can't reproduce my problem
anymore. Maybe it was in the cache ? (weird, as I hadn't seen it
before).

**Comment by annando** [comment]
So can we close it?

**Comment by strk** [comment]
Yes, #close please
