### ISSUE TITLE
https error with friendica

### ISSUE THREAD

**Issue by soko1** [friendica/friendica#2492]
Hi!
https://social.decart.xyz - error certificate (using friendica, screenshot: http://imgur.com/8T7SpQT)
https://social.decart.xyz/test.php - it's ok.

Why?

**Comment by tobiasd** [comment]
your logo graphic is fetched via http not https, hence FF pulls a warning.

**Comment by soko1** [comment]
Thanks, man!

**Comment by annando** [comment]
Can we close the issue?

**Comment by soko1** [comment]
Yes, thanks!
