### ISSUE TITLE
Check for iconv or/and mbstring during installation

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2506]
I just setup a new Friendica server with Arch Linux as server system and it wasn't possible to connect to any other account, I tried my account on social.yl.ms and the helpers account without success. Then by luck I found that I did not activate/install php extension/module mbstring and iconv. It would be nice to check for this to be available, maybe it is enough to have one available.

**Comment by tobiasd** [comment]
PR #2714 should solve this for iconv module, the mb_string module is already checked during the installation.
