### ISSUE TITLE
Url rewrite in .htaccess is not working

### ISSUE THREAD

**Issue by allmyfavoriteusernamesaretaken** [friendica/friendica#2512]
Hi *,

I'm trying to install friendica 3.4.3-2 on Debian Jessie and get the following error on the system check page:

`Url rewrite in .htaccess is not working. Check your server configuration.`

The file ".htaccess" exists and is writable for "www-data":
```
$ ls -l /var/www/html/social.ignorelist.com/.htaccess 
-rw-r--r-- 1 www-data www-data 924 May 13 17:01 /var/www/html/social.ignorelist.com/.htaccess
$ cat /var/www/html/social.ignorelist.com/.htaccess
Options -Indexes
AddType application/x-java-archive .jar
AddType audio/ogg .oga
#AddHandler php53-cgi .php

<FilesMatch "\.(out|log)$">
Deny from all
</FilesMatch>

<IfModule mod_rewrite.c>
  RewriteEngine on
  # Protect repository directory from browsing
  RewriteRule "(^|/)\.git" - [F]

  # Rewrite current-style URLs of the form 'index.php?pagename=x'.
  # Also place auth information into REMOTE_USER for sites running
  # in CGI mode.

  # If you have troubles or use VirtualDocumentRoot
  # uncomment this and set it to the path where your friendica installation is
  # i.e.:
  # Friendica url: http://some.example.com
  # RewriteBase /
  # Friendica url: http://some.example.com/friendica
  # RewriteBase /friendica/
  #
  #RewriteBase /

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

</IfModule>
```

Rewriting is allowed:
```
$ a2enmod rewrite
Module rewrite already enabled
```

And .htaccess files are evaluated by apache:
```
$ cat /etc/apache2/sites-available/social.ignorelist.com.conf
<VirtualHost *:80>

        ServerName social.ignorelist.com
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www/html/social.ignorelist.com

        Redirect permanent / https://social.ignorelist.com/
</VirtualHost>

<VirtualHost _default_:443>

        ServerName social.ignorelist.com
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www/html/social.ignorelist.com

        <Directory "/var/www/html/social.ignorelist.com/">
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLEngine on
        # Some more SSL stuff
</VirtualHost>
```

Is there anything I'm missing?

Thanks a lot in advance!

**Comment by annando** [comment]
Please check if you can reach https://yourhostname.tld/install/testrewrite (replace "yourhostname.tld" with your actual host name of course). This should return a simple "ok". If it doesn't then you have to recheck your apache configuration. If it returns this "ok" then we have to have a deeper look into friendica.

**Comment by allmyfavoriteusernamesaretaken** [comment]
It returns a simple "ok".

**Comment by fabrixxm** [comment]
So your mod_rewrite is ok.
Please be sure that your serve can resolve his domain name correctly.
To check for working mod_rewrite, we open https://yourhostname.tld/install/testrewrite  ***from your sever***, so your server must be able to correctly resolve "yourhostname.tld" to your server IP (or at least to 127.0.0.1)

**Comment by allmyfavoriteusernamesaretaken** [comment]
That's it. I forgot to add the domain name to the server's hosts file.

For everyone with the same problem: I had to add the following line to the server's `/etc/hosts` file:

`127.0.1.1      yourhostname.tld`

With `yourhostname.tld` being you server's host name.

Thanks a lot for your help!
