### ISSUE TITLE
[feature request] please make admin/users sortable

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2516]
Hello,
my friendica node has 67 registered users at the moment. Which means that the **admin/users** page became a little bit crowded. And I hope it gets even worse in the future. :-) So, to have a better overview it would be nice to have a **possibility to sort the list of users**. I wish it would be possible to click on every heading and the table gets automagically sorted.

**Please make the page admin/users sortable by the headings** (Name, Email, Register date, Last login, Last item, Account).

Thank you!

**Comment by fabrixxm** [comment]
hold my ~~beer~~ mate

**Comment by AlfredSK** [comment]
:-)

**Comment by fabrixxm** [comment]
Closed by #2517

**Comment by AlfredSK** [comment]
Wow! That was fast. +1
