### ISSUE TITLE
Post deletion after dropping contacts should be a background process

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2518]
By dropping contacts a process gets started, which deletes the postings of the person(s), who were selected to drop and can make friendica absolutely unusable for quite a long time, because actually the deletion happens as foreground process.

**Comment by annando** [comment]
Would be nice if someone could test it.

**Comment by tobiasd** [comment]
I dont have enough contacts to delete many, especially some with many postings, but deleting some with an unknown number of postings has worked.

**Comment by annando** [comment]
Sounds like it is working. So we should close the issue.

**Comment by rebeka-catalina** [comment]
On 2016.12.04, Michael Vogel wrote:
> Sounds like it is working. So we should close the issue.

No, with people who don't share that much it isn't possible to test
this. What if you wait a few days ? As I already told you via PM I
started sharing with a person, who shares quite a lot and in a few
days I can tell you for sure, if it works or not.

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/friendica/friendica/issues/2518#issuecomment-264774866

-- 
Ich weiss, dass ich nichts weiss
	~ Sokrates ~

**Comment by tobiasd** [comment]
As there is another open issue, I think we can leave this open a bit so you can test it @rebeka-catalina

**Comment by tobiasd** [comment]
I should have pressed the refreh button ... but anyway I think @rebeka-catalina can test this.

**Comment by annando** [comment]
There is no difference anymore if a contact has 1 or 100,000 item entries, since the deletion is done in the background. So a valid test is to delete a contact. Then you had to check whether the item entries are deleted in the database. (This will be done with low priority, so wait for several hours)

**Comment by tobiasd** [comment]
I had only long inactive contacts for deletion, with probably no items in the DB due my expiration settings.

**Comment by rebeka-catalina** [comment]
On 2016.12.05, Michael Vogel wrote:
> There is no difference anymore if a contact has 1 or 100,000 item entries, since the deletion is done in the background. So a valid test is to delete a contact. Then you had to check whether the item entries are deleted in the database. (This will be done with low priority, so wait for several hours)
> 

Well, why should we test then, if it's already clear 

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/friendica/friendica/issues/2518#issuecomment-265082087

-- 
/X\(‘-‘)/X\

**Comment by tobiasd** [comment]
@rebeka-catalina tested this and it is working, so I'll close this ticket.
