### ISSUE TITLE
Feature Request: Character counter for plaintext editor

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2525]
The "web editor" has this counter, the plaintext editor not. We should add this to the editor as well.

- [x] frio #2937
- [ ] vier
- [ ] duepuntozero
- [ ] smoothly
- [ ] quattro

**Comment by annando** [comment]
Sorry, this was already done, but we forgot to close this issue. We don't have the web editor any more and the plain text editor now counts the characters.

I'm closing this issue. And I guess we should have a look at some more issues, maybe they are solved in the meantime as well :)

**Comment by irhen** [comment]
Oh, I see. Great! :)

**Comment by tobiasd** [comment]
It is? Which theme? What do I have to do to enable it?

**Comment by tobiasd** [comment]
Oh, I see the Frio theme has it. @irhen you could try to port it to the other supported themes (duepunto, quattro, vier, smoothy). I think it would be really great to have the counter in all themes, not only one.

In Frio it is done in [view/theme/frio/template/jot.tpl line](https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/jot.tpl#L104) around line 105. I'm not sure how much work it will be to port it to the other themes.

**Comment by annando** [comment]
Oh, okay.

**Comment by irhen** [comment]
@tobiasd oh well. I'm not sure either how much work will it take, but I'll try to get it done. There'll be a PR from me to let you know I have an idea. Thanks!

**Comment by rabuzarus** [comment]
@irhen Frios character-counter is done here https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/jot-header.tpl#L23.

It should be simple to port it to other themes

**Comment by rabuzarus** [comment]
was solved with https://github.com/friendica/friendica/pull/2937 . So I close this issue

**Comment by tobiasd** [comment]
@rabuzarus that did only add the counter to frio, but all the other themes don't have it. Hence I'm reopening the issue.
