### ISSUE TITLE
XMPP Addon (and Chrome) doesn't play well with events

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2528]
Use Chrome or Safari, enable the XMPP addon, go to /events - you won't see the calendar and no JS is executed on that page. The console is telling "colorbox is not a function".

**Comment by MrPetovan** [comment]
Related to #2528 and #3717, same question, should we just mark this addon as unsupported since no one has picked up either issue for more than a year?

**Comment by MrPetovan** [comment]
The addon has been marked as unsupported.
