### ISSUE TITLE
Frio: Missing functionality

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2537]
Frio is a cool new theme. But since it is "experimental" by now, several stuff is missing:
- [x] There is no user menu like in other themes, for example in vier:
  ![image](https://cloud.githubusercontent.com/assets/844208/15626270/60ce3d52-24c1-11e6-85b1-6337c10c4cfe.png)
- [x] Some ugly word wrap when a location is too long:~~
  ![image](https://cloud.githubusercontent.com/assets/844208/15626284/abafe6fe-24c1-11e6-8652-da1098874c04.png)
- [x] When in network view you don't see the selected network~~
- [x] Editing posts is a little bit ugly because you are sent to some nearly blank page~~ (Not reproducible)
- [x] When creating a post you cannot select or deselect the posting connectors
- [ ] Long deep nested threads are looking a little bit narrow:
  ![image](https://cloud.githubusercontent.com/assets/844208/15626392/15511004-24c4-11e6-9f21-761d8ba8bc40.png)

... more to come :-)

**Comment by rabuzarus** [comment]
@annando 
concerning usermenu, I have removed the usermenu with https://github.com/rabuzarus/frio/commit/adefc315f7b77b9e3f9b0544d74804de20f6a656

The idea was to have user related actions in the hover card.
At the time it is a little bit problematic. Because for frio hovercard uses "contact_photo_menu" for it's actions while the original item menu in network view was constructed by "item_photo_menu". So the hover card misses some functionality.

This is in area which should reconstructed in core (until now I have now idea how). But the idea should be the same. Contact related actions (like pm, poke, connect and so on) should be displayed in the hover card and post/thread related actions (like follow the thread) should be under the thread dropdown menu

**Comment by annando** [comment]
The hovercard support needs to be part of the core. What about moving it to /hovercard and make it JSON instead of XML?

**Comment by rabuzarus** [comment]
At the present time hovercard.php containing 3 parts in dependence of the kind of request 
1.) Give raw template content (used by jSmart)
2.) Give hovercard html output
3.) Give json output

Part one should be moved in it's own file under /mod. It should be more generally -> Transmit a request for a template and return it as raw content. This would need the implementation in core of something what is my "mode=none" (https://github.com/friendica/friendica/blob/develop/view/theme/frio/php/modes/none.php)

Part 2 and 3.
I have provided both json and html. While json is actually used for the js hovercard I also implemented html output (which isn't used at the moment). The idea was that someone maybe can make use of it. An idea is to have the possibility to embed something like hover card in a post. Hubzilla implemented something like this 2 months ago

So why remove the html part? We can move it to to /mod/hovercard or maybe /mod/userinfo or something like this.

When you read the readme of frio_hovercard addon. In long scope I would rather have an external request. Diaspora and gnu social are doing it that way -> asking the remote server (where the user of the hovercard does have his/her account) for it's public userdata (with json). So we wouldn't have to query through a big gcontact table. This would much smoother in regards of resources

**Comment by annando** [comment]
I just realized that you are generating the HTML for the hovercard there and no XML file. So I would like to move it into the core. Do you agree?

**Comment by rabuzarus** [comment]
Just would like to now what you thinking about my points above?

**Comment by annando** [comment]
I really would prefer querying the gcontact table instead of querying external resources. They could be unavailable at some time - and database queries are always faster and more reliable than network queries.

BTW: Diaspora is caching the contact data locally as well.

**Comment by rabuzarus** [comment]
mhhh OK

We should really move it to core /mod

But we should think about moving the template raw content part in an own file.

**Comment by rabuzarus** [comment]
> When creating a post you cannot select or deselect the posting connectors

I haven't looked into the code but I want to point out that frio is using https://github.com/flatlogic/awesome-bootstrap-checkbox for generating checkboxes. That's why the original checkboxes don't work as expected
This is realated with https://github.com/friendica/friendica/issues/2539

**Comment by annando** [comment]
Not totally I guess. You cannot even see the settings - so I guess that this code isn't even printed out.

**Comment by rabuzarus** [comment]
> Not totally I guess. You cannot even see the settings - so I guess that this code isn't even printed out.

Do we talk about the same things? My screen:
![jotnets](https://cloud.githubusercontent.com/assets/3750381/16356525/297c0ec6-3adb-11e6-9ab4-931e038d1375.png)

**Comment by annando** [comment]
Well ...

At first I see this here:
![bildschirmfoto 2016-06-25 um 14 06 08](https://cloud.githubusercontent.com/assets/844208/16356591/26653c78-3ade-11e6-8b3a-9b3f975725d7.png)

After pressing "tab" in the mail field I get this:
![bildschirmfoto 2016-06-25 um 14 06 28](https://cloud.githubusercontent.com/assets/844208/16356594/37525a16-3ade-11e6-843d-eea3a1c89ff5.png)

So the problem is an optical one.

**Comment by rabuzarus** [comment]
Mhhh this is difficult without the possibility of reproducing this. What browser are using?

**Comment by annando** [comment]
Currently it's Chrome on MacOS. But it's also happening with Palemoon, Firefox and Opera on Linux and Safari on MacOS.

And it doesn't depend on the amount of share links as well. I tested with an account that has only to of these options.

**Comment by rabuzarus** [comment]
Can you right click on the mail field for developer tool and look in the generated html and have a look what changes after pressing tab

**Comment by annando** [comment]
Well ... I just realized that I simply had to scroll down the page to see these options. It should be okay to reduce the height of the acl list so that it doesn't always scales this way. It is irritating that even on large displays these options are always out of sight

**Comment by rabuzarus** [comment]
Yes this is a bit problematically. Because we don't know if the user does have jotnets. At the present state the acl height (the inner section for permission selection) is calculated by css, but it's calculated under the adoption that there are no jotnets. I have no real solution because you don't have any if then statements in css :-/ . But if you want you can experiment a little bit with this. The acl permission selection section should also have a min height.

**Comment by annando** [comment]
From my point of view these points are all solved.
