### ISSUE TITLE
Frio: Cannot see/change Notification Settings

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2539]
When using the wonderful Frio theme the checkboxes in Settings/Account Settings/Notification Settings don't work. I cannot see the current status and cannot switch the settings.

**Comment by rabuzarus** [comment]
I added some setting templates to frio last week. Can you please test again and tell me if this issue is still valid?

**Comment by AlfredSK** [comment]
It is working now! Thank you!
