### ISSUE TITLE
Frio: Default Post Permissions doesn't respect display width

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2540]
Another usability glitch with the outstanding Frio theme. :-)
The overlay window of Settings/Account Settings/Security and Privacy Settings/Default Post Permissions doesn't respect the display width. The window is very wide, so one has to scroll horizontally to see and select the groups and users.

![frio-permissions](https://cloud.githubusercontent.com/assets/3656054/15627602/bbca2dec-24e9-11e6-88cf-25c453dea2a3.jpg)

**Comment by rabuzarus** [comment]
it's because the systemsettings are not ready know.
Acl should opened with a bootstrap modal and what you see is an acl model opened with colorbox.

BTW:
There is a js function (I think in modals.js) which can be called and ervery page will be loaded in a bootstrap modal

**Comment by AlfredSK** [comment]
Got it. So, take this report as a reminder, then. And thanks for this great theme!

**Comment by rabuzarus** [comment]
Can you please latest git develop and tell me if it is solved?

**Comment by AlfredSK** [comment]
I checked this and I can confirm it is working now. So, I think I can close this. Thanks!
