### ISSUE TITLE
Different contact avatar shown in comment and notification

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2593]
The avatar shown for a contact can be different for a comment or a notification,
like the one for @annando  in the attached screenshot. I would expect to always see the same avatar instead (depending on which one my contact decided to show me).

![diff_avatars](https://cloud.githubusercontent.com/assets/289678/15990087/07d5de6a-308a-11e6-9f53-f05fd0563872.png)

**Comment by annando** [comment]
This is fixed in one of the latest commits on the "develop" branch.

**Comment by strk** [comment]
confirmed, sorry for the noise. Fixed as of 0eb69b963e5bc17f94064e20a0b7629296f5aeb8
