### ISSUE TITLE
All notifications appear s "{8}{7}"

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2597]
As of 0eb69b963e5bc17f94064e20a0b7629296f5aeb8, see screenshot:

![screenshot from 2016-06-12 13 43 51](https://cloud.githubusercontent.com/assets/289678/15990960/cd8770e2-30a3-11e6-8bd1-831c461c5a49.png)

**Comment by annando** [comment]
Please clear your browser cache. This will help.

**Comment by strk** [comment]
How about this, from a console-based browser (and no previous cache):


```
     * [12][IMG]
       {8}{7}
       {3}
```

I recognize the pattern

**Comment by annando** [comment]
Does this console browser interpret javascript? These values are replaced after loading.

**Comment by strk** [comment]
nope, it doesn't. I confirm a clean cache fixes the problem on javascript-aware browsers
