### ISSUE TITLE
Frio: Bookmarklet doesn't work

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2611]
/mod/bookmarklet.php is used for the "Diaspora Sharer". With Frio it only shows a grey page and one can't share an item with this.

**Comment by rabuzarus** [comment]
Can you explain it a little bit deeper. Do you mean posting directly from the page "bookmarklet"? Or is it integrated somewhere? Can you describe the use case so that I can follow the correct steps?

**Comment by annando** [comment]
Just call /bookmarklet on your system with - for example - "vier". For more details see here: https://sharetodiaspora.github.io/about/

**Comment by rabuzarus** [comment]
Is this issue solved with the commit?

**Comment by annando** [comment]
It is working but could be improved when time comes. We can close the issue for now.
