### ISSUE TITLE
photos.php: Permission checking is incorrect

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2619]
This should be a reminder of a post I wrote half a year ago.

Have a look at photos.php https://github.com/friendica/friendica/blob/develop/mod/photos.php#L1035
`$visitor = $cid;`
The problem is that `$visitor` will be always empty because the variable `$cid` have been never defined before.
I guess this should not be the intended behavior.

BTW: This piece of code is used also at other places (have a look at https://github.com/friendica/friendica/pull/2223 for a list). It would be nice to have a central function to get this permissions. And reduce code.

**Comment by Quix0r** [comment]
Yes, DRY is a good approach.

**Comment by annando** [comment]
The variable $cid doesn't exist anymore. So probably the problem doesn't exist anymore as well.

**Comment by annando** [comment]
If no one disagrees, then I close this thing now. It doesn't make any sense to keep something open that refers to something that even doesn't exist anymore.

**Comment by MrPetovan** [comment]
Closed as invalid.
