### ISSUE TITLE
vcard and microformats not up to date

### ISSUE THREAD

**Issue by dissolve** [friendica/friendica#2629]
There were a few issues with some of the vcard class properties that are incorrect and there are spots of microformats here and there that are not using the most recent stable version microformats (microformats 2)

**Comment by fabrixxm** [comment]
afaik, vcard in profile page is used by Diaspora to fetch user info, doesn't it?
Are we sure that changing them we don't break Diaspora protocol?
I don't know, I didn't checked, I'm talking from fading memories, someone with more knowledge is needed...

**Comment by dissolve** [comment]
handled by PR
https://github.com/friendica/friendica/pull/2630
