### ISSUE TITLE
Retriever AddOn/Plugin causes problems when receiving post comments

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2675]
I'm not sure what is the exact problem, but this diagnosis was done by @annando and [here](https://social.yl.ms/display/ec054ce7135784f2357cc5c964767155) is some post where we tried to figure out what is the reason. 

So post comments are not received and distributed correctly and it is caused be the Retriever AddOn.

**Comment by tobiasd** [comment]
The addon has been moved to the friendica/deprecated-addons repository and is marked as unsupported 

Hence I'm closing this issue.
