### ISSUE TITLE
Answers to missing items in threads aren't displayed

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2732]
If a thread contains posts that are an answer to a post that isn't present in the database then this post isn't displayed in the thread.

We should treat this differently.

**Comment by MrPetovan** [comment]
How do you know there are orphan items? Are they pulled in the item SQL query but not displayed? If yes, on what column are they pulled if their parent doesn't exist? The non-thread conversations are using the `parent` column (referencing the top-level post) while the threaded conversations use the `thr-parent` column (which would be referencing a non-existent post).

**Comment by annando** [comment]
Orphans can happen when Friendica users are interacting with OStatus users. due to the different ways, the posts are distributed. 

AFAIK the postings are fetched.

**Comment by MrPetovan** [comment]
I'm so glad I was able to finally close an issue I didn't open myself 🤗

**Comment by annando** [comment]
You are my hero :-)
