### ISSUE TITLE
"System error. Post not saved." when adding a new post

### ISSUE THREAD

**Issue by nytche** [friendica/friendica#2751]
hello,
since I upgraded toubuntu 16.04 and php 7, i cannot add posts to friendica. The corresponding log error is the following:
`2016-08-28 07:35:10@kcdg0ilfd7u1preuvik776qfk6 [NORMAL]:dba.php:129:q  dba: Field 'object' doesn't have a default value
2016-08-28 07:35:10@kcdg0ilfd7u1preuvik776qfk6  [NORMAL]:dba.php:161:q  dba: INSERT INTO`item`(`guid`,`extid`,`uid`,`type`,`wall`,`gravity`,`network`,`contact-id`,`owner-name`,`owner-link`,`owner-avatar`,`author-name`,`author-link`,`author-avatar`,
`created`,`edited`,`commented`,`received`,`changed`,`uri`,`thr-parent`,`title`,`body`,`app`,`location`,`coord`,`tag`,`inform`,`verb`,`object-type`,`postopts`,
`allow_cid`,`allow_gid`,`deny_cid`,`deny_gid`,`private`,`pubmail`,`attach`,`bookmark`,`origin`,`moderated`,`file`,`rendered-html`,`rendered-hash`)
        VALUES( '7b6677a41257c2942ebe331062540965', '', 2, 'wall', 1, 0, 'dfrn', 10, 'Fred Nitche', 'https://friendica.nitche.org/profile/niitche', 'https://friendica.nitche.org/photo/cd1cdcef59ac1791f83176b9f491c3da-5.jpg', 'Fred Nitche', 'https://friendica.nitche.org/profile/niitche', 'https://friendica.nitche.org/photo/cd1cdcef59ac1791f83176b9f491c3da-5.jpg', '2016-08-28 07:35:10', '2016-08-28 07:35:10', '2016-08-28 07:35:10', '2016-08-28 07:35:10', '2016-08-28 07:35:10', 'urn:X-dfrn:friendica.nitche.org:2:7b6677a41257c2942ebe331062540965', 'urn:X-dfrn:friendica.nitche.org:2:7b6677a41257c2942ebe331062540965', '', 'test', '', '', '', '', '', 'http://activitystrea.ms/schema/1.0/post', 'http://activitystrea.ms/schema/1.0/note', 'lang=estonian;0.69833333333333:french;0.555:portuguese;0.51', '', '', '', '', 0, 0, '', 0, 1, 0, '', 'test', '098f6bcd4621d373cade4e832627b4f6') returned false.
Field 'object' doesn't have a default value
2016-08-28 07:35:10@kcdg0ilfd7u1preuvik776qfk6  [NORMAL]:item.php:833:item_post mod_item: unable to retrieve post that was just stored.`

also upgraded to 3.4.2, same issue. Any solution?

**Comment by annando** [comment]
Please change the sql settings so that the system can store entries without default values. It is a known issue that we have to fix in the future.

**Comment by nytche** [comment]
what are the sql settings? do I have to change the row 'object' in 'item 'table'?

**Comment by annando** [comment]
No, it is something in the database settings for the mysql server. At the moment I don't have the time to look for it.

**Comment by nytche** [comment]
up please

**Comment by annando** [comment]
See here a solution for the issue: https://www.farbeyondcode.com/Solution-for-MariaDB-Field--xxx--doesn-t-have-a-default-value-5-2720.html

**Comment by nytche** [comment]
I added sql-mode="NO_ENGINE_SUBSTITUTION" to /etc/mysql/my.cnf file, then I restarted mysql. It did not solved the issue.
This seemed to have happened then I upgraded my server to Ubuntu 16.04. Probably Mysql have changed too, but I have no issue on my other applications.

any idea?

**Comment by annando** [comment]
I will do a pull request that (I hope) will be part of the upcoming release, so that this problem is fixed.

**Comment by annando** [comment]
The release candidate contains needed changes to the tables. You could switch to it or you could wait for the new version that is planned for the upcoming weekend.

**Comment by annando** [comment]
We did some changes to the default values in the database so this issue should be solved.

**Comment by nytche** [comment]
Hello, solved by upgrading to 3.5
