### ISSUE TITLE
Language setting is not persistent.

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2752]
The language setting in my user profile is not persistent. On my node I had to switch the system language to stop friendica switching my profile language back to the system language.
I almost forgot about this, but today I created an account on a server which I don't administrate and the system language is german.
I can set my profile language to english but after a while it get's reset to german. Each of my systems is configured to en_US.UTF-8 - I don't install at all german locales.

**Comment by tobiasd** [comment]
I could not reproduce this on my system. Server and computer are set to `LANG=de_DE.UTF-8`. I've set the language used for Friendica to `en` in the user settings, while the system is set to `de`. For the last two weeks (since I've made these settings) the language was always English.

**Comment by rebeka-catalina** [comment]
On squeet.me the system is german. When I put the language in my profile to english it will set back to german again and again and again. It's really annoying stuff.
I had the same on f.belug.de, but there I'm the admin, so I changed the system language to english.

**Comment by Hypolite** [comment]
I had that issue as well, I changed my user language to english on my instance but less than a day later, my account settings had been reverted to french. It stopped switching back to french when I set the system language to english in the Admin panel.

**Comment by tobiasd** [comment]
What browsers are you using? I'm running Vivaldi (Chromium based), maybe there is a browser problem?

**Comment by Hypolite** [comment]
Using Google Chrome Version 53.0.2785.116 m

**Comment by tobiasd** [comment]
That is almost the same version as Vivaldi uses (Chrome/53.0.2785.122). In Vivaldi one cannot change the preferred language at the moment though. I had no problem using Firefox so far; so I might just try to use Chrome for some time with Friendica.

**Comment by Hypolite** [comment]
Just stumbled on a visual example: 
![friendica_mixed_language](https://cloud.githubusercontent.com/assets/925415/18820542/6e7a64ee-836c-11e6-9c1c-9b3ce1f67d71.png)

In the Admin -> Site Settings, Language is visibly set to "en"
In my Account Settings, Language is visibly set to "fr"

The whole interface is in english, only the notifications are in french. I'm going to switch my account language to "en", let's see how long it takes to switch back. Is there any language auto-selection based on geolocation, whether it's the user or the server? My server is hosted in France.

**Comment by rebeka-catalina** [comment]
I've got the problem with firefox and vimb (webkitgtk)

**Comment by zotlabs** [comment]
Just for a data point, my account language had been set to English and this morning I logged in and it had changed to french without any settings change on my part. I changed it back to English. In my case it doesn't seem browser related. The DB setting changed without my intervention. 

Worth noting that since Friendica no longer honours the browser language it can be very difficult for some folks to find a place in the interface to change the language since it may all be in another language. My account was in French and I believe the site is in German. I'm sure the decision not to use the browser setting was made for good reason but it's a huge usability issue. On my initial registration on this site I had to find my way around in another language until I had logged in and got the registration email (also in another language)  and could finally login and get to a settings page - and I only succeeded because I knew approximately where to change this.  The decision to not use the browser language should probably be reviewed.

**Comment by AlfredSK** [comment]
On libranet.de I have set system language (admin/site) to "en" and user language to "en". Without logging in the page is presented in German. Why is that? Geo location? Browser language preferences? I don't know. 
After logging in the interface is in German and user language is set to "de". Why? So I set it back to "en" and save it. Interface is in English now. But after logging out and in again the language is back on German and the setting has been magically switched back to "de". 
This happens with Firefox/49.0 (Ubuntu Linux) and Chromium/52.0.2743.116 (Ubuntu Linux) both with language preferences set to de-de, de, en-us, en. But I also tried en-us, de-de, de, en with no difference at all.

**Comment by tobiasd** [comment]
Yes maybe we should consider it. But make it better working then before. I remember having to set the language with the "Flag" tool on a regular basis and many complains in the support channel that the language was screwed up.Which was the reason to make it a setting.

Just tested in Chrome. For me it sticks to the language set in the browser settings. Regardless of the settings in the admin panel or the user settings. Firefox and Vivaldi honors them and at least for me stick to them.

**Comment by rebeka-catalina** [comment]
I also couldn't find out the trigger. I'm pretty sure, that $some_action somewhere triggers something to change the language back to the system language, because I also had it sometimes, that I set the profile language to english and just a few minutes later it got set back to german. It's really annoying - on f.belug.de I had trouble as well. Also one of our users told me, when the system language was set to english "Hey, I always have to set the language to german again and again and again"
so I changed the system language to german and since that day I had to change back my profile language back to english again and again and again. 
After a while I switched the system language back to english, becaus I prefer english, but as it's so annoying for me, I think it's also very annoying to others and since I created a second account on squeet.me, where the system language is set to german and now I've got this problem again. That's why I opened this issue.

I think it's not a very big problem, but it can be really annoying. Sometimes I open the menu and look for example for 'messages' or 'settings' and I check the menu entries from top to bottom and back and down again and then I just see that the language got set back to german.

@tobiasd I'm not sure, but I don't think that there's a connection to the browsers we use.
I'm now on FF 45.4.0 develop, but I've had the problem also with a Version of 38.x.x, 45.3.0 and also with webkit-browsers.

**Comment by tobiasd** [comment]
Ok, when you had the problem with an older Firefox as well. It was just a thought as Vivaldi changed behavior with a new version and FF still works as expected for me.

It is strange though, that the language gets set to *different* languages (system language,preferred browser language)

**Comment by rebeka-catalina** [comment]
Well, it can take hours or a day until the language gets changed, or just a few minutes :-/

By the way : I don't use the "browser location" setting. Of course not, because it's located in germany and I want english as language for the interface.

**Comment by AlfredSK** [comment]
I'm confused. I tested this with FF on Android now. I switched the browser language from "System" (German) to "English US". Now everything in Friendica is set and shown in English. So, my conclusion is that the language settings in Friendica (admin/site and settings/basic) have no function at all (except respecting the system/browser setting).
In my opinion there should be an option "use browser language" OR use the language which is set in user settings (/settings). But please no weird, hard to understand mixture of both.

**Comment by Hypolite** [comment]
Another good one that just happened:
- Was logged on Chrome on Mac OS X to [my Friendica server ](https://friendica.mrpetovan.com) (system: en, user: en, interface: en)
- I closed the browser completely (Command + Q)
- Opened Chrome again, opened Friendica, the interface is in french.
- I directly went to my user settings through the dropdown menu, the interface is back to english and the language displayed is indeed "en". System language is still "en" as well.

**Comment by tobiasd** [comment]
What is the preferred browser language setting?

**Comment by Hypolite** [comment]
Not sure what you are talking about, is it in the Friendica Admin? The User Account settings? My own browser settings?

**Comment by tobiasd** [comment]
I'm playing around with it this evening in the vagrant machine.

**Comment by rebeka-catalina** [comment]
Isn't there a possibility, that the system language is set by the admin and becomes the default and the default get's overwritten by the profile language ?

**Comment by Hypolite** [comment]
> Isn't there a possibility, that the system language is set by the admin and becomes the default and the default get's overwritten by the profile language ?

This is the expected behavior: the admin of the server sets the interface language of the website, but individual users can change the language to whatever they want, overriding the server language setting.

**Comment by rebeka-catalina** [comment]
> This is the expected behavior

Yes, I know, but for me it sounds like there was some code to get values from browser. 
I mean a simple setting, which does what has been set, without any auto-magic.

**Comment by Hypolite** [comment]
I'm not aware of any browser language settings import, but that would explain the sudden switches better than anything else.

**Comment by tobiasd** [comment]
In `ìnclude/security` lines 82 to 86 save the current browser language to the DB. In `index.php` than the browser language is used (as it was just saved). But this was set at least in 2012 makes me wonder why it worked in the meantime.

I'll watch it on my node a bit before making a PR for it.

@zotlabs do you remember why you saved the language at that point into the database?

**Comment by tobiasd** [comment]
@rebeka-catalina @Hypolite sure, there is browser language checking. It was the default in the beginning but confused many user and was also not reliable. So we changed it some time back. I think I've found a problem, though it won't fit for the server system language settings I think.

**Comment by Hypolite** [comment]
What about this: `if($login_initial || $login_refresh)`

`$login_initial` makes sense but when is `$login_refresh` set?

**Comment by tobiasd** [comment]
it is set in `include/aut` during the login process.

**Comment by rabuzarus** [comment]
I'm not really inside this topic but if someone is trying to fix this it would be nice if the language for not logged in users would be the one of the browser (Just thinking of visiting a russion friendica profile and can't navigate because I don't understand the menu points)

**Comment by tobiasd** [comment]
That was my idea as well @rabuzarus

**Comment by zotlabs** [comment]
What we're currently providing in hubzilla (based on the original/old friendica model, with only minor modification):

1. Use the browser preferred language, in the order given by the browser and based on the translations available
2. If no browser preference or no match for the browser preference, fall back on the site preferred language.
3. if no site preferred language fall back to English

4. Allow translation developers or those with unique needs to over-ride the language for a $_SESSION via a special/hidden page (we have an app mapped to this in hubzilla). This $_SESSION value over-rides all other language settings including the browser. It is rarely used. 

5. Save the language which was used on account creation (usually the browser language) as the account language. This is primarily/only used in email notifications since there is no browser to give us hints.

**Comment by Hypolite** [comment]
Switched again to french, and it only affected the notifications.

**Comment by tobiasd** [comment]
I'm on it, you don't need to fill in more "it happened again" ;-) I have now various browsers with funny browser language combinations to test with the Vagrant machine. Just need some more time fiddling around with it.

**Comment by Hypolite** [comment]
No problem, I just wanted to add the language reordering trick that didn't work.

**Comment by rebeka-catalina** [comment]
This is just a test if it's really possible to reply with an email -
I've just seen the reply.github.com address in From-header and have to
try it out - you can ignore this, if it works. :-D

**Comment by Hypolite** [comment]
It works!

**Comment by rebeka-catalina** [comment]
Yes \o/ Very nice feature :-D

**Comment by Hypolite** [comment]
I don't want to pile one, but since this morning I can't switch back to english at all. I'm on the `develop` branch.

**Comment by tobiasd** [comment]
A month of testing in the development branch, what is the state for you with this bug?

**Comment by AlfredSK** [comment]
Well, if you ask me I would say it is fixed. :)

**Comment by rebeka-catalina** [comment]
On 2016.11.06, Tobias Diekershoff wrote:
> A month of testing in the development branch, what is the state for you with this bug?

I'm pretty sure it's fixed now :-)

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/friendica/friendica/issues/2752#issuecomment-258676403

-- 
„Wo kämen wir hin, wenn jeder sagte, wo kämen wir
hin und keiner ginge, um zu sehen, wohin wir kämen,
wenn wir gingen.“
	~ Kurt Marti ~

**Comment by Kulak** [comment]
I went to <https://squeet.me/friendica>.  It reports version:


My laptop is in United States and set to display English.   Instead on Safari the web page displayed in

    Dies ist Friendica, Version 3.5.2-dev die unter folgender Webadresse zu finden ist https://squeet.me

On Safari I could not find Accept-Encoding request header.

On Chrome I got:

   Это Friendica, версия 3.5.2-dev работает на веб-узле https://squeet.me

(That's Russian).  At least I can read Russian.

Chrome reported request headers:

```
GET /friendica HTTP/1.1
Host: squeet.me
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
DNT: 1
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: PHPSESSID=6ao3kmd5cr4n6bcg3k8jv1p4a3

```

**Comment by Hypolite** [comment]
Can you try looking at https://friendica.mrpetovan.com?

By the way, it's in Russian because your browser told Friendica you can read it. The German part clearly was a problem.

**Comment by Kulak** [comment]
Chrome request:

```
GET / HTTP/1.1
Host: friendica.mrpetovan.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
DNT: 1
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: PHPSESSID=dqttuhttp8o80ilnos9o0i54j4
```

Response page included Russian main menu (Посты, Информация, Фото, Видео, Мероприятия, Контакты)

That's a Chrome browser 57.0.2987.133 on Windows 10.

My default location, locale and language are United States, English.

**Comment by Hypolite** [comment]
Confirmed, expect incoming patch.
