### ISSUE TITLE
<br> tags in codeblocks when sending posts to diaspora

### ISSUE THREAD

**Issue by svbergerem** [friendica/friendica#2775]
You can find an example here: https://pod.omgsrsly.net/posts/190625

Inside the code block there are `<br>` tags, which aren't in the [original post on pirati.ca](https://pirati.ca/display/ec054ce72057d3af783c436523896730).

(You can also see `<key>` tags in the post which currently aren't supported in CommonMark. One could replace them by inline code blocks or just keep the current solution. That's just a matter of personal preference.)

**Comment by annando** [comment]
This is a bug in the underlying HTML2Markdown parser. Maybe there is some updated version that fixed this problem.

**Comment by annando** [comment]
Isn't this now solved with one of the last pull requests?

**Comment by Hypolite** [comment]
Fixed via #3295

**Comment by tobiasd** [comment]
So, is this working now?

**Comment by annando** [comment]
If no one disagrees we should close it. If someone experiences the problem again, we can reopen it.

**Comment by svbergerem** [comment]
> If someone experiences the problem again, we can reopen it.

Sounds good to me.
