### ISSUE TITLE
After upgrading to Asparagus PHP errors show in the log and all content is temporarily "gone"

### ISSUE THREAD

**Issue by steinhobelgruen** [friendica/friendica#2780]
Hi,

After upgrading Friendica to Asparagus (git pull method), all content temporarily disappeared. Then a spike in the number of php-processes appeared (presumably performing some sort of database update) and after about half an hour everything seems to have reappeared.

Still the logs show:
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/htdocs.fnordica/mod/ping.php on line 344, referer: https://fnordica.de/network?f=&order=post&`
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/htdocs.fnordica/mod/ping.php on line 381, referer: https://fnordica.de/network?f=&order=post&`
`PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/htdocs.fnordica/mod/network.php on line 731, referer: https://fnordica.de/network?f=&order=post&`
(1000s of each line)

Is that still the update running or is there a problem?

Web Server is Debian Wheezy, Apache 2.2.22 / PHP 5.4.45
DB Server is Debian Wheezy, Dockered MariaDB 10.0.22

Cheers,
Thomas Renger, https://fnordica.de/profile/dentaku

**Comment by annando** [comment]
This temporarily vanishing is caused by background processes that update the data. For some time (hours, days, ...) not all content is available - until the update was completed.

Concerning the warnings: Could you have a look in the logfile for entries with "dba.php" in it? Maybe some query fails.

Additionally please execute this command in the command line:

````
php include/dbstructure.php update
````

Maybe some database update wasn't finished.

**Comment by docbray** [comment]
I just had an issue, and not sure if it is related to this or not. I had a similar spike in PHP activity on my server after upgrading to the latest version last night. Except it locked up my server and had to restart. After restarting, everything looked to be working fine, and no more PHP spikes.  Not sure if related to the my core problem, though which is...

Today, when I go check my profile on my site it says that "Requested profile is not available", and my posts are not appearing at all. The weird thing is that I can still login/out, I can set my profile settings, and this account is an admin account and I can do everything admin related. But my avatar no longer shows. I can still see the photos I've uploaded, though. 

Logs have this to say about it (if it helps):
`
2016-09-16 09:36:20@9crgqi4258nudm95cf9bos0dp2	[DEBUG]:identity.php:50:profile_load	profile error: profile/docbray?tab=profile`

**Comment by annando** [comment]
@docbray First of all: Have you checked if the database structure changes are done? Please execute the command that was mentioned above.

Then please have a look in the logfile for entries before this entry you posted. The value in the logfile behind the "@" is the session id (9crgqi4258nudm95cf9bos0dp2). So please post these lines as well.

Additionally have a look for entries with "dba.php" in it.

**Comment by steinhobelgruen** [comment]
The 
`php include/dbstructure.php update`
(and then some waiting) did the trick. I only lost two test messages that I posted on my Friendica-Timeline befor the DB update.
