### ISSUE TITLE
[XMPP] Authentication does not work after a few hours

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#2781]
I'm having latest develop from friendica and master from friendica-addons, I'm getting this in logfile:

```
Mon, 19 Sep 2016 10:49:15 +0000 [MySQL] invalid query: SELECT `uid`, `password` FROM `user` WHERE `nickname`='roland'
Mon, 19 Sep 2016 10:49:15 +0000 [exAuth] got password
Mon, 19 Sep 2016 10:49:15 +0000 [exAuth] authentification failed for user roland@f.haeder.net
Mon, 19 Sep 2016 10:49:52 +0000 [exAuth] stop
Mon, 19 Sep 2016 10:49:52 +0000 [exAuth] stop
```

The nickname has the uid=1, also with others it is happening (but working for somet time only).

**Comment by annando** [comment]
What happens if you kill the "auth_ejabberd.php" process? Is it then working again?

**Comment by Quix0r** [comment]
I always had restarted ejabberd. Okay, I try this out.

**Comment by Quix0r** [comment]
Yes, that helped again. Maybe turn on error-reporting (E_ALL | E_STRICT for older PHP versions) and check if notices are coming?

**Comment by annando** [comment]
Maybe the SQL connections gets lost after some time. That would explain why restarts of that process are a solution.

**Comment by Quix0r** [comment]
Is this okay?
````
        ├─beam(23303)─┬─auth_ejabberd.p(16689)
        │             ├─auth_ejabberd.p(16818)
        │             └─inet_gethost(23470)─┬─inet_gethost(23471)
        │                                   └─inet_gethost(23472)
 ````

**Comment by Quix0r** [comment]
I could do this:
> $ ps -ax|grep $USER|grep php|cut -d " " -f 1
And kill all found processed but that is only a work-around. better is that auth_ejabberd.php disconnects from database after an hour of inactivity and then reconnect once activity (auth requests) are coming.

I do this here at work with a daemon that had same issues until I fixed it as described above:
- disconnect from database after 1 hour of inactivity (that hour avoids massive disconnect/reconnect)
- reconnect if authentication is requested again

**Comment by annando** [comment]
I will examine both options.

**Comment by Quix0r** [comment]
Thank you for rewriting it. I have just undone my work-around as it was no fix anyway and I know have to hard-kill (KILL signal) the beam process, the php processes seem to not respond not even  on KILL.

**Comment by annando** [comment]
The pull request was accepted. If you are on the develop branch you can update your system and check if it is now working better.

**Comment by Quix0r** [comment]
Still this case, sorry. But at least I just have reload and then it connects back.

**Comment by annando** [comment]
Could you check if the authentication process is restarted when you are having this issue? And please have a log in the logfile for this process. (There is a special logfile for this)

**Comment by Quix0r** [comment]
A situation where it fails:
````
Wed, 12 Oct 2016 09:54:00 +0200 [MySQL] invalid query: SELECT `uid`, `password` FROM `user` WHERE `nickname`='roland'
Wed, 12 Oct 2016 09:54:01 +0200 [exAuth] got password
Wed, 12 Oct 2016 09:54:01 +0200 [exAuth] authentification failed for user roland@f.haeder.net
Wed, 12 Oct 2016 09:54:01 +0200 [exAuth] stop
````
And where it works after 2nd attempt (password X-ed out):
````
Fri, 14 Oct 2016 21:07:14 +0200 [exAuth] start
Wed, 19 Oct 2016 09:43:25 +0200 [exAuth] authentification failed for user roland@f.haeder.net
Wed, 19 Oct 2016 09:43:25 +0200 [exAuth] stop
Wed, 19 Oct 2016 09:43:40 +0200 [exAuth] start
Wed, 19 Oct 2016 09:55:02 +0200 [exAuth] got password xxxxx
Wed, 19 Oct 2016 09:55:02 +0200 [exAuth] authentificated user roland@f.haeder.net
````

**Comment by Quix0r** [comment]
Style thing: avoid using sizeof() as it is an alias for count() and it may confuse c programmers where sizeof() gives the allocated memory back which is not the behaviour of count().

**Comment by annando** [comment]
Problem is that you lose your database connection after some time. So the system has to reconnect - but it only detects this with the next authentication request. Maybe I find a workaround, let me think ...

**Comment by Quix0r** [comment]
Here is an idea:

- once a query was executed, updated a "last_queried" timestamp (in PHP code)
- in a loop, wait for incoming queries
- if the timestamp is to far from current timestamp, drop connection manually

This way is more clear because no timeout occurs.

**Comment by tobiasd** [comment]
Has the PR by @annando fixed the issue you had/have @Quix0r ?

**Comment by Quix0r** [comment]
No, still no login. https://f.haeder.net/http-bind - what is wrong here?

**Comment by annando** [comment]
This is some issue with your XMPP server, unrelated to Friendica.

**Comment by Quix0r** [comment]
Maybe not entirely:
`2018-05-13 xx:xx:x.xxx [critical] <0.3915.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'`
Keeps flooding here.

**Comment by Quix0r** [comment]
Was wrong user/group, must be `ejabberd.ejabberd` on it. Still issue is there.

**Comment by Quix0r** [comment]
Fixed! In `ejabberd.yml` I had to set `tls: false` for http-bind listener. OMG, makes no sense having TLS on `127.0.0.1`, right? ;-)
