### ISSUE TITLE
Issues with MySQL 5.7

### ISSUE THREAD

**Issue by annando** [friendica/friendica#2786]
Using Friendica with MySQL 5.7 can make problems since it doesn't accept the value "0000-00-00 00:00:00" in datetime fields anymore.

Quick solution see here:
https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html

In the first step we should link to this in our documentation. But we also should change Friendica so that this isn't a problem anymore.

**Comment by tobiasd** [comment]
It's now documented, so I move this to a later milestone.

**Comment by annando** [comment]
This issue should already been solved.

**Comment by annando** [comment]
This issue is solved, I think.
