### ISSUE TITLE
Switch to Markdown for post formatting

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2810]
Yes, I know that BBCodes were all the rage 15 years ago, I was there, it was glorious, then we had a WYSIWYG phase that was horrible, then the wiki syntax took over, and then Markdown came upon us, and it was glorious again.

Markdown is a discrete formatting engine that relies on the least amount of added characters to provide bold, italic, titles, lists, link, embeds, etc... It is currently used by a variety of software, including GitHub, the Atlassian suite (Jira, Bamboo, BitBucket, etc...), and especially Diaspora.

Friendica is currently receiving and decoding Markdown messages from Diaspora and sending specially Markdown-encoded messages back. I'd suggest we cut the translation and we switch to Markdown by default for Friendica posts.

Since we have an cached HTML version of the posts, I don't expect too much trouble enabling this change. The code can be changed right away, and the raw content of the posts can be converted in the background. The only issue I can think of would arise if someone tries to edit a post that hasn't been converted to Markdown yet. The raw message would still be including BBCodes, but it would then be interpreted as Markdown.

Technically, we already ship the Markdown library with Friendica, it's then just a matter of switching the raw-to-HTML function and simplifying a lot of Diaspora-related code.

What do you think?

**Comment by tobiasd** [comment]
Does markdown support all the things that can be done with current bbCode? Spoilers, colorized text, naming the person you quote in a blockquote, alignment of texts, inclusion of maps? Tables in Markdown also never really worked out for me. 

Also, github is not the developers or support forum.

**Comment by fabrixxm** [comment]
There was the idea to allow pluggable post editors, to give the user the option to select between bbcode or markdown or rich text (I know there is already, but isn't supported and isn't pluggable) or wathever, given that every editor pass to the backend the text in bbcode...

The main problem is that we use bbcode not only as text formatting but also as "transport" (see attachments, reshares and so on).

**Comment by Hypolite** [comment]
Welp, case closed.

**Comment by annando** [comment]
I think we could store the content markup type along with the content. Wen interacting Diaspora, we work with Markdown. When interacting with GNU Social, we use HTML. And Friendica is using BBCode.

When we would store the content along with the type, then we could use different processors to render the content - without the need of multiple translations.

Concerning our use of BBCode for some transport stuff: I don't really like it - although I create several markup elements :-)

I would like to make these elements obsolete. Then we really could switch between several languages without any problem.

**Comment by Hypolite** [comment]
I looked at how Diaspora manages the shared content: it doesn't allow to add any content to the reshare. Subsequently, there are no cases where there is Markdown formatting and then an embed post like we can do in Friendica. Not sure about multimedia though.

As a rule I don't like to allow plain HTML in editing fields, and it looks like we would have to come up with a lot of Markdown extensions to cover all the cases that exist woth BBCodes. Not worth it.

**Comment by annando** [comment]
What I meant was that we should to shared content in a way that we say: Reshare item XZY and use content YXZ as annotation to it.

**Comment by fabrixxm** [comment]
ouf. I can add only one :+1: . count it as 100 :-)

**Comment by Hypolite** [comment]
Note sure I understand what you mean @annando, am I missing something? 🤔

**Comment by annando** [comment]
We should do reshares in a way that we say: "We reshare item XYZ. Additionally we comment it with the following text ...". At Diaspora you can only do naked reshares and no comments. But other networks (for example Twitter) can do comments for Reshares (Retweets).

And additionally to the comments for reshares (and naked reshares) we should introduce more structure for sharing links, attachments, ...

I'm not sure when I can do that, but it is definitely on my list.

**Comment by Hypolite** [comment]
That's what the ˋ[share]` BBCode is already doing, AFAIK?

**Comment by fabrixxm** [comment]
yep, but it's a misuse of a formatting language.
DFRN, the protocol friendica use to federate, is based on Activity Stream 1, that's Atom with some custom tags.
In activity stream you usually build an xml that means "user" "verb" "object".. like "Annado" "reshared" "this post from Hypolite" (that's the simple version of the story)
every items have a textual field for clients that doesn't not unterstand the "verb" or the "object", so ideally the textual field should be literally "Annado reshared this post from Hypolite: link". If the receiving node don't know the "reshared" verb or don't know how parse the "post" object, it shows to the user just the textual field.

That's how like, dislike and so on works: "Hypolite" "like" "this post from Annado"

ATM, we are using the textual field to carry formatted data that should be in transport XML..

If the "user" "verb" "object" is well defined we can have many verb that apply to many object:
- "write", "share", "like", "dislike", "comment", "merge"
- "post", "link", "file", "photo", "video", "audio", "pull request", "commit" ;-)

**Comment by Hypolite** [comment]
Gotcha, thanks for the explanation!

**Comment by annando** [comment]
BTW: @Hypolite how good are you in doing front end stuff? One step that prevents us from using other markup languages for the editing is - like it was said in this issue - the misuse of bbcode elements for actions that should be done directly via the protocol.

To prepare a solution for this my long time plan was a different editor that guides the user. For example: When sharing a link, the link information should be displayed not in naked bbcode but more like Google+ or Facebook is doing. That means that you would only be able to directly write a comment but not (accidentally) interfere in the bbcode construct for sharing links.

Same goes with reshares. I really would like it if the user would press the reshare button. Then the message would appear that is intended to be reshared. The user can add a title a comment or a hash tag - but couldn't apply changes in the reshared content itself.

When we do this we can - in a next step - store and transmit the data in a more structured way.

**Comment by Hypolite** [comment]
I can do frontend stuff, but it really isn't my _forte_. I'm more than happy to fix frontend stuff (as my PRs showed so far), but coming with creative way of showing a text editor isn't a fun thing for me.
