### ISSUE TITLE
Double notification + wrong message for requested registrations

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2813]
I tried to create a test account to verify my work on #2804, but then I stumbled on this multipronged issue regarding registration requests in notifications:

![friendica_registration_request_notification_issue](https://cloud.githubusercontent.com/assets/925415/18939630/848d58b2-85cf-11e6-864d-98b8589ae65b.png)

Please disregard the language discrepancy, it's already being address by #2752.

There are two notifications for a single registration request, one of them being badly formatted. I dug the `ping.php` code a little, and here's what I found:
- The first notification is stored in the DB with an already translated message that end up being mangled since the contact name is forcefully prepended to the message that misses the expected contact mention at the end
- The second notification is created out of the actual registration requests

I was able to fix the first notification display, but by doing so I went back on changes introduced in the vier and frio theme. The typical notification template is the following:

    <li class="{4}">
        <a href="{0}"><img data-src="{1}" height="24" width="24" alt="" />{2} <span class="notif-when">{3}</span></a>
    </li>

vier and frio themes have the fancier one: 

    <li class="{4} notif-entry" onclick="location.href='{0}';">
		<div class="notif-entry-wrapper media">
			<div class="notif-photo-wrapper media-object pull-left"><a href="{6}"><img data-src="{1}"></a></div>
			<div class="notif-desc-wrapper media-body">
				{8}{7}
				<div><time class="notif-when time" data-toggle="tooltip" title="{5}">{3}</time></div>
			</div>
		</div>
    </li>

The placeholders are described in `main.js:265`:

- {0}  // link to the source
- {1}  // photo of the contact
- {2}  // preformatet text (autor + text)
- {3}  // date of notification (time ago)
- {4}  // vistiting status of the notification
- {5}  //date of notification
- {6}  // profile url of the contact
- {7}  // clean status text
- {8}  //preformatat author (name + profile url)

Now, the problem is that the contact name is stripped from {7}, and then prepended by {8}{7}. But not all translated messages expect the contact name in the front. For example in french, for the registration request message, the contact name is at the end. And that's exactly what is already in {3}, used by previous templates.

My questions then are:
- Why switch from {3} to {8}{7}? Is there a specific reason I can't possible deduce from the code?
- Why not go back to {3} since fixing {8}{7} produce exactly the same result?
- Why two different notifications for registration requests? Is it an artifact of a legacy system?
- If yes, which way is the "canon"?

**Comment by rabuzarus** [comment]
> Why switch from {3} to {8}{7}? Is there a specific reason I can't possible deduce from the code?

Do you mean {2} //preformated text instead of {3} //date of notification?
I introduced {8} to give the themes more control of how to display notifications in different themes because I'm not a fan of hardcoded stuff.
I think as far as it is possible the core code should give only plain text (without html elements and css classes) and leave it to theme to create the elements.

E.g. frio is the only theme which does make a heavy use of bootstrap. So it was really annoying to have that much hardcoded elements in the core where I can't change the css class to a bootstrap class.  Or to construct the html elements the way I want to change it.

**Comment by fabrixxm** [comment]
> I think as far as it is possible the core code should give only plain text (without html elements and css classes) and leave it to theme to create the elements.

:+1: 

in this case I think we could use only the plain text notification and remove the link on contact name (we already have it on photo), which is less important than the actual link of notification (i think I never clicked on username on a notification on purpose...)

**Comment by rabuzarus** [comment]
The idea behind the link in the notifs is to have a possible hover card if he/she hovers over the author link to get more information about the author . But there was a bug that I didn't get solved (The hovercard was opened in the notification popup and the width of the hover card was limited through the width of notification popup).

On the other side it was a decision for consistency. At other places in friendica we always link the author with his/her profile url

**Comment by fabrixxm** [comment]
I understand that, but replacing the username from plain text with linked username client side is error prone. Get the example from @Hypolite . you could do somenting like

```js
   plain_text = plain_text.replace(username, linkedusername);
```

just before populate the notification template, but if the user calls himself something that could appear on notification message, we are back here.

**Comment by rabuzarus** [comment]
@Hypolite I'm not familiar with french. Is there a possibility in french to change the translation so the author name could be at the beginning of the sentence?

**Comment by Hypolite** [comment]
Yes, using the passive voice. What about RTL languages like Arabic or Hebrew? Not sure prepending would always work.

Also, what about the double notification for reg request? Which one should be kept?

**Comment by rabuzarus** [comment]
> Yes, using the passive voice, but the original translation term in english has the name at the end. I only saw the french version because of the language selection issue. And what about RTL languages like Arabic or Hebrew? Not sure prepending would always work.

Yes you are right. I'm not very familiar with this language topic. Do you want to step into this topic and try to fix it (if it's possible can try to keep the link to the author url)? Sry for not having the  time to step into it.

> Also, what about the double notification for reg request? Which one should be kept?

I'm for the one which comes from the `register` table (the other one comes from the `notify` table). But this should be discussed with the other developers.

My reason for voting to keep the notification from the `register` table is that the message text in the `notifiy` table is hardcoded (e.g. already translated). With keeping the notifications from the `register` table we would have more possibilities. But this is just my opinion.

**Comment by Hypolite** [comment]
> Do you want to step into this topic and try to fix it (if it's possible can try to keep the link to the author url)?

Definitely, we already have the contact link, and we can add it to the translation at the right place through the `format()` Javascript function.

> My reason for voting to keep the notification from the register table is that the message text in the notifiy table is hardcoded (e.g. already translated). With keeping the notifications from the register table we would have more possibilities. But this is just my opinion.

Same here, I just didn't to go ahead and destroy everything.

**Comment by Hypolite** [comment]
Actually, I just found a side effect with removing the `notifiy` record and keep the generated notification based off the `register` table. Notifications are expected to be turned to seen when the relevant item is accessed. However, with auto-generated notifications for registration approvals, it stays unseen until the registration is actually approved, and at this point it disappears entirely from the notification dropdown.

Is it an expected behavior?

**Comment by annando** [comment]
I changed the behaviour some versions ago when I often had the situation that I forgot about these requests.

I added the auto generated notifications so that they only vanish when the person decided to accept or reject the account request. Same goes for contact requests which should only vanish when we decided to accept or reject the contact request.

I think that there are two classes of notifications: The one that are only notifications that something is happened. And the other one that request an action. These should stay unseen until the action was done.

**Comment by Hypolite** [comment]
> I think that there are two classes of notifications: The one that are only notifications that something is happened. And the other one that request an action. These should stay unseen until the action was done.

It makes perfect sense and I'll leave it like that. On Facebook the "action required" notifications (the contact request) are in a separate page but it's the same principle, it doesn't go away until you actually do something. I don't think that those notifications should then linger because an action has been taken and following the notification link again would not be useful any more since the item would have disappeared (either registration request or contact request)

> This means that you could have 20 seen notifications and the 21st position is an unseen one. When you work at this place, could you fix this as well?

I don't see a problem with that, notifications are ordered by time and I don't think it should be any different. We already show the 50 latest notifications in the dropdown, which should be ample enough not to miss anything, but should you, there's the notification page for you.

I'm perfectly happy with the current state of the notifications and I won't tinker with it anymore unless something really wrong shows up.
