### ISSUE TITLE
[Admin] Unable to save config items present in .htconfig.php but not in DB

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2816]
I was trying to set the default system theme in the Admin when I noticed that my selection was not remembered, while I could see other config changes being correctly saved.

It turns out the admin save action checks for the existence of a config value before trying to insert or update a row in the database. However, if a default value is defined in the `.htconfig.php` file, the config value will be considered to exist in the database, but the resulting `UPDATE` query will be unsuccessful because the record doesn't exist.

This issue can be averted by using the `REPLACE` query statement which create a record if it doesn't already exist in the table, or update the row if it exists. However, it relies on a `PRIMARY` or `UNIQUE` key, which would be on the couple of fields `config.cat` and `config.k`. There already is an index on those fields, but it's not set as `UNIQUE`.

I don't know how complicated it is to push a database migration change, and depending on the difficulty, I can propose an alternative fix which wouldn't rely on such a key by adding a simple existence check query before the `INSERT` or `UPDATE` query. Please note this wouldn't be ideal because it would significantly slow down the admin settings save action.

As a side note, the `.htconfig` header stating:

    /* *********************************************************************
     *  The configuration below will be overruled by the admin panel.
     *  Changes made below will only have an effect if the database does
     *  not contain any configuration for the friendica system.
     * *********************************************************************/

Is not exactly true at the moment, since any value present in the file but not in the DB cannot in fact be updated through the Admin Panel.

**Comment by zotlabs** [comment]
Might wish to avoid REPLACE if there are any ambitions of supporting POSTGRES which uses slightly different conventions. It isn't as elegant to check for row existence and then INSERT or ALTER accordingly, but it is the most portable solution in the long run. I see a race condition once or twice a year in the row existence check, so the choice is yours. It's almost always the same value so the race condition has never caused data loss to my knowledge.  It's either that or 'if postgres do this; else do that;' 

On the existence issue, it appears that the original code has been replaced but the cut/paste may have been a bit hurried. When checking for existence, we originally set $instore to check if it existed on disk, as opposed to existing in memory. This has been renamed to $refresh but the variable inside the function is still called $instore. If you change '$instore' to '$refresh'  in include/Core/Config.php it may actually work as desired. We no longer do this the same way in hubzilla, and instead re-wrote most of this lib code; but renaming the var would be the quickest way to fix the regression.

**Comment by Hypolite** [comment]
Good point about standard SQL, although I'm not risking race conditions either. My question was about Friendica's schema flexibility, not about standard SQL. I just thought about using "ON DUPLICATE KEY" which answers your concerns but still not mine about the difficulty of changing the nature of an index in the database for a minor version update. Is adviseable?

I will rename the variable if it's the absolute safest way of doing stuff, e.g if there's currently no reliable way of patching existing installations' database.

**Comment by zotlabs** [comment]
The database and database update procedures have changed dramatically since I left the project. You'd need to ask @annando ; however the cat and k values are only unique when considered together (as you've probably ascertained); not separately - and you can't use the same scheme with pconfig, where cat, k, and uid together make a unique entry.

**Comment by annando** [comment]
So config values aren't inserted under some special conditions? AFAIK @rabuzarus or @fabrixxm had rewritten the config class. This has to be done there.

**Comment by Hypolite** [comment]
The current problem is the existing DB value check that is satisfied by a value from ˋ.htconfig`. My suggested fix would be a performance improvement since this check wouldn't be needed anymore. However it requires a DB structure change, and I know how touchy it can be.

**Comment by Hypolite** [comment]
I submitted a hotfix PR to fix the issue while we can continue talking about the viability of the schema change.

**Comment by Hypolite** [comment]
I found the `update.php` file where I added a new DB update.
