### ISSUE TITLE
Move translation language folder in a subfolder of view

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2817]
This is a minor inconvenience, but it already happened a few times for me. I'm looking for a specific term in the whole Friendica codebase, and it happens to exist in the translation file of all the languages, polluting the results. I'd like to exclude the translation folder from my search, except I can't since it's the root `view` folder that also contains the default templates and the themes.

Proposed change:

- view
   - fonts
   - install
   - php
   - smarty3
   - templates
   - theme
      -vier
      -frio
      - ...
   - **lang**
      - **fr**
      - **de**
      - **...**

It's a small change that tremendously increases the readability of the Friendica folder structure.

List of affected files:
- README.translate.md
- doc/translations.md
- include\pgettext.php
- include\text.php
- util\README
- util\make_credits.py
- util\typo.php

I'm ready to do the change as soon as I have a few approvals.

**Comment by tobiasd** [comment]
For the addons the subdirectory is `$addonname/lang/$lng` I think we should stick to one schema.

And the filelist ist missing `doc/translations.md` I think.

**Comment by Hypolite** [comment]
No issue with naming the new folder **lang** instad of **translation**.

And I thought everything in the `doc` folder was automatically generated when the help pages are built, which now sounds stupid to myself as I'm writing it. 😅
