### ISSUE TITLE
Improve error message when remote connection fails the SSL checks

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2835]
Today I tried to subscribe to [the Friendica Theme Developer public forum](https://friendica.eu/profile/ftdevs) and [the Friendica UX Watchdogs public forum](https://fc.oscp.info/profile/ux-watchdogs), and each time after submitting my own profile, I have been redirected to my own connection URL: https://friendica.mrpetovan.com/dfrn_request/hypolite

And on both occasions the following error messages showed up on the top right like on the following capture:
![friendica_public_forum_connection_issue](https://cloud.githubusercontent.com/assets/925415/19017636/5406f012-880f-11e6-990f-bdc17900f8c3.png)

Trying to connect to the public forums again tells me that I already introduced myself, and they don't appear in the public forums list on the right aside.

**Comment by annando** [comment]
In which format have you entered your profile? And you are right. The messages are really weird.

**Comment by Hypolite** [comment]
I used the full URL: https://friendica.mrpetovan.com/profile/hypolite

I tried to connect with other user profiles using the short form (hypolite@friendica.mrpetovan.com) but it usually failed, so I stuck with the long form.

**Comment by annando** [comment]
With the long form it should work. I will check for the origin of the error message. Hopefully it is something with the old Friendica version.

**Comment by annando** [comment]
Hmm, the errors are created here: https://github.com/friendica/friendica/blob/master/mod/dfrn_request.php#L120-L138

On my system the checks work just fine - but in the current version the probe mechanism was rewritten completely.

**Comment by annando** [comment]
I guess this was fixed with pull request https://github.com/friendica/friendica/pull/2854.

**Comment by Hypolite** [comment]
Unfortunately it wasn't. I'm running the `develop` branch on my server, and I too hoped that the webfinger issue would solve this one, but I still got the same errors after updating my codebase.

**Comment by annando** [comment]
Isn't the error generated on the remote site?

**Comment by Hypolite** [comment]
It doesn't look like it since my theme is appearing.

**Comment by tobiasd** [comment]
Is this issue fixes by #2854? If so, please close the issue

**Comment by Hypolite** [comment]
Just tested with latest `develop`, I get the same errors.

**Comment by annando** [comment]
Do you have some log file entries that could help?

**Comment by Hypolite** [comment]
Not yet, I'll try again tomorrow with full debug enabled.

**Comment by annando** [comment]
I cannot reproduce the problem. I added some logging.

**Comment by Hypolite** [comment]
Alright, I have a partial answer. My server can't determine https://fc.oscp.info/profile/ux-watchdogs profile data because the SSL certificate has expired. No profile data, no connection.

````[NORMAL]:network.php:136:z_fetch_url    fetch_url error fetching https://fc.oscp.info/profile/ux-watchdogs: SSL certificate problem: certificate has expired````

Not sure about https://friendica.eu/profile/ftdevs though. I tried to connect again but I forgot to turn on debug, and when I tried again with debug on, the remote server told me I already introduced myself. How long before it "forgets" that I introduced myself?

**Comment by rabuzarus** [comment]
>How long before it "forgets" that I introduced myself?

It will never forget it :-/ It is stored in the db and needs to be removed by hand

**Comment by annando** [comment]
You could create a secondary account for testing. With enabled logging (debug mode) you then could try again.

**Comment by tobiasd** [comment]
I could not reproduce this with the current develop branch code with a fresh test account. I had to force my browser to make an exception for the bad cert, but the connection to the forum was established.

**Comment by annando** [comment]
Can someone now reproduce this problem? If not I would like to declare it as fixed (until further notice).

**Comment by rabuzarus** [comment]
Maybe this (https://helpers.pyxis.uberspace.de/display/adbba6c6195881e9ef5d948466219808) is related.

**Comment by annando** [comment]
I don't think so. I would however like to check the issue you linked to for the 3.5.1

**Comment by Hypolite** [comment]
Just tried to connect to https://friendica.eu/profile/ftdevs with a new account and full debug on and here's the debug result:
`[NORMAL]:network.php:141:z_fetch_url	fetch_url error fetching https://friendica.eu/noscrape/ftdevs: SSL certificate problem: unable to get local issuer certificate`

It looks like I ran into another SSL issue, although not the same as with https://fc.oscp.info/profile/ux-watchdogs

After a little poking around, I found out that it is because `friendica.eu` Let's Encrypt certificate still uses an old Intermediate Certificate (named X1) that is now inactive. It should use the newer X3 Intermediate certificate, and I believe issuing a new certificate should do the trick.

Attached `openssl` tests:

````
~# openssl s_client -showcerts -crlf -connect friendica.eu:443
CONNECTED(00000003)
depth=0 CN = friendica.eu
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = friendica.eu
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = friendica.eu
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=friendica.eu
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=friendica.eu
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
---
SSL handshake has read 3666 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: B63A9F81DFCB6D67844F45F3E536C72A0930269CD14835FEDF7A47BC3CC1BF06
    Session-ID-ctx:
    Master-Key: 570F400AA93B5B9D0696BE9A5C55F66E7BE73A17B4760E0B754E0CD75144F381C4D4BCA9326B3A84AB3875E9C8C08724
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket: [...]
    Start Time: 1487136760
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
````

````
~# openssl s_client -showcerts -crlf -connect friendica.mrpetovan.com:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = diaspora.aeriesguard.com
verify return:1
---
Certificate chain
 0 s:/CN=diaspora.aeriesguard.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=diaspora.aeriesguard.com
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
---
SSL handshake has read 3172 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: F410CD1489BB8464D9BA31661D17EF075C5DBC2068628BB0205682C9894E5CF7
    Session-ID-ctx:
    Master-Key: 0708C5C9BB9C3D3718C52C2FF6EF3CC7701B9623BDE53F2A71335B292797ADBEEA619F573C0384F22EE483A1C1E3CA9A
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket: [...]
    Start Time: 1487137400
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
````

**Comment by annando** [comment]
@rabuzarus I cannot reproduce the described issue concerning this forum.

@Hypolite sounds to me like no Friendica bug.

Can we close the issue?

**Comment by Hypolite** [comment]
Both issues I had weren't Friendica issues (SSL issues from the remotes) but the error message isn't helpful. I'll close this one because it isn't blocking for the release.

**Comment by tobiasd** [comment]
I have not looked into the code, but can the error message be made more helpful?

We could reopen this issue as a reminder then and remove the milestone.

**Comment by Hypolite** [comment]
We have the SSL error string in the Debug log, so we can definitely improve the user-facing error.

**Comment by MrPetovan** [comment]
Haven't had one of those in a while, closing for now.
