### ISSUE TITLE
Users with non XHTML themes can't use their account@friendica.instance to connect

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2850]
Since I started using Friendica with the frio theme, I never could connect using my short-form address `hypolite@friendica.mrpetovan.com`, it invariably failed. Using my full profile URL (https://friendica.mrpetovan.com/profile/hypolite) seemed to work so I didn't think much about it. Until today.

I set up a fan page account for a webcomic I'm following, and I wanted to connect with it to access its posts. However, in the connect page, I don't have the choice of address, it shows my shot-form address and there are no way of changing it. Unexpectedly, the connection request failed, which surprised me since we are on the same server.

After a quick debugging session, it turns out that during the connection exchange, the XML parsing of my profile page fails because the frio theme is using the HTML5 doctype, not the XHTML one.

I have two solutions in mind:
1. ~~Generate an XML-compliant page for profiles that would be independent of the theme so that the parser is always successful~~ (**Edit**: [It already exists](https://friendica.mrpetovan.com/xrd/?uri=acct%3Ahypolite%40friendica.mrpetovan.com) but it's apparently not used)
2. ~~Use regular expressions instead of an XML parser to grab the links, this would probably be faster than a full XML parse of an HTML document that may or may not be XML compliant~~ Not practical
3. ~~**Edit**: Find out why the XML page isn't queried instead of the full public profile web page~~ Nevermind, I assume this is needed for non-Friendica connection
4. **Edit 07/10**: Replace the XML parser by a HTML DOM parser like @annando suggests.

**Comment by annando** [comment]
Regular expressions aren't a suitable way of parsing XML or HTML. PHP has a built in XML and HTML parser that works reliable. 

I will check the issue when I'm having a little bit more time.

**Comment by zotlabs** [comment]
I don't know if it's still the case but we originally used the HTML5Parser library, which is pretty robust with a wide variety of input, from HTML1 to pure XML. the reason I used this library was because it was one of the few *HTML parsers for PHP which would rarely die or fail to parse the input, even when given hand-crafted web pages from 1995 that were full of tag errors.  If a web browser displayed the page, HTML5Parser would parse it and try to make sense of the structure, no matter how badly malformed. We did find one bug but fixed it long ago.

**Comment by annando** [comment]
We had several issues with that library in the past. There were some combinations of elements where the parser went into an endless loop. We nearly removed it from the system (there is one place left) and replaced it with the built in HTML parser from PHP which seems to be very reliable.

**Comment by Hypolite** [comment]
Updated the solutions list, I can take care of 4. probably this weekend, this is a bummer for me right now.

**Comment by annando** [comment]
I would like to reproduce it. Is it something in the probing (Probe.php)?

**Comment by Hypolite** [comment]
Yes, performing webfinger. I'm not in front of my computer right now so I
couldn't tell you which line, sorry.

**Comment by Hypolite** [comment]
Friendica Log:
````
[DATA]:Probe.php:128:webfinger_dfrn     webfinger_dfrn: hypolite@friendica.mrpetovan.com:
[DEBUG]:dfrn_request.php:466:dfrn_request_post  dfrn_request: url: ,network=dfrn
[DATA]:network.php:143:z_fetch_url      fetch_url hypolite@friendica.mrpetovan.com: 302 HTTP/1.1 302 Found
Date: Fri, 07 Oct 2016 03:37:02 GMT
Server: Apache/2.4.10 (Debian)
Set-Cookie: PHPSESSID=od9qa8ta98e0itgn2fr646kcr7; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Account-Management-Status: none
Location: https://friendica.mrpetovan.com/profile/hypolite
Content-Length: 0
Content-Type: text/html; charset=UTF-8

[DATA]:network.php:143:z_fetch_url      fetch_url https://friendica.mrpetovan.com/profile/hypolite: 200 HTTP/1.1 200 OK
````

Subsequent Error Log:
````
PHP Warning:  Invalid argument supplied for foreach() in /home/friendica/friendica/include/Probe.php on line 130, referer: https://friendica.mrpetovan.com/dfrn_request/maximumblefeed
PHP Stack trace:, referer: https://friendica.mrpetovan.com/dfrn_request/maximumblefeed
PHP   1. {main}() /home/friendica/friendica/index.php:0, referer: https://friendica.mrpetovan.com/dfrn_request/maximumblefeed
PHP   2. dfrn_request_post() /home/friendica/friendica/index.php:340, referer: https://friendica.mrpetovan.com/dfrn_request/maximumblefeed
PHP   3. Probe::webfinger_dfrn() /home/friendica/friendica/mod/dfrn_request.php:451, referer: https://friendica.mrpetovan.com/dfrn_request/maximumblefeed
````

**Comment by annando** [comment]
Today I'm on an event where I'm doing the streaming, but I will try to dig into it. 

It looks like that my test code is looking like this:

````
$data = Probe::webfinger_dfrn($url, $hcard);
````

I get the same warning.

Changing things there has to be done very careful since the webfinger function is used for many different networks.

**Comment by Hypolite** [comment]
I submitted a quick fix for this issue.

Ultimately, the problem comes from the fact that Friendica isn't returning the profile's XRD output when probed using webfinger. See `include/Probe.php:436`, the Accept-Content is set to `application/xrd+xml` but Friendica still shows the HTML profile page.

**Comment by annando** [comment]
I digged into the code. The problem was inside the "webfinger_dfrn" function that never worked like expected.

**Comment by Hypolite** [comment]
Verified, closing Issue, thanks!
