### ISSUE TITLE
Add <link>s for individual statuses

### ISSUE THREAD

**Issue by Gargron** [friendica/friendica#2864]
Profile pages have a <link> to the alternate Atom representation of the user's feed. Individual statuses should have a <link> to the alternate Atom representation of that particular entry.

Even better if you can add a `Link` header to those pages so that this information could be retrieved with a simple `HEAD` request rather than downloading and parsing HTML.

This information helps resolve unknown conversations in Mastodon (https://github.com/Gargron/mastodon/commit/4bec613897d8835bb78202c7a36691b654f14967)

**Comment by Hypolite** [comment]
@annando Is it something we can add easily?

**Comment by annando** [comment]
@Gargron Do you mean something like this? 
```<link rel="self" type="application/atom+xml" href="https://pirati.cc/api/statuses/show/406283.atom"/>```

I currently want to improve this thread resolving as well, so it would be great if you could explain it with some examples.

**Comment by Hypolite** [comment]
Apparently it's more like `rel="alternate"`.

**Comment by Gargron** [comment]
`<link rel="alternate" type="application/atom+xml" href="https://pirati.cc/api/statuses/show/406283.atom"/>` would be right, yeah

**Comment by annando** [comment]
I misread your request. Friendica already is doing so. When you visit my profile https://pirati.ca/profile/heluecht you will see this link in the source code:

```
<link rel="alternate" type="application/atom+xml" href="https://pirati.ca/dfrn_poll/heluecht" />
```

Isn't this what you wanted?

But: I would like to have some thread completion that works with the data directly in the feed item. For this we could use the ```<ostatus:conversation>``` element, I think.

**Comment by fabrixxm** [comment]
@annando that's a link to user timeline feed.
@Gargron is asking for a "personalized" link tag in /show/ or /display/ which should return a single-item atom feed (?)

**Comment by annando** [comment]
I really should learn to read text more carefully ;-)

But: Shouldn't the link then display the whole conversation?

See for example this post: https://diaspodon.fr/users/zauberstuhl/updates/1597

It contains this link:
```<link href='https://diaspodon.fr/users/zauberstuhl/updates/1597.atom' rel='alternate' type='application/atom+xml'>```

But this link only contains the single post - not the whole thread.

And that link is already part of the post:
```<link rel="self" type="application/atom+xml" href="https://diaspodon.fr/users/zauberstuhl/updates/1597.atom"/>```

**Comment by fabrixxm** [comment]
> But: Shouldn't the link then display the whole conversation?

That's why I put a "(?)" :-)

But I think we should follow what others are doing.  

Anyway, a link to (e.g.) `/display/0123ABC` in friendica, it's a link to the post with id `0123ABC`. We then show the whole conversation for convenience to the user. (often, themes will highlight the selected post, anyway).

So, I think we should offer an "alternate" view of the data the link represents: the post with that id.

**Comment by annando** [comment]
Only that single post or the whole thread?

**Comment by Gargron** [comment]
The single-entry Atom representation is necessary when we want to confirm an entry that was included in, say, a shared status, because it might not necessarily be part of a user's current feed and we don't want to paginate through all of the feed's items to find it.

**Comment by annando** [comment]
Maybe we should also add an element to the protocol that directly points to an Atom representation of the whole thread?

**Comment by fabrixxm** [comment]
> Maybe we should also add an element to the protocol that directly points to an Atom representation of the whole thread?

what do you mean "to the protocol" ?
here we are talking about a link tag in html page returned by friendica on `/display/<id>` urls

**Comment by annando** [comment]
I meant adding some additional element to the OStatus protocol. I would like to add some stuff to the OStatus protocol so that users always get the whole thread. I guess this is possible with a little effort.

**Comment by Gargron** [comment]
@annando Look up Atom Threads spec. Besides thr:in-reply-to, there is thr:replies: https://tools.ietf.org/html/rfc4685#section-4

**Comment by annando** [comment]
```thr:replies``` looks nice - but can only work when the status was fetched again after some time. It doesn't work on delivery. Here some link to a feed with the whole known conversation would be fine.

**Comment by annando** [comment]
I just read these lines:

> A "replies" link appearing as a child of the Atom feed or source
   element indicates that the referenced resource likely contains
   responses to any of that feed's entries.  A "replies" link appearing
   as a child of an Atom entry element indicates that the linked
   resource likely contains responses specific to that entry.

I do understand this _"any"_ as: The ```thr:replies``` should not only contain direct answers to this specific entry but also answers to answers of that entry and so on?

@Gargron Do you think that we could extend that _"likely"_ in a way that we could point it to a feed that contains **all** known entries in that thread and not only the children of that entry?

**Comment by tobiasd** [comment]
Can this be closed?

**Comment by annando** [comment]
Best would be if @Gargron could confirm this.

**Comment by annando** [comment]
I will now close it, I guess that @Gargron is satisfied with this solution.
