### ISSUE TITLE
[frio] reshared posts and additional text

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2865]
If I reshare a post and I write some additional text _beneath_ the reshared content this text is displayed as part of the original post.

**Comment by Hypolite** [comment]
Can you create a public post to show the result please?

**Comment by tobiasd** [comment]
This is a common problem with "too wide" browsers with "too short" content in the attachment textual data.

**Comment by AlfredSK** [comment]
Example: https://libranet.de/display/0b6b25a8525807006b8d88a980614338

The mention of "Music & Vinyl" shouldn't be part of the reshared content.

**Comment by AlfredSK** [comment]
Some pictures...

![bild1](https://cloud.githubusercontent.com/assets/3656054/19571157/5418f6b6-96fd-11e6-9b92-07d01f654bf6.jpg)
reshare something with additional text (TEST)

![bild2](https://cloud.githubusercontent.com/assets/3656054/19571182/6d0bad08-96fd-11e6-84ea-6a94d2dce019.jpg)
Preview of posting with text (TEST) inside the reshared content

**Comment by Hypolite** [comment]
Perfect, I'll take a look at it tonight EST.

**Comment by Hypolite** [comment]
Turns out this issue wasn't specific to the frio theme.

**Comment by AlfredSK** [comment]
@Hypolite Yes. I know. :) I'm pulling the new code right now...

**Comment by AlfredSK** [comment]
Looks like it is working now...
https://libranet.de/display/0b6b25a818580a6e13a6630241017686
Do you think I can close the issue?

**Comment by Hypolite** [comment]
That's what usually happens when it's fixed. You can always reopen it later if you found a related issue.
