### ISSUE TITLE
Push participations + retractions to the relay system 

### ISSUE THREAD

**Issue by jaywink** [friendica/friendica#2872]
Friendica AFAIK supports pushing posts out to [the relay system](https://github.com/jaywink/social-relay/blob/master/docs/relays.md).

In addition to posts, participations (likes, comments) and retractions will be delivered by the relays to the same destination where the originating post was delivered to. This allows nodes which are fully disconnected from each other by social interaction to receive not only the posts but also the participations.

Friendica should, if relay outbound setting is enabled, send also participations (comments, likes) and retractions (for posts) to the relay in the settings. See [relay document](https://github.com/jaywink/social-relay/blob/master/docs/relays.md#participations-comments-likes-and-participations).

Basically TLDR, just like for the post, a simple CC of the payload to the (preferably same) relay.

Please let me know if you have questions about this and sorry for the noise if this is already implemented.

**Comment by annando** [comment]
The needed change would be simply done - just be changing 4 lines of code. I will do it when our expiration system is reworked. Currently the relay messages are stored forever. To avoid problems for smaller servers we will expire these messages after a period of time.

**Comment by AlfredSK** [comment]
> I will do it when our expiration system is reworked.

Any news here? I am thinking about configuring my server to push posts to the relay system (receiving is enabled already).

**Comment by annando** [comment]
The work at the expiration part is now completed.

**Comment by jaywink** [comment]
As pointed out [in discourse](https://discourse.diasporafoundation.org/t/public-post-federation/264/123), diaspora has no intention to send interactions to the relay. Instead, all received posts will be auto-subscribed to, which will cause source nodes to deliver interactions themselves.

Closing.
