### ISSUE TITLE
Avoid constants as they are painfully slow

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#2876]
Constants in PHP are slow in initialization and consume more memory than e.g. array elements. You should avoid them everywhere you can as they really don't give any improvements. If you still want fixed values (not be able to change), put them in a class' private array and make them available only through getter.

Or simply use a plain old array and don't change there anything (e.g. prefix it with __ to mark it as read-only for you).

**Comment by Hypolite** [comment]
Thanks for the suggestion, are you able to quantify the performance gain of replacing all Friendica-specific constants by an array of values?

**Comment by annando** [comment]
If you activate the addon "rendertime" you can see which parts of the system uses how much time. It is mostly the database, the filesystem and the network. The other parts aren't using that much time.

**Comment by Hypolite** [comment]
For a typical Friendica page, WinCacheGrind reveals 206 calls to `define()` for a total of 0,3ms used (0,02% of total time). I don't think this warrants too much optimization efforts. I don't know about memory usage and I usually overlook it as improving the page speed diminishes the time during which memory is used anyway. This would be more meaningful for a daemon process running continually.

**Comment by Quix0r** [comment]
Okay, still it should be considered on e.g. "daemonized" scripts (that continously run in the background).

**Comment by Hypolite** [comment]
Granted, but I don't think Friendica has any of those.
