### ISSUE TITLE
Suppress Language setting by default

### ISSUE THREAD

**Issue by lewissam** [friendica/friendica#2881]
Admin setting: "Suppress language information in meta information about a posting."

Ought be suppressed by default, as most information rendered is meaning less for user.

Further discussions here: https://libranet.de/display/0b6b25a8425816f685813e2325909176

**Comment by tobiasd** [comment]
This is a theme thing (vier). There are addons that use the language information, which can be useful for the users and rely on that information.

**Comment by Hypolite** [comment]
Even on servers where post language is suppressed it still is available in the database, I'm guessing the addons can still acess it.

**Comment by annando** [comment]
Correct. I once added it for testing purposes. Then I forgot about it.

**Comment by tobiasd** [comment]
Just a cross link to #3005
