### ISSUE TITLE
Long lines and code blocks

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2892]
This is a reminder that we need a decision and a solution how to display long lines in code blocks. At the moment these lines are handled differently in our themes and are breaking the themes (for example frio).
Here you can find the discussion about this issue https://libranet.de/display/0b6b25a820580c7f48ea9f6071987096

**Comment by tobiasd** [comment]
current devel has now a fix for this @AlfredSK

**Comment by AlfredSK** [comment]
Great! Looks better now. :-)
