### ISSUE TITLE
Failed redirection after action

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2893]
It's been twice today that after an action (last one being removing a contact), I'm redirected to this URL:

    https://friendica.mrpetovan.com/network?mode=raw&pagename=network?f=&order=post&page=9&_=1478405237509`

Notice the double question mark. The `pagename` parameter become `network?f=` and Friendica expectedly throws a 404 error. I didn't try to look at the code for redirection yet.

**Comment by annando** [comment]
Does this still happen?

**Comment by MrPetovan** [comment]
Yep, infrequently.

**Comment by annando** [comment]
This calls for a complete rewrite of this redirection thing. But please not in this version anymore.

**Comment by MrPetovan** [comment]
Possibly related to #5896

**Comment by JonnyTischbein** [comment]
Could you please give some more details how to reproduce or where to look into ?
I'm probleming recreating the situation.

**Comment by MrPetovan** [comment]
I can't reliably reproduce this but you can track the times where we use `mode=raw` for example.

**Comment by MrPetovan** [comment]
I haven't experienced this again, closing.
