### ISSUE TITLE
Theme frio userlist is in the background 

### ISSUE THREAD

**Issue by seraphyn** [friendica/friendica#2915]
When you start with an @ in your post to get the usernames with the first letters, the will be normally a dropdown to select the username.
The dropdown is there, but in the background and it is not possible to select the names:

![friendicalistbackground](https://cloud.githubusercontent.com/assets/140527/20301485/ca6d4e40-ab23-11e6-9455-c0e760c46e4b.png)

**Comment by fabrixxm** [comment]
I can't reproduce this on last devel.
Have you tried to force-reload the page with e Ctrl + F5 to force Firefox to download the latest files?

**Comment by seraphyn** [comment]
Tried it again with Chrome and Firefox.

**Comment by annando** [comment]
it is a rich text editor issue I guess. With the plain text editor it is working fine.

**Comment by fabrixxm** [comment]
Oh, sorry, didn't noticed the rich editor..
Yes, I rembember something about popup and richtext editor...

**Comment by seraphyn** [comment]
I would use Plaintext... NP

**Comment by tobiasd** [comment]
This issue has been fixed in the current develop branch. I'll close the ticket.
