### ISSUE TITLE
Image URLs from Diaspora containing & are failing

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2925]
Over the past couple of months, I experienced empty Diaspora posts. It was image posts whose image I couldn't see on my Friendica instance. A few of them were because the Diaspora instance hosting the image was unavailable, but not all of them were self-hosted.

And then tonight I found the issue. If the embedded image URL contains a `&` (like most Facebook image URLs), then this character is escaped as `&amp;` in the body field of the item. And once it gets processed by the bbcode parser, it ends up being the wrong URL because we don't directly show the provided URLs, instead we escape it one more time.

I'm not familiar with debugging the Diaspora protocol, so I've got a few questions:
- Does anyone else have this issue?
- Is there any way to log the raw requests from Diaspora servers?
- Are we performing any escape on our end when we receive the item from Diaspora? If yes, where? If now, it seems like we should unescape what we receive from Diaspora but I'm not comfortable with the idea.

Please tell me what you think.

**Comment by annando** [comment]
We save the raw data in the object field of an item, I think.

**Comment by Hypolite** [comment]
Thanks for the info, I'll look at it tonight.

**Comment by Hypolite** [comment]
Confirmed: the offending HTML encoded ampersand is also found in the raw XML object we get from Diaspora.

*sigh*

Another hack in the works.

**Comment by tobiasd** [comment]
With the PR merged, can this be closed?

**Comment by Hypolite** [comment]
I didn't formally test it but I believe it can be closed.
