### ISSUE TITLE
Email confirmation for pending registration 

### ISSUE THREAD

**Issue by lewissam** [friendica/friendica#2926]
I'm running a small node with an "approval required" registration policy.

Feedback from my users indicates that they felt their spirits dampened by the lack of immediate email confirmation about their registration status.

I understand that the website displays a short message about a requested registration. But some users felt confused by the lack of an email and suspected a technical problem with the service they tried to sign up for.

A short email that acknowledges a pending registration might be very useful and probably will be within standard practices. A "Suppress user notification of pending approval" option might cater for those servers with higher security/ privacy requirements.

Cheers,
Sam

**Comment by lewissam** [comment]
Thanks for the swift fix!

Not sure if this was intended, but the website display "Your registration is pending approval by the site owner." seem now not working anymore.
https://github.com/friendica/friendica/commit/ea38af9799f20c237c752251e3546670f9ec0eb7

**Comment by tobiasd** [comment]
No it was not intended and in the VM I've tested it with it did not happen. But it occurred now ...  so I'll have a look at it. Thanks for the heads up!
