### ISSUE TITLE
Invalid profile URL when connecting to users on same server

### ISSUE THREAD

**Issue by gvansanden** [friendica/friendica#2956]
Hi

I've been running a Friendica server for years at https://social.taurix.net.  I recently upgraded to the latest stable version using git pull, and since that time I can no longer connect accounts on my own server, I get the error: "invalid profile URL".

The apache log shows:
[Mon Nov 21 16:32:02.448372 2016] [:error] [pid 10018] [client 192.168.122.5:41966] PHP Warning:  Invalid argument supplied for foreach() in /nfs/www/friendika/include/Probe.php on line 129, referer: https://social.taurix.net/dfrn_request/gvs

Server is running Ubuntu 14.04.

**Comment by annando** [comment]
That could be related to some problem that we fixed in the develop branch. Is it possible that you switch to the develop branch to check this?

**Comment by gvansanden** [comment]
Sure, can I switch back later?  I’d like to keep the server mostly stable :-)

Thanks

Guy

**Comment by Hypolite** [comment]
I don't think so if there are database changes on `develop`, and they are frequent. Best thing to do in this case would be to wait until the new official release to switch back to `master`.

**Comment by doweio** [comment]
@gvansanden  -  I compared the latest stable release to the dev version in Github and found only minor differences to the relevant piece of code causing the error.

This might be very bad advice, and I have no idea of the consequences, but you can replace the problematic line of code to get this functionality back.

Navigate to /include/ and edit Probe.php around line 127.  Comment out the original line and add this new one:
`		//$links = self::webfinger($webbie);`
`		$links = self::lrdd($webbie);`

One consequence is that trips-out the friend request form and makes it reload, but on second submission the system works fine and you can make connections with people who host their account locally.

Again, this may be stupid, break your installation, blow up the internet, etc... but it works for me.

**Comment by Hypolite** [comment]
@doweio Interesting, thanks for the find. We might not use the hack as is, but it's a good lead to start fixing this issue.

**Comment by gvansanden** [comment]
I actually risked it and switched to dev.  That fixed it

**Comment by Hypolite** [comment]
Oh, so next release will fix this issue. Great!

**Comment by annando** [comment]
@Hypolite if the develop branch fixes it, we can close this issue, can't we?

**Comment by Hypolite** [comment]
I'd rather let @gvansanden close it because it was his, but yeah, in essence we can close it.

**Comment by gvansanden** [comment]
Sure, closing the issue.  Thanks
