### ISSUE TITLE
Mastodon: Profile images are missing or wrong

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2957]
I just have a bunch of Twitter contact who signed up on https://mastodon.social, and I added them to my Friendica account.

The picture below sums the first issues I have with it.

![screen shot 2016-11-21 at 3 28 06 pm](https://cloud.githubusercontent.com/assets/925415/20499416/6a185a0e-afff-11e6-8d19-6aa6a84e9eb9.png)

- The profile image is absent in the feed, but it shows up OK on the hovercard (that I can't screenshot because any keypress hides it)
- The image of the Mastodon status link attachment is from a different account than the one named "hoodie"

Are those Mastodon-specific or OStatus-general issues?

**Comment by annando** [comment]
This partly fixed with https://github.com/friendica/friendica/pull/3009

**Comment by annando** [comment]
Does this still happen?

**Comment by Hypolite** [comment]
I didn't see the issue recently, although I've added very few Mastodon contacts since it was way too verbose. I'll reopen if I see this issue again. Thanks for your work!

**Comment by annando** [comment]
I haven't done anything with the avatar picture - but maybe it was solved on the mastodon side.

**Comment by Hypolite** [comment]
Unfortunately, after enabling Eugen again, I got this: https://friendica.mrpetovan.com/display/52acf9cdeb9faf4c1cfb5af7e18fda5e065ba5d0

![screen shot 2017-03-03 at 11 10 14 am](https://cloud.githubusercontent.com/assets/925415/23558530/04174992-0002-11e7-9543-5d8d91c2bf91.png)

I'm not in contact with AlexJacobson, I only got the top level post because I'm following Eugen. Bonus point for the missing avatar image.

**Comment by Hypolite** [comment]
Another example from a legitimate contact I've had for months now: https://friendica.mrpetovan.com/display/52acf9cd4e70b9522689a2b3d2f91ba6ca970175 
<img width="192" alt="screen shot 2017-03-03 at 11 19 41 am" src="https://cloud.githubusercontent.com/assets/925415/23558942/86eb78e2-0003-11e7-956d-9121fba2d1bf.png">

**Comment by annando** [comment]
Do you have the message XML for me?

**Comment by Hypolite** [comment]
Tonight 😊

**Comment by Hypolite** [comment]
I added the XML objects for both instances. The first seems straightforward, the provided avatar is relative and seems to indicate absence of user-submitted avatar picture. The second one had me dumbfounded, I never saw that kind of XML object before in the `item` table.

**Comment by annando** [comment]
I expected something like a relative path already. But for the stuff we will see :-)

**Comment by annando** [comment]
Does this still occur? My PR should have solved this.

**Comment by tobiasd** [comment]
Yes it still happens for me. When a Mastodon user I follow comments on a posting by someone I don't follow, that thread gets imported (even though I only import the threads started by my contacts) and then the user image of the thread starter can be wrong.

**Comment by tobiasd** [comment]
And it is not only a Mastodon issue, just saw it on a GNU social thread.

**Comment by Hypolite** [comment]
Yes, still happening for me too, very consistently.

**Comment by annando** [comment]
Please check via /probe/ if the avatar looks okay. Additionally have a look at the item data (especially the fields "owner-link", "owner-avatar", "author-link" and "author-avatar").

**Comment by Hypolite** [comment]
New example: 
![ostatus-wrong-avatar](https://cloud.githubusercontent.com/assets/925415/24834537/ca874098-1cb6-11e7-94d6-8b0e50846224.png)

Hovercard and comment pictures are right, but the top-level avatar is wrong. This avatar is the go-to image for wrong avatar. I looked for it in the contact table, and it's part of a row with an empty name and nick.

Probing either `copiesofcopies@mastodon.social` or `https://mastodon.social/@copiesofcopies` returns the following:
````
Array
(
    [name] => Aaron Williamson
    [nick] => copiesofcopies
    [guid] => 
    [url] => https://mastodon.social/@copiesofcopies
    [addr] => copiesofcopies@mastodon.social
    [alias] => https://mastodon.social/users/copiesofcopies
    [photo] => https://files.mastodon.social/accounts/avatars/000/006/884/original/b4ec64f7ff0bda4b.jpg?1491244160
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [batch] => 
    [notify] => https://mastodon.social/api/salmon/6884
    [poll] => https://mastodon.social/users/copiesofcopies.atom
    [request] => 
    [confirm] => 
    [poco] => 
    [priority] => 0
    [network] => stat
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA47ZU2R4XI+dBgQwItGw1S
AFty6OsuY5iC/uBLkYg7xJqJ43jAAOVNVJy857l42BP0n+O7PK7jR/6DFsPqEP28Y
aytW6ZHpb1fExZcpju6ssHd+y7zsr4F2QQ2Sx+CezgwYWNxY8pU84bIh5Xkd+l57b
dEekt1ADYYOtPOw4w+nrDwsUB0At7EdPX6ovDlvUZzEKj7yS5ZO4UIK18X7PWNPR4
mpEyvDTEOZ0YkdG9KeRJQkPCIMscw4RDLvZpTjTIgpEN7J151GN7UE/nmHvMqyxU7
TYMhhZY3cY/Usih2kibtybCWVOqm5aIBzCu24OuHZmMgY4BBaNCUaLZgZGpBQIDAQ
AB
-----END PUBLIC KEY-----

    [baseurl] => http://mastodon.social
)
````

The item's owner ID and author ID are both pointing to the above contact with no nick and name. The public item contact-id is the same, however my item (uid != 0) has the correct contact ID. Both rows have a gcontact-id pointing to an existing row with empty values.

Here's the XML Object:

````xml
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:media="http://purl.org/syndication/atommedia" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:mastodon="http://mastodon.social/schema/1.0">
  <id>tag:witches.town,2017-04-08:objectId=211789:objectType=Status</id>
  <published>2017-04-08T23:41:54Z</published>
  <updated>2017-04-08T23:41:54Z</updated>
  <title>has anyone gotten a magnet implanted in their finger and if so has it interfered with your cellphone</title>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <content type="html">&lt;p&gt;has anyone gotten a magnet implanted in their finger and if so has it interfered with your cellphone&lt;/p&gt;</content>
  <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
  <mastodon:scope>public</mastodon:scope>
  <link rel="alternate" type="text/html" href="https://witches.town/users/oceangrunge/updates/27341"/>
  <link rel="self" type="application/atom+xml" href="https://witches.town/users/oceangrunge/updates/27341.atom"/>
</entry>
````
The missing `<author>` tag could be the issue, however most author-related displays are right, like the hovercard, the author name, etc... I'm guessing we are trying to fill most blanks in a way that eludes me, and the avatar is the only missing piece However, the full view of the conversation still heavily errors out, with the whole left column missing.

**Comment by annando** [comment]
This sounds like a very different problem, not the one that was reported at first.

**Comment by Hypolite** [comment]
Agreed about the link attachment displaying the wrong avatar, however the top-level post missing avatar image is still relevant.

**Comment by annando** [comment]
Is it still happening with the last avatar changes? I cannot reproduce this at my system.

**Comment by Hypolite** [comment]
I don't have any problem with normal Mastodon accounts pictures, and the specific issue I described in my last comment proved to be a Mastodon issue: #3318
