### ISSUE TITLE
Mastodon: Unable to select account in permission tab

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2958]
I can't send a private status to any Mastodon contact (doesn't show in the permission tab of the frio JOT), on top of not being able to send them private messages. Or did I misunderstand the "Private communications are not available for this contact." notice on the local profile page?

**Comment by tobiasd** [comment]
OStatus based systems (GS, SN) do not know private communication across the nodes borders. Does Mastodon?

**Comment by Hypolite** [comment]
My use case was the following: I wanted to send an @-status to someone on Mastodon, and I didn't want it to be public on Friendica. The status would be public on Mastodon of course, but not on Friendica.

**Comment by tobiasd** [comment]
Yes, but OStatus does not know directed communication. All your statuses are pushed to all your followers. If you publish a top-level post that shall reach your OStatus followers it has to be public and as such will be on your Friendica wall and be distributed to all other contacts as well. If you reply to a public posting, then all the OStatus followers will get that reply as well.

**Comment by Hypolite** [comment]
I'm confused, I thought Friendica and the remote servers of whatever flavor had a distinct copy of the statuses?

In this case for example, I would expect that a private copy of the status to be stored on my instance, that a copy would be send through the OStatus protocol to `mastodon.social` (and would be public there), and that's it since I wouldn't have selected any other contacts in the permission list. Am I missing something?

**Comment by tobiasd** [comment]
You are missing that "privat" copy is not possible (as far as I know) on the GNU Social/StatusNet part of the world for non-local postings on the micro-blog. Mastodon might do it differently, but that would not be compatible with how GS/SN does it.

**Comment by Hypolite** [comment]
I don't want the status to be private on GNU Social/StatusNet, I just want it not to be sent to all the Federation servers I know except the one of the contact I selected in the Permissions tab. That would be private enough for me. Is it possible?

**Comment by tobiasd** [comment]
I don't think so. You do a posting, it is placed on your wall so everyone you selected in the ACL that comes over Magic-Auth will see it there. In addition everyone you selected gets it pushed to their stream. Should pushing not work, other Friendica instances you are connected with will checkout your node after Magic-Authing and pull the posting if the other end is allowed to see the posting.

Mastodon needs the posting to be public, so you need to post the posting in public so it can be distributed to Mastodon. If Mastodon would implement private communication across nodes/projects boders, then it could be implemented.

**Comment by Hypolite** [comment]
Gotcha, I didn't know about the pull feature. I guess it makes sense it's not working this way then.

**Comment by tobiasd** [comment]
Should you ever have to shutdown the node for hardware work, you wont miss a post as long as you don't need too long to restart the machine. :-)

**Comment by Hypolite** [comment]
Isn't this already taken care of by the failed message retries from the remote servers? 🤔

**Comment by tobiasd** [comment]
In part yes. But not all connected networks do this. Also you could install on a Notebook with local web server and dynamic DNS service. Say given notebook is on for an hour a day, it would be very uncertain that the resend will see the note active- But starting this notebook-node will pull recent messages and push the answers. As long as not everybody is doing so, the network as whole can still work fine.

**Comment by Hypolite** [comment]
Thanks for the explanation. The pull feature is actually one of the reasons I switched from Diaspora to Friendica since I would regularly miss the first comments from threads and be confused about who was saying what to whom.

**Comment by Hypolite** [comment]
So I guess I can close this issue since it depends on Mastodon having a private message feature.
