### ISSUE TITLE
Mastodon: Replies incorrectly show as public status

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2961]
In my stream ([link](https://friendica.mrpetovan.com/display/52acf9cd8ef57813de8d43e66e79d1b6acb661c2)):
![screen shot 2016-11-21 at 4 05 51 pm](https://cloud.githubusercontent.com/assets/925415/20500682/810e8314-b004-11e6-8a25-9504bbfc96fa.png)

Source [link](https://mastodon.social/users/LogicalDash/updates/76393):
![screen shot 2016-11-21 at 4 06 07 pm](https://cloud.githubusercontent.com/assets/925415/20500713/995828ee-b004-11e6-8e73-2886363f86b2.png)

XML object:

````xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <status feed="https://mastodon.social/users/LogicalDash.atom" xmlns="http://superfeedr.com/xmpp-pubsub-ext">
        <http code="200">Fetched (ping) 200 86400 and parsed 1/12 entries</http>
        <next_fetch>1970-01-18T03:04:07.734Z</next_fetch>
        <entries_count_since_last_maintenance>11</entries_count_since_last_maintenance>
        <velocity>0.1</velocity>
        <generated_ids>true</generated_ids>
        <period>86400</period>
        <last_fetch>1970-01-18T03:02:41.334Z</last_fetch>
        <last_parse>1970-01-18T03:02:41.334Z</last_parse>
        <last_maintenance_at>1970-01-18T03:02:39.365Z</last_maintenance_at>
    </status>
    <link rel="lrdd" href="https://mastodon.social/.well-known/webfinger?resource=acct%3ALogicalDash%40mastodon.social" />
    <link rel="alternate" href="https://mastodon.social/users/LogicalDash.atom" />
    <link title="Zack Spec" rel="alternate" href="https://mastodon.social/users/LogicalDash" type="text/html" />
    <link title="Zack Spec" rel="self" href="https://mastodon.social/users/LogicalDash.atom" type="application/atom+xml" />
    <link title="" rel="hub" href="https://pubsubhubbub.superfeedr.com" type="text/html" />
    <link title="Zack Spec" rel="salmon" href="https://mastodon.social/api/salmon/10987" />
    <title>Zack Spec</title>
    <updated>2016-11-21T20:48:52.000Z</updated>
    <id>https://mastodon.social/users/LogicalDash.atom</id>
    <entry xmlns="http://www.w3.org/2005/Atom" xmlns:geo="http://www.georss.org/georss" xmlns:as="http://activitystrea.ms/spec/1.0/" xmlns:sf="http://superfeedr.com/xmpp-pubsub-ext" xml:lang="en">
        <id>tag:mastodon.social,2016-11-21:objectId=129479:objectType=Status</id>
        <published>2016-11-21T20:48:52.000Z</published>
        <updated>2016-11-21T20:48:52.000Z</updated>
        <title>@dolljoints it's basically Usenet 2.0</title>
        <content type="html">&lt;p&gt;&lt;a href="https://mastodon.social/users/dolljoints" class="h-card u-url p-nickname mention"&gt;@&lt;span&gt;dolljoints&lt;/span&gt;&lt;/a&gt; it's basically Usenet 2.0&lt;/p&gt;</content>
        <link title="@dolljoints it's basically Usenet 2.0" rel="self" href="https://mastodon.social/users/LogicalDash/updates/76393.atom" type="application/atom+xml" />
        <link title="@dolljoints it's basically Usenet 2.0" rel="alternate" href="https://mastodon.social/users/LogicalDash/updates/76393" type="text/html" />
        <link title="@dolljoints it's basically Usenet 2.0" rel="mentioned" href="https://mastodon.social/users/dolljoints" />
        <verb xmlns="http://activitystrea.ms/spec/1.0/">http://activitystrea.ms/schema/1.0/post</verb>
    </entry>
</feed>

**Comment by Hypolite** [comment]
I'm upping the priority if I may. In my feed I'm getting a lot of Mastodon statuses that are replies to other Mastodon statuses I know nothing about from users I don't follow. 😖

**Comment by tobiasd** [comment]
Well, GNU Social and StatusNet do not know non-public postings that are transmitted to non-local nodes. I wonder how Mastodon deals with it, so that recipients on other OStatus nodes don't publish the postings in their streams.

**Comment by tobiasd** [comment]
Oh, now I see, you mean replies. m) It's the same (buggy) behavior  as with other OStatus networks. I don't think that an "important" in the subject line will give @annando more time for reworking OStatus implementation ;-)

**Comment by Hypolite** [comment]
The [Important] tag isn't there to speed up the development process, but rather to indicate, among the many Mastodon issues I opened, the one that I would like to see fixed in priority. I thought about putting the tag [Urgent], and then I thought the same thing as you told me: it wouldn't give more time to @annando.

**Comment by tobiasd** [comment]
As I understood him at the Hackathon, it would be best to rewrite the entire OStatus thing.

**Comment by Hypolite** [comment]
That sounds pretty bad, like something that's not going to be done anytime soon 😞

I wish I had enough knowledge of the protocol to do it, but I'm afraid it would take me an insane amount of time just to get up to speed with @annando on protocol.

**Comment by tobiasd** [comment]
It is on his ToDo list AFAIK but not for the 3.5.1 I assume.

**Comment by annando** [comment]
The problem here is that Mastodon reacts differently than GNU Social. We are using some GNU Social behaviour to complete the threads. Mastodon doesn't have this ability, I guess. Question is if Mastodon supports some of the neccessary API calls.

**Comment by annando** [comment]
This issue is not about the non working thread completion - so I think that with pull request https://github.com/friendica/friendica/issues/3272 this is now solved.

**Comment by Hypolite** [comment]
Not quite, I'm afraid, I just got a reply that showed up as a top-level thread with "Only import OStatus thread from known contacts"

Friendica: https://friendica.mrpetovan.com/display/52acf9cd7f36baba17b044dbe1176cc1e38d57eb
Mastodon: https://mastodon.social/users/Gargron/updates/1412849

**Comment by Hypolite** [comment]
Wait, it's not a reply, it just is a top-level post mentioning someone. I take that back.

**Comment by annando** [comment]
@Hypolite This sounds like:

> A: Is the blinker working?

> B: Yes
> B: No
> B: Yes
> B: No

**Comment by Hypolite** [comment]
To be fair it looked like a detached reply I've seen when I checked the "Only import OStatus threads from known contacts", but then I checked the remote URL and it was a top-level post even there.

**Comment by Hypolite** [comment]
To be fair it looked like a detached reply I've seen when I checked the "Only import OStatus threads from known contacts", but then I checked the remote URL and it was a top-level post even there.

**Comment by Hypolite** [comment]
it's going to sound like a running gag, but I'm reopening this Issue since the changes are a little too restrictive. In this example, a reply to a thread started by a followed contact didn't get imported, and the reply to the reply then becomes a top-level post because there's nothing to attach to it.

Original thread: https://mastodon.social/@jplebreton/1899353
Friendica display of the thread: https://friendica.mrpetovan.com/display/52acf9cd5c137748fb909742004a839c09658fde
Orphan reply: https://friendica.mrpetovan.com/display/52acf9cd038f481e957c95ea333f81ae0da6afeb

Please note this reply doesn't show up in the "Status" tab of the related contact, and the profile picture is wrong for some reason.

**Comment by annando** [comment]
Due to the whole nature how the messages are transported, this cannot totally be avoided, I guess.

**Comment by Hypolite** [comment]
What about the thread completion process, wouldn't it fetch the missing updates?

**Comment by annando** [comment]
Let's say it this way: Its complicated. Especially the problem is with threads on different servers. Each and every server could have its very own collection of posts that needn't to be identical. It is mostly working when the system is configured to fetch all threads where one of your followers is interacting. But with only fetching threads that your posters have started this makes problems.

**Comment by Hypolite** [comment]
I'm a little disappointed that OStatus support isn't better on Friendica but I understand the challenge. If anything it could push me to leave Twitter for a self-hosted GNU Social instance to be able to follow OStatus accounts more comfortably.

Closing again since no work is going to go into this issue.

**Comment by annando** [comment]
I will eventually look into the thread completion, that's for sure.

**Comment by Hypolite** [comment]
Do you need this issue to be left open? I'd rather not have my hopes too high for now.

**Comment by annando** [comment]
No. There are too many Mastodon issues open at the moment. I would like to clean up the open issues before concentrating on this one.
