### ISSUE TITLE
At sign (@) should be counted as valid URL character when autolinking

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2964]
Medium URL have the handle of the author in the URL, and this handle starts with an @ symbol. Unfortunately, Friendica doesn't expect it and cuts Medium URLs just before the offending @ symbol.

For example,

https://medium.com/@lessig/see-just-how-unequal-we-are-479634cc6a24

will become

[https://medium.com/](https://medium.com/)@lessig/see-just-how-unequal-we-are-479634cc6a24

I don't have the time to dive into the autolinking feature right now, hence this tracker issue. But I'm definitely getting to the bottom of this.

**Comment by tobiasd** [comment]
I guess this is related to #2487 so when the one gets fixed the other should be as well

**Comment by Hypolite** [comment]
Yep, it's a duplicate, closing this one.
