### ISSUE TITLE
js errors with new json ping.php

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2968]
When visiting a remote profile on a foreign server (through redir) I can see empty notify badges (while there shouldn't be any notify badges)
The js console gives the error message `main.js:219 - Uncaught TypeError: Cannot read property 'length' of null(…)`

![empty_notify_badges](https://cloud.githubusercontent.com/assets/3750381/20542732/3049e216-b103-11e6-9fed-12ac4c36dea2.jpg)

**Comment by Hypolite** [comment]
Nice catch, I didn't notice the sneaky `if (local_user())` near the top of the 300-lines functions. I am pretty mad at the one(s?) who thought having variable existence of fields in an API call was a good idea. Spoiler alert: it's not. 😡

**Comment by Hypolite** [comment]
Is it fixed?
