### ISSUE TITLE
Mastodon: Still getting network status of ignored Mastodon contact

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2971]
Because of #2961, #2963, #2962 and #2959 I decided to ignore one of my recent Mastodon contacts. I was expecting not to see anymore status updates in my network feed but here we are, I just got one right up.

Am I missing something about Ignore, should I block them altogether? Is ignoring the equivalent of Twitter's mute? I feel like it lacks an intermediary setting, like "unfollow". I don't want to end all contact, especially if they directly reach out to me, and yet I'd rather not have their public status in my network feed.

**Comment by annando** [comment]
The OStatus implementation is "special". This is one of the reasons why we should rework it.

**Comment by Hypolite** [comment]
Confirming this still happens.

**Comment by Hypolite** [comment]
Actually, statuses stop coming in after a while. I didn't check exactly how long, but it could be in the 24-hours ballpark. Is it because we tell the remote server not to send anymore statuses?

Could Friendica just ignore the new incoming statuses before the remote server stops sending them?

**Comment by Hypolite** [comment]
Confirming this is still happening. Yesterday I ignored @Gargron because of the sheer number of likes and replies that get imported in my timeline (see #2364 and #3011), and this morning I'm still getting fresh content from him.

**Comment by Gargron** [comment]
Sorry but why did you have to call me here? My feed activity is not unusual. Friendica probably shouldn't pull in things I favourite though, since normally those aren't displayed as part of the user stream.

**Comment by Hypolite** [comment]
Sorry I didn't mean to summon you, it has nothing to do with Mastodon (although isn't Mastodon pushing updates to remote contacts?). I simply wrote in your Mastodon handle and you just happen to have the same Github handle. It didn't even auto-complete it during edition or I would have been alerted.

**Comment by annando** [comment]
I think this is a duplicate to the things that were discussed in issue https://github.com/friendica/friendica/issues/2364 - I think we should close that.

**Comment by Hypolite** [comment]
It's actually invalid, while the ignore action isn't immediate, it is indeed taken into account after a few hours. Closing.

**Comment by MrPetovan** [comment]
Reopening as I got a status from an ignored public account shared by an account I follow in my stream.

**Comment by MrPetovan** [comment]
False alarm, I didn't actually ignore them but I had no way to check on mobile.
