### ISSUE TITLE
embedded videos are cut off

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2987]
When I open an embedded video it doesn't show the whole video width. Look at the picture (it should be 16:9).
![video_cut_off](https://cloud.githubusercontent.com/assets/3750381/20841290/92358982-b8b3-11e6-8e26-f6c208f5ce2e.jpg)

Friendica: Version 3.5.1-dev

**Comment by Hypolite** [comment]
Can you provide a public URL. It seems to be an OEmbed issue, not a native Friendica embed one, but I'd need to see the original post to be sure about that. However this should not prevent us from fixing it, just to know where to look for.

**Comment by rabuzarus** [comment]
https://15o2.de/display/a084910610583f1b7a2a34f684554899

But you can reproduce it with every youtube link

**Comment by fabrixxm** [comment]
I can't reproduce it on FFX 50 on OSX:

<img width="680" alt="schermata 2016-12-02 alle 17 53 00" src="https://cloud.githubusercontent.com/assets/309361/20842556/32e82db8-b8b8-11e6-83cb-7c0a23701e75.png">

**Comment by Hypolite** [comment]
Can't reproduce on Chrome 54 on Mac OS X Yosemite (10.10)

![screen shot 2016-12-02 at 11 53 22 am](https://cloud.githubusercontent.com/assets/925415/20842597/0ec2ce98-b886-11e6-83d6-1aa33ac324d3.png)

**Comment by Hypolite** [comment]
Can't reproduce either on Safari 9.0 on Mac OS X Yosemite (10.10)

![screen shot 2016-12-02 at 11 55 30 am](https://cloud.githubusercontent.com/assets/925415/20842690/55ba40e2-b886-11e6-8ef6-a877e590f70b.png)

**Comment by rabuzarus** [comment]
Ok I tested it on the foreign remote server. There everything is fine. But not in my own network stream

**Comment by Hypolite** [comment]
Can you paste your local post URL so that we can test again?

**Comment by rabuzarus** [comment]
https://friendica.kommune4.de/display/a084910610583f1b7a2a34f684554899

**Comment by rabuzarus** [comment]
html from remote
```
<a class="embed_video" href="https://www.youtube.com/watch?v=A6kjnrUff9o&amp;feature=youtu.be&amp;t=3m12s" onclick="this.innerHTML=Base64.decode(&quot;PGlmcmFtZSAgY2xhc3M9ImVtYmVkX3JpY2giIGhlaWdodD0iMzE5IiB3aWR0aD0iNDY1IiBzcmM9Imh0dHBzOi8vMTVvMi5kZS9vZW1iZWQvYUhSMGNITTZMeTkzZDNjdWVXOTFkSFZpWlM1amIyMHZkMkYwWTJnX2RqMUJObXRxYm5KVlptWTVieVptWldGMGRYSmxQWGx2ZFhSMUxtSmxKblE5TTIweE1uTT0iIGZyYW1lYm9yZGVyPSJubyI+RWluZ2ViZXR0ZXRlciBJbmhhbHQ8L2lmcmFtZT4=&quot;); return false;">	<img width="160" height="120" src="https://i.ytimg.com/vi/A6kjnrUff9o/hqdefault.jpg"><div style="width: 160px; height: 120px;"></div></a>`

base64decode gives ```<iframe  class="embed_rich" height="319" width="465" src="https://15o2.de/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1BNmtqbnJVZmY5byZmZWF0dXJlPXlvdXR1LmJlJnQ9M20xMnM=" frameborder="no">Eingebetteter Inhalt</iframe>```

on my side base64decode gives ```<iframe onload="resizeIframe(this);" class="embed_rich" height="239" width="100%" src="https://friendica.kommune4.de/oembed/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1BNmtqbnJVZmY5byZmZWF0dXJlPXlvdXR1LmJlJnQ9M20xMnM=" scrolling="no" frameborder="no">Eingebetteter Inhalt</iframe>```

This is because the foreign remote server doesn't have the latest dev code (https://github.com/friendica/friendica/blob/develop/include/oembed.php#L261)

**Comment by tobiasd** [comment]
For me (Chromium/Linux) it's the same within the stream the video has the wrong size. The origin of the video is from a GNU Social contact.

![bildschirmfoto vom 2016-12-02 18 48 55](https://cloud.githubusercontent.com/assets/433490/20844490/52d38c32-b8c0-11e6-8ebd-18730d44f4de.png)

**Comment by rabuzarus** [comment]
OK, here is something to test or to discuss.

```
$("body").on('focus', '.oembed.video > a.embed_video',  function() {
        $(this).css('float', 'none');
});
```
This event listener reacts when a link with the class `embed_video` gets the focus (I really would like to use `click` instead of `focus` but this doesn't work :-(  ) and the css `float: none;` is set to `a.embed_video`.

There some things which I don't like:
- it doesn't work correct in every case (I had 1 of 7 cases where the iframe did appear after a second click)
- reacting on `click` event would be better
- it is js (a native css solution would be better)

Better solutions are welcome

**Comment by tobiasd** [comment]
This seems not to be solved for quattro, in other themes it seems to be working :+1:
