### ISSUE TITLE
platform determination needs to be checked

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#2999]
The platform/version determination process for the gserver table needs to be checked.

**Comment by annando** [comment]
Please add some servers that are currently failing to be detected correctly.

**Comment by zotlabs** [comment]
Hubzilla detection is going to get a bit harder as it is so configurable. The Twitter API was recently move to plugin - along with federation in general (such as the Diaspora protocol plugin) and sites can even re-brand their software. I noticed in the logs Friendica trying to hit 4 or 5 different Twitter API paths which aren't going to resolve if that plugin isn't installed. Possibly your best chance at detection of a modern hubzilla server is siteinfo.json or just accept the zot line from webfinger. Sites can also hide the version so at some point trying to scrape it could just end up eating resources and not really obtain anything useful.

**Comment by tobiasd** [comment]
additionally mastodon.social; and false detection of platforms should be avoided

**Comment by annando** [comment]
The "blablanet" fork currently seems to have a problem. When you - for example - visit the page https://blablanet.co.il/.well-known/host-meta you get an "aa" as the first characters. This "aa" seems to be in the output of every page. This - of course - breaks some routines.

@zotlabs is there any reliable check for Hubzilla when you only have the base url of a server?

**Comment by tobiasd** [comment]
The issue with the "aa" in blablanet output was addressed on blablanet/blablanet#2

**Comment by annando** [comment]
By now it doesn't seem as if this change had arrived at the servers.

**Comment by annando** [comment]
I did some more work for the server type detection in that branch: https://github.com/annando/friendica/tree/1702-detect-server

I will do a pull request for the 3.5.2

**Comment by annando** [comment]
This was solved in pull request https://github.com/friendica/friendica/pull/3228
