### ISSUE TITLE
Get rid of legacy stuff

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3005]
For the release in the next year I would like to get rid of some old legacy stuff in the system to clean up the code and to make things easier.

This is:

* [x] Remove old style pager
* [x] Threading in comments always activated https://github.com/friendica/friendica/pull/3978
* [x] Remove displaying of language data
* [x] Replace background processing with the worker
* [x] Reduce the search functionality to the global search

**Comment by rabuzarus** [comment]
From my point of view we should think also about removing the "personal notes" module.
In the present implementation it isn't very useful and I assume it isn't used by the people (but we should do maybe a survey about this)

**Comment by rabuzarus** [comment]
one point about `Threading in comments always activated`

From the view of theme developer:
It would be useful if we would have some kind of hardcoded max thread level (and the possibility to overwrite this by the theme - if more thread levels are really needed). The max thread level shouldn't be that high (because of the limited space it is very hard to display thread level 8 in a nice looking way)

**Comment by AlfredSK** [comment]
> Threading in comments always activated

Hmm. Personally, I don't like this idea. I've disabled the threading of comments on my server and I really like it that way. I prefer to have the comments sorted by date. I think it looks better, especially on mobile devices.

**Comment by annando** [comment]
With disabled threading, OStatus won't work correctly.

**Comment by Quix0r** [comment]
Maybe #3010 is related to this issue, too? I have rewritten some static calls that inside the method is being converted into a non-static call to object-related calls and i used `get_app()` (which encapsulates fetching App instance.

**Comment by annando** [comment]
Since there were no objections against it, one of my first pull requests to the 3.5.2 will be the removal of the old background processing: https://github.com/annando/friendica/tree/1702-only-worker

I guess that it will be followed by the removal of the old pager since this is really a performance drain.

And after this the "old style share" will be removed, since this is a barrier for native reshares which we should implement in the future as well.

If there aren't any objections against it, I will proceed this way.

**Comment by Quix0r** [comment]
Just a quick idea: @annando I would expand your list with checkboxes like [ ] and link to tickets to use this ticket as a meta ticket. Only a suggestion. :-)

**Comment by annando** [comment]
Does anyone disagree against reducing the search functionality to the global search?

My next work will be the creation of new classes for the item handling and the frontend stuff.

**Comment by Quix0r** [comment]
What does it in practice mean? What disadvantage does the current search have? What disadvantages or advantages do we have of the reduction?

**Comment by annando** [comment]
I find the current situation confusing where you have two different search fields and one of them is searching through all posts that are visible to the current user and the other one is searching through all posts that are visible to the user in the network stream. (And the user doesn't know about the difference)

This search makes the network.php more complicated and it is a problem for the speed improvements in the database and the whole rewrite of the item handling.

**Comment by Quix0r** [comment]
Okay, thank you for explaining it.

**Comment by MrPetovan** [comment]
Wow, congrats on completing this to-do list! What about the search though, I didn't see a corresponding PR.

**Comment by annando** [comment]
There was one :)

**Comment by MrPetovan** [comment]
Good!

**Comment by hoergen** [comment]
Nooo don't remove "personal notes" I use it a a lot.
There should be additional functionality, so that you can use it as real good notebook.I will open a feture request for that.

**Comment by rabuzarus** [comment]
but we have a whole module just for setting the perms to "show it just me". I think we can solve such things in an more effektive way

**Comment by hoergen** [comment]
If I will still have that functionality and look&feel I'm ok with it. (personalNotes)
I thought about extend it, to use categories that should be displayed on the left side. It's a great tool.
