### ISSUE TITLE
Mastodon: Getting statuses mentioning one of my contact from unknown contacts

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3011]
In my network tab, I'm seeing Mastodon statuses from people I don't have in my contacts. They happen to mention a user that is in my contacts however. Is it expected?

In my network stream:
![screen shot 2016-12-14 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/925415/21201413/dd697706-c218-11e6-8736-e190dce8b9d5.png)

[Link to original post on Mastodon](https://mastodon.social/users/CrillFactor/updates/463416)

**Comment by tobiasd** [comment]
Seems like Mastodon makes some action out of it. Like when your contact likes a posting.

**Comment by annando** [comment]
I'm not so sure. I guess I have to create a Mastodon account to test the whole stuff - but not in this release.

**Comment by Quix0r** [comment]
I would prefer to see liked posts of my contacts (e.g. my contact X likes a post from contact Y, but Y is not on my contact list, still I would like to see what X is liking). If some people don't want this and some wants, then better add an user-specific option.

**Comment by Hypolite** [comment]
@Quix0r I understand your point, but it's never explicit in Friendica that a specific post by someone you're not in contact with shows up in your stream because one of your contact liked it. Sure, your contact will be listed in the "X people like this" box, but it's not immediately clear why you're getting something from a stranger in your feed.

Also, for me it's a matter of consistency. Friendica posts that my contacts like don't show up in my stream, so I don't expect Diaspora or OStatus posts to show up in my stream just because one of my contacts liked it.

Also, there already is a feature to receive posts from strangers based on actions from your contacts via the share/retweet/boost feature. I don't think the like feature should yield the same result, especially since most network don't show liked posts in streams either. Twitter started to do it, but it's not all the likes, just a few here and there, and it's explicit you're seeing the post in your feed because one of your contacts liked it.

Lastly, it's easier to like something than to write something, so a full "liked" feed is way more verbose than a post one. This is an issue for me because I like being "up to date" with my stream.

**Comment by annando** [comment]
Is this still an issue?

**Comment by annando** [comment]
I guess that this was covered by issue https://github.com/friendica/friendica/issues/2364

**Comment by Hypolite** [comment]
I've not seen this behavior for a while, closing now.
