### ISSUE TITLE
Mastodon: Discrepancies between contact status tab and my network stream

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3013]
Comparing https://friendica.mrpetovan.com/contacts/2577/posts with https://mastodon.social/users/jplebreton I noticed some status where missing from the contact status tab that showed in my network stream.

Example of missing statuses:
- https://friendica.mrpetovan.com/display/52acf9cdafef3bd4bb2388700a0d7b9f0beae10d
- https://friendica.mrpetovan.com/display/52acf9cdd41fca45c4fda2c51c97b02b23b8ffb9
- https://friendica.mrpetovan.com/display/52acf9cdfce47a31e37fb668ae3557c7a70ec9ea

However, this is happening before I enabled #3009 on my server.

**Comment by annando** [comment]
I guess we now should have a very good OStatus implementation. Please check now.

**Comment by MrPetovan** [comment]
Ha ha, it's not a good day to check, mastodon.social is down, I'll try again later.

**Comment by AlfredSK** [comment]
Yes. The problem seems to be...
> mastodon.social uses an invalid security certificate. The certificate is only valid for cmdr.social Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by MrPetovan** [comment]
Nothing wrong on my side with a new recent follow.
