### ISSUE TITLE
Diaspora: Proxyfied images don't play well with Camo

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3017]
[Camo](https://github.com/atmos/camo) is the image proxy Diaspora chose to circumvent mixed-content warning on HTTPS pods with remote HTTP images. However, it requires that the original URL to be proxyfied correctly set the Content-Type header.

Friendica's `proxy` mod is basically doing the same, except it doesn't keep the Content-Type after the original URL is proxyfied, which leads Camo to refuse to serve it.

Friendica's `proxy` should keep the original Content-Type when serving the requested URL.

Reference thread: https://friendica.mrpetovan.com/display/748ab390a558013435ef52540061b601

**Comment by annando** [comment]
We can't keep the content-type. We are storing the cached files directly in the proxy folder so that they can be served directly from the web server (to increase the performance).

**Comment by Hypolite** [comment]
Original post XML:
````xml
<XML>
  <post>
    <status_message>
      <diaspora_handle>nebukadnezar@sechat.org</diaspora_handle>
      <guid>be7d70b0a846013426c10242ac110005</guid>
      <created_at>2016-12-19 18:27:38 UTC</created_at>
      <provider_display_name/>
      <raw_message>Da mir der [herzmeister der welten](/people/869bd9c582925ae2)  hochofizellestestest das St&#xF6;ckchen f&#xFC;rs #diaphoto &#xFC;berreicht hat, hab ich mir   &#xD;
einen Begriff &#xFC;berlegt, der gro&#xDF;- oder kleingeschrieben, der Phantasie jede Menge Raum bietet:&#xD;
### #spinnen&#xD;
F&#xFC;r die Nichtspinner eine [Begriffserkl&#xE4;rung](https://de.wikipedia.org/wiki/Spinnen_%28Begriffskl%C3%A4rung%29)&#xD;
&#xD;
[Spielregeln](/posts/67c5ae7092b1013311884860008dbc6c)&#xD;
[The rules](/posts/804e57e0395b0134b3da782bcb452bd5)&#xD;
[Liste der bisherigen Themen](https://gist.github.com/Faldrian/befaeacef9919d708568503c2ba68e92)&#xD;
#diaphoto #diaphoto1651 #Spiel, #Thema, #St&#xF6;ckchen #Staffelstab #photo, #foto #fotografie #photography</raw_message>
      <public>true</public>
    </status_message>
  </post>
</XML>
````

Notice how we already manage the `/display/*` post. Is there any way in Friendica to look for a contact by guid so that those links can be localized?

Failing that, I propose we prepend the poster's domain name to the `/people/*` links so that they won't fail the protocol check.

**Comment by Hypolite** [comment]
I found the specific issue for this case: the image URL had a dot after a question mark, which fooled the extension extraction.

**Comment by Hypolite** [comment]
I will close this issue when I'll post my next Instagram picture and verify that it's displaying correctly on a remote Diaspora pod.

**Comment by Hypolite** [comment]
This is verified as fixed.
