### ISSUE TITLE
OStatus: Getting statuses my contacts are replying to

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3018]
[Closed as duplicate of #2364]

In my network stream I'm getting Mastodon statuses from people I'm not connected with just because someone I'm in contact with replied:
![screen shot 2016-12-16 at 4 31 34 pm](https://cloud.githubusercontent.com/assets/925415/21279230/412f9352-c3ad-11e6-839f-caa2570df36d.png)
In this example, I'm not in contact with goldie_ice, but I'm in contact with Gargron.

![screen shot 2016-12-16 at 4 41 05 pm](https://cloud.githubusercontent.com/assets/925415/21279500/7b21c368-c3ae-11e6-97d4-13cce25be935.png)
This is a combo with #2959. The original status is by Gargron, I'm not in contact with the retweeter but Gagron happened to like it, so it lands in my stream.

**Comment by tobiasd** [comment]
It is the current behavior also with GNU Social

**Comment by tobiasd** [comment]
see #2364

**Comment by Hypolite** [comment]
Should I close this as duplicate?

**Comment by annando** [comment]
I think so.

**Comment by Hypolite** [comment]
Reopening because it apparently wasn't a full duplicate of #2364 and it still happens for me.

**Comment by annando** [comment]
So now we only have to rename it, since it is an OStatus thing ;-)

**Comment by Hypolite** [comment]
With the explosion of Mastodon subscription after the latest Twitter changes, this issue is becoming more pressing, I'm getting way more content from OStatus than I would like since mos are replies to other stuff I didn't subscribe to.

**Comment by annando** [comment]
I think that this is now solved with the rewritten OStatus part (when the corresponding option is set)

**Comment by tobiasd** [comment]
looks good for me now

**Comment by annando** [comment]
Okay. So I'm closing it now.
