### ISSUE TITLE
Mastodon: Media posts don't seem to work with OEmbed

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3019]
Mastodon media posts are picked up by the OEmbed parser in Friendica but it just shows the non-interactive URL of the original media post.

Example: https://friendica.mrpetovan.com/display/52acf9cde51b84b00c8af4321821efdf0cb1bc27

It probably is an issue with Mastodon though.

**Comment by annando** [comment]
The OEmbed stuff is done in the bbcode parser. I don't think that this is a Mastodon problem.

**Comment by Hypolite** [comment]
Actually it was, OEmbed URLs existed for Mastodon media posts, but they just displayed the raw text of the status. I opened [an issue on Mastodon's GitHub](https://github.com/Gargron/mastodon/issues/361) and it was fixed today.

**Comment by annando** [comment]
Ahh, now I understand. I misunderstood the problem. So I guess you can close this issue?

**Comment by Hypolite** [comment]
As soon as I will have verified it is a Mastodon-only issue, yes.

**Comment by Gargron** [comment]
It seems like the actual problem is that the OEmbed stuff in the bbcode parser oembeds the media links in the body of Mastodon statuses in the first place. Those links do a 301 redirect to the original status (they're essentially placeholders), so perhaps the OEmbed discovery code shouldn't follow redirects?

**Comment by Hypolite** [comment]
I appreciate the suggestion, but we simply can't turn off redirection follow for all links, even just Mastodon. What about HTTP to HTTPS redirection? We need to follow those.

**Comment by Gargron** [comment]
That's true. I'm not sure how to handle this. I feel like keeping the placeholder links is worth it, for e.g. statuses that have no text content otherwise, or for clients that don't display attachments and thus need to signalize that an attachment is there. Perhaps you're right and the href on those links should just go straight to the attached file.

**Comment by Hypolite** [comment]
I have no grand idea about it, it just what is happening on Twitter for example.

**Comment by Gargron** [comment]
When I checked right now I couldn't find the placeholder links on Twitter anymore, I think they started stripping them out on the client side now. But yeah previously it used to redirect you to `status_url/media/some_media_id` and that page had a modal window pre-opened with the image. Mastodon doesn't have modals on public non-JS pages so it's not quite the same, but I suppose linking to original file directly will do.

**Comment by Hypolite** [comment]
I'm thinking about the `pic.twitter.com/*` links you can see in the notifications for example. Twitter clients usually strip them when displaying the attached image:

![screen shot 2016-12-19 at 11 29 46 am](https://cloud.githubusercontent.com/assets/925415/21320320/933a67ca-c5de-11e6-858a-e5c45c56e300.png)

**Comment by Gargron** [comment]
Yes that's exactly the links I was talking about/trying to emulate.

**Comment by Hypolite** [comment]
Ha, never mind, you're right, they indeed redirect to the picture modal, but there's only one link even for multiple images. Now I'm curious how Friendica handles Twitter media posts, but the connector seems broken at the moment. 😅

**Comment by Hypolite** [comment]
Closing as this is a Mastodon issue/feature.
