### ISSUE TITLE
"Join URL" http://dir.friendi.ca/siteinfo

### ISSUE THREAD

**Issue by lewissam** [friendica/friendica#3020]
https://libranet.de/dfrn_request/saml

A dfrn_request for hidden user profiles leads to a Friend/Connection Request page containing the following URL: http://dir.friendi.ca/siteinfo ["follow this link to find a public Friendica site and join us today"]

This directory http://dir.friendi.ca/siteinfo does NOT list anything.

A more suitable alternative would be this new Friendica directory: http://dir-fc.oscp.info/health or possibly even the federation directory itself: https://the-federation.info/

**Comment by Beanow** [comment]
Perhaps http://dir-fc.oscp.info/servers is more the style of listing you mean?
It's the same data as http://dir-fc.oscp.info/health but aimed at users wanting to sign up.

Source in https://github.com/Beanow/dir/tree/feature/redesign-prototype
Improved later by https://github.com/tugelbend/dir/tree/feature/redesign-prototype

(Related to #2311)

**Comment by lewissam** [comment]
Thanks very much! Yes, this URL http://dir-fc.oscp.info/servers  would be ideal.

Can this URL easily be replaced on in the code? Or is it generated by being linked to the external directory at http://dir.friendi.ca?

**Comment by Beanow** [comment]
@lewissam as per #3053 that directory will be shut down soon. The code for these pages are available and being picked up though.

As for setting the URL, I assume it's based on the directory url configuration. @annando perhaps can tell.

**Comment by annando** [comment]
Yeah, there is a setting for that. But I really would like to have dir.friendi.ca as a working solution as well.

**Comment by lewissam** [comment]
Thanks @Beanow and @annando , I found the setting.

Replacing the directory url in the admin panel still leaves a problem: 

- The current link is generated with dir.example/**siteinfo** and not dir.example/**server**

The Friendica code adds _siteinfo_ but Beanow's directory code gives out the info on .../server

**Comment by MrPetovan** [comment]
Now that @Beanow's improved directory code has been merged in the main friendica dir repository, this can reliably be changed to `servers`.
