### ISSUE TITLE
Twitter: Not getting any statuses from any contact

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3028]
I'm connected with multiple Twitter accounts I otherwise follow on Twitter itself, and I'm not getting any updates from them. The status tab of the contact pages shows nothing at all:

![screen shot 2016-12-19 at 11 35 48 am](https://cloud.githubusercontent.com/assets/925415/21320550/755a8f04-c5df-11e6-8ff4-d8d6242a85ac.png)

**Comment by tobiasd** [comment]
I know it would help you - but for my T-contacts it works fine. Just to have another datapoint here.

**Comment by Hypolite** [comment]
I'm going to try remove contact and re-adding them.

**Comment by Hypolite** [comment]
When connecting with a Twitter contact, I'm getting the following error:
`replace_macros: Unable to load template file 'view/templates/follow_slap.tpl'`

I believe the file has been removed recently.

**Comment by annando** [comment]
Have you setup your twitter connector so that it only shows posts of contacts that are already added and you add them by hand?

**Comment by Hypolite** [comment]
I followed the plugin install instructions, registering a Twitter application and submitting the client ID and secret to Friendica. Is there anything else I need to do?

**Comment by annando** [comment]
And you have connected your Friendica account with your Twitter account? How are the settings there?

**Comment by Hypolite** [comment]
Yes I did, and it works perfectly. All my public posts are relayed on my Friendica'profile.

**Comment by annando** [comment]
I'm a little bit confused. Are any posts from Twitter imported or not?

**Comment by Hypolite** [comment]
I'm getting Twitter posts from my personal account, but nome from Twitter accounts I connected with.

**Comment by annando** [comment]
Which options have you activated in the user settings for the twitter connector?

**Comment by Hypolite** [comment]
In Social Networks (/settings/connectors):
Currently connected to: [MrPetovan](https://twitter.com/MrPetovan)
✔️ Allow posting to Twitter
✖️ Send public postings to Twitter by default
✔️ Mirror all posts from twitter that are no replies
✖️ Import the remote timeline
✔️ Automatically create contacts
✖️ Clear OAuth configuration

**Comment by annando** [comment]
When you activate "Import the remote timeline" it will work.

**Comment by Hypolite** [comment]
*gif of a person opening a closet, all the content is falling on him*

Alright, it definitely works, but not the way I expected interacting with a Twitter contact. The setting you made me change retrieves all the tweets that show up in the timeline of my Twitter account I'm connected with, as well as the mentions.

However, I just wanted the tweets from specific Twitter accounts I'm having as contacts on Friendica to show up in my stream. Basically, that Twitter contacts worked like OStatus contacts. I know it's not the same protocol at all and that the Twitter connector has to poll Twitter for new content instead of passively receiving it, but we evidently already are doing it for the remote timeline import.

Is it clearer?

**Comment by annando** [comment]
Disable "Automatically create contacts" and remove all Twitter contacts that you don't want to follow here - or ignore them.

**Comment by Hypolite** [comment]
Ok, I see where you're getting at, does this means you can receive statuses from Twitter contacts if you don't have a Twitter account following them yourself?

**Comment by annando** [comment]
No, you can only follow Twitter contacts that you follow with your Twitter account.

**Comment by Hypolite** [comment]
Ok, thanks for the clarification, closing this as it isn't a bug as I thought.
