### ISSUE TITLE
Diaspora: /people/* links are stripped of their hostname

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3029]
I recently received [a Diaspora* post](https://friendica.mrpetovan.com/display/28e46630a8540134360352540061b601) mentioning a user account on the remote pod through a `/people/*` link (exact URL: https://nerdpol.ch/people/869bd9c582925ae2).

Problem is that this remote link gets stripped of the remote domain name and ends up showing as `people/869bd9c582925ae2` in the post, which gets flagged as bad by the protocol whitelist., but still gets picked up by the OEmbed process that tries to access `http://people/869bd9c582925ae2`.

It seems to me the remote server hostname shouldn't be stripped in the first place, but I'm probably forgetting about a use-case where we need to remove it, to show a post by guid for example.

**Comment by annando** [comment]
I can imagine that it is like with the /posts links. it is some Diaspora magic stuff. The value is the guid of the contact. And the guid is similar on each server. So this always points to the user on the watchers server.

**Comment by Hypolite** [comment]
Original post XML:
````xml
<XML>
  <post>
    <status_message>
      <diaspora_handle>nebukadnezar@sechat.org</diaspora_handle>
      <guid>be7d70b0a846013426c10242ac110005</guid>
      <created_at>2016-12-19 18:27:38 UTC</created_at>
      <provider_display_name/>
      <raw_message>Da mir der [herzmeister der welten](/people/869bd9c582925ae2)  hochofizellestestest das St&#xF6;ckchen f&#xFC;rs #diaphoto &#xFC;berreicht hat, hab ich mir   &#xD;
einen Begriff &#xFC;berlegt, der gro&#xDF;- oder kleingeschrieben, der Phantasie jede Menge Raum bietet:&#xD;
### #spinnen&#xD;
F&#xFC;r die Nichtspinner eine [Begriffserkl&#xE4;rung](https://de.wikipedia.org/wiki/Spinnen_%28Begriffskl%C3%A4rung%29)&#xD;
&#xD;
[Spielregeln](/posts/67c5ae7092b1013311884860008dbc6c)&#xD;
[The rules](/posts/804e57e0395b0134b3da782bcb452bd5)&#xD;
[Liste der bisherigen Themen](https://gist.github.com/Faldrian/befaeacef9919d708568503c2ba68e92)&#xD;
#diaphoto #diaphoto1651 #Spiel, #Thema, #St&#xF6;ckchen #Staffelstab #photo, #foto #fotografie #photography</raw_message>
      <public>true</public>
    </status_message>
  </post>
</XML>
````

Notice how we already manage the `/display/*` post. Is there any way in Friendica to look for a contact by guid so that those links can be localized?

Failing that, I propose we prepend the poster's domain name to the `/people/*` links so that they won't fail the protocol check.

**Comment by annando** [comment]
Can we close this now?

**Comment by Hypolite** [comment]
I'm waiting for an actual example of Diaspora* post with a `/people/*` link to verify it, there's no more work to be done here.

**Comment by foss-** [comment]
maybe there could be a diaspora test account for friendica devs to test such functionality?

**Comment by Hypolite** [comment]
I'm so lazy I didn't realize I could do it on my own. I'm going to test it and report the results.

**Comment by Hypolite** [comment]
It seems to work now, good job me!
