### ISSUE TITLE
Use "placeholder" in new post form textarea

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#3062]
Instead of javascripting the "share" text in empty textare we sould just use the ´placeholder´ attribute (and remove all the useless scripting).
This will improve user experience and make the textarea to have a standard behaviour.

**Comment by annando** [comment]
What is the "placeholder" attribute?

**Comment by tobiasd** [comment]
You can set placeholder text for HTML form elements (see [here](http://www.w3schools.com/tags/att_input_placeholder.asp))

**Comment by Quix0r** [comment]
Oh, I didn't know about that attribute (pure HTML again, no fancy/buggy JS).

**Comment by Hypolite** [comment]
Unfortunately this issue has to be reopened, clicking on the default comment textarea doesn't bring up the comment box, and clicking away brings the "undefined" string in the comment textarea.

![friendica_comment_box_undefined](https://cloud.githubusercontent.com/assets/925415/23020145/a04a566a-f413-11e6-92b6-863f07c0038d.png)

The "Comment" links are working as expected though.
