### ISSUE TITLE
Settings > Display > Genereal Theme settings should only show options for mobile theme if a mobile theme exists

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3066]
When there is no mobile theme option there's no need to display that option. Cluttering the settings options with options that are not even options (nothing can be selected) is not a good idea.

Thus I propose to hide that option in case there is no mobile theme that can be selected.

**Comment by rabuzarus** [comment]
Should be solved with https://github.com/friendica/friendica/issues/3068 . Please try. If it works for you this issue can be closed

**Comment by foss-** [comment]
confirmed, great work!
![bildschirmfoto 3](https://cloud.githubusercontent.com/assets/5708172/21742415/fa48168c-d4ee-11e6-85d3-05a1b780aad3.jpg)

On that instance mobile themes are not enabled. So tested vier + quattro and they as well no longer show the mobile theme option dropdown.

Everything is behaving as expected now and the UI has been de-cluttered a bit.

Thx @rabuzarus
