### ISSUE TITLE
Frio: Pressing Esc when contact autocomplete dropdown appears closes editor modal

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3084]
Situation:
I open the post editing modal, I enter a @ sign which opens the contact auto-complete dropdown, although I don't want to select any. I press Esc to dismiss the dropdown, only to see the entire modal disappear.

Expected:
The first Esc press dismisses the dropdown, the second Esc press closes the modal.

Silver lining: The modal is only hidden when closed, bringing it back up keeps the entered text, fortunately.

This is a low priority fix that can wait the next release.

**Comment by tobiasd** [comment]
As the ACL dialogue was completely rewritten, is this still an issue in Frio?

**Comment by AlfredSK** [comment]
Yes, the behavior is still the same. First ESC closes modal completely.

**Comment by MrPetovan** [comment]
It wasn’t related to the ACL, just the mention auto-complete.

**Comment by MrPetovan** [comment]
Alright, time to shine.

**Comment by MrPetovan** [comment]
Phew.
