### ISSUE TITLE
500 Error with php 7.1.1

### ISSUE THREAD

**Issue by templis** [friendica/friendica#3100]
Get this Error after upgrade to php 7.1.1:
2017/01/21 00:14:48 [error] 26170#26170: *1817 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/friendica/boot.php:985
Stack trace:
#0 /var/www/friendica/include/ForumManager.php(105): App::remove_baseurl('https://friendica....')
#1 /var/www/friendica/mod/network.php(151): ForumManager::widget(1, NULL)
#2 /var/www/friendica/index.php(320): network_init(Object(App))
#3 {main}
  thrown in /var/www/friendica/boot.php on line 985" while reading response header from upstream, client: 78.43.43.35, server: friendica.url.tld, request: "GET /network?f=&order=post& HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "friendica.url.tld"

**Comment by annando** [comment]
Are you using the develop or the master branch?

**Comment by templis** [comment]
i use the master branch
