### ISSUE TITLE
Bottom edge of the window can not be clicked when XMPP chat window is activated

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#3105]
See here
https://www.youtube.com/watch?v=1HGKc0C1p8s&feature=youtu.be

**Comment by MrPetovan** [comment]
Related to #3717, same question, should we just mark this addon as unsupported since no one has picked up either issue for more than a year?

**Comment by annando** [comment]
Possibly this is a good idea.

**Comment by MrPetovan** [comment]
The addon has been marked as unsupported.
