### ISSUE TITLE
Theme frio: Syntax error in Color.php

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#3107]
I get this on an unregular lint check:

> Errors parsing ./view/theme/frio/php/Colors.php
> PHP Fatal error:  Cannot redeclare colors::RGBToHSL() in ./view/theme/frio/php/Colors.php on line 182

**Comment by Quix0r** [comment]
Thank you for cleanup. :-)

**Comment by Hypolite** [comment]
You're welcome!
