### ISSUE TITLE
Fresh install: HTTPException already declared

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3113]
On a fresh install of the develop branch 3 weeks ago, the HTTPException was said to be already declared. I had to comment out line 8 of `include/api.php` to be able to even reach the install screen.

**Comment by tobiasd** [comment]
On Debian Jessie with PHP5.6 I did not encounter this. Would be great if we could test it on other systems.

**Comment by annando** [comment]
Sounds like an autoloader problem to me. This class is only included once in the API. It isn't included at any other place in the code.

**Comment by annando** [comment]
Like I said 10 days ago, I guess this has something to do with autoloading. @Hypolite @fabrixxm @rabuzarus are you experts in this?

**Comment by fabrixxm** [comment]
I have to find time to check it.. but afaik in master httpexceptions aren't loaded via autoload..

**Comment by annando** [comment]
@Hypolite tried the develop branch.

**Comment by fabrixxm** [comment]
yep, of course.. sorry, I wrote without boot up the brain...

**Comment by tobiasd** [comment]
Just to note this, I did not encounter this during installations on clean CentOS 7 and Ubuntu 16.04.

**Comment by Hypolite** [comment]
That's enough tests for me to close this issue as invalid. I maybe had the develop branch in a in-between state.
