### ISSUE TITLE
Fresh install: Blank MySQL password not supported

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3114]
On a fresh install of the `develop` branch 3 weeks ago, the installer refused a blank MySQL password even though MySQL supports it. Friendica should either allow blank passwords (preferred) or make very clear that we don't allow it.

**Comment by tobiasd** [comment]
Similar aspect @Quix0r, when the wrong credentials are entered there is no feedback in the installation wizard, the page just reloads.

**Comment by Quix0r** [comment]
I would prefer a warning to the user if no password is entered as this is generally insecure (easy to break in and today there are good password generators around). In the database connection step, I would also like to output a pre-warning that a password-less access is possible with MySQL/MariaDB but not recommended due to security-related concerns.

**Comment by Hypolite** [comment]
In my opinion, only root-access admins or devs are using password-less MySQL accounts. Either it's local install on *AMP, or it's on a remote machine they control. All other vendor-supplied hosting solution provide password-protected accounts by default.

Therefore, I don't think we should scold users for not having a password protected account, let alone prevent them from using one, since they know exactly why they're using such an account.

PhpMyAdmin has a warning for password-less accounts, but it's the only case I know where it does indeed matter, since PhpMyAdmin overrides the realm part of MySQL accounts (localhost in "hypolite"@"localhost") by publicly exposing local MySQL users. But Friendica doesn't do such thing, so I really don't think we should say or do anything as long as the connection establishes.

**Comment by tobiasd** [comment]
I think those people don't need the installation wizard but can install friendica manually.  The process is documented in the INSTALL file.

**Comment by Hypolite** [comment]
Of course, but if you're a #LazyAdmin like me, you both have password-less accounts for dev and use the wizard not to forget to set any critical config value.

**Comment by tobiasd** [comment]
The htconfig file should now hold all the information the template holds after a sucessful run of the wizard. Can we move this along to 3.5.2 as the wizard now has *at least a big warning that empty passwords are not allowed*.

**Comment by annando** [comment]
@Hypolite could you live with postponing it to 3.5.2?

**Comment by Hypolite** [comment]
Most definitely.

**Comment by annando** [comment]
How should we proceed here? Should we simply allow empty passwords? Should we create some warning? Should we discourage the users?

**Comment by Hypolite** [comment]
If we leave the check, we should at least add a notice.

**Comment by tobiasd** [comment]
The notice is there.

**Comment by Hypolite** [comment]
Then it's a done deal!
