### ISSUE TITLE
Fresh install: PHP Warnings on registration

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3115]
On a fresh install of the `develop` branch 3 weeks ago, clicking on the registration link at the end of the install, I get a few Warning: Illegal string offset 'url' in `include/Core/Config.php` on line 107/137 for `url`, `build` and `addon`.

I assume missing config values.

**Comment by Quix0r** [comment]
And maybe missing `isset()` calls?

**Comment by annando** [comment]
I'm bad in git stuff. Can someone provide a link to a file in the version when @Hypolite experienced the problem? We had changed much stuff in the config recently, so I want to make sure if the changes maybe have fixed the problem.

**Comment by Hypolite** [comment]
Just did a fresh install with the `3.5.1rc` branch and I didn't get the same warnings.
