### ISSUE TITLE
Fresh install: Disabled themes appear in the Admin theme setting list

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3116]
On a fresh install of the `develop` branch 3 weeks ago, the Admin -> Site -> System theme list shows all the available themes even though none has been enabled yet in the Admin -> Themes page.

**Comment by annando** [comment]
This really sounds like "allowed_themes" wasn't set.

**Comment by tobiasd** [comment]
#3140 solves this one, so I'm closing it
