### ISSUE TITLE
Fresh install: Unable to change admin settings present in .htconfig

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3117]
On a fresh install of the `develop` branch 3 weeks ago, I was unable to change any Admin setting that are in .htconfig because it fires an UPDATE query on an non-existent row in the database.

The problem lies in the way the Config wrapper checks for existence: it only checks for existence in memory, and if it exists, it assumes that there is a corresponding row in the database, however config values can be loaded from the `.htconfig` file as well.

This is a regression of #2816.

**Comment by annando** [comment]
Yeah, you are right. I will have a look at it.

**Comment by Hypolite** [comment]
I believe the issue was reintroduced when you split the `INSERT ... ON DUPLICATE KEY ...` queries I introduced to handle such cases. I agreed with your changes back then, but by then all the config values in my `.htconfig` had rows in the DB.

**Comment by annando** [comment]
Problem is that this "on duplicate key" really kills my system. So its better to try an update - and when this fails, we insert it. These are some more code lines - but a huge performance gain.

**Comment by Hypolite** [comment]
Not saying we should revert to my version (like I said, I validated the change), just pointing out what introduced the regression.

**Comment by annando** [comment]
Thanks for pointing this out because it was the origin of the problem. I guess my solution in the pull request should solve this problem once and for all - and it doesn't contain redundant code and respects the performance.

**Comment by tobiasd** [comment]
It works for me, but I'd love to see other people testing it as well ;-)

**Comment by annando** [comment]
Since @Hypolite had done a "thumbs up" I think he tested it as well? So weil can close this issue, can't we?

**Comment by Hypolite** [comment]
I trust you guys.
