### ISSUE TITLE
Fresh install: vier theme isn't enabled by default

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3118]
On a fresh install of the `develop` branch 3 weeks ago, I saw that the vier theme isn't enabled by default although it is set as the default in the `.htconfig` file. Not sure if it has any practical implication for anything but I was confused when I visited the Admin -> Themes page not to see the current theme enabled.

**Comment by annando** [comment]
Maybe this is solved by the pull request https://github.com/friendica/friendica/pull/3121 as well? If not then we forgot some additional config value. Could you check if the config value "allowed_themes" is set?

**Comment by tobiasd** [comment]
You are right, I'll add it to the template

**Comment by tobiasd** [comment]
I've tested this on a clean VM and it worked as supposed. So I'm closing this issue.
