### ISSUE TITLE
Remove duplicate database entries when creating unique indexes

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3126]
Currently we rely on the ````INSERT IGNORE```` database statement to remove duplicate entries. But this doesn't work with every MySQL flavor.

We have to find a solution for this before the release.

**Comment by annando** [comment]
It's solved with pull request https://github.com/friendica/friendica/pull/3132

**Comment by tobiasd** [comment]
So this can be closed?

**Comment by annando** [comment]
I hope so. I tested it on my system. Or does anyone wants to test it as well?

**Comment by tobiasd** [comment]
3132 is merged, everyone on dev will test it
