### ISSUE TITLE
Photo captions not placed correctly

### ISSUE THREAD

**Issue by habruening** [friendica/friendica#3130]
My photos have wrong placed texts. See screenshot.

<img width="529" alt="screenshot_20170129_161524" src="https://cloud.githubusercontent.com/assets/6696415/22405142/3619ddb6-e63e-11e6-933e-522e59c46569.png">

**Comment by habruening** [comment]
This occurs with Firefox and Chrome.

**Comment by Hypolite** [comment]
Can you add what theme are you using right now?

**Comment by annando** [comment]
I guess it is "vier".

**Comment by habruening** [comment]
Yes, it is "vier.
