### ISSUE TITLE
Cannot invite members if config['system']['directory'] empty

### ISSUE THREAD

**Issue by habruening** [friendica/friendica#3131]
When config['system']['directory'] empty, I cannot invite my friends. I get a message
"This system is not currently configured to connect with other public sites or invite members."

But I see no reason for this. Why is it not possible to invite members without using the public directory?

**Comment by annando** [comment]
This is - indeed - a good question.

**Comment by tobiasd** [comment]
At the moment the invitation mail is including a link to the directory list of public nodes.

So if the config variable is not set, the link needs to be excluded from the mail and instead only invite to the node itself.

**Comment by tobiasd** [comment]
In the develop branch you can now invite ppl to your node, if the registration is not closed. If the nodes registration is closed, the admin needs to create accounts I think.

@habruening can we close the issue?

**Comment by annando** [comment]
@tobiasd I guess we can close it now if you had tested it.
