### ISSUE TITLE
Make worker as the only way for background processing

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3134]
The worker is active since 3.5.0 and was improved in 3.5.1. Currently I don't see any condition where the old method would be better than the worker. So i think for the next version we should remove the old method. This will simplify the code and we can further optimize the background processing.

Update: Removing the old style of the background processing was addressed in the issue https://github.com/friendica/friendica/issues/3005 as well.

**Comment by Quix0r** [comment]
Well, on some hosters you don't have shell access. So they cannot execute shell scripts. I like the way Nextcloud/Owncloud is doing it:

1. By cron-job (shell)
2. By 1x1 pixel (browser-based, non-javascript)
3. By AJAX (JavaScript, each page reload)

**Comment by annando** [comment]
The worker doesn't need a shell. it can be adjusted so that it uses the so called "front end worker". Then the system is doing something similar to your second point.

The disadvantage is that front end jobs are mostly time limited since webservers are mostly running into a timeout.

I currently don't know any situation where the current method has an advantage compared to the worker.

**Comment by Quix0r** [comment]
Yes, slow running scripts may end up in TCP timeouts which sometimes (e.g. with Apache MPM worker) end up in 500 internal server errors. So on large instances, it is recommended to use shell cron-job. Okay, fine with me then, that people with no shell access can still have "cron jobs" but with a performance penality (as the website seem to load slow).

**Comment by annando** [comment]
The website wouldn't load slow. The frontend worker avoids this problem.

**Comment by annando** [comment]
This was solved in pull request https://github.com/friendica/friendica/pull/3226
