### ISSUE TITLE
Support pnut

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3145]
Pnut is so called "A short-messaging social network" - and they got an API. So we should create a connector for them.

The API is described here: https://pnut.io/docs/api

**Comment by spacenerdmo** [comment]
@33MHz just made me aware that this was an open issue. I actually got around to hacking together a connector for this.

https://codeberg.org/thrrgilag/friendica-pnut-addon

**Comment by tobiasd** [comment]
If you like, this can be included in https://git.friendi.ca/friendica/friendica-addons

**Comment by spacenerdmo** [comment]
Yes I'm open to that. Is there a particular process or workflow you need me to follow or is it just a matter of registering an account and opening a pull request against a specific branch?

**Comment by annando** [comment]
Just create an account at git.friendi.ca. And then create a pull request from your repository against our at that server.

**Comment by MrPetovan** [comment]
Closed by https://git.friendi.ca/friendica/friendica-addons/pulls/1466, thank you @thrrgilag !
