### ISSUE TITLE
MYSQL fulltext engine don't work anymore for fulltext search

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#3157]
The mysql fulltext engine search broke with the removal of the index keys `title` and `body` of the `item` table through https://github.com/friendica/friendica/pull/3096 and https://github.com/friendica/friendica/pull/3069

There some parts in the code which use it.

We should decide if we add the missing index keys to make the fulltext engine work again or if we want remove the code.

**Comment by annando** [comment]
The use of the fulltext engine has to be enabled in the admin interface. If not selected (which is the default) it isn't used.

**Comment by rabuzarus** [comment]
Yes I know. I have switched  to "don't use the fulltext engine"
This issue is more a reminder that we have non working code in friendica where we need to decide what we are doing until the release. Think of installation which have enabled this setting and don't realize that it don't work after the update to 3.5.1

**Comment by annando** [comment]
The update to 3.5.1 changes nothing concerning this. If you are having these full text indexes in 3.5.0 then you will have it in 3.5.1 as well.

**Comment by rabuzarus** [comment]
It would not just be about updates. What is with new installations. They would get the the db structure from  dbstructure.php with the missing keys.

> The update to 3.5.1 changes nothing concerning this. If you are having these full text indexes in 3.5.0 then you will have it in 3.5.1 as well.

I just did a test with a test installation. The last git pull at this instance was some time ago. I checked the db. The keys for title and body were available. After this I did a git pull and run the update process. The keys were deleted.

Annado, I don't want to talk about if it would make sense to have this keys or not (I just don't know if they improve the searching process very much).
I just want to prevent that the user ends up with a setting that won't work.

If this feature doesn't make sense, fine lets remove it. Otherwise we should add the keys.

I know you are very busy at the moment. And this is nothing which needs to be done tomorrow. But we should decide this topic before we release

**Comment by annando** [comment]
Hmm, the dbstructure.php update shouldn't delete this kind of indexes. I'm not sure what exactly to do.

**Comment by annando** [comment]
@tobiasd @fabrixxm @hypolite What do you think? Should we just hide and disable this config value until we decided what to do?

**Comment by tobiasd** [comment]
The indices where removed because they slowed down big nodes?

**Comment by annando** [comment]
No. It seems as if they were removed falsely by the database update script. But in fact they are useless on bigger servers.

**Comment by tobiasd** [comment]
Personally I never had this option activated. I don't remember the reason though.

**Comment by annando** [comment]
Would anyone had a problem when I removed the disabled code completely? Thing is that fulltext indexes aren't working so great. Does anyone disagrees?

**Comment by Hypolite** [comment]
Removing commented code? I'm auto-agreeing!

**Comment by Hypolite** [comment]
Closed via #3354
