### ISSUE TITLE
Dev: unify the behavior of link elements in socialactivity objects

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#3158]
There is a different handling of presenting links in social activity objects. At the moment this does break the poking messages

e.g.:
Sender poke activity object
```
 <type>http://activitystrea.ms/schema/1.0/person</type>
 <title>Max Mustermann</type>
 <id>https://friendica.kommune4.de/contact/1145</id>
 <link>
     <link rel="alternate" type="text/html" href="https://test.kommune4.de/profile/trebor" />
     <link rel="photo" type="image/jpeg" href="https://friendica.kommune4.de/photo/6fe2fd5b8bb04da3b0159a5d15a422ea-4.jpg" />
 </link>
```
Received poke activity object
```
<type>http://activitystrea.ms/schema/1.0/person</type>
<title>Max Mustermann</type>
<id>https://friendica.kommune4.de/contact/1145</id>
<link rel="alternate" type="text/html" href="https://test.kommune4.de/profile/trebor" />
<link rel="photo" type="image/jpeg" href="https://friendica.kommune4.de/photo/6fe2fd5b8bb04da3b0159a5d15a422ea-4.jpg" />
```

You will find the discussion about this issue on https://helpers.pyxis.uberspace.de/display/4029d2ca89586e57ba58109268300550

**Comment by MrPetovan** [comment]
The link to the forum discussion doesn't work anymore. Which format should it be? The first or the second?

**Comment by annando** [comment]
For me this looks like if the sender is creating the first XML structure, but it arrives in the second form at the receiver. This would explain why it seemed to work when I tested it some months ago.

**Comment by MrPetovan** [comment]
This issue seems to be invalid as pokes are correctly sent and received.
