### ISSUE TITLE
Can't update to latest version, database errors

### ISSUE THREAD

**Issue by nytche** [friendica/friendica#3160]
Hello, 

When upgrading from 3.4.2. to 3.5, without git, I have the following errors when trying to update database:
"L'exécution de la mise à jour 1202 pour la structure de base de données a échoué avec l'erreur: Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `attach` MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `cache` MODIFY `v` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `contact` MODIFY `about` text, MODIFY `keywords` text, ADD `avatar` varchar(255) NOT NULL DEFAULT '', MODIFY `photo` text, MODIFY `thumb` text, MODIFY `micro` text, MODIFY `site-pubkey` text, MODIFY `pubkey` text, MODIFY `prvkey` text, MODIFY `request` text, MODIFY `notify` text, MODIFY `poll` text, MODIFY `confirm` text, MODIFY `poco` text, MODIFY `reason` text, MODIFY `info` mediumtext, MODIFY `ffi_keyword_blacklist` mediumtext, ADD INDEX `nurl` (`nurl`);
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `conv` MODIFY `recips` mediumtext, MODIFY `subject` mediumtext;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `event` MODIFY `summary` text, MODIFY `desc` text, MODIFY `location` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `fcontact` ADD `guid` varchar(255) NOT NULL DEFAULT '', MODIFY `pubkey` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `fsuggest` MODIFY `note` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `gcontact` MODIFY `about` text, MODIFY `keywords` text, ADD `birthday` varchar(32) NOT NULL DEFAULT '0000-00-00', ADD `hide` tinyint(1) NOT NULL DEFAULT 0, ADD `nsfw` tinyint(1) NOT NULL DEFAULT 0, ADD `notify` text, ADD `alias` varchar(255) NOT NULL DEFAULT '', ADD INDEX `name` (`name`), ADD INDEX `nick` (`nick`), ADD INDEX `addr` (`addr`);
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `gserver` MODIFY `info` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `intro` MODIFY `note` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `item` DROP INDEX `uid_unseen`, DROP INDEX `uid_starred`, ADD `gcontact-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `owner-id` int(11) NOT NULL DEFAULT 0, ADD `author-id` int(11) NOT NULL DEFAULT 0, MODIFY `body` mediumtext, MODIFY `object` text, MODIFY `target` text, MODIFY `postopts` text, MODIFY `tag` mediumtext, MODIFY `attach` mediumtext, MODIFY `inform` mediumtext, MODIFY `file` mediumtext, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext, MODIFY `rendered-html` mediumtext, ADD INDEX `uid_unseen_contactid` (`uid`,`unseen`,`contact-id`), ADD INDEX `uid_contactid_id` (`uid`,`contact-id`,`id`), ADD INDEX `gcontactid_uid_created` (`gcontact-id`,`uid`,`created`), ADD INDEX `authorid_created` (`author-id`,`created`), ADD INDEX `ownerid_created` (`owner-id`,`created`), ADD INDEX `uid_starred_id` (`uid`,`starred`,`id`);
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `mail` MODIFY `body` mediumtext;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `mailacct` MODIFY `pass` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `notify` MODIFY `msg` mediumtext;
Des erreurs ont été signalées lors de la création des tables.oembed
Des erreurs ont été signalées lors de la création des tables.parsed_url
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `photo` MODIFY `desc` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
Des erreurs ont été signalées lors de la création des tables.process
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `profile` MODIFY `with` text, MODIFY `pub_keywords` text, MODIFY `prv_keywords` text, MODIFY `likes` text, MODIFY `dislikes` text, MODIFY `about` text, MODIFY `music` text, MODIFY `book` text, MODIFY `tv` text, MODIFY `film` text, MODIFY `interest` text, MODIFY `romance` text, MODIFY `work` text, MODIFY `education` text, MODIFY `contact` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `queue` MODIFY `content` mediumtext;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `thread` ADD `gcontact-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `owner-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `author-id` int(11) unsigned NOT NULL DEFAULT 0, ADD INDEX `uid_gcontactid_commented` (`uid`,`gcontact-id`,`commented`), ADD INDEX `uid_gcontactid_created` (`uid`,`gcontact-id`,`created`);
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `user` MODIFY `pubkey` text, MODIFY `prvkey` text, MODIFY `spubkey` text, MODIFY `sprvkey` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext, MODIFY `openidserver` text;
Des erreurs sont survenues lors de la mise à jour de la base de données.ALTER TABLE `workerqueue` MODIFY `parameter` text;"

any idea on how to fix the issue?

**Comment by annando** [comment]
Please open a shell and execute the following command in the friendica web root:

````
php include/dbstructure.php update
````

Then the system checks manually for database changes. The command displays the executed sql queries. 

When the system returned some lines after you started this command then please try it a second time. When then no line is returned, the structure changes were successful. If not then please copy the sql queries into the mysql console and have a look for the returned error.

**Comment by nytche** [comment]
Here are the errors in the mysql console:

ALTER TABLE `attach` MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
ALTER TABLE `cache` MODIFY `v` text;
ALTER TABLE `contact` MODIFY `about` text, MODIFY `keywords` text, ADD `avatar` varchar(255) NOT NULL DEFAULT '', MODIFY `photo` text, MODIFY `thumb` text, MODIFY `micro` text, MODIFY `site-pubkey` text, MODIFY `pubkey` text, MODIFY `prvkey` text, MODIFY `request` text, MODIFY `notify` text, MODIFY `poll` text, MODIFY `confirm` text, MODIFY `poco` text, MODIFY `reason` text, MODIFY `info` mediumtext, MODIFY `ffi_keyword_blacklist` mediumtext, ADD INDEX `nurl` (`nurl`);
ALTER TABLE `conv` MODIFY `recips` mediumtext, MODIFY `subject` mediumtext;
ALTER TABLE `event` MODIFY `summary` text, MODIFY `desc` text, MODIFY `location` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
ALTER TABLE `fcontact` ADD `guid` varchar(255) NOT NULL DEFAULT '', MODIFY `pubkey` text;
ALTER TABLE `fsuggest` MODIFY `note` text;
ALTER TABLE `gcontact` MODIFY `about` text, MODIFY `keywords` text, ADD `birthday` varchar(32) NOT NULL DEFAULT '0000-00-00', ADD `hide` tinyint(1) NOT NULL DEFAULT 0, ADD `nsfw` tinyint(1) NOT NULL DEFAULT 0, ADD `notify` text, ADD `alias` varchar(255) NOT NULL DEFAULT '', ADD INDEX `name` (`name`), ADD INDEX `nick` (`nick`), ADD INDEX `addr` (`addr`);
ALTER TABLE `gserver` MODIFY `info` text;
ALTER TABLE `intro` MODIFY `note` text;
ALTER TABLE `item` DROP INDEX `uid_unseen`, DROP INDEX `uid_starred`, ADD `gcontact-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `owner-id` int(11) NOT NULL DEFAULT 0, ADD `author-id` int(11) NOT NULL DEFAULT 0, MODIFY `body` mediumtext, MODIFY `object` text, MODIFY `target` text, MODIFY `postopts` text, MODIFY `tag` mediumtext, MODIFY `attach` mediumtext, MODIFY `inform` mediumtext, MODIFY `file` mediumtext, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext, MODIFY `rendered-html` mediumtext, ADD INDEX `uid_unseen_contactid` (`uid`,`unseen`,`contact-id`), ADD INDEX `uid_contactid_id` (`uid`,`contact-id`,`id`), ADD INDEX `gcontactid_uid_created` (`gcontact-id`,`uid`,`created`), ADD INDEX `authorid_created` (`author-id`,`created`), ADD INDEX `ownerid_created` (`owner-id`,`created`), ADD INDEX `uid_starred_id` (`uid`,`starred`,`id`);
ALTER TABLE `mail` MODIFY `body` mediumtext;
ALTER TABLE `mailacct` MODIFY `pass` text;
ALTER TABLE `notify` MODIFY `msg` mediumtext;
CREATE TABLE IF NOT EXISTS `oembed` (
	`url` varchar(255) NOT NULL,
	`content` text,
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	 PRIMARY KEY(`url`),
	 INDEX `created` (`created`)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `parsed_url` (
	`url` varchar(255) NOT NULL,
	`guessing` tinyint(1) NOT NULL DEFAULT 0,
	`oembed` tinyint(1) NOT NULL DEFAULT 0,
	`content` text,
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	 PRIMARY KEY(`url`,`guessing`,`oembed`),
	 INDEX `created` (`created`)
) DEFAULT CHARSET=utf8mb4;
ALTER TABLE `photo` MODIFY `desc` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext;
CREATE TABLE IF NOT EXISTS `process` (
	`pid` int(10) unsigned NOT NULL,
	`command` varchar(32) NOT NULL DEFAULT '',
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	 PRIMARY KEY(`pid`),
	 INDEX `command` (`command`)
) DEFAULT CHARSET=utf8mb4;
ALTER TABLE `profile` MODIFY `with` text, MODIFY `pub_keywords` text, MODIFY `prv_keywords` text, MODIFY `likes` text, MODIFY `dislikes` text, MODIFY `about` text, MODIFY `music` text, MODIFY `book` text, MODIFY `tv` text, MODIFY `film` text, MODIFY `interest` text, MODIFY `romance` text, MODIFY `work` text, MODIFY `education` text, MODIFY `contact` text;
ALTER TABLE `queue` MODIFY `content` mediumtext;
ALTER TABLE `thread` ADD `gcontact-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `owner-id` int(11) unsigned NOT NULL DEFAULT 0, ADD `author-id` int(11) unsigned NOT NULL DEFAULT 0, ADD INDEX `uid_gcontactid_commented` (`uid`,`gcontact-id`,`commented`), ADD INDEX `uid_gcontactid_created` (`uid`,`gcontact-id`,`created`);
ALTER TABLE `user` MODIFY `pubkey` text, MODIFY `prvkey` text, MODIFY `spubkey` text, MODIFY `sprvkey` text, MODIFY `allow_cid` mediumtext, MODIFY `allow_gid` mediumtext, MODIFY `deny_cid` mediumtext, MODIFY `deny_gid` mediumtext, MODIFY `openidserver` text;
ALTER TABLE `workerqueue` MODIFY `parameter` text;

**Comment by annando** [comment]
You are using a MySQL version that doesn't allow ````0000-00-00 00:00:00```` as a valid value, I guess.

It would had been easier to analyze the problem if you had executed the sql queries line by line. Could you repeat that?

Concerning the ````0000-00-00 00:00:00```` problem please check your MySQL documentation if this behavior can be adjusted. I'm using MariaDB which doesn't have that problem.

**Comment by nytche** [comment]
Hello, 
I am not very good at SQL but I try to debug query by query as you said. But now I have a problem with the item table:
mysql> ALTER TABLE `item` DROP INDEX `uid_unseen`;
^C^C -- query aborted (because endless waiting)
ERROR 1034 (HY000): 137 when fixing table

I did not find the solution. Can you help?

**Comment by annando** [comment]
What do you declare "endless waiting"? The item table can be really huge. On my server it lasts several hours to change an index on the item table.

**Comment by nytche** [comment]
two hours I guest.
Tomorrow I can try running all day...

**Comment by annando** [comment]
I suggest that you open a second mysql console. Then you execute the command "show processlist;".

There you can see if the command is executed.

**Comment by eelcomaljaars** [comment]
Regarding the '0000-00-00 00:00:00' timestamp issue. I just ran into running a clean install. http://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at suggested setting the SQL mode in more recent versions of mysql to blank : 

SET sql_mode = '';

This worked for me (again on a clean install)

**Comment by annando** [comment]
Thanks @eelcomaljaars for this hint.

@nytche Can you try setting this sql mode and report back?

**Comment by nytche** [comment]
yes, SET sql_mode = ''; solved the date issue.
Saturday I ran all "item" queries all the day (around 45 mn per querie), I had to add backquotes on some field names.
Now I have another error syntax, I will check or post it here later.

**Comment by eelcomaljaars** [comment]
Please note that in the end, I had to declare this sql_mode setting on a server level in the my.cnf 👍 

[mysqld]
sql_mode = ''

and restart the server. (see #3174 and #3172) for more info

**Comment by nytche** [comment]
for datetime errors, sql_mode = ''; or SQL_MODE='ALLOW_INVALID_DATES';
Then I had to escape some tables names, those which included "-" and those with special names (but I don't remember now the names).

thank for your help!
