### ISSUE TITLE
Attached URL OEmbed: HTTP Code 302 should be followed

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3163]
Currently, Friendica is displaying a nice version of the first URL it finds in any post, the same way Facebook or Twitter do. However, the OEmbed retrieval process stops at the first response, which ends up showing 302 redirections:

![screen shot 2017-02-14 at 4 55 00 pm](https://cloud.githubusercontent.com/assets/925415/22951241/73852850-f2d6-11e6-8016-aa0e08dbe42c.png)

https://friendica.mrpetovan.com/display/d4e2bbc0d51e01342b53782bcb452bd5

I believe it's just a matter of setting curl `FOLLOW_LOCATION` setting to `true` in the OEmbed probe.

**Comment by annando** [comment]
No, sadly this is not so easy: http://stackoverflow.com/questions/2511410/curl-follow-location-error

**Comment by Hypolite** [comment]
Gotcha, this looks like something I'd like to fix.

**Comment by annando** [comment]
Our ````z_fetch_url```` function is already doing so - or should do so. So you could debug why it hadn't done here.

**Comment by Hypolite** [comment]
Definitely. Not a milestone issue though, don't worry about it.

**Comment by Hypolite** [comment]
I have more info. The problem isn't with `z_fetch_url` but with the `ParseUrl` library @rabuzarus wrote, and only with `medium.com` links.

The reason is ParseUrl is first issuing a `HEAD` request to obtain the actual resource location to query through redirections. However, it doesn't handle errors due to servers refusing `HEAD` requests, which means it goes to the `GET` request with an unfollowed URL, which yields `302 Found` link attachments.

My suggestion is to ditch the `HEAD` request(s) entirely. If there's a redirection, there's not much of a body anyway, so the overhead would not be significant. However, if there's no redirection, it cuts the number of HTTP requests in half, which is itself somewhat significant.

I'll submit a PR going this way.
