### ISSUE TITLE
addon leistungsschutzrecht needs a new source file for members of LSR

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3180]
The leistungsschutzrecht addon source URL for member information is not available anymore, thus the addon does not work ATM.

The LSR addon for WP (https://github.com/gglnx/d64-lsr-stopper) has a working source file in TXT form.

**Comment by Quix0r** [comment]
Maybe this is the right place: https://github.com/friendica/friendica-addons ?

**Comment by tobiasd** [comment]
No it is not.as the project is only using one issue tracker, hence the label for the addon.

**Comment by Quix0r** [comment]
Okay, I thought you have separate issue trackers.

**Comment by tobiasd** [comment]
With friendica/friendica-addons#416 the source of the list was updated. So I'm closing this issue.
