### ISSUE TITLE
Theme Frio: de localization suggestion + UI improvements for contact request dialog

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3187]
Please let me know if you think the proposal makes sense. And if so, if it should be split in two separate issues for localization and radio button UI change.

**Current contact request dialog in de**

> Soll Deine Beziehung beidseitig sein oder nicht? "Kontakt" bedeutet, ihr könnt gegenseitig die Beiträge des Anderen lesen dürft. "Fan/Verehrer", dass du das lesen deiner Beiträge erlaubst aber nicht die Beiträge der anderen Seite lesen möchtest. Genehmigen als:

**Proposal**

> Soll Deine Beziehung beidseitig sein?
> 
> Als _Kontakt_ könnt ihr gegenseitig die Beiträge des Anderen lesen. Als _Fan/Verehrer_ erlaubst du das Lesen deiner Beiträge, empfängst aber nicht die Beiträge des Anderen.

- Note 1: The radio button should be left of the text, having it on the right side feels wrong
- Note 2: I don't like the category "Fan/Verehrer". Verehrer is something romantic. I don't think it is appropriate in this context.

Happy to review the english strings for this location.

**Comment by rabuzarus** [comment]
Just a very short answer. The contact request template isn't yet written for friendica. So the issue name would be more correct with something like "there should be an own contact request template". But on the other hand I'm aware of all the missing templates in frio.

Note two  is a general friendica string issue and don't belong to frio.

**Comment by foss-** [comment]
let's discuss on friendica and file bugs *after* the community has given feedback.
