### ISSUE TITLE
frio: Hubzilla user comment direct link doesn't scroll to the relevant comment

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3194]
The following link refers to a post down the page, but the scroller chokes on the @ sign in the guid that only appears with Hubzilla comments:

https://friendica.mrpetovan.com/display/8b6eb4f1aae87ea75b7da19d49c5e7cff35ec144b758634a1db80cb7d0a1e8db%40lastauth.com

Javascript error:
````
Uncaught Error: Syntax error, unrecognized expression: #item-8b6eb4f1aae87ea75b7da19d49c5e7cff35ec144b758634a1db80cb7d0a1e8db%40lastauth.com
    at Function.gb.error (jquery.js:2)
    at gb.tokenize (jquery.js:2)
    at gb.select (jquery.js:2)
    at Function.gb [as find] (jquery.js:2)
    at m.fn.init.find (jquery.js:2)
    at e.fn.init.m.fn.init (jquery.js:2)
    at e.fn.init (jquery-migrate.js:2)
    at m (jquery.js:2)
    at scrollToItem (theme.js:582)
    at mod_display.js:10
    at dispatch (jquery.js:3)
    at r.handle (jquery.js:3)
````

**Comment by annando** [comment]
Yeah, this is known - but I'm too dumb for JS.

**Comment by Hypolite** [comment]
It just is a reminder for me, if I find a duplicate issue I'll close this.

**Comment by annando** [comment]
I don't think that is has been filed as issue.

**Comment by Hypolite** [comment]
Very well, then, it's on my list. 😊

**Comment by annando** [comment]
I just wrote your name on it :-)

**Comment by Hypolite** [comment]
Thanks, is there a way for me to assign a ticket to myself without being a collaborator?

**Comment by annando** [comment]
I don't know.

**Comment by Hypolite** [comment]
FWIW, regular user can't assign tasks themselves, only repository contributor and above can. I see the potential for abuse though if it was implemented, like a bot account assigning all the tasks of all the repositories to itself.

**Comment by tobiasd** [comment]
I'd say just write a comment below an issue and say that you are going to implement a fix for it.

**Comment by Hypolite** [comment]
Assigning allows visual hints and issue filtering in Github to better keep track of the issues you were intending on tackling. I often have to go through the whole list of recently modified issues to find the few I'm intenting to fix.

**Comment by tobiasd** [comment]
That is what I use the browsers bookmarks for ;-)

**Comment by Hypolite** [comment]
I'll admit I'm not using them to their full potential!
