### ISSUE TITLE
Directory maintainer

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#3198]
Based on #3053 I found that not only is my directory server a pretty important piece of infrastructure. My code is also the leading code for the directory. Even though I consider it very much unfinished and in a prototype state.

Looking at the commit history the directory hasn't gotten much love at all.
* May 2012 - November 2012, the first directory was built.
* June 2014 - August 2014, I made a bunch of improvements.

The rest of the time it's been completely silent.

There is a lot of room for improvement and lots of low hanging fruit when it comes to the directory code. **Having a maintainer for the directory would really make a difference I feel.** Hence this issue.

Some examples of what needs love:
- There's an unfinished [new design](http://dir-fc.oscp.info/home). Would be awesome to finish and have as the default.
- https://github.com/friendica/dir/issues/4 The statistics from http://dir-fc.oscp.info/health/25 shows 120 days, but the DB keeps stats forever and needlessly bloats DB disk usage.
- https://github.com/friendica/dir/issues/9 https://github.com/friendica/dir/issues/8 https://github.com/friendica/dir/issues/7 Would much improve the protocol currently in place for the directories.

**Comment by annando** [comment]
Too much issues, too few developers :-(

Additionally most of the stuff is frontend stuff. And I guess that most of our developers don't like the front end :-)

**Comment by Beanow** [comment]
@annando actually I think the frontend stuff can be kept really simple. Just take my design and put the rest of the content in.

The biggest issues are in the protocols. And some in the implementation quality.

**Comment by Hypolite** [comment]
This looks like a hill I could die on, after I'm done with the minor frontend fix for Friendica. However I'm not sure I'm grasping the full extent of the protocol(s) used, and I may need some kind of crash course or better, a 1-on-1 to get up to speed.

If I'm to update the design, I think I'll lean to a frio-like display. I like the cleanliness of your new design, but I'm confused about how to bring about a user/group list. There's a prominent search bar but I'm not sure if it accepts interests, location, etc...

**Comment by Beanow** [comment]
The search matches quite a lot. https://github.com/Beanow/dir/blob/feature/redesign-prototype/mod/search.php#L51

I don't mind talking about the internals. I just don't wish to be the maintainer, since I haven't been an active Friendica user for years. I would only be maintaining it to scratch the itch of seeing something I worked on unfinished.

I don't really mind which direction you want to go design wise. Anything is better than the old one.

**Comment by Hypolite** [comment]
I've done a dustup of the repository, merged multiple branches by tugelbend and Quix0r, I'm only a View away from merging the new design into the master branch.

**Comment by Beanow** [comment]
Seems as though you got the hang of the codebase. Let me know if you still need my thoughts on anything, like the protocols.

**Comment by Hypolite** [comment]
Thanks, I didn't touch any of it because I didn't see any reason for it not to work well.

**Comment by Beanow** [comment]
It works, but to say it works well may be stretching it :P
My biggest suggestions are already in https://github.com/friendica/dir/issues

Primarily because of https://github.com/friendica/dir/issues/9 there's still a chance profiles get overlooked. And in general the number of requests that need to be performed to keep this protocol up are fairly high.

Outside of reliability and performance. Changes to the protocol could also give the directory new use-cases. For example, https://fc.oscp.info/profile/admin is not a dead profile to be removed with the maintenance cron. But it isn't exactly a lively profile either. Including timestamps for most recent public activity could let you see who are active members and allows for interesting search filter options.

The only thing to actually cause problems in the long run may be https://github.com/friendica/dir/issues/13 and https://github.com/friendica/dir/issues/4, but otherwise they're about improvements.

**Comment by Hypolite** [comment]
I'll look at them in due time, right now I'm trying to finish the redesign so we can finally update the master branch of this repo. Thanks for your time and explanations!
