### ISSUE TITLE
Protocol/DB: Inconsistent use of contact-id for OStatus likes

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3203]
While trying to fix [the latest uncovered issue with highlighted Like button](https://github.com/friendica/friendica/issues/2792#issuecomment-279923637) (#2792), I discovered a pretty serious inconsistency in the `item` table in the way we store the `contact-id` for the like actions.

It can correspond either to:
- The `author` contact
- The `owner` contact
- The `uid` contact

The first two lines are weird enough, but problems arise with the last case which only happens with OStatus contacts on my posts (`uid != 0`). Not only it incorrectly attributes a like to me even though I never liked my post, but when I try to like the relevant item, it already finds a like with my `contact-id` and simply deletes it even though it was created by someone else. The process repeats until there aren't any like with `local_user() = uid = contact-id` on the item, deleting other contacts' likes.

I'm summoning @annando because I really am not familiar with the protocol, and there may be a reason why the `contact-id` isn't consistently the `author-id` of the item as the rest of the application is expecting. But the `contact-id = uid` case definitely needs to be addressed, and I don't really know where to start.

**Comment by Hypolite** [comment]
Additional data. Out of 35742 items with `like` verb that are assigned to my `uid`, here's how many values are corresponding to the same contact (not always the same `contact.id`)

All networks | uid | contact-id | gcontact-id | owner-id | author-id
------------ | ------------- | -- | -- | -- | --
uid | N/A | 955 | 926 | 193 | 926
contact-id | 955 | N/A | 5977 | 30209 | 5977
gcontact-id | 926 | 5977 | N/A | 1626 | 35739
owner-id | 193 | 30209 | 1626 | N/A | 1626
author-id | 926 | 5977 | 35739 | 1626 | N/A

There seems to be an almost perfect correlation between `gcontact-id` and `author-id`, however for `uid` and `contact-id`, there seem to be oddities (`contact-id = uid` and `uid = owner-id`).

This table isn't really telling, but a group by network is actually pretty interesting:

Friendica (2960) | uid  | contact-id | gcontact-id | owner-id | author-id
------------         | ---- | ----------- | ------------- | ---------- | ----------
uid                     | N/A | 926           | 926              | 193          | 926
contact-id          | 926 | N/A           | 1921           | 666           | 1921
gcontact-id       | 926  | 1921         | N/A             | 751           | 2957
owner-id           | 193  | 666           | 751              | N/A          | 751
author-id           | 926 | 1921         | 2957            | 751           | N/A

Diaspora (32282) | uid  | contact-id | gcontact-id | owner-id | author-id
------------           | ---- | ----------- | ------------- | ---------- | ----------
uid                       | N/A | 0               | 0                  | 0             | 0
contact-id            | 0     | N/A           | 3583            | 29072      | 3583
gcontact-id          | 0     | 3583         | N/A              | 373          | 32282
owner-id              | 0     | 29072       | 373              | N/A          | 373
author-id             | 0     | 3583         | 32282          | 373           | N/A

OStatus (502) | uid  | contact-id | gcontact-id | owner-id | author-id
-----------      | ---- | ----------- | ------------- | ---------- | ----------
uid                 | N/A | **29**            | 0                  | 0              | 0
contact-id      | **29**   | N/A          | 473              | 473          | 473
gcontact-id    | 0     | 473          | N/A             | 502           | 502
owner-id        | 0     | 473          | 502              | N/A          | 502
author-id       | 0      | 473         | 502              | 502          | N/A

The problem I have been having is located in the OStatus table, where it reads 29. Those are 29 likes from remote OStatus contacts on posts I wrote, and albeit I'm not considered the owner in any case, I'm wrongly the `contact-id`.

I'm now utterly confused by the meaning of `contact-id`, `owner` and `author` in the specific context of the `like`. I thought the author liked a post/comment written by the owner, and the `contact-id` should be the author, but this doesn't look like it's reliably the case in Friendica, and it definitely isn't the case with Diaspora and OStatus.

One thing for certain, the `gcontact-id` is at least the author in all of the three cases above. The missing 3 in the Friendica table are due to missing data in `gcontact` table.

**Comment by annando** [comment]
Nice coincidence. Just in these minutes I had a look at falsely highlighted likes :-)

I can explain the behaviour for the "contact-id": Every item needs this id. But it possible that (especially on Diaspora and OStatus) people can respond to our public posts even when they aren't in our contact table. So for these posts the "contact-id" is our own. This is why I created the "author-id".

The "contact-id" is mostly the author but sometimes the owner of an item. Since this is technically needed, it is clearly confusing. The "author-id" and "owner-id" on the other hand should be more reliable. They were added in one of the last versions.

The "gcontact-id" on the other hand is something that I added but that was superseded by "author-id" and "owner-id". We should drop that in the 3.5.2.

**Comment by Hypolite** [comment]
Are you saying we are about to drop the only consistent part of this card castle? 😭

**Comment by annando** [comment]
Just to emphasize this: the "contact-id" is only the technical contact. The "author-id" is the real author.

The "gcontact-id" was something in between. It doesn't help with repeated items and forum posts where author and owner are different.

**Comment by Hypolite** [comment]
The problem with `author-id` is that it references the public contact, which isn't the same as the logged in contact. For example, my `author-id` is `6` on my server, but I'm logging with the `contact-id = 1`. How can I check `author-id` against `local_user()`?

**Comment by annando** [comment]
We are in need of a function where this can be done easily.

**Comment by Hypolite** [comment]
Even before being done easily, can it actually be done? I couldn't find any field to link the various rows in the `contact` table that are, well, me.

**Comment by annando** [comment]
The function ````get_contact($url);```` will return the appropriate id. You simply have to feed it with the url of the ````self````contact for your user id.

**Comment by Hypolite** [comment]
Thanks, it is indeed not easy at the moment. Is there anything else to do in this issue, either right now or in the future, or should we close it as is?

**Comment by annando** [comment]
You have to decide if you agree with this explanation or if you want something to be changed ;-)

**Comment by Hypolite** [comment]
I'm fine with using `author-id` and enabling an easier bridge with the current logged in user. Closing for now.
