### ISSUE TITLE
Twitter Addon: Truncates statuses quoting a tweet and re-embed the status

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3215]
**EDIT**: This was witnessed on a version of friendica-addons dating back to October 2016. All my supplied examples are obsolete and I'm waiting on a new instance of the issue to appear with the latest codebase.

I have the Twitter connector enabled to post on my behalf on Friendica for each non-reply tweet I post, and I've spotted an annoying display quirk when adding a quoted tweet in a status.

Basically, up to a certain length, the status' text is truncated (even though we don't have a character limit on Friendica) and then the initial tweet is embedded, instead of the quoted tweet.

Exemple (sorry about the french language): https://friendica.mrpetovan.com/display/735a20291958b983cb33bd6218002887
![screen shot 2017-03-07 at 3 12 58 pm](https://cloud.githubusercontent.com/assets/925415/23675881/d10e873c-0348-11e7-9d23-e3fd3c1fe9dd.png)

Expected result: https://friendica.mrpetovan.com/display/735a20295658bf151fa2e49008804641
![screen shot 2017-03-07 at 3 16 40 pm](https://cloud.githubusercontent.com/assets/925415/23675998/25a55a1e-0349-11e7-89b0-c0b437b408f3.png)

I believe it just is a code change since all the information is already displayed and accessible, either directly in the status, or through probing.

**Comment by annando** [comment]
The first post is created with the mirror function, isn't it? I guess we have to implement there the changes we already had done in the timeline import function to import quoted tweets.

**Comment by Hypolite** [comment]
It turns out this issue isn't limited to quoted tweets, even regular tweets can be truncated and then self-quoted in the Friendica post.

Example of a media post: https://friendica.mrpetovan.com/display/735a20291858bf1cfd2e7e1507541226

**Comment by annando** [comment]
BTW: You had updated the Addons recently, hadn't you?

**Comment by Hypolite** [comment]
It looks like I was up to date with master

**Comment by annando** [comment]
Could you post the content of the object field?

**Comment by Hypolite** [comment]
The content field seems empty for all the examples above. Here's the `body` fields, even though it's not very helpful:
````
C'est au contraire le meilleur exemple de démocratie s'il est effectivement élu sans être candidat. Tout sera donc… 
[attachment type='link' url='https://twitter.com/i/web/status/837677246701764608' title='Hypolite Petovan on Twitter' preview='https://pbs.twimg.com/profile_images/1704456086/hypolite_lunettes_instagram_recadre_400x400.jpg']“C'est au contraire le meilleur exemple de démocratie s'il est effectivement élu sans être candidat. Tout sera donc fait pour l'empêcher. https://t.co/WfUj2oO9r3”[/attachment]
````

````
Le mystère @decodexofficiel s'épaissit, fdesouche, les-crises et valeursactuelles provoquent une erreur. Heureuseme… 
[attachment type='link' url='https://twitter.com/i/web/status/839214816141185025' title='Hypolite Petovan on Twitter' image='https://pbs.twimg.com/media/C6V9UR0XQAIbCdm.jpg:large']“Le mystère @decodexofficiel s'épaissit, fdesouche, les-crises et valeursactuelles provoquent une erreur. Heureusement, pas lemonde.”[/attachment]
````

**Comment by annando** [comment]
Are you *really* sure that the Twitter addon is on the current version? We are storing the Twitter data in the Object field for some time now.

**Comment by Hypolite** [comment]
````
~/friendica/addon$ git fetch
~/friendica/addon$ git pull
Already up-to-date.
~/friendica/addon$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
````
Am I missing something?

**Comment by annando** [comment]
That commt is from October: https://github.com/friendica/friendica-addons/commit/8ef2b13360c9b7908798b8912cea8af4c218e7ca

This one is the most current one: https://github.com/friendica/friendica-addons/commit/bb04495f5b1941002b624b9463c6a3c6f5030f07

**Comment by annando** [comment]
I just saw a mirrored post with a quote that worked just fine: https://pirati.ca/display/ec054ce71758c2c1d865af9984446495

**Comment by Hypolite** [comment]
This doesn't look like a Twitter status that would have been imported to Friendica, can you confirm if it just is a Friendica post referencing a tweet or a Twitter-originated post?

And WTF about the state of my cloned repository of friendica-addons?! I may have to scrap it entirely and start fresh again. Oh well.

**Comment by annando** [comment]
This post was a tweet that was redistributed as Friendica post via the "mirror" function of the Twitter addon - just like your post.

It is looking different because I have disabled OEmbed. See here for another view of the same post:
https://pod.geraspora.de/posts/ec054ce71758c2c1d865af9984446495

**Comment by Hypolite** [comment]
Nevermind, I just realized I cloned my own friendica-addons repo instead of the official one. No wonder it wasn't up-to-date. I ended up scrapping the folder and cloning the right repo.

I'll try another retweet on Twitter, I'll tell you if it still truncates the mirrored post.

**Comment by Hypolite** [comment]
Unable to reproduce the issue with latest code, yay and thanks!
