### ISSUE TITLE
Diaspora: embedded images with link turn wrong on Friendica

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3217]
Original Diaspora post: https://pod.geraspora.de/posts/efcc9a60e25c0134760b4860008dbc6c

Friendica result: https://friendica.mrpetovan.com/display/efcc9a60e25c0134760b4860008dbc6c

I'm self-assigning this issue.

**Comment by annando** [comment]
Yeah, this is looking horrible.

**Comment by Hypolite** [comment]
Closed #3217 via #3222.
