### ISSUE TITLE
Twitter: Strip @ mentions from posts to Twitter

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3218]
Currently, we export verbatim Friendica posts to Twitter including @-mentions, which means that "**@Hypolite Petovan**" on Friendica gets turned into "**@Hypolite** Petovan" once posted on Twitter, which triggers unexpected mentions of unknown Twitter accounts.

The @ sign should just be stripped from the output to Twitter so that no confusion is possible.

I'm self-assigning this issue.

**Comment by annando** [comment]
I'm using the "@" to directly address Twitter persons e.g. in comments. When people are doing crossposts they have to consider things like addressing people. Because of things like this, the "abstract" bbcode was created.

**Comment by tobiasd** [comment]
*People* usually don't consider anything ;-)

Maybe we can use `@nick` instead of `@name` for the Twitter message?

**Comment by annando** [comment]
Since several versions I want to change every plaintext output from ````@name```` to ````@nick````. I always forget to do it ;-) (The changes would also be done in the API. Additionally I wanted to change the ````@nick+id```` in the editor to ````@nick@domain.tld````

**Comment by Hypolite** [comment]
Do your Friendica comments ever get posted on Twitter? Do you mention Twitter handles in top-level posts? This PR is targeted at top-level posts, specifically shared posts that are likely to contains mentions of people in the Fediverse without you having to consider anything.

I guess I could add a condition in the @-stripping case if the related account link is a twitter.com/nick.

**Comment by annando** [comment]
I'm importing the Twitter timeline. So I comment a lot on Twitter posts - and the function is the same.

**Comment by Hypolite** [comment]
Thanks you for the elaboration, I don't use that particular feature so I wasn't sure it was available. Then what I did is wildly off the mark. What about my suggestion of keeping @ signs for recognized Twitter accounts links?

**Comment by annando** [comment]
The opposite would be better: Remove it for known non-Twitter accounts. We can use the public contacts for checking.

**Comment by Hypolite** [comment]
By default all mentioned accounts are known since we create a public profile if it doesn't exist during tge BBCode conversion. So both your version and mine seem equivalent to me. Am I missing anything?

**Comment by annando** [comment]
You are missing when someone just enters ````@username```` without any full profile link.

**Comment by Hypolite** [comment]
Ok, this wouldn't be a problem since my code only deals with @-mentions that get transformed into links like `@[url=http://server.tld/nick]Full Name[/url]` (known accounts). By checking for `twitter.com` in the `server.tld` part, I can make sure I only remove the @ sign for non-Twitter accounts.

What do you think?

**Comment by annando** [comment]
Not so good. We have other two way connectors. Hopefully soon there will come pnut.io. For this the same rules apply. Having a positive list to only remove the links to profiles from from distributed systems is the better idea.

**Comment by Hypolite** [comment]
Do you mean checking the network of the contact related to each @-mention and weeding out the one that aren't the target network? I'm utterly confused, would accept any implementation hint.

**Comment by annando** [comment]
You could use a callback function. This function then would check against the public contacts. And if it finds out that the contact is one of the federated ones, it would replace the "@". Otherwise it should reduce it to ````@username````

**Comment by Hypolite** [comment]
Ok, that was what I had in mind. This means the network list to check against would be static? We would just strip the @ for DFRN, Diaspora and OStatus/StatusNet, right?

**Comment by annando** [comment]
I would add pump.io as well. And we could add new networks to it at any time.

**Comment by Hypolite** [comment]
See, that's what I wanted to avoid. Since we know the target network when we create the post in the Twitter/Facebook/etc... addon, we can remove every @-mention link but the Twitter ones.

**Comment by annando** [comment]
Best would be if the BBCode function would know the network for which the code is generated.

**Comment by Hypolite** [comment]
It's already the case to some extent with the `$simplehtml` or `$htmlmode` parameters, but I feel like network-specific treatment should be done outside of the main BBCode function, or else it will just grow uncontrollably bigger as we add new network support/addons.

**Comment by annando** [comment]
I would like to replace this code conglomerate with a complete new class. We could work with a parameter array

**Comment by Hypolite** [comment]
This wouldn't really solve the network-specific dilemma of having a big do-it-all blob or a per-addon network-specific touchups, a solution I prefer.

**Comment by Shnoulle** [comment]
I have exactly the same issue with gnusocial and TwitterBridge : and some of my ostatus contcat have same nickname in twitter. I have to deactivate TwitterBridge for this . Think the 'removing' all user (except twitter account) is a good solution ... but : i prefer to be able to to send a notice/twitt to one specific user on twitter ....

**Comment by annando** [comment]
@Shnoulle The Twitter Bridge in GNU Social is very basic and has got several limitations. You cannot decide on a single post basis if you want to post that specific content to Twitter or not.

I, personally, disabling the posting to Twitter whenever it is a post that doesn't make sense there. And every post that mentions a Friendica user shouldn't make sense at Twitter.

**Comment by Shnoulle** [comment]
@annando yes, i know the limitation of twitterbridge, but have some good point ;) and i use it during a long time then have some experience :) of : this is a good point / this is not a good point. And clearly the `@username` is a bad pint ( poor `@dbd@twitter.com` )

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/754
