### ISSUE TITLE
Protocol-less OpenID URI is not accepted

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3230]
An OpenID URI with no protocol part (ie: `someone.openid.org`) is allowed by OpenID specification, where normalization of the URI is supposed to turn that to `http://someone.openid.org`. Friendica instead (develop branch, commit 3f6fd8ee691c7d46496e63cb13360cb8f8b0a9d6) tells me: "Please enter an URL." with a client-side popup.

**Comment by strk** [comment]
NOTE: protocol-less works fine from the login page, just fails from the user setting page

**Comment by strk** [comment]
Things might have broke by 8367cadeeffec4b6792a502847304b17ceba5882 (or at least that commit is the one that comments-out the normalization step, and contains a commit log which seems wrong [using https instead of http when protocol is missing]).  @tobiasd anything to say about that ?

**Comment by strk** [comment]
Forget about the above, the URL validity check is clearly a client-side check, so must be in the theme. I'm using Frio, if that matters.

**Comment by strk** [comment]
Do you know which code handles the "Please enter a URL." message ? I cannot find it in the sourcecode

**Comment by strk** [comment]
Ok this patch fixes it, but I guess we might want to have a custom client-side validator, how would that be done ?

```
diff --git a/mod/settings.php b/mod/settings.php
index 1d83251..c12943a 100644
--- a/mod/settings.php
+++ b/mod/settings.php
@@ -1160,7 +1160,7 @@ function settings_content(App $a) {
        if ($noid) {
                $openid_field = false;
        } else {
-               $openid_field = array('openid_url', t('OpenID:'),$openid, t("\x28Optional\x29 Allow this OpenID to login to this account."), "", "", "url");
+               $openid_field = array('openid_url', t('OpenID:'),$openid, t("\x28Optional\x29 Allow this OpenID to login to this account.")); //, "", "", "url");
        }
 
        $opt_tpl = get_markup_template("field_yesno.tpl");
```

**Comment by annando** [comment]
@strk Do you know what such a protocol less URI does return upon authentication as identity?

**Comment by strk** [comment]
I don't understand the question, but from reading my original submission it looks like the problem was that Friendica just did not allow protocol-less URI and OpenID spec wants to add `http://` in front in that case

**Comment by annando** [comment]
The OpenID server does return an identity URL upon authentication. So in your case this can be without protocol?

**Comment by strk** [comment]
The URL returned by server is fine, my understanding is that the _javascript_ of Friendica does not even hit the server when the URL does not start with a protocol. This is what the initial bug submission seems to say (I did not test recently to see if anything changed)

**Comment by annando** [comment]
The background of my question was this: The value in the user settings has to be the value that is returned by the OpenID server. So when the server returns an URL without protocol, then we have to change something. When it is only that you can enter a value without protocol, then we had to change some more stuff at our backend.

**Comment by strk** [comment]
The server returns an URL with the protocol. I think the Friendica backend should contact the server and request authentication prior to allow you to enter the string. This would give it a way to obtain the real openid (server-returned).

**Comment by strk** [comment]
See #3231 for the server verification... doing that might fix this (once the client-side check is removed)

**Comment by annando** [comment]
See my comment for that issue. Can we then close this here and postpone the issue #3231 to the next version with the added task to simplify the process of assigning the authentication URL?

**Comment by strk** [comment]
Ok, closing
