### ISSUE TITLE
Replace smileys in API

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#3234]
in the API /statuses/friends_timeline in the statusnet_html field i see the smiley code and not a link to the smiley picture. Can this be replaced by a link to the smiley picture for the smileys (in core and in the smileys-addon) just like in the web frontend?

**Comment by tobiasd** [comment]
I think it should then honor the user settings about the emoticons then.

**Comment by annando** [comment]
In the develop branch the emojis are now replaced with unicode emojis when this addon is activated.
