### ISSUE TITLE
API: Parse BBCode in direct messages

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#3235]
If I send the link BBCode in a new status, it gets parsed into a link for the receiver. In a direct message i get only the BBCode (at least in the /direct_messages/all API) back.

**Comment by tobiasd** [comment]
I've just checked it in Twidere, the link URL was displayed after the link text, but the text itself was not clickable. In the web UI the link text is clickable as intended.

That's was you mean?

**Comment by annando** [comment]
We have completely reworked the API since them. Also there aren't that many client our there yet, who support that API at all. Now the Mastodon API is used the most.
