### ISSUE TITLE
Binary attachments in statuses via API

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#3238]
In the web view I can see binary attachments in Posts. In the API api/statuses/friends_timeline only links to images are shown as attachement due to compatibility issues with GNU Social. An additional return value for binary attachments would be great (perhaps in the friendica_activities part).

**Comment by LubuWest** [comment]
Is this still on the agenda?

**Comment by tobiasd** [comment]
It looks like it dropped off the agenda, when the milestones 3.6.1 was renamed to 2018.05. That rename has caused many such instances with dropped issues from the agenda and I did not found all of these back then. So I've put it onto the agenda again.

**Comment by annando** [comment]
The API had been completely reworked since then. I guess we can close it.
