### ISSUE TITLE
maintenance mode should be informative

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3242]
When the Friendica is set into maintenance mode, the node is showing a very brief notification only.

The nodes admin should have the possibility to set a reason for the maintenance. Alternatively to the simple message, it should be possible to set an URL for a page with further information. Visitors should be redirected to that page if the URL is set.

**Comment by annando** [comment]
I think we can close the issue now?

**Comment by Hypolite** [comment]
Tobias suggested that you could define a custom URL to show during maintenance mode. Your PR only covers the maintenance mode message.

**Comment by annando** [comment]
So I suggest that if the description is a link then the system does a redirect?

**Comment by tobiasd** [comment]
Sounds like a good idea for me :-) This should then be mentioned in the help as well.
