### ISSUE TITLE
Call to undefined function get_lockpath() in .../addon/pumpio/pumpio_sync.php on line 44

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3255]
Right after upgrading to develop branch (8752ce6254ddca9e0eb66353489649f672f92e3f)  I'm not being flooded by messages originating from the cron job poller:
```
Call to undefined function get_lockpath() in .../addon/pumpio/pumpio_sync.php on line 44
```

**Comment by strk** [comment]
seems to be fixed in the friendica-addon master repository, please disreguard this (wrong repo anyway)

**Comment by Hypolite** [comment]
Everything went better than expected 🌈
