### ISSUE TITLE
Friendica code blocks aren't rendered in Diaspora

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3274]
This is the flip side of #3189

Friendica's code blocks gets added HTML tags breaking the whitespace structure when viewed in Diaspora. It might be something we can fix on our end the same way #3189 was fixed, by removing code blocks before any whitespace management, and then re-adding them to the resulting message afterwards.

![Friendica code block](https://p.elaon.de/CjFTGK/)

![Diaspora code block](https://p.elaon.de/J3x/)

Reference post: https://friendica.mrpetovan.com/display/1860bc0e6158d14834e95d6899168678

Thanks Rebeka for the report!

**Comment by annando** [comment]
We also should update the HTML2Markdown library. We are currently using 2.2.1, but the current version is 4.4.1.

**Comment by Hypolite** [comment]
Perfect, I'll do that in the same movement.

**Comment by Hypolite** [comment]
I narrowed down the issue, it's about `<code>` tags being transformed into inline code in Markdown instead of code blocks. An update of the HTML-to-Markdown library could be enough to solve the issue, however I'm waiting on [a decision about Composer](https://friendica.mrpetovan.com/display/735a20297958dc5b05af6fc298562397) to go through the hassle of adding it myself of use the shiny Composer config file.
