### ISSUE TITLE
Mastodon: Support Content Warning

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3285]
Original: https://mastodon.social/users/dia/updates/1518924
Friendica: https://friendica.mrpetovan.com/display/52acf9cd888b8ed9b472abac0789e9547341987c

XML:

````xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:mastodon="http://mastodon.social/schema/1.0" xmlns:media="http://purl.org/syndication/atommedia" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:thr="http://purl.org/syndication/thread/1.0">
   <id>https://mastodon.social/users/dia.atom</id>
   <title>&amp;#x2666;&amp;#xFE0F;&amp;#xFF24;&amp;#xFF49;&amp;#xFF41;&amp;#x2666;&amp;#xFE0F;</title>
   <subtitle>I like you!</subtitle>
   <updated>2017-04-03T11:35:30Z</updated>
   <logo>https://files.mastodon.social/accounts/avatars/000/006/755/original/0a7d7fa7d8f24c98.png?1491173125</logo>
   <author>
      <id>https://mastodon.social/users/dia</id>
      <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
      <uri>https://mastodon.social/users/dia</uri>
      <name>dia</name>
      <email>dia@mastodon.social</email>
      <summary>I like you!</summary>
      <link rel="alternate" type="text/html" href="https://mastodon.social/@dia" />
      <link rel="avatar" type="image/png" media:width="120" media:height="120" href="https://files.mastodon.social/accounts/avatars/000/006/755/original/0a7d7fa7d8f24c98.png?1491173125" />
      <link rel="header" type="image/png" media:width="700" media:height="335" href="https://files.mastodon.social/accounts/headers/000/006/755/original/POqg3uN.png?1480857915" />
      <poco:preferredUsername>dia</poco:preferredUsername>
      <poco:displayName>&amp;#x2666;&amp;#xFE0F;&amp;#xFF24;&amp;#xFF49;&amp;#xFF41;&amp;#x2666;&amp;#xFE0F;</poco:displayName>
      <poco:note>I like you!</poco:note>
      <mastodon:scope>public</mastodon:scope>
   </author>
   <link rel="alternate" type="text/html" href="https://mastodon.social/@dia" />
   <link rel="self" type="application/atom+xml" href="https://mastodon.social/users/dia.atom" />
   <link rel="hub" href="https://mastodon.social/api/push" />
   <link rel="salmon" href="https://mastodon.social/api/salmon/6755" />
   <entry>
      <id>tag:mastodon.social,2017-04-03:objectId=1484062:objectType=Status</id>
      <published>2017-04-03T11:35:30Z</published>
      <updated>2017-04-03T11:35:30Z</updated>
      <title>@Mutsui &amp;#xE0; la fin ils meurent</title>
      <summary>spoilers rom&amp;#xE9;o et juliette</summary>
      <content type="html">&amp;lt;p&amp;gt;&amp;lt;a href="https://mastodon.social/@Mutsui" class="h-card u-url p-nickname mention"&amp;gt;@&amp;lt;span&amp;gt;Mutsui&amp;lt;/span&amp;gt;&amp;lt;/a&amp;gt; &amp;#xE0; la fin ils meurent&amp;lt;/p&amp;gt;</content>
      <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
      <link rel="self" type="application/atom+xml" href="https://mastodon.social/users/dia/updates/1518924.atom" />
      <link rel="alternate" type="text/html" href="https://mastodon.social/users/dia/updates/1518924" />
      <activity:object-type>http://activitystrea.ms/schema/1.0/comment</activity:object-type>
      <thr:in-reply-to ref="tag:mastodon.social,2017-04-03:objectId=1484051:objectType=Status" href="https://mastodon.social/@dia/1484051" type="text/html" />
      <link rel="mentioned" href="https://mastodon.social/users/Mutsui" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" />
      <mastodon:scope>unlisted</mastodon:scope>
   </entry>
</feed>
````

Not sure if the Content Warning is passed in the XML object, maybe it's a Mastodon feature request to pass the info in the XML first. Any idea @annando ?

**Comment by annando** [comment]
If @gargron tells where this is hidden, we can add some #nsfw tag to it to trigger our own system.

**Comment by Hypolite** [comment]
Another unfortunate example:

Mastodon: https://mastodon.xyz/users/alex73630/updates/3212
Friendica: https://friendica.mrpetovan.com/display/47cb7c42f887b8dbbe6a327c04551ac37ce46677

XML Object to come tonight.

**Comment by Hypolite** [comment]
I've got an answer from Gargron: Everything is in the `summary` tag. If it's present, it should be the clear text, while the `content` should be hidden by default only to be revealed by a click.

**Comment by Hypolite** [comment]
Closed via #3315

**Comment by Gargron** [comment]
:+1: 💯

**Comment by adrianheine** [comment]
Is there an issue for the other way round, i. e. federating posts with spoiler to mastodon?

**Comment by annando** [comment]
You could enclose stuff like this: ```[abstract]Abstract[/abstract]```

**Comment by MrPetovan** [comment]
It wouldn’t create a CW on the Mastodon side, just a specific version of the post text.

**Comment by annando** [comment]
The "abstract" for ActivityPub is filling the "summary" field, which on Mastodon is used for the content warning: https://github.com/friendica/friendica/blob/develop/src/Protocol/ActivityPub/Transmitter.php#L1198

**Comment by MrPetovan** [comment]
Isn't that a pretty big departure from the `abstract` intent? Is it documented anywhere?

**Comment by annando** [comment]
I do consider an "abstract" similar to a "summary" - like the Wikipedia is doing: https://en.wikipedia.org/wiki/Abstract_%28summary%29

**Comment by MrPetovan** [comment]
Indeed, but for other platforms, the abstract replaces the whole post body, while in this case it supplements it. I'm glad @tobiasd thought about the special case and took on himself to document it.

**Comment by annando** [comment]
Other platforms are more limited and can only display the abstract and not both fields :-)

**Comment by adrianheine** [comment]
But the abstract is not shown on Friendica, right?

**Comment by annando** [comment]
That's correct.

**Comment by adrianheine** [comment]
So there's no way to write a CW from Friendica to Friendica and Mastodon, but you can do that from Mastodon …

**Comment by annando** [comment]
Mastodon does misuse the "summary" field for its content warning.

**Comment by adrianheine** [comment]
Yeah, I know, but it's still unfortunate that Friendica cannot trigger this Friendica feature while Mastodon can.

**Comment by MrPetovan** [comment]
Friendica has a more complex post collapse system that is receiver-driven instead of sender-driven. Look for the filtering addons like Advanced Content Filter, blockem, Language Filter, NSFW and Show More.
