### ISSUE TITLE
GNU Social: Didn't get delivered a reply to a requipped post of mine

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3299]
My [post about the fediverse graph](https://friendica.mrpetovan.com/display/735a20299758e67bc2dcb15917892881) got requipped on GNU Social, then someone replied to it, but I can't see this post anywhere on my instance nor I got a notification about it.

Friendica post: https://friendica.mrpetovan.com/display/735a20299758e67bc2dcb15917892881
GNU Social Requip: https://gs.archae.me/notice/614772
GNU Social reply: https://social.freedombone.net/notice/118295

Is there anything I should have done to get the reply delivered to me on my instance?

**Comment by annando** [comment]
Normally it should work. Have a look at your logfile for the message.

**Comment by Hypolite** [comment]
I don't have the logfile enabled at all times unfortunately. 😕

**Comment by annando** [comment]
So we won't be able to dig into it :-(

**Comment by annando** [comment]
I don't think that we can do anything about this. We process every incoming post. So when there is no incoming post, then we cannot change anything about this.
