### ISSUE TITLE
mkdir(): Permission denied in /var/www/friendica/boot.php on line 2478

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3300]
Hello,

I get this warning when running `include/poller.php`:
```
PHP Warning:  mkdir(): Permission denied in /var/www/friendica/boot.php on line 2478
```

(I'm using the develop branch.)

**Comment by annando** [comment]
Seems like your temp directory is not really writable. Are you using systemd-tmpfiles?

**Comment by Rudloff** [comment]
The directory is writable (`touch /tmp/foo` works).
It seems the issue is that Friendica is trying to write directly to `/hostname`. I think it is because the `$new_temppath` variable is created by appending to nothing: https://github.com/friendica/friendica/blob/develop/boot.php#L2475

**Comment by annando** [comment]
You are right. The variable ```$new_temppath``` isn't defined. I guess that one of the last pull requests had created that problem. I will fix it this weekend.

**Comment by annando** [comment]
@Rudloff please update your system, then report if the problem was solved.

Thank you for reporting this!

**Comment by Rudloff** [comment]
Yes, it seems to be fixed, thanks!

**Comment by Rudloff** [comment]
Yes, it seems to be fixed, thanks!
