### ISSUE TITLE
API for events

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#3302]
I can see a JSON of events in /cal/[profile]/json. Is it possible to provide the same function (also related functions for creating events) in the  API section for the logged in user? Thanks!

**Comment by AlfredSK** [comment]
"Could someone with a github account please close the issue 3302? It was solved with the friendica/events API in 2020.03. Thanks!"

https://forum.friendi.ca/display/3e98eba8-175e-daaa-7c4a-95a563934705
