### ISSUE TITLE
"Secure Mail" Settings Key not accepted

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#3313]
My key is not accepted, it was working, but at some point I wanted to change it. The new key was not accepted and then the old one was not accepted anymore. 

Key: https://pgp.mit.edu/pks/lookup?search=0xFB3110E80DAA7AE33E45850DA3401A895B9295A2&op=index

Message in Friendica: 

> Das Sicherheitsmerkmal war nicht korrekt. Das passiert meistens wenn das Formular vor dem Absenden zu lange geöffnet war (länger als 3 Stunden).

Translated: 
> The security feature was not correct. This happens mostly when the form was opened too long before sending (longer than 3 hours).

I can enter an invalid text which will be taken as a key. I just entered this by mistake and it was accepted:
> "Secure Mail" Settings

Let me know what information I should provide.

**Comment by tobiasd** [comment]
On Sun, 09 Apr 2017 05:38:22 -0700
ben-utzer <notifications@github.com> wrote:

> Let me know what information I should provide. 

What size does your key have? IIRC 1024 should work.

**Comment by ben-utzer** [comment]
> What size does your key have? IIRC 1024 should work.
4096 Bit, it was working before.

**Comment by tobiasd** [comment]
Ok, when it was working before, I had problems with large keys when I used the addon.

@fabrixxm should have a look then.

**Comment by ben-utzer** [comment]
Be careful when you test this, I just played around and since can`t add the key anymore. Can someone tell me where this is stored in the DB, I will add it manually.

**Comment by fabrixxm** [comment]
That addon needs some love..
the gpg library is using is not actively maintained anymore, and the version the addon ships is older than the last release. It says it supports up to 4096 bit keys, but there was an issue with keys bigger than 2048. The issue was then closed, but I think it was closed in a more recent version than the one shipped.

**Comment by fabrixxm** [comment]
anyway, the key is saved in db, "pconfig" table, uid=your user id, cat="securemail", k="pkey"

**Comment by fabrixxm** [comment]
take a look at friendica/friendica-addons#410

**Comment by tobiasd** [comment]
@ben-utzer what is the status here?

**Comment by tobiasd** [comment]
Seems to be working now, so I'll close the issue.

**Comment by ben-utzer** [comment]
Yes it is working, sorry missed this on Github.
