### ISSUE TITLE
Emoji replaced by "?"

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3314]
Hello,

When I try to post the `😱` emoji, it is replaced by `?`.
Here is an example: https://social.rudloff.pro/display/de03dfa01358ea9f0dd83bf618135465

**Comment by Hypolite** [comment]
Is your database compatible with the `utf8mb4` collation? What branch are you using? The Emoji support was introduced in the 3.5.1 stable version through a database update, please make sure your schema is up to date in the Admin panel.

**Comment by Rudloff** [comment]
I'm using the develop branch (3.5.1-553-gb9c0c11) and the admin says the database is correctly updated.
My MySQL server supports `utf8mb4` (running `ALTER DATABASE foo CHARACTER SET = utf8mb4;` works).

But my Friendica database seems to still use `utf8_general_ci`.
Maybe something wrong with the update? Should I manually change the collation?

**Comment by Hypolite** [comment]
If you manually change the collation of your database, you will be only changing  the default collation for new tables, e.g. the collation of the next table that is created without collation information. Same thing with table collation which is the default field collation.

The collation information only is important at the field level. Can you show us what the `CREATE TABLE` of the `item` table looks like? Fields like `body`, `title` and `object` should have the following collation: `utf8mb4_general_ci`.

**Comment by Rudloff** [comment]
I still see `utf8_general_ci` for these fields in phpMyAdmin.

Here is the SQL export from the `item` table:
```sql
CREATE TABLE IF NOT EXISTS `item` (
`id` int(10) unsigned NOT NULL,
  `guid` varchar(255) NOT NULL DEFAULT '',
  `uri` varchar(255) NOT NULL DEFAULT '',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `contact-id` int(11) NOT NULL DEFAULT '0',
  `gcontact-id` int(11) unsigned NOT NULL DEFAULT '0',
  `type` varchar(255) NOT NULL DEFAULT '',
  `wall` tinyint(1) NOT NULL DEFAULT '0',
  `gravity` tinyint(1) NOT NULL DEFAULT '0',
  `parent` int(10) unsigned NOT NULL DEFAULT '0',
  `parent-uri` varchar(255) NOT NULL DEFAULT '',
  `extid` varchar(255) NOT NULL DEFAULT '',
  `thr-parent` varchar(255) NOT NULL DEFAULT '',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `edited` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `commented` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `received` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `changed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `owner-id` int(11) NOT NULL DEFAULT '0',
  `owner-name` varchar(255) NOT NULL DEFAULT '',
  `owner-link` varchar(255) NOT NULL DEFAULT '',
  `owner-avatar` varchar(255) NOT NULL DEFAULT '',
  `author-id` int(11) NOT NULL DEFAULT '0',
  `author-name` varchar(255) NOT NULL DEFAULT '',
  `author-link` varchar(255) NOT NULL DEFAULT '',
  `author-avatar` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL DEFAULT '',
  `body` mediumtext,
  `app` varchar(255) NOT NULL DEFAULT '',
  `verb` varchar(255) NOT NULL DEFAULT '',
  `object-type` varchar(255) NOT NULL DEFAULT '',
  `object` text,
  `target-type` varchar(255) NOT NULL DEFAULT '',
  `target` text,
  `postopts` text,
  `plink` varchar(255) NOT NULL DEFAULT '',
  `resource-id` varchar(255) NOT NULL DEFAULT '',
  `event-id` int(11) NOT NULL DEFAULT '0',
  `tag` mediumtext,
  `attach` mediumtext,
  `inform` mediumtext,
  `file` mediumtext,
  `location` varchar(255) NOT NULL DEFAULT '',
  `coord` varchar(255) NOT NULL DEFAULT '',
  `allow_cid` mediumtext,
  `allow_gid` mediumtext,
  `deny_cid` mediumtext,
  `deny_gid` mediumtext,
  `private` tinyint(1) NOT NULL DEFAULT '0',
  `pubmail` tinyint(1) NOT NULL DEFAULT '0',
  `moderated` tinyint(1) NOT NULL DEFAULT '0',
  `visible` tinyint(1) NOT NULL DEFAULT '0',
  `spam` tinyint(1) NOT NULL DEFAULT '0',
  `starred` tinyint(1) NOT NULL DEFAULT '0',
  `bookmark` tinyint(1) NOT NULL DEFAULT '0',
  `unseen` tinyint(1) NOT NULL DEFAULT '1',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `origin` tinyint(1) NOT NULL DEFAULT '0',
  `forum_mode` tinyint(1) NOT NULL DEFAULT '0',
  `last-child` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `mention` tinyint(1) NOT NULL DEFAULT '0',
  `network` varchar(32) NOT NULL DEFAULT '',
  `rendered-hash` varchar(32) NOT NULL DEFAULT '',
  `rendered-html` mediumtext,
  `global` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=8384 DEFAULT CHARSET=utf8;
```

**Comment by Hypolite** [comment]
If the automatic database structure didn't pick up those discrepancies, I'm afraid you'll have to manually update the faulty fields.

Please **backup your DB** and run the following query on a small table with at least a varchar field:

````sql
ALTER TABLE
    `table_name`
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;
````
If it's successful, you'll have to run it for all tables, the most important being `item`.

You may encounter errors such as `ERROR 1071 (42000) at line 2229: Specified key was too long; max key length is 767 bytes` for tables with an index on `varchar(255)` columns. In this case you'll have to reduce the size of the index or the size of the column.

I'm sorry you have to do this manually, we did what we could to make the transition seamless.

**Comment by Rudloff** [comment]
I ran this on every table and it seems to work now, thanks!
I didn't get any SQL error.
