### ISSUE TITLE
Web app manifest

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3317]
Hello,

It would be nice to have a web app manifest: https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
This would allow Friendica to be added to the Android homescreen as a standalone app.
(It already kind of works because of the `apple-mobile-web-app-capable` meta but a manifest would allow for a better integration.)

I can submit a PR about this if you're okay with it.

**Comment by Hypolite** [comment]
Yes please. I've been actively working to improve native iOS home screen integration, and Android support would be great as well.
