### ISSUE TITLE
Keyboard shortcut to  skip to the next post

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3327]
Hello,

Because post can be pretty long (and have a lot of comments), I find myself doing a lot of scrolling when I browser my network tab.
I think it would be useful to have a keyboard shortcut that scrolls the next post into view.
What do you think?

**Comment by Hypolite** [comment]
It's a good idea, please use the standard keyboard shortcuts for browsing items, `J` for next, `K` for previous.

We also already use a scrolling system for comments in the frio theme, you could use the same logic: https://github.com/friendica/friendica/blob/b5a42c5b31fae5315bacd37769eba20ab2345aaa/view/theme/frio/js/theme.js#L581

**Comment by Rudloff** [comment]
Do you think this should be implemented in the theme (so it can reuse the `scrollToItem()` function) or in the core?

**Comment by Hypolite** [comment]
The particularity of `scrollToItem()` is that it highlights the item that was scrolled to. This is good for first load scroll, but not for manual scroll.

Beyond that, it would be better if the feature was available in all themes, but you can always limit yourself to a single theme and let someone else pick up the slack to port the feature to other themes or make it standard.
