### ISSUE TITLE
Table deliverq missing

### ISSUE THREAD

**Issue by Alkarex** [friendica/friendica#3331]
Table `deliverq` is used (e.g. in https://github.com/friendica/friendica/blob/554704e6b9b046e4b71253b429a3e13ac1403e19/mod/admin.php#L477 ) but not defined in database.sql / dbstructure.php
Its creation appears in update.php but still using MYISAM https://github.com/friendica/friendica/blob/a410f86e9cc2faa1f84853604657d870a9ed10e5/update.php#L704-L709
That table was not created on my instance.

**Comment by Hypolite** [comment]
Nice find again! Thanks for the review!

**Comment by Hypolite** [comment]
However, this table is obsolete and its mentions should be removed from the system.

**Comment by annando** [comment]
Thanks for pointing us to this.

**Comment by Hypolite** [comment]
Closed via #3335
