### ISSUE TITLE
URL rewrite doesn´t work

### ISSUE THREAD

**Issue by BlackListMe** [friendica/friendica#3342]
Hi,

I´ve started my first friendica project and i´m stuck at installation. The last point  sohws "URL rewrite funktioniert" (URL rewrite works) with a red dot. Below is the hint: "Umschreiben der URLs in der .htaccess funktioniert nicht. Überprüfe die Konfiguration des Servers." (URL rewrite doesn´t work in .htaccess)

a2enmod rewrite says:
`Module rewrite already enabled`

.htaccess is configured with friendica defaults, except RewriteBase is set to a virtual documente root:
`RewriteBase /friendica/`

And this is the according apache config:

`````
<VirtualHost *:80>
        ServerName  tonstudio.filder.cloud

        DocumentRoot /var/www/html/friendica
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory /var/www/friendica>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride All
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>`


hostname is configured in /etc/hosts:

`127.0.0.1       localhost
127.0.1.1       tonstudio.filder.cloud`

I have no idea, what could cause this problem. Could you please help..

Thanks
Robin

**Comment by Hypolite** [comment]
Hi @BlackListMe, thanks for reporting your issue.

First of all, there's a mismatch between your `DocumentRoot` and the second `Directory` directive, but I'm not sure it would change anything.

Secondly, are you running your instances in a subfolder? It isn't recommended. It doesn't appear to have any other apps on your domain `tonstudio.filder.cloud` so you could move your friendica instance one folder up, remove `RewriteBase` and it should work.

**Comment by annando** [comment]
Concerning the installation in a subfolder: This will limit your ability to interact with other networks. GNU Social **could** work, Mastodon **might** and Diaspora and Hubzilla **won't** work at all with a Friendica installation in a subfolder.

Best is to use some subdomain for it.

**Comment by BlackListMe** [comment]
Ok, thanks for your answers.

I moved the friendica folder up to /var/www/friendica, changed the related pathes in apache config aand removed RewriteBase.

Now, the browser gives only an empty index :(

**Comment by BlackListMe** [comment]
.htaccess is gone. Try to install friendica from scratch...

**Comment by annando** [comment]
BTW: Especially if you are interested in the communication with Mastodon you should install the develop branch.

**Comment by Hypolite** [comment]
Beware when you copy files from folder to folders on *nix systems, `.htaccess` can be ignored as it uses the usual notation for hidden files. It is safer to move entire directories at once.

**Comment by annando** [comment]
This seems to be a local installation issue, so I'm closing it now.
