### ISSUE TITLE
Umlaut/UTF8 problem only in notifications

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3346]
A user on my server pointed out that cyrillic characters in notifications are displayed in a wrong way. I've checked my database. Everything looks fine there. But I found out that there is an issue not only with cyrillic characters but also with german umlauts and other utf8 characters. This happens only with notifications. I made some screenshots...

![umlaut-utf8-1](https://cloud.githubusercontent.com/assets/3656054/25074704/430e929a-2302-11e7-86d5-09bf4dab60aa.png)

![umlaut-utf8-2](https://cloud.githubusercontent.com/assets/3656054/25074706/49dee6b0-2302-11e7-9abf-15e52a241373.png)

Maybe this is an issue with my server but I couldn't find the source of the problem. Can someone else confirm this?

**Comment by Hypolite** [comment]
I can confirm this, it has been happening for a while, but not in the dropdown notifications, so I didn't report it. However, it's happening in the `/notifications/system` page I have to use on mobile that I started using more regularly recently.

It fails for Emojis too.
