### ISSUE TITLE
My feed is not updated on friendica

### ISSUE THREAD

**Issue by nytche** [friendica/friendica#3347]
Hello,
I am a little confused about that and I don't know if I should report here, but I don't know where.
I had once a personal server with my one Friendica pod, upgraded until 3.5, but now I want to use someone else pod. I tried friendica.eu importing manually my contacts, and snarl.de with automatic import. Since yesterday, I still don't see any post from my friends - they are all from Diaspora. Did I miss something in the parameters?

**Comment by Hypolite** [comment]
Do you know if either servers have enabled Diaspora support? It's built-in but it can be disabled.

**Comment by rabuzarus** [comment]
I thought `relocate` does only work with friendica contacts. But I'm not sure.

**Comment by annando** [comment]
The automatic relocation does only work for Friendica contacts, this is true. Diaspora contacts have to be added again by hand.

**Comment by nytche** [comment]
ok, will try again on snarl.de, I will let you know.

**Comment by nytche** [comment]
it works.
the issue was with friendica.eu
thx.
