### ISSUE TITLE
Open link to source in a new tab

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3359]
Hello,

I often forgot that the link to source is not opened in a new tab by default, so I have to go back in my browser history and I can't find the post I was reading (because I'm using infinite scrolling)...
Would you be OK to add `target=_blank` to these links?

**Comment by rabuzarus** [comment]
I wouldn't like to change it for frio. I know the situation is not ideal at the moment. I hope in the future friendica will also have something like `function is_matrix_url()` which would recognize if a link does belong to the friendica network. The idea is that `Friendica` links would open in the same tab and non `Friendica` links would open in a new tab. But at the moment we don't have the possibility to distinguish the links. I hope that @beardyunixer will something like this. 

To explain my decision:
One of my goals of `Frio` was the strengthen the feeling in `Friendica` of being one single network (like the big commercial ones). The other themes do open all external links (and also some internal links) always in a new tab. After 15min of clicking arround you end up with 15 new tabs which you have to close. This was really annoying (especially on mobile devices).
If the user want to open the source in a new tab he/she can use right click - open in new tab.

**Comment by Rudloff** [comment]
Another issue I have is that I use the web app in standalone mode (add to homescreen on Android) and when an external link opens in the same webview, it is hard to return to my instance because i don't have any browser GUI.

I understand your arguments but maybe this could be added as an option in the theme?

**Comment by rabuzarus** [comment]
I have nothing against options :-)

**Comment by Rudloff** [comment]
Great! I will try to submit a PR for this.

**Comment by rabuzarus** [comment]
Something does come to my mind regarding the android web app.
Is it possible to identify through js if friendica is used as web app or in a browser? In this case we could add `target=_blank` through js.

**Comment by Rudloff** [comment]
According to [this article](https://developers.google.com/web/updates/2015/10/display-mode) you can use something like this:
```js
if (window.matchMedia('(display-mode: standalone)').matches) {

}
```
