### ISSUE TITLE
Can't talk to a Mastodon instance where nobody follows me

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3360]
Hello,

This was originally reported here: https://social.rudloff.pro/display/de03dfa09758e9370d2c8a2547608943
I'm not sure if this is a Friendica or Mastodon bug.

I'm using Friendica 3.5.1-626-g6a7a459.
When I send a message to a Mastodon instance where nobody follows me, the message is never received. It seems that as soon as someone on the instance follows me, messages are received correctly.

Here are some logs for messages that were never received:
https://gist.github.com/Rudloff/a1bf6f2cf91c4d158777cdee10fb0798
https://gist.github.com/Rudloff/16c6721abd81a42d1bfde278d57c7f19

**Comment by annando** [comment]
It seems as if there are some Salmon problems with Mastodon.

**Comment by Rudloff** [comment]
My last pull seems to have made things worse for me (because of #3367?).
Now when I comment on a Mastodon post, my comment is not received (but initial post that are not comments work fine).
Here is an example: 
* https://social.rudloff.pro/display/de03dfa01358f9d093917c6104775747
* https://mamot.fr/@rudloff_test/589957

The first post was received fine by Mastodon but the comment ("Re-re") was not received.
This used to work before.

Here are the logs for this post: https://gist.github.com/Rudloff/37dd20eb67cd2a2bc06d812a71ee1d1c

**Comment by annando** [comment]
@Rudloff this can only be coincidence. The salmon isn't working at the moment, so only PuSH is used to deliver messages. And PuSH wasn't modified in the last days.

**Comment by Rudloff** [comment]
Indeed, I tried to go back to 6a7a459 and it still doesn't work. So it might be a change in Mastodon.

**Comment by annando** [comment]
Could you check again? I did some changes in the whole protocol stuff. I'm unsure if it helps - we will see.

**Comment by Rudloff** [comment]
I updated to b6945a4 and tried again.

I can still reproduce to two issues mentionned above:
* Messages sent to an instance where nobody follows me are never received.
* Replies to Mastodon posts are never received.

**Comment by annando** [comment]
Hmm, okay. I will check if salmon is working. 

BTW: Replies are working here without any problems. How have you tested the first post?

**Comment by Rudloff** [comment]
Sorry, I'm not sure what first post you're referring to ?

**Comment by annando** [comment]
I mean, how have you tested this:

> Messages sent to an instance where nobody follows me are never received.

**Comment by Rudloff** [comment]
I created an account on a random Mastodon instance with few users then sent a message to that account: https://social.rudloff.pro/display/de03dfa08259074004ad5d0665705650
It was never received by the Mastodon user.


But when I follow/defollow my acount from Mastodon, it then works correcly.
You can see this behavior here for example:
* https://social.rudloff.pro/display/de03dfa04858f74bfb33c01095387735
* https://toot.aquilenet.fr/users/rudloff_test/updates/2306

The first reply is not received (because there was no follow) but the next are received.
(This was when replies still worked correctly.)

**Comment by annando** [comment]
Okay. This looks like a good test. And it seems as if there are still Salmon issues.

**Comment by annando** [comment]
I just did a test: https://mastodon.social/@heluecht/4874165

The fish symbol at the end of the post means that the post was transmitted via Salmon. 

See the difference here: https://pirati.cc/conversation/314195#notice-411943

The small dot show that the post was transmitted via push. So Salmon should work now with Mastodon.

So we have to check the log files if the message was transmitted. When this was done as well, it could be a Mastodon issue.

**Comment by Hypolite** [comment]
What's the baby bottle for? 😄

**Comment by annando** [comment]
The fish is for the _Salmon_ protocol, the baby bottle shows the transport via  _feed_.

**Comment by annando** [comment]
I updated the issue I created at Mastodon for this: https://github.com/tootsuite/mastodon/issues/2196

Please also check your logfile for the text ":salmon.php:171:". You should have lines like these:
```
2017-05-02 12:26:40@wrk59087a870e0315.77060175	[NORMAL]:salmon.php:171:slapper	slapper for https://mastodon.social/api/salmon/xxx returned 201
```

**Comment by annando** [comment]
@Rudloff Is this still happening? I have the feeling that currently all platforms cooperate well. There are however Salmon issues with Pleroma, but this seems to be a Pleroma issue.

**Comment by Rudloff** [comment]
I didn't ran more tests but it feels like I don't have this issue anymore.

**Comment by annando** [comment]
So do you want to close this issue?

**Comment by Rudloff** [comment]
Yes I guess we can close it.
