### ISSUE TITLE
Buffer plugin: add url to origin post in the sent message

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3378]
When you publish on your own but spread the message across multiple external sites it is good to include a link back to the original post, this is known as the [POSSE](https://indieweb.org/POSSE) principle.

It would be nice if the Buffer plugin allowed doing that, maybe as a configuration setting.

I'm filing this here because the friendica-addon repository does not allow filing issues.

**Comment by Hypolite** [comment]
You posted in the right place!

**Comment by tobiasd** [comment]
The buffer addon was deprecated, hence closing this issue.
