### ISSUE TITLE
Network page aside: Clear "Network" selection when clicking on a forum

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3379]
It's been a few times where nothing appeared when I clicked on a forum in the network page aside. It turns out my previous Network filter on OStatus had been carried, which means it was looking for OStatus posts in the Friendica forum I was looking at.

In my opinion, this isn't a filter anyone would expect when clicking on a Friendica forum, and I propose the network filter to be cleared/ignored when looking at a Friendica forum list of posts.

**Comment by annando** [comment]
It would be great if someone™ could define, which filters should be combinable and which ones not.

**Comment by Hypolite** [comment]
I opened this issue out of frustration but I can definitely look into that. In my opinion the network filter should come after any other, to refine any other chosen filter, which means any other filter should reset it.

**Comment by MrPetovan** [comment]
I've now been in the awkward situation of wondering if my node was broken because I could only see the Friendica posts in my network for 24 hours until I realized I had the network filter set.

I'm inching towards nixing the session feature for network filter because there's no obvious indication it's turned on when I open my feed on my phone or even just on a different computer.

**Comment by annando** [comment]
Concerning the starting post: We now clear the filters when a forum is selected.

To the other issue: You would like to have different session settings? So some session settings should expire after some time, others not?

**Comment by MrPetovan** [comment]
For me, either the filtered networks are displayed prominently at the top of the network page, or the network filter setting doesn’t persist in session at all.
