### ISSUE TITLE
Lost slash in openid URL... 

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3383]
I tried registering on meld.de with my OpenID URI: `strk.kbt.io` - I was successfully redirected and verified as being the owner of that url and then brought back to the registration page with my nickname and email filled in correctly.

BUT the pre-filled OpenID field had a missing slash: `https:/strk.kbt.io/openid/` !

Same happens if I initially type the full canonical openid address `https://strk.kbt.io/openid/'.

I'm sure my OpenID server reports the canonical URI correctly and the return URL confirms it as on the friendica site it looks like this:

```
/register&email=strk@kbt.io&nickname=strk&openid_url=https://strk.kbt.io/openid/
```

So it is some code in `/register` that drops that slash.

**Comment by strk** [comment]
Tried on my system and I confirm the problem persists as of  27b3943cc7a79ad16be45276f4676de22fc38617

**Comment by strk** [comment]
This is what I get adding debug lines: `$_GET['openid_url']: https:/strk.kbt.io/openid/`
And I confirm the QUERY string contains `&openid_url=https://strk.kbt.io/openid/`
How can that happen ?

**Comment by strk** [comment]
URL-encoding those slashes works: `%2F` instead of `/` - now to figure who makes up that URL...

**Comment by Hypolite** [comment]
Directly calling `http://friendica.mrpetovan.com/register?email=strk@kbt.io&nickname=strk&openid_url=https://strk.kbt.io/openid/` yields the expected `$_GET['openid_url']` value with the double forward slash. Can you confirm the return URL?

**Comment by copiis** [comment]
I run 3.5.2 dev 1220

**Comment by strk** [comment]
The url generation seems to be here (or at least this code looks suspicious)
```
mod/openid.php:103:                     $args .= '&openid_url=' . notags(trim($authid));
```

**Comment by strk** [comment]
@Hypolite maybe it depends on the browser doing the urlencoding for you ? I'm using Firefox here.

**Comment by strk** [comment]
Found the issue, the return url is missing a `?` character, but directly starts with `&` instead !
Fixing that fixes the issue. Filing a PR next. Will also include urlencoding even if it was NOT the issue at hand.

**Comment by strk** [comment]
Please see #3384 for the fix
