### ISSUE TITLE
Contact Spam

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#3387]
It would be nice, to have the possibility to block some servers as protection from contact spam. Maybe as an feature in the admin panel

**Comment by Hypolite** [comment]
Thanks for submitting this feature request! Given the amount of requests we got about a server block feature, I'm sure this will be considered soon.

**Comment by Hypolite** [comment]
Pondering whether to implement a quick contact request block or a more thorough ban on all communications, thoughts?

**Comment by annando** [comment]
I would do the last one. And I suggest using the function that @tobiasd mentioned. This can then be implemented in the get_url and post_url functions.

**Comment by Hypolite** [comment]
What function exactly? I only saw you mentioning `z_fetch_url`, he mentioned the whitelist but it doesn't seem to be tight enough.

**Comment by annando** [comment]
There is the function ```allowed_url``` in ```network.php```. This currently only checks a whitelist, but could be extended to a blacklist. After this is done, this function can be added to ```z_fetch_url``` and ```post_url```. This would be a very low level block.

**Comment by Hypolite** [comment]
Thanks for laying on the work for me!

**Comment by Hypolite** [comment]
Pinging @pztrn, I know he was waiting for this feature. Please beware that it is untested. It doesn't make anything crash as far as I know, but I'm not sure about the coverage of the block.
