### ISSUE TITLE
Replace smilies by emoji

### ISSUE THREAD

**Issue by Shnoulle** [friendica/friendica#3391]
Since DB moved to utf8mb4 : we can use emoji and not smilies.

I think it can be great to use and send emoji directly, maybe must validate if other server accept emoji ?

1. gs is ok with emoji, seems mastodon too
2. I'm sure twitter and facebook too (hope ?)
3. diaspora ? Unsure
4. Other's ?

Maybe only by plugin/extension and not then the default smilies by core ?

**Comment by annando** [comment]
I think we should use the emojis as some kind of "transport medium". We should have some (optional) converter at the sending and receiving part so that they could be replaced by images.

I think that most systems will support these things very well.

**Comment by Shnoulle** [comment]
Currently `<3` or `:-)` can be replaced by picture in Friendica but not in other fediverse part ❤️ or 😄 can easily replace it ;)

**Comment by Hypolite** [comment]
That's what @annando meant: we should replace emojis with images for Friendica users sho want it, however we should only communicate with emojis with remote servers. This means translating emojis to images in the bbcode process (easy, we already do that), but also making sure that we are keeping the emoji version to transmit toremote servers (not as easy).

**Comment by Shnoulle** [comment]
OK, it's not what i mean : i mean save `<3` by ❤️ if admin activate the option

Idea can be **always send emoji** + by option

1. Always use image and save shortcuts in DB (need a emoji to shortcuts from remote)
2. Use image for shortcuts , save shortcuts in DB but didn't replace remote emojis
3. Always use emoji (replace shortcuts by emoji when save in DB or in js before send POST)

**Comment by Hypolite** [comment]
And what would be the default option?

**Comment by annando** [comment]
@Shnoulle We now are having an addon that uses unicode emojis. Does this work for you?

**Comment by Shnoulle** [comment]
Yep, i close it :)
