### ISSUE TITLE
Mastodon: Shared "Via" posts should be timed according to sharer, not shared

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3394]
I just switched from "Posted Order" to "Commented Order", and I discovered a bunch of recent boosted posts referring to hours-old original toots. It turns out the Friendica post end up being timed according to the original post, not of the boost time, which buries it in the timeline in "Posted Order", while making it pop up in "Commented Order" even though there's no comment or like.

Example of boosted toot 8 hours later: https://friendica.mrpetovan.com/display/52acf9cd5a65b0b0cd8140b1b1ce31c93e77be48

**Comment by tobiasd** [comment]
Can you rewrite the title in normal English without the slang?

**Comment by annando** [comment]
From my side this is an intended behavior. I think that it is important to see how old a reshared item really is.

**Comment by MrPetovan** [comment]
Duplicated by #3816, closed because of the richer discussion over there.
