### ISSUE TITLE
frio: Contact search box autofill doesn't give expected results

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3396]
There are a few problems with the autofill search box in the frio theme version of the contact list:
- The search seems to only be on a few select accounts. Looking for a specific account I know I have in my contacts doesn't always works.
- The few selected account list is always the same, even when a network filter is applied. As such, results show me twitter accounts even if the Friendica or OStatus network filter is activated.

The first issue doesn't happen when I manually click on the "Find" button because the enter key doesn't submit the search form as expected. The network filter is also reset when manually searching.

**Comment by rabuzarus** [comment]
Yes it is not the best.  The search starts after the input of two letters. I guess the search is limited to 1000 (or 100 - I don't know anymore. For more info I have to look into the code)  contacts. With every further letter it filters through a cached list so it doesn't need to much performance. 
If the instance doesn't use the internal search it become even worse because the global dir doesn't provide many search options

**Comment by lazy-sunshine** [comment]
I am fairly new to this open source contribution.Can I give it a try?

**Comment by annando** [comment]
@lazy-sunshine Help is always welcomed. When you want to create a pull request, just have a look at the way we are doing this at the moment. And please have a look at the way we are coding (PSR-2 with some exemptions).

But I guess this shouldn't be too hard, we don't bite.


Mostly.


:-)

**Comment by tobiasd** [comment]
On Wed, 09 Aug 2017 16:56:28 +0000 (UTC)
Kirti <notifications@github.com> wrote:

> I am fairly new to this open source contribution.Can I give it a try?

Sure, just do :-) And don't hesitate to ask questions if you encounter any problem!

**Comment by Hypolite** [comment]
@lazy-sunshine Yes please, you can reach out to any of us if you wonder where or how a thing is supposed to be.

**Comment by MrPetovan** [comment]
This is still ongoing, I'm planning to take a stab at it in the next week or so.
