### ISSUE TITLE
Frio : unable to remove contact from contacts page (js issue)

### ISSUE THREAD

**Issue by Shnoulle** [friendica/friendica#3406]
There are js issue on contact page, on firefox 53.0

**Reproductibility**

1. Got to contacts page
2. Try to directly remove a contact via 'delete contact'
3. Look at javascript console

`SyntaxError: missing ; before statement  contacts:1:79`

**Comment by Hypolite** [comment]
Good catch, thanks!

**Comment by Shnoulle** [comment]
Thanks to you :)
