### ISSUE TITLE
URLs to Friendica protocol documents don't work

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#3427]
[https://github.com/friendica/friendica/blob/master/doc/Protocol.md](https://github.com/friendica/friendica/blob/master/doc/Protocol.md)
## Friendicas DFRN Protocol

-  [Document with the DFRN specification](https://github.com/friendica/friendica/blob/master/doc/spec/dfrn2.pdf)

- [Schema of the contact request process](https://github.com/friendica/friendica/blob/master/doc/spec/dfrn2_contact_request.png)

- [Schema of the contact request confirmation](https://github.com/friendica/friendica/blob/master/doc/spec/dfrn2_contact_confirmation.png)

- [Description of the message flow](https://github.com/friendica/friendica/blob/master/doc/help/Message-Flow)

**Comment by tobiasd** [comment]
This is part of the documentation that is shiped to every Friendica instance (example.com/help) and there it is working as expected.

If you want to read them at github, take the files from the "spec" directory https://github.com/friendica/friendica/tree/master/spec

**Comment by urbalazs** [comment]
@tobiasd the reporter reacted with a thumbs up, so I guess this issue can be closed.
