### ISSUE TITLE
acl lookup for unknown contacts returns "nick+0"

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3428]
When typing an ```@``` followed by a nickname, a lookup is done. For known contacts it then returns something in the form of ```@nickname+id```. ```id``` is the contact id. The search also includes unknown contacts. For them the system returns a ```@nickname+0```. This is of course bad since this cannot be resolved to a handle.

This should be resolved to ```@nickname@server.tld```. But anyway I suggest to completely drop the ```@nickname+id``` format and to replace it with ```@nickname@server.tld``` even for known contacts.

**Comment by tobiasd** [comment]
The +id is handy for people with many accounts with the same nick on server you cannot all remember. Remembering a short number helps to mention the correct incarnation over the API ;-)

**Comment by annando** [comment]
I can't remember a id, but I can remember an address with a server name in it.

**Comment by tobiasd** [comment]
You are 84, but I tend to mistype the server names on the mobile, the ID is really handy there :-)

**Comment by annando** [comment]
I don't see a huge problem to keep interpreting this format. But the lookup shouldn't return it - and returning a zero id is surely a bug.

**Comment by tobiasd** [comment]
I see, then I misread your initial proposal for the solution.

**Comment by Hypolite** [comment]
The real issue is that when you edit a post with mentions, there's only `@nick` in the textarea.

**Comment by annando** [comment]
This is another thing.

**Comment by Hypolite** [comment]
Indeed, I just wanted to bump #2880
