### ISSUE TITLE
Registrierung (Selbstregistrierung) des ersten Benutzers funktioniert nicht

### ISSUE THREAD

**Issue by davidmoerike** [friendica/friendica#3435]
Registrierung des ersten Benutzers http://derpiratvomsee.net/register funktioniert nicht.

Wenn der erste Benutzer da ist und admin ist, kann ein weiterer Benutzer sich registrieren (Selbstregistrierung).

Auch die Registrierung weiterer Benutzer _durch den admin_ funktioniert.

**Comment by Hypolite** [comment]
Hi David, can you please use English to write your issue? Even though I'm starting to get the hang of it, I'm not fully fluent in German yet!

**Comment by tobiasd** [comment]
On Fri, 05 May 2017 22:06:45 -0700
Jan David Mörike <notifications@github.com> wrote:

> Registrierung des ersten Benutzers http://derpiratvomsee.net/register
> funktioniert nicht.

Under which conditions is the registration failing so we can reproduce this problem?

* Which operation system are you using, which version?
* Which PHP version?
* What kind of database are you using?
* Did you see any errors in the systems logs?

**Comment by davidmoerike** [comment]
On May 5 or 6 git pull executed. Develop branch.

Database deleted and created  (that is, database empty), and .htconfig.php deleted and empty .htconfig.php created, so installation goes from beginning.

Still creation of the first user does not work (the user with the admin email). After one-time call of create_user (through the poller, as I have told here), login is possible. And also the creation of new users works.
