### ISSUE TITLE
contacts Seite: die linke Seitenleiste erscheint nicht

### ISSUE THREAD

**Issue by davidmoerike** [friendica/friendica#3436]
contacts Seite: die linke Seitenleiste - die wo zum Beispiel die Auswahl der Netzwerke ist - erscheint nicht.

Vermutete Ursache: Upgrade auf Debian 9.0

Adresse: http://derpiratvomsee.net

**Comment by Hypolite** [comment]
Hi David, can you please use English to write your issue? Even though I'm starting to get the hang of it, I'm not fully fluent in German yet!

**Comment by tobiasd** [comment]
On Fri, 05 May 2017 22:08:16 -0700
Jan David Mörike <notifications@github.com> wrote:

> contacts Seite: die linke Seitenleiste - die wo zum Beispiel die
> Auswahl der Netzwerke ist - erscheint nicht.

* Which theme are you using?
* Do you have activated the network selection in the users configuration
* Are you using the develop branch or the master branch of Friendica

**Comment by davidmoerike** [comment]
Will make new test and then answer in English. David Moerike


Am 06.05.2017 um 07:22 schrieb Hypolite Petovan:

**Comment by davidmoerike** [comment]
Will make new test and then answer in English. David Moerike



Am 06.05.2017 um 08:05 schrieb Tobias Diekershoff:
> On Fri, 05 May 2017 22:08:16 -0700

**Comment by davidmoerike** [comment]
Seems sidebar appears now. Friend selection is there, network selection not. Second, third and fourth option activated; see screenshot.

![network-features](https://cloud.githubusercontent.com/assets/7329689/25791432/8db26faa-33c0-11e7-8259-433473c7a747.jpg)
