### ISSUE TITLE
temp path not honored in directory usable checks

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3452]
With #3451 the path for the temporary files is not honored.

In the settings I have defined the temp path to be `/tmp/social.diekershoff.de` which is filled with files. After above mentioned PR Friendica complains about `/tmp` not being write-able (which is wrong).

Situation is persistent using PHP5.6 and 7.0

**Comment by annando** [comment]
The PR https://github.com/friendica/friendica/pull/3451 can't cause this. It could - however - be an issue of PR https://github.com/friendica/friendica/pull/3423

**Comment by tobiasd** [comment]
b3faf3867d5895d716434b2b41647657425cd364 is the last commit working on my node, that is basically what I can tell you.

**Comment by annando** [comment]
I guess it was the change that @Hypolite did.

**Comment by Hypolite** [comment]
Can you please indicate where does the temp directory check fails?

**Comment by tobiasd** [comment]
Sure, here is what the error looks like in the servers error log (copied all lines over from the other issue in the correct order).

> FastCGI-stderr: PHP Fatal error: Uncaught exception 'Exception' with message 'Basepath isn't usable.' in /.../src/App.php:195
> FastCGI-stderr: Stack trace:
> FastCGI-stderr: #0 /.../index.php(22): Friendica\App->__construct('/...')
> FastCGI-stderr: #1 {main}
> FastCGI-stderr: thrown in /.../src/App.php on line 195

**Comment by annando** [comment]
What exactly is the log file telling about ```directory_usable``` shortly before this message?

**Comment by tobiasd** [comment]
It's from the servers error log - it is currently the only error logged there. Friendica logs have something about Mastodon pubsub_post arriving and fetching the related postings.

Current develop dies with

> FastCGI-stderr: PHP Fatal error:  require_once(): Failed opening required '/.../include/Probe.php' (include_path='/.../vendor/pear-pear.php.net/Console_Getopt:/.../vendor/pear-pear.php.net/Archive_Tar:/.../vendor/pear-pear.php.net/Structures_Graph:/.../vendor/pear-pear.php.net/XML_Util:/.../vendor/pear-pear.php.net/XML_Parser:/.../vendor/pear-pear.php.net/PEAR:/.../vendor/pear-pear.php.net/Text_Highlighter:.:/usr/share/php:/usr/share/pear') in /.../include/network.php on line 10

**Comment by tobiasd** [comment]
I've just tested again with the state of #5451 and the node just don't work. Nothing is logged :-/ neither in die Friendica logs nor in the servers logs. Just the Browser saying Error 500.

**Comment by annando** [comment]
There is no "require_once" for "Probe.php" in the current develop in line 10:
https://github.com/friendica/friendica/blob/develop/include/network.php#L10

But there is in the master:
https://github.com/friendica/friendica/blob/master/include/network.php#L10

This error sounds like you hadn't got all the new files.

**Comment by tobiasd** [comment]
So, git is failing?

**Comment by tobiasd** [comment]
No, it seems to be one of the addons. Switched them all off after freshly pulled repositories resulted in the same Error 500.

**Comment by annando** [comment]
Maybe you should clone it from a fresh source, just to be sure?

**Comment by tobiasd** [comment]
Reloading the addons and everything is nice. so closing this issue.
