### ISSUE TITLE
Remove default "http://" from "url" BBCode

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3480]
Right now, adding the `url` BBCode to a text field prepends anything selected (or not) with `http://`. I understand the intention but I think it is wrong for a few reasons:
* Not all user-supplied links are domain-only: Using a full URL or a link text will require the user (= me) to manually remove the offending prefix.
* Even if it was only domains, it would be bad practice to suggest HTTP over HTTPS
* It introduces a single exception to the BBCode function

I'm now unilaterally deciding to remove this unnerving non-feature after painstakingly creating [a list of just six links in a post](https://friendica.mrpetovan.com/display/735a202920592080fb3a3eb695061563).

**Comment by annando** [comment]
I guess this had been done by intention. However, I do understand your arguments. So I will accept the corresponding PR when no one disagrees.

**Comment by Hypolite** [comment]
I know about [Chesterton's Fence principle](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton.27s_fence) but any way I slice it, I can't find a reasonable current use for this. If it was checking if the selected text was a domain-only URL, I could have left it in place, but as it stands with systematic prefixing it's just too much friction for no discernible gain.
