### ISSUE TITLE
Error adding email contacts

### ISSUE THREAD

**Issue by plberd** [friendica/friendica#3501]
I've configured my imap account and tried to add a contanct with the following result:

2017-05-29 14:40:35@84vvt0tt8kctv4lp20cohbdas4  [DEBUG]:Probe.php:1319:mail     searching someone@some.where, 4 messages found.
2017-05-29 14:40:35@84vvt0tt8kctv4lp20cohbdas4  [DEBUG]:network.php:604:avatar_img      Avatar: someone@some.where https://myserver/images/person-175.jpg
2017-05-29 14:40:35@84vvt0tt8kctv4lp20cohbdas4  [DEBUG]:identity.php:53:profile_load    profile error: follow?url=mailto%3Asomeone%40rsome.where

And the send request page says the profile is not available and the button fails with a long message stating that it couldn't find a suitable protocol and that I should try adding mailto: to my contact's id (which I had done, and it seemed it had actually found it)

**Comment by annando** [comment]
Are these all entries with "84vvt0tt8kctv4lp20cohbdas4" in the logfile?

**Comment by plberd** [comment]
It seems so. But a I deleted the logfile today. I don't know what that means.
Every test I ran today is tagged like that, other unrelated lines are tagged differently. I tried with several mail addresses and my server has only one local user.

**Comment by annando** [comment]
Are you on the RC, Develop or Master?

**Comment by plberd** [comment]
I'm on develop.

**Comment by tobiasd** [comment]
Which PHP version? I have no problems with (following) email contacts on Jessie with PHP5.6

**Comment by plberd** [comment]
I run Xenial with PHP7.0. After some more testing I found that it works for some addresses, more precisely, it works for those I don't need "mailto:" to force the protocol.
Those that work, work either with or without "mailto:" (someone@orange.fr, someone@yahoo.com.ar)
Those that don't work, well... don't work, either with or without "mailto:". (someone@gmail.com, someone@myserver)

**Comment by annando** [comment]
Can someone reproduce the problem?

**Comment by tobiasd** [comment]
I just tested this and always got the error message popup, that the domain was blocked. For all email addresses I tested (`mailto:` prefixed) and I cannot find any of these domains treated special in the settings.

**Comment by annando** [comment]
This is solved by my PR. But funny enough the current problem hadn't been the reported one. This had been another problem - but since I was able to add a mail contact, I really can say that this is fixed.

**Comment by tobiasd** [comment]
True, but you asked and while testing that problem surfaced ;-)
