### ISSUE TITLE
Silent registration failure

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3506]
I've setup a friendica node again, from the develop branch @ 0cc15f5c3d80af9b334b14390f04bd9ba0548354

The installation procedure terminates with giving me the registration page, where I register.
Upon completing the registration (hitting `Register` button) I'm redirected to front-page, where I'm prompted to enter credentials. But at this point, the database has an empty `user` table, so no registration occurred.

The frustrating part is that there is no trace of error. User was not notified about a registration error, apache error log is empty, INSTALL.txt file doesn't mention any way to obtain friendica specific logs.

This ticket is to fix the `silent failure` (which I'm yet to find out the cause of).

\cc @fabrixxm

**Comment by strk** [comment]
Same behavior with 66c6c37921e123b4bfad0e13871bb0d7f0a1990b (3.5.2rc)

**Comment by strk** [comment]
Ok I found an interesting fact: cleaning the browser cookies for he new node (which replaces an old node on the same URL) makes the registration succeed:

   1. It takes much longer for the page to respond upon hitting `Register`
   2. I get a popup message mentioning `Registration successful`
   3. There is now a row in the `user` table

So this was about finding an existing cookie in the browser.

NOTE that the failure was also silent after enabling logs in `.htconfig.php`:
```
$a->config['system']['loglevel'] = 4;
$a->config['system']['logfile'] = "/tmp/friendica.log";
$a->config['system']['debugging'] = true;
```

**Comment by Hypolite** [comment]
Is it related to #3174 ?

**Comment by strk** [comment]
I don't know @Hypolite but the PR you mentioned there are both merged in the commits I reference, so maybe not ? Anyway this ticket is about failures being silent.

**Comment by Hypolite** [comment]
Gotcha, thanks for checking it out.

**Comment by nupplaphil** [comment]
I tried it 3-4 times at my local node with the same hostname (https://friendica.local), but I cannot simulate it :-/
- adding a empty db
- calling https://friendica.local
- installation (with Berlin and DE language)
- directly go to https://friendica.local/register
- register "Max Mustermann"
=> Checking the `user` table and the entry is there.

@strk Which browser did you use?

To be honest the question is, if the bug still exists, because we re-factored the whole installation process during the last two years.

**Comment by strk** [comment]
I'm not in a condition to work on trying this again, feel free to
close it. Thanks for trying it yourself!

PS: it was likely Firefox <someversion>

**Comment by MrPetovan** [comment]
Thanks for your reply!
