### ISSUE TITLE
unexpected 'if' (T_IF) in include/api.php on line 2293

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3507]
Going to `/settings` page right after initial successful login results in a blank page and this error logged by apache:
```
[Wed May 31 10:17:13.428815 2017] [:error] [pid 26320] [client xxx:45156] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in xxx/include/api.php on line 2293
[Wed May 31 10:17:18.428461 2017] [:error] [pid 26245] [client xxx:45157] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in xxx/include/api.php on line 2293
[Wed May 31 10:19:48.434173 2017] [:error] [pid 26641] [client xxx:52972] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in xxx/include/api.php on line 2293, referer: xxx/profile_photo/new
```

This is with 66c6c37921e123b4bfad0e13871bb0d7f0a1990b from the 3.5.2rc branch

**Comment by strk** [comment]
that line and the ones nearby all start with a `+` sign as if the came from a diff

`git blame` reports them coming from bbddea03 by @gerhard6380

**Comment by strk** [comment]
That commit should be fixed or reverted. Develop branch (0cc15f5c3d80af9b334b14390f04bd9ba0548354) is fine.

**Comment by annando** [comment]
The pull request https://github.com/friendica/friendica/pull/3508 is accepted.
