### ISSUE TITLE
Random profiles are not found by find tool

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3512]
The `Find People` column on the left of `/contacts` page has a `Random profile` link which opens random profiles taken by somewhere (global dir?). Searching the name of any of those random profiles though does not return any hit, which is confusing (the system cannot find the profile it sends me to ?)

This is with vier theme, 3.4.3-4309-g0cc15f5 (master branch)

**Comment by annando** [comment]
I guess this is related with having a not working directory address in the config. Can you confirm that?

**Comment by strk** [comment]
Testing now, the `Random Profile` always only returns my own profile (only profile on my node). That same profile is not found by `Find People`. I'm pretty sure when I initially filed this I was getting more profiles though, dunno what happened. In any case the global directory URL is http://dir.friendi.ca/ which is bogus.

**Comment by annando** [comment]
Please set it to http://dir.friendica.social/ and try again.

**Comment by strk** [comment]
Setting directory to http://dir.friendica.social/ makes it able to
find my local profile and profiles on other nodes.

Random profile still always returns my own profile though.

How about keeping this ticket open until an error is returned to user
about global directory being incorrectly set ?

**Comment by annando** [comment]
Please execute this query in the MySQL console:
```
SELECT COUNT(*) FROM `gcontact` WHERE `network` = 'dfrn' AND `last_contact` >= `last_failure` AND `updated` > UTC_TIMESTAMP - INTERVAL 1 MONTH;
```
Then tell the result.

**Comment by strk** [comment]
```
+----------+
| COUNT(*) |
+----------+
|        2 |
+----------+
1 row in set (0.01 sec)
```

**Comment by annando** [comment]
Okay. That means that your server does only know two different entries where it can chose from.

**Comment by annando** [comment]
@strk Does this answer satisfy you? Can we close this it?

**Comment by strk** [comment]
Fell free to close it
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
