### ISSUE TITLE
Use "lock table" to avoid SQL timing problems

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3515]
The code here sometimes creates SQL errors since the database entry was inserted by another process between the time of checking for its existence and storing it: https://github.com/friendica/friendica/blob/develop/include/items.php#L447-L467

This can be avoided with the use of locked tables.

We have to create a new function for dba.php for the locking and unlocking. Then we have to check our code for other places where this could help.

**Comment by Hypolite** [comment]
Can we close this issue?
