### ISSUE TITLE
New "lock" function to serialize some functionality

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3516]
There is is (unused) functionality that could be used to serialize some functionality that would interfere when being called at the same time. This could - for example - help in poller.php where the check for too much connections regularly quits more processes than needed because this check happened at the same time.

The functionality needs to be updated to avoid its problems from the past where locks stayed forever when there was a crash during a lock.

It could move into some new "Lock" class (@Hypolite: Which would be the right place?) and could then be used at alle the places where a regular "lock table" can't help.

**Comment by Hypolite** [comment]
I think `src/Util/Lock.php` would be suitable. It's a helper class that isn't really core to Friendica.

**Comment by Hypolite** [comment]
Is it a File lock or a Database lock?

**Comment by annando** [comment]
Neither the one nor the other ;-)

See here for the current code: https://github.com/friendica/friendica/blob/develop/include/lock.php

**Comment by Hypolite** [comment]
Ooooh, gotcha. I rest my case regarding naming.

**Comment by Hypolite** [comment]
Can we close this issue?
