### ISSUE TITLE
Age: 2017

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3529]
Just stumbled over this by playing with the Vagrant VM using Trusty.

If you edit a profile, but not enter a date of birth, "0001-01-01" is saved to the DB. But when you then look at the profile, the age is given as "2017".

**Comment by irhen** [comment]
Hello there!
I'd like to give it a try, but I have some questions first.
1. What age do you expect to see in this case? I've been staring at this issue, like, forever and still couldn't come up with any other possible answer.
2. I've never tried to contribute to anyone's project before and right now I'm a lil confused. Where do I find the exact part of the code that needs to be fixed? I've looked through some files in the repository, couldn't find anything related to this issue and got upset. :)

**Comment by tobiasd** [comment]
Hey @irhen thanks for looking into this!

Regarding your 1st question: As the user did not enter any date of birth to the profile, I would expect the profile showing no age at all. If the date of birth is different from "0001-01--01" I would expect the calculated age being shown.

For your 2nd question, everything that is shown in the Web UI in Friendica is a module, and all modules are located in the `mod` directory of the repository. The smarty3 templates for the way the data is shown are located in `view/templates` In this case I think it is the file `view/templates//profile_advanced.tpl` (line 23). that is used. And finally, as this deals with displayed information which have a descriptor ("Age") that can be translated, you can look at `util/messages.po` where the strings used as descriptor is marked for translation in the code.

I hope this helps you finding the correct place in the code to find a solution for the issue.

**Comment by irhen** [comment]
Thank you very much for your quick response!
I'd like to take on this issue, if you're okay with that. I expect to show somewhat working within a week or so, is it okay?

**Comment by tobiasd** [comment]
Sure and don't hesitate to ask further questions, either here or in the development [forum](https://helpers.pyxis.uberspace.de/profile/developers).

**Comment by tobiasd** [comment]
fixed in #3573 so closing this
