### ISSUE TITLE
replace_macros with frio theme

### ISSUE THREAD

**Issue by Oviked** [friendica/friendica#3531]
Hi,

when I try to load profile or network page with frio theme, I get this error : 
`replace_macros: Invalid compiled template for 'file:view/theme/frio/templates/profile_vcard.tpl'` or `replace_macros: Invalid compiled template for 'file:view/theme/frio/templates/comment_item.tpl'` or again `replace_macros: Invalid compiled template for 'file:view/theme/frio/templates/paginate.tpl'` in contact page.

admin page or settings page is working.

I'm on Friendica V3.5.2.

**Comment by annando** [comment]
You should have a folder ```view/smarty3/compiled``` on your system. Please remove all files in that directory.

**Comment by Oviked** [comment]
Yes. After deletion, It works ! 
Thanks a lot.
