### ISSUE TITLE
GS Likes on Community Page

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3536]
Likes from GNU social should not reach the community page of a node when it shows all public postings (e.g. on snarl)

**Comment by annando** [comment]
Does anyone disagree to close this issue now?

**Comment by tobiasd** [comment]
On Mon, 31 Jul 2017 23:21:30 -0700
Michael Vogel <notifications@github.com> wrote:

> Does anyone disagree to close this issue now?

No, if it is working now we can close it :-)
