### ISSUE TITLE
SysV semaphore is not currently acquired

### ISSUE THREAD

**Issue by Alkarex** [friendica/friendica#3553]
I get a bunch of warnings in my cron job:
```
PHP Warning:  sem_release(): SysV semaphore 140173393599224 (key 0x66010143) is not currently acquired in /home/alex/public_html/f.a80.fr/src/Util/Lock.php on line 160
```

https://github.com/friendica/friendica/blob/4515c36f69badb0b63a0f85666011c1369b98477/src/Util/Lock.php#L160

https://github.com/friendica/friendica/pull/3551

**Comment by tobiasd** [comment]
Same here (Jessie, PHP5.6)
