### ISSUE TITLE
Scroll to next/previous does not work anymore

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3583]
Hello,

It seems the functionality added by https://github.com/friendica/friendica/pull/3330 does not work anymore on 3.5.2 stable.
I had a quick look and I think it is because the `thread_level_1` class does not exist anymore.

**Comment by AlfredSK** [comment]
Works for me on develop. But I've discovered lately the XMPP addon breaks the scroll to next/previous.

**Comment by Rudloff** [comment]
I can't reproduce anymore on 3.5.4 so I'm closing.
