### ISSUE TITLE
User is not granted admin privileges despite adding the email in admin_email

### ISSUE THREAD

**Issue by anmol26s** [friendica/friendica#3589]
Hi
I added the email of the desired admin to $a->config['admin_email'] = 'admin@example.com'; in .htconfig.php but admin account is not granted with the admin privileges. I run a nginx server.

Can I grant the admin privileges from the database?

**Comment by annando** [comment]
Please double check if the given mail address in the .htconfig.php is the same like the one from your registered user.

**Comment by anmol26s** [comment]
I have double checked, the emails match but there is no admin panel in the account.

**Comment by tobiasd** [comment]
Do you want to have more then one admin? Just because you wrote "adding" in the title of the issue. Which version of Friendica are you using? Current stable release (3.5.2) or another version?

And to answer the other question, no there is no DB setting, just the entry in the `.htconfig.php` file.

**Comment by AlfredSK** [comment]
Hmm. I have two mail addresses configured for admin rights in .htconfig.php and it works for me. Both users have access to the admin panel. I'm on current develop.

**Comment by anmol26s** [comment]
@tobiasd @AlfredSK   I have tried with one and many emails, creating many accounts but neither works. I am using the latest [release (3.5.2)](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/app.src). I have updated the a package for [Yunohost](https://yunohost.org). I tried manually installing on the server but admin rights are still not granted to the mail reflecting in `$a->config['admin_email'] ='';`
Maybe  there is a problem in nginx configuration. If you have any idea please check [nginx.conf](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/nginx.conf) (If you are checking the nginx file please do check the statement for redirecting from http to https. The https should be forced,but its not happening and the site loads with http)
I have updated Hubzilla package too with the same configuration. But in it the user can be granted admin privileges  from the database.

**Comment by anmol26s** [comment]
Amazingly, if I go to mydomain.tld/admin with the admin account I can access all the admin options. But there is no admin panel option on the side bar drop down. 
Is that the default way to access the admin panel or there should be admin option in the side bar?

**Comment by tobiasd** [comment]
On Thu, 20 Jul 2017 05:14:43 +0000 (UTC)
anmol26s <notifications@github.com> wrote:

> Is that the default way to access the admin panel or there should be
> admin option in the side bar?

Which theme are you using?

**Comment by anmol26s** [comment]
In  admin -> themes only frio  is unchecked 

- [X] duepuntozero - (without version)
- [ ] frio - V.0.8
- [X] Quattro - 0.6
- [X] Smoothly - Version 2013-05-08 
- [X] Vier - 1.2

**Comment by tobiasd** [comment]
But which one is the user account in question using?

If you have not changed the default setting my guess is `vier` where @annando had hidden the link to the Admin Panel in the top nav bar behind the small icon aside of the search box.

**Comment by anmol26s** [comment]
I feel so stupid right now /o\ 
My apologies . I am use to Hubzilla's admin panel which is under drop down of the profile icon in the top nav bar.
Its there and working. Why it has no text? And icon somewhat looks like an advance search option.
Thanks

**Comment by tobiasd** [comment]
On Thu, 20 Jul 2017 07:10:40 +0000 (UTC)
anmol26s <notifications@github.com> wrote:

> I feel so stupid right now /o\ 
> My apologies . I am use to Hubzilla's admin panel which is under drop
> down of the profile icon in the top nav bar.

Don't! The other themes have it in a more obvious place in the drop down menu as well.

**Comment by tobiasd** [comment]
BTW are the packages for Yunohost working?

**Comment by anmol26s** [comment]
Yes the packages are working, [see here](https://forum.yunohost.org/t/social-decentralized-networks-hubzilla-and-friendica-apps-working-again/3166). I need to create the update, backup and restore script  for Friendica though.Some one need to run the hub for some time for complete test. Hubzilla is ready and I am using it personally. 
For the update script I would like to know which folders stores the users data so that it can be rsync with new sources on update?

**Comment by tobiasd** [comment]
You should only need to backup the database and the `.htconfig.php` file, the DB holds all the data and the file is for the config.

**Comment by annando** [comment]
@tobiasd blame me for making this so invisible in "Vier" ;-)

**Comment by anmol26s** [comment]
@tobiasd Of course the database and `.htconfig.php ` need to be backed up, but where is the users pictures stored? That is need to be backed up too otherwise after update users will not see there profile pictures.
@tobiasd A text field would be a good addition to it.

**Comment by annando** [comment]
@anmol26s everything is in the database - even the pictures.

**Comment by tobiasd** [comment]
> A text field would be a good addition to it.

What do you mean?

**Comment by anmol26s** [comment]
I mean there should be text for admin button in the default theme. 

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
