### ISSUE TITLE
nice looking link preview

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#3593]
Would be nice if Friendica would show a nice looking preview for links. Here are some examples:

GNU Social:

![gnusocial](https://user-images.githubusercontent.com/1589737/28469556-e4a0108c-6e36-11e7-90b9-b41a03a1c851.png)

Diaspora:

![diaspora](https://user-images.githubusercontent.com/1589737/28469603-06dff158-6e37-11e7-9201-44eacd9203ea.png)

And this is how it looks on Friendica:

![friendica](https://user-images.githubusercontent.com/1589737/28469572-f095ef56-6e36-11e7-809b-27901c00eda1.png)

**Comment by tobiasd** [comment]
How have you embedded the link? When I use the "Add a link" button in the editor, I get a nice preview. (the yellow background is because it is only a preview and the theme I'm using has them with a yellow background).

![bildschirmfoto vom 2017-07-21 17-49-11](https://user-images.githubusercontent.com/433490/28471444-69c8cdf2-6e3d-11e7-9f7a-548cdd0a661b.png)

**Comment by annando** [comment]
It looks this way:
![bildschirmfoto 2017-07-21 um 19 18 55](https://user-images.githubusercontent.com/844208/28474592-8e281732-6e49-11e7-9df2-0274b27c941e.png)

And has to be entered that way:
```
"Google is aggressively using its monopoly position in Internet services such as Google Mail, Google Calendar and YouTube to advertise Chrome."

Do we really want a WWW dominated by one big company? I hope we learned something from the past!

#Chrome #Firefox #Open #Web
[attachment type='link' url='https://andreasgal.com/2017/07/19/firefox-marketshare-revisited/' title='Firefox marketshare revisited' image='https://andreasgal.files.wordpress.com/2017/07/desktop_percentage.png']Why building a better browser doesn’t translate to a better marketshare I posted a couple weeks ago about Chrome effectively having won the browser wars. The market share observations in the blog p…[/attachment]
```
You don't have to enter the elements by hand, just use the function to insert a link from the editor. This will do the rest.

The advantage behind this is that especially with multiple links in a post you can select the single link that should be displayed this way.

**Comment by schiessle** [comment]
OK, thanks. I just copy&pasted the link directly in the input field. Maybe it would be a nice improvement to detect links and then add the additional code automatically? Now that I know it I can use the insert link function but I assume if I post a link vai Twidere then I have again the same problem, hence auto detection of links would be really nice.

**Comment by annando** [comment]
For the web interface I wouldn't like to change the behavior, since clicking this button is no problem. There I would like to delegate the decision to the user.

For the API - on the other hand - we could add some setting that allows that links are added under certain circumstances. Do you agree with this?

**Comment by schiessle** [comment]
Personally I would probably just implement it as default for all links. All other social networks I'm aware of do it this way and I never saw a user complaining about nice looking links. ;)

Bit if this is not a option for you I would be really happy to have it at least for the API as you described.

**Comment by annando** [comment]
There is a reason not to automatically automatically add the preview to a link. Like you have said in issue https://github.com/friendica/friendica/issues/3596 Friendica has an advanced way to post messages to networks like Twitter. We are shortening messages, leaving only the title or a fitting number of paragraphs when there is an "attachment" element in the post. Then we automatically assume that this link is the most important and that the text is an introduction to it.

When we don't find this "attachment" element, we automatically assume that this is a blog post where the whole text is important. Then we shorten the text as well, but the link directs to the Friendica post.

**Comment by schiessle** [comment]
@annando didn't know that but it sounds reasonable

**Comment by annando** [comment]
Bets - of course - would be that the user would chose the posting type. Means: Link, Photo, Album or blog post. The system could try to detect it and could suggest the best type - but the user could change the suggestion.

But this is front end stuff - and we really are short with front end developers.

**Comment by divnull** [comment]
The method using “[attachment type=link …” mentioned above seems like it includes the _entire_ text of the referenced page. I just “attached” a really long article, and had to delete my message because the resulting post went on for pages. Is there an option to only display a summary?

**Comment by MrPetovan** [comment]
You can edit the summary in the link preview feature by clicking on it in frio, or in the post body in vier.

**Comment by annando** [comment]
@divnull Page creators can define what should appear as preview text of their web pages. Normally this should only be a small part, but sometimes they include the whole text there.

**Comment by divnull** [comment]
@MrPetovan, editing the summary to control what is shown would be the behavior I'd expect, but the contents of the summary appear to be irrelevant. Regardless of what is typed there, the whole article gets posted. (Here is the article in this particular case: https://politi.co/2FDTUA2)

**Comment by divnull** [comment]
@annando From what you say, I assume Friendica is looking at a header in the page? Which one?

**Comment by annando** [comment]
There are several meta header we are looking at. See here for details: https://github.com/friendica/friendica/blob/develop/src/Util/ParseUrl.php

**Comment by MrPetovan** [comment]
This issue isn't relevant anymore, there are nice looking previews for link, both manual and automatic.
