### ISSUE TITLE
[website] http://friendi.ca/ use fonts from google

### ISSUE THREAD

**Issue by Shnoulle** [friendica/friendica#3599]
Some user (for example me), didn't like to be tracked. 

fonts from google is great, but google know you go to this website with this IP. And it's easy to include fonts in http://friendi.ca/ server directly :).

**Comment by tobiasd** [comment]
I think this is the wrong tracker for this issue. Pleas file one against the [friendica-wp-theme](fabrixxm/friendica-wp-theme) repository of @fabrixxm., hence I'm closing the issue here.

**Comment by fabrixxm** [comment]
anyway https://github.com/fabrixxm/friendica-wp-theme/releases/tag/v1.1.1

**Comment by Shnoulle** [comment]
@tobiasd Sorry 😊 😿 
@fabrixxm Thanks 😽 😍

**Comment by tobiasd** [comment]
@fabrixxm that looks kind of broken for me (the drop down menu) or do I have caching issues?

**Comment by fabrixxm** [comment]
@tobiasd I'll check...

**Comment by fabrixxm** [comment]
Looks like wp changed html markup for menus. I have updated the css. Version 1.1.2 :-)

**Comment by tobiasd** [comment]
Guess @annando has to have a look, as I cannot delete the current Friendica theme any longer after choosing another theme for temporal usage as before.

The error reads

> Deletion failed: The requested theme does not exist.

and one explanation I've found, was that the theme directory name must not contain any spaces? But as that solution is 9 month old and it worked till yesterdays update of WP... I guess it's a different but similar problem.

**Comment by annando** [comment]
WP is so totally out of my mental scope, which means that I have to search for this issue in the web as well. But currently I'm still at the probing issue, followed by one issue with the buffer addon and some personal stuff which also consumes much time.

**Comment by tobiasd** [comment]
> WP is so totally out of my mental scope, which means that I have to
> search for this issue in the web as well. But currently I'm still at

I think, you just have to manually delete the Friendica theme directory and then upload the latest zip of the theme again and activate. it.
