### ISSUE TITLE
Cross-posting not working with Remote Profiles

### ISSUE THREAD

**Issue by Megver83** [friendica/friendica#3611]
Hi, I've 2 different accounts in 2 different public nodes. Both are connected to D*, Pump and GNUSocial.
In both accounts I follow RSS feeds, and enabled Remote Profile so that the feeds look like my posts. The only issue here is that when there are new feeds, although they look like my posts they do not appear in the other social networks.

IDK if this is a bug, but if Friendica is like that (in the case it's a feature, not a bug), please consider adding the option, at least as optional.

**Comment by annando** [comment]
This is a bug. Which branch are you using?

**Comment by annando** [comment]
Do you have an example of a post? (Best would be a link to it). Then we can check the most obvious things first.

**Comment by doweio** [comment]
I'm the sysadmin on one of these nodes (friendica.me) and have been discussing this with @Megver83 there too.  We are currently running 'Asparagus' 3.5.2 - 1227.  

I'm subscribed to this issue.  Just let me know if I can provide any more info. :)

**Comment by annando** [comment]
This could be either a bug or a result of some configuration. For example there could be some privacy setting in the profile or the server. Furthermore we have to check whether this occurs to any user or just this special one.

Currently there is another user that is reporting something that - at the first look - sounds like the same. But there is still much to check.

You could check the following:
- are there any PHP errors? (Hopefully you set up a php log file that contains the warnings. This has to be done in the php configuration file and you may see these messages in mails from your crontab).
- Are there entries with "dba.php" in the friendica log file?
- Which MySQL version are you using?

**Comment by annando** [comment]
@doweio I just discovered an ugly issue and I'm not sure if that could be even a problem at your system. Please check if PDO is installed and activated for PHP. If not, please install it. Then report again.

**Comment by doweio** [comment]
Yep, PDO is enabled:
`PDO

PDO support => enabled
PDO drivers => mysql

pdo_mysql

PDO Driver for MySQL => enabled
Client API version => 5.5.57

Directive => Local Value => Master Value
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock`

**Comment by annando** [comment]
@doweio Can you check for entries with ```dba.php``` in the friendica log file?

**Comment by doweio** [comment]
@annando - I have just switched on debugging to see what else I get, but so far I only have dba.php entries which were logged _before_ I enabled remote profiles.

`2017-04-15 10:51:00@msf103e1ljfvbuvcic3kqb6vk7	[NORMAL]:dba.php:147:q	DB Error (Disonnected) 2006: MySQL server has gone away
2017-04-15 10:51:00@msf103e1ljfvbuvcic3kqb6vk7	[NORMAL]:dba.php:179:q	dba: UPDATE 'session'`

This doesn't seem like the type of error you are looking for, I'm guessing.  I will monitor the log file and report back. @Megver83 - please feel free to retry using your remote profile(s).

**Comment by annando** [comment]
@doweio It would be good to have a link to such a post that is present on your server but wasn't transmitted.

**Comment by doweio** [comment]
@Megver83 - Can you supply a link please?

**Comment by doweio** [comment]
@annando - Does anything on [this page](https://friendica.me/profile/megver83?page=1) help?

**Comment by annando** [comment]
So this is only the title in the posts? @Megver83 can you change the contact settings to fetch further information for the feed. I guess that this is the problem.

**Comment by Megver83** [comment]
> So this is only the title in the posts? @Megver83 can you change the contact settings to fetch further information for the feed. I guess that this is the problem.

How do I do that, exactly?

**Comment by annando** [comment]
You go to ```/contacts```, there you select the contact and select "show contact" (or something similar - depending on theme and language). Your url in the browser should now look like similar to this: ```/contacts/5755``` (The number will be different)

On that page you have the contact settings and the options for "fetch further information".

BTW: Can you give me the exact feed url? Then I can do some tests on my own.

**Comment by Megver83** [comment]
I get feeds from many parts, mainly https://gitlab.com/Megver83.atom

**Comment by annando** [comment]
Have you changed the settings that I described above? If this is then working then I have a direction to look at.

**Comment by Megver83** [comment]
> Have you changed the settings that I described above? If this is then working then I have a direction to look at.

Yep

**Comment by annando** [comment]
Does "Yep" mean that it is working now?

**Comment by Megver83** [comment]
> Does "Yep" mean that it is working now?

I meant that I've changed the settings as you told me

**Comment by annando** [comment]
And does it work now?

**Comment by Megver83** [comment]
not really, feeds do not appear anywhere :S

**Comment by annando** [comment]
Have you made a test post on that account that appeared on the other networks?

When you write a post with that specific account, had you have a look at the permissions? Is it readable for everyone? Can you select and deselect the posting to pump.io?

BTW: I hope that you are the native connectivity to be reachable via GNU Social and Diaspora?

**Comment by Megver83** [comment]
I made a test post which appeared in other networks
https://friendica.me/display/78ea265d7859a328e69e6a1243238290
https://diasp.org/posts/7856392
https://datamost.com/Megver83/note/61olHk-tTAKA1y8Kx9euog

I had to manually put the option for everyone to be able to see it. However, all the feeds are public too
https://gitlab.com/Megver83/megver83.ga/commit/90103c0c27eb5527e79975997261a649a81e6ede

**Comment by annando** [comment]
So you had to change something at the permissions before doing that post? This irritates me. The "remote self" functionality is always using the default permissions. So if you have to change something when doing a manual post then the automatic ones will have the same problem as well.

**Comment by annando** [comment]
@Megver83 I discovered a possible reason why it wasn't working. Maybe your admin wants to switch to the develop branch where this will possibly be fixed, after the pull request https://github.com/friendica/friendica/pull/3683 was accepted or he waits for the release that should be done in the next few weeks.

**Comment by annando** [comment]
@Megver83 Another user tested it and it went well. On the "develop" branch everything is now working fine. @doweio

**Comment by Megver83** [comment]
OK, I'll notify here wether if it worked or not

**Comment by annando** [comment]
You are currently on the "master" branch. That means that you have to wait for the update.

**Comment by tobiasd** [comment]
So, we can close this issue?
