### ISSUE TITLE
friendi.ca HTTPS connection is untrusted

### ISSUE THREAD

**Issue by strk** [friendica/friendica#3621]
Firefox says: `Your connection is not secure`
Problem is wrong name is associated to certificate.
Please switch to letsencrypt to fix this problem.

\cc @fabrixxm @annando @rabuzarus

**Comment by tobiasd** [comment]
There is no HTTPS page. This is known and will be fixed eventually.

**Comment by annando** [comment]
The page https://friendi.ca now works, I'm closing this issue.
