### ISSUE TITLE
Can't connect to other user: Invalid profile URL.

### ISSUE THREAD

**Issue by maciekt** [friendica/friendica#3624]
I've set new instance of Friendica 3.5.2 on site http://dar.hostmc.pl/

There are to two users registered: maciek@dar.hostmc.pl and mrowkojad@dar.hostmc.pl. When I try to connect one of them to another red label "Invalid profile URL" appears.

How to solve this problem?

**Comment by annando** [comment]
Can you connect to accounts on other servers like for example the support forum at ```helpers@helpers.pyxis.uberspace.de```?

**Comment by tobiasd** [comment]
Please check your config. The `.well-known` path is not accessible from the web which is needed for finding other accounts.

**Comment by annando** [comment]
@maciekt it should look like this: https://squeet.me/.well-known/host-meta

Please check your web server setting. Which one are you using?

**Comment by maciekt** [comment]
> Can you connect to accounts on other servers like for example the support forum at helpers@helpers.pyxis.uberspace.de?

It gives message: "Requested profile is not available."

> Please check your config. The .well-known path is not accessible from the web which is needed for finding other accounts.

I don't have such folder ".well-known". Also in .htconfig.php it is not mentioned anywhere.

> Which one are you using?

Linux version 3.10.0-614.10.2.lve1.4.55.el7.x86_64 (mockbuild@build.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jun 20 08:59:12 EDT 2017

**Comment by tobiasd** [comment]
Which server are you using? Apache, nginx or something else?

The directory is "virtual" so to speak. The URL is managed by Friendica but at the moment it returns an error 404. The servers rewrite rules might not be working correctly.

**Comment by maciekt** [comment]
Apache/2

**Comment by maciekt** [comment]
> The servers rewrite rules might not be working correctly.

.htaccess:

`Options -Indexes
AddType application/x-java-archive .jar
AddType audio/ogg .oga
#AddHandler php53-cgi .php

<FilesMatch "\.(out|log)$">
  <IfModule authz_host_module> 
    #Apache 2.4
    Require all denied
  </IfModule>
  <IfModule !authz_host_module>
    #Apache 2.2
    Deny from all
  </IfModule>
</FilesMatch>

<IfModule mod_rewrite.c>
  RewriteEngine on
  # Protect repository directory from browsing
  RewriteRule "(^|/)\.git" - [F]

  # Rewrite current-style URLs of the form 'index.php?pagename=x'.
  # Also place auth information into REMOTE_USER for sites running
  # in CGI mode.

  # If you have troubles or use VirtualDocumentRoot
  # uncomment this and set it to the path where your friendica installation is
  # i.e.:
  # Friendica url: http://some.example.com
  # RewriteBase /
  # Friendica url: http://some.example.com/friendica
  # RewriteBase /friendica/
  #
  #RewriteBase /

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

</IfModule>

**Comment by maciekt** [comment]
No ideas? :(

**Comment by annando** [comment]
Could you check your apache logfiles? This seems to be some administration problem and not really a Friendica thing.

Problem is that your rewrite doesn't work like expected. 

This one here:
http://dar.hostmc.pl/.well-known/host-meta

should be converted to this here:
http://dar.hostmc.pl/?pagename=.well-known/host-meta

You could try the ```RewriteBase /``` like it is described in the .htaccess file.

**Comment by maciekt** [comment]
Tech support answered, that .well-known directory is used as global alias for DirectAdmin software and can't be redirected by .htaccess.

I modified network.php file and in function z_fetch_url() I added:

if(preg_match("/\.well-known\/host-meta/", $url)) $url = "http://dar.hostmc.pl/index.php?pagename=.well-known/host-meta/";

After this change I can connect to people registered on my server, but foreign addresses (like helpers@helpers.pyxis.uberspace.de) give message "The profile address specified does not provide adequate information. No compatible communication protocols or feeds were discovered. Unable to match @-style Identity Address with a known protocol or email contact. Use mailto: in front of address to force email check."

**Comment by annando** [comment]
The answer from your tech support is bad :-( Problem is that **any** remote system needs access to that folder.

I guess this is something that needs to be checked directly with the creators of "DirectAdmin". I cannot believe that there is no solution.

BTW: The change that you did has some side effects ;-) One you have already experienced :grinning:

**Comment by annando** [comment]
I created a post at their forum: https://forum.directadmin.com/showthread.php?t=55213

We could do one more check. Please enable the debug log level. Then access ```http://dar.hostmc.pl/.well-known/host-meta``` on your system. After this, you should have an entry in the logfile with "index.php: page not found:". Please check for this entry and post it here.

Maybe we can code some workaround.

**Comment by annando** [comment]
There is already an answer in the forum: https://forum.directadmin.com/showthread.php?t=55213&p=282970#post282970

Please forward this to your administrator and report again.

**Comment by maciekt** [comment]
Problem has been solved by server's administrator. Thank you.
