### ISSUE TITLE
nginx: URL rewrite test failed while browsing test URL is successful

### ISSUE THREAD

**Issue by guyou** [friendica/friendica#3629]
Hi,

I'm trying to revive a Docker container for friendica: https://github.com/mkaag/docker-friendica. This container is based on Nginx. Currently, I have a functioning Friendica. But... I need to comment out some check in the install.php.

In the context of the `install.php`, the test for URL rewriting (`/install/testrewrite`) failed, while pointing directly my browser to this page return the expected "ok".

Looking at the logs, I found that error.log contains such errors:
```
2017/08/12 23:22:03 [error] 23#0: *17 open() "/usr/share/nginx/html/install/testrewrite" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /install/testrewrite HTTP/1.1", host: "localhost"
```

I suspect some rewriting rule is false because there is no reason to look under `/usr/share/nginx/html` while friendica is installed under `/opt/friendica`. Do you have any idea how to solve this?
The config is: https://github.com/mkaag/docker-friendica/blob/master/build/nginx.conf

PS: I'm not familiar with Nginx.

**Comment by astifter** [comment]
This is still the case, had the issue during several installs lately.

**Comment by MrPetovan** [comment]
None of us at Friendica are familiar with nginx that I know of, we need extra help.

**Comment by astifter** [comment]
Okay, I narrrowed it down to the install page fetching http://<url>/install/testrewrite. My server is configured to use https everywhere so it 301's to https://<url>/install/testrewrite. 
For some reason the Network::fetchUrl does not handle the redirect properly, it should but ....

**Comment by astifter** [comment]
Ah, does not work with snakeoil certificates. With self-signed certs the test works.

**Comment by MrPetovan** [comment]
Thanks for looking into it, is it a case of just updating the documentation or can we check for snakeoil certificate during install?

**Comment by astifter** [comment]
I think its best to hand over the Curl error to the user so he can deal with it. There can be so many things, we can't check for them all...
