### ISSUE TITLE
pumpio cron error

### ISSUE THREAD

**Issue by doweio** [friendica/friendica#3636]
I use the poller.php cron process and I'm getting a daily cron output message:

`PHP Warning:  Invalid argument supplied for foreach() in /home/friendica/public_html/addon/pumpio/pumpio.php on line 1410`

Looking at the code at 1410:
`foreach ($users->items AS $user)`
    `pumpio_get_contact($uid, $user);`

Not sure whether to mention this, but my posts aren't shared to the pump instance I'm connected to.  But my posts aren't shared to twitter either, so not sure if this has any bearing. (They are, at least, shared to GNUSocial)

Current version Friendica 'Asparagus' 3.5.2 - 1227

**Comment by annando** [comment]
The warning is not a big problem - it has nothing to do with your other problems.

**Comment by annando** [comment]
@doweio The pull request is accepted. Please update the addon repository and have a look if it happens again.

**Comment by annando** [comment]
@doweio Is it working now for you?

**Comment by annando** [comment]
I'm closing it now.
