### ISSUE TITLE
Make URL rewriting optional

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3637]
Currently relayd/httpd on BSD isn't supporting URL rewriting and it prevents it to run a Friendica instance. In my opinion, URL rewriting should be a "nice to have" rather than mandatory, especially since most our URLs aren't SEO-optimized human-readable slugs.

I suggest we introduce an configuration value to enable/disable URL rewriting. This means all the links that are generated/static have to be run through a filter function taking the config value into account.

It's an easy but long job, and it's a nice way for me to get back into Friendica development.

Thanks to silverwizard@friendica.obscuritus.ca for bringing this issue to me.

**Comment by annando** [comment]
When you do so, please change all links in a way that they are all relative. I think that links to the same domain shouldn't contain the domain name.

BTW: Welcome back!

**Comment by Hypolite** [comment]
It's a good idea, however links displayed in emails should include the domain name. And thanks!

P.S: I'll watch out for the webfinger output.

**Comment by annando** [comment]
I suggest links like https://server.tld/index.php/path/name - this should work on every system and is looking fine as well.

**Comment by Hypolite** [comment]
Do we already support this form or is it something that should be added?

**Comment by annando** [comment]
No, currently we don't support this - but we should.

**Comment by Hypolite** [comment]
I'm afraid it would fool basic web servers, so I'll just add it as a third option. Here are the options I'm thinking about:
1. Web server rewrite: https://server.tld/path/name
2. Friendica rewrite: https://server.tld/index.php/path/name
3. Vanilla URL : https://server.tld/index.php?pagename=/path/name

**Comment by annando** [comment]
The option in the middle is the one that Nextcloud is using as well. So I guess it should work on any significant server system.

**Comment by annando** [comment]
I just realized a possible showstopper: How do you want to realize the ".well-known" path?

**Comment by Hypolite** [comment]
Well, how is it realized today?

**Comment by tobiasd** [comment]
See `mod/_well_known.php`. Maybe one could keep a documentation file with the needed files and the information they should contain. So admins running BSD on their server can copy them to the appropriate places and put the correct URLs into them.

**Comment by MrPetovan** [comment]
I just realized that we don't use a centralized internal URL factory and that it is a prerequisite to making URL rewriting optional as well. This is far from being a Junior Job and with the `.well-known` abstraction I'm not even sure it's possible.
