### ISSUE TITLE
RFC 7033 WebFinger route returns XML/XRD instead of JSON/JRD

### ISSUE THREAD

**Issue by SuperTux88** [friendica/friendica#3661]
I'm currently finishing [RFC 7033 WebFinger](https://tools.ietf.org/html/rfc7033) support for diaspora (diaspora/diaspora#5963) and I saw, that friendica already supports the correct route (`/.well-known/webfinger`), but always returns XML instead of JSON, even when requesting JSON via `Accept` header.

```
curl -H "Accept: application/jrd+json" -v "https://pirati.ca/.well-known/webfinger?resource=acct:heluecht@pirati.ca"
```

According to the [spec](https://tools.ietf.org/html/rfc7033#section-4.2) you should always respond with JSON/JRD, unless something else is requested:

> A WebFinger resource MUST return a JRD as the representation for the resource if the client requests no other supported format explicitly via the HTTP "Accept" header.

Diaspora supports currently JRD (default) and XRD when you set the `Accept` header:

```
curl -v "https://nerdpol.ch/.well-known/webfinger?resource=acct:supertux@nerdpol.ch"
curl -H "Accept: application/xrd+xml" -v "https://nerdpol.ch/.well-known/webfinger?resource=acct:supertux@nerdpol.ch"
```

**Comment by tobiasd** [comment]
This was addressed in #3670 if I'm not mistaken, so 3.5.3 will have this included.

**Comment by annando** [comment]
@SuperTux88 When you think that Friendica is now doing it right, then please close the issue.

**Comment by SuperTux88** [comment]
Yes, everything seems to work, thanks for the fast fix! ❤️ 🍪

(the milestone here is set to 3.6, so is it in 3.5.3 or 3.6?)

**Comment by tobiasd** [comment]
On Thu, 31 Aug 2017 22:39:45 +0000 (UTC)
Benjamin Neff <notifications@github.com> wrote:

> (the milestone here is set to 3.6, so is it in 3.5.3 or 3.6?)

I think "It should be done by the end of the year (3.6), but it was done in late summer (3.5.3)"  :-)
