### ISSUE TITLE
Twitter posts with Flickr link dublicate images

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#3680]
Undesirable behaviour as discussed here: https://friendica.hubup.pro/display/174591b42159ad26547f7e9880359443

Such Twitter posts end up with duplicated images via pulling embedded picture from tweet and original Flickr URL.

**Comment by AndyHee** [comment]
This seems to be fixed now. 

There is no duplication of images any more in such posts.

**Comment by annando** [comment]
I haven't done anything. It's magic ...
