### ISSUE TITLE
General Content filter and display of GS Attachments

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3684]
When the general content filter addon is triggered (NSFW) on a posting from GS/Ma the attached images are shown although the posting itself is collapsed.

I would expect, that the attached nude pictures are not displayed when the content is filter by the user settings.

**Comment by annando** [comment]
This is complicated.

**Comment by tobiasd** [comment]
On Wed, 06 Sep 2017 01:05:50 -0700
Michael Vogel <notifications@github.com> wrote:

> This is complicated.

I understand, but if someone is nice enough to tag their pictures as NSFW and  the timeline is still filled with inappropriate images, then the filter is almost useless, I mean it still filters out most politics topics these days.

**Comment by annando** [comment]
Problem is that the adding of the picture is done at a completely different place - when the whole content processing already had taken place.

**Comment by tobiasd** [comment]
seems to work :-)
