### ISSUE TITLE
Change log date and time format to be ISO8601 compliant

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3685]
Some time ago I tried to configure fail2ban to catch failed login attempts and block the corresponding IP. Because our logfile is lacking a definition of the used timezone an ugly workaround was necessary to make fail2ban work with Friendica.

We're using UTC in our logfile and there should be a date/time format with timezone specification.

Current format:
2017-09-29 13:45:00

Proposed format:
2017-09-29T13:45:00+00:00
or
2017-09-29T13:45:00Z

With this change it would be possible for a third-party tool like fail2ban to detect the logtime correctly.

Thank you.

**Comment by AlfredSK** [comment]
Discussion on Friendica...

https://libranet.de/display/0b6b25a85959981abf47efb116424689

**Comment by AlfredSK** [comment]
Solved by #3687 

Tested with fail2ban. Works w/o any workaround now. :-)

Thank you! :+1:

**Comment by annando** [comment]
I guess we can close it, since https://github.com/friendica/friendica/pull/3687 does the job, right?
