### ISSUE TITLE
Password reset and initial email with password not working

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#3691]
The email with the initial password is not send to the new user, also the password reset function email won't send emails.

Friendica version: Developer 

Scenario 1: Created a new user in admin panel, new user did not receive a email with password.
Scenario 2: Password reset function does not send an email either.

Conclusion: There is currently no possibility to create/sign up new users.

**Comment by tobiasd** [comment]
This works for me now, @ben-utzer how is it on your node? can we close the issue?

**Comment by ben-utzer** [comment]
I'll check on the weekend and will close the issue if it works again.

**Comment by ben-utzer** [comment]
Works for me and others.
