### ISSUE TITLE
Why does OStatus/Salmon handler fetch original post with `.as` suffix?

### ISSUE THREAD

**Issue by snarfed** [friendica/friendica#3696]
hi all! first off, thanks for building friendica. i'm a big fan of your work!

i'm working on an ostatus/salmon implementation (https://fed.brid.gy/) and trying to get it to federate with friendica. it's currently sending salmon slaps, and friendica is verifying them ok, but it then tries to import it by fetching the original post URL with an `.as` suffix, which fails.

i haven't found this `.as` suffix flow anywhere in the ostatus, salmon, or related specs. any idea why you do it?

here's the current friendica code that does this:

https://github.com/friendica/friendica/blob/a6e1f9c89d2d5948980538f4ad6ecfd5b6a059cc/include/ostatus.php#L982

i did some spelunking, and it looks like it was originally added by @annando in #621 back in 2013:

https://github.com/friendica/friendica/commit/bc972e16ce513fd610615d190046cd43e01fb92d#diff-27eaffb04d4caed8cafc1e4bd184d956R40

here's an example salmon slap body i'm sending. for comparison, so far mastodon and hubzilla are receiving and ingesting it successfully, and i'm close with gnu social.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<entry xml:lang="en-US"
       xmlns="http://www.w3.org/2005/Atom"
       xmlns:activity="http://activitystrea.ms/spec/1.0/"
       xmlns:georss="http://www.georss.org/georss"
       xmlns:ostatus="http://ostatus.org/schema/1.0"
       xmlns:thr="http://purl.org/syndication/thread/1.0"
       xml:base="http://snarfed.org/reply6.html">
<author>
 <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
 <email>ryan@snarfed.org</email>
 <uri>ryan@snarfed.org</uri>
 <name>ryan</name>
</author>

<activity:object-type>http://activitystrea.ms/schema/1.0/comment</activity:object-type>
<id>http://snarfed.org/reply6.html</id>
<title>test reply via https://fed.brid.gy/</title>

<content type="xhtml">
<div xmlns="http://www.w3.org/1999/xhtml">
<a class="u-in-reply-to" href="http://localhost:2000/display/5d69984e2059b2c6c3208c8154392512"></a>
test reply via <a href="https://fed.brid.gy/">https://fed.brid.gy/</a>
</div>
</content>

<link rel="alternate" type="text/html" href="http://snarfed.org/reply6.html" />
<link rel="ostatus:conversation" href="http://snarfed.org/reply6.html" />

<activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
<published>2017-09-08T16:31:26+00:00</published>
<updated>2017-09-08T16:31:26+00:00</updated>
<thr:in-reply-to ref="urn:X-dfrn:localhost:2000:1:5d69984e2059b2c6c3208c8154392512" href="http://localhost:2000/display/5d69984e2059b2c6c3208c8154392512" type="text/html" />
</entry>
```
thanks in advance!

**Comment by annando** [comment]
Forget about the "as" stuff :-) This was done long time ago to be able to receive full threads although the system had received only some posts of the thread. Currently I'm developing a complete rewrite of that thread completion that not only works with GNU Social but also is fully compatible to systems like Pleroma and Mastodon as well.

This will hopefully be a big move ahead to a more compatible and more complete communication between these systems.

**Comment by snarfed** [comment]
hey, great news! thanks for the response. any idea on ETA? week, month, quarter out?

sounds like this will be a more compliant ostatus implementation, which is great. i know you're also aware of activitypub, which mastodon and hubzilla (among others) have mostly implemented already.

thanks again! exciting!

**Comment by annando** [comment]
It is currently running on my development system. In the next days I will look for any problems. it is already working well: https://github.com/annando/friendica/tree/new-ostatus

**Comment by snarfed** [comment]
awesome, thanks!

i tried it just now, and i got it all the way through the new ostatus code to return HTTP 200 to a salmon slap POST. it's not rendering the reply, though. when i load the original post in friendica (that the salmon slap replies to), it just shows that post itself, without the reply.

here are the friendica logs, with contents elided and dates removed for readability. friendica is serving on localhost:2000, external site is serving on localhost. original friendica post is http://localhost:2000/display/5d69984e2059b2c6c3208c8154392512 , reply is http://localhost/reply7.html , webfinger serves on http://localhost:8080/ (redirected through www.brid.gy) let me know if you want any more info, or if i should wait until later to test any more.

```
[DATA]:salmon.php:28:salmon_post	mod-salmon: new salmon <?xml version='1.0' encoding='UTF-8'?>

[NORMAL]:salmon.php:100:salmon_post	mod-salmon: Fetching key for ryan@localhost
[NORMAL]:salmon.php:10:get_salmon_key	Fetching salmon key for ryan@localhost
[DEBUG]:Probe.php:103:hostMeta	Probing for ryan@localhost
[DATA]:network.php:174:z_fetch_url	fetch_url https://ryan@localhost/.well-known/host-meta: 302 HTTP/1.1 302 Found

[DATA]:network.php:174:z_fetch_url	fetch_url http://www.brid.gy:8080/.well-known/host-meta: 200 HTTP/1.1 200 OK

[DEBUG]:Probe.php:157:hostMeta	Probing successful for ryan@localhost
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost:8080/.well-known/webfinger?resource=ryan%40localhost: 200 HTTP/1.1 200 OK

[NORMAL]:salmon.php:42:get_salmon_key	Key located: Array

[DEBUG]:salmon.php:114:salmon_post	mod-salmon: key details: Array

[NORMAL]:salmon.php:141:salmon_post	mod-salmon: Message verified with mode 1
[NORMAL]:salmon.php:161:salmon_post	mod-salmon: Author unknown to us.
[DEBUG]:ostatus.php:285:process	Import OStatus message
[DEBUG]:items.php:291:add_page_info_to_body	add_page_info_to_body: fetch page info for body 
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost/reply7.html: 200 HTTP/1.1 200 OK

[DEBUG]:ostatus.php:285:process	Import OStatus message
[TRACE]:session.php:37:ref_session_read	no data for session 635kdehpmv01nqit1ce7ka5qd1
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost:2000/display/5d69984e2059b2c6c3208c8154392512: 200 HTTP/1.1 200 OK

[TRACE]:session.php:37:ref_session_read	no data for session 0rl0l749vgj8og2lf8ntapr851
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost:2000/display/ryan/1.atom: 200 HTTP/1.1 200 OK

[DEBUG]:ostatus.php:838:fetchRelated	Fetched XML for URI urn:X-dfrn:localhost:2000:1:5d69984e2059b2c6c3208c8154392512
[DEBUG]:ostatus.php:285:process	Import OStatus message
[DATA]:Probe.php:1581:fixAvatar	Base: http://localhost:2000/profile/ryan - Avatar: http://localhost:2000/photo/profile/1.jpg - Fixed: http://localhost:2000/photo/profile/1.jpg
[DATA]:Probe.php:1581:fixAvatar	Base: http://localhost:2000/profile/ryan - Avatar: http://localhost:2000/photo/profile/1.jpg - Fixed: http://localhost:2000/photo/profile/1.jpg
[DEBUG]:items.php:291:add_page_info_to_body	add_page_info_to_body: fetch page info for body An original post.
[TRACE]:session.php:37:ref_session_read	no data for session fmtkfkks6bjj2edvddt9964ff3
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost:2000/display/ryan/1: 200 HTTP/1.1 200 OK

[TRACE]:session.php:37:ref_session_read	no data for session of26fa1j8n7sd9duhnlhfub496
[DATA]:network.php:174:z_fetch_url	fetch_url http://localhost:2000/display/ryan/1.atom: 200 HTTP/1.1 200 OK

[DEBUG]:ostatus.php:457:process	Item with uri urn:X-dfrn:localhost:2000:1:5d69984e2059b2c6c3208c8154392512 for user 1 already exists.
[NORMAL]:ostatus.php:460:process	Item was stored with return value 0
[NORMAL]:network.php:427:http_status_exit	http_status_exit 200
```

**Comment by annando** [comment]
it seems as if the post couldn't be stored because of this:
```
[DEBUG]:ostatus.php:457:process	Item with uri urn:X-dfrn:localhost:2000:1:5d69984e2059b2c6c3208c8154392512 for user 1 already exists.
```

**Comment by snarfed** [comment]
right! i figured as much. which confuses me because that's the original post that i created inside my local friendica instance. ie it already exists in the db, with that id, so it seems like friendica should understand that, and not try to store it again and fail.

**Comment by annando** [comment]
Have you tried it with the current RC branch again? It was improved very much.

**Comment by snarfed** [comment]
thanks for the nudge! i haven't tried it since we last talked two weeks ago. i'll try again!

**Comment by snarfed** [comment]
tried again, and i think i'm seeing basically the same error as last time, with slightly different messages:

```
[DEBUG]:ostatus.php:294:process	Import OStatus message
[DEBUG]:ostatus.php:403:process	Processing post with URI http://localhost/reply9.html for user 1.
[DEBUG]:items.php:291:add_page_info_to_body	add_page_info_to_body: fetch page info for body 
...
[DEBUG]:ostatus.php:646:processPost	Reply with URI http://localhost/reply9.html already existed for user 1.
[NORMAL]:ostatus.php:489:process	We couldn't lock - but tried to store the item anyway. Return value is 0
[DEBUG]:ostatus.php:496:process	Processing done for post with URI http://localhost/reply9.html for user 1.
2017-09-28T05:26:52Z@log59cc881b2472b2.56982443	[NORMAL]:network.php:427:http_status_exit	http_status_exit 200
```

full log attached.

[log.txt](https://github.com/friendica/friendica/files/1339620/log.txt)

**Comment by annando** [comment]
Please have a look in the logfile for all entries with "log59cc881b2472b2.56982443" in it. Before the "Return value is 0" there has to be some log entry from the item.php.

This "We couldn't lock" confuses me - but unrelated to this current case.

**Comment by snarfed** [comment]
sure! all of the log lines with that string are in the [full log](https://github.com/friendica/friendica/files/1339620/log.txt) linked above. here's the only line from `items.php`:

```
[DEBUG]:items.php:291:add_page_info_to_body	add_page_info_to_body: fetch page info for body 
```
