### ISSUE TITLE
frio: Move avatar to the left to create a more compact theme in normal browser

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#3711]
Feature request
I would love to move the avatar and some more infos to the left, to have a more compact theme. Because monitors have more width than height, small posts take too much space in height.

Maybe put the hash tags on the left too and make it just normal clickable text links, instead of ballon like text.

Maybe like this

![000_temp](https://user-images.githubusercontent.com/24474762/30524498-460b10ec-9bf5-11e7-8a49-2eec82912128.jpg)

**Comment by rabuzarus** [comment]
I am not convinced by this idea. Putting the the contact/post info to the left would create a left column with much empty space. So the body would be smaller and the content would stretch vertically. So there would be no benefits in space.
And giving the `wall-item-container` more horizontal space is not an option for me.

**Comment by hoergen** [comment]
ok. I changed to vier, that is looking more modern and, compact, like what I need on my wide screen.

**Comment by MrPetovan** [comment]
Closing as issue seems to have become invalid.
