### ISSUE TITLE
Personal notes don't work on current develop branch

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3801]
Personal notes (.../notes) don't work on current develop branch. Notes are posts with ACL automatically set as "visibile only to creator".
I just created a new note but it isn't displayed. I can see it on network page but nowhere else. Old notes are not visible too.

See discussion here:
https://forum.friendi.ca/display/0b6b25a81059e5fc8b36a28362609046

**Comment by tobiasd** [comment]
The problem was solved with #3802 so I'll close this issue.
