### ISSUE TITLE
Shared post date shouldn't use the original post date

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3816]
When one of my contacts retweets an older tweet, it doesn't show in the network page because the post date is set to the original tweet's posting date, which can be hours or even days in the past, burying the post in the feed.

I'd like the post date to be set to the retweet's date instead so it can accurately show up in the feed.

Edit (19/01/2018) : Applicable to Ostatus shares as well: #3394

**Comment by annando** [comment]
It's identical to issue https://github.com/friendica/friendica/issues/3394
I would like to show the original date of a reposted item. Question is how we can solve this.

**Comment by MrPetovan** [comment]
There's an obvious solution that involves having two different date fields, one for the display, and one for the ordering in the feed for those cases.

**Comment by annando** [comment]
This solution would mean just another datetime field - and we already are having so much of them by now:

* created
* edited
* commented
* received
* changed

I would like to only use the existing fields. Problem as well is, that we need an index for every field that we want to sort the items after.

**Comment by MrPetovan** [comment]
What's wrong with another field and another index? It isn't like the current database really is optimized for disk space, with all the items' contents duplicated for every single person who is supposed to receive it! 😅

Once we move the obvious duplicated fields out of the `item` table, I will be much more sympathetic to limiting the number of useful fields. 😉

**Comment by annando** [comment]
I'm currently planning to redesign the whole item handling. So I would like to keep the current item table static at the moment.

And: Adding new fields and indexes to the item table is a process that can last several hours on large servers. So I'm very cautious with every change to it.

Possibly we can use one of the other fields - but I would like to do this when I'm encapsulating the whole calls to the item table. Then I will know better what to do and to use.

**Comment by zeroadam** [comment]
Forgive my ignorance (not knowing the underlying code), but does this mean that a "retweet" is not in fact a new post (with a current datetime) from the contact who retweeted?

**Comment by MrPetovan** [comment]
It is, but we keep the original post's author and creation date.

**Comment by MrPetovan** [comment]
> I'm currently planning to redesign the whole item handling. So I would like to keep the current item table static at the moment.
Let me know if you need some help for the design, or even just to bounce off ideas. I have a lot of experience with relational database that I think can prove useful.

**Comment by annando** [comment]
Im currently planning a change in two steps:

1. I'm writing a class to act like an interface between the core and the database. Every read and write process to the item table (and the associated tables) will use this class.
2. After the abstraction is done, I will design new tables and table relations.

I need the first step to know for sure what is really needed (which data, how it is sorted and how it is fetched and queried). Then we can make a new design together that is planned for performance.

But at first I would like to have a hint how to name this interface class. Currently I thought using the namespace ```Friendica\Database``` and the class name ```Item```.

**Comment by zeroadam** [comment]
Well, I'm sure this.Context.DataRepository... isn't going to fit in the Friendica world! :-D

**Comment by annando** [comment]
@zeroadam you are speaking in riddles.

**Comment by zeroadam** [comment]
@annando Yes, sorry, that is roughly how database abstraction in .NET is (what we use at my workplace).

**Comment by MrPetovan** [comment]
Discussion about the Item abstraction class has been [moved to the Friendica Developers forum](https://friendica.mrpetovan.com/display/735a20297259e949a55a65f020568249).

**Comment by Guni86** [comment]
Hi Guys!  May I Contribute to your Projekt ? I am a Student and looking for my study for Open Source Projekt.

**Comment by annando** [comment]
@Guni86 of course. Just install Friendica on a server (develop-branch), then subscribe to the Developer forum developers@forum.friendi.ca. Then we can talk about everything.

**Comment by tobiasd** [comment]
> Hi Guys!  May I Contribute to your Projekt ? I am a Student and
> looking for my study for Open Source Projekt. 

Of course :-) Welcome! Feel free to ask questions, either on the issue you want to work on or in the developers forum @annando mentioned.

**Comment by Guni86** [comment]
Ooh, Thanks ! 
I did all Requiremnets for Insalling.

**Comment by Guni86** [comment]
I assume the Problem Retweet is not solved.  We (me and my Project partner) analyzed the Code and figured out some issue in the Include/api.php .

**Comment by MrPetovan** [comment]
Great, just submit a PR for us to review!

**Comment by Guni86** [comment]
Our Idea was submit on the Line 2813 Include/api.php additionally neu Time create code

**Comment by Guni86** [comment]
what's the difference between Line 4385 $reshared_item["created"] = $posted; AND  Line 2813 $retweeted_status['created_at'] = api_date($retweeted_item['created']); ?

**Comment by MrPetovan** [comment]
That's a very good question, I guess @annando would know.

**Comment by annando** [comment]
The functions are having different purposes. One formats the item entry, one is for the API data.

**Comment by MrPetovan** [comment]
Duplicate of #3394, kept open because of the discussion.

**Comment by MrPetovan** [comment]
A year and an Item refactoring later, any chance for a solution to this @annando ? Pushing to next release.

**Comment by annando** [comment]
With AP it is even more preferable to use the original date of the post, since reshared posts in AP are the original posts, they only get redistributed.

**Comment by MrPetovan** [comment]
Still not good for me. If one of the accoutns I follow shares a year-old post, I want to be able to see the post.

The worst part of this is that it will appear at the top of the page in the Ajax `update_network` call, but when I will refresh the `/network` page, the post will be gone, buried with other year-old posts.

**Comment by MrPetovan** [comment]
I did some digging on how AP does resharing, and it turns out reshares have their own URL and creation date, which would allow us to store it as a full-fledged item.

Announce object: https://mastodon.social/users/skynebula/statuses/101669568220219763/activity
Original post object: https://mamot.fr/users/Khrys/statuses/101669364234778328/activity

From there, we can create an item with:
- `uri`: Announce `id`
- `created`: Announce `posted`
- `owner`: Announce `actor`
- `author`: Object `actor`
- `body`: Object `content`

The downsides of this method would be the downsides of how we are doing reshares ourselves at the moment:
- Duplication of the original post.
- If the original post is deleted, reshares remain.

BUT, on the other hand, this means we could create "native reshares" without the `[share]` tag by creating the same kind of item described above and delivering them as `Announce`.

**Comment by MrPetovan** [comment]
Related to https://github.com/friendica/friendica/issues/838

**Comment by annando** [comment]
BTW: A Reshare would not alter the item creation date, but the "commented" date.

**Comment by MrPetovan** [comment]
This isn't an acceptable solution for me. It would accommodate people using the "Commented Order" stream but not the "Posted Order" people. And like [I said on the Friendica Developer forum](https://friendica.mrpetovan.com/display/735a2029-215c-7803-4cca-389298218207):
> We can have a system that accommodates people using the Posted Order and that shows the number of reshares which for me is a way lower priority than actually missing a post from my contacts.

**Comment by annando** [comment]
I would stick to the solution to handle a reshare like an activity that is added to an item. So many reshares could arrive at a single item. We do have several date fields. Which one should be changed upon receiving of the reshare message? And think about the case that reshare also arrives on items that you posted. This would be changed in the same way.

**Comment by MrPetovan** [comment]
I don't understand your concern, currently when Diaspora mutual contacts reshare my posts, I'm getting a copy for each reshare. This state would actually be an improvement for AP over the current where reshares from my AP contacts are completely lost because buried too far in the network stream.

**Comment by annando** [comment]
The Diaspora protocol handles reshares as separate (new) items - in difference to AP. In AP the reshares are more handled like comments.

**Comment by MrPetovan** [comment]
Maybe, but it still should show at the time it was reshared in the network stream and the contact status page.

**Comment by annando** [comment]
We could - indeed - consider changing this behaviour for Diaspora reshares.

**Comment by MrPetovan** [comment]
Do you mean bury them in the network stream like we do with AP announces? 🤔

**Comment by annando** [comment]
No.

**Comment by MrPetovan** [comment]
Ok, I wasn't sure.

**Comment by tobiasd** [comment]
What is the situation here with the new reshare method?

**Comment by annando** [comment]
We now are simply adding the "announce" message to an item. We don't change the "created" date of the original message. So a reshared item will still have the same "created" date like the original post. However, we are updating the "commented" date (I guess), liker we are doing with likes.

**Comment by tobiasd** [comment]
So, is this issue still an issue or obsolete due to the changes to the handling of reshares?

**Comment by annando** [comment]
This issue cannot be fulfilled the desired way.

**Comment by MrPetovan** [comment]
Boo 😢

**Comment by MrPetovan** [comment]
Perfectly solved by #7348
