### ISSUE TITLE
Install fails due to bug in pgettext 

### ISSUE THREAD

**Issue by dfsklar** [friendica/friendica#3828]
When installing on Mac OS X Sierra, with apache and php set up perfectly, the install produces a message (see below) that, although a warning only, causes the first install page to specify that mod_rewrite is not setup correctly and thus the user is not given the chance to proceed to the next install page.

The error is:
```
Invalid argument supplied for foreach() in ....include/pgettext.php on line 111
```

The reason is:  the database is not set up yet of course, so it is not sane for pgettext to be attempting to query the database to obtain translation information!  For some reason, q() returns TRUE instead of false, even though the query does fail (for obvious reasons: database part of the install sequence has not even been reached yet).  Thus, the foreach statement is executed even though clearly the query did not succeed.

**Comment by dfsklar** [comment]
This is FATAL.  This is priority HIGH.  Users who aren't creative enough to go in and fix the bug in pgettext are unable to proceed with installation.

**Comment by dfsklar** [comment]
I have a PR repairing this - watch for it!

**Comment by annando** [comment]
It's great that you are having a PR. I will wait for it.

**Comment by annando** [comment]
Please have a look at my pull request. This should handle the problem.

**Comment by dfsklar** [comment]
tested on a brand new node that had never had any friendica instance - very nice work!

**Comment by annando** [comment]
If you think that this fixed it, please close the issue. Just to explain: We are having two kind of database functions. There is the function ```q()``` that we used in the past. Now we are using the ```dba``` class functions that allow more abstract calls.

**Comment by smth** [comment]
Will the fix be included in a release any time soon? If not, what's the recommended action for new users? Fix it yourself / use previous release / use release candidate?

**Comment by annando** [comment]
This is part of 3.6

**Comment by smth** [comment]
Hi @annando Yeah, I assumed as much. My questions are when will 3.6 be released? Is it recommended to use 3.6 it in its current (RC) form?

**Comment by annando** [comment]
3.6 seems to be really stable. I hope that the release comes soon. We don't have a predefined date. Are you connected to the Developer Forum? I guess we will discuss about the release date there.

**Comment by tobiasd** [comment]
Please have a look at [Friendica 3.6-rc available](https://friendi.ca/2018/03/03/3-6-rc-available/) for some notes about the update process, if you are coming from the 3.5.4 stable version. There were some changes.

**Comment by smth** [comment]
Not seen the developer forum, not updating either. Potential new user, figuring out where to start. Sounds like 3.6-rc is the answer I was looking for. Thanks for the info.
