### ISSUE TITLE
Regular non-admin user is able to delete and edit posts made by others

### ISSUE THREAD

**Issue by dfsklar** [friendica/friendica#3834]
I as a regular non-admin user am able to delete and edit posts made by others.

It may be this is a bug only occurring amongst users who are members of a public forum.  I am creating this issue report as a placeholder to ensure it is must not be "lost" or ignored since it is a major security issue.  As I continue to research I will add information/clarification and repro instructions.

**Comment by AlfredSK** [comment]
Interesting. Can you describe this a little more, please? I tried to reproduce this with a regular user, a forum user and an admin user. I couldn't edit posts and comments made by other users. And yes, there is a 'delete' button/link. But as far as I know this only "deletes" the item from *my* stream.

**Comment by dfsklar** [comment]
Thanks for the clarification.  The delete button only deleted it from my stream.  
New users will definitely be confused by this.  It should be a "hide" button, not a "delete" button.  The issue is one of clarity-of-UX; this is not a security issue.

**Comment by AlfredSK** [comment]
Well, technically the item will be deleted from the database. :-) But maybe you're right. Could be confusing for new users.

**Comment by dfsklar** [comment]
Not sure what you mean by "...will be deleted from the database".  The post
was not actually deleted from the database.  It is still visible to other
users.  It truly seems to have been a "hide" operation, not a deletion.
Yet the confirmation message when I had tapped the trash icon was indeed
the very shocking "Delete this item?" query.  If that confirm message had
been "hide this from your view?", I would  not have been so shocked.

**Comment by AlfredSK** [comment]
Friendica stores every item for every user involved in the database. If there are, say, 5 users getting a post because they are receivers of that post, a copy of that item is stored in the database for every receiver. If one user is hitting the 'delete' button, the item related to that user is deleted from the database.
That being said, I have to admit I'm no developer. So, this represents my understanding of how the storage of items work. I could be wrong.

**Comment by dfsklar** [comment]
Very interesting!  I had no idea it was doing copies in that way.  Of
course, from the user's point of view, she is not deleting the post, she is
merely hiding it.  A user would never think she has the right to delete
another user's post!  So this remains a UX-clarification problem solved via
UX changes (prompt labeling, perhaps the icon itself, etc).

**Comment by tobiasd** [comment]
>  It should be a "hide" button, not a "delete" button.

But you do not hide the things you delete. You just delete them.

**Comment by tobiasd** [comment]
> merely hiding it.  A user would never think she has the right to
> delete another user's post!  So this remains a UX-clarification
> problem solved via

Why not? If I get an email from you, I have the right to delete it from my INBOX. The network stream is similar to my INBOX in the federated social networks. Why should there be anyone removing this right frim me?

**Comment by annando** [comment]
It is not that easy :-) It depends on where the comments belong to. Means: If you delete a comment from some other person that was done on one of your posts, then this comment will be deleted from the whole net. (When the network type supports this) 

This is done to be able to react to offending stuff.

Concerning this "hide" versus "delete" thing: It is more a "local delete" versus "global delete" thing. But you are right, that it could be nice to clarify it.

**Comment by MrPetovan** [comment]
I agree with the change from "Delete" to "Hide", and this issue should be renamed accordingly

**Comment by tobiasd** [comment]
> I agree with the change from "Delete" to "Hide", and this issue
> should be renamed accordingly

But does not "hide" imply that it can made unhidden? Or that it can be "found" again?

**Comment by MrPetovan** [comment]
Not necessarily. For example Twitter's UI allow to hide some elements without being able to find them later. However they give you time to reconsider by replacing the element by a box saying "The element has been hidden, Do you want to show it again?"

**Comment by dfsklar** [comment]
This is really about metaphors.  FB allows me to hide a user's post, but
not "delete" it because in FB-land, a post is something that exists in the
world and can only be retracted by its author.  You can hide it from your
timeline, or even unfollow its author... but there's no "delete" button on
other authors' posts in my feed.

It's like my trying to delete France; I should be allowed to say "I never
want to visit France" but I shouldn't be allowed to say "Please delete
France"!

So if the user comes you Friendica with an FB-like metaphor on their minds,
"delete" is a weird verb to see.   Whereas:  if the user comes to Friendica
thinking it's a mail app in a sense... then "delete" makes sense.  What's
weird, though, is that when they visit the original author's status panel,
it'll be clear that deletion was not what occurred.  The metaphor gets
muddy in that case...

But this is clearly a case of "you say poh-tay-toh ... I say poh-tah-toh" !


On Mon, Oct 30, 2017 at 11:24 AM, Hypolite Petovan <notifications@github.com

**Comment by annando** [comment]
On Diaspora the corresponding button is named "hide" - or "delete".

**Comment by Andi-K** [comment]
Maybe "remove" is a better term for local deleting?

**Comment by MrPetovan** [comment]
To me "remove" carries the same meaning as "delete".

**Comment by Andi-K** [comment]
Yeah, but it makes more sense to me than "hide". 
Like @tobiasd said, "hide" imply that it can made unhidden or that it can be "found" again. 

We can call it"remove (from your own view)" to distinguish it from delete (it global).

**Comment by MrPetovan** [comment]
I'm okay with this change if other people are also okay with it.

**Comment by tobiasd** [comment]
The mouse over text with the hint has been changed, so I'm closing this issue.

**Comment by rabuzarus** [comment]
New discussion about  UX problems of https://github.com/friendica/friendica/pull/5038 at https://forum.friendi.ca/display/4029d2ca335b0a738f93728251250257
