### ISSUE TITLE
Official support forum using a theme that is strangely DISABLED by default

### ISSUE THREAD

**Issue by dfsklar** [friendica/friendica#3839]
I love the theme that is being used by the official support forum:
 https://forum.friendi.ca/profile/helpers

But when I installed friendica latest commit of the "develop" branch (3.6-dev), and created an account, and tried all the themes displayed in the selection box, none matched the support forum's theme.

It would be nice to make that theme available since many of the users of the support forum are "new-to-friendica" folks like me who think of that forum as a "model"/"paradigm" and thus want to "match it" as much as possible.

**Comment by MrPetovan** [comment]
It just is frio with a custom color scheme (configurable in the theme settings).

**Comment by AlfredSK** [comment]
Yes, it's 'frio'. And thanks for the reminder. I'm very happy about the colors I picked for the developers forum. They're looking cool and they're matching GitHub's color scheme. I'm not so sure about that orangish color tone of the helpers forum. I think we need a poll. :)

**Comment by rabuzarus** [comment]
@AlfredSK 
I like the colors of the support forum. They are warm and friendly :-)

**Comment by annando** [comment]
@rabuzarus what about taking these colors for another color scheme?

**Comment by dfsklar** [comment]
OK here's the issue:  `frio` is not one of the themes that is shown when I visit "Settings"/"Display".  So this is not an officially distributed theme?  Why is it not shown in the pulldown list?
![screen shot 2017-10-30 at 7 02 11 pm](https://user-images.githubusercontent.com/1151882/32199850-df3cae44-bda4-11e7-9efb-1f52e2d9fcad.png)

**Comment by annando** [comment]
You have to enable "Frio" in the admin interface.

**Comment by rabuzarus** [comment]
@annando 
I rather would like to replace the standard (default) color scheme because the default colors were copied from HumHub (social network).
I don't want to have too much schemes where only two colors have been changed. This is something that users can do on their own. Schemes should be some kind of extension of CSS that could not be changed by the user settings. E.g. a real dark theme (with a dark background for `.tread-wrapper`). The `Red` scheme is only part of the code because I wanted some examples for future theme (scheme) developers.

**Comment by dfsklar** [comment]
@annando -- ok so you have to admit:  WHY oh WHY is "Frio" -- the most gorgeous theme provided as part of the default install -- by default DISABLED, whereas there are 3 or 4 themes that are enabled by default.  What could be the reason for having "frio" be disabled by default?

**Comment by dfsklar** [comment]
OK I had not even tried to enabled it, so had not seen the comment that states it is "not ready for prime time".  So I guess the only issue is: finishing it!  I will close this issue and please forgive me for not having pursued this further before complaining!

**Comment by tobiasd** [comment]
> frio ... by default DISABLED,

because nobody had thought about enabling it in `/view/templates/htconfig.tpl` since the time frio got more completed. Last time that template was updated, frio was still work in progress.

Just add it in line 39 and make a pull request ;-)
