### ISSUE TITLE
Some articles appear without images

### ISSUE THREAD

**Issue by hfroese** [friendica/friendica#3863]
Sometimes an article appears without image - but on Friendica only. Same article appears correctly in other networks.

**Friendica:**
![screenshot-2017-11-3 hfrc-federation network 1](https://user-images.githubusercontent.com/1968490/32379409-bf6d0058-c0ad-11e7-9cf8-e9b6f566f811.png)

**Diaspora:**
![screenshot-2017-11-3 joindiaspora](https://user-images.githubusercontent.com/1968490/32379415-c3494f42-c0ad-11e7-9e67-5db6bab057d3.png)

**Mastodon:**
![screenshot-2017-11-3 mastodon](https://user-images.githubusercontent.com/1968490/32379420-c641fde8-c0ad-11e7-9937-ca66dbde2fa6.png)

**Comment by hfroese** [comment]
Code to the article above:

`[quote]Ein Bücherregal passt locker in einen flachen Karton. Es ist beim Kauf in seine Einzelteile zerlegt. Daheim muss es zusammengebaut werden, was nicht jedermanns Sache ist. In naher Zukunft muss der Kunde nur noch eins tun: Den Karton entfernen. Dann baut sich das Regal langsam aber sicher allein auf.[/quote]
[attachment type='link' url='http://www.trendsderzukunft.de/formengedaechtnis-implantate-der-zukunft-passen-sich-perfekt-an-den-koerper-an/2017/11/03/' title='Formengedächtnis: Implantate der Zukunft passen sich perfekt an den Körper an' image='http://www.trendsderzukunft.de/wp-content/uploads/2017/11/Origami-620x372.jpg']Ein Bücherregal passt locker in einen flachen Karton. Es ist beim Kauf in seine Einzelteile zerlegt. Daheim muss es zusammengebaut werden, was nicht jedermanns[/attachment]
#Wissenschaft #Forschung #Medizin #Implantationen`

**Comment by annando** [comment]
Just to confuse you: It is loading here as well:
https://pirati.ca/display/535de4198859fc7ebf90af0214563424

**Comment by hfroese** [comment]
How does it come from and what's the difference of our nodes - except different Friendica versions?

**Comment by AlfredSK** [comment]
Even more confusion: https://libranet.de/display/535de4198859fc7ebf90af0214563424 ;-)

**Comment by annando** [comment]
It is some iframe that can't be loaded. You could deactivate this by putting this into the .htconfig.php:
 
```$a->config['system']['no_oembed_rich_content'] = true;```

**Comment by hfroese** [comment]
Works fine now - thx 👍
