### ISSUE TITLE
Request for theme frio: send button and format bar

### ISSUE THREAD

**Issue by hfroese** [friendica/friendica#3870]
Two featur requests:

- Cheking an article leads to _preview-conten_ but there's no send button.  If the post is ready to send, we have to switch back to _wrapper_ first. An adittional send buttton on preview content wil make handling easier.

- As available in comments, a format bar is desirable for new posts.

**Comment by rabuzarus** [comment]
should be fixed with https://github.com/friendica/friendica/pull/5777

**Comment by vinzv** [comment]
Works for me with `develop` so I guess this issue can be closed.

**Comment by MrPetovan** [comment]
Closed via #5777
