### ISSUE TITLE
Replace deprecated (P)Config functions with new syntax

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3873]
The functions ```get_config```, ```get_pconfig```, ```set_config```, ```set_pconfig``` and ```probe_url``` are deprecated and should be replaced with ```Config::get```, ```PConfig::get```, ```Config::set```, ```PConfig::get``` and ```Probe::uri```.

This has to be done in every file in the core and the add ons. And in every file where these lines had been changed, the corresponding ```use``` directives has to be used:

* ```use Friendica\Network\Probe;```
* ```use Friendica\Core\Config;```
* ```use Friendica\Core\PConfig;```

There is only one important thing: A ```probe_url($url, PROBE_DIASPORA);``` has to be replaced with ```Probe::uri($url, NETWORK_DIASPORA)```.

After these changes had been done, the old files and the corresponding includes can be removed.

**Comment by zeroadam** [comment]
PR for the addon side of things
https://github.com/friendica/friendica-addons/pull/439

will start in on the main over the next few days.

**Comment by MrPetovan** [comment]
The replacement list should include `del_config()` and `del_pconfig()` by `Config::delete()` and `PConfig::delete()` respectively.

**Comment by annando** [comment]
@MrPetovan Yeah, I forgot the other functions. I also never thought that this would be done so fast ;-)

So now we have two more files removed from ```include```.

**Comment by zeroadam** [comment]
OK, now that I fixed my bug and the develop branch is functioning fully, this issue should be good to go!

**Comment by MrPetovan** [comment]
Closing for now, if anything happens we can always reopen. Thanks for your help!
