### ISSUE TITLE
Twitter/Mastodon/GNU Social: Mention all profiles involved in replies.

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3884]
Currently, replying to a Twitter/Mastodon/GNU Social post only mention the author of the replied post. However, this doesn't match the default behavior of those platforms where replies mentions all the people involved in the thread by default. This is important since users of those platforms expect notifications from all replies in a thread, not just the one directly replying to them, exactly like Friendica's thread notifications.

This behavior should also be applied for shared post from those same platforms, where both the original author and the sharer should be mentioned in the reply to the sharing post. Ideally Friendica should allow this as well, but I expect it to be a little bit more complicated than just mentions.

**Comment by annando** [comment]
The mentioning in the text is just some "old style stuff". In fact the real mentioning is done via some protocol data. This already is mentioning very much persons (if I remember the code correctly). Additionally we are sending salmons to all these people.

So adding these people in the text could be done, but is like the icing of the cake.

**Comment by tobiasd** [comment]
Icing seems to be what many people like...

**Comment by annando** [comment]
I know. But we then should add them when the commenting begins, so that people could decide to leave them in or not.

**Comment by MrPetovan** [comment]
I understand, however I verified the expected behavior wasn't working with a Mastodon user and a Twitter user. In both cases they were able to read the reply to someone else in a thread they were involved, but they weren't notified they were mentioned.

> I know. But we then should add them when the commenting begins, so that people could decide to leave them in or not.

Yes!

**Comment by annando** [comment]
With Twitter this is something different. Let's see how to solve this.

**Comment by MrPetovan** [comment]
I believe adding the mentions in the comment box would be sufficient a solution for Twitter.

**Comment by PolynomialDivision** [comment]
This is the same reason why you can not answer to posts on Mastodon or?
So everything you write as a comment is interpreted by Mastodon as a new message or?

**Comment by MrPetovan** [comment]
I can reply to Mastodon posts, do you have a public example of the behavior you are describing? It would be a separate issue as this one.

**Comment by PolynomialDivision** [comment]
@MrPetovan 
Sry. This is mastodon behavior... If you are on your "home"-page it just displays eatch comment as new post...
I'm new to mastodon... ^^

Sry for unnecessary post.

**Comment by MrPetovan** [comment]
By the way, we also have this behavior at the moment in the "Status" page of a contact, posts and replies are mixed in the list.

**Comment by tobiasd** [comment]
Is this still an issue?

**Comment by annando** [comment]
Not sure. We did some stuff with the mentions.

**Comment by MrPetovan** [comment]
This seems to be working as expected now.
