### ISSUE TITLE
global community timeline disclaimer

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#3894]
If the community page is configured such that all public top-level postings arriving on the node are displayed (global community) there should be a disclaimer displayed at the top of the page, explaining that the content of the community page does not necessarily reflect the opinion of the nodes community.

**Comment by tobiasd** [comment]
I think I found the place to change, so I'll assign this to me.

**Comment by annando** [comment]
You know that this hasn't got any legal benefit?

**Comment by tobiasd** [comment]
Yes I know. But some people don't see a community strictly legally and need this header for a reminder that what they see on the page is the sum of all arriving public postings and not the stuff users of the node do post.

**Comment by tobiasd** [comment]
I can add an option for the admin to select if you like ;-)
