### ISSUE TITLE
Remove all "Go back to previous page" redirections after actions

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3897]
When submitting a new private message, the current action afterwards is redirect the user to the previous page they were on. No matter what page. If you have multiple Friendica tabs opened like I always have, it becomes a game of roulette, you never know where you're going to land on, place your bets!

Each "previous page" redirect should bring back where it makes sense instead, for exemple in the private conversation after submitting a new private message.

Occurences of `goaway($_SESSION['return_url']);` to be fixed:
- [x] Private messages (#5774)
- [x] Post edition (#5774)
- [x] Follow (#5800)
- [x] Unfollow (#5800)
- [x] Contact Batch Actions (#5800)
- [x] Cancel Contact Action (#5800)
- [x] Filer (#5861)
- [x] Drop Item (#5861)
- [x] Drop Items (#5861)
- [x] Repair OStatus (#5861)
- [x] OStatus Subscribe (#5861)
- [x] Event actions (#5861)

**Comment by annando** [comment]
I'm not sure if this is a junior job, but the change does make sense.

**Comment by MrPetovan** [comment]
There's no complicated protocol knowledge to know before hopping on this task, and it just requires you to generate some URLs, I think it is a junior job.

**Comment by JonnyTischbein** [comment]
Where are you sending the private message ?
In tab ````/message/new```` I have trouble to start a new conversation, no user is suggested and I receive ````No recipient selected.```` with ````@user@server.de```` and ````user@server.de````

To an existing conversation there is no redirect. I'm staying at  ````/message/new````.

When starting a message via ````/contacts```` (the envelope icon, and the popup) I get returned to the site and even if I go to an profile (including external server) I am redirected to ````/contacts````. I also have multiple friendica tabs open.

Is the problem still accrue (in 2018.08) ?

**Comment by MrPetovan** [comment]
Oh yeah, it still is a problem.

**Comment by JonnyTischbein** [comment]
How can I reproduce it?
Is it the message "popup" or the static site?
Only new conversations or replying to existing one too?

**Comment by MrPetovan** [comment]
If you have a private message notification, try opening it as well as other notifications in multiple tabs. If you answer to the private message, you will be redirected to one of the other notification items.

It isn't limited to private messages, editing posts works the same way as well.

Here are the actions that don't currently trigger a redirection in frio:
- Submitting a new item
- Deleting an item
- Liking/Commenting on an item

That's it.

**Comment by JonnyTischbein** [comment]
Now I get it. But only for editing my posts. 
Everytime I open a new private messages notification I am redirected to ````/message/[id]```` (no popup).

I'll give it a try

**Comment by annando** [comment]
BTW: Concerning these redirects, I would suggest to only use relative paths.

**Comment by JonnyTischbein** [comment]
Which page did you mean by follow / unfollow ?

I've tried `/contact/[id]` more specific `/unfollow?url=[URL]`. But I can't reproduce a wrong redirection. It seems that the GET param url provides the redirection url.

**Comment by MrPetovan** [comment]
- The `url` parameter of the `/unfollow` module is the URL of the remote profile.
- The cancel action indeed redirects to a session variable, which is wrong.

**Comment by MrPetovan** [comment]
If we have a contact ID, yes. If not, to `/contacts`.

**Comment by MrPetovan** [comment]
@JonnyTischbein Do you need help with the last items on the list?

**Comment by JonnyTischbein** [comment]
> Edit Post: /editpost/[item_id without a second URI string parameter

How else would you like to do it ? Possible return locations are:
- display post
- network
- community
- profile

**Comment by MrPetovan** [comment]
The single item display sounds the most relevant.

**Comment by JonnyTischbein** [comment]
> Drop Item: /item/drop/[item_id]
>-    Item not found

This would be an endless loop. Is it okay to return to `/item/` with the info message `Item not found` ?

**Comment by MrPetovan** [comment]
Why not redirect to `/network` with the notice?

**Comment by AlfredSK** [comment]
Yesterday I had an error with a redirection. I was redirected to a completely white page with an unknown and strange URL. Thing is I don't remember exactly what I did. I think it was related to a contact deletion or an unfollow. I don't know. :-) I will try to reproduce it.

**Comment by JonnyTischbein** [comment]
> - Filerm: /filerm but I don't know what it is for.

This would also be an endless loop. Would `/network` be here good ?

**Comment by MrPetovan** [comment]
The function is called automatically when you access `/filerm` on your Friendica node.

**Comment by JonnyTischbein** [comment]
Ahhh it is "called" from `/include/text.php`

     removeurl' => ((local_user() == $item['uid']) ? 'filerm/' . $item['id'] . '?f=&term=' . xmlify(file_tag_decode($mtch[1])) : ""),

Still not sure where to goaway to.

**Comment by MrPetovan** [comment]
The list is complete, closing, thanks for your work!
