### ISSUE TITLE
PHP fatal error - function attributes() in Diaspora.php

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3905]
Hello,
I get a lot of these PHP fatal errors lately. Is that related to the latest code reorganization?

`[15-Nov-2017 15:01:00 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /var/www/html/libranet/src/Protocol/Diaspora.php:262 
Stack trace: 
#0 /var/www/html/libranet/mod/receive.php(52): Friendica\Protocol\Diaspora::decode_raw(false, '<diaspora xmlns...') 
#1 /var/www/html/libranet/index.php(355): receive_post(Object(Friendica\App))
#2 {main}
  thrown in /var/www/html/libranet/src/Protocol/Diaspora.php on line 262`

**Comment by MrPetovan** [comment]
It doesn't look like anything we changed, it is related to XML traversing, and it all depends on the XML input of this function. Maybe the Diaspora protocol changed?

**Comment by AlfredSK** [comment]
Ah! Okay. I tried to find corresponding/related stuff with the same time-stamp in the friendica log. But no luck so far. Maybe an outdated Diaspora pod?
If I find nothing serious I will close this issue.

**Comment by MrPetovan** [comment]
I can exchange with Diaspora users today, so hopefully it is limited to a single server.

**Comment by AlfredSK** [comment]
Me too. Everything seems fine. Also, I'm only getting these PHP error messages on libranet.de but not on forum.friendi.ca (both running on the current develop code). 
> hopefully it is limited to a single server

I think you're right.

**Comment by MrPetovan** [comment]
There doesn't seem to be anything we can do, closing for now.
