### ISSUE TITLE
add categories as tags to re-posted RSS feeds

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#3911]
I subscribed to the RSS feed of my blog and automatically re-post it with friendica. I think it would be a nice addition if friendica would add the categories defined in the rss feed as tags at the bottom  of each post.

**Comment by annando** [comment]
In the contact settings is a configuration that is called "Fetch further information for feeds". This can be set to "Fetch information and keywords".

It is then looking that way: https://squeet.me/display/962c3e10e5db9e2aa6ea30fb5f0e7df16233d73f

This is ideal if your feed only provides a snippet of the original post. If your feed contains the full blog post, this is not so ideal.

**Comment by tobiasd** [comment]
Björns blog feed contains full articles. I know that you hate documentation, but maybe you could add a more elaborate information to the help text of that option?

**Comment by annando** [comment]
Remind me on the hackathon ;-)

**Comment by annando** [comment]
@schiessle can you test it? I added it on the hackathon.

**Comment by schiessle** [comment]
@annando awesome! 😃 

I just tried it by cherry-picking the commit from your pull request to the master branch. Created a test user, added my rss feed and set the contact setting "Fetch further information for feeds" to "fetch keywords" but the tags are not added. That's the feed I used for testing: https://www.schiessle.org/index.xml

**Comment by annando** [comment]
Now by looking at your feed I realised my mistake. The current solution adds the page keywords as tags, not the category in the feed. I will correct that.

**Comment by annando** [comment]
From my point of view this issue had been solved. So I will close it now.

**Comment by schiessle** [comment]
Thanks @annando! I will test it as soon as it is available in the master branch. In case I experience any issue (what I doubt) I will re-open this issue or create a new one.
