### ISSUE TITLE
Security: Use random_bytes for random string generation

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3946]
Since version 7, PHP provides a cryptographically secure random bytes generators with `random_bytes()`. It should replace the current homecooking we are doing in https://github.com/friendica/friendica/blob/develop/include/text.php#L51

Additionally, we can use the following polyfill for PHP < 7 and >= 5.4 : https://github.com/paragonie/random_compat

Related to #3942

**Comment by annando** [comment]
As long as this function can generate random strings of a given length, I totally support this.

**Comment by MrPetovan** [comment]
Sure it can, it’s its only parameter!

http://php.net/manual/en/function.random-bytes.php
