### ISSUE TITLE
changing the password not possible

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3999]
I think we introduced a bug in the auth system. There are two separate reports about it. It seems impossible to change a password at the moment. An error occurs that the password is incorrect.

**Comment by MrPetovan** [comment]
Do you know what error? Thanks for the report.

**Comment by AlfredSK** [comment]
Sorry. I was in a hurry. :-) Therefore the very short description. I'll later check this myself. For now here is a link to one of the discussions.

https://forum.friendi.ca/display/a8e4f565595a23a0d6475ca518787305

Maybe you can ask Richard to provide some information in English. He's an admin too.

**Comment by MrPetovan** [comment]
Thanks, I can reproduce the issue on my server, I'm on it.
