### ISSUE TITLE
Diaspora: Still receiving posts 12 hours after unfollowing

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4013]
Yesterday afternoon, I unfollowed a Diaspora two-way connection. The contact page accurately shows that only I am sharing with them, however I’m still receiving their posts in my network stream as of this morning.

**Comment by annando** [comment]
Posts or comments?

**Comment by MrPetovan** [comment]
Posts.

**Comment by MrPetovan** [comment]
Additional info: Only deleting the contact seem to stop the posts from coming, but I don’t think I’m still sharing with them anymore.

**Comment by MrPetovan** [comment]
And now another look at the contact page shows we are mutual friends without me doing anything.

**Comment by annando** [comment]
That's strange. This is one of these "can't happen" things.

**Comment by MrPetovan** [comment]
More info: I've unfollowed again the same account, verified an hour later that it stuck, and now I've received a new top-level post from them, and the sharing status has been reverted again.

**Comment by annando** [comment]
I cannot reproduce. I did both private and public posts with my Diaspora test account. 

I was bidirectionally connected: The post from Diaspora reached my Friendica account.
I was unidirectionally connected: The post from Diaspora hadn't reached my Friendica account.

You went to the contacts page and clicked on "Disconnect/Unfollow"?

Was it a public or private post? Was it from Diaspora or Hubzilla?

**Comment by MrPetovan** [comment]
> You went to the contacts page and clicked on "Disconnect/Unfollow"?

Yes, with multiple Diaspora contacts. I still receive their posts.

> Was it a public or private post? Was it from Diaspora or Hubzilla?

They are public Diaspora posts.

**Comment by annando** [comment]
AFAIK you are connected with my test account on pod.geraspora.de, aren't you?

You should have got a post now. Can you now unfollow this account and tell me?

**Comment by MrPetovan** [comment]
I've got no "Unfollow/Disconnect" button on your profile page!

**Comment by MrPetovan** [comment]
But I'm not sharing with you either.

**Comment by MrPetovan** [comment]
> Contact: Michael
 Actions
Status
Michael is sharing with you
Network type: diaspora

**Comment by zeroadam** [comment]
Not "mutual" friends it seems

**Comment by annando** [comment]
I hadn't followed you, I did this now. How is the connection status?

**Comment by MrPetovan** [comment]
> Contact: Michael
 Actions
Status
You are mutual friends with Michael
Network type: diaspora
Disconnect/Unfollow

**Comment by MrPetovan** [comment]
After receiving a post from you and unfollowing you,

> Contact: Michael
 Actions
Status
You are sharing with Michael
Network type: diaspora
Connect/Follow

**Comment by MrPetovan** [comment]
I received your new test post and we're back to
> Contact: Michael
 Actions
Status
You are mutual friends with Michael
Network type: diaspora
Disconnect/Unfollow

**Comment by MrPetovan** [comment]
The problem stemmed from the fact I set up my personal account as a "Free Love" account that transforms any follower request (one-directional) to my account into friend request (bi-directional). And we actually "fix" any lingering one-directional relation when we receive a public post from a contact that had been unfollowed for any reason.

Changing my account to "soapbox" (accepting following request automatically) will avoid this counter-intuitive issue.

**Comment by annando** [comment]
BTW: Do you think we can close this issue now?

**Comment by MrPetovan** [comment]
It's fixed for me, although I only had to change a setting while you removed a feature that was working, not just like I thought it would.
