### ISSUE TITLE
Update false evaluations to is_null in reference to P/Config::get

### ISSUE THREAD

**Issue by zeroadam** [friendica/friendica#4020]
Per @annando 
"In one of the last PRs I corrected a bug where we took a value that we fetched with the Config class and compared it via !== false - which now doesn't work anymore since the Config class would return a null.

Before making the release we have to check the system for all compares with === false or !== false if they compare with a value that was fetched via the Config class. Then we have to use is_null instead."

**Comment by zeroadam** [comment]
!== false found in 136 files
== false found in 138 files

**Comment by MrPetovan** [comment]
What about `=== false` ?

**Comment by zeroadam** [comment]
that's what I meant sorry.. ===

**Comment by MrPetovan** [comment]
Is it all done?

**Comment by annando** [comment]
If @zeroadam found all occurrences then yes.

**Comment by zeroadam** [comment]
From what I could tell, yes that was all of them. I ended up searching for all occurrences of both === false and !== false. I ignored the /vendor and /library folders.

I am checking addons now

**Comment by MrPetovan** [comment]
Let's wait to close this until the addons are covered then.

**Comment by annando** [comment]
Okay. Then I guess we will leave this open until you are done with checking.

BTW: Thanks!

**Comment by zeroadam** [comment]
Very welcome! Did find a few in addons and have submitted a PR

**Comment by zeroadam** [comment]
I believe this should be able to be closed now.
