### ISSUE TITLE
Delete unused files in /mod

### ISSUE THREAD

**Issue by annando** [friendica/friendica#4023]
See here: https://ethercalc.org/friendica_mod

It seems as if we can delete these files:
* cb.php
* mood.php
* navigation.php
* qsearch.php
* session.php

We should check this intensively before deletion.

**Comment by MrPetovan** [comment]
Can you please close this issue and stick to the original one here: #3995 ?

**Comment by annando** [comment]
Örgs ...

**Comment by MrPetovan** [comment]
I'm sorry what?

**Comment by annando** [comment]
It's just a German version of "oops"
