### ISSUE TITLE
Hooktube video URLs

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#4061]
Currently videos posted directly via hooktube URLs don't show up in posts.

[video]https://hooktube.com/watch?v=S6bOkFLrsAc [/video]

**Comment by annando** [comment]
In my test they were displayed as a link, but not embedded. Embedding depends upon the OEmbed support of the other page.

**Comment by tobiasd** [comment]
> In my test they were displayed as a link, but not embedded. Embedding
> depends upon the OEmbed support of the other page.

IIRC `[video]` is just a short form for `[youtube]` or `[vimeo]`

**Comment by annando** [comment]
It is the universal form.

**Comment by MrPetovan** [comment]
Hooktube has an embed mode with the following URL form: https://hooktube.com/embed/[Youtube video ID] like https://hooktube.com/embed/kRdO6jAd2E4

**Comment by AndyHee** [comment]
I suggest to put this issue on hold.

Discussion here https://f.belug.de/display/1860bc0e635a7b1662a0eef933929129 have revealed hooktube promotes controversial websites via a "Friends" link.

**Comment by AndyHee** [comment]
Promising alternatives seem to be available.

**Comment by MrPetovan** [comment]
Which ones?

**Comment by AndyHee** [comment]
Apparently there is http://tubeunblock.me/ There's also a decentralised peertube in the makings...
https://medium.com/we-distribute/peertube-decentralized-video-powered-by-activitypub-and-webtorrent-8aaa4c3749d7 
Rebeka mentioned something lie this.

**Comment by MrPetovan** [comment]
Embed code for PeerTube (no OEmbed):
````HTML
<iframe width="560" height="315" src="https://peertube.cpy.re/videos/embed/f78a97f8-a142-4ce1-a5bd-154bf9386504" frameborder="0" allowfullscreen></iframe>
````

TubeUnblock:
````HTML
<iframe width="560" height="315" src="//tubeunblock.com/embed?v=htWO0--MbQg" frameborder="0" allowfullscreen></iframe>
````
