### ISSUE TITLE
Implement networkpublic_timeline.json

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4071]
Hello,
Would it be possible to implement `api/statuses/networkpublic_timeline.json`?
It should return the latests posts from the federated timeline (ie. known posts from all the federated instances).

**Comment by MrPetovan** [comment]
Does it have to be this specific name? We generally use the word "community" for federated posts.

**Comment by MrPetovan** [comment]
What about `api/statuses/public_timeline.json`? Isn't it what you're expecting?

**Comment by Rudloff** [comment]
This specific API endpoint (`networkpublic_timeline`) is already implemented by Qvitter (https://github.com/hannesmannerheim/qvitter/issues/96) and called by Twidere (and possibly other clients).

AFAIK `public_timeline.json` only shows posts from users of my server whereas the new endpoint would display posts from other federated servers as well.
The federated timeline vs. local timeline concept has been popularized by Mastodon, you can read more about it [here](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/User-guide.md#the-public-timelines).

**Comment by annando** [comment]
Okay, sounds reasonable.

**Comment by Rudloff** [comment]
I didn't find any documentation for this. The [GNU Social source code](https://git.gnu.io/gnu/gnu-social/blob/master/lib/router.php#L337) only mentions that it is not part of the Twitter API.
But from what I understand, it should use the same parameters as [`statuses/public_timeline`](http://twitter-api.readthedocs.io/en/latest/timelines.html?highlight=public_timeline#get--api-statuses-public_timeline.json).
