### ISSUE TITLE
Adding contacts to contact groups not working

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4075]
On current develop I cannot add contacts to a contact group. Neither on the contact's page nor by managing the groups.
On the other hand _removing_ contacts from groups is working.

**Comment by tobiasd** [comment]
It seems to be working for me (both pages using dc7bff02359c0b2ab05488278ac78b8b0e014827). Using vier theme, should this matter.

**Comment by AlfredSK** [comment]
I'm using frio. Wait a minute. Will test with vier....

**Comment by AlfredSK** [comment]
Ah! The group editor works. But in single contact view (show contact) I can set or unset group memberships on the left side and it _looks like_ it doesn't work. Actually, the contact is added or removed from the group but the checkbox doesn't work like expected. After reload it always shows "disabled".
That happens with frio and vier.
