### ISSUE TITLE
Add a way to pin a post

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4077]
Hello,
Would it be possible to add a way to pin a post so it is always displayed at the top of a profile page?

(Twitter has a similar functionnality and uses the following POST API endpoint: `account/pin_tweet.json` and `account/unpin_tweet.json`.)

**Comment by annando** [comment]
Why not? I don't think that we will do this on a short term, but we can consider it while rewriting the item handling.

**Comment by annando** [comment]
I just stumbled upon this. I guess we can close it?

**Comment by MrPetovan** [comment]
Closed by #7823
