### ISSUE TITLE
max_id parameter is ignored in statuses/user_timeline.json

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4078]
According to [Twitter doc](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline), there is a `max_id` parameter that allows to return posts older than a specific ID.
It seems to be ignored by Friendica 3.5.4.

Both URLs return the exact same result:
* https://social.rudloff.pro/api/statuses/user_timeline.json?exclude_replies=false&count=20&include_blocked_by=true&include_rts=true&include_blocking=true&user_id=13
* https://social.rudloff.pro/api/statuses/user_timeline.json?exclude_replies=false&count=20&include_blocked_by=true&include_rts=true&include_blocking=true&user_id=13&max_id=186706

This parameter is used by Twidere when you scroll to the bottom of a timeline and it then tries to get more/older messages.

PS: Sorry for opening a lot of Twidere-related tickets. I've been using Twidere as my main client for some time and writing down missing things. This is the last one for now ;)

**Comment by MrPetovan** [comment]
> PS: Sorry for opening a lot of Twidere-related tickets. I've been using Twidere as my main client for some time and writing down missing things. This is the last one for now ;)

It's okay, it's my view that we should work on what people actually use, and you opening all those issues give us a pretty good incentive to improve/fix/talk about the API.
