### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4082]
Is there a reason to keep the following branches on the friendica repository:
- fabrixxm-patch-1
- gh-pages

I'd like them to be remove if they don't serve any purpose anymore. The only branches that should be alive are `develop` and `master`.

**Comment by annando** [comment]
"gh-pages" is our old homepage. But, yeah, I guess we can get rid of it.

**Comment by MrPetovan** [comment]
Thanks, and `fabrixxm-patch-1` was a hotfix branch that should have been removed after the pull request was merged.

Both branches have been deleted, I'm breathing better now.
