### ISSUE TITLE
Implement account/update_profile API

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4094]
This would allow users to edit their profile from another client.
It is documented here: https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile

I'm not sure all the parameters apply to Friendica, but we could at least use `name` and `description`.

**Comment by Rudloff** [comment]
I started working on this. I'm just waiting for #4121 to be fixed so I can test it from Twidere.

**Comment by annando** [comment]
You will experience a small problem with the "location" field when implementing this. The location that we return on the API is either the default location in the user table or a combined value from different fields in the profile. I don't think that you can easily write these values back.

**Comment by Rudloff** [comment]
I'm only working on name and description for now since Twidere only allows to change these.
