### ISSUE TITLE
Hide the "save search" button when the feature is not enabled

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4105]
In Frio, there is a save button on the search results page that loads this URL: `search?search=foo&save=Save`.
However, I can't find the saved search anywhere.
Is this functionality incomplete?

**Comment by annando** [comment]
You have to enable it in the extended features.

**Comment by Rudloff** [comment]
Oh right, thanks.
Could we maybe hide the save button if this feature is disabled? It is quite confusing to have a button that seems to do nothing.

**Comment by rabuzarus** [comment]
this issue should be fixed. So I close it
