### ISSUE TITLE
Feature: remote_self for OStatus contacts

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4112]
A user of my node has a use case where she wants to automatically reshare posts from a Mastodon contact.
Is it possible that we implement the remote_self mechanism for OStatus/Mastodon contacts?

Thank you!

**Comment by annando** [comment]
The question is: What is the background of doing so? Everyone on Friendica could subscribe to the Mastodon account.

**Comment by annando** [comment]
I'm not a big fan of semi abandoned Friendica accounts that are only used for mirroring and where friendship requests are never answered because that person only logged in once and never again, I must confess.

**Comment by AlfredSK** [comment]
Me too. But on the other hand, I'm also no fan of making regulations how other people have to use Friendica. :-) The account isn't abandoned. It is used actively. See... https://libranet.de/profile/marionline
If you think that it isn't a good idea I can live with that. :-) Feel free to close the issue.

**Comment by annando** [comment]
We can put this issue on the list of feature requests. Possibly someone wants to work at it.

**Comment by tobiasd** [comment]
Maybe the workaround over a RSS feed works? Should mastodon export a simple RSS feed, which I have not checked.

**Comment by AlfredSK** [comment]
I found a feed. Example: https://mastodon.social/users/libranet.atom
But it looks like the feed has some issues. It consists of shares _and_ reshares and the posts have strange headlines. :-)
But maybe, this is good enough as a workaround.

**Comment by paulinsche** [comment]
My use-case: The mastadon-app ist great for sharing pictures, where this is (with 3.6) not so comfortable.

**Comment by annando** [comment]
Have you tried Twidere with Friendica?

**Comment by paulinsche** [comment]
Looks like a solution for me :+1: --- can remove twitter and mastelab/mustard AND twitter official app... Thank you for the hint.

**Comment by annando** [comment]
The OStatus part of Friendica is more or less in hibernation. I must confess that I don't intend to do much more than some bugfixing to that module.

**Comment by AlfredSK** [comment]
I understand and agree. Should I choose it?

**Comment by annando** [comment]
You could choose to close it :-)

**Comment by AlfredSK** [comment]
Hey!

**Comment by MrPetovan** [comment]
Ha!
