### ISSUE TITLE
Enhance: export of events to other networks

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4115]
The stream entries for Events that reach other networks need some improvements. See e.g. [here](https://diasp.eu/posts/6499893), some HTML and some BBCode elements are included.

**Comment by tobiasd** [comment]
[Another example](https://despora.de/posts/8497210)

**Comment by annando** [comment]
This should now be fixed through PR https://github.com/friendica/friendica/pull/4586

**Comment by tobiasd** [comment]
How do they look in GNU social?

**Comment by annando** [comment]
Haven't tested that. But the problem was mostly the HTML2Markdown conversion.

**Comment by annando** [comment]
Could you check it?

**Comment by tobiasd** [comment]
Will do

**Comment by annando** [comment]
It looks great on GNU Social, I think: https://gnusocial.de/notice/14082762

On Diaspora it will need some love: https://pod.geraspora.de/posts/0b6b25a8805aaf62b84eff8529847544

**Comment by tobiasd** [comment]
They should really show the map ;-)

**Comment by annando** [comment]
Give me some time (this evening will be okay) then Diaspora will show a map.

**Comment by tobiasd** [comment]
In the RSS feed the exported event looks ok.

**Comment by tobiasd** [comment]
Diaspora looks good now?

**Comment by annando** [comment]
Including a card link. Just test it for yourself.

**Comment by annando** [comment]
Look here: https://pod.geraspora.de/posts/ec054ce7645ab186a0aa9f0053237354

**Comment by tobiasd** [comment]
Seems not to work anymore...

* friendica https://friendica.xyz/display/adf174d5125ac7476ae9baf005928029
* diaspora* https://pod.geraspora.de/posts/7842058

**Comment by tobiasd** [comment]
For the Atom/RSS feed export, I think if an event has a title set, that should be used instead of the "new note by" title. But that might be a general issue with the RSS feed?

**Comment by PolynomialDivision** [comment]
In the mobile view everything seems to look nice?
