### ISSUE TITLE
Move PHP libraries from library to composer

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4116]
Third part of the code restructuration with #4090 and #3878, this aims at getting rid of the `library` folder in favor of Composer.

The move process is the following for each library:
- Look for the same library name in Packagist, the Composer repository
- If it doesn’t exist, look for the library name in Pear, Composer can import them directly
- If found either way, don’t directly use `composer require` as the version likely changed since it was last updated in `library`. Instead edit `composer.json` to add the package and its target version manually to the list. You can use a star to make Composer import the latest minor version that’s unlikely to break compatibility
- Remove require calls to the library in the code. The Composer autoloader should take care of requiring the imported library.
- **Test the feature**! If you can’t, drop the whole process, clean up any changes you made to composer or the code and move on to the next library. Everything in `library` is currently working so we’d rather not introduce regressions because of a lack of testing.
- Even with minor version increases it’s possible to have breaking changes, make the necessary adjustments in the code and test, *test*, **test**!
- Once you’ve make sure the new library in Composer is working properly, delete the relevant file(s) in `library` and commit the files in `vendor`. Normally the vendor folder is excluded from git, but we don’t have updated our release process to still include them while trusting `develop` users to run `composer install`.
- Celebrate! 🎉

**Comment by MrPetovan** [comment]
TwitterOAuth was the last PHP file that I could safely move out of `library`. The following files are hard dependencies of Friendica in their current version or don't exist as a package in Packagist:
- ASNValue.class (used in `Util\Crypto` for Salmon Magic Envelope)
- asn1.php (used in `Util\Crypto` for Salmon Magic Envelope)
- OAuth1.php (extended by FKOAuth1.php)
- slinky.php (absent from Packagist, required in `Util\Network` and only used by the StatusNet addon)

There are more recent Packagist libraries for dealing with ASN1, Salmon and OAuth, but I'm not knowledgeable enough in either topics to know how to rework them.

The last resort, of course, is to keep them as is and making them available through the Composer autoloader. There are two solutions:
- keep the `library` folder and set Composer autoloader to look for classes inside
- move the remaining PHP files to `vendor/legacy` and set the Composer autoloader to look for classes inside. This effectively removes the `library` folder but adds the `vendor` folder back into source control, with a potential future name conflict with a vendor named `legacy`.

What do you think?

**Comment by annando** [comment]
We can remove slinky, I guess. URL shorteners are so old fashioned ...

I think we should leave the files in the old place, just to remind us of finding good replacements.

**Comment by MrPetovan** [comment]
Finally closed by #9184 and #9327
