### ISSUE TITLE
Implement list API

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4134]
The [`lists/list`](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-list) endpoint currently exists but always returns an empty array.

The following endpoints could also be useful:
* [`lists/ownerships`](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-ownerships)
* [`lists/create`](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/post-lists-create)

These are also used by Twidere but I'm not sure they make sense in Friendica:
* [`lists/subscriptions`](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-subscriptions)
* [`lists/memberships`](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-memberships)

**Comment by annando** [comment]
We now support the corresponding API endpoints in the Mastodon part of our API.
