### ISSUE TITLE
Only show top level posts in profile feed

### ISSUE THREAD

**Issue by annando** [friendica/friendica#4137]
The profile feed should have an option to only show the top level posts.

**Comment by MrPetovan** [comment]
+1

**Comment by MrPetovan** [comment]
My last top-level post doesn't show in my post feed. It could be a cache issue but the 15-minutes TTL is long passed.

Post: https://friendica.mrpetovan.com/display/735a2029105a5568794f6f2779787214
Feed: https://friendica.mrpetovan.com/feed/hypolite/

**Comment by AlfredSK** [comment]
I cannot access the post on your node (1st link). It doesn't work on my node too: https://libranet.de/display/735a2029105a5568794f6f2779787214 
Is this a public post?
I just tested the feed myself and it worked.
https://libranet.de/feed/alfred

**Comment by MrPetovan** [comment]
Indeed, the post was somehow private, thanks for checking on your side.
