### ISSUE TITLE
NGINX HTTP Splitting security issue

### ISSUE THREAD

**Issue by anmol26s** [friendica/friendica#4146]
There is security issue hinted by gixy to change $uri to $request_uri on these line 
https://github.com/friendica/friendica/blob/develop/mods/sample-nginx.config#L86
https://github.com/friendica/friendica/blob/develop/mods/sample-nginx.config#L88
https://github.com/friendica/friendica/blob/develop/mods/sample-nginx.config#L95

See this check of YunoHost indicating it
https://github.com/YunoHost-Apps/friendica_ynh/pull/1#issuecomment-354454132

gixy indicating security issue here:
https://github.com/yandex/gixy/blob/master/docs/en/plugins/httpsplitting.md

Can someone test it with $request_uri  on nginx and confirm the normal working, so that pull request could be created as I am not using Friendica right now.

**Comment by AndyHee** [comment]
Shouldn't this config be updated to php7.0-fpm?

Conservative and cautious distros like Debian are already using PHP7.0; PHP5.0 is not considered standard any more.

https://github.com/friendica/friendica/blob/develop/mods/sample-nginx.config#:L130

**Comment by tobiasd** [comment]
If you know what you are doing ;-) please do :-D

**Comment by anmol26s** [comment]
@AndyHee 
If you have php7.0 then you can change it to `fastcgi_pass unix:/run/php/php7.1-fpm.sock;`
Note that on Debian jessie php7.0 is not there by default.

**Comment by tobiasd** [comment]
Eelco [tested](https://forum.friendi.ca/display/174591b4145af3bcfca3b94481973156) the following setting

    loc­a­tion /​{
      root /​var/​hosting/​hutspod/​public;
      index index.html index.htm index.php;
      try_​files $uri $uri/​/index.php?q=$request_uri&$args;
    }

and everything except the `network` tab seemed working. Same result when `?q` was exchanged by `?pagename`.

**Comment by tobiasd** [comment]
Some more results from testing, that are broken in the approach of the OP.

* https://​social​.isurf​.ca/​n​e​t​w​o​r​k​?​f​=​&​a​m​p​;​o​r​d​e​r​=post
* https://​social​.isurf​.ca/​s​e​a​r​c​h​?​s​e​a​r​c​h​=​nginx

**Comment by AndyHee** [comment]
@anmol26s Debian 8 has been superseded by Debian 9 ("stretch").

**Comment by realkinetix** [comment]
I did more testing on this over the weekend, couldn't find a solution, but I am curious about what's tripping Friendica up... please have a look at https://social.isurf.ca/display/c443a55c125b01e17647b72981577555

**Comment by tobiasd** [comment]
@AndyHee it has, but @anmol26s has Friendica and Hubzilla packages for YunoHost which still is Jessie based.

**Comment by tobiasd** [comment]
I'll close the issue as #5122 made the changes @anmol26s proposed in #5019 to fix this into the RC branch. The changes got tested by 3 people and seem to work (I don't have a nginx setup myself) If anyone encounters problems, don't hesitate to use this issue or a new one to let us know.
