### ISSUE TITLE
installer returns .htaccess not working (false negative)

### ISSUE THREAD

**Issue by sebastianschauenburg** [friendica/friendica#4150]
The installer fails with the following message: "URL rewrite in .htaccess is not working. Check your server configuration.". I think it's a false negative since:
 * /install/testrewrite returns OK
 * .htaccess works (breaking the config due to changing the file, results in a nonworking website)
 * manually creating a .htconfig results in a working instance (I can create a useraccount for example)
 * I host multiple sites (such as wordpress, with similar apache configurations) and they work fine.

I assume it has something to do with vhosts and SSL. I use a Let's Encrypt SSL certificate (e.g. valid) right from the start of the installation. The HTTP website redirects to the HTTPS version (e.g. there is no HTTP version of the website) with an Apache vhost configuration line such as:

>         Redirect permanent /            https://some.site.fqdn/

The server is running on Debian 9.3 (Stretch) and I'm also using ServerName and ServerAlias, but that shouldn't matter at all. 

I've read through many issues and though they are similar, they are not the same:
 * not using suexec
 * .htaccess effectively works (since I doubt everything, I've also increased the LogLevel rewrites to trace8)

Please let me know how I can help to debug this. Cheers.

**Comment by annando** [comment]
You could have a look at the access.log to see which page the install process is calling.

**Comment by sebastianschauenburg** [comment]
Access and error logs didn't bring up anything useful. Since https://yourhostname.tld/install/testrewrite returns OK, I tried to access that URL from the host, which didn't work correctly. Name resolving was a bit flaky and caused this issue and fixing DNS fixed it. (default hosts file workaround also works)

**Comment by MrPetovan** [comment]
Thanks for the follow-up!
