### ISSUE TITLE
New table structure for items

### ISSUE THREAD

**Issue by annando** [friendica/friendica#4154]
This will be a "living documentation". We will replace the single "item" table in a mixture of several tables to reduce redundancy and data growth. The tables will be:

* `thread` - for user specific data. One entry per Thread and user.
* `item-content` - Contains the item content. (Body, title, ...). One entry per item guid/item uri.
* `item-user` - Data that is user specific (like "hidden"). One entry per user and `item-content`.
* `thread-permission` - will replace `allow_cid` and so on. 1:N, attached to `thread`.
* `item-attachment` - attached data. 1:N, attached to `item-content`.
* `item-tag` - mentions and hashtags. 1:N, attached to `item-content`.

(Names can be changed)

We will analyze each field in the `item` table to see to which table it belongs (or if it can be discarded).

**Comment by MrPetovan** [comment]
Aren't `thread` and `item-user` redundant?

**Comment by annando** [comment]
```thread``` is a single entry per thread, ```item-user``` is an entry per post. 

Especially it is important for the sorting. It does make sense to have an index for "uid, commented" on the thread, but not on the item. There we (I guess) will only need an index "uid, item-id". And the thread will have different data than the item-user.

**Comment by MrPetovan** [comment]
Gotcha.

**Comment by tobiasd** [comment]
Is the work done with this @annando ?

**Comment by annando** [comment]
Not totally. It is completely different from the plans and the user items are still open - or some other solution.

**Comment by MrPetovan** [comment]
These comments used to be in the DB structure file and can't be moved to the new JSON database structure file.
```
// User specific fields. Eventually they will move to user-item`
uid, contact-id, wall, origin, pubmail, starred, unseen, mention, forum_mode, psid
// It has to be decided whether these fields belong to the user or the structure
resource-id, event-id
// Could possibly be replaced by the "attach" table?
attach
// Deprecated fields. Will be removed in upcoming versions
allow_cid, allow_gid, deny_cid, deny_gid, postopts, inform, type, bookmark, file, location, coord, tag, plink, title, content-warning, body, app, verb, object-type, object, target-type, target, author-name, author-link, author-avatar, owner-name, owner-link, owner-avatar, rendered-hash, rendered-html
```

**Comment by annando** [comment]
From my point of view this issue is mostly complete. We do have separate tables. We can do something this the tags and the attachments, but this can be considered in the future. So I declare this closed.
