### ISSUE TITLE
Drop support for PHP < 5.6

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4161]
The PHP Group doesn't support 5.4-5.5 versions anymore for 1 year and a half already: http://php.net/supported-versions.php

Shared hosting overwhelmingly provides support for PHP 5.6: http://phpversions.info/shared-hosting/

The [upcoming changes to password hashing using `password_hash()`](https://github.com/friendica/friendica/issues/3942) will bump the minimum version requirement to 5.5.

Do we have any statistics about PHP version usage among Friendica nodes?

**Comment by rabuzarus** [comment]
*gg* my devel machine does use php5.4

**Comment by MrPetovan** [comment]
Have you considered an upgrade? What OS is it?

**Comment by rabuzarus** [comment]
opensuse 13.1. I missed the distribution updates (dist upgrades are really annoying for opensuse). Now the version isn't supported anymore. The problem is that I would need to update several versions. So I decided to do a fresh install (and switching to openssuses rolling release - opensuse tumbleweed). But for a fresh install I would need one week (because there are so many own configurations and many self compiled packages - to take this time is impossible for the next time) and I would need a new hdd which I can't afford at the moment :-/

**Comment by MrPetovan** [comment]
Stay in school, kids, don't miss distribution updates.

**Comment by rabuzarus** [comment]
OK I got php56 installed through https://download.opensuse.org/repositories/home:/aeneas_jaissle:/sewikom/openSUSE_13.1/

But I need compile xdebug by my self. Hopefully it will work.

**Comment by rabuzarus** [comment]
OK xdebug is a also compiled. I love it when this is working easily (sometimes you have to try several days until you give up because some packages won't compile)

**Comment by annando** [comment]
There are hosters (e.g. Uberspace) who are still using 5.4. They are using CentOS 6 which still hadn't got EOL.

**Comment by MrPetovan** [comment]
Apparently this is configurable, see https://wiki.uberspace.de/development:php

It seems to depend on the specific host but CentOS 6 doesn't seem to be the limiting factor for the version of PHP.

**Comment by tobiasd** [comment]
> Do we have any statistics about PHP version usage among Friendica
> nodes?

That PHP statistics page is great. Additionally I would always consider which versions are provided by the Oldstable/LTS versions of the most used distributions. On Debian that would be php5.6 and Ubuntu LTS is php7 I believe.

CentOS on the other hand has a really long support time, 10 years for versions 5/6/7, and I don't think we should wait for every distribution.

For me 5.6 sounds reasonable as lower limit.

**Comment by annando** [comment]
Okay. Then I state the opposite ;-)

**Comment by MrPetovan** [comment]
@tobiasd I initially wrote this issue as dropping support for PHP < 7 but the PHP version OS page convinced me to revise my expectations! 😅
