### ISSUE TITLE
PHP Fatal error: Uncaught BadFunctionCallException

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4163]
Hello,
since the last pull from develop I'm getting a lot of these PHP errors. I think it started yesterday.

```
PHP Fatal error:  Uncaught BadFunctionCallException: defaults($arr, $key, $def) requires an array as first parameter in /var/www/html/libranet/boot.php:599
Stack trace:
#0 /var/www/html/libranet/mod/profile.php(60): defaults(NULL, 'pub_keywords', '')
#1 /var/www/html/libranet/index.php(336): profile_init(Object(Friendica\App))
#2 {main}
  thrown in /var/www/html/libranet/boot.php on line 599
```

Edit: PHP Version 7.0.22

**Comment by AlfredSK** [comment]
I think I found the responsible commit. But I'm not sure because I'm a bloody amateur.
https://github.com/friendica/friendica/commit/4e6050489d2179adf9d156b3f00f3c8e9645af0c
Hello @MrPetovan :-)

**Comment by MrPetovan** [comment]
Yeah, I guess I was too strict in the parameter checks in this function. NULL is a perfectly valid value for a variable supposed to be an array. I'm keeping the other null check for the key variable.

**Comment by AlfredSK** [comment]
The error is gone. Thank you once more for fixing the things you've broken. :-D
Thanks! 🥇 👍
