### ISSUE TITLE
Scrutinizer error tracking issue

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4176]
https://scrutinizer-ci.com/g/MrPetovan/friendica/issues/task/4176-scrutinizer

Log:
- January 16th 2018: 1691 issues
- January 19th 2018: 1681 issues
- February 7th 2018: 2018 issues (!?)
- February 13th 2018: 1964 issues (thanks @rabuzarus)
- February 14th 2018: 1898 issues
- October 22th 2018: 2222 issues (!!)
- December 25th 2018: 2459 issues (!!!) but the code quality score jumped from 2.9 to 3.54 out of 10!
- December 26th 2018: 2219 issues (https://github.com/friendica/friendica/pull/6327)
- January 7th 2019: 2344 issues (because of the deprecation of Logger::log)

**Comment by MrPetovan** [comment]
@MrPetovan added `Tedious` `Necessary` labels a day ago

**Comment by annando** [comment]
In German you would say "Mühsam ernährt sich das Einhörnchen" (comparable to "Little by little, the bird builds its nest.")

**Comment by MrPetovan** [comment]
Here's how static analysis can concretely help a project code health in unexpected ways: When I updated `dba::select()` return type documentation to reflect the possibility of an `array` in case of `limit => 1`, the next Scrutinizer inspections showed a bunch of issues regarding type handling around the fact that we were calling array-only functions on the return data of `dba::select(limit => 1)`.

It then hit me that we were doing two very different things with `dba::select()` and that it should probably be split into two distinct functions. This helped:
- Create `dba::selectFirst()` with a clear and simple purpose and non-ambiguous return types.
- Make `dba::select()` clearer and simpler with less conditions and non-ambiguous return types. I removed an input parameter (`$params[only_query]`) and a variable (`$single_row`) that didn't need to be moved to the new function.
- Simplify all the `dba::select(limit => 1)` calls to `dba::selectFirst()`.

I probably could have come up with the change myself but the fact is that I didn't, and only my commitment to fix issues brought up by Scrutinizer finally prompted me to do it.

**Comment by MrPetovan** [comment]
I finally got to run Scrutinizer again after the TLS debacle surrounding `git.friendi.ca`, and unfortunately we jumped 300 issues since last February.

BUT the Scrutinizer Code Quality Score jumped from 2.91/10 to 3.47/10, so we must be doing something right.

**Comment by MrPetovan** [comment]
Currently the output of Scrutinizer isn’t useful, too many false positives, closing here.
