### ISSUE TITLE
Registration not possible - allowed mail domains broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4184]
Registration of new users is not possible with current develop branch. The 'allowed email domains' field at the admin panel isn't working as expected.
If the field is empty all domains should be allowed. But at the moment all domains are forbidden if the field is empty. 
Workaround: Put an asterisk in the field as placeholder. :-)

Summoning @MrPetovan because I think this is related to one of his latest commits. Hello! 👋

**Comment by AlfredSK** [comment]
Thanks for the fix. Registrations are working again. 🍰

**Comment by MrPetovan** [comment]
No, thank you for testing `develop` on a live node!

**Comment by tobiasd** [comment]
In the support forum thread Richard mentioned that he still has some strange problems. But I think that is something specific for his node?

**Comment by MrPetovan** [comment]
Can you be more specific?

**Comment by MrPetovan** [comment]
Ok, there's not much I can do with what you said, if you can get a specific use case that's failing with the latest develop I could work with it.
