### ISSUE TITLE
In memory... 

### ISSUE THREAD

**Issue by elvecio** [friendica/friendica#4189]
https://github.com/redmatrix/hubzilla/issues/952
https://github.com/tonybaldwin
Thank you.

**Comment by MrPetovan** [comment]
I'm sorry about his passing, @tobiasd wrote something about him on Friendica here: https://friendica.mrpetovan.com/display/f3ad7b1c835a53a59460086045301640

I never had any contact with him so I'll refer to someone else for the appropriate tribute to give him on Friendica.

**Comment by tobiasd** [comment]
I've just added the paragraph with a heavy heart to my draft of the release notes preparing the upcoming release.

**Comment by tobiasd** [comment]
Thanks for your patience @elvecio *The Tazmans Flax-lily* was just released, dedicated to @tonybaldwin, I'.' close the issue now.
