### ISSUE TITLE
Notifications aren’t created

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4199]
I haven’t received a single notification since 19 hours ago, although people have been replying to my posts and interacting with posts I liked.

I haven’t had the chance to review the PHP error log yet.

**Comment by MrPetovan** [comment]
While I was debugging the notification function yesterday, some started to show up, and this morning I received some notifications for items I posted yesterday 12 hours ago. I'm not sure I understand what could be wrong.

**Comment by annando** [comment]
I'm on the current code and I'm getting notifications.

**Comment by MrPetovan** [comment]
It's good for now for me as well.
