### ISSUE TITLE
Replies to comments are always attached to top-level post

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4207]
Since this morning on the latest develop, every time I tried to reply under a comment, the comment is displayed as a comment on the top-level post.

I seem to remember @annando changed code in `include/items.php` regarding the parent to give the ability to comment on public posts but I'm not certain it would be the exact cause of this behavior.

**Comment by annando** [comment]
I will have a look at it soon. I can imagine that it has something to do with the unification of the item store functionality.

**Comment by annando** [comment]
Could this be some optical glitch because of the flattening of deep item structures? It really looked great on my system today.

**Comment by MrPetovan** [comment]
I’ll be able to check the DB tonight, but I don’t think the display would be that far off.

**Comment by MrPetovan** [comment]
Check proved I was right, but now it works as expected.
