### ISSUE TITLE
Image upload without a posting should not trigger an activity on OStatus

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4228]
When uploading an image via `/photos/$nick/upload` one can decide not to post a new entry with the photo. Which is the default setting of the options in the dialog.

Even with this option active a posting on OStatus is created with the new image, containing a back link to the Friendica node that does not contain a valid item ID for the `/display`  module.

I would expect that when the option is activated it is also valid for other communication protocols.

**Comment by annando** [comment]
I cannot reproduce on the current develop branch. And according to the source this shouldn't be possible at all.

**Comment by AlfredSK** [comment]
I saw this several times with a Mastodon test account. But I can't remember when and how that happened exactly. I'll try to reproduce it later today.

**Comment by tobiasd** [comment]
> I cannot reproduce on the current develop branch. And according to
> the source this shouldn't be possible at all.

For me it happened last time a month ago. I uploaded a screenshot public to my Friendica gallery but checked not to send a message around with the upload. Later I used that image in a closed thread and got a reply from @hoergen, that on GNU social he saw only the image, but not the text. But it happened before as well.

**Comment by annando** [comment]
Okay, found. This was really hard to find since it was a totally indirect thing.

**Comment by MrPetovan** [comment]
👏👏👏

**Comment by tobiasd** [comment]
I did a test this morning (the screenshot in my fork awesome posting) but could only find the posting, not the image. So I think this is working now as expected.
