### ISSUE TITLE
bug location

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#4236]
Link: https://dir.friendica.social/directory/search?query=Argentina

Server: yes Argentina
Users:Not all are from Argentina

[![imagebin](http://upimage.mamalibre.com.ar/up/f56f58142eee0dd23bda1cccf5b0ecad.png)](http://upimage.mamalibre.com.ar/#f56f58142eee0dd23bda1cccf5b0ecad.png)

**Comment by MrPetovan** [comment]
Thanks for the report, there is a specific issue tracker for Friendica's Directory : https://github.com/friendica/dir/issues, can you please close this one and open another over there?

Thanks!
