### ISSUE TITLE
Contact request from OStatus should be possible to accepted as full contact

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4242]
When getting a contact request from OStatus there is at the moment only the possibility to connect as follower instead of full contact. In a second step you can request a connection so that you get your contacts posts as well.

This should be changed so that you don't have to do the second step and you can accept the contact request as full contact. (that would omit the second step)

**Comment by annando** [comment]
This is more or less one of the "don't want to fix" things. With the exception of GNU Social we won't use OStatus anymore in the future. And with AP the connection process is coded in the described way.
