### ISSUE TITLE
queue is not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4256]
looks like #4254 has broken the queue.

`util/typo.php` sais

> PHP Fatal error:  Cannot declare class Friendica\Worker\Queue because the name is already in use in src/Worker/Queue.php on line 23

**Comment by zeroadam** [comment]
OK.. How should this be renamed. Also, I thought there was discussion about namespaces separating class names that were duplicate, which is why I didn't immediately think this would cause issue... :-(

**Comment by MrPetovan** [comment]
Closing #4256 through #4258
