### ISSUE TITLE
Move JS libraries to Composer

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4265]
Follow-up to #4116,

Now that all the PHP libraries have been extracted from `library/`, let's move to extract all Javascript libraries from `library/` and `js/`.

The move process is the following for each library:
- Look for the same library name in Bower or NPM (all jquery-related libraries)
    - Please look first in the Bower repository for al non JQuery libraries. Bower features an ignore config which reduces the footprint of imported libraries by removing development and tests files from the source repository.
    - If found in Bower: `composer require bower-asset/[library]:^[current version]`
    - If found in NPM: `composer require npm-asset/[library]:^[current version]`
- Update the `<script>` tags in the `view/` directory.
- **Test the feature**! If you can’t, drop the whole process, clean up any changes you made to Composer or the code and move on to the next library. Everything in `library/` and `js/` is currently working so we’d rather not introduce regressions because of a lack of testing.
- Even with minor version increases it’s possible to have breaking changes, make the necessary adjustments in the code and test, *test*, **test**!
- Once you’ve make sure the new library in Composer is working properly, delete the relevant file(s) in `library/` or `js/` and commit `composer.json` and `composer.lock`.
- Celebrate! 🎉

Caveats:
- `js/jquery.textinputs.js`: Part of Rangy obsolete for a while, not sure about the upgrade path, left as-is for now.
- `js/ajaxupload.js`: Another obsolete library unavailable in the Javascript repositories. No drop-in replacement found yet.
- `library/cropper`: Another obsolete library unavailable in the Javascript repositories. No drop-in replacement found yet.

Theme libraries that can be mutualized:
- `font-awesome`

**Comment by MrPetovan** [comment]
- `js/jquery.migrate.js`: Do we still need it?
- `js/modernizr.js`: What do we use it for?

**Comment by tobiasd** [comment]
What about font awesome? It is currently twice in the repository IIRC once in vier and once in frio.

**Comment by annando** [comment]
The whole JS stuff is not my cup of tea. So I hope that someone else can answer the question. The only thing I can do is to use ```grep``` to search for function calls, but that doesn't help that much.

**Comment by MrPetovan** [comment]
> What about font awesome? It is currently twice in the repository IIRC once in vier and once in frio.

Font-awesome is available about 4 times in the Bower repository 😄

It's added to the list of libraries we can move to Composer.

**Comment by annando** [comment]
We are using several different versions, I guess. And in "Vier" I even manually edited the CSS and used an old CSS with a new font file. Changing this will be "fun" (from a painful point of definition).

**Comment by tobiasd** [comment]
haha :) ok it was just a thought but if it is a custom build of fa then better noch touch it

**Comment by annando** [comment]
I'm for touching it :-) But then we have to make sure that it keeps on working.

**Comment by MrPetovan** [comment]
Move of `jquery-textcomplete` is bogged down by common library issues between npm and Bower: https://github.com/fxpio/composer-asset-plugin/issues/311 https://github.com/fxpio/composer-asset-plugin/issues/312
