### ISSUE TITLE
Deleting vendor broke my instance

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4273]
@MrPetovan i followed your advice and deleted my vendor directory,
Then i did a git pull, that worked good and then i did a util/composer.phar update and now i got this message

`util/composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)          
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/base64 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

and  now my friendica is inaccessible :(

**Comment by hoergen** [comment]
Forget that m) I did a util/composer.phar install and everything is back

**Comment by hoergen** [comment]
Yes

**Comment by annando** [comment]
Okay, then I'm closing it now.

**Comment by MrPetovan** [comment]
Related to #4259
