### ISSUE TITLE
Fatal error: require_once(): Failed opening required vendor/autoload.php in boot.php on line 21

### ISSUE THREAD

**Issue by strk** [friendica/friendica#4278]
As of commit 4f43d9e501c9b528f10f0337beb028ba40313684
friendica is impossible to visit, fatal error and blank page.

Chances are this was introduced by merging #4259 - that is with commit a13ad278ef571e77919502db1daccd2ca8e43c6b

**Comment by tobiasd** [comment]
Please run

    util/composer.phar install

from the bottom of your Friendica installation.

**Comment by strk** [comment]
Here's what I get:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for defuse/php-encryption v1.2.1 -> satisfiable by defuse/php-encryption[v1.2.1].
    - defuse/php-encryption v1.2.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-apcu.ini
    - /etc/php5/cli/conf.d/20-curl.ini
    - /etc/php5/cli/conf.d/20-gd.ini
    - /etc/php5/cli/conf.d/20-imagick.ini
    - /etc/php5/cli/conf.d/20-intl.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-pdo_mysql.ini
    - /etc/php5/cli/conf.d/20-pdo_pgsql.ini
    - /etc/php5/cli/conf.d/20-pgsql.ini
    - /etc/php5/cli/conf.d/20-readline.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

Friendica installation used to be straightforward, is this making it a lot harder ? Could this step be done automatically, maybe with some placeholder code running it ?

**Comment by strk** [comment]
NOTE: installing php5-mcrypt made the composer run work, so I'm closing this. But I'm still concerned about ease of install/upgrade.

**Comment by tobiasd** [comment]
> Friendica installation used to be straightforward, is this making it
> a lot harder ? Could this step be done automatically, maybe with some
> placeholder code running it ?

Yes, what you describe is a known issue and has to be addressed before releasing the next stable version. Consens was that, if you want to run development code, users can also issue the composer command after the pull. The update intructions in the got updated accordingly and the instructions in the release notes will be detailed for this as well.

> php5-mcrypt

Please note that the minimum version of PHP required by Friendica was recently raised to 5.6, just in case you are on a older server.

**Comment by MrPetovan** [comment]
> Friendica installation used to be straightforward, is this making it a lot harder ? Could this step be done automatically, maybe with some placeholder code running it ?

The "normal" installation from an archive will continue to be straightforward. If you don't want to type the command after each pull, you can check Git hooks: https://nerdpress.org/2014/11/14/git-deploy-composer-install-hook/
