### ISSUE TITLE
Encrypt private messages/private items

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4279]
Working on upgrading `defuse/php-encryption` (#4272) got me thinking about how we could expand its usage beyond the RINO setting.

I read the php-encryption tutorial here: https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md
And it says

> **This isn't for encrypting network communication**: Likewise, if you're trying to encrypt messages sent between two parties over the Internet, you don't want to be using this library. For that, set up a TLS connection between the two points, or, if it's a chat app, use the Signal Protocol.
> 
> What this library provides is symmetric encryption for "data at rest." This means it is not suitable for use in building protocols where "data is in motion" (i.e. moving over a network) except in limited set of cases.

It got me thinking that we actually don't encrypt private messages and private items. An admin or an database attacker has access to the private communications of all the users, which kinds of defeat the point of `Privacy` we are claiming on http://friendi.ca.

How it works is we are encrypting the private key of each user with their own password. Which means data encrypted with their public key can only be decrypted once they have provided their password and decrypted their own private key. As soon as they log out, their private key and private messages are unable to be read either by the node admin nor by any attacker getting a dump of the database.

What do you think about it?

**Comment by annando** [comment]
Nice idea - but it is complicated to avoid any attack vectors. An attacker could simply hack into the server and could start listening for some time, until the persons logged in.

So when we are doing this, we shouldn't reinvent the wheel, but should have a look at how other solved this problem.

**Comment by MrPetovan** [comment]
The caveat is that we can’t encrypt with the user’s private key in the worker process.

The complication is that we still need the public key available at least for Diaspora communication. And any decryption from Diaspora has to be postponed until the user logs in.

Maybe we should us a separate key for this, it would be simpler.

**Comment by annando** [comment]
Some JS based encryption with a ```[crypto]``` BBCode element would be a "easy to implement" solution.

**Comment by tobiasd** [comment]
I once tried that, but my JS-fu was to bad for this. Reviving the crypt tag would be grat.

**Comment by MrPetovan** [comment]
What does JS has to do with it? Transmitting the user’s unencrypted key for Javascript to use isn’t ideal.

I was thinking we could also encrypt the private message/item metadata (mainly the author) so that only the recipient would be able to know who sent them what after we receive the message.

In this case Javascript would be even more unwieldy.

**Comment by annando** [comment]
There is some client based JS encryption, so that the key never leaves your system.

**Comment by MrPetovan** [comment]
So you would supply your own public key to Friendica, and then the Javascript plugin/addon/client would use your private key to decrypt in your browser?

**Comment by annando** [comment]
I'm not sure how this is really working.

**Comment by MrPetovan** [comment]
Anyway, now that we got defuse/php-encryption out of Friendica, I'm not sure I want to bring it back again to implement this. I would probably go straight for llibsodium anyway, but this looks more work than I'm ready to put down.
