### ISSUE TITLE
Group Widget

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#4290]
Hello,

there is a small bug in the Group Widget

**Edit Group** -> **Contact without Group**
`
Warning: require_once(include/contact_widgets.php): failed to open stream: No such file or directory in /something/mod/nogroup.php on line 17
`

Line 17: `require_once 'include/contact_widgets.php';` but there is no `contact_widgets.php` in folder `include`

**Comment by zeroadam** [comment]
Will be fixed by: https://github.com/friendica/friendica/pull/4289

**Comment by MrPetovan** [comment]
Thanks for your report! This is now fixed.
