### ISSUE TITLE
Extra HTML + BBCode output in Mastodon post

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4295]
Original Mastodon post: https://mastodon.social/@Gargron/99385733176194324
Friendica display: https://friendica.mrpetovan.com/display/52acf9cda0c0247e117755756e29d88f80e25747

There is an extra `" target="_blank">http://po.st/A...[/attachment]` at the bottom of the post.

**Comment by annando** [comment]
So it is looking on my machine: https://pirati.ca/display/52acf9cda0c0247e117755756e29d88f80e25747

It will be somewhere in the functions that are called from ```add_page_info_to_body```.

**Comment by MrPetovan** [comment]
Another example from Diaspora: https://friendica.mrpetovan.com/display/0f9cbcd0e1d50135fdb9047d7b62795e
Original post: https://diasp.org/posts/0f9cbcd0e1d50135fdb9047d7b62795e

**Comment by annando** [comment]
The problem is the new regexp for URL in include/bbcode.php. It is too greedy.

**Comment by MrPetovan** [comment]
Another display issue in this post after the reversion: https://friendica.mrpetovan.com/display/0c40ea67635a7b332cce3be770120356

**Comment by MrPetovan** [comment]
Ok, the last one is trigger by the `@` in the Mastodon URL that get transformed into Twitter mentions.

**Comment by MrPetovan** [comment]
Never mind, The post probably was created on a pre-revert Friendica instance.

**Comment by MrPetovan** [comment]
This is so much a corner case I just filed my hand on it. When a Twitter user is mentioned (here `@sarahjeong`, we replace all occurences of `@sarahjeong` by `@[url=https://twitter.com/sarahjeong]sarahjeong[/url]`. The problem is that the Mastodon URL `https://mastodon.social/@sarahjeong` includes the search string and then get replaced. Nothing to do wih the autolinker regular expression.
