### ISSUE TITLE
renamed hooks cause addon config not to work

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4314]
With #4288 the hook names `plugin_*` got renamed to `addons_*` but in the database still the old name is anchored so that the new hooks are not executed.

**Comment by MrPetovan** [comment]
Ooooooh, we need an update function for that, good catch.

**Comment by zeroadam** [comment]
Yes, sorry about this. I did not experience errors while developing, because I had disabled addons before hand and thus none were in the db table.

**Comment by zeroadam** [comment]
`SELECT hook
REPLACE(hook, 'plugin', 'addon')
FROM hook
WHERE hook LIKE '%plugin%'`

I'm not quite sure how to do this in our update.php but I believe this will take care of the issue.

**Comment by MrPetovan** [comment]
I'm writing an update function right now.

**Comment by MrPetovan** [comment]
I thought it would be simple, but if you fiddled with addon post-update, there will be both `plugin_settings` and `addon_settings` hooks in the table, so a straight update isn't possible because of the primary key. I've been trying to force reload plugins by resetting the timestamp in the addon table but it only reload a single addon before stopping.

I can't spend more time on this but if someone wants to take over:
````
function update_1246() {
	// Removing hooks with the old name
	dba::e("DELETE FROM `hook`
WHERE `hook` LIKE 'plugin_%'");

	// Force reload addons
	dba::e("UPDATE `addon`
SET `timestamp` = 1");

	// Make sure we install the new renamed ones
	Addon::reload();
}
````

**Comment by tobiasd** [comment]
> I've been trying to force reload plugins by resetting the timestamp
> in the addon table but it only reload a single addon before stopping.

There is a button at the top of the addons page in the admin panel to reload all active addons. Could this be of some use to update the hook settings?

**Comment by MrPetovan** [comment]
Normally yes but for some reason on my node it stops after the first addon.

BTW, updating the timestamp shouldn’t be necessary since we modified all the addon files.
