### ISSUE TITLE
Account delegation not available any more

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4315]
The option "manage accounts" (german: verwalten) to switch accounts is not available any more. I'm on developer and pulled today morning

**Comment by annando** [comment]
I guess it is related to https://github.com/friendica/friendica/pull/4293

**Comment by annando** [comment]
Background: Currently delegation worked that way that the system looked for users with identical e-mail and the same password hash. Due to the new password encryption it seems as if even same passwords now have different hashes.

We need a way to solve this issue without compromising security.

**Comment by MrPetovan** [comment]
How do you create managed accounts? Like normal accounts? The management link was only done via identical email/password hash or is there another link made at some point?

**Comment by annando** [comment]
There are two ways: You can do some magic foo in the settings. Then two accounts are connected but they cannot do everything. (This is done for editors) For example you cannot change settings.

And when the mail address and the password hash are identical then the delegations works (worked) automagically. And the person is able to do everything (means: It is an admin delegation)

**Comment by MrPetovan** [comment]
What are the "key settings" you can't change with manual delegation?

**Comment by annando** [comment]
All settings, including profile and so on. You can only post, comment and delete items.

**Comment by MrPetovan** [comment]
So, instead of an automagical admin delegation, we now need an explicit admin delegation. Do the delegated accounts still need to be accessed individually by username/password? Can you have multiple page managers for a single delegate?

**Comment by tobiasd** [comment]
yes they are still accessible by their username/password, and I think it is only one possible delegation from an accout but one account can manage multible accounts.

**Comment by MrPetovan** [comment]
I'm thinking about creating purely delegated accounts the same way you can create pages on Facebook that are only accessible from the page managers, not directly.

**Comment by AlfredSK** [comment]
Just an addition: the 'normal' way of permission to manage accounts is working. With normal way I mean via user settings -> delegations.

**Comment by MrPetovan** [comment]
Can you actually manage delegated accounts?

**Comment by hoergen** [comment]
If i delegate it works again. So I have to login with every account and give delegation to my main account. Then I got "Verwalten" "Delegation" again.

**Comment by MrPetovan** [comment]
What do I need to do then?

**Comment by hoergen** [comment]
Hmm if the delegation feature is intended to do exacly this, then we used an undocumented and maybe not official feature until now ;) If so, I would suggest to close this "non bug"

**Comment by MrPetovan** [comment]
Since you opened it, you can even do it yourself 🙂

**Comment by hoergen** [comment]
Ok. Never did this before \o/ I close it now

**Comment by AlfredSK** [comment]
Yeah. The alternative way via same mail/password was a way to do account management with enhanced possibilities. For example changing the user settings of the managed account.

**Comment by tobiasd** [comment]
> Can you actually manage delegated accounts?

What do you mean with manage? I can access the /manage page where the one delegation I have on my node for a bit of testing is accessible. I can use the page to select that account and switch over. So I guess, yes I can manage the account (not changing any settings, for this I need to login to that account).

**Comment by annando** [comment]
it is important to know that there is a difference between the two types of delegation: The now dysfunctional one allowed to edit all settings (including profile, social media settings, privacy and so on). Using the other method simply allows some basic stuff.

**Comment by MrPetovan** [comment]
More code deletion then, to remove an undocumented feature that's now broken?

**Comment by annando** [comment]
And some new code to enable the different levels of delegation :-)

Additionally we are having to check some functionality. Currently (or better: before the change) we updated the login date of all accounts with same mail and password. This is important for keeping the poller processes running (otherwise they would stop after some time). So we have to check if his is done with the other delegation as well.

**Comment by MrPetovan** [comment]
All of this sounds insane to me.
