### ISSUE TITLE
Make admin delegation explicit

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4319]
Enhancement part of #4315

Before we switched to the secure password hashing (#3942), we used to check on the same email and password hash to grant admin delegation powers, namely changing the settings of the delegated account.

Now that the hashes are unique even for the same password, this undocumented feature doesn’t work anymore and we have to implement an explicit admin delegation toggle.

The delegated account settings can still be changed individually by logging in as the account itself so it isn’t a bug-level priority.

**Comment by annando** [comment]
Maybe not "lug-level" - but in my opinion this has to be solved until the release.

**Comment by MrPetovan** [comment]
Since #4424 admin delegation is possible again, however the `parent-uid` field isn't set anywhere, the delegation nodule still needs to be modified to allow another account to take control of the current one.

**Comment by MrPetovan** [comment]
Relevant discussion: https://friendica.mrpetovan.com/display/ec054ce7375a8113b95d7df686595464

**Comment by MrPetovan** [comment]
I'm still confused by the current delegation interface, so I have no idea what to do for the new one. 

I need an answer to the following questions What should the `delegate/` page show and what are the available actions;
- When there aren't any other accounts with the same email?
- When there are any other accounts with the same email and the current user has a `parent-uid` set?
- When there are other accounts with the same email with no `parent-uid` set?
- When some of the other accounts with the same email have a `parent-uid` set and it isn't the current account?
- When all the other accounts with the same email have a `parent-uid` set and it isn't the current account?
- When some of the other accounts have a `parent-uid` set and it is the current account?
- When all the other accounts with the same email have a `parent-uid` set and it is the current account?

**Comment by annando** [comment]
I guess at first we have to see the difference between the current ```/delegate``` page and the ```parent-uid``` stuff. 

The first one is for allowing other accounts to do _some_ things with your account (like writing posts, commenting, ...) -  but not changing settings.

The second one is for the full (administrative) control. My plan is that in the future you can easily create new accounts as child accounts from your current one. Then the ```parent-uid``` value will be set automatically.

So all we are doing in the meantime with that field is only some interim stuff that needn't to be perfect.

So to make the interim solution easy, we could do it this way:
1. Only show accounts with the same mail address. If there are none, you cannot delegate.
2. Only allow to delegate to an account that isn't delegated itself. (so if an account does have some ```parent-uid``` it cannot be a parent for other accounts)
3. When there are are several accounts with the same mail but without a parent, we show them all.
4. When the current account already is an parent to other accounts, you cannot assign a parent to this account.

**Comment by annando** [comment]
Since there is now a frontend, I think we can close this issue.
