### ISSUE TITLE
"Item not found" when accessing a public comment display URL

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4344]
This is a direct link to a public comment: https://friendica.mrpetovan.com/display/a6551d71ed5bda0f5d9ea9fce9209169225ad9b1

However, when I'm not logged, accessing it shows "Item not found".

**Comment by annando** [comment]
Have a look in the database and look for items with the "guid" with the value "a6551d71ed5bda0f5d9ea9fce9209169225ad9b1". I guess you won't find an item with the "uid" with the value "0".

There are some rules why items aren't copied for the global user.

**Comment by MrPetovan** [comment]
Indeed, is there something we can do about it?

**Comment by annando** [comment]
Could be a bug that prevents he creation of that entry - or intention.

**Comment by hoergen** [comment]
This is common at the moment.
See this post https://social.yl.ms/display/e18176ef235a75760b8d3ca666933054 when you want to open the picture directly to zoom in with this picture url https://social.yl.ms/photos/utzer/image/7e8d6f75978393211d088fcb2cf06eb7 you see a white page.

**Comment by tobiasd** [comment]
>  see a white page.

Is there anything in the PHP log file? WSoD are commonly PHP errors.

**Comment by hoergen** [comment]
I have no accesss on this server, because it's not mine.

**Comment by MrPetovan** [comment]
@hoergen  There's no white page anymore for the URL you provided.

**Comment by hoergen** [comment]
You are right. I can see now the page and picture as well. I'll close this issue then. Thanks to all 🌻

**Comment by MrPetovan** [comment]
🤣

**Comment by MrPetovan** [comment]
The root cause is that Twitter post items are created only for the corresponding importing user. Nothing to do here anymore.
