### ISSUE TITLE
UI corruption from perfect-scrollbar

### ISSUE THREAD

**Issue by zeroadam** [friendica/friendica#4348]
Getting resource not found for: https://<mydomain>/vendor/perfect-scrollbar/dist/css/perfect-scrollbar.min.css

Looking in my vendor directory after util/composer install, there is no dist/ in perfect-scrollbar, but css is there.

**Comment by MrPetovan** [comment]
More importantly, your domain is missing!

**Comment by zeroadam** [comment]
domain removed to keep the NSA away!

**Comment by AlfredSK** [comment]
I applied the changes in #4349 manually on my node because the GUI is corrupted and the bug fix isn't merged yet.
I'm still getting errors in FF web console...
```TypeError: $(...).perfectScrollbar is not a function ... main.js:170:3```

frio: The top menu on network page and home (profile/...) page is missing. Also the dropdown notification menu is empty.

**Comment by zeroadam** [comment]
Did you Ctrl f5 after applying the changes manually?

**Comment by AlfredSK** [comment]
Yes. I cleared the browser cache as well.

**Comment by MrPetovan** [comment]
It's not merged yet, that's why.

**Comment by AlfredSK** [comment]
> I applied the changes in #4349 manually

:-)

**Comment by zeroadam** [comment]
@alfredsk ok was just wondering

**Comment by MrPetovan** [comment]
I forgot a path element, the PR is updated, sorry for the inconvenience.

**Comment by AlfredSK** [comment]
Great! :-) I check again.

**Comment by AlfredSK** [comment]
Much better now. Works! 🥇
