### ISSUE TITLE
Don't allow following Twitter accounts until a personal account has been connected

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4362]
Discussion see this [thread in the support forum](https://forum.friendi.ca/display/39bbe52a115a7089960ae56366284075)

**Comment by zeroadam** [comment]
This is going to require checks from the main code to see if twitter addon is enabled and then basically disallow any @twitter.com or http(s)://twitter.com from Contacts:: is my assumption. There may not be any code changes to addons directly?

**Comment by MrPetovan** [comment]
It is more complicated than that. The problem arises when:
- The Twitter addon is enabled
- The current user didn't set up their personal Twitter account in their settings

In this case we accept the contact creation but the Twitter addon can't follow up with a follow on Twitter, which prevents any update to be retrieved.

The correct way to do it is to verify that the Twitter follow was successful before creating the contact, and show an error message if it wasn't.

**Comment by annando** [comment]
We call some ~~hook~~ addon for the twitter adding stuff. This thing could return some data if not enabled.

**Comment by MrPetovan** [comment]
The banned word is `plugin`, meanwhile `hook` is fine. 😛

**Comment by zeroadam** [comment]
🤣
