### ISSUE TITLE
Notification for Forum postings not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4368]
I have activated "send notification on new postings" for the support
forum, but since some days this option seems not to work for new postings
where the forum is mentioned with the @-name syntax.

I get notification for direct wall postings and ones using the !-name syntax.

**Comment by annando** [comment]
The ones with the ```@``` may or may not work. This depends if the post was delivered by the forum or the sender. This is why the ```!``` was invented. There the delivery path is reliable.

**Comment by tobiasd** [comment]
On Wed, 31 Jan 2018 01:29:11 -0800
Michael Vogel <notifications@github.com> wrote:

> The ones with the ```@``` may or may not work. This depends if the
> post was delivered by the forum or the sender. This is why the ```!
> ``` was invented. There the delivery path is reliable.

As I see it, this is a problem with the notification system. It should
send me a notification regardless of @name or !name is used to address
the forum. Or make ! the only way it is possible at all to address a
forum.

**Comment by annando** [comment]
The notification system works with the contact that owns the post. When using "wall-to-wall" or ```!``` the owner is reliably the forum. When using ```@``` it *can* happen that the owner is the original poster or the forum - this depends whose delivery chain is faster and if the receiver follows the user and/or the forum.

This is not a problem of the notification system.

**Comment by tobiasd** [comment]
> This is not a problem of the notification system.

looks like a wontfix then, ergo I close this issue as the system behaves as expected.

**Comment by annando** [comment]
Problem is also that we cannot suppress using the ```@``` to address the forum, since there could be forums that are used like hashtags on other systems. There the behavior would be okay.
