### ISSUE TITLE
Only import OStatus conversations started by our contacts not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4369]
So unwanted threads are imported. Some where contacts comment on, some
they only like (I know, both is simply an activity so both trigger this
bug.)

**Comment by annando** [comment]
If this now happens again, please have a look for the item uri in the logfile. You should see log lines like these:
* ```Item with uri ... belongs to parent .... It will be imported.```
* ```tem with uri ... belongs to a contact (...). It will be imported.```
* ```Item with uri ... will be imported since the thread contains posts or shares.```
* ```Item with uri ... will be imported due to the system settings.```

**Comment by tobiasd** [comment]
I will try to remember.

**Comment by annando** [comment]
@tobiasd had it happened again?

**Comment by tobiasd** [comment]
Yes, from a contact I'm only sharing with who got replies from some contacts I follow. I'll try to fetch the other information.

**Comment by tobiasd** [comment]
Here they are

    belongs to a contact (nnn). It will be imported.
    will be imported since the thread contains posts or shares.
    for user N stored.

So, pubsubhub feed from Contact B, I'm following, arrives with reply to Contact A, whom I just share with, leads to import of thread of Contact A.

**Comment by tobiasd** [comment]
Sorry, should have use the same placeholder. It's Follower A.

Yes, it is all for one uri. The thread in the log file that involved the wrongly imported GNU social thread.

**Comment by tobiasd** [comment]
yes

**Comment by annando** [comment]
Okay, then I found a possible weakness in the code.

**Comment by annando** [comment]
Could you check it again?

**Comment by tobiasd** [comment]
Yes, I keep my eye open.

**Comment by tobiasd** [comment]
I have not seen this in the last couple days, so I'm closing this issue.

**Comment by hoergen** [comment]
Still getting commented posts from pleroma

**Comment by annando** [comment]
Look for the logfile entries that I mentioned above.

**Comment by hoergen** [comment]
I only see Worker Messages. Which level should i configure the log? I configured it now to "normal"

**Comment by annando** [comment]
When you only see worker messages then the file permissions for the logfile don't fit to the frontend user. Please adjust this. Then set the loglevel to "debug". After this we will see.

**Comment by hoergen** [comment]
Ok I have those entries. For example

> note belongs to a contact (16375). It will be imported.

**Comment by annando** [comment]
you could call https://server.tld/contacts/16375 - (replace "server.tld" with your hostname). Then you will see the contact. This should be a contact that you are following.

**Comment by hoergen** [comment]
I know I can see who that is, but how does that help?
Acutally it still imports conversations not raised and only commented by my contacts. for example this one (some minutes ago) - red dot is my contact

![00_temp](https://user-images.githubusercontent.com/24474762/37683332-9668f0ae-2c8c-11e8-8f87-74bb6df74a0c.jpg)

**Comment by annando** [comment]
It is important seeing the logfile entries for this thread. There we will see the reason why it was imported.

**Comment by hoergen** [comment]
I can't find it any more the only thing i find is 
`DiscoverPoCo.php:190:discoverUsers     Check profile https://pleroma.soykaf.com/users/SarcasmKid`

Will search for another occurence

**Comment by hoergen** [comment]
Here I have one from Mastodon. I'm not following this user
https://horche.demkontinuum.de/display/52acf9cdc6a3fb0c1d6da2f2dc2e0cf7d095667c

I'm not sure to put the log file in here because of privacy?

**Comment by tobiasd** [comment]
Just send @annando a private message on Friendica

**Comment by hoergen** [comment]
Ok, @annando helped me to find the wrong configuration. I was a little missleaded by leaving a check empty under https://<friendica-site>/admin/site/   "Nur OStatus Konversationen unserer Kontakte importieren" 

Because I thought "less checked = less imports" ;)

**Comment by MrPetovan** [comment]
With pleasure!
