### ISSUE TITLE
Don't get twitter to work

### ISSUE THREAD

**Issue by templis** [friendica/friendica#4409]
Hey there,

I have problems to get the Twitter connector to work.
I have the Twitter app on twitter installed and configured - On friendica I fill in my Twitter Consumer Key and Secret, but in User Settings the oauth button is "empty" and leads to: 'https://api.twitter.com/oauth/authorize?' <- here it should stand more

I've also tried to set the variable in .htconfig like before I've updated to developer build of friendica.

I don't get any errors until I update my Profile with empty PIN. Then I get a http 500:
```
2018/02/07 02:27:55 [error] 1227#1227: *9641 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Ungültiges Anfrage-Token. in /var/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:137
Stack trace:
#0 /var/www/friendica/addon/twitter/twitter.php(233): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
#1 /var/www/friendica/src/Core/Addon.php(245): twitter_settings_post(Object(Friendica\App), Array)
#2 /var/www/friendica/src/Core/Addon.php(223): Friendica\Core\Addon::callSingleHook(Object(Friendica\App), 'connector_setti...', Array, Array)
#3 /var/www/friendica/mod/settings.php(288): Friendica\Core\Addon::callHooks('connector_setti...', Array)
#4 /var/www/friendica/index.php(346): settings_post(Object(Friendica\App))
#5 {main}

```
Can You help me to debug this?
I think, it don't send my consumer key and consumer secret settings to abraham\twitterOUth

**Comment by MrPetovan** [comment]
Thanks for reporting the issue, it seems we have to improve error catching.

Can you disable the Twitter addon in the mean time?
