### ISSUE TITLE
frio: Unicode/UTF8 issues on .../?tab=profile

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4412]
Since the last pull from develop the profile page https://domain.tld/profile/user/?tab=profile has encoding issues.

PersÃ¶nliche Notizen   (Persönliche...)
Ãœber:   (Über:)

I only get this with frio. With vier everything is well.
Maybe related to the membersince update?

**Comment by MrPetovan** [comment]
It is extremely likely: http://php.net/manual/fr/domdocument.savehtml.php#119813

**Comment by MrPetovan** [comment]
Triggered by https://github.com/friendica/friendica-addons/pull/519

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/520

**Comment by tobiasd** [comment]
> I only get this with frio. With vier everything is well.

It looks ok here. But I don't have membersince activated.

After enabling membersince there was no change. Maybe some Browser setting different from UTF?

**Comment by MrPetovan** [comment]
@tobiasd You're late to the party, we found the issue and fixed it in the meantime 😛

**Comment by tobiasd** [comment]
> we found the issue and fixed it in the meantime 😛

great!

**Comment by MrPetovan** [comment]
There’s a new issue with the latest change: https://friendica.mrpetovan.com/display/adf174d5175a7b3534f4227739914130

**Comment by MrPetovan** [comment]
Worked around by #4432

Please disable the addon and enable the additionnal feature instead.
