### ISSUE TITLE
frio: no login button on public page

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4431]
I'm missing the login button on the public page of frio.
![00_temp](https://user-images.githubusercontent.com/24474762/36017629-d8ad4aec-0d78-11e8-94e4-0eba32088ab1.jpg)

**Comment by AlfredSK** [comment]
See PR  #4421 :-)

**Comment by MrPetovan** [comment]
Closing via https://github.com/friendica/friendica-addons/pull/530
