### ISSUE TITLE
Diaspora compatiblity: citing quote; font-size

### ISSUE THREAD

**Issue by DeusFigendi** [friendica/friendica#4445]
I just began to write some postings on friendica and learn the bb-syntax and check how this looks on diaspora. So I found some problems how this code is converted before federating to diaspora.

### Quote with Author:

In Friendica I write

```bbcode
[quote=Testauthor]Content[/quote]
```
Renders to HTML
```html
<strong class="author">Testauthor hat geschrieben:</strong><blockquote>Content</blockquote>
```

Markdown sent to diaspora:

```markdown
**Testauthor wrote:**> Content\n
```
There is a `\n`ewline missing before the `>` I'd say! The might be caused because `<blockquote>` is a blockelement and doesn't need a `<br/>`reakeline.

### font-size

In Friendika I write

```bb-code
[size=xx-small]Small text[/size]
```

This renders to HTML:
```html
<span style="font-size: xx-small; line-height: initial;">Small text</span>
```

And this HTML is exactly sent to diaspora.

**Once** diaspora understood `<small>` if I remember correctly. But it doesn't today. But it never supported `<span>` I think. If I want to write something small in diaspora I use `<sub>` or `<sup>`

So when I write in diaspora
```markdown
<small>small</small><sup>sup</sup>
```

It renders to
```html
&lt;small&gt;small&lt;/small&gt;<sup>sup</sup>

in desktop-view and

smallsup

in mobile-view
```

Friendica shows me
```html
<span style="font-size: small; line-height: initial;">small</span>sup
```

But I don't know **where** to fix this, this is propably a diaspora issue (when it escapes/strips the html itself it should also federate escaped/striped html I'd say).

**Comment by DeusFigendi** [comment]
Ah okay the problem with mobile/desktop on diaspora is known allready: https://github.com/diaspora/diaspora/issues/7658

**Comment by MrPetovan** [comment]
Hey @DeusFigendi, thanks for opening an issue.

For the quote, you are probably right. We should add a newline before the quote.

For the font-size, Friendica's BBCodes don't include `sup`, so it won't be picked up on Friendica display.

**Comment by DeusFigendi** [comment]
> For the font-size, Friendica's BBCodes don't include sup, so it won't be picked up on Friendica display.

I thought so but sending that inline-CSS in a span is bad too. Maybe it's a better idea to strip it completely.

replace it by `<sup>` when sending/federating (not on receive) would be cool but complicated because it depends on the value of "size" what to send.

**Comment by MrPetovan** [comment]
Unfortunately, `<sup>` and `<sub>` have specific meanings that aren't limited to a smaller font-size so I wouldn't use them as such.

I'm slightly confused about what you are expecting from the BBCode <-> HTML <-> Markdown conversion, can you provide actual posts showing display discrepancies and precise the conversion direction?

**Comment by AlfredSK** [comment]
Here is a related issue I opened on Christmas 2015. :-)
#2199

**Comment by annando** [comment]
We are using this way: BBCode => HTML => Markdown

The problem with the HTML2Markdown-Library is that Markdown doesn't seem to be really standardized concerning the handling of inline HTML. Knowing specific problems we can always try to improve it. But I'm with @MrPetovan concerning ```<sub>``` and ```<sup>```: They are meant for other things.

**Comment by DeusFigendi** [comment]
> Unfortunately, <sup> and <sub> have specific meanings that aren't limited to a smaller font-size so I wouldn't use them as such.

I agree, I just said it would be nice but in the end it's bad semantic. (I use this, but I am not happy with this)
Still: Stripping the HTML would be fine.

> Markdown doesn't seem to be really standardized concerning the handling of inline HTML

Yes indeed, afaik diaspora **wants** to follow http://commonmark.org/ but in the end it also depends on the used libraries.

**Comment by annando** [comment]
We have to check whether our Markdown parser does allow this stripping.

**Comment by MrPetovan** [comment]
Markdown is supposed to output HTML tags as-is, including `<span>` tags, but if we at some point escape the HTML entities like `<` and `>` then Markdown would respect them and display them as literal instead of HTML tags.

**Comment by DeusFigendi** [comment]
Okay, maybe I've been a little hastely with my sugestions about the size-thingy.

Following the specs the [diaspora-federation-protocol](https://diaspora.github.io/diaspora_federation/federation/types.html#markdown) says:

> Text formatted with markdown using the CommonMark spec.

And the [CommonMark spec says about raw HTML](http://spec.commonmark.org/0.28/#raw-html)

> Text between \< and \> that looks like an HTML tag is parsed as a raw HTML tag and will be rendered in HTML without escaping. Tag and attribute names are not limited to current HTML tags, so custom tags (…) may be used.

So friendica is doing this right at the moment and diaspora is parsing it wrong or it has to change its definition of "markdown" (for example excluding or including a set of html-elements so one can program against this spec).
Since other software should and will also follow the protocol spec and not any common practice.

So I'd say @MrPetovan is totally right on his first statements:

> For the quote, you are probably right. We should add a newline before the quote.

and about the font-size just keep it as it is, since it's spec conform.
