### ISSUE TITLE
upload photo and don't work. Like permission denied

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4448]
Hi guys

FIrst thank you for the good program i like it but i was maybe 2 days to install friendica include it don't work and it is product version. Now first there was issue with database the known for the developers " FILE table is too high " so i have to change it to utf8 utf8mb4 is not working.

Now when i try to upload photos it comment uploading and then white screen this can be permission denied but where and what permissions to work. Now developers make friendica to have everything in friendica directory and not to be in all hard disk, becouse this problem is permission denied, if friendica has all in one directory there will be no problem with permission denied.

**Comment by gurussia** [comment]
update 1: MySql/MariaDB issue: Error 1709: Index column size too large. The maximum column size is 767 bytes

**Comment by gurussia** [comment]
update 2: here is temporally solution: https://bgzashtita.es/git/peturbg/mysql/commit/4babcc96ed0f152c22b0303e4af7e4e908e447df

**Comment by annando** [comment]
Which version of MySQL or MariaDB are you using? Are you using InnoDB?

**Comment by annando** [comment]
A white screen mostly occurs with PHP errors. So please activate the PHP error logging (in your php.ini) and look for errors there.

**Comment by annando** [comment]
Since there had been no more explanations to this issue, I will close it now.
