### ISSUE TITLE
HTTP status 500 when delivering to pirati.ca

### ISSUE THREAD

**Issue by git-marijus** [friendica/friendica#4450]
This might be an obscure bug or a result of a bug already fixed or something else:
when i send a comment to heluecht@pirati.ca from mario@hub.somaton.com, pirati.ca answers with status 500. This does not appear to happen with other channels or other instances.

Can someone possibly explain what might be going on here?

**Comment by MrPetovan** [comment]
Hi @git-marijus, I believe @annando can have access to the error log on https://pirati.ca

**Comment by annando** [comment]
Please come with an exact date and (UTC) time, then I can have a look. Please consider that my logs are only held for 3 days with anonymous IP addresses.

**Comment by git-marijus** [comment]
Here you go:
```
2018-02-14T13:31:17Z:LOG_INFO::network.php:356:z_post_url: z_post_url: error: https://pirati.ca/receive/users/0704b08f5c777566: 
2018-02-14T13:31:17Z:LOG_INFO::network.php:357:z_post_url: z_post_url: debug: Array
(
    [url] => https://pirati.ca/receive/users/0704b08f5c777566
    [content_type] => text/html; charset=UTF-8
    [http_code] => 500
    [header_size] => 267
    [request_size] => 198
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.269837
    [namelookup_time] => 0.012442
    [connect_time] => 0.037171
    [pretransfer_time] => 0.132836
    [size_upload] => 3916
    [size_download] => 107
    [speed_download] => 397
    [speed_upload] => 14557
    [download_content_length] => -1
    [upload_content_length] => 3916
    [starttransfer_time] => 0.158799
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => xxx.xxx.xxx.xxx
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => xxx.xxx.xxx.xxx
    [local_port] => xxxxxxx
    [request_header] => POST /receive/users/0704b08f5c777566 HTTP/1.1
Host: pirati.ca
User-Agent: Mozilla/5.0 (compatible; zot)
Accept: */*
Content-type: application/json
Content-Length: 3916
Expect: 100-continue


)
```

**Comment by annando** [comment]
I had massive delivery problems with your account, so my system set your account to "archive". Until then we hadn't accepted any content anymore. This is now changed.

Thanks for the report!

**Comment by MrPetovan** [comment]
Closed via #4457

**Comment by git-marijus** [comment]
I see... I had some extended downtime in december and during last summer probably thats why...
I wonder why status 500 though...

**Comment by annando** [comment]
Maybe 403 would be better in that case.

**Comment by AlfredSK** [comment]
I see in _my_ server logs that hub.somaton.com has a network timeout setting of 4 seconds. I don't know whether that is true or not but sometimes I get those timeouts after 4 seconds.
Maybe that leads to some delivery issues.

**Comment by git-marijus** [comment]
AFAIK the timeout is set to 60 seconds. For PHP and curl. Not sure about nginx but 4 seconds seems strange. I will investigate...
