### ISSUE TITLE
php7.2 include/poller.php

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4452]
hi guys when php7.2 is activated it comment this error.:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in include/poller.php on line 721
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
include/poller.php on line 733
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
include/poller.php on line 748

But it is currious when, php7.1 is activated it just work with php7.1, but if php7.2 is activated and only use php7.1 for cron it again comment: Parameter must be an array or an object that implements Countable in

but if php7.1 is acivated and use cron php7.1 it works. Please guys repair it, php7.2 is more fast, include i use production version but it is old, if it install development version and git pull when new things are avaible is it gonna work in production machine.

And is there some facebook api.

Thanks guys

**Comment by MrPetovan** [comment]
The warnings come from a version that's very far from the current `develop` version, they should translate to 
- https://github.com/friendica/friendica/blob/develop/src/Core/Worker.php#L786
- https://github.com/friendica/friendica/blob/develop/src/Core/Worker.php#L802
- https://github.com/friendica/friendica/blob/develop/src/Core/Worker.php#L821

All three results from an array variable that's not been instantiated beforehand.

**Comment by MrPetovan** [comment]
Related to #4443

**Comment by gurussia** [comment]
MrPetovan  in the moment i'm not developer. So in simple languages what it the command to solve it.

Thanks.

**Comment by MrPetovan** [comment]
At the moment please use PHP 7.1 to prevent the messages. Since they aren't Fatal Error, you should be able to use Friendica normally. We will fix the Warning in the coming days on the `develop` branch, if you want to stay on the `master` stable branch you will have to wait for the upcoming release.

**Comment by gurussia** [comment]
how much is danger developer version, for example if developer version is intalled in production computer what can happend.

**Comment by gurussia** [comment]
what i don't understand is. When i use php7.1 it poller.php without errors, but when i activate php7.2 and run it with php7.1 it comment  PHP Warning: count(): Parameter must be an array or an object that implements Countable in include/poller.php

So in php there can be automatic mode, if i imagine it mean, that if you activate php7.1 and php7.2 then it automatically can get version that work. For example: if php7.2 don't have mcrypt then it can get it from php7.1. So is there solution to make it work in automatic mode.

**Comment by annando** [comment]
You have two options:

1. Use PHP 7.1 until the new release is coming. I hope that the new release will be available at least in spring.
2. Use the "develop" branch: The current develop branch however can be unstable. And it could be more work keeping it running.

Means: Are you good at server administration? Do you know where the configuration files on your server are, what they mean and do you know ```less```, ```tail``` and ```git```? If yes: Choose the second option.

**Comment by MrPetovan** [comment]
The `develop` version can leave your Friendica node inaccessible for hours at a time. We tend to fix fatal errors under 24 hours but if your update schedule is longer than that, your node can be unavailable for a while if you get unlucky and update during the break period.

Many nodes already run on the `develop` branch with a regular update task, but you can also be selective in which commit you want to update to.

**Comment by gurussia** [comment]
thanks guys really help. If i have time and if i remember maybe i will use developer but maybe with fear, becouse  maybe it can leaks data, so guys can you comment if someone install developer edition is it gonna leaks data from stable.

**Comment by MrPetovan** [comment]
There's no particular danger to leak data. On the contrary, when Friendica is broken on `develop`, nobody can access your data, not even yourself!

**Comment by MrPetovan** [comment]
That said, I don't recommend using Friendica for legally-sensitive data. While we have some security features for data transport between decentralized networks servers, the whole database is in plain text (except for passwords) and we haven't performed a formal penetration audit on the current state of the software.

**Comment by gurussia** [comment]
Thanks you. That say. you can leave this topic pending and when php7.2 is release to try someone again and comment if this gonna work. and again thanks.

**Comment by MrPetovan** [comment]
We will fix the problem in the coming days, so this issue will be closed, however you will have to wait for the upcoming release if you decide to stay on the stable channel.

**Comment by gurussia** [comment]
did you solve php7.2 issue

**Comment by MrPetovan** [comment]
Yes I did, it is expected to be merged on the `develop` branch as promised. Here's the relevant pull request: #4455

**Comment by gurussia** [comment]
Guys you are wonderfull... Can you comment me how to make it work in stable version.

**Comment by MrPetovan** [comment]
If you are able to edit files your server, you can add `$ids = [];` here:
https://github.com/friendica/friendica/blob/master/include/poller.php#L710

**Comment by gurussia** [comment]
Thanks guys it works good
