### ISSUE TITLE
www-data: how to change from who send e-mail for registration, notification and etc. 

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4476]
Hi guys.
friendica is sending from www-data and it prohibite/forbid other e-mail server to pass in inbox to other e-mail servers. So where it has to be edit so it can generate ot make it be from be from po@yourmain.com.

**Comment by annando** [comment]
There is a setting in the admin interface that defines the name of the sender.

**Comment by MrPetovan** [comment]
What about the sender address?

**Comment by gurussia** [comment]
setting in the admin interface, you mean plugin " becouse i found plugi and it has person who to send, but again it send from www-data

**Comment by tobiasd** [comment]
No, in the site configuration in the admin panel. `example.com/admin/site/` in the upper most block. You first set the site and domain name, and the 3rd option defines the email address that is used to send out notifications.

**Comment by gurussia** [comment]
No it don't work, again it comment www-data

**Comment by annando** [comment]
It is a difference which account is sending the mail and which sender it uses. The account is defined in your PHP settings concerning mails.

**Comment by gurussia** [comment]
thanks guys. can someone comment what directory and what files are needed.

**Comment by annando** [comment]
The way your system sends mails is defined in your php.ini. So please consult the PHP documentation for details.

**Comment by gurussia** [comment]
annando false i was loolking /etc/php/ and change there from who to send e-mail is dangerous. There is applications where they smailend from correct persopn or system. So change friendica to can send from user or from yourmain.com.

**Comment by MrPetovan** [comment]
I can think of three possible sending parameters:
- The sender name, it is your instance name, first setting in `/admin/site/`.
- The sender address, third setting in `/admin/site/`, defaults to `noreply@yourdomain.com`, `yourdomain.com` is the second setting in `/admin/site/`.
- The system user sending emails, it's going to be the user running the web server/backend process/thread.

You already can change the first two from Friendica, the third depends on your server's configuration.

How mails are sent after that is out of the scope of the Friendica project. We rely on the PHP `mail()` command to send mail, please check [the PHP manual page for `mail()`](http://php.net/manual/ru/function.mail.php).

**Comment by gurussia** [comment]
strange. If i send e-mail directly from mail it send e-mail from the user and this mean, message is not spam for the other servers. But for some unknown reason, friendica use www-data, why then friendica php use www-data for mail, when other php mail use other user

**Comment by gurussia** [comment]
update 1: from The sender name, it is your instance name, first setting in /admin/site/. It change to user@yourdomain.com, it save include it comment php -f scripts/workers.php and dbstructure.php and again e-mail is comming from www-data

**Comment by MrPetovan** [comment]
>  If i send e-mail directly from mail it send e-mail from the user and this mean, message is not spam for the other servers. But for some unknown reason, friendica use www-data, why then friendica php use www-data for mail, when other php mail use other user

Are you logged in as `www-data` when you test the `mail()` function? PHP sends mail through the current user, and Friendica is ran by the web server user, and on your server it is `www-data`.

**Comment by MrPetovan** [comment]
> But it is unknown, what you mean third setting in /admin/site, in third setting there is Sender Email and it is changed to user, and again it send e-mail from www-data

Can you provide the email headers for e-mails sent with `www-data` that are considered as spam?

**Comment by annando** [comment]
There had been no further answer, so this issue is now closed.
