### ISSUE TITLE
Solved: friendica stable, don't receive messages from contacts.

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4478]
In friendica it don't receive messages from contacts and from e-mail it comment there is messages, include this messages are not in friendica messages like dissapeared " nobody delete, clean them " in mysql new messages are there, so how to make messages from mysql come to friendica.

**Comment by gurussia** [comment]
update 1: I try send email and he comment he recieve the e-mail that i send him message to friendica descentralizaed network but in his user he didn't receive it. what has to be updated to recover his messages.

**Comment by tobiasd** [comment]
Can you have a look at the initial description of issue #1900 ? It is one of the issues that are addresses in the upcoming release and the email contact handling got some improvements already in the `development` branch.

**Comment by gurussia** [comment]
is it possible to get from developer and make it work in stable.

**Comment by MrPetovan** [comment]
Yes, it will be included in the next release, although we don't have a date yet.

**Comment by MrPetovan** [comment]
I'm confused about your issue now, can you describe what "message" is to you? Is it a post, is it an email, is it a private message in Friendica ?

**Comment by gurussia** [comment]
from stable it installed developer version and too again when someone send post message, send message from friendica to friendica it don't arrive. Messages are in mysql, include it arrive e-mail that person has send message but the messages are not in friendica, messages are in mysql. it is like friendica can't see messages, only mysql are see messages.

**Comment by gurussia** [comment]
Now, this is bad. friendica developers need to make it automatic process, if someone install friendica on server and after that it move to another server with the same database min. messages will from friendica users will stop work. If someone send you message it will not display on your message and it will send you notification there is message but in friendica user message there will no message.

So to be solved: Every user in yourdomain.com has to do manual: Settings > profile > relocate

So if you have 30 users and some of them don't know what to do, they will complain. So this process need to be automatic

**Comment by annando** [comment]
At the bottom of the page /admin/site/ the administrator can perform a relocation to a new host name for all of his (or her) users.

**Comment by gurussia** [comment]
annando the other day that i start issue is becouse i try it and it didn't work. What work is the latest i write, it has to be maked manual by every user... And you read what will happend if you have 30 users, include annando remember Mastodon has min. 4xx users, so do you imagine every person from 4xx to make it manual relocation.

**Comment by annando** [comment]
BTW: The protocol that Mastodon uses doesn't support relocation. Means: If you are in contact with users from OStatus based networks (GNU Social, Mastodon, Pleroma) then the relocation is not processed. This is a limitation of these systems, not of Friendica.

**Comment by gurussia** [comment]
annando it was only example. It is sure there is friendica that has 3xx users, do you imagina 3xx friendica users to manually relocate they messages.

**Comment by annando** [comment]
Like I said: The functionality to move the whole system does exist. We had tested it for the master branch and it worked. So when it hadn't worked now, we need a detailled error description what you had done, what you expected should be the result and what happened instead. Especially if there had been error messages, we really need the message text, so that we can check where the message was raised. Even if the message wasn't in english, an **exact copy** of the text will help since then we can search for the translation string.

Since you reported some issues, I really recommend that you enable the friendica log file in the debug level (don't forget to activate some log rotate on your system) and to enable the PHP error logging.

**Comment by gurussia** [comment]
Like I said: if someone move friendica from one server to another server and restore friendica, the same 100 % exact copy, messages will not be displayed when someone send messages to other, when friendica was moved from old to new server. With relocating, every user had to press relocating, but imagine if they are 3xx users, imagine every 3xx users pressing relocate... if there are old years peoples they will not press relocate... include they can damage they profile. So system relocate is needed.

I just remember message was simply . yes one simply . " dot" and messages in fiendica didn't was there. Messages was in mysql, include e-mail was generated that mail was send from one user to other user. And for this peoples who gonna comment " some times only . can have issue " No they are wrong, after only . user send some more messages and the same. Now it update to developer branch and again messages didn't appeared, so relocate has been pressed. Include now it comment issue: php scripts/worker.php 
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/etc/friendica/include/dba.php on line 969

It was open issue, but Petovan close it: https://github.com/friendica/friendica/issues/4482

**Comment by MrPetovan** [comment]
There already is a system relocation feature, if it doesn't work, we'll need more info to fix it because we tested it ourselves successfully. You can't just move the files and the database because we make heavy use of the hostname in all communication.

I closed the other issue because it was a duplicate, when did the warning appears in your log? What was the action you did?

**Comment by annando** [comment]
Since there had been no further answer, this issue is now closed.
