### ISSUE TITLE
stable version to developer version:  Parameter must be an array or an object that implements Countable in dba.php on line 969

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4482]
php scripts/worker.php 
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/etc/friendica/include/dba.php on line 969

/var/etc/html/friendica# PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/etc/friendica/include/dba.php on line 969

**Comment by MrPetovan** [comment]
Duplicate of #4478, please keep commenting in the original issue.
