### ISSUE TITLE
Community pages identical

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4495]
With the community page set to "No community page" the generated pages for the local and global community are identical, only consisting of public local postings.

@annando sais he had an idea, but then the Squirrel(TM) hit.

**Comment by annando** [comment]
There are rules that decide if a post is visible on the global community page: https://github.com/friendica/friendica/blob/develop/src/Model/Item.php#L865-L881

In fact the the "no community page" setting doesn't change this behaviour, it is the "hide-friends" setting and the setting if a contact is hidden or blocked.

We could discuss if we could lower these checks.

**Comment by tobiasd** [comment]
To be honest, I still tink "No community page" should be no, and there is a missing "No public community page" setting.

But I think when it depends on the hidden-contact status, then it is more a missing documentation issue for the setting. Could you add it to the `Settings.md` files below the "Block public" paragraph.
