### ISSUE TITLE
Multiline code blocks display problem

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4496]
When a code block is used around a commonly used configuration notation containing square brackets, the BBCode parser removes the line feeds.

Excample

    [config section]
    something = someValue

results in

    [config section]something = someValue

This also suffered from the Squiirel(TM)

**Comment by MrPetovan** [comment]
I believe this would be covered by #4488.

**Comment by tobiasd** [comment]
This issue seems to be fixed, so I'll close it.

**Comment by MrPetovan** [comment]
I believe it was fixed by #5765
