### ISSUE TITLE
Superblock: Getting comments from superblocked profiles under posts from contacts

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4507]
Hello,
I use the superblock add-on to block comments of some non-contacts. It worked reliably for a long time. Unfortunately, it has not been reliable for a few weeks now. I see a lot of comments from superblocked people lately. My superblock list mainly contains Diaspora profile URLs.
Is there something I can provide here to find the cause?

**Comment by MrPetovan** [comment]
From what I see in the code, superblock only blocks notifications, so it would make sense if you still see the posts.

**Comment by hoergen** [comment]
I think it works, if you just use the domain name instead of protokoll://domainname

so: https://shitposter.club doesn't work for non-contacts
but: shitposter.club will be blocked

Maybe the plugin should remove any  "protocol" when saving the string.

Tried it now for two days

**Comment by AlfredSK** [comment]
@hoergen You speak about the server blocklist, don't you? Superblock is an add-on for users. Not an admin setting. And it clearly states to add "profile URLs".

@MrPetovan No. Superblock blocks everything. Superblock should completely remove all posts and comments from the view of the user. At least that is what it should do and what it did in the past.

**Comment by MrPetovan** [comment]
Ha, nevermind, most of what the addon do is editing a PConfig value and I thought it was specific to the addon, but no, it exists in the main Friendica code and isn't used except for the addon. Talk about feature creep... 🙄

Simply put, to block an item it checks the `author-link` field against the `[local_user()]['system']['blocked']` pconfig value after splitting the string into an array based on commas.

To debug this, you can provide the DB value of ``SELECT `val` FROM pconfig WHERE `cat` = 'system' AND `k` = 'blocked' AND `uid` = [Your user Id]``  and the DB value of ``SELECT `author-link` FROM `item` WHERE `guid` = '[offending item guid']'``

**Comment by AlfredSK** [comment]
I will do so tomorrow morning. Have an appointment now. :-)

**Comment by AlfredSK** [comment]
```SELECT `v` FROM pconfig WHERE `cat` = 'system' AND `k` = 'blocked' AND `uid` = 2;```

`https://diasp.org/u/grok, https://nerdpol.ch/u/traumatizer, https://pod.dapor.net/u/rss_nsfw, https://diasp.eu/u/obito, https://joindiaspora.com/u/harigwebikemegiddo, https://diasp.de/u/plage, https://joindiaspora.com/u/nohopeone, https://joindiaspora.com/u/schestowitz, https://joindiaspora.com/u/mediaservice, https://pod.jns.im/u/foxnews, https://diaspora.gianforte.org/u/theaitetos, https://joindiaspora.com/u/lorraine_1_norse, https://joindiaspora.com/u/echpolryn, https://joindiaspora.com/u/nintenth, https://pod.ponk.pink/u/harigwebikemegiddo, https://diasporabrazil.org/u/ben_senmedo, https://nerdpol.ch/u/werhier, `

```SELECT `author-link` FROM `item` WHERE `guid` = 'e12cd5a0fe480135bc6c2b296c4bcbbf';```

```+---------------------------------------------+
| author-link                                 |
+---------------------------------------------+
| https://diaspora.gianforte.org/u/theaitetos |
| https://diaspora.gianforte.org/u/theaitetos |
| https://diaspora.gianforte.org/u/theaitetos |
+---------------------------------------------+
3 rows in set (0.00 sec)```

Hello

**Comment by MrPetovan** [comment]
Please try to remove the spaces in the config value. If it effectively blocks the posts, we need to trim the values after splitting on commas.

**Comment by AlfredSK** [comment]
I'm pretty sure I tried that already. But I'll test it again now...
And you are sure the delimiter is still a comma and not a newline? ;-)

**Comment by MrPetovan** [comment]
It is a comma, but we already are trimming the values.

https://github.com/friendica/friendica/blob/26c1926f1f1eaced87096f879842e43546e626f0/include/conversation.php#L512-L514

Not sure what's the problem then.

**Comment by AlfredSK** [comment]
It's not that easy to test something that is not there if everything works. :-)
Is it not there because it works or because the blocked accounts don't post/comment anything? Hmm.

I deleted all entries from superblock and watched the community page. Then I did the same with the all the entries in superblock.
Looks like posts on community page are blocked successfully. I don't see anything from blocked profiles there. I also don't get any public posts via tags in my network stream. Seems to work!

So, superblock is working in general. But there is one remaining problem. I still get comments from superblocked profiles under posts from contacts.

**Comment by annando** [comment]
Please check under which exact circumstances these comments still appear. Is it on /network or /display? Or /community? Or all of these?

**Comment by AlfredSK** [comment]
All of these. :) I found comments of superblocked profiles on all three pages. And I just discovered one case where a superblocked user's comment was visible under a post of a stranger/non-contrac. So, it looks like superblock doesn't work on comments at all. (It works reliably on posts).

**Comment by MrPetovan** [comment]
I believe it's time to retire superblock and implement a blocking mechanism in core. Not this release, of course, but it's something we should think about.

**Comment by annando** [comment]
The weird thing about "superblock" is that it is one of these addons where the whole functionality is in the core and everything the addon was doing is to provide the settings interface.

But yeah: We need a better blocking mechanism that replaces the various addons.
