### ISSUE TITLE
Network items display doesn't update after interaction

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4508]
After today's merges, the `network` page on the `posted last` doesn't show comments/likes at all. I commented on a Mastodon status, and the `update_network` call returned nothing when I submitted my comment. However, the comment appears on the `display` view .

![network-missing-comment](https://user-images.githubusercontent.com/925415/36710242-a18b01aa-1b4a-11e8-90bb-1f03e5253699.png)
![network-missing-comment2](https://user-images.githubusercontent.com/925415/36710243-a19dc010-1b4a-11e8-82e5-a873ac541403.png)
Reference URL: https://friendica.mrpetovan.com/display/949f3b5f518f9b85dadebdbf4e612ec0f416a278

The PR culprit might be #4500 or #4501

**Comment by annando** [comment]
Should be fixed by https://github.com/friendica/friendica/pull/4509

**Comment by MrPetovan** [comment]
Just pulled, tried to like an item, the update_network ran without errors but was empty, post wasn't updated. Reloading the `network` page didn't help. Single post `display` page stays correct.

**Comment by annando** [comment]
Did commenting work?

**Comment by MrPetovan** [comment]
Just tried, and it didn't show on the network page.

**Comment by MrPetovan** [comment]
Nevermind, I just pulled again and now it works again, thanks!

**Comment by MrPetovan** [comment]
Rectification, initial `network` page display now shows likes and comments, commenting updates the post display, but unliking doesn't. 🤔

**Comment by MrPetovan** [comment]
After #4514, the network display once more doesn’t update after any interaction.

**Comment by annando** [comment]
Refresh your browser cache. The Javascript had changed, but browsers are a little bit dumb.

**Comment by MrPetovan** [comment]
It seems to behave as expected now.
