### ISSUE TITLE
Performance: Postpone DB update in Contact::getIdForURL on display page

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4522]
With the rendertime addon activated, I'm seeing recurring calls to `dba::update` in a display page:
`/display`:
```
dba::update, Contact::getIdForURL, public_contact, builtin_activity_puller: 0.395
dba::update, Contact::getIdForURL, BBCode::Friendica\Content\Text\{closure}, preg_replace_callback: 0.355
```
`/network`:
```
dba::update, Item::update, networkSetSeen, networkThreadedView: 0.314
dba::update, Contact::getIdForURL, public_contact, builtin_activity_puller: 0.263
```
These update calls should be postponed to a cron execution as they are significantly slowing down the load of a simple display page.

**Comment by annando** [comment]
The ```networkSetSeen``` has to be just in time. It is important for the auto loading that only loads items that are unseen.

In ```getIdForURL``` we have to see whether there is always an update. Normally this should only occur upon changes.

**Comment by MrPetovan** [comment]
> The networkSetSeen has to be just in time. It is important for the auto loading that only loads items that are unseen.

Oh yeah, I just copied all the database write calls but it actually makes sense.

**Comment by MrPetovan** [comment]
> In getIdForURL we have to see whether there is always an update. Normally this should only occur upon changes.

Yes but in no cases the update should happen on display. If there are changes they can be postponed to a background task so that the page load doesn't randomly suffer from it.

**Comment by annando** [comment]
Problem is that putting something in the background needs some worker call - which will perform a write command as well.

**Comment by MrPetovan** [comment]
Yes but it's possible to have a smaller footprint than the whole `Network::probe` call and the big subsequent `contact` write.

**Comment by annando** [comment]
The probe is needed directly as return value of the function. But either the probe nor the update should be done with every call.
