### ISSUE TITLE
user not found on deleting a single user account

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4535]
Hello,
when I try to delete a single user account on .../admin/users by clicking the trash bin icon (vier) I get an error notification "User not found". The account is not deleted.
On the other hand when I select the account using the checkbox for multiple account deletions and I hit the "delete" button at the bottom of the page I get the notification "1 user deleted". The account is deleted successfully.

There are no interesting messages in Friendica log or PHP log. Well, I saw an error 500 but I don't know if it is related.

**Comment by annando** [comment]
Which version are you using? Dev, RC or Stable?

**Comment by AlfredSK** [comment]
I had this issue with develop and I have it with 3.6-RC as well.

**Comment by tobiasd** [comment]
Just for the record, I just had no problems with stable and that delete button. But can confirm the "User not found" issue on RC.

**Comment by MrPetovan** [comment]
I'm working on it.

**Comment by tobiasd** [comment]
Deletion works fine when marking only that one account and used the mass-deletion functionality.

**Comment by MrPetovan** [comment]
Closed via #4538
