### ISSUE TITLE
Cannot access frio theme settings when set as system theme

### ISSUE THREAD

**Issue by efelon** [friendica/friendica#4550]
Logged in as administrator and being in the admin menu; After selecting frio as the Default system theme, i cannot find the theme settings to define colors, background, etc. for not logged in users.

On the url .../admin/themes/frio it only shows the readme, but no settings.

Friendica: 3.5.4
PHP: 7.0
Nginx: latest on Raspbian Stretch

**Comment by rabuzarus** [comment]
This will be only possible with the upcoming Friendica 3.6.
