### ISSUE TITLE
communityhome test - possible issues (RC branch)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4555]
I'm testing communityhome add-on to find possible issues, db errors, php stuff. Here is what I found with all options enabled except 'hide login':

(1) On submitting the settings at .../admin/addons/communityhome I get a PHP warning.
`[06-Mar-2018 19:06:38 UTC] PHP Warning:  Missing argument 2 for communityhome_addon_admin_post(), called in /path/to/friendica/mod/admin.php on line 70 and defined in /path/to/friendica/addon/communityhome/communityhome.php on line 53`

(2) On logout from the node I get...
`2018-03-06T19:15:58Z@9beks0bh6isusuuv6u9rqi0u34      [NORMAL]:dba.php:479:p      DB Error 1146: Table 'friendicadb.con' doesn't exist`
Also throwing this query into the log...
````
q, communityhome_home, Addon::callHooks, home_content
SELECT `uni`.`contacts`,`uni`.`items`, `profile`.*, `profile`.`uid` AS `profile_uid`, `user`.`nickname` FROM (SELECT COUNT(*) as `contacts`, `uid` FROM `contact` WHERE `self`=0 GROUP BY `uid`) AS `con`, (SELECT COUNT(*) as `items`, `uid` FROM `item` WHERE `item`.`changed` > DATE(NOW() - INTERVAL 1 MONTH) AND `item`.`wall` = 1 GROUP BY `uid`) AS `ite`, ( SELECT `contacts`,`items`,`ite`.`uid` FROM `con` RIGHT OUTER JOIN `ite` ON `con`.`uid`=`ite`.`uid` UNION ALL SELECT `contacts`,`items`,`con`.`uid` FROM `con` LEFT OUTER JOIN `ite` ON `con`.`uid`=`ite`.`uid` ) AS `uni`, `user`, `profile` WHERE `uni`.`uid`=`user`.`uid` AND `uni`.`uid`=`profile`.`uid` AND `profile`.`publish`=1 GROUP BY `uid` ORDER BY `items` DESC,`contacts` DESC LIMIT 0,10
````

With '**Show last active users**' _disabled_ I don't get the DB error (2) but the PHP warning (1) remains.

I didn't notice any performance issues (just for the record).

**Comment by MrPetovan** [comment]
I'm not using this addon because I'm on a single-user node, I can try to fix the most obvious errors but I'm not sure what is the expected addon result/display in general.

**Comment by MrPetovan** [comment]
Look what I found next to the query you dug: `// this query don't work on some mysql versions`

No shit, Sherlock!

**Comment by annando** [comment]
I would like to remove that functionality for now, until someone tries to make it better.

**Comment by MrPetovan** [comment]
I'm not even sure what it is doing with the `a RIGHT OUTER JOIN b UNION ALL b LEFT OUTER JOIN a`. I'll remove it for now.

**Comment by MrPetovan** [comment]
Addon has been deprecated, offending SQL query has been removed.
