### ISSUE TITLE
Slow queries on notifications/network and notifications/personal

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4556]
I'm on 3.6-rc. When I go to .../notifications/network or .../notifications/personal the loading of the content takes up to one minute (sometimes even more). The other notification pages (system, home, intros) are very fast. The mysql slow queries log is showing a query time of 35.8 seconds for the network notifications...
```
# Time: 180306 21:39:23
# User@Host: blabla @ blablabla []
# Thread_id: 12184  Schema: friendica  QC_hit: No
# Query_time: 35.844912  Lock_time: 0.000081  Rows_sent: 0  Rows_examined: 256748
SET timestamp=1520368763;
SELECT `item`.`id`,`item`.`parent`, `item`.`verb`, `item`.`author-name`, `item`.`unseen`, `item`.`author-link`, `item`.`author-avatar`, `item`.`created`, `item`.`object` AS `object`, `pitem`.`author-name` AS `pname`, `pitem`.`author-link` AS `plink`, `pitem`.`guid` AS `pguid` FROM `item` INNER JOIN `item` AS `pitem` ON `pitem`.`id`=`item`.`parent` WHERE `item`.`visible` = 1 AND ( `item`.`author-link` regexp 'libranet\\.de/profile/alfred$' OR `item`.`tag` regexp 'libranet\\.de/profile/alfred\\]' OR `item`.`tag` regexp 'libranet\\.de/u/alfred\\]' ) AND `item`.`unseen` = 1 AND `item`.`deleted` = 0 AND `item`.`uid` = 2 AND `item`.`wall` = 0 ORDER BY `item`.`created` DESC LIMIT 0, 20;
```
When reloading the page the same query takes only 7 seconds.

**Comment by MrPetovan** [comment]
@annando is the resident SQL expert, he should be able to figure this out faster than I would.

**Comment by annando** [comment]
I'm not sure if PR https://github.com/friendica/friendica/pull/4570 will solve this since I don't have any issues with this.

**Comment by AlfredSK** [comment]
You can be sure now. It is solved. The two pages are loading very fast again.
Thanks.
