### ISSUE TITLE
Switch to Cropper.js library to also support touch devices

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4572]
Have you ever tried to setup a new account with a touch device? It's impossible to crop the profile image with our cropping library. You cannot move the crop lines. Cropper.js supports touch devices. Really cool!

Homepage: https://fengyuanchen.github.io/cropperjs/
Repository: https://github.com/fengyuanchen/cropperjs

Thank you!

**Comment by MrPetovan** [comment]
Fixes #839
