### ISSUE TITLE
Twitter: GIF animations sometimes end up end up static

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4584]
Examples:
- https://friendica.mrpetovan.com/display/a6551d713c55f480a62c8758e02cc6dd694db83d 🔒
- https://friendica.mrpetovan.com/display/a6551d7187ac7e91ca6e467a626546af4986c1b8 🔒
- https://friendica.mrpetovan.com/display/a6551d71dde9b84971a2df53a97472d80fedb960 🔒
- https://friendica.mrpetovan.com/display/a6551d71784fabd53d87e4b00c14c0f9459e8314 🔒
- https://friendica.mrpetovan.com/display/a6551d7172e36045d859cb52d8d395f969b70308 🔒
- https://friendica.mrpetovan.com/display/a6551d712d5afecd9513ffb07346b92dc976ea28 🔒
- https://friendica.mrpetovan.com/display/a6551d71ebf08926bc254a8d97cf8c5c0efa1220 🔒
- https://friendica.mrpetovan.com/display/a6551d7178099f47111f2ac777b405f8abadab0b 🔒

Counter-examples:
- https://friendica.mrpetovan.com/display/a6551d713e9e292602fea845022c09c3454de157 🔒
- https://friendica.mrpetovan.com/display/a6551d71804eaa72a36d992dfb7d37e2fb4826b5 🔒

**Comment by annando** [comment]
The links are still not accessible from the outside, since no shadow entries are generated for Twitter posts.

**Comment by MrPetovan** [comment]
Yeah, it's a self-reminder.

**Comment by MrPetovan** [comment]
The source object for all these examples have been wiped out by the latest item post update process, I have to collect more evidence now.

**Comment by annando** [comment]
@MrPetovan Had you got some examples now?

**Comment by MrPetovan** [comment]
Not lately unfortunately, I'll reopen if I see another.

**Comment by MrPetovan** [comment]
New example: https://friendica.mrpetovan.com/display/a6551d71c5ba4e8427a76ad4036ac99732a34848
