### ISSUE TITLE
frio: Submit posts asynchronously in the modal (aka don't jump to top of timeline after re-sharing a post)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#4599]
**Currently**
When sharing a post an overlay is shown. That's great but as soon as the "Share" button is pressed users find themselves at the top of their stream.

**Expected**
Without the technical background I can see no good reason UI wise to do this. Users loose their place in the feed and reading and sharing becomes a very frustrating thing up to the point where users will not share posts, they'd like to share, because they are tired of scrolling back down and searching for their position where they last were before sharing a post.
Request: why not share the post and stay at the exact position in the stream/feed?

**Comment by MrPetovan** [comment]
Thanks for reporting this, I have had the idea in the back of my head for a while, but I didn't take the take to write an issue about it.

My current workaround: open the post I want to share in a new tab and share from there not to lose my current place in the timeline.

**Comment by MrPetovan** [comment]
Technical context: The reason the page reloads is that the form in the modal window (the overlay) is submitted normally, which makes the browser load a new page. What we need to add is asynchronous form submission.

**Comment by hoergen** [comment]
Same, when you delete a post. Should I open a seperate issue?

**Comment by foss-** [comment]
@MrPetovan while technically correct the new title may not be helpful for laymen like myself searching issues. maybe having both would be good? re: timing of filing this: same here, has been bothering me for years, never got around to filing this till today.

**Comment by MrPetovan** [comment]
@foss- I understand your concern, but (un)fortunately we aren't getting enough opened issues that we would need users to recognize their issue in the list before posting. Currently the Issue list is mainly used by developers, which explains the title change to a more technical one.

**Comment by MrPetovan** [comment]
Technical details:

When a user submits a modal form, controls should be disabled until we get a response. If failed, we should display a message and enable the form controls back. If successful, we should display a message, clear out the modal form and hide it.

If it was an edit modal form, we should then update the edited post display through one of the `update_*` calls. This is the trickiest case as there are many pages where a post can be edited.

**Comment by valvin1** [comment]
It would be a great feature :)

**Comment by MrPetovan** [comment]
Closed by #8203
