### ISSUE TITLE
develop Installation fails

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4601]
Installing Friendica in a Debian Stretch VM I encountered the following error after entering the DB credentials in the installation wizard.

    PHP Fatal error:  Uncaught Error: Call to a member function real_escape_string() on null in /var/www/html/include/dba.php:205\nStack trace:\n
    #0 /var/www/html/include/dba.php(1142): dba::escape('config')\n
    #1 /var/www/html/include/dba.php(1103): dba::select('config', Array, Array, Array)\n
    #2 /var/www/html/src/Core/Config/JITConfigAdapter.php(59): dba::selectFirst('config', Array, Array)\n
    #3 /var/www/html/src/Core/Config.php(83): Friendica\\Core\\Config\\JITConfigAdapter->get('system', 'shortcut_icon', NULL, false)\n
    #4 /var/www/html/src/App.php(499): Friendica\\Core\\Config::get('system', 'shortcut_icon')\n
    #5 /var/www/html/index.php(388): Friendica\\App->init_pagehead()\n#6 {main}\n
      thrown in /var/www/html/include/dba.php on line 205, referer: http://192.168.0.114/index.php?q=install

**Comment by MrPetovan** [comment]
You shouldn't have the JITConfigAdapter on the RC branch, are you sure you checked out the right branch?

There may be a problem with install on `develop`, but this particular error can't show up on the RC branch because the files don't exist.

**Comment by tobiasd** [comment]
You are right m) I had a typo while checking out the rc branch.

But the RC branch has another installation bug. I'll open a new issue for the other bug.

**Comment by MrPetovan** [comment]
Fixed through #4617
