### ISSUE TITLE
[Twitter] Display poll options

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4605]
Local link: https://friendica.mrpetovan.com/display/a6551d71e306aa370d01fb625c992d3eabc3f9c3 🔒

I'm thinking about a simple representation of the poll like this:
````
- [ ] Option 1
- [ ] Option 2
- [ ] Options 3
````

**Comment by MrPetovan** [comment]
It turns out it is a "Premium" feature that would depend on the Premium application of the Twitter account registering the Twitter app with Friendica.

https://developer.twitter.com/en/docs/tweets/enrichments/overview/poll-metadata

**Comment by widle** [comment]
Just a note: polls are not a premium feature anymore (and have not been for some time), so it should be easier to test now.

**Comment by MrPetovan** [comment]
Thanks for the hint!

**Comment by foss-** [comment]
Is this wontfix as Twitter shut down most outside interaction?

**Comment by MrPetovan** [comment]
Indeed.
