### ISSUE TITLE
Forum Links from Hubzilla

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4609]
Hubzilla also has the possibility to post to forums by using an exclamation mark (!).
When such a post is delivered to Friendica the links are shown as IMG links (Image/Photo).

See here: https://libranet.de/display/5cbecd11b1440e684ec63c46d3eb8d3c9a59c329674b16fba3ff3546fe732d98@hub.somaton.com

You have to scroll down to the last line of the post.

**Comment by MrPetovan** [comment]
Can you please paste the display of https://libranet.de/itemsource?guid=5cbecd11b1440e684ec63c46d3eb8d3c9a59c329674b16fba3ff3546fe732d98@hub.somaton.com please? I don't have this post locally.

**Comment by AlfredSK** [comment]
The item can not be found on my node anymore. I'll see if I can find a new example.

**Comment by MrPetovan** [comment]
Good to know, now it just is another Regex in the BBCode wall.

**Comment by MrPetovan** [comment]
Closed via #6414

**Comment by AlfredSK** [comment]
Works! :tada:  See here https://libranet.de/display/53fa226c8788d4e49e17a8829937d84b8857b735c4a46759b93f0d5c20ff5dd4@hub.lazyteddy.eu

**Comment by MrPetovan** [comment]
Yay!
