### ISSUE TITLE
[3.6-rc] installation fails

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4611]
Ok, here is the issue with the installation wizard. Tested on a clean Debian Stretch.

    PHP Fatal error:  Uncaught Error: Call to a member function real_escape_string() on null in /var/www/html/include/dba.php:205\n
    Stack trace:\n#0 /var/www/html/include/dba.php(1048): dba::escape('config')\n
    #1 /var/www/html/src/Core/Config.php(164): dba::update('config', Array, Array, true)\n
    #2 /var/www/html/src/Database/DBStructure.php(208): Friendica\\Core\\Config::set('system', 'maintenance', 1)\n
    #3 /var/www/html/mod/install.php(543): Friendica\\Database\\DBStructure::update(false, true)\n
    #4 /var/www/html/mod/install.php(95): load_database()\n
    #5 /var/www/html/index.php(346): install_post(Object(Friendica\\App))\n
    #6 {main}\n  thrown in /var/www/html/include/dba.php on line 205, referer: http://192.168.0.114/install

It seems to be caused by wrong DB credentials, maybe general login problems with the given DB.

**Comment by MrPetovan** [comment]
So, basically, same error: the DB isn't correctly instantiated during install, and it breaks the first database call.

**Comment by tobiasd** [comment]
looks like, yes; resulting in a WSOD during installation.

**Comment by annando** [comment]
I guess wrong credentials during the installation lead to this. During installation the database connect always returned "true" - even on a failure.
