### ISSUE TITLE
Uncaught exception in twitter addon (3.6-rc)

### ISSUE THREAD

**Issue by ddorian1** [friendica/friendica#4627]
Since I switched to the 3.6-rc branch, the poller some times (~once a day) terminates with this exception. This didn't happen while I was on the master branch.

``PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: name lookup timed out in /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:440
Stack trace:
#0 /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array)
#1 /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array)
#2 /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(178): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'statuses/user_t...', Array)
#3 /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/twitter.php(875): Abraham\TwitterOAuth\TwitterOAuth->get('statuses/user_t...', Array)
#4 /var/www/virtual/jschwab/f in /var/www/virtual/jschwab/friendica.jschwab.org/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 440``

**Comment by MrPetovan** [comment]
Hi @ddorian1 and thanks for reporting the issue. This error just is a DNS request timeout we can't really control, so the best we can do is fail silently instead.

**Comment by annando** [comment]
I do have similar errors:
```
PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Operation timed out after 5000 milliseconds with 0 bytes received in /path/to/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:440
```

**Comment by MrPetovan** [comment]
Probably fixed by https://github.com/friendica/friendica-addons/pull/565 and https://github.com/friendica/friendica-addons/pull/569
