### ISSUE TITLE
Move executable scripts to bin/

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4629]
Latest installment of the code restructuration after #3878, #4090, #4116 and #4265.

This time we move all executable scripts from `scripts` and `util` in the `bin/` folder.

I even created a Console to remove most PHP executable scripts in the process!

By the way, don't hesitate to point out the scripts/console commands that don't serve any further purpose.

**Comment by tobiasd** [comment]
I like the current separation of the scripts needed by the core, and those only needed by the devs or in special situations.

**Comment by annando** [comment]
If this is all done in a single script, then it i fine for me. Otherwise I would like to have these scripts separated as well.

**Comment by annando** [comment]
Why have the three files stay "as-is"? Wouldn't it be easier, having a single entry point? And yes: A subfolder would be okay for me as well.

**Comment by MrPetovan** [comment]
Because they serve different purpose? The console is meant to be used by a human, while the others are specific entry points. I wasn't able to find documentation about `daemon.php` though.

**Comment by annando** [comment]
I would prefer having them all into one script. What are the others thinking about it? I think that the advantage would be to have unified the whole process. So index.php and console.php would be the only two entry points.

Yeah, daemon.php isn't really documented. I found it some time ago and had improved it.

**Comment by tobiasd** [comment]
> All the PHP CLI commands have been gathered in the console, but the
> `daemon.php`,  `worker.php`  and `auth_ejabberd.php` have to stay
> as-is.

I feared so.

**Comment by MrPetovan** [comment]
Please don't forget about https://github.com/friendica/friendica-addons/pull/550 and https://github.com/friendica/friendica-addons/pull/551

I need to do a Friendica Developer post about the new location of Composer now!

**Comment by tobiasd** [comment]
And remember to write a blog posting about it as well.

**Comment by MrPetovan** [comment]
I will, thanks for the reminder.

**Comment by MrPetovan** [comment]
New question: I've seen other `bin/` folders being organized by target interpreter. All the executable PHP scripts are in `bin/php/`, the executable Python scripts would be in `bin/py/` and the executable Shell scripts would be in `bin/sh/`.

What do you think instead of a hodgepodge of executable scripts in `bin/dev/`?

**Comment by tobiasd** [comment]
I think the location of the executables should not be changed on a weekly basis. The PR with the new location was merged, stick with the dead snake.

**Comment by MrPetovan** [comment]
Duly noted, although it is `develop` after all.
