### ISSUE TITLE
Add notifications for automatically accepted friend requests (soapbox)

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4639]
I set up my account as a soapbox to allow anyone to follow me automatically, and I'd like to be notified when someone does. Currently friend requests notifications are only sent when an approval is required.

**Comment by MrPetovan** [comment]
Revisiting this issue, where should I look in general for automatically accepted friend requests? in the same place as the pending friend requests?

Any help would be appreciated.

**Comment by MrPetovan** [comment]
My plan was to add a notification with `type = NOTIFY_INTRO` and `verb = ACTIVITY_FOLLOW` in this block, am I doing it right?
https://github.com/friendica/friendica/blob/1585b5db456ce7b9d0ad3d6dc97a1f5ff6810bf9/mod/dfrn_request.php#L576-L587

I suppose that it's only valid for DFRN contacts (maybe OStatus as well?) so I was planning on adding a notification as well for Diaspora here:
https://github.com/friendica/friendica/blob/1585b5db456ce7b9d0ad3d6dc97a1f5ff6810bf9/src/Protocol/Diaspora.php#L2465-L2475

I'm not sure what I'm doing though, so any help or hint is appreciated.

**Comment by annando** [comment]
Just look for this "SOAPBOX" stuff in the Protocol code. But when you change the behaviour, you should add this with a switch. But I'm really totally unsure if it can be done so easily. I guess the notification system has to be enhanced as well.

**Comment by MrPetovan** [comment]
I found the appropriate translation strings in `include/enotify.php` so this is clearly feasible, we just don't send the notification.

**Comment by annando** [comment]
AFAIK we suppress the notification messages at the moment.

**Comment by MrPetovan** [comment]
From what I seen, we don't even send anything when there's no action required. I'm not sure what we would be actively "suppressing".

**Comment by futureisfoss** [comment]
I came across this follower notification issue on soapbox accounts. When I asked about it on the Friendica Support forum [here](https://social.trom.tf/display/dbc8dc44-1362-126b-a827-57d456706316), I was told to create a feature request on this repository. Seeing there is already an opened issue about this, I'm just leaving a comment here.

**Comment by MrPetovan** [comment]
I started working on this and I have a question, should the notifications disappear from the dropdown when the follower unfollow you?

**Comment by akno77** [comment]
Hi, is this feature (still) working? I don't get any notifications about auto follows in the current Friendica Version...

**Comment by MrPetovan** [comment]
Good question, I can’t remember ever receiving a notification for follows even after this was closed. 🤔
