### ISSUE TITLE
1 contact request from Mastodon creates 6 contact requests

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4655]
I got 2 contact requests from Mastodon and that creates in friendica 6 contact requests each. so I got 12 friend requests .

For exmaple this 1 request.

![00_temp](https://user-images.githubusercontent.com/24474762/37846551-3f5e30d2-2ece-11e8-8890-ac638c90468e.jpg)

**Comment by MrPetovan** [comment]
Very artsy!

Stable or Develop?

**Comment by hoergen** [comment]
3.6 stable pulled git today

**Comment by annando** [comment]
I will have a look at it, once I'm back on "dev". Currently I'm waiting on stable until all open pull requests are merged and some people on smaller systems hadn't got problems with it.

**Comment by zeroadam** [comment]
Sorry, I know it's not related but since @annando mentioned waiting on dev. I pulled latest develop and I can get to login screen, but once I login, I get 500 for every page. Whole node basically down.

**Comment by MrPetovan** [comment]
Error log?

**Comment by annando** [comment]
Try to run ```scripts/dbstructure.php update``` manually.

**Comment by zeroadam** [comment]
src/Database/DBStructure.php update? Ran quickly with no output

**Comment by zeroadam** [comment]
@MrPetovan 

[Fri Mar 23 16:31:13.615207 2018] [php7:warn] [pid 1000] [client 73.172.166.61:46648] PHP Warning:  Invalid argument supplied for foreach() in /srv/http/friendica/include/conversation.php on line 956
[Fri Mar 23 16:31:13.615256 2018] [php7:error] [pid 1000] [client 73.172.166.61:46648] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to conv_sort() must be of the type array, null given, called in /srv/http/friendica/include/conversation.php on line 962 and defined in /srv/http/friendica/include/conversation.php:1534\nStack trace:\n#0 /srv/http/friendica/include/conversation.php(962): conv_sort(NULL, 'commented')\n#1 /srv/http/friendica/include/conversation.php(582): conversation_add_children(Array, true, 'commented')\n#2 /srv/http/friendica/mod/community.php(169): conversation(Object(Friendica\\App), Array, 'community', 0)\n#3 /srv/http/friendica/index.php(371): community_content(Object(Friendica\\App))\n#4 {main}\n  thrown in /srv/http/friendica/include/conversation.php on line 1534

**Comment by hoergen** [comment]
There was a change from **util/**composer to **bin/**composer .Then you have to run 
`php bin/composer.phar update`

and then 
`php bin/composer.phar install`

and don't forget to change that in a script you may run :)

**Comment by hoergen** [comment]
I'm now on develop branch again.

**Comment by zeroadam** [comment]
@hoergen I did notice that as well. I had already run both update and install prior to my mentioning this

**Comment by hoergen** [comment]
Did you check file system rights (owner,group,executable)? 
I had some issues after switching to develop.

**Comment by zeroadam** [comment]
I have a script I run for permissions so... However, after latest pull.. I got the maintenance message and now, everything is working. Able to login and see posts and such. Thing seem to be normal!

**Comment by MrPetovan** [comment]
What about the original issue after you correctly switched to Develop?

**Comment by hoergen** [comment]
Today I had the problem again. 1 Mastodon request creates 6 requests .

**Comment by annando** [comment]
I cannot reproduce. Is it always from the same server?

**Comment by hoergen** [comment]
Hmm good question. I don't think so, but i can't tell for sure

**Comment by annando** [comment]
Please have a look at it when it occurs again.

**Comment by MrPetovan** [comment]
It did occur again, see #4803.

**Comment by hoergen** [comment]
Ah sorry .. I knew somewhere deep down in my subconsciousness there was already an issue. Thanks @MrPetovan for merging them 🌻

**Comment by hoergen** [comment]
I got again several contact requests the last days from different mastodon servers and there are **every time 6** requests on my friendica. 
The requests are showing a different time. Something between 1-3 minutes difference between each request.

**Comment by hoergen** [comment]
Now it's getting quite annoying because for every Mastodon contact request (what produces 6 requests) I have to go through all requests and
  - accept 1 request

and then 

  - delete 1 request
  - delete 1 request
  - delete 1 request
  - delete 1 request
  - delete 1 request

and since gnusocial.de announced that it will close end of may, this is going nuts at the moment :(

I have the feeling, that friendica is multiplying that request. But I'm not sure. I will switch on the logs. Maybe that enlightens a little more

**Comment by annando** [comment]
Funny enough I never experienced that problem. But I will check how I can prevent it.

**Comment by hoergen** [comment]
You know I still think there is something living in my database ;) We had once a session where you found , why I didn't find a contact of mine. Gladly I find everbody but one account in my contact I can't mention or write a PM. Everything else is ok.

So maybe there is something wrong with my account, that produces such weird things?

**Comment by annando** [comment]
The ghost in the machinery. ;-) We will find it.

**Comment by tobiasd** [comment]
Have the 5 ghosts re-entered since the above fix was merged 20 days ago?

**Comment by hoergen** [comment]
Didn't experienced this again on my personal account. Yesterday i deleted 5 ghosts from the podcast account (automatic request approvals), but I don't know from when those requests were. hmm.
I would say this is solved?

**Comment by hoergen** [comment]
Since yesterday on develop RC and it started again to create 2 friend request (instance https://metalhead.club/)

**Comment by tobiasd** [comment]
I've got some contact requests from mastodon users (on different nodes though) in the last days. All worked fine with the RC branch. Are you ok with moving this issue to the next milestone @hoergen ?

**Comment by hoergen** [comment]
Sure I had several contact requests from Mastodon in the last days with just one request. Maybe it is fixed? Let's close it and if it returns we open it again.

**Comment by hoergen** [comment]
Sorry have to open it. It happened again.
Mastodon Instance https://social.tchncs.de

**Comment by tobiasd** [comment]
Do you have any log entries from this happening?  Could you have a look into the `intro` table of your DB for the requests and see if there is something interesting.

**Comment by hoergen** [comment]
Will search in the log. In the intro table I cant see something unusual ( besides I don'T know how "unusual" should look like). As far as I remember there were other Mastodon requests that came only with one request. Maybe it is dependent to the mastodon version?

**Comment by tobiasd** [comment]
> Will search in the log. In the intro table I cant see something
> unusual ( besides I don'T know how "unusual" should look like). As
> far as I remember there were other Mastodon requests that came only
> with one request. Maybe it is dependent to the mastodon version?

Me neither ;-) is the time stamp identical for all requests? I think it is only precise for the second, but maybe the other end is sending out multiple requests sometimes.

**Comment by hoergen** [comment]
The timestamp is different. There are always some minutes (5-10) in bertween.

**Comment by hoergen** [comment]
Friendica should check, if there is already a contact request or a contact. Then the problem shouldn't occur again.

**Comment by tobiasd** [comment]
Minutes in between. Woe, I thought maybe seconds. But not a fixed interval?

**Comment by hoergen** [comment]
I guess since this is a decentralized network the fixed interval varies because of several reasons (queue, response, power of each system and so on ;)

**Comment by hoergen** [comment]
I thought this fix is already in the actual rc. That's why I thought, that something was going wrong again.

**Comment by tobiasd** [comment]
Has this occurred again for you in 2018.08-dev @hoergen ?

**Comment by hoergen** [comment]
Didn't notice this again. I close this issue then. Thanks for reminding 🌻
