### ISSUE TITLE
new dependency in develop does not meet the PHP version requirements

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4660]
There is a problem with PHP5.6 and some dependency pulled in, reported over one of the matrix support rooms.

 > - paragonie/constant\_time\_encoding v2.2.2 requires php ^7 -> your PHP version (5.6.30) does not satisfy that requirement.

**Comment by MrPetovan** [comment]
I don't have PHP 5.6 anymore, either on my local machine or on my server, so someone™️ with PHP 5.6 should run `bin/composer.phar update` on the current `develop` branch and submit a PR with the updated `composer.lock` or send it to me at `mrpetovan@gmail.com`.

**Comment by MrPetovan** [comment]
Scratch that, I still have the PHP 5.6 CLI installed, I should be able to do it on my own with 
````$> /usr/bin/php5 bin/composer.phar update````

**Comment by tobiasd** [comment]
I can set a VM for this with VirtualBox. It could be enough if you are using Vagrant and change the `config.vm.box = "ubuntu/xenial64"` line to use `ubuntu/trusty64` instead.
