### ISSUE TITLE
removing contact groups not possible

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4663]
When deleting a contact group, either with or without contacts in that group, this only results in an error message bubble-info that "Unable to remove group" (mod/group.php:129 according to DE messages.po).

Friendica Version used: 3.6

**Comment by annando** [comment]
It was easy to find. But since I'm currently running "master", I'm unsure where to apply the PR against.

**Comment by tobiasd** [comment]
You can just clone the repository on your notebook in a new directory and fix the bug there. If you install the Vagrant stuff in addition, you have even a machine to work on, even though your production server runs the master branch (same here)

**Comment by MrPetovan** [comment]
You can also change the file on GitHub in a separate branch from develop and submit a PR from here as well. Or explain the  needed change here, Or paste the changed code in a code block.

**Comment by MrPetovan** [comment]
Closed through #4675
