### ISSUE TITLE
Error during DB update

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4664]
During the DB upgrade something went wrong and Friendica send an error report to the admin pleading for help. The error message is

> Errors encountered performing database changes: ALTER IGNORE TABLE `item` ADD `content-warning` varchar(255) NOT NULL DEFAULT '' COMMENT ''; 

The node remains in the maintenance mode.

MySQL-Version: dbVersion5.5.5-10.0.34-MariaDB-0ubuntu0.16.04.1
Used Friendica Version: 2018.05-dev

**Comment by annando** [comment]
Please execute the command in the SQL console to see the actual error.

**Comment by copiis** [comment]
Error 1296 occurred during database update:
Got error 64 'Temp file write failure' from InnoDB
Errors encountered performing database changes: ALTER IGNORE TABLE `item` ADD `content-warning` varchar(255) NOT NULL DEFAULT '' COMMENT ''; <br />

**Comment by annando** [comment]
That error just says that there is not enough disc space on your system.

**Comment by copiis** [comment]
I have 202 GB free space...

**Comment by annando** [comment]
Do you have separate partitions? The error message is very clear - all explanations on the web seems to say the same.

**Comment by MrPetovan** [comment]
Do you have enough inodes? This can also lead to write failures.

Try executing `$> df -i /`

**Comment by copiis** [comment]
df -i /

says

Dateisystem      Inodes IBenutzt    IFrei IUse% Eingehängt auf
/dev/vda1      15859712   260708 15599004    2% /

**Comment by copiis** [comment]
cat /proc/partitions
major minor  #blocks  name

 253        0  262144000 vda
 253        1  253754368 vda1
 253        2          1 vda2
 253        5    8386560 vda5
  11        0      55296 sr0

**Comment by MrPetovan** [comment]
I can't see anything wrong but I'm not an expert either. Did you get the error while executing the SQL query directly from the command line?

**Comment by copiis** [comment]
> Yes

**Comment by annando** [comment]
Like discussed at a another place: Your temp partition is really small. This database update possibly writes stuff in there - and the item table is huge.

**Comment by annando** [comment]
I guess we can close this issue for two reasons:

1. @copiis had solved the problem by changing the temp path like he told on XMPP
2. It is no bug in Friendica
