### ISSUE TITLE
DB Error in expiration query

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4669]
My node is currently collecting jobs for the workerqueue. While looking into the log I found the following:

    [NORMAL]:dba.php:545:e  DB Error 1048: Column 'k' cannot be null
    dba::update, Cache::set, Image::getInfoFromURL, OStatus::feed, PubSubPublish::execute, call_user_func_array, Worker::processQueue
    INSERT INTO `cache` (`k`, `v`, `expire_mode`, `updated`) VALUES ('', 'b:0;', 0, '2018-03-24 05:25:50') ON DUPLICATE KEY UPDATE `k` = '', `v` = 'b:0;', `expire_mode` = 0, `updated` = '2018-03-24 05:25:50'

Friendica Version 3.6 stable
MariaDB 10.1.23

**Comment by MrPetovan** [comment]
This happens when `Image::getInfoFromURL0` is called with an empty image URL parameter.
