### ISSUE TITLE
bin/console po2php produces invalid strings.php files

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#4670]
Using `bin/console po2php messages.po` produces `strings.php`file with syntax errors.

I tested it with DE, FR and NL messages.po files. All turned out having syntax errors after conversion.

Friendica Version: 2018.05-dev

**Comment by MrPetovan** [comment]
Are we still using this tool?

I personally fixed another issue when I moved the script over to the console command, when I tested it with a short messages.po, so I assumed it wasn’t used or someone would have reported it earlier.

Can you be more precise about which messages.po fails and the actual error in the strings.php output?

**Comment by tobiasd** [comment]
> Are we still using this tool?

Huh? I tested your new `bin/console` tool and it failed. The translations I added were generated with  A backup copy of the `util/po2php` tool.

> Can you be more precise about which messages.po fails and the actual error in the strings.php output?

I tried to translate the DE, FR and NL `messages.po` files to `string.php` all ended up with syntax errors. I think it was always some not terminated string.

**Comment by MrPetovan** [comment]
> Huh? I tested your new bin/console tool and it failed. The translations I added were generated with A backup copy of the util/po2php tool.

I don't care as much about test as I care about actual usage. I tested it too, but it doesn't make it "used". Thanks for conforming actual usage.

> I tried to translate the DE, FR and NL messages.po files to string.php all ended up with syntax errors. I think it was always some not terminated string.

That's what I was afraid of. When I moved the script to the console command I fixed an issue where strings were terminated twice. It could be a Windows/Linux difference and I'm not specially happy about it.
