### ISSUE TITLE
[nsfw] Add hashtag-only hiding

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4681]
Currently, the NS​FW addon only allows to hide posts containing specific words. If I set `ns​fw`, it will hide the posts with `ns​fw` and `#ns​fw`.

However, if I set `#ns​fw`, it won't hide posts with `#ns​fw`. This is due to the way we are separating the `#` from the hashtag label to make the final link.

The solution is to look in the `term` table if the provided hiding string is a hashtag.

**Comment by MrPetovan** [comment]
@annando Don't forget about https://github.com/friendica/friendica-addons/pull/560 !

**Comment by annando** [comment]
Yeah, that's my short attention span :-)
