### ISSUE TITLE
API docs about /statuses/friends doesn't mention count parameter

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#4689]
The API /statuses/friends lists only 20 friends ( all types oft friendships). It is sorted by screenname and stops at the letter i.
I'm on Friendica 3.6 Master.

**Comment by annando** [comment]
It is no bug. This API has got a ```count``` parameter - and the default value for this is 20.

**Comment by LubuWest** [comment]
@annando Then the api.md  is out oft date...

**Comment by annando** [comment]
Would you mind, renaming the issue to something like "API documentation has to be updated"? Then we could add this as some junior job to some following release.
