### ISSUE TITLE
Implement friendships/create and friendships/destroy API endpoints

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4694]
This would allow to add/remove friends from an external app:
* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-create
* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-destroy

**Comment by imattau** [comment]
Just following up to see if there will be any work on this, or anticipated completion timeframe?

**Comment by annando** [comment]
This should work now.
