### ISSUE TITLE
Add a way to return a bigger avatar in users/show

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4695]
### Expected behavior
(See https://github.com/TwidereProject/Twidere-Android/issues/1103)
It would be nice to be able to return a bigger avatar.

### Actual behavior
We currently only return a 48x48 px avatar.

### Steps to reproduce the problem
Call https://social.rudloff.pro/api/users/show.json?include_blocking=true&user_id=13&include_blocked_by=true

### Friendica version you encountered the problem
3.6

### Friendica source (git, zip)
git

### PHP version
5.6.33-0+deb8u1

### SQL version
5.5.59

**Comment by Rudloff** [comment]
I can work on a PR for this but we need to decide how to do it first.
@mariotaku mentionned two different ways:
> GNU Social added profile_image_url_profile_size field in User object, and Fanfou added profile_image_url_large. Both fields has an URL pointed to larger profile image. You can consider use fields like that.

I think `profile_image_url_large` might be easier to implement and won't break compatibility with clients that expect a 48x48 px image.

**Comment by annando** [comment]
This "profile_image_url_profile_size" seems to be an additional field as well. So we could use that as well.

**Comment by mariotaku** [comment]
So it's just about naming. I prefer `profile_image_large` personally, it'd
be nice to return a 144x144 or 128x128 image.

P.S. are there a field for original image?

**Comment by Rudloff** [comment]
@annando You are right it, I misread the GNU Social code. `profile_image_url_profile_size` contains the URL of a 96x96px image.

@mariotaku I think GNU Social also returns a `profile_image_url_original` field so we could implement this too.

**Comment by annando** [comment]
We do have three sizes in our contact table. Please don't use the "avatar" field since this contains the external url. For privacy and caching issues we always use "photo", "thumb" or "micro", where "photo" is the biggest one.

**Comment by annando** [comment]
@mariotaku we have 175, 80 and 48. And no, don't ask me why "175" - that had been before my time.
