### ISSUE TITLE
Implement saved_searches/create and saved_searches/destroy

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4696]
This would allow users to create/remove saved searches from an external app.

For some reason the Twitter API doc for this is missing:
* https://developer.twitter.com/en/docs/tweets/search/api-reference/post-saved_searches-create
* https://developer.twitter.com/en/docs/tweets/search/api-reference/post-saved_searches-destroy-id

**Comment by annando** [comment]
We now support this functionality via the corresponding Mastodon API endpoints for the tag handling.
