### ISSUE TITLE
Controlling the formatting of links for imported content

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#4708]
Due to fancy link formatting when importing tweets, some links are modified in an undesirable way. This is usually the case when the URL leads to a site with strict cookie control, as well as when redirected to censorship notification where the nodes pull via tor exit servers. The issue seems also relevant for "shareboxes". A longer discussions documents the problem relatively well here:  https://friendica.hubup.pro/display/174591b4785ab908c8a0422837797102

The modification of imported content (i.e. URLs in text) is unexpected behaviour.

Some level of control in terms of link formatting could avoid this problem.

I am on the develop branch.

**Comment by MrPetovan** [comment]
I've got a really egregious example:

Twitter post: https://twitter.com/vectorpoem/status/979770328997027840
Friendica post:
![screen shot 2018-03-30 at 1 41 39 pm](https://user-images.githubusercontent.com/925415/38147391-204f584a-3420-11e8-8d06-26399261f0c7.png)
The "relentless.com" link is being converted to the redirection "amazon.com" in the body itself, and a fancy preview is tacked on even though the original post didn't.

**Comment by annando** [comment]
This is a cause of our routine that tries to follow short link url. We either have the possibility to not resolve short link url (which results in not knowing where we get to - which is a possible security or privacy issue) or to sometimes have the described problem.

**Comment by MrPetovan** [comment]
No, we should just not format further imported posts from other platforms. It is this way because we make every Twitter posts go through `mod_item()` by filling `$_REQUEST` when it should call `Item::insert()` or similar directly instead.

**Comment by annando** [comment]
Regular tweets are inserted via "Item::insert", we only call the function in "mod_item" for mirrored posts.

Please have a look at "Network::finalUrl", this is the function that follows the redirections. It is called directly in the addon for every link entity.

**Comment by MrPetovan** [comment]
I don't think this is a problem with the URL resolver itself, but it is a problem that we are calling it at all on an already-formatted post. Twitter post formatting should be limited to mentions, and everything else should be kept as is, including if there's a link preview or not.

**Comment by annando** [comment]
This line is responsible: https://github.com/friendica/friendica-addons/blob/develop/twitter/twitter.php#L1149

**Comment by MrPetovan** [comment]
Great, thank you for looking into it. Sadly I don't have the post's object anymore so I'm not sure what/how to change it.

**Comment by annando** [comment]
The only possible way is to change that line from ```$expanded_url = Network::finalUrl($url->expanded_url);``` into ```$expanded_url = $url->expanded_url;```.

This will however lead to more user tracking and link obfuscation when there are shortlinks involved.

**Comment by MrPetovan** [comment]
The problem with the link in my example post is that the display should have stayed the same (relentless.com) no matter what the actual target (in this case, amazon.com) was.

**Comment by annando** [comment]
Have a look in that function. There we not only create the preview data but also are replacing the link in the body. It should be possible to only replace the linked URL but not the displayed link.

**Comment by annando** [comment]
Can we close this now?

**Comment by annando** [comment]
Okay.

**Comment by annando** [comment]
The original case is fixed, I think, isn't it?

**Comment by MrPetovan** [comment]
It isn't fixed per se, but there's a workaround.

**Comment by annando** [comment]
I think that we really can move this issue to the next release?

**Comment by MrPetovan** [comment]
Definitely.

**Comment by AndyHee** [comment]
Sorry @MrPetovan I overlooked your mentioning awhile ago. Thanks @tobiasd for brining this up again.

I regularly have post coming in from Twitter with these issues. Two typical cases: 

(1) A tweet shares an article hosted on an academic publisher's website (_Hey I read this interesting article!_). The preview says a website needs to set cookies. The URL is converted to something like this https://journals.sagepub.com/page/cookie-policy. As the tweet may not mention the name of the journal and author, I end up having to look at twitter itself.

 (2) A tweet shares a blog post URL for a blog hosted on a random site with heavy google analytics. The result is an accurate preview with the correct picture and preview text, but the actual blog's URL is converted to http://www.google.com

**Comment by MrPetovan** [comment]
(1) is the behavior I just mentioned above your reply, but (2) is completely foreign to me. In any case, keeping the original link URL seems to be the best course of action.

In the case of Twitter link, we can develop `t.co` links directly in the body because we have this information in the tweet JSON so we will have a meaningful URL to show.

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/788
