### ISSUE TITLE
Add query-based content-filter addon

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#4709]
Preface: _The "Blockem" addon is really great! It gives users a fine-grain level of control over their timelines. Friendica has distinguished itself from other social media platforms like Facebook by allowing users to control how their timeline is populated._

**Enhancement Suggestion**

It may be useful to combine search elements such keywords and users. E.g. : Hide a specific person's posts if they use a specific keyword.

Use case: Person X send generally interesting posts but their specific (persistent) view on topic abc is irrelevant to me, despite that I generally have not objection to topic abc as such. At the moment I can only completely hide either all of X's posts or everyone else posts on topic abc.

How to best achieve this at a technical level, I am not sure. But we may want to review whether merging this addon with the NFW addon could be a way forward.

**Comment by MrPetovan** [comment]
What you're suggesting amounts to creating a complex content-filter query system, with variables checks and logical operators. In essence, it would also cover the language filter addon and the CW we receive from Mastodon and Pleroma.

Something like ``Hide if: `user` = "test@example.com" AND `body` MATCHES "keyword"`` to follow your example.

It would be something that could be use along the existing addons because we still need simple tools for simpler needs.

**Comment by AndyHee** [comment]
I see. You're saying such a complex filter would not be suitable for simple queries?

Are you concerned about processing speed?

**Comment by MrPetovan** [comment]
No, the complex system would handle complex queries just fine, but the accessibility penalty would keep people away from it. So we need an accessible system for simple needs, and an "expert" system for more advanced needs, while it could also handle simple cases.

More design elements:
- The new content filter system would need to record rules. A rule has a name and a query and can be switched on/off and ordered. Rules are per-user.
- It would use the same [`content-filter` hook as discussed in this forum discussion](https://friendica.mrpetovan.com/display/735a2029715ab80d1874cf6808556656), which means it would have access to the same item variables as the other content filtering addons.
- The content system query language needs support for logical operators OR, AND, NOT and parentheses. Comparators should include at least exact and partial match. Beginning/End of strings comparators would be great, but aren't mandatory.
- Activated rules would be checked in order, first rule to match takes the cake. The content-filter label shows the name of the matched rule.

**Comment by MrPetovan** [comment]
Implementation hints:
- https://stackoverflow.com/a/10772665
- https://symfony.com/doc/current/components/expression_language.html (https://packagist.org/packages/symfony/expression-language)

**Comment by MrPetovan** [comment]
@annando, this addon would need a specific database table, do we have an example of another addon using a dedicated table or do I have to make it part of the core?

**Comment by annando** [comment]
I suggest adding a hook in dbstructure.php so that addons can change the database structure.

**Comment by MrPetovan** [comment]
Ah, interesting, thanks for the tip.

**Comment by annando** [comment]
You could call the command that is called when you do a "dbstructure update".

**Comment by MrPetovan** [comment]
Yeah, I realized that just after I wrote it, but I had to leave work and I spent the evening with my girlfriend, thanks for answering though!

**Comment by MrPetovan** [comment]
Progress report:
![advancedcontentfilter_settings](https://user-images.githubusercontent.com/925415/38185824-f2fa60ba-361d-11e8-80e6-e79406278bc7.png)
![advancedcontentfilter_post](https://user-images.githubusercontent.com/925415/38185823-f2ee5c8e-361d-11e8-996d-22c9b77fe88b.png)

**Comment by MrPetovan** [comment]
To Do list:
- [x] Add the custom database table through the new hook `dbstructure_definition`
- [x] Add the settings page to add new rules with expression validation error handling
- [x] Add Expression caching through serializing in database and in memory rule caching
- [x] Add the `content_filter` hook using `ExpressionLanguage` evaluation of the users' own rules
- [ ] Show all the users' rules
- [ ] Allow editing rules
- [ ] Allow enabling/disabling rules
- [ ] Allow deleting rules

**Comment by annando** [comment]
Concerning new hooks: Formerly they had been named after the function names. Most of them now had changed, so that this isn't so obvious now. But for new hooks I would like to stick to this scheme by naming the hook in some "Class::function" like way.

**Comment by MrPetovan** [comment]
I'like to keep them in `snake_case`, it's simpler and consistent. Especially since you can have multiple hooks in a single function. How do you call them then ? "Class::function_start"? I'd rather keep "class_function_start" as it is now.
