### ISSUE TITLE
Language Filter default settings

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#4710]
This addon seems to be "User" enabled by default, as soon as the administrator activates it.

This is rather confusing for users who expect to see content in their local language that is not: en,de,fr,it,es

My newly signed up users need to first disable this addon or whitelist their language before they see content in their local Asian languages.

Users should actively opt-in, rather than having to opt-out for this filter.

**Comment by AndyHee** [comment]
In the light of the discussion here: https://github.com/friendica/friendica-addons/pull/563

The default settings for the minimum number of characters should be increased. Perhaps around 100.

**Comment by MrPetovan** [comment]
140, as a cheeky wink to the former Twitter character limit?

**Comment by AndyHee** [comment]
Haha nice.

I assumed you set yours pragmatically to 100, so it will limited posts to one-liners only.

**Comment by MrPetovan** [comment]
Yeah, that's the spirit, but I didn't carefully measure the number of characters.

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/609
