### ISSUE TITLE
scripts/worker.php returns unexpected "System Unavailable" HTML output

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4714]
### Expected behavior
The `worker.php` cron does not send any e-mail.

### Actual behavior
Since I updated to 3.6, I often get e-mails containing this:
```html
<html>
	<head><title>System Unavailable</title></head>
	<body>Apologies but this site is unavailable at the moment. Please try again later.</body>
</html>
```

### Steps to reproduce the problem
Here is my crontab:
```cron
*/10 * * * *    cd /var/www/friendica/; /usr/bin/php scripts/worker.php
```

### Friendica version you encountered the problem
3.6

### Friendica source (git, zip)
git

### PHP version
5.6.33-0+deb8u1

### SQL version
5.5.59

**Comment by MrPetovan** [comment]
Who is the sender of those emails? On some systems, cron itself sends email with the cronjob output to the cron user's inbox.

**Comment by Rudloff** [comment]
Yes, cron is configured to send e-mails when there is an output and this is expected.
What is unexpected here is that `worker.php` returns this ouput.

**Comment by MrPetovan** [comment]
This output can be triggered when the DB can't connect for example: https://github.com/friendica/friendica/blob/master/include/dba.php#L102

**Comment by Rudloff** [comment]
Hum, that's strange but maybe it happens because my SQL server has too many connections.
If that's the case, I don't think this can be fixed in Friendica (except maybe return a non-HTML and more explicit error).

**Comment by MrPetovan** [comment]
The `develop` branch got rid of this HTML message in the connection function, and only dispenses the HTML error message when in a HTML context, so this should resolve itself.

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica/commit/881c7ccfc11aab542f42d5c6a555722aa5eb5c75#diff-6cb3a981df757a28e6d6b23c3837dc85
