### ISSUE TITLE
Contacts > Group Editor: Icon to remove/add contact to groups should be more distinguishable (color?)

### ISSUE THREAD

**Issue by chicken7745** [friendica/friendica#4721]
### Actual behavior 
Currently two very similar icons are used and both use grey color and differ only by 45 degree rotation.

### Expected behavior 
UI could be improved by adding color codes to icon. Suggestion current icon "add" green color, current icon "remove" red color. Current icons are finde, adding color would make them more distinguishable. 

### Steps to reproduce the problem 
Select contacts > group or "create a new group"

### Friendica version you encountered the problem 
2018-05-dev, Node: squeet.me

Unsure if this is limited to fro or how it is solved in other themes.
![bildschirmfoto 2018-03-31 um 22 42 25](https://user-images.githubusercontent.com/37964610/38167566-5d5418d0-3537-11e8-8909-6b1cdabac89f.png)

**Comment by tobiasd** [comment]
Which theme are you using?
