### ISSUE TITLE
forum not show, if contact is hide from others

### ISSUE THREAD

**Issue by paulinsche** [friendica/friendica#4726]
### Expected behavior
Using frio, forums are shown on the left side of <site>/network. The forums should be always visible, even if the contact is not show to others.
### Actual behavior
Forum is not shown, as soon as contact is hidden from others.
### Steps to reproduce the problem
* Join a forum
* look at your <site>/network. Forum is displayed
* change the visibility of the contact to „hidden to others“
* Forum is not displayed any longer
### Friendica version you encountered the problem
3.6
### Friendica source (git, zip)
git tags/3.6
### PHP version
7.0.28-0ubuntu0.16.04.1
### SQL version
7.0.28-0ubuntu0.16.04.1

**Comment by MrPetovan** [comment]
Thanks for reporting this issue!

**Comment by tobiasd** [comment]
In current 2018.08 develop branch, with the vier theme but I guess the widget is theme independent, the forum hidden from contacts is listed in the forum list widget.

Maybe it could be a caching issue (on my end as it was shown before). But it would be great if others could check this out as well!
