### ISSUE TITLE
Message list in /message should show the actual 'From' user, not me

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#4738]
### Expected behavior
If I have a message from "Bob Smith", and I am "Adam Clark", the message in the list should not say "Adam Clark and You", it should say "Bob Smith and You"

### Actual behavior
I have several that are from between me and different people that all say "Adam Clark and You"

### Steps to reproduce the problem
Look at my messages at /message

### Friendica version you encountered the problem
3.6

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
mariadb 10.0.32

**Comment by annando** [comment]
Thanks for creating this issue. This is a known bug that we really have to fix.

**Comment by MrPetovan** [comment]
I started looking into this, and this is worse of a mess than I thought it was. First of all, there's no easy way to know which private message started a conversation. Even for the initial `mail` row, the `uri` and `parent-uri` are different.

Secondly, I'm confused as of what the `conv` table is about. I thought it was a list of top-level private messages, but not all `mail` rows have a `convid` set, and it seems to be one `conv` row per message when it is set.

My immediate plan would be to straighten out the `uri` and `parent-uri` in the `mail` table. Is there a specific reason why the `uri` and `parent-uri` don't match in the first message of a private conversation?

**Comment by annando** [comment]
This whole mess needs a complete overhaul - especially since Diaspora does know private messages with multiple receivers - which I want to implement for years. So if you really like to place your hand on this - please do so! - then please change it according to this requirement.

**Comment by MrPetovan** [comment]
It's too big of a task for me and for the RC. I'd rather defer Federation stuff to you, but if I may venture a suggestion: why not use a regular item with ACLs?

**Comment by annando** [comment]
This is a possibility. I had to investigate how to easily separate these two tasks without changing the database structure.

**Comment by MrPetovan** [comment]
Closed via #6280
