### ISSUE TITLE
Hashtags are broken when a post was edited

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4739]
When writing a post and using #hashtags they are shown correct when the post is sent. 
When the post is edited&sent, the hashtags are broken and not highlighted anymore when you hover over the text. 

Tested with frio and vier. Same behaviour.
Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259

**Comment by ben-utzer** [comment]
In meiner [lokalen Kopie des Beitrags](https://social.yl.ms/display/2196d4ee475ac47728d7c8f040211499) wird der Tag nicht verlinkt oder hervorgehoben, jedoch wird dieser unter dem Beitrag angezeigt und eine Suche nach #Firefox fördert diesen zu Tage. In dem [Beitrag bei hoergen](https://horche.demkontinuum.de/display/2196d4ee475ac47728d7c8f040211499) kann ist der #Hashtag im Chrome hervorgehoben sobald ich mit dem Mauszeiger über den Thread fahre. 
Lokal habe ich aktuelle das Theme Vier genutzt. 

Sorry for the german text, I am now to lazy to translate it. :-(

**Comment by annando** [comment]
Same is with mentions.

**Comment by tobiasd** [comment]
This is fixed by now, so I'm closing the issue.
