### ISSUE TITLE
URLs with äöü are broken

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#4741]
write post with URL with ä, ö or ü in it like
https://de.wikipedia.org/wiki/Rübezahl
without changing it to https://de.wikipedia.org/wiki/R%C3%BCbezahl

**Currently**

The URL is onlyhttps://de.wikipedia.org/wiki/R and "übezahl" is normal text. By that the link is broken.

**Expected**

äöü can exist in URLs, so they should not break them.

**Comment by MrPetovan** [comment]
Thanks for the report, this is a known issue with no simple solution:  #2487

Closing this issue as a duplicate.
