### ISSUE TITLE
communityhome addon vanished from admin/addons

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4756]
communityhome addon vanished from admin/addons (develop branch)

### Friendica version you encountered the problem

Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259

### Friendica source (git, zip)

git develop

### PHP version

7.0

Discussion (German):
https://forum.friendi.ca/display/a8e4f565205ac674259bedf981883647

**Comment by MrPetovan** [comment]
The addon has been marked as “Unsupported”, options are either not working or slow as heck.

**Comment by AlfredSK** [comment]
Slow? There was a problem with one option. That one was removed. I think it is working well now.
See: https://forum.friendi.ca/

**Comment by MrPetovan** [comment]
Please see https://github.com/friendica/friendica-addons/pull/539
