### ISSUE TITLE
White page after git clone ...

### ISSUE THREAD

**Issue by jodumont** [friendica/friendica#4769]
### Expected behavior
Having a page to start the installation

### Actual behavior
Having a white page
but my PHP works fine because I'm able to see opcache if I download this [php file](https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php) in the same directory

### Steps to reproduce the problem
Actually you could :
````
git clone https://github.com/jodumont/docker-image-friendica.git
cd docker-image-friendica
docker build -t friendica .
docker run -tp 443:443 friendica
````

### Friendica version you encountered the problem
3.6

### Friendica source (git, zip)
git but I also try via zip with the same issue

### PHP version
7

### SQL version
percona 5.7 from (https://hub.docker.com/r/library/percona/)

**Comment by tobiasd** [comment]
Have you run the `php bin/composer.phar install` command after the git pull  during the initial setup/cloning of Friendica?

**Comment by jodumont** [comment]
@tobiasd no why ;)
just kidding

I saw you add the installation tag, could you give me I link where I should found this info
because from the main website I finish here (https://github.com/friendica/friendica/releases) and 
ended to run `php util/composer.phar install`

**Comment by MrPetovan** [comment]
Check this out: https://github.com/friendica/friendica/blob/master/INSTALL.txt

In the next release the Composer.phar executable as been moved to `/bin`, see

https://github.com/friendica/friendica/blob/develop/INSTALL.txt

**Comment by tobiasd** [comment]
The release notes are mentioning it in the section about "Updating using git from the stable branch", as the changes were done to the development branch some time ago and everybody on develop had most likely already picked up composer into their updating chain as it was communicated over the dev channels before.

For new installations, please read the INSTALL.txt, there it is mentioned in the section when installing from github (you don't need to do this, if you install from the provided friendica-full-3.6 archive files as they include the dependencies).
