### ISSUE TITLE
Wrong status ID in statuses/networkpublic_timeline

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4772]
### Expected behavior
When calling `api/statuses/networkpublic_timeline.json`, we get an array of status objects and they each have an ID.
This ID can then be used to call `api/statusnet/conversation/[id].json` to get the full conversation.

### Actual behavior
I get this:
```json
{
    "text": "Ceci est un test.",
    "truncated": false,
    "created_at": "Wed Dec 27 19:49:00 +0000 2017",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "source": "Friendica",
    "id": 34,
    "id_str": "34",
```

But when I call `api/statusnet/conversation/34.json`, I get this error:
```json
{
  "status": {
    "error": "There is no status with this id.",
    "code": "400 Bad Request",
    "request": "api/statusnet/conversation/34.json?count=20"
  }
}
```

(It seems the correct URL here is  `api/statusnet/conversation/33.json`.)

### Steps to reproduce the problem
1. Open the federated timeline in Twidere.
2. Touch a specific status.

### Friendica version you encountered the problem
2018-05-dev (232d1009e56744d064908b1c1803153d211efdad)

### Friendica source (git, zip)
git

### PHP version
7.0.27-0+deb9u1

### SQL version
MariaDB 10.1.26-0+deb9u1

**Comment by MrPetovan** [comment]
Closed through #5015
