### ISSUE TITLE
Why won't Friendica federate with other networks if it is installed in a subfolder?

### ISSUE THREAD

**Issue by karbovskibg** [friendica/friendica#4774]
hi there.

Why friendica had to be installed in friendico.yourdomain.com or why friendico had to be install on index.php to enable other connector like mastordom to work in the moment i can't remember the names but in web menu it comment that friendico had to be installed on general root to work with other friendico servers

**Comment by MrPetovan** [comment]
Hi @karbovskibg, this is due to the way Webfinger addresses work. A Webfinger address is [username]@[domain].[tld], very much like an email address. These address are widely used by many federated social networks. It means that [username] has an account on the [domain].[tld] server. You'll note there isn't any mention of a subfolder, only a domain (that can be a subdomain).

A Friendica node will work in a subfolder, and will be able to federate with other Friendica nodes, but due to the limitation of Webfinger and the other federated social networks, it won't federate with Diaspora pods and Mastodon instances.

**Comment by karbovskibg** [comment]
hi petovan. If friendico only works in general root, then developers of friendico can make redirect from root to subdomain. petovan you are developers fail to make this rediction mean you are limiting peoples to communicate with other humankind, petovan you developers of friendico are like governments if you don't have money you can do nothing. petovan in friendico it comment: friendico descentralizaed social network " so this mean, freedom is FORCED.

**Comment by MrPetovan** [comment]
I'm not sure what you are saying about a redirection but I sure have no problem forcing people to be free although I don't think that's what we are doing here.

Bottom line:
- You CAN host a Friendica instance in a subdomain
- It WILL work out of the box in a subdomain
- Federation ISN'T guaranteed

**Comment by AlfredSK** [comment]
I want to buy an A.

**Comment by karbovskibg** [comment]
petovan lets see:

friendica is insalled in: yourdomain.com/friendica

When we go to: admin ->  Enable Diaspora support Diaspora support can't be enabled because Friendica was installed into a sub directory. 

Now petrovan why in subfolder friendica is not working 100 % and in root of ruby: http://yourdomain.com friendica is working.

petrovan simple: Now if friendica is not working in subfolder: http://yourdomain.com/friendica and you petrovan are developer then you can make redirection. If friendica works from: http://yourdomain.com then make for this peoples who install friendica in subfolder. redirection -> http://yourdomain.com/friendica go to http://yourdomain.com and when peoples want to Enable Diaspora support Diaspora support it will work.  in the moment diaspora don't work becouse friendica is in subfolder.

**Comment by MrPetovan** [comment]
Diaspora is requesting specific bits of information from Friendica servers like http://yourdomain.com/.well-known for example.

If Friendica is installed in a subfolder, these requests will fail and Diaspora connections will fail because Diaspora doesn't expect Friendica nodes to be installed in a subfolder.

**Comment by karbovskibg** [comment]
petovan now you resolve your question for redirection.

**Comment by karbovskibg** [comment]
developers of friendica. Why you are limiting peoples to use 100 % friendico. petrovan so you comment, installing friendico in general root: yourdomain.com driaspora will work and installing friendico in subfolder: yourdomain.com/friendica it will not, becouse it don't contain some missing .well-known
developers of friendico, but this is SHAME, for some .well-known you can't use 100 % friendico. make redirection user install yourdomain.com/friendica and turn diaspora on, diaspora connect and redirection go to name where user make subfoler, from there friendico creata .well-known " what create: well known women tits, bananas, digs, nude body... 21 century all peoples thinks for women, men and etc." after redirection it will be http://yourdomain.com/friendica/.well-known " and here goes women, men and etc. "

**Comment by annando** [comment]
Just imagine that someone installs Diaspora and Friendica on the same machine (this does happen) and the user installs Diaspora on http:://server.tld and Friendica on http://server.tld/friendica.

Diaspora works with hard coded endpoints, like ```/receive```. If we now would redirect the ```/receive``` to ```/friendica/receive``` then the Diaspora installation would stop working.

**Comment by karbovskibg** [comment]
annando hi.

are you developer or not. like petovan you reaolveyour question with redirection. annando it wilp be direct to developer diaspora amd ask them to open gate for friendica if not then make redirection from /refirect to /redirectfriendica. what kind of information diaspora wants to work in subfolder. in the moment it only wants /.well-known " but what: bananas, apple, food and etc. " and annando dont imagine becouse this is real, women who install diaspora and friendica on the same machine is insecure women.

**Comment by MrPetovan** [comment]
> women who install diaspora and friendica on the same machine is insecure women.

We don't need this kind of sexist comment here, please bring them elsewhere.

As for your question about federation when Friendica is installed in a subfolder, I believe we answered it and will be closing this issue now.
