### ISSUE TITLE
Delete old rss feed posts automatically 

### ISSUE THREAD

**Issue by rocky-III** [friendica/friendica#4775]
### Friendica version you encountered the problem

see `example.com/friendica` on your Friendica node for the version information.

**Comment by rocky-III** [comment]
i would be cool to have a plugin / funktion to Delete old rss feed posts automatically  after a certain time period (let's say after 30 days) . RSS feeds producing many posts, which I want to deleted automatically after a certain time period.

https://squeet.me//display/94c637c7155ac31d4ac8944823210769

**Comment by MrPetovan** [comment]
There is a user settings to delete old posts (including RSS feeds) In Settings -> Security and Privacy. You may want to check in "Advanced Expiration Settings" to prevent your posts to be expired.

**Comment by MrPetovan** [comment]
Also, the conversation you linked led to the creation of this issue: #4735, closing this one as duplicate.

**Comment by rocky-III** [comment]
Ok didn´t found the #4735 - so looking forward to see this New Feature. Thanks
