### ISSUE TITLE
Database Connection - Use environment variables (optional setting)

### ISSUE THREAD

**Issue by M-arcus** [friendica/friendica#4791]
I am currently creating a Dockerfile for a selfhosted server-solution (cloudron). During first testing, I have encountered the following problem:
 
### Problem
The MySQL credentials change at every start of the docker container, meaning the container only works at the first run. But the MySQL credentials can be accessed per `getenv()`.

### Proposed solution:
Add a config setting 'Get MySQL-Connection from Environment Variables'
Set the default `false`, so it doesn't break anything for existing installations.
If set to `true`, the credentials will be taken from the Environment Variables per `getenv()`.

I would open a PR for it, if you agree to adding this feature

**Comment by MrPetovan** [comment]
This is similar to #4784, except that it concerns the install process, while your proposed solution would be bypassing the install for MySQL config, am I right?

**Comment by MrPetovan** [comment]
Here's my question then: do we need to choose between either implementation or can we have both at the same time?

**Comment by MrPetovan** [comment]
Then by all mean, submit a PR.

**Comment by karbovskibg** [comment]
M-arcus and don't include real things that women kick men becouse petovan and ananndo don't want to read it. petovan and annando you have to face the real life ad other peoples. no women violence for men.

**Comment by nupplaphil** [comment]
hm @M-arcus .. how do we sync changes from here and maybe #4784 to not break each other? How much is your progress so far? So shall I will wait with my approach/changes until you're finished?

**Comment by M-arcus** [comment]
Fixed by #4855

**Comment by M-arcus** [comment]
Documentation needed.
@MrPetovan Should I open a new issue for it?

**Comment by MrPetovan** [comment]
I just added the label, hopefully someone (maybe you?) will pick up on it.

**Comment by tobiasd** [comment]
@M-arcus could you write the docs for this?

**Comment by M-arcus** [comment]
@tobiasd yes, will do

**Comment by MrPetovan** [comment]
Thank you for your work!
