### ISSUE TITLE
Pending registrations different information on different admin pages

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4804]
### Expected behavior
Same info from 
  * /admin page 
  * /admin/users/ page 
about the number of registrations. In my case this number should be 0 (zero).

### Actual behavior
On the /admin page I have the info
>     Pending registrations  **6** 

On the /admin/users/ page it says
>    User registrations awaiting confirmation
>    **No registrations.**

### Steps to reproduce the problem
I don't know. I have just to click on those pages ;)

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259
### Friendica source (git, zip)
git
### PHP version
PHP Version 7.0.29-1~dotdeb+8.1
### SQL version
MariaDB

**Comment by MrPetovan** [comment]
I can reproduce this, I have a mysterious one pending registration that doesn't appear in the Users panel.

**Comment by miqrogroove** [comment]
I've seen this as well.  On the back end, there are some stale records from when I was toying with the invitation system.  Somehow, invitation codes are being counted here instead of actual users.

**Comment by hoergen** [comment]
Interesting and would make sense.
There should be a duration an invitation is effect like a week or so. And then the invitation will be invalid.
And the invitation should be visible on the admin users page with email. So you have an overview.

**Comment by miqrogroove** [comment]
Check the register table schema.  I'm pretty sure it doesn't have any email, it's just the codes and dates.

**Comment by hoergen** [comment]
Thanks ther were a lot of spam thingys. I deleted it ;)
