### ISSUE TITLE
Adding contact by @user@example.com does not work

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#4815]
### Expected behavior
Adding a contact via the form "Neuen Kontakt hinzufügen - Adresse oder Web-Link eingeben" in /contacts should add the contact with a leading @ in front of the username, so @user@example.com should work and user@example.com and https://example.com/profile/user, the last two do, the first doesn't. 
This is confusing as the search works with @user@example.com just fine. 

### Actual behavior
A page with "protocol not recognized" shows up. 

### Steps to reproduce the problem
Go to /contacts and add a new contact with the @@ handle. 

### Friendica version you encountered the problem
Current develop. 

### PHP version
7.2.x

**Comment by annando** [comment]
In the search you have several options to search for stuff. "#" for hash tags, "!" for forums and "@" for contacts. This prefix is needed for the separation.

**Comment by MrPetovan** [comment]
Yes butwe still could add contacts with a leading `@`.

**Comment by jranma** [comment]
Confusing behavior still present in version 2019.06
If you add a mastodon (possibly other services) user with the @user@host format, servers reply "The network type couldn't be detected. Contact can't be added". Remove first @ and it's working fine.

**Comment by MrPetovan** [comment]
Thanks for the additional testimony.

**Comment by annando** [comment]
@jranma it depends on where you enter this. When you use the top search bar, then it has to be with a leading ```@```.

**Comment by MrPetovan** [comment]
I think it is in the contact add field.

**Comment by annando** [comment]
Yeah, possibly we could simply removing leading ```@``` if added - or we simplify the system and only allow contacts to be added in the search bar?

**Comment by AlfredSK** [comment]
I would like to suggest to remove the @ silently when the add-contact-box is used.

**Comment by MrPetovan** [comment]
Closed by #7329
