### ISSUE TITLE
Info: forum.friendi.ca down

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4826]
There is a major incident with my provider. 😭 forum.friendi.ca is down at the moment. There's nothing I can do about it. The machine is running but the network connection is gone. I'm sorry. 😞
See here: http://status.df.eu/ and here: https://mastodon.social/web/statuses/99848958269329558

**Comment by MrPetovan** [comment]
You should have posted on the Friendica Support forum... wait.

**Comment by AlfredSK** [comment]
The forum is reachable again. Closing...

**Comment by tobiasd** [comment]
There are email lists, and IRC / Matrix rooms as well.
