### ISSUE TITLE
Approve diaspora members in forums

### ISSUE THREAD

**Issue by AgnesElisa** [friendica/friendica#4843]
I made a forum in Friendica and have some Diaspora members who follow the forum.
The forum is set to be private. When a Friendica member tries to join the group, I get a request that I can approve (either as a friend or a as subscriber). This is how it should work. I expected the same for Diaspora members.

However, Diaspora members can just join. As soon as they request to subscribe to the group, they are subscribers, as if it is an open forum.

So in short:
I created an account, set it to be a community forum, chose private forum as an option, and shared it globally and had both Friendica (works fine) and Diaspora users (no approval process) join.

Please note I know very, very little about coding, but judging from what I have read about other problems with communication between Friendica and Diaspora, I think it may be quite some work to fix this properly. I think a possible work-around solution could be if a forum can be set to post to a group of its members by default (for instance "group1"). This way, when someone enters the forum they are automatically added to "group2", but will only receive posts when they are manually added to "group1" by the account manager. I cannot find if this is possible already.

### Friendica version you encountered the problem
I encountered this problem on Friendica, version 2018-05-dev running at web location https://libranet.de

That's all I know!
Please give me feedback if this is not the right place/way to share the issue

**Comment by hoergen** [comment]
Is this fixed? Because there are some people that want to have a private Forum for themselfs and they surely don't wont some random people in there.

**Comment by AgnesElisa** [comment]
I'm not entirely sure because it's months ago, but I don't think it was fixed. Hopefully someone else knows

**Comment by annando** [comment]
I don't know either.

**Comment by hoergen** [comment]
Maby this fixed the problem https://github.com/friendica/friendica/pull/4882

I tried it today from diaspora and it worked like described in the issue. Neither the diaspora contact could read a post nor could the diaspora contact send posts to the private forum. 

So we could close this issue, if everybody agree ?
