### ISSUE TITLE
Allow hidden input of password in bin/console newpassword

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4860]
### Expected behavior
setting new password works

### Actual behavior

Is not working
```
PHP Warning:  mkdir(): Permission denied in /path2friendica/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 316

PHP Warning:  mkdir(): Permission denied in /path2friendica/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 316

PHP Warning:  file_put_contents(): Filename cannot be empty in /path2friendica/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 86
```

The line 86 is  $result = file_put_contents($filePath, $cacheFileData); (surrounded by)
```
        $cacheFileData = json_encode($cacheObj);

        if ($this->config['gzipCompression']) {
            $cacheFileData = gzcompress($cacheFileData);
        }

        $filePath = $this->getFilePathFromKey($key);
         $result = file_put_contents($filePath, $cacheFileData);

        return $result ? true : false;
```

### Steps to reproduce the problem

in friendica dir `bin/console newpassword Username`

### Friendica version you encountered the problem
2018-05-dev
### Friendica source (git, zip)
git
### PHP version
7
### SQL version
mysql  Ver 15.1 Distrib 10.0.32-MariaDB,

**Comment by hoergen** [comment]
I already set a new password a week ago. There it worked. I'm on the latest git pull ;)

**Comment by MrPetovan** [comment]
Grmbl. This is going to be yet another "but this works on my machine" issue I can't reliably reproduce. I'll check which directory was supposed to be created tonight.

**Comment by hoergen** [comment]
Little Off-Topic: As I already wrote to @annando  I believe there is something living in my database and waiting to cause trouble. I exchanged in the last year twice the whole directory with a new git pull and I moved to a new server and a new database. And I still have some weird things happening. I already tried to compare different user with each other and other things to come behind that ghost in the machine. But I wasn't lucky yet.

**Comment by MrPetovan** [comment]
This issue actually sounds more like a down-to-earth permission issue.

**Comment by hoergen** [comment]
I did a git pull git pull tried it again and it worked. We should close this issue with the comment "Ghost is tired now"
BUT I didnt put a password at the end of the ommand, because I don't wan't to have it in my bash history. And it said "Password" changed ? So there is no password at the moment? 

Could this command ask for a password and not showing it, while im typing it in the console?

**Comment by MrPetovan** [comment]
This is a very interesting question, please keep this issue open and change the title to "Allow hidden input of password in bin/console newpassword"
