### ISSUE TITLE
Occasional broken posts when relay enabled, possibly just from Diaspora

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#4862]
### Expected behavior
The content of a post is brought in appropriately.

### Actual behavior
Random other posts show up instead.

### Steps to reproduce the problem
Seems to be related to having the relay enabled, but this is only anecdotal so far.   In fact, Michael Vogel suggests it's not related.  

An example broken post: https://social.isurf.ca/display/1e24c5c0254401365e6f2aaaaae32306
The original post: https://diaspora.natrinicle.com/posts/1e24c5c0254401365e6f2aaaaae32306

Another example: https://social.isurf.ca/display/a833fac0254301365e732aaaaae32306
Original: https://diaspora.natrinicle.com/posts/a833fac0254301365e732aaaaae32306

Support forum discussion: https://social.isurf.ca/display/c443a55c605acb9ae0c5dd9451651276

### Friendica version you encountered the problem
3.6 Stable

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
MariaDB 10.0.32-0+deb8u1

**Comment by annando** [comment]
The relay has nothing to do with this. It happened before as well.

**Comment by MrPetovan** [comment]
Is this still happening after #4865 ?

**Comment by realkinetix** [comment]
Fortunately, I haven't noticed this issue in quite some time now, I suspect it did get resolved.

**Comment by MrPetovan** [comment]
Closed via #4865
