### ISSUE TITLE
Short statistic on the directory servers

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4866]
I think it would be helpful to have a very short statistic on our directory servers about the size of the friendica network. 

I thought about a line like "**There are 300 Friendica servers overall and 10 Friendica that are open for public registration**". Or something like that.

This idea came from when I was watching the-federation.info and saw only 66 friendica servers whereas my servers statistic sees nearly 300 servers. This pushes people away that are new to the topic federated social networks. Even people that are already familiar with it e.g. coming from GNUSocial just look at  those numbers, keep asking if this is a serious project.

**Comment by AndyHee** [comment]
Not sure this is the right place here @hoergen.

I think the issue should be raised here: https://github.com/friendica/dir

**Comment by MrPetovan** [comment]
@AndyHee is right, please move the issue over to the https://github.com/friendica/dir projects that has its own set of Issues.

**Comment by hoergen** [comment]
Thanks for telling me. I wasn't really aware of it. Here is the issue now https://github.com/friendica/dir/issues/44
