### ISSUE TITLE
Guess language from the plaintext version of posts' body

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4867]
Currently, short posts with an URL trigger the language filter even with a content limit set and the guessed language is often wrong because it includes the URL.

I want to extract the plaintext from items' body, run the language guesser on the plaintext only, and match the character limit of the `langfilter` addon against the plaintext body as well.

This would add another column to the `item` table with the plaintext content to avoid repetitive content parsing.

**Comment by MrPetovan** [comment]
That's the conclusion I was reaching yesterday after it took a couple hours to add a field to my `item` table. I even wanted to put the language information in a separate table whose creation would be triggered by the `langfilter` addon since we don't use it for anything else in Friendica anymore.

**Comment by annando** [comment]
Same goes possibly with the item cache. This possibly could be stored in a single field as well. Possibly you could name this table "item-content" or something comparable. Then we could use it at some base for the redesign.

**Comment by tobiasd** [comment]
There are other addons that use this information as well. E.g. my [Typography](https://bitbucket.org/tobiasd/friendica-typography) one. I cannot find the other link ATM

**Comment by annando** [comment]
Please so everything with the "item" class. And please use the ```uri``` as a link.

**Comment by MrPetovan** [comment]
Ah, interesting, since your addon wasn't part of the friendica-addons repo, I couldn't find any other usage than the `langfilter` addon.

**Comment by MrPetovan** [comment]
@annando 
> Please so everything with the "item" class.

I'm sorry what?

**Comment by annando** [comment]
"do", not "so" ;-)

**Comment by MrPetovan** [comment]
Why `uri` and not `item.id`? The current item cache is personal to each user because of the zrl tag.

**Comment by annando** [comment]
When a post is distributed to 10 users, you have 10 different values in the ```id``` field - but a single ```uri```. Concerning the ```zrl```: I knew that there was a problem :-( So we have to change that as well. (Put it on my list)

**Comment by MrPetovan** [comment]
Which list? Where is it? How long is it?

**Comment by annando** [comment]
To the moon and back, I guess.
