### ISSUE TITLE
upload of picture in a private message not working

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#4868]
Upload of picture in private message not working (anymore). I can upload a picture in a post, but not in a private message. 

I use Frio and Friendica with the current dev. branch, the problem was confirmed by @rabuzarus as well.

Referenz Friendica: https://social.yl.ms/display/4029d2ca955ad87b3a4c7a2429183972

**Comment by tobiasd** [comment]
I think it is not only Frio having this problem.
