### ISSUE TITLE
Make the item language metadata into a neat array

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4869]
Prompted by https://github.com/friendica/friendica-addons/pull/586

Currently, the guessed languages are stored in the `postopts` field which is an amalgamation of information rather hard to query.

The same way we format the list of tags into an array before display, I'd like to store the language data in a separate array for use by the Advanced Content Filter addon.

**Comment by bkil** [comment]
Yes, that would be useful.

For example, while language detection could sometimes make a mistake in picking the most likely language, I wouldn't expect the real language to be missing from the top 3 candidates.

**Comment by annando** [comment]
The language is now stored in the `language` field in the `post-content` table. It is stored there as JSON encoded string.

**Comment by MrPetovan** [comment]
Good to know, but it still isn't something than we can easily query in the Advanced Content Filter addon, we would need to decode it first.

**Comment by bkil** [comment]
Maybe a regexp could do the trick, depending on the use case. I'll have a look tomorrow.

**Comment by annando** [comment]
Why not simply use the result of `json_decode`?

**Comment by MrPetovan** [comment]
Because someone™ has to add the result of `json_decode` to the array we pass to the content filter.

**Comment by annando** [comment]
Well, `language` is part of the `item` array that is passed via the `prepare_body_content_filter` hook.

**Comment by MrPetovan** [comment]
Thank you for the added technical detail, I wasn't saying it is difficult, I just pointed out that it doesn't exist yet and work has to be done to do it.

**Comment by MrPetovan** [comment]
Addressed in https://github.com/friendica/friendica-addons/pull/1097
