### ISSUE TITLE
Login Dialog is Confusing

### ISSUE THREAD

**Issue by astifter** [friendica/friendica#4878]
As discussed in [the forums](https://forum.friendi.ca/display/e18176ef375ad770f8ca3c8135838652) the login page is quite confusing.

I have rearranged the login dialogs for vier and frio: https://github.com/astifter/friendica/tree/reorganize_login.

Enjoy.

**Comment by MrPetovan** [comment]
Can you please provide screenshots before/after?

**Comment by astifter** [comment]
I can only privde "after" quickly, before can be seen here (https://nerdica.net) or (https://friendica.togart.de)



![screenshot_20180421-123419](https://user-images.githubusercontent.com/206846/39083163-64e43e5c-4560-11e8-841f-1144a77d7f93.png)
![screenshot_20180421-123355](https://user-images.githubusercontent.com/206846/39083164-69bd2330-4560-11e8-866a-e1c3e09e66fe.png)

**Comment by MrPetovan** [comment]
I have a change suggestion, can you please submit a PR from your branch against `friendica/develop`?
