### ISSUE TITLE
PHP 7.2 Improvements

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#4898]
Some improvements need to be made in several PHP files in order for it to be fully compatible with version 7.2. The errors or warnings that have flagged up so far are:

Upon manually running the worker Cron job:
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/site/public_html/include/dba.php on line 969`

Upon entering the settings page:
`Warning: Use of undefined constant self - assumed 'self' (this will throw an Error in a future version of PHP) in /var/www/site/public_html/src/Util/Temporal.php on line 62`

Upon adding a contact:
`Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/site/public_html/src/Model/Profile.php on line 95`

Upon clicking the Global Community tab:
`Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/site/public_html/src/Object/Post.php on line 81`

Upon entering example.com/friendica
`Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/site/public_html/mod/friendica.php on line 126`

Running Friendica version 2018-05-dev with no addons
installed 21/04/2018
PHP 7.2.4
MariaDB 10.2
Apache 2.4.33

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by MrPetovan** [comment]
Please update to the latest develop, `include/dba.php` has been modified and the line number doesn't match any `count()` any more.

**Comment by MrPetovan** [comment]
Nevermind, I found the culprit back.
