### ISSUE TITLE
Optional use .htconfig.php instead of htconfig.php in AutomaticInstallation.php

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#4899]
I'm currently creating an automatic installation shell script for docker-usage and try to use the console command `autoinstall` in `Core/Console/AutomaticInstallation.php`

Therefore I automatically create the complete `.htconfig.php` with the shell script.

But at
https://github.com/friendica/friendica/blob/ea4e9b2cce3647be0704bde71ea8511ed349ca80/src/Core/Console/AutomaticInstallation.php#L44
it is using the prepared `htconfig.php` for the installation.

What about **optionally** using the `.htconfig.php` instead of the `htconfig.php` and skip creating the `.hconfig.php`? What do you say @M-arcus and @MrPetovan? It's an enhancement for #4849

**Comment by MrPetovan** [comment]
The `htconfig.php` just is a template for the final `.htconfig.php` so you'd be better checking in the `.htconfig.php` is present first.

**Comment by nupplaphil** [comment]
So the process would be:
- check if `.htconfig.php` is present
- if it is, check if Friendica is already installed
- if so, return with info "already installed"

- if there's no `.htconfig.php`, do like the current implementation

- if there IS a `.htconfig.php` , use it instead of creating it

That would work, wouldn't it?

**Comment by nupplaphil** [comment]
Ah sorry @M-arcus , I didn't refresh the page

Yes that would work too I think :-)

**Comment by nupplaphil** [comment]
Solved with #4697
