### ISSUE TITLE
frio: search in /contacts doesn't work for username

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4923]
### Expected behavior
search for username like myname@domain.tld should find the `myusername`
Dosn't work in frio, but works in vier

### Actual behavior
only works with the users first- and lastname.

### Steps to reproduce the problem
Just use the search.

Problem with all that is, that some ☇☈☋♐⚔ people are using symbols instead of characters, then you can't find them via search and you have to scroll all of your contacts.

### tec
Friendica version: 2018-05-dev
Friendica source: git
PHP version: 7.0
SQL version: mariadb

**Comment by MrPetovan** [comment]
🙈

**Comment by rabuzarus** [comment]
do you mean the nav search. If so, it would be very strange because vier and frio use the same code

**Comment by hoergen** [comment]
The search on the contact page

![00_temp](https://user-images.githubusercontent.com/24474762/39192855-72814f1a-47da-11e8-9f0b-e0284c2e96c9.png)

**Comment by zeroadam** [comment]
This is because the emoji that @MrPetovan is using is not an "o"

**Comment by hoergen** [comment]
@zeroadam I know, but in vier the search is searching on the "name" and on the "username" . 
There I can find hyp and hypo.

**Comment by MrPetovan** [comment]
If you click on "Find" with "hypo", does my account show up?

**Comment by hoergen** [comment]
As soon I click on it, it finds it. 
But I think 9 of 10 people (including me) wouldn't click additionally on the "Find" button, when they already "felt" the ajax feature.  Why should they ?

**Comment by MrPetovan** [comment]
I was just making sure of the precise use case. The contact autocomplete feature is pretty janky, it only holds part of your contacts, and like you found out it doesn't look for usernames. That's why I'm systematically using the Find button (the Enter key doesn't even work 😕 ).

I personally would like to remove the contact autocomplete feature as we tried to fix it, and it didn't completely worked out. And now it shows again it's subpar compared to the native contact search.

**Comment by tobiasd** [comment]
Which contacts are missing? Is there a pattern in that; for me all seem to be there.

**Comment by MrPetovan** [comment]
Like @hoergen found out, the autocomplete doesn't search on username, only display names. For this reason, the number of accounts shown for a specific autocomplete string will be different from the number of accounts shown using the actual search form.

This autocompletion feature isn't warranted anyway as it already is a search field.

**Comment by tobiasd** [comment]
Strange, works for me. I can search e.g. for `helu` and `Mich` and get @annando in the suggestions.

**Comment by MrPetovan** [comment]
When I'll rewrite the ACL selector this autocomplete will come in handy, but it isn't necessary in the contacts page and as such it's better out if we have any problem with it.
