### ISSUE TITLE
frio: Rename "Default" color scheme as "Custom"

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4927]
It took me a while to figure out I could only change frio's color by selecting the "Default" theme.

It should be renamed "Custom" to clear confusion about what it truly is.

**Comment by rabuzarus** [comment]
No, theoretically you can also change the color of the other schemes. But it is up to the scheme which colors are allowed to change E.g. for the red scheme https://github.com/friendica/friendica/blob/develop/view/theme/frio/schema/red.php#L7

**Comment by MrPetovan** [comment]
And that’s great, but you still are stuck with the overall red color. If you want to change the red color, you look for a “Custom” scheme, not a “Default” one.

**Comment by rabuzarus** [comment]
yes, but theoretically other schemes could be added which would allow to change the same things like the Default schema. Maybe we should rather work on something which updates the color fields immediately after selecting a new color scheme

**Comment by MrPetovan** [comment]
Why not create an additional “Default” scheme where nothing can be customized, as the name suggests?

**Comment by rabuzarus** [comment]
This is of course also possible. 
If I remember correctly, some wanted the red theme to be the default theme..

**Comment by MrPetovan** [comment]
I'm going to change the name to "Custom" and create a new "blue" theme.
