### ISSUE TITLE
Update default Friendica Directory URL protocol

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4938]
See: https://friendica.mrpetovan.com/display/39bbe52a105ae33c8bbc2a9127337153

The "http" protocol part in the default directory URL setting prevents submissions to the Friendica directory.

The required changes are:
https://github.com/friendica/friendica/blob/241ed9a9cd3254db0afe63c78f2c367b6f8a7a05/util/htconfig.vagrant.php#L67-L69

https://github.com/friendica/friendica/blob/8d8aef5624d9992464be432ffe775dad55a6bb4f/boot.php#L1294-L1296

https://github.com/friendica/friendica/blob/69a7afc577b85a57bc04f676d273866191ab8462/view/templates/htconfig.tpl#L109-L111

**Comment by annando** [comment]
Big question is: Is it a problem on the server (web server configuration) or on the client (Friendica core)?
