### ISSUE TITLE
mobile_theme isn't set in table pconfig

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4946]
On the forum node (3.6 master) I have set vier as system theme. If I create a new account and then change the user's theme to frio it only works in desktop mode. On mobile devices vier is still in use. **The reason is in table pconfig 'mobile_theme = ---' isn't set for the UID of the new account.** In fact the entry for mobile_theme is missing completely. I had to add it manually to the DB to make it work.

### Expected behavior
When setting a theme in settings display it should also work on mobile devices.

### Actual behavior
The system theme is used instead.

### Steps to reproduce the problem
Set system theme to vier. Register a new account. Login and change the user setting display/theme to frio. Take a smartphone and look at the profile page of the new user.

### Friendica version you encountered the problem
3.6 master

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 MariaDB

**Comment by AlfredSK** [comment]
I have only enabled vier and frio in Admin/themes. So there is no special "mobile theme" like 'frost' available on the node. Dunno. Maybe this has something to do with the described behavior.

**Comment by MrPetovan** [comment]
Can confirm the mobile theme is set to the system theme when the mobile-theme user config is missing or blank.

**Comment by tobiasd** [comment]
Yes, as expected. If the user has no theme selected, the systems theme is used. Question is what system theme is selected for the mobile theme.

**Comment by MrPetovan** [comment]
It should defaults to the user base theme, not the system theme. The problem is that we use `---` to indicate no mobile theme, but we test for empty string as well with a different outcome. Both should default to the user's theme. I'm working on a fix that brings more global functions from `boot.php` into classes.

**Comment by AlfredSK** [comment]
> If the user has no theme selected, the systems theme is used. Question is what system theme is selected for the mobile theme.

In my case system theme is vier. And in admin/site 'no special theme for mobile devices' is set. If the user changes his theme to frio the theme for mobile devices doesn't fall back to the user theme (frio) but to the system theme (vier).
Solution one: always fall back to the user theme if no mobile theme is set
Solution two: force the setting of a mobile theme in pconfig when the user changes his theme
