### ISSUE TITLE
addon: blockem doesn't collapse comments of blocked persons anymore

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4947]
### Expected behavior
Comments of blocked profiles/persons should be displayed collapsed.

### Actual behavior
I have several entries separated by commas. Comments aren't collapsed. I'm pretty sure it worked yesterday or the day before yesterday. :-)

### Steps to reproduce the problem
Well, add some profile URL to the blockem settings and reload your network stream.

### Friendica version you encountered the problem
2018-05-dev

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
MariaDB 10.0

**Comment by MrPetovan** [comment]
I can't reproduce this, did you make sure to use the full profile URL in the blockem settings?

**Comment by AlfredSK** [comment]
Yes. I'll look into this later again.
All I can say for now is that comments of one user aren't collapsed anymore. It had worked until yesterday. I didn't change anything to the blockem config.

**Comment by MrPetovan** [comment]
Ah, it's about comments, I checked top level posts, it's a good hint, I'll try again with comments.

**Comment by MrPetovan** [comment]
Still can't reproduce the issue with comments, please check you have commas between each profile URL. I'd really like to turn this field into a new line separated field.

**Comment by AlfredSK** [comment]
I checked the list like 10 times. Every entry is separated with a comma and a space. I also tried commas only. Doesn't work.
But I've put a friendica profile URL into the list now. Works!
Then I've added a hubzilla channel URL. Works too!
And another diaspora URL. That worked too!
The only difference is these people are contacts of mine. The one that doesn't work insn't a contact.

**Comment by AlfredSK** [comment]
It was a pleasure. :-D

**Comment by MrPetovan** [comment]
And now it works again ☹️

**Comment by MrPetovan** [comment]
I found the issue in the database. Some remote comments seem to have the wrong `contact-id` set, which leads Friendica to believe that some remote comment have been written by the current user, which disables the content filters.

**Comment by MrPetovan** [comment]
Or I just had no idea what I did initially when I wrote this code and nobody picked me up on it.
