### ISSUE TITLE
Message button on /profile/<user> is cropped in frio.

### ISSUE THREAD

**Issue by astifter** [friendica/friendica#4950]
When the screen width is below 1200px the second layout-breakpoint for frio is reached. This leads to a cropped message label in the profile-aside:
![screenshot-2018-4-28 friendic a stifter profile_photo](https://user-images.githubusercontent.com/206846/39400540-8b64de06-4b32-11e8-9afe-a099be17a1d1.png)

I suggest making the message-button 'width: 100%;' and remove everything else from style.css:1123 so that 
- the button looks the same with all breakpoints
- has a cleaner apperance because the sides align with the other text
- provide a nice separator between the heading (name, friendica-id) and the other profile information

![screenshot-2018-4-28 friendic a stifter profile](https://user-images.githubusercontent.com/206846/39400553-d1e32784-4b32-11e8-8a62-b4ebaec8a34e.png)

**Comment by MrPetovan** [comment]
Can you submit a patch?

Paging @rabuzarus and @fabrixxm to discuss the finer design points.

**Comment by rabuzarus** [comment]
No. The `Message` button and the `Connect` button are in one line to save vertical space. We should rather change the css only for small screens (button width is 100%) and leave it for larger screens as it is

**Comment by astifter** [comment]
Fixed in #5498.
