### ISSUE TITLE
Better tooltips when adding / removing contacts to groups

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#4965]
When editing groups there is a tooltip for adding / removing a contact to a group. Current tooltip may be a bit confusing.

**Currently**

en Add Contact / Remove Contact
de Kontakt hinzufügen / Kontakt löschen

**Suggested**

en Add Contact to Group / Remove Contact from Group
de Kontakt zur Gruppe hinzufügen / Kontakt aus Gruppe entfernen

Low prio but easy to fix. Also the tooltip is quite far away from the x + icon.

![bad tooltip en 2](https://user-images.githubusercontent.com/5708172/39467525-d3584e8e-4d2e-11e8-83d9-85fa81b25fea.jpg)
![bad tooltip en 1](https://user-images.githubusercontent.com/5708172/39467526-d370651e-4d2e-11e8-8d30-e8ce66ed44b1.jpg)
![bad tooltip 2](https://user-images.githubusercontent.com/5708172/39467527-d387cdd0-4d2e-11e8-8124-0f8c416e482c.jpg)
![bad tooltip 1](https://user-images.githubusercontent.com/5708172/39467528-d3a46760-4d2e-11e8-92cc-1a12ef2985bb.jpg)

**Comment by Quix0r** [comment]
Is this theme-depending?

**Comment by Quix0r** [comment]
And how do I update the language files? Fixing this in `mod/group.php` is one thing, but in i18n files is other.

**Comment by MrPetovan** [comment]
Once you have modified a translation label, you need to run `bin/run_xgettext.sh` from Friendica’s root and commit the changes to `util/messages.po`

**Comment by tobiasd** [comment]
So, this can be closed?

**Comment by MrPetovan** [comment]
No, the positioning hasn't been addressed.

**Comment by Quix0r** [comment]
According to @MrPetovan it is theme-depend and some "hacky" CSS.

**Comment by tobiasd** [comment]
I see, but that is nothing blocking for the May release I think so I'll move it to the August release.

**Comment by MrPetovan** [comment]
Please do!

**Comment by foss-** [comment]
https://github.com/friendica/friendica/issues/5095 done
