### ISSUE TITLE
find solutiontion to deal with old pump.io contacts / can not be remove currently

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#4966]
**Currently**

pump.io contacts are not showing up under contacts and thus can not be removed. they do show up though when searching contacts. results show "1 result" but then no contact is listed.

those contacts also show when editing groups. they can be added and removed from groups.

version: 2018-05-dev-1259

**Expected**

Unsure how to solve this. Ideally the contacts would show up under contacts and then could be removed by the user. If that is not possible should all pump.io contacts be removed backend-wise?

**Comment by foss-** [comment]
Was able to successfully delete some identi.ca / pump.io contacts. Closing this one and thanks to whoever fixed this.

**Comment by MrPetovan** [comment]
If pump.io contacts can't be deleted when the addon isn't activated, then deactivating the addon should remove all pump.io contact? 😅

**Comment by AlfredSK** [comment]
How about this: When a connector has been disabled archive all contacts after some grace time and add a note "unsupported network type" to the archived contacts. This would add some transparency to the process from the user's perspective and the archived contacts were still visible for the user.
