### ISSUE TITLE
[video] tag fails when URL contains a query string.

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4970]
See: https://friendica.mrpetovan.com/display/ec054ce7105ae843f3bbd0b369179784

The following example is rendered as text is despite being a valid video file URL:
```[video]https://video.twimg.com/ext_tw_video/991226583728906241/pu/vid/480x360/TYso7qIFeWXvZbu9.mp4?tag=3[/video]```

**Comment by foss-** [comment]
Looks like this may be related? https://github.com/friendica/friendica/pull/4989

**Comment by annando** [comment]
I wouldn't use the word "related" - but would state that this is **exactly** the fix for this issue :grin:

**Comment by MrPetovan** [comment]
Fixes through #4989
