### ISSUE TITLE
PHP 7.2 Warning

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#4971]
More PHP 7.2 Warnings:

`Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/friendica/include/items.php on line 66`

This one appears when inserting a web attachment in a new post

And another that I've picked up in the PHP Error log:

`PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/mass-trespass.uk/public_html/src/Protocol/PortableContact.php on line 1023`

On Friendica 2018-05-dev
PHP 7.2 FPM
Apache 2.4 
MariaDB 10.2

**Comment by MrPetovan** [comment]
Mentioned by Adam Clarke as well: https://friendica.mrpetovan.com/display/c443a55c105af8c214461fd636082134
