### ISSUE TITLE
notifyall - undelivered mail returned to sender because of malformed FROM

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4976]
I just tried to notify all users about the 'blocked contacs' bug. I was using the notifyall add-on.
I got more than 400 bounce mails because the FROM header is malformed.

```
550-5.7.1 [134.119.20.10      13] Messages with multiple addresses in From:
550 5.7.1 header are not accepted. m133-v6si221657wmf.59 - gsmtp (in reply
to end of DATA command)
```

How can this happen? I have two admin users configured in .htconfig.php: 

`$a->config['admin_email'] = 'xxxxx@libranet.de,yyyyy@libranet.de';`

So, notifyall added both mail addresses to the FROM field. But multiple addresses in From: header are not accepted.

**Comment by MrPetovan** [comment]
Good catch.

**Comment by AlfredSK** [comment]
@tobiasd Can we put this bug on the list of milestone 2018.05? Should be an easy-to-fix issue. :-)

**Comment by tobiasd** [comment]
You can fix it now ;-)

**Comment by AlfredSK** [comment]
I see. :joy: Unfortunately my PHP book hasn't arrived yet.

**Comment by tobiasd** [comment]
The addon takes the `sender_email` configuration value from the site settings, not the `admin_email` as far as I could see at the moment. `sender_email` should not contain more then one email addresses I think.

Could you check the settings from the admin panel -> site settings.

**Comment by AlfredSK** [comment]
Yes, I can. In admin panel...

Sender email: `admin@libranet.de`

In .htconfig.php...
````
$a->config['admin_email'] = 'alfred@libranet.de,admin@libranet.de';
$a->config['admin_name'] = "Steffen K9";
````
Oh! And it is even worse. I ckecked the source of one failed mail...
````
X-PHP-Originating-Script: 33:Emailer.php
From: Steffen@libranet.de, K9@libranet.de, LIBRANET.de Administrator <admin@libranet.de>
Reply-To: Steffen@libranet.de, K9@libranet.de, LIBRANET.de Administrator <admin@libranet.de>
````
Do you see? "Steffen K9" is translated into two mail adresses "Steffen" and "K9".

So, it takes the admin name and translates it into mail adresses AND puts the actual sender mail at the end. :-)

**Comment by tobiasd** [comment]
Ok, that makes more sense then ;-)

**Comment by tobiasd** [comment]
@AlfredSK you might want to try friendica/friendica-addons#601 it might help. I think the `,` in the constructed sender name is the problem, but I'm confused that it did not freaked out before.

**Comment by AlfredSK** [comment]
I will test sending 1000+ mails as soon as the PR is merged. Thank you!

**Comment by AlfredSK** [comment]
@tobiasd Yeah, I was kidding. I used the test mode of notifyall before. :-)
Btw. my own server doesn't complain about the From field. It delivers and receives the mail. 
Merely 50% of the mails were rejected on the original incident.

**Comment by AlfredSK** [comment]
Works! 👍
Fixed by https://github.com/friendica/friendica-addons/pull/601

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/601
