### ISSUE TITLE
Unfollow twitter contact in friendica

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#4983]
### Expected behavior
Deleting a contact on the twitter network via Contacts > Drop Contact would unfollow the contact on Twitter.

### Actual behavior
Currently deleting the contact in friendica results that they're just recreated as contacts in friendica when their new posts come in from the twitter network.

### Friendica source 
up-to-date develop

**Comment by annando** [comment]
The current behaviour is intended. For example: You can select to only see the content of a few of your Twitter contacts in Friendica. So you chose not to automatically create new contacts - and you delete all contacts - except the few you want to see in Friendica.

**Comment by AndyHee** [comment]
Thanks @annando for clarifying this! The use case you describe is plausible. 

I think, this is probably merely a documentation issue, as I was not the only person who felt something was missing.

I'll check it and improve the documentation by adding a detailed hint/explanation to this option "Automatically create contacts".

**Comment by AndyHee** [comment]
There is a PR here now to add an detailed description. https://github.com/friendica/friendica-addons/pull/610

However, I still think it would be nice to have a switch for deletion that would allow to specify whether to both delete in Friendica and on Twitter. In this way this option is not affected and we will have a more convenient interface.

If people think this is useful, could someone please change the labels and remove " Docs/Translation " and add " Enhancement". Thanks!

**Comment by AndyHee** [comment]
My apologies, I think my idea wasn't very clear.

So, Michael highlighted that it's possible to have a selective set of Twitter contacts on Friendica in comparison to who you actually follow on Twitter. This very useful and I have added an explanation for this option "Automatically create contacts"; in this case you don't enable this option to have selective contacts.

One of the current shortfalls of this addon is that you cannot unfollow someone on Twitter by dropping them as Friendica contact.

So the solution is would be something like this:

*Drop contact
*Ask whether to both unfollow on Twitter and to drop contact on Friendica. (Possibly in form of a tick box on the confirm menu that is pre-ticked if "Automatically create contacts" is enabled)
*IF delete both is true THAN 1. Unfollow on Twitter, 2. Drop contact on Friendica
*ELSE Drop contact on Friendica only

This is my idea of an enhancement to make the unfollow process possible that considers Michael's useful function. Hope this makes sense.

**Comment by MrPetovan** [comment]
And again, there's a huge difference between dropping a contact and simply unfollowing one. Unfollowing is "I don't want to see their top-level posts in my network stream" while dropping a contact is "I want to completely remove all their posts destined to me from my node". Twitter has the former mechanism, while it doesn't have the latter outside of blocking. If "Automatically create contacts" is enabled we shouldn't even allow contact deletion, only contact unfollow which then should be mirrored on Twitter.

**Comment by AndyHee** [comment]
Yes, wouldn't this be a nice enhancement what you're saying?

**Comment by MrPetovan** [comment]
I agree it would, provided it's triggered on Twitter contact unfollow, not contact dropping which shouldn't be allowed when "Automatically create contacts" is enabled.

**Comment by AndyHee** [comment]
I think, I begin to understand what you're saying. It will in effect be two very different modes how this addon would  operate.
