### ISSUE TITLE
Buggy or slow federation?

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#4985]
### Expected behavior
My likes/comments should appear on people's instances when they follow me.

### Actual behavior
Some comments and likes are not appearing on people's instances who follow me: [see this post for details](https://f.haeder.net/display/adbba6c6215aedf0d32a14d377953796) and [this](https://f.haeder.net/display/adbba6c6185aed9b5bd35ba538104425).

### Steps to reproduce the problem

1. Run 2 instances
2. Have accounts on both of them
3. Follow each other, no encryption enabled
4. Post a message on one instance, comment/like/dislike on other

### Friendica version you encountered the problem
Latest `develop` code is installed.

### Friendica source (git, zip)
git

### PHP version
````
PHP 7.0.28-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
````
### SQL version
`mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by tobiasd** [comment]
I've also had the issue, that comments by other people took a long while to reach other contacts nodes. Maybe it was the worker fetching them.

**Comment by annando** [comment]
I do have two instances and do regular communication tests. I cannot reproduce any communication issue.

Are you running a clean "develop" or do you have some local changes?

**Comment by Quix0r** [comment]
Yes, as I continue to develop on it (cleanups).

**Comment by annando** [comment]
This complicates debugging your problem :-)

**Comment by Quix0r** [comment]
I'm currently developing on it and these changes (see my clone) are not that impacting (only cleanup, just check my code).

**Comment by annando** [comment]
No, the worker is working really fine. The "worker_fetch_limit" is the solution for a system where the write performance is extremely low. But it has got the side effect that a single blocking task can massively delay the execution of the other tasks. This is no bug.

**Comment by Quix0r** [comment]
So is 50 fetch limit okay? Fetching only 1 (default) per cycles (`worker_fetch_limit * worker_queue` ?) is a bit low and no wonder that federation is slow. Sure we need to take care of not DoS-ing other nodes. So there should be a per-IP (not hostname, see multiple virtual host setups, like my server) per time span limit implemented?

**Comment by annando** [comment]
1 is the best. This is only a problem with systems where a write process last very long. Concerning the speed: I just saw a system that had processed 1,500 jobs per minute - which is really fast. (With the value set to "1")

**Comment by tobiasd** [comment]
@Quix0r what is the status on this?

**Comment by Quix0r** [comment]
I have not seen this again, maybe slow worker as mentioned in conversation.
