### ISSUE TITLE
Reconnecting to a contact/forum

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#4999]
### Expected behavior
After delet a contact or forum from the contact list it should be possible to reconnect to it.

### Actual behavior
After deleting a contact it is not possible to reconnect, because the contact is only deleting on my side of the connection. Therefore it is not possible to reconnect and the info-bubble 

> Du hast Dich hier bereits vorgestellt.

appears.

### Steps to reproduce the problem
Delete a contact from the contact list and try to reconnect

### Friendica version you encountered the problem
2018.05-rc

### Friendica source (git, zip)
git

### PHP version
7

### SQL version
MariaDB 10.1

**Comment by nupplaphil** [comment]
It sounds like this one wouldn't/shouldn't get fixed for 2019.03, should it?
I was running into this issue too, so I think we should prioritize it for the next release - if possible.

**Comment by annando** [comment]
The issue is based on the behaviour of the DFRN protocol. We will solve it when we finally will connect between Friendica via ActivityPub instead of DFRN.

**Comment by MrPetovan** [comment]
Has this been solved by #7095?

**Comment by annando** [comment]
I hope so.

**Comment by MrPetovan** [comment]
Closing for now.
