### ISSUE TITLE
Support for APCu caching

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#5011]
I would like to request that Friendica adds support for APCu caching to it's configuration. It appears that at the moment it supports disk and memcached caching but not APCu.

**Comment by nupplaphil** [comment]
should be fixed with #7022

**Comment by AlfredSK** [comment]
Is there a configuration needed or is apcu used if it is available on the server?

**Comment by MrPetovan** [comment]
You need to set the `system.cache_driver` config key to `apcu`.

**Comment by nupplaphil** [comment]
> You need to set the `system.cache_driver` config key to `apcu`.

Same config setting is needed for using this cache as lock:
`system.lock_driver`
