### ISSUE TITLE
Theme 'Frio' doesn't work with automatic install

### ISSUE THREAD

**Issue by M-arcus** [friendica/friendica#5033]
### Expected behavior

Theme 'Frio' is fully loaded and usable after first automatic installation and first login.

### Actual behavior

After logging in, the theme is only partially loaded, no menu points, only basic layout and logout button

### Steps to reproduce the problem

1. Set htconfig.php settings theme = 'frio'
2. Add 'frio' to allowed themes setting
3. Execute installation
4. Register and login

### Friendica version you encountered the problem

Newest develop version
Commit: 7997df877d709f5c7ca211449ad941b1be216a2d

### Friendica source (git, zip)

Git

### PHP version

7.0

### SQL version

5.7

**Comment by MrPetovan** [comment]
Can you please try clearing your browser cache?

**Comment by M-arcus** [comment]
@MrPetovan Yes, I still get an incomplete theme:
![selection_059](https://user-images.githubusercontent.com/25648755/39956525-b2d1c37c-55e2-11e8-99b1-042d81eb0280.png)

However, if I execute the installation script with another template (example: 'vier') and then change to frio, everything works fine.

**Comment by MrPetovan** [comment]
I've seen this issue before, but I can't remember if/what was the solution.

**Comment by MrPetovan** [comment]
Never mind, found it: #4921

Maybe there is something there you can use?

**Comment by MrPetovan** [comment]
Perfect!

**Comment by M-arcus** [comment]
This was merged into the RC, but not into develop.

How do we continue here?

**Comment by tobiasd** [comment]
simply use RC until it is merged back into master and develop ;-)

**Comment by M-arcus** [comment]
@tobiasd So can this issue be closed? (not familiar with the workflow here)

**Comment by tobiasd** [comment]
Sure :-) if it is fixed. I did not check the state of the issue, sorry ;-)
