### ISSUE TITLE
SQL error on gserver-tag INSERT

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#5034]
I have this several times in my debug log:
````
2018-05-13T03:22:37Z@xxx.yyy [NORMAL]:dba.php:539:e  DB Error 1062: Duplicate entry '12345-foo' for key 'PRIMARY'
dba::insert, PortableContact::discoverRelay, PortableContact::checkServer, Queue::execute, Worker::execFunction, Worker::execute, Worker::processQueue
INSERT INTO `gserver-tag` (`gserver-id`, `tag`) VALUES ('12345', 'foo')
````
by `12345` and `foo` are only example values.

**Comment by annando** [comment]
Are you on the RC? If yes, then update your installation. This was handled by a PR some days ago.

**Comment by Alkarex** [comment]
Same problem here on /develop
I am not familiar with the work flow: when are the RC fixes merged into /develop ?

**Comment by tobiasd** [comment]
Once it is released and was merged into master and master is merged into develop. If the open issues are solved by then it was planned for in a week...

**Comment by Alkarex** [comment]
Any reason for not merging or cherry-picking those fixes immediately into /develop?
Otherwise people running /develop (like me) have to do that locally.
(Sorry for hijacking this thread)

**Comment by tobiasd** [comment]
Yes. Get those who run on develop to test the RC branch and try to get the developers concentrate on important fixes for the release and not working on nice new features so that the release can be bundled up.

**Comment by Quix0r** [comment]
So, this is a duplicate. Okay, thank you for explaining it.

**Comment by MrPetovan** [comment]
Duplicate of #4816
