### ISSUE TITLE
Comment relay issue to hubzilla

### ISSUE THREAD

**Issue by git-marijus** [friendica/friendica#5043]
When i receive a toplevel post from friendica i am only receiving comments from the post owner. No comments from other friendica profiles and no comments from diaspora.

**Comment by git-marijus** [comment]
Yes i have checked the logs. Not sure about where to find version info in friendica. It appears to go wrong with libranet.de and pirati.ca. Still works with kirgroup.com though...

**Comment by AlfredSK** [comment]
https://kirgroup.com/nodeinfo/1.0 is on master 3.6-1256
Libranet.de and Pirati.ca are on 2018.05-rc-1261

**Comment by annando** [comment]
So situation is that there is a starting post on (for example) pirati.ca. Someone else (from Diaspora or from Friendica?) answers, but on Hubzilla you only see the starting post and the comments from pirati.ca?

I have to check whether I still have a Hubzilla test account. Then I can check this by myself.

**Comment by annando** [comment]
@git-marijus Can you check if it works now?

**Comment by git-marijus** [comment]
Yes, it appears to be fixed again!
Thank you!
