### ISSUE TITLE
Mentions and Tags from Hubzilla

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5046]
### Expected behavior
Mentions should work and look like mentions. Tags should work and should be linked to a tag search.

### Actual behavior
Hubzilla has introduced some kind of new mentions (webmentions?). These mentions have curly braces around the webfinger ID like this `@{someone@somewhere.tld}`. These mentions don't work in Friendica. The actual ID is missing `@{}`.

In posts imported from Hubzilla the first tag added to the end of a post has always a `\` in front of the first tag. Further tags are looking okay. Also the tag isn't a link to a tag search.

Both issues occured in the following public posts...

### Steps to reproduce the problem
**Post in Friendica:**
https://libranet.de/display/7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe
**Original on Hubzilla:**
https://dacha.xmpp.moe/channel/marzanna/&f=&mid=7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe?f=&jsdisabled=0
### Friendica version you encountered the problem
2018.05-rc-1261

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 (MariaDB)

**Comment by annando** [comment]
I have the feeling that this is some Markdown problem. Similar happens with hashtag lists from Diaspora.

**Comment by AlfredSK** [comment]
Can this be fixed for the upcoming release?
The `{}-mentions` are really bad because you don't know who was mentioned.
The other issue with those `\` in front of tags ( `\#tag` ) isn't nice, but it's less bad.

**Comment by annando** [comment]
Do you have some example from the last days? We need to have the raw data - and that is in a table that isn't stored for very long.

You get the needed code this way: (I take the link from above as an example)

* Use the guid to fetch the uri: ```select uri from item where guid='7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe' limit 1;```
* You got an uri like "marzanna@dacha.xmpp.moe:7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe".
* With that value you now look into the content table: ```select source from conversation where `item-uri` = 'marzanna@dacha.xmpp.moe:7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe';```

The value of the source field should help to detect the problem.

**Comment by MrPetovan** [comment]
Single query:
```sql
SELECT `source`
FROM `conversation` c
JOIN `item` i ON i.`uri` = c.`item-uri`
WHERE `guid` = '7ac2b62938f441f7a991f5a650c64ff2a1ae2bdd707dd024dc557d48bfd2af41@dacha.xmpp.moe'
LIMIT 1
```

**Comment by AlfredSK** [comment]
Ok. I'll have a look if I find a recent example.

**Comment by MrPetovan** [comment]
No, it shows that the backslash is added and mentions are stripped by the Hubzilla delivery mechanism itself.

**Comment by AlfredSK** [comment]
Ok. I checked the post on Diaspora (despora.de). The mention is empty there as well but the tags are intact.
Maybe we should ask Mike or Mario about that issue.

**Comment by git-marijus** [comment]
This is how an outgoing message with a mention over diaspora protocol looks in my log:
```
<?xml version="1.0" encoding="UTF-8"?>
<status_message>
<author>mario@hub.somaton.com</author><guid>913c11741edfe82fa9e170a17c1d5fdfcb7105e8ebac2b764b74c1baec9b147d@hub.somaton.com</guid>
<created_at>2018-08-27T18:08:15Z</created_at>
<public>false</public>
<text>@{motesting@diasp.org} test123</text>
</status_message>
```
Not sure where the actual mention could get lost. This appears to be working in diaspora.

What doesn't work in diaspora is the new forum mentions. They just appear as text like that: `!{hubzilla@project.hubzilla.org}`.

**Comment by git-marijus** [comment]
Hold a minute. It seems to work for some contacts but not for others...

**Comment by git-marijus** [comment]
The issue with some @mentions being empty should be fixed now in hubzilla.

**Comment by annando** [comment]
@git-marijus I guess that the backslash problem is due to some MarkDown dialect incompatibility. Funnily we are using the same library at Friendica as well.

**Comment by AlfredSK** [comment]
@git-marijus Your work works. :-)

See here: 
https://libranet.de/display/f65208a48a1929a8994dfe3849d1cb66dbe999ecd9e21c807001c13c39c8d461@hub.libranet.de

(Test with mentions an tags)

Thank you! :tada:

**Comment by AlfredSK** [comment]
As this is no issue anymore and it has been tested with the current RC I'll close here...
