### ISSUE TITLE
SMTP authentication configuration in Friendica

### ISSUE THREAD

**Issue by M-arcus** [friendica/friendica#5047]
I am installing Friendica inside an environment that can't be modified and need to set up a smtp connection with authentification. 

I tried setting this in Friendica, but haven't found a place where I can set the smtp  host, port, username and password.

Is there a configuration for this?

**Comment by M-arcus** [comment]
@MrPetovan @tobiasd Would you be interested in a PR with the [PHPMailer class](https://github.com/PHPMailer/PHPMailer) instead of the `mail()` function?

**Comment by tobiasd** [comment]
If you can plug it in as an addon, then those who do not need it as they have a working PHP setup wont need to care, but those who miss functionality could activate the addon.

**Comment by 001101** [comment]
@M-arcus Any progress on this?

**Comment by M-arcus** [comment]
@001101 Sorry for replying this late :( 

Yes, I was able to make it work, though it turned out a little ugly. Are you still interested in the code?

**Comment by annando** [comment]
I think it could be interesting for some users to not have to rely upon the mail settings of the server.

**Comment by poVoq** [comment]
Might also be interesting for people facing issues with notification emails going into the spam folder. Especially for registration emails this is a real issue.

**Comment by kecalcze** [comment]
I am of those that are interested in :)

**Comment by M-arcus** [comment]
I will post the link to the SMTP addon asap, sorry for the delay

**Comment by poVoq** [comment]
This one?
https://github.com/M-arcus/friendica-addons/tree/develop/phpmailer

**Comment by M-arcus** [comment]
@poVoq This is an older version, i will push a newer one

**Comment by M-arcus** [comment]
I added a PR https://github.com/friendica/friendica-addons/pull/834

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/834

**Comment by poVoq** [comment]
@M-arcus 
Sorry, but how does the configuration work now if the above is outdated. I can't seem to find the exact syntax for the config file explained anywhere.
Maybe a good idea to add this to the addon's description until that is implemented in the admin gui?

**Comment by MrPetovan** [comment]
Please check the Config help page accessible from every Friendica instance: `/help/Config`.

For example, mine is https://friendica.mrpetovan.com/help/Config

**Comment by poVoq** [comment]
Is it possible that this addon needs something from the dev branch and does not work on 2019.03?

I am getting a fatal error (config hook not found) when it tries to send a registration email.

**Comment by M-arcus** [comment]
@poVoq Can you please post the error message?

**Comment by M-arcus** [comment]
Are you using secure smtp?

**Comment by poVoq** [comment]
Yes trying to :)

Error:
`Fatal error: Uncaught Error: Class 'Config' not found in /var/www/vhosts/myhosting/friendica/addon/phpmailer/phpmailer.php:45 Stack trace: #0 /var/www/vhosts/myhosting/friendica/src/Core/Hook.php(201): phpmailer_emailer_send_prepare(Object(Friendica\App), Array) #1 /var/www/vhosts/myhosting/friendica/src/Core/Hook.php(177): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'emailer_send_pr...', Array, Array) #2 /var/www/vhosts/myhosting/friendica/src/Util/Emailer.php(37): Friendica\Core\Hook::callAll('emailer_send_pr...', Array) #3 /var/www/vhosts/myhosting/friendica/include/enotify.php(692): Friendica\Util\Emailer::send(Array) #4 /var/www/vhosts/myhosting/friendica/src/Module/Register.php(281): notification(Array) #5 [internal function]: Friendica\Module\Register::post() #6 /var/www/vhosts/myhosting/friendica/src/App.php(1356): call_user_func(A in /var/www/vhosts/myhosting/friendica/addon/phpmailer/phpmailer.php on line 45`

Config:
```
return [
	'phpmailer' => [
		'smtp' => true,
		'smtp_server' => 'smtp.example.com',
		'smtp_port' => 25,
		'smtp_port_s' => 465,
		'smtp_secure' => 'ssl',
		'smtp_username' => 'noreply@example.com',
		'smtp_password' => 'password123',
		'smtp_from' => 'noreply@example.com',
	],
];
```

**Comment by M-arcus** [comment]
@poVoq I opened a PR

**Comment by poVoq** [comment]
@M-arcus works now with the stable 2019.03 release :+1:

**Comment by poVoq** [comment]
@M-arcus Actually, I noticed that it does not seem to disable the old email system though and now I get two emails? Any idea why this might be the case?
