### ISSUE TITLE
Official Friendica Docker-Images

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5050]
Hi,

I'd like to create a set of official Docker-Images for different usage:
- apache (standalone with local DB - official/stable)
- fpm-apache (fpm image for scalability)
- fpm-alpine (Alpine fpm image for scalability)

for 
- develop
- latest stable (currently 3.6)

Therefore I started at
https://github.com/nupplaphil/friendica-docker
creating some images.

I'm currently using 
https://github.com/nupplaphil/friendica-docker/tree/master/.examples/docker-compose
for my friendica instance :-).

Here my questions:
- Am I allowed to create a "official" Docker repository for friendica? (like https://github.com/friendica/docker/)
- I'd like to participate at https://github.com/docker-library/official-images to provide "official" Docker Images

What do you think?

**Comment by M-arcus** [comment]
Little bit offtopic:
I have created a docker image at https://github.com/M-arcus/friendica-docker-image
(only usable as [cloudron app](https://cloudron.io/))

**Comment by nupplaphil** [comment]
@M-arcus Nice work :-)

I'd like to create a more generic image (amd64, i386, ...) so everybody can deploy Friendica in a way he'd like. It's one of my thoughts about how to make Friendica more public.

**Comment by MrPetovan** [comment]
I'm all for it, although I don't have the power to create such a repository.

**Comment by tobiasd** [comment]
Have fun! friendica/docker

**Comment by MrPetovan** [comment]
That was quick!
