### ISSUE TITLE
Missing "ignore notification" option in public posts

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5062]
### Expected behavior
When commenting on a public post from people you dont follow e.g. you get over the hashtag relay servers, you dont have the option to ignore further notifications when people continue commenting on this post.

### Actual behavior
Notifications to eternity ;)

### Steps to reproduce the problem
Comment on posts from people you don't follow.

### Friendica version
_Friendica 2018.05-rc / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1_

**Comment by hoergen** [comment]
Wow, saw one yesterday ..... *start git pulling like hell*  ;)
AND I'm convinced @annando could do that one-handed even if the pigs are squirrels !  😇

**Comment by annando** [comment]
Does this count?
![](https://thumbs.gfycat.com/TameConcreteDrever-size_restricted.gif)

**Comment by hoergen** [comment]
The eagle has already landed?

**Comment by annando** [comment]
Not yet.

**Comment by MrPetovan** [comment]
Subset of #5158
