### ISSUE TITLE
pump.io loop in posting activities

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5063]
### Expected behavior

I've activated the pump.io bridge again to listen to my old identi.ca account.

For this I've activated the "Import of the remote timeline" and "Activate pump.io addon" all other options were disabled.

I was expecting to send out 1 comment / like when answering to an activity posted at identi.ca.

### Actual behavior

I flooded the timeline. During 13hour over night me not at the computer the comment was transferred  something like 150time (I stopped counting at 70 there tha scrollbar of the browser was at 50%).

Same behavior was with the like on a different posting.

### Friendica version you encountered the problem

2018.05rc

**Comment by annando** [comment]
I experienced this behaviour as well.

**Comment by annando** [comment]
Should be fixed now. Please check.
