### ISSUE TITLE
delete database no user

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#5074]
![screenshot_2018-05-17-12-06-37](https://user-images.githubusercontent.com/750525/40186833-6cbdbc40-59cc-11e8-91c3-e2cc2e010a08.png)

Admin valhalla.mamalibre.com.ar

**Comment by MrPetovan** [comment]
1st suggestion: don't delete your database. Remote server hold your account's public key, and if you recreate an account with the same username on the same domain, you will generate a different public-private key pair that remote servers will not recognize.

2nd suggestion: you have to contact the admin of the server the forum is on and ask him to delete your outdated contact on their server.

**Comment by tobiasd** [comment]
Sólo para aclarar. Estás hablando del foro oficial de soporte (`@helpers@forum.friendi.ca`) ¿verdad?

Y trató de volver a conectarse después de tener que reiniciar, haga una copia de seguridad de su base de datos. Pero no se puede, ya que la conexión ya existe.

Si es así, el administrador del foro @alfredsk tiene que quitarte de la lista de contactos.

**Comment by AlfredSK** [comment]
¿Qué? :-)

**Comment by AlfredSK** [comment]
Entiendo lo que dices. :-) Deeple.com es muy bueno.

Question is, who is "I"? Are you Fabián Bonetti? And you want me to delete **your** contact from the helpers@forum.friendi.ca forum? Right?
