### ISSUE TITLE
Friendica uses sometimes the wrong theme for not-logged in users (2018.05-rc)

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#5092]
### Actual behavior
When visiting the some random profile pages on foreign instances, friendica doesn't sometimes show the correct theme of this user.
An initial research has shown that `$this->profile_uid` in `private function computeCurrentTheme()` is always `NULL` (https://github.com/friendica/friendica/blob/2018.05-rc/src/App.php#L1124).

### Steps to reproduce the problem
Close your browser and open the browser again in private browser mode - don't log in to your account - just insert https://libranet.de/profile/fau_dresden

https://libranet.de/profile/fau_dresden should have the dark vier theme but, it is displayed with the frio theme (love-music schema).

You can also find some discussion under https://friendica.kommune4.de/display/4029d2ca725aeecbc1833aa100845378

### Friendica version you encountered the problem
2018.05-rc

**Comment by MrPetovan** [comment]
This is a problem I've been having on Friendica mobile as well, even as I was logged in. First page shows node default theme, reloading shows my user-defined theme.

So it seems to be a session/cache/cookie issue.

**Comment by MrPetovan** [comment]
Problem is, it never happens on my node on desktop...

**Comment by rabuzarus** [comment]
I have an theory.
I guess there is a place in the code where `$a->getCurrentTheme()` is called when `$a->profile_uid` isn't yet available. In this case `$a->current_theme` will be set to the systems default theme. But even if we have the `$a->profile_uid` later `function computeCurrentTheme()` will not be called because we already have a theme name in `$a->current_theme` (https://github.com/friendica/friendica/blob/2018.05-rc/src/App.php#L1098).
When I call a profile page `$a->getCurrentTheme()` is called over 100x but only the first call doesn't have a `$a->profile_uid`. But this first call is the one that defines the theme.
This bug was introduced with https://github.com/friendica/friendica/pull/4951/

@MrPetovan can you please have a look

**Comment by MrPetovan** [comment]
No, the bug is older, I merely changed a global function into a class method.

Can you pinpoint where `getCurrentTheme` is called without profile_uid?

**Comment by rabuzarus** [comment]
> No, the bug is older, I merely changed a global function into a class method.
And you introduced the following condition: https://github.com/friendica/friendica/blob/2018.05-rc/src/App.php#L1098 
I guess before https://github.com/friendica/friendica/pull/4951 it didn't matter, that `$a->profile_uid` wasn't available for the first call of `current_theme()` because all the other (100+) calls of `current_theme()` return the correct theme. With https://github.com/friendica/friendica/pull/4951 `computeCurrentTheme()` is called only once.

> Can you pinpoint where getCurrentTheme is called without profile_uid?

Is there an easy way to find that out?

**Comment by MrPetovan** [comment]
```php
if (empty($this->profile_uid)) {
    (d)logger(...);
}
```

**Comment by rabuzarus** [comment]
it is call from the index.php
https://github.com/friendica/friendica/blob/develop/index.php#L325

**Comment by MrPetovan** [comment]
I tried removing the caching altogether but it still fails to show my custom theme on first load on my phone. It must be something else.

**Comment by AlfredSK** [comment]
I just tried it again with different profiles on my node and couldn't reproduce it anymore.

**Comment by rabuzarus** [comment]
I have to reopen this issue because since https://github.com/friendica/friendica/commit/979230da27c1159125ab0a0ab5f6b81e7d7a6515#diff-58980ac23a3a9a0b92abd9805eed1e78 did reverted https://github.com/friendica/friendica/pull/5123 the problem appears again

**Comment by rabuzarus** [comment]
Yes. It is exactly the same. I test the issue with https://libranet.de/profile/fau_dresden . (have a look at the issue description. It happens the same way). After loading the page a second time the the correct theme is displayed

**Comment by MrPetovan** [comment]
This time it’s caused by #6465 that was reverting part of #6340.
