### ISSUE TITLE
frio theme: Fix alignment for removing / adding a contact to a group

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#5095]
Follow up issue to #4965, which fixed the naming of the tooltip for that action.

Alignment of tooltip seems to be CSS + theme dependent. Closing #4965 and opening this to keep track of the remaining alignment issue. Tooltip should be next to "x" and "+" icon.

Screenshots from frio theme:

![39467526-d370651e-4d2e-11e8-8d30-e8ce66ed44b1](https://user-images.githubusercontent.com/5708172/40278995-87029a00-5c3b-11e8-9a15-5d0595a8d7ce.jpg)
![39467525-d3584e8e-4d2e-11e8-83d9-85fa81b25fea](https://user-images.githubusercontent.com/5708172/40278996-871a3372-5c3b-11e8-9728-8507167f3dc6.jpg)

**Comment by FrancoisGeyser** [comment]
Hi,  can I have a look at this?

**Comment by MrPetovan** [comment]
Yes, let us know what we can help you with!
