### ISSUE TITLE
Bookmark BBCode not interpreted in Twitter messages

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5113]
### Expected behavior

Shared tweets are displayed in imported retweet/cross-posted retweets.

### Actual behavior

`[bookmark]` BBCode tags are display in raw text: https://friendica.mrpetovan.com/display/735a2029565b04d6e246f11062708057

### Steps to reproduce the problem

1. Enable Twitter addon with post mirroring
2. Post a retweet on Twitter
3. Wait for Friendica mirroring

Or

1. Enable Twitter addon with timeline import
2. Twitter contact retweets/quote tweet
3. Wait for Friendica import

### Friendica version you encountered the problem

`2018.05-rc` although it's been reported on `develop` as well. See: https://forum.friendi.ca/display/735a2029675b030e47b1d36293207950

### Friendica source (git, zip)

git

### PHP version

7.0

### SQL version

[irrelevant]

**Comment by MrPetovan** [comment]
This behavior stopped 21 hours ago.

**Comment by annando** [comment]
That's weird.
