### ISSUE TITLE
Receiving "Site public key not available in contact record for URL" upon adding myself on own friendica instance

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#5114]
### Expected behavior

I can add myself with chris@friendica.cwiwie.org

### Actual behavior

I receive the following error upon adding myself:

Remote site reported: Site public key not available in contact record for URL https://friendica.cwiwie.org/profile/chris.

### Steps to reproduce the problem

1. Contacts
2. Add new contact
3. Enter: chris@friendica.cwiwie.org

### Friendica version you encountered the problem

3.6

### Friendica source (git, zip)

git

### PHP version

PHP 7.2.5-0ubuntu0.18.04.1

### SQL version

mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64)

**Comment by annando** [comment]
AFAIK we disallowed adding yourself as a contact in the upcoming version.

**Comment by tobiasd** [comment]
If you want to write a post only for yourself, you can use the "private notes" functionality.

Or you create a group for your all of your contacts and when you then write a regular posting, you can select in the ACL to not share it with that group.

**Comment by wiwie** [comment]
just tried it out, the personal notes functionality doesn't call the MathJax addon renderer either.

**Comment by MrPetovan** [comment]
Interesting, thanks for the report.

**Comment by wiwie** [comment]
the workaround with the group of all contacts and then excluding it from the post works though.

**Comment by tobiasd** [comment]
Thanks for reporting the bug with the MathJax addon!

**Comment by MrPetovan** [comment]
Closing this since the real issue has been opened at #5118
