### ISSUE TITLE
Remove dns_get_record() from include/dba

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5116]
See https://github.com/friendica/docker/issues/6

We don't need this knid of antics anymore when trying to connect to the database. If the configuration is correct, we don't need it (and it can still fail), and if the the configuration is wrong, there wouldn't be any database connection anyway.

**Comment by nupplaphil** [comment]
So do we add this workaround until you fix the Bug in Friendica? Otherwise you cannot install Friendica in Docker environments (except per autoinstall)
