### ISSUE TITLE
Delete post tags

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#5121]
Is there a way of editing the tags of a post or deleting tags?

Is this technically possible?

If yes: This would be a really helpful feature when one misspells the tag.

**Comment by MrPetovan** [comment]
Hi @wiwie, you can’t edit your post to fix the spelling. I know the previous tag will still be associated, and I don’t know if the new one will be associated, but at least the display will be correct.

**Comment by wiwie** [comment]
I can't find any functionality related to tags when editing a post?! I only see a "add tag" icon under the post on my wall. This is with the frio and view themes...

and what do you mean by "at least the display will be correct"?

**Comment by MrPetovan** [comment]
Let's start over:
- Is it your own post?
- Or did you add a tag on someone else's post?

If it's your own post, then you can edit the content where the tag has presumably been added. In this case the post text will be changed, but the offending tag will stay, and I'm not sure the corrected tag will be added.

If you added a tag on someone else's post, you can remove the post saying "X added the tag #YYYY" but I don't think it removes the tag from the post either. You can add the corrected tag to the post the same way, though.

**Comment by wiwie** [comment]
it was my own post. but if I click on "edit post" I don't see any of the tags nor any functionality to edit / remove / add them. Am I supposed to?

![image](https://user-images.githubusercontent.com/2605261/40543706-e0504740-6025-11e8-8e9e-9cf9c5b44f72.png)

**Comment by MrPetovan** [comment]
Only if you added tags in the post body text. Otherwise it would be the same case as with someone else's post.

**Comment by wiwie** [comment]
aaah, ok. will try that now. thanks.

**Comment by miqrogroove** [comment]
I think this should be reopened from an admin perspective.  What if someone uses a vulgar tag and I need to edit/delete the tag?

**Comment by MrPetovan** [comment]
What is the problem with a vulgar tag?

**Comment by miqrogroove** [comment]
Maybe I didn’t understand, but it sounded like there was no way to remove a tag from someone else’s post.  Even an admin has no way to moderate this?

**Comment by MrPetovan** [comment]
Users can add tags to other people's posts. It will be displayed as a comment "X added the tag #tag to this posts." The comment can be deleted by an admin, but I'm pretty sure the tag will stay attached to the post even if it isn't displayed anymore.
