### ISSUE TITLE
Cannot accept friend request due to 404 error

### ISSUE THREAD

**Issue by AgnesElisa** [friendica/friendica#5125]
### Expected behavior
Get friend request, accept as friend, get friend added to contacts and see each other's posts

### Actual behavior
I got a friend request from another friendica account, not on the same node. When I accepted as a friend it said there was a temporary issue and I should try again (sadly the screenshot I made was too late and I didn't realise this in time, so I don't have the actual text, sorry). The screenshot does show a 404 error, see: https://libranet.de/display/735a2029205b08325c3c194984126431
I tried several times and allowed some time in between. I tried it both from my phone and from my pc.
I tried to connect with the connection button on the profile, which gave an error saying we were already friends, but he did not show up in my contacts and his profile did not look like we were friends. I then deleted the request and tried to connect again, but again I got an error saying it looks like we are already friends, while we are not.

### Steps to reproduce the problem
I'm not sure. This is the first time I encountered this problem. 

### Friendica version you encountered the problem
2018.05-rc-1265

**Comment by AlfredSK** [comment]
At the moment it's the RC branch, actually. :-)

**Comment by AgnesElisa** [comment]
Haha I had just updated the info (probably between when you opened the thread and when you sent your comment)

**Comment by MrPetovan** [comment]
Like @tobiasd said, it could be an nginx configuration issue, summoning @wiwie as I believe you were trying to connect with them.

**Comment by AlfredSK** [comment]
Hmm. Tried it with my testuser and it seems to work...

Contact: Cxxxxx Wxxxxx
Status:
    Network type: Friendica
    Last update: Never
    **Awaiting connection acknowledge**

**Comment by AlfredSK** [comment]
Hmm2. But I also got a timeout in the friendica logfile...

````
2018-05-25T16:57:28Z@chsvga1l4mgqu0f12msicdnjc3 [NORMAL]:Network.php:221:curl   error fetching https://friendica.cwiwie.org/dfrn_request/chris?confirm_key=d9a9xxxxxx...xxxxxx7422: Operation timed out after 25000 milliseconds with 0 bytes received
````
And no 404 in apache access log.

**Comment by wiwie** [comment]
I adapted my nginx configuration a bit, towards the mods/sample-nginx.config which I had overlooked previously:

```
server {

  server_name friendica.cwiwie.org;
  root XXX;

  log_not_found off;                          # Turn on if you want to track "not found" errors
  access_log XXX;
  error_log XXX;
  #rewrite_log on;                            # Uncomment if you want to debug your rewrites (then change 'crit' above to 'notice')

  # block stuff early
  # Do not log favicon.ico and robots.txt stuff
  location ~* /(favicon\.ico|robots\.txt) {
    allow all;
    access_log off;
    log_not_found off;
  }

  # Return error 444 for these files
  location ~* ^.+\.(bzr|git|log)$ {
    access_log off;
    log_not_found off;
    return 444;
  }

  # Deny public access to ~ (bak) files
  location ~* ~$ {
    access_log off;
    log_not_found off;
    return 444;
  }

  include mime.types;

  #############
  # Friendica #
  #############
  location / {
    if (!-e $request_filename) {
      rewrite ^(.*)$ /index.php?q=$1;
    }
  }


   # make sure webfinger and other well known services aren't blocked
   # by denying dot files and rewrite request to the front controller
   location ^~ /.well-known/ {
     allow all;
    if (!-e $request_filename) {
      rewrite ^(.*)$ /index.php?q=$1;
    }
   }

  #######################
  # Security: Friendica #
  #######################
  # block public access to .htaccess and .htconfig.php
  location ~* /\.ht {
    access_log off;
    log_not_found off;
    return 444;
  }

  # block public access to .tpl files located in /view/ folder
  location ~* /view/(.*)\.tpl$ {
    access_log off;
    log_not_found off;
    return 444;
  }

  # block public access to /util/ folder
  location ^~ /util/ {
    access_log off;
    log_not_found off;
    return 444;
  }

  ############################
  # redirect 50x error pages #
  ############################
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
    internal;
  }

  ##############
  # enable PHP #
  ##############
  location ~ \.php$ {
    try_files $uri =404;

    fastcgi_split_path_info ^(.+\.php)(.*)$;

    fastcgi_pass unix:XXX.sock;

    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

fastcgi_param HTTPS on;

    client_max_body_size 512M;
    fastcgi_buffers 64 4K;

    include /etc/nginx/fastcgi_params;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate XXX; # managed by Certbot
    ssl_certificate_key XXX; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = friendica.cwiwie.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;

  server_name friendica.cwiwie.org;
    return 404; # managed by Certbot


}
```

Can anyone help me testing whether it's working now?

**Comment by MrPetovan** [comment]
I just tried to connect with you, the following URL
```
https://friendica.cwiwie.org/?dfrn_url=68747470733a2f2f667269656e646963612e6377697769652e6f72672f70726f66696c652f6368726973&dfrn_version=2.23&confirm_key=2890ad7c2eb262eae306cd14d2dd660c014e49d18b02cec53d08f1fe562eb9991527534032&aes_allow=1
```
yielded `403 Forbidden` error.

**Comment by wiwie** [comment]
ok. now?

**Comment by tobiasd** [comment]
Can we close this issue? [This](https://libranet.de/display/0b6b25a8155b0c9a4f098d0115632291) looks like it is working now.

**Comment by wiwie** [comment]
Just for completeness, I made it work by changing the nginx config pretty much to the provide sample config. Sorry for the inconvenience...
