### ISSUE TITLE
Prevent automatic table structure alteration

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5137]
I'm trying to run a daily backup, but I'm getting the following errors over the last 6 days:
```
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `workerqueue` at row: 0
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `gserver-tag` at row: 0
mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `photo` at row: 19576
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `workerqueue` at row: 0
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `workerqueue` at row: 0
mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `workerqueue` at row: 0
```
No table definition shouldn't change after the one-time update when the current DB build number differs from the target DB build number.

I'd like to add a `.htconfig.php` setting to prevent automatic DB structure check and force to update the DB structure manually.

**Comment by AlfredSK** [comment]
Same here. Approximately two out of three mysqldumps are failing because of that issue (I run a scripted backup every three days). There is also a discussion in the helpers forum about it.

**Comment by MrPetovan** [comment]
I'll tell you tomorrow if the automatic backup succeeded.

**Comment by annando** [comment]
Here it worked.

**Comment by AlfredSK** [comment]
Here too. Backup successful.
Tomorrow cron will start a planned backup. I'll report what happens.

**Comment by annando** [comment]
It could be disabled before the database backup and could be enabled afterwards.

**Comment by MrPetovan** [comment]
My automatic backup went through this morning, the workerqueue optimization query was throwing it off.

**Comment by AlfredSK** [comment]
Yep. Backup cron job was successful. Thank you!
