### ISSUE TITLE
Twitter addon - change/remove "@name" that no twitter account is mentioned

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5141]
### Expected behavior
When posts are forwarded to twitter, make sure that fediverse names like @namethingy are not translated 1:1 . It occurs very often some strangers (mostly the wrong people) with that name on twitter get mentions. Maybe just remove the "@ shortname" and remove the brackets from the fediverse address 

### Actual behavior
For example these is wrong on twitter because they are mentioning eventually the wrong people

"RT @besser (besser@horche.demkontinuum.de)"
https://twitter.com/hoergen/status/1000844845265686528

"RT @Joe Slam (produnis@friendica.produnis.de)"
https://twitter.com/hoergen/status/1000786260481462272

"RT @Karneol (Karneol@social.tchncs.de)"
https://twitter.com/hoergen/status/999913150873980928

### Steps to reproduce the problem
Share posts to twitter

### Friendica version you encountered the problem
Friendica 2018.05-rc / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1

**Comment by MrPetovan** [comment]
> For example these is wrong on twitter because they are mentioning eventually the wrong people

Interestingly they are wrong on GitHub as well.

**Comment by hoergen** [comment]
Damn .. searched not good enough. So we use the #3218 issue and close this?

**Comment by MrPetovan** [comment]
Yes please, it's a duplicate.

**Comment by hoergen** [comment]
Duplicate
