### ISSUE TITLE
Typo 'bandwith' should be 'bandwidth'

### ISSUE THREAD

**Issue by abanink** [friendica/friendica#5147]
### Expected behavior
Both in display strings and code, correct spelling of 'bandwidth'

### Actual behavior
In strings and variable names, you will find both 'bandwith' and 'bandwidth'

### Steps to reproduce the problem
I don't know if/which issues it generates, but it is certainly there for `Bandwith Saver Mode` (sic) setting in Display Settings

### Friendica version you encountered the problem
2018-05-dev, 2018.05-rc

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (i686) using readline 5.2

**Comment by MrPetovan** [comment]
If you want to tackle this, please start from the `2018.05-rc` branch and request pull against the same branch.

**Comment by abanink** [comment]
Illustration of the bug:

> $ find . -name "*.php" | xargs grep PConfig | grep bandwi
> ./mod/update_profile.php:	if (PConfig::get(local_user(), "system", "bandwith_saver")) {
> ./mod/update_community.php:	if (PConfig::get(local_user(), "system", "bandwith_saver")) {
> ./mod/update_display.php:	if (PConfig::get(local_user(), "system", "bandwith_saver")) {
> ./mod/update_notes.php:	if (PConfig::get(local_user(), "system", "bandwith_saver")) {
> ./mod/update_network.php:	if (PConfig::get(local_user(), "system", "bandwith_saver")) {
> ./mod/settings.php:		PConfig::set(local_user(), 'system', 'bandwidth_saver'         ,$bandwidth_saver);
> ./mod/settings.php:		$bandwidth_saver = PConfig::get(local_user(), 'system', 'bandwidth_saver', 0);

=> PConfig::set is done on `bandwi`**d**`th_saver` key
=> PConfig::get is done on `bandwith_saver` key

**Comment by tobiasd** [comment]
If you are going to work on this, please keep in mind that these are config settings and you cannot simple rename them to correct the typo but you have to provide a automatic way for existing settings to be saved in the new variables/DB fields with the correct spelling.

**Comment by abanink** [comment]
@tobiasd 
that's a good point.
However, I checked the DB and find this:
```
MariaDB [friendica_dev]> select * from pconfig where k like '%bandwi%';
+----+-----+--------+-----------------+------+
| id | uid | cat    | k               | v    |
+----+-----+--------+-----------------+------+
| 12 |   1 | system | bandwidth_saver | 1    |
| 48 |   2 | system | bandwidth_saver | 0    |
| 75 |   3 | system | bandwidth_saver | 0    |
+----+-----+--------+-----------------+------+
3 rows in set (0.00 sec)
```

So am I correct to say that the DB actually already has the correct spelling.
I reviewed the changes in my PR and cannot find an occurrence where it affects a change in configuration key/DB, except for 'get' - so it does not affect the user's settings.

**Comment by tobiasd** [comment]
> So am I correct to say that the DB actually already has the correct
> spelling.

Maybe on your node. What about all the other out there?

**Comment by annando** [comment]
I guess the best way is to increase the database version number and to use the update process for this.

**Comment by MrPetovan** [comment]
Or use:
```php
PConfig::get(local_user(), 'system', 'bandwidth_saver', PConfig::get(local_user(), 'system', 'bandwith_saver'))
```

**Comment by annando** [comment]
But this only has to be made only once. And having such a call in the code for years doesn't look right.

**Comment by MrPetovan** [comment]
We have been doing it at least once!

The last solution is to avoid renaming the config key name and just fix the displayed strings.

**Comment by annando** [comment]
Just because we did bad things once, doesn't mean we have to repeat this 😀

**Comment by MrPetovan** [comment]
It's true, it was just a reminder we have to clean it in the upcoming release probably.

**Comment by annando** [comment]
We cannot simply remove something like this in a next release, since we never know from which version the people are updating.

**Comment by abanink** [comment]
Concerning the 'Translation' part of this issue, I think now that changing it in the code is optional - this could be done in the translations so that the end user does not see this typo in the settings page.

Concerning the 'Bug' part of this issue, I fail to understand why the fix could break something;  given that the `bandwidth_saver` feature was added in mod/settings.php by #2822 (commit d9a5554543e5230828b3733f55e25304138e4601) and the 'set' always had the correct spelling.
With my very limited knowledge, I would say that the error is only in the mod/update_xxx.php files when performing the 'get' for the bandwidth_saver key, and calling a 'get' for 'bandwith_saver' key (with the typo) could never result in the setting that the user configured since the feature was introduced (i.e. if I'm right, the feature was never active even if the user enabled it in the settings!).

Please bear with me if the opposite is true; explaining why would give me an insight in the way it works.

**Comment by MrPetovan** [comment]
I trust you did your homework. I was merely providing a way for you not to do it.

**Comment by MrPetovan** [comment]
> Concerning the 'Translation' part of this issue, I think now that changing it in the code is optional - this could be done in the translations so that the end user does not see this typo in the settings page.

The reason why I'd rather have the fix in the translation base string as well is that it doesn't look "good". It may be more work to update the translations afterwards, but at least the code looks slightly less amateurish. I don't know if it's that important but in Transifex you can reuse a former translation, which speeds up the process with a different base string.
