### ISSUE TITLE
Can't ignore/delete public post I'm receiving notifications about

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5158]
### Expected behavior

I should be able to ignore a thread I'm receiving notifications about.

### Actual behavior

I can't ignore the thread nor delete it. The dropdown menu only shows "Link to the source".

URL: https://friendica.mrpetovan.com/display/0989743048390136bfa60242ac110007

![link-to-source](https://user-images.githubusercontent.com/925415/40869810-70ff5834-65ef-11e8-9683-83f904dfad98.png)

Database row:

id | guid | uri | uid | contact-id | gcontact-id | type | wall | gravity | parent | parent-uri | extid | thr-parent | created | edited | commented | received | changed | owner-id | owner-name | owner-link | owner-avatar | author-id | author-name | author-link | author-avatar | title | body | app | verb | object-type | object | target-type | target | postopts | plink | resource-id | event-id | tag | attach | inform | file | location | coord | allow_cid | allow_gid | deny_cid | deny_gid | private | pubmail | moderated | visible | spam | starred | bookmark | unseen | deleted | origin | forum_mode | last-child | mention | network | rendered-hash | rendered-html | global | content-warning
-- | ---- | --- | --- | ---------- | ----------- | ---- | ---- | ------- | ------ | ---------- | ----- | ---------- | ------- | ------ | --------- | -------- | ------- | -------- | ---------- | ---------- | ------------ | --------- | ----------- | ----------- | ------------- | ----- | ---- | --- | ---- | ----------- | ------ | ----------- | ------ | -------- | ----- | ----------- | -------- | --- | ------ | ------ | ---- | -------- | ----- | --------- | --------- | -------- | -------- | ------- | ------- | --------- | ------- | ---- | ------- | -------- | ------ | ------- | ------ | ---------- | ---------- | ------- | ------- | ------------- | ------------- | ------ | ---------------
944090 | 4f5a8e1044a00136e9a7543d7eeced27 | anonymiss@despora.de:4f5a8e1044a00136e9a7543d7eeced27 | 0 | 2749 | 0 | remote | 0 | 0 | 944090 | anonymiss@despora.de:4f5a8e1044a00136e9a7543d7eeced27 | | anonymiss@despora.de:4f5a8e1044a00136e9a7543d7eeced27 | 2018-05-28 12:26:45 | 2018-05-28 12:26:45 | 2018-06-02 02:17:37 | 2018-06-01 19:23:02 | 2018-06-02 02:17:37 | 2749 | anonymiss | https://despora.de/u/anonymiss | https://friendica.mrpetovan.com/photo/e12ec08129f1bbb40cba7778dddb1025-5.png?ts=1527044471 | 2749 | anonymiss | https://despora.de/u/anonymiss | https://friendica.mrpetovan.com/photo/e12ec08129f1bbb40cba7778dddb1025-5.png?ts=1527044471 | | [img]https://despora.de/uploads/images/4ab3c772afc52d88eb48.png[/img]#[url=https://friendica.mrpetovan.com/search?tag=economy]economy[/url] #[url=https://friendica.mrpetovan.com/search?tag=justice]justice[/url] #[url=https://friendica.mrpetovan.com/search?tag=capitalism]capitalism[/url] #[url=https://friendica.mrpetovan.com/search?tag=humanity]humanity[/url] | mobile | http://activitystrea.ms/schema/1.0/post | http://activitystrea.ms/schema/1.0/image | | | | lang=italian;0.18708333333333:romanian;0.18125:tagalog;0.17833333333333 | https://despora.de/posts/4f5a8e1044a00136e9a7543d7eeced27 | | 0 | #[url=https://friendica.mrpetovan.com/search?tag=capitalism]capitalism[/url],#[url=https://friendica.mrpetovan.com/search?tag=economy]economy[/url],#[url=https://friendica.mrpetovan.com/search?tag=humanity]humanity[/url],#[url=https://friendica.mrpetovan.com/search?tag=justice]justice[/url] | | | | | | | | | | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | dspr | 1d724c971e1f3ad588d0c2c3a30f4198 | <img src="https://friendica.mrpetovan.com/proxy/d0/aHR0cHM6Ly9kZXNwb3JhLmRlL3VwbG9hZHMvaW1hZ2VzLzRhYjNjNzcyYWZjNTJkODhlYjQ4LnBuZw==.png" alt="Image/photo"><br>#<a href="https://friendica.mrpetovan.com/search?tag=economy" class="tag" title="economy">economy</a> #<a href="https://friendica.mrpetovan.com/search?tag=justice" class="tag" title="justice">justice</a> #<a href="https://friendica.mrpetovan.com/search?tag=capitalism" class="tag" title="capitalism">capitalism</a> #<a href="https://friendica.mrpetovan.com/search?tag=humanity" class="tag" title="humanity">humanity</a> | 1 | 

### Steps to reproduce the problem

1. Like a status
2. Get a notification
3. ???
4. Open the dropdown menu

### Friendica version you encountered the problem

Friendica 2018.05

### Friendica source (git, zip)

git (master branch)

### PHP version

PHP 7.2.5

### SQL version

MariaDB 10.1.26

**Comment by tobiasd** [comment]
part of #4960 I guess.

**Comment by annando** [comment]
The table structure currently doesn't allow this. This will change in this release.

**Comment by MrPetovan** [comment]
> part of #4960 I guess.

It's remotely related. #4960 is about ignoring contacts, this is about ignoring threads.

> This will change in this release.

Which one? 2018.08?

**Comment by annando** [comment]
Most changes that I'm currently doing are preparations for this.

**Comment by MrPetovan** [comment]
So next release, thanks!

**Comment by annando** [comment]
Of course it depends upon my time and the obstacles on the way.

**Comment by annando** [comment]
After many item changes had been done, I'm currently thinking of dropping the "user-item" table, since in the next release my work will focus on making the item table very slim. The "user-item" table would be some possible (but not really ideal) place for setting this "ignore" field.

We now would had two options:
1. Creating some workaround for only one version
2. Postponing this to the next version

**Comment by MrPetovan** [comment]
I don't remember being possible to interact as much with public (uid=0) posts, so this is in a way backward breaking change. We need a way to ignore or hide public posts and `user-item` seems the only logical place for it.

What would the workaround look like? I'd rather not have this issue for 3 additional whole months.

**Comment by annando** [comment]
I created the workaround. It works fine. We do need some "updateForUser" function.

**Comment by MrPetovan** [comment]
I still can't ignore the original post I linked in this issue but I assume this will work from now on?

**Comment by annando** [comment]
It worked here really fine.

**Comment by MrPetovan** [comment]
Never mind, the option now shows.
