### ISSUE TITLE
DB structure update fails

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5168]
### Expected behavior

DB structure being updated automatically.

### Actual behavior

The DB structure update fails.

    $ bin/console dbstructure update
    ALTER IGNORE TABLE `group_member` MODIFY `contact-id` int unsigned NOT NULL EFAULT 0 COMMENT 'contact.id  of the member assigned to the associated group'; 

### Steps to reproduce the problem

1. execute `bin/console dbstructure update` from the CLI at the base of the Friendica directory

### Friendica version you encountered the problem

2018.08-dev

### Friendica source (git, zip)

git

### PHP version

7.0

### SQL version

MariaDB 10.1.23

**Comment by MrPetovan** [comment]
What's the error?

Did you copy the exact message from the `dbstructure update` output?

The two last automatic DBstructure updates went fine on my server, even though they went for a long time.

**Comment by tobiasd** [comment]
Please see above for the output of `dbstructure update`.

**Comment by MrPetovan** [comment]
The query is missing a `D` before `EFAULT` and I was wondering if it was a copy&paste mistake or the actual output. The latter would surprise me because we haven't changed this part of the dbstructure update.

**Comment by tobiasd** [comment]
Could have been a new line in the terminal and an accidentally double take of the backspace key.

**Comment by MrPetovan** [comment]
Do you have the associated database server error with the fail?

**Comment by tobiasd** [comment]
It is working now.
