### ISSUE TITLE
Forum RSS feed

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5181]
Feature request

RSS feed for forums

### Friendica version you encountered the problem
Friendica develop / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1

**Comment by tobiasd** [comment]
Try something along the lines of https://forum.friendi.ca/feed/helpers/posts

**Comment by hoergen** [comment]
OMG yes. It's my fault. I didn't edit the access rights for posts So the posts were not visible for everyone. Now that I changed it, it works like a charme. Thank you. I close it now.

**Comment by MrPetovan** [comment]
That was easy.
