### ISSUE TITLE
Deleted Users Still Listed in Local Directory

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5188]
### Expected behavior

Deleted users should not appear in the local directory.

### Actual behavior

Users awaiting permanent deletion are still listed in the local directory and only their profiles have been removed.

### Steps to reproduce the problem

1. Go to user’s Settings menu.
2. Click on Remove account.
3. Switch to any other user account, then view the local directory.

### Friendica version you encountered the problem

2018.08-dev - 1268

### Friendica source (git, zip)

git clone

### PHP version

7.2.5

### SQL version

Didn’t check.

**Comment by MrPetovan** [comment]
If you access the account from the local directory, the profile correctly doesn't show up?

**Comment by MrPetovan** [comment]
Indeed, i was just making sure the bug wasn't deeper. Thank you for the report!
