### ISSUE TITLE
Corrupt HTML in Registration Request Emails

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5191]
### Expected behavior

`Site Location: <a href=“https://example.com”>https://example.com</a>`

### Actual behavior

`Site Location: <a href=“https://example.com<br target=“_blank”>https://example.com<br</a> />`

### Steps to reproduce the problem

Configure site for registration by approval only.

### Friendica version you encountered the problem

2018.08-dev - 1268

**Comment by miqrogroove** [comment]
Looks like the bare URL is specified here, and is corrupted some time before the email goes out.

https://github.com/friendica/friendica/blob/13557985844b669f2dbae1294b39044928a1078f/include/enotify.php#L369

**Comment by MrPetovan** [comment]
It looks like you could have a line break after your site URL in your `.htconfig.php` value for `hostname`. This line break gets transformed into `<br/>` on line 568 of `include/enotify.php`.

**Comment by miqrogroove** [comment]
My .htconfig.php file has no mention of hostname.  It is not there by default and I have done nothing to add it.

**Comment by MrPetovan** [comment]
Indeed, this is set in your admin settings. Please make sure the hostname doesn't have any trailing charcter that could be interpreted as a line break.

**Comment by MrPetovan** [comment]
While testing #5180 I could confirm that the problem probably comes from a wrong hostname config value, and it is set in the Admin settings.

**Comment by MrPetovan** [comment]
To debug this you probably have to get the value of `$body` on line 564 (just before the text/html conversion), and work your way through `html_entity_decode(BBCode::convert(stripslashes(str_replace(["\\r\\n", "\\r", "\\n\\n", "\\n"], "<br />\n", $body))), ENT_QUOTES, 'UTF-8')`, unpacking the output of each nested function.

**Comment by MrPetovan** [comment]
> Are you sure this isn’t the problem right here?

No, or it would fail on all systems, which it didn't on mine. My best guess would be the autolinker that would grab more than expected because we don't manually add a `<a>` tag. However, we pass the body to `BBCode::convert()` and it adds anchor links to what seems like URLs via a regular expression.

**Comment by miqrogroove** [comment]
$body
`Site Location:	https://example.com\nLogin Name:`

$step1
```Site Location:	https://example.com<br />
Login Name:```

$step2
```Site Location:	https://example.com<br />
Login Name:```

$step3
`Site Location:	<a href="https://example.com&lt;br" target="_blank">https://example.com&lt;br</a> /&gt;<br>Login Name:`

$step4
`Site Location:	<a href="https://example.com<br" target="_blank">https://example.com<br</a> /><br>Login Name:`

**Comment by miqrogroove** [comment]
https://pastebin.com/3LYj9Yfj
