### ISSUE TITLE
SocialHome: Direct link to source post is wrong

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5194]
### Expected behavior

Clicking on "Link to source" on a public SocialHome (https://github.com/jaywink/socialhome) post opens it on the remote server.

### Actual behavior

The source link gives a "Page not found" error on SocialHome.

### Steps to reproduce the problem

1. Navigate to https://friendica.mrpetovan.com/display/e82fa84f-f8a9-4ad5-b207-7a5dd0ffe6af
2. Click the top right menu arrow
3. Click the "Link to source" link
4. It opens https://jasonrobinson.me/posts/e82fa84f-f8a9-4ad5-b207-7a5dd0ffe6af and shows "Page not found".

Actual post link is https://jasonrobinson.me/content/1696845/ah-the-joy-of-providing-a-free-service-ht/

### Friendica version you encountered the problem

2018-08-dev

### Friendica source (git, zip)

git

### PHP version

7.2

### SQL version

MariaDB 10.5

Paging @jaywink

**Comment by annando** [comment]
Currently Socialhome doesn't have a direct link that we can provide. Hopefully @jaywink will change this over time.

**Comment by MrPetovan** [comment]
Closing for now until @jaywink manifests himself.
