### ISSUE TITLE
Frio Profile Links Broken for Mobile

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5205]
### Expected behavior

The poster’s name on any post should link to their profile.

### Actual behavior

Works on Chrome for Windows.  Works in Duepuntozero, does not work in Frio theme when testing Chrome for Android and Safari for iOS.

### Steps to reproduce the problem

1. Switch to the Frio theme.
1. [edit] Go to Admin, Site settings, and enable the Block Public setting.
1. Visit the network page.
1. Try clicking/tapping some names.

### Friendica version you encountered the problem

2018.08-dev

**Comment by rabuzarus** [comment]
At the moment a click on the profile link opens the hovercard. The profile link inside the hovercard links to the poster's profile. We can change this. But we would lose the hovercard feature for mobiles.

**Comment by annando** [comment]
The hovercard principle is incompatible to touch devices. And you know my point concerning the accessibility. We need some additional way to reach everything from the hovercard.

**Comment by miqrogroove** [comment]
But I’m not seeing the hovercard on mobile.  Whenever I tap a name, the name changes color and decoration and them nothing else happens.

**Comment by MrPetovan** [comment]
I've seen "1 touch = hover, 2 touch = click" on an Android browser but iOS mobile hasn't any behavior for hover.

**Comment by miqrogroove** [comment]
Added another ticket, which might need separate work.

Revised and re-requested the patch.  This time, it fixes the broken links without adding any problems.
