### ISSUE TITLE
Frio Has No /profiles/ Link

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5211]
### Expected behavior

The way to manage multiple profiles should be to click the Profiles link to navigate to /profiles/ as described at https://forum.friendi.ca/help/Profiles

### Actual behavior

I found no way to do this in the Frio theme except to manually type the URL.  Frio exposes the profile editor after clicking the Clone option, but after that there is no way to return to that new profile.  I switched to Duepuntozero to figure out how it should look, and I did find the link in that theme.

In light of this highly confusing feature experience, I think the best workaround is to disable the multiple profiles feature until it is working properly in any enabled themes.

### Steps to reproduce the problem

1.  Switch to Frio theme.
2.  Enable Multiple Profiles under Settings > Additional features > General
3.  Visit your own profile.
4.  Click/tap Edit Profile
5.  In the Profile actions dropdown, click Clone This Profile
6.  Make some changes and save your new profile.
7.  Visit some other page, such as Contacts.
8.  Now try to find your new profile.

### Friendica version you encountered the problem

2018.08-dev

**Comment by rabuzarus** [comment]
There is a link in frio to show/edit the profiles
If you are logged in and you hover over your profile picture in the left aside widget on your `profiles` page, a `manage profiles` icon will appear. It is the same behavior like in vier.
Sure this is not very intuitive.

I would prefer to have the user profile settings also available in the user settings. So users can easily find them However, this would require changes in the modules of friendica and would affect all themes (not solely frio)

**Comment by miqrogroove** [comment]
I disagree.  Tapping my profile picture on my profile page takes me to a raw XML text display.  The experience is terrible and appears totally broken.

**Comment by MrPetovan** [comment]
Same here for clicking on Link to Source on my own Twitter posts. It looks
like `redir/[your public contact id]` goes to the `dfrn_poll` URL which has
an XML output.

**Comment by rabuzarus** [comment]
![edit_profiles](https://user-images.githubusercontent.com/3750381/41474278-dd51228e-70bb-11e8-8126-c22f6b0ac258.png)

**Comment by miqrogroove** [comment]
Yeah it doesn't look anything like that.  Is it a desktop-only feature or widescreen only?

**Comment by rabuzarus** [comment]
desktop-only - you need to **hover** with the mouse over the profile picture

**Comment by miqrogroove** [comment]
I could not validate any of that in my testing.  I can only see a /profiles link in the following situation:

1.  The multiple profiles feature is enabled, and
2.  The browser width is sufficient to cause the profile picture to appear, and
3.  The user taps or clicks the extreme upper-right corner of the profile picture.

It is not necessary to “hover” however the link does remain invisible unless hovered.

Based on this extra info, I still believe the experience is so poor that it is best disabled.

**Comment by astifter** [comment]
I think this is fixed with PR #5475.
![friendica-local astifter com_profiles_1 pixel 2 xl](https://user-images.githubusercontent.com/206846/44119809-932ea8c8-a01a-11e8-85bb-fcac6429c8c4.png)

**Comment by miqrogroove** [comment]
This is much better.  I noticed I have to click on the Profile tab of my own profile and click on Edit Profile before I can see this though.  It's a three-step process.  Now I also see a link directly under Settings, which is even easier.
