### ISSUE TITLE
Search for tags in /API/search

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#5221]
It seems the API does  a full text  search,  which is unreliable for hashtags. This may be due  to the hashtag symbol. A special parameter to search just for hashtags would be nice.

**Comment by annando** [comment]
I would like to completely switch to hashtag search, since the fulltext search mostly runs into timeouts on every server.

**Comment by LubuWest** [comment]
The normal search works well on  my server. I would miss  it.

**Comment by tobiasd** [comment]
OP thinks it's working now - closing
