### ISSUE TITLE
Disable source storage for network != OStatus by default

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5233]
I added Friendica Support as one of my first contacts on a fresh installation.  I noticed after a few days that the conversation table had grown to ~170 MB.  This is a bit alarming, so I've just looked into its contents.

One example entry is over 800,000 bytes and appears to be an XML feed with this at the top:

`<id>https://forum.friendi.ca/profile/helpers</id>`

I wonder why these are so large and so many?  I ran the following query:

```SELECT COUNT(`item-uri`) FROM `conversation` WHERE LENGTH(`source`) > 700000```

The result was 180.

Next I ran a date query and found that every one of these entries has a received value on 2018-06-09.

I've already deleted Friendica Support as a contact.

I would like to know how to prevent this kind of extreme bloat.  And, what is the best way to clean up what I already have here?

Also, why do I have conversation entries from https://forum.friendi.ca/display/helpers/ that are dated today when I am no longer connected (and therefore nobody else is connected on my site) ?

### Friendica version you encountered the problem

2018.08-dev

**Comment by annando** [comment]
The conversation table is used to store the raw data from the received posts. This table will grow over time.

**Comment by miqrogroove** [comment]
So is it normal for it to grow over 100 MB on the same day as the first user's first connection to the support forum?

**Comment by annando** [comment]
The support forum has nothing to do with this. There seemed to have been a very large post.

**Comment by miqrogroove** [comment]
Tried changing settings with "Clean database" enabled and "Lifespan of unclaimed items" reduced to 7 days.  No difference so far.  Perhaps these are "remote" items yet not "unclaimed"?

**Comment by miqrogroove** [comment]
One example row has conversation-uri: https://forum.friendi.ca/display/helpers/167825 and LENGTH(`source`): 835840.

If I search by uri, that same one appears in 3 rows, each with the same source length.

**Comment by MrPetovan** [comment]
You can manually clear the `source` column in the `conversation` table or the `object` in the `item` table if you don't plan on troubleshooting federation. These are the raw messages we receive from remote servers and can be discarded once they have been processed by the server, which a row in the database is the proof of.

**Comment by MrPetovan** [comment]
Now that I'm thinking about it, storing source messages probably should be a setting, disabled by default.

**Comment by miqrogroove** [comment]
That would be a nice improvement, considering the size of these messages.

**Comment by annando** [comment]
The conversation table is not only used for debugging purposes, but is also used for the thread completion in the OStatus protocol.

When "DBClean" is enabled, conversation entries that are older than 90 days will be deleted.

**Comment by annando** [comment]
BTW: Never ever clean the "object" field in the "item" table. This field is used to store some data for actions (like, dislike, attend, ...) for posts from federated networks.

In the past we had stored the raw protocol data from Twitter there as well, but this had been removed from that addon.

**Comment by miqrogroove** [comment]
Also, if I join the support forum from my own Friendica site, is the OStatus protocol even used?

**Comment by MrPetovan** [comment]
Not for Friendica to Friendica communication.

**Comment by miqrogroove** [comment]
So there's that.  Could we simply not save the source field when using Friendica protocol?

**Comment by MrPetovan** [comment]
We can add Diaspora to the list as well.

**Comment by miqrogroove** [comment]
Getting warm?

https://github.com/friendica/friendica/blob/1e00efdb99fb1a333fca5bd75d2ceb55ce0f1166/src/Model/Conversation.php#L52

**Comment by annando** [comment]
We have to use it for Friendica posts as well, since Friendica and OStatus do interact. I could imagine that we have some setting to define the days that we store this data.

**Comment by miqrogroove** [comment]
This is patterned from other examples in the same file.  Untested.  Just looking for feedback.

https://github.com/friendica/friendica/compare/develop...miqrogroove:patch-1

**Comment by MrPetovan** [comment]
I'd prefer to give feedback on a PR, even if you retract it later.

**Comment by annando** [comment]
I don't understand the need for this patch. In DBClean we already have got this cleaning of the "conversation" table. We only need to add some parameter to it instead of the constant.

**Comment by MrPetovan** [comment]
What if you want to keep the conversation but not the source?

**Comment by annando** [comment]
The only purpose of this table is to keep the original source that we received.

**Comment by MrPetovan** [comment]
My mistake, but then again there's no PR to request changes yet.

**Comment by MrPetovan** [comment]
Is this closed by #5263 ?

**Comment by miqrogroove** [comment]
My conversation table is shrinking nicely now after a pull and a htconfig update.

I still don't know why the new support forum posts are showing up in my table when nobody is connected, but that's not so bad.

**Comment by MrPetovan** [comment]
`gcontact` and `fcontact` rows are meant to stay even if no user has a connection with the recorded accounts. They are snapshots of the "whole known fediverse". Check the `uid` in the `contact` table, if it's `0`, it means that it is the public record of this account on your server, with no ties to a specific user.

**Comment by miqrogroove** [comment]
Yeah I don't see anything else unusual.  Closed for me.
