### ISSUE TITLE
[Addons] Where are Twitter/Email/G+ addons ?

### ISSUE THREAD

**Issue by Draky50110** [friendica/friendica#5239]
Hello.
Trying Friendica for 1st time, can't find a page where Twitter and Google+ addons are.
Found a Github page with addons but not those and links like addons.friendi.ca is not working.

**Comment by AndyHee** [comment]
Your node is up and running?

If yes go to the admin panel and activate the twitter addon. You need to configure it as admin and than your users can use it by adding their credentials.

If your node is not up yet, install ALL addons via `git checkout https://github.com/friendica/friendica-addons` into the friendica root folder.

**Comment by tobiasd** [comment]
The addons are in [friendica/friendica-addons](https://github.com/friendica/friendica-addons) that you need to clone into the `addon` directory in your friendica base directory.

    git clone https://github.com/friendica/friendica myfriendica
    cd myfriendica
    bin/composer.phar install 
    git clone https://github.com/friendica/friendica-addons addon

Or if you have downloaded the full-archive for Friendica core, you can download the friendica-addon archive provided by github from the repository above and put the contents of the archive into the addon directory.

The addon directory should then contain e.g. a twitter subdirectory, that contains the addon.

**Comment by Draky50110** [comment]
Thanks a lot !
