### ISSUE TITLE
Worker Maximum load does not work as advertised

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5243]
### Expected behavior

Worker queues need to have robust self-recovery.

### Actual behavior

The "Maximum load average" does not work as advertised.

This setting comes with the tip:  "Maximum system load before delivery and poll processes are deferred (default 50)."

Debugging results:

When I look at the process table, it is empty.

When tooMuchWorkers() calls activeWorkers() it comes back as 1 (I guess because worker.php is now trying to run?)

$queues is correctly set to 2.

maxloadavg is set to 50.

If I have less than 3 workers and less than 51 load, I expect my worker to run.

The worker does not run.

By the end of tooMuchWorkers(), the $queues value has been reduced to 1, preventing any further work because the return value of tooMuchWorkers() is return $active >= $queues;

Why only 1 queue?  Let's see...

$load comes back as, for example, 41.88, with maxloadavg at 50.  Now, 

$slope = 2 / pow(50, 3);

$slope = 2 / 125000;

$queues = ceil( 0.000016 * pow(max(0, 50 - 41.88), 3));

$queues = ceil( 0.000016 * pow(8.12, 3);
$queues = ceil( 0.000016 * 535);
$queues = ceil( 0.009 )
$queues = 1;

The formula used here is completely mismatched with description of the Admin settings.  We have a very specific example where the load is below the maximum, and yet all workers are being deferred.

### Friendica version you encountered the problem

2018.08-dev - 1268

**Comment by MrPetovan** [comment]
Thanks for the investigative work!

**Comment by miqrogroove** [comment]
Two obvious things that might be done if we want the behavior to match the description:

Change
```$queues = ceil($slope * pow(max(0, $maxsysload - $load), $exponent));```

To
```if ($load > $maxsysload) $queues = ceil($slope * pow(max(0, $maxsysload - $load), $exponent));```

And Change 
```return $active >= $queues;```

To
```return $active > $queues;```

**Comment by annando** [comment]
The formula is meant to decrease the number of workers according to the load. When the load is about 0 to 1, all specified workers will be used. But when the load is near the maximum load, the number of workers goes to 1. And when the load is even higher, then the system won't work at all.

**Comment by miqrogroove** [comment]
I could use that as the intention, or strategy, for a patch, but currently it does not work that way.

**Comment by annando** [comment]
The system works as expected. It is based on the idea that an idle system has got a load of 0-1. Only then the system will use the whole number of workers.

**Comment by miqrogroove** [comment]
The system never uses the whole number of workers.  As I demonstrated above, the logic tests for $active >= $queues after $active was already incremented, which means the whole number of workers is never reached.

**Comment by annando** [comment]
Calculate the above formula with a load of 0.2.

**Comment by miqrogroove** [comment]
$queues = ceil( 0.000016 * pow(max(0, 50 - 0.2), 3));

$queues = ceil( 0.000016 * pow(49.8, 3);
$queues = ceil( 0.000016 * 123506);
$queues = ceil( 1.976 )
$queues = 2;

Assuming the 2nd worker.php just started, $active = 2.

return $active >= $queues;
return 2 >= 2;
return true;

tooMuchWorkers() returns true, and the 2nd worker throws a debug error.

**Comment by MrPetovan** [comment]
Closed via #5248

**Comment by miqrogroove** [comment]
With debug logging turned on, I'm getting so many messages from Worker.php now I can't tell if it's working or not working.  😆  I think by looking at the source of the debug messages, I can understand what it's doing.  I still had max queues = 2, and now it's reporting Load: 5.66/100.  Based on the new formula, this load is "more than tiny" so I only get 1 worker.  If this is normal for my server, then max queues = 3 may be appropriate.

**Comment by miqrogroove** [comment]
And confirmed.  Max queues 3 gives noticeably better results for me.  So this new formula not only works better, it gives me much better control over system performance.  Yay!

**Comment by annando** [comment]
The exponential function in the code had been chosen by intention. The background is that when your system works fine with a load of 1 and stops working with a load of 40, then at a load of 20 it isn't only half dead, but is already extremely slow.

**Comment by miqrogroove** [comment]
One way to address that is to set the max load at 20.  Another would be to refactor the formula again so that it works as intended with a non-linear function, but one that respects a server like mine that might work well a 20 or 40 load.

**Comment by annando** [comment]
Problem is that we don't know at which level your used server really is at it's limit. I made a PR that sets the linear calculation as an option that can be enabled via the .htconfig.php.

**Comment by miqrogroove** [comment]
I don't see any reason to include two different calculations that accomplish the same thing.  I will refactor this again.

**Comment by miqrogroove** [comment]
Please see #5251 for a clearer implementation.
