### ISSUE TITLE
Frio: Can't Connect/Follow an Atom URL

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5244]
### Expected behavior

From the Contacts page, I should be able to supply a URL, such as https://gnucash.org/atom.php and then click the Connect button.

### Actual behavior

In Duepuntozero theme I'm sent to /follow?url=https%3A%2F%2Fgnucash.org%2Fatom.php&submit=Connect where I'm given a "Submit request" button.

In Frio theme I'm sent to a blank screen at /follow?url=https%3A%2F%2Fgnucash.org%2Fatom.php  The page source is hundreds of lines of code, but it doesn't render anything other than a background color.

### Steps to reproduce the problem

1. Switch to Frio theme.
2. Go to /contacts
3. Paste a URL in the "Add new contact" widget.
4. Click/tap the Connect button.

### Friendica version you encountered the problem

2018.08-dev

**Comment by rabuzarus** [comment]
https://github.com/friendica/friendica/issues/2552 - point 20

**Comment by MrPetovan** [comment]
Point 20 is "Network view: borders of shared content are generated through js (this will not applied on new content which is loaded through js -> autoload next page or new post through update) -> I'm not happy to solve this with js. This is something core should provide (shared content in an own div with a class "shared_content")" 🤔

**Comment by rabuzarus** [comment]
no is's
> many templates aren't available for frio

**Comment by MrPetovan** [comment]
Point 21 then, but I had to count manually (twice) and it wasn't a fun task.

**Comment by rabuzarus** [comment]
OK Point 21. I have now counted for the fourth time. And now it is point 21 :-/

**Comment by MrPetovan** [comment]
My point is: don't use point numbers.

**Comment by AlfredSK** [comment]
I don't know but... works here. Cannot reproduce. The button is there and after clicking it the atom feed is added as contact.
2018.08-dev

**Comment by miqrogroove** [comment]
You know what, this is caused by the ABP plugin for Chrome.

Consider that solved!
