### ISSUE TITLE
Error while installing 2018.05

### ISSUE THREAD

**Issue by cyfyrifilefe** [friendica/friendica#5254]
### Expected behavior
Run installation script.

### Actual behavior
Warning: require_once(/var/www/friendica/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/friendica/boot.php on line 20
Fatal error: require_once(): Failed opening required '/var/www/friendica/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/friendica/boot.php on line 20

### Friendica version you encountered the problem
2018.05

### PHP version
7.0.27-0+deb9u1

**Comment by tobiasd** [comment]
You are missing the composer managed dependecies from your installation.As you did not mention your installation source (git or from the archive) there are different solutions for the problem.

You can either pull the dependencies manually from the base of your Friendica installation. This has to be done whenever you pull from the repository and there are changes to the dependencies. To do so, please use the following commands on the CLI

    git clone https://github.com/friendica/friendica [web server folder]
    cd [web server folder]
    php bin/composer.phar install

see [INSTALL.txt](https://github.com/friendica/friendica/blob/develop/INSTALL.txt#L67). This can be automated, an example can be found [here](https://github.com/friendica/friendica/blob/develop/doc/Developers-Intro.md#composer).

If you are not using git to manage the code, then please take the [friendica-full-2018.05](https://github.com/friendica/friendica/files/2061623/friendica-full-2018.05.tar.gz) archive file as advertised in the release notes. It contains also the dependencies.

**Comment by cyfyrifilefe** [comment]
Thank you very much Tobias,

with the  friendica-full-2018.05 I could get it running.

I think it would be very important to link directly to the full archive. 
To prevent frustration and preserve friendica's good reputation.

Friendly ;-)

**Comment by tobiasd** [comment]
Great :-) I'll have a look where we can put that link more prominent
