### ISSUE TITLE
Uncaught TypeError: Argument 4 passed to get_responses() must be of the type array

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5257]
I'm getting a lot of PHP fatal errors.

````
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to get_responses() must be of the type array, boolean given, called in /friendica/mod/photos.php on line 1601 and defined in /friendica/include/conversation.php:1423
Stack trace:
#0 /friendica/mod/photos.php(1601): get_responses(Array, Array, '', false)
#1 /friendica/index.php(391): photos_content(Object(Friendica\App))
#2 {main}
  thrown in /friendica/include/conversation.php on line 1423
````

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
MariaDB 10.0

**Comment by tobiasd** [comment]
Seems to be caused when visiting a photo album.

**Comment by MrPetovan** [comment]
Closed via #5280

**Comment by miqrogroove** [comment]
I just need to point out that although the pull helped avoid that error message, the return value of Item::selectFirst() in photos.php is still unchecked and so nothing has been done to resolve the original error message if it should be triggered in the future.  If Item::selectFirst() returns false, the same fatal error will be generated by get_responses().

**Comment by MrPetovan** [comment]
Thanks for the elaboration!
