### ISSUE TITLE
Deleted account posts still display on community page

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5260]
### Expected behavior

Not to see the postings on the community page.

### Actual behavior

They are there

### Steps to reproduce the problem

Delete an account with postings visible on the community page (or have a user delete their account). And look at the community page.

### Friendica version you encountered the problem

2018.05

I think this is related to #5010 and #5188

**Comment by annando** [comment]
It seems as if contact deletion works fine now: https://forum.friendi.ca/display/0b6b25a8575b8c2cb511552474836294

**Comment by MrPetovan** [comment]
Is this fixed?

**Comment by annando** [comment]
Can we close it now?

**Comment by tobiasd** [comment]
I'd really like to test this in snarl first, once it is on the RC branch.

**Comment by tobiasd** [comment]
As I could not find postings of deleted accounts there, I'll close this issue now.
