### ISSUE TITLE
Postings to forums distributed to contacts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5262]
### Expected behavior

Using the !name notation, forum postings should not be distributed to contacts.

### Actual behavior

Two of my contacts reported seeing postings in their timeline that were posted to a forum they are not member of (¹Berliner Luft and !Deutschsprachige Nutzer at snarl).

* https://kirgroup.com/display/f3ad7b1c155b2a96c028b90183559636
* https://amici.pallamondo.net/display/f3ad7b1c115b29fee6e56f6513721697

### Friendica version you encountered the problem

Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1269 

### PHP version

7.0 (on snarl 5.6 in case it is relevant)

**Comment by tobiasd** [comment]
Postings are also distributed over the OStatus protocol.

**Comment by annando** [comment]
Distribution over the OStatus protocol is intended - due to the way that protocol is working.

**Comment by tobiasd** [comment]
> Distribution over the OStatus protocol is intended - due to the way
> that protocol is working.

Could you check the docs about this and correct them eventually? So far I understood you differently that !name is _exclusively_ for the forum and not distributed otherwise.

**Comment by annando** [comment]
Public posts (also comments) are always distributed to all OStatus followers. This is how OStatus is supposed to work.

**Comment by MrPetovan** [comment]
I agree with @tobiasd , !name posts shouldn't be public with regard to OStatus.

**Comment by annando** [comment]
I just tested with post https://forum.friendi.ca/display/ec054ce7115b84594849f9f897733002 - this post was sent only to the forum - not to anyone else. And the coding looks safe.

**Comment by annando** [comment]
I had a deeper look into the feeds (OStatus and DFRN) that we provide. This shouldn't be a loophole either. I'm still on the search.

**Comment by MrPetovan** [comment]
This issue should be tested again with the latest RC.

**Comment by annando** [comment]
Can we close this issue now?

**Comment by tobiasd** [comment]
Yes, I think this is fixed. At least towards the OStatus world I did not see leaks and I did not hear complains about forum postings appearing to them.
