### ISSUE TITLE
Fix Class dba For Prepared LIMIT

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5266]
### Expected behavior

The database driver should be able to prepare statements similar to "LIMIT ?"

### Actual behavior

The database driver binds all variables as string literals, including integers.

Notice args missing here

https://github.com/friendica/friendica/blob/019637123a5676c218b33725131efd9d5a6844eb/include/dba.php#L430

**Comment by MrPetovan** [comment]
What kind of DB failure? Hopefully not a silent or generic one.

**Comment by miqrogroove** [comment]
It's been quite a rabbit hole.  I've got enough info now to make a new ticket.

**Comment by MrPetovan** [comment]
Friendica "The Rabbit Hole" 2018.08

**Comment by miqrogroove** [comment]
I confirmed with the patch for the other ticket that the "LIMIT ?" syntax now works with both drivers.

I will follow up to the PR comments about Delivery.php after dinner.  I haven't had a chance to look at the code for that, and it wasn't clear from the comments exactly why that patched caused a problem.

**Comment by miqrogroove** [comment]
> It is converted to some WHERE `id` IN ("20284642",20284642) - and this leads to the problem that the query lasts several minutes instead of a fracture of seconds.

I simply don't understand the problem here, so could you explain what this is doing that is not normal?  In other words, if the old query was `IN ("20284642","20284642")` and the new query has `IN ("20284642",20284642)` then why is the latter running slowly?  And why isn't the solution as simple as typecasting one ID or the other?

> The problem is that the record we get are all strings, no matter the field type.

This is totally normal in PHP.  Again, I am missing the point because I deal with databases in PHP all the time.  What exactly is the "problem" specific to this situation?

> Problem is that integer database values don't return values as integer - and that this results in some speed problem with "IN(...)".

Again, the first statement is always true, and the second statement I'm not understanding.  What is the speed problem exactly?  Before we had only strings and now with integers everything is slowing down?

**Comment by miqrogroove** [comment]
This just doesn't make any sense.  How can an IN condition with only 2 values take "minutes" to evaluate?  I think this is not accurate.  And if there is an unidentified problem, then it would be best to revert the patch.

**Comment by MrPetovan** [comment]
@annando used a benchmark of the same query performed 100,000 times.

Strings-only: 30 seconds
Mixed types: 39 seconds

I believe it is significant, even though I'm as confused as you are.

**Comment by MrPetovan** [comment]
I'm just re-hashing the conversation from https://github.com/friendica/friendica/pull/5267#issuecomment-399210132 on, but you can check for yourself.

**Comment by miqrogroove** [comment]
Let's wait for some clarification.

**Comment by miqrogroove** [comment]
Woah look at this

https://bugs.mysql.com/bug.php?id=64791

**Comment by miqrogroove** [comment]
I can see the direction annando was taking, and he would have realized it was a bit upside down eventually.  I will put a patch against his latest commit.

**Comment by annando** [comment]
@miqrogroove Yup, that MySQL bug exactly describes the problem that I experienced. And instead of having the need to use a unified cast, I want to solve this problem at a central place.

**Comment by miqrogroove** [comment]
This new patch fixes the condition generator.  I can only think of two other centralized strategies.  One is to revert all these patches.  The other is to add a central helper function for every IN() usage.  A specific IN() generator, if you will.

**Comment by MrPetovan** [comment]
Closed via #5272
