### ISSUE TITLE
loadHooks() Triggers !$can_be_prepared if PDO Disabled

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5268]
The only obvious symptom I get is this:

[21-Jun-2018 19:47:59 UTC] PHP Warning:  mysqli_result::close(): Couldn't fetch mysqli_result in /include/dba.php on line 1415

The backtrace points me to loadHooks().

After a bunch of digging, I'm as far as the "break" statement in dba.php under `if (!$can_be_prepared || (count($args) == 0)) {`

**Comment by annando** [comment]
This "can_be_prepared" is needed since on MySQLi you cannot prepare all SQL commands.

**Comment by miqrogroove** [comment]
annando, I think we have to dig deeper.  It's the dba::select() call generating that query.  So either we got count == 0 or something else strange happening, and it is not caught properly.

**Comment by miqrogroove** [comment]
Okay, here's the problem.

In the mysqli driver, if there are no args passed due to no prepare needed, the dba::p() returns the wrong object.  It goes to `$retval = self::$db->query(` which returns mysqli_result and not a mysqli_stmt.

**Comment by miqrogroove** [comment]
In the next step, dba::close() is called, which triggers a `mysqli_result->free_result()` followed by a `mysqli_result->close()` which is at that point invalid because the object no longer exists.

**Comment by MrPetovan** [comment]
Closed via #5271
