### ISSUE TITLE
Fatal error after last git pull

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5275]
`Fatal error: Uncaught Error: Class 'Item' not found in /Path to friendica/addon/viewsrc/viewsrc.php:45 Stack trace: #0 /Path to friendica/src/Core/Addon.php(246): viewsrc_item_photo_menu(Object(Friendica\App), Array) #1 /Path to friendica/src/Core/Addon.php(223): Friendica\Core\Addon::callSingleHook(Object(Friendica\App), 'item_photo_menu', Array, Array) #2 /Path to friendica/include/conversation.php(868): Friendica\Core\Addon::callHooks('item_photo_menu', Array) #3 /Path to friendica/src/Object/Post.php(369): item_photo_menu(Array) #4 /Path to friendica/src/Object/Thread.php(183): Friendica\Object\Post->getTemplateData(Array) #5 /Path to friendica/include/conversation.php(731): Friendica\Object\Thread->getTemplateData(Array) #6 /var in /Path to friendica/addon/viewsrc/viewsrc.php on line 45`

See yourself : https://horche.demkontinuum.de/network?f=&order=post&

### Friendica version you encountered the problem
Friendica develop / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1

**Comment by hoergen** [comment]
Restarted apache  and it is working again . wtf?

**Comment by hoergen** [comment]
Scrolling down the timeline the message is there again and repeating 

![00_temp](https://user-images.githubusercontent.com/24474762/41774844-aae52672-7621-11e8-9abf-f78f069d7a4d.jpg)

**Comment by hoergen** [comment]
And there it is again  like here https://github.com/friendica/friendica/issues/5275#issue-334838915  :(

**Comment by hoergen** [comment]
horche.demkontinuum.de is officially down aka doesn't work anymore because of this error :(

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/629#issuecomment-399417130

**Comment by MrPetovan** [comment]
Please update your addons.

**Comment by hoergen** [comment]
@MrPetovan you should not  close my issues when they are not solved. 

**Please reopen! Thank you!**

I always update friendica and the addons with a script. I pulled 3 times now and the problem is still existing.

**Comment by hoergen** [comment]
Restarted apache and mysql pulled again 2 times and NOW it is working again.

Thank you 🌻
