### ISSUE TITLE
New Addon idea: Mastodon custom emojis

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5292]
Mastodon servers can offers custom `:shortcodes:` producing custom emojis images on their server, but this is lost when displaying in Friendica.

Thankfully, Mastodon servers publish their list of custom emojis with the shortcode and associated image (see https://mastodon.social/api/v1/custom_emojis)

This new addon would poll known Mastodon server for their custom emojis, store them locally, and hook into the post body renderer to replace custom shortcodes with the corresponding img tag.

To prevent conflicts, this replacement should only occur for Mastodon posts and ony with the custom emojis of the author’s server.

**Comment by tobiasd** [comment]
There is the `smilie` hook to expand the emoji list which should be used for this I think.

**Comment by tobiasd** [comment]
It handles only the list of available emojis AFAIK so the replacement of the emojis can then be done later at the central place.

**Comment by MrPetovan** [comment]
Yeah, this wouldn't work for this addon. This addon should open the possibility of selectively apply smilies based on the source network and the specific instance. I'm regularly getting Friendica smilies wrongly replaced into non-Friendica posts.

**Comment by annando** [comment]
I guess we can close this issue, since the addon is existing now?
