### ISSUE TITLE
API /users/show requires login in develop

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#5318]
In the develop version  2018-08 the API /users/show requires a login. In earlier versions this wasn't necessary. Is there a reason for this or is it a bug?

**Comment by Rudloff** [comment]
@LubuWest Are you calling it with the `user_id` or `screen_name` parameter? This does not require login on 2018.05.

(Calling it without any parameter requires a login for some reason though. It should probably return an error saying that either `user_id` or `screen_name` is required instead.)

**Comment by LubuWest** [comment]
I am calling with screenname to check if the name  exists in the server.

**Comment by annando** [comment]
When this is the same behaviour like Twitter is doing, then it is a "won't fix" in my eyes.

**Comment by LubuWest** [comment]
I removed the API request from latest Friendiqa version.

**Comment by annando** [comment]
When you need to do something in Friendiqa that isn't possible by now, just create an issue. It should be no problem creating a new API function.

**Comment by LubuWest** [comment]
The check was needed because people put all type of data in the user field. But I think with the relabeling to nickname the check is no longer needed by now. And I created so many more important open issues for the API...
