### ISSUE TITLE
Worker details admin page

### ISSUE THREAD

**Issue by JeroenED** [friendica/friendica#5319]
As proposed on [friendica](https://social.jeroened.be/display/cd9f100a205b254034b1acb148434485) and mr. Petovan's request I think it would be nice to have a page with the current queue of worker jobs and possible current progress.

Details on page (if possible)
- Created (eg. 2018/07/04 14:07:18)
- Job (eg. DBClean)
- Job parameters in text (eg. Expired Threads)
- Priority
- current progress on task

**Comment by MrPetovan** [comment]
Thanks for suggesting this new feature!

**Comment by JeroenED** [comment]
Assigned to @JeroenED
Closed by commit 678efab1c9105c9a1a4098a42c4a7bc7ae0dfabc
