### ISSUE TITLE
Likes cannot be undone

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5321]
### Expected behavior

When a posting or comment was liked, it should be possible to withdraw the like with a 2nd click on the like button.

### Actual behavior

You can click the button as often as you want, the like is stuck.

### Steps to reproduce the problem

Like something. Decide it is not worth the like and try to remove it.

### Friendica version you encountered the problem

2018.08-dev

**Comment by annando** [comment]
Will be fixed with PR https://github.com/friendica/friendica/pull/5323

**Comment by MrPetovan** [comment]
Closed via #5323

**Comment by tobiasd** [comment]
Unliking still does not work here on the latest develop code (bd1056a61e49b7ec2073d2fba5dc45f23188b2f0), hence I reopened the issue.

**Comment by annando** [comment]
It does work. I guess you had tried on some item you tried before? Then have a look in the database. You will see several likes from the same author. This is a cause of the fixed bug. When you test on some fresh item you will see that it works.

**Comment by tobiasd** [comment]
Nope, tried it on new items. The like is stuck there.

**Comment by tobiasd** [comment]
Same is true for dislikes.

**Comment by annando** [comment]
Please check whether there is a difference between liking/unliking a post or a comment. I'm currently investigating.

**Comment by AlfredSK** [comment]
From my experience it doesn't happen all the time. 
I **can** like/unlike **my own posts** for example. But I **cannot** unlike **my own comments**.
I **can** like/unlike Twitter posts.
I **cannot** unlike Friendica, Diaspora, Mastodon (OStatus) posts.

**Comment by MrPetovan** [comment]
I can verify this, see https://friendica.mrpetovan.com/display/ec054ce7365b4d8930e94fa771799633

**Comment by MrPetovan** [comment]
Existing likes before the fixing PR still can't be undone but new likes can be (even though the display doesn't asynchronously update on frio).

**Comment by MrPetovan** [comment]
Closed via #5557 and #5558
