### ISSUE TITLE
Dbstructure update 1276 isn't marked successful after applying

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5334]
### Expected behavior
After running... 
`sudo -u www-data php bin/console.php dbstructure update`

I should only get that output **once**... 

````ALTER IGNORE TABLE `item-activity` MODIFY `uri` varchar(255) NOT NULL, MODIFY `uri-hash` char(80) NOT NULL COMMENT 'SHA-1 and RIPEMD-160 hash from uri', MODIFY `activity` smallint unsigned NOT NULL;```` 

### Actual behavior
But I get it again and again when I run the dbstructure update command.
If I run the query manually in MySQL console everything looks okay. No errors.

### Friendica version you encountered the problem
2018.08-dev (current code)

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 MariaDB

**Comment by copiis** [comment]
I can confirm, here to after each bin/console.php dbstructure update

**Comment by AlfredSK** [comment]
I think I can close this because it didn't happen on subsequent updates.
Objections?

**Comment by AlfredSK** [comment]
Okay. :-)

**Comment by annando** [comment]
I guess we can close it, can't we?

**Comment by AlfredSK** [comment]
Well, you said we have to watch this. So I watched... :-)
Closing.
