### ISSUE TITLE
Personal notes broken again

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5337]
### Steps to reproduce
Go to .../notes. No notes available. 

### Version
2018.08-dev

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 MariaDB

**Comment by annando** [comment]
I will have a look at it after fixing the warnings - which will last some hours, I guess.

**Comment by tobiasd** [comment]
Juoo, none of the private notes shown.

**Comment by annando** [comment]
Yeah, fixing the warnings took some more hours. I will have a look at it.

**Comment by annando** [comment]
Will be fixed with PR https://github.com/friendica/friendica/pull/5380

**Comment by tobiasd** [comment]
I think you should refer from the *fixing* PR to this request, then the status of that PR will be shown directly behind the reference and one can see if the PR is open or merged.

For me the notes are back again, so I'll close the issue.

**Comment by AlfredSK** [comment]
Sorry to bring bad news. Personal notes are broken again.

**Comment by MrPetovan** [comment]
Please open a new issue titled "Personal notes broken again again".
