### ISSUE TITLE
Settings of advanced content filter is an empty page.

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#5341]
### Expected behavior
There should be text fields and/or switches/options, something.

### Actual behavior
The page is empty and it's not possible to do anything.

### Steps to reproduce the problem
I just have to open the page via /addon

### Friendica version you encountered the problem
I don't know the friendica version, but to me the advanced content filter behaved this way since the advanced content filter appeared.

see `example.com/friendica` on your Friendica node for the version information.
current develop

### Friendica source (git, zip)
git

### PHP version
5.6.36-0+deb8u1

### SQL version
10.0.35-MariaDB

**Comment by MrPetovan** [comment]
I just tested, the advanced content filter page is still working as of commit e84c48b979ab265cd29ff3624e975e288c6755fc dating from June 20th 2018.

**Comment by rebeka-catalina** [comment]
On 2018.07.09, Hypolite Petovan wrote:
> I just tested, the advanced content filter page is still working as of commit e84c48b979ab265cd29ff3624e975e288c6755fc dating from June 20th 2018.

For me it never worked. The problem exists on our site from the
beginning.

**Comment by MrPetovan** [comment]
The advanced content filter setting page is a Javascript Vue app, do you have any error in the browser console?

**Comment by rebeka-catalina** [comment]
On 2018.07.09, Hypolite Petovan wrote:
> The advanced content filter setting page is a Javascript Vue app, do you have any error in the browser console?

Yes, there is one error message:

``
Content Security Policy: The page’s settings blocked the loading of a
resource at self (“default-src”). Source: call to eval() or related
function blocked by CSP.
vue.min.js:6
``

**Comment by MrPetovan** [comment]
Okay thanks, this is helpful. So we should either relax the Content Security Policy or avoid eval calls.

**Comment by rebeka-catalina** [comment]
Is this a bigger task, or do you think this could be done with the
other issues for the next release?

**Comment by MrPetovan** [comment]
I found that Vue templates can be compiled in advance, which would avoid `eval()` calls and pass the CSP block.

**Comment by rebeka-catalina** [comment]
On 2018.08.04, Hypolite Petovan wrote:
> I found that Vue templates can be compiled in advance, which would avoid `eval()` calls and pass the CSP block.

Thank you very much! Now it works and I'm very excited :-)

**Comment by MrPetovan** [comment]
Great, that was the point! I probably am the only that can change the display of the addon settings from now on, but at least it's working for you!

**Comment by rebeka-catalina** [comment]
On 2018.08.04, Hypolite Petovan wrote:
> Great, that was the point! I probably am the only that can change the display of the addon settings from now on, but at least it's working for you!

I haven't yet tested the addon itself - I must say that I am really
missing some real life examples and a few explanations there on it's
help page.
I would like to try a while the next days and then ask you a few
questions. I think we should enlarge it's documentation a bit.

**Comment by MrPetovan** [comment]
I'm available for all your questions. The addon is intended to be generic and expose as much data from items as possible, which can be confusing indeed.

Here are my own rules:
- "Mastodon Sensitive Image": `content_warning && network == 'stat' && body matches "/\\[img\\]/"`
- "NSFW": `body matches "/\\]#NSFW\\[/i"`
- "NSFW image": `body matches "/nsfw/i" and body matches "/\\[img/"`
