### ISSUE TITLE
Problems with theme and setup

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#5354]
Since a few days my node acts weird. There is no notifications anymore about tagging, new introductions and such, but instead the rendering is garbled with post & received dates and such. 

See https://silverhaze.org/s/zp3e6NpE5RmKFrK for a screenshot. 

Version is Friendica 'The Tazmans Flax-lily' 2018.05 - 1276 which is weird by itself as it seems to be running on stable code base but with develop database structure as discussed on XMPP conference chat. 

I already tried to remove smarty cache, browser cache and deactivated memcache setting, restarted php7.0-fpm and apache2 running on Debian stable. 
Changing theme does not help. Tested with Frio, Vier and duepuntzero.

**Comment by tobiasd** [comment]
Just some observations:

* The white field in the upper left corner is the `div id="panel"` missing the `style="display:none;"`.
* The additional date-time stamps are the commented, received and created dates, also missing the `style="display: none;"` property. (On my node the `display: none` is set, hence I mention *missing*)
* looking at your profile page, I also see the *spinner* that is usually only visible when a posting receives some action (like etc.), that is also missing the `display:none`
* Your `/friendica` page is not working resulting in a white screen. That might be related to #2209 or not ;-)
* but according to your *nodeinfo* information your nodes version is 2018.05 with a DB of 1266 which is the correct combination.

Can you run `git diff` in your Friendica base directory and see if there are any changes reported by git? You could also run `git status` to see if there are any changed files (their diffs should be shown by the first command). If so (and the changes are unwanted) I think you can do a `git checkout 2018.05` or `git reset HEAD --hard` to reset the code to the version from the repository. But that would not explain ***why*** the style element was missing.

**Comment by ingoj** [comment]
git diff: 

```
vserv1:/var/www/net/nerdica.net/friendica# git diff
vserv1:/var/www/net/nerdica.net/friendica#

```

git status:
```
vserv1:/var/www/net/nerdica.net/friendica# git status
HEAD detached at 2018.05
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .htaccess.old
        doc/Plugins.md
        doc/Tests.md
        doc/database/db_ffinder.md
        doc/database/db_fserver.md
        doc/database/db_item_id.md
        doc/database/db_spam.md
        doc/de/Plugins.md
        doc/readme.md
        doc/upgrade.md
        friendica/
        include/Contact.php
        include/DirSearch.php
        include/Emailer.php
        include/ForumManager.php
        include/HTTPExceptions.php
        include/NotificationsManager.php
        include/Photo.php
        include/Smilies.php
        include/attach.php
        include/auth.php
        include/auth_ejabberd.php
        include/bbcode.php
        include/cache.php
        include/cli_startup.php
        include/config.php
        include/contact_selectors.php
        include/contact_widgets.php
        include/create_shadowentry.php
        include/cron.php
        include/cronhooks.php
        include/cronjobs.php
        include/crypto.php
        include/datetime.php
        include/dba_pdo.php
        include/dbclean.php
        include/dbm.php
        include/dbstructure.php
        include/dbupdate.php
        include/delivery.php
        include/dfrn.php
        include/diaspora.php
        include/directory.php
        include/discover_poco.php
        include/email.php
        include/expire.php
        include/fcontact.php
        include/features.php
        include/feed.php
        include/files.php
        include/follow.php
        include/friendica_smarty.php
        include/gprobe.php
        include/group.php
        include/identity.php
        include/like.php
        include/message.php
        include/msgclean.php
        include/nav.php
        include/network.php
        include/notifier.php
        include/oauth.php
        include/oembed.php
        include/onepoll.php
        include/ostatus.php
        include/pgettext.php
        include/photos.php
        include/pidfile.php
        include/plaintext.php
        include/plugin.php
        include/poller.php
        include/post_update.php
        include/probe.php
        include/profile_selectors.php
        include/profile_update.php
        include/pubsubpublish.php
        include/queue.php
        include/queue_fn.php
        include/quoteconvert.php
        include/redir.php
        include/remove_contact.php
        include/salmon.php
        include/session.php
        include/shadowupdate.php
        include/socgraph.php
        include/spool_post.php
        include/system_unavailable.php
        include/tags.php
        include/tagupdate.php
        include/template_processor.php
        include/threads.php
        include/threadupdate.php
        include/uimport.php
        include/update_gcontact.php
        include/user.php
        include/xml.php
        js/
        library/Chart.js-1.0.2/
        library/HTML5/
        library/Smarty/
        library/colorbox/
        library/cropper/
        library/datetimepicker/
        library/dddbl2/
        library/defuse/
        library/facebook.php
        library/fullcalendar/
        library/jgrowl/
        library/jquery-textcomplete/
        library/langdet/
        library/markdown.php
        library/moment/
        library/oauth2-php/
        library/perfect-scrollbar/
        library/php-markdown/
        library/slinky.php
        library/tiptip/
        library/twitteroauth.php
        library/video-js/
        mod/cb.php
        mod/content.php
        mod/login.php
        mod/mood.php
        mod/navigation.php
        mod/oembed.php
        mod/post.php
        mod/qsearch.php
        mod/session.php
        mods/redme.txt
        object/
        src/Core/Cache/AbstractCacheDriver.php
        src/Core/Cache/ArrayCache.php
        src/Core/Cache/CacheDriverFactory.php
        src/Core/Cache/IMemoryCacheDriver.php
        src/Core/Cache/RedisCacheDriver.php
        src/Core/Cache/TraitCompareDelete.php
        src/Core/Cache/TraitCompareSet.php
        src/Core/Lock.php
        src/Core/Lock/
        src/Model/OpenWebAuthToken.php
        src/Module/Magic.php
        src/Module/Owa.php
        src/ParseUrl.php
        src/Util/HTTPHeaders.php
        src/Util/HTTPSignature.php
        src/Worker/SetItemContentID.php
        tests/ApiTest.php
        tests/DatabaseTest.php
        tests/bootstrap.php
        tests/datasets/
        tests/src/
        util/convert_innodb.sql
        util/daemon.php
        util/db_update.php
        view/js/addon-hooks.js
        view/templates/admin_aside.tpl
        view/templates/admin_blocklist.tpl
        view/templates/admin_deleteitem.tpl
        view/templates/admin_federation.tpl
        view/templates/admin_logs.tpl
        view/templates/admin_plugins.tpl
        view/templates/admin_plugins_details.tpl
        view/templates/admin_queue.tpl
        view/templates/admin_settings_features.tpl
        view/templates/admin_settings_head.tpl
        view/templates/admin_site.tpl
        view/templates/admin_summary.tpl
        view/templates/admin_users.tpl
        view/templates/admin_viewlogs.tpl
        view/templates/mood_content.tpl
        view/templates/navigation.tpl
        view/templates/settings-end.tpl
        view/templates/settings-head.tpl
        view/templates/settings.tpl
        view/templates/settings_addons.tpl
        view/templates/settings_connectors.tpl
        view/templates/settings_display.tpl
        view/templates/settings_display_end.tpl
        view/templates/settings_features.tpl
        view/templates/settings_nick_set.tpl
        view/templates/settings_nick_subdir.tpl
        view/templates/settings_oauth.tpl
        view/templates/settings_oauth_edit.tpl
        view/templates/settings_pagetypes.tpl
        view/theme/frio/js/mod_notifications.js
        view/theme/frio/scheme/plusminus.css
        view/theme/frio/scheme/plusminus.jpg
        view/theme/frio/scheme/plusminus.php
        view/theme/frio/templates/admin_aside.tpl
        view/theme/frio/templates/contact_block.tpl
        view/theme/frio/templates/settings.tpl
        view/theme/frio/templates/settings_display.tpl
        view/theme/frio/templates/settings_features.tpl
        view/theme/frio/templates/settings_oauth.tpl
        view/theme/frio/templates/settings_oauth_edit.tpl
        view/theme/frio/templates/suggestions.tpl
        view/theme/frost-mobile/
        view/theme/frost/
        view/theme/quattro/templates/admin_users.tpl

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by tobiasd** [comment]
Have you once had an installation from an archive file in the same directory? All these untracked files are strange and should probably be moved out of the directory.

**Comment by ingoj** [comment]
Yeah, my initial installation years ago was likely to be based on the tarball... later I upgraded always using git...

**Comment by tobiasd** [comment]
Maybe do a backup of your Friendica directory just in case ;-) I tested this and it worked; but just in case... I don't see a custom `home.[html|css]` file in the listing above, but that would be need to be saved to a place outside of the repository e.g..

You can delete the files using git. With a

    git clean -dn

you can see what files and directories will be deleted. The `-n` is for the dry-run, the `-d` for deleting directories and files. If you have to use force, you can add a `-f` to the call.

    git clean -df

This should delete all the unwanted old files from the tar archive.

**Comment by ingoj** [comment]
Hmmm, just created a fresh installation by... 
1) mv friendica friendica.bak
2) git clone https://github.com/friendica/friendica.git
3) cd friendica/
4) cp ../friendica.bak/.htconfig.php .
5) git clone https://github.com/friendica/friendica-addons addon
6) chown -R www-data:www-data ../friendica
7) sudo -u www-data bin/composer.phar install --no-dev
8) restarting php7.0-fpm and apache2 

But still the same broken UI... 
git clean -dn returns without any output, which should imply that there are no files that needs to be deleted.

**Comment by MrPetovan** [comment]
What does `git status` says in the new folder?

**Comment by tobiasd** [comment]
You are now on develop... I suppose accidentally but if the DB update has already started then you should not switch back.

But it's strange that you still have that problem (your `/friendica` page is working now though)

**Comment by tobiasd** [comment]
If the worker should not have started the update process to the DB by now, and you want to go back to the master branch you can `checkout 2018.05`. But I think in the mean time your background job should have picked up the information that there needs to be done some work on the DB.

With the following  MySQL query you can check the progress:

    select count(*) as rest from `item` where icid is null;select count(*) as converted from `item` where not icid is null; select count(*) as content from `item-content`;

it's from #5311 @annando said he was using it to monitor the process.

**Comment by ingoj** [comment]
Well that outputs: 

```
MariaDB [friendica]> select count(*) as rest from `item` where icid is null;select count(*) as converted from `item` where not icid is null; select count(*) as content from `item-content`;
+--------+
| rest   |
+--------+
| 919538 |
+--------+
1 row in set (0.24 sec)

+-----------+
| converted |
+-----------+
|      9878 |
+-----------+
1 row in set (0.01 sec)

+---------+
| content |
+---------+
|    7520 |
+---------+
1 row in set (0.00 sec)

```

I did monitor the upgrade process using mytop instead. Worked as well. ;)
Wasn't there a CLI command to do the DB update as well?

**Comment by tobiasd** [comment]
The "rest" value counts down. mytop has no such counter IIRC And yes, there is a CLI command, but that will only kick the workers, e.g. if the cron did not kick them.

    bin/console dbstructure update

or something like that. But it's not to monitor.

That panel, that should have a `display: none` but has not on your node is generated at line  38 of [src/Content/Nav.php](https://github.com/friendica/friendica/blob/dd00a943f20a8224f934cfb110eb23dacef242a4/src/Content/Nav.php#L38). If there is a `display: none` in your copy of the code, then there is some caching acting strange I think.

**Comment by ingoj** [comment]
Line 38: 

`                $a->page['nav'] .= '<div id="panel" style="display: none;"></div>' ;`

Monitoring the DB update within MySQL is working itself, but it seems that only a few items will be converted by each invocation of bin/console dbstructure update. Running this inside of a while loop will take ages, but otherwise I see no other way to do it. It doesn't seem that those updates are done in chunks of 10.000s as stated in #5311

**Comment by tobiasd** [comment]
The conversion is done in chunks by the background process to not bring down the node by huge LOAD so it will take some time.

In the "Performance" section of the admin panel "Site settings" there is another cache path I've totally forgotten about (sorry for that!). Though I don't really understand why that `display: none` is missing in so many places on your node.

**Comment by ingoj** [comment]
The problem right now is that the system is in maintenace since yesterday evening and making no progress at all according to that information: 

```
System down for maintenance
2018-07-11 21:35:23 UTC: Database update

```

The conversion itself hung since yesterday evening, until I invoked the worker manually: 

```
MariaDB [friendica]> select count(*) as rest from `item` where icid is null;select count(*) as converted from `item` where not icid is null; select count(*) as content from `item-content`;
+--------+
| rest   |
+--------+
| 914305 |
+--------+
1 row in set (0.24 sec)

+-----------+
| converted |
+-----------+
|     11158 |
+-----------+
1 row in set (0.01 sec)

+---------+
| content |
+---------+
|    8580 |
+---------+
1 row in set (0.00 sec)```

Now the numbers are slowly changing, "rest" in not going doing in 10ks, but more like hundreds...

**Comment by tobiasd** [comment]
Yea, there are other DB structure changes involved as well. Guess @annando is interested in the reduction in the overall DB size afterwards.

**Comment by ingoj** [comment]
Somehow the maintenance mode is gone after some invocations of worker... hmmm...

**Comment by ingoj** [comment]
A few minutes later: 

```
+--------+
| rest   |
+--------+
| 911059 |
+--------+
1 row in set (0.25 sec)

+-----------+
| converted |
+-----------+
|     11532 |
+-----------+
1 row in set (0.01 sec)

+---------+
| content |
+---------+
|    8930 |
+---------+
1 row in set (0.00 sec)

```

**Comment by ingoj** [comment]
I'm down to this after about 10 hrs of calling worker in a loop: 

```
+--------+
| rest   |
+--------+
| 908102 |
+--------+
1 row in set (0.24 sec)

+-----------+
| converted |
+-----------+
|     21596 |
+-----------+
1 row in set (0.01 sec)

+---------+
| content |
+---------+
|   18061 |
+---------+
1 row in set (0.00 sec)
```

**Comment by tobiasd** [comment]
Maybe @annando has an idea why that takes so long.

Have you checked the tmp path in the admin settings?

**Comment by ingoj** [comment]
@MrPetovan - git status reports: 

```
friendica# git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean

```

**Comment by ingoj** [comment]
@tobiasd - You mean the /tmp/itemcache? I already did a rm -rf /tmp/itemcache/*, but will do again,because I don't know anymore if it was before and after checking out the develop branch... 

It didn't help deleting itemcache and view/smarty3/compiled/*.

**Comment by annando** [comment]
The conversion speed depends upon the worker interval.

**Comment by ingoj** [comment]
@annando - well, running this script: 

`while true ; do date ; sudo -u www-data /usr/bin/php bin/worker.php ; sleep 10 ; done`

This results in this output: 

```Thu Jul 12 20:00:05 CEST 2018
Thu Jul 12 20:00:19 CEST 2018
Thu Jul 12 20:00:29 CEST 2018
Thu Jul 12 20:00:40 CEST 2018
Thu Jul 12 20:00:53 CEST 2018
Thu Jul 12 20:01:06 CEST 2018
Thu Jul 12 20:01:17 CEST 2018
```

The load on webserver VM is around 0.5-1.5 with 4 vCPUs, and on DB VM it's about 2-4 with 6 CPUs. From my POV the database could take much more load.

**Comment by annando** [comment]
Please use this script:
```select count(*) as rest from `item` where icid is null and iaid is null; select count(*) as converted from `item` where not icid is null or not iaid is null; select count(*) as content from `item-content`; select count(*) as activities from `item-activity`;```

**Comment by ingoj** [comment]
Ok... 

```
MariaDB [friendica]> select count(*) as rest from `item` where icid is null and iaid is null; select count(*) as converted from `item` where not icid is null or not iaid is null; select count(*) as content from `item-content`; select count(*) as activities from `item-activity`;
+--------+
| rest   |
+--------+
| 903305 |
+--------+
1 row in set (0.95 sec)

+-----------+
| converted |
+-----------+
|     28174 |
+-----------+
1 row in set (0.10 sec)

+---------+
| content |
+---------+
|   20058 |
+---------+
1 row in set (0.01 sec)

+------------+
| activities |
+------------+
|       3027 |
+------------+
1 row in set (0.00 sec)```

**Comment by annando** [comment]
How much worker have you activated?

**Comment by ingoj** [comment]
max load avg: 50
min mem: 0
max num parallel worker: 10
enable fastlane: true

**Comment by tobiasd** [comment]
Have you activated any server-side addons that remove the `display: none` bit from HTML elements? ;-) I suppose not, but somewhere between the source code and the display in the browser this attribute is vanishing, reproducible, for different people looking at the pages using different browser. So it should be done on the server.

**Comment by ingoj** [comment]
Just had Apache itself doing some caching, but deactivated this for now. Same for the proxy setting of friendica, although this shouldn't affect the generated content, but only the connections that friendica opens to other sites. 

Still broken theme. The panel in upper left corner is moving out of window when scrolling down, if that helps.

**Comment by ingoj** [comment]
@tobiasd - I've now deactivate several addons and only have these active: 

    altpager
    twitter
    defaultfeatures
    wppost
    leistungsschutzrecht
    diaspora
    remote_permissions
    newmemberwidget
    retriever
    buglink
    forumdirectory
    langfilter
    superblock
    blockem
    nsfw
    statusnet

**Comment by tobiasd** [comment]
I don't think any of these *should* interject with the `display: none`

**Comment by ingoj** [comment]
Big question then: what is then causing the issues on my node? :-)

**Comment by tobiasd** [comment]
Jupp.

BTW the `retriver` addon was deprecated and should not be in the addons repository anymore. I wonder why you have it still in the list.

**Comment by ingoj** [comment]
Yeah, retriever addon is listed, but when I click on that click, nothing is shown. I've not deleted this in mysql from the addon table. 

Anyway, when running my worker script in a while loop, sometimes this can be seen: 

```
Fri Jul 13 13:48:39 CEST 2018
Fri Jul 13 13:48:49 CEST 2018
PHP Notice:  Undefined index: title in /var/www/net/nerdica.net/friendica/src/Content/Text/BBCode.php on line 565
Fri Jul 13 13:49:00 CEST 2018
Fri Jul 13 13:49:10 CEST 2018

```

**Comment by AlfredSK** [comment]
Also `altpager` and `defaultfeatures` don't exist in the repo anymore.

**Comment by ingoj** [comment]
@AlfredSK - ah, well... altpager already removed from addon table, but it still shows up together with retriever under Active Addons. Is there another place to remove a reference to these addons in the DB?

**Comment by MrPetovan** [comment]
In the `config` table, `cat = "system" AND k = "addon"`.

**Comment by ingoj** [comment]
@MrPetovan - ok, that worked, but problem still persist. I'm running out of ideas what to do next to fix this issue. On one hand I think that it might be related to the slow database conversion, on the other hand that makes no sense as it seems more like a broken CSS or something. 

Maybe an option would be to have a TeamViewer session or such...

**Comment by MrPetovan** [comment]
I finally took a look at https://nerdica.net/profile/ij.

Here's the Console log for this page:

```
ij:5 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-KHM/X9LYqS3cynnesMX8U0OCXLOYoe6M8+uS6wwyLMg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:28 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-6VVOq3q0/KIbLquKzAA0vvPrzdaLYQmrOu3Wbm2CgLQ='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:55 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-eaaWRWOur+RWn8NU//KBWlYT6rpKh7hXCDiFCZhIvxI='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:153 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-BrwazGiuO0D1A++r1rWGZXQ7vEZUo/F09X+J3JZJlkY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:193 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-HXh/LF/eHhmV18fBCGdV1Z8nFEZRNlJcSr163d+lWr4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

[132] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:209 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:252 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:291 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:311 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:384 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-jazoCSM3JojjyxgM/LXtJjDRQJS4MX0GKGPrMA3zsJ4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:879 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-RckZBXgv1Pbd5KXKYleo1m4g59i5d4FCaWsqqOJiwXE='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

[24] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-HSAk0l/m7twE9WmoJs4CT1Q3MWTi9VX1salEKauS9Zs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

[11] Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:1900 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-FmN9CGyzky6bFcS4u6PPiBcAF0vrdm90O1iFkADP190='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:2556 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-t9JOBcIMzIJwyL1j8EyaAmIgrpGC3ypteqYsxVbKSvA='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:1 Refused to load the image 'https://media.tenor.com/images/0d64c266779627bb1adf763aa0095fd1/raw' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

ij:3214 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-F4NsFiSlQZtB00LV0YdtP7df25arCUwWtljlKgCxOdE='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

main.js:374 Uncaught ReferenceError: localUser is not defined
    at NavUpdate (main.js:374)
    at HTMLDocument.<anonymous> (main.js:305)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
```

Clearly there's something wrong with the Content Security Policy as it prevents inline style and inline scripts from being used. Not sure where it is set or what to change it to.

**Comment by ingoj** [comment]
Ha! Thanks for that pointer!

In Apache config there was this setting: 

`Header set Content-Security-Policy "default-src 'self';"`

Commenting this out and everything is working again... what a mess!

Now I think I need to find out the proper settings for CSP... hmmm...

**Comment by MrPetovan** [comment]
Yeah, the screenshot in the original post threw me off, I thought it was a private install or something. Eventually, I had to type your URL manually and find out about the CSP.

**Comment by AlfredSK** [comment]
I have a basic CSP enforced via Apache virtual host that is working w/o any issues. I tried a lot of different settings and did a lot of tests. You need some unsafe-inline and unsafe-eval settings. Let me have a look and I will post it here...

**Comment by ingoj** [comment]
@AlfredSK - that'd be great! Very much appreciated! 

Only issue open is now the very slow database migration: 
```
+--------+
| rest   |
+--------+
| 891818 |
+--------+

```

**Comment by AlfredSK** [comment]
````
<IfModule mod_env.c>
# Add security and privacy related headers
Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
SetEnv modHeadersAvailable true
</IfModule>
````

I don't know if the code has been cleaned lately. Maybe some unsafe-inline isn't necessary anymore. But the above basic policy definitely works.

**Comment by ingoj** [comment]
@AlfredSK - Thanks! This seems to work so far... at least no garbled output anymore :)

**Comment by tobiasd** [comment]
is the DB update problem solved @ingoj ?

**Comment by ingoj** [comment]
No. But I could create a new issue for this or we can talk about this in the Friendica Admin forum.

**Comment by tobiasd** [comment]
Yes, we can. I'll still reopen the issue. It should be closed, once the issues are solved.

**Comment by MrPetovan** [comment]
There are two different issues though, I believe the main issue was about garbled display, and it was caused by too strict CSP.

**Comment by MrPetovan** [comment]
I agree with the above comment.

**Comment by ingoj** [comment]
I've now created #5382 for the database conversion part. This issue can be closed now, I think.
