### ISSUE TITLE
redis: Delivery issues with redis enabled

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5355]
### Expected behavior
Enable redis in .htconfig and post something. The post should be delivered.

### Actual behavior
Delivery fails silently. No post arrives anywhere.

### Steps to reproduce the problem
Enable redis in .htconfig.php and try to share something. 

My redis config:
````
$a->config['system']['cache_driver'] = 'redis';
$a->config['system']['redis_host'] = '/var/run/redis/redis.sock';
$a->config['system']['redis_port'] = 0;
````
Connection to redis is established via UNIX socket. That worked before.
I did not try to connect via TCP/IP because I use redis for Nextcloud too and I don't want to break this. :-)

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 MariaDB

**Comment by Quix0r** [comment]
I'm testing this now here. Currently I have an exception of an absent class `Redis`.

**Comment by Quix0r** [comment]
This is because of name spaces. I have now rewritten it a bit.

**Comment by nupplaphil** [comment]
@quix0r you've to install php-redis or something similar to get the `Redis` class in PHP

**Comment by Quix0r** [comment]
Already installed! I had to add the name space `\` to it. PR will be ready.

**Comment by Quix0r** [comment]
And same with other cache drivers as Friendica has now own name spaces.

**Comment by nupplaphil** [comment]
With the latest develop pull, the Message queue dropped from 4.500 to 0. What about you @alfredsk ? 

Thanks @quix0r for the fix! :)

**Comment by AlfredSK** [comment]
I have not re-enabled redis yet. I'll try today and report. Should be easy to test because posts to Mastodon didn't work before this PR. Stay tuned...

**Comment by AlfredSK** [comment]
Okay. Looks like it is working. I sent some posts to forums and some public postings as well. Delivery seems to work.
Closing...

**Comment by Quix0r** [comment]
@AlfredSK sorry for the noise. :-)
