### ISSUE TITLE
"Database in use" install screen doesn't allow any further action

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5368]
### Expected behavior

If the credentials used during the Friendica installer wizard point to a database already containing Friendica tables, a "Database in use" page shows up with a link to go back to the database credentials form or an option to overwrite the existing tables.

### Actual behavior

There's only the error message "Database in use".

### Steps to reproduce the problem

1. Install Friendica normally.
2. Delete `config/local.ini.php`.
3. Run the installer again with the same database credentials

### Friendica version you encountered the problem

2018.08-dev

### Friendica source (git, zip)

git

### PHP version

7.2

### SQL version

MariaDB 10.13

**Comment by JonnyTischbein** [comment]
What do you think of this solution ? I know its a bit hard to read. But it this the same procedure as `Could not create table.` and `Could not connect to database.`.

       /mod/install.php - Line 125-136
	if (DBA::$connected) {
		$r = q("SELECT COUNT(*) as `total` FROM `user`");
		if (DBA::isResult($r) && $r[0]['total']) {
			$tpl = get_markup_template('install.tpl');
			return replace_macros($tpl, [
				'$title' => $install_title,
				'$pass' => '',
				'$status' => L10n::t('Database already in use.'),
				'$text' => '',
			]);
		}
	}

Change to

	if (DBA::$connected) {
		$r = q("SELECT COUNT(*) as `total` FROM `user`");
		if (DBA::isResult($r) && $r[0]['total']) {
			$install_wizard_pass = 2;
			$wizard_status = L10n::t('Database already in use.');
		}
	}

Result:

![screenshot](https://owncloud.riotcat.org/index.php/apps/files_sharing/ajax/publicpreview.php?x=1366&y=293&a=true&file=Screenshot_2018-10-03_21-23-58.png&t=iDpbQGio47zFGxM&scalingup=0)

*Offtopic:*
What I don't get is why the php path from the first step is deleted in the database step:

	case 2: { // Database config

			$dbhost    = notags(trim(defaults($_POST, 'dbhost'   , 'localhost')));
			$dbuser    = notags(trim(defaults($_POST, 'dbuser'   , ''         )));
			$dbpass    = notags(trim(defaults($_POST, 'dbpass'   , ''         )));
			$dbdata    = notags(trim(defaults($_POST, 'dbdata'   , ''         )));

			$phpath    = notags(trim(defaults($_POST, 'phpath'   , ''         )));

			$adminmail = notags(trim(defaults($_POST, 'adminmail', ''         )));

**Comment by MrPetovan** [comment]
It would be perfect, thanks for looking into this!

**Comment by MrPetovan** [comment]
Closed via #5819
