### ISSUE TITLE
"Login failed" error with correct credentials

### ISSUE THREAD

**Issue by volkomorov** [friendica/friendica#5377]
Hi, cannot login to my friendica self-hosted with correct credentials (login & password). Requesting of password by email doesn`t work. 

### Expected behavior

Successful login at login page

### Actual behavior

"Login failed" error with correct credentials

### Friendica version you encountered the problem

2018.05

### PHP version

PHP 7.1.17-1+ubuntu16.04.1

### SQL version

5.7.22-0ubuntu0.16.04.1 

Please, help to fix and give advices, how and where to find the cause of problem :)

**Comment by MrPetovan** [comment]
Hi @volkomorov and thanks for your interest in Friendica! Do you have a problem login in with your first user credentials?

**Comment by volkomorov** [comment]
thanks a lot for you for Friendica profect! Yes, my friendica is just for me, it`s available at friends.volkomorov.ru, so one user is admin

**Comment by MrPetovan** [comment]
The simplest thing you can do is start the install over again. Drop all the tables in your database, delete you `.htconfig.php` file in the Friendica root directory, and access your domain again. When the new install is done, you will get a chance to register another account.

**Comment by tobiasd** [comment]
If you don't want to reinstall Friendica, you can reset the password by two ways.

1. The Friendica console, that you can reach at the command line of your server from the base directory of your Friendica installation contains a command to reset the password. Running `bin/console newpassword --help` in the Friendica base directory gives you all the options for the tool.
2. If this does not work you can use the old `fpassgen` tool ([you can find a copy here](https://social.diekershoff.de/projects/tobias/fpassgen)) and modify the MySQL table `user`. But the former tool should just work if the installation was successful.

**Comment by volkomorov** [comment]
thank you so much, @MrPetovan @tobiasd ! I try today

**Comment by volkomorov** [comment]
@tobiasd I have changed password by `bin/console newpassword --help` with confimation `Password changed`, but got the same error at login page: "Login failed". I think that is not the password problem, but something related to mysql in general

**Comment by tobiasd** [comment]
Have you used the command with or without the `--help`?

**Comment by volkomorov** [comment]
@tobiasd with --help, then:

`bin/console newpassword <my nickname> [new password]`

**Comment by volkomorov** [comment]
@tobiasd haha, I`m stupid :) I use [password] with brackets, as in --help message :) thanks a lot! You have saved my Friendica!

**Comment by tobiasd** [comment]
Great!
