### ISSUE TITLE
Fatal Memory Error

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5379]
I ran git pull today after a week or two of no other updates.  My site is now unresponsive and logging this repeatedly:

[14-Jul-2018 22:49:06 UTC] PHP Fatal error:  Allowed memory size of 94371840 bytes exhausted (tried to allocate 131072 bytes) in src/Core/System.php on line 70

**Comment by miqrogroove** [comment]
I was able to restore the site with this shell command:

`php -f bin/console.php dbstructure update`

Nevertheless, the pull did break my site and there was no information available about the problem.

**Comment by MrPetovan** [comment]
This happens when there’s an infinite DB logging loop. Please try to update your DB structure manually.

**Comment by miqrogroove** [comment]
So.. whenever anyone updates to the next version their site will crash because of a DB logging loop?

**Comment by miqrogroove** [comment]
See #5295 in that case.
