### ISSUE TITLE
Posts From Deleted Contact in Feed After Pull

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5388]
After performing the git pull over the weekend, I started seeing Friendica Support posts in my Network feed.  I deleted the Friendica Support forum from my personal contacts quite a while ago.  I've also confirmed that forum is not currently in my personal contacts.  Note the hover tooltip for the Network page says "My friends' conversations".

These posts do not appear in the Community feed, which looks like it has not changed.

Something has changed significantly with the feed system, or has gone quite wrong now.  Is this normal?

**Comment by annando** [comment]
When had you updated your system? Today a solution for a problem had been merged that sounds like yours.

**Comment by miqrogroove** [comment]
Possible duplicate of #5262

git show returned commit b5fe1c60a908acbdbeec140e237ff118c845ac6b

Prior to that, I had not updated in 2-3 weeks.

**Comment by annando** [comment]
Okay, your branch is old, please update.

**Comment by miqrogroove** [comment]
Alright I did the git pull and composer.phar again.

The site was in maintenance mode on the first try.

Second try, same feed including 8 posts from Friendica Support.

Any other steps to take?

**Comment by annando** [comment]
So new posts from the support forum arrived? Or do you mean the the old ones still existed? And were these posts from today?

**Comment by miqrogroove** [comment]
I believe these 8 posts are "old ones".  Most recent post says 11 hours ago.

**Comment by miqrogroove** [comment]
To be specific, there have been no new posts to Friendica Support in the past 11 hours.  My site is showing the most recent post at the top.  Would you like to make a new post and find out what happens?

**Comment by miqrogroove** [comment]
Additional symptom of this bug:  The forums list does not appear in the network sidebar, even though it is enabled and forum posts are in the feed.

**Comment by miqrogroove** [comment]
Due to lack of traction here, I'm going to use the "Remove Locally" link on each post and close out this issue.
