### ISSUE TITLE
cronjob for polling worker didn't work anymore

### ISSUE THREAD

**Issue by templis** [friendica/friendica#5389]
### Expected behavior
cronjob:
*/10 * * * * cd /var/www/friendica/; /usr/bin/php bin/worker.php 
should update the timeline

### Actual behavior
Friendica don't update the timeline automatically.
I must go to my friendica instance and renew timeline by clicking on network tab.

### Steps to reproduce the problem
sudo -u www-data /usr/bin/php bin/worker.php
brings:
`PHP Fatal error:  sodium_init() in Unknown on line 0`
for each worker process (on my instance the error comes 4 times)
Also my connected twidere can't pull the update.

### Friendica version you encountered the problem
development (2018.08-dev )

### Friendica source (git, zip)
git

### PHP version
php7.2

### SQL version
5.7.22

**Comment by MrPetovan** [comment]
Hi @templis and thanks for your report. First of all, the worker doesn't play any role in the timeline refresh. It is done by the `mod/ping.php` module and one of the `mod/update_*.php` modules depending on the page you're on.

Now it seems like there an issue with the PHP 7.2 built-in libsodium extension. Are you using the pecl extension "libsodium" by any chance?

Can you please provide an extract of your PHP Info related to sodium?

**Comment by templis** [comment]
Hi MrPetovan,

i use the official ubuntu package from the ubuntu 18.04 repo and php-fpm with nginx:
`libsodium compiled version: 1.0.6`
`libsodium headers version: 1.0.16`
`libsodium library version: 1.0.16`

but if I do a `pecl list-all | grep sodium` I got:
`pecl/libsodium            2.0.11         Wrapper for the Sodium cryptographic library`

So I think the sodium error doesn't have anything to do with the friendica instance.

But why it doesn't automatically update my friendica instance anymore?
Or can I cronjob update my Instance till it works again? E.g. like the workerprocess trigger it by `/usr/bin/php /var/www/friendica/mod/ping.php`

**Comment by MrPetovan** [comment]
If you have PHP 7.2 you don't need the pecl sodium extension, you can safely remove it.

The automatic refresh is done by AJAX requests, not by cronjobs. Check your browser console to see if the `/ping` calls are coming in.

**Comment by templis** [comment]
The issue is gone - so I'll close this.
Sorry for let the Issue so long open.

**Comment by MrPetovan** [comment]
No problem!
