### ISSUE TITLE
Tests should not erase the default database

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#5405]
Hello,

Since https://github.com/friendica/friendica/pull/5295,  if I run `./vendor/bin/phpunit` without any environment variable, it will empty the database configured in `config/local.ini.php` without any warning.

I think we should either:
* Skip tests that require a database (and database cleanup) if no `MYSQL_*` environment variable is explicitely defined.
* Ask the user for a confirmation.

**Comment by MrPetovan** [comment]
Skipping seems more appropriate. Should it happen in `DatabaseTest::getConnection`?

**Comment by Rudloff** [comment]
Yes, I think if we call `markTestSkipped()` in `getConnection()` it will skip the database cleanup as well.

**Comment by MrPetovan** [comment]
Sorry for your production database by the way.

**Comment by Rudloff** [comment]
Don't worry, it was my test database (and I had a backup).
