### ISSUE TITLE
Error 500 in frontend

### ISSUE THREAD

**Issue by annando** [friendica/friendica#5423]
### Expected behavior
The working with the frontend should work flawlessly.

### Actual behavior
Every few times the system gets a time out and responds with an error 500 after several minutes of waiting.

### Steps to reproduce the problem
Work with the system.

### Friendica version you encountered the problem
Current "develop" branch, after the "config" changes. (This hadn't happened before)

### Friendica source (git, zip)
git

### PHP version
7.0.27

### SQL version
MariaDB

I guess that the problem lies within the session handling. I got - for example - this analysis data:
```Database: 0.117/0, Network: 0, Rendering: 0.03, Session: 11.09, I/O: 0.01, Other: 0.12, Total: 11.37```

More than 11 seconds for the session handling doesn't sound good. I guess the timeout happens when the session handling delays even more.

**Comment by MrPetovan** [comment]
Error 500 leave a trace in the log, additionally what is you session driver?

**Comment by MrPetovan** [comment]
Could it be related to this: #5422

**Comment by annando** [comment]
It is only happening some times.

The 500 looks like the Apache timeout when the background process doesn't react in time. So I guess that there isn't a log entry.

I never looked into the session driver thingy and the settings. I don't know what's configured.

**Comment by MrPetovan** [comment]
You can get the current configuration with `bin/console config system session_handler`.
