### ISSUE TITLE
Friendica\Database\mysqli' not found

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5434]
After testing the current develop code from this morning (6a6a805225688b308dee4cf94dd3ef115ded868f) I got a WSoD with the following fatal error.

> PHP Fatal error:  Uncaught Error: Class 'Friendica\Database\mysqli' not found in /.../src/Database/DBA.php:93

### PHP version

7.0

### SQL version

MariaDB 10.1

**Comment by MrPetovan** [comment]
Related to #5410
Caused by to #5418
