### ISSUE TITLE
After git pull friendica is down

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5440]
i did a git pull on friendica developer and addons and now my friendica is gone.

**Comment by hoergen** [comment]
The webbrowser says "The requested URL /network was not found on this server."

**Comment by tobiasd** [comment]
Please have a look if there is a `.htaccess` file or only a `.htacces-dist` file. If it is only the later one, please copy over the dist file

    $> cp .htaccess-dist .htaccess

**Comment by tobiasd** [comment]
If that helps, this was caused by #5428 and is a duplicate of #5432 but should have been solved by #5435

**Comment by hoergen** [comment]
I renamend .htaccess restarted apache and named it back. Now it works again .. dont understand it ... but everything seems to be fine again. I didnt edit any file. Is this the magic token everybody is taking of? ;)

**Comment by MrPetovan** [comment]
No, it was caused by a mistaken commit that renamed `.htaccess` to `htaccess-dist`, which removed all URL rewriting.
