### ISSUE TITLE
PHP errors caused by the worker

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5443]
### Expected behavior
no errors
### Actual behavior
PHP Notice:  getimagesizefromstring(): Read error! in /home/users/zsemberi/www/friendica/src/Object/Image.php on line 789
PHP Notice:  Undefined property: stdClass::$html in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 170
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 171
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 173
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 207
PHP Notice:  Undefined index: body in /home/users/zsemberi/www/friendica/src/Model/Item.php on line 2231
PHP Notice:  Only variables should be passed by reference in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1685
### Steps to reproduce the problem
Log of Cronjob
### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1279
### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
Maria

**Comment by copiis** [comment]
PHP Notice:  Undefined index: api_source in /home/users/zsemberi/www/friendica/addon/dwpost/dwpost.php on line 140
PHP Notice:  Undefined index: api_source in /home/users/zsemberi/www/friendica/addon/ijpost/ijpost.php on line 139
PHP Notice:  Undefined index: api_source in /home/users/zsemberi/www/friendica/addon/ljpost/ljpost.php on line 134
PHP Notice:  Undefined index: description in /home/users/zsemberi/www/friendica/addon/tumblr/tumblr.php on line 417

**Comment by copiis** [comment]
PHP Notice:  Undefined index: nurl in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1658

**Comment by copiis** [comment]
Meld.de is back online but this error keeps coming

sh: 1: phpbin/worker.php: not found

**Comment by MrPetovan** [comment]
Still is #5467
