### ISSUE TITLE
Calender Post to Diaspora wrongly formated

### ISSUE THREAD

**Issue by PolynomialDivision** [friendica/friendica#5445]
### Expected behavior
If you insert a picture into a calender entry and this post is getting send to a diaspora server, the server should display the entry correctly.

### Actual behavior
Some html stuff is not parsed correctly... There are html tags in the post. Images are not displayed.

### Steps to reproduce the problem
Make a calender entry or go here: https://pod.geraspora.de/posts/8366630
Origin Post: https://friendica.astatu.berlin/display/96794102465b546178658bd119590102

### Friendica version you encountered the problem
2018.05

### Friendica source (git, zip)
git

### PHP version
I don't know.

### SQL version
I don't know.

**Comment by MrPetovan** [comment]
This looks like a duplicate of #4115, can you please confirm by checking over there if the display issues are the same in the provided examples?

**Comment by PolynomialDivision** [comment]
Display issues are the same.
Will close this issue.
