### ISSUE TITLE
Fatal error in Protocol/OStatus

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5464]
### Expected behavior

OStatus messaging should work without errors.

### Actual behavior

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Protocol\OStatus::constructObjecttype() must be of the type array, boolean given, called in /src/Protocol/OStatus.php on line 1707 and defined in /src/Protocol/OStatus.php:1505

### Friendica version you encountered the problem

2018.08-dev a27ef8d0c9c835724ad7682c920f396420c3681b

### PHP version

7.0

**Comment by MrPetovan** [comment]
There's another one as well:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Protocol\OStatus::import() must be of the type array, null given, called in mod/salmon.php on line 186 and defined in src/Protocol/OStatus.php:291
Stack trace:
#0 mod/salmon.php(186): Friendica\Protocol\OStatus::import('<?xml version="...', Array, NULL, '')
#1 index.php(364): salmon_post(Object(Friendica\App))
```
