### ISSUE TITLE
Worker is gone

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5467]
### Expected behavior
no errors
### Actual behavior
sh: 1: phpbin/worker.php: not found
HTTP ERROR 500
### Steps to reproduce the problem
last git pull
### Friendica version you encountered the problem
latest dev
### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
Maria

**Comment by MrPetovan** [comment]
Looks like a space is missing between the PHP path and the script to execute...

**Comment by copiis** [comment]
My cronjob look like this
cd /home/users/zsemberi/www/friendica; /usr/bin/php bin/worker.php
The error message is that wath the cron sends to me

**Comment by MrPetovan** [comment]
You can pull again.

**Comment by copiis** [comment]
👍 problem solved

**Comment by MrPetovan** [comment]
Apparently not: https://github.com/friendica/friendica/issues/5443#issuecomment-407093663

**Comment by MrPetovan** [comment]
Are you sure you are on the latest develop?

**Comment by MrPetovan** [comment]
Are you using the daemon? It may need to be restarted.

**Comment by Quix0r** [comment]
The bug is still there. Using latest changes.

**Comment by Quix0r** [comment]
This made the worker actually run again: `screen -dmS worker ./bin/worker.php --cron` But it should be considered as workaround and not fix.

**Comment by nupplaphil** [comment]
I'm sorry, it seem's that I switched the `--cron` flag. Before my change, you had to set `no_cron` to disable the cron mechanism. Now you have to set `--cron` to enable it.

I'm currently busy at work so please somebody else change `--cron` to `--nocron` in `bin/worker.php` and `src/Core/Worker.php` as well.

**Comment by annando** [comment]
That's the reason why the daemon still does the job, but not the worker when it is started from the crontab, I guess.

**Comment by AlfredSK** [comment]
The workerqueue is down to zero and the warning is gone. So yeah, I think it is fixed. :tada:  I'll check the logs later.
