### ISSUE TITLE
[curweather] Update Layout of Widget (and Fix Whitespace)

### ISSUE THREAD

**Issue by astifter** [friendica/friendica#5473]
Weather items are broken up in suboptimal places. Unrelated links are right next to each other.
 
![screenshot_2018-07-23 friendica social network network 1](https://user-images.githubusercontent.com/206846/43101399-9c61dfea-8ec8-11e8-8632-3ef28e28374a.png)
![screenshot_2018-07-23 friendica social network network](https://user-images.githubusercontent.com/206846/43101402-9ce731ae-8ec8-11e8-8606-5c2c99ce1455.png)

Also, as mentioned in [friendica-addon#653](https://github.com/friendica/friendica-addons/pull/653) also fix whitespaces. 

Fix to be coming soon.

**Comment by astifter** [comment]
Fixed in (friendica-addon#662)[https://github.com/friendica/friendica-addons/pull/662]:

Vier:
![screenshot_2018-07-23 friendica social network network 2](https://user-images.githubusercontent.com/206846/43102357-33355a8a-8ecb-11e8-97ee-f727320cb2d9.png)

Frio:
![screenshot_2018-07-23 friendica social network network 3](https://user-images.githubusercontent.com/206846/43102356-33160bda-8ecb-11e8-9cf2-449963f7e2ea.png)

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/662
