### ISSUE TITLE
[frio] In edit profile page, there are two different but equal upload options.

### ISSUE THREAD

**Issue by astifter** [friendica/friendica#5474]
![screenshot_2018-07-23 friendica social network profiles](https://user-images.githubusercontent.com/206846/43103159-8bbd6bfa-8ecd-11e8-9e58-2fe12bfc9a6a.png)

Both upload links open up different upload options. And there is no link to open  the page to view all profiles.

(Fix is on its way...)

**Comment by MrPetovan** [comment]
@rabuzarus said it was a WIP feature.

**Comment by MrPetovan** [comment]
Oh, I agree with you, I wasn't sure you already knew.
