### ISSUE TITLE
[bug] typo check script "thinks" script is invalid but throws own error (escaped whole command string?)

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#5488]
Notice: Undefined index: nsfw-submit in /var/www/../addon/nsfw/nsfw.php on line 104
Notice: Undefined index: qcomment-submit in /var/www/../addon/qcomment/qcomment.php on line 67

### Expected behavior

The commit hook runs without errors as there are no fatal/parser errors in scripts.

### Actual behavior

An exception is thrown:
````
sh: 1: -l: not found
PHP RuntimeException:  Parse error found in src/Database/DBStructure.php, scan stopped. in /../src/Core/Console/Typo.php on line 116
PHP Stack trace:
PHP   1. {main}() /../bin/console.php:0
PHP   2. Friendica\Core\Console->execute($callback = *uninitialized*) /../bin/console.php:9
PHP   3. Friendica\Core\Console->doExecute() /../vendor/asika/simple-console/src/Console.php:108
PHP   4. Friendica\Core\Console\Typo->execute($callback = *uninitialized*) /../src/Core/Console.php:102
PHP   5. Friendica\Core\Console\Typo->doExecute() /../vendor/asika/simple-console/src/Console.php:108
PHP   6. Friendica\Core\Console\Typo->checkFile($php_path = '', $file = class SplFileInfo { private $pathName = 'src/Database/DBStructure.php'; private $fileName = 'DBStructure.php' }) /../src/Core/Console/Typo.php:56
[Error] Parse error found in src/Database/DBStructure.php, scan stopped.
````

### Steps to reproduce the problem

Just run `./bin/console typo`.

### Friendica version you encountered the problem

Latest develop.

### Friendica source (git, zip)

git

### PHP version

````
PHP 7.2.4-1+b2 (cli) (built: May 29 2018 02:53:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+b2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
````

### SQL version

*Unrelated*

**Comment by MrPetovan** [comment]
What does `bin/console config config php_path` gives? It seems the php command part is missing from the  `exec()` call in `src/Core/Console/Typo.php`.

**Comment by Quix0r** [comment]
`config.php_path =>` I revert it now back and test.

**Comment by Quix0r** [comment]
All fixed, sorry for the noise. Maybe a nasty `TemperatureOutOfBoundsException` did this to me? ;-)
