### ISSUE TITLE
The administrator should be able to private message anybody on the node

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#5504]
### Expected behavior
The system administrator should be able to send any user a private message.

### Actual behavior
Same access level as anyone else, and if a user blocks private messages from non-friends, then the sysadmin would have to resort to looking up & emailing a user if they had to contact them.

### Steps to reproduce the problem
Try sending a message to any user that has default settings on.

### Friendica version you encountered the problem
2018.05 

### Friendica source (git, zip)
git

### PHP version
7.2.4

### SQL version
mariadb 10.1.29

**Comment by tobiasd** [comment]
Duplicate of the 2nd part from #773 so I'll close this one.

**Comment by MrPetovan** [comment]
More like point 1, still a duplicate though.
