### ISSUE TITLE
Opening a profile link of a 2018-dev profile from a 2018.05 account does not work

### ISSUE THREAD

**Issue by PolynomialDivision** [friendica/friendica#5541]
### Expected behavior
If I click on a profile on a 2018-dev server using a 2018.5 server, the site should appear.

### Actual behavior
Page Not Found.

### Friendica source (git, zip)
git

**Comment by tobiasd** [comment]
Just to clarify, your account is on 2018.08-dev and you click on the profile link of somebody on a node running 2018.05 (or earlier) but you don't get the profile but an Page not found error message?

**Comment by PolynomialDivision** [comment]
The other way around.
Using a 2018.5 server and open a 2018.8-dev profile.

**Comment by annando** [comment]
Does this happen when you are connected or not connected to this profile?

**Comment by tobiasd** [comment]
[Thread in the support forum about this issue](https://forum.friendi.ca/display/96794102105b618956a2165992867690)

**Comment by tobiasd** [comment]
We have to test this in RC with a know 05 + 08rc combination to see if the fix really works.

**Comment by annando** [comment]
I checked from snarl

**Comment by tobiasd** [comment]
And it did not work?

**Comment by annando** [comment]
Before my change I got an error message - after the change it worked.
