### ISSUE TITLE
Adding pictures in private posts don't work (frio)

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5544]
### Expected behavior
When pressing the upload button, the file browser opens and you can select a file and upload it.

### Actual behavior
Pressing the upload button gives no reaction and you can't upload a picture,

### Steps to reproduce the problem
Create a private message.

### Friendica version you encountered the problem
Friendica 2018.08-dev - 1272 / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1

**Comment by MrPetovan** [comment]
Related to #4868
