### ISSUE TITLE
Libravatar addon: remove notice about shutdown of libravatar.org

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#5566]
Hi!

In my Libravatar addon of 2018.08-dev - 1276 there is this notice about Libravatar being shutdown: 

`Please note that the Libravatar service will shut down on 2018-09-01:. You maybe want to switch to the catavatar or gravatar addon.`

But as you can read on the also linked page of https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/ there is another announcement that Libravatar will continue service: https://blog.libravatar.org/posts/Libravatar.org_is_not_going_away/

So, if not already done in newest versions, please remove that warning from the Libravatar addon about the shutdown. 
Thanks!

**Comment by tobiasd** [comment]
The note in the addons README was removed with friendica/friendica-addons#687 hence I'll close the issue.
