### ISSUE TITLE
Gender, Maritial status and sexual preference are saved in generic language

### ISSUE THREAD

**Issue by JeroenED** [friendica/friendica#5596]
### Expected behavior
When saving your gender, maritial status or sexual preference in 1 locale and you change the locale to another one, the data is translated as well

### Actual behavior
When saving your gender, maritial status or sexual preference in 1 locale and you change the locale to another one, the data is blank

### Steps to reproduce the problem
* Save one (or more) of the datas
* Change the locale (eg. german)
* Check the data just set

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
GIT

### PHP version
PHP-7.2

### SQL version
MariaDB-10.2

Assigned to @JeroenED as a contribution for the 2018.11-release so he has something to relax while painting and moving into his apartment.

**Comment by JeroenED** [comment]
Currently thinking about fixing this this way:

### When saving the data into the database
* Translate the value behind of the options into the default 'C' language

### When viewing the data
* Translate the data using the field saved in the database

### Intermediate
* Database update which takes the currently (wrongly) set value and translates this to 'C' within the database (I feel I'll need some assistance with this)

**Comment by annando** [comment]
Concerning this (and other very specialized) fields I think we should reconsider what we store at all. I really would like to reduce it to the (few) fields that are really needed in separate fields like birthday, XMPP address, location and so on.

**Comment by annando** [comment]
When we remove these fields we don't have to take care of this problem ;-)

This is something that we should discuss in the developer forum.

**Comment by MrPetovan** [comment]
> (Nope it isn't)

What do you mean by this?

> Database update which takes the currently (wrongly) set value and translates this to 'C' within the database (I feel I'll need some assistance with this)

The hard part is figuring in which language the value was initially set, especially if the user changed their language afterwards.

1. The simplest solution is to load the strings array of the user's language, `array_search()` the string and replace the value by the key.
2. The most accurate solution is to try for each language if there's a matching value in the strings array and replace by the associated key.

I suggest trying 1. first and fall back to 2. if you can't find the string.

**Comment by JeroenED** [comment]
> What do you mean by this?

I found it pretty weird to see that this was the actual cause of this issue. It should be a very good example of the law of linus. It's even more weird I just noticed it which could have been in the code for years, I believe

(Sorry for grammos, typos and inappropriate language, it's 8u30am ;)

**Comment by MrPetovan** [comment]
It's all good, I wasn't sure what you were referring to.

**Comment by annando** [comment]
This thing here is more complicated than one may think at the start. Some of this data is transmitted via our communication protocols to other servers. When using DFRN for this, we possibly should transmit it in the generic form. But then we have to ensure to do a translation of these values when displaying them.

When transmitting via OStatus or Diaspora (I guess only Diaspora is using the "gender" field), we have to translate it before we transmit it.

And of course all this translation things should be done exclusively in the appropriate Model class.

Sounds like some funny thing to work at ;-)

**Comment by annando** [comment]
And like I said: This will also mean that you have to replace the old ```q(...)``` calls with the ```DBA::``` calls - which also means that after this you are an specialist in this and you can replace all old calls with the new ones :-)

**Comment by AndyHee** [comment]
I observed a closely related issue when changing account types.

If you fill in the marital status or sexual preference fields in a personal account and change that account to a forum account, these values are still displayed in the profile.  However, _modifying_ these values is not possible any more because access to the entry fields is blocked. The control of "Show more profile fields: Yes/ No" is not possible.

The display of this profile information should be suppressed, if the account type is changed accordingly.

**Comment by MrPetovan** [comment]
Please file a separate issue for this.

**Comment by AndyHee** [comment]
OK, will do.
