### ISSUE TITLE
Warnings/Errors since DB Update 1282

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5605]
No Messages

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1475

Update to DB 1282

Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1282

git

7.2.7-0ubuntu0.18.04.2
5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1

**Comment by copiis** [comment]
PHP Notice:  Undefined index: width in /home/users/zsemberi/www/friendica/include/items.php on line 75

**Comment by MrPetovan** [comment]
Related to #5470
