### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5625]
Seen while running composer.phar update today:

- Removing npm-asset/moment (2.20.1)
[InvalidArgumentException]
  Unknown downloader type: npm-signature.

When I ran it a second time, it seemed to update rather than remove npm-asset/moment and then finish without any errors.

**Comment by MrPetovan** [comment]
If you run `composer update`, you'll certainly find yourself at odds with the committed `composer.lock`. However, we also need someone to verify Friendica isn't breaking with new versions of dependencies. If your server runs fine after `composer update`, please consider opening a PR to submit your updated `composer.lock`.

**Comment by miqrogroove** [comment]
Seems like no traction here.  I'm not sure what all that means, but I was told before to run composer after every pull, so that's what I'm doing.
