### ISSUE TITLE
Twitter: Reply tweet creates new top-level post in Friendica

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5643]
### Expected behavior
When I cross-post to Twitter and write a reply on that post on Twitter itself the reply should be displayed as a comment to the original post in Friendica.

### Actual behavior
The reply on Twitter creates a new top-level post in my Friendica network stream with a different GUID. The reply tweet is displayed as a comment on that new post.
I'm not sure. Maybe this behavior is totally normal. But I can't remember that I noticed that before.

### Steps to reproduce the problem
My Twitter connector settings: All options enabled except 'send ... by default'.
I also have configured the name of the Twitter app (`friendica*`) in 'addon.ini.php'.

Original post: https://libranet.de/display/0b6b25a8835b79f0c5b1f03788715337
Tweet with reply: https://twitter.com/alfred_sk/status/1031308939097456640
Re-imported post with reply as comment: https://libranet.de/display/a6551d71275e78de249a4b4bdc0e9aa2fa57ab35

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
git

### PHP version
7.0.30

### SQL version
10.0.34-MariaDB

**Comment by AlfredSK** [comment]
Oops. The last link isn't accessible when I'm not logged in. Made a screenshot...

![bildschirmfoto von 2018-08-20 21-37-19](https://user-images.githubusercontent.com/3656054/44362499-785ffc80-a4c1-11e8-9f98-334a7422f17c.png)

**Comment by annando** [comment]
This is the expected behaviour. We keep the connector network posts separated from the posts in the federated networks.

**Comment by AlfredSK** [comment]
Ok. Thank you for the explanation. And I thought I found a blocker for the release. :-)
Closing...
