### ISSUE TITLE
E-mail notifications for private messages not working

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5651]
### Expected behavior
E-mail notifications for private messages should be delivered if the option is enabled in the settings.

### Actual behavior
E-mail notifications for private messages are not delivered even though the option is enabled in the settings.

### Steps to reproduce the problem
Enable the option. Send a PM. Watch your Inbox. :-)

### Friendica version you encountered the problem
2018.08-dev (pulled just now)

### Friendica source (git, zip)
git

### PHP version
7.0.30

### SQL version
10.0.34-MariaDB

**Comment by annando** [comment]
Had it worked before?

**Comment by tobiasd** [comment]
yes

**Comment by AlfredSK** [comment]
Just for clarification: other notification mails do work.

**Comment by tobiasd** [comment]
Just noticed, that I don't get email notifications about comments either. Only new contact/-requests trigger new mails.

**Comment by AlfredSK** [comment]
E-mail notifications for private messages are working again. :tada: Thanks!
