### ISSUE TITLE
friendica/vendor/autoload.php missing after upgrade

### ISSUE THREAD

**Issue by mexon** [friendica/friendica#5658]
I just upgraded Friendica by switching to the 2018.05 branch.  Now I just get this error when I try to load the front page:

[Fri Aug 24 18:39:16.106459 2018] [:error] [pid 1766] [client 81.135.14.36:50079] PHP Warning:  require_once(/var/www/friendica/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/friendica/boot.php on line 20
[Fri Aug 24 18:39:16.106509 2018] [:error] [pid 1766] [client 81.135.14.36:50079] PHP Fatal error:  require_once(): Failed opening required '/var/www/friendica/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/friendica/boot.php on line 20

Is that file supposed to exist?  If so, why isn't it checked in?

**Comment by mexon** [comment]
Ah fuck, fine, I have to use this composer thing because I hadn't updated for too long and everything's changed because whatever.  Ever considered detecting this and doing something more user-friendly than just displaying a blank page?

**Comment by annando** [comment]
The blank page occurs because there are some PHP errors. I guess it would be complicated, checking for a missing vendor.

**Comment by MrPetovan** [comment]
If you download the stable package, the vendor folder is included, so the file is present. If you use git, then we expect you to have read the documentation about upgrading Friendica with git available here: https://friendica.exon.name/help/Update#1_2
