### ISSUE TITLE
Feature Request: Allow <Ctrl><Enter> to submit messages

### ISSUE THREAD

**Issue by ddeimeke** [friendica/friendica#5673]
It would be great to allow the keyboard shortcut <Ctrl><Enter> for submitting new messages.

**Comment by MrPetovan** [comment]
@vinzv No, this template is specific to the display of a textarea. Since it's Javascript, you want to put it in a `.js` fie. Since it's site-wide and not depending on a specific template, it probably should be in `view/js/main.js`.

Also I'd like us to move away from JQuery because modern Javascript has caught up with it, so if you can find a vanilla Javascript way to do the same, that'd be great.

**Comment by vinzv** [comment]
I like the idea of not relying on jQuery. Found [this one](https://www.catswhocode.com/blog/using-keyboard-shortcuts-in-javascript) and adapted it:

```
var isCtrl = false;
document.onkeyup=function(e) {
    if(e.which == 17) isCtrl=false;
}document.onkeydown=function(e){
    if(e.which == 17) isCtrl=true;
    if(e.which == 13 && isCtrl == true) {
         document.getElementById("myForm").submit(); 
         return false;
    }
}
```

One thing I'm unsure if on MacOS it's common to use Ctrl+ or Cmd+Enter for submitting. The latter would be a bit harder to capture as Cmd is no regular modifier and browser dependend:
- Firefox: 224
- Opera: 17
- WebKit browsers (Safari/Chrome): 91 (Left Command) or 93 (Right Command)

**Comment by MrPetovan** [comment]
Great! Regarding the `document.onkeyup = function (e) {...}` syntax, I'd rather use the `document.addEventListener('keyup', function (e) {...})` to avoid any conflicts between multiple declarations for the same event.

**Comment by carlinhush** [comment]
Has there been any progress with this issue?

**Comment by MrPetovan** [comment]
Not yet, but @vinzv did about half the work already, So this should be quicker to implement for anyone who feel like picking it up.

**Comment by vinzv** [comment]
_(Please bear with my non-existing JS abilities!)_

I got it to work somehow. But trying to adapt it for the regular posting form fails miserably. Maybe someone knowing `view/js/main.js` better could have a look?

<details>
<summary>demo code</summary>

```html
<form id="myform">
<textarea id="msg"></textarea>
<button type="submit">Post</button>
</form>
```

```javascript
<script>
var isCtrl = false;
document.addEventListener('keyup', function (e) {
    if(e.which == 17) isCtrl=false;
})
document.addEventListener('keydown', function (e) {
    if(e.which == 17) isCtrl=true;
    if(e.which == 13 && isCtrl == true) {
         document.getElementById("myform").submit(); 
         return false;
}
})
</script>
```
</details>
<details>
<summary>Javascript</summary>

```javascript
function keyboard_submit() {
	var isCtrl = false;
	document.addEventListener('keyup', function (e) {
		if(e.which == 17) isCtrl=false;
})
	document.addEventListener('keydown', function (e) {
		if(e.which == 17) isCtrl=true;
		if(e.which == 13 && isCtrl == true) {
			document.getElementById("profile-jot-form").submit();
			return false;
}
	})
}
```
</details>

**Comment by foss-** [comment]
What's the status here? On macOS I can send a new post by pressing `cmd+enter`. So what is being requested seems to work as expected.

How are other OSs behaving? is this working for you @ddeimeke ?

**Comment by AlfredSK** [comment]
On linux desktop Ctrl+Return is working.

**Comment by MrPetovan** [comment]
I’m pretty sure it’s working on Windows too.
