### ISSUE TITLE
command line php without register_argc_argv

### ISSUE THREAD

**Issue by uranixcz** [friendica/friendica#5686]
### Expected behavior
Ability to send friend requests a and messages.
### Actual behavior
Can't add, message or follow friend. Both accounts are visible in the directory.
### Steps to reproduce the problem
"Invalid profile URL" message on friend's profile when I submit connection request. Only when using czech language I also see "Verze PHP pro příkazový řádek na Vašem systému nemá povolen "register_argc_argv"." 
When using Add New Contact form I see "The network type couldn't be detected. Contact can't be added." and also only in czech language I see the register_argc_argv message.
I see "No recipient selected." even when I fill in his whole account name in messages.
### Friendica version you encountered the problem
2018.05
### PHP version
$a->config['php_path'] = '/usr/bin/php';
Server API | FPM/FastCGI (same result with CGI)
 php -v
PHP 5.6.36-0+deb8u1 (cli)
 php -i | grep argc
register_argc_argv => On => On
_SERVER["argc"] => 0
 php -i | grep disable_functions
disable_functions => no value => no value
php5-fpm -i | grep argc
register_argc_argv => On => On
_SERVER["argc"] => 0
 php5-fpm -i | grep disable_functions
disable_functions => no value => no value

error log for this website is empty
### SQL version
mysql 5.5.60

**Comment by Aditoo17** [comment]
The register_argc_argv message was wrongly translated. Original is: "Your Identity Address:". I fixed that at Transifex, but it's not in version 2015.05.

**Comment by MrPetovan** [comment]
Can you please provide the two relevant accounts?

**Comment by uranixcz** [comment]
It's https://friendica.sebesdileni.cz/profile/mauser and https://friendica.sebesdileni.cz/profile/mmartinb84

**Comment by MrPetovan** [comment]
Thanks! We'll be testing on our end.

**Comment by MrPetovan** [comment]
Sorry I didn't come around to this, the profiles don't seem to be accessible again.
