### ISSUE TITLE
Post Dates Wrong in Atom Feeds

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5691]
### Expected behavior

When adding/connecting an Atom feed, Friendica should read the post dates.

### Actual behavior

Friendica only seems to read the feed date and then load the entire feed with the same post date.

### Steps to reproduce the problem

Here is a good example feed that I was just looking at https://github.com/fisharebest/webtrees/releases.atom

**Comment by miqrogroove** [comment]
The nature of the bug is that, after the first connection, it may consume posts one-at-a-time, therefore the bug is not noticeable.

**Comment by MrPetovan** [comment]
@miqrogroove Can you pull the latest RC and check again please?

**Comment by annando** [comment]
It looked good during my tests, so I think we really can close it.

**Comment by miqrogroove** [comment]
We might need to re-open this.  I just did a pull on the develop branch.  Then, added a new contact:

https://github.com/friendica/friendica/releases.atom

Under the Status tab for the new contact, every post says "4 months ago" 😢

I will do some more testing and make sure this wasn't a cached result.

**Comment by annando** [comment]
You wrote:
>  I just did a pull on the **develop** branch.

it is fixed on the RC, not the develop.

**Comment by miqrogroove** [comment]
Ah, I didn't realize the RC branch has newer patches than develop.  I will checkout and re-test the new branch.

**Comment by MrPetovan** [comment]
During the release candidate period, we're running both branches in parallel. The RC branch gets all the bugfixes while the develop gets the new features and enhancements that will be released in the next version.

**Comment by miqrogroove** [comment]
Now it works, thanks.
