### ISSUE TITLE
Tests: MemcachedCacheLockDriverTest::testLockTTL randomly fails

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5716]
This is one for @nupplaphil

Running tests, there is this occasional error (like in this build: https://travis-ci.org/friendica/friendica/builds/423713732)

```
There was 1 failure:
1) Friendica\Test\src\Core\Lock\MemcachedCacheLockDriverTest::testLockTTL
Failed asserting that false is true.
/home/travis/build/friendica/friendica/tests/src/Core/Lock/LockTest.php:111
```
It only triggers on a single version of PHP out of the 4, not always the same.

I'm assuming the test is faulty.

**Comment by nupplaphil** [comment]
Mabe I can have a look at it on saturday/Sunday :-)

**Comment by MrPetovan** [comment]
I put it for next milestone, better check the Codecov configuration for the release instead if you can.

**Comment by nupplaphil** [comment]
I'm in conversation with the codecov team, hopefully we will clear the issues this week :)
