### ISSUE TITLE
Wrong permissions to photos in PMs

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5721]
@ben-utzer reported in [the support forum](https://forum.friendi.ca/display/e18176ef215b87ce37defd3777048360) that the permissions of newly uploaded photos in private messages don't get the correct permissions in the current 2018.08-RC code.

Additionally the reader of a PM don't get remote authed when opening the PM so that the image permissions have to be set to *public* manually after the sending of the PM so that the image can be viewed in the PM by the receiver.

Followup to #5544

**Comment by annando** [comment]
This isn't coded at all and it could mean much work to implement it. I would prefer just to hide the functionality to post pictures than to add this whole functionality.

**Comment by tobiasd** [comment]
As the initial problem was fixed with this milestone, I'd rather prefer it _really_ fixed then totally useless as it is at the moment.

**Comment by tobiasd** [comment]
Then we should remove this feature from the UI until it is fixed. At the moment it is totally broken and useless and in this state a blocker.

**Comment by annando** [comment]
I tried to find the Javascript that does invoke the picture browser. I haven't found it. When we want to replace the picture browser with a button that simply adds ```[img][/img]```, then someone else has got to do it.

**Comment by MrPetovan** [comment]
Just remove the button for this release.

**Comment by annando** [comment]
No. Before the change, the button just inserted that ```[img][/img]``` - which I would like to keep. I guess that @rabuzarus can help in finding the call.

**Comment by rabuzarus** [comment]
hmm difficult. Here is the js code for inserting bbcode formations. This code opens also the image browser when the element which should be inserted is the `img` bbtag. (https://github.com/friendica/friendica/blob/develop/view/js/main.js#L80)

**Comment by annando** [comment]
The workaround is ugly - but working.

**Comment by MrPetovan** [comment]
Moving milestone then. There's only the relationship issue to go before we can wrap up this release.

**Comment by annando** [comment]
This is now coded, need some testing.

**Comment by tobiasd** [comment]
Works at least between RC and RC, locally and remote.
