### ISSUE TITLE
JS error: acl is not defined(…)

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#5723]
Since https://github.com/friendica/friendica/pull/56113 I get the following js error for the pages which don't use the ACL

`main.js:308 Uncaught ReferenceError: acl is not defined(…)`

### Friendica version you encountered the problem
2018.08-dev and 2018.08-rc
.

**Comment by MrPetovan** [comment]
Is it preventing any other JS behavior?

**Comment by rabuzarus** [comment]
don't know. At the moment I guess not. So it doesn't seem to be critical and doesn't hurry.
But at some point we should find a solution

**Comment by MrPetovan** [comment]
It was to determine the milestone to assign it to. Thanks for the elaboration.

**Comment by annando** [comment]
I guess it prevents the creation of new shared events in Frio - so it is a blocker for the current version.

**Comment by AlfredSK** [comment]
I just created a shared event (shared with @rabuzarus and @annando) with frio. Yes, I got the error in the browser console too. But the event was created successfully.
