### ISSUE TITLE
DFRN: Changing relationsships doesn't work as expected

### ISSUE THREAD

**Issue by annando** [friendica/friendica#5733]
Following an follower should change the relationship into a bidirectional relationship - unfollowing should turn this into a "follower" state.

This doesn't work at the moment.

**Comment by annando** [comment]
On my system it does work now fine. Does someone wants to test it as well?

**Comment by MrPetovan** [comment]
Paging @rabuzarus

**Comment by rabuzarus** [comment]
Sry, I don't have any time for testing until Sunday.

**Comment by rabuzarus** [comment]
OK first results:
We have a mutual friendship between contact A and B. Contact A wants to change the relationship and unfollows contact B. 

Result: on both contact the relationship is changed correctly (contact B becomes a fan of contact A).

There are now two possibilities.

1.) Contact A can upgrade the relationship again to a mutual friendship. Result: Works correctly.
2.) Contact B (remember B is fan of A) can unfollow contact A. In this case the friendship should be dissolved. Result: **Doesn't work correctly**. On both sides the contacts will be marked as "unknown" but they will be deleted just on one side (I haven't found out which side don't delete the contact - I guess that's random but I'm not sure)

**Comment by annando** [comment]
Have you looked again? Marking as "unknown" is the first step to deleting them. This deletion can take some time.

**Comment by rabuzarus** [comment]
yes. tried it 5x. There is something I don't understand. After the last try I had a look into the queue. In both (A and B) the removal of the contact was listed. When both queues were empty the contact on the one instance was removed the contact on the other instance was still present.

**Comment by MrPetovan** [comment]
More tests are needed after this patch.

**Comment by annando** [comment]
All my tests had been successful - I don't think that we still have to wait longer for the release.
