### ISSUE TITLE
Make additional features core/remove them

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5742]
The Additional Features panel makes the Friendica experience inconsistent between servers. We have to decide, for each one, if we should make it standalone or remove it entirely.

Vote here: https://ethercalc.org/9zi4o5sh2yvg

Voting is free-form, however there are a few predefined words you can choose from:
- Keep: Leave the setting as an additional feature admin can lock and user can disable (when unlocked and enabled).
- Core: Force-enable the feature on all servers.
- Remove: Discard the entire feature from the project.

**Comment by tobiasd** [comment]
I don't think this inconsistency is the issue. It is simply the freedom everybody has when they setup their social network node.

But I think many of the features got hidden for some strange reason (e.g. editing posting being confusing for users) Admins and users are not stupid There are however some features for which I think it is really good for them to be additional (who needs tag clouds in their profile for instance).

**Comment by rabuzarus** [comment]
> who needs tag clouds in their profil

I.
Tagclouds are better than categories.

**Comment by MrPetovan** [comment]
@tobiasd Don’t worry, separating what should be done with each additional feature (including keeping it as is) is the whole point of this issue.

**Comment by MrPetovan** [comment]
After 2 years and 15 votes, this finally will be laid to rest by #8872
