### ISSUE TITLE
Notification page broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5745]
Notifications/system is broken 
I'm on current RC.

https://server.com/notifications/system
is showing error:
replace_macros: Unable to load template 'file:view/theme/frio/templates/'

Sorry for not using the issue template. I'm on work and on mobile...

**Comment by MrPetovan** [comment]
Caused by #5743

Reference: https://github.com/friendica/friendica/pull/5743#issuecomment-419431509

**Comment by tobiasd** [comment]
I think it is still broken.

The page for the contact notifications does not show ignored contact requests anymore, which was the case previously.

**Comment by tobiasd** [comment]
The option is there (at least in with the vier theme) but the content of the page is missing.

**Comment by MrPetovan** [comment]
What is the specific URL that doesn't show anything? I'm unfamiliar with introductions since I'm using a Soapbox.

**Comment by tobiasd** [comment]
> What is the specific URL that doesn't show anything? I'm unfamiliar
> with introductions since I'm using a Soapbox.

It is `notifications/introductions?show=all` (or without the parameter to only show the ones waiting to interaction).

**Comment by MrPetovan** [comment]
My Introductions Notifications display:
![20f34fb1-60f3-4d0b-99cf-6f10ef792e1e](https://user-images.githubusercontent.com/925415/45312765-f2046c80-b4fa-11e8-8dc7-72be6e0cfaea.png)
After tapping on « Show all »:
![ca32be41-5574-4724-aae5-691269323f94](https://user-images.githubusercontent.com/925415/45312788-0183b580-b4fb-11e8-8d4a-6b853d55da01.png)
What is missing on your server?

**Comment by MrPetovan** [comment]
There is no "All" tab and I don't understand what you said afterwards. Are you getting introductions from Diaspora accounts that you ignore because they only do reshares? And you don't see them anymore in the "Show all" link of the "Introductions" tab of the "Notifications" page, right?

**Comment by tobiasd** [comment]
> There is no "All" tab and

There is the link abgove the notifications "Show all" which then calls the URL with the parameter "show=all". Sorry if that is not the name you would use for this, but for me it is "All" contact notification.

> I don't understand what you said
> afterwards. Are you getting introductions from Diaspora accounts that
> you ignore because they only do reshares?

I get sharing notifications or contact request from e.g. people who have not posted anything by now and have an empty profile page. Or only post some shit I don't care about. Especially from diaspora* (as they don't know the not accepting of sharing) I hit the "ignore request" button. Putting them on hold for the moment.

This has the result that (a) their request does not linger anymore in the active notifications, thus the notification counter is lowered and (b) that repeatedly send notification (that are send out by d* just in case the 1st notification did not arrive for some reason) are dropped, as there is already such a notification.

These notification about their contact request stay in the system and are shown on the "All" page for contact notifications.

From time to time I go through the list of ignored request and checkout those I was unsure initially about. Having a look what they are posting now, eventually deciding to start interaction with them now.

> And you don't see them
> anymore in the "Show all" link of the "Introductions" tab of the
> "Notifications" page, right?

No. Partly.

This is not about the "Interactions" section of the notifications. It is about the "Contact requests".

**Comment by MrPetovan** [comment]
> This is not about the "Interactions" section of the notifications. It is about the "Contact requests".

I believe the english translation is "Introductions", see following screenshot:
![introductions-notifications-tab](https://user-images.githubusercontent.com/925415/45357574-a1d9e880-b594-11e8-8461-ff2545fd1633.png)

Anyway, thanks for the elaboration!
