### ISSUE TITLE
PHP warnings on Personal Notes page

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#5752]
PHP Warnings when entering 'Personal Notes' page

`
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/mass-trespass.uk/html/mod/notes.php on line 73

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 511

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 512

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 519

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 520

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 521

Warning: Cannot modify header information - headers already sent by (output started at /var/www/mass-trespass.uk/html/mod/notes.php:73) in /var/www/mass-trespass.uk/html/index.php on line 522`

On 2018.08-rc, database version 1283, post update version 1281.
PHP 7.2-fpm and MariaDB 10.3

**Comment by MrPetovan** [comment]
Related to #5470
