### ISSUE TITLE
Unable to delete a SocialHome post sharing a post mentioning me

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5757]
I started using the multiple deletion feature to cull my timeline (thanks @rebeka-catalina for the pointer) and I noticed yesterday that I couldn't select this post: https://friendica.mrpetovan.com/display/901b9a60973d0136141c047d7b62795e

It's a SocialHome share of a SocialHome post I'm mentioned in, and I'm not following the sharer.

Here's the dropdown menu expanded:

![socialhome-mention](https://user-images.githubusercontent.com/925415/45358057-3d1f8d80-b596-11e8-850a-917d8e05b270.png)

A few things things:
- I'm not sure this post should be in my network timeline even if I'm mentioned.
- I should get a notification when I'm mentioned, this post didn't trigger any.
- I should be able to delete it if it does appear in my network stream, which isn't the case at the moment.

**Comment by MrPetovan** [comment]
Damn, I thought I posted the capture with the dropdown menu. No, the delete option is absent as well.

**Comment by rebeka-catalina** [comment]
On 2018.09.11, Hypolite Petovan wrote:
> I started using the multiple deletion feature to cull my timeline (thanks @rebeka-catalina for the pointer) and I noticed yesterday that I couldn't select this post: https://friendica.mrpetovan.com/display/901b9a60973d0136141c047d7b62795e
> 
> It's a SocialHome share of a SocialHome post I'm mentioned in, and I'm not following the sharer.

Did you receive the posting via a hashtag, that you are following?

**Comment by MrPetovan** [comment]
Ah, yes, I'm following only one hashtag and it's #friendica, which this post mentions. So it isn't about mentioning my handle.

**Comment by MrPetovan** [comment]
Duplicate of #5186
