### ISSUE TITLE
Profile "♥ Status" shows nonsense after editing profile

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5767]
### Expected behavior
When using the simple profile (show more profile fields => off) there is no profile field for "Marital Status". So when I have edited my profile the ♥ Martial Status shouldn't show up under my main avatar and nothing should be stored in that field.

### Actual behavior
The martial status is shown under the main avatar (frio: profile page) and is showing a heart and an "e" as status. When looking at the 'Basic' tab at `.../profile/X/view?tab=profile`I see a 'e never'.

![bildschirmfoto von 2018-09-18 21-03-08](https://user-images.githubusercontent.com/3656054/45710255-620f9400-bb86-11e8-8a5e-3122c67a5310.png)

### Steps to reproduce the problem
Make sure you're using the basic kind of user profile and the martial status isn't set. Edit your profile e.g. by adding a tag and save the profile. Click on 'view profile' and you will see it.

### Friendica version you encountered the problem
2018.08-rc database version 1283 post update version 1281

### Friendica source (git, zip)
git

### PHP version
PHP 7.2.10

### SQL version
mysql  Ver 15.1 Distrib 10.1.34-MariaDB

**Comment by JonnyTischbein** [comment]
Finally I do know the error accurse. In `mod/profiles.php` while parsing args to the template the selection is created via 

    '$marital' => ContactSelector::maritalStatus($r[0]['marital']),

if the profile is deatiled it is displayed, if not a hidden input with

		<input type="hidden" name="marital" id="profile-edit-marital" value="{{$marital.2}}" />

is printed.

Now the generated select starts with

     $a =<select name=\"sexual\" .....

and

    $a[2] = e

**Comment by MrPetovan** [comment]
Nice work, detective!

**Comment by MrPetovan** [comment]
Closed via #5841
