### ISSUE TITLE
Addon Impressum: PHP Warning: A non-numeric value encountered (PL strings)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5768]
PHP Warning:  A non-numeric value encountered in .../addon/impressum/lang/pl/strings.php on line 5

### Friendica version you encountered the problem
2018.08-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
This means there's an occurrence of `L10n::tt()` that doesn't pass an integer value as its third parameter.

Additionally, the first parameter of this particular instance of `L10n::tt()` will be the key of an array in the `view/lang/pl/strings.php` file.

Let the hunt begin!

**Comment by AlfredSK** [comment]
I had a look at a couple of different language versions of strings.php and I only found that line in the PL version. Other language versions have a much simpler line 5.

**Comment by MrPetovan** [comment]
Indeed, but the line itself isn't remarkable, except for the fact that it actually does numeric operations unlike many others. Which means this is the only version that will fail if a non-numeric value is passed. And the place this value is passed is the third parameter of the `L10n::tt()` function when there's a translation string array associated with a specific key like this:
https://github.com/friendica/friendica/blob/68c6895e1a185688eadcae6d86fbab6b8aae861d/view/lang/pl/strings.php#L124-L131

So we have to find the `L10n::tt()` call where the first parameter is the key to a translation string array (in this case, `'Attending'` and where the third parameter may be a non-numeric value.

**Comment by annando** [comment]
We can do this by adding the callstack to some logger output when that value isn't set. I did this before for the translations.

**Comment by AlfredSK** [comment]
Another incarnation of the same issue:
`PHP Warning:  A non-numeric value encountered in .../addon/fromapp/lang/ru/strings.php on line 5`

**Comment by MrPetovan** [comment]
Sounds like the same issue, there a `L10n::tt()` call out there that's misbehaving.

**Comment by annando** [comment]
I created a PR: https://github.com/friendica/friendica/pull/5781

After this had been merge and you see this warning again, please have a look for ```Non numeric count called by``` in the logfile. Then report here.

**Comment by AlfredSK** [comment]
Yes, sir. Here is my report with three slightly different lines from the log:
````
L10n.php:187:tt  Non numeric count called by get_response_button_text, get_responses, Post::getTemplateData, Thread::getTemplateData, conversation, display_content
L10n.php:187:tt  Non numeric count called by get_response_button_text, get_responses, Post::getTemplateData, Thread::getTemplateData, conversation, networkConversation, networkThreadedView, network_content, update_network_content
L10n.php:187:tt  Non numeric count called by get_response_button_text, get_responses, Post::getTemplateData, Post::getTemplateData, Thread::getTemplateData, conversation, networkConversation, networkThreadedView, network_content, update_network_content
````

**Comment by AlfredSK** [comment]
Six more hours w/o an error. Great. Closing...
