### ISSUE TITLE
Can't Save Update Frequency for Atom Feeds

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5778]
### Expected behavior

On an RSS/Atom contact page, I should be able to change the "Update public posts" setting away from "Frequently"

### Actual behavior

I can click on the drop down list, but every time I return to an RSS/Atom contact page, it is now always set to "Frequently", even for contacts I had previously set to other values.

### Friendica version you encountered the problem

2018.08-rc

### Friendica source (git, zip)

git

**Comment by miqrogroove** [comment]
I don't know if this changed recently, but the only way to make this work in the Frio theme is to one of the section arrows later in the page to reveal one of the Submit buttons.  After clicking one of the (hidden) Submit buttons, this will save correctly.

**Comment by MrPetovan** [comment]
It isn’t recent and it is confusing.

**Comment by MrPetovan** [comment]
On the frio theme, we're using an accordion to show the multiple options for a contact, and the submit button that saves the pull frequency is in a difference accordion than the select input control.

**Comment by MrPetovan** [comment]
@JonnyTischbein This looks right up your alley of quick fixes. You just need to add a submit button in the accordion panel of the update frequency for feeds in the frio theme. You can add any RSS feed as a contact to test this.

**Comment by MrPetovan** [comment]
Closed via #5821
