### ISSUE TITLE
Catavatar: New users don't get a cat avatar with registration policy 'approval'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5779]
### Expected behavior
When catavatar is enabled new users should get a cat avatar by default after account creation.

### Actual behavior
This works as expected when register policy is set to 'open'. Every new user gets a cat as avatar by default.
But if register policy is set to 'approval' new users will get a silhouette man avatar instead.

### Steps to reproduce the problem
Set register policy to 'approval'. Log out and register a new user via .../register. Approve the new user in admin panel. Then log in your new user account. No cat!

Also I see these error lines in my PHP error log:
````
PHP Fatal error:  Uncaught Friendica\Network\HTTPException\NotFoundException in .../addon/catavatar/catavatar.php:179
Stack trace:
#0 .../index.php(387): catavatar_content(Object(Friendica\App))
#1 {main}
  thrown in .../addon/catavatar/catavatar.php on line 179
````

### Friendica version you encountered the problem
2018.08-rc
database version 1283
post update version 1281

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34-MariaDB

**Comment by JonnyTischbein** [comment]
If a user is waiting for approval the flag `blocked` is set to true.

    +-------------------+-----+---------+-----------------+-----------------+
    | email             | uid | blocked | account_expired | account_removed |
    +-------------------+-----+---------+-----------------+-----------------+
    | test8@test.test   |   9 |       1 |               0 |               0 |
    +-------------------+-----+---------+-----------------+-----------------+

but the addon requires not blocked user.

        addon/catavatar/catavatar.php
	174 $condition = ['uid' => $uid, 'blocked' => false,
	175		'account_expired' => false, 'account_removed' => false];
	176 $user = DBA::selectFirst('user', ['email'], $condition);

Would it save to remove the blocked condition ?

**Comment by annando** [comment]
I don't see that much of a problem in this little change.

**Comment by MrPetovan** [comment]
If a user isn't approve, will the avatar be correctly deleted?

**Comment by JonnyTischbein** [comment]
Yes it is!
The catavatar picture are availabel by `/catavatar/[user-UID]/[size:4,5,6]`.
If a user signs up and is waiting for approval the picture is available. After deny the request the picture isn't anymore.
I guess it is the case because after deny a request the requested account gets the flags `account_expired` and `account_removed `

**Comment by annando** [comment]
The avatar isn't stored in that addon. There will be an entry in the photo table - and this is connected to the user id. So no problem.

**Comment by MrPetovan** [comment]
Perfect, let's go forward with it then.

**Comment by JonnyTischbein** [comment]
Since the code is in another repository how should I reference the pull request? Or I just don't :D ?

**Comment by MrPetovan** [comment]
You did good, it's up to @AlfredSK to close this up now.

**Comment by AlfredSK** [comment]
Ok.
