### ISSUE TITLE
frio: PRs for custom color schemes?

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5782]
This is a question concerning the custom/pre-installed color schemes of frio.

### _Does it make sense to create a PR for a frio color scheme?_

I'm talking about a color set. Nothing more. Something like that...
````
	$nav_bg = "#111111";
	$link_color = "#222222";
	$background_color = "#333333";
````

**Comment by AlfredSK** [comment]
> in this case we need a process how to decide which schemes should be included

Well, I could decide it. :joy:  Seriously, I understand your point. The reason I opend this issue is that I'm not totally satisfied with the default colors. I would love to be able to provide pre-configured choices (1) for new users or a different default color set for new users (2) on my node.

(1) Of cause I could do that locally only. But that would be unconvenient when updating via git pull.
(2) There's already an issue for that solution -> #4854

**Comment by rabuzarus** [comment]
I'm also unsatisfied with the default color ;-) But what color scheme should be the default one? Would you like to start and guide a discussion on the support forum?

**Comment by poVoq** [comment]
Since we are talking about a bootstrap theme here, why not simply allow the use of one of the many predefined color themes? The most commonly used for various projects is probably https://bootswatch.com/

**Comment by rabuzarus** [comment]
because Frio is already a custom theme and I guess without manual work there would be many glitches.
But it would be really cool if someone could take a good dark bootstrap theme and adjust it for frio.
This is something I want to do since I started with Frio. But I never had the time for it.
