### ISSUE TITLE
Saved Folder

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#5791]
### Expected behavior
A click on a _Saved Folder_ open a stream with the saved posts

### Actual behavior
A click on a _Saved Folder_ result in a PHP error
`[25-Sep-2018 13:48:03 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to conversation() must be of the type array, boolean given, called in /path/to/friendica/mod/network.php on line 342 and defined in /path/to/friendica/include/conversation.php:435`
`Stack trace:`
`#0 /path/to/friendica/mod/network.php(342): conversation(Object(Friendica\App), false, 'network-new', 0, false, '', 1)`
`#1 /path/to/friendica/mod/network.php(466): networkConversation(Object(Friendica\App), false, 'network-new', 0)`
`#2 /path/to/friendica/mod/network.php(380): networkFlatView(Object(Friendica\App), 0)`
`#3 /path/to/friendica/index.php(392): network_content(Object(Friendica\App))`
`#4 {main}`
`thrown in /path/to/friendica/include/conversation.php on line 435`

The error did not appear on every _Saved Folder_. Maybe the problem is, that the folder contain a post from a (forum) account which not exist anymore.

### Steps to reproduce the problem
Open your _Saved Folders_ 

### Friendica version you encountered the problem
2018.12-dev - 1283

### Friendica source (git, zip)
git

### PHP version
7.2.9

### SQL version
5.5.5-10.0.34-MariaDB

**Comment by MrPetovan** [comment]
Thanks for your submission!

**Comment by tobiasd** [comment]
I think saved folders are working fine at the moment. Can we close this issue?

**Comment by annando** [comment]
From my point of view, yes.

**Comment by MrPetovan** [comment]
This part of the code has been completely refactored, I wasn't able to track down the new place the error would have been thrown from.
