### ISSUE TITLE
Minor issue with code blocks from Pleroma

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5801]
Pleroma post: https://pleroma.site/notice/5822579
Friendica post: https://friendica.mrpetovan.com/display/a0914d6ccb70c888ee453a1dc896cce5655b5e5e

The Pleroma post has two paragraphs each with as single inline `<code>`, this gets treated as a single paragraph (=line) with two inline `<code>`.

**Comment by annando** [comment]
Does this change still handles ```[code]```? I'm always nervous when a change only consists of removed code.

**Comment by MrPetovan** [comment]
Yep, it just doesn't remove new lines before/after.
