### ISSUE TITLE
Photos Uploaded to Albums Have No Permissions

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5805]
### Expected behavior

Permitted users & groups should be able to see uploaded photos.

### Actual behavior

When uploading a photo through the Browser tab of the New Post dialog, if any Album has been selected then the photo object will have no permissions at all, even though the Post will have the correct permissions.

This results in a red circle slash image displayed to every user except for the user who uploaded the photo.

### Steps to reproduce the problem

1.  Create an Album by uploading or editing a photo from the profile page.
2.  Go to the network page or the profile status page.
3.  Click "New post"
4.  Click the Browser tab.
5.  Select an Album
6.  Click "Upload"
7.  Enter the message and permissions desired.
8.  Click Share
9.  Go to the photos section of your own profile page again.
10.  Navigate to the newly uploaded photo and inspect the permissions.

### Friendica version you encountered the problem

2018.08-rc and 2018.09

Plugins:  JS Uploader - 1.0 (enabled and disabled, same problem described above)

Theme: Frio

Browser:  Chrome for Windows, Chrome for Android

### Friendica source (git, zip)

git

**Comment by MrPetovan** [comment]
Thanks for the detailed report!

**Comment by MrPetovan** [comment]
Assuming fixed via #6159
