### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved .../src/Module/Object.php on line 16

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5811]
### Actual behavior
On current dev I'm getting a PHP fatal error: `Cannot use 'Object' as class name as it is reserved in .../src/Module/Object.php on line 16`

### Friendica version you encountered the problem
2018.12-dev
commit 406b46b63531bb45d73eda3badc7ba657c1ab8c0

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
15.1 Distrib 10.1.34-MariaDB

**Comment by MrPetovan** [comment]
This has to be solved with a proper router.

It would look like the way we're doing for the API:
```php
App->registerRoute('object', Friendica\Module\Object::class);
```

**Comment by annando** [comment]
Ah, so we mustn't use "Object" as a class name. I could rename it without any problem.

**Comment by MrPetovan** [comment]
Isn't `/object` an expected AP endpoint?

**Comment by annando** [comment]
There are no fixed names. We could name it "smurf" and it would work as well.
