### ISSUE TITLE
VERSION of 2018.09.tar.gz is 2018.08-rc

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5817]
We accidentally released the 2018.09 release with the value "2018.08-rc" in VERSION.

I fear that this isn't changeable anymore, is it? Because I'm currently upgrading the docker images and I'm comparing the VERSIONs to check if a running docker-container has to upgrade :-(

**Comment by nupplaphil** [comment]
The release merge is
https://github.com/friendica/friendica/commit/71ec84f6dc83f753fe80170cfdfd32d202850d90/VERSION

The change is one commit later
https://github.com/friendica/friendica/commit/c48fcd4a8f329946cdf09d214596ecf29e859cff/VERSION

**Comment by MrPetovan** [comment]
It usually isn't recommended to move a tag to a different commit, because it is "rewriting history". However, we aren't using tags to allow people to download Friendica, so I don't think it should be that much of a problem. Not sure if it would update the release on GitHub though.

**Comment by MrPetovan** [comment]
The tag and release have been updated.
