### ISSUE TITLE
Add "Redirect to previous URL" after login

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5818]
### Expected behavior

Clicking on an auth-only page while anonymous redirects to the login page. Once valid credentials have been supplied, the original page should be shown again.

### Actual behavior

The after login redirection is always `/network` no matter the URL that triggered the login. it is especially annoying for using `/bookmarklet` for example (see https://github.com/friendica/friendica/issues/5785#issuecomment-425870296)

### Steps to reproduce the problem

1. Log out of Friendica
2. Go to `/bookmarklet?url=https://friendi.ca&title=Friendica`
3. Log in with valid credentials
4. `/network` page loads

Related to #3897, `/login` should be the only page with a "Return to previous page" feature.

**Comment by JonnyTischbein** [comment]
At this time it is trying to use `$_SESSION['return_url']`

     /src/Module/Login.php - 156-164
		if (x($_SESSION, 'return_url')) {
			$return_url = $_SESSION['return_url'];
			unset($_SESSION['return_url']);
		} else {
			$return_url = '';
		}

		goaway($return_url);
	}

But when logging in it is alway empty. Is it because the SESSION is started after login or because the variable is not set before redirecting to the login mask ?

Would it be save to get the previous URL via `$_SERVER['REQUEST_URI']` as an hiden input field in the login form ?

I also remember the same behaviour when accessing a page like `/contacs` without being logged in and login via the "popup" login form.

**Comment by MrPetovan** [comment]
So we do have such a system in place, it just isn't working. Can you please add some debug on your end to figure out why the session variable isn't populated?

Putting the destination URL in a hidden field in the login form would work as well, albeit it sounds less elegant to me. Still, if you can't make the session variable work for a reason or another, please go forward with your idea.

**Comment by JonnyTischbein** [comment]
I got the error! In `/src/Module/Login.php`

     public static function post()
     {
          session_unset();

Of course does it unset the return_url too. To fix it I did:

     public static function post()
     {
          $return_url = $_SESSION['return_url'];
          session_unset();
          $_SESSION['return_url'] = $return_url;

But the return_url isn't set right in every page.

When calling (logged out) :

| URL | $_SESSION['return_url'] |
|---|---|
| `/bookmarklet?url=abc` |  `/bookmarklet?url=abc` |
| `/contacts` | `https://friendica.x.org` |
| `/profiles` | `https://friendica.x.org` |
| `/message` | `https://friendica.x.org` |
| `/community` | `https://friendica.x.org` |
| `/notifications` | `https://friendica.x.org` |
| `/events` | `https://friendica.x.org` |
| `/network` | `/network` |
| `/admin` | `/admin` |
| ... | ... |

Every page but `/network` and `/admin` stay blank but with header to login, the other two are displaying the login mask.

Now my questions:

- can I fix it in prettier way ?
- should all pages redriect to login ?

Now?
![screenshot](https://owncloud.riotcat.org/index.php/apps/files_sharing/ajax/publicpreview.php?x=1366&y=293&a=true&file=Screenshot_2018-10-05_20-41-24.png&t=bA9NmaFXmoStm4F&scalingup=0)

Most
![screenshot](https://owncloud.riotcat.org/index.php/apps/files_sharing/ajax/publicpreview.php?x=1366&y=293&a=true&file=Screenshot_2018-10-05_20-41-35.png&t=oj46THBi5PWJ38k&scalingup=0)
![screenshot](https://owncloud.riotcat.org/index.php/apps/files_sharing/ajax/publicpreview.php?x=1366&y=293&a=true&file=Screenshot_2018-10-05_20-43-47.png&t=qC8tYDswZ922Dmn&scalingup=0)

**Comment by MrPetovan** [comment]
Closed via #5853
