### ISSUE TITLE
Wrong parameter in Automatic Installation

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5820]
https://github.com/friendica/friendica/blob/0589d9ed2d1fe234d9369eb6d8a906e18d9692ff/src/Core/Console/AutomaticInstallation.php#L111

As I said in https://github.com/friendica/docker/pull/30#issuecomment-427180299 , the parameter must not be `$php_path`, it has to be `$url_path`.

So we need
- a new environment variable for the URL-Path
- fixing the parameter

**Comment by MrPetovan** [comment]
Closed via #5825
