### ISSUE TITLE
Pulled 5 minutes ago, now Friendica is offline

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5832]
Fatal error: Uncaught Error: Call to undefined method Friendica\App::isInstallMode() in /PATHTO/htdocs/index.php:168 Stack trace: #0 {main} thrown in /PATHTO/htdocs/index.php on line 168

### Friendica version you encountered the problem

Develop

**Comment by MrPetovan** [comment]
Closed via #5833
