### ISSUE TITLE
API Notification for all comments when liking a thread

### ISSUE THREAD

**Issue by JonnyTischbein** [friendica/friendica#5849]
### Expected behavior
When I like a thread with an API client I only get notifications for new comments commited after my like.

### Actual behavior
If I like a thread I get notification for the initial thread and all comments so far.

### Steps to reproduce the problem
Use API client (like twidere) and like a thread you not interacted with before.

### Friendica version you encountered the problem
This is Friendica, version 2018.09 that is running at the web location https://friendica.astatu.berlin. The database version is 1283, the post update version is 1281.

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
Replace later

**Comment by MrPetovan** [comment]
Oh, sorry, I misread. It is peculiar indeed.

**Comment by annando** [comment]
Yeah, this is a little bit problematic with the way we currently implemented this part of the api.
