### ISSUE TITLE
admin/federation: Improve pleroma stats display

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5850]
### Expected behavior
The Statistics of Pleroma instances should look as nice as the stats of the other networks. We should get rid of those IDs (commit IDs?) after the main version number.

### Actual behavior
It seems that every instance has its own version ID. These IDs behind the actual version number disrupt the layout (see image).

### Steps to reproduce the problem

![bildschirmfoto von 2018-10-07 14-16-40](https://user-images.githubusercontent.com/3656054/46581677-10e41900-ca3d-11e8-9894-141c8e0e1f4d.png)

### Friendica version you encountered the problem
2018.12-dev
database 1284
post-update 1281

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
mysql Ver 15.1 Distrib 10.1.34-MariaDB

**Comment by tobiasd** [comment]
The title of the issue made me close the browser for an hour :-(

**Comment by tobiasd** [comment]
fixed by #6114

**Comment by tobiasd** [comment]
Reopening this, as they changed something again so the graph looks broken again :-)
