### ISSUE TITLE
Wrong redirect after Login

### ISSUE THREAD

**Issue by JonnyTischbein** [friendica/friendica#5863]
Since  #5853
### Expected behavior
Without being logged after visiting an 404 Page or `/video` and `/photo` **AND / OR** Login via the the Pop-up menu from the header I'm redirected to a valid page.

### Actual behavior
Using the popup login form no matter if page found or not the redirect url is always `https://friendica.domain.org/https://friendica.domain.org/`

### Steps to reproduce the problem
1. logout
2. go to
  - `/some404url`
  - `/video` or `/photo`
  - popup login on any page with a embeeded login mask (see #5853 or table in https://github.com/friendica/friendica/issues/5818#issuecomment-427462884 [before PR])
3. login at popup menu

### Friendica version you encountered the problem
develop

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
mysql  Ver 14.14 Distrib 5.6.36

**Comment by MrPetovan** [comment]
Closed via #5865
