### ISSUE TITLE
Why have the sources of 2018.09 changed ?

### ISSUE THREAD

**Issue by anmol26s** [friendica/friendica#5869]
Have the sources of Friendica 2018.09 changed after the release ?
Yunohost checksum is giving corrupt checksum message while checking the hash.

https://github.com/friendica/friendica/archive/2018.09.zip

**Comment by AlfredSK** [comment]
Maybe that's related to the fact that the release tag was initially misplaced on the wrong commit. That has been corrected later IIRC.

**Comment by anmol26s** [comment]
Ok 
Thanks for the information.
