### ISSUE TITLE
Travis CI still broken

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5870]
I know, you already said it in a PR https://github.com/friendica/friendica/pull/5794#issuecomment-425899114

@MrPetovan and @alfredsk can we add the obsolete TLS version to the git.friendi.ca repo? Because as far as I can see, it's a high risk when reenabling travis in about 1-2 weeks, we maybe have A LOT of todo to fix tests (and of course fixing some bugs behind it ;-) ).

**Comment by tobiasd** [comment]
> add the obsolete TLS version

Should not Travis switch to a more recent version? I think it is bad practice to enable "obsolete" TLS versions.

**Comment by AlfredSK** [comment]
Yep. But this will - probably - never happen. According to Stackexchange the issue exists for more than 5 years now. As far as I understood it Travis-CI ist using a library that insists on a certain (old) main version of GnuTLS.
I'm not sure if allowing TLS 1.1 (at the moment git.frindi.ca only allows TLS 1.2) will solve the issue. But it is worth a try.

Or maybe here are some useful informations:
https://github.com/travis-ci/travis-ci/issues/7131

**Comment by AlfredSK** [comment]
Quote:

> In the meantime, you can try adding the following to your .travis.yml file:
`sudo: required`
This will route your builds on our sudo-enabled Precise infrastructure where the problem doesn't happen.

**Comment by nupplaphil** [comment]
@tobiasd I don't like the idea of adding depracted/obsolete libraries (escepecially in case of encryption) ;-)
@AlfredSK worth a try :)

**Comment by nupplaphil** [comment]
see https://github.com/friendica/friendica/pull/5872#issuecomment-428518638
@AlfredSK maybe we can switch as said. Because the Workaround isn't necessary anymore :-(

**Comment by AlfredSK** [comment]
Okay. I hear you. Thing is I have no control whatsoever over git.friendi.ca.
As far as I know only @tobiasd can set `SSLProtocol all -SSLv3 -TLSv1` for the server.

**Comment by AlfredSK** [comment]
Here are the settings for ciphers and protocols from my Apache 2.4.29 ssl.conf as an example:

````
SSLCipherSuite "EECDH+CHACHA20 EECDH+AESGCM EECDH+AES+SHA384 EECDH+AES+SHA256 EECDH"
SSLHonorCipherOrder on
SSLProtocol all -SSLv3 -TLSv1
````

This still gives an A+ on [ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=gitea.libranet.de&hideResults=on) with TLS1.1 enabled.

**Comment by nupplaphil** [comment]
@tobias I'm sorry to bug you.. Can you enable this TLS setting.. Because I have the fear that there are some broken tests which we have to repair and they become more over time :-/

And we merged a lot of PRs the last two weeks which surely had impact .. And AFAIK there are more to come.

**Comment by tobiasd** [comment]
No I cant. But the person who can said he will have a look if it is possible.

**Comment by MrPetovan** [comment]
I have the same problem with Scrutinizer, I reached out to their team and here's their response:

> thanks for the report. I've created an issue for this. We should be able to include this in the next update (sometime in November). In the meantime, **you could add some custom commands to see if you can upgrade to a newer version before running the composer install command**.

I guess we could do that with Travis as well?

**Comment by nupplaphil** [comment]
Upgrading composer? Or what do we have to upgrade?
I'm for every solution(!) because I'm a little bit sweaty when thinking about the recent PRs and their surely impact on tests ^^

**Comment by MrPetovan** [comment]
Upgrading GNU TLS. It is supposed to have active support for TLS 1.3 from version 3.6.4, current version is 3.6.7 but I don't think this is the version currently used on the Debian boxes at Packagist, Travis and Scrutinizer, probably using he same Docker image.

I'm not sure of the manual command needed to install a newer version of GNU TLS though.

**Comment by MrPetovan** [comment]
Also Scrutinizer (and Travis) installs the latest stable version of Composer every run, so you don't need to do `composer self-update` ever.

**Comment by nupplaphil** [comment]
Uff.. So deepdiving in the configs ^^ ..  I'll make a PR with different options and look what's/if its working ^^

**Comment by MrPetovan** [comment]
The config is pretty straightforward to run arbitrary commands. The real difficulty is figuring out what commands to run on the target environment without having access to it.

**Comment by nupplaphil** [comment]
... I just say dependency hell ;-)
https://travis-ci.org/nupplaphil/friendica/jobs/441864629#L1409

**Comment by MrPetovan** [comment]
Geez, good luck with that, it looks like hell to me.

**Comment by nupplaphil** [comment]
I'm sorry, but I won't continue on this track. It will take hours to compile everything needed I guess. And as said I'm not even sure for how long this would work..
3.6.4 is just planed in ubuntu cosmic (4 releases ahead) ... 

@tobiasd I'd really appreciate that we can add TLS 1.1 :-(

**Comment by nupplaphil** [comment]
Next try: maybe I can use a custom *.deb and manually install it during Travis run ;-) .. Let's have a look ^^

**Comment by nupplaphil** [comment]
Next fail ^^
Found https://packages.ubuntu.com/cosmic/gnutls-bin and directly added it (and did about 7-8 rounds to fulfill the dependencies)

At least bounced back dependencies to `libc` itself which doesn't work on trusty ;-)

**Comment by nupplaphil** [comment]
@tobiasd any updates so far?

**Comment by tobiasd** [comment]
Don't you think I would say so if there were any updates? Funny thing is by nudging me about it you actually lower my motivation to spend any part of my spare time for this problem. So thanks...

**Comment by nupplaphil** [comment]
I'm sorry, it's just that I see a lot of work coming over me to fix all the tests (I'm pretty sure about it) .. 

That's why I have tried my last 2 Weekends to maybe create workarounds to not nudge you and start fixing them instead. I'll let it as is and still wait now, I promise..

**Comment by MrPetovan** [comment]
You're doing fine, @nupplaphil, you did all you could by yourself and asked an expected progress report on a blocking issue for many parts of Friendica development.

**Comment by tobiasd** [comment]
Sorry @nupplaphil about the tone of my reply. I appreciate your work on the issue and your efforts to find a workaround.

But as said above (a) I don't have direct access to the configuration of the server that is run by another volunteer and (b) I think this is more the problem of a professional run businesses to upgrade their product. For me there is a huge difference towards the expectations towards the work of volunteers and professionals and volunteers get much more benefit of doubt then professionals as we volunteers all have a life outside of the project.

**Comment by nupplaphil** [comment]
No worries, I'm just a little bit frustrated that none of the workarounds are working ... 

I'm with you that a professional test-company should at least can handle their TLS-handshakes ;-) . Nevertheless I think they will always deliver to their customers first before to us volunteers. And as they said in the issue, they won't fix it in the near future..

Maybe we can have an alternative to Travis-CI, but that would be a big project/change i guess... I'm currently thinking/reading about https://drone.io or https://scrutinizer-ci.com which enables us to use gitea for it too (afaik it's the future repo of Friendica)

**Comment by nupplaphil** [comment]
I'm afraid, no :-(

https://travis-ci.org/friendica/friendica/jobs/444408276#L549

**Comment by tobiasd** [comment]
ben-utzer is on the way at the moment, but will check out.

**Comment by nupplaphil** [comment]
@ben-utzer 

maybe this works (if you not already did it that way :-) )

https://github.com/friendica/friendica/issues/5870#issuecomment-428612553
> Here are the settings for ciphers and protocols from my Apache 2.4.29 ssl.conf as an example:
> 
> ```
> SSLCipherSuite "EECDH+CHACHA20 EECDH+AESGCM EECDH+AES+SHA384 EECDH+AES+SHA256 EECDH"
> SSLHonorCipherOrder on
> SSLProtocol all -SSLv3 -TLSv1
> ```
> 
> This still gives an A+ on [ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=gitea.libranet.de&hideResults=on) with TLS1.1 enabled.

**Comment by MrPetovan** [comment]
> Maybe we can have an alternative to Travis-CI, but that would be a big project/change i guess... I'm currently thinking/reading about https://drone.io or https://scrutinizer-ci.com which enables us to use gitea for it too (afaik it's the future repo of Friendica)

Funny you should mention that, Scrutinizer has the same GNU TLS issue as Travis and Packagist...

**Comment by ben-utzer** [comment]
I missed that TLSv1.1 also needs old cipher suites. Now it is active.

**Comment by nupplaphil** [comment]
It worked ! :-) Thanks a lot !

https://travis-ci.org/nupplaphil/friendica/builds/444467369
(I don't know if you can see it)

Now the real work starts for me ;-) :-D

**Comment by MrPetovan** [comment]
> (I don't know if you can see it)

Yep, and it miserably failed!
