### ISSUE TITLE
Reshare a post ignores last position

### ISSUE THREAD

**Issue by seraphyn** [friendica/friendica#5871]
### Expected behavior
When I reshare a post, it should only be reshared and I stay at the position in the stream

### Actual behavior
I scrolled through the stream, ~ 50 posts, and than reshare a post. After this it autmagically scrolls to the top and I have to scroll down to the place where I was.

### Steps to reproduce the problem
See Acutal behaviour

### Friendica version you encountered the problem
Version 2018.09

### Friendica source (git, zip)
Upgraded since years :)
### PHP version
PHP 7.0.30-nmm1 (cli) ( NTS )

### SQL version
mysql  Ver 14.14 Distrib 5.6.38, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by AlfredSK** [comment]
I think this is related to this issue: #4599

**Comment by seraphyn** [comment]
@AlfredSK For sure, Sorry,
Close mine please

**Comment by MrPetovan** [comment]
Thanks for your submission!

Duplicate of #4599
