### ISSUE TITLE
PHP Fatal error:  Uncaught Error

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5881]
PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\App::get_hostname() in /home/users/zsemberi/www/friendica/addon/diaspora/diaspora.php:60
Stack trace:
#0 /home/users/zsemberi/www/friendica/src/Core/Addon.php(309): diaspora_queue_hook(Object(Friendica\App), Array)
#1 /home/users/zsemberi/www/friendica/src/Core/Addon.php(286): Friendica\Core\Addon::callSingleHook(Object(Friendica\App), 'queue_predelive...', Array, Array)
#2 /home/users/zsemberi/www/friendica/src/Worker/Queue.php(42): Friendica\Core\Addon::callHooks('queue_predelive...', Array)
#3 [internal function]: Friendica\Worker\Queue::execute()
#4 /home/users/zsemberi/www/friendica/src/Core/Worker.php(348): call_user_func_array('Friendica\\Worke...', Array)
#5 /home/users/zsemberi/www/friendica/src/Core/Worker.php(240): Friendica\Core\Worker::execFunction(Array, 'Queue', Array, true)
#6 /home/users/zsemberi/www/friendica/src/Core/Worker.php(100): Friendica\Core\Worker::execute(Array)
#7 /home/users/zsemberi/www/friendica/bin/worker.php(61): Friendica\Co in /home/users/zsemberi/www/friendica/addon/diaspora/diaspora.php on line 60

**Comment by annando** [comment]
Pinging  @nupplaphil

**Comment by copiis** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\App::get_hostname() in /home/users/zsemberi/www/friendica/addon/diaspora/diaspora.php:290
Stack trace:
#0 /home/users/zsemberi/www/friendica/src/Core/Addon.php(309): diaspora_send(Object(Friendica\App), Array)
#1 /home/users/zsemberi/www/friendica/src/Worker/ForkHook.php(16): Friendica\Core\Addon::callSingleHook(Object(Friendica\App), 'notifier_normal', Array, Array)
#2 [internal function]: Friendica\Worker\ForkHook::execute('notifier_normal', Array, Array)
#3 /home/users/zsemberi/www/friendica/src/Core/Worker.php(348): call_user_func_array('Friendica\\Worke...', Array)
#4 /home/users/zsemberi/www/friendica/src/Core/Worker.php(240): Friendica\Core\Worker::execFunction(Array, 'ForkHook', Array, true)
#5 /home/users/zsemberi/www/friendica/src/Core/Worker.php(100): Friendica\Core\Worker::execute(Array)
#6 /home/users/zsemberi/www/friendica/bin/worker.php(61): Friendica\Core\Worker::processQueue(true)
#7 {main}
  thrown in /home/users/zsemberi/www/friendica/addon/diaspora/diaspora.php on line 290
