### ISSUE TITLE
API field friendica_owner

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#5884]
The field friendica_owner for news items  was filled with the forum account details until 2018-09, if it came via a forum. Now it shows the same data as the user field which is redundant and the information about the forum is lost. Can you change that back?

**Comment by annando** [comment]
Yeah, it's the API. And we do have some issues with repeated posts and surely some more things. We really have to check.

**Comment by MrPetovan** [comment]
Closed by #6898
