### ISSUE TITLE
[mastodoncustomemojis] PHP Warning in JSON after CURL

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5890]
_Originally posted by @annando in https://github.com/friendica/friendica/pull/5888#issuecomment-429104786_

@annando I checked it with a curl'ed https://mastodonten.de/api/v1/custom_emojis and a check afterwards. But here are no failures (the array was working). Do you have an example where it fails?

**Comment by annando** [comment]
No, I don't have more data - but it occurred 33 times so far. Possibly this happens when the returned content is empty or the server hadn't been reachable.

**Comment by MrPetovan** [comment]
Copying the warning for visibility:
 ```
PHP Warning:  Illegal string offset 'static_url' in addon/mastodoncustomemojis/mastodoncustomemojis.php on line 100
```

**Comment by MrPetovan** [comment]
It just is a malformed JSON leading to a type mismatch. Although I'm surprised it didn't choke on `'shortcode'` a line before. We should check for the existence of both keys before accessing them.

**Comment by AlfredSK** [comment]
> Although I'm surprised it didn't choke on `'shortcode'` a line before.

I'll check my log. I remember I had more than one warning about illegal string offsets in mastodoncustomemojis.php.

**Comment by AlfredSK** [comment]
Here it is...
````
PHP Warning:  Illegal string offset 'shortcode' in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 99
PHP Warning:  Illegal string offset 'static_url' in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 100
PHP Warning:  Illegal string offset 'shortcode' in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 100
````
