### ISSUE TITLE
Include previews for embedded links in API

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#5892]
For links to twitter, YouTube, etc. it would be nice to have a parameter in the API which requests a preview/embed for the target URL in the status_html or another field.

**Comment by MrPetovan** [comment]
Reference discussion: https://friendica.mrpetovan.com/display/735a2029-685b-b606-af94-558070172518

Basically, make post preview available in the API.

**Comment by annando** [comment]
It is - more or less - a single function call. But it would be called at any time. So the question is if there are conditions where we shouldn't do it?

**Comment by MrPetovan** [comment]
I don't think so. The only question is if it should be a logged in call or not. Do we use the `local_user()` when rendering a post?

**Comment by annando** [comment]
This function had to be called when the post is created.

**Comment by LubuWest** [comment]
Is there a configuration on a user level for embedding of content? It has privacy relevance, so there should be a switch somewhere.

**Comment by MrPetovan** [comment]
I seem to remember something about OEmbed (no rich OEmbed) but it probably is at the node level, not at the user level.

**Comment by annando** [comment]
We currently adding the link preview thing when receiving posts from Diaspora.
