### ISSUE TITLE
DBA.php errors about missing column in 'item'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5893]
### DBA.php errors about missing column in 'item':

````
2018-10-12T13:13:21Z@n85fjakhe5ngb00vaja6juc1ae [INFO]:DBA.php:631:e    DB Error 1054: Unknown column 'diaspora_signed_text' in 'field list'
DBA::insert, Item::insert, Processor::postItem, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent
INSERT INTO `item` (`parent-uri`, `gravity`, `network`, `private`, `author-id`, `owner-id`, `uri`, `created`, `edited`, `guid`, `diaspora_signed_text`, `uid`, `contact-id`, `uri-id`, `wall`, `extid`, `received`, `changed`, `commented`, `visible`, `deleted`, `post-type`, `allow_cid`, `allow_gid`, `deny_cid`, `deny_gid`, `attach`, `origin`, `resource-id`, `event-id`, `uri-hash`, `thr-parent`, `parent-uri-id`, `thr-parent-id`, `global`, `psid`, `icid`) VALUES ('https://octodon.social/users/cwebber/statuses/100866264755512782', 6, 'apub', 0, 327958, 327958, 'https://pleroma.site/objects/3d501067-f3c5-461a-8237-e18f384b9c1c', '2018-10-12 13:13:19', '2018-10-12 13:13:19', 'a0914d6c063f9ca24a6d67fbafe6c76b8ec6f653', '', 2121, 416844, 2902566, 0, '', '2018-10-12 13:13:21', '2018-10-12 13:13:19', '2018-10-12 13:13:19', 1, 0, 0, '', '', '', '', '', 0, '', 0, '153935002df2bde4c32e4ae93175f3dea954f54f', 'https://pirati.ca/objects/ec054ce7-145b-c09c-40d5-a9a489858575', 2828367, 2902441, '', 119, '2909049')
````
Possibly related to #5889

### Friendica version you encountered the problem
2018.12-dev commit 735a5980bd1da3afc3eaa95edcd80478864a032b
database 1284
postupdate 1281

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
mysql Ver 15.1 Distrib 10.1.34-MariaDB

**Comment by AlfredSK** [comment]
Btw. there is a really bad side effect. There are a lot ot database connections (97 in my case; worker stops because maxConnectionsReached) trying to send data to the item table. I have to kill them.

**Comment by MrPetovan** [comment]
Caused by #5889

**Comment by AlfredSK** [comment]
Hmm. Do you think it was the best move to close this? I guess @annando wants to improve his PR with the missing dbstructure update. Does he get notified that something was wrong with his PR?

**Comment by MrPetovan** [comment]
I follow-up on the faulty PR, he will be notified.

**Comment by AlfredSK** [comment]
Ah! Ok.

**Comment by annando** [comment]
That's weird. We are using this field for years now: https://github.com/friendica/friendica/blob/develop/src/Protocol/Diaspora.php#L1741

It's a virtual field that is deleted during the "insert" process, before any database insert takes places: https://github.com/friendica/friendica/blob/develop/src/Model/Item.php#L1298-L1303

**Comment by annando** [comment]
Okay, I found it ... The field is now sometimes existing - but empty.
