### ISSUE TITLE
Redirect on .../display after editing a comment not working

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5896]
### Expected behavior
After editing a comment in single post view (.../display/...) the user should be redirected to the same "display" page he/she was on. 

### Actual behavior
After editing a comment in single post view (.../display/...) I'm redirected to https://example.com/update_display and that's it - just a white page. The edited version of the comment is saved successfully. If I go back using the browser's 'back' button everything is ok.

### Steps to reproduce the problem
Go to a post you commented on using the single post view like https://example.com/display/123456789... and edit your comment. Click on "Save".

### Friendica version you encountered the problem
2018.12-dev / db:1284 / pu:1281

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
mysql Ver 15.1 Distrib 10.1.34-MariaDB

**Comment by MrPetovan** [comment]
@JonnyTischbein can you look into this?

**Comment by annando** [comment]
Additionally it seem to throw some notices.

**Comment by JonnyTischbein** [comment]
Worked fine even with multiple tabs (but for now I could only test it on android)

**Comment by AlfredSK** [comment]
> Are you using multiple Friendica tabs?

No. Most of the time I don't. I'm home now. Will check soon.
Btw. I never tried this on a mobile device. I had the issue with FF and Chromium on a desktop device.

**Comment by AlfredSK** [comment]
Ok. That's weird. I just edited a comment on a restricted post that I made myself. Then I edited a comment on a public post from someone else. I did it with FF and Chromium. It worked on all the attempts. :thinking: 
Now I'm confused. It will probably happen again as soon as this issue is closed. :-)

**Comment by AlfredSK** [comment]
It happend again. :-) The error message in the little notification bubble was something like 'item not found' (Beitrag nicht gefunden). So, I guess it tries to redirect to a non-existent GUID after saving the edit. But unfortunately, when I opened my browser console and tried to reproduce it - it didn't happen again. :-/

**Comment by JonnyTischbein** [comment]
I'm using the `guid` from table `item` and do

     /include/item.php
     goaway('/display/' . $item['guid']);

is there any case where that the field isn't filled properly ?

**Comment by MrPetovan** [comment]
I don't think it would redirect to `/update_display` though.

**Comment by MrPetovan** [comment]
I just had this issue by doing this:
1. Comment on a post in the `/network` stream.
2. When the post appears after Ajax update, click on the Edit button.
3. After saving, my browser was redirected to `/update_network`.

**Comment by MrPetovan** [comment]
I would expect a similar workflow for `/display`:
Comment on a post in the `/display` stream.
When the post appears after Ajax update, click on the Edit button.
After saving, my browser was redirected to `/update_display`.

**Comment by JonnyTischbein** [comment]
Works the same for `/display`

     PHP Notice:  Undefined index: p in /var/www/friendica/mod/update_display.php on line 15
     PHP Notice:  Undefined index: item_id in /var/www/friendica/mod/display.php on line 209

Here is the value isn't catched if empty

       /var/www/friendica/mod/display.php on line 209
      $item_id = $_REQUEST['item_id'];
      $item = Item::selectFirst(['uid', 'parent', 'parent-uri'], ['id' => $item_id]);

      /var/www/friendica/mod/update_display.php
      $profile_uid = intval($_GET["p"]);

      header("Content-type: text/html");
      echo "<!DOCTYPE html><html><body>\r\n";
      echo "<section>";

      $text = display_content($a, true, $profile_uid);
    

Is AJAX capable of killing GET params ?

**Comment by MrPetovan** [comment]
No, but the Ajax call may be incomplete on the JS side.

**Comment by MrPetovan** [comment]
Thanks for looking into it, I'll take a look tonight myself.

**Comment by AlfredSK** [comment]
I'd like to express my relief that I'm apparently not mad. :-)
Thank you for confirming the issue.

**Comment by MrPetovan** [comment]
The first form is prepared in `comment-item.tpl`, the second form is prepared in `jot.tpl`.

`jot.tpl` is used in:
- `mod/editpost.php:60`: Probably inconsequential since we never hit this module anymore.
- `include/conversation.php:1120`: This is more interesting, the `$return_path` is derived from the `App->query_string`, which in the case of an Ajax update, would be `update_display` or `update_network`.

Maybe just stripping `update_` from the `query_string` would be enough to fix this.

**Comment by JonnyTischbein** [comment]
Thank you very much!

It wasn't `App->query_string` but my second argument `$a->cmd` (basically the same)` in `mod/editpost.php`

     /src/Object/Post.php:161
     $edpost = ["editpost/" . $item['id'] . "/" . base64_encode($a->cmd), L10n::t("Edit")];

Doing the strip in `editpost.php` worked. I could make a commit tomorrow.
The change in `conversation.php` didn't change anything. I guess it is the call for a new post not for editing one ?

**Comment by MrPetovan** [comment]
I'm not sure what you're talking about but any fix is welcome. I looked into this quickly tonight with no tests at all.

**Comment by JonnyTischbein** [comment]
If we add your suggestion from https://github.com/friendica/friendica/issues/3897#issuecomment-427692151 (replace the second argument `return_url` when editing a post with `/display/[guid]`) it would also fix this issue.

But instead I can also add stripping `update_` from the `return_url`.

In my opinion it is more useful to stay on the side you're editing the post. (Until Ajax will replace it :smile: )
But I'm open to it.

**Comment by MrPetovan** [comment]
Closed via #5940
