### ISSUE TITLE
Group timeline?

### ISSUE THREAD

**Issue by roytam1** [friendica/friendica#5900]
Friendica's group function seems a bit hidden(I need to type /groups in url to access group page), I wonder if we can have Group timeline to increase the usage of groups?

**Comment by AlfredSK** [comment]
You don't have to go manually to /groups. Go to your user settings, additional features, network sidebar and enable the group filter. You can select the group on your network page now to see only posts and comments from that group.

**Comment by roytam1** [comment]
OK that works! Thanks!

**Comment by annando** [comment]
You can see all community posts on your system with ```/community/global/community```.
