### ISSUE TITLE
[fromgplus] PHP Notice Undefined property: stdClass::$published

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5908]
PHP Notice:  Undefined property: stdClass::$published in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 529

**Comment by copiis** [comment]
PHP Notice:  Undefined property: stdClass::$attachments in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 498

**Comment by MrPetovan** [comment]
Add coverage for this notice in https://github.com/friendica/friendica-addons/pull/752

**Comment by copiis** [comment]
PHP Notice:  Undefined index: download_content_length in /home/users/zsemberi/www/friendica/src/Util/ParseUrl.php on line 144

**Comment by MrPetovan** [comment]
Please move this comment to #5470.
