### ISSUE TITLE
User account expiry feature

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#5919]
When deleting user accounts that seem abandoned (e.g. last login six month ago), I send the user an email telling them their account will be removed in 30 days. I also inform them how to avoid this.

A month later I delete the account manually, depending whether they have logged on or not as instructed.

It would be nice to automate this process. Instead of deleting accounts immediately, there could be any option of setting when accounts will expire and then actually deleted. Expiration however should be conditional: i.e. the user has not logged on after having been emailed.

Here the sample email, I send out:

Hello
> Your Friendica account at [server name] is scheduled for deletion, as you have not logged in for more than six month.
> 
> To prevent your account being permanently deleted, log in at https://[server] now. You can retrieve your password here: https://[server url]/lostpass
> 
> If you don't take any action, your account will be permanently deleted in 30 days.
> 
> Best regards,
> 
> Administrator
[server name]
[contact email]
[URL to admin on server]

**Comment by tobiasd** [comment]
No, that addon sends out a notification a week before the deletion. @AndyHee wants a email notification automatically when you hit the delete button on a user account in the admin panel.

**Comment by AndyHee** [comment]
I had in mind an account expiry feature that is conditional.

So, if the account is set to expire in one month and the user doesn't log on, the account will automatically deleted. If the user logs on, the expiration will be revoked and nothing happens. This of course would require email notification telling the user to log on.

This new feature is meant to deal with abandoned accounts, giving those users some chance to change their mind.

@annando what's the addon you mentioned?

**Comment by AndyHee** [comment]
This is mostly redundant since the permanent deletion time has been extended considerably.
