### ISSUE TITLE
ActivityPub: deleted post still appears with different author

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5925]
Mastodon post (deleted): https://mastodon.social/@Gargron/100504079836117790

Friendica post: https://friendica.mrpetovan.com/display/aeedddc0b23101364a8100163e3b85e3

Screenshot network page:
![friendica-ap-deleted-post-change-owner-network](https://user-images.githubusercontent.com/925415/46925082-11aa1b80-cff8-11e8-9b7c-44586ba21b54.png)
Link on the title is https://mastodon.social/@Gargron/100504079836117790

Screenshot display page (content is gone!):
![friendica-ap-deleted-post-change-owner](https://user-images.githubusercontent.com/925415/46925051-c09a2780-cff7-11e8-9b69-fe3858d3c647.png)
"Link to source" has disappeared and instead there's a "View in Separate Page" link leading to https://friendica.mrpetovan.com/display/aeedddc0b23101364a8100163e3b85e3

This post even had another different author before I refreshed my network stream.

Source of the GUID:
```xml
<reshare>
  <author>jakob@pod.orkz.net</author>
  <guid>aeedddc0b23101364a8100163e3b85e3</guid>
  <created_at>2018-10-14T22:52:00Z</created_at>
  <root_author>culturekat@pluspora.com</root_author>
  <root_guid>9658fd60af660136474c005056268def</root_guid>
</reshare>
```
Source of the root GUID:
```xml
<status_message>
  <author>culturekat@pluspora.com</author>
  <guid>9658fd60af660136474c005056268def</guid>
  <created_at>2018-10-11T09:33:08Z</created_at>
  <public>true</public>
  <text>#funny #meme </text>
  <photo>
    <guid>8b74c5e0af6601364741005056268def</guid>
    <author>culturekat@pluspora.com</author>
    <public>true</public>
    <created_at>2018-10-11T09:32:50Z</created_at>
    <remote_photo_path>https://pluspora.com/uploads/images/</remote_photo_path>
    <remote_photo_name>653c4790c3988ca4bb75.jpg</remote_photo_name>
    <status_message_guid>9658fd60af660136474c005056268def</status_message_guid>
    <height>723</height>
    <width>597</width>
  </photo>
</status_message>
```
This content doesn't appear in the post.

The `item-content` row with the captured content above still exists, with an empty `uri`.

No PHP error at the time of posting.

**Comment by annando** [comment]
I'm confused about that "Diaspora" in the post.

**Comment by MrPetovan** [comment]
Me too! The previous displayed owner that I didn't capture was a Mastodon reshare, so I wouldn't focus too much on the Diaspora side.

**Comment by annando** [comment]
This really looks like some problem in your item table with the field "icid". Can you check the value of the field for this post? Then have a look in the "item-content" table for that id. And have a check if this "icid" is used in items with a different uri as well.

**Comment by MrPetovan** [comment]
The `icid` points to the "orphan" `item-content` row without a `uri`.

**Comment by MrPetovan** [comment]
I haven't seen this again, it probably was caused by #5787, closing for now.

**Comment by annando** [comment]
We can test this again, when I changed the relation between the content table and the item table. I would like to see to which content this post is then connected to.
