### ISSUE TITLE
Friendica not reachable any more

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5937]
Made a git pull 7-8 hours ago and Friendica is still not reachable any more.
I have a lot apache processes running wild with a lot of CPU consumption and mysql is as well using a lot CPU. The 4 CPUs are completely on 100% since yesterday evening.

Have a lot apache log entries like
`05Z@log:9192:5bc57db0f212c1773 [INFO]:DBA.php:547:p    DB Error 1054: Unknown column 'next_try' in 'where clause'
DBA::count, Worker::totalEntries, Worker::findWorkerProcesses, Worker::workerProcess, Worker::processQueue`

> Error 503 - Service Temporarily Unavailable
> System is currently overloaded. Please try again later.

Help?

### Friendica source (git, zip)
latest developer

**Comment by hoergen** [comment]
Btw .. ever tried http://guthib.com/ ? ;))

**Comment by annando** [comment]
Please execute ```bin/console dbstructure update``` by hand.

**Comment by hoergen** [comment]
Ok that did it. Thank you. It's working again

Got the message

`bin/console dbstructure update

ALTER IGNORE TABLE `contact` ADD `deleted` boolean NOT NULL DEFAULT '0' COMMENT 'Contact has been deleted'; 
CREATE TABLE IF NOT EXISTS `diaspora-interaction` (
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `interaction` mediumtext COMMENT 'The Diaspora interaction',
         PRIMARY KEY(`uri-id`)
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='Signed Diaspora Interaction';
ALTER IGNORE TABLE `workerqueue` DROP INDEX `priority_created`, DROP INDEX `done_executed`, ADD `next_try` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Next retrial date', ADD `retrial` tinyint NOT NULL DEFAULT 0 COMMENT 'Retrial counter', ADD INDEX `priority_created_next_try` (`priority`,`created`,`next_try`), ADD INDEX `done_executed_next_try` (`done`,`executed`,`next_try`); 
`

Should I do something else?

**Comment by hoergen** [comment]
Friendica seems now under heavy load and therefore rare usable, that is not really reflected by the OS (Load 10 / CPU 12%)

**Comment by hoergen** [comment]
Friendica is again not reachable right now. as well mysql is not reachable from another application. Only if I restart mysql I can reach it for some time before it is unreachable again.

**Comment by annando** [comment]
Please update your repository. Possibly the fix that I just had done is solving your problem as well.

Can you have at the access log of your web server? Are you having very much requests to the same page?

**Comment by hoergen** [comment]
I did a git pull some minutes ago, when I saw that the latest pull request are merged. Now mysql is on 160% CPU. Hope this is a good sign?

**Comment by hoergen** [comment]
I couldn't see in apache log a lot requests to the same page ..

**Comment by annando** [comment]
What is "show processlist" saying in the mysql console?

**Comment by hoergen** [comment]
It says 364 rows with a lot 

`Waiting for table metadata lock | SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`guid`, `item`.`author-id`, `item`.`id` A`

**Comment by hoergen** [comment]
Info: mysql cpu consumption rised slowly to 300% and higher with peeks to 400%.

**Comment by hoergen** [comment]
Info 2: the system load is weird low with 7,5 / 6,35 / 5,10

**Comment by hoergen** [comment]
restarted apache and  the mysql CPU consumption was dropping instantly. will continue watching it

**Comment by hoergen** [comment]
When doing now

`bin/console dbstructure update`

it says 
`[Error] Unable to connect to database`

I still have the old .htconfig.php working because the new one didn't work for me yet .. could it be this?

**Comment by hoergen** [comment]
In the friendica log I only have those entries

`2018-10-16T08:37:01Z@log:1616:5bc5a32d047555967 [INFO]:Worker.php:543:maxConnectionsReached     Maximum level (100%) of system connections reached: 400/400`

**Comment by hoergen** [comment]
hmmm have the impression that this is a DDOS .. seeing a lot bots requesting (Yandex / AhrefsBot / Semrush ) ... try to activate fail2ban (im new to this)

**Comment by hoergen** [comment]
Friendica is reachable again (without activating fail2ban)

**Comment by annando** [comment]
When doing "show processlist" you have to have a look at the process with the longest runtime. Most likely this is the blocking one. This "Waiting for table metadata lock" is a clear sign that some (single) process is blocking the whole system.

it would be great to see what query this is.

**Comment by hoergen** [comment]
the process list is nearly emtpy now

**Comment by annando** [comment]
Okay. When it is full again, have a look at rows with "Time" with a high number and not sleeping or waiting.

**Comment by hoergen** [comment]
ok I will. Thank you for your ideas and help. Will close this issue now.

**Comment by MrPetovan** [comment]
Possibly fixed by #5938
