### ISSUE TITLE
[twitter] Received quote-tweets only show quoted tweet

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5955]
Probably caused by https://github.com/friendica/friendica-addons

**Comment by annando** [comment]
I can second this. I guess it is from the missing "preshare" value that had been removed here:
https://github.com/friendica/friendica/pull/5942/files#diff-dbbffc32752b4d95e98eec53ad7d7f77L959

**Comment by MrPetovan** [comment]
Yep, it should be prepended to the `$callback(...)` calls line 909.

**Comment by annando** [comment]
I think it is a little bit more complicated. Depending upon the different out types we added ```<br>``` or ```<hr>``` between the quoted text - or did other things. We should keep that behaviour.

**Comment by MrPetovan** [comment]
It's actually restoring this behavior that led to this omission in the first place.

**Comment by annando** [comment]
It still doesn't work here.

**Comment by MrPetovan** [comment]
Now I don't get it. I'll do more tests tonight I guess.

**Comment by MrPetovan** [comment]
I don't understand, it looks fixed fixed on my server after update. I'm correctly receiving Twitter quote-tweets again.

**Comment by annando** [comment]
I had several empty ones here - but also some working ones. I will watch it here over the day.

**Comment by MrPetovan** [comment]
The last instance of an empty quote-tweet I got was more than 6 hours ago (17:15 EST), every single quote-tweet after that point displays correctly.

**Comment by annando** [comment]
It looked fine here now too.
