### ISSUE TITLE
Missing hostname in link URL in Diaspora post body

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5956]
Diaspora post: https://pod.orkz.net/posts/dd57f670b51101364a8300163e3b85e3
Friendica post: https://friendica.mrpetovan.com/display/dd57f670b51101364a8300163e3b85e3

Will extract the source when at home. I might create a dedicated admin page for that purpose since I need it often when I can't access my remote host.

**Comment by annando** [comment]
This is some "magic" link that is used by Diaspora. This is by intention without the hostname.

**Comment by MrPetovan** [comment]
The problem is twofold. Either Friendica should support Diaspora magic links and it currently doesn't, or it shouldn't support Diaspora magic link and it should just prepend the original pod hostname.

The current situation where the protocol is slapped on a relative URL is unsatisfactory in either case.

**Comment by annando** [comment]
Previously we supported this. I guess it got lost due to some changes with the baseurl stuff.
