### ISSUE TITLE
Registration mail broken because no password included

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5960]
### Expected behavior
There should be a password included in the registration mail. (Yes, that's bad practice but that's another issue) :-)

### Actual behavior
Password is missing. Username is located at the place where the password should be.
And other issues (see below).

`Die Anmelde-Details sind die folgenden:`
`Adresse der Seite: Mordor Social` <-- shouldn't that be a URL?
`Benutzernamename:`  <-- that's complete nonsense
`Passwort: Meister Lampe`  <-- No. That's the user name

The password reset mail works and contains a password.

### Steps to reproduce the problem
Register a new user on your node and look into the registration mail.

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Yup, you're right.
