### ISSUE TITLE
Image not selectable when filename is too long

### ISSUE THREAD

**Issue by dubst3pp4** [friendica/friendica#5968]
### Expected behavior
When I create a post and upload an image, clicking on the images thubnail inserts the bbcode for the image.

### Actual behavior
When I click on the thumbnail, nothing happens, because the filename overlaps the clickable area.

### Steps to reproduce the problem
Upload an image with a long filename (for me something like "Bildschirmfoto von 2018-10-19 09-17-45.png" caused the problem). It seems that this happens when you have less than 4 pictures in the image browser.

### Friendica version you encountered the problem
2018.09

See screenshot below:
![bildschirmfoto vom 2018-10-19 15-51-36](https://user-images.githubusercontent.com/2373731/47222415-fb64dc80-d3b6-11e8-8f21-7721160a94dc.png)

**Comment by MrPetovan** [comment]
Hi, this is a known issue although I can't find the previous discussion about it, it might have been on the Support forum.

Anyway, the solution is to add the CSS property `pointer-events: none` on the name overlay to allow clicks to go through it and select the image.

**Comment by tobiasd** [comment]
Can you check if this is only a problem, when you use the frio theme?

**Comment by MrPetovan** [comment]
It looks like it's caused by a JS framework only used in frio.
