### ISSUE TITLE
ActivityPub: Reshares by ignored accounts still show up in network stream

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5983]
### Expected behavior

When ignoring an ActivityPub account, all the posts by this account (including reshares) should be hidden from the network stream.

### Actual behavior

Only the posts actually authored by the ignored account are hidden, reshares still show up, probably because the reshared account itself isn't ignored.

**Comment by tobiasd** [comment]
For me this is actually the expected behaviour ;-) I may block a certain politician from my stream, but still follow an other one. So if that other one repeats a posting, it might be worth my attention after all.

**Comment by annando** [comment]
We are ignoring authors, not owners, I think. It's a question of definition.

**Comment by MrPetovan** [comment]
My personal case is that I'll prefer to stay in contact but they mostly reshare stuff I don't care always about.

Overall it feels weird to see a post mentioning an ignored account, even if it's only as a resharer.

> I may block a certain politician from my stream, but still follow an other one. So if that other one repeats a posting, it might be worth my attention after all.

This is a slightly different case, I'm not following nor blocking the accounts that the ignored account reshare posts from. But I'd be confused if I blocked B and that I would see a post from B reshared by A who I follow.

Even worse, if I ignore A and block B, will I see a reshare of B by A? A reshare of A by B?

**Comment by tobiasd** [comment]
So you don't want to not see a reshare by your contacts of ignored contact, but have an contact ignored and don't want to see their reshares. Ok this is a different situation then - I agree, I would not want to see their reshares either.

**Comment by MrPetovan** [comment]
I haven't witnessed this again in a while, pushing to next release.

**Comment by MrPetovan** [comment]
I haven't witnessed this again in a while, removing from milestone.

**Comment by MrPetovan** [comment]
Another instance has been witnessed by @rebeka-catalina , re-adding to milestone: https://forum.friendi.ca/display/fd59d1fe-105c-c1f5-c902-3f0307501604

**Comment by MrPetovan** [comment]
Can this be related to the recent changes in the way reshares are handled?

**Comment by annando** [comment]
I must confess that I'm currently struggling even finding a piece of code where we have a look at these values at all.

**Comment by MrPetovan** [comment]
Which values?

**Comment by annando** [comment]
Where do we look at all if we ignore a contact during the item processing?

While digging through the code I also saw that we can easily ignore content from an ignored author - but it will be complicated to ignore content that is reshared by an ignored contact, due to the way we now are processing the reshares.

**Comment by MrPetovan** [comment]
Aren't we fetching the original post when we receive a reshare? Can't we check at this point if the importer ignored the reshared author?

**Comment by annando** [comment]
Sadly it's not that easy. We don't receive content for a dedicated user on our server. This means that at first we receive the content and later we distribute it to our users. Between this point we have done the fetching - or possibly the content already exists on our system.

**Comment by MrPetovan** [comment]
So when we finally distribute it to our users, we have to add an extra check for shared content as well.

**Comment by annando** [comment]
When we distribute it, we are distributing some content without knowing that it is reshared. Now reshares are only activities, added to the starting post, just like an "like" or a comment.

I will see how I can solve this issue.

**Comment by MrPetovan** [comment]
Fixed by #7277, I'll reopen if I see anything suspicious.
