### ISSUE TITLE
Call to undefined method Friendica\Core\Addon::check()

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5994]
https://github.com/friendica/friendica/blob/ebc97ba8fe80442ca817bfe8f79b32588c2573ef/src/App.php#L1718

```
Fatal error: Uncaught Error: Call to undefined method Friendica\Core\Addon::check() in /var/www/html/src/App.php:1718 Stack trace: #0 /var/www/html/index.php(15): Friendica\App->runFrontend() #1 {main} thrown in /var/www/html/src/App.php on line 1718
```

**Comment by nupplaphil** [comment]
There is no `check()` in https://github.com/friendica/friendica/blob/develop/src/Core/Addon.php

**Comment by nupplaphil** [comment]
@MrPetovan maybe you already moved `check_addons()` to `Addon::check()` but it's in the next PR so your branch is working?

**Comment by MrPetovan** [comment]
Fixed in https://github.com/friendica/friendica/commit/f6e064195a4509f6eb7532a63681b5e57741e056

**Comment by nupplaphil** [comment]
Back in business :+1:

**Comment by MrPetovan** [comment]
Turns out there was this as well: https://github.com/friendica/friendica/commit/373df31817c413b03ebb9a1fb1351990fe9f4b29
