### ISSUE TITLE
Strange profile page relationship action link display

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6012]
I wanted to connect with @vinzv 's new account on https://less.re but there has been many inconsistencies between the relationship status display and the relationship action link on the profile page:
1. ✅ Before connecting, the hovercard showed the follow button.
2. ❌ Before connecting, on the profile page, the relationship action link was "Disconnect"?
3. ✅ Just after connecting, the profile page showed "Awaiting connection acknowledgment".
4. ❌ Just after connecting, on the profile page, the relationship action link was "Connect"?
5. ✅ After the connection was accepted, the relationship action showed "Disconnect".

Also I can access the same profile from two different contact ID?
- https://friendica.mrpetovan.com/contact/142577 🔒 : I'm not connected with this contact, yet there is a "Disconnect" link. ❌
- https://friendica.mrpetovan.com/contact/142914 🔒 : I'm connected with this contact, and there is a "Disconnect" link. ✅

Both https://friendica.mrpetovan.com/contact/142577/conversations 🔒 and https://friendica.mrpetovan.com/contact/142914/conversations 🔒 show the same content.

**Comment by MrPetovan** [comment]
First issue: all the public contacts have `rel = 2` which prompts the `Disconnect/Unfollow` link for any contact the user doesn't have a relationship with yet.

**Comment by MrPetovan** [comment]
Second issue: When awaiting connection acknowledgment, there is a Disconnect link but it fails to go through because the contact `rel` is `0` (and `pending` is `1`.

Question: Is it even possible to disconnect from a contact while "Awaiting connection acknowledgement"? I tried deleting the contact, but it didn't remove the physical record which made it impossible for me to try to reconnect on my node. When I deleted the contact record manually and tried to reconnect, I ended up on the remote node with the `Already introduced" error.

**Comment by annando** [comment]
We do have several issues with pending contacts, for example they can comment your posts, but you don't see it - but you had seen it, before they started the follow request.

**Comment by MrPetovan** [comment]
This doesn't answer my main question: is a contact disconnection can be honored by remote servers while it is awaiting acknowledgment? If yes, I can make `/unfollow` check `pending` as well, otherwise I keep hiding the disconnection link.

And I think we should hide the "Delete" item as well since it breaks everything as well.

**Comment by MrPetovan** [comment]
Hiding it is.
