### ISSUE TITLE
after git pull fatal error in browser - friendica down

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6015]
I did a git pull 3 minutes ago and now friendica is down with the following error message. 
Help ?

`
Fatal error: Uncaught Error: Call to undefined function goaway() in /PATH2FRIENDICA/addon/startpage/startpage.php:34 Stack trace: #0 /PATH2FRIENDICA/src/Core/Hook.php(164): startpage_home_init(Object(Friendica\App), Array) #1 /PATH2FRIENDICA/src/Core/Hook.php(141): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'home_init', Array, Array) #2 /PATH2FRIENDICA/src/Core/Addon.php(337): Friendica\Core\Hook::callAll('home_init', Array) #3 /PATH2FRIENDICA/mod/home.php(16): Friendica\Core\Addon::callHooks('home_init', Array) #4 /PATH2FRIENDICA/src/LegacyModule.php(68): home_init(Object(Friendica\App)) #5 /PATH2FRIENDICA/src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init') #6 [internal functi in /PATH2FRIENDICA/addon/startpage/startpage.php on line 34`

latest develop / mariadb / PHP7

**Comment by annando** [comment]
Have you updated the addons as well?

**Comment by hoergen** [comment]
Yes I do it always with  a script, so that i dont forget it.

**Comment by annando** [comment]
Please deactivate "startpage" for now. This is a cause of PR https://github.com/friendica/friendica/pull/5907

I hope that @nupplaphil can fix it soon.

For the chronicles, these files need to be touched:
```
blackout/blackout.php:        goaway($myurl);
impressum/impressum.php:    goaway('friendica/');
notifyall/notifyall.php:	goaway('admin');
startpage/startpage.php:		goaway($page);
statusnet/statusnet.php:			goaway('settings/connectors');
statusnet/statusnet.php:				goaway('settings/connectors');
statusnet/statusnet.php:					goaway('settings/connectors');
twitter/twitter.php:			goaway('settings/connectors');
```

**Comment by hoergen** [comment]
How can I deactivate startpage? I can't access Friendica.

**Comment by annando** [comment]
Comment out the line with ```goaway```. This should let your page be accessible.

**Comment by hoergen** [comment]
ok commented out in `addon/startpage/startpage.php` `goaway($page);` and Friendica is there again. Thanks a lot.
Think I don't close it yet until this is fixed?

**Comment by annando** [comment]
Please leave it open, yes.

**Comment by AlfredSK** [comment]
Btw. it is possible to manually go to a page by typing in the URL path.
And it is not possible to disable Startpage. Message says 'disabled' but it is still enabled.

**Comment by nupplaphil** [comment]
I think I'm to stupid to use my IDE and the search function!

Sorry for the inconvenience to you :-(

**Comment by MrPetovan** [comment]
Closed via https://github.com/friendica/friendica-addons/pull/763
