### ISSUE TITLE
Make links more obvious in Frio

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#6018]
Links are not decorated in Frio which makes them not really obvious depending on the context. Would we change that?
See post by Andy H3 in this Screenshot:
![47441038-a6a6d480-d7af-11e8-9569-126c7db5a500_2](https://user-images.githubusercontent.com/74432/47457450-6ce9c400-d7d7-11e8-8662-976e16b5acf2.png)
(Source: https://less.re/display/174591b4715bd07d464ffca869562117)

**Comment by vinzv** [comment]
> They actually lighten up when the post is hovered with a mouse, which of course doesn't really work with mobile (although if you tap on the post text, the links light up).

On mobile it's even harder. But on the desktop you need to have the incentive to hover it. That's what I meant with _depending on the context_.  Hovering the post only lightens up the submenu with like, comment etc.

> I've never liked this display gimmick on frio, and I'll welcome its removal.

I'm fine with the lighting up but for links inside the text there should be some underline, icon, whatever.

**Comment by vinzv** [comment]
> Hovering the post only lightens up the submenu with like, comment etc.

Oh, wow. I just realised that it's my custom color selection which nukes out the highlighting of in-text links... 
![screenshot_20181024_214906_2](https://user-images.githubusercontent.com/74432/47457363-2b591900-d7d7-11e8-9220-db4e5c40517c.png)

So I that reduces the issue to mobile-only.

**Comment by MrPetovan** [comment]
Underline would be a great fit, and we could get rid of the non-standard Underline BBCode tag in the formatting bar of the post/comment forms.

**Comment by vinzv** [comment]
I'm not sure what link underlining has to do with regular underlining?

**Comment by MrPetovan** [comment]
Underlining is the default formatting of links, if you remove all CSS on any browser, links will be underlined. There used to be a `<u>` tag in HTML 4 that was adding underline formatting but it's been deprecated in HTML 5 in favor of semantic tags like `<strong>` and `<em>` whose default formatting are respectively bold and italic.

In that regard, I'm in favor of dropping the confusing and deprecated `[u]` BBCode tag and restoring the default underlining formatting for links.

**Comment by MrPetovan** [comment]
I did a quick test, and underline for links is really awful and it isn't the standard Bootstrap (which frio is based on) uses. The remaining improvement would be to remove the highlighting on hover and warn about custom link colors that would be too close to regular text maybe?

**Comment by AlfredSK** [comment]
Hmm. I like the current highlighting of links in frio. The highlighting is currently done not only for links in the text but also for headlines and so on. If the link coloring would be permanent and not only on hovering the UI would be too colorful from my point of view. :-)
Maybe it is possible to make this an option in frio settings (highlight links on hover ON/OFF).
And please don't use underline for links as default. This looks like 90s-WWW. ;-)

**Comment by MrPetovan** [comment]
> the UI would be too colorful from my point of view

Maybe it's a problem that can be solved by tweaking the color scheme?

**Comment by vinzv** [comment]
> And please don't use underline for links as default. This looks like 90s-WWW. ;-)

Yeah, that's why my proposal was quite openly written. Some &raquo; or fontawesome icon would be good I guess.

**Comment by vinzv** [comment]
> Hubzilla has an addon that does mark links with a little bookmark icon. I like that.

Looking good! Other things that might be adequate:
https://fontawesome.com/v4.7.0/icon/hand-o-right
https://fontawesome.com/v4.7.0/icon/link

Or, to have it smaller and less cluttering:
https://fontawesome.com/v4.7.0/icon/caret-right
https://fontawesome.com/v4.7.0/icon/angle-right

**Comment by MrPetovan** [comment]
I'm not a fan of adding icons in the middle of the text. I'm now firmly convinced it's a color scheme issue and it's made worse by the hovering highlighting.

**Comment by rabuzarus** [comment]
What about adding a `mobile` or `tablet` class to https://github.com/friendica/friendica/blob/develop/view/theme/frio/php/default.php#L66 with `$a->is_mobile` and `$a->is_tablet`? With this we could deactivate the highlight feature for mobile and tablets through css

**Comment by MrPetovan** [comment]
Sure, and then we can have a frio user setting to disable it all the time as well.
