### ISSUE TITLE
[frio] File browser disappear when submitting a picture exceeding the file size limit

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6027]
### Expected behavior

An error message shows up in the file browser when I submit a picture heavier than the size limit and allows me to upload a new picture.

### Actual behavior

The error message received by the `/wall_upload` call is never shown anywhere and the file browser disappear until the page is reloaded.

### Steps to reproduce the problem

1. Open the new post modal
2. Switch to the File Browser tab
3. Upload a picture heavier than the `system.maximagesize` config value

### Friendica version you encountered the problem

2018.12-dev

**Comment by JonnyTischbein** [comment]
I guess I found the point where it failed. `onComplete` is not called on error. But I didn't found out why or how to solve. But I'm on it on the next days.


https://github.com/friendica/friendica/blob/15eada076f5ebd0db81263d07b28c5970b4db5b2/view/js/filebrowser.js#L110

**Comment by JonnyTischbein** [comment]
This already happens but is not received from js.
https://github.com/friendica/friendica/blob/15eada076f5ebd0db81263d07b28c5970b4db5b2/mod/wall_upload.php#L194-L203

**Comment by rabuzarus** [comment]
ohh one thing. frio does use a patched version of the filebrowser https://github.com/friendica/friendica/blob/develop/view/theme/frio/js/filebrowser.js

**Comment by JonnyTischbein** [comment]
Ohhh thanks!
But it is the same. I guess I was just linking the wrong file.


https://github.com/friendica/friendica/blob/15eada076f5ebd0db81263d07b28c5970b4db5b2/view/theme/frio/js/filebrowser.js#L207-L222
