### ISSUE TITLE
Viewing 'conversations' of a specific contact broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6034]
### Expected behavior
When I go to the conversations (Status) page of a contact the page should show the conversations of that contact.

### Actual behavior
The conversations page (Status) of the contact is empty. The posts page (Posts and Comments) is working.

### Steps to reproduce the problem
Search for a contact of yours (I tested it with a DFRN contact). Click on the little cloud icon (Network Posts). You're redirected to a page like https://example.com/contact/12/conversations and the page doesn't show any items.

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by tobiasd** [comment]
On what commit are you (on 15eada076f5ebd0db81263d07b28c5970b4db5b2, AP event participation merged, it is working for me). Using vier theme, in case it is a frio specific issue.

**Comment by annando** [comment]
Please test with other contacts as well. There seems to be an issue with contacts that are hidden.

**Comment by AlfredSK** [comment]
Yep. Right. When a contact isn't hidden. The page works es expected.

Question is why is the contact hidden? I did not hide it manually and the default profile of the contact is public and published. But the contact has two profiles (a public and a private profile). I am on the list of contacts that are allowed to see the privat profile.

**Comment by annando** [comment]
The contact decided to hide the profile.

**Comment by AlfredSK** [comment]
> The contact decided to hide the profile.

No. I'm the contact (me on another node). I would know. :-)

**Comment by tobiasd** [comment]
Mmh... for me even the statuses and conversations of _hidden_ contacts are displayed using the vier theme.

**Comment by AlfredSK** [comment]
Cannot reproduce anymore. Works for all contacts now (even the hidden ones).

Closing.
