### ISSUE TITLE
Installing current develop state broken

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#6038]
I just put up a node for testing and development purposes at https://2.vinzv.space.
As you can see the installer spits out some HTML but gives just a blank page. Switching to master branch brings up the regular installer with it's checks for PHP modules and so on. So I guess my server is configured fine.

### Friendica source (git, zip)
git, develop branch, commit 933f432

### PHP version
PHP 7.0.30-0

### SQL version
MariaDB 10.1.26-0

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by JonnyTischbein** [comment]
Is everything fine with the composer? Isn't there a different between master and develop right now?

**Comment by MrPetovan** [comment]
I don't think it is related. I've been completely changing `index.php` and `src/App.php`, I'd guess I introduced a regression for the install.

**Comment by nupplaphil** [comment]
@MrPetovan I'm currently debugging it.

Is it possible that with the introduction of `LegaceBaseModule.php` we cannot use globals in the legacy mods anymore?
https://github.com/friendica/friendica/blob/933f43218ad9e08a5fc6cc0d17928fd0f42ffa6e/mod/install.php#L14

**Comment by nupplaphil** [comment]
@vinzv It should work now with the current develop branch
Can you confirm it?

**Comment by vinzv** [comment]
@nupplaphil Yes, it works! Thanks a lot!
