### ISSUE TITLE
Cron Warnings

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6087]
`PHP Warning:  constant(): Couldn't find constant  in /src/Protocol/PortableContact.php on line 1376`

**Comment by MrPetovan** [comment]
Duplicate of https://github.com/friendica/friendica/issues/5911#issuecomment-436101442
Fixed by #6086

**Comment by miqrogroove** [comment]
I will try this patch.  I've only seen the error one time though.

**Comment by MrPetovan** [comment]
It depends on whether remote nodes running on develop have updated to the faulty version and how fast they have updated to the subsequent fix.

**Comment by miqrogroove** [comment]
For the 2018.09 branch it is also necessary to add `use Friendica\Core\Logger;` with the patch.  Going to try this over again.

**Comment by miqrogroove** [comment]
Nope.  Patch failed again.  Going to remove your call to `Logger::log()` and see if that works.

**Comment by MrPetovan** [comment]
Which patch? Which Logger call?

**Comment by tobiasd** [comment]
This adding `use Friendica\Core\Logger` maybe?

**Comment by MrPetovan** [comment]
This issue will be permanently fixed with #6336

**Comment by MrPetovan** [comment]
Closed via #6336
