### ISSUE TITLE
Friends/Subscriber Confusion

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6088]
When approving a "new follower" request, I am prompted to confirm the connection is a "subscriber" only in the second step.  After this, the new contact is displayed as a member of my default "Friends" group.  Is that correct?

At this point it is unclear if this new follower has become a subscriber with access to my private Friends-only posts.  I do want a follower to see my public posts only, and my intuition is that it's necessary to manually remove the new contact from the Friends group to hide content intended for people I know personally.

Is this a configuration problem?  A bug?  Working as designed?

**Comment by MrPetovan** [comment]
The `Friends` group is the default group where new contacts go to. If you want to have a smaller circle of actual friends, you have to create another group, move contacts manually to it, and then start posting to this group only.

So you can have 3 visibility tiers:
1. Public posts for anyone on Internet
2. Protected posts for all your followers only
3. Private posts for hand-picked contacts

My understanding is that you only want 1. and 3. and could do without 2., is that correct?

**Comment by miqrogroove** [comment]
Yeah I was not expecting "Friends" to include "followers".  This would also affect permissions on old posts and photos.  That's a bit of mess.

**Comment by MrPetovan** [comment]
I'm sorry about that, `Friends` is actually a hard-coded string that is translated into the user's language when we create this first catch-all contact group. I don't think it should exist as it currently behaves since we support ungrouped contacts anyway.
