### ISSUE TITLE
WSOD since last git pull

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6091]
Since git pull 06.11.18 - 16:16
[Tue Nov 06 16:08:57.599846 2018] [proxy_fcgi:error] [pid 7007:tid 139780055602944] [client 176.199.12.168:49472] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Friendica\\Content\\Text\\Feature' not found in /home/users/zsemberi/www/friendica/src/Content/Text/HTML.php:967\nStack trace:\n#0 /home/users/zsemberi/www/friendica/mod/network.php(209): Friendica\\Content\\Text\\HTML::search('', 'netsearch-box', '/network?f=', true)\n#1 /home/users/zsemberi/www/friendica/mod/network.php(167): saved_searches('')\n#2 /home/users/zsemberi/www/friendica/src/LegacyModule.php(68): network_init(Object(Friendica\\App))\n#3 /home/users/zsemberi/www/friendica/src/LegacyModule.php(39): Friendica\\LegacyModule::runModuleFunction('init')\n#4 [internal function]: Friendica\\LegacyModule::init()\n#5 /home/users/zsemberi/www/friendica/src/App.php(1692): call_user_func(Array)\n#6 /home/users/zsemberi/www/friendica/index.php(15): Friendica\\App->runFrontend()\n#7 {main}\n  thrown in /home/users/zsemberi/www/friendica/src/Content/Text/HTML.php on line 967\n'

**Comment by annando** [comment]
Please have a look at your php error log. Have you updates the addons as well?

**Comment by copiis** [comment]
Just updatet my posts, yes i updatet the addon as well

**Comment by annando** [comment]
Okay, please update the core again. There had been a problem for a few minutes. It seems you fetched the code exactly at the wrong time :-)

**Comment by MrPetovan** [comment]
Fixed by #6089

**Comment by copiis** [comment]
>  It seems you fetched the code exactly at the wrong time :-)

Yes thats my talent
