### ISSUE TITLE
ActivityPub: Object URI is not dereferencable

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6100]
### Expected behavior

 - See an object ID, e.g. https://libranet.de/objects/0b6b25a8-795b-e3c3-593b-b4e393158365
 - `GET` it with `Accept: application/activity+json`.
 - Receive an ActivityPub-compatible representation of the post.

Relevant AP documentation:

https://www.w3.org/TR/activitypub/#obj-id

>  These identifiers must fall into one of the following groups:
> 
>     1. Publicly dereferencable URIs, such as HTTPS URIs, with their authority belonging to that of their originating server. (Publicly facing content SHOULD use HTTPS URIs). 

### Actual behavior

 - See an object ID, e.g. https://libranet.de/objects/0b6b25a8-795b-e3c3-593b-b4e393158365
 - `GET` it with `Accept: application/activity+json`.
 - Receive a 404.

This inhibits the ability of a pure AP server to back-fill a conversation when it sees a reply to a Friendica object the server hasn't yet seen.

### Friendica version you encountered the problem

`This is Friendica, version 2018.12-dev that is running at the web location https://libranet.de. The database version is 1289, the post update version is 1281.`

**Comment by clacke** [comment]
Ideally, the `id` of the post would be the same as the `url` of the post, and the `url` attribute would be redundant (e.g. Pleroma doesn't add it when publishing posts).

Currently the `url`, e.g. https://libranet.de/display/0b6b25a8-795b-e3c3-593b-b4e393158365 , doesn't support the `Accept: application/activity+json` header -- it just returns the HTML page.

**Comment by annando** [comment]
This 404 does happen when the item cannot be found or is private. Possibly there is some side effect with forum posts. Normally it does work fine.

**Comment by clacke** [comment]
Hmm. If I try to get, without added headers, https://libranet.de/objects/0b6b25a8-175b-e3c9-049b-509591767566 (which is Public), I get redirected to https://libranet.de/display/0b6b25a8-175b-e3c9-049b-509591767566 . If I get .../display/... with activity+json, I get redirected to .../objects/... . If I try to get .../objects/... with activity+json, I get 404.

**Comment by annando** [comment]
Like I said, there seems to be an issue with forum posts. Just try some other link, it will work.

**Comment by clacke** [comment]
What's a forum post? The one I linked is just a comment on a post from GNU Social.

**Comment by fabrixxm** [comment]
> What's a forum post? The one I linked is just a comment on a post from GNU Social.

It's is, in fact, from the point of view of Friendica, a comment to a post in a forum-type profile

https://forum.friendi.ca/display/a730e153165be3b5e11b28a542245460

**Comment by clacke** [comment]
Does this mean I would only be able to fetch the objects for my original posts, not comments to other posts?

**Comment by clacke** [comment]
I can confirm that e.g. `curl -H accept:application/activity+json https://libranet.de/objects/0b6b25a8-935b-e6b4-7656-bbf026681357` (an original post) works.

**Comment by annando** [comment]
Yeah, it had been a bug. Thanks for reporting it!
