### ISSUE TITLE
slow travis-ci tests

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6101]
We do have slow tests which results in times about 30 minutes before a check is added to the PR.

@Rudloff do you know a good way to trace what tests are too long? I'd like adding something like https://github.com/johnkary/phpunit-speedtrap to track phpunit. Do you have experiences with it?

**Comment by Rudloff** [comment]
I think that is a good idea. I have used phpunit-speedtrap a few years ago and I remember it being pretty straightforward to setup.

(However, I'm pretty sure slow tests come from the database IO and the solution would be to mock all database access.)

**Comment by nupplaphil** [comment]
Thanks for the quick reply! I'll add it with a PR and take the results as a prio-line for refactoring some tests.

**Comment by nupplaphil** [comment]
unfotunately phpunit-speedtrap requires at least PHP 7.0
Do you know an alternative? Because I already bricked the whole composer dependencies twice in changing some versions in `composer.json` ;-)

**Comment by Rudloff** [comment]
Maybe we could use the outdated phpunit-speedtrap 1.1? (I really don't like using outdated dependencies but since this will only be used by developers...)

The alternative would be to write our own listener (example [here](https://fatalfailure.wordpress.com/2011/08/22/detecting-slow-tests-with-phpunit/)) but it is more work.

**Comment by nupplaphil** [comment]
I successfully added it with #6104 :-)

And here are the top 10 of slow tests:
```
You should really fix these slow tests (>500ms)...
 1. 4839ms to run Friendica\Test\src\Core\Lock\DatabaseLockDriverTest:testLockTTL
 2. 4772ms to run Friendica\Test\src\Core\Lock\MemcachedCacheLockDriverTest:testLockTTL
 3. 4754ms to run Friendica\Test\src\Core\Lock\RedisCacheLockDriverTest:testLockTTL
 4. 2749ms to run Friendica\Test\src\Core\Cache\RedisCacheDriverTest:testTTL
 5. 2722ms to run Friendica\Test\src\Core\Cache\DatabaseCacheDriverTest:testTTL
 6. 2715ms to run Friendica\Test\src\Core\Cache\MemcachedCacheDriverTest:testTTL
 7. 2476ms to run Friendica\Test\ApiTest:testApiStatusesRepeatWithId
 8. 2415ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithNegativePage
 9. 2258ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithRss
 10. 2237ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithNegativePage
...and there are 342 more above your threshold hidden from view
```

I think I have to refactor the cache tests ;-)

**Comment by MrPetovan** [comment]
The TTL waits for 5 seconds no matter what, right?

**Comment by nupplaphil** [comment]
Yep, because otherwise I'd have to fake a "timewarp" which isn't possible yet.

I now added a skip for the TTL-tests until we mock redis/memcache/db. Because we do want to test if we use the cache right, not if the cache itself is working right. But this would be a lot more of mocking-action which I don't want to do now to be honest ;-)

**Comment by nupplaphil** [comment]
I'd like to use this issue for tracking slow tests until we don't have any slow tests anymore. Is it OK for you?

**Comment by nupplaphil** [comment]
New best of:
```
You should really fix these slow tests (>500ms)...
 1. 5269ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithNegativePage
 2. 5179ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithRss
 3. 5140ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithNegativePage
 4. 5138ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithRss
 5. 5104ms to run Friendica\Test\ApiTest:testApiStatusesRepeatWithId
 6. 3733ms to run Friendica\Test\ApiTest:testApiStatusesMediap
 7. 3600ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimeline
 8. 3375ms to run Friendica\Test\ApiTest:testApiStatusesUpdateWithHtml
 9. 3234ms to run Friendica\Test\ApiTest:testApiStatusesDestroyWithId
 10. 3213ms to run Friendica\Test\ApiTest:testApiStatusesNetworkpublicTimelineWithRss
...and there are 338 more above your threshold hidden from view
```

Next step is to mock DBA for API test cases ;-)

**Comment by nupplaphil** [comment]
Thanks to #7441 , we gain more speed:
```console
You should really fix these slow tests (>500ms)...
 1. 2831ms to run Friendica\Test\ApiTest:testApiStatusesRepeatWithId
 2. 2551ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithNegativePage
 3. 2490ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithRss
 4. 2456ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithRss
 5. 2272ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithNegativePage
 6. 1777ms to run Friendica\Test\ApiTest:testApiStatusesMediap
 7. 1704ms to run Friendica\Test\ApiTest:testApiStatusesUpdateWithHtml
 8. 1696ms to run Friendica\Test\ApiTest:testApiStatusesShowWithConversation
 9. 1691ms to run Friendica\Test\ApiTest:testApiStatusesUpdate
 10. 1611ms to run Friendica\Test\ApiTest:testApiConversationShowWithId
...and there are 19 more above your threshold hidden from view
```

**Comment by nupplaphil** [comment]
Some new insights:
- currently ~30% of the overall time is "just" building up the test-environment (composer install, setup environment, ...)
- The last ~10% is uploading the coverage

For the first 30%, we can think about a "test-docker" instance, which would have all environments pre-set. I know such environment f.e. for the nextcloud codebase.
This would be a benefit if we ever want to switch to gitea too, because such "test-docker" instance would enable test our codebase without being forced to use travis ;-)

**Comment by nupplaphil** [comment]
Last run of #7465 

```console
You should really fix these slow tests (>500ms)...
 1. 3456ms to run Friendica\Test\ApiTest:testApiStatusesRepeatWithId
 2. 3083ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithNegativePage
 3. 2997ms to run Friendica\Test\ApiTest:testApiStatusesHomeTimelineWithRss
 4. 2960ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithRss
 5. 2929ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimelineWithNegativePage
 6. 2106ms to run Friendica\Test\ApiTest:testApiStatusesMediap
 7. 2076ms to run Friendica\Test\ApiTest:testApiConversationShowWithId
 8. 2060ms to run Friendica\Test\ApiTest:testApiStatusesShowWithConversation
 9. 2009ms to run Friendica\Test\ApiTest:testApiStatusesPublicTimeline
 10. 1938ms to run Friendica\Test\ApiTest:testApiStatusesUpdateWithHtml
...and there are 19 more above your threshold hidden from view

Time: 6.96 minutes, Memory: 184.00MB
```
Overall Time: 11,18 minutes
So we're currently loosing ~35-40% of the time in the environment

**Comment by MrPetovan** [comment]
In this context, we're "saving" 35% of the testing time, not "losing". 😉

**Comment by nupplaphil** [comment]
English, my best not is sometimes I speak cannot good ... But thanks for the hint :D

**Comment by MrPetovan** [comment]
It's fine, I like teaching. I didn't expect to teach English to a bunch of German nerds, 'tis all.

**Comment by nupplaphil** [comment]
Closing --> nothing to do :-)
