### ISSUE TITLE
Display of more profile fields for some account type

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#6105]
### Expected behavior

The following screenshots are from two different account types. The first is a personal page and the second a public forum. The first allows modifying the additional profile fields (marital status, political views, etc.), while the second does not permit this, as there is no access to these fields.

![untitled](https://user-images.githubusercontent.com/28751375/48300223-05887f80-e50c-11e8-9764-d0cd2e807e35.png)
![untitled2](https://user-images.githubusercontent.com/28751375/48300224-09b49d00-e50c-11e8-9783-fe9e06e6ccc2.png)

If there is no possibility to alter these additional fields --because there is no access to them-- one would expect that none of these additional fields are displayed on a user's profile.

### Actual behavior

Regardless of the selected account type (i.e. personal pages or public forum), this information is displayed if any of these fields are populated. 

Real scenario, I imported a public forum account and it contained random strings in two of these additional profile fields. I cannot explain how these fields were populated. 

When I consequently wanted to remove the information, it took me several attempt to figure out how to access these fields that seemed to have disappeared at the time. 

### Friendica version you encountered the problem
Develop

**Comment by FrancoisGeyser** [comment]
Hi,  I would like to have a look at this?

**Comment by MrPetovan** [comment]
Of course, let us know what we can help you with!

**Comment by AndyHee** [comment]
I think this can be closed.

The total revamp of profiles addressed this.
