### ISSUE TITLE
Twitter: import of remote timeline broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6109]
### Expected behavior
Import of the Twitter remote timeline should work if the import is activated in the settings.

### Actual behavior
Import of the remote timeline is broken since approx. 24 hours.
Discussion: https://forum.friendi.ca/display/0b6b25a8-115b-e752-79ed-cb0184754502

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by annando** [comment]
See here for the most likely cause: https://github.com/friendica/friendica/issues/5913#issuecomment-437628443

**Comment by AlfredSK** [comment]
I saw this comment. But I don't have that error in my PHP error log.

**Comment by AlfredSK** [comment]
Nope. Nothing in syslog or apache/error.log either.

**Comment by AlfredSK** [comment]
With my limited understanding of methods and functions it's hard to track this down.

In https://github.com/friendica/friendica-addons/blob/d2460a43e5faf685bda49e18214e6d3efe0a21d9/twitter/twitter.php#L1268
there is a `Strings::getTags()` but I cannot find a function (?) with the name `getTags()` in src/Util/Strings.php.

Maybe this is related or I am telling nonsense here. :-)

**Comment by MrPetovan** [comment]
Caused by #773
