### ISSUE TITLE
Undefined index 'comment' in DBStructure

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#6119]
In line 332 
https://github.com/friendica/friendica/blob/f67cf4e63b5779dde74baa1a39ca02fecc5273ab/src/Database/DBStructure.php#L331-L333
I didn't check, could be an issue with my addon. Nevertheless the code should check the index before accessing it.
Something like:

```php
 if (isset($database[$name]["table_status"]["Comment"])) {
        $structurecomment = isset($structure["comment"]) ? $structure["comment"] : "";
	if ($database[$name]["table_status"]["Comment"] != $structurecomment) {
             $sql2 = "COMMENT = '".DBA::escape($structurecomment)."'";
```

**Comment by MrPetovan** [comment]
Related to #5932

**Comment by annando** [comment]
Could you check whether your addon does contain comment fields at all? All core tables do have these fields.

**Comment by fabrixxm** [comment]
My addon does not contains "comments" field:
https://kirgroup.com/projects/fabrixxm/friendica-projects/tree/master/projects.php#L2319

I could add it, but I think a better approach is to be prepared for it to  be missing.
either:
- the field is optional, then we check for it and have a default value
- the field is mandatory, then we raise an hard error, so developers know that is missing
