### ISSUE TITLE
"... is not a fully qualified URL, please use App->internalRedirect() instead"

### ISSUE THREAD

**Issue by annando** [friendica/friendica#6124]
Related to https://github.com/friendica/friendica/issues/6019

```
[13-Nov-2018 08:45:32 Europe/Berlin] PHP Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: 'https://squeet.me/https://squeet.me/search?tag=Mobilität' is not a fully qualified URL, please use App->internalRedirect() instead in /src/Core/System.php:252
Stack trace:
#0 /src/App.php(1850): Friendica\Core\System::externalRedirect('https://squeet....')
#1 /src/App.php(1865): Friendica\App->internalRedirect('https://squeet....')
#2 /mod/redir.php(41): Friendica\App->redirect('https://squeet....')
#3 /src/LegacyModule.php(68): redir_init(Object(Friendica\App))
#4 /src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init')
#5 [internal function]: Friendica\LegacyModule::init()
```

**Comment by MrPetovan** [comment]
Oooh, `parse_url` can't understand non-ANSI characters, it's getting spicy.

**Comment by annando** [comment]
it would be too easy is it would be too easy.

**Comment by MrPetovan** [comment]
Beyond banter, the solution is to correctly escape the search term with `urlencode()`.

**Comment by annando** [comment]
Could you collect a list where we don't escape correctly? This sounds like some task for the weekend.

**Comment by MrPetovan** [comment]
Not easily, beyond the obvious `App->redirect` calls, we use `toggle_mobile` and `redir` to make arbitrary redirections.

For example, in this case, this looks like it was a `/redir/[contact_id]?url=https://squeet.me/search?tag=Mobilität` call, which doesn't make any sense at all.

**Comment by MrPetovan** [comment]
Part of #5996
