### ISSUE TITLE
Items from Saved Folders cannot be removed

### ISSUE THREAD

**Issue by MarkusF47** [friendica/friendica#6125]
### Expected behavior
Items from Saved Folders should be gone after removing them.

### Actual behavior
* Redirection to a URL in the form of `https://<friendica server>/filerm/<ID>?f=&term=<folder name>`
* Items are not deleted

### Steps to reproduce the problem
* open a Saved Folder
* click on the `(x)` of the red saved folder tag of a posting

### Friendica version you encountered the problem
2018.12-dev

@annando suggests that it is related to this PHP notice:
`PHP Notice: Undefined index: cat in /mod/filerm.php on line 17`

**Comment by MrPetovan** [comment]
Paging @JonnyTischbein, may be related to #5861

**Comment by JonnyTischbein** [comment]
I don't think so. In the PR I removed the optional (if the SESSION var war set) internal redirect after the unsave operation.

https://github.com/JonnyTischbein/friendica/blob/29033bdf05f1d4db09f319659ca533894eab4c7f/mod/filerm.php#L24-L28

But I will take a look.

**Comment by tobiasd** [comment]
When I tried accessing a saved folder (possible an empty one) I got the following PHP error

````
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to conversation() must be of the type array, boolean given, called in /mod/network.php on line 349 and defined in //include/conversation.php:441
Stack trace:
#0 /mod/network.php(349): conversation(Object(Friendica\App), false, Object(Friendica\Content\Pager), 'network-new', 0, false, '', 2)
#1 /mod/network.php(478): networkConversation(Object(Friendica\App), false, Object(Friendica\Content\Pager), 'network-new', 0)
#2 /mod/network.php(387): networkFlatView(Object(Friendica\App), 0)
#3 /src/LegacyModule.php(69): network_content(Object(Friendica\App))
#4 /src/LegacyModule.php(44): Friendica\LegacyModule::runModuleFunction('content')
#5 [internal function]: Friendica\LegacyModule::content()
#6 /src/App.php(1719): call_user_func(Array)
#7 /v in /include/conversation.php on line 441
````

When trying to remove an entry from a different folder I got a WSoD (no message logged as far I can find) but the posting remained in the maybe a missing use in `folder.filerm` or so?

**Comment by MrPetovan** [comment]
Is this fixed by #6152?

**Comment by tobiasd** [comment]
For me the posting was removed from the group; but I got the following error

```
PHP Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: 'https://example.com/network?f=&file=free media' is not a fully qualified URL, please use App->internalRedirect() instead in /src/Core/System.php:252
Stack trace:
#0 /src/App.php(1850): Friendica\Core\System::externalRedirect('https://social....')
#1 /mod/filerm.php(39): Friendica\App->internalRedirect('/network?f=&fil...')
#2 /src/LegacyModule.php(69): filerm_content(Object(Friendica\App))
#3 /src/LegacyModule.php(44): Friendica\LegacyModule::runModuleFunction('content')
#4 [internal function]: Friendica\LegacyModule::content()
#5 /src/App.php(1719): call_user_func(Array)
#6 /index.php(15): Friendica\App->runFrontend()
#7 {main}
  thrown in /src/Core/System.php on line 252
```

**Comment by MrPetovan** [comment]
Please move this comment to #5996 as it is unrelated to this fix.

**Comment by MrPetovan** [comment]
Once the unelated Fatal Error locally fixed, I was able to verify this issue is fixed.
