### ISSUE TITLE
UX Annoy: [frio] "Comment" link needs two clicks on posts with replies

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6133]
### Expected behavior

Clicking on the "Comment" link on a post with replies opens the OP comment box and focuses the textarea.

Expected behavior (on a post without replies):

![screen shot 2018-11-14 at 13 48 15](https://user-images.githubusercontent.com/925415/48505153-5fdb5600-e814-11e8-850d-4ce822c0467c.png)
![screen shot 2018-11-14 at 13 48 23](https://user-images.githubusercontent.com/925415/48505154-6073ec80-e814-11e8-9c7f-ef05d997aa33.png)

### Actual behavior

Clicking on the "Comment" link on a post with replies first closes the displayed inactive comment textarea, another click is required to open the comment box again.

Actual behavior on a post with replies:

![screen shot 2018-11-14 at 13 47 40](https://user-images.githubusercontent.com/925415/48505181-71246280-e814-11e8-8ee6-987db4dac355.png)
![screen shot 2018-11-14 at 13 47 50](https://user-images.githubusercontent.com/925415/48505182-71246280-e814-11e8-8c6c-e1cccd669fdc.png)
![screen shot 2018-11-14 at 13 47 59](https://user-images.githubusercontent.com/925415/48505184-71246280-e814-11e8-8024-607838d4f3bd.png)

### Steps to reproduce the problem

1. Click on the "Comment" link on a post with replies
2. Loudly sigh
3. Click again on the "Comment" link

### Friendica version you encountered the problem

2018.12-dev

### Friendica source (git, zip)

git

### PHP version

7.2

**Comment by tobiasd** [comment]
This is frio specific right? Using vier and Vivaldi the comment box text area is selected  when I click the comment link.

**Comment by MrPetovan** [comment]
Most probably. Did you check both on a reply-less post and on a reply-full post?

**Comment by tobiasd** [comment]
Yes, in vier the focus is set into the comment text area, for comments of comments, comments of postings with or without comments and when you start editing a new posting.
