### ISSUE TITLE
UX Annoy: Birthday reminders showing for followers

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6135]
### Expected behavior

Birthday reminders show only for people I chose to follow.

### Actual behavior

Birthday reminders show also for people who are following me.

![screen shot 2018-11-14 at 14 56 53](https://user-images.githubusercontent.com/925415/48508890-b8fbb780-e81d-11e8-8ba1-a5cce5edebf4.png)
![screen shot 2018-11-14 at 14 57 56](https://user-images.githubusercontent.com/925415/48508891-b9944e00-e81d-11e8-8c87-e8e388b691c1.png)

### Friendica version you encountered the problem

2018.12-dev

**Comment by tobiasd** [comment]
I <3 that feature ;-) So you want a per contact selection to show the birthday reminder, opting in to show it?

**Comment by MrPetovan** [comment]
With my settings (Soapbox), I don't have any interaction with my followers. At the moment I can't even have a comprehensive list of people who follow me but that I don't follow myself in the `/contact` page.

I think those reminders should only be shown for people who at least have manually validated a follow request.

**Comment by tobiasd** [comment]
I was thinking a checkbox at `/contact/id` within the contact settings block to show the notifications.

I don't like having it tied to the connection state. I may follow somebody who is publishing their birthday publically who does not follow back but I still might want to have the notification. On the other hand I may have a mutual connection with a dear friend where I know the birthday and don't need the additional reminder in my socnet.

**Comment by annando** [comment]
I wouldn't want to be check/uncheck such settings at all of my several hundred contacts.

**Comment by tobiasd** [comment]
Show the reminder once it is either a mutual bi-directional connection or you are a fan of somebody (but not for your fans) automatically, but with an per-user checkbox to override the automatic behaviour?
