### ISSUE TITLE
wrong redirection after comment deletion

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6148]
### Expected behavior

When viewing a conversation thread at `/display/$GUID` and deleting a comment from the thread, to remain on the `/display/$GUID` page.

### Actual behavior

After deletion one is put on the `/network` page.

### Steps to reproduce the problem

* (use vier maybe)
* open a conversation thread
* delete a comment

### Friendica version you encountered the problem

2018.12-dev

**Comment by MrPetovan** [comment]
I'm sorry to bug you again, but can you please look into it @JonnyTischbein?

**Comment by annando** [comment]
We have to check for the following condition:
What does happen when the conversation url is ```/display/$GUID``` but ```$GUID``` is the ```$GUID``` of the comment that we just have deleted? In that case the return url should be the parent post.

**Comment by JonnyTischbein** [comment]
Right, I missed that case.
It returns to an empty page, Item not found

**Comment by MrPetovan** [comment]
It should be good now, right?

**Comment by annando** [comment]
I guess so, I haven't tested though.
