### ISSUE TITLE
AP: /redir links go to /outbox

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6168]
Local post: https://friendica.mrpetovan.com/display/00d81f2c-185b-f2ac-213b-439424023616
Source link: https://friendica.mrpetovan.com/redir/19405?url=https://MELD.de/display/00d81f2c-185b-f2ac-213b-439424023616
Final redirection: https://meld.de/outbox/richard?dfrn_id=1:d879ef8923f7e8f96660ed40f18e70a85c7f0203b0d67d34de697f8f41d8a85b&dfrn_version=2.23&type=profile&sec=ddfe1edee0208274874ab0d8ea009796bd99996eb0e4b29c619712e938c513d4&destination_url=https://MELD.de/display/00d81f2c-185b-f2ac-213b-439424023616

Profile link: https://friendica.mrpetovan.com/redir/19405
Final redirection: https://meld.de/outbox/richard?dfrn_id=1:d879ef8923f7e8f96660ed40f18e70a85c7f0203b0d67d34de697f8f41d8a85b&dfrn_version=2.23&type=profile&sec=2e8cc39fd1798abd76ab99b4d91494b93443c5484e30302806d1cbcf528ff18c

**Comment by annando** [comment]
Weird.

**Comment by MrPetovan** [comment]
I found an interesting discrepancy in my `contact` table while searching on `` `nurl` = 'http://meld.de/profile/richard'``:

id | uid | network | poll
-- | -- | -- | --
19405 | 0 | dfrn | https://MELD.de/dfrn_poll/richard
125194 | 0 | apub | https://MELD.de/dfrn_poll/richard
31072 | 1 | apub | https://Meld.de/outbox/richard

There are two public entries with a different `network` but the same `poll`, and my relationship entry with a different `poll`.

The `/redir` links above should have been `/redir/125194` and I would be correctly redirected to the end address, but since it's taking the first public entry, it goes like this:
1. `/redir` pulls the `contact` record with `` `id` = 19405``
2. It checks the `network` to see if it should remote auth. In this case, it is `dfrn`, so no simple redirection to the target destination URL, the goal is to call `https://MELD.de/dfrn_poll/richard?destination_url=...`
3. But then `/redir` pulls the contact with the same `nurl` and `` `uid` = 1 ``, and BAM, an `apub` contact with an unexpected `poll` address.
4. This leads to try remote authentication against `https://Meld.de/outbox/richard` which isn't geared for it.

The solution is to remove the first outdated record, and add a unique index on `uid, nurl` to prevent this from happening again. We also need to add a check to update the public record with the new `network` instead of trying to create a new one.

**Comment by MrPetovan** [comment]
Addendum: In my `contact` table have 87 public contacts with two records with a different `network`. It's either Mastodon contacts (`stats` and `apub`) or Friendica contacts (`dfrn` and `apub`).

**Comment by annando** [comment]
I'm confused that DFRN contacts are now present as APUB as well, this really was unintended. Concerning the unique key: It is complicated :-) When using the statusnet connector, we can have the same url with two different networks. 

Some workaround for the problem could be to switch to the new magic auth when we detect such a situation. But this doesn't solve the duplicates.

**Comment by MrPetovan** [comment]
Well, we do have an order of priority for network, I believe it should also be used when looking for the public contact of a given nurl.

**Comment by annando** [comment]
In fact I would like to deprecate that connector since the purpose is very limited.

**Comment by MrPetovan** [comment]
So first we deprecate the connector, then we can add the unique index. Is it an addon or a built-in connector?

**Comment by annando** [comment]
I tend to deprecate the addon when OStatus itself is deprecated by Mastodon, so that GNU Social itself will be an island. In the time between I would like to create some job that has got a look at duplicates. One cannot simply remove them, the linked data needs to be aggregated.

**Comment by MrPetovan** [comment]
Wait, are you talking about StatusNet or OStatus? I don't think we should deprecate OStatus, what about all the existing GNU Social relationships?

**Comment by annando** [comment]
I wouldn't deprecate OStatus, but I'm unsure about the right time to remove that addon. I consider this addon toxic, like the "Diaspora" addon. People assume that they need this to communicate with these networks.

So I'm unsure what to do there. Possibly we could also change these addons in a way that they are only visible to selected users.

**Comment by MrPetovan** [comment]
Maybe we should do the other way, put the built-in Diaspora and OStatus support into their respective addon?

**Comment by annando** [comment]
Please not ;-)

The protocols do need too much stuff from the core. These would be "fake" addons.
