### ISSUE TITLE
[wppost] Friendica posts will not be broadcast to WordPress.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6173]
Ower this link

https://zsemberi.de/xmlrpc.php

**Comment by copiis** [comment]
The status quo is that my Wordpress addon is enabled in friendica and posts are to be sent automatically to my Worpress page on zsemberi.de, but that's none of your business. The URL is https://zsemberi.de/xmlrpc.php set and the access data I have twice checked.

**Comment by annando** [comment]
Yeah, I currently do have the same problems here. I will check.

**Comment by annando** [comment]
@copiis great you closed it. I totally forgot to mention this issue in my corresponding PR.

**Comment by copiis** [comment]
Mann denkt mit...
