### ISSUE TITLE
[AP] Video doesn't seem to be working anymore

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6175]
Original post: https://meld.de/display/00d81f2c-125b-f427-be94-679089703498

Local post: https://friendica.mrpetovan.com/display/00d81f2c-125b-f427-be94-679089703498

In both pages, the video either fails to play or fails to load entirely on Vivaldi (based on Chromium) on Mac OS and Windows.

**Comment by annando** [comment]
It does play in both systems when I try it.

**Comment by jasoncheng** [comment]
It's can play now; Could it also support as attachments on API response, thanks

<img width="1116" alt="2018-11-21 12 05 20" src="https://user-images.githubusercontent.com/540463/48786330-9be54e00-ed21-11e8-817b-b228706a3dc1.png">

**Comment by MrPetovan** [comment]
More info:
Video URL on local post: https://friendica.mrpetovan.com/redir/19405?url=https://MELD.de/attach/27
Output:
```json
{
	"@context": ["https:\/\/www.w3.org\/ns\/activitystreams", "https:\/\/w3id.org\/security\/v1", {
		"vcard": "http:\/\/www.w3.org\/2006\/vcard\/ns#",
		"dfrn": "http:\/\/purl.org\/macgirvin\/dfrn\/1.0\/",
		"diaspora": "https:\/\/diasporafoundation.org\/ns\/",
		"manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
		"sensitive": "as:sensitive",
		"Hashtag": "as:Hashtag"
	}],
	"id": "https:\/\/MELD.de\/outbox\/richard",
	"type": "OrderedCollection",
	"totalItems": 636,
	"first": "https:\/\/MELD.de\/outbox\/richard?page=1"
}
```
(Related to #6168)

Video URL on local post: https://meld.de/redir/3?url=https://MELD.de/attach/27
Output (compressed): [VID-20181119-WA0008.mp4.zip](https://github.com/friendica/friendica/files/2600653/VID-20181119-WA0008.mp4.zip)

Plays fine in Quicktime Player but not in the browser. Only the first 11.5KB load (a few frames) but it stops and never picks up.

**Comment by AlfredSK** [comment]
In Firefox both videos are playing well here. (FF 63.0 on Linux)

**Comment by copiis** [comment]
Works for me, tested with Firefox, Vivaldi and Chrome.

**Comment by MrPetovan** [comment]
Duplicate of #6168
