### ISSUE TITLE
Preferences for additional features with 2018.12

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#6195]
A school project has different wishes for version 2018.12. I'll summarize this here:

The "additional features" should be adjustable on the server again.

Suggestion: 
Default setting as in the last 2018.12. 
The admin can reactivate the settings on the server and make them available to the users. Comparable to the "advanced settings" of an AVM router.

Further settings should be possible
- Show Forums
- Group Filters
- Network Filter
- Personal
- Contributions 'do not like'
NEW (hide eventlist)

Note for the user: If you have any questions about the settings, please contact the admin of your installation.

The "Personal notes" should also be displayed in the icon bar. We use this more often and the way via the submenu is cumbersome.
In addition there should be a possibility to embed videos directly without using the insert button. This seems a little outdated and boring for the children ;).
Hubzilla does this with an addon "std_embeds.php". Maybe this can be used for Friendica?

**Comment by annando** [comment]
Can you split your issues, since they cover separate topics?

Concerning the group filters: Would it be okay to just not display the group filter when there is only a single group?

**Comment by MrPetovan** [comment]
> Default setting as in the last 2018.12.

As in `2018.09`, right?

**Comment by MrPetovan** [comment]
When I saw this issue, that was my thought exactly, having them configurable from the settings file, which made me consider switching it from an INI file to a PHP array before the `2018.12` release. What do you think?

**Comment by MrPetovan** [comment]
1. Less issues with quotes.
2. Actionable error messages for syntax errors, wider IDE syntax check support.
3. Same support for constants (unlike JSON).
4. Same support for comments (unlike JSON).
5. No parsing required.
6. Same as database config file.
