### ISSUE TITLE
Only first hastag is displayed.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6202]
Only first hastag in the post is presented at the end of the post. All following hashtags are missing.

**Comment by MrPetovan** [comment]
Can you please post screenshots of the editing screen and the resulting displayed post?

**Comment by MrPetovan** [comment]
I can confirm only one hashtag (and one mention) is stored in `term`.

**Comment by JonnyTischbein** [comment]
I'm not sure what the code in Term.php does but it is cause by setting `$link = ''` in 143
https://github.com/friendica/friendica/blob/ea4e772b1e776876c40e30c67f30e6c35cf7d3aa/src/Model/Term.php#L130-L144

Or the `DBA::exist` is wrong

https://github.com/friendica/friendica/blob/ea4e772b1e776876c40e30c67f30e6c35cf7d3aa/src/Model/Term.php#L159-L161

If remove linke 143 or the continue in 160 it is working. 

I would guess that 143 is wrong but I'm really unsure.

Can anybody help ?

**Comment by JonnyTischbein** [comment]
It should be your commit @MrPetovan https://github.com/friendica/friendica/commit/81f89ccae82786c5a99de921e1a44e8b47d8d592#diff-9b6e5e7245832faa46e10a22f1e64812

We need to adjust the `DBA::exist` call

**Comment by MrPetovan** [comment]
Yes, the correct answer its to adjust the exists condition to not rely on the link. Nice catch!

**Comment by JonnyTischbein** [comment]
I did rely on the hashtag term instead. That is okay, isn't it ?

**Comment by MrPetovan** [comment]
Yep, it's supposed to be unique for the uid, iod and type.
