### ISSUE TITLE
[AP] Wrong text in notifications

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6205]
### Expected behavior

When somebody mentions me in a comment with an @-mention to see the notification "XYZ mentioned you" and "XYZ commented on the posting of ZYX" otherwise.

### Actual behavior

I think this has to do something with the `To` field in AP. I get notifications about being *mentioned* even though it is only a comment to a comment of mine in a thread I commented on.

**Comment by tobiasd** [comment]
> Where does the commenting post come from? Friendica?

Yes, it is from ~friendica

**Comment by MrPetovan** [comment]
I can confirm this when Mike answers a Friendica post, it mentions everyone subscribed to the post.

**Comment by MrPetovan** [comment]
Passing note that with https://github.com/friendica/friendica/pull/6389, you'll get `X mentioned you on Y's post` notifications instead which are slightly more descriptive than just `X mentioned you`.

**Comment by annando** [comment]
For technical reasons I wouldn't like to change anything. We need this behaviour to better cooperate with other AP implementations. And I wouldn't like to have to look into the body of a post if someone is mentioned. I really would like to postpone this the next version where our notification system will handle it better.

**Comment by annando** [comment]
With the latest changes this behaviour shouldn't happen anymore. (Besides comments from systems like Pleroma or Mastodon who always tag the receivers)

**Comment by tobiasd** [comment]
I will have a look, if this happens again with contacts from nodes that run the RC code.

**Comment by tobiasd** [comment]
This happened again in a forum posting. No explixit @-mention contained in the reply and the reply was not directed to a comment of mine.

**Comment by MrPetovan** [comment]
But was it directed to a comment of a comment of yours? What does https://friendica.mrpetovan.com/admin/item/source?guid=<reply GUID> says about the mentions?

**Comment by MrPetovan** [comment]
We need more info about this issue.

**Comment by annando** [comment]
I cannot reproduce the problem and never experienced it.

**Comment by tobiasd** [comment]
@MrPetovan and how can there be more information? There are postings when I get a notification about a mention that does not happen but it turns out they are comments on comments to a comment of mine.

**Comment by annando** [comment]
So the issue is that someone is commenting on a comment to your post? Then it is most likely that you got mentioned invisibly. That's a kind of expected behaviour. But I do understand your point as well.

**Comment by annando** [comment]
See #7964. This issue is planned for the next release and would be the base for a new notification class that @nupplaphil is planning to work at. Then we will cover this issue. So I would like to move this issue to the next milestone.
