### ISSUE TITLE
Security: Escape user-submitted content in templates

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6208]
~~@annando started to add escaping in #6204~~

~~Here's a worksheet to track what's done and what's left: https://ethercalc.org/hpekpx3ns7sq~~

~~Basically, escaping in Smarty means filtering a variable with the [`|escape` modifier](https://www.smarty.net/docsv2/en/language.modifier.escape).~~

~~- Escaping HTML : `<p>{{$var|escape:htmlall}}</p>`~~
~~- Escaping a URL attribute:  `<a href="{{$var|escape:urlpathinfo}}">...</a>`~~
~~- Escaping an URL as a query string parameter: `http://example.com/?url={{$var|escape:url}}`~~
~~- Escaping Javascript code: `<script>{{$var|escape:javascript}}</script>`~~
~~- Escaping email address: `<a href="mailto:...">{{$var|escape:mail}}</a>`~~

However, there is a [template-wide setting](https://www.smarty.net/docs/en/variable.escape.html.tpl) to auto-escape variable à priori:
```php
$smarty->escape_html = true;
```
If this setting is active, we may want to use the `{{$var nofilter}}` modifier for variables holding expected HTML.

**Comment by annando** [comment]
Auto-escaping sounds nice - but will need a lot of testing as well. And since changing this value doesn't trigger a recompile of the template, we cannot switch easily between these values for testing purposes.

I guess that escaping the url would now most likely result in double encoded url?

And concerning this ```{{$var|escape:htmlall}}``` luckily we only need to type ```{{$var|escape}}``` to trigger a ```htmlspecialchars``` which is enough for security purposes.

**Comment by MrPetovan** [comment]
It means that no more escaping needs to be done to the specified file in the specified theme.

> I guess that escaping the url would now most likely result in double encoded url?

I don't know for sure.

> And concerning this {{$var|escape:htmlall}} luckily we only need to type {{$var|escape}} to trigger a htmlspecialchars which is enough for security purposes.

If you can vouch for it!

**Comment by annando** [comment]
I tested the escaping with some harmless XSS in a contact's name. So I say that it will be enough. I looked inside the code and also saw that we can prevent double encoding. I'm currently unsure, how to trigger it, but should we do yo?

**Comment by MrPetovan** [comment]
Should we do yo?

**Comment by annando** [comment]
Preventing double encoding does mean that we don't get problems with stuff like ```&amp;amp;``` - but on the other hand we won't see the places where we double encode, so we can't fix it.

**Comment by MrPetovan** [comment]
No, we will see the errors, the display is wrong and URL with query parameters (like in `/network`) will be wrong as well.

**Comment by annando** [comment]
Are we speaking of the same? I meant the double encoding - I guess you meant the general escaping?

**Comment by MrPetovan** [comment]
I thought you meant we won't see double encoding errors.

**Comment by annando** [comment]
Disabling double encoding should in fact avoid the double encoding errors.

But we possibly should have an eye on ```$smarty->escape_html = true;``` as well.

**Comment by MrPetovan** [comment]
This setting sounds like way less work overall.

**Comment by MrPetovan** [comment]
I've been enabling `escape_html = true` on my server. As a result, I removed almost all explicit `|escape` calls, and I'm working backwards to only enable unescaped content when it is necessary. I have to go through all Friendica pages so I may miss some instances.

**Comment by annando** [comment]
Is it something for the RC? I really would like to postpone it to the next develop, since I guess that we will need some time to make sure that all fields are unescaped that have to.

**Comment by MrPetovan** [comment]
No, it's security, and the RC phase is the best moment to spot escaping issues while many eyes are on it before the release.

**Comment by annando** [comment]
How have you checked, which fields needs to be unescaped and which not?

**Comment by MrPetovan** [comment]
Visual check, HTML text appears when a variable should be unescaped. In this regard it is more striking when there's an issue than the other way.

**Comment by MrPetovan** [comment]
Closed for release.
