### ISSUE TITLE
[AP] Can't import a post using Mastodon search

### ISSUE THREAD

**Issue by drequivalent** [friendica/friendica#6212]
### Expected behavior
When giving a link to Friendica post to a Mastodon search (like this: "https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389") it should fetch and "find" this post then let the user interact with it.

### Actual behavior
The search turns up empty

### Steps to reproduce the problem
On Mastodon copy a link to Friendoca post ("https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389" for example)

### Friendica version you encountered the problem
Whatever @MrPetovan is running, which is 2018.12-dev

**Comment by annando** [comment]
Just to clarify: This is not a bug, but it would be a nice feature.

**Comment by tobiasd** [comment]
Is this really a bug? For me it sounds more like a feature request to support a feature of Mastodon.

**Comment by drequivalent** [comment]
AFAIK, it's not a feature of Mastodon specifically, rather than a standard. A lot of social engines work by fetching (and making available for fetching) messages via Search (which basically sends a GET request with Accept: application/activity+json, which returns the post in AP syntax). Try:

```
curl -sH "Accept: application/activity+json" https://mastodonsocial.ru/@drequivalent | jq
curl -sH "Accept: application/activity+json" https://pleroma.site/notice/9085426 | jq
curl -sH "Accept: application/activity+json" https://share.tube/videos/watch/a7c9b55f-1f68-44eb-a3ed-2a9cd6782e39 | jq
curl -sH "Accept: application/activity+json" https://prismo.news/posts/125 | jq
curl -sH "Accept: application/activity+json" https://write.as/franklyfrank/the-right-recipe-35 | jq
```
Friendica unfortunately, doesn't do that, this request turns up empty:
```
$ curl -sH "Accept: application/activity+json" https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389 | jq
```

So, yeah, I think it's kind of a bug.

**Comment by MrPetovan** [comment]
This seems to come from the fact that we are redirecting to https://friendica.mrpetovan.com/objects/735a2029-105b-feae-774e-519940805389 when we receive the `Accept: application/activity+json` header,

The following command works (notice the `L` flag) for example.
```
curl -sLH "Accept: application/activity+json" https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389
```

Isn't Mastodon following redirections?

**Comment by drequivalent** [comment]
Probably not, that's for @Gargron to say

**Comment by MrPetovan** [comment]
I submitted a question at the Mastodon repo: https://github.com/tootsuite/mastodon/issues/9390

**Comment by drequivalent** [comment]
Good. I wonder if there's some default behavior on that. If not, I think it must be codified somewhere then, it's kinda important.
