### ISSUE TITLE
 Deselect all contacts in Frio

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6213]
I mean to remember that if I have created a post, I could deselect all contacts under the "access rights" tab with a click on "For everyone visible". That is not possible anymore.

**Comment by MrPetovan** [comment]
No one should be selected.

**Comment by JonnyTischbein** [comment]
Does it make sence to create a post visible for no one or should it be impossible to share that post?

**Comment by MrPetovan** [comment]
No, but it's a good starting point to add people one by one instead of having to deselect everyone one by one.

**Comment by JonnyTischbein** [comment]
But if you select a contact to show or dont show "show for everyone" is disabled

**Comment by copiis** [comment]
Just tested. When I select a contact, all others are deselected. Is that how it should work? Is both equal in Frio and Four.
It's just a bit confusing.

**Comment by MrPetovan** [comment]
Good to know, however this still is a regression, this button used to be a toggle.

**Comment by JonnyTischbein** [comment]
> Just tested. When I select a contact, all others are deselected. Is that how it should work? Is both equal in Frio and Vier.
> It's just a bit confusing.

Can't reproduce it

![screenshot_2018-11-28_17-39-45](https://user-images.githubusercontent.com/10757520/49166949-a791cf80-f334-11e8-8dcb-fe1d5e3e3b44.png)

**Comment by copiis** [comment]
Well the "Visible to everybody" button becomes grey

**Comment by JonnyTischbein** [comment]
Ahhh I though all other means if you select a show all other shows are removed

**Comment by AlfredSK** [comment]
What I see in the image shared by @JonnyTischbein is the intended behavior. Or isn't it? If you select a contact or a group you create a private post not visible to everyone. So the button "visible to everyone" is deselected (grey).

**Comment by AlfredSK** [comment]
Btw. I just tried the following in frio:
Select a contact or a group: the button "visible to everyone" is deselected (grey)
Unselect the contact or group: the button "visible to everyone" is selected (green)
- or -
Select the button "visible to everyone": the user or group gets unselected (grey)

Looks ok to me.

**Comment by copiis** [comment]
Then all the buttons, next to the contacts, should be set to green as standard and if you click the button "visible to everyone", then everything will turn gray and you will only select the contacts to receive the post.

**Comment by AlfredSK** [comment]
> Then all the buttons, next to the contacts, should be set to green as standard

But this would be a private post to all your contacts only - not public to everyone. That's a different thing from my point of view.

**Comment by copiis** [comment]
But all that is not intuitive ...

**Comment by MrPetovan** [comment]
No, but making it intuitive would require a bigger rework.

**Comment by MrPetovan** [comment]
Apparently this isn't a regression but expected. This rekindles my will to redo the ACL selector with better UX like I mentioned here: https://github.com/friendica/friendica/issues/1430#issuecomment-416005116
