### ISSUE TITLE
Footnote in Impressum leeds to unusable site

### ISSUE THREAD

**Issue by ddeimeke** [friendica/friendica#6215]
### Expected behavior

Site up and running.

### Actual behavior

Empty page.

### Steps to reproduce the problem

Add a footnote with the Impressum plugin.

### Friendica version you encountered the problem

2018.09

### Friendica source (git, zip)

Git

### PHP version

7.2

### SQL version

MariaDB 5.5.60

**Comment by MrPetovan** [comment]
Hi, the addons version and Friendica version should match at all times, please checkout the friendica-addons `master` branch whose version is set to match Friendica version `2018.09`.

**Comment by ddeimeke** [comment]
Perfect hint: Works again.

Thank you!
