### ISSUE TITLE
Block server from shell

### ISSUE THREAD

**Issue by JeroenED** [friendica/friendica#6245]
(Ref: https://pirati.ca/display/ec054ce7-405c-0de9-08b1-9fb109363515)

Because of a server block request and myself playing chess again, I started wondering if it's possible to add a node to the blocked servers list from the console.

While thinking ahead I concluded it would be nice to have these related features as well in console:
- get currently blocked servers
- Remove a blocked server (or remove all)

**Comment by MrPetovan** [comment]
It's entirely possible, however what is the expectation for the blocked server list? Should it be human readable or machine-parseable or both?

**Comment by JeroenED** [comment]
A list with 1 blocked server per line.

    $ php bin/console blocked-servers
    social.example.com
    friendica.mrpetovan.com
    
    $ php bin/console blocked-servers add social.jeroened.be "I hate myself"
    OK
    
    $ php bin/console blocked-servers remove social.jeroened.be
    OK

**Comment by JeroenED** [comment]
If it's too easy, you can add this one as well:

````
$ php bin/console blocked-servers --details
Node                          Since            Reason
social.jeroened.be            15-10-1991 14.36 I hate myself
friendica.mrpetovan.com       19-05-2010 23.56 Because I can
forum.friendi.ca              23-05-2005 12.45 I don't need support
````

**Comment by nupplaphil** [comment]
@JeroenED The "since" isn't possible yet, because we don't save the timestamp. But the rest works as suggested after merging #7018 ;-)

**Comment by JeroenED** [comment]
Closed since #7018 is merged

**Comment by MrPetovan** [comment]
Fixed the milestone as well.

**Comment by AlfredSK** [comment]
Ha! I just misread the headline as 'block server from hell'. :)

**Comment by rebeka-catalina** [comment]
On 2019.07.07, Steffen K9 wrote:
> Ha! I just misread the headline as 'block server from hell'. :)

:-D
