### ISSUE TITLE
jotShare is not defined: resharing from single post view broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6246]
### Expected behavior
Resharing an item should be also possible when viewing the item in single post view (/display/...).

### Actual behavior
When I try to reshare this post...
https://libranet.de/display/0b6b25a8966e7a3fc5f6cf6f405fadfef2db52ce
...nothing happens. The modal window for sharing stuff in frio doesn't open.

I get an error in my browser console instead:
`ReferenceError: jotShare is not defined`

Is that a template problem?

It is possible to share the very same item from my network stream. So, the error only occurs when I'm on the /display/... page.

### Steps to reproduce the problem
Open an item's display page and try to reshare it.

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
I can't reproduce, I can share this exact post on my node from the following URL: https://friendica.mrpetovan.com/display/0b6b25a8966e7a3fc5f6cf6f405fadfef2db52ce

**Comment by AlfredSK** [comment]
Hmm. I tried some other posts w/o any issue. But the one I mentioned throws the error I reported evrytime I try to reshare it from /display/...

I just tried to reshare other posts from "Nextcloud News....". It's not possible. I always get 'jotShare is not defined'. The accounts is hosted on my node.

**Comment by AlfredSK** [comment]
Ok. That's weird.
I logged in to another account on the _same node_. I cannot reshare the post (jotShare is not defined).
Then I logged in to another account on _another node_ (just like you did) and it works.
I also can reshare it when I try it as the Nextcloud News account itself.

Is there some authentication involved when I try it on the same node? I don't think so but I have no other explanation. :-)

**Comment by tobiasd** [comment]
I could not reproduce this in the vier theme.

Note however that the sudden appearance of the "new posting" editor area on the page is somehow surprising ;-)

**Comment by AlfredSK** [comment]
This is one of the weird issues with the 'display' page. There are the 'profile not found' errors, the weird 404s, the (sometimes) missing like/comment/share buttons and so on.
All these issues seem to have something to do with permissions/authentication/session. It seems like Friendica is "thinking" the user is a visitor when calling the .../display/... page of an item. And these problems do only occur when the user is on the same node as the author of the post.

The good thing is, I cannot reproduce this anymore. Just like the 404s this has been fixed unintentionally or magically.

I think I will close it. If the issue reoccurs we can reopen it.
