### ISSUE TITLE
Optimize crawler traffic

### ISSUE THREAD

**Issue by wiktor-k** [friendica/friendica#6248]
Hello,

I'm not sure where to log this issue but if it's not an appropriate place please point me to the right one.

### Expected behavior

Crawler looks for one URL at most.

### Actual behavior

Crawler scans 12 different URLs every couple of seconds/minutes. This multiplied by number of different servers running Friendica generates a huge traffic load. And I'm not even running any "fediverse" software :(

### Steps to reproduce the problem
Grep for friendica in HTTP server logs. Sample hits:
```
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /.well-known/host-meta HTTP/1.1" 200 202 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /poco HTTP/1.1" 404 1366 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET / HTTP/1.1" 200 6935 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /api/statusnet/version.json HTTP/1.1" 200 16 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /api/gnusocial/version.json HTTP/1.1" 200 12 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /api/v1/instance HTTP/1.1" 200 260 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:50 +0000] metacode.biz "GET /siteinfo.json HTTP/1.1" 404 1366 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:51 +0000] metacode.biz "GET /api/statusnet/config.json HTTP/1.1" 200 672 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:51 +0000] metacode.biz "GET /statistics.json HTTP/1.1" 404 1366 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:51 +0000] metacode.biz "GET /.well-known/nodeinfo HTTP/1.1" 200 175 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:51 +0000] metacode.biz "GET /friendica/json HTTP/1.1" 404 1366 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
[11/Dec/2018:10:27:51 +0000] metacode.biz "GET /friendika/json HTTP/1.1" 404 1366 "-" "Friendica 'The Tazmans Flax-lily' 2018.12-dev-1290; https://friendica.philipp.info" "*/*" TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
```

(there are almost 4000 hits from today only and it's not yet noon here!)

### Friendica version you encountered the problem
2018.12-dev-1290 I suppose, I don't use it.

**Comment by annando** [comment]
At Friendica we do have a mechanism to detect the server version and software that is running on the other side. To be able to do so, we have to probe some different endpoints. This all should be endpoints that don't create much load on the queried system. Do you know if any of these calls create a significant load on your system?

**Comment by wiktor-k** [comment]
Thanks for the reply @annando!

> At Friendica we do have a mechanism to detect the server version and software that is running on the other side. 

I understand why do you do that but as a server administrator I feel this is a little bit excessive. For example I - as a server administrator - can't *opt out* of this scanning in any way. No `robots.txt` etc. And I didn't even *opt in* here.

Some time ago I proposed that [all fediverse systems use one file](https://github.com/jhass/nodeinfo/issues/23#issue-325316573) for discovery and that'd decrease the load 12x.

Fortunately Friendica uses User-Agent properly so I always have the "ultimate solution" of just dropping traffic in the load balancer but every time I encounter an issue like that I first seek for a good solution. Good solutions will solve the problem for everyone, instead of hiding it just for me.

> Do you know if any of these calls create a significant load on your system?

They create noise in my logs, everytime I have to `grep -v Friendica`.

**Comment by annando** [comment]
We are using this also for avoiding to deliver content to servers that aren't existing anymore. By blocking such calls this could create communication issues.

But it should be possible to reduce the amount of system specific queries. When we already detected some server type in the past, we could leave out some calls that aren't in use for this type of network at all. Only when this fails, we could switch to the larger probing.

**Comment by wiktor-k** [comment]
> We are using this also for avoiding to deliver content to servers that aren't existing anymore. By blocking such calls this could create communication issues.

That's good to know.

> But it should be possible to reduce the amount of system specific queries. When we already detected some server type in the past, we could leave out some calls that aren't in use for this type of network at all. Only when this fails, we could switch to the larger probing.

Excellent idea! Actually I would be interested in indicating "no server type" as I'm not planning to run any fediverse software but reducing traffic would also be very welcome.

For example Friendica first scans for `/.well-known/host-meta`, would it be possible to indicate `"noFediverseHere": true` there? ;)

Another thing that I saw is the scan for 12x URLs happens *every minute*, is that Friendica default that maybe could be tweaked?

**Comment by MrPetovan** [comment]
So you're the one running `metacode.biz` and messing up federation statistics? You actually are running a "fediverse" software with the following fake stats page: metacode.biz/api/v1/instance

I guess that the ransom of success then. Nothing for us to do on Friendica. Good day sir.

**Comment by wiktor-k** [comment]
@MrPetovan, I know it's hard to believe but *I do not want to mess up statistics*. That's why I created this issue. My problem is ["I can't opt out of this scanning in any way. No robots.txt etc. And I didn't even opt in here."](https://github.com/friendica/friendica/issues/6248#issuecomment-446172208)

**Comment by annando** [comment]
You kind of opted in by providing the endpoints that indicate that you offer these federate services. If you don't offer a federated social network then you shouldn't offer these endpoints, I think. In difference to web crawlers that search for content for search engines, this scanning is part of the regular communication process between the servers. So it doesn't make sense to be able to "opt out" of this.

Concerning the number of requests: Every Friendica server does a regular probing. Since there are hundreds of servers, there is some amount of queries. But if you would offer a federated service, the number of these queries wouldn't be significant compared to the regular communications that occur between the servers.

**Comment by wiktor-k** [comment]
> If you don't offer a federated social network then you shouldn't offer these endpoints, I think.

Good point, I'll modify these endpoints to return HTTP status `410 Gone` ([the spec notes](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.11) that "This condition is expected to be considered permanent.").

Thanks @annando!

**Comment by AndyHee** [comment]
Hello @wiktor-k thanks for your input! Are you running a Mastodon instance on this `metacode.biz`?

**Comment by wiktor-k** [comment]
Hi @AndyHee, nope. I'm actually doing low-level ActivityPub development (writing client and server myself from the spec, and I did [fix some issues with AP support in Mastodon](https://github.com/tootsuite/mastodon/pull/7488)). It's probably due to my experiments why my server name appeared in crawlers in the first place...

**Comment by AndyHee** [comment]
I see @wiktor-k . That sounds interesting! What kind of experiment did you run that created this endpoint?

**Comment by wiktor-k** [comment]
> What kind of experiment did you run that created this endpoint?

The endpoint was part of an experiment I ran with an author of another crawler tool. I "fuzzed" their crawler with different sets of data disclosing bugs in the code (e.g. I set `version` to a string) they fixed the crawler, rinse and repeat. (I also had a nice low-level e-mail chat about fediverse protocols and schemas with them, it doesn't happen every day! :) )

**Comment by AndyHee** [comment]
Did it work?

It'd be great to give us a heads up for your next experiment. I'm copying in @JeroenED who has a lot of expertise with crawlers. You might be able to give us some advise on a range of issues.

**Comment by wiktor-k** [comment]
Yeah, we did several rounds of these, one test cycle spanned days and they fixed a lot of issues. It was some time ago but it seems the files had some [less-than positive site-effects](https://libranet.de/display/cd9f100a-135c-0d97-6d76-234106564370). Well in hindsight it is obvious, I should've deleted them quickly :disappointed:.

> It'd be great to give us a heads up for your next experiment.

No worries, I don't do experiments without consent, this one getting out of scope is already bad.

> I'm copying in @JeroenED who has a lot of expertise with crawlers. You might be able to advise us on a range of issues.

Yeah, I observed some anti-crawler mechanisms in the wild myself, like redirecting to a big file ([`CURLOPT_PROGRESSFUNCTION`](https://stackoverflow.com/a/17642638) may be a good idea). I see you have redirect limit and timeouts already :+1:

**Comment by MrPetovan** [comment]
Thanks for the elaboration!

**Comment by wiktor-k** [comment]
No problem, sorry for the confusion.

**Comment by MrPetovan** [comment]
And sorry I thought this was malicious.

**Comment by AndyHee** [comment]
Thanks @wiktor-k . Have a look at the Friendica code when you have some time. You might be able to make some nice contributions here. 😊

**Comment by wiktor-k** [comment]
Thanks for the invitation @AndyHee, I already took a look at it locally, looks cleanly designed on a first sight :)

**Comment by annando** [comment]
@wiktor-k don't look into the older parts of the code (folder "mod" and "include") or you will have another opinion :grinning:
