### ISSUE TITLE
Drag&Drop for images and files when creating new content

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#6249]
With FRIO, the inclusion of images in contributions requires a certain amount of planning. 
First the image has to be uploaded to the server.
Then edit a text once. Then you have to go to the picture gallery again to select the picture and so on.

No matter in which order you perform these activities, it takes many clicks again and again.
Working with it is unergonomic and error-prone. Especially for Neulinde this is very confusing and partly deterrent.

It should therefore be possible to interlock the existing technology better with each other.

Simple solution: 
- The editor is supplemented by an editing icon for images.
- This icon opens the image gallery below the edited text or as a popup.
- From the picture gallery 1-n pictures can be taken over into the text
- In addition, the upload of new images is supported. 
- The Drag&Drop function from "photos/~/upload" can be used here.
- If an image is dropped into the upload field, it is uploaded to the image database and can be selected for the editor.

More complex solution:
- Images can be integrated directly into the editor via drag&drop and the image is uploaded to the image database.

**Comment by MrPetovan** [comment]
> - The editor is supplemented by an editing icon for images.
> - This icon opens the image gallery below the edited text or as a popup.
> - From the picture gallery 1-n pictures can be taken over into the text
> - In addition, the upload of new images is supported.

I don't understand, these points describe the current system. See following screenshots of the location of the buttons allowing to bring up the gallery where you can upload new pictures while you write your post/comment:
![friendica_comment_box](https://user-images.githubusercontent.com/925415/49799263-85c02180-fd12-11e8-97b6-69e5ce542f5f.png)
![friendica_share_box](https://user-images.githubusercontent.com/925415/49799264-85c02180-fd12-11e8-8321-913500aae6b0.png)

**Comment by loma-one** [comment]
The user guidance is already solved in different ways.
There is also a difference, if I have to switch from the editor to another tab, or if I call a function from the editor (in this case the picture gallery).

It would already be a profit, if the picture gallery can be started in the same way, as with the comments solved.

**Comment by loma-one** [comment]
if you see the dialogs standing on top of each other, you will notice that the icons have different sequences ;)

**Comment by loma-one** [comment]
Wouldn't it be worth considering whether creating a new content behaves the same as creating a comment?
For me the usability for comments is clearer and smarter, because it works without the TAB.

**Comment by annando** [comment]
@loma-one a small hint: You can edit your comments, that makes the communication less cluttered.

@MrPetovan I think it would be an improvement, if users simply could use drag&drop to upload pictures in comments and posts. So yes, there currently is some way, but we can make it more obvious.

**Comment by MrPetovan** [comment]
I fully agree with you, but unfortunately this isn't trivial to solve.

**Comment by loma-one** [comment]
Okay, I'm just a user, and I don't pay enough attention to that. For me everything is quite simple ;)
At this point a big thank you for your super ingenious work!

**Comment by rabuzarus** [comment]
Sorry, I must confess, I haven't understand the problem..

As far as I know drag&drop for photo upload is only supported via addon. So it isn't a standard behavior.

And what is is confusing when writing a post?
1.) Open the new post modal
2.) Writing text
3.) Switch to browser tab
4.) Upload photo (Frio does also support to upload the picture into a specific album via browser)
5.) Select photo (frio will switch automatically to the message tab and insert the photo)
6.) click on permission and set the permision
7.) click on message and send your message

If you ignore the first point (opening the new message modal), these are the same steps like for comments or when you using the vier theme. The only difference is that you you use icons instead of modal tabs.

The `new message` modal in Frio was inspired by twitter because I found it very annoying to have to scroll to the top every time when I wanted to write a new message

**Comment by MrPetovan** [comment]
The main difference between the comment form and the new post form with regard to uploading media is the "Browser" tab that's counter-intuitive compared to the expected "Attach" button that's present in the comment form.

**Comment by annando** [comment]
@rabuzarus The suggested method - instead of your 7 list points is:
1. Write a post/comment
2. Drag&Drop the picture into the post/comment box
3. The picture is automatically uploaded and inserted into the post/comment

This would be a much easier way.

**Comment by rabuzarus** [comment]
@annando [semi-OT]
1.1 open file manager
1.2 go to directory with picture
1.3 drag the the file manager to an area of the monitor where it doesn't hide the upload/text field
[if you have an file manager already open - like I always have - you need to move also the file manager to the the virtual desktop with the browser]
;-)

But in this case we should move the js upload addon to the core

**Comment by MrPetovan** [comment]
> 1.1 open file manager
> 1.2 go to directory with picture
> 1.3 drag the the file manager to an area of the monitor where it doesn't hide the upload/text field
> [if you have an file manager already open - like I always have - you need to move also the file manager to the the virtual desktop with the browser]
> ;-)

Unfortunately this still is more familiar than the "Browser" tab and the media modal so it would be preferred anyway.

**Comment by annando** [comment]
We need both ways.

**Comment by loma-one** [comment]
![Drad&Drop](https://pixelfed.social/storage/m/2c947e771f8c9b728a8908ee906850bafe029c8f/6f82e2595364fcd0613ddf8e75aa655a9dad43a9/hYnAlMTYhBxbZx73AxUw3uojaIax56CpXglof0IQ.png)

![Text](https://pixelfed.social/storage/m/2c947e771f8c9b728a8908ee906850bafe029c8f/6f82e2595364fcd0613ddf8e75aa655a9dad43a9/hPf5HVY1u8vIWzfYbKfLFaNTGqY7nDtBA7V1HO9G.png)

**Comment by MrPetovan** [comment]
GitHub:
![github_comment_box](https://user-images.githubusercontent.com/925415/50044317-df488900-004f-11e9-96ee-4dbdc6791e54.png)
Gmail:
![gmail_compose_window](https://user-images.githubusercontent.com/925415/50044318-e2437980-004f-11e9-8673-278d358fa507.png)

**Comment by rabuzarus** [comment]
https://framagit.org/hubzilla/core/blob/master/view/tpl/jot-header.tpl#L474-505

**Comment by MrPetovan** [comment]
Update: the drag and drop should be added to the composer page as well: #7937

**Comment by loma-one** [comment]
Duplicate from https://github.com/friendica/friendica/issues/11825
