### ISSUE TITLE
Infinite scrolling leads to display problem

### ISSUE THREAD

**Issue by ddeimeke** [friendica/friendica#6254]
### Expected behavior

Behave like in 2018.09

### Actual behavior

After loading new posts, the left column doubles leaving less space for the postings.

### Steps to reproduce the problem

Use the key "j" to see new posts until you come to the end, after load of new articles the problem occurs.

### Friendica version you encountered the problem

This is Friendica, version 2018.12-rc that is running at the web location https://friend.d5e.org. The database version is 1291, the post update version is 1281.

### Friendica source (git, zip)

Git

### PHP version

PHP 7.2.13

### SQL version

MariaDB 10.3.11

**Comment by MrPetovan** [comment]
Can you please post a screenshot of this behavior?

**Comment by ddeimeke** [comment]
<img width="1366" alt="png-bild" src="https://user-images.githubusercontent.com/1115364/49878664-6ca99480-fe28-11e8-859b-a4925ff2c059.png">

**Comment by AlfredSK** [comment]
I had the same issue after switching to RC branch. But after a Shift+Reload (refresh browser cache) it didn't occur anymore.

**Comment by ddeimeke** [comment]
Refresh did not work for me, but deleting the whole cache did the trick.
