### ISSUE TITLE
Connect Button appears on always connected forums

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#6255]
### Expected behavior
If i visit a connected forum the button _Connect_ should not appear

### Actual behavior
The button _Verbinden/Connect_ appears, but i am always connected with the forum
![friendica-kontakt](https://user-images.githubusercontent.com/12498438/49899014-d3e03c80-fe5a-11e8-9c59-569a7e022ee9.png)

### Steps to reproduce the problem
Visit a connected forum page

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.13

### SQL version
10.0.34-MariaDB

**Comment by annando** [comment]
I'm not sure if this is related. This whole remote thingy is a ... interesting ;-)

**Comment by MrPetovan** [comment]
It sounds like the relationship isn't correctly checked the same way the "Connect" button was systematically displayed.

**Comment by MrPetovan** [comment]
Closed via #6256
