### ISSUE TITLE
Create Contact Groups

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#6259]
### Expected behavior
Go to `/contact` -> _View Contact_, the contact widget should appear on the left side (theme Frio) and you can create a new group.
![friendica-gruppen](https://user-images.githubusercontent.com/12498438/49944252-4fd59580-feea-11e8-849b-0af36664760c.png)

### Actual behavior
With a new Account with no existing groups, no contact widged appear and it is not possible to create a new group. 

### Steps to reproduce the problem
Create a new Account, add a contact and try to create a contact group

### Friendica version you encountered the problem
Friendica 2018.12-rc - 1291

### Friendica source (git, zip)
git

### PHP version
PHP 7.2.13

### SQL version
10.0.34-MariaDB

Discussion (in german):
https://forum.friendi.ca/display/962c3e10-155c-124f-2fa6-be0672399412

**Comment by MrPetovan** [comment]
Closed via #6264
