### ISSUE TITLE
Issues with new Backend Storage Engine feature

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6263]
Follow-up to #6180

```
Fatal error:  Class Friendica\Model\Storage\SystemResource contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Friendica\Model\Storage\IStorage::getOptions, Friendica\Model\Storage\IStorage::saveOptions) in src/Model/Storage/SystemResource.php on line 15
```
Fixed in https://github.com/friendica/friendica/commit/b029774b344b1907f78dece6c909b113abf2661a

**Comment by MrPetovan** [comment]
Since I fixed this issue and without changing anything else, many avatar pictures are now displaying the dreaded red circle. It concerns both new contacts and long-time ones.

**Comment by fabrixxm** [comment]
uops. sorry.

mmmmmmh.. avatar pictures should not show red circle...

**Comment by fabrixxm** [comment]
> mmmmmmh.. avatar pictures should not show red circle...
mmmmmmh.. avatar pictures should not show red circle...
No true, you can

But why you get it it's the question now.. 
You get the red circle because in Module/Photo.php:71 we call `Model\Photo::getPhoto` with requested resource id and scale and in Model\Photo.php:140 we get "false"..

But before anything, check if file exists in 'photo/' subfolder...

**Comment by AndyHee** [comment]
This might be possibly related to this: https://github.com/friendica/friendica/issues/6266.

The error message points to this line in admin.php:1537 with code relating to storage backend.

**Comment by MrPetovan** [comment]
Still getting red circles in many avatar places.

More details:
- `/crepair` doesn't fix red circle image.
- In a thread by a single author, their picture can have a red circle in the top-level post but not in their own replies.

**Comment by fabrixxm** [comment]
can you:
- open the red circled image in a new tab
- add `var_dump($photo); die();` after src/Module/Photo.php#L71
- shift-reload the tab, check you  don't get the image again. You should get  "false" or an array.
if you get the image again, you have it on disk under  `./photo/`.
if you get the array... you shouldn't ...
if you get "false", could be the query at src/Model/Photo.php#L126 or at src/Model/Photo.php#L140

if fails the first query.. you could not have a photo with given resource-id, which I don't know if it can be a normal case with profile photos.

if fails the second query.. again, you don't have a photo with that resource-id and given scale (or less) or something is wrong with some permission fields.. 

At this point a cause could be in code that generate the various profile pictures................

**Comment by MrPetovan** [comment]
Since I've removed the feature from the RC branch and that I'm actively debugging #6262, I won't be able to do that probably until the stable release.

The main point of my tests is that I stayed on the default SystemResource storage backend.

**Comment by AndyHee** [comment]
`(in fact is not selectable as backend in admin page)`

I changed from Legacy mode to Backend and ../admin/site is not accessible. I didn't add any sample backend in addons.

**Comment by AndyHee** [comment]
@fabrixxm Yes, it works again. Thanks!

I switched to `Database` now. I will attempt to move the storage later. Where will the DB be actually located?

**Comment by AndyHee** [comment]
Tried this `$ bin/console storage move` and got this:

```
PHP Warning:  Error while sending STMT_CLOSE packet. PID=22284 in /var/www/friendica/src/Database/DBA.php on line 585
[Error] Database storage failed to insert data
```

Some of the node's PHP info here: https://paste.ee/p/I9pWF

**Comment by nupplaphil** [comment]
This one would be very interesting for the docker repo, because I would add a docket feature to mount the storage outside of the common `/var/www/html` path. This will increase security and maybe a little bit the db-performance :)

**Comment by ingoj** [comment]
Basically it finally worked for me after invoking the command several times: 
```
# sudo -u www-data bin/console storage move 
Moved 17057 files
```
But I guess this is a general issue that should be solved for release, so I keep this issue open until it is closed or merged with the other issue.

**Comment by MrPetovan** [comment]
If there isn't any further issue with the new backend storage engine feature than #6778, then I will close here.
