### ISSUE TITLE
Frio: "justifyPhotos" breaks photos page

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#6268]
in `develop`, not in `2018.12-rc`

open `/photos/<user>/<profile photos album>`

The gallery is initially loaded correctly, then when javascript kicks in, most of the photos are replaced with the Red Circle.

Upon inspection, the Red Circle images have `src` that points to `/photo/<id>-4-2.jpg`  (or similar)
Note the double size definition.

commenting out from line 441 to line 447 in [view/theme/frio/js/theme.js](https://github.com/friendica/friendica/blob/dd7d556c86b762045220fbda6e28d97c72e91347/view/theme/frio/js/theme.js#L442-L447) fix the issue.

Looks like the js is adding a suffix where it should not.

as said, in `2018.12-rc` it works as expected.

see https://kirgroup.com/photos/fabrixxm/album/466f746f2064656c2070726f66696c6f

**Comment by MrPetovan** [comment]
`-4` isn't registered in the `justifyGallery` call as a valid scale suffix so it isn't taken into account. According to my photo table, scale goes from 1 to 6 and should be mirrored in the `sizeRangeSuffixes` array.

**Comment by fabrixxm** [comment]
it works on `2019.01-rc`, or better: it works on your `bug/6334-escape-get-app branch`
