### ISSUE TITLE
Edit of forum posts doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6276]
### Expected behavior
When I edit a forum post the changed text should be delivered to and displayed on the forum node. Also the edit should be distributed to all recipients (members of the forum).

### Actual behavior
When I edit a forum post the changed text is displayed locally but isn't delivered to to forum node. Because of that also the recipients don't get the edited version of the post.

### Steps to reproduce the problem
Write a forum post to e.g. `!helpers@forum.friendi.ca`. Edit your post. Go to the status page of the helpers account and have a look at your post.

I did a test with my main node and the forum node:
https://libranet.de/display/0b6b25a8-415c-1687-ed43-b42567516948
https://forum.friendi.ca/display/0b6b25a8-415c-1687-ed43-b42567516948

Both nodes are on current RC.

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by hoergen** [comment]
Experienced that I can't edit my own posts any more. 

Maybe this is the same cause?

**Comment by MrPetovan** [comment]
Any error? Steps to reproduce?

**Comment by AlfredSK** [comment]
Do you have a screenshot? Is it that no interaction is possible at all or is only the edit not working?

**Comment by annando** [comment]
Yeah, this is some expected (but unwanted) behaviour. Although you started the forum post, you transfer ownership to the forum account. I still have to think about this case.

**Comment by AlfredSK** [comment]
Ah! I had another suspicion. Thanks for the screenshot.

**Comment by hoergen** [comment]
In my case it wasn't a forum post. It's a completly normal post, visible to everyone aka public.
https://horche.demkontinuum.de/display/2196d4ee-155c-1e2e-3411-161741886621

**Comment by annando** [comment]
Possibly this is related to your weird contact link problem.

**Comment by AlfredSK** [comment]
Yup. I sometimes have this strange behavior too. That's why I asked "Is it that no interaction is possible at all... ?" earlier in this thread.

**Comment by AlfredSK** [comment]
See also: https://forum.friendi.ca/display/0b6b25a8-845c-17d5-f86d-1cf544266276

**Comment by AlfredSK** [comment]
All these errors/bugs (the 404s, the missing like/share/comment buttons, ...) have one thing in common (from my observation): they **only happen on the .../display/... page** of the item - not in the network stream.

**Comment by AlfredSK** [comment]
Maybe somehow the session data gets lost? It's like you are not logged in (Friendica thinks ;-) you're not logged in) because private post -> 404 and other posts w/o interaction buttons just like you were just a visitor.

**Comment by AlfredSK** [comment]
Ok. Checked the state of this issue. Edits are still not showing up on the forum.

**Comment by annando** [comment]
The comment https://github.com/friendica/friendica/issues/6276#issuecomment-449572977 is still valid.

**Comment by MrPetovan** [comment]
Pushing to next release because it doesn't look like it's going to be tackled anytime soon.

**Comment by AlfredSK** [comment]
I edited some _comments_ of forum posts lately (2019.03-rc). Those edits were successfully delivered to the forum and the receivers of the original post.
I'll check what happens when I edit a forum _post_.

**Comment by AlfredSK** [comment]
Ok. Test done. While editing comments is working, editing forum posts still doesn't work. I can edit the post locally but the edit doesn't show up on the forum itself.

**Comment by annando** [comment]
There still is no quick solution to this issue. It affects how forum posts are stored in the system.

**Comment by annando** [comment]
P.S.: Does someone disagree to move this to the next milestone?

**Comment by MrPetovan** [comment]
Nope, let's put this release out already.

**Comment by MrPetovan** [comment]
Not an RC task.

**Comment by annando** [comment]
I'm still lacking a good idea how to solve this.

**Comment by annando** [comment]
Editing of forum posts will only work in combination with transporting the first forum post via ActivityPub. Means: Changing this will make older forum servers not working anymore. If no one disagrees then I will perform this change in the release after this one..

**Comment by tobiasd** [comment]
Means also that diaspora* members of a forum wont see forum postings anymore? Do forums work at the moment with diaspora*?

**Comment by annando** [comment]
Forums don't really work with Diaspora by now. Means: You can't create forum posts on Diaspora. You can answer to them. This would possibly not work anymore.

**Comment by AlfredSK** [comment]
Issue solved. Tested with a comment and the top-level post. Both edits worked locally and have been federated successfully to another Friendica node. Closing...

https://libranet.de/display/85a863ed-5761-5748-d525-7b8335163642
