### ISSUE TITLE
[frio] creating new post dialogue is broken 

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6289]
### Expected behavior
Normal create post dialogue

### Actual behavior
A veeeeeeeeeeeeeeeeery long popup with loooooots of CSS ;)
![00_temp](https://user-images.githubusercontent.com/24474762/50343841-c72da980-0528-11e9-93bc-83af4c2842e4.jpg)

### Steps to reproduce the problem
create new post

### Friendica version you encountered the problem
2018.12-rc, MariaDB, PHP7

**Comment by MrPetovan** [comment]
Related to #6208
Caused by #6262

**Comment by annando** [comment]
Fixed with https://github.com/friendica/friendica/pull/6290

**Comment by MrPetovan** [comment]
Less than an hour between the report and the merge, good job team!

**Comment by hoergen** [comment]
GREAT Thank you ❤️️
