### ISSUE TITLE
addon notifyall: smarty escaping issue

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6296]
### Steps to reproduce the problem
Got to:   
https://example.com/admin/addons/notifyall

**Administration - Addons**

Notifyall - 1.0 : Disable

`Send admin email message to all account holders. <b>-><a href=/notifyall TARGET = "_blank">send now!</a><-</b>`

Author: Mike Macgirvin (Inital Author of the hubbwall Addon for the Hubzilla Project), Rabuzarus 

...

### Friendica version you encountered the problem
2018.12.-rc

**Comment by AlfredSK** [comment]
Haha! I had to escape the line with the issue here because Github editor is repairing the error automagically. :-)

**Comment by annando** [comment]
Leave me some time to breathe ;-)

**Comment by MrPetovan** [comment]
Closed via #6299

**Comment by MrPetovan** [comment]
Part of #6208
