### ISSUE TITLE
smarty escaping issues on picture upload page

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#6297]
![friendica-picture-upload](https://user-images.githubusercontent.com/12498438/50364265-8f962000-056f-11e9-81b3-492819ef3518.jpg)

### Steps to reproduce the problem
Go to _Pictures_ and try to upload a Photo

### Friendica version you encountered the problem
2018.12-rc - 1291

### Friendica source (git, zip)
git

### PHP version
7.2.13

**Comment by AlfredSK** [comment]
...and with 'js_upload' disabled:

![grafik](https://user-images.githubusercontent.com/3656054/50364603-fa942680-0570-11e9-8fc8-cf62c8df9a13.png)

**Comment by MrPetovan** [comment]
Part of #6208

**Comment by MrPetovan** [comment]
Closed via #6298
