### ISSUE TITLE
Accept a new contact (smarty escaping issues)

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#6300]
![kontaktanfrage-genehmigen](https://user-images.githubusercontent.com/12498438/50365666-e7378a00-0575-11e9-99f4-7ce438637014.png)

### Steps to reproduce the problem
Accept a new contact.

### Friendica version you encountered the problem
2018.12-rc - 1291

**Comment by MrPetovan** [comment]
Closed via #6302

**Comment by MrPetovan** [comment]
Part of #6208
