### ISSUE TITLE
Loglevel of failed logins should be 'warning'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6303]
### Expected behavior
Would be great to have failed logins at loglevel 'warning'. This would allow the admin to set the logging to the lowest level and still use fail2ban to protect Friendica against brute force login attempts.
Also, it seems logical to have failed logins on loglevel 'warning'.

### Actual behavior
Failed login attempts are logged to loglevel 'info' and above.

### Friendica version you encountered the problem

2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Wholeheartedly agree, a low-volume "Warning" level would be more informative than the firehose that the other log levels are.

**Comment by annando** [comment]
I don't understand why you dislike 2 GB large logfiles, (2 GB per day) 😬

**Comment by AndyHee** [comment]
So for the new monolog framework (https://github.com/friendica/friendica/pull/6376) the desired level should be `'error'`. Isn't it?

(https://github.com/friendica/friendica/issues/6403)

**Comment by nupplaphil** [comment]
I added `warning` as error level. With the introduction of Monolog, a warning is defined as 
> Exceptional occurrences that are not errors.
>
> Example: Use of deprecated APIs, poor use of an API, undesirable things
> that are not necessarily wrong.
Which fits perfect for login failures.

Alternative, We could add a seperare "security" stream and log security issues in separated files with any level we want :)

**Comment by nupplaphil** [comment]
changed with #6409

**Comment by AndyHee** [comment]
I'm not entirely sure if this could be closed @MrPetovan . If I understand this correctly the level for fail2ban to work is now 'notice'. Isn't? That's very high like the old legacy warning and nothing would have changed. Apologies if I'm misreading this.

I think the way forward is '"security" stream and log security issues in separated files' as @nupplaphil suggested.

**Comment by nupplaphil** [comment]
currently, it is `Logger::warning()`, so it shouldn't create **that** traffic anymore.

But I'm with @AndyHee that a own stream would definitly make it easier to find for fail2ban. If I make everything "right", it should be finished with the next logging PR.

**Comment by AlfredSK** [comment]
Hmm. When on log level `warning` the log file on my node is around 70-80MB per day. And it works flawlessly with fail2ban. So, I think the initial issue is solved.
Should we keep the issue open nonetheless?

**Comment by MrPetovan** [comment]
This issue morphed into something else, so it should either be renamed or closed and another one about adding a separate failed login stream.

**Comment by AlfredSK** [comment]
@AndyHee I'll close this one at this point because the initial issue has been solved.
If you still think another log level is necessary please open a new issue for that. Thank you.
