### ISSUE TITLE
[API][Question] favorites/create failure on global item

### ISSUE THREAD

**Issue by jasoncheng** [friendica/friendica#6305]
i try to add favorite item from [ /api/statuses/networkpublic_timeline ], but it always fail (error code 400).

item table (assume my uid = 1)
(id, guid, uid, gravity, global)
(1, ee0fb620e7170136418848600054b5a3, 1, 0, 1)
(2, ee0fb620e7170136418848600054b5a3, 0, 0, 1)

networkpublic_timeline return [{ id: 2....}] , i must failure on favorites/create; the correct response item should be  [{ id: 1....}] for mark as starred.

so, networkpublic_timeline should return items belong to this user not global one, then starred will work, am i right?

if i try to fix it, anything i should notice ? 

thanks for help

**Comment by annando** [comment]
This shouldn't be a thing anymore.
