### ISSUE TITLE
Another template error when selecting a contact group

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6308]
While doing tests for another issue I found this...

Go to .../group and select one of your contact groups. Looks like the trash can is damaged. :-)

![bildschirmfoto von 2018-12-22 18-58-06](https://user-images.githubusercontent.com/3656054/50377530-240b8b80-061f-11e9-86a9-5c5e7ba6169e.png)

**Comment by MrPetovan** [comment]
Part of #6208
