### ISSUE TITLE
tag completion painfully slow

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6319]
### Expected behavior
When you add a tag while composing a new post or comment in Frio (don't know about other themes) the system tries to display some suggestions for the tag completion. These suggestions must be displayed instantly to be of any use.

### Actual behavior
When your database is huge as mine the tag completion/suggestion takes around 20 seconds. This makes this function not only useless but even looking like a bug.

Imagine you type a tag and then you continue to write your text or some other tags and all of a sudden the tag completion popup shows up around 20 seconds after you typed the tag. 😂

So my suggestion is to add some index for the corresponding query to speed up the tag completion (or whatever works) or remove this function completely.
Another possibility would be to make the tag completion configurable for the node admin. So it could be deactivated on larger nodes (with a small database it works well).

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Yeah, this sucks right now. Pushing this to next release as it is still working, barely.

**Comment by hoergen** [comment]
I only hat this experience on theme "vier". On Frio it works like a charme. 
Mostly used Firefox, but as far as I remember I had the same problem on Chromium (in vier, not in frio)

**Comment by MrPetovan** [comment]
I've experienced the slowness on frio as well.

**Comment by AlfredSK** [comment]
Discussion:
https://forum.friendi.ca/display/0b6b25a8-325c-96b2-fdc6-72c723007417

Possible solution:
```alter table `term` add index `term_type` (`term`, `type`);```

**Comment by MrPetovan** [comment]
This makes perfect sense, let me edit the `config/dbstructure.config.php` file accordingly.
