### ISSUE TITLE
HTML encoding of umlauts in location

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6329]
### Expected behavior
Umlauts (Umlaute in real German) in the location field should be encoded correctly.
`Köln` is the name of the city.

### Actual behavior
I stumbled upon this in utzer's contact card (while looking at a post in single post view) and contact details: `K&ouml;ln, Germany`. 
I have asked 'utzer' about this. On his side it looks right. So it seems to be another encoding/escaping issue.

![bildschirmfoto von 2018-12-26 10-07-02](https://user-images.githubusercontent.com/3656054/50440344-15aac180-08f6-11e9-83c1-6f81c57a276f.png)

![bildschirmfoto von 2018-12-26 09-51-38](https://user-images.githubusercontent.com/3656054/50440189-56eea180-08f5-11e9-9890-fc36a8bc2c48.png)

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by AlfredSK** [comment]
Hmm. I just changed my own profile to a location with umlauts. I don't have the issue locally.
Maybe a false alert. I'll wait for utzer's response...

**Comment by AlfredSK** [comment]
This fix from @annando came faster than expected. I was still exploring the situation with utzer. :-)

**Comment by MrPetovan** [comment]
Closed via #6330
Part of #6208

**Comment by MrPetovan** [comment]
> I was still exploring the situation with utzer. :-)

The problem was that we were expecting BBCode in the `location` profile field. So we were performing BBCode conversion, which produces valid HTML (with special characters already encoded). Then Smarty double-encoded the output, which showed the raw HTML.

@annando solution was to get rid of the BBCode conversion for the `location` and `address` profile fields.

**Comment by AlfredSK** [comment]
And.... fixed. Umlaute 'ö' are looking good again.

**Comment by annando** [comment]
And we really, really should compile a list of fields that should be converted via BBCode.
