### ISSUE TITLE
Wrong Config Linebreaks

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6349]
### Expected behavior

the `*.config.php` should have the common unix linebreak `\n` (LF)

### Actual behavior

the `*.config.php` do have the windows linebreak `\r\n` (CLRF)

### Steps to reproduce the problem

Opening f.e. `local.config.php` for wrong linebreak and `src/App.php` for correct linebreak

### Friendica version you encountered the problem

2018.12-rc

### Friendica source (git, zip)

git

**Comment by MrPetovan** [comment]
Closed via #6352
