### ISSUE TITLE
HTML escaping issue: Profile visibility - profile selector

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6360]
### Actual behavior / Steps to reproduce the problem
Go to the contact details of one of your _Friendica_ contacts. Open the 'profile visibility' accordion...

![bildschirmfoto von 2019-01-01 09-06-53](https://user-images.githubusercontent.com/3656054/50571239-8abe4100-0da5-11e9-89ee-8115506b3ed1.png)

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Part of #6208

**Comment by MrPetovan** [comment]
Closed via #6362
