### ISSUE TITLE
Profiles: HTML escaping issue

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6361]
### Actual behavior / Steps to reproduce the problem
Go to settings -> profiles. There are some escaping issues. See screenshot, please.

![bildschirmfoto von 2019-01-01 10-12-03](https://user-images.githubusercontent.com/3656054/50571568-2ce22700-0dae-11e9-93fa-d449837f2a14.png)

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Closed via #6362
