### ISSUE TITLE
single picture view in gallery has escaped coding issues

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6363]
Another case of escaped HTML coding issues... in the single image view of the gallery.

![friendica_gallery_single_pictureview](https://user-images.githubusercontent.com/433490/50582603-041c6900-0e64-11e9-85eb-5dd37ce752ce.png)

### Friendica source (git, zip)

2018.12-rc

**Comment by MrPetovan** [comment]
Part of #6208 

Next time please include the URL of the page, it makes it easier to track down the faulty template.

**Comment by MrPetovan** [comment]
Closed via #6365
