### ISSUE TITLE
Content blocking on Chromium Latest breaks item containers

### ISSUE THREAD

**Issue by JeroenED** [friendica/friendica#6367]
When using Chromium Latest (currently: 73.0) content blocking breaks view of status update containers. When something like a tweet or some media with tracking is loaded the container is not fully viewed. See screenshot.

![selection_003](https://user-images.githubusercontent.com/6833806/50640278-ae7bb580-0f64-11e9-9cc4-48a152775b92.png)

![selection_004](https://user-images.githubusercontent.com/6833806/50640816-4af28780-0f66-11e9-9720-7e156f7b2adf.png)

To be treated as: we know the issue and we'll see the progress on chromium's side.

## Browser
Chromium Latest (First seen on Mobile and tablet confirmed on pc as well; screenshot from PC)

## Expected behaviour
When a update with external content is loaded the content loads (with regard to user's preference) and the container grows evenly.

## Actual behaviour
When a update with external content is loaded, the content loads (with regard to user's preference), the container grows but the background color does not grow. Moreover the like, comment, share buttons might disappear when mouse is hovered. The behaviour is not limited to only posts with remote content, but when a post with remote content is on the page there will be bugs.

## Workaround
Install chromium stable
refreshing the page could help.

## Friendica version
2018-12-rc

## Server details:
PHP 7.3
MariaDB 10.2

**Comment by MrPetovan** [comment]
Did you try disabling the content blocker?

**Comment by JeroenED** [comment]
I have unknowingly been checking out this issue and can confirm the issue is gone in the latest chromium stable. I cannot tell which built it was solved as I simply didn't know I was still using latest dev build.

**Comment by MrPetovan** [comment]
Good, closing for now!
