### ISSUE TITLE
Change new user registration emails to show nickname as login name, not email address

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6370]
### The current behavior
I recently had a new user who did new user-y things, and wound up registering multiple accounts and not being able to log in on any of them.  I noticed that when we email new users, the account details are sent as:

Site Location: https://social.isurf.ca
Login Name: <the person's email address>
Password: someassignedpassword

It was suggested we have this issue created for change/enhancement in the next release - reference at: https://social.isurf.ca/display/c443a55c285c2e6d048a84e897086828

### What should be the actual behavior

Considering email addresses are not unique to accounts, but the nicknames are, shouldn't we be suggesting to users to use their nicknames to login, instead of email address? Any advanced user who creates a 2nd account at the same email address (on purpose) already has to understand they can't login to the system with their email address any longer (so sayeth the help docs).

### Steps to reproduce the problem

Create an account on a friendica node.

### Friendica version you encountered the problem
2018.09

### Friendica source (git, zip)
git

### PHP version
7.2.9

### SQL version
mariadb 10.1.35

**Comment by MrPetovan** [comment]
Closed via #6371
