### ISSUE TITLE
Monolog - logfile permission denied

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6379]
> @nupplaphil this is a cool new feature by the sounds of it. I'm looking forward to the new gui!
> 
> It seems to work now! But I had to change the permission of my logfile. My wrong file permissions initially caused a fatal error.
> 
> What permissions are recommended for the logfile? I have a dedicated user for this server and only `www-data` for the view/smarty3 folder.
> 
> ```
> 2019/01/04 23:04:11 [error] 1133#1133: *25021 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/friendica/src/App.php on line 1561PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/friendica/logs/friendica.log" could not be opened: failed to open stream: Permission denied in /var/www/friendica/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
> Stack trace:
> #0 /var/www/friendica/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
> #1 /var/www/friendica/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
> #2 /var/www/friendica/vendor/monolog/monolog/src/Monolog/Logger.php(609): Monolog\Logger->addRecord(250, 'no data for ses...', Array)
> #3 /var/www/friendica/src/Core/Logger.php(335): Monolog\Logger->log(250, 'no data for ses...')
> #4 /var/www/friendica/src/Core/Session/DatabaseSessionHandler.php(38): Friendica\Core\Logger::log('no data for ses...', 'notice')
> #5 [internal function]: Friendica\Core\Session\DatabaseSessionHandler->read('b0cvf26b4u0elm" while reading response header from upstream, client: 195.201.227.53, server: friendica.hubup.pro, request: "GET /objects/174591b4-565c-2f7e-c65a-5fa956709479 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "friendica.hubup.pro"
> ```
> 
_Originally posted by @AndyHee in https://github.com/friendica/friendica/pull/6376#issuecomment-451491258_

**Comment by nupplaphil** [comment]
AFAIK the permission of the logfile should be the same as the user who runs apache2 / nginx. maybe it's because of the directory permission? I'll take a look. In the backend, it calls `fopen()` for writing.

**Comment by AndyHee** [comment]
> AFAIK the permission of the logfile should be the same as the user who runs apache2 / nginx. maybe it's because of the directory permission?

Yes, I think it's the directory permission that caused the problem.

**Comment by AndyHee** [comment]
@MrPetovan the reason I brought this up here was not really to get support, but to highlight a potentially serious error. If someone identically sets the wrong logfile permission, a fatal error is caused.

I was more hoping that the design of this new feature would avoid such behaviour and check the permissions or something like this. I guess, if not a _bug_ we're possibly looking for an enhancement to correct this potential problem.

What do think @nupplaphil ?

**Comment by MrPetovan** [comment]
Until an issue is confirmed to be something we can fix and not something that is specific to the reporter's setup, I put the Support Request label. This doesn't mean we won't look at it, it just means we don't know yet if we have to change something in Friendica itself. If the issue turns out to be on our end, I will gladly update the label.

**Comment by AndyHee** [comment]
OK, thanks for clarifying this!

Here are the instructions for replicating the issue:
- Create the logfile in a folder like `../log/my-friendica.log`
- Give the following permissions` -rw-r--r-- friendica friendica` to both folder and file
- Run web server under `www-data`

**Comment by nupplaphil** [comment]
thanks @AndyHee for the instructions! Now I know better what to do!
I'll reproduce it and try to fix it or at least create a warning!

**Comment by nupplaphil** [comment]
I added this message to the log admin-panel:
![bildschirmfoto von 2019-01-06 16-12-06](https://user-images.githubusercontent.com/379654/50737877-f2252800-11cd-11e9-9866-a5f6a8366cc1.png)

**Comment by tobiasd** [comment]
What is the status of this issue? Can it be closed or moved to the next milestone?

**Comment by nupplaphil** [comment]
I think you can switch to the next release, I won't add any changes for the 2019.03

**Comment by nupplaphil** [comment]
Since this behavior is indeed annoying. I want to fix it for this Release.

I get this error after almost every update with docker...

**Comment by nupplaphil** [comment]
Fixed by #7191
