### ISSUE TITLE
Delivery status indicator shows "pending" for all older posts

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#6383]
All posts written prior to the new indicator show "Notifier task is pending" for me.

This is annoying, at least to my eye.

Shouldn't there be some kind of fallback implemented for older posts? Meaningful would be, in my eyes, to hide the indicator alltogether for these posts.

**Comment by MrPetovan** [comment]
Caused by #6238 

I'll look into this after the release, thanks for the report!

**Comment by MrPetovan** [comment]
Related to #6232

**Comment by MrPetovan** [comment]
Tech obstacle: I don't have a good way to separate the older posts (without any expected delivery counts) with newer posts (with expected delivery counts) at the moment. Both have their counts to 0.

**Comment by MrPetovan** [comment]
How do you know how many delivery target there were? How many were successful?

**Comment by annando** [comment]
One just could say that they all had been successful in the past, can't we?

**Comment by MrPetovan** [comment]
Indeed, that was one one part of the question, what about how many delivery targets?

**Comment by annando** [comment]
I haven't had a look at the system. When it is a signed int, then you could use a negative value as well. So "-1" would be: "no information".

**Comment by MrPetovan** [comment]
Does every item has an associated `item-delivery-data` row or do I need to create them retro-actively?

**Comment by annando** [comment]
Only items that are to be delivered do have this - and only from some time in the past.

**Comment by MrPetovan** [comment]
So, updating the value for existing rows should be enough when people update to 2019.03 stable.

**Comment by annando** [comment]
Would be a first step.

**Comment by MrPetovan** [comment]
A little step for me, but a giant step for the upcoming release.
