### ISSUE TITLE
Menu items missing in mobile with Vier theme

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#6384]
When using the Vier theme and browsing friendica with my phone, some top menu items are completely missing. For these items no icon is shown and there is no drop-down for these hidden items shown either. This includes for instance the site administration and search field.

**Comment by wiwie** [comment]
I'm using Chromium on Android

**Comment by tobiasd** [comment]
Was the `viewport` removed recently? vier used to work with the smartphone browser, but currently in the 2019.01-rc it only shown the desktop version.

**Comment by MrPetovan** [comment]
On vier the viewport is added if App->is_mobile is set, which it doesn't appear to be. However I've seen it working when I did my tests on iOS Add to Home Screen with frio.

**Comment by tobiasd** [comment]
For me the break happened between Dec 24 2018 and Jan 06 2019. On Christmas Eve the page was usable on my smartphone (there were no browser changes on the phone afterwards).

**Comment by MrPetovan** [comment]
Is anyone taking on this issue for this release?

**Comment by MrPetovan** [comment]
Could it be related to #6208? One would need a remote debugger on a desktop to look at the page source on vier mobile.

**Comment by tobiasd** [comment]
Yes I want to try. At least to identify the commit the break to blame the right person(s).

**Comment by tobiasd** [comment]
`git bisect` resulted in 979230da27c1159125ab0a0ab5f6b81e7d7a6515 as the 1st broken commit for vier (mobile) for me.

**Comment by annando** [comment]
@MrPetovan do you want to take over?

**Comment by MrPetovan** [comment]
Not really, I'm not personally using vier and I can't easily debug iOS mobile sessions on my Windows machine.

@tobiasd Thanks for narrowing it down.

**Comment by annando** [comment]
Thanks goes to @tobiasd for pinning it down. The cause was the change that the loading of the theme.php had been moved **after** the module functions had been called. This caused that the "_init" functions hadn't been called anymore - which resulted in some CSS not being loaded anymore.

**Comment by MrPetovan** [comment]
This change was required to fix #1495, this current issue requires specific work on the vier theme to accommodate for the change that prevented an admin to edit the site theme settings if their user theme was different.

**Comment by annando** [comment]
Meh ... But without this move, the "(theme)_init" functions don't seem to be called reliant.

**Comment by MrPetovan** [comment]
That's the problem of having theme files actually executing stuff on require, there's no outside control.

**Comment by MrPetovan** [comment]
How is this related with the position of the theme include?

**Comment by tobiasd** [comment]
Thanks for fixing my problem ;-) But the initial report was about the missing icon for the admin panel and the search bar.

On the Jolla1 there would be enough space to add the icon for the admin panel to the nav-bar in mobile as well. Eventhough the mail notification link was added. But those two links could also be added to the drop-down menu *when on mobile*, couldn't they?

**Comment by tobiasd** [comment]
I think the mail notification icon should rather be hidden from the nav.bar (if the user was an admin) as the mails are also available in the drop-down menu.

**Comment by annando** [comment]
Having looked at the original issue, I think that this isn't a bug, but a feature request (that does make sense). But can we possibly postpone it?

**Comment by tobiasd** [comment]
I moved it to the next milestone.

**Comment by annando** [comment]
I tried to simply remove ```#nav-admin-link``` in the mobile CSS file - but this didn't work. I really hope that there are people out there who are better in CSS than me.

**Comment by MrPetovan** [comment]
> This includes for instance the site administration and search field.

These two items (among others) are voluntarily hidden in the Vier mobile CSS, it is a change request, not a problem of missing space:
https://github.com/friendica/friendica/blob/2d8a4a923f0ff02fff2aa74ac2a2aea4d860fe41/view/theme/vier/mobile.css#L1-L4

However, the message icon can also be hidden in mobile view to reclaim some space.

**Comment by tobiasd** [comment]
I would show the admin and events in mobile mode, but hide the mail notification (as that is displayed in the user menu). On my Jolla1 (4.5" screen) that is ok from the width of the icons.

![friendica-vier--mobil](https://user-images.githubusercontent.com/433490/52911825-77116000-32a9-11e9-8592-24d44b140d7c.png)

**Comment by tobiasd** [comment]
Which branch of Friendica are you using @wiwie? In the current 2019.06-development branch some adjustments to the shown menu items in vier mobile mode were done.

**Comment by tobiasd** [comment]
ping @wiwie

**Comment by wiwie** [comment]
I'm on 2019-09 now and there the problem is indeed solved. Thanks for the ping!
