### ISSUE TITLE
HTML escaping issue in Profile

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#6394]
### Actual behavior
![friendica-profil](https://user-images.githubusercontent.com/12498438/50735820-014bac00-11b5-11e9-8cab-562512690a30.png)

![friendica-profil-2](https://user-images.githubusercontent.com/12498438/50735787-808cb000-11b4-11e9-8916-e3ebd939746a.png)

### Steps to reproduce the problem
Go to a post via the notifications, in the widged on the left side you can see the HTML entities or go to the profile of a contact.

### Friendica version you encountered the problem
Friendica 2019.01-rc - 1292
Theme Frio

### Friendica source (git, zip)
git

### PHP version
7.2.13

**Comment by MrPetovan** [comment]
Part of #6208
Closed via #6400
