### ISSUE TITLE
Editing of forum posts is either not available or fails with freezed screen

### ISSUE THREAD

**Issue by joysfera** [friendica/friendica#6397]
### Expected behavior
Editing of forum posts is available and works.

### Actual behavior
Editing of posts created on the forum profile is not possible at all, there's no way of editing that post.
This is similar to #6276 probably.

However, editing of posts created on my own profile and just "moved" to forum using the !forumname notation is allowed, but as soon as I click the edit link the page is grayed out and kinda freezed (no interaction whatsoever is possible).

### Steps to reproduce the problem
Create a forum profile. Send a message there using !forumname. Visit the forum profile page, locate your post and try to edit it.

### Friendica version you encountered the problem
2019.01rc

### Friendica source (git, zip)
nerdica.net admin will know it
### PHP version
nerdica.net admin will know it
### SQL version
nerdica.net admin will know it

**Comment by annando** [comment]
This is another known problem where we still are searching for a solution.

**Comment by AlfredSK** [comment]
I guess this is solved. See https://github.com/friendica/friendica/issues/6276#issuecomment-932440891

**Comment by tobiasd** [comment]
closing, as editing forum postings is possible now
