### ISSUE TITLE
Deleting of forum posts does not actually delete them?

### ISSUE THREAD

**Issue by joysfera** [friendica/friendica#6398]
### Expected behavior
Deleting of forum posts delete them.

### Actual behavior
The deleted post disapears from the forum but is visible in the stream of all posts.

### Steps to reproduce the problem
Visit a forum profile page, create a post there. Delete it - it says "delete locally", no idea what "locally" means there. Then open your stream (www.nerdica.net/network), your post is there like if it wasn't deleted. It can even be edited easily, contrary to #6397.

### Friendica version you encountered the problem
2019.01rc

### Friendica source (git, zip)
nerdica.net admin will know it

### PHP version
nerdica.net admin will know it

### SQL version
nerdica.net admin will know it

**Comment by annando** [comment]
Yes, currently this is not possible. This is a known problem and cannot be fixed easily.

**Comment by joysfera** [comment]
Is there somewhere a list of known problems so when I, as a newcomer, encounter the next known one, will not report it here? Thanks!

**Comment by annando** [comment]
Just report it here. It will be kept as a reminder to possibly fix it somewhere in the future.

**Comment by AlfredSK** [comment]
Checking....

**Comment by AlfredSK** [comment]
Created a forum post. Waited 15 minutes. Deleted it globally.
https://libranet.de/display/0b6b25a8-9461-574f-c8c4-02a921485494 --> The requested item doesn't exist or has been deleted. :-)

Post vanished locally, on another Friendica node, on Mastodon and Misskey.

I think this can be closed.
