### ISSUE TITLE
Sharing on social networks from meld.de does not work

### ISSUE THREAD

**Issue by sjosiden** [friendica/friendica#6399]
### Expected behavior

Post should be shared on corresponding accounts on tumblr, twitter, diaspora and google+

### Actual behavior

Posts are only visible on friendica/meld.de

### Steps to reproduce the problem

Create account, set up social networks under settings, create a post, check on corresponding account

### Friendica version you encountered the problem

https://meld.de/friendica:

This is Friendica, version 2018.12-dev that is running at the web location https://MELD.de. The database version is 1295, the post update version is 1281.

Site Owner is  Richard Zsemberi. He says:

<q> I noticed that too. Since December 27, only contributions are imported.
For me you are unfortunately in the wrong place, please use the ladybug at the bottom left of the page to report errors directly to Github.</q>

**Comment by AlfredSK** [comment]
I just checked the connectors on a node which is on current RC. That worked.
https://libranet.de/display/0b6b25a8-155c-3257-3800-25b070504175

So, either it's a problem with the develop branch or a specific issue on meld.de.

**Comment by annando** [comment]
I **really strongly** suggest changing to the RC. This is under heavy testing at the moment and seems to work fine on most occasions.

**Comment by tobiasd** [comment]
I have postings that originated from meld.de on my node. But I cannot say if they were distributed directly or fetched later by the worker.

**Comment by tobiasd** [comment]
closing this issue as meld.de was closed
