### ISSUE TITLE
Update doc/tools.md

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#6403]
Since the introduction of the monolog logging framework (https://github.com/friendica/friendica/pull/6376), the fail2ban regex string has changed in `/etc/fail2ban/filter.d/friendica.conf`.

These changes should be reflected in `doc/tools.md` including the specification of the required loglevel to make fail2ban work.

The documentation should show filters both for Friendica prior and post 2019.03

### Friendica version you encountered the problem

develop

**Comment by nupplaphil** [comment]
fixed with #6409
