### ISSUE TITLE
Cron Fatal Error

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6411]
Seen today...

PHP Fatal error:  Call to a member function autocommit() on null in src/Database/DBA.php on line 878

version 2018.09

Line 878 is in function lock() so I assume this is an unhandled connection error.  Difficult to say if the underlying problem is mis-use of the DBA class or a failure within the DBA to actually check the connection.

Also note, DBA::disconnect() never modifies the value of self::$connected 😱

**Comment by MrPetovan** [comment]
Yeah, it happens, when the connection drops any subsequent database call will fail, see #5787, closing here as a duplicate.
