### ISSUE TITLE
Editing of posts/comments can freeze with grayed out screen

### ISSUE THREAD

**Issue by joysfera** [friendica/friendica#6417]
### Expected behavior
After clicking on the "Edit" link an  editor window pops up.

### Actual behavior
Sometimes the whole screen grays out and everything freezes.
This is not related to editing forum posts as I thought in #6397 - it's unrelated to forums.

### Steps to reproduce the problem
Edit what you write and you'll encounter it sooner or later.

Google Chrome console reports at that moment:
```
Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
static.addtoany.com/menu/page.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED

main.js:492 Uncaught ReferenceError: callAddonHooks is not defined
    at Object.success (main.js:492)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
main.js:492 Uncaught ReferenceError: callAddonHooks is not defined
    at Object.success (main.js:492)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
(anonymous) @ main.js:492
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.(anonymous function) @ jquery.min.js:4
liveUpdate @ main.js:480
(anonymous) @ main.js:395
(anonymous) @ main.js:393
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.(anonymous function) @ jquery.min.js:4
NavUpdate @ main.js:387
```

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
nerdica.net admin would know it.

### PHP version
nerdica.net admin would know it.

### SQL version
nerdica.net admin would know it.

**Comment by MrPetovan** [comment]
Thanks for your report, I checked the nerdica.net version at https://nerdica.net/VERSION and it says `2018.12-rc`.

Since it's a Javascript-related, can you try clearing your cache and try to reproduce the issue?

**Comment by AlfredSK** [comment]
This is probably solved as well.
See https://github.com/friendica/friendica/issues/6276#issuecomment-932440891
