### ISSUE TITLE
Mobile view doesn't look good on RC

### ISSUE THREAD

**Issue by annando** [friendica/friendica#6424]
On 2019.01rc the mobile view can look very ugly, since under certain circumstances the CSS isn't loaded. This is a cause of this coding: https://github.com/friendica/friendica/blob/2019.01-rc/src/Core/Theme.php#L199-L202

**Comment by MrPetovan** [comment]
Caused by #6380

**Comment by MrPetovan** [comment]
I can't reproduce this on:
- iOS Firefox Mobile
- iOS Safari
- iOS Chrome
- Windows Firefox with mobile user-agent
- Android (Galaxy Note9) Firefox
- Android (Galaxy Note9) Chrome

Without more info, there isn't much I can do about it.

**Comment by MrPetovan** [comment]
Actually #6380 doesn't reliably fix #5148, so I might just revert given the limited scope of this change.

**Comment by MrPetovan** [comment]
Closed by #6427
