### ISSUE TITLE
Composer: DBUnit is abandoned and no longer maintained

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6429]
Composer install is throwing a warning about phpunit/dbunit.
`Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.`

See here: https://packagist.org/packages/phpunit/dbunit

> PHPUnit extension for database interaction testing
> This package is abandoned and no longer maintained. No replacement package was suggested.

And here: https://github.com/sebastianbergmann/dbunit/issues/217

**Comment by MrPetovan** [comment]
Paging @nupplaphil

**Comment by nupplaphil** [comment]
Oh... Good to know... Added to my ToDo List ;-)

**Comment by nupplaphil** [comment]
I read the issue. So every project should write it's own dbunit backend.. Sounds like a little bit of work to be honest.. But I'll take this todo over my current friendica-work because of the impact on the composer ..

**Comment by nupplaphil** [comment]
I'm currently stuck at https://github.com/mockery/mockery/issues/940
Hopefully they'll reply soon :-/

**Comment by annando** [comment]
When you do have a look at it, can you have a look at the message ```Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.``` as well?

I know that I can solve it by updating the stuff - but this changes the versions in the composer file.

**Comment by MrPetovan** [comment]
You can run `composer update --lock` to solve this message.

**Comment by AlfredSK** [comment]
> You can run `composer update --lock` to solve this message.

Hmm. A lot of admins running the RC branch - including me - have already executed `bin/composer update` (w/o the `--lock` part). Did we break the composer stuff?

**Comment by MrPetovan** [comment]
No, I added a bunch of platform dependencies to the `composer.json` file but I didn't properly update the `composer.lock` file in the process. None of the dependency version have changed but the lock file recorded hash still didn't match the `composer.json` file.

**Comment by AlfredSK** [comment]
Is this solved by #6576 ?

> Almost everything except the API is now using the DB-mocking library.

Sounds like there's still something to do. So, do we keep this issue open?

**Comment by nupplaphil** [comment]
Yep, I think this will stay open until @mrpetovan refactored the routing engine and than we have to fix the ApiTests again. I think after it we can have a look on getting rid of the dbunit dependency

**Comment by nupplaphil** [comment]
Will be fixed by #7441 :-)
