### ISSUE TITLE
PHP fatal error - worker.php

### ISSUE THREAD

**Issue by danielbierstedt** [friendica/friendica#6431]
### Expected behavior
Workers doing maintenance

### Actual behavior
Throwing multiple errors, looks like iterating over a list or array:

PHP Fatal error:  Uncaught Error: Call to a member function autocommit() on null in /volume1/www/fr/src/Database/DBA.php:878
Stack trace:
#0 /volume1/www/fr/src/Core/Lock/DatabaseLockDriver.php(23): Friendica\Database\DBA::lock('locks')
#1 /volume1/www/fr/src/Core/Lock.php(118): Friendica\Core\Lock\DatabaseLockDriver->acquireLock('worker', 0)
#2 /volume1/www/fr/src/Core/Worker.php(1093): Friendica\Core\Lock::acquire('worker', 0)
#3 /volume1/www/fr/boot.php(537): Friendica\Core\Worker::add(10, 'DBUpdate')
#4 /volume1/www/fr/bin/worker.php(41): check_db(true)
#5 {main}
  thrown in /volume1/www/fr/src/Database/DBA.php on line 878

### Steps to reproduce the problem
run the maintenance job:

/usr/local/bin/php70 bin/worker.php

### Friendica version you encountered the problem
2018.09

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
Information from: https://friendi.ca/resources/installation/
https://github.com/friendica/friendica/files/2409065/friendica-full-2018.09.tar.gz

### PHP version
PHP 7.0.30

### SQL version
5.5.59-MariaDB

**Comment by annando** [comment]
In the forum post you said that you are running it on a Synology NAS. I'm running Nextcloud on a Synology NAS and had some problems in the shell with PHP extensions that hadn't been loaded. Calling it this way worked for me:
```/usr/local/bin/php70 -c /volume1/@appstore/WebStation/misc/WebStation-php70/conf.d/extension.ini ...```

**Comment by MrPetovan** [comment]
This is a classic MySQL connection loss issue, see #6411 and #5787. Considering closing as a duplicate.

**Comment by danielbierstedt** [comment]
If you think, collecting similar cases in one thread, go ahead. I'll monitor #5787 and try to find out whats going on here...

**Comment by urbalazs** [comment]
@danielbierstedt @MrPetovan as I see this issue will be handled in another issue. You can close this one.
