### ISSUE TITLE
The release of 2019.01 is overdue

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6459]
Is there anything left to do for the release of Friendica 2019.01? I don't see any serious issues with milestone 2019.01 anymore. Does anyone still have important pull requests in the pipe?

### Expected behavior
We should release Friendica 2019.01 on the upcoming weekend.

### Actual behavior
The release is already three weeks late.

### Steps to reproduce the problem
`git log`

### Friendica version you encountered the problem
2019.01-rc

### Friendica source (git, zip)
git

**Comment by MrPetovan** [comment]
The release is actually 7 weeks overdue! Time to wrap it up. The next release will actually come pretty fast.

**Comment by annando** [comment]
Issue https://github.com/friendica/friendica/issues/6282 and https://github.com/friendica/friendica/issues/6384 should be solved. Additionally I have to solve some AP message relay problem I discovered today.

**Comment by annando** [comment]
I think that https://github.com/friendica/friendica/issues/5913, https://github.com/friendica/friendica/issues/5911, https://github.com/friendica/friendica/issues/6208 and https://github.com/friendica/friendica/issues/5932 can be closed now (and new ones can be opened for the next version).

https://github.com/friendica/friendica/issues/6384 could be postponed, so I guess we are done for the release?

**Comment by AlfredSK** [comment]
I just check 'vier' on a mobile device again. The mobile view is displayed when using a phone or tablet. So, 'vier' isn't broken on mobile devices anymore.

**Comment by MrPetovan** [comment]
Closed for release, milestone clear.

**Comment by rabuzarus** [comment]
I have to reopen https://github.com/friendica/friendica/issues/5092 again. We would say we really should fix it before we release the new version
