### ISSUE TITLE
.htaccess rewrite code for .well-known?

### ISSUE THREAD

**Issue by imattau** [friendica/friendica#6466]
Support required--

Is there any code already available for the .htaccess file for .well-known (similar to Nextcloud)?

My site is currently returning 403 errors for .well-known/host-meta. Otherwise everything else is working fine.

### Friendica version you encountered the problem
2018.09
see `example.com/friendica` on your Friendica node for the version information.
1283
### PHP version
7.1
### SQL version
MariaDB (Mysql)

**Comment by MrPetovan** [comment]
Hi, there's a `.htaccess-dist` in the root folder of Friendica that you can rename to `.htaccess` to work with Apache out of the box.

**Comment by imattau** [comment]
I'm on a shared host, and have email the admins to check if there is an issue with .well-known.

**Comment by imattau** [comment]
Issue resolved. It was due to the .htaccess file in the root directory, affecting the subdomains.
