### ISSUE TITLE
Email Notification: Link to Thread

### ISSUE THREAD

**Issue by JonnyTischbein** [friendica/friendica#6468]
### Expected behavior
When I get an email notification I get a link to the local thread.

### Actual behavior
The Email contents:
- who has commented, 
- the comment, 
- a link to the friendica page, 
- a link to the notification view
![screenshot_2019-01-19_13-11-34](https://user-images.githubusercontent.com/10757520/51426521-4ed00c00-1bec-11e9-8980-c6c02a962a17.png)

### Steps to reproduce the problem
1. Enable email notification for comments
2. Get a comment on a thread you interacted with
3. Receive email

### Friendica version you encountered the problem
This is Friendica, version 2018.12-rc that is running. The database version is 1291, the post update version is 1281.

### Friendica source (git, zip)
git

### PHP version
7.0 dotdeb debian

**Comment by MrPetovan** [comment]
The link to the notification redirects automatically to the specific thread, it looks like a UX issue.

**Comment by MrPetovan** [comment]
The link to the notification is used to mark it as read before redirecting to the notification target..

**Comment by JonnyTischbein** [comment]
I see...
