### ISSUE TITLE
`.well-known/nodeinfo` returns NodeInfo url which doesn't exist

### ISSUE THREAD

**Issue by jaywink** [friendica/friendica#6472]
### Expected behavior

The fact that `/.well-known/nodeinfo` lists an URL imho means that that url should exist.

### Actual behavior

If the add-on "Publish server information" is not activated, NodeInfo route gives 404.

### Steps to reproduce the problem

For example follow this: https://social.gl-como.it/.well-known/nodeinfo

I see this come up once a month maybe on https://the-federation.info, latest https://github.com/thefederationinfo/the-federation.info/issues/174 . I could just make the parser ignore invalid JSON (the 404 page), but IMHO since the well known page lists the URL it should exist. Maybe the fix would be to not render the well known page if public server information is not active?

Related also to #3855

**Comment by MrPetovan** [comment]
Thanks for the report, the link shouldn’t be displayed it isn’t supposed to be accessed.

How does the-federation.info handle empty nodeinfo link list?

**Comment by MrPetovan** [comment]
You aren't the only nodeinfo client around, we should fix our end anyway.

**Comment by MrPetovan** [comment]
Closed via #6727
