### ISSUE TITLE
Transparent profile pictures cannot be used

### ISSUE THREAD

**Issue by sesom42** [friendica/friendica#6477]
### Expected behavior
Transparent profile pictures (png) are displayed correctly. E.g. in the bar at the top right of the Frio theme.

### Actual behavior
Transparent profile pictures are displayed correctly at the beginning, but after a few days they are only displayed as a black square.

### Steps to reproduce the problem
Set a transparent profile picture and wait a few days. Unfortunately I don't know after how many days the error occurs. I think after less than five days.

### Friendica version you encountered the problem
2019.01-rc

**Comment by annando** [comment]
I guess that some image conversion routine is to blame. But I haven't found it by now.

**Comment by rabuzarus** [comment]
Yes this behavior seems to be new with this release. My profile picture was also transformed to a black square

**Comment by ben-utzer** [comment]
I have this problem as well, compare accounts here:
https://social.yl.ms/display/ec054ce7-835c-5d61-f7a7-610721354998
and here:
https://pirati.ca/display/ec054ce7-835c-5d61-f7a7-610721354998

**Comment by fabrixxm** [comment]
The image is converted in jpeg somewhere.

I'm using a png with alpha in my profile, but everywhere else it has a black background (see [original](https://kirgroup.com/display/61b57c7e-165c-5da0-45e8-2bb597546001) and [federated](https://friendica.mrpetovan.com/display/61b57c7e-165c-5da0-45e8-2bb597546001) ). On mastodon png is correctly used (see [here](https://mastodon.opencloud.lu/@paolo/101557204350354980) )(The only exception being mastodon.social which still shows my old profile photo)

After some time also *my* server starts to show me the black background on smaller version of the profile picture. Going in photos page and select the same photo as profile photo again fixes this.

**Comment by MrPetovan** [comment]
Well, first of all, we slap `.jpg` to profile images whether they are JPG or PNG: https://friendica.mrpetovan.com/photo/profile/6.jpg

So that may definitely not help.

This could also explain why it appears normally on the profile (the browser disregard the wrong extension) but why it breaks when the picture is imported in a contact (because we trust the extension): https://friendica.mrpetovan.com/photo/29af3b693e9bc2bcc0143526093cdff1-4.jpg

First step would be to have a conditional extension when the profile picture is first saved. It may actually solve the latter issue.

**Comment by tobiasd** [comment]
> Well, first of all, we slap `.jpg` to profile images whether they are
> JPG or PNG

Is this a new behaviour? Transparent backgrounds in PNGs used to work for years reliable when the ImagMagics library was installed.

**Comment by annando** [comment]
This is not new. It is new (for some time now) that we propagate the avatar picture link from the "self" user.

**Comment by MrPetovan** [comment]
I keep digging, and I found out that we set the user's photo URL *independently*  of image retrieval/storage. For example we set `https://friendica.mrpetovan.com/photo/profile/6.jpg` as the user's avatar image URL on user creation before we store either the Gravatar image/default avatar image.

This, obviously, isn't good. I'm assuming we don't even update the user's avatar URL on profile picture update, we just update the photo record with the new picture, whatever the image type it is.

**Comment by MrPetovan** [comment]
This looks like a massive undertaking to overhaul the image handling with proper extensions. Moving to next milestone.

**Comment by MrPetovan** [comment]
Not an RC task.

**Comment by annando** [comment]
While fixing some bugs in the AP profile discovery I discovered bugs in the webfinger stuff which lead me to bugs in this photo stuff. Possibly its not that hard.

**Comment by MrPetovan** [comment]
Fixed by #6477

**Comment by MrPetovan** [comment]
Can anyone please try to use a transparent picture on the latest RC?

**Comment by fabrixxm** [comment]
I've set the same png as my profile picure again. now the url correctly ends in .png :+1: 
now I'll wait for contacts to update my profile picture, e.g. [here](https://friendica.mrpetovan.com/display/61b57c7e-165c-5da0-45e8-2bb597546001)

**Comment by MrPetovan** [comment]
Yes! https://friendica.mrpetovan.com/photo/f5fa3ddc8307c8f9241d00da2cfa123e-4.png
