### ISSUE TITLE
User documentation needs updating at https://social.isurf.ca/help/Quick-Start-guide

### ISSUE THREAD

**Issue by llaxton** [friendica/friendica#6478]
In preparation for new release, page needs updating - 

Current:
This is a bit like your Facebook wall. It's where all your status messgages are kept, and where your friends come to post on your wall. To write your status, simply click in the box that says "share". When you do this, the box will expand. You can see some formatting options at the top such as Bold, Italics and Underline, as well as ways to add links and pictures. At the bottom you'll find some more links. You can use these to upload pictures and files from your computer, share websites with a bit of preview text, or embed video and audio files from elsewhere on the web. You can also set your post location here.

Once you've finished writing your post, click on the padlock icon to select who can see it. If you do not use the padlock icon, your post will be public... 

Suggested:
This is a bit like a Facebook wall. It's where all your status messages are kept, and where your friends come to post on your wall. To write your status, simply click on the box that says "share". When you do this, the box will expand. You can see some formatting options at the bottom such as Bold, Italics and Underline, as well as ways to add text links and a paperclip icon to attach (embed content from) different types of URLs (image/video/audio/webpage). You can also set your post location here. The browser tab can be used to upload and post media to/from your account.

Once you've finished writing your post, click on the padlock icon or permissions tab to select who can see it. If you do not change anything, your post will be public...

**Comment by tobiasd** [comment]
part of #1478

**Comment by realkinetix** [comment]
Attempted to adjust accordingly, but it's tricky when covering the differences in the major themes.

**Comment by MrPetovan** [comment]
Fixed by #6810
