### ISSUE TITLE
Distribution broken on develop

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6492]
Testet to Wordpress, Buffer, LinkedIn and tumbrl

VersionFriendica 'The Tazmans Flax-lily' 2019.03-dev - 1299
upload_max_filesize	64M
post_max_size	72M
memory_limit	512M
MySQL / MariaDB
max_allowed_packet	16777216
Ubuntu 18.04 operating system (64-bit)
Kernel-generic 4.15.0-43
Administration Panel 18.2.1 (Build 1466) Change History
Web server Apache / 2.4.29 (Ubuntu)
PHP 7.2.10-0ubuntu0.18.04.1
Database Version 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
FTP server ProFTPD 1.3.5e
Database Administration phpMyAdmin 4.8.4

**Comment by tobiasd** [comment]
So it is *only* a problem with the bridges/addons?

**Comment by copiis** [comment]
I think there is no difference in the addons between Master and Develop and on Master it worked.

**Comment by copiis** [comment]
Then there lies the rabbit buried in the pepper?

**Comment by MrPetovan** [comment]
It isn't a problem with the addons. My Twitter posts don't reach Twitter, but I receive Twitter posts, both mirrored and my home feed.

Additionally, my messages never reach Friendica forums, and possibly other places.

Delivery is broken in the core, I intend on looking into it in about 8 hours.

**Comment by annando** [comment]
:grimacing: 

BTW: You should be called "brave heart" for running "develop" on a large production system, Currently I don't dare to do the update even on my development machine. I guess I will do the update there on Sunday.

**Comment by copiis** [comment]
> It isn't a problem with the addons. My Twitter posts don't reach Twitter, but I receive Twitter posts, both mirrored and my home feed.
> 
> Additionally, my messages never reach Friendica forums, and possibly other places.
> 
> Delivery is broken in the core, I intend on looking into it in about 8 hours.

I can confirm everything

**Comment by MrPetovan** [comment]
I'm seeing posts from 12+ hours ago are starting to get delivered from my node thanks to the new delivery indicator, this problem likely was cause by the APDelivery bug I introduced and fixed in #6487.

**Comment by annando** [comment]
is fixed by https://github.com/friendica/friendica/pull/6515
