### ISSUE TITLE
Infinite Scroll leads to display problem in 2019.01

### ISSUE THREAD

**Issue by seraphyn** [friendica/friendica#6493]
### Expected behavior
Page should loud the next articles

### Actual behavior
![friendica_endlessscroll](https://user-images.githubusercontent.com/140527/51566620-4c440f80-1e95-11e9-99b8-727ba5b3c8ee.png)

### Steps to reproduce the problem
Scroll down to the last post and a load is happening.

### Friendica version you encountered the problem
2019.01
Theme Frio 0.8.5

### Friendica source
git

Cache emptied after update, all addons pulled after update.
Database updated.

**Comment by MrPetovan** [comment]
Did the cache you are referring to concerns the browser cache? The `main.js` file was changed and is likely to be cached on any and all browsers you are using to browse Friendica.

**Comment by seraphyn** [comment]
@MrPetovan This.
The last thing I was thinking about.
Thanks @MrPetovan
