### ISSUE TITLE
feature request DiCa app

### ISSUE THREAD

**Issue by Rik44444** [friendica/friendica#6494]
Dear all,
is this also the right place to comment on the DiCa app for android? apologies if it is not. I just wanted to say that I am really impressed by the app: it is very good to a new user (me) in both its simplicity and available features. I also have a feature request: am I correct to say that there are now 'tabs' for:
- friends (my friends' posts)
- public (all Friendica posts) - called community/local on my squeet.me pod
- network (all Federated posts) - called community/global on my squeet.me pod
- my (my own posts) - called profile on my squeet.me pod
- favourites (listing my favourites)

The feature request is to add another tab, for the tab that is called 'Network´ on my squeet.me pod (NOT the same as what you call network in the app, that appears to be all Federated posts). This tab, on squeet.me, shows my own posts + all the posts related to my saved searches (hashtags i have saved) + all my friends posts. This is actually the tab I use the most by far in my browser, so it would be great if it was also available in the app.
Keep up the amazing good work!! Happy to contribute from a user perspective where i can (have no coding experience).
Rik

**Comment by MrPetovan** [comment]
Thanks for your interest, [DiCa has its own issue tracker](https://github.com/jasoncheng/dica/issues). Please submit this report [by opening a new issue over there](https://github.com/jasoncheng/dica/issues/new).
