### ISSUE TITLE
Usermenu has broken links on remote host

### ISSUE THREAD

**Issue by Ixiter** [friendica/friendica#6495]
### Expected behavior
usermenu links on a foreign host link to correct pages on own host
### Actual behavior
**links are broken**, result in an Error 400 - Bad Request
**the nickname is missing** in all links that needs it :see screenshot for profile link example
### Steps to reproduce the problem
login at your host. visit another host where you are known but dont have an account
### Friendica version you encountered the problem
2019.01 on own and remote host own= socivitas.com remote=squeet.me
frio theme
![friendica_usermenu_links_bug](https://user-images.githubusercontent.com/1101592/51576003-cb950b80-1eb4-11e9-90ff-b3cc451b888f.jpg)

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by MrPetovan** [comment]
Closed via #6526
