### ISSUE TITLE
Rotation of Images not possible

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6498]
### Expected behavior

In the "Edit Image" section of the gallery there is the possibility to rotate an image (anti-)clockwise. This should rotate the image accordingly.

### Actual behavior

It is not. The preview image (`-1` at the end of the file name) remains as it was. Furthermore the original size image (`-0` at the end of the file name) does not contain a valid image anymore that can be displayed in the browser.

### Steps to reproduce the problem

* upload an image
* edit the image and use the rotate image functionality

### Friendica version you encountered the problem

2019.01

### Friendica source (git, zip)

git

### PHP version

PHP 7.2.13 , php-gd same version

### SQL version

MariaDB 15.1

**Comment by MrPetovan** [comment]
Closed via #6779
