### ISSUE TITLE
MySQL high load / core dump

### ISSUE THREAD

**Issue by danielbierstedt** [friendica/friendica#6500]
I updated from 2018.09 to 2019.02 about an hour ago.

### Actual behavior
- High load from DB process. Forced db structure update produces core dump.
root@DiskStation:/volume1/www/fr# bin/console.php dbstructure update
Segmentation fault (core dumped)

- bad performance while browsing
- not able to post into Friendica Support Forum: results in 504 - GW timeout

### Friendica version you encountered the problem
2019.01

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
Zip

### PHP version
7.0

**Comment by danielbierstedt** [comment]
Update: restarted whole server: no improvement. No updates at all incoming. Worker queue empty.

**Comment by annando** [comment]
Please execute ```bin/console.php dbstructure update``` in the command line. Does it return something?

**Comment by danielbierstedt** [comment]
Yes, it does, as mentioned in the text:

```
root@DiskStation:/volume1/www/fr# bin/console.php dbstructure update
Segmentation fault (core dumped)
```
Forced a db structure check from the web interface:
`
Fehler 1214 beim Update der Datenbank aufgetreten The used table type doesn't support FULLTEXT indexes
Das Update 1293 der Struktur der Datenbank schlug mit folgender Fehlermeldung fehl: Fehler beim Ändern der Datenbank aufgetretenALTER IGNORE TABLE `profile` ADD FULLTEXT INDEX `pub_keywords` (`pub_keywords`); 
`

**Comment by danielbierstedt** [comment]
Server version: 5.5.59-MariaDB Source distribution
That is on a Synology NAS

**Comment by annando** [comment]
Please use the MariaDB 10 package instead. (It can be installed additionally to the existing version)

**Comment by danielbierstedt** [comment]
Yes sir. I'll need to find out how that works, if I need to migrate databases etc. Will report back once done.

**Comment by annando** [comment]
You have to dump the database from the old database server and import it to the new server.

**Comment by danielbierstedt** [comment]
And then (most likely) update the port in the Friendica config

**Comment by annando** [comment]
Correct.

**Comment by danielbierstedt** [comment]
This really bugs me! Its not that easy, because the local mysql client just ignores the port setting. No idea how to handle the migration.

**Comment by MrPetovan** [comment]
Why do you have to update the port? It should still be 3306 by default even after the upgrade.

**Comment by danielbierstedt** [comment]
No, that is not true for the Synology installation. Situation:
- two MariaDB running, 5 on 3306 and 10 on 3307 (default settings)
- when connecting to localhost, port settings are being ignored, because when connecting to localhost the socket is being used instead of network.
- correct settings for friendica local.ini.php is host:port. there is no separate port setting

- exported using mysqldump
- import: "mysql -u {user} -p {database} -h 127.0.0.1 -P 3307 < backup.sql"
- dbstructure update now without output (interpret that as good)
- webinterface structure check returnes "good"

`root@DiskStation:/volume1/www/fr# /usr/local/bin/php70 -c /var/packages/WebStation/etc/php_profile/79eb865c-cfa7-45cf-a0cf-c2938c235dfd/conf.d/user_settings.ini -f bin/console.php dbstructure update
Cannot load Zend OPcache - it was already loaded
ALTER IGNORE TABLE `profile` ADD FULLTEXT INDEX `pub_keywords` (`pub_keywords`);
`

**Comment by danielbierstedt** [comment]
the respective php.ini file. Could be, there are settings coming from somewhere else, too. Can research later that day or so.

`  1
  2 zend_extension = opcache.so
  3 extension = apcu.so
  4
  5 extension = bz2.so
  6 extension = curl.so
  7 extension = gd.so
  8 extension = gettext.so
  9 extension = iconv.so
 10 extension = openssl.so
 11 extension = pdo_mysql.so
 12 extension = posix.so
 13 extension = xsl.so
 14 extension = zip.so
 15
 16 display_errors = Off
 17 open_basedir = /var/services/tmp:/etc.defaults:/usr/bin/php:/usr/syno/synoman:/etc:/var/run:/volume1/@tmp/php:/var/services/web:/var/services/photo:/var/services/blog:/var/services/home    s:/volume1/web/nextcloud:/volume1/www/fr:/volume1/www/hub
 18 default_socket_timeout = 180
 19 opcache.enable_cli = 1
 20 opcache.interned_strings_buffer = 8
 21 register_argc_argv = On
`

**Comment by annando** [comment]
@MrPetovan This "opcache" thing is because of the Synology NAS. I have one at home, too. I'm running Nextcloud on it. But I guess this behavior changed, when I changed from PHP 7.0 to PHP 7.2.

**Comment by MrPetovan** [comment]
You can try to comment the `zend_extension = opcache.so` line and run `php -i | grep opcache` to see if the message disappeared and opcache is still enabled.

**Comment by annando** [comment]
This is ... complicated. The Synology Webstation does work - but it is some nicely constructed thing.

**Comment by danielbierstedt** [comment]
I saw the 7.2 being available few days ago. Will try that at the weekend or so, so I have enough time to fix issues.

Meanwhile, I think we can close this issue. 

Thank you guys!

**Comment by tobiasd** [comment]
So this was an issue with MariaDB 5.5 being too old?

**Comment by annando** [comment]
Not related, but related in some way: Due to a problem with the worker and a database structure change in the workerqueue table, after the update the people have to update the database structure by themselves. The automatic database update won't work.
