### ISSUE TITLE
Reshares displayed on Diaspora

### ISSUE THREAD

**Issue by pixelsalad** [friendica/friendica#6501]
Hi all, 

I'm new here, so I really don't know how this works yet.

When a friendica post is reshared and displayed on Diaspora there is a short sequence of symbols that contain the link to the original post. Another user had to show me there was a link, because it is easily missed. 

Since reshares can be edited on friendica, I think it's important the link is more prominently displayed

I can't even tell what the current display is [l] I guess. Could be an l or I. 

[source] or [link] or [original] would be better. Or just displaying the link like [https://something]

**Comment by MrPetovan** [comment]
Hi @pixelsalad and thanks for reaching out.

Can you please post a screenshot of the reshare apparence? It might be a display issue on Diaspora end that we wouldn't be able to address here.

**Comment by annando** [comment]
I spoke with her in a discussion before. She means the link on Friendica (with - I guess - Frio) on reshared posts. She would like to see the link to the original post more prominently.

**Comment by pixelsalad** [comment]
Here is a link to the my friendica post displayed on my diaspora account

https://pod.thomasdalichow.de/posts/962c3e10-125c-45d3-8a18-289011881590

I'm talking about the link displayed between the line #Test and Hier ist...

**Comment by MrPetovan** [comment]
Here's the final output I came up with: https://diaspora.permutationsofchaos.com/posts/2200689

**Comment by MrPetovan** [comment]
Fixed by #6774
