### ISSUE TITLE
Force db-update isn't working 

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6503]
### Expected behavior

`bin/console.php dbstructure update -f` ignores even locked updates

### Actual behavior

the lock `friendica.philipp.info:lock:dbupdate` isn't ignored, so I had to manually delete it before retrying the update.

### Steps to reproduce the problem

- set the lock HOST:lock:dbupdate
- `bin/console.php dbstructure update -f`
- the lock isn't deleted automatically

### Friendica version you encountered the problem

develop

### Friendica source (git, zip)

git

**Comment by MrPetovan** [comment]
Is this still an issue that needs to be fixed in this release?

**Comment by MrPetovan** [comment]
Closed via #6740
