### ISSUE TITLE
Notifications appear in english and german

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6522]
### Expected behavior
Notifications should appear in users configured language

### Actual behavior
Sometimes in english, sometimes in german, sometimes mixed.

![00_temp](https://user-images.githubusercontent.com/24474762/51787213-53a63a00-216f-11e9-97b7-708c4c1f5874.png)

### Steps to reproduce the problem
Wating for new notifications ;)

### Friendica version you encountered the problem
git / latest develop / mariadb 10.0.37-MariaDB / php 7.0

**Comment by annando** [comment]
Jepp, some translations are missing at "develop".

**Comment by MrPetovan** [comment]
The few "on their post" strings.

**Comment by annando** [comment]
Yeah, you gave a really big task for the translators.

**Comment by hoergen** [comment]
Is this as well a translation thing? Or just a leftofer typo somewhere in the code?

![00_temp](https://user-images.githubusercontent.com/24474762/51972565-fc101300-247b-11e9-9016-8235c6fa0d69.png)

**Comment by tobiasd** [comment]
Well, IIRC you have an account at Transifex ;-)

For me it looks like a left over from copy and pasting, but the source string seems also have a missing space after the bracket problem.

**Comment by tobiasd** [comment]
I'm curious why there is BBCode in the strings @annando @MrPetovan ? That _could_ be the explanation for the `a` (from a link) as well. I have no clue.

**Comment by MrPetovan** [comment]
It seems to be an unfortunate copy-pastye, see relevant `strings.php` extract:
```php
$a->strings["%1\$s tagged you on [url=%2\$s]a %3\$s[/url]"] = "%1\$s markierte dich auf [url=%2\$s]a %3\$s[/url]";
$a->strings["%1\$s commented on [url=%2\$s]a %3\$s[/url]"] = "%1\$s kommentierte [url=%2\$s]a %3\$s[/url]";
$a->strings["%1\$s tagged you on [url=%2\$s]%3\$s's %4\$s[/url]"] = "%1\$s markierte dich auf  [url=%2\$s]%3\$s's %4\$s[/url]";
$a->strings["%1\$s commented on [url=%2\$s]%3\$s's %4\$s[/url]"] = "%1\$s kommentierte [url=%2\$s]%3\$ss %4\$s[/url]";
$a->strings["%1\$s tagged you on [url=%2\$s]your %3\$s[/url]"] = "%1\$s markierte dich auf [url=%2\$s]a %3\$s[/url]";
$a->strings["%1\$s commented on [url=%2\$s]your %3\$s[/url]"] = "%1\$s kommentierte [url=%2\$s]deinen %3\$s[/url]";
$a->strings["%1\$s tagged you on [url=%2\$s]their %3\$s[/url]"] = "%1\$s markierte dich auf [url=%2\$s]a %3\$s[/url]";
$a->strings["%1\$s commented on [url=%2\$s]their %3\$s[/url]"] = "%1\$s kommentierte [url=%2\$s]a %3\$s[/url]";
```

**Comment by tobiasd** [comment]
But why is there BBCode in the strings? HTML codes are recognised as such by Transifex and handled user friendly, BBCode is not. So HTML would be better for the Translation.

**Comment by MrPetovan** [comment]
I guess you'd have to ask @friendica : https://github.com/friendica/friendica/commit/5734d5f357742814b56d3d8e0e6daf2e86e793d0

**Comment by hoergen** [comment]
Just noticed, this "a" sounds a little bavarian .... "marrrkierrte dich auf a Beitrrrag" pfüati!

**Comment by tobiasd** [comment]
The translation was updated. So *this* issue should be solved.
