### ISSUE TITLE
frio: Paper-clip behaves different in post and comment

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6524]
### Expected behavior
Paper-clip should always behave the same. Regardless if it is in a post or a comment.
For another representation of URLs there is the URL funktion.

### Actual behavior
In a post it generates the full preview with an image and the description like this
`
[attachment type='video' url='https://www.youtube.com/watch?v=Jmv6TJ2BYs8' title='How to sample vinyl on the Synthstrom Deluge' image='https://i.ytimg.com/vi/Jmv6TJ2BYs8/maxresdefault.jpg']First tutorial I've ever made showing you how I going about sampling vinyl into my Deluge. I hope my process is helpful. Leave a comment if you have any ques...[/attachment]`

In a comment it produces just
`[url=https://www.youtube.com/watch?v=Jmv6TJ2BYs8]How to sample vinyl on the Synthstrom Deluge[/url]`

What can be achieved with the hyperlink button as well. Or maybe should be achieved with the hyperlink button, because the button just inserts 
`[url][/url]`

### Steps to reproduce the problem
Push da button ;)

### Friendica version you encountered the problem
git / latest develop / mariadb 10.0.37-MariaDB / php 7.0

**Comment by rabuzarus** [comment]
A comment isn't a Top-Level post. A comment is for discussing Top-Level posts. So it should focus more on text and less on multimedia attachments. That's why we decided to don't have attachments in comments.

Would like to close this issue with `won't fix`

**Comment by hoergen** [comment]
Hmm ok I don't agree because then the function should indicate a different behaviour. But I close it as you wish.

**Comment by MrPetovan** [comment]
> Push da button ;)

😄

**Comment by rabuzarus** [comment]
> Hmm ok I don't agree because then the function should indicate a different behaviour.

Maybe it should indicate a different behavior, but this would be another discussion.
My point was just that comments shouldn't have attachments

**Comment by MrPetovan** [comment]
Is there any way "we" can revisit this? I agree with @hoergen, it should either be consistent between both cases or have different display.

Besides, we can attach images in comments already, what's the difference for video/audio?

**Comment by rabuzarus** [comment]
> Besides, we can attach images in comments already, 

No we can display audio/video but it isn't an attachment.
The difference is that the audio video tags arn't attachments - friendica can display it but as far as I know the other networks won't display this tags. @annando can describe the difference in a better way.
Other networks display only one attachment - the audio/video tags are the friendica way to display more than just one video per post.

We had this discussion with https://github.com/friendica/friendica/pull/6013/ (which introduces the `paperclip` for comments) but I can't find the corresponding discussion on friendica.

There are two questions:
1.) What kind of data do we want show in the comments to the user? And how do we want to show it to the user?
2.) How to input this data to have a good UX

I gave my opinion for 1.) in my comment above.

**Comment by MrPetovan** [comment]
So it is a case where we need a different display.
