### ISSUE TITLE
search url returns 3rd party posts in otherwise closed installation

### ISSUE THREAD

**Issue by kkretsch** [friendica/friendica#6525]
### Expected behavior
The url "/search?tag=the" should not return 3rd party posts for anonymous users

I'm running a personal installation without open registration and disabled somehow ("keine Gemeinschaftsseite") access to start page articles. Only my own ones can/should be seen via the profile page of myself. (For anonymous access)

### Actual behavior
It returns all matches for anonymous users

### Friendica version you encountered the problem
Current git pull "2019.03-dev"

### Friendica source (git, zip)
git

### PHP version
PHP 7.0.32-0ubuntu0.16.04.1 

### SQL version
5.7.25-0ubuntu0.16.04.2 (Ubuntu)

**Comment by AlfredSK** [comment]
I'm not sure if this is the solution you want but you can disable the search function for not logged-in visitors completely. The setting isn't available in the GUI. You have to set that in your config file.

**Comment by kkretsch** [comment]
Thanks, that solves it.
I'm just a bit confused that setting local_search to true disables the public search, but that is just a wording issue. Thinking twice about it makes sense again.

**Comment by annando** [comment]
Blame me for the wording :-) Some "only_local_search" would had been better, I guess.
