### ISSUE TITLE
frio - bug in user admin when sorting users table

### ISSUE THREAD

**Issue by Ixiter** [friendica/friendica#6529]
### Expected behavior
The users table should reorder and the block and delete button should still be there
### Actual behavior
When you reorder the table, the block and delete buttons disappear
### Steps to reproduce the problem
Got to the admin panel users, uncollapse the users tab and reorder the table. the block and delete buttopn disappear
### Friendica version you encountered the problem
2019.01
frio theme

Reported in the support forum at https://forum.friendi.ca/display/b8c357bb-115c-4c81-0ff1-eb1261115722

**Comment by MrPetovan** [comment]
Closed via #6530

**Comment by MrPetovan** [comment]
Pro Tip: If you have a fix ready for an issue that hasn't been reported on GitHub yet, you can skip creating an issue and directly submit the PR with the same reference information you provided here. The reason why there are issues and PR is that different people can report the first and submit the second. When it's the same person reporting the problem and fixing it, it doesn't make as much sense to have two separate parts.

Thanks again!

**Comment by Ixiter** [comment]
Hey .. I am german. We love protocols, reports and protcolling and reporting. Twice is the new once!
:D

Yes .. thought that already but diodnt know how we handle it. Others want an issue/a ticket for each case before commit and push. I also prefer your way. Just do what is to do and its done.

**Comment by annando** [comment]
I'm so totally non German ... (With the exception of my origin). I have to be forced to keep standard ways of working. 😁

**Comment by Ixiter** [comment]
Me neither. I dont like Wurst, I dont drink Bier and I cross the street while red light.
