### ISSUE TITLE
API field user wrong for forum posts

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#6537]
The API field user contained the user data of the original author for forum posts for the api /statuses/friends_timeline. Since 2019.1 the field contains the data of the forum. This data should be in the friendica_owner field (see #5884). The user field should deliver the data of the original author.

**Comment by MrPetovan** [comment]
Forum posts are treated as "retweeted status". You can find the original author in `retweeted_status.user` in the item structure.

**Comment by annando** [comment]
This is done in this way so that clients like Twidere are displaying it in a good way.

**Comment by annando** [comment]
We possibly should add a "friendica_author" field to avoid any confusion. But: A forum does in fact simply reshare the original post. So it is completely okay that the user of a forum post is the forum, while the user of the reshared post is the original author.

**Comment by MrPetovan** [comment]
Closed via #6898
