### ISSUE TITLE
Receiving double identical replies on Friendica posts

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6543]
### Case 1: Friendica post, double Diaspora replies

https://friendica.mrpetovan.com/display/2196d4ee-215c-4fbd-0dba-469497567207

Post 1 GUID: 4f625a6**005ab01379be6101b0e8ace24**
Post 2 GUID: 5d23cb1**005ab01379be6101b0e8ace24**

Highlighting the identical part. I believe the the first characters are for the originating server/account?

Posts have **different** timestamp.

### Case 2: Friendica post, double Friendica replies

https://friendica.mrpetovan.com/display/735a2029-165c-4f70-b2a5-40c212169507

Post 1 GUID: **2196d4ee**-855c-4f9e-da75-c02313237312
Post 2 GUID: **2196d4ee**-165c-4f9e-da8c-a7c814022851

This time the prefix is the same, and both posts have the **same** timestamp.

**Comment by annando** [comment]
The comment is doubled at the commenter's server as well: https://pod.geraspora.de/posts/2196d4ee-215c-4fbd-0dba-469497567207

This does mean that the comment in fact is created twice by the commenter. Concerning the GUID: Diaspora has got a different method than we.

Case 2 is doubled at the commenter's server as well: https://horche.demkontinuum.de/display/2196d4ee-855c-4f9e-da75-c02313237312

For me it seems like the commenter has simply pressed the "send" button twice by accident.

**Comment by MrPetovan** [comment]
Thanks for looking into it, when I saw the first double comment, this was my intuition, but it happened again a few minutes later with someone else.
