### ISSUE TITLE
Directory permissions for filesystem storage

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#6545]
### Expected behavior

It should be possible to set the permission for the storage directory to `friendica:www-data` or `www-data:www-data` if the cronjob is run by a dedicated friendica user.

### Actual behavior

It's impossible to run the cornjob command and the console storage move command by the same dedicated users.

This has implication for Debian users in terms of ease of management via remote access.

'Furthermore trying to write in index.html is stuck in a loop raising the system LOAD above any sane values.' 

For further discussions please see here: https://forum.friendi.ca/profile/helpers?f=&owt=cd8187fa5a1e4f2a0d068f539a50dbaf

### Friendica version you encountered the problem

 develop

### Friendica source (git, zip)
git 
### PHP version
7.3 

### SQL version
MariaDB

**Comment by fabrixxm** [comment]
have you `chmod g+rwx $STORAGE_FOLDER` ?
plus, the code should set similar permissions on files it creates.
By default files are created `-rw-r--r--    www-data www-data`  and folders `drwxr-x---  www-data www-data`, they should be writeable by the group.

**Comment by AndyHee** [comment]
> have you chmod g+rwx $STORAGE_FOLDER ?

I did this: `chmod 0770 $STORAGE_FOLDER` after creating the directory.
