### ISSUE TITLE
Connect/Follow dialog "Does contact_name know you?" button is unresponsive

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#6547]
### Expected behavior
The button / slider defaulting to "Yes" should be responsive and users should be abel to switch to "No" with a click or mouse dragging.

### Actual behavior
Nothing. No matter if that button is clicked or dragged, nothing happens.

### Steps to reproduce the problem
Enter e.g. helpers@forum.friendi.ca into the "Add new contact" field in teh contacts section to get to the dialog in question.

### Friendica version you encountered the problem
squeet.me instance: This is Friendica, version 2019.01 that is running at the web location https://squeet.me. The database version is 1293, the post update version is 1281.

![connect follow button unresponsive](https://user-images.githubusercontent.com/5708172/51906561-a9275480-23c4-11e9-8404-b680de2b7886.png)

**Comment by MrPetovan** [comment]
This color looks like all form elements are disabled, can you click on any of them?
Additionally, please check for Javascript error in the Developer Console of your browser (F12 to bring it up by default).

**Comment by foss-** [comment]
related, setting to dupe of #3717
