### ISSUE TITLE
Postings to a forum are distributed to non-forum-member contacts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6558]
### Expected behavior

If a forum is mentioned with the `!name` notation the posting should be exclusive to the forum and be distributed by the forum to the members.

### Actual behavior

After a posting I was informed by one of my contacts, that they got the posting as well, though they are not member of the forum.

@annando was in the thread, [his reply](https://pirati.ca/display/ec054ce7-195c-509f-c757-56e406742046)

> ja, da ist noch Arbeits­be­darf bei der AP-​Implementation von Fri­en­dica. Da müs­sen wir noch Pro­bleme lösen.

### Friendica version you encountered the problem

2019-03.dev

**Comment by annando** [comment]
It's not a bug, but we have to a design decision.

**Comment by tobiasd** [comment]
It is a bug. Forum posting to `!name` should only be distributed to members of that forum. Instead they reach non-members. That is a bug.

**Comment by rebeka-catalina** [comment]
I also think that it's a bug. A while ago I have seen forum postings in the global community, but I wasn't sure if it's because I'm a member of those forums or not.

**Comment by annando** [comment]
@rebeka-catalina seeing a forum thread in the global community is not a bug at all (As long as it is a public forum). We did so all the time.

**Comment by HankG** [comment]
Ironically the behavior mentioned is the behavior I'm hoping for so that non-forum members can see it and have it attract potential new members.  I do agree that it would be good if there were posts that only propagate to forum members as well.  If new members could see legacy posts the ability to see old forum-private posts would be awesome too.  However I don't believe that federation allows for that sort of a user workflow.  

I am curious though what the default "Permissions" block is doing for forum posts if not limiting distribution though.  When a user makes a personal post that's controlling who can see the post at all IIRC.  The default Permissions on a forum post is forum only.  What is the actual behavior for that setting?  I know it's not creating limited post privacy because the post is renderable in a web browser with a user that isn't logged in.

**Comment by rebeka-catalina** [comment]
On 2019.01.30, Hank G wrote:
> Ironically the behavior mentioned is the behavior I'm hoping for so that non-forum members can see it and have it attract potential new members.

This is possible but for technical reasons that I don't remember in
details this shouldn't be done with the friendica forums.

There is for example a forum for music and sometimes I want to post to
the forum and to my contacts, then I use an @ instead of an
! to mention the forum. This way the post appears also as item
in your profile.

**Comment by tobiasd** [comment]
The technical reasons is, that there arise problems when the posting is distributed over different path (directly to contacts and via more then one forum) the distribution of comments that are made over the different forums leads to not-distribution of the comments to everyone who should get them (as they received the initial posting).

> I am curious though what the default "Permissions" block is doing for forum posts if not limiting distribution though. When a user makes a personal post that's controlling who can see the post at all IIRC. The default Permissions on a forum post is forum only. What is the actual behavior for that setting? I know it's not creating limited post privacy because the post is renderable in a web browser with a user that isn't logged in.

When you select a forum in the ACL, the `!forumname` mention is automatically added to your post (a forum ignores all postings without a mention of the forum account. Only those where it is mentioned in will be distributed to the forum members) and the receivers list is limited to that forum only. Your posting is then send to the node of the forum and that coordinates the distribution to the members of the forum. As well as the distribution of the comments to the members of the forum.

Whe yoiu use the `@forumname` mention syntax, your node and the forum node distribute the posting to your contacts and the forum members. Depending which way the posting took to a receiver, the distribution of a comment will then work or not.

**Comment by HankG** [comment]
> When you select a forum in the ACL, the !forumname mention is automatically added to your post (a forum ignores all postings without a mention of the forum account. Only those where it is mentioned in will be distributed to the forum members) and the receivers list is limited to that forum only. Your posting is then send to the node of the forum and that coordinates the distribution to the members of the forum. As well as the distribution of the comments to the members of the forum.

I understand the message distribution part.  The part I'm getting confused on is view permissions.  If I'm posting to myself the only people who are even allowed to view the post are the people it was directly sent to.  If I use the URL in a browser that isn't logged in the post doesn't render (in experimenting it throws a 404 error).  However in the case of Forum posts those are visible to anyone, including an anonymous user.

**Comment by tobiasd** [comment]
Yes, postings to public forums will be accessible by anybody using the internet. Postings to private forums wont. As postings to any public message board / forum in the internet are.

But you only send out the message to the forum, and don't SPAM your family with boring answers to support requests about Friendica. Which at the moment is (or was?) broken.

**Comment by HankG** [comment]
> Yes, postings to public forums will be accessible by anybody using the internet. Postings to private forums wont. As postings to any public message board / forum in the internet are.

The differentiation between public/private forums and posts isn't obvious in the UI unfortunately. 

> But you only send out the message to the forum, and don't SPAM your family with boring answers to support requests about Friendica. Which at the moment is (or was?) broken.

As long as there is a way to initiate that even if it isn't the default that'd be great. I'm guessing that if you do override permissions to "Share with Everybody" then this would accomplish that.

**Comment by tobiasd** [comment]
> As long as there is a way to initiate

As Rebeka said, you just need to select the targeted audience (e.g. public) and then mention the forum with an `@forumname`. This will distribute the posting to your selected audience and the forum. But you should not mention more then one forum.

But as forums are meant to be a separate channel to distribute a message, this is not the default behaviour of the ACL.

> The differentiation between public/private forums and posts isn't obvious in the UI unfortunately.

True. At the moment you need to know which of your forums are private and which are public.
