### ISSUE TITLE
No Timelines with Redis enabled in config

### ISSUE THREAD

**Issue by imattau** [friendica/friendica#6569]
### Actual behavior
With redis enabled on the server, I added the cache_driver under [system] in the local.config. All pages of Friendica were served, except for any timeline pages. These are all blank.

When removing the cache_driver line from the config, appears to fix the issue.

### Steps to reproduce the problem
Using redis, add cache_driver line to local.config

### Friendica version you encountered the problem
2019.1

### PHP version
7.1
### SQL version
MySQL/MariaDB

**Comment by AlfredSK** [comment]
Have you also configured the redis path and port in your Friendica config file?

**Comment by annando** [comment]
Blank pages most likely generate an entry in the PHP error log. Please have a look for this.
