### ISSUE TITLE
Hash marks in Markdown code blocks are double-escaped

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6570]
Diaspora post: https://pod.orkz.net/posts/ae70d8b007ba0137043300163e3b85e3
Friendica post: https://friendica.mrpetovan.com/display/ae70d8b007ba0137043300163e3b85e3

Expected code block display:
```
ExpiresActive On

#Default = 2 hours
ExpiresDefault A7200

#Expires after 60 seconds
ExpiresByType text/html A60
```

Actual code display:
```
ExpiresActive On 

&#35;Default = 2 hours 
ExpiresDefault A7200 

&#35;Expires after 60 seconds 
ExpiresByType text/html A60
````

To test this issue, the admin-only `/babel` path can be used to verify the formatting conversions to/from Markdown and to/from BBCode are correct.

**Comment by MrPetovan** [comment]
Possibly related to #6554

**Comment by Ixiter** [comment]
Could be related to #6654. Though, I never use the htmlentity  `&#35;` for hashmarkers in my codes. 
Anyways .. I can do some tests on. Please remind me, if I dont come back with a test result.

**Comment by Ixiter** [comment]
Can't reproduce

On my dev host, using develop branch, it works pretty good. 
A test post displayed correct markdown, highlighted by the syntax highlighter addon.

**Comment by MrPetovan** [comment]
Here's the source XML of the Diaspora post I received on my node:
```xml
<status_message>
  <author>goob@pod.orkz.net</author>
  <guid>ae70d8b007ba0137043300163e3b85e3</guid>
  <created_at>2019-01-31T19:16:49Z</created_at>
  <public>true</public>
  <text>### HTTP redirecting advice&#xD;
&#xD;
I've got a few redirects set up on my server, using `Redirect 301` permanent redirects.&#xD;
&#xD;
However, some of these are not permanent: I update them to point to a new page every 2 months, every 6 months or every year as new information becomes available. Would it be better for me to use a temporary code such as `307` for these cases? I also have a list of expire times, which includes the following:&#xD;
&#xD;
	ExpiresActive On&#xD;
	&#xD;
	#Default = 2 hours&#xD;
	ExpiresDefault A7200&#xD;
	&#xD;
	#Expires after 60 seconds&#xD;
	ExpiresByType text/html A60&#xD;
&#xD;
So would this mean that no browser would cache the redirect information for longer than these times? And if so that permanent redirects are all right?&#xD;
&#xD;
One concern of mine is the possibility that search engines might keep results to old pages. The old pages remain and are still valid, so that's not a failure, but I'd like the first result to be the latest page.&#xD;
&#xD;
#webdesign #http #redirect #help</text>
</status_message>
```
What's in `<text>` is ultimately going throught the `Markdown::toBBCode` routine.

**Comment by Ixiter** [comment]
Well, these are no hashmarks. Indented parts in markdown get handled as code blocks. What we see is a  whatever conf snippet and the `#Default` lines are comments in the conf code, not hashes.
The following is just indented no ticks used for that code block.

    <?php
    # as we can use them in PHP
    ?>

**Comment by Ixiter** [comment]
OK, you said that already in the topic :D 
Sorry.

In my tests I couldnt repeat the behaviour of displaying the enties. I see hash marks.

**Comment by Ixiter** [comment]
Sorry I did bad reading of the issue.

However .. I tried both directions -  from a master branch to a develop branch installation and vice versa. Everything displayed
