### ISSUE TITLE
share custom frio color scheme's

### ISSUE THREAD

**Issue by JeroenED** [friendica/friendica#6574]
Ref. Discussion with @Annando at Fosdem 2019

There are several open PRs containing added color scheme to the frio theme and merging them is not wanted.

Another solution for adding these can be by providing a string that automatically applies these. Using this, someone who created a good color scheme can share it with in a status update. People wanting to apply it can just apply it without a guessing colors.

This only requires to add a text input in the customizer and the save button parses the colors from the string.

A sebsequent feature will be creating a direct link to immediately apply it and further to save presets shared by others.

**Comment by MrPetovan** [comment]
I like this concept.

**Comment by AlfredSK** [comment]
Yeah! Me too. :-)

What I would also like is that frio's system colors should also be applied to new user profiles.
If I define a color set for my node in admin panel (which already is implemented) this color set should be the default one for new users as well. But instead the hard-coded default colors of frio are used.

**Comment by JeroenED** [comment]
Since the overwhelming positive reactions I will try to have a working implementation ready for 2019.03 release. Since the code structure is already in my head it's just a matter of spitting it into real code. Might be done this week to be honest.

**Comment by JeroenED** [comment]
I just started to wonder something. What does @rabuzarus think about this? It's his theme and it's up to him if it will be merged.

**Comment by MrPetovan** [comment]
It’s considerate of you to ask, but you aren’t modifying anything from the theme itself, just adding a meta feature, so I think it’s okay.

**Comment by annando** [comment]
I also think that this change it totally okay. @rabuzarus has got a problem with additional colour themes - but this isn't an additional theme, but an enhancement to share and import custom colour changes.

**Comment by rabuzarus** [comment]
I don't remember when but some time ago I have discussed with @MrPetovan about the usefulness of providing the user a possibility to save his/her own color scheme. So I really like the idea of sharing custom color schemes between users.

> There are several open PRs containing added color scheme to the frio theme and merging them is not wanted

@JeroenED 
It is important to me that you understand that I'm not against adding more color schemes, but I'm against adding color schemes which pre-define only the colors the user can change by his/her own.
