### ISSUE TITLE
Profile: Birthday field placeholder shows wrong hint

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6575]
### Expected behavior
Birthday place holder should be YYYY-MM-DD

### Actual behavior
Birthday placeholder is actually "YYYY-MM-DD

### Steps to reproduce the problem
Go to your profile. Edit the profile. Look at the birthday field placeholder if that field is empty.
This minor issue can be misleading. Users might think they have to actually enter the date starting with ".

I think this can be fixed by changing https://github.com/friendica/friendica/blob/441d9530984289aab027be40864a5f4e80607970/src/Util/Temporal.php#L151
to `'placeholder=' . L10n::t('YYYY-MM-DD or MM-DD') . ''`

### Friendica version you encountered the problem
2019.01 and 2019.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
MariaDB 10.1.34

**Comment by MrPetovan** [comment]
The solution is actually to unescape `$field.5` in `view/templates/field_input.tpl` and `view/theme/frio/templates/field_input.tpl`.

**Comment by AlfredSK** [comment]
Haha. That's why I'm no dev. :-)
I just searched the repo for YYYY-MM-DD. Found a matching line in Temporal.php and played with the code of that line on my node until it worked.
