### ISSUE TITLE
Add Markdown as additional/alternative post format

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#6597]
It should be made easier for people with no knowledge of BBCode or Markdown to create lists in the new post editor.

**Comment by MrPetovan** [comment]
The obvious path is supporting Markdown as an additional/alternative post format, renaming this issue.

**Comment by HankG** [comment]
I'm thinking this is a pretty complex job. Is it really a "Junior Job"?

**Comment by MrPetovan** [comment]
Not really. Here's how it is at the moment:
1. Escape BBCode code blocks
2. Convert BBCode to HTML
3. Restore BBCode code blocks

Here's how it can be with Markdown:
1. Escape BBCode code blocks
2. **Convert Markdown to HTML**
3. **Escape HTML code blocks**
4. Convert BBCode to HTML
5. **Restore HTML code blocks**
6. Restore BBCode code blocks

**Comment by tobiasd** [comment]
I would suggest making the Markdown parsing configurable. And either use Markdown or BBCode, I don't think mixing them is a good idea (esp. as Markown already allows usage of HTML code if the Markdown syntax is not sufficient.)

**Comment by MrPetovan** [comment]
Then in this case it would be

1. Depending on the site/user config, EITHER:
    a. Escape BBCode code blocks
    b. Convert BBCode to HTML
    c. Restore BBCode code blocks
2. - OR -
    a. Convert Markdown to HTML

**Comment by tobiasd** [comment]
Is the [Markdown addon](https://github.com/friendica/friendica-addons/tree/develop/markdown) sufficient to close this ticket?

**Comment by annando** [comment]
@tobiasd from my point of view it is.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica-addons/pull/924
