### ISSUE TITLE
Unable to Post After Upgrade to 2019.01

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6604]
Immediately after upgrading, I found that it is impossible to post anything on my website.  😢

I am able to click the New Post button.  All tabs appear to work.  I can upload photos from the browser tab properly.  The Share button behaves as usual, but then my post never appears anywhere.

Tried on Windows and Android.

Using Frio theme.

Is 2019.01 dead on arrival?

**Comment by MrPetovan** [comment]
2019.01 has some rough edges, but none that rough that we knew about! Can you verify in your `item` table that what you post actually shows up in the database? Any PHP error?

**Comment by miqrogroove** [comment]
You will have to bear with me as I'm not super familiar with the schema.

I had attempted the same post 3 times.  I came up with 6 records in the item table.  Three of them are wall = 1 and three of them are wall = 0.  There are 3 records in the item-content table with matching uri-id integers.  And I do see the photo I uploaded in the photo table.

**Comment by MrPetovan** [comment]
Thanks, at least it isn't a data submission error, just a display issue apparently. It may not be easier to troubleshoot, but we've cornered the issue.

**Comment by miqrogroove** [comment]
Is there a way to make sure the cron worker is in a good status?

**Comment by MrPetovan** [comment]
If you go to the admin overview page, you can see the state of the worker queues, the one to watch is the third one. Additionally, a message is displayed if the worker hasn't ran for over an hour.

**Comment by miqrogroove** [comment]
All the queues show zero in the admin panel.  But in the workerqueue table there are around 11 rows with done = 0.

**Comment by MrPetovan** [comment]
What does the `executed` and `next_try` fields look like for those 11 rows?

**Comment by miqrogroove** [comment]
That table doesn't have a next_try column 😳
```
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto incremented worker task id',
 `parameter` mediumblob COMMENT 'Task command',
 `priority` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Task priority',
 `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Creation date',
 `pid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Process id of the worker',
 `executed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Execution date',
 `done` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Marked 1 when the task was done - will be deleted later',
```

**Comment by MrPetovan** [comment]
You're missing the `next_try` and `retrial` columns in the `workerqueue` table in this output, which is weird because you shouldn't have been able to load the admin main page.

Please run `bin/console dbstructure update --force` just in case.

**Comment by miqrogroove** [comment]
Also this...

```
SELECT id,parameter FROM `workerqueue` WHERE done = 0

id	parameter	
358468	
    ["DBUpdate"]
	
358469	
    ["SpoolPost"]
	
358470	
    ["Cron"]
	
358471	
    ["Notifier","wall-new","2850"]
	
358472	
    ["CreateShadowEntry","2850"]
	
358473	
    ["Notifier","wall-new","2852"]
	
358474	
    ["CreateShadowEntry","2852"]
	
358475	
    ["Notifier","wall-new","2854"]
	
358476	
    ["CreateShadowEntry","2854"]
	
358477	
    ["Notifier","wall-new","2856"]
	
358478	
    ["CreateShadowEntry","2856"]
```

I will try the force update next.

**Comment by miqrogroove** [comment]
The force update command definitely made several changes.

**Comment by miqrogroove** [comment]
Previous post attempts are lost in oblivion, but new posts are working now.

Is there anything we need to do to ensure the database update runs after the git pull?  Should this be in the upgrade instructions?

**Comment by annando** [comment]
To update from a version before 2019.1 this ```bin/console dbstructure update``` is needed. Possibly we should add this in the documentation. This ```--force``` is only needed on special occasions.

**Comment by miqrogroove** [comment]
This needs to be updated then https://friendi.ca/2019/01/21/friendica-2019-01-released/

It only mentions server server load and such, not that the extra command is required after the pull.

Also noticed my site is slow to load on any page with posts on it, even after the DB fix.  But at least it works now.

**Comment by MrPetovan** [comment]
It actually is mentioned in the `Known Problems` section of this blog post.

**Comment by nupplaphil** [comment]
> 
> 
> This `--force` is only needed on special occasions.

addendum: Yep, this is only needed in case the update got "stuck" in between so a retry would be impossible otherwise (due to a "deadlock").

**Comment by miqrogroove** [comment]
A bit unhappy about this because the product offers no indication that the database revision has begun or become stuck.  But my site is working so carry on.

**Comment by MrPetovan** [comment]
I'm not sure how we can detect this state yet but this is an interesting exploration avenue.
