### ISSUE TITLE
MySQL Unix Socket support

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#6606]
Would it be possible to also support MySQL connections via Unix Socket rather than TCP? I understand that for multifunctional servers (database and web server on same server), performance can be better using sockets due to not having the overhead of TCP, ie improvements in throughput and latency.

**Comment by MrPetovan** [comment]
Technical reference: https://secure.php.net/manual/en/ref.pdo-mysql.connection.php

**Comment by MrPetovan** [comment]
This has been implemented.
