### ISSUE TITLE
Uncaught TypeError PortableContact

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#6607]
PHP Error log contains many of these:
'08-Feb-2019 09:25:37 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Protocol\PortableContact::discoverServerUsers() must be of the type array, null given, called in /srv/http/src/Protocol/PortableContact.php on line 1700 and defined in /srv/http/src/Protocol/PortableContact.php:1762
Stack trace:
#0 /srv/http/src/Protocol/PortableContact.php(1700): Friendica\Protocol\PortableContact::discoverServerUsers(NULL, Array)
#1 /srv/http/src/Worker/DiscoverPoCo.php(75): Friendica\Protocol\PortableContact::discoverSingleServer(8102)
#2 [internal function]: Friendica\Worker\DiscoverPoCo::execute('update_server_d...', 8102)
#3 /srv/http/src/Core/Worker.php(369): call_user_func_array('Friendica\\Worke...', Array)
#4 /srv/http/src/Core/Worker.php(258): Friendica\Core\Worker::execFunction(Array, 'DiscoverPoCo', Array, true)
#5 /srv/http/src/Core/Worker.php(100): Friendica\Core\Worker::execute(Array)
#6 /srv/http/bin/worker.php(60): Friendica\Core\Worker::processQueue(false)
#7 {main}
 thrown in /srv/http/src/Protocol/PortableContact.php on line 1762'

Current develop from about 36h ago and PHP 7.3.2.

**Comment by MrPetovan** [comment]
Moved to https://github.com/friendica/friendica/issues/6386#issuecomment-461799483
