### ISSUE TITLE
Display an admin notice when the database structure isn't up-to-date

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6609]
Stemming from #6604

Currently, aside from willfully going to `/admin/dbsync/`, there's no obvious indication in the admin panel that the database structure isn't correctly updated to the latest revision.

This leads to odd errors and general confusion, as the database structure update is supposed to be automatic.

The message should inform of the database structure version discrepancy and offer a link to `/admin/dbsync/` as well as the manual console command to update the structure: `bin/console dbstructure update`.

**Comment by annando** [comment]
I thought of some automatism in the worker.

**Comment by MrPetovan** [comment]
We now have a couple of conditional messages:
- `The database update failed. Please run "php bin/console.php dbstructure update" from the command line and have a look at the errors that might appear.`
- `The last update failed. Please run "php bin/console.php dbstructure update" from the command line and have a look at the errors that might appear. (Some of the errors are possibly inside the logfile.)`
