### ISSUE TITLE
Share box lost all the tools including the post buttons

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#6618]
### What should happen
Clicking into the [Share] textbox to make a new status message should display buttons and editor tools or other information.

### What does happen
It just remains an inactivated status box.
![screenshot from 2019-02-09 16-13-11](https://user-images.githubusercontent.com/28640985/52526388-c3471980-2c85-11e9-8ef5-a2cf791f4da5.png)

### Steps to reproduce the problem
Hard to say. This is a brand new Friendica server. It definitely worked 3 days ago. I've been working the last couple days at turning on many of the cool options available from the standard plugins. I don't know when the trouble arose, but I noticed it today after not getting the XMPP plugin to work right.

### Friendica version you encountered the problem
This is Friendica, version 2019.01 that is running at the web location https://social.outsourcedmath.com. The database version is 1293, the post-update version is 1281.

### Friendica source (git, zip)
git clone https://github.com/friendica/friendica.git -b master public_html

### PHP version
7.2.10

### SQL version
MariaDB 10.1.38

**Comment by MrPetovan** [comment]
Hi @WNYmathGuy and thanks for the report.

Please test these steps:
1. Disable all addons
2. Clear your browser cache
3. Check for Javascript errors in Developer Console (F12 to bring it up)
4. Change theme for frio (you will have to enable it first in the admin page)

To see if it still happens.

**Comment by WNYmathGuy** [comment]
Thanks @MrPetovan 
All add-ons are disabled right now. Tried it with browser cache cleared as well as in a browser that never gets used. Both had the problem persist. Despite opening the Developer Console, I don't know how to make it display the Javascript errors. One unexpected thing was the ability to comment on an existing post works normally. Another strange thing is the frio theme's [new post] button is ineffective. It's like a placebo button.

This is probably a red-herring, but... In the last 24 hours, I installed ejabberd, changed my mind and purged it, then installed jabber2, then uninstalled that and reinstalled ejabberd, thought I had finally set things up correctly, saw the posting problem and panicked into uninstalling ejabberd again. After that I showed up here making this issue. Is it possible that any shared program got removed?

![screenshot from 2019-02-09 19-28-37](https://user-images.githubusercontent.com/28640985/52528177-72dfb400-2ca5-11e9-9ce3-a291dca81484.png)

![screenshot from 2019-02-09 19-53-21](https://user-images.githubusercontent.com/28640985/52528183-b9cda980-2ca5-11e9-99e9-16e6b055b354.png)

**Comment by MrPetovan** [comment]
If the frio New Post button doesn't work, something is really wrong with your setup.

I just created an account on your server, tried both vier and frio, and both new post behaviors worked for me. By now I assume it has to do with your own browser, can you try with another one? In a private window with extensions disabled?

**Comment by AlfredSK** [comment]
@WNYmathGuy and @MrPetovan 
The issue with the new post button in frio is that nasty bug in 2019.01 (master). If the user has enabled 'Use Browser Location' in Settings -> Basic Settings -> Post Location the modal for new posts is not loaded.

**Comment by WNYmathGuy** [comment]
Thanks @AlfredSK 
That was the thing. I unchecked that checkbox and saved the settings.
![screenshot from 2019-02-10 14-33-33](https://user-images.githubusercontent.com/28640985/52538480-1af68b00-2d41-11e9-9308-65626882b26b.png)

### After unchecking it.
![screenshot from 2019-02-10 14-33-54](https://user-images.githubusercontent.com/28640985/52538482-1fbb3f00-2d41-11e9-8d3a-3463be67938a.png)
