### ISSUE TITLE
[frio] Sharing a post from the display page does not work

### ISSUE THREAD

**Issue by romariorios** [friendica/friendica#6635]
### Expected behavior

The share popup should appear, allowing you to share the post

### Actual behavior

The page fades, but the popup never appears

### Steps to reproduce the problem

1. Open any individual post by clicking the date
2. At the display page, click the share button

### Friendica version you encountered the problem

This is Friendica, version 2019.03-dev that is running at the web location https://libranet.de. The database version is 1302, the post update version is 1297.

**Comment by AlfredSK** [comment]
Yup. Confirmed.

Related errors from web console with an example reshare attempt:
````
SyntaxError: invalid regular expression flag s ... linkPreview.js:513:80
TypeError: $(...).linkPreview is not a function ... 2df00200f980137e85f2a0000053625:385:40
jotShow https://libranet.de/display/42df00200f980137e85f2a0000053625:385 
jotShare https://libranet.de/display/42df00200f980137e85f2a0000053625:269 
onclick https://libranet.de/display/42df00200f980137e85f2a0000053625:1
````

**Comment by rabuzarus** [comment]
Thanks for reporting. Maybe I will find some time for fixing the issue on Thursday

**Comment by rabuzarus** [comment]
I tried to reproduce the issue on libranet but when I reproduce the steps everything is working like expected

@AlfredSK
Please update your browser cache and give me a link to an item on libranet where the issue appears.

I tried https://libranet.de/display/42df00200f980137e85f2a0000053625 but there everything is working like it should

**Comment by rabuzarus** [comment]
ha ha - only FF is affected by this issue
argh

**Comment by AlfredSK** [comment]
So, @rabuzarus do you still need something from me?
