### ISSUE TITLE
XMPP configuration troubles...

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#6636]
I'm a newbie to Friendica and XMPP via ejabberd.
### Expected behavior
The chat window should auto-login using the Friendica stored credentials for the users on the system.

### Actual behavior
It tries to but has an infinite wait graphic spinning.
![screenshot from 2019-02-10 17-42-54](https://user-images.githubusercontent.com/28640985/52540876-9e71a580-2d5c-11e9-9aab-b54d6a9e0a87.png)

### Steps to reproduce the problem
1. Install ejabberd
1. Edit the `/bin/ejabberd/ejabberd.yml` file to include the virtualhost domain name with the BOSH connector thingie text record on my domain name service [mod_bosh](https://docs.ejabberd.im/admin/configuration/#discovery) .
1. Follow the instructions at the top of the `~/bin/auth_ejabberd.php` file making the appropriate changes.
```
auth_method: external
extauth_program: "/home/vserveradmin/domains/social.outsourcedmath.com/html/bin/auth_ejabberd.php"
```
4. Restart ejabberd and click the checkbox.
![screenshot from 2019-02-10 17-49-38](https://user-images.githubusercontent.com/28640985/52540961-a716ab80-2d5d-11e9-90dd-ce49c840c2cf.png)

### Friendica version you encountered the problem
This is Friendica, version 2019.01 that is running at the web location https://social.outsourcedmath.com. The database version is 1293, the post-update version is 1281.

### Friendica source (git, zip)
git clone https://github.com/friendica/friendica.git -b master public_html

### PHP version
7.2.10

### SQL version
MariaDB 10.1.38

**Comment by WNYmathGuy** [comment]
P.S. This morning I tried switching plug-in's parameter and the `ejabberd.yml` file to 
```
hosts:
  - "localhost"
```
from
```
hosts:
  - "jabber.outsourcedmath.com"
```
and it made no difference.

**Comment by realkinetix** [comment]
I would recommend setting your ejabberd loglevel to 5, restart ejabberd, and then report back what you're seeing in your logs.  You may also want to test from a normal XMPP client (pidgin, gajim, etc.) to see if you can login using your Friendica credentials as well.  However, information on what's happening should show up in the ejabberd logs.

**Comment by annando** [comment]
Have you checked, whether you can use the XMPP server with the Friendica credentials with a regular client?

BTW: The XMPP addon seems to break some stuff with the Frio theme. So it isn't recommended to use it at the moment. We would need someone who could have a look at it.

**Comment by WNYmathGuy** [comment]
@realkinetix Their's a lot of this in the `/var/log/ejabberd/error.log` and `/var/log/ejabberd/ejabberd.log` files.
```
2019-02-11 22:01:07.211 [critical] <0.1809.3>@extauth:loop:137 extauth script has exitted abruptly with reason 'normal'
```
I'm such a Jabber newbie that I don't even know what I don't know. Thus, I don't really know how to set up a Pidgin connection correctly, so I don't know if the Pidgin failure message is from badly setting things or because of something else.
```
wnymathguy@social.outsourcedmath.com/ disconnected
SSL Connection Failed
```

@annando I'm not sure I understood the first question but was it what realkinetix asked me to do? I'm not using the Frio theme right now though.

**Comment by realkinetix** [comment]
When you're getting that extauth script failure error, there could be a couple of issues.  It's possible that you're running a distribution that runs systemd, and has things like "ProtectHome=true" in /etc/systemd/system/multi-user.target.wants/ejabberd.service - which completely breaks expected user/group privileges on unix, but hey, systemd is the bomb.  (Pardon the sarcasm... I had to fight with this on my system - Distros are doing completely unexpected things with their new systemd toy.).

If that's the case, comment out the ProtectHome line and restart ejabberd.

If that's not the case, perhaps you have the path incorrect in ejabberd.yml?  ...  But, I'll bet it's the systemd setup getting in your way.

However, that said - I would strongly suggest getting a bit familiar with XMPP before running your own ejabberd that's open to the public.

**Comment by WNYmathGuy** [comment]
@realkinetix You were right, that file had `ProtectHome=true` in it. Oddly on my system, the entity `/etc/systemd/system/multi-user.target.wants/ejabberd.service` is a symbolic link to somewhere I don't know how to find. I used my GUI to edit that file. I double checked by downloading the sym-link and saw the edit I made was there; `#ProtectHome=true`. I was still getting the same error after restarting the service, so a tried a full server reboot and still the error persists.

I doublechecked the path statement in that `ejabberd.yml` file for the `exauth_program` parameter by copying a valid path statement created with {first letter}-{tab key} repeats in my Terminal window to the line under the one in the YML file and checking each character one at a time. No mistakes in that path.

I'll heed your advice and ditch the XMPP IM toy because I don't have the time to learn about it now, but it would be nice to get it to work for the next "me" type person that comes along with the same problem.

Just for completeness in this thread, I'm on a Ubuntu 18.04 LTS server with all updates done. I installed ejabberd with the Ubuntu command `sudo apt-get -y ejabberd`. I changed as little as possible to the YML file as possible; only where instructed to by [ejabberd](https://docs.ejabberd.im/admin/configuration/) and Friendica/here. In my Systemd manager, this is the default contents of the two related ejabberd items:


`ejabberd`
<details>

<pre>
#! /bin/sh

### BEGIN INIT INFO
# Provides:          ejabberd
# Required-Start:    $remote_fs $network $named $time
# Required-Stop:     $remote_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts ejabberd jabber server
# Description:       Starts ejabberd jabber server, an XMPP
#                    compliant server written in Erlang.
### END INIT INFO

# chkconfig: 2345 90 10
# description: ejabberd XMPP server

set -o errexit

. /lib/lsb/init-functions

DIR=/usr/sbin
CTL="$DIR"/ejabberdctl
USER=ejabberd
EJABBERDRUN=/run/ejabberd

test -x "$CTL" || {
	log_daemon_msg "ERROR: ejabberd not found: $DIR"
	exit 1
}

mkrundir()
{
	if [ ! -d $EJABBERDRUN ]; then
		mkdir -p $EJABBERDRUN
		if [ $? -ne 0 ]; then
			log_daemon_msg -n " failed"
			return
		fi
		chmod 0755 $EJABBERDRUN
		chown ejabberd:ejabberd $EJABBERDRUN
	fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    test -x "$CTL" || exit 0
    mkrundir
    log_daemon_msg "Starting ejabberd..."
    if ! /etc/init.d/ejabberd status > /dev/null; then
	su - $USER -c "$CTL start"
	su - $USER -c "$CTL started"
    fi
    log_daemon_msg "done."
    ;;
  stop)
    test -x "$CTL" || exit 0
    log_daemon_msg "Stopping ejabberd..."
    if $CTL status >/dev/null || test $? = 1 ; then
	su - $USER -c "$CTL stop"
	su - $USER -c "$CTL stopped"
    fi
    log_daemon_msg "done."
    ;;
  status)
    test -x "$CTL" || exit 0
    log_daemon_msg "Getting ejabberd status..."
    su - $USER -c "$CTL status"
    ;;
  force-reload|restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 3
    ;;
esac

exit 0
</pre>

</details>

<br />

`ejabberd.service`
<details>

<pre>
[Unit]
Description=A distributed, fault-tolerant Jabber/XMPP server
Documentation=https://www.process-one.net/en/ejabberd/docs/
After=epmd.service network.target
Requires=epmd.service

[Service]
Type=forking
User=ejabberd
Group=ejabberd
LimitNOFILE=65536
Restart=on-failure
RestartSec=5
ExecStart=/bin/sh -c '/usr/sbin/ejabberdctl start && /usr/sbin/ejabberdctl started'
ExecStop=/bin/sh -c '/usr/sbin/ejabberdctl stop && /usr/sbin/ejabberdctl stopped'
ExecReload=/bin/sh -c '/usr/sbin/ejabberdctl reload_config'
PrivateTmp=true
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
</pre>

</details>

<br />

OS management GUI Web interface
<details>

![screenshot from 2019-02-12 11-50-49](https://user-images.githubusercontent.com/28640985/52652874-e1e32580-2ebc-11e9-9050-4614c7040ef8.png)

</details>

**Comment by poVoq** [comment]
> BTW: The XMPP addon seems to break some stuff with the Frio theme. So it isn't recommended to use it at the moment. We would need someone who could have a look at it.

I think much of these issues would be solved simply by updating ConverseJS to the latest version. There have been massive improvements since the 4.0 version in nearly all regards.

**Comment by annando** [comment]
@poVoq Yes, Converse should be updated - but I simply failed by trying to do so. So I would like to delegate this task to someone else.

**Comment by MrPetovan** [comment]
I wouldn't mind, but I failed to set up my own XMPP server, so I have nothing to test ConverseJS with.

**Comment by poVoq** [comment]
There are millions of open for registration xmpp servers you could test it with :) See: https://xmpp.net/directory.php

jix.im for example runs a recent version of ejabberd and provided BOSH access.

**Comment by MrPetovan** [comment]
Ha, good to know, I thought it was specific to locally-ran XMPP server. I'm knee-deep in implicit mentions at the moment, but I might look at it next.

**Comment by WNYmathGuy** [comment]
@poVoq How do you determine what XMPP hosts in that list you linked to have a BOSH host? Also, that jix.im, I can't find anything about them having a BOSH host.

**Comment by poVoq** [comment]
I don't think it is specifically mentioned anywhere, but most ejabbered servers should support it. See here for a lot more XMPP compliance data: https://compliance.conversations.im/

In the caseof jix.im it is mentioned on the information page: https://jix.im/en/informations/
The actual BOSH url is: https://xmpp.jix.im/bosh

**Comment by WNYmathGuy** [comment]
@poVoq so is the Jabber server `https://xmpp.jix.im` and the user ID `somebody@jix.im` ? 

I'm going to try it in the "Jappix Mini" plugin.

**Comment by poVoq** [comment]
Jappix Mini is extremely outdated and hasn't been in development for multiple years. I am not sure why it is even still included in Friendica.

It might be that the xmpp. part is only used for the BOSH... as far as I know it simply a DNS entry to where the actual server is, so I would use only jix.im as the server address as intended.

**Comment by WNYmathGuy** [comment]
Thanks @poVoq I'll disable that Jappix Mini then. The other XMPP plugin worked fine.

Something I didn't realize before opening this ticket is the Admin doesn't need to set-up anything for it to work for users. That's only if somebody wanted their Friendica server to have a tightly controlled XMPP service (_I guess for privacy reasons_). As long as the Admin has not disabled the "XMPP-Chat (Jabber)" plugin all users have the ability to just put their XMPP servers info in their own `Settings » Plugins » XMPP-Chat (Jabber)` and then log into the chat widget. If a user wants to be found easily, their `Settings » Profiles » Basic information` section has a place to put their "XMPP (Jabber) address". 

Like a math book, it's all clear after you understand it, but 100% opaque before you understand it.
