### ISSUE TITLE
On Diaspora, my comments mention myself

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6656]
### Expected behavior

 - I write a comment on Friendica, no mentions.
 - On Diaspora, the comment looks about the same.

### Actual behavior

 - I write a comment on Friendica, no mentions.
 - On Diaspora, the comment starts with `@clacke`.

https://libranet.de/display/0b6b25a8-135c-6519-0784-cda733887484

https://verge.info.tm/posts/29819#0b6b25a8-135c-6519-0784-cda733887484

### Friendica version you encountered the problem

`This is Friendica, version 2019.03-dev that is running at the web location https://libranet.de. The database version is 1302, the post update version is 1297.`

**Comment by annando** [comment]
This is related to https://github.com/friendica/friendica/pull/6614

**Comment by clacke** [comment]
Yeah, this is a duplicate of part of the ongoing conversation in #6552 too. Closing.
