### ISSUE TITLE
Separate id for logger per single workerqueue task

### ISSUE THREAD

**Issue by annando** [friendica/friendica#6658]
### Expected behavior
Every single workerqueue task should have its own logger id to easily find related logger entries.

### Actual behavior
Currently the logger creates entries like ```{"file":"Worker.php","line":802,"function":"tooMuchWorkers","uid":"ea667bb","process_id":4225}``` where the "uid" value stays the same during the whole lifetime of the process. This drastically reduces the ability to debug problems.

### Friendica version you encountered the problem
2019.3dev

**Comment by nupplaphil** [comment]
Fixed with #6723
