### ISSUE TITLE
Fatal Error- Uncaught Error: Call to undefined function Friendica\Module\mime_content_type()

### ISSUE THREAD

**Issue by chuckdee68** [friendica/friendica#6659]
### Expected behavior

Updated to latest friendica 2019.1.

### Actual behavior

PHP Fatal error:  Uncaught Error: Call to undefined function Friendica\Module\mime_content_type() in /src/Module/Proxy.php:194 (redacted first part of path)

### Friendica version you encountered the problem

2019.1

### Friendica source (git, zip)
zip

### PHP version
7.2

### SQL version
5.7

**Comment by MrPetovan** [comment]
It seems like you're missing the `fileinfo` extension on your PHP installation.

**Comment by chuckdee68** [comment]
Thanks!  I worked through that and some other errors and everything is working fine now!

**Comment by tobiasd** [comment]
So, the installer needs to check for the existence of that extension?

**Comment by MrPetovan** [comment]
For the archive version yes, otherwise Composer is doing the check for the Git clone version.

**Comment by tobiasd** [comment]
So it has to be added.

**Comment by MrPetovan** [comment]
Yep.
