### ISSUE TITLE
Maintenance job interupts related to specific user

### ISSUE THREAD

**Issue by danielbierstedt** [friendica/friendica#6661]
### Actual behavior
Maintenance Job interupts with status 255 since update to 2019.01 - 1293

### Friendica version you encountered the problem
2019.01 - 1293

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
Zip

### PHP version
7.2

### SQL version
10
[[NAS]Aufgabenplaner hat eine geplante Aufgabe abgeschlossen.txt](https://github.com/friendica/friendica/files/2870578/NAS.Aufgabenplaner.hat.eine.geplante.Aufgabe.abgeschlossen.txt)

**Comment by MrPetovan** [comment]
Where do you see the 255 error code? Did you enable your node's debug log? You can then look for entries mentioning `worker`.

**Comment by danielbierstedt** [comment]
I see this from the worker background output, I get that emailed. I attached the file to the original post. I did not enable the debug log, because that is usually very much and (for me) mostly not helpful... But I can do if you want me to.

**Comment by MrPetovan** [comment]
Yes, you can enable it temporarily, and when you get another email from your cronjob, you can turn it off and filter all the lines that mention "worker".

**Comment by danielbierstedt** [comment]
to be honest, I don't see anything interesting relating to workers...

`10116 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:705:tooMuchWorkers   Load: 3.95/50 - processes: 0/1/2741 - maximum: 4/5
10117 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:709:tooMuchWorkers   Active workers: 1/4 Fork a new worker.
10118 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:548:maxConnectionsReached    Connection usage (system values): 1/151
10119 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:1017:runCron Add cron entries
10120 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:705:tooMuchWorkers   Load: 3.95/50 - processes: 0/1/2742 - maximum: 4/5
10121 2019-02-17T11:30:03Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:709:tooMuchWorkers   Active workers: 1/4 Fork a new worker.
10122 2019-02-17T11:30:04Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:705:tooMuchWorkers   Load: 3.95/50 - processes: 0/1/2743 - maximum: 4/5
10123 2019-02-17T11:30:04Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:709:tooMuchWorkers   Active workers: 1/4 Fork a new worker.
10124 2019-02-17T11:30:04Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:819:findWorkerProcesses  Deferred: 0 - Total: 2743 - Maximum: 1 - jobs per queue: 1
10125 2019-02-17T11:30:04Z@log:31773:5c6945bb9285c155 [Debug]:Worker.php:548:maxConnectionsReached    Connection usage (system values): 1/151
10126 2019-02-17T11:30:04Z@log:31773:5c6945bb9285c155 [Info]:Worker.php:330:execFunction  Process 31773 - Prio 20 - ID 71704: Notifier ["Notifier","comment-n      ew","182835"] - Process PID: wrk:31773:5c6945bc2827b581
`

**Comment by MrPetovan** [comment]
Thanks, I'm not sure how to help you further debug, I'll refer you to @annando

**Comment by danielbierstedt** [comment]
thanks. I can link the whole file somewhere, if needed.

**Comment by annando** [comment]
Looks a little bit like this known memory problem with JSON-LD.

**Comment by danielbierstedt** [comment]
You have a link or anything to that memory issue? To be honest, I don't think that's the case. This happens since activation of AP and only for a specific user from Mastodon (I believe). So, to me it looks more like a protocol issue.

**Comment by annando** [comment]
The memory issue happened because of specific AP accounts - so we both are right :grimacing: 

When a JSON-LD can't be parsed, we throw an error - but since the error message contains the parsed content, this could lead to memory issues.

**Comment by danielbierstedt** [comment]
Oh... I see. Since I have no idea how to block that specific user - I'll try to find out how to disable AP for now.

**Comment by annando** [comment]
Are you on RC? If not, you really should switch to it.

**Comment by danielbierstedt** [comment]
No, I'm running:

Friendica 'The Tazmans Flax-lily' 2019.01 - 1293

Usually, my plan is to stick to the stable releases. Is that wrong here?

**Comment by tobiasd** [comment]
> Since I have no idea how to block that specific user

If you are the admin of a node, you can block users and other nodes from further communication with your node from the admin panel. I don't think that a block on the users base (as you as user blocks somebody) will change this issue, as their content may still arrive on the node, just not in the users stream.

**Comment by tobiasd** [comment]
> Usually, my plan is to stick to the stable releases. Is that wrong here?

No, it is not. But in this case the 2019.03-RC should *soon* become the stable release and is almost stable already. There are just some bugs on the list of the milestone left, many (almost all? I don't have counted them) of them from before the 2019.01 release.

**Comment by danielbierstedt** [comment]
So, this might sound stupid, but I cannot find a ressource to download the RC. Is that update only possible using git?

**Comment by tobiasd** [comment]
Not stupid at all. But yes, the RC is only available via git (same as the development code).

You could download the tar-archive that github generates. But this is missing the dependency files that are managed using composer. So if you use that tar-archive, you would need to run `bin/composer.phar install --no-dev` on the command line, after you uploaded the contents of the archive to your server.

**Comment by danielbierstedt** [comment]
Okay... same for the plugins or do I ignore that?

**Comment by MrPetovan** [comment]
If you're using Git, your addon install should be on the same branch as your base install.

**Comment by danielbierstedt** [comment]
Sorry, not using Git. Why? WTF?
Easy.
1. I'm running this stuff on a Synology NAS. To be able to use git, I need to install the git package, which comes with the server and everything. Lots of overhead for such a small device.
2. I'm planning to offload Friendica onto my shared hoster (All-Inkl) - or at least I'm thinking about it. Then, I'll only be able to upload stuff by FTP. Yes, I could have a shaddow copy on a Ubuntu Laptop, but... Thats somehow additional, unnecessary effort.
Right or wrong? Other ideas?

**Comment by MrPetovan** [comment]
It's up to you, of course. In this case, you can download an archive of [the friendica/friendica-addons repo](https://github.com/friendica/friendica-addons) on any branch.

The current RC branch state is https://github.com/friendica/friendica-addons/archive/2019.03-RC.zip for example.

**Comment by annando** [comment]
You can install the git server package for your NAS. Then you do have the "git" command line tool as well.

**Comment by annando** [comment]
@danielbierstedt how is the current status?

**Comment by danielbierstedt** [comment]
@annando Sorry and thanks for the wake up call.

To be honest, I had the server down for some weeks and I'm not sure if I'm going to continue with Friendica (or better, any alternative social media system). Reason here is first this install issues. I think, Friendica was never meant to run on a small NAS, given the install and maintenance needs and, of course, the system load. Disk IO is a huge problem here for me.

And the more personal issue: I never found people with similar interests or any real meaningful discussions about stuff I care. Looks to me its either politics or the daily breakfast... But thats a personal issue for me.

Anyway, you may close this issue, thanks for your help so far. I'll think how to continue, maybe you read my name again - or not.

Daniel

**Comment by annando** [comment]
Friendica does run well on small devices like Raspis. But running on Synology NAS is more complicated. I'm running a Nextcloud server on this and not everything runs smoothly out of the box.

It's sad that you haven't found something interesting. But that's life.

BTW: You can close the issue by yourself as well.

**Comment by danielbierstedt** [comment]
@annando You are right, thats how life goes and it was not intended to be a complaint. Just informational.
