### ISSUE TITLE
Worker process returning unexpected results

### ISSUE THREAD

**Issue by chuckdee68** [friendica/friendica#6662]
### Expected behavior
Cron job to be recognized

### Actual behavior

Dashboard shows that worker process has not been run, and the return from the cron job is only 

Content-type: text/html; charset=UTF-8

Repeated over and over

### Steps to reproduce the problem

Cron job set up every 15 minutes as

/opt/cpanel/ea-php72/root/usr/bin/php /home/[redacted]/rpg.pbem.online/bin/worker.php

### Friendica version you encountered the problem

Friendica, version 2019.01 that is running at the web location http://rpg.pbem.online. 
The database version is 1293, 
the post update version is 1281.

### Friendica source (git, zip)
zip

### PHP version
7.2

### SQL version
MySQL 5.7

**Comment by MrPetovan** [comment]
The worker should be ran from the Friendica base install, so please try
```
cd /home/[redacted]/rpg.pbem.online/ && /opt/cpanel/ea-php72/root/usr/bin/php bin/worker.php
```
instead.

**Comment by chuckdee68** [comment]
Thanks!  That worked!
