### ISSUE TITLE
On-click post import / conversation of non-contacts via URL

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6665]
I'm thinking (very raw thoughts)  of a new feature where you can import a single public post, when you have the URL like in such a comment

> Ich finde, wir sollten etwas mit den Maskottchen machen, die @lostinlight in diesem Post vorgestellt hatte: https://iliketoast.net/posts/cd1ec940ec630136eaa56c626dd55703

Maybe there is a way for an option, that I as a reader can not just jump to that public post on the other platform, but also tell friendica to import it to my stream, so I can comment or like it or (hopefully not) block that account or something.

**Comment by AlfredSK** [comment]
Very nice idea. Possible workflow: enter the URL in the search field, hit enter, item is displayed as single post view (.../display/...).
There is already an issue for that: https://github.com/friendica/friendica/issues/6022

**Comment by hoergen** [comment]
Ok, then this post is a double and I close it let's proceed at https://github.com/friendica/friendica/issues/6022
