### ISSUE TITLE
Provide tar.gz for vresion friendica-full-2019.01

### ISSUE THREAD

**Issue by anmol26s** [friendica/friendica#6666]
Hi
It would be nice if you can provide the tar.gz for the friendica-full-2019.01 along with tar.bz2.

https://github.com/friendica/friendica/releases/download/2019.01/friendica-full-2019.01

Thanks

**Comment by tobiasd** [comment]
> It would be nice if you can provide the tar.gz for the
> friendica-full-2019.01 along with tar.bz2.

That would then have to be uploaded at a different spot into the interwebs, as github has a size limitation which is too small for tar.gz or zip files. At the moment we use github, as the releasdes are automatically created there, alongside the incomplete archive files.

What is your problem with the bzip compressed archive?

**Comment by MrPetovan** [comment]
> That would then have to be uploaded at a different spot into the interwebs

What about on https://friendi.ca ?

**Comment by tobiasd** [comment]
Same issue (at least it is an issue for me), it would mix locations. Also Michael would have to upload the files to the server.

One can easily convert the tar.bz2 file into tar.gz via `bunzip2 -c < friendica-full-2019.01.tar.bz2 | gzip -c > friendica-full-2019.01.tar.gz` locally. But then one could also use the bzip archive directly.

**Comment by MrPetovan** [comment]
Is bzip2 universally available?

**Comment by tobiasd** [comment]
I've never installed bzip on my systems actively is all I can say about that ;-)

**Comment by anmol26s** [comment]
We don't have Yunohost helper for tar.bz.

**Comment by tobiasd** [comment]
I see. And Yunohost does not work with git?

**Comment by tobiasd** [comment]
The upload limit at friendi.ca is large enough, so you can find the file there [friendica-full-2019.01.tar.gz](https://friendi.ca/wp-content/uploads/2019/02/friendica-full-2019.01.tar.gz).
