### ISSUE TITLE
Dev: Decide if pdesc contains a title or a description

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#6670]
### Expected behavior
Either have a title or a description field but not one field for both

### Actual behavior
At the moment we have a profile field where the profile owner can insert either his/her title or
his/her profile description (https://github.com/friendica/friendica/blob/2019.01/config/dbstructure.config.php#L1023).
Because a title is something different than a short description we should limit the field to one meaning.
Personally I vote for description because I see the value of having a short description which does describe the profile in one or two short sentence(s).

### Friendica version
2019.01 stable

**Comment by tobiasd** [comment]
As there is also the field for the content of "Tell us something about you" (which sounds like a short description or summery) I would think that field as a title.

**Comment by rabuzarus** [comment]
@tobiasd 
I see it from a different perspective. The "Tell us something about you" is the the big `about` field where people are telling about their vita, forums about their conditions and shops about their opening hours.

As a theme developer I would like to have a a field where the profile owner can describe in a very short way (1 or 2 sentences) what this profile is about.

In a later step I would like to discuss if we can store it in the `contact` table so I can make use it in Frio's hover card. This would have the advantage that you don't hav

**Comment by AlfredSK** [comment]
But we have to be aware that we federate our "about" (tell us about...) field to Diaspora's "bio" field.
On the other hand we are showing the title/description on the global directory.

**Comment by rabuzarus** [comment]
To illustrate what I mean: Have a look at https://libranet.de/profile/socialcenterhasi/?tab=profile
On the left side in the vcard there is the `pdesc` and in the profile content box is the `about` field

**Comment by rabuzarus** [comment]
Don't get me wrong a short description can also contain a clarifying title like `Administrator`like @AlfredSK is doing in his profile. But if we call the field also `Title` it is a little bit misleading because from my point of view we should use a term which animates the user to chose more descriptive title (e.g. for @AlfredSK  `Administrator of libranet.de`)

**Comment by AlfredSK** [comment]
Ok, ok. I'll change it. :)

**Comment by AlfredSK** [comment]
I think this is outdated since it has been changed with the profile restructuring. Can we close it?

**Comment by MrPetovan** [comment]
Closed by #8261
