### ISSUE TITLE
API: Respect globalcommunitysilence

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6672]
### Expected behavior
If the admin has silenced an account on the community pages the items of that account shouldn't be visible when looking at the community streams via API.

### Actual behavior
If the admin silenced an account via `bin/console globalcommunitysilence ...` the items of that account still appear on the community streams when using an app (API).

### Steps to reproduce the problem
Silence an account by running `bin/console globalcommunitysilence https://example.com/profile/nick`. Check if the account has been silenced successfully by looking at the community streams with a browser. Then check the community streams with an app.

### Friendica version you encountered the problem
2019.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
Fixed in #6765

**Comment by AlfredSK** [comment]
I'll check the fix now. And I'll close the issue if it works.

**Comment by MrPetovan** [comment]
Yes, please.

**Comment by nupplaphil** [comment]
@AlfredSK I fixed it for `api/statuses/public_timeline` calls.

**Comment by AlfredSK** [comment]
Looks like it's working. I don't see my local heroes anymore when I check the local community stream with Fedilab or the global community stream with Twidere.
Thank you very much!
