### ISSUE TITLE
Forumdirectory in frio theme looks bad

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#6674]
### Expected behavior
After enabling the addon the /forumdirectory should look similar to /directory in the frio theme.
### Actual behavior
Strange ugly box around it that doesn't fit at all to the rest of the page.
### Steps to reproduce the problem
Enable frio theme & forumdirectory addon
### Friendica version you encountered the problem
2019.01
see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
Git
### PHP version
7.3
### SQL version
5.6

**Comment by poVoq** [comment]
Besides the bug report, would be actually really nice if the forum listing would be improved in general and allow a thread view with collapsed comments. I.e. a bit similar to how for example a phpbb board looks like.

**Comment by MrPetovan** [comment]
Thanks for your report!

**Comment by poVoq** [comment]
@rabuzarus
After upgrading I only get a forbidden HTML error message on the /forumdirectory link now.

**Comment by MrPetovan** [comment]
Did you upgrade both Friendica and the addons on the same branch (both `develop`)?

**Comment by poVoq** [comment]
No, both 2019.03-RC

**Comment by MrPetovan** [comment]
Ah, you're right, both relevant PRs against `develop` date back before the RC phase, so the `2019.03-RC` branches should work as expected.

**Comment by MrPetovan** [comment]
Can anyone else confirm the forbidden message?

**Comment by MrPetovan** [comment]
I just tried `/irc` after having enabled the `IRC Chat Room` addon and it worked as expected.

**Comment by poVoq** [comment]
Sorry my bad. Thanks for the help!
