### ISSUE TITLE
Import of threads not honouring the settings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6675]
### Expected behavior

If the option "Only import OStatus/​ActivityPub threads from our con­tacts" is activated by the admin of a node, only the conversations the contacts of the users have started should be imported and completed.

### Actual behavior

Conversations from aliens are imported and succesively completed the contacts take part in. This happens with any activity (e.g. comments of likes)- For both Mastodon (AP and OStatus) and GNU social / postActiv aliens / contacts.

### Steps to reproduce the problem

Activate the option and wait for new conversations being pulled in.

### Friendica version you encountered the problem

2019.03-dev

### PHP version

7.2

**Comment by tobiasd** [comment]
Currently I have the impression, that it is mostly the OStatus import of threads which is ignoring the settings. Though not all GS contacts threads are imported.

**Comment by annando** [comment]
I currently don't have a clue about this. I'm currently thinking about changing this whole thing in a way that it would be some user setting directly in the item class - but not for this version.

**Comment by tobiasd** [comment]
An observation over the last days: Mastodon (top-level) postings are imported as well. But it might still be that the contact causing the wrong thread completion by an interaction (like or comments) is always a GS contact.

**Comment by hoergen** [comment]
I noticed that this bug is still happening with OStatus from GNUSocial. I get every thread my contacts are commenting :(

**Comment by tobiasd** [comment]
Today I witnessed a Friendica (AP) contacts comment pulling in a thread by a Mastodon (AP) stranger.

**Comment by tobiasd** [comment]
I'm still getting postings from Mastodon and GNU social people in my stream that I do not follow when contacts of mine interact with the thread.

**Comment by AlfredSK** [comment]
I can confirm that I see threads where I don't follow the top-level post author but I do follow a user who commented on the post. In my case theses threads are all coming from Pleroma.

@tobiasd Do you have enabled the new option in your user settings? I'm asking because it is disabled by default.

**Comment by AlfredSK** [comment]
OK. Something is weird with that Pleroma contact I follow. 'tsumiki' (ivesen) is showing as 'network type pleroma' but when I filter my contacts via the protocol widget the contact is listed in the category 'OStatus'.

**Comment by tobiasd** [comment]
> @tobiasd Do you have enabled the new option in your user settings?
> I'm asking because it is disabled by default.

Yes, that's why I re-opened the issue because the new option did not fix the problem.

I'm still getting threads from aliens using Mastodon, Pleroma or GNU social into my timeline. The contacts that interacted with the thread are also on any of those three.

**Comment by annando** [comment]
The change is coded in the AP part, not on the OStatus part. I'm currently if this can be done easily there as well.

**Comment by AlfredSK** [comment]
Just an addition to my comments above:

Something is fishy with that Pleroma connection:
```
index [WARNING]: error: https://https//miniwa.moe/users/ivesen/.well-known/host-meta: 0 - Could not resolve host
```
See the double 'https' in the URL.

Also, I got a message from `ivesen@miniwa.moe` that I was constantly refollowing their account - like a dozen times in the last couple of days. But I only did it one time manually.

**Comment by AlfredSK** [comment]
I think we have more issues with Pleroma contacts. I just got a friend request from someone I do already have a bidirectional contact relationship with - or I thought so... After accepting it I have two bidirectional relationships with the same Pleroma (AP) contact now.

Maybe it's better to open a new issue for that.

![Screenshot_20190721-201618(1)](https://user-images.githubusercontent.com/3656054/61595307-ca3f6400-abf5-11e9-8b97-fd80a4d2dba1.png)

**Comment by annando** [comment]
Yeah, please open a new issue. This is unrelated.

**Comment by tobiasd** [comment]
Seems to work now.

But the confusing thing is how some reshared items are displayed, not with the "via" descriptor. The way they are displayed now screems SPAM invasion. But I guess that is a different issue.
