### ISSUE TITLE
Frio theme customization as admin are overridden by individual settings

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#6677]
### Expected behavior
Having custom options to select when indicating the "custom" color scheme in the admin menu even if selected "blue" in the individual settings display menu.

### Actual behavior
When entering the admin menu the "custom option can be selected but no actual customization options appear unless also changing the individual settings to "custom".

### Steps to reproduce the problem
Enable frio as admin account, set color theme to "blue" in individual display settings, go to admin menu and try to customize theme for other users.

### Friendica version you encountered the problem
2019.01

### Friendica source (git, zip)
git
### PHP version
7.3
### SQL version
5.6

**Comment by poVoq** [comment]
No, that is definitly a bug, or at least a very unexpected behaviour :p

**Comment by MrPetovan** [comment]
So, you're saying that since, as an admin, your personal account's theme selection is a pre-defined scheme, you can't customize the site's theme colors?

The "Support Request" label is used for most issues that aren't trivial to reproduce until they can actually be reproduced. If what you describe happens on other nodes, then it will be expectedly requalified as a bug.

**Comment by poVoq** [comment]
![themecustombug](https://user-images.githubusercontent.com/940360/52915740-cc795b80-3301-11e9-9961-1b4d66a3be63.jpg)
This happens when I have "blue" selected in my personal settings and "custom" in the admin settings.

**Comment by poVoq** [comment]
Also, if I switch back to "custom" in the personal settings, my previous settings are lost. At the very least it should return to the site default custom settings as by the admin menu...

**Comment by MrPetovan** [comment]
Thanks for the additional information. To be frank I don't even know if we are using this screen at all. The only place I know where you can set the site's theme scheme is in Admin -> Site -> General Information -> System Theme -> "change theme settings" link.

Can you please check if you can set up custom colors over there?

**Comment by poVoq** [comment]
Exactly the same issue on that popup view.

**Comment by MrPetovan** [comment]
Ok, thank you for the report and bearing with me.

**Comment by poVoq** [comment]
Hmm... can it be that the Admin settings in general are not being applied? I created a few forum accounts on my test page and they all switched back to the default greenish/blue color of the Frio theme.

**Comment by MrPetovan** [comment]
Unfortunately, it is possible too. But the particular issue that you described in your original post seems to stem from the fact that user settings are wrongly used to inform admin settings display.

This other potential issue would have a different origin.

**Comment by AlfredSK** [comment]
> I created a few forum accounts on my test page and they all switched back to the default greenish/blue color of the Frio theme.

The setting in admin panel is only used as system theme and color set. For example when you look at pages while you're not logged in. It isn't used for new user accounts, unfortunately. New user accounts always use the hard coded default colors. But it would be great if the system colors would be used instead.

**Comment by AlfredSK** [comment]
Here is the issue for using the site color settings for new accounts after registration.
https://github.com/friendica/friendica/issues/4854

**Comment by MrPetovan** [comment]
Closed via #6747
