### ISSUE TITLE
Database is polluted by a process writing nonsene

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6679]
Till today I used the addon "Start Page" where you can define the timeline and group you want to start after login. Yesterday I noticed, while helping another user, that the theme ier is not usable, with my defined start page "network/60".
The 60 is the definition of the selected group from frio. But that doesn't work on vier. So I deleted the entry in the addon, but didn't deactivate it.

Today I noticed, that my avatar vanished and at the same time @tobiasd noticed, that mentioning me has an issue https://github.com/friendica/friendica/issues/6552#issuecomment-464424259 

I started correcting the wrong entries in a lot of different fields of the contact table . I wrote that in my post https://horche.demkontinuum.de/display/2196d4ee-155c-694d-cac0-b13872080230

> Found 34 entries in table contacts where seeral fields, like nick, avatar, url, nurl, addr, photo, thumb, micro, request, notify, poll, confirm, poco are changed.
> 
> example
> avatar field has: horche.demkontinuum.de/index.p… [url=https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi]https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi[/url]
> 
> addr: hoergen@horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi
> 
> nick: [url=https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi]horche.demkontinuum.de/index.p…[/url]

The bb-code is made automatically ye the new friendica commentbox JS .. but that is another problem.

Meanwhile there are a lot more lines in the database with bullshit code like `network/60` and `.well-known ` stuff. 

I deactivated the addon completly and deactivated the cron job so that (hopefully no other process is continuing destroying the database). I have backups, but I wont restore them until I don't know the origin of this disaster. So  my server is now on standby.

Do you have any clue, what I can do?

### Steps to reproduce the problem
It is doing that automatically

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2019.03-dev - 1302  / php7.2 / Mariadb

**Comment by MrPetovan** [comment]
This seems to be an intricate problem between your webserver rewrite engine (because of the `index.php` that should never be shown anywhere) and an unfortunate redirection loop during a probe, compounded by the addon redirection itself.

To unpack:
- The cronjob probes contact URL to update information
- The probe follows any redirection for up to 5-10? cyclical redirections to `network/60` that each add a piece of garbage at the end of the URL.
- The job updated the contact URL with the new URL.
- The cronjob probes the new contact URL for any other reason (`.well-known/host-meta`) for example
- The probe follows any additional redirections and concatenate the result once more.
- The URL gets saved once again.
- etc...

The underlying problem seems to be that the initial call to `/` redirects to `/index.php/network` which gets incorrectly treated as a `/home` module call, which calls the `startpage` hook, which redirects to `/index.php/network/network/60`, which gets incorrectly treated as a `/home` module call again.

Which means that at some point your system base URL gets computed to at least `https://horche.demkontinuum.de/index.php` which should never happen.

Can you please got to `https://horche.demkontinuum.de/phpinfo` and copy the `Apache Environment` values? I'm interested in `REDIRECT_URL`, `REDIRECT_URI`, `REDIRECT_SCRIPT_URL`, `SCRIPT_URL`, and `REQUEST_URI`.

**Comment by hoergen** [comment]
Variable | Value
-- | --
REDIRECT_REMOTE_USER | no value
REDIRECT_HTTPS | on
REDIRECT_SSL_TLS_SNI | horche.demkontinuum.de
REDIRECT_STATUS | 200
HTTPS | on
SSL_TLS_SNI | horche.demkontinuum.de
HTTP_HOST | horche.demkontinuum.de
HTTP_USER_AGENT | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
HTTP_ACCEPT | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE | de,en-US;q=0.7,en;q=0.3
HTTP_ACCEPT_ENCODING | gzip, deflate, br
HTTP_DNT | 1
HTTP_CONNECTION | keep-alive
HTTP_COOKIE | PHPSESSID=4en7kd8tsjetuhfvee9dril21f
HTTP_UPGRADE_INSECURE_REQUESTS | 1
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_SIGNATURE | <address>Apache/2.4.25 (Debian) Server at horche.demkontinuum.de Port 443</address>
SERVER_SOFTWARE | Apache/2.4.25 (Debian)
SERVER_NAME | horche.demkontinuum.de
SERVER_ADDR | 37.221.193.213
SERVER_PORT | 443
REMOTE_ADDR | 91.64.43.206
DOCUMENT_ROOT | /.....htdocs/
REQUEST_SCHEME | https
CONTEXT_PREFIX | no value
CONTEXT_DOCUMENT_ROOT | /.../htdocs/
SERVER_ADMIN | dingdong@donkykongkongkong
SCRIPT_FILENAME | /..../htdocs/index.php
REMOTE_PORT | 44078
REDIRECT_URL | /phpinfo
REDIRECT_QUERY_STRING | pagename=phpinfo
GATEWAY_INTERFACE | CGI/1.1
SERVER_PROTOCOL | HTTP/1.1
REQUEST_METHOD | GET
QUERY_STRING | pagename=phpinfo
REQUEST_URI | /phpinfo
SCRIPT_NAME | /index.php

**Comment by MrPetovan** [comment]
Nothing looks wrong, which was kind of expected, otherwise you couldn't have accessed to this very page. I suggest you clean your database up, and then manually run the worker once and look for this `index.php` in local contact fields.

**Comment by hoergen** [comment]
Hmm thanks for checking. But I can't clean the database, because there are  too many entries for all kinds of contacts with wrong photo, thumb, micro, avatar. 
I cleaned up my account, but it keeps polluting it again, as son I start the workers. I already tried it.

**Comment by MrPetovan** [comment]
Clean records starts being polluted again?

**Comment by hoergen** [comment]
It seems like. I cleaned it up tree times and after a while I found again polluted lines with my account name.

**Comment by MrPetovan** [comment]
Ugh, that sucks, it's even worse than I imagined. There's something wrong with how your webserver handles curl requests in general then. Is `network/60` still appearing in the garbage after you deactivated the startpage addon and cleaned the records?

**Comment by hoergen** [comment]
Yes. I  checked the log file and I have lots of erros like this

`2019-02-17 06:02:18 worker [WARNING]: error: https://www.fessebouc.fr/.well-known/webfinger.xml?resource=garibaldo_pingouin%40www.fessebouc.fr: 404 -  [] {"file":"CurlResult.php","line":144,"function":"checkSuccess","uid":"38a2356","process_id":12164}`

or

`2019-02-18 01:04:22 worker [WARNING]: error: https://redsocial.dynv6.net/users/vi/inbox: 500 -  [] {"file":"CurlResult.php","line":144,"function":"checkSuccess","uid":"d3cdf97","process_id":3580}`

**Comment by MrPetovan** [comment]
What about the specific string `network/60`?

**Comment by hoergen** [comment]
There is no "mention" about `network/60` in the logfile

found another, maybe, interesting  lines.

```
2019-02-18 05:24:02 index [WARNING]: error: https://diaspora.u4u.org/statistics.json: 406 -  [] {"file":"CurlResult.php","line":144,"function":"checkSuccess","uid":"d857762","process_id":10346}
2019-02-18 05:24:31 index [WARNING]: API call - not implemented {"module":"api","action":"call"} {"file":"api.php","line":426,"function":"api_call","uid":"59bac91","process_id":10340}
2019-02-18 05:24:45 index [WARNING]: error: https://pluspora.com/.well-known/webfinger.xml?resource=https%3A%2F%2Fpluspora.com%2Fu%2Fsiqua: 404 -  [] {"file":"CurlResult.php","line":144,"function":"checkSuccess","uid":"7732e4d","process_id":10357}
```

**Comment by annando** [comment]
@hoergen those messages are not errors. When probing contacts, we generate a lot of noise since there are several ways how the other system could react.

**Comment by hoergen** [comment]
I deactivated php logging in .htaccess and activated the workers again .. let's see what is happening.

**Comment by hoergen** [comment]
ok stoped it again after a minute arround 50 lines of contact table are changed in several fields with network/60 bullshit.

**Comment by annando** [comment]
Can you have a look into the config/pconfig table if you find any of these "network/60" content in it?

**Comment by hoergen** [comment]
in config I can find it from time to time, like i wrote in https://forum.friendi.ca/display/39bbe52a-115c-6ab3-53c9-702357513137 / h2157518.stratoserver.net/nc/index.php/s/z98Kw7RGMNykLAx

but pconfig seems to be clean (im still hitting the button)

**Comment by hoergen** [comment]
exported with
`mysqldump -u FRIENDICA -p FRIENDICA --ignore-table=FRIENDICA .item --ignore-table=FRIENDICA .item-activity --ignore-table=FRIENDICA .item-content --ignore-table=FRIENDICA .item-delivery-data --ignore-table=FRIENDICA .item-uri --ignore-table=FRIENDICA .parsed_url --ignore-table=FRIENDICA .photo   --ignore-table=FRIENDICA .queue  --ignore-table=FRIENDICA .conversation --result-file=dbdata.sql`

I searched with `less `and and search string `network\/60`  I find for example

`INSERT INTO `cache` VALUES ('APDelivery:createActivity:2055392','a:10:{s:8:\"@context\";a:3:{i:0;s:37:\"https://www.w3.org/ns/activitystreams\";i:1;s:28:\"https://w3id.org/security/v1\";i:2;a:6:{s:5:\"vcard\";s:32:\"http://www.w3.org/2006/vcard/ns#\";s:4:\"dfrn\";s:35:\"http://purl.org/macgirvin/dfrn/1.0/\";s:8:\"diaspora\";s:34:\"https://diasporafoundation.org/ns/\";s:25:\"manuallyApprovesFollowers\";s:28:\"as:manuallyApprovesFollowers\";s:9:\"sensitive\";s:12:\"as:sensitive\";s:7:\"Hashtag\";s:10:\"as:Hashtag\";}}s:2:\"id\";s:82:\"https://horche.demkontinuum.de/objects/2196d4ee-135b-ed19-64c4-a42050399402#Delete\";s:4:\"type\";s:6:\"Delete\";s:5:\"actor\";s:47:\"https://horche.demkontinuum.de//profile/hoergen\";s:9:\"published\";s:20:\"2018-11-15T06:59:48Z\";s:10:\"instrument\";a:2:{s:4:\"type\";s:7:\"Service\";s:4:\"name\";s:82:\"Friendica \'The Tazmans Flax-lily\' 2019.03-dev-1302; https://horche.demkontinuum.de\";}s:2:\"to\";a:1:{i:0;s:44:\"https://www.w3.org/ns/activitystreams#Public\";}s:2:\"cc\";a:0:{}s:6:\"object\";a:2:{s:2:\"id\";s:75:\"https://horche.demkontinuum.de/objects/2196d4ee-135b-ed19-64c4-a42050399402\";s:4:\"type\";s:9:\"Tombstone\";}s:9:\"signature\";a:5:{s:4:\"type\";s:16:\"RsaSignature2017\";s:5:\"nonce\";s:64:\"3d4528b78bb556b438f43b6ba2ca9b1eef203ff9333e68770dbc5745b39d7c84\";s:7:\"creator\";s:264:\"https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi#main-key\";s:7:\"created\";s:20:\"2019-02-18T07:45:32Z\";s:14:\"signatureValue\";s:684:\"lCnMOHDmooWCd1butXa+sWtw0bkILh885kPrrfQW7hCy6V7elxtoqk/GovvslrAnrkkdDX6OanPI9e3D8iGwK8KspD49L+krMVXp51Q2defA+SXWInd8b93LuwrCH7O7ACvt4jKiKhBmpsT5n6GRmNdYQw/v7ldqCxJXS0I7zmIwqSiplfu+Qbbk1xo06yYN+uc2B4fTSasuLoXKgemFKeiOvEdeN0Zp95dkQZ+v/nlHwjBE/wiOSu2hmOqn1kW5hCUgaUrpYdtY9Asduxv3Q6Ae5cKQdsOwPjaIrxUJb7xNPX1O1Te4elbpaenzCFjEZT+WW8VSFLrqVjPXQv1Bd5kHmQ0e0yKW3aDKE4dQo85EwQt184hzN7lWLpw42xeFOm12bsrNASdWZiBdmxPQTt/TcY5Ck6wytJpflzXsxsHH4uFytIMqFTSBDmyUiAGo2qRbpy3S4iu3KSjoOPFpQN31auNlb9ZMnpPyhRmNhVXb3ftJehH761OWPD/Gt87jgKWhTrxeVdIaROAIznIW9gN8PRNUtBKloYvS8aUp2ky3xbdKDEiRBpN2a8tuktLo/f4Yus8XOCptuK2uerLrKF5JvxcwwHOvnWp379pqnY/Yk9MjRJJQqWFOY2Ne0SNEAS5o1pUyMFdfKf97ljyJwU9L7QQ2f0oKMFM4tVSDVHU=\";}}',0,'2019-02-18 07:45:32','2019-02-18 08:00:32'),('APDelivery:createActivity:2055402','a:10:{s:8:\"@context\";a:3:{i:0;s:37:\"https://www.w3.org/ns/activitystreams\";i:1;s:28:\"https://w3id.org/security/v1\";i:2;a:6:{s:5:\"vcard\";s:32:\"http://www.w3.org/2006/vcard/ns#\`

and I find with that search string as well something like this **<U+200D>**
`'alsternerd 🤷🏼<U+200D>♀️','alsternerd','','IT-Helpdesk, everything IT`

and this .. same hit **<U+200D>**

`/uploads/images/thumb_large_035fdfab0be9ff7e851c.jpg','',-1,0),(51607,0,'2018-10-16 06:37:19',0,0,2,0,'apub','Sebastian','hinterwaeldler','','Bookworm 📚 Pumper 🏋️<U+200D>♂️ Scientist 👨<U+200D>🔬 Cyclist 🚴<U+200D>♂️ German 🇩🇪',NULL,'','','https://horche.demkontinuum.de/photo/19296364025bc5871f93f08476425253-4.png?ts=1547794353','https://horche.demkontinuum.de/photo/19296364025bc5871f93f08476425253-5.png?ts=1547794353','https://horche.demkontinuum.de/photo/19296364025bc5871f93f08476425253-6.png?ts=1547794353',NULL,'','','https://mastodon.social/users/hinterwaeldler','http://ma    stodon.social/users/hinterwaeldler','hinterwaeldler@mastodon.social','https://mastodon.social/@hinterwaeldler','-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt4gvkYmHjYGVqCBPulRS\nYHsaz3alyQWrZnXqpq7gK5vcAYxgwiUtIAXGt0qmm5fEACJm4j8HBgA3KbPxcN55\nAYj/dbTYwwkxWAHJ4kvem7vpixCmF/NnYimQKF5ezJ+yxNfCrQfHaVHqsND4foQy\nQcAttLzb0bOe1GpaHtMQD84FaJptvCs0YHuWiqF86xIwgwP33wh5i7XyaAs1oz2N\nR1kyhulQZfkvTYwpThHNZUNTOD1+6bhFPmuSfBk2D4eN4btJR0s++az3supL1gXq\n6JZXvUsDej4IQxAPnSEvxqaDq8lOs/6CKP0rVvZjbxl2uTu6T50UX4Wya91TUBhc\ndwIDAQAB\n-----END PUBLIC KEY-----',NULL,'https://mastodon.social/inbox',NULL,'https://mastodon.social/users/hinterwaeldler/inbox','https://mastodon.social/users/hinterwaeldler/outbox',NULL,NULL,0,0,0,0,'','0001-01-01 00:00:00','2018-10-16 06:37:23','0001-01-01 00:00:00','2018-10-16 06:37:19','2018-10-16 06:37:20','2019-01-18 06:52:33','0001-01-01 00:00:00','2018-10-16 06:37:23',0,0,0,1,0,0,0,0,0,0,NULL,99,NULL,0,'','0001-01-01',0,0,NULL,'https://files.mastodon.social/accounts/avatars/000/301/786/original/TGY2W9Y2HT3S.png','',0,0),(51608,0,'2018-10-16 06:37:20',0,0,2,0,'apub','Sebastian','hinterwaeldler','','Bookworm 📚 Pumper 🏋️<U+200D>♂️ Scientist 👨<U+200D>🔬 Cyclist 🚴<U+200D>♂️ German 🇩🇪',NULL,'','','https://horche.demkontinuum.de/photo/15602397685bc5872041318188212061-4.png?ts=1547794353','https://horche.demkontinuum.de/photo/15602397685bc5872041318188212061-5.png?ts=1547794353','https://horche.demkontinuum.de/photo/15602397685bc5872041318188212061-6.png?ts=1547794353',NULL,'','','https://mastodon.social/users/hinterwaeldler','http://mastodon.social/users/hinterwaeldler','hinterwaeldler@mastodon.social','https://mastodon.social/@hinterwaeldler','-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkgwP33wh5i7XyaAs1oz2N\nR1kyhulQZfkvTYwpThHNZUNTOD1+6bhFPmuSfBk2D4eN4btJR0s++az3supL1gXq\n6JZXvUsDej4IQxAPnSEvxqaDq8lOs/6CKP0rVvZjbxl2uTu6T50UX4Wya91TUBhc\ndwIDAQAB\n-----ENDHPUBLICoKEY-----',NULL,'https://mastodon.social/inbox',NULL,'https://mastodon.social/users/hinterwaeldler/inbox','https://mastodon.social/users/hinterwaeldler/outbox',NULL,NULL,0,0,0,0,'','0001-01-01 00:00:00','2018-10-16 06:37:23','0001-01-01 00:00:00','2018-10-16 06:37:20','2018-10-16 06:37:20','2019-01-18 06:52:33','0001-01-01 00:00:00','2018-10-16 06:37:23',0,0,0,1,0,0,0,0,0,0,NULL,99,NULL,0,'','0001-01-01',0,0,NULL,'https://files.mastodon.social/accounts/avatars/000/301/786/original/TGY2W9Y2HT3S.png','',0,0),(51609,0,'2018-10-16 06:37:20',0,0,2,0,'apub','Sebastian','hinterwaeldler','','Bookworm 📚 Pumper 🏋️<U+200D>♂️ Scientist 👨<U+200D>🔬 Cyclist 🚴<U+200D>♂️ German 🇩🇪',NULL,'','','https://horche.demkontinuum.de/photo/45844053155bc587206db5f907335451-4.png?ts=1547794353'    ,'https://horche.demkontinuum.de/photo/45844053155bc587206db5f907335451-5.png?ts=1547794353','https://horche.demkontinuum.de/photo/45844053155bc587206db5f907335451-6.png?ts=1547794353',NULL,'','','https://mastodon.social/users/hinterwaeldler','http://mastodon.social/users/hinterwaeldler','hinterwaeldler@mastodon.social','https://mastodon.social/@hinterwaeldler','-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt4gvkYmHjYGVqCBPulRS\nYHsaz3alyQWrZnXqpq7gK5vcAYxgwiUtIAXGt0qmm5fEACJm4j8HBgA3KbPxcN55\nAYj/dbTYwwkxWAHJ4kvem7vpixCmF/NnYimQKF5ezJ+yxNfCrQfHaVHqsND4foQy\nQcAttLzb0bOe1GpaHtMQD84FaJptvCs0YHuWiqF86xIwgwP33wh5i7XyaAs1oz2N\nR1kyhulQZfkvTYwpThHNZUNTOD1+6bhFPmuSfBk2D4eN4btJR0s++az3supL1gXq\n6JZXvUsDej4IQxAPnSEvxqaDq8lOs/6CKP0rVvZjbxl2uTu6T50UX4Wya91TUBhc\ndwIDAQAB\n-----END PUBLIC KEY-----',NULL,'https://mastodon.social/inbox',NULL,'https://mastodon.social/users/hinterwaeldler/inbox','https://mastodon.social/users/hinterwaeldler/outbox',NULL,NULL,0,0,0,0,'','0001-01-01 00:00:00','2018-10-16 06:37:20','0001-01-01 00:00:00','2018-10-16 06:37:20','2018-10-16 06:37:20','2019-01-18 06:52:33','0001-01-01 00:00:00','2018-10-16 06:37:20',0,0,0,1,0,0,0,0,0,0,NULL,99,NULL,0,'','0001-01-01',0,0,NULL,'https://files.mastodon.social/accounts/avatars/000/301/786/original/TGY2W9Y2HT3S.png','',0,0),(51610,0,'2018-10-16 06:37:22',0,0,2,0,'apub','Sebastian','hinterwaeldler','','Bookworm 📚 Pumper 🏋️<U+200D>♂️ Scientist 👨<U+200D>🔬 Cyclist 🚴<U+200D>♂️ German 🇩🇪',NULL,'','','h`

**Comment by hoergen** [comment]
Should all tables be `utf8mb4_general_ci` ? Because some are not

**Comment by hoergen** [comment]
Switched on Workers again and let's see what is happening

**Comment by hoergen** [comment]
There is a job: 
`CronJobs: repair_database`

**Comment by hoergen** [comment]
Still randomly exchanging photo, url, micro, addr and so back and forth.

I activated "Start Page" addon again and entered "network" in it. As far as I know that was the default. Maybe it "repairs" itself again.

**Comment by hoergen** [comment]
Activated query-log and found for example something like that

`Execute   /*DBA::update, JITConfigAdapter::set, Configuration::set, Config::set */ UPDATE `config` SET `v` = 'https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi' WHERE (`cat` = 'system' AND `k` = 'url')`

**Comment by hoergen** [comment]
`1376 Execute   /*DBA::update, DatabaseSessionHandler::write, session_write_close */ UPDATE `session` SET `data` = 'return_path|s:21:\"network?f=&order=post\";remember|b:0;last_login_date|s:19:\"2019-02-18 23:31:30\";uid|i:1;theme|s:4:\"vier\";mobile-theme|s:3:\"---\";authenticated|i:1;page_flags|i:0;my_url|s:431:\"https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/profile/hoergen\";my_address|s:415:\"hoergen@horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network\";addr|s:12:\"91.64.43.206\";new_member|b:0;cid|i:1;language|s:2:\"de\";sysmsg_info|a:0:{}last_updated|a:1:{s:12:\"profile:1:1:\";i:1550537072;}network_last_top_limit|s:19:\"2019-02-19 00:38:35\";network_last_date|s:19:\"2019-02-19 00:38:35\";network_last_date_timestamp|i:1550537138;sysmsg|a:0:{}', `expire` = 1550717143 WHERE (`sid` = '4en7kd8tsjetuhfvee9dril21f' AND (`data` != 'return_path|s:21:\"network?f=&order=post\";remember|b:0;last_login_date|s:19:\"2019-02-18 23:31:30\";uid|i:1;theme|s:4:\"vier\";mobile-theme|s:3:\"---\";authenticated|i:1;page_flags|i:0;my_url|s:431:\"https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/profile/hoergen\";my_address|s:415:\"hoergen@horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network\";addr|s:12:\"91.64.43.206\";new_member|b:0;cid|i:1;language|s:2:\"de\";sysmsg_info|a:0:{}last_updated|a:1:{s:12:\"profile:1:1:\";i:1550537072;}network_last_top_limit|s:19:\"2019-02-19 00:38:35\";network_last_date|s:19:\"2019-02-19 00:38:35\";network_last_date_timestamp|i:1550537138;sysmsg|a:0:{}' OR `expire` != 1550717143)) `

**Comment by hoergen** [comment]
I have the impression all this `network/60` comes from the session data/table ...even I activated the addon put network in it ... after that I changed the theme to vier, clicked around and changed it back to frio .... then i changed back to vier, emptied the field in start page addon, saved it. Clicked in vier arround and changed back to frio.

I did all that because I noticed the problem start first, when i changed the themes.
At the moment there seems to be a replacing field  war in my database.

Let's see tomorrow, if something changed.

**Comment by hoergen** [comment]
when you enter `https://horche.demkontinuum.de/index.php` you get `https://horche.demkontinuum.de/index.php/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network/network`

the `60` disapeared at the Moment.

**Comment by annando** [comment]
For me it seems as if the function ```determineURLPath``` https://github.com/friendica/friendica/blob/develop/src/App.php#L398 is the problem. 

The function ```checkURL``` https://github.com/friendica/friendica/blob/develop/src/App.php#L1062 is rewriting the config setting that @hoergen described above. And this is using ```getBaseURL``` which is then using the parts that the first mentioned function is generating.

**Comment by hoergen** [comment]
Now I have on my pinwall a post that I shared 

this morning but it looks like another user of my server wrote it. :(
https://horche.demkontinuum.de/display/2196d4ee-195c-6bb2-ff5e-2e2355054940

**Comment by hoergen** [comment]
Deleted that post

**Comment by hoergen** [comment]
I think if I could stop all processes to change the "v" value this could be a workaround

![00_temp](https://user-images.githubusercontent.com/24474762/53008655-27ae6980-343a-11e9-913d-d95a82b6ed71.jpg)

**Comment by hoergen** [comment]
the v value is fully:

`https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi`

**Comment by MrPetovan** [comment]
Maybe try to empty the session table? The presence of `index.php` in all these URLs still bugs me.

**Comment by hoergen** [comment]
> 
> 
> Maybe try to empty the session table? The presence of `index.php` in all these URLs still bugs me.

I did that already several times ;)

**Comment by MrPetovan** [comment]
Also what are these config rows with hexadecimal category and key?

**Comment by hoergen** [comment]
I have no clue where they come from. I tried to search them, but didn't found something

**Comment by MrPetovan** [comment]
@annando may be onto something, please comment out this line: https://github.com/friendica/friendica/blob/1df19d3553efc02c76ed17cdc617312f19b21bce/src/App.php#L1073

**Comment by annando** [comment]
We have to fix ```getBaseURL```. Commenting out that line won't help at all places.

**Comment by MrPetovan** [comment]
Yes, but until then this would prevent database pollution and may actually revert some of the damage since the base URL would be stable again.

**Comment by hoergen** [comment]
Now Friendica is starting autmatically exchanging my different accounts. In this case I answered as hoergen, but friendica put my runner (forum) account in there. I am logged in as hoergen not as "runner" and I didn't change my idendity via manage

![00_temp](https://user-images.githubusercontent.com/24474762/53077641-be3e6180-34f2-11e9-8143-f46a3c8b4a1b.jpg)
https://horche.demkontinuum.de/display/2196d4ee-495c-6d10-9182-1c9876120598

**Comment by hoergen** [comment]
Messages that I wrote in my servers forums are away now. Only some RSS feeds are left. :(

For example
https://horche.demkontinuum.de/profile/klangwerk
https://horche.demkontinuum.de/profile/runner
https://horche.demkontinuum.de/profile/filmzeit

Maybe my server starts "deleting" (with replacing field content) forums ?

**Comment by annando** [comment]
I am totally clueless what happens there. I hope that this evening I can have a look at it - but this is really strange and I don't really know where to look at.

**Comment by hoergen** [comment]
Tell me if you want to have access to the server to see yourself what is happening. xmpp is not working, but riot.

**Comment by annando** [comment]
I guess it would be best. Could you send me your Matrix handle via SMS/Signal/Telegramm/...?

**Comment by hoergen** [comment]
I still have your matrix account and sent you a notification.

**Comment by annando** [comment]
Okay. So I guess that other PR and my server move will have to wait ...

**Comment by MrPetovan** [comment]
Wow that's a pickle. ☹

**Comment by hoergen** [comment]
I have the impression, that maybe a reason could be the composer.lock problem. After I pulled today git, I got again composer warning messages and in friendica I saw again  the bullshit code. But then I removed the `composer.lock` pulled it again, without doing `composer install` or something.
And at the moment everything is looking calm and normal.

**Comment by annando** [comment]
Had the database bug returned?

**Comment by hoergen** [comment]
It seems solved. I updated again, there was a composer error with an abandoned package, but everything seems good. Should we close this issue for now?

**Comment by MrPetovan** [comment]
Yes, I'll open a specific issue to handle the issue properly.
