### ISSUE TITLE
German i18n: "du", "Du" or "Sie"?

### ISSUE THREAD

**Issue by rompe** [friendica/friendica#6684]
I have tried to contact developers [by posting to the developer forum](https://firstpost.de/display/ddbc8765-145c-6707-1b6c-dda546032083) but it seems nobody but me got that posting, so I'm asking here.

I fixed a bunch of typos and vaguenesses over at [Transifex](https://www.transifex.com/Friendica/friendica/language/de/) and would now like to address users in the same way everywhere. Right now there is a mixture of _"du"_, _"Du"_ and _"Sie"_. Which one would you prefer to see in every part of the software?

**Comment by annando** [comment]
I guess the "du" is the best way. "Sie" is much too formal - and "Du" is only used partially in letters/mails.

**Comment by AndyHee** [comment]
Overall, there should be consistency. The style of address and use of personal pronouns should not vary within a specific localization.

If there is demand for a more formal version of a language, a new localization should be created. E.g. "German-Sie".

If you need assistance on how to easily create a new localization on the basis of a set of existing translation files, please let me know. I can prepare the necessary files. I have already done this for American English that was done on the basis of the British English files.

**Comment by tobiasd** [comment]
Are you in contact with the forum?

I agree with @annando that we should use the informal tone of "du" and "dir" oder the formal "Sie".

Thanks for helping with the translations and clearing up of the mess of 20 translators cooking the soup together!

**Comment by rompe** [comment]
@AndyHee At the moment I'm just trying to reduce the variants to exactly one. If someone demands a formal "Sie" locale I would volunteer to create it, but I'm fine with a consistent "du".

@tobiasd As stated above I tried to contact the forum, but I seem to have failed since I don't think anybody else received the linked message and I don't receive any other message from the forum. I still need to dig deeper into Friendica in order to investigate that.

So, as @annando voted for "du" and that would have been my favorite, too (I regularly use "Du", but I'm old-fashioned and well aware of that), I will convert everything to "du", and as soon as anybody asks for "Sie", you may contact me and I will introduce a new locale for that. OK?

**Comment by tobiasd** [comment]
Yes, just do it :-)

**Comment by rompe** [comment]
Done, but I couldn't edit these two as they are "reviewed translations" and as such aren't editable for mere mortals:

```
"%s teilt mit Dir"
"Sie müssen angemeldet sein um Addons benutzen zu können."
```

Maybe somebody with permissions might want to change them into these:

```
"%s teilt mit dir"
"Du musst angemeldet sein, um Addons benutzen zu können."
```

This issue can be closed afterwards. Thanks all!

**Comment by tobiasd** [comment]
You should be able to review them now. We don't really use the "review" mode, but at one point some strings got reviewed by someone and since then I forget on a regular basis to promote the translators to reviewers.

**Comment by rompe** [comment]
Done. Thanks again!
