### ISSUE TITLE
URL rewrite not working,  install/testrewrite not found²

### ISSUE THREAD

**Issue by feydreva** [friendica/friendica#6699]
### Expected behavior
when going to http://tribe.randome.camp/install/testwrite I should get a OK

### Actual behavior
I get page not found

### Steps to reproduce the problem
go to http://tribe.randome.camp/install/testwrite

### Friendica version you encountered the problem
I cloned latest git 

### Friendica source (git, zip)
Git

### PHP version
php -v
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

### SQL version

It seems the install directory is missing  (?!)

feydreva@randome02:/var/www/friendica$ ls -l
total 1288
-rw-r--r--  1 www-data www-data  62313 Feb 19 17:03 CHANGELOG
-rw-r--r--  1 www-data www-data   3201 Feb 19 17:03 CREDITS.txt
-rw-r--r--  1 www-data www-data    834 Feb 19 17:03 Doxyfile
-rw-r--r--  1 www-data www-data  14084 Feb 19 17:03 INSTALL.md
-rw-r--r--  1 www-data www-data  27525 Feb 19 17:03 LICENSE
-rw-r--r--  1 www-data www-data   3679 Feb 19 17:03 README.md
-rw-r--r--  1 www-data www-data     12 Feb 19 17:03 VERSION
-rw-r--r--  1 www-data www-data   1492 Feb 19 17:03 Vagrantfile
drwxr-xr-x  3 www-data www-data   4096 Feb 19 17:03 bin
-rw-r--r--  1 www-data www-data  23128 Feb 19 17:03 boot.php
-rw-r--r--  1 www-data www-data   2519 Feb 19 17:03 build.xml
-rw-r--r--  1 www-data www-data   2532 Feb 19 17:03 composer.json
-rw-r--r--  1 www-data www-data 137204 Feb 19 17:03 composer.lock
drwxr-xr-x  2 www-data www-data   4096 Feb 19 17:03 config
-rw-r--r--  1 www-data www-data  61557 Feb 19 17:03 database.sql
drwxr-xr-x  6 www-data www-data   4096 Feb 19 17:03 doc
-rw-r--r--  1 www-data www-data    234 Feb 19 17:03 docblox.dist.xml
-rw-r--r--  1 www-data www-data 866896 Feb 19 17:03 friendica_test_data.sql
drwxr-xr-x  4 www-data www-data   4096 Feb 19 17:03 images
drwxr-xr-x  2 www-data www-data   4096 Feb 19 17:03 include
-rw-r--r--  1 www-data www-data    377 Feb 19 17:03 index.php
drwxr-xr-x  2 www-data www-data   4096 Feb 19 17:03 library
drwxr-xr-x  2 www-data www-data   4096 Feb 19 17:03 mod
drwxr-xr-x  4 www-data www-data   4096 Feb 19 17:03 mods
-rw-r--r--  1 www-data www-data    871 Feb 19 17:03 phpunit.xml
-rw-r--r--  1 www-data www-data    549 Feb 19 17:03 ruleset.xml
drwxr-xr-x  2 www-data www-data   4096 Feb 19 17:03 spec
drwxr-xr-x 15 www-data www-data   4096 Feb 19 17:03 src
drwxr-xr-x  6 www-data www-data   4096 Feb 19 17:03 tests
-rw-r--r--  1 www-data www-data   9952 Feb 19 17:03 update.php
drwxr-xr-x 20 www-data www-data   4096 Feb 19 17:21 vendor
drwxr-xr-x 11 www-data www-data   4096 Feb 19 17:19 view

**Comment by MrPetovan** [comment]
This path test the URL rewriting capabilities, which means it isn't an existing file path in the project. Have you copied `.htaccess-dist` to `.htaccess` if you'r using Apache?

**Comment by feydreva** [comment]
yes I have copied .htaccess-dist to .htaccess

since the domain of this install is tribe.randome.camp 
I have modify it  and uncomment  RewriteBase /


OK... found the issue. I have the wrong directery set up in my apache conf file...
