### ISSUE TITLE
Cannot find admin panel ?

### ISSUE THREAD

**Issue by feydreva** [friendica/friendica#6701]
Using the mail configured during installation for registration should give access to admin pannel.

I created the 1st user using the mail given in the installation phase.
I can see it in the local.config.php file  : 'admin_email' => 'XXX@yyy.zz',
I didn t need to verify the email for that user...

but when I logg in with it, I do not see the admin panel.
Where is the menu for the admin panel ?

thank you

**Comment by MrPetovan** [comment]
It depends on the theme, please try the `/admin` path on your Friendica domain.

**Comment by feydreva** [comment]
yes it works.
it is not documented anywhere, and I used the default theme
Thanks :)

**Comment by MrPetovan** [comment]
On `vier`, it is a "slider" icon in the middle of the header bar.
On `frio`, it is in the user menu.
