### ISSUE TITLE
Firefox 65.0.1 doesn't show the notifications sub menu (frio)

### ISSUE THREAD

**Issue by annando** [friendica/friendica#6702]
### Expected behavior
When clicking on the notification symbol, the submenu with the listed notifications should appear.

It has got to be a browser problem, since it works with other Firefox versions or other browsers. Reloading doesn't help.

### Actual behavior
A submenu without any entry does appear.

### Steps to reproduce the problem
Use Firefox Quantum 65.0.1 (MacOS) 

### Friendica version you encountered the problem
2019.03-dev

**Comment by MrPetovan** [comment]
vier and frio alike? No Console error?

**Comment by annando** [comment]
Under "vier" the same problem occurs. I'm getting this one:
````
NS_ERROR_FILE_CORRUPTED: main.js:244

    <anonym> https://pirati.ca/view/js/main.js:244 dispatch7jQuery

NavUpdate https://pirati.ca/view/js/main.js:396 i4jQuery
````

**Comment by MrPetovan** [comment]
That's a new one for me.

**Comment by MrPetovan** [comment]
What about this: https://davidjb.com/blog/2017/11/resolving-an-ns_error_file_corrupted-error-in-mozilla-firefox/

Can you please run 

```
localStorage.clear()
sessionStorage.clear()
```
In your Javascript console?

**Comment by annando** [comment]
````
localStorage.clear();
[Exception... "File error: Corrupted"  nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]
````

**Comment by MrPetovan** [comment]
Ok so this is your own Firefox install that's corrupted.

**Comment by MrPetovan** [comment]
The provided article suggests to run the commands again when they failed once.

**Comment by annando** [comment]
After the command it worked again.
