### ISSUE TITLE
Frio login page custom background image isn't being used

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6712]
### Expected behavior

I expect my login page custom background image setting to be used.  It is set (and has been for a very long time) to use https://social.isurf.ca/photo/54914271625ab7ea1855c3c683199971-0.jpg which is publically available.

### Actual behavior

Frio is using it's default login page background with 2019.03-rc 

### Steps to reproduce the problem

Go to admin/themes/frio and set a Login page background image.  Even with it set, it's displaying Frio's default background on the login page.

### Friendica version you encountered the problem

2019.03-rc

### Friendica source (git, zip)

git 

### PHP version

7.3.1

### SQL version

mariadb 10.3.12

**Comment by realkinetix** [comment]
If one has a look at the login page at social.isurf.ca and sees my custom image, it's due to me replacing Frio's img/login_bg.jpg file directly, not because of the settings.

**Comment by realkinetix** [comment]
Switching config_adapter from jit to preload fixes this.

**Comment by MrPetovan** [comment]
Glad to hear this!

**Comment by nupplaphil** [comment]
Possibly fixed with #6724 (please try again with JIT config-adapter)

**Comment by realkinetix** [comment]
This seems to be OK now as well with jit.  Thanks!
