### ISSUE TITLE
2019-3-RC Settings in the admin are not taken over, text disappears.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6716]
It has just struck me that in the admin area under page -> registration the welcome text has disappeared and changed settings are no longer adopted.

### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
5.5.5 Meria

**Comment by nupplaphil** [comment]
There's a bug setting config values in the db when there's already a value in the config file.

**Comment by nupplaphil** [comment]
Fixed with #6724
