### ISSUE TITLE
Atom feed behind GET query params: Ampersand gets escaped to html entity before request

### ISSUE THREAD

**Issue by softmetz** [friendica/friendica#6733]
### Expected behavior

I want to add a feed from TT-RSS into Friendica, using the sharing URL, e.g. https://host.of.ttrss/public.php?op=rss&id=-2&view-mode=all_articles&key=cpi5ef5c71f296c683f

### Actual behavior

- I get an error stating, that no valid protocol or feed was find. 
- Log says, the request returned HTTP status 403
- Checking Log on TT-RSS shows that the following was requested: https://host.of.ttrss/public.php?op=rss&amp;d=-2&amp;view-mode=all_articles&amp;key=cpi5ef5c71f296c683f

### Steps to reproduce the problem

1. Get feed URL with Query parameters (e.g. from tt-rss)
2. Add feed URL as new Contact
3. Feed doesn't get added, instead error shows up, that the protocol or feed are unknown

### Friendica version you encountered the problem

- 2019.01
- 2019-03-dev

### Friendica source (git, zip)

git

### PHP version

7.3

### SQL version

1293

**Comment by annando** [comment]
Will be fixed by PR https://github.com/friendica/friendica/pull/6734
