### ISSUE TITLE
[API] - Use of Friendica with Fedilab

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#6739]
Hey there,

I am starting this issue so we can exchange about the API and its integration with [Fedilab](https://gitlab.com/tom79/mastalab).
 
Currently, I built a [common code](https://gitlab.com/tom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/client/GNUAPI.java) for handling API calls for Friendica and GNU social (with some divergences).

I would like with this thread, to exchange with dev/users for building an app matching expectations of Friendica users.

The first step, I would like to introduce groups, like I did for GNU social, but I didn't success yet for understanding how it works with the web app (I can create them but not mention them). Do groups are also seen as users?

**Comment by tobiasd** [comment]
Thanks for adding support for Friendica to Fedilab :-)

No, groups are not seen as users. They are collections of the contacts as a user wants to sort their contact. There are some [API calls](https://github.com/friendica/friendica/wiki/Friendica-API#friendicagroup_show--auth) (and following) to handle contact groups. When you post a new top level posting, you can set the ID of a group to dis-/allow all the members of the groups to see that posting in question.

**Comment by stom79** [comment]
OK. Thank you. I will investigate that point. I will use Friendica more often to better understand its use. I also added the tag and issues can be fetched here: https://gitlab.com/tom79/mastalab/issues?scope=all&utf8=%E2%9C%93&state=all&label_name[]=Friendica

**Comment by annando** [comment]
Question is what you mean with "groups". I can imagine that you mean the thing that we call "forum" in Friendica. This is roughly comparable to the groups from GNU Social. These forum you also address with the ```!``` like you do on GS.

**Comment by stom79** [comment]
Oh! OK. I didn't find that in the api doc. Could you give me more details (api endpoints)?

**Comment by tobiasd** [comment]
The forums are not in the API. You just make a normal posting (top-level) and mention a forum the account is in contact with (forums in Friendica are regular accounts with a special role) and mention the forum with a `!name`-mention. The forum will then redistribute the posting to the members of the forum.

**Comment by poVoq** [comment]
@stom79 please also include HubZilla as a supported platform. Should be similar to Friendica.
I think both also have a Twitter1.1 API extension that works for example with Twidere.

**Comment by stom79** [comment]
@poVoq Yes, I will. https://gitlab.com/tom79/mastalab/issues/827

**Comment by stom79** [comment]
I would need your help. I implemented the Direct message timeline with the conversation for direct messages.
But I didn't manage to post a reply. Here is what I am using:

https://github.com/friendica/friendica/wiki/Friendica-API#direct_messagesnew-postput-auth

```
user_id: id of the user
screen_name: screen name (for technical reasons, this value is not unique!)
text: The message
replyto: ID of the replied direct message
title: Title of the direct message
```
What params are mandatory? What these params are waiting? For instance, for replyto, is it the conversation id or the id of the message we are replying?

Thanks for the clarification.

**Comment by annando** [comment]
I will check this.

**Comment by annando** [comment]
```replyto``` is a numeric id of the message that we are replying to. At minimum for a mail we need ```user_id``` or ```screen_name``` and ```text```.

**Comment by stom79** [comment]
Thanks. That works!

**Comment by poVoq** [comment]
Strange swap of username and full name:
https://gitlab.com/tom79/mastalab/issues/844

**Comment by stom79** [comment]
What I am missing the most with Friendica is the ability to search for messages by passing a URL, that will help to resolve the remote account and the post. Something like:

https://libranet.de/api/search&q=https://toot.fedilab.app/@fedilab/103228200800794861

Do you think it's possible to implement it?

**Comment by MrPetovan** [comment]
Absolutely, we already do it on the Friendica fronted. What would be the expected output? On the frontend we redirect to the local copy of the post we fetched.

**Comment by stom79** [comment]
Oh that's great! 
I don't know how Friendica works in this case, but ideally, if the search is an account URL, I would expect a json array of accounts. For messages, a json array of posts. That will allow to keep the logic of the API on my end.

Mastodon, for instance returns the same structure with `/api/v2/search?q=my_url`: `{accounts: [,…], statuses: [], hashtags: []}` when searching an account, and `{accounts: [], statuses: [,…], hashtags: []}`  for posts.

It's not needed to group them like the Mastodon API (ie; accounts, statuses, hashtags) but keeping the same payload for statuses (ie: Friendica home timeline) and accounts (ie: when checking following/followers with Friendica) would really help.

BTW, is there a way to see follow requests? It seems by default, Friendica followers need to be approved. That could be great too if I can put this feature with the app.

**Comment by MrPetovan** [comment]
Same as timeline and same as contacts, got it.

> BTW, is there a way to see follow requests? It seems by default, Friendica followers need to be approved. That could be great too if I can put this feature with the app.

Yep, it's `api/friendships/incoming` according to the same Twitter API endpoint: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-incoming

**Comment by stom79** [comment]
Thanks. What second API endpoint can I use to get accounts from the previous `/friendships/incoming` call.
I tried to pass the array of ids from the previous endpoint to `/users/lookup.json` but I got a 404.

**Comment by stom79** [comment]
@MrPetovan did Friendica implement an endpoint to accept follow requests? It seems it doesn't exist for Twitter.

**Comment by MrPetovan** [comment]
I had the feeling this question was coming next, and unfortunately I don't have a positive answer for you. I'll create a separate issue for it.

**Comment by annando** [comment]
Does Mastodon has got these endpoints? Our longtime goal is a Mastodon compatible API. So we could enable these endpoints and could implement the other Mastodon endpoints step by step.

**Comment by MrPetovan** [comment]
> Does Mastodon has got these endpoints?

Yes, see #7887

**Comment by annando** [comment]
Are there still any issues out there?

**Comment by SpcCw** [comment]
It seems there is some problem with replying now. I have tried using Fedilab with my instance (current develop) and when I reply to some post the comment gets sent as a separate post.

I checked the webserver log and this endpoint is used: `/api/v1/statuses`

In Friendica log it also seems correct:
```
2023-01-28T15:31:42Z index [DEBUG]: Got request parameters {"request":{"status":"xyzxyz","media_ids":[],"poll":[],"in_reply_to_id":14610365,"quote_id":0,"sensitive":false,"spoiler_text":"","visibility":"unlisted","scheduled_at":"","language":"ru"},"command":"api/v1/statuses"} - {"file":"BaseModule.php","line":288,"function":"checkDefaults","request-id":"63d53fde8f769","uid":"7876b8","process_id":236152}
```
If I manually check status 14610365 with API it also exists:
```
curl -sS -u usr:pass --request GET --url "https://friends.deko.cloud/api/v1/statuses/14610365"
// the status is shown //
```

And when I try to manually reply using API I get the same result as in Fedilab - it gets posted separately:
```
curl -sS -u usr:pass --request POST --data "in_reply_to_id=14610365" --data "status=xyzxyz" --url "https://friends.deko.cloud/api/v1/statuses"
```
```
{
    "id": "14610670",
    "created_at": "2023-01-28T15:55:39.000Z",
    "in_reply_to_id": null,
    "in_reply_to_status": null,
    "in_reply_to_account_id": null,
```

So it seems there is some problem with API here. Also I see that these separate posts have wrong visibility (always public) even when I select unlisted.

**Comment by annando** [comment]
This "comments are created as a separate post" should be fixed in the latest develop. When have you updated the last time?

**Comment by SpcCw** [comment]
I am pretty sure it was yesterday but maybe something went wrong in the update script or got cached... I updated again and indeed it works now.

The question with incorrect visibility remains though. Or it isn't supported by Friendica yet?

**Comment by annando** [comment]
When you mean this "answer with changed privacy setting": We recently added an check so that posts will not be processed, when the privacy settings are changed.

**Comment by SpcCw** [comment]
@annando - yes, it works from web interface but not from Fedilab (or maybe API in general).

Example: someone replies to my public post with limited visibility comment. If I reply to that comment from web interface then my reply is also unlisted (which is correct). If I reply from Fedilab it goes as public - even though it is selected as "unlisted" in the app and `"visibility":"unlisted"` is passed to API.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/35988439/215316500-81035da8-b54e-4d82-aaec-0d342900aae8.png)

**Comment by foss-** [comment]
By now Fedilab is working quite nicely and Tom deprecated his GitHub account so there won't be further interaction via this channel. Can this issue be closed?

Remaining issues in regards to Fedilab interaction should be filed as new issues.
