### ISSUE TITLE
Notification "mark as seen" button not working

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#6748]
### Expected behavior
When clicking on the "mark as seen" button the notifications should disappear... they do not :( 

### Actual behavior
Well, see above.

### Steps to reproduce the problem
Install, use Frio theme, try button when notifications show up.

### Friendica version you encountered the problem
2019.01 & 2019.03RC

### Friendica source (git, zip)
git
### PHP version
7.3
### SQL version
5.6

A bit strange that this seems to effect not sufficient people that is bug as shown up before? Maybe I have some strange configuration issue?

**Comment by poVoq** [comment]
I should add that this only effects some notifications that seem stuck on the pull down. If I click on all notification Friendica claims that there are no unread notifications.

Also happens with the "Vier" theme by the way.

**Comment by MrPetovan** [comment]
What kind of notification still shows up after you clicked "Mark as seen"? There's an expected delay between the time you press the button and the notification list display update because it's refreshed on the next recurrent polling Ajax call every 10 seconds or so.

**Comment by poVoq** [comment]
Several ones, as old as when I first installed my instance.It doesn't work at all on those it seems.

**Comment by MrPetovan** [comment]
Can you describe the type of notification staying?

What happen if you manually browse `/notify/mark/all` on your node?

**Comment by poVoq** [comment]
That gives me a "result success" message but the notifications remain visible in the drop down.

The notification are mixed, one connection acceptance and several comment notifications. But in total only 7 or so that seem stuck.

Sorry that I can't pin it down better'

**Comment by MrPetovan** [comment]
Are you running your own node? Do you have access to the database?

**Comment by poVoq** [comment]
Yes to both, however on a shared host (with SSH). I am currently testing Friendica, but ran into multiple issues. The same server runs Hubzilla fine.

**Comment by MrPetovan** [comment]
Well, it is hardly surprising given Friendica and Hubzilla are two different piece of software.

What does the following query give you?
```sql
SELECT * FROM `notify` WHERE `seen` = 0;
```

**Comment by tobiasd** [comment]
> but the notifications remain visible

Notifications that are read will not be removed from the list in the drop-down menu for notification. But they get a different background colourisation. Maybe this is the reason for this issue?

This helps to get back to recent conversation threads more easy as the (marked as read) notifications stay there for easy access to the thread.

**Comment by poVoq** [comment]
Ahh, ok. Well then I'll close this :) It is a bit contrary to how other systems do it, but it does make sense in its own way I guess. Maybe another button to "clear" notifications would make it less confusing for new users.

**Comment by MrPetovan** [comment]
This behavior is similar to Twitter's, for example, where notifications stay in the list after they have been seen. Why would you want a clear feature?

**Comment by poVoq** [comment]
Never used Twitter. Maybe just my neuroticism to want to clear away the notifications after having read them :)
