### ISSUE TITLE
Relayed posts are not accessible via search or notification

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6762]
### Expected behavior
There posts coming via relay server to my stream. When I search for those posts, I get a result and when I click  on "View in context". It jumps directly to the post.

### Actual behavior
Clicking on the results on "View in context" I get an empty page (no WSOD!). Just empty 
2 Screenshot (before clicking and result)
![00_temp](https://user-images.githubusercontent.com/24474762/53405848-052bcb80-39b9-11e9-9b41-c3c31f039fc0.png)

### Steps to reproduce the problem
Search for tags
Example: https://horche.demkontinuum.de/search?tag=Mediagobblin

### Friendica version you encountered the problem
Friendica 2019.03-rc / git / PHP7.2 / mariadb  Ver 15.1 Distrib 10.1.37

**Comment by hoergen** [comment]
If you like such a post or comment it or somebody else is commenting or mentioning you and you get a notification, the click on the notification leads to an empty page.

**Comment by hoergen** [comment]
Checked it again and it is working now.

**Comment by annando** [comment]
It's magic :-)
