### ISSUE TITLE
Console storage move isn't handling table name option

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6785]
As per: https://social.isurf.ca/display/c443a55c-395c-787a-acda-3ba460245966 I discovered that the console move process with the attach table being set in the command didn't restrict the move to the attach table.  It doesn't seem to be getting passed to the StorageManager.php move() function.

**Comment by tobiasd** [comment]
Part of #6263

**Comment by MrPetovan** [comment]
Closed via #6786
