### ISSUE TITLE
Profile Photo doesn't propagate all places properly

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#6804]
### Expected behavior
1. Make an account and see a default image or generated gravitar.
1. Upload a picture at the first prompt to do so. Crop appropriately. Save the result.
1. Over some period of time see the image all places that link a profile with the uploaded image. e.g. Directory, theme widgets like "Last users" in Vier, Forum Directory, and so on.

### Actual behavior
1. Make an account and see a default image or generated gravitar.
1. Upload a picture at the first prompt to do so. Crop appropriately. Save the result.
1. Over some period of time see the image some places that link a profile with the uploaded image but not all places. The default picture persists in many locations. e.g. Directory, theme widgets like "Last users" in Vier, Forum Directory, and so on.
1. Attempt to remedy this by editing the users photo's list (_deleting the default image and selecting one of the strangely duplicated original user uploaded pictures as the Profile Image_), and discover it did not solve the problem. The default image persists for many days. It almost seems like a stochastic process. e.g. see image below: doing this operation to the Technical Support user caused the image for the Stock Picking Discussion forum to be disrupted back to the default gravitar and had no effect on Technical Support or the Admin (off screen with correct uploaded image).

### Steps to reproduce the problem
**see Actual Behavior section.**

### Friendica version you encountered the problem
2009.01

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
MariaDB 10.1.38

![screenshot from 2019-03-03 17-21-31](https://user-images.githubusercontent.com/28640985/53702807-02760f80-3dd9-11e9-92d0-2ab31e47924e.png)

![screenshot from 2019-03-03 17-21-58](https://user-images.githubusercontent.com/28640985/53702810-06099680-3dd9-11e9-8340-574c581a4fc8.png)

**Comment by MrPetovan** [comment]
This looks like a potential issue with the `forumdirectory` addon, anyone can confirm the massive avatars?

**Comment by vinzv** [comment]
With Frio it all looks fine:

![image](https://user-images.githubusercontent.com/74432/63655898-084c1c80-c78e-11e9-9484-768e8f87373d.png)

Same with Vier:

![image](https://user-images.githubusercontent.com/74432/63655913-2ade3580-c78e-11e9-8759-d125d7faaf29.png)

Maybe someone with more than just one forum should re-check that.

**Comment by WNYmathGuy** [comment]
@vinzv I guess it should have been closed long ago. It actually looks fine in the variety of themes I use too.

**Comment by vinzv** [comment]
Well then: could you please close it? Thanks!

**Comment by WNYmathGuy** [comment]
I thought tech people did that. Sorry.
