### ISSUE TITLE
Fatal Error in Delivery.php

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6812]
This came up one time only, when the cron ran after I added a post:

`PHP Fatal error:  Cannot use Friendica\Model\Queue as Queue because the name is already in use in /src/Worker/Delivery.php on line 16`

Version 2019.01

**Comment by nupplaphil** [comment]
Seems like a "use" namespace conflict in `Delivery.php`

**Comment by annando** [comment]
Do you have got a whole callstack?

**Comment by miqrogroove** [comment]
If it repeats I will try to get more info.

**Comment by MrPetovan** [comment]
I'm on it.

**Comment by MrPetovan** [comment]
Closed via #6818
