### ISSUE TITLE
Can't post a comment with memcached cache driver enabled

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6814]
### Expected behavior

Hitting 'Submit' on my comment actually posts the comment

### Actual behavior

Spinner goes on forever in the browser, PHP-FPM error logs show:
```
[06-Mar-2019 17:12:06 America/Toronto] PHP Fatal error:  Uncaught Exception: Memcached class isn't available in /home/friendica/friendica/src/Core/Cache/MemcachedCacheDriver.php:39
Stack trace:
#0 /home/friendica/friendica/src/Core/Cache/CacheDriverFactory.php(36): Friendica\Core\Cache\MemcachedCacheDriver->__construct(Array)
#1 /home/friendica/friendica/src/Core/Cache.php(34): Friendica\Core\Cache\CacheDriverFactory::create('memcached')
#2 /home/friendica/friendica/src/Core/Cache.php(46): Friendica\Core\Cache::init()
#3 /home/friendica/friendica/src/Core/Cache.php(83): Friendica\Core\Cache::getDriver()
#4 /home/friendica/friendica/src/Content/OEmbed.php(69): Friendica\Core\Cache::get('oembed:622:http...')
#5 /home/friendica/friendica/src/Util/ParseUrl.php(157): Friendica\Content\OEmbed::fetchURL('https://www.the...')
#6 /home/friendica/friendica/src/Util/ParseUrl.php(58): Friendica\Util\ParseUrl::getSiteinfo('https://www.the...', true, true)
#7 /home/friendica/friendica/include/items.php(106): Friendica\Util\ParseUrl::getSiteinfoCached('https://www.the...', true)
 in /home/friendica/friendica/src/Core/Cache/MemcachedCacheDriver.php on line 39
```

I actually have a lot of these starting from the time I enabled the memcached cache driver earlier today.  They all report the same initial "PHP Fatal error:  Uncaught Exception: Memcached class isn't available in /home/friendica/friendica/src/Core/Cache/MemcachedCacheDriver.php:39" error.

### Steps to reproduce the problem

Enable memcached cache driver in local.config.php

### Friendica version you encountered the problem

2019.03-rc - 1304

### Friendica source (git, zip)

git

### PHP version

7.3.2

### SQL version

mariadb 10.3.12

**Comment by nupplaphil** [comment]
Did you install the memcached driver on your system?

It isn't enough to just enable it per config, you have to install a memcache server and the `php-memcached` package too. The Fatal Error reports that it cannot load the `Memcached` class, which indicates my guess.

https://serverpilot.io/docs/how-to-install-the-php-memcache-extension

**Comment by realkinetix** [comment]
Oh dear... I have the feeling I didn't restart php-fpm.  I will check on this again...

**Comment by realkinetix** [comment]
ok... very sorry for the false report!  Hanging my head in shame!  heh.
