### ISSUE TITLE
Incoming posts from blocked servers via hashtag relay

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6819]
### Expected behavior
When a server is blocked it shouldn't be possible that posts of that server are arriving via hashtag relay server.

### Actual behavior
Blocked the server www2 . gabbers . me (without the spaces) on my node, but I keep getting posts because I saved the hashtag search #Berlin  e.g. display/5ab97ec4e96a31ee0e5ce7d928325e7c7333e316 on that node.

### Steps to reproduce the problem
Wait for a hashtag that you saved.

### Friendica version you encountered the problem
Friendica 2019.03-rc / git / PHP7.2 / mariadb Ver 15.1 Distrib 10.1.37

**Comment by MrPetovan** [comment]
Geez that's bad.

**Comment by MrPetovan** [comment]
Closed via #6834

**Comment by MrPetovan** [comment]
@hoergen Can you pull the latest RC and hopefully not see any more posts from the blocked server?

**Comment by hoergen** [comment]
I did right some seconds ago. There are still post from tonight there. I think https://github.com/friendica/friendica/pull/6849 will match only new delivered messages?

**Comment by MrPetovan** [comment]
Oh yeah, definitely. Sorry for the confusion. It would only apply to newly received posts, not for existing ones, although it probably should prevent the display of existing ones.

**Comment by hoergen** [comment]
It is happening again. Posts from servers, that are on my server block list appearing again via hashtag delivery

**Comment by annando** [comment]
An which branch are you currently?

**Comment by hoergen** [comment]
I'm on the actual develop.

**Comment by hoergen** [comment]
This server is blocked in admin panel, but there are still incoming posts 

![00_temp](https://user-images.githubusercontent.com/24474762/55700444-8b332d00-59cf-11e9-89e3-867f667cdf7a.png)

**Comment by MrPetovan** [comment]
This is supposed to have been finally fixed by #6849, any other instance since?

**Comment by MrPetovan** [comment]
I'm out of my depth with federation stuff, I'm passing the buck to @annando.

**Comment by hoergen** [comment]
Didn't occur the last weeks .. maybe it's fixed. If it doesn't happen again in the next 4 weeks, we can close this issue.

**Comment by hoergen** [comment]
Or mabye close it for this 2019.06 release. IT's no need to keep it open.
