### ISSUE TITLE
Saved Folders: Display of filed items broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6823]
### Expected behavior
When I click on a saved folder all filed items should be accessible.

### Actual behavior
When I click on a saved folder only one page of filed items is shown. If the number of 'items to display per page' is set to X I get exactly X filed items. That's it. The end.

### Steps to reproduce the problem
I'm using frio **with infinite scroll** option. My setting for 'number of items to display per page' is 20.
When I click on a folder to display the filed items I get exactly 20 items. But when I scroll down there is a line saying 'The end'. It doesn't load the next items.
When I change my setting to show e.g. 40 items per page I get 40 filed items and again 'The end' is displayed as if there are no more items. But that's not true.
**Without infinite scroll** I get an empty page (no items) when I click on the 'next' button.

Discussion: https://forum.friendi.ca/display/0b6b25a8-105c-8193-e81f-078987484912

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by tobiasd** [comment]
This is not a theme issue I think you can remove the boldness from the theme name you are using. It is a general bug.

**Comment by MrPetovan** [comment]
Fixed by #6844

**Comment by AlfredSK** [comment]
Yeah! Works again. 🍾🎉🎊💃
