### ISSUE TITLE
openid failure with a server that has multiple openid-s

### ISSUE THREAD

**Issue by vn971** [friendica/friendica#683]
I'm using an openid server "yandex.ru". It offers 3 valid openid addresses for me:
openid.yandex.ru/vn91
vn91.ya.ru
NovikovVasiliy11.moikrug.ru

Proplem: friendica allows me to log in only with the first address.
When I tested the second address I also changed it in my settings, of course. (Actually, I started with the second one and came to the first only to test friendica.)

What I think may be the reason: the server "yandex.ru" may respond with 3 allowable addresses to friendica. But friendica might check only the first one, see it doesn't match and fail to log me in.

**Comment by strk** [comment]
Time to close this (after 3 years) -- big powers please do !

**Comment by vn971** [comment]
I'm not eager to test this issue with the current version of friendica, so I'm OK with closing...
