### ISSUE TITLE
Network feed with infinite scroll unexpectedly ending

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6832]
Currently, my network feed isn't showing items older than 2 hours ago with the infinite scroll.

It's been happening a few times over the last several months all without action on my part. I don't have post expiration enabled.

When switching to pagination, the number of top-level items per page is wildly inconsistent:
- 1st page: 13 items
- 2nd page: 4 items (ending with the same last items as infinite scroll)
- 3rd page: 2 items (?!)
- 4th page: 6 items
- 5th page: 14 items
- 6th page: 15 items
- 7th page:  14 items
- 8th page: 13 items

It seems there is a hiding process happening after the current page's items have been fetched which would produce an empty infinite scroll response, breaking the whole system.

**Comment by annando** [comment]
We have solved this in one of the last versions, haven't we?

**Comment by MrPetovan** [comment]
Closed by #9418
