### ISSUE TITLE
Full Name Inconsistencies

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6848]
### Expected behavior
A user should have one full name and only one like should be displayed with the current full name.

### Actual behavior
Sometimes it happens that the user has an inconsistency with the full name. The self contact has a different name than the user's full name. That leads to double likes with both names.

### Steps to reproduce the problem
For the third time in two weeks I had to repair a user's full name. The user once had the full name set to something like 'User One' and later changed it to something like 'userone (Friendica)'. The new name magically changes back to the old one after some days. When the user likes a comment two likes are displayed on the remote side. One like for the old name and one for the new name.

**What I found out:**
Whenever that happens the self contact in the contact table is showing the old name. When I repair the name in the DB the second 'like' with the old/wrong full name vanishes.
So there is a discrepancy between the self contact and the user's record in the user table. And there is another contact in apcontact table. If I remember correctly the name field was showing the wrong name, too.

**General thoughts:**
I wonder why there are two possibilities to set the full name in our UI. You can change your name in the account settings and in your profile settings. Why does the account have a full name field? Shouldn't it be sufficient if the full name is set in the default/public profile? And more important: what happens when I set two different names in those two locations? (Maybe that's the source of the issue)

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by AlfredSK** [comment]
Does the "Needs More Info" tag means that you need more info _from me_? What do you need?

**Comment by MrPetovan** [comment]
We need more info about the actual discrepancy, e.g. between the
- user
- public contact (self)?
- remote contact if any

**Comment by AlfredSK** [comment]
I'm not sure if it is OK to post the real user name here. Maybe it is sufficient to post an example to get the picture.
This is how it looks in the DB when the issue occurs...

**user table:**
uid = 1873
nickname = 'userone'
username = 'userone (Friendica)'

**contact table:**
uid = 1873 AND self = 1
nick = 'userone'
name = 'User One'

**apcontact table:**
nick = 'userone'
name = 'User One'

When I repair the 'name' field in contact table to use 'userone (Friendica)' the inconsistency is gone and the double likes are gone too. Because the user is on my node I see the change instantly after refreshing (reloading) the page.
The last time I also repaired the 'name' in table 'apcontact'. Until now the issue didn't reoccur.

**Comment by annando** [comment]
Memo to myself: Using only one source ("self" contact) for everything :-)

**Comment by AlfredSK** [comment]
@annando About the two possibilities to set the full name in the user interface: I can set my full name in settings -> account AND in settings -> profiles -> default (public) profile. Could that be a problem, leading to the described issue?

**Comment by annando** [comment]
I just tested it. It doesn't matter where to change it, it will be distributed to all places (user, default profile, self contact).

**Comment by AlfredSK** [comment]
Hmm. Then what could have caused the inconsistency? I asked the user about it. She changed the user name once some weeks ago. Later, the name changed again by itself. That happened several times.

**Comment by MrPetovan** [comment]
What about the contact probing later? It sounds like it could be the same issue source than the transparent avatar that work as a user but not as a contact because they're fetched by the ContactUpdate worker.

**Comment by AlfredSK** [comment]
It happened again. User name switched back to the old one.

Ok. It get's crazy. I saw the wrong name in a comment and again a double like (old + new name). I went to the contact details. There was the correct (!) name displayed. I forced a contact refresh (update now). Bam! The wrong name appeared. I did a probe (see below). It showed the correct name. What? How? I went again to the contact details. Correct name! Contact update. Wrong name! Probe. Correct name! Contact. Correct name! Update contact. Wrong name. ... ... I think you get the picture. :-)

Probe:
```
Array
(
    [name] => alysonsee (Fca)
    [nick] => alysonsee
    [guid] => 0b6b25a8475af8560c0dc61391552991
    [url] => https://libranet.de/profile/alysonsee
    [addr] => alysonsee@libranet.de
    [alias] => https://libranet.de/~alysonsee
    [photo] => https://libranet.de/photo/19857237075b96afa734b48061447524-4.jpg?ts=1552878636
    [community] => 
    [keywords] => dogs urban lgbt iphoneography nordicnoir gratitude bingewatching
    [location] => Denver, Colorado, USA
    [about] => free associator, binge watcher, dog lover, urban dweller, IT manager, happy hour appetizer menu sampler.
    [batch] => 
    [notify] => https://libranet.de/dfrn_notify/alysonsee
    [poll] => https://libranet.de/dfrn_poll/alysonsee
    [request] => https://libranet.de/dfrn_request/alysonsee
    [confirm] => https://libranet.de/dfrn_confirm/alysonsee
    [poco] => https://libranet.de/poco/alysonsee
    [priority] => 0
    [network] => dfrn
.....
```

**Comment by MrPetovan** [comment]
What is the wrong name you're seeing for this account? Can you pull this profile public display name from all the places we talked before (user, self-contact, public contact, gcontact, apcontact)?

**Comment by AlfredSK** [comment]
It doesn't happen anymore. I did that cycle like 7 or 8 times. Then it stopped all of a sudden. At the moment everything is fine (again). But I'm pretty sure it will come back.
Wrong (old) name: 'Alyson See'

**Comment by AlfredSK** [comment]
OK. I watched that weird behavior for some weeks. Looks like it doesn't happen anymore. Don't ask me why but it seems to be solved.
Closing for now...

**Comment by annando** [comment]
@AlfredSK the develop branch now has got a functionality that checks and updates contacts every few days. So it should now selfrepair.
