### ISSUE TITLE
Editor doesnt seem to write to attach table (videos)

### ISSUE THREAD

**Issue by Narrekapp** [friendica/friendica#6852]
Tried to find out why my /videos/adminna on my test vm is empty

Saw /mod/videos.php tries to load from table attach.

$r = q("SELECT hash FROM `attach` WHERE `uid` = %d AND filetype LIKE '%%video%%'

Added an embedded video from youtube into  a new post

[attachment type='video' url='https://www.youtube.com/watch?v=dM0d9uUgVSc' title='SIA - Rainbow (From My Little Pony The Movie) PMV' image='https://i.ytimg.com/vi/dM0d9uUgVSc/maxresdefault.jpg']Lyrics: [Verse 1] I know you, you’re a special one Some see crazy where I see love You fall so low but soar so high Big dreamer shoot for open sky So much li...[/attachment]

Saved, video plays fine, but table attach is still empty.

Table attach in database friendica 	
This table contains no data.

I think if the editor doesnt write to this table then /mod/videos.php will never find a video, right? Confused...

**Comment by MrPetovan** [comment]
Hi @Narrekapp and sorry for the confusion.

The `attach` table is exclusively for uploading binary files (not images) in the file browser. External links attachments like the one you posted an example of aren't saved in the `attach` table.

**Comment by Narrekapp** [comment]
Hi! I saw the videos mod doesnt even have an upload function (in comparision to pics).

Would be so much easier i one could populate the videos page from og attachments!

Could you make this a "New Feature" request?

**Comment by MrPetovan** [comment]
Populating videos from attachments sounds like an import nightmare depending on the attachment target. A better first step would be to enable adding videos directly from `/videos` the same way you can independently add photos in `/photos`.

**Comment by Narrekapp** [comment]
Great news (release date)!

Now that i get used to work with Linux (Ubuntu) its time to get my first real server. :)

I think i will continue to play with the video mod if no one else wants to. Somewhen in a galaxy far far away i once had an php course (on windows! :) but so many things have changed since then and i never needed it...
