### ISSUE TITLE
IRC addon broken, /irc gives a forbidden message on 2019.03 RC

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#6854]
### Expected behavior
/irc should open the freenode webchat if the addon is enabled

### Actual behavior
gives a "forbidden" error message

### Steps to reproduce the problem
Probably: install 2019.03 RC and enable IRC addon. I upgraded my instance from 2019.01 though.

### Friendica version you encountered the problem
2019.03 RC

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
MySQL 5.6

**Comment by poVoq** [comment]
Probably same issue as mentioned here: https://github.com/friendica/friendica/issues/6674

**Comment by MrPetovan** [comment]
Possibly, good catch.

**Comment by MrPetovan** [comment]
Can anyone else confirm?

**Comment by MrPetovan** [comment]
I just tried `/irc` after having enabled the `IRC Chat Room` addon and it worked as expected.

**Comment by poVoq** [comment]
Hmm, so what could have gone wrong in my update? Some .htaccess issue maybe?

**Comment by tobiasd** [comment]
The addon is working for me using the 2019.03-RC code. Could you check your rewrite rules of the web server?

**Comment by poVoq** [comment]
Both were working before updating from 2019.01  (but the /forumdirectory looked ugly in the frio theme) and I run this instance on a shared host so I didn't play around with rewrite rules :)

**Comment by tobiasd** [comment]
To bad ;-) Is there, by chance, logged something into Friendicas logs when you try to access `/irc`?

**Comment by poVoq** [comment]
Found the error, somehow the addon git repo got dupicated in the friendica root. Thus the directories are competing. My bad, but I really wonder how that might have happend. :(

**Comment by tobiasd** [comment]
I'll try to remember this issue for the next time a strange *forbidden* reply of a server pops up ;-) Thanks for the info that you fixed the problem.
