### ISSUE TITLE
No line wrap for long XMPP adresses in profile & not clickable

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#6855]
### Expected behavior
Similar to how long profile link URL on the profile page wrap around the lines to not break the layout, so should long XMPP do. Also should support XMPP URI: https://wiki.xmpp.org/web/XMPP_URIs

### Actual behavior
See: https://freegamedev.net/profile/fgd_general
A scroll bar appears below the profile picture. Also not clickable.

### Steps to reproduce the problem
Put a long xmpp address into the XMPP profile field. I guess this might be a Frio theme specific issue?

### Friendica version you encountered the problem
2019.03 RC

### Friendica source (git, zip)
git

### PHP version
7.2.15
### SQL version
MySQL 5.6

**Comment by poVoq** [comment]
Just noticed that the link urls also don't seem to wrap in Chrome (but do in Firefox).

**Comment by poVoq** [comment]
@MrPetovan which additional information do you need?

**Comment by MrPetovan** [comment]
It would be great if we could test this in most browsers, we have been having issues with line wrap that was depending on the target browser.

**Comment by poVoq** [comment]
As written in my second post, issue is there both in Firefox and Chrome. In Chrome not even the URL doesn't wrap.

**Comment by MrPetovan** [comment]
Oh, I remember why I put the "Need more info" tag, because I couldn't verify the provided URL from work (because of domain filter on `game`)

**Comment by poVoq** [comment]
Maybe there could be an option to link to an XMPP online / MUC badge instead?
Like this:
https://modules.prosody.im/mod_muc_badge.html
or this:
https://github.com/conversejs/xmpp-chat-badge

**Comment by poVoq** [comment]
Way beyond the original issue, but presence indication via a jabber bot would be awesome:
http://serendipity.ruwenzori.net/index.php/2006/02/27/jabber-presence-indicator-in-a-web-page
A more recent example of a similar bot build with php would be: https://github.com/kanboard/plugin-jabber
And when that would be working, then all sorts of notifiactions to users/MUCs would also be possible :)

**Comment by MrPetovan** [comment]
Thanks for the suggestions!

**Comment by poVoq** [comment]
Would be still nice if a fix for the line break issues for XMPP profile fields would go into 2019.03.

**Comment by MrPetovan** [comment]
Ha, I lost track of this particular issue in the process.

**Comment by AlfredSK** [comment]
The question is also what is a better visual solution if we want avoid scrollbars?
```
💬  jabberuser@xmpp.superdom
ain.com
```
Meh. :-)

--or--

```
💬  jabberuser@xmpp.superdom...
```
Yeah.

**Comment by MrPetovan** [comment]
Hopefully
```
💬  jabberuser@xmpp.
superdomain.com
```
OR
```
💬  jabberuser@
xmpp.superdomain.com
```

**Comment by AlfredSK** [comment]
Meh. That's very ugly.

**Comment by poVoq** [comment]
If it is a proper clickable URI then I think the dots solution is the best,maybe combined with a mouseover popup. But if it stays non-clickable it of course has to be one of the full versions as mentioned above.

**Comment by MrPetovan** [comment]
Since it's supposed to be an identifier you input in your XMPP client, I don't think we can get away with a link and a truncated address and have to use the full text. Unless I'm mistaken? Is it currently a link?

**Comment by poVoq** [comment]
Currently it is not a link, but most browsers/OS understand XMPP URIs (see my link above).
Also if it is a link you can just right click on it and choose copy link location to get the full link in your clipboard.

**Comment by MrPetovan** [comment]
Most probably. I would expect free OSes to perform better about XMPP than Windows since Microsoft are carrying their own instant message software. Thanks for the elaboration, I may actually have to do both: add a link and keep the address whole.

**Comment by poVoq** [comment]
Works in the latest 2019.03 RC. Thanks a lot!
