### ISSUE TITLE
BBcode in description returned by externalprofile/show

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#6861]
### Expected behavior
When calling `/api/externalprofile/show.json`, the `description` should be in plain text.

### Actual behavior
It contains some BBcode (`[url=...`).

### Steps to reproduce the problem
Call https://social.rudloff.pro/api/externalprofile/show.json?profileurl=https%3A%2F%2Fmastodon.social%2F%40stephaniewalter

### Friendica version you encountered the problem

2019.01

### Friendica source (git, zip)
git

### PHP version
7.0.33-0+deb9u3

### SQL version
10.1.37-MariaDB

**Comment by MrPetovan** [comment]
Should it be plaintext or is HTML fine?

**Comment by MrPetovan** [comment]
Fixed by #7197
