### ISSUE TITLE
Category labels in posts are not clickable

### ISSUE THREAD

**Issue by oliverzet** [friendica/friendica#6865]
### Expected behavior
The green category labels in posts should be clickable and lead to the corresponding url. For example a
click on a green category label called "My Photos" should take me and anyone who clicks it to:
https://servername/profile/username?f=&category=My%20Photos

### Actual behavior
Right now the green category labels are not clickable. They are just sitting at the bottom of a post being only descriptive

### Steps to reproduce the problem
Go to any post that uses category labels and try clicking on the label. Nothing will happen.

### Friendica version you encountered the problem

2019.03-rc-1304

**Comment by FrancoisGeyser** [comment]
Hi, can I have a look at this?

**Comment by tobiasd** [comment]
> Hi, can I have a look at this?

Hey Francois, sure.

And thank you for diving into this (and possible the other) issue(s) :-) If you have any questions about the code, just ask. Here or in the developers forum at https://forum.friendi.ca/~developers
