### ISSUE TITLE
Registration mails: HTML version is mixed up/mangled

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6866]
### Expected behavior
The text of HTML registration mails should be correct and in the right order.

### Actual behavior
While the text of the plain text version is totally OK, the text of the HTML version is mixed up and mangled. The credentials are at the wrong place and some parts are duplicated.

### Steps to reproduce the problem
Register an account on a 2019.03-rc node and have a look at the HTML version of the registration mail. I checked this with Thunderbird (Linux), K9-Mail (Android) and Nextcloud Mail (Web).

### Example (unfortunately only in German):

Hallo Friendica Tutorials,  danke für deine Registrierung auf venera.social 🍀. Dein Account wurde eingerichtet.
--
 
Die Anmelde-Details sind die folgenden:	Adresse der Seite:	angemeldet hast.Bitte nimm dir ein paar Minuten, um die anderen Einstellungen auf dieserSeite zu kontrollieren.Eventuell magst du ja auch einige Informationen über dich in deinemProfil veröffentlichen, damit andere Leute dich einfacher finden können.Bearbeite hierfür einfach dein Standard-Profil (über die Profil-Seite).Wir empfehlen dir, deinen kompletten Namen anzugeben und ein zu dirpassendes Profilbild zu wählen, damit dich alte Bekannte wiederfinden.Außerdem ist es nützlich, wenn du auf deinem Profil Schlüsselwörterangibst. Das erleichtert es, Leute zu finden, die deine Interessen teilen.Wir respektieren deine Privatsphäre - keine dieser Angaben ist nötig.Wenn du neu im Netzwerk bist und noch niemanden kennst, dann können sieallerdings dabei helfen, neue und interessante Kontakte zu knüpfen.Solltest du dein Nutzerkonto löschen wollen, kannst du dies unter https://venera.social/removeme">https://venera.social	Benutzernamename:	XXXuserXXX	Passwort:	XXXXPasswordXXXDu kannst dein Passwort unter "Einstellungen" ändern, sobald du dichangemeldet hast.Bitte nimm dir ein paar Minuten, um die anderen Einstellungen auf dieserSeite zu kontrollieren.Eventuell magst du ja auch einige Informationen über dich in deinemProfil veröffentlichen, damit andere Leute dich einfacher finden können.Bearbeite hierfür einfach dein Standard-Profil (über die Profil-Seite).Wir empfehlen dir, deinen kompletten Namen anzugeben und ein zu dirpassendes Profilbild zu wählen, damit dich alte Bekannte wiederfinden.Außerdem ist es nützlich, wenn du auf deinem Profil Schlüsselwörterangibst. Das erleichtert es, Leute zu finden, die deine Interessen teilen.Wir respektieren deine Privatsphäre - keine dieser Angaben ist nötig.Wenn du neu im Netzwerk bist und noch niemanden kennst, dann können sieallerdings dabei helfen, neue und interessante Kontakte zu knüpfen.Solltest du dein Nutzerkonto löschen wollen, kannst du dies unter https://venera.social/removeme jederzeit tun.Danke für deine Aufmerksamkeit und willkommen auf venera.social 🍀.
 
 
  | Danke,
  | Steffen K9, venera.social 🍀 Administrator

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by tobiasd** [comment]
Can you forward me the mail?

**Comment by AlfredSK** [comment]
Done. Forwarded as attachment.

**Comment by tobiasd** [comment]
Thanks :)

**Comment by tobiasd** [comment]
Could this be a problem with the URL detection of the autolinker o.O

`Adresse der Seite:	<a href="https://venera.social&lt;br%20/&gt;%09Benutzernamename:%09tutorial&lt;br%20/&gt;%09Passwort:%09Z**********1&lt;br%20/&gt;&lt;br%20/&gt;Du%20kannst%20dein%20Passwort%20unter%20" einstellungen sobald du dich></a>`

This is the link to the node, the registration was done at. The `<a` tag is totally broken due some mishap in the replacement. But IIRC it is just the HTMLyfied version of the text message.

**Comment by MrPetovan** [comment]
Yep, looks like an autolinker mishap from when it was capturing line feeds. It was fixed with #6857, closing here. Thanks @tobias for looking into it!
