### ISSUE TITLE
statuses/mentions_timeline API returns posts that don't mention me

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#6867]
### Expected behavior
IIRC, calling `/api/statuses/mentions_timeline.json` should return posts that mention me or that are from threads I liked.

### Actual behavior
It also returns some random posts I never interacted with.
Here is a recent example:
```json
  {
    "text": "@IzzyOnDroid\nThanks!\n@toXel",
    "truncated": false,
    "created_at": "Tue Mar 12 10:43:13 +0000 2019",
    "in_reply_to_status_id": 1019293,
    "in_reply_to_status_id_str": "1019293",
    "source": "Mastodon (AP)",
    "id": 1021502,
    "id_str": "1021502",
    "in_reply_to_user_id": 0,
    "in_reply_to_user_id_str": "0",
    "in_reply_to_screen_name": null,
    "geo": null,
    "favorited": false,
    "user": {
      "id": 17679,
      "id_str": "17679",
      "name": "Maritrini",
      "screen_name": "thoughtcrime",
      "location": "Mastodon (AP)",
      "description": "Socialista libertario / anticomunista / criptoanarquista / free software zealot. Hasta las narices de que en mi país un tweet sea delito. Okdiario es un virus",
      "profile_image_url": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-6.png?ts=1547324877",
      "profile_image_url_https": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-6.png?ts=1547324877",
      "profile_image_url_profile_size": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-5.png?ts=1547324877",
      "profile_image_url_large": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-4.png?ts=1547324877",
      "url": "https://todon.nl/users/thoughtcrime",
      "protected": 0,
      "followers_count": 0,
      "friends_count": 0,
      "listed_count": 0,
      "created_at": "Sat Jan 12 20:27:57 +0000 2019",
      "favourites_count": 0,
      "utc_offset": 0,
      "time_zone": "UTC",
      "geo_enabled": false,
      "verified": false,
      "statuses_count": 0,
      "lang": "",
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "following": false,
      "follow_request_sent": false,
      "statusnet_blocking": false,
      "notifications": false,
      "statusnet_profile_url": "https://todon.nl/users/thoughtcrime",
      "cid": 0,
      "pid": 17679,
      "network": "apub"
    },
    "friendica_owner": {
      "id": 17679,
      "id_str": "17679",
      "name": "Maritrini",
      "screen_name": "thoughtcrime",
      "location": "Mastodon (AP)",
      "description": "Socialista libertario / anticomunista / criptoanarquista / free software zealot. Hasta las narices de que en mi país un tweet sea delito. Okdiario es un virus",
      "profile_image_url": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-6.png?ts=1547324877",
      "profile_image_url_https": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-6.png?ts=1547324877",
      "profile_image_url_profile_size": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-5.png?ts=1547324877",
      "profile_image_url_large": "https://social.rudloff.pro/photo/15243987795c3a4dcd74edb509223891-4.png?ts=1547324877",
      "url": "https://todon.nl/users/thoughtcrime",
      "protected": 0,
      "followers_count": 0,
      "friends_count": 0,
      "listed_count": 0,
      "created_at": "Sat Jan 12 20:27:57 +0000 2019",
      "favourites_count": 0,
      "utc_offset": 0,
      "time_zone": "UTC",
      "geo_enabled": false,
      "verified": false,
      "statuses_count": 0,
      "lang": "",
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "following": false,
      "follow_request_sent": false,
      "statusnet_blocking": false,
      "notifications": false,
      "statusnet_profile_url": "https://todon.nl/users/thoughtcrime",
      "uid": 0,
      "cid": 0,
      "pid": 17679,
      "self": 0,
      "network": "apub"
    },
    "friendica_private": false,
    "statusnet_html": "@IzzyOnDroid<br>Thanks!<br>@toXel",
    "statusnet_conversation_id": 1019284,
    "external_url": "https://social.rudloff.pro/display/cc41e9b87c58a4ad9191c7bc33e6c50ab97a2978",
    "friendica_activities": {
      "like": [],
      "dislike": [],
      "attendyes": [],
      "attendno": [],
      "attendmaybe": []
    }
  }
```

Note that the URL in `external_url` returns a blank page for some reason, so I can't even check the context of this post.
(But for posts that mention me, `external_url` works correctly.)

### Steps to reproduce the problem
I call https://social.rudloff.pro/api/statuses/mentions_timeline.json?count=20&include_blocked_by=true&include_blocking=true&latest_results=true.

### Friendica version you encountered the problem
2019.01

### Friendica source (git, zip)
Git

### PHP version
7.0.33-0+deb9u3

### SQL version
10.1.37-MariaDB

Edit: Also, these don't appear at all in https://social.rudloff.pro/notifications.

**Comment by annando** [comment]
The mentions should reflect what you are calling your network page with this parameter: ```/network/?f=&conv=1```

**Comment by Rudloff** [comment]
Well, these random messages don't appear here, so I am not really sure where they are coming from.

**Comment by Rudloff** [comment]
I got several new posts like this. Most of them are from people I don't know, but they all seem to be mentioning accounts I am following.

**Comment by MrPetovan** [comment]
Thanks for the elaboration.

**Comment by tobiasd** [comment]
Maybe this could be related to #6675? Are these postings from accounts speaking OStatus or ActivityPub?

**Comment by Rudloff** [comment]
I think they all come from Mastodon/AP.

**Comment by MrPetovan** [comment]
Something's definitely afoot. Top-level statuses are included in the output of this API endpoint, which doesn't make sense either for implicit or explicit mentions.

**Comment by MrPetovan** [comment]
Unfortunately I don't have a good enough mastery of the `thread` table to be able to change the current behavior to the intended one. Could we use the tag table instead with implicit and explicit mentions?

**Comment by annando** [comment]
Currently this API endpoint does return the stuff that ```/network/?f=&conv=1``` does return. This means that we do return all content (the complete thread) where we had interacted.

**Comment by MrPetovan** [comment]
This isn't convenient for most clients that work with individual posts. I don't think the API should return full threads. Clients should be able to fetch threads one by one based on single posts.

**Comment by annando** [comment]
I just described what the API currently does ;-) Whatever we change here, it must be well thought, since performance will be an issue.

**Comment by annando** [comment]
Problem is that we do have three different conditions:
1. People are tagging us directly.
2. People are directly answering to one of our posts or comments.
3. People are commenting in a thread where we had participated.

If we decide to only display posts from condition 1, then we will only reliably display answers from Mastodon/Pleroma there. On Friendica you can answer a post/comment without tagging. When we decide to display this as well (since they relied directly to our content), we have to see that this doesn't work with Diaspora. Diaspora doesn't know threaded comments. So technically you can't see that a post is a comment on your comment.

What do we do? Problem is the performance as well. Depending on the rules, it can be very ... interesting ... do solve this problem without killing the database.

**Comment by MrPetovan** [comment]
The implicit mention system would actually allow to filter ActivityPub direct/thread replies from actual mentions in 1., for Mastodon, Pleroma and Friendica. So this filter on implicit/explicit tags would only leave Diaspora sub-replies out because they always are attached to the top-level post.

Let's recap:
1. People are tagging us directly: Available for all protocols.
2. People are directly answering to one of our posts or comments: Available for all protocols for posts, AP/Ostatus only for comments.
3. People are commenting in a thread where we had participated: The current behavior.

I think this API endpoint should be limited to 1. + 2., because 3. is the home stream anyway.

**Comment by annando** [comment]
The "implicit mention" can be disabled, like I did for my account. I prefer to mention manually, since especially people from Diaspora do complain about being mentioned all the time :-)

I'm currently unsure how to filter for this. Possibly this is something for the "user-item" table.

**Comment by MrPetovan** [comment]
With 1. and 2. combined there's no difference between implicit mentions and explicit mentions, that's exactly what I grouped them together. Remember I worked on those damn mentions more than you actually did! 😛

**Comment by annando** [comment]
I think the best solution to this will be two boolean fields in the "user-item" table or some "type" field that indicates whether the associated post falls into category 1 or 2. I'm unsure about the naming. "mentioned" and "answered" could be possible, but I'm open for suggestions. Having two fields would help us distinguish between someone mentioning us in some post and someone mentioning us and answering to our post. But from an index point of view we should stick to one field. So possibly we stick to some "type" field with some bit operation?
