### ISSUE TITLE
/follow?url= redirects to /contact

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6868]
### Expected behavior

If I go to `/follow?url=` I get to that URL and can edit the URL bar further to add a profile address.

### Actual behavior

It redirects to `/contact`. This changed in a recent update, and I consider it a regression. The URL bar is part of the user interface.

### Friendica version you encountered the problem

This is Friendica, version 2019.03-rc that is running at the web location https://libranet.de. The database version is 1304, the post update version is 1297.

I realize this is pretty [xkcd 1172: Workflow](https://xkcd.com/1172/), but ... mobile browsers are terrible and need workarounds, and I actually think redirecting from invalid URLs are a bad idea in general. It's awful when you follow a link that has one tiny typo, and the server tells the client to forget the entire URL. Show a more relevant page than a generic 404, fine, but please keep the URL.

I imagine this change was made because it seemed neater and didn't seem to matter. But it matters to at least one user. :-)

**Comment by MrPetovan** [comment]
How do you go to `/follow?url=` in the first place?

**Comment by clacke** [comment]
The usual way, writing in the URL bar, see below.

It is by far the fastest way to get to a posts-and-comments page for a user, whether I am already following that user or not. I use it dozens of times per day, on phone and on computer. Any other method involves multiple multi-second page loads and clicking on small GUI elements or remembering the local contact number for the user. That's why URLs are an important UI, they are the CLI of the web.

Now that the page redirects, the procedure takes several times longer, from:

1. Type `fo` in URL bar.
2. Click the first suggestion.
3. Edit the URL to paste or type the username at the end.

To:
1. Type `li` in URL bar. Autocompletes to the hostname part of the URL.
2. Click the end of the partial URL to deselect and retain the autocompletion.
3. Type `fo` in URL bar. Autocompletes to the path without the query parameter.
4. Click the end of the partial URL to deselect and retain the autocompletion.
5. Type `?` in URL bar. Autocompletes to everything up to the `=`.
6. Click the end of the partial URL to deselect and retain the autocompletion.
7. Paste or type the username at the end.

This method is still faster and requiring less mental load than using the contact search GUI.

This is a problem with my web client, and if there is some good reason for the redirect I'll understand, but from the information I have at the moment, this is a regression and lost functionality.

**Comment by clacke** [comment]
I found a workaround! `/follow?url=.` does not redirect! :-D

**Comment by MrPetovan** [comment]
Closing here, I don't think we'll revisit the behavior of the empty parameter.
