### ISSUE TITLE
I run two virtual servers on one IP address and I think it's causing problems

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#6872]
### Expected behavior
Friendship requests should work properly

### Actual behavior
They don't.

### Steps to reproduce the problem
1. Spin-up one Friendica instance on a virtual server subdomain (subserver) of domain 1 on a DHCP IP address.
1. Use it for a while making some friend connections.
1. Spin up another Friendica instance on a virtual server subdomain (subserver) of domain 2 on the same DHCP assigned IP address.

### Friendica version you encountered the problem
2019-01

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
MariaDB 10.1.38

### Commentary 
I'm not certain that it's the shared IP that is a problem because there is conflicting evidence about the observed problems. e.g. a friendship connection created on server 1 prior to the creation of server 2 does not work properly, and after fully disconnecting the two-way friendship by both parties, it cannot be reestablished. I cannot see the "Connect" button on their profile even a day after disconnecting and they get an error message when clicking the connect button on my profile. I can see connect buttons for other people on their server though. Private messages to them were received using the "Message" button on their profile page, but their responses were never seen by me until by happenstance I was looking a the database and saw my name in an item-content. I found the URL of that message and was able to see and converse with them by knowing the direct link on their server for the conversation. If I visit that server's profile for the former friends profile while logged in on the Server 2 profile, I see the Server 1 profile icon and name in the personal drop-down menu. This first friend was initiated by me.

A second one on Server 1 was initiated by an outsider on a different server than friend 1. This other was discovered in the Introduction notifications, but every time I clicked the button to approve a two-way friendship, I got an error message stating that it couldn't connect to the server. The second friend I'm describing now also has a profile page that won't show me a connect button. I "@" messaged them about the problem, but either they didn't write back, or I can't see their messages like the friend 1 problem.

![Screenshot from 2019-03-13 06-15-27](https://user-images.githubusercontent.com/28640985/54309888-87b2ae80-45a7-11e9-8d18-36cab3a7b1ae.png)

![Screenshot from 2019-03-13 06-28-32](https://user-images.githubusercontent.com/28640985/54309897-8b463580-45a7-11e9-928c-b41e9b00ce18.png)

![Screenshot from 2019-03-13 15-31-20](https://user-images.githubusercontent.com/28640985/54309910-926d4380-45a7-11e9-93ae-0800c39c2706.png)

![Screenshot from 2019-03-13 15-31-31](https://user-images.githubusercontent.com/28640985/54309914-9731f780-45a7-11e9-9860-8db0ae8449f5.png)

![Screenshot from 2019-03-13 15-46-55](https://user-images.githubusercontent.com/28640985/54309920-9a2ce800-45a7-11e9-9221-695cf36c766e.png)

### Conclusion
I'm willing to do experimentation with whoever winds up working on this with my servers if that would help diagnose the trouble. I don't know where to look for logs or other data that would help diagnose the real problem.

**Comment by AlfredSK** [comment]
I don't think that's a general problem. Running multiple instances on the same machine with the same IP works from my experience. I'm running 4 nodes (4 Apache VirtualHosts, 4 domains, 4 DNS A records) on one server. They're all using the same IP.

**Comment by WNYmathGuy** [comment]
> I don't think that's a general problem. Running multiple instances on the same machine with the same IP works from my experience. I'm running 4 nodes (4 Apache VirtualHosts, 4 domains, 4 DNS A records) on one server. They're all using the same IP.

@AlfredSK Thanks for ruling that out.

**Comment by WNYmathGuy** [comment]
Just for the record, this issue and #6873 have no relationship. The other had to do with the XMPP-Chat add-on. Disabling the add-on didn't affect the basis for this issue.

**Comment by annando** [comment]
I'm running pirati.ca and squeet.me (and pirati.cc and status.pirati.ca) with the same machine and the same IP.

**Comment by WNYmathGuy** [comment]
@annando I'm not as technically savvy as you. Please be verbose about the curl command. I've used curl in the past but mainly because an install instruction recipe said to and that was just "copy & paste" without understanding.

**Comment by annando** [comment]
Just do ```curl https://your.server/.well-known/host-meta```

**Comment by WNYmathGuy** [comment]
Maybe a relevant note? I was in the sweeping power failure 3 weeks ago when that wicked wind storm raced across North America. My IP is DHCP and the ISP reassigned the IP's in my area. Is their anything in the Friendica code that uses a static IP instead of the URL to remember connections? Or am I throwing a red-herring in the mix?

@annando Both servers had similar results:
```
<?xml version='1.0' encoding='UTF-8'?><XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'
     xmlns:hm='http://host-meta.net/xrd/1.0'>
 
    <hm:Host>your.server</hm:Host>
 
    <Link rel='lrdd' type='application/xrd+xml' template='https://your.server/xrd?uri={uri}' />
    <Link rel='lrdd' type='application/json' template='https://your.server/.well-known/webfinger?resource={uri}' />
    <Link rel='acct-mgmt' href='https://your.server/amcd' />
    <Link rel='http://services.mozilla.com/amcd/0.1' href='https://your.server/amcd' />
	<Link rel="http://oexchange.org/spec/0.8/rel/resident-target" type="application/xrd+xml" 
        href="https://your.server/oexchange/xrd" />

    <Property xmlns:mk="http://salmon-protocol.org/ns/magic-key"
        type="http://salmon-protocol.org/ns/magic-key"
        mk:key_id="1">RSA.BigFreakingString.AQAB</Property>
</XRD>
```
Does that mean anything to you?

**Comment by tobiasd** [comment]
No, Friendica is using the domain not the IP (except if you installed it using the IP).

**Comment by WNYmathGuy** [comment]
> No, Friendica is using the domain not the IP (except if you installed it using the IP).

@tobiasd I did not. I made a virtual subserver (subdomain) using the [Virtualmin](https://www.virtualmin.com/) management system, then in a terminal pulled the git repo into the root folder for the subdomain.

**Comment by tobiasd** [comment]
Then it really should not be a problem with changing IP addresses with the same domain name. Same situation on my node.

**Comment by WNYmathGuy** [comment]
Last night I wrote a private message to the Admin on social.isurf.ca outlining the connection problem I was having with a member of his instance, including to links to our conversation and to this issue. This morning I saw an Introduction from the Shelenn persona, so something was possibly done by the Admin to fix the problem. Something that came to my mind was that I knew their server was a development version. I checked this morning and the other persona from the other server is also a development version.

![Screenshot from 2019-03-16 11-00-07](https://user-images.githubusercontent.com/28640985/54477284-e6ad3900-47dc-11e9-84a4-9223357c9ffb.png)

![Screenshot from 2019-03-16 10-58-55](https://user-images.githubusercontent.com/28640985/54477285-ead95680-47dc-11e9-8184-e7c58718e3df.png)

**Comment by MrPetovan** [comment]
Thanks for the update, is there any lingering issue?

**Comment by WNYmathGuy** [comment]
@MrPetovan I'll say no. I would have clicked Close and comment, but I thought it would be up to the Dev's to decide if the new version had this issue mitigated.

**Comment by MrPetovan** [comment]
I'll close here then, if you have further issue on the same topic, feel free to reopen.

**Comment by realkinetix** [comment]
As an aside, this administrator did nothing to change the situation - have been away for a few days.  While I did receive the message from Mr. Math Guy, I couldn't respond due to the fun private message settings we have by default.  I have notified him of that just now on a connect request.
