### ISSUE TITLE
Peertube remote follow does not work correctly

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#6874]
Remote follow coming from Peertube seems to add `acct:` before the account name.
For example: https://social.rudloff.pro/follow?url=acct:datagueule@peertube.datagueule.tv

### Expected behavior
I think we should accept this URL format.

### Actual behavior
I get the "Can't detect network type" error.
Removing `acct:` from the URL allows me to follow as expected.

### Steps to reproduce the problem
1. Browse to https://peertube.datagueule.tv/video-channels/c2fbac48-b069-42dd-b24c-7969c14a1374/videos
1. Click *Subscribe*
1. Fill in your Friendica account name

### Friendica version you encountered the problem
2019.01

### Friendica source (git, zip)
Git

### PHP version
7.0.33-0+deb9u3

### SQL version
10.1.37-MariaDB

**Comment by annando** [comment]
I worked on it and will prepare the fix when my other PR is merged (since that PR is based upon the other one)

**Comment by nupplaphil** [comment]
Fixed with #6882
