### ISSUE TITLE
Avatar Double Action

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6911]
### Expected behavior
normal display of avatars
### Actual behavior
after git pull today in the morning
![00_temp](https://user-images.githubusercontent.com/24474762/54683612-f93faf00-4b09-11e9-9eb0-8dbcab39cd2b.jpg)

### Steps to reproduce the problem
The Timeline looks all the same at the moment

### Friendica version you encountered the problem
2019-3-rc/php7/mariadb

**Comment by MrPetovan** [comment]
I can't reproduce this on latest RC.

**Comment by annando** [comment]
I can't reproduce either. Could you try with different browsers?

**Comment by hoergen** [comment]
Strange, you are right another Browser the problem is gone. 👍
Ok Firefox, what did you do this time... *sigh*

**Comment by MrPetovan** [comment]
We have both displays for smaller screens, but they never are supposed to show at the same time. Do you have a specific Firefox version this happens with?

**Comment by hoergen** [comment]
No a standard and one I cleanedup with a complete new profile. I did a new profile again, deleted all cookies and caches and now it is good on FF too.

**Comment by tobiasd** [comment]
> I can't reproduce either. Could you try with different browsers?

I had the situation yesterday, that many postings that contained images had those dubled. Imports from Twitter, but also normal postings by contacts.

Today it seems to have normalized.
