### ISSUE TITLE
Umlaut doesnt work properly in Swedish

### ISSUE THREAD

**Issue by Bjoessi** [friendica/friendica#6913]
### Expected behavior
Displaying åäö.
### Actual behavior
Displayiung aring auml ouml
### Steps to reproduce the problem
Set the browser language preference to Swedish
### Friendica version you encountered the problem
2019.03-rc (libranet.de) and 2019.01 (personal test server), but seems to be on all servers
![Skaermklipp](https://user-images.githubusercontent.com/48803247/54770660-5e7bc900-4c0c-11e9-9564-69929ba7934e.PNG)

**Comment by Bjoessi** [comment]
When swapping language preference to German, I see no problems like this, so it seems this is related to the Swedish language pack.

**Comment by MrPetovan** [comment]
Thanks for the report, it could be an issue either with the translation itself or the template.

**Comment by tobiasd** [comment]
On Thu, 21 Mar 2019 10:08:56 -0700
Bjoessi <notifications@github.com> wrote:

> When swapping language preference to German, I see no problems like
> this, so it seems this is related to the Swedish language pack.

Thanks for spotting this. This should affect all languages with umlaute in the labels of the login page. Which is not the case for German.

It should be an easy fix if anyone aims for the low hanging fruit (I suspect a missing "nofilter" in a SMARTY template either globally or special for the frio theme) ;-) Else I'll have a look at it tomorrow morning.

**Comment by Bjoessi** [comment]
But this is not only the login page, this seems to be everywhere in menus etc.
![Skarmklipp2](https://user-images.githubusercontent.com/48803247/54772783-cd5b2100-4c10-11e9-9872-28e820c97d31.PNG)

**Comment by MrPetovan** [comment]
Yep, it's an issue with the translation itself. I'm fixing it at the moment.

**Comment by MrPetovan** [comment]
I replaced all the unexpected HTML entities in translation texts with the appropriate character. The file has to be updated on Friendica now.

I noticed that the Swedish translation is very partial. I encourage you to create an account at Transifex (https://www.transifex.com/Friendica/friendica/) and start translating some untranslated strings.

**Comment by Bjoessi** [comment]
I am on it!

**Comment by MrPetovan** [comment]
That's the spirit, thank you very much!

**Comment by Bjoessi** [comment]
Could you perhaps also run your automagical find/replace script through the exisiting translation material?
![Capturetrans](https://user-images.githubusercontent.com/48803247/54804127-1a73dd00-4c7b-11e9-8a3a-cd4ef34fabec.PNG)

**Comment by MrPetovan** [comment]
All the existing translations for the core have been corrected, but apparently Transifex will keep showing every single version in suggestions no matter how wrong it was. We could purge these versions from the "Translation Memory" but it's a feature above our free account.

**Comment by MrPetovan** [comment]
And now all the existing Swedish translations in the addons have been corrected as well, but the wrong versions will keep showing up as suggestions as well.

**Comment by MrPetovan** [comment]
Final word: Only the Swedish translation was affected.

**Comment by Bjoessi** [comment]
Have been looking around, this is the only remaining umlaut error I have been able to find.
![vaumlnnercircles](https://github.com/friendica/friendica/assets/48803247/2bf2feba-21c2-4f54-8f27-00b37e33f6e6)

**Comment by Bjoessi** [comment]
I apologize in advance if I made an error here reopening the issue - perhaps I should have opened a new one.

**Comment by MrPetovan** [comment]
@Bjoessi Not at all, it's related. The "Friends" group is created automatically when the account is created, using the translation of "Friends" corresponding to your account language at the time of creation. After that, it will keep the same name even if the translation gets fixed later. However, you can update the name of the circle yourself by going to the `/circle/` page, clicking on its name, and then the pencil to fix its name.
