### ISSUE TITLE
Notifications pertaining to a single thread aren't cleared together anymore

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6921]
### Expected behavior

Clicking on a notifications clears all other notifications for the target thread.

### Actual behavior

After the first notification in a thread is clicked and cleared, the second-oldest notifications in the same thread shows up in the notification dropdown as unread.

### Steps to reproduce the problem

1. Have two people interact on a thread you're following.
2. Click on the first notification
3. Notice the second notification that should have been cleared

### Friendica version you encountered the problem

2019.06-dev

**Comment by nupplaphil** [comment]
Seems like a possible regression because of #6783 ..

**Comment by MrPetovan** [comment]
Indeed, I'm not sure how you went from this (notice the parentheses and the `OR` operator in the condition)
```php
q(
	"UPDATE `notify` SET `seen` = %d WHERE (`link` = '%s' OR (`parent` != 0 AND `parent` = %d AND `otype` = '%s')) AND `uid` = %d",
	intval($seen),
	DBA::escape($note['link']),
	intval($note['parent']),
	DBA::escape($note['otype']),
	intval(local_user())
);
```
To this:
```php
DBA::update('notify', ['seen' => $seen], ['link' => $note['link'], 'parent' => $note['parent'], 'otype' => $note['otype'], 'uid' => local_user()]);
```
I mean, it's slicker, granted, but logically it's nowhere near the original condition. 😋
