### ISSUE TITLE
`/manifest` generates an user session on each page load

### ISSUE THREAD

**Issue by lapo-luchini** [friendica/friendica#6927]
### Expected behavior
Manifest page not to require nor generate a session in DB.

### Actual behavior
Each page load contains a call to `/manifest` and that, in turn, generates one log entry `index [NOTICE]: no data for session` and a new row in DB.

### Steps to reproduce the problem
Load any page. (e.g. "Home")

### Friendica version you encountered the problem
854cc3e47296d4a1b01b893376064cf254d84f79

### Friendica source (git, zip)
git

### PHP version
7.3.3

### SQL version
MySQL 5.7, structure update 1304.

**Comment by nupplaphil** [comment]
I can confirm this behaviour and now I know at least where the huge mass of `no session found` comes from ;-)
