### ISSUE TITLE
Update Friendica 2019.03: blank screen for network/profile/community - Database-update 1293? Missing files?

### ISSUE THREAD

**Issue by Arrappathor** [friendica/friendica#6932]
### Expected behavior
A running single-user friendica-instance after upgrade from 2019.01 to 2019.03 (as it did flawlessly before).

### Actual behavior
I can log in (as admin) and access all sites, except network/profile/community show blank screens.
Worker is working.
Database-structure is still 1293 (shouldn't it be 1300?).
maybe some files in are missing in friendica-full-2019.03.tar.gz, like: .codecov.yml .editorconfig .gitattributes .gitignore .gitmodules .travis.yml robots.txt

### Steps to reproduce the problem
Upgrade as in 
https://github.com/friendica/friendica/releases/tag/2019.03
unpack full archives, delete files on server and upload via ftp 
permissions are set correctly (nextcloud and wordpress are running) 
bin/console dbstructure update (after making it executable) showed no error 

### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
friendica-full-2019.03.tar.gz + friendica-addons-2019.03.tar.gz

### PHP version
7.0.33

### SQL version
10.1.37-MariaDB

### OS
Raspbian 9 Stretch

Meanwhile i've restored 2019.01 without any problems. 
Thank you very much for your great tool!

**Comment by MrPetovan** [comment]
Hi @Arrappathor and thanks for your report. I can't take the time to look into your issue right now, but someone else should be in contact with you in the next 24 hours.

In the mean time, can you look if you have any error in your PHP/Web server logs?

**Comment by Arrappathor** [comment]
There are some, indeed.
Those are from my last time trying to update this morning:

[Mon Mar 25 04:53:41.025662 2019] [:error] [pid 21657] [client 173.95.176.232:59064] PHP Warning:  require(/var/www/html/vendor/composer/../paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 70

[Mon Mar 25 04:53:41.027662 2019] [:error] [pid 21657] [client 173.95.176.232:59064] PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/composer/../paragonie/random_compat/lib/random.php' (include_path='/var/www/html/vendor/pear/text_languagedetect:.:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 70

[Mon Mar 25 04:53:42.469616 2019] [:error] [pid 21689] [client 173.95.176.232:59136] PHP Warning:  require(/var/www/html/vendor/composer/../paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 70

[Mon Mar 25 04:53:42.470027 2019] [:error] [pid 21689] [client 173.95.176.232:59136] PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/composer/../paragonie/random_compat/lib/random.php' (include_path='/var/www/html/vendor/pear/text_languagedetect:.:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 70

[Mon Mar 25 05:01:32.729767 2019] [:error] [pid 21689] [client 172.93.51.164:48070] PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/html/include/conversation.php on line 823

[Mon Mar 25 05:01:32.889174 2019] [:error] [pid 21689] [client 172.93.51.164:48070] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/include/conversation.php on line 823

[Mon Mar 25 05:01:32.889458 2019] [:error] [pid 21689] [client 172.93.51.164:48070] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/include/conversation.php on line 827

[Mon Mar 25 05:01:32.890245 2019] [:error] [pid 21689] [client 172.93.51.164:48070] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to conv_sort() must be of the type array, null given, called in /var/www/html/include/conversation.php on line 833 and defined in /var/www/html/include/conversation.php:1358\nStack trace:\n#0 /var/www/html/include/conversation.php(833): conv_sort(NULL, 'created')\n#1 /var/www/html/include/conversation.php(497): conversation_add_children(Array, false, 'created', 1)\n#2 /var/www/html/src/Module/Profile.php(345): conversation(Object(Friendica\\App), Array, Object(Friendica\\Content\\Pager), 'profile', 0, false, 'created', 1)\n#3 [internal function]: Friendica\\Module\\Profile::content()\n#4 /var/www/html/src/App.php(1368): call_user_func(Array)\n#5 /var/www/html/index.php(17): Friendica\\App->runFrontend()\n#6 {main}\n  thrown in /var/www/html/include/conversation.php on line 1358

[Mon Mar 25 05:05:08.104361 2019] [:error] [pid 21657] [client 188.174.159.41:47670] PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/html/include/conversation.php on line 823

[Mon Mar 25 05:05:08.115599 2019] [:error] [pid 21657] [client 188.174.159.41:47670] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/include/conversation.php on line 823

[Mon Mar 25 05:05:08.395523 2019] [:error] [pid 21657] [client 188.174.159.41:47670] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/include/conversation.php on line 823

[Mon Mar 25 05:05:08.395774 2019] [:error] [pid 21657] [client 188.174.159.41:47670] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/include/conversation.php on line 827

[Mon Mar 25 05:05:08.396326 2019] [:error] [pid 21657] [client 188.174.159.41:47670] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to conv_sort() must be of the type array, null given, called in /var/www/html/include/conversation.php on line 833 and defined in /var/www/html/include/conversation.php:1358\nStack trace:\n#0 /var/www/html/include/conversation.php(833): conv_sort(NULL, '`created`')\n#1 /var/www/html/include/conversation.php(470): conversation_add_children(Array, false, '`created`', 1)\n#2 /var/www/html/mod/network.php(345): conversation(Object(Friendica\\App), Array, Object(Friendica\\Content\\Pager), 'network', 0, false, '`created`', 1)\n#3 /var/www/html/mod/network.php(946): networkConversation(Object(Friendica\\App), Array, Object(Friendica\\Content\\Pager), 'network', 0, '`created`')\n#4 /var/www/html/mod/network.php(385): networkThreadedView(Object(Friendica\\App), 0, 0)\n#5 /var/www/html/src/LegacyModule.php(71): network_content(Object(Friendica\\App))\n#6 /var/www/html/src/LegacyModule.php(45): Friendica\\LegacyModule::runModuleFunction('content')\n#7 [internal function]: Friendica\\LegacyModule::con in /var/www/html/include/conversation.php on line 1358

Thanks for your efforts!

**Comment by nupplaphil** [comment]
This sounds like a composer problem.

Please try
```console
$> bin/composer.phar install
```

So the dependencies will get updated too.

**Comment by Arrappathor** [comment]
Hello, 
i didn't use git to install/upgrade.
I installed and upgraded using these archive files 
https://friendi.ca/wp-content/uploads/2019/03/friendica-full-2019.03.tar.gz and
https://github.com/friendica/friendica-addons/archive/2019.03.tar.gz
where dependencies are/should be included.
Also i restored to 2019-01 to have a running system; maybe i'll try next time updating.
Thanks a lot!

**Comment by tobiasd** [comment]
What operation system is running on your server? I'll try to reproduce your problem in a VM.

**Comment by Arrappathor** [comment]
Hi!

PHP version
7.0.33

SQL version
10.1.37-MariaDB

OS
Raspbian 9 Stretch

Thank you!

**Comment by tobiasd** [comment]
I've made a clean install on Debian/Stretch with MariaDB 10.1.37 and PHP 7.0.33 from the two archive files and *it worked*. I don't think that the problems are caused by Debian vs. Raspbian.

**Comment by tobiasd** [comment]
Could you check that the file

    /var/www/html/vendor/composer/random_compat/lib/random.php

is present on your server and in the archive file? (It should)

**Comment by tobiasd** [comment]
Regarding the files not included in the archive

> .codecov.yml .editorconfig .gitattributes .gitignore .gitmodules .travis.yml

These are files needed by the development tools. They are not needed for *just running* Friendica. Hence they were removed from the archive file.

> robots.txt

The default `robots.txt` is generated by Friendica automatically when the file is missing on the file-system. So if you had such a file before, you had created it manually and should probably restore it from your backup.

**Comment by Arrappathor** [comment]
> Could you check that the file
> ```
> /var/www/html/vendor/composer/random_compat/lib/random.php
> ```
> is present on your server and in the archive file? (It should)

/var/www/html/vendor/composer has no subfolders in my archive;  
containing files are: diverse autoload_?!?.php ClassLoader.php include_paths.php installed.json and LICENSE - and no lib/random.php 

BUT: i have a test-environment myself on my local debian-pc (where updating worked without problems), but there is var/www/html/vendor/composer/random_compat/lib/random.php also missing.

**Comment by Arrappathor** [comment]
I'll try another update tomorrow. Maybe i just messed something up.
So long: thank you!

**Comment by tobiasd** [comment]
Sorry, wrong copy&pasting, the `..` in your posting results in

> /var/www/html/vendor/paragonie/random_compat/lib/random.php

that file should be present.

**Comment by Arrappathor** [comment]
Heureka! ...and my fault.

In my first attempts of updating, I've copied the **folder** config from my old installation to the new archive-files and so also **overwrote** the containing (new) files (esp. dbstructure.config.php).

During my last attempt i just copied local.config.php & addon.config.php et voila: it has been successful! I'm now running a beautiful "Dalmatian Bellflower".

Sorry for the inconveniences.
And thank you all very much for the immediate support!
Thank you.

**Comment by tobiasd** [comment]
Thanks for the update :-) and great to read that you found the origin of the problem.

**Comment by Cyborgscode** [comment]
I don't agree with "beautyfull" & "running" as : 

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/federationcloud-foode/friendica-full-2019.03/include/conversation.php on line 822
PHP Warning:  array_merge(): Argument #1 is not an array in /home/federationcloud-foode/friendica-full-2019.03/include/conversation.php on line 823

stopped friendica from functioning entirely. Yes, its just a Warning, but it broke it. 

PATCH:

from:

        foreach ($parents AS $parent) {
                $condition = ["`item`.`parent-uri` = ? AND `item`.`uid` IN (0, ?) ",
                        $parent['uri'], $uid];
                if ($block_authors) {
                        $condition[0] .= "AND NOT `author`.`hidden`";
                }
                $thread_items = Item::selectForUser(local_user(), [], $condition, $params);

                $comments = Item::inArray($thread_items);

                if (count($comments) != 0) {
                        $items = array_merge($items, $comments);
                }
        }

TO:

        foreach ($parents AS $parent) {
                $condition = ["`item`.`parent-uri` = ? AND `item`.`uid` IN (0, ?) ",
                        $parent['uri'], $uid];
                if ($block_authors) {
                        $condition[0] .= "AND NOT `author`.`hidden`";
                }
                $thread_items = Item::selectForUser(local_user(), [], $condition, $params);

                $comments = Item::inArray($thread_items);

                if (is_array($comments) && count($comments) != 0) {
                        $items = array_merge($items, $comments);
                }
        }

And when someone is on it:

PHP Notice:  Undefined index: backend-class in /home/federationcloud-foode/friendica-full-2019.03/src/Model/Photo.php on line 178

Add in Line 177:
if (!isset($photo["backend-class"]) ) return null;

because the entire following block is wrong, if backend-class is not set at all.

**Comment by Cyborgscode** [comment]
but hes correct with not copying all the configs. The update instruction should really be more precise !

**Comment by tobiasd** [comment]
> copying all the configs

Sorry for overlooking that file.

I don't think a file describing the structure of the database should be in the configuration directory at all. As I don't work on the database structure personally I did not notice that so far.

I'll update the release notes as soon as possible. But most likely not today.
