### ISSUE TITLE
Can't react on contact request

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6936]
### Expected behavior
If a contact request appears in the notification, clicking on it I can react with accept/reject/ignore

### Actual behavior
The notification is there, but as soon I click on it but on the `/notifications/intros/` page is no contact request visible
![00_temp](https://user-images.githubusercontent.com/24474762/54910765-e865b380-4ee4-11e9-9e49-e7bb71acd495.png)

### Steps to reproduce the problem
Wait for a contact request ;)

### Friendica version you encountered the problem
Friendica develop / git / PHP7.2.15-1 / mariadb Ver 15.1 Distrib 10.1.37

**Comment by MrPetovan** [comment]
From Steve Dowe by email:
> To keep a long story short, a couple of years ago I updated my Friendica.me node and it all went a bit wrong.  I started again from scratch, but used the same username (doweio@) which, as Michael Vogel pointed out, would cause problems for me regaining connections with my contacts.  Such is the case with you.  I’d like to keep my username and am slowly trying to resolve this.
> 
> Could you possibly drop me as a contact so I can reconnect with you?

I did. And he replied to me with this:

> I think I have come across a bug with introductions! I get a notification but when I click on the bell, a pop-up appears saying I have no introductions.  I’ve attached a GIF demonstrating this.  I’m running 2019-03.dev.  Shall I create a bug?
> 
> ![Screen Recording 2019-03-21 at 11 45 54](https://user-images.githubusercontent.com/925415/54920135-d1b95f80-4ed8-11e9-893e-689b9320d1c5.gif)

**Comment by rebeka-catalina** [comment]
Totally forgot, that I have already opened an issue to this : 
https://github.com/friendica/friendica/issues/6864

**Comment by MrPetovan** [comment]
Thanks for the pointer, I closed your issue because there was less details and documentation.
