### ISSUE TITLE
frio: fake comment box doesn't work with latest Chrome/Chromium

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6947]
### Expected behavior
The (fake) comment box should expand itself to the real comment box when clicking/tapping on it.

### Actual behavior
With latest Chrome/Chromium it doesn't work anymore. The comment box collapses again instantly or it doesn't expand at all (depending on OS).

### Steps to reproduce the problem
Try to expand the fake comment box with Chromium 73.0 on Linux or with Chrome 73.0 on Android.

### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
Can anyone else confirm this?

**Comment by AlfredSK** [comment]
I think so: https://forum.friendi.ca/display/c443a55c-205c-9b12-99c5-a65064446314

**Comment by MrPetovan** [comment]
I just confirmed it as well on Chrome 73 on macOS.

**Comment by AlfredSK** [comment]
Should I open an issue on Google's bug tracker that they have to test their browser to be Friendica compatible?

**Comment by MrPetovan** [comment]
Yes please, it used to work, there's no reason for it not to work anymore.

**Comment by AlfredSK** [comment]
Interesting. When you click in the box and hold the mouse button you can start typing. After the first character is in the comment box it stays open and you can release the mouse button to continue to write your comment. :-)
