### ISSUE TITLE
File to folder not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6952]
## Expected behaviour

Being able to file postings to folders.

## Actual behaviour

In the current development branch I'm unable to select a folder to file a posting to.

The dialog is empty and collapsed to the border of the box (using the vier theme), or contains the navbar of the page, but otherwise no content (using the frio theme).

This happens using Firefox 60.6 (LSR) and Vivaldi 2.4 (stable channel).

## Friendica Version

2019.06-dev, commit 1c2a77c47fbc5fed030b0c82fa3f37c0361955ce

**Comment by AlfredSK** [comment]
Here is a screenshot on Frio with Firefox. Weird.

![grafik](https://user-images.githubusercontent.com/3656054/56075101-69fe8200-5dbd-11e9-80fe-3a908fee197c.png)

**Comment by rebeka-catalina** [comment]
Oh... I thought it's a local problem caused by an addon or so
![folder](https://user-images.githubusercontent.com/7385838/56091155-9805c400-5e9a-11e9-99bd-b8cb3201f071.jpg)

**Comment by MrPetovan** [comment]
I'm on it.

**Comment by MrPetovan** [comment]
Caused by #6782, I have a fix.

**Comment by AlfredSK** [comment]
Works again! 🎉😁 Thank you very much!
