### ISSUE TITLE
Ignored Profiles should show up under contact/ignored (or somewhere else)

### ISSUE THREAD

**Issue by BinkaDroid** [friendica/friendica#6967]
You can ignore profiles which are not part of your contacts (e.g. to keep their content out of the global community stream)
### Expected behavior
You should be able to see a list of your ignored profiles somewhere
### Actual behavior
You can't keep track of all ignored profiles, as contacts/ignored won't show them & there is no way to un-ignore them if you don't remember them
### Steps to reproduce the problem
- Click on "Show contact" on a profile in your global community stream
- Click "Ignore" from the upper-right actions menu
Status will change to ignored
### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
zip

**Comment by MrPetovan** [comment]
There is an "Ignored" tab in the Contacts page now.
