### ISSUE TITLE
Duepuntozero, Vier, Quattro: Can't submit reply (to replies) with explicit mentions enabled

### ISSUE THREAD

**Issue by realityfabric** [friendica/friendica#6980]
### Expected behavior
The expected behavior is that when you reply to a comment on a post it will:

- automatically fill the comment box with @ handles that would have been automatically tagged
- allow you to add or remove @ handles
- allow you to write and post your reply comment.

### Actual behavior
The actual behavior is that the first two things happen, but there is no button to allow actually submitting the reply. You can still reply to the original post and tag people with their @ handle in those comments. It seems that you can also still comment on reply comments that do not tag anyone (and thus do not autofill the comment box with @ handles).

This is true with Mastodon and Friendica accounts when using the Duepuntozero theme.

Changing the theme to Frio allows you to use explicit mentions as expected. Switching back to Dueputozero causes it to stop working again.

### Steps to reproduce the problem
1. Set your theme to Duepuntozero.
2. Turn on explicit mentions.
3. Find or create a post.
4. Reply to the post with a different account than the one that created the post.
5. View the comment thread with a different account than the one that replied (this can be the account that made the post).
6. At this point, the comment box should be filled with the @ handle of the person who had replied. In my case, it appears to be set as placeholder text (light gray, instead of black). There will not be a submit button.

### Friendica version you encountered the problem
Version: 2019.03
DB Version: 1304
Post Update Version: 1297

### Friendica source (git, zip)
Domain: nerdica.net

**Comment by realityfabric** [comment]
I should have tested this before I posted this, but:

- Quattro and Smoothly also have this same issue.
- Vier does not have this issue.

Steps to reproduce should be the same as with Duepuntozero, but using each of those themes instead.

**Comment by foss-** [comment]
Now that Duepuntozero & Quattro are deprecated and Vier is known to work, should this issue be closed?
