### ISSUE TITLE
Contact requests from server blocked profiles

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6981]
### Expected behavior
If a user (profile) is on the server's remote contact blocklist (.../admin/contactblock) users shouldn't get contact/friend requests from these remote users.

### Actual behavior
The users are getting contact/friend requests from server blocked users/profiles and also get notifications about it.
Also, it doesn't help to ignore the contact requests. The user gets new contact requests again and again although the former requests had been ignored and are listed on the ignored contact request list (.../notifications/intros/all).

So, actually there are two issues with these contact requests. But I think they're related to the same underlying problem.

I see this behavior with ActivityPub (Mastodon) users/profiles. Maybe other protocols are affected too. But I only see the issue with AP users/profiles.

### Steps to reproduce the problem
Add an AP user/profile to your server's remote contact blocklist and then send a contact request from that AP user (click on Mastodon's 'follow' button) to your Friendica profile.

### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
Is this resolved?

**Comment by AlfredSK** [comment]
Hard to say. I did not get those requests lately. But that doesn't mean it is resolved.
But I can test it. I just have to register a Mastodon account and block it...

**Comment by AlfredSK** [comment]
Hmm... Difficult to find an instance. Maybe bear.community is good. :-)

**Comment by AlfredSK** [comment]
OK. I waited 20 minutes. No contact request / introduction. Contact blocking seems to work. Closing...
Fixed by #7170
