### ISSUE TITLE
composer.lock not up to date vs. composer.lock is modified

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6982]
### Expected behavior
`composer install` should work w/o error messages.

### Actual behavior
After switching to develop I get an error message...
`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.`

When I run `bin/composer update --no-dev` the error message is gone.

But now I get a git error about the modified composer.lock file. 

And when I checkout the upstream composer.lock to get rid of the git error I get the 'not up to date' error again. And so on... :-)

Looks like composer.lock and composer.json are somehow out of sync.

### Friendica version you encountered the problem
2019.06-dev

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
This error isn't significant, when we actually update the dependencies we update the `composer.lock` file with it. If you want, you can submit a patch with the up-to-date `composer.lock` after having ran `bin/composer update --lock`.

**Comment by MrPetovan** [comment]
Fixed by #6986
