### ISSUE TITLE
Server list is not available

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6997]
https://dir.friendica.social/servers  says that all servers have an expired version
https://server.meld.de/servers commes a 504 gateway timeour

**Comment by MrPetovan** [comment]
The first page of https://dir.friendica.social/servers shows multiple servers with `Stable Version`.

And I can open https://server.meld.de/servers just fine.

I can't reproduce any of your issues, sorry.

**Comment by copiis** [comment]
Now it's okay again.

**Comment by MrPetovan** [comment]
Also, next time please submit your directory-related issues here: https://github.com/friendica/friendica-directory/issues

We don't have a way to transfer issues between repositories yet.

**Comment by AlfredSK** [comment]
My uneducated guess: The issue was related to the downtime of git.friendi.ca.

**Comment by MrPetovan** [comment]
But the directory doesn't interact at all with `git.friendi.ca`?

**Comment by AlfredSK** [comment]
Didn't it retrieve the info about the stable/develop version from git.friendi.ca?

**Comment by MrPetovan** [comment]
I take it back, you're right.

**Comment by AlfredSK** [comment]
Thank you. Then at least I was right once today. 😁
