### ISSUE TITLE
Prevent all contact probing in frontend for magic links

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6999]
See https://github.com/friendica/friendica/issues/6971#issuecomment-482556538

Currently the `Contact::getIdForURL` has a `no_update` parameter flag that prevents almost all probing, except in the case where it's the most expensive: when a probe has never gone through and we have no local contact data.

Thanks to @annando, we can now use the less expensive `Contact::getProbeDataFromDatabase` for magic links and save some precious time for page render.

Thanks to @miqrogroove for their log perusing efforts.

**Comment by annando** [comment]
I do see "getProbeDataFromDatabase" as a helper function for "getIdForURL". I suggest to change the behaviour of the "no_update" parameter, so that a probe does never occur. That parameter is only used for frontend stuff where a probing would lead to delays.

**Comment by MrPetovan** [comment]
The whole process was wasteful anyway: we would query the DB for a contact ID based on a URL, then probe if nothing was found, to end up querying the contact data based on this contact ID.

Using `Contact::getProbeDataFromDatabase` solves two problems at once. We don't probe ever and we directly get the data we need. It is simpler than to rewrite `Contact::getIdForURL` that is used in many parts of the code.

**Comment by miqrogroove** [comment]
You might need to do both.  Even if this is more efficient, it leaves the other function somewhat bugged.

**Comment by MrPetovan** [comment]
It isn't a problem for backend usages, so in that regard it isn't "bugged", just extremely inconvenient in a corner case when used for frontend, which is outside of this method's concern.
