### ISSUE TITLE
Creating a contribution with Frio complex

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#7008]
The functions for creating a contribution with picture or video are all very widely distributed in Frio. This is not intuitive to learn. This reduces the attractiveness of the application because it looks more complex than it is.
By rearranging the position of individual elements, the application can be operated more easily and quickly.

- The post preview should move under the post, as in the comments. 
- The button "Preview" moves to the editor.
- Uploading images and files is also integrated into the editor. 
- The image and file preview can be opened below the editor.
- You can switch between the functions "Preview" and "Plant browser". Only one of the functions is active at a time.

![Editor_frio](https://user-images.githubusercontent.com/44441246/56089759-2c225c00-5e98-11e9-894c-1823f9454373.png)
Since I cannot develop it myself, this is to be understood here as a suggestion of an end user.

**Comment by MrPetovan** [comment]
Thank you for your suggestion! The main creator of the frio theme is @rabuzarus, I'll leave him comment on your suggestions first.

**Comment by rabuzarus** [comment]
Personally I don't like the suggestions. Most of them leading to a behavior which was already implemented in former times and which frio has changed to improve the situation. But like always many improvements are some kind of personal taste

 > - The post preview should move under the post, as in the comments.
> - The button "Preview" moves to the editor.

Frio introduced the "Preview tab" so user doesn't need to scroll for previewing short posts. And scrolling is rather annoying - especially in modals

> - Uploading images and files is also integrated into the editor.

This would be a very inconsistent behavior. The modal tabs are used to display other content in the modal (Editor, Permissions, Preview, Files). In the case of the Upload tab displays a file manager.
To be consistent according to your suggestion all other tabs would have to be icons which are below the editor. This would rise the visual complexity and would be problematic on smaller screens
