### ISSUE TITLE
Filling out "title" field makes formatting on mastodon and pleroma go wild

### ISSUE THREAD

**Issue by Ai-rin** [friendica/friendica#7015]
Using title field leads to stripped spaces and/or new lines, and missing media preview on those networks.
My guess is that Friendica's format converter is failing, but I can be wrong.

For example, the source post:
https://libranet.de/display/0b6b25a8-555c-b3b8-2280-162586625873

And this is how it looks on Pleroma and Mastodon:
![Screenshot_20190416_135027](https://user-images.githubusercontent.com/29887769/56203804-9bda4780-604e-11e9-8e92-4db684ac06b9.png)
![Screenshot_20190416_135231](https://user-images.githubusercontent.com/29887769/56203918-e360d380-604e-11e9-97c7-3decc29402c2.png)

Friendica version is 2019.06-dev that is running at the web location https://libranet.de.

**Comment by MrPetovan** [comment]
Hi @Ai-rin and thanks for your report. Unfortunately both these displays are expected and don't depend on our side. It boils down to the way Friendica, Pleroma and Mastodon handle posts.

For starters, I probably should explain how your top post is stored in Friendica. It should look something like:
```
Title: 赤い靴 (red shoes)
Body: #art
[attachment link='https://twitter.com/avogado6/status/1117416367521558528' image='https://libranet.de/proxy/09/aHR0cHM6Ly9wYnMudHdpbWcuY29tL21lZGlhL0Q0SGNMekdVRUFBR2Z1eC5qcGc6bGFyZ2U=' title='アボガド6 on Twitter']“赤い靴”[/attachment]
```
Title and body are two different fields, and there's a whole BBCode block to handle the link preview.

Here's the catch though: neither Pleroma nor Mastodon handle title fields nor BBCode blocks. So we have to send them something they can understand.

The final content we send to both these platforms is this:
```json
{
  ...
  "id": "https://libranet.de/objects/0b6b25a8-555c-b3b8-2280-162586625873",
  "type": "Article",
  "summary": "#art“赤い靴”",
  "published": "2019-04-14T22:45:54Z",
  "url": "https://libranet.de/display/0b6b25a8-555c-b3b8-2280-162586625873",
  "attributedTo": "https://libranet.de/profile/airin",
  "sensitive": false,
  "context": "https://libranet.de/display/airin/27234646",
  "name": "赤い靴 (red shoes)",
  "content": "#<a href=\"https://libranet.de/search?tag=art\" class=\"tag\" title=\"art\">art</a> <a href=\"https://twitter.com/avogado6/status/1117416367521558528\" target=\"_blank\">twitter.com/avogado6/status/11&hellip;</a>",
  "source": {
    "content": "#[url=https://libranet.de/search?tag=art]art[/url]\r\n[attachment type='link' url='https://twitter.com/avogado6/status/1117416367521558528' title='アボガド6 on Twitter' image='https://pbs.twimg.com/media/D4HcLzGUEAAGfux.jpg:large']“赤い靴”[/attachment]",
    "mediaType": "text/bbcode"
  },
  ...
}
```
You can see all the different pieces of information that each network chooses to display.

On Pleroma, they just show the `name` field and the HTML `content` field.

On Mastodon, they show the `name` field, the `summary` field (which is all the visible text in the post body if you simply remove the BBCode tags) and the `url` field to the original post.

We don't have any influence on these decisions, and tweaking the output per network would be cumbersome.

Hopefully I addressed your confusion, let me know if you have more questions.

**Comment by Ai-rin** [comment]
Lot of thanks for such a detailed answer! I suppose, best workaround I have for now, is not use "title" field for compatibility reasons. Hopefully, they will address this issue somehow in the future.

**Comment by MrPetovan** [comment]
I wouldn't have too much hope for this, I don't think they consider their own behavior like an issue.
