### ISSUE TITLE
#1214 - The used table type doesn't support FULLTEXT indexes

### ISSUE THREAD

**Issue by Danie10** [friendica/friendica#7021]
### Expected behavior
Database to be created without errors

### Actual behavior
Gives error #1214 - The used table type doesn't support FULLTEXT indexes

### Steps to reproduce the problem
Tried standard install as well GIT CLONE to webserver but I get the error above after linking to the database.
I then went into phpMyAdmin and dropped the tables and imported the database.sql file.
It gives this error after importing:
Error
SQL query:
TABLE profile
CREATE TABLE IF NOT EXISTS profile (
id int unsigned NOT NULL auto_increment COMMENT 'sequential ID',
uid mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'Owner User id',
profile-name varchar(255) NOT NULL DEFAULT '' COMMENT 'Name of the profile',
is-default boolean NOT NULL DEFAULT '0' COMMENT 'Mark this profile as default profile',
hide-friends boolean NOT NULL DEFAULT '0' COMMENT 'Hide friend list from viewers of this profile',
name varchar(255) NOT NULL DEFAULT '' COMMENT '',
pdesc varchar(255) NOT NULL DEFAULT '' COMMENT 'Title or description',
dob varchar(32) NOT NULL DEFAULT '0000-00-00' COMMENT 'Day of birth',
address varchar(255) NOT NULL DEFAULT '' COMMENT '',
locality varchar(255) NOT NULL DEFAULT '' COMMENT '',
region varchar(255) NOT NULL DEFAULT '' COMMENT '',
postal-code varchar(32) NOT NULL DEFAULT '' COMMENT '',
country-name varchar(255) NOT NULL DEFAULT '' COMMENT '',
hometown varchar(255) NOT NULL DEFAU[...]
MySQL said: Documentation
#1214 - The used table type doesn't support FULLTEXT indexes

But it does show an imported structure and tables.

### Friendica version you encountered the problem
2019.03 with database version 1304

### Friendica source (git, zip)
Git

### PHP version
7.1

### SQL version
MySQL 5.5.62

**Comment by Danie10** [comment]
**Expected behavior**
Database to be created without errors

**Actual behavior**
Tried standard install as well GIT CLONE to webserver but I get the error above after linking to the database.
I then went into phpMyAdmin and dropped the tables and imported the database.sql file.

It gives this error after importing:
Error
SQL query:
--
-- TABLE profile
--
CREATE TABLE IF NOT EXISTS `profile` (
	`id` int unsigned NOT NULL auto_increment COMMENT 'sequential ID',
	`uid` mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'Owner User id',
	`profile-name` varchar(255) NOT NULL DEFAULT '' COMMENT 'Name of the profile',
	`is-default` boolean NOT NULL DEFAULT '0' COMMENT 'Mark this profile as default profile',
	`hide-friends` boolean NOT NULL DEFAULT '0' COMMENT 'Hide friend list from viewers of this profile',
	`name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
	`pdesc` varchar(255) NOT NULL DEFAULT '' COMMENT 'Title or description',
	`dob` varchar(32) NOT NULL DEFAULT '0000-00-00' COMMENT 'Day of birth',
	`address` varchar(255) NOT NULL DEFAULT '' COMMENT '',
	`locality` varchar(255) NOT NULL DEFAULT '' COMMENT '',
	`region` varchar(255) NOT NULL DEFAULT '' COMMENT '',
	`postal-code` varchar(32) NOT NULL DEFAULT '' COMMENT '',
	`country-name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
	`hometown` varchar(255) NOT NULL DEFAU[...]
MySQL said: Documentation
#1214 - The used table type doesn't support FULLTEXT indexes

But it does show an imported structure and tables.

**Friendica version you encountered the problem**
2019.03 with database version 1304

**PHP version**
7.1

**SQL version**
MySQL 5.5.62

**Comment by MrPetovan** [comment]
Please update your MySQL version to at least 5.6, Friendica doesn't support MySQL 5.5 and below for this reason.

**Comment by Danie10** [comment]
Thanks, I was working off the online guide at https://forum.friendi.ca/help/Install that still stated requirements:
"Mysql 5.5.3+ or an equivalent alternative for MySQL"
I'll try update though and test again. If it is this, the guide needs an update.

**Comment by Danie10** [comment]
Not sure whether to laugh or cry but thanks v5.6 sorted it out. Spent a full 24 hours battling with it not realising it was that version number.

**Comment by MrPetovan** [comment]
These requirements are easier to update and are consequently more current thant the in-site help: https://friendi.ca/resources/requirements/
