### ISSUE TITLE
Enabling the phpmailer addon does not disable standard emailing

### ISSUE THREAD

**Issue by poVoq** [friendica/friendica#7023]
### Expected behavior
If you switch sending emails through the new phpmailer addon then it should stop sending emails through the regular system

### Actual behavior
Emails are duplicated

### Steps to reproduce the problem
Install Friendica 2019.03 and the new phpmailer addon. Register or do any other activities that triggers an email notification. Get two emails (one often hidden in the Spam folder).

### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
git
### PHP version
7.2.17
### SQL version
MySQL 5.7

@M-arcus @kecalcze

**Comment by M-arcus** [comment]
The first mail happens behind this hook `src/Util/Emailer.php` on line 37, if you have the addon installed:
```
Hook::callAll('emailer_send_prepare', $params);
```

The second mail happens here `src/Util/Emailer.php` on line 94:
```
$res = mail(
	$hookdata['to'],
	$hookdata['subject'],
	$hookdata['body'],
	$hookdata['headers'],
	$hookdata['parameters']
);
```
I couldn't find a native way to stop the `mail()` from executing. 
I would suggest adding a parameter into the `$params` that stops the `mail()` function

**Comment by MrPetovan** [comment]
It's  a very good idea, thank you for the suggestion.

**Comment by kecalcze** [comment]
Is anyone working on this or I can take it?

**Comment by annando** [comment]
@kecalcze feel free! Help is always welcome!

Had you already dome some PR? If not, please have some patience since we have a strict review concerning coding standards. First PRs mostly take their time since there are so many different things to consider.

**Comment by MrPetovan** [comment]
@kecalcze Did you do any work on this or can I tackle it myself?

**Comment by kecalcze** [comment]
Sry I don't have time for it. So it's free to take.

**Comment by MrPetovan** [comment]
No problem, I'll take a stab at it then.

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica/pull/7187 and https://github.com/friendica/friendica-addons/pull/859
