### ISSUE TITLE
Show 4XX errors in theme template

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7047]
Part of #2800

Currently, 404 errors are shown in a black on white page with no navigation. This is a problem for iOS "Add to Home Screen" as there aren't any navigation element provided by the phone itself. And with the recent change where the app isn't refreshed any time it's opened, the app can stay stuck on the barren 404 page for a while.

Unlike critical 500 errors, 4XX errors are manageable on Friendica side and can be rendered in the current theme template including the navigation.

**Comment by annando** [comment]
I would suggest some graphics with these mascot: https://iliketoast.net/posts/cd1ec940ec630136eaa56c626dd55703 - if possible.

**Comment by MrPetovan** [comment]
For now I'm working on a generic page with the error title and a custom message for all the errors, but I guess we can commission a sad bunny for all errors.

**Comment by nupplaphil** [comment]
solved by #7068 ?

**Comment by MrPetovan** [comment]
I received some graphics for the error page that I need to integrate at least in the frio theme: https://gitlab.com/lostinlight/per_aspera_ad_astra/tree/master/friendica-404

So this isn't over just yet.

**Comment by annando** [comment]
@MrPetovan please, please immediately stop everything you are doing and integrate these lovely graphics right now!

**Comment by MrPetovan** [comment]
Unfortunately I can't integrate those graphics as is, they don't account for arbitrary text and custom theme settings. I did my best (which isn't saying much).
