### ISSUE TITLE
Password sent via email.

### ISSUE THREAD

**Issue by tari-alfaro** [friendica/friendica#7051]
You send users' passwords via email. It's a bad security practice because a lot of emails are sent in cleartext. Services like Gmail scrape your emails to do *quick replies* and could be scraping passwords too.

I recommend that you ONLY send a verification link to verify the account. Do not send any links regarding authentication. It's bad.

Also, DO NOT use `mt_*` functions in your code. It is outdated.

https://github.com/friendica/friendica/blob/427a79056fe742beadc4b1a7a2ef18f46e002d7e/src/Model/User.php#L338

This is a bad way to generate a password. Just don't do it. At all. Instead check if a password is compromised via [Troy Hunt's HIBP API.](https://haveibeenpwned.com/) And enforce the user to pick a password during registration.

**NOTE:** OpenSSL is hard to get right. And is only recommended for cryptography experts. [Choose a good, easy to use cryptography library.](https://paragonie.com/blog/2015/11/choosing-right-cryptography-library-for-your-php-project-guide)

**Comment by MrPetovan** [comment]
Ha ha, I'm always happy to see @paragonie being mentioned as it also is my go-to place for PHP cryptography.

Thank for your report, though, unfortunately it is a duplicate of an existing issue that still has to be taken on: #4752

**Comment by tari-alfaro** [comment]
@MrPetovan Ah, alright. Good to know. :)
