### ISSUE TITLE
Feature Request: A Home-Button

### ISSUE THREAD

**Issue by sennewood** [friendica/friendica#708]
If a users surfs to another friendica server he must enter the URL of his server to get back. A button to go back instant would be helpful.

**Comment by Beanow** [comment]
I think this is a UX issue with can test by watching users. If this is still an issue we should look into it imo.

**Comment by rabuzarus** [comment]
I would say this isn't a an issue anymore. We have remote authentication through magic links (dfrn auth or OpenWebAuth). This means on the remote side there will be a home button which brings the user back tho his/her own profile

**Comment by vinzv** [comment]
I think all questions are answered. Can we close this issue?

**Comment by annando** [comment]
I second this.

**Comment by MrPetovan** [comment]
Closiiiiiing.
