### ISSUE TITLE
Groups in contacts can't be selected

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7094]
### Actual behavior
If you select a contact on the `/contact` page or process a contact request, You are not able to select or deselect any of your defined groups. The selection will disappear instantly again.
Tested in vier and Frio

### Steps to reproduce the problem
Go to the `/contact` page 

### Friendica version you encountered the problem
 - Friendica 'Dalmatian Bellflower' 2019.06-dev - 1310
 - git 
 - PHP7.2.15-1
 - mariadb Ver 15.1 Distrib 10.1.37

**Comment by nupplaphil** [comment]
Sounds like a regression because of the new routes from #7065

**Comment by nupplaphil** [comment]
Issue still exists :-/ 
=> verified on my node too

**Comment by nupplaphil** [comment]
fixed with #7107
