### ISSUE TITLE
Missing route /contact/x/updateprofile

### ISSUE THREAD

**Issue by annando** [friendica/friendica#7106]
In the current dev the described route is missing.

**Comment by nupplaphil** [comment]
fixed with #7107

**Comment by annando** [comment]
Sure? The path is "updateprofile" not "update".

**Comment by nupplaphil** [comment]
How dare .. -.-* It's still in my clipboard .. thanks :D

**Comment by annando** [comment]
There is no way to define a route where we only specify the first part and ignore about in the following parts? I' just asking because I guess that this really will lead to a huge amount of possible routes - and to several forgotten ones.

**Comment by nupplaphil** [comment]
hm .. we've to look when we use the data from the routes instead `$a->argc`, if it's easier with a wildcard.
But it's possible, I used it for the help page where we don't know the subpath:
https://github.com/friendica/friendica/blob/20c9d5fe1dfdea55f920a1a53a1d34e4a540a0a4/src/App/Router.php#L130

But one positive aspect of the new routes is that we now really "know" what services we have. Maybe we can create the same type of documentation like for API :-)

**Comment by MrPetovan** [comment]
I agree with @nupplaphil, I prefer to have all available paths explicit, except for the actual variable parts (IDs, GUIDs, nicknames...).

**Comment by tobiasd** [comment]
I see a very long testing phase to find all the routes you have forgotten so far. ;-)

**Comment by nupplaphil** [comment]
Maybe we find therefore some routes we didn't know at all or routes without need ;-)

**Comment by tobiasd** [comment]
Mass unignoring of contacts does not work. Probably other mass actions with contacts as well but I could not test those.

I fear that we will miss some and end up with a broken state.

**Comment by annando** [comment]
We need an appropriate logging. Then people should have a look at it.
