### ISSUE TITLE
Nerdica-issued password not working

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#7121]
### Expected behavior
I should be able to login with new password issued by Nerdica.net

### Actual behavior
Failed to login with issued password emailed to me

### Steps to reproduce the problem
reset password
try to login with issued password

### Friendica version you encountered the problem

see `example.com/friendica` on your Friendica node for the version information.

**Comment by MrPetovan** [comment]
As this is a node-specific issue, please contact your node admin first. In the case of Nerdica, you need to contact [Ingo Jürgensmann](https://nerdica.net/profile/ij).
