### ISSUE TITLE
Frio - open link in a new tab

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#7123]
(hope it is not a duplicate, I've not found it)

### Actual behavior
I have the Frio theme enabled. When I click on a link embeded in a post. The links open in the current tab. If I do the same with Vier theme link opens in a different tab.
 
### Expected behavior
When I click it opens it in a new tab. Or make this feature optional with a settings.

### Friendica version you encountered the problem
2019.03

**Comment by MrPetovan** [comment]
This is a design decision, or rather a design non-decision. We kept the default browser behavior for links, leaving users in charge of deciding if they want to open most links in a different tab or not. Of course this isn't true for third-party widgets (like Twitter and Youtube) that may have their own link policy.

**Comment by nupplaphil** [comment]
As a workaround, you can click with the mousewheel, which automatically open it in a new tab :)

**Comment by MrPetovan** [comment]
Or `Ctrl + Click` on Windows or `Command + Click` on Mac.

**Comment by AlfredSK** [comment]
I have an Android phone. Where do I find that mousewheel thingy? ;-)

**Comment by MrPetovan** [comment]
On iOS: Press long on a link, then "Open in a new tab" in the pop up menu. I'm unfamiliar with android controls.

**Comment by valvin1** [comment]
I have tested deeper and I notice that with Firefox I have different behaviour. 
If the friendica tab is pinned all links open in a new tab. (looks to be a good alternative)
If it is not pinned not formatted links (links detected by the browser) open in a new tab but it is not the case for link preview which was the reason I open this issue. 
It looks like the behaviour is not similar depending the kind of the link.

**Comment by valvin1** [comment]
as it is a whished feature and i've a good workaround I close the issue.
