### ISSUE TITLE
First time setup hangs on last screen

### ISSUE THREAD

**Issue by tellmewho** [friendica/friendica#7132]
### Expected behavior
That setup is finished and the new instance of friendica can be accessed.

### Actual behavior
After clicking on "Send" on the last side (Admin-mail, location & language) the page keeps loading for ages before giving up with a "Internal Server Error" after ~10min.

### Steps to reproduce the problem
Opening https://new.friendica.node/install and providing all requested information...

### Friendica version you encountered the problem
This happens on all friendica versions I tried (3.5 to 2019.04)

### Friendica source (git, zip)
.zip

### PHP version
7.2
### SQL version
MariaDB 10.3

After some investigation I suspect the problem to be `sql_mode` being set to `STRICT_TRANS_TABLES`  . If so, maybe add an errormessage about it, have it in the system requirements (since it is mySQL default since Version 5.7)

In case this is the problem: is there a workaroung (if one is not able to change the setting)?

**Comment by MrPetovan** [comment]
Paging @nupplaphil for command-line install recommendation.

**Comment by nupplaphil** [comment]
I don't think that the sql_mode is the reason for it. I checked it before I stepped through the install wizzard and the output is:
```sql
mysql> SELECT @@GLOBAL.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

You can install it without wizard with the command-line:
```console
root@friendica:/var/www/friendica# php bin/console.php autoinstall -U https://new.friendica.node -s -H ${DBHOST} -d ${DBNAME} -U ${DBUSER} -P ${DBPASS}
```
Please attach the output of this command in case it doesn't work.

**Comment by tellmewho** [comment]
Hi,
thanks for your answer. Unfortunately I don't have command-line access :( 
Any other way? I tried before to import "friendica_test_data.sql", but had strange errors (like missing send buttons) and thought it might be due to incompatible db-structure...

**Comment by MrPetovan** [comment]
Yeah, the test data isn't suited for running a production node.

**Comment by nupplaphil** [comment]
@tellmewho can you try it localy? e.g. inside a [LAMP](https://en.wikipedia.org/wiki/LAMP_(software_bundle)#External_links) environment? Just to be sure it works.

**Comment by nupplaphil** [comment]
@tellmewho did it work? Do you need support? :)

**Comment by tellmewho** [comment]
Sorry, never managed to set up a test environment. Now I changed the hoster and everything works! Thanks for you help anyway!
