### ISSUE TITLE
Feature Request: "classic Forum concept in friendica" 

### ISSUE THREAD

**Issue by superfirefox** [friendica/friendica#715]
Friendica is super, 
but there is one thing that is missing: it's missing  a built in forum with admin panel, or (instead) some kind of integration with phpbb3 forums.

There is no way to make threads that only some users can watch, and no way to play with the permissions (like in a phpbb3 forum).

Soon or later forums will die, a social networks that has a forum function is the future.

thx
Adel

**Comment by vinzv** [comment]
I think this idea is beyond Friendica's scope and purpose. Building something full-flavored like phpbb upon Friendica would be just over the top, imho. Can we close this issue?

**Comment by MrPetovan** [comment]
Agreed.
