### ISSUE TITLE
Saved Folder with commas in name doesn't work!

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#7171]
Reported by Garry Knight (https://forum.friendi.ca/display/c443a55c-155c-c9e2-dc0b-aa4826352853)

> I think I might have found a bug. I have a number of Saved Folders for bookmarking posts. One of them has the name "Science, Medicine, Health". When I save a post and the list of Saved Folders comes up for me to select from, I notice that this folder seems to be represented as three folders, one called "Science", one called "Medicine", and one called "Health".
>
> Thinking this to simply be an aberration, I've been clicking on the word "Science", thinking that I'm selecting the correct Saved Folder. But when I click on the name in the Saved Folders list, only one post shows up. It appears that all of the others have been lost.
>
> This is easy to replicate: simply create a Saved Folder with the above name, then try to save posts to it using the Save to Folder item in the post's drop-down menu, then use the drop-down list of folders to try to select the correct one.
> 
> I'm now wondering whether any other Saved Folders with more than one word in the name are working properly. I'll experiment and report back.

**Comment by MrPetovan** [comment]
Fixed by #7199
