### ISSUE TITLE
Manually adding the #NSFW tag to an item should trigger the nsfw filter

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7176]
Currently, only posts that were published with the #NSFW tag will be collapsed by the addon, but manually adding the tag to an existing post won't make the addon collapse the post.

**Comment by tobiasd** [comment]
That's a regression than as this was the initial functionality for the "add tag" feature. Somebody posted something that should have been tagged with NSFW initially.

**Comment by MrPetovan** [comment]
I tested again today, it worked as expected.
