### ISSUE TITLE
Additional feature "Archives" not working on profile page

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7183]
### Expected behavior
The additional feature "Archives" should work on the personal profile (home) page just like on the network page.

### Actual behavior
It doesn't. I get a cute 404 when I click on a month in the Archives widget when I'm on my profile/home page. It works on the network page but not on the personal profile page.

### Steps to reproduce the problem
Enable the additional feature "Archives". Go to your profile page (.../profile/$nickname) and click on a month in the Archives widget.

Discussion: https://forum.friendi.ca/display/0b6b25a8-125c-e421-cf77-8e9741811040

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.17

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
Is this resolved?

**Comment by AlfredSK** [comment]
Yes, it works. Closing...
