### ISSUE TITLE
I can't register to Friendica network

### ISSUE THREAD

**Issue by word20** [friendica/friendica#7188]
I visited Nerdica.net server and I can't register. The capcha result is not accepted
What is the reason ?

**Comment by MrPetovan** [comment]
Hi, I reached out to Nerdica.net administrator, hopefully he will be able to answer this node-specific question.

You can also choose from other public servers to register on the Friendica network and still connect with Nerdica.net accounts: https://dir.friendica.social/servers

**Comment by ingoj** [comment]
Ah, already wondered why there are no new users in the past days... 

I deactivated mathcaptcha addon. Maybe Tobias needs to check as well...

**Comment by MrPetovan** [comment]
Thanks for your reactivity!

@word20 Please close this issue if you're able to register on Nerdica.net or any other Friendica node.
