### ISSUE TITLE
Replace defaults() with ??

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7190]
PHP 7.0 introduced the coalescing operator `??` that doesn't choke on non-set variables and inexistant array keys. The `defaults()` function had been created to emulate its behavior. Since Friendica's hard minimum version is now PHP 7.0, we can replace it with the language construct.

**Technical note 1**: `defaults()` isn't exactly the same as `??`. The main difference is that `??` doesn't fall back to the default value (defined on the right of the operator) if the checked value exists and is falsy.

**Technical note 2**: As a function call, `defaults()` will be resolved on its own before any other operator. In most cases involving `??` and another operator, parentheses are warranted to avoid nasty side-effects. Example of counter-intuitive and hazardous operator combination:
- `$foo ?? $bar . $baz`
- `$foo . $bar ?? $baz`
- `$foo ?? $bar == $baz`
- `$foo == $bar ?? $baz`
- `$foo ?? $bar == $baz ?? $qux`

**Comment by annando** [comment]
It seems as if ```defaults(...)``` still is better, since we can set a default value?

**Comment by MrPetovan** [comment]
The only point of `??` is to provide a default value (on the right) if the tested variable (on the left) is `null` or not set without emitting a notice (like `?:` does).

`defaults()` also returns the default for falsy values, which makes it combine `??` and `?:` in a single function call. However we don't always need both features, which means we can convert many `defaults()` calls to `??`.

**Comment by MrPetovan** [comment]
Addons PR: https://github.com/friendica/friendica-addons/pull/899

**Comment by MrPetovan** [comment]
Don't forget https://github.com/friendica/friendica-addons/pull/899 !
