### ISSUE TITLE
Missing themed error page or login page for /admin

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7209]
### Expected behavior
When I'm not logged in and I go to example.com/admin I should get a themed error page (403) and the possibility to log in.

### Actual behavior
I get an all white, blank page instead.

### Steps to reproduce the problem
Log out. Go to example.com/admin.

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.17

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment]
Fixed by #7211
