### ISSUE TITLE
Possible regression 2FA & host-meta & single-user-mode

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#7217]
### Expected behavior

https://friendica.philipp.info/.well-known/host-meta should return the valid XML

### Actual behavior

It automatically redirects me to the network page.
When I insert a `print_r($this->module_class);` here
https://github.com/friendica/friendica/blob/develop/src/App.php#L1158
it prints `Friendica\Module\TwoFactor\Verify`

=> plz can somebody verify it, I recently recovered from a fatal crash, so I don't want to make noise in case it's just on my node ;-)
=> Maybe it's just a problem with single user mode

### Steps to reproduce the problem

- enable 2fa
- logout / use another client and goto `http://{domain}/.well-known/host-meta`

### Friendica version you encountered the problem

2019.06-rc

### Friendica source (git, zip)

git

**Comment by AlfredSK** [comment]
Cannot confirm. host-meta is showing the XML. No redirection.

**Comment by nupplaphil** [comment]
Do you have a "single user mode" node too to check? I cannot confirm it on opensocial.at too, but friendica.philipp.info has this issue, even with the latest update

**Comment by AlfredSK** [comment]
No. Sorry. No single user mode node at hand.

**Comment by MrPetovan** [comment]
I'll check on my own node.

**Comment by MrPetovan** [comment]
I can't reproduce this after logging out, nor in a new window.

**Comment by nupplaphil** [comment]
Do you see my https://friendica.philipp.info/.well-known/host-meta ?

**Comment by MrPetovan** [comment]
Plain and clear.

**Comment by nupplaphil** [comment]
OK ... weird ... maybe a wrong redirect which inside my VPN connection
=> nevermind
