### ISSUE TITLE
Don't send hashtags as links over ActivityPub

### ISSUE THREAD

**Issue by GidiKroon** [friendica/friendica#7222]
### Expected behavior

When you post something with a hashtag in the text, I expect this text to be delivered to the recipients as pure text (a # followed by the characters of the hashtag) so that the behaviour of the recipient's service can decide what to do with clicks on these hashtags.

### Actual behavior

It seems that when a post contains a hashtag on Friendica, it is either stored or displayed with an internal hyperlink to the search page (e.g https : // social.isurf.ca / search?tag=HashTag).

When a post is delivered to Twitter, Tumblr, SocialHome, the behaviour is as expected and the internal link behind the hashtag in Friendica is removed.

When a post is delivered to Mastodon over ActivityPub, the internal Friendica link remains in the post (note that Mastodon doesn't support rich text but it does support hyperlinks). However, when clicking on the hashtag, the Mastodon UI intercepts the link and does its own hashtag thing.

If the hashtag in the post occurs before any other url, the preview card for the hashtag in Friendica is (sometimes) shown instead of the preview card of any actually shared url. This is confusing and probably unintended.

When a post is received on Pleroma over ActivityPub, the internal Friendica link also remains in the post and when you click the hashtag, you are taken to Friendica.

(to be honest I don't know what is or should be in the tag field. I guess for the above I am talking about the content field, but I'm just observing this behaviour from a user's perspective)

### Steps to reproduce the problem

Create a post and select recipients on Pleroma and/or Mastodon. Receive the post there and notice while hovering over the hashtag that it is a Friendica link. Click the hashtag on Pleroma and notice you are taken to the Friendica instance.

### Friendica version you encountered the problem

2019.06-rc and earlier on social.isurf.ca

_thanks for your attention_

**Comment by MrPetovan** [comment]
Thank you for your detailed report!

**Comment by annando** [comment]
Do you know how these systems are acting?

**Comment by GidiKroon** [comment]
From a user's perspective it looks like these systems (Mastodon, Pleroma, Pixelfed) are sending a plain hashtag without hyperlink to their site and when such a message is recieved on Friendica it is displayed as a Friendica search link.

**Comment by guzzisti** [comment]
I had a look how federation between mastodon instances handles the tags and it seems, that even between them tags are linked to searches on the remote instance.

Watching the (public) timeline of a user on mastodon.social (e.g. https://mastodon.social/@Azt3c). The user boosted a toot from a user of mastodon.cloud which included hashtags. The hashtags link to searches on mastodon.cloud, not mastodon.social.
It's no difference if i'm logged in with my mastodon.social account or not.

Speaking as a user, i'm not sure which behaviour i'd tend to prefer.

**Comment by annando** [comment]
I tested with Mastodon and Pleroma. Both are creating links to their specific hosts, but clicking on the links will end up in a local hashtag search on that system. The same happens with Friendica posts. In fact I don't see any difference in behaviour between posts from Friendica, Mastodon or Pleroma.

**Comment by GidiKroon** [comment]
Interesting, seems like Mastodon is acting differently on public pages than for logged in users in the web app. Anyway, I guess what I was concerned about was mainly this:

![20190708_211056](https://user-images.githubusercontent.com/4947306/60836777-bc85e980-a1c6-11e9-8c43-549e277c36ef.jpg)
![20190708_211125](https://user-images.githubusercontent.com/4947306/60836814-d32c4080-a1c6-11e9-9a60-8802f23e4540.jpg)

First is on Mastodon, second is on Pleroma. In the second the effect is more subtle, but on the first it seems to me there's a hyperlink which isn't there in the post from Pleroma. The hyperlink triggers the preview card. (On Mastodon and Pleroma preview cards seem to be the responsibility of the viewing application rather than the sending system; I guess I don't have preview cards turned on on Pleroma)

**Comment by annando** [comment]
Okay, that preview thingy is weird.

**Comment by tobiasd** [comment]
There used to be a configuration setting for the admin to _enforce_ the link to the local search for the tag on postings or to not enforce that link back.

**Comment by fedione** [comment]
Any news about this topic?

**Comment by annando** [comment]
We are doing not so different from what other systems are doing it. One had to look from the Mastdon/Pleroma side if this is now looking okay.

**Comment by GidiKroon** [comment]
It has not changed. It's still like in my screenshot. It isn't like that from other systems. It could maybe be because the # symbol is not included in the link text?

**Comment by fedione** [comment]
I can confirm that 

> It has not changed.

Hashtags are still linking to Friendica.

**Comment by fedione** [comment]
Screenshot:

![Fedi One](https://user-images.githubusercontent.com/55923612/66294034-4b9abe80-e8e8-11e9-838c-ada1952b9bf3.png)

**Comment by GidiKroon** [comment]
Something has changed now, on social.isurf.ca (12-rc) within the last five days. When you use hashtags and receive the post on Mastodon, no preview is shown anymore (good). However, the hashtag also doesn't work anymore. You can click on the hashtag in your post as received by Mastodon, which brings you to the list of posts in your Mastodon instance that have that hashtag, but your post is not in the list.

I feel it has something to do with the fact that in Mastodon the # seems to be part of the hashtag, while on Friendica it is not.

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by annando** [comment]
I just tested it with my test account on mastodon.social. Partly it works. I had one hash tag that reliably showed up. For another one there hadn't been any result. And for a third one not the original post, but some other Friendica post appeared.

For me it seems more like some Mastodon issue.

**Comment by annando** [comment]
In one of the last versions we finally fixed this issue. I think that we can close it.

**Comment by GidiKroon** [comment]
Yes, it works correctly now, thanks!

Tested Mastodon and Pleroma: the hashtags are not sent as links so there's no preview (good) and when clicking them on Mastodon you get the posts known to that Mastodon server as is normal for Mastodon (good). When clicking a Friendica originated hashtag in Pleroma, it links to the tag search in Friendica, which is also ok since Pleroma doesn't recognise Friendica's hashtag format.

Thanks again, closing the issue.
