### ISSUE TITLE
Don't strip hyperlinks over ActivityPub

### ISSUE THREAD

**Issue by GidiKroon** [friendica/friendica#7223]
This is an enhancement request, not a bug.

### Expected behavior

If you enter a url in a post in Friendica, the post will contain a hyperlink to that url. The link text may be different from the url. When this post is published to e.g. Twitter, the hyperlink is deconstructed and a plain text version with the link text and the url is sent. That's ok, because Twitter doesn't support hyperlinks.

When publishing this post over ActivityPub, to e.g. Mastodon or Pleroma, I do expect the hyperlink to remain as-is in the content, since both support hyperlinks.

### Actual behavior

When the post is sent to Mastodon or Pleroma over ActivityPub, the hyperlink is deconstructed into the link text and url and sent as plain text anyway. At least, that is how it appears to the receiving user.

### Steps to reproduce the problem

Create a post on Friendica with a url and a link text that differs from the url. Target a user on Mastodon or Pleroma. As the receiving user, see that the link text is placed before the url.

Optionally create a similar post on Pleroma with a hyperlink. Target a user on Mastodon. See as the receiving user that you have received a post where the link text is clickable and takes you to the url.

### Friendica version you encountered the problem

2019.06-rc or earlier on social.isurf.ca

_thanks for your attention_

**Comment by MrPetovan** [comment]
Thank you for the detailed report!

**Comment by annando** [comment]
It is to be tested if this does work with these systems. Especially Mastodon is very picky concerning the interpreted HTML.

**Comment by GidiKroon** [comment]
Here is a public post from Pleroma containing a hyperlink: https://pleroma.gidikroon.eu/objects/c32c1bf7-3656-4c3a-b640-fa1e9a419c92
Here is how it is received on Mastodon, with the hyperlink and link text, without url in the text: 
![20190603_230344](https://user-images.githubusercontent.com/4947306/58834815-9368bb00-8654-11e9-9e62-e6c643a9f756.jpg)
Another example: https://pleroma.gidikroon.eu/objects/ce730c20-f8b6-4a96-8015-b0232b75471f, which arrives fine on Mastodon.

**Comment by MrPetovan** [comment]
Fixed by #7255
