### ISSUE TITLE
[frio] Profile sidebar message button issues

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7226]
In the profile sidebar, the "Message" button doesn't appear for profiles that are supposed to accept them (Diaspora and DFRN).

Furthermore, when clicking on the button remotely connected, the Ajax call to `/wallmessage/[nickname]` fails with a 403 error.

**Comment by annando** [comment]
It should be available for AP as well.

**Comment by MrPetovan** [comment]
It doesn't even appear in the contact list or the hovercard for AP contacts, which makes it consistent with the sidebar 🙃

What is the prevailing rule?

**Comment by annando** [comment]
The rule is that these messages do work now for AP as well - but we haven't made the required changes in the frontend to respect this. Means: Please add AP everywhere where it comes to direct messages.

**Comment by MrPetovan** [comment]
AP all software? Mastodon and Pleroma too?

**Comment by annando** [comment]
Yep.

**Comment by MrPetovan** [comment]
This is a duplicate of #6410
