### ISSUE TITLE
Defective profile/user names with some Diaspora pods

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7235]
### Expected behavior
A user/profile name should always be displayed as full name.

### Actual behavior
There are some servers with probably weird configs that show the profile/user URL instead. And sometimes they show weird characters instead of the user names.

### Steps to reproduce the problem
I've seen this only with Diaspora pods. They seem to be hosted on a URL like www.example.com but the user profiles have webfinger addresses like user@example.com (w/o the www).

Is this just a bad config on the remote side or do we have to do something on our side to show these user names correctly?

Examples:
https://www.datataffel.dk
https://www.iitians.xyz
https://www.fessebouc.fr

A post:
![Bildschirmfoto von 2019-06-04 20-02-22](https://user-images.githubusercontent.com/3656054/59147468-455d0a00-89fc-11e9-8b56-0bdc58997d7d.png)

A reshare:
![Bildschirmfoto von 2019-06-08 14-37-58](https://user-images.githubusercontent.com/3656054/59147480-5279f900-89fc-11e9-817b-a519a534fcad.png)

Another post:
![Bildschirmfoto von 2019-06-02 17-32-27](https://user-images.githubusercontent.com/3656054/59147487-632a6f00-89fc-11e9-9318-7199ace365cd.png)

**Negative probe (with www):**
`mads_aggerholm@www.datataffel.dk`
```
Array
(
    [name] => mads_aggerholm@www.datataffel.dk
    [nick] => mads_aggerholm@www.datataffel.dk
    [guid] => 
    [url] => mads_aggerholm@www.datataffel.dk
    [addr] => 
    [alias] => 
    [photo] => https://libranet.de/images/person-300.jpg
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [poco] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [baseurl] => https://www.datataffel.dk
)
```

**Positive probe (w/o www):**
`mads_aggerholm@datataffel.dk`
```
Array
(
    [name] => Mads Aggerholm
    [nick] => mads_aggerholm
    [guid] => 803091206131013764fb14dae9ef692e
    [url] => https://www.datataffel.dk/u/mads_aggerholm
    [addr] => mads_aggerholm@datataffel.dk
    [alias] => 
    [photo] => https://www.datataffel.dk/assets/user/default-2c878d1cd0171726fc490add065f342be5a959729df46a89807a4c18a8fc8d14.png
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [batch] => https://www.datataffel.dk/receive/public
    [notify] => https://www.datataffel.dk/receive/users/803091206131013764fb14dae9ef692e
    [poll] => https://www.datataffel.dk/public/mads_aggerholm.atom
    [request] => 
    [confirm] => 
    [poco] => 
    [priority] => 0
    [network] => dspr
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArmhkWu3TjYQARDCOf9Rw
ymqrar8Itmq0eaB7gaJL5FSAHvF2EabG/10ztmxIAXtxLE0zetuOp3px+485dYjU
19WbtMj5jGSZxIX5MnROdNn+pwuJpUkYYoZZEyr3EVFnpXIP3jt8GYSBTOj9+EbD
x9/xJIDFIwEtTsRFMw9wJOYQFG6sZJ3MDZ/lNIRBIYYk9RjEecUapiRQSnrp5mWH
NjEyKraG37JHlyNFIv/ARK1XpIRurAMjtlma/RfieH92yqdCK8EcEo4g8Mk64Js3
O6HrtjrcJbyah8QqAHf+SXyMlN/p6FZX14ImF6ub2zd+pFODphIt0Z3xia6TMFwS
BfuvBDIO5bPR8ZGyn/22lyVnlAjnxQm1//kzOHX7Txmii2iAJR7YYTMBYWBokT8C
8fSIugYccEKEbCJiqfx+9lzuB77YJdjQYrYNlnxONi6wBrlJj+CXZraiwL2pKBHi
3UXHnamtZL+dBsKr1gygJZGLkaQ2lvonJ+6Oc1Fq2qwh9YaJPjWJx6PHdx5C+LHv
1SpdyQRqf5s8DzjpWbNFrtc07y1dEQ74CTy9AW4oBKCTVUvzJBq1I2gON6aCvMXm
8JeSs4B4MKVt1JkYUthrbPIvKcFB5jSnmgT30v7cMjmMDMM3sAb/UuRS7BuH/PpZ
OubrdtXFH5pPnHmWUinhyJkCAwEAAQ==
-----END PUBLIC KEY-----

    [baseurl] => https://datataffel.dk
)
```

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
10.1.40 MariaDB

**Comment by AlfredSK** [comment]
Discussion: https://forum.friendi.ca/display/0b6b25a8-395c-e980-c870-b00788196100

**Comment by nupplaphil** [comment]
I do notice a lot of similar warnings too..

**Comment by AlfredSK** [comment]
We should really have a look at this because this is a bad UX when users see those mangled up user names.

I get a lot of errors (404) in my log like this one:
```
https://www.datataffel.dk/.well-known/webfinger.xml?resource=makitbigg%40www.datataffel.dk: 404
```

As you can see it tries to get data from the resource `makeitbigg`@**www**.`datataffel.dk`. 

But because the user address is actually `makeitbigg@datataffel.dk` you get the error 'not found' (404).

Conclusion:
If this setup is officially supported by Diaspora - having your node at https://www.domain.tld but your user handles w/o 'www' like user@domain.tld - we should support that and fix it on our side.
If this is an unsupported, weird configuration these pods are using, I tend to block communication with them because it looks very ugly and give users the impression that this is some Friendica bug.

**Comment by MrPetovan** [comment]
Neither of those URLs work:
- https://datataffel.dk/.well-known/webfinger.xml?resource=makeitbigg%40datataffel.dk
- https://datataffel.dk/.well-known/webfinger.xml?resource=acct:makeitbigg%40www.datataffel.dk
- https://datataffel.dk/.well-known/webfinger.xml?resource=makeitbigg%40datataffel.dk
- https://datataffel.dk/.well-known/webfinger.xml?resource=acct:makeitbigg%40www.datataffel.dk
- https://www.datataffel.dk/.well-known/webfinger.xml?resource=makeitbigg%40datataffel.dk
- https://www.datataffel.dk/.well-known/webfinger.xml?resource=acct:makeitbigg%40ww.datataffel.dk
- https://www.datataffel.dk/.well-known/webfinger.xml?resource=makeitbigg%40datataffel.dk
- https://www.datataffel.dk/.well-known/webfinger.xml?resource=acct:makeitbigg%40ww.datataffel.dk

However, both https://datataffel.dk/.well-known/host-meta and https://www.datataffel.dk/.well-known/host-meta returns this:
```
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Link rel="lrdd" type="application/xrd+xml" template="https://www.datataffel.dk/.well-known/webfinger.xml?resource={uri}"/>
</XRD>
```
So it isn't a problem related to the presence (or absence) of `www.` in the domain name. They publish an endpoint that doesn't exist at all. Unfortunately we are using that endpoint to probe new contacts because we aren't bound to a specific protocol that could simply ignore this meta endpoint.

Nothing we can do on our end to guess their network with such a misleading setup. The best would be to contact the admin of this pod to let them know their setup is broken for other software than Diaspora.

**Comment by MrPetovan** [comment]
- No specific problem probing for `redj@fessebouc.fr`, updating the contact is likely to fix further display issues. The share box name display issue might be something else, like a misplaced quote.

**Comment by AlfredSK** [comment]
Thank you for looking at that and for the explanation. I guess I can close the issue then...

**Comment by annando** [comment]
I had a look at it as well. It looks really weird. I want to ask at Diaspora as well.

**Comment by AlfredSK** [comment]
OK. So I keep it open until we have some additional information.

**Comment by annando** [comment]
According to my sources the redirect should be the opposite way. I'm not totally sure though, why the display looks that way.

**Comment by AlfredSK** [comment]
Since a couple of days I don't see those "URL-names" anymore. Most likely the names have been repaired by the contact update or something else has changed in the meantime. Let's see...

**Comment by annando** [comment]
You are on "develop" aren't you? This branch now has some automatic contact repair/update mechanism.

**Comment by AlfredSK** [comment]
Yes. I'm on develop. Thank you for the explanation.
