### ISSUE TITLE
Upgrade to 2019.03 results in redirect to 404

### ISSUE THREAD

**Issue by strk** [friendica/friendica#7236]
I've upgraded (git pull && bin/composer.phar install) to 5ca279478eb6dd06b698e8c050ea1315c404a454 and since then going to `/` redirects me to `/profile/strk` which is a 404.

### PHP version

7.0

### SQL version

what version do you want to read here ?

**Comment by nupplaphil** [comment]
You mean upgrade to 2019.04, don't you?

Are there any errors/hints in the log? I assume you're running a single mode instance, are you?

**Comment by strk** [comment]
Probably 2019.04, yes. Cannot find logs, `grep -i log .htconfig.php` yelds no results

**Comment by AlfredSK** [comment]
There is no such thing as .htconfig.php anymore. The site config is located in the .../config folder now.

**Comment by annando** [comment]
Are you using Apache or nginx?

**Comment by strk** [comment]
Apache

**Comment by annando** [comment]
Please have a look if you do have the file ```.htaccess```. If not, then copy it from ```.htaccess-dist```

**Comment by strk** [comment]
Doin gthe copy of `.htaccess-dist` to `.htaccess` fixed the issue here, thanks
