### ISSUE TITLE
Private message replies received from ActivityPub aren't displayed

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7240]
Related to #7226

I tried sending a private message to a Pleroma account and a Mastodon account., I know it arrived because the remote users replied to me. I know they replied to me because I received an email notification for them. However, the replies themselves isn't displayed in the private conversation the notification emails point to, I can only see my own initial message.

The email notifications explicitly mention "private message" and both notification links redirect to `message/0`.

**Comment by annando** [comment]
It does work here, both with Mastodon and Pleroma.

**Comment by MrPetovan** [comment]
The replies show up in the private message thread?

**Comment by MrPetovan** [comment]
Additional evidence: https://forum.friendi.ca/display/7f2cc12a-205d-000b-3134-d82422360834

**Comment by annando** [comment]
I realize that there is a problem, sadly I cannot reproduce it.

**Comment by MrPetovan** [comment]
Here's the issue:
```
2019-06-13 00:45:38 index [ERROR]: DB Error {"code":1292,"error":"Incorrect datetime value: '2019-06-13T00:45:36Z' for column `friendica_dev`.`mail`.`created` at row 1","callstack":"DBA::insert, Mail::insert, Processor::postMail, Processor::postItem, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent"
```
I don't know why your DBMS accepts `2019-06-13T00:45:36Z` in a `datetime` column, but MariaDB 10.3.15 sure doesn't.

**Comment by MrPetovan** [comment]
Fixed by #7259

**Comment by annando** [comment]
I guess you can close this now?

**Comment by MrPetovan** [comment]
Yup!
