### ISSUE TITLE
Can't edit own post that is older than 1 month

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7252]
### Expected behavior
Able to edit own posts as long they exist on my home node.
The automatic deletion of my posts is set to 90 days aka 3 months.

### Actual behavior
Can't edit those posts like
https://horche.demkontinuum.de/display/2196d4ee-105c-c606-6852-c41439489978
![00_temp](https://user-images.githubusercontent.com/24474762/59253609-e7643880-8c2e-11e9-88c1-acb4b4ff7980.jpg)

### Steps to reproduce the problem
Search and try to edit post.

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.06-rc - 1313 / git / PHP7.2.15-1 / mariadb Ver 15.1 Distrib 10.1.37

**Comment by MrPetovan** [comment]
The conditions for the edit link to appear are:
- You must be logged in.
- You own contact URL must be the same as the `author-link` field of the item.
- The item `uid` field must not be 0.

What is the page you're viewing this post from? If it's a display/search/community page, it's possible that you're seeing the public `uid = 0` version of your post and that you can't edit it for this reason.

Can you please look into your `item` table for `guid = 2196d4ee-105c-c606-6852-c41439489978` and check if there's any row with `uid != 0`?

**Comment by hoergen** [comment]
As i mentioned above im looking logged in on the url https://horche.demkontinuum.de/display/2196d4ee-105c-c606-6852-c41439489978 

It's my post and i should be able to edit it.?

This is the DB search in item table for that guid

![00_temp1](https://user-images.githubusercontent.com/24474762/59290328-d1bf3500-8c67-11e9-9572-d5d815eb75e9.png)

**Comment by MrPetovan** [comment]
I'm not saying you did anything wrong, I'm just stating the conditions as they are written in the code, and none of them include a time condition, so it has to be some other issue, probably related to the `uid = 0`.

But it definitely is an issue, you absolutely should be able to edit your own posts. Your table rows looks right assuming you're `uid=1` on your own node. So it is something else.

Can you please temporarily add a `var_dump($item);` in `mod/display.php` on line 82 and report back the display of this particular post? You can remove the line as soon as you successfully reloaded the page.

**Comment by hoergen** [comment]
I get the  following

`array(6) { ["id"]=> int(3311327) ["uid"]=> int(0) ["parent"]=> int(3311327) ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" ["author-id"]=> int(2) ["body"]=> string(801) "Das sieht ja mal gar nicht gut aus ... [b]ran The Countdown to War Has Started... Here's Why[/b] Is it likely that we are getting closer to another terrible war? Or has it already started? What could this mean for the major markets? We look at the charts and the facts. https://www.youtube.com/watch?v=HCBXYnhZLEo #[url=https://horche.demkontinuum.de/search?tag=Krieg]Krieg[/url] #[url=https://horche.demkontinuum.de/search?tag=MittlererOsten]MittlererOsten[/url] #[url=https://horche.demkontinuum.de/search?tag=Iran]Iran[/url] #[url=https://horche.demkontinuum.de/search?tag=USA]USA[/url] #[url=https://horche.demkontinuum.de/search?tag=Öl]Öl[/url] #[url=https://horche.demkontinuum.de/search?tag=Terror]Terror[/url] #[url=https://horche.demkontinuum.de/search?tag=TerrorÖl]TerrorÖl[/url]" } `

**Comment by MrPetovan** [comment]
So you are getting the `uid=0` item against all odds, which is what prevents you from being able to edit it.

Next debug attempt, can you please insert a `var_dump(__LINE__);` on:
- line 47
- then line 52
- then line 59
- then line 72
- then line 76
- then line 98

Reload the page, copy the output and remove the added lines?

**Comment by hoergen** [comment]
I assume it is the same file  `mod/display.php` , but I'm not sure if you mean insert above those lines or below those lines?

**Comment by MrPetovan** [comment]
Yes, in the same file, and you should insert the line above those lines. Each line number takes into account the fact that the inserted debug lines add more lines to the file.

**Comment by annando** [comment]
Please check if some item lines could be deleted.

**Comment by hoergen** [comment]
Ok result is

`int(47) int(53) int(103) `

**Comment by hoergen** [comment]
> Please check if some item lines could be deleted.

You mean in the database?

**Comment by MrPetovan** [comment]
Yes, please check the `deleted` field for all the rows with the same guid.

**Comment by MrPetovan** [comment]
> Ok result is
> 
> `int(47) int(53) int(103) `

This doesn't look right, I don't have any debug output on either line 53 or 103. Can you please paste your display.php `init()` method with the added debug?

**Comment by hoergen** [comment]
Ok, maybe we have a logical problem. Did you count the lines with the changes or without the changes? Because I was starting with 98 and changing down to 47 to preserve the correct lines, you asked me for. 
If you put the changes already in your request, then I put the changes in the wrong lines ;)

**Comment by MrPetovan** [comment]
I went the natural way, from top to bottom, and added that "Each line number takes into account the fact that the inserted debug lines add more lines to the file."

**Comment by hoergen** [comment]
ah ok .. so i'll do that again

**Comment by hoergen** [comment]
so the result this time
`int(47) int(52) int(72) `

I don't know how to
`Can you please paste your display.php init() method with the added debug?`

**Comment by MrPetovan** [comment]
Never mind, it's enough, thanks. 

So it tries to find the item with `uid=1` (that you can edit) on line 52, but can't get it for some reason, and then defaults back to the public item in line 72.

Can you please add a `var_dump($sql, $condition);` in `src/Model/Item.php` on line 407?

**Comment by hoergen** [comment]
This is the output

`string(1647) "SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`guid`, `item`.`author-id`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid`, `item-content`.`body` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 LEFT JOIN `item-content` ON `item-content`.`uri-id` = `item`.`uri-id` WHERE (`item`.`guid` = ? AND `item`.`uid` = ?) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(2) { ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" ["uid"]=> int(1) } string(1678) "SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`guid`, `item`.`author-id`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid`, `item-content`.`body` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 LEFT JOIN `item-content` ON `item-content`.`uri-id` = `item`.`uri-id` WHERE (`item`.`guid` = ? AND `item`.`private` IN (?, ?) AND `item`.`uid` = ?) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(4) { ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" [0]=> int(0) [1]=> int(2) ["uid"]=> int(0) } string(1540) "SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`parent-uri`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 WHERE (`item`.`guid` = ? AND `item`.`uid` = ?) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(2) { ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" ["uid"]=> int(1) } string(1571) "SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`parent-uri`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 WHERE (`item`.`private` IN (?, ?) AND `item`.`guid` = ? AND `item`.`uid` = ?) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(4) { [0]=> int(0) [1]=> int(2) ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" ["uid"]=> int(0) } string(233) "SELECT `item`.`id`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` WHERE (`item`.`id` = ? AND `item`.`private` IN (?, ?)) LIMIT 1" array(3) { ["id"]=> int(3311327) [0]=> int(0) [1]=> int(2) } string(226) "SELECT `item`.`uid`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` WHERE (`item`.`uri` = ? AND `item`.`wall` = ?) LIMIT 1" array(2) { ["uri"]=> string(75) "https://horche.demkontinuum.de/objects/2196d4ee-105c-c606-6852-c41439489978" ["wall"]=> bool(true) } string(255) "SELECT `item`.`id`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` WHERE (`item`.`parent-uri` = ? AND `item`.`uid` = ? AND `item`.`unseen` = ?) LIMIT 1" array(3) { ["parent-uri"]=> string(75) "https://horche.demkontinuum.de/objects/2196d4ee-105c-c606-6852-c41439489978" ["uid"]=> int(1) ["unseen"]=> bool(true) } string(1713) "SELECT `item`.`parent-uri`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid`, `item-content`.`title`, `item-content`.`body`, `item-content`.`plink`, `author`.`name` AS `author-name`, `author`.`thumb` AS `author-avatar` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 LEFT JOIN `item-content` ON `item-content`.`uri-id` = `item`.`uri-id` WHERE (`item`.`id` = ? AND `item`.`uid` IN (0, ?) ) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(2) { [0]=> int(3311327) [1]=> int(1) } string(3872) "SELECT `item`.`id`, `item`.`uid`, `item`.`parent`, `item`.`uri`, `item`.`parent-uri`, `item`.`thr-parent`, `item`.`guid`, `item`.`contact-id`, `item`.`owner-id`, `item`.`author-id`, `item`.`wall`, `item`.`gravity`, `item`.`created`, `item`.`edited`, `item`.`commented`, `item`.`received`, `item`.`event-id`, `item`.`attach`, `item`.`file`, `item`.`private`, `item`.`starred`, `item`.`origin`, `item`.`id` AS `internal-iid`, `item`.`network`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid`, `item-activity`.`activity` AS `internal-activity`, `item-content`.`language`, `item-content`.`title`, `item-content`.`content-warning`, `item-content`.`body`, `item-content`.`location`, `item-content`.`coord`, `item-content`.`app`, `item-content`.`rendered-hash`, `item-content`.`rendered-html`, `item-content`.`verb`, `item-content`.`object-type`, `item-content`.`object`, `item-content`.`plink`, `item-delivery-data`.`postopts`, `item-delivery-data`.`queue_count` AS `delivery_queue_count`, `item-delivery-data`.`queue_done` AS `delivery_queue_done`, `permissionset`.`allow_cid`, `permissionset`.`allow_gid`, `permissionset`.`deny_cid`, `permissionset`.`deny_gid`, `author`.`url` AS `author-link`, `author`.`name` AS `author-name`, `author`.`thumb` AS `author-avatar`, `author`.`network` AS `author-network`, `owner`.`url` AS `owner-link`, `owner`.`name` AS `owner-name`, `owner`.`thumb` AS `owner-avatar`, `owner`.`network` AS `owner-network`, `contact`.`url` AS `contact-link`, `contact`.`name` AS `contact-name`, `contact`.`thumb` AS `contact-avatar`, `contact`.`writable`, `contact`.`self`, `contact`.`id` AS `cid`, `contact`.`alias`, `contact`.`uid` AS `contact-uid`, `event`.`created` AS `event-created`, `event`.`edited` AS `event-edited`, `event`.`start` AS `event-start`, `event`.`finish` AS `event-finish`, `event`.`summary` AS `event-summary`, `event`.`desc` AS `event-desc`, `event`.`location` AS `event-location`, `event`.`type` AS `event-type`, `event`.`nofinish` AS `event-nofinish`, `event`.`adjust` AS `event-adjust`, `event`.`ignore` AS `event-ignore`, `event`.`id` AS `event-id` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 LEFT JOIN `event` ON `event-id` = `event`.`id` LEFT JOIN `item-activity` ON `item-activity`.`uri-id` = `item`.`uri-id` LEFT JOIN `item-content` ON `item-content`.`uri-id` = `item`.`uri-id` LEFT JOIN `item-delivery-data` ON `item-delivery-data`.`iid` = `item`.`id` LEFT JOIN `permissionset` ON `permissionset`.`id` = `item`.`psid` WHERE (`item`.`parent-uri` = ? AND `item`.`uid` IN (0, ?) ) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) ORDER BY `item`.`uid`, `item`.`commented` DESC LIMIT 300" array(2) { [0]=> string(75) "https://horche.demkontinuum.de/objects/2196d4ee-105c-c606-6852-c41439489978" [1]=> int(1) } string(206) "SELECT `item`.`origin`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` WHERE (`item`.`id` = ?) LIMIT 1" array(1) { ["id"]=> int(3311327) } string(1488) "SELECT `item`.`id`, `item`.`id` AS `internal-iid`, `item`.`network` AS `internal-network`, `item`.`icid` AS `internal-icid`, `item`.`iaid` AS `internal-iaid` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 WHERE (`item`.`uid` = ? AND `item`.`guid` = ?) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) LIMIT 1" array(2) { ["uid"]=> int(1) ["guid"]=> string(36) "2196d4ee-105c-c606-6852-c41439489978" } `

**Comment by MrPetovan** [comment]
Thank you, it's helpful. Based on this, can you please verify, in order:
1. the `visible`, `deleted` and `moderated` field of the item with id `3311315`.
2. the existence in the `user-item` table of a row with `iid = 3311315 AND uid = 1`.
3. the `hidden` field of the `user-item` row with `iid = 3311315 AND uid = 1`.

**Comment by hoergen** [comment]
**1. the visible, deleted and moderated field of the item with id 3311315.**
Modify | visible | deleted | moderated
-- | -- | -- | --
edit | 1 | 1 | 0

**2. the existence in the user-item table of a row with iid = 3311315 AND uid = 1.**
```
SELECT * FROM `user-item` WHERE `iid` = '3311315' AND `uid` = '1' LIMIT 50 (0.000 s) Edit

No rows. 
```

**3. the hidden field of the user-item row with iid = 3311315 AND uid = 1.**
search only for iid=3311315 doesn't give a result

**Comment by MrPetovan** [comment]
Thanks, so your own item has been deleted but not the corresponding public item, which means you didn't do it manually. It isn't the first time we have reports of unwarranted item deletion but unfortunately we currently have no way what or why triggered the deletion.

We should add this information in the item table because it is getting out of hand.

We checked a single post but you said you can't edit any post older than 1 month?

**Comment by hoergen** [comment]
I just looked at this post. Didn't search for another one. I think as soon we reduce the redundancy of entries in the database that @annando talked about some time ago, we won't have such issues any more. At the end there should be only one entry in the database and not several ones.

So I would say we close that issue, because we know what the reason is behind and there will be a general solution in the future.

Thank you so much for the whole research and searching for the reason of this issue. 🌻

**Comment by MrPetovan** [comment]
Thank you for your assistance, it was invaluable!

**Comment by AlfredSK** [comment]
Just as an addition in this thread...
https://libranet.de/display/ec054ce7-565d-00c0-9689-812358528347
...I could edit my posts for some time. Then, all of a sudden, it didn't work anymore. All my comments are not editable by me anymore.

**Comment by hoergen** [comment]
I reopen  this issue

**Comment by hoergen** [comment]
I checked several posts in the last month and I could every post. So maybe the bug is gone. How about you @AlfredSK  If you are fine with it, I would close this issue.

**Comment by AlfredSK** [comment]
Well, I didn't look very hard but I can't remember seeing this issue again. Feel free to close it.
