### ISSUE TITLE
Put infos for issues in preferences

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7253]
To open an issue you should always put enough information into each issue. One of these infos are  

- Friendica version you encountered the problem
- git or non git
-  PHP version
-  SQL version

We should put those information into the users `/settings` as separate section, so that every user who is contributing , has  the correct and asked information available and can copy and paste it directly into the issue.

It should look like this 
![00_temp](https://user-images.githubusercontent.com/24474762/59257373-1b8f2780-8c36-11e9-960a-3e3e40a02877.png)

**Comment by nupplaphil** [comment]
I'd like to add it for 2019.09 :-)

**Comment by annando** [comment]
Some of this stuff we already are having in the admin settings. I wouldn't want to expose such values for users.

**Comment by AlfredSK** [comment]
I think I'm with @annando here. Maybe we can extent the .../friendica page in a way the admin can expose information about the software and hardware that is used.

As an addition: Frio really needs a menu entry/link "about this node" or some other more obvious way to the .../friendica page. I've put a link on the login page and in my TOS. But as default the only link to .../friendica is in Help -> scroll down to the very end of the page.

**Comment by hoergen** [comment]
I don't see a problem to expose such information to the user.  You mean "Security through obscurity"
Putting it to the admin section doesn't help the user who wants to open an issue.
If it is helpfull that people working on issues have those information, it should be visible to the users as well.

**Comment by guzzisti** [comment]
@hoergen No offense meant, but: why did you hide your "Identity Address"? Security by obscurity? :wink: 

I'm really uncertain regarding this...my first thought was that a user should contact the instance admin before opening an issue.
"security by obscurity" is not considered a security mechanism, but on the other hand there are principles like "data reduction" (Datensparsamkeit auf deutsch) that would opt for not showing this information to the public (or users).

**Comment by hoergen** [comment]
🌻
What do you mean with "Identity Address"? You mean the city location where i live? In this context, it doesn't matter because it is not related to my friendica node. The one who needs to know it is my provider.

You can see my node contact and my email on this page  https://horche.demkontinuum.de/friendica

So I don't hide it. ;)

Data reduction is great, but it as always meant for something completely else.
 It is meant for collecting data regarding activities like clicking on a link, visiting a page, reacting on event, duration of staying on a page and so on.

In my view users should be able to open an issue independently from their node admin. It could have several effects and advantages 

1. Users start contributing to the project with small but equally important
2. Users may be getting more and more involved in the project
3. A node admin could accidentally or intentionally change the character of the context
4. It takes away the work load a node admin has anyway with his node
5. Users become more and more confident about the project and start their own node

**Comment by AlfredSK** [comment]
I have placed some information about the software and hardware on my /friendica page now. This is the place where users can find information about the Friendica version and such. So, I guess that's the appropriate place.

**Comment by hoergen** [comment]
It could be one place, but regarding to the doubts of the others, we could put this information with the actual state to the start page of the preferences of every user. So only logged in users can see that and not anonymous viewers, crawlers  and some evil haxors ;)

Maybe this is a good compromise?

**Comment by hoergen** [comment]
Wontfix. Closing it.
