### ISSUE TITLE
fetch fails if friendica post reshared from diaspora

### ISSUE THREAD

**Issue by git-marijus** [friendica/friendica#7269]
If a friendica post is shared from diaspora and hubzilla tries to fetch it from friendica, the fetch returns 404.

Here is the original post: https://libranet.de/display/0b6b25a8-655d-0361-c075-a3b460596594
Here is the post at diaspora: https://diasp.org/posts/0b6b25a8-655d-0361-c075-a3b460596594

https://libranet.de/fetch/post/0b6b25a8-655d-0361-c075-a3b460596594 returns 404 though.

**Comment by annando** [comment]
Looks like some bug in the router.

**Comment by MrPetovan** [comment]
We only have the `/fetch/{guid}/post` route, not the `/fetch/post/{guid}` route.

**Comment by MrPetovan** [comment]
Fixed by #7270
