### ISSUE TITLE
Pleroma reply appears top-level when accessed directly

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7285]
Friendica post (Diaspora reshare): https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998
Reply URL: https://friendica.mrpetovan.com/display/ee9e5ac6a5c11678def0175dbac588f63d76e441

The reply URL is both displayed in the thread and redirected to from notifications. The notification correctly identifies the reply as being on my own post. I'm not sure why the top-level post isn't picked up in the single post display.

Additionally, further replies to this Pleroma post only appear in the reply display page, not in the complete thread display. I'll dig into the `item` table later.

**Comment by annando** [comment]
Have a look for the URL of the reply. Then look for the source in the "conversation" table and check whether it has got a reply URL there. And then have a look if this reply URL is known on your system.

**Comment by MrPetovan** [comment]
The item table shows an interesting situation for the same `guid` and `uri`:

id | uid | wall | gravity | notes
--|--|--|--|--
2055600 | 1 | 0 | 0 | Top-level post for me (uid=1)
2055601 | 0 | 0 | 0 | Public top-level post 
2055602 | 1 | 1 | 6 | Reply for me (uid=1)
2055603 | 16 | 0 | 6 | Reply for another user on my node

The issues:
- The same post is both a top-level post and a reply
- There's no public reply item

But this explains why I see the post in both situations (either as a reply or as a top-level post) and why when I reply to the top-level post, it doesn't show up on the reply item.

In the conversation table, there is only one row with the item uri:

Field | Value
--|--
item-uri | https://shitposter.club/objects/61bdc0f9-4f27-4639-88b8-2dd7a0efad58
reply-to-uri | https://friendica.mrpetovan.com/objects/735a2029-105d-0afb-8d97-48e316865998
conversation-uri | https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998
conversation-href | https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998
source | See below

```xml
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:ostatus="http://ostatus.org/schema/1.0">
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <id>https://shitposter.club/objects/61bdc0f9-4f27-4639-88b8-2dd7a0efad58</id>
  <title>New note by adrint</title>
  <content type="html">&lt;span class='h-card'&gt;&lt;a data-user='5897' class='u-url mention' href='https://friendica.mrpetovan.com/profile/hypolite'&gt;@&lt;span&gt;hypolite&lt;/span&gt;&lt;/a&gt;&lt;/span&gt; Climate change is literally part of nature.</content>
  <published>2019-06-20T05:51:06.767187Z</published>
  <updated>2019-06-20T05:51:06.767187Z</updated>
  <ostatus:conversation ref="https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998">https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998</ostatus:conversation>
  <link ref="https://friendica.mrpetovan.com/display/735a2029-105d-0afb-8d97-48e316865998" rel="ostatus:conversation"/>
  <summary/>
  <link type="application/atom+xml" href="https://shitposter.club/objects/61bdc0f9-4f27-4639-88b8-2dd7a0efad58" rel="self"/>
  <link type="text/html" href="https://shitposter.club/objects/61bdc0f9-4f27-4639-88b8-2dd7a0efad58" rel="alternate"/>
  <author>
    <id>https://shitposter.club/users/adrint</id>
    <activity:object>http://activitystrea.ms/schema/1.0/person</activity:object>
    <uri>https://shitposter.club/users/adrint</uri>
    <poco:preferredUsername>adrint</poco:preferredUsername>
    <poco:displayName>Adrint</poco:displayName>
    <poco:note>I am Adrint: Linux hobbyist, shitposter, /pol/itician, and purveyor of dank may-mays. I may look fly, but I wanna die.</poco:note>
    <summary>I am Adrint: Linux hobbyist, shitposter, /pol/itician, and purveyor of dank may-mays. I may look fly, but I wanna die.</summary>
    <name>adrint</name>
    <link rel="avatar" href="https://shitposter.club/media/93cb10f279a0188180e46f99235bcee0611080f9fedeaa38cb11b2ee85e2e4c8.jpg?name=93cb10f279a0188180e46f99235bcee0611080f9fedeaa38cb11b2ee85e2e4c8.jpg"/>
    <link rel="header" href="https://shitposter.club/media/a36ad5117395f0f3341d9bc72a88f20ab0385e5fc594b0958493acd252a8db29.jpg?name=a36ad5117395f0f3341d9bc72a88f20ab0385e5fc594b0958493acd252a8db29.jpg"/>
    <ap_enabled>true</ap_enabled>
  </author>
  <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="https://friendica.mrpetovan.com/profile/hypolite"/>
  <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
  <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="https://shitposter.club/users/adrint"/>
</entry>
```

**Comment by annando** [comment]
This arrived via OStatus

**Comment by MrPetovan** [comment]
Yes, protocol is 3 in the conversation table.

**Comment by annando** [comment]
We cannot change the behaviour that Pleroma sends both AP and OStatus. And we cannot influence their content. So I would declare this fixed in some way, since we improved the duplicate check.
