### ISSUE TITLE
Registration button on home page despite of registration policy closed

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7293]
### Expected behavior
When the registration policy is set to 'closed' there should be no "Register" button on the home page.

### Actual behavior
When the registration policy is set to 'closed' there is a "Register" button. Clicking the button redirects to a Friendica page with no content and only a notification bubble saying "Permission denied".

That's bad UX. People will think registration is broken instead of closed.

### Steps to reproduce the problem
Set register policy to close. Visit the home page of your node.

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
10.1.40 MariaDB

**Comment by MrPetovan** [comment]
Is this only a frio theme issue?

**Comment by AlfredSK** [comment]
I will check later. :-)

**Comment by AlfredSK** [comment]
Later: I switched the node to 'vier'. The register link is at the bottom of the page. Clicking it gives "Permission denied". So yes, it's the same behavior with other themes than frio.

**Comment by MrPetovan** [comment]
That's what I found out as well, there's a central theme-agnostic switch to show the registration link or not.
