### ISSUE TITLE
Weird stuff is displayed instead of a code block

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7300]
I found a bug with the filebrowser (frio) when creating a post and uploading an image. But this is a separate bug.

When I tried to post the browser console output I got a very weird content displayed instead. When I edit the post the code block is displayed correctly. But when I save it I get the weird stuff again.

This is the content of the code block:
```
[code]File Browser: test201906 image fbrowser.image.main undefined filebrowser.js:90:11
SyntaxError: missing ) in parenthetical ajaxupload.js:1:17
    _getResponse https://venera.social/view/js/ajaxupload.js:641[/code]
```

And this is what I get after saving the post (it was actually a comment if that matters):

`
PGNvZGUgY2xhc3M9Imxhbmd1YWdlLSI-RmlsZUJyb3dzZXI6IHRlc3QyMDE5MDYgaW1hZ2UgZmJyb3dzZXIuaW1hZ2UubWFpbiB1bmRlZmluZWQgZmlsZWJyb3dzZXIuanM6OTA6MTENClN5bnRheEVycm9yOiBtaXNzaW5nICkgaW4gcGFyZW50aGV0aWNhbCBhamF4dXBsb2FkLmpzOjE6MTcNCiAgICBfZ2V0UmVzcG9uc2UgaHR0cHM6Ly92ZW5lcmEuc29jaWFsL3ZpZXcvanMvYWpheHVwbG9hZFwuanM6NjQxPC9jb2RlPg==
`

See: https://libranet.de/display/0b6b25a8-105d-0e40-d169-e3c257307209

### Steps to reproduce the problem
Write a comment with that code block I posted above...

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
MariaDB 10.1.40

**Comment by AlfredSK** [comment]
The top level post was a forum post. And the code block in my comment looks totally normal on the forum node (also on RC, but not with the latest commits from today).

**Comment by AlfredSK** [comment]
This is caused by 7294 or by 7286.
Summoning @annando and @MrPetovan :-)

Whenever I try to add actual code like the one mentioned above or some PHP code I get some base64 stuff instead.

**Comment by MrPetovan** [comment]
On it.

**Comment by MrPetovan** [comment]
I have been trying to save posts and replies with the same exact input and it doesn't end up as Base64 string. I have the Unicode Emojis addon enabled as well.

**Comment by MrPetovan** [comment]
Fixed by #7302

**Comment by AlfredSK** [comment]
Hmm. This is the list of my add-ons:
blockem, buffer, catavatar, fromapp, geocoordinates, ifttt, impressum, js_upload, langfilter, newmemberwidget, notifyall, nsfw, openstreetmap, pumpio, rendertime, showmore, startpage, superblock, tumblr, twitter, unicode_smilies, wppost

After #7302 has been merged everything was fine again.

**Comment by MrPetovan** [comment]
I found the actual issue.

**Comment by AlfredSK** [comment]
I'm curious...

**Comment by MrPetovan** [comment]
Actually fixed by https://github.com/friendica/friendica/pull/7304
