### ISSUE TITLE
Event calendar - federation doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7303]
### Expected behavior
When I make local changes to an event or a shared event these changes should federate to other users on local node and remote nodes.
These changes are: Event actions like 'will attend' and so on, changing the event time, deleting an event.

### Actual behavior
All those changes are displayed locally for the user who makes the changes - e.g. the creator changes the time -> creator can see the changed time. A user the event is shared with clicks 'will attend' -> the user sees the 'will attend' notice.
But nobody else can see those changes. Nobody gets the information who will attend the event or that the time has changed.
Also, when the creator deletes the event from the calendar. The event stays in all remote calendars. The deletion doesn't federate at all.

### Steps to reproduce the problem
As user A create an event in your calendar and share it with user B. A makes changes to the event. A clicks on 'will attend'. Then login with account of user B and check if you can see the attendance notice from user A and the changes A made to the event.

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
10.1.40 MariaDB

**Comment by annando** [comment]
I'm on it.

**Comment by MrPetovan** [comment]
Fixed by #7306

**Comment by MrPetovan** [comment]
@AlfredSK Can you please pull and try again?

**Comment by AlfredSK** [comment]
Yes. Just need a coffee...

**Comment by AlfredSK** [comment]
Works! 'Will attend' is transmitted to the other user now. Also changing the event time federates again.
The only thing that doesn't work is the deleting the event. It is deleted locally but not on the remote side.
