### ISSUE TITLE
[frio] New compose page to replace/complement the jot modal

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7309]
The current JOT modal offers a different publishing experience from the comment box due to the constraints of the modal window. Having a separate page would stamp out these inconsistencies and offer more room for additional publishing options for top-level posts.

The advantages would be:
- Consistent file browser behavior (both in a modal).
- Consistent preview behavior (both with a button instead of a tab).
- Permissions shown prominently (combined with https://github.com/friendica/friendica/issues/7308 to save space).
- Possible location and publishing date fields without sacrificing expensive real estate in the modal.
- No more modal closing when pressing escape to hide the autocomplete lists (personal pet peeve).
- Possibility to have a draft feature.

This page should retain the pre-filled mention feature we currently have when pressing the Compose button from the network page filtered by forum.

**Comment by annando** [comment]
When you rework the permissions, it would be great to not only had the option to post public or to dedicated groups/accounts, but to post non public to all followers. This is a special collection for AP.

**Comment by MrPetovan** [comment]
How is is different from having only a single group (all contacts) in the "Allowed" field for example?

**Comment by annando** [comment]
We could also create a virtual group "all followers". Only thing is that the user can't remove someone from that group except from unfollowing someone. 

To explain the difference to the regular groups: In AP every receiver has to be added to the headers "to", "cc" or "bcc". In a public post you only add the public collection to "to" or "cc", nothing more (except you want to mention someone or you want to address someone who isn't following you). 

In difference to this in our regular non public posts we have to add every single receiver in "to", "cc" or "bcc".

This virtual group would be different to this and more like the public posts. We would address the post to the "followers" collection to the header instead of addressing each and every single contact .

**Comment by MrPetovan** [comment]
To shorten the difference:
- Public: Sent to all followers but not namely.
- Protected: Sent to all followers namely.

**Comment by annando** [comment]
To fill the gap:
* Public: Sent to all followers, not namely and everyone else can see and interact
* Followers: Sent to all followers, not namely and only the followers can see and interact
* Protected: Sent to selected followers namely.

**Comment by MrPetovan** [comment]
What's the difference? Can new followers actually get the "Followers" post after it's been posted and delivered and interact on it?

**Comment by annando** [comment]
The difference is that "followers" will always include all of your followers - with no exemption. "Protected" does include a selected group of contacts that you can chose freely.

And yes, new followers would be able to fetch old followers posts.

**Comment by MrPetovan** [comment]
We might have a problem on terms: "protected" on Twitter means "followers" in your list, and your "protected" would simply be "private".

**Comment by annando** [comment]
I'm not good in wording. So yeah, this sounds okay. So I finally had been able to explain it ;-)

**Comment by MrPetovan** [comment]
Here's how I see the permissions choice:
- A radio button list with:
    - Public
    - Protected
    - Custom, with two tag inputs:
        - Allowed: Autocompleted groups and contacts
        - Disallowed: Autocompleted groups and contacts

Is it possible to have a public post with a group or contact disallowed?

**Comment by annando** [comment]
Neither public nor protected posts can exclude someone. But of course you can always add someone.

**Comment by MrPetovan** [comment]
So the radio buttons make sense. What about mentioning to add someone?

**Comment by annando** [comment]
I wouldn't suggest doing the adding in the modal dialog. This normally is done with public posts and additionally mentioning someone in the post.

**Comment by MrPetovan** [comment]
Ok, so I rest my design case.

**Comment by annando** [comment]
I would love seeing a new design!

**Comment by MrPetovan** [comment]
Disclaimer: It won't be shiny, rather extremely functional. It will look like a bigger comment box with additional form fields above/below.

**Comment by annando** [comment]
Make it shiny!

**Comment by MrPetovan** [comment]
I'm not @lostinlight, I can't do cute.

**Comment by nupplaphil** [comment]
https://m.youtube.com/watch?v=93lrosBEW-Q

**Comment by MrPetovan** [comment]
Given the existing design constraints, I won't be able to provide this new view for other themes than Frio.

But I have a sneak preview!

![friendica-compose-design-1](https://user-images.githubusercontent.com/925415/60736757-1d42c700-9f26-11e9-8f73-76e4187777c3.png)
Explanations:
- Blue means "Group", Red means "Single Contact".
- "Followers" is a meta-group referencing every contact who follows you. I also added the meta-group "Mutuals". I couldn't name it "Friends" because this is how we name the default contact group (that I want to nix).
- I need to add the dropdown/radio buttons to make a post visibility public or custom. "Protected" is now covered by the meta-group "Followers".
- The connector checkboxes are missing too.

**Comment by MrPetovan** [comment]
### Progress report

Visibility accordion is done. I removed the `Public` meta-group I was initially using to avoid confusion since this meta-group would have made any other selection moot.

![friendica-compose-design-2-visibility](https://user-images.githubusercontent.com/925415/60750188-df1fc480-9f72-11e9-9219-87401477468e.png)

Plugin checkboxes should show if any was actually showing on my test node. I'll have to test this one more thoroughly on my main instance.

**Comment by MrPetovan** [comment]
### Progress report

The compose view can accept its own form parameters in the query string, which paves the way for drafts.

I added the special group ids to the ACl expansion functions/methods, and I'm now ready to test how good they work exactly.

Near-final look:
![friendica-compose-design-3-location](https://user-images.githubusercontent.com/925415/60935724-db54b080-a298-11e9-85bc-1604fe43d66b.png)

**Comment by annando** [comment]
Think of making it scrollable for small displays.

**Comment by MrPetovan** [comment]
It's going to be scrollable as any other page on the frio theme.

**Comment by SpencerDub** [comment]
This is exciting to see! I picked a good time to get interested in Friendica. 😁

**Comment by tobiasd** [comment]
> What about mentioning to add someone?

I don't like the idea

> *Hey everybody it is birthday time for @heluecht and I want to throw a surprise party*

could then spoil the surprise. While it was only to let the recipients of the posting know which of the 10 Micheals in the peer-group has the birthday, so that the presents can be related to HSV handball and not ManU soccer.

**Comment by MrPetovan** [comment]
I actually thought about that specific scenario. How it it handled at the moment? What happens if Michael is mentioned in the body and added to the "Except" field?

**Comment by AlfredSK** [comment]
> What happens if Michael is mentioned in the body and added to the "Except" field?

All hell breaks loose - everything goes up in flames. ;-)

**Comment by MrPetovan** [comment]
![elmer-flames](https://user-images.githubusercontent.com/925415/61172861-e473a500-a558-11e9-84c4-270d43967e88.gif)

**Comment by MrPetovan** [comment]
The actual answer is that, for ActivityPub at least, mentions don't override permissions if they are set. It only adds an additional notifier message if the message is public and the mentioned account isn't among your followers.

**Comment by tobiasd** [comment]
He should not (IOW I have not used it for a while but rather selected all other recipients) receive the posting.
