### ISSUE TITLE
forum filter in network view only show content of followed contacts

### ISSUE THREAD

**Issue by guzzisti** [friendica/friendica#7315]
From: https://sozialwolke.net/display/703b8751-115d-1091-e4c8-337367978593

### Expected behavior
When using a forum filter in the network view, all content published to this forum should be shown.

### Actual behavior
After the forum filter is applied, only content of contacts that you follow is shown. This is the case even if the users used the `!` notation to refer to the forum.

### Steps to reproduce the problem
- Follow a forum
- When new posts appear, this will be shown in your network timeline
- Apply a forum filter in the network view (shown left of the timeline)
- Content by people you have no connection to disappears

### Friendica version you encountered the problem
2019.06

### Friendica source (git, zip)
zip

### PHP version
7.3.6

### SQL version
MySQL 5.7.26

---
Don't know if this is helpful, i found the following situation in the database:
There are 2 contacts for the forum in the `contact` table as this is the case for all forums i guess this is intentional:
![image](https://user-images.githubusercontent.com/10488791/60018866-b0f5d700-968c-11e9-9240-dc728004d2cf.png)

The forum filter refers to the contact id 1101 which is owned by my user. All other content linked to the forum (like the "... via Friendica Support" links) refers to the contact id 1100.

**Comment by AlfredSK** [comment]
Hmm. I checked this but could not reproduce. I have an account with only 12 contacts. One of them is the Friendica Support forum. I see a lot of forum posts from various people when I click on the Support Forum in the forum widget.
Then I compared it with my main account (with >400 contacts). Both streams are identical.

It seems that the cause is not to be found in the forum widget/filter itself. Must be something different.

**Comment by guzzisti** [comment]
I still have this behaviour...Friendica Support shows 2 posts in the last day [Screenshot](https://user-images.githubusercontent.com/10488791/60176623-2d1c2600-9817-11e9-8f13-758ffc833cf4.png)
Using the forum filter, it still only shows my last post a few days ago.

But its getting even crazier ;)
In Friendica Admin, the last post is from Adam Gashkin [Screenshot](https://user-images.githubusercontent.com/10488791/60176750-7c625680-9817-11e9-9fd2-dff41a9ae4ef.png)

Using the forum filter, i see 2 posts from 3 months ago - without the comments [Screenshot](https://user-images.githubusercontent.com/10488791/60177037-32c63b80-9818-11e9-8bfd-fc100322c8f6.png).

If you need me to provide additional info please let me know.

**Comment by annando** [comment]
I have to think about a good query and a possible cause. How good are you in doing SQL queries?

**Comment by guzzisti** [comment]
I think "good" is not overestimated. I've been a developer for more than 15 years and some sort of "DBA" nowadays.

**Comment by annando** [comment]
Okay, so I will explain the database structure and the relations, then you can search by yourself ;-)

**Comment by guzzisti** [comment]
At least i could try :)
I will try to dig a bit further on my own...but this have to wait till end of my holiday. ;)

**Comment by annando** [comment]
Have fun! I'm currently working on some other tasks, so I hadn't got time looking at it.

**Comment by guzzisti** [comment]
I was looking forward to investigate this issue a bit further this evening...but currently i'm not sure if the issue still exists.
I will do another test with a test user.

**Comment by annando** [comment]
You could have a look at the corresponding contact of the forum. Then you can have a look at the fields "forum", "prv" and "contact-type". What does the contact entries tell? (you should have at least two entries. One with "uid=0" and one with another value in "uid")

**Comment by guzzisti** [comment]
Having a further look, it seems like not all forums are affected. It seems to work for "Friendica Admins", but "Friendica Support" and "Friendica Developers" don't work as expected.

There are 2 contacts for each forum. Values are the same for all of these contacts: forum=1, prv=0, contact-type=0
There is a obvious difference i found, see screenshot below:
* Friendica Admin (the forums where filtering works and `item`s are imported) uses DFRN
* Friendica Support & Friendica Developer (filter shows and `item` table shows no items except my posts) uses ActivityPub
![image](https://user-images.githubusercontent.com/10488791/61148551-4ee7ff00-a4df-11e9-8fde-9d28e50bcd1c.png)

I have the strong feeling that its related to my issue. ;)

**Comment by annando** [comment]
Naaaa, this "protocol" field can't be related to this. It must be something else :grimacing: 

Yeah, I really do think that we still have some issues with "Friendica over AP".

But you do get all forum posts, don't you? You only don't see them under the forum's page?

**Comment by guzzisti** [comment]
I see all forum posts in my timeline (i guess thats the `conversations` table?) but not using the forums page.

**Comment by annando** [comment]
"conversation" is only for storing the raw data (for a limited time). The posts are in the tables with "item".

**Comment by guzzisti** [comment]
Thank you for the information. I tried to get a bit further, but i don't see any light at the end of the tunnel. ;)

I stated earlier that "Friendica Admins" seems to work, but this is not completely true. The 2 most recent posts (https://friendica.philipp.info/display/f1417ed3-935d-2c3c-10dc-3b4583321488 and https://libranet.de/display/0b6b25a8-905d-2b53-8a00-fcb437586727) are missing from the forum view. The posts are marked as "Friendica (AP)" in my timeline where they show up.

But i see older posts that have the initial posts as "Friendica" (e.g. https://forum.friendi.ca/display/2196d4ee-105d-271d-0c88-4fd409708541), i also see https://forum.friendi.ca/display/2196d4ee-845d-25b4-0b3a-373712356839 as "Friendica" on my node, whereas the original post https://forum.friendi.ca/display/2196d4ee-845d-25b4-0b3a-373712356839 shows as "Friendica (AP)".

I'm pretty sure there is a glitch in the current ActivityPub implementation. Will give it another try later on.

**Comment by annando** [comment]
I'm absolutely sure that it is a glitch in AP. I can tell the background: Forum posts are done like reshares. Normally a reshare is some activity for an item. And it doesn't change the item. For forums we have to change the owner of the item to the forum account. I though that I had done so - but obviously I haven't.

**Comment by guzzisti** [comment]
Ah, i did some tests with modifying contact-id and owner-id as these where obviously different to the post transfered over DFRN, but the posts didn't show up in the frontend. Maybe i missed something or there some sort of caching in between.

**Comment by annando** [comment]
You have to modify the "owner-id" in the "thread" table as well.

**Comment by annando** [comment]
This here is the relevant code that _should_ work:

https://github.com/friendica/friendica/blob/develop/src/Protocol/ActivityPub/Receiver.php#L388-L405

**Comment by annando** [comment]
I just found a flaw in the whole process. I guess we need several changes to the whole process ...

gnarf ...

**Comment by MrPetovan** [comment]
Sorry about that!

**Comment by guzzisti** [comment]
I gonna move my instance to the develop-branch the next days and keep you updated.

**Comment by MrPetovan** [comment]
I would wait a couple days, the current develop branch state is less than satisfactory.

**Comment by annando** [comment]
I did tests with 3 servers. My changes do work very fine. Thanks for reporting this issue!
