### ISSUE TITLE
Investigate `/contact` pages slowness

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7316]
At 1000 contacts, the `/contact` page and `/contact/xxx/conversation` page take more than 10 seconds to load on my node.

I intend to go to the bottom of this using XDebug traces.

**Comment by annando** [comment]
You don't need traces, this clearly is a database issue. You could try the config variables "db_loglimit" and "db_log" to trace it down (or use the slow query log in MySQL).

**Comment by MrPetovan** [comment]
Yes, missing table indices is my first hunch.

**Comment by annando** [comment]
It is fast on my system. So possibly you only need some database speedup. Have you already used mysqltuner.pl?

**Comment by MrPetovan** [comment]
Yes, with unfortunately bad results. My system hasn't changed since the last time I did an actual optimization, so I'll pass, thank you.

**Comment by annando** [comment]
So just investigate the slow query log and report them. I can have a look at it, In fact I would like to keep the index stuff changes under my control.

**Comment by MrPetovan** [comment]
You'll always be in control since I won't self-merge my own PRs. If you're quicker than @nupplaphil, that is! 😃

**Comment by annando** [comment]
Thing is: When I'm doing index stuff I'm using stuff like the "explain" command to see if this really works, also I'm using index usage statistics to test the usage over a few days.

**Comment by MrPetovan** [comment]
I'll tell you what, I'll look into it tonight, and if it's an index issue like I suspect, I'll hand it to you. Deal?

**Comment by annando** [comment]
Sounds good.

**Comment by MrPetovan** [comment]
So far no DB bottleneck, neither for `/contact` nor `/contact/xxx/conversation`, rendertime shows the whole page load time in "Other". It looks like XDebug will come in handy.

**Comment by MrPetovan** [comment]
Day 1 summary: I'm going crazy. I found #7319 to have been slowing page loads significantly, but this isn't the unsettling part. According to the DB profiling, a `DBA::selectFirst` query on the table `user` with a condition on `id` (the primary key) is twice faster if the `nickname` field is absent from the query. Even then, it still is a 50 ms query for a simple primary key record lookup in a single table with just 13 rows!

**Comment by annando** [comment]
Have you enabled the "rendertime" addon with ```'profiler' => true,``` in the config? This should also help finding the origin of the speed loss.

**Comment by MrPetovan** [comment]
Yes, most queries take <10ms, so I focused on the 100+ms, and that's when I started pulling my hair:

```php
DBA::select('user', ['id'], ['uid' => 1]); // ~50ms (which is already massive)
DBA::select('user', ['nickname'], ['uid' => 1]); // ~100ms (which is downright incomprehensible)
```

**Comment by annando** [comment]
This really sounds more like an SQL server issue. I did a small test:

```
$stamp1 = microtime(true);
$data = DBA::select('user', ['uid'], ['uid' => 1]);
$stamp2 = microtime(true);
echo ($stamp2 - $stamp1) . "\n";
$stamp1 = microtime(true);
$data = DBA::select('user', ['nickname'], ['uid' => 1]);
$stamp2 = microtime(true);
echo ($stamp2 - $stamp1) . "\n";
```

And I got results like this:
```
0.0002748966217041
0.00031304359436035
```

**Comment by MrPetovan** [comment]
I agree with you, but I still am at a loss. I did an ``OPTIMIZE TABLE `users` `` but I'm not confident.

**Comment by MrPetovan** [comment]
Found another weird bottleneck:
```
Database Write:
Database::insert, DBA::insert, Worker::add, Contact::getIdForURL: 0.908
```
After `OPTIMIZE TABLE `workerqueue`;`
```
Database Write:
Database::insert, DBA::insert, Worker::add, Contact::getIdForURL: 2.504
```
Gaaaah.

**Comment by MrPetovan** [comment]
This particular page slowness seems to be caused by my hard disk not keeping up with all the writes MariaDB is trying to perform, closing for now.
