### ISSUE TITLE
Avalanche of info bubbles "X welcomes $you"

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7317]
### Expected behavior
Dunno. I expect to not seeing that avalanche of info bubbles. So, either there should be a fix or those info bubbles need to be suppressed.

### Actual behavior
Every time some image is loaded I get a notification bubble "X welcomes Steffen K9".
I'm not sure. But this did not happen one day before the release. So, most likely this is caused by the last minute merge of PR #7305.

It's somewhat annoying but it's really over the top on the admin/users page...

![Bildschirmfoto von 2019-06-24 22-03-08](https://user-images.githubusercontent.com/3656054/60049094-d9ea8c00-96cd-11e9-8de1-279fe0b53a6f.png)

As a workaround I'll disable them completely in my user settings.

### Friendica version you encountered the problem
2019.06 master

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
10.1.40 MariaDB

**Comment by MrPetovan** [comment]
Nice!

**Comment by MrPetovan** [comment]
Calling @deantownsley to the rescue.

**Comment by deantownsley** [comment]
Sorry about the extra noise.  #7305 adds authentication to the "bare" image load call path.  I think the issue here is that I didn't think to add a check to see if the image being retrieved is public.  If you happened to have any private images on that page, they should work now :wink:.  I think the right fix is to add a check for if the image is public and then, if so, skip the authentication attempt.  I can have a patch to do that later today.  What branch should I target the PR at?

**Comment by AlfredSK** [comment]
Thanks for the elaboration. That page is showing the registered users of my node. The images loaded are the profile avatars of the local users. They're most likely public.

**Comment by MrPetovan** [comment]
The branch you should target is now `develop` since we have released a new version yesterday.

**Comment by deantownsley** [comment]
Hopefully addressed by #7318.

**Comment by MrPetovan** [comment]
@AlfredSK Can you please pull and try again?

**Comment by AlfredSK** [comment]
I'll see what I can do this evening.

**Comment by AlfredSK** [comment]
So. Back from work. To check this I have to switch to develop. Is that branch in a working (mostly stable) state at the moment?

**Comment by MrPetovan** [comment]
Absolutely, we haven't merged any risky PR so far.

**Comment by AlfredSK** [comment]
OK. I switched one node to develop. Seems to work. I didn't get those notification bubbles anymore. Closing...

Seems to be fixed by #7318.
