### ISSUE TITLE
Shared host installation impossible

### ISSUE THREAD

**Issue by jranma** [friendica/friendica#7325]
trying to install friendica 2019.06 fresh new on my shared host hosting, using https://friendi.ca/resources/installation/ doc

I unziped and copied all the files to /

trying to access Friedica, I get 404 error: 
http://MY_DOMAIN/install not found. 

/install directory is missing.

**Comment by jranma** [comment]
ok, solved by renaming .htaccess
(documentation should be updated :)

**Comment by jranma** [comment]
ok, solved by renaming .htaccess
(documentation should be updated :)

**Comment by jranma** [comment]
ok, solved by renaming .htaccess
(documentation should be updated :)

**Comment by MrPetovan** [comment]
Hi @jranma, which documentation did you follow so that we can update it?

**Comment by jranma** [comment]
https://friendi.ca/resources/installation/

**Comment by MrPetovan** [comment]
Thanks!
