### ISSUE TITLE
deleted contacts not removed from groups

### ISSUE THREAD

**Issue by redmatrix** [friendica/friendica#7337]
### Expected behavior

Deleting a contact removes it from groups and from delivery to those groups they were once members of.

### Actual behavior

Deleted group members showing up in ActivityPub envelopes, there may be other places. Delivery attempts of private posts to the group in question are also made to the deleted contacts. It is also particularly insidious because if you edit the group and look at the members, the deleted contact is not shown in that display so there is no easy way to tell within the Friendica UI that this deleted contact may still be included in private posts. 

### Steps to reproduce the problem

Delete a contact that was in a group. Send a private message to that group. In my case I can see ActivityPub activities on other systems showing the deleted contact as a 'cc' recipient. I have also verified that a delivery attempt was made to this deleted contact. 

### Friendica version you encountered the problem

2019.09-dev (libranet.de)

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)

n/a

### PHP version

n/a

### SQL version

n/a

A quick glance at source shows that Item::enumeratePermissions() may be calling Group::expand() without the $check_dead flag set, but it isn't clear if adding the flag would cause undesirable side effects elsewhere. 

src/Protocol/ActivityPub/Transmitter.php::L389

**Comment by annando** [comment]
@MrPetovan hadn't you wanted to have a look at this?

**Comment by MrPetovan** [comment]
I don't want to but I'll do it if I must. I only touched Groups for meta-groups like "Followers" and "Mutuals".

**Comment by annando** [comment]
In the original discussion @redmatrix had provided some solution that should work. We only have to decide if there is any reason to keep deleted contacts in a group. If not then we could simplify that proposed software change even more.

**Comment by MrPetovan** [comment]
No, there's absolutely no reason to keep a deleted contact in a group. This at least is clear.

**Comment by annando** [comment]
Well, when you wrote a non public post to a specific group of people, remove some person from that group and now you decide to change or delete the post, then it would be great if this is done at the copy for that removed person as well, isn't it?

**Comment by MrPetovan** [comment]
This is different, in your example the contact isn't deleted, only the group. As for a reliable update/deletion process, we would need an additional list independent of the ACL of all the recipients of a specific post. But we can't silently keep a contact in a group when it's been removed or deleted.
