### ISSUE TITLE
PHP error / http 500 when opening an old photo

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#7340]
### Expected behavior
Show photo.

### Actual behavior
When I try to open certain photos from /photos/$user/album I get a PHP error.

One block like this shows up in the log each time I press F5 or try to open another photo from the album.

[02-Jul-2019 12:42:31 Europe/Brussels] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to get_responses() must be of the type array, bool given, called in /path/to/webroot/mod/photos.php on line 1541 and defined in https://social.yl.ms/photos/utzer/image/38aea7645d6d44c8b75c558993c99206include/conversation.php:1524
Stack trace:
#0 /path/to/webroot/mod/photos.php(1541): get_responses(Array, Array, false)
#1 /path/to/webroot/src/LegacyModule.php(71): photos_content(Object(Friendica\App))
#2 /path/to/webroot/src/LegacyModule.php(45): Friendica\LegacyModule::runModuleFunction('content')
#3 [internal function]: Friendica\LegacyModule::content()
#4 /path/to/webroot/src/App.php(1241): call_user_func(Array)
#5 /path/to/webroot/index.php(17): Friendica\App->runFrontend()
#6 {main}
  thrown in /path/to/webroot/include/conversation.php on line 1524

### Steps to reproduce the problem
Go to some old photos, in my case it was an album from 2016. 

### Friendica version you encountered the problem
Latest released version, 2019.06.

### Friendica source (git, zip)
git

### PHP version
7.3.6

### SQL version
10.3.16-MariaDB

**Comment by MrPetovan** [comment]
Sounds like a Fatal Error submission: https://github.com/friendica/friendica/issues/7297

**Comment by ben-utzer** [comment]
Well indeed, I didn't remember that you started collecting php errors separately. Should I just copy my whole issue text into a comment over there?
