### ISSUE TITLE
Tags shouldn't be links when transmitted to non-Friendica servers

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7344]
### Expected behavior
Tags shouldn't be links to the node the post is coming from. They should be transmitted as is - plain text. The remote side should decide what to do with them. For example link them to their local #tag stream.

### Actual behavior
Tags are links to the node where the post is coming from.
When I post something with #tags I don't expect them to be transmitted as links to my node.
It doesn't make sense. Especially when your Friendica node is not allowing unauthorized usage of the search function (you end up on a 404 page). 

### Steps to reproduce the problem
Write a post with #sometag. Look at that post on e.g. Mastodon. The tag is linked to you node like https://friendica.example.com/search?tag=sometag

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
I checked how this works between two Friendica nodes. There it works like expected. The tag always links to the local tag stream.

**Comment by hoergen** [comment]
There is another issue https://github.com/friendica/friendica/issues/7222

**Comment by MrPetovan** [comment]
Closing as duplicate, thanks for the keen eye!

**Comment by AlfredSK** [comment]
I'm sorry. :man_shrugging:
