### ISSUE TITLE
Add item table "shared" field

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7346]
Redux of #3816

Currently items have the following date fields:
- created
- edited
- commented
- received
- changed

I propose adding a new `shared` field that will be set to the `created` date by default, and updated when we receive a share of this item from one of our contacts. This would limit its update to non-public posts (`item.uid !== 0`)

Subsequently, the "Posted last" order will move from `created` to `shared`. This will allow shared items to show in the network stream at the date and time they were shared, not initially posted, while retaining and displaying the creation date.

I want to do this on my own, but I'm a little unclear as to where in the protocols I would have to update the new field.

@annando do you have any pointer?

**Comment by annando** [comment]
Any new date field that is used for ordering will increase the need for several more indexes. I really do suggest using the existing fields. Can't we simply use the field ```commented``` instead?

**Comment by MrPetovan** [comment]
I don't think so. I use notifications to be kept up-to-date with comments on the threads I choose to follow. The "Commented last" order is awful for me because I can't mentally keep the position I last read in the stream since the order constantly changes from comments I don't necessarily care about.

**Comment by annando** [comment]
The ```received``` field is the date that the post arrived at first on the system. So when it had been fetched for the first time at the receiving of the reshare message, then it will have that date. When that post will be reshared a second time, then it won't be appear again in your timeline.

BTW: In fact I just had seen that we don't always order by the receiving date, but the creation date. I guess it will help a lot when we change that overall.

**Comment by MrPetovan** [comment]
Interesting, it wouldn't bring already existing posts up in the stream but would show newly shared post at the sharing date. I'll make the change locally and I'll report on that.

**Comment by MrPetovan** [comment]
Which pager bug?

**Comment by annando** [comment]
I mean the bug that causes the skipping of posts of several hours when scrolling down.

**Comment by annando** [comment]
Sadly my changes don't fix that bug. But I do now have some hints. But this will most likely be a separated PR.

**Comment by MrPetovan** [comment]
Using the `received` field for sorting so far is working to bring shared item when they were shared in the network stream.

**Comment by annando** [comment]
My changes to the date fields are having the following effect: A reshare of an item that is new to you will appear at the top. But when you already knew the post, then it won't be displayed to you again.

**Comment by MrPetovan** [comment]
It's perfect.

**Comment by MrPetovan** [comment]
Closed by #7348
