### ISSUE TITLE
Worker Syntax Error

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#7364]
After upgrading to 2019.06 on a Dreamhost server, I'm getting this error persistently from my cron:

`PHP Parse error:  syntax error, unexpected '?' in /include/text.php on line 189`

I've checked and double checked that the PHP version for the cron is 7.2.19.

Do I need to configure something else to enable the Null Coalescing Operator?

**Comment by miqrogroove** [comment]
Is there any chance the worker is spawning other processes with the wrong PHP version?

**Comment by miqrogroove** [comment]
I think I have a solution for this host.  The old cron command looks like this:

```
php -f /bin/worker.php
```

The new cron command needs this:

```
export PATH=/usr/local/php72/bin:$PATH
php -f /bin/worker.php
```

Whereas this will not work at all:

```
/usr/local/php72/bin/php -f /bin/worker.php
```

**Comment by MrPetovan** [comment]
The null coalescing operator has been introduced in PHP 7.0, so it is possible that a lingering PHP 5.6 version is running the cronjobs.

Without fiddling with your environment variable, this cron command should work:

```
cd /home/user/domain/ && /usr/local/php72/bin/php bin/worker.php
```
