### ISSUE TITLE
All Non-Public Posts Missing After 2019.06 Upgrade

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#7365]
After pulling 2019.06, my test user reported that none of my friends-only posts or photos are showing up on any page.

I tried sharing a new post with a single group and it never showed up.  I might be the only person who can see my new post.

**Comment by miqrogroove** [comment]
I created a new test account, added a mutual friendship, even tried yet another test post.  Verified Friends-only posts are not visible to anyone other than myself.

I am deleting my Friendica node today.  This software has been so dysfunctional that I've never been able to share simple messages or photos with my friends.

**Comment by MrPetovan** [comment]
I'm sorry to see you go but I understand your decision!
