### ISSUE TITLE
Changed font for posts and comments

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7369]
Somebody changed the font to a serif font for the input fields (e.g. posts and comments)
![00_temp](https://user-images.githubusercontent.com/24474762/61136381-10d4e600-a4b3-11e9-90ac-a20e8bbb1e4c.png)

It seems to bee every editable field inclusively pulldown menus/lists

### Friendica version you encountered the problem
latest develop, git, mariadb , php7.2

**Comment by MrPetovan** [comment]
I can't reproduce this. We haven't changed any font in any stylesheet recently. Can you inspect the textarea element in the Developer Console to see where the font comes from?

**Comment by AlfredSK** [comment]
Hmm. Most likely that can be caused by the browser's font settings.

**Comment by hoergen** [comment]
Hmm the only thing that maybe changed (I don't know exactly) is a new versoin of firefox. Everything else didn't change for weeks.
I tested it with chromium and there everything is ok. Very strange.
Thanks for the feedback. I close this issue.

**Comment by hoergen** [comment]
Just for info. I had to start with a fresh firefox profile to restore to get rid of the font problem.
It didn't help to deactivate all addons. I am really wondering what happened that changed the font setting.

**Comment by MrPetovan** [comment]
Very weird, sorry you had to go through that.

**Comment by AlfredSK** [comment]
My second thought was either something is blocking the use of the webfonts and system default fonts are used or the FF setting "Seiten das Verwenden von eigenen statt der oben gewählten Schriftarten erlauben" is not enabled (sorry for the German).

**Comment by hoergen** [comment]
@AlfredSK that was the first thing i checked and experimented with it. And btw your german is excellent ;)))
