### ISSUE TITLE
Blocklist - Sperrliste

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7370]
On the admin panel (english language) the widget "Tools" look like
![00_temp](https://user-images.githubusercontent.com/24474762/61136791-c142ea00-a4b3-11e9-8bd7-c7e1de791a2d.png)

in german there is the word "Blockliste" and "Sperrliste". I think we should use on both "Blockliste" as this is the common word people start searching on, when they want to block an account.

![01_temp](https://user-images.githubusercontent.com/24474762/61136963-0ebf5700-a4b4-11e9-8dd6-acd2ff838c46.png)

### Friendica version you encountered the problem
latest develop, git, MariaDB, PHP 7.2

**Comment by MrPetovan** [comment]
The translations are defined at Transifex: https://www.transifex.com/Friendica/friendica/

**Comment by hoergen** [comment]
I don't know how to find that text snippet  on Transifex and correct it.
