### ISSUE TITLE
[2019.06] PHP Warning: file_get_contents(/proc/meminfo): failed to open stream

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7375]
`PHP Warning:  file_get_contents(/proc/meminfo): failed to open stream: No such file or directory in /friendica/src/App.php on line 707`

**Comment by tobiasd** [comment]
part of #7298

**Comment by MrPetovan** [comment]
This is an odd one. We check that `/proc/meminfo` exists and is readable with `is_readable()` before attempting to retrieve its content with `file_get_contents()`, but apparently the existence and readability check succeeded in your case?

**Comment by MrPetovan** [comment]
Did this warning come up again?
