### ISSUE TITLE
Addons and connectors completely disabled

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7383]
After my last git pull this morning, all Addons and connectors are disabled and can't be activated again.

### Friendica version you encountered the problem
git, Develop, MariDB, PHP7.2

**Comment by nupplaphil** [comment]
Confirmed on local node
Caused by #7372 
Should be fixed by #7384

**Comment by nupplaphil** [comment]
@hoergen does it work again?
I've the fear that you do have to re-enable all addons & connectors again. Big sorry for that!

**Comment by hoergen** [comment]
It works again and as you said all addons had to be activated again. But fortunately all configurations are still there 👍
