### ISSUE TITLE
Performing real reshares

### ISSUE THREAD

**Issue by annando** [friendica/friendica#7393]
Currently our reshares are some real ugly workaround. We open the editor and display this ugly accumulation of some weird BBCode stuff. (And yes, I can mock about it, since I'm responsible for that :grinning:)

I would like to now split the mechanism in two slightly different actions. One will be "quote" which would (at first) react like the existing reshare, means that you can add your own comment to it. In some following step we should then only allow the comment to be added without being able to modify the original post. This is something for frontend people.

The second one will be "reshare" which will only do exactly this. Means: Pressing "reshare" on a post will immediately send a reshare message through the net. (Just like on any other software out there)

There will only be some small differences in behaviour: When done on a post from the ActivityPub universe, it will send the AP "Announce" message - and it will send it only to the AP world. When done on a post from Diaspora, it will only send the corresponding command from the Diaspora world. Reshares on DFRN will be treated like AP. 

Reshare will not leave their universe. This is due to the different ways that these mechanisms do work on AP and Diaspora. On AP a reshare is just another activity that is mostly comparable to a "like". It doesn't generate a new message, it just sends out the activity that a person shared some post. Means: When you comment on some reshared message, this comment will reach the original post.

On Diaspora however the reshare creates a brand new post with a brand new GUID with a completely separate comment thread.

Since both Diaspora and AP require the original post to exist in their very own universe, we cannot reshare a Diaspora post to AP and vice versa.

Question now is: Do you like this idea? And if yes, I really would be pleased if someone could help me in the frontend stuff.

**Comment by foss-** [comment]
This!
Note sure if this is a good time to also consider another aspect of reshares, or maybe that should be another GitHub issue: resharing a commented post including the comment? Twitter does this by default iirc. Often I want to reshare the post including the comment from one of the people I follow, but on friendica only the original post is reshared, which in many occasions I do not want to share without the added perspective of the person who commencted on it.

**Comment by annando** [comment]
We now do have these real reshares, so I close this issue.
