### ISSUE TITLE
Use server theme for new users works but with a minor problem

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7397]
This is a follow up for #7378

### Expected behavior
If the servers theme is e.g. frio then it should also show up as current theme in the user settings of a **new** user.

### Actual behavior
If a **new** user registers an account and logs in for the first time everything looks right. The defined node theme and the defined custom color scheme of the server is successfully applied as initial user theme and color scheme. The display is OK.
But when the user looks at the settings -> display -> general theme settings the user will find 'duepuntozero' listed as the active theme. And the user cannot open the accordion 'custom theme settings' - possibly because 'duepuntozero' doesn't have custom theme settings.

### Steps to reproduce the problem
Enable all available standard themes. Set your server's theme to frio and define a custom color scheme for the node. Then register a **new** user account and check the user's display settings.

![grafik](https://user-images.githubusercontent.com/3656054/61396145-5c2e3080-a8c7-11e9-96ce-96cd08170b7f.png)

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
That's a funny one too. Should we display the node theme settings as the user's if they didn't set it yet? This can apply to the them, but to the theme customization as well.

**Comment by AlfredSK** [comment]
I would expect that the user settings are equal to the node settings (including the color scheme values). But at least it should show the right theme as the active one.

**Comment by MrPetovan** [comment]
Alright, after perusing the code, it's clear we weren't using the node values for displaying custom theme settings to new users, but we are supposed to show the node theme for new users.

I also found out you can force enable a theme that wasn't enabled by the admin simply by mentioning it when submitting your display settings. Granted, it takes a little bit of finesse (adding the missing option in the theme select list through the Developer Console) but man oh man this is bad.
