### ISSUE TITLE
Unmentionable and unselectable contacts after failed probe

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#7408]
### Expected behavior
If I write a posting I want to be able to decide with whom I share my content.

### Actual behavior
If friendica probes contacts and a such a probe fails for some reason then these contacts get unmentionable and unselectable in the post permission settings and sometimes this really causes problems. Currently I can't set post permissions for several contacts because they have been marked as failed, but I know that they are there and active and at least I want to decide with whom I want to share my postings independently from the result of the last probe. Now I can't do anything else than to wait until they system probes those active contacts again and then hopefully with success, so that I can give those contacts again post permissions as I think.

### Steps to reproduce the problem
I don't know what's really needed to make friendica think that a probe of contacts failed even if those contacts are active.

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.09-dev - 1319 

### Friendica source (git, zip)
git
### PHP version
7.3.6
### SQL version
15.1 distrib 10.2.22-mariadb

**Comment by MrPetovan** [comment]
Technical details: A regex grep on `` `success_update` >=? `failure_update` `` shows the infamous condition used in
- `mod/acl.php` (governs mentions and ACL auto-completion)
- `mod/poco.php` (?)
- `src/Content/ForumManager.php` where it is used to hide forums, nicely tying this issue with #7057

The problem with this condition is that it is silent: the contact disappears from auto-complete (and network forum aside) lists without the user knowing when or why. And manually re-fetching the contact doesn't seem to update the `success_update` field even if the user knew that some contacts disappeared.

We already have an archive feature for contact who go for too long without a successful probe, what is the purpose of this confusing contact hiding condition?

**Comment by annando** [comment]
In ```mod/poco.php``` I think it is okay. ```poco``` is simply publishing some vital contacts. The other ones can surely be changed to ```archive``` I think.

**Comment by MrPetovan** [comment]
Ok.
