### ISSUE TITLE
Problem mit Foren auf der gleichen Instanz

### ISSUE THREAD

**Issue by michip21** [friendica/friendica#7418]
### Expected behavior
Posts in ein Forum werden von allen Forenteilnehmer gesehen.

### Actual behavior
Siehe Post https://f.praschnig.com/display/b8c357bb-145d-3571-40dd-1dd570876714
Problem tritt bei öffentlichen und privaten Foren auf.

### Steps to reproduce the problem
User A und Forum Z sind auf der gleichen Instanz beheimatet. User A sieht im Forum nur die eigenen Posts, andere werden nicht angezeigt. Das selbe bei User B (ebenfalls gleiche Instanz).
User B ist auf einer anderen Instanz angemeldet. Bei ihm werden alle Posts im Forum Z angezeigt.
English:
User A and Forum Z are based on the same instance. User A sees in the forum only their own posts, others are not displayed. The same for User B (same instance as well).
User B is logged in on another instance. With him all posts in the forum Z are indicated.

### Friendica version you encountered the problem
2019.06 - 1313

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
MariaDB 5.5.5

**Comment by MrPetovan** [comment]
Hi and thank you for your report! Unfortunately, not everyone in the Friendica team can read German fluently, so if you have any proficiency in English, it could improve the response rate on your issue.

**Comment by michip21** [comment]
Hi, yes I know. But my english is very bad. So I can only translate with google-translate:
My problem translated into English:
User A and Forum Z are based on the same instance. User A sees in the forum only their own posts, others are not displayed. The same for User B (same instance as well).
User B is logged in on another instance. With him all posts in the forum Z are indicated.

**Comment by hoergen** [comment]
I noticed the same problem. i'm owning the musicproduction forum https://horche.demkontinuum.de/profile/klangwerk . It only shows my forum posts, but not other forum posts. I can see other forum posts in my personal users timeline. But when i try to see the forum (clicking on the forums name on the widget) I only see my posts.

Another problem occured, when I was clicking to open the forums profile. The redir is leading to a wrong location ?

The redir URL is https://horche.demkontinuum.de/redir/65766
and it  leading to https://horche.demkontinuum.de/profile/klangwerk?f=&f=&redir=1 and the error message in the browser is

> The page isn’t redirecting properly
> An error occurred during a connection to horche.demkontinuum.de.
>     This problem can sometimes be caused by disabling or refusing to accept cookies.

I disabled every firefox plugin for that page and still get this error message. As well I tried it with Chromium (without plugins) and the same happened.

**Comment by hoergen** [comment]
ping? :) The Forums are not really usable at the moment and I would suggest we need to investigate to find a solution for 2019.12 ?

**Comment by hoergen** [comment]
Since todays pull I (normal user) don't see newly published posts on my local forum, that I posted with the forum account. Not in my normal users timeline and not by opening the forum.

**Comment by hoergen** [comment]
Did you change something? I see a forum post as user in my user timeline I did today  with my forum account.

**Comment by AlfredSK** [comment]
Probably the contact has been updated (and converted back from AP to DFRN).
