### ISSUE TITLE
Multiple contact requests

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#7422]
### Expected behavior
If a user requests to be a contact multiple time it should not create multiple requests. 

### Actual behavior
It creates multiple contacts requests. 

### Steps to reproduce the problem
Not sure. 

### Friendica version you encountered the problem
Latest develop, state 23.07.2019.

### Friendica source (git, zip)
git

See picture of multiple contact requests from same account:

![image](https://user-images.githubusercontent.com/8361662/61718574-8f5b3e80-ad63-11e9-9a0c-170bf09612f5.png)

Stragely the profile URL in the contact request is a RSS: 
![image](https://user-images.githubusercontent.com/8361662/61718623-a732c280-ad63-11e9-85e8-968249499b06.png)

**Comment by hoergen** [comment]
I remember this issue, but it seems to be fixed, isn't it?

**Comment by utzer** [comment]
Yes and I don't remember the issue. :-P

**Comment by hoergen** [comment]
Ok, then I'll close this issue. Thank you :+1:
