### ISSUE TITLE
[Blocked] Diaspora: Receiving chevron-containing body breaks display

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7433]
## Additional newlines

Diaspora side: https://diaspora.kapper.net/posts/1816752#df609e90920e01372f02558e28f9c4e5
Firendica side: https://friendica.mrpetovan.com/display/df609e90920e01372f02558e28f9c4e5

## Stripped content

Diaspora side: https://diaspora.kapper.net/posts/1816752#bfd0e9b0920f01372f02558e28f9c4e5
Friendica side: https://friendica.mrpetovan.com/display/bfd0e9b0920f01372f02558e28f9c4e5

**Comment by MrPetovan** [comment]
Oof, this one's a doozy. Since we're receiving Diaspora message in XML, we decode entities in message bodies on reception.

The source message is:

```xml
<comment>
  ...
  <text>I prefer to think of a website as a book - on the home page(=cover) the &lt;h1&gt; is the name of the website
on the other pages (=chapter) the current page title is the &lt;h1&gt; and the name of the website is at the pageheader as an &lt;h2&gt; or normal paragraph (but still on first position)
...</text>
  ...
</comment>
```

The resulting message body is 
```
I prefer to think of a website as a book - on the home page(=cover) the <h1> is the name of the website
on the other pages (=chapter) the current page title is the <h1> and the name of the website is at the pageheader as an <h2> or normal paragraph (but still on first position)
...
```

However, there are three problems:
- Markdown accepts HTML tags.
- Header tags (h1, h2, ...) are block-level.
- These literal tags aren't matched.

All of these trigger the parser to escape the first character of the unmatched tags to prevent infinite loop and put it on its own block since it's supposed to be a block-level tag.

What Diaspora should have sent is this: 

```xml
<comment>
  ...
  <text>I prefer to think of a website as a book - on the home page(=cover) the &amp;lt;h1&amp;gt; is the name of the website
on the other pages (=chapter) the current page title is the &amp;lt;h1&amp;gt; and the name of the website is at the pageheader as an &amp;lt;h2&amp;gt; or normal paragraph (but still on first position)
...</text>
  ...
</comment>
```

Where the chevrons are double-encoded, which yields encoded chevrons on message reception and gives the correct display in Friendica.

**Comment by MrPetovan** [comment]
Blocked by https://github.com/diaspora/diaspora/issues/8047

**Comment by annando** [comment]
I just did some small tests. Indeed Diaspora is sending these elements unescaped. They do rely on their Markdown parser that is parsing HTML elements only when the element is not only opened but also closed. A single ```<h1>``` or ```</b>``` in the text is encoded, but when you use both (like ```<h1>Test</h1>``` then the parser treats this element like the H1 header.

**Comment by MrPetovan** [comment]
This looks like a case where different Markdown parsers are behaving differently from each other. The CommonMark spec isn't clear about unbalanced block-level HTML tags in paragraphs, so results are inconsistent among parsers.
