### ISSUE TITLE
PHP Notice on stable

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7439]
`PHP Notice:  Undefined index: nickname in /friendica/addon/twitter/twitter.php on line 1887`

**Comment by MrPetovan** [comment]
Please use the dedicated master issue for reporting notices, warnings and fatal errors:
- Notices: https://github.com/friendica/friendica/issues/7299
- Warnings: https://github.com/friendica/friendica/issues/7298
- Fatal errors: https://github.com/friendica/friendica/issues/7297
