### ISSUE TITLE
Simple postings should not be displayed as reshares.

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#7454]
### Expected behavior
<s>If I reshare a posting by my contacts I expect that friendica displays that I have reshared this from a contact.</s>

If I submit a posting it should be diplayed as simple posting and not as reshare of a posting from myself. Please check the screenshot in my comment below.

### Actual behavior
<s>Reshares show up like if I reshared the posting from myself, but also mixed up with doubled profile picture of myself and a profile picture of my contact.</s>

Every posting I submit is displayed as reshare.

### Steps to reproduce the problem
<s>Simply reshare a posting.</s>

I just have to submit a posting.

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.09-dev - 1320 

### Friendica source (git, zip)
git

### PHP version
7.3.7

### SQL version
mysql Ver 15.1 Distrib 10.2.22-MariaDB

**Comment by annando** [comment]
Reshares currently are a PITA. From our side it's a fragile construct. That was the reason that I wanted to split the single reshare functionality into two separate functions, one for a plain reshare and one for a quoted reshare. See the discussion here: https://forum.friendi.ca/display/ec054ce7-665d-2e3d-ca27-f02780441596

I have to check if I can reproduce the issue.

**Comment by rebeka-catalina** [comment]
Reshare without actually resharing?? If just submitted a posting... not a reshare, but friendica creates a reshare?! o.O
![reshare-2](https://user-images.githubusercontent.com/7385838/62289596-66236800-b45f-11e9-973a-020068244d0d.jpg)

**Comment by rebeka-catalina** [comment]
And my postings aren't distributed.

**Comment by MrPetovan** [comment]
I feel like this has to do with the contact ID shenanigans from yesterday, I've seen another similar account: https://forum.friendi.ca/display/0b6b25a8-965d-42f0-dd53-0d8362316621

**Comment by rebeka-catalina** [comment]
In my friendica.log there is this error message a few thousand times
``2019-08-01 14:29:56 worker [ERROR]: Error(s) while parsing XML string. {"callstack":"Probe::hostMeta, Probe::detect, Probe::uri, Contact::updateFromProbe","worker_id":"aa943d3","worker_cmd":"UpdateContact"} - {"file":"XML.php","line":426,"function":"parseString","uid":"eed423","process_id":2321}
``

**Comment by rebeka-catalina** [comment]
Yes that's the same issue. Also my postings don't appear on my profile page - only on /network

**Comment by MrPetovan** [comment]
This means Friendica can't link these posts to your profile, probably because the `contact-id` field for these items isn't your self-contact anymore.

**Comment by annando** [comment]
@rebeka-catalina the XML error is unrelated.

**Comment by annando** [comment]
@MrPetovan I guess we have to check not only for being a follower, but also for being the "self" contact. I'm currently fighting with massive database issues ("Lock wait timeout exceeded; try restarting transaction"), so I have to stabilize my system first before doing any bug fixing.

**Comment by MrPetovan** [comment]
I'm reverting your changes in the meantime since there's no fix in sight and it massively affect develop.

**Comment by MrPetovan** [comment]
Probably caused by #7452

**Comment by MrPetovan** [comment]
Should be fixed with the revert #7455 , please confirm.

**Comment by rebeka-catalina** [comment]
> Should be fixed with the revert #7455 , please confirm.

Confirmed. Thank you :-)
