### ISSUE TITLE
Pictures uploaded to post have wrong permission

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#7456]
### Expected behavior
When a picture is uploaded to a post it should inherit the permission of the post. 

### Actual behavior
The new picture will be private only. 

### Steps to reproduce the problem
Start new post, add new picture (upload one). 

### Friendica version you encountered the problem
Latest develop version. 

### Friendica source (git, zip)
git

**Comment by MrPetovan** [comment]
This doesn't seem to affect comments.

**Comment by annando** [comment]
I already have got a fix. PR will come this evening.

**Comment by ben-utzer** [comment]
For me it affected comments too.
