### ISSUE TITLE
Wrong notification text on reshares

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7467]
### Expected behavior
When someone re-shared one of my posts the notification should say 'X re-shared your post'.

### Actual behavior
When someone re-shared one of my posts the notification says 'X _commented_ on your post'
This is confusing because there is no new comment.

### Steps to reproduce the problem
When someone re-shared one of your posts look at the notification text.

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by annando** [comment]
You currently get a notification when someone reshares your messages? Do you also get notifications for likes?

**Comment by AlfredSK** [comment]
Yes and no.

**Comment by MrPetovan** [comment]
I've never had notifications for reshares.

**Comment by AlfredSK** [comment]
Well it doesn't say 'reshare'. It says 'commented on'. But when you follow the notification link there is no comment but a new re-share.

**Comment by AlfredSK** [comment]
I think this one was also fixed magically by one of the latest PRs that changed the contact-id stuff.
I did not get a notification for a new comment when someone reshared a post of mine.

**Comment by AlfredSK** [comment]
OK. I waited another 5 days. Didn't reoccur. Closing.
