### ISSUE TITLE
Starring and saving should be possible for all posts/items

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7469]
### Expected behavior
Adding a star (starring) and saving an item to a folder should always be possible no matter if I follow the author or not.

### Actual behavior
It is only possible for items from contacts. It isn't possible with items I get via followed hashtags or for random posts on e.g. the community pages. This is somehow inconsistent and confusing.

### Steps to reproduce the problem
Look for a post you got via a followed hashtag from a stranger. Try to add a star or try to save it to a folder.

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
For next time:
- Staring (pronounced "Stair-ing"): Look intensely
- Star**r**ing (pronounced "Star-ing"): Add a star

😉

Back to the issue at hand, I believe this is because of the separation between public post (uid=0) and your own copy of a public post (uid=yours) that you can't star or save them. Otherwise you would star or save it for everyone getting the item from a hashtag search as well.

**Comment by AlfredSK** [comment]
I'll remember that. ⭐

**Comment by annando** [comment]
I guess I will staring at the starring. 😀 

We had to store that value in the ```user-item``` table and not the ```item``` table as we are doing right now. Technically this is possible. But it's not a bug since it was never expected to work that way.

**Comment by AlfredSK** [comment]
@helucht Can we add this to the next release? Is it much work? What do you think?

**Comment by AlfredSK** [comment]
@annando Can we add this to the next release? Is it much work? What do you think?

**Comment by annando** [comment]
Starring would be a much easier task than saving into folders. But it still is some work.

**Comment by AlfredSK** [comment]
I'm not sure. But something is weird here. :-) Could be another issue...

I do follow someone. I *cannot* add a star or save to folder when I see a post of them on **community page**. But I *can* add a star or save the item to a folder when I see the very same post on `/network` or `/display`.

Is this a bug or a missing feature? I think this had worked in the past. But I'm not sure.

**Comment by MrPetovan** [comment]
It probably comes from the different display.

**Comment by annando** [comment]
@AlfredSK it is not a bug. It is something that we can address now with the new post tables.

**Comment by AlfredSK** [comment]
Looks like this is solved. When I check random posts on my community pages I can add a star and save items to a folder now. Closing?
