### ISSUE TITLE
Trending hashtags feature

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7473]
### Expected behavior
Hashtags are useful. But the discovery of interesting topics/hashtags isn't easy. Would be cool if we would have some kind of trending hashtags feature. See Twitter. :-)

I don't know if this is actually possible in a distributed network and I don't know if we have the necessary data in our database. It's just an idea I would like to see as a Friendica feature.

### Friendica version you encountered the "problem"
2019.09-dev

**Comment by MrPetovan** [comment]
Trending anything is just "this thing was the most frequent among all the posts in the last 24 hours" so we do have this information.

The query would look like this:

```sql
SELECT t.`term`, COUNT(*) AS `score`
FROM `term` t
JOIN `item` i ON t.oid = i.`id`
WHERE t.uid = 0
AND t.otype = 1
AND t.type = 1
AND i.uid = 0
GROUP BY `term`
ORDER BY `score` DESC
LIMIT 10
```
(Warning, it takes 26 seconds on my node with 1,000,000 terms and 1,000,000 items)

**Comment by AlfredSK** [comment]
Cool. Could indices speed this up?

**Comment by MrPetovan** [comment]
Actually, limiting items to received in the last 24 hours speeds up the query under a second.

**Comment by AlfredSK** [comment]
Here: 10 rows in set (22.91 sec)
And I just found out that 'sexy' is trending. :-)

**Comment by MrPetovan** [comment]
Please try the updated version.

**Comment by AlfredSK** [comment]
10 rows in set (0.08 sec)

**Comment by MrPetovan** [comment]
Here you go, fresh, accurate trending hashtags served in a record time. I'm not even sure about the background process anymore. Should this list be an aside in community pages? With a distinction between local trending and federation-wide trending?

**Comment by AlfredSK** [comment]
Hmm. Is this a core feature or an additional setting?
I'd like to see that as widget on the /network page. You have your own followed hashtags there. So it makes sense to have the trending hashtags there as well. But this page is already pretty crowded with side widgets. :-)
Let's see what others think about it.

**Comment by MrPetovan** [comment]
I think it should be an additional feature protected behind the site and user switch because it isn't core to our business and can be gamed into an upsetting/harassment tool.

**Comment by annando** [comment]
@MrPetovan you don't need the item table. The term table also holds the ```received``` field:
```SELECT `term`, COUNT(*) AS `score` FROM `term` WHERE `uid` = 0 AND `otype` = 1 AND `type` = 1 AND `term` != '' AND `received` > DATE_SUB(NOW(), INTERVAL 1 DAY) GROUP BY `term` ORDER BY `score` DESC LIMIT 10;```

BTW: Here it is:
```
+-------------+-------+
| term        | score |
+-------------+-------+
| caturday    |    31 |
| Politik     |    28 |
| usa         |    23 |
| photo       |    18 |
| bot         |    17 |
| ElPaso      |    16 |
| Health      |    15 |
| GIF         |    14 |
| mywork      |    14 |
| Environment |    14 |
+-------------+-------+
```

**Comment by MrPetovan** [comment]
This query takes 4 seconds while mine takes 400ms, something afoot with indices.

**Comment by MrPetovan** [comment]
My list is different from yours:
```
Health
Environment
Steve
caturday
Music
photo
Technology
gif
bot
Nantes
```
(Steve was a French partygoer who was pushed into the river in Nantes by a police charge because the party was off-hours and whose body has just been found)

**Comment by AlfredSK** [comment]
> With a distinction between local trending and federation-wide trending?

For me it would be sufficient to have a global list.

**Comment by annando** [comment]
Concerning the query speed: I think adding an index is better than doing a complex query.

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> SELECT `term`, COUNT(*) AS `score` FROM `term` WHERE `uid` = 0 AND `otype` = 1 AND `type` = 1 AND `term` != '' AND `received` > DATE_SUB(NOW(), INTERVAL 1 DAY) GROUP BY `term` ORDER BY `score` DESC LIMIT 10;
+-----------+-------+
| term      | score |
+-----------+-------+
| nsfw      |   236 |
| bot       |   223 |
| politics  |   135 |
| news      |   103 |
| linux     |    97 |
| sexy      |    84 |
| girls     |    83 |
| abyss_fun |    80 |
| Photo     |    72 |
| USA       |    64 |
+-----------+-------+
10 rows in set (4.02 sec)
```

Ähem. A lot of nsfw stuff here. :-)

**Comment by annando** [comment]
No cats!

**Comment by MrPetovan** [comment]
> Concerning the query speed: I think adding an index is better than doing a complex query.

I trust you on that, I'm guessing it consumes more disk space overall but less memory during execution?

**Comment by annando** [comment]
I guess that the disk space thing won't be that bad. But anyway I want to rework the whole hash tag stuff anyway. We don't need to store this per user. We only need to store this per unique item. (comparable to the "item-content" table) This of course would reduce disk space as well.

**Comment by MrPetovan** [comment]
I'm probably going to take a first pass at it with my own query, when you finally get around to do what you said, you'll be able to change it.

**Comment by MrPetovan** [comment]
@AlfredSK Please give it a stab, I'm impatient to know if it matches your expectations!

**Comment by AlfredSK** [comment]
Yep. I just came home. Give me a minute, please. :-)

**Comment by MrPetovan** [comment]
No minutes for you!

**Comment by AlfredSK** [comment]
Well...

![image](https://user-images.githubusercontent.com/3656054/62554283-24d0f500-b871-11e9-9cc3-93b2f4d97524.png)

**Comment by MrPetovan** [comment]
Any SQL error in the log?

**Comment by MrPetovan** [comment]
What happens if you run this query directly?
```sql
                                 SELECT t.`term`, COUNT(*) AS `score`
				FROM `term` t
				 JOIN `item` i ON i.`id` = t.`oid` AND i.`uid` = t.`uid`
				 JOIN `thread` ON `thread`.`iid` = i.`id`
				WHERE `thread`.`visible`
				  AND NOT `thread`.`deleted`
				  AND NOT `thread`.`moderated`
				  AND NOT `thread`.`private`
				  AND t.`uid` = 0
				  AND t.`otype` = 1
				  AND t.`type` = 1
				  AND t.`term` != ''
				  AND i.`received` > DATE_SUB(NOW(), INTERVAL 24 HOUR)
				GROUP BY `term`
				ORDER BY `score` DESC
				LIMIT 20
```

**Comment by AlfredSK** [comment]
No SQL errors found. Just some xml errors. But these are related to UpdateContact. Also no PHP errors.
Will run the query by hand now...

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> SELECT t.`term`, COUNT(*) AS `score` FROM `term` t  JOIN `item` i ON i.`id` = t.`oid` AND i.`uid` = t.`uid`  JOIN `thread` ON `thread`.`iid` = i.`id` WHERE `thread`.`visible`   AND NOT `thread`.`deleted`   AND NOT `thread`.`moderated`   AND NOT `thread`.`private`   AND t.`uid` = 0   AND t.`otype` = 1   AND t.`type` = 1   AND t.`term` != ''   AND i.`received` > DATE_SUB(NOW(), INTERVAL 24 HOUR) GROUP BY `term` ORDER BY `score` DESC LIMIT 20;
+-----------------+-------+
| term            | score |
+-----------------+-------+
| bot             |   299 |
| news            |   187 |
| nsfw            |   157 |
| Politics        |   153 |
| Linux           |   137 |
| Microsoft       |   110 |
| USA             |    89 |
| ElPaso          |    87 |
| entempsrealepa  |    81 |
| abyss_fun       |    76 |
| technology      |    76 |
| Worldnews       |    75 |
| Trump           |    74 |
| art             |    68 |
| featuredstories |    66 |
| gnu             |    66 |
| SCIENCE         |    63 |
| donaldtrump     |    61 |
| NDR             |    59 |
| mastoart        |    57 |
+-----------------+-------+
20 rows in set (0.12 sec)
```

**Comment by AlfredSK** [comment]
To find a possible SQL error, is it enough to set log level to INFO and grep for 'sql'?

**Comment by MrPetovan** [comment]
Well, I'm puzzled. Could be a cache issue. I'll do more tests tonight EST.

**Comment by AlfredSK** [comment]
Summary of observation:

- found no SQL error
- found no PHP error
- found no other related error in Friendica log
- found no related error in my browser console

Looks like the code is absolutely perfect. It simply doesn't show the tags. :-)

**Comment by AlfredSK** [comment]
Because you mentioned 'cache issue': I'm using Redis as session storage and cache driver.

**Comment by MrPetovan** [comment]
What about now @AlfredSK ?

**Comment by AlfredSK** [comment]
![Screenshot_20190807-073332](https://user-images.githubusercontent.com/3656054/62609079-627d5e80-b901-11e9-86b5-f66e89949643.jpg)

**Comment by MrPetovan** [comment]
Perfect, thanks.
