### ISSUE TITLE
[Critical] Unescaped username in hovercard trigger XSS test

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7494]
See https://friendica.mrpetovan.com/display/962c3e10205b6ac99275589025082085

> Beim hovern über Nutzernamen werden etwaige script-Tags im Namen ausgeführt. Könnte vielleicht problematisch sein. Und ist es insofern auf jeden Fall, da es das Nutzerinfo-Popup verhindert.

**Comment by MrPetovan** [comment]
I did some cursory test, and I wasn't able to set a XSS username from the admin user add form or the setting username change form. Maybe it was set through the API?

**Comment by AlfredSK** [comment]
Did you see the date of that post? 😱 😆

**Comment by MrPetovan** [comment]
No 😖
