### ISSUE TITLE
Exclusive forum posts broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7497]
### Expected behavior
When I compose a forum posts with a `!-mention` that post should be an exclusive forum post. It should only be delivered to the forum and the forum should distribute the post to its members.
Also those posts should be displayed when I filter my network stream via the 'Forums' network filter/widget.

### Actual behavior
When I compose a forum posts with a `!-mention` that post looks like a normal public post (but with 'X shared via Y' in the top line of the post). It is delivered to - in my case - 449 servers.
The post doesn't appear in the network stream of the forum account when I select the forum in the 'Forums' widget.

### Steps to reproduce the problem
Create a forum post with a `!-mention`. Look at the delivery counter (paperplane). Click on the forum link in the left side 'Forums' widget.

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
The discovery:
https://forum.friendi.ca/display/0b6b25a8-165d-4e8a-b1c0-b37970218061

**Comment by tobiasd** [comment]
I cannot reproduce this with the current development code. Over the last couple of days I created postings for forums that only got the forum server as delivery count. How do you compose the new posting? I'm using the vier theme and local creation in `/network` or the dedicated forum streams works as expected.

**Comment by AlfredSK** [comment]
I would say it is fixed by one of the latest PRs touching the contact-id, author, owner stuff. Maybe PR #7512.
