### ISSUE TITLE
Replace "Share" icon?

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7522]
The "share" button is using the official logo of slideshare.com. I'm not sure if that's desired but even more I find the icon unclearly describing the feature of posting some content. Maybe it's better to replace it with some sending icon like the paperfold plane?

![image](https://user-images.githubusercontent.com/74432/63203731-c0444000-c091-11e9-9728-25bb494c4d72.png) vs. ![image](https://user-images.githubusercontent.com/74432/63203772-06010880-c092-11e9-8343-58b3feb16faf.png)

**Comment by MrPetovan** [comment]
Agreed.

**Comment by nupplaphil** [comment]
Fixed by #7525
