### ISSUE TITLE
Replace paper plane icon with check mark

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7527]
I think a check mark would be more intuitive for what the status is about:

![image](https://user-images.githubusercontent.com/74432/63215251-22e61c00-c124-11e9-95d0-d696313c7a7b.png) vs. ![image](https://user-images.githubusercontent.com/74432/63215257-37c2af80-c124-11e9-96ba-cb26781fe981.png)

**Comment by MrPetovan** [comment]
I disagree, this icon is about delivery, not about validation in general. Plus the delivery rarely completes because of unavailable remote hosts/contacts, so the check mark would virtually never appear.

**Comment by vinzv** [comment]
Looking at the respective template there are three usages for the paper plane:
1. delivery_underway
2. delivery_almost
3. delivery_done

I would only replace the last one. As it's not shown most of the time as you say it wouldn't hurt. Furthermore it would show that a process is really finished. People might recognize those mark(s) from messenger apps.

**Comment by MrPetovan** [comment]
Fair enough, please submit your PR for merge.

**Comment by MrPetovan** [comment]
Closed via #7529
