### ISSUE TITLE
Frio - Preview auto generation is broken

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7531]
### Expected behavior
Pasting an URL starts generation a preview (open graph)

### Actual behavior
Doesn't generate a preview aka nothing happens

### Steps to reproduce the problem
Paste an URL in a new post.

### Friendica version you encountered the problem
Developer - git - mariaDB - PHP7.2

**Comment by hoergen** [comment]
Ah ok .. it's only the automatic generation of the preview is switched off. And you have to do it the old way with clicking on the "attachement" button. That's good 👍

**Comment by MrPetovan** [comment]
The automatic generation of previews isn't switched off, it has been slightly limited to prevent inserted image tags from triggering a preview.

What are the exact steps you took not to get a preview?

**Comment by hoergen** [comment]
I like it that it is "switched" off, because it is limiting the user to edit the preview.
There were no other steps necessary than those i described above. Just did the paste.

**Comment by MrPetovan** [comment]
I understand that, but it isn't expected, I just pasted a URL into the post textarea of the compose page and was greeted with a link preview.

**Comment by hoergen** [comment]
So it is working for you? Did a pull some minutes ago and is (gladly) not working for me ;)

**Comment by MrPetovan** [comment]
Yes, it is still working for me, including after a cache clear since a Javascript file was modified.

**Comment by hoergen** [comment]
Ah ok could be that it is a cache problem. I love that problem in this case :)

**Comment by MrPetovan** [comment]
Duplicate of #7576
