### ISSUE TITLE
[Frio] Show notification icon in mobile view

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7536]
This is a followup to #6384 somehow, but for Frio. 
I think having the notification icon in the right slide-in menu is unnecessarily complex. Therefore it would be good to have it in the top bar as well. There is enough room to have it.

![image](https://user-images.githubusercontent.com/74432/63231057-340f5580-c216-11e9-976e-5d4bb60c251c.png) 
vs. 
![image](https://user-images.githubusercontent.com/74432/63231060-530de780-c216-11e9-9a15-f8c4f3e5454a.png)

The notification dropdown has enough room as well:

![image](https://user-images.githubusercontent.com/74432/63231073-8badc100-c216-11e9-9bed-713dec2b0352.png)

**Comment by AlfredSK** [comment]
I like the idea. But I never liked the icon. From my point of view it somehow doesn't match visually. Is there a good alternative in font awesome?

**Comment by MrPetovan** [comment]
The bell, probably? https://fontawesome.com/icons/bell?style=solid

**Comment by nupplaphil** [comment]
[x] vote for the bell ! :-)

**Comment by AlfredSK** [comment]
Bell is well. ;-)

**Comment by vinzv** [comment]
The bell would have been my first choice as well. I switched it.
![image](https://user-images.githubusercontent.com/74432/63279979-4509a680-c2aa-11e9-9822-77205f713a21.png)

**Comment by AlfredSK** [comment]
Looks much better! Thank you.

**Comment by nupplaphil** [comment]
Bell'ed by #7539
