### ISSUE TITLE
[Frio] Admin user icon is hard to recognize

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7542]
Looking at this icon I wouldn't have interpreted it as "admin". Even knowing it's intended as medical doctor I find it hard to recognize.

![image](https://user-images.githubusercontent.com/74432/63303865-620d9c00-c2e1-11e9-8941-ff33cfae8814.png)

Maybe we should switch it to something more intuitive and better distinguishable? 
Some proposals:

![image](https://user-images.githubusercontent.com/74432/63303897-7d78a700-c2e1-11e9-97e3-6b739917f8f7.png) ![image](https://user-images.githubusercontent.com/74432/63304106-2f17d800-c2e2-11e9-8145-c6618dcf91f2.png) ![image](https://user-images.githubusercontent.com/74432/63304129-4a82e300-c2e2-11e9-8671-013c831a7c94.png) ![image](https://user-images.githubusercontent.com/74432/63304171-756d3700-c2e2-11e9-88ce-1cd7a5cf1acc.png) ![image](https://user-images.githubusercontent.com/74432/63304341-f0cee880-c2e2-11e9-84a1-ffa40630b833.png) ![image](https://user-images.githubusercontent.com/74432/63304360-08a66c80-c2e3-11e9-8db8-b279e6a89a8a.png)

Any opinions?

**Comment by annando** [comment]
It should be the same icon like the link to the administration.

**Comment by MrPetovan** [comment]
The spy in fedora and trenchcoat?

**Comment by annando** [comment]
I just meant that - when we do change it - we should change it at the other place as well.

**Comment by vinzv** [comment]
So the spy icon is okay for you? Or should we streamline all admin icons to something completely different like in the examples above?
The spy is often used for anonymous usage, browser's privacy mode etc. So this might a bit confusing.

**Comment by MrPetovan** [comment]
I agree, we should replace it with something else like a monarchy crown maybe? The usual iconography is a person in a suit and tie but it is a little bit too gendered for my taste.

Wrench/tools can work too as well.

**Comment by vinzv** [comment]
There is a crown in FontAwesome but only from v5 upwards. We would need to migrate to this version first which is a separate task I guess.

As an intermediate solution we could use one of my proposals made earlier.

**Comment by MrPetovan** [comment]
The key could work as well, but I don't think the others are appropriate.

**Comment by AlfredSK** [comment]
Where is that icon anyway? I don't see it. I have the spy guy as admin icon.

**Comment by vinzv** [comment]
> Where is that icon anyway? I don't see it. I have the spy guy as admin icon.

It's at /admin/users

**Comment by nupplaphil** [comment]
Changed to spy Icon with #7549 :)
