### ISSUE TITLE
Hook disappeared

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7555]
There are no more hooks in the boxes. Side-effect of #7551
https://meld.de/photo/43861870545d5f9b8010f6f556879002

**Comment by nupplaphil** [comment]
Pinging @vinzv :)

**Comment by vinzv** [comment]
Can't reproduce, even directly on meld.de:
![image](https://user-images.githubusercontent.com/74432/63590034-f8281780-c5aa-11e9-852c-278bfc9fcabe.png)

**Comment by MrPetovan** [comment]
So it's a browser-OS specific issue?

**Comment by vinzv** [comment]
Hard to believe as then there would be other icons not working as well.
I tested with FF68 on Linux. What OS and Browser do you use, @copiis?

**Comment by MrPetovan** [comment]
Unicode support is variable between browsers/OSes.

**Comment by copiis** [comment]
> Hard to believe as then there would be other icons not working as well.
> I tested with FF68 on Linux. What OS and Browser do you use, @copiis?

Vivaldi.
Just cleared the cache and now I get an internal server error.
Is meld.de still available for you?

**Comment by vinzv** [comment]
Nope, internal error for me as well.

**Comment by copiis** [comment]
Okay, I was tampering with the .httaccess.
Does anyone have an original file?

**Comment by vinzv** [comment]
It's here: https://github.com/friendica/friendica/blob/develop/.htaccess-dist

**Comment by copiis** [comment]
Okay it was a cache problem
