### ISSUE TITLE
[Frio] Make forums widget less distracting

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7556]
I realized that the coloured icons of the forums widget keep distracting me while scrolling through the timeline. Not massively, just slightly but continously. Here's my proposal to remove that distraction in Frio:

![Screenshot_20190823_225508](https://user-images.githubusercontent.com/74432/63623306-8b883980-c5f9-11e9-8ef3-881cc6c7b852.png) ![Screenshot_20190823_225555](https://user-images.githubusercontent.com/74432/63623311-8f1bc080-c5f9-11e9-82fc-64649d81dba3.png)

Comments?

**Comment by nupplaphil** [comment]
Done with #7569
