### ISSUE TITLE
[Frio] Make post tags less distracting

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7557]
Same as in #7556 just for post tags in Frio: desaturate the tags and saturate them on hover.

![Screenshot_20190823_231857](https://user-images.githubusercontent.com/74432/63624432-955f6c00-c5fc-11e9-8b1d-805006b4b4ff.png) ⮕ ![Screenshot_20190823_231906](https://user-images.githubusercontent.com/74432/63624433-955f6c00-c5fc-11e9-8927-a9c98a5ce008.png)

And as a step further I'd like to discuss the usage of "#" and the flash. I understand the intention of both but think it's too much. As the hash symbol is more related to pure text I would prefer to use the flash on the button at start:

![image](https://user-images.githubusercontent.com/74432/63624551-0c950000-c5fd-11e9-9b0b-d0ee9665e8b0.png) vs. ![image](https://user-images.githubusercontent.com/74432/63624583-26cede00-c5fd-11e9-9943-5d608a419ba7.png)

What do you think?

**Comment by AlfredSK** [comment]
I'm not a huge fan. There are not only tags. There are also mentions and categories. If they're all colorless it would be hard to see the difference.

**Comment by vinzv** [comment]
Hm, you're right. Making this only for single buttons would make it more cluttered.
What about making the effect for the whole bar, similar to the like/dislike/comment section?

![Screenshot_20190824_005258](https://user-images.githubusercontent.com/74432/63627834-c1cdb500-c609-11e9-8fbf-aa0b8a0164c7.png)
⬇
![Screenshot_20190824_005314](https://user-images.githubusercontent.com/74432/63627839-c72aff80-c609-11e9-91b2-3fd2e9ae4269.png)

**Comment by annando** [comment]
What about not making them totally colourless, but just reduced colours?

**Comment by vinzv** [comment]
That's possible too. Two Variants:

50% grayscale

![Screenshot_20190824_153614](https://user-images.githubusercontent.com/74432/63638202-71943880-c685-11e9-853c-b86a4b9c6127.png)

50% grayscale + opacity reduced by 40%

![Screenshot_20190824_153731](https://user-images.githubusercontent.com/74432/63638204-7658ec80-c685-11e9-8a9b-1e64472b4968.png)

**Comment by AlfredSK** [comment]
Hmm. I'm not excited yet. ;-) How would it look without greyscaling, but only with some transparency?

**Comment by vinzv** [comment]
Half transparent (meaning 50% opacity):

![image](https://user-images.githubusercontent.com/74432/63640098-b081b880-c69c-11e9-9636-f951193fd2f4.png)

**Comment by AlfredSK** [comment]
Looks better. And on mouse-over it is shown w/o transparency?

**Comment by vinzv** [comment]
Yes, that's the plan for all variants (transparent, desaturated etc.). On mouse over both of the single buttons as well as on the whole bar everything get's fully colored:

![image](https://user-images.githubusercontent.com/74432/63640287-9f39ab80-c69e-11e9-95c5-05399d00c515.png)

![image](https://user-images.githubusercontent.com/74432/63640290-ab256d80-c69e-11e9-86d5-4b797c5c4076.png)

**Comment by Extarys** [comment]
Normal:
![image](https://user-images.githubusercontent.com/11581433/104748043-40575500-571f-11eb-8bd2-9b5cd92fd39d.png)

Hover:
![image](https://user-images.githubusercontent.com/11581433/104748117-55cc7f00-571f-11eb-86d3-d5d011a1c53f.png)

Opacity: 0.4
Grayscale: 0.2

I also increased the opacity of the action buttons from 0.3 to 0.4 to match. I find the tags too dim at 0.3 and I like consistency.

@MrPetovan What do you think?
EDIT: Maybe make tagged people a little more punchy :thinking: 

Opacity 0.6 for the mentions only, everything like above
![image](https://user-images.githubusercontent.com/11581433/104748924-3bdf6c00-5720-11eb-858b-0d1c90e2f1d4.png)

Opacity: 0.7 Grayscale 0.1 for the mentions only:
![image](https://user-images.githubusercontent.com/11581433/104749221-8d87f680-5720-11eb-958b-906e01457641.png)

Opacity: 0.8 Grayscale: 0.4 on all labels:
![image](https://user-images.githubusercontent.com/11581433/104749423-cde77480-5720-11eb-8fbe-61d571831de8.png)

I think the last one is a good compromise and make the tags easier to read without hovering the post.


And another one more gray
Grayscale: 0.6 Opacity: 0.8
![image](https://user-images.githubusercontent.com/11581433/104750266-d7251100-5721-11eb-87fc-f04ae280ea64.png)

**Comment by MrPetovan** [comment]
What's the grayscale value you're using?

**Comment by Extarys** [comment]
@MrPetovan Sorry refresh the page please, I made a lot of screenshots with all the values

**Comment by MrPetovan** [comment]
No, I mean, is it a CSS attribute?

**Comment by Extarys** [comment]
Yes it is. There you go:
```
 .wall-item-container .wall-item-bottom .wall-item-tags span.label {
        filter:grayscale(0.6);
        opacity: 0.8;

        -webkit-transition: all 0.25s ease-in-out;
		-moz-transition: all 0.25s ease-in-out;
		-o-transition: all 0.25s ease-in-out;
		-ms-transition: all 0.25s ease-in-out;
		transition: all 0.25s ease-in-out;
    }
```

**Comment by MrPetovan** [comment]
Thanks, how's the browser support?

**Comment by Extarys** [comment]
![image](https://user-images.githubusercontent.com/11581433/104753681-54eb1b80-5726-11eb-8d17-981629f24284.png)
I don't think it matter that much, as the filter won't be applied on unsupported browser and it's mainly an "eye candy". I wouldn't compare it to a feature that breaks and render a part of the app unresponsive or unusable on older browser.

**Comment by Extarys** [comment]
Wait, wrong filter, the previous one was for SVG.

![image](https://user-images.githubusercontent.com/11581433/104753976-b3b09500-5726-11eb-8eb8-9fe2d07d1876.png)

I'd say it's better :laughing:

**Comment by MrPetovan** [comment]
Excellent, it looks good technically, I'll leave other people the opportunity to comment on the aesthetics.

**Comment by annando** [comment]
I like that greyish look!

**Comment by Extarys** [comment]
@annando Thanks for commenting. You mean the last image with `Grayscale: 0.6 Opacity: 0.8` ?

**Comment by annando** [comment]
Yes

**Comment by AlfredSK** [comment]
Dunno. :-)

> Opacity: 0.8 Grayscale: 0.4

Seems to be not grey enough.

> Grayscale: 0.6 Opacity: 0.8

Seems to be too grey.

But maybe I just need to see it in action to decide which one looks better.

**Comment by Extarys** [comment]
@AlfredSK I guess `Opacity: 0.8 Grayscale: 0.5` which is in the middle of both. And we can test in the develop branch how you folks like it if it's what you are running. It's quite trivial to change so we can just do another PR along the way.

**Comment by Extarys** [comment]
Might revisit this when I tackle #9769 
Maybe explore with no fading black text in the post itself, etc. I'll discuss this on that specific issue when I get there :stuck_out_tongue:
