### ISSUE TITLE
Manage accounts by delegation is partly broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7558]
### Expected behavior
If I have configured a delegate* for an account and switch to the managed account I should really land in that account with the possibility to manage everything - except settings.

`*` - not the manage function by setting the same email, the other (cool) one. :-)

### Actual behavior
In current develop and rc it looks like I have switched successfully at first. But when I try to actually do something I notice that I'm still authenticated as my main user/account. After clicking on some menu the theme settings and everything doesn't match the settings of the managed account. Sometimes this happens directly after switching, sometimes it needs a page refresh. What I always see - when it doesn't work - is that the avatar and username doesn't change in the upper right area (frio).

At first that happend only on the Friendica Forum node when I tried to manage the forum accounts. But today I experienced the same on libranet.de when I tried to manage my local support forum and a news account.

### Steps to reproduce the problem
Delegate the right to manage an account of yours to some other contact of yours. (Explanation for @MrPetovan : Login to the account (2) you want to manage; go to settings -> delegations; select the user (1) you want to delegate the right to manage your account to by clicking on its avatar; Logout; Login to your account (1) again; now you can switch accounts by using the right side main menu -> manage).

Now try to switch accounts. Watch the theme and the name/avatar of the current user. It should change but it doesn't all the time. If it doesn't - you're unable to manage anything because you're not really in the managed account. It behaves more like a normal redir. 

### Friendica version you encountered the problem
2019.09-rc / 2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by tobiasd** [comment]
On Sat, 24 Aug 2019 02:37:24 -0700
Steffen K9 <notifications@github.com> wrote:

> After clicking on some menu the theme settings and everything doesn't
> match the settings of the managed account. Sometimes this happens
> directly after switching, sometimes it needs a page refresh. What I
> always see - when it doesn't work - is that the avatar and username
> doesn't change in the upper right area (frio).

I just tried it on my node this seems to work as expected. Clicking through the pages did not change the theme settings. For me this would be vier exchanged to frio.

**Comment by AlfredSK** [comment]
Hmm. I just tried again.
Logged in as 'Forum Admin' -> ok.
Switched to 'Friendica News' -> ok. Worked surprisingly! :-)
Switched to 'Helpers Forum' -> not ok. I'm still the 'Forum News' user.
Another attempt to switch to 'Helpers Forum' -> seems to work, but when I try to access the contacts I notice that I'm still the 'Friendica News' account.
Switching back to the 'Forum Admin' -> doesn't work. You need to login to continue (it is trying to access the /admin page)

**Comment by AlfredSK** [comment]
In another attempt I could successfully switch between Admin, Developers and News. Then I tried to switch to Helpers and this happend....

![image](https://user-images.githubusercontent.com/3656054/63636404-18b9a580-c66f-11e9-87d9-0a132c718e7d.png)

The theme changed to the one of the Helpers account but the user name still shows news. When I e.g. click on the contacts icon in the top bar I'm redirected to the contacts of the News account. The switch simply didn't work. I'm still the News account. I was only thrown on the profile page of the Helpers account. Clicking on some icon...

![image](https://user-images.githubusercontent.com/3656054/63636439-a2697300-c66f-11e9-9d6d-55ad7e959e19.png)

**Comment by AlfredSK** [comment]
Hmm. Works with Firefox but not with Chromium. Maybe some cookie setting?

**Comment by AlfredSK** [comment]
I have a question. How does the authentication work when I switch to a managed account? Is there some auth data stored somewhere? Cookie, session data, something else?

**Comment by AlfredSK** [comment]
Ah! Interesting. When I click on the avatars (green box) the switch to a managed account is very unreliable. It only works approx. in 1 of 10 attempts.

On the other hand it works absolutely reliable when I click on the links (red box) below the avatars.

![image](https://user-images.githubusercontent.com/3656054/64060950-1b1e8100-cbd4-11e9-9025-8035b7eb626d.png)

**Comment by tobiasd** [comment]
Is this still an issue or can it be closed?

**Comment by AlfredSK** [comment]
Oh! I totally forgot this one. It worked lately. I think we can close it.
