### ISSUE TITLE
Pleroma: Contacts and contact requests are kind of a mess

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7559]
### Expected behavior
When I send a contact request to Pleroma and the request gets accepted I should see a (one) mutual relationship and that's it. When I receive a contact request from Pleroma and I accept it I should see a (one) mutual relationship and that's it.
I should not get or send more contact request and end up with two, three, four contacts for the same Pleroma user.

### Actual behavior
When I accept a contact request from Pleroma I see a mutual relationship but I get more contact requests in the following days. And when I accept them I have more than one contact for the same Pleroma user (with same webfinger/URL but different contact IDs).
When I send a contact request to a Pleroma user and the user accepts it that user will get a lot more contact request from me and will complain about it. :-)

Communication works but the contacts / contact requests are a mess.

### Steps to reproduce the problem

**Discussion:**
https://forum.friendi.ca/display/0b6b25a8-895d-57fb-41b7-fbc246900720

![image](https://user-images.githubusercontent.com/3656054/63635663-1ce0c580-c665-11e9-8f0f-c71a1bc08613.png)

![Bildschirmfoto von 2019-08-21 17-17-16](https://user-images.githubusercontent.com/3656054/63635665-279b5a80-c665-11e9-9ea2-c1c6c714bfda.png)

![Bildschirmfoto von 2019-08-16 18-11-01](https://user-images.githubusercontent.com/3656054/63635668-2ec26880-c665-11e9-8739-41e39f7f2bee.png)

### Friendica version you encountered the problem
2019.09-rc / 2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
Maybe this Pleroma issue is related to our problem:
https://git.pleroma.social/pleroma/pleroma/issues/1189

**Comment by annando** [comment]
When performing some tests, I experienced strange behaviour by Pleroma. I still have to experiment a little bit, but Pleroma seems to act erroneous.

**Comment by annando** [comment]
Some update: On the Pleroma Frontend you can press the "follow" button as often as you want to - there is no difference in behaviour if the contact request is pending. So most likely people will tend to press it multiple times.

Every time that the button is pressed, a new contact request is generated. Additionally Pleroma does not only send an ActivityPub contact request but also an OStatus contact request. Due to timing issues this can cause the "multiple contact problem". I have prepared a PR for that. I guess I will finish it this evening.

**Comment by AlfredSK** [comment]
Captain's log supplemental: I checked the contact list of the Friendica Helpers forum. The same issue seems to exist with Mastodon users. I found several duplicates of Mastodon contacts. I hope this is already addressed by the two PRs. Let's see...

**Comment by AlfredSK** [comment]
This one seems to be fixed. 
Additional PRs: #7582 and #7616
