### ISSUE TITLE
[Frio] Replace social network with icon on posts

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7563]
As we have switched to ForkAwesome we now have quite a few social network icons (Hubzilla, GNU Social, Mastodon etc.) available. Heck, even [ActivityPub is there](https://forkaweso.me/Fork-Awesome/icons/)! Should we replace the sender's social network in the upper right of every post with an icon?

![image](https://user-images.githubusercontent.com/74432/63655981-09317e00-c78f-11e9-859f-6fc6930e25d3.png)

**Comment by MrPetovan** [comment]
YES!

**Comment by annando** [comment]
I need it for debugging purposes, so from my side only when we do have a config setting to change the behaviour (I suggest some setting that is only available in the config file) and when there is a description for screenreaders.

**Comment by MrPetovan** [comment]
I was thinking about an alternative text or a `title` attribute.

**Comment by vinzv** [comment]
Having an alt text or `title` is fine for me as well. If that works for @annando as well I'll build it that way.

**Comment by annando** [comment]
I would like to have this (more or less) debug config value to see the names at a single glance. (Means: like the current state)

Would this "only" have got different icons per protocol or per used software?

**Comment by AlfredSK** [comment]
> Would this "only" have got different icons per protocol or per used software? ...

Hmm. The same applies to Hubzilla posts (Diaspora vs. AP). 
From a user's point of view, I don't care about the protocol the post was transmitted with, but I'm interested in what network (software) the post was coming from. Remember, protocols are nerdy stuff. Normal people don't care about the tech terminology. :-)

**Comment by annando** [comment]
BTW: Currently we don't have a constant for the used software. This is some free format string since there are too much systems out there. Means: We will need some function that will return the appropriate icon string.

**Comment by vinzv** [comment]
I just tried to implement the network icon like this:
`<li><span class="wall-item-network" title="{{$item.app}}"><i class="fa fa-{{$item.network_name}}" aria-hidden="true"></i> {{$item.network_name}}</span></li>`

It technically works but `$item.network_name` delivers the name with capitalized first letter - which ForkAwesome can't handle. Is there a way do get $item.network_name in all-lowercase?

**Comment by annando** [comment]
@vinzv there are too many different networks and systems out there. This isn't a fixed set. Means: The only reliable way is some function that knows of all available networks/systems and then assigns them and that handles all unknown systems. For example: Neither Ganggo nor Socialhome are known. For these we had to look at the protocol level and had to choose Diaspora.

**Comment by annando** [comment]
@MrPetovan That's why I want to do it in a dedicated PHP function.

**Comment by AlfredSK** [comment]
Whatever we do it should be consistent. In my humble opinion it should be either icons or labels (text) but no mixture of both.

**Comment by vinzv** [comment]
**On the design side**
My understanding is that there's quite a fixed set of known networks. Friendica, GNU Social, 
Mastodon, Hubzilla and a handful more. Those are covered by ForkAwesome but of course there are others which are not and there might be more (new) networks in the future.

Furthermore, yes, mixing is bad but might be unavoidable if we stick with ForkAwesome here. But even if we use manually built icons there will be another brand new network coming out of the blue and showing up as text.

So it's kind of a general decision: Going with icons only and text as fallback - or not?

**On the technical side**
There might be a more elegant way but this is how I built it for now:
```smarty
                        {{if $item.network_name != "Friendica"}}
                        <li><span class="wall-item-network" title="{{$item.app}}">{{$item.network_name}}</span></li>
                        {{else}}
                        <li><span class="wall-item-network" title="{{$item.app}}"><i class="fa fa-{{$item.network_name|lower}}" aria-hidden="true"></i></span></li>
                        {{/if}}
```

**Comment by annando** [comment]
I still stick to the idea of a functionality inside of PHP for that. It can do the following:
* Check if the software is known, then use the matching icon
* If the software isn't known, then check for a matching icon for the network
* If also the network isn't known, use some general icon

**Comment by vinzv** [comment]
Yes, that sounds reasonable to me as well. It's just something don't know how to build in PHP.
