### ISSUE TITLE
HTTPS behind proxy server

### ISSUE THREAD

**Issue by Maxhy** [friendica/friendica#757]
Friendica should support https behind a proxy server like haproxy for load balancing, nginx or apache proxy checking HTTP_X_FORWARDED_PROTO server variable.

There only few lines to changes on protocol detection.
if(x($_SERVER,'HTTPS') && $_SERVER['HTTPS'])

should be replaced by

if((x($_SERVER,'HTTPS') && $_SERVER['HTTPS']) || (x($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'))

**Comment by shtrom** [comment]
It seems trickier than that. There are a few other non-standard ways to pass this information:

- `X-Forwarded-Proto` [0] (as @maxhy pointed out)
- `Front-End-Https: on` [1]

There is also a standard way [2]:

- `Forwarded: for=192.0.2.1; proto=https; by=192.0.2.2`

I think a fix for this issue should handle at least the latter one, but the former ones should probably also be included for backward compatibility (note that at least NginX does not set any of those variable by default). There might also be others that I am not aware of.

[0] https://www.drupal.org/node/3131
[1] https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields
[2] https://tools.ietf.org/html/rfc7239

**Comment by shtrom** [comment]
Ah, there is also an `X-Forwarded-Ssl: on` which is given as an example with NginX [0]

[0] https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy#SSL_with_nginx

**Comment by vinzv** [comment]
According to e5c7a0cf9369f39abcd8ef75e6edfb6c2b2b241a this is fixed. Can we close this issue?

**Comment by annando** [comment]
No one ever seemed to have tested this. But I think we could reopen it when it wouldn't work.

**Comment by MrPetovan** [comment]
Cloooooosing.
