### ISSUE TITLE
Deleted User still in the Database an gets Email

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7574]
A user wrote to me, he had an account to test on friendica registered and also deleted again, but the email address is probably still in the database, he still gets emails from users there. He also gets a new password if he enters password resets, but the login doesn't work (of course).

How can I delete this user completely?
I'm on RC

**Comment by copiis** [comment]
> Email = Private messages?

I think it's more the notifications that someone has responded to your post but I could ask again if it's important?

**Comment by annando** [comment]
Also you should check whether the account really is removed.

**Comment by copiis** [comment]
How can i du tust?

**Comment by copiis** [comment]
> If you could ask which type of notification emails were received it would be great.

He is notified by email when there are responses to posts he has been involved in.

**Comment by copiis** [comment]
> Also you should check whether the account really is removed.

The user is still present in the database under user.

**Comment by copiis** [comment]
I just found a second user who is still in the database although I got a deletion mail from him.

**Comment by annando** [comment]
The users are staying in the database for some time until they are removed. This is done to be able to send deletion notices to the other systems.

**Comment by copiis** [comment]
> The users are staying in the database for some time until they are removed.

Is this the filed with the expirationtime? `account_expires_on`

**Comment by tio-trom** [comment]
Happens for me too, for the 2022.06 version. I had 5 admin users and removed 4. They still get emails when there is a new request for signup....

**Comment by MrPetovan** [comment]
You need to remove their email address from the `config/local.config.php` file. This is the only way we recognize administrators at the moment.

**Comment by tio-trom** [comment]
> You need to remove their email address from the `config/local.config.php` file. This is the only way we recognize administrators at the moment.

Problem is, there is only 1 email there right now. And I get the emails to 1 single email address yet I receive 4 at once:
![2022-11-12_01-12](https://user-images.githubusercontent.com/38043315/201446572-bcd68147-d15b-41ab-9852-f162bdc20dc7.png)

Unsure if this is related to the above tho. These are users that I made to test it, some time ago. I then deleted them. As you can see I get the emails to the same email address but different user account:
![2022-11-12_01-14](https://user-images.githubusercontent.com/38043315/201446647-aea8b46a-c803-4cbf-bcc4-068b17ecf746.png)

Am confused :D

**Comment by tio-trom** [comment]
> You need to remove their email address from the `config/local.config.php` file. This is the only way we recognize administrators at the moment.

Problem is, there is only 1 email there right now. And I get the emails to 1 single email address yet I receive 4 at once:
![2022-11-12_01-15](https://user-images.githubusercontent.com/38043315/201446709-7571d462-6558-4821-b2e2-ed48cd78befe.png)


Unsure if this is related to the above tho. These are users that I made to test it, some time ago. I then deleted them. As you can see I get the emails to the same email address but different user account:
![2022-11-12_01-15_1](https://user-images.githubusercontent.com/38043315/201446715-afc601f7-ea42-4aae-b305-ec0b6833698b.png)


Am confused :D

**Comment by MrPetovan** [comment]
What does your `config.admin_email` config value look like?

**Comment by tio-trom** [comment]
Like so:
![2022-11-12_02-12](https://user-images.githubusercontent.com/38043315/201449500-da368900-779e-4c17-ab20-5dc988d9510d.png)

**Comment by MrPetovan** [comment]
Alright, found the issue, you're confusing your email address (tio@tromf.tf) with the WebFinger address of the multiple users that share the same email. `tiotest1@social.trom.tf` isn't an email address, it's just the user with the nickname `tiotest1` on your Friendica node with domain `social.trom.tf`.

In Friendica we allow the creation of multiple users with the same email. This means that even with a single email address in the `admin_email` config key, it can refer to multiple user accounts which will be sent the admin emails separately.

**Comment by tio-trom** [comment]
Ah I see thank you for the explanation. However why is the user `tiotest1@social.trom.tf` for example still receiving these emails when the user is already deleted?

**Comment by MrPetovan** [comment]
Because we don't check for deletion when retrieving the admin users, this could be improved. Also only sending one email per address would be good.

**Comment by MrPetovan** [comment]
So, to boil down what we have to do:
- Suppress notifications for deleted user accounts
- Only pick one admin account per email address

This sounds doable.
