### ISSUE TITLE
Resharing with Firefox broken - invalid regexp group and linkPreview is not a function

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7576]
### Expected behavior
When I try to reshare a post or comment it should work with Firefox too.

### Actual behavior
Firefox is throwing errors in the browser console when I try to reshare a post or comment. The screen gets grey but the post modal doesn't open.

**Errors in FF's error konsole:**
```
SyntaxError: invalid regexp group linkPreview.js:1:1
```
and
```
TypeError: $(...).linkPreview is not a function 0b6b25a8-725d-6557-981e-eff527424970:383:40
    jotShow https://libranet.de/display/0b6b25a8-725d-6557-981e-eff527424970:383
    jotShare https://libranet.de/display/0b6b25a8-725d-6557-981e-eff527424970:267
    onclick https://libranet.de/display/0b6b25a8-725d-6557-981e-eff527424970:1
```

### Steps to reproduce the problem
Use Firefox (68). Use the Frio theme. Follow a notification about a comment by clicking on the notification. Click the share link. Also, watch the error console of Firefox.

It works w/o any error with Chromium 76.

### Friendica version you encountered the problem
2019.09-rc

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Can you please pull latest RC and try again?

**Comment by AlfredSK** [comment]
Yes. As soon as I am home.

**Comment by AlfredSK** [comment]
Works like a charm. Thank you very much. 😃
