### ISSUE TITLE
[Frio] Image upload broken with new compose page

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#7586]
### Expected behavior
The upload button should open the file select dialog.

### Actual behavior
The upload button looks like it's clicked (color switching) but nothing happens.
Selecting a Gallery (Profile Pictures or other) leads to /network.
![image](https://user-images.githubusercontent.com/74432/63971058-f62bf000-caa5-11e9-8b07-67adbca6cd0f.png)

As a side note: The same procedure works fine with jot modal composer.
### Steps to reproduce the problem
Start writing a new post and try to upload a picture. (Firefox 68 Linux here)

### Friendica version you encountered the problem
2019.09-rc
### Friendica source (git, zip)
git
### PHP version
7.3.4
### SQL version
mariadb 10.3.15

**Comment by AlfredSK** [comment]
It works with Chrome on Android.

**Comment by MrPetovan** [comment]
Please try clearing your cache?

**Comment by MrPetovan** [comment]
Works on Vivaldi on Mac OS.

**Comment by vinzv** [comment]
This is what I did:
- cleared the cache of my browser with Ctrl + F5 [failed]
- deleting all web site data + cookies via menu [failed]
- tried Firefox for Android [failed] 
- tried a WebView based browser for Android ("FOSS Browser") [worked]
- tried a completely new profile of Firefox on Linux [worked]
- running my regular FF profile in safe mode [worked]
- deactivated all addons in my regular profile [failed]

I'm running out of options, kinda... 🤔

**Comment by MrPetovan** [comment]
I can reproduce this on Firefox 67.0.1 for Windows.
I can reproduce this on Firefox 68.0.2 for Windows.

I think this issue is triggered by the lack of Javascript regular expression lookbehind support in Firefox, as reported in #7531 and #7576.

Each time it fails, can you verify the `SyntaxError: invalid regexp group` error shows up in the Developer Console when you load the page?

**Comment by MrPetovan** [comment]
Can you please pull latest RC and try again?

**Comment by vinzv** [comment]
> Each time it fails, can you verify the `SyntaxError: invalid regexp group` error shows up in the Developer Console when you load the page?
Yes, exactly!

> Can you please pull latest RC and try again?
Tried - it works. Wohoo, thanks!
