### ISSUE TITLE
"Link to source" in events view redirects to user profile instead of the event

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#7597]
### Expected behaviour

Following the "link to source" in the popup of an event should lead to the display of the event so that the user can interact with the entry.

### Actual behaviour

The "link to source" redirects to the profile of the creator of the event. Which is also in the URL shown when one hovers the mouse over the link.

Tested with vier and frio themes in Firefox and Vivaldi.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/433490/64273227-2a3d6000-cf41-11e9-8923-e40a7e883d5d.png)

* click on the "link to source" button in an event popup

### Friendica version you encountered the problem

This behaviour is new in 2019.09-rc

**Comment by MrPetovan** [comment]
Please verify this is solved by #7602

**Comment by tobiasd** [comment]
Yes. it is :-)
