### ISSUE TITLE
Forum contacts with protocol 'Friendica (AP)' not showing up in Forum Widget

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7603]
### Expected behavior
Forum contacts should show up in the left side Forum Widget no matter if they're DFRN or AP contacts.

### Actual behavior
Today I missed the Friendica Support Forum (helpers) in the left side Forum Widget. Even on the forum node itself it wasn't showing up in the widget.

Then I checked what could be wrong. And I found the Support Forum was listed as Friendica (AP) contact while all other forums are Friendica (DFRN) contacts. The latter are showing up in the widget.

Then I went to the contacts page of all forum accounts (hosted on forum.friendi.ca) and selected 'Update Now' from the action menu. All forum contacts (developers, admins) were converted from 'Friendica' to 'Friendica (AP)' by doing so. And now they're all gone from the Forum Widget'.

### Steps to reproduce the problem
Look at the Forum Widget. Is some forum missing? Check the contact details. Is it Friendica (AP)?
Chose a forum contact that is a 'Friendica' (DFRN) contact. Select 'Update Now' from the action menu. Check if the contact has been converted to 'Friendica (AP)'. If so, check the Forum Widget on your network page.

### Friendica version you encountered the problem
2019.09-rc (tested with libranet.de and forum.friendi.ca)

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
![image](https://user-images.githubusercontent.com/3656054/64472560-a2ce3780-d160-11e9-8846-93d74a55af97.png)

![image](https://user-images.githubusercontent.com/3656054/64472571-c85b4100-d160-11e9-8220-773afc65f2e4.png)

![image](https://user-images.githubusercontent.com/3656054/64472577-e32db580-d160-11e9-977b-5901597a5faf.png)

**Comment by nupplaphil** [comment]
I've the same behaviour on my node.

**Comment by nupplaphil** [comment]
After the pull today, it's back again.. @alfredsk plz have a look too..

**Comment by AlfredSK** [comment]
Umm. No PR has been merged today. The forums are still AP contacts and not showing up in the widget. Maybe some contact update background job is bringing them back? I'll wait and see...

**Comment by AlfredSK** [comment]
Hooray! Fixed by #7607 

![image](https://user-images.githubusercontent.com/3656054/64638365-dc739c80-d405-11e9-9e52-b7d7e9267fca.png)
