### ISSUE TITLE
Opt out flag for federated search engine

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7610]
There is a new federated search engine https://search.social/about that spiders through the network collecting profiles and posts.There is already a convenient option for Mastodon to opt-out of the index, but not for all the other networks without blocking the whole services or adding code into the source code manually.

It would be nice if Friendica 
1. would have a clickable option in the **preference for every user** to opt out (on by default) of this search engines. 
2. Maybe as well an **administrator option for the whole node** itself, if an administrator doesn't want to have his node spidered at all.

**AND** as @annando mentioned this opens up the possibility to add mastodon and pleroma contacts to the friendica directory

> BTW: Having this config value on Mastodon and possibly Pleroma does open up the possibility to display contacts from these systems in our directory as well.

The corresponding issue that was raised _"Add other networks like Hubzilla/Mastodon/Pleroma/Diaspora ..."_  https://github.com/friendica/friendica-directory/issues/25

Description 

> Opting Out
> 
> There’s multiple ways of opting out to the index:
> 
>   Recommended/best way: set your account non indexable (meta tags),
>  - On Mastodon, this is the Opt-out of search engine indexing setting in Preferences > Other
>  - In your search.social account settings,
>  - Instance admins can put an instance-wide restrictive robots.txt.
> 
> Posts from non reachable instances will be removed from the index after around three months.

**Comment by tobiasd** [comment]
Would be great if they would have said what meta information they need for the opt-out.

**Comment by annando** [comment]
It's the ```<meta content='noindex, noarchive' name='robots'>``` on the profile page.

**Comment by hoergen** [comment]
in Mastodons Repository this should be
 - Add `noindex` flag to API repsonse https://github.com/tootsuite/mastodon/pull/7822
 - Search Indexes shouldn't be allowed to see boosted statuses of accounts which prohibit indexing https://github.com/tootsuite/mastodon/issues/7164 
 - want to get "Opt-out of search engine" https://github.com/tootsuite/mastodon/issues/6361
 - Instance-wide search engine opt-out https://github.com/tootsuite/mastodon/issues/11750

**Comment by tobiasd** [comment]
> It's the ```<meta content='noindex, noarchive' name='robots'>``` on
> the profile page.

Great :) I think this privaxy fix could be accepted for the current RC if a PR was made.

**Comment by annando** [comment]
Give me a minute.

**Comment by annando** [comment]
Still missing is the interpretation of that header when we crawl other profiles. I will see if I can do this as well.

**Comment by tobiasd** [comment]
In another PR?

**Comment by annando** [comment]
Yeah, the one that I did right now :-)

**Comment by annando** [comment]
I think we can declare this fixed. We are using the setting "Publish your default profile in the global social directory" for this.

**Comment by hoergen** [comment]
I think we can close this issue. Maybe there will be an option in future where you can stay in the directory but tell search engines not to crawl and archive your posts.

**Comment by tobiasd** [comment]
I've added a _short_ paragraph to the settings help text about this additional meaning of the setting.

![image](https://user-images.githubusercontent.com/433490/64904428-3efcbf00-d6ca-11e9-8235-9b38832b9666.png)

What do you think about it?

**Comment by hoergen** [comment]
Great text 👍. Only, I'm not used to "adhere to". In my experience the the term "stick to" is more common?

**Comment by tobiasd** [comment]
_deeply_ suggested the adhere :-)

**Comment by MrPetovan** [comment]
Adhere is correct. Stick to is more conversational.

**Comment by hoergen** [comment]
Yes I know deepl is sugessting that, but if you read/listen to articles, tutorials, podcasts, movies and so on, everybody is using "stick to". But I won't be in the way if you like to write shakespeare-ish messages ;)

**Comment by MrPetovan** [comment]
I'm assuming Tobias wasn't going for an informal tone in technical documentation. This isn't the style I would be using either. Both are correct, Other possible phrasings:
- "Friendica cannot influence whether search engines will respect this setting or not."
- "Third-party search engines may or may not respect this setting."

**Comment by tobiasd** [comment]
I like that "... may or may not ..." :-)
