### ISSUE TITLE
Images don't display on Mastodon, only URL provided

### ISSUE THREAD

**Issue by ironm0nk3y** [friendica/friendica#7618]
### Expected behavior
Post new image and share public post mastodon users can see it.

### Actual behavior
Mastodon post on has a url. Embded image no longer posted in image.

### Steps to reproduce the problem
Upload photo and share post or post image from wall photos gallery. Looks normal in friendica but mastodon no go.

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.06 - 1320

### Friendica source (git, zip)
Git 
### PHP version
7.2
### SQL Version
Latest MariaDB install.

**Comment by annando** [comment]
To understand it correctly: You Post a picture from Friendica and it doesn't appear on Mastodon? O Mastodon there is only a link to the picture?

This does work in the upcoming 2019.09.

**Comment by annando** [comment]
How is your Friendica handle? Although I'm convinced that the upcoming version doesn't have this problem, I want to be sure.

**Comment by ironm0nk3y** [comment]
So where we are at the moment. I updated the OS on this installation. Which included update for php and mariadb. Now if I upload a picture to a gallery first and share it, it is good. If I attempt to created a status from twidere or my network page on web ui upload the image there within post not gallery first, the recipient in mastodon is greated with a red circle with slash. As if the everyone permission is not being honored.

If I use twidere as an example:
Select image on mobile and select share
SELECT TWIDERE app and craft post or tag
Sent posting, posting accepted
Refresh timeline in twidere red circle present also on mastodon redcircle.

Storage is directory, perms on directory are www-data:www-data.

Post is update  an improvement but resembles similar issue opened. I will post #when I find it.

Thanks




Sep 13, 2019, 05:30 by notifications@github.com:

**Comment by AlfredSK** [comment]
Some days ago it didn't work in 2019.09-rc. So, I did a new test on current RC code (libranet.de). A photo uploaded to and posted from Friendica is displayed correctly on mastodon.social.

**Comment by annando** [comment]
@ironm0nk3y question still is, how is your Friendica handle? I would like to have a look at your postings.

But nevertheless I'm still convinced that this is not a blocking bug for the current version.

**Comment by AlfredSK** [comment]
In the meantime _I_ have two examples. :-)

**7 days ago**; public post; there is **only a link** to the image on mastodon.social
https://libranet.de/display/0b6b25a8-115d-73c2-d2b2-544317276349 

**1 day ago**; public post; the image is **correctly displayed** on mastodon.social
https://libranet.de/display/0b6b25a8-175d-7bdb-9413-518749165135

Jeez! I cannot provide the Mastodon links. Whenever I copy the item link and execute that link in my browser I'm redirected back to Friendica. That's annoying. :-) 
@annando Do you have any idea how to get the link to an public item on Mastodon?

**Comment by tobiasd** [comment]
Screenshots maybe?

**Comment by AlfredSK** [comment]
Yes. The screenshots! :man_facepalming: 
:-)

**Comment by AlfredSK** [comment]
![image](https://user-images.githubusercontent.com/3656054/64905230-6b6a0880-d6d5-11e9-992e-ec0d832624cb.png)

![image](https://user-images.githubusercontent.com/3656054/64905237-83418c80-d6d5-11e9-8166-36c7be581a1a.png)

**Comment by annando** [comment]
@AlfredSK some days ago I fixed some stuff that exactly caused this problem. So when all newer posts are fine then the bug is finally fixed.

**Comment by AlfredSK** [comment]
Yes. That's what I thought, too.

**Comment by MrPetovan** [comment]
Closing here as already fixed.

**Comment by ironm0nk3y** [comment]
Awesome what did you fix so I can do the same. ;-)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by annando** [comment]
You can update to the latest version when we release it.

**Comment by ironm0nk3y** [comment]
Thanks! Then I keep my eyes open. And thank you for your work on this awesome platform!

-------- Original Message --------

**Comment by vsatmydynipnet** [comment]
May I reopen this one.  I have a fresh setup server: 

Diese Friendica-Instanz verwendet die Version 2021.04
Die Datenbankversion ist 1413/1413 und die Post-Update-Version 1400/1400.

Federation Mastodon -> Friendica works fine, Image is shown

Federation Friendica -> Mastodon works fine too, except instead of the image there is a link on Mastodon (points to the Friendica Instance Post).

My Instance is a Photo/Video based one so exchanging images between the user/followers is kinda a must. 

Would be great if there is a fix for it.

Thank you very much for this cool peace of software.

**Comment by annando** [comment]
@vsatmydynipnet Do you have a link to the post? I need to analyze the data.

**Comment by vsatmydynipnet** [comment]
> @vsatmydynipnet Do you have a link to the post? I need to analyze the data.

@annando use -- removed --, feel free to follow to see all posts. NSFW :-)

**Comment by annando** [comment]
These posts are having titles. Those posts are interpreted differently on Mastodon. See the current PR here: https://github.com/friendica/friendica/pull/10291

**Comment by vsatmydynipnet** [comment]
Thank you for the hint. I was reading the german conversation an tested without titel. That way the image is shown on mastodon as it should be. but i think for users this is not understandable. they will post with titel and reask over and over. :-)

May I do a suggestion:

on transmit to Mastodon, if there is a image and a title, transmit

join(titel+NewLine+post text) in max length what mastodon accepts as text + link to post + the image as attachement.

or do i see things wrong here?

**Comment by annando** [comment]
We are transmitting posts via AP for nearly all receiving systems (except Diaspora and older Friendica systems). So also we are using AP to transmit posts to newer Friendica systems. Some "are you Mastodon" would need to be tested not only on the transmitting side but also when these systems would fetch the content. Also there is not only Mastodon, but Pleroma and some other systems.

Also imagine if Mastodon would implement a better handling of this. Then we also would need to handle version numbers as well. This is much too complicated and it is very likely that there would be side effects.

**Comment by vsatmydynipnet** [comment]
I will ask Eugen / Mastodon about this one. Thank you for your help.

**Comment by annando** [comment]
@vsatmydynipnet he is very clear about this. His position is that Mastodon is a software for *short* messages. This is for example one of his arguments for the static and non configurable character limit.

Some time ago I opened an issue concerning this topic: https://github.com/tootsuite/mastodon/issues/8892

**Comment by vsatmydynipnet** [comment]
I have no idea if there are specs in regards to the protocoll which  one side is not following, I also only see Eugen added suggestion on the https://github.com/tootsuite/mastodon/issues/8892 issue in Oct. 2020. But IMHO if people talk, there should always be a way.  I mentioned Eugen on Mastodon. Maybe he finds time to recheck this problem. Missing images in postings IMHO damages the looks and feel in Fediverse, so whatever solution is possibible would help to grow Fediverse IMHO.

**Comment by oculos** [comment]
I don't if this is still an issue, but right now, my friendica posts only show as links on mastodon.

**Comment by foss-** [comment]
@oculos Could you share your version from `Help > Site/Version Info` please.
Ideally also share a sample post: a) URL of your friendica post b) that friendica post received on mastodon.

**Comment by MrPetovan** [comment]
Did you add a title to your posts? If yes, this changes the way Mastodon interprets your posts since Mastodon doesn't have a concept of post title. So they assume it's a link to a bigger posts and only provide a backlink to the post on your server.

**Comment by oculos** [comment]
> Did you add a title to your posts? If yes, this changes the way Mastodon interprets your posts since Mastodon doesn't have a concept of post title. So they assume it's a link to a bigger posts and only provide a backlink to the post on your server.

Yes, I did. So that explains it, I guess. Thanks!
