### ISSUE TITLE
Get rid of implicit self-mentions

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7629]
I'm happy with the implicit mentions we are doing. But I don't like one thing – implicit self-mentions.

### Expected behavior
When I comment my own posts Friendica should not add an implicit self-mention. 

### Actual behavior
When I comment my own posts I automatically mention myself. This seems completely unnecessary and very weird. I my eyes this gives the impression that I'm a self-centered and lunatic person. 😀

### Steps to reproduce the problem
Write a post. Write a comment on the top level post. Friendica doesn't show that self-mention. But on other networks you can see it.

I think implicit self-mentions have no purpose and no practical advantage at all. Please add a check for implicit self-mentions and then suppress (get rid of) them completely.

### Friendica version you encountered the problem
2019.09-rc

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
Discussion this way...
https://forum.friendi.ca/display/0b6b25a8-165d-7cc8-c6c6-9ce104233120

**Comment by MrPetovan** [comment]
It makes sense that it would be only with the Diaspora protocol, because we force explicit mentions because of the absence of threading. We probably can exclude self-mentions from the process though.

**Comment by annando** [comment]
It's not only Diaspora, it's AP as well.

**Comment by AlfredSK** [comment]
Yeah, I thought so too. But I did some tests yesterday. The self-mentions didn't exist on Pleroma and Mastodon. Hmm...

**Comment by annando** [comment]
I can't test it, I have it disabled, since I want to decide on my own who I'm mentioning :-)

**Comment by AlfredSK** [comment]
**Top-level post in Friendica:**

https://libranet.de/display/0b6b25a8-175d-7e00-4820-abf985141362

![image](https://user-images.githubusercontent.com/3656054/64919602-4052e800-d7ad-11e9-89d8-79b3280ab8be.png)

**Comments on several other sites/networks:**

1. Hubzilla:
![image](https://user-images.githubusercontent.com/3656054/64919635-80b26600-d7ad-11e9-8113-917aedd04f51.png)

2. Diaspora:
![image](https://user-images.githubusercontent.com/3656054/64919650-9de73480-d7ad-11e9-90a5-5b30cd858a03.png)

3. Mastodon:
![image](https://user-images.githubusercontent.com/3656054/64919655-b35c5e80-d7ad-11e9-977d-e10b68bf4f90.png)

4. Pleroma:
![image](https://user-images.githubusercontent.com/3656054/64919667-ca02b580-d7ad-11e9-9e7c-6f7c5fe2df86.png)

5. Friendica (another node):
![image](https://user-images.githubusercontent.com/3656054/64919677-e999de00-d7ad-11e9-8def-c0358f133d15.png)

So, the self-mention does only appear on diaspora networks.

**Comment by AlfredSK** [comment]
**Summary:** all my comments have an implicit self-mention on Diaspora nodes/networks (bad UX) and don't have an implicit self-mention on AP/DFRN nodes/networks (good, works).

**Comment by MrPetovan** [comment]
Please test again with the latest RC.

**Comment by AlfredSK** [comment]
Friendica:
![image](https://user-images.githubusercontent.com/3656054/64920962-a9425c00-d7bd-11e9-91a3-37b89d61d77c.png)

Hubzilla:
![image](https://user-images.githubusercontent.com/3656054/64920967-c0814980-d7bd-11e9-80c0-eb1f06e8382f.png)

Diaspora:
![image](https://user-images.githubusercontent.com/3656054/64920973-d727a080-d7bd-11e9-9f8a-69abed30c65d.png)

**Comment by AlfredSK** [comment]
And the implicit mentions of other users are still working (comment on comment). Perfect.

![image](https://user-images.githubusercontent.com/3656054/64921064-a2681900-d7be-11e9-95e2-fe7f494c6299.png)

Fixed by #7630
