### ISSUE TITLE
Stream order of posts is broken

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#7632]
### Expected behavior
If stream order is set to 'posted order' I expect that it is ordered that way.

### Actual behavior
A 11 months old posting of a contact of mine got liked by somebody and is on top of my stream and a page refresh doesn't make it disappear. This is not the first time it happens to me - it happens since a very long time over and over again.

### Steps to reproduce the problem
Ask somebody to like an old posting shared by one of your contacts that's visible for both of you and see if friendica puts it on top of your network stream, when 'posted order' is activated.

### Friendica version you encountered the problem
 Friendica 'Dalmatian Bellflower' 2019.09-rc - 1322 

### Friendica source (git, zip)
git

### PHP version
PHP 7.3.9

### SQL version
mysql  Ver 15.1 Distrib 10.2.22-MariaDB, for Linux (x86_64) using readline 7.0

**Comment by annando** [comment]
Can it be that your storage time is short than these 11 months? Then the post had been refetched. And since the "posting order" in fact is a "order in which the posts arrived at your server, the behaviour is correct.

**Comment by rebeka-catalina** [comment]
On 2019.09.15, Michael Vogel wrote:
> Can it be that your storage time is short than these 11 months?

90 days.

> Then the post had been refetched. And since the "posting order" in fact is a "order in which the posts arrived at your server, the behaviour is correct.

Wonderful. Everything is working correctly, even if my stream order
is broken? Could you then please remove or rename those buttons to
control the order? Those buttons don't keep what they're promising.

**Comment by annando** [comment]
If we would do it strictly according to the date at which the posting had been created, you would simply don't see many posts. When - for example - my server has got some hickups and hadn't delivered some posts for several hours, these posts would then appear deep down in your timeline.

Or when you subscribed to some feeds, then we take the feed date as creation date. But when you - for example - fetch the feeds only once a day, then the possibility would be high that you never would see these feed posts. Same goes with reshared items.

**Comment by rebeka-catalina** [comment]
On 2019.09.15, Michael Vogel wrote:
> If we would do it strictly according to the date at which the posting had been created, you would simply don't see many posts. When - for example - my server has got some hickups and hadn't delivered some posts for several hours, these posts would then appear deep down in your timeline.

Cool, that's exactly what the button promises and what I'm waiting
from such a setting.

> Or when you subscribed to some feeds, then we take the feed date as creation date. But when you - for example - fetch the feeds only once a day, then the possibility would be high that you never would see these feed posts. Same goes with reshared items.

Exactly. Then I would have to filter, or to scroll back. That's
exactly, what I would like to have. The current chaos brings me
headaches.

**Comment by MrPetovan** [comment]
I agree we should rename the "posted order" since it isn't the "posted order" anymore. It is more intuitive and practical (for shares for example), but doesn't match the label anymore.

**Comment by rebeka-catalina** [comment]
Wouldn't it be possible, to build in a 'strict' switch for those, who
want this?

Michael, I totally understand that you for example need it as it's
currently done, but you and me are 'living' in totally different
worlds.

You have hundreds of contacts and a massive amount of incoming
posts, but I'm not in such a situation. For me it's extremely annoying
as it's currently working. I nearly every day delete stuff, just
because it's old stuff on top of my stream. That's just disturbing
every day and... hell... it doesn't end. I want posts in exactly
posted order and I'm for sure not the only one who wants that.
I know a few members who are also annoyed about that misorder.

**Comment by annando** [comment]
No, we cannot afford a third sorting order. Each sorting order really costs us performance and disc space.

**Comment by rebeka-catalina** [comment]
That's really a reason for me to leave friendica some day.

**Comment by MrPetovan** [comment]
We should keep track of the deleted items, only removing the body/source that are space-intensive.

**Comment by annando** [comment]
Well, concerning the case above: We could try to check the age of the added post (in fact, we should already do).

Concerning the other things: We could optionally display the receipt date instead of the creation date on the post.

**Comment by MrPetovan** [comment]
No, the creation date is important for context, but the label really should be renamed.
