### ISSUE TITLE
$_SERVER['PHP_SELF'] can be empty with nginx/php-fpm

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7635]
The current `sample-nginx.config` file states:
> NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

This seems to make `$_SERVER['PHP_SELF']` empty and subsequently makes Friendica treat every request as a backend one, disabling sessions, which prevents login altogether.

We should either:
- Stop suggesting this configuration (a discussion about this value can be found [here](https://serverfault.com/questions/627903/is-the-php-option-cgi-fix-pathinfo-really-dangerous-with-nginx-php-fpm))
- Use a different `$_SERVER` key for backend determination, like possibly `SCRIPT_FILENAME` which is present regardless of this configuration.

I'm not familiar with the nginx/php-fpm setup, so I'll leave up to someone else to decide although I would prefer a more robust code that doesn't depend on platform-dependent `$_SERVER` keys.

**Comment by annando** [comment]
Can this be the reason for the problem that one user reported after update?

**Comment by rebeka-catalina** [comment]
What I can say is, that I have set up this node about a year ago and
cgi.fix_pathinfo was never enabled in my setup.

**Comment by MrPetovan** [comment]
Thanks for the testimonial, with Adam Clarke we were surprised no one else came forward with the same issue before, so it doesn't just depend on this configuration key. One more reason to make the code as ubiquitous as possible.

**Comment by MrPetovan** [comment]
`$_SERVER['PHP_SELF']` isn't used anymore in the Friendica codebase thanks to #7639 .
