### ISSUE TITLE
Tumbrl account authentication or re-authentication fails

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7652]
If you want to authenticate or re-authenticate an account at Tumbrl you get the message "Could not connect to Tumblr. Refresh the page or try again later." Can anyone confirm this?

**Comment by AlfredSK** [comment]
Yes. I get the same message when I click on the tumblr re-authenticate link. But posting to tumblr works nonetheless.

**Comment by copiis** [comment]
Thats right, posting to works

**Comment by Anu-El** [comment]
Log in to Mastdon,Gab and Friendcia have all Failed to accept my Log
in's....I have Been trying for Days.    So far I've only got Acess to
Wordpress and Peertube.

**Comment by annando** [comment]
According to https://github.com/friendica/friendica/issues/11551#issuecomment-1499949114 at least the authentication seems to work, so I guess we can close this issue?
