### ISSUE TITLE
Log in to Mastdon, Gab and Friendica have all Failed

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7655]
Log in to Mastdon,Gab and Friendcia have all Failed to accept my Log
in's....I have Been trying for Days.    So far I've only got Acess to
Wordpress and Peertube.

_Originally posted by @Anu-El in https://github.com/friendica/friendica/issues/7652#issuecomment-533924628_

**Comment by annando** [comment]
I think we can close this?

**Comment by MrPetovan** [comment]
Why? It isn't part of a milestone, it just is a support request.

**Comment by annando** [comment]
I prefer closing support requests as well when there is no response.

**Comment by MrPetovan** [comment]
Then just do it and mention the reason.
