### ISSUE TITLE
Rework "redir" and calls to "remote_user"

### ISSUE THREAD

**Issue by annando** [friendica/friendica#7657]
The PR #7656 introduced some changes to "redir" and the "remote_user" function. These changes need to be completed. Means:
- Rewriting of "redir.php" (removal of unneeded code)
- Replacing the loops through the "remote" session cookie with calls to "remote_user"
- Adding the user id to all calls of "remote_user" where this does make sense

**Comment by nupplaphil** [comment]
Maybe you can create `redir` as a new `src/Module/Redir` and remove unneeded code during the transfer :)

**Comment by annando** [comment]
Yes, this is planned.
