### ISSUE TITLE
Better image viewing experience for federated posts

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#7658]
When viewing posts with images created in Friendica, clicking on image opens it in large viewing box with buttons to switch between multiple images which is nice and expected.

However when similar post comes from Diaspora (presumably other networks too), images are unclickable and the only way to expand them larger is to individually use "Show image..." browser functionality on every image which is a hassle. Also if there are multiple images, they are jumbled together in the post.

1. Can Friendica image viewer catch all images to expand them on click like Hubzilla does?

2. It would be even nicer if multiple images attached to the post would be grouped together in some way (e.g. Diaspora shows only the first image and the rest as thumbnails, Hubzilla groups them into a grid with dynamically sized thumbnails so more images are attached, lesser their thumbnails are).

Examples of how federated post with multiple images looks:

Hubzilla
https://hub.deko.cloud/display/9cb3ac10b745013709797a163ef10931

Diaspora
https://deko.cloud/posts/9cb3ac10b745013709797a163ef10931

Friendica
https://libranet.de/display/9cb3ac10b745013709797a163ef10931

**Comment by hoergen** [comment]
I opened a similiar request a while ago;)
https://github.com/friendica/friendica/issues/5133

**Comment by SpcCw** [comment]
@hoergen I did some searching but couldn't find it :)

Also I think when it comes to federated images, it is important to have some image grouping functionality as well otherwise posts with lots of images look quite bad. Maybe this could be taken from Hubzilla? I think they made it as addon.

**Comment by hoergen** [comment]
Yes think we need that urgently because people start posting lots of images :( But it is a front end task and at the moment there are really not much people involved. We would need some more people that are helping.

**Comment by annando** [comment]
In the past @rabuzarus had been a specialist in extracting stuff from Hubzilla and implementing it here. Possibly he wants to do it again?

**Comment by AlfredSK** [comment]
I really like the idea to have some kind of album view or photo carousel when a post contains more than X images. There are posts with **a lot** of images like [this one](https://libranet.de/display/1a61a700c7dd0137e2fc268acd52edbf). It's a pain to scroll through such a post especially on mobile devices.

When users just post images it would be great to have them presented in a way like Hubzilla is doing it. But what if a user wants to tell a photo story - a post with photos and descriptions/text between the photos (like a blog post)? When we extract the photos from the post to show them as an album at the top or at the bottom of the post we would destroy the intended structure of the post.

**Comment by SpcCw** [comment]
@AlfredSK I like how Diaspora does this. There you can either just attach images to the post (then they end up displayed as thumbnails / carousel with one image showing as large). Most posts use this mode as it is easy and efficient - just type the text, upload multiple images, hit post.

However you can still upload photos and embed them in the post like Friendica does by using "Insert image" button. In this case they are not extracted by the carousel viewer as it is assumed the post author intended them to be viewed in this exact way. This happens more rarely but it can be useful sometimes.

It works quite great. Also perhaps it is simpler approach to implement (rather than going over post content and looking for embedded images). Hubzilla image gallery sometimes produces weird results and also can cause performance hit when there are lots of posts with images to be processed.

Maybe Friendica could adopt Diaspora approach? Given how many posts contain high-resolution images good photo viewing UX is important.

**Comment by SpcCw** [comment]
Now this issue is no longer relevant because of amazing new features: Image Grid functionality and Fancybox addon!

**Comment by MrPetovan** [comment]
CC @MarekBenjamin and @brockhaus for the compliments
