### ISSUE TITLE
[Frio] Mobile View: Notice is overlapping nav-bar

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#7660]
I think we should adapt the position of the notice field for mobile views. An example is the welcome message after the login. It annoys me every time that I don't see the notification symbol after the login:
![LRM_EXPORT_272204056056212_20190924_203406262](https://user-images.githubusercontent.com/379654/65539948-b58b8f00-df0a-11e9-99ea-c75fc0eb3a88.jpeg)

Of course this is a minor problem, but I think these minor fixes increases the UX a lot :)

**Comment by AlfredSK** [comment]
Yes, it's not ideal. But you can close the notification bubble with that small x.

**Comment by nupplaphil** [comment]
I've so big thumbs, it costs me 2-3 times to catch the x ;) ... Another UX pain for me ...

**Comment by MrPetovan** [comment]
We've removed this particular notice since it wasn't useful.

**Comment by MrPetovan** [comment]
Closed by #8919
