### ISSUE TITLE
Friendica is partly  broken

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7663]
After git pulling this morning i got logged out all the time and when i click on a mention i get "Unauthorized" in my browser

**Comment by hoergen** [comment]
Hmmm I needed to restart my server to solve this problem ? 
At the moment it is solved, so I close it. Somebody else having this situation?

**Comment by annando** [comment]
The last days I also had got the problem that I had to log in more often. I guess that it will be solved with my pending PR.

**Comment by hoergen** [comment]
You are right, I get still logged out from time to time.

**Comment by hoergen** [comment]
And I get again the unauthorized in my browser. I reopen the issue.

**Comment by hoergen** [comment]
Ok commenting seems to be broken too. At the moment I can't comment.

**Comment by AlfredSK** [comment]
Hmm. On my node it seems to work. Pulled this morning as well.

**Comment by hoergen** [comment]
Now it is solved with @annando  PR
