### ISSUE TITLE
Account posting notification is triggered when account is just mentioned

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7664]
The option you can set, to get a notification when a contact is posting something, is triggered, when some other contact (both are my contacts) is mentioning the one contact i configured to be mentioned.

**Example**
1. I checked account "Hans", so that I get a notification, when he posts something
2. My other contact "Traudl" is writing a new post where she is mentioning "Hans"
3. I receive a notification that "Traudl" wrote a new post.

### Expected behavior
Only get notifications when "Hans" is writing new posts and not, when he is mentioned by others in new posts

### Friendica version you encountered the problem
git, latest 2019.09-rc, PHP7.2 Mariadb

**Comment by tobiasd** [comment]
This is really annoying. :-(

**Comment by annando** [comment]
Should be fixed now.

**Comment by hoergen** [comment]
Thanks a lot I close this issue
