### ISSUE TITLE
Drone CI - Increase speed

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#7667]
As FollowUp of #7643 
- [x] Add Caching ( http://plugins.drone.io/meltwater/drone-cache/ )
- [ ] Add Vendor package as submodule ( https://github.com/friendica/vendor/ ) instead composer install
- [ ] Check DB Setup (currently takes 8 minutes to setup only the DB structure for each test..)
- [ ] Simplify `autotest.sh` for non DB tests

**Comment by nupplaphil** [comment]
bumped to 2020.03 because we, @ben-utzer and I need a little bit more time to fix a problem with a port-forwarding :-)

**Comment by ben-utzer** [comment]
I think some of this is probably solved with the new server, is @nupplaphil still around to try it? Also I remember it would be possible to have more clients carrying out tests, wasn't it? 

@tobiasd, I don't have any real knowledge about the drone thing, but maybe someone else has?

**Comment by tobiasd** [comment]
Seems to be working now, so closing the issue :)
