### ISSUE TITLE
Can't see restricted posts on remote profile if the remote profile is on the same instance

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#7679]
### Expected behavior
Restricted posts should be visible on the profile page if the visitor does have the permissions to read it even if profile owner and visitor are on the same instance

### Actual behavior
if a visitor does visit someones profile page and the visitor and profile owner are on the same instance, the visitor isn't able to see restricted posts on the owners profile page even if the visitor does have the permission to see this posts.

This was introduced with https://github.com/friendica/friendica/commit/5254147ccc18417f0b16ec4d8b8325d7790b4fde

### Friendica version you encountered the problem
2019.09

### PHP version
7.2

**Comment by annando** [comment]
There are some more ugly things happening. Hopefully these are now fixed with PR https://github.com/friendica/friendica/pull/7678

**Comment by rabuzarus** [comment]
https://github.com/friendica/friendica/pull/7678 fixes the issue
