### ISSUE TITLE
error for /api/friendica/remoteauth

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#7685]
The endpoint doesn't work anymore for not-DFRN contacts. It shows an XML of the profile page, but not the requested sub-URL. Parameters are c_URL=https://domain.tld/profile/screenname&url=https://domain.tld/photos/screenname

**Comment by MrPetovan** [comment]
Thanks for the report, I'll look into it.

**Comment by MrPetovan** [comment]
This endpoint isn't supposed to work with non-DFRN contacts at all. I'd need a contact URL to verify its `poll` field, you can send both to me in a private message at https://friendica.mrpetovan.com/profile/hypolite

**Comment by MrPetovan** [comment]
Closed by #7971
