### ISSUE TITLE
Enhancements for account registration (Captcha/HoneyPot/Comment field)

### ISSUE THREAD

**Issue by tellmewho** [friendica/friendica#7688]
I just set up a new instance of friendica and within 48 hours I got 5 account registrations which seem to be automatically made by spammers.

How about adding a honeypot to the registration page and/or have a comment field for people to tell me: 

- why I should approve their account
- what ever...

**Comment by AlfredSK** [comment]
When the register policy is set to APPROVAL there is a field to leave a note for the admin.
"Leave a message for the admin, why you want to join this node"

We could make that field mandatory, I think.

**Comment by tellmewho** [comment]
> When the register policy is set to APPROVAL there is a field to leave a note for the admin.
> "Leave a message for the admin, why you want to join this node"
> 
> We could make that field mandatory, I think.

Sounds good! ...and maybe give the possibility to customize "Leave a message for the admin, why you want to join this node" !

**Comment by tobiasd** [comment]
As a first patch, I've added the `require` attribute to the textarea designated for the note to the admin.

The placeholder text is currently fixed to that strings, so that it can be translated to all supported languages so the visitors get int in their selected browser language. You can set a *more personal* note into the register text config in the admin panel. That text will be shown above the entire registration form.

**Comment by tellmewho** [comment]
Thanx!

**Comment by tellmewho** [comment]
I'm afraid I have to reopen this.
I added the patch from @tobiasd and when I try to register myself for test purpose I can't send the registration without entering a note **but** I have already 4 new registrations pending without note?!?
Any way to find out what happens?

**Comment by MrPetovan** [comment]
Yes, it's a classic case of client-side validation that robots can just bypass by submitting the form anyway. We don't check the note has been filled on the server side yet.

**Comment by tobiasd** [comment]
All fine with reopening the issue! And sorry to be unclear about that ;-) but that was the reason I've written "part of" in my pull request. Checking the input from the note is another step I had so far no time to touch.

**Comment by tobiasd** [comment]
> Any way to find out what happens?

What happened is basically the `required` field that was added is asking the users client politely to have a look that the field is filled. But the client (browser / script / whatever) can just ignore the request.

**Comment by tobiasd** [comment]
The server side part was merged into the develop branch of Friendica @tellmewho could you please check if this helps with your problem?

**Comment by tellmewho** [comment]
Thanks! You guys are amazing! I updated my register.php and let you know the next days if something changed. I got ~3-4 registrations per day since I set up the server. I'm quite surprised to be the first one having this problem, since I didn't promote my friendica node anywhere and still attracted so many bots 8)

**Comment by tellmewho** [comment]
Strange, it was rather quite for about a week (no bot registrations), but for a couple of days now I get random registrations with random names and comments, like: 

Username: egLNFhlGIOJtKy 
Mailaddress: ***lakebail@yahoo.com 
Comment: ZGQMSaylYxmsiKec

Still my question: am I the only one having this problem?

**Comment by AlfredSK** [comment]
Who knows? At least it looks like nobody else has reported this problem yet.

**Comment by MrPetovan** [comment]
The other method I know to ward off spam bots is to add another field to the registration form and add a message for people not to put anything in it. Bot will add nonsense/spam in it because that's what they are programmed for and be rejected.

**Comment by MrPetovan** [comment]
I didn't know the name "tar pit" for this.

**Comment by tobiasd** [comment]
Me neither, but it feels like a "tar pit" for poor bots ;-)

**Comment by tobiasd** [comment]
@MrPetovan do you think, that a "hidden" input field would be sufficient for such a field.

**Comment by MrPetovan** [comment]
I'm not sure, bots could ignore it. A regular input field would be better, even if we hide it from the display with CSS..

**Comment by tobiasd** [comment]
@tellmewho we added a *hidden* field to the register form at the Hackathon with #7812 I hope it helps to prevent at least some of those registrations.

**Comment by tobiasd** [comment]
Has anybody tried the latest changes to the registration with the hidden field? does it have an impact at all? I mean after the initial problems (sorry for those again).

**Comment by tellmewho** [comment]
> Has anybody tried the latest changes to the registration with the hidden field? does it have an impact at all? I mean after the initial problems (sorry for those again).

I only managed to update the files on my server yesterday, that's why I didn't give a feedback yet. Sofar (over night) I got no new registrations, but for whichever reasons I had "breaks" of upto 4-5 days before as well. So I'll get back at the end of the week to give a final conclusion!

Thanks for your efforts!

**Comment by tellmewho** [comment]
No new (unwanted) registrations anymore!! Thanks a lot!

**Comment by tobiasd** [comment]
Thanks for checking @tellmewho
