### ISSUE TITLE
ActivityPub: using sharedInbox for private deliveries can leak privacy

### ISSUE THREAD

**Issue by redmatrix** [friendica/friendica#7691]
### Expected behavior

Posts to lists/circles/aspects with one member should only be delivered to that one member.

### Actual behavior

Privacy leakage through sharedInbox interface, delivering to all followers of the post creator on the remote site.

### Steps to reproduce the problem

Send a post to a list/circle/aspect/whatever with one member but where you have other followers on that site. The private post is delivered to other followers. This *may* be platform specific, in this case Zap was used. See the following discussion.

This is a subtle artifact of sharedInbox behaviour. The default behaviour is "if the public inbox is addressed, deliver to the public inbox, else deliver to all this actor's followers". These are the only two use cases for this endpoint. 

Note that the specific contents of the addressing fields is not directly referenced in this description; except to to detect the presence of the public inbox and use the addressing fields and attempt individual deliveries in the total absence of a sharedInbox.   

Friendica is apparently delivering private posts addressed to lists/circles/aspects to the sharedInbox and not to the private inbox of the desired recipient(s). The recipient sharedInbox (in this case on a Zap system) is using the default sharedInbox behaviour and is therefore delivering to people outside the scope of the private post. Checking the actual addressing fields on Zap is not a workable solution because deliveries can be made to Bcc recipients who have been stripped from the server-to-server addressing fields per the spec. In the server to server case the inbound server is relatively dumb and needn't check addressing, only permission to post. The destination is determined by the endpoint used and recipients are checked only in the case of addressing the public inbox directly from the sharedInbox endpoint.  Some projects do check individual addresses, but haven't yet dealt with the Bcc bugs which they've introduced because Mastodon does not really use Bcc.

An amusing anecdote: it is apparently not possible to deliver to the public inbox via Bcc. This is an undocumented flaw in the spec caused by the inclusion of the "deliver to my followers" mode by Mastodon during the spec evolution. Probably not a serious flaw but mentioning here because I doubt anybody but myself is even aware of it.   

I believe the only workable solution is to deliver private posts only to the private inboxes of the recipients. I am willing to listen to disagreement and other possibilities but point out this is likely to involve how to handle the Bcc case specially, and the recipient system doesn't really have any knowledge of the Bcc recipients unless this is a C2S transaction (which this is not). 

### Friendica version you encountered the problem
see `example.com/friendica` on your Friendica node for the version information.

2019.09 running on libranet.de

### Friendica source (git, zip)

unknown

### PHP version

unknown

### SQL version

unknown

**Comment by annando** [comment]
Concerning BCC: When we address someone via BCC, we directly deliver the message to their private inboxes, since the "bcc" header mustn't be set in S2S, only in C2S. For the rest of the post I have to be more awaken than at the moment.

**Comment by annando** [comment]
I think that PR #7691 handled this issue? Can we close it?
