### ISSUE TITLE
ActivityPub Event "id" is faulty

### ISSUE THREAD

**Issue by lanodan** [friendica/friendica#7694]
### Expected behavior

- The event's ActivityPub id should be fetcheable and return the same object 

### Actual behavior

- Another UUID is given

### Steps to reproduce the problem

- Create an event
- Try to fetch it's ActivityPub representation (By putting something like ``Accept: application/ld+json,application/activity+json,application/json``)
- `/display/:uuid` works, getting the `/objects/:uuid` given in the ActivityPub object doesn't works.

Note: taking the UUID of `/display/:uuid` and reusing it for `/object/:uuid` works.

Examples:
- Display URL: https://snarl.de/display/0bf23919-405d-954e-2656-79d172340661 → 200
- ActivityPub id: https://snarl.de/objects/0bf23919-545d-954e-2656-28e563298254 → 404
- Forged activity id by reusing the display URL: https://snarl.de/objects/0bf23919-405d-954e-2656-79d172340661 → 200

### Friendica version you encountered the problem

Whatever setup snarl.de has… sorry.

**Comment by lanodan** [comment]
Looks like it's a duplicate of https://github.com/friendica/friendica/issues/6603 and snarl.de probably didn't update in the meantime, sorry I messed my Github issue searching on first tries.

**Comment by MrPetovan** [comment]
No problem, thanks for the report anyway!

**Comment by MrPetovan** [comment]
> Looks like it's a duplicate of #6603 and snarl.de probably didn't update in the meantime

I can confirm snarl.de still is on version 2019.01, which is pretty old by Friendica's standards.

See http://snarl.de/friendica

**Comment by Anu-El** [comment]
Thanks I'm going to try this.
 The Registration has been a Nightmare.
It doesn't Accept User Names and it asks for User Names that are
Complicated that has had me Trying to get an Account for over 2 Weeks and I
Saw that I had an Old Account in my Emails.
 Mastodon Social Media has done The same thing.
When I finally got an Account from Mastodon Social Media it Said that my
Account was Suspended and I hadn't had The Account over 25-30 Minutes
before I was Locked out.
  This Frustration is Insane.
 Please help me.

**Comment by MrPetovan** [comment]
This support request makes no sense in this issue, please open another one mentioning the Friendica node you've been trying to register with.
