### ISSUE TITLE
Geocoordinates addon doesn't resolve addresses

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#7697]
### Expected behavior
When Geocoordinates addon is enabled and post location is provided, coordinates should be resolved into an address.

### Actual behavior
Coordinates still display as numbers both for incoming and outgoing posts.

### Steps to reproduce the problem
- enable geocoordinates addon
- configure it with API key
- post something with "add location" option

### Friendica version you encountered the problem

2019.09, git

**Comment by SpcCw** [comment]
Just a little update:
If posts are sent through API with location passed as "lat" and "long" parameters, then names are resolved! But it doesn't work with web interface (both new compose window and older dialog).

**Comment by MrPetovan** [comment]
Thanks for the follow-up!

**Comment by annando** [comment]
This should now have been solved, also we now have a second addon that also does this job.
