### ISSUE TITLE
Contact requests from Diaspora on News Page Accounts are wrong/misleading

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7702]
### Expected behavior
When a Diaspora user follows a news page account (like `news@forum.friendi.ca`) the user should be automatically accepted as a follower (fan). There souldn't be a notification for a contact request.

### Actual behavior
When I add a Friendica news page account to an aspect on Diaspora everything seems to be fine. On Diaspora the news account is added to the contacts. But on the Friendica news page account I get a notification about a contact request and there is a an actual contact request waiting for approval....

![image](https://user-images.githubusercontent.com/3656054/66253164-14030980-e764-11e9-8731-29a662e3c044.png)

But! When I check the list of contacts that contact is listed as 'is fan of yours'. So, the automatic acceptance of the contact request actually worked...

![image](https://user-images.githubusercontent.com/3656054/66253170-4a408900-e764-11e9-9167-7dcf1ce40024.png)

### Steps to reproduce the problem
Try to follow a news page account from Diaspora. Watch what happens on Friendica's side.

### Friendica version you encountered the problem
2019.09 master

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by tobiasd** [comment]
This should be fixed in the current development version of Friendica. Do you want to test it with another account or can we close the issue?

**Comment by AlfredSK** [comment]
I can check it. Let me do the pull...

**Comment by AlfredSK** [comment]
OK. I checked it with the same Diaspora user and another news page account on develop. It works as expected now. Thank you! Closing...

Fixed by #7810
