### ISSUE TITLE
Password reset doenst work

### ISSUE THREAD

**Issue by fedione** [friendica/friendica#7709]
Request password reset and received email but the link doesnt work.

Got a HTTP ERROR 500 

Logfile:

```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ParagonIE\\Certainty\\Exception\\BundleException: No valid bundles were found in the data directory. in /var/www/clients/client0/web1/web/vendor/paragonie/certainty/src/Fetch.php:128
Stack trace:
#0 /var/www/clients/client0/web1/web/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(72): ParagonIE\\Certainty\\Fetch->getLatestBundle()
#1 /var/www/clients/client0/web1/web/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(45): DivineOmega\\PasswordExposed\\PasswordExposedChecker->getBundleFromCertainty()
#2 /var/www/clients/client0/web1/web/src/Model/User.php(414): DivineOmega\\PasswordExposed\\PasswordExposedChecker->__construct(Object(GuzzleHttp\\Client), Object(DivineOmega\\DOFileCachePSR6\\CacheItemPool))
#3 /var/www/clients/client0/web1/web/src/Model/User.php(462): Friendica\\Model\\User::isPasswordExposed
...
```

Any help is much appreciated :)

**Comment by MrPetovan** [comment]
Please grant write permission to the web server to the `vendor/` folder recursively.

**Comment by fedione** [comment]
Write permission is granted.

**Comment by MrPetovan** [comment]
And it still fails?

**Comment by annando** [comment]
Can we enable some check for this? Then we can display it on the admin page.

**Comment by fedione** [comment]
@annando how to do this?

**Comment by fedione** [comment]
> And it still fails?

Yes, it fails

**Comment by annando** [comment]
@fedione this is something that has to be done in the code. This was meant as some notice what to do to prevent such problems in general, not directly your case.

**Comment by MrPetovan** [comment]
We should at least just skip the password check in this case, this means a `try { ... } catch` block.

**Comment by MrPetovan** [comment]
Meanwhile, you can edit your local `config/local.config.php` to set `$config['system']['disable_password_exposed']` to `true`.

**Comment by fedione** [comment]
> Meanwhile, you can edit your local `config/local.config.php` to set `['system']['disable_password_exposed']` to `true`.

Seems that it looks quite different in my  local.config.php :(

Don't know wherr and how to add this .

**Comment by fedione** [comment]
Okay - found it:

		'disable_password_exposed' => true,

**Comment by MrPetovan** [comment]
It should look like this:
```php
return [
    ...
    'system' => [
        ...
        'disable_password_exposed' => false,
        ...
    ],
    ...
];
```

**Comment by fedione** [comment]
@MrPetovan 
This works - Thanks :)

**Comment by MrPetovan** [comment]
The exception is now caught with #7734
