### ISSUE TITLE
addons.friendi.ca not working

### ISSUE THREAD

**Issue by lostinlight** [friendica/friendica#7731]
### Expected behavior
https://addons.friendi.ca , linked in Addons git repo, should show information about addons

### Actual behavior
http version returns default apache page

**Comment by tobiasd** [comment]
Thanks for spotting. I think that sub-domain was forgotten when moving from friendica.com to friendi.ca. You can find the addon directory at https://snarl.de/wiki/doku.php?id=friendica_addons though for many addons listed there the information are sadly outdated.

**Comment by tobiasd** [comment]
We closed the index, almost all addons are in the projects addon repository. So I'm closing this issue.
