### ISSUE TITLE
Search field doesn't show results and deleting a saved search doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7733]
### Expected behavior
When I delete a saved search from the left aside widget by clicking on the trash can the saved search should be deleted.

### Actual behavior
When I delete a saved search from the left aside widget by clicking on the trash can the saved search is not deleted. I get an error 404 page instead. Clicking on "Go Back" brings me back to the network page. The saved search I tried to delete is still there.

### Steps to reproduce the problem
Delete a saved search by clicking on the trash can in the left aside widget...

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
Works in master. Maybe caused by PR #7714 ?

**Comment by MrPetovan** [comment]
Absolutely, on it.

**Comment by MrPetovan** [comment]
Found the issue.

The URL `/search/saved/remove/%23hashtag` is rewritten by Apache as `index.php?pagename=/search/saved/remove/`

However, adding the `B` flag to the URL rewriting rule solves this issue like this:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?pagename=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA,B]
```

Problem is that this change has to be done manually by all the existing Friendica node admin.

Instead, I can change the URL structure to be `/search/saved/remove?term=%23hashtag` but it is slightly less elegant, but maybe we don't need elegance for this particular URL.

**Comment by copiis** [comment]
> ,B

Just ad this?

**Comment by MrPetovan** [comment]
Yes, but on all the existing Friendica nodes running on Apache? Here lies the problem.

**Comment by AlfredSK** [comment]
Since we are not shipping the `.htaccess` anymore I vote for the less disruptive, less elegant way to solve this issue. :-)

**Comment by AlfredSK** [comment]
Oops! And I just found out that searching for a tag in the search field doesn't work either.

`.../search?search=%23test` is the URL when I hit the search button. This URL gives no results and there is no 'save' button.
`.../search?q=%23test` is the URL of an already existing saved search. This URL shows the results and the 'save' button.

I temporarily added the 'B' to the rewrite rule. But it didn't solve this issue.

**Comment by MrPetovan** [comment]
> Since we are not shipping the `.htaccess` anymore I vote for the less disruptive, less elegant way to solve this issue. :-)

That was my feeling as well.

**Comment by tobiasd** [comment]
> The same is true for every search. I just searched for a user witch @testuser. Doesn't work. And searching for a post URL (to pull an external post) doesn't work.

I can confirm this. The search bar seems to be broken entirely.

**Comment by MrPetovan** [comment]
Even after pulling #7737 ?

**Comment by tobiasd** [comment]
> Even after pulling #7737 ?

Yes, I'm on 962724bec71aa15e7b83228c58fbd4709f439077

For all search requests made from the nav-bar or `/search` I'm getting a frowning bunny and the message "file not found".

Additionally when opening `/search` from the vier-menu entry a search for the term "search" is already made, thus delaying the page display. Which is the only search that works, displaying postings that don't contain the word (on the first glance).

Did something change in the web-server config used for Friendica + Apache? I'm running with lighttpd.

**Comment by AlfredSK** [comment]
From my experience it does work again. I switched back to current develop and tested a search for a user and a tag. Both searches were successful. I also tried fetching a remote post from squeet.me. That wasn't successful. I'll try to fetch other posts and report the result.

**Comment by AlfredSK** [comment]
Fetching a post from Mastodon and Diaspora does work here too.

**Comment by tobiasd** [comment]
All search request lead to the file not found page. Independent of the used theme.

Did something change with the query string for the search?

**Comment by tobiasd** [comment]
To answer my question `search` seems now `q` which breaks the search with seems to have broken it with lighttpd.

**Comment by tobiasd** [comment]
Ok, fixed it.

Historically the `q` parameter was used for what is now the `pagename` parameter in the URL. That changed but the old way kept working. The change is the search module is basically the first breaking change from the silent support of the old way hence the lighttpd config needs to be adopted.

**Comment by MrPetovan** [comment]
Oooh, sorry about that, I really couldn't have known.
