### ISSUE TITLE
[frio] Follow button affected by whether they follow me

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#7740]
### Expected behavior

 - I am not following a user
 - When I tap the user's avatar on mobile, the popup has the follow button (head-and-shoulders and plus)

### Actual behavior

 - I am not following a user
 - When I tap the user's avatar on mobile, the popup has the follow button only if the user is not following me

### Friendica version you encountered the problem

`This is Friendica, version 2019.12-dev that is running at the web location https://libranet.de. The database version is 1323, the post update version is 1322.`

The theme is Frio.

**Comment by MrPetovan** [comment]
Is it the same in the desktop hovercard? Can you please take a screenshot of the missing button?

**Comment by clacke** [comment]
Specific examples discussed over at https://libranet.de/display/0b6b25a8-935d-a323-8327-f90179615712 .

**Comment by MrPetovan** [comment]
Ok, I can confirm. I have been overhauling the follow buttons but I didn't touch the hovercard yet.
