### ISSUE TITLE
Log file without write access leads to white screen

### ISSUE THREAD

**Issue by michip21** [friendica/friendica#7756]
### Actual behavior
In the admin settings, logging is enabled, but the logfile has no write permission. This leads to a white screen without error message.

### Steps to reproduce the problem
Turn on logging with a wrong path with no write permission.

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.09 - 1323

### Friendica source (git, zip)
git

### PHP version
7.2

**Comment by MrPetovan** [comment]
What does your PHP/web server logs say?

**Comment by michip21** [comment]
Apache Errorlog:
`[Sun Oct 20 09:16:54.367026 2019] [proxy_fcgi:error] [pid 882:tid 140053078554368] [client xx.xx.xx.xx] AH01071: Got error 'PHP message: PHP Warning:  is_file(): open_basedir restriction in effect. File(../friendica.log) is not within the allowed path(s): (/home/users/friendica/www:/home/users/friendica/files:/home/users/friendica/tmp) in /home/users/friendica/www/src/Factory/LoggerFactory.php on line 99\nPHP message: PHP Warning:  is_dir(): open_basedir restriction in effect. File(..) is not within the allowed path(s): (/home/users/friendica/www:/home/users/friendica/files:/home/users/friendica/tmp) in /home/users/friendica/www/src/Util/Logger/StreamLogger.php on line 182\nPHP message: PHP Warning:  is_dir(): open_basedir restriction in effect. File(..) is not within the allowed path(s): (/home/users/friendica/www:/home/users/friendica/files:/home/users/friendica/tmp) in /home/users/friendica/www/src/Util/Logger/StreamLogger.php on line 187\nPHP message: PHP Fatal error:  Uncaught UnexpectedValueException: Directory ".." cannot get created: open_basedir restriction in effect. File(/home/users/friendica) is not within the allowed path(s): (/home/users/friendica/www:/home/users/friendica/files:/home/users/friendica/tmp) in /home/users/friendica/www/src/Util/Logger/StreamLogger.php:188\nStack trace:\n#0 /home/users/friendica/www/src/Util/Logger/StreamLogger.php(158): Friendica\\Util\\Logger\\StreamLogger->createDir()\n#1 /home/users/friendica/www/src/Util/Logger/StreamLogger.php(116): Friendica\\Util\\Logger\\StreamLogger->checkStream()\n#2 /home/users/friendica/www/src/Util/Logger/AbstractLogger.php(116): Friendica\\Util\\Logger\\StreamLogger->addEntry('error', 'Error(s) while ...', Array)\n#3 /home/users/friendica/www/src/Core/Logger.php(155): Friendica\\Util\\Logger\\AbstractLogger->error('Error(s) while ...', Array)\n#4 /home/users/friendica/www/src/Util/XML.php(426): Friendica\\Core\\Logger::error('Error(s) while ...', Array)\n#5 /home/users/friendica/www/src/P...\n'
`

**Comment by nupplaphil** [comment]
Hmm.. There's a check in this case. I'll check the check ;)

**Comment by annando** [comment]
You should check if you have a check for the check 😁

**Comment by nupplaphil** [comment]
This error is caused by using a "relative" path for the logfile directory and because the streamlogger tries to create a directory `..`.

**Comment by MrPetovan** [comment]
Can't we just use `realpath()`?

**Comment by nupplaphil** [comment]
Sounds even better.. :)
