### ISSUE TITLE
Reshare a Friendica post from Diaspora to Friendica removes title

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7766]
### Expected behavior
Post should look still like it looks on Friendica

### Actual behavior
Screenshot lovestory ;) 

Original post on Friendica
![02_temp](https://user-images.githubusercontent.com/24474762/67481392-3a7cdc00-f662-11e9-9038-686400ad3f66.png)

Post on Diaspora
![00_temp](https://user-images.githubusercontent.com/24474762/67481431-4e284280-f662-11e9-9f5d-36116bac6fe0.png)

Reshare comes back from Diaspora to Friendica - Title is missing "Wenn jetzt nur noch Personal da wäre ... Neuer Bußgeldkatalog für Berlin Bis zu 120 Euro für weggeworfene Zigarette"
![01_temp](https://user-images.githubusercontent.com/24474762/67481526-6dbf6b00-f662-11e9-9131-3101ef8ef3df.png)

### Steps to reproduce the problem
Create a post and do the share pingpong.

### Friendica version you encountered the problem
latest develop 2019.12
git
php7.2
mariadb

**Comment by annando** [comment]
Yeah ... the reshare part in Friendica is currently a PITA.

**Comment by annando** [comment]
This should be fixed via https://github.com/friendica/friendica/pull/7903

**Comment by annando** [comment]
I would like to close it now, if you don't mind?

**Comment by hoergen** [comment]
As far as I can see (found just one example)  it is fixed.
