### ISSUE TITLE
Friendica und die Förderation zu Mastodon

### ISSUE THREAD

**Issue by fedione** [friendica/friendica#7772]
Friendica ist super - ehrlich 😆

Ich förderiere allerdings auch, und so kommt es auch zu seltsamen Erscheinungen 🤔

Während auf Diaspora der Originalbeitrag:

https://friendica.x.hfrc.de/display/5616ed50-155d-b2a6-b091-391277049601

genau so erscheint, wie er sein sollte

![17862104615db2a9700c14e670077905-1](https://user-images.githubusercontent.com/55923612/67555885-766f7a00-f712-11e9-89b4-be123231f844.png)

so sieht er auf Mastodon doch ganz schön verwurstelt aus 🙄

![73484074125db2a9575d3a9031577196-0](https://user-images.githubusercontent.com/55923612/67555951-999a2980-f712-11e9-8d42-4c0eb8d698e9.png)

Nicht nur, dass das eingebettet Bild fehlt, es werden auch Links zu Friendica statt zum Originalbeitrag von zeit.de angezeigt.

**Da Mastodon doch wesentlich mehr Nutzer hat als Diaspora, wäre es doch schön, wenn auch dort die Posts so ankommen könnten, wie sie sein sollen** 😆

So sollte der Beitrag auf Mastodon eigentlich aussehen:

![20486635285db2ad2812f81206863249-0](https://user-images.githubusercontent.com/55923612/67555999-ae76bd00-f712-11e9-9437-d8a831321fea.png)

Wenn nur die URI von zeit.de im Beitrag steht, und nicht der Link zum Post von Friendica, wird das Vorschaufeld unten im Post automatisch generiert.

Das Gleiche gilt auch für den umgekehrten Weg.

Diaspora Posts werden wunderbar auf Friendica dargestellt:

![14651852715db2af46a5d2f666468704-1](https://user-images.githubusercontent.com/55923612/67556046-bfbfc980-f712-11e9-9388-8bfdf341e734.png)

während Posts von Mastodon ohne Bild und Textauszug auskommen müssen:

![67249147875db2af66c35c7319480025-1](https://user-images.githubusercontent.com/55923612/67556070-cc442200-f712-11e9-8c32-867545edf682.png)

Ich weiß jetzt, dass Mastodon Bilder nicht einbettet, und auch keine HTML Formatierungen kennt, aber, wenn ich in einem Friendicapost eine URI eingebe, wird sie direkt in einen Textauszug mit Foto umgewandelt.

Das geht doch auch bestimmt umgekehrt, also wenn ein Post von Mastodon mit URI kommt?

Es wäre wirklich fantastisch, wenn Friendica auch Mastodon, auf welcher programmtechnische Art und Weise auch immer, so genial integrieren könnte wie Diaspora.

**Comment by fedione** [comment]
Nachtrag 🙂

Ich weiß, dass ihr das Projekt Friendica in eurer Freizeit programmiert und betreut, und ihr das nicht hauptberuflich macht und dafür bezahlt werdet, und ihr euch auch mit Dingen beschäftigt, von denen ich keine Ahnung habe.

Für mich bedeutet aber Förderation nicht nur, dass der Post irgendwie ankommt.

Es ist eben mein **Wunsch!**, dass ein Post von Friendica auf allen Netzen gut aussieht, und umgekehrt genauso.

Ich habe gehört, dass es zwischen Mastodon und Diaspora ideologische Differenzen geben soll, und deshalb die Förderation zwischen diesen beiden Systemen nicht funktioniert.

Sollt das auch hier der Fall sein, so möchte ich meinen Wunsch, damit kein Unfriede ensteht, zurückziehen.

**Comment by AndyHee** [comment]
Thanks for opening this issue. Could you please summarise this in English? Is this a "Support" request or an "Enhancement"? | Vielen Dank. Koennen sie das Problem auf englisch zusammen fassen? Handelt es sich um Unterstützungsanfrage oder Verbesserung?

**Comment by annando** [comment]
@AndyHee this is a request for the enhancement of how Friendica posts are appearing on other systems, especially Mastodon. There is one issue in that post that I want to have a look at. But in fact we don't have that much influence on how the posts appear on other systems - and especially Mastodon is very limited.

**Comment by AndyHee** [comment]
Thanks @annando I wasn't entirely sure what was asked. 

@fedione you may also want to speak to the folks at Mastodon about how posts appear over there.

**Comment by fedione** [comment]
Thanks to @annando too :)

Summary:

Friendica posts are looking strange at Mastodon. I think if the URI that links back to Friendica ( see second image ) is removed, the post will look fine because Mastodon inserts post excerpt and image by the URI only - not by HTML.

Similar in Friendica:

Received posts by Mastodon doesn't show excerpt and image ( see 5th image )

So my feature request is to handle the URI, sent with a Mastodon post, like an URI is handled by local postings.

As result an image and the excerpt is showing with the post - if available.

**Comment by hoergen** [comment]
The repository of mastodon can be found here https://github.com/tootsuite/mastodon
I already opened an issue for a maybe similar problem. Just check it and if it fits, join the issue ;) 
https://github.com/tootsuite/mastodon/issues/12194

**Comment by fedione** [comment]
Just a reminder 😉

![201910290838](https://user-images.githubusercontent.com/55923612/67746942-deca9e00-fa27-11e9-85f8-c3693f56844e.jpg)

**Comment by annando** [comment]
From my point of view this issue is solved with the current release. We made everything that we could so that other systems like Mastodon or Pleroma do display our content correctly.
