### ISSUE TITLE
Resharing Mastodon post removes embedded video

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7773]
### Expected behavior
The reshare contains all elements from the original source

### Actual behavior
the video elements are removed.

Original post (in Friendica timeline)
![00_temp](https://user-images.githubusercontent.com/24474762/67580378-8608b600-f746-11e9-8f3c-f3f5774d3011.png)

Preview of reshared post (if finally reshared, it looks exactly like this)
![01_temp](https://user-images.githubusercontent.com/24474762/67580410-991b8600-f746-11e9-984d-06730a5492e5.png)

Original post on mastodon https://framapiaf.org/@davidrevoy/103023169372139713

### Steps to reproduce the problem
Reshare a post from Mastodon with a embedded video

### Friendica version you encountered the problem
current develop
git
php 7.2
current mariadb

**Comment by annando** [comment]
This should be fixed now by https://github.com/friendica/friendica/pull/7903

**Comment by annando** [comment]
Can we close it?

**Comment by hoergen** [comment]
It is fixed. Perfect. Thank you 🌻
