### ISSUE TITLE
Personal notes are public when posted from non-Composer jot

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#7778]
### Expected behavior

Writing a personal note on the users "private note" tab, should create a note only visible to the user.

### Actual behavior

It is public. See https://social.diekershoff.de/display/f3ad7b1c-345d-b5ce-fbef-a9b891609097

### Steps to reproduce the problem

1. Go to your home and select the "personal notes" tab; or go to `/notes`
2. Write a personal note.

### Friendica version you encountered the problem

2019.12-dev

### Friendica source (git, zip)

git

### PHP version

7.2

**Comment by annando** [comment]
Meh!

**Comment by AlfredSK** [comment]
Cannot reproduce.
I wrote a personal note. When I'm not logged in I get a 'not found' error when I try to access the URL of the note.

**Comment by annando** [comment]
Is it a theme issue?

**Comment by AlfredSK** [comment]
That's what I thought too. I checked it with frio.

**Comment by tobiasd** [comment]
It is broken in frio as well, if the "compose page" is not activated. See https://social.diekershoff.de/display/f3ad7b1c-165d-b680-eec9-206326028069

**Comment by AlfredSK** [comment]
Ah! I have the compose page activated.

**Comment by annando** [comment]
I can confirm the bug. I'm onto it. I will try to solve it this evening.

**Comment by annando** [comment]
Meh, I cannot reproduce it anymore. Everything seems to work fine.

**Comment by tobiasd** [comment]
Yes, still broken. The morning greetings went out.

**Comment by annando** [comment]
I just found it. It had been well hidden.

**Comment by tobiasd** [comment]
Confirmed. Thanks a lot!

**Comment by annando** [comment]
In the next days I will add some additional checks for this situation.
