### ISSUE TITLE
Compose page of frio theme on dev results in blank screen

### ISSUE THREAD

**Issue by fedione** [friendica/friendica#7781]
Compose page results in blank screen.

Friendica Friendica 'Dalmatian Bellflower' 2019.12-dev - 1323 (just updated  but error persist)

Apach error.log:

> [Mon Oct 28 17:19:30.711666 2019] [proxy_fcgi:error] [pid 21828] [client xx.xx.xx.xx:53366] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\\Util\\ACLFormatter::expand() must be of the type string, null given, called in /path/on/my/server/web/src/Module/Item/Compose.php on line 77 and defined in /path/on/my/server/web/src/Util/ACLFormatter.php:19\nStack trace:\n#0 /path/on/my/server/web/src/Module/Item/Compose.php(77): Friendica\\Util\\ACLFormatter->expand(NULL)\n#1 [internal function]: Friendica\\Module\\Item\\Compose::content()\n#2 /path/on/my/server/web/src/App/Page.php(311): call_user_func(Array)\n#3 /path/on/my/server/web/src/App/Page.php(365): Friendica\\App\\Page->initContent(Object(Friendica\\App\\Module), Object(Friendica\\App\\Mode))\n#4 /path/on/my/server/web/src/App.php(795): Friendica\\App\\Page->run(Object(Friendica\\App), Object(Friendica\\App\\BaseURL), Object(Friendica\\App\\Mode), Object(Friendica\\App\\Module), Object(Friendica\\Core\\L10n\\L10n), Object(Friendica\\Core\\Config\\JitConfiguration), Object...', referer: https://experimental.friendica.hfrc.de/settings/display

**Comment by nupplaphil** [comment]
I brick it, I (try to) fix it :-)

**Comment by AlfredSK** [comment]
Interesting. I don't get this error. Possibly because I use the preload config adapter?

**Comment by MrPetovan** [comment]
Hi @fedione , thanks for the report, next time please add it in the dedicated master issue for fatal errors: https://github.com/friendica/friendica/issues/7675

**Comment by fedione** [comment]
Didn't know this exist, but I'll do it next time.

**Comment by nupplaphil** [comment]
@AlfredSK It's in case you have a `null` set in the user-table for any of `allow_cid`, `allow_gid`, `deny_cid`, `deny_gid` fields .. So this is not a issue related to every instance

**Comment by fedione** [comment]
Works perfect now- thanks

**Comment by MrPetovan** [comment]
Did you alter your database values to be empty strings instead of NULL? The important PR related to your issue #7782 hasn't been merged into develop yet.

**Comment by fedione** [comment]
Nope - didn't do nothing else but pulling 🤔

**Comment by MrPetovan** [comment]
It looks like it solved on its own on your server! 😅

**Comment by fedione** [comment]
Well, sometimes me and my server are unbelievable 😄

**Comment by nupplaphil** [comment]
Should finally be solved with #7793
