### ISSUE TITLE
password changing not possible

### ISSUE THREAD

**Issue by fedione** [friendica/friendica#7796]
Trying to change a password results in an error an the old one still remains:

Master:

![201911021025](https://user-images.githubusercontent.com/55923612/68069045-8c58ec80-fd5b-11e9-93d1-5161d94dff9b.png)

Dev:

![201911021028](https://user-images.githubusercontent.com/55923612/68069081-d17d1e80-fd5b-11e9-96fb-79192d581d41.png)

**Comment by fedione** [comment]
error.log:

`[Sat Nov 02 10:30:14.231134 2019] [proxy_fcgi:error] [pid 19511] [client xx.xx.xx.xx:44664] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: hide_wall in /a/path/on/my/server/web/mod/settings.php on line 574', referer: https://experimental.friendica.hfrc.de/settings`

**Comment by annando** [comment]
This should have been solved by now. The server admin should update their installation.

**Comment by MrPetovan** [comment]
Duplicate of #7709, fixed by #7734

**Comment by fedione** [comment]
Works in dev - user was logged out immediately after changing without notification.

Still same problem in master.

**Comment by MrPetovan** [comment]
Yes, we only update `master` on a quarterly basis during releases. Last time was in September, next time will be in December.

**Comment by fedione** [comment]
Despite a security problem like this one? 😲

**Comment by AlfredSK** [comment]
Can someone please elaborate what the actual problem is?
I just tested changing my password on a node on master and it works w/o any issue.  🤔

**Comment by MrPetovan** [comment]
> Despite a security problem like this one? 😲

It isn't a security problem as much as a usability problem depending on the web server configuration, so I'm not comfortable making a hotfix release just for this.

> Can someone please elaborate what the actual problem is?

The password exposed check on password change requires a Certificate Authority bundle to ensure the security of the third-party API call. This bundle has to be downloaded in the `vendor` folder, which may or may not be writable by the web server. When the bundle is missing, the password exposed check failed spectacularly and aborted the password change procedure. This has been fixed on `develop`.

However, it doesn't affect all nodes and password exposition checks can be disabled in the configuration. It isn't a critical security feature, just an elaborate password strength check, so it doesn't compromise Friendica to disable it.

**Comment by AlfredSK** [comment]
Thank you! I get it now.

**Comment by copiis** [comment]
> Can someone please elaborate what the actual problem is?
> I just tested changing my password on a node on master and it works w/o any issue.

It works on my master to

**Comment by fedione** [comment]
I really don't know why this isn't working on my instance, except adding `'disable_password_exposed' => true,` to local.config.php.

It is a pretty fresh installation (2019/10/23) pulled by git wit no error messages whiles installation.

I followed this instruction: https://forum.friendi.ca/help/Install

and the web server has recursive read/write access to vendor directory.

**Comment by MrPetovan** [comment]
Are you using Apache or nginx+php-fpm? In the latter case, php-fpm would need write access to the `` `vendor/` file tree, not the nginx user.

**Comment by fedione** [comment]
I'm using Apache and php-fpm.

**Comment by MrPetovan** [comment]
The same applies, Apache and php-fpm might be running with different users, and it's the php-fpm user would need write access, not the Apache one.

**Comment by fedione** [comment]
Nice to know but also not working.

Even setting directorys recursively to 0777 - for testing purposes only! - doesn't work

**Comment by fedione** [comment]
Switching to fast-cgi is not working also.

**Comment by MrPetovan** [comment]
I'm stumped, I'm unfamiliar with this setup and have no idea why it isn't working and how to fix it.

**Comment by fedione** [comment]
Well - it is like it is and it seems I have to live with that additional line in config.

**Comment by AlfredSK** [comment]
Hmm. I'm using Apache 2.4.41 with php-fpm 7.2.24 here. Both are running with user 'www-data'.
`drwxr-xr-x  27 www-data www-data   4096 Nov  2 03:52 vendor/`

**Comment by ben-utzer** [comment]
> requires a Certificate Authority bundle to ensure the security of the third-party API call

@MrPetovan so how can I solve this, install the CA bundle?

**Comment by MrPetovan** [comment]
Give write access to the web server user recursively in `vendor/`, or fiddle with your local `composer.json` to require the `dev-master` version of `paragonie/certainty` to pull in updated CA bundles: https://github.com/paragonie/certainty/blob/master/README.md#non-supported-use-case

**Comment by ben-utzer** [comment]
> Give write access to the web server user recursively in `vendor/`, or fiddle with your local `composer.json` to require the `dev-master` version of `paragonie/certainty` to pull in updated CA bundles: https://github.com/paragonie/certainty/blob/master/README.md#non-supported-use-case

My webserver and http user have that access right that was set when pulling by git with the very same user. The webserver user calls php and I use the webserver user to call git and the whole update commands, not sure how else one would do it. Still it didn't work at that time. I think it is working with 12.2019-rc now, so the bug seems to be fixed now.
