### ISSUE TITLE
Access rights in public and private forums

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7799]
- Posts in **public** forums need to be always public, regardless if members are posting with restricted access.
- Posts in **private** forums need to be always restricted, regardless if members are posting with no restricted access
- Removal of the access right settings from the preferences

**Comment by hoergen** [comment]
Is this still a thing, or can it be closed?

**Comment by annando** [comment]
Forum posts in public forums should now automatically be "unlisted". And they should be private in private forums.

**Comment by hoergen** [comment]
Is this a "keep open" or a "close it" ?

**Comment by annando** [comment]
Can you check, if it works like expected? From the coding and from my expectation it should.

**Comment by hoergen** [comment]
Since i don't have a clue what your first answer is heading to with "unlisted" please tell me if this can be closed.

**Comment by annando** [comment]
"unlisted" is public, but the post won't appear in searches or on the community page.

**Comment by hoergen** [comment]
Why it is so hard to get an answer? But I interpret it as "can be closed because it is done".
