### ISSUE TITLE
Friendica as Mozilla Persona identity provider

### ISSUE THREAD

**Issue by fabrixxm** [friendica/friendica#780]
Friendica could act as a [Mozilla Persona](http://www.mozilla.org/en-US/persona/) identity provider, enabling users to log into services using Persona with their 'webbie' (user@server)

**Comment by Beanow** [comment]
Personally I think it should be the other way around. Use a good identity provider server and add support to Friendica to use this as your log-in method.

**Comment by tobiasd** [comment]
closing this as Moz Persona is almost a dead walker
