### ISSUE TITLE
Can we have both a global friendica and a global fediverse community?

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#7802]
This is Probably already being worked on, but it took me some time to realize that global community meant global fediverse, and not global friendica after trying to add friends in that community and it didn't work. An extra global friendica exclusive community would be great as then we could add any of the friends, instead of realizing they were diaspora or mastadon and cant friend them

**Comment by MrPetovan** [comment]
Hi @anubis2814, you can actually friend (=follow) Diaspora and Mastodon accounts from your Friendica account.

**Comment by anubis2814** [comment]
Oh ok, there hve been a few on odd servers I haven't been able to.  I think it'd still be a good idea though probably bottom of your prioties right now.

**Comment by MrPetovan** [comment]
It doesn't sound very complicated to have a community page with Friendica-only contact based on the existing community pages, it would be a good first issue.

**Comment by SpcCw** [comment]
Perhaps it would be cleaner and more logical from UX perspective to extend protocol filter to work on Global Community page as well?

**Comment by annando** [comment]
Well, a protocol filter wouldn't in any case have the expected result. Friendica posts can arrive via DFRN (our own protocol) but also via Diaspora (if received via relay) or via ActivityPub (from newer Friendica installations under certain circumstances).

**Comment by SpcCw** [comment]
> Friendica posts can arrive via DFRN (our own protocol) but also via Diaspora (if received via relay) or via ActivityPub (from newer Friendica installations under certain circumstances).

I noticed that. If there is a easy way to select posts by actual network, maybe this filter should be updated to do this instead? I don't see much use for users to filter posts _by protocol_ while selecting users by network could be interesting, especially if extended to GC page.

**Comment by MrPetovan** [comment]
I'm actually running into the same issue in #7777 where I have to identify Friendica contacts because only them can use remote authentication.

**Comment by annando** [comment]
Filter by "Network" in the meaning of "used software" would be the wrong way. If you would so this, you had to create single filters for Mastodon, Pleroma, Funkwhale, Socialhome, GNU Social, Hubzilla, Kroeg, Misskey, Mobilizon, Osada, Nextcloud, Peertube, Pixelfed, read.as, Wordpress, write.as, zap ... just to name a few.

@MrPetovan concerning your issues we possibly can discuss this in #7777 or in the developer forum. This shouldn't be no issue at all.

**Comment by SpcCw** [comment]
> If you would so this, you had to create single filters for Mastodon, Pleroma, Funkwhale, Socialhome, GNU Social, Hubzilla, Kroeg, Misskey, Mobilizon, Osada, Nextcloud, Peertube, Pixelfed, read.as, Wordpress, write.as, zap ... just to name a few.

Yep and it would be fun exactly because of this :) Of course I don't think there should be hard-coded list of all currently available software for user to choose from. It could be dynamically populated from reasonably recent posts or in similar fashion like existing "Trending Tags".

Anyway if this is not how it works under the hood, it is no big deal, just an idea.

**Comment by MrPetovan** [comment]
> @MrPetovan concerning your issues we possibly can discuss this in #7777 or in the developer forum. This shouldn't be no issue at all.

https://github.com/friendica/friendica/issues/7817#issuecomment-551123191

**Comment by anubis2814** [comment]
If we added protocols as a channel feature option, this option would be very easy to accomplish, but its out of my experience to do.

**Comment by annando** [comment]
See here for all the keywords that you can use in the channels: https://github.com/friendica/friendica/blob/2024.03-rc/doc/Channels.md#additional-keywords-for-the-full-text-search
You can use `platform:friendica` to filter for posts from Friendica.

**Comment by anubis2814** [comment]
Oh cool, I can probably make it more user friendly then.
