### ISSUE TITLE
Show max. image upload size on photo upload page

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7807]
### Expected behavior
Every node has some max image upload size. We should inform the user on the photo upload page about that limit.

### Actual behavior
There is no such info yet.

### Steps to reproduce the problem
Go to the photo upload page https://example.com/photos/$user/upload

![foto-upload](https://user-images.githubusercontent.com/3656054/68083795-7c114200-fe2d-11e9-9020-846ea0c86a19.png)

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
Could this be also a 'Junior Job' (I mean the label)?

**Comment by casperrutten** [comment]
I would like to work on that.
But is the files drop zone already done by someone? Otherwise I would like to work on that too.
For me it is to get some experience with it.
Is there a preferable platform to develop this on? Are there already comparable developments in Friendica? I have to start from scratch, so I want to do it right from the start.

**Comment by MrPetovan** [comment]
Hi @casperrutten, any code editor with PHP auto-complete will do. I personally use PHPStorm (https://www.jetbrains.com/phpstorm/). You will also need a Git client, I can recommend Fork (https://git-fork.com) for Mac and Windows.

What do you mean by "comparable developments"?

**Comment by casperrutten** [comment]
I have git on linux. I already installed the development version with Vagrant on my local desktop. (I have the node running under friendica.vrije-mens.org) With the platform I meant  the script language to use. Are there any default libraries in de Friendica code I can use?

**Comment by MrPetovan** [comment]
Friendica is written in PHP for the backend code, and HTML/CSS/Javascript for the front-end. We use jQuery on all themes, and Bootstrap 2 specifically for the `frio` theme. You can see a list of all JS libraries available site-wide in `view/asset` or in the `composer.json` for all the dependencies with the vendor name `npm-asset` and `bower-asset`.

I'm not aware of a library to do drop-in upload in Friendica, but my knowledge is far from complete. @AlfredSK Where does the drop in display come from?

**Comment by AlfredSK** [comment]
It's from the `js_upload` add-on. :-) It's one of the coolest things we have.

**Comment by MrPetovan** [comment]
Oooooh, shiny.

**Comment by casperrutten** [comment]
Yes, nice, But the valum qq uploader plugin that is used is 9 years old and not maintained any more.
I suggest to use a more uptodate plugin with the possibility to reduce the size to the max upload size. That would be more user friendly. I took a look at dropzone.js and it looks really flexible and usable on different locations of the site.
For the moment I struggle with getting insight in the used code/file structure of friendica. The nearest I get is 'The Quick Template Guide', but it doesn't give any details. Can you give me a hint where I can find this?

**Comment by MarekBenjamin** [comment]
I recently had a related discussion with [Friendica Support](https://forum.friendi.ca/profile/helpers) about that [here](https://friendica.mbbit.de/display/b25b9f4f-5863-6429-6761-bcd789222173):

In my humble opinion, there are two issues which should be addressed / clarified regarding image uploads:

1. In general, for me it was not possible to upload any files with `size > UPLOAD_MAX_FILESIZE`  in `php.ini `. On my instance, this value was set to 2M (2 Megabyte), which I found is quite low. 
2. [Michael Vogel](https://pirati.ca/profile/heluecht) informed me that there is an autoscale feature included in friendica which automatically reduces the resolution of an image in steps of 5120, 2560, 1280 to 640 pixels until the file size is below the values set at the image upload options on the friendica admin site, see screenshot (sorry for the German UI) [https://pirati.ca/display/ec054ce7-6063-642b-166c-838195105492](url)

![Screenshot 2022-11-18 003544](https://user-images.githubusercontent.com/117765478/202582567-262cf3b8-0191-4278-adbc-e4e931c0f97d.png)

For 1. I suggest:

Adding a text on at the image upload section on the admin site that tells something like  
> `size > UPLOAD_MAX_FILESIZE`  in `php.ini ` must be set to accordance of the maximum file size.

and for 2.:

Adding some explaination to the description of the two fields, e.g.: 
> "Maximum file size on the server: If exceeded, the system will automatically reduce the resolution in steps of 5120, 2560, 1280 to 640 pixels during upload until the file size is fallen below ."

**Comment by MarekBenjamin** [comment]
If some can confirm my hypotheses mentioned above, I will try to address both points as a lecture for me to learn to contribute to friendica.

**Comment by MrPetovan** [comment]
A couple answers:
1. The actual maximum upload file size is the minimum of `php.ini:upload_max_filesize` and the `system.maximagesize` config key. The first would trigger an error at the web server level, the second will trigger an error at the application level.
2. This isn't a consistent behavior, sometimes it scales down the picture the way you describe, sometimes it blocks the upload altogether. Check the usages of the `->get('system', 'maximagesize')`.

**Comment by MarekBenjamin** [comment]
Great, thanks for the clarification. So regarding 1. it would be possible to add an information regarding

> php.ini:upload_max_filesize and the system.maximagesize 

I already started to look around a bit in the sources and identified the locations of the string 

> Maximum size in bytes of uploaded images. Default is 0, which means no limits.

of which I think could be firmly extended by the hint that `php.ini:upload_max_filesize` and `system.maximagesize` need to be set to at least the desired limit. 

But at the moment I am confused where to change it. It occurs at least in `lang/C/messages.po` and in `Site.php:470` and unfortunately I am not aware of the mutual dependency between the two locations. I guess the i10n of PHP uses the string as an index to look up translations. If so, I guess changing it only in one place would mess things up. 

I guess I have to dig deeper in PHP i10n with *.po files? 

BTW: Is it a good idea at all to provide the information about  ´php.ini:upload_max_filesize´ and the ´system.maximagesize´  there?

**Comment by MarekBenjamin** [comment]
and for 2., given all the same challenges as above, it would require an additional case for the appropriate text depending on the instance's behavior with file sizes over the limit. 

Which means it needs a check how the instance handles bigger files and then tell the user what happens in this case.
So it would require some kind of string selection for the description of the input field. 

I guess this disambiguation need to be done in `Site.php:470`  where the `$maximagesize` array is initalized?

**Comment by MrPetovan** [comment]
Good question about L10n. The way it works is you make changes to the translation strings in the PHP code (so at least `Site.php`). When you’re done, you have to run the `bin/run_xgettext.sh` shell script, it will update the `messages.po` file that you shouldn’t edit manually.

**Comment by MarekBenjamin** [comment]
Ahh, of course localization I10n and not internationalization i10n, sorry for messing that up. Okay nice, so I need a test setup to learn about the consequences fist, just an edited on GitHub editor won't be sufficient at this point. 

So I am out for the next days creating a test instance, playing around with those strings and maybe come up with a pull request for the tip texts by the end of November. 

In any way, thank you so such for your suggestions and tips.

**Comment by MrPetovan** [comment]
No, thank you for looking into this!

**Comment by MarekBenjamin** [comment]
Is there a good reason we want Admins to define the upload limits in bytes? At least for myself, I am not able to convert "I want to have a limit of, e.g., 8 MB" directly to "I want to have a limit of  8,000,000 Bytes".

**Comment by MrPetovan** [comment]
You can enable the use of shorthands for the config value but the value will need to be converted to a byte number when doing the actual comparison, using the function I directed you in your PR for example.

**Comment by MarekBenjamin** [comment]
As discussed [here](https://github.com/friendica/friendica/pull/12267#discussion_r1032811948), perhaps it is also a good idea to inform the admin on this page whether the amount of bytes for the upload limit are interpreted as MiB (`2**20`) or MB (`10**6`)?

**Comment by MrPetovan** [comment]
Yes, let's use the PHP convention of converting shorthands to binary prefixes, so `2**10` for k/K, `2**20` for m/M and `2**30` for g/G.

**Comment by MarekBenjamin** [comment]
On a second thought: When the admins enter the bytes value without prefix, they don't have to mind about using binary or si prefixes.

**Comment by MarekBenjamin** [comment]
> Yes, let's use the PHP convention of converting shorthands to binary prefixes, so `2**10` for k/K, `2**20` for m/M and `2**30` for g/G.

Totally agreed, anything else would be really messy. But still we have to be aware that it is not perfectly correct since it is a (though widely accepted and obviously even by PHP) double standard for the meaning of unit prefixes. :-)

**Comment by MrPetovan** [comment]
Yes, which means I wholeheartedly support your suggestion to indicate to admins it's using a binary prefix when you get around to implement the shorthands for the config value.

**Comment by MrPetovan** [comment]
This has been closed by https://github.com/friendica/friendica/pull/12267, thanks again @MarekBenjamin !
