### ISSUE TITLE
bbcode to markdown: > in a code block is converted to &_gt_;

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#7808]
### Expected behavior

The `>` should be displayed as such in code blocks and not as `&_gt_;`.

### Actual behavior

When posting a code block like

     [code][guid] => [/code]

it is converted to

    `[guid] =&_gt_; ` 

in Markdown. Without the code block the conversion works as expected.

A `<` will be removed from the markdown output.

### Steps to reproduce the problem

* Look up the babel module (or post some code block and look at the result on a Diaspora* account)
* Craft a code block that contains a `<`  or `>`

Probably related to  #4488

**Comment by nupplaphil** [comment]
Another great opportunity for tests :D

**Comment by MrPetovan** [comment]
Pushed to next release because of expected upstream change in the HTML to Markdown library.
