### ISSUE TITLE
Admin Summary - one line too much

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7821]
### Expected behavior
On admin summary page every line is precious. There shouldn't be a superfluous extra line. ;-)

### Actual behavior
There is one weird extra line in the accounts section of the admin summary page.

### Steps to reproduce the problem
Look at the page. 👀

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Is it just on frio?

**Comment by AlfredSK** [comment]
No. I checked frio and vier. Same issue.

**Comment by AlfredSK** [comment]
![Screenshot_20191106-213406__02](https://user-images.githubusercontent.com/3656054/68335938-b0ab2500-00dd-11ea-8dcb-fbedf7c22e6d.jpg)

**Comment by AlfredSK** [comment]
Ah! Now I get it!
The name of that account type is missing. **It's not an extra (duplicate) line.**

**Comment by MrPetovan** [comment]
I cannot reproduce, can you please paste the page HTML?

**Comment by AlfredSK** [comment]
Hmm. That's completely weird. On the forum node it's very obvious. There are 5 accounts. 3 forum accounts, 1 news account and 1 normal (but non published) account - the admin account.
But the forum node is showing no normal (standard) account but that weird extra line with the number '1'.
I guess non published, hidden accounts do show up in that line at the bottom.

**Comment by AlfredSK** [comment]
> can you please paste the page HTML?

Sorry, I'm on mobile only at the moment. Apparently, mobile browsers have no option to show a page's HTML code.
I'll send it later.

**Comment by AlfredSK** [comment]
Ok. I'm home again. Having a laptop again, finally. :-)

I have only copied the part of the HTML code where the account stats are coded:

```
	<div id="admin-summary-wrapper">
				<div id="admin-summary-queues" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Message queues</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry"><a href="https://libranet.de/admin/queue/deferred">3752</a> - <a href="https://libranet.de/admin/queue">487</a></div>
		</div>

				<div id="admin-summary-pending" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Pending registrations</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">0</div>
		</div>

				<div id="admin-summary-users" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Signed up users</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">1054</div>
		</div>

						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Standard account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">957</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Automatic follower account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">58</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Public forum account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">18</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Automatic friend account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">8</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Blog account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">0</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted">Private forum account</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">6</div>
		</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-summary">
			<hr class="admin-summary-separator">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 admin-summary-label-name text-muted"></div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 admin-summary-entry">7</div>
		</div>
```

As you can see the last div class is the weird one.

**Comment by MrPetovan** [comment]
Indeed, I don't have any additional line on my single-user node, I'll check the code tonight EST.

**Comment by AlfredSK** [comment]
Can this be related to #7825 ? The bug is producing bogus accounts (registration fails but an incomplete account may be created nonetheless).

**Comment by AlfredSK** [comment]
Probably all caused by #7812

**Comment by MrPetovan** [comment]
Can you please run ``SELECT `page-flags`, COUNT(*) FROM `user` GROUP BY `page-flags`;`` on your database and report the results?

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> SELECT `page-flags`, COUNT(*) FROM `user` GROUP BY `page-flags`;
+------------+----------+
| page-flags | COUNT(*) |
+------------+----------+
|          0 |      960 |
|          1 |       58 |
|          2 |       17 |
|          3 |        8 |
|          5 |        6 |
|        255 |        8 |
+------------+----------+
6 rows in set (0.00 sec)

```

**Comment by AlfredSK** [comment]
And the corresponding numbers from the admin summary:

```
Standard account 960
Automatic follower account 58
Public forum account 17
Automatic friend account 8
Blog account 0
Private forum account 6
                    8
```

**Comment by AlfredSK** [comment]
What is the `'page-flags' = 255` anyway? Some kind of fall back when no account type has been set?

**Comment by annando** [comment]
There is no obvious code where the 255 can come from.

**Comment by MrPetovan** [comment]
I looked into it as well, and I'm equally stumped.

**Comment by AlfredSK** [comment]
At first I thought that those 255er accounts where incomplete accounts created during the "tar pit incident" but then I checked the forum node. That crushed my theory.

The forum node is on develop as well. It has three forum accounts, one news account and one special admin account.
That admin account is not published, not listed in directories and as much hidden as possible. 
But it is a normal, personal account. So it should show as personal account (standard, page-flag = 0) but in fact it is listed in that weird div class with page-flag = 255.

**Comment by AlfredSK** [comment]
Question: what's the difference between the fields 'page-flags' and 'account-type' in table user? The account types are correct even when 'page-flags' = 255.

Example: my own account
nickname = alfred
account-type = 0
page-flag = 255

**Comment by AlfredSK** [comment]
Ok. I changed the field for my own user from 255 to 0. Then I went to my user settings changed a random setting and saved it.
Bamm! The 255 is back when I check the database.

**Comment by AlfredSK** [comment]
When I check my account type in my user settings. The radio button at 'personal account' is on/set. BUT in the subsection (which type of personal account) NO radio button is on/set.

When I set the subtype 'standard' and then save it the radio button in the subtype section is vanished again.

It seems that setting that subtype isn't possible and that triggers the weird page-flag 255.

Could this be the bug?

**Comment by MrPetovan** [comment]
I found the bug, you're going to laugh.
