### ISSUE TITLE
Registration broken with policy approval

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7825]
### Expected behavior
Registration should work with register policy approval.

### Actual behavior
If the admin has enabled registrations with approval a registration attempt gives an error 500 page. 

"POST /register HTTP/2.0" 500 357 "https://libranet.de/register"

The user will not get a mail with the registration details but the nickname is nonetheless "already in use" afterwards.

I wondered why I see the number of users of my node growing without any new users visible in the admin/users page.

The 'tarpit' PR introduced this bug (I think). #7812

See also: https://github.com/friendica/friendica/issues/7675#issuecomment-552009327

### Steps to reproduce the problem
Enable registrations with approval by the admin. Try to register an account.

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
My other issue #7821 could be a symptom of this bug.

**Comment by MrPetovan** [comment]
Possibly fixed with https://github.com/friendica/friendica/commit/babcd244125d37a84b786399d58646738c012d70

**Comment by AlfredSK** [comment]
I'll check it later today. Thank you!

**Comment by AlfredSK** [comment]
Ok. Tested again. Works! 🎉
