### ISSUE TITLE
Sort order of published RSS feeds should be "inbound date" not entry creation date

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7835]
I'm using a TTRSS Feed Reader server to create one RSS feed out of different feeds that I distribute with friendica . The problem is, that the friendica is sorting the entries of that rss feed by the original  publishers creation date.

So when I send a post that is 3 weeks old from my rss feed to friendica, I won't see that post in my timeline until I scroll back 3 weeks.

So as I understood, we do normaly sort the timeline after inbound (arrival on the node) date and time. We should do that as well with rss feeds. It is also very confusing, when you add an rss feed as a contact where the last rss entry is some days ago and you don't see anything in your current timeline..

### Expected behavior

1. add rss feed as contact
2. sort by inbound (node arrival) date and time
3. see all rss entries in your timeline, when friendica fetches the information

### Friendica version you encountered the problem
develop (14.11.2019)
git
php 7.2
mariadb

**Comment by AlfredSK** [comment]
Huh? Your described expected behavior is exactly what we already have. The post order is by 'time of arrival'. That's also true for feed contacts from my experience.

**Comment by hoergen** [comment]
I checked it yesterday and today with two rss feeds and it is the behavior i described above. That's why i opened this issue. Otherwise there wouldn't be a reason to open an issue ;)

**Comment by hoergen** [comment]
Still testing. Seems the normal operation, when a feed is already connected and "new old" posts  are incoming, they are posted in the "incoming order". But when you connect a new rss feed to friendica the first import doesn't do that.

**Comment by hoergen** [comment]
Still testing and the result is **not** continuously the same.

For example: I added today news from some days ago to the rss feed that feeds a friendica account. The added articles are shown with the date, when they are posted on the original news site and not when they are imported in friendica.

Last week it took the imported date.

**Comment by hoergen** [comment]
Current example

1. current date time: 29.11.2019 - 06:05
2. added an article from 21.11.2019 00:00 to the rss feed to feed the friendica "Nachrichten" account
3. Friendica imports that article with date time 21.11.2019 00:00 

So I only can find this article with my personal account, when scrolling back in time. one week.

![00_temp](https://user-images.githubusercontent.com/24474762/69845346-ae696000-1270-11ea-8df8-e1c2b17c8c31.png)e

Or opening "Nachrichten" (my contact) and then the display is even more weird: It displays the "older" article after a new article

so the order is 
1. first (older) article is one week old
2. second (newer) article is 19 hours old

![01_temp](https://user-images.githubusercontent.com/24474762/69845553-5aab4680-1271-11ea-881a-adeaa4e53728.png)

**Comment by MrPetovan** [comment]
The displayed date is still the created date, even if the received date is later. This explains why the `week old post shows up before the 19 hours old post, it's been received more recently. You shouldn't have to scroll back one week to find the 1 week old post if you're following the Nachrichtenkanal account. The post will show up shortly after 29.11.2019 - 06:05 in your network tab, no matter what the created date says.

**Comment by hoergen** [comment]
Yes I thought that too. On the "Nachrichten" account everything is like you would expect, but on my personal account the post is one week back. 

Both accounts are on the same node, maybeif there is a difference, if both accounts are on different nodes?

**Comment by annando** [comment]
In PR https://github.com/friendica/friendica/pull/7877 there is a new config value. If enabled you not only see the creation date but also the receipt date of a post.

**Comment by hoergen** [comment]
Where is this option available? In a config file? In the user preferences or site preferences?

**Comment by hoergen** [comment]
Ah ... so i should set this in config file?

```
	// show_received (Boolean)
		// Show the receive data along with the post creation date
		'show_received' => true,
		// show_received_seconds (Integer)
		// Display the received date when the difference between received and created is higher than this.
		'show_received_seconds' => 500,
```

**Comment by annando** [comment]
Currently it is only in a config file. If useful, we can always extend this as a user config value. But I created it mostly for debug purposes.

**Comment by hoergen** [comment]
Ok the patch worked fine, but the original (title) problem still exists ;)
I don''t see added news in my current timeline, even the news post says "created a week ago and recieved 5 minutes ago". I have to scroll back aka search in the contact timeline.

**Comment by annando** [comment]
The sorting should be after the "received" date on the network page. Isn't that the case?

**Comment by hoergen** [comment]
Did you change something? If not, it is like I described it.

**Comment by hoergen** [comment]
watched it for some time and im on develop now. It seems to be fixed.
