### ISSUE TITLE
[twitter] Hashtags with the same prefix gets replaced with a link to the prefix

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7838]
### Expected behavior

Each hashtag links to the search page of its full length

### Actual behavior

Hashtags with the same prefix  a previous hashtag get half-replaced with a link to the search page of the previous hashtag

Example:

`#hash #hashtag` get replaced by `(#hash) (#hash)tag` instead of `(#hash) (#hashtag)`

Technical information; This happens because we replace *all* `#hash` before trying to replace *all* `#hashtag` which doesn't exist anymore after the first replace. A remediation would be to make sure the replace is only preformed once by taking advantage of the `count` parameter of `str_replace`, see https://www.php.net/manual/en/function.str-replace.php

**Comment by harrycoulton** [comment]
Hi, I'd like to help out with this. Can I be assigned and take a look at it?

**Comment by MrPetovan** [comment]
Hi @harrycoulton and thanks for your offer, unfortunately GitHub only allows team members to be assigned a specific issue, but it's all yours.

**Comment by schmaker** [comment]
I think this issue is obsolete after end of Twitter API
