### ISSUE TITLE
Make mentions split on more characters

### ISSUE THREAD

**Issue by silverwizard** [friendica/friendica#7849]
### Expected behavior

I attempted to take @mwlucas@bsd.network in this post https://friendica.obscuritus.ca/display/0c40ea67-115d-d616-1ab3-dcf055591288 . The original post didn't have the space between @mwlucas@bsd.network and the 's which made it not show as a mention

### Actual behavior

@mwlucas@bsd.network's would understand that the ' was not in the URL

### Steps to reproduce the problem

Attempt to mention someone, then place a punctuation character

### Friendica version you encountered the problem

This is Friendica, version 2019.09 that is running at the web location https://friendica.obscuritus.ca. The database version is 1323, the post update version is 1322.

### Friendica source (git, zip)
git

### PHP version
$ php -v 
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
$ 

### SQL version
MariaDB [(none)]> select @@version;
+--------------------------+
| @@version                |
+--------------------------+
| 10.1.37-MariaDB-0+deb9u1 |
+--------------------------+
1 row in set (0.00 sec)

MariaDB [(none)]>

**Comment by annando** [comment]
I just tested it on the current version, it worked for me.
