### ISSUE TITLE
contacts page: better info on which format is wanted to add / find users

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#786]
This is three wishes in one report:

When on the contact page, it is not obvious, which format is expected to add new users. Currently it is:

user@example.org

1) I suggest showing exactly that in light-grey color in the add-user text-box. That way the user knows exactly which format is expected.

2) If another format like the URL is entered, show an informative error message indicating which format to use for this function to work.

3) Allow the user to paste an URL of a contact that should be added.

If anything is fixed, we can either close this as a whole and I can create separate issues for the remaining items or wait for all three to be fixed.

**Comment by annando** [comment]
For several versions it is possible to enter the contact address in various ways. So I'm closing the issue.
