### ISSUE TITLE
Missing/Broken client API

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#7863]
I run Friendica 2019.09  and Fedilab 2.25.0. I know that it worked in the past and I'm not sure if a Friendica or a Fedilab update broke it. But I can no longer access Friendica with Fedilab. If I try to reload my timeline I get this error in the apache access.log:

````
89.244.184.74 - bjoern [24/Nov/2019:13:13:47 +0100] "GET /api/v1/timelines/home?limit=20 HTTP/1.1" 501 4068 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:13:48 +0100] "GET /api/v1/timelines/home?limit=20 HTTP/1.1" 501 4068 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
````

When I switch to the Friendica account from a different account on Fedilab I see this messages in the access.log:

````
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/instance HTTP/1.1" 501 4035 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/filters HTTP/1.1" 501 4050 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - - [24/Nov/2019:13:17:31 +0100] "GET /.well-known/nodeinfo HTTP/1.1" 404 4101 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/timelines/home?limit=20 HTTP/1.1" 501 4068 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - - [24/Nov/2019:13:17:31 +0100] "GET /api/v1/instance HTTP/1.1" 501 4051 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/conversations?limit=20 HTTP/1.1" 501 4066 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/accounts/verify_credentials HTTP/1.1" 501 4072 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/notifications?limit=15 HTTP/1.1" 501 4066 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/custom_emojis HTTP/1.1" 501 4057 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
89.244.184.74 - bjoern [24/Nov/2019:13:17:31 +0100] "GET /api/v1/notifications?exclude_types[]=follow&exclude_types[]=favourite&exclude_types[]=reblog&exclude_types[]=poll&limit=15 HTTP/1.1" 501 4159 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
````

**Comment by annando** [comment]
I'm mostly sure that it is a fedilab issue. I saw some possibly related discussions the last days.

**Comment by AlfredSK** [comment]
Fedilab released the update 2.25.1 that addresses the 501 issue.

**Comment by AlfredSK** [comment]
...but this one isn't a good sign:
`"GET /.well-known/nodeinfo HTTP/1.1" 404`
The nodeinfo couldn't be found.

**Comment by AlfredSK** [comment]
Oops! I'm getting a lot of 'invalid consumer key' errors but Fedilab is working nonetheless. :-/

`index [WARNING]: API login - error {"module":"api","action":"login","exception":"Invalid consumer key"} - {"file":"api.php","line":194,"function":"api_login","uid":"d9ba70","process_id":11313}`

**Comment by schiessle** [comment]
I updated now to Fedilab 2.25.1 but problem is still the same.

**Comment by annando** [comment]
Have you tried to enable nodeinfo?

**Comment by schiessle** [comment]
after I enabled nodeinfo this request returns 200:

````
89.247.40.229 - - [26/Nov/2019:23:07:17 +0100] "GET /.well-known/nodeinfo HTTP/1.1" 200 4172 "-" "Dalvik/2.1.0 (Linux; U; Android 9; Mi MIX 2 Build/PQ3A.190801.002)"
````

but the other 501-errors stay the same.

**Comment by annando** [comment]
Can you open an issue that Fedilab as well? Possibly they know better what the problem is.

**Comment by schiessle** [comment]
Corresponding Fedilab ticket: https://framagit.org/tom79/fedilab/issues/365

**Comment by schiessle** [comment]
I was pointed to the solution here: https://framagit.org/tom79/fedilab/issues/365

Fedilab 2.25.1 solved the problem (nodeinfo is needed) but you need to logout and login again to make it work.

**Comment by annando** [comment]
The always enabled Nodeinfo will soon come: https://github.com/friendica/friendica/pull/7873
