### ISSUE TITLE
federation with pixelfed - images missing on incoming posts

### ISSUE THREAD

**Issue by guzzisti** [friendica/friendica#7868]
### Expected behavior
When following an user on a pixelfed instance the complete including text and image is shown in the timeline.

### Actual behavior
When a pixelfed posts is received via ActivityPub, the images are missing in the content.

### Steps to reproduce the problem
- follow an user on pixelfed
- wait for a post to be federated to your instance

### Friendica version you encountered the problem
2019.12-dev 
1324

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
5.7

**Comment by annando** [comment]
Since when does this happen? I had experienced this as well, but only since a few days (possibly last week).

**Comment by guzzisti** [comment]
I can only guess, as i only follow a few not-so-active pixelfed accounts. I believe it worked with 2019.09 and may be broken since i updated to the current develop branch. But thats only a rough guess.

I opened the issue because of a comment of @pixelsalat@squeet.me that image federation does not work for her either.

**Comment by tobiasd** [comment]
For me it worked Oct 6th, but it did not work Nov 14th. Just checked with a pixelfed account I'm following.

**Comment by annando** [comment]
Is fixed by PR https://github.com/friendica/friendica/pull/7875
