### ISSUE TITLE
DB: 'config' -> 'allowed_themes' is storing (a lot of) redundant data

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7881]
### Expected behavior
The field `v` for `k = allowed_themes` in DB table `config` should contain a comma seperated list of the allowed themes of the node. Every allowed theme should be stored once in that list.

### Actual behavior
``SELECT `v` FROM `config` WHERE `k` LIKE 'allowed_themes'`` 
``duepuntozero,frio,quattro,smoothly,vier,frio,frio,frio,frio,frio,frio,vier,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,quattro,quattro,frio,frio,frio,duepuntozero,quattro,smoothly,vier,frio,frio,quattro,vier,vier,vier,vier,vier,vier,frio,frio,quattro,smoothly,vier,duepuntozero,frio,frio,frio,frio,vier,vier,vier,vier,vier,vier,vier,vier,vier,vier,frio,vier,frio,vier,frio,frio,vier,frio,quattro,vier,duepuntozero,quattro,smoothly,frio,duepuntozero,vier,smoothly,quattro,frio,vier,frio,frio,quattro,duepuntozero,smoothly,vier,vier,frio,quattro,smoothly,vier,smoothly,duepuntozero,vier,vier,vier,vier,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,duepuntozero,frio,frio,quattro,smoothly,vier,vier,vier,vier,vier,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,vier,smoothly,quattro,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,duepuntozero,duepuntozero,duepuntozero,quattro,smoothly,vier,frio,frio,quattro,duepuntozero,frio,frio,frio,frio,frio,frio,quattro,duepuntozero,vier,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,quattro,quattro,quattro,quattro,frio,vier,frio,frio,vier,quattro,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,duepuntozero,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,quattro,smoothly,duepuntozero,vier,frio,vier,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio,frio`` 

What the heck? :-)

### Steps to reproduce the problem
``SELECT `v` FROM `config` WHERE `k` LIKE 'allowed_themes'`` 

### Friendica version you encountered the problem
2019.09 and 2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDD

**Comment by MrPetovan** [comment]
🤣

**Comment by nupplaphil** [comment]
should be fixed with #7885 
Pulling & Pushing themes are now checked for their uniqunes ;-)
