### ISSUE TITLE
[API] Provide post/contact search

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7889]
Part of #6739

If provided with a valid post URL, this API endpoint should return a list of posts identified by this URL (expectedly only one) in the format of the home timeline.

If provided with a valid account webfinger/profile URL, this API endpoint should return a list of contacts identified by the input (expectedly only one) in the format of the contact list.

**Comment by annando** [comment]
We should tag the API requests with a milestone. This is very important to implement, I think.

**Comment by MrPetovan** [comment]
Is there an existing API endpoint for search or is this something that has to get created?

**Comment by annando** [comment]
We do have some endpoint, I'm not sure if this works.

**Comment by MrPetovan** [comment]
I don't mind if it currently works or not, I just want to know if I have to create one or reuse an existing one.

**Comment by annando** [comment]
Best is to have a look at Twitter's API of the different search endpoints. Then you can have a look at include/api.php if the endpoint is registered there.

**Comment by MrPetovan** [comment]
Ok thanks, I was going to do it anyway, but it's easier if someone already knows.

**Comment by MrPetovan** [comment]
Closed by #7941

@stom79, you can test with Fedilab

**Comment by stom79** [comment]
Sorry, I replied here: https://github.com/friendica/friendica/pull/7941#issuecomment-568016020
That's great!
