### ISSUE TITLE
"Link to source" for hubzilla & Friendica is broken

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7892]
### Expected behavior
Clicking on the frio menu on the right side of a post "Link to source" should lead you to the post on the original server

### Actual behavior
The post can' be found.

Post on friendica https://horche.demkontinuum.de/display/64da3b94-1b34-4f95-ac21-4a7faf5c53e4

1. Url that friendica has for "Link to source" https://hubzilla.eu/channel/cb7f604332cf39/?mid=64da3b94-1b34-4f95-ac21-4a7faf5c53e4
2. Hubzilla URL https://hubzilla.eu/channel/cb7f604332cf39/?f=&mid=b64.aHR0cHM6Ly9odWJ6aWxsYS5ldS9pdGVtLzY0ZGEzYjk0LTFiMzQtNGY5NS1hYzIxLTRhN2ZhZjVjNTNlNA

### Steps to reproduce the problem
Do the share ping pong (friendica -> hubzilla -> friendica)

### Friendica version you encountered the problem
git / develop / PHP7.3 / MariaDB

**Comment by hoergen** [comment]
As well link to source in friendica is broken .
When clicking on a "link to source" in my timeline it sends me to 

`https://snarl.de/display/0bf23919-285d-f3e1-c8de-0de519586967addr=https%3A%2F%2Fsnarl.de%2Fprofile%2Fbuecherratte?owt=f5ddec30e62af2cc622e992208a33928`

but the correct URL is (without magic token)

`https://snarl.de/display/0bf23919-285d-f3e1-c8de-0de519586967`

**Comment by hoergen** [comment]
Maybe only the "?" is lacking.  The following URL works

`https://snarl.de/display/0bf23919-285d-f3e1-c8de-0de519586967?addr=https%3A%2F%2Fsnarl.de%2Fprofile%2Fbuecherratte?owt=f5ddec30e62af2cc622e992208a33928`

**Comment by hoergen** [comment]
Still problems with that 

The URL i get in Friendica with a public post on hubzilla https://labonneheure.ch/channel/emanuel/?mid=251386dd-781f-4869-a30e-4581a73af64b

This throws an error "Permission denied" on the original site

The original URL is https://labonneheure.ch/channel/emanuel/?f=&mid=b64.aHR0cHM6Ly9sYWJvbm5laGV1cmUuY2gvaXRlbS8yNTEzODZkZC03ODFmLTQ4NjktYTMwZS00NTgxYTczYWY2NGI

**Comment by MrPetovan** [comment]
Fixed by #8454, can you please confirm?

**Comment by hoergen** [comment]
Yes it seems to work. Thank you 🌻
