### ISSUE TITLE
[API] - Returns more object with statuses

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#7899]
### Expected behavior
For dealing with statuses, it would be nice to get mentions and cards.
### Actual behavior
The object `user_mentions` seems to always return an empty array. Also, I did't find an easy way to deal with cards
### Steps to reproduce the problem
Call to a timeline endpoint such as `statuses/public_timeline` to get the json array of statuses.
### Friendica version you encountered the problem
2019.12-dev
------
It would help if Friendica uses the Account and Status objects close to the Mastodon API (I know it's planned).

Not everything should be implemented but having cards, mentions, tags will improve the way to deal with timelines. Also, instead of the  `/redirect/_id_` relative URL from href in statuses, it would help to to use the full URLs to the profile, because the app parses some elements from them.

Thanks for your help.

**Comment by annando** [comment]
What do you mean with "cards"?

**Comment by stom79** [comment]
It's an object containing information about the embedded link (could be a mention, a link to a website, etc.)
https://docs.joinmastodon.org/api/entities/#card

**Comment by annando** [comment]
Ah okay. I would prefer adding such stuff to the new endpoints. To explain the reason: Since some time we are refactoring the whole code. We moved from procedural structures to a class driven system. The API is one of the very last places that still are procedural. The new endpoints will be build with classes and the router mechanism - so I would prefer concentrating all work there.

**Comment by MrPetovan** [comment]
I've already started to map the Mastodon Account entity to Friendica contacts for my work on the Follow Requests endpoint. We'll add support for additional entities as we add support for more Mastodon endpoints. None of the existing Friendica/Twitter endpoints should be affected.

**Comment by annando** [comment]
@MrPetovan when you work on the API, I would suggest that we - at the moment - would rely on the authentication that is done via the old API endpoints. Doing so, we could add the new endpoints step by step (and @stom79 could add them to the application). And at some point we could then add the Mastodon login mechanism as well.

**Comment by MrPetovan** [comment]
That's what I've been doing so far. I'm restraining myself from rewriting too much API stuff, I'm focusing on adding the new endpoint.

**Comment by stom79** [comment]
Do you have a dev instance where I will be able to test Fedilab with new endpoints? Also, I plan to support newer and older releases of Friendica. I think that it could be nice to indicate in nodeInfo the api used. Thanks for your work.

**Comment by MrPetovan** [comment]
https://libranet.de is regularly updated with the latest `develop` code thanks to @AlfredSK

**Comment by MrPetovan** [comment]
> I think that it could be nice to indicate in nodeInfo the api used. 

Interesting, how so? We have partial support for Twitter API, and we're introducing partial support for Mastodon API as well. How can we show the partiality degree between Friendica versions?

**Comment by AlfredSK** [comment]
> Do you have a dev instance where I will be able to test Fedilab with new endpoints?

Yes, on libranet.de I pull from develop at least once a day - sometimes even more often. :-) If you need a test account on a node that runs current stable code (master) feel free to register on https://venera.social .

**Comment by stom79** [comment]
Thanks @AlfredSK, great to know that my Friendica account on Libranet will allow me to test dev changes quickly :+1:

**Comment by stom79** [comment]
> Interesting, how so? We have partial support for Twitter API, and we're introducing partial support for Mastodon API as well. How can we show the partiality degree between Friendica versions?

I know that Pleroma lists its api in node info under a `features` point:

`"features":["pleroma_api","mastodon_api","mastodon_api_streaming","polls","pleroma_explicit_addressing","media_proxy","chat","relay"]`

https://pleroma.fr/nodeinfo/2.1.json

They don't display a degree but if you want to keep the Twitter API with the mastodon API, maybe listing endpoints?

On my end, that's true that I can easily know what endpoints will be available by following release notes and check the version of Friendica in node info.

**Comment by MrPetovan** [comment]
Thanks for the hints!

**Comment by annando** [comment]
I wouldn't want to add "pleroma_api" or "mastodon_api" as long as this is 100% covered. But we now always publish the nodeinfo. And there we not only publish the Friendica version but also the database version that can act like some "build" number.

**Comment by annando** [comment]
Since we are now covering the Mastodon API, I guess this issue is solved.
