### ISSUE TITLE
Module\Objects to redirect to the reshared item instead of errorring out

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7900]
Follow-up to #7898 

https://github.com/friendica/friendica/blob/9a4240c3b2f1d31a60f823223dcbb9b24d67e20d/src/Module/Objects.php#L45-L49

The module should redirect to the shared item instead of throwing a Not Found error when the activity is a reshare.

**Comment by annando** [comment]
See my comment that I made on the other issue - before seeing that you already created this issue:

> I thought about it. This would be wrong. System would want to fetch this URL, but will be redirected to another one. This could confuse systems and wouldn't serve any purpose. It would be an idea if this was some front end endpoint - but this is purely a machine endpoint.

**Comment by MrPetovan** [comment]
Fair enough.

**Comment by annando** [comment]
BTW: I already coded it - and then realized the potential problems behind this.
