### ISSUE TITLE
[frio] Composer Modal jot new permission tab doesn't show connectors

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7902]
The new compose popup from frio is broken because it doesn't show the connectors any more

### Friendica version you encountered the problem
git / develop / PHP7.3 / MariaDB

**Comment by hoergen** [comment]
Revert commits to this one and you got it back.

`git checkout 0641212187b4650cdc066b19fe60a76211d20fa4 .`

**Comment by AlfredSK** [comment]
I don't see the connector setting on the /compose page as well.

**Comment by MrPetovan** [comment]
Caused by #7897
