### ISSUE TITLE
Buffer no longer allow creation of new apps

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#7916]
As the friendica-addons respository doesn't allow "issues", I create it here. Please let me know if there is a better place to report issues with some of the addons.

I just tried to connect my Friendica server to Buffer in order to cross-post to LinkedIn. But I learned that since October it is no longer possible to create a app at Buffer to use the API. :cry: 

Not sure if there are now other ways to use the API or if they want to shutdown the API completely. Does someone already looked into it and knows more?

**Comment by annando** [comment]
This here is the right place for the addons as well. We hadn't looked deeply into the Buffer addon for some time. Can you provide some log file stuff? When posting there should be some entries with "buffer.php" in its name.

**Comment by schiessle** [comment]
Ah, sorry. I forgot the add the URL. The problem is not the Plugin but that Buffer disables the possibilities to register new apps on their side (see "October 14, 2019: New application registration closed"): https://buffer.com/developers/api/logs

It seems that LinkedIn has it's own API so for LinkedIn it might be possible to have a dedicated addon, like for Twitter in the future: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin

**Comment by annando** [comment]
Sad to hear that the API shut down. So yeah, we will deprecate this addon.

Since I don't have a LinkedIn-Account, someone else has to provide some connector.

**Comment by annando** [comment]
@schiessle Could you open an issue for directly supporting LinkedIn? Then I guess that we could close this issue here.

**Comment by schiessle** [comment]
Done: https://github.com/friendica/friendica/issues/7918
