### ISSUE TITLE
[API] Rewrite followers/ids and friends/ids to output expected data

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7920]
Both Twitter endpoints `api/followers/ids` and `api/friends/ids` wrongly return the same data when one should returns followers, the other follows.

Found while rewriting the API docs for #7904

**Comment by annando** [comment]
Please have a look at this line:
```INNER JOIN contact AS pcontact```

It is an SQL alias for the table ```contact```.

**Comment by MrPetovan** [comment]
Ooooh. They still wrongly both return the same data when one should returns followers, the other follows.

**Comment by annando** [comment]
Yes. This doesn't look right.

**Comment by MrPetovan** [comment]
Fixed by #7943
