### ISSUE TITLE
Encrypt session data

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#7933]
During my `Session` class refactoring, I found something interessting at the nextcloud codebase (which is sometimes my source for new ideas ;-) ):

https://github.com/owncloud/core/pull/17866

owncloud introduced encrypting the session data, so no other user is capable of reading it through direct access. It seems like a serious security issue.

So I think in a followup release, we should add a encryption for Session variables too.

**Comment by MrPetovan** [comment]
What's the point? Who can access session data?

**Comment by Quix0r** [comment]
@MrPetovan Normally the session data is stored as a file on the server's file system. Means basically the local system administrator can reach it (if application is not properly secured, also external people can read it through an inclusion attack, **theoretically**).

But newer PHP versions does encryption of session data by default. It is some `php.ini` setting.

**Comment by Quix0r** [comment]
So I think today this is relatively pointless as it is "transparently" done by PHP itself.

**Comment by nupplaphil** [comment]
Closed due valid arguments against it ;)
