### ISSUE TITLE
Friendica Installation Fails 2019.12-rc

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7934]
After
git clone https://github.com/friendica/friendica.git -b 2019.12-rc sozica
cd sozica
bin/composer.phar install --no-dev
git clone https://github.com/friendica/friendica-addons.git -b 2019.12-rc addon

After cloning Github I get a 404 page when I go to the main url 
Is it possible that the install.php is missing in the main directory?

**Comment by MrPetovan** [comment]
Still need to rename `.htaccess-dist` to `.htaccess` for Apache installs.
