### ISSUE TITLE
Drag&Drop of images in Composer

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#7937]
In order to standardize the functions and to offer a better user experience, the existing Drag&Drop function for uploading images should also be offered in Composer. It would be optimal to copy the content directly into the composer and output it.
![Drag_and_Drop_Compose](https://user-images.githubusercontent.com/44441246/70709542-653bf600-1cdd-11ea-9c88-45b663d424f8.png)

**Comment by AlfredSK** [comment]
Also great but duplicate of #6249 .

**Comment by MrPetovan** [comment]
Duplicate of #6249
