### ISSUE TITLE
frio: visual glitch with 'active tab indicator' on .../contact/123456

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7946]
### Expected behavior
The active tab indicator on a contact page should always indicate the active tab.

### Actual behavior
With Friendica contacts there is an additional tab 'Common Friends'. That seems to confuse the active tab indicator.

![20191213210043](https://user-images.githubusercontent.com/3656054/70828486-b6d2a680-1deb-11ea-85fb-bb09e8721b8e.png)

When you click on 'Advanced' the tab indicator is shown under 'Common Friends'. 
When you click on 'Common Friends' the tab indicator is shown under 'Contacts'.

### Steps to reproduce the problem
Go to your contacts page. Click on the little grey man (view contact) of one of your Friendica contacts and follow the description above.

### Friendica version you encountered the problem
2019.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Fixed by #7948

**Comment by AlfredSK** [comment]
That was quick! :-)

**Comment by MrPetovan** [comment]
Indeed!

**Comment by annando** [comment]
I'm just waiting for the test to finish - which sadly is slow again.

**Comment by MrPetovan** [comment]
Should be done in the next 2 minutes.

**Comment by AlfredSK** [comment]
root@librabox2 ~/html/libranet # git pull_

...waiting...

**Comment by AlfredSK** [comment]
Works! Thank you.
