### ISSUE TITLE
[frio] Self contact hovercard shouldn’t show follow and private message action buttons

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7953]
Self-explanatory.

**Comment by annando** [comment]
I can unfollow myself - which adds some interesting psychological situation :-)

**Comment by tobiasd** [comment]
Why is the *self* contact shown at all?

**Comment by MrPetovan** [comment]
Your own post show your public contact avatar and name. On any other theme than frio, contact are relegated to the contact page, which you don’t have access to for your public contact, it’s just your profile page. But on frio we show a hovercard whose display depends on the contact record itself, hence the confusing action buttons display.

**Comment by tobiasd** [comment]
I see :-)

**Comment by MrPetovan** [comment]
Fixed by #7957
