### ISSUE TITLE
Can't add some users to groups when initially setting contact up

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#7991]
### Expected behavior
Being able to add a new contact to any/all contact groups that I'd like.

### Actual behavior
When adding in several users recently, I found that trying to add the user to various groups would very quickly un-check after checking the group box - this is prior to that user allowing the contact connection.  At points in the past, this behaviour wasn't noticed.

### Steps to reproduce the problem
Try to add in some new users and add them to a variety of your configured groups.

### Friendica version you encountered the problem
2019.12-rc

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
MariaDB 10.3.18

**Comment by realkinetix** [comment]
Discussed at https://social.isurf.ca/display/c443a55c-755d-fc5b-2b68-5b6525558544

**Comment by MrPetovan** [comment]
So, erroring out on pending contact is currently expected, shouldn't it?
