### ISSUE TITLE
frio: visual glitch with 'new post' button

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8013]
### Expected behavior
When the `network` page or `profile/$user` page is loaded or reloaded the 'new post' button should be displayed immediately at the right place.

### Actual behavior
There is a visual glitch when the page is loaded/re-loaded. The 'new post' button is initially rendered at the wrong place.

You can see it for a fraction of a second in the top corner of the first post. Then it jumps into the right position in the tab bar. This also leads to the situation that all the content in the posts has to be re-rendered/re-sized after the button left the initial (wrong) position.

![frio-issue-icon_20191225131055](https://user-images.githubusercontent.com/3656054/71450856-36f0f880-276a-11ea-9c1a-20552455ca04.png)

**Discussion:**
https://forum.friendi.ca/display/0b6b25a8-515e-0354-a17e-8e7659288422

### Steps to reproduce the problem
Load/re-load the network or profile page and watch closely at the top-right corner of the first post and what happens to the content of the posts.

Tested with Chromium, Opera and Firefox.

### Friendica version you encountered the problem
2019.12

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
This is the way @Rabuzarus found to stick a button in this place since using the tab bar header template wasn’t possible. So the button is added later, then repositioned using Javascript when the page is done loading.

**Comment by AlfredSK** [comment]
Hmm. OK. I understand. But then somethinmg must be different now. I never saw the post button at that initial/wrong position before. Now I can clearly see the button there for 0.5 to 1 second. This looks really like an error. Also, that resizing of the post column is not nice.

I must admit I noticed that behavior for some weeks. But only now I felt like I have to report it. ;-)

Maybe we can change that somehow? Maybe in a way that the button isn't visible at the initial position and the post column doesn't resize. Would that be possible?

**Comment by MrPetovan** [comment]
Yes, that would be a good idea.

**Comment by rabuzarus** [comment]
as far as I could remember the post button should be hidden on its original position through css

**Comment by MrPetovan** [comment]
Welcome back!

**Comment by AlfredSK** [comment]
Have not noticed that in a while. Closing.
