### ISSUE TITLE
[vier] Add received date display to posts

### ISSUE THREAD

**Issue by Ravenbird** [friendica/friendica#8014]
### Expected behavior

When you open the network, Theme Vier does not show when a post has been synchronized and therefore ended up at this point. This creates the impression that old posts are listed before newer posts, although the posts should be sorted by the time they were created.

With Vier it looks like this:

![](https://files.coding4.coffee/selif/xtstzqjs.jpg)

With Frio it looks like this:

![](https://files.coding4.coffee/selif/1t17y48w.png)

### Steps to reproduce the problem

Fix the Vier Theme.

### Friendica version you encountered the problem

Friendica version: 2019.12

**Comment by MrPetovan** [comment]
We started sorting by receiving date because native reshares (sharing without a quote) would appear at the date they were originally posted, not when they were reshared, which you would probably miss if the reshared post is one or more days old.

**Comment by tobiasd** [comment]
The problem, is that vier was forgotten when the other themes got the update to also show the information when the posting was received. Without the information, the display is simply a mess.

**Comment by MrPetovan** [comment]
Agreed, I was just answering the `the posts should be sorted by the time they were created` part. The display should be updated as well.

**Comment by MrPetovan** [comment]
Closed by #8015
