### ISSUE TITLE
New events should use default ACL selection

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8058]
### Expected behavior

As it is the case with ACL settings for new postings, when creating an event and select the *Share Event* option, the default selection from the user configuration should be used.

### Actual behavior

When sharing an event, it is public by default.

This changed after the new ACL dialog was introduced for all themes. Before #7876 the user configuration was used.

### Steps to reproduce the problem

* Create a new event
* Fill out the form and select *Share Event*

### Friendica version you encountered the problem

2020.03-dev

**Comment by MrPetovan** [comment]
It is my understanding that the event creation form ACL selector never accounted for the current user default permissions. It only carried over an existing event ACL selection during edition, which I kept as is.  Although it definitely should take the user's default permissions on event creation.

Not so much a bug as an enhancement but it's nitpicking, I'll take care of it anyway.

**Comment by tobiasd** [comment]
Mmh... I don't think that events should be share by default. But when they are shared, then they should use the default settings. Your fix now drastically change the behavior of creating new events.

**Comment by MrPetovan** [comment]
Aaah, I see what you mean. The share checkbox could have stayed unchecked even if the default post permissions were public. I didn’t mean to force all events to be shared, I’ll create a follow-up issue.
