### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8069]
### Expected behavior
When I select 'Logout' I should be logged out and the login/home page should be displayed.

### Actual behavior
When I select 'Logout' I am still logged in and the page just reloads (with startpage add-on the configured startpage is loaded). A notification bubble is mistakenly claiming "Logged out."
I did use the 'remember me' option on login if that's important.

This is only happening since today.

### Steps to reproduce the problem
Login (maybe with remmeber me set). Try to logout. I said try to logout... ;-)

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
I'm using Redis as session storage and cache driver. No PHP errors.

**Comment by MrPetovan** [comment]
It’s the new Friendica business model aiming at user retention 😈

**Comment by AlfredSK** [comment]
Didn't you complain about 'remember me' doesn't work reliably? Now it does. 😂

**Comment by MrPetovan** [comment]
"I'll remember you whether you want it or not"

**Comment by nupplaphil** [comment]
Cookies never died ;-) .. Fixed with #8070
