### ISSUE TITLE
NodeInfo usage default is incorrectly an array

### ISSUE THREAD

**Issue by jaywink** [friendica/friendica#8081]
### Expected behavior

NodeInfo spec defines `usage` as an object - https://nodeinfo.diaspora.software/schema.html

### Actual behavior

If no usage output, it comes out as an array - https://friendica.koehn.com/nodeinfo/2.0

Culprit here? https://github.com/friendica/friendica/blob/03038e7a3bb74bdab497d26b7f829a5c3036d1c2/src/Module/NodeInfo.php#L35

### Friendica version you encountered the problem

2019.12-1327

**Comment by annando** [comment]
The other fields are looking fine? PHP seems to automatically convert associated arrays to objects. Only with empty data this automatic doesn't work.

This will be changed for both version 1 and 2.

**Comment by MrPetovan** [comment]
We just have to use the `JSON_FORCE_OBJECT` flag in `json_encode()`.

**Comment by annando** [comment]
This would be a problem with other data that possibly could contain empty array values.

**Comment by MrPetovan** [comment]
I know, but PHP doesn't have a specific representation of empty objects/hashes. The other solution is to provide zeroed statistics for uncooperative nodes.

**Comment by MrPetovan** [comment]
I guess PHP does have a specific representation for empty objects after all.

**Comment by jaywink** [comment]
Wow. Are all issues for Friendica handled this fast? Love it! <3

**Comment by MrPetovan** [comment]
No, just yours ❤
