### ISSUE TITLE
White screen on /network with activated Advanced Content Filter

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#8090]
### Expected behavior
The `/network` site shoud appear

### Actual behavior
A white screen appears

### Steps to reproduce the problem
Activate the _Advanced Content Filter_ and then go to `/network` or `/profile/user`

The PHP Error log:
```
PHP Fatal error:  Uncaught Error: Class 'Friendica\Core\Cache' not found in /addon/advancedcontentfilter/advancedcontentfilter.php:117
Stack trace:

#0 /src/Core/Hook.php(202): advancedcontentfilter_prepare_body_content_filter(Object(Friendica\App), Array)
#1 /src/Core/Hook.php(178): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'prepare_body_co...', Array, Array)
#2 /src/Model/Item.php(3536): Friendica\Core\Hook::callAll('prepare_body_co...', Array)
#3 /src/Object/Post.php(343): Friendica\Model\Item::prepareBody(Array, true)
#4 /src/Object/Post.php(478): Friendica\Object\Post->getTemplateData(Array, 2)
#5 /src/Object/Thread.php(189): Friendica\Object\Post->getTemplateData(Array)
#6 /include/conversation.php(772): Friendica\Object\Thread->getTemplateData(Array)
#7 /ht in /addon/advancedcontentfilter/advancedcontentfilter.php on line 117
```
### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2020.03-dev - 1330

### Friendica source (git, zip)
git

### PHP version
7.2.26

**Comment by MrPetovan** [comment]
Thanks for the report, are you sure you updated both Friendica base and Friendica addons to the same version?

**Comment by atasingorneq** [comment]
Yes, i just checked.

**Comment by atasingorneq** [comment]
PHP error log:
`
PHP Fatal error:  Uncaught Error: Class 'Friendica\Core\Cache' not found in /addon/advancedcontentfilter/advancedcontentfilter.php:117
Stack trace:
#0 /src/Core/Hook.php(202): advancedcontentfilter_prepare_body_content_filter(Object(Friendica\App), Array)
#1 /src/Core/Hook.php(178): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'prepare_body_co...', Array, Array)
#2 /src/Model/Item.php(3536): Friendica\Core\Hook::callAll('prepare_body_co...', Array)
#3 /src/Object/Post.php(343): Friendica\Model\Item::prepareBody(Array, true)
#4 /src/Object/Thread.php(189): Friendica\Object\Post->getTemplateData(Array)
#5 /include/conversation.php(772): Friendica\Object\Thread->getTemplateData(Array)

#6 /mod/network.php(292): conversation(Object(Friendica\App), Array, Object(Friendica\Content\Pager), 'networ in /addon/advancedcontentfilter/advancedcontentfilter.php on line 117
`

**Comment by MrPetovan** [comment]
Thanks for checking!

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica-addons/pull/942

**Comment by nupplaphil** [comment]
This would have been included in https://github.com/friendica/friendica-addons/pull/941 as well since I found it too (and some other missing Cache references I found too ..)

**Comment by MrPetovan** [comment]
Did you add the `Cache->set` call as well?

**Comment by nupplaphil** [comment]
nope, gotcha :-)
