### ISSUE TITLE
Contact request cannot be ignored

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8098]
### Expected behavior

That you can ignore a contact request from a Diaspora* account.

### Actual behavior

You cannot.

This is a regression in the behavior as it was possible to ignore such a request. This did not discard the request (which is not possible because Diaspora* does not expect this) but it at least did not bother the Friendica user with the repeated request of that account anymore. Instead the request was moved to the _ignored_ contact requests.

When I ignore such a request now, the request stays in the list of requests I have to decide about. Which also means, that the could for the notification is not reduced to 0, which makes it harder to see actual new notifications as the alert for new notifications is _always on_.

### Friendica version you encountered the problem

2020.03-dev

**Comment by MrPetovan** [comment]
Can you ignore any other contact request? It should be network dependent.

**Comment by tobiasd** [comment]
No I cannot ignore other (Friendica) contact requests.

I created a test account on my node and made the contact request. I cannot ignore it, but at least discarding it still works.

**Comment by MrPetovan** [comment]
Thanks for the elaboration.

**Comment by MrPetovan** [comment]
Fixed by #8105
