### ISSUE TITLE
Can't login after first account creation

### ISSUE THREAD

**Issue by AnkeW** [friendica/friendica#8104]
I installed Friendica following the guide, and it seemed to work fine until the "log in" step. When I enter the username and auto-generated password I received via email, the page with the login form reloads, not displaying an error message.

Anybody know what might be up or how I could find out? 
The account was created, and using the password reset link to get another auto-generated password does not work. I also tried copying the password into a text editor and copying it from there, to make sure no leading or trailing spaces were attached.

**Comment by MrPetovan** [comment]
Hi @AnkeW and thank you for reaching out. Can you elaborate on the Friendica version you installed? One reason you have this problem is that the session might not stick and would be regenerated each page call, which would redirect you to the login page without an error message. Do you know how to consult browser cookie content or would you be willing to open registrations for me to try on your instance?

**Comment by AnkeW** [comment]
This is Friendica, version 2019.12 that is running at the web location http://www.scribblers.club. The database version is 1327, the post update version is 1322.

I can see a PHPSESSID cookie, but I'm not sure what I'd need to look out for.

Registrering is open. Thanks a lot for having a look!

**Comment by AnkeW** [comment]
PHP version:  7.1 
MySQL version: 5.7.28-nmm1-log

**Comment by MrPetovan** [comment]
Found the issue: Your login form on `http://www.scribblers.club/login` is posting to `https://www.scribblers.club/login` which redirects to `http://www.scribblers.club/login` without having submitted the form data.

Suggested remediation: Please fix your SSL setup and remove the redirection from `https://` to `http://`

In the meantime you can temporarily disable SSL on your Friendica node from the command line: `bin/console config system ssl_policy 0`

**Comment by AnkeW** [comment]
Thank you!

**Comment by tobiasd** [comment]
> In the meantime you can temporarily disable SSL on your Friendica node from the command line: bin/console config system ssl_policy 0

I wonder if the installer should automatically disable SSL when it was used over HTTP only and have a big scary red box about problems with HTTPS or something alike.

**Comment by MrPetovan** [comment]
I’ve never seen this SSL setup where HTTPS redirects to HTTP. I’m not even sure how we can account for it without being too specific about it. The certificate seemed deficient as well according to my browser, but we do expect some people to use self-signed certificates that browsers and curl would reject with strict SSL checks, so we can’t use a failed SSL state conclusively.

**Comment by tobiasd** [comment]
I was thinking a installation without TLS at all, for whatever reason. If there is no HTTPS available, which might very well the case if the installer runs without it, the setting should be adopted accordingly.

Or the installing user should be informed about the problem, and the 2 possible ways to resolve it (a) configure TLS or (b) set this option.

**Comment by MrPetovan** [comment]
I guess the installer would have indeed be accessed with TLS.
