### ISSUE TITLE
Posts not showing up on group wall

### ISSUE THREAD

**Issue by spirewalk** [friendica/friendica#8109]
Posts I make to a group do not appear on its wall.  It's visible on my home page along with all other posts I make, and it's clearly "padlocked" to the group I tried to post in, it's just not on the wall.

**Comment by annando** [comment]
Which version are you using? Is the forum account on the same server?

**Comment by spirewalk** [comment]
Dalmatian Bellflower' 2020.03-dev - 1330, and this is all on one server.  I
noticed that my beta tester can post to the group wall, and I can reply to
his thread, but any post I make to a group does not show up in the group
wall.

**Comment by annando** [comment]
Meh ... I thought to have fixed it lately.

**Comment by AlfredSK** [comment]
Are we sure we are all talking about the same thing?

> "padlocked" to the group

This doesn't look like the issue is about forum posts. Is it possible that the question is about contact groups? I'm asking because there is a common confusion between `group = forum` and `group = contact/privacy group`.

**Comment by MrPetovan** [comment]
Very nice catch, in this case the "group wall" is comprised of posts from members of this group, you excluded.

**Comment by spirewalk** [comment]
So it’s not a bug separating my contact group list, it’s a feature?  I’m
sorry for the misunderstanding.  Blame that on a Facebook or OSSN mentality
where I expected contact groups to behave as the former two examples, where
you have a group and all files and posts go into that group.  Mine, theirs,
everyone.

So should I be building a forum then, and it behaves more like a FB or OSSN
group?

**Comment by MrPetovan** [comment]
Yes, if you want to see your posts in the "group", creating a forum seems more appropriate. Contact groups are more like aspects or circles.

**Comment by schmaker** [comment]
I think this issue is safe to close - especially after changing name of groups/circles and forums/groups name change it can cause confusion in case someone would like to continue discussion here
