### ISSUE TITLE
blockbot addon - allow good bot by default

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#8125]
I'm testing this addon on my friendica instance. Unfortunately it blocks uptimeRobot by default.

I see there was a settings to allow good bots but it is not setup by default [here](https://github.com/friendica/friendica-addons/blob/9cb6ca5a62232f1b9d0f10c8b6e7c55900d9d1b0/blockbot/blockbot.php#L43)

I think it could be a good to enable it by default ?

**Comment by MrPetovan** [comment]
Paging @annando , he made the addon, not sure what the philosophy was exactly.

**Comment by annando** [comment]
Even "good" crawlers still are crawlers. So people could decide to block them as well. I wanted to make the most blocking the default.

**Comment by valvin1** [comment]
ok @annando 
So let's close this issue ;)

In this [PR](https://github.com/friendica/friendica-addons/pull/945) I think I fix a bad behaviour with good agents if you can have a look.
