### ISSUE TITLE
Automatic friend is broken

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8151]
### Expected behavior
When an account is set to "Automatic friend" mode, all incoming requests are automatically added as friends in default group.

### Actual behavior
Incoming connection requests get approved as followers identical to "Soapbox" mode.

### Steps to reproduce the problem
Set user to "Automatic friend" mode. Send connection request to them and you will become a follower, not a friend.

### Friendica version you encountered the problem
2019.12, 2020.03

### Friendica source (git, zip)
git master

### PHP version
PHP 7.4.1

### SQL version
MariaDB 10.3

**Comment by tobiasd** [comment]
Yes I think so as well. Saw a pending request this morning on an organization account that should accept automatically.

**Comment by annando** [comment]
@tobiasd this would be a different issue. This issue here is about an automatic friend request which had to send a contact request in answer to an incoming contact request.

**Comment by tobiasd** [comment]
Ok, then both are broken ;)

**Comment by annando** [comment]
Please open another issue for that.
