### ISSUE TITLE
Rewrite gender selector in profile

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#8153]
Currently, the "Gender" field in profiles is a drop-down selector, with entries like "Male," "Female," "Intersex," "Hermaphrodite," and "Transgender" (among others). While I applaud the attempt to include a variety of gender options beyond the radio button "Male / Female" selector, I think this is less than helpful for a number of reasons.

First, it conflates a variety of different traits, like sex (intersex), gender (male, female), and... gender identity? That's not quite it, but the "are you trans or cis?" question. Someone can be male and transgender, but the way this form presents the options, it's as if "transgender" is its own distinct gender, which I know many trans people find othering.

Second, it offers a word (hermaphrodite), that, in addition to having nothing to do with gender (it's about sex characteristics), is also [largely considered by the intersex community to be stigmatizing and hurtful](https://isna.org/node/16/). Of course, there may be people out there who prefer to identify with that term--the world is wide--but I expect that they are far fewer than those who find it a hurtful slur.

This selector also leaves out a number of other gender identities, such as agender, genderqueer, demiguy/demigirl, and two-spirit, to name a few.

I recognize this is a big and complex thing to tackle in a single form, but could I request some sort of review of this part of the profile? [This article by UX Collective](https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51) is a great resource on designing gender-inclusive forms, especially because it links to related articles in the footer. [Practice Makes Progress](http://www.practicemakesprogress.org/blog/2015/9/18/asking-about-gender-on-online-forms) also has an article on the subject. [This is a discussion on MetaFilter](https://ask.metafilter.com/306031/How-to-handle-gender-field-drop-down-options-in-software) about the subject. [Yonatan Zunger](https://medium.com/@yonatanzunger/this-is-a-great-piece-f65943f99165) shared some thoughts on internationalization and gender.

In the short term, I wonder if replacing the drop-down selector with a free-form text entry field for gender and a selector for pronouns might be more simple and inclusive? I don't know what that looks like on the back-end and I expect it might create some translation issues, though Zunger's piece above also somewhat addresses the potential linguistic challenges. As it stands, the current gender selector makes me a little wary of inviting my friends, many of whom are trans or gender-diverse, to make profiles on my Friendica instance. 😕

### Friendica version you encountered the problem

2019.12

**Comment by MrPetovan** [comment]
> I wonder if replacing the drop-down selector with a free-form text entry field for gender and a selector for pronouns might be more simple and inclusive?

This will be done in #7817

**Comment by SpencerDub** [comment]
Awesome!

**Comment by MrPetovan** [comment]
I don't think we'll have an explicit gender field again, I consider this will be closed by #7817

**Comment by SpencerDub** [comment]
Sure thing! That addresses it too. I didn't know if anything in Friendica relied on that gender data, and I wanted to err on the side of thorough when writing the issue.

Thanks for the quick response. :)

**Comment by MrPetovan** [comment]
You're welcome, thanks for the detailed report!

**Comment by AndyHee** [comment]
Thanks @SpencerDub for your thoughtful input! 

Welcome to Friendica!
