### ISSUE TITLE
Contact requests by an Organization account not automatically accepted

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8157]
### Expected behavior

Contact requests for an "Organization" account should be accepted automatically as advertised in the help text of the account type.

### Actual behavior

At least for one request from a Diaspora* account this did not work. Similar to #8151 

### Friendica version you encountered the problem

2020.03-dev (libranet.de)

**Comment by AlfredSK** [comment]
I'm not sure if I remember correctly but I saw the same behavior with a News account.

**Comment by annando** [comment]
I cannot reproduce this. I tested with both ActivityPub and Diaspora.

**Comment by AlfredSK** [comment]
I also didn't experience it again lately - or no new users followed my 'news' and 'forum' accounts. :D

**Comment by tobiasd** [comment]
Seems to have worked for at least one new follower of the org account I encountered this. So lets close the issue for the moment until it happens again.
