### ISSUE TITLE
[frio] Remove profile tabs

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#8164]
The newly revamped profile is great! Excellent thinking, nicely put in place. One minor point for improvement. 

### Actual behavior

The naming of the profile tabs ('Basic' and 'Advanced') is not very logical and reminiscent of a configuration panel.

![Screenshot_2020-01-25_11-30-41](https://user-images.githubusercontent.com/28751375/73116325-fce06580-3f66-11ea-82cd-2bafeffd87e7.png)

_Advanced_ profile information? 

### Expected behavior

A more natural language usage, something along the line.

|  Key Information |  Additional Information |

TBH do will really need tabs? Couldn't this be all displayed on one page?

### Friendica version you encountered the problem
2020.03-dev

**Comment by MrPetovan** [comment]
I fully agree with you. I didn't want to change too much without a conversation, I'm glad people are taking the matter into their own hands.

**Comment by AlfredSK** [comment]
Yes. I think the tabs are not necessary anymore.

There's also another visual issue when the display is a little more narrow. The "View profile as:" is displayed over (read: in front of) the headline "Profile".
