### ISSUE TITLE
Pinned Post feature broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8172]
### Expected behavior
Pinned posts should be pinned. The option in the action menu should toggle the pin/unpin status.

### Actual behavior
My pinned posts are not pinned anymore. It is not possible to pin them again or to pin other posts. This is probably caused by PR #8156 because it worked before I pulled it.

### Steps to reproduce the problem
Check your pinned posts on your wall/status page. Try to toggle the pinned status.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Fixed by #8175
