### ISSUE TITLE
Distribution/federation of comments partly broken/acting weirdly

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8180]
### Expected behavior
I made a public test post. Everyone participated should get all the comments. (I know that there are protocol limitations)

### Actual behavior
A lot of people commented. But everyone participated did only get my comments (comments of the thread owner) but no other comments. No matter from what network the other commenters are they only see their own and my comments.

https://libranet.de/display/0b6b25a8-295e-2eed-f2d3-ee7689821828

Another weird thing. Some of the comments from Diaspora users in that thread were picked up from a second account of mine and redistributed as remote self post (normally that account only redistributes my own posts). That should never happen.

https://libranet.de/display/0891a3d0233e0138e011268acd52edbf
https://libranet.de/display/85a863ed-145e-2ef2-9ac3-fc5880630494

Looks like a lot of comments were falsely redistributed as own posts. To be more precise: every comment from Diaspora I liked.
https://venera.social/profile/steffen

The reason I made this test in the first place: I cannot comment on another thread I started. I could do it yesterday. But since today my comments on that thread don't federate anymore. The 'notifier task pending' icon never goes away.

https://libranet.de/display/0b6b25a8-135e-2e0f-6e6b-7d8537708897

I checked my worker queue. It is somewhat above normal. But not very long. But I see an unusual high share of "Delivery: wall-new" entries with priority 20.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
Hmm. When I try to comment on my own thread I get this now in the browser console...

`/item:1 Failed to load resource: the server responded with a status of 500 ()`

Nothing in PHP error log.

**Comment by MrPetovan** [comment]
Can you please check what is the full URL resulting in 500 in the Network tab?

I've identified cases where we throw an Exception, we catch it and display it as 500 error but nothing gets written in the log.

**Comment by AlfredSK** [comment]
Do you mean the network tab in the browser console? If so it is `https://libranet.de/item`. Btw. I'm on my my status page while trying to comment `https://libranet.de/profile/alfred`. But it also happens when I try to comment from the posts display page.

**Comment by AlfredSK** [comment]
When I press on Submit to send the comment nothing happens. Just a rotating wheel and some javascript errors "Violation - forced reflow while executing javascript took XX ms".

**Comment by AlfredSK** [comment]
This is a more complete version of the output from the console:

```
jquery.min.js:4 POST https://libranet.de/item 500
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
post_comment @ main.js:748
onsubmit @ 0b6b25a8-195e-2f1a-0264-034544556585:6510
jquery.min.js:4 XHR failed loading: POST "https://libranet.de/item".
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
post_comment @ main.js:748
onsubmit @ 0b6b25a8-195e-2f1a-0264-034544556585:6510
```

**Comment by AlfredSK** [comment]
And in apache access log:

```
"POST /item HTTP/2.0" 500 2271 "https://libranet.de/profile/alfred" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/79.0.3945.117 Chrome/79.0.3945.117 Safari/537.36"
"POST /item HTTP/2.0" 500 2271 "https://libranet.de/display/0b6b25a8-195e-2f1a-0264-034544556585" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/79.0.3945.117 Chrome/79.0.3945.117 Safari/537.36"
```

**Comment by AlfredSK** [comment]
The only thing I found is what I posted in that comment https://github.com/friendica/friendica/issues/8180#issuecomment-578864127

In the meantime I rebooted the server. After that I could comment again w/o getting an error 500. But the other things are still concerning me. I mean the delivery issue and the fact that some comments were distributed as posts (partly comments from others as posts of me).

**Comment by MrPetovan** [comment]
I get it, it was confusing for me on the other end as well.

**Comment by AlfredSK** [comment]
The error 500 and not being able to comment on own posts didn't happen again. But I'm not sure about the weird comment distribution. I think I need to check that again.

**Comment by realkinetix** [comment]
I suspect we're seeing the similar issue on my 2019.12 system, as I'd just started noticing that I could see one of my instance contact's comments to unrelated posts on other instances, but they're not showing in my network feed locally.

That user also noticed strangeness and commented that when they share or comment, the distribution to other systems is very low, but when they create a new post the distribution is wide.

Their comment is here: https://social.isurf.ca/display/c443a55c-715e-63d4-6456-213297383428

@AlfredSK Did you notice if the item distribution got better after the DB error fix?

**Comment by AlfredSK** [comment]
All I can say is it doesn't seem to have happened again.

**Comment by realkinetix** [comment]
Awesome... I'm looking forward to the RC!

**Comment by AlfredSK** [comment]
I think we can close this for now and reopen in case it happens again. Any objections?
