### ISSUE TITLE
Missing notifications from forum

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8182]
I didn't get any notification from any reply of this forum thread I interacted with.

https://friendica.mrpetovan.com/display/7c104781-195e-2f26-ed87-4ca864495840

**Comment by hoergen** [comment]
I noticed that I don't get notifications at all at the moment. Pulled today morning.

**Comment by nupplaphil** [comment]
Yep, shoul be fixed today in the evening I think
