### ISSUE TITLE
Forum threads are creating DB Errors

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#8184]
### Expected behavior

Adding threads to forums should get sent to other members of this forum.

### Actual behavior

I added two of my accounts to a test forum and added two threads vice-versa . None of both got the thread of the other.

But I found a DB error at my develop instance:
```console
2020-01-27T21:41:43Z worker [ERROR]: DB Error {"code":1048,"error":"Column 'gender' cannot be null","callstack":"Database::update, DBA::update, Contact::updateSelfFromUserID, User::getOwnerDataById, HTTPSignature::transmit, APDelivery::execute, Worker::execFunction, Worker::execute
","params":"UPDATE `contact` SET `name` = 'Forum', `nick` = 'forum', `avatar-date` = '2020-01-27 21:35:59', `location` = '', `about` = '', `keywords` = '', `gender` = '', `contact-type` = 3, `xmpp` = '', `photo` = 'https:\/\/friendica.philipp.info\/photo\/19186234305e2f57bf3f58e109
183545-4.jpg?ts=1580160959', `thumb` = 'https:\/\/friendica.philipp.info\/photo\/19186234305e2f57bf3f58e109183545-5.jpg?ts=1580160959', `micro` = 'https:\/\/friendica.philipp.info\/photo\/19186234305e2f57bf3f58e109183545-6.jpg?ts=1580160959', `avatar` = 'https:\/\/friendica.philipp
.info\/photo\/profile\/7.jpg', `forum` = '1', `prv` = '', `unsearchable` = '1', `url` = 'https:\/\/friendica.philipp.info\/profile\/forum', `nurl` = 'http:\/\/friendica.philipp.info\/profile\/forum', `addr` = 'forum@friendica.philipp.info', `request` = 'https:\/\/friendica.philipp.
info\/dfrn_request\/forum', `notify` = 'https:\/\/friendica.philipp.info\/dfrn_notify\/forum', `poll` = 'https:\/\/friendica.philipp.info\/dfrn_poll\/forum', `confirm` = 'https:\/\/friendica.philipp.info\/dfrn_confirm\/forum', `poco` = 'https:\/\/friendica.philipp.info\/poco\/forum
', `updated` = '2020-01-27 21:41:43' WHERE (`id` = 116191)"} - {"file":"Database.php","line":714,"function":"e","uid":"80acf6","process_id":241880} 
```

### Steps to reproduce the problem

- I executed `php bin/console.php dbstructure update` without errors/results (so should worked)

- Create a new forum to a `develop` instance
- Add a user of a `develop` instance to this forum
- Add a user of a `master` instance to this forum
- Post a thread in the forum with both accounts

### Friendica version you encountered the problem

2020.03-dev

### Friendica source (git, zip)

git

### PHP version

```console
PHP 7.3.13 (cli) (built: Dec 26 2019 22:25:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
```
### SQL version

```console
mysql  Ver 15.1 Distrib 10.4.11-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by MrPetovan** [comment]
But `gender` isn't null in the query? 😵

**Comment by nupplaphil** [comment]
That's the point why I'm currently stuck too ...

**Comment by MrPetovan** [comment]
In any case, gender shouldn't be referenced anywhere except the migration script. This is a good starting point to fix this.

**Comment by MrPetovan** [comment]
Wait, it's in the `contact` table. I din't touch it.

**Comment by nupplaphil** [comment]
Does #8190 fix this issue as well? At least it seems related (gender in contact table)

**Comment by MrPetovan** [comment]
I don't think so since I explicitly left alone the `contact.gender` field.

**Comment by nupplaphil** [comment]
ah ok

**Comment by nupplaphil** [comment]
What do we do with this error? It nevers happend again on my node with the current dev branch... Shall I close it ?

**Comment by AlfredSK** [comment]
Currently I see zero DB errors in the logs of my personal node(s) and the forum node, too. But I can try to reproduce it...

**Comment by AlfredSK** [comment]
Did I say 'I see zero DB errors'? I was wrong. I see hundreds of DB errors. But they seem unrelated to this issue...

**Comment by AlfredSK** [comment]
Test 1:
https://libranet.de/display/85a863ed-355e-3e97-37da-40d980427127
Test 2:
https://libranet.de/display/027b03f7-175e-3e97-929b-391023260281

No DB errors with code 1048.

**Comment by nupplaphil** [comment]
Closing this issue since doesn't occur anymore
