### ISSUE TITLE
Profile link in main menu doesn't link to the profile

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8185]
### Expected behavior
When I click on 'Profile' in the main menu my user profile should be displayed.

### Actual behavior
When I select 'Profile' in the main menu the 'Status' page is displayed.
The URL is `https://friendica.server/profile/nickname?tab=profile` but the tab is 'Status'.

### Steps to reproduce the problem
Click on user avatar in the upper right area. Select 'Profile' from the menu.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Indeed, I overlooked this parameter that isn't used anymore.

**Comment by MrPetovan** [comment]
Fixed by #8188
