### ISSUE TITLE
Scheduled Posts

### ISSUE THREAD

**Issue by annando** [friendica/friendica#819]
Adding a possibility to add posts to a queue so that they are delivered at a later time.

**Comment by schiessle** [comment]
Any chance that this gets implemented? Having the option to schedule posts is something which is really handy, especially of organizations who want to optimize their marketing/pr efforts. I hear it regularly that this is a killer feature which is for example available for tweetdeck and which keeps people from switching.

**Comment by annando** [comment]
Yeah, we really should put this on the list. Thanks for pointing at it.

Currently one could implement it indirectly with buffer.

**Comment by MrPetovan** [comment]
Closed as duplicate for #8038 that has more description and conversation.

**Comment by victort** [comment]
circular reference. this refers to #8038, and gets closed, but #8038 refers to #819, then get closed. =(

**Comment by MrPetovan** [comment]
There's no automatic closure for duplication, which means there always is an open issue about scheduled posts.
