### ISSUE TITLE
sem_get(): failed for key 0x6602b303: No space left on device in /path/to/friendica/src/Core/Lock/SemaphoreLock.php on line 41

### ISSUE THREAD

**Issue by softmetz** [friendica/friendica#8200]
After updating to 2019.12 Friendica stopped working. As it turned out the problem was too may semaphores. Friendica failed with

> NOTICE: PHP message: PHP Warning: sem_get(): failed for key 0x6602b303: No space left on device in /path/to/friendica/src/Core/Lock/SemaphoreLock.php on line 41]

I found the command line
```
for whatever in `ipcs -s | awk '{print $2}'`; do ipcrm -s $whatever; done
```

which fixed the issue for me. My hoster is Uberspace

**Comment by MrPetovan** [comment]
That's impressive that the underlying system would run out of inodes I presume?

**Comment by annando** [comment]
We changed a lot with the locking system. Did this happen again?

**Comment by MrPetovan** [comment]
This was related to a lack of disk space/inode on the underlying system, nothing we can do on our end to prevent this.
