### ISSUE TITLE
Notifications aren't cleared for a whole thread

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8205]
### Expected behavior

Clicking on a post/reply notification clears the notifications for the whole thread.

### Actual behavior

Clicking on a post/reply notification clears the notification for the specific item in the thread (the most recent one) and then the next most recent notification in the same thread appears in the notification dropdown as if there was a new reply in the thread.

I believe this is a regression that was introduced by @nupplaphil 's work on notifications.

**Comment by nupplaphil** [comment]
Fixed with #8208
