### ISSUE TITLE
Secure Mail addon broken

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8206]
### Expected behavior

Notification emails being encrypted with my OpenPGP key.

### Actual behavior

Since friendica/friendica-addons#952 notification emails are send in clear text.

### Friendica version you encountered the problem

2020.03-dev

**Comment by nupplaphil** [comment]
Any failure, errors, notices,... In the logs?

**Comment by tobiasd** [comment]
None that I saw in the usual suspects with a _notice_ loglevel.

**Comment by nupplaphil** [comment]
Ok, I'll have a look today evening

**Comment by tobiasd** [comment]
Maybe the time frame for the break is a bit bigger. As I received the last encrypted notification on Jan 26th. This morning was only the first unencrypted mail after some break I just realized.

Thanks for having a look!

**Comment by nupplaphil** [comment]
Fixed with https://github.com/friendica/friendica-addons/pull/953 :)
