### ISSUE TITLE
Hashtag Pagination does not work 

### ISSUE THREAD

**Issue by gsantner** [friendica/friendica#8216]
### Expected behavior
When clicking to "page 2" /"next page"/"older", I get post results from next page.

### Actual behavior
Page with empty results

### Steps to reproduce the problem
Click on the next page button.

I've also tried 2 other theme options, so seems not to be a theme issue. And also two different servers, so guess no server issue.

### Friendica version you encountered the problem
* Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://friendica.feneas.org. Die Datenbankversion ist 1313 und die Post-Update-Version 1322.
* Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://nerdica.net. Die Datenbankversion ist 1327 und die Post-Update-Version 1322.

Notice: Next page navigates to `https://friendica.feneas.org/search?#fosdem&page=2`, making the parameter be in the hashtag and not picked up by GET request. However changing to `https://friendica.feneas.org/search?page=2#fosdem` does not fix the issue either.

![screenrecord](https://user-images.githubusercontent.com/6735650/73599662-b5953e80-453d-11ea-8da2-f9be19629059.gif)

**Comment by gsantner** [comment]
@annando

**Comment by AlfredSK** [comment]
URL should probably be `https://friendica.server/search?q=%23hashtag&page=2`
