### ISSUE TITLE
Add endless pagination on non-network stream pages

### ISSUE THREAD

**Issue by gsantner** [friendica/friendica#8217]
### Expected behavior
Because >>Hashtag Pagination does not work #8216 <<, I've tried alternatively the endless scrolling settings option. However it seems to not do anything at all, still pagination buttons are there and nothing gets loaded additionally when I'm on the bottom.

### Actual behavior
No additional content is loaded when I reach bottom.

### Steps to reproduce the problem
Enable endless scroll in theme settings.

I've also tried 2 other theme options, so seems not to be a theme issue. And also two different servers, so guess no server issue.

### Friendica version you encountered the problem
* Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://friendica.feneas.org. Die Datenbankversion ist 1313 und die Post-Update-Version 1322.
* Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://nerdica.net. Die Datenbankversion ist 1327 und die Post-Update-Version 1322.

**Comment by gsantner** [comment]
@annando

**Comment by AlfredSK** [comment]
Infinite scroll is available on the network page only.

**Comment by gsantner** [comment]
OK I  expected it to work on all kind of "paginated" pages :D .

**Comment by AlfredSK** [comment]
Who doesn't? ;-) 
I'm pretty sure there is already a feature request to support infinite scroll on the community pages. #5562
