### ISSUE TITLE
Frio theme: CSV contact import wrong button

### ISSUE THREAD

**Issue by gsantner** [friendica/friendica#8219]
### Expected behavior
When uploading csv, my contact get imported.

### Actual behavior
When using the Frio theme, uploading a contact csv (from mastodon follower) and clicking the submit button down below does not work as expected.

After upload&submit the "settings updated" message toast comes up. But  "Importing Contacts done" should be shown. 

Import works however at Vier theme.

File: mod/settings.php.

### Steps to reproduce the problem
* Set frio theme in settings
* Goto settings to import contact section

### Friendica version you encountered the problem
Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://friendica.feneas.org. Die Datenbankversion ist 1313 und die Post-Update-Version 1322.

**Comment by valvin1** [comment]
i've just reproduced the same issue on 2019.12 and 2020.03-dev.

**Comment by MrPetovan** [comment]
Thanks for the elaboration!
