### ISSUE TITLE
"Image upload failed"

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#8228]
When I try to upload a photo, either via my Photos or the Browser tab of the post composer (in the Frio theme), I can select a photo, but it does not upload. I get an error message: "Image upload failed."

### Expected behavior
The image uploads properly.

### Actual behavior
I get an error message: "Image upload failed." The image does not upload.

In my `/var/log/php7.0-fpm.log` file, I see a corresponding entry:

> [02-Feb-2020 14:57:32] WARNING: [pool friendica] child 3449 said into stderr: "NOTICE: PHP message: PHP Warning:  Error while sending STMT_CLOSE packet. PID=3449 in /var/www/friendica/src/Database/Database.php on line 652"

### Steps to reproduce the problem
1. Download the full-size version of [this image](https://unsplash.com/photos/W7cPLHOa0eQ) (which I've been using for testing)
2. Navigate to either the Browser in the post composer or the Upload Photos page. Click "upload" and attempt to upload the above image.

### Friendica version you encountered the problem
2019.12

### Friendica source (git, zip)
Zip, I believe. Installed via [this install script for YunoHost](https://github.com/SpencerDub/friendica_ynh).

### PHP version
php7.0fpm

### SQL version
10.1.41-MariaDB-0+deb9u1 - Debian 9.9

### Server settings (as reported by Friendica admin page)

PHP:
* **upload_max_filesize:** 50M
* **post_max_size:** 200M
* **memory_limit:** 128M

MySQL / MariaDB:
* **max_allowed_packet:** 1048576

I'm sure this is just some sort of configuration problem on my end, but I'm having a hard time figuring out where the issue is, and I would appreciate any help.

**Comment by AlfredSK** [comment]
Your max allowed packet size (database) is 1MB. That's the reason why you get the DB error when you try to send the image to the database.

**Comment by SpencerDub** [comment]
Updating `max_allowed_packet` in `/etc/mysql/my.cnf` to 50M did the trick. Thank you, @AlfredSK!
