### ISSUE TITLE
Frio theme: Comment button overlap (mobile)

### ISSUE THREAD

**Issue by gsantner** [friendica/friendica#8229]
### Expected behavior
That blue comment button can be pressed.

### Actual behavior
To top button above comment button and you cannot scroll down further.

![https://i.postimg.cc/ZKVkfw24/Screenshot-20200203-122417-Galerie.png](https://i.postimg.cc/ZKVkfw24/Screenshot-20200203-122417-Galerie.png)

### Friendica version you encountered the problem

Diese Friendica-Instanz verwendet die Version 2019.12, sie ist unter der folgenden Adresse im Web zu finden https://friendica.feneas.org. Die Datenbankversion ist 1313 und die Post-Update-Version 1322.

**Comment by MrPetovan** [comment]
Yep, I have had this issue myself before.

**Comment by nupplaphil** [comment]
I think a good practice would be that the top button appears when you start scrolling up. As a "shortcut"

**Comment by MrPetovan** [comment]
Duplicate of #7560
