### ISSUE TITLE
Following via /dfrn_request gives error on Mastodon

### ISSUE THREAD

**Issue by wakest** [friendica/friendica#8233]
### Expected behavior
Tried to follow https://friendica.mrpetovan.com/dfrn_request/hypolite

![image](https://user-images.githubusercontent.com/7890201/73787976-147ed180-4751-11ea-80af-f95da769b33f.png)

[thread about it on the fediverse here ](https://social.wake.st/@liaizon/103602586820083604)

### Friendica version you encountered the problem
2020.03-dev at https://friendica.mrpetovan.com

**Comment by wakest** [comment]
just realized if I changed the url manually it works, so friendica is somehow sending mastodon only "profile/hypolite" instead of the whole url https://social.wake.st/authorize_interaction?uri=https://friendica.mrpetovan.com/profile/hypolite

**Comment by MrPetovan** [comment]
Ah, so my hunch was right, thanks for testing with the full profile address.

**Comment by wakest** [comment]
just checked with your instance: I can follow you only if I use the form @liaizon@social.wake.st but it fails for https://social.wake.st/@liaizon (with and without https://) and https://social.wake.st/users/liaizon and also @liaizon@wake.st (my short name, which is actually the only one mastodon shows/recommends in the interface of my profile.

**Comment by wakest** [comment]
using https://social.wake.st/@liaizon gives me 
"Remote subscription can't be done for your network. Please subscribe directly on your system."

**Comment by wakest** [comment]
liaizon@wake.st, @liaizon@wake.st and @liaizon@social.wake.st give me
"The provided profile link doesn't seem to be valid"

**Comment by annando** [comment]
@wakest I guess this is a special case for your setup with the multiple hostnames.

**Comment by annando** [comment]
With the exception of liaizon@wake.st it worked here on my machine.

**Comment by MrPetovan** [comment]
What worked exactly?

**Comment by annando** [comment]
I entered the addresses from above at https://pirati.ca/remote_follow/heluecht and got no error messages.

**Comment by MrPetovan** [comment]
Thanks, can we confirm it's the same page @wakest used when they tried to follow me?

**Comment by annando** [comment]
It *should*

**Comment by wakest** [comment]
Just tried this again on pirati.ca and this is what I got:

_Works on https://pirati.ca/remote_follow/heluecht_
https://social.wake.st/@liaizon
https://social.wake.st/users/liaizon
liaizon@social.wake.st

_"The provided profile link doesn't seem to be valid"_
liaizon@wake.st
@liaizon@wake.st
@liaizon@social.wake.st

**Comment by annando** [comment]
That's the expected behaviour. The format with the leading `@` is invalid.

**Comment by wakest** [comment]
invalid is only one way to describe it. its also the expected behavior of 99% of the people who might be copying a handle and pasting it into that field. I don't personally care if its valid or not valid, if you want people to try again with out the leading @ what about having that be an error message, or just dropping the leading @ on paste?
![image](https://user-images.githubusercontent.com/7890201/75082434-d5ec6380-5513-11ea-9699-ab9b04a7a98c.png)

**Comment by annando** [comment]
@wakest PR is done: https://github.com/friendica/friendica/pull/8328
