### ISSUE TITLE
Cleanup task of removed yesno/onoff feature

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8238]
Follow-up to #8236 

I found the remaining occurrences:

`yesno`:
- `doc/AddonStorageBackend.md`
- `view/templates/settings/settings.tpl`
- `view/theme/frio/templates/settings/settings.tpl`
- `src/Model/Storage/IStorage.php`
- `src/Module/Admin/Site.php`

`onoff`:
- `view/templates/settings/settings.tpl`
- `view/theme/frio/templates/settings/settings.tpl`
- `view/theme/frio/js/theme.js`

**Comment by nupplaphil** [comment]
Can you  fix these errors as well (shown at various places in the "settings" page)?
```console
Warning: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/html/view/smarty3/compiled/904f52272ff5cbb20c257606e5dac6ed0eadad02_2.file.field_checkbox.tpl.php on line 33
```

**Comment by MrPetovan** [comment]
It probably is the array of "Yes"/"No" translated labels used as a string.
