### ISSUE TITLE
impossible to remove custom profile fields

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8246]
With #7817 and the _new custom profile fields_ existing entries from the old multiple profiles feature got converted to the new format. Among others the `since` field got converted. For each end every of my additional profiles.

### Expected behavior

To be able to remove the duplicates. Or to remove the unwanted entries from the profile at all.

### Actual behavior

You cannot remove them. All you can to is hide them from all visitors.

### Steps to reproduce the problem

* add some custom profile fields
* try to remove them

### Friendica version you encountered the problem

2020.03-dev

**Comment by MrPetovan** [comment]
What did you do to try to remove them? The text at the top of the list of profile fields says to blank the label input to remove the custom field, have you tried it?

**Comment by tobiasd** [comment]
On Thu, 06 Feb 2020 07:11:55 -0800
Hypolite Petovan <notifications@github.com> wrote:

> What did you do to try to remove them? The text at the top of the
> list of profile fields says to blank the label input to remove the
> custom field, have you tried it?

No, because I expected some trash icon / button and TBH never read the text. I'll try if this works.

But from the UX have a very long list of duplicated entries (all the stuff that did not change over the different profiles) and just got frustrated because there is no delete button.

**Comment by tobiasd** [comment]
On Thu, 06 Feb 2020 07:11:55 -0800
Hypolite Petovan <notifications@github.com> wrote:

> The text at the top of the list of profile fields says to blank the
> label input to remove the custom field,

Do we use this technique anywhere else on Friendica? For me it sounds totally counter-intuitive to leave the label empty to delete something.

**Comment by MrPetovan** [comment]
No, we use a checkbox for this in the domain block list but I was trying to limit the height of each custom field block.

The problem of the delete button is that I didn't plan on adding ajax removal so a delete button in a form would reload the page and neither frio nor the other themes have a way to show the custom profile field list again when reloading the user settings page.

**Comment by tobiasd** [comment]
Closing, as it counter-intuitively works as designed.

**Comment by MrPetovan** [comment]
Now that the form is working as is without Javascript, we (I) can add asynchronous improvements like field deletion.
