### ISSUE TITLE
[frio] Regression: Notification menu display is broken on mobile

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8248]
Caused by #8240 

Normal state, note how big the notification button is compared to the other menu item, using links:
![Screen Shot 2020-02-06 at 16 44 45](https://user-images.githubusercontent.com/925415/73981419-2baff180-4900-11ea-8a55-4835bfad0528.png)
Open state, note the absence of background color of the notification menu, the whole top bar menu moved off the bar itself:
![Screen Shot 2020-02-06 at 16 45 06](https://user-images.githubusercontent.com/925415/73981422-2c488800-4900-11ea-9755-835b31f4ffc5.png)

How to reproduce: Have a horizontal screen resolution lower than 768 pixels.

**Comment by annando** [comment]
Meh ... I hate this CSS stuff.

**Comment by MrPetovan** [comment]
Please notice I didn't assign you this issue.

**Comment by annando** [comment]
I appreciate this. When you make more drastic changes (like changing it back from "button" to "a"), please ensure with an extension like "Chromevox" if the system still tells whether the popup is opened or closed. This is controlled via the attribute "aria-expanded" that has to change value when the popup is opened or closed.

**Comment by MrPetovan** [comment]
I don't intend to change the markup, I will use what you decided for accessibility.

**Comment by AlfredSK** [comment]
It is not only a visual issue. I noticed that you cannot open the menu _again_ after you have selected a notification and you were redirected to the /display page of the notified item. You need to go back to a regular page like /profile/... or /network to make the notification menu work again.

Tested on phone and tablet with Android.

**Comment by annando** [comment]
I only tested on my regular computer, there everything looked fine, grmbl ...
