### ISSUE TITLE
Use profile.about instead of profile.pdesc for profile description

### ISSUE THREAD

**Issue by annando** [friendica/friendica#8251]
I just realized that the profile field "about" is one of the fields that had been moved to the custom profile fields. I think this should be exchanged with the field "pdesc". "pdesc" is only a varchar(255) while "about" is a text field.

Formerly we transmitted the content in the "about" field for example in the "summary" field of the AP profile data. We now use the content of "pdesc" for that, that is much too short for that purpose and doesn't allow line feeds.

On other systems (Mastodon, Pleroma, Diaspora, GNU Social) the "summary" field is always a longer text field. It is used for a longer self description. We should also use a longer field for that and instead move the content of the "pdesc" field to the custom profile fields.

**Comment by MrPetovan** [comment]
It is possible for all users that haven't been on the develop branch.

**Comment by annando** [comment]
Since the value was copied to the custom profile fields, users of the develop branch could copy it by hand. That's not the best method, but a working one.

**Comment by MrPetovan** [comment]
Indeed.

**Comment by MrPetovan** [comment]
Please see https://github.com/friendica/friendica/pull/8261#issue-372801390

**Comment by MrPetovan** [comment]
I'm not satisfied with the result of this, my description reads

```
he/him – fr-fr/en-us – UTC -5h — #Friendica core developer. Avatar by @DearMsDear@mastodon.art
```

But neither the hashtag nor the @-mention is active, how can we make that happen?
