### ISSUE TITLE
[frio] popup menu on network indication icon not available any more

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8255]
### Expected behavior
Available popup menu

### Actual behavior
no popup menu
![00_temp](https://user-images.githubusercontent.com/24474762/74088317-58494200-4a95-11ea-91a5-931c207a8ead.png)

### Friendica version you encountered the problem
git, develop ; php7.3 , mariadb

**Comment by annando** [comment]
Look for the link named "more".

**Comment by MrPetovan** [comment]
It's tucked with the activity buttons (Like, Dislike, Comment, Share, Attend...)

**Comment by hoergen** [comment]
Oh I see. Thanks 👍

**Comment by hoergen** [comment]
Have to reopen, because "more" has a line break and is hidden by existing "likes"

![00_temp](https://user-images.githubusercontent.com/24474762/74134875-99ec0100-4beb-11ea-8939-ddeac1701bea.png)

**Comment by hoergen** [comment]
reopen

**Comment by MrPetovan** [comment]
@annando Founs it was specific to Firefox.
