### ISSUE TITLE
Frio: Align the network icons

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8264]
### Expected behavior
I know that's kind of nitpicking but small things are important, too. :-) I think the network icons in the top corner of posts and comments should be horizontally aligned.
The position looks better in the post. I think it is too near to the border of the background "card" in the comments.

### Actual behavior
Since we removed the drop down menu it is more obvious that the icons are not horizontally aligned.

### Steps to reproduce the problem

![Bildschirmfoto von 2020-02-09 20-07-02](https://user-images.githubusercontent.com/3656054/74108283-011c9d80-4b79-11ea-976c-286bf9202dc7.png)

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
I didn't align the icons exactly, instead I used the padding top value that is slightly lower for comments than for the top level post.
