### ISSUE TITLE
Profile description isn't converted to HTML for remote publish

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8280]
Follow-up to #8261
Part of #7817 

See https://friendica.mrpetovan.com/display/735a2029-645e-4571-caeb-0e5369673401

We send the raw BBCode string to remote systems fetching Friendica profiles. We need to provide the HTML version for non-Friendica systems.

Do we have to provide plaintext ourselves for systems not supporting HTML in profile descriptions (like Friendica pre-2020.03)?

**Comment by annando** [comment]
We should provide the HTML when queried via AP. Possibly Markdown via Diaspora (we have to check how they send their stuff) and possibly BBCode with anything that is Friendica<->Friendica only.

**Comment by MrPetovan** [comment]
Result:
- Diaspora: Plaintext which we were already doing
- DFRN: BBCode
- ActivityPub: HTML that we currently convert back to BBCodes on reception, which prevents any specific Friendica <-> Friendica shenanigans.

**Comment by MrPetovan** [comment]
Closed by #8333
