### ISSUE TITLE
Frio: background color of unseen notifications barely visible

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8281]
### Expected behavior
The background color of unseen notifications should be better visible.

### Actual behavior
The background color of unseen notification is only barely visible. Sometimes it is very hard to notice the difference to the background color of already seen notifications.

### Steps to reproduce the problem
Receive a new notification. See the background colors of the new notification. Compare it to the default background color.

### Proposed solution
Change the CSS to use `#dcecf0` color value. It is similar to the current color but better visible.
https://www.color-hex.com/color/dcecf0

For comparison our current color:
https://www.color-hex.com/color/f3fcfd

I have tested it locally. Unseen notifications are much better visible.

What do you think? I can do the PR. It's a child's task. ;-)

![Bildschirmfoto von 2020-02-13 21-32-14](https://user-images.githubusercontent.com/3656054/74475872-9042f180-4ea8-11ea-9710-3c7ede03f3ee.png)

Fixed by #8282

**Comment by AlfredSK** [comment]
Or is there a color palette to pick a color from?

**Comment by MrPetovan** [comment]
I'm confused by your screenshot, were you hovering the last item when you took it?

**Comment by AlfredSK** [comment]
No. Maybe you never noticed. We have a light-blue background for all unseen notifications. The first notification is a new (unseen) notification.
My mouse was hovering over the old notification on the bottom. The one with you in it. :-)

This is a screenshot with the changed color. (I changed it locally from light-light blue to the color you see in the screenshot)

**Comment by MrPetovan** [comment]
Ok, it makes more sense. And I meant the last item in top-to-bottom order, not the most recent notification that I see you have changed the background color.

We have to make sure this color isn't part of the scheme or custom-defined colors before we can actually change it wherever it is appropriate.

**Comment by AlfredSK** [comment]
The color is only used here...
https://github.com/friendica/friendica/search?q=f3fcfd&unscoped_q=f3fcfd

**Comment by MrPetovan** [comment]
Perfect, you can even make the change yourself!

**Comment by AlfredSK** [comment]
I'm not sure about the plusminus scheme. I don't know what other stuff is changed there. So, I would rather only change the main style.css file.

What do you think about the color? Should it be a little less colorful to better match the hover background color?

**Comment by MrPetovan** [comment]
If it was using the previous color, I think you can change plusminus as well. The color is fine to me and I'm not sure how it has to match the hover color.

**Comment by AlfredSK** [comment]
It has to be similar in saturation and brightness to not look like an alien. :-)
I think I found a better one:
https://www.color-hex.com/color/e3eff3

**Comment by MrPetovan** [comment]
Seems like you have this under control, I trust you.

**Comment by AlfredSK** [comment]
Do you have an idea where this is used? I have never seen a background color there.

https://github.com/friendica/friendica/blob/e757d16fc167e4b421b38a4267bb2addd6aaace0/view/theme/frio/css/style.css#L2981-L2984

**Comment by MrPetovan** [comment]
Me neither.
