### ISSUE TITLE
Frio: post preview is showing old action menu

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8288]
### Expected behavior
Since the old action menu has been moved to the new `···more` menu it should not show up anywhere. The leftovers should be removed as well.

### Actual behavior
I never noticed that before but frio is showing the action menu in the post previews. That dropdown menu should be removed there for consistency.

![preview_20200215141949](https://user-images.githubusercontent.com/3656054/74588662-c2666780-4ffe-11ea-83d3-829818574262.png)

### Steps to reproduce the problem
Create a new post. Click on preview.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Closed by #8332
