### ISSUE TITLE
Frio: Notifications icon usability issue

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8290]
### Expected behavior
Clicking/tapping on the notification icon (bell) should open the drop-down menu whether or not there is an info bubble for new notifications.
The info bubble should be "click-through".

### Actual behavior
The info bubble is preventing the correct function of the dropdown menu. When you click/tap on the info bubble the dropdown menu doesn't open. You need to click beside the info bubble to open it.

On other icons it works like expected (e.g. the network icon).

### Steps to reproduce the problem
Receive a new notification. Click/tap exactly on the info bubble. Then click/tap beside the info bubble. Experience the difference! :-)

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Maybe that also happens with other themes but I don't use them. So I cannot tell if this is theme specific.

**Comment by MrPetovan** [comment]
No, it is specific to frio since @annando changed the notification icon from `<a>` to `<button>` for accessibility purposes.
