### ISSUE TITLE
XML in codeblocks damaged on delivery

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8299]
### Expected behavior
When I post some XML lines in a BBCode code block it should be delivered as such and displayed as XML in a code block for the communication partners.

### Actual behavior
The XML in the code block looks good locally in my post but it is damaged on delivery. Sometimes the whole content of the code block vanishes.
 
### Steps to reproduce the problem
**This is the original stuff I posted on a develop node:**
https://libranet.de/display/0b6b25a8-155e-47ea-0fca-438626977648

```
[code]<policy domain="resource" name="thread" value="1"/>[/code]

and

[code]
<policy domain="resource" name="width" value="5KP"/>
<policy domain="resource" name="height" value="5KP"/>
<policy domain="resource" name="area" value="32MB"/>
[/code]
```

**And this is how it looks on other nodes:**

Forum node (master) - both code blocks empty:
https://forum.friendi.ca/display/0b6b25a8-155e-47ea-0fca-438626977648

Venera (master) - code block looks like BBCode instead of XML:
https://venera.social/display/0b6b25a8-155e-47ea-0fca-438626977648

Mordor (develop) - code blocks empty, plus line breaks vanished:
https://mordor.social/display/0b6b25a8-155e-47ea-0fca-438626977648

### Friendica version you encountered the problem
2020.03-dev (posted and received on develop)
2019.12 (received on master)

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Interessting. On Mastodon the XML looks right.

**Comment by tobiasd** [comment]
I have the same problem on my node running develop. Though I _only_ have seen mis-escaped `&gt;` in code blocks lately. But these brackets _are_ a subset of XML.

**Comment by MrPetovan** [comment]
Oh boy.

**Comment by MrPetovan** [comment]
After a couple tests this seems to concern the transmission of a message by a forum to its members and I'm out of my depth in this regard.

**Comment by annando** [comment]
The transmission via Diaspora and ActivityPub looks fine - but DFRN seems to have troubles.

**Comment by annando** [comment]
I guess this part is responsible: https://github.com/friendica/friendica/blob/develop/src/Protocol/DFRN.php#L2377-L2396

**Comment by MrPetovan** [comment]
Awesome, thanks for looking into it!

**Comment by AlfredSK** [comment]
Tested with rc -> rc. Works.
