### ISSUE TITLE
Friendica PWA doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8310]
Currently Friendica isn't recognized as PWA on Firefox for Android. You can't add it to home screen as a web app.

I tried to modify PWA manifest and it seems that Firefox requires "sizes" and "type" properties for "icon".

The following works for me:

```
{
  "name": "{{$title}}",
  "start_url": "{{$baseurl}}",
  "display": "standalone",
  "description": "A Decentralized Social Network",
  "icons": [{
    "src": "{{$baseurl}}/{{$touch_icon}}",
    "sizes": "128x128",
    "type": "image/png"
  }]
}
```

But maybe it is a good idea to add all currently supported fields so it will be more future-proof:
```
{
  "name": "{{$title}}",
  "start_url": "{{$baseurl}}",
  "display": "standalone",
  "description": "A Decentralized Social Network",
  "theme_color": "black",
  "background_color": "black",
  "short_name": "Friendica",
  "icons": [{
    "src": "{{$baseurl}}/{{$touch_icon}}",
    "sizes": "128x128",
    "type": "image/png"
  }]
}
```

**Comment by MrPetovan** [comment]
It isn't recognized as a PWA by iOS either, thank you for the suggestion, I'll implement it later in the week.

**Comment by wiwie** [comment]
Small addition to issue description: the relevant file is 
```
view/templates/manifest.tpl
```

**Comment by MrPetovan** [comment]
Related: https://github.com/friendica/friendica/issues/2800#issuecomment-565178129

**Comment by MrPetovan** [comment]
I can confirm this works with iOS Safari, Friendica is correctly recognized as a Add to Home Screen app again.

**Comment by annando** [comment]
I just tested with Chrome under Android.

**Comment by annando** [comment]
Icecat works as well. So I assume that it will work with other browsers as well.
