### ISSUE TITLE
Capture API Login Data

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#8314]
### Expected behaviour

The capturing of users' last login data (date and time) regardless of method of access.

### Actual behaviour

Currently users' last login date/time are not recorded if accessed via API.

This can result in puzzling displays in the Admin panel like this:

![image](https://user-images.githubusercontent.com/28751375/74843802-08089480-535f-11ea-974d-03cf92fc0bc8.png)

It more problematically may cause accidental deletion of user accounts in conjunction with the public_server addon as discussed here:

https://forum.friendi.ca/redir/137?url=https://friendica.hubup.pro/display/174591b4-185e-4d04-af2f-6f9087439805

### Steps to reproduce the problem

Log out of a user account for some time and post via a client. Compare Last login and Last item via the admin panel.

### Friendica version you encountered the problem

2020.03-dev

**Comment by AndyHee** [comment]
When I initially open this issue, I thought about automation of user management (e.g. cleaning up scripts).

I think not recording user logins represents a serious **security** issue. Could this please be reflected in label, so that this is not merely a fancy enhancement. Thanks.


Below additional screenshots of two active test accounts. The first one posts publicly, the second one only private posts.

![10229355145e50d90ad7928335579702-0](https://user-images.githubusercontent.com/28751375/79293257-71d79180-7efd-11ea-838c-ce8285ff2e7f.png)
![17074592045e95c71dd1d44965455517-0](https://user-images.githubusercontent.com/28751375/79293261-756b1880-7efd-11ea-9189-59ed0942a1da.png)

**Comment by MrPetovan** [comment]
Why is it a security issue?

**Comment by AndyHee** [comment]
Password login is a form of access control. A robust access control process requires adequate logging or monitoring capability. 

Insufficient logging of access will not allow the tracing of malicious activity on the system. Administrators cannot determine whether or when an account has been accessed subsequent a suspected security breach.

In particular, determining time of access in case of a breach is crucial as it allows to contextualise other logs. It will allow the piecing together of other relevant information that may shed light on the nature of the breach. This can help explaining what might have happened and could prevent further potential breaches.


Further  reading: 
David Kim (2010)  _Fundamentals of Information Systems Security_ Jones & Bartlett Learning

**Comment by MrPetovan** [comment]
Thank you for the elaboration!

**Comment by AndyHee** [comment]
Thank you @MrPetovan for fixing this! Really appreciated!
