### ISSUE TITLE
Record Last Item Date for Items with Restricted Persmission 

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#8325]
### Expected behaviour

Node operators should be able to see via the admin panel, whether a user account is active or not, or whether it has been abandoned.

### Actual behaviour

Currently there is no certain way of telling via the admin panel, whether an account is active or not. If an account is operated with strict permission and does not respond to public posts or sends items with restricted permission, admins cannot know the account status.

This is particularly relevant for users who use Friendica via an API client (see https://github.com/friendica/friendica/issues/8314), but may also affect users via web interface. 

### Steps to reproduce the problem

See here: https://friendica.hubup.pro/redir/552?url=display/174591b4-975e-50db-a29a-a42222519292
### Friendica version you encountered the problem

2020.03-dev

**Comment by AndyHee** [comment]
Thanks @tobiasd for labelling this. I didn't explain this well. I don't think it's an UI issue.

In the DB table `contact` there is a field called `last-item`. This is populated with a time/date value every time the user sends an item. This value shows in the user section of the admin panel.

For some reason, this `last-item` value is not recorded when the permission of an item is set to private. I'm not sure if this only happens via API or all posts. I will find out later.

**Comment by annando** [comment]
The `last-item` is only used for public posts for privacy issues. We do publish this data as well. So we should only use data that is public.

**Comment by AlfredSK** [comment]
The privacy concern is a valid point.
But it seems that posts via API are not taken into account. I have seen a profile with two public posts but the admin panel is showing 'last item: never'.

**Comment by tobiasd** [comment]
> Node operators should be able to see via the admin panel,

@AndyHee but I did not want to include an AI label, for "Admin Interface" and the admin user still is kind of a user. Hence I came around to the UI label.

**Comment by AndyHee** [comment]
> The `last-item` is only used for public posts for privacy issues. We do publish this data as well. So we should only use data that is public.

Thanks @annando for sheding light on this.

I'd like to rename the heading in the user section to "Last public item" to make it less confusion for admins.

I'll also initiate a discussion in the support forum about a meaningful mechanism that will show a time frame of adequate length without revealing an actual time stamp for activity. This can be a nice compromise between protecting users' privacy and efficient administration.

**Comment by AndyHee** [comment]
> > Node operators should be able to see via the admin panel,
> 
> @AndyHee but I did not want to include an AI label, for "Admin Interface" and the admin user still is kind of a user. Hence I came around to the UI label.

Now, I understand after having read Michael's reply that this is an enhancement that requires work on the UI and elsewhere.

**Comment by AndyHee** [comment]
Closing this as PR https://github.com/friendica/friendica/pull/8330 addressed some of the issues.

Anything else is currently not feasible.
