### ISSUE TITLE
Mentions from SocialHome are incorrectly processed

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8338]
See https://friendica.mrpetovan.com/display/b20fe479-c5421ac97582e1dc-7a3e85af

**Comment by MrPetovan** [comment]
Item source:
```json
{
  "@context":[
    "https://www.w3.org/ns/activitystreams",
    {
      "pyfed":"https://docs.jasonrobinson.me/ns/python-federation"
    },
    {
      "Hashtag":"as:Hashtag"
    },
    "https://w3id.org/security/v1",
    {
      "sensitive":"as:sensitive"
    }
  ],
  "type":"Create",
  "id":"https://jasonrobinson.me/u/jaywink/#activities/21bbf979-8205-4dc7-92ff-062ab513eb2f",
  "actor":"https://jasonrobinson.me/u/jaywink/",
  "object":{
    "id":"https://jasonrobinson.me/content/e6f925b6-c4e2-48bd-83b2-91e3478fb967/",
    "type":"Note",
    "attributedTo":"https://jasonrobinson.me/u/jaywink/",
    "content":"<p>@<a class=\"mention\" href=\"https://friendica.mrpetovan.com/profile/hypolite\" rel=\"nofollow\" target=\"_blank\"><span>Hypolite Petovan</span></a> :P Was there something fundamentally wrong with the job or just wrong time?</p>",
    "published":"2020-02-25T21:16:56.125439+00:00",
    "inReplyTo":"https://friendica.mrpetovan.com/objects/735a2029-145e-558e-1991-92d360977974",
    "sensitive":false,
    "summary":null,
    "url":"",
    "source":{
      "content":"@{https://friendica.mrpetovan.com/profile/hypolite} :P Was there something fundamentally wrong with the job or just wrong time?",
      "mediaType":"text/markdown"
    },
    "tag":[
      {
        "type":"Mention",
        "href":"https://friendica.mrpetovan.com/profile/hypolite",
        "name":"https://friendica.mrpetovan.com/profile/hypolite"
      }
    ],
    "to":[
      "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc":[
      "https://friendica.mrpetovan.com/profile/hypolite"
    ]
  },
  "published":"2020-02-25T21:16:56.125439+00:00",
  "to":[
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc":[
    "https://friendica.mrpetovan.com/profile/hypolite"
  ]
}
```

**Comment by annando** [comment]
Well, see the `tag` element: `"name":"https://friendica.mrpetovan.com/profile/hypolite"`. In my opinion this is a SocialHome bug.

**Comment by MrPetovan** [comment]
In what way? What should be the `name` property? How would it fix the issue since we don't support curly brackets anyway?

**Comment by annando** [comment]
AFAIK the name should contain the name. I hat to check for that. And what do you mean with "we don't support curly brackets"?

**Comment by MrPetovan** [comment]
Look at the mention in Jason's post, it still shows the curly brackets around the profile URL from the source, it isn't just a profile name issue:
![Screen Shot 2020-02-26 at 16 15 43](https://user-images.githubusercontent.com/925415/75388646-56fc7f80-58b3-11ea-8382-ceb0dc8e7d01.png)

**Comment by annando** [comment]
Ah, now I understand. This is a different thing. This is some Diaspora thing. So for interpreting the Markdown stuff we need to do some Diaspora magic here as well.

**Comment by AlfredSK** [comment]
Interesting. The closing curly bracket seems to be part of the link.

**Comment by MrPetovan** [comment]
Yes, because it is a valid character in URLs.

**Comment by MrPetovan** [comment]
> Ah, now I understand. This is a different thing. This is some Diaspora thing. So for interpreting the Markdown stuff we need to do some Diaspora magic here as well.

Diaspora magic? Or more like "special case for SocialHome" ?

**Comment by annando** [comment]
No. This curly stuff is used by Diaspora for their mentions. So the Markdown content from SocialHome is using this as well in AP.

**Comment by MrPetovan** [comment]
I found the issue, when we convert from Markdown to HTML we run the autolink regular expression to generate anchor tags from stray URL, so the `@{url}` form becomes `@{<a href="url">url}</a>` and doesn't get picked up by the mention detector. So we have to do it before the Markdown to HTML conversion.
