### ISSUE TITLE
support as:announce for events

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8341]
### Expected behavior

`as:Announce` reactions to postings are correctly understood and handled by Friendica.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://layer8.space/users/gebrauchskunst/statuses/103720551923879083/activity",
  "type": "Announce",
  "actor": "https://layer8.space/users/gebrauchskunst",
  "published": "2020-02-25T17:00:23Z",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "https://libranet.de/profile/fsfeberlin",
    "https://layer8.space/users/gebrauchskunst/followers"
  ],
  "object": "https://libranet.de/objects/0b6b25a8-445e-54c1-6555-a50991506655",
  "atomUri": "https://layer8.space/users/gebrauchskunst/statuses/103720551923879083/activity"
}
```

* original Reaction https://layer8.space/users/gebrauchskunst/statuses/103720551923879083/activity
* to Friendica event https://libranet.de/objects/0b6b25a8-445e-54c1-6555-a50991506655

### Actual behavior

What looks like an event entry is added to the network stream with the title "as:Announce", a date seemingly unrelated to the posting and a starting time at 0h.

### Steps to reproduce the problem

* post an event

### Friendica version you encountered the problem

2020.03-dev (libranet.de)

**Comment by annando** [comment]
We do support Announces - but it seems as if it could be a problem with events.

**Comment by MrPetovan** [comment]
Can you please confirm #8461 fixes this issue?

**Comment by tobiasd** [comment]
jepp
