### ISSUE TITLE
Notification link in new follower email seems invalid

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8342]
From https://friendica.mrpetovan.com/redir/252857?url=https://venera.social/display/85a863ed-205e-575c-b54d-3f9686539256 (in French)

Apparently the generated link in the notification email for new followers ends up in an "Unauthorized" error page.

@nupplaphil can you please look into it?

**Comment by nupplaphil** [comment]
Which version does it occur?
As far as I can see, I wiped the `notify/view/{id}` route in favor of `notification/{id}`.

**Comment by nupplaphil** [comment]
This - normally - happens in case the user isn't logged in.
It is also a master-specific issue, the develop branch is now working as said with a different route.

@MrPetovan can you ask if he was logged in when he clicked the link?

**Comment by MrPetovan** [comment]
I was able to confirm it, the user was expecting a login form instead of an error.

**Comment by nupplaphil** [comment]
ah I now understand
