### ISSUE TITLE
Share of Twitter tweet doesn't show image in editor modal nor embed image in post.

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8363]
### Expected behavior
When pressing share for the twitter tweet at https://twitter.com/Ecosia/status/1235159488564539394 in friendica using the frio theme, the showing modal for editing the reshare should look like this: 
![grafik](https://user-images.githubusercontent.com/2605261/75878589-21f3ae00-5e1a-11ea-90ae-725f0679103c.png)
and the image of the original tweet should be embedded in the reshare.

### Actual behavior
The modal looks like this:
![grafik](https://user-images.githubusercontent.com/2605261/75878634-320b8d80-5e1a-11ea-9e8f-b8b931f5b13b.png)
i.e., the image is never shown, also not when clicking back and forth between the modal tabs. The image is also not embedded in the reshare if submitted.

If closing the modal and hitting share a second or third time, the image is correctly loaded and also embedded in the reshare. 

### Steps to reproduce the problem
1. Hit share for the tweet in friendica
2. Wait for the modal to show

### Friendica version you encountered the problem
recent develop branch

### Friendica source (git, zip)
git

### Friendica source (git, zip)
git; on branch develop

### PHP version
PHP 7.3.11-0ubuntu0.19.10.3 (cli) (built: Feb 12 2020 15:22:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.3, Copyright (c) 1999-2018, by Zend Technologies

### SQL version
mysqld  Ver 5.7.29 for Linux on x86_64 (MySQL Community Server (GPL))

**Comment by utzer** [comment]
I had a problem like this, but it worked breifly after deactivating the twitter add-on and reactivating it again. @wiwie can you try this?

**Comment by wiwie** [comment]
Did this happen to you recently?

I haven't encountered this issue for some time. This issue was created quite some time ago. So I think I'll close the issue for now unless you encountered it recently.

**Comment by utzer** [comment]
> Did this happen to you recently?

Yes, last week. But go ahead to close the issue, I need to open a new one for the embedding in general I think. For Twitter the solution was to briefly deactivated the Twitter add-on, but since I tried that I also didn't post any Twitter links myself. However I see plain Twitter links without previews coming from Diaspora.
