### ISSUE TITLE
Limit post content by rendered height instead of number of characters

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8374]
I'm sometimes receiving posts that are excessive in height containing lots of images or formatting that stretches the content vertically.

The current implementation of the showmore add-on takes into account only the number of characters of the post. This approach does not necessarily catch the above cases. 

It would be nice if the existing logic could be adapted in the showmore add-on or a new add-on could be implemented that is able to calculate the rendered height of the post and limits it to a user-specified number of pixels.

I believe that this could be solved by some combination of css + JavaScript. A css class could be used to limit the height of the post content div to X pixels, and JavaScript could be used to (1) append a button at the end of that div that triggers JavaScript functions that (2) dynamically adds and removes the previously mentioned css class from the div.

**Comment by MrPetovan** [comment]
Thanks for the implementation suggestion!

**Comment by wiwie** [comment]
I have a more or less working prototype which could be used as a starting point.

It's not thoroughly tested, and I just discovered that it doesn't always work with twitter widgets, possibly because they are loaded asynchronously after the height of the div is calculated and hence it appears to be of small height, while it in fact isn't.

**Comment by wiwie** [comment]
ok, it also doesn't work with content that is loaded when scrolling. will improve it a bit more before it should be used for anything...

**Comment by MrPetovan** [comment]
Thank you for your time!

**Comment by wiwie** [comment]
My solution now also works with infinite scroll. Problems with Twitter persist.

**Comment by wiwie** [comment]
Have a working version now for all kinds of posts. It turned out to be not depending on the platform of the post, but on the fact that the events I was using fired when DOM was fully loaded and possibly before images were loaded. Hence leading to incorrect heights. I'm now using a trigger function I found on SO that waits for images to load and then fires. Current problems with it:

(1) it's hard coded into core friendica JavaScript, css, and template files. So it's not an add-on at all.
(2) the cutoff height is not parameterized.

Should I try to figure it out myself to turn it into an add-on (possibly with someone's help), or does anyone with more experience volunteer to finish it?

**Comment by wiwie** [comment]
Actually not sure though whether it's at all possible to wrap this functionality into an add-on...

**Comment by MrPetovan** [comment]
Can’t you add the feature in a separate JS file that can be included by an add-on?

**Comment by MrPetovan** [comment]
If you submit a PR I’d be able to tell you with more details how to put it in an add-on.

**Comment by wiwie** [comment]
Will do create a PR not likely later today

**Comment by wiwie** [comment]
See PR at https://github.com/friendica/friendica/pull/8402 .

**Comment by wiwie** [comment]
Created a second PR for an implementation as addon at friendica/friendica-addons#968.

**Comment by wiwie** [comment]
Should this issue be closed now that the PR is merged?

**Comment by MrPetovan** [comment]
Absolutely, but it's yours, so you're getting the honor.
