### ISSUE TITLE
Database Error while upgrading

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8378]
After the git pull today the database was updated and I got the error message (german)

```
Die Fehlermeldung lautet
Fehler beim Ändern der Datenbank aufgetreten ALTER IGNORE TABLE `conversation` ADD `direction` tinyint unsigned NOT NULL DEFAULT 0 COMMENT 'How the message arrived here: 1=push, 2=pull'; 
```

A manual `php bin/console.php dbstructure update` didn't help either.

### Friendica version you encountered the problem
git / php7.2 / mariadb

**Comment by annando** [comment]
Please execute ```ALTER IGNORE TABLE `conversation` ADD `direction` tinyint unsigned NOT NULL DEFAULT 0 COMMENT 'How the message arrived here: 1=push, 2=pull';``` in the mysql console and report the error.

**Comment by hoergen** [comment]
`Fehler in der SQL-Abfrage (1060): Duplicate column name 'direction' `

**Comment by annando** [comment]
What does `php bin/console.php dbstructure update -f` tell?

**Comment by hoergen** [comment]
No output ... tells nothing

**Comment by hoergen** [comment]
But why it should it print something? 
The error message says : There is already a column named "direction" you can't add another one, what the SQL statement tries to do.

**Comment by annando** [comment]
When `php bin/console.php dbstructure update -f` doesn't return anything, then - except from the message - everything worked well. Possibly there had been two jobs performing the same database alteration at the same time?

**Comment by hoergen** [comment]
Maybe but i still have the BIG YELLOW WARNING in the Administrator section. How can I get rid of it?

**Comment by annando** [comment]
I never had this warning. I'm unsure how to get rid of it.

**Comment by hoergen** [comment]
The solution is, to talk to you. I checked it again and now it is gone. You should provide a chat robot ;))

Thanks a lot for your help 🌻
