### ISSUE TITLE
Number of reshare (Support for native reshares)

### ISSUE THREAD

**Issue by OpenCode** [friendica/friendica#838]
If someone reshare a post, the original user can't know this. Is possibile to have the reshares number and who have shared the post?

**Comment by MrPetovan** [comment]
@annando came through with a neat suggestion
> [We can] treat a reshare like a "like" or "dislike", means that it will be treated just like an activity for an item. We won't use the different author/owner combination for this anymore. Instead there will be some notice at the bottom of the item. Comparable to the "X persons like this", we will then have some "X persons reshared this".

**Comment by MrPetovan** [comment]
Closed by #6966 !
