### ISSUE TITLE
Profile image upload problems from mobile

### ISSUE THREAD

**Issue by bright-star** [friendica/friendica#839]
Multiple users reported problems cropping uploaded profile photo once registering.

For myself, on a Samsung Galaxy S2 running Android 4.2.2, tapping the "browse' button to upload an image does nothing in Tint Browser.

Using the default Android browser, I can upload an image but the crop handles don't respond to tapping, making it impossible to crop.

**Comment by MrPetovan** [comment]
I've been able to upload images on iOS, however the image caption in the image browser is not clickable, so I wasn't able to insert them in my messages. This is a way minor issue that can be easily solved with a `pointer-events: none;` on the caption element, allowing clicks and taps to go right through it and to select images even if the caption is completely covering them.

**Comment by MrPetovan** [comment]
There has been talks about replacing the JS cropping library, I can't find where though, maybe it was from @fabrixxm ?

**Comment by AlfredSK** [comment]
See issue #4572

**Comment by MrPetovan** [comment]
Ah, thanks!

**Comment by AlfredSK** [comment]
I think this is fixed by #4711 and can be closed.
