### ISSUE TITLE
[frio] Allowed contact/groups are also added to the disallowed ACL

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8393]
See https://forum.friendi.ca/display/adf174d5-195e-6631-3fd3-158733851512

Selecting any contact/group in the `Allowed` ACL field ends up adding them to the `Disallowed` ACL field after submitting, making private posts effectively distributed to nobody.

**Comment by annando** [comment]
It isn't just a display problem?

**Comment by MrPetovan** [comment]
I do not know. I would need to make a more specific test I would be able to receive on my accounts.

**Comment by MrPetovan** [comment]
I tried publishing a private post to my dev account from my regular account, the post says "delivery to remote servers is done 1/1" but I got nothing on my dev node.

**Comment by annando** [comment]
I just did a small test and everything looked great. The display was correct and the message had been delivered.

**Comment by AlfredSK** [comment]
Works here too. Looks good on sender's side and was delivered to both receivers (master and rc).

![Bildschirmfoto von 2020-03-09 20-51-02](https://user-images.githubusercontent.com/3656054/76251829-03d9e380-6248-11ea-8ba1-86456c4c2c2e.png)

**Comment by atasingorneq** [comment]
> It isn't just a display problem?
No, no display problem on my system. I tested it again.

Friendica 2020.03-rc - 1337
PHP 7.2.27

**Comment by AlfredSK** [comment]
Could this be dependent of the user's default post permission? Mine is public. But maybe the issue occurs when the user has set private posts as default. – Just a wild guess...

**Comment by MrPetovan** [comment]
I don't have default post permissions on my regular account.

**Comment by MrPetovan** [comment]
The actual use case to reproduce this is to select any contact group in the Deny field, and then the contacts/groups in the allow field are automatically added, and this bug prevented to select multiple contacts/groups in the Deny field as well.
