### ISSUE TITLE
Specific Mastodon posts can't be imported

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8394]
These Mastodon public post URLs give no results when searched on. They should be imported as public post to be interacted with:
- https://radical.town/@velexiraptor/103794092364276493
- https://radical.town/@velexiraptor/103794123399939923

The author profile sports a lock on the side of their webfinger address, does it prevent technical endpoint access?

**Comment by MrPetovan** [comment]
I can't seem to be able to follow the author either, I'm getting the following error:

> The profile address specified does not provide adequate information.
No compatible communication protocols or feeds were discovered.

Profile URL: https://radical.town/users/velexiraptor

**Comment by AlfredSK** [comment]
The probe for https://radical.town/users/velexiraptor looks ok here on current RC.
Import of both posts works as well.

**Comment by AlfredSK** [comment]
The lock on the webfinger address in Mastodon means that the user has enabled the approval of new followers.

**Comment by MrPetovan** [comment]
Of course it's possible that my instance would be blocked by `radical.town`, although unlikely?

**Comment by MrPetovan** [comment]
Doesn't work either from my dev node at https://dev-friendica.mrpetovan.com

**Comment by annando** [comment]
I just tested it and it does work here. Does something like this happened again?

**Comment by MrPetovan** [comment]
Tested it and it works too.
