### ISSUE TITLE
posts to other people's walls can't be edited

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#840]
Is this a bug or a feature? When attempting to edit a post commenting on someone else's wall, I am taken to a page indicating that the post cannot be found.

**Comment by silke** [comment]
Are we clear about the *intended* behaviour?

**Comment by Beanow** [comment]
I don't think we are, but in hindsight I would go for editing on your home server.
So somehow the edit link needs access to some mutually known ID. Maybe the GUID or URI is known on both servers?

**Comment by AlfredSK** [comment]
Checked this one. I'm recognized and remote authenticated by a forum account. I can post and comment but as soon as I try to edit one of my own forum posts I get a "post not found" notification. So, this issue is still valid.

Friendica 2018.12-rc

**Comment by annando** [comment]
Yeah, this is possibly impossible.

**Comment by fabrixxm** [comment]
![](http://cdn2.sbnation.com/imported_assets/861236/castle_confused.gif)
