### ISSUE TITLE
Contact about field on /display doubled

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8404]
### Expected behavior

See the _about_ text of a contact once in the aside widget on `/display` underneath the contacts profile picture.

### Actual behavior

It is displayed twice, at least using the `vier` theme, once above and once beneath the image.

![friendica-20200311](https://user-images.githubusercontent.com/433490/76399736-6d104280-637f-11ea-804c-ce5216d5cbaa.jpg)

### Steps to reproduce the problem

1. Visit a posting at `/display`

### Friendica version you encountered the problem

2020.03-rc

**Comment by MrPetovan** [comment]
Thank you for the report!
