### ISSUE TITLE
Contacts statuses or statuses and comments should contain reshares

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8414]
### Expected behavior
When a contact is resharing posts from other contacts, these reshares should be visible, when I open the contacts status page on my node. Or maybe under status and comments.

### Actual behavior

Actually I only can see the reshares in my stream, but not on the status page of that contact on my node.

### Friendica version you encountered the problem
git / 2020.3-rc / MariaDB / PHP7.2

**Comment by annando** [comment]
That is based on the way we are doing (and storing) reshares.

**Comment by hoergen** [comment]
Maybe it is not implemented, but it isn't an UX (User Experience) because reshares are part of a users timeline, when you visit their profiles on their server. And it isn't an Enhancement as well, because it should be part of a basic view on a users profile. So i consider it more as a bug as a Enahncement. If there would be a category for it, it should be "unfinished".

**Comment by MrPetovan** [comment]
It is UX because it doesn't pertain to the source code itself but to Users and their eXperience and especially eXpectations.

**Comment by annando** [comment]
It would be a bug when the expected behaviour would differ from the outcome. But the system currently behaves exactly how it is expected when you know the technical background. Reshares are still a complete mess from the technical side.

**Comment by hoergen** [comment]
> But the system currently behaves exactly how it is expected
Surely from developer point of view, but if a user want to see, what a contact "posted" lately, a user expects to see the reshares as well.

I understand, that this is under construction, but I didn't find an issue for that and I think it is really important to not forget that this part wont be forgotten.

**Comment by MrPetovan** [comment]
Thanks, you did the right thing opening an issue.

**Comment by annando** [comment]
Yeah, I do understand that users are expecting a different behaviour.

**Comment by hoergen** [comment]
Orphaned. Closing.
