### ISSUE TITLE
RU Translation errors

### ISSUE THREAD

**Issue by eugene-vereshchagin** [friendica/friendica#8417]
Account preferences >> Security and Confidentiality:

>Разрешить друзьям отмечять ваши сообщения? 
>Your contacts can add additional tags to your posts.

отмечять => отмечать

Позвольть предлогать Вам потенциальных друзей?
If you like, Friendica may suggest new members to add you as a contact.

Позвольть => Позволять
предлогать => предлагать

source: meld.de

**Comment by MrPetovan** [comment]
Thank you for the report, we use a third-party service to manage translation with Transifex: https://www.transifex.com/friendica/friendica/

If you want to edit the translations directly, you can create an account over there and make the corrections yourself.
