### ISSUE TITLE
Notification texts not translated

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8432]
### Expected behavior

Notification text being translated into the language used by the user.

### Actual behavior

They are not. All notifications are displayed with the English template text; e.g. "commented on their" and then the placeholders are inserted accordingly to the user selected language.

> $PersonXYZ commented on $PersonABC's Beitrag "Good  morning"

In `include/enotify.php` (ll 175) the `$message` is constructed outside of the `l10n->t()` call which might cause this problem.

### Friendica version you encountered the problem

2020.03-dev but just now had time to look into the code.

**Comment by annando** [comment]
I think this should be fixed in this release.

**Comment by tobiasd** [comment]
Notifications are still untranslated for me

**Comment by tobiasd** [comment]
Note, the "XYZ shared a new item" ("XYZ hat einen neuen Beitrag geteilt") in the case of notifications for a new postings of a contact is translated correctly.

**Comment by tobiasd** [comment]
The regen of the messages.po did not help, so I'll move this issue to the next level.

**Comment by annando** [comment]
The messages.po does contain these texts: https://github.com/friendica/friendica/blob/develop/view/lang/C/messages.po#L476-L529

Isn't this enough? Or is there any other additional magic needed?

**Comment by tobiasd** [comment]
Aparently that is not enough. At least on my node notifications about comments and replies are untranslated. Only the "$somebody shared a new item" notification seems to be translated in the UI.

**Comment by annando** [comment]
I don't know the exact procedure how the texts are transferred to transifex. I thought that `messages.po` would be taken as a basis?

**Comment by annando** [comment]
It had been fixed by https://github.com/friendica/friendica/pull/8777

**Comment by tobiasd** [comment]
Yes, the messages.po file is taken by Transifex and the strings are translated. Once they arrive in the strings.php files of the languages, they should replace the original text. For some reason this is (was?) not working for these notification strings. Lets see if the latest updates change something about that.

**Comment by annando** [comment]
It did. I already got translated notifications this morning.
