### ISSUE TITLE
Feature Request: Additional info in registration request

### ISSUE THREAD

**Issue by bright-star** [friendica/friendica#844]
When a registration request arrives, the only  information present is email and name. It would be extremely useful to allow a short note to be included as part of the registration process, as admins may not be able to link pseudonyms and emails to people, but still want to limit registrations based on other information.

**Comment by silke** [comment]
Sorry for the moment - I'm removing feature requests from 3.4, for the week to come let's concentrate on bug fixes.

**Comment by tobiasd** [comment]
this is now in the current develop version so I'll close this issue

**Comment by bright-star** [comment]
Thanks!
