### ISSUE TITLE
[twitter] Allow mentions of Friendica profiles, don't link back to Twitter

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8440]
### Expected behavior
When I insert a (web)mention `@user@friendica.node` in a Tweet it should be imported and displayed as a mention in Friendica - if possible. It shouldn't become a (broken) link to Twitter.

### Actual behavior
On Twitter itself the `@user@friendica.node`-mention is displayed as plaintext. It's not a link. Ok.
But the imported item in Friendica is showing the mention as Link to Twitter: `https://twitter.com/user%40friendica.node`

### Steps to reproduce the problem
https://twitter.com/alfred_sk/status/1241649917967376384
https://libranet.de/display/0b6b25a8-865e-772a-3e19-9eb970292902

### Friendica version you encountered the problem
2020.03-rc

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
