### ISSUE TITLE
Cannot post public

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#8449]
### Expected behavior

Having the possibility to post something with the public audience.

### Actual behavior

I've set a default contact group as receiver for my postings. When I select "Public" in the ACL (using the vier theme) the default selection is greyed out. But when hitting the send button, the posting is shared only with the default selected group.

The same happens when I erase the selected group from the ACL.

When other groups are selected, those get the posting as expected.

### Steps to reproduce the problem

* set default permissions to a group
* create a new posting, making it public
* hit the share button

### Friendica version you encountered the problem

2020.03-rc

**Comment by AlfredSK** [comment]
I can confirm that for frio.

**Comment by atasingorneq** [comment]
Same Problem here.

**Comment by MrPetovan** [comment]
Fixed by #8450

**Comment by MrPetovan** [comment]
Can you please try again on the latest RC?

**Comment by tobiasd** [comment]
Thanks, looks working
