### ISSUE TITLE
Big emojis when they are the only thing in a post/comment

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8458]
### Expected behavior
When emojis are the only content in a post (unlikely) or comment they should be displayed big. 
# 🤩

### Actual behavior
Sometimes they are so tiny that they're hardly recognizable.

🤩

### Friendica version you encountered the problem
2020.03

### Friendica source (git, zip)
git

**Comment by MrPetovan** [comment]
So you'd like Friendica to behave like instant messaging app? I'd rather implement emoji reactions than accepting the idea of comments including only emojis. 😬

**Comment by AlfredSK** [comment]
Well, people do it because they're used to it. I would like to see this "content" better presented. And implemented emoji reactions are not very popular in our community.  😱

**Comment by annando** [comment]
:nerd_face:

**Comment by SpencerDub** [comment]
I'll be the dark horse here and say I like the idea of *both* larger default size for emoji-only posts *and* emoji reactions. 😜

**Comment by AlfredSK** [comment]
Hmm. I added this line to my config file:
`'big_emojis' => true,`

But it doesn't seem to work as expected.

![IMG_20200517_222718](https://user-images.githubusercontent.com/3656054/82159391-0717ce00-988e-11ea-89af-1b53ba6189da.png)

**Comment by annando** [comment]
I just send a test.
