### ISSUE TITLE
Error message during database update to 2020.03

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8476]
I just received this mail from the system. The update of the "conversation" table is still in progress. Should I be worried?

> Die Friendica-Entwickler haben vor kurzem das Update 1338  veröffentlicht, aber bei der Installation ging etwas schrecklich schief.  Das Problem sollte so schnell wie möglich gelöst werden, aber ich  schaffe es nicht alleine. Bitte kontaktiere einen Friendica-Entwickler,  falls du mir nicht alleine helfen kannst. Meine Datenbank könnte  ungültig sein.
> --
> Die Fehlermeldung lautetFehler beim Ändern der Datenbank  aufgetretenALTER IGNORE TABLE `conversation` ADD `direction` tinyint  unsigned NOT NULL DEFAULT 0 COMMENT 'How the message arrived here:  1=push, 2=pull'; <br />
> danke
> der Administrator von Friendica 🌐
>

**Comment by copiis** [comment]
Meanwhile I get several error messages per minute.

**Comment by MrPetovan** [comment]
> Incorrect key file for table 'conversation'; try to repair it

Please try to perform manually ``REPAIR TABLE `conversation`;``

**Comment by copiis** [comment]
`REPAIR TABLE `conversation`;` went through without any problems

I still get this in the admin area

`The database update failed. Please run 'php bin / console.php dbstructure update' in the command line and watch for any error messages that may appear. The last update failed. Please run "php bin / console.php dbstructure update" on the command line and take a look at any errors that may occur. (Additional information about errors could be found in the log files.)`

**Comment by MrPetovan** [comment]
What happens when you run the console command again?

**Comment by copiis** [comment]
I get the same output

```
Fehler 1034 beim Update der Datenbank aufgetreten
Incorrect key file for table 'conversation'; try to repair it
Fehler beim Ändern der Datenbank aufgetretenALTER IGNORE TABLE `conversation` ADD `direction` tinyint unsigned NOT NULL DEFAULT 0 COMMENT 'How the message arrived here: 1=push, 2=pull'; <br />

```

**Comment by fatalerrors80** [comment]
Exactly the same problem here. Instance works but all profile pictures are gone. Mariadb detects no problem in table :

> friendica.2fa_app_specific_password                OK
friendica.2fa_recovery_codes                       OK
friendica.addon                                    OK
friendica.apcontact                                OK
friendica.attach                                   OK
friendica.auth_codes                               OK
friendica.cache                                    OK
friendica.challenge                                OK
friendica.clients                                  OK
friendica.config                                   OK
friendica.contact                                  OK
friendica.contact-relation                         OK
friendica.conv                                     OK
friendica.conversation                             OK
friendica.diaspora-interaction                     OK
friendica.event                                    OK
friendica.fcontact                                 OK
friendica.fsuggest                                 OK
friendica.gcign                                    OK
friendica.gcontact                                 OK
friendica.gfollower                                OK
friendica.glink                                    OK
friendica.group                                    OK
friendica.group_member                             OK
friendica.gserver                                  OK
friendica.gserver-tag                              OK
friendica.hook                                     OK
friendica.inbox-status                             OK
friendica.intro                                    OK
friendica.item                                     OK
friendica.item-activity                            OK
friendica.item-content                             OK
friendica.item-delivery-data                       OK
friendica.item-uri                                 OK
friendica.locks                                    OK
friendica.mail                                     OK
friendica.mailacct                                 OK
friendica.manage                                   OK
friendica.notify                                   OK
friendica.notify-threads                           OK
friendica.oembed                                   OK
friendica.openwebauth-token                        OK
friendica.parsed_url                               OK
friendica.participation                            OK
friendica.pconfig                                  OK
friendica.permissionset                            OK
friendica.photo                                    OK
friendica.poll                                     OK
friendica.poll_result                              OK
friendica.process                                  OK
friendica.profile                                  OK
friendica.profile_check                            OK
friendica.profile_field                            OK
friendica.push_subscriber                          OK
friendica.queue                                    OK
friendica.register                                 OK
friendica.search                                   OK
friendica.session                                  OK
friendica.sign                                     OK
friendica.storage                                  OK
friendica.term                                     OK
friendica.thread                                   OK
friendica.tokens                                   OK
friendica.user                                     OK
friendica.user-contact                             OK
friendica.user-item                                OK
friendica.userd                                    OK
friendica.worker-ipc
note     : The storage engine for the table doesn't support check
friendica.workerqueue                              OK

**Comment by fatalerrors80** [comment]
> REPAIR TABLE `conversation`;
phpMyAdmin answers :
This kind of table doesn't support repair.

**Comment by fatalerrors80** [comment]
> > REPAIR TABLE `conversation`;
> > phpMyAdmin answers :
> > This kind of table doesn't support repair.

In Mariadb console :
| friendica.conversation | repair | note     | The storage engine for the table doesn't support repair |

**Comment by AlfredSK** [comment]
Btw. the same error is thrown when your $tmpdir has not enough free space left during ALTER TABLE.

**Comment by annando** [comment]
@copiis have you searched the web for this error message? This message is generated by the SQL server, so it had to be repaired with some SQL magic.

**Comment by annando** [comment]
@fatalerrors80 Do you also get the message "Incorrect key file for table"? If not, then your problems are caused by something else and don't belong to this ticket.

**Comment by copiis** [comment]
I deleted the database tables and imported a previously made backup in the hope that the newly created mysam tables would make the error message disappear. Unfortunately it did not eradicate the error message. I'm a bit baffled now and would be grateful for a little nudge in the right direction.

**Comment by copiis** [comment]
Would it help to clear the table?

**Comment by annando** [comment]
I wouldn't recommend to delete any data. Have you searched for possible solutions to this problem in the internet?
