### ISSUE TITLE
When uploading photo via API 404 happens

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8477]
### Expected behavior

I use the following piece of code to upload photos:
`r = requests.post('https://friends.deko.cloud/api/friendica/photo/create.json', files=myfile, data={'album':'Temp'}, auth=HTTPBasicAuth(usr, pss))`

Before 2020.03 it worked, returning json with status code 200, photo id, etc.

### Actual behavior

After the update to 2020.03 it returns:
`{'status': {'error': 'Photo-related item not found.', 'code': '404 Not Found', 'request': 'api/friendica/photo/create.json?'}}`

But photo does get uploaded to the album.

### Friendica version you encountered the problem
2020.03

### Friendica source (git, zip)
git

### PHP version
7.4.4

### SQL version
MariaDB 10.3

**Comment by SpcCw** [comment]
Possibly related to this commit?
dde2cf6ac0cef2a51c149774e810d8a1151846d4

**Comment by MrPetovan** [comment]
It is likely, thanks for looking into it.

**Comment by MrPetovan** [comment]
So, the workflow is as follow:
- with these parameters `api_fr_photo_create_update()` is in `$mode == 'create'` and calls `save_media_to_database()` without a `photo_id` and `$mediatype == 'photo'`.
- Without `photo_id`, `save_media_to_database()` is supposed to call `post_photo_item()` in `include/api.php:4845`. This is supposed to create the "photo-related item" that the error is referring to.
- Then in `include/api.php:4848`, `prepare_photo_data()` expects the photo-related item to be present.

Investigation axes:
- Check `post_photo_item()` is actually called.
- Check the existence of a photo-related item for the resource id of the latest photo you uploaded via the API. `post_photo_item()` doesn't check the return value of `Item::insert` so it's possible it's failing silently for whatever reason.

**Comment by copiis** [comment]
Is this problem solved in the Develop version?

**Comment by MrPetovan** [comment]
Not yet.

**Comment by copiis** [comment]
Can it be that the error also occurs when trying to share an article with an image out of an app?

**Comment by MrPetovan** [comment]
I'm not sure about it.

**Comment by SpcCw** [comment]
In case someone is struggling with this - it is possible to use `api/media/upload` as a workaround until this gets fixed.

There are some differences:
- photos always get uploaded to Wall Photos album
- photos get "Only Yourself" permission until post is made
- this API function doesn't return photo-id so it has to be extracted somehow (e.g from photo URL which is returned)

**Comment by MrPetovan** [comment]
Well, I found the culprit, but I'm not sure of the way going forward. Using `Item::selectFirstForUser` in `prepare_photo_data()` generate the following request:
```sql
SELECT `item`.`id`, `item`.`uri-id` AS `internal-uri-id`, `item`.`uid` AS `internal-uid`, `item`.`network` AS `internal-network`, `item`.`psid` AS `internal-psid`
FROM `item`
STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id`
    AND NOT `contact`.`blocked`
    AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3)))
        OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0)
STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked`
STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked`
LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 43
LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 43
LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 43
WHERE (`item`.`resource-id` = '15294775905ef27e1b5a666587297410' AND `item`.`type` = 'photo')
AND `item`.`visible`
AND NOT `item`.`deleted`
AND NOT `item`.`moderated`
AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`)
AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`)
AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0)
AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`)                                                                                                                           AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0)  LIMIT 1
```
The problem is that the `item` record created before with the correct `resource-id` and `type` has its `visible` field set to `0` which excludes it from this query.

Three solutions:
1. Change the `visible` field value to `1` for photo item record. I don't know what would be the side-effects.
2. Use a different item retrieval function that doesn't imply `visible = 1`. I don't know what would be the side-effects.
3. Remove the implicit `visible = 1` condition from `Item::selectFirstForUser` to make it explicit. There are 20 other uses of this method that would need to add an explicit condition on `visible`. This is the most targeted change with the least side-effects I can think of .

Without @annando 's guidance, I'd go for 3.

**Comment by annando** [comment]
I don't like any of these solutions :-) This invisible items are used as some kind of frame for uploaded pictures. So I guess that there would be side effects. Without having looked into the code, I guess that the solution with the lowest impact is to use `Item::selectFirst` instead in this specific code.

**Comment by MrPetovan** [comment]
Okay, thanks for the feedback.
