### ISSUE TITLE
Multiple database error while upgrading Friendica do 2020.03

### ISSUE THREAD

**Issue by fatalerrors80** [friendica/friendica#8478]
When running "sudo -u www-data ./bin/console dbstructure update":
```
ALTER IGNORE TABLE `gcontact` ADD `last_discovery` datetime DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of the last contact discovery', MODIFY `gender` varchar(32) NOT NULL DEFAULT '' COMMENT 'Deprecated'; 
```

Error 1118 occurred during database update:
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```
ALTER IGNORE TABLE `photo` ADD `accessible` boolean NOT NULL DEFAULT '0' COMMENT 'Make photo publicly accessible, ignoring permissions'; 
```

Error 1118 occurred during database update:
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Errors encountered performing database changes: 
```
ALTER IGNORE TABLE `gcontact` ADD `last_discovery` datetime DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of the last contact discovery', MODIFY `gender` varchar(32) NOT NULL DEFAULT '' COMMENT 'Deprecated';
```
Errors encountered performing database changes:
```
ALTER IGNORE TABLE `photo` ADD `accessible` boolean NOT NULL DEFAULT '0' COMMENT 'Make photo publicly accessible, ignoring permissions';
```
### SQL version MariaDB 10.3.22-MariaDB

The result is Friendica working but no profile pictures. I did not test everything.

Possibly linked with issue #8476

**Comment by MrPetovan** [comment]
For the row size too large errors, you have to convert your tables to the Barracuda format: https://mariadb.com/kb/en/how-to-change-innodb-fileformat-to-barracuda/

**Comment by Quix0r** [comment]
A `SHOW VARIABLES LIKE 'innodb_file_%'` gives me:
````
innodb_file_format | Barracuda
innodb_file_format_check | ON
innodb_file_format_max | Antelope
innodb_file_per_table | ON
````
And runs with no errors on database update. 0cd4e79cfdad3af393c611239a689d4f7bf30c54 is current commit id.

**Comment by fatalerrors80** [comment]
> For the row size too large errors, you have to convert your tables to the Barracuda format: https://mariadb.com/kb/en/how-to-change-innodb-fileformat-to-barracuda/

I tryed that conversion without success :
`MariaDB` [INFORMATION_SCHEMA]> SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE TABLE_SCHEMA = "friendica";
+-------------------------------------------------------------------------+
| MySQLCMD                                                                |
+-------------------------------------------------------------------------+
| ALTER TABLE `friendica`.`openwebauth-token` ROW_FORMAT=DYNAMIC;         |
| ALTER TABLE `friendica`.`gserver` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`queue` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`poll` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`register` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`gcign` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`profile_check` ROW_FORMAT=DYNAMIC;             |
| ALTER TABLE `friendica`.`gfollower` ROW_FORMAT=DYNAMIC;                 |
| ALTER TABLE `friendica`.`term` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`item-activity` ROW_FORMAT=DYNAMIC;             |
| ALTER TABLE `friendica`.`config` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`contact-relation` ROW_FORMAT=DYNAMIC;          |
| ALTER TABLE `friendica`.`push_subscriber` ROW_FORMAT=DYNAMIC;           |
| ALTER TABLE `friendica`.`gserver-tag` ROW_FORMAT=DYNAMIC;               |
| ALTER TABLE `friendica`.`2fa_recovery_codes` ROW_FORMAT=DYNAMIC;        |
| ALTER TABLE `friendica`.`conv` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`process` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`storage` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`auth_codes` ROW_FORMAT=DYNAMIC;                |
| ALTER TABLE `friendica`.`poll_result` ROW_FORMAT=DYNAMIC;               |
| ALTER TABLE `friendica`.`participation` ROW_FORMAT=DYNAMIC;             |
| ALTER TABLE `friendica`.`userd` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`fcontact` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`thread` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`event` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`item-content` ROW_FORMAT=DYNAMIC;              |
| ALTER TABLE `friendica`.`user` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`apcontact` ROW_FORMAT=DYNAMIC;                 |
| ALTER TABLE `friendica`.`gcontact` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`user-item` ROW_FORMAT=DYNAMIC;                 |
| ALTER TABLE `friendica`.`group_member` ROW_FORMAT=DYNAMIC;              |
| ALTER TABLE `friendica`.`glink` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`permissionset` ROW_FORMAT=DYNAMIC;             |
| ALTER TABLE `friendica`.`mailacct` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`cache` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`notify` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`item-uri` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`hook` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`item-delivery-data` ROW_FORMAT=DYNAMIC;        |
| ALTER TABLE `friendica`.`attach` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`inbox-status` ROW_FORMAT=DYNAMIC;              |
| ALTER TABLE `friendica`.`item` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`mail` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`2fa_app_specific_password` ROW_FORMAT=DYNAMIC; |
| ALTER TABLE `friendica`.`profile_field` ROW_FORMAT=DYNAMIC;             |
| ALTER TABLE `friendica`.`search` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`fsuggest` ROW_FORMAT=DYNAMIC;                  |
| ALTER TABLE `friendica`.`oembed` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`photo` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`workerqueue` ROW_FORMAT=DYNAMIC;               |
| ALTER TABLE `friendica`.`challenge` ROW_FORMAT=DYNAMIC;                 |
| ALTER TABLE `friendica`.`session` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`worker-ipc` ROW_FORMAT=DYNAMIC;                |
| ALTER TABLE `friendica`.`user-contact` ROW_FORMAT=DYNAMIC;              |
| ALTER TABLE `friendica`.`profile` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`diaspora-interaction` ROW_FORMAT=DYNAMIC;      |
| ALTER TABLE `friendica`.`manage` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`tokens` ROW_FORMAT=DYNAMIC;                    |
| ALTER TABLE `friendica`.`locks` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`sign` ROW_FORMAT=DYNAMIC;                      |
| ALTER TABLE `friendica`.`notify-threads` ROW_FORMAT=DYNAMIC;            |
| ALTER TABLE `friendica`.`addon` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`conversation` ROW_FORMAT=DYNAMIC;              |
| ALTER TABLE `friendica`.`group` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`pconfig` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`parsed_url` ROW_FORMAT=DYNAMIC;                |
| ALTER TABLE `friendica`.`intro` ROW_FORMAT=DYNAMIC;                     |
| ALTER TABLE `friendica`.`contact` ROW_FORMAT=DYNAMIC;                   |
| ALTER TABLE `friendica`.`clients` ROW_FORMAT=DYNAMIC;                   |
+-------------------------------------------------------------------------+
69 rows in set (0.000 sec)`

**Comment by fatalerrors80** [comment]
> SHOW VARIABLES LIKE 'innodb_file_%'

`MariaDB [friendica]> SHOW VARIABLES LIKE 'innodb_file_%';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_file_format    |       |
| innodb_file_per_table | ON    |
+-----------------------+-------+
2 rows in set (0.001 sec)
`
I guess the unset raw could be a problem. But trying to change it tells me that value is read only.

**Comment by MrPetovan** [comment]
You would have to change the value in your MariaDB configuration files. On my Devuan (Debian-like), this file is `/etc/mysql/mariadb.conf.d/50-server.cnf`

**Comment by annando** [comment]
You have to execute these `ALTER TABLE` commands by hand that you printed out above. This command only displays the SQL commands you need to execute to change the file format.

**Comment by fatalerrors80** [comment]
> You would have to change the value in your MariaDB configuration files. On my Devuan (Debian-like), this file is `/etc/mysql/mariadb.conf.d/50-server.cnf`

After making that change, I fixed the databaqse using those commands :
```
ALTER TABLE photo ROW_FORMAT=Dynamic;
ALTER TABLE gcontact ROW_FORMAT=Dynamic;
```

Then run sudo -u www-data ./bin/console dbstructure update again.

Do you think I should convert all the other tables?
If yes any command to treat them all instead of doing this table after table?

Thanks.

**Comment by annando** [comment]
Just do it line by line.

**Comment by fatalerrors80** [comment]
All lines converted, no more issue.

I suggest the updater explain that conversion process.

Thank you all !

**Comment by annando** [comment]
We could add some check (and convert) mechanism like we have with MyISAM.

**Comment by MrPetovan** [comment]
What about the server configuration, is it needed?

**Comment by annando** [comment]
The server configuration is needed as a default for new tables. But existing tables need to be transformed manually.

**Comment by MrPetovan** [comment]
Ok, I was wondering if the setting was necessary for existing tables to be converted.
