### ISSUE TITLE
Normalize settings page display

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8482]
Offshoot of #8480

Settings pages are looking inconsistent, header hierarchy is out of wack, frio doesn't have a themed page for additional features.

**Comment by annando** [comment]
From an accessibility pint of view there shouldn't be gaps in the header hierarchy.

**Comment by MrPetovan** [comment]
Indeed. However there seem to be a confusion regarding the `section_title.tpl` template that is a `h2` and is used for page titles that should be `h1`, at least in vier and frio.

**Comment by MrPetovan** [comment]
Closed by #8486
