### ISSUE TITLE
Mobile frio theme: Right navmenu covers its hamburger button and thus prevents closing menu

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8485]
### Expected behavior
When touching the right hamburger button, the menu that opens should be located such that it allows to click the hamburger button again to close the menu.

### Actual behavior
When touching the right hamburger button, the appearing menu covers the button such that it can't be interacted with again. On a mobile device it can be then tricky to close the menu at all.

![Screenshot_20200401-214753](https://user-images.githubusercontent.com/2605261/78180152-a3af1980-7462-11ea-955c-276466aa995f.png)

### Steps to reproduce the problem
1. Touch the right hamburger menu

### Friendica version you encountered the problem
Develop branch; commit 248a7fa48a161aedf619dd9a36718775c9a2677f

**Comment by wiwie** [comment]
I believe the issue originates from the offcanvas class from the jasny bootstrap library. It works fine for the left hamburger menu and there the same class. I haven't looked into more details.

To mimick the same behaviour as for the left hamburger menu a quick workaround for me is adding the following css to the frio style.css:

```
#myNavmenu {
    top: 90px;
}
```
This places the menu under the second topbar. Not sure though, whether this is a clean way of solving it.

**Comment by AlfredSK** [comment]
Just tap on a free space outside of the menu.

**Comment by MrPetovan** [comment]
Out of scope, but I don't recognize the "Show 1 post filtered by the rule /corona|CORONA/", is it an addon you are working on?

**Comment by wiwie** [comment]
@MrPetovan well it's not an add-on yet but it could turn into one if the general idea works. I was playing with the idea to aggregate multiple filtered posts masked by the same pattern together into a more compact representation, such that my timeline wasn't filled up with post "husks" that contain only content warnings. It is semi-functional but I'm not entirely convinced of my current approach..

**Comment by wiwie** [comment]
@AlfredSK well yes that is a workaround and works most of the time. But there were cases where I had opened both menus at the same time and it got ugly with getting this one away without having the left menu closed as well. In that case a properly positioned menu would be the correct solution I guess.

**Comment by MrPetovan** [comment]
I agree with @wiwie , the workaround worked well enough in most cases but it still is a workaround.

**Comment by wiwie** [comment]
Can anyone comment on my suggested fix via the addition of the above css? It seems not like the most elegant way to me and that there must be a better way. Anyone any ideas? If not I would create a PR with the above.

**Comment by MrPetovan** [comment]
Why isn't it elegant? How does it look in non-mobile with the same declaration?

**Comment by wiwie** [comment]
It's because I found that setting top: 90px would lead to a cutoff of the bottom of the menu with my phone screen size. So I'm actually using top: 50px; now on my instance.

Also, I got that impression that this was a hacky fix because it seems to work fine with the offcanvas class with the left hamburger menu, I believe without this workaround?

**Comment by AlfredSK** [comment]
> I agree with @wiwie , the workaround worked well enough in most cases but it still is a workaround.

Is it? I checked other mobile versions of software like Discourse. The main (right side) menu behaves exactly like frio's main menu. You have to tap outside the menu to close it.

But don't get me wrong. When you find an elegant (non-hacky) way to improve it I'll be happy. :-)

**Comment by wiwie** [comment]
> > I agree with @wiwie , the workaround worked well enough in most cases but it still is a workaround.
> 
> Is it? I checked other mobile versions of software like Discourse. The main (right side) menu behaves exactly like frio's main menu. You have to tap outside the menu to close it.
> 
> But don't get me wrong. When you find an elegant (non-hacky) way to improve it I'll be happy. :-)

Do these other pages also have two menus that can potentially overlap each other/ cover the whole screen such that closing one menu is only possible by tapping on the other menu, thereby activating (non desired) some menu item?

Simple use case: open the left menu, open the right menu, see how the whole screen is covered.

If this is the desired behaviour to close the right menu, the page needs to either (1) prevent that a close action by tapping outside activates some other menu item (Probably that could be possible by adding some kind of overlay?), Or (2) prevent that both menus can be opened at the same time/automatically closing the other menu.

How is for instance discourse solving this scenario?

**Comment by tobiasd** [comment]
Can opening the one menu trigger the signal to close the other?

**Comment by AlfredSK** [comment]
Maybe the simplest method is to add an icon/button that is closing the menu.

Here is a humble mockup:


![Screenshot_20200410-202936](https://user-images.githubusercontent.com/3656054/79014672-afd65d80-7b6b-11ea-8865-63df68bb902a.png)

**Comment by wiwie** [comment]
@AlfredSK why would you rather insert am additional closing button into the menu, than positioning the menu such that one can click on the hamburger menu to close the menu?

**Comment by AlfredSK** [comment]
Because with the latter you're losing vertical space. That's the main reason.

Also, covering the three dots when opening the menu is a common design principle. We shouldn't break that. I already mentioned Discourse. It's the same with mobile browsers. The main menu covers the three dots e.g. in Firefox and Chrome. We shouldn't introduce a completed different workflow.

I think a small icon is the least disruptive way to cover your egde case issue without breaking the the design principle and without losing vertical space.

**Comment by AlfredSK** [comment]
Maybe when we use the design of the desktop main menu on mobile as well... At least it looks better. But I don't know how good this works with very small displays.

![main-menu](https://user-images.githubusercontent.com/3656054/79019856-88858d80-7b77-11ea-8a95-bc466abd8e82.png)

**Comment by wiwie** [comment]
@AlfredSK ok, makes sense. I just don't think the closing cross is particularly pretty. Then I'd rather vote for a more subtle approach where the menus cannot be opened at the same time or where one closes the other when opened.

**Comment by vinzv** [comment]
> Maybe when we use the design of the desktop main menu on mobile as well... At least it looks better. But I don't know how good this works with very small displays.

While it looks good the menu points would be really hard to hit. To solve the initial problem I'd stick with @wiwie's hack:
```
#myNavmenu {
    top: 90px;
}
```
