### ISSUE TITLE
Relax HTTP policies for public ActivityPub endpoints

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8489]
From this conversation: https://friendica.mrpetovan.com/display/d772ceb0575f0138cb5a0242ac180002

## Relax CORS restrictions for public GET requests

> There’s no sense have CORS restrictions on GET requests for publicly-shared ActivityPub objects (like your actor). Other HTTP verbs, sure. That’s how other services work. `Access-Control-Allow-Origin: *` is good, and it’s what you use for things like your profile pic.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

## Relax cache directives for public GET requests

> Yeah, actually. It would be nice if those same object had better `Cache-Control` as well, so that browsers/applications could cache the results, at least for a time. Right now it's set to, `no-store, no-cache, must-revalidate`, which while super-conservative, is probably just less efficient than it could be. Setting a reasonable static value (like a day or two) and/or sending an `Etag` would be better.

References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by MrPetovan** [comment]
@annando can you please confirm the `changed` field in the `item` table is an accurate cache key for a single item display like the `/object` endpoint? I'm trying to get the necessary info to create a meaningful ETag.

**Comment by annando** [comment]
Well, I guess so.

**Comment by MrPetovan** [comment]
Ok thanks.
