### ISSUE TITLE
Authentication via API verify_credentials.json fails with error 500

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8493]
I'm using external user authentication for my Prosody XMPP server. The authentication fails from time to time. So I had a deeper look what might be the problem.

### Expected behavior
When `authentication = "http_async";` is enabled in Prosody config with `http_auth_url = "https://libranet.de/api/account/verify_credentials.json";` a user is able to use XMPP chat with their Friendica credentials.
The return value of `.../api/account/verify_credentials.json` should be something between 200 and 299 to be successfully authenticated.

### Actual behavior
The weird thing is it works for days or even weeks. But then all of a sudden I get an error when I try to login in Gajim (Linux) or Conversations (Android). Also, when I try to authenticate directly on the webpage 'https://libranet.de/api/account/verify_credentials.json' - with my Friendica login data - I get an error 500 too.

I checked the Prosody config. It seems to be ok. Also, the error 500 appears directly on the API login page too. So, I think this isn't related to Prosody at all.

Even weirder: Sometimes the issue seems to resolve itself after some hours.

**Any Idea why I get an error 500 when I try to authenticate via API verify_credentials.json?**

### Debug log Prosody:
```
Apr 04 07:13:48 c2s559a064c2930 debug   Client sent opening <stream:stream> to libranet.de
Apr 04 07:13:48 c2s559a064c2930 debug   Sending[c2s_unauthed]: <?xml version='1.0'?>
Apr 04 07:13:48 c2s559a064c2930 debug   Sending[c2s_unauthed]: <stream:stream xml:lang='en' id='63dc2692-ab48-48e5-b842-299e7db9b3cd' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0' from='libranet.de'>
Apr 04 07:13:48 c2s559a064c2930 debug   Sent reply <stream:stream> to client
Apr 04 07:13:48 c2s559a064c2930 info    Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Apr 04 07:13:48 c2s559a064c2930 debug   Offering mechanism PLAIN
Apr 04 07:13:48 c2s559a064c2930 debug   Sending[c2s_unauthed]: <stream:features>
Apr 04 07:13:48 c2s559a064c2930 debug   Received[c2s_unauthed]: <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>
Apr 04 07:13:48 libranet.de:auth_http_async     debug   Testing password for user alfred at host libranet.de with URL https://libranet.de/api/account/verify_credentials.json
Apr 04 07:13:48 libranet.de:auth_http_async     debug   sync_http_auth()
Apr 04 07:13:48 libranet.de:auth_http_async     debug   HTTP auth provider returned status code: 500
Apr 04 07:13:48 libranet.de:saslauth    debug   sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text>Unable to authorize you with the authentication credentials you&apos;ve sent.</text></failure>
Apr 04 07:13:48 c2s559a064c2930 debug   Sending[c2s_unauthed]: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Apr 04 07:13:48 socket  debug   connection failed in read event: closed 
Apr 04 07:13:48 socket  debug   closing client with id: 559a064c1e90 closed 
Apr 04 07:13:48 c2s559a064c2930 info    Client disconnected: closed
Apr 04 07:13:48 c2s559a064c2930 debug   Destroying session for (unknown) ((unknown)@libranet.de): closed
```

### PHP error log:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Protocol\Activity::match() must be of the type string, null given, called in /var/www/html/libranet/include/conversation.php on line 158 and defined in /var/www/html/libranet/src/Protocol/Activity.php:218
Stack trace:
#0 /var/www/html/libranet/include/conversation.php(158): Friendica\Protocol\Activity->match(NULL, 'http://activity...')
#1 /var/www/html/libranet/include/api.php(2980): localize_item(Array)
#2 /var/www/html/libranet/include/api.php(965): api_format_item(Array, 'json')
#3 /var/www/html/libranet/include/api.php(340): api_account_verify_credentials('json')
#4 /var/www/html/libranet/mod/api.php(132): api_call(Object(Friendica\App))
#5 /var/www/html/libranet/src/LegacyModule.php(90): api_content(Object(Friendica\App))
#6 /var/www/html/libranet/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction('content', Array)
#7 [internal function]: Friendica\LegacyModule::content(Array)
#8 /var/www/html/libranet/src/App/Page.php(332): call_user_fu in /var/www/html/libranet/src/Protocol/Activity.php on line 218
```

### Steps to reproduce the problem
I really don't know.

### Friendica version you encountered the problem
2020.03

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
I found a workaround...

When I change line 218 in .../src/Protocol/Activity.php from...

`public function match(string $haystack, string $needle)`

to...

`public function match($haystack, string $needle)`

it works again. But removing the type hint isn't a real solution to the problem, I guess.

**Comment by MrPetovan** [comment]
No, it isn't a solution. Thanks for the trace, it's a massive help.

**Comment by MrPetovan** [comment]
So, I've been able to track the technical reason of this issue. `Friendica\Protocol\Activity::match()` takes a item verb as a first argument. `verb` used to be a column in the `item` table but has been deprecated. Instead, it is now generated from the `activity` column of the `item-activity` table. Problem is, not all `item` rows have a related `item-activity` row, which results in the virtual field `row` to be `NULL`.

So far, I've been unable to determine a pattern among the `item` rows that are missing a corresponding `item-activity` row.

Help me @annando, you're my only hope

**Comment by AlfredSK** [comment]
Thanks and may the Force be with you!

**Comment by annando** [comment]
@MrPetovan sorry, but you are looking weird in that princess dress. :grimacing:

**Comment by MrPetovan** [comment]
Can you please pull the latest develop and test again?

**Comment by AlfredSK** [comment]
I can. I've been on master long enough.  😉

**Comment by AlfredSK** [comment]
Switched to develop. Tested login with Gajim and Conversations successfully. No error 500.  🎉
Since the problem occurred infrequently, I will keep an eye on it.

**Comment by casperrutten** [comment]
I've been on this problem too.
After I prefixed the url with ../verify_credentials.json**?skip_status=true** it worked.
It skips line 962-967 in api.php.
Hope this helps, but like @AlfredSK said, it occurs infrequently
tested on 2020.03

**Comment by Quix0r** [comment]
Here https://f.haeder.net/api/account/verify_credentials.json asks for a password but ends with an error, see: https://f.haeder.net/verify_credentials.txt for details (2 attempts).

**Comment by Quix0r** [comment]
>It looks like that mod_auth_http_aysync is still in alpha stage so I had manually download it from the source code repository. The "no response" is now gone. I get a "wrong password" in Dino. So the connection between #prosody and #Friendica actually works! But now it is Friendica (see above logfile).

Quoted from [here](https://f.haeder.net/display/adbba6c6-1060-bfb3-9074-32a596620129).

**Comment by Quix0r** [comment]
Here is a `grep "auth" prosody.log`: https://f.haeder.net/auth.txt

**Comment by AlfredSK** [comment]
You can use a browser to directly test the login at https://f.haeder.net/api/account/verify_credentials.json

If that is working the issue is probably on the Prosody (config) side.

**Comment by Quix0r** [comment]
@AlfredSK If I try to authenticate with proper login data, the prompt comes up all over again. Please also look into https://f.haeder.net/verify_credentials.txt

**Comment by AlfredSK** [comment]
Do you use 2FA?

That log looks weird. Why is your systems PATH variable content in there? If the login fails you should get a message. 

Are you using some proxy or something like that? Maybe there is the source of the issue.

I'm pretty sure your config is wrong at some point.

**Comment by Quix0r** [comment]
Yes, that's enabled. Does this affect it? That would be very sad.

**Comment by Quix0r** [comment]
I think `/include/api.php` tries OAuth? `$third_party` there is set to `true`. So 2FA should be bypassed.

`SELECT * FROM `pconfig` WHERE `cat` = '2fa'` returns 2 records, where `verified` is set to `1` and `secret` is set, too.

**Comment by Quix0r** [comment]
I think I have a solution:
`if ($third_party && DI::pConfig()->get($user['uid'], '2fa', 'verified')) {` needs to be moved right before the final `else` block. So APIs still have a chance to verify login (since there is no 2FA possible in JSON calls) before the application-specific password is checked? What if no record exists in `2fa_app_specific_password` like it is here the case?

Edit: Or is `$third_party` here correctly checked but `/include/api.php` somehow misuses it?

**Comment by Quix0r** [comment]
Let's not abuse this ticket, the 500 error is fixed but a new logic error seem to have arisen when 2FA is enabled. Please lock this issue!

**Comment by AlfredSK** [comment]
The verify credentials json path is using basic auth. So username + password. If you're using 2FA you need to create an app token in your 2FA settings and use the token instead of your normal password.

**Comment by Quix0r** [comment]
And then I really don't need those change I introduced? It isn't maybe obvious to a regular user (wasn't even to me). This needs more documentation and surely some JSON reply when no app-specific password is set.

Yes, it works flawless. But wasn't really obvious. Maybe the JSON should return a proper message like _"You cannot use your normal password and 2FA. Please setup an application-specific password."_ Something like this that makes the user aware of it.

**Comment by MrPetovan** [comment]
A 500 error is never expected, a wrong auth should be replied to with a 403 or 401 error.
