### ISSUE TITLE
Redirect after poking/pinging someone doesn't take place

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#8498]
### Expected behavior
The website redirects to previous page.

### Actual behavior
The website remains after the `GET` (shouldn't it be `POST`?) request finishes. It may allow to press F5 (reload) very often.

### Steps to reproduce the problem
Ping/poke a Friendica account.

### Friendica version you encountered the problem
`develop` at ad68aaae3

### Friendica source (git, zip)
GIT

### PHP version
_Not relevant._

### SQL version
_Not relevant._

**Comment by MrPetovan** [comment]
What theme were you using?
