### ISSUE TITLE
manual dbstructure update not succeeding

### ISSUE THREAD

**Issue by c1ph4** [friendica/friendica#8506]
### Expected behavior
manual dbstructure update should succeed with no errors

### Actual behavior
As the automatic update of my database wasn't successful when updating Friendica from 3.6 to 2020.3 I tried to trigger this manually via "Putty". However this wasn't successful as "Putty" shows those messages after triggering the update:

```
php bin/console.php dbstructure update
ALTER TABLE `pconfig` MODIFY `id` int unsigned NOT NULL auto_increment COMMENT '', MODIFY `uid` mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'User id', MODIFY `cat` varbinary(50) NOT NULL DEFAULT '' COMMENT '', MODIFY `k` varbinary(100) NOT NULL DEFAULT '' COMMENT '', COMMENT = 'personal (per user) configuration storage'; ALTER TABLE `pconfig` MODIFY `v` mediumtext COLLATE utf8mb4_general_ci COMMENT '';

Fehler 1064 beim Update der Datenbank aufgetreten
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `pconfig` MODIFY `v` mediumtext COLLATE utf8mb4_general_ci COMMENT '' at line 1
ALTER TABLE `session` MODIFY `id` bigint unsigned NOT NULL auto_increment COMMENT 'sequential ID', COMMENT = 'web session storage'; ALTER TABLE `session` MODIFY `data` text COLLATE utf8mb4_general_ci COMMENT '';

Fehler 1064 beim Update der Datenbank aufgetreten
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `session` MODIFY `data` text COLLATE utf8mb4_general_ci COMMENT ''' at line 1
Fehler beim Ändern der Datenbank aufgetretenALTER TABLE `pconfig` MODIFY `id` int unsigned NOT NULL auto_increment COMMENT '', MODIFY `uid` mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'User id', MODIFY `cat` varbinary(50) NOT NULL DEFAULT '' COMMENT '', MODIFY `k` varbinary(100) NOT NULL DEFAULT '' COMMENT '', COMMENT = 'personal (per user) configuration storage'; ALTER TABLE `pconfig` MODIFY `v` mediumtext COLLATE utf8mb4_general_ci COMMENT '';<br />
Fehler beim Ändern der Datenbank aufgetretenALTER TABLE `session` MODIFY `id` bigint unsigned NOT NULL auto_increment COMMENT 'sequential ID', COMMENT = 'web session storage'; ALTER TABLE `session` MODIFY `data` text COLLATE utf8mb4_general_ci COMMENT '';
```

### Steps to reproduce the problem
1) update Friendica from 3.6 to 2020.3
2) log in after the maintenance finished and check your admin account
3) notice the error messages, you should trigger the update of the database manually
4) log into "Putty" or some other tool and check for error messages

### Friendica version you encountered the problem
2020.03

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
zip
### PHP version
7.2
### SQL version
5.7.28

**Comment by MrPetovan** [comment]
There seem to be an issue with the semi-colon `;` between statements. Can you please try to run these queries manually in the mysql console via PuTTY?

**Comment by c1ph4** [comment]
Okay, it seems doing the updates one by one via "PHPMyAdmin" did the trick in the end:

> Das Update 1338 der Struktur der Datenbank wurde erfolgreich angewandt.
> Database: 0/0, Network: 0, Rendering: 0, Session: 0, I/O: 0, Other: 0.2, Total: 0.2

Thanks @MrPetovan for the hint!

Closing this ticket now.
