### ISSUE TITLE
connectors settings page blank after adding gnusocial

### ISSUE THREAD

**Issue by adrelanos** [friendica/friendica#8511]
### Expected behavior

Show settings page

### Actual behavior

blank (white) website

### Steps to reproduce the problem

go to https://meld.de/settings/connectors

Consumer key
Consumer secret
Base API URL:https://gnusocial.cc/api/

### Friendica version you encountered the problem

https://meld.de/profile/whonix

**Comment by tobiasd** [comment]
It's working for me (on my Friendica node), so it would be really great if the node admin of meld.de could have a look into the log file after visiting the settings page. Blank page smells like a PHP error, so have a look into that log file first.@copiis.

**Comment by adrelanos** [comment]
You sure your message reached @copiis or got any other way of contact?

**Comment by MrPetovan** [comment]
His public profile is https://meld.de/profile/rick

**Comment by copiis** [comment]
@adrelanos Can you tell me the exact time when it happened so that I can narrow it down?

**Comment by adrelanos** [comment]
I reproduced this right now. Logged in with account `whonix@meld.de` and went to page `https://meld.de/settings/connectors`. Page is empty.

(Feel free to login with my account of that helps. It's a public project account. Therefore nothing to hide. If you need password from me, I can provide it. Or also feel free to change password and I can reset later.)

**Comment by copiis** [comment]
Found something, maybe that's it.

[](PHP Fatal error:  Uncaught TypeError: Argument 2 passed to OAuthRequest::from_consumer_and_token() must be an instance of OAuthToken, null given, called in /friendica/addon/statusnet/library/twitteroauth.php on line 239 and defined in /friendica/library/OAuth1.php:361\nStack trace:\n
#8473 0 /friendica/addon/statusnet/library/twitteroauth.php(239): OAuthRequest::from_consumer_and_token(Object(OAuthConsumer), NULL, 'GET', 'https://gnusoci...', Array)\n
#1 /friendica/addon/statusnet/library/twitteroauth.php(100): TwitterOAuth->oAuthRequest('https://gnusoci...', 'GET', Array)\n
#2 /friendica/addon/statusnet/statusnet.php(325): TwitterOAuth->getRequestToken('oob')\n
#3 /friendica/src/Core/Hook.php(219): statusnet_settings(Object(Friendica\\App), '<span id="setti...')\n
#4 /friendica/src/Core/Hook.php(195): Friendica\\Core\\Hook::callSingle(Object(Friendica\\App), 'connec...', referer: https://github.com/friendica/friendica/issues/8511)

**Comment by MrPetovan** [comment]
Yes, that would be it, thanks.

**Comment by adrelanos** [comment]
Yes. Fixed. Thanks!
