### ISSUE TITLE
Saved Searches - next page broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8514]
### Expected behavior
When I click on a saved search (e.g. #art) in the left side widget I get a stream of items tagged with #art. When I want to get more items I click on the 'Next' button at the bottom of the page. The next page with items should show up.

### Actual behavior
The first page works. But when I click on 'Next' I get a page with no items. This happens with often used tags like #art or #newhere too. So, there should be content but it isn't displayed.

### Steps to reproduce the problem
Follow a hashtag by adding it to the saved searches. Click on that saved search. Try to go to page two.

### Friendica version you encountered the problem 
2020.03
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
The problem is that the next button calls a false URL.

It is like this...
`https://libranet.de/search?q=#art&page=2`

But it should be like this...
`https://libranet.de/search?q=%23art&page=2`

**Comment by AlfredSK** [comment]
I'm not sure. Is it here?

https://github.com/friendica/friendica/blob/0773d26aa87179ef93ae72596913d90a7a5142fd/src/Module/Search/Saved.php#L31-L36

**Comment by MrPetovan** [comment]
No, look at `$_GET['term']`, it's looking for a `term` GET parameter, but it is named `q` in the URLs you pasted before.

**Comment by AlfredSK** [comment]
I'm looking really hard. :-) But I don't get it. The thing is it's working as expected on page 1.
`https://libranet.de/search?q=%23art`

But when I look at the URL of the 'Next Button' it adds the `&page=x` part to the URL but also doesn't encode the `#` in front of the term.

**Comment by SpcCw** [comment]
It is not just saved searches but in other places too, e.g. try searching local directory. Try "linux" as search term and pagination works and it fails in the exactly same way for "#linux". 

I think it has something to do with changes to `src/Content/Pager.php` or upstream.

**Comment by annando** [comment]
There is some pager problem. The solution in PR #8651 is a workaround.

**Comment by AlfredSK** [comment]
### "Next" button missing on saved searches

The PR #8651 did something but the thing is that now there is no next button anymore on the pages of saved searches. The next button doesn't show up at the bottom of the page. So, there is no way to go to the next page now. 

I can manually go to other pages by adding `&page=x` to the end of the URL. But when I do so there is a "previous" button ◀️ but no "next" button ▶️.

**Comment by AlfredSK** [comment]
Hmm. Seems like the PR didn't fix anything. When I manually go to page 3 and I click on "previous"/"newer" I'm still redirected to `.../search?q=#art&page=2` and the page doesn't show any content. When I replace the `#` with `%23` the content shows up.

**Comment by annando** [comment]
The PR should redirect the `search?q=#` to `search?tag=`.

**Comment by AlfredSK** [comment]
Ok. Then the problem is probably the missing "next" button.
