### ISSUE TITLE
Twitter probing should accept mobile twitter URLs (https?://mobile.twitter.com/XXX)

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8517]
Currently, the twitter probing logic works for https?://twitter.com/XXX URLs and XXX@twitter.com handles. I suggest to also allow https?://mobile.twitter.com/XXX URLs.

My use case for this feature often is discovering a twitter account on my mobile browser and then wanting to copy & paste the corresponding https://mobile.twitter.com/XXX URL into the contact search input. Currently, however such links are not accepted. Hence, such links have to be manually edited by removing the "mobile." subdomain.

**Comment by MrPetovan** [comment]
Closed by #8811 and https://github.com/friendica/friendica-addons/pull/992
