### ISSUE TITLE
Friendica & Letsencrypt confusion

### ISSUE THREAD

**Issue by coamtaker618** [friendica/friendica#8521]
I'm having an issue similar to #5660 (Friendica May Be Incompatible With LetsEncrypt ).  I am trying to install Friendica on a self-hosted linux system.  I ran Lets Encrypt (successfully) first and then tried to install Friendica afterwards (the logic being that I could use the proper https settings with a trusted cert on setup--since, you know Friendica asks).

However now I seem to either get server error or infinite loops.  Is there any reference to working Apache conf files & Friendica .htaccess files?  I suspect the confusion is somewhere inbetween the two? And maybe a 3rd point as to whether Friendica should be accessible in /var/www/html (default for apache) or /var/www/friendica (where friendica seems to like to be installed).

As per bug #5660 I've tried various permutations of commenting out rewrite commands in both Apache conf & .htaccess in Friendica.  I also did set .well-known to 777 because then I KNOW it's not a permission issue.

Again, the goal here is "simply" a fresh install of Friendica on a linux host with a LE cert.  If it would be easier to start from scratch, I'd be willing to do that too (since I haven't actually hit a 'working' state yet)--whatever is easiest.

Thanks in advance for any help/provided documentation.

**Comment by tobiasd** [comment]
Hey @coamtaker618 sorry to hear about your problems setting Friendica up with Lets Encrypt for TLS. Most of the Friendica nodes are using LE, so there should be a solution. But as I'm not using Apache for the web-server, I'd rather let other using that combo help with the configuration. However

> And maybe a 3rd point as to whether Friendica should be accessible in /var/www/html (default for apache) or /var/www/friendica (where friendica seems to like to be installed).

you can install Friendica to any directory that is accessible from the web-server. So if you like to have your installation in `/var/www/html` then you can do so.

**Comment by coamtaker618** [comment]
Thanks tobiasd! Briefly scanning over that link it seems like it might be helpful.  I must admit, I did not come across that page before--unfortunately the howto's seem fairly scattered and inconsistant from what I've seen >_> 

What's your setup for Friendica?  I assume there's got to be some sort of webserver and some sort of SSL handling?   I went for apache because that's just what I use for some other stuff and I assumed it would be easier >_>

If there's a better/easier/faster approach, I'm all ears!

**Comment by AlfredSK** [comment]
> I also did set .well-known to 777

How did you do that ? `.well-known` is not an actual file/directory. It's dynamically created by PHP. Don't create such a directory manually. You will run into troubles.

Friendica doesn't need some special/magic settings in the Apache virtual host's conf file - just a normal/default configuration.

Just make sure you have a section like the following in your conf file to allow Friendica's `.htaccess` file to override the general Apache settings. Otherwise the URL rewrite doesn't work.

```
<Directory /path/to/friendica>
        AllowOverride All
</Directory>
```

I use certbot for creating the Let's Encrypt certificate. Nothing fancy here as well.
`certbot certonly --apache -d libranet.de,dir.libranet.de,...`

After the certificate has been created and stored you have to put the correct paths to the `privkey`  and `fullchain` .pem-files into your Apache virtual host's conf file. And that's it.

**Comment by coamtaker618** [comment]
Glad to hear there's no magic sauce!  Hopefully that means this will be easy ;)

Ok, so I deleted the .well-known folder.

I've also got the following in my LE apache config (rewriting myurl but keeping everything else the same):

<VirtualHost *:80>
     ServerAdmin admin@example.com
     DocumentRoot /var/www/friendica
     ServerName myurl.com
     ServerAlias www.myurl.com

     <Directory /var/www/friendica/>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined

RewriteEngine on
RewriteCond %{SERVER_NAME} =myurl.com [OR]
RewriteCond %{SERVER_NAME} =www.myurl.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>


So obviously my files are hosted in "/var/www/friendica/"  but I know Apache doesn't like having the "/var/www/html" file exposed, so how should I manage that? Should I redirect the html folder to that friendica folder?

**Comment by AlfredSK** [comment]
No. Just disable the default conf file with `a2dissite 000-default.conf default-ssl.conf` and reload the Apache service.

Please note that these file names can be different on your system. I'm using Ubuntu. On Debian it should be the same. But I have no idea about other distributions.

Also, why that `www`-rewrite condition? Do you really need that?

**Comment by coamtaker618** [comment]
Thanks AlfredSK.  I'm using Ubuntu Server, so we'll have the same files names :)

friendica-le-ssl.conf is the only enabled file, all other default files are disabled (and apache has been reloaded since).  I can certainly try commenting out portions of the rewrite condition. I was just trying things I found on the interwebz >_>

**Comment by AlfredSK** [comment]
Ok. I post my conf files here. I use virtual host files for each domain/subdomain and I use two files for each of them - one for http (port 80) and one for https (port 443).

**libranet.conf:**
```
<VirtualHost libranet.de:80>
        ServerName libranet.de
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/libranet

        Redirect permanent / https://libranet.de/

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Directory /var/www/html/libranet>
                AllowOverride All
        </Directory>
</VirtualHost>

**friendica-ssl.conf:**
```
<IfModule mod_ssl.c>
               <VirtualHost _default_:443>
                ServerName libranet.de
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/html/libranet

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                SSLEngine on
                SSLCertificateFile /etc/letsencrypt/live/libranet.de/fullchain.pem
                SSLCertificateKeyFile /etc/letsencrypt/live/libranet.de/privkey.pem

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                <Directory /var/www/html/libranet>
                                AllowOverride All
                </Directory>
        </VirtualHost>
</IfModule>
```

I have stripped all comments and all the stuff I added for convenience or security. This is the **needed** stuff.

Also, I use the `html` folder as normal sub-directory - not as a document root because I also have a `/var/www/data` folder for file storage etc.

**Comment by coamtaker618** [comment]
Ok, copying & modifying & pasting now.

But I did want to ask, what do you mean by "Also, I use the html folder as normal sub-directory - not as a document root because I also have a /var/www/data folder for file storage etc."   I get that you use /var/www/data as your data folder (which makes sense)--but does that mean my /var/www/friendica folder is your /var/www/html folder?

**Comment by coamtaker618** [comment]
ignore previous comment.  as soon as I started processing your apache conf file I see what you mean!  Maybe I do the same here to avoid tripping over issues?

**Comment by AlfredSK** [comment]
No. The Friendica files are in /var/www/html/friendica. That's the document root.
That's a special thing I made. You don't have to do it that way. You just have to adjust the paths in the conf files to **your** Friendica directory.

**Comment by coamtaker618** [comment]
Ok, I gave that a shot (used /var/www/friendica isntead of your /var/www/html/friendica).  The "Redirect permanent " certainly works!  I am getting a 404 error though when it tries to redirect to the install page (which I assume is a dynamically created page as well)

www-user owns the entire /var/www/friendica folder at 755, so it should be able to generate it, no?

**Comment by AlfredSK** [comment]
I don't remember what path the install process is using. Sorry. But when I check the code `.../install` seems to be right.
Please double check all the paths in your Apache conf files. Weird things can happen if you have a typo or or wrong path somewhere in these files.

**Comment by coamtaker618** [comment]
AlfedSK, thanks for the reply.  I suspect you are correct because I made a clean install on a fresh VM and it (mostly) worked using only HTTP (this was a proof of installaion, I have no intention of actually deploying HTTP outside my own test network).

As expected, http installed fine.  However it did have a bug on setup as far as I can tell), it seems to hardcode https for the login page.  While I commend the push towards https, and I also look forward to the day this is a moot point as I'm HSTS on this anyway, it does make http installation somewhat silly if you can't login.

**Comment by coamtaker618** [comment]
A much delayed update, but I wanted to let everyone know I have it working!! I remade the VM this is installed in and (following the conf files above) was able to get it to work :)

I'm not 100% sure exactly what happened, but I think I may have logged in using the IP rather than the URL for part of the initial config (since it was local).  Seems like you need to use the URL from the get-go or Friendica identifies itself by the IP, and that doesn't HTTPS very well :p

**Comment by MrPetovan** [comment]
Thanks for the follow-up!

**Comment by coamtaker618** [comment]
@MrPetovan of course!

Sorry for repoening it, I was afraid I did something wrong when I was getting secure SSL errors and insecure page loads.  Ends up as I was moving stuff around I made 2 errors:
1) frendica != friendica
2) I missed one instance of "libranet" despite using a replace all!!!

I'm now 100% HTTPS :)

Thank you all again!
