### ISSUE TITLE
Button "back to top" is not displayed correctly

### ISSUE THREAD

**Issue by Singh-in** [friendica/friendica#8525]
### Expected behavior
The button "back to top" should always appear when scrolling towards the end of the page.

### Actual behavior
The button "back to top" is hidden when scrolling to the end and is shown when scrolling to the beginning. 

### Friendica version you encountered the problem
Version 2020.03 1338 Post-Update-Version 1329.

### Friendica source (git, zip)
git

### PHP version
7.3
### SQL version
10.3.x

**Comment by AlfredSK** [comment]
> The button "back to top" should always appear when scrolling towards the end of the page.

I don't think so. When the button would be displayed while scrolling down it would block elements which are behind the button. That would create a really bad UX.
From my point of view the button behaves perfectly fine.

**Comment by MrPetovan** [comment]
We changed this behavior last release for the reason @AlfredSK said, if we show it when scrolling down it can cover other UI controls even though there's no perceived intention to scroll up because of the scrolling down. When you start to scroll up, we do display this faster alternative after a short while.

**Comment by Singh-in** [comment]
then it was wrong until version 2019.12 and with all other integration I have ever seen. 
Remarkable!

**Comment by MrPetovan** [comment]
We do value user feedback and input but we definitely don't need this kind of sarcastic attitude.

**Comment by Singh-in** [comment]
Let me put it this way. That was a not very professional answer and the solution is not up to standard. I'm done.
