### ISSUE TITLE
Mandatory console table type parameter for dbstructure toinnodb

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8526]
For MariaDB barracuda table type there are two recommended options for Friendica

1. Dynamic - more flexibility in field size
2. Compressed - additionally to Dynamic fields can be compressed, but needs more CPU

**Sources**
1. Dynamic https://mariadb.com/kb/en/innodb-dynamic-row-format/
2. Compressed https://mariadb.com/kb/en/innodb-compressed-row-format/

At  the moment the console command `php bin/console.php dbstructure toinnodb` changes it automatically to dynamic, what is presumably the best choice for most of the installations. But it would be good, you an administrator have the choice with this conversion to decide the table type.

**Comment by AlfredSK** [comment]
Ackshully, it's the "InnoDB row format".

**Comment by hoergen** [comment]
Ignored. wontfix.

**Comment by annando** [comment]
See the remarks on the page https://mariadb.com/kb/en/innodb-compressed-row-format/#read-only

For a long time MariaDB wanted to get rid of `COMPRESSED`. They now appear to have changed their opinion. But I guess it is safer to not rely on this and to stick with the other format.
