### ISSUE TITLE
[2020.03] PHP Notice:  Undefined offset: 400 in /friendica/addon/buffer/bufferapp.php on line 135

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8528]
### Actual behavior
PHP Notice:  Undefined offset: 400 in /friendica/addon/buffer/bufferapp.php on line 135
### Steps to reproduce the problem

Friendica version you encountered the problem
Friendica 'Red Hot Poker' 2020.03 - 1338

Friendica source (git, zip)
git

PHP version
PHP Version 7.3.15

SQL version
MariaDB 10.1.44

**Comment by MrPetovan** [comment]
Please report individual Notice messages in https://github.com/friendica/friendica/issues/8475

**Comment by MrPetovan** [comment]
Moved to https://github.com/friendica/friendica/issues/8475#issuecomment-616553162
