### ISSUE TITLE
Encoding issue when uploading pictures

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8534]
Okay this is a little difficult to explain one :) I found it while updating Friendica Russian translation.

### Steps to reproduce the problem
1. Start writing new post. 
2. Go to Browser section to upload pictures. 
3. Select any album named in Cyrillic letters. If the localized interface is turned on then one of these will be "Wall Photos" - which will be displayed as "Фото стены". But it also happens with user created albums.
4. Upload the photo there and it won't appear in it afterwards. 
5. Go to photo section and you'll see it got uploaded into `Ð¤Ð¾ÑÐ¾ ÑÑÐµÐ½Ñ ` album instead which is gibberish.

![2020-04-21_20-07](https://user-images.githubusercontent.com/35988439/79892843-cd2ce680-840b-11ea-9884-f6bcde755b0f.png)

However if you decode it, you'll discover it is the right name, just converted in **ISO-8859-1** encoding when it should be **UTF-8**

There is no such problem if pictures are uploaded via main Photos section.

### Friendica version you encountered the problem
2020.03
### PHP version
7.4

**Comment by MrPetovan** [comment]
> just converted in **ISO-8859-1** encoding when it should be **UTF-8**

This is a problem I haven't seen in a long while. I didn't miss it. Thanks for the report!

**Comment by MrPetovan** [comment]
The madness. It has multiple level of Hell:
1. We use album names as reference to albums (!)
2. We pass them through PHP's `bin2hex()` to add them in an attribute field (I assume to avoid XSS??) (!!)
3. We pass them through a monkey wrenched Javascript `hex2bin()` to put them in the GET parameter of an Ajax request (!!!!)

The fun parts:
- Our Javascript `bin2hex()` gives a different output than PHP's `bin2hex()`.
- Our Javascript `hex2bin()` assumes Latin-1 string encoding like you found out about.
- Native Javascript's `atob()` to convert a string into base64 doesn't handle characters outside of Latin-1 either.

At this point, I don't know anymore, are we just clowns with fake engineering degrees?

**Comment by MrPetovan** [comment]
The solution was to trust Smarty's default escaping instead of the contorsion we were doing with `bin2hex()` and `hex2bin()`.

**Comment by SpcCw** [comment]
Patched the files according to the pull request above and the issue seems to be gone.
Awesome!
