### ISSUE TITLE
Peertube no status updates. Even not via RSS

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8538]
### Expected behavior

Following a peertube account, or the RSS feed will bring you status updates to your timeline.

### Actual behavior

Following peertube account is possible, but useless. Because you won't get status updates. Even if you follow the RSS feed you won't get status updates. 

### Steps to reproduce the problem

For example try to follow my peertube account via federation or rss feed

1. **Account**: https://mytube.madzel.de/accounts/odosendaidokai
2. **Channel**:   https://mytube.madzel.de/video-channels/odosendaidokaichan
3. **RSS**:  https://mytube.madzel.de/feeds/videos.xml?videoChannelId=38

Maybe there is a general problem with RSS feeds in the develop branch?

### Friendica version you encountered the problem
git / develop / mariadb / php 7.2

**Comment by annando** [comment]
It is possible to follow a peertube channel via AP. This works (with newer Peertube versions).

**Comment by hoergen** [comment]
You missed completely the point. You can follow **but you wont' get status updates**

**Comment by annando** [comment]
By subscribing to the channel (and not the account) you get updates. I tested it with different systems.

**Comment by tobiasd** [comment]
Maybe, when subscribing the account, then Friendica should not subscribe but display an error page with instructions to follow the channel instead.

**Comment by annando** [comment]
@tobiasd There is no way for us to detect that situation. Also we have to check why we can subscribe to users but never get updates. This *could* be a Peertube thing, this *could*be a Friendica thing.

**Comment by hoergen** [comment]
First I assumend it is on peertubes side, but then I saw that Friendica seems to have in the current develop stat difficulties with adding new rss feeds. So maybe there is a correlation?

**Comment by annando** [comment]
I subscribed to the channel. You could insert some content, then we could see if it works.

**Comment by hoergen** [comment]
I inserted yesterday a video. Shouldn't we get that?

**Comment by annando** [comment]
No, I subscribed today.

**Comment by hoergen** [comment]
Ok, I try to publish something. 
In general I like the idea, if you subscribe, you get the last .. don't know 10 posts or the last 1 week or something like that.

**Comment by hoergen** [comment]
A Video is published https://mytube.madzel.de/videos/watch/f39419b0-29a4-4409-8451-b921da568cb9

**Comment by annando** [comment]
It came with an "Update" message. Since the original hadn't been found, nothing had been done. I can change that behaviour.

**Comment by annando** [comment]
Could you try it again?

**Comment by hoergen** [comment]
I uploaded another video .

**Comment by annando** [comment]
Arrived: https://pirati.ca/display/37351193-c8de-4943-853c-e5f48a0643c4

**Comment by hoergen** [comment]
Nice ... but you changed something? That will be pushed soon? ;)

**Comment by annando** [comment]
That one just arrived without this "update" thing from above. So it worked out of the box.

**Comment by hoergen** [comment]
So did it on my site now ... hmmm none of the videos before arrived on my site ... is it again the thing  that you have to have an eye on it that it works? ;)

**Comment by annando** [comment]
Homeopathic coding ...

**Comment by hoergen** [comment]
I have the video wieder gelöscht, nur if you see the broken Vorschau on your Instanz

**Comment by annando** [comment]
Creo que dieser Sprachmix Hypolite could confuse, je crois.

**Comment by MrPetovan** [comment]
I just lacked "Vorshau", otherwise I was good on the meaning, thank you for caring about my lack of Deutsch verstehen.

**Comment by hoergen** [comment]
ok the next video didn't come through. Nor via AP neither RSS. The only difference so far is the length of the video. That one that came through was very short. All the others are longer.

**Comment by annando** [comment]
Weird. I get a lot of videos and some of yours as well. Can you give me the URL? Then I have a look in my logfile.

Possibly this is also related to your reported database errors.

**Comment by hoergen** [comment]
Oversolved by this issue https://github.com/friendica/friendica/issues/9705
