### ISSUE TITLE
[feature] add option to hide birthday notifications

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#8542]
Birthday reminders are nice. But not every user cares about them and some may even find them distracting and would want to hide them.

### Expected behavior
1. Add toggle to hide/show birthday reminders to Settings > Notifications
2. Add "x" to birthday notification at top of network page in extended view to hide them after seeing them. This would allow users to remove the info once seen.

### Actual behavior
No option to hide birthday notifications.

**Comment by MrPetovan** [comment]
Thank you for the feature request!

**Comment by RealVegOs** [comment]
I would like such an option with the "x" too. Another solution was for me, not to show the birthdays on top of my timeline. Would rather accept it somewhere in a side panel. But the "x" is OK.
🍻🍻🍻🍻🍻🍻🍻🍻🍻🍻

**Comment by MrPetovan** [comment]
Technical note: There's a system-wide config `theme.hide_eventlist` to hide them that can easily be transformed into a user-specific setting.
