### ISSUE TITLE
Image proxy can't handle redirections

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8553]
Proxy URL: https://friendica.mrpetovan.com/proxy/3f/aHR0cHM6Ly9wb29sLmpvcnRhZ2UuY29tL2dsYWNlb25zb2NpYWwvbWVkaWFfYXR0YWNobWVudHMvZmlsZXMvMDAxLzU5OS8yMDcvb3JpZ2luYWwvOGViNTViYjRhYjAyMDVhZi5wbmc=.png
Target URL: https://pool.jortage.com/glaceonsocial/media_attachments/files/001/599/207/original/8eb55bb4ab0205af.png
Actual URL: https://blob.jortage.com/blobs/5/f2e/5f2ea7cb0869334cc2c2e2b0d21a68501f0b9cdeed7225578227dcb28712478b29188542115c44c71bc145fbb497fb1e3b1ed1d378af3007a676cf5618d35895

Proxy returns an Internal Server Error with redirections.

**Comment by annando** [comment]
Your test works here. I clicked on all three links and saw the same picture.

**Comment by MrPetovan** [comment]
Dammit. Closing for now.
