### ISSUE TITLE
Approval of registrations partly broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8557]
### Expected behavior
When you have register policy set to approval you are able to accept a registration by clicking on the 'thumb up' icon.

### Actual behavior
When I do that I get a info bubble with 'account approved' message. But it doesn't work. The user still waits for approval and remains in the list of pending registrations.
I am able to approve the account by using the batch approval (checking the box and click on the button).

My admin account is using vier as theme. Don't know if that's important.

This is a new issue. It worked reliably one or two days ago.

### Steps to reproduce the problem
Register policy set to approval.
Register an account.
Try to approve it by clicking on the thumb up icon.

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Thank you for the report. Any SQL error related to the new views?

**Comment by AlfredSK** [comment]
I have to check that.

**Comment by annando** [comment]
Please check for "DB Error" in your Friendica log file. I can remember that I did some work at exactly that place - and I was only able testing exactly that situation theoretically, since I don't have this situation on my servers.

**Comment by annando** [comment]
Please execute this query: ```select * from `pending-view`;```

**Comment by MrPetovan** [comment]
Executing the view query outside of Friendica worked for me, but using PDO did fail in my case.

**Comment by annando** [comment]
Does it crash with the same error on PDO?

**Comment by MrPetovan** [comment]
My registrations are closed so I can't really test that case.

**Comment by AlfredSK** [comment]
```
MariaDB [friendica]> select * from `pending-view`;
Empty set (0.000 sec)
```

Which isn't suprising because I was able to approve the new account via the batch aproval - like described in the issue.

Also, I found no PHP errors matching the time when the issue occured.

**Comment by annando** [comment]
@AlfredSK with errors I meant in the Friendica log this time. You have to search for "DB Error".

**Comment by AlfredSK** [comment]
I already reported all the DB errors I found. There was none related to this issue as far as I can tell.
Only the 'Duplicate entry...' and 'Truncated incorrect DOUBLE value...' ones.

**Comment by AlfredSK** [comment]
I'm doing a test. Registering an account myself and will see what happens....

**Comment by MrPetovan** [comment]
Doesn't that make you fall under the no-duplicate account policy at Libranet?

**Comment by AlfredSK** [comment]
I have plenty of accounts. :-)

**Comment by AlfredSK** [comment]
If I only knew what to grep for. The debug level logging is insane. :-)

But I don't get any DB errors when I click on the thumb. Also no error in browser console. And no PHP error/warning.

**Comment by AlfredSK** [comment]
The thumb is linked to this URL...
`https://libranet.de/admin/users/allow/3788?t=1588106946.a75c188e4d758dd02922f10ab186612cc7a016c65ea4e5b98a00a7a4f4d9a07cb6b3b983bf1a9bedf723c743f7b6f49ea7352d8376fead802b31caecc3f63e1b`

I hope that's no secret key to the server. :-)

**Comment by annando** [comment]
Should be fixed by the PR. I used the wrong database call there. Weird that it worked in the console.

**Comment by AlfredSK** [comment]
Works again. :-) :+1:
