### ISSUE TITLE
DB errors: 1292 - Truncated incorrect DOUBLE value

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8560]
### Actual behavior
I get a LOT of DB errors for 'Truncated incorrect DOUBLE value'.

Example
```
DB Error {"code":1292,"error":"Truncated incorrect DOUBLE value: 'user@server.tld:fdacc1ed-175e-a824-b686-caa372711356'","callstack":"Database::update, DBA::update, message_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent, Page::run","params":"UPDATE `notify` SET `seen` = 1 WHERE (`type` = 16 AND `parent` = 'user@server.tld:fdacc1ed-175e-a824-b686-caa372711356' AND `uid` = 33)"} - {"file":"Database.php","line":731,"function":"e","uid":"7e66c6","process_id":6869}
```

I replaced the actual user and server with placeholders.

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
There is another one that appears very often...

`DB Error {"code":1062,"error":"Duplicate entry 'http:\/\/mstdn.social\/users\/ritzelpaket' for key 'nurl'","callstack":"Database::insert, DBA::insert, GContact::updateFromPublicContact, GContact::updateFromPublicContactID, Contact::updateContact, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction","params":"INSERT INTO `gcontact` (`name`, `nick`, `url`, `nurl`, `location`, `about`, `keywords`, `contact-type`, `network`, `addr`, `notify`, `alias`, `created`, `updated`, `server_url`, `nsfw`, `hide`, `archived`, `archive_date`, `birthday`, `photo`, `last_contact`, `last_failure`, `community`, `generation`) VALUES ('ritzelpaket', 'ritzelpaket', 'https:\/\/mstdn.social\/users\/ritzelpaket', 'http:\/\/mstdn.social\/users\/ritzelpaket', '', '', '', 0, 'apub', 'ritzelpaket@mstdn.social', 'https:\/\/mstdn.social\/users\/ritzelpaket\/inbox', 'https:\/\/mstdn.social\/@ritzelpaket', '2020-04-28 14:49:44', '2020-04-28 14:49:46', 'https:\/\/mstdn.social', 0, 0, 0, '0001-01-01 00:00:00', '0001-01-01', 'https:\/\/libranet.de\/images\/person-300.jpg', '2020-04-28 14:49:46', '0001-01-01 00:00:00', '', 2)"} - {"file":"Database.php","line":731,"function":"e","uid":"06f2bc","process_id":20044}`

**Comment by annando** [comment]
Duplicate entries can happen and they aren't an error. But the first one sounds weird.

**Comment by AlfredSK** [comment]
This one looks interssting...
https://github.com/friendica/friendica/issues/8474#issuecomment-620809409

**Comment by annando** [comment]
I know where the messages comes from - in fact it is unchanged for quite some time - and the query is simply wrong. I guess I need some detective work to see how this query was supposed to look alike.

It is this line: https://github.com/friendica/friendica/blob/develop/mod/message.php#L361

And you mustn't try to search an integer value ("parent") with a string ...

**Comment by AlfredSK** [comment]
Btw. is it intended that the postupdate script always drops and re-creates the new views every time I run it manually?

**Comment by annando** [comment]
Sadly yeah. I haven't found a way to check if they look like they had been expected to look.
