### ISSUE TITLE
Can't login to your Diaspora account. Please check handle (in the format user@domain.tld) and password.

### ISSUE THREAD

**Issue by adrelanos** [friendica/friendica#8564]
### Expected behavior

functional diaspora export

### Actual behavior

> Can't login to your Diaspora account. Please check handle (in the format user@domain.tld) and password.

### Steps to reproduce the problem

go to https://meld.de/settings/connectors

go to diaspora export

check Enable Diaspora Post Addon
enter Diaspora handle
enter Diaspora password
check Post to Diaspora by default

save settings

### Friendica source (git, zip)

https://meld.de/profile/whonix

//cc @copiis

**Comment by copiis** [comment]
[2020.06-dev]

`PHP Notice:  Undefined index: aspect in /friendica/addon/diaspora/diaspora.php on line 178', referer: https://meld.de/settings/connectors`

**Comment by MrPetovan** [comment]
I'll be able to test this later in the day.

**Comment by MrPetovan** [comment]
I haven't been able to reproduce this issue, however I have enjoyed overhauling the Diaspora connector settings panel.

Are you sure you used you full Diaspora address `user@domain.tld`? I used `mrpetovan@diaspora.permutationsofchaos.com` for myself and it worked with my Diaspora password.

**Comment by adrelanos** [comment]
My mistake. Used dispora login e-mail address instead of diaspora handle. Thanks for help.

> Connected with your Diaspora account whonix@diasp.org

**Comment by MrPetovan** [comment]
The Diaspora handle contains the pod domain that we need to authenticate you against. With just the email address, we can't guess which pod you registered on!
