### ISSUE TITLE
DB error: 1366 - incorrect integer value

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8565]
### Expected behavior
Don't try to store empty strings in integer fields.

### Actual behavior
```2020-04-29T20:19:53Z worker [ERROR]: DB Error {"code":1366,"error":"Incorrect integer value: '' for column `friendica`.`gserver`.`relay-subscribe` at row
 1","callstack":"Database::update, DBA::update, GServer::discoverRelay, GServer::detect, GServer::check, GContact::sanitize, PortableContact::load, Fetch
PoCo::execute","params":"UPDATE `gserver` SET `relay-subscribe` = '', `relay-scope` = '' WHERE (`id` = 2081)"} - {"file":"Database.php","line":736,"funct
ion":"e","uid":"a613ef","process_id":5283}``` 

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
MariaDB 10.3

**Comment by annando** [comment]
Had this happened again or can we close the issue?

**Comment by AlfredSK** [comment]
Yes. It still seems to happen once a day. I checked today's and yesterday's log file. 

I checked what server has the ID 2018 in my gserver table:
```
MariaDB [friendica]> select id, url, site_name, network, `relay-subscribe`, `relay-scope` from gserver where id = 2081;
+------+-----------------------------+------------------+---------+-----------------+-------------+
| id   | url                         | site_name        | network | relay-subscribe | relay-scope |
+------+-----------------------------+------------------+---------+-----------------+-------------+
| 2081 | https://friendica.hubup.pro | HubUP^ Friendica | dfrn    |               1 | tags        |
+------+-----------------------------+------------------+---------+-----------------+-------------+
```

**Comment by annando** [comment]
Meh ...

**Comment by AlfredSK** [comment]
As far as I can tell it happens only with that ID 2081. So, maybe, it's a specific situation with the one remote node?
