### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by WisTex** [friendica/friendica#8569]
I noticed that the original script was released under the MIT license and that you changed it to GNU Affero? Why? The GNU Affero License makes it impossible to integrate with any non-GPL script.

I can understand wanting people to contribute back, but the problem with the GNU Affero License in particular is that *everything* has to GPL or GNU Affero, including any themes you use, any third-party scripts you integrate with, etc.

Is there a way to use the script under the original MIT license, or some other license that says we can use non-GPL scripts and themes alongside your script?

**Comment by tobiasd** [comment]
Mike Macgirvin changed the license back then when the work on RedMatrix started. There was some harassment by people for Friendica _not_ using AGPL before... but you have to ask him for the exact reasons.

You can always checkout the commit before the switch from MIT license and then use that old version and re-implement all the features you want to have,

As for your own plugins and themes. Use what ever license you want to use for them. No one from the project will chase you for putting your plugin under another license.

**Comment by WisTex** [comment]
That's what I thought. Unfortunately, the GPL basically makes it harder for federation to be used outside the open-source world since you cannot integrate a GPL script with a non-GPL script.  For example, you cannot use Freindica to handle users for a non-GPL script (which is what I was hoping to accomplish).

The entire concept of "federation" and "sorry, it's only for GPL" are at odds with each other since you significantly limit your audience. 

I know you probably cannet change it, but the person who changed it shot yourself in the foot. You will never have widespread usage if it cannot be integrated with non-GPL scripts.

**Comment by MrPetovan** [comment]
What makes you think we want widespread usage? What kind of non-GPL script Friendica would benefit from regarding audience?

**Comment by WisTex** [comment]
The whole point of "federation" is so that users can connect with each other. If there are very few users, interest will die, and the project will die. And I have seen way too many great ideas fail because they did not foster a large enough userbase.  Having a system that makes it easier for users to connect one another doesn't mean much if there are not a significant number of users using it.

**Comment by MrPetovan** [comment]
This didn't answer any of my questions. There has been enough users and interest to keep the project going since 2014, what makes you think it would change anytime soon if we keep this license?

Besides, the whole point of "federation" is not relying on a single piece of software. There are "just" over 10,000 Friendica users, but thanks to "federation", they are able to communicate with more than 3,500,000 accounts across more than a dozen projects.

I'm still curious, what is the integration that can't happen because of licensing issue?

**Comment by WisTex** [comment]
Unless I am misunderstanding the GPL, it appears that:

1. You cannot use a third party theme since it is copyrighted and you can't mix GPL with copyrighted work. That any theme you create must be released as GPL, even if it is specific for your website.
2. If you want to build a website with multiple scripts, you cannot combine non-GPL scripts with a GPL script. For example, if you purchased code that allows people to bookmark their favorite websites, you would have to release that under the GPL if you combine both scripts into one website. If you do not one the copyright of that code, you cannot combine it with a GPL script.
3. If your theme links to multiple scripts, they all become subject to the GPL, since it is now considered "one work" even if the only thing you are doing is linking from one script to another so it looks seamless. 

That means anything you change is subject to the GPL, even copyrighted work you do not own.

**Comment by annando** [comment]
You can always extend Friendica by using addons - and they needn't to have the same license.

Is this more some general question or do you have some project in mind?

**Comment by WisTex** [comment]
We have a particular project in mind. We are still building the site and saw Friendica and Hubzilla and other similar federated identify software with social features, and thought that it would be ideal to use as the login for our website, especially since social features are already built-in.

The challenge is that the theme we are using is purchased. We have a license but don't own the copyright. We also have certain scripts that we purchased that do various things that we also do not own the copyright to. We were going to use the same theme, API calls, and custom code directly accessing the database and various functions to unite the scripts into one website. For example, logging into Friendica/Hubzilla/etc. also logs you into the rest of the website, even though that part of the site is a completely separate codebase. The permissions for the rest of the site are tied to your federated account.

The issue with GPL and GNU Affero is that it attempts to force any "combined work" into using that license. Since we do not own the copyright of all of the code we want to integrate, it is actually illegal for us to release it under GPL or GNU Affero.

**Comment by annando** [comment]
Well, concerning the theme one has to see if this is a problem. Logging in could be done completely via addons.

**Comment by hoergen** [comment]
As @annando said, you can always extend Friendica with scripts,with various licenses (without violating those licenses). But the big difference here,as  I understand, is that those scripts and extensions can't be part of the Friendica project. Thus those scripts can't be integrated and distributed with Friendica. But you can use it to extend your personal "Website" in every way of your personal and legal taste.
Or do I miss something @tobiasd  ?

**Comment by tobiasd** [comment]
INAL but for the project we always said (if memory servers me correctly) that you are free to _use the API and the hooks for your clients, themes and addons_. Especially for the addons, there are many under a more permissive opensource license (if it differs it is noted in the PHP header of those addons), mostly from the time when Friendica was under one as well.

As you mention Hubzilla, that and zot are licensed using the MIT license.
