### ISSUE TITLE
Fix Perfect Scrollbar dependency

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8578]
Oof, all the current Travis builds are failing because one of the Bower dependency repository has been deleted by its author. We have to find another source for Perfect Scrollbar, or get rid of the dependency altogether.

_Originally posted by @MrPetovan in https://github.com/friendica/friendica/pull/8573#issuecomment-623507001_

**Comment by AlfredSK** [comment]
Nice. The complete repo vanished. Is this here an option?
https://www.npmjs.com/package/perfect-scrollbar
https://github.com/mdbootstrap/perfect-scrollbar

**Comment by MrPetovan** [comment]
Yes, Composer supports both Bower and npm, I'm been selecting Bower for standalone libraries likePerfect Scrollbar and npm for jquery-based libraries, but I can make an exception.

**Comment by MrPetovan** [comment]
So. We were using noraesae's Perfect Scrollbar version 0.6.16, but they deleted their GitHub account entirely, leaving orphan packages. But [some guy registered under the same user name on GitHub](https://github.com/noraesae/perfect-scrollbar-bower/issues/1#issuecomment-623767584), and created the same name repository to maintain compatibility with his own system, using an old version (0.5.9).

Meanwhile, the npm package named `perfect-scrollbar` isn't the same piece of software, it's part of a larger project called Material Design for Bootstrap and wouldn't be a drop-in replacement.

I also learned that [Bower is getting deprecated](https://bower.io/blog/2017/how-to-migrate-away-from-bower/), so the Bower dependencies we are using now may not be available in some near or far future.  

I also learned that [the Composer plugin we've been using to pull frontend libraries from npm and Bower](https://github.com/fxpio/composer-asset-plugin) is being replaced by [another one that's apparently more involved](https://github.com/fxpio/foxy).

I'm not sure where all of this places us, the quick and dirty solution would be to ship a copy of the last distribution version of Perfect Scrollbar we used with Friendica, alongside the handful of libraries I couldn't find in npm or Bower.

The ideal would be to move from fxpio/composer-asset-plugin + Bower/npm to fxpio/foxy + npm/Yarn and redo the search of the Bower packages we currently use, but I'm guessing it won't be straightforward.

**Comment by annando** [comment]
Is there a way for some quick hack so that the checks don't fail? And then in the next days this whole could be renewed?

**Comment by annando** [comment]
I did the quick and dirty solution here: https://github.com/friendica/friendica/pull/8581

This saves us some time to continue working on the open PR and to search for good solution.

**Comment by MrPetovan** [comment]
It would be enough, I opened a separate issue for an eventual migration.

**Comment by MrPetovan** [comment]
Closed by #8581

**Comment by MrPetovan** [comment]
> Meanwhile, the npm package named `perfect-scrollbar` isn't the same piece of software, it's part of a larger project called Material Design for Bootstrap and wouldn't be a drop-in replacement.

I was informed that it is in fact the same project, just multiple major versions ahead than the version we used, which means we can use the npm package at the version we used it.

**Comment by annando** [comment]
Sounds good. I really dislike included libraries.

**Comment by MrPetovan** [comment]
Me too, but your quick fix was necessary to resume tests.
