### ISSUE TITLE
ActivityPub followers/following collections contain non-ActivityPub actors

### ISSUE THREAD

**Issue by koehn** [friendica/friendica#8588]
### Expected behavior
ActivityPub actors in `followers` and `following` collections would contain valid ActivityPub actors.

### Actual behavior
Actors from Diaspora et al appear alongside ActivityPub actors. Attempts to `GET` the URLs of e.g., Diaspora actors result in a 406, 404, or timeout. 

### Steps to reproduce the problem
View the `followers` or `following` collection of a Friendica user with both ActivityPub and non-ActivityPub actors, e.g., https://friendica.mrpetovan.com/profile/hypolite

### Friendica version you encountered the problem
Current

see `example.com/friendica` on your Friendica node for the version information.

### PHP version
N/a
### SQL version
N/a

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by koehn** [comment]
Thanks for the fast fix!

**Comment by MrPetovan** [comment]
Of course! Not all the Friendica nodes run the develop branch so you might encounter more shenanigans but you'll be set with mine and libranet.de for example.
