### ISSUE TITLE
Ensure post location is plaintext

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8593]
I received a reply from Hubzilla where the post location contains a BBCode link that isn't interpreted and shows as is: https://friendica.mrpetovan.com/display/471946b8-cd69-4fde-bb93-82b8092091bf

Hubzilla display: https://lo.hn/display/b64.aHR0cHM6Ly9sby5obi9pdGVtLzQ3MTk0NmI4LWNkNjktNGZkZS1iYjkzLTgyYjgwOTIwOTFiZg

We can simply run `BBCode::toPLaintext` on the post location to fix this display issue as I do not think having arbitrary HTML in this place is a good idea.

**Comment by annando** [comment]
When we store the location always as plaintext, then in fact we should make a plaintext of it upon receiving it.

**Comment by MrPetovan** [comment]
To be fair it's the first time I've seen something other than plaintext in that field, which means that we had no idea what we had to convert it from to ensure plaintext. Now we know we can have BBCodes, which means that we can probably expect HTML as well. I'll first run `Markdown::convert`, `BBCode::convert` then `HTML::toPlaintext` instead of just `BBCode::toPLaintext` directly just to cover all the bases we know about.

**Comment by annando** [comment]
Which way had it arrived? Diaspora or AP?

**Comment by MrPetovan** [comment]
AP.
