### ISSUE TITLE
bower-asset/perfect-scrollbar is unavailable during installation via git

### ISSUE THREAD

**Issue by timmyraa** [friendica/friendica#8598]
While installing friendica 2020.03 from git, after running composer install, the installation fails with the following message:

```
- Installing bower-asset/perfect-scrollbar (0.6.16): Downloading (failed)    Failed to download bower-asset/perfect-scrollbar from dist: The "https://api.github.com/repos/utatti/perfect-scrollbar-bower/zipball/3049129e5dbb403295ce8507a461cdd0f200938c" file could not be downloaded (HTTP/1.1 404 Not Found)
```

It then asks you to log in to github, but after doing so it says it still failed as the repo is no longer available:

```
[RuntimeException]
Failed to execute git clone --no-checkout 'https://***:***@github.com/utatti/perfect-scrollbar-bower.git.git' '/var/www/friendica/view/asset/perfect-scrollbar' && cd '/var/www/friendica/view/asset/perfect-scrollbar' && git remote add composer 'https://***:***@github.com/utatti/perfect-scrollbar-bower.git.git' && git fetch composer && git remote set-url origin 'https://github.com/utatti/perfect-scrollbar-bower.git.git' && git remote set-url composer 'https://github.com/utatti/perfect-scrollbar-bower.git.git'

Cloning into '/var/www/friendica/view/asset/perfect-scrollbar'...remote: Repository not found. fatal:***@github.com/utatti/perfect-scrollbar-bower.git.git/' not found
```

I could install via zip, but git is my preferred method to keep it updated in the future.

**Comment by MrPetovan** [comment]
Hi, it is [a known problem](https://github.com/friendica/friendica/issues/8578) that was fixed on the `develop` branch.

To avoid this issue on your server:
- Switch to the latest `develop` branch.
- Install 2020.03 from [the archive release](https://github.com/friendica/friendica/releases/tag/2020.03).

As a general rule, we discourage administrators to install stable versions of Friendica through git to avoid this kind of situation.

**Comment by timmyraa** [comment]
Apologies - I did try searching for the error and package, but couldn't find anything. I'll switch away from git to zip instead, even though that method and the merits are touted on here: https://friendi.ca/resources/ :)

**Comment by MrPetovan** [comment]
Thanks for pointing out the documentation discrepancy, we'll update that page shortly!

**Comment by MrPetovan** [comment]
The page has been updated: https://friendi.ca/resources/
