### ISSUE TITLE
vier: Profile editing not possible

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8606]
### Expected behavior
When using 'vier' it should be possible to edit the user profile.

### Actual behavior
There is an error on the .../settings/profile page when using 'vier'.
The sub-sections don't open on click/tap. Nothing happens.

![vier-profile-edit](https://user-images.githubusercontent.com/3656054/81395752-7cfc9680-9124-11ea-872e-4794d6f67824.png)

Reported here: https://libranet.de/display/0b6b25a8-725e-b2ab-0963-ada190361470

### Steps to reproduce the problem

- Switch the theme to 'vier'
- Go to .../settings/profile to edit the profile
- Click on the (sub-)sections e.g. 'personal'

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
I'm on it.

**Comment by annando** [comment]
Thx! It had been reported from one of my users as well.
