### ISSUE TITLE
Replies to Mastodon threads don't seem to be generating notifications

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8610]
It's the second report I'm getting from Mastodon contacts who stumbled on one of my replies without having been notified of it.

See https://cybre.space/@LogicalDash/104133447813726081

I'm not sure what could have caused this change of behavior, maybe the recent work on terms/tags?

Not sure what causes Mastodon notifications in the first place.

**Comment by AlfredSK** [comment]
I think Mastodon notifications rely on mentions: no mention -> no notification.

**Comment by MrPetovan** [comment]
You can see the mention in my reply on the Mastodon thread though.

**Comment by AlfredSK** [comment]
Hmm. Is that an implicit mention?

I just commented on a Mastodon thread with an explicit mention (that thing you see in the body while creating the comment) and I got a notification on Mastodon.

![masto-notif](https://user-images.githubusercontent.com/3656054/81431148-f619df00-9160-11ea-885b-55194fec8740.png)

**Comment by AlfredSK** [comment]
Yup. No notification on Mastodon when implicit mentions feature is enabled.

**Comment by MrPetovan** [comment]
Weird, implicit mentions only make sense on Friendica. Even if I didn't mention the account I was replying to explicitly, you can see the mention in the reply on the Mastodon side, which means it's been added to the body just before sending the message. I thought it should be enough to trigger the notification. Apparently not, but it was working before @annando 's work on terms/tags.

**Comment by AlfredSK** [comment]
Yeah. With an implicit mention you see the mention in the body on Mastodon but no notification is triggered.

**Comment by annando** [comment]
We are adding the mentions not only in the body but also in the non visible part. I have to check.

**Comment by annando** [comment]
Yeah, there is an issue that depends on the settings for the implicit mentions.

**Comment by annando** [comment]
Yeah, due to the new way of detecting and storing of mentions and hashtags, this feature doesn't work anymore. I guess the best way is to completely rework it. Since I never use this, the question is, which persons should be mentioned in a comment?

Imagine A is commenting on B and is mentioning B. Then you comment on A. Does this feature mentions only A or also B? Does it make a difference if A is mentioning B not in the body, but only in the other protocol fields?

I have got several ideas how to make it work again - I just need to know how it should work.

**Comment by MrPetovan** [comment]
> Imagine A is commenting on B and is mentioning B. Then you comment on A. Does this feature mentions only A or also B?

Both.

> Does it make a difference if A is mentioning B not in the body, but only in the other protocol fields?

It doesn't. It matters for display in Friendica because mentions of people in the protocol fields will be stripped from the start of the message body.

Let's take this message:
> To: A
> CC: B
> Body: `@A @B Hey look at @C`

In Friendica, both `@A` and `@B` are considered implicit mentions and will be stripped from the start of the message to give just `Hey look at @C`. However some AP software put thread mentions at the end of the message, and in this case they will appear in the body.

It would then look like
> To: A
> CC: B
> Body: `@A Hey look at @C @B`

And in Friendica we would only strip `@A` from the displayed item body which would give `Hey look at @C @B`.

**Comment by MrPetovan** [comment]
## With disabled implicit mentions

### Incoming message

> To: A
> CC: B
> Body: `@A @B Hey look at @C`

The message body is left unchanged, however we still store `@A` and `@B` as implicit mentions in the tag table.

## Outgoing message

> To: A
> CC: B
> Body: `@A @B Hey look at @C`

Again, the message body is left unchanged because the implicit mentions already are present at the start of the body.

**Comment by MrPetovan** [comment]
Confirmed to be fixed.
