### ISSUE TITLE
CLI: bin/console user delete resets deletion counter

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#8612]
Hi!
When deleting users on CLI by using bin/console user <user> it seems as if the deletion counter "user is deleted in 7...6...4...2....1 days" is being reset when within the deletion grace time period the user is deleted again, for example by a cron script running each week, before the worker task of Friendica actually really deletes the user. So the period starts again with 7 days and the user is effectively not being deleted. 

When the cron script runs every 14 days, this doesn't happen, because worker task has had time to really delete the user. 

I think, the problem is that bin/console user delete doesn't check if the user is already marked as deleted and thus resets the timestamp again to 7 days. Maybe this can be solved by changing the underlying SQL query...

**Comment by MrPetovan** [comment]
You're absolutely right, thanks for the report!
