### ISSUE TITLE
Cant fetch Atom link from Hugo website generator

### ISSUE THREAD

**Issue by strk** [friendica/friendica#8623]
### Expected behavior

I pass the root of a Hugo generated website to the `Add New Contact` field in `/contact` page and get to see the Atom feed in there

### Actual behavior

An error message says: 
> The network type couldn't be detected. Contact can't be added.

### Friendica version you encountered the problem

2020.03 Red Hot Poker

**Comment by MrPetovan** [comment]
If the URL doesn't point to an actual Atom/RSS feed, we don't do auto-discovery from meta tags of generic HTML documents.

**Comment by strk** [comment]
I'm pretty sure Friendica used to do this ?

**Comment by tobiasd** [comment]
I have to agree with @strk Friendica did do auto-detection from the meta-informations of a webpage. But I have not tried to do so for some time now.

**Comment by MrPetovan** [comment]
Would you mind sharing the URL of the site you've tried on?

**Comment by tobiasd** [comment]
Following a Wordpress page (e.g. https://friendi.ca) works.

**Comment by tobiasd** [comment]
And I could follow https://gohugo.io/ , assuming they use Hugo for the page.

**Comment by MrPetovan** [comment]
Thanks for the follow-up, I feel like this is among the Friendica features I regularly forget they exist. Sorry for my misleading comment.

**Comment by strk** [comment]
URL of site tried: https://strk.kbt.io/blog

**Comment by MrPetovan** [comment]
Thanks!

**Comment by MrPetovan** [comment]
I can see the header tags:
```html
<link href="./index.xml" rel="alternate" type="application/rss+xml" title="Strk&#39;s Blog" />
<link href="./index.xml" rel="feed" type="application/rss+xml" title="Strk&#39;s Blog" />
```  
Maybe the relative links with the `./` syntax aren't recognized by Friendica.

**Comment by MrPetovan** [comment]
Yep, we assume the link is absolute in these fields: https://github.com/friendica/friendica/blob/32bddec33d37883d6bbeb57c85eec18ae568f517/src/Network/Probe.php#L1780-L1802

**Comment by MrPetovan** [comment]
This is tricky because there are multiple relative path syntax and this means we probably have to care about the value of an eventual `<base>` tag as well.

**Comment by MrPetovan** [comment]
@strk I noticed you removed the RSS links from your blog, but if you restore them and try adding the blog URL to a latest develop Friendica node, it should resolve the relative feed URL and correctly add it as contact.
