### ISSUE TITLE
Attaching videos and other files doesn't work

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8626]
### Expected behavior
Files are attached to the posts and accessible later.

### Actual behavior
Files seem to get uploaded and linked to the posts but videos don't play (even though the player displays) and downloading any file results in 0 byte download.

### Steps to reproduce the problem
Make a post and attach some files via browser dialog to it. Try to play the attached video or download any attached file from it.

### Friendica version you encountered the problem
2020.03
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.4.5

**Comment by MrPetovan** [comment]
What is the URL of these files/videos Friendica uses in the post?

**Comment by SpcCw** [comment]
@MrPetovan, after the post is published it has links like this:

https://friends.deko.cloud/redir/827?url=https://friends.deko.cloud/attach/5

If I go to "Videos" section where recent videos appear then the video (which also doesn't play there) has link like this:

https://friends.deko.cloud/attach/5?attachment=0

**Comment by MrPetovan** [comment]
Ok, the attach module, thank you for the elaboration.

**Comment by MrPetovan** [comment]
I can verify the wrong behavior on the latest `develop`.

**Comment by MrPetovan** [comment]
Will be closed by #8670
