### ISSUE TITLE
dbstructure update 1348 fails with error 1452

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8636]
### Expected behavior
dbstructure update 1348 should run successfully.

### Actual behavior
After the postupdate 1347 finally went through I updated to the latest develop and now I'm running into this dbstructure update error.

.../friendica tells me: "This is Friendica, version 2020.06-dev that is running at the web location https://libranet.de. The database version is 1348, the post update version is 1347."

But in admin panel I have the warning "The database update failed. Please run "php bin/console.php dbstructure update" from the command line and have a look at the errors that might appear." ( I also tried running it with _the force_ '-f')

When I do that I get:
```
Error 1452 occurred during database update:
Cannot add or update a child row: a foreign key constraint fails (`friendica`.`#sql-4da3_ff1312`, CONSTRAINT `tokens-client_id-clients-client_id` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON DELETE CASCADE)
ALTER IGNORE TABLE `user` MODIFY `guid` varchar(64) NOT NULL DEFAULT '' COMMENT 'A unique identifier for this user', MODIFY `username` varchar(255) NOT NULL DEFAULT '' COMMENT 'Name that this user is known by', MODIFY `password` varchar(255) NOT NULL DEFAULT '' COMMENT 'encrypted password', MODIFY `nickname` varchar(255) NOT NULL DEFAULT '' COMMENT 'nick- and user name', MODIFY `email` varchar(255) NOT NULL DEFAULT '' COMMENT 'the users email address', MODIFY `openid` varchar(255) NOT NULL DEFAULT '' COMMENT '', MODIFY `timezone` varchar(128) NOT NULL DEFAULT '' COMMENT 'PHP-legal timezone', MODIFY `language` varchar(32) NOT NULL DEFAULT 'en' COMMENT 'default language', MODIFY `register_date` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'timestamp of registration', MODIFY `login_date` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'timestamp of last login', MODIFY `default-location` varchar(255) NOT NULL DEFAULT '' COMMENT 'Default for item.location', MODIFY `theme` varchar(255) NOT NULL DEFAULT '' COMMENT 'user theme preference', MODIFY `pubkey` text COMMENT 'RSA public key 4096 bit', MODIFY `prvkey` text COMMENT 'RSA private key 4096 bit', MODIFY `spubkey` text COMMENT '', MODIFY `sprvkey` text COMMENT '', MODIFY `pwdreset` varchar(255) COMMENT 'Password reset request token', MODIFY `pwdreset_time` datetime COMMENT 'Timestamp of the last password reset request', MODIFY `account_expires_on` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'timestamp when account expires and will be deleted', MODIFY `expire_notification_sent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'timestamp of last warning of account expiration', MODIFY `allow_cid` mediumtext COMMENT 'default permission for this user', MODIFY `allow_gid` mediumtext COMMENT 'default permission for this user', MODIFY `deny_cid` mediumtext COMMENT 'default permission for this user', MODIFY `deny_gid` mediumtext COMMENT 'default permission for this user', MODIFY `openidserver` text COMMENT ''; 
ALTER IGNORE TABLE `user-contact` MODIFY `blocked` boolean COMMENT 'Contact is completely blocked for this user', MODIFY `ignored` boolean COMMENT 'Posts from this contact are ignored', MODIFY `collapsed` boolean COMMENT 'Posts from this contact are collapsed'; 
ALTER IGNORE TABLE `user-item` MODIFY `ignored` boolean COMMENT 'Ignore this thread if set', MODIFY `pinned` boolean COMMENT 'The item is pinned on the profile page'; 
ALTER IGNORE TABLE `verb` MODIFY `name` varchar(100) NOT NULL DEFAULT '' COMMENT ''; 
ALTER IGNORE TABLE `worker-ipc` MODIFY `jobs` boolean COMMENT 'Flag for outstanding jobs'; 
ALTER IGNORE TABLE `workerqueue` MODIFY `parameter` mediumtext COMMENT 'Task command', MODIFY `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Creation date', MODIFY `executed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Execution date', MODIFY `next_try` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Next retrial date'; 
Errors encountered performing database changes: ALTER IGNORE TABLE `item` MODIFY `guid` varchar(255) NOT NULL DEFAULT '' COMMENT 'A unique identifier for this item', MODIFY `uri` varchar(255) NOT NULL DEFAULT '' COMMENT '', MODIFY `uri-id` int unsigned COMMENT 'Id of the item-uri table entry that contains the item uri', MODIFY `uri-hash` varchar(80) NOT NULL DEFAULT '' COMMENT 'RIPEMD-128 hash from uri', MODIFY `parent-uri` varchar(255) NOT NULL DEFAULT '' COMMENT 'uri of the parent to this item', MODIFY `parent-uri-id` int unsigned COMMENT 'Id of the item-uri table that contains the parent uri', MODIFY `thr-parent` varchar(255) NOT NULL DEFAULT '' COMMENT 'If the parent of this item is not the top-level item in the conversation, the uri of the immediate parent; otherwise set to parent-uri', MODIFY `thr-parent-id` int unsigned COMMENT 'Id of the item-uri table that contains the thread parent uri', MODIFY `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Creation timestamp.', MODIFY `edited` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of last edit (default is created)', MODIFY `commented` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of last comment/reply to this item', MODIFY `received` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime', MODIFY `changed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date that something in the conversation changed, indicating clients should fetch the conversation again', MODIFY `network` char(4) NOT NULL DEFAULT '' COMMENT 'Network from where the item comes from', MODIFY `icid` int unsigned COMMENT 'Id of the item-content table entry that contains the whole item content', MODIFY `iaid` int unsigned COMMENT 'Id of the item-activity table entry that contains the activity data', MODIFY `vid` smallint unsigned COMMENT 'Id of the verb table entry that contains the activity verbs', MODIFY `extid` varchar(255) NOT NULL DEFAULT '' COMMENT '', MODIFY `psid` int unsigned COMMENT 'ID of the permission set of this post', MODIFY `resource-id` varchar(32) NOT NULL DEFAULT '' COMMENT 'Used to link other tables to items, it identifies the linked resource (e.g. photo) and if set must also set resource_type', MODIFY `attach` mediumtext COMMENT 'JSON structure representing attachments to this item', MODIFY `allow_cid` mediumtext COMMENT 'Deprecated', MODIFY `allow_gid` mediumtext COMMENT 'Deprecated', MODIFY `deny_cid` mediumtext COMMENT 'Deprecated', MODIFY `deny_gid` mediumtext COMMENT 'Deprecated', MODIFY `postopts` text COMMENT 'Deprecated', MODIFY `inform` mediumtext COMMENT 'Deprecated', MODIFY `type` varchar(20) COMMENT 'Deprecated', MODIFY `bookmark` boolean COMMENT 'Deprecated', MODIFY `file` mediumtext COMMENT 'Deprecated', MODIFY `location` varchar(255) COMMENT 'Deprecated', MODIFY `coord` varchar(255) COMMENT 'Deprecated', MODIFY `tag` mediumtext COMMENT 'Deprecated', MODIFY `plink` varchar(255) COMMENT 'Deprecated', MODIFY `title` varchar(255) COMMENT 'Deprecated', MODIFY `content-warning` varchar(255) COMMENT 'Deprecated', MODIFY `body` mediumtext COMMENT 'Deprecated', MODIFY `app` varchar(255) COMMENT 'Deprecated', MODIFY `verb` varchar(100) COMMENT 'Deprecated', MODIFY `object-type` varchar(100) COMMENT 'Deprecated', MODIFY `object` text COMMENT 'Deprecated', MODIFY `target-type` varchar(100) COMMENT 'Deprecated', MODIFY `target` text COMMENT 'Deprecated', MODIFY `author-name` varchar(255) COMMENT 'Deprecated', MODIFY `author-link` varchar(255) COMMENT 'Deprecated', MODIFY `author-avatar` varchar(255) COMMENT 'Deprecated', MODIFY `owner-name` varchar(255) COMMENT 'Deprecated', MODIFY `owner-link` varchar(255) COMMENT 'Deprecated', MODIFY `owner-avatar` varchar(255) COMMENT 'Deprecated', MODIFY `rendered-hash` varchar(32) COMMENT 'Deprecated', MODIFY `rendered-html` mediumtext COMMENT 'Deprecated', ADD INDEX `parent-uri-id` (`parent-uri-id`), ADD INDEX `thr-parent-id` (`thr-parent-id`), ADD CONSTRAINT `item-uri-id-item-uri-id` FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `item-parent-uri-id-item-uri-id` FOREIGN KEY (`parent-uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `item-thr-parent-id-item-uri-id` FOREIGN KEY (`thr-parent-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `item-psid-permissionset-id` FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT; <br />
Errors encountered performing database changes: ALTER IGNORE TABLE `tokens` MODIFY `secret` text COMMENT '', MODIFY `client_id` varchar(20) NOT NULL DEFAULT '' COMMENT '', MODIFY `scope` varchar(200) NOT NULL DEFAULT '' COMMENT '', ADD INDEX `client_id` (`client_id`), ADD CONSTRAINT `tokens-client_id-clients-client_id` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON UPDATE RESTRICT ON DELETE CASCADE; <br />
```

### Friendica version you encountered the problem
2020.06-dev commit bf8bb47d7de5b653a128a96ca703c58aa8b90a4a

### Friendica source (git, zip)
git 

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Error on altering the item table:
``ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`friendica`.`#sql-4da3_1009fae`, CONSTRAINT `item-psid-permissionset-id` FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`))``

Error on altering the tokens table:
``ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`friendica`.`#sql-4da3_1009fae`, CONSTRAINT `tokens-client_id-clients-client_id` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON DELETE CASCADE)``

**Comment by MrPetovan** [comment]
The following queries will tell you which foreign key values are missing from the reference tables:
```sql
SELECT `psid`, `uid`
FROM `item`
LEFT JOIN `pemissionset` ON `permissionset`.`id` = `item`.`psid`
WHERE `permissionset`.`id` IS NULL
```
and
```sql
SELECT `client_id`, `scope`, `uid`
FROM `tokens`
LEFT JOIN `clients` ON `clients`.`client_id` = `tokens`.`client_id`
WHERE `clients`.`client_id` IS NULL
```

**Comment by AlfredSK** [comment]
What the...
First query: ERROR 1146 (42S02): Table 'friendica.pemissionset' doesn't exist
Oh! Ok. A typo. :-)
...
But still: ERROR 1052 (23000): Column 'uid' in field list is ambiguous

**Comment by AlfredSK** [comment]
1. 
```
+------+------+
| psid | uid  |
+------+------+
|  849 | 1927 |
|  849 | 1927 |
|  849 | 1927 |
+------+------+
```

2.
```
+----------------------+---------+-----+
| client_id            | scope   | uid |
+----------------------+---------+-----+
| 0WEJk1x6AlgtjGRhyABX | request |   0 |
| 0WEJk1x6AlgtjGRhyABX | request |   0 |
| 0WEJk1x6AlgtjGRhyABX | request |   0 |
+----------------------+---------+-----+
```

**Comment by AlfredSK** [comment]
Thanks for helping with those queries. But I have no clue what the results sets tell me or what to do. I don't know what a 'child row', a 'foreign key' and a 'reference table' is. I'm lost.

**Comment by MrPetovan** [comment]
Back to the basics then. One way of storing data about anything is to store all the relevant values in the fields of in a single table.

Example:

Table `car`

make | make_logo | model
------------ | ------------- | --------
Volkswagen | volkwagen.png | Beetle
Volkswagen | volkwagen.png | Van
Volkswagen | volkwagen.png | Golf
BMW | bmw.png | 318
BMW | bmw.png | M3

Quickly you can spot patterns, similar values in fields across multiple rows. To save on space and allow editing these similar values without having to update every single row containing the value, we create a separate table (the **child table**) with all the relevant fields. From there, we assign a identifier and we refer to this identifier in the main table.

Table `car`

make_id | model
------------ | -------------
1 | Beetle
1 | Van
1 | Golf
2 | 318
2 | M3

Table `make`

id | name | logo
------------ | ------------- | --------
1 | Volkswagen | volkswagen.png
2 | BMW | bmw.png

However so far there's no hard relationship between `car.make_id` and `make.id`, so we could have  a row in `car` referring to the non-existent `make.id` value `3`. This would result in a blank when we try to retrieve the make information of the car. Database software allow the creation of a hard link between parent table `car` and child table `make` to ensure there always is a corresponding row in the child table. This is called a **foreign key** and it would prevent the insertion of non-existing `make.id` values in the `car.make_id` field.

Adding a foreign key to an existing pair of tables is tricky because the data needs to be already consistent (= no values in parent table referring to non-existent child table records), but since there was no hard consistency check, it is unlikely, like in your case.

The two queries I made you run show you existing references in the parent tables that are missing in the child tables. From there, you have two choices to restore data consistency to allow the foreign key to be created:
- Add a record with the corresponding identifier in the child tables with guessed data. It can be safe to do so in specific circumstances like in https://github.com/friendica/friendica/issues/8628 where we were able to reconstruct the missing data from the context.
- Delete the offending parent rows. This is the safest route to ensure consistency without jeopardizing privacy, and the related objects probably weren't usable without the related child table record anyway.

**Comment by annando** [comment]
Can you check if the user with the id `1927` still exists? There is no functionality that deletes permissionsets - except when a user is deleted. When that user exists, please check if the user is planned to be deleted.

With the `tokens` table I had been unsure to add that foreign key there - but I thought that the probability of an error should be low, since the table is so small. Well :-)

**Comment by annando** [comment]
@AlfredSK I added some pre check that automatically fixes these problems. Please fetch the latest changes and try again.

**Comment by AlfredSK** [comment]
Just for the record: there is no user with `uid = 1927` in table `user`.

I will pull and retry...

**Comment by AlfredSK** [comment]
Looks like it worked. :tada:  The message in admin panel is gone. 
But I cannot check directly via Linux console because I accidentally locked myself out. Bloody 2FA + fail2ban. 🤪

**Comment by AlfredSK** [comment]
I had blocked myself with three different client IPs (home wifi, mobile network and from another server). The lockout was really complete. :-) But I sneaked back into the server by switching the data connection to SIM card 2 on my phone.

Anyway. Back to topic:
Now I can confirm the dbstructure update was successful. Thanks again.
