### ISSUE TITLE
 Error on account creation: "Nickname is already registered. Please choose another."

### ISSUE THREAD

**Issue by coamtaker618** [friendica/friendica#8638]
When creating a new account (either on the webpage or the admin user page), I get the following error:

"Nickname is already registered. Please choose another."

The problem is that this is a (nearly) brand new Friendica install! I only have 2 users and neither of them have this nickname. I did have a user with this nickname whom I deleted. Looking in the database (friendica.user table), I only see the 2 users I'd expect (neither with any overlapping info to this user I'm attempting to create)...so I'm not even sure where it could be checking this list? I have also rebooted the system hosting Friendica since making these changes.

**Comment by MrPetovan** [comment]
Hi, please look into the `userd` table. That's where we store deleted usernames. We prevent user from reusing deleted usernames because we use public/private cryptographic key pairs to authenticate messages, and remote servers store the public key to check whether a message is from the account it claims to be sent from.

Creating a new user with the same username would result in the creation of a different cryptographic key pairs generation and the rejection of all subsequent message sent to remote systems that used to know about the previous account.

**Comment by tobiasd** [comment]
There is also a list of forbidden nicknames (define able by the admin of a node) to prevent the usage of nicks like 

> info, marketing, sales, support, abuse, noc, security, postmaster, hostmaster, usenet, news, webmaster, www, uucp, ftp, root, sysop

by some random people.

**Comment by coamtaker618** [comment]
@MrPetovan interesting.  I assume as this node is still standalone there's no harm...but that's good to know in the future :)   So for this instance am I correct in my understanding that removing these users from the `userd table` will result in them being usable names again?

Also, so I know, does it compare full names or emails or usernames or any of the above to the `userd` table when creating a new account?

@tobiasd Yes, I do remember seeing that list.  That makes sense!

**Comment by MrPetovan** [comment]
What do you mean by "standalone"? If it's "no federation at all", then yes there's no harm.

> So for this instance am I correct in my understanding that removing these users from the `userd table` will result in them being usable names again?

Absolutely.




> Also, so I know, does it compare full names or emails or usernames or any of the above to the `userd` table when creating a new account?

Just usernames (the `user` part in `user@domain.tld`). Email addresses don't have to be unique per account.

**Comment by coamtaker618** [comment]
Yes, I meant "no federation at all" when I said "standalone".  Cool, thanks :)  I'll give that a try when I get a chance!

**Comment by coamtaker618** [comment]
Delayed response, but it worked!  Was able to use that username again as soon as  I delelted the userd table!!  Thanks for the help :)
