### ISSUE TITLE
Please remove system.basepath from the database

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8659]
Moved my Friendica to a different folder.
I have already changed the path in the config but in the admin area I have the following message. Where can I find this in the database?

`Friendica's system.basepath würde aktualisiert '/home/users/meld/www/friendica' von '/home/users/zsemberi/www/friendica'. Bitte entfernen Sie system.basepath aus der Datenbank um Unterschiede zu vermeiden.`

**Comment by MrPetovan** [comment]
Table `config`, `cat = "system" AND key = "basepath"`

**Comment by MrPetovan** [comment]
I'm pretty sure there's an admin setting for this, but if not, you have the DB route above.

**Comment by copiis** [comment]
In the admin area you can only change the path to the tmp directory.
But I wouldn't have gotten into the admin area without the right path because the page could not be loaded, I had to change the path in the config. After a while the message disappeared, everything seems to be running smoothly now.

**Comment by copiis** [comment]
Just seen that the path was taken over in the database.

**Comment by MrPetovan** [comment]
What do you mean "taken over"?

**Comment by copiis** [comment]
The path was automatically transferred from the config file in the database.

**Comment by MrPetovan** [comment]
Great news!
