### ISSUE TITLE
My admin profile has disappeared after moving Friendica on the server.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8662]
### Expected behavior
My profile should be visible.
### Actual behavior
There is a profile not found message with the following information.
```
#0 [internal function]: Friendica\Module\Profile\Profile::content(Array)
#1 /friendica/src/App/Page.php(332): call_user_func(Array, Array)
#2 /friendica/src/App/Page.php(388): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#3 /friendica/src/App.php(576): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#4 /friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#5 {main}
```
### Steps to reproduce the problem
I moved my Friendica instance on the server and exported the database once and imported it again.
### Friendica version you encountered the problem
2020.06-dev
see `example.com/friendica` on your Friendica node for the version information.
Friendica 'Red Hot Poker' 2020.06-dev - 1348
### Friendica source (git, zip)
git
### PHP version
7.3
### SQL version
MariaDB 10.1.44

**Comment by copiis** [comment]
And the users are no longer displayed in the admin area.
![meld de-220316](https://user-images.githubusercontent.com/12480023/82374096-d87d2d00-9a1e-11ea-9087-b1a41b68d208.png)

**Comment by MrPetovan** [comment]
What does your `user` table look like after the import?

**Comment by copiis** [comment]
All users were still there. I have now reinstalled Friendica.
