### ISSUE TITLE
No welcome email

### ISSUE THREAD

**Issue by coamtaker618** [friendica/friendica#8669]
I have a new (self-hosted) Friendica install that I am trying to add users to.  Unfortunately I am not receiving the welcome email that Friendica should be generating.

As per issue #8630 I initially had an invalid email address for the admin email address. This has been changed & the admin email address is now an email I have access to!  However I believe due to changing the email address the rest of the email related data (such as credentials to allow mail sending) need to be updated.  This is just a guess, but I think it makes sense.

Fundamentally the problem is that Friendica tells me the new Friendica user account should be getting the "welcome email" but does not.

**Comment by annando** [comment]
We are using the mail functionality of the used server. Please check in that log file first if a message had been sent. Very often this problem occurs because of wrong mail server settings.

**Comment by coamtaker618** [comment]
How would one go about changing these settings?  I don't see anything in my config.php file about email settings beyond the admin_email


Interestingly I also have "'disable_email_validation' => 'true'"   clearly that needs to be false, but shouldn't that option not send any emails?

**Comment by AlfredSK** [comment]
We send mails through the mail() function. This needs a working local smtp mail server like postfix or sendmail. It is also possible to use the 'PHP Mailer' add-on instead where you can configure an external mail server to handle the outgoing mails.

**Comment by coamtaker618** [comment]
ooohhh, I think I saw (and then forgot) that.  OK.   That's been on the backburned for a while...guess it's now front and center!

Do you know of any good walkthroughs on how to set this up given that I own a domain and want to self-host the mail server?

**Comment by MrPetovan** [comment]
I would discourage you to try to host your own mail server. Well, setting it up is easy, but the hard part is having your email actually reach their intended recipients, as most corporate email server owners (think Gmail, Outlook, ICloud, etc...) are very picky about the quality of the received emails to prevent spam.

If you have zero knowledge about working with an email server, it's easier to use a third-party mail service that allow custom domains like ProtonMail, Fastmail (that I use) or Tutanota.

**Comment by coamtaker618** [comment]
mmk, I have heard that.  While it's not a major concern for my usecase I can see it being enough of a headache on the times it DOES show up.

Maybe I'll keep that on the backburner then....

So for now it sounds like PHP Mailer is the easier way to go--any known good references for setting that up with Friendica?

**Comment by coamtaker618** [comment]
Also, is there any sort of forwarder that I can use? So I can setup something (mail relay? if that's the right term?) so that Friendica is always pointing to that and then if I want to switch from ProtonMail to Fastmail...I only switch that one thing (that I'm calling a mai relay) and not Friendica config and/or anything else I do this with?

**Comment by tobiasd** [comment]
You can use the phpmailer addon (https://github.com/friendica/friendica-addons/tree/develop/phpmailer) with any mail provider you trust your systems mail notifications with. Though you can also enable the securemail (https://github.com/friendica/friendica-addons/tree/develop/securemail) addon to get your notification mails gpg/pgp encrypted.

**Comment by coamtaker618** [comment]
Forgot to follow-up!

I installed phpmailer addon, added the info to the friendica config for mail info (weird that it lacks a GUI but hey--this works) & bam, email works!!)

Thanks for the help all :)
