### ISSUE TITLE
[frio] Contact conversation page shows double wrapping

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8672]
Ugh

<img width="687" alt="Screen Shot 2020-05-21 at 11 50 14" src="https://user-images.githubusercontent.com/925415/82577651-47f73780-9b59-11ea-9ec9-18bf2453b4a3.png">

**Comment by annando** [comment]
Hmm, I don't see what you are seeing, I guess. Can you point me to the problem?

**Comment by MrPetovan** [comment]
On timelines, posts have their own wrapping, we don't need the generic page wrapper. This is a regression because of a CSS simplification change I made recently. This page just needs to be excluded from the general case.

**Comment by annando** [comment]
What do you mean with "wrapping" here? (Possibly my brain is on standby since today is some christian holiday and I'm just trying to do something productive now)

**Comment by MrPetovan** [comment]
The light beige rectangles between the content and the background color/picture in my case.

**Comment by annando** [comment]
Ah okay. Hadn't seen it as a bug.

**Comment by MrPetovan** [comment]
This page used to look like the network page.
