### ISSUE TITLE
url rewriting with nginx? nginx support?

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#868]
Both [this guide](https://github.com/friendica/friendica/wiki/Running-Friendica-with-SSL) and [this guide](https://github.com/friendica/friendica/wiki/Nginx-Install-Guide) make reference to setting up a server with nginx, but the initial setup page throws an error regarding .htaccess files and URL rewrites, which is the Apache way to do it. Is nginx still supported, and if so, what's the right way to get set up with nginx?

**Comment by shaftoe** [comment]
I'm not entirely sure this should have been closed, maybe you want to check https://github.com/friendica/friendica/pull/3723
