### ISSUE TITLE
blocked accounts / follow-up settings

### ISSUE THREAD

**Issue by gravity-deleted** [friendica/friendica#8688]
Hi,

I have noticed two points in the user administration in the normal user account.

1. where can I find the blocked accounts? (Ok, actually you don't really need them either. I just noticed that).

2. if a user asks if he is allowed to follow, you have the possibility to follow him, or only allow him to follow.
If one permits that the account may follow, it is nevertheless listed in the following contacts. If I go to his page, I have however the possibility to follow. 
That is, partly it seems to work.

I hope you understand what I mean.

**Comment by MrPetovan** [comment]
Hi @gravity-deleted , I'm sorry I don't understand if there's an actual question you haven't figured the answer to already.

Just in case, you can find the accounts you blocked in the Contacts page, or by appending `/contact/blocked` to your base Friendica instance domain/path.

And I don't understand what doesn't partly work from the example you gave in the second point.

**Comment by gravity-deleted** [comment]
Excuse me. I'll try to explain it better.

1. I was looking for a button in the GUI. I use the theme "four". Since I couldn't find one, I thought it was overlooked. So I brought it up briefly. 

Thanks for the tip with the URL. But since I use the addon "Superblock" they are not listed there.
Probably my mistake. Sorry. I'll take a closer look at this.

But the important thing is the second point.

If I get a request that someone wants to follow me, I have two possibilities to agree to the request.

1. Agree and also follow.
2. agree but not follow.

If I choose the second point, the account is still counted among the accounts I follow.
That is then however not correct.

**Comment by MrPetovan** [comment]
Are you sure they are counted in your follows and not just your followers? How can you see this?

**Comment by gravity-deleted** [comment]
The display is different.

On my profile page on the left side the number of my contacts is displayed. There it is added to it.

On the page where the accounts are shown, which I follow, he is not included.

If I call up the account via /contact/, I have the possibility to follow him. Therefore I do not follow him.
But he was assigned to a group. And this function only works for accounts which I actively follow? Or?

Since he hasn't posted again yet, I can't tell yet if his posts will be displayed.

**Comment by MrPetovan** [comment]
Contact = Account you have any relationship with. They could be following you, you could be following them, or you could be mutuals.

The display on the contact page is accurate, if you have the possibility to follow them, this means you aren't following them currently. You won't get any of their posts in your network page.

**Comment by gravity-deleted** [comment]
Okay, thank you. Now I understand the meaning of the ad. Then everything is fine and I will close this spam here.

Thanks for the info.

**Comment by MrPetovan** [comment]
You're welcome!
