### ISSUE TITLE
Make like links one-way

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8691]
### Problem

Clicking on a like like switches the like status. However, display quirk may display a post with a like without it, so clicking on the Like link again actually removes the existing like instead of being ignored.

### Solution

Make like links one-way. We have the support for `action=like` and `action=unlike`, we just have to use them in displayed post and remove the toggle behavior.

**Comment by annando** [comment]
How would you remove a "like" or "dislike" then?

**Comment by MrPetovan** [comment]
The same way we do currently when receive a second like on the same post.

**Comment by annando** [comment]
Could you explain this? I saw the table in the PR and had no clue.

**Comment by MrPetovan** [comment]
Before using a truth table I had a complicated if/elseif structure with 4 different statements with duplicated code between them. I wasn't even sure it was accurately covering all the possible cases. Truth tables are used to design the simplest boolean logic expressions possible by listing all possible cases and their expected outputs, then coming up with boolean logic expressions based on the inputs for each output.

In this case, it gives a XOR to decide whether to delete the existing activity which is the simplest possible boolean logic form but whose use isn't evident just by reading it, so I attached the full truth table.

**Comment by annando** [comment]
I'm still too stupid to understand. Can you show in a screenshot how a like or dislike can be removed after the change?

**Comment by MrPetovan** [comment]
The same way they were before. What changes is the way the asynchronous call looks like.

Before:
- Add a like: `/like?itemid=12345&verb=like`
- Remove a like: `/like?itemid=12345&verb=like`

After:
- Add a like: `/like?itemid=12345&verb=like`
- Remove a like: `/like?itemid=12345&verb=unlike`

The advantage is that now that they are separate, we know exactly the intent of the call, which rules out the false positives that the toggle created.

Before, Friendica was sometimes showing a version of a post without a displayed like even though the like existed. Clicking on the like button would then remove the existing hidden like even though it wasn't the intent.

Now, even if Friendica doesn't display an existing like, clicking the the link again will have the expected intent: create a like. However, since the like already exists, nothing will actually happen.

**Comment by annando** [comment]
So nothing changes from a user's view?

**Comment by MrPetovan** [comment]
Nothing at all. It even fixes a UX problem caused by Friendica's inconsistent asynchronous display updates.

**Comment by annando** [comment]
Ah okay. I totally misunderstood.
