### ISSUE TITLE
Event items are created with network = unkn which prevents interactions with them

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8694]
### Steps to reproduce the problem

1. Create an event with just a title, no share, all defaults from form.
2. Visit event item `/display` page
3. Notice attendance buttons are missing

@annando What network should these items be created with? DFRN or AP?

**Comment by annando** [comment]
`dfrn` is appropriate. I guess this happened when I made my changes to the checks in the `item` class.

**Comment by MrPetovan** [comment]
Thanks!

**Comment by MrPetovan** [comment]
Worked!
