### ISSUE TITLE
Configuring processing of deleted users

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#870]
How long does it take for users in the section "User waiting for permanent deletion" to be deleted? Is this a setting that can be configured?

**Comment by Beanow** [comment]
More people have been confused about this. I think we should find a way to better explain this.

**Comment by vinzv** [comment]
Docs look clearly written to me now. Can we close this issue?

**Comment by annando** [comment]
I would like to delegate this decision to @tobiasd

**Comment by tobiasd** [comment]
The question is not if it is well written or not, but if it is written such that it describes the way accounts are deleted. To check this, @annando must read the docs to check.

**Comment by annando** [comment]
Is it ```Remove-Account.md```? Or is it something additional?

**Comment by MrPetovan** [comment]
Closed via #7623
