### ISSUE TITLE
ActivityPub ids with # symbol are not valid; resolvable

### ISSUE THREAD

**Issue by koehn** [friendica/friendica#8700]
### Expected behavior
Per the [ActivityPub specification](https://www.w3.org/TR/activitypub/#obj-id), IDs must either be `null` or:

>Publicly dereferencable URIs, such as HTTPS URIs, with their authority belonging to that of their originating server. (Publicly facing content SHOULD use HTTPS URIs). 

### Actual behavior
Friendica (and Mastodon; heading there next) ids include the fragment (`#`) section, which renders the portion of the ID beyond the fragment symbol as unresolvable by HTTP-conforming libraries such as [libcurl](https://ec.haxx.se/cmdline/cmdline-urls#fragment).

**Comment by annando** [comment]
AFAIK We are only doing this for the ID that encloses the content - and only the content ID is resolvable.

Concerning the `#` in the URL: Isn't that a regular part of a URL?

**Comment by koehn** [comment]
It is a regular part, but agents are not supposed to send it (and don't send it) as part of an HTTP request. Thus URLs with anything after `#` are not resolvable, and fall ouside the spec. 

If I run `curl -vH 'Accept: application/activity+json' 'https://mastodon.technology/@norztech#likes/836349#Like'` (a Mastodon id, but you get the idea)

`curl` sends:
```
> GET /@norztech HTTP/2
> Host: mastodon.technology
> User-Agent: curl/7.64.1
> Accept: application/activity+json
```

**Comment by MrPetovan** [comment]
Since it's a widespread usage of the `#`, is it possible that ids aren't used to resolve object in practice? Isn't there a `url` property that's used instead by the various non-compliant implementation?

**Comment by koehn** [comment]
I cannot imagine so, but in any case it's a violation of the AP specification. It could be that:

1. They're not resolving the URLs (likely); or
2. They're using a non-conforming HTTP client that is sending the fragment even though it shouldn't

**Comment by annando** [comment]
Well, AFAIK this is a URL that is not needed to be resolved. The content itself is resolvable.

**Comment by koehn** [comment]
So here's a situation where it would be super-handy to be able to resolve these URLs:

1. Bob Creates a Note and federates the Create to Jim and John using Bob's http-signature.
2. Jim replies to the Note and sends a Create using Jim's http-signature to Bob to federate
3. Bob's server sends Jim's Create to John, signed with Bob's http-signature

John's server is in a bit of a pickle: how to verify this activity is authentic? It's signed by Bob but the Actor is Jim. It would be really easy to just GET the message from Jim's server using HTTP.

But we can't because the ID is not resolvable as it contains a `#`. 

This wouldn't be an issue if either:
1. Jim sent the Create activity to John's server, signed with Jim's http-signature (vastly preferred by me, if you're curious); or
2. The ID was resolvable

**Comment by annando** [comment]
What I currently don't understand: You have the ID for the activity, that is something like https://pirati.ca/objects/ec054ce7-205e-ce54-03f0-5ad329982198#Create - and you do have the content under https://pirati.ca/objects/ec054ce7-205e-ce54-03f0-5ad329982198

You can always resolve the latter one.

**Comment by koehn** [comment]
How am I supposed to know how to decompose the IDs from a random server? Even if I do resolve the ID I don't get a Create activity, I get a Note.

**Comment by annando** [comment]
AFAIK every other implementer is resolving the content, not the activity. But I wouldn't had a problem creating some URL like https://pirati.ca/objects/ec054ce7-205e-ce54-03f0-5ad329982198?activity=Create that would create an activity for that post if this helps.

**Comment by koehn** [comment]
That would absolutely resolve the issue for me, and be compliant with the spec.
