### ISSUE TITLE
Community pages broken: no content

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8702]
### Expected behavior
The community pages should show posts.

### Actual behavior
There are no posts when I go to the community pages. I can go forward and backwards with the pager buttons. But no content is displayed.

### Steps to reproduce the problem
Well, go to the community pages.

### Friendica version
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Paging @annando , he's been working on items.

**Comment by AlfredSK** [comment]
Yep. It's caused by the "item-activity is removed" PR.

**Comment by MrPetovan** [comment]
Caused by #8690

**Comment by AlfredSK** [comment]
Works! 🎉 Thanks for fixing this. :-)
