### ISSUE TITLE
Admin settings site: additional form section breaks correct display of accordions

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8709]
### Expected behavior
The accordions on admin -> site should all have the same margin in frio.

### Actual behavior
The last accordion 'relocate instance' doesn't have the correct margin. I think this is caused by the additional form section in the template. If I move that accordion to the main form section everything looks good.

But I'm not sure if this additional form section for 'relocate instance' has been done on purpose. So, before I start providing a PR I want to ask about it. :-)

Additional question about the themes: The "problem" is only visible with frio. But the additional form section also exists in the main template. So, if I change it in frio should I also change it in the main template?

I also stumbled upon the HTML tag `<strong>` inside that accordion. I tried to fix that too but I miserably failed with that. I don't understand why that tag is visible on the page. I checked other PHP files with `<strong>` inside a `DI::l10n` line and it works there - but not with '/src/Module/Admin/Site.php'.

### Steps to reproduce the problem
![image](https://user-images.githubusercontent.com/3656054/83348428-c3f93880-a32c-11ea-87f5-64b1f61de894.png)

Go to admin -> site. Look at the accordions in frio.

### Friendica version you encountered the problem
2020.06

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
The additional form section for 'relocate instance' probably has the purpose to not accidentally submit it when another setting is changed and submitted.

**Comment by tobiasd** [comment]
Yes, I think that was the purpose of it.

**Comment by MrPetovan** [comment]
You're correct, would you like to try your hand at fixing this display quirk?

**Comment by AlfredSK** [comment]
Are you asking me, @MrPetovan ? I can try. But I cannot promise anything. I guess it needs to be fixed via CSS then?

**Comment by MrPetovan** [comment]
Yes, I'm asking you, I actually wrote my comment in an earlier tab that didn't display @tobiasd 's reply!

**Comment by AlfredSK** [comment]
Sorry. I'm unable to fix this. My knowledge about CSS is too limited and there's not enough time to learn more until the release.

**Comment by MrPetovan** [comment]
It's okay, thanks for trying!

**Comment by AlfredSK** [comment]
Thank you for your nice words. -> I feel better.
Looking at the solution in your PR... -> Oh! That easy? -> I feel completely stupid. ☺️

**Comment by AlfredSK** [comment]
Fixed by #8822

Somehow the auto-closing is broken. Closing...
