### ISSUE TITLE
Redirect routing

### ISSUE THREAD

**Issue by zeroadam** [friendica/friendica#8714]
### Expected behavior
Redirects or 'redir' requests are meant to be internal. "Normally they should only be "Friendica to Friendica"."

### Actual behavior
the /redir/ mechanism allows for open usage of redirections. This allows a friendica node to be used for phishing redirects as one example.

### Steps to reproduce the problem
construct a url using a friendica node, i.e. https://social.yl.ms/redir/574?f=1&url=https://apple.com and the user is sent to the apple.com site. Additionally the referrer is shows as the node.

### Friendica version you encountered the problem
Friendica 'Red Hot Poker' 2020.06-dev - 1351

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
git

### PHP version
7.4.6

### SQL version
MariaDB

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by annando** [comment]
I think we really have to rethink this functionality. I would like to strip it down to make it less misusable. Question only is: how?

**Comment by MrPetovan** [comment]
You have to write down exactly what this feature is supposed to be doing, and subsequently allow only these use cases with no insecure general fallback.

**Comment by zeroadam** [comment]
Thanks all! This seems to be doing the trick. Tested some based on my situation and now not redirecting as before! 🥇

**Comment by ben-utzer** [comment]
Can someone remove my url above? Or remove the url completely!

**Comment by MrPetovan** [comment]
I removed the domain.

**Comment by zeroadam** [comment]
Sorry @ben-utzer didn't mean to have your url out there like that.

**Comment by fabrixxm** [comment]
this thing need a release **asap**
hetzner has blocked our instance for this.

**Comment by MrPetovan** [comment]
Oof. You can apply the patch manually right now.
