### ISSUE TITLE
Bookmark BBCode don't render anymore

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8722]
See https://friendica.mrpetovan.com/display/735a2029-865e-d6a9-ea63-a60992169114

I've seen this behavior mostly with Twitter posts, either retweet or quote-tweets. I thought my twitter addon wasn't up to date but it shows like this even after a git pull.

**Comment by annando** [comment]
it is on some systems and on some others everything is fine. Can this be some OEmbed problem? I had deactivated it on my system but AFAIK you have activated it, haven't you?

**Comment by copiis** [comment]
I am using OEmbed and I have the problem

**Comment by annando** [comment]
Can you disable this for a test? It will not show immediate effects, but new posts should look differently.

**Comment by copiis** [comment]
Okay, i did it now

**Comment by SpencerDub** [comment]
I am also seeing this behavior. Friendica version **'Red Hot Poker' 2020.03 - 1338**.

**Comment by AlfredSK** [comment]
I don't allow Twitter embeds and I don't see that problem on my node.

**Comment by MrPetovan** [comment]
Found the problem, it's an ordering issue in the BBCode parser.

**Comment by copiis** [comment]
> but new posts should look differently.

OEmbed is the cause and old post that you edit and save looks good again.

**Comment by MrPetovan** [comment]
Alright, Twitter posts still don't render correctly after this fix.

**Comment by copiis** [comment]
Ups...
