### ISSUE TITLE
User handles are parsed inconsistently with trailing punctuation

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#8726]
This is a report based on [this post here](https://friendica.xanderwharts.us/display/000f629c-955e-2f46-136e-771435734637).

### Issue summary
When you mention a username in the message body followed immediately by certain punctuation characters, including `!]')`, the mention will not be replaced with a link or shortened handle unless the same username is repeated elsewhere in the message body without being followed by such punctuation.

This creates unexpected behavior when mentioning a user in the possessive; without an additional reference, a phrase like `@hypolite@friendica.mrpetovan.com's recent post` will not parse, displaying the string literally without fetching the link to the user's profile or their display name.

### Expected behavior
When usernames are written out, they will be parsed and replaced with links and a shortened handle, even when followed by punctuation.

### Steps to reproduce the problem
1. Create a new post in Friendica. Write a user's handle, followed *directly* by an apostrophe (`'`) or exclamation point (`!`). For example: `@hypolite@friendica.mrpetovan.com's name`
2. Submit the post. Notice that the username does not parse.
3. Create a new post (or edit the original) and repeat step 1. Before submitting the post, write the user's handle a second time, this time without any trailing punctuation. For example: `@hypolite@friendica.mrpetovan.com's name is @hypolite@friendica@mrpetovan.com`
4. Submit the new post. Notice that this time, both mentions have been parsed.
5. Repeat step 3, but wrap the unmodified handle in `[noparse]` tags: `@hypolite@friendica.mrpetovan.com's name is [noparse]@hypolite@friendica@mrpetovan.com[/noparse]`
6. Submit the new post. Notice that within the `[noparse]` tag, the handle was replaced with a link (forcing the other mention to be replaced), but the BBCode link was not parsed.
### Friendica version you encountered the problem
Friendica 'Red Hot Poker' 2020.03 - 1338

### Friendica source (git, zip)
I don't recall, sorry.

### PHP version
7.0.33-29+0\~20200514.36+debian9\~1.gbp126f6f

### SQL version
10.1.44-MariaDB-0+deb9u1 - Debian 9.11

**Comment by MrPetovan** [comment]
That's a nice find for an annoying behavior. Especially step 5 and 6 are concerning.
