### ISSUE TITLE
/network page doesn't load, getting 500 error or blank page

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8732]
### Expected behavior
Load network page, don't show HTTP 500 error.

### Actual behavior
Sometime HTTP 500 error, sometimes just blank page. 

### Steps to reproduce the problem
switch from 'master' to 'develop' branch and try to open /network, while having PHP version below running. 

### Friendica version you encountered the problem
 2020.06-dev

### More infos and log extract
After I updated Friendica to the current develop branch, when I try to access /network?order=post (the link in the very top left), I get this in httpd error log:

`[Fri Jun 05 11:40:29.087800 2020] [proxy_fcgi:error] [pid 2197:tid 140111354259200] [client 192.168.173.33:33960] AH01071: Got error 'PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 58`
`PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 60`
`PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 61`
`PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 63`
`PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 64`
`PHP message: PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 72'`

The PHP log doesn't tell more:

`[05-Jun-2020 11:50:48 Europe/Berlin] PHP Notice: Trying to access array offset on value of type null in /var/http/friendica/src/Module/NoScrape.php on line 63`

### Friendica source (git, zip)
git

### PHP version
PHP-FPM with PHP 7.4.6 

### SQL version
mariadb  Ver 15.1 Distrib 10.4.13-MariaDB

**Comment by MrPetovan** [comment]
In the future please report fatal errors like this in [the master issue](https://github.com/friendica/friendica/issues/8473).

**Comment by ben-utzer** [comment]
@MrPetovan OK, will do so. 

Addition: I found outstanding postupdates I think. 

I ran "bin/console postupdate" and it is now running for a while already. 
`Überprüfe ausstehende Update-Aktionen
Erledigt.
Ausstehende Post-Updates ausführen
..................................................`

Is this related?

**Comment by MrPetovan** [comment]
I found the source of the notices, but it wasn't related to the `/network` page issues. 500 errors should leave a trace in your web server log. Blank pages as well, although it's iffier.

**Comment by ben-utzer** [comment]
> 500 errors should leave a trace in your web server log. Blank pages as well, although it's iffier.

Last times I tried it was just empty page.

**Comment by ben-utzer** [comment]
Hmm still no access to /network, maybe I have to do something else.

**Comment by MrPetovan** [comment]
from https://github.com/friendica/friendica/issues/8473#issuecomment-639636627
> I get this here:
> 
> ```
> [05-Jun-2020 19:04:38 Europe/Amsterdam] PHP Notice:  Trying to access array offset on value of type null in /var/http/src/Content/Widget/SavedSearches.php on line 46
> [05-Jun-2020 19:04:38 Europe/Amsterdam] PHP Notice:  Trying to access array offset on value of type null in /var/http/src/Content/Widget/SavedSearches.php on line 47
> [05-Jun-2020 19:04:38 Europe/Amsterdam] PHP Notice:  Trying to access array offset on value of type null in /var/http/src/Content/Widget/SavedSearches.php on line 48
> [05-Jun-2020 19:04:38 Europe/Amsterdam] PHP Notice:  Trying to access array offset on value of type null in /var/http/src/Content/Widget/SavedSearches.php on line 49
> [05-Jun-2020 19:04:38 Europe/Amsterdam] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Core\Search::getSearchPath() must be of the type string, null given, called in /var/http/src/Content/Widget/SavedSearches.php on line 49 and defined in /var/http/src/Core/Search.php:321
> Stack trace:
> #0 /var/http/src/Content/Widget/SavedSearches.php(49): Friendica\Core\Search::getSearchPath()
> #1 /var/http/mod/network.php(145): Friendica\Content\Widget\SavedSearches::getHTML()
> #2 /var/http/src/LegacyModule.php(90): network_init()
> #3 /var/http/src/LegacyModule.php(59): Friendica\LegacyModule::runModuleFunction()
> #4 [internal function]: Friendica\LegacyModule::init()
> #5 /var/http/src/App/Module.php(271): call_user_func()
> #6 /var/http/src/App.php(571): Friendica\App\Module->run()
> #7 /var/http/index.php(42): Friendica\App->runFrontend()
> #8 {main}
>   thrown in /var/http/src/Core/Search.php on line 321
> ```

**Comment by ben-utzer** [comment]
My /network loads again!! Love you guys for this great help, thanks to @MrPetovan and @annando, this is one reason why I love Friendica!
