### ISSUE TITLE
Tweets display broken

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#8736]
Forwarded tweets are no longer displayed correctly.
V.2020.03 - 1338

![Screenshot_2020-06-06  ˈloma  Matthias E  ˈloma](https://user-images.githubusercontent.com/44441246/83939255-cf8ca980-a7db-11ea-9643-ea9653a3166b.png)

**Comment by copiis** [comment]
Twitter no longer allows Oembed. OEmbed must be deactivated in the admin area then it should work again

**Comment by MrPetovan** [comment]
It won't work exactly the same, though, they will appear as regular shared posts, not embedded tweets.

**Comment by MrPetovan** [comment]
Closed by #8725
