### ISSUE TITLE
[frio] Sort user list, select multiple users, then batch delete is not possible

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8743]
### Expected behavior
When going to /admin/users I can select multiple users and then go to the bottom and delete them all together. 

### Actual behavior
You can only select and delete multiple users at once as long as you do not change the sorting of the user list. 

### Steps to reproduce the problem
Go to /admin/user, then sort the users by date they signed up, then select 2 or more and scroll down, the delete and disable buttons are gone now. 

### Friendica version you encountered the problem
Current develop

### Friendica source (git, zip)
git 

### PHP version
PHP-FPM with PHP 7.4.6

### SQL version
mariadb Ver 15.1 Distrib 10.4.13-MariaDB

**Comment by MrPetovan** [comment]
Does this happen on both frio and vier?

**Comment by ben-utzer** [comment]
> Does this happen on both frio and vier?

Will check later. Does this happen for you too? 

Ah, I used Firefox.

**Comment by AlfredSK** [comment]
Happens here, too. Frio, Chromium. As soon as you change the sorting (in any way) the buttons for batch processing are gone.

Does NOT happen with vier.

**Comment by MrPetovan** [comment]
Thanks for the added details.
