### ISSUE TITLE
add contacts via dfrn_request utterly broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8746]
### Expected behavior
The 'dfrn_request' URL to add contacts is used rather seldom these days. But when it is used it should give the expected result.

### Actual behavior
The presented profile URL to follow is complete rubbish. 
Sometimes you get a relative 'redir' (!) URL as the profile URL to follow. And you end up with an error when you hit the button to confirm the process.
And sometimes you are on dfrn_request page for user A but the actual profile URL in the follow dialogue is for user B (on some random fediverse server).

### Steps to reproduce the problem
At first I had difficulties to reproduce that problem with my personal account. But a local user had reported the error on the support mailing list. Yes, we have a mailing list! ;-)
So I created a new test account and did some tests...

1. Login to the test account (I used an incognito window to exclude interferences with other sessions)
2. Go to a global directory page (dir.friendica.social or dir.libranet.de)
3. Look for some user from a develop node (could not reproduce with remote master users)
3. Hit on the follow buttons on the right side

### Some examples

![redir-contact](https://user-images.githubusercontent.com/3656054/83968016-6897ef00-a8c6-11ea-955b-fadb2a6b4cf8.png)

**That redir url redirects to some user on squeet.me!**

![redir-contact-3](https://user-images.githubusercontent.com/3656054/83968021-78173800-a8c6-11ea-86d1-419a20a060e5.png)

![redir-contact-4](https://user-images.githubusercontent.com/3656054/83968025-806f7300-a8c6-11ea-88ac-8597536984af.png)

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by annando** [comment]
It only happens when following via the directory?

**Comment by AlfredSK** [comment]
**...when following via 'drfn_request' urls.** 
I didn't find another way to trigger a follow via 'dfrn_request' except when using one of the directory sites.

**Comment by MrPetovan** [comment]
Can you please share the URLs that produced these strange displays?

**Comment by AlfredSK** [comment]
Example URL:
https://friendica.mrpetovan.com/dfrn_request/hypolite
...when I try to follow you from the directory.

**Comment by MrPetovan** [comment]
Now I can reproduce the issue and it gave me a different URL than in your screenshot???

**Comment by AlfredSK** [comment]
Yes. When I tried it again this morning to confirm the browser-URL I got a different result. On the day I opened this issue I could do it several times and I always got the same user profile URL. But this time it was a different one but a wrong one nonetheless. Mysterious. :-)

The biggest riddle is that 'redir' address in example 1. It should be `https://libranet.de/profile/wikipedia_de` or `wikipedia_de@libranet.de`.

**Comment by annando** [comment]
I hope that this weekend I can test it. I currently have some other tests running. I'm working on reducing the "Probe" calls. We really do them very often. This surely has some impact on other and our system.

**Comment by AlfredSK** [comment]
If you need some data, more info or database query results from me, please "@" me...

**Comment by MrPetovan** [comment]
The problem is weirder than I would have expected, fortunately the solution was a one-liner.

**Comment by AlfredSK** [comment]
Interesting explanation in your PR. From my experience and what the user who discovered the issue told me the contact request failed when the URL was a 'redir' URL (example 1).
I don't remember the exact error message that popped up in the info bubble. But it was something like "parameter 2 missing".

**Comment by MrPetovan** [comment]
Yes, I saw this variable was also used later in the template in a form input element. I was wrong about the display-only.

**Comment by AlfredSK** [comment]
Works like a charm now. :-) 🥳
