### ISSUE TITLE
@ Mentions don't work anymore, as well as ! (exclamation mark) 

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8756]
### Expected behavior
Mentions with @ or ! should cause the mentioned person to receive the message addressed to them. 

### Actual behavior
@user@example.com is just shown as normal text. 

### Steps to reproduce the problem
Write a post am mention me on Friendica, if you can not reproduce look for one of this posts:
https://social.yl.ms/display/e18176ef-845e-e10f-841b-263353934723

https://social.yl.ms/display/e18176ef-155e-e0fb-59ab-3c2541093754

### Friendica version you encountered the problem
Latest dev 

### Friendica source (git, zip)
git

### PHP version
Still same as last days. 😜

### SQL version
Same as some days before.

**Comment by AlfredSK** [comment]
Huzzah! 🎉

**Comment by ben-utzer** [comment]
Thanks for fixing it, I think it works again, did a git pull and mentions are with a link again.
