### ISSUE TITLE
Unable to load CSS

### ISSUE THREAD

**Issue by ehehdada** [friendica/friendica#8759]
### Expected behavior

Load CSS

### Actual behavior

Unable to load CSS: 
Refused to apply style from 'https://social.lucentinian.com/view/asset/jgrowl/jquery.jgrowl.min.css?v=2020.06-dev' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'https://social.lucentinian.com/view/asset/jquery-colorbox/example5/colorbox.css?v=2020.06-dev' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'https://social.lucentinian.com/view/asset/jquery-datetimepicker/build/jquery.datetimepicker.min.css?v=2020.06-dev' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'https://social.lucentinian.com/view/asset/perfect-scrollbar/dist/css/perfect-scrollbar.min.css?v=2020.06-dev' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### Steps to reproduce the problem

Open the website with Chromium based web browsers like Opera

### Friendica version you encountered the problem

master

### Friendica source (git, zip)

git

### PHP version

7.4.6

### SQL version

MariaDB 10

**Comment by ehehdada** [comment]
I had to execute ./autotest.sh but I didn't see any mention about this script in install.md

**Comment by MrPetovan** [comment]
Hi @ehehdada , when I open your node URL in my Chromium-based Vivaldi browser, all the stylesheets you mentioned load correctly. I checked each URL individually for their mime type return and it was `text/css` as intended.

Did you run Composer since you reported this issue? The HTML response would come from the file not existing and Friendica trying to show a page without success. Composer is tasked to import those files from the dependency repositories when Friendica is installed from git.

**Comment by ehehdada** [comment]
Thanks @MrPetovan to take a look at the problem! 

Here some other clues regarding the problem reviewing the date-time of the files:

1. The command `composer install --no-dev` was executed in other machine
1. In the production server, the repo was cloned and only the `vendor` folder was copied from the testing machine to the production server
1. After the command `./autotest.sh` was executed, the folder `view` was correctly populated with the missing files and solved the problem

`./autotest.sh` executed the `composer` command that is in the friendica repo, because the production server has no `composer` installed.

If the files were missing, the server didn't reply with 404 for these missing CSS files, but with something with the MIME type `text/html`.

**Comment by MrPetovan** [comment]
No, we use URL rewriting in Friendica so `https://friendica.install/module/parameter` will be transformed into `https://friendica.install/index.php?p=module/parameter` if and only if the path doesn't exist on the web server.

So `https://social.lucentinian.com/view/asset/jgrowl/jquery.jgrowl.min.css?v=2020.06-dev` is meant to load the file, but if it doesn't exist, the request will be transformed into `https://social.lucentinian.com/index.php?p=view/asset/jgrowl/jquery.jgrowl.min.css&v=2020.06-dev` which will return a 404 error, although with the MIME type `text/html`.

Interesting that you used `autotest.sh`, it is meant to bootstrap the unit tests, its use isn't recommended in production.

As for Composer, we ship a copy of the binary for just this case where it isn't installed on the server. You can find it in `bin/composer.phar`.

Did you have anything else to ask?

**Comment by ehehdada** [comment]
No more questions. Thank you very much @MrPetovan !
