### ISSUE TITLE
Failed to update contact record.

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8760]
### Expected behavior
Change of contact "Notification and privacy" should be possible. 

### Actual behavior
After reload failure "Failed to update contact record." is shown. 

### Steps to reproduce the problem
Go to a contact profile under /contact/nnnnnn and try to change "Notification for new posts" or "Hide this contact from others", it is not possible. 

### Friendica version you encountered the problem
latest dev with a pull from last night. 

### Friendica source (git, zip)
git

### PHP version
PHP 7.4.6

### SQL version
mysql  Ver 15.1 Distrib 10.4.13-MariaDB

**Comment by ben-utzer** [comment]
If someone, as me, really needs to deactivate the notifications for a contact, you can delete the contact and readd it after, then the notifications are off be default.

**Comment by MrPetovan** [comment]
I pulled the latest develop and wasn't able to reproduce this issue. You're getting this error because the query to update the contact failed. It just happens to feature [a field that was recently renamed](https://github.com/friendica/friendica/pull/8742). Are you sure your DB structure is up to date?

**Comment by ben-utzer** [comment]
I will check later today if the is some outstanding DB update from last days, I did manually run the command a week ago I think.

**Comment by ben-utzer** [comment]
In /admin I can see that database structure is 1354, is that answering the question? I can later on run the console command for DB update again.

**Comment by ben-utzer** [comment]
The command ´´´bin/console dbstructure update´´´ didn't return anything.

**Comment by ben-utzer** [comment]
It seems to have been an outstanding database update.

**Comment by ben-utzer** [comment]
Quick question, would it be a good idea to run `bin/console dbstructure update` after each daily update? I mean it wouldn't hurt?

**Comment by MrPetovan** [comment]
It doesn't hurt.
