### ISSUE TITLE
New quoted reshares are looking odd

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8764]
### Expected behavior
Quoted reshares should not look different. They should look consistent to other shares.

### Actual behavior
1. The icons for the 'network' and the 'link to source' are arranged vertically instead of horizontally. That looks inconsistent to me. The vertical arrangement doesn't look bad - not at all. But two different ways to display those icons are one too many in my eyes.

![new-quoted-reshares](https://user-images.githubusercontent.com/3656054/84535409-0dae2f80-acec-11ea-8474-1d025c3fda25.png)

2. The background of the content of the quoted post doesn't respect the opacity settings of frio. When I set the opacity to 80% the area of the reshared post is fully opaque. Well, it is open to discussion whether the new look is better or not - maybe I can get used to it... (edit, 2 days later: I think I like it)

### Steps to reproduce the problem
Look at quoted reshares. :-)

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Yes, the icons should be next to each other horizontally. I'm using the opacity setting and I haven't been bothered by shared posts not being transparent.

**Comment by AlfredSK** [comment]
@MrPetovan Hmm. It looks like those opaque background "cards" of the reshared posts are missing on my personal statuses stream (home icon). That causes an issue where the content has no left and right margin and is therefore reaching to the physical border of the screen of a mobile device.

**Comment by MrPetovan** [comment]
These are week-old posts, the markup is the previous one, but with the new CSS. Joy!

**Comment by AlfredSK** [comment]
Friendica Remix

**Comment by AlfredSK** [comment]
The issue with 'reshared content has no margin' only occurs on small displays. Doesn't happen on medium and large displays.
On the other hand the icons (network, link to source) are looking ok on small displays - but not on medium and large displays.

**Comment by AlfredSK** [comment]
Looks like the issue is solved. With new content the icons and the margins are looking good.
I think we can close this.

**Comment by AlfredSK** [comment]
Grrr. The wrong CSS for some reshares issue is still occuring from time to time:

https://libranet.de/display/0b6b25a8-125e-f76d-508a-975680433148

**Comment by MrPetovan** [comment]
Hmm, the post content (including the share) has been generated on a non-frio theme, which doesn't work as expected with the Frio theme.

**Comment by AlfredSK** [comment]
Aha. The local user is using vier, apparently. The original, reshared post is from Mastodon.

**Comment by foss-** [comment]
This entire UI has seen a rework since. Is this a problem in the current stable or RC build @AlfredSK ?

**Comment by AlfredSK** [comment]
I don't think so. Didn't notice the issue lately.
