### ISSUE TITLE
Categories are not showing up at the bottom of the post

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8766]
### Expected behavior
Categories should be displayed at the bottom of a post. In frio it is a green button linked to the category's stream. I'm pretty sure other themes have a textual link.

### Actual behavior
No matter if the admin has enabled or disabled the setting *admin - site - advanced - suppress tags* the buttons/links to the categories 
are missing.

### Steps to reproduce the problem
Enable option 'categories' in user settings
Disable option 'suppress tags' in admin settings
Write a post with (mentions, tags and) **a category**
Look at the bottom of the newly created post

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
The green button (frio) or the link to the category is displayed in the post's preview but not when it has been submitted.

**Comment by annando** [comment]
@AlfredSK can you check and then close it, if it works for you?

**Comment by AlfredSK** [comment]
Yes. Give me a minute. :-)

**Comment by annando** [comment]
This post is three minutes old, so you are overtime :grin:

**Comment by AlfredSK** [comment]
I know, I know.

**Comment by AlfredSK** [comment]
Works! The category is showing up at the bottom of the post and also in the Categories widget.

**Comment by AlfredSK** [comment]
Hmm. Is it expected that I only see the category at the bottom of the post when I look at the post locally?
I submitted a test post to a contact group. I can see the category locally. But one of the contacts who has received the post (on another RC node) cannot see the category. I'm not sure if this is expected or not.

**Comment by annando** [comment]
Yes, they are local.

**Comment by AlfredSK** [comment]
Ok.
