### ISSUE TITLE
Add correct Webp handling

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#8768]
### Expected behavior
Webp is a kind of video format that can replace gif. Friendica seems to convert those videos to JPEG. 

Friendica should not convert the Webp at all. Either keep it as a video file, proxy it locally as is or load it as remote content. 

### Actual behavior
Webp is converted to a statical image. 

### Steps to reproduce the problem
See here: https://social.yl.ms/display/ab868b8b-1e89-45c6-8959-272afb8a3230

Go to original post to see animated image. 

### Friendica version you encountered the problem
Current dev

### Friendica source (git, zip)
Git

### PHP version
Same as before 

### SQL version
Same as before. 

Can someone confirm that this is not working on her/his node?

**Comment by ben-utzer** [comment]
On squeet.me it is also not working I think, but it is different there, I think the server fails to convert it.

See here. https://squeet.me/display/ab868b8b-1e89-45c6-8959-272afb8a3230

**Comment by ben-utzer** [comment]
Not working with embedding and video BBCode as well, see here. 
https://social.yl.ms/display/e18176ef-955e-e53c-a12d-eb6333571876
