### ISSUE TITLE
[twitter] Likes on received tweets aren't forwarded to Twitter

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8778]
I noticed recently that likes I add on received Twitter posts via the connector add-on aren't forwarded to Twitter anymore, even after waiting for the worker to pick up the task.

Not sure if it's because of a change of Twitter API or a change in Friendica item handling.

Meanwhile, comments still are correctly forwarded.

**Comment by annando** [comment]
I just checked. It worked here without a problem. Best is to have a look at the log files, I guess.

**Comment by MrPetovan** [comment]
Thanks for the feedback.

**Comment by MrPetovan** [comment]
After enabling the log in Info level and filtering twitter messages I found this:
```
2020-06-19T23:08:49Z worker [INFO]: twitter_action 'like' send, result: stdClass Object
                    [message] => Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform
 {"worker_id":"4366221","worker_cmd":"ForkHook"} - {"file":"twitter.php","line":511,"function":"twitter_action","uid":"0a9aac","process_id":17403}
```
There are a couple problems with this, like the fact there no user feedback that it failed, we don't expect it to fail, and the log level when it fails is Info.

I contacted the Twitter support and I plan on improving the feedback from the addon.

**Comment by MrPetovan** [comment]
Wile waiting for the support answer, I looked around and apparently Twitter is demanding a callback URL for application offering "Sign In with Twitter" like the Friendica Twitter addon, which means that the authentication via code may not be available anymore. This would require adding a twitter addon module to handle the callback during authentication.

**Comment by MrPetovan** [comment]
I was wrong about the reason:
```
Thanks for reaching out. Your app was restricted for sending a large volume of unsolicited and/or repeat @mentions. This is prohibited by the Twitter Rules:

Spam: You may not use the Twitter service for the purpose of spamming anyone. What constitutes “spamming” will evolve as we respond to new tricks and tactics by spammers. Some of the factors that we take into account when determining what conduct is considered to be spamming are:

if you send large numbers of unsolicited replies or mentions;
if you send large numbers of duplicate replies or mentions;

Note that this behavior is not allowed regardless of whether or not it is automated. Per the Automation Rules if you are sending automated @mentions the recipient or mentioned user(s) must have requested or have clearly indicated an intent on Twitter  to be contacted by you.

As a next step please respond to this email listing the measures that you have taken to limit this behavior on your platform.
```
I have no idea why my single-user application was flagged so I requested more information about the kind of spam my application sent because the only behavior that has changed over the past 3 years is unprotecting my Twitter account.

**Comment by annando** [comment]
It's funny that it is working with my system, especially since it is used on servers with multiple users.

I'm all in for improving the handling of Twitter rejects and a new registration mode.

**Comment by MrPetovan** [comment]
The dialog was quickly interrupted by an answer from the Twitter support simply demanding I pledge to stop the spam behavior for my application to be reinstated, so I'll never know what caused it. I simply answered "I agree to stop this spam behavior" to get my app back up and running.

**Comment by MrPetovan** [comment]
My app has been restored, no further question asked.
