### ISSUE TITLE
[Diaspora] Relative links to Diaspora-local posts fail

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8781]
Abridged source:
```xml
<status_message>
  ...
  <text>[people of the world](/posts/2576978090fd0138ee4c005056264835)</text>
</status_message>
```
Result:
<img width="664" alt="Screen Shot 2020-06-16 at 14 12 07" src="https://user-images.githubusercontent.com/925415/84811797-6545e700-afdb-11ea-86f3-655146e1d00a.png">

Additional notes:
The source shows a labeled link but it got transformed into a link preview. I don't think it should happen with labeled links because content is effectively lost with the link label.

**Comment by annando** [comment]
This bug must be new. When receiving such a post, the Diaspora protocol stack has to check if a message with such an GUID does exist on the system. Otherwise it has to query the server from where we received this message. This server will then either serve us the content or direct us to the original server of that post.

**Comment by annando** [comment]
I just saw that it is something for Mr. RegExp. This check needed to be expanded:
https://github.com/friendica/friendica/blob/develop/src/Protocol/Diaspora.php#L1283

Just have a look at `/post/` vs. `/posts/`. I'm not totally sure, if `/post/` is correct - `/posts/` is.

**Comment by MrPetovan** [comment]
Indeed.

**Comment by MrPetovan** [comment]
Wait, this is only for `diaspora://` links. The regular expression on line 1293 should have taken care of it.

**Comment by annando** [comment]
Oh yeah, you are right.

**Comment by MrPetovan** [comment]
Probably found the issue: we are performing `add_page_info_to_body` before fetching the GUID.

**Comment by MrPetovan** [comment]
Also even if we performed `fetchGuid` before `add_page_info_to_body`, it doesn't replace the link in the body with an absolute one, so I'm back to square one.

**Comment by MrPetovan** [comment]
Hum, `add_page_info_to_body` probably shouldn't extract links with no scheme nor labeled links.

**Comment by MrPetovan** [comment]
The solution has been to rewrite most of the regular expressions that were used in the Page Info feature. They were written by someone who self-admitted their awkwardness using them.

The Page Info now explicitly looks for URLs at the end of the body, with a scheme, and during the removal of the link itself from the body, it keeps the label if it isn't the URL itself. This way we don't lose any user-supplied data, even if I expect some post displays to include shortened URL labels like `example.com/dfsd...`.

This rule can easily be dropped if it's too much of an inconvenience.

**Comment by tobiasd** [comment]
@utzer had shared a problem with diaspora* reshares; is this related?

https://forum.friendi.ca/display/e18176ef-745e-e9a9-5c67-1b7649383352

**Comment by MrPetovan** [comment]
Not directly. In this case it wasn't a link in the post body and wasn't transformed into a non-working link preview. Instead, is was a full-on share and was correctly processed.

However, it has to do with the transformation we perform on relative Diaspora-local links with absolute Friendica-local links, as a result we don't have the original source link anymore in the share box itself. Please open a separate issue.

**Comment by ben-utzer** [comment]
> Please open a separate issue.

Will do

**Comment by MrPetovan** [comment]
This works. Some labeled links have started to appear as text, even though most are shortened version of the link URL. I believe I will able to straighten this out in the next release.
