### ISSUE TITLE
Embed HTML into profile

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#8793]
Hi there,
Just wondering if it would be possible to allow people to Embed HTML such as video or music into one or more of their profile slots.  It would make the profile a lot more like a myspace page back in the day if you could and make it more lively.  PHP may prevent this though.  
Thanks!

**Comment by tobiasd** [comment]
You can use BBCode elements in the free-form profile information fields. So everything (I gues, only tested basic formatting, links and videos from Youtube) that can be used in postings to your profile wall can also be used in the free-form fields of the profile.

**Comment by anubis2814** [comment]
Is there a tutorial on that?

**Comment by anubis2814** [comment]
Actually figured it out, thanks!

**Comment by tobiasd** [comment]
No tutorial, but every node has the BBCode documentation at example.com/help/BBCode with BBCode snipplet and expected result in it.

**Comment by anubis2814** [comment]
Ok sorry, but in BBC is it possible to format so I can add spaces?  In some cases [pre] is used but I can't seem to use it.  Thanks

**Comment by MrPetovan** [comment]
What is the intended display? Maybe we are wrongly displaying spaces in pre-formatted BBCode tags.

**Comment by anubis2814** [comment]
Trying to use [pre]  Text  [/pre]  to produce "  Text  ", Instead it just ignores the spaces and treats them like they aren't there.  According to some places online they should work like this but maybe I'm not reading it right.

**Comment by MrPetovan** [comment]
Our BBCode parser is a little overzealous when it comes to spaces. For example, `[NotABBCodeTag] More text` will be converted to `[NotABBCodeTag]More text` by default and I believe you might be victim of the same trick. Would you please open an issue here about this problem?

**Comment by anubis2814** [comment]
Basically I just need a way to create white space

**Comment by anubis2814** [comment]
Sure will do, Thanks!
