### ISSUE TITLE
BBCode parser ignores white space

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#8800]
### Expected behavior
[pre] Text [/pre] to produce " Text "
### Actual behavior
[pre] Text [/pre] to produce "Text"
### Steps to reproduce the problem
Just put in the code
### Friendica version you encountered the problem
2020.03

From Mr Petrovan "Our BBCode parser is a little overzealous when it comes to spaces. For example, [NotABBCodeTag] More text will be converted to [NotABBCodeTag]More text by default and I believe you might be victim of the same trick. Would you please open an issue here about this problem?"

**Comment by MrPetovan** [comment]
Thanks for opening this issue!
