### ISSUE TITLE
Mastodon rss feeds can't be added as contacts.

### ISSUE THREAD

**Issue by skrlet13** [friendica/friendica#8807]
### Expected behavior

Mastodon RSS feed added as a contact so I can mirror its content.

### Actual behavior

Mastodon RSS feed isn't added as a contact, Message: The network type couldn't be detected. Contact can't be added.

### Steps to reproduce the problem

Try to add a Mastodon RSS as a contact (feed). It doesn't work.
If you probe the direction (changed for example):
```
Array
(
    [name] => https://example.com/users/user.rss
    [nick] => https://example.com/users/user.rss
    [guid] => 
    [url] => https://example.com/users/user.rss
    [addr] => user@example.com
    [alias] => 
    [photo] => https://myinstance.ex/images/person-300.jpg
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [baseurl] => https://example.com
)
```

### Friendica version you encountered the problem

2020.03

### Friendica source (git, zip)

git

### PHP version

PHP 7.4.7

### SQL version

mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment]
Hi @skrlet13 and thank you for the report!

**Comment by annando** [comment]
What is the use case for doing so?

**Comment by AlfredSK** [comment]
> ... so I can mirror its content

**Comment by MrPetovan** [comment]
Content can be mirrored with a regular Mastodon contact, but this is a bug regardless.

**Comment by AlfredSK** [comment]
No. You cannot set up a mirror for AP contacts.

**Comment by annando** [comment]
I have a bad feeling about this mirroring. I guess that in many cases this will lead to abandoned and unmaintained Friendica accounts that mirror every content to some other networks (like for example Twitter).
