### ISSUE TITLE
Adding contact can result in blank white page

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#8818]
2020.06-rc https://squeet.me
database 1354
post update 1350

### Reproduce
1. open https://squeet.me/contact
2. in the "Add new contact" field add contact info in the form of username@squeet.me of a user who also is on squeet.me
3. Click "Connect" button

### Expected behavior
Contact should be added.

### Actual behavior
Blank page https://squeet.me/follow?url=username%40squeet.me

![blank](https://user-images.githubusercontent.com/5708172/85923376-b59a3000-b88a-11ea-8293-329fd094c2a8.png)

**Comment by AlfredSK** [comment]
Possibly a white screen of death - PHP fatal error.
Pinging @annando

**Comment by MrPetovan** [comment]
Can't reproduce on my RC dev node.

**Comment by AlfredSK** [comment]
Me neither.
2020.06-rc

**Comment by foss-** [comment]
Odd that thsi is not reproducible as for me, in another test, the problem is reproducible also on pirati.ca
Wondering if this might be related to a certain state during contact approval and before the other user accepted the request.

**Comment by tobiasd** [comment]
squeet.me and pirati.ca are the tinkering nodes of @annando so he might find a solution with his current tinkering state of the code. Means it could well be a "local" problem to his tinkering nodes.

**Comment by annando** [comment]
You can reproduce this on pirati.ca as well? That's great, because squeet.me has a reduced logging.

**Comment by annando** [comment]
I tried following a pirati.ca account from another pirati.ca account. I did the same with a squeet.me account on squeet.me. I cannot reproduce the behaviour.

**Comment by foss-** [comment]
This came down to being a problem with ublock origin overblocking with its cosmetic filter. Disabling that setting the page returns to normal. I am at a loss, why that would block an entire page from loading. No custom filters set for squeet me.

![ublock origin](https://user-images.githubusercontent.com/5708172/85927771-872b4d80-b8a8-11ea-955e-5c10072ebb9b.png)

**Comment by MrPetovan** [comment]
So, nothing to do?

**Comment by foss-** [comment]
Not sure about that. There's quite a few users with ublock origin out there so would be good if things worked by default with ublock origin enabled. But if you think it is not worth the effort, let's close this issue.

**Comment by MrPetovan** [comment]
What exactly is blocked when you load that page with UBlock Origin? Can you open the developer console and see what requests are prevented from loading?

**Comment by annando** [comment]
I'm using uBlock origin as well - but don't experience that problem.

**Comment by foss-** [comment]
Firefox 77.0.1
This is the console output that is shown after clicking connect button (sorry it is in german):

```
Das Cookie “Friendica” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite follow
Das Cookie “Friendica” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite style.pcss
Das Cookie “Friendica” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite ping
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden.
```

**Comment by AlfredSK** [comment]
Maybe it depends what block-lists are active in uBlock Origin. I use the default lists for Germany and I don't have the issue.
I think I remember there was a list that makes troubles. But I cannot remember which one.

**Comment by foss-** [comment]
Good point. Unticked _EasyList_ and things still worked. Thought I had a match, but ticking that list again and again adding a contact, things are still working. Maybe an update of all lists brought them to a compatible state? Would be an interesting task of finding out the problematic blocklist and the entry on that list and than getting that removed from the list.

Closing this issue, as I do not see that happening with the time available here.
