### ISSUE TITLE
Twitter-Plugin: Retweets are displayed unpleasant 

### ISSUE THREAD

**Issue by PolynomialDivision** [friendica/friendica#8827]
Currently, if a retweet on twitter is published to friendica, they always have `[bookmark=` in it. Further, it seems that the author of the post is wrong.

Here is an example: 
- [Friendica](https://friendica.astatu.berlin/display/96794102-945e-f705-ec43-a62349883341)
- [Twitter](https://twitter.com/astaup/status/1276789514414022659)

**Comment by tobiasd** [comment]
What version of Friendica are you using?

**Comment by annando** [comment]
See https://friendica.astatu.berlin/friendica  - it is 2020.03. AFAIK we solved this in the RC.

**Comment by MrPetovan** [comment]
Thank you for your report, this issue is a duplicate of #8722 fixed by #8725
