### ISSUE TITLE
[frio] Add Ignore/Block author feature in post actions dropdown

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#8828]
Would it be possible to have an option to mute someone in the global or local feed so they would never show up? The best we have right now it to ignore thread.  I use these community feeds a lot less because I can't clean them out of people I don't care about.  Sorry if this is a duplicate request, I couldn't find one similar, 
Thanks!

**Comment by MrPetovan** [comment]
I believe you can go in the contact page of each individual authors and mark them as "ignored". If it doesn't mute them from the local community feed, at least the top-level posts, [I believe it should](https://github.com/friendica/friendica/issues/4960#issuecomment-648562208).

**Comment by MrPetovan** [comment]
As a general piece of information, node administrators can mute individual accounts in the community pages from the command-line with the following command synopsis:
```
$ bin/console globalcommunitysilence <profile_url> [-h|--help|-?] [-v]
```

**Comment by anubis2814** [comment]
No, I don't want the individuals muted globally, this should be listed more as an enhancement.  Say someone is in the feed and posts only in German and I don't know German.  If this was like facebook, instead of having to go to the person's profile and mute them, I would go to the "more" dropdown menu on the post and have an option to hide/ignore their posts.  Basically make that a post option.

**Comment by anubis2814** [comment]
Also I can't seem to find an ignore option.

**Comment by AlfredSK** [comment]
I think the available option were already mentioned. But as a summary...

As a user you can ignore someone to suppress the display of all their posts. When you use the theme frio you find the option by clicking on their avatar and select the 'view contact' icon. Then (on the contact page) you find the ignore option in the top-right 'action menu'.
If you want to get rid of individual posts of a user (no general muting) you can select 'remove locally' from the '...more' menu of that post. 

As a node admin you have the possibility to remove the posts of a user from the community pages the way @MrPetovan explained (via command line interface -> console). This removes the user from the community pages for everyone (users and visitors).

Btw. "ignore thread" only mutes the thread. Means you don't get any further notifications about subsequent comments.

**Comment by MrPetovan** [comment]
So the post option would ignore the author directly? Sounds good, Twitter already has this feature where you can mute or block someone from any of their post.

**Comment by anubis2814** [comment]
Thanks, I found out how to do that.  And yes MrPetrovan that's what I wanted, thanks!  Just ignore them from the more dropdown instead of having to find the ignore function.

**Comment by AlfredSK** [comment]
> So the post option would ignore the author directly? Sounds good,...

The idea to move the ignore/block options to the more menu is a good idea because at the moment they're hard to find.
But it somehow breaks the current systematic separation between 'post actions' (bottom of post + more menu) and 'contact actions' (hovercard + contact page).
I already had the idea to add ignore/block actions directly to the contact's hovercard. But the space is limited there and too many icons in the hovercard may look ugly.

**Comment by MrPetovan** [comment]
On Twitter for example you can't follow/message someone from the post dropdown so there still is a separation of concerns.

**Comment by tobiasd** [comment]
This is a frio specific problem I think. In vier, the mute and block actions are already in the contact action drop-down menu you see when clicking on the profile picture.

**Comment by MrPetovan** [comment]
Thanks for the extra info about vier!

**Comment by tiotrom** [comment]
Yup would be nice to have the same option in Frio. Should we open the issue on the theme's github page if there is any? Do you guys maintain that theme or?

**Comment by MrPetovan** [comment]
We do maintain the frio theme ourselves, it's one of the five official themes and soon to be default one for new install.

**Comment by anubis2814** [comment]
I wish the other themes were equally customizable

**Comment by foss-** [comment]
Post actions dropdown in This is Friendica, version 2024.03-rc that is running at the web location https://pirati.ca. The database version is 1556/1556, the post update version is 1550/1550.

This is resolved right? Can the issue be closed? polite ping @anubis2814 

![2024-03-09 frio](https://github.com/friendica/friendica/assets/5708172/1ce3e046-e8ec-49e3-bf5f-945d253a78d2)

**Comment by anubis2814** [comment]
I tend to close things when they have come out on the stable release so that people have had time to test them out and agree that that its what they wanted.

**Comment by anubis2814** [comment]
Yes thank you, I didn't realize I has requested this, since it was 4 years ago.  I will close it out
