### ISSUE TITLE
Unseen Notifications not showing up

### ISSUE THREAD

**Issue by SeanHowardRoadmunk** [friendica/friendica#8829]
### Expected behavior

https://convenient.email/api/friendica/notifications returns notifications where seen=0

### Actual behavior

https://convenient.email/api/friendica/notifications only shows me seen notifications

### Steps to reproduce the problem

curl -u 'Basic:Auth' https://convenient.email/api/friendica/notifications|jq

### Friendica version you encountered the problem

This is Friendica, version 2020.03 that is running at the web location https://convenient.email. The database version is 1338, the post update version is 1329.

### Friendica source (git, zip)

git

### PHP version

$ php --version
PHP 7.0.33-0+deb9u7 (cli) (built: Feb 16 2020 15:11:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u7, Copyright (c) 1999-2017, by Zend Technologies
$ 

### SQL version

$ mysql --version
mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
$

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by MrPetovan** [comment]
Fixed by #8837
