### ISSUE TITLE
The last update failed. Please run "php bin/console.php dbstructure update" - won't work

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8830]
### Expected behavior
Database update runs and finishes without interaction 

### Actual behavior
Get this message in /admin

> The last update failed. Please run "php bin/console.php dbstructure update" from the command line and have a look at the errors that may appear in the console and logfile output.

### Steps to reproduce the problem
Not sure

### Friendica version you encountered the problem
Current RC

### Friendica source (git, zip)
git

### PHP version
PHP 7.4.x

### SQL version
mariadb Ver 15.1

### More info
I did run the ./bin/console dbstructure update even with -f, but it just takes a few seconds, no output on the console nor in the log. And the message in /admin still there since 2 weeks or so. 

I think the update is finished and the messages is wrong. 

Under /admin/dbsync it says "No failed updates." and when I click "Check database structure" it shows "Database structure update 1354 was successfully applied.". 

@annando didn't have time to help, so I thought I try the broader/different audience here.

**Comment by ben-utzer** [comment]
No ideas? Anyone?

**Comment by annando** [comment]
We solved this now, haven't we?

**Comment by utzer** [comment]
> We solved this now, haven't we?
Yes, still not clear what caused the problem, but it was just solved by running the commands once more.
