### ISSUE TITLE
Calendar entries should always direct to your own server & Update notification

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#8836]
When somebody on an other server creates a calendar entry, that is shown in your calendar, the link on the calendar entry will always lead you to the other server. 

In my view of usability this is a big mistake. It should always lead to your own server, because
1. Sometimes those creator servers are not reachable or very slow
2. The "Magic Dingsi" is not working and you get a white page

And when you attend a calendar entry, you should get a notification, when the creator is changing it. (maybe this is already  implemented, but I never noticed)

**Comment by MrPetovan** [comment]
I don't think this should be handled this release. It raises important philosophical questions about whether we should always refer to the source node or not, what it means to private items stored on remote servers, and new features (notification).

**Comment by tobiasd** [comment]
Mmh... the broken condition of following the notification to the remote server was discovered during the RC phase, and the introduction of why it does not work seems to have happened during the last development cycle as _it worked before_. Hence I put the 2020.06 milestone on it.

**Comment by annando** [comment]
I think that we should provide both links - like with posts.
