### ISSUE TITLE
Support incoming HTTP Signatures with "hs2019" algorithm

### ISSUE THREAD

**Issue by vpzomtrrfrt** [friendica/friendica#8839]
### Expected behavior
HTTP Signature handling should accept signatures with algorithm "hs2019". All other values are deprecated in current drafts of the spec: https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00

### Actual behavior
Only "rsa-sha256" and "rsa-sha512" seem to be accepted, based on the code in `src/Util/HTTPSignature.php`. Attempting to send a new-style signature results in "Invalid HTTP signature, message will be discarded." message in logs

### Steps to reproduce the problem
- Send an activity to an inbox with a Signature header using the "hs2019" algorithm.

### Friendica version you encountered the problem
2020.03

### Friendica source (git, zip)
archive

### PHP version
7.4.6

### SQL version
mysqld 10.1.30-MariaDB

**Comment by annando** [comment]
I'm bad at reading and understanding of specifications. Especially with RFC I have a hard time with. Are there any blog posts, articles, ... that explain the differences? Are there already implementations where one can test the own implementation?

**Comment by vpzomtrrfrt** [comment]
The algorithm field was deemed a security risk because malicious actors could set it to a weaker algorithm in their forged requests. "hs2019" isn't really an algorithm so much as a token indicating that the algorithm should be determined from the key.

Now what _that_ means, I'm not sure, other implementations appear to have just hardcoded SHA256, which seems not good

**Comment by vpzomtrrfrt** [comment]
I've started a thread on SocialHub to discuss this in general: https://socialhub.activitypub.rocks/t/state-of-http-signatures/754

**Comment by MrPetovan** [comment]
Thank you for the report. However the provided document is a draft and I'm not sure we should start implementing drafts given how "slow" we generally are at following specs.

**Comment by vpzomtrrfrt** [comment]
It would indeed appear that there is no defined way to specify the signature algorithm for a publicKey, and the consensus so far is just to always use rsa-sha256

**Comment by MrPetovan** [comment]
So it's just a matter of accepting `hs2019` as `rsa-sha256` ?

**Comment by vpzomtrrfrt** [comment]
Technically no, but practically yes

**Comment by annando** [comment]
@vpzomtrrfrt in the linked discussion you also wrote something about `created` and `expires` - and also about this `keyId` stuff. Should this be considered then as well?

**Comment by MrPetovan** [comment]
> Technically no, but practically yes

Thank you, that's exactly what I thought.

**Comment by vpzomtrrfrt** [comment]
Support for (created) and (expires) is also a requirement for the current drafts, so it would be nice to do that as well
