### ISSUE TITLE
Wrong data cached for Mastodon profile probe

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8844]
Original forum thread: https://libranet.de/display/0b6b25a8-145f-00f0-a05a-f33746577567

I have tested all three provided Webfinger addresses in the thread in `/follow`, and each time the data was returned from cache with the following traits:
- Default data including `network = unkn`,
- `subscribe` is the expected `https://<Mastodon host>/authorize_interaction?uri={uri}` template from the Webfinger.

Probing from the admin `Probe Address` tool returns the expected data with `network = apub` because it skips the cache. Then the cache is updated with the correct information and it isn't possible to get a faulty response anymore.

What strikes me as odd is that we specifically avoid to store a probe result in cache if `newtork = unkn`. And yet in all three cases the cached data featured `network = unkn`. I wasn't able to find any other spot where the wrong probe result could have been cached disregarding the `network` value.

I have no explicit evidence because I wasn't able to reproduce a wrong probe that could have been stored in cache, but I suspect this is a regression caused by #8813 . However there are many others contenders since probing has been heavily modified this version. Paging @annando

**Comment by annando** [comment]
After the weekend I can have a look at it,

**Comment by MrPetovan** [comment]
So libranet.de has to be updated and more tests have to be conducted with newly created Mastodon accounts, otherwise the cache will likely be correct.

**Comment by annando** [comment]
The trick with my changes is that I do the probing by not using the cache. This should fix all issues.

**Comment by MrPetovan** [comment]
I didn't understand the changes in depth, did you have to duplicate any code from probing?

**Comment by AlfredSK** [comment]
Updated it is.

**Comment by annando** [comment]
There is no code duplication or anything similar. I just made a change that I want to make in the next release anyway: Replacing most `Probe::uri` with `Contact::getByURL` - which also calls `Probe::uri`. The significant change is that the probing is now called with the parameter set to ignore the cache.

**Comment by annando** [comment]
And then I realized the real reason for the issue ... It had been a really longstanding bug. See the PR.
