### ISSUE TITLE
HTTP Signature: Add support for (created) and (expires)

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8845]
> Support for (created) and (expires) is also a requirement for the current drafts, so it would be nice to do that as well

_Originally posted by @vpzomtrrfrt in https://github.com/friendica/friendica/issues/8839#issuecomment-653916186_

HTTP Signature draft: https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00

**Comment by MrPetovan** [comment]
So, multiple things:
- We are the second PHP project on GitHub to have added support for `hs2019`
- We have a rigid signing/verifying process with no abstraction whatsoever and no tests, which makes any changes hazardous
- We probably should use an external library for this kind of task, but they require [using PSR-7 messages](https://github.com/friendica/friendica/pull/8364) which we don't just yet.

And even [the most advanced HTTP Signature PHP library](https://github.com/liamdennehy/http-signatures-php) forked off [the most popular one](https://github.com/99designs/http-signatures-php) is only just [compatible with the version 10 of the draft](https://github.com/liamdennehy/http-signatures-php/releases/tag/10.0.1).

So I'm going to put this back on the shelf until we have PSR-7 messages, then we can replace our HTTP Signature scaffolding by something more robust.

**Comment by MrPetovan** [comment]
Blocked by #8364

**Comment by MrPetovan** [comment]
Blocked by #4090

**Comment by annando** [comment]
There seems to be an issue with Lemmy concerning the two fields. It seems as if the needed changes are minimal. I applied some logging to my local system and subscribed to some Lemmy groups to check this.
