### ISSUE TITLE
bin/console user delete - User has already been marked for deletion.

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#8846]
Hi!

With the current 2020.06-rc version bin/console user delete doesn't reset anymore the date when deleted a second time, which is a great improvement! :-) 

However, I think it would be nice when it wouldn't state "User has already been marked for deletion." when it is used with "-q" option, because it's no longer "quiet" when there is still an output. 
YMMV, though... just an idea... :)

**Comment by MrPetovan** [comment]
I wasn't aware of a `-q` flag in the first place.

**Comment by MrPetovan** [comment]
Ha, I see, it's more like a `--non-interactive` or `-y` flag.

**Comment by ingoj** [comment]
Hmm, yeah, well... to be more verbose... each week my cleanup_friendica.sh script runs... it uses bin/console user list active -c 10000 to output the users... then it checks the last login date and deletes users that haven't logged in since 7 months and deletes them. When it does that, it complains about already deleted users, generating a mail to me where (last time happened) all lines consisted of those "already marked for deletion"... it's not really annoying but maybe not correct as well and when there are like 200 lines of this you can easily oversee something important. 

So, my first idea was this issue with the "-q" option not working properly. But afterwards I thought that the problem may even exist before: "bin/console user list active" maybe shouldn't list accounts that are already marked for deletion, right?

**Comment by MrPetovan** [comment]
Definitely, so two changes:
- rename the misleading `-q` option in `user delete`
- filter users marked for deletion `in `user list active`.
