### ISSUE TITLE
HTTP Signature: Allow header values without quotes

### ISSUE THREAD

**Issue by vpzomtrrfrt** [friendica/friendica#8847]
### Expected behavior
HTTP Signature parsing should support parsing values without quotes. According to the spec, each sig-param can be _either_ a quoted-string or a token, where "token" means /[!#$%&'*+\-.^_`|~0-9A-Za-z]+/

### Actual behavior
As seen in `src/Util/HTTPSignature.php`, Friendica appears to be requiring quotes for each value in the Signature header

### Steps to reproduce the problem
- Send an ActivityPub activity to an inbox with a Signature header that doesn't use quotes for all values
- Friendica logs "Invalid HTTP signature, message will be discarded."

### Friendica version you encountered the problem
59c42a92

### Friendica source (git, zip)
git

### PHP version
7.4.7

### SQL version
10.1.30-MariaDB

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by annando** [comment]
@MrPetovan since this possibly includes regular expressions, I would like to delegate this to you :grin:

**Comment by MrPetovan** [comment]
I figured.
