### ISSUE TITLE
Pasting a photo into a comment

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#8848]
This should be listed as an improvement.
I mostly copy and paste photos when say posting cross platforms.  However there is no mechanism to do in Friendica to do that.  With BBcode and markdown being the key way of posting this may take several more upgrades to get to that point, but it would make friendica more user friendly if there was an option for this.  As it is I either have to use mastodon and repost (trying to get my admin to install the activitypub mirror so it will mirror mastodon) or use twitter which will mirror post. Just wondering if this is even possible in the near future. Thanks!

**Comment by MrPetovan** [comment]
I've never seen pasting image in forms, but I just noticed it in the GitHub comment textarea. I assume that at some point we'll use a all-in-one third-party library at some point that will support both dropping and pasting.

**Comment by schmaker** [comment]
I think this issue is safe to close
![image](https://github.com/friendica/friendica/assets/14954032/913c7ef6-3887-4117-befe-3977ff26d0fe)

**Comment by anubis2814** [comment]
Yes, this has fit the request perfectly.   Posted in 2020 the platform is almost a completely different place.
