### ISSUE TITLE
Decrease info-bubbles display-time from 10 to 5 seconds

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#885]
We live in a fast moving world. 10 seconds is a long time for a quick info bubble welcoming the user or saying "you've been logged out". I propose decreasing that to 5 seconds which should be more than enough, especially considering that most notifications are very brief.

**Comment by tobiasd** [comment]
This is fixed now in the develop branch of friendica for the default themes and the two frost themes which have a separate main.js file. If you are using another theme that has it's own main.js file you have to change the time there manually from 10000 to 5000 milliseconds.
