### ISSUE TITLE
AP Follow Accept has invalid ID

### ISSUE THREAD

**Issue by vpzomtrrfrt** [friendica/friendica#8857]
### Expected behavior
The Accept activity should contain the follow's ID in the object field.
### Actual behavior
The ID is just a number?
```
  /* snip */
  "id": "http://testfr.localhost/activity/c555f07d3c25ef37",
  "type": "Accept",
  "actor": "http://testfr.localhost/profile/somegroup",
  "object": {
    "id": "9",
    "type": "Follow",
    "actor": "http://localhost:7575/users/Carson",
    "object": "http://testfr.localhost/profile/somegroup"
  },
  "instrument": {
    "type": "Service",
    "name": "Friendica 'Red Hot Poker' 2020.06-rc-1355",
    "url": "http://testfr.localhost"
  },
  "to": [
    "http://localhost:7575/users/Carson"
  ],
  /* snip */
```
### Steps to reproduce the problem
- Create a Community Forum
- Follow the profile from another service (I used Pleroma)
### Friendica version you encountered the problem
e5269c56

### Friendica source (git, zip)
git

### PHP version
7.4.7

### SQL version
10.1.30-MariaDB

**Comment by MrPetovan** [comment]
If you must know, this is the database Id of the contact you've been asking to follow. In this case it would be the contact id of the forum account.

Thank you for the report!

**Comment by MrPetovan** [comment]
I looked into it for a short while, but I'm out of my depth without a full Follow/Accept example. Referring to @annando

**Comment by annando** [comment]
@vpzomtrrfrt thanks for your report! This bug only happened with contacts that automatically accept incoming requests, which isn't the default. So it went unrecognized for some time.
