### ISSUE TITLE
Frio - upload image freeze

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#8868]
### Expected behavior

On firefox desktop, I try to upload a photo : [this one](https://www.peppercarrot.com/0_sources/0ther/artworks/hi-res/2020-05-09_Saffron-steampunk-clothes_by-David-Revoy.jpg) ; 

after a few second I should be uploaded and I wish to to use it in my post.

### Actual behavior

Loading icon is present but nothing happens. In my web console I can see the following message :

``` 
SyntaxError: expected expression, got '<' 
ajaxupload.js:2
    _getResponse https://friendica.valvin.fr/view/js/ajaxupload.js?v=2020.06-rc:641
```
Note that other smaller picture can be uploaded without issue.
### Steps to reproduce the problem

Compose a new post using Frio Theme and the ajax composer. Go to Browser and Upload the photo provided upper.

### Friendica version you encountered the problem

2020-06-rc ; but i'm wondering if it is a new issue. 

### PHP version

7.3.19

### SQL version

MariaDB 10.3

**Comment by MrPetovan** [comment]
The error means that an Ajax request meant to return Javascript code returned HTML instead. You would need to inspect the page where the upload is happening in the Network tab, ignore the "ping" calls and note the calls showing up when an image is uploaded.

**Comment by AlfredSK** [comment]
I tried it too. Worked here with the provided image. If 'ajax composer' is the frio post modal window then I couldn't confirm the issue. Image upload was successful.
PHP 7.4, storage: file system, 2020.06-rc

**Comment by AlfredSK** [comment]
A smaller image worked? Just to be sure... what is the setting 'max. image size' in `admin panel` > `site` > `file upload` showing?

**Comment by valvin1** [comment]
I did check file upload on friendica and php but it was ok. 

Regarding network tab it is on the reverse proxy side : 

![image](https://user-images.githubusercontent.com/1267915/87255151-a15c5280-c488-11ea-965c-ca777331bf10.png)

Obvious that the process don't stop and show an error message. So issue is on nginx side.

**Comment by valvin1** [comment]
I confirm it was nginx configuration issue :) maybe a nice error message when it happens could help to understand btw i close the issue.
Thanks for the help.

**Comment by MrPetovan** [comment]
Hum, this would be up to the used library, which I'm not sure has a public issue tracker.
