### ISSUE TITLE
Contact managment menu is cut off when displayed for a contact at bottom of browser page

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#887]
This is maybe not easy to reproduce but 100% reproducible if you have enought contacts in your contacts list
- go to YourUserName > Contacts
- make sure you have enough contacts so they fill the browser window (I have 7 rows of contacts, 6 contacts per row)
- if I then click the rectangle to show the contact management overlay menu the problem is that that menu always gets attached to the bottom of the contact

What happens: The new overlay menu is out of sight in the browser window or cut off and the user first has to scroll down. scrolling down is only possible with the move in the overlay menu since otherwise the menu will disappear and scrolling further down then won't be possible since the user already has reached the end of the webpage

What is expected to happen: if displaying the overlay menu for the last contacts row, it should display over the contact and not below the contact to avoid this very unfriendly navigation glitch

**Comment by Beanow** [comment]
For reference, this problem displayed in Vier:
![Dropdown issue on last line](http://ss.oscp.info/2015-01-24_19-38-52.png)
_^ The last options are off-screen_

It is possible to reach them if you scroll while the menu is open. But it's definitely annoying to do.

**Comment by foss-** [comment]
This is a vier specific issue, which no longer is the default theme in friendica. 

The issue is persisting, but with no maintainer for vier, there is little chance of this getting addressed. Closing.

![1](https://github.com/friendica/friendica/assets/5708172/d2f6a957-247d-4633-97f2-4bbca817d524)
