### ISSUE TITLE
Friendica upgrade to 2020.07  failed. User and all posts are gone

### ISSUE THREAD

**Issue by seraphyn** [friendica/friendica#8873]
### Expected behavior
Have an upgrade and cheer the news

### Actual behavior
Upgraded and tried an upgrade of the database.
Quit with:
`friendica$ bin/console dbstructure update
[Error] Call to undefined method ReflectionType::getName()`

Homepage shows at the userpage:
```
#0 /www/htdocs/w00e78f0/friendica/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content(Array)
#1 [internal function]: Friendica\Module\Profile\Index::content(Array)
#2 /www/htdocs/w00e78f0/friendica/src/App/Page.php(332): call_user_func(Array, Array)
#3 /www/htdocs/w00e78f0/friendica/src/App/Page.php(388): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#4 /www/htdocs/w00e78f0/friendica/src/App.php(576): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#5 /www/htdocs/w00e78f0/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#6 {main}
```
### Steps to reproduce the problem
used the git way, like the years before, switched from master to stable

### Friendica version you encountered the problem
 Version 2020.07
database 1355 , Post-Update-Version 1329.

### PHP version
PHP Version 7.3.17-nmm1

Tried a reinstall with tar.gz and a backup of the db. 
Give me same problems.

**Comment by seraphyn** [comment]
The Mailfunction from friendica sends me this mail:
Fehler beim Ändern der Datenbank aufgetreten
`ALTER TABLE `temp-tag` DROP INDEX `PRIMARY`, DROP INDEX `tag`, ADD `id` int unsigned NOT NULL auto_increment COMMENT '', ADD `name` varchar(96) NOT NULL DEFAULT '' COMMENT '', ADD `url` varbinary(255) NOT NULL DEFAULT '' COMMENT '', ADD PRIMARY KEY(`id`), ADD UNIQUE INDEX `type_name_url` (`name`,`url`), ADD INDEX `url` (`url`), COMMENT = 'tags and mentions', DEFAULT COLLATE utf8mb4_general_ci;`

**Comment by annando** [comment]
Are you using MariaDB, MySQL or some other flavour? From which Friendica version are you trying to update?

**Comment by seraphyn** [comment]
Update is directly from previous master Version via git.

### DBMS Serverversion
 Server-Version: 5.7.28-nmm1-log - (Ubuntu) 
### PHP
Datenbank-Client Version: libmysql - mysqlnd 7.4.5
PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
PHP-Version: 7.4.5 
### Provider
All-inkl.com

Install atm Version 2019.12 via tar.gz with the backup of the database before.
It takes hours to import the database from the shell again via mysql.

**Comment by seraphyn** [comment]
Still wating.
Hangs at maintencance and the message: 
> Dienst nicht verfügbar
> 2020-07-14 09:50:46 UTC: aktualisiere Tabelle item

**Comment by MrPetovan** [comment]
Can you please run `php --version` on your command line?

**Comment by annando** [comment]
Can you execute `show processlist;` in the MySQL console?

**Comment by tobiasd** [comment]
Thanks for reporting @seraphyn I've added a note about this issue in the release notes.

**Comment by seraphyn** [comment]
> Can you please run `php --version` on your command line?

 php --version
PHP 7.4.5 (cli) (built: Apr 20 2020 12:23:03) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.0, Copyright (c) 2002-2020, by ionCube Ltd.

**Comment by seraphyn** [comment]
Site is up again.
No Posts available.
Version is  2019.12

**Comment by seraphyn** [comment]
> Thanks for reporting @seraphyn I've added a note about this issue in the release notes.

I used PHP7.3 for friendica and now 7.4

**Comment by seraphyn** [comment]
> Can you execute `show processlist;` in the MySQL console?
> 
> Do you know if you can change to MariaDB? This would make things easier.

I'm running this one since years on All-inkl.com, I could try to change their ... ;)
I think I should set up a VPS for this one. Will install a Debian machine with LAMP and test it there again.
Think this will speed up some things. 
It's the first update that breaks the installation.

**Comment by seraphyn** [comment]
> show processlist;

mysql> show processlist;
+--------+----------+-----------+----------+---------+------+----------+------------------+
| Id     | User     | Host      | db       | Command | Time | State    | Info             |
+--------+----------+-----------+----------+---------+------+----------+------------------+
| 238227 | d0192e9a | localhost | d0192e9a | Sleep   |    1 |          | NULL             |
| 240409 | d0192e9a | localhost | d0192e9a | Sleep   |    0 |          | NULL             |
| 240845 | d0192e9a | localhost | d0192e9a | Query   |    0 | starting | show processlist |
+--------+----------+-----------+----------+---------+------+----------+------------------+
3 rows in set (0,00 sec)

**Comment by MrPetovan** [comment]
I asked the PHP version because `ReflectionType::getName()` has been introduced in PHP 7.1. Not sure why you would get this error with either PHP 7.3 or 7.4.

**Comment by AlfredSK** [comment]
> My posts aren't available. All the other ones from the universe are there.

That can happen because the postupdate isn't finished yet.

**Comment by seraphyn** [comment]
> > My posts aren't available. All the other ones from the universe are there.
> 
> That can happen because the postupdate isn't finished yet.

Had a look today. No Post from me available.

**Comment by annando** [comment]
You are using MySQL from Oracle and sadly not MariaDB. MariaDB does support some stuff that improves the database update a lot. We had coded a workaround for the problem. But when the update fails then you are stuck like you currently are. Your data isn't lost, but the tables had been moved to "temp-...".

**Comment by seraphyn** [comment]
Install a dedicated debian vps with PHP 7.4 , mariadb and Apache2 atm.
Then I try to use the backup again.
Will bring further information later.

**Comment by seraphyn** [comment]
Installed, with the backup, updated the DB, and it's allready running.
`root@fr:/var/www/html/friendica# sudo -u www-data bin/console dbstructure update
ALTER IGNORE TABLE `item` MODIFY `private` boolean NOT NULL DEFAULT '0' COMMENT 'distribution is restricted';`
It's forwarding me to the profile and 
Page have 404 with 
Not Found

The requested URL was not found on this server.
20 Minutes later white page, url is maintenance.
No errors in the Logs. Only in 404 in the access-Logs

**Comment by seraphyn** [comment]
I close the issue once.
I will invest time again later, which unfortunately was not available at the moment

**Comment by john11smith** [comment]
I'm having the same problem. Upgrade from 'Red Hot Poker' 2020.03 - 1338 to any version using the archive method.

**Comment by annando** [comment]
@john11smith please have a look if any database processes are still running with `show processlist;` in the mysql console.

If nothing is running, please execute `bin/console dbstructure update` and if that is done without any errors, please execute `bin/console dbstructure update -f`.

And if this done, please have a look at your friendica log file for entries with "DB Error" in it.

**Comment by john11smith** [comment]
> @john11smith please have a look if any database processes are still running with `show processlist;` in the mysql console.
> 
> If nothing is running, please execute `bin/console dbstructure update` 
Nothing was running with exception of show processlist itself. After `bin/console dbstructure update` many errors, first is:
Error 1005 occurred during database update:
Can't create table `name_friend`.`post-category` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by john11smith** [comment]
@annando thanks for the quick reply. Nothing was running with exception of show processlist itself. After `bin/console DB structure update` many errors, first was:
```
Error 1005 occurred during database update:
Can't create table `name_friend`.`post-category` (errno: 150 "Foreign key constraint is incorrectly formed")
```
This time tried version Friendica 2020.09-1. PHP Version 7.2.34, MariaDB Server 10.3.25

**Comment by annando** [comment]
@john11smith can you have a look if the table `tag` exists on your system? That message normally appears when a foreign key is created and the related table doesn't exist. This shouldn't happen and isn't reported by now, but you never know ...

As a backup you also could paste the content of `database.sql` to the mysql console. In that file there are all the commands that needed to create the datatbase. It doesn't delete tables, it just creates them if they aren't existing.

**Comment by john11smith** [comment]
@annando table tag exists.
problem with running commands database.sql
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'text COMMENT '',
`closeness` tinyint unsigned NOT NULL DEFAULT 99 COMMENT '',...' at line 112
```
lines are (starting from 107)
```
	`unsearchable` boolean NOT NULL DEFAULT '0' COMMENT 'Contact prefers to not be searchable',
	`sensitive` boolean NOT NULL DEFAULT '0' COMMENT 'Contact posts sensitive content',
	`baseurl` varchar(255) DEFAULT '' COMMENT 'baseurl of the contact',
	`gsid` int unsigned COMMENT 'Global Server ID',
	`reason` text COMMENT '',
	`closeness` tinyint unsigned NOT NULL DEFAULT 99 COMMENT '',
```

**Comment by annando** [comment]
Weird. I don't see an SQL error there. In fact this file is automatically checked with every build since it used to set up the automated testings. How good are you administration skills? Can you try to pin it down to the exact cause?

You could also try to split the `database.sql` into single files per table and run it separately. I fear that these steps are the only possibility to find the reason. And though it seems that you are currently the only one with this problem, this of course could also mean that you are the only one who reported it and many other had given up. So we should have a deep look at it.

**Comment by john11smith** [comment]
@annando Yes, there is no error, if commands given line by line or in little chunks would be no error. Apparently in copy-pasting transferred over internet complex commands process, parts of commands get lost. Anyway, after creating tables manually result would be 0 rows affected. The problem is not database creating, but something else. Originally why I started digging, my first problem was - when press on **Home** tab error appears:

```
Not found

User not found.

#0 /var/home/c-panel_account/public_html/web.com/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content(Array)
#1 [internal function]: Friendica\Module\Profile\Index::content(Array)
#2 /var/home/c-panel_account/public_html/web.com/src/App/Page.php(331): call_user_func(Array, Array)
#3 /var/home/c-panel_account/public_html/web.com/src/App/Page.php(387): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#4 /var/home/c-panel_account/public_html/web.com/src/App.php(560): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#5 /var/home/c-panel_account/public_html/web.com/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#6 {main}
```
I've tried also not just upgrading, but also new install, the same problem with versions Friendica 2020.09-1 and 2020.07 but 2020.03 works fine.

**Comment by annando** [comment]
I have a feeling where this does come from. Could you directly update to the current RC and activate `'pdo_emulate_prepares' => true,` in the local.config.php in the `database` section (where the database name is defined)

I guess that your MySQL server stumbles upon the foreign keys that we introduced this year.

**Comment by john11smith** [comment]
@annando not sure what directly update supposed to mean? If update using git method it cannot be done, because the node is running on reseller hosting, not vps.
v2020.12RC is not available via archive, so I have tried to update from v2020-03 to v2020-09-1 using the archive files like described here [https://friendi.ca/2020/09/24/friendica-2020-09-1-hotfix-release/](https://friendi.ca/2020/09/24/friendica-2020-09-1-hotfix-release/) 
But after copying `config/local.config.php` added line `'pdo_emulate_prepares' => true,` in the database section, but the result was the same as always. And I don't think it should help, because that line is included in v2020-09-1 `local-sample.config.php` and gets copied to `local.config.php` automatically during fresh install, but the problem would be still there.
I think nobody else encounters that problem because everybody uses git. My node is not aware of any more 2020.03 nodes. All other nodes are on newer versions available only via git, like 2020.12-rc 2020.12-dev. Or there are many just 2020 without any more numbers.

**Comment by annando** [comment]
Can you have a look at the friendica log file for entries with "DB Error" in it? I'm convinced that you are running into this problem: https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared

**Comment by john11smith** [comment]
@annando it can be the same problem, but how it helps me? So the solution is to move to VPS? Shouldn't node work on shared hosting? Version 2020.03 works somehow.
Enabled  debugging, errors like these:
```
2020-12-19T21:14:09Z index [ERROR]: DB Error {"code":1146,"error":"Table 'account_frnd.owner-view' doesn't exist","callstack":"DBA::selectToArray, vier_community_info, vier_init, Page::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`blocked` = 0 AND `publish` = 1) ORDER BY `register_date` DESC LIMIT 0, 9"} - {"file":"Database.php","line":668,"function":"p","uid":"1e3747","process_id":28160}
2020-12-19T21:14:09Z index [ERROR]: DB Error {"code":1146,"error":"Table 'account_frnd.verb' doesn't exist","callstack":"DBA::selectFirst, Verb::getID, ping_init, LegacyModule::runModuleFunction, LegacyModule::init, call_user_func, Module::run, App::runFrontend","params":"SELECT `id` FROM `verb` WHERE (`name` = 'http:\/\/activitystrea.ms\/schema\/1.0\/follow') LIMIT 1"} - {"file":"Database.php","line":668,"function":"p","uid":"3b6181","process_id":30880}
2020-12-19T21:14:09Z index [ERROR]: DB Error {"code":1146,"error":"Table 'account_frnd.verb' doesn't exist","callstack":"DBA::insert, Verb::getID, ping_init, LegacyModule::runModuleFunction, LegacyModule::init, call_user_func, Module::run, App::runFrontend","params":"INSERT INTO `verb` (`name`) VALUES ('http:\/\/activitystrea.ms\/schema\/1.0\/follow') ON DUPLICATE KEY UPDATE `name` = 'http:\/\/activitystrea.ms\/schema\/1.0\/follow'"} - {"file":"Database.php","line":771,"function":"e","uid":"3b6181","process_id":30880}
2020-12-19T21:14:09Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'item.vid' in 'where clause'","callstack":"DBA::p, Item::select, Item::selectForUser, ping_init, LegacyModule::runModuleFunction, LegacyModule::init, call_user_func, Module::run","params":"SELECT `item`.`uid`, `item`.`uri-id`, `item`.`wall`, `item`.`uri-id` AS `internal-uri-id`, `item`.`uid` AS `internal-uid`, `item`.`network` AS `internal-network`, `item`.`psid` AS `internal-psid` FROM `item` STRAIGHT_JOIN `contact` ON `contact`.`id` = `item`.`contact-id` AND NOT `contact`.`blocked` AND ((NOT `contact`.`readonly` AND NOT `contact`.`pending` AND (`contact`.`rel` IN (2, 3))) OR `contact`.`self` OR `item`.`gravity` != 0 OR `contact`.`uid` = 0) STRAIGHT_JOIN `contact` AS `author` ON `author`.`id` = `item`.`author-id` AND NOT `author`.`blocked` STRAIGHT_JOIN `contact` AS `owner` ON `owner`.`id` = `item`.`owner-id` AND NOT `owner`.`blocked` LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = 1 LEFT JOIN `user-contact` AS `user-author` ON `user-author`.`cid` = `item`.`author-id` AND `user-author`.`uid` = 1 LEFT JOIN `user-contact` AS `user-owner` ON `user-owner`.`cid` = `item`.`owner-id` AND `user-owner`.`uid` = 1 WHERE (`item`.`unseen` AND `item`.`uid` = 1 AND NOT `item`.`origin` AND (`item`.`vid` != '0' OR `item`.`vid` IS NULL)) AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`) AND (`user-author`.`blocked` IS NULL OR NOT `user-author`.`blocked`) AND (`user-author`.`ignored` IS NULL OR NOT `user-author`.`ignored` OR `item`.`gravity` != 0) AND (`user-owner`.`blocked` IS NULL OR NOT `user-owner`.`blocked`) AND (`user-owner`.`ignored` IS NULL OR NOT `user-owner`.`ignored` OR `item`.`gravity` != 0) "} - {"file":"Database.php","line":668,"function":"p","uid":"3b6181","process_id":30880}
```

**Comment by annando** [comment]
On a shared hoster you cannot change the database settings. Do you have shell access?

**Comment by john11smith** [comment]
@annando Yes, I have shell access.
Today I tried to create missing tables. Here is the result:

` CREATE VIEW `tag-search-view` AS SELECT
.......
ERROR 1146 (42S02): Table 'niosseug_frnd.post-tag' doesn't exist`
`CREATE VIEW `owner-view` AS SELECT
........
ERROR 1054 (42S22): Unknown column 'contact.manually-approve' in 'field list'`

**Comment by annando** [comment]
I have the feeling as if this is a "step by step" task and isn't done by executing a single command.

The first step should be to ensure that all tables exist. This can be done by separating the commands from the `database.sql` per table. If there is an error telling something about foreign keys then remove the lines with `FOREIGN KEY` in it. This should then have created all needed tables.

So the next step is then to execute `bin/console dbstructure update` and to check for the first error to occur. And if the system is complaining about missing fields, please insert them by hand. This shouldn't happen, since the system is self healing. But something is weird on your system. I still think that this could be a problem with the database server configuration. This will be easier with the upcoming release where the setting I described earlier (`pdo_emulate_prepares`) started to work.

**Comment by john11smith** [comment]
@annando I was really struggling with step-by-step, because double tabs in places like that:
`	FROM `register`

`			INNER JOIN `contact` ON `register`.`uid` = `contact`.`uid``
were confusing database, so I removed them using `sed "s/^[ \t]*//" database.sql > database_notab.sql`
It allowed me to create the majority of tables without problems. But still stuck on a table
`DROP VIEW IF EXISTS `owner-view`;
CREATE VIEW `owner-view` AS SELECT`
...
`ERROR 1054 (42S22): Unknown column 'contact.manually-approve' in 'field list'
`

**Comment by annando** [comment]
Question is, what `bin/console dbstructure update` now tells. Because this command should update the `contact` table.

**Comment by john11smith** [comment]
@annando `bin/console dbstructure update` generates messages like:
```
ALTER IGNORE TABLE `contact` ADD FOREIGN KEY (`gsid`) REFERENCES `gserver` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER IGNORE TABLE `clients` ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER IGNORE TABLE `2fa_app_specific_password` ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER IGNORE TABLE `2fa_recovery_codes` ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER IGNORE TABLE `apcontact` ADD FOREIGN KEY (`gsid`) REFERENCES `gserver` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER IGNORE TABLE `attach` ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER IGNORE TABLE `auth_codes` ADD FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER IGNORE TABLE `contact-relation` ADD FOREIGN KEY (`cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
```
Another error shortly appeared on admin information overview `http://frnd.nioss.eu/.well-known/host-meta is not reachable on your system. This is a severe configuration issue that prevents server to server communication. See the installation page for help`
Also, I noticed that in database view mentioned before `owner-view` is a field URL with a link to `http://domain.name/profile/user_name` but on the server the actual folder `profile` is missing at all.

**Comment by john11smith** [comment]
@annando Looks like I have managed to locate the problem, with debug logging at notice level enabled. Looks like the same as [https://github.com/friendica/friendica/issues/8550](https://github.com/friendica/friendica/issues/8550). Will be posting updates there.
```
2020-12-22T18:32:05Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, networkThreadedView, network_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent, Page::run","params":"SELECT * FROM `network-thread-view` WHERE (`uid` = 1) ORDER BY `commented` DESC LIMIT 0, 40"} - {"file":"Database.php","line":668,"function":"p","uid":"667ca8","process_id":2224420}
2020-12-22T18:32:05Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, vier_community_info, vier_init, Page::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`blocked` = 0 AND `publish` = 1) ORDER BY `register_date` DESC LIMIT 0, 9"} - {"file":"Database.php","line":668,"function":"p","uid":"667ca8","process_id":2224420}
2020-12-22T18:32:05Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, networkThreadedView, network_content, update_network_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent","params":"SELECT * FROM `network-item-view` WHERE (`uid` = 1 AND `unseen` = 1) ORDER BY `commented` DESC LIMIT 100"} - {"file":"Database.php","line":668,"function":"p","uid":"8af6a4","process_id":2224420}
2020-12-22T18:32:07Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectFirst, User::getOwnerDataById, Profile::load, Status::content, Index::content, call_user_func, Page::initContent, Page::run","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"} - {"file":"Database.php","line":668,"function":"p","uid":"0e97e0","process_id":2224420}
2020-12-22T18:32:07Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, vier_community_info, vier_init, Page::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`blocked` = 0 AND `publish` = 1) ORDER BY `register_date` DESC LIMIT 0, 9"} - {"file":"Database.php","line":668,"function":"p","uid":"0e97e0","process_id":2224420}
```
