### ISSUE TITLE
Pinned posts override privacy permissions

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#8882]
I've discovered that pinning a post appears to override its permissions, making it visible beyond the intended audience.

### Expected behavior
A pinned post retains its permissions.

### Actual behavior
A pinned post is visible to the public.

### Steps to reproduce the problem
1. Create a post. Limit the audience of that post to a specific user or group.
2. Pin the post.

### Friendica version you encountered the problem
Friendica 'Red Hot Poker' 2020.03 - 1338

### Friendica source (git, zip)
Don't recall.

### PHP version
7.0.33-0+deb9u8

### SQL version
10.1.44-MariaDB-0+deb9u1

**Comment by MrPetovan** [comment]
I have no clue how permissions are factored in for items. I defer to @annando

**Comment by annando** [comment]
@SpencerDub can fetch the latest version and try again?

**Comment by MrPetovan** [comment]
Considering this closed.

**Comment by SpencerDub** [comment]
@annando 
Oh, sorry. Fetching versions is hard for me in my server setup, since I rely on YunoHost packages. 😕

**Comment by MrPetovan** [comment]
It's all good, this issue can be reopened if you don't witness improvement after you update to the next release.
