### ISSUE TITLE
Update successful / old version number still displayed

### ISSUE THREAD

**Issue by gravity-deleted** [friendica/friendica#8884]
### Expected behavior

Successful display of the new version number

### Actual behavior

Update with git and install the new files.
No error message. git also informs you that everything is up to date.

But the admin overview still shows the 2020.03 version.

### Steps to reproduce the problem

Update with git. (no error message)
bin/composer.phar install (no error message)

The addons were also updated.

After checking the Admin Overview, try to update again with Git reported that everything is up-to-date.

### Friendica version you encountered the problem

**Friendica 'Red Hot Poker' 2020.03**

### Friendica source (git, zip)

git

### PHP version

7.3.20

### SQL version

mysqlnd 5.0.12-dev

**Comment by MrPetovan** [comment]
Please switch the the `stable` branch, we've abandoned the `master` branch this version.

**Comment by MrPetovan** [comment]
@annando @tobiasd We should either bring the `master` branch to `stable` or remove it completely because in the current state it is confusing.

**Comment by tobiasd** [comment]
Then bring it to stable. And maybe add a note for the admin panel to switch the branch to `stable`.

**Comment by MrPetovan** [comment]
We can't know what git version they are currently using. The simplest would be to delete the branch. Admins wouldn't be able to mistakenly update it and believe they are on the latest version.

**Comment by annando** [comment]
We could keep the "master" branch for one version cycle and remove them after this. In the meantime we can communicate with the admins. This current change had been really spontaneously.

**Comment by gravity-deleted** [comment]
> @annando @tobiasd We should either bring the `master` branch to `stable` or remove it completely because in the current state it is confusing.

It works! Thanks!

Could I have read somewhere that the one branch is abandoned?

I would certainly support there being a Stable Branch which is clear.

I got confused for a second there.

**Comment by gravity-deleted** [comment]
> Please switch the the `stable` branch, we've abandoned the `master` branch this version.

It works! Thanks!

Could I have read somewhere that the one branch is abandoned?

> @annando @tobiasd We should either bring the `master` branch to `stable` or remove it completely because in the current state it is confusing.

I would certainly support there being a Stable Branch which is clear.

I got confused for a second there.

**Comment by MrPetovan** [comment]
I've now brought the `master` branch to the `stable` branch, we'll delete it next release in a couple months.

**Comment by MrPetovan** [comment]
> Could I have read somewhere that the one branch is abandoned?

In the release notes: https://github.com/friendica/friendica/releases/tag/2020.07

**Comment by AlfredSK** [comment]
...and on our blog: https://friendi.ca/2020/07/12/friendica-red-hot-poker-2020-07-released/
...and on the Friendica News channel: https://forum.friendi.ca/display/39bbe52aace3446df91167b111ad83c31654bfd2
...and on our Twitter account: https://twitter.com/FriendicaNews/status/1282403870526844930

...to name a few. ;-)

**Comment by gravity-deleted** [comment]
Who can read is clearly at an advantage! :)

Thanks for the help. I'm gonna practice my reading.

**Comment by tobiasd** [comment]
Yes ;-) but it is also a problem of how to write such information. Maybe I should add a "**Important**: ..." at the beginning of the "Updating using git" section as TL;DR bulletin for people who just skim the text.

**Comment by gravity-deleted** [comment]
> Yes ;-) but it is also a problem of how to write such information. Maybe I should add a "**Important**: ..." at the beginning of the "Updating using git" section as TL;DR bulletin for people who just skim the text.

Basically -> RTFM !

Only in this case I wanted to update as soon as possible to solve two other problems.

And since I don't use any extensions which require special attention, I have indeed only skimmed. Definitely my mistake, only I really didn't expect that the "Master" branch would be changed.

Anyway.

However, I would agree that in such a case a big "warning" would be great.
