### ISSUE TITLE
Frio: "permissions" in post composer is uncapitalized on mobile

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#8885]
In version 2020.03 - 1338, when using the Frio theme on mobile, if you go to the "Permissions" tab of the post composer, "permissions" is entirely lowercase.

It is properly capitalized in the list (when viewing it from other tabs), but uncapitalized when on that specific tab.

Screenshot to illustrate:
![2020-07-15 - Frio permissions](https://user-images.githubusercontent.com/4674927/87585709-544ccc00-c694-11ea-9613-5d2c071b356e.png)

**Comment by MrPetovan** [comment]
Looks like
```css
.dropdown-mobile-jot > button {
    text-transform: capitalize;
}
```
or a translation update in `en-US` for the word `permissions`.

**Comment by SpencerDub** [comment]
> That or a translation update in `en-US` for the word `permissions`.

I currently see this in [/view/lang/en-us/strings.php](https://github.com/friendica/friendica/blob/develop/view/lang/en-us/strings.php), line 92:

```
$a->strings["permissions"] = "permissions";
```
What would updating this look like? Adding a line? Capitalizing one or both of these?

I can make the edit, not a problem, I just want to avoid breaking stuff or causing unintended consequences. 😬

**Comment by AlfredSK** [comment]
Translations (like en-us) are done on Transifex, not directly on GitHub.
https://www.transifex.com/Friendica/friendica/

**Comment by MrPetovan** [comment]
What @AlfredSK said, these files you found are generated from the translated strings we export from Transifex shortly before each release.

**Comment by tobiasd** [comment]
OTOH the base string is all lowercase, so the assumption by the translator that it is meant that way is reasonable for me. For me there are two questions

1. is that string only used in that one location
2. if we change the `permissions` to `Permissions` in the source, will there be different strings, which is important for not only this case.

And regarding (q1) yes it is only this one location where the word `permissions` is translated as single word. So it would be save to update the translation for that string and thus not breaking all the other translations.

**Comment by MrPetovan** [comment]
It appears to be an inconsistency in the source strings. It had been solved with CSS on Frio until now but it could be fixed in the source material like you suggested. It amounts to replace `DI::i10n()->t('permissions')` with `DI::i10n()->t('Permissions')`

**Comment by annando** [comment]
I don't like this CSS "fix", because it is incorrect in other languages to use caps at the beginning of each word.

**Comment by MrPetovan** [comment]
Me neither but replacing source strings means that translators have to redo work that they already did.

**Comment by AndyHee** [comment]
I've now corrected the US and GB translations.

**Comment by MrPetovan** [comment]
Thanks, we still need to replace the source string.

**Comment by AndyHee** [comment]
Okay, no problem.

**Comment by walstonjd** [comment]
> Thanks, we still need to replace the source string.

I'd like to help with that if possible. Could you bring me up to speed?

**Comment by MrPetovan** [comment]
Yes. Translation strings can be found in the code as `DI::l10n()-t('<translation string>')`. It’s a metter of replacing the translation string `permissions` by `Permissions`.
