### ISSUE TITLE
Certain tags not working after update

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#8896]
After I upgraded my server to 2020.07 I noticed some tags stopped working. These specific tags:

- don't return posts by tag search (but same posts can be found by these strings in full-text search)
- don't appear in users' tag clouds
- don't appear in tag suggestions during post composition
- don't get added to tag list under the post

This applies to both existing and newly created posts.

So far I found two of these problematic tags: #Москва and #ТакиеДела

All of these tags are Cyrillic but I don't think it is related to language because other Cyrillic tags work as expected.

Example post: https://friends.deko.cloud/display/d0446be5-385f-131a-1a27-500497036827 (contains two problematic tags and one normal one)

Related discussion: https://friends.deko.cloud/display/ec054ce7-965f-1316-6568-873476378313

Any suggestions? I noticed it too late to roll back to pre-update backup and I'd really like to at least "reset" these tags if it is impossible to fix them (i.e. be able to use them for at least newly made posts).

Friendica, version 2020.07, database version is 1355, post update version is 1350, upgraded by git from stable branch, PHP 7.4.8, MariaDB 10.3.22.

**UPDATE:** Just tried the same tags on mordor.social - they don't work there either.

**Comment by SpcCw** [comment]
Okay, I found tag table in the database and as I see tags that don't work are missing from it. Ones that do work are present.

```
select * from tag where name like 'Москв%';
+-------+------------------+-----+
| id    | name             | url |
+-------+------------------+-----+
| 64490 | Москва2020       |     |
+-------+------------------+-----+
```

As I understand it, tags used to be in term table and should be in tag table now but these didn't migrate for some reason?

**Comment by SpcCw** [comment]
When something is posted with problematic tags, the following appears in the logs (DEBUG level)
```
2020-07-18T21:42:41Z index [INFO]: Check for tags {"uri-id":1445061,"hash":"#@!","callstack":"Item::insert, Item::addShadow, Item::insert, item_post"} - {"file":"Tag.php","line":214,"function":"storeFromB$
2020-07-18T21:42:41Z index [INFO]: Found tags {"uri-id":1445061,"hash":"#@!","result":[["#[url=https:\/\/friends.deko.cloud\/search?tag=\u0422\u0430\u043a\u0438\u0435\u0414\u0435\u043b\u0430]\u0422\u0430\$
2020-07-18T21:42:41Z index [ERROR]: DB Error  - {"file":"Database.php","line":769,"function":"e","uid":"2cfee1","process_id":3705}
2020-07-18T21:42:41Z index [ERROR]: No tag id created  - {"file":"Tag.php","line":177,"function":"getID","uid":"2cfee1","process_id":3705}
```

**Comment by annando** [comment]
Thanks, this should help.

**Comment by SpcCw** [comment]
Hey, something changed here :)

After updating to RC some of the missing tags appeared but their last letter became "?"

I tried it on another node and got same effect there: https://mordor.social/display/027b03f7-175f-dcdf-1f07-318898786735

However after I deleted the post on my node and tried again, tags disappeared again and now are back to their previous behavior: https://friends.deko.cloud/display/d0446be5-645f-dce6-130d-17f352438242

Here's one with problematic tag used for the first time after update: https://friends.deko.cloud/display/d0446be5-475f-dce6-a6bd-f64273102272

UPD: It seems that the problem is caused by letter "а" if tag ends with it - then it gets replaced by "?" and the tag itself doesn't work. Same tags with capital "А" work. Perhaps this is some sort of encoding issue?

**Comment by SpcCw** [comment]
I think I identified the problem. After commenting out [this line](https://github.com/friendica/friendica/blob/c6bb405b07a24cb2112637ac2bd967c3e8a167b8/src/Model/Tag.php#L74) it starts to work as expected.

Before: https://friends.deko.cloud/display/d0446be5-385f-131a-1a27-500497036827
After: https://friends.deko.cloud/display/d0446be5-875f-ddbc-664e-955723338927

I think it happens because _trim_ in `$name = trim($name, "\x00..\x20\xFF#!@,;.:'/?!^°$%".'"');` doesn't support multibyte strings and it causes unexpected results. Could we replace it with something else? I found [some workarounds here](https://www.php.net/manual/en/ref.mbstring.php).

@annando what do you think?

Also currently this issue populates DB with junk tags from federated posts if unfixed:
```
| 118384 | наук?                       |     |
| 118682 | наукаимедицин?              |     |
| 118333 | наукаитехник?               |     |
```
These tags can't be used and will require manual intervention later so I think something should be done about this before release.
