### ISSUE TITLE
frio theme - profile viewas form looks messed up

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#8906]
On the profile page (frio theme), the "viewas" form looks messed up (maybe because it contains a too long username).
See these screenshots:

### Expected behavior

![friendica-viewas-fixed](https://user-images.githubusercontent.com/5753419/87917112-bdf21f00-ca74-11ea-940d-796254e3bd73.jpg)

### Actual behavior

![friendica-viewas](https://user-images.githubusercontent.com/5753419/87917135-c6e2f080-ca74-11ea-8a62-55c2f90147d2.jpg)

### Steps to reproduce the problem

Not sure. Simply editing a username in the select with developer tools does not seem to work.
I see it messed up when the select contains the contact "Thorsten 'Das Leben, das Univers…' Leemhuis(1/6)".
When I delete this select option with chromium devTools, everything looks okay.

### Friendica version you encountered the problem
friendica version: 2020.07
database version: 1355
post-update version: 1350

### PHP, MySQL etc..
don't know, I am just a user

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by MrPetovan** [comment]
The "View as" form has been moved to the bottom of the page where contact names can take as much space as they want.
