### ISSUE TITLE
Reconsider usage of the "notice" function and remove it when unneeded

### ISSUE THREAD

**Issue by annando** [friendica/friendica#8907]
The function "notice" is used at many places (272 times). It is used so often and in an superfluous way so that users want to have all notices removed.

Since the notice can surely be used in a useful way we should define a guideline for using the function and then rework all parts of the code where the function currently is used.

See the discussion here: https://forum.friendi.ca/display/2196d4ee-845f-140b-2a94-61e827651246

**Comment by MrPetovan** [comment]
The `Welcome back %s` info should be removed but the `Welcome %s` and `Please upload a profile photo.` should stay.

The `Post published` should be investigated as of why it appears multiple time and should be omitted when posting from the Compose page (non-AJAX mode).

**Comment by annando** [comment]
I also want to remove it when settings had been saved.

**Comment by annando** [comment]
Have we reached now a level where `notice` and `info` are only used when really needed?

**Comment by AlfredSK** [comment]
My feeling tells me that it is okay now.

**Comment by MrPetovan** [comment]
Mostly, as we've discovered recently in #9218
