### ISSUE TITLE
can't add a smiley via click in the post editor

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#8910]
### Expected behavior
when clicking a smiley from the selection in the post editor, it should be inserted into the text 
### Actual behavior
nothing happens. console output:
```
Uncaught ReferenceError: plaintext is not defined
    at smileybutton_addsmiley (network?contactid=297538&order=post:1139)
    at HTMLImageElement.onclick (network?contactid=297538&order=post:1120)
```
### Steps to reproduce the problem
- write a new post in a webbrowser (I used chromium). 
- click the smiley symbol if available. a selection of smileys should appear
- click one of the smileys
- see if it is added to the text

### Friendica version you encountered the problem
friendica version: 2020.07
database version: 1355
post-update version: 1350
theme: Frio

### Friendica source (git, zip), PHP version, SQL version
k.A. just user

**Comment by MrPetovan** [comment]
Note: It seems to be an issue with the addon `smileybutton`.

**Comment by haheute** [comment]
With theme `vier` it does not seem to work. The error message looks the same.

**Comment by MrPetovan** [comment]
Thank you very much!

**Comment by MrPetovan** [comment]
Sorry I missed this, it is now a duplicate or #9914 for which I came up with a fix.
