### ISSUE TITLE
White page and PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted

### ISSUE THREAD

**Issue by xango60** [friendica/friendica#8921]
### Expected behavior
Dear team a few days ago I installed an instance of Friendica on my proxmox 5.4 server in a LAMP container. All regular for the first few days, then today when I try to enter I get a blank page. Looking in the apache logs I found these errors:
Container debian 10 with standard config
### Actual behavior
non info in friendica/log/friendica.log
### Steps to reproduce the problem
this is the apache error.log:
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in /var/www/friendica/vendor/paragonie/sodium_compat/autoload-php7.php on line 27
PHP Stack trace:
PHP   1. {main}() /var/www/friendica/index.php:0
PHP   2. require() /var/www/friendica/index.php:28
PHP   3. ComposerAutoloaderInitFriendica::getLoader() /var/www/friendica/vendor/autoload.php:7
PHP   4. composerRequireFriendica() /var/www/friendica/vendor/composer/autoload_real.php:63
PHP   5. require() /var/www/friendica/vendor/composer/autoload_real.php:73
PHP   6. require_once() /var/www/friendica/vendor/paragonie/sodium_compat/autoload.php:51
PHP   7. require_once() /var/www/friendica/vendor/paragonie/sodium_compat/lib/sodium_compat.php:825
PHP   8. spl_autoload_call() /var/www/friendica/vendor/paragonie/sodium_compat/lib/constants.php:8
PHP   9. {closure:/var/www/friendica/vendor/paragonie/sodium_compat/autoload-php7.php:9-31}() /var/www/friendica/vendor/paragonie/sodium_compat/lib/constants.php:8

### Friendica version you encountered the problem
2020.07

### Friendica source (git, zip)
2020 tar.gz
### PHP version
7.3
### SQL version
10.3.22-MariaDB-0+deb10u1

**Comment by MrPetovan** [comment]
Thanks for the report, 2 MB max memory is far too little to run Friendica, please bump the limi to at least 128 MB in your php.ini file.

**Comment by xango60** [comment]
Hi
my php.ini is already at 120 mb
see below:
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 128

**Comment by MrPetovan** [comment]
Thanks for the elaboration, however this doesn't seem to be the value PHP uses as a limit when processing your web pages as demonstrated by the number in the error message itself (`2097152` bytes so exactly 2 MB). Please make sure to reload either Apache or php-fpm, maybe they are using a former values and haven taken the new one into account yet.

**Comment by xango60** [comment]
I don't know I changed the limit to 256M, reboot and still white page

**Comment by AlfredSK** [comment]
I think you're changing the value at the wrong place. I know nothing about "proxmox" but usually there are several php.ini files - for CLI processes and for e.g. FPM etc.
You may also use a `.user.ini` file in Friendica's document root to set the PHP environment variables. It's convenient and you can set different values for each served application that way.

**Comment by MrPetovan** [comment]
Let's troubleshoot deeper. Please edit your Friendica install `index.php` file and make it look like this:

```php
<?php
phpinfo();
die();

[rest of the file without any <?php] 
```

Then reload the page. You should see the PHP Info page. It will show the current configuration (including the `memory_limit` value) and the list of used INI configuration files, please make sure you added the modification to them as well.

**Comment by xango60** [comment]
Strange strange issue, I checked on google about memory_limit
and I changed the line
memory_limit = 128
with 
memory_limit = 256M
and now is working; I'm not expert about PHP but the missing M was the issue.
Let me time to test the system and I'll inform you.
Thank you

**Comment by MrPetovan** [comment]
This was my next line of inquiry. I didn't immediately notice the `128` which means literally 128 bytes of maximum memory, which PHP raises to the minimum 2 MB implicitly, but I've noticed you added the M when you changed for 256 MB. This should be enough.

**Comment by xango60** [comment]
It was my mistake, well there is always something more to learn. What seems strange to me, and that for a few days everything worked. Better this way. Day after day I am discovering the validity of this software.
Thanks for your support, and the work of the Friendica team.

**Comment by MrPetovan** [comment]
You're welcome, if your problem is solved you can close this issue.

**Comment by mikauskas** [comment]
I have a similar error, for me 128 MB is really not enough. Getting blank pages everywhere except admin panel. Latest develop.
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /var/www/quality/src/Database/Database.php on line 927`

**Comment by MrPetovan** [comment]
Thank you for the report, please increase PHP's memory limit to 256M as well.

**Comment by mikauskas** [comment]
@MrPetovan even 2GB is not enough, perhaps it all gets sucked up into other space? `PHP Fatal error:  Allowed memory size of 2126512128 bytes exhausted (tried to allocate 8192 bytes) in /var/www/quality/src/Database/Database.php on line 927`

**Comment by MrPetovan** [comment]
Ok, this is concerning, what page do you get the error on? Any?

**Comment by mikauskas** [comment]
I think something was wrong with MariaDB. Purge, reinstall didn't help, but server OS reinstalling helps with all problems :)

**Comment by MrPetovan** [comment]
Oof, sorry about that.
