### ISSUE TITLE
[forumdirectory] DB Error in addon module

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8922]
```
{"code":1064,"error":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`user`.`page-flags` = 2' at line 1","callstack":"Database::fetchFirst, DBA::fetchFirst, forumdirectory_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent, Page::run","params":"SELECT COUNT(*) AS `tot$
```

**Comment by annando** [comment]
The important part of the message is cut at the end.

**Comment by MrPetovan** [comment]
I know, but it's what we have to work with.

**Comment by annando** [comment]
You should have an entry with "DB Error" in your logfile with the complete query.

**Comment by MrPetovan** [comment]
This doesn't come from my log, and I was able to find the problem query based on this stub:
https://github.com/friendica/friendica-addons/blob/d2639edbc210fed7ed8f29609597ff133e716212/forumdirectory/forumdirectory.php#L96-L99
```php
	$cnt = DBA::fetchFirst("SELECT COUNT(*) AS `total` FROM `profile`
				INNER JOIN `user` ON `user`.`uid` = `profile`.`uid`
				WHERE $publish AND NOT `user`.`blocked` AND NOT `user`.`account_removed` `user`.`page-flags` = ? $sql_extra",
				User::PAGE_FLAGS_COMMUNITY);
```
There's a missing `AND` in the last line of the query.

**Comment by annando** [comment]
Ah, it's the same error we had in the core?

**Comment by MrPetovan** [comment]
I do not know.

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica-addons/pull/1015
