### ISSUE TITLE
[frio, mobile, iOS only] share not working, creates empty post

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#8928]
2020.09-dev
database version 1358
post update version 1350

On friendica mobile (iOS, Android not tested yet) sharing a post is not possible. Affects all posts (friendica, twitter, diaspora).

When tapping the share option a new post draft is created but it remains empty.

This is not reproducible on frio desktop.

**Comment by MrPetovan** [comment]
I confirm this behavior on iOS Home Screen app. Not sure how to debug this though since I don't have access to the phone's browser console.

**Comment by AlfredSK** [comment]
I don't have this issue on Android (Chrome web app).

**Comment by MrPetovan** [comment]
Dammit.

**Comment by MrPetovan** [comment]
I can reproduce this on Vivaldi Desktop, we're getting somewhere.

**Comment by MrPetovan** [comment]
I can see textcomplete Javascript errors in my console when the share block isn't added to the modal window textarea, clearing my cache resolved the issue. Can you please try to clear your Safari website cache? Clearing the cache of an iOS Home Screen App is impossible without removing said app.

This kind of cache issues is still expected on the develop branch, but they will not subside on release when the version number changes.

**Comment by foss-** [comment]
Cleared Brave cache and share is working again.

**Comment by MrPetovan** [comment]
Can we close this?

**Comment by foss-** [comment]
clearing cache resolves this problem.
