### ISSUE TITLE
Add converse.js to Friendica Addons

### ISSUE THREAD

**Issue by bjoerns1983** [friendica/friendica#893]
The Jappix Mini chat has some important features missing, like displaying offline accounts etc. and it seems that these things will not be integrated in it.

Please consider to create an add on for converse.js which is a more featurefull XMPP web client, which supports Offline Accounts, OTR etc.

Documentation for converse.js can be found here: https://conversejs.org/
Sourcecode can be found here: https://github.com/jcbrand/converse.js

**Comment by tobiasd** [comment]
I think we can close this issue right? see [xmpp addon](https://github.com/friendica/friendica-addons/tree/master/xmpp).

**Comment by annando** [comment]
I would say so.
