### ISSUE TITLE
Changing the send mail address (noreply)

### ISSUE THREAD

**Issue by gravity-deleted** [friendica/friendica#8932]
Hi,

I came across something that I can't really explain and I can't find my mistake.

**Version:** Friendica 'Red Hot Poker' 2020.07 - 1355

I have defined an address in the options under "sender for emails". I noticed that this is not supported with the mail () function.

That means, the notifications about new contact requests and so on. If I remember correctly, it worked when confirming that the database was updated successfully.

But since I use PHP Mailer SMTP I wanted to avoid this by entering the data of the mail I want to use.
This didn't work either, so I need to have and use a noreply.

What can I do so that all mails run over the PHP Mailer SMTP and I can define the mail account?

**Comment by MrPetovan** [comment]
The `From:` field is set through the `phpmailer.smtp_from` configuration key for the PHP Mailer addon if this is what you are asking.

**Comment by gravity-deleted** [comment]
It Works. (Probably the update helped)

And changing the mail address completely does not work?
If it does not work, do I have to create the PGP key on the noreply?

**Comment by gravity-deleted** [comment]
It Works.

However, I have no real explanation. I haven't changed anything.
(Probably the update helped)

Sorry for the spam. Closed.
