### ISSUE TITLE
Frio: Shared posts do not respect "content background opacity" setting for theme

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#8935]
Settings > Display Settings > Custom Theme Settings > Content background opacity > Set to very low and use a dark background

Same problem exists for the Reply field beneath posts.

### Expected behavior

Reposts / shared posts should also respect that setting.

### Actual behavior

Shared posts ignore that setting and look "wrong".

<img width="676" alt="shared post not respecting opacity setting" src="https://user-images.githubusercontent.com/5708172/88579258-0ea3e200-d04a-11ea-9a87-bf80ec205b0a.png">

**Comment by MrPetovan** [comment]
This is a straightforward change: find the shared content CSS class or selector, and add the content background opacity variable like we do for the existing post background.

**Comment by MrPetovan** [comment]
This was not straightforward. To enable a dark theme (the overarching goal of this issue), I've had to continually edit some parts to enabled content background transparency.

I may have reached a point too far, including with the second nav bar, and I need feedback:

![friendica-darkmode](https://user-images.githubusercontent.com/925415/89725087-858d9300-d9d9-11ea-89a5-bcaaba803785.png)

**Comment by foss-** [comment]
The initial problem for shared posts is resolved with your changes. That is awesome thanks so much 🙌

Is it possible to also tackle the "Reply to" field and have that apply the same background color?

Re: 2nd nav bar: Interesting approach. Wouldn't it be easier to also make that text + background color configurable?

Uncertain about the 2nd nav bar opacity concept. Would prefer moving those elements elsewhere and getting rid of the overwhelming two bar navigation at the not. But as discussed this is not trivial to solve. So would making the 2nd bar respect color settings of the top nav bar work? At least that would prevent having it look white, alien and not fit in at all.

**Comment by MrPetovan** [comment]
> Is it possible to also tackle the "Reply to" field and have that apply the same background color?

Not consistently across form controls. For example, select dropdowns background has always been white, despite my efforts to change it. This makes using the chosen theme font color impossible for light colors. So I kept the default combination background/font color for form fields, including text boxes and select boxes.

> Re: 2nd nav bar: Interesting approach. Wouldn't it be easier to also make that text + background color configurable?

No, it's two more controls in the theme customization form which is already packed, especially after the addition of the font color control. I feel like we have enough available customizable colors to use them for this second navbar but I haven't found the right combination yet.

**Comment by MrPetovan** [comment]
I found a way to have a consistent result with the second nav bar without having to provide more color controls: reversing the main nav bar colors. Using a lighter nav bar background color, it also make primary buttons stand out against the dark background and reduces the contrast of the second nav bar without hurting light themes. Additionally, more Bootstrap defaults have been improved with opacity:

![friendica-darkmode-1](https://user-images.githubusercontent.com/925415/89744886-917f6080-da7e-11ea-9f27-4afa4a7b07dd.png)

![friendica-darkmode-1-modal](https://user-images.githubusercontent.com/925415/89745030-ee7b1680-da7e-11ea-990a-020e6e093735.png)
