### ISSUE TITLE
Potential foreign key constraint violation updating to 2020.09

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8940]
I updated my node to the latest develop branch, and received a bunch of emails about a failing query:
```
The friendica developers released update 1358 recently,
but when I tried to install it, something went terribly wrong.
This needs to be fixed soon and I can't do it alone. Please contact a
friendica developer if you can not help me on your own. My database might be invalid.

The error message is
Errors encountered performing database changes: ALTER IGNORE TABLE `contact-relation` ADD `follow-updated` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of the last update of the contact relationship', ADD `follows` boolean NOT NULL DEFAULT '0' COMMENT '', ADD FOREIGN KEY (`cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
```

This query failed because one of the values of `contact-relation.relation-cid` didn't exist in `contact.id`, breaking the foreign key constraint.

I believe we should sanitize the data first before updating the table.

**Comment by annando** [comment]
Meh, I hoped that the data would be sane enough there. I had checked with my rather messy development system and everything went fine. So guess your system is even more messy than mine ;-)

**Comment by annando** [comment]
This should already be solved: https://github.com/friendica/friendica/blob/develop/update.php#L572-L579

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/9012
