### ISSUE TITLE
Post expiration interval can override user search query

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#8943]
### Demonstrated behavior

From my Friendica instance, if a user searches for a specific URL to grab a post from another system (I tested with https://yo.isurf.ca/notice/9wFh8IegUT7YpcAXqq ), but the post itself is older than an expiration setting (I believe the only expirations that this post is older than is the "Lifespan of remote items" and "Lifespan of unclaimed items"), then Friendica errors out and tells the user "No results".  The logs shows: 
`2020-07-28T20:36:58Z index [NOTICE]: Item created before expiration interval. {"created":"2020-06-19T20:38:21-07:00","expired":"2020-06-28T13:36:58-07:00", ....`

### Expected behavior

If a user goes to pull in a post from somewhere else in this fashion, it should override system expiration settings.

### Steps to reproduce the problem

Have the two settings mentioned set to under 30 days and then search for a post than is older days.

### Friendica version you encountered the problem

2020.07 stable

### Friendica source (git, zip)

git

### PHP version

7.4.8

### SQL version

MariaDB 10.3.23

**Comment by annando** [comment]
This is slightly more complicated. The check for the item age is deeply in the code, far away from the code that manually adds items.

**Comment by SpcCw** [comment]
Yes, this is annoying at times (especially when you don't know what is going on). Note that this seems to be affected only by post expiration setting (both global and user) and not "unclaimed items".

**Comment by annando** [comment]
Yes. It is this check: https://github.com/friendica/friendica/blob/2020.09-rc/src/Model/Item.php#L1354-L1373

**Comment by annando** [comment]
This can't be changed easily. So I suggest moving it to the next milestone.

**Comment by annando** [comment]
In the end the change had been easy :-)
