### ISSUE TITLE
Twitter connection can no longer be disconnected after changing access data.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8950]
### Expected behavior
If you change the Twitter access data in the admin area, you should be able to delete and re-establish the connection to Twitter in the settings
### Actual behavior
If you change the Twitter access data in the admin area, there is no longer a button in the settings that deletes the connection, ergo the old Twitter connection can no longer be deleted.
### Steps to reproduce the problem
Create a new app on Twitter. Enter the new access data in the admin area (key and secret) Now try to delete the Twitter connection in the settings.
### Friendica version you encountered the problem
2020.07 - 1355
### Friendica source (git, zip)
git
### PHP version
7.4
### SQL version
MariaDB 10.1.44

**Comment by MrPetovan** [comment]
My phone is out for repairs at the moment so I can't provide a valid phone number for my Twitter account so I could create a new app and test this issue. I'm afraid this will have to be pushed to the next release.

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica-addons/pull/1028
