### ISSUE TITLE
Add image to comment reloads page and redirects to /network

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8956]
### Expected behavior
When I try to add an image to a comment the image should be added to the editor.

### Actual behavior
When I comment on a post on single post page (/display/...) and I try to add an image to that comment the page reloads and (possibly) redirects to /network or the configured default page (startpage-addon).
Could be theme specific. I'm using frio.

### Steps to reproduce the problem
Open a post in single post view.
Comment on that post.
Click on the image icon.
Photos browser shows up.
Click on an album name or an image thumbnail.
Instead of adding the BBCode to the editor the page is reloaded.

When I try the same on /network or my /profile page it is somewhat better. But after selecting an image the comment box collapses - but BBCode is inserted correctly.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Before labeling this as a bug, please make sure:
- You cleared your browser cache.
- The console doesn't show any javascript errors.

**Comment by annando** [comment]
I just saw a fatal error in my logs that seems to be associated with uploads: https://github.com/friendica/friendica/issues/8875#issuecomment-667466124

Are you experiencing that fatal error as well?

**Comment by clacke** [comment]
I now saw this happen with `compose` too.

When you open the gallery, first the thumbnails are small, then they get bigger. If you click one when it's small, you get the redirect.

When I make a comment and click the insert image icon, the thumbnails stay small, they don't get to the big state.

**Comment by AlfredSK** [comment]
> Are you experiencing that fatal error as well?

No.

**Comment by AlfredSK** [comment]
Cleared the browser cache, deleted all compiled smarty templates.

Chromium says when loading the single post page:
```
textarea.js:133 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at t.value (textarea.js:133)
    at new t (textarea.js:30)
    at n.fn.init.$.fn.textcomplete (autocomplete.js?v=2020.09-dev:206)
    at n.fn.init.$.fn.editor_autocomplete (autocomplete.js?v=2020.09-dev:296)
    at HTMLDocument.<anonymous> (0b6b25a8-215f-2490-f044-25f714652179:100)
    at i (jquery.min.js?v=2020.09-dev:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=2020.09-dev:2)
    at Function.ready (jquery.min.js?v=2020.09-dev:2)
    at HTMLDocument.J (jquery.min.js?v=2020.09-dev:2)
```

**Comment by MrPetovan** [comment]
This has now been fixed.
