### ISSUE TITLE
frio: wrong avatar thumbnail in top bar

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8967]
### Expected behavior
Show *your* avatar thumbnail in top (main) bar in frio.

### Actual behavior
For some accounts a random (wrong) avatar thumbnail is used. A user of my node reported this. I checked some of my accounts and I can confirm it.

### Steps to reproduce the problem
Just check some of your accounts if the right thumbnail is used.

https://libranet.de/display/0b6b25a8-755f-284e-1c8f-1d2507080884

### Friendica version you encountered the problem
2020.09-dev after PR8960

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
I only checked with frio. Don't know if other themes are affected too.

**Comment by annando** [comment]
Yeah, it had been a stupid bug :grin:

**Comment by AlfredSK** [comment]
Seems to be fixed. 🎉 User says: "100% success". Thank you! 😍
