### ISSUE TITLE
Vendor problem in Version 2020.03 and missing directory in Versions 2020.07

### ISSUE THREAD

**Issue by graud** [friendica/friendica#8979]
Additional: in Version 2020.07 the Vendor directory is missing completely.

### Expected behavior
Installing version 2020.03 on local machine should open up the install wizard.

### Actual behavior
Installing version 2020.03 on a local machine gives me the error "Vendor path not found. Please execute "bin/composer.phar --no-dev install" on the command line in the web root.

### Steps to reproduce the problem
download source
decompress
move folder to /var/www/html
change permissions and user/group
open up localhost/friendica

### Friendica version you encountered the problem
2020.03 stable

see `example.com/friendica` on your Friendica node for the version information.

### PHP version
7.3.20

### SQL version
5.0.12-dev

**Comment by MrPetovan** [comment]
Hi, thank you for your report, you have two ways of resolving this issue:
1. Doing what the error message suggests.
2. Doing what [the release notes](https://github.com/friendica/friendica/releases/tag/2020.07) suggest and downloading the full archive (named `friendica-full-2020.07.tar.gz`) that includes the `vendor` folder.
