### ISSUE TITLE
Login not possible and switching accounts not possible

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8984]
### Expected behavior
I should be able to switch to another managed account. I should be able to login from main page.
 
### Actual behavior and steps to reproduce
Switching accounts: User A is selecting another account B from example.com/delegation. That doesn't work. User A is thrown back to the previous page in current session of user A. E.g. A was on /contact. Went to /delegation. Selected another manged account B. A is thrown back to /contact of user A.

Even worse: User A logs out to check what's wrong. User A cannot log in anymore. A enters credentials. Clicks on 'Login'. Page is reloaded without A being logged in. 
**Edit: Login with 'remember me' works! Login w/o 'remember me' fails.**

### Friendica version you encountered the problem
2020.09-dev latest code 

### PHP version
7.4

### SQL version
10.3 MariaDB

### Session config
```
'cache_driver' => 'redis',
'session_handler' => 'cache',
```

**Comment by AlfredSK** [comment]
Login with 'remember me' works!

**Comment by AlfredSK** [comment]
Maybe related to this?
https://github.com/friendica/friendica/pull/8982/commits/077b57ecb38e7114539a54c0670a4930d434c276

**Comment by MrPetovan** [comment]
It's possible, let me look into this.

**Comment by MrPetovan** [comment]
Ah-ha! Session clearing is used in the context of an active session, so destroying the session on clear was the wrong approach.

Instead, we don't ignore a session write with empty data, we destroy the session. Session writes happen at the end of the script, so there's no interference when session is cleared in the middle of the script.

**Comment by AlfredSK** [comment]
Works again!
