### ISSUE TITLE
Embed of rendered friendica post in non-activitypub website?

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8985]
Is it possible to get a rendered version of a (my own) post from a (my own) friendica instance to embed it into other (non-activitypub) websites?

I'm trying to built a page that includes some of my own friendica posts and would love to see this functionality.

Currently, I'm using the friendica API to retrieve the contentMap of my own posts. However, this comes with several problems: some of my posts contain bbcode, which uglifies the embedded version of the post. Also, I'd love if the embedded version of my post could contain the replies and likes (possibly in an anonymous way) and if it had some of the interactivities of the original post, such as the "go to source".

Is this possible somehow already (possibly via some third party software)? And if no, would this be a large effort?

**Comment by wiwie** [comment]
How much effort would it be to implement something like oembed? Couldn't an initial simple version basically render just the same html that is rendered on the post/ network page?

**Comment by MrPetovan** [comment]
Absolutely, we use it for the preview already, albeit in a pretty tortuous manner, so we would probably need to create a more straightforward way.

**Comment by wiwie** [comment]
Could you point me to the code that creates the preview? Also, which preview is it, i.e where is it used?

**Comment by MrPetovan** [comment]
The preview is done in `mod/item.php` when `$preview` is set to `1` through the `preview` GET parameter. However it is meant to take a post body from the publishing form, not from an existing item.

A closer approach would be the `mod/display.php` file using the `conversation()` global function defined in `include/conversation.php` and maybe use the `minimal` layout, like this: https://friendica.mrpetovan.com/display/24324cc4-e0244641dd3c75d8-ca3f271b?mode=minimal

However it still displays the whole conversation, not a single post. There is a display context where single posts are displayed with the link to the context conversation in the search results. Apparently you can get this display by settings the `$mode` parameter of the `conversation()` function to `'search'`.

So in theory, you could build a new OEmbed module that fetches a single item by guid, and feed it to `conversation()` with `$mode = 'search'`, and forces the minimal layout by artificially setting `$_GET['mode'] = 'minimal'`.

Good luck!

**Comment by wiwie** [comment]
Wow thanks for your extensive answer. I'll have a look at it :-)

**Comment by wiwie** [comment]
Actually I tried this out back then but forgot to report back.

I didn't end up using this approach, because the standard approach to doing embeds like this turned out to be iframes. And I really dislike those.

So what I instead ended up doing was to parse friendica's API and custom bake a highly simplified UI of the posts on the other page. No comments, no like counter, no reshare counter. Just the title and the body. It's not particularly pretty, but functional.
