### ISSUE TITLE
Showmore_dyn add-on: configure height of posts

### ISSUE THREAD

**Issue by mpanhans** [friendica/friendica#8990]
The Showmore Dynamic add-on is wonderful. I have just one suggestion, because even rather short posts require clicking "Show More" to see the entire post. Nearly everything in my own feed needs to be expanded. I think ideally posts would be collapsed to about 3x the current height limit.

I do not believe this can currently be configured by the instance admin (though perhaps I am wrong?). So my request is to either allow this minimum "show more" height to be configured by the admin; or to increase it to 3x the current height.

**Comment by MrPetovan** [comment]
This addon max height is configurable individually by each user in their Addons settings.

**Comment by AlfredSK** [comment]
I tried this one time only because the height configuration didn't work as expected. I had the impression the max. height value is only applied on posts but not on comments.
But maybe that is another issue.

**Comment by mpanhans** [comment]
> This addon max height is configurable individually by each user in their Addons settings.

I see! Sorry, yes I hadn't noticed there was Settings > Addons outside of the Admin Panel. I still stand by my original statement that "Showmore Dynamic add-on is wonderful." But yes so let's close this issue.

**Comment by MrPetovan** [comment]
> I tried this one time only because the height configuration didn't work as expected. I had the impression the max. height value is only applied on posts but not on comments.
> But maybe that is another issue.

It is indeed another issue.

**Comment by MrPetovan** [comment]
cc @wiwie for the praise.
