### ISSUE TITLE
[wrong translation de] german admin site names 'config/local.ini.php' instead of  'config/local.config.php'

### ISSUE THREAD

**Issue by produnis** [friendica/friendica#8993]
Hi there,
I might have found a small "bug" / wrong translation.

On the german admin site, friendica states:

`Die Konfiguration von Friendica befindet sich ab jetzt in der 'config/local.ini.php' Datei. Kopiere bitte die Datei 'config/local-sample.config.php' nach 'config/local.config.php' und setze die Konfigurationvariablen so wie in der alten .htconfig.php. Wie die Übertragung der Werte aussehen muss, kannst du der Konfiguration Hilfeseite entnehmen.`

it names 'config/local.ini.php' instead of  'config/local.config.php' in the first sentence.

The correct message should be (i think):
`Die Konfiguration von Friendica befindet sich ab jetzt in der 'config/local.config.php' Datei. Kopiere bitte die Datei 'config/local-sample.config.php' nach 'config/local.config.php' und setze die Konfigurationvariablen so wie in der alten .htconfig.php. Wie die Übertragung der Werte aussehen muss, kannst du der Konfiguration Hilfeseite entnehmen.`

greetings
Joe

**Comment by MrPetovan** [comment]
Good catch!

**Comment by produnis** [comment]
i would like to fix it on my own, I looked at transifex but I don't know where to find that message....

**Comment by MrPetovan** [comment]
The source string should be `%d year old`, please make sure you check the plural as well.

**Comment by MrPetovan** [comment]
The source text starts with `Friendica's configuration now is stored in config/local.config.php`.

**Comment by produnis** [comment]
Thx, I edited and hit "save as suggestion"

**Comment by MrPetovan** [comment]
You should have been able to save the new version, @tobiasd do you know why people can't save translations directly but as suggestions instead?

**Comment by tobiasd** [comment]
looking at the Transifex sources, this should be fixed I think.

**Comment by MrPetovan** [comment]
Nope, here's the relevant snipper in `view/lang/de/strings.php`
```php
$a->strings["Friendica's configuration now is stored in config/local.config.php, please copy config/local-sample.config.php and move your config from <code>.htconfig.php</code>. See <a href=\"%s\">the Config help page</a> for help with the transition."] = "Die Konfiguration von Friendica befindet sich ab jetzt in der 'config/local.ini.php' Datei. Kopiere bitte die Datei  'config/local-sample.config.php' nach 'config/local.config.php' und setze die Konfigurationvariablen so wie in der alten <code>.htconfig.php</code>. Wie die Übertragung der Werte aussehen muss, kannst du der <a href=\"%s\">Konfiguration Hilfeseite</a> entnehmen.";
$a->strings["Friendica's configuration now is stored in config/local.config.php, please copy config/local-sample.config.php and move your config from <code>config/local.ini.php</code>. See <a href=\"%s\">the Config help page</a> for help with the transition."] = "Die Konfiguration von Friendica befindet sich ab jetzt in der 'config/local.config.php' Datei. Kopiere bitte die Datei  'config/local-sample.config.php' nach 'config/local.config.php' und setze die Konfigurationvariablen so wie in der alten <code>config/local.ini.php</code>. Wie die Übertragung der Werte aussehen muss, kannst du der <a href=\"%s\">Konfiguration Hilfeseite</a> entnehmen.";
```
The second line is fine, but the first isn't. The correct translation has been suggested in Transifex by @produnis , but I have not been able to save it, I could just upvote his suggestion.

In [the German team screen](https://www.transifex.com/Friendica/teams/12172/de/), both @produnis and I are in the "Translators" group which means we can't directly save translations, apparently only "Reviewers" or "Coordinators" (of which you are a part of) can. I don't believe we need this distinction, but I don't have the power to promote Translators to Reviewers.

**Comment by tobiasd** [comment]
For _some_ reason I only saw the correct 2nd string this morning when searching for them... But I have elected all translators to reviewers now and adopted the suggestion. PR will follow soon.

**Comment by MrPetovan** [comment]
Thanks!
