### ISSUE TITLE
Email Connector getting "The network type couldn't be detected. Contact can't be added."

### ISSUE THREAD

**Issue by erothoff** [friendica/friendica#8994]
### Expected behavior
Add a Contact from the connected (by IMAP) email account, when you have an email from the person.

### Actual behavior

With emails from the wanted contact in the IMAP email account, I get an error "The network type couldn't be detected. Contact can't be added." When I use Probe Diagnostic and enter a Lookup address, in the output I get "Output: [network] => unkn"
I am using the same account that I use on another site, and the email address of a contact on that site.

While I get email updates on the other site, I can not add new email contacts on that site as well. Happened about the time the site admin upgraded to 20.07.

### Steps to reproduce the problem

I have tried with multiple emails addresses that are sitting in my email account. So all you should need to do is make sure the site is using 20.07, and has email connector, an email account using SSL connected. (TLS is not working.) and an email from the desired contact in the inbox.  I do not remember if you have to use the mailto: before the email address or not. (I have tried both.) 

### Friendica version you encountered the problem
20.07

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
Mine is a zip, Other site I believe is git.

### PHP version
PHP Version 7.4.3

### SQL version
mysqlnd 7.4.3

**Comment by MrPetovan** [comment]
I believe @annando is using the email connector, hopefully he can have enlightened advice.

**Comment by tobiasd** [comment]
You can try to add `email:` as hint for Friendica to the address when you try to add the contact.

**Comment by annando** [comment]
I suggested @erothoff to open this issue. I'm currently fighting with the forum message distribution, so I'm not having that much time. I'm convinced that there is a bug in the probing, since there had recently been many changes, so I don't want to forget about this.

**Comment by erothoff** [comment]
I tried using email: in front of the email address, but it didn't help on either server. :-(
