### ISSUE TITLE
'Contacts' link on own profile page gives 'forbidden' error

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8995]
### Expected behavior
I don't know what the expected behavior is but I'm pretty sure an error 403 (forbidden) is not it.

### Actual behavior
When I go to my profile page (house icon) there are several links in the second top bar: 'profile', 'status', 'photos', 'videos', 'events' 
and 'personal notes'.
When I click on 'photos', 'videos', 'events' or 'personal notes' an additional link appears: 'contacts'. When I click on the 'contacts' link I get a 'forbidden' error (permission denied).

```
#0 [internal function]: Friendica\Module\Profile\Contacts::content()
#1 .../src/App/Page.php(332): call_user_func()
#2 .../src/App/Page.php(388): Friendica\App\Page->initContent()
#3 .../src/App.php(560): Friendica\App\Page->run()
#4 .../index.php(42): Friendica\App->runFrontend()
#5 {main}
```

### Steps to reproduce the problem
1. Go to your own profile (status) page by clicking on the house icon

![contacts-1](https://user-images.githubusercontent.com/3656054/89730295-bc959000-da3d-11ea-800f-c76fdcdc4f9e.png)

As you can see there is no 'contacts' link in the second top bar.

Now click on one of the other links on the right side of 'status' - 'photos', 'videos', 'events' or 'personal notes'.

![contacts-2](https://user-images.githubusercontent.com/3656054/89730347-14cc9200-da3e-11ea-84bf-9320bcdaa339.png)

The 'contacts' link appeared. Which is weird. I think it should be there from the beginning or it shouldn't appear at all if this is the intended behavior.

Now click on that 'contacts' link.

![contacts-3](https://user-images.githubusercontent.com/3656054/89730410-84db1800-da3e-11ea-90ee-6c0e5cfb85ea.png)
 
### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Did you enable hiding your contact list?

**Comment by AlfredSK** [comment]
Yes, indeed. I did that yesterday.

**Comment by AlfredSK** [comment]
Ha! You're right. When I disable the hiding option it works as expected.
But I wouldn't expect that option to have an impact on myself.

**Comment by MrPetovan** [comment]
Yes, the condition is imperfect.
