### ISSUE TITLE
/settings password seems to be ignored

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#8997]
### Expected behavior
When I want to change my displayed name, my current password should be needed. (?)

> "Dein aktuelles Passwort um die Änderungen zu bestätigen"

### Actual behavior
Password can be left blank or random.

### Steps to reproduce the problem
Go to `/settings` and basic settings (#basic-settings-collapse), enter a new name. Leave password field empty or write a random value into it. Save. The new name should be accepted, without or with wrong password.

### Friendica version you encountered the problem
Version: 2020.07
Datenbankversion: 1355
Post-Update-Version: 1350
theme: Frio V.0.8.5

### PHP version & SQL version
- don't know (just user)

ps: There is also `/settings/profile` with a form to change the name without password field.

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by MrPetovan** [comment]
It appears the password is only necessary to change the email address. The display name can be freely changed. I guess the wording isn't clear about this.

**Comment by AlfredSK** [comment]
The full name can also be changed in the profile. Since we only have one profile now this seems to be redundant.
I think we can remove the full name field from the account settings completely.

**Comment by MrPetovan** [comment]
Fair point.

**Comment by tobiasd** [comment]
The display name of the account makes somewhat sense in both places of the settings for me.
