### ISSUE TITLE
Submitting of new PM fails

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8999]
### Expected behavior
When creating a completely new PM the auto-completion list at the TO field should vanish after selecting the desired recipient from the list. Submitting the message should work.

### Actual behavior
The auto-completion list doesn't vanish after selecting the recipient. You can only ignore this obstacle or hit ESC to close the list. Although the name of the recipient is visible now in the TO field submitting the PM fails with 'no recipient selected'.

### Steps to reproduce the problem
Go to /message.
Click on `+` to start new PM thread.
When the cursor is in TO field start typing to get the auto-completion list.
Try to select a recipient.
Try to submit the message.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Forum thread: https://forum.friendi.ca/display/0b6b25a8-135f-2ff6-bc2c-2b9410487483

**Comment by MrPetovan** [comment]
Ugh. Updating to a newish version of textcomplete fixed an ugle performance issue in Firefox, but stripped the possibility to complete contact names in a standard `<input>` tag (compared to `<textarea>` which works fine). Looking deeper in the code, I realized that using textcomplete for selecting a single element in a fixed list isn't ideal, so someone™ will have to change this form control to something more suitable. It could be tagsinput that has support for `<select>` elements.

**Comment by erothoff** [comment]
So an update on Messages. In stable stable version, 2020.07, in Vier, if I had someone in the list, I could message them, but I could not add someone to message. In Duepuntozero, I could reply to someone but I could not send to someone new. I just tested on Libranet and I can reply to a message, just not send a new message. So this same problem is in the stable version.
