### ISSUE TITLE
small typo, missing space

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9000]
Just a small typo. I believe a blank space character (or two: same for singular) is missing in the German localization.

### Expected behavior

> 37 Jahre alt

### Actual behavior

> 37Jahre alt

### Steps to reproduce the problem

add a birthday, use german localization, visit profile page

### Friendica version you encountered the problem
Version: 2020.07
Datenbankversion: 1355
Post-Update-Version: 1350
theme: Frio V.0.8.5

**Comment by MrPetovan** [comment]
If you want to fix this typo yourself, please register (or sign up) at Transifex where Friendica translations are managed: https://www.transifex.com/Friendica/friendica

**Comment by haheute** [comment]
OK, I think I have added it as a suggestion
