### ISSUE TITLE
[Feature Request] Repost a thread

### ISSUE THREAD

**Issue by gravity-deleted** [friendica/friendica#9002]
Hi!

I have a suggestion for improvement. If it's feasible.

There should be a way to repost an entire thread.

You could probably at least implement this internally for Frendica by assigning an "ID". But I'm only interested in the posts which were written by the creator. I think you need a timestamp for the ID to make sure that it is something that belongs together.

Do you understand what I mean?
It could be a great thing.

**Comment by MrPetovan** [comment]
Unfortunately this is an inherent limitation of all the social media platforms using a character limit, regardless of architecture: both Twitter, Mastodon and Pleroma don't allow this.

Friendica doesn't have a character limit per post which means we definitely don't have a specific local concept of threads of posts by the same author. But you can share the first post and encourage people to read the whole thread.

**Comment by gravity-deleted** [comment]
I figured as much. But I think it's a great idea, people are just very comfortable...
It would also be very nice for an overview.

But if it doesn't work, not even Frendica internally, you can't do anything.

Thanks for the info.
