### ISSUE TITLE
Translations: Conventionalisation, exemplified with German »du«/ »Du«/ »Sie«

### ISSUE THREAD

**Issue by timogith** [friendica/friendica#9008]
### Expected behavior

In German (as in many other languages, e.g. Korean, Swedish even after the du reform, French), there are different degrees of formality or politeness or friendliness in addressing users. As a user, you may find it strange, inadequate, or even impolite to be addressed in different ways in the same relation (here: Friendica UI - user). I would expect to have German users addressed (w.r.t. the purpose of the node) as either »Du« (written with a capital D, as this means to be a little more valuing than the version with a small d, which some -- mostly older -- people consider impolite) or »Sie« (which is used in formal contexts, always with a capital S).
Even though it would be nice to have an in-built back-end option of setting the formality (so that business use cases could opt for a different addressing than hobby nodes), from a linguistic point of view I reckon that would be hard to achieve (in linguistic pragmatics, formality is not the same as politeness, and yet another aspect would be kindness or cordiality -- and in Korean, to mention the worst language known to me in that regard, there are loads -- several dozens -- of potential contextual variants around indicating social relations only with verb endings, so to have this implemented to the point would be extremely sophisticated). Nonetheless I would strongly suggest to got for a standardisation here. (I have not checked the other languages I speak, a lot of translations seem to be missing there…).

This brings me to my general nice-to-have: There ought to be a **language-specific file in the translation system specifying linguistic conventions**. This is meant to include Friendica's very own terminology as well as addressing issues.

### Actual behavior

There is all types of translations around -- in my example, »du«, »Du«, »Sie«. And terminology is often confusing due to unexpected variants. Which is really odd most of the time.

### Steps to reproduce the problem

Set the language to German and just click through (far too many instances to enumerate).

**Comment by MrPetovan** [comment]
Hi @timogith and thank you for your concern. Friendica's translation is a community effort, and to that extent you can participate yourself. First by [joining the Friendica translation team at Transifex](https://www.transifex.com/Friendica/friendica/) where we perform translation, and second by drafting this language-specific file for German that we will be able to point to translators.

**Comment by tobiasd** [comment]
If you like, you can create separate translations for formal and informal language. I would think that most user would prefer the informal version, but I could be totally wrong with that. Guess you might get better results regarding that question in the [support forum of Friendica](https://forum.friendi.ca/profile/helpers). Then as @MrPetovan already mentioned, the community needs to perform the effort to unify the used language at Transifex.

**Comment by MrPetovan** [comment]
I feel like the issue is that the current translation is mixing addressing styles. This seems to be less about having both styles available than having a single consistent style across a unique German translation.

**Comment by tobiasd** [comment]
I think so as well. So the (German speaking) community should decide which form they prefer and then rush over to Transifex to fix the current translation and maybe also create the other form, if there are enough people who want that form.

But github is not used by most of the community members. Hence my suggestion to ask the question in the support forum. That should be the place to find the most interested community members.

**Comment by MrPetovan** [comment]
Oh absolutely.

**Comment by foss-** [comment]
💯for informal. No need to create overhead of informal and formal german localization. This is not the registry office.

**Comment by foss-** [comment]
Fixed. Please close.

**Comment by MrPetovan** [comment]
Did you update the translation strings in Transifex?

**Comment by foss-** [comment]
yes

**Comment by MrPetovan** [comment]
Closed by #9096
