### ISSUE TITLE
atom feed: Don't leave <title> empty

### ISSUE THREAD

**Issue by maneg2** [friendica/friendica#901]
I noticed that the atom feeds Friendica generates, for example

https://social.saz.im/dfrn_poll/sazius

come with elements which "title" tag is empty.

It would be great if you could put in there, say, the first x character (or k words) of the post; this way they would be more easily dealt with in a news reader (as now I have to open every one to see whether I am interested, with what I am proposing I could skim 80% of them).

**Comment by tobiasd** [comment]
I think this is implemented now? When I call `/feed/usernick` I see *usernick repeated something* and *new note by usernick* when no title was set.

**Comment by tobiasd** [comment]
Update to my last comment: When a title was set, it still shows "*new note by usernick*/. I think when a title was set it should be used in the `/feed` entry.

But I have not found an feed entry without a set title in all the feeds I have looked at so far.
