### ISSUE TITLE
posted order on network stream get updated like activity order

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9013]
### Expected behavior

Having only new top-level postings and new threads added to the network stream in _posted order_.

### Actual behavior

I think as a side effect of #9011 comments on old threads put the thread at top of the network stream in _posted order_ (as expected for _activity order_).

After a reload of the page, the wrongly added postings are not shown anymore.

### Friendica version you encountered the problem

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)

git development branch 2d25d5975a8ea0608275ba3b7e8a2a8a84ace73b

**Comment by annando** [comment]
I expected some problems after my work, since I simplified a lot. There is a lot of legacy code on the network page, so I got rid of all the stuff that I couldn't explain for myself.

PR is on the way.

**Comment by tobiasd** [comment]
I read about your expectations and thought _found one_ ;-)
