### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by osoloco** [friendica/friendica#903]
Any plans on supporting Google's opensourceed webp image format?
https://developers.google.com/speed/webp/

ImageMagick and Facebook now support webp. Chrome and Opera browsers do as well, but not yet Firefox, IE, Safari. Phtoshop doesn't yet either and so some FB users have complained about not being able to edit pics downloaded from FB when using Opera or Chrome but I suppose there could always be a right-click option to download images in other formats.

**Comment by annando** [comment]
It is now 2016 - and still Firefox can't handle this format. The support of this format in PHP seems to be possible with version 5.5. Does anyone knows how to offer images in multiple formats so that the browser could decide which one to chose? If that isn't possible, we should close the issue.

**Comment by osoloco** [comment]
There is a PageSpeedModule for Apache which will convert images to webp on-the-fly for browser clients supporting the format:

http://blog.teamtreehouse.com/getting-started-webp-image-format

**Comment by lapo-luchini** [comment]
[Firefox 65 now supports the WebP image format](https://hacks.mozilla.org/2019/01/firefox-65-webp-flexbox-inspector-new-tooling/).
[Safari still doesn't](https://caniuse.com/#feat=webp).

**Comment by foss-** [comment]
Tested webp image upload via drag and drop and it works fine.

This is Friendica, version 2023.09-dev that is running at the web location https://squeet.me. The database version is 1523/1523, the post update version is 1507/1507.

**Comment by MrPetovan** [comment]
This probably depends on whether squeet.me used GD (less likely) or ImageMagick (more likely) for image manipulation.

**Comment by AlfredSK** [comment]
Will be closed after 10 years! ♥️🎉☺️
