### ISSUE TITLE
Likes from Diaspora are not imported

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#905]
I've discovered an issue with "Likes" from Diaspora. I get the posts but the likes are missing. This is also true for likes of my contacts. I've found a lot of messages like this in my logfile...

````diaspora_like: top-level owner verification failed.````

I'm pretty sure this only happens since a couple of days. If I can help in any way, feel free to ask...

Version: 3.2.1748 - 1169
Plugins: altpager, forumlist, impressum, membersince, n-s-f-w, openstreetmap, privacy_image_cache, rendertime, startpage, statistics_json, twitter

Regards,
AlfredSK

**Comment by silke** [comment]
So you still consider this a bug that needs to be resolved on a proper way?

**Comment by friendica** [comment]
The order of args for the signature changed a while back. I've got this:

$signed_data = $positive . ';' . $guid . ';' . $target_type . ';' . $parent_guid . ';' . $diaspora_handle;

**Comment by annando** [comment]
@friendica Thanks. I will try it.

**Comment by fabrixxm** [comment]
Closed by #1446
