### ISSUE TITLE
Missing INSTALL.txt

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9064]
### Friendica version you encountered the problem

see `example.com/friendica` on your Friendica node for the version information.

**Comment by 4nanook** [comment]
The installation procedure refers you to INSTALL.txt to add a cron job for the worker but there is no INSTALL.txt in the github repository.  The version I installed is the current development version fro github via git clone.  PHP 7.4 Sql MariaDB 10.3.22

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by 4nanook** [comment]
Happy to help, did find docs in the doc directory that got me past this but still having other difficulties.

**Comment by SpcCw** [comment]
Looks like there are still some references to it:
```
/usr/share/nginx/friends/src/Module/Install.php:354:			. DI::l10n()->t('Please see the file "INSTALL.txt".')
/usr/share/nginx/friends/src/Core/Installer.php:508:			$help .= DI::l10n()->t('You can alternatively skip this procedure and perform a manual installation. Please see the file "INSTALL.txt" for instructions.') . EOL;
```

Related discussion:
https://hellquist.eu/display/f5e72586-1160-1e8e-10dc-9b3365179604?owt=fb944edd57f456b244eae85ebac19fca

**Comment by 4nanook** [comment]
Ok sorry.

**Comment by MrPetovan** [comment]
It’s okay, we just have to update the reference in a couple more places, your work is done here 🙂

**Comment by tobiasd** [comment]
Fixed the two @SpcCw mentioned. There is a third one in the `build.xml` file which I guess belongs to the doxygen tool.

**Comment by nupplaphil** [comment]
at least should be closed by #10337 :-)

**Comment by MrPetovan** [comment]
> at least should be closed by #10337 :-)

I believe you meant "at last" (endlich)?

**Comment by nupplaphil** [comment]
Yes, yes.. You're right :x

**Comment by annando** [comment]
@MrPetovan you know, concerning our knowledge of the English version we have to meat in the middle :grimacing:
