### ISSUE TITLE
Home gives user not found and php errors

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9069]
### Expected behavior
Expect to see a normal home page.
### Actual behavior
```
#0 /misc/www/friendica/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content()
#1 [internal function]: Friendica\Module\Profile\Index::content()
#2 /misc/www/friendica/src/App/Page.php(331): call_user_func()
#3 /misc/www/friendica/src/App/Page.php(387): Friendica\App\Page->initContent()
#4 /misc/www/friendica/src/App.php(560): Friendica\App\Page->run()
#5 /misc/www/friendica/index.php(42): Friendica\App->runFrontend()
#6 {main}
```
### Steps to reproduce the problem
After creating initial user and setting some of the basic admin stuff hit the home icon.
### Friendica version you encountered the problem
Development
see `example.com/friendica` on your Friendica node for the version information.
This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.
### Friendica source (git, zip)
git
### PHP version
7.4.9
### SQL version
MariaDB 10.3.22

**Comment by MrPetovan** [comment]
Sounds like #8949, solution may be here: https://github.com/friendica/friendica/issues/8550#issuecomment-620206601

**Comment by annando** [comment]
How is the current status? Can we close this issue?

**Comment by 4nanook** [comment]
Yes have new issue now.
