### ISSUE TITLE
PHP Warning in bin/console dbstructure update

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9070]
### Expected behavior
Update to progress without error.

### Actual behavior
bin/console dbstructure update
PHP Warning:  Use of undefined constant CURLE_OPERATION_TIMEOUTED - assumed 'CURLE_OPERATION_TIMEOUTED' (this will throw an Error in a future version of PHP) in /misc/www/friendica/boot.php on line 228

Warning: Use of undefined constant CURLE_OPERATION_TIMEOUTED - assumed 'CURLE_OPERATION_TIMEOUTED' (this will throw an Error in a future version of PHP) in /misc/www/friendica/boot.php on line 228

### Steps to reproduce the problem
Run bin/console dbstructure update
### Friendica version you encountered the problem
see `example.com/friendica` on your Friendica node for the version information.

This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.
### PHP version
7.4.9
### SQL version
MariaDB 10.3.22

**Comment by MrPetovan** [comment]
It sounds like you don't have the curl extension enabled, which Composer should have complained about when you ran the `install` command after cloning the git repository. Can you please run `php -i | grep curl` and paste the output here?

**Comment by 4nanook** [comment]
There appears to be a bug in my php.  If I enable curl as an extension, it bitches about it already being loaded, but if I do not, then it isn't there.  I've reverted to the "it bitches about it being loaded mode", that shows it's capabilities in phpinfo().  Now, I ran composer again and it brought down a bunch more modules but still home page looks the same.  Do I have to completely re-install or is there a way to recover from here?

**Comment by MrPetovan** [comment]
Can you go to `/admin/logs/` on your domain and enable the Friendica log in a location of your choice? It is relative to the Friendica root folder and must be writable by the web server. I'm still assuming you haven't updated your database config to allow for more `table_definition_cache`? This would explain the non-working Home.

**Comment by 4nanook** [comment]
Sorry I decided given all the initial trouble that perhaps the development
branch was not a good choice and so started over with stable.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
And now the stable is giving me exactly the same error.  Even though I have the various PHP modules all enabled.

**Comment by 4nanook** [comment]
I do not have a admin directory in my friendica root directory, this is what I have:

addon	     bin       build.xml  composer.json  config       database.sql  docblox.dist.xml  friendica_test_data.sql  include	  library  mod	 README.md    spec  static  update.php	 vendor   view
autotest.sh  boot.php  CHANGELOG  composer.lock  CREDITS.txt  doc	    Doxyfile	      images		       index.php  LICENSE  mods  ruleset.xml  src   tests   Vagrantfile  VERSION

Website didn't do wonderful things for the formatting.

**Comment by tobiasd** [comment]
The `/admin/logs/` is the URL path to the page in the admin panel. The entire URL is something like `https://example.com/admin/logs/`. On that page, you can configure the log-level for Friendica and dis-/enable taking logs.

**Comment by MrPetovan** [comment]
> And now the stable is giving me exactly the same error. Even though I have the various PHP modules all enabled.

The same PHP error or the same Home page error?

**Comment by 4nanook** [comment]
Same home page error.  I've enabled logs but nothing produced, thought perhaps I need to create the directory and file manually,
so did that, still no data being logged.  Also, if I change my password in my profile it no longer works, either the password I change
it to or the original from when the account was setup, but if I reset password, that password works, until I try to change it again.

**Comment by 4nanook** [comment]
I got some mysql errors relating to debian-maint-user; going to fix that and restart.

**Comment by MrPetovan** [comment]
> Sorry I decided given all the initial trouble that perhaps the development branch was not a good choice and so started over with stable.

This is another liability. Going from `stable` to `develop` is just about checking out the new branch, but the opposite isn't as straightforward, because we don't have an automatic process to downgrade the database structure. If you still want to stay on `stable`, you need to wipe out your database and start the install again to make sure you won't have issues with database structure mismatch.

Have you changed your database server configuration yet?

**Comment by annando** [comment]
AFAIK we used the views in the stable version as well. So an insufficient configuration will have an effect there as well. The develop branch itself is really stable at the moment. Several production machines are running with it.

**Comment by 4nanook** [comment]
Ok at this point I'm cleaning a bunch of crap out of MariaDB that is causing errors, they aren't errors that would affect
friendica just things with bad passwords, etc, but they litter the logs with so much crap it is difficult to find relevant errors,
then will make another attempt.  Also found I did not have argc/argv enabled on the cli version of PHP, so that might be
relevant.

**Comment by 4nanook** [comment]
On Tue, August 25, 2020 6:28 am, Hypolite Petovan wrote:
>> Sorry I decided given all the initial trouble that perhaps the
>> development branch was not a good choice and so started over with
>> stable.
>
> This is another liability. Going from `stable` to `develop` is just about
> checking out the new branch, but the opposite isn't as straightforward,
> because we don't have an automatic process to downgrade the database
> structure. If you still want to stay on `stable`, you need to wipe out
> your database and start the install again to make sure you won't have
> issues with database structure mismatch.
>
> Have you changed your database server configuration yet?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/friendica/friendica/issues/9070#issuecomment-680025232

     I blitzed everything, got every error out of my mariadb, it is running
perfectly and not a single slow query, I checked every single requirement
in the prerequesites, when I created my initial account Home looked okay,
but when I logged out and back in, it was fuxored there after.  However,
this time I did succeed in getting logging working turned on debugging and
attached voluminous logs to a new issue.  I went back to development
branch.

     I created a new issue since this was a new install again and is
somewhat different in that it seemed ok until I logged out and
logging is working this time.  I also attached apache error log and I
would have attached mariadb but no errors in the log to report so no
point.  I also added a phpinfo.php into the friendica directory so
you can see my php config for yourselves.

**Comment by 4nanook** [comment]
This no longer seems to be an issue so am closing.
