### ISSUE TITLE
Add support for uderscore in hashtag for twitter addon

### ISSUE THREAD

**Issue by ahangarha** [friendica/friendica#9071]
### Expected behavior
In Persian language, there are many cases we need to separate words in hashtag using ZWNJ and Underscore. While both of these characters are supported in Friendica, it is expected to be supported in twitter addon as well.

### Actual behavior
If one post something which has some Persian hashtag like #نرم‌افزار _آزاد  it gets poblished on twitter in separate form so that first part (نرم‌افزار) remains as hashtag but second part gets separated and becomes a regular word. 

### Steps to reproduce the problem
Simply post some like this in Freindica with twitter addon activated: "متن آزمایشی برای بررسی نمایش #نرم‌افزار_آزاد روی توییتر" and see what happens.

### Friendica version you encountered the problem
2020.07

### Friendica source (git, zip)
Not sure as it is not mine.

### PHP version
Not sure as it is not mine.

### SQL version
Not sure as it is not mine but I see database version is 1355.

**Comment by schmaker** [comment]
With discontinued Twitter API i think this issue can be closed

**Comment by ahangarha** [comment]
@schmaker Thanks for noticing this 👍🏾
