### ISSUE TITLE
Forum doesn't accept posts from ActivityPub unless someone follows the poster

### ISSUE THREAD

**Issue by vpzomtrrfrt** [friendica/friendica#9072]
### Expected behavior
I expect the forum to reshare any posts targeted at the forum profile.
### Actual behavior
Sending a note with a mention of the forum seems to be ignored, unless the author is followed by a user on the forum's instance
### Steps to reproduce the problem
- Send a Note addressed to the forum account (I used Pleroma for this)

The post seems to be discarded.

- Follow the author from a user account on the Friendica instance
- Send another Note to the forum account

This time it works.
### Friendica version you encountered the problem
9601f540
### Friendica source (git, zip)
git
### PHP version
7.4.9
### SQL version
10.1.30-MariaDB

**Comment by tobiasd** [comment]
Is the account you used to send the test message to the forum, member of the forum?

**Comment by annando** [comment]
Is the forum running on your system? If yes, please have a look in the logfile for entries with `tagDeliver` in it.

**Comment by vpzomtrrfrt** [comment]
Now it's working, not sure what happened here
