### ISSUE TITLE
Friendica ARRRGGGHH Can't Get Install to WORK!

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9075]
First, I blitzed everything, the code, the database, the whole shebang.  I fixed ALL errors in my mariadb install such that it
starts and runs 100% clean.  I fixed ALL errors in php such that IT starts and runs 100% clean.  I went through the list of prerequisites and checked that I had them all enabled and showing up in phpinfo() as well as non-PHP prerequisites.  When I
initially logged in, "HOME" did not show anything abnormal.  Then I attempted to change my password, which failed with no specific reason, and when I logged back in, failing with the new password but still working with the initial friendica supplied password, now home was messed up.  There are ZERO php errors and ZERO mariadb errors in the logs.  However, logging IS working now so I guess some minor headway.  I've added a function so you can view my phpinfo, https://friendica.eskimo.com/phpinfo.php

### Expected behavior
I expect to get a normal home page.  And I expect it to allow me to change my password, neither is happening.
### Actual behavior
I get this for a home page:
Not found

User not found.

#0 /misc/www/friendica/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content()
#1 [internal function]: Friendica\Module\Profile\Index::content()
#2 /misc/www/friendica/src/App/Page.php(331): call_user_func()
#3 /misc/www/friendica/src/App/Page.php(387): Friendica\App\Page->initContent()
#4 /misc/www/friendica/src/App.php(560): Friendica\App\Page->run()
#5 /misc/www/friendica/index.php(47): Friendica\App->runFrontend()
#6 {main}
Please note that I only got this after I logged out and back in again.

### Steps to reproduce the problem
Go through the install, create the initial account, login, attempt to change passwords on the account (which fails), logout and attempt to login with new password (which fails) and then attempt with old password (which succeeds), Then go to home.

### Friendica version you encountered the problem
see `example.com/friendica` on your Friendica node for the version information.

This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.

### Friendica source (git, zip)
git
### PHP version
php --version
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

PHP 7.4.9 (cgi-fcgi) (built: Aug  7 2020 14:30:01)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

I use suphp to launch php code with the ownership of the code owner and friendica has it's own user ID which it is owned by
and runs with.

### SQL version
mariadb --version
mariadb  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by 4nanook** [comment]
[friendica.log](https://github.com/friendica/friendica/files/5128647/friendica.log)
[error.log](https://github.com/friendica/friendica/files/5128662/error.log)
The mysql error log is empty so nothing to show.

**Comment by MrPetovan** [comment]
Thank you I was able to find this:
```
2020-08-26T08:38:00Z index [ERROR]: DB Error {"code":1146,"error":"Table 'friendica.owner-view' doesn't exist","callstack":"DBA::selectToArray, vier_community_info, vier_init, Page::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`blocked` = 0 AND `publish` = 1) ORDER BY `register_date` DESC LIMIT 0, 9"} - {"file":"Database.php","line":666,"function":"p","uid":"e8ff0b","process_id":1382641}
```
This view is used by the system to retrieve the information about a user. Without this information, we assume the user wasn't found.

Please run `bin/console dbstructure update` from the command line in your Friendica install folder to create these views and report any error the command outputs.

**Comment by 4nanook** [comment]
I ran the command as instructed, it returned almost immediately, still the same results.
I zipped the logs and run again, this is what is in the logs after the bin/dbstructure update:

2020-08-26T09:41:07Z index [ERROR]: DB Error {"code":1146,"error":"Table 'friendica.network-item-view' doesn't exist","callstack":"DBA::selectToArray, networkThreadedView, network_content, update_network_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent","params":"SELECT * FROM `network-item-view` WHERE (`uid` = 1 AND `unseen` = 1 AND 1) ORDER BY `commented` DESC LIMIT 100"} - {"file":"Database.php","line":666,"function":"p","uid":"9e412e","process_id":1453920}
2020-08-26T09:41:16Z index [INFO]: Start system mode query [] - {"file":"poco.php","line":127,"function":"poco_init","uid":"c812ca","process_id":1454497}
2020-08-26T09:41:16Z index [ERROR]: DB Error {"code":1146,"error":"Table 'friendica.owner-view' doesn't exist","callstack":"DBA::selectToArray, poco_init, LegacyModule::runModuleFunction, LegacyModule::init, call_user_func, Module::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`net-publish` = 1) LIMIT 0, 1"} - {"file":"Database.php","line":666,"function":"p","uid":"c812ca","process_id":1454497}
2020-08-26T09:41:16Z index [INFO]: Query done [] - {"file":"poco.php","line":143,"function":"poco_init","uid":"c812ca","process_id":1454497}
2020-08-26T09:41:16Z index [INFO]: End of poco [] - {"file":"poco.php","line":326,"function":"poco_init","uid":"c812ca","process_id":1454497}
2020-08-26T09:41:34Z index [INFO]: DELETE FROM `session`  WHERE (`expire` < 1598434894) {"callstack":"Database::gc, session_start, Native::start, Dice::Dice\\{closure}, Dice::create, Dice::Dice\\{closure}","internal_callstack":{"session:[\"`expire` < ?\",1598434894]":true}} - {"file":"Database.php","line":1303,"function":"delete","uid":"32f0fb","process_id":1455494}

Still the same on home page.

**Comment by 4nanook** [comment]
Didn't mean to close, accidental.  No error in mariadb.log or apache error.log.

**Comment by MrPetovan** [comment]
What about `bin/console dbstructure update -v` ? It should display more information.

**Comment by 4nanook** [comment]
This is all that it showed:

Executable: /misc/www/friendica/bin/console.php
Arguments: array (
  0 => 'dbstructure',
  1 => 'update',
)
Options: array (
  'v' => 1,
)
Command: dbstructure
Class: Friendica\Console\DatabaseStructure
Arguments: array (
  0 => 'update',
)
Options: array (
  'v' => 1,
)

**Comment by 4nanook** [comment]
These are the tables that exist in the database:

| 2fa_app_specific_password |
| 2fa_recovery_codes        |
| addon                     |
| apcontact                 |
| attach                    |
| auth_codes                |
| cache                     |
| challenge                 |
| clients                   |
| config                    |
| contact                   |
| contact-relation          |
| conv                      |
| conversation              |
| diaspora-interaction      |
| event                     |
| fcontact                  |
| fsuggest                  |
| group                     |
| group_member              |
| gserver                   |
| gserver-tag               |
| hook                      |
| inbox-status              |
| intro                     |
| item                      |
| item-activity             |
| item-content              |
| item-uri                  |
| locks                     |
| mail                      |
| mailacct                  |
| manage                    |
| notify                    |
| notify-threads            |
| oembed                    |
| openwebauth-token         |
| parsed_url                |
| participation             |
| pconfig                   |
| permissionset             |
| photo                     |
| post-category             |
| post-delivery-data        |
| post-tag                  |
| process                   |
| profile                   |
| profile_check             |
| profile_field             |
| push_subscriber           |
| register                  |
| search                    |
| session                   |
| storage                   |
| tag                       |
| thread                    |
| tokens                    |
| user                      |
| user-contact              |
| user-item                 |
| userd                     |
| verb                      |
| worker-ipc                |
| workerqueue               |

**Comment by 4nanook** [comment]
[friendica.log](https://github.com/friendica/friendica/files/5128647/friendica.log)
[error.log](https://github.com/friendica/friendica/files/5128662/error.log)
The mysql error log is empty so nothing to show.

**Comment by 4nanook** [comment]
[friendica.zip](https://github.com/friendica/friendica/files/5129096/friendica.zip)
A zip file of mysqldump of the database.

**Comment by MrPetovan** [comment]
Can you please run these queries manually on your Friendica database?
```sql

--
-- VIEW category-view
--
DROP VIEW IF EXISTS `category-view`;
CREATE VIEW `category-view` AS SELECT 
	`post-category`.`uri-id` AS `uri-id`,
	`post-category`.`uid` AS `uid`,
	`item-uri`.`uri` AS `uri`,
	`item-uri`.`guid` AS `guid`,
	`post-category`.`type` AS `type`,
	`post-category`.`tid` AS `tid`,
	`tag`.`name` AS `name`,
	`tag`.`url` AS `url`
	FROM `post-category`
			INNER JOIN `item-uri` ON `item-uri`.id = `post-category`.`uri-id`
			LEFT JOIN `tag` ON `post-category`.`tid` = `tag`.`id`;

--
-- VIEW tag-view
--
DROP VIEW IF EXISTS `tag-view`;
CREATE VIEW `tag-view` AS SELECT 
	`post-tag`.`uri-id` AS `uri-id`,
	`item-uri`.`uri` AS `uri`,
	`item-uri`.`guid` AS `guid`,
	`post-tag`.`type` AS `type`,
	`post-tag`.`tid` AS `tid`,
	`post-tag`.`cid` AS `cid`,
	CASE `cid` WHEN 0 THEN `tag`.`name` ELSE `contact`.`name` END AS `name`,
	CASE `cid` WHEN 0 THEN `tag`.`url` ELSE `contact`.`url` END AS `url`
	FROM `post-tag`
			INNER JOIN `item-uri` ON `item-uri`.id = `post-tag`.`uri-id`
			LEFT JOIN `tag` ON `post-tag`.`tid` = `tag`.`id`
			LEFT JOIN `contact` ON `post-tag`.`cid` = `contact`.`id`;

--
-- VIEW network-item-view
--
DROP VIEW IF EXISTS `network-item-view`;
CREATE VIEW `network-item-view` AS SELECT 
	`item`.`parent-uri-id` AS `uri-id`,
	`item`.`parent-uri` AS `uri`,
	`item`.`parent` AS `parent`,
	`item`.`received` AS `received`,
	`item`.`commented` AS `commented`,
	`item`.`created` AS `created`,
	`item`.`uid` AS `uid`,
	`item`.`starred` AS `starred`,
	`item`.`mention` AS `mention`,
	`item`.`network` AS `network`,
	`item`.`unseen` AS `unseen`,
	`item`.`gravity` AS `gravity`,
	`item`.`contact-id` AS `contact-id`
	FROM `item`
			INNER JOIN `thread` ON `thread`.`iid` = `item`.`parent`
			STRAIGHT_JOIN `contact` ON `contact`.`id` = `thread`.`contact-id`
			LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = `thread`.`uid`
			LEFT JOIN `user-contact` AS `author` ON `author`.`uid` = `thread`.`uid` AND `author`.`cid` = `thread`.`author-id`
			LEFT JOIN `user-contact` AS `owner` ON `owner`.`uid` = `thread`.`uid` AND `owner`.`cid` = `thread`.`owner-id`
			WHERE `thread`.`visible` AND NOT `thread`.`deleted` AND NOT `thread`.`moderated`
			AND (NOT `contact`.`readonly` AND NOT `contact`.`blocked` AND NOT `contact`.`pending`)
			AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`)
			AND (`author`.`blocked` IS NULL OR NOT `author`.`blocked`)
			AND (`owner`.`blocked` IS NULL OR NOT `owner`.`blocked`);

--
-- VIEW network-thread-view
--
DROP VIEW IF EXISTS `network-thread-view`;
CREATE VIEW `network-thread-view` AS SELECT 
	`item`.`uri-id` AS `uri-id`,
	`item`.`uri` AS `uri`,
	`item`.`parent-uri-id` AS `parent-uri-id`,
	`thread`.`iid` AS `parent`,
	`thread`.`received` AS `received`,
	`thread`.`commented` AS `commented`,
	`thread`.`created` AS `created`,
	`thread`.`uid` AS `uid`,
	`thread`.`starred` AS `starred`,
	`thread`.`mention` AS `mention`,
	`thread`.`network` AS `network`,
	`thread`.`contact-id` AS `contact-id`
	FROM `thread`
			STRAIGHT_JOIN `contact` ON `contact`.`id` = `thread`.`contact-id`
			STRAIGHT_JOIN `item` ON `item`.`id` = `thread`.`iid`
			LEFT JOIN `user-item` ON `user-item`.`iid` = `item`.`id` AND `user-item`.`uid` = `thread`.`uid`
			LEFT JOIN `user-contact` AS `author` ON `author`.`uid` = `thread`.`uid` AND `author`.`cid` = `thread`.`author-id`
			LEFT JOIN `user-contact` AS `owner` ON `owner`.`uid` = `thread`.`uid` AND `owner`.`cid` = `thread`.`owner-id`
			WHERE `thread`.`visible` AND NOT `thread`.`deleted` AND NOT `thread`.`moderated`
			AND (NOT `contact`.`readonly` AND NOT `contact`.`blocked` AND NOT `contact`.`pending`)
			AND (`user-item`.`hidden` IS NULL OR NOT `user-item`.`hidden`)
			AND (`author`.`blocked` IS NULL OR NOT `author`.`blocked`)
			AND (`owner`.`blocked` IS NULL OR NOT `owner`.`blocked`);

--
-- VIEW owner-view
--
DROP VIEW IF EXISTS `owner-view`;
CREATE VIEW `owner-view` AS SELECT 
	`contact`.`id` AS `id`,
	`contact`.`uid` AS `uid`,
	`contact`.`created` AS `created`,
	`contact`.`updated` AS `updated`,
	`contact`.`self` AS `self`,
	`contact`.`remote_self` AS `remote_self`,
	`contact`.`rel` AS `rel`,
	`contact`.`duplex` AS `duplex`,
	`contact`.`network` AS `network`,
	`contact`.`protocol` AS `protocol`,
	`contact`.`name` AS `name`,
	`contact`.`nick` AS `nick`,
	`contact`.`location` AS `location`,
	`contact`.`about` AS `about`,
	`contact`.`keywords` AS `keywords`,
	`contact`.`gender` AS `gender`,
	`contact`.`xmpp` AS `xmpp`,
	`contact`.`attag` AS `attag`,
	`contact`.`avatar` AS `avatar`,
	`contact`.`photo` AS `photo`,
	`contact`.`thumb` AS `thumb`,
	`contact`.`micro` AS `micro`,
	`contact`.`site-pubkey` AS `site-pubkey`,
	`contact`.`issued-id` AS `issued-id`,
	`contact`.`dfrn-id` AS `dfrn-id`,
	`contact`.`url` AS `url`,
	`contact`.`nurl` AS `nurl`,
	`contact`.`addr` AS `addr`,
	`contact`.`alias` AS `alias`,
	`contact`.`pubkey` AS `pubkey`,
	`contact`.`prvkey` AS `prvkey`,
	`contact`.`batch` AS `batch`,
	`contact`.`request` AS `request`,
	`contact`.`notify` AS `notify`,
	`contact`.`poll` AS `poll`,
	`contact`.`confirm` AS `confirm`,
	`contact`.`poco` AS `poco`,
	`contact`.`aes_allow` AS `aes_allow`,
	`contact`.`ret-aes` AS `ret-aes`,
	`contact`.`usehub` AS `usehub`,
	`contact`.`subhub` AS `subhub`,
	`contact`.`hub-verify` AS `hub-verify`,
	`contact`.`last-update` AS `last-update`,
	`contact`.`success_update` AS `success_update`,
	`contact`.`failure_update` AS `failure_update`,
	`contact`.`name-date` AS `name-date`,
	`contact`.`uri-date` AS `uri-date`,
	`contact`.`avatar-date` AS `avatar-date`,
	`contact`.`avatar-date` AS `picdate`,
	`contact`.`term-date` AS `term-date`,
	`contact`.`last-item` AS `last-item`,
	`contact`.`priority` AS `priority`,
	`contact`.`blocked` AS `blocked`,
	`contact`.`block_reason` AS `block_reason`,
	`contact`.`readonly` AS `readonly`,
	`contact`.`writable` AS `writable`,
	`contact`.`forum` AS `forum`,
	`contact`.`prv` AS `prv`,
	`contact`.`contact-type` AS `contact-type`,
	`contact`.`hidden` AS `hidden`,
	`contact`.`archive` AS `archive`,
	`contact`.`pending` AS `pending`,
	`contact`.`deleted` AS `deleted`,
	`contact`.`unsearchable` AS `unsearchable`,
	`contact`.`sensitive` AS `sensitive`,
	`contact`.`baseurl` AS `baseurl`,
	`contact`.`reason` AS `reason`,
	`contact`.`closeness` AS `closeness`,
	`contact`.`info` AS `info`,
	`contact`.`profile-id` AS `profile-id`,
	`contact`.`bdyear` AS `bdyear`,
	`contact`.`bd` AS `bd`,
	`contact`.`notify_new_posts` AS `notify_new_posts`,
	`contact`.`fetch_further_information` AS `fetch_further_information`,
	`contact`.`ffi_keyword_denylist` AS `ffi_keyword_denylist`,
	`user`.`parent-uid` AS `parent-uid`,
	`user`.`guid` AS `guid`,
	`user`.`nickname` AS `nickname`,
	`user`.`email` AS `email`,
	`user`.`openid` AS `openid`,
	`user`.`timezone` AS `timezone`,
	`user`.`language` AS `language`,
	`user`.`register_date` AS `register_date`,
	`user`.`login_date` AS `login_date`,
	`user`.`default-location` AS `default-location`,
	`user`.`allow_location` AS `allow_location`,
	`user`.`theme` AS `theme`,
	`user`.`pubkey` AS `upubkey`,
	`user`.`prvkey` AS `uprvkey`,
	`user`.`sprvkey` AS `sprvkey`,
	`user`.`spubkey` AS `spubkey`,
	`user`.`verified` AS `verified`,
	`user`.`blockwall` AS `blockwall`,
	`user`.`hidewall` AS `hidewall`,
	`user`.`blocktags` AS `blocktags`,
	`user`.`unkmail` AS `unkmail`,
	`user`.`cntunkmail` AS `cntunkmail`,
	`user`.`notify-flags` AS `notify-flags`,
	`user`.`page-flags` AS `page-flags`,
	`user`.`account-type` AS `account-type`,
	`user`.`prvnets` AS `prvnets`,
	`user`.`maxreq` AS `maxreq`,
	`user`.`expire` AS `expire`,
	`user`.`account_removed` AS `account_removed`,
	`user`.`account_expired` AS `account_expired`,
	`user`.`account_expires_on` AS `account_expires_on`,
	`user`.`expire_notification_sent` AS `expire_notification_sent`,
	`user`.`def_gid` AS `def_gid`,
	`user`.`allow_cid` AS `allow_cid`,
	`user`.`allow_gid` AS `allow_gid`,
	`user`.`deny_cid` AS `deny_cid`,
	`user`.`deny_gid` AS `deny_gid`,
	`user`.`openidserver` AS `openidserver`,
	`profile`.`publish` AS `publish`,
	`profile`.`net-publish` AS `net-publish`,
	`profile`.`hide-friends` AS `hide-friends`,
	`profile`.`prv_keywords` AS `prv_keywords`,
	`profile`.`pub_keywords` AS `pub_keywords`,
	`profile`.`address` AS `address`,
	`profile`.`locality` AS `locality`,
	`profile`.`region` AS `region`,
	`profile`.`postal-code` AS `postal-code`,
	`profile`.`country-name` AS `country-name`,
	`profile`.`homepage` AS `homepage`,
	`profile`.`dob` AS `dob`
	FROM `user`
			INNER JOIN `contact` ON `contact`.`uid` = `user`.`uid` AND `contact`.`self`
			INNER JOIN `profile` ON `profile`.`uid` = `user`.`uid`;

--
-- VIEW pending-view
--
DROP VIEW IF EXISTS `pending-view`;
CREATE VIEW `pending-view` AS SELECT 
	`register`.`id` AS `id`,
	`register`.`hash` AS `hash`,
	`register`.`created` AS `created`,
	`register`.`uid` AS `uid`,
	`register`.`password` AS `password`,
	`register`.`language` AS `language`,
	`register`.`note` AS `note`,
	`contact`.`self` AS `self`,
	`contact`.`name` AS `name`,
	`contact`.`url` AS `url`,
	`contact`.`micro` AS `micro`,
	`user`.`email` AS `email`,
	`contact`.`nick` AS `nick`
	FROM `register`
			INNER JOIN `contact` ON `register`.`uid` = `contact`.`uid`
			INNER JOIN `user` ON `register`.`uid` = `user`.`uid`;

--
-- VIEW tag-search-view
--
DROP VIEW IF EXISTS `tag-search-view`;
CREATE VIEW `tag-search-view` AS SELECT 
	`post-tag`.`uri-id` AS `uri-id`,
	`item`.`id` AS `iid`,
	`item`.`uri` AS `uri`,
	`item`.`guid` AS `guid`,
	`item`.`uid` AS `uid`,
	`item`.`private` AS `private`,
	`item`.`wall` AS `wall`,
	`item`.`origin` AS `origin`,
	`item`.`gravity` AS `gravity`,
	`item`.`received` AS `received`,
	`tag`.`name` AS `name`
	FROM `post-tag`
			INNER JOIN `tag` ON `tag`.`id` = `post-tag`.`tid`
			INNER JOIN `item` ON `item`.`uri-id` = `post-tag`.`uri-id`
			WHERE `post-tag`.`type` = 1;

--
-- VIEW workerqueue-view
--
DROP VIEW IF EXISTS `workerqueue-view`;
CREATE VIEW `workerqueue-view` AS SELECT 
	`process`.`pid` AS `pid`,
	`workerqueue`.`priority` AS `priority`
	FROM `process`
			INNER JOIN `workerqueue` ON `workerqueue`.`pid` = `process`.`pid`
			WHERE NOT `workerqueue`.`done`;
```

**Comment by 4nanook** [comment]
I got an error on the first query so did not attempt to run the rest, here is the session:

DROP VIEW IF EXISTS `category-view`;
Query OK, 0 rows affected, 1 warning (0.000 sec)

MariaDB [friendica]> CREATE VIEW `category-view` AS SELECT 
    -> `post-category`.`uri-id` AS `uri-id`,
    -> `post-category`.`uid` AS `uid`,
    -> `item-uri`.`uri` AS `uri`,
    -> `item-uri`.`guid` AS `guid`,
    -> `post-category`.`type` AS `type`,
    -> `post-category`.`tid` AS `tid`,
    -> `tag`.`name` AS `name`,
    -> `tag`.`url` AS `url`
    -> FROM `post-category`
    -> 
Display all 1881 possibilities? (y or n)
    -> NER JOIN `item-uri` ON `item-uri`.id = `post-category`.`uri-id`
    -> 
Display all 1881 possibilities? (y or n)
2fa_app_specific_password                  MASTER_USER                                apcontact.inbox                            hide-friends                               port
2fa_app_specific_password.description      MATCH                                      apcontact.manually-approve                 hidewall                                   post-category
2fa_app_specific_password.generated        MAX                                        apcontact.name                             homepage                                   post-category.tid
2fa_app_specific_password.hashed_password  MAX_CONNECTIONS_PER_HOUR                   apcontact.nick                             hometown                                   post-category.type
2fa_app_specific_password.id               MAX_QUERIES_PER_HOUR                       apcontact.outbox                           hook                                       post-category.uid
2fa_app_specific_password.last_used        MAX_ROWS                                   apcontact.photo                            hook.file                                  post-category.uri-id
2fa_app_specific_password.uid              MAX_UPDATES_PER_HOUR                       apcontact.pubkey                           hook.function                              post-delivery-data
2fa_recovery_codes                         MAX_USER_CONNECTIONS                       apcontact.sharedinbox                      hook.hook                                  post-delivery-data.activitypub
2fa_recovery_codes.code                    MBRCONTAINS                                apcontact.statuses_count                   hook.id                                    post-delivery-data.dfrn
2fa_recovery_codes.generated               MBRDISJOINT                                apcontact.subscribe                        hook.priority                              post-delivery-data.diaspora
2fa_recovery_codes.uid                     MBREQUAL                                   apcontact.type                             howlong                                    post-delivery-data.inform
2fa_recovery_codes.used                    MBRINTERSECTS                              apcontact.updated                          hub-verify                                 post-delivery-data.legacy_dfrn
?                                          MBROVERLAPS                                apcontact.url                              iaid                                       post-delivery-data.ostatus
ABS                                        MBRTOUCHES                                 apcontact.uuid                             icid                                       post-delivery-data.postopts
ACOS                                       MBRWITHIN                                  app                                        icon                                       post-delivery-data.queue_count
ACTION                                     MD5                                        archive                                    id                                         post-delivery-data.queue_done
ADD                                        MEDIUM                                     attach                                     ignore                                     post-delivery-data.queue_failed
ADDDATE                                    MEDIUMBLOB                                 attach.allow_cid                           ignored                                    post-delivery-data.uri-id
ADDTIME                                    MEDIUMINT                                  attach.allow_gid                           iid                                        post-tag
AES_DECRYPT                                MEDIUMTEXT                                 attach.backend-class                       inbox                                      post-tag.cid
AES_ENCRYPT                                MERGE                                      attach.backend-ref                         inbox-status                               post-tag.tid
AFTER                                      MICROSECOND                                attach.created                             inbox-status.archive                       post-tag.type
AGAINST                                    MID                                        attach.data                                inbox-status.created                       post-tag.uri-id
AGGREGATE                                  MIDDLEINT                                  attach.deny_cid                            inbox-status.failure                       post-type
ALGORITHM                                  MIGRATE                                    attach.deny_gid                            inbox-status.previous                      postal-code
ALL                                        MIN                                        attach.edited                              inbox-status.shared                        postopts
ALTER                                      MINUTE                                     attach.filename                            inbox-status.success                       previous
ANALYZE                                    MINUTE_MICROSECOND                         attach.filesize                            inbox-status.url                           print
AND                                        MINUTE_SECOND                              attach.filetype                            info                                       priority
ANY                                        MIN_ROWS                                   attach.hash                                inform                                     private
AREA                                       MLINEFROMTEXT                              attach.id                                  information_schema                         process
AS                                         MLINEFROMWKB                               attach.uid                                 installed                                  process.command
ASBINARY                                   MOD                                        attag                                      interaction                                process.created
ASC                                        MODE                                       auth_codes                                 interest                                   process.pid
ASCII                                      MODIFIES                                   auth_codes.client_id                       intro                                      profile
ASENSITIVE                                 MODIFY                                     auth_codes.expires                         intro.blocked                              profile-id
ASIN                                       MONTH                                      auth_codes.id                              intro.contact-id                           profile-name
ASTEXT                                     MONTHNAME                                  auth_codes.redirect_uri                    intro.datetime                             profile.about
ASWKB                                      MPOINTFROMTEXT                             auth_codes.scope                           intro.duplex                               profile.address
ASWKT                                      MPOINTFROMWKB                              author-avatar                              intro.fid                                  profile.book
ATAN                                       MPOLYFROMTEXT                              author-id                                  intro.hash                                 profile.contact
ATAN2                                      MPOLYFROMWKB                               author-link                                intro.id                                   profile.country-name
AUTO_INCREMENT                             MULTILINESTRING                            author-name                                intro.ignore                               profile.dislikes
AVG                                        MULTILINESTRINGFROMTEXT                    avatar                                     intro.knowyou                              profile.dob
AVG_ROW_LENGTH                             MULTILINESTRINGFROMWKB                     avatar-date                                intro.note                                 profile.education
BACKUP                                     MULTIPOINT                                 backend-class                              intro.uid                                  profile.film
BDB                                        MULTIPOINTFROMTEXT                         backend-ref                                is-default                                 profile.gender
BEFORE                                     MULTIPOINTFROMWKB                          baseurl                                    issued-id                                  profile.hide-friends
BEGIN                                      MULTIPOLYGON                               batch                                      item                                       profile.homepage
BENCHMARK                                  MULTIPOLYGONFROMTEXT                       bd                                         item-activity                              profile.hometown
BERKELEYDB                                 MULTIPOLYGONFROMWKB                        bdyear                                     item-activity.activity                     profile.howlong
BETWEEN                                    MUTEX                                      block_reason                               item-activity.id                           profile.id
BIGINT                                     NAME                                       blocked                                    item-activity.uri                          profile.interest
BIN                                        NAMES                                      blocktags                                  item-activity.uri-hash                     profile.is-default
BINARY                                     NAME_CONST                                 blockwall                                  item-activity.uri-id                       profile.likes
BINLOG                                     NATIONAL                                   body                                       item-content                               profile.locality
    ->  `tag` ON `post-category`.`tid` = `tag`.`id`;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`tag` ON `post-category`.`tid` = `tag`.`id`' at line 12
MariaDB [friendica]> 

Sorry did not get the very first part, I did use friendica; before that and started with the MySQL friendica> prompt but missed that part in the cut-n-paste.

**Comment by 4nanook** [comment]
I should have said 2nd query failed, drop view succeeded.

**Comment by MrPetovan** [comment]
Somehow the tabs were intepreted as auto-completion, let's try the `CREATE VIEW` command without whitespaces:
```sql
CREATE VIEW `category-view` AS SELECT 
`post-category`.`uri-id` AS `uri-id`,
`post-category`.`uid` AS `uid`,
`item-uri`.`uri` AS `uri`,
`item-uri`.`guid` AS `guid`,
`post-category`.`type` AS `type`,
`post-category`.`tid` AS `tid`,
`tag`.`name` AS `name`,
`tag`.`url` AS `url`
FROM `post-category`
INNER JOIN `item-uri` ON `item-uri`.id = `post-category`.`uri-id`
LEFT JOIN `tag` ON `post-category`.`tid` = `tag`.`id`;
```

**Comment by 4nanook** [comment]
This is an explanation I found for the error:

Fix ERROR 1064 (42000) while creating a database in MySQL?
MySQLMySQLi Database

The ERROR 1064 (42000) mainly occurs when the syntax isn’t set correctly i.e. error in applying the backtick symbol or while creating a database without them can also create an error, if you will use hyphen in the name, for example, Demo-Table will result in ERROR 1064 (42000).

To remove the error, you need to use backtick around the database name properly or use nothing. Following is the syntax wherein we haven’t used the backtick. This works correctly −

create database yourDatabaseName;

Since adding hyhen to the database name will result in an error. Let us implement it while creating the database name −

mysql> create database customer-tracker;

This will produce the following error since we used hyphen in the database name, which isn’t acceptable −

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near '-tracker' at line 1

Still, we can fix the hyphen in the database name by surrounding the name with backtick symbol −

mysql> create database `customer-tracker`;

This will produce the following output −

Query OK, 1 row affected (0.21 sec)

Now database is created successfully.
raja

Not sure how this error applies since you are creating a view not a database and there are already backticks.

**Comment by MrPetovan** [comment]
Please see my previous comment if you missed it.

**Comment by 4nanook** [comment]
Ok, yes timing thing, you and I cross-typing messages.  I tried that query it failed with a permission error:

MariaDB [friendica]> CREATE VIEW `category-view` AS SELECT 
    -> `post-category`.`uri-id` AS `uri-id`,
    -> `post-category`.`uid` AS `uid`,
    -> `item-uri`.`uri` AS `uri`,
    -> `item-uri`.`guid` AS `guid`,
    -> `post-category`.`type` AS `type`,
    -> `post-category`.`tid` AS `tid`,
    -> `tag`.`name` AS `name`,
    -> `tag`.`url` AS `url`
    -> FROM `post-category`
    -> INNER JOIN `item-uri` ON `item-uri`.id = `post-category`.`uri-id`
    -> LEFT JOIN `tag` ON `post-category`.`tid` = `tag`.`id`;
ERROR 1142 (42000): CREATE VIEW command denied to user 'friendica'@'localhost' for table 'category-view'
MariaDB [friendica]> Bye

Here is how I created the database to begin with, I used a script, $1 is "friendica" and $2 is the password:

mysql -u root -p << EOF
CREATE USER '$1'@'localhost' IDENTIFIED BY '$2';
CREATE USER '$1'@'%.eskimo.com' IDENTIFIED BY '$2';
CREATE USER '$1'@'eskimo.com' IDENTIFIED BY '$2';
CREATE DATABASE $1;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'%.eskimo.com';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'eskimo.com';
EOF

Do I need t do something different creating the database?

**Comment by MrPetovan** [comment]
Yes, you need the `CREATE VIEW` privilege on top of the others that are listed in this script.

So it would be 
```bash
mysql -u root -p << EOF
CREATE USER '$1'@'localhost' IDENTIFIED BY '$2';
CREATE USER '$1'@'%.eskimo.com' IDENTIFIED BY '$2';
CREATE USER '$1'@'eskimo.com' IDENTIFIED BY '$2';
CREATE DATABASE $1;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE VIEW, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE VIEW,, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'%.eskimo.com';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE VIEW,, ALTER, INDEX, DROP, LOCK TABLES ON $1.*
TO '$1'@'eskimo.com';
EOF
```

**Comment by 4nanook** [comment]
Thank you.  Had to edit the rest of the white space out of the rest of the queries but other than that everything went.  I modified my script to add CREATE VIEW for future  use.  Thank you.  Now Home displays normally, will proceed to try to change my password, etc and finish setup and see what else I can explode.  Thanks for your prompt and courteous assistance

**Comment by MrPetovan** [comment]
It's my pleasure, thank you for using Friendica!
