### ISSUE TITLE
Storage files missing - contact's avatar returns an error

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#9077]
This is not an issue but something which happens after a wrong manipulation.

I switch storage from database to files. But with wrong rights permissions on a docker volume and some wrong actions I lost a part of my files.

So all uploaded files disappeared and some contact's avatar are not anymore present. My uploaded files are lost but it is not so important. I'm wondering if there is a way to initialize contact's avatar?

At the moment front is trying to get the photo id but server responds internal Error : 

```
Invalid photo with id 25640.

#0 [internal function]: Friendica\Module\Photo::init(Array)
#1 /var/www/html/src/App/Module.php(271): call_user_func(Array, Array)
#2 /var/www/html/src/App.php(571): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Array, Array)
#3 /var/www/html/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#4 {main}
```

Would it be possible to do something to refresh all contacts for example ?

Thank you

**Comment by valvin1** [comment]
or maybe is there a way to get back some files from database if it has not been yet removed ?

**Comment by cnleo** [comment]
I had similar problems with the switch to file-storage. I had luck that only the avatar/profile images went gone (and my early posts of the lack of migration progress). You can go to your contacts and refresh the contact data. But you must do it for every contact. Because, only there is still something left to click.

```
https://*host*/profile/*you*/contacts
hover on a contact --> “view contact”
switch from “profile” to “advanced” - contact settings panel
click “refresh contact data”
```

**Comment by valvin1** [comment]
@cnleo thank you, I've tested on a friendica contact and unfortunately it didn't work :( On Mastodon contact I don't have this option.

**Comment by valvin1** [comment]
I've tried [tips](https://friendica.valvin.fr/display/7f2cc12a-155f-479e-ba8e-719271689556) given by @annando but unfortunately it hasn't work. Without contact thumbnails UI is very ugly.

Does doing a `bin/console avatar update` is hard to do ?

**Comment by valvin1** [comment]
Oh I had a look to code and found there were 3 columns for the photo.

I did ``update contact set `photo`='', `thumb`='', `micro`='';``

First time I played only with `photo` column.

Now image are coming back :)
