### ISSUE TITLE
Browser UserAgentString for WebOS missing

### ISSUE THREAD

**Issue by davodego** [friendica/friendica#908]
Please add UserAgentString for WebOS devices.

HP Tochpad: Mozilla/5.0 (hp-tablet; Linux; hpwOS/3.0.0; U; en-US) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/233.70 Safari/534.6 TouchPad/1.0 

HP Pre3: Mozilla/5.0 (webOS/2.2.4; U; de-DE) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/221.56 Safari/534.6 Pre/3.0

**Comment by Beanow** [comment]
I think this is for detecting mobile devices?
A more robust way would be to move to media queries and a responsive design with the upcoming redesign. In the mean time this is a bug, not a feature.

**Comment by silke** [comment]
@davodego Can you confirm this is fixed now?

**Comment by davodego** [comment]
Yes I can confirm, its fixed. Friendica updated to 3.4.0 today. Webos Devices show friendica in mobile theme. Tested with HP TochPad (webos 3.0.5), HP Veer (webos 2.2.4) and Palm Pre Plus (webos 2.1.1).
Thanks...
