### ISSUE TITLE
no text background color in frio accented themes with background image

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9081]
### Expected behavior

Having a solid background color underneath the text of postings for readability.

### Actual behavior

The Light Accented theme works as expected. But the Dark and Black Accented themes do not show the tinted background color underneath the text of postings, so they become unreadable.

![friendica_fria_accented](https://user-images.githubusercontent.com/433490/91384267-69d61980-e82e-11ea-8f1a-46fbd7f9c221.jpg)

### Steps to reproduce the problem

* Choose the dark or black accented theme variant of the frio theme
* configure a backgroound image

### Friendica version you encountered the problem

2020..09 develop 8f1d2b00a5d7db8d37fb589f7ebe61dc0ed14368

**Comment by MrPetovan** [comment]
Thanks, I'll remove the possibility to add a background image for the dark and black schemes, they weren't meant for that at all.
