### ISSUE TITLE
frio: reposts / shares username and link to original post are black when post is not in focus (mobile only)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9089]
Using frio, dark with blue accent on iOS, the username and link to original post of reposts / reshares with comment are shown in black which is very unreadable. Once the post is in focus the link color comes into effect.

This still is a problem making it unnecessarily difficult to read. The two elements in black have the same colours as the surrounding post.

Interestingly this issue is limited to the mobile version of frio. On desktop the colours are fine.

2020.09-dev https://squeet.me Datenbankversion 1365 Post-Update-Version 1350.

![123](https://user-images.githubusercontent.com/5708172/91634218-03e4c000-e9ef-11ea-918a-fa750a95ce7f.jpeg)

**Comment by vinzv** [comment]
I can confirm that. Desktop vs. mobile view:
![image](https://user-images.githubusercontent.com/74432/95131888-26d96100-075f-11eb-9e09-f596f03a2aa8.png) ![image](https://user-images.githubusercontent.com/74432/95131905-3062c900-075f-11eb-93bb-d532a3d54850.png)

It looks like `.shared_header a` from global.css does not get overwritten by style.pcss.
