### ISSUE TITLE
frio: body field exceeds post modal when content reaches max height

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9090]
### Expected behavior
When I write a post with a lot of characters or when I reshare a larger post the body input should enable scrolling when the bottom of the input field (text area) is reached.
In other words: how it is on stable.

### Actual behavior
When using **mobile device** (phone/tablet): Instead of enabling scrolling the input field for the body (text area) is growing in height and starts to exceed the post modal window. See red marks.

![IMG_20200829_125729](https://user-images.githubusercontent.com/3656054/91635442-ddc41d80-e9f8-11ea-92b0-c460f1c82167.png)

### Steps to reproduce the problem
Open post modal on mobile. Start adding newlines until the cursor gets to the bottom of the body text area. Continue to add newlines. Or try to reshare a large post using a mobile device.

I'm using Android 7 and 10 with latest Chrome browser.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by wiwie** [comment]
While I do observe the same behaviour I actually felt this worked better for me than enabling scrolling.

And that is because my device screen is so small that there was barely any scroll space as the rest of the editor dialog takes up quite some of the vertical space already. And secondly, I had all kinds of weird "navigating issues" when I actually tried to scroll in the field or changed the cursor position. Often I couldn't scroll all the way to the bottom or to the top and the cursor was laggy.

**Comment by MrPetovan** [comment]
If we intentionally kept that text area that big, it still shouldn't overflow the modal window.

**Comment by MrPetovan** [comment]
This is a real gem of a doozy. The autosize javascript library we use to increase its size automatically with the content can work with a maximum height, but it depends on the height of the modal window, which is a fixed dynamic element. No idea how to make both play nice with each other.

**Comment by AlfredSK** [comment]
There is still an issue with the preview. I should have mentioned that in the original issue description though. See the following examples with stable and RC branch...

**Preview in stable:**

![preview-stable](https://user-images.githubusercontent.com/3656054/93014163-0c242a00-f5af-11ea-9745-cad4fc955786.png)

**Preview in RC:**

![preview-rc](https://user-images.githubusercontent.com/3656054/93014167-1ba37300-f5af-11ea-9d5c-15c6040071dd.png)

**Comment by MrPetovan** [comment]
Finally found the actual culprit: https://github.com/friendica/friendica/pull/9039/files#diff-a9b25ac4bedcd7e5d2d808a79488c3ebL1309
