### ISSUE TITLE
Own forum posts trigger notification

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9107]
### Expected behavior

Don't get a notification of your own postings to a forum.

### Actual behavior

I got one.

### Steps to reproduce the problem

* set "get notification for postings of this account" for a forum
* post a new note to the forum
* wait a moment until the forum "reshares" the posting and get notified.

possible also required is to have the "detailed notifications" enabled.

### Friendica version you encountered the problem

2020.09-dev 3e95c7ef18423dd055604b234327d91af28e5de1

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)

git

### PHP version

7.4.9

### SQL version

mysql  Ver 15.1 Distrib 10.3.23-MariaDB

**Comment by annando** [comment]
It's complicate :-)

**Comment by MrPetovan** [comment]
complicate`d`

**Comment by annando** [comment]
The english language is just complicated. :grimacing:

**Comment by AlfredSK** [comment]
The `E`nglish language... 😜

**Comment by MrPetovan** [comment]
Yeah? Try German or French.
