### ISSUE TITLE
Worker Explodes

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9117]
### Expected behavior
Expect cron job to complete without errors
### Actual behavior
```
PHP Warning:  file_put_contents(/friendica/32/3e/45092077e28b11a7285701fa10738a0e9770cae165895b98d36e49c8525e): failed to open stream:    
No space left on device in /misc/www/friendica/src/Model/Storage/Filesystem.php on line 143                                                                                                                                                                                         
Warning: file_put_contents(/friendica/32/3e/45092077e28b11a7285701fa10738a0e9770cae165895b98d36e49c8525e): failed to open stream: No      
space left on device in /misc/www/friendica/src/Model/Storage/Filesystem.php on line 143                                                  
PHP Fatal error:  Uncaught Friendica\Model\Storage\StorageException: Filesystem storage failed to save data to                            
"/friendica/32/3e/45092077e28b11a7285701fa10738a0e9770cae165895b98d36e49c8525e". Check your write permissions in                          
/misc/www/friendica/src/Model/Storage/Filesystem.php:148                                                                                  
Stack trace:                                                                                                                              
#0 /misc/www/friendica/src/Model/Photo.php(299): Friendica\Model\Storage\Filesystem->put()                                                
#1 /misc/www/friendica/src/Model/Photo.php(450): Friendica\Model\Photo::store()                                                           
#2 /misc/www/friendica/src/Model/Contact.php(1628): Friendica\Model\Photo::importProfilePhoto()                                           
#3 /misc/www/friendica/src/Model/Contact.php(1890): Friendica\Model\Contact::updateAvatar()                                               
#4 /misc/www/friendica/src/Model/Contact.php(1785): Friendica\Model\Contact::updateFromProbeArray()                                       
#5 /misc/www/friendica/src/Worker/UpdateContact.php(35): Friendica\Model\Contact::updateFromProbe()                                       
#6 [internal function]: Friendica\Worker\UpdateContact::execute()                                                                         
#7 /misc/www/friendica/src/Core/Worker.php(427): call_user_func_array()                                                                   
#8 /misc/www/friendica/src/Core/Worker.php(328): Friendica\Core\Worker::execFunction()                                                    
#9 /misc/www/friendica/src/Core/Worker.php(105): Friendica\Core\Worker::execute()                                                         
#10 /misc/www/friendica/bin/worker.php(75): Friendica\Core\Worker::processQueue()                                                         
#11 {main}                                                                                                                                
  thrown in /misc/www/friendica/src/Model/Storage/Filesystem.php on line 148
```
         File systems are nowhere near full.  Everything is owned by friendica, and cron job is launched as friendica.  Has been working fine for days now all the sudden crash-n-burn.
### Steps to reproduce the problem
          Spontaneous, just let it do it's thing for a few days and it explodes.
### Friendica version you encountered the problem
This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.
### Friendica source (git, zip)
git
### PHP version
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
### SQL version
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

This is a df on the machine:
```
Filesystem                  1K-blocks      Used  Available Use% Mounted on
udev                         28759428         0   28759428   0% /dev
tmpfs                         5760968      1232    5759736   1% /run
/dev/sda3                   210704800  53821060  146157452  27% /
tmpfs                        28804828         0   28804828   0% /dev/shm
tmpfs                            5120         0       5120   0% /run/lock
tmpfs                        28804828         0   28804828   0% /sys/fs/cgroup
/dev/loop0                     103040    103040          0 100% /snap/bitcoin-core/75
/dev/loop1                     103040    103040          0 100% /snap/bitcoin-core/81
/dev/loop2                     165888    165888          0 100% /snap/chromium/1279
/dev/loop3                     165888    165888          0 100% /snap/chromium/1284
/dev/loop4                      99328     99328          0 100% /snap/core/9665
tmpfs                        28804828       364   28804464   1% /tmp
/dev/loop6                      56320     56320          0 100% /snap/core18/1880
/dev/loop5                      98944     98944          0 100% /snap/core/9804
/dev/loop7                      56704     56704          0 100% /snap/core18/1885
tmpfs                        28804828        68   28804760   1% /var/lib/php/sessions
/dev/loop8                      63616     63616          0 100% /snap/gtk-common-themes/1506
tmpfs                        28804828         0   28804828   0% /var/tmp
/dev/sda1                      463844    110051     325326  26% /boot
204.122.16.12:/misc        1663065088 247441408 1331075072  16% /misc
204.122.16.254:/mail        152537088  70605824   74234880  49% /mail
204.122.16.128:/pocketcoin 2753437696  51804160 2561696768   2% /pocketcoin
204.122.16.12:/home        4078658560 836772864 3037069312  22% /home
204.122.16.12:/friendica   1059362816   5117952 1001201664   1% /friendica
tmpfs                         5760964         0    5760964   0% /run/user/145
tmpfs                         5760964         0    5760964   0% /run/user/4
tmpfs                         5760964         0    5760964   0% /run/user/0
tmpfs                         5760964         8    5760956   1% /run/user/120
```

Friendica is at /misc/www/friendica and storage for photos, etc, is /friendica, /misc is at 16% and /friendica 1%.
I have had to suspend workers (comment out the cron job) since every one is failing this way.

**Comment by MrPetovan** [comment]
I'm sorry I'm not able to help you troubleshoot this specific hosting issue. What I can say is that it isn't an issue we can fix in the code. Friendica just reported a permission denied error coming from the underlying operating system it interacts with.

**Comment by 4nanook** [comment]
It is running on Ubuntu 20.04 which runs a whole host of other PHP applications just fine.  I've created a user "friendica" that the code runs under, it is all owned by friendica, all the code, all the file space.  It is saying it is out of space but it is not.  It is not a permission issue, it is running as friendica and it has permissions 770 on the directory, also owned by friendica.

**Comment by MrPetovan** [comment]
What I mean by "permission denied" is that the underlying Operating System denied a file creation command issued by Friendica, no matter the actual reason which Friendica doesn't know about.

**Comment by 4nanook** [comment]
Ok, I found the problem, plenty of space but ran out of inodes.

**Comment by MrPetovan** [comment]
Glad to hear it.

**Comment by 4nanook** [comment]
This brings up a question though, eventually left unchecked this WILL run out of space even after I fix the file system to have adequate inodes, is there a way to tell friendica how much space it can use?  Or will it handle this more gracefully than running out of inodes?

**Comment by MrPetovan** [comment]
And then what happens the next time Friendica needs to create a file once the quota is reached?

**Comment by 4nanook** [comment]
Yes that is my question, there is not a quota set on it, so what happens when it runs out of space?  I'm trying to understand how I am supposed to manage this? This is for the File upload storage backend.  I've given it a file system with 2.6T available.

**Comment by MrPetovan** [comment]
What I meant was: if we implement a quota, what would happen differently when the quota is hit compared to when the underlying system runs out of inodes or free space?

**Comment by 4nanook** [comment]
It would make sense to me to remove the oldest material as you approach
the limit.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
What if it's a user-submitted picture? What if contacts start to randomly miss their avatar? This isn't sustainable.

**Comment by 4nanook** [comment]
Neither is just running out of space, infinite space isn't sustainable
either.  Of the two the latter seems to be the better option.  Perhaps going
by last access rather than upload date?

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
Friendica doesn't have infinite disk space requirements, we have pretty good estimates per user from the existing servers. The per user storage requirements actually decrease with the number of users, making the disk space requirement a curve that starts strong and then ends up plateauing around 1,000-10,000 users. I guess we never thought about the "running out of inodes" issue, which definitely isn't in the scope of the Friendica software itself.

**Comment by 4nanook** [comment]
Ok, in that 10,000 user plateau, how much space is estimated to be
required?

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
I don't remember exactly, but I can give you my numbers, for a single-user node running since 2016 with no database cleanup enabled. I use almost 1 GB for file storage and 22Gb database storage, but I don't know about the inodes. Since it isn't linear with the number of users, I expect 10,000 users to require about 100Gb of storage and 150Gb database, probably. We use a relational database which allows reusing numerical identifiers instead of copying the same data for each user/contact.

You can ask @AlfredSK for his exact numbers (users, file storage, database storage) since he runs the most popular Friendica node.

**Comment by 4nanook** [comment]
So then 2.6TB should be adequate?

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
By a wide margin, even if you wanted to become the new most popular Friendica node.

**Comment by annando** [comment]
My server squeet.me with more than 1,400 users is using 128GB space for the SQL database and 3.7 GB disk space. It currently holds more than 7.8 million public posts. The server itself has got 6 cores and 32GB memory. It has a regular load between 1 and 3.

**Comment by AlfredSK** [comment]
...most popular. 😍
I can have a look this evening to tell the exact numbers.

**Comment by AlfredSK** [comment]
**libranet.de**
registered users: `1110`
web root with proxy folder: `9.9G`
storage backend filesystem: `43G`
database: `88G`

**venera.social**
registered users: `538`
web root with proxy folder: `2.5G`
storage backend filesystem: `13G`
database: `22G`

Both nodes are running on the same root server. Hardware: 12 Core, 64GB RAM, 2x 1TB NVMe SSD RAID1, 1Gbit/s NIC.

**Comment by copiis** [comment]
Cool, was bezahlst du im Monat?

**Comment by AlfredSK** [comment]
74,24 Euro/month.

**Comment by 4nanook** [comment]
Sounds good, I recreated the file system with the default 4k/inode, I had originally created it to hold backup files which was why so few inodes, so it now has 174907392 inodes, should last it a while :)

**Comment by 4nanook** [comment]
It is not clear to me what comprises a "standard" server setup.  I went through the requirements on the website and made sure all were accounted for, granted it took me several iterations.

**Comment by MrPetovan** [comment]
You said it yourself, you set up a different size/inode for your file system than the default, so this qualifies as non-standard. All the requirements listed on the website are built on top of these low-level defaults.

**Comment by 4nanook** [comment]
Ok fair enough.
