### ISSUE TITLE
Use max_id/min_id for network page pagination

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9127]
The current network page pagination is based on numbered pages that can change when the following happens:
- new posts are received
- posts are manually deleted

Using the max_id/since_id pagination would ensure pages are consistent over time.

**Comment by annando** [comment]
Can we move this to the next milestone? I don't think that this is some crucial stuff.

**Comment by MrPetovan** [comment]
I'm bumping this up because I use the network pagination intensively these days where I don't keep up to date with social media often during the day. It's good that the community page got the infinite scroll from the network page, now can the network page get the proper pagination from the community page please? Pretty please?

**Comment by annando** [comment]
When you say pagination, do you mean the switching pages when the infinite scroll is deactivated? I'm asking, because with activated infinite scroll the pagination is already based on the date of the last entry.

**Comment by MrPetovan** [comment]
Yes, without infinite scroll. The reason I'm using the paginated mode is because on my Friendica iOS Home Screen app, when I tap on an external link, it switches to Safari, which is good, but when I come back to the Friendica app, it reloads the current page. Since we do not alter the address bar with the infinite scroll, it simply loads the network page back from the start. With pages it reloads the current page, which is good except that currently pages shift with each new post. So depending on the time I spent away from Friendica, either on mobile or on desktop, the same page may be completely different, but still filled with posts I've already been through.

The ideal would be to fix both the pagination and the infinite scroll by altering the address bar as the new pages are scrolled by after they were loaded asynchronously, but for now just fixing the pagination would be enough. Infinite scrolling is harder to perfect.

**Comment by MrPetovan** [comment]
I started looking into it and I'm glad I did because I realized we've been doing the max_id/since_id pagination wrong (especially since_id) for all the API endpoints that currently use it.

I also might have moved `mod/network.php` to `src/` in the process so this will be cut into separate PRs.
