### ISSUE TITLE
When playing a youtube video embedded only the first 1/2 minute or so plays then it freezes

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9131]
### Expected behavior
Expect the video to play in it's entirety unless manually interrupted.
### Actual behavior
It stops after 20-30 seconds and can not be restarted, but if I copy the video URL and play it directly on youtube
it plays correctly.
### Steps to reproduce the problem
Click on any embedded video in the news stream.
### Friendica version you encountered the problem
see `example.com/friendica` on your Friendica node for the version information.
This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.
### Friendica source (git, zip)
git
### PHP version
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
### SQL version
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by MrPetovan** [comment]
While this is outside of Friendica's scope since we're using Youtube's embed code, please verify you don't have a content blocker extension messing with third-party content on Friendica pages.

**Comment by 4nanook** [comment]
I have tracking disabled, this does cause Youtube to initially fail and then play for me, but it does not cause it to stop midway into the video, and youtube embedded on other platforms such as farcebook, puketnet, or freenet does not display this behavior.

**Comment by MrPetovan** [comment]
Any browser console error message? Again, this has little to do with Friendica itself so I will not dedicate too much time to this specific issue.

**Comment by 4nanook** [comment]
No it just stops

**Comment by MrPetovan** [comment]
Then I'm out of options, sorry about that.

**Comment by annando** [comment]
Have you tried different browsers? Possibly it is some browser issue.

**Comment by AlfredSK** [comment]
Maybe auto page reload? Or whatever that option for our pages is called.
It's somewhere in display options. Something like 'auto update/reload content only on top of page' should be enabled. I would give that a try.

**Comment by 4nanook** [comment]
I am using Firefox, if it does not worth with FIrefox this is problematic since it is a widely used Browser.  Embedded Youtube
videos work elsewhere as I have previously mentioned.  I do not understand AlfredSK's response about auto update/reload only at top of page?

**Comment by tobiasd** [comment]
@AlfredSK pointed out that the problem might be, that the automatic content loading for new postings might interrupt the playback of the video. For this mechanism there are some settings a user can apply in their settings (User settings -> Display).

Among these, there is the "Automatic updates only at the top of the post stream pages" which will prevent Friendica from loading new content into the network stream if you are not at the top of the page. So if you activate that option, scroll down to a video and watch it; and then the video does not stop after some time, the root for the problem is found.

**Comment by 4nanook** [comment]
Ok, I do not have this enabled in my settings but it is updating anyway.

**Comment by tobiasd** [comment]
Exactly. Without enabling this option the network page will be updated when new content arrives after a couple of seconds. This might cause the video playback to be stopped as the page is refreshed with new content.

If you enable the option, the stream should be refreshed on new content only when you are at the top of the stream. So scrolling down to view the video the playback should not be interrupted--if this is the root of the problem.

**Comment by 4nanook** [comment]
Nope still fail the same, video didn't move, just stops.

**Comment by annando** [comment]
The question concerning the browser is not meant to tell you that you have to use a different browser all the time. But it helps detecting the origin of the problem.

**Comment by 4nanook** [comment]
I tried with Google Chrome and with Tor Browser, Google Chrome stopped at the exact same spot it stops at with Firefox, and Tor stopped much sooner, about four seconds into the video.

**Comment by 4nanook** [comment]
Since the video scraping broke, and then was subsequently repaired, I am not seeing this issue anymore.  Don't know if it's something you've fixed or youtube's fixed, but whatever it was appears to be corrected so I am closing this trouble report.
