### ISSUE TITLE
Don't show '... reshared this' at top of post in all cases

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9135]
### Expected behavior
The new place for '...reshared this' is a good thing for items I got in my stream because of the reshare. It doesn't make sense for all other cases:
- someone reshared a post of me
- I had that item in my network stream anyway (not because of the reshare)
- it shows '7 people reshared this' (then the display at the top it completely weird)

From my point of view the intention was right. But as it is now it's not ready for the next release. We should rethink and refine that thing.

It should only show the one sharer who is responsible for making me see the post in my stream. The number of reshares should return to the bottom of the item (where the likes count is, too). And maybe only show the number of reshares there.

### Actual behavior
Reshares, resharer, number of reshares are always displayed at the top of a post that has reshares. That's confusing and as it is now (see above examples) it seems out of place in most cases.

### Steps to reproduce the problem
Look at various reshares. :-)

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Some examples.

**Seems right:** someone shared it and therefore I have it in my stream

![Screenshot_20200904-211636](https://user-images.githubusercontent.com/3656054/92279750-41b67c80-eef8-11ea-9ce7-c6d07eb9b790.png)

**Seems wrong:** my own post, why does it show the resharer at the top?

![Screenshot_20200904-211812](https://user-images.githubusercontent.com/3656054/92279881-89d59f00-eef8-11ea-9440-449930844070.png)

**Seems weird:** multiple reshares, not useful and out of place at the top

![Screenshot_20200904-211936](https://user-images.githubusercontent.com/3656054/92279978-b7224d00-eef8-11ea-8cc5-874cd40b70eb.png)

**Comment by MrPetovan** [comment]
Ha ha, I never have the last two examples. I'm not as popular as you visibly!

**Comment by annando** [comment]
I would be in favour of this model:
- only when the post is in my stream because it had been reshared, then this "xxx reshared this" should be at the top
- additionally the numbers of reshares (and likes) should be expressed as simple numbers behind their respective action buttons. A click on the numbers then reveals the resharers/likers.

**Comment by annando** [comment]
I think we should handle this in the current RC to something that is more similar to other systems.

**Comment by MrPetovan** [comment]
I'm not sure how to go about it. In the template, we have access to two pieces of information about the resharing:
- A "<account link>/<number> people reshared this" string in the interactions
- A "<account name> reshared this" in the direction

Ideally, I'd like to have a "<account link> reshared this" string available but I have little idea how to go about it.

**Comment by SpcCw** [comment]
I updated to RC and to be honest this reshare indication is bugging me a bit as well...

It takes too much space to my liking and also I am not sure why the first thing about the post should be the information how many people reshared it. It can even create unwanted bias. I think having this in the footer together with likes is much better - especially since now there is this awesome indicator showing why post got in the feed - I like it a lot!

**Comment by MrPetovan** [comment]
The goal is to only show the resharer that put this post in your feed. It is the case on my single-user node, but as I found out I'm an edge-case.

**Comment by SpcCw** [comment]
I don't think it is too bad (it is mostly "X people reshared" that annoys me). I understand it is mainly matter of taste - some like this information better at top prominently visible, some would like to have it more discreet.

**Comment by MrPetovan** [comment]
Yeah, like I said, "X people reshared this" wasn't meant to show at this spot, but since I never get it on my personal node, I didn't realize it could.

**Comment by annando** [comment]
One could hook in here: https://github.com/friendica/friendica/blob/2020.09-rc/include/conversation.php#L729-L731

Instead of setting the actor, we could set some other value here.

**Comment by AlfredSK** [comment]
Also, would be cool if there was a different background color shade for that area. I imagine that a little bit like the top area of the comments here on Github (xyz commented ...). :-) I don't know how difficult it is to find a solution that works with the various color schemes. But it would look really cool.

**Comment by MrPetovan** [comment]
> I don't know how difficult it is to find a solution that works with the various color schemes.

Insanely difficult. The font color is intended to be displayed on the panel color (light on most themes, dark/black in the respective schemes), but not on the background, than can literally be anything from a solid color to a multi-colored LSD-fueled piece of art. The font color can be slightly darker as we use two different tones throughout the design, the font size can be reduced, but the background will not change.

**Comment by MrPetovan** [comment]
> One could hook in here: https://github.com/friendica/friendica/blob/2020.09-rc/include/conversation.php#L729-L731

Thanks, I can work with that.

**Comment by annando** [comment]
I made a small change already:
![Bildschirmfoto vom 2020-09-08 23-59-45](https://user-images.githubusercontent.com/844208/92531907-7b0c2680-f22f-11ea-9b2a-8acec0a77d60.png)

This had to be applied to other themes as well - and the bottom has to be changed.

**Comment by MrPetovan** [comment]
Let's add the reshare icon in front of the first line.

**Comment by AlfredSK** [comment]
Big thanks to everyone involved. I'm happy now. :-)

**Comment by MrPetovan** [comment]
Michael was able to bring home the idea I had!
