### ISSUE TITLE
frio: contact hovercards in top level posts cannot be opened anymore

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9136]
### Expected behavior
~~When on mobile~~ I should be able to open the hovercard of the contact who shared the top level post.

### Actual behavior
~~When on mobile~~ I cannot open the hovercard of the sharer anymore. It still works for hovercards in comments.

### Steps to reproduce the problem
It doesn't matter if you go to network, profile or community pages. Try to open a hovercard of the contact who shared a post by tapping on the avatar.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Oh! It still works when you click at the very bottom of the user avatar - but not when you e.g. click in the center or top area of the avatar. On mobile it's the same. Bottom works. ;-)

**Comment by AlfredSK** [comment]
Tested with Firefox an Chromium. Same.

**Comment by annando** [comment]
Ah okay. I can imagine that it is associated with changes from @MrPetovan - and if not, I still think that he will find it quicker than me :-)

**Comment by MrPetovan** [comment]
I cannot reproduce this issue on Windows / Chromium / Vivaldi / frio / dark. I've been clicking on all the parts of the top-level post avatar and the hovercard has been showing up consistently.

What are your conditions for not being able to do it?

**Comment by MrPetovan** [comment]
Nevermind, I can reproduce this issue in Firefox.

**Comment by AlfredSK** [comment]
Thanks! It's fixed. Tested with Chrome/Android.
