### ISSUE TITLE
Quotation marks in photo captions cause text to disappear upon edit

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#9138]
### Expected behavior
When editing a photo with a caption that contains quotation marks, the entire string appears within the "Caption" text field.

### Actual behavior
When editing a photo with a caption that contains quotation marks, the caption is cut off in the "Caption" text field where the first quotation mark appears.

### Steps to reproduce the problem
1. Upload a photo.
2. Edit the photo details and add a caption that contains the character `"`; for instance:
> This is a so-called "caption".
3. Save the edit. At this point, if you view the photo, the caption should display in full, quotation marks and all.
4. Edit the photo again and look at the "Caption" text field. Notice that the string is cut off, for example:
> This is a so-called 

### Friendica version you encountered the problem
2020.03

### Friendica source (git, zip)
Don't recall. 

### PHP version
7.3.19-1~deb10u1

### SQL version
10.3.23-MariaDB-0+deb10u1 

### Notes
I suspect this is a matter of captions not being escaped/sanitized properly.

**Comment by tobiasd** [comment]
You are using the frio theme right?

I've just tested with vier to directly insert the BBCode for an image with a caption and surrounded one of the words of the caption with " and the caption was displayed correctly. Could you check this?

**Comment by SpencerDub** [comment]
@tobiasd 

I can replicate this in Vier.

I forgot to attach screenshots; that might help demonstrate what I'm saying.

---

**On Frio:**
![Error - Quote mark in caption](https://user-images.githubusercontent.com/4674927/92417800-f7601600-f118-11ea-80de-63dd545fec19.png)

---

**On Vier:**
![Error - Quote mark in caption - Vier](https://user-images.githubusercontent.com/4674927/92417801-f8914300-f118-11ea-8c5a-638bd4d67622.png)

---

Notice the disparities between the saved caption ("Screenshot of the "Merlot" theme for Frio") and the contents of the Caption text box at the bottom ("Screenshot of the ").

**Comment by MrPetovan** [comment]
Classic case of missing HTML encoding, thank you for the report!
