### ISSUE TITLE
Update Community Forums help documentation

### ISSUE THREAD

**Issue by mpanhans** [friendica/friendica#9150]
The "Community Forums" page on the help documentation has been outdated (for example: https://forum.friendi.ca/help/Forums) since the front-end for page delegation was added. Some discussion of that front-end implementation is here: https://github.com/friendica/friendica/issues/4319

Below I propose language that can be used to update the Community Forums help page:

> Friendica also lets you create forums and/or celebrity accounts.
> 
> Every page in Friendica has a nickname and these must all be unique. This applies to all forums, whether they are normal profiles or forum profiles.
> 
> To create a new linked account that can be used as a forum, log in to your normal account and go to Settings > Manage Accounts. Here you can register additional accounts with new nicknames that will be linked to your primary account. This is also where you can designate which account is the parent user. Once your primary account is designated as the parent user, you will be able to easily toggle identities and manage your forums.
> 
> You may also appoint a delegate to manage your forum. The Delegates section of Manage Accounts page will provide you with a list of contacts on the instance under "Potential Delegates". Selecting one or more persons will give them access to manage your forum. They will be able to edit contacts, profiles, and all content for this account/page. Please use this facility wisely. Delegated managers will not be able to alter basic account settings such as passwords or page types and/or remove the account.
> 
> **Types of Forum Accounts**
> 
> On the new account, visit the “Settings” page. Towards the end of the page are "Advanced Account/Page Type Settings". Typically you would use "Normal Account" for a normal personal account. This is the default selection. Community Forum/Celebrity Accounts provide the ability for people to become friends/fans of the forum without requiring approval.
> 
> The exact setting you would use depends on how you wish to interact with people who join the page. The "Soapbox" setting lets the page owner control all communications. Everything you post will go out to the forum members, but there will be no opportunity for interaction. This setting would typically be used for announcements or corporate communications.
> 
> The most common setting is the "Community Forum". This creates a forum page where all members can freely interact.
> 
> The "Automatic Friend Account" is typically used for personal profile forums where you wish to automatically approve any friendship/connection requests.
> 
> **Posting to Community forums**
> 
> [This section can stay the same as before]

**Comment by tobiasd** [comment]
Thanks for the work!

But personally, I don't like the mixing of terms. A soapbox account is no forum.

A forum is a place where every member of the forum can post to to reach all other members of the forum. A soapbox is an announcement channel that is one-directional regarding to the origin of the message flow.

Also one can simple create a new account and don't associate a parent user with the delegation mechanism. Although the delegation has the advancement, that switching from one account to another is a bit more simple. Maybe the section could mention both options, with the delegation highlighted for that advancement?

**Comment by mpanhans** [comment]
Yes, good points. I had copied previous language on those parts, but I agree it can be better. I propose a new section below which I hope addresses your comments. An alternative could be to break this "Forums" help page into two: "Account Types" and "Managing Accounts." Obviously feel free to make any further edits, but I think any update to this help page to reflect new options will be a big improvement. 

> Friendica also lets you create community forums and other types of accounts that can function as discussion forums, celebrity accounts, announcement channels, news reflectors, or organization pages, depending on how you want to interact with others. Management of these pages can be delegated to other accounts, or a parent account can be designated to easily toggle multiple identities.
> 
> Every page in Friendica has a nickname and these must all be unique. This applies to all forums, whether they are normal profiles or forum profiles.
> 
> **Managing Accounts**
> 
> To create a new linked account that can be used as a forum, log in to your normal account and go to Settings > Manage Accounts. Here you can register additional accounts with new nicknames that will be linked to your primary account. 
> 
> You may appoint a delegate to manage your forum. The Delegates section of Manage Accounts page will provide you with a list of contacts on this instance under "Potential Delegates". Selecting one or more persons will give them access to manage your forum. They will be able to edit contacts, profiles, and all content for this account/page. Please use this facility wisely. Delegated managers will not be able to alter basic account settings, such as passwords or page types, or remove the account.
> 
> Additionally, this page is also where you can choose to designate an account as a parent user. If your primary account is designated as the parent user, you will be able to easily toggle identities and manage your forums or other types of accounts.
> 
> **Types of Accounts**
> 
> On the new account, visit the Settings > Account page. Towards the end of the page is a section for "Advanced account types". Typically you would use "Personal Page - Standard" for a normal personal account with manual approval of “friends” and “followers.” This is the default selection. On this page you can change the type of account if desired.
> 
> The other subtypes of a Personal Page are “Soapbox” and “Love-all.” A Soapbox account is an announcement channel that automatically approvals follower requests. Everything posted by the account will go out to the followers, but there will be no opportunity for interaction. This setting would typically be used for announcements or corporate communications. Love-all automatically approves contacts as friends.
> 
> In addition to Personal Page, there are options for Organization Page, News Page, and Community Forum. Organization and New Pages automatically approve contact requests as followers.
> 
> Community Forum provide the ability for people to become friends/fans of the forum without requiring approval. This creates a forum page where all members can freely interact.
> 
> **Posting to Community forums**
> 
> [This section can stay the same as before]

**Comment by tobiasd** [comment]
Great :) Only thing I see at the moment

> You may appoint a delegate to manage your forum

Maybe "to manage your new account, e.g. a forum"?
