### ISSUE TITLE
Absence of file /include/items.php

### ISSUE THREAD

**Issue by IronBug** [friendica/friendica#9151]
I decided to update Friendica instance to develop branch to solve problems with Pleroma AP exchange.
And the developer version does not work, because file **./vendor/composer/autoload_files.php** contains request of **/include/items.php**, which does not exist in the repository. 
I guess it was just accidentally forgotten to be committed in some push request.

**Comment by IronBug** [comment]
sorry for fake alarm. it was a quirk of composer.phar installation, I guess. I ran it again and it works fine.

**Comment by MrPetovan** [comment]
Awesome, we like self-closing issues!
