### ISSUE TITLE
auto-hide confirmation notifications

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9153]
### Expected behavior

Auto-hide confirmation notifications.

### Actual behavior

Notifications are shown indefinitely forcing the user to interact. That is not a good default / bad UX. Chances are, the user has seen the notification so why should they have to move the mouse, find the much too small "x" and click that to continue whatever they were going to do instead?

![Bildschirmfoto 2020-09-07 um 10 34 46](https://user-images.githubusercontent.com/5708172/92366908-0da8aa80-f0f6-11ea-8d95-8782216d3f98.png)

**Comment by MrPetovan** [comment]
I believe we should have two different behaviors for these, on success messages it should disappear by itself, on failure it shouldn't. Currently we do the distinction in the PHP code for either kind of messages but we don't treat them differently in Javascript.
