### ISSUE TITLE
Hashtag parameter isn't encoded on search moudule if the user visits the next page

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#9164]
### Actual behavior
if you are searching for a hashtag - lets say 'friendica' - you will get the following url `https://yourserver.com/search?q=%23friendica`. But if you visit the next (second) page of the results the hashtag sign isn't encoded and you will get as url `https://yourserver.com/search?q=#friendica&page=2` and would fail to load the results.

The correct url shoutd be: `https://yourserver.com/search?q=%23friendica&page=2` 

### Steps to reproduce the problem
Search for a hashtag and jump to the next page

### Friendica version you encountered the problem
2020.09-rc

### PHP version
PHP 7.4

### SQL version
MariaDB 10.3

**Comment by MrPetovan** [comment]
Grumble, thanks for the report!
