### ISSUE TITLE
Quick comment pluggin doesn't work

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#9172]
### Expected behavior
The answers stored in the plug-in settings should be automatically inserted into the comment field when you click on them.
### Actual behavior
Nothing is inserted.
### Steps to reproduce the problem
Activate the plugin, define a quick reply, comment on a post and try to insert the reply.
### Friendica version you encountered the problem
2020.09-rc
### Friendica source (git, zip)
git
### PHP version
7.4.8
### SQL version
Mariadb 10.1

**Comment by tobiasd** [comment]
Can you check if it is working for you using a different theme? For me this looks like a bug in frio.

**Comment by ghost** [comment]
> Can you check if it is working for you using a different theme? For me this looks like a bug in frio.

You're right, it's a "Frio" problem

**Comment by tobiasd** [comment]
Since when do you have the problem? Switched to the RC branch or something like that?

**Comment by ghost** [comment]
> Since when do you have the problem? Switched to the RC branch or something like that?

I can't tell you that because I only recently activated the add-on.
I am on latest RC
