### ISSUE TITLE
last composer tab out of the row

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9182]
I hope this is no duplicate issue. It's just the last tab not fitting in the row.

### Expected behavior
all tabs of the composer should be in one row

### Actual behavior
![friendica-composer](https://user-images.githubusercontent.com/5753419/92929686-3b1c8d80-f441-11ea-9705-ce47b77f5497.jpg)

### Steps to reproduce the problem
not sure. I use chromium here.

### Friendica version you encountered the problem
version: 2020.09-rc
database version: 1367
post-update-version: 1350
theme: Frio V.0.8.5

**Comment by MrPetovan** [comment]
This looks like a translation length issue. I guess we can allow for a little more room, but since it's a fixed value, it may still break for another long worded language like Finnish or Turkish, so I'm not sure what we should do about it.

**Comment by SpcCw** [comment]
> This looks like a translation length issue.

It is. Same problem with Russian. Maybe we can have a little more space added and update Transifex character limits for these strings so translators know it in advance?

With Russian it seems to work when all four words are under 34 characters (all of them combined, no spaces). On 35 characters it starts to break. However words are uneven in length. I think it would be good if this dialog didn't break on 40 characters total and then every string was set to 10 char limit in Transifex. This would make it more predictable and gave enough room to play for the most.

**Comment by MrPetovan** [comment]
Thank you for the elaboration, the source translation word `Permissions` is 11 characters already, not sure a 10 char limit would be workable.

But the combined length of the German translation is 38 characters so maybe 40 chars max is all it would take.

**Comment by tobiasd** [comment]
I'm not aware of limits regarding word length that could be set for the translation. One could search for shorter synonyms of the words, but I'm not sure if that search will be successful for all languages possible affected.

**Comment by haheute** [comment]
I have tried with these CSS values (added to that selectors): 

```
.nav-tabs>li{
    white-space:nowrap;
    max-width: 21%;
}
.nav-tabs>li>a{
    text-overflow: ellipsis;
    overflow: hidden;
    font-size: 1.2rem;
}
```
![friendica-comp-css](https://user-images.githubusercontent.com/5753419/92989501-1a9e1300-f4d5-11ea-8ccb-00bb9d75efd0.jpg)

don't know if it would be a solution or work everywhere.

**Comment by MrPetovan** [comment]
It would be a solution, but we need to add the full translation as title text. And we can slightly increase the width as well, thanks!

**Comment by MrPetovan** [comment]
Interestingly, I do not get the same display when using the German translation on Vivaldi/Windows, so it seems to be a system font issue. I also verified the Finnish translation and it fits perfectly, so I'll just slightly increase the modal window width.
