### ISSUE TITLE
Impossible to insert a '>' into the title of a post

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9192]
### Expected behavior
When I put something like "... > ..." into the title it should stay that way after submitting the post.

### Actual behavior
When I put something like "... > ..." into the title it is changed to "... ] ..." after submitting the post.

### Steps to reproduce the problem
Enter something containing a `>` into the title of a new post. Look at the preview or submit it and look at the post.

### Friendica version you encountered the problem
2020.09-rc and older

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Ah, yes, another legacy artifact.

**Comment by annando** [comment]
Yeah, `Strings::escapeTags`, used 217 times ...
