### ISSUE TITLE
frio: improve UI indicator for active post interactions (like, dislike, star, share, comment, ...)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9201]
### Expected behavior

Active post interactions should be highlighted by a color that works for all three frio color schemes (light, dark, black). See how Twitter solved this (notice how much cleaner Twitter UI looks by only using icons and omitting  descriptive text as users are familiar with those icons:
<img width="414" alt="twitter color" src="https://user-images.githubusercontent.com/5708172/93100454-74efcd00-f6a9-11ea-9965-4bb38315e9f7.png">

Summarizing suggested changes:

- [x] slightly increase size of post interaction icons https://github.com/friendica/friendica/pull/12699
- [x] add color to icons (highlight color or share: green, like / dislike: red, comment: blue, star: yellow)
- [x] remove text labels (on mobile, text labels still exist on desktop)
- [ ] use full width for icon spacing preventing the currently clumped up icons clumped up on the left https://github.com/friendica/friendica/issues/12835

### Actual behavior

The third comment was liked. It is almost impossible to distinguish, that that option is active.
<img width="240" alt="like active indicator" src="https://user-images.githubusercontent.com/5708172/93100552-918c0500-f6a9-11ea-82eb-305e1e88c476.png">

### Friendica version you encountered the problem

2020.09-rc

**Comment by MrPetovan** [comment]
Fixing the lack of distinction in dark/black schemes will be done this release, but @annando's idea to migrate to a Mastodon-like display for interactions (with an icon and a number of existing interactions and no label) will come in an upcoming release.

**Comment by foss-** [comment]
The requested mock-ups of Twitter UI for desktop and mobile.

Status quo:

Icon size: still a tad too small for my taste.

Icon colors: frio uses highlight color now, which is a start. Let's call that solved.

Text labels: Friendica got rid of the text labels on mobile. Not sure if they are needed on desktop - Twitter and Mastodon seem to disagree. Would still like to see them go. There is no benefit and they clutter the UI.

Use full width for spacing: still not the case and I find the spacing used in friendica really odd. Why squish the icons together and make it unnecessarily hard to tap or click them?

Twitter Desktop:

![twitter desktop](https://user-images.githubusercontent.com/5708172/213776993-1f1eec78-224b-417d-b3bb-9f7a609a3288.png)

Twitter Mobile:

![twitter mobile](https://user-images.githubusercontent.com/5708172/213776901-aea07e46-420b-4f2b-84bd-204133a597e2.png)

**Comment by foss-** [comment]
Closing this issue. Three of the 4 suggestions were addressed and for the remaining one we have https://github.com/friendica/friendica/issues/12835

Friendica state as of 2023-02-22:
![1](https://user-images.githubusercontent.com/5708172/220632324-d5d7ad3d-b1fa-459b-84ff-ac10e5d249ee.jpg)
