### ISSUE TITLE
searching for a Mastodon posting to get it local to interact does not work

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9204]
### Expected behavior

Search for the URL of a Mastodon posting to be able to locally interact with it.

### Actual behavior

The message "No results" (src/Module/Search/Index.php:179 according to the messages.po file) is shown.

### Steps to reproduce the problem

Search for the URL of a Mastodon posting that is not known to your server before.

### Friendica version you encountered the problem

2020.09-rc cade34cd2d22b14661bc7d034014a2d58838c4b9

**Comment by MrPetovan** [comment]
Does it fail with any post? From any Mastodon instance? Would you be able to provide a sample URL to hopefully reproduce the issue?

**Comment by tobiasd** [comment]
It does also fail with postings from Pleroma and Friendica.

Taking some random postings from the federated timeline of my Mastodon-test-account server. All have failed on my node.

https://mstdn.social/@verge/104864373644594744
https://mastodon.social/@hntooter/104864371845167374
https://pleroma.site/objects/451dbbf4-6fd3-4ab3-a052-befbbaaaa6d7
https://octodon.social/@cwebber/104864342911693845
https://squeet.me/objects/962c3e1093af48f422dfaa3c2097979cef5ecd5e

**Comment by MrPetovan** [comment]
Thank you for the elaboration.

**Comment by annando** [comment]
To explain the origin of the problem: For security issues we now do verify content more strict. To solve this, we had to convince the system that the content is alright. This should be no security problem.

**Comment by tobiasd** [comment]
Works again, thanks :)
