### ISSUE TITLE
Unable to resolve your name at the provided location.

### ISSUE THREAD

**Issue by chrber** [friendica/friendica#922]
Hi,

I am always running master on my friendica. I have broken my friendica, I think and tried to find help through google without any success. This is why I turn to the devs, maybe you have a hint or two how to resolve my issue.
Issue one: I can not connect to anybody any longer. Not even to users on my own server. I always get this error message: "Unable to resolve your name at the provided location."

There is a report of this problem here: http://bugs.friendica.com/view.php?id=289
but nobody responds to it.

Here are my system stats:
Kernel: 2.6.32-042stab083.2 #1 SMP Fri Nov 8 18:08:40 MSK 2013 x86_64 GNU/Linux
Debian GNU/Linux 7 \n \l
ii  php5                               5.4.4-14+deb7u7
ii  mysql-server-5.5                   5.5.35+dfsg-0+wheezy1

Maybe you can give me some general hints on how to start debugging this issue.

Thank you.
Christian

**Comment by soko1** [comment]
Hi!
Error in the absence webfinger.
File `m/dfrn_request.php`:
```
$url = webfinger_dfrn($url,$hcard);
...
                if(! strlen($url)) {
                        notice( t("Unable to resolve your name at the provided location.") . EOL);
                        return;
                }
```
$url is NULL after calling webfinger_dfrn().

webfinger_dfrn():
```
function webfinger_dfrn($s,&$hcard) {
        if(! strstr($s,'@')) {
                return $s;
        }
        $profile_link = '';

        $links = webfinger($s);
...
```
$links is NULL.
webfinger():
```
function webfinger($s, $debug = false) {
        $host = '';
        if(strstr($s,'@')) {
                $host = substr($s,strpos($s,'@') + 1);
        }
        if(strlen($host)) {
                $tpl = fetch_lrdd_template($host);
...
```
$tpl is NULL.
fetch_lrdd_template():
```
function fetch_lrdd_template($host) {
        $tpl = '';

        $url1 = 'https://' . $host . '/.well-known/host-meta' ;
        $url2 = 'http://' . $host . '/.well-known/host-meta' ;
        $links = fetch_xrd_links($url1);
     ...
```
$links is NULL => need files example.com/.well-known/host-meta.

P.S.: I'm not sure.

I have exactly the same error.

**Comment by annando** [comment]
Please provide your hostname and profile address. Then we can do some checks.

**Comment by soko1** [comment]
http://social.decart.xyz
sagan@social.decart.xyz

**Comment by soko1** [comment]
Found an error!

nginx:
```
...
location ~ /\. { deny all; access_log off; log_not_found off; }
```
fix:
```
#location ~ /\. { deny all; access_log off; log_not_found off; }
```

**Comment by annando** [comment]
You should have this statement since it prevents hidden files from being read. But you should have an extra rule for the .well-known folder.

**Comment by redmatrix** [comment]
There is also an issue with letsencrypt, which creates a physical .well-known directory and stores its acme-challenge file there and this over-rides the built-in .well-known handler. We had to create a special Apache rule in hubzilla and modify the well-known handler a bit to work around this. Haven't yet modified the nginx config there but it will likely require something similar.

**Comment by soko1** [comment]
> You should have this statement since it prevents hidden files from being read. But you should have an extra rule for the .well-known folder.

Yes, I had this in mind. Thanks!
