### ISSUE TITLE
[vier] Autocompletion for formatting codes, hashtags and usernames takes very long

### ISSUE THREAD

**Issue by ilsd** [friendica/friendica#9220]
### Expected behavior

Autocompletion of tags should happen within a second.

### Actual behavior

Typing an opening spare-bracket (`[`) in the editor tries to autocomplete bbcode but takes a lot of time. The same is true for the `@`-sign and Hashtags (`#`).  

### Steps to reproduce the problem

Start to write a new post using the vier theme.

### Friendica version you encountered the problem

This has been reported by two users; both of them are from squeet.me (Version 2020.09-rc, Datenbankversion ist 1367/1367, Post-Update-Version 1350)

### Original post

This is result of the discussion https://squeet.me/display/962c3e10-165f-5383-5159-72a144813680

**Comment by tobiasd** [comment]
What browsers are you using?

For me using Firefox 68-ESR it displays the tags rather quickly, something like 2seconds. But the auto-completion libraries have had often problems with different browser versions in the past.

**Comment by MrPetovan** [comment]
In this RC [the old embedded jQuery textcomplete library has been replaced with the slightly less old vanilla Javascript textcomplete library](https://github.com/friendica/friendica/pull/8917). It greatly improved BBCode autocompletion performance on Firefox specifically.

What's the witnessed delay that sparked this issue?

**Comment by ilsd** [comment]
So I asked the reporting users for their browser-types and OS and also to measure the time they had to wait. Here are their answers:

* Manjaro w/ Firefox 80
* Windows 10 Home and Firefox 80.0.1

Both of them reported that the autocompletion now works too fast to be able to tell the exact time they had to wait.

In one sentence: I think we can close this issue ;-)

**Comment by MrPetovan** [comment]
Yay!
