### ISSUE TITLE
Follow button when already friends

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9229]
### Expected behavior
On the "Status" page, show an "unfollow button" when already friends or maybe no button.

### Actual behavior
The pages
https://nerdica.net/contact/126076/conversations (friendica),
https://nerdica.net/contact/353762/conversations (friendica)
and
https://nerdica.net/contact/297102/conversations (diaspora)
(examples, maybe more, all 3 are bi-directional friendships)
show me a "Follow" button on the left side below the avatar picture and bio.

### Steps to reproduce the problem
Follow some user and check the contact/{{id}}/conversations page when the friendship is bidirectional.
The problem is on the "Status" tab/page. On "Profil" tab/page it seems to work.

### Friendica version you encountered the problem

version: 2020.09-rc
database version: 1367 
post update version: 1350
theme: Frio V.0.8.5

**Comment by AlfredSK** [comment]
Hmm. I checked 6 random, bidirectional contacts (Friendica and Diaspora). I have an unfollow button under the main avatar. I'm on current RC, too.

**Comment by haheute** [comment]
There are these 'tabs':

"Status" "Statusnachrichten und Kommentare" "Profil" "Kontakte" "Erweitert"

they all show me a "+Follow" button except "Profil" which shows an "unfollow" button and a "Nachricht" button. (on the diaspora contact above )

**Comment by AlfredSK** [comment]
Ah! Since 'profile' is the default when you go to the contact's page I only checked that.
Yep. Confirmed. The other tabs have a 'follow' button.
