### ISSUE TITLE
frio: mobile: color for unread notification wrong

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9236]
**Currently**
On frio mobile iOS, unread notifications are shown with wrong color in the dropdown.
![notification colors wrong](https://user-images.githubusercontent.com/5708172/93669626-ce833d80-fa95-11ea-9510-4289e5a78f11.png)

**Expected**
Readable unread notification in dropdown. Probably works as expected with light frio theme? So this could be a new problem after introducing light, dark and black themes for both darker frio themes.

**Comment by vinzv** [comment]
I can't reproduce it:

![image](https://user-images.githubusercontent.com/74432/95130958-a108e600-075d-11eb-9709-6dd79b4d35b5.png)

<del>Is this a new (unread) notification?</del> Nevermind, overlooked it in your post. Still I can't reproduce it in Firefox Desktop with iOS active via dev tools. Maybe something specific to Safari?

**Comment by foss-** [comment]
Thanks for looking into this. This was iOS Firefox so wondering how accurate Firefox dev tools reproduce mobile environment.
Need more unread notifications to test additional browsers.

**Comment by vinzv** [comment]
I just could reproduce it with Firefox on Android. It needs to be an unread notification:
![Screenshot_2020-10-06-00-00-31-70_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/74432/95136857-2e046d00-0767-11eb-9ec8-64036bb1779d.jpg)

I'll have a look into it.

**Comment by MrPetovan** [comment]
Changing the text color didn't seem to do the trick, the problem seems to be more about the background color of the active notification that isn't consistent across desktop/mobile.
