### ISSUE TITLE
frio: "back to top" arrow icon should match light, dark, black theming

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9249]
### Expected behavior
 "back to top" arrow icon should match light, dark, black theming.

### Actual behavior
the UI for the "back to top" arrow looks rather alien.
![current ui](https://user-images.githubusercontent.com/5708172/93723866-a5040800-fba2-11ea-95e7-e671d410dcab.png)

 2020.09-rc

**Comment by MrPetovan** [comment]
What color do you think it should be?

**Comment by foss-** [comment]
Asking the obvious question. What about using the highlight color for the arrow box and make the arrow itself transparent (this example is frio, dark with blue accent)? That would solve the situation for all three accented themes.

![proposal 1](https://user-images.githubusercontent.com/5708172/94349814-7e354e00-0048-11eb-9cb7-d488aef6827b.png)

**Comment by MrPetovan** [comment]
Sounds good, I just couldn't figure it out because the possibility space.

**Comment by foss-** [comment]
@vinzv [brought up](https://github.com/friendica/friendica/pull/9403) the interesting question whether "scroll-to-top" is needed at all.

Twitter does not use it and the reason for that is, that they have static navigation which always is accessible. I find that a superior concept and it holds true for friendica desktop and mobile. To go-to-top users can click the menu option at any time.

Any objections to just remove scroll to top?

**Comment by MrPetovan** [comment]
On iOS it is perfectly useless, since a tap on the status bar at the top of the screen scrolls to the top of any page. The rare times I've browsed Friendica on Android, I've been enjoying this feature as there are no built-in way to do it.

**Comment by AlfredSK** [comment]
Yes. Objection here. Don't remove it.

**Comment by vinzv** [comment]
> On iOS it is perfectly useless, since a tap on the status bar at the top of the screen scrolls to the top of any page. The rare times I've browsed Friendica on Android, I've been enjoying this feature as there are no built-in way to do it.

With smaller screens that might be right, but on 5.x inch upwards sized phones moving you thumb to the top bar to scroll  the page to the top does not sound very convenient.

@AlfredSK Do you use it only on mobile or at your PC as well?
_Edit:_ And what are the reasones why you want to go to top?

**Comment by foss-** [comment]
@AlfredSK thanks for sharing your sentiment, but without explanation it is not as helpful as it could be. Can you share the devices and OSs you are using and your use-cases for this feature?

So far mobile android seems to be the only use-case due to the lack of `Tap status bar to scroll to top` feature. Am I missing something? Can we differentiate and only show this to android users? If not, show to all mobile users?

**Comment by AlfredSK** [comment]
Explanation: 
Why do you want to remove a working and useful feature? What is the point/benefit of removing it?
I think the ball is on your side to explain the removal.

PS: Remember, nearly 75% of mobile users are using Android devices. And you want to remove the only possibility for these users to get back to top of the stream w/o reloading the page. Why?

On desktop this is a non-issue because there is a hardware keyboard.

**Comment by foss-** [comment]
So consensus is, this is not needed on desktop. The argument is very simple: if you add things without questioning why, chances are, you will have developed [The Homer](https://www.youtube.com/watch?v=WPc-VEqBPHI).

GitHub, Twitter, Zulip, Discourse and many other websites are not using a back to top option on mobile. I highly doubt they all do this out of hate for android users.

**Comment by MrPetovan** [comment]
This is different. We aren't discussing whether to add this button or not. It's already there, so removing it would be more work instead of deciding of not adding it in the first place which would indeed have been less work. But we're past that, someone already spent the time to add this feature.

**Comment by foss-** [comment]
Right, this was not intended to hold up development. Initial idea was to make the existing button fit more nicely with frio themes. Lets stick with that plan and keep the element for both desktop and mobile.

**Comment by vinzv** [comment]
> Explanation:
> Why do you want to remove a working and useful feature? What is the point/benefit of removing it?
> I think the ball is on your side to explain the removal.

I don't use it at all, even on other sites than Friendica as well. So I mostly don't care about it and of course don't want to remove it _per se_. But currently the button feels a bit like a stranger which is both due to it's visuals but also because it's so off the rest of the navigation. That's why I asked for your reasons of using it so I can understand the use case(s) of this button and if maybe we can integrate a bit more into the general navigation.
Do you reach the menu with it? Or do you use it to get to the start of your timeline?

**Comment by MrPetovan** [comment]
The menu always shows so it can't be used for this. So it's your other suggestion: to get to the top of the timeline page I'm on.

**Comment by foss-** [comment]
Fits in much better now. This is what it looks like for frio dark theme with blue highlight color:

![back to top](https://user-images.githubusercontent.com/5708172/103458464-d1cecc00-4d08-11eb-9598-05935cc8cda7.PNG)
