### ISSUE TITLE
Some Re-Shares from Mastodon are falsely attributed

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9264]
### Expected behavior

As I'm using the "old style" layout for re-shared posting I expect the re-sharers profile picture being displayed alongside with the authors profile picture.

### Actual behavior

For some postings re-shared  from Mastodon contacts, originally coming from Mastodon the re-sharers profile picture is not shown. The direction icon (? I think it is the direction icon) wrongly shows that I'm following the person.

![friendica-reshare-wrong-attribution](https://user-images.githubusercontent.com/433490/93971316-26f55c00-fd70-11ea-93c7-6ecffd733f8c.png)

In the footer line of the posting, it is correctly displayed who of my contacts re-shared the posting. Clicking through to the contacts page of the original author the "Follow" button is correctly displayed.

### Steps to reproduce the problem

Wait for such an wrong attribution to arrive in the network stream and enjoy you cup of tea.

### Friendica version you encountered the problem

Friendica 2020.12-dev d0505222efa2f11e31dc555ce20237330acf9f33

**Comment by annando** [comment]
Had this been after or before you had PR https://github.com/friendica/friendica/pull/9257 active on your system? And had this post arrived before or after the merge?

**Comment by tobiasd** [comment]
d0505222efa2f11e31dc555ce20237330acf9f33 is _Merge pull request #9257 from annando/causer-id _ so most likely after

**Comment by annando** [comment]
Please have a look at this item entriy for the values of "owner-id" and "author-id". Please check if they are identical or different and to which contacts they belong.

**Comment by tobiasd** [comment]
```
 select `contact-id`, `owner-id`, `author-id` from item where guid="1da5c913-a4143166d714825e-1b149a4f";
+------------+----------+-----------+
| contact-id | owner-id | author-id |
+------------+----------+-----------+
|      11299 |    11299 |     11299 |
|      11299 |    11299 |     11299 |
+------------+----------+-----------+
2 rows in set (0.003 sec)
```

11299 is the original author of the posting.

**Comment by tobiasd** [comment]
Pleroma contacts can share these falsely attributed AP postings as well.

**Comment by annando** [comment]
How is the `causer-id` for the example above? And please also display the content of `post-type`.

**Comment by AlfredSK** [comment]
I've seen similar situations. Where the little indicator says 'You follow' but I have never heard of that user before. And I certainly don't follow.
I'm using the new style display of reshares.

With a quick scroll through the community page I found one post (no reshare) of a GnuSocial user that falsely says 'You follow...'.
And two posts of a Friendica news account (heise/squeet.me) - one says 'You follow...' the other one says 'Global'.

**Comment by tobiasd** [comment]
Causer ID is the re-sharer who is displayed in the footer.
