### ISSUE TITLE
Feature Request Relay Function

### ISSUE THREAD

**Issue by Tuxi2020** [friendica/friendica#9268]
Hallo, 
das ist ein Feature Request für die Relay-Funktion in Friendica.

Auf der https://url/community/global sollen vom Relay nur die Beiträge von den Usern angezeigt werden die nicht in der eigenen Kontaktliste sind. Das würde die Übersichtlichkeit wesentlich verbessern.

Da ich kein Englisch spreche hier die Übersetzung über deepl.com:

Hello, 
this is a feature request for the relay function in Friendica.

On https://url/community/global the relay should only show the posts from users who are not in their own contact list. This would improve the clarity considerably.

**Comment by MrPetovan** [comment]
Hi, the filtering this feature would require would significantly slow down the community page load. I understand the desire to only see "fresh" content from sources you don't already follow, but it would have a significant performance impact.

**Comment by annando** [comment]
I have to test the performance impact.

**Comment by annando** [comment]
Update: There is nearly no performance impact at all. Do we want to have it enabled all the time or only as a personal/global setting?

**Comment by Tuxi2020** [comment]
Sounds great.
If the effort is not too high, it would be great if the user could turn it off or on by himself. Then it's up to you how you want it.
What do the others think?
(deepl.com)  ;-)

**Comment by annando** [comment]
This is currently for performance testings only. We will improve this, once we know that it works fast on all systems.

**Comment by Tuxi2020** [comment]
Thanks for the information and especially for the effort.  :-)

**Comment by annando** [comment]
Do we have something to do for this, since we now do have the filtering for this.

**Comment by MrPetovan** [comment]
#9277 closes this.
