### ISSUE TITLE
Header of notification emails still not all correct

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9282]
### Expected behavior
Header fields in email should look like this:
```
Date: Sat, 26 Sep 2020 13:21:09 +0200
To: name@example.com
Subject: [Friendica Meldung] Comment to conversation
```

### Actual behavior
Header fields look like this:

```
Precedence : list
X-Friendica-Host : social.yl.ms
X-Friendica-Platform : Friendica
X-Friendica-Version : 2020.12-dev
List-ID : <notification.social.yl.ms>
List-Archive : <https://social.yl.ms/notifications/system>
```
The difference is the space before the `:`, there should not be one. 

### Friendica version you encountered the problem

Current dev, pull some hours ago. 

### Friendica source (git, zip)
git

**Comment by nupplaphil** [comment]
That's a easy one :) I'll fix it

**Comment by utzer** [comment]
Good. I just wanted to report it, it is a Schönheitsfehler I would say.
