### ISSUE TITLE
Lock additional feature in disabled state

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9286]
### Expected behavior
I'm not sure. The node admin is able to lock an additional feature as 'enabled'. So I expect that it is also possible to lock a feature as 'disabled'.
Locking an additional feature in 'disabled' state should prevent the users from enabling it.

### Actual behavior
When I try to lock an additional feature as 'disabled' I can save the settings. But the lock checkbox is empty again after saving the settings. I assume it isn't possible to lock a feature as 'disabled'. But I'm not sure about this.

### Steps to reproduce the problem
Go to admin > features
Disable a feature
Set the lock checkbox
Save settings
Check the checkboxes

### Friendica version you encountered the problem
2020.12-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
MariaDB 10.3

**Comment by AlfredSK** [comment]
Ha! **It is possible** to lock a feature in disabled state. But the admin doesn't see the locked state after saving the settings.

**Steps to reproduce**

(1) ...as admin:
Go to admin > features
Disable a feature
Set the lock checkbox
Save settings

(2) ...as user:
Go to settings > features
Look for the disabled feature
It's gone - the user cannot enable it

So, it works! But the admin cannot see that the feature is locked. The checkbox is empty. I guess that's an UI bug then.

**Comment by bkil** [comment]
Should this be tagged with `Junior Jobs` perhaps?
