### ISSUE TITLE
Search is not implemented in Twitter v.1 - compatible API

### ISSUE THREAD

**Issue by yvolk** [friendica/friendica#929]
I encounted this problem testing Friendica work with [AndStatus Android client](https://github.com/andstatus/andstatus/wiki).
E.g. valid Search request URL="https://pirati.ca/api/search.json?count=200&q=AndStatus" returns error 404 page.
See corresponding issue in AndStatus: [support for friendica](https://github.com/andstatus/andstatus/issues/55)

**Comment by tobiasd** [comment]
The issue at AndStatus is closed, does it work now so we can close this issue?

**Comment by annando** [comment]
No, not by now.

**Comment by yvolk** [comment]
Yes, closing the issue in AndStatus meant that "basic" support of Friendica works in AndStatus. Now we came to the point where this support will be extended function by function via focused issues like this one.

**Comment by Rudloff** [comment]
I would like to work on a PR to implement the GNU Social search API `search.json?q=<query>`.
Should we also add support for the new Twitter search API (`search/tweets.json`)?

**Comment by MrPetovan** [comment]
It depends on the client-side support, does Twidere use it for example?

**Comment by Rudloff** [comment]
Twidere uses `search.json`. I don't know about other clients though.

**Comment by MrPetovan** [comment]
If you can make it work with a single search function and two different wrappers for it, the better.

**Comment by annando** [comment]
Finally after only 3 years this issue was closed ;-)
