### ISSUE TITLE
the no contact discovery setting should prevent the system from discovering new contacts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9296]
### Expected behavior

There is a setting in the admin panel to "discover new contacts". When this is activated no profile data from non-contacts should be fetched and renewed.

### Actual behavior

However even if this setting is _not_ active, the system detects new contacts and refreshes the data of these contacts e.g. to show shared contacts with existing contacts. Also the contact information from profiles that once-upon-a-time were in involved in a conversation are constantly updated.

**Comment by annando** [comment]
I just checked - it does: https://github.com/friendica/friendica/blob/develop/src/Model/Contact/Relation.php#L200-L202

But I created a PR that should help: https://github.com/friendica/friendica/pull/9297
