### ISSUE TITLE
add emoji picker to compose window

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9298]
### Expected behavior

Compose window should have emoji picker. This is what Twitter offers:
![twitter](https://user-images.githubusercontent.com/5708172/94366085-f007a900-00d5-11eb-9c3a-108000d60aa9.png)

User struggling with current implementation: https://squeet.me/display/962c3e10-165f-7085-251a-a76182130593

### Actual behavior

Currently there is no emoji picker. The workaround is to use `:face` to show a list of available emojis, but that is not very convenient and most users will not be familiar with this mechanism.

**Comment by AlfredSK** [comment]
There is already an add-on for this. I think it's the smileybutton add-on.

**Comment by loma-one** [comment]
What is already integrated is not a picker as described above

**Comment by MrPetovan** [comment]
All OSes have a built-in emoji picker, whether it's Windows, Mac OS, iOS or Android. I'm less familiar with GNU/Linux GUIs, but I assume that they have one as well. We do offer a custom emoji picker because they can't be inserted from the built-in Unicode emoji pickers.

**Comment by foss-** [comment]
Emoji picker has been part of frio for a long time. Closing.
