### ISSUE TITLE
use of hashtag to removal content from message stream from the nodes conntected relay

### ISSUE THREAD

**Issue by smokinjo** [friendica/friendica#9305]
### Is the feature request related to a problem? Please describe.

Certain content is undesirable to a user for a variety of reasons and instead of removing the entire stream of messages, I'd like to see a way to remove only posts with offending hashtags.

It is done the other way in the admin section.  You stop all content, or except what you want.

### Describe the feature you'd like

Assuming that a node receives all content from a relay:

Is there a way to add hashtag filters via the admin or user page?

Ideally, it would be a global setting by admin to eliminate global hashtags.   But, having it as a user setting would allow each user to remove the content that they do not want.

### Describe alternatives you've considered

None

### Additional context

**Comment by MrPetovan** [comment]
Hi @smokinjo , there is a setting to filter messages from relays on an allow list of node-wide keywords and another to allow user-defined keywords as well, but there isn't any setting to deny posts based on a list of keywords.

**Comment by smokinjo** [comment]
@MrPetovan , you are right.  By using keywords to select what you want to read, eliminates all content, but the few words  you choose.  Not letting anything else in.   This approach eliminates all content, not allowing me to see other possibly interesting content, because it does not fit into my hand full of keywords.  This, for me, is too narrow of a focus. (maybe not for every one, depending on the needs/interests of the user/node)

I see it is as I want to let all things in, and as I see things I do not like, or prefer not to read about, I add them to my filter, and my stream gets smaller.

Each person has their preference/approach.  Having both approaches, allows a person/group to filter their content/or not as they wish.

**Comment by annando** [comment]
There should be no problem, adding some deny-list of hashtags. This would be system wide. This would override possibly subscribed user hashtags.

**Comment by smokinjo** [comment]
OK, I now see the possible consequence of this method.

Would thi sscenario be possible:

1 - at the admin level this woudl be a deny-list style. Allowing all to show up at the node, except those that are denied.
2 - at the user level, the user could choose one of the other: 
     a - deny list - thus further shrinking the content stream
     b - selective add hashtag - where the specificaly the topics via hashtags that they want

Could tis be possible?

**Comment by annando** [comment]
Deny list at the user level is not possible. A user should not be able to decide what other user don't see.

**Comment by smokinjo** [comment]
The idea is not to have an individual decide what others see.

- I assumed incorrectly that the user was able to have a say on what content the saw(only affecting their own content stream by using a accept/deny list).

So, if I understands it correctly:

- deny/accept lists are admin only
- user can not affect what is in their own stream

Not a big deal, I just thought it was possible. Would be nice, but I can live with the deny list at admin level only!

Thanks for explaining.

**Comment by annando** [comment]
Users can subscribe to tags. These tags will appear in their network stream.

**Comment by smokinjo** [comment]
OK, this is a good compromise.   Thanks!  Works for me.
