### ISSUE TITLE
Cross-Posting to Facebook/Twitter/Instagram

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9311]
I want to move away from these pesky social (ad) networks and I kinda did, but would be great if whatever I post on Friendica could be posted on these social networks with a link to the original Friendica post. This way people may start to follow us on Friendica. We have a volunteer based project (TROM tromsite.com), and we would not like to loose the followers from those ad-networks mentioned above.

I see that for Twitter there is an option to automatically post on it, but none of my tests worked. Or maybe it only posts if it is in the limit of the characters? For Facebook I see no options. 

I think that having a robust tool that can cross-post on those ad-networks could be super useful for people who want to migrate to Friendica.

And thank you so much for this wonderful tool!

**Comment by AlfredSK** [comment]
Forget posting to Facebook/Instagram. Facebook doesn't allow that. We had an add-on for Facebook. But since Facebook closed their API there is no way of cross-posting to FB.

The Twitter connector on the other hand works. As admin you need to register an "app" with read/write access at Twitter. Then the admin needs to configure that for the Friendica node. If successful the users can connect their Twitter account via the connector's user settings.

**Comment by tiotrom** [comment]
I understand about fb and instagram. I was wondering how services like https://hootsuite.com/ do it. ??

About Twitter, ok, I see. We will try our own instance of Friendica so if that works we should be able to set it up.

A follow-up question: is it possible to follow Facebook/Twitter pages/profiles from Friendica? If so, how? I seem to not understand how to do that. And second, I have set up to follow RSS sources but I do not see any RSS post into my feeds despite there being updates to those RSS sources.

**Comment by MrPetovan** [comment]
Facebook closed their API for regular users. Hootsuite is a Facebook partner and as such does still have access to it.

About your follow-up questions:
- Follow a Facebook account: Not possible.
- Follow Twitter accounts: once you set up the application and the Twitter connector at the node level, users will receive the posts from accounts they follow with their Twitter account in their Friendica timeline. They will be able to reply to such posts and the reply will be sent to Twitter.

**Comment by tiotrom** [comment]
I understand thank you for your answers!

**Comment by vinzv** [comment]
Let's close this as it won't be possible, unfortunately.

**Comment by tiotrom** [comment]
Ok sure! For those interested, I have come up with a pseudo solution to post from friendica to fb + twitter and such. I write about it here https://www.tiotrom.com/2020/10/the-social-ad-networks-the-fediverse-and-my-live-is-back/

**Comment by MrPetovan** [comment]
I can't open the link, it says "Too many redirections".

**Comment by tiotrom** [comment]
Sorry about that. It works now. I had to add it to cloudflare because the server was under immense amounts of hits and such, so it was an issue with the certificate. Works now. Mind you, this is a pseudo-solution, using IFTTT and RSS. Basically I am now posting on Friendica and the posts can go to Twitter/Facebook automatically via Friendica's RSS + IFTTT.

**Comment by MrPetovan** [comment]
Awesome, this is why we publish the RSS feed of public posts, so you aren't limited by Friendica's own plugin selection.

**Comment by MrPetovan** [comment]
I can access your article and oh boy it's excellent.
