### ISSUE TITLE
Post from Wordpress to Friendica

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9312]
We have a few websites where we post: from apps to documentaries or books. Would be fantastic to automate it so that whenever we post a new app to our Wordpress website (as a post), it will go to Friendica. I cannot find any such integration. Cheers!

**Comment by AlfredSK** [comment]
The only way I know of is to follow the RSS/atom feed of the WP blog and then configure that feed-contact as 'remote self'. That setup automatically posts the blog articles as Friendica posts to the Fediverse.

The remote self setting can be found in the contact details.

PS: sending posts **to** WP works via the WordPress connector.

**Comment by tiotrom** [comment]
Sounds interesting with the feed-contact. Can this be done with say a mastodon account? Our Mastodon account pulls posts from our blogs' RSS. I can use our Mastodon account to post on Friendica then. But clicking the user's details I see no such option...

**Comment by MrPetovan** [comment]
You don't need the Mastodon RSS feed to set up the remote self, you can just directly follow a Mastodon account and in the contact page you can set up the mirroring.

**Comment by tiotrom** [comment]
Ah sounds great. However I cannot see that option anywhere. 
![image](https://user-images.githubusercontent.com/34804533/94476700-1d854d00-01d1-11eb-873e-813cb6b439e7.png)
This is teh "contact" page for our Mastodon account.

**Comment by annando** [comment]
We don't support mirroring for Mastodon accounts. But you can simply mirror the RSS feed from Friendica.

**Comment by AlfredSK** [comment]
And the mirror option needs to be enabled in the admin panel first to make it available in the contact settings of RSS/atom feeds.

Admin > Site > Policies > Allow Users to set remote_self

Wait. Is that true? Or is the feed mirroring independent of that option? Hmm. I'm not sure.

**Comment by tiotrom** [comment]
Ok so Mastodon mirroring is not supported? Second, is it possible to mirror RSS? If so, I suppose the admin has to enable it, right?

**Comment by AlfredSK** [comment]
yes.

> I suppose the admin has to enable it, right?

yes, indeed.

**Comment by tiotrom** [comment]
Maybe this https://github.com/kernox/Mastodon-Share-for-WordPress and this https://wordpress.org/plugins/autopost-to-mastodon/ can be used to make such a plugin for Wordpress? Or make Friendica work the other way with Wordpress, grab the posts and display on Friendica?

**Comment by vinzv** [comment]
> Maybe this https://github.com/kernox/Mastodon-Share-for-WordPress and this https://wordpress.org/plugins/autopost-to-mastodon/ can be used to make such a plugin for Wordpress? 

See here: https://github.com/friendica/redmatrix_wp

> Or make Friendica work the other way with Wordpress, grab the posts and display on Friendica?

That would be exactly what RSS mirroring does.

Mastodon btw offers a RSS feed per account. That way you could even mirror an Mastodon account to your Friendica account. (Though that's quite pointless as Friendica users could simply follow the Mastodon account.)

**Comment by tiotrom** [comment]
I found the easiest way. Grab the RSS, add it to contacts, then mirror the posts from RSS as my own Friendica posts. Works like a charm. It is possible directly from the Friendica's settings. Go to the RSS contact, click "advance" and scroll down.
