### ISSUE TITLE
No Connect below Profile Picture

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9315]
- [ x] I have searched open and closed issues for duplicates

I tried to but the URL above did not work.

### Bug Description

There is no "Connect" word or button below the profile image that friendica instructions says should be there.
### Steps to Reproduce

Select another friendica user on your friendica site, go to their profile, look at the picture, no "Connect" below it.
1.  step one
2.  step two
3.  step three

Actual Result:

No Connect
Expected Result:

Expect to see a Connect word or button so I can friend them.

### Screenshots

![Screenshot at 2020-09-28 15-09-06](https://user-images.githubusercontent.com/3466797/94491287-cc5b6600-019c-11eb-84cc-7532535dcb2e.png)

### Platform Info

Friendica Version:

This is Friendica, version 2020.12-dev that is running at the web location https://friendica.eskimo.com. The database version is 1369/1369, the post update version is 1341. 

The instructions for finding version didn't work either, I found this under Help -> Information.  There is no About This Site
in my help menu.
Friendica Source: 
Git Hub Develop
PHP version:
'PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by vinzv** [comment]
Can confirm that. 
As a workaround hovering over the small profile picture gives you the option to connect:
(Text is in German over here, but should be obvious.)

![grafik](https://user-images.githubusercontent.com/74432/94975861-48460d00-0513-11eb-9106-ce1dd1d85db0.png)
