### ISSUE TITLE
Blocked accounts in admin/users not recognizable

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9326]
- [🕵️‍♂️] I have searched open and closed issues for duplicates

### Bug Description
When the admin blocks a user account at .../admin/users there is no indication that the account is blocked. The blocked account looks exactly like the unblocked accounts. It isn't possible to recognize blocked accounts.

The issue exists with *frio* and *vier*. I didn't check other themes.

### Steps to Reproduce

1.  go to admin/users
2.  block an account by clicking on the 'forbidden' icon --or-- use the checkbox + block-button at the bottom
3.  look at the user list
4.  try to discover an indication that the account has been blocked

Actual Result:
There is no indication that the account is blocked. It looks exactly like all other user accounts. Also, the 'forbidden' icon still shows "block" as mouse-over tool-tip. 

Expected Result:
Blocked accounts should be easy to recognize. There should be some visual difference to unblocked accounts (font color or bold/italic font). Or even better - there should be a separate section/accordion for blocked accounts (just like for deleted accounts).
Also, the tool-tip of the 'forbidden' icon should change to "unblock" when an account is blocked.

### Platform Info

Friendica Version:
2020.12-dev and 2020.09-1

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by tiotrom** [comment]
I agree. I would add that you can see that a user is ignored if you click its profile. But it is very confusing since there is no obvious way to see the ignored users. Also, the word "ignore" to me sounds like everything is ignored about the user. Private messages, comments, likes, etc.. Should it be changed to "don't follow"? Something similar maybe.

**Comment by AlfredSK** [comment]
@tiotrom This issue is about something different. It is about the admin panel (pages for the node admin) and the user/account management for the node.

**Comment by tiotrom** [comment]
Ah I apologize maybe I left teh comment on the wrong issue. Feel free to delete it. Sorry.
