### ISSUE TITLE
Improving the LanguageFilter settings UI

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#9328]
### Is the feature request related to a problem? Please describe.

No, not really. I want to improve the UI.

### Describe the feature you'd like

It would be nice to have a range slider for setting the value of minimal confidence. See this mockup for better understanding:

![grafik](https://user-images.githubusercontent.com/74432/94693588-33f7e980-0334-11eb-8d17-ef9e7b7d7820.png)

### Describe alternatives you've considered

As far as I've found my way through the code this would need two things primarily:

1. An additional field template like https://github.com/friendica/friendica/blob/develop/view/templates/field_input.tpl
2. An additional variable for the input field type like in `{{if $field.6}} type="{{$field.6}}"{{else}} type="text"{{/if}} name="{{$field.0}}`
3. Consequently a duplicate field template for Frio.
While the first is doable I could not find anything where those variables (`$field.X`) are defined.

### Additional context
This feature could be re-used in various other places where value ranges need to be set by the user (or admin). So it's no only related to LanguageFilter. Plus, the range slider could be extended via JS or jQuery to show a figure bubble:

![grafik](https://user-images.githubusercontent.com/74432/94694161-d4e6a480-0334-11eb-9494-ffbfa765c7ad.png)

**Comment by MrPetovan** [comment]
There are sliders in the frio theme settings but since it's theme-specific it wouldn't work out-of-the-box in vier and the other themes.

**Comment by MrPetovan** [comment]
I have a basic slider working but it has no Javascript bells and whistles and is styled according to the browser's default:

![friendica-slider-nostyle](https://user-images.githubusercontent.com/925415/95002621-103ada80-05a4-11eb-8420-716a301d3b8c.png)

Should I keep it along with my fix for https://github.com/friendica/friendica/issues/9250#issuecomment-703153334 or would you like to explore [a custom CSS solution](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/)?

**Comment by vinzv** [comment]
The default browser style is fine as a start I guess. So just shove it in. 
But having the actual value stated somewhere would be good. Something like this:
![image](https://user-images.githubusercontent.com/74432/95003878-69c2f980-05e4-11eb-926f-47d5bc57d2da.png)

**Comment by MrPetovan** [comment]
I ended up lifting the slider from the frio theme settings, turns out it's a couple inline Javascript callbacks so it will work in all themes.
