### ISSUE TITLE
MySQL error while executing various functions

### ISSUE THREAD

**Issue by Tuxi2020** [friendica/friendica#9329]
### Bug Description
This bug report was written on the following forum post: https://libranet.de/display/ec054ce7-785f-74a4-00f0-719531886627

The search function and the display of my contacts' network posts did not work because of the following MySQL errors:

"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'friendica.item.uri' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by".

The following entry in the MySQL config file solved the problem:
sql_mode = "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

It would be good if this entry in the config file was not necessary.

Translated with www.DeepL.com/Translator (free version)

### Steps to Reproduce

1. display network postings of the contacts
2. search function in the Friendica interface

Actual Result:

No result is displayed after performing the above steps

Expected Result:

After executing the two functions mentioned above, a result must be displayed

### Screenshots

none

### Platform Info

Friendica Version:

Friendica 'Red Hot Poker' 2020.12-dev - 1369

Friendica Source: Git

PHP version: 7.0.4

SQL version: MySQL 5.7.31 (Ubuntu 20.04)

**Comment by AlfredSK** [comment]
This is specific to MySQL. They're using `only_full_group_by` in their default SQL_MODE setting. MariaDB on the other hand doesn't include that in their default setting.
