### ISSUE TITLE
PWA doesn't install on Firefox

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#9337]
After recent update(s) Friendica is no longer installable as PWA on Firefox Mobile

### Steps to Reproduce
Delete installed PWA and try to install it again.

Actual Result:
PWA doesn't install as PWA. If it was installed previously there can be some display glitches (it is still kind of looks as PWA but unnecessary browser controls might appear, background isn't seamless sometimes, etc). 

Expected Result:
PWA works.

Friendica Version:
2020.09-1

There seems to be a problem with PWA manifest preventing it to install. I tried changing values and it appears that icon size "128x128" is no longer enough to make the app installable, it has to include "192x192". Also it seems that background and theme color attributes are not populated (but it isn't critical, just doesn't look nice).

Example of manifest which doesn't work on Firefox:
https://venera.social/manifest

My manually tweaked manifest which works for me:
https://friends.deko.cloud/manifest

**Comment by SpcCw** [comment]
Also I tried it on Chrome and it works there. However it seems like 192x192 is included by almost all PWA websites I tried so maybe it should be considered standard now?

**Comment by AlfredSK** [comment]
Yep. Seems 192x192 is mandatory. Also a 512x512 icon is recommended.

Google: [Web app installability requirements](https://web.dev/installable-manifest/#recommendations)
Mozilla: [Add to Home screen](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#How_do_you_make_an_app_A2HS-ready)

**Comment by MrPetovan** [comment]
Can you please try after pulling the newest `develop` changes?

**Comment by vinzv** [comment]
Just tested sucessfully with FF Mobile and Chrome (both Android) on state of 50a0927e7e4166416e3a6919d263bf0460bcbe5a.

**Comment by nupplaphil** [comment]
Fixed by #9343
