### ISSUE TITLE
Original link auto copy

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9338]
Hello there,
Since I mirror my twitter and friendica feed, I've been trying to do everything in friendica.  However I still like to post them to facebook.  I used to go into twitter to copy the initial tweet or article.  Discovered that I can go into the code and just copy it and post it.  Would it be possible to just skip that step and have a copy original button so I don't have to go into the code and copy the link?  Would make posting to multiple platforms much easier.

**Comment by MrPetovan** [comment]
Where in the code did you go to get the original link?

**Comment by anubis2814** [comment]
[share author='George Takei' profile='https://twitter.com/GeorgeTakei' avatar='https://social.isurf.ca/photo/14651574695c50529d6d121952116156-5.jpg?ts=1594144336' link='**https://twitter.com/GeorgeTakei/status/1312410528166350848**' posted='2020-10-03 15:13:47' guid='a6551d7128bfde64ab961540cbd495d019d64710']Look. When people drink and drive, they are being irresponsible and putting others in severe danger. When they get drunk and crash their cars, we pray that they didn’t hurt anyone and will themselves recover. But we also condemn their behavior as criminally reckless. Got it?[/share]

**Comment by anubis2814** [comment]
[share author='FiveThirtyEight' profile='https://twitter.com/FiveThirtyEight' avatar='https://social.isurf.ca/photo/54038636445c66b3307c568418946876-5.jpg?ts=1601058327' link='https://twitter.com/FiveThirtyEight/status/1312409968461656067' posted='2020-10-03 15:11:34' guid='a6551d71178a0c65d8daabec838d7c5c8e24a066']Watch this space: We’ll be monitoring polls for signs of how all this news affects the presidential race.
[attachment type='link' url='**https://53eig.ht/3jrCFF7**' title='2020 Election Forecast' image='https://fivethirtyeight.com/wp-content/uploads/2020/08/2020-FTE-PresPromo-16x9-sized.jpg']Latest forecast of the 2020 presidential election between President Donald Trump and Joe Biden by Nate Silver’s FiveThirtyEight[/attachment][/share]

**Comment by anubis2814** [comment]
Either one will do. Having an option for both would be amazing.

**Comment by MrPetovan** [comment]
If you're using frio, the original link of shared post is displayed as an external link icon, you can copy it via the right-click menu on your desktop browser: 
![friendica_external_link](https://user-images.githubusercontent.com/925415/94997598-41061a00-057a-11eb-8214-036e5b6bf3be.png)

For attachments, both the title, image and domain name are links to the web page that you can copy with a right-click in your desktop brwoser.
