### ISSUE TITLE
Don't update the trending tags every couple of minutes

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9344]
- [X] I have searched open and closed issues for duplicates

### Bug Description
The query for updating the trending tags is a heavy task. That query runs for approx. one minute and is examining millions of rows on a larger DB.
It doesn't make sense to run that query multiple times per hour.

Actual Result:
```
# Time: 201002 21:57:35
# User@Host: frnd_admin[frnd_admin] @ localhost []
# Thread_id: 35006  Schema: friendica  QC_hit: No
# Query_time: 41.990267  Lock_time: 0.000027  Rows_sent: 20  Rows_examined: 36230437
# Rows_affected: 0  Bytes_sent: 589
# Tmp_tables: 1  Tmp_disk_tables: 0  Tmp_table_sizes: 254184
# Full_scan: Yes  Full_join: No  Tmp_table: Yes  Tmp_table_on_disk: No
# Filesort: Yes  Filesort_on_disk: No  Merge_passes: 0  Priority_queue: Yes
SET timestamp=1601675855;
SELECT `name` AS `term`, COUNT(*) AS `score` FROM `tag-search-view` WHERE `private` = 0 AND `wall` AND `origin` AND `received` > DATE_SUB(NOW(), INTERVAL 24 HOUR) GROUP BY `term` ORDER BY `score` DESC LIMIT 20;
```

10 minutes later the query ran again. And so on...

Expected Result:
Dunno. I think it would be sufficient to run that task like once every 8 hours or so.

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by annando** [comment]
We could move this task to the section of the cron that is executed hourly. And/or we can add a check that we don't calculate this, if it was deactivated.

**Comment by AlfredSK** [comment]
Issue doesn't exist in stable. The query is super fast. 1 second instead of 30-50 seconds.
