### ISSUE TITLE
Improve GitHub issue templates: disable blank issue

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9349]
Currently there are templates for

- Bug report (Create a report to help us improve)
- Feature request (Suggest an idea for this project)
- Question / Support (Select this if you have a question)
- Friendica Community Support (Please ask and answer questions here.)

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository says

> You can encourage contributors to use issue templates by setting blank_issues_enabled to false. If you set blank_issues_enabled to true, people will have the option to open a blank issue.

Templates currently have "Don’t see your issue here? Open a blank issue. " but imo it's fair to disable as all options are covered by the template options.

**Comment by nupplaphil** [comment]
I thought about it too but wasn't sure if it isn't a hard constraint for contributers ..

**Comment by foss-** [comment]
Not many reports use the blank format so probably fine to close this issue.
