### ISSUE TITLE
Forum/news/organization tabs in contacts.

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9355]
When you click on your contacts there are tabs for All contacts, followers, following, and mutual contacts.  Please also add one each for Forums, News and Organizations. That would help to organize my contacts further..
Thanks!

**Comment by MrPetovan** [comment]
Good suggestion. It can be done easily with an additional query filter like the one used for the relationship direction.

**Comment by annando** [comment]
The only problem that I see is that one might want to combine these filters (possibly you want to see organizations that are following you). So we might use a sidebar filter like we do on the network and community page.

**Comment by MrPetovan** [comment]
Yup. We have the technology.
