### ISSUE TITLE
like toggle on /contact/{id}/conversations page not (visually) completing 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9358]
The like function on the contact conversations page seems to load forever / does not seem to visually complete.

- [x] I have searched open and closed issues for duplicates

### Bug Description
On the contact conversations page, when I like or 'unlike' a post, the spinning graphic seems to spin forever and does not seem to complete, until I reload the page. I have only tried with diaspora contacts.

On the `/network?order=post` page, this function works. After very short time the spinner image disappears and the likes get refreshed (new like is counted/displayed).

### Steps to Reproduce

1. go to a (diaspora) contact's conversations page (for example hovercard -> click cloud icon)
2. like a post
3. wait or reload page if it does not seem to complete visually

Actual Result:

only after reloading the page, the spinning graphic disappears and the new like is displayed

Expected Result:

show the spinning image and hide it again and refresh the likes below the post 

### Screenshots

![friendica-like-endless](https://user-images.githubusercontent.com/5753419/95013951-efc25d00-0643-11eb-848e-96522038db66.jpg)

### Platform Info

Friendica Version: 2020.09-1
database version: 1369/1369 
Post-Update-Version: 1350
Theme: Frio V.0.8.5

**Comment by annando** [comment]
Something similar happens with commenting. The "update" functionality that should do it in the background doesn't work so well.
