### ISSUE TITLE
Cut and paste photos

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9359]
If not for this lack of a feature I wouldn't have to use twitter or mastodon.  Instead If I want to share a picture directly through friendica I have to download the picture whcih takes time and storage space, upload it, which takes time and storage space and then post it.  So instead I will cut and paste into twitter usually which will mirror onto my friendica feed.  I think I've talked to people in the developer's forum and they said this may take a while to figure out an require an outside client to pick, but formally putting it in as a request now to get it into the discussion.
Thanks as always for your hard work.

**Comment by MrPetovan** [comment]
Thank you for you report. Athough even if we implement cut and paste photos in posts/comments, it will take storage space on your Friendica node, the same way the picture you upload to Twitter takes storage space on Twitter.

**Comment by anubis2814** [comment]
True but I would like to be on twitter as little as possible and eventually get off of it entirely.  Freindica has allowed me to mostly get away from facebook.  Upsides and downsides.

**Comment by annando** [comment]
I think it would be a nice idea to simplify the picture upload by using c&p.

**Comment by anubis2814** [comment]
This is now an option, thanks!
