### ISSUE TITLE
Friend not follow, and friend them on their profile 

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9372]
Would it be possible to do like facebook and have a distinction between friending and following?  I have family members that I would like to get off of facebook, but thanks to politics we don't follow each other to prevent starting arguments.  Facebook is just an easy way to check up on each other and keep in touch.  Also for some people with I think mastodon or diaspora accounts, when you go to their page there is no option to follow them.  You have to do a search for their address and then have the option to follow them.  Understand fi either of these are logistically difficult and wont happen for a long time.

**Comment by MrPetovan** [comment]
You can follow someone and then immediately ignore them to prevent their content to show in your network page, but they will still remain in your contact list and you will be able to see their timeline of public posts.

As for the remote follow button, I can verify it exists on my node: https://friendica.mrpetovan.com/profile/hypolite

There's a "Follow" button that leads to https://friendica.mrpetovan.com/remote_follow/hypolite which is the page you want to put your Diaspora/Mastodon account URL in to follow my account.

**Comment by annando** [comment]
I not completely understand this request. So you don't want to follow someone but wants to follow someone?

**Comment by anubis2814** [comment]
With another person on friendica the follow button is there, but if you find someone you want from a non-friendica.  Pulled someone out of the directory literally at random.  https://quitter.pl/profile/mik/profile  On their profile there is  no option to follow them.  If you take their account address and put it into search you will be given the option.  

Thanks about the ignore, I'll try it out.  Will probably help.

**Comment by MrPetovan** [comment]
Indeed, let me see if it depends on the theme but it really shouldn't.

**Comment by anubis2814** [comment]
Thanks!

**Comment by MrPetovan** [comment]
Hum, it doesn't depend on the theme: https://friendica.mrpetovan.com/profile/hypolite6/profile

I would bet that it's a version issue, [we fixed these buttons on `develop` pretty recently](https://github.com/friendica/friendica/pull/9357) so these buttons will not show on Friendica nodes running on version 2020.09 included to 2020.12 excluded.

**Comment by anubis2814** [comment]
I believe this is good enough and is no longer needed.
