### ISSUE TITLE
Merge frio-specific share block template into the base template

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9378]
See https://github.com/friendica/friendica/issues/9377#issuecomment-704632217 for a description of the issue.

Task list:
- [ ] Investigate [this interesting CSS situation](https://github.com/friendica/friendica/blob/a78b9caa3f6c05b61ce99cdd00fc8e1ee8ef8788/view/theme/frio/css/style.css#L1814-L1830) I introduced in https://github.com/friendica/friendica/pull/8740.
- [x] Replace/Merge the base `share_content.tpl` template file with the frio-specific one.
- Update/Fix display on:
    - [x] vier
    - [ ] smoothly
    - [ ] duepuntozero
    - [ ] quattro

**Comment by Extarys** [comment]
If I try to fix this, how can I test it?

**Comment by MrPetovan** [comment]
Thanks for offering! The way you can test this is by clicking on the quote-share button, and bringing up the preview in the compose modal/form. This has to be done with each separate theme activated for your test account.

This also means you need a Friendica instance for which you can edit the files.

**Comment by Extarys** [comment]
Thanks.

I was testing friendica on my computer to code as it's easier. I might get a VPS soon on OVH to install this and matrix. I might be able to work on this at that point, as my local installation doesn't have a domain name associated with it and I want to avoid exposing my IP address publicly and take the unnecessary risk.

**Comment by MrPetovan** [comment]
I believe you can still test this particular issue with a local installation even with no federation features by accessing it from `localhost` for example. You don't even need a running worker!

**Comment by Extarys** [comment]
Oh :facepalm: yeah nevermind I have multiple test accounts.

**Comment by annando** [comment]
Isn't this solved with https://github.com/friendica/friendica/pull/10170?

**Comment by MrPetovan** [comment]
Not if there still are at least two `share_content.tpl` templates file in different folders in the repository.

**Comment by annando** [comment]
The share element is now fetched every time, so we don't have the issue when changing themes anymore like described in that issue.

**Comment by MrPetovan** [comment]
If it's still cached in the item, then it still will cause visual discrepancies depending on which user's triggered the first render. Previously, it only depended on the node's default theme.

**Comment by annando** [comment]
Ops, I just had been confused by my own coding. With this version we are removing the `attachment` element before rendering and the the `share` element.

**Comment by MrPetovan** [comment]
What does in mean in practice?

**Comment by annando** [comment]
In practice we are now handling the media and link attachments "on the fly". This doesn't slow down the system but it adds more flexibility. This also enabled us to finally handle the Mastodon API without many problems.

**Comment by MrPetovan** [comment]
Does this include reshared/share-quoted posts? Are quoted post body fetched from the item cache as well?

**Comment by annando** [comment]
It only affects the attached media in that posts.

**Comment by MrPetovan** [comment]
Ok, so the caching issue still stands.
