### ISSUE TITLE
[frio] Cannot scroll left fly-out sidebar on mobile

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#9383]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When using Frio on mobile, when the fly-out sidebar is opened, it cannot scroll vertically. Any content in the sidebar beneath the edge of the screen is inaccessible.

### Steps to Reproduce

1. Switch your theme to Frio if it is not already.
2. Open Friendica on mobile or resize a desktop window to be narrow enough that the sidebar collapses and the three vertical dots (⋮) are visible on the left of the navbar.
3. Navigate to a page with a sidebar, such as the Contacts page or your Profile.
4.  Open the sidebar by tapping the (⋮) on the left of the navbar.
5. Attempt to scroll the navbar vertically.

**Actual Result:**

The navbar does not scroll. When you swipe vertically (or scroll with the scrollwheel if using a mouse), nothing moves.

**Expected Result:**

The navbar scrolls in accordance with the swiping or scrollwheel scrolling.

### Platform Info

**Friendica Version:** 2020.09

**Friendica Source:** https://files.friendi.ca/friendica-full-2020.09.tar.gz

**PHP version:** 7.3.19-1~deb10u1

**SQL version:** 10.3.23-MariaDB-0+deb10u1

**Comment by MrPetovan** [comment]
I noticed this as well. I believe it is because the sidebar has `position: fixed` which enables to see it no matter how far down the page is scrolled, but it doesn't have a limited height to the current window which prevents scrolling the side bar itself.
