### ISSUE TITLE
Editing a post on Frio adds extra nonfunctional permissions fields to the composer until the page reloads

### ISSUE THREAD

**Issue by SpencerDub** [friendica/friendica#9385]
- [X] I have searched open and closed issues for duplicates

### Bug Description
Using the Frio theme, if you edit and submit a post, then open the post composer again on the same page *without reloading*, the Permissions tab displays extra nonfunctional fields, one per each time a post has been submitted on that page.

### Steps to Reproduce

1. Use the Frio theme.
2. Compose and publish a post.
3. Locate the post in a feed. I've been using the Network/Latest Activity view, but I've seen this on the Profile/Status view as well.
4. Click the "More" link and select "Edit". Edit the content of the post, perhaps by adding a character or word. Save the edit.
5. Click the "Compose" button in the tab bar to create a new post.
6. Click the "Permissions" tab in the post composer, and then click "Limited/Private".
7. Close the new post composer without saving a post.
8. Repeat steps 3-7 several more times. 

**Actual Result:**

Each time a post edit is saved on a page, an extra field is added to both the "Show to" section and the "Except to" section on the Permissions tab.

All of these fields, except those at the very bottom of the groups, are nonfunctional. They do not autocomplete contacts if you type in them, and if you click on the "X" to delete listed groups or contacts, it will not work--unless you are interacting with the field at the bottom of the group.

If these excess fields exceed the height of the post composer, it is impossible to scroll vertically to view the rest of the content. This means that after about 3 or 4 edits on the same page, it is impossible to set "Except to" permissions settings on this new post, because the functional "Except to" field is at the bottom of the group, which is not displayed and cannot be scrolled to.

If you reload the page, the extra fields will disappear, but they will begin accumulating again as you edit posts.

**Expected Result:**

No matter how many posts you edit on a page, the post composer's Permissions tab will only ever contain one field of each "Show to" and "Except to", and they will both be functional.

### Platform Info

**Friendica Version:** 2020.09

**Friendica Source:** https://files.friendi.ca/friendica-full-2020.09.tar.gz

**PHP version:** 7.3.19-1~deb10u1

**SQL version:** 10.3.23-MariaDB-0+deb10u1

### Screenshots
![Frio extra permissions fields - 02](https://user-images.githubusercontent.com/4674927/95365454-00aee080-0887-11eb-89df-b51b5359f598.png)

**Comment by MrPetovan** [comment]
Whoa.

**Comment by MrPetovan** [comment]
Simpler steps to reproduce:
1. Click on Edit on any of your posts.
2. Close the modal.
3. Open the compose modal in the permissions tab.

For more inputs, repeat 1-2.
