### ISSUE TITLE
auth_ejabberd.php loads with no errors but doesn't authenticate

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#9394]
Latest `develop` code at ad316447b5429d75b907f9ccbb77e9c1f2a01ef7 does let `bin/auth_ejabberd.php` (correct chmod/chown) load but no authentication takes place.

I have now finally PHP 7.3:
````
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0RC2, Copyright (c) 2002-2019, by Derick Rethans
````

**Comment by MrPetovan** [comment]
How do you know no auth took place? Any PHP error? What does the Friendica log look like on auth attempts?

**Comment by Quix0r** [comment]
I got the error message "Invalid username or password", but both are correct.

**Comment by Quix0r** [comment]
I remember we once had that with some magic thing? I can barely remember it.

**Comment by Quix0r** [comment]
I have added a cachegrind file, maybe it can help finding the place? It invokes through the `ExtAuth::checkCredentials()` and then `ExtAuth::auth()` method.

https://f.haeder.net/cachegrind.txt

**Comment by Quix0r** [comment]
Wrong link, "Edit" doesn't work here on Github since @microsoft took over. ;-(

https://f.haeder.net/cachegrind.txt

**Comment by annando** [comment]
I'm using ejabberd with this on my machine - and it is working here. AFAIK it has some logging possibility as well, so please have a look.

**Comment by Quix0r** [comment]
Setting the same clear-text `password` for `uid`=1, `cat`='xmpp' in table `pconfig` does fix this issue.

**Comment by Quix0r** [comment]
Setting the same clear-text password for `uid=1, cat='xmpp'` in table `pconfig` does fix this issue.

**Comment by MrPetovan** [comment]
Oh man, not being able to edit one's own comments on GitHub is going to annoy me.

**Comment by tobiasd** [comment]
mmh... ok immediately after commenting you still can edit the comment.

And even some days later, this comment is editable.

**Comment by MrPetovan** [comment]
In this repository you have the right to edit anyone's comment, including your own, did you test it on a repository you were just visiting?

**Comment by Quix0r** [comment]
Let's leave it there. The hex-encoded password is back and I was not able to login. It happened just now?

**Comment by MrPetovan** [comment]
Looking at the code, this happens during a regular frontend authentication. The session variable `allow_api` isn't set so the addon generates a random hexadecimal value and assign it to the personal config value `xmpp.password`.

There's no hint as of why we're doing this since the `allow_api` variable is only set when authenticating against the API.

**Comment by Quix0r** [comment]
When we talk about it, I noticed that Adminer always wraps `cat` and `k` into `HEX()` calls as it is binary. I have these `cat` and `k` values visible (and searchable!): `` `cat`='6E6574776F726B2E76696577' ``, `` `k`='67726F75702E73656C6563746564'``. If I remove the `HEX()` calls, it shows `` `cat`='network.view'`` and `` `k`='group.selected'`` which is searchable.

I would propose to change the column types to `varchar` and not `varbinary`.
