### ISSUE TITLE
No admin account after import of profile

### ISSUE THREAD

**Issue by regenpfeifer** [friendica/friendica#9396]
I have switched my server hardware and therefore also had to re-install my friendica instance. I have exported my friendica profiles / identities. After the new installation of friendica I hat the opportunity to import my saved profile. I chose this way instead of creating a new (admin) user.

Now I am logged in with this imported profile. But unfortunately this seems not to be an admin account (the saved profile was admin). Now I am somehow locked-in. It seems that my Friendica-Installation has only one user, which is NOT admin. Is there any way to make my imported profile admin?

Please excuse me that I am asking here. I cannot ask in the community help forum, because here I am registered as "user" (with the re-imported account), but my questions do not appear.

Thank you for any help, regenpfeifer

Ich habe meinen Server - und damit auch meine Friendica-Instanz - neu aufgesetzt. Zuvor habe ich mein(e) Profile(e) exportiert. Nach der Neu-Installation wurde mir gleich beim Start angeboten, das gesicherte Profil zu importieren. Dies habe ich gemacht, anstatt einen neuen Nutzer zu erstellen.

Nun bin ich mit diesem importierten Nutzerkonto / Profil angemeldet. Obwohl dies in der vorherigen Installation ein Admin-Konto war, ist es dies hier anscheinend nicht. Nachdem es sich um eine Neu-Installation handelt, habe ich nun womöglich überhaupt kein Administrator-Konto und stecke fest.

Gibt es eine Möglichkeit, den importierten Nutzer zum Admin zu machen? Danke!

**Comment by regenpfeifer** [comment]
Meanwhile my post has appeared in the Helpers Forum and I am looking foward to answers there.

**Comment by tobiasd** [comment]
> Now I am logged in with this imported profile. But unfortunately this seems not to be an admin account 

You need to set the email address of the admin(s) in the config file of Friendica. Once that matches the email address of the account you will have access to the admin panel again.

Have a look for

```
'config' => [
                'admin_email' => 'bob@example.com',
```

in your `config/local.config.php` file.

**Comment by Quix0r** [comment]
I think this can be closed now?

**Comment by regenpfeifer** [comment]
Oft course, this can be closed, thank you!
