### ISSUE TITLE
Comments on PeerTube videos not working

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9407]
- [🤖] I have searched open and closed issues for duplicates

### Bug Description

When I comment a video that was posted on PeerTube I expect the comment being shown on PeerTube as well. However it is not.

* [Link to PeerTube video](https://mytube.madzel.de/videos/watch/973793f8-38c9-48dd-aeb1-f46080db4898)
* [Link to Friendica showing the comment](https://pirati.ca/display/973793f8-38c9-48dd-aeb1-f46080db4898), meaning it is distributed to the thread contributors
* [Original link to the comment](https://social.diekershoff.de/display/f3ad7b1c-205f-82a6-b64c-839232956551)

### Steps to Reproduce

- Receive a video from PeerTube or import it via the search bar.
- Comment on it.

### Platform Info

Friendica 2020.12-dev e3cf708dd819ffabe53fb299cad5cb76b24aaf5c

**Comment by annando** [comment]
I saw this as well. Since we don't seem to have issues with other AP implementations, this possibly could be an issue inside of PeerTube.

**Comment by tobiasd** [comment]
The interactions from Mastodon are arriving at the video.

**Comment by tobiasd** [comment]
Tested to reply with the @-mention included, but that did not work either.
