### ISSUE TITLE
Add videos to an instance via archive.org

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9421]
Since uploading videos and streaming them takes a huge toll over any server, and as far as I've seen the video-upload feature is not allowed/existent in some Friendica instances (maybe in most), what about a way to connect Friendica with archive.org and basically pull the video library from my personal archive.org account into friendica? to connect the two. This is their API https://archive.org/services/docs/api/.

We are using archive.org for our projects and have uploaded hundreds of GB and all works like a charm and there is no limitation in terms of storage it seems. You can upload as much as you want.

Ok, let me know what you think about this idea :)

**Comment by tio-trom** [comment]
I think we can close this one. I opened it but with an old github account so I cannot close it. Does not make sense now. We have Peertube. Perhaps Friendica will support video uploads in the future. So please whoever can, close this one :)
