### ISSUE TITLE
/network not working

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9423]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

/network does not load anymore, a fault is displayed instead. 
![image](https://user-images.githubusercontent.com/8361662/95994229-53ad0880-0e30-11eb-9d55-a3ced9a85f3e.png)

Error:
```
#0 [internal function]: Friendica\Module\HTTPException\PageNotFound::content()
#1 /srv/http/src/App/Page.php(331): call_user_func()
#2 /srv/http/src/App/Page.php(387): Friendica\App\Page->initContent()
#3 /srv/http/src/App.php(559): Friendica\App\Page->run()
#4 /srv/http/index.php(42): Friendica\App->runFrontend()
#5 {main}
```

### Steps to Reproduce

1.  go to /network on your server.

Expected Result:

List of posts from friends. 

### Screenshots

see above.

### Platform Info

Friendica Version:

Friendica Source: 
git - develop branch, pulled today. 

PHP version:
PHP 7.4.11

SQL version:
not sure. 

Post in !helpers
https://social.yl.ms/display/a8e4f565-145f-86f9-4e97-a76106526546

**Comment by annando** [comment]
The reason will be the router cache. The router data is cached for 24 hours. I'm unsure if there are ways to easily clear it. @MrPetovan to the rescue!

**Comment by ghost** [comment]
Now it works for me again.

**Comment by MrPetovan** [comment]
See https://github.com/friendica/friendica/pull/9419#issue-501969299

> As usual with router file changes, the cache must be regenerated, the simplest way to do this is to reload the addons in the administration.

**Comment by MrPetovan** [comment]
I should write a cache-buster routine based on the router file modification time the same way Smarty recompiles template based on their time of last modification.

**Comment by utzer** [comment]
Yes, we should avoid these special actions needed, users will just see it is not working and they will not like it. So best to implement such a "buster", and for the other caching it would be great too. 

Thanks for explaining.

**Comment by MrPetovan** [comment]
Thanks to #9425 router dispatch data will now be automatically re-computed when the base routes file is changed.

**Comment by utzer** [comment]
Closed
