### ISSUE TITLE
reshare doubletts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9428]
### Bug Description

Two if my contacts (one from Mastodon, one from Pleroma) re-shared the same posting from a Mastodon account. Both re-shares were displayed (directly after each other, hence I noticed it). As the both are re-shared (via AP) I expect to only see the posting once.

### Steps to Reproduce

Get to contacts to re.share one posting in the same moment perhaps?

### Screenshots

![grafik](https://user-images.githubusercontent.com/433490/96236361-3d23c000-0f9c-11eb-9997-7ec5643199d5.png)

### Platform Info

Friendica 2020.12-dev 472cc10ac5e8a688a7767313474f60d05edf52f6

**Comment by annando** [comment]
These are different posts. Have a close look at the text.

**Comment by MrPetovan** [comment]
It was probably a Delete & Redraft couple of posts. We still don't fully honor deletions, maybe because of a race condition in this case.

**Comment by tobiasd** [comment]
You are right @annando m) ok, closing this issue :D

**Comment by annando** [comment]
@MrPetovan Delete does work - but the situation most likely was that the item had been reshared before - and had been received before as well. The delete then isn't propagated to this system, since it is not in the list of known receivers, so we can't process the delete.
