### ISSUE TITLE
Everyone who looks at the friendi.ca site thinks you have to download it

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9430]
Everyone who looks at the friendi.ca site thinks you have to download it.  I've had friends go to the site which they were driven to leave facebook and give up because they think they have to download it.  Its very server host oriented and is turning off and pushing away people who would join.  The front page needs to be more instructive on how to pick an instance or people will go to the page ready to join and then give up because it doesn't make any sense to them..

**Comment by MrPetovan** [comment]
You are 100% right about this.

**Comment by foss-** [comment]
This 💯 - a simple change to tackle this with very low cost and intended effect would be to just switch order of `Download` and `Try It` buttons. Suggested that a few years ago, but response back then was to focus on decentralization. I still do not think that is smart. Most users are not admins. So there is no point in telling them to setup their own instance. Not even sure if Download is a good term. The button is not a download but goes to a wiki page. Maybe `Setup Instance` would be more descriptive and accurate?
![website](https://user-images.githubusercontent.com/5708172/96368211-03e18080-1153-11eb-99bb-a5448f9fe96d.png)

**Comment by anubis2814** [comment]
I would actually move the download button further down the page in its own section.  Considering there are only 3 stable long term instances in the us obviously that idea didn't really do what it intended

**Comment by anubis2814** [comment]
In fact I'd move the download Button all the way to the area that says Free Software - Free Protocols.  And Instead maybe put a title there saying "What to run your own server?" Everything above should be selling and explaining the options.  A person has to be sold on it as well before they would consider downloading it in the first place there are a lot of platforms out there why shoudl they run ours in the first place if it hasn't sold itself.

**Comment by MrPetovan** [comment]
I agree with @anubis2814 , we have two distinct audiences on friendi.ca and we should treat them separately: Friendica users and Friendica admins. Currently the front page is speaking to both at the same time which is confusing. We should create two separate landing pages for users and admins, and populate them with relevant information for each.

**Comment by annando** [comment]
I agree as well - I simply just donÄt know how to do it :-)

**Comment by tobiasd** [comment]
My guess, update the WP-Theme or ask @fabrixxm ;-)

**Comment by MrPetovan** [comment]
Is it a custom theme?

**Comment by tobiasd** [comment]
Yes, or at least customized - see https://git.friendi.ca/friendica/friendica-wp-theme for the sources.

**Comment by fabrixxm** [comment]
https://git.friendi.ca/friendica/friendica-wp-theme/pulls/8
(have a look at what I wrote in it, because my English is really bad...)

A screnshot of the home page with annotated changes:
![bitmap](https://user-images.githubusercontent.com/309361/96561640-1deca180-12c0-11eb-9ba4-155a779a71e4.jpg)

_edit: updated screenshot_

**Comment by tobiasd** [comment]
I'll put it live this evening, if nobody else does.

**Comment by MrPetovan** [comment]
Closed by https://git.friendi.ca/friendica/friendica-wp-theme/pulls/8
