### ISSUE TITLE
twitter preview

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9447]
I miss the twitter preview rendered when posting a twitter link like this one:
https://twitter.com/henryhneff/status/1318922746030624768

- [x] I have searched open and closed issues for duplicates

### Bug Description

I shared a twitter link and expected or hoped that some preview from twitter would be rendered or maybe some opengraph link with picture, but did not see that. 

### Steps to Reproduce

1. copy the twitter link from the browser address bar you want to share
2. write a new post in friendica
3. paste the link, for example https://twitter.com/henryhneff/status/1318922746030624768
4. post the post and look if something is rendered

Actual Result:

![friendica-twitter](https://user-images.githubusercontent.com/5753419/96904055-e4ba5a00-1496-11eb-897e-7c7ed650a1f2.jpg)

Expected Result:

something like this (from diaspora .. or simpler (opengraph))
![friendica-diasp-twitter](https://user-images.githubusercontent.com/5753419/96904246-20edba80-1497-11eb-8f28-ac554ec17c55.jpg)

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2020.12-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1370/1370 und die Post-Update-Version 1349/1350."

**Comment by AlfredSK** [comment]
Captains log, supplemental:
I do not have Twitter on the 'Allowed OEmbed domains' list. But I think a normal preview (image, text - w/o directly embedding the tracking hell from Twitter) should be possible.

**Comment by SpencerDub** [comment]
I am also encountering this behavior on v2020-09. I have the Twitter connector enabled and configured for my account, but still nothing. In the OEmbed settings, I have no domains allowlisted, but I also haven't checked the "No OEmbed rich content" box:

![OEmbed settings](https://user-images.githubusercontent.com/4674927/96906822-39d27d80-144f-11eb-92da-d268366464fb.png)

Possibly related: When I paste the URL of a tweet into the search bar, it does not fetch the tweet; instead, Friendica creates a profile with a URL that links to that tweet:

![Twitter profile](https://user-images.githubusercontent.com/4674927/96906874-4b1b8a00-144f-11eb-96a1-706cf66ef547.png)

I expect tweets to look like [this](https://friendica.mrpetovan.com/display/735a2029-105f-8ef0-e929-f10213863281) in Friendica, which appears to be an example of a tweet being properly parsed and reshared natively, probably through the Twitter connector? But I'd sure like it if that sort of native reshare didn't require importing one's Twitter stream.

**Comment by MrPetovan** [comment]
https://friendica.mrpetovan.com/display/735a2029-105f-8ef0-e929-f10213863281

This display is created by the mirroring feature of the Twitter connector, which is distinct from the general URL parser we use to create rich content previews in posts.

**Comment by SpencerDub** [comment]
> https://friendica.mrpetovan.com/display/735a2029-105f-8ef0-e929-f10213863281
> 
> This display is created by the mirroring feature of the Twitter connector, which is distinct from the general URL parser we use to create rich content previews in posts.

Gotcha. Separate issue, then; sorry.

**Comment by MrPetovan** [comment]
Related to #8736

Twitter doesn't offer OEmbed anymore, but we should be able to hook the Twitter addon into the parse URL to provide a nicer looking share box.

**Comment by MrPetovan** [comment]
Alright, the Twitter addon isn't meant to be used from the node itself without a registered Twitter account, so I have a general question about contacts: does `rel = 0` mean anything for public contacts with `uid = 0`? @annando

**Comment by MrPetovan** [comment]
Here's the new result with the new `parse_link` hook from the Twitter addon. If it is enabled and correctly set up at the node level, any user, even without a linked Twitter account, will be able to add these previews to their posts.

![friendica-preview-twitter-link](https://user-images.githubusercontent.com/925415/96962811-8c567d00-14d5-11eb-898e-0564509aa8af.png)

**Comment by haheute** [comment]
I have just posted a twitter link on libranet.de which imo runs the latest code, but i still can't see a preview:
https://libranet.de/display/0b6b25a8-195f-a30e-9570-32f149981978

Is this preview generated when it's posted or when the page/stream is loaded ? Does it make sense to wait for older posts, until they show the image and description or should i test with a new post then?

**Comment by MrPetovan** [comment]
It should appear directly in the preview of the post if the node enabled the Twitter connector and updated their addons to the latest `develop` which is easy to forget. Paging @AlfredSK

**Comment by AlfredSK** [comment]
The Twitter connector works and everything is up to date. But still, there is no preview created in the post modal. Just that "enter title" line...

![image](https://user-images.githubusercontent.com/3656054/98170190-d97f1980-1eed-11eb-9e7a-2641367d3a5a.png)

**Comment by MrPetovan** [comment]
Thanks, I just remembered you also need to reload the active addons to register the new hooks.

**Comment by AlfredSK** [comment]
Already did that twice. Can do it again...

**Comment by AlfredSK** [comment]
Nope. No change.

**Comment by MrPetovan** [comment]
Can you please try the following:
- Use a different Twitter URL (results are cached by URL).
- If it still doesn't work, disable/enable the Twitter connector. The configuration (node/users) will not be deleted in the process.
- Try with another different Twitter URL.

**Comment by AlfredSK** [comment]
Tried another random Twitter URL. 
Didn't work.
Disabled twitter addon.
Enabled Twitter addon.
Tried yet another Twitter URL.
Works.

**Comment by haheute** [comment]
Yes, now it shows a preview with photo and description when under "Message" tab. Under "Preview" tab there is no photo, as well as in the final post. There seems to be no photo, too. 
tried here: https://libranet.de/display/0b6b25a8-205f-a333-a538-5c3015636237

**Comment by MrPetovan** [comment]
Interesting, I can look into it more, thank you for the feedback.
