### ISSUE TITLE
Timeline sort order with login has changed

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9451]
In 2020.12-dev the sort order of your timeline has changed from "Latest Posts" to "Latest Activity" when you log in , or when you switch accounts.
![00_temp00](https://user-images.githubusercontent.com/24474762/97077575-4688da00-15e5-11eb-8a52-c68381026d08.jpg)

This is very confusing and we shouldn't change standard behavior like that without a possibility to configure it.

1. Please change it back to standard behavior "Latest Posts"
2. If there is a need to set another sort order as login default, pls make it configurable.

**Comment by foss-** [comment]
`Latest Activity` is what users are familiar with coming from Twitter. Changes might be confusing, but I would not consider them a bug if they are for the better. Not sure I understand the argument about "standard behavior". Defaults are standard behavior. The default was changed so there is no point in arguing to switch back to "correct" standard behavior.

I agree though this should be easy to change for users preferring a different timeline sort. Tried clicking on `Latest Posts` logged out and back in and sorting was back to `Latest Activity`. I don't think a setting is needed, but user choice should be remembered. Is that possible?

**Comment by annando** [comment]
It's a changed behaviour, but not a bug. The last tab on the network page changed from being stored in a config field to a session variable. Previously this created some problems when working with several devices in parallel, since switching the tab on the one machine crippled the update mechanism on the other machine.

However, it should be possible to use that config field when no session value had been stored.

**Comment by MrPetovan** [comment]
The data format of the previous config variable and the new session variable aren't directly compatible so we can't easily offer backward compatibility. However it is just a one-time change.

**Comment by hoergen** [comment]
Maybe you don't confuse those many "twitter users coming to friendica", but all existing friendica users. If you like to change the behavior, you should consider the following topics

1.  Did you weight about confusing friendica or twitter users. Where is your focus? :)
2. If you change the behavior, then don't change it for existing accounts! Nobody likes when a software switches to a completely different behavior, you can't fix, because it is "hardcoded" (or a bug).
3. If you like to have a twitter alike feeling, then you should change the complete layout with "latest activity" to a comment based stream and not to a post based stream. THEN it is not confusing Twitter users.

Now you are confusing twitter and friendica users. And I don't think this is the intention ;)

**Comment by hoergen** [comment]
Just for information what happened in the other issue: 
Friendica stores your selection, so it won't automatically switches it's behavior again. Thanks a lot :+1:
