### ISSUE TITLE
I accidentally deleted the admin

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#9459]
I accidentally deleted the admin.
Is there a way to restore it to the database?

**Comment by AlfredSK** [comment]
You can promote any user to be an admin by adding their mail address to your local.config.php file.

**Comment by ghost** [comment]
Found it out, you change the following field of the table "user" from 1 to 0
![mail zsemberi de _ localhost _ meld _ user _ phpMyAdmin 4 9 5-mail zsemberi de](https://user-images.githubusercontent.com/12480023/97118095-74b30a80-1708-11eb-9ddd-92b66033c469.png)
