### ISSUE TITLE
Twitter list or G+ Circles

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9463]
I know you guys are working hard on post filtering so this may be redundant and just merge it with other requests if so.  Basically I would like a twitter style list or G+style circles so I can only see posts from select people I want to look at.  Probably already in the works, just figured I'd add my vote to it, or bring it up just in case it hadn't been thought of

**Comment by AlfredSK** [comment]
That's what contact groups are (also) for. Sort your contacts into groups. Select that group in the widget on network page. Voilà. A stream of posts of the members of that group.

**Comment by anubis2814** [comment]
Ok, wow, that wasn't very intuitive at all but very very cool.  Thanks!

**Comment by AlfredSK** [comment]
I usually sort new contacts into groups right when I follow them or accept their follow request. During the follow workflow you are on the contact's page anyway. On that page (left side widget panel) you can select the groups for that contact right at the beginning. So you can save the effort to sort the contacts into groups later.

**Comment by anubis2814** [comment]
Yeah i see it now, and will be doing it, just one of many great but hidden features to newer users
