### ISSUE TITLE
Mastodon's custom emojis don't show anymore

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9465]
Mastodon's custom emojis used to be shown in individual posts. They didn't in display names and profile description because the emojis weren't shipped with the profile information like they used to be with the posts. Did anything change in Mastodon's AP post structure?

Do we have to store the custom emojis per remote server for posts as we needed to do anyway for display names/profile description?

**Comment by annando** [comment]
The emojis are stored by server. So they don't work in posts anymore?

**Comment by MrPetovan** [comment]
I'm not aware of a per server storage, I thought about adding this feature to convert display names but I didn't get to do it. I thought each post included the custom emojis of the server and that's why each post could be rendered properly.

**Comment by annando** [comment]
@MrPetovan isn't thid fixed now?

**Comment by AlfredSK** [comment]
Looks like it is working...
https://libranet.de/display/52acf9cd-af74796387679b4a-e0bfadd1

**Comment by MrPetovan** [comment]
Duplicate of #9525, fixed by #9526
