### ISSUE TITLE
Sort order of /network is not your last choosing

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9467]
### Bug Description
If you click on the network timeline icon, so you jump to `/network` you get very old entries displayed on the top of your timeline (maybe activity sorted?)

When you then click on "latest posts" the sort order is again  `/network?order=received` -> correct.

### Goal
If you click on the network icon it should reflect your last configuration / choosing

### Platform Info
- Friendica Version: 2020.12-DEV
- Friendica Source: GIT
- PHP version: 7.3
- SQL version: MariaDB latest

**Comment by MrPetovan** [comment]
Duplicate of #9457, see last comments.
