### ISSUE TITLE
Site works, but command line tools complain about database setup

### ISSUE THREAD

**Issue by triantos** [friendica/friendica#9469]
I just setup Friendica on a new clean Ubuntu system. The site is mostly working well, but none of the command line tools work. I tried, for example, to run: `$ php bin/console.php maintenance 0` but I get the error `[Error] Database isn't ready or populated yet`. My cron job is also failing to run for the same reason. I do have the database variables set in my local.config.php file, and when I look at `php bin/console.php config` they do show up as I'd expect. From the command line, my www user is able to use those settings to manually talk to mysql. Do I also need some environment variable(s) to tell the command line tools to read that config? my site is using php via fpm for Apache2, whereas the command line tools are using php for cli, of course.

I checked the wiki and all over the internet and didn't find any suitable answers. thank you!

**Comment by MrPetovan** [comment]
Sorry to hear that, can you please activate your Friendica debug log in the Admin section, left-hand sidebar, "Logs". Please set the level "Info" and a log file path relative to the install folder than can be written by both the web server user, and whatever user you're logged as in the CLI.

Then run a CLI command again and check the log afterwards.

**Comment by triantos** [comment]
Thank you very much for such a fast response! The log you requested is below.

[friendica.log](https://github.com/friendica/friendica/files/5462873/friendica.log)

I don't yet fully understand how the federation works, but I was surprised to see all of these connections to the outside world, and all of those invalid sessions trying to fetch from /friendica. This server is a test server with exactly two people having accounts on it now, and neither of us are doing anything to hammer it like this. [edit: I think this is my server discovering federated servers, which is cool, but is crushing the machine. I'll go try to learn whether I have control over this. My queue of worker jobs is growing pretty rapidly since cron can't run.]

edit: I should also mention that it's possible I setup the database incorrectly. What I did was to just load database.sql into mariadb from the command line. That seems to be what the instructions told me to do but since I'm having a possible db issue I thought I'd mention it.

thanks again!

**Comment by MrPetovan** [comment]
The log doesn't show anything from your command line input, so it may be something else. Please try `$ php bin/console.php dbstructure dryrun` to see if the structure is correct. It shouldn't output any SQL queries in this case. If it does, please run `$ php bin/console.php dbstructure update` afterwards.

**Comment by triantos** [comment]
Unfortunately that command doesn't run, and throws the same `[Error] Unable to connect to database`

**Comment by triantos** [comment]
I'm going to start going through the code to figure out exactly what's throwing the error but any pointers would be welcome since I'm completely unfamiliar with the internals.

**Comment by annando** [comment]
When the site itself works but the command line doesn't, then possibly your PHP-CLI doesn't contain all needed modules, like for example the PDO module. Can you check that?

**Comment by triantos** [comment]
yep that appears to be it! Brilliant, and what a silly thing I overlooked. I checked phpinfo through apache but not from the cmd line. Thanks! I'll confirm that fixes this issue and then close it or come back with more q's.

**Comment by triantos** [comment]
Awesome! that was indeed it. Thank you to both of you for the quick help!

**Comment by MrPetovan** [comment]
Oooh, nice catch.

**Comment by annando** [comment]
We should enable an install check for the modules that are available for the worker and the command line.
