### ISSUE TITLE
Posting to community support site

### ISSUE THREAD

**Issue by triantos** [friendica/friendica#9470]
Hi, I'm very new to Friendica, and I'm not much of a twitter/FB guy, so maybe this is obvious to people who've used those other social sites.

I'm trying to figure out how to post these types of questions to the community support forum. The little bit of info I see makes me think I should be posting to my wall, and including "!helpers@forum.friendi.ca" at the top of the post. Is that correct? I'm not really sure what magic is supposed to route that to that forum, but as I look at the forum's public view, I don't see my post anywhere there. It would be great to include a FAQ item or some explicit help page about exactly how to post to that group, for newbies like me. Once I learn how to do so I'm happy to write it up, if that's of help.

thank you!

**Comment by MrPetovan** [comment]
Hi @triantos , have you tried following the forum account first before posting to it? You can enter this URL: `https://forum.friendi.ca/profile/helpers` or the WebFinger address `helpers@forum.friendi.ca` in the "Add New Contact" form in the sidebar of the Contacts page.

**Comment by triantos** [comment]
Thank you! That was the piece I was missing. I appreciate your quick help!
