### ISSUE TITLE
High load and lots of activity on what should be an idle server

### ISSUE THREAD

**Issue by triantos** [friendica/friendica#9473]
- [X] I have searched open and closed issues for duplicates

### Bug Description

On a fresh install of 'stable' to a new ubuntu box, I am seeing surprisingly high loads and lots more traffic into my site than I would have otherwise expected. The machine has only been online for 2 days. Is it possible that new machines have to be crawled by other federated nodes? I can't think of why else I'd have over 5000 hits to my site when I haven't announced it to anyone and for now, it's just one other friend and I testing out friendica.

### Steps to Reproduce

1.  install the 'stable' branch to a clean system
2.  within 12 hours, start watching the web traffic come rolling in
3.  The vast majority of the traffic is HTTPS reads of /friendica. I'm guessing this is other servers trying to discover mine. From looking at the Admin -> Federation Statistics page, my machine has discovered only 42 Friendica systems plus 15 Diasopra machines, so that shouldn't account for all of this inbound traffic to me.

**Actual Result:**

I am seeing loads of > 6 most of the time. This is in a reasonably powerful container I instantiated on a very powerful server. Most of my other containers that are similarly spec'd for other applications do not have trouble running within the memory/CPU limits I've given to this machine. Most of the time I'm now unable to access my machine through my browser since the server is so busy.

**Expected Result:**

I would expect the machine to be roughly idle, other than the cron job running every 10 minutes

### Screenshots

Not appropriate, really, though I can share data from my apache logs or other files if needed.

### Platform Info

Friendica Version:
Friendica 'Red Hot Poker' 2020.09-1-1369

Friendica Source: ??

PHP version: 7.4.3

SQL version: mariadb  Ver 15.1 Distrib 10.3.25-MariaDB

**Comment by annando** [comment]
This had been fixed with this PR: https://github.com/friendica/friendica/pull/9336

If possible, I would suggest using the "develop" branch.

**Comment by triantos** [comment]
I checked out the develop branch, ran `php bin/console.php dbstructure update` (which changed one index), but now my server displays a blank page after I login. Is there some other magic step I'm missing?

**Comment by MrPetovan** [comment]
Please check your web server log for PHP Fatal Errors.

**Comment by triantos** [comment]
Is there some additional setting I need to add to my local.config.php or somewhere in the database to explicitly set my preferred language (to English)?

`[Fri Oct 30 14:45:21.350814 2020] [php7:notice] [pid 822] [client 192.168.1.13:42362] PHP Fatal error:  Uncaught Error: Class 'LanguageDetection\\Language' not found in /var/www/friendica/src/Model/Item.php:2477\nStack trace:\n#0 /var/www/friendica/src/Model/Item.php(1704): Friendica\\Model\\Item::getLanguage()\n#1 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(573): Friendica\\Model\\Item::insert()\n#2 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(496): Friendica\\Protocol\\ActivityPub\\Processor::postItem()\n#3 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(782): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity()\n#4 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(214): Friendica\\Protocol\\ActivityPub\\Processor::fetchMissingActivity()\n#5 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(495): Friendica\\Protocol\\ActivityPub\\Processor::createItem()\n#6 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(782): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity()\n#7 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(214): Friendica\\Protocol\\ActivityPub\\ in /var/www/friendica/src/Model/Item.php on line 2477`

**Comment by triantos** [comment]
I should mention that my current local.config.php sets language to 'en'.

`        'system' => [
                'default_timezone' => 'America/Los_Angeles',
                'language' => 'en',
        ],`

**Comment by annando** [comment]
Please update the vendor folder with `php bin/composer.phar install --no-dev`

**Comment by triantos** [comment]
I am rapidly falling in love with your quick response times! That did it, thank you very much!
