### ISSUE TITLE
Never auto-mention yourself

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9480]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When I reply to an own (post or)* comment Friendica adds on odd auto-mention of myself. That's weird and uncommon.
That's especially bad when using implicit mentions where you're unable to delete the weird self-mention before submitting the comment.

*) I think it doesn't happen with replies to top level posts. But I'm not sure.

### Steps to Reproduce

1.  Look for a comment of yourself
2.  Reply to that comment
3.  When using implicit mentions you need to look at your comment from another network. When using explicit mentions you will see it right away locally on Friendica.
4. You have mentioned yourself. See?

Actual Result:
Automatic self-mentions are weird, wrong and useless.

Expected Result:
Never ever auto-mention yourself. I can't come up with a situation where they are useful or meaningful. We should prevent/suppress these self-mentions - no matter if the mentions are explicit or implicit.

### Screenshots
(don't want to shoot my screen. it's a good screen)

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git
PHP version:
7.4
SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
Mastodon users are expecting posts to contain self-mentions on threads, so that's why we keep track of them.

**Comment by tobiasd** [comment]
I agree with @AlfredSK outside of test thread I usually don't talk with myself... regardless of it being the social norm of not.

**Comment by MrPetovan** [comment]
Let's be clear, both of you want us to change something in Friendica because you don't like the expected display in other social network software? So this change wouldn't be visible for Friendica users for which the display would stay the same (with no visible self-mention), but the other social network software users would have a counter-intuitive experience with posts coming from Friendica, even though they didn't complain about the presence of the self-mention, while they did in fact complain about the absence of mentions in posts from Friendica, which is the reason why we implemented the implicit/explicit mentions feature.

Did I summarize the problem correctly?

**Comment by tobiasd** [comment]
They did complain about a missing self-mention??? ok, no keep it in, I'll just need to cut the connection to that platform then.

**Comment by AlfredSK** [comment]
> Did I summarize the problem correctly?

Sarcasm aside, no you don't.

I think the issue is that Mastodon needs the mentions for threads and notifications. I can't remember this has anything to do with mentioning yourself all the time. 
I just checked it with Mastodon. There is NO visible self-mention when I reply to an own item - not on Mastodon itself, not on our side.
I checked Misskey. There is NO visible self-mention when I reply to an own item - not on Misskey itself, not on our side.
I checked Pleroma. There is NO visible self-mention when I reply to an own item - not on Pleroma itself, not on our side.

Only we are adding these self-mentions visibly to the BODY of the post.

**Comment by MrPetovan** [comment]
> They did complain about a missing self-mention??? ok, no keep it in, I'll just need to cut the connection to that platform then.

Not specifically, about missing mentions altogether.

**Comment by MrPetovan** [comment]
> I just checked it with Mastodon. There is NO visible self-mention when I reply to an own item - not on Mastodon itself, not on our side.
> I checked Misskey. There is NO visible self-mention when I reply to an own item - not on Misskey itself, not on our side.
> I checked Pleroma. There is NO visible self-mention when I reply to an own item - not on Pleroma itself, not on our side.
> 
> Only we are adding these self-mentions visibly to the BODY of the post.

Ah, I see what you mean, I didn't realize self-mentions didn't appear on these platforms. I believe they used to, as on Twitter, but I haven't checked for that specifically. Sorry for the sarcasm.

We can probably add a check for it, as we already don't allow people to self-mention themselves in the post form, but I'm not sure of the technical implications of not allowing self-mentions at all.
