### ISSUE TITLE
Underscores in user mention triggers italics 

### ISSUE THREAD

**Issue by norz** [friendica/friendica#9486]
- [X] I have searched open and closed issues for duplicates

### Bug Description

The mention of a username with two _ in it (ex: `_user_`) is interpreted as _italics_ and the mention is ineffective machine wise.  

**NB: this might be due to the ~ “parse as markdown” setting. I’ll try without it later.** 

### Steps to Reproduce

1.  Find such user
2.  Reply with a comment 
3.  Post comment

Actual Result:

Italics instead of mention:
`@[i]user[/i]@framasphere.org `

Expected Result:

`@_user_@framasphere.org`

### Screenshots

Example : 
https://libranet.de/display/0b6b25a8-925f-9fd9-1d5b-1d6026315166

### Platform Info

Friendica Version:

2020.12-dev that is running at the web location https://libranet.de. The database version is 1372/1372, the post update version is 1349/1350.

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
Yep, this is an unfortunate interaction with the Markdown addon. We should exclude mentions from this parsing.

**Comment by norz** [comment]
Merci Hypolite! 🙏 

I just tested with “ Enable Markdown parsing ” disabled, and it works. 👍 
https://libranet.de/settings/addon
(I had forgotten about enabling this add on.)

I guess I’ll keep it disabled as long as I exchange messages with this _user_. 😉 
And I’ll do the markdown parsing elsewhere if needed. 

(Very minor issue, but even if prioritised as “won’t fix” this ticket might help someone in the future.)

**Comment by annando** [comment]
I don't think that it is a minor issue. I would like to have it fixed for this release.

**Comment by MrPetovan** [comment]
I'll take it up since it involves regular expressions.

**Comment by norz** [comment]
Merci! 🙏
