### ISSUE TITLE
Friendica\Model\PermissionSet record uninitialized

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9491]
- [ ] I have searched open and closed issues for duplicates

### Bug Description
Calling certain /display pages gives internal server error. Reported items are...

Example 1:
https://libranet.de/display/c1ffbd23-6f61af2669026404-9157d9d8

Example 2:
https://libranet.de/display/ee9e5ac6-6f6faab01f08af3d-42f4255b

Unfortunately there is nothing in PHP error log.

Edit:
**Only happens for authenticated (logged in) users. In a "private" browsing window (logged out) the pages are working w/o error!**

This is what a user gets when calling the first example URL:
```
Friendica\Model\PermissionSet record uninitialized

#0 /var/www/html/libranet/src/BaseModel.php(119): Friendica\BaseModel->checkValid()
#1 [internal function]: Friendica\BaseModel->__get()
#2 /var/www/html/libranet/src/BaseCollection.php(91): array_column()
#3 /var/www/html/libranet/src/Model/PermissionSet.php(76): Friendica\BaseCollection->column()
#4 /var/www/html/libranet/src/Model/Item.php(3457): Friendica\Model\PermissionSet::get()
#5 /var/www/html/libranet/mod/display.php(300): Friendica\Model\Item::getPermissionsSQLByUserId()
#6 /var/www/html/libranet/src/LegacyModule.php(90): display_content()
#7 /var/www/html/libranet/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction()
#8 [internal function]: Friendica\LegacyModule::content()
#9 /var/www/html/libranet/src/App/Page.php(331): call_user_func()
#10 /var/www/html/libranet/src/App/Page.php(387): Friendica\App\Page->initContent()
#11 /var/www/html/libranet/src/App.php(559): Friendica\App\Page->run()
#12 /var/www/html/libranet/index.php(42): Friendica\App->runFrontend()
#13 {main}
```

Reported problem discussed here:
https://libranet.de/display/0b6b25a8-125f-a1de-8ca1-c8e510002371

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.3

**Comment by AlfredSK** [comment]
Weird. When I'm **not logged in** the links are working as expected!

**Comment by utzer** [comment]
I tried to search for some [Diaspora link](https://sechat.org/posts/97030fd000be01399ee3002590d8e506) and got the same result I think. 

```
#0 /var/www/src/BaseModel.php(119): Friendica\BaseModel->checkValid()
#1 [internal function]: Friendica\BaseModel->__get()
#2 /var/www/src/BaseCollection.php(91): array_column()
#3 /var/www/src/Model/PermissionSet.php(76): Friendica\BaseCollection->column()
#4 /var/www/src/Model/Item.php(3457): Friendica\Model\PermissionSet::get()
#5 /var/www/mod/display.php(300): Friendica\Model\Item::getPermissionsSQLByUserId()
#6 /var/www/src/LegacyModule.php(90): display_content()
#7 /var/www/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction()
#8 [internal function]: Friendica\LegacyModule::content()
#9 /var/www/src/App/Page.php(331): call_user_func()
#10 /var/www/src/App/Page.php(387): Friendica\App\Page->initContent()
#11 /var/www/src/App.php(559): Friendica\App\Page->run()
#12 /var/www/index.php(42): Friendica\App->runFrontend()
#13 {main}
```

I did a search today, some time during the afternoon, for some squeet.me URL (Friendica) which did not result in this fault. 

I just realized it shows the profile pic of the remote user whose post I searched for.

**Comment by haheute** [comment]
I just wanted to display a [post](https://libranet.de/display/39a36370013701399570005056264835) from a diaspora user and got `Interner Serverfehler
Friendica\Model\PermissionSet record uninitialized`, too. Works in incognito window.

**Comment by utzer** [comment]
> I just wanted to display a [post](https://libranet.de/display/39a36370013701399570005056264835) from a diaspora user and got `Interner Serverfehler Friendica\Model\PermissionSet record uninitialized`, too. Works in incognito window.

I had this too yesterday, clicked on the time+date link and got the fault.

**Comment by annando** [comment]
This is deep in the whole class structure. Pinging @nupplaphil and @MrPetovan for help.

**Comment by MrPetovan** [comment]
I started to look into it yesterday but I was unable to even import the mentioned posts on my dev instance and it was 1:30 AM so I went to bed instead, I'll resume my investigation today.

**Comment by annando** [comment]
Thanks! I guess that it isn't specific to that post, but to the permissions. In one of my recent changes I improved the detection of the remote contact id so that it started to work at more places.

**Comment by MrPetovan** [comment]
Can you both look into your `permissionset` table for a row with an empty or 0 id?

**Comment by annando** [comment]
There should be one:
```
MariaDB [piratica]> select * from permissionset where id=0;
+----+-----+-----------+-----------+----------+----------+
| id | uid | allow_cid | allow_gid | deny_cid | deny_gid |
+----+-----+-----------+-----------+----------+----------+
|  0 |   0 |           |           |          |          |
+----+-----+-----------+-----------+----------+----------+
1 row in set (0.00 sec)
```

**Comment by annando** [comment]
I have the feeling as if the check in `checkValid()` mistakenly thinks that `0` is unitialized.

**Comment by MrPetovan** [comment]
Ok, so that's why, I didn't expect models to have an id equal 0, so I used `empty()` to check its value.

**Comment by annando** [comment]
We need `0` values like these to make the foreign keys working.

**Comment by utzer** [comment]
> There should be one:
> 
> ```
> MariaDB [piratica]> select * from permissionset where id=0;
> +----+-----+-----------+-----------+----------+----------+
> | id | uid | allow_cid | allow_gid | deny_cid | deny_gid |
> +----+-----+-----------+-----------+----------+----------+
> |  0 |   0 |           |           |          |          |
> +----+-----+-----------+-----------+----------+----------+
> 1 row in set (0.00 sec)
> ```

same here, but it is already solved, at least understood why it happens. Thanks again for the quick help!
