### ISSUE TITLE
Users list in /admin/users has broken sorting + pagination, impossible to hit page 2 of non-default sort

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#9496]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I recently wanted to look up a user in the web UI by email address.  I sorted the list by Email and then needed to go to page 2, but the sort reverts to default when trying to go to another page, making it impossible to get to another page's worth of users sorted by email address.

### Steps to Reproduce

Use the frio theme
Go to /admin/users
Change the sorting of the users to something you like/need
Go to page 2, see that the results are based on the default sort (Name)

Friendica Version: 2020.09-1 - 1369

Friendica Source: git

PHP version: 7.4.11

SQL version: MariaDB 10.3.23

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by MrPetovan** [comment]
I've never had enough users to hit the page size, but oh lord the pagination on this page is awful on frio.

**Comment by realkinetix** [comment]
Heh, I should have posted bugs about it earlier!

**Comment by MrPetovan** [comment]
I'm now in the process of separating this page in five distinct pages, it's going to look less crowded and the pagination will work.

**Comment by MrPetovan** [comment]
I have a good one for @annando : In the users admin page, blocking a user sets `user.blocked` to 1, but when we retrieve the list of blocked users, we look in `owner-view` where the `blocked` field is provided by `contact.blocked` which isn't set while blocking users. 

So which one is it? Are we currently relying on `owner-view.blocked` for user blocks?

**Comment by annando** [comment]
I guess this is an error in the view. But before changing the view we have to check where `blocked` is currently used. Possibly we could also fill both fields in parallel.

**Comment by AlfredSK** [comment]
Here is the issue about the blocked users on admin/users:

https://github.com/friendica/friendica/issues/9326

Would be great when this is addressed as well.

**Comment by MrPetovan** [comment]
> I guess this is an error in the view. But before changing the view we have to check where `blocked` is currently used. Possibly we could also fill both fields in parallel.

I've been going through all the reference to the multiple `blocked` fields and so far all the usages of `owner-view.blocked` I've found assume it's the user's.

It sounds like the simplest would be to switch the field from `contact.blocked` to `user.blocked` since we don't use the `blocked` field with public contact records. For local users blocking public contacts, we have the `user-contact` table.

It should solve a host of inconsistent behaviors that haven't been reported so far. Like for example blocking a user from the admin prevents to display their photos (by checking `user.blocked`), but not their videos (by checking `owner-view.blocked`).

**Comment by MrPetovan** [comment]
How do I update my view locally? I've updated the `static/dbview.config.php` and ran `bin/console dbstructure update -f` but nothing changed.

**Comment by annando** [comment]
The way you did it is the correct way. How have you checked if it worked? Have you directly looked  at the query in the MySQL console?

**Comment by MrPetovan** [comment]
There are two things I did in the meantime:
- I updated the version number in `static/dbstructure.config.php` and ran the updater again.
- I refreshed the views in my IDE database browser.

I'm not sure which one actually made the change visible, I don't remember if I tested the faulty page in the mean time.

Anyway, it's good now, and I'm polishing the new pages.
