### ISSUE TITLE
Exchange contact.url and contact.alias for Mastodon contacts

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9508]
See https://discourse.joinmastodon.org/t/solved-whats-the-interoperable-mention-format/3069

Mastodon's logged in view treats HTML links whose URL is featured in the message mentions differently. Unfortunately, Mastodon rewrites the mentioned profile URLs from `https://domain.tld/users/username` to `https://domain.tld/@username` which doesn't match the link URL in the body anymore and the mentions links are treated like vulgar external links.

To enable the expected mention link behavior from Friendica messages including a Mastodon profile mention, we would need to start using the `https://domain.tld/@username` in the `contact.url` field and `https://domain.tld/users/username` in the `contact.alias` field, which is the exact opposite of what we've been doing so far.

Is there a way to do this, even if it is little by little with each new contact probe?

**Comment by annando** [comment]
Whatever we do, we should never do some `if mastodon then ...`.

**Comment by MrPetovan** [comment]
I've had an explanation of the discrepancy between both format. `https://domain.tld/users/username` is considered the unique profile `id`, while `https://domain.tld/@username` is considered as the URL to access to profile page. So Mastodon uses the `url` in the body mention link URL, but uses the `id` in the mention `tag` array. This `id` is then converted to the profile `url` to enhance the display of the mention links.

I'm thinking we could store the AP profile `url` in `contact.url` and the `id` in `contact.alias`. Then we use `contact.url` in the body mention links and `contact.alias ?: contact.url` in the `tag` array.

**Comment by annando** [comment]
I don't think that we need to change anything in how we store the `alias` and the `url` in the `contact` table. The `alias` already contains the correct value, the `url` value is used for the whole communication part.

**Comment by MrPetovan** [comment]
What do you mean by "correct" value?

**Comment by annando** [comment]
The `alias` should already contain the profile link with this `@` in it and could be used for the whole "visual" stuff. The value in `url` however is used for the technical part, means the address fields in the protocol.

**Comment by MrPetovan** [comment]
So body mentions should be using the `contact.alias` value if it exists, I'll try that.
