### ISSUE TITLE
[frio] Unable to sort users in admin panel by 'registration date', 'last login', 'last public item'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9518]
- [X] I have searched open and closed issues for duplicates

### Bug Description
After the latest changes to the node's user list at .../admin/users I cannot sort the user list by 'registration date', 'last login' and 'last public item' anymore. It worked with some weird issues. Then I refreshed my browser cache. But now it doesn't work at all. I'm using Frio.

### Steps to Reproduce

1.  go to .../admin/users (no matter if you chose 'All' or 'Active' tab)
2.  refresh your browser cache or empty that cache
2.  open the details of a user with that little triangle
3.  try to change the order by clicking on 'registration date', 'last login', 'last public item'

Step 2 is important. It somehow (partly) works until you refresh your cache. Then it fails.

Actual Result:
Nothing happens.

Expected Result:
User list should be sorted by 'registration date', 'last login', 'last public item'.

### Browser
Chromium 86
Firefox 82

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
I didn't check these hidden sort fields, thank you for your testing.

**Comment by MrPetovan** [comment]
Caused by #9501

**Comment by AlfredSK** [comment]
Works again. 🎉 Thank you!
