### ISSUE TITLE
Link regex only recognizes http[s] links

### ISSUE THREAD

**Issue by navigium** [friendica/friendica#952]
Although it's seldom used, I think it should be possible to post gopher:// or ftp:// links in Friendica. Probably it's just a matter of adjusting the regex. (though I really didn't do any PHP in ages. So I can't do it myself.)

**Comment by silke** [comment]
Yes, would be nice, but I'm removing it from the 3.4 milestone. (Which of course doesn't mean I want to keep anyone from working on it.)

**Comment by tobiasd** [comment]
gopher links are supported now since #1803 ftp and mailto are now supported as well. so I'm closing this issue.
