### ISSUE TITLE
frio: timeline not updating / refreshed when a post is liked or commented on

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9533]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When clicking like / dislike on a post, frequently the UI is not refreshed correctly. The spinner keeps spinning and never goes away. The like is recognized, but the timeline UI is never updated automatically so the info who liked that post is not updated.

A similar problem happens when commenting on a post. The comment is sent, but the timeline is not updated automatically so it appears as if the comment was never sent. On a manual refresh the comment then is shown.

Actual Result:

Like or comment not shown in timeline UI after being clicked / sent.

Expected Result:

Timeline UI should automatically refresh or be updated showing the like / comment.

Additional Info:

This is frio specific. Testing in Vier, liking and commenting on a post both resulted in the UI automatically refreshing / showing the like / comment.

### Platform Info

Friendica Version: 

This is Friendica, version 2020.12-dev that is running at the web location https://pirati.ca. The database version is 1373/1373, the post update version is 1349/1362.

**Comment by MrPetovan** [comment]
This behavior isn't consistent, I've been able to see updated display after likes and comments. If it was failing all the time, it would be easier to troubleshoot but as it stands it's pretty much a mystery to me, and I already spent quite some time trying to make this behavior more consistent.

**Comment by foss-** [comment]
You are correct. I should have mentioned this is inconsistent behavior and not always reproducible. But it happens fairly frequently here. Not sure if I can claim unexpected outweighs expected occurrences, but feels so.

**Comment by MrPetovan** [comment]
I'm with you there, I still tried to minimize the inconvenience of this inconsistent behavior, like prevent removing a like that was added but not displayed. Now clicking again an inactive like link on a post you already liked will just be ignored instead of toggling the like off.

**Comment by annando** [comment]
Weird thing is that being on the same machine I cannot reproduce it for myself.

**Comment by foss-** [comment]
There have been so many changes, fixes and improvements and I have not seen the problematic behavior in a while.

Case closed and thanks for all the work that went into improving post interaction.
