### ISSUE TITLE
Huge amounts of admin notification mails for dbstructure updates

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9561]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When a database structure update is applied the admin can get tons of notification mails about it. The last time I got 650 (!) notification mails about the successful dbstructure update. I just applied the db update 1378 on a mid size node and got 114 mails about it.

The larger the node (database size) the more mails are created and send to the admin's mail box. Small node: around 20 mails, mid size node: around 120 mails, large node: 300-650 mails.

At first I thought it could be related to the phpmailer add-on. But I also received 10 mails when I updated the Friendica Community Forum node where phpmailer isn't used and the mail server is running on the same machine. 

### Actual Result:
Tons of notification mails for database structure updates.

### Expected Result:
One notification mail about the database structure update.

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by annando** [comment]
@AlfredSK do consider this fixed?

**Comment by AlfredSK** [comment]
Hmm. I got a reasonable amount of mails for the last dbstructure update. But I'm not sure. The larger/longer the update the more mails I got in the past. 

I cannot remember it was really bad since your PR has been merged. So I think we can close this issue.

**Comment by MrPetovan** [comment]
Still getting multiple emails as well, but the last long update of the photo table "only" generated a couple.
