### ISSUE TITLE
Twitter: No resharer marker anymore

### ISSUE THREAD

**Issue by annando** [friendica/friendica#9562]
Using the current develop branch the "xyz reshared this" text seems to be missing with posts that arrive from Twitter. For example the following post is not from one of my followers:
![Bildschirmfoto vom 2020-11-20 23-27-19](https://user-images.githubusercontent.com/844208/99855920-2dddf680-2b88-11eb-9588-b44c4d33c12a.png)
And on my Tweetdeck you can see that it had been reshared:
![Bildschirmfoto vom 2020-11-20 23-32-35](https://user-images.githubusercontent.com/844208/99856197-bbb9e180-2b88-11eb-9e24-eacae007e4c7.png)

**Comment by MrPetovan** [comment]
I'm fuzzy on how this is supposed to appear so I'm not sure I'll be able to fix it on my own.

**Comment by annando** [comment]
Since it is still working with AP, it must be related with the latest changes in the addon. (Somewhere in the last days, most likely before the last change)

**Comment by MrPetovan** [comment]
Yes, but since I do not know how it works, I cannot guess what change broke it.
