### ISSUE TITLE
Showmore Dynamic broken on Vier

### ISSUE THREAD

**Issue by pixelsalad** [friendica/friendica#9568]
The “show more” display of theme Vier is broken. It appears somewhat randomly in the stream either horizontally or vertically.

**Comment by AlfredSK** [comment]
Thank you for submitting the issue.

Can you please use the issue template when creating a new issue? It is very helpful to get more information about the details of the problem, the expected behavior and in case of UI problems one or two screenshots would make it easier to understand the issue.

For example there are two 'show more' add-ons - 'showmore' and 'showmore dynamic'. I guess the problem is the latter one but nobody knows by just reading your short description.

**Comment by pixelsalad** [comment]
Screenshots for clarification:

![Screenshot_20201121_163256](https://user-images.githubusercontent.com/46964467/99881222-c328cb80-2c18-11eb-92b4-7a3cd77a8ee6.png)
![Screenshot_20201121_163343](https://user-images.githubusercontent.com/46964467/99881225-c4f28f00-2c18-11eb-8822-eb8b71412d01.png)
![Screenshot_20201121_163546](https://user-images.githubusercontent.com/46964467/99881226-c623bc00-2c18-11eb-830e-ddb1e746e02b.png)

**Comment by AlfredSK** [comment]
Ah! Yep. Looks like 'showmore dynamic' add-on. Thank you!

**Comment by AlfredSK** [comment]
Until this is fixed you can disable it in your user settings -> addons -> showmore dynamic.

**Comment by pixelsalad** [comment]
I unchecked the box you can see there. And.... no change.
Showmore dynamic requires a number to be set.
![Screenshot_20201121_180037](https://user-images.githubusercontent.com/46964467/99882864-b5c50e80-2c23-11eb-994e-25ac14dc32ee.png)

**Comment by MrPetovan** [comment]
You can enter an extraordinarily large number and it will de facto disable the addon.

**Comment by AlfredSK** [comment]
Oh. I didn't know there is no disable option for showmore dynamic (I don't use it).
What you actually see there are two separate add-ons. The one at the top just cuts too long text (longer than the shown number) and adds a link to show the full text. The one at the bottom is the showmore dynamic add-on. You can try to set a very high number like 2000 to prevent it from collapsing posts.

**Comment by pixelsalad** [comment]
I set the showmore dynamic max height to 3000 and now the stream looks good again. :sunglasses:

**Comment by annando** [comment]
We really have to improve that addon. It needs an option to deactivate it and it needs this inflating/deflating behaviour like the other addons.
