### ISSUE TITLE
PHPMailer add-on: Character encoding broken in notification mails

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9572]
- [X] I have searched open and closed issues for duplicates

### Bug Description
All unicode characters in notification mails are broken. When the user or admin receives notification mails unicode emojis or cyrillic or asian characters are broken. They're shown as weird placeholder or special ascii characters. This problem appeared in the last days/weeks. It was working correctly before. I checked it with different mail clients. It's the same issue with all of them. So, this must be a Friendica bug.

### Steps to Reproduce

1.  Receive notification mails with utf-8/unicode characters
2.  Look at the mails with different clients :-)

Actual Result:
You will see stuff like `Steffen K9 ð°` or `registration request from 'ÐÐ¼Ð¸ÑÑÐ¸Ð¹ ÐÐ¼Ð¸ÑÑÐ¸ÐµÐ²Ð¸Ñ' at venera.social ð.`

Expected Result:
Correctly handle unicode characters in notification mails.

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.3

**Comment by AlfredSK** [comment]
Screenshot of an admin notification mail in (maybe, hard to tell) Russian language...

### Nextcloud mail:

![image](https://user-images.githubusercontent.com/3656054/100544390-99ddf000-3255-11eb-8e53-b9cb3e877106.png)

### Thunderbird:

![image](https://user-images.githubusercontent.com/3656054/100544421-cabe2500-3255-11eb-85b0-eb3b4afb8d72.png)

**Comment by AlfredSK** [comment]
### Source of the mail incl. headers

```
Subject: =?iso-8859-1?B?W9Ch0LjRgdGC0LXQvNC90L7QtSDRg9Cy0LXQtNC+0LzQ?=  =?iso-8859-1?B?u9C10L3QuNC1IEZyaWVuZGljYV0g0J/QvtC70YzQt9C+?=  =?iso-8859-1?B?0LLQsNGC0LXQu9GMINGD0LTQsNC70LjQuyDRgdCy0L7R?=  =?iso-8859-1?B?jiDRg9GH0ZHRgtC90YPRjiDQt9Cw0L/QuNGB0Yw=?=
Date: Sun, 29 Nov 2020 13:22:23 +0000
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Message-ID: <p6srxQbVdtHnEqzphtdKAagr65hkUmgOAro1cBGXFE@libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.12-dev
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="b1_p6srxQbVdtHnEqzphtdKAagr65hkUmgOAro1cBGXFE"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.
--b1_p6srxQbVdtHnEqzphtdKAagr65hkUmgOAro1cBGXFE
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒ ÑƒÐ´Ð°Ð»Ð¸Ð» ÑÐ²Ð¾ÑŽ ÑƒÑ‡Ñ‘Ñ‚Ð½ÑƒÑŽ Ð·Ð°Ð¿Ð¸ÑÑŒ Ð½Ð° Ð²Ð°ÑˆÐµÐ¼ ÑÐµÑ€Ð²ÐµÑ€Ðµ Friendica. ÐŸÐ¾Ð¶Ð°Ð»ÑƒÐ¹ÑÑ‚Ð°, ÑƒÐ±ÐµÐ´Ð¸Ñ‚ÐµÑÑŒ, Ñ‡Ñ‚Ð¾ Ð¸Ñ… Ð´Ð°Ð½Ð½Ñ‹Ðµ Ð±ÑƒÐ´ÑƒÑ‚ ÑƒÐ´Ð°Ð»ÐµÐ½Ñ‹ Ð¸Ð· Ñ€ÐµÐ·ÐµÑ€Ð²Ð½Ñ‹Ñ… ÐºÐ¾Ð¿Ð¸Ð¹.

id Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ: 4031

thanks
Steffen K9 ðŸ°, Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€ LIBRANET.de

--b1_p6srxQbVdtHnEqzphtdKAagr65hkUmgOAro1cBGXFE
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional //EN">
<html>
<head>
	<title>Friendica Notification</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
</head>
<body>
	<table style="border:1px solid #ccc">
	<tbody>
		<tr>
			<td style="background:#084769; color:#FFFFFF; font-weight:bold; font-family:'lucida grande', tahoma, verdana,arial, sans-serif; padding: 4px 8px; vertical-align: middle; font-size:16px; letter-spacing: -0.03em; text-align: left;">
				<img style="width:32px;height:32px; float:left;" src="https://libranet.de/images/friendica-32.png" alt="Friendica Banner">
				<div style="padding:7px; margin-left: 5px; float:left; font-size:18px;letter-spacing:1px;">Friendica</div>
				<div style="clear: both;"></div>
			</td>
		</tr>
		<tr>
			<td>
				<table>
	<thead>
	<tr>
		<td>
			ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒ ÑƒÐ´Ð°Ð»Ð¸Ð» ÑÐ²Ð¾ÑŽ ÑƒÑ‡Ñ‘Ñ‚Ð½ÑƒÑŽ Ð·Ð°Ð¿Ð¸ÑÑŒ Ð½Ð° Ð²Ð°ÑˆÐµÐ¼ ÑÐµÑ€Ð²ÐµÑ€Ðµ Friendica. ÐŸÐ¾Ð¶Ð°Ð»ÑƒÐ¹ÑÑ‚Ð°, ÑƒÐ±ÐµÐ´Ð¸Ñ‚ÐµÑÑŒ, Ñ‡Ñ‚Ð¾ Ð¸Ñ… Ð´Ð°Ð½Ð½Ñ‹Ðµ Ð±ÑƒÐ´ÑƒÑ‚ ÑƒÐ´Ð°Ð»ÐµÐ½Ñ‹ Ð¸Ð· Ñ€ÐµÐ·ÐµÑ€Ð²Ð½Ñ‹Ñ… ÐºÐ¾Ð¿Ð¸Ð¹.
		</td>
	</tr>
	</thead>
	<tbody>
		<tr>
			<td style="padding-right:22px;">
				id &#1087;&#1086;&#1083;&#1100;&#1079;&#1086;&#1074;&#1072;&#1090;&#1077;&#1083;&#1103;: 4031
			</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<td>
				thanks
			</td>
		</tr>
	<tr>
		<td>
			Steffen K9 ðŸ°, Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€ LIBRANET.de
		</td>
	</tr>
	</tfoot>
</table>

			</td>
		</tr>
	</tbody>
	</table>
</body>
</html>


--b1_p6srxQbVdtHnEqzphtdKAagr65hkUmgOAro1cBGXFE--
```

**Comment by MrPetovan** [comment]
I'm guessing this part doesn't play well with Cyrillic:
```
Content-Type: text/html; charset=iso-8859-1
```
However I don't know how to make sure we use UTF-8 for outgoing emails.

**Comment by annando** [comment]
How are you sending your mails? Via PHP or via the addon?

**Comment by AlfredSK** [comment]
See the provided mail source. ;-) Via the phpmailer add-on.

X-Mailer: PHPMailer 6.1.4

**Comment by AlfredSK** [comment]
When I use the notifyall add-on to check the mail headers I get mails with correct body (emojis are ok). But my name in the from and reply-to field is mangled.

```
From: =?iso-8859-1?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_A?=
 =?iso-8859-1?Q?dministrator=22?= <admin@libranet.de>
Reply-To: =?iso-8859-1?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_A?=
 =?iso-8859-1?Q?dministrator=22?= <admin@libranet.de>
```

**Comment by annando** [comment]
So it is an addon problem, I guess.

**Comment by AlfredSK** [comment]
I can disable the add-on and check again...

Btw. I'm getting those admin mails about 'user deleted their account' in the language of the user instead of my language or the default language of the node. But that's another issue.

**Comment by AlfredSK** [comment]
Test w/o phpmailer: Everything is ok. My bunny is displayed as such. 🐇

**Comment by AlfredSK** [comment]
The mail headers are completely different **w/o** PHPMailer add-on:

```
Subject: Ohne phpmailer
From: =?UTF-8?B?IlN0ZWZmZW4gSzkg8J+QsCwgTElCUkFORVQuZGUgQWRtaW5pc3RyYXRvciI=?= <admin@libranet.de>
Reply-To: =?UTF-8?B?IlN0ZWZmZW4gSzkg8J+QsCwgTElCUkFORVQuZGUgQWRtaW5pc3RyYXRvciI=?= <admin@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="6-528690241-985702814=:73912"
Message-Id: <20201129171744.63DFA2E826E9@libranet.de>
Date: Sun, 29 Nov 2020 17:17:44 +0000 (UTC)

--6-528690241-985702814=:73912
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

VGVzdCBhZ2Fpbi4uLiDwn5Ce8J+UivCfmKPinqHvuI/wn5qA8J+Sg+KYlfCfpLnwn5q+

--6-528690241-985702814=:73912
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

VGVzdCBhZ2Fpbi4uLiAmIzEyODAzMDsmIzEyODI2NjsmIzEyODU0NzsmIzEwMTQ1OyYjNjUwMzk7
JiMxMjg2NDA7JiMxMjgxMzE7JiM5NzQ5OyYjMTI5MzM3OyYjMTI4NzAyOw==

--6-528690241-985702814=:73912--
```

**Comment by MrPetovan** [comment]
> When I use the notifyall add-on to check the mail headers I get mails with correct body (emojis are ok). But my name in the from and reply-to field is mangled.
> 
> ```
> From: =?iso-8859-1?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_A?=
>  =?iso-8859-1?Q?dministrator=22?= <admin@libranet.de>
> Reply-To: =?iso-8859-1?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_A?=
>  =?iso-8859-1?Q?dministrator=22?= <admin@libranet.de>
> ```

This isn't mangled, this is your name converted to an ASCII-only representation with a header indicating the encoding used. Your emoji is correctly described as the sequence of four 8-bits characters: `=F0=9F=90=B0`. The `@` sign is encoded as `=2C` and the `.` is encoded as `=2E`.

**Comment by annando** [comment]
Yeah, but it is encoded as `iso-8859-1` which has got *slight* problems with unicode stuff :-)

**Comment by MrPetovan** [comment]
Fair enough, I'm just saying this particular snippet isn't mangled because it looks mangled. It's a perfect representation of multi-byte characters with a single-byte encoding. The decoding might not produce the expected ouput, but this snippet isn't proof of mangleness.

**Comment by AlfredSK** [comment]
Yeah. Of course you're right. With 'mangled' I was referring to the display in the mail clients. I should have been more precise.

**Comment by MrPetovan** [comment]
Thank you for the precision. So it is about the mail encoding in PHPMailer specifically, which curtails the problem.

**Comment by MrPetovan** [comment]
Please try to apply the patch in https://github.com/friendica/friendica-addons/pull/1049, it might be that simple.

**Comment by AlfredSK** [comment]
Perfect!

![image](https://user-images.githubusercontent.com/3656054/100553577-e2fe6600-328e-11eb-9481-7bc7a8be046b.png)

```
From: =?UTF-8?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_Admini?=
 =?UTF-8?Q?strator=22?= <admin@libranet.de>
Reply-To: =?UTF-8?Q?=22Steffen_K9_=F0=9F=90=B0=2C_LIBRANET=2Ede_Admini?=
 =?UTF-8?Q?strator=22?= <admin@libranet.de>
Message-ID: <nEJL3DKuSUegAFD2l1o0AWF8TKtJKGt6nFwFUftxeaY@libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="b1_nEJL3DKuSUegAFD2l1o0AWF8TKtJKGt6nFwFUftxeaY"

This is a multi-part message in MIME format.
--b1_nEJL3DKuSUegAFD2l1o0AWF8TKtJKGt6nFwFUftxeaY
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

0J/QvtGB0LzQvtGC0YDQuNC8LCDQuNGB0L/RgNCw0LLQuNGCINC70Lgg0LfQsNC/0LvQsNGC0LrQ
sCDQv9GA0L7QsdC70LXQvNGDLuODkeODg+ODgeOBp+WVj+mhjOOBjOino+axuuOBmeOCi+OBi+OB
qeOBhuOBi+imi+OBpuOBv+OBvuOBl+OCh+OBhuOAgvCfpLfwn5qA8J+Sg/CfmLvwn6Sq8J+RgPCf
mLTwn5i14pig77iP8J+qpvCfmI3imr3wn6Sm4oCN4pmC77iP4piR77iP

--b1_nEJL3DKuSUegAFD2l1o0AWF8TKtJKGt6nFwFUftxeaY
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

JiMxMDU1OyYjMTA4NjsmIzEwODk7JiMxMDg0OyYjMTA4NjsmIzEwOTA7JiMxMDg4OyYjMTA4MDsm
IzEwODQ7LCAmIzEwODA7JiMxMDg5OyYjMTA4NzsmIzEwODg7JiMxMDcyOyYjMTA3NDsmIzEwODA7
JiMxMDkwOyAmIzEwODM7JiMxMDgwOyAmIzEwNzk7JiMxMDcyOyYjMTA4NzsmIzEwODM7JiMxMDcy
OyYjMTA5MDsmIzEwODI7JiMxMDcyOyAmIzEwODc7JiMxMDg4OyYjMTA4NjsmIzEwNzM7JiMxMDgz
OyYjMTA3NzsmIzEwODQ7JiMxMDkxOy48YnI+JiMxMjQ5NzsmIzEyNDgzOyYjMTI0ODE7JiMxMjM5
MTsmIzIxODM5OyYjMzg5ODg7JiMxMjM2NDsmIzM1Mjk5OyYjMjc3NzA7JiMxMjM3NzsmIzEyNDI3
OyYjMTIzNjM7JiMxMjM5MzsmIzEyMzU4OyYjMTIzNjM7JiMzNTIxMTsmIzEyMzkwOyYjMTI0MTU7
JiMxMjQxNDsmIzEyMzc1OyYjMTI0MjM7JiMxMjM1ODsmIzEyMjkwOzxicj4mIzEyOTMzNTsmIzEy
ODY0MDsmIzEyODEzMTsmIzEyODU3MTsmIzEyOTMyMjsmIzEyODA2NDsmIzEyODU2NDsmIzEyODU2
NTsmIzk3NjA7JiM2NTAzOTsmIzEyOTcwMjsmIzEyODUyNTsmIzk5MTc7JiMxMjkzMTg7Jnp3ajsm
Izk3OTQ7JiM2NTAzOTsmIzk3NDU7JiM2NTAzOTs=


--b1_nEJL3DKuSUegAFD2l1o0AWF8TKtJKGt6nFwFUftxeaY--
```
