### ISSUE TITLE
How to get out of Maintenance Mode

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9574]
# For general question about Friendica, please try to find a solution at https://wiki.friendi.ca first.
After performing a git update, when I go to friendica I get redirected to maintenance:
Service Unavailable

2020-11-22 03:34:55 America/Los_Angeles: updating item-content table.

#0 [internal function]: Friendica\Module\Maintenance::content()
#1 /misc/www/friendica/src/App/Page.php(331): call_user_func()
#2 /misc/www/friendica/src/App/Page.php(387): Friendica\App\Page->initContent()
#3 /misc/www/friendica/src/App.php(559): Friendica\App\Page->run()
#4 /misc/www/friendica/index.php(42): Friendica\App->runFrontend()
#5 {main}

Report Bug

This website uses cookies. If you continue browsing this website, you agree to the usage of cookies.
This website is tracked using the Matomo analytics tool. If you do not want that your visits are logged in this way you can set a cookie to prevent Matomo / Piwik from tracking further visits of the site (opt-out).

Can someone tell me how to get out of maintenance and back into normal operation?

**Comment by 4nanook** [comment]
It corrected itself, just took a few minutes.

**Comment by MrPetovan** [comment]
When your node upgrade its database schema, no other operations (read or write) can happen. This is why we force the maintenance mode during this process. Once it is over, the maintenance mode is lifted automatically like you found out. Additionally, the maintenance mode message informs you about the current progress: `updating item-content table.`.

Please do not try to interfere with the database schema upgrade process as it can have unexpected consequences like having a partially upgraded schema which could cause random features from malfunctioning.

**Comment by 4nanook** [comment]
Thanks, never had a database update take substantial time before as in
minutes.  So didn't understand what was going on.  The maintenance mode
page did not display correctly as I showed in the question so I was a bit
concerned about that too.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
What display did you expect for the maintenance page?

**Comment by 4nanook** [comment]
DId not expect to see PHP errors.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment]
I understand it looks like a PHP error because it includes a stack trace. However only administrators like you can see it on their node's error pages for troubleshooting purposes, and it doesn't mean there is a bug. If you can see the normal website theme, then it is an application-handled error (like "user/item not found") and it doesn't warrant a bug report on its own.

**Comment by 4nanook** [comment]
Ok, thanks for the explanation.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
