### ISSUE TITLE
Autopopulate extended to twitter posts

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9579]
Loving the auto populate, when I @ someone and they are part of the fediverse, however if they from twitter I have to type the whole thing out, even though I'm "connected" to them via twitter mirror.  As most of my friends are on twitter cause I can't convince them to try a new platform, autopopulate for twitter addresses would be very helpful.
Thanks!

**Comment by MrPetovan** [comment]
Thanks for the suggestion, we might be restricting mentions to federated protocols, not sure it's relevant anymore.

**Comment by anubis2814** [comment]
Oh dear, I was REALLY enjoying having that level of connection with my other friends.
