### ISSUE TITLE
let showmore display a little bit more of a reshare 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9582]
### Is the feature request related to a problem? Please describe.

Not really a problem, only a small idea:
I have shared a post and don't see enough to know what this post was about:

![friendica-showmore](https://user-images.githubusercontent.com/5753419/99957813-94c9fe00-2d88-11eb-82b1-fda18ffb0227.jpg)

### Describe the feature you'd like

Maybe a little bit more could be shown. Example picture:

![friendica-showmore-idea](https://user-images.githubusercontent.com/5753419/99957915-b9be7100-2d88-11eb-8f4e-8fe2be9ef5ff.jpg)

### Additional context

I use Frio V.0.8.5 and have the showmore addon enabled and set to 1100 characters.

The instance (libranet.de) has these addons enabled:

> advancedcontentfilter, blockbot, blockem, catavatar, fromapp, geocoordinates, ifttt, impressum, js_upload, langfilter, markdown, newmemberwidget, notifyall, nsfw, openstreetmap, phpmailer, showmore, startpage, superblock, tumblr, twitter, unicode_smilies, wppost

**Comment by MrPetovan** [comment]
This is the problem with the legacy showmore addon, since it cuts after a certain number of characters in the post body, the share block are cut early since it counts the characters used to render the share block itself.

If you're using the frio theme, I suggest you use the Show More Dynamic addon instead.

**Comment by AlfredSK** [comment]
...or simply configure it to show more characters. :-)

**Comment by MrPetovan** [comment]
Or that, but it would show a lot more of all the other posts that don't include HTML tags in their body.

**Comment by AlfredSK** [comment]
Yes. The default is 1100. Which can be a little bit too aggressive. That's why I'm using 1800. And I'm pretty happy with it.

**Comment by haheute** [comment]
I totally misunderstood the setting. <s>I thought it will only get active when characters `> settings number` but always block until the same height.
Obviously not. </s>  I don't know what I thought. Now I've set it to 1200 and that looks okay for me.
