### ISSUE TITLE
Ability to exclude Twitter from search results

### ISSUE THREAD

**Issue by jgoerzen** [friendica/friendica#9584]
### Is the feature request related to a problem? Please describe.

When doing a search, particularly hashtag search, on a node that has Twitter enabled -- even if I do not personally have my Twitter account linked -- Twitter results will appear alongside Fediverse results.  The Twitter results tend to be of lower quality (because Twitter) and higher volume (also because Twitter) and can overwhelm the results I really want to see - from the Fediverse.

### Describe the feature you'd like

The ability to link Twitter is useful.  There should be a way to restrict search results such that Twitter isn't included, even on nodes that support Twitter.

More generally, it may be nice for searches to support an option to:

- Only search certain types of networks
- Or, exclude certain types of networks from the search

These settings should be preserved for saved searches.

### Describe alternatives you've considered

About all I can see as an alternative would be to switch to a node that doesn't have Twitter enabled at all.  This info isn't easily summarized in the node table, so wouldn't be easy to find necessarily.

### Additional context

**Comment by MrPetovan** [comment]
Thank you for the suggestion!

**Comment by AlfredSK** [comment]
Weird. I tried to reproduce this. I searched for #uspol - a hashtag with an expected huge amount of content. I scrolled down three weeks. I didn't find a single Twitter post. Only Fediverse content.

I use the Twitter connector on the node and personally, too.

**Comment by MrPetovan** [comment]
#uspol is indeed a Fediverse-specific hashtag.

**Comment by jgoerzen** [comment]
I replicated just now with a search for `#covid` on social.isurf.ca

**Comment by annando** [comment]
The search should only be on posts from the federated networks. If not then there's a bug.

**Comment by jgoerzen** [comment]
Definitely includes twitter also.  Screenshot: 
![example](https://user-images.githubusercontent.com/112925/100411508-9836e100-3037-11eb-906f-64d9ca9a8304.png)
