### ISSUE TITLE
Accepting contact requests: no notification, workflow to accept the contact completely broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9588]
- [X] I have searched open and closed issues for duplicates
- [X] Please treat with priority because this bug is really bad

### Bug Description
When you receive a contact request you **don't get any notification** about it - except when you habe enabled mail notifications. But in Friendica itself there is no notification anymore. It's gone.
Also when you go to contacts/pending there is no way to accept the contact request when using a **mobile device**.

The second bug might be Frio specific.

### Steps to Reproduce

1.  receive a contact request
2.  look at the dropdown notification menu (no info bubble, no new notification)
3.  go to contacts/pending with a mobile device
4.  try to accept the request

Actual Result:
Contact requests are broken. You don't get any notification about it in Friendica.
It's impossible to accept a pending contact request on contacts/pending page.

Expected Result:
A contact request should trigger a notification (info bubble on bell icon + entry in the drop down menu). Clicking on the contact request notification should redirect to a page where you can actually accept the request.

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
> * [x]  Please treat with priority because this bug is really bad

* [x] Duly noted

**Comment by AlfredSK** [comment]
Actually... I found out now that there is a way on mobile devices to accept the request. But it's well hidden. On contacts/pending you have to open the hover menu at the contact's avatar. There you find the menu item to accept the request.

**Comment by annando** [comment]
Well, indeed I have got several currently unanswered contact requests as I just saw. @MrPetovan are you working on it?

**Comment by MrPetovan** [comment]
No, tonight isn't a good time for me, please take it away.

**Comment by AlfredSK** [comment]
Maybe the workflow for accepting the requests is only broken because of the missing notifications. But I'm not sure.

**Comment by annando** [comment]
I can have a look at it, once that I finished my current task.

**Comment by annando** [comment]
The error had only been in the notifications. And after applying the fix I was able to confirm all requests.

**Comment by AlfredSK** [comment]
Ah!  As I suspected. :-) Thank you.
