### ISSUE TITLE
Twitter mirror ignores posts for 10 minutes after any fediverse posts happen 

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9589]
So I've noticed that not everything mirrors from twiter.  I discussed this with folks on the friendica helpers forum but never documented it.  I've noticed that after a post from someone in the fediverse is made on your timeline, the twitter mirror just stops mirroring anything for about 10 minutes.  After that it starts mirroring anything posted after that 10 minute gap and you never see anything posted during that 10 minute gap.  So you end up having missing communications from twitter without realizing it.  
Thanks!

**Comment by annando** [comment]
This has to be some other problem. The whole system is asynchronous. Means: The twitter posts are imported via some worker task. But incoming posts are processed without the worker. And even it the worker had been involved (it would do so, if someone comments on one of your posts), then this task would just be added to the list of tasks that are processed - and they are processed in parallel tasks.

You must have got a different problem.
