### ISSUE TITLE
Frio: Going to follow page follows

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#9598]
To reproduce:
 - I click an avatar
 - I click the plus icon

Expected behavior:
 - I see their follow page, with information about them, a list of posts, etc and a follow button

Actual behavior:
 - I see their contact page, which says I am now following them
 
> This is Friendica, version 2020.12-dev that is running at the web location https://libranet.de. The database version is 1379/1379, the post update version is 1349/1350.

> Installed addons/apps:
> advancedcontentfilter, blockbot, blockem, catavatar, fromapp, geocoordinates, ifttt, impressum, js_upload, langfilter, markdown, newmemberwidget, notifyall, nsfw, openstreetmap, phpmailer, showmore, startpage, superblock, tumblr, twitter, unicode_smilies, wppost

Display theme: Frio

**Comment by annando** [comment]
Yes. This was one of the changes to simplify the process to follow/unfollow someone.

**Comment by foss-** [comment]
Seems to work as designed. Can this be closed?

**Comment by MrPetovan** [comment]
Absolutely.

**Comment by MrPetovan** [comment]
Closed by #9440
