### ISSUE TITLE
Friendica does not allow me to post / comment after update, other users OK, other functions OK.

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9606]
- [ x] I have searched open and closed issues for duplicates

Yes, this is related to #9600, but I've closed that as I've made so many changes to my system that the original data is no longer
correct.  I've updated mariadb version and changed the configuration significantly, fixed all duplicate keys in the database, optimized all tables, and used a better tuning script that is more suitable for mariadb.  There were some errors in the earlier logs relating to database disconnects but I believe these were the result of my restarting the server or rebooting and unrelated,
therefore I am supplying fresh logs after the new server is in place and the duplicate keys fixed.

### Bug Description

Immediately after I applied some recent updates, when I try to comment on a post or post, I get a pop-up that says "Item wasn't stored."

### Steps to Reproduce

1.  Login and go to Home.
2.  Try to Post or Comment.

Actual Result:

Pop-up that says "Item wasn't stored." and the post or comment does not appear.  This only happens for me, it seems to
work okay for other users.  It seems to fail only for me.

Expected Result:

Expect the post to succeed.
### Screenshots

![friendica](https://user-images.githubusercontent.com/3466797/100544007-db47ae80-3207-11eb-9e8b-c2a2456e7672.png)
### Platform Info

Friendica Version:

This is Friendica, version 2020.12-dev that is running at the web location https://friendica.eskimo.com. The database version is 1380/1380, the post update version is 1349/1349.

Friendica Source: 
Github
PHP version:
php --version
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
SQL version:
mysql --version
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

[friendica.log](https://github.com/friendica/friendica/files/5612258/friendica.log)
Debug is turned on in index.php but php.out has nothing in it.

I will post the results of tuning-primer.sh after the server has been running long enough to get some useful data.  It provides
a more accurate assessment of memory utilization for MariaDB than does mysqltuner which really only works well with mysql.
Of particular note, there is always the concern that I was eating too much memory, but tuning-primer.sh says otherwise:

MEMORY USAGE
Max Memory Ever Allocated : 5.65 G
Configured Max Per-thread Buffers : 6.50 G
Configured Max Global Buffers : 5.26 G
Configured Max Memory Limit : 11.76 G
Physical Memory : 54.93 G
Max memory limit seem to be within acceptable norms

So yes if you used the full buffer on all threads (there are five workers) you could be upwards of 30G, but the machine is
configured with 56G so should be fine.  In practice memory usage never goes over 8G for EVERYTHING on the server, I
only allocate the huge amount for disk cache.

**Comment by MrPetovan** [comment]
See this log line:
```
2020-11-29T13:48:05Z index [NOTICE]: Author is blocked by user {"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-115f-c3a6-95a0-01f648089662"} - {"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"1cf962","process_id":580425}
```
For some reason, you seem to have managed to block your own account, which prevents you from posting.

It isn't blocked at the node-level, it is blocked at the user-level. I couldn't find a way in the UI to do or revert this, so I assume you'll have to fix it yourself in the database.

You can check two separate places, not sure which one is authoritative so you may have to fix both fields:
```sql
UPDATE `contact` SET `blocked` = 0 WHERE `nurl` = "http://friendica.eskimo.com/profile/nanook" AND `uid` = 1;
```
```sql
UPDATE `user-contact` SET `blocked` = 0 WHERE `uid` = 1 AND `cid` = (SELECT `id` FROM `contact` WHERE `uid` = 0 AND `nurl` = "http://friendica.eskimo.com/profile/nanook" LIMIT 1);
```

**Comment by 4nanook** [comment]
Thank you.  That fixed it!  Now how I did it I do not know.  It was working before I applied updates and not after.  I've saved these in the event I manage to do it again.

**Comment by 4nanook** [comment]
All done so closing.
