### ISSUE TITLE
Auto-completion for user names and bbcode tags doesn't work every now and then

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9622]
- [X] I have searched open and closed issues for duplicates

### Bug Description
The auto-completion for user names and bbcode tags doesn't work every now and then. When you type e.g. `@hypo` or `[cod` nothing happens. The list with suggestions doesn't pop up. As far as I remember it happens in comment boxes only. 

### Steps to Reproduce
Difficult because 90% of the time it works flawlessly. I didn't find out yet when and why this happens. But I just had an example...

1.  Someone wrote a comment. I got a notification about it.
2.  I clicked on the notification and was redirected to the /display page of the item.
3.  I clicked in the "fake" comment box at the bottom of the thread to write a comment.
4.  I typed `[code` ... nothing happens.

Actual Result:
Sometimes nothing happens. No popup list with suggestions for completion.
 
Expected Result:
Popup list with suggestions should work reliable.

### Related discussion

https://forum.friendi.ca/display/373ebf56-595f-cb47-8897-25e813717102 (German)

### Platform Info

Friendica Version:
2020.12-dev / 2020.12-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB

**Comment by MrPetovan** [comment]
Is auto-completion systematically missing on all of the `/display` page comment boxes?

**Comment by AlfredSK** [comment]
I don't know. I have to check that...

**Comment by AlfredSK** [comment]
Now it is the other way around. :-) 
It works on a random /display page (mentions and bbcode). It works on community pages.
It doesn't work on other pages like personal status page, network.

Checked another random /display page. Now it doesn't work there either.

I cannot find any systematic failure. Seems to be completely random.

**Comment by AlfredSK** [comment]
I'm using Chromium/Linux and Chrome/Android.

**Comment by annando** [comment]
With Firefox it is the same. Sometimes it works on the display page and sometimes not. The browser console doesn't give a hint.

**Comment by annando** [comment]
@MrPetovan can you have a look at it?

**Comment by MrPetovan** [comment]
Yeah, it's on my list after fixing the show more addon, or we can exchange.

Edit: Since you're probably sleeping, I'll take this on now and take the show more addon next if you didn't swoop in.

**Comment by AlfredSK** [comment]
Great! Seems to work reliably now. ❤️
