### ISSUE TITLE
Post in Friendica to Twitter get shorted without linking back to Friendica

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9624]
- [x] I have searched open and closed issues for duplicates

### Bug Description
When I publish a post in Friendica I usually have them sent to Twitter too. For some days (on dev/RC 2020.12) these posts not are shortened to the first line, so forwarded to Twitter only up to the first break. 
Photos are also stripped from the post. 

Example [Tweet](https://twitter.com/utzer/status/1335265745031352320?s=19)  
Resulting from this [post ](https://social.yl.ms/display/e18176ef-405f-cbba-0609-821526402274) 

### Steps to Reproduce

Post something longer that 240 characters from Friendica to Twitter or include a picture in a post to Twitter. 

Actual Result:
See above. 

Expected Result:
In the past, till a week ago, posts gut truncated on Twitter and a link back to Friendica was added. Pictures where included in the Tweet.

### Screenshots
Use the links above to see result. 

### Platform Info

Friendica Version:
Current RC 

Friendica Source: 
Git
PHP version:
Not sure, but up to date. Can check if really needed. 
SQL version:
Not sure, but up to date. Can check if really needed.

Please test this. I really use this feature a lot and would miss it much if it wasn't fixed before the release.

**Comment by annando** [comment]
Had it worked in stable? Because I compared the code and on the first glance I hadn't seen any differences.

**Comment by utzer** [comment]
It worked on dev a week ago, tweets have a marking social.yl.ms if they are sent from my Friendica account. See this one [here](https://twitter.com/utzer/status/1332938645741965313) with photos and [here](https://twitter.com/utzer/status/1331305312129839106) with a link.

**Comment by utzer** [comment]
😯 Speechless

Thanks! Will test later.
