### ISSUE TITLE
"Quote Share" breaks the formatting of the contribution

### ISSUE THREAD

**Issue by Singh-in** [friendica/friendica#9629]
- [x] I have searched open and closed issues for duplicates

### Bug Description

For forwarded contributions or when creating a "Quote Share" the formatting is broken

### Steps to Reproduce

Display of forwarded contributions in the stream
or
Quote a contribution
Preview

Actual Result:

Expected Result:

### Screenshots

![Screenshot_2020-12-06](https://user-images.githubusercontent.com/62051161/101278599-a8c82380-37bc-11eb-89d4-e24eadb303bc.png)
![Screenshot_2020-12-06(1)](https://user-images.githubusercontent.com/62051161/101278603-acf44100-37bc-11eb-8484-447f5c2675fc.png)

### Platform Info

Friendica Version: 2020.12-RC

Friendica Source: https://github.com/friendica/

PHP version: 7.3

SQL version: 10.3

**Comment by annando** [comment]
Will be fixed by https://github.com/friendica/friendica/pull/9626
