### ISSUE TITLE
frio: mobile: not possible to tap "accept" for friend / contact request

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9636]
- [X] I have searched open and closed issues for duplicates

### Bug Description

The text and the Accept / Decline friend / contact request UI is overlapping in frio, mobile UI. iOS, Firefox 29.2.

### Steps to Reproduce

Receive friend / contact request

Actual Result: It is not possible to tap the checkmark to accept the request.

Expected Result: UI elements and text should not overlap.

### Screenshots
(White sections are sanitized)
![contact request](https://user-images.githubusercontent.com/5708172/101537612-12eaef00-399c-11eb-81df-5b097b8b4378.jpg)

### Platform Info

This is Friendica, version 2020.12-rc that is running at the web location https://squeet.me. The database version is 1383/1383, the post update version is 1349/1350.

**Comment by MrPetovan** [comment]
Do you know when it was working last?

**Comment by foss-** [comment]
Sorry no, mostly use desktop so running into this was coincidence.

**Comment by MrPetovan** [comment]
Got it, thanks.

**Comment by MrPetovan** [comment]
> Do you know when it was working last?

To answer my own question, it was working with alternate buttons before we introduced the new Mode class and we removed the `App->is_mobile` property (method?) that a couple of templates were still using, including this one.
