### ISSUE TITLE
[AP] Limit remote emoji size in post body

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9639]
Since emojis have been fixed, I've started receiving AP posts where the emoji image is 3-4x the line height, which visually distorts the post body.

The image height can be limited related to the font size, but we can't target them precisely since we use a generic markup `<span><img src="..."></span>`.

This issue is then two-fold:
1. Add a class name to these in the protocol processor.
2. Add a CSS rule to limit their height relative to the font size (using em).

**Comment by annando** [comment]
You had it only 3-4 times in size? I just met Godzilla in form of an emoji :-)
https://pirati.ca/display/59e215f1-72ac6bd07c0c6aa9-ad1142a3

**Comment by AlfredSK** [comment]
Oh! I thought those were posted that big on purpose. I thought it is a "new thing" on fedi. 😁

**Comment by AlfredSK** [comment]
...please take the config key `'big_emojis'` into account when solving this issue.

**Comment by MrPetovan** [comment]
> ...please take the config key `'big_emojis'` into account when solving this issue.

What have I done in me previous lives to deserve such a punishment in this current one?

**Comment by annando** [comment]
It most likely had been very boring.

**Comment by MrPetovan** [comment]
Alright, I looked into it and `big_emojis` is only about Unicode emojis. I don't think it should apply to remote Mastodon/Pleroma emojis because they are meant to be displayed at text size. So this is a concern I don't need to factor in. 😌

**Comment by AlfredSK** [comment]
Shouldn't the behavior be the same - no matter if they are unicode or custom emojis? I really like consistency. :-)

**Comment by MrPetovan** [comment]
They are an entirely different beast. Unicode emojis are characters we can identify, custom emojis are just regular images we wrap with a `<span>` tag when we process the AP message. This means we can't identify a single custom emoji in a post the same way we do with unicode emojis.

And while Unicode emojis are meant to scale, custom emojis can be of any size (which was the crux of this very issue) and won't necessarily be consistent with each other, even from the same Mastodon instance.

**Comment by AlfredSK** [comment]
Thanks for the explanation. :blobthumbsup:  :-)
