### ISSUE TITLE
Ignored contacts still generate notifications

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9640]
Yesterday I had an unpleasant conversation with someone I was alerted of their comments through notifications, and this morning when I went to their contact page to ignore them I found out they were already ignored. Now, I know [we haven't completely agreed on the Ignore behavior](https://github.com/friendica/friendica/issues/4960), but I feel like this specific part is a no-brainer?

**Comment by annando** [comment]
AFAIR "ignore" means ignoring top level posts, but not blocking the whole communication - that would be blocking.

**Comment by MrPetovan** [comment]
No, but still, I shouldn’t be getting notifications from their comments.

**Comment by annando** [comment]
When ignoring only affects top level postings and not comments then notifications for comments should occur, shouldn't they?

**Comment by MrPetovan** [comment]
I still disagree with that, I feel like it's missing an intermediary between the current Ignore just about top-level posts and blocking that cuts all communication (which is therefore guessable). I didn't want to block this account, I just wanted to, well, ignore it, and I couldn't because of the notifications I kept receiving.

The current ignore behavior isn't consistent with Twitter's mute nor consistent with its own name. It's counter-intuitive and pretty much useless in its current form.

**Comment by annando** [comment]
Yeah, most likely we need some "ignore top level posts" setting. This would be ideal for example when you want to stay in contact with someone speaking multiple languages but posting mostly in a language that you don't understand. So you would keep their comments but not their top level posts.

**Comment by MrPetovan** [comment]
I'm flexible on displaying comments of ignored contacts or not, but the notifications must go.

**Comment by MrPetovan** [comment]
Since nobody else added their 2 cents, I'm going forward with dropping notifications from ignored contacts.

**Comment by annando** [comment]
I think that we are currently 50:50 concerning the "ignore" behaviour :-)

I think that we need an option where we can define that we don't want to see top level posts from selected contacts but would stay connected to them and continue to interact with them in a normal way - which would include notifications.

I think that we should add some configuration to the notification settings instead if we want to have a quick solution that doesn't include a complete redesign.

**Comment by MrPetovan** [comment]
Yeah, yeah, yeah, but until we've decided what to do with ignored contacts, I don't want to receive notifications from them without having to block them. So I'm putting my foot down on this specific behavior. If we ever agree on something else, it will be easily reversed.

**Comment by annando** [comment]
You could create a setting for this.

**Comment by MrPetovan** [comment]
I could but I won't until we have a firm agreement on what Ignore should do. Settings are a cheap short-term solution but often end up costing more on the long run.

**Comment by MrPetovan** [comment]
Closed by #9858
