### ISSUE TITLE
Misattributed Diaspora reply becomes top-level post 

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9641]
Original thread: https://friendica.mrpetovan.com/display/735a2029-745f-d0d9-92b8-25a575390980
Diaspora reply: https://nerdpol.ch/posts/735a2029-745f-d0d9-92b8-25a575390980#1a5b49401c58013960bc52540039b762
Misattributed comment as a top-level post: https://social.yl.ms/display/e18176ef-945f-d0e1-b4c1-589737649409

This is a really weird occurence I've never seen before. A comment from one of my remote contact (A) on one of my top-level posts became a top-level post by me on another contact's (B) node. Apparently these two contacts cannot communicate with each other as A's posts don't appear on B's server and B's posts don't appear on A's server.

But it still doesn't justify the comment misattribution. I believe the reply by A was delivered to B because I liked it. Then something really wrong happened and it got transformed into a top-level post attributed to me.

**Comment by annando** [comment]
It seems as if we currently have got some relaying problem. Not everyone seems to get all comments in a thread. So possibly there is some relation here.

**Comment by MrPetovan** [comment]
We should at least prevent the transfer of authorship to the causer.

**Comment by annando** [comment]
Do you have the logs from that day? If yes then have a look for entries with the GUID of that post that happened in "Delivery.php". Then take the value for "uid" from that log and have a look for all log entries with the same value for "uid" that happened in "Delivery.php". Have a look if you see 'Top level post' in it.

**Comment by annando** [comment]
Question is if https://github.com/friendica/friendica/pull/9644 could have caused this.

**Comment by MrPetovan** [comment]
I'll update my system and I'll try again.

**Comment by MrPetovan** [comment]
That'd be great, but I'm not sure how to reproduce this, maybe I should ask the concerned parties to try again once their node have been updated?

**Comment by annando** [comment]
Yeah, possibly. I want to address this issue also in another direction. Since Diaspora comments can only be read by systems that understand Diaspora, I'm considering transmitting them via the Diaspora protocol between Friendica servers anyway.

**Comment by annando** [comment]
Had it happened again?

**Comment by MrPetovan** [comment]
Not yet, it's too specific of a case for it to happen organically. And I haven't taken the time to contact A and B to set up a manual test.

**Comment by annando** [comment]
When it hadn't happened by now, I suggest to close this issue by now. Then we can reopen it in case it happens again.
