### ISSUE TITLE
[twitter] Mirrored post from Twitter mirrored back

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9642]
Twice since yesterday have my Tweets mirrored to my Friendica account been forwarded to Twitter again, resulting in a double publication to Twitter. The cycle seems to stop there though.

I've deleted the first duplicate tweet as I thought I made a mistake, but I've kept the second: https://twitter.com/MrPetovan/status/1336692793834680324

This is a copy forwarded from Friendica of a native retweet that was mirrored to Friendica here: https://friendica.mrpetovan.com/display/735a2029-115f-d0eb-2591-aac031331365

I'm assuming it has to do with the change in the URI we assign to posts from Twitter and ensure unicity of the mirror/forward relationship.

**Comment by annando** [comment]
I guess so. I'm currently working on the performance stuff and will then focus on distribution bugs. But I hopefully will have some time for this as well.

**Comment by MrPetovan** [comment]
I've reactivated mirroring from + post forwarding to Twitter, I've posted again to Twitter, cross your fingers.

**Comment by MrPetovan** [comment]
I can confirm this issue has been solved by https://github.com/friendica/friendica-addons/pull/1056, thanks!
