### ISSUE TITLE
Storage directory diversification for smaller backups

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9646]
If you make a file backup of your system, you backup photos and images from external sites and users. 

Since this can last in a huge backup size, it would be good, if photos and images of local users and forums can be identified within a special directory inside the storage directory. So you are able to only backup your local users stuff and not everything that is delivered to your server.

This will vastly decrease backup sizes and increase the backup speed for systems  with the file storage backend enabled.

A similar strategy would be good for the database storage backend.

**Comment by MrPetovan** [comment]
I thought regular user content and proxified remote pictures were stored differently?

**Comment by AlfredSK** [comment]
Well, we have the (optional) `.../proxy` folder.

**Comment by hoergen** [comment]
Ok and why is the storage directory so big?
I don't use the proxy.

**Comment by SpcCw** [comment]
@hoergen for me A LOT of space seems to be consumed by remote users' avatars. Some of them are quite large (animated ones especially) and there is awful lot of them - I am pretty sure most of them never interacted with my server directly.

Friendica isn't the only platform that does this but I wish there was come cleanup option.

**Comment by annando** [comment]
@SpcCw we have implemented a clean up for long time archived contacts in this RC. Also I want to implement a routine that removes the cached avatars for contacts that aren't active. I have to fix some bugs first, so it's likely that it will be part of the next release (and not this one).

**Comment by hoergen** [comment]
Can this issue be closed?
