### ISSUE TITLE
Peertube channels listed in forum widget

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9650]
- [🐧] I have searched open and closed issues for duplicates

### Bug Description

Using Friendica 2020.12-rc Peertube channels I'm following are listed in the forum widget on the side of the network stream.

### Steps to Reproduce

1.  Follow PeerTube channels
2.  have a look at the side bar forum widget
3.  ...

Actual Result:

PeerTube channels are listed in the forum widget.

Expected Result:

As a PeerTube channel is no forum, they should not be listed there.

### Screenshots

The _FSFE Main Channel_ and _Friendica Tutorials (de)_ are examples for this behavior.

![grafik](https://user-images.githubusercontent.com/433490/101977800-83219b00-3c50-11eb-9439-540569cb993f.png)

### Platform Info

Friendica Version: 2020.12-rc

Friendica Source: git

PHP version: 7.4

SQL version:10.3.27-MariaDB

**Comment by annando** [comment]
Peertube channels are using the type "group" that we are using for our forums as well. So they are listed there.

**Comment by tobiasd** [comment]
Possible, but still they are no forums hence they should not be listed in a forum widget. ;)

**Comment by annando** [comment]
Well, there is no way for the system to detect the difference between "group" and "group". And in some way it behaves like a forum in the way that the Peertube groups are distributing posts from others.

**Comment by tobiasd** [comment]
So if I select a PeerTube channel in the forums widget I can expect to post new things to that channel, similar to the other forums in that list?

**Comment by annando** [comment]
The behaviour what to do with received messages is up to the receiving system. But on our side the system doesn't see any differences between these two groups. We couldn't try some "are you Friendica?" detection, since the service https://gup.pe/ isn't Friendica, but should work exactly like a Friendica forum.

**Comment by tobiasd** [comment]
Those gup.pe groups were not listed in the forums widget though. It is only the PeerTube channels.
