### ISSUE TITLE
diaspora posts with youtube links show up empty in friendica

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9656]
- [x] I have searched open and closed issues for duplicates

### Bug Description

diaspora posts with youtube links show up empty in friendica.

### Steps to Reproduce

Diaspora Post with only a youtube video link: https://diasp.org/posts/8248f5201fad0139198a7085c2fdcc0b
![Bildschirmfoto 2020-12-13 um 21 38 00](https://user-images.githubusercontent.com/5708172/102023110-7f466380-3d8b-11eb-9e7f-a453e68a6362.png)

shows up as empty post on friendica: https://diasp.org/posts/8248f5201fad0139198a7085c2fdcc0b
![Bildschirmfoto 2020-12-13 um 21 38 40](https://user-images.githubusercontent.com/5708172/102023129-98e7ab00-3d8b-11eb-9a07-8460222e0edb.png)

Actual Result:

empty post

Expected Result:

video should be displayed

### Platform Info

This is Friendica, version 2020.12-rc that is running at the web location https://squeet.me. The database version is 1383/1383, the post update version is 1349/1350.

**Comment by annando** [comment]
This is an automatic method to prevent bad content ... You really should hear other music.

I also would be happy just transferring the problem to the site owner, but sadly it's me :grin: 

I had recently seen other posts from Diaspora that had been empty. But I thought that this might be some temporarily problem with the codebase, since currently I'm performing some coding tests there as well.

I will try having a look at the logs.

**Comment by annando** [comment]
I just saw that this might be some BBCode issue. The post itself is valid: 
```[youtube]p51c5g1iNzw[/youtube] ```

But babel returns just empty content.

**Comment by haheute** [comment]
I just had the problem that no preview appeared, when creating a post with video tag: `[video]https://www.youtube.com/watch?v=IMt7z1wuIJI[/video]`

It used to work with video tag before -- maybe it's related (?)  

I then posted just the link without video tag. That ended without embedded player: https://libranet.de/display/0b6b25a8-165f-d7bd-a3a5-011278797115

**Comment by MrPetovan** [comment]
Yes, it's related, the new HTML sanitizer is a little overzealous with the video embed code.
