### ISSUE TITLE
Large amount of really old posts is re-imported and presented as new content

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9657]
[V] I have searched open and closed issues for duplicates

### Bug Description
Since a couple of weeks I see **a lot** of really old posts in my /network page (sorted by latest posts). Some of these posts are 5-8 years old. I guess someone interacted with this content on a remote server. Most likely the content got a new 'like'. 

Because of this 'like' the ancient post is re-imported and presented like a new post because it has been received again just now. All the examples I see in my timeline are Diaspora posts. But I'm not sure if only the diaspora protocol is affected.

Example: `7 years ago (Received 55 minutes ago)`

This is annoying. A 'like' should not change the order of posts when sorted by 'latest posts'. Maybe we shouldn't re-import old content when a 'like' is received.

### Actual Result:
Ancient posts are showing up as new content in network stream when a 'like' is received.

### Expected Result:
Either discard the 'like' completely when the parent post is already expired or make at least sure the ancient stuff isn't displayed as new content in network stream when sorted by 'latest posts'.

### Platform Info

Friendica Version:
2020.12-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by annando** [comment]
I guess we can introduce the date check there.

**Comment by AlfredSK** [comment]
Some of these posts don't even have a like or comment. But it is possible that the "liker" is blocked.
