### ISSUE TITLE
"General Information" is not markd as translatable

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#9673]
- [ X ] I have searched open and closed issues for duplicates

### Bug Description

The section title "General Information" is not marked as translatable. You can [see the string here](https://github.com/friendica/friendica/blob/2020.12-rc/view/theme/frio/templates/admin/site.tpl#L36).

### Steps to Reproduce

1.  Change language other than English (let assume, the seleced language is fully translated)
2.  Go to Admin -> Site
3.  See the "General Information" header, it is always in English

Actual Result:

The string is displayed always in English.

Expected Result:

The string should be displayed in the selected language of the user interface.

**Comment by MrPetovan** [comment]
Ha, good catch!
