### ISSUE TITLE
Add "Remember this device" feature to 2FA auth

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9677]
See https://forum.friendi.ca/display/0b6b25a8-115f-dcce-d35c-8e1607849246

Having the device you have your 2FA app constantly asks for a 2FA token doesn't make much sense. A "Remember this device" feature would remember the first valid 2FA code entered and not ask again until the cookie expires.

**Comment by MrPetovan** [comment]
Security-related tasks are so touchy I already spent several hours working on this writing barely any code.

I realized I needed to add an extra key to the cookie data array and this requires to change how the cookie is set, I'll resume tomorrow with a fresh(er) mind.

**Comment by AlfredSK** [comment]
Hmm. I tried it on my phone. It doesn't seem to work. I enabled that additional checkbox on login page and entered a 2fa code.
After some hours I had to do the same again. I had to enter 2fa code again. I also checked the list of trusted browsers after that. I found the list empty.

**Comment by MrPetovan** [comment]
Can you please verify you have the table in your database? See https://github.com/friendica/friendica/pull/9823#issuecomment-769724951

**Comment by AlfredSK** [comment]
I already saw that comment. Let me check... Nope! Table `2fa_trusted_browser` doesn't exist.

**Comment by AlfredSK** [comment]
Ok. Running the dbstructure update manually created the table.

**Comment by AlfredSK** [comment]
Now it works. 🎉

**Comment by MrPetovan** [comment]
Excellent!
