### ISSUE TITLE
The word "required" is not translatable

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#9678]
- [ X ] I have searched open and closed issues for duplicates

### Bug Description

According to [these two lines in the source code](https://github.com/friendica/friendica/blob/2020.12-rc/src/Module/Admin/Blocklist/Server.php#L79-L80) the word "reqiured" is appended to the translated string as is.

### Steps to Reproduce

1.  Choose an other language than English.
2.  Go to Admin -> Server Blocklist and see the form.

Actual Result:

Translated: Kiszolgálótartomány-minta required, Original English: Server Domain Pattern required
Translated: A tiltás oka required, Original English: Reason for the block reqiured

Expected Result:

All strings should be translated. It would be nice to separate "required" a little bit, for example:

- Server domain pattern (required)
- Reason for the block (reqiured)

Please note, that one string is Title Case while the other is Sentence case. This is not consistent.

**Comment by tobiasd** [comment]
The "required" parameter is for the form field to be required before a modern browser will send the form data with the new entry to the server.

**Comment by MrPetovan** [comment]
This label is used as is in the frio template, so it needs to be translated. I'm working on it.

**Comment by annando** [comment]
Isn't it meant to be used as an attribute? See here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

**Comment by tobiasd** [comment]
Yes it is the attribute for the two input fields so that they are marked as required in the HTML form.

**Comment by MrPetovan** [comment]
Neither this original issue nor the submitted PR are about the `required` attribute that was already set and still will. Also please don't link to W3Schools in the future, it is a private entity not associated with the W3C that made their business to show you ads while you consult sometimes outdated web standard information copied from elsewhere.

For all your web standards needs, please use [the Mozilla Developer Network Web Docs website](https://developer.mozilla.org) instead.
