### ISSUE TITLE
"Yourself" is not marked as translatable in the profile page

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#9682]
- [ X ] I have searched open and closed issues for duplicates

### Bug Description

In the profile page the option "Yourself" is not marked as translatable. You can [see the string here](https://github.com/friendica/friendica/blob/2020.12-rc/view/templates/profile/index.tpl#L105).

### Steps to Reproduce

1. Change language other than English (let assume, the seleced language is fully translated)
2. Go to the profile and scroll down to the bottom. See the first option of "View profile as" field, it is always in English

Actual Result:

The string is displayed always in English.

Expected Result:

The string should be displayed in the selected language of the user interface.

**Comment by MrPetovan** [comment]
Thank you for the report!
