### ISSUE TITLE
Some kind of UI feedback to notice / undo accidental actions on mobile

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#9698]
Recently, it happened to me several times that I accidently hit reshare or like on random posts when scrolling through my friendica timeline on mobile.

It would be helpful if there was
(1) at least some kind of in-your-face feedback (e.g. a notification popup saying "post liked" or such) on the UI such that I don't miss it if this happens such that I can undo it
Or even better (2) a notification popup with an undo button such that it is possible to undo immediately.

**Comment by MrPetovan** [comment]
Both likes and direct reshares can be undone by pressing the same button again so I’m not sure we need a separate undo action for them.

For deletion, we have a confirm dialog to prevent unwanted actions.

**Comment by wiwie** [comment]
I know that they can be undone by pressing again. But that requires being aware of having liked/reshared.

But several times it happened now to me that I accidently pressed one of them and didn't notice when scrolling over a post with a lot of comments. It was only incidentally that I saw that I had liked/reshared when scrolling over the respective post/comment again.

**Comment by MrPetovan** [comment]
I see what you mean about the accidental tapping while you scroll. I feel like the best route for this is to have an instant reaction to the tap instead of waiting for the server's response as it can take quite some time.

**Comment by wiwie** [comment]
It does make a lot of sense to not wait for the server response.

Some initial thoughts I had, which may turn out to be non-sensical upon closer inspection:
- They could be shown as "snack bars"
- They could be black "bars" possibly semi-transparent with white text at the bottom of the screen
- They should not prevent further interaction with the remaining UX, and they should not obstruct view

Alternatively, and this probably is the more elegant solution:
- clearly reflect the initiated action via the buttons (e.g. like / reshare) on the UX while it is ongoing. Possibly change their color or maybe overlay them with some kind of spinner or animation.
- At the least, these changes to the buttons should be prominent enough, so they jump in the observers eye even when scrolling fast.
- Currently, a spinner is shown which is easily overlooked.
- I'm not entirely convinced though, this would suffice to prevent the random actions while fast scrolling scenario.

(I'm using the frio theme and hence all my points are specific to it)

**Comment by foss-** [comment]
Could you add "mobile" and "theme" to the issue title so this issue can be understood quicker. Which instance are you on?

How is the "mistap" happening for you? For me on iOS when I scroll a timeline using frio everything behaves as expected. If landing on one of the action items, it recognizes the tap, but does not trigger its action until the tap is released. So in case of scrolling it understands, the user wants to scroll and does not trigger the items action.

Tested on squeet me and action happened immediately although I had very mixed results in the past and even ran into situations where the spinner would spin indefinitely.

@MrPetovan  what would an instant response / reaction look like? In a brief test the info below the post that "MyUsername liked / shared / ..." was very instant.

**Comment by MrPetovan** [comment]
An instant response means that we update the display before we get the server's response, and then if the response is negative (unable to add a like or a share in this case), we revert the display to the original state, eventually with an associated asynchronous message display. However, currently we can't do that easily since the we can't guess the updated display from the JavaScript frontend, we have to wait until the action if performed and the display is refreshed asynchronously, two independent events that sometimes causes the display to not refresh correctly.

**Comment by SpcCw** [comment]
@MrPetovan is there some reason to make reshare button one click (not asking confirmation)?

I get that we can undo reshares by clicking the button again and it seems to work fine so far but personally I do have accidental clicks and unwanted reshares sometimes make me nervous and checking my feed to confirm reshare cancellation.

I would certainly prefer having simple confirmation for this action.

**Comment by MrPetovan** [comment]
Funnily enough Twitter used to have a 1-click approach to reshares but now two-clicks are nevessary.

**Comment by SpcCw** [comment]
I can see how accidental resharing of certain content can be highly undesirable :)

Especially if you don't notice it soon enough.

**Comment by AlfredSK** [comment]
Well, when you hold your phone in the left hand your scroll-thumb is hovering exactly over the buttons. So every scroll action can lead to a like or reshare if you scroll a little too slow.

The reshare issue could be easily avoided if we would have only one reshare button. When pressed a little popup dialogue could show up directly at the button with two options 'reshare' and 'quoted reshare'.

I'm not sure about the like button. A 'like' should be really easy to do.

**Comment by MrPetovan** [comment]
Can you all please test the changes I introduced in #9756 to feel if it is enough to prevent most unwarranted reshares?

**Comment by wiwie** [comment]
I'll have to wait with testing until my admin updates his instance. I think he's usually rather quick though.

**Comment by SpcCw** [comment]
Just tried it and I like it a lot so far.
Thanks! Looks cleaner as well with less buttons.

**Comment by foss-** [comment]
For reference a screenshot of the reworked UI:
![new UI](https://user-images.githubusercontent.com/5708172/104010739-498b7380-51ad-11eb-8fd6-ed28e10da80b.png)

**Comment by MrPetovan** [comment]
Thanks for your feedback, I consider this issue closed.

**Comment by wiwie** [comment]
This solution tackles accidental reshares.

Accidental likes are not considered an issue?

IMHO accidentally liking a random post could really give people the wrong impression about what kind of person one is. Same as reshares. Of course there is always the workaround to regularly check the personal tab.

**Comment by foss-** [comment]
Personally would not consider that a bug to tackle. If you scroll left or right of the like icon you should be fine. Been using friendica for a long time and have not run into this problem so far.

I do not think making the UI overly complicated to avoid such edge cases is in users interest.

**Comment by wiwie** [comment]
What keeps you from applying the same argument (scrolling left or right) to reshares?

**Comment by MrPetovan** [comment]
> This solution tackles accidental reshares.
> 
> Accidental likes are not considered an issue?
> 
> IMHO accidentally liking a random post could really give people the wrong impression about what kind of person one is. Same as reshares. Of course there is always the workaround to regularly check the personal tab.

I don't think it's the same kind of deal. For example, Friendica doesn't provide a way to list all the posts an account has liked (or disliked), so the "exposure" is lessened.

Furthermore, I'd like to look into removing the like display for posts that aren't yours like Mastodon is doing. This would limit even more the exposure of a wrong like to the post author only.

> What keeps you from applying the same argument (scrolling left or right) to reshares?

Reshare buttons were placed in the middle of the screen, like/dislike are on one side, so the probability of misstap is reduced, I think.

**Comment by wiwie** [comment]
Ok. The second argument is interesting. I wasn't aware that Mastodon is doing this. In fact I sometimes use the list of likers to identity interesting new contacts. This would then not be possible any longer?

Regarding the first argument: are likes not federated? I believe all my contacts get a copy of the post when I liked it? So I agree that it's lessened in that they cannot get the complete list, but on the other hand I feel it probably happens more often that others are becoming aware of likes of a contact via their own timeline than via browsing all posts of said contact? Just a guess though.

**Comment by MrPetovan** [comment]
You raise a good point, I know I'm getting posts my follows comment on, but I'm not sure I'm getting those they just like.

**Comment by foss-** [comment]
Iirc likes should be federated e.g. to Twitter. And I am certain that on Twitter followers receive info when a post is liked. I still am opposed complicating the like interaction. 

@wiwie are you having the same issue if you are using Twitter (if you are not using it, would be interesting to give it a try and see if you are running into the same issue).

I am still unable to reproduce this issue. When I scroll and even when I put my finger on the like icon on mobile, once I scroll the like action is not triggered.

**Comment by MrPetovan** [comment]
> Iirc likes should be federated e.g. to Twitter. And I am certain that on Twitter followers receive info when a post is liked.

It depends, some are sent to your followers but not all.

**Comment by AlfredSK** [comment]
> I'll have to wait with testing until my admin updates his instance. I think he's usually rather quick though.

@wiwie Oh! You are on my node. :-) I wasn't aware of that. I switched to develop today. The reworked share button is available now.
