### ISSUE TITLE
Get a lot very old posts in my timeline

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9705]
Using the current 2020.12.-RC I get a lot really old posts from time to time in my timeline. I noticed it because I was wondering, that I got my own Peertube posts again from time to time.
I am watching this since around 3 Weeks?

Like this one 
![00_temp00](https://user-images.githubusercontent.com/24474762/103134606-b2a1c000-46b2-11eb-8201-69f342a2e113.jpg)
https://conf.tube/videos/watch/7d0aa9a1-d9fb-4dbd-9183-aec6cdf1ec35

It kind of "oversolves" this issue :) https://github.com/friendica/friendica/issues/8538

**System**
Install : git
Version 2020.12-RC (25.12.2020)
PHP 7.4

**Comment by annando** [comment]
Peertube is sending updates on their videos from time to time. We also removed the date check on incoming posts. So this is is the result.

**Comment by hoergen** [comment]
What is the reason that you removed the date check?
Maybe a check on the post, if the post is older than a week or two, it will be discarded ?

**Comment by annando** [comment]
It hadn't been possible to import older posts.

**Comment by hoergen** [comment]
I don't get the logic of your answer :) Shouldn't we try to avoid to import older posts?
I understand, if one connects the first time to an account, that you want have the last .. 10 or 20 posts,.
But why should you want to import older posts from an already existing contact?

**Comment by AlfredSK** [comment]
Think "manual import" via search for example.

**Comment by hoergen** [comment]
Hmm those old posts are really annoying and my personal opinion that should be stooped before doing the release. Meanwhile i get several old posts on daily basis. And I am only following mabye 3-5 Peertube accounts.

**Comment by hoergen** [comment]
Ok, after monitoring it for a while I think the issue is really solved and I am now officially closing this issue.

**Comment by hoergen** [comment]
I reopen this issue because I recieved again an very old post (7 month)
![00_temp00](https://user-images.githubusercontent.com/24474762/104901912-4eef7780-597e-11eb-9dc3-143ccf0de25e.jpg)
source : https://friendica.feneas.org/display/7e13cec0930c01385afc101b0efced44

**Comment by annando** [comment]
How long is your message storage time? When it is more than 7 months then this is okay.

**Comment by hoergen** [comment]
No hehe I'm deleting after 30 days. No need for long archiving. 
As I suggested in another issue it would be a good idea to use the last received date and store it in that contact, to check, if the next incoming post is older or newer ?

**Comment by annando** [comment]
Problem is: There are situations where you would want to import old posts manually. This here most likely was a situation where someone shared that post - and since it wasn't available on your system, it was fetched. This is a complicated situation.

**Comment by hoergen** [comment]
Hmm as far I could see, the post wasn't shared. It arrived as a new post.
Maybe the function to import posts should have some "if aka case" statements for different situations?

**Comment by annando** [comment]
Problem is that this information needs to be passed through many different functions and protocols. So currently we do now if a post was delivered to us regularly, by relay (only DFRN and AP, not Diaspora) or fetched. The fetching is not split further.

**Comment by hoergen** [comment]
Is the problem solved? I didn't notice some more posts, but I wasn't that attentive watching my stream the last week.

**Comment by annando** [comment]
I haven't done any additional work at this.

**Comment by hoergen** [comment]
Okay, maybe I didn't see it.  Had one old post again, so it still exists.

**Comment by hoergen** [comment]
I get old posts again. 2 Year old  ... 3 years old from different servers mostly peertube.

This one for example https://conf.tube/w/b4e5c88b-45a6-4942-b7d6-2027721862aa

**Comment by annando** [comment]
Peertube regularly sends stuff like viewing statistics for their videos. I have to have a look why the check of the age of a post doesn't work in this case.

**Comment by hoergen** [comment]
Still old posts are delivered over and over again. Solution was described years ago here and in other threads. Any chance this will get a fix? If not, please close this Bug report.

**Comment by AndyHee** [comment]
Ancient posts from a previous decade still lurking in my database, despite active cleanup settings.

![Screenshot_20231005_231838](https://github.com/friendica/friendica/assets/28751375/6283fa29-0813-49c3-84d3-839398f55674)

![Screenshot_20231005_213242](https://github.com/friendica/friendica/assets/28751375/b6575e32-ed49-4bfc-825c-ce8cb714e9e2)

**Comment by annando** [comment]
@AndyHee that's something different and unrelated to this issue. You can see that there is no corresponding remark at the creation date.

**Comment by AndyHee** [comment]
OK @annando - thanks! @tobiasd suggested this might be a problem specifically relating to posts that were created via the calendar function. 

I also noticed the same problem for old posts from what used to be called "Forums"; they equally don't get removed from the database.

**Comment by hoergen** [comment]
Still an issue?

**Comment by annando** [comment]
At least not for me.

**Comment by hoergen** [comment]
ok i close it
