### ISSUE TITLE
[frio] Blocking and unblocking users via the hovercard

### ISSUE THREAD

**Issue by Singh-in** [friendica/friendica#9719]
### Is the feature request related to a problem? Please describe.

Blocking or unblocking a user is complicated because it is solved via various steps. This creates unnecessary barriers that can be avoided. 
Blocking a user who is not in the contacts is currently not possible.

The steps are:
- Call Contacts 
- Search for the user to be blocked from the list of contacts and select him/her via "Show contact".
- Use the "Actions" menu to set a block or remove the block.

Blocking a user who is not in the contacts is not supported today. 

### Describe the feature you'd like

Blocking and unblocking a user, regardless of whether they are listed as a contact, directly from the network stream.

For this purpose, the hovercard is to be extended by the functions 
- "Block" if there is no nlock and 
- "Unblock" if a block already exists.
- If necessary, the existing call under Contacts can be used to generate the result.
- In addition, it should also be possible to block users who are not listed as contacts.
- If necessary, it makes sense to create a contact as a contact and automatically assign it to a group (blocked) if the contact has not yet been managed but is to be blocked.

Counter-suggestions that are technically easier to realize are welcome

**Comment by SpcCw** [comment]
I think it is totally possible to block someone not in your contacts, just to to their profile information from the hovercard and you can block them in "actions" on the top right. It takes two steps.

![image](https://user-images.githubusercontent.com/35988439/103294053-1f45f300-4a02-11eb-907b-1002e62183e5.png)

**Comment by MrPetovan** [comment]
@SpcCw You're right, but it does prove @Singh-in 's point, it isn't user-friendly.

We're looking into the best place to add this feature. I like the idea of adding it to the posts dropdown list in the "More" link in frio but it may be added in the hovercard as well.

**Comment by Singh-in** [comment]
@SpcCw 
you are right. Learned something again.

@MrPetovan 
Since it is possible to add a contact on the hovercard, this seemed more consistent to me than in the dropdown list. But you are right. It is still more present there.

**Comment by SpcCw** [comment]
Yes, I agree that current way is somewhat counterintuitive. It suits me fine however having a button on the hovercard would be more organic and easier for people coming from other networks.

Just make sure it asks for clear confirmation before commencing block :)

**Comment by Extarys** [comment]
Do you need to block users/spammers frequently in friendica/fediverse? (Honest question)

Most social network (tech giants), you do need to go on the profile page to block a user. If you need to block users on a regular basis, I understand the purpose, but if you block as often as I block someone on facebook for example (1 or 2 per year tops) then going to the profile page isn't that cumbersome. We just need to make sure all options are labelled and positioned clearly to make this as much intuitive as possible.

**Comment by tobiasd** [comment]
I'm blocking accounts once every week basis, mostly annoying re-shared stuff.

**Comment by AlfredSK** [comment]
I do 'blocking' nearly as often as I do 'liking'. :-)

**Comment by Extarys** [comment]
Ok thanks! I will check what we can do.

Damn @AlfredSK that is sad though

**Comment by AlfredSK** [comment]
> that is sad though

Well, I exaggerated a little bit. :-) But I think this isn't sad at all. Blocking is completely normal to keep the timeline and community pages in a readable state and reduce the number of useless bot posts.

**Comment by Singh-in** [comment]
Among other things, there is a lot of pornographic stuff flying around. In addition, there are some servers that increasingly spread conspiracy theories. I don't want to see them in my timeline. So it's an advantage to be able to block them quickly and conveniently. That happens quite often.

**Comment by MrPetovan** [comment]
I still prefer the idea of blocking from the `More` link in Frio, it allows us to immediately remove the offending post from the network stream, which a hovercard block button would not. Both are possible, but the may be a conflict of expectation with the hovercard block button in the context of a specific post.

**Comment by Extarys** [comment]
Having the option in the post or comment `More` option would indeed be better. The hover card looks already cluttered.

**Comment by Singh-in** [comment]
solved with #9833
