### ISSUE TITLE
Numbers with dollar sign (such as money sums) get removed from reshares

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#9720]
### Bug Description
If a post contains some figure with dollar sign (e.g. $50) and it gets reshared, this figure is missing from the reshare.

### Steps to Reproduce

1. Make a post and include some number with dollar sign:
https://friends.deko.cloud/display/d0446be5-185f-eb43-b6ba-454083538146

2.  Reshare the post and look at the reshare:
https://friends.deko.cloud/display/d0446be5-175f-eb43-c5a9-5a6731031592

### Platform Info
Happens for a while now, 2020-12-rc included.

No errors in logs.

**Comment by MrPetovan** [comment]
I have a hunch it has to do with the tagging system, $ means something specific in Hubzilla if I remember correctly.

**Comment by SpcCw** [comment]
@MrPetovan - to me it also looks like a problem with string processing as if $... isn't escaped somewhere and PHP treats it as variable. With $1 and $0 actual variable substitution happens.

Orig: https://friends.deko.cloud/display/d0446be5-125f-ec12-a24c-88a159977524
Reshare: https://friends.deko.cloud/display/d0446be5-865f-ec15-a699-bf2054885536

It seems to always take and try to substitute the first two digits following after $.

**Comment by MrPetovan** [comment]
It seems more complicated than just variable interpolation from this: https://friends.deko.cloud/display/d0446be5-195f-ec12-b845-019684528110

Nice catch though!

**Comment by SpcCw** [comment]
Ups, I put the wrong link to original post! It was pointing to another reshare and got confusing. The correct link is https://friends.deko.cloud/display/d0446be5-125f-ec12-a24c-88a159977524 and I updated the previous comment.
