### ISSUE TITLE
Native reshares do not trigger notifications

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9723]
If I follow page A, and page A posts a normal post, I get the notification. But if page A post a native reshare, I do not get the notification.

**Comment by tiotrom** [comment]
It seems that native reshares do not even appear in the newsfeed...so they are basically invisible :P

**Comment by AlfredSK** [comment]
When you reshare something yourself you see it in your 'home' stream (the house icon). Or am I getting you wrong?

**Comment by tiotrom** [comment]
Yes you see your own reshare, but others won't. Others who follow you. That was my point about ;)

**Comment by SpcCw** [comment]
I can confirm this. I have multiple accounts on my server following each other. I just "native reshared" a fresh post then switched to another account and can't see it in the network stream.

However if I open first account's hovercard and click on "network posts" icon I can see the reshare just fine. I can interact with it and if I do (e.g. like it) it starts to appear in Network stream.

Update: just noticed weird thing - these reshares do appear in Network stream after they get any interaction. As soon as some person from other server liked it my other account received it in Network stream (some 40 minutes later) even though they don't follow each other.

**Comment by tobiasd** [comment]
I think they do now in 2021.09-rc (optionally) right @annando

**Comment by annando** [comment]
Yeah, they should.
