### ISSUE TITLE
"Missing database structure config file static/dbstructure.config.php" but file is present

### ISSUE THREAD

**Issue by Casuallynoted** [friendica/friendica#9728]
I've been doing searching around and haven't been able to find another instance of this issue. I just upgraded my friendica instance and it's giving me the error in the title. What's weird is that that file is right there where it should be and has all the stuff it should in it. I'm not sure what else to provide on this one, it's weird because it gives me the same error when trying to do DB updates.

**Comment by annando** [comment]
Possibly it is a file permission problem?

**Comment by Casuallynoted** [comment]
I tried setting the file’s permissions to 665, but still no dice. Should I try setting it to something different?

**Comment by annando** [comment]
I never heard of this issue, so I'm unsure how to fix it. Possibly it is a problem with the wrong base directory?

**Comment by Casuallynoted** [comment]
What would I do if I wanted to change the base directory in the config without the site working?

**Comment by annando** [comment]
You can do all the stuff in the command line.

**Comment by AlfredSK** [comment]
Put something like this... into the `system` section of your `config/local.config.php` file:

`'basepath' => '/path/to/your/friendicafolder',`

**Comment by Casuallynoted** [comment]
Ok so I did that and it seems to be giving a different error now!

```
Fatal error: Uncaught TypeError: Argument 4 passed to Friendica\App::runFrontend() must be an instance of Friendica\App\Authentication, instance of Friendica\Security\Authentication given, called in /Volumes/Docker/tmp/Friendica/index.php on line 40 and defined in /Volumes/Docker/tmp/Friendica/src/App.php:419
Stack trace:
#0 /Volumes/Docker/tmp/Friendica/index.php(40): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1609461737.7215)
#1 {main} thrown in /Volumes/Docker/tmp/Friendica/src/App.php on line 419

Warning: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) in Unknown on line 0
```

**Comment by AlfredSK** [comment]
Oh! Docker. Sorry, that stuff is a blackbox for me.

**Comment by MrPetovan** [comment]
@Casuallynoted Do you know which source version do you have? Is `/Volumes/Docker/tmp/Friendica/` a local git repository by any chance? If so please run `git show` and report the output.

**Comment by Casuallynoted** [comment]
This is what I'm seeing atm when I run that-
commit 51c785f89c273d4d8ec45bea0a6ccecdc3abec5f (HEAD -> stable, tag: 2020.09-1, origin/stable, master)
Author: Tobias Diekershoff <tobias.diekershoff@gmx.net>
Date:   Thu Sep 24 15:24:20 2020 +0200

    Version 2020.09-1

diff --git a/VERSION b/VERSION
index 682a8d1fb..ed52ef786 100644
--- a/VERSION
+++ b/VERSION
@@ -1 +1 @@
-2020.12-dev
+2020.09-1
diff --git a/boot.php b/boot.php
index af08d5443..6cc717d6b 100644
--- a/boot.php
+++ b/boot.php
@@ -38,7 +38,7 @@ use Friendica\Util\DateTimeFormat;
 
 define('FRIENDICA_PLATFORM',     'Friendica');
 define('FRIENDICA_CODENAME',     'Red Hot Poker');
-define('FRIENDICA_VERSION',      '2020.12-dev');
+define('FRIENDICA_VERSION',      '2020.09-1');
 define('DFRN_PROTOCOL_VERSION',  '2.23');
 define('NEW_UPDATE_ROUTINE_VERSION', 1170);

**Comment by MrPetovan** [comment]
It looks like you have two conflicting version of the source tree on your machine. The `index.php` seems to be in version `2020.12-dev` while the `src/App.php` is still in version `2020.09`, which triggers the type error you are getting. Please run `git checkout -- . && git clean -df && git checkout 2020.09-1` in the Friendica root folder (`/Volumes/Docker/tmp/Friendica/`).

It will reset all the locally modified files git knows about (not the local configuration files that are git ignored) and do a clean checkout of the lower version between the two conflicting ones.

**Comment by Casuallynoted** [comment]
Damn, that did it! 👍 Thank you so so much!
