### ISSUE TITLE
Hashtags that consist of numbers only do not work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9733]
- [X] I have searched open and closed issues for duplicates

### Bug Description
Hashtags that consist of numbers *only* do not work. 

Tags like `#abc2020` or `#2020abc` do work!

### Steps to Reproduce

1.  add a hashtag like `#2020` to your post
2.  click on preview or submit the post
3.  see that `#2020` is text only (no link to search)

Actual Result:
Hashtags that consist of numbers only are displayed as plain text w/o a link to a search URL.

Expected Result:
They should work like textual hashtags.

### Platform Info

Friendica Version:
2020.12-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by Extarys** [comment]
Thanks for the report @AlfredSK !

The hastag is not detected, looks like a server-side/PHP bug.

![image](https://user-images.githubusercontent.com/11581433/105176471-4a989b00-5af3-11eb-96b7-f521a962a7d7.png)

**Comment by MrPetovan** [comment]
It really is.
