### ISSUE TITLE
Deny registration

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#9736]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

Registration on my server is open by approval. However, at the moment it is not possible not to approve the registration, because unfortunately nothing happens when I press the Deny button on the `/admin/users/pending` page. The contact remains in the list.

### Steps to Reproduce

1.  Activate registration after approval
2.  Register a new user
3.  Go to `/admin/users/pending` and refuse registration

### Actual Result:

The contact remains in list `/admin/users/` with the message Blocked and in list `/admin/users/pending` it is still waiting for confirmation.

### Expected Result:

The registration should be rejected and the user should disappear from the list.

### Platform Info

Friendica Version: Friendica 'Red Hot Poker' 2020.12-rc - 1384

Friendica Source: git

PHP version: 7.4.13

SQL version: MariaDB 10.3.27

**Comment by AlfredSK** [comment]
Hmm. I just denied a registration yesterday. I had no issue with it.

What theme and what browser/OS do you use?

How exactly did you deny the registration? There's the possibility the interact with every registration request individually and there's  the possibility to use the batch processing of registration requests.

**Comment by atasingorneq** [comment]
I tried with Firefox and Chromium on my Laptop and with Fennec on Android, and i tried with the batch processing and the idividually. Always with the same result.

**Comment by AlfredSK** [comment]
Ok. And what theme do you use?

**Comment by atasingorneq** [comment]
Oh sorry, I just forgot to write. I use Frio and have also tested it with Vier.

**Comment by AlfredSK** [comment]
Thanks. I just tried to reproduce it with an up to date 2020.12-rc.

Registered a new account (like a user would do it)
Went to admin/users/pending
Clicked on the "Deny" button (on the right side of the line)
Request is successfully denied
Request vanished from the "Pending" list

Tested with frio, Chromium/Linux.

**Comment by AlfredSK** [comment]
Since there have been some code changes in the area, I would refresh or clear the browser cache and then try again.

**Comment by atasingorneq** [comment]
Same result also with cleared browser cache ...

**Comment by AlfredSK** [comment]
Maybe it is useful to have a look at the browser console. If there is an error you should get some information there.

**Comment by MrPetovan** [comment]
Like @AlfredSK I have tried to deny users on frio both ways (per registration and in bulk) and tested it to work. We definitely need more information about your own node. Can you please watch the Friendica log and the PHP/web server log while you're denying a registration?
