### ISSUE TITLE
Still get posts from an ignored Twitter user

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9740]
if I ignore a Twitter friend, then I can still see their retweets. Not sure about their tweets tho.

**Comment by tiotrom** [comment]
To update this, I see the re-shares of a twitter user that I used to follow but now I removed or blocked. So I see the re-shares, not the posts. It is weird, but I cannot get rid of those....probably have to go to twitter and remove/unfollow the user. So this is a problematic bug since you lose control over what you don't want to see. Just saying :P

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.

**Comment by tio-trom** [comment]
Yes should be closed.
