### ISSUE TITLE
Many strings are not marked as translatable

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#9743]
The following files contain many hard-coded strings. These are displayed in Admin -> Diagnostics, and they are not marked as translatable:

- https://github.com/friendica/friendica/blob/develop/view/templates/probe.tpl
- https://github.com/friendica/friendica/blob/develop/view/templates/webfinger.tpl
- https://github.com/friendica/friendica/blob/develop/view/templates/admin/item/source.tpl
- https://github.com/friendica/friendica/blob/develop/view/templates/babel.tpl
- https://github.com/friendica/friendica/blob/develop/view/templates/debug/activitypubconversion.tpl

Some of this pages (e.g. Probe or WebFinger) has no left sidebar in the admin page.

**Comment by MrPetovan** [comment]
Hi and thank you for your report. Since these pages are mainly used for debugging, we haven't given them too much attention intentionally. Adding the admin left menu is also a nice to have.

**Comment by urbalazs** [comment]
It would be also nice to add some explanation texts to these pages: what are they used for, how to use them, examples etc.

**Comment by MrPetovan** [comment]
When I tackle this nice to have issue, I can probably add some info.
