### ISSUE TITLE
Video attachment is removed from the post after upgrading from 2020.09-1 to 2021.01

### ISSUE THREAD

**Issue by urbalazs** [friendica/friendica#9745]
### Bug Description

I had a Friendica version 2020.09-1 and a post that contained a video file. After upgrading to 2021.01, the video is missing from the post. If I login as the user who shared the post with the video and try to edit the post, the following error message is displayed in the _Browser_ tab of the edit widget:

```
Warning: htmlspecialchars() expects parameter 1 to be string, array given in .../friendica-full-2021.01/view/smarty3/compiled/b48688150f6f0a40e7c2daa2c7945be70015666d_2.file.filebrowser.tpl.php on line 44
```

### Steps to Reproduce

1.  In 2020.09-1, create a post and include a video in the body.
2.  Upgrade to 2021.01
3.  See the post. The video is missing, and an error message is displayed in the edit widget.

If I add the video again, the code `[attachment]1[/attachment]` is added to the post and the video is displayed again. However if I go back to the edit widget, the attachment code is missing again in the post's body.

**Comment by MrPetovan** [comment]
Thank you for your report!

**Comment by AlfredSK** [comment]
@MrPetovan Oh! Do you remember that warning? That's the one I couldn't reproduce anymore and where my logs were already deleted by logrotate.

**Comment by MrPetovan** [comment]
Yup, but I don't think it's related to the attachment disappearance, it's specific to file browser display.

**Comment by urbalazs** [comment]
The warning message is added to **PHP Warnings** in https://github.com/friendica/friendica/issues/9748#issuecomment-754759368

**Comment by urbalazs** [comment]
2020.09-1 and 2021.01 are not supported anymore. Since I cannot reproduce this problem in newer versions, I close this issue.
