### ISSUE TITLE
Theme: Frio: Mobile: dark / black schemes not respected / applied in left sidebar

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9764]
### Bug Description

Theme: Frio: Mobile: dark / black scheme not applied to left sidebar.

### Steps to Reproduce

Open Friendica on mobile and open the three dots on the left to open left sidebar view.

Actual Result:

![frio mobile left sidebar](https://user-images.githubusercontent.com/5708172/104011968-42fdfb80-51af-11eb-852b-f2c1960b3c07.PNG)

Expected Result:

Would expect that color scheme is followed.
Should someone decide to work on this: there is a minor issue with the right sidebar as well where the bottom area below the menu items is displayed in white. Expected would be to apply the background color used on the rest of the site.

### Platform Info

This is Friendica, version 2021.03-dev that is running at the web location https://pirati.ca. The database version is 1384/1384, the post update version is 1384/1384.
iOS 13.4

**Comment by MrPetovan** [comment]
Oof, nice find.
