### ISSUE TITLE
Frio: mobile: need to scroll up to top of timeline to see search input field

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#9767]
Currently, when located somewhere down the timeline and clicking on the search icon in the top bar to bring the search input field up the input field is not visible as it is attached to the top of the timeline.

So in order to see the search field one needs to scroll all the way up the timeline.

This is a minor inconvenience, but I encounter it comparably frequently.

**Comment by MrPetovan** [comment]
Thank you for the report, I've had this experience as well, although it's been easier for me since I've been using the paginated results on the network page. But hey, it's a use for the Back to Top button!

**Comment by foss-** [comment]
Solution could be to extend search field above timeline so that no scrolling is needed to use it.

**Comment by wiwie** [comment]
My idea would be to insert the search bar at the bottom of the two top toolbar panels.

This way it would be shown over (> z index) the timeline. Which would lead to temporarily hiding a small portion of the timeline when the search button is pressed, but I don't think this would be a problem.

If I understood the layout correctly nothing else would need to be changed.

Oh wait, now I jinxed it. CSS is never that easy.

**Comment by Extarys** [comment]
@MrPetovan Can you also close this please? :heart: 

Fixed in PR #9806

**Comment by MrPetovan** [comment]
Of course.

Hot Tip: You could have done it yourself if you'd have mentioned this issue in your PR like "Fixes #9767". This issue would have been closed automatically once your PR would have been merged.
