### ISSUE TITLE
post not appearing on diaspora

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9777]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I have just [posted a picture](https://libranet.de/display/0b6b25a8-475f-fc89-2757-618471320385) and I'm always looking on my diaspora account, to see if it appears there. It doesn't. And it says only "remote server 75" where normally has a number > 250 or even 300.

### Steps to Reproduce

Post something public (i did on libranet.de). Look if it appears on diaspora. (I have tried 2 times. both didn't work.)

Actual Result:

doesn't appear

Expected Result:

should appear. and did until ~ yesterday or today

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2021.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1385/1385 und die Post-Update-Version 1384/1384."

**Comment by annando** [comment]
Yeah, it seems as if there currently is a bug that prevents public posts to Diaspora in the develop branch. I had done some changes there, so I know who to blame :grinning:
