### ISSUE TITLE
Last post endless scrolling bug

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9782]
### Bug Description

When saving a post in an empty friendica folder and opening that folder. that one post is repeating forever. The same ist happening for the last post of a timeline (if there is really no other post)

### Steps to Reproduce

1.  Create a folder and 
2.   save a post into it
3.  open folder
4. scroll down
5. keep scrolling
6. you can do it

### Actual Result:

Eternal repetition of the post

### Expected Result:

Display only one appearance of a post.

### Screenshots
I'm too shy

### Platform Info

- Friendica Source:  git current DEV 12.0.01.2021
- PHP version: 7.4
- SQL version: MariaDB currenty Debian version

**Comment by MrPetovan** [comment]
> ### Screenshots
> I'm too shy

😄

**Comment by annando** [comment]
@hoergen can you check if this still is a problem?

**Comment by hoergen** [comment]
Seems to be solved. Tried a few different posts and didn't have that effect any more. Thanks for reminding  :+1:
