### ISSUE TITLE
Problem Updating Develop Version

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9784]
- [x ] I have searched open and closed issues for duplicates

### Steps to Reproduce

When I go into the admin page I see:

A new Friendica version is available now. Your current version is 2020.12-dev, upstream version is 2021.03-dev

I am running the develop release.  I used the steps outlined on the community forum to update:

cd path/to/friendica
git pull
bin/composer.phar install --no-dev

cd path/to/friendica/addon
git pull

Actual Result:

When it finished it still gives the same message on the admin page as if no update has taken place.

Expected Result:

Expected to be on the newest version and no message telling me a newer version is available.

### Platform Info

Friendica Version:

Friendica Source: 
Github

PHP version:PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans

SQL version:
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by tobiasd** [comment]
Can you have a look into your admin panel for the version number that is displayed there?

The version from the repository is fetched by the background process. This is then compared to the local version when you call the admin panel. So if the version number of your local system is not updated to 2021.03-dev then there might have been a problem during the `git pull`. Maybe some local changes that would collide with the newly fetched code resulting in git stopping the updating process.

**Comment by 4nanook** [comment]
Actually, a PHP update today broke my PHP environment and php is randomly
core dumping so right now I'm going to chase that down before I continue to
troubleshoot friendica.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
After fixing my PHP environment, I did a git pull and it told me it would not overwrite index.php which it thinks I had changed.  I don't remember changing it, so I copied index.php to index.save and did a git reset --hard and then a git pull and then was able to finish the update.  After which I diff'd the index.php and index.save, there were changes but they weren't changes I made.

**Comment by 4nanook** [comment]
I'm all good now, so closing.
