### ISSUE TITLE
Blocking of reshares doesn't work

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9786]
## Bug Description

I tried to block a reshare (Diaspora) on user level and on admin level, but none of it worked.

### Steps to Reproduce

Philosophical answer: I can't reproduce, that is producing nothing.

### Screenshots

Imagine reshares, you don't want to have in your timeline

### Platform Info

Friendica Version: develop
Friendica Source: git
PHP version: 7.4
SQL version: mariadb latest.something(Debian)

**Comment by MrPetovan** [comment]
Did you block the reshared author or the resharer author?

**Comment by hoergen** [comment]
I blocked the reshared author.

**Comment by MrPetovan** [comment]
Thanks for the clarification!

**Comment by ghost** [comment]
@hoergen Is this this behavior that you mean?

[https://drive.google.com/file/d/1J4Qc6rK58AqNe38lGS7EBDOl_XT1le17/view?usp=sharing](url)

**Comment by ghost** [comment]
> I blocked the reshared author.

Is this this behavior that you mean?

https://drive.google.com/file/d/1J4Qc6rK58AqNe38lGS7EBDOl_XT1le17/view?usp=sharing

**Comment by hoergen** [comment]
@copiis  Maybe .. possible ... sorry but your  urls are blocked here. Why don't you share your information in here ?

**Comment by ghost** [comment]
The link led to a GIF.
I'll try to describe it.
After clicking on Block, you will be asked again for confirmation, then the corresponding post will be grayed out, but after the page has been refreshed, the post will be back.
Is that the behavior that you have too?

**Comment by hoergen** [comment]
No. As I described above someone reshared a post and I don't like to see the account this person reshared. So I blocked the "reshared account". Until now I didn't see a reshared post again from this person, but I don't know if there was something reshared ;) It is like Schrödingers Reshare ;)

**Comment by hoergen** [comment]
Deactivated Diaspora connector, so this bug report is irrelevant to me.
