### ISSUE TITLE
Add phone number (and it's privacy setting)

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9795]
### Is the feature request related to a problem? Please describe.

Contacts should be able to have a phone number. They already have an address so why not? :P

### Describe the feature you'd like

A way for a person to add (at least) one phone number and the ability to set it's privacy (Only Me, Friends, Followers, etc)

### Additional context
I'd like to eventually add an easy way for someone to browse it's contact and see their contact info IRL. Could be one of many steps to add CardDav sync eventually?

**Comment by MrPetovan** [comment]
This is already available with the Custom Profile Fields. However, private profile fields will not be accessible to anyone not using Friendica as we don't have a way to authenticate them when viewing your profile.

We have removed several overly-specific profile fields in favor of the Custom Profile Fields feature, and the reason we are keeping the detailed (but optional) address fields is to offer location-based profile search on Friendica directories. See for example this search on a locality on the official Friendica directory instance: https://dir.friendica.social/search?field=locality&q=Seattle

**Comment by Extarys** [comment]
Interesting.

To make sure, custom fields only appear/work on friendica instances then? (Which is awesome no matter what)

I guess the phone number and other specific information could be implemented only on the front-end and make the process use a custom field in the background. My main goal was to eventually add the option on the contact page to list phone numbers and addresses of friends and family members.

I guess we can revisit this eventually(TM)

I will let you close this issue in case there is something to add or, whatever :smile:

**Comment by MrPetovan** [comment]
> To make sure, custom fields only appear/work on friendica instances then? (Which is awesome no matter what)

No, only private custom fields are Friendica-specific. Public custom fields are available to anyone regardless of the software they use.

**Comment by Extarys** [comment]
Okay, thank you for the explanation.
