### ISSUE TITLE
Theme: frio: mobile: low prio: space below right sidebar does not apply background color

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9811]
In frio dark theme on mobile the space below the right sidebar does not apply background color and is displayed in white. This looks especially odd for dark and black theme.

Expected: should have same background color used in rest of theme.

![white space](https://user-images.githubusercontent.com/5708172/104837645-31ef7180-58b6-11eb-96d7-cb0871afb1c9.png)

**Comment by Extarys** [comment]
Might have been fixed with #9806 

I'll continue to test. I also found the background of the right side bar is not dark on dark theme:
![image](https://user-images.githubusercontent.com/11581433/105102885-9577cb80-5a7d-11eb-9afd-26af9432a78c.png)

**Comment by Extarys** [comment]
How does that look:
![image](https://user-images.githubusercontent.com/11581433/105109861-6405fc80-5a8b-11eb-8624-4203b4b70cbe.png)
