### ISSUE TITLE
'Tag Cloud' is throwing DB error 1052 - column 'private' is ambiguous

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9814]
- [X] I have searched open and closed issues for duplicates

### Bug Description
Looks like the additional feature 'Tag Cloud' is causing a database error because there is an ambiguous column 'private' in where clause. 

```
index [ERROR]: DB Error {"code":1052,"error":"Column 'private' in where clause is ambiguous","callstack":"DBA::p, TagCloud::tagadelic, TagCloud::getHTML, Widget::tagCloud, Status::content, Index::content, call_user_func, Page::initContent","params":"SELECT `name`, COUNT(`name`) AS `total` FROM `tag-search-view` LEFT JOIN `item` ON `tag-search-view`.`uri-id` = `item`.`uri-id` WHERE `tag-search-view`.`uid` = XX AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND `private` != 1 AND `item`.`wall` AND `item`.`owner-id` = 1139 GROUP BY `name` ORDER BY `total` DESC LIMIT 50"} - {"file":"Database.php","line":662,"function":"p","uid":"3b3f6a","process_id":156257}
```
I masked the UID of the user.

### Steps to Reproduce
I don't use the feature myself. But maybe it's enough to activate it and watch the Friendica log.

1.  enable additional feature 'tag cloud'
2.  use it (I don't know how. It is just there. Isn't it?)
3.  watch your log, grep for DB errors

### Platform Info
Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
According to my log it is not fixed. I'm still getting the same DB error every couple of seconds.

I guess we need to reopen it.

**Comment by annando** [comment]
Please ensure that the worker process who reported this hadn't been some old one. Also please copy the error message here, since it can't be totally identical.

**Comment by AlfredSK** [comment]
This is the last error from just now. 

``
2021-01-18T09:43:10Z index [ERROR]: DB Error {"code":1052,"error":"Column 'private' in where clause is ambiguous","callstack":"DBA::p, TagCloud::tagadelic, TagCloud::getHTML, Widget::tagCloud, Status::content, Index::content, call_user_func, Page::initContent","params":"SELECT `name`, COUNT(`name`) AS `total` FROM `tag-search-view` LEFT JOIN `post-view` ON `tag-search-view`.`uri-id` = `post-view`.`uri-id` WHERE `tag-search-view`.`uid` = 2913 AND `post-view`.`visible` AND NOT `post-view`.`deleted` AND NOT `post-view`.`moderated` AND `private` != 1 AND `post-view`.`wall` AND `post-view`.`owner-id` = 496302 GROUP BY `name` ORDER BY `total` DESC LIMIT 50"} - {"file":"Database.php","line":662,"function":"p","uid":"571006","process_id":1110992}
``

This error is thrown like 5 times per minute.

**Comment by AlfredSK** [comment]
Also, my PHP log is flooded with this...

``
[18-Jan-2021 09:35:35 UTC] PHP Notice:  A non well formed numeric value encountered in /var/www/html/libranet/src/Core/PConfig/PreloadPConfig.php on line 76
``

**Comment by AlfredSK** [comment]
Running the worker manually from command line works w/o any error output.

**Comment by AlfredSK** [comment]
Another related thing:
The info bubbles about new items on network and home icon are showing crazy values from time to time. And then they are changing all of a sudden.

Example: Network shows ~8000 new items. Then when page is refreshed it shows ~200.
Some time later I refresh the page again. Up to ~3000 new items. Another refresh down to ~100.

**Comment by annando** [comment]
Concerning the numbers I think that PR https://github.com/friendica/friendica/pull/9816 will help. And this other thing is something that I will have a look at as well.

**Comment by AlfredSK** [comment]
Uh! Oh! The number of posts and comments reported on the-federation.info (via nodeinfo) has skyrocket. What the...

![grafik](https://user-images.githubusercontent.com/3656054/104953144-27240200-59c6-11eb-99c7-f7fd30ccda7b.png)

https://the-federation.info/node/libranet.de

**Comment by AlfredSK** [comment]
Maybe it will get back to normal values. Let's see...

**Comment by AlfredSK** [comment]
All problems fixed. Comments reappeared. DB errors gone. Node stats back to normal. 🚀🎉
