### ISSUE TITLE
Twitter reshare is not shown under my profile's status tab

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#9817]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When resharing (not quote sharing) a Twitter post, it is not shown under the Status tab of my profile. This is the case for reshares of other networks (e.g. Friendica, Mastodon).

### Steps to Reproduce

1. Click reshare on a Twitter post
2. Browse to Status page of my profile (https://libranet.de/profile/wiwiec/status)

Actual Result:

The Twitter post is not shown on my status apge

Expected Result:

The Twitter post is shown on my status page

### Platform Info

Friendica Version:

> This is Friendica, version 2021.03-dev that is running at the web location https://libranet.de. The database version is 1389/1389, the post update version is 1384/1384.

PHP version:

PHP 7.4

SQL version:

MariaDB 10.3

**Comment by foss-** [comment]
This is likely obsolete due to Twitter addon deprecation.
