### ISSUE TITLE
Two notifications for some likes

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9820]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When someone likes one of my posts I frequently get two notifications about it. I 'quote reshared' a Diaspora post. When one user likes my post I see an info bubble showing "2" on the home/house icon. And at .../notifications/home I have two identical entries for the same 'like'.

### Steps to Reproduce

1.  find someone who likes your content
2.  observe your home icon, watch the info bubble there
3.  go to .../notifications/home
4.  count the lines per received 'like'

Actual Result:
Two notifications per 'like' at .../notifications/home
Info bubble shows "2"

Expected Result:
One notification per 'like' at .../notifications/home
Info bubble shows "1"

### Platform Info

Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
Is this still current after the latest changes?

**Comment by AlfredSK** [comment]
I haven't had it lately. Will check later. Maybe it was some temporary side effect.

**Comment by AlfredSK** [comment]
Problem is i need to find someone who likes my content. :-) ... will do it on my own then.

**Comment by MrPetovan** [comment]
If you were posting anything, I would like it, but you are not showing in my feed.

**Comment by AlfredSK** [comment]
Yeah I'm not the chatty type. ;-)

**Comment by AlfredSK** [comment]
Look! I posted something provocative.

https://libranet.de/display/0b6b25a8-1460-09f7-66d7-3c7927892875

**Comment by AlfredSK** [comment]
Looking good.

![grafik](https://user-images.githubusercontent.com/3656054/105417298-b1c16700-5c3b-11eb-9ce6-d9d7169c6aec.png)
