### ISSUE TITLE
Navigation broken on smartphone

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9827]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Since the last CSS changes, on my smartphone the top panel navigation is broken, the icons invisible or misplaced, I am not sure.

### Steps to Reproduce

Test it with chromium (or other browser) dev tools. Mobile M and Mobile S seem to be affected. (width < 383px)

Actual Result:
 
the icons / buttons are not there 
edit: they seem to be above the orange text "Neueste Beiträge"

Expected Result:

they should be there

### Screenshots

![navbar](https://user-images.githubusercontent.com/5753419/105176153-26ee4880-5b25-11eb-8843-0cadd0a8cbe3.jpg)

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2021.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1392/1392 und die Post-Update-Version 1384/1384."

**Comment by MrPetovan** [comment]
Paging @Extarys

**Comment by Extarys** [comment]
Found the issue, should be fixed soon.

Thanks for the report and sorry that this happened.

**Comment by Extarys** [comment]
The offcanvas really need a redo. The right menu on small screen cannot be scrolled (not introduced by my PR)
![image](https://user-images.githubusercontent.com/11581433/105184197-132eec00-5afd-11eb-91ea-e8e658ddc8a0.png)

On small screens the topbar now shows properly in my tests:
![image](https://user-images.githubusercontent.com/11581433/105184306-348fd800-5afd-11eb-95fb-0b867e909b1f.png)

I'll make a PR. :smile:
