### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [friendica/friendica#9834]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by MrPetovan** [comment]
[We've talked about this in the past](https://github.com/friendica/friendica/issues/1553#issuecomment-355725772) and didn't find a sufficient reason to go forward with the account type change, can you please explain your motivations for submitting this suggestion?

**Comment by Extarys** [comment]
Does organisation allow more flexible permission options for contributors? If with this I can assign myself to some UI issues for example and tag UI/UX stuff, I'm all for it!

But if it's a headache and might break things, don't touch it lol.

**Comment by MrPetovan** [comment]
It looks like I'm able to assign you to issues you commented on. For now, please add a comment on the issues you plan on tackling for this release and I'll assign them to you and put them on the milestone.

**Comment by Extarys** [comment]
I appreciate it @MrPetovan

**Comment by Neustradamus** [comment]
Thanks @Extarys and @MrPetovan for your reply! :)

@friendica: I think that the best solution is (in few minutes):
- Change your username to friendicaaccount (or other): https://github.com/settings/admin
- Few second after, create friendica organization: https://github.com/organizations/new

And:
- Transfer friendica into friendica org: https://github.com/NEWACCOUNTUSERNAME/friendica/settings
- Other repos too (linked to friendica project)

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

cc: @fabrixxm, @tobiasd, @Rudloff, @annando, @AlfredSK, @snd1, @hoergen, @AndyHee.

**Comment by annando** [comment]
I don't have enough permissions doing so. I guess only @tobiasd is able doing so.

**Comment by Extarys** [comment]
@Neustradamus It's nice and all but like @MrPetovan said, what would be the advantage? I guess one of them is having multiple "admins" in case one of them gets abducted by a "rival" federation project but other than that I am still confused.

**Comment by Neustradamus** [comment]
It will be more legal, better management, etc.
There will be no breaks.

I can do in few minutes, if you take me the possibility.

I have done for several projects without problems.

**Comment by tobiasd** [comment]
For all I'm concerned the organization page is at https://git.friendi.ca/friendica as we had the plan to migrate off. If you now decide to drop that plan then please say so (and yes I know the migration is slow for various reasons).

**Comment by Neustradamus** [comment]
What migration?

The first step is to do the changes in GitHub, it can be done in few minutes, I can do it if I have access.
I have already done for several.

After you can do the migration that you want.

**Comment by annando** [comment]
@Neustradamus on a longterm or midterm we are planning to move away from Github to our own repository.

**Comment by Neustradamus** [comment]
Ok, there will be no problem with a mirroring like several organizations/projects :)

But the question is when we do the changes here, I recall, I can do it in few minutes.

**Comment by Extarys** [comment]
@tobiasd Gitea! :heart_eyes: Thanks for the link I'll save it.

Yeah instead of mirroring github to gitea, I think we should do the inverse. Mirror gitea repo to github.

Gitea worked hard in 2020 and we now have kabanboard (is that how they are called?) :angel: Anyway, I hate microsoft but I also don't want you guys to spend hours trying to migrate when you could just code and fix bugs. Migrate when you're ready.

Edit: typos

**Comment by annando** [comment]
@Extarys currently we do have a problem with the tests. I guess that's what is limiting us now.

**Comment by Neustradamus** [comment]
User account to Organization account is very easy, in few minutes and without breaks.

After it, no problem to use Gitea and to create a mirroring.

**Comment by MrPetovan** [comment]
We hear you, we just have a slight credentials problem, only one person has the keys to @friendica, so if they aren't going to do it, it won't happen.

**Comment by tobiasd** [comment]
I really don't see the point in migrating it here on github to an organization (where then the same people will have admin rights to the settings because I had distributed those to some people to increase the Bus-factor that they forget it later on may decrease the bus factor again as we now see...).

AFAIK we want to quit github, more sooner then later. There is/was (?) that performance problem with the Drone IO CI server. So why should there any more work then needed spend into this? If you guys want to stay on github say so, then utzer can close the other VMs for the stuff he is hosting.

**Comment by Neustradamus** [comment]
@tobiasd: Better to manage the organization with your personal account instead of fake account.
And for the mirror will work too...

**Comment by Neustradamus** [comment]
9 months after, there is a progression?

**Comment by tobiasd** [comment]
Yes, only a few repositories are left active on github. The others have been moved to our gitea server managed by an organization account.

**Comment by Neustradamus** [comment]
@tobiasd: Thanks for your reply!

But it is possible to migrate the github personal account to organization?

**Comment by MrPetovan** [comment]
No, this is out of the question now that the migration to our own Gitea server is underway.

**Comment by Neustradamus** [comment]
Hi all,

I think that you have changed plan, it is possible to migrate the personal account to organization?

**Comment by MrPetovan** [comment]
The plan holds, we just had to figure out a way to have our Continuous Integration pipeline work both in GitHub before the move and in Gitea after the move.

I believe @nupplaphil managed it so we should be good to migrate now.

**Comment by nupplaphil** [comment]
Except for the docker images, everything else is ready :-)

I just need a oauth2 token of the gitea repo and a date

**Comment by Neustradamus** [comment]
Dear @friendica team,

Have you progressed on my request?
Migration of the personal account to organization like others?

**Comment by MrPetovan** [comment]
In a way. We're almost there with the migration off GitHub to Forgejo. We just hit a snag migrating the issues and have reported the bug with the upstream project. I don't expect any change will be made to the GitHub account itself.

**Comment by Neustradamus** [comment]
Dear @friendica team,

Have you progressed on my request?
Migration of the personal account to organization like others?

**Comment by tobiasd** [comment]
The organization is located at https://git.friendi.ca/friendica however a upstream problem in gitea prevents final movement of this repository.

**Comment by Neustradamus** [comment]
@tobiasd: Maybe but it does not solved the problem of this personal account which must be converted into organization.

**Comment by MrPetovan** [comment]
There's absolutely no problem with this, and as we said we are leaving the GitHub account behind as soon as we can, which makes this "issue" and renewing the conversation about it moot.

**Comment by Neustradamus** [comment]
Dear @friendica team,

Any news about it?

**Comment by Neustradamus** [comment]
Dear @friendica team,

I wish you a Happy New Year 2024!

**Comment by Neustradamus** [comment]
Dear @friendica team,

Have you progressed on my request?

Thanks in advance.
