### ISSUE TITLE
Time to detach from the original code

### ISSUE THREAD

**Issue by Neustradamus** [friendica/friendica#9835]
It is possible to detach this fork from the original source?
- https://support.github.com/contact?tags=rr-forks

It will be better to search in code etc.

cc @duthied.

**Comment by MrPetovan** [comment]
Hi, [we've talked about this before](https://github.com/friendica/friendica/issues/1553#issuecomment-355488307), I'm not sure where we stand on this topic.

**Comment by Neustradamus** [comment]
Dear @friendica team,

Have you progressed on it?

**Comment by tobiasd** [comment]
Please have a look into the upstream issue of gitea to move large repositories from gh including the history of PRs and issues. When this is fixed we can move from gh leaving behind it's bogus information in this regard.

**Comment by Neustradamus** [comment]
Dear @friendica team,

Any news about it?

**Comment by Neustradamus** [comment]
Dear @friendica team,

Have you progressed on my request?

Thanks in advance.
