### ISSUE TITLE
Autofollowed nicknames

### ISSUE THREAD

**Issue by Singh-in** [friendica/friendica#9842]
### Is the feature request related to a problem? Please describe.

no

### Describe the feature you'd like

When a new user registers, it should be possible to store a nickname that automatically follows each new user.
This can be an admin or another person who takes over tasks on the platform. 

This automatic follower serves, for example, as a contact person for questions, problems or observes whether the new user behaves on the platform in accordance with the terms of use.

### Describe alternatives you've considered

no

### Additional context

**Comment by MrPetovan** [comment]
This is related to #7795 

However, I don't think it is nearly as useful in this direction. Public posts already are available in the community page for observation, and private posts are, well, private.

For contact point, automatic follow like in #7795 sounds more intuitive.

**Comment by Extarys** [comment]
The client can suggest the new user tags and peoples to follow. Like a card on the side or a modal greeting the user with a per-determined, configurable list with a button on the side of each for easy follow.

Like we can see here [#7795 (comment)](https://github.com/friendica/friendica/issues/7795#issuecomment-549141367). (Reading the discussion there it seems there is already a plugin that could be extended)

**Comment by Singh-in** [comment]
I think the suggestion under # [7795](https://github.com/friendica/friendica/issues/7795#issuecomment-549141367) is good. Therefore I close this
