### ISSUE TITLE
Mastodon posts not rendering images properly

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9846]
- [x] I have searched open and closed issues for duplicates

I looked for `embed` and `mastodon`. I hope I didn't spam the repo.

### Steps to Reproduce

[See this post](https://nerdica.net/display/52acf9cd-bed06e765fcfc28c-92e8eb82).

(I'm concerned about privacy but I guess if you can see it it's because the post is public)

**Actual Result:**

The post on friendica contain html code.

**Expected Result:**

Not seeing html tags, `<>`.

### Screenshots

Friendica result:
![image](https://user-images.githubusercontent.com/11581433/105428113-ad398600-5c1c-11eb-8b05-830237ccdfd4.png)
![image](https://user-images.githubusercontent.com/11581433/105427793-ede4cf80-5c1b-11eb-8c29-7fa947f0cc47.png)

Mastodon result:
![image](https://user-images.githubusercontent.com/11581433/105427816-fa692800-5c1b-11eb-8fb9-0c76e6a0fac2.png)

### Platform Info

Friendica Version: 2021.01

This is Friendica, version 2021.01 that is running at the web location https://nerdica.net. The database version is 1384/1384, the post update version is 1383/1384.

Friendica Source: Unknown

PHP version: Unknown

SQL version: Hmm, I'm confused. 1384 or 1383? DB server is unknown.

**Comment by MrPetovan** [comment]
Found the issue, we replace hashtags inside of image descriptions.
