### ISSUE TITLE
Themes: frio: secondary menubar: move dropdown indicator to the left and add text to compose button

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9856]
Dropdown indicator should be next to the dropdown option.

That would also free up space to increase size of the "New Post" button (currently lacking text).

![frio mobile item order](https://user-images.githubusercontent.com/5708172/105612755-4227b500-5dbe-11eb-843e-babe35596f9e.jpeg)

**Comment by Extarys** [comment]
Thanks! That is a good suggestion. That arrow always get to me.
