### ISSUE TITLE
cancel photo deletion throws error

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9871]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When dropping / deleting a photo you are asked "Are you sure?". When clicking `cancel`, an error message appears.

### Steps to Reproduce

1. click on the trash bin icon of a photo
2. "Are you sure?" - question appears
3. choose `cancel`

Actual Result:

blank page with: {"error":"Keine Dateien hochgeladen."}

Expected Result:

redirect back to single photo page 

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2021.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1394/1394 und die Post-Update-Version 1384/1384."

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by haheute** [comment]
Now, when I click `Foto löschen` (delete photo) or `Abbrechen` (cancel), the same error appears. So it seems, I can't delete photos.
(`https://libranet.de/photos/xy/image/163132209360923b54c6fa1692154431/drop`)
