### ISSUE TITLE
Friendica api return various document type and responses

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9872]
- [x] I have searched open and closed issues for duplicates

### Bug Description

API endpoint for friendica currently doesn't return either a json value or a standardized response.

### Steps to Reproduce

1.  Like a post, subscribe to a thread or star a post
2. Check the response in the Network tab

Actual Result:

#### Returns

--------------
200

HTML Page

#### Returns

--------------
200

```
{status: 'OK'}
```

#### Returns

--------------
200

1 (or) 0

Expected Result:

A valid json response containing the status of the request and the current state of the action

```
{
    status: 'ok',
    post_id: '17',
    verb: 'like',
    state: 1
}
```

### Platform Info

Friendica Version:

2021.03-dev

**Comment by Extarys** [comment]
Mastodon API for:
[Bookmarks](https://docs.joinmastodon.org/methods/accounts/bookmarks/)
[Favorites](https://docs.joinmastodon.org/methods/accounts/favourites/)

@annando The mastodon API for starred (or is it like?) only support GET request to get favorites posts. It doesn't seem to support POST.

Is there another documentation you could link here when we work on this? Maybe I just didn't read the right api documentations.

**Comment by annando** [comment]
The documentation is the correct one. What is the problem with GET here?

**Comment by MrPetovan** [comment]
I assume that they would like the API endpoint we use to star or like a post. I don't think we list it in the API documentation since it's only used in the Friendica themes.

**Comment by Extarys** [comment]
@annando the api from mastodon, from what I can see, is only to get (retrieve) the information, not to set it in the database.

**Comment by annando** [comment]
The setting is done here: https://docs.joinmastodon.org/methods/statuses/

**Comment by MrPetovan** [comment]
Do we support the Mastodon's API `v1/statuses/:id/favourite` endpoint?

**Comment by annando** [comment]
At some time in the future we should. But I could imagine that we could start with basic auth there as well. Then we could implement those endpoints as well.

**Comment by Extarys** [comment]
Since the current themes don't read the responses of the current endpoints, can we modify those responses to return a proper json object? Would be faster/simpler for now until auth is implemented and all.

**Comment by MrPetovan** [comment]
Absolutely.

**Comment by MrPetovan** [comment]
@Extarys What is the `state` return key supposed to be? We return HTTP error codes when a request fails, not a fully-formed response like the one you suggested.

**Comment by MrPetovan** [comment]
Nevermind, I found my answer with the `item/{id}/ignore` module that allows to toggle the ignore status of a thread, the `state` is the actual value being set for the `ignore` verb.

**Comment by MrPetovan** [comment]
I've now normalized the following frontend API endpoints:
- `POST item/{id}/follow`
- `POST item/{id}/ignore`
- `POST item/{id}/pin`
- `POST item/{id}/star`
- `POST item/{id}/activity/{verb}`

When called without a `return` request parameter, they will output the following structure:
```
{
  "status":"ok",
  "item_id":13666,
  "verb":"pin",
  "state":0
}
```

**Comment by Extarys** [comment]
Can I kiss you? :open_mouth: 

Thank you very much @MrPetovan !
(Sorry been busy)

**Comment by Extarys** [comment]
Woops I closed but I forgot about the subthread endpoint. Should be left open for now I guess

**Comment by MrPetovan** [comment]
Yes please, I'll update this issue's status once it's merged. Feel free to gather the list of the next endpoints you'll need normalized, I'm sure these weren't the only one you're eyeing at using.

**Comment by MrPetovan** [comment]
The last PR in this issue has been merged, which completes it.
