### ISSUE TITLE
Embedded rich content doesn't show

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#9875]
- [x] I have searched open and closed issues for duplicates

### Bug Description

When OEmbed rich content is enabled (globally or by whitelist) it doesn't show in some cases.
Discussion: https://forum.friendi.ca/display/d8230ed6-1660-1038-312d-f36036758955

### Steps to Reproduce

1.  Make post with a link

Example links:
https://blog.mrpetovan.com/review/video-game/love-letter-to-euro-truck-simulator-2-from-confinement/
https://open.audio/library/tracks/242/
https://soundcloud.com/garryknight/remembering

Actual Result:
https://friends.deko.cloud/display/d0446be5-5860-13ac-0025-0fb443865797
https://friends.deko.cloud/display/d0446be5-1660-13ac-3db8-ad1749264410
https://friends.deko.cloud/display/d0446be5-1560-13ac-7fdd-ea0345004472
If I look at source code in the browser it shows iframe as empty.

Expected Result:

Not an empty rectangle :)

### Platform Info

2021.03-dev, git (also happens on stable)

**Comment by MrPetovan** [comment]
It is possible that iframes are filtered out by the HTML sanitizer we have been adding to the BBCode to HTML converter. Not sure why it would show on one system but not the next.

**Comment by AlfredSK** [comment]
The difference in behavior seems to be related to the node's oembed setting in admin panel -> policies.
When oembed is allowed it doesn't work. Fetching the preview w/o oembed seems to work.

**Comment by AlfredSK** [comment]
Example: On my node oembed is off - with exceptions for Vimeo and Soundcloud.
So, the preview for @MrPetovan blog post works (oembed off). But the Soundcloud preview/player doesn't work (oembed on).

**Comment by hellquist** [comment]
Hi! Just to add that I experience something similar and/or the same (I'm not well versed enough yet to do fine-tuned error reports on the platform).

Basically my post, which is a simple one line of text, two linebreaks followed by a link to an article (in this case on New York Times) look great when composing the message, with preview image, headline and text excerpt from the article.

<img width="371" alt="friendica_write_post" src="https://user-images.githubusercontent.com/2326590/106963334-b78d7100-6740-11eb-9fbb-937382944454.png">

However when posting, or even when viewing the message before posting in the preview tab, the image is completely gone, the link remains, the headline remains but the text excerpt from article is gone.

<img width="371" alt="friendica_preview_post" src="https://user-images.githubusercontent.com/2326590/106963372-c8d67d80-6740-11eb-86d1-915a382a8132.png">

This is a link to my post I wrote earlier today describing this, with screenshots: https://friendica.feneas.org/display/76158462-1260-1c6d-edd5-808276395566

As I'm not a server admin or similar I am possibly describing this incorrectly, or am confused over if it belongs here at all. If so I apologize.

**Comment by xanathon** [comment]
I also had the oembed problem and no one was able to resolve it. From what I learned it is a years old bug that was never fixed.

**Comment by tiotrom** [comment]
Same here. I then disabled oembed and videos seem to work + some thumbnails. But not other thumbnails...idk is weird. Like look here at tens of examples https://social.trom.tf/profile/trom

**Comment by SpcCw** [comment]
> I also had the oembed problem and no one was able to resolve it. From what I learned it is a years old bug that was never fixed.

This particular problem is relatively new, it certainly worked in before. Another issue referencing it: https://github.com/friendica/friendica/issues/9962

**Comment by SpcCw** [comment]
Seems to work right now. Closing the issue.

Thanks, Friendica overlords!
