### ISSUE TITLE
Installation of Friendica 2021.03-dev fails because postupdates to the DB have not finished

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#9885]
### Bug Description

The installation of Friendica 2021.03-dev from git fails with the following error message

> Updates from postupdate version are not supported. Please update at least to version 2021.01 and wait until the postupdate finished version 1383.

### Steps to Reproduce

1.  Install a fresh 2021.03-dev version of Friendica

Actual Result:

Error message is displayed.

Expected Result:

The installation to work with the correct, empty database structure.

### Platform Info

Friendica Version: 2021.03-dev from git

**Comment by tobiasd** [comment]
Installation (in a Debian 10 VM) worked for me. @annando did you fix something in the code but forgot to close the issue ;-) ?

**Comment by annando** [comment]
I have the feeling as if I fixed this while fixing another issue.

**Comment by tobiasd** [comment]
Installation with 2daa783f151b6afce7624bfab775b3438f1e78e0 worked hence I'm closing this ticket.
