### ISSUE TITLE
Page jumps back to top gradually

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9886]
- [X] I have searched open and closed issues for duplicates

### Bug Description
The pages containing post items like network or community are jumping back to the top of the page step by step. The only thing you need to do to see the behavior is watching the page. **This happens only because the content is refreshed after some seconds - not because new content is loaded.**

I've checked that e.g. on the Friendica community node by visiting the community page https://forum.friendi.ca/community All you need to do to reproduce this is visiting the page, scroll down a couple of posts, wait and watch. After some minutes you're back at the top of the page.

This is very inconvenient. Users are losing their reading position on the page because of that. Also, it is confusing.

There is a "workaround". If the user has enabled the display setting "automatic updates only at the top of the post stream pages" it doesn't happen. But this works only when the user is logged in. It doesn't work for visitors.

**Additional info:** Looks like this only happens with Firefox but not with Chromium. 🤔

### Steps to Reproduce

1.  visit e.g. https://forum.friendi.ca/community
2.  scroll down maybe 5-10 posts
3.  wait and watch the page
4.  the page gradually jumps back to top

**Actual Result:**
The pages are gradually jumping back to top w/o any interaction by the user and also when no new content is loaded into the stream.

**Expected Result:**
The pages should **always** stay fixed on the users/visitors reading position.

### Platform Info

Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

Browsers tested:
Firefox 85, Chromium 88

**Comment by foss-** [comment]
Unable to reproduce on
* iOS 14.4, Firefox 30 (3279), pirati.ca, frio
* macOS 10.15.7 (19H114), Firefox 85, pirati.ca, frio

Is there some setting that needs to be active for the problematic behavior to show? Had network page open after scrolling down a good bit. No reloading, location not changing, waited 5 minutes, no dice.

This is Friendica, version 2021.03-dev that is running at the web location https://pirati.ca w frio theme. The database version is 1396/1396, the post update version is 1384/1384.

**Comment by AlfredSK** [comment]
Hmm. Another user had confirmed it yesterday, but today I can't reproduce it anymore. Weird.

**Comment by AlfredSK** [comment]
I'll check the behavior again later today. It's weird I cannot reproduce it myself now. I'll close it when don't find something...

**Comment by AlfredSK** [comment]
Cannot reproduce anymore. Good. Whatever. Closing. :-)
