### ISSUE TITLE
forced track user

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#989]
a user follows me. but I can not say I follow. 

"You've already presented here."

force as I can follow?. Previously I had to delete the user I'm trying to follow. And now I want to follow again

but the system does not allow me to do?. has console commands forced to track user?

**Comment by annando** [comment]
We changed the connection method for contacts. So this shouldn't be a problem anymore.

**Comment by MrPetovan** [comment]
Closed until further notice.
