### ISSUE TITLE
[twitter] link in post unclickable / only shown as text

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9895]
### Bug Description

This Tweet https://twitter.com/bellingcat/status/1355855703718715393 seen on friendica https://pirati.ca/display/a6551d713c3a5092853484e5862236837b2f2242 results in a post with unclickable link.

### Steps to Reproduce

Visit https://pirati.ca/display/a6551d713c3a5092853484e5862236837b2f2242

Actual Result:

Post shows as `Navalny Poison Squad Implicated in Murders of Three Russian Activists https://t.co/PsRY8ZZ7g3`
and URL is not shown as link.

For the tweet it seems twitter converts the actual link https://www.bellingcat.com/news/uk-and-europe/2021/01/27/navalny-poison-squad-implicated-in-murders-of-three-russian-activists/ to https://t.co/PsRY8ZZ7g3?amp=1 which then forwards to the actual  link.

For some reason friendica does not display the link as URL.

Expected Result:

Links should be clickable. Ideally an article preview should also be displayed. Maybe this is not working due to twitter adding another laying and friendica not being able to display previews for links forwarding to another link.

### Screenshots

<img width="693" alt="friendica post" src="https://user-images.githubusercontent.com/5708172/106385643-9db2fd80-63d1-11eb-9d43-32224cb75840.png">
<img width="621" alt="tweet" src="https://user-images.githubusercontent.com/5708172/106385654-ad324680-63d1-11eb-84b2-f0291ba2864a.png">

### Platform Info

Friendica Version: This is Friendica, version 2021.03-dev that is running at the web location https://pirati.ca. The database version is 1396/1396, the post update version is 1384/1384.

**Comment by MrPetovan** [comment]
Yep, I can confirm, we've been treating Twitter post-ending link differently, I suppose to to add a link preview, but it doesn't seem to work correctly.

**Comment by MrPetovan** [comment]
This issue relates to OEmbed. There were various conditions making OEmbed result invalid, which would make us skip parsing the link.

A double-part fix is on the way.
