### ISSUE TITLE
No notifications any more for comments and selected users

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9896]
Since about a week or maybe more I don't get notifications any more on comments and users I configured to get notifications, when they post a message.

I still get notifications for contact requests and direct messages.
And I can manually check all notifications here  `https:///Friendica-Server-URL/notifications/home?show=all`

### Steps to Reproduce

Clone my Friendica server ;) 

### Screenshots

![grafik](https://user-images.githubusercontent.com/24474762/106388166-8c6fee00-63dd-11eb-9530-334f1e0fa5ee.png)

### Errors
PHP log

```
[30-Jan-2021 12:10:45 UTC] PHP Fatal error:  Uncaught Error: Class 'Type' not found in /FRIENDICA/htdocs/addon/public_server/public_server.php:115
Stack trace:
#0 /FRIENDICA/htdocs/src/Core/Hook.php(217): public_server_enotify()
#1 /FRIENDICA/htdocs/src/Core/Hook.php(193): Friendica\Core\Hook::callSingle()
#2 /FRIENDICA/htdocs/include/enotify.php(461): Friendica\Core\Hook::callAll()
#3 /FRIENDICA/htdocs/include/enotify.php(692): notification()
#4 /FRIENDICA/htdocs/include/enotify.php(603): check_item_notification()
#5 /FRIENDICA/htdocs/src/Model/Item.php(1202): check_user_notification()
#6 /FRIENDICA/htdocs/src/Protocol/ActivityPub/Processor.php(636): Friendica\Model\Item::insert()
#7 /custom/ in /FRIENDICA/htdocs/addon/public_server/public_server.php on line 115
[30-Jan-2021 12:14:27 UTC] PHP Fatal error:  Uncaught Error: Class 'Type' not found in /FRIENDICA/htdocs/addon/public_server/public_server.php:115
```

And this: 

`not writable, please chmod to 775 in /wwwverzeichnis/htdocs/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297`

There is "some" information about that here https://github.com/stevebauman/purify/issues/20

### Platform Info

- Friendica Version: current develop 2021.03-dev Die Datenbankversion ist 1396/1396 und die Post-Update-Version 1384/1384.
- Friendica Source:  git
- PHP version: 7.4
- SQL version: MariaDB current Debian

**Comment by hoergen** [comment]
There is as well a delayed queue with lot of `wall-new` messages. Maybe this has something to do with it?

**Comment by blackandred** [comment]
```
[30-Jan-2021 12:10:45 UTC] PHP Fatal error:  Uncaught Error: Class 'Type' not found in /FRIENDICA/htdocs/addon/public_server/public_server.php:115
```

It seems that some addon is failing. Try `composer install` or disabling such addon if it is possible - sorry I may be wrong, Im not very familiar with Friendica but actually just a PHP developer.

**Comment by hoergen** [comment]
With every git pull i also run `composer install --no-dev`  but I tried it again with and without --no-dev, but no change.
I doubt, that the public_server addon can be a problem because all other public servers should have the same problem. Currently there is only my server  affected.

I have the impression its the `not writable, please chmod to 775 in /wwwverzeichnis/htdocs/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297`

And I don't know how to fix that.

**Comment by blackandred** [comment]
Please show the whole file "public_server.php" or at least it's line 115 + first lines with `use` statements in the file header.

**Comment by hoergen** [comment]
It is this
https://github.com/friendica/friendica-addons/blob/develop/public_server/public_server.php

of friendica/addons https://github.com/friendica/friendica-addons

**Comment by hoergen** [comment]
~~Hmmm stumbled across that the friendica demon is not working any more. Some friendica update broke it.~~
forget it I resetup cronjob again weeks ago after I noticed, that demon doesnt work reliably

**Comment by hoergen** [comment]
I deactiveted the public_server addon like you said and it seems new notifications are incoming (had one).
Thanks a lot for the help, even I needed some time to be brave enough. :+1:

**Comment by MrPetovan** [comment]
I've fixed the `public_server` and `testdrive` addons here: https://github.com/friendica/friendica-addons/pull/1077
