### ISSUE TITLE
Broken instance url, instance unusable after upgrade from 2020.09 to 2021.01 [docker]

### ISSUE THREAD

**Issue by blackandred** [friendica/friendica#9899]
- [x] I have searched open and closed issues for duplicates

### Bug Description

After I upgraded instance from 2020.09 to 2021.01, then I got corrupted the database.
`system.url` in `config` table is getting an invalid URL `https://friendica.wprzemianie.pl/friendica.wprzemianie.pl` in effect all urls looks shitty and makes instance unusable - without js, css, images etc.

Every retry of changing this entry in database results in... reset after crontab task runs. So turn off the docker container, change entry in database, start container, then it is fine. After I run crontab job `./bin/worker.php` then it is back to broken url :facepalm: 

Also I get this error when running `./bin/worker.php`: https://github.com/friendica/friendica/issues/9747#issuecomment-771148871

### Steps to Reproduce

Possibly the issue could be specific to my instance, so I don't know exactly how I can describe the steps to reproduce. In my case it is simple, but I think you could have issues reproducing this.

1.  Run crontab job `./bin/worker.php`
2.  Check in the browser

Actual Result:

`system.url` is `https://friendica.wprzemianie.pl/friendica.wprzemianie.pl`

Expected Result:

`system.url` should be `https://friendica.wprzemianie.pl/`

### Screenshots

![image](https://user-images.githubusercontent.com/22807686/106517641-0e910d00-64d9-11eb-8b4a-6b30465ab25e.png)

### Platform Info

Friendica Version: 2021.01

Friendica Source: Docker

PHP version: 7.4

SQL version: MariaDB 10.4

**Comment by fabrixxm** [comment]
have you tried to run in terminal

    $ bin/console config system url https://friendica.wprzemianie.pl

?

edit: nevermind, I had missed the "Every retry of changing this entry in database results in... reset after crontab task runs." part.

**Comment by MrPetovan** [comment]
Can you please confirm the values of the following config keys:
- `config.hostname`
- `system.urlpath`
- `system.ssl_policy`

**Comment by blackandred** [comment]
```
www-data@1d631337110d:~/html$ bin/console config system url
system.url => https://friendica.wprzemianie.pl

www-data@1d631337110d:~/html$ bin/console config system urlpath
system.urlpath => friendica.wprzemianie.pl

www-data@1d631337110d:~/html$ bin/console config system ssl_policy
system.ssl_policy => 1

www-data@1d631337110d:~/html$ env|grep FRIENDICA|grep URL
FRIENDICA_URL=https://friendica.wprzemianie.pl
```

**Comment by MrPetovan** [comment]
Thanks, what about `config.hostname`?

**Comment by blackandred** [comment]
```
www-data@1d631337110d:~/html$ bin/console config system hostname
system.hostname => 

www-data@1d631337110d:~/html$ bin/console config hostname
Config section hostname returned nothing

www-data@1d631337110d:~/html$ hostname
1d631337110d

www-data@1d631337110d:~/html$ cat config/local.config.php |grep hostname
		'hostname' => 'mysql_database',
		'hostname' => '',
```

**Comment by MrPetovan** [comment]
The correct command is `bin/console config config hostname`.

**Comment by blackandred** [comment]
Sorry than. Thanks for immediate response :sunglasses: 

```
www-data@1d631337110d:~/html$ bin/console config config hostname
config.hostname => friendica.wprzemianie.pl
```

**Comment by fabrixxm** [comment]
```
www-data@1d631337110d:~/html$ bin/console config system urlpath
system.urlpath => friendica.wprzemianie.pl
```
this should be empty, i think..

**Comment by blackandred** [comment]
Thanks. It seems that it is fixed by:

1. `./bin/console config system urlpath ""`
2. Then via database query I set `system.url` (hex: 73797374656D and 75726C) to proper url `https://friendica.wprzemianie.pl/`

Verified by:
1. I ran `./bin/worker.php`
2. Checked in the browser

**Comment by blackandred** [comment]
Thank you very much for your time and your help. I hope this issue will help someone in case anybody would have such issue.

**Comment by fabrixxm** [comment]
I didn't read the code, so I don't know if has some impacts, but on my node 'system.url' is without the end "/"

**Comment by blackandred** [comment]
Sure, I will adjust then :smile:
