### ISSUE TITLE
"Contact not found" when blocking a stranger

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#9905]
Today I tried to block a stranger one of my contacts replied to.

The asynchronous `item/block/<item_id>` calls returned 404 Not Found with the message "Contact not found".

This came from this code:
```php
$item = Post::selectFirstForUser(local_user(), ['guid', 'author-id', 'parent', 'gravity'], ['id' => $args->get(2)]);
if (empty($item['author-id'])) {
	throw new HTTPException\NotFoundException('Item not found');
}

$cdata = Contact::getPublicAndUserContacID($item['author-id'], local_user());
if (empty($cdata['user'])) {
	throw new HTTPException\NotFoundException('Contact not found');
}
```
Friendica wasn't able to retrieve a user-specific contact id for the stranger and aborted. @annando What is the correct way of blocking a stranger?

**Comment by MrPetovan** [comment]
I still don't know how to handle this. @annando can you please help me?

**Comment by annando** [comment]
There is the `user-contact` table that does this job. And there is the model class `Contact\User` that contains the functions to block and unblock. It just needs any contact id.

**Comment by MrPetovan** [comment]
My code is the following:
```php
$item = Post::selectFirstForUser(local_user(), ['guid', 'author-id', 'parent', 'gravity'], ['id' => $args->get(2)]);
if (empty($item['author-id'])) {
	throw new HTTPException\NotFoundException('Item not found');
}

$cdata = Contact::getPublicAndUserContacID($item['author-id'], local_user());
if (empty($cdata['user'])) {
	throw new HTTPException\NotFoundException('Contact not found');
}

Contact::block($cdata['user'], DI::l10n()->t('Blocked on item with guid %s', $item['guid']));
```

Currently it blocks with `Contact not found`.

**Comment by MrPetovan** [comment]
I found `Contact\User::setBlocked` but I can't provide a reason, is this intended?

**Comment by annando** [comment]
Since it is only for personal blocking, I haven't considered sending myself a notice why I blocked someone.

Edit:
Concerning your code: Just provide the `author-id` to `Contact::User::setblocked` - that's really all.

**Comment by MrPetovan** [comment]
Ok thanks. I like the idea of leaving a personal note for a block, as it can be challenging to remember the reason for blocking a specific account even only one month after.

**Comment by annando** [comment]
Yeah, I guess that `Contact::block` is more for the public contacts.
