### ISSUE TITLE
[smileybutton] Unable to insert smilies by clicking on them

### ISSUE THREAD

**Issue by thystra** [friendica/friendica#9914]
When attempting to input a smiley via the smiley plugin/button on the post, clicking on the desired smiley does not insert it into the post.  Copy/past does work, however.  Mouseover should also indicate the smiley code required to manually input smiley into the post.  

Desired behavior is for the user to click on the smiley and have it inserted into the post.  This is on: Friendica 'Red Hot Poker' 2021.01 - 1384
Theme: Vier

Behavior occurs in Firefox and Brave browsers.

**Comment by MrPetovan** [comment]
Thank you for the report!
