### ISSUE TITLE
Registration Mail Issue

### ISSUE THREAD

**Issue by myprivacymatters** [friendica/friendica#9919]
Running 2021.01. Had everything set up and working when I realized that Friendica needed to be running on a subdomain. Reinstalled everything to a subdomain, but now, when I register, it never sends the initial email. I spoke with my hosting service that assures me I am whitelisted for PHP mail sending. They show no logs of any email requests being sent. I have deleted and reinstalled twice, thinking I may have a corrupted upload, but this does not appear to be the case. Any help would be appreciated.

**Comment by myprivacymatters** [comment]
As an aside, the problem also presents itself in previous version of Friendica.

**Comment by MrPetovan** [comment]
As a general rule, mail sending issues are unlikely to be related to Friendica itself. If anything we've had [trouble sending too many emails](https://github.com/friendica/friendica/issues/9561). Friendica uses the internal PHP `mail()` function that relies on the underlying system to send emails.

This means that if any other install can send emails, the Friendica is likely to work as expected, and the issue is likely to be on your hosting side. I understand you took steps to contact your hosting provider which is good, but they have a limited capacity to help you with this specific issue.

Can you please follow the instructions in this page to verify the `mail()` function works outside of Friendica? https://mediatemple.net/community/products/grid/360016044211/troubleshooting-common-issues-with-php-mail

**Comment by myprivacymatters** [comment]
I have confirmed that mail is working outside of Friendica. Multiple test messages sent and received with no issue from within both the root directory and the subdirectory using mail() function.

**Comment by MrPetovan** [comment]
Can you please try to reset the password of the account you created? This should send an email to the email address you submitted.

**Comment by myprivacymatters** [comment]
Therein lies the issue. Because I have never received the initial email with the original password, I have no ability to login to change anything. I will try the password reset function and see if it sends anything.

**Comment by myprivacymatters** [comment]
I tried the password reset and no joy. I might add that when things were working, I would receive a notification of registration and emails being sent via a popup. I am getting none of that. I am beginning to wonder if the issue isn't within the mail function, but the registration function. Perhaps no email i sent because I am not being created in the user database.

**Comment by MrPetovan** [comment]
Can you please verify the content of your "user" table in your database?

**Comment by myprivacymatters** [comment]
Empty results

**Comment by myprivacymatters** [comment]
Could be there is no permission to write to the database?

**Comment by MrPetovan** [comment]
Alright, so this rules out the mail issue, which is good. Database issues are usually easier to fix. First step is to check the database settings in `config/local.config.php`, namely the host name, the user name, the password and the database name.

**Comment by myprivacymatters** [comment]
Everything seems to match. I know I said this before, but the hostname is currently set to localhost....is this an issue?

**Comment by MrPetovan** [comment]
I don't know, it entirely depends on your hosting environment. On my RPS where I installed the database server on the same machine as my Friendica site is hosted, it is `localhost`, but on many hosting environments, particularly shared, the host name could be different.

**Comment by myprivacymatters** [comment]
I have sent a query and should hear soon.

**Comment by MrPetovan** [comment]
I don't think it would be that, after all it was working fine before. But we still need to make sure in the troubleshooting process.

**Comment by myprivacymatters** [comment]
So they have already responded and it is localhost,  which is how it appears in my local.config.php.

**Comment by MrPetovan** [comment]
Wow, that was quick. The next step would be to try to register again, see if it works, and if not, check for PHP errors, and then manually enable the Friendica log and check it for errors.

**Comment by myprivacymatters** [comment]
I tried again and it did not work. How do I check for PHP errors, @MrPetovan? I am not a total noob, but still have a lot to learn.

**Comment by MrPetovan** [comment]
Again, it depends on your hosting environment. For example, on my server it's in the Apache error log which on Debian is in `/var/log/apache2/error.log`. But your error log might be somewhere else.

**Comment by myprivacymatters** [comment]
Not able to secure logs that show anything beyond 02-01-21. How do I manually enable logging for Friendica? By the way, I am aware that you likely don't get paid to help, but know that it is VERY appreciated!!!

**Comment by myprivacymatters** [comment]
A cursory check of the database shows no privileges.  Wondering if that is something that needs correxted.

**Comment by myprivacymatters** [comment]
I meant corrected.  I am willing to build a new database if necessary.

**Comment by MrPetovan** [comment]
If you can, please start fresh with a new database, yes.

**Comment by myprivacymatters** [comment]
Should I name them something different or will that matter?

**Comment by MrPetovan** [comment]
Yes, please use another name, just to be sure.

**Comment by myprivacymatters** [comment]
Okay. New database and user created with all privileges. Do I change local.config.php via text editor or delete it and recreate it?

**Comment by MrPetovan** [comment]
Please delete it and go through the install wizard again.

**Comment by myprivacymatters** [comment]
Done. Should I set up the cron job first or try the registration?

**Comment by MrPetovan** [comment]
Registration first, it doesn't depend on the cronjob.

**Comment by myprivacymatters** [comment]
Same results...nothing.

**Comment by MrPetovan** [comment]
Thanks for trying, did you find the PHP/web server log yet?

For the Friendica log, please set the following keys in the `config/local.config.php` file:
```php
return [
    ...
    'system' => [
        ...
        'debugging' => true,
        'loglevel' => 'notice',
        'logfile' => 'friendica.log',
        ...
    ],
    ...
];
```
These config keys can then be set directly from the admin interface once your node will be up and running and the values in this file will be irrelevant.

**Comment by myprivacymatters** [comment]
Whenever I add that, it borks the file and nothing loads.

**Comment by myprivacymatters** [comment]
At this point, I trust you implicitly. Any chance I could merely send you my credentials and have you look at the setup?

**Comment by MrPetovan** [comment]
Absolutely, you can use my email address: hypolite@mrpetovan.com and if you aren't confortable sending your full credentials by email I can give you my Signal number by email.

**Comment by myprivacymatters** [comment]
What is your Signal number?

**Comment by myprivacymatters** [comment]
Request for Signal number sent!

**Comment by MrPetovan** [comment]
Solved off-band.
