### ISSUE TITLE
Export of contacts only exports a few of them

### ISSUE THREAD

**Issue by hellquist** [friendica/friendica#9920]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When exporting contacts (settings -> Export personal data -> Export contacts to CSV) to .csv file, far from all contacts in reality get exported.

I actually noticed this the first time when moving from friendica.feneas.org to my self-hosted instance.
I now experience the same thing again on my self-hosted instance.

On friendica.feneas.org I at the time had 75 contacts, but only 16 were in the export file. I thought at the time I must have done something wrong, but when testing to export a .csv file now on my self-hosted instance, I notice only 60 out of my (current) 137 contacts are actually in the .csv file, at all.

### Steps to Reproduce

1.  Look at contacts to see how many you have
2.  Export contacts to .csv file
3.  Open .csv file (Sublime Text) and count how many contacts you have in there

Actual Result:

* 16 out of 75 contacts were exported on friendica.feneas.org
* 60 out of 137 contacts were exported on my self-hosted instance

Expected Result:

* I would expect 75 out of 75 contacts to be exported from friendica.feneas.org
* I would expect 137 out of 137 contact to be exported from my self-hosted instance

### Platform Info

Friendica Version:

Friendica Source: Friendica 'Red Hot Poker' 2021.03-dev - 1398

PHP version: 7.4.3

SQL version: MySQL 8.0.23

I have no idea what set-up/version friendica.feneas.com is using.

**Comment by MrPetovan** [comment]
Thank you for the report!

**Comment by tobiasd** [comment]
For me (Friendica 2021.03-dev) the exported CSV file seems to contains all current active and archived contacts. I've only checked the number counts of these two contact _groups_ but they match.

**Comment by asherpen** [comment]
on 2022.10 I tried to Export contacts to CSV today and I got a CSV file with 78 contacts, which is the same number of my Followers  number. 
The accounts I'm following should be 205.

**Comment by MrPetovan** [comment]
The contact export was set up to export only followers and mutual friends, which explains the discrepancy. This is a quick fix.
