### ISSUE TITLE
Themes: frio: make network icon link to original post (instead of using a separate link icon cluttering the UI)

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9928]
Proposing to make the network icons link to the original post. Currently frio uses a separate link icon. Is this really needed? Using the network icon as link should be sufficient. The separate link icon would become obsolete and we could de-clutter the post UI.
Maybe the orignal though process was, to indicate users are leaving the site. But personally I do not see using a separate linkl icon as a good solution to that problem and rather this being expected behavior of the fediverse. It is part of being decentralized so there is no need to hide or highlight that fact.

<img width="1056" alt="network icon link" src="https://user-images.githubusercontent.com/5708172/107847457-0cd61c00-6dec-11eb-8a62-a7779dd8fa05.png">

**Comment by MrPetovan** [comment]
The icon makes it instantly visible that there's something more to a post. However I agree with @Extarys 's  private suggestion to only show it when it's an actual remote post. Local posts don't need this link and worse, it's a generic `/redir/...` link that isn't usable to share with people who aren't yourself.

But combining it with the network icon obfuscate the feature without reclaiming any valuable space.

**Comment by Extarys** [comment]
> But combining it with the network icon obfuscate the feature without reclaiming any valuable space.

I agree that we wouldn't put anything else there, but it would unclutter the UI a little.

I want to play with this, trying to move it to the time ago section of the header, but I'm afraid it'll then clutter that part with too much information.

I'll move some stuff around and post screenshots here.
Happy monday! :cat:

**Comment by AlfredSK** [comment]
Is it possible to give the needed hints for accessibility when the icon has two functions?

At the moment there is a label for the transport (e.g. Friendica AP) and a label for 'link to original'. I can imagine that would be hard to combine when there would be only one icon.

**Comment by MrPetovan** [comment]
A combined label would be "pleroma (AP) Link to source" ? I don't like this at all.

**Comment by foss-** [comment]
Really happy this could be addressed in https://github.com/friendica/friendica/pull/13633
Thanks for your work @Raroun ❤️
