### ISSUE TITLE
Frio Theme Customisation Inconsistent Login Page

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#9934]
- [X] I have searched open and closed issues for duplicates

### Bug Description

When using the Frio theme with predefined customisation (e.g. Accentuated Dark), the login widget on the login page is not customised. 

### Steps to Reproduce

Actual Result:
See here for example https://friendica.hubup.pro/

Expected Result:

Something like the  https://friendica.hubup.pro/network

### Platform Info

Friendica Version:
2021.03-dev

**Comment by Extarys** [comment]
Would it be possible to redirect users to the main login page with a `?out=/network` parameter to tell where to redirect the user after login?

**Comment by MrPetovan** [comment]
I don't understand the question, would you care to elaborate?

**Comment by Extarys** [comment]
@MrPetovan Sorry.
Right now when you go to `/network` we see a login page that is different from `/index.php`. Some websites, when they detect the user is on a page with insufficient privileges, they will redirect the user to the main login page (here it's `/index.php`) with extra arguments to where the user should be redirected after a successful login.

I hope this is clearer. I might try to find a more concrete example if needed.

**Comment by AlfredSK** [comment]
Ok. But I think this feature request is unrelated to the original issue.

Hint: users can set their default page after login by using the Startpage add-on.

**Comment by Extarys** [comment]
Well, no. The issue is that there is 2 different login page design depending on what page is requested when you're not logged in. Using this method would allow a more consistent navigation/login page.

**Comment by MrPetovan** [comment]
I see what you mean, there are a front page login widget, and a general purpose login page. Not all nodes will have a front page (for example single-user nodes like mine).

I still think people expect a login form on the front page when it is enabled so I don't think we can get rid of it.

**Comment by AndyHee** [comment]
I think this issue needs some further explanation. I'm aware there currently are no seasoned UX designers here.

The dark theme seems not be fully implemented for the **login widget** on the login page. 

![Screenshot_2021-11-04_20-20-33](https://user-images.githubusercontent.com/28751375/140321358-0e5bd6dc-4300-4800-bd07-8d6276949700.png)

Shouldn't the login widget reflect the _colour scheme_ ? I don't think it should be white but the type of **dark blue** or **aquamarine** that we see here below:

![Screenshot_2021-11-04_20-28-02](https://user-images.githubusercontent.com/28751375/140322596-4e316943-0010-4f12-b8f8-7e331d4b9f44.png)

That's all that's missing, probably relatively easy to adjust.

For the Frio mobile version it seems ok though.

![signal-2021-11-04-202442](https://user-images.githubusercontent.com/28751375/140323442-9672b01d-bf8f-4c78-96b4-0405c903b1a8.jpg)
