### ISSUE TITLE
bin/console storage move [Error] 

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9937]
- [X] I have searched open and closed issues for duplicates

### Bug Description

bin/console storage move
[Error] Der Datenbankspeicher konnte keine Daten einfügen

I switched it to Database some weeks ago, so new items should be stored in the DB. 
```
bin/console storage list
 Sel | Name                
-----------------------
     | Filesystem          
 *   | Database
 ```

Moving from Filesystem to Database is not possible. 

### Steps to Reproduce

1. Have your storage set to Filesystem. 
2. Try to move it to Database. 

Fault shows. 

It should move all files from Filesystem to Database. 

### Platform Info

Friendica Version: stable and current develop
I tried it some weeks ago with stable and now after the update to dev branch again, it does not work in both versions. 

Friendica Source: git

PHP version: 7.4.15

SQL version: mariadb  Ver 15.1 Distrib 10.5.8-MariaDB

**Comment by utzer** [comment]
@annando @tobiasd  would that be a bug to fix for the upcoming release? It was/is already present in the current stable and as well in the current dev branch. 

Oh, also would be grateful for any tip what to grep for in the log to see if there is some problem on my serverS.

**Comment by annando** [comment]
Does the user who executes the move command does have write access to the folders and files where the photos are stored by now? It is unlikely that this is some general bug, since I'm currently moving the photos on one of my servers as well (from the "photo" table to the "storage" table).

**Comment by utzer** [comment]
Yes, the user has rw access, but I am now just running a `sudo chown -R user:user /path` to make sure. (username=groupname)

Also I think I already did that the last time when it didn't work.

**Comment by utzer** [comment]
By the way, what should be the permission? I got this for files:
`-rw-rw---- 1 www www    0 16. Jun 2020  f59e28c1cd6c2112934d8e2c65a941d1918ce51457ad3d4162814413f90f`

**Comment by utzer** [comment]
> It is unlikely that this is some general bug, since I'm currently moving the photos on one of my servers as well

OK, I now tried on one of the servers, there is it working, but the other got some problem. I will check my php log on the one computer where it does not work. 

Besides that, have you got any tip on what I can look for in the Friendica log?

**Comment by utzer** [comment]
Ok, I think I got something, don't mind me for the moment.

**Comment by utzer** [comment]
OK, it was the "max_allowed_packet" that was to small. Thanks for confirming it works on your side, thanks for the helpful log output of Friendica, sorry for bothering.:-(
