### ISSUE TITLE
DB error 1064 - syntax error - unexpected '@', expecting $end

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9948]
- [X] I have searched open and closed issues for duplicates

### Bug Description
I found two of the following SQL syntax errors in my log.

```
DB Error {"code":1064,"error":"syntax error, unexpected '@', expecting $end","callstack":"Post::select, Content::getURIIdListBySearch, Index::content, call_user_func, Page::initContent, Page::run, App::runFrontend","params":"SELECT `uri-id` FROM `post-view` WHERE (`uri-id` IN (SELECT `uri-id` FROM `post-content` WHERE MATCH (`title`, `content-warning`, `body`) AGAINST ('xxxx@xxxxxxxworks.com' IN BOOLEAN MODE)) AND (NOT `private` OR (`private` AND `uid` = 4106)) AND (`network` IN ('apub', 'dfrn', 'dspr', 'stat') OR (`uid` = 4106 AND `uid` != 0))) GROUP BY `uri-id` ORDER BY `uri-id` DESC LIMIT 0, 40"} - {"file":"Database.php","line":662,"function":"p","uid":"5b01cd","process_id":1827771}
```

Right before the DB error I see some 'http error' messages (404) while trying to fetch some well-known endpoints followed by a 'no valid network found' error.

### Platform Info

Friendica Version:
2021.03-dev - database 1404/1404, post update 1400/1400

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
> InnoDB full-text search does not support the use of the @ symbol in boolean full-text searches. The @ symbol is reserved for use by the `@distance` proximity search operator.

https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html

So we need to replace them with spaces.

**Comment by akno77** [comment]
I came across the same issue today. I've got in my logs db errors like:

`syntax error, unexpected '@', expecting $end`

for queries like:

```
SELECT `uri-id` FROM `post-searchindex` WHERE (MATCH (`searchtext`) AGAINST ('https://mastodon.social/@someaccount' IN BOOLEAN MODE) AND (NOT `restricted` OR `uri-id` IN (SELECT `uri-id` FROM `post-user` WHERE `uid` = 3))) ORDER BY `uri-id` DESC LIMIT 0, 20
```
