### ISSUE TITLE
Improve Mainteance Page

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#9950]
While upgrading to the current develop, I'm forced to look onto the maintenance page while the database upgrade is on the way. And I think it would be good, if there would be a better explanation for the end users why they can't access the website than this: 

![Bildschirmfoto 2021-02-22 um 21 23 52](https://user-images.githubusercontent.com/18173881/108766006-dff4d800-7554-11eb-8518-1662f778d6b9.png)

The title "Service Unavailable" is quite large and prominent while "2021-02-22 19:36:41 UTC: executing post update 1395" is quite small and easy to overlook. I think it would be better to title it as "Maintenance - Database Update" and maybe a better understandable progress information. For example, if it's known what needs to be updated, then display all the necessary steps and the current position of what is currently worked on. 

For the traces of Exception thrown, I don't think that this is of interest for the end users. Maybe this can be hidden behind a collapseable/expandable element?

**Comment by MrPetovan** [comment]
Hi @ingoj , you are seeing the exception stack traces because you are the administrator of your node. End users do not see these.

As for updating the title of the maintenance page, it is a good idea.

**Comment by annando** [comment]
I think it would be better to rework the page. The callstack isn't needed, not even for the administrator. So the page should tell in the title that it is in maintenance and the text should provide more details. @MrPetovan would you like to work on this?

**Comment by MrPetovan** [comment]
I do believe the call stack is useful. We do ask admins to provide call stacks whenever they have an error, this is no different.

However, we can differentiate between different types of Exception and show user-appropriate data for this particular case.

**Comment by annando** [comment]
The maintenance information is no an unexpected error. It is an expected downtime. What purpose does a call stack serves in this specific case?

**Comment by MrPetovan** [comment]
I addressed that part in my second sentence. This page is currently a catch-all for frontend exceptions, and can be tailored depending on the exception.
