### ISSUE TITLE
Database issues after running mysqltuner

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#9954]
Already since the last stable release 2021.01: when running mysqltuner on your database, it will result in some strange effects and Mysql needs to be restarted afterwards... 

Before mysqltuner: 
![Bildschirmfoto 2021-02-23 um 22 14 47](https://user-images.githubusercontent.com/18173881/108909827-582ace80-7625-11eb-8b49-57473b7500ee.png)

After mysqltuner:
![Bildschirmfoto 2021-02-23 um 22 15 33](https://user-images.githubusercontent.com/18173881/108909843-5bbe5580-7625-11eb-9ed4-42141448b417.png)

Note how the table looks. Also the "Home" page shows a "User not found": 

![Bildschirmfoto 2021-02-23 um 22 17 36](https://user-images.githubusercontent.com/18173881/108909929-798bba80-7625-11eb-8d75-de0095a9cbdf.png)

Trace of that screenshot: 
```
Exception thrown in /var/www/net/nerdica.net/friendica/src/Module/Profile/Status.php:58
Stack trace:
#0 /var/www/net/nerdica.net/friendica/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content(Array)
#1 [internal function]: Friendica\Module\Profile\Index::content(Array)
#2 /var/www/net/nerdica.net/friendica/src/App/Page.php(333): call_user_func(Array, Array)
#3 /var/www/net/nerdica.net/friendica/src/App/Page.php(390): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#4 /var/www/net/nerdica.net/friendica/src/App.php(557): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Util\Profiler), Object(Friendica\Core\Config\PreloadConfig), Object(Friendica\Core\PConfig\PreloadPConfig))
#5 /var/www/net/nerdica.net/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\PreloadPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1614115043.3383)
#6 {main}
```

No idea how running mysqltuner can have this impact...

**Comment by MrPetovan** [comment]
I don't think mysqltuner changes anything to the server configuration and definitely nothing to Friendica so I'm even more befuddled than you.

**Comment by MrPetovan** [comment]
Can you verify your `users` table has the expected data?

**Comment by ghost** [comment]
Well, did that, but can't spot a problem there. The user is still existing in that state...

It's really strange, and as said, it worked in older versions like a half year ago. 

I guess I need to refer to a movie quote from Wargames: "The only winning move is not to play (with mysqltuner)". ;) 

But it would be good to know if this is revealing an issue in the Friendica DB or if it's maybe a bug in mysqltuner. Currently I only experience issues with the Friendica DB, but not with e.g. my Wordpress DBs.

**Comment by MrPetovan** [comment]
What does the log say when you get this error?

**Comment by MrPetovan** [comment]
Are you sure your database scheme is up to date?

**Comment by annando** [comment]
`mysqltuner.pl` doesn't perform any automated changes. And you should always have a look at every suggested change. Only when you know the impact, you should apply these changes.

Please perform a `bin/console dbstructure update -f` to be sure that your database structure is okay. Then set the loglevel at least to the "error" level and have a look for entries with "DB Error" in it.

**Comment by ghost** [comment]
> Are you sure your database scheme is up to date?

Yes, after updating to 2021.03-rc (Friendica 'Red Hot Poker' 2021.03-rc - 1406): 

```
# sudo -u www-data bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.

All pending post updates are done.
```

**Comment by ghost** [comment]
> `mysqltuner.pl` doesn't perform any automated changes. And you should always have a look at every suggested change. Only when you know the impact, you should apply these changes.

I didn't apply any changes. It's enough to just run mysqltuner and have it output its findings to have that impact. 

> Please perform a `bin/console dbstructure update -f` to be sure that your database structure is okay. Then set the loglevel at least to the "error" level and have a look for entries with "DB Error" in it.

This is the output: 

```
vserv1:/var/www/net/nerdica.net/friendica# bin/console dbstructure update -f

vserv1:/var/www/net/nerdica.net/friendica#
```

So, apparently no issues with the database, I'd guess... 

However, with the update to 2021.03-rc (and thus from -1405 to -1406) the issue seems to be gone. So I'm closing this now and will re-open when the issue should come back...
