### ISSUE TITLE
DB error 1064 - SQL sytax error when CleanItemUri is runnung

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9956]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Found this SQL syntax error in my log.

```
DB Error {"code":1064,"error":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1","callstack":"DBA::delete, CleanItemUri::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"DELETE FROM `item-uri` WHERE `id` IN ();"} - {"file":"Database.php","line":765,"function":"e","uid":"a53204","process_id":833566}
```

### Platform Info

Friendica Version:
2021.03-dev - db 1406 / pu 1400

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
Huh, I've never tried using IN with an empty list, I guess it doesn't work!

**Comment by annando** [comment]
This is fixed by https://github.com/friendica/friendica/pull/9959
