### ISSUE TITLE
PHP8 - Can't drop tables (via console.php)

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#9958]
I'm afraid this issue report is going to be pretty light on details - but I've just encountered an issue with php 8 and dropping tables via bin/console.php.  When running via PHP 8:

```
friendica@social ~/friendica $ !495
bin/console dbstructure drop -e
[Error] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails
DROP TABLE `item`;
friendica@social ~/friendica $
```

But it worked via PHP 7.4:

```
friendica@social ~/friendica $ php7.4 bin/console.php dbstructure drop -e
DROP TABLE `item`;
```

I'm not sure why the issue didn't log to the PHP cli error log.  There are some other fatal errors I will be adding to the php8 fatal errors issue #9498 right away, though.

**Comment by MrPetovan** [comment]
This is most peculiar since the error is thrown by the database and shouldn’t have any relationship with the PHP code or the interpreter’s version.

**Comment by annando** [comment]
I cannot imagine that this could have anything to do with PHP. Like @MrPetovan said: The error is thrown by the database. I can imagine however, that between those two calls the foreign key constraint vanished.

**Comment by realkinetix** [comment]
No worries - I don't think I can even replicate this now, so I'll close.  Thanks!
