### ISSUE TITLE
button breaks the theme

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#996]
addon: Smileybutton 
theme: diabook

**Comment by tobiasd** [comment]
This issue was addressed in https://github.com/friendica/friendica-addons/commit/9a1c783d74e6bea6fca49422e6106f7af23cfee5 for the main themes. Just tested it and only quattro seems to lack the button now. Looks good in duepunto and vier though.

**Comment by ddorian1** [comment]
I disabled it on quattro for the moment, because quattro needs to have some different HTML added. I will add that when I find the time to look into it.

**Comment by tobiasd** [comment]
For the other buttons it uses the ALT text IIRC

**Comment by vinzv** [comment]
_(I'm on master branch, FF68 Linux)_

As the original screenshot seems to be lost, here are new ones:
![image](https://user-images.githubusercontent.com/74432/63295096-22888500-c2cc-11e9-9904-eb9b1b3f37d1.png)
![image](https://user-images.githubusercontent.com/74432/63295136-37fdaf00-c2cc-11e9-9939-c7810d70f8e1.png)

It has two more issues:
1. Smilies can't be clicked
2. As soon as I type something the popup moves downwards:
![image](https://user-images.githubusercontent.com/74432/63295285-8e6aed80-c2cc-11e9-972b-14ff417e5e33.png)

**Comment by foss-** [comment]
Is this problem still a thing? Just checked and emoji picker works fine in frio. Paging @MrPetovan - can this be closed?
