### ISSUE TITLE
Internal server error when deleting a local user account

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9966]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When I try to delete a local user account in admin panel by clicking on the little trash can:

**Internal Server Error**
`'https://libranet.de is not a relative path, please use System::externalRedirectTo`

Stack trace:
```
Exception thrown in /var/www/html/libranet/src/App/BaseURL.php:451
Stack trace:
#0 /var/www/html/libranet/src/BaseModule.php(160): Friendica\App\BaseURL->redirect()
#1 /var/www/html/libranet/src/Module/Admin/Users/Index.php(89): Friendica\BaseModule::checkFormSecurityTokenRedirectOnError()
#2 [internal function]: Friendica\Module\Admin\Users\Index::content()
#3 /var/www/html/libranet/src/App/Page.php(333): call_user_func()
#4 /var/www/html/libranet/src/App/Page.php(390): Friendica\App\Page->initContent()
#5 /var/www/html/libranet/src/App.php(557): Friendica\App\Page->run()
#6 /var/www/html/libranet/index.php(42): Friendica\App->runFrontend()
#7 {main}
```

**Error info bubble:**
"The form security token was not correct. This probably happened because the form has been opened for too long (>3 hours) before submitting it."

But the page has been reloaded seconds before the deletion attempt.

**No PHP errors in PHP error log.**

Also, deleting user accounts via batch processing (mark multiple accounts and hit the delete button at the bottom of the page) is working.

### Steps to Reproduce

1.  go to admin/users
2.  hit the little trash can to delete an account
3.  observe the error page

### Platform Info
Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
Great! Now that I created the issue I tried it again (for the fourth time in the last 20 minutes). And guess what? It worked as expected.

I will leave it open. Because the exception looks a little bit concerning.

**Comment by AlfredSK** [comment]
I just had the same issue again. Found this issue. :-)

**This is the current URL when I try to delete a user account:**

`https://libranet.de/admin/users/active?o=-register_date`

**This is the linked URL of the little trash can:**

`https://libranet.de/admin/users/delete/4198?t=1622486445.39e6ccac.........` (shortened)

**This is the error message I get:**

`Internal Server Error 'https://libranet.de is not a relative path, please use System::externalRedirectTo`

**This is the exception and the stack trace:**

```
Exception thrown in .../src/App/BaseURL.php:451
Stack trace:
#0 .../src/BaseModule.php(190): Friendica\App\BaseURL->redirect()
#1 .../src/Module/Admin/Users/Index.php(89): Friendica\BaseModule::checkFormSecurityTokenRedirectOnError()
#2 [internal function]: Friendica\Module\Admin\Users\Index::content()
#3 .../src/App/Page.php(333): call_user_func()
#4 .../src/App/Page.php(390): Friendica\App\Page->initContent()
#5 .../src/App.php(567): Friendica\App\Page->run()
#6 .../index.php(42): Friendica\App->runFrontend()
#7 {main}
```

**Comment by AlfredSK** [comment]
Tested again on stable and develop. Works as expected. Looks like this is fixed. Closing.

**Comment by MrPetovan** [comment]
Self-fixing bugs, my favorite kind of bug.
