### ISSUE TITLE
Frio - Fix aspect ratio of videos 

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9969]
Since most Videos on all platforms have an aspect ratio of around 16:9 the thumbnails shouldn't be displayed in 1:1 aspect ratio. Please fix it, so previews are shown in 16:9 aspect ratio.

At the moment it looks so wrong and broken like this
![00_temp00](https://user-images.githubusercontent.com/24474762/109422329-69842a00-79db-11eb-9585-0b9982456ca9.jpg)

### Platform Info

Friendica Version: develop
Friendica Source:  git
PHP version: 7.4
SQL version: mariaDB latest Debian release

**Comment by foss-** [comment]
Isn't this a dupe of https://github.com/friendica/friendica/issues/9438?

**Comment by hoergen** [comment]
No it isn't The other issue is talking about fixing overlapping elements in the stream.
This issue is fixing the aspect ratio of the thumbnails. Different topic.

**Comment by foss-** [comment]
Right, would have assumed if using full width was fixed, wrong aspect ration may also be touched. But you are right, not the same problem. The issues are now cross-linked so maybe both will be fixed when code is touched.

**Comment by AlfredSK** [comment]
Do you have oembed enabled? I'm asking because I cannot reproduce this with oembed disabled. The only humble thing I have is the video has a 1:1 (or 4:3?) frame around it. But aspect ratio etc. is ok.

**Comment by foss-** [comment]
Does this problem effect all youtube videos you try to embed in a friendica post or only some?
If only some could you share the youtube URL for one of the problematic videos so it can easily be tested?

**Comment by hoergen** [comment]
> Do you have oembed enabled? I'm asking because I cannot reproduce this with oembed disabled. The only humble thing I have is the video has a 1:1 (or 4:3?) frame around it. But aspect ratio etc. is ok.

I have enabled it in the config, because the preview here was continously broken. But aside of this problem an oembed shouldn't change the aspect ratio.




> Does this problem effect all youtube video you try to embed in a friendica post or only some?
> If only some could you share the youtube URL for one of the problematic videos so it can easily be tested?

I tried to find some posts in my timeline with yt videos, but couldn't find one yet, so I can't answer your question currently.

**Comment by hoergen** [comment]
Update: tried it with a deactivated/activated oembed . The same effect,

**Comment by hoergen** [comment]
I think it is solved.
