### ISSUE TITLE
View 'friendica.post-thread-view' references invalid table(s) or column(s) or function(s)

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#9975]
After updating to the current RC I noticed DB backup failing with the following error:
```
mysqldump: Couldn't execute 'SHOW FIELDS FROM `post-thread-view`': View 'friendica.post-thread-view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them (1356)
```

If I try to run this query I get the same result:
```
MariaDB [friendica]> SHOW FIELDS FROM `post-thread-view`;
ERROR 1356 (HY000): View 'friendica.post-thread-view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

DB update did stuck during upgrade and I saw warning message in the admin panel telling me to run it manually by console which I did and everything seems to work well afterwards but this issue appeared. DB is 1406/1406, post update 1400/1400

**Comment by annando** [comment]
Which database server are you using? (Flavour, version)

**Comment by SpcCw** [comment]
@annando I use mariadb-server-10.3

**Comment by annando** [comment]
We renamed the old views. Please remove the "post-view" and "post-thread-view" by hand.

I guess we should add some automatic mode to remove old views.

**Comment by SpcCw** [comment]
Thanks, it worked!

> I guess we should add some automatic mode to remove old views.

Maybe add this clean-up functionality to `bin/console dbstructure drop` ?

**Comment by realkinetix** [comment]
Glad this was filed - figured I might be running in to a php8 issue, but found this instead.  Thanks @annando for the fix!
