### ISSUE TITLE
wrong name when resharing mastodon post

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9984]
- [x] I have searched open and closed issues for duplicates

### Bug Description
When I reshare a mastodon post, on top of the reshare, I see a link instead of my user name.

### Steps to Reproduce
Reshare a mastodon post and visit your "Status" page. (the House icon) 

Actual Result:

I see a link (`https://libranet.de/profile/xy`) instead of my user name.

Expected Result:

I expected to see my user name: `xy@libranet.de`

### Screenshots

![friendica-geteilt](https://user-images.githubusercontent.com/5753419/110078803-909a7d00-7d88-11eb-8624-a68a88caa308.jpg)

### Platform Info

Friendica Version:

Version 2021.03-rc
Datenbankversion 1407/1407
Post-Update-Version 1400/1400.

**Comment by annando** [comment]
I cannot reproduce this by now.

**Comment by haheute** [comment]
yes..  I have tried again (two times) right now, and both seemed to work. hmm..

**Comment by annando** [comment]
Air humidity? :grimacing:

**Comment by haheute** [comment]
I don't know.. or moon phase :-/  maybe close and reopen if necessary?

**Comment by AlfredSK** [comment]
I've seen that too every now and then. But the behavior isn't reproducible and swiftly vanishes on its own. 🤷

Could be caused by Aurora Borealis because server is located in Finland. :-)
