### ISSUE TITLE
The word "post" in notifications doesn't seem to be translatable

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#9992]
- [y] I have searched open and closed issues for duplicates

### Bug Description

The word "post" in notifications list doesn't seem to be translatable - or I don't know where to find it. I tried searching for it in Transifex and switching between languages.

Leaving it untranslated makes it look especially weird with languages using non-Latin alphabet.

![image](https://user-images.githubusercontent.com/35988439/110214645-a0b07a80-7eb6-11eb-9ec1-f7bcf005be52.png)

**Comment by MrPetovan** [comment]
Please look for `text:[post]` in the `messages.po` resource in Transifex, it shows to me as message number 1030.

**Comment by SpcCw** [comment]
@MrPetovan - then it doesn't work for some reason. In the screenshot above there are examples for Russian and French. Both translations are present in Transifex. Russian was submitted 8 years ago, not sure about French as I am not on the team but it is there. So either the string is not translatable or is translated somewhere else...

--------- French ---------:
![image](https://user-images.githubusercontent.com/35988439/110218951-761dec00-7ecd-11eb-823f-0d35eec1fe5c.png)

--------- Russian -------:
![image](https://user-images.githubusercontent.com/35988439/110218995-b41b1000-7ecd-11eb-8a06-24eb58ccbce5.png)

**Comment by MrPetovan** [comment]
Both translations are present in the RC branch:
RU: https://github.com/friendica/friendica/blob/953d0ed72df2f2ebb011277c435b5dc21b11bb63/view/lang/ru/strings.php#L1063

FR: https://github.com/friendica/friendica/blob/953d0ed72df2f2ebb011277c435b5dc21b11bb63/view/lang/fr/strings.php#L1060

So I really am not sure why it doesn't work properly.

**Comment by annando** [comment]
In the German translation this word is translated, so there doesn't seem to be a general problem.

**Comment by SpcCw** [comment]
@annando - are you sure? Maybe it is version dependent?

Here's 2021.03-rc:
![image](https://user-images.githubusercontent.com/35988439/110231732-9039e780-7f2a-11eb-8d22-98b86527e04b.png)

**Comment by annando** [comment]
I'm on the latest RC:
![Bildschirmfoto vom 2021-03-07 07-59-26](https://user-images.githubusercontent.com/844208/110232001-2ebe4c80-7f1b-11eb-8e7d-ae71e48bebf2.png)

But since I see that it isn't working on your system, we have to have a look what's so special with this word.

Update: I guess I know why this is the case. The translation of the word "post" is not done in the same context as the rest.

**Comment by SpcCw** [comment]
@annando - my previous screenshot was from mordor.social and the one below is from my system. Now I also notice weird round brackets around this word which absent on my system but preset on some others.

![image](https://user-images.githubusercontent.com/35988439/110232124-e576f880-7f2c-11eb-95b4-844acbe1f38f.png)

**Comment by AlfredSK** [comment]
Could it be related to this?
https://github.com/friendica/friendica/issues/9749#issuecomment-774666225

**Comment by annando** [comment]
@AlfredSK no.

**Comment by AlfredSK** [comment]
Ok. At least I have tried.
