### ISSUE TITLE
DB Log - Worker - Compacting error

### ISSUE THREAD

**Issue by hellquist** [friendica/friendica#9998]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I was asked to submit my database errors [here by Michael Vogel](https://pirati.ca/display/ec054ce7-7760-224c-d426-08d369931464?owt=2d4546f4deb077df2ad1afb9455448f6). I can't really explain them, or what goes wrong, but was told the errors themselves contain all the needed information, so here it goes:

```2021-03-06T03:05:42Z worker [ERROR]: compacting error {"worker_id":"2c2be33","worker_cmd":"ContactDiscovery"} - {"file":"JsonLD.php","line":153,"function":"compact","uid":"ee1f5e","process_id":2284585}```

I also get a bunch of other Index compacting errors but that is already filed by someone else in #9544

### Platform Info

Friendica Version:

Friendica Source: Friendica 'Red Hot Poker' 2021.03-dev - 1406

PHP version: 7.4.3

SQL version: 8.0.23

**Comment by annando** [comment]
This one doesn't matter. It isn't a database error but simply some log entry. This only means that the system fetched an activitypub profile that has got invalid data. We cannot do anything about this situation.

Update: What do we do about this issue? @hellquist do you mind if I close it?

**Comment by hellquist** [comment]
> Update: What do we do about this issue? @hellquist do you mind if I close it?

I absolutely don't mind. I am merely trying to be helpful, ideally without being in the way and still contribute with what I can contribute with (right now, reporting), whilst "learning as I go", so you guys do what you need to do (and tell me if I stop being helpful and become a nuisance, hehe). :)
